### ISSUE TITLE
Can we make a web-based log plotter?

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1005]
Being able to provide more information than the standard dataweb page might be a selling point.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1007.  Created by mjc23 on 2015-12-10T08:14:09, last modified: 2016-01-25T15:17:29_

**Comment by KathrynBaker** [comment]
The Grafana work covers this
