### ISSUE TITLE
Update the CAEN IOC to the most recent version

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1006]
As a support person I would like to update the CAEN IOC to the most recent version from the Canadian Light Source (?http://exshare.lightsource.ca/OpenSource/Software/Forms/AllItems.aspx?RootFolder=%2fOpenSource%2fSoftware%2fEPICS%2fHVCAENx527%2fHVCAENx527-1-3&FolderCTID=&View=%7b7B5A5CD2-E60E-4498-AF3B-EA1AED6AF287%7d) 

== Acceptance Criteria ==
1. The new IOC is being used in the background

== Notes ==
1. Updating this software will mean that the OPIs will have to be reworked, if the new IOC works a new ticket will be needed to update the OPIs
1. Try it first.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1008.  Created by kvlb23 on 2015-12-11T15:04:16, last modified: 2016-01-31T23:00:30_

**Comment by KathrynBaker** [comment]
This was reviewed and merged a while back, the new IOC is in use, but whether it is in a final version is still to be decided
