### ISSUE TITLE
"waitformove" return alarm status for limit violations

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1007]
The "waitformove" command should indicate if any motors have violated include any soft limits (.LVIO motor record field) via the alarms status record.

#### Notes
1. This is a follow-on to #991

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1009.  Created by skn09965 on 2015-12-11T17:29:30, last modified: 2015-12-11T17:29:30_

**Comment by IsabellaRey** [comment]
Started looking at this, but haven't done any actual work on it yet, so I'm moving it back to Ready while I work on another story.
Looks fairly straightforward, the LVIO field is a flag that indicates whether there has been a soft limit violation, see how the waitfor_move already handles printing of motors in alarm status

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/genie_python#28
Details on how to test on the pull request

**Comment by AdrianPotter** [comment]
Works well. Just a couple of points:

1) check_limit_violations (and check_alarms) both throw an exception when I pass in None
2) In genie_simulate, check_limit_violations may as well create and return the object on the same line. Unlike check_alarms, there is no benefit in distinguishing the objects in the return.
3) In genie_epics_api, the check_alarms and check_limit_violations is an almost direct copy. It might be easier to have a method to get the PV fields for a given field (e.v. LVIO) and then do a list comprehension to filter them For instance

```
minor = [s[0] for s in get_pv_fields_from_blocks(args) if s[1]=="MINOR"]
```

assuming s is a tuple  e.g. `("block_name","MINOR")`

**Comment by IsabellaRey** [comment]
Fixed
