### ISSUE TITLE
Indicate which perspective is open

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1018]
As an IBEX user I would like to know which perspective I have open. This could be done by highlighting the appropriate perspective switcher button.

This will help usability, and particularly help to show when a user has got to the Log Plotter from right clicking on a block and choosing 'Display Block History'.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1020.  Created by whb43145 on 2015-12-24T10:41:30, last modified: 2016-02-04T08:35:19_

**Comment by KathrynBaker** [comment]
PR has been merged
