### ISSUE TITLE
GUI: Scripting window improvements

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1019]
The scripting window has some options for creating new consoles. 
If we want allow opening of more than one console then the option to open a PyDev console should be left where it is, but it should not offer up the option of opening a Jython console.

Can we remove some of the icons from the top (save, clear console, pin console)?  **Yes, we want to remove some of these.**
Can we remove the "select python type" dialog which appears when we create a new console?  **Yes, we do want to remove this option.**
Can we warn the user before he or she kills a console?  **Yes, we do want to do this.**
Do we want a similar warning if when interrupting a script?  **Yes, we do want to do this.**

Note to developer: the buttons are provided by the Eclipse !ConsoleView, not anything from !PyDev. Matt: I am not completely sure of this.

We will almost certainly have to fork and build our own version of PyDev to achieve the behaviour we want.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1021.  Created by whb43145 on 2015-12-24T15:51:43, last modified: 2016-01-25T15:17:29_

**Comment by kjwoodsISIS** [comment]
Break down into smaller tickets:
1. Fork it & build it
2. Answer & do each of the questions above.
Do these as separate tickets.

**Comment by kjwoodsISIS** [comment]
Close this issue when #1153 and #1154 are done.

**Comment by Tom-Willemsen** [comment]
Reraised by HRPD during a sprint demo, but it is likely that this will be superseded by NICOS shortly.

**Comment by kjwoodsISIS** [comment]
This ticket will be superseded by a number of other tickets. No further need for this ticket to remain open.
