### ISSUE TITLE
Hardcoded path to Python

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1021]
The path to (Genie) Python is currently harcoded to C:\Instrument\Apps\Python. This means it does not work on Linux, and it also may want to be changed on Windows.

##### Options
There are a few options to fix this:
1. Allow access to the preferences screen in IBEX (to see this exists go Scripting -> Plotting -> Click the arrow next to 'Open Console' -> !PyDev Console -> Configure interactive console preferences)
1. Does removing the hardcoded setting bring up the prompt to choose the path?
1. Have hardcoded options for Windows and Linux
1. Other ...?

##### Proposed Solution
At the Sprint pre-planning meeting on 17th March 2016, we agreed that the most appropriate solution was to use a relative path name - that way it works on both Windows & Linux.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1023.  Created by whb43145 on 2016-01-05T10:43:51, last modified: 2016-01-25T15:17:29_

**Comment by ianbush** [comment]
A better solution suggested was to keep the Python (with genie_python) folder relative to the client. This should make it possible to keep it fixed on Windows and Linux.

**Comment by kjwoodsISIS** [comment]
This issue is now complete.
