### ISSUE TITLE
BlockServer: Separate out functionality

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1025]
Dominic created a module that only creates a Block Rules PV if requested. This easily allows the PV to be optional or a site specific (or even instrument specfic) functionality to be used instead.

In a similar way other BlockServer functionality could be separated out to make it more flexible for the both us and the ESS to use.

There are other potential candidates for the same treatment, for example:
- run-control (see #1064)
- starting and stopping IOCs (the ESS may not have the freedom to start and stop IOCs) (see #1065)
- database communication?
- archiver
- bumpstrips
- ...

Ultimately the block_server.py file will only create the core PVs and the site/instrument specific ones will instead be created on-the-fly.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1027.  Created by mjc23 on 2016-01-07T14:20:00, last modified: 2016-01-25T15:17:29_

**Comment by kjwoodsISIS** [comment]
This story can be closed when all the child issues are closed.

**Comment by Tom-Willemsen** [comment]
Separation listed in acceptance criteria have been achieved:
- run-control -> RUNCTRL
- starting and stopping IOCs -> ProcServControl, see e.g. https://github.com/ISISComputingGroup/IBEX/issues/8558 for improvements made
- database communication -> DBSVR
- archiver -> ARBLOCK/ARINST currently, new archiver being investigated
- bumpstrips -> not part of BLOCKSVR
