### ISSUE TITLE
Is the flashing Alarm button too annoying?

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1031]
It is quite annoying first thing in the morning. Especially if the IOC log is flashing too and they are out of sync.

Though it does draw attention well, maybe continuously red (or orange when there is a warning) would be better and just as effective?

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1033.  Created by mjc23 on 2016-01-12T09:27:18, last modified: 2016-01-29T16:48:03_

**Comment by kjwoodsISIS** [comment]
_Trac comment by kvlb23 on 2016-01-29 16:48:03:_

I've actually added the code for this whilst looking into the perspective highlighting - after all I am likely to be changing the same files anyway.

**Comment by KathrynBaker** [comment]
PR has been merged
