### ISSUE TITLE
Add unit tests for uk.ac.stfc.isis.ibex.epics.writing

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1032]
As a developer I would like some unit tests for the Writable classes in uk.ac.stfc.isis.ibex.epics.writing, similarly to #847.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1034.  Created by whb43145 on 2016-01-14T15:04:32, last modified: 2016-01-28T11:52:57_

**Comment by kjwoodsISIS** [comment]
Ask Ian to do this, in collaboration with someone else - to share the knowledge.

**Comment by IsabellaRey** [comment]
Pull request: ISISComputingGroup/ibex_gui#211
