### ISSUE TITLE
GUI: Stop Searching For Nameless Synoptic

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1033]
The GUI is still searching for the PV:

%MYPVPREFIX%CS:BLOCKSERVER:SYNOPTICS::GET

This can be seen using casnooper and should not be happening.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1035.  Created by ffv81422 on 2016-01-18T10:50:37, last modified: 2016-02-11T16:42:21_

**Comment by kjwoodsISIS** [comment]
_Trac comment by whb43145 on 2016-02-11 16:42:21:_

I belive this is fixed by #1037. When reviewing please verify this, e.g. by running:

`casnooper -t60 -p0 -c0 > casnooper.txt`

**Comment by KathrynBaker** [comment]
I checked this, it worked
