### ISSUE TITLE
Synoptic: Not clearing when connecting to a non-running instrument

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1035]
If you select a synoptic then switch to an instrument that is not running (i.e. not running EPICS) the synoptics from the previous instrument are still listed and the synoptic still shown.

Also, if one creates a new synoptic on DEMO it does not show up in the list, unless one restarts IBEX or switches to another instrument and back again.

== Notes ==
1. Initial assessment is that this is quite a complex issue.  It probably needs to be split into two (or more) tickets.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1037.  Created by mjc23 on 2016-01-18T11:27:37, last modified: 2016-02-04T09:53:05_

**Comment by kjwoodsISIS** [comment]
_Trac comment by whb43145 on 2016-02-04 09:53:05:_

This was going to be split into 2 tickets, but was left as one as a lot of changes to the synoptic behaviour were made.

**Comment by KathrynBaker** [comment]
Was (amusingly) fixed and merged when trac issue 1037 was fixed (the git issue is probably 1039)
