### ISSUE TITLE
NICOS: Investigate dependency on Devices/Setups

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1038]
NICOS has it's own version of configurations and devices. These should be investigated to see how much we can disable without breaking NICOS functionality

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1040.  Created by ffv81422 on 2016-01-20T10:42:31, last modified: 2016-01-28T11:26:30_

**Comment by kjwoodsISIS** [comment]
When Michael Wedel visited in early Feb we ran a quick test.  Seems that no particular configuration is needed.

**Comment by kjwoodsISIS** [comment]
Create a working example with NDXDEMO.

**Comment by IsabellaRey** [comment]
NOTE: a Nicos instrument IbexTestInstrument was created as part of #1039. This was copied from demo, and it's simply adding genie_python to the imported modules. 

This instrument would be a good place to start playing with cutting back what we don't need.

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/nicos-core#2

**Comment by John-Holt-Tessella** [comment]
I can run nicos demon on my machine and connect with the GUI. I can get blocks() to check it worked.
