### ISSUE TITLE
NICOS: Add genie_python commands

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1039]
NICOS already runs any generic python commands but also has an idea of what commands are available to the user. The genie_python commands should be added to this list.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1041.  Created by ffv81422 on 2016-01-20T10:43:44, last modified: 2016-01-28T11:26:30_

**Comment by kjwoodsISIS** [comment]
May need nothing more than adding a directory in the right place.
Worth checking.

**Comment by kjwoodsISIS** [comment]
We want to keep at least some of the original NICOS commands, as well as genie_python.
May be sufficient to merely add genie-python commands.

**Comment by IsabellaRey** [comment]
It should be enough to tag the genie_python commands we want to include with the same @usercommand decorator used by NICOS. The genie_python library could be imported by defining an appropriate configuration in a system.py file.

**Comment by IsabellaRey** [comment]
See pull requests ISISComputingGroup/genie_python#20 and ISISComputingGroup/nicos-core#1
