### ISSUE TITLE
MUON FRONT END: OPIs

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1042]
As an instrument scientist I'd like a friendly GUI screen to interact with my power supplies.

#### Acceptance Criteria
1. OPIs exist as appropriate for the TDK Lambda Genesys, Danfysik 8000 and Danfysik 9000

#### Notes
1. The creation of the IOCs are in #980, #982, #983

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1044.  Created by kvlb23 on 2016-01-21T17:16:57, last modified: 2016-01-28T11:50:38_

**Comment by John-Holt-Tessella** [comment]
Additional acceptance criteria for changes in KEPCO OPI. 

Acceptance Criteria:
1. Voltage correctly labels voltage and has correct units
2. Current correctly labels current
3. Instrument Ident is connected
4. Macro with instrument IOC_NUM available

General
1. On selecting a component on a synoptic the correct component target details are selected

Useful knowledge for testing:
Set in globals.txt: 
GENESYS_01__SIMULATE=1
GENESYS_01__PORT1=NUL
GENESYS_01__ADDR1=1

Once IOC are started set simulation mode via:
caput %MYPVPREFIX%KEPCO_01:SIM 1
caput %MYPVPREFIX%DFKPS_01:SIM 1
caput  %MYPVPREFIX%GENESYS_01:1:SIM 1

On Danfysik:
To alter the interlock  use:
Interlocked: caput %MYPVPREFIX%DFKPS_01:SIM:STA 65535
OK: caput %MYPVPREFIX%DFKPS_01:SIM:STA 0

To alter current
caput  %MYPVPREFIX%DFKPS_01:SIM:CURR 1

To alter voltage
caput  %MYPVPREFIX%DFKPS_01:SIM:VOLT 1

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/214
