### ISSUE TITLE
MUON FRONT END: IBEX GUI: Changes for the initial tests

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1043]
As an instrument scientist I want to be able to run an IBEX GUI client to access the Muon Front End controls

== Acceptance Criteria ==
1. MUONFE is added to the drop down list of instruments

== Notes ==
1. The power supply OPIs should be made available via a synoptic
2. The OPI creation is covered in #1042, and should cover note 1

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1045.  Created by kvlb23 on 2016-01-21T17:30:31, last modified: 2016-01-28T11:50:38_

**Comment by KathrynBaker** [comment]
Name should probably be MUONFE by the looks of things, without the underscore.

**Comment by IsabellaRey** [comment]
Pull Request: ISISComputingGroup/ibex_gui#196
