### ISSUE TITLE
GUI: Convert Group Editing to use View Models

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1044]
A lot of the code in the config editor does not use View Models despite involving large amounts of logic. This makes code hard to extend and hard to understand in places. The first canditate for refactoring should be the GroupsEditingPanel.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1046.  Created by ffv81422 on 2016-01-22T10:25:09, last modified: 2016-01-28T11:33:51_

**Comment by ianbush** [comment]
ISISComputingGroup/ibex_gui#193

**Comment by John-Holt-Tessella** [comment]
Reviewing: John
