### ISSUE TITLE
Jenkins: Build every inst_server PR

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1046]
As a developer it would be nice for PRs on the inst_servers to be automatically tested when I first create them. See #1041 for the same done on the GUI.
##### Notes
1. This will be harder than the GUI as the inst_servers rely on paths + code outside of their branch

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1048.  Created by ffv81422 on 2016-01-25T16:30:20, last modified: 2016-01-28T11:34:57_

**Comment by AdrianPotter** [comment]
What is impeding this ticket?

**Comment by DominicOram** [comment]
I'm not sure. I had a brief look at it before I left for RAL space but as far as I'm aware it's not been looked at since

**Comment by AdrianPotter** [comment]
Moving back to backlog. Nothing impeding it but it's not something we are prioritising right now

**Comment by mattclarke** [comment]
See here to review:

http://epics-jenkins.isis.rl.ac.uk/job/inst_servers_pr_pipeline/

**Comment by mattclarke** [comment]
Added ticket to fix database server tests. I'll check the other tests tomorrow and create tickets if necessary.
