### ISSUE TITLE
Motion Setpoints needs to provide access to the alarm state

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1048]
If one of the underlying motors goes into alarm then the associated BLOCK needs to be able to report this.

Currently caget %MYPVPREFIX%CS:SB:SAMPLE_POSN.SEVR returns its own alarm not the underlying alarm.

BTW: is there a easy way to put a simulated motor into alarm?

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1050.  Created by mjc23 on 2016-01-27T09:48:37, last modified: 2016-01-28T11:38:39_

**Comment by kjwoodsISIS** [comment]
Alarms viewdoesn't manage Blocks (IOCs & PVs but not Blocks).

**Comment by John-Holt-Tessella** [comment]
Need to ask about this on Monday

**Comment by John-Holt-Tessella** [comment]
To put a motor in alarm simply set its lo limit to be above its current position

See #1157 for display change.

Acceptance Test:
1. Set up a galil IOC (6 for preference)
1. Create a block on the setpoint. (This has a Pv like LKUP:MON3:POSN)
1. Monitor both the block and set point
1. Edit the alarm status 
1 Assert that the block and setpoint go into alarm

This can be done using the synoptic view, e.g. using in out synoptic component
