### ISSUE TITLE
GUI: PV Selection for Blocks: Facility PVs should not default to local

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1049]
As a user I don't want to have to uncheck the local check box when I select a facility PV

== Acceptance Criteria ==
1. Facility PVs when selected from the lookup are not recorded as local

== Notes ==
1. This probably just requires a check that the PV entered is not in the list of Facility interest level PVs when the PV is entered on to the PV address field on the Block Configuration page

**Comment by KathrynBaker** [comment]
PR has been merged
