### ISSUE TITLE
GUI: Changes to make to the Instrument Switcher

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1052]
As an IBEX user there are a few changes that would make the interaction with the Instrument Switcher interface (Menu > IBEX > Switch Instrument) more useful.

##### Suggested changes
1. Ability to type an instrument name not just click to one, this could allow for easy searching of a long list of instruments in the future, or connection to 'unlisted' machines, such as other development systems.
2. Whilst the local system is always at the top of the list, and this is helpful, it might be nice to be have the rest of the list in alphabetical order, as this would make it easier to find an entry as the list grows. An extension of this could be to have the top 5 most frequently visited instruments at the top as well, so you would have localhost, most frequent 1 - 5, everything else alphabetically.
3. The list of instruments to display might be best suited to be a PV or parametrised in some way so that the visible list does not require a new client when instruments are added. The suggested name for this list would be some variation on IBEX Targets, as these will not necessarily all be instruments.
4. It would be good if the list could give an indication if the instrument EPICS server is running, or not. E.g. after the name there could be something like `ServerName (NOT PRESENT)` when the blockserver of ServerName is not available.

This issue has been broken down into 4 smaller issues: #1092, #1093, #1094, #1095

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1054.  Created by kvlb23 on 2016-01-29T15:50:46, last modified: 2016-01-29T15:50:46_

**Comment by AdrianPotter** [comment]
Closing in favour of not having a separate ticket for remaining two open issues
