### ISSUE TITLE
Synoptics with long names not available remotely

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1053]
Synoptics with long names do not seem to be available remotely. For example on DEMO there are the snyoptics Larmor and Larmor_Changer_Eurotherm_Julabo.

Remotely `caget IN:DEMO:CS:BLOCKSERVER:SYNOPTICS:LARMOR:GET` works but `caget IN:DEMO:CS:BLOCKSERVER:SYNOPTICS:LARMOR_CHANGER_EUROTHERM_JULABO:GET` does not.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1055.  Created by whb43145 on 2016-02-01T12:31:12, last modified: 2016-02-01T12:31:12_

**Comment by FreddieAkeroyd** [comment]
PV names are max 60 characters, the long name is over this length. I suspect the blockserver, being a channel access server, is allowing a longer name but the epics gateway (for remote access) is not. Options for longer names would be:

* Move synoptics to a shorter namespace e.g. IN:DEMO:CS:SNPT:   and do we need :GET (or can it be shortened too)

**Comment by kjwoodsISIS** [comment]
Create a "SYNOPTICS" name space.  Limit length to 30 characters in the GUI.

**Comment by IsabellaRey** [comment]
See pull requests:
ISISComputingGroup/EPICS-inst_servers#43 for the blockserver
ISISComputingGroup/ibex_gui#219 for the GUI
ISISComputingGroup/ibex_system_tests#3 for the UI system tests

**Comment by IsabellaRey** [comment]
After reviewing, please move the ticket to the Impeded column

**Comment by John-Holt-Tessella** [comment]
Review passed

**Comment by IsabellaRey** [comment]
In view of the upcoming release, I have picked this ticket up again.
I have merged the master branch (for the blockserver) into the current branch, and refactored the way the PV names are created: there is now a pv_names file in the core module.

**Comment by John-Holt-Tessella** [comment]
Need to merge the system tests, I will do this tomorrow (23rd).
