### ISSUE TITLE
Updates to Eclipse Developer's Edition

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1054]
More updates:

1. Get standard Eclipse updates
1. Go to Window > Preferences > Java > Code Style > Formatter, Edit the active profile (hopefuly the IBEX one), Go to the comments tab, Uncheck the box `New line after @param tags`(edited)
1. Any more...?

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1056.  Created by whb43145 on 2016-02-02T15:57:15, last modified: 2016-02-02T15:57:15_

**Comment by ianbush** [comment]
A new version was created as part of #1108 to also include the RCP Testing Tool plugin, as well as the changes here.
