### ISSUE TITLE
Synoptic components with the same name all point to the same target

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1055]
To reproduce create a synoptic and a number of components, without changing the names from the default. Add targets to some or all of the components, while leaving them as unknown type.

Now save the synoptic and open it. Clicking any of the components will open the same target, regardless of how each one is set. In the editor the components still have the correct target.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1057.  Created by whb43145 on 2016-02-10T14:17:46, last modified: 2016-02-10T14:17:46_

**Comment by kjwoodsISIS** [comment]
Component names should be unique.

**Comment by ianbush** [comment]
See - ISISComputingGroup/ibex_gui#185
