### ISSUE TITLE
Path in scripting window for Linux

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1058]
As a Linux user I would like my path to be set correctly in the scripting window.

After #1026 is completed the Windows paths should be correct. Some more thought needs to go in to getting the Linux ones right.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1060.  Created by whb43145 on 2016-02-11T13:45:32, last modified: 2016-02-11T13:45:32_

**Comment by kjwoodsISIS** [comment]
Should just work if genie_python is correctly installed.
Just need to check and fix, if required.

**Comment by John-Holt-Tessella** [comment]
Yes path is:
os.getenv("PATH")
Out[7]: '/home/vagrant/from_script/EPICS/base/master/bin/linux-x86_64;C:\\Instrument\\Apps\\EPICS_UTILS;/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/vagrant/EPICS/base/bin/linux-x86_64:/home/vagrant/.local/bin/:/vagrant/EPICS/base/bin/linux-x86_64:/home/vagrant/.local/bin/'

PATH is expanded. Note the windows path in here. I will look at fixing this.

**Comment by John-Holt-Tessella** [comment]
Paths are set in `uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java` there should be a linux version of this. Put in ticker #1204

**Comment by John-Holt-Tessella** [comment]
NB no review needed no changes made

**Comment by IsabellaRey** [comment]
Reviewing. Checking instructions of first paragraph on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/building-on-linux

**Comment by IsabellaRey** [comment]
Added some extra comments on the instructions as part of the review
