### ISSUE TITLE
Display beam status graphically

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1061]
As a user, I want to see the beam status displayed graphically. As a support person, I don't want to have to display the beam status via the internal Eclipse browser (it doesn't run on Linux and leaks memory on Windows).

#### Acceptance Criteria
1. The beam status is displayed graphically.
2. The beam status for TS21 and TS2 are overlayed on the same graph.
3. There are 1-hour views and 1-day views of the beam status. 

#### Notes
1. This ticket originates from #1020.
2. We could use the Log Plotter to display the beam status.
3. Historical data (for the 1-day & 1-hour views) should be available from the archive database.

**Comment by AdrianPotter** [comment]
I've created a new ticket, 1143, for combining the 2 status graphs following discussion at the sprint review meeting on 21/4
