### ISSUE TITLE
Display MCR News as simple text

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1062]
As a user, I want to see the MCR News. As a support person, I don't want to have to display the MCR News via the internal Eclipse browser (it doesn't run on Linux and leaks memory on Windows). It is sufficient to display the MCR News as simple text.

#### Acceptance Criteria
1.  The MCR News is displayed as simple text.
2.  The MCR News is refreshed periodically. 

#### Notes
1.  This ticket originates from #1020.
2.  Refresh rate should be at least as frequent as the web-based MCR News. 
3.  The MCR news will be available via channel access from the central server

**Comment by AdrianPotter** [comment]
Checked on master branch at revision ca7ea07.

The MCR news is displayed in the MCR news tab as simple text now. The formatting is as I would expect. 

The text is being updated periodically as described. The update period is currently 30s which seems appropriate to keep the information current without putting undue strain on the system.

**Comment by IsabellaRey** [comment]
Being reviewed
