### ISSUE TITLE
Launch Default Browser for Web Links

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1063]
As a support person, I want the user's default browser to be launched when the user clicks on a web-link, so that IBEX does not need to use the internal Eclipse browser (it doesn't run on Linux and leaks memory on Windows). IBEX should not care if the user prefers to use IE, Firefox, Chrome, ... <whatever>.
Acceptance Criteria
1.  On clicking a web-link, IBEX launches the user's default browser. 

Notes
1.  This ticket originates from #1020.
2.  The same mechanism should be used on the Linux version of IBEX.
3.  The list of links displayed by the web-links perpsective is stored here http://dataweb.isis.rl.ac.uk/SeciLinks/default.htm. IBEX could download that page and grab the links out of it, and display them for the user to click. However, if the links chnage only infrequently we could get away with a hardcoded list of links in the first instance.

**Comment by ianbush** [comment]
ISISComputingGroup/ibex_gui#191
