### ISSUE TITLE
IMAT: IOC & OPI for load cell meter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1079]
As a scientist, I need IBEX to support the Mantracourt ADW15 load cell meter, so that I can monitor the load on the IMAT sample stack.
#### Acceptance Criteria
1. I can view the load on the IMAT sample stack via the IBEX GUI.
2. I can query the load on the IMAT sample stack via a script.
#### Notes
1. Web page: [Mantracourt  ADW15 ](http://www.mantracourt.com/products/digital-indicators/weighing-indicator-with-analogue-data#specifications)
2. We will need a t least an IOC and OPI.  Need to determine if we need a separate driver.
3. Need to determine if the device needs to be calibrated and, if so, how?

**Comment by KathrynBaker** [comment]
duplicated by #5860 - which has more technical information
