### ISSUE TITLE
Conventions for Angles on Single Axis Rotation Stages

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1084]
As a scientist, I need IBEX to support different conventions for angles on single axis rotation stages, so that I can control the rotation in a natural fashion.
#### Acceptance Criteria
1. TBD
2. TBD.
#### Notes
1. The most obvious conventions are:
   1. Rotation range: 0 - 360 degrees
   2. Rotation range: -180 - +180 degrees<br>
      Perhaps the simplest thing to do is provide a checkbox on the OPI to say which convention you want to use.  Maybe also include a clear statement, so that the user is in no doubt about the selected convention.
2. What if the underlying motor supports only one convention?  Is that likely/possible?.
3. What if the rotation range is greater than 360 degrees?(assuming that the rotation stage can support such a thing without getting cables tangled etc.)
4. What about other more restrictive ranges?  For example: Rotation range: 45 - 135 degrees.
5. This issue assumes a single axis of rotation.  How do we handle multiple rotation axis?  With a separate issue?  What are the supported conventions?
6. Which instruments use only single axis rotation stages?

**Comment by KathrynBaker** [comment]
SAG did not see the benefit of this, other items may need to be considered (such as making limits more obvious)
