### ISSUE TITLE
IOC for linkham95 temperature controller

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1085]
Used on LARMOR and elsewhere, LabVIEW VI already exists

**Comment by kjwoodsISIS** [comment]
Base IOC on existing VI.
Need an OPI too.

**Comment by AdrianPotter** [comment]
Reviving based on comments from @FreddieAkeroyd. Currently no feedback signal is used from the device to confirm receipt of input commands. The T95 does in fact respond to commands, but just with a carriage return. We can check for that.

**Comment by AdrianPotter** [comment]
Done. Just need this pull request reviewed:

https://github.com/ISISComputingGroup/EPICS-linkam95/pull/2

**Comment by AdrianPotter** [comment]
@FreddieAkeroyd merged and closed the remaining PR a week ago so I'm going to mark as complete
