### ISSUE TITLE
Remove hard-coding of default OPIs

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1088]
The OPIs which are recommend as defaults for Components are hard-coded in `DefaultTargetForComponent`.

One solution might be to define the Component types in code and assign OPIs to them via the opi_info.xml file.
We already have a number of Component types defined in code, so we could modify the XML like so:

```xml
<descriptions>
	<opis>
		<entry>
                    <type>CHOPPER</type>     This is the new bit
                    <key>Mk3 Chopper</key>
                    <value>
                          <path>Mk3Chopper.opi</path>
                          <description>Description required.</description>
                          <macros>
                          </macros>
                     </value>
		</entry>
```

Regarding Component types, some are general (CHOPPER) and some are quite specific (EUROTHERM, JULABO).
Could some of these be more generalised,  for example: TEMPERATURE?
It would require being able to select the appropriate icon though.

**Comment by IsabellaRey** [comment]
Pull request #195

**Comment by IsabellaRey** [comment]
ISISComputingGroup/ibex_gui#195
