### ISSUE TITLE
TDK Lambda Genesys: Extra logic to add

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1090]
As a developer I want to make sure that all the *required* logic is available to the TDK Lambda Genesys.

**Acceptance Criteria**
1. Any PINI values have been added after testing (e.g. Setting a voltage automatically)
2. Check if the logic below is needed to turn off the PSU:
If more than a second has passed since the Output Current Set Point was read as being not set to zero
AND
If the supply is ON
AND
If the Output Current Set Point is 0
AND
If the Field Value < 1
AND
If the Output Voltage < 0.1
AND
If the Max of the last 20 voltage readings - the Min of the last 20 voltage readings < 0.1
A result of TRUE will turn the Output Off

**Comment by kjwoodsISIS** [comment]
No longer needed.
