### ISSUE TITLE
GUI: List of Instrument Names

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1092]
As an IBEX developer and support person, I would like the list of instrument names in the instrument switcher field/menu to be dynamically configurable, so that the list can be updated without having to modify the client.

##### Acceptance Criteria
1. IBEX client populates the instrument switcher field/menu using a configurable list of instruments

##### Notes
1. This issue originates from #1052
2. The configurable list of instruments could be a PV.
3. The suggested name for this configurable list is IBEX Targets (or something similar), because not all the systems in the configurable list will be instruments.  In reality, the configurable list is a list of server machines, most of which control instruments - some servers may control other hardware (and we want IBEX to have access to these too).

**Comment by kjwoodsISIS** [comment]
Beam current server could supply a list of PVs.

**Comment by IsabellaRey** [comment]
Pull request: ISISComputingGroup/ibex_gui#209

**Comment by AdrianPotter** [comment]
Added a slightly more generic version Isabella's put PV script to the repo, given it's usefulness. Pull request:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/42

**Comment by AdrianPotter** [comment]
Both pull requests accepted and merged. Setting to review complete
