### ISSUE TITLE
GUI: Type Instrument Name

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1093]
As a scientist, I want to be able to type the name of an instrument in the "switch instrument" field, so that I can:
1. easily enter the name of the desired instrument without having to search a long list of instrument names
2. connect to an unlisted server (e.g. a development system)

##### Acceptance Criteria
1. The user is able to type the name of the instrument into the "switch instrument" field 
2. The user is able to connect to an unlisted server (provided he knows the name of the server).

##### Notes
1. This issue originates from #1052

**Comment by IsabellaRey** [comment]
Pull request: ISISComputingGroup/ibex_gui#199
