### ISSUE TITLE
GUI: Sort Instrument Names

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1094]
As a scientist, I want the list of instruments I can select to be sorted, so that switching instruments is as easy as possible. 
##### Acceptance Criteria
1. The 'localhost' instrument is always at the top of the list 
2. The next 5 instruments in the list are the 5 most frequently visited instruments.
   1. if the user has not visited 5 other instruments, then only listed those that he/she has visited (which might be zero).
3. All other instruments are listed alphabetically.
##### Notes
1. This issue originates from #1052
2. It would be good to separate the 3 categories in the drop-down menu.  For example:  
   ![instrument_list](https://cloud.githubusercontent.com/assets/7249337/13921668/f794d01a-ef70-11e5-96f2-d6662acb724d.png)

**Comment by IsabellaRey** [comment]
Acceptance Criteria 1 and 3 already addressed in #1096

**Comment by IsabellaRey** [comment]
Note: after a Google search, I couldn't find any obvious way to add separators using ComboViewer / SWT Combo. It looks like SWT Combo doesn't support separators.

**Comment by IsabellaRey** [comment]
Note: The Instrument selection dialog has now changed (see #1092) and the instrument list is displayed in a table rather than a drop-down menu.

**Comment by kjwoodsISIS** [comment]
Closed (ticket was inadvertently left open)
