### ISSUE TITLE
IRIS: IOC for Lakeshore Temperature Controller (model 218)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1097]
As a scientist, I need an IOC for the Lakeshore model 218 temperature controller, so that I can control it from IBEX.

##### Acceptance Criteria
1. I can control a Lakeshore model 218 temperature controller from a console (using caput, caget, etc.). 
2. I can control a Lakeshore model 218 temperature controller from a genie_python script. 

##### Notes
1. See [IRIS wiki page](https://github.com/ISISComputingGroup/IBEX/wiki/IRIS-Instrument-Details)
2. Manufacturer details of [Lakeshore model 218 temperature controller](http://www.lakeshore.com/products/Cryogenic-Temperature-Monitors/Model-218/Pages/Overview.aspx)

**Comment by kjwoodsISIS** [comment]
Check against 340/350 models.

**Comment by FreddieAkeroyd** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/26
