### ISSUE TITLE
IRIS: OPI for Lakeshore Temperature Controller (model 218)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1098]
As a scientist, I need an OPI for the Lakeshore model 218 temperature controller, so that I can control it from the IBEX GUI.

##### Acceptance Criteria
1. I can control a Lakeshore model 218 temperature controller from the IBEX GUI. 

##### Notes
1. See [IRIS wiki page](https://github.com/ISISComputingGroup/IBEX/wiki/IRIS-Instrument-Details)
2. Manufacturer details of [Lakeshore model 218 temperature controller](http://www.lakeshore.com/products/Cryogenic-Temperature-Monitors/Model-218/Pages/Overview.aspx)

**Comment by kjwoodsISIS** [comment]
Base OPI on exisiting VI

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/223
