### ISSUE TITLE
IRIS: OPI for McLennan PM600 Motion Controller

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1100]
As a scientist, I need an OPI for the McLennan PM600 Motion Controller, so that I can control the IRIS rotating centre-stick from the IBEX GUI.

##### Acceptance Criteria
1. I can control a McLennan PM600 Motion Controller from the IBEX GUI. 

##### Notes
1. There is a [PM600 driver](http://www.aps.anl.gov/epics/modules/manufacturer.php#McLennan%20Servo%20Supplies) available from the EPICS web-site.
1. [McLennan web-site](http://www.mclennan.co.uk/)

**Comment by kjwoodsISIS** [comment]
Can use standard EPICS motor record.
Check current VIs for any special parameters that might be required (e.g. for Matt North's group).

**Comment by AdrianPotter** [comment]
I've submitted a PR for this ticket. The standard motor OPI can be used for the McLennan but I've widened the OPI slightly to accommodate a longer description; they now contain the motor type (MCLEN, or GALIL)

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/303

**Comment by IsabellaRey** [comment]
Ticket merged in. Minor layout adjustment of other OPIs using the motor would be good, but I've captured in a separate ticket ISISComputingGroup/IBEX#1545
