### ISSUE TITLE
Custom users and RBs don't work

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1101]
Rob reported a problem with setting users and RBs manually. 
We need to get more information off him, but it sounds like if you enter a RB and User that are not in the database then it appears incorrectly in the dashboard.

**Comment by rerpha** [comment]
Can't see anything obvious wrong, need to talk to rob again.

**Comment by KathrynBaker** [comment]
Have asked Rob for more info, but have noticed that when selecting an RB Number via the search dialog on my system it isn't updating back at the moment on my system which may or may not be a local setup problem relating to my DAE, which is not simulating properly.

**Comment by KathrynBaker** [comment]
The not writing back has been isolated, it is down to my DAE not simulating properly, as I don't have the problem on DEMO, and on DEMO it seems to work.

**Comment by KathrynBaker** [comment]
Moved to impeded as I'm waiting for a response from Rob as to whether this is still occurring or not

**Comment by AdrianPotter** [comment]
@KathrynBaker: Any response from Rob? If not, please could you chase it up again? If we can't get a report on the state of the issue, then we should mark this as unreproducable.

**Comment by kjwoodsISIS** [comment]
Apparently, Rob has been happily using manual entry for the last cycle, so it would seem this is no longer an issue.  This issue will be closed.
