### ISSUE TITLE
LARMOR: OPI for Linkam 95 Temperature Controller

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1106]
As a scientist, I need an OPI for the Linkam 95 Temperature Controller, so that I can use it to control the temperature of my sample.

##### Acceptance Criteria
1. I can control a Linkam 95 Temperature Controller from the IBEX GUI. 

##### Notes
1. See ticket #1085 for the corresponding IOC.
1. [Linkam web-site](http://www.linkam.co.uk/t95-system-controllers/)

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/ibex_gui#245
