### ISSUE TITLE
GUI: change how LogPlotterSettings and AlarmSettings update the instrument's host name

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1109]
Currently LogPlotterSettings and AlarmSettings udpate the host name in their preference string by matching a pattern defined as a static string of the InstrumentInfo class and its derived classes. This means that the CustomInstrumentInfo host name can't be just any alpha-numeric string, as this would be a too broad match (currently must start with NDW). Also, there is a maintenance issue as these methods must be updated every time a new InstrumentInfo class is added.

Acceptance criteria:
1. Change the search mechanism to replace the old host name with the new one; the old host name is currently not being passed to the methods.
2. Refactor InstrumentInfo and its subclasses to remove the static method that provides the regex pattern
3. Remove the constraint that a CustomInstrumentInfo must start with NDW

**Comment by IsabellaRey** [comment]
NOTE: relaxing the name restriction is addressed in #1218

**Comment by IsabellaRey** [comment]
As described above, the root cause of restricting the custom instrument name is the way the LogPlotterSettings and AlarmSettings search for and replace the instrument name in their preferences strings. It is easy to change the InstrumentInfoReceiver interface to get both the new and old hosts (which the Instrument class can provide) and so simply replace the old host name with the new one.

However, the above does not work at startup because of two issues:

1. Strangely, the org.cssstudio.alarm.beast.Activator (used by AlarmSettings) does not derive from AbstractUIPlugin (and this seems to be the case of other alarm.beast activators too). This means the AlarmSettings preferences don't get saved to file when the GUI is closed, and so when you restart the GUI, they always contain `localhost` instead of the last host name. We can't really do much about this, we would need to set AlarmSettings to explicitly look for `localhost` as well as the old host name, which is more a hack than a proper fix.

2. The LogPlotterSettings preferences correctly store the last instrument name when the GUI is restarted. However, if the last instrument before closing the GUI was a custom instrument, currently the Instrument class can't retrieve it, because it's not in the list of known instruments, and it defaults to `localhost.` So the LogPlotterSettings would contain the correct old host name, but the Instrument would instruct it to look for `localhost` instead (which ironically is the opposite situation to issue 1!). There is a ticket to remember the last instrument at #1110 (this involves saving the full PV prefix, not just the host name).

So the current ticket depends on #1110 to resolve issue 2. Only when that is done it makes sense to apply changes for this ticket, and introduce a hack to solve issue 1.

Relaxing of the custom name restrictions is addressed in #1218

**Comment by DominicOram** [comment]
Adding a note here that unit tests should be created that test https://github.com/ISISComputingGroup/IBEX/issues/1110 along with this ticket. Acceptance criteria 2 will most likely create so many changes to unit tests that it only makes sense to be done after this is done.

**Comment by AdrianPotter** [comment]
Discussion with John:

- New setup is very unstable (as is the old one) because settings string can be corrupted and there's no recovery mechanism (i.e. what would happen if someone had an instrument called 'JDBC'!?)
- All instruments are reliant on having a fixed format for their setting URLs because otherwise switching instrument wouldn't work.

Based on this, I'm going to revert the change to the interface so the `old instrument` is no longer passed but instead construct each of the settings urls in place.
