### ISSUE TITLE
GUI: Remember custom instrument at startup

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1110]
Currently custom instruments are not retrieved at startup, as only the instrument name is saved and then it is checked against the list of known instruments.

Change the Instrument class so that initialisation allows custom instruments. This also requires saving the custom pv prefix in addition to the instrument name before the application is closed.

**Comment by FreddieAkeroyd** [comment]
This needs to persist on the client, not the server.

**Comment by IsabellaRey** [comment]
If this ticket is done, then #1109 can be addressed.

**Comment by DominicOram** [comment]
Writing this on here as I'm half way through the ticket and off next week. I managed to save and load the name, host and prefix. However, I came across some odd behaviour in updateHostName() in log settings and had to comment out the thrown error so as to test the saving/loading of the initial preferences. See https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket1110_remember_custom_inst

**Comment by IsabellaRey** [comment]
@DominicOram  take a look at #1109 (its latest comment is the most up-to-date description of what it's wrong with it)

Maybe we need to fix this ticket and that on the same commit to get something that is not broken

**Comment by AdrianPotter** [comment]
PR build failing. Please fix tests.

**Comment by DominicOram** [comment]
Build now passes

**Comment by AdrianPotter** [comment]
Sorry to be a pain but the InstrumentInfo and derived CustomInstrumentInfo classes are quite important to the function and the return values are sufficiently specific that I think they in particular would benefit from some unit tests. It's not necessary to write unit tests to give 100% coverage on both classes (though you're welcome to) but could you at least cover the changed code.

**Comment by DominicOram** [comment]
Unit tests will be done in https://github.com/ISISComputingGroup/IBEX/issues/1109 (see note on that ticket)
