### ISSUE TITLE
GUI: System PYTHONPATH changes detected message

### ISSUE THREAD

**Issue by ianbush** [ISISComputingGroup/IBEX#1113]
When starting the client for the very first time there is a pop-up about 'System PYTHONPATH changes detected'. It appears that the client sets some configuration for C:\Instrument\Apps\\Python\Lib\site-packages\epics", but nothing in this location is created by the genie_python installed.

**Comment by ianbush** [comment]
ISISComputingGroup/ibex_gui#203

**Comment by IsabellaRey** [comment]
Being reviewed
