### ISSUE TITLE
Explicitly add IOCs to Configs

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1116]
As a scientist and as an IBEX support person, I want to be able to explicitly add IOCs to a config, so that 
I don't have to rely on IOCs being previously added and automatically started in IBEX.
##### Acceptance Criteria
1. I can select and add an IOC to a config (analogous to the way in which I can add Blocks to a config)
##### Notes
1. This issue originates from #1069

**Comment by AdrianPotter** [comment]
Note for future reference: IOCs can be added to configs, but only when they're set to auto-start/auto-restart. No way to just "add" without these additional properties
