### ISSUE TITLE
Configure any IOCs belonging to a Config

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1117]
As a scientist and as an IBEX support person, I want to be able to configure any IOC that is included in a Config.
##### Acceptance Criteria
1. I can select any IOC included in the current config
2. I can configure the selected IOC
3. I am not permitted to configure an IOC if it is not included in the current config
##### Notes
1. This issue originates from #1069

**Comment by DominicOram** [comment]
Done
