### ISSUE TITLE
On adding or modifying a component in a Config

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1118]
As a scientist and as an IBEX support person, I want to be able to add a component to, or modify a component in, my current Config.  When I do so, I want to be alerted to any errors or inconsistencies that might arise.
##### Acceptance Criteria
1. I can add a component to the current config.
2. I can modify a component already included in the current config
3. I am alerted to any any errors or inconsistencies that arise for the change to the config.
4. A description of any errors or inconsistencies is written to the log.
##### Notes
1. This issue originates from #1069
2. At a minimum, IBEX should check for:
   1. duplicate Block or Group names
   2. duplicate IOCs (see #1116) - the configuration IOCs should override component IOCs
3. The description of any errors or inconsistencies written to the log, should advise the user how to rectify the problem  (For example: "Duplicate Block names in component XXXX and component YYYY.  Block names on an instrument must be unique." or "GALIL_01 IOC exists in more than one component. Please add GALIL_01 to the configuration or remove the extra components that contain this IOC.")

**Comment by DominicOram** [comment]
Now done
