### ISSUE TITLE
On loading a Config

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1119]
As a scientist and as an IBEX support person, when I load a config, I want to be alerted to any errors or inconsistencies.
##### Acceptance Criteria
1. On loading a config, I am alerted to any any errors or inconsistencies within the config.
2. A description of any errors or inconsistencies is written to the log.
##### Notes
1. This issue originates from #1069
2. The required checks are the same as those performed in #1118

**Comment by DominicOram** [comment]
Done
