### ISSUE TITLE
Silent start_inst

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#1120]
Add another start_inst that can run without popping up consoles. It can be annoying when start_inst keeps popping up windows when starting up, and the user is trying to do something else. This could be done with procserv flags or by running start_inst and redirecting the output to a null or void. 

Errors can be misleading, e.g. the ones about process can't be found when the stop_inst part runs.

**Comment by FreddieAkeroyd** [comment]
It is OK for the windows to pop up and then hide again.  What is not OK is if the windows fail to hide.
We only need to fix this issue if windows fail to hide.
More irritating to developers than scientists.
