### ISSUE TITLE
GUI - Hackathon: Connecting Read PV

### ISSUE THREAD

**Issue by ianbush** [ISISComputingGroup/IBEX#1121]
Finish connecting the GET_SCREENS PV for reading the device screens XML and converting to a device screens object.

Continue from branch Connecting_PVs.

**Comment by AdrianPotter** [comment]
See ibex_gui branch:

https://github.com/ISISComputingGroup/ibex_gui/tree/Connecting_to_PVs

As of revision 0570789, the GET_SCREENS PV for the device screens is now read from the PV for the current instrument and written to the screen.

To test:

1. Check out the Connecting_to_PVs branch
1. Check that the PV %MYPVPREFIX%CS:BLOCKSERVER:GET_SCREENS exists. If not, go to 4
1. Create the PV %MYPVPREFIX%CS:BLOCKSERVER:GET_SCREENS by doing a caput to %MYPVPREFIX%CS:BLOCKSERVER:SET_SCREENS with some valid XML data (example at end).
1. Open the IBEX gui
1. Open the device screens
1. Switch to your local instrument

The device screens will be displayed as XML on screen. Note that the PV has been read, converted to an object model and then converted back to XML for displaying in a recognisable format. It is not intended that the output to the screen is the same as the PV value, and in fact helps to demonstrate that the conversion is in fact happening internally.

In case your GET_SCREENS PV doesn't exist, the following data is valid:

```
<?xml version="1.0" ?>
<devices xmlns="http://epics.isis.rl.ac.uk/schema/screens/1.0/">
    <device>
        <name>Eurotherm 2</name>
        <key>Eurotherm</key>
        <type>OPI</type>
        <properties>
            <property>
                <key>EURO</key>
                <value>EUROTHERM1</value>
            </property>
        </properties>
    </device>
</devices>
```
