### ISSUE TITLE
GUI - Hackathon: Connect Write PV

### ISSUE THREAD

**Issue by ianbush** [ISISComputingGroup/IBEX#1122]
The equivalent to reading the PV in #1121 needs to be implemented for writing the PV.

**Comment by IsabellaRey** [comment]
I have merged the master branch into the existing branch (which is the same as for #1121)

**Comment by IsabellaRey** [comment]
Moving back to Ready as I need to work on more urgent tickets first

**Comment by IsabellaRey** [comment]
Two pull requests as part of this ticket: ISISComputingGroup/EPICS-inst_servers#51 (this should be checked first, as the changes in the GUI depend on it) and ISISComputingGroup/ibex_gui#265

Description on how to test are in the pull requests
