### ISSUE TITLE
GUI - Hackathon: Populate device screens list

### ISSUE THREAD

**Issue by ianbush** [ISISComputingGroup/IBEX#1124]
Populate a list of device screens and make the open button work.

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/282

**Comment by AdrianPotter** [comment]
Code reviewed: Couple of questions, but nothing blocking
Jenkins PR build currently failing. Retesting.

**Comment by AdrianPotter** [comment]
Not in release notes
