### ISSUE TITLE
Blockserver - Hackathon: Device screens schema validation and tidying up

### ISSUE THREAD

**Issue by ianbush** [ISISComputingGroup/IBEX#1129]
During the hackathon good progress was made in creating the block server PVs for getting and setting the list of device screens. This now just needs tidying up and XML schema validation adding.

**Comment by AdrianPotter** [comment]
See ibex_gui branch:

https://github.com/ISISComputingGroup/ibex_gui/tree/Connecting_to_PVs

As of revision 0570789, the GET_SCREENS PV for the device screens is now read from the PV for the current instrument and written to the screen.

To test:

1. Check out the Connecting_to_PVs branch
2. Check that the PV %MYPVPREFIX%CS:BLOCKSERVER:GET_SCREENS exists. If not, go to 4
3. Create the PV %MYPVPREFIX%CS:BLOCKSERVER:GET_SCREENS by doing a caput to %MYPVPREFIX%CS:BLOCKSERVER:SET_SCREENS with some valid XML data, for example:

<?xml version="1.0" ?>
<devices xmlns="http://epics.isis.rl.ac.uk/schema/screens/1.0/">
    <device>
        <name>Eurotherm 2</name>
        <key>Eurotherm</key>
        <type>OPI</type>
        <properties>
            <property>
                <key>EURO</key>
                <value>EUROTHERM1</value>
            </property>
        </properties>
    </device>
</devices>

4. Open the IBEX gui
5. Open the device screens
6. Switch to your local instrument

The device screens will be displayed as XML on screen. Note that the PV has been read, converted to an object model and then converted back to XML for displaying in a recognisable format. It is not intended that the output to the screen is the same as the PV value, and in fact helps to demonstrate that the conversion is in fact happening internally.

**Comment by AdrianPotter** [comment]
Link pull request https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/45

**Comment by AdrianPotter** [comment]
Caused some failing unit tests.  Please review and merge PR:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/46

**Comment by AdrianPotter** [comment]
John found an issue when starting up the block server after this was integrated:

MAJOR: Error creating device PV: local variable 'devices_file_name' referenced before assignment

Fixed:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/47
