### ISSUE TITLE
LARMOR: 2nd TPG300

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1130]
As an instrument scientist, I would like a 2nd TPG300 IOC, so that I can control the TPG300 device that controls the vacuum for the LARMOR SANS tank.

##### Acceptance Criteria
1. A 2nd TPG300 IOC is available in IBEX
1. I can control the 2nd TPG300 via an OPI in IBEX.

##### Notes
1. None

**Comment by FreddieAkeroyd** [comment]
There are currently 2 TPG300 IOCs, but I've added a 3rd one just in case

**Comment by kjwoodsISIS** [comment]
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 16 June 2016 14:48
> To: Woods, Kevin (Tessella,RAL,ISIS); Akeroyd, Freddie (STFC,RAL,ISIS)
> Subject: LARMOR Tank pressure
> 
> Dear Kevin and Freddie,
> 
> I called in a couple of favours and made a few calls. The tank pressure for LARMOR is now connected – using the TPG300_02 ioc.
> 
> The PV for the pressure is :
> IN:LARMOR:TPG300_02:PRESSURE_A1
> 
> Ioc TPG300_01 is on COM 13
> Ioc TPG300_02 is on COM 14
> 
> All I have done is edit the globals.txt file to include the com port for TPG300_02. Then run the TPG300_02 ioc. No code changes – just configuration.
> 
> I’m not entirely sure about the IBEX configurations. I have a feeling that is for Rob to review at some point.
> 
> The appropriate ticket should now be ready for review. I will leave the ioc running. The pressure is currently roughly 760.
> 
> Regards,
> 
> Gareth

**Comment by KathrynBaker** [comment]
I've looked at the PVs, and they seem to exist, and give reasonable values,  moving to complete
