### ISSUE TITLE
MUON FRONT END: Tests for the May 2016 Maintenance Day (4th May)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1135]
As an instrument scientist I have a few tests I would like to run relating to the Muon Front End automation:

1. Check that the Danfysik IOC and hardware work together
2. Check that the updated TDK Lambda Genesys IOC and hardware work together
3. Use SECI to interact with a Danfysik via a script
4. Use SECI to interact with a TDK Lambda Genesys via a script

**Notes**

NDEMUONFE has been communicating with a development version of the TDK Lambda Genesys IOC, but needs to be checked against the one that has been merged.
There is a rough and ready VI that talks to three Lambdas at present, additions will be required for the Danfysik to this VI to allow for test 3 to be undertaken.
This ticket is time dependent, and requires that issues #980, #982 and #983 are all merged beforehand.

**Comment by KathrynBaker** [comment]
A number of bug fixes and changes are required for this to work properly, however the test detailed above are all passed with quick patches made on the system. These changes need to be captured and as such I will create a 'mop-up' ticket with the various alterations that are required

**Comment by IsabellaRey** [comment]
The fixes needed have been captured in #1170, so this ticket can be considered completed
