### ISSUE TITLE
IBEX Release Tagging

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1137]
As a developer, I want to be able to tag a specific IBEX build (client or server), so that I can clearly identify each release of IBEX.
#### Acceptance Criteria
1. Ability to label repositories with a tag indicating the IBEX release that they contribute to.
2. Documented instructions on how to tag repositories.
##### Notes
1. Do we need a convention for IBEX release tag labels (e.g. version m.n.o.p)?  If so, we should include it in the instructions for tagging repositories.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release

I've added notes for tagging a release
