### ISSUE TITLE
IBEX Release Process

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1138]
As a developer, I would like to have a dcoumented process for releasing IBEX, so that I can create well-defined, clearly indentifiable & traceable releases of IBEX (client & server).

#### Acceptance Criteria
1. A documented definition of how release a build of IBEX server (that is copy it to a long-term persisted location).
1. A  documented definition of how release a build of IBEX client (that is copy it to a long-term persisted location).

#### Notes
1. None.

**Comment by kjwoodsISIS** [comment]
May also need to think about #1230 - is the install process supposed to performed by using the script?

**Comment by AdrianPotter** [comment]
I believe this is fixed as of #1586
