### ISSUE TITLE
Update project workflow in wiki

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1140]
This ticket relates to the IBEX developers workflow wiki:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki

There are a number of points missing from the wiki. Notably, what is Waffle, how do we use it, and what is the workflow for the various stages of a ticket's life cycle?

There are also 2 sections of the wiki currently dedicated to the Git workflow:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Development-Workflow
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-Cribs

These should be merged and updated as appropriate and integrated with the description of the ticket life cycle.

Acceptance criteria:
1. Waffle usage and description of ticket stages in Wiki
2. Git workflow refactored so that information is no longer duplicated

**Comment by KathrynBaker** [comment]
I think it is fair to say that the wiki is no longer out of date in this way (it is a long time since we used Waffle)
