### ISSUE TITLE
Prevent illegal characters in description

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1142]
A user can not save configurations with illegal characters in. 

Steps to reproduce.
1. Open IBEX GUI
2. Configurations -> Configurations -> New
3. Saves As...
4. Enter valid name
5. Set description as "Desc !"£$ &amp; &lt;"
6. Configurations -> Configurations -> Load select default
7. Configurations -> Configurations -> Load new configuration not save.

Notes for developer:
There is nothing in "C:\Instrument\Settings\config\<username>\configurations\configurations\<test name>\meta.xml"

There might be an associated error:
"'ascii' codec can't encode character u'\xa3' in position 56: ordinal not in range(128)" from blocksvr from application IOCLogServer

**Comment by John-Holt-Tessella** [comment]
see https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/41
and https://github.com/ISISComputingGroup/ibex_gui/pull/215

It would be good to review tiket #1149  first because this merges in that change

**Comment by AdrianPotter** [comment]
The workflow above has been confirmed as fixed up to step 5.

Whilst testing, I noticed that in the new configuration dialog, the "Save as" button is enabled by default, even though the dialog reports an empty description error. If you enter a description and remove it, the button is disabled. I believe the behaviour should be that the button is disabled on entering the dialog until a description is entered.

Similarly, on clicking the "Save as" button, the "OK" button in the save dialog is initially enabled even though no name has been entered. Again, the correct behaviour should be that the button is disabled initially until a valid name is entered.

**Comment by AdrianPotter** [comment]
Re-reviewing...
