### ISSUE TITLE
Empty groups can not be saved

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1145]
If a group does not contain any blocks that group is not saved. Check whether this is desired behaviour. (see ISISComputingGroup/ibex_gui#193)

Acceptance Criteria:

1. Create a new configuration
2. Add a group
3. Save
4. Reload that configuration
5. Ensure that group shown and is empty
6. Repeat for new group in edited configuration
7. Repeat for new group in component
8. Repeat for new group in current configuration

**Comment by kjwoodsISIS** [comment]
This is not a bug.  It is intentional behaviour.
