### ISSUE TITLE
Group Names are not Checked on Input

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1146]
When a user enters a group name it should be validated so that a user can not accidentally add special characters (which will create an error on save).

(See ISISComputingGroup/ibex_gui#193)

Acceptance Criteria:

1. Create a new group in a configuration 
1. Enter a name with a space
1. Error message should be shown and save/save as button should be disabled
1. Repeat for a component
1. Repeat for current configuration

**Comment by John-Holt-Tessella** [comment]
jenkins retest this please

**Comment by AdrianPotter** [comment]
Awaiting check style updates

**Comment by AdrianPotter** [comment]
Works as expected. Changes merged. Thanks!
