### ISSUE TITLE
GUI: A different way to indicate a block is under run-control

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1149]
Turning a block red or green if it is under run-control and in or out of range is okay, but it needs to be suitable for colour blind people and when it is red it can be hard to read the value.

For this ticket we will create prototypes of a few different ways of indicating the status and will run them pass some of the scientists (Rob, Winfried, Christy?)

Proposals:

1. Make the block fonts slightly bigger (currently we can fit nine values in a column, what happens if we increase the font size so only eight fit?)
1. Change the shade of red for out of range and see if it can be distinguished by the colour blind
1. Make it flash if out of range
1. Place a "traffic light" at the end of the value indicating its status (Not under control = white, under control = black, out of range = red, possibly flashing?)

**Comment by kjwoodsISIS** [comment]
This has wider implications than just Blocks.  Similar considerations apply to the table of motors, Alarms, etc.  We might want to think about a broader solution (e.g. allow the user to choose colour scheme).

**Comment by kjwoodsISIS** [comment]
Another suggestion: could you draw an underline under a block that is under run-control?
