### ISSUE TITLE
Modify PyDev for IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1154]
As an IBEX developer, I want to modify PyDev to implement IBEX specific behaviour.
#### Accepatnce Criteria
1. Remove the following icons from the top of the console: pin console. (check the functionality of pin console first)
2. Remove the "select python type" dialog which appears when creating a new console.
3. Warn the user before he or she kills a console.

#### Notes
1. This issue is a child of #1019

**Comment by kjwoodsISIS** [comment]
See also issue #1169

**Comment by DominicOram** [comment]
This ticket will most likely involve a lot of fiddling with the Eclipse API. This fiddling will have to be reworked under Eclipse 4 so on hold until then or until it is decided that the Eclipse 4 move is taking too long...

**Comment by Tom-Willemsen** [comment]
+1 from EMU scientists (specifically, they requested item 3 in the acceptance criteria above: want the user before killing the pydev console)

**Comment by DominicOram** [comment]
Pin console removed in https://github.com/ISISComputingGroup/ibex_gui/pull/1104

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1104 also covers 2

**Comment by Adam-Szw** [comment]
1. and 2. don't actually work currently if you create a second console view. Is there any chance we could fork pydev? Working with it is very hacky currently because pydev doesnt let you override console creation process so current solutions revolve around letting it do its things and then ripping out existing buttons and replacing them with our own. @DominicOram @RaiBishal @JamesKingWork

**Comment by Adam-Szw** [comment]
PR for updating our fork: https://github.com/ISISComputingGroup/Pydev/pull/2
I will need this PR reviewed and approved first before procceeding with ticket since if we decide for another version or I pulled something wrong changes would have to be discarded

**Comment by DominicOram** [comment]
From discussion with @JamesKingWork I think point 3 is the most important and people tend not to use the second console view so maybe we could focus on that?

**Comment by Adam-Szw** [comment]
If we don't care about second console view then we can have a solution without even using pydev. I had a working solution that follows same logic as https://github.com/ISISComputingGroup/ibex_gui/pull/1104 but none of it works in second view. Do we go with it and ignore second view then?

**Comment by DominicOram** [comment]
I think if we have something that works for most cases we go for it and make a ticket for the edge case

**Comment by Adam-Szw** [comment]
PRs
Ibex Gui: https://github.com/ISISComputingGroup/ibex_gui/pull/1356
PyDev fork: https://github.com/ISISComputingGroup/Pydev/pull/3
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/6795

**Comment by rerpha** [comment]
Looks good, i'm not sure whether it's worth creating the tickets for points 1+2 but I'll leave that up to you

**Comment by DominicOram** [comment]
I believe points 1+2 are covered in https://github.com/ISISComputingGroup/ibex_gui/pull/1104
