### ISSUE TITLE
Display Alarm State of Blocks

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1157]
As a scientist, I want Blocks to display their alarm status, so that I can take action if any of my Block do go into an alarm state.

#### Acceptance Criteria
1. If the PV corresponding to a Block goes into an alarm state, IBEX should indicate that the Block is in an alarm state.
1. The alarm state of a Block could be indicated in one (or both) or the following ways:
   1. Blocks in state of alarm are shown in the Block/Groups area of the GUI by a colour change, or associated icon.
   1. Blocks in state of alarm are shown in the Alarm view.

#### Notes
1. A PV can go into an alarm state, we need to make sure we reflect the state of alarm in the corresponding block.
1. The Alarm view shows IOCs in a state of alarm.  What do we need to do to show PVs and Blocks in a state of alarm?

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/241

**Comment by IsabellaRey** [comment]
Reviewing at same time as #1171, as there's one pull request for both

**Comment by IsabellaRey** [comment]
Provided feedback, mainly style warnings
