### ISSUE TITLE
Groups become messed up if they have the same name while editing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1158]
Group UI is confused when groups have the same name (if if temporarily e.g. if you wanted to call the parent parent_left)

1. Create a 2 blocks and group in a new configuration
1. Add block to first group
1. Add remaining block to new group
1. Change name to be the same as first group

First group is selected with second group blocks in. Editing the name edits the second block

**Comment by John-Holt-Tessella** [comment]
Dev Notes: 

See code at GroupsEditorPanel 189 for text modification listener.

**Comment by kjwoodsISIS** [comment]
This may have been "fixed" - because it is now no longer possible to have two groups with the same name.  Need to check and confirm.

**Comment by kjwoodsISIS** [comment]
No longer a problem.
