### ISSUE TITLE
stop_inst.bat kills Nicos processes

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1159]
NOTE: NICOS will eventually start/stop with the instrument anyway, so maybe there is no need to address this issue?

Steps to reproduce: start one or more nicos processes from command line, then run stop_inst.bat (or start_inst.bat, which calls stop_inst.bat). The nicos processes are killed.

Note the "SUCCESS" lines in the .bat script output, as follows. There seems to be one line for each nicos process, and they don't appear when nicos is not running

Waiting 10 seconds for process cleanups to complete before next actions
ERROR: The process "procServ.exe" not found.
ERROR: The process "gateway.exe" not found.
ERROR: The process "conserver.exe" not found.
ERROR: The process "console.exe" not found.
ERROR: The process "PSCTRL-IOC-01.exe" not found.
ERROR: The process "ArchiveEngine.exe" not found.
ERROR: The process "Mk3Chopper.exe" not found.
SUCCESS: The process with PID 11996 (child process of PID 14060) has been terminated.
SUCCESS: The process with PID 9660 (child process of PID 8928) has been terminated.
SUCCESS: The process with PID 14964 (child process of PID 312) has been terminated.
ERROR: The process "SeciUserInterface.exe" not found.
ERROR: The process "SECIStartup.exe" not found.
ERROR: The process "LabVIEW.exe" not found.
ERROR: The process "mkscript3.exe" not found.
ERROR: The process "muonscript.exe" not found.
ERROR: The process "makescript.exe" not found.
ERROR: The process "PlotScan.exe" not found.
ERROR: The process "vs7jit.exe" not found.
ERROR: The process "mari_script.exe" not found.
ERROR: The process "tkgenie32.exe" not found.

**Comment by kjwoodsISIS** [comment]
Not really a problem.
