### ISSUE TITLE
NICOS: get existing tests to work

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1160]
As a developer, I want NICOS to be tested. NICOS has already automated tests which can run with nose, but some are failing, and we should investigate how to fix them.

For the daemon tests failing, the help message is not very helpful, but a Google search seems to point at an error in the test teardown.

It's probably worth checking whether the same tests pass in Linux: check with Owen if it's possible to run them quickly on his Linux machine, as he has Nicos running.

**Comment by AdrianPotter** [comment]
I've created a pull request for nicos-core:

https://github.com/ISISComputingGroup/nicos-core/pull/3

The tests all now run both in PyCharm and from the command line. I've also skipped a few tests pertaining to functionality we don't intend to use.

I've added some documentation on the wiki to help get started with testing:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Testing-Nicos
