### ISSUE TITLE
Default synoptic does not appear in edit config

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1161]
On the summary tab the default synoptic is not selected when you edit a configuration

**Comment by AdrianPotter** [comment]
I've updated the code to display the recommended synoptic:

https://github.com/ISISComputingGroup/ibex_gui/pull/230

Just need to add a system test...

**Comment by AdrianPotter** [comment]
System test pull request:

https://github.com/ISISComputingGroup/ibex_system_tests/pull/5

**Comment by AdrianPotter** [comment]
Note that some instruments

Acceptance criteria:

1. Open an Instrument (try several)
2. Go to the configuration menu
3. Open the edit configuration window
4. Go to the Summary tab
5. The "Synoptic" combo box should be non-empty

On the local instrument the default is "-- NONE --", on DEMO it is "IMAT_Mockup_01 (recommended)". This contrasts to the previous behaviour where the selection was blank

**Comment by IsabellaRey** [comment]
Sorry, I can't finish reviewing this story as I can't get the maven build to work, so I can't run the system tests.

One should check that the test passes

**Comment by IsabellaRey** [comment]
Maven build working again, so I've finished reviewing
