### ISSUE TITLE
Deal with error on news not available

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1162]
As a user if I views the news and the web page is not accessible then I want to see a message stating that, not a stack trace on the console.

Acceptance criteria

1. Change the MCR_NEWS_PAGE_URL url to point at a different domain (McrNewsPanel.java)
1. Open Beam Status
1. News box shows error message
1. Repeat for incorrect page with correct domain

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/226
