### ISSUE TITLE
GUI: use SWTResourceManager to create Fonts and Colours

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1163]
Many parts of the code use the SWTResourceManager and ResourceManager classes to create things like Fonts and Colours.

However, in a few classes Fonts are created directly without using the ResourceManagers. Should they be changed to use the ResourceManagers instead? 

Same for Colors?

NOTE: this ticket originates from #1147: if things like Fonts and Colors are not disposed correctly, they cause resource leaks. Using Fonts and Colors from the ResourceManager should take care of that for us.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/228

**Comment by AdrianPotter** [comment]
I've removed all instances of "new Font(" and "new Color(" in the gui code, except within the SWTResourceManager itself.

**Comment by AdrianPotter** [comment]
I've updated the code so that the cursors for the Synoptics are now created from the resource manager rather than in place

**Comment by AdrianPotter** [comment]
I've also refactored the creation of new images outside of the SWT resource manager so that they're now disposed along with their parents.

**Comment by AdrianPotter** [comment]
Note that GitHub is suffering some technical issues at the moment so the new commits haven't appeared. Hopefully it will be resolved soon...
