### ISSUE TITLE
Group policy for system test setups

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1165]
As a developer, I want RCPTT system tests to be able to run on any developer's machine as well as on Jenkins, and ideally without leaving test artefacts in the instrument server.

Currently, when running a test on a local machine, this can create new configurations and synoptics which don't get deleted in a tear down context (see for example the Test Cases AddFirstBlock and CreateSimpleSynoptic). These artefacts are deleted manually by the developers, to be able to run the tests a second time.

On Jenkins, this is taken care of by clearing the EPICS workspace between test runs.

As part of this ticket have a team discussion to decide:
* do we go for having tear down contexts so no manual steps are needed on the developers' machines? These extra steps will slow down the tests (for example, to delete the current config, one must switch to a different config first) and currently seem to bring no benefits for Jenkins
* do we rely on naming conventions for newly created configurations/synoptics?
* which instrument should the test point to (e.g. for PV names)?

**Comment by kjwoodsISIS** [comment]
We agreed that there should be a clean slate policy, meaning that since the test starts with a "clean slate" it should tidy up after all the tests were run  and leave a "clean slate" when finished.  There was also a discussion about whether we should clean up between individual tests in a test-suite comprising multiple tests - it might be valid to not clean up between individual tests (i.e. only clean up at the end).

**Comment by IsabellaRey** [comment]
Following discussion with Adrian and John:

In an ideal world, before each test it would be nice to:

1. stop and restart the GUI, because if a test leaves dialogs open and the GUI is not restarted, the next test will fail to find the widgets it needs
2. stop and restart the blockserver, pointing at a blank configurations directory every time.  It would be nice to have a blank configuration directory is because a test may make changes to a configuration which may cause a following test to fail. If there are 100 tests in between, it becomes really difficult to debug. However, one can only clear the configuration directory while the blockserver is not running, so we would need a way to stop and restart the blockserver every time.

The setup above however would make the tests extremely slow. Maybe we could settle for something in between, e.g. have a clean slate every 10 tests.

So there are a few questions that need answering with this ticket:
1. Is it possible to stop and restart the blockserver from within RCPTT?
2. Is it possible to change the IPCONFIGROOT (which contains the path to the config directory) on the fly from within RCPTT, so that it points to an empty config directory (so that the local one doesn't get touched)?
3. Is it possible to stop and restart the IBEX application from within RCPTT?
4. Is it possible to group tests in tens and run the setups above before each group?
5. Is it possible to read the INSTRUMENT environment variable, containing the name of the instrument?

**Comment by AdrianPotter** [comment]
Note that if Ticket #1168 is fixed, it will help keep system test run time down

**Comment by John-Holt-Tessella** [comment]
NB pull request may already have been done for IBEX GUI because it is also part of ticket #1068

**Comment by AdrianPotter** [comment]
Moving back to ready whilst tackling higher priority tickets
