### ISSUE TITLE
Unexpected configuration behaviour for new instrument

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1168]
Discovered whilst working with a fresh development machine. Having installed EPICS and started a new local instrument, I was very confused when IBEX reported the instrument status as "UNKNOWN". It took a while to discover that this is because there is no loaded configuration. Even though no configuration was loaded, I could still enter "Edit current configuration...". To fix the problem I had to load 2 existing configurations until the instrument reported its state as "SETUP".

Reproduction steps.
1. Remove the current local instrument configuration in C:\Instrument\Settings\config\ or similar
2. Get a fresh copy of the default config by running:

git clone http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/inst.git NDWXXX
1. Start the instrument
2. Start IBEX

At this point you should be able to observe that the "Edit current configuration..." button is active, but if you click it, the name and description of the current config is empty. The state of the instrument appears as "UNKNOWN".

Now load configuration "test". For me this did not update the instrument status in the GUI. Loading configuration "test2" did the trick.

Acceptance criteria:
1. When opening IBEX with a new instrument, and at least one configuration exists, IBEX should select one.
2. When opening IBEX with a new instrument and no configurations have been set up, the "Edit Current Configuration..." button should not be active

**Comment by kjwoodsISIS** [comment]
During Sprint pre-Plannjing meeting on 13th June 2016, we agreed that if there is no "default" config, the system should load the "base" config.

**Comment by KathrynBaker** [comment]
Only one instrument left to be new, closing,
