### ISSUE TITLE
GUI: Disconnected blocks need to be clearer

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1171]
Some sort of colouring?

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/241

**Comment by IsabellaRey** [comment]
Reviewing at same time as #1157, as there is one pull request for both

**Comment by IsabellaRey** [comment]
Provided feedback, mainly style warnings
