### ISSUE TITLE
EPICS build on dev PC broken

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1172]
Issue discovered by Isabella, confirmed by Adrian.

Steps to reproduce:
1. Get a fresh copy of EPICS from the repo
2. Run build.bat

The console log for the error is:

C:\Instrument\Apps\EPICS\docs_built\manuals\manual.rst
../docs_built/source/sdtest/sdtest.rst:99: (ERROR/3) Malformed table.
No bottom table border found or no blank line after table bottom.

===== ====================  ====================================================
============================================================
Macro Default               Notes
===== ====================  ====================================================
============================================================
../docs_built/source/sdtest/sdtest.rst:102: (WARNING/2) Blank line required afte
r table.
C:\Instrument\Apps\EPICS\docs_built\manuals\manual.rst:: (ERROR/3) Anonymous hyp
erlink mismatch: 2 references but 0 targets.
See "backrefs" attribute for IDs.

The error step in the build process is:

C:\Instrument\Apps\EPICS\isisdoc>C:\Instrument\Apps\Python\Scripts\rst2pdf.exe -
-output=test.pdf --config=rst2pdf.conf --stylesheet-path=. --stylesheets=a4,seri
f 

it is triggered by

C:\Instrument\Apps\EPICS\isisdoc\make_manuals.bat

The script was changed at the end of Feb by Freddie because the old Python script was no longer present. It seems odd its gone undetected this long.

Isabella has tried cleaning her system and running a fresh build with the same result. It's not obvious to me from the recent changes to the repo where this might have come from. I think the command being run is fine, but the anonymous link being reported needs to be found and fixed.

Acceptance criteria:
1. EPICS build runs to completion without error

**Comment by FreddieAkeroyd** [comment]
This is related to a __ in a PV name in sdtest.rst being treated as an anonymous hyperlink by rst2html, will commit a fix. Seems that rst2html itself does not by default exit with a non-zero status on error, hence it not being flagged by the build server. I will add appropriate options.

**Comment by FreddieAkeroyd** [comment]
Related pull requests are:

- ISISComputingGroup/EPICS#21
- ISISComputingGroup/EPICS-ioc#29

You may want to do them in that order as the first adds error checking and should then fail a build properly, then the second fixes the rst error
