### ISSUE TITLE
install_to_inst.bat should not require install.log to be created first

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1173]
On NDXZOOM I attempted to run install_to_inst.bat on what is a clean machine from an EPICS perspective, and got a warning that Windows cannot find C:\Instrument\Apps\EPICS\install.log

It could be that this is appropriate in our minds, but my instinct would be that this should not be necessary

**Comment by ChrisM-S** [comment]
Just a thought, but did it already have EPICS beam logger?
Chris

**Comment by FreddieAkeroyd** [comment]
The problem is that the EPICS directory does not exist and so robocopy is unable to create an install.log for the copy, an easy fix

**Comment by KathrynBaker** [comment]
Not applicable in this situation, ISIS Beam logger won’t be using that directory.

Regards,
Kathryn

**Comment by ChrisM-S** [comment]
Does that mean we have more than one EPICS installation on ZOOM then?

Just curious ☺.

Chris

**Comment by KathrynBaker** [comment]
No, one EPICS installation, that uses the Apps directory. The beam logger is all in LabVIEW. Some of the tools relating to channel access will be duplicated, as we needed those in the LabVIEW directories for use on non-IBEX instruments, but this is only tools such as caget, caput, caRepeater. All of about 5MB of repeated (compiled) code. The EPICS IOC etc. for the beam logger is run centrally, so all the LabVIEW needed was channel access to read it.

Regards,
Kathryn
