### ISSUE TITLE
genie_python: improved spectra plotting

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1174]
It should automatically add new plots to the last created graph, and if the user forgets to capture the last graph it should be possible to retrieve this.

To do:

* In genie.py create a add_spectrum method that adds to the existing plot
* In genie.py create a method for getting the existing plot object, get_last_plot?
* genie_plot.py add spectrum etc. need default values for period etc.

**Comment by AdrianPotter** [comment]
Code reviewed and tested. Works great, thanks.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/25 by the way
