### ISSUE TITLE
Chopper OPI graph limits

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1176]
Is it possible to specify some more sensible limits for the phase/frequency graph? It currently autoscales and with the number varying only slightly just fills the display with a solid line. Ideally it wants a low limit of 0 and a high limit of (max+10%)

**Comment by kjwoodsISIS** [comment]
In discussion we suggested that it might be possible to use the PV's expected operating range to set sensible limits.

**Comment by kjwoodsISIS** [comment]
Ultimately, this problem is a limitation of CSS.  It might be solved by upgrading to 3.3.11, or it might need an upgrade to 4.x (which would be a major job).  This issue is not urgent - the above workaround can be implemented, if necessary.

**Comment by KathrynBaker** [comment]
This has not been considered in 8 years, people will now either be used to it, and/or not finding it an issue, closing (new ticket can be created if this is still needed)
