### ISSUE TITLE
Motor twitching - torque (CNEN) enabled

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1178]
Sometimes after a move particularly with MTR0105 (jaws2 north) on larmor the motor position (sp and rbv) starts twitching. This can be stopped by going into the advanced motor record fields and "disabling torque". Question is how did it suddenly get enabled? Seems to be governed by the CNEN field. Looking at the code If  CNEN changes and msta.GAIN_SUPPORT != 0 an ENABLE_TORQUEUE / DISABLE_TORQUE message based on cnen value is sent.

Also If GAIN_SUPPORT is enabled it looks like it will check msta.EA_POSITION of msta and adjust CNEN appropriately. So is EA_POSITION getting enabled, or are there junk bits in MSTA? The _torque commands -> Motorsetclosedloop in the asyn driver which is also used for motor off/on

**Comment by FreddieAkeroyd** [comment]
Think this may be related to the asyn motorStatusPowerOn_ parameter which may also be used fot EA_POSITION

**Comment by kjwoodsISIS** [comment]
May need to implement a temporary fix for cycle 2016/02 (28 June 2016 - 29 July 2016)

**Comment by kjwoodsISIS** [comment]
Ask Rob if he can reproduce it for us during the shutdown.

**Comment by GDH-ISIS** [comment]
I think this is also happening on MERLIN. The read-backs are voltage potentiometers and as a result are constantly updating. In addition, the set points are being constantly updated and the motors are being moved - constantly twitching. .CNEN is changing between enabled and disabled a lot. Changing the retry deadband RDBD appeared to have no effect.
