### ISSUE TITLE
Consistent check style usage

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1181]
The current check style warnings in Eclipse cover a far greater number of issues than used by Jenkins. Many of these warnings are outside the agreed upon style for documenting the code.

The suggestion is to update the checkstyle file  in the IBEX developer version of Eclipse to cover only documentation as requested for:
- Classes
- Public methods
- Public fields

Developers will then add in this documentation as they introduce or change code.

Acceptance criteria:
1. Instructions are available in the wiki for updating the checkstyle file for an existing install of IBEX Eclipse
2. The newest checkstyle file is used in the latest version of IBEX Eclipse on the network
3. When checkstyle is run on the source with the new style file, only the above mentioned issues are highlighted

**Comment by kjwoodsISIS** [comment]
Apparently, this is already done.  Check.  If done, close it.
