### ISSUE TITLE
Source copyright is out of date

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1182]
In the Ibex_gui source, the copyright notices only go up to 2015. They need to be modified to include 2016. This likely also applies to other IBEX repos.

Acceptance criteria:

1. Source code copyright statements in IBEX project all extend as far as 2016

**Comment by FreddieAkeroyd** [comment]
I believe the date is the date you are first claiming copyright from, and if you make a "new version" then you should add a new date or extend a date range as appropriate. So we could update the copyright for every file each year, but that would probably be an unnecessary git commit. Any files created/modified in 2016 should probably have a 2016 copyright. If a company is releasing a product, they might want all code that forms part of that particular product release to have the same copyright date (as that release is "publication"), but if the code is open on GitHub a single publication date doesn't really exist. I've opened a few Mantid source files and it doesn't look like they change the date each year on a per file basis.

**Comment by John-Holt-Tessella** [comment]
Find out if this is important

**Comment by John-Holt-Tessella** [comment]
Looking at (https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html) it says that we should edit the copyright only when we change the files. It suggests we do need a copyright on each file to prevent others from copying the files, putting their own copyright on them and then using them. So I have edited the workflow to say this. (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-Cribs and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Development-Workflow)

**Comment by John-Holt-Tessella** [comment]
After review send the following to all. Hey All, we have had a look at the copyright policy and it looks like it needs to be updated everytime the code is edited. SO when editing or review code please update the copyright to be Copyright (C) <original year> - <current year>

**Comment by DominicOram** [comment]
Can we write a script to do this for us?

**Comment by KathrynBaker** [comment]
Given that it only needs to be done on code that is being edited (new code should be using the correct date as that information comes from the automatic comments in the developers edition of eclipse), it is likely to only take a couple of extra minutes per task, if that, to change the dates, and check them.

Although I guess a script could be written that could be run on all files checked in on a branch to update the copyright date if necessary. It could be a reasonable project for someone doing work experience, or an introductory project/task for a student/graduate/someone who has never dealt with git/eclipse/java/python/ruby/whatever we do to try and automate this, as I’m not sure the couple of days the script might take is worth the saving on the time it takes to just change the info. Unless we could hook that script into our git add commands.

**Comment by DominicOram** [comment]
Yh, I was going with a hook into git. Basically it seems like something so easy to automate that we shouldn't need to modify our workflow (as people will just forget).

**Comment by John-Holt-Tessella** [comment]
If we forget it isn't a big problem. It will still have copyright on (which lasts quite a long time) and we have public git history which shows the changes. It seems it is protection against people steeling the code, copyrighting it and claiming we owe them money.
