### ISSUE TITLE
Blockserver: Refactor

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1187]
As a developer I would like the blockserver code to be cleaner.

There are several possible items. Pick one and push the others to a new ticket.
1.  In block_server.py the PVDB has multiply repeated elements, use a method to replace this. There are also large switch statement in write and read. Think whether it would be worthwhile adding  the methods to the dictionary (maybe as a class). See https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/43/files for inspiration where the name changed showed common patterns.
2. In BlockServer/block_server.py line 574 the developer is forced to catch Exception which is a bit too generic. Let us try to make exceptions more specific
3. The block server has rules for the group names and configuration names (also possibly description) which the GUI reads, they are reimplemented in the blockserver as well. This code should be the same to prevent one being changed without the other. (see config_holder.py _check_name)

**Comment by DominicOram** [comment]
For point 1 a similar refactor could also occur on the pvs-on-the-fly. Currently they're stored as a dictionary of `pv : data`. If they were instead `pv : method_to_get_data` they wouldn't need to be updated all the time.

**Comment by KathrynBaker** [comment]
Lots of cahnges have happened to the blockserver since this ticket was created. Whilst refactoring in various areas is still likely required, a different approach is probably warranted by now.
