### ISSUE TITLE
GUI: Duplicate code

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1189]
uk.ac.stfc.isis.ibex.ui.synoptic.component.ComponentIcons.java and uk.ac.stfc.isis.ibex.ui.synoptic.editor.component.ComponentIcons.java are almost identical and both need to be updated in the same way when a new OPI is added.

This seems wrong, can we take out the commonality?

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/ibex_gui#229

**Comment by IsabellaRey** [comment]
on hold while jenkins warnings are sorted
