### ISSUE TITLE
Dataweb dashboard page - optional display of experiment title

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1192]
As a scientist, I want the display of the experiment title on the dataweb dashboard page to be optional, so that I can suppress its display if required (e.g. for reasons of confidentiality).

#### Acceptance Criteria
1. In the IBEX client I can toggle the display of the experiment title on/off.
1. On setting the display of the experiment title to OFF, the experiment title in the dataweb dashboard is suppressed the next time the page is refreshed.
1. On setting the display of the experiment title to ON, the experiment title in the dataweb dashboard is displayed the next time the page is refreshed.
1. The value of the experiment title display setting should default to OFF.

#### Notes
1. The control to toggle the display of the experiment title should reside in IBEX (the dashboard is just a dumb display).
1. The value of the current display setting should be persisted in instrument configuration files.
1. The URL for the dataweb dashboards is: http://dataweb.isis.rl.ac.uk/Dashboards/default.htm

**Comment by kjwoodsISIS** [comment]
Break into separate issues:
1. Update BlockServer to support a PV to toggle Title on/off
1. Update IBEX client to allow the user to toggle the Title on/off.
1. Update the web page to display the title.

**Comment by ThomasLohnert** [comment]
Pull requests for the first 2 sub-issues from the previous comment:
https://github.com/ISISComputingGroup/EPICS-isisdae/pull/8
https://github.com/ISISComputingGroup/IBEX/issues/1374

Web page still needs to be updated to utilise the PV, but I understand its currently still undergoing various changes anyway.

**Comment by ThomasLohnert** [comment]
Part 1 & 2 are implemented and merged, Part 3 is covered in https://github.com/ISISComputingGroup/IBEX/issues/1382. Closing this ticket.
