### ISSUE TITLE
GUI: Tabs in DAE experiment setup panel

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1193]
In the DAE experiment setup panel there are 3 tabs (time channels, data acquisition, periods). When the instrument is running (i.e. not in SETUP) the "send changes" button is correctly greyed out, but it also seems that moving to a different tab to view all the current settings is disabled too. Would it be possible to allow switching between these 3  tabs regardless of run state?

**Comment by IsabellaRey** [comment]
It seems that the issue is the other way round: the user can switch tabs only when the instrument is running, but not otherwise.

**Comment by IsabellaRey** [comment]
Just for traceability: what I wrote on the comment above turned out to be a bug introduced in the last sprint; I've fixed it as part of this ticket.

**Comment by IsabellaRey** [comment]
See pull requests IBEXComputingGroup/ibex_gui#225 and IBEXComputingGroup/ibex_system_tests#4

**Comment by AdrianPotter** [comment]
At the moment, the tabs are accessible and read-only, which is great. Thanks. As discussed though, as a user, there should be a visual indication that the controls are disabled (e.g. greyed out). As it stands, the controls look enabled, but don't respond which is confusing from a user perspective.

**Comment by IsabellaRey** [comment]
Jenkins is being funny with the warnings. Please wait to merge this one until I have fixed the warnings that actually come from this ticket
