### ISSUE TITLE
Document the Process for Adding new Instruments to the list

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1196]
As an IBEX support person, I want the process of adding a new instrument to the list of available instruments to be documented, so that I don't have to rely on a single individual to update the list.

#### Acceptance Criteria
1. The process of adding new instruments to the list of available instruments is documented.
1. The process should make it clear that adding a new instrument should be initiated with a new issue (for traceability).

#### Notes
1. None.

**Comment by IsabellaRey** [comment]
I've added a section at the end of https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC

I've also made it clear in the Home page https://github.com/ISISComputingGroup/ibex_developers_manual/wiki that this content is under the Deployment section

**Comment by AdrianPotter** [comment]
Thanks for the docs. I've done some additional rearrangement of the pages since there are now clearly two very separate topic on the "Deployment page". All the content is still easily accessible from the wiki home page.
