### ISSUE TITLE
EMMA and others: Generic Sample Stack OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1197]
As an IBEX support person, I want a generic sample stack OPI (if possible), so that I can control the instrument sample stack without needing an instrument specific sample stack.
#### Acceptance Criteria
1. A generic sample stack OPI can be selected in the IBEX GUI.
2. The generic sample stack OPI supports variable numbers of axes.
#### Notes
1. Number of axes could be configurable as a macro setting.
2. Axes labels could be configurable as macro settings.
3. In some cases it may be preferable to have instrument specific sample stack OPIs, so having a generic sample stack OPI does not preclude having instrument specific sample stack OPIs.

**Comment by AdrianPotter** [comment]
- [ ] Close related IMAT ticket when complete

**Comment by kjwoodsISIS** [comment]
It would be useful to implement this ticket for EMMA.  EMMA has only a limited number of axes, but we could use EMMA as a vehicle for implementing this ticket (in place of #2366).

**Comment by kjwoodsISIS** [comment]
IMAT would like a proper sample stack OPI within six months  - when they start getting real users.
