### ISSUE TITLE
Make Dataweb & GUI display of Blocks consistent

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1198]
As a scientist, I want the Dataweb & GUI views of Blocks on my instrument to be consistent.
#### Acceptance Criteria
1. The Blocks displayed on the dataweb should be consistent with those displayed on the IBEX GUI.
   1. Blocks should be displayed with the same number of significant figures
   2. Blocks should be displayed with units
#### Notes
1. See attached screenshots.
   1. The screenshot below shows how Blocks are displayed by the GUI.  The number of significant figures is limited, units (if available) are displayed.  ![gui_larmor_blocks](https://cloud.githubusercontent.com/assets/7249337/15219760/dd9c5fa6-185c-11e6-8af3-a8f65df69e9e.PNG)
   2. Dataweb_LARMOR_Blocks.PNG shows how the same Blocks are displayed by the Dataweb.  Some blocks have reasonable numbers of significant figures; others have unfeasibly large numbers of significant figures.  None have units.

![dataweb_larmor_blocks](https://cloud.githubusercontent.com/assets/7249337/15219784/fb4a7f92-185c-11e6-943b-3e0ea8065f49.PNG)

**Comment by kjwoodsISIS** [comment]
It may be that the Dataweb system is not using the EPICS precision field - it should.

**Comment by DominicOram** [comment]
Fixed by #2069
