### ISSUE TITLE
LARMOR: ISISStat - drivers

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1199]
As a scientist, I need ISISstat drivers, so that I can control the ISISstat cryostat.

#### Acceptance Criteria
1. I can control the ISISstat from IBEX.

#### Notes
1. Click [ISISstat cryostat](http://www.isis.stfc.ac.uk/sample-environment/low-temperature/isisstat/isisstat14139.html) for a description of the device.
1. Apparently, the Mercury iTC controls the etemperature.  See e-mail in comment below.
1. VIs for this device exist already.  It may be possible to implement this issue using lvDCOM (see [LVDCOM](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LVDCOM-auto-generate-xml) and [LVDCOM-IOC-boot](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LVDCOM-IOC-boot)).
1. VIs do exist and lvDCOM was used.
1. Currently only the temperature control is implemented and there is no simulation mode or OPI. There will be follow up tickets for this.

##### Acceptance Criteria

1. There are three temperature cards that need to be monitored, these can be switched on in the IOC by adding macros (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC).
    1. Temp 1 (Sample rod)
    1. Temp 2 (VTI_DB6)
    1. Temp 3(PT2_DB7.T1)
1. For each temperature card, user can:
    1. View
        1. Temperature (TEMP)
        1. Temperature Set point (TEMP:SP:RBV)
        1. Name of sample (NAME)
    1. Set
        1. Temperature Set point (TEMP:SP)

Also check the other PVs but these are less important.

You will need the vi installed with the mercury controller on..

**Comment by kjwoodsISIS** [comment]
> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 10 May 2016 11:12
> To: Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Howells, Gareth (STFC,RAL,ISIS)
> Subject: FW: ISISStat2 and EPICS
> 
> Hi,
> Gareth was included on this reply but isn’t in today.
> Please can you add the Mercury VI to the list of requirements for Larmor next cycle.
> 
> Thanks
> 
> Rob
> 
> From: Down, Richard (STFC,RAL,ISIS) 
> Sent: 10 May 2016 08:40
> To: Dalgliesh, Robert (STFC,RAL,ISIS); Church, Andy (STFC,RAL,ISIS); Charleston, Thomas (STFC,RAL,ISIS); Haynes, Richard (STFC,RAL,ISIS); Major, Robert (STFC,RAL,ISIS)
> Cc: Howells, Gareth (STFC,RAL,ISIS)
> Subject: RE: ISISStat2 and EPICS
> 
> Hi Rob,
> 
> You will need to add a Mercury VI; I’m not sure what usability there is with the VI so please talk to Gareth Howells.
> 
> Regards
> 
> Richard. 
> 
> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 09 May 2016 17:33
> To: Church, Andy (STFC,RAL,ISIS); Charleston, Thomas (STFC,RAL,ISIS); Haynes, Richard (STFC,RAL,ISIS); Down, Richard (STFC,RAL,ISIS); Major, Robert (STFC,RAL,ISIS)
> Subject: ISISStat2 and EPICS
> 
> Hi,
> There is a further snag with running the ISISStat2 on Larmor and that is the lack of Labview controls.
> 
> Can someone let me know what controllers are needed to operate the cryostat.
> e.g. Eurotherms, bespoke Oxford controllers etc. 
> If it’s easier for me to pop over to the mag lab and talk it through I’m happy to do so.
> 
> Sorry to be a pain
> 
> Rob

**Comment by kjwoodsISIS** [comment]
> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 07 May 2016 10:14
> To: Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Kockelmann, Winfried (STFC,RAL,ISIS)
> Subject: New EPICS drivers
> 
> Hi Kevin, Freddie,
> Between Larmor and IMAT we have a few additional requests for EPICS drivers.
> I’ve spoken to Freddie about most of this.
> 
>    1) We will be running with the ISISStat on Larmor early next cycle this will require the drivers to run the cryostat but also there is a power supply to drive the magnet that it will sit in. We will have vi’s for all of this already.
>    < ... snipped ... >

**Comment by John-Holt-Tessella** [comment]
I have started a page here with info
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC

**Comment by John-Holt-Tessella** [comment]
Need to download diamond resource and talk with Rob

**Comment by John-Holt-Tessella** [comment]
This needs to be active on POLREF too which does not run epics. Wait until Freddie comes back to sort this out.

**Comment by John-Holt-Tessella** [comment]
Wait for direction. See https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket1199_mercury_controller and https://github.com/ISISComputingGroup/EPICS/tree/Ticket1199_mecury_controller

**Comment by John-Holt-Tessella** [comment]
ISIS "support" module: https://github.com/ISISComputingGroup/EPICS-MercuryiTC/pull/1
EPICS base: https://github.com/ISISComputingGroup/EPICS/pull/25
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/37
