### ISSUE TITLE
LARMOR: EPICS driver for PI Rotation Stage

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1201]
As a scientist, I want an EPICS driver for the PI Rotation Stage, so that I can control it from IBEX.

#### Acceptance Criteria
1. I can control the PI Rotation Stage from IBEX.

#### Notes
1. How will the PI Rotation statge be controlled? - via the existing EPICS motor record or via a specific PI driver?
1. There are EPICS drivers for [PI devices](http://www.aps.anl.gov/epics/modules/manufacturer.php#Physik%20Instrumente) on the EPICS web-site.

**Comment by kjwoodsISIS** [comment]
> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 07 May 2016 10:14
> To: Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Kockelmann, Winfried (STFC,RAL,ISIS)
> Subject: New EPICS drivers
> 
> <... snipped ...>
>    3) The PI rotation stage that I bought for OffSpec is being used quite a lot for Winfried’s imaging work. Can we get the existing vi converted over. We have been using the SDTest driver but it’s probably time to get it done properly. Genoveva is looking at buying a second one for IMAT.

**Comment by FreddieAkeroyd** [comment]
The motor record has built in support for  PI GCS2 generic command set which looks to cover the C867 controller on LARMOR.  From a look at the source code it is configured via PI_GCS2_CreateController() and arguments

static const iocshArg PI_GCS2_CreateControllerArg0 = {"Port name", iocshArgString};
static const iocshArg PI_GCS2_CreateControllerArg1 = {"asyn Port name", iocshArgString};
static const iocshArg PI_GCS2_CreateControllerArg2 = {"Number of axes", iocshArgInt};
static const iocshArg PI_GCS2_CreateControllerArg3 = {"priority", iocshArgInt};
static const iocshArg PI_GCS2_CreateControllerArg4 = {"stackSize", iocshArgInt};
static const iocshArg PI_GCS2_CreateControllerArg5 = {"moving polling time [msec]", iocshArgInt};
static const iocshArg PI_GCS2_CreateControllerArg6 = {"idle polling time [msec]", iocshArgInt};

**Comment by FreddieAkeroyd** [comment]
Tested in my office , all seems to be OK. Added notes on baud rate setup and resolution setting to IOC eadme
