### ISSUE TITLE
genie_python: tidy up the globals hack

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1202]
Originally I put in a hack to get scripts loaded by the user into the correct context.
I have found a slightly neater hack.

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/22

**Comment by John-Holt-Tessella** [comment]
Tested : 
set_instrument("NDXDEMO") 
load_script("c:/project/genie_script.py")
my_test()

from both scripting console in IBEX and command line
