### ISSUE TITLE
Linux Installation for Client

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1204]
As a user I would like to be able to download and install the client to run in linux.
Carry on work and create a linux client so I can install and run a client in linux.

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/building-on-linux
for some notes

**Comment by KathrynBaker** [comment]
Given the use on linux for remote work in 2020 onwards, whilst there is still work to do this ticket is no longer applicable.

**Comment by FreddieAkeroyd** [comment]
Work completed in #5509
