### ISSUE TITLE
Linux install for backend

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1205]
As a user I wish to install the backend on a linux client.

Carry on work started in #1204

**Comment by John-Holt-Tessella** [comment]
As part of this update path in `uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java` for linux versions. Probably within a script statement or using a config file

**Comment by KathrynBaker** [comment]
Things have changed a lot since this ticket, and more is underway, closing in favour of new requirements and tickets that will become apparant under new projects.
