### ISSUE TITLE
MUON FRONT END: Danfysik changes

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1208]
NEEDED SEPTEMBER 2016 CYCLE

The suggestions for these changes have been discussed via email and in person, and these are what should be needed.

As an IBEX user I want to be able to use multiple types of Danfysik PSU without having to make alterations to anything other than their own setup when they are changed.

**Acceptance Criteria**
1. The Changes listed below are all made

**Notes**
1. #1170 should be merged before doing this ticket

**Changes to make**
Changes to the protocol files (in support)
- Create a new folder structure for the protocol files, creating subfolders within the protocols folder, one for "ORIGINAL_MICE", one for the "DFK8000" and one for the "DFK8800"
- Put a copy of the original protocol files into the ORIGINAL_MICE folder, note that these will need to be from the first commit of the repo, not the current version in master
- At the top level create dfkps_common.proto, with the content detailed in the comments
- Within DFK8000 and DFK8800 create dfkps.proto with appropriate content as detailed in the comments

Changes to the db files (in ioc)
- Create a db file with the standard items as detailed in the comments
- Create status db files for various status response types (character or hex)
- Create a db file that separates out the calibration aspects, and allows the calibration to be updated whilst running (as per the Eurotherm calibrations), details in the comments for everything except the changing whilst running
- Create a db file for the polarity records, as not all Danfysik power supplies are bipolar, details in the comments

Make sure that there is a 1:1 calibration file that can be used as a default which is saved within the IOC

Changes to the st.cmd files (in ioc)
- A number of new macros are needed to handle the various settings as follows:

| Macro | Purpose | Default Value |
| --- | --- | --- |
| BAUD | Specify the Baud rate of the system | `9600` |
| BITS | Number of bits for the asyn serial protocol | `8` |
| PARITY | The parity for the asyn serial protocol | `none` |
| STOP | The number of stop bits for the asyn serial protocol | `2` |
| BIPOLAR | Specify if the PSU is `BIPOLAR` or `UNIPOLAR` | `BIPOLAR` |
| DEV_TYPE | The type of the device, e.g. `8000`, `8800` or `9100` | `8000` |
| CALIBRATED | Whether or not the PSU should use a file to translate from the Current reading to a field value | `CALIB` |
| CALIB_PATH | Path to the folder with calibration files | local path to folder with the calibration file from change 3 |
| CALIB_FILE | The name of the calibration file to use | The file created in change 3 |
| STATUS_TYPE | The type of status file to use, either `HEX` or `CHAR` | `HEX` | 
- Use the DEV_TYPE macro to specify the protocol file to use, if it is 8800 use the DFK8800 folder, otherwise use the DFK8000 folder (more changes like this may be needed for other models in the future)
- Create st-xxxx.cmd for the 8000 and 8800 to cover differences in behaviour, details in the comments
- Between
```
##ISIS## Load common DB records 
< $(IOCSTARTUP)/dbload.cmd
```
and 
```
## Load our record instances
#dbLoadRecords("db/xxx.db","user=faa59Host")
```
call the appropriate st-xxxx.cmd file  using `<st-$(DEV_TYPE)`
- Load the common db in all cases
- If the PSU is UNIPOLAR don't load the polarity db (`stringiftest("POL", "$(POLARITY=BIPOLAR)")` at some point, then before the load records use `$(POL) dbload...`. If the macro is set and is not BIPOLAR the POL macro should be "#" so the line will not run)
 - If the PSU is not calibrated don't load the calibration db (checks and interactions as for the polarity, note that the path and file use defaults of 1:1, and this defaults to calibrated, otherwise the field changes will be lost)
- Load the appropriate status records

**Comment by KathrynBaker** [comment]
Some settings which are different for different for each PSU type so far, whilst not necessarily something to include in these files, it might be helpful in the future.

| Model Number | Baud Rate | Number of Stop Bits | Polarity |
| --- | --- | --- | --- |
| 8000 | 9600 | 2 | Bipolar |
| 8800 | 19200 | 2 | Unipolar |
| 9100 | 115200 | 1 | Bipolar |

**Comment by KathrynBaker** [comment]
Commands for the common protocol file:

| Protocol Command | Device Command | Reply |
| --- | --- | --- |
| adc | `AD \$1` | `%d` |
| cmd | `CMD` | `%{LOC|REM}` |
| cmdsp | `%{LOC|REM}` | |
| pol | `PO` | `%{+|-}` |
| polsp | `PO%{+|-}` | |
| powersp | `%{F|N}` | |
| reset | `RS` | |
| first | `S1FIRSTH` | `%x` |

Commands for the 8000 protocol file:

| Protocol Command | Device Command | Reply |
| --- | --- | --- |
| dac | `DA \$1 %d` | |
| dacsp | `DA \$1` | `\$1 %d` |
| status | `S\$1H` | `%x` |

Commands for the 8800 protocol file:

| Protocol Command | Device Command | Reply |
| --- | --- | --- |
| dac | `WA %d` | |
| dacsp | `WA 1` | `\$1 %d` |
| status | `S1` | `%c` |

**Comment by KathrynBaker** [comment]
st-8000.cmd needs to include the following:

## Initialise the comms with the PSU
asynOctetConnect("DFKINIT","L0")
asynOctetWrite DFKINIT "UNLOCK\r"

**Comment by KathrynBaker** [comment]
st-8800.cmd needs to include the following:
```
## Initialise the comms with the PSU
asynOctetConnect("DFKINIT","L0")
asynOctetWrite DFKINIT "ADR 000\r"
```

**Comment by KathrynBaker** [comment]
NOTE: When this is done, and is being added to the release we will need to make sure that the configs/syonptics etc. on LARMOR are corrected to use more appropriate PVs than they currently do

**Comment by KathrynBaker** [comment]
There is some dev work for SECI that involves adding the control of the SLEW rate. This is not a standard feature of the PSUs, it requires a specific hardware change, and possibly some interactions using ESC characters. However, as it is about to be added there, it should probably be considered in with this. It is only available to the 8500 models, so is probably best in the central protocol file, but with a specific db that can be loaded based on a USE_SLEW macro. The commands to/from the PSU are as follows:

Command | Purpose
R(x) | Read slew DAC 1 or 2 (replace x with 1 or 2)
R3 | Read slew DAC 1 absolute
W(x) | Write slew DAC 1 or 2 (replace x with 1 or 2), and provide a value
W3 | Write slew DAC 1 absolute, provide a value

These would be standard read and :SP PVs.

**Comment by kjwoodsISIS** [comment]
@KathrynBaker , @ThomasLohnert what is your estimate for the story points for this issue?

**Comment by ThomasLohnert** [comment]
2 perhaps? It's taking me a while but I'm not sure how much of it is the task being complex and how much is me just having to learn all the EPICS stuff to be honest.
