### ISSUE TITLE
IOC (and maybe motor) aliasing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1217]
It would be useful for IOC's for fixed beamline equipment to be able to change their namespace e.g. KEPCO_01 to be aliased to something more memorable. Something like and ioc looking for a per-instrument <iocname> file that contains an alias mapping. Will also need such a scheme for motors and with a mixture of Galil, MacLennan, beckhoff, PI rotation stages, it is not clear who MTR0505 should be. etc.

**Comment by KathrynBaker** [comment]
I think this might be covered less generically under #1194, where I specified PSUs.

Regards,
Kathryn

**Comment by kjwoodsISIS** [comment]
We'll focus on motors initially.  If there's time, extend to all IOCs (otherwise create a new issue).

**Comment by KathrynBaker** [comment]
Motor aliasing does exist, no other aliasing has been made available. Closing in favour of new considerations that upcoming projects may require,
