### ISSUE TITLE
GUI: add extra info to log message about instruments PV

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1219]
When the dialog for switching instrument is opened, a log message is displayed to indicate whether the PV containing the list of instruments was read correctly.

Sometimes the list doesn't get populated, and the log message says that the content of the PV wasn't parsed correctly.

Change the log message so that it also prints the content read from the PV, because it's not clear why it should work most of the times, but not always.

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/ibex_gui#227

Hopefully this fixes the actual bug too

**Comment by AdrianPotter** [comment]
The extra information as been added as requested but I've seen at least once instance where the PV is null on start up.

The current design of the instrument list doesn't properly use the observable pattern and potentially creates a 20s start up lag. The goal of this ticket has been achieved so I'm going to close it, but I'll create a new ticket to do some re-factoring.

**Comment by AdrianPotter** [comment]
Refactoring suggested as ticket #1222
https://github.com/ISISComputingGroup/IBEX/issues/1222
