### ISSUE TITLE
Set COM ports via GUI

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1220]
The intention was to set the COM ports via the edit config dialog using the IOC macros.

This needs to be implemented. The GUI does what it is supposed to, but the IOCs need to have COM port as an option to set.

BTW: this is based on a complaint from Rob

**Comment by KathrynBaker** [comment]
Have added the following to globals.txt on LARMOR to cover this:
```
# Values taken from st.cmd files
EUROTHERM_01__PORT=COM21
EUROTHERM_02__PORT=COM22
JULABO_01__PORT=COM17
JULABO_02__PORT=COM18
# Both Kepcos had the same values
KEPCO_01__PORT=COM19
KEPCO_02__PORT=COM19
# Used the TPG values from above
TPG300_01__PORT=COM13
TPG300_02__PORT=COM14
```
It might be a good idea to have a look at the contents of that file sometime and make sure things are current - I've doubled up on the Port addresses for the TPG300 as I'm renaming it, but there are a lot of commented lines and similar that may or may not be needed long term.

**Comment by KathrynBaker** [comment]
Assuming no requirements to macro anything else until #1246 has been done, this is ready for review. Other than the macros mentioned in the comment above, there are no changes that are needed, IMAT has no serial devices that have been altered.

**Comment by KathrynBaker** [comment]
A little investigation elsewhere actually found that the GUI isn't doing what it needs to, as changes via the GUI are not being picked up at the appropriate level of the IOC startup. This fix will be covered by #1281

**Comment by John-Holt-Tessella** [comment]
Did we need to add the macros into a config file in the relevant IOC boot directory so they appear as macro's to set in the IBEX gui?

**Comment by FreddieAkeroyd** [comment]
Yes, they should be added to config.xml in the iocBoot area, though config.xml support xinclude so if you have several iocs with the same set of macros you don't need to repeat the file contents (see GALIL01 ansd GALIL02 for an example)

**Comment by FreddieAkeroyd** [comment]
#1281 should now be fixed BTW

**Comment by KathrynBaker** [comment]
I’d not even known the config.xml files existed, I’ll move 1220 back to in progress and get those added/altered as appropriate for the PORTs I created.

Regards,
Kathryn

**Comment by John-Holt-Tessella** [comment]
I have added the being able to include configs information to the wiki at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches (this is a new page if you could check the page's accuracy that would be great)
