### ISSUE TITLE
IBEX: Instrument list refactoring

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1222]
At the moment, the way the instrument list is read for the GUI is a little unreliable and potentially might result in a 20 second startup lag. 

As a developer I would like the instrument list code to be refactored to properly implement the observable pattern:
- InstrumentListObservable contains, but is not in itself, an observable so should be renamed to avoid confusion
- Instrument.instruments() treats the InstrumentListObservable class as a collection wrapper rather than a true observable. For each time Instruments() is called, a new observable is created, it has to wait to connect to the PV, and then gives the values. What should happen is the observable is created once and then has an observer to update a target as the PV value changes. I would suggest that the Instruments class, as a singleton itself, should contain a static observable and a (private) static observer. The constructor of Instruments should initialize the observer and register it with the observable. When a value is registered by the observable, the collection of objects returned by Instuments() should be updated (wherever it ends up being stored).

**Comment by DominicOram** [comment]
Fixing https://github.com/ISISComputingGroup/IBEX/issues/1110 first as it should make this one a little easier.
