### ISSUE TITLE
Memory leak in IocLogServer

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1223]
java.exe on NDXMAT for the IocLogServer is currently using ~1GB of memory

**Comment by John-Holt-Tessella** [comment]
Impeded until we check the NDXDemo no longer is suffering from memory issues

**Comment by John-Holt-Tessella** [comment]
NDXdemo is better I am not sure it is completely cured. After 1 week it is using only ~100MB (heap ~60MB) vs 1.5GB. I think that this is still increasing but very slowly

**Comment by John-Holt-Tessella** [comment]
Acceptance testing:

1. Create a message ensure that it is logged to the correct host, client etc
1. Create a log message for a new application. client or host. Ensure there are no errors thrown
1. Check that the memory taken is not huge (less than 200MB).

**Comment by AdrianPotter** [comment]
C:\Instrument\Apps\EPICS\ISIS\IocLogServer\master\dev-tools\ioc_message_simulator.py for generating messages

**Comment by AdrianPotter** [comment]
Confirmed that the memory taken up by the process does increase with new messages, but doesn't grow unreasonably large. It stayed under 100MB for the duration of the test.

**Comment by AdrianPotter** [comment]
Looking at the java visual VM, the used heap is being garbage collected much more effectively now and consequently the overall heap size is remaining roughly constant after several 10000 message bursts. Just reviewing the code in the PR before completing.

**Comment by AdrianPotter** [comment]
Just a couple of fixes needed:

- Update copyright statements
- Check if "protected" access modifiers are needed in some cases

**Comment by John-Holt-Tessella** [comment]
Added copyright and remove protected in favour of default access modifier.
