### ISSUE TITLE
Adapt Nicos daemon to read from xml

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1224]

**Comment by kjwoodsISIS** [comment]
We need to support the notion of a "scan table" - i.e. the system is stepped through a sequence of changes to a variable (as if each new value of the variable defined a row in a table).

**Comment by DominicOram** [comment]
After discussion this ticket has been replaced by more specific tickets (https://github.com/ISISComputingGroup/IBEX/issues/1365 and https://github.com/ISISComputingGroup/IBEX/issues/1364)
