### ISSUE TITLE
GUI refactoring: create a XMLUtils plugin

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1226]
Currently we have XML utils classes in three plugins: ibex.devicescreens.xml, ibex.opis.desc and ibex.synoptic.xml

These three classes do essentially the same thing.

Refactor so we have a single generic XMLUtils class in its own package

NOTE: the ibex.devicescreens.xml plugin is in the Hackathon GUI branch, which at the time of writing hasn't been merged in the main branch yet. If it hasn't been merged when this ticket is picked up, you should probably work on that branch

**Comment by IsabellaRey** [comment]
NOTE: this may need a bit thinking though, because fields like the marshaller are static: when the schema gets set, it is set for everyone using the class, but e.g. synoptics have a different schema than device screens. Somehow we still need to allow for different co-existing schemas.

**Comment by KathrynBaker** [comment]
Fixed as part of #2074
