### ISSUE TITLE
GUI: broken target platform [urgent]

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1228]
With a fresh clone of ibex_gui and a fresh installation of eclipse from \\isis\inst$\Kits$\CompGroup\ICP\Developer Tools\\eclipse-ibex-v3.1, setting the target platform fails, as http://download.eclipse.org/technology/nebula/archives/Q42015/release/ doesn't exist anymore!!

John and I have tried on my machine to use http://archive.eclipse.org/technology/nebula/Q42015/release/ instead, and importing only the Nebula Visualization Widgets.

This seems to work for elementary checks, but as it seems to be a quite fundamental change, we feel it would require a more complete system test

**Comment by IsabellaRey** [comment]
There is a branch in ibex_gui with the changes in targetplatform to be checked

**Comment by IsabellaRey** [comment]
The maven build fails importing files from eclipse repositories too, even with the gui from the master branch.

It's looking like eclipse have moved/deleted files within their repositories overnight, as Adrian had a build working just yesterday

**Comment by AdrianPotter** [comment]
I've searched Google, and though the Eclipse forums and can find no explanation for the outage. I've posted a request on the Eclipse forums and am currently awaiting a reply.

**Comment by AdrianPotter** [comment]
Remove impeded flag. I kept thinking. 

Go to:

http://download.eclipse.org/eclipse/updates/3.8/

and you'll get a page saying that it's a repo page that you should open in Eclipse. On the left of the main image there's a like that says "Show directory contents". It's not obvious. Looking at the directory contents, the XML files we're looking for seem to be wrapped in a JAR file. We may need build.bat to get the JAR and then extract the XML or deal with the JAR directly. I'll keep investigating.

**Comment by AdrianPotter** [comment]
Our proxy settings were blocking access to the updates site:

https://github.com/ISISComputingGroup/ibex_gui/pull/232

**Comment by AdrianPotter** [comment]
Equivalent maven settings for IOCLogServer:

https://github.com/ISISComputingGroup/EPICS-IocLogServer/pull/3
