### ISSUE TITLE
Upgrade CS-Studio

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1229]
The bug encountered in ticket #1206 is owing to a bug in our version of CS-Studio. The bug was fixed in the source in October 2014 and has been available from version 3.3.11 since December 2014. To clear the bug, we need to upgrade our version of CS-Studio.

Should we upgrade CS-Studio? If so, to which version? We can upgrade to the latest sub-release of our present version (i.e. to 3.3.11), or we can go all the way and migrate to 4.2.3:

`http://controlsystemstudio.org/controlsystemstudio/current.html#`

The former should fix some bugs without too much impact on our current setup. The full migration will require upgrading our Eclipse platform as well.

**Comment by kjwoodsISIS** [comment]
We agreed that it would be worth upgrading to v3.3.11 (if possible).  Upgrading to v4.2.3 (or later), should wait until we have migrated to Eclipse 4.

**Comment by AdrianPotter** [comment]
See some discussion on ticket #1968
