### ISSUE TITLE
genie_python install script not working

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1230]
When running the build_pthon.bat file as described on the wiki:

```
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-and-installing-genie_python
```

The script runs into a lot of access denied errors while accessing files from the directory:

```
p:\Kits$\CompGroup\ICP\
```

The final lines of my log are:

```
p:\Kits$\CompGroup\ICP\Client\genie_python\Python\Tools - Access is denied.
p:\Kits$\CompGroup\ICP\Client\genie_python\Python - Access is denied.
p:\Kits$\CompGroup\ICP\Client\genie_python\README.txt - Access is denied.
Access is denied.

(Python) C:\Instrument\Dev\genie_python\package_builder>if 0 NEQ 0 exit /b 0

(Python) C:\Instrument\Dev\genie_python\package_builder>"C:\Instrument\Dev\genie
_python\package_builder\sleep" 10

(Python) C:\Instrument\Dev\genie_python\package_builder>mkdir p:\Kits$\CompGroup
\ICP\Client\genie_python
A subdirectory or file p:\Kits$\CompGroup\ICP\Client\genie_python already exists
.

(Python) C:\Instrument\Dev\genie_python\package_builder>if 1 NEQ 0 exit /b 1
```

**Comment by AdrianPotter** [comment]
I've updated the wiki so that in future developers will just use the standard workflow. The existing script and documentation still have value so I've left them in place.

**Comment by IsabellaRey** [comment]
Hi Adrian,
Just to be sure: as part of this ticket you haven't modified any of the files in genie_python?
Is the "Building" section in the docs any relevant if the script doesn't work? Maybe you could just add a line or so to make it more explicit if the Building section refers to a different use case than the Development Workflow section (as in, to indicate that you don't need to do both)?

**Comment by FreddieAkeroyd** [comment]
The error is due to build_python.bat trying to install back to kits$ which you did not have permission to do. I've put in a pull request as per #1317 so that build_python.bat will work locally and can then be used as a good check that all is OK. I've also updated the wiki notes
