### ISSUE TITLE
ZOOM: Omron FINS PLC interactions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1232]
This is a placeholder, as yet the PLC has not been designed enough for any computing tasks to be undertaken.  (Update: as of 29/11/2016, the PLC is still not sufficiently ready for use).

As an instrument Scientist on ZOOM I want to be able to interact with the PLC system via IBEX.

#### Notes ####
1. This is likely to be something similar to SANS2D
1. This will be an Omron PLC, as such it should be possible to treat this as a setup act once we have the memory map from the appropriate teams, and as such shouldn't take too long.
1. We could chase up the presence of the computing group PLC, and ask for the PLC logic to be put on that and test the interactions separate to the production PLC.
1. The intention is that the PLC will be used to control all or some of the following:
   1. "Fast Shutter" (as used on SANS2D)
   1. "Pneumatic Shutter" (also as used on SANS2D)
   1. Pfeiffer TPG 300s

**Comment by KathrynBaker** [comment]
Ideally in place for ZOOM startup May 2nd 2017, there are alternative methods to access this information, but they are not ideal for the running of the instrument

**Comment by KathrynBaker** [comment]
For IP address etc. talk to me, memory map is now available as well - currently with me as well

**Comment by KathrynBaker** [comment]
This PLC is now on and connected to the network (28/4/17 11:20)

**Comment by KathrynBaker** [comment]
Memory map added to wiki - see the instrument page for that information

**Comment by KathrynBaker** [comment]
Removed awaiting as all the data is now available, added Proposal as whilst it was not needed in the end for May will be needed in September 2017

**Comment by kjwoodsISIS** [comment]
Please attach the data, or provide a link to it (e.g. put the data in ICP Discussions if you don't want to put it on GitHub).

**Comment by KathrynBaker** [comment]
The memory map is available - see the instrument page or the corrected link above, the only item I haven't put here, and haven't yet figured out where to put it as information is the IP address of the PLC - it is not appropriate in ICP discussions as far as I'm concerned, and certainly not appropriate for GitHub.

**Comment by KathrynBaker** [comment]
For info, a mock of the GUI could be:
![ZOOM PLC.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56cf1d9deeb6921300dcafd8/125516c66e82c728ace21e0d46d2bbb50ec2b385acabf301b44fff9e2c4533317346f67d7383b12dbc1028505d5c4cae405b5f44fbfd8c7da4e02e6c981e5ab38532022d8c6853beb2901db90bbb24824880b5b48f4cc8ec3e25f5c6.png)

This will need verifying and tweaking I should think upon discussion with the instrument scientists, it is in the IBEX balsamiq folder.

There should also be a heartbeat as on LARMOR.

**Comment by KathrynBaker** [comment]
If not already reviewed, consider reviewing #2103 before undertaking this ticket

**Comment by KathrynBaker** [comment]
Few things noticed so far (full review not complete):

Missing instrument notes in release notes (shouldn't include the IP address, but there should be a reminder for adding the macro and the st.cmd in settings)
No SPs for the buttons, everything is separated, which means we can't create blocks on these items - which is handy
Similarly, the buttons are all longouts - which is what the PLC needs, but it would be better to have them as booleans for interacting with, and they do need to revert back to the original value (which the PLC does underneath automatically) - although the db could just send the command whatever value is set, with a camonitor on `:VACUUM:MONITOR:2:INSERT` I could see it go 1 once, but then never again, and that position could be changed on the PLC (reset it to 0 in the script)
Similar location, that ca monitor on `:VACUUM:MONITOR:2:INSERT` had a link invalid issue listed

**Comment by samueljackson92** [comment]
This should be good for retesting now whenever you're ready.

**Comment by FreddieAkeroyd** [comment]
Hi Sam,

zoom-vacuum-gauges    is almost a direct copy of    imat-plc-press   - would it be possible to re-use a common implementation between these two?

I'm a little concerned about the potential performance of the current implementation having worked with these PLCs before, for example address 519 is read 14 separate times as each bit is read individually. It would be more efficient to read the address once and then split out the bits from the DB record. There is an example of doing this in   imat-plc-attn-main   which makes use of an   mbbiDirect   record to split off the bits.

**Comment by samueljackson92** [comment]
@FreddieAkeroyd Both of those sound like sensible suggestions to me.

**Comment by samueljackson92** [comment]
@FreddieAkeroyd I've updated this to use the `mbbiDirect` record for all the single bit reads. I have also changed this to share the common implementation.

**Comment by KathrynBaker** [comment]
There is a slight problem with the readback from the gauges. When connected to the ZOOM PLC I got some very worrying readings, for example, gauge 1 was reading 3e98, which is a little worrying as a pressure. I went to check the HMI and could see that it is actually likely to be 9.8e3. I didn't check on the status of the monitors etc. but it might be worth a walk down and check once this is sorted. (For reference the PLC and HMI are on the raised floor between the side of ZOOM and the ZOOM counting house, at the moment.)

**Comment by FreddieAkeroyd** [comment]
comparing imat and zoom substitution files, the higher numbered PLC address is the exponent in the imat files whereas it is the lower address in the zoom files, so it looks like the PLC addresses just need to be swapped round as @KathrynBaker suspected

**Comment by samueljackson92** [comment]
@KathrynBaker @FreddieAkeroyd I shall take a look at this today.

**Comment by samueljackson92** [comment]
@KathrynBaker @FreddieAkeroyd This is swapped now. Numbers look much closer to what Kathryn is expecting to see.
