### ISSUE TITLE
ZOOM: Live View

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1235]
As a scientist on ZOOM I want to be able to view live detector data

**Acceptance Criteria**
1. There is a live view

**Notes**
1. This is a reproduction of functionality used on SANS2D
2. The solution to this varies based on the DAE being used by the instrument, will need to check which DAE is planned when this ticket is undertaken.

**Comment by KathrynBaker** [comment]
Adding to the list, although this is likely to need some help from Freddie

**Comment by kjwoodsISIS** [comment]
We really ought to have a description, or even a specification, of what the "Live View" is.  This ticket is the opportunity to create that description.

**Comment by kjwoodsISIS** [comment]
Pair up on this ticket to share the knowledge.

**Comment by FreddieAkeroyd** [comment]
Requires #2100 as starter
