### ISSUE TITLE
ZOOM: GUI for the DMS

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1236]
As an instrument scientist on ZOOM I want to be able to control the DMS from IBEX.

Acceptance Criteria
1. There is an OPI for the DMS

Notes
1. DMS stands for the Detector Motion System
2. Note that the axis configuration (axes names, associated files) should be created as part of this ticket.
3. This is galil driven motion of multiple axes:
* Disk Beam Stop 1 X
* Disk Beam Stop 1 Y
* Disk Beam Stop 2 X
* Disk Beam Stop 2 Y
* Strip Beam Stop
* Detectors
* Baffle

**Comment by KathrynBaker** [comment]
Moving to an appropriate sprint for shutter open date

**Comment by IsabellaRey** [comment]
NOTE: as part of this ticket I found that the axis.db file in the axis support module was missing an MTR_able PV, which was showing as Disconnected when drilling down from the DMS OPI to the motor details.
I've fixed this as part of the ticket.

**Comment by IsabellaRey** [comment]
Please check both the GUI PR and the axis support module PR

**Comment by AdrianPotter** [comment]
Looks good. A few points:

- Please could there be some documentation for how to set up the DMS, as described in the PR. I've done something similar for the PGC (https://github.com/ISISComputingGroup/IBEX/wiki/PGC). Note the comment about adding the extra line in the axes.cmd file, I fell into that trap whilst testing.
- The `View motors` button isn't aligned with the surrounding text boxes and the spacing is greater than the other elements. Please could the right end of the button be aligned with the right extent of the text boxes. horizontal extent might be greater than the text boxes, but not if it doesn't need to be. Similarly reduce the right padding between the edge of the text boxes and the group box.

**Comment by AdrianPotter** [comment]
Will need picking up by someone else since Isabella is on maternity leave. Fixes are quite straightforward.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/IBEX/wiki/DMS
