### ISSUE TITLE
ZOOM: Limit permission to move via software

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1237]
As a scientist on ZOOM I want to make sure that there are software controls on things which are not safety critical, but that should still not be allowed to occur in certain situations, such as the detectors should not be moved when the HV is on.

**Acceptance Criteria**
1. There is a mechanism to limit motion based on other items

**Notes**
1. This is probably best done via SNL
2. The full list of states and what is allowed needs to be refined
3. There is certainly a need to disallow motion under vacuum, or when the HV is on
4. This may effect multiple areas of motion, e.g. DMS and PGC

**Comment by kjwoodsISIS** [comment]
Plan the solution first.  Raise new tickets to implement.

**Comment by John-Holt-Tessella** [comment]
Impeded while I sort the meeting

**Comment by kjwoodsISIS** [comment]
Tickets created: #1864, #1865, #1866, #1867, #1868.
Discussion on [Inhibitor ](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor) wiki page.
