### ISSUE TITLE
ZOOM: GUI and axis setup for the sample stack

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1238]
As a scientist I want to be able to control the sample stack from IBEX

#### Acceptance Criteria ####
1. It is possible to control 8 out of the 9 sample stack axes from both a command line and via a GUI (see note 4.i regarding the one axis that cannot be controlled).
2. There is an OPI for the ZOOM Sample Stack, which allows control of all the axes (as noted below).

#### Notes ####
1. The entire ZOOM sample stack consists of a JJ X-ray 7-axis sample stack mounted on rails ([schematic diagram](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/ZOOM/ZOOM_Sample_Stack_Schematic.pptx))
1. The entire ZOOM sample stack will have, in effect, 9 degrees of freedom.
   1. 2 of the 9 degrees of freedom relate to the wholesale motion of the sample stack
      1. along the direction of the beam (i.e. back & forth along rails) (X-direction)
      1. across the direction of the beam (perpendicular to the rails, to correct for any small misalignments of the rails) (Y-direction)
   1. the remaining 7 degrees of freedom relate to the internal degrees of freedom of the JJ X-Ray device itself
      - X, Galil
      - Y, Galil
      - Fine Z, Galil
      - Phi, Galil
      - Psi, Galil
      - Chi, Galil
      - Coarse Z, Galil
1. All 7 axes on the JJ X-Ray device are controlled by Galils
1. Of the two "wholesale motion" axes:
   1. motion along the direction of the beam is controlled by a Beckhoff controller (read only)
**Note:** Because the Beckhoff will be treated by IBEX as a read-only device, this means that there is a separate, independent (i.e. independent of IBEX) system which is used to move the sample stack along the rails.
   1. motion across the direction of the beam is controlled by a Galil controller.
1. An OPI for the JJ X-Ray sample stack was originally created for LARMOR.

**Comment by KathrynBaker** [comment]
Moving to an appropriate sprint for shutter open date

**Comment by kjwoodsISIS** [comment]
For more details see the [Zoom Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/ZOOM-Instrument-Details) page.

**Comment by KathrynBaker** [comment]
The extra two axis will be in place - as such a GUI with a linked container to the existing 7-axis sample stack (as used on LARMOR), then the additional control of the extra Y axis, and a readback of the X (Beckhoff) acis is needed. This is due to be commissioned in early 2017 and should be available for shutter open

**Comment by kjwoodsISIS** [comment]
Attached is a sketch of how the ZOOM Sample Stack OPI might appear.
![zoom_sample_stack_opi](https://cloud.githubusercontent.com/assets/7249337/21233328/a8ea455e-c2e6-11e6-9a6b-44399e1c9c99.png)

**Comment by kjwoodsISIS** [comment]
At the present time, there is no information about the setup of the Beckhoff motor controller used to control the motor that drives the sample stack along the rails.  Rather than delay the completion of this ticket, we will temporarily assume that the rail motor can be driven by a Galil.
When the setup details of the Beckhoff controller become available we will update the OPI (see ticket #2038).
