### ISSUE TITLE
GUI: Configure Block does not warn if name is invalid

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1239]
The dialog for configuring a block does not warn if the name is invalid, though the okay button is disabled correctly.

For example: `NEW_BLOCK_1!!!!!`

**Comment by John-Holt-Tessella** [comment]
I think that this error message is returned by the Block Server and that it has been fixed on the latest block server. Is this in Configuration-> Edit Current : Blocks, Add Block the Name dialogue?
