### ISSUE TITLE
Edit config / edit current config

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1245]
Configuration -> configuration -> edit does not show the current configuration, on first view it looks like it has gone missing but it is available via "edit current configuration". Would it be possible to list the current configuration in the Configuration -> configuration -> edit as "greyed out" so as to avoid confusion?

**Comment by KathrynBaker** [comment]
It might not be "greyed out" but, including it and highlighting that it is the current config is probably a reasonable solution for the sake of our control logic and usability, as rather than being unselectable, it just asks if you're happy to edit the current one.
