### ISSUE TITLE
LARMOR: Setup Danfysik 9100

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1248]
As an instrument scientist I want the Danfysik 9100 available via IBEX.

**Acceptance Criteria**
1. The Danfysik is available to communicate with via IBEX

**Notes**
1. This is a set up task, the code for the Danfysik 8000 series should be suitable for the 9100
2. If the db/proto files for the 9100 are not suitable, then the ticket for updating to use the 8800 models (#1208) could be brought forward, or at least the structural changes from that ticket would need to be done, and db and protocol files created for the 9100 series instead.
3. At time of writing, the PSU should be turned on, but as there is no water, so the interlocks will be tripped and it is not possible to ramp the magnet
4. It is connected to the moxa at 130.246.38.8, and is in slot 6, which equates to COM port 42
5. This is a good chance to see the setting up of an item on a beamline, and diagnosing any problems that it may have.

**Comment by KathrynBaker** [comment]
Given that there are no code changes for this (only ones are from those already under review, or things that should be macro'd, baud rate and stop bits, which will be caught by #1208 - I'll make sure of that), The best suggestion I have to test this is to simply do a caget of something like IN:LARMOR:DFKPS_01:POL, or CURR or VOLT or check the ILK (at the moment, until the water is turned on that should return Interlock)

**Comment by IsabellaRey** [comment]
At the time of reviewing, the IOC is not up and running on LARMOR, but I can see it in its list of available IOCs. Kathryn points out that Delft are probably testing now, so it's best not to disturb without confirming with them. Kathryn though confirmed that the IOCs are setup and working, and Rob was watching while she was playing with PSU values.

I think this ticket can be considered done.
