### ISSUE TITLE
Some Images are not Loading on Dev Manual

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1249]
For example see: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/BlockServer-Structure

It is unknown how many images are affected, the whole of the manual should be checked and fixed

**Comment by AdrianPotter** [comment]
I've fixed the images on that page and cast an eye over the remaining 108 pages in the wiki. I didn't find any other broken image links.

**Comment by DominicOram** [comment]
Great, thank you
