### ISSUE TITLE
genie_python: change how init_inst works

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1251]
Move the init files for the instrument (e.g. init_demo.py) to the settings folder, so they can be put into SVN and don't get updated when a new version of genie is installed.

To test:

- I have already update DEMO, so no need to checkout the code.
- Start a new genie_python session
- It should print "THIS IS DEMO!"
- Typing "hello()" should print hello - the hello function is defined in init_demo.py which is in `C:\Instrument\Settings\config\NDXDEMO\Python`
- Change the hello function to print something else and start a new genie_python session and check it works as expected
- Typing "msf.do_scan()" should print a message and the title.

msf is a module that references genie from within genie, i.e. it creates a circular dependency. However, it should work without any problems...

**Comment by DominicOram** [comment]
Looks good to me
