### ISSUE TITLE
Time Channels tab not disabled at startup

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1252]
As a user, the controls in the three "Experiment Setup" tabs in the DAE view should be disabled when the instrument is running. This is true if you start the experiment while the gui is open but if you open the gui when the experiment is already running then some of the controls in the "Time  Channels" tab are still active. The other two tabs look fine.

Acceptance criteria:

1. Load the gui
2. Start an experiment on the current instrument
3. Restart the gui
4. Go to the DAE view/Experiment setup/Time Channels
5. The controls (time regime tables) should be disabled

**Comment by IsabellaRey** [comment]
On my machine it looks like the Time Regime tables are actually disabled, but they are not greyed out. Still, they should be greyed out

**Comment by IsabellaRey** [comment]
The enabled flag was being set recursively in the setChildrenEnabled method of ExperimentSetup. This is fine to disable the time channels tables and all their children when the DAE view has been opened at least once.

However, when the DAE view is opened for the first time, the tables don't exist yet, as they get created later in the updateTimeRegimes method of TimeChannelsPanel. So the top level panel was disabled (so you couldn't edit the tables) but the tables and their children weren't disabled, so they weren't greyed out.

See pull request ISISComputingGroup/ibex_gui#242

**Comment by AdrianPotter** [comment]
Was wondering if we could add a system test but RCPTT doesn't seem to like restarting the client mid-test so I don't think we can do it easily.
