### ISSUE TITLE
Rethink bumpstrip availability

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1253]
Currently the spangle banner is populated with a bumpstrip indicator based on the BUMPSTRIP_AVAILABLE PV in the blockserver. This was added as a temporary solution and is not very extensible. A more flexible solution should be found.

**Comment by DominicOram** [comment]
This has been mostly done through pair/group programming but is now almost finished. It makes sense for someone to take individual ownership now...

**Comment by ThomasLohnert** [comment]
Related PRs:
https://github.com/ISISComputingGroup/ibex_gui/pull/300
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/65

**Comment by John-Holt-Tessella** [comment]
Add current bumpstrip for Larmor to block server initi. I fpossible make this conditional on the PV PREFIX.
