### ISSUE TITLE
Config should not be edited until block dialog accepted

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1254]
In the EditBlockDialog there are a number of bugs due to the block/config being edited before the OK button is pressed. Some noticed bugs:

* Go to the Add Block dialog and close the pop-up, the block is still added

* Go to the Edit Block and immediately cancel
* Subsequently add a new block, the previously edited block disappears

This may be sort of desired behaviour in that we might not want all changes to a block to be lost when closing the dialog (could potentially have a pop-up informing of lost changes?)

**Comment by AdrianPotter** [comment]
Reviewed. A few comments on the code structure in the PR
