### ISSUE TITLE
GUI: Sensible Behaviour if genie_python is not installed

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1259]
When first installing the GUI on Simon's machine we found that although it booted many buttons etc. did not work as genie_python was not installed. The GUI should work as much as possible without genie_python and give an error message to the user in the parts where genie_python is required

**Comment by kjwoodsISIS** [comment]
Alternatively, could we simply run a check on whether genie_python is installed whenever the IBEX GUI is started and display an appropriate message.  For example:
"The IBEX client has detected that genie_python is not installed.  Some features of the IBEX client require genie_python to be installed.  Please install genie_python and re-start the IBEX client."

**Comment by kjwoodsISIS** [comment]
Don't need this any longer - genie_python is now bundled with the GUI.
