### ISSUE TITLE
genie_python should report a version number

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1263]
As a developer and support person, I want genie-python to report its version number, so that i can easily check the version number, or a ask a user to tell me which version he is using.
#### Acceptance Criterion
1. I can use a "version" command, which reports the genie_python version number to the console.
2. (optional) genie_python reports its version number in a banner (written to the console) when it first starts
### Notes
1. None

**Comment by kjwoodsISIS** [comment]
Display the genie_python version number in the About Box too.

**Comment by IsabellaRey** [comment]
NOTE: genie_python has a file called version, but not used anywhwere

**Comment by AdrianPotter** [comment]
Also make sure to update the creating a release section of the dev manual

**Comment by Tom-Willemsen** [comment]
We won't display the genie_python number in the about box as this would either involve:
a) Coupling the GUI and genie_python, which is undesirable for a client-server relationship.
b) Invoking a full scripting session when displaying the about dialog, which is slow.
