### ISSUE TITLE
Jenkins script to create a release from a tag

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1264]
As a developer, I want Jenkins to be able to create a release of the IBEX client, IBEX server or genie_python, from a given tag, so that I have an automated means of creating easily identifiable releases.
#### Acceptance Criteria
1. I can run a script for Jenkins that create a release of IBEX client, IBEX server or genie_python labelled with a version number (the tag).
#### Notes
1. Do we mean one script that produces all 3 artefacts (i.e. IBEX client, IBEX server or genie_python)?  Or one script that is capable of producing any one of the 3 artefacts.
   1. The former seems somewhat inflexible - for example, it commits you to releasing new versions of IBEX server or genie_python if all you ned to do is make a small chnage to the IBEX client.
   2. The latter seems more flexible (or maybe it is 3 separate scripts) - you can create a release of, say, the IBEX client independently of the IBEX server or genie_python.

**Comment by John-Holt-Tessella** [comment]
It might be easier and better for Jenkins to create a build when a repository is tagged (I don't know if this is possible but see https://groups.google.com/forum/#!topic/jenkinsci-dev/0RHUNDhyhog for a possible solution)

**Comment by KathrynBaker** [comment]
At present we do not build from tags directly. but things are working in a suitable fashion. Changes such as this should be considered when we next look at updating our CI.
