### ISSUE TITLE
Web-page pointing to released IBEX clients

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1265]
As an instrument scientist or visiting scientist, I want a web-page (that I can find) that points me at the location of released versions of the IBEX client, so that I can quickly navigate to the appropriate location and download the right client.
#### Acceptance Criteria
1. There is a web-page, easily available, that tell me where released version of the IBEX client are stored.
2. The web-page tells me how to install the IBEX client.
#### Notes
1. To make the web-page easily available, could it be linked from the ISIS-Internal page?  Or is there an alternative page it could be linked from?

**Comment by kjwoodsISIS** [comment]
See also #922

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/InstallingIBEX
