### ISSUE TITLE
Adding GUI tests

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1268]
Adding various system tests to do the following:

- [x] Add a block and a group

- [x] Add multiple blocks to one group

- [x] Add multiple blocks to multiple group

- [x] Block without group goes into "Other" group

- [x] Create a synoptic and add multiple components

**Comment by AdrianPotter** [comment]
I've added a few comments to the PR:

https://github.com/ISISComputingGroup/ibex_system_tests/pull/10

Please review and then move back to Review when complete

**Comment by simonfernandes** [comment]
Waiting on #1165 to avoid having to use undo routines and for (better) compatibility when adding to the test suite.
