### ISSUE TITLE
System testing prior to Cycle 2016/02 (session 1)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1272]
As a developer, I want to conduct comprehensive system testing of IBEX prior to cycle 2016/02 (28th June to 29th July), so that I can be confident that IBEX will run reliably on the instruments to which it is deployed.

#### Acceptance Criteria
1. Team is satisfied regrading the quality of IBEX.
1.  Recent issues reported by Rob Dalgliesh are resolved (or, if they can't be resolved, we understand why and can propose a workaround).

#### Post-Testing
1. NDXDEMO is updated with a tested, fixed version of IBEX server
1. LARMOR is updated with a tested, fixed version of IBEX server
1. A tested, fixed version of IBEX client is made available to users
1. IMAT is updated with a tested, fixed version of IBEX server

#### Notes
1. Should we update IBEX server on other instruments - notably ALF?

**Comment by kjwoodsISIS** [comment]
> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 08 June 2016 11:23
> To: Akeroyd, Freddie (STFC,RAL,ISIS)
> Cc: Clarke, Matt (STFC,RAL,ISIS); Rogers, Sarah (STFC,RAL,ISIS); King, Stephen (STFC,RAL,ISIS); Doutch, James (STFC,RAL,ISIS); Alba Venero, Diego (STFC,RAL,ISIS)
> Subject: RE: testing
> 
> Hi Freddie,
> Please find attached the latest version of the revised scripts for larmor and an example script.
> I haven’t had a chance to tweak the script generator as I’m still waiting for a licence.
> 
> I would additionally like to be able to pull in the list of valid positions from the autogenerated sample.txt at some point but the function call check_move_pos() with available positions defined by hand will do for now.
> 
> This seems to import ok into a genie python session on Larmor and would hopefully run if there wasn’t a whole bunch of stuff turned off. This is now as similar to the SANS2D, LOQ stuff as I think I can reasonably get for now.
> 
> Rob
> 
>> From: Akeroyd, Freddie (STFC,RAL,ISIS) 
>> Sent: 06 June 2016 16:37
>> To: Dalgliesh, Robert (STFC,RAL,ISIS)
>> Subject: testing
>> 
>> Hi Rob,
>> 
>> We are going to try and do a more thorough test of IBEX prior to cycle. As well as manual GUI testing, we would like to copy your configs, scripts etc. from LARMOR onto NDXDEMO and then try to run something in simulation mode. Have you already got the config/scripts etc. that you will be running at start of cycle, or would you be able to suggest a reasonable sequence of operations that should form part of our system test
>> 
>> Thanks,
>> 
>> Freddie      
>>

**Comment by AdrianPotter** [comment]
Starting by creating a release version and deploying to NDXDEMO for testing purposes. I will add a page to the wiki to document my process so far so anyone else can follow and expand.

**Comment by kjwoodsISIS** [comment]
Attaching LARMOR issues reported in last few months.  We should test to check that each is specifically resolved.
[LARMOR_Issues.zip](https://github.com/ISISComputingGroup/IBEX/files/323133/LARMOR_Issues.zip)

**Comment by AdrianPotter** [comment]
I've gone through and done extensive exploratory testing on IBEX. Most of the issues 1319-1352 have been submitted as a result. I don't believe any of these should block the release of version 2.0 but similarly they should be addressed at some point.

I ran the attached test scripts and they seemed fine.

Kathryn looked at Rob's specific issues and made the following comments:

```
Issue 63171 (about the touch screen and search requirements) is not something we have any dealings with – it’s part of the Safety requirements, so really not our area of expertise
Issue 63172 (motors spontaneously disappearing) – I haven’t explicitly included this, as it could be covered by the OPI tests, if it isn’t the OPI and the Java, then we can always add a test of start a motor IOC, look at that tab, stop the IOC, restart the IOC and see if it comes back, but this reads as the IOCs were running throughout, so not sure how to recreate it.
Issue 63081 (IE doesn’t get focus from the web links) – This is an IE/Windows problem, and requires a change to working practice, such as changing the default browser. I’m not sure this has been discussed at all.

I’ve listed tests for 63119, 63965, 63935, 63936, 63072, 63080, 63928, 63071 and 63927, and these can be shared as either a blank spreadsheet or as filled in after the fact.
My spreadsheet also has tests for most of the tickets listed in the release and that we have reviewed so far this sprint. It is not an exhaustive list, and the tests are not as detailed as I would like, but it is a starting point, and it will keep me busy this afternoon getting them done.
```

I will attach the referred spreadsheet to the ticket

**Comment by AdrianPotter** [comment]
[tests pre-release-kvlb.xlsx](https://github.com/ISISComputingGroup/IBEX/files/341752/tests.pre-release-kvlb.xlsx)
