### ISSUE TITLE
Add Calculation Method and Time Channel File to DAE tab

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1274]
Next to "Time Unit" in the DAE time channels panel should be

Calculation Method
Time Channel File

The relevant back end support for these seems to be already in the client, it is just not possible to set them from the GUI

The reason why NDXDEMO cannot see spectra is because it is set to a calculation method of "file" and there is no way to change this from the GUI! Not sure how it got this way, the filename it is trying to use is mantid_py.bat which was also displayed as a period file.

**Comment by kjwoodsISIS** [comment]
Consider adding to the Properties dialog (visible to support team, not users)

**Comment by ThomasLohnert** [comment]
Related pull requests:
https://github.com/ISISComputingGroup/EPICS-ioc/pull/47
https://github.com/ISISComputingGroup/EPICS-isisdae/pull/6
https://github.com/ISISComputingGroup/ibex_gui/pull/261

**Comment by John-Holt-Tessella** [comment]
Review: Checking on some implementation details with @FreddieAkeroyd

**Comment by John-Holt-Tessella** [comment]
Change requests after talking with Freddie and Thomas:

1. Make Calc method a radio buttons selection
1. Make labels `Use TCB File` and `Specify Paramters`
1. On radio button change hide appropriate controls
    1. Display for Use TCB Control: time unit and file path
    1. Display for specify parameters: time unit and time regime group box
1. Change in time regimes group box first drop down from TCB File to blank
1. Diasallow typing in all drop downs where files can be selected (tcb file, 3 table files and period file)
1. Make send changes button read apply changes
1. Create a discard change button which will reset the value back to those on the server
1. Enable/disable buttons when there are no changes (this might be hard don't do if it is hard)

**Comment by ThomasLohnert** [comment]
Have now pushed changes that implement all these points apart from:

7.Create a discard change button which will reset the value back to those on the server
8.Enable/disable buttons when there are no changes (this might be hard don't do if it is hard)

Would argue that this is out of scope and should be a separate ticket as the apply/discard changes buttons are associated to all changes in experiment setup including data acquisition and period settings, not just time channels.

**Comment by AdrianPotter** [comment]
Slight rework of drop downs requested. Currently not clear when drop downs are empty where the GUI is expecting to get files from. Would be good to point users at the correct location in this case and have a tooltip explicitly stating where files are expected.

Note that the changes for this ticket will break the current system tests as the context for setting up the table files puts the files in the wrong place from the GUI's point of view. These will need fixing before the ticket can be marked complete.

**Comment by DominicOram** [comment]
As @AdrianPotter mentioned previously this has broken the system tests. Specifically the SetupDAETables context. Can you fix the system tests please?
