### ISSUE TITLE
System testing prior to Cycle 2016/02 (session 2)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1275]
Continuation of system testing, after urgent tickets have been implemented.  See #1272.

**Comment by kjwoodsISIS** [comment]
See also two LARMOR scripts, attached to #1272.

**Comment by AdrianPotter** [comment]
@kjwoodsISIS: What else needs to be done for this ticket? Mine and @KathrynBaker's testing for ticket #1272 concluded once urgent tickets had been merged in. Some of the issues Rob reported have not yet been resolved. These mostly involve response times from UI actions. Should these be covered under separate issues?

**Comment by AdrianPotter** [comment]
No more testing required. Effort under Ticket #1272 covers this too
