### ISSUE TITLE
System test: deleting all blocks deletes all groups

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1276]
Add a system test to check that, after adding multiple blocks to multiple groups, removing all of the blocks results in all groups being removed.

Waiting on #1269

**Comment by AdrianPotter** [comment]
A few changes needed. See https://github.com/ISISComputingGroup/ibex_system_tests/pull/11

**Comment by simonfernandes** [comment]
Waiting on #1165 to avoid having to use an undo routine and for (better) compatibility when adding to the test suite.
