### ISSUE TITLE
lvDCOM translates macros on each call

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1277]
You can use macros in the XML configuration of lvdcom, but it appears these get translated on each call so you are unable to change a macro definition inbetween two separate loads of the XML file to allow reuse of the file

Looks like best approach is to create our own macro cache based on the environment at load time, this would then allow additional "special" macros to be created by the program if need be.

**Comment by John-Holt-Tessella** [comment]
Code looks good. Tested no macro, long macro line and short macro line and changing env after starting.
