### ISSUE TITLE
Blockserver: PV name bug

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1279]
In block_server.py, the PVDB contains an int PV called "CURR_CONFIG_CHANGED", which I think results in the full PV name being %MYPVPREFIX%:CS:BLOCKSERVER:CURR_CONFIG_CHANGED.

However, in core/config_list_manager.py there is another PV called ":CURR_CONFIG_CHANGED", which I think results in %MYPVPREFIX%:CS:BLOCKSERVER::CURR_CONFIG_CHANGED (i.e. same as before, but with an extra : after BLOCKSERVER!)

A caget shows that both PVs exist, the first one is an int, the second one is a waveform.

It probably is just a bug,  but worth checking.

**Comment by DominicOram** [comment]
Both should probably be removed as per https://github.com/ISISComputingGroup/IBEX/issues/1280

**Comment by IsabellaRey** [comment]
Yes, this is just because as part of #1053 I'm doing a refactoring that involves touching this.  So this is a tiny ticket to fix the bug, for traceability, then I can merge the change into my branch and do the refactor.

**Comment by IsabellaRey** [comment]
Pull request ISISComputingGroup/EPICS-inst_servers#48
