### ISSUE TITLE
Blockserver: unused CURR_CONFIG_CHANGED PV flag?

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1280]
As a developer, I don't want to maintain unused code.
The blockserver PVDB has an int PV called CURR_CONFIG_CHANGED, which as the name says, flags if the current configuration has changed.

The GUI doesn't seem to be using this PV, and when multiple users are looking at the same instrument, any change to the current config from a user is picked up by the other GUIs correctly.

Do we need this PV in the blockserver? Discuss with the team, and remove if not needed. If there are still plans to use it, create a ticket for that (or check if there is one already) and reference it in this ticket.

**Comment by KathrynBaker** [comment]
I’m afraid I’m answering a question with a question – how would a non-GUI client know if the config was being changed?

Regards,
Kathryn

**Comment by DominicOram** [comment]
I added this PV on a bit of a whim, when I first added it I think it was mildly useful at the time I added it but it's not any longer. In fact it doesn't actually even work as how can a client acknowledge to the blockserver that it is aware of a config change. We should remove it.

As to Kathryn's question there is a SERVER_STATUS PV that lets clients know when the blockserver is actively changing the configuration if that's what you mean?

**Comment by KathrynBaker** [comment]
In which case the CURR_CONFIG_CHANGE probably isn’t doing much of use, I just wanted to make sure that if you left a console open for some time, that you could be easily aware that the current config had been changed from what was initially loaded, as there it could be helpful.

Regards,
Kathryn

.

**Comment by DominicOram** [comment]
No, you can't easily know if a config has changed in that situation but the PV wont help in that anyway as how will the Blockserver know what you think the configuration should be? If you want a command you can easily call that will need to be done client-side, i think

**Comment by AdrianPotter** [comment]
Change has been merged, thanks. Please could you create an EPICS PR to bring the submodule up to date?

**Comment by DominicOram** [comment]
Updated submodule in https://github.com/ISISComputingGroup/EPICS/commit/71d8dac2e788c8b37b63d91e7c855bbc14e08cfb
