### ISSUE TITLE
MACROs set in the GUI do not work

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1281]
As a User if I set a Macro in the GUI on a configuration I expect it to be used within the IOC.

## Acceptance test

1. Set a macro in the configuration
1. Make sure it effects the IOC it is set on
1. Change configurations makes sure the macro is changed back
1. Update the macro make sure it changes the current gui. 
1. Look at what the behavious is when setting the macro in the GUi and in globals.txt fin sout desired behaviour and make sure it works

## Dev Notes

I can not appear to set a macro in the GUI and have it work in the IOC. Looking at the log of a starting IOC I see
```icpconfigLoad: $(ICPCONFIGDIR)="C:/Instrument/Settings/config/NDW1407/configurat
ions/rcptt_text"
icpconfigLoad: last configuration was "/rcptt_text"
icpconfigLoad: configuration "/rcptt_text"
icpconfigLoad: no components for "/rcptt_text"
icpconfigLoad: Error in "C:/Instrument/Settings/config/NDW1407/configurations/rc
ptt_text/iocs.xml" File was not found at offset 0```

This is the incorrect path on mine for configurations it should be `C:\Instrument\Settings\config\NDW1407\configurations\configurations\rcptt_text` (note double configuration)
 Look at code is C:\Instrument\Apps\EPICS\support\icpconfig\master\icpconfigApp\src\icpconfig.cpp line 364ish and  try line 349 in that same cpp, as that would set the config root to a level lower, although lines 382 to 387 are also related I think, I did try with a start_inst using a different macro for ICPCONFIGROOT, but that caused other problems instead

**Comment by KathrynBaker** [comment]
https://github.com/ISISComputingGroup/EPICS-icpconfig/pull/1

Probably best left for Freddie to have a look at

**Comment by FreddieAkeroyd** [comment]
It seems that the icpconfig code assumes that the blockserver is adding /configurations and /components to the relevant bits to distinguish components and configurations,  I'm guessing it used to do this? Will need to do more code changes as probably easier to do that then try and rewrite existing configs...

**Comment by FreddieAkeroyd** [comment]
Fix now committed to master

**Comment by KathrynBaker** [comment]
My test setup still gets the macro that I set in the config, so moving this ticket to review_complete

**Comment by IsabellaRey** [comment]
Just an observation, as I was checking this too: I have tried having the same macro set both through the GUI and the globals.txt. It looks like the globals.txt wins.

Can we just confirm this is the desired behaviour?
