### ISSUE TITLE
IMAT: OPI for the attenuator

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1284]
As an instrument scientist I would like to be able to control my attenuator from an OPI and not just the scripting prompt

*Acceptance Criteria*
1. There is an OPI for the attenuator

*Notes*
1. There are sim records for use in dev without the PLC needing to be in place
2. The PVs in question are of the format $(P)$(Q) - Q is set as ATTEN, and there is only an OPEN, CLOSED, OPEN:SP and CLOSE:SP to consider
3. Something like the in out section of the monitor OPI should be suitable

**Comment by IsabellaRey** [comment]
Pull request ISISComputingGroup/ibex_gui#254
