### ISSUE TITLE
Mercury OPI and Sim Records

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1285]
As a scientist using the Mercury IOC in IBEX I want a very simple OPI. As a developer of the OPI I need simulation records.

## Notes

Initially the OPI needs just TEMP, TEMP SP and name

**Comment by IsabellaRey** [comment]
See ISISComputingGroup/EPICS-MercuryiTC#2 and ISISComputingGroup/EPICS-ioc#46 for the changes in the IOC first.

Then see ISISComputingGroup/ibex_gui#260 for the OPI and GUI. It might be worth testing the GUI not just with simulation mode, but also with the actual LabView .vi the IOC talks to.

**Comment by AdrianPotter** [comment]
Not clear whether name/title should be settable from the OPI. Please can we discuss when you get back

**Comment by AdrianPotter** [comment]
Suggest talking to Gareth about whether title is needed.

**Comment by IsabellaRey** [comment]
Checked with Gareth - for the time being have the Name field as read-only; the instrument scientist can change it on the hardware if needed; this is probably safer.

**Comment by IsabellaRey** [comment]
Name field made read-only in the OPI. See pull request ISISComputingGroup/ibex-gui#286
