### ISSUE TITLE
Mercury Pressure Card IOC

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1286]
As a scientist I would like to monitor the Pressure through the mercury IOC and have it appear on the mercury OPI

Acceptance criteria:
- Equivalent information can be displayed in IBEX as was available in SECI. 
- THis is an extension f the existing mercury ioc - it needs to be configurable

**Comment by Tom-Willemsen** [comment]
Still lvdcom.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1005
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/448
- https://github.com/ISISComputingGroup/EPICS-MercuryiTC/pull/5

Note: the existing labview VI for the pressure card has two front panel items both called `Voltage` - one is for the voltage of the pressure sensor, the other is a heater voltage. As far as I know, lvdcom cannot diambiguate items with the same names, so I renamed the heater voltage to `HeaterVoltage` instead (there is a new version of the VI with this change temporarily at `<share>\ISIS_Experimental_Controls\data for tickets\Ticket1286_new_mercury_pressure_vi`). @FreddieAkeroyd just to confirm, is this correct or is there a way to tell lvdcom which `Voltage` I want to read in each instance?
