### ISSUE TITLE
Simulation does not work for FINS IOC

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1288]
As a developer I want the simulation mode to work for FINS machine.
I tried simulation with with imat-attn and larmor-air fins and both don't allow the simulation to be set. 
It appears that the bi for status for instance never completes its first get and so can not have simulation set on it. The PACT record is always 1.

**Comment by John-Holt-Tessella** [comment]
Also make attenuation simulation reset values to 0

**Comment by IsabellaRey** [comment]
The same issue seems to be happening with the MERCURY IOC

**Comment by samueljackson92** [comment]
Found a work around for this problem. In the configuration file I changed the `finsUDPInit` call to be:
```
finsUDPInit("PLC", "$(PLCIP=127.0.0.1)", "TCP")
```
Pointing the IP address to localhost allows the FINS controller to get a response and then give up on making a connection which then allows the rec sim to kick in.
