### ISSUE TITLE
Jenkins: Can the build scripts be made more efficient by zipping?

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1296]
The build scripts currently do a lot of direct copies of large folders to the //isis drive. Inspection suggest this takes a large fraction of the build time. Please could someone investigate whether zipping the Jenkins artifacts on the build machine prior to copying improves the performance?

Note that if implemented, some install scripts may subsequently need updating.

**Comment by ChrisM-S** [comment]
I've commented in #1297 (which I read first!) with some example code which would allow building of VHD files for distributions.  Obviously, this is a full bandwidth way of achieving this goal too (also no compression CPU so very efficient writing).

**Comment by FreddieAkeroyd** [comment]
Chris moved the build server to the R3 network on 29th June, and the final copy time dropped significantly (something like 45 minutes -> 5 minutes). So I don't think there is any need to look at zipping now?

**Comment by kjwoodsISIS** [comment]
No issues reported since July 2016, so this issue is assumed to require no further action.
