### ISSUE TITLE
Blockserver crash with import error

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1301]
Blockserver is continually restarting on NDXDEMO due to a missing xml module, it uses genie-python so i'm guessing this is a genie python build/package issue 

[Sat Jun 25 14:58:00 2016]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\block_server.py", line 33, in <module>

[Sat Jun 25 14:58:00 2016]     from BlockServer.epics.gateway import Gateway

[Sat Jun 25 14:58:00 2016]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\epics\gateway.py", line 19, in <module>

[Sat Jun 25 14:58:00 2016]     from server_common.utilities import print_and_log

[Sat Jun 25 14:58:00 2016]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\server_common\utilities.py", line 20, in <module>

[Sat Jun 25 14:58:00 2016]     from xml.etree import ElementTree

[Sat Jun 25 14:58:00 2016] ImportError: No module named xml.etree

**Comment by John-Holt-Tessella** [comment]
Reinstalled Genie Python this now works.

**Comment by FreddieAkeroyd** [comment]
Should now be resolved in future by #1312
