### ISSUE TITLE
Blockserver Error on change config

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1305]
Invetigate a fix error:

```
Could not retrieve IOC list: 'NoneType' object has no attribute 'decode'
```
1. Run a configuration
2. Change configurations (I went to IMAT_mockup_01)
3. IOC Log shows error

**Comment by John-Holt-Tessella** [comment]
This is does not stop it find the IOC later.

**Comment by AdrianPotter** [comment]
I've searched through my logs, Larmor's logs and Iris's logs. I identified the issue on Larmor. The last occurrence happened on 22nd August 2016. The logs in the other two locations don't go far enough back to detect the issue. I think we can safely say this is fixed.
