### ISSUE TITLE
Clicking cancel on edit block deletes that block

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1308]
Steps to reproduce

1. Create a block
1. Right click on it
1. Select "Edit block"
1. Click cancel
1. Save

Block is removed from display.
This might be fixed by #1252. Test first

**Comment by ThomasLohnert** [comment]
Can confirm that https://github.com/ISISComputingGroup/ibex_gui/pull/249 fixes this
