### ISSUE TITLE
Support information for devices

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1310]
As a user of IBEX, there are times when the device being attached doesn't quite behave in an expected way, so I could do with troubleshooting information for various devices.

**Acceptance Criteria**
1. There is location that has a list of devices with troubleshooting available

**Notes**
1. This was highlighted by attempting to talk to one of the Danfysik models, which had multiple baud rates - there is a rate for communicating with it from outside, and one for daisy chaining multiple PSUs
2. It might be an idea to know where to look for programming and hardware manuals (not everyone in the team uses/has access to LabVIEW Modules), and to record simple troubleshooting and recovery procedures
3. This is probably something to consider adding to our developers wiki, or making it obvious where to find it if it is already there

**Comment by KathrynBaker** [comment]
It was suggested during a sprint planning that the trouble shooting steps be added to the developers wiki, and the manuals be put in sharepoint and linked from the wiki

**Comment by DominicOram** [comment]
We're slowly building up information on subpages of https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC and manuals are now on a share. I'm going to call this done.
