### ISSUE TITLE
Mk3Chopper: automatically adjust to the number of choppers found on startup

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1314]
A single Mk3 Chopper crate (= 1 IOC) can have multiple choppers connected to it.

The number of choppers connected can be queried, so it will be possible to use this value to set up the PVs for all the chopper automatically in the st.cmd using macros.

Also, the "$(P)SIM", "$(P)DISABLE" and "$(P)NUM_ENABLED" should be in a common db file as they do not need to created for each chopper.

**Comment by FreddieAkeroyd** [comment]
If this looks to be difficult, we could just macro it out via configurations / globals.txt for the moment
