### ISSUE TITLE
Automatically start IBEX on appropriate instruments

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1315]
As a developer I don't want to have to remember to run start_inst every time as computer is restarted, make sure that instruments using IBEX start automatically

**Acceptance Criteria**
1. The instruments currently using IBEX, or a subset thereof, all start the IBEX server on computer startup. These are:
- LARMOR
- IMAT
- ALF (might not need this at the moment)
- ZOOM
- MUONFE (server 2012, may need a different method)
- SANS2D (for the CAEN, so should be using a cut down version)

**Notes**
1. Whilst HIFI_CRYOMAG does use parts of IBEX, at the moment these are started by the VI, so it does not need an auto-restart
2. This is at it's simplest a "put a shortcut to the .bat in the startup folder" on each of the instruments listed above, but should also be added to the instructions for converting an instrument, alongside pinning a copy of the GUI to appropriate taskbars
3. The MUONFE requirement could be separated out to a different ticket as it will require a (currently) unique solution

**Comment by KathrynBaker** [comment]
+1 for LARMOR - just had to start the server on LARMOR as it wasn't running after an update or restart would be my guess

**Comment by ChrisM-S** [comment]
+2/3 for HRPD, POLARIS, IMAT?.  My test for a working instrument (after upgrade) with DAE is to boot the NDH, wait, remote desktop into the NDX and see if the run number is showing in the dashboard (and then begin and end a run – with a change title if working) so technically these passed because they started SECI!
So sorry @KathrynBaker LARMOR was my fault!

**Comment by KathrynBaker** [comment]
No problem re LARMOR, it just confused an Instrument Scientist – he has now made a note of how to start the server for the future.

**Comment by John-Holt-Tessella** [comment]
There is a script written by @FreddieAkeroyd ibex_system_boot.bat in the top level. This should be added to startup menu. Step needs to be placed in instrument deploy script.
