### ISSUE TITLE
IBEX: RB lookup date range

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1319]
Ticket raised as part of release 2.0 system testing. Marked as question so that usefulness to actual user can be evaluated.

As a user, when I open up the RB number search dialog in the Experiment Details perspective, I would like to be able to search a range of dates, rather than a specific date.

For acceptance:
1. Determine if this genuinely would benefit users. If false, close ticket. If true, proceed to 2.
2. The RB number can be searched over a range of dates.

Don't forget to add a system test!

**Comment by KathrynBaker** [comment]
This is probably not necessary. The contents of the RB number lookup are typically only a couple of cycles long. I don’t think most experiment teams come with more than one or two RBNUMBERS, and tend to know when they are here, so looking for multiple RBs for a team would likely be done by name, but looking by date shouldn’t need a range.

Regards,
Kathryn

**Comment by DominicOram** [comment]
Closing as wontfix.
