### ISSUE TITLE
IBEX: RB lookup, click column headers to sort

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1320]
As a user, I want to be able to sort the entries in the RB lookup table in the Experiment Details view. At the moment the table numbers are clickable, but nothing happens when I do. This is unexpected.

There are many tables in IBEX where the same would apply. This one in particular seems like it would benefit from being sortable.

Acceptance criteria:
1. Is this a useful change? If not, close the ticket. Else proceed to 2.
2. When I click on any column in the RB Number Lookup dialog, it sorts the list.
3. Clicking on a number for a 2nd time inverts the sort.

**Comment by AdrianPotter** [comment]
Note that sorting is enabled in the IOC Log view so it's definitely doable

**Comment by DominicOram** [comment]
PR at https://github.com/ISISComputingGroup/ibex_gui/pull/677
