### ISSUE TITLE
IBEX: Remove Experiment Team individually

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1322]
As a user, I want to be able to individually remove members from the Experiment Team in the Experiment Details view. Currently I can only clear them all which isn't useful if I just want to remove one.

Acceptance criteria:

1. Add several members to the team in the Experiment Details view
2. Delete one member of the team
3. The remaining members of the team are left in place.

**Comment by AdrianPotter** [comment]
1. Add a 1st, give them a non-default name
2. Add a 2nd user, give them a non-default name
3. Click set
4. Select the 2nd user, then remove - the user is removed
5. Select the 1st user, then remove - the user is not removed.

Notably, following step 5, I also tried the clear button and it didn't work.

Please could you fix the bug and update the system tests

**Comment by DominicOram** [comment]
After discussion with @KathrynBaker there are a number of other bugs within the Experiment Team table that it would make sense to fix all together:
- Pressing the Clear button after a number of users have been added doesn't clear the dashboard
- Pressing the Add button twice results in two DEFAULT_USERs in the dashboard but only one in the table, this should instead be DEFAULT_USER and DEFAULT_USER_1 etc.
- Setting two users to have the same name causes one to disappear even if they have different institutes. Users with exactly the same name, institute and role should be allowed and should appear on the table + dashboard as usual.

**Comment by DominicOram** [comment]
I'm happy to fix this once I'm back from holiday but anyone is free to grab it as it shouldn't be too hard.

**Comment by DominicOram** [comment]
Added change to allow multiple users to be removed at once

**Comment by AdrianPotter** [comment]
Functionality good. Just a couple of things to address before closing:

- `removeUser` in the GUI should now be renamed to `removeUsers`
- Please update the system tests to test multiple users removed
- Please add an entry to the release notes
- It would be good to have some unit tests to cover the BlockServer changes

**Comment by AdrianPotter** [comment]
There are still a few new checkstyle warnings arising from the new code. Please could you review and fix:

http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_build_PRs/384/

**Comment by AdrianPotter** [comment]
Tested and reviewed everything else and it's all fine, so just the checkstyle fixes please

**Comment by DominicOram** [comment]
Fixed checkstyle. See http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_build_PRs/389/ and http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_build_PRs/390/
