### ISSUE TITLE
IBEX: Toggle plots in beam status view

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1324]
As a user, I cannot always see 3 separate lines for the TS1, TS2 and synchotron beam current plot in the Beam Status view. I would like to be able to toggle whether each of the three lines is visible so that I can see more clearly what the historical current is.

Acceptance criteria:
1. Each of the three lines on the beam current plot can be enabled/disabled
2. The choice is preserved when I switch between plot period.

**Comment by KathrynBaker** [comment]
Almost exactly the same as #1715, have added the extra requirement to that ticket and will close this one
