### ISSUE TITLE
GUI: "Select Block" option for Log Plotter

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1326]
Given I'm in the Log Plotter window and I have an active plot, I can right click on the plot and select "Add PV" in the subsequent dialog, I am prompted to add the PV name. I may not know the exact name I want.

As a user, I would like a "Select PV" dialog, similar to the one in the "Add block" dialog that gives be a list of possible PVs I can choose to add to the plot.

**Comment by rerpha** [comment]
Given we have the option to do this from device screens now (anything outside of these probably won't be important?) I'm going to close.
