### ISSUE TITLE
IBEX: Unhelpful error on invalid email address

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1328]
1. Open the Log Plotter view
2. Plot the graph for a block
3. Right click the block and select "Send email"
4. Enter "Hello world" in the "From" box
5. Click "OK"

The error response I get on NDX demo is `501 5.1.7 Invalid address`. This isn't helpful for diagnosing the issue.

**Comment by KathrynBaker** [comment]
Whilst attempting to reproduce it on dev machine was instead getting a connection unavailable, given that this is not reported and has not been considered in a number of years, closing the ticket
