### ISSUE TITLE
genie: Unable to load script from Windows path format

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1334]
If I try and load a script using an absolute path in Windows format e.g. 

load_script("C:\test\file1.py")
or
load_script("C:\\test\\file1.py")

I get an error saying the script file was not found.

This case should be handled by genie

**Comment by AdrianPotter** [comment]
Note that change_script_dir works as expected

**Comment by DominicOram** [comment]
It appears that, for me at least, the script is actually found and run but the error is thrown anyway.

test.py:
```python
print "Hello World"
```

genie_python:
```python
>>> load_script("C:\test.py")
Hello World
ERROR: No script found
```

**Comment by kjwoodsISIS** [comment]
Check what happens when using '\\'

**Comment by John-Holt-Tessella** [comment]
Make the error massage state what file it is looking for

**Comment by FreddieAkeroyd** [comment]
Maybe also scan the string for non ascii characters, if you find "tab" you know they typed \t somewhere when it really needs to be \\t   or  /t   to work

**Comment by AdrianPotter** [comment]
@DominicOram: The command creates two different errors: "No script found" which is presumably looking for some genie_python specific content in the script, and "Script file was not found" which is self-explanatory. Both error messages would benefit from more clarity

**Comment by AdrianPotter** [comment]
Had a quick look while waiting for other stuff. Errors are easily extended. The current path conversion logic is a bit all over the place. Suggest factoring out into a separate class and putting in some unit tests.
