### ISSUE TITLE
genie: get_sample_pars() returns internal error

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1341]
I ran get_sample_pars() on NDXDEMO. It returned the error:

`ERROR: 'NoneType' object has no attribute 'groups'`

This suggests something unexpected is happening internally. It's not the sort of error I'd expect to reach the user

**Comment by AdrianPotter** [comment]
Note that the instrument is running if that has any relevance

**Comment by kjwoodsISIS** [comment]
Close this issue and fix under #1396
