### ISSUE TITLE
genie: send_sms not working: times out and responds with error

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1343]
I've tried send_sms with my number both in UK and international format and each time I get the reply 

`<urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

as in ticket #1342.

**Comment by FreddieAkeroyd** [comment]
It is likely using the old wwwcache proxy - I will fix and also add both slack and email support

**Comment by FreddieAkeroyd** [comment]
See PR for how to test the three commands send_sms, send_email and send_alert.
