### ISSUE TITLE
genie_python unable to load script

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1345]
The following simple script

def test():
    endAngle = 1.0

fails to load with load_script() with error
In [5]: load_script("c:/test1.py")
ERROR: script not loaded as errors found in script:
        Line 2: 'end' command without brackets

**Comment by mattclarke** [comment]
The script checker is confused by the line starting with end, it is assuming it is supposed to be end(), so it is complaining. I have temporarily commented out the script checker on IMAT
