### ISSUE TITLE
IBEX: "Edit/New Configuration" window enhancements

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1347]
Following feedback from one of the scientists during sprint review a while back, I have been looking at the "edit configuration window" and ways to make the process of creating/editing a new configuration more intuitive and user friendly. While looking into this I have also come up with some additional proposed changes to the window, which can be found at the bottom of this page.

Specifically, the scientist was confused as to how to actually create a new configuration, which stemmed from the "Description" and "Name" fields, which are required to save a config, being somewhat 'hidden away' in the summary tab.

To address this issue, I have created the following 3 mockups, ordered from less to more radical in the changes they introduce.

V1
![edit_config_mockup1_small](https://cloud.githubusercontent.com/assets/18398579/16481258/3aa5e418-3ea2-11e6-9656-5f03c1d1df5e.png)
In this variant, I address the issue by simply moving the summary tab to the front so it is the first thing the user sees when opening the window.

V2
![edit_config_mockup2_small](https://cloud.githubusercontent.com/assets/18398579/16481373/df71ce94-3ea2-11e6-8aab-b5d1f4a87240.png)
In this variant, the "Summary" tab is essentially separated out from the tabbed pane, which provides the user with a sort of reference point across all tabs. (E.g. in the current version it is not easy to see which config it is you are actually currently editing.)

V3
![edit_config_mockup3_small](https://cloud.githubusercontent.com/assets/18398579/16482029/fdbc5ca4-3ea5-11e6-8c31-abcd55e9a6bf.png)
This variant is following an idea John had, the part of note here is the tree structure on the left, more similar to the synoptics window. This provides the user with a full map of the configuration and should eliminate a lot of tab switching.

Furthermore, I propose the following additional design changes to the window:
- I understand the tabs are in order of the steps one would typically take to create a configuration (almost like a wizard). As such, would it not make sense to add components first as this will already add some fixed IOCs, Blocks, Groups?
- Currently, to edit IOC macros / PV values / PV sets one has to switch to the relevant tab and selecting the relevant IOC from a drop down menu, which seems slightly awkward. I propose that they instead can be edited directly from the list of blocks, see the screenshot of V2. I am not completely sure if that makes sense with the workflow of editing configs, so feel free to tell me if this idea is rubbish. In V3 this is taken care of by having those settings in each IOCs tree structure.
- Messages of errors which prevent the user from saving changes are currently displayed on top of the window. I propose to move to them next to the save buttons at the bottom to make it easier for the user to establish a connection between the two. (See screenshot of V1)

Open to discussion!

**Comment by KathrynBaker** [comment]
Don’t forget there is as ticket (#1116) to explicitly add IOCs to a config, so that rather than having to wade through ALL the IOCs all the time, you only have to do it once when adding it to that config. It looks like this is implied in V3, but I wanted to make sure, as this is the kind of thing to remember when redesigning this interface. I quite like V3, it is similar, but different to the synoptic setup, so shouldn’t be too difficult to deal with.
I think V3 as a clean lookup might also cover most of #1117 as well. Although, limiting the list of IOCs on the existing lookups once they have been explicitly added could have the same effect.
There are also a couple of ticket (#1118 and #1119) with work on how to deal with conflicts between components and configs.

**Comment by John-Holt-Tessella** [comment]
Use Case 1: User adds selected PVs for a given IOC
Use Case 2: Add PV associated with JAWS. Allow user to search all PVs for JAWS (it is not clear that this is associated with GALIL01/02 so user wants a find) 
Use Case 3: User want to add PV for IOC that has not run on the local instrument so does not appear on the list (i.e. setting up config before first run or setting up IOC)

**Comment by kjwoodsISIS** [comment]
At pre-planning on 07/07/2016 we agreed to implement V2.  V3 can come later.

**Comment by AdrianPotter** [comment]
@kjwoodsISIS: Is there a follow up ticket to implement this?

**Comment by AdrianPotter** [comment]
Added ticket #1397 to cover implementation

**Comment by ThomasLohnert** [comment]
Re-opened: This was closed as https://github.com/ISISComputingGroup/IBEX/issues/1397 was meant to cover V2 implementation instead, however there is already an (unmerged) pull request (https://github.com/ISISComputingGroup/ibex_gui/pull/279) and 1397 has since been edited to instead cover the outstanding implementation of V3. Added rework label as minor changes are proposed in the PR comments.
