### ISSUE TITLE
IBEX: Delete multiple synoptics at a time

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1350]
As a user, I would like to be able to delete multiple synoptics at a time. Currently, I have to go Synoptic > Delete > [Select] > Ok for every synoptic I want to delete. I would like standard shortcuts (CTRL+LMOUSE, SHIFT+LMOUSE) to work to allow me to select multiple synoptics at a time.

**Comment by simonfernandes** [comment]
Also implementing being able to select multiple configurations for deletion.

**Comment by John-Holt-Tessella** [comment]
Ensure that editing synoptics doesn't allow multi-select.

**Comment by simonfernandes** [comment]
GUI changes (please review first):  https://github.com/ISISComputingGroup/ibex_gui/pull/283
System tests: https://github.com/ISISComputingGroup/ibex_system_tests/pull/20
