### ISSUE TITLE
IBEX: Why is there a currently selected text box on the edit synoptic dialog?

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1351]
If you go to edit a synoptic in IBEX, the edit synoptic view gives you a list of synoptics. You select one, it's highlighted, and you click ok.

Towards the bottom of the dialog, there's a read-only text box that shows the currently selected item on the list. The text is identical to that shown in the list. Given the highlighting in the list shows which item is selected, this box seems entirely redundant. If it serves no purpose, please could we remove it?

**Comment by DominicOram** [comment]
This is also true in loading and editing configs, should it be changed here also?

**Comment by AdrianPotter** [comment]
Thanks for the changes. The OK button no longer works in the Configuration or Component dialogs.

Please could you fix and add system tests.
