### ISSUE TITLE
IBEX: edit config window, "enabled" checkbox in PV sets persists

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1353]
The checkbox in the "Enabled" column in the PV sets tab in the edit config window persists when switching from an IOC that has entries in the table to one that does not.

Steps to recreate:
1. Open PV Sets tab in Edit Configuration window
2. Select any of the Galil IOCs from the dropdown menu
3. Select any IOC for which the table is empty (i.e. most of them, for example the Genesys ones) from the dropdown menu

**Comment by kjwoodsISIS** [comment]
What is the story point estimate for this story?  Will the person who picks up this story please assess the number of story points and add the appropriate label.

**Comment by IsabellaRey** [comment]
While running manual system tests for release 2.1.0, the following was also noticed:
IOC PV Sets does not display the saved result on load

Steps to reproduce:
1. Open configuration
1. select GALIL_01 in PV Sets
1. Tick check box to YES
1. Save
1. Re-open configuration and select GALIL_01 in PV Sets: the entire row is missing

**Comment by ThomasLohnert** [comment]
Re-setting the label provider gets rid of the checkbox (see clear() method in BlocksTable)

**Comment by ThomasLohnert** [comment]
In the new Edit IOC dialog, the steps described in the original ticket are not possible anymore as each dialog only contains the PV Sets for the IOC being edited. Closing this issue.
