### ISSUE TITLE
IBEX: edit config window: IOC settings from component are not shown

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1355]
Any non-default IOC settings that are part of a component are not displayed in the GUI when said component is added to a configuration.

Steps to reproduce:
1. Create a new configuration 1, check some of the auto-(re)start boxes in the IOC tab.
2. Save as component
3. Create a new configuration 2, add the previously created component. Save.
4. Edit configuration 2. The IOC tab should contain the same checked boxes as the previously created component, but it does not.

Furthermore, the component IOCs should not be editable as long as that component is part of the configuration, as is the case with blocks and groups.

**Comment by DominicOram** [comment]
Putting into impeded as there is some work from https://github.com/ISISComputingGroup/IBEX/issues/1884 that should be merged first

**Comment by Tom-Willemsen** [comment]
1884 is merged now. Moving out of impeded.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/488
https://github.com/ISISComputingGroup/ibex_system_tests/pull/44
