### ISSUE TITLE
genie_python script checker enhancements [TIMEBOX: 2d]

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1359]
There is a bug that means if a line starts with end, begin etc. the checker thinks it is a call to the DAE, so if it doesn't match end() it raises an error.

e.g. endAngle = 5

This needs to be fixed and we should add unit tests. We should also look for other ways to enhance it too

**Comment by John-Holt-Tessella** [comment]
See #1345 for original bug
