### ISSUE TITLE
Script Server: Start NICOS with Instrument

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1362]
1. As part of start_inst on the backend the NICOS backend should also be started up
2. The NICOS backend should be aware of genie python commands
3. A NICOS account should be present for the GUI to use

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/EPICS#28 and ISISComputingGroup/nicos-core#4

Details on how to test are in the pull requests.

**Comment by AdrianPotter** [comment]
Functionality tested and code reviewed and merged. Please update .gitmodules in the main EPICS repo and the release notes: https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev

**Comment by AdrianPotter** [comment]
Submodules updated

**Comment by IsabellaRey** [comment]
Added to release notes
