### ISSUE TITLE
Script Server: Create an IBEX NICOS Script Server Window

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1363]
This is only a ticket to make a quick mock-up of the perspective.

Keep in mind that the perspective should be able to be easily disabled as this view may not be on any real instruments for some time

**Comment by IsabellaRey** [comment]
Review passed. Cannot be merged into master until we have defined a strategy on how to avoid activating in the released GUI those plugins that are still under development.

**Comment by IsabellaRey** [comment]
Can now merge, as Nicos perspective is not visible by default as per #1372
