### ISSUE TITLE
Script Server: Send a script to NICOS from the GUI

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1364]
Create a simple text editor with a send button, which will add the script in the editor to the NICOS queue on the instrument.

This relies on #1363.

Remember to include instrument switching in this so that scripts can be sent to other NICOS backends. The username/password set in #1362 will also need to be used but can be hard-coded into the GUI for now.

**Comment by AdrianPotter** [comment]
Wait for #1456 as well

**Comment by DominicOram** [comment]
Do this after https://github.com/ISISComputingGroup/IBEX/issues/1756. Can be tested using nicos-gui

**Comment by kjwoodsISIS** [comment]
What is impeding this story?

**Comment by DominicOram** [comment]
It cannot be started until #1756 is merged.

**Comment by AdrianPotter** [comment]
#1756 has been merged. Moving out of impeded
