### ISSUE TITLE
Dataweb speed up: Generate the page

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1371]
This is a sub ticket for #1191 

The service needs to pull in the various pages of blocks information from the instrument, as well as the config details, and build an appropriate page showing the current values

It was felt that getting the single GET_CURR_CONFIG_DETAILS PV, and the timeout for this should be acceptable, as a long delay on this would indicate an issue with the instrument

It needs to display the blocks by group
It needs to differentiate between hidden/non-hidden blocks, only showing hidden ones when that option is selected
It needs to pay attention to the "hide title" PV, and hide that information when the title is set to hidden
If it cannot get the xml, or the PV it should display an appropriate message, e.g. "INST is offline, the last config in use was xxxxxx at yyyyyyy"

**Comment by KathrynBaker** [comment]
There should also be a check on the INST archive for the SP records, and if you can find them easily display that alongside the value as (setpoint = spvalue)

**Comment by KathrynBaker** [comment]
There are a couple of seemingly error situations that are easily solved, and should be undertaken, typically these are based on the web service not restarting or not getting data after a restart. (This is done by the ICP at the start of every run, so it is an unlikely situation for this system, but the exceptions should be coded for).

Should the HTML return Error 400, or when looking for blocks in the XML they can't be found but they are expected, send a /restart to the appropriate location and try again before declaring either the block or the system unreachable.

**Comment by kjwoodsISIS** [comment]
If the web service doesn't re-start then an Error 400 seem appropriate.
If an individual block is unreachable, then the system should state that it is unreachable (or disconnected, or whatever, ....).

**Comment by KathrynBaker** [comment]
Replaced by #1382 in order to utilise different technologies
