### ISSUE TITLE
Update BlockServer to support a PV to toggle Experiment Title Display on/off

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1373]
Sub-ticket for https://github.com/ISISComputingGroup/IBEX/issues/1192.

Add a PV to the BlockServer for toggling the visibility of the experiment title in the Dataweb dashboard page via the GUI.

**Comment by KathrynBaker** [comment]
This would be better in an IOC (the DAE) for use with the dataweb display rather than in the blockserver. That way it can be added to the archive items and can be retrieved and used more easily where it is needed, and keep the number of PVs the dataweb page generator has to deal with to a minimum.

**Comment by ThomasLohnert** [comment]
Yeah, I agree it makes more sense in the DAE

**Comment by AdrianPotter** [comment]
Tested using Ticket #1374 version of the GUI. PV exist and reacts as expected
