### ISSUE TITLE
Update IBEX client to allow the user to toggle Experiment Title Display on/off.

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1374]
Sub-ticket for https://github.com/ISISComputingGroup/IBEX/issues/1192.

Add a control to the IBEX GUI connected to the PV for toggling the visibility of the experiment title on the Dataweb dashboard page.

**Comment by AdrianPotter** [comment]
Please add system tests

**Comment by AdrianPotter** [comment]
Needs entry adding to release notes
