### ISSUE TITLE
Datweb: Extend the user functionality

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1375]
As a user I would like to extend the dataweb dashboard to show some extra information such as set-points, alarm states, run control states

**Comment by DominicOram** [comment]
I am about to send an email to group leaders so we can ask them what they want out of the web dashboard in the long run. From this create a design document

**Comment by DominicOram** [comment]
From discussion with Large Scale Structures:
•	It would be good to have spectra and detector images available
•	The dashboard must be kept simple for accessing over poor connections (A second site with more functionality might be good)
•	Instrument Scientists mostly use the site on mobiles, users may use it if they are not at RAL
•	Plotting blocks etc. on request would be useful
•	The run status should be much more prominent
•	 It would be useful to show currently running scripts
•	The main things users/scientists care about is are there any errors and how far through a run are we
•	Functionality should be prioritised over style
•	A broad look at how people interact with the control system may be useful (e.g. look into an app to provide notifications for alarms on instruments)
•	It would be nice for the display to be customisable (freeboard.io  was mentioned as something that could be useful)

I will continue to bug other groups.

**Comment by DominicOram** [comment]
Impeded by other science groups not responding. If there is no further response by the end of the sprint I will close and create some tickets for the work mentioned above.

**Comment by ChrisM-S** [comment]
It might be good to put this in context of ticket #2140 (IBEX Client (short) design review etc.)  There might be a simple distinction in client functionality for a web-dashboard/mini-client interface which would help us.  For example only WEB 2.0 protocols for browser compatibility without plugins (or even with a plugin?).  i.e. maybe see everything but no control via Kafka?

**Comment by DominicOram** [comment]
Added #2240 and #2239 as first steps. #2159 is also part of this.
