### ISSUE TITLE
unable to add logging to an existing block in the current config

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1377]
Right click on a block and select edit block, or go via the menu options to edit the current config, disable the logging (just click on the enabled checkbox for the logging settings) - the block disappears from the archive engine. Go back into that block and click the enabled checkbox again (to enable the logging) and the change isn't saved.

(May want to check the Run-Control settings as well)

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/280
https://github.com/ISISComputingGroup/ibex_system_tests/pull/16

**Comment by DominicOram** [comment]
System tests need work, merged rest

**Comment by IsabellaRey** [comment]
I am un-picking this from review, as I didn't really have time to do anything about it. Would be just good to check if system tests pass and if they fail when the changes are not there

**Comment by John-Holt-Tessella** [comment]
Tests look good to me, they are testing the GUI which for the moment is enough.
