### ISSUE TITLE
Linux: Several small issues prevent installing and running IBEX/EPICS on Ubuntu 14.04

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/IBEX#1378]
Trying to install a fresh copy of IBEX on Ubuntu 14.04, I ran into the following issues:

- EPICS/isisdoc/make_manuals.sh fails with a bash: Bad substitution error during make
- BlockServer throws an exception saying PV_postEvent takes exactly 3 arguments (2 given)
- BUILD_ARCH (build_arch.txt) gets set to "st.cmd" instead of "linux-x86_64" at some point during startup. Unclear about impact, but this is certainly not good.

**Comment by John-Holt-Tessella** [comment]
I will review this when I have finished my current ticket.

**Comment by John-Holt-Tessella** [comment]
All changes are sensible and I can build the instrument but I have not go as far as running it. I will approve the changes and at some point get this running on my virtual machine. There is a ticket for this https://github.com/ISISComputingGroup/IBEX/issues/1205
