### ISSUE TITLE
Machines are not pushing config changes

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1379]
As an instrument scientist I expect my configuration changes to be pushed to my branch in the configuration repository.

There appears to be no ZOOM or IMAT and LARMOR is old. Repository was the one on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)

**Comment by kjwoodsISIS** [comment]
Define exactly what should happen and implement it.
Then produce a troubleshooting page on the wiki.

**Comment by DominicOram** [comment]
The git repo in question is http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/inst

This repo should have all of the instrument configurations on it, each in their own branch. The local repo should be created on instruments as part of the documentation linked above and pushed to by the blockserver when configurations are changed. I suspect there is an issue in how the blockserver is pushing configs.

**Comment by DominicOram** [comment]
This is fixed by the two referenced PRs. However, due to https://github.com/ISISComputingGroup/IBEX/issues/1436 this will break all system tests. So is currently impeded until that issue is fixed.
