### ISSUE TITLE
Dataweb: Blockserver: Serve the current config details as JSON via a URL

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1380]
As a developer I want to be able to get the current config details via a URL for use with the dashboard.

There needs to be a URL that is unique to each instrument
The page should consist of the JSON relating to the current configuration running on the machine
There are asynchronous web servers that might be of use to this
It would be a good idea to look at compressing this information using HTTP compression
The contents of the URL should be updated alongside any changes made to the blockserver
This should be an additional class in the blockserver, and might be well suited to be an additional package
A wrapper, tests and mocks will be needed for this functonality

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/62 as a first draft. This isn't asynchronous and is uncompressed. Are these features entirely necessary at this stage?

**Comment by KathrynBaker** [comment]
Those features probably aren't needed at the moment, the compression is probably of more use once we start getting large configs being passed via this server, but we could leave that to be a concern when we know what the hit is.

**Comment by KathrynBaker** [comment]
All works nicely, and updates happily.
