### ISSUE TITLE
NICOS: Python installation to include modules for Nicos

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1385]
Currently the build_python.bat script in genie_python/package_builder does not install the modules needed to run Nicos, but it should.
Installation requirements for Nicos can be found at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Installing-Nicos-on-Windows

NOTE: the developers manual has a step to install the C++ compiler for Python 2.7: we think this might only be needed to run the nicos-gui (which for us is only a testing tool). Try at first without the installer if you can run the daemon (try the cache too, as we will probably need it in the future).

**Comment by John-Holt-Tessella** [comment]
I did:
`C:\Instrument\Apps\EPICS\ISIS\ScriptServer\nicos-core\master>"c:\Instrument\Apps
\Python\Scripts\pip.exe" install -r requirements.txt`

and my requirments.txt was edited to look like:
```
--extra-index-url https://forge.frm2.tum.de/simple
#--allow-external nicoslivewidget
#nicoslivewidget>=1.2 ; python_version < '3.0'
--allow-external nicos-pyctl
nicos-pyctl>=1.0
--allow-external mysql-connector-python
mysql-connector-python>=1.0.7
scipy>=0.9.0
matplotlib>=1.1
numpy>=1.6.1
pyserial>=2.5
pyzmq>=13.1.0
lxml>=2.3.2
pyfits>=2.4.0
rsa>=3.1.2
gr>=0.16.0
ldap3>=0.9
psutil>=2.0
python-redmine>=1.0.2
pyepics>=3.2.4
```

**Comment by AdrianPotter** [comment]
Created the new PR for a minor change:

https://github.com/ISISComputingGroup/genie_python/pull/61

The other PR for the main functionality for this ticket has already been closed:

https://github.com/ISISComputingGroup/genie_python/pull/59
