### ISSUE TITLE
Muon Front End: Momentum Slits (and Barn Door Jaws)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1388]
Needed for September Cycle, but need hardware to test aspects of it

As a support person I would like all the Galil interactions for the muon Galil to be handled in one location, rather than 4.

__Acceptance Criteria__
1. There are PVs to allow the different control requirements of the Muon Galil to be available
2. Where control is required by one instrument, it is able to do so via the access gateway, while other items cannot control it
3. The muon front end system can talk to the galil through the firewall

__Notes__
1. The momentum slits are a single motor driving an aperture (1 motor, 2 slits as in the photo below), the final details of the inearity and logic for this is still to be confirmed, but will need an OPI and an appropriate db file and motion axes aliasing. This will be a standard motor and an alias for the gap.
2. The barn door jaws requires some galil code to be downloaded, a variable in the galil to be set (there is a PV to do this), then the appropriate program to be executed on an appropriate thread. The value for the variable will be sent from the Instrument PCs (one jaw set, one program, one variable, one readback each for HIFI, MUSR and EMU), and this will need to send out the analog readback for each jaw set via a PV. Due to the unique nature of these jaws, there is not an immediate need to transfer all the functionality (e.g. the lookup between the voltage being used and it's associated gap) into EPICS, but this should be noted as a consideration for future work, and will need to be addressed when the muon instruments are converted to EPICS.

momentum slits photo:
![20160707_113158](https://cloud.githubusercontent.com/assets/10552381/16685911/3d7208ba-4506-11e6-8fbd-709e9004b43e.jpg)

**Comment by kjwoodsISIS** [comment]
After discussion, we think a lvDCOM solution will be easiest.

**Comment by John-Holt-Tessella** [comment]
Writing some info here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Barndoors-and-Momentum-Slits-on-MUON-Front-End

**Comment by John-Holt-Tessella** [comment]
![image](https://cloud.githubusercontent.com/assets/7570055/16876896/b5a83164-4a9d-11e6-82de-cb27e9e33e73.png)

Voltage vs position. Question is it correct to take only the right hand side of this graph?
