### ISSUE TITLE
Configurations: Long names not visible remotely

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1394]
As was found with the synoptics, long config names are not visible on remote systems, despite appearing in the configs list.

The fix for this could however be different, the config names already have a pv listed within the configurations information, it may be possible to programatically set this value to be something other than an invalid name which might make this change invisible to users (unless they have a habit of using cagets to look at their configs), and assuming that the GUI can use that value to load the config

**Comment by DominicOram** [comment]
It's worth noting that whilst config name and PV are currently the same, both the BS and GUI do not make that assumption. Obviously it's nice to have them the same for us connecting to them manually but this is quite rare. Maybe the solution here is for the blockserver to create a shortened version of the name for the PV?

**Comment by DominicOram** [comment]
Summary of comments made on slack regarding this ticket:
1. Would be nice to have PVS somewhat related to names
2. Blockserver could truncate name to n-3 and append _01 etc.
3. Blockserver could also remove vowels (giving a shorter but somewhat related name)
4. Synoptic names/PVs are also decoupled, they should follow the same rules as the configs
