### ISSUE TITLE
LARMOR: IOC & OPI for 3D Magnet System

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1398]
As a scientist, I would like an IOC & OPI for the 3D Magnet system, so that I can use them to control the magnet and its supporting devices in my experiments.

##### Acceptance Criteria
1. I can view and change the PVs which define the state of the 3D Magnet system (e.g.via scripts).
1. I can view and change the state of the 3D Magnet system via the IBEX GUI.

##### Notes
1. The 3D Magnet system comprises:
   1. temperature controllers, 
   1. 3 magnet power supplies, 
   1. helium level. 
   1. a rotation stage, 
   1. a needle valve control, 
1. There is a manufacturer supplied VI.  A copy of the manufacturer's VI is located on the C: drive on LARMOR, in ```C:\LabVIEW Modules\Drivers\Scientific Instruments\3D Magnet\Source Code\Vector-control-v16isis.vi```
1. With such a complex system, and given that there is a manufacturer supplied VI, a lvDCOM solution is the most appropriate approach.
1. The rotation stage can be controlled via the normal EPICS motor record (i.e. does not need to be controlled via LabVIEW).
1. Need to consult with Rob Dalgliesh to see what is required in terms of a UI and what PVs should be available for scripting.

**Comment by kjwoodsISIS** [comment]
Original e-mails requesting support for 3D magnet:
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 12 July 2016 14:09
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Akeroyd, Freddie (STFC,RAL,ISIS)
> Subject: FW: 3D cryomagnet 
>
> Hi Kevin,
> 
> Just to let you know that I believe Rob would like to use a 3D magnet system on LARMOR for the September cycle.
> 
> The system uses temperature controllers, 3 magnet power supplies, rotation stage, needle valve control, helium level. There is a vi that is supplied from the manufacturer to control the equipment. It sounds to me as though LVDCOM could be appropriate.
> 
> Below is his email. I will confirm the requirement as definite as soon as I can.
> 
> Regards,
> 
> Gareth
> 
> 
>> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
>> Sent: 12 July 2016 09:32
>> To: Bunce, Dave (STFC,RAL,ISIS); Down, Richard (STFC,RAL,ISIS)
>> Cc: Howells, Gareth (STFC,RAL,ISIS); Haynes, Richard (STFC,RAL,ISIS); Church, Andy (STFC,RAL,ISIS)
>> Subject: 3D cryomagnet 
>> 
>> Hi Dave, Richard,
>> I would like to schedule the 3D cryomagnet on Larmor at the start of the September cycle for a week long experiment.
>> We will need the rotating centre stick to be working.
>> 
>> Will this be a problem?
>> 
>> Thanks
>> 
>> Rob

**Comment by kjwoodsISIS** [comment]
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 11 August 2016 17:23
> To: Woods, Kevin (Tessella,RAL,ISIS); Akeroyd, Freddie (STFC,RAL,ISIS)
> Cc: Dalgliesh, Robert (STFC,RAL,ISIS)
> Subject: LARMOR : 3d Magnet for second week of coming cycle
> 
> Dear All,
> 
> Rob Dalgliesh is intending to scheduling a large 3D magnet on LARMOR for the second week of the coming cycle. This system is from a manufacturer and had LabVIEW vis supplied. Currently the system has NO computer associated with it but DOES HAVE a moxa dedicated to it. We run the LabVIEW control software on the ndx control machine after adding the MOXA configuration to the control machine. There is a needle valve that is presently driven from a Galil analog voltage output line. This will have to be addressed to work on LARMOR with a minor modification to the LabVIEW code (I believe).
> 
> There is also a rotation stage that is currently intended to be Galil. I think this part should be fine as Rob can use one of his spare Galil axes.
> 
> The LabVIEW control software can be found in :
> C:\LabVIEW Modules\Drivers\Scientific Instruments\3D Magnet\Source Code\Vector-control-v16isis.vi
> 
> Kind regards,
> 
> Gareth

**Comment by kjwoodsISIS** [comment]
Discussed by Gareth, Freddie John & Kevin (on Friday, 12th August 2016).
* the 3D magnet has mainly been used on POLREF up until now.
* currently controlled via LabVIEW running on the NDXxxxxxx PC (at some point in the future it might be better to control it from a dedicated PC).
* uses a dedicated Moxa, because the whole 3D magnet system includesd several devices which all uses RS-232 ports:
   * 2 x temperature controllers
   * 3 x power supplies (for the 3 orthogonal superconducting coils)
   * helium level system
* the needle valve is controlled separately from the other devices (currently takes an analog signal from a Galil controller, which is used to drive the motor that drives the needle valve itself).
* the rotation stage is also controlled separately via a Galil controller.
* need to check if Rob has a spare Galil controller (can't have LabVIEW and EPICS both controlling the same Galil).
* we agreed the lvDCOM was the best way to add support into IBEX

**Comment by kjwoodsISIS** [comment]
Gareth reports that LARMOR may wish to use a Lakeshore 336 as part of their setup.

**Comment by kjwoodsISIS** [comment]
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 17 August 2016 17:55
> To: Woods, Kevin (Tessella,RAL,ISIS); Holt, John (Tessella,RAL,ISIS); Akeroyd, Freddie (STFC,RAL,ISIS)
> Subject: 3D magnet for LARMOR
> 
> Dear all,
> 
> Latest update : the 3D magnet will be cooled down early September and takes approximately 3 days to cool down. I believe this is good news as I think we have time to put together a genuine test in the magnet lab at the back of R80, before it goes onto LARMOR. As long as we use small fields and small changes in temperature I think we should be fine. I turned the system on today briefly. Useful parameters currently are :
> 
> Cryocon 14 : 130.246.36.211                         (Need to check DHCP reserved)
> MOXA IP address : 130.246.37.108            (Need to check DHCP reserved)
>                                                                                 Port 1 : SMC X
>                                                                                 Port 2 : SMC Y
>                                                                                 Port 3 : SMC Z
>                                                                                 Port 4 : Cryocon 32 temperature controller
>                                                                                 Port 5 : Helium level meter
> 
> I think this will be ok to get it operational. Depending on the timing factors, we may be able to hook it up to ndxlarmor itself to further mitigate issues.
> 
> Regards,
> 
> Gareth

**Comment by kjwoodsISIS** [comment]
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 22 August 2016 18:15
> To: Dalgliesh, Robert (STFC,RAL,ISIS); Bones, Jon (STFC,RAL,ISIS)
> Cc: Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Subject: 3d magnet rotation stage
> 
> Hi Rob and Jon,
> 
> 3D magnet rotation stage is now configured on LARMOR in EPICS (for the second week of cycle). Details are : 
> 
> Used 2nd sample environment axis. It is labelled in the table of motors (MTR0702)
> +- 370 degrees
> Motor with encoder.
> No limit switches.
> Home position defined by an index pulse on the encoder. Just be careful you do not wrap around too many times.
> 
> Jon, thank you for finding the stage – much appreciated.
> Rob, thank you for finding the cables - much appreciated.
> 
> Stage looks good for cycle. Motion system left tripped and 3d magnet rotation stage cables disconnected.
> 
> Regards,
> 
> Gareth

**Comment by IsabellaRey** [comment]
Functionality looks OK. There are some fixes needed before merging please, mostly cosmetic:

- [ ] configure/RELEASE file in both support module and ioc: change EPICS_BASE to use "Instrument" instead of "INSTRU~3"
- [ ]

**Comment by GDH-ISIS** [comment]
Just a quick update regarding the 3D magnet for LARMOR :

1)	I have updated the LabVIEW code on LARMOR.
2)	Added MOXA used for the 3D magnet to LARMOR (COM PORT 101 to COM PORT 116). This is out of the way of the standard COM port range -  can be altered if not appropriate.
3)	Turned on equipment.
4)	Started software. Everything communicated.
5)	Stopped LabVIEW code.
6)	Turned everything off. 

I believe the cryogenics group will start cooling the system down early next week.
