### ISSUE TITLE
Spectra Plot Update

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1402]
Spectra plots may not update correctly, reported by the user on IMAT

Reproduce by:

1. Go to DAE Tab
1. Update the plot number
1. Click Set Plot

About 1 in 10 times plot is not updated.

Is this a race condition between switch PV and update plot?

**Comment by IsabellaRey** [comment]
On review, plot still doesn't update every time, see comment in pull request.
