### ISSUE TITLE
IRIS: Support for Lakeshore 336 Temperature Controller

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1404]
As scientist working on IRIS, I need to monitor and control the temperature on a Lakeshore model 336 temperature controller.

##### Acceptance Criteria
1. I can view and change the PVs which define the state of a Lakeshore model 336.
1. I can view and change the state of a Lakeshore model 336 via the IBEX GUI.

##### Notes
1. IRIS will need at least one, possibly more than one Lakeshore model 336 controller.  Initially, we will assume they just have a single device.
1. Essentially, we will need an IOC and OPI.
1. There is an existing EPICS driver for the Lakeshore model 336 temperature controller - see http://www.aps.anl.gov/epics/modules/manufacturer.php#Lakeshore
1. See also #1097 & #1098 which implemented support for a Lakeshore model 218 temperature controller

**Comment by IsabellaRey** [comment]
Created IOC, OPI and Emulator.

To test the IOC you will need the following pull requests:
* ISISComputingGroup/EPICS-lakeshore#1
* ISISComputingGroup/EPICS-ioc#56
* ISISComputingGroup/EPICS#35

For the OPI:
* ISISComputingGroup/ibex_gui#293

For the emulator:
* ISISComputingGroup/EPICS-DeviceEmulator#2

Details on testing on the individual pull requests

**Comment by IsabellaRey** [comment]
I have the real device on my desk, you can get it to review the ticket

**Comment by AdrianPotter** [comment]
I've got the device now - in case anyone else comes looking for it.

**Comment by AdrianPotter** [comment]
Great work. There's a lot of elements on this ticket and it's all working together nicely. Just a few things from discussion between Isabella, Ian and me:

- OPI
    - The set points all take negative inputs, and when they do the RBVs update to the absolute value of the input. I don't think negative inputs should be accepted at all unless appropriate.
    - Having discussed with Ian, let's rename the "Measurement" labels to "Input" so we have consistent terminology
    - For alarm labels where the only states are "alarm" and "no alarm", let's use a red LED instead
    - Please put the heater output as a 2nd y-axis plot on the temperature graphs.
    - Ultra picky, but the spacing between the 1st and 2nd row on the output details OPI is much bigger than the 2nd and 3rd rows. Please could the spacing be made consistent.
- IOC
    - Please implement John's activity PV so the temperature graphs in CSS keep extending line plots even when the value remains constant
- Device emulator
    - Please implement a base "Command" class that the other commands can derive from
    - The emulator class currently has responsibility for managing communication with the Telnet server, tracking the state of the model, and executing commands. This effectively combines the model and the "view". Please could the emulator be refactored to separate these concerns as much as possible.

**Comment by IsabellaRey** [comment]
Additional points:
* Optional: have SIM macros (see TPG26X IOC) in the st.cmd so the IOC can easily be started in RECSIM or DEVSIM mode
* Double-check that protocol is built in data/ dir
