### ISSUE TITLE
IRIS: Support for IRIS CryoValve

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1405]
As scientist working on IRIS, I need to monitor and control the IRIS CryoValve (i.e. open it or close it).

##### Acceptance Criteria
1. I can view and change the PVs which define the state of the ISIS CryoValve.
1. I can view and change the state of the ISIS CryoValve via the IBEX GUI.

##### Notes
1. The IRIS CryoValve is a device that is unique to IRIS.
1. We can base the IOC and OPI on the existing VI for the IRIS CryoValve.  The commands for the CryoValve are very simple - they are documented in the attached readme.txt file.
1. When we have created the IOC and OPI, ask if we can test it on IRIS.

**Comment by AdrianPotter** [comment]
[IRIS Cryovalve - Readme.txt](https://github.com/ISISComputingGroup/IBEX/files/363684/IRIS.Cryovalve.-.Readme.txt)

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/285
https://github.com/ISISComputingGroup/EPICS/pull/30
https://github.com/ISISComputingGroup/EPICS-ioc/pull/50
https://github.com/ISISComputingGroup/EPICS-IrisCryoValve

**Comment by AdrianPotter** [comment]
I still have 2 cryo valves on my desk. Come get them from me when you want to do the testing.

**Comment by IsabellaRey** [comment]
Minor rework needed: IOC name should be max 8 chars long, and IOC top directory should have same name as IOC.
No functionality reviewed yet

**Comment by IsabellaRey** [comment]
Following review:

* Have protocol Makefile add protocol as "DATA += <protoName>" and st.cmd should set protcol path pointing at the data/ directory (see updated manual)
* MASTER_RELEASE file: just move CRYVALVE macro up so file is in alphabetical order
* OPI: add $(NAME) macro at least in the OPI Name property
* Add emulator

**Comment by AdrianPotter** [comment]
All done
