### ISSUE TITLE
IRIS: Support for MKS PDR2000 Pressure Transducer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1406]
As scientist working on IRIS, I need to monitor the read backs from a MKS PDR2000 Pressure Transducer (connected to a Baratron pressure valve).

##### Acceptance Criteria
1. I can view the PVs which define the state of the PDR2000 Pressure Transducer.
1. I can view the state of the PDR2000 Pressure Transducer via the IBEX GUI.

##### Notes
1. We can base the IOC and OPI on the existing VI for the PDR2000 Pressure Transducer.
1. There is an existing EPICS driver for a MKS PDR4000 Pressure Transducer - see http://www.aps.anl.gov/epics/modules/manufacturer.php#MKS%20Instruments - that could, perhaps, be adapted.  Alternatively, it might be simpler to create our own driver from scratch.
1. When we have created the IOC and OPI, ask if we can test with a real MKS PDR2000.

**Comment by AdrianPotter** [comment]
Waiting to hear from Gareth (or @KathrynBaker?) about getting hold of the VI and/or reference manual. Can't find it online. Putting back into pool until we've got a starting point.

**Comment by kjwoodsISIS** [comment]
There is an on-line manual for the PDR2000.  
There are also EPICS drivers for the PDR4000 transducer, which we might be able to modify. 
For both of these, please follow the links from https://github.com/ISISComputingGroup/IBEX/wiki/IRIS-Instrument-Details#noteMKS

**Comment by AdrianPotter** [comment]
Super, thanks. Also got the VIs from @KathrynBaker

**Comment by AdrianPotter** [comment]
@davidkeymer has also sent me a summary of the commands in use:

```
MKS PDR2000 commands used in VI: v - read version; p - read pressures; u - read units; f - read full scales.  All straightforward enough, however I think you may need to do some clever formatting of the replies to each command as both channels are returned.
```

@davidkeymer and Ian Silverstone currently looking into borrowing a physical device.

**Comment by AdrianPotter** [comment]
PR4000 IOC not applicable that I can see. Device protocol completely different.

**Comment by kjwoodsISIS** [comment]
Ah well.  It was worth a try!  :-)

**Comment by AdrianPotter** [comment]
The IOC and OPI are both ready now. I've tested with an emulated device (see #1418). I would prefer not to declare this done though until it's had a dry run on an actual device either in the office or out and about in the field. @davidkeymer, please let me know if and when you find one I can try.

**Comment by AdrianPotter** [comment]
Have contacted Chris Goodway on the advice of Ian Silverwood

**Comment by AdrianPotter** [comment]
Moving to review. Please test with simulation mode and emulators as no device is currently available. It has been noted that refinement of the protocol is likely to be needed following the first test session on Iris

**Comment by AdrianPotter** [comment]
Pull requests:

EPICS - https://github.com/ISISComputingGroup/EPICS/pull/38
IOC - https://github.com/ISISComputingGroup/EPICS-ioc/pull/59
Support module/device emulator - Already on master
GUI - https://github.com/ISISComputingGroup/ibex_gui/pull/299

**Comment by IsabellaRey** [comment]
Haven't tested the functionality yet. Could you please check the following before I continue:

* in st. cmd files dbLoadRecords command, the MKSPDR200 macro should be fixed to be IOCNAME
* in the support module, the protocol should be built into data/ (and so st.cmd updated to reflect this)
* IOC name should be max 8 chars long

Optional: have SIM macros (see TPG26X IOC) in the st.cmd so the IOC can easily be started in RECSIM or DEVSIM mode
