### ISSUE TITLE
DAE: Set default of display:title to "no"

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1408]
From the sprint preview meeting on 13/07/16. There was no clear answer on whether the default of the title:display PV should be yes or no.

Having the titled displayed is useful, but it's understandable that some don't want it. However, most won't switch it on if it off by default.

Personally, I think this would be better as an opt-out rather than the current opt-in. It also means that the state of the system prior to the introduction of the functionality is preserved.

04/08/2016: we discussed this and agreed it should default to "no".  The user can always change it later.

**Comment by KathrynBaker** [comment]
The default has now been in place for years, changing it would be a greater impact than leaving it at this point. Closing.
