### ISSUE TITLE
IBEX: "Show Title" checkbox enabled state doesn't update as expected

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1409]
If my instrument is running and I have the DAE view open, then stop my instrument, many of the controls disable but the checkbox doesn't.

Conversely, if I open the DAE view when the instrument is stopped, most of the controls are disabled. When I start my instrument, most of the controls become available but the Show Title checkbox doesn't.

That probably means that the enabled state of the block isn't properly listening to the underlying PV, it's just checking it once when it's created.

**Comment by kjwoodsISIS** [comment]
I don't think it really matters.  The purpose of the "Show Title" checkbox is to control the display of the title on the Dataweb page.  You should be able to toggle the status of the title on the Dataweb page irrespective of whether the DAE is running or the instrument is stopped.
