### ISSUE TITLE
IRIS: Monitor TPG26x (ISIS Vacuum System)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1411]
As an IRIS instrument scientist, I want to be able to monitor the TPG26x (ISIS Vacuum System), so that I can view its current status.

#### Acceptance Criteria
1. I can view the PVs which show current status of the TPG26x.
1. I can view current status of the TPG26x in the instrument GUI.

#### Notes
1. The TPG26x on IRIS is _not_ connected to a PLC, we connect directly to it.
1. There are two aspects to this story:
   1. Create an IOC to serve up the PVs
   1. Create a OPI to display the PVs in the instrument GUI
In ticket #216 we created an IOC & OPI for a TPG300.  We should check whether we can adapt it.

**Comment by kjwoodsISIS** [comment]
There are links to the Pfeiffer web-site here: https://github.com/ISISComputingGroup/IBEX/wiki/IRIS-Instrument-Details#notePfeiffer

**Comment by kjwoodsISIS** [comment]
When you pick up this story, please take a few minutes to estimate the story-points.

**Comment by IsabellaRey** [comment]
Done first review. Fixed needed as listed in EPICS-ioc pull request

**Comment by IsabellaRey** [comment]
This ticket is ready to go. I have merged the EPICS-related branches, just waiting for Jenkins to build the latest GUI pull request, then will move as review complete.

**Comment by John-Holt-Tessella** [comment]
Last change https://github.com/ISISComputingGroup/EPICS-TPG/pull/2

**Comment by IsabellaRey** [comment]
Merged the last change in the support module and fixed errors from the auto-merge of master into the GUI branch. Still waiting for Jenkins to pass the GUI PR, so I can merge and close this ticket
