### ISSUE TITLE
Block server does not sometimes restart archiver

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1413]
It seems that sometimes when you change configuration the archiver is not updated. This can be seem by looking the web page and seeing that the blocks there do not change, however the sql database does change.

**Comment by kjwoodsISIS** [comment]
> From: Facilities IT [mailto:FITservicedesk@stfc.ac.uk] 
> Sent: 17 July 2016 13:15
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Subject: INSTRUMENT (LARMOR): Computing: User Interface: Se blocks not being recorded in nexus... ISSUE=64728 PROJ=15
> When replying, type your text above this line. 
> ________________________________________
> Query Number 64728
> This is a copy of the most recent response to query number 64728 in the FBU IT Servicedesk.
> Customer : LARMOR Instrument
> Query Subject : INSTRUMENT (LARMOR): Computing: User Interface: Se blocks not being recorded in nexus file
> Query Status : New Instrument Request
> This email has been CC'd to : (permanent) ann.terry@stfc.ac.uk, richard.heenan@stfc.ac.uk, sarah.rogers@stfc.ac.uk, stephen.king@stfc.ac.uk, robert.dalgliesh@stfc.ac.uk, diego.alba-venero@stfc.ac.uk, james.doutch@stfc.ac.uk, kevin.woods@stfc.ac.uk, ian.bush@stfc.ac.uk, john.webster@stfc.ac.uk
> ________________________________________
> Query Description (newest entry at top)	
>   	
> Entered on 17/07/2016 at 13:15:35 BST (GMT+0100) by ISIS Computing Support:
> Having changed configuration the Bench_Rot and many other blocks are 
> persistently not being recorded which breaks Mantid reduction.
> A full restart fixed the problem but it looks like there is a problem with 
> changing configurations and block logging.
> 
> Reported by: Robert Dalgliesh (mailto:robert.dalgliesh@stfc.ac.uk)
> ISIS Instrument: LARMOR
> Name of computer problem was submitted from: ndxlarmor.isis.cclrc.ac.uk
> Current ISIS Cycle: 16/2
> Product: Instrument Problem/Bug Report
> Category: Computing: User Interface
> Severity: critical
> Priority: P1
> Scientist Contact Information: http://www.isis.stfc.ac.uk/people/instrument-scientists-4398.html
> Instrument Contact List (i.e. who gets these sorts of emails): http://sparrowhawk.nd.rl.ac.uk/footprints/contacts.html 
>

**Comment by kjwoodsISIS** [comment]
> From: Facilities IT [mailto:FITservicedesk@stfc.ac.uk] 
> Sent: 17 July 2016 23:53
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Subject: INSTRUMENT (LARMOR): Computing: User Interface: Se blocks not being recorded in nexus... ISSUE=64728 PROJ=15
> 
> When replying, type your text above this line. 
> ______________________________________
> Query Number 64728
> This is a copy of the most recent response to query number 64728 in the FBU IT Servicedesk.
> Customer : LARMOR Instrument
> Query Subject : INSTRUMENT (LARMOR): Computing: User Interface: Se blocks not being recorded in nexus file
> Query Status : Agent Response
> This email has been CC'd to : (permanent) ann.terry@stfc.ac.uk, richard.heenan@stfc.ac.uk, sarah.rogers@stfc.ac.uk, stephen.king@stfc.ac.uk, robert.dalgliesh@stfc.ac.uk, diego.alba-venero@stfc.ac.uk, james.doutch@stfc.ac.uk, kevin.woods@stfc.ac.uk, ian.bush@stfc.ac.uk, john.webster@stfc.ac.uk
> ________________________________________
> Query Description (newest entry at top)	
>   	
> Entered on 17/07/2016 at 23:53:16 BST (GMT+0100) by Akeroyd, Freddie:
> Hi Rob,
> 
> I think I know the cause (https://github.com/ISISComputingGroup/IBEX/issues/1413) and have a blockserver code fix, it’s a one-liner that could be applied to NDXLARMOR when it is next convenient to do restart
> 
> Freddie 
>

**Comment by KathrynBaker** [comment]
The pull request certainly covers these issues
