### ISSUE TITLE
IOC: Rename Lakeshore218

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1414]
The lakeshore218 IOC name (LAKESHORE218_01) is one character too long for some DEVIOS PVs on developers machines (at least on my machine and John's).

Lakeshore218 should be renamed to something shorter (ideally sticking to the new guideline of max 8 chars), consistently with Lakeshore336 (ISISComputingGroup/IBEX#1404)

Note: this involves renaming both files and folders. The top-level IOC folder should have the same name as the IOC too. It may be easier to create a new IOC from scratch with the new name and then copy over the relevant files

**Comment by IsabellaRey** [comment]
This is not quite a breaking change, but we should check whether existing instruments are making use of this IOC and check files that may need updating, such as autosave files (do we care about these ones?), globals.txt, configurations and synoptics. A TODO note should be added to the release notes.

**Comment by kjwoodsISIS** [comment]
#1416

**Comment by kjwoodsISIS** [comment]
LARMOR has a Lakeshore device in its [list of equipment](https://github.com/ISISComputingGroup/IBEX/wiki/LARMOR-Instrument-Details).  Not aware of any other instruments using Lakeshore devices.

**Comment by kjwoodsISIS** [comment]
How many story-points for this issue?

**Comment by IsabellaRey** [comment]
Maybe 1 point is enough if everything goes smoothly

**Comment by IsabellaRey** [comment]
IOC renamed to LKSH218

See pull requests:
ISISComputingGroup/EPICS-ioc#57
ISISComputingGroup/ibex_gui#295
