### ISSUE TITLE
Shorter IOC names

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1415]
Following discussion with Freddie and John on ISISComputingGroup/IBEX#1414 it was proposed that all IOC names (without "_01") should be no more than 8 characters long.

We should think about shortening names of existing IOCs. As shorter IOC names may less clear as to what they refer to, it was suggested that a "Full Name" PV is added to each IOC, and it is displayed in the GUI in the Start/Stop IOC dialog next to or in place of the IOC name.

We should probably have a discussion as a team about this.

**Comment by kjwoodsISIS** [comment]
See also #1644 - do at the same time!

**Comment by DominicOram** [comment]
Closing as has been done, https://github.com/ISISComputingGroup/IBEX/issues/1447 covers the full name part.
