### ISSUE TITLE
Introduce device emulation support to team workflow

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1418]
As a developer, I want to test IOCs and OPIs with as close to the full workflow as possible, even if I don't have access to a real device. 

Currently, we can only test up to the db record level, not at the protocol level.

Isabella has some code written for HiLase which would allow devices to be emulated by a simple Telnet client. I would like to adapt the code if necessary and introduce it to our repo and development workflows to assist with producing and testing IOCs

**Comment by kjwoodsISIS** [comment]
Just some food for thought (I am not suggesting we should change the scope of this issue).
We should have a think about the different ways in which we can emulate devices.  Record level emulation and telnet emulation are clearly two tools we can have in our "armoury".  A third one could be the simulators that Mike Hart is developing (although, these might be a longer term initiative)

**Comment by AdrianPotter** [comment]
Absolutely. Michael is currently working on a Linkam95 emulator. My impression is it'll be somewhat more sophisticated than what we're proposing here. I'm going to email Michael now so he can have a look at what we're doing to see how it fits in.

I've created a pull request on the main branch to include the new submodule:

https://github.com/ISISComputingGroup/EPICS/pull/32

the new repo is here:

https://github.com/ISISComputingGroup/EPICS-DeviceEmulator

and I've created a wiki page here:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Emulating-Devices

**Comment by AdrianPotter** [comment]
@mattclarke asked if the new code has a license, and have we checked whether CLF attached a license, and are they ok with us using it? Just checking...

**Comment by kjwoodsISIS** [comment]
@mattclarke & @AdrianPotter - I will check with CLF

**Comment by AdrianPotter** [comment]
Thanks

**Comment by AdrianPotter** [comment]
I've added the Eclipse public license to the repo. Waiting for a response about usage from CLF. Please close ticket in a few weeks if no further updates.

**Comment by FreddieAkeroyd** [comment]
@adrianpotter you mentioned you were going to contact Michel Hart, what was the outcome of that?

**Comment by AdrianPotter** [comment]
Michael's aware of the framework. He's currently working on a Linkam emulator, I don't recall whether he said he was going to use this in his work.

**Comment by AdrianPotter** [comment]
David is out at the moment. @IsabellaRey just sent a follow up email. If we don't hear anything by the end of next week, I'll move the ticket to review.

Could do with the pull request being merged anyway since we're now using the code in practice. @John-Holt-Tessella is reviewing; there was an unrelated Jenkins failure on the last attempt to build (which shouldn't build anything in the new repo).

**Comment by John-Holt-Tessella** [comment]
Repo merged into master. Waiting for reply on licence (although it is positive so far). If this comes back negative we will remove and rewrite.

**Comment by AdrianPotter** [comment]
Moving to review. Ticket has been stale for nearly 3 weeks. If this really needs chasing up, please create a fresh ticket.
