### ISSUE TITLE
Add automated IOC testing using emulated devices

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1419]
As a developer, I would like to be able to add automated tests for checking the behaviour of IOCs.

This would not previously have been possible since an IOC would otherwise require a physical device to talk to. With the introduction of emulated devices as part of Ticket #1418, we can feasibly set up a framework to set an emulated device to a specific state and then check its responses to given input.

Acceptance criteria:
1. There exists a framework for writing automated tests emulated devices
2. The framework is documented in Github explaining how to add tests and configure emulated devices
3. The automated IOC tests are run in Jenkins against the EPICS-IOC repo.

**Comment by John-Holt-Tessella** [comment]
I started to look at this as part of ticket #1411 and got stuck when launching the proc server command. There is something weird about:

    C:\\Instrument\\Apps\\EPICS\\tools\\master\\cygwin_bin\\procServ.exe  --noautorestart -L TPG268xEmulator.log -p TPG268xEmulator.pid -n TPG268xEmulator  -c /c/Instrument/Apps/EPICS/support/DeviceEmulator/master/tpg26x54722 C:\\Instrument\\Apps\\Python\\python.exe Tpg26xEmulator.py

vs

    C:\\Instrument\\Apps\\EPICS\\tools\\master\\cygwin_bin\\procServ.exe --logstamp --logfile="my.log" --timefmt="%%Y-%%m-%%d %%H:%%M:%%S" --restrict --ignore="^D^C" --noautorestart --wait --name=MOTORSIM --pidfile="my.pid" --logport=63993 --chdir="/cygdrive/c/Instrument/Apps/EPICS/support/motor/master/iocBoot/iocmotorSim" 63992 %ComSpec% /c C:\\Instrument\\Apps\\Python\\python.exe st.cmd

**Comment by IsabellaRey** [comment]
NOTE: the classes written for running IOC unit tests have their own unit tests too! These are currently under test_framework/tests/

They used to pass in Linux, it would be good to check they pass in Windows.
Please update these tests if you make any changes to the classes.

**Comment by IsabellaRey** [comment]
Note that the unit test framework was developed for linux. I think it would be best to proceed in steps:
* check that the emulator for this IOC can run on its own (outside of procserv)
* check that the test IOC can run on its own (this will mean updating EPICS base paths) and can talk to the emulator
* check that you can launch and stop gracefully the emulator with procserv from the command line (you might decide you don't need procserv at all)
* check that you can launch and stop gracefully the test IOC with procserv from the command line (you might decide you don't need procserv at all)
* check that you can launch them within python
* the existing python classes have methods to build, clean, launch and stop the IOCs. All these are written for linux: they will need fixing to work for Windows. We might decide we don't need to build/clean IOCs from within the test framework
* the existing framework uses pyepics to do caget/caput: we might decide we want to use the same classes as the blockserver instead

**Comment by FreddieAkeroyd** [comment]
Do we actually want the device emulator stopping and starting IOCs/procserv? I think it would be useful if it instead provided a simulation service that IOCs could connect to themselves on demand. So something like:

simulation service launched by start inst, no simulators initially present
IOC starts up up, sees it has been requested to do device simulation
so calls newly added IOC command passing IOC name to simulation service, which starts a simulator and returns port number simulator is running on
IOC now connects ASYN to this IP port rather than a serial port

**Comment by FreddieAkeroyd** [comment]
I can see running lots of instances of the simulator in separate procServs is a sort of simulation service, but might run into issues of assigning unique port numbers etc. for many devices

**Comment by John-Holt-Tessella** [comment]
Have started a branch because Ticket1419_testing_using_emulated_devices for this ticket in emulated devices because TPG tests were parked but I left the test file in the commit. I am going to remove it from there and put it in this branch. The test does not run.

**Comment by John-Holt-Tessella** [comment]
superseded by Plankton
