### ISSUE TITLE
Blockserver: Tests can be run from IDE

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1421]
For debugging and development purposes it would be useful if the unit tests can be run from within the IDE (PyCharm).
This will make it easier to debug and also increase the quality of the code.

**Comment by mattclarke** [comment]
How to test:
In pycharm, right-click on the various test files in test_modules and select "run unit tests". Confirm that they run successfully.
Run the whole test suite from the command line to confirm that still works.
Run up the instrument and check that still works as normal.

Note: You will need to have the corrected version of the _base component (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows) Setting up a configuration directory)

**Comment by mattclarke** [comment]
Most of the unit tests have been mocked so that they don't require access to the file system, e.g. configurations and synoptics are saved and loaded from memory.

Tests that rely on schema, for example, still use the file system.

**Comment by IsabellaRey** [comment]
This ticket is still under review. I am having some problems with loading configs from the GUI - need to check with Matt if it's just some setting on my machine or something needs fixing

**Comment by IsabellaRey** [comment]
Ticket reviewed, only last finishing touches needed, as indicated in pull request
