### ISSUE TITLE
Lakeshore 336: support for curve points

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1423]
The Lakeshore336 device allows reading and setting points of a specified calibration curve (one point at the time, see CRVPT protocols in the manual), but this feature is currently not supported in the IOC.

This might be a bit fiddly to get right.

At the time of the original ticket for creating the Lakeshore336 IOC (ISISComputingGroup/IBEX#1404) this feature didn't seem necessary, at least (to quote Kathryn) "until we know we're dealing with a lakeshore 340 (RS232 comms as opposed to Ethernet), as the standard lakeshore tool can be used over the Ethernet easily enough".  (as a background piece of info: lakeshore336 has Ethernet comms)

This ticket is being added as a reminder in case we come to need the functionality.

**Comment by kjwoodsISIS** [comment]
There is, as yet, no demand for this feature.  If we need to implement it, raise a new ticket.
