### ISSUE TITLE
GUI: Blank Log Plotter Fixes

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1428]
There are a couple of fixes to make to the blank log plotter screen. 
- [x] The text should mention that the screen can also be accessed through OPIs
- [x] The text should appear/disappear properly when the log plotter is accessed from an OPI
- [x] There should be system tests for this behaviour

**Comment by IsabellaRey** [comment]
Review OK, just waiting for release notes before merging

**Comment by DominicOram** [comment]
Release notes added
