### ISSUE TITLE
GUI: Make ToM suitable for colour-blind users

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1432]
As a colour blind user, I want the Table of Motors to use a high-contrast colour scheme, so that I can easily see what the display is telling me.
#### Acceptance Criteria
1. I can choose a high-contrast style of display, in which the state of the motors is indicated by the position or presence/absence of markers, rather than by different colours (which may not contrast well).
#### Notes
1. Existing users may be used to the current Table of Motors display style, so the proposal in this issue is **_not_** to replace the current style of display, but to offer an alternative.
2. A simple drop-down menu could allow the user to choose his/her preferred display style.
3. The current Table of Motors display uses a low contrast colour scheme.  Depending on the degree of colour-blindness, a colour blind person might not be able to tell the difference between the two states illustrated in the attached picture.  Use the [ColourOracle](http://colororacle.org/index.html) utility to see how the current display - 
   ![tom_full_colour](https://cloud.githubusercontent.com/assets/7249337/17179809/6517056c-5412-11e6-8d58-c2433b9d9e01.PNG) - 
   appears to colour-blind people.
4. There is a wiki page with hints & tips for [designing for colour blindness](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Designing-for-Colour-Blindness).
#### Suggested Display Style 1

The attached diagram ![tom_traffic_light](https://cloud.githubusercontent.com/assets/7249337/17179792/50c27fba-5412-11e6-83ec-377664803650.png) illustrates one possible alternative display style.  Rather than rely solely on colour to indicate the state of a motor we could use a traffic light scheme (as an alternative to the current style of display).  In this type of display, the state of a motor is indicated by the position of the light, as well as the colour.  The shapes don't have to be circles, they could be squares.  Notice also that the lights have outlines drawn in black.  In this display, red means the motor is active, but stationary; green means the motor is active and moving; grey means the motor is inactive (e.g. not connected, switched off, etc.).  Note: in this display the text fields have been left-justified to make room for the traffic light display.  It might also be worthwhile drawing the limit, arrow & home icons in outline instead of grey (and continuing to draw these icons as solid black when the motor is moving or has reached a limit or home position).
#### Suggested Display Style 2

Another possibility is to keep the same style of display as the current ToM, but allow the user to select a different set of colours by choosing a colour configuration file (just a test file listing named combinations of RGB values).  We can have one configuration file design for people with normal colour-vision and additional configuration files designed for people with red-green or blue-yellow forms of colour blindness.  Individuals could also tweak the file to adjust the settings to suit the severity of their colour blindness.  This has the advantage that it could be extended (over time) to include other other types of display.
**Note:** This type of configuration file is a _**client**_ configuration file; it is not an instrument configuration file.
#### Suggested Display Style 3

Please suggest an alternative display style.

**Comment by IsabellaRey** [comment]
After discussion with John and Tom:

Suggested Display Style 1 doesn't seem to add anything that is not already there: the point of the different background colour is to draw the eye of the user quickly without looking at the small icons at the bottom of the cell. The info from the traffic light would simply repeat what is already there, and again in small icons.

We will go for Style 2. However, to start with, we won't give the user the option to choose from a config file (would a user actually edit it anyway? where would we store this file?). Instead, the user will be able to select from a menu a colour mode from a list of existing ones. Additional modes can be added on request and will require re-deploying the client. If needed in the future we can revisit the config file option.

The user preference should be persited when the client restarts.

**Comment by IsabellaRey** [comment]
We attempted to set up persistence of the option between sessions, but this was taking too long so was abandoned. Setting the menu choice to be persistent is a simple setting in the manifest file, but we didn't manage to get the actual colour palette to be updated at startup. If needed, it can be added as it's own ticket.
