### ISSUE TITLE
System tests for the BlockServer

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1435]
The unit tests are all well and good but they do not test the whole.

What I would like is to be able to run a test script against a running instance of the BlockServer that:
- Checks that the expected PVs exist
- Can write, read and delete configs (confirm they are on disk)
- Same for the synoptics, spangle banner and devices
- etc.

All files saved should not be in C:\Instrument\Settings....\, rather a temporary directory should be used and deleted at the end.

Part 2 - Separate ticket?

It would be preferable if it did not rely on the full instrument being running (e.g. it doesn't need the run-control IOC or a real database). This would allow it to be run easily on the buildserver.

To achieve this it will be necessary to start the BlockServer in a test state, so it will probably need some adjustment to the command line args.

I don't want a "test=True" parameter being passed around to the various objects, so we need to think of a more elegant solution. Ideas:
- Possibly we could break encapsulation and inject mock objects where required
- Make the imports conditional so it can import the mocks when testing and the real classes when running for real.

``` python
if simulate:
  import mockruncontrol as runcontrol
else:
  import realruncontrol as runcontrol
```

**Comment by mattclarke** [comment]
Chris has suggested that this would also be a good way of checking a fresh installation is working.

**Comment by kjwoodsISIS** [comment]
We have way of creating & running system tests.  If we need to create appropriate tests, as described above, raise a new ticket.
