### ISSUE TITLE
IRIS: Install IBEX on NDXIRIS

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1439]
As a developer, I want to install IBEX on NDXIRIS well ahead of the new cycle (13th Sept 2016), so that I have plenty of time to test it with the equipment on IRIS and to resolve any problems.

#### Acceptance Criteria
1. IBEX installed on NDXIRIS
2. Confirmation that IBEX is working correctly on NDXIRIS.  (I should be able to control equipment on IRIS).

#### Notes
1. Make sure that Notepad++ is set to replace tabs with spaces. This makes things easier in the long run.
1. `init_iris.py` should be put in `C:\Instrument\Settings\config\NDXIRIS\Python\`. To create the `init_iris.py` file copy the `init_default.py` file and rename it.
1. Any scriptsused to "configure" the instrument" should also live in `C:\Instrument\Settings\config\NDXIRIS\Python\`. User scripts should go somewhere else, probably `C:\scripts` by default.
1. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-and-installing-genie_python for more details.

**Comment by AdrianPotter** [comment]
Release candidate 1 installed. Awaiting release candidate 2

**Comment by John-Holt-Tessella** [comment]
On IRIS and Ian is happy.
