### ISSUE TITLE
Dataweb: Get data from the archive engine pages

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1441]
Write a simple python program that connects to the archive engine pages:
* The INST page is: http://host:4812/group?name=INST
* The BLOCKS page is: http://host:4813/group?name=BLOCKS
* The DATAWEB page is: http://host:4813/group?name=DATAWEB
and puts the data into a python object.

**Comment by OliviaBourne** [comment]
Covered by ticket 1382
