### ISSUE TITLE
Save and restore snapshots of PV sets

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1449]
As an instrument scientist, I want to be able to save snapshots of a set of PVs (in general covering multiple IOCs) to capture the settings of my instrument at a particular point in time, and then be able to re-apply these settings at a later point.
When operating with different configurations I may be interested in the same set of PVs, just with different values

**Comment by IsabellaRey** [comment]
The motivation for this ticket originally comes from ISISComputingGroup/IBEX#1209

**Comment by KathrynBaker** [comment]
#8161 is a better version of this
