### ISSUE TITLE
IBEX: System Test ahead of Cycle 2016/03

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1450]
As a developer, I want to conduct comprehensive system testing of IBEX prior to cycle 2016/03 (13th September to 28th October), so that I can be confident that IBEX will run reliably on the instruments to which it is deployed.

#### Acceptance Criteria
1. Team is satisfied regarding the quality of IBEX.
2. Any recent issues reported by instrument scientists via the Footprints system are resolved (or, if they can't be resolved, we understand why and can propose a workaround).

#### Post-Testing
1. NDXDEMO is updated with a tested, fixed version of IBEX server
1. LARMOR is updated with a tested, fixed version of IBEX server
1. IMAT is updated with a tested, fixed version of IBEX server
1. The tested, fixed version of IBEX server is deployed to IRIS
1. The tested, fixed version of IBEX server is deployed to MUONFE
1. A tested, fixed version of IBEX client is made available to users
1. Record the version number of the build selected for release.

#### Notes
1. Should we update IBEX server on other instruments - notably ALF?

**Comment by AdrianPotter** [comment]
Testing finished. A selection of tests have failed, none critical, but many in need of ticket creation. @IsabellaRey is going to summarise and create the relevant tickets

**Comment by IsabellaRey** [comment]
The following tickets were created as a result of the system tests:

#1596

**Comment by IsabellaRey** [comment]
The template for manual system tests has been updated (available at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests)

**Comment by IsabellaRey** [comment]
NOTE: as part of this ticket the latest release 2.1.0 was deployed on NDXDEMO and NDXIRISTEST.

Regarding deployment on other machines:
* LARMOR: addressed by #1553
* IMAT: addressed by #1552
* IRIS: addressed by #1439 & #1453
* MUONFE: no ticket in for this sprint, but devices are being tested

**Comment by IsabellaRey** [comment]
Added spreadsheet with results of this test session at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests-Results
