### ISSUE TITLE
Shorter BlockServer PV suffixes

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1451]
Following on from #1394, long PVs mean that configuration names will soon be truncated to just six characters by the blockserver (accommodating a 60 character limit). Could certain PV suffixes be shortened to allow for longer names?

The longest PV seems to be `BLOCKSERVER:component_pv:GET_COMPONENT_DETAILS`. It was suggested that this could be shortened to `BLOCKSERVER:component_pv:GET_COMP_DETAILS`, for example.

**Comment by kjwoodsISIS** [comment]
Could also truncate BLOCKSERVER to BLKSVR.

**Comment by KathrynBaker** [comment]
BLOCKSERVER name has been shortened, closing.
