### ISSUE TITLE
GUI: display instrument info

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1452]
As a scientist or support person, I may not remember details about the instrument such as its PV prefix.

It would be useful to have a Help->About dialog that shows some useful information about the current instrument, such as instrument name, machine name, PV prefix, software version number (when we have it).

This information needs to be updated when the user switches instrument

**Comment by DominicOram** [comment]
This should be a bit easier now refactoring has been done on the Instrument Info data

**Comment by KathrynBaker** [comment]
Whilst the machine information is missing, given the large display of the system connected to in the dashboard at present that feels unnecessary, the other information is now available in a help > about.
