### ISSUE TITLE
IRIS: Test Session

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1453]
As a developer, I would like to test IBEX on IRIS, so that I can be sure that it communicates correctly with the various devices on the instrument.

#### Acceptance Criteria
1. IBEX installed on IRIS
1. Correct communication with each device on IRIS tested and confirmed (attach a copy of the log files as evidence).

#### Notes
1. Need to check which devices are actually installed on IRIS when we conduct the test.  It may be that some do not actually get connected until very close to the start of cycle 2016/03 (13th Sept.).  Need to liaise with instrument scientist.

**Comment by kjwoodsISIS** [comment]
Do it on a release branch.

**Comment by AdrianPotter** [comment]
Just to note, the MKS PDR 2000 needs explicitly testing with an actual device as this hasn't been possible during development. Some configuration changes (e.g. terminators in the protocol) are expected.

**Comment by John-Holt-Tessella** [comment]
I have added a new ticker just for the MKS PDR2000 see #1620
