### ISSUE TITLE
Improve auto-generated PV prefix

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1454]
For non-instruments, default PV prefix is computername:username: which can get too long. Proposal is to remove username and shortern hostname in a way that both server and client can calculate. Also move to TE: (test) top level prefix. Suggestion for shorterning hostname would be to take first say 6 characters and then add a two-digit hash computer from the full hostname

**Comment by FreddieAkeroyd** [comment]
Is related to #1451

**Comment by FreddieAkeroyd** [comment]
Merge ISISComputingGroup/EPICS#39 after GUI changes

**Comment by FreddieAkeroyd** [comment]
Instrument behaviour should be unchanged, developer computers will become e.g.   TE:NDW1158:   (most standard isis computer names are 7 character or less), and funny long names will be caught.  
 
The GUI will need updating to pick up non-instrument computers. It currently uses CS:INSTLIST to produce a list of instruments, but I think it should not include the local computer automatically in this list as having both IMAT and NDXIMAT in the instrument list is potentially confusing. If another name is typed as in instrument, a PV prefix should be prompted for but a guessed default provided from above algorithm detailed above. There is currently an ND restriction on valid names for additional instrument, can that be dropped?

**Comment by kjwoodsISIS** [comment]
Need to make a corresponding change to the GUI.

**Comment by IsabellaRey** [comment]
See ISISComputingGroup/IBEX#1109 and ISISComputingGroup/IBEX#1110 for dropping the ND naming restriction

**Comment by AdrianPotter** [comment]
I don't think we can merge this until the corresponding change to the GUI is ready. Setting to impeding awaiting the above tickets

**Comment by AdrianPotter** [comment]
Needs corresponding changes to the GUI. Going to review this in bulk with other instrument tickets
