### ISSUE TITLE
GUI: fix synoptic macros for Danfysik and TPG300

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1455]
For Danfysik, the "type" that appears in the synoptics has a typo, which should be fixed. At the same time, the macro used by the Danfysik OPI should be changed so instead of the IOC number we pass the full IOC name (so it's not hard-coded in the OPI).  At the time of writing, Danfysik IOCs are in use, but they don't appear in any synotpic in Larmor or IMAT, so hopefully no existing synoptic files need changing. A note should be added in the release notes to double-check this at the time of release.

For TPG300, the OPI requires a macro N, which actually if set would break the OPI! If N is left blank, the OPI points at IOC _01, but can never point at another IOC, e.g. _02.  The macro should be changed to be the full IOC name instead.   At the time of writing, TPG300 is in use in three synoptics in Larmor, where this macro will need updating at the time of release. Currently it's not in use in IMAT, but again it should be double-checked at release time

**Comment by AdrianPotter** [comment]
Pull request here:

https://github.com/ISISComputingGroup/ibex_gui/pull/298

I've updated the release notes for Larmor and IMAT to update their component macros as necessary.
