### ISSUE TITLE
NICOS: Convert pickled python to JSON

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1456]
Currently NICOS sends back and forth pickled python objects. Whilst there is a java library to handle such objects it's not perfect in converting things and doesn't do the 'magical' reflection of gson. Therefore a small layer should be written to allow NICOS to read/write JSON

**Comment by DominicOram** [comment]
Note that there are a couple of cases where NICOS expects unserialised data. The ones that I am aware of:
* When first connection is made a 32 bit unique ID is sent to the server
* When live data is sent from NICOS (we probably wont use this feature any time soon though)

**Comment by AdrianPotter** [comment]
Looks good. I've just added some comments on the code for review that might help with readability and flexibility. Please could you take a look.

**Comment by DominicOram** [comment]
Suggested changes made, feel free to add any more comments
