### ISSUE TITLE
Activate Checkstyle on all plug-ins for the IBEX GUI

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1457]
As a developer I would like to checkstyle to check all the plug-ins, there are a number that currently do not have this activated. It is probably worth doing a checkout and merge to master with that change for all of them at once, with no other changes in that merge. The number of allowed checkstyle errors/warnings for Jenkins may need to be increased to allow for this.

**Comment by DominicOram** [comment]
Checkstyle has been activated for all projects as part of https://github.com/ISISComputingGroup/IBEX/issues/1282.
