### ISSUE TITLE
BlockServer: Defining instrument-specific properties for Banner

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1460]
As an instrument scientist, I want a way to define instrument specific properties for display in IBEX' spangle banner (such as the bump stop for LARMOR).

At the moment, the BlockServer provides the bool_str class for simple Boolean properties with customisable display messages. A possible implementation would read e.g. an XML file and parse it into bool_str objects on startup.

**Comment by KathrynBaker** [comment]
+1 for the muon scientists - they would like to see some extra infromation, such as overall status of magnets

**Comment by DominicOram** [comment]
Done in https://github.com/ISISComputingGroup/IBEX/issues/3562
