### ISSUE TITLE
Add motor status string calc to other motors

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1469]
Take the MSTA -> motor status string out of galil motor into a more general file so it can be used by McLennan etc. Only issue is that galil uses 
$(P):$(M) whereas rest of motor world uses $(P)$(M) so bit of careful reorganisation needed

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/EPICS-motor/pull/2
https://github.com/ISISComputingGroup/EPICS-ioc/pull/72

Note that it'd be best to merge Ticket #1099 first

**Comment by FreddieAkeroyd** [comment]
Needs GALIL driver itself updating to do new way, will create an additional ticket
