### ISSUE TITLE
GUI: Delete config dialog allows current config to be selected

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1470]
In the delete configuration dialog window, a user's current configuration shows up in the list and can be selected for deletion. While it can't actually be deleted, no indication is given to the user afterwards. Moreover, if a user attempts to delete multiple configurations and, accidentally or otherwise, includes their current configuration, none of the configurations will delete.

Some suggestions:

- An indicator/error message could be displayed that a user is attempting / has attempted to delete their current configuration.
- The current configuration could be omitted from the list.

**Comment by kjwoodsISIS** [comment]
Omitting the current configuration from the list is probably the best solution.  If the user can't select the current configuration, he can't delete it.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_system_tests/pull/24
https://github.com/ISISComputingGroup/ibex_gui/pull/315

**Comment by AdrianPotter** [comment]
Rework issues have been addressed

**Comment by IsabellaRey** [comment]
Reviewed the rework.
GUI looks fine, but system test needs a fix, as per pull request

**Comment by AdrianPotter** [comment]
I've updated the system test to use a loop

**Comment by IsabellaRey** [comment]
Reviewed the loop, thanks. Test doesn't fail when it should, please see pull request.
