### ISSUE TITLE
Add IOC name and description to config.xml

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1471]
Relates to first part of #1447

**Comment by AdrianPotter** [comment]
A few comments attached to the pull request

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/40

**Comment by AdrianPotter** [comment]
Just retesting. Having run through the workflow that didn't work yesterday with Freddie, it's being more cooperative today. I'm going to have a closer look to see what's going on
