### ISSUE TITLE
Muon Front End: Control script should allow querying run number

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1473]
As a MFE user, I want the control script to allow me to query the run number for the instruments I'm connected to

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/mfe_control_scripts/pull/1

**Comment by John-Holt-Tessella** [comment]
How do I set up the MFE scripts? Is there some documentation in the wiki?
