### ISSUE TITLE
MUONFE: Test Danfysik Changes

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1476]
@ThomasLohnert  to write text ...

**Comment by ThomasLohnert** [comment]
Test the changes made to the Danfysik IOC in https://github.com/ISISComputingGroup/IBEX/issues/1208 on real devices to ensure proper functionality for both the 8000 and 8800 model. 
Communication with the devices (protocol correctness) and calibration should be tested in particular to ensure behaviour does not differ from simulated device.

**Comment by John-Holt-Tessella** [comment]
I update the SLEWABS:SP record to be OUT inetead of INP please test I have done the right thing.

**Comment by KathrynBaker** [comment]
Moved to impeded as until we have a PSU to test with we can't test this

**Comment by KathrynBaker** [comment]
Tickets #1597, #1599 and #1623 came out of this, the testing is complete

**Comment by AdrianPotter** [comment]
Moving to review_complete if testing is done
