### ISSUE TITLE
IOC: Linkam95 pump status reports incorrect values

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1477]
Found while Michael was testing with his Linkam95 emulator written with Plankton.

When the pump speed is 15-100, PUMP:STAT reports unknown values.

**Comment by AdrianPotter** [comment]
The PUMP:STAT PV assumes speed is 0-30 but we changed it to percentage 0-100 without updating the corresponding stat values.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/312
https://github.com/ISISComputingGroup/EPICS-ioc/pull/69

**Comment by IsabellaRey** [comment]
Looks good, only one minor fix needed:
PUMP:SPEED still says "percentage" in the DESC field

**Comment by AdrianPotter** [comment]
Fixed
