### ISSUE TITLE
Muon Front End: GUI not defaulting correctly

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1479]
When using the GUI on NDEMUONFE, the default instrument PVs are not set up correctly so it looks as if the instrument is not available and running when it is. The instrument has been swapped at the moment, and so long as no one changes instruments it should be OK. However, it is worth fixing this, as this will cause confusion otherwise. My guess would be that the default PVs look for NDX, and this being NDE gets classed as a dev system rather than an instrument within the GUI, so might be an easy fix, or disappear anyway with the other changes we have planned for the instrument selector, such as in #1452

**Comment by kjwoodsISIS** [comment]
Does the control PC have to be called NDEMUONFE?  Could it be called NDXMUONFE (or is there already a machine called NDXMUONFE)?

**Comment by KathrynBaker** [comment]
I went with NDEMUONFE in keeping with the naming conventions we had for CHIPIR. There isn’t an NDXMUONFE, but then, this isn’t an NDX system, different OS, no dedicated hardware, nothing on it except EPICS, no DAE, not as critical to keep running during a cycle as an NDX…

If we do decide to change the name then we will need to update the GUI as we will need to be able to access the system remotely. At the moment, it’s only locally the first time you ever start a version of the client that this will bite. I put it in as a bug, and there is no urgency for this (hence not giving it a milestone), but is something to be aware of if we can make it better in the future.

**Comment by kjwoodsISIS** [comment]
My reason for asking is that I think we should try to avoid any "special rules" about server names in the client as much as possible (and I do appreciate why we have naming conventions for development systems ...).  The ideal would be a solution that doesn't care if the server is called NDX... or NDE...

**Comment by KathrynBaker** [comment]
Indeed, which is where some of the other discussions we’ve been having come in relating to things like the instrument list (although I couldn’t find a ticket about that), and information in the help/about.

It should also probably not care if the server is NDW or NDLT, or any other system so that we can allow it to become more portable.

**Comment by John-Holt-Tessella** [comment]
This should now work because of fixes in #1510. However what does not work is that the hostname and alarm servers will not be set correctly when selecting from a machine which is not NDEMUONFE. This is because the host name is assumed to be NDXxxx for an item in the instrument list. This should be fixed when a PV is created containing the Host names for the RDB and alarm server.

**Comment by AdrianPotter** [comment]
The issue identified above should be fixed by #1109
