### ISSUE TITLE
GUI: Motor record controller indices incorrect

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1480]
In the motor record perspective in IBEX, there are multiple tabs for sets of motor records: 1-8, 9-16 and 17-24.

The indexing down the left hand side matches the controller number for 1-8, but it says 1-8 on the subsequent two tabs as well. I would expect it to be 9-16 and 17-24 respectively

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/302

**Comment by IsabellaRey** [comment]
Only needs checkstyle fixes as indicated in pull request
