### ISSUE TITLE
GUI: Motor record java exception on bad input

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1482]
If I open up Ibex and put a string in the target position of a motor record I get a java exception:

```
2016-08-12 16:17:38 ERROR: Failed to write value to PV NDW1695:HRA63823:MOT:MTR0502.VAL from widget Text Input.
Illegal input : Hello 
java.text.ParseException: Unparseable number: "HEllo"
```

It should be handled more gracefully

**Comment by KathrynBaker** [comment]
This no longer seems to be the case, or at least it is not visible in the built client
