### ISSUE TITLE
Dynamically Allocate procserv and conserver ports

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1484]
Currently these are hard-coded, but clashes are possible.

**Comment by FreddieAkeroyd** [comment]
Probably still a good idea, but we can avoid issues using 

netsh int ipv4 set dynamicport tcp 

see https://support.microsoft.com/en-gb/kb/929851

**Comment by ChrisM-S** [comment]
Hi Freddie,

Given that system defaults from VISTA onwards are already set to the IANA range (start=49152 num=16384 as far as I can see) does this mean we need to change the system configuration to something different?? i.e. the older windows ranges or a different range?

If so, what would the new values be so I can build them into the new clone and test – is this likely to affect anything else.

Thanks,

Chris

**Comment by KathrynBaker** [comment]
It might be nice to have an easy list/lookup of the ports in use if they are dynamically issued
