### ISSUE TITLE
EPICS ioc dependencies not set correctly

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1490]
If we have an IOC which uses substitutions and templates, where the templates come from a support module, the built .db file in the IOC is not updated on a simple make of the IOC (even with a new make of the support module), unless a make clean is done first.

The IOC doesn't seem to resolve its dependencies correctly when the template and the substitution files are not in the same place: compare the .db.d file in App\Db\O.windows-x64 for the LKSH336 to that of FINS (Note however that LKSH218 has template and substitusions in the same folder, but the .db.d file looks the same as the LKSH336!)

A post on tech-talk suggests that this (or something similar) was fixed in EPICS base 3.14.12.2, and we have 3.14.12.4, but it still doesn't work.

**Comment by IsabellaRey** [comment]
To reproduce, for example on the lakeshore336:
* do a make on the support module
* do a make on the IOC
* do a change in the lakeshore336.template in the support module
* do a make on the support module
* do a make on the IOC: the change is not picked up

If you make clean the IOC, and then make, the change is picked up

**Comment by FreddieAkeroyd** [comment]
I think this is fixed in 3.15 as it uses MSI to build dependencies
