### ISSUE TITLE
Db checker script should flag any duplicate fields

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1491]
Currently the db_checker.py script in C:\Instrument\Apps\EPICS\ISIS\DbUnitChecker\master\ fails the build with an error if a PV has multiple DESC fields, but it only flags a warning for multiple EGU fields.

For consistency, the script should fail the build whenever any field of the same PV is defined more than once

**Comment by kjwoodsISIS** [comment]
Check for duplicate PV names (issue a warning).

**Comment by AdrianPotter** [comment]
Happy with code. Please rework databases to conform to new pattern and mark for review  when done.

**Comment by DominicOram** [comment]
Fixed all errors, warnings still persist, I will leave those to be fixed as people go
