### ISSUE TITLE
GUI: Synoptic Editor - malformed controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1492]
The attached screenshot is taken from the Synoptic Editor dialog.  It shows two small "buttons" next to the list of PVs in the Component Details pane.  It is not clear what these two "buttons" are for.  Were they, once upon a time, arrow buttons?
![image](https://cloud.githubusercontent.com/assets/7249337/17701007/f5298de8-63bf-11e6-8531-6bf41161d324.png)

Client Version: 2.0.0.540

We should fix this.

**Comment by John-Holt-Tessella** [comment]
I do not see this on my version (which is dev versiob 2.0.0.3c14946

**Comment by KathrynBaker** [comment]
I think this might be a scaling issue based on OS and system being used (related to the resolution). I have arrows on my desktop, NDEMUONFE is missing arrows, on my laptop I have even more scaling issues (e.g. I can’t actually see the box to type in a custom prefix). So the buttons are probably fine, but our scaling isn’t.

**Comment by John-Holt-Tessella** [comment]
This is a difference between the tyco build and the eclipse version. I think it is probably part of having moved some icons into targets. Instead of being in synoptics. It should be a quick fix.
