### ISSUE TITLE
IOC: Linkam95 pump mode improperly set

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1496]
On startup, the Linkam95 uses a PINI on the pump mode to issue a command for it to go into auto state. Unfortunately, this is issued before the "T" command starts scanning. The Linkam insists that a "T" command comes first and so the auto pump mode is rejected.

Unfortunately, as there is no RBV for the pump mode, this could lead to unseen inconsistencies between the IOC pump mode and the device pump mode.

**Comment by kjwoodsISIS** [comment]
What is the proposed solution for this problem?

**Comment by AdrianPotter** [comment]
Duplicate #1509
