### ISSUE TITLE
OPIs: finish demo opi with new style

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1499]
Following the OPI chat on 18/8/16, take the existing templates of the Lakeshore336 for the new style and apply the changes discussed in the meeting.

The template can be shown to instrument scientists at the next sprint review before we take action on existing OPIs
- Labels should be bold to distinguish them from RBVs
- RBV widgets should have transparent background
- Use native buttons
- OPI title should have both generic device type and NAME macro
- Have ON/OFF buttons instead of boolean buttons with LEDs

**Comment by IsabellaRey** [comment]
I have updated the Lakeshore 336 demo of the new OPI style. This is in resources/Lakeshore336_OPI_demo.

Note that I have only changed enough OPIs to make the point:
* the main OPI, all tabs except the last
* Output settings OPI

Could someone please take a look, to see I haven't missed anything. If you want to run the lakeshore 336 IOC, you can start its emulator and start the IOC in DEVSIM mode. I have updated the opi_info file so you can create a test synoptic to compare the current OPI with this one, to see how it fits in the overall GUI.

Note these OPIs are mainly for demo purpose (though the widgets I've changed should be all hooked up correctly). I think this branch doesn't need merging for now, until we've decided on a strategy of how to go about changing and merging OPIs.

**Comment by IsabellaRey** [comment]
P.S. So just to clarify, I haven't created a pull request for this one

**Comment by AdrianPotter** [comment]
Couple of thoughts:

- The `control input` label is currently floating outside a group box. Should we allow floating controls (see next point)?
- The `output settings` button controls more than the group box it belongs to, perhaps this is a suitable case for a floating control
- The `Output 1` tab group box `Control parameters` has multiple columns of data. Should we do that, or stick to the strict row layout of other tabs. In this case in particular the value is below its label which is even more out of step with the rest of the style
- In the `Output settings tab` the `Control input` values are in a second column. Again, should we allow this? If so, can we add a separator? Further, the `label:RBV:SP` row pattern is disrupted as the drop down box is below the RBV. We should keep that pattern as far as possible.

**Comment by IsabellaRey** [comment]
NOTE: I have asked for feedback from Rob, Winfried and Ian on 8/9/2016, and waiting to see what they say

**Comment by IsabellaRey** [comment]
Feedback was very positive. Winfried had some concerns about the smaller fonts, so we're going to install a test build of the client from this ticket's branch on IMAT, at the same time as the release 2.1.0.

I'm moving this ticket to impeded until we get feedback from Winfried. We can wait 1-2 weeks counting from deployment on IMAT.

**Comment by kjwoodsISIS** [comment]
Moved to SPRINT_2016_09_08 because it is delayed a for at least two weeks.

**Comment by IsabellaRey** [comment]
NOTE: I have written to Winfried, but he's on holiday until next week, so still waiting

**Comment by IsabellaRey** [comment]
REMINDER: when moving this ticket to Review Complete please add another ticket to finish off converting the Lakeshore336 OPI, from the branch of this ticket: not all screens have been converted, and there may be things in the converted widgets that need adjusting by following the guidelines in the template OPI (for sure things like pointing at the correct fonts and colours)

**Comment by IsabellaRey** [comment]
I am moving this ticket to Review again: as we haven't had feedback from Winfried on time, we decided to go ahead with the new template anyway.

The new Lakeshore 336 OPI is currently on a branch for this ticket.

The new ticket to finish off the Lakeshore 336 OPI is ISISComputingGroup/IBEX#1758
