### ISSUE TITLE
Dataweb: Hide hidden blocks and order groups

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1502]
The hidden blocks need to be hidden!
The "None" group should be labelled "Other" and appear last in the list of groups

**Comment by KathrynBaker** [comment]
Current behaviour for SECI dataweb is that there is a button to press to show the hidden blocks, have we discussed the removal of this with our users? If not, then we should maintain current functionality. Hidden blocks are not on the blocks archiver page (or they weren't), but were on a separate page (dataweb).

**Comment by kjwoodsISIS** [comment]
Split into two separate tickets: #1504 and #1505

**Comment by mattclarke** [comment]
Nobody said anything about removing any functionality

**Comment by mattclarke** [comment]
Closed as split into two tickets
