### ISSUE TITLE
Danfysik OPI: make calibrated and uncalibrated versions

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1503]
In the Danfysik IOC, depending on the CALIBRATED macro, the calibrated.db file is loaded or not. This means that any PV that has to do with FIELD is not loaded if the ioc is not calibrated, and so it shows as disconnected in the OPI. In addition to this, CURR:SP should be shown if the system isn't calibrated, otherwise there is no way to set the current (in the calibrated case it would come from FIELD)

The OPI should be reworked to have two versions: one for the calibrated case, and one for the non-calibrated case.

The two OPI versions could be:
If uncalibrated:
Current                                                                                                                SP           RBV
Status (Power)                                                                                  SP           RBV
Interlock                                                                                              RBV
Voltage                                                                                                                RBV 
Polarity (Hide if unipolar – macro’d option in st.cmd)       SP           RBV        

If Calibrated:
Field                                                                                                      SP           RBV        Field Unit             SP           RBV
Status (Power)                                                                                  SP           RBV
Interlock                                                                                              RBV
Current                                                                                                                RBV
Voltage                                                                                                                RBV
Polarity (Hide if unipolar – macro’d option in st.cmd)       SP           RBV        

To decide which version to load, there could be a CALIBRATED PV in the common db file, which takes the same value as the macro. The OPI can use linking containers and have a rule to react to this PV and set the opi file of the linking container.

NOTE: the OPI currently doesn't follow any standardised layout. When doing this ticket, please make it conform to the standardised layout in place (that is the new layout if we have defined it and got the OK from the instrument scientists, otherwise use the old standard layout)

**Comment by IsabellaRey** [comment]
It might be worth doing ISISComputingGroup/IBEX#1621 before this one

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Danfysik for testing help
