### ISSUE TITLE
GUI: Variable column width, IOC macro table [TIMEBOX: 1 day]

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1507]
As a user, I would like to change the width of columns in the IOC macro table in the GUI so I can read longer macro descriptions.

**Comment by kjwoodsISIS** [comment]
A scroll bar might be an acceptable compromise if variable-width columns prove too tricky.

**Comment by kjwoodsISIS** [comment]
Right-justifying the PV name would also help.
