### ISSUE TITLE
IOCs: EPICS_BASE path

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1508]
When creating a new IOC, the EPICS_BASE path in configure/RELEASE appears as C:/INSTRU~3/Apps/EPICS/base/master instead of C:/Instrument/Apps/EPICS/base/master.

This doesn't seem to break anything at the moment, but wouldn't it be better if it was spelled out explicitly?

**Comment by FreddieAkeroyd** [comment]
When you ran makeBaseApp was your working directory C:/INSTRU~3/Apps/EPICS/... or c:/Instrumenmt/Apps/EPICS/... ?

**Comment by John-Holt-Tessella** [comment]
Test this before fixing. Just in makeBaseApp

**Comment by FreddieAkeroyd** [comment]
This will not break anything as the EPICS_BASE path in RELEASE is a default that is never actually used in our case, it will always be superseded by includes further down. The way it works out EPICS_BASE is to find the location of the makeBaseApp  you ran and then strip a few bits from its location, if this file was found by windows searching in your PATH environment variable and PATH has been shortened then the shortening will get propagated too.
