### ISSUE TITLE
IOC: Linkam95 does not send 'T' command first

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1509]
The Linkam T95 manual states that the first command sent to the device must be the 'T' command. At the moment, the way scanning is set up, the command to set the pump mode goes first, and is thus ignored. Please make it so 'T' is the first thing that is sent.

**Comment by KathrynBaker** [comment]
This might need the same solutions as the Danfysik and Genesys PSUs – they actually send a command in the st.cmd before the db files are loaded for very similar reasons.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/70

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/3

**Comment by AdrianPotter** [comment]
Thanks @KathrynBaker  for the input. That would definitely have been a solution. I note that the McLennan also does a similar thing. In the end @IsabellaRey  helped me do it via some PV trickery.
