### ISSUE TITLE
Include new webdashboard in IBEX

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1511]
The web dashboard has been built by Olivia. It should be included as part of IBEX by:
* Adding the required libraries to python install
* Starting the webserver as part of start_inst (note that the work for https://github.com/ISISComputingGroup/IBEX/issues/1382 must be merged before this)

**Comment by AdrianPotter** [comment]
Not that the PR to add `requests` to Python is a prerequisite for #1382

**Comment by AdrianPotter** [comment]
Waiting for #1382 to complete

**Comment by AdrianPotter** [comment]
#1382 completed. Moving back to ready

**Comment by DominicOram** [comment]
The architecture has changed a little so marking as wont fix and adding replacement ticket.
