### ISSUE TITLE
Muon Front End: Need two more Danfysiks

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1512]
I missed the need for DFKPS_10 and DFKPS_11 (two PSUs I thought were on an instrument but which are actually going to be front end). Adding these should be a quick job as the _02+ IOCs use the information in _01 to load everything up now.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/71

**Comment by ThomasLohnert** [comment]
Everything looks good, just missed changing the IOC number for Rampfilelist.

**Comment by AdrianPotter** [comment]
Done
