### ISSUE TITLE
Experimental Database: Should handle missing files without restarting

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1514]
At the moment if there isn't a file in RBNUM the experimental database keeps restarting, it should just go into the waiting state and try again in an hour, or when asked to.

**Comment by KathrynBaker** [comment]
Probably worth fixing with #1420

**Comment by AdrianPotter** [comment]
Review #1420 first.

https://github.com/ISISComputingGroup/EPICS-ExperimentalDatabase/pull/6

**Comment by AdrianPotter** [comment]
To test, run main.py in the experimental database and verify that it starts correctly without a file (which will probably be the case on your local machine). Then try and set the file with the "F" command and check that it responds correctly.

To make it easier, you may want to reduce the sleep time in do_work from 3600 to something a bit more regular.
