### ISSUE TITLE
Database Server: Refactor to reduce the number of connections needed

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1515]
In database_server.py there are a number of queries related to interesting PVs active PVs and IOC pvs, which causes a large number of connections to be opened. IT should be possible to refactor the code to open one connection do the work and then close it, or to filter the information in python as part of the dataabse server rather than using SQL queries.

Check the Experimental Details Database isn't doing anything silly either.

**Comment by KathrynBaker** [comment]
Increased to 3 to allow for more thorough regression testing

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/72

**Comment by AdrianPotter** [comment]
Caused EPICS to fail. Please review:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/73
