### ISSUE TITLE
Database Server: Quick fix to solve the number of connections issue

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1516]
Just go and comment a line out,

**Comment by AdrianPotter** [comment]
My tool of choice for monitoring TCP connections:

https://technet.microsoft.com/en-us/sysinternals/tcpview.aspx

Note PR is:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/70

I can confirm that the rate of creation of TCP sockets is greatly diminished after the change. Just checking functional operation for negative side effects
