### ISSUE TITLE
System Tests: misleading names

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1522]
The system tests MultipleSynopticsCanBeSimultaneouslyDeleted and MultipleConfigsCanBeSimultaneouslyDeleted only check that synoptics/configs can be deleted one at the time, not simultaneously.

Check with the author of the tests what the original intent was and either rename the tests or change them to do what they say they do.

While doing this ticket, please also check the tests AddMultipleBlocksToMultipleGroups and AddMultipleBlocksToOneGroup: blocks are added one at the time. Though these tests don't say "simultaneously" it may be worth double-checking what the original intention was (and rename the tests with OneByOne or so)

**Comment by Tom-Willemsen** [comment]
Refers to rcptt tests which are no longer in use.
