### ISSUE TITLE
IOC: Eurotherm temperature set point can be negative

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1523]
Eurotherm temperature set points are measured in Kelvin yet accept negative input. This seems odd

**Comment by kjwoodsISIS** [comment]
Yes, it does seem odd.  However, sometimes people use negative values to signal some kind of special input (no, I wouldn't do it that way either ...).  So, it is worth checking if there is a particular reason for accepting negative input values.

**Comment by KathrynBaker** [comment]
Eurotherms aren’t always used in Kelvin, sometimes they are used in Celsius, and sometimes they are used as process control other than temperature. Typically, yes it is Kelvin, but not always.

Regards,

**Comment by kjwoodsISIS** [comment]
Discussed at Sprint pre-Planning meeting on 01-09-2016.  Agreed that this is not a bug - when units are something other than Kelvin, negative values may be required.
