### ISSUE TITLE
Emulators: write a simple emulator in Plankton framework

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1524]
The aim of this ticket is to write our first emulator using the Plankton framework, so we can then use it as the template for future emulators.

The device being emulated in this ticket is the cryo valve, which is very simple. Use as an example the emulator for the Linkam 95 which was written by Michael Hart (Adrian has the code).

As part of this ticket:
- make sure that we can pass the port number into the emulator
- update the documentation to cover this framework. The documentation should make it clear that this works only for stream device IOCs

**Comment by IsabellaRey** [comment]
See also comments on ISISComputingGroup/IBEX#1526 for link on latest emulator code

**Comment by IsabellaRey** [comment]
This is the link to Plankton v1.0:   https://github.com/DMSC-Instrument-Data/plankton/releases/tag/v1.0

**Comment by IsabellaRey** [comment]
ISISComputingGroup/IBEX#1526 and ISISComputingGroup/IBEX#1528 can be reviewed at the same time as this one

**Comment by AdrianPotter** [comment]
This ticket just needs #1734 to be reviewed and merged. Then my request on:

https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/4

has been fulfilled, it can be merged, and this ticket closed

**Comment by AdrianPotter** [comment]
#1734 has been reviewed and closed
