### ISSUE TITLE
Update script generator backend

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1525]
The script generator backend is currently just an example. It contains a table with a few columns, and an example of data-binding below it. With this complete, I am now focusing on implementing the real thing that will link with this frontend design: 

![mockup](https://cloud.githubusercontent.com/assets/14293717/18249080/0704e86e-7374-11e6-88b2-193f51b54c32.png)

![simplified uml](https://cloud.githubusercontent.com/assets/14293717/18341224/eda03e80-75a0-11e6-9ef9-7f2dd2a1cfa2.png)

**Comment by kjwoodsISIS** [comment]
Is the "planned design" documented somewhere?  If so, please link it to this ticket.

**Comment by simonfernandes** [comment]
My tickets have been far too broad and vague so far. Having spoken to Dom, the plan is draw a line in the sand and merge this ticket in (containing everything the previous two unmerged tickets do) and write more specific, descriptive tickets going forward. 

I will add a UML diagram to this ticket shortly so that it is clear what I have been working towards.

**Comment by kjwoodsISIS** [comment]
I think you should write tickets that define the functionality you are going to provide to the user.  There is a standard technique for doing this - user stories.  I think you will find that adopting such a technique will allow you create much more relevant tickets that you can break down into "do-able" chunks.  Come an have a word and I will show you how to write a user story.

**Comment by simonfernandes** [comment]
Note:

This ticket includes everything in #1495 and #1461. 

Also fixes #1560 and #1562.
