### ISSUE TITLE
Emulators: can IOC talk to multiple ports?

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1527]
This ticket should answer the following question:
can an IOC talk to more than one port at once?

It has been proposed that an IOC in device simulation mode could have a string PV to send the backdoor commands to the emulator, so we don't need to pass the backdoor port number out of the IOC. The feasibility of this depends on the outcome of the question for this ticket.

This ticket may require setting up an IOC to try and talk to two different emulators (or a single emulator that can listen on two ports)

**Comment by KathrynBaker** [comment]
The answer to the first question will be yes – we just give it a different port name. We already do this with COM ports in things like SDTEST, so I doubt the IP will be that different.

**Comment by FreddieAkeroyd** [comment]
An IOC can talk to multiple IP or TCP ports, it could generate two free port numbers for normal and backdoor passing both to the emulator, or it could use a PV (but the pv would probably be bound to a different TCP port too)

**Comment by DominicOram** [comment]
Closing as the underlying issue (how to send backdoor commands when testing IOCs) has been solved using the IOCTestingFramework
