### ISSUE TITLE
Emulators: launch and stop from IOC

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1529]
As a developer, I would like an IOC to be able to launch its own emulator in the st.cmd file.

The IOC could launch a wrapper script to do this. Make sure the wrapper script can pass a port number to the emulator and return this port number to the IOC. Generating the port number in the wrapper is for another ticket

If emulators have a backdoor port different from the main one, the wrapper should take care of that too.

We should also verify what happens to the emulator when the IOC is stopped. If it doesn't die with the IOC, we should make sure it somehow gets killed.

You can use the cryo valve IOC and emulator

**Comment by IsabellaRey** [comment]
See also comment by @MikeHart85 in ISISComputingGroup/IBEX#1530

**Comment by IsabellaRey** [comment]
NOTE: in plankton, the backdoor is on a different port than the main one.
The plankton emulator can be killed by calling the control.py script with the stop argument (see docs for details)

**Comment by Tom-Willemsen** [comment]
obsolete
