### ISSUE TITLE
Emulator: wrapper to generate port number

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1530]
The wrapper used by the IOC to launch the emulator should take care of finding a free port in the system that the emulator can use (and a backdoor port too, if it is different from the main one)

**Comment by MikeHart85** [comment]
We started developing a similar wrapper to launch docker based simulations at the ESS called [zoo](https://github.com/DMSC-Instrument-Data/zoo). 

We haven't tackled the problem of determining what port or IP the simulation is running on yet (the focus was more combining multiple simulation frameworks into one package with a common interface), but you may get some ideas from it.

**Comment by FreddieAkeroyd** [comment]
There is also an example python command to return free ports in   utils/free_ports.py

**Comment by mattclarke** [comment]
Freddie has done the work for this, and I have reviewed it - I have just added it to a JULABO as an example of usage, so somebody needs to review that PR.

**Comment by mattclarke** [comment]
Added to release notes
