### ISSUE TITLE
Setup simple IOC unit tests

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1531]
The aim of this ticket is to set up a way of running IOC unit tests that can be used as a template/framework for future IOCs.

Use the cryo valve IOC and its emulator to write some simple unit tests for the cryo valve, ideally using also the backdoor functionality, and document the process in the development wiki.

Note there are already some helper classes (e.g. to wrap an IOC) defined in support/DeviceEmulator/master/test_framewok, which were provided by CLF. See if any of this can be reused. NOTE: these files use pyepics to read/write PVs, and launch IOCs using procserv, but we may decide to do things differently.

If do end up having helper classes, make sure they are unit tested too.

We should also discuss where the framework files should be stored. Same for the IOC unit tests.

**Comment by IsabellaRey** [comment]
This ticket is related to ISISComputingGroup/IBEX#1419

**Comment by DominicOram** [comment]
Closing as solved by the IOCTestingFramework
