### ISSUE TITLE
IRIS: DAE Testing

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1532]
As a support person, I want to perform some tests on the IRIS DAE before the next cycle (2016/03, starting 13th September 2016).  This will also be an opportunity to install EPICS on NDXIRIS.

**Comment by AdrianPotter** [comment]
The 13th September cycle is now 2 weeks in, and we've installed and test IBEX. Are we still intending to do any testing? Has it been done? Can we still do it if it's needed given the cycle has started?
