### ISSUE TITLE
IRIS: Create Configs

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1533]
As a support person, I want to create some configs for IRIS, so that I can confirm that IBEX will drive IRIS satisfactorily.

### Acceptance Criteria
1. The new configs should be based on existing SECI configs for IRIS
2. The new configs should be trialled on NDXIRISTEST

**Comment by AdrianPotter** [comment]
I've created a replica of TLCCR_new on NDXIRIS

**Comment by John-Holt-Tessella** [comment]
On IRIS and Ian is happy.
