### ISSUE TITLE
IRIS: Create Synoptics

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1534]
As a support person, I want to create some synoptics for IRIS, so that I can confirm that they represent the instrument satisfactorily.

### Acceptance Criteria
1. The new configs should be trialled on NDXIRISTEST

### Notes
1. IRIS is not a complex instrument - it might not need more than one synoptic.

**Comment by AdrianPotter** [comment]
I've created a synoptic for TLCCR_new on NDXIRIS. This can be further customised by Ian when we get to training

**Comment by John-Holt-Tessella** [comment]
On IRIS and Iain is happy.
