### ISSUE TITLE
IRIS: Training for IRIS scientists

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1536]
As a support person, I want to arrange a training session for IRIS scientists, so that I can train then in how to use IBEX.

### Acceptance Criteria
1. Arrange a date for training to take place (w/c 12th Sept or w/c 19th Sept.)
1. Train scientists in using IBEX, especially creating configs & synoptics
1. Train scientists in writing genie_python scripts

### Notes
1. The IBEX User manual is available to scientists here: http://shadow.nd.rl.ac.uk/ibex_user_manual/Home

**Comment by AdrianPotter** [comment]
Scheduled for Friday 16th September
