### ISSUE TITLE
User Manual: FAQ

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1539]
As a support person, I would like to enhance the FAQ section of the User Manual, so that users can check it for answers to their most common questions.
### Acceptance Criteria
1.  Additional question & answers added to the existing FAQ section of the User Manual.
### Notes
1. Many questions asked about SECI might equally apply to IBEX.  We should re-cycle any appropriate SECI questions.
2. The User Manual can be edited from:
   1. https://github.com/ISISComputingGroup/ibex_user_manual/wiki or
   2. http://shadow.nd.rl.ac.uk/ibex_user_manual/Home
3. Please Note: the User manual is written in reStructuredText (not Markdown).

**Comment by John-Holt-Tessella** [comment]
As part of #1581?

**Comment by kjwoodsISIS** [comment]
No.  This ticket is about a FAQ for users (i.e. scientists).
#1581 relates to "Support Training" - training people who provide support to the scientists (i.e. us).

**Comment by John-Holt-Tessella** [comment]
During the support training we will probably cover common questions that scientist ask so these should be captured.

**Comment by kjwoodsISIS** [comment]
Just add Q&A when the crop up.
