### ISSUE TITLE
GUI: DAE Periods tab layout

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1541]
Modify layout of the "Periods"-tab in the DAE experiment setup to match that of the "Time Channels"-tab - that is, change the content of the window depending on whether the setup mode is a) loading from file or b) entering parameters manually, only showing relevant settings in each case.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/319 contains changes for both this ticket and https://github.com/ISISComputingGroup/IBEX/issues/1551 (made a mess by branching off but not switching) so these need to be reviewed together

**Comment by ThomasLohnert** [comment]
Added system test: https://github.com/ISISComputingGroup/ibex_system_tests/pull/29

**Comment by IsabellaRey** [comment]
Moving into rework at the same time as #1551 
See pull request for details
