### ISSUE TITLE
OPIs: adjust linking containers to motor opi

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1545]
Following ISISComputingGroup/IBEX#1100  mymotor.opi has become a little larger.

This means that it is scaled down in OPIs that are using it in linking containers.

This ticket is to re-adjust the size and/or properties of the linking containers of the OPIs using mymotor.opi so they look good again

**Comment by IsabellaRey** [comment]
NOTE: the sample_changer.opi and linear_sample_changer.opi have a floating label "Racks:" on top of the linking containers of the motors. This label is invisible, with no rules, no scripts, and it doesn't appear to be used anywhere else. So I am deleting it as part of this ticket.

**Comment by AdrianPotter** [comment]
Fixes #1579 too?
