### ISSUE TITLE
NICOS: Add ZeroMQ dependency into GUI

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1548]
As of #1547 the NICOS proxy will use ZeroMQ to connect to any clients. A library for doing this should be installed into the GUI. This must be included in:
* The P2 site
* The maven build

**Comment by John-Holt-Tessella** [comment]
This is probably active MQ

**Comment by DominicOram** [comment]
Yes, as I've gone with an active MQ solution this ticket is unnecessary. I will therefore close it.
