### ISSUE TITLE
GUI: Add current/new labels to DAE table selection

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1551]
The purpose of the readback label and combobox used to display / change the currently selected DAE table(s) may not be clear to the user.

Convey their purpose more clearly, e.g. by adding a "current" label to the readbacks and a "new" or "change" label to the comboboxes.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/319 contains changes for both this ticket and https://github.com/ISISComputingGroup/IBEX/issues/1541 (made a mess by branching off but not switching) so these need to be reviewed together

**Comment by DominicOram** [comment]
Moving into rework as changes need to be made on #1541

**Comment by IsabellaRey** [comment]
Moving into rework at the same time as #1541 
See pull request for details
