### ISSUE TITLE
LARMOR: Upgrade IBEX on NDXLARMOR

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1553]
As a developer, I want to install a new version of IBEX on NDXLARMOR ahead of the new cycle (13th Sept 2016), so that I have plenty of time to test it with the equipment on LARMOR and to resolve any problems.

#### Acceptance Criteria
1. New version of IBEX installed on NDXLARMOR 
1. Confirmation that IBEX is working correctly on NDXLARMOR. (I should be able to control equipment on LARMOR).

#### Notes
1. Consult with Rob Dalgliesh before upgrading.

**Comment by John-Holt-Tessella** [comment]
Sent email to Rob about upgrade, waiting for reply:
```
Hi Rob,

CC Freddie, Kevin

Just to let you know that the upgrade of IBEX is now complete, it is now on version 2.1.0. I have not tested any of the connection to IOCs apart from the ones running and I have not tested setting anything on those IOCs because I didn’t want to break anything. The upgrade was smooth so I don’t expect any problems. There are a couple of issues that I should confirm with you and sort out for the next time we upgrade the system:

1.	I upgrade all the calibration files to now sit in C:\Instrument\Settings\config\common but I found some in C:\Instrument\Settings\calib\sensors which we don’t have in our main branch. Do you recognise and want to keep any of the following files:

16/10/2013  10:24               506 Instructions for formatting files.txt
12/03/2012  15:11           181,780 K.tbl
19/02/2014  14:39           129,239 linear E254.tbl
20/02/2014  11:30                23 None (2).txt

19/02/2014  14:44           128,441 spline E254.tbl
25/02/2013  17:23             2,934 TBT.csv

25/02/2013  17:33             2,894 TBT_Test.csv

23/06/2015  14:41            10,592 vssver.scc
12/03/2012  15:11             2,628 W5.txt

2.	The Eurotherm now has a variable number instruments connected to a port (original it was always three) to set the number you need to set the address for each eurotherm running. I have done this in your globals.txt which now contains the following (added just the lines with ADDR) could you check that the eurotherm is as you expect:
EUROTHERM_01__PORT=COM21
EUROTHERM_01__ADDR_1=1
EUROTHERM_01__ADDR_2=2
EUROTHERM_01__ADDR_3=3
EUROTHERM_02__PORT=COM22
EUROTHERM_02__ADDR_1=1
EUROTHERM_02__ADDR_2=2
EUROTHERM_02__ADDR_3=3

3.	The DAE period files and channel files now belong in slightly different directories. I couldn’t find any of these so I haven’t moved them. The normal table files are now in C:\Instrument\Settings\config\NDXLARMOR\configurations\tables.

4.	IBEX is showing an error connecting to the FINS PLC is this because it is switched off or is this a genuine error which we need to look at?

5.	The chopper IOC should now check the number of chopper connected to it automatically. I didn’t want to start this IOC could you do this and check that it works for you?

Thank you for your help with this. If you see any unusual behaviour or have any problems please let us know.

Cheers,

John
```

**Comment by John-Holt-Tessella** [comment]
Do I need to send change list to Rob.

**Comment by John-Holt-Tessella** [comment]
[ReleaseNotes.pdf](https://github.com/ISISComputingGroup/IBEX/files/476689/ReleaseNotes.pdf)

**Comment by John-Holt-Tessella** [comment]
Waiting for reply for Rob:
4. Is fixed

**Comment by ChrisM-S** [comment]
First of all, this does show the value of recording the release details.  It could have been months before we had a disk space problem with accumulating backups and if we can fix the procedure it could also prevent it on another 30 machines in future!

The best place to copy backup files on an instrument to is to:

      C:\data\old\

perhaps to a folder like "ibex_backup" for identification.  As a manual process, it would be helpful if any previous backups could also be removed from here when a new one is added (unless they are still needed).

This means the data will go onto the same partition as the managed instrument data, so although it does potentially eat data space which might be used, the process for finding and recovering space does not require the instrument to be restarted and the VM disk to be re-compacted.  Also, after about 6 months files are cleared off this area automatically so the space will eventually get reclaimed.

**Comment by kjwoodsISIS** [comment]
Moved back to "Review Complete" - issues only get closed at the end of the sprint (it makes it easier to track what was actually completed during the sprint).

**Comment by IsabellaRey** [comment]
Can we capture what Chris said in the Deployment instructions in the Developers wiki?

**Comment by ChrisM-S** [comment]
My apologies, I didn't even realize I'd closed the issue.  I'm too used to clicking "Save and Close" in outlook where the meaning of "close" in the GUI is subtly different!  (weird that it initially says "close issue" which is quite clear but once you've started typing makes it very ambiguous).

**Comment by kjwoodsISIS** [comment]
Chris's suggestions now included the [Deployment](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC) instructions.
