### ISSUE TITLE
Script Generator: Create a SANS script for ZOOM

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1558]
As a ZOOM scientist, I want to create a SANS script, so that I can automate SANS experiments.
#### Relies on:
- [ ] #1559 
- [ ] #1564 
- [ ] #1567 
- [ ] #1565 
- [ ] #1568 
- [ ] #1569
#### Acceptance Criteria
1.  I can create a new, empty script.
2.  I can choose which actions that I want the script to perform.
3.  I can view the script that the system has created.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
