### ISSUE TITLE
Script Generator: Create a new, empty script

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1559]
As a ZOOM scientist, I want to create a new, empty script so that I can create new scripts from a clean sheet.
#### Relies on:
- [ ] #1560 
- [ ] #1562 
- [ ] #1563 
- [ ] #1566 
- [ ] #1570 
#### Acceptance Criteria
1.  When requested, the system creates a new, empty script for me.
2.  On first starting, the system automatically creates a new, empty script.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
