### ISSUE TITLE
Script Generator: On creating a new, empty script

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1560]
As a ZOOM scientist, I want the system to generate a new, empty script with a single row.
#### Acceptance Criteria
1.  When the system creates a new, empty script, it should have a single row.
2.  The single row must consist of a number of columns, as follows:
   - _POSITION_ - The sample's position in the rack. Rack contains a top (T) and bottom row (B), with 20 columns (A to T). A position can range from AT to TB.
   - _TRANS_ - Transmission. Numerical value of the period of time to wait for when collecting TRANS data.
   - _TRANS_WAIT_ - The units of time used with the TRANS value. Can be microamp-hours, seconds, minutes or frames.
   - _SANS_ - Small Angle Neutron Scattering. Numerical value of the period of time to wait for when collecting SANS data.
   - _SAMPLE_NAME_ - The name given to the sample by the user. Alphanumeric values only.
   - _THICKNESS_ - Numerical value for the thickness of the sample.

**Comment by DominicOram** [comment]
Which branch was these completed on?

**Comment by simonfernandes** [comment]
Sorry, forgot to include. This one here: https://github.com/ISISComputingGroup/ibex_gui/pull/318

**Comment by DominicOram** [comment]
There is a new row with the columns mentioned. Can you add the details listed above of what these columns are to some documentation somewhere as in https://github.com/ISISComputingGroup/ibex_gui/pull/332
