### ISSUE TITLE
Script Generator: Provide an estimated script time

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1561]
As a ZOOM scientists I would like to be able to enter information about my script and receive an estimate for how long my script will take.
#### Acceptance Criteria
1. The user can enter information into the estimated times part of the script generator
2. When requested, the user receives an estimated time based on this information
#### Notes
1. Information entered should be validated

**Comment by Tom-Willemsen** [comment]
Re-requested by IRIS

**Comment by ThomasLohnert** [comment]
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/4172. Closing this one as the other ticket has more detail.
