### ISSUE TITLE
Script Generator: Add a new row

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1563]
As a ZOOM scientist, I want to be able to add a new row so that I can write scripts that perform multiple actions.
#### Acceptance Criteria
1.  I can write a value in any column of a row.
2.  In response, the system creates a new, empty row below it.

**Comment by DominicOram** [comment]
Which branch was these completed on?

**Comment by simonfernandes** [comment]
Sorry, forgot to include. This one here: https://github.com/ISISComputingGroup/ibex_gui/pull/318

**Comment by DominicOram** [comment]
Rows are added when all columns are updated with values. Good work
