### ISSUE TITLE
Script Generator: Save a script

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1564]
As a ZOOM scientist, I want to be able to save a script so that I don’t have to repeatedly create the same script.
#### Acceptance Criteria
1.  I can choose to save the current script as a file.
2.  The system prompts me to provide a file name and location.
3.  The system will have an option to save the script as a Python .py file.
4.  No longer applicable
5.  The system saves the script.

**Comment by mattclarke** [comment]
4. The system will have an option to save the script as a CSV file.

Moved to new ticket
