### ISSUE TITLE
Script Generator: Create a meaningful script

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1567]
As a ZOOM scientist I would like the values I enter into the script generator to create a meaningful script based on the same logic as the original SANS script program.
#### Acceptance Criteria
1. Values entered into the new script generator perspective will create the same script as those entered into the original SANS Script program
2. The exact logic for this should be documented: see #1565 for settings logic documentation, see #1560 for documentation on columns

**Comment by simonfernandes** [comment]
Validation needs to be added for the position and period row fields. 

**Period** – Double value
**Position** – A two-character, case insensitive string

**Comment by DominicOram** [comment]
Can you remove the dependency on LocalDate and use something Java 1.7 compatible please? Feel free to do this on another branch.
