### ISSUE TITLE
Script Generator: Send a script to NICOS

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1568]
As a ZOOM scientist, I want to be able to send a script to be scheduled by NICOS.
#### Acceptance Criteria
1.  I can choose to send a script to NICOS, to be started at the next available opportunity, or at a time of my choosing.
2.  In response, the system will add the script to NICOS, to be executed at a desired time or next available opportunity.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
