### ISSUE TITLE
Script Generator: Load a script

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1569]
As a ZOOM scientist, I want to be able to load a script from a file so that I don’t have to type it out again.
#### Acceptance Criteria
1.  I can choose to load a file containing experiment data. Types of file
2.  In response, the system will populate the table with the corresponding data.
#### Notes
1.  The system will accept a file in Excel format.

**Comment by DominicOram** [comment]
This is for the old script generator, no longer relevant so closing it.
