### ISSUE TITLE
Script Generator: Include drop downs in the Script Generator table

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1570]
As a ZOOM scientist I would like to be able to set my SANS/TRANS wait for units from a predefined list of:
- MicroAmp Hours
- Minutes
- Seconds
- Frames
#### Acceptance Criteria
1. The user should be able to select from a drop down of these options in the script generator table.
2. This selection should be reflected in the final script

**Comment by DominicOram** [comment]
Where is the PR for this?

**Comment by simonfernandes** [comment]
Whoops, just added.

**Comment by DominicOram** [comment]
Looks good. Couple of things:
* Remove the Sans/TransEditingSupport as they are now replaced by the anonymous classes
* Remove the ComboCellLabelProvider as it's not used (keep the control one though as it could be useful down the line)
* Fix the checkstyle warnings that have been introduced (http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_build_PRs/462/checkstyleResult/new/)

**Comment by DominicOram** [comment]
Still has some warnings http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_build_PRs/471/checkstyleResult/new/HIGH/
