### ISSUE TITLE
GUI: Block displays "error" in error

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1571]
In the GUI, displaying the value of a field motor record can lead to an error if the relevant field does not have a .SEVR sub-field.

Fix the GUI to avoid this error.  

The underlying cause is probably the alias rules in the BlockServer - but is a fix that needs to be made more carefully.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/320
