### ISSUE TITLE
Blockserver: update alias gateway rules

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1572]
Consider updating the Blockserve alias gateway rules to provide a better fix to #1571.

**Comment by John-Holt-Tessella** [comment]
This might be fixed by #1574 I will check with @FreddieAkeroyd

**Comment by FreddieAkeroyd** [comment]
Yes, I did a proper rather than a quick fix in #1574 so this issue can be closed
