### ISSUE TITLE
IRIS: Motor OPI too small in single_stage

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1579]
In the single_stage OPI there is an embedded motor OPI of fixed width. As the motor OPI has been widened, it has been shrunk to fit in the single_stage OPI and looks a bit weird.

**Comment by IsabellaRey** [comment]
Check if this was fixed by ISISComputingGroup/IBEX#1499

**Comment by AdrianPotter** [comment]
Fixed by #1545
