### ISSUE TITLE
IOC: Too many error messages from LKSH218 in RECSIM

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1580]
When the Lakeshore 218 is started in RECSIM mode, a lot of errors are reported in the IOC log. Although the GUI should be able to cope with that, it can't at the moment and is messy. Please could the IOC be tidied up so that in RECSIM mode it doesn't flood the log

**Comment by GRyall** [comment]
This related to a much older version of the GUI and is unlikely to remain an issue. Given it relates to RECSIM mode, even of the issue remains it will not occur on a beam line. Closing ticket, we can reopen it if the behaviour is seen again or still poses an issue.
