### ISSUE TITLE
Add IRIS to instrument list

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1585]
Add IRIS to CS:INSTLIST and make sure it appears as an available instrument on the GUI

**Comment by IsabellaRey** [comment]
To reviewer: simply check that you can see IRIS in the list of instruments in the GUI

**Comment by AdrianPotter** [comment]
Definitely in PV. I've seen it in my inst list today. I can't anymore though, it's blank. Covered under ticket #1183
