### ISSUE TITLE
GUI usability: DAE tables

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1588]
Steps to reproduce:
1. Set a DAE wiring table from the GUI DAE perspective
2. Change the table from genie python. Back in the GUI DAE perspective, the current table is updated to the one set through genie
3. The table in the drop-down is the last one previously selected from the GUI, which is fine. Click Apply Changes WITHOUT re-selecting a table in the drop-down: the table is not updated until a selection is made

This may or may not be what we want. Maybe it's fine as it waits for an explicit choice from the user, but maybe it's a usability issue. Can we discuss?

**Comment by KathrynBaker** [comment]
As we've not discussed this yet, closing
