### ISSUE TITLE
SERVER: Macros not written quickly enough

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1595]
We saw that if we changed a macro in a configuration with an autostarting IOC this was not always picked up the first time it restarted, I am unsure if this was because the file wasn't written quickly enough or what.

**Comment by AdrianPotter** [comment]
Check against #1614

**Comment by John-Holt-Tessella** [comment]
Might be fixed by #1500

**Comment by AdrianPotter** [comment]
2 PRs: Inst_servers and GUI

**Comment by mattclarke** [comment]
Just needs confirmation that behaviour is covered by manual tests

**Comment by AdrianPotter** [comment]
Updated test 15-9. Added test 15-11
