### ISSUE TITLE
GUI: Synoptic editor update target details

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1602]
When I try and change the component type for an existing synoptic component, the component target details aren't auto-updated

**Comment by AdrianPotter** [comment]
Putting back in backlog as this is evidently more than a 0. Please see PR:

https://github.com/ISISComputingGroup/ibex_gui/pull/373

for a commentary

**Comment by KathrynBaker** [comment]
Not reproducable 8 years later
