### ISSUE TITLE
GUI: OPI update too slow

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1606]
When an OPI is open, but the IOC is stopped, when the IOC starts, the OPI does not appear connected in a reasonable time, even on refresh: it has to be closed and opened again. This isn't very nice for the user

**Comment by AdrianPotter** [comment]
Believe fixed with #1614

**Comment by John-Holt-Tessella** [comment]
Mentioned by Ian from IRIS at Sprint review

**Comment by kjwoodsISIS** [comment]
Check with a CAMonitor command first.

**Comment by FreddieAkeroyd** [comment]
Check if a camonitor on the PV recovers quickly, when an IOC starts it send out beacon packets and this is just a check that there isn't an issue with this setup. If camonitor recovers but the OPI doesn't then this is an issue with either the OPI refresh, pvmanager or even the underlying CAJ

**Comment by kjwoodsISIS** [comment]
Create a ticket to check behaviour of CAmonitor first and then work upwards.

**Comment by mattclarke** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/1971

**Comment by mattclarke** [comment]
Closed as superseded by https://github.com/ISISComputingGroup/IBEX/issues/2162
