### ISSUE TITLE
LARMOR: Remove SVN, Install Git

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1610]
During the upgrade of LARMOR prior to cycle 2016/03, we noticed that LARMOR is still running SVN and that Git has never been installed.  We should correct this.
#### Acceptance Criteria
1. Check that LARMOR has no critical files stored in its SVN repository that would not be replaced by corresponding files from a Git repository.
2. Make a backup of LARMOR's SVN repository (in case you need to roll back)
3. Uninstall SVN (including TortoiseSVN if it is installed)
4. Install Git (and TortoiseGit, if required).
#### Notes
1. Check with Rob Dalgliesh when it would be convenient to do this work.

**Comment by John-Holt-Tessella** [comment]
Add to release notes

**Comment by AdrianPotter** [comment]
I'm just emailing Rob to check when a good time to do this is...

**Comment by John-Holt-Tessella** [comment]
Did not uninstall SVN this is needed for SECI. Otherwise done.

NB We had a problem deleting a file because it was open on another instrument. I will ad to trouble shooting
