### ISSUE TITLE
GUI: error message on duplicate synoptic names

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1611]
Usability issue in the synoptic editor:

duplicate component names cause an error message "Component names must be unique" to appear under the "Component Details" title. It would be useful to state in the message which component names are being repeated, in case you have many components and you're not pointing at one that is duplicate

NOTE this was picked up while installing release 2.1.0 on LARMOR: an existing synoptic had components with duplicate names (don't know how it got saved, but it did), and it wasn't clear which name was duplicated.

**Comment by mattclarke** [comment]
The error message just shows the name of the component you are on, even if it is not a duplicate.
"component name" and "component name      " are considered not to be unique.

**Comment by DominicOram** [comment]
Awaiting merge of https://github.com/ISISComputingGroup/ibex_gui/pull/403
