### ISSUE TITLE
Other: Create IBEX landing page

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1619]
As a user I would like to visit an external IBEX landing page from which I can access all the links for various documentation etc. 

It is possible to create these in git hub uses pages. In fact Freddie and John tried this from the IBEX repository. See http://isiscomputinggroup.github.io/IBEX/ which is generated from doc folder in that repository. It also allows CNAME for that hosting.

**Comment by FreddieAkeroyd** [comment]
It would be possible to have e.g. http://computing.isis.stfc.ac.uk/IBEX map via a CNAME to  http://isiscomputinggroup.github.io/IBEX/ - I'm not sure what to call the "computing" bit officially though. I guess the question is GitHub pages (i.e. static html) or a wiki, static pages published from another tool would ultimately look prettier.

**Comment by kjwoodsISIS** [comment]
I think we should avoid people having to use GitHub to see our documentation.  

Why do we need to map to GitHub?  We already generate http://shadow.nd.rl.ac.uk/ibex_user_manual/Home from the "source" on GitHub.  Why don't we just have  http://computing.isis.stfc.ac.uk/IBEX link to the local copies of the documentation generated from the "source" on GitHub?

**Comment by FreddieAkeroyd** [comment]
That's true, I had forgotten that and it avoids all the GitHub issues. However I've just had a chat with Tom and what we really should have is an IBEX landing page at  http://www.isis.stfc.ac.uk/groups/computing/  unfortunately this means we will have to use the Rhythmyx content management system...

**Comment by kjwoodsISIS** [comment]
Does this mean that the landing page (and only the landing page) has to be written with Rhythmyx?  Or is there an expectation that all the documentation has to be written with Rhythmyx?  
I am sure we can live with using Rhythmyx to write a landing page with static links to our documentation generated from GitHub.  From what I hear about Rhythmyx, writing all the documentation in Rhythmyx would be a severe handicap...

**Comment by KathrynBaker** [comment]
We are fine to have static links from a rhythmyx page, and already do so for Open Genie and Mantid. At least that is the opinion of the computing group web editor (me)

Regards,
Kathryn
