### ISSUE TITLE
IRIS: Test PDR 2000

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1620]
MKS PDR 2000 needs explicitly testing with an actual device as this hasn't been possible during development. Some configuration changes (e.g. terminators in the protocol) are expected.

**Comment by John-Holt-Tessella** [comment]
Impeded until equipment is available.

**Comment by AdrianPotter** [comment]
According to the latest information from Ian/David, the PDR2000 will not be used on Iris, at least not in a way that requires and IOC through Ibex. I've added some comments to the IOC to note its untested state
