### ISSUE TITLE
Numerous Instrument List Changes

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1622]
This ticket encompasses:
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1109
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1110
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1222
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1479
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1183
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1705
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1706
- [x] https://github.com/ISISComputingGroup/IBEX/issues/1510

It is a placeholder to describe the overall method that will (hopefully) fix all of these.

The fist ticket to do is https://github.com/ISISComputingGroup/IBEX/issues/1110, which should save three things when the GUI is closed:
- User-friendly instrument name e.g. LARMOR
- Instrument PC name e.g. NDXLARMOR
- Instrument PV prefix e.g. IN:LARMOR

This will remove the need for the 20 second wait referenced in https://github.com/ISISComputingGroup/IBEX/issues/1222, which was originally there to make sure the instrument list was gathered before starting the GUI. If the PV still isn't connected when the switch dialog is opened a blank list should be displayed rather than waiting for 20 seconds (confirm this by connecting the instrument list to a dummy PV, killing the associated IOC and opening the window)

The CS:INSTLIST PV can then be updated to provide all of the information that is saved above, this will fix https://github.com/ISISComputingGroup/IBEX/issues/1479 where there is a mildly different PC name. It will also allow a flexible decoupling of all these parameters by removing the logic from the UI. Keep in mind when doing this that changes in the CS:INSTLIST should be backwards compatible with old GUIs. 

Finally, all of this messing might fix https://github.com/ISISComputingGroup/IBEX/issues/1183.

**Comment by IsabellaRey** [comment]
NOTE: we should add ticket #1109  to this list, because it's what's causing the "ND" restriction on custom instrument names.

**Comment by John-Holt-Tessella** [comment]
Consider doing #1705 at the same time
