### ISSUE TITLE
Danfysik 8800: Need to tell it to start to change the current

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1623]
In yet another oddity for the Danfysik 8800 model, there is an extra step on setting the current, in that it has to be explicitly told to start. This is dome by sending a TS command. To implement this update the danfysik 8800 proto file to include:

```
start {
    out "TS";
}
```

Add the following to the 8800 setup db file:

```
record(bo, "$(P)START")
{
    field(DESC, "Reset")
    field(DTYP, "stream")
    field(OUT, "@dfkps.proto start $(port) 0")
    field(ZNAM, "Start")
    field(ONAM, "Start")
    field(SIML, "$(P)SIM")
    field(SIOL, "$(P)SIM:START")
    field(SDIS, "$(P)DISABLE")
}

record(bo, "$(P)SIM:START"){
    field(DTYP, "Soft Channel")
}
```

Add a forward link to the new record from RAW:SP for the 8800 (in the status db)

**Comment by KathrynBaker** [comment]
Not easy to test, but is in use on NDEMUONFE.

Pull requests:
https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/4
https://github.com/ISISComputingGroup/EPICS-ioc/pull/79

**Comment by John-Holt-Tessella** [comment]
Forward link will be treated in a separate ticket
