### ISSUE TITLE
genie_python: Disable accidental setting genie keywords

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1625]
As a user if I make a mistake I do not want to be able to overwrite genie commands with my own. E.g. cshow=3 or g.cshow=3 or g=3 or inst=3

```
>>> g.cshow("Block1")  # Fine

>>> g = 5

>>> g.cshow("Block1")  # BOOM!
```

See http://code.activestate.com/recipes/65207-constants-in-python/ which might help with `g.` and `inst.`. If it is not possible add a command to enable a user to programatically reimport commands. Add documentation for this.

**Comment by mattclarke** [comment]
I think using namespaces such as g and inst are a good thing.
I am 99% certain we cannot do anything about ```g=1``` without hacking Python, and I am not sure we want to go down that road.

**Comment by GRyall** [comment]
No further request and a clear argument against. Closing as not planned.
