### ISSUE TITLE
GUI: Wider fields (frames & current) on Dashboard

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1632]
As a scientist, I want the fields used to display the number of frames and the current to be wider, so that the value does not get truncated.

#### Acceptance Criteria
1. The Good/Raw Frames field must be capable of displaying integer values of up to 8 + 8 digits, without truncation.
1. The Current/Total field must be capable of displaying decimal values up to 7 + 7 digits (including the decimal point), without truncation.
   1. The format of the Current/Total fields must be 9999.99 (to allow for currents over 1000uA).

#### Notes
1. A frame field of 8 digits allows values up to 99,999,999 (N.B.  do not include the commas in the dashboard display itself).
1. **Example:** Good/Raw Frames: 34613592/37196925
1. **Example:** Current/Total:    25.83/1015.79

**Comment by IsabellaRey** [comment]
#1648 fixed in the same pull request as this ticket
