### ISSUE TITLE
GUI hangs on LARMOR

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1633]
The client hung on LARMOR a couple of times last night - Rob is wondering if it is due to the Lakeshore and 3D magnet OPI that he has recently started using

**Comment by John-Holt-Tessella** [comment]
Might be running for a couple of hours with a graph. Can you add more detail @FreddieAkeroyd ?

**Comment by John-Holt-Tessella** [comment]
It is not clear what the problem is try the graphs in for this ticket, if ok then mark as wont fixed

**Comment by John-Holt-Tessella** [comment]
Write ticket if find bug

**Comment by John-Holt-Tessella** [comment]
See #1634

**Comment by John-Holt-Tessella** [comment]
Didn't crash running as is on iris test. Going to have it actually open and on my desktop and see if this crashes it

**Comment by John-Holt-Tessella** [comment]
This does not seem to be a problem. I have left it open for several days on NDXIRISTEST.  Is this still happening for Rob? I will try an OPI open for a while next and see if that is bringing the system down.
Impeded until @FreddieAkeroyd can ask Rob if it is still happening or OPI time kills us.
Maybe a different Java version or memory issue if it is still happening.

**Comment by kjwoodsISIS** [comment]
No longer impeded.  Ask Rob if issue still occurs.  tell Rob we've made changes that might have fixed it.

**Comment by AdrianPotter** [comment]
No further reports of issues in a year. Closing
