### ISSUE TITLE
Log Plotter Issues on LARMOR

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1634]
Rob has found that leaving a block plotting in the log plotter for a few hours hangs/crashes the client, is there a buffer size issue?

**Comment by John-Holt-Tessella** [comment]
Related to #1633

**Comment by John-Holt-Tessella** [comment]
I can find no evidence of this on NDXIRISTEST. 
Is it possible that this is caused by a log message problem? I will try just conencting NDXIRISTEST to larmor and see if it crashes naturally.

**Comment by John-Holt-Tessella** [comment]
Seems to work. I will leave #1633 as impeded and ask Rob after we deploy new client with log plotter fix
