### ISSUE TITLE
Default logging of new blocks

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1635]
Rob was caught out by the default logging for new blocks in "no log", he believes this is a change from previously. The default logging choice should be enabled and "every 30 seconds"

**Comment by kjwoodsISIS** [comment]
The current behaviour (i.e. "no log") is described in the user manual.  When this change is implemented, the user manual needs to be updated (see http://shadow.nd.rl.ac.uk/ibex_user_manual/CreateandManageConfigurations#blocks-tab).
