### ISSUE TITLE
IBEX Client is stopped by the Window Firewall

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#1638]
Installing the IBEX client on a clean machine with firewall enabled (not an unlikely scenario) is a very unexciting experience.  It would be good if IBEX could detect this and either correct the firewall to allow access to itself or its portsor at least give a message requesting that it is allowed through.  The symptoms are very much like a failing and infinitely slow instrument list on a "Switch Instrument".
## Notes:

1) If the client can trigger the normal windows "application needs to open the firewall port" message, this would probably do the job.
2) It would also be helpful if it didn't give up trying and flagged with it's own message that it had no access through the firewall.
3) It would be reasonable to expect the user or their system administrator to sort out the firewall issue and not expect IBEX to do this.  Just furnishing sufficient information to allow someone to do this would be ideal.

**Comment by John-Holt-Tessella** [comment]
Test can see instrument list on new instrument. (Add to notes after new release). Check on zoom?

**Comment by kjwoodsISIS** [comment]
Add instructions to the Manual on how to configure your firewall to let IBEX client through.

ISIS plan to install Firewalls site wide.  Check when this is happening.  Can we get IBEX packets included in the policy?  Ask FIT.  See ticket XXXX.

**Comment by ChrisM-S** [comment]
The firewall rule needed is shown below, it is important to restrict allowed UDP packets from address of the EPICS Control-SVCS machine  IP address and port as shown below (otherwise the firewall would simply be opened to UDPs from anywhere to anywhere!).  Should we have a fall back machine too in case the main Control-SVCS is down?  This will need to be run as an administrator privileged command or as @kjwoodsISIS commented in a group policy.

`netsh advfirewall firewall add rule name="Control SVCS Machine" dir=in action=allow protocol=UDP remoteip=130.246.51.171 remoteport=5064 profile=any`

**Comment by kjwoodsISIS** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 07 November 2016 12:16
> To: Fielden, Nick (STFC,RAL,ISIS)
> Cc: Moreton-Smith, Christopher (STFC,RAL,ISIS)
> Subject: IBEX and Firewalls at ISIS
> 
> Hi Nick,
>  
> I understand from Chris that ISIS plans to install firewalls on all ISIS machines.
>  
> Such a plan will impact IBEX, because IBEX operates as a client-server system.  We need to have a way to ensure that IBEX clients can get through the firewall to talk to IBEX servers (one (in some cases more than one) IBEX server per instrument; any IBEX client can talk to any IBEX server).  From our perspective, the best way to accomplish this would be to have IBEX included in any site-wide group policy, so that any ISIS PC can be used to run the IBEX client.  Would this be possible?
>  
> Also, in the event that visiting scientists want to run IBEX on their own PCs, it will probably be necessary (in some cases, at least) to provide them with instructions on how to configure their own firewalls.  Are there (or will there be) instructions on how to do this (so that we can refer to them from the IBEX User Manual)?
>  
> Thanks,
>  
> Kevin

**Comment by kjwoodsISIS** [comment]
> Hi Kevin,
> 
> In short, yes, it will certainly be possible to open up whatever holes/exclusions are needed for ISIS operations.  I’ve copied John Good in on this reply so that he’s aware and will discuss with you at the relevant time (he’s managing the project overall).  It will probably be quite a while before we’re ready to put the more “sensitive” machines like instrument servers into it and we’ll be doing it carefully as a phased and tested migration.  Would you have a list of the IBEX client machines?  Are these likely to be people’s desktop PCs and laptops or are they more fixed and controlled?  Like wise it would be useful to have from you or Chris a list of the IBEX servers (which I assume will grow over time).  I’m guessing these may well be the instrument machines?
> 
> John: please see below and discuss with Kevin and Chris in good time while we’re in the planning phase of this project.
> 
> Thanks,
> Nick

**Comment by kjwoodsISIS** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 07 November 2016 14:14
> To: Fielden, Nick (STFC,RAL,ISIS)
> Cc: Moreton-Smith, Christopher (STFC,RAL,ISIS); Good, John (STFC,RAL,ISIS); Shuttle, Anthony (STFC,RAL,ISIS); Nell, Leon (STFC,RAL,ISIS)
> Subject: RE: IBEX and Firewalls at ISIS
> 
> Hi Nick,
> 
> Thanks for this.  We’ll liaise with John when the time comes.
> 
> The IBEX clients will not be fixed and controlled.  For the most part, IBEX clients will be PCs in the instrument cabins and also desktop PCs & laptops.  Scientists can also install the IBEX client on their home PC. 
> 
> The IBEX servers are the instrument control PCs themselves (i.e. the NDX machines).  Servers that are currently running IBEX are NDXLARMOR, NDXIMAT, NDXIRIS and NDEMUONFE.  Over the next two years the rate at which we migrate servers from SECI to IBEX will increase (from, say, 1 or 2 per shutdown, to 3, 4 or even 5, as we get better at doing the migrations).
> 
> Kevin

**Comment by mattclarke** [comment]
Added instructions for the firewall to https://github.com/ISISComputingGroup/ibex_user_manual/wiki/InstallingIBEX
