### ISSUE TITLE
MUONFE: lvDCOM for HIFI CryoMag VI

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1639]
James would like to be able to talk to the CryoMag VI on NDXHIFI from MUONFE.

C:\LabVIEW Modules\Instruments\HIFI\Cryomag\Client Side\HIFI - Cryomag.llb\HIFI - Cryomag - Front Panel.vi

It is best if the IOC runs on NDXHIFI.

**Comment by KathrynBaker** [comment]
There's no need to do this, the Cryomag is already channel access from the Cryomag server side, more appropriate would be to just alter the access gateway security settings on the cryomagnet to include MUONFE, and add blocks as appropriate, given that we have the ability to have remote blocks...

**Comment by FreddieAkeroyd** [comment]
Possibly superseded by #1695

**Comment by John-Holt-Tessella** [comment]
superseded
