### ISSUE TITLE
MUONFE:lvDCOM for HIFI Jaws VI

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1640]
James would like to be able to talk to the JAWS VI on NDXHIFI from MUONFE.

C:\LabVIEW Modules\Instruments\MUSR\Muon Jaws\Muon Jaws - System Functions.llb\Muon Jaws - System Functions - Front Panel.vi

It is best if the IOC runs on NDXHIFI.

**Comment by FreddieAkeroyd** [comment]
Possibly superseded by #1695
