### ISSUE TITLE
SECI: Start gateway automatically if present

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1641]
It would be useful if SECI could automatically start the CA gateway if present.

This means one less thing to remember for the scientist if he/she has any IOCs on the NDX machine

**Comment by KathrynBaker** [comment]
If you look in the hifi Cryomag server side there are bat files and LabVIEW code which provide a work around to this, it is somewhere else as well but I can't remember where.

**Comment by John-Holt-Tessella** [comment]
superseded
