### ISSUE TITLE
MUONFE: Start lvDCOM IOC automatically

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1642]
It would make the scientists life easier if the VI could automatically start the IOC if it was present.

This needs to be done in such a way that the VI is isolated from any IOC start-up issues

**Comment by KathrynBaker** [comment]
Check out the client side of the hifi cryomagnet, it does this in LabVIEW, but there are some issues when restarting it all, so it could be worth adding the proceed stops to the kill SECI functionality, although we would then have to add the start IOC explicitly to SANS2D if that gets updated as it uses the cut down start_inst option

**Comment by FreddieAkeroyd** [comment]
Possibly superseded by #1695

**Comment by John-Holt-Tessella** [comment]
superseded
