### ISSUE TITLE
Start compiling a list of expected behaviour

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1643]
For development and testing it would be useful to have a document listing what behaviour is expected.
This can guide the developers and be tested against before releases.

For example:
- New blocks should default to being logged.
- Other groups should appear last
- DAE settings can only be changed during SETUP
- cshow and cset should show run-control limits even when not under run-control

**Comment by John-Holt-Tessella** [comment]
Add to testing document

**Comment by AdrianPotter** [comment]
Note ticket #1622. Expected behaviour of cget/cset when connected/disconnected and under/not under run control is a good example of something that should be captured

**Comment by John-Holt-Tessella** [comment]
Add to system testing process!
