### ISSUE TITLE
Eurotherm IOC name

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1644]
The Eurotherm IOC name is EUROTHERM_01, but in the PV prefix it appears as EUROTHERM1. This is a bit confusing, ideally the two should be the same.

**Comment by kjwoodsISIS** [comment]
Schedule for Xmas/New Year shutdown.

**Comment by AdrianPotter** [comment]
A couple of extensions:

- Shorten EUROTHERM name to 8 letters
- Create incremental release 2.2.1
    - Branch from the same point as 2.2.0
    - Make the changes to the Eurotherm
    - Merge in any changes on the 2.2.0 branch
    - Create version 2.2.1 by updating version numbers on 2.2.1 branch
    - Create a pull request for the Eurotherm changes back onto the master branch

**Comment by AdrianPotter** [comment]
The work has been done. As predictable from above, the branching will take a bit of resolution. **Merge conflicts on the branch are expected. These will need resolving during the merge, not on the PR**

- Please review the 2 pull requests for release 2.2.1
- If the reviews are ok, please merge those 2 pull requests
    - Make sure to update the release_2.2.1 release notes
    - Make sure to update the IOC submodule with IOC branch Release_2.2.1 in the Release_2.2.1 branch of the EPICS repo
- You should now be able to create a release 2.2.1 version of EPICS and the client via Jenkins

The work also needs merging into master

- Review the 2 master branch PRs as normal, merge, update the release notes and EPICS submodules
    - Be especially careful not to cause any side effects in the IOC submodule

**Comment by IsabellaRey** [comment]
IOCs and GUI work fine, no problems found.
Just a couple of minor points:

- [ ] spelling of devEurothrm.db and isActiveEurothm.db should be the same in the filename, the Makefile and the st.cmd (EUROTHRM is capitalised in the Makefile and st.cmd - though the IOC runs fine! I'm surprised, I thought the Makefile was case-sensitive, but clearly it isn't!)
- [ ] in the st.cmd files for IOCs 01-06 we can remove the IOCPVPREFIX macro, as now it gets set correctly automatically
- [ ] the release notes should say to also check for autosave sav files - PVs will need renaming there too

**Comment by KathrynBaker** [comment]
Another extension that might be needed - to save pain at a later date, is to shorted the MK3CHOPPER name before the release - as that will be needed on ZOOM, and if we make that change before too much setup on ZOOM is done then we only have to change one instrument, not two - this change is in ticket #1895
