### ISSUE TITLE
Eurotherm: do not send startup setpoint to 0 (root cause)

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1646]
This ticket originates from ISISComputingGroup/IBEX#1630, and was flagged by Ian on IRIS

The root cause seems to be that support/ReadASCII/master/ReadASCIIApp/src/ReadASCII.cpp line 93 sets the setpoint to 0.

The ReadASCII takes care of things like ramping, which is not embedded in the actual device.

I have tried commenting this line out and the setpoint stops being set at startup, while the ramping seems to be still preserved. However, it would be good to test this better and make sure it doesn't break anything else (are we left with uninitialised values?) and be sure it's not used by other IOCs

**Comment by IsabellaRey** [comment]
P.S. there is a eurotherm on my desk

**Comment by IsabellaRey** [comment]
Please when this ticket is done make sure that the fix in ISISComputingGroup/IBEX#1630 is reverted! (that ticket involved commenting out a SCAN field which should be restored)

**Comment by John-Holt-Tessella** [comment]
This ticket never appears to make it to the code so I have included it on the release notes on IRIS.

**Comment by IsabellaRey** [comment]
After discussion with Freddie and John, and as we have to apply ISISComputingGroup/IBEX#1703 as a hot fix, we're going to put the temporary fix addressed in ISISComputingGroup/IBEX#1630 into master (though we have created a separate ticket for it ISISComputingGroup/IBEX#1709 )

So THIS ticket must make sure the change in ISISComputingGroup/IBEX#1709 is reverted!

**Comment by IsabellaRey** [comment]
Following discussion with Freddie: changes in protocol file are more subtle than we initially thought.

- [ ] Have a regex that allows to deal with the variable terminator
- [ ] ERR PV: check if it's broken by setting all read protocols to be empty and see if we can get an error code or not. If we can, it means that currently the error gets reset in the device following a read. Could try by having a separate readerr protocol function, and the @mismatch in read/write would simply call that.

**Comment by IsabellaRey** [comment]
@John-Holt-Tessella  while looking into this could you also set the IOC to use the protocol in the data/ directory of the support module please.
