### ISSUE TITLE
User manual: how to convert genie scripts

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1647]
Add a page to the user manual to show examples of how to convert scripts from open genie to genie_python, like below. Note that some examples should be already in the slides used to train IRIS scientists on IBEX (check with Adrian or John where these slides are)

| My Open Genie Script |	Notes | My equivalent_genie_python Script |
| ------ | ----  | ------------- |
| My_Instrument_Script | It is fine to give your new genie_python script the same name as the original Open Genie script. | My_Instrument_Script () |
| /* some comment */ Do_something arg1 arg2 | In python, function calls have ( )s round the list of arguments. | #some comment Do_something (arg1, arg2) |
| /* another comment */ Do_something_else arg3 | ... | #another comment Do_something_else (arg3) |
| | |

**Comment by AdrianPotter** [comment]
See #1538

**Comment by IsabellaRey** [comment]
Moving to review complete, as any fixes will be addressed in #1538

**Comment by AdrianPotter** [comment]
I've changed the document format from markdown to restructured text so it appears ok on the shadow copy. Please check you're still happy.
