### ISSUE TITLE
GUI: Current/Total not working for high numbers

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1648]
From Ian:
"""
I’ve had a confusing time thinking that there was beam off, but it seems that the current/total counts display was not reporting the true number. My best guess is that it is reaching 999.99 before resetting to 0, and runs longer than 1000 uA are therefore misreported.

Runs over 1000 uA are rare, but not that rare, so I really think they should be reported properly. At these longer times the good/raw frames are also running out of space.

I’ve attached a screen shot of the end of the run - the real number of uA according to the journal is 4326
"""

In his screenshot the Current/Total on the dashboard displays 0 / 236.51

**Comment by IsabellaRey** [comment]
Comment from Freddie:
Could we please have an urgent fix to the GUI dashboard to add a bit more space in the “/Total” part, it looks like the leading “4” is being chopped off from 4236 (the “Current” part doesn’t need any change). Also we need a bit more space to handle Good/Raw frames in in the millions

**Comment by IsabellaRey** [comment]
I'm moving this back to ready, as I haven't had time to fix it. Feel free to pick it up if you have time before I'm back on Friday PM!


For the current/total, it may not be just a matter of more space (from Ian's screenshot it looks like that row had plenty space to print a number of 4326 - the Good/Raw Frames though do need more space). Maybe the problem is to do with formatting from Numbers to Strings in the GUI MonitorPanelModel, though at a first look I can't see why that would be a problem. It would be best to try and reproduce the issue by pointing the GUI at some test PVs (currently DAE:BEAMCURRENT and DAE:GOODUAH)

**Comment by IsabellaRey** [comment]
AH!! I think the problem is in ObservableDecimalRatio line 35: 

FORMAT.setMaximumIntegerDigits(3);

But this needs checking with test PVs and see if it affects any other class.

**Comment by kjwoodsISIS** [comment]
See also #1632.  We should resolve both tickets at the same time.

**Comment by IsabellaRey** [comment]
#1632 fixed in the same pull request as this ticket
