### ISSUE TITLE
GUI: Better handling of wrong java

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1651]
If you start the GUI with a 32-bit version of java, you get a verbose dialog starting 

```
Java was started but returned exit code=13
```

At the very least, this issue needs covering in the user manual. Ideally though we should catch it and output something a bit more useful.

**Comment by kjwoodsISIS** [comment]
User manual updated - see [Starting & Stopping IBEX](http://shadow.nd.rl.ac.uk/ibex_user_manual/Introduction/StartingAndStoppingIBEX)

**Comment by John-Holt-Tessella** [comment]
Bundled version is used
