### ISSUE TITLE
GUI: RBNumber not displayed on DAE

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1653]
The RB Number is not shown on the DAE -> Run Information tab. 

Reproduce:
1. Type RB Number 467328 in RB Number on Experimental Details
2. Click set
3. Look at RB Number on info tab it is not set.
4. Start run 
5. Look at RB Number on info tab it is not set.
6. Stop run
7. RB Number is in summary (C:\data\summary.txt)

System Seen On: IRIS

Found by Ian. Please report fixed to him after it is done.
Note RB Number can be set at any time on the Experimental Details Tab. It is definitely getting passed into the experiment because it appears in the log (C:\data\summary.txt) after a run. 
Also can you check what the length of this number is because 2147483647 misses off the last 2 digits (this needs an error in the GUI)

**Comment by AdrianPotter** [comment]
The client is looking at the wrong PV. `...:DAE:RBNUMBER` was replaced some time ago by  `..:DAE:_RBNUMBER` to fix some logic in the Experimental Database, see issue #748. Point the client at the correct PV (DAE version).

Similarly for USERNAME.

There is a problem with the PV that _RBNUMBER forward links to. I've captured it in issue #1743

**Comment by FreddieAkeroyd** [comment]
I'm moving this to impeded until we have discussed #1743 some more

**Comment by AdrianPotter** [comment]
Give #1743 a bit of time to get fixed. If it doesn't, I think it would be best to merge this in the mean time. The behaviour is as expected and definitely better than showing nothing
