### ISSUE TITLE
Log Plotter: Better tab names

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1654]
As an instrument scientist all my log plotter tabs being called "Not saved to file" doesn't give much information, and doesn't help to distinguish the plots, a better naming approach would improve the ability to view and discuss these plots.
#### Acceptance Criteria
1. If the variable to be plotted is a block, the tab name should default to the block name (e.g. "My_Block").
2. If the variable to be plotted is a PV, the tab name should default to the PV name (e.g. `IN:LARMOR:MK3CHOPPER_01:CH1:FREQ`)

**Comment by KathrynBaker** [comment]
Placed into the next sprint as this has come out of NDEMUONFE testing

**Comment by kjwoodsISIS** [comment]
I wouldn't call this a bug - the software is not doing anything that contradicts a requirement.  In this case there was no requirement about how the tabs should be named.

So, the question is this: what default name do scientists wish to see?
1. We could default the name to something based on the block name or the PV name?  For example: "Graph_of_My_Block_Name" or "Graph_of_My_Block_Name_(not_saved_to_file)".

The advantage of default name like "Not saved to file" is that it is very obvious that you have not saved the graph to a file.  Should we continue to include that phrase in the name?  Or do scientists not care too much about saving the plots?

**Comment by KathrynBaker** [comment]
I missed the enhancement label –a much better one to use.

The comment I had was “The log plotter tabs are all called "Not saved to file". Could they have more descriptive names?”, so your guess is as good as mine for what to call them instead. I think the problem is if you have three plots, how do you know which is which? I’d probably say that we can just use the block name on the tab, I don’t think there is much concern over the saving of blocks, and it prompts on exit anyway if the plot isn’t saved.

**Comment by kjwoodsISIS** [comment]
Added acceptance criteria to the original description.

**Comment by ThomasLohnert** [comment]
Note acceptance criterium 1 was fixed with https://github.com/ISISComputingGroup/IBEX/issues/2730

**Comment by KathrynBaker** [comment]
Note also that plots from the Beam Status screen has the PV name listed as well

**Comment by KathrynBaker** [comment]
Blocks do indeed have this now, and the other hasn't been mentioned since 2016 by a scientists. Closing we can create a more appropriate ticket if this is founf to be an issue again.
