### ISSUE TITLE
IOCs and GUI: Units are not displayed for some blocks [TIMEBOX: 2d]

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1655]
Some block have units but some do not fix this. Also if units get changed (e.g. TPG26x) the units are not updated in the blocks display. 

IOCs which don't have units:
1. TPG300 pressures
2. Lakeshore Temperature
3. Eurotherm Temperature
4. Chopper Phase which should be ms (IRIS chopper)

Reported by Ian please let him know when it is fixed.

**Comment by John-Holt-Tessella** [comment]
Merge in:

https://github.com/ISISComputingGroup/EPICS-utilities/pull/4
https://github.com/ISISComputingGroup/EPICS-Magnet3D/pull/1

ioc

**Comment by John-Holt-Tessella** [comment]
Couple of merges to add units. Created a new ticket to capture tasks left on this ticket https://github.com/ISISComputingGroup/IBEX/issues/1805

**Comment by DominicOram** [comment]
Small corrections on PR
