### ISSUE TITLE
IRIS: Support for Volumetric Rig

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1657]
As a scientist, I want to control the Volumetric Rig from an NDX machine.
#### Acceptance Criteria
1. To be determined
#### Notes
1. See e-mail trail below.  Further discussions may be needed and outcomes recorded below.
2. Implementation of this ticket might require several stories.

**Comment by kjwoodsISIS** [comment]
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 27 September 2016 13:31
> To: Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Silverwood, Ian (STFC,RAL,ISIS)
> Subject: IRIS Volumetric Rig
> 
> Dear Freddie and Kevin,
> 
> Ian Silverwood on IRIS has some sample environment kit being developed by Matt North’s sample environment group. Graham Burgess is currently working on it. Initial details are :
> 
> 1)	Called Volumetric rig. Mixes different gases together according to required recipes.
> 2)	Long running project – running for years – internal ISIS development.
> 3)	PLC with HMI developed by Graham Burgess.
> 4)	Opens and closes valves. Interlock system present to prevent different gases being allowed to mix.
> 5)	The intention is for RS232 remote communication (I believe). Commands are not yet defined.
> 6)	Controlled via ndx
> 7)	Controlled also offline by another system for setup purposes (possibly another ndx, or a laptop – we need to make a decision on this)
> 8)	Wants to have control of the recipes from script. Need to decide where this control resides (for example, in the PLC, ioc, or python script – after talking briefly with Ian, I think the ioc, but this needs to be discussed)
> 9)	Needs to be moved around the hall to different beamlines.
> 10)	Remote interface on the PLC side has yet to be written.
> 11)	Delivery date is hoping to be early 2017.
> 12)	There is a student in the mix of this project that is looking to do some work on the development and operation of this equipment (Zoe)
> 13)	System assembly is by Mark Kibble.
> 14)	Project leader is James Taylor (commissioning and software).
> 15)	Electronic PLC control is Graham Burgess.
> 
> Kind regards,
> 
> Gareth

**Comment by John-Holt-Tessella** [comment]
Q) Check if this is Modus over TCP.

**Comment by kjwoodsISIS** [comment]
> From: Silverwood, Ian (STFC,RAL,ISIS) 
> Sent: 25 October 2016 09:35
> To: Silverwood, Ian (STFC,RAL,ISIS); Bones, Jon (STFC,RAL,ISIS); Howells, Gareth (STFC,RAL,ISIS); Akeroyd, Freddie (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS); Holt, John (Tessella,RAL,ISIS); Burgess, Graham (STFC,RAL,ISIS); Taylor, James (STFC,RAL,ISIS); kevin.woods@tessella.com
> Subject: Volumetric rig control
> When: 29 November 2016 10:30-11:30 (UTC+00:00) Dublin, Edinburgh, Lisbon, London.
> Where: CR22 - RL, R1 (10,VC)
> 
> I’d like to get us together to discuss how computer control of the new volumetric rig is likely to work and how SECI/ IBEX can interface with everything.
>

**Comment by kjwoodsISIS** [comment]
IOC, OPI, Emulator

**Comment by John-Holt-Tessella** [comment]
First part in #1881

**Comment by John-Holt-Tessella** [comment]
Latest estimate is that it will be needed for September 2017.

**Comment by John-Holt-Tessella** [comment]
>Hopefully the apparatus will be ready by September, and then commissioned by James. If >it is not, then it is unlikely to be ready until the new year, as it is unlikely progress can be >made during the cycle.
>
>For the initial commissioning, the panel can be operated by the integrated interface on >the panel, but for more advanced operating we will want the ability to script. I think if you >aim to have things ready by January/February that would suit me.
>
>Thanks,
>
>Ian

**Comment by GRyall** [comment]
Assuming this is ISIS project 540, it was cancelled in 2021 (see internal project list documentation for more detail).
