### ISSUE TITLE
ZOOM: Are the Julabo Models all supported?

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1658]
ZOOM will be using the following three models of Julabo:
FP50-HE
FPW55-SL (as on SANS2D)
FP51-SL (as on SURF)

We should ensure that all three can be supported by the IOC, and if not generate a ticket to make the appropriate changes

**Comment by John-Holt-Tessella** [comment]
This looks good and is the same as the "FP50_MH" db file which is loaded. The only worry I have is the read termination characters. The manual suggests they should be `\n` but the protocol has it as `\r\n`. I think this can be sorted out during the test.

**Comment by John-Holt-Tessella** [comment]
See doc https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Julabo

**Comment by KathrynBaker** [comment]
Regarding termination characters, if they do need to be different, then there are easy ways to macro the values out for variation.
