### ISSUE TITLE
genie_python: Disconnected blocks should have None as value

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1662]
As a python user when I cget a disconnected block I want its value to be None and I want to be able to query a connected property on the dictionary.

NB this should relate to other showing values too.

**Comment by AdrianPotter** [comment]
Works as advertised, thanks. For consistency though, if a block is not under run control then shouldn't its high and low limits also be `None`?

**Comment by AdrianPotter** [comment]
Captured under #1643
