### ISSUE TITLE
IOC: Cryvalve STATUS needs SP for cset

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1663]
Requested from Ian. As a user, he would like a PV for STATUS:SP equivalent to the current OPEN:CMD so that cset works with associated blocks.

The background for this is that if you set a block in genie_python (e.g. `...:STATUS`) and then run `cset` on it, it will try and set the set point associated with that PV (e.g. `...:STATUS:SP`). The Cryvalve doesn't have that, so you can't do a `cset` on a block watching the status.

There is a workaround which is to use `set_pv` instead and set the PV directly, but it would be easier if it could be done from a block name.

The fix for this should be easy, just alias OPEN:CMD to STATUS:SP. The original PV should still be available so as not to break any backwards compatibility.

Also as part of this ticket, please update the IOC PR checklist and documentation to highlight this particular issue.

**Comment by FreddieAkeroyd** [comment]
I think the PV should actually be called STAT rather than STATUS as per
 https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming

**Comment by AdrianPotter** [comment]
Fair point. Under this ticket, please review any other new IOCs:

- Lakeshore 336
- PDR 2000
-  LINKAM95
- TPG300
