### ISSUE TITLE
genie_python: Create template Python directory in master settings

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1666]
On Iris, we set up a directory containing an instrument initialisation file (`init_iris.py`), package initializer (`__init__.py`) and instrument file (`inst.py`) in `C:\Instrument\Settings\config\NDXIRIS\Python`. These set up the standard package names for genie commands and instrument scripts.

Please set this up on the master branch of Settings\config so it is automatically applied to new instruments.

Please also apply it to the other existing instruments.

**Comment by John-Holt-Tessella** [comment]
do #1749 at the same time (read before doing this)

**Comment by Tom-Willemsen** [comment]
This has already been done by @John-Holt-Tessella, I have just updated it to be in line with the changes in #1749
