### ISSUE TITLE
GUI: View configs when in read-only

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1667]
When pointing the GUI to a machine that I don't have write permission I would like to be able to view the config, hence 'edit config' should change to view.

**Comment by KathrynBaker** [comment]
#1410 already exists to cover the first point

**Comment by DominicOram** [comment]
Thanks, updated desc

**Comment by KathrynBaker** [comment]
Comment that no longer made sense and provided a link that could have been confusing has been deleted.
