### ISSUE TITLE
BlockServer: Crashes when git locked

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1673]
The blockserver seems to occasionally not release the lock from the configurations git repo when shutting down. This means that on next startup the lock cannot be obtained resulting in a message of `Lock at ... could not be obtained`. The blockserver will then not work, with the error message of `no attribute '_config_list`.

The blockserver should be able to deal with a locked git repo gracefully and should ideally never leave the repo in a locked state

**Comment by AdrianPotter** [comment]
Merge with #1518 so exceptions are properly caught by the write queue
