### ISSUE TITLE
Web Dashboard: Add caching to JSON Bourne

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1674]
Caching should be added to JSON Bourne so that when pages are requested they load much faster

**Comment by DominicOram** [comment]
Note that this work has now been done as part of https://github.com/ISISComputingGroup/IBEX/issues/1675 on the branch for that ticket

**Comment by ThomasLohnert** [comment]
Only some minor changes needed. Filed this issue under rework symbolically for both issues being fixed by the PR

**Comment by DominicOram** [comment]
Rework done

**Comment by DominicOram** [comment]
Note: Keyboard interrupt wont work inside pycharm (bug with pycharm)
