### ISSUE TITLE
Web Dashboard: Look at favicon

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1677]
The web dashboard currently has no favicon, we should put one in.

**Comment by DominicOram** [comment]
Can use the icon in base\uk.ac.stfc.isis.ibex.client.product\icons

**Comment by AdrianPotter** [comment]
Cannot be reviewed before #2509

**Comment by AdrianPotter** [comment]
Awaiting rework of #2509
