### ISSUE TITLE
User Manual - Reference Section

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#1682]
As an ISIS computing support person, sample environment support person or instrument scientist, I would like to be able to refer to a "reference" section of the user manual to find out about a particular device on the ISIS instruments and specifics of how the device is connected, and how it's drivers are implemented within IBEX.  Some tasks which I would like to be able to perform with the help of the appropriate section of the reference section of the user manual are:

**Key things I would like to be able to do.**
1. Move a device from one instrument to another (where the device has not been configured on the destination instrument).  Successfully configuring and getting values read out for scripting.
2. Diagnosing Problems with a device which was previously working but for some reason no longer appears to be responding.
3. Adding a second or third device where one device is already functioning. e.g. as second Eurotherm.
4. Replacing a device where for some reason the hardware has failed.
5.  Change a calibration table (for example when a sensor has been replaced)

**Notes**
This is checklist of the sort of things which would be useful in the reference section for a device (or class of devices if more appropriate).  It would be good to do one or two device reference "pages" to get the format organized and tested with supporters and scientists.
- [ ] A quick reference to any other names the device may have, other things it is used in or connected to, other manufacturers of the same device.  How similar are different other models of this device to this one? and links to appropriate separate device references if necessary.
- [ ] A picture or two in situ of the real device or a similar one (or diagram) of the device or that type of device, particularly with reference to any connectors which might need to be identified in a support situation.
- [ ] A _short_ description or introduction to the device, it's purpose, the normal use in an ISIS context so that I understand what the device is.  This would include how it would normally be controlled e.g. cset commands, manual control with block readout etc.
- [ ] A note about proper device usage, any potential hazards when dealing with it, e.g. connecting, powering off/on and power cycling for example.  Links to any specific risk assessments.
- [ ] A link or links provided to one of more manufacturer's manuals stored online, probably kept in SharePoint and accessed by a federal id to avoid compromising a manufacturers IP.
- [ ] A full list of associated PVs and prefixes to enable diagnostics to be carried out on the device along with descriptions.  It is important that though they may be "interesting" or otherwise that they are available as I do not always know what the scientist may require from a device (for simply logging the correct PV).
- [ ] Specific pointers to any initialization files and settings which apply to this device with guidance about where they are, what may need changing within them.  How to recover them if corrupted or missing.
1. Not all of these items need to be laboriously added, but can be computer generated lists to be available as part of the manual (even when bits are printed to PDF or paper).  PVs, IOC settings and PV descriptions are likely to come from the device database.  Pointing to a separate document or source code is not overly helpful and may not be available if there are network issues when support is needed.
2. Mining the tickets and comments of devices which have already been developed would provide most of the information about devices, IOC setup etc. if selectively formatted into the general device descriptions.  This information otherwise is likely to be lost.

**Comment by GRyall** [comment]
There is now documentation on the wiki here: [https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC). But if this is lacking, please do reopen the ticket with the detail of what still needs to be provided
