### ISSUE TITLE
Device Reference - Eurotherm

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#1683]
As a computer support person, sample environment (user support) person or scientist I would like to be able to read a section of the user manual to allow me to identify, understand, configure, attach and diagnose issues with a standard ISIS Eurotherm Temperature controller. #1682 gives the basic structure of the information I will need to see in the reference section of the user manual.

**Notes**
- I am technically trained, familiar in general with support in ISIS and as a basic user of the IBEX system but may be new to the device I have been asked to set-up on a Sunday lunchtime!
- I don't want to be held up by lack of information or feel that the first thing I need to do is phone someone else at home.
- I would like to print a copy of the appropriate section (to PDF for sure or even paper)

**Comment by GRyall** [comment]
There is a wiki page now here:[https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eurotherm]( https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eurotherm). Closing the ticket as complete, do reopen if the documentation still lacks something required.
