### ISSUE TITLE
Inst_server: Refactor to use connection pool

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1686]
Linked to tickets #1614 and #1515. At the moment, there is an issue with multiple threads making simultaneous queries on the same connection causing errors and a hang.

Kathryn is implementing a quick fix of locking the method so only one thread can access it at a time. A better solution would be to use a connection pool.

To reproduce the current issue, run the following genie_python script on your local instrument:

```
from genie_python import genie as g
for i in range(10000):
    g.changeSamplePar("HEIGHT",1)
```

Hopefully 10000 iterations is enough to observe the issue.

Once fixed, please test that:
1. The number of TCP connections created is not excessive, as in ticket #1515
2. The interesting PV list still gets populated as expected
3. Please do a thorough check of inst_server related behaviour from genie_python and in the GUI to try and rule out any other negative side-effects

**Comment by AdrianPotter** [comment]
Also see if #1679 can be reverted once this is sorted

**Comment by ChrisM-S** [comment]
Just a thought,  but is this something we could capture in an automated system/stress test?

It’s clearly important that any build (after the fix) will pass this, and if we go for connection pooling, this is certainly one regression test that needs to pass after this is done.

Chris
