### ISSUE TITLE
RB numbers list not updated on LARMOR

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1688]
Rob has reported he hasn't got any RB numbers for this cycle, but can see last cycle. Looking at the log file shows

[Wed Oct  5 11:11:20 2016] Error updating database: 1062 (23000): Duplicate entry '1569006' for key 'PRIMARY'
[Wed Oct  5 12:11:20 2016] Performing hourly update
[Wed Oct  5 12:11:20 2016] Error updating database: 1062 (23000): Duplicate entry '1569006' for key 'PRIMARY'

**Comment by KathrynBaker** [comment]
If the update isn’t working there is an obvious fix to get that working, and we can investigate the bug off-line – if the contents of EXPDB are deleted, a console opened to the EXPDB process and type in the command “U” (for update) it should just pick up what is in the current RBNUM information. This will not fix the bug, but should provide a quick fix.

**Comment by FreddieAkeroyd** [comment]
Having had a look at the code , the problem is that it cannot handle a continuation experiment i.e. the same RB number coming back with different dates. There is a check for (rbnumber, date) to see if an experiment is present, which fails if it has a new date, but then the insert fails as the rb number is the primary key. I can fix that bit easily by changing the  check_experiment() method and using an UPDATE rather than insert, but I don't know if there will be a similar issue with team memberships at the moment...

**Comment by KathrynBaker** [comment]
Having had a look at the code myself (hence the ticket now being in progress), I'm not sure a simple change and update instead would work (as no new experiments would then be added). However, everything is reasonably isolated so changes to one data area should have little impact on others.

The big question, the assumption that lead to that check for experiment based on those criteria was the RB Numbers don't get reused - which is obviously not the case, but would we ever have the RB Number repeated within a typical cycle (or at least that XML file)?

If we can expect that, we probably need to extend the PK of experiment to be the ID and the start date. We would then need to alter the check to be on only those two items (and update the duration if it is different in the check), expand the experimentteams to have that date in as well, and update everything else.

If we should never have RB Numbers repeated in that XML, then we can update the check on experiments to look only for the ID, and if it exists check (and update if necessary) the start date and the duration.

**Comment by kjwoodsISIS** [comment]
Are there documented rules on how RB Numbers should be used?  Surely we should at least review these (if they exist) to see if IBEX is currently handling all the situations it needs to handle.  Does Hannah's team "own" these rules?

**Comment by KathrynBaker** [comment]
If there are documented rules, I’ve never seen them. Having double checked with Matt that it is unlikely but may be possible, I shall contact Hannah to gain clarification, as whilst they might not ‘own’ those rules, they should know what they are.

**Comment by FreddieAkeroyd** [comment]
Experiments can be scheduled in multiple parts, I'm guessing they get the same RB number for both parts, but that is a Hannah question. How likely it is both parts would fall in the same cycle I don't know. I'm also not sure if multi-part experiments are usually when you have beamtime on more than one instrument, in which case we wouldn't see that as the file has been pre-filtered by instrument. The issue on LARMOR was a user coming back to finish an experiment from a previous cycle, I suppose in theory if they lost beamtime at start of cycle could they get re-scheduled for end of cycle and hence appear twice, or would actually the original entry get updated and hence they still only appear once but with a different date? I'll push my simple fix on a branch anyway and we can await Hannah's reply.

**Comment by KathrynBaker** [comment]
I received a response from Hannah:

> An experiment (i.e. an RB number) can span several visits. For example, an experimenter may be
> awarded 10 days of time for a particular RB number but are only scheduled to do 4 days at first and > then if that all goes well they are booked in at a later date (usually in a different cycle) to use the 
> remaining 6 days. Both stints have the same RB number as they are part of the same experiment. 
> Dates can change as scheduler reschedule things but I believe the web service will return you an 
> experiment part number too. The part number refers to the stints e.g. their first 4 days in the previous > example would be part 1 and the second stint of 6 days would be part 2. An experiment can have 
> many parts (no max). An experiment has a minimum of 1 part.

The XML that is being generated from this web service doesn't use the part number. We should probably alter the PK rules to include the start date in light of this.

**Comment by KathrynBaker** [comment]
Returned to backlog, as that will be a breaking change we should wait until the long Sprint for release in the new year (need to alter the PK, and therefore the Databases and python to reflect that)

**Comment by FreddieAkeroyd** [comment]
I agree that a change to the PK should be delayed and would be the proper fix, but I believe the PR I submitted will fix the majority of cases seen (one repeated experiment part per cycle) which was Rob's reported issue. As there were a few accelerator issues last cycle, we might be seeing a few repeated experiments next cycle on both IRIS and LARMOR. If there are two or more experiment parts in a cycle you would only see one of them, but at least would be able to choose the right RB number if not the right date (and we don't use the date ourselves anyway). I would suggest we create a separate ticket for the proper solution and look at deploying an intermediate fix for next cycle.

**Comment by FreddieAkeroyd** [comment]
Ignore PR 91 - reference by mistake
