### ISSUE TITLE
Dataweb: Auto update page or values on page

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1690]
As a scientist I would like the number on the page to autoupdate. Either the page should, optionally, autoupdate or can we use javascript to update the number in place.
1. Use case: I want to be able to zoom in on my phone and not have the page refresh itself thus loosing the zoom
2. I might want to set the rate of autoupdate if the page whole page is updating

Asked for by: Russell

**Comment by DominicOram** [comment]
A first step towards doing this is https://github.com/ISISComputingGroup/IBEX/issues/1676.

Leaving this ticket here as a placeholder for creating a more sophisticated solution.

**Comment by ThomasLohnert** [comment]
I believe this was fixed with https://github.com/ISISComputingGroup/JSON_bourne/pull/2

**Comment by Tom-Willemsen** [comment]
was done
