### ISSUE TITLE
IRIS: Test the sample changer

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1691]
The sample changer will be available later this week so we can test it on IRIS with the mcleanon motors.

**Comment by AdrianPotter** [comment]
@davidkeymer and I spent a couple of days last week on the sample changer. It required a few fixes, which I did under a separate ticket having forgotten this one existed. The sample changer is now working as expected

**Comment by AdrianPotter** [comment]
Related ticket is #1708
