### ISSUE TITLE
IOC: Lakeshore SP for temp

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1692]
As a scientist I would like to create a temperature block for a lakeshore and be able to set it's value.

This is currently not how it works because the temperature controller can be connected to any of two sensors so each temp doesn't have a set setpoint PV. However we could maybe work around this. Think about how to do this and fix it if possible.

Asked for by Ian

**Comment by kjwoodsISIS** [comment]
Ask if Ian needs this for next cycle.
