### ISSUE TITLE
MUONFE: SECI generate lvDCOM startup files

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1695]
The muon group would like to have selected values from EMU/HIFI/MUSR available as blocks on MUONFE so that they can be both logged and controlled, and also a synoptic created. A general way to do this would be for SECI to automatically generate a lvDCOM config file (+db substitutions file) for all its blocks whenever a configuration is loaded. This then provides a generic way to partially epicsify a SECI instrument. 
- seci generate lvDCOM xml file from information in its blocks
- seci generate a DB template substitutions file - see #1694 

restarting of lvDCOM is covered in #1696

This has now been done with lvDCOM reading the block information from SECI and self-generating its own config files

**Comment by John-Holt-Tessella** [comment]
Relies on #1694

**Comment by mattclarke** [comment]
I was planning to review this until I realised I didn't have LabVIEW installed!

**Comment by FreddieAkeroyd** [comment]
Docs at http://epics.isis.stfc.ac.uk/doxygen/lvDCOM/ updated with SECI command
