### ISSUE TITLE
Mobile Dashboard

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#17]
As a scientist, I want a mobile dashboard GUI, so that I can control my experiment from a mobile device (e.g. iPad, Android tablet, smartphone, etc.)

'''Completion Criteria'''
1. I can view the PV values for my experiment on my mobile device.
1. I can set the PV values for my experiment on my mobile device.
1. [optional] I can halt my experiment from my mobile device.

'''Notes''':
1. LV already has an iOS app that works with shared variables (need to make our VIs shared-variable aware)
1. Can we write CSS clients that run on iOS an/or Android?
1. Do we need to clear this kind of access with IS? - Answer: almost certainly!
1. Need to clearly state which devices we're prepared to support (e.g. iOS, Samsung Android tablets & nothing else).

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 17.  Created by skn09965 on 2013-01-14T12:19:28, last modified: 2013-01-14T12:19:28_

**Comment by kjwoodsISIS** [comment]
This is not going to happen any time soon, quite apart from the notion of being allowed to control an instrument from a remote location.  Issue closed.

**Comment by ChrisM-S** [comment]
I'm sure this came through from the requirements sessions (and before), should we be dropping this? or is the requirement preserved if not the ticket, I know Pas was originally asking for this amongst others.

**Comment by kjwoodsISIS** [comment]
The ticket, as currently written, suggests that the user will be able to **_control_** his or her instrument remotely from a mobile device (i.e. from iPhone or Android phone whilst walking up the High Street...).  I can't see that ever happening.  Viewing, yes; control, no.

I am not suggesting that by closing this ticket we will never create a mobile dashboard.  We can create a new ticket when we are ready to create a mobile dashboard (for viewing).  Similarly, if we want to create a mobile device for **_control_** (e.g. for the mobile jog-boxes we have previously discussed), we can again raise a ticket when we are ready to do so.

Unless we are prepared to act on this ticket soon, there is no point in keeping it open - it just adds to the overall administrative burden and contributes no value.
