### ISSUE TITLE
Dev: Add to gitignore

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1701]
Add .idea and .project to git ignore files so that these files are not checked in.

**Comment by AdrianPotter** [comment]
For inst_servers:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/91

I've submitted the addition for `.project` files to all EPICS submodules directly to master. Having talked to John it was too much work to make pull requests for every one.  Don't update the EPICS submodules, they will trickle in gradually as each is updated as a result of other changes.

**Comment by FreddieAkeroyd** [comment]
I've pushed all the git submodules, it was making for rather a confusing view otherwise
