### ISSUE TITLE
IRIS: Look at script issue

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1702]
Ian's script stopped mid run. Why?

**Comment by John-Holt-Tessella** [comment]
Ian had a strange script failure last night which he’s asked me to have a look at.  I haven’t done yet, but I’m bound to need some help somewhere, so I thought I’d send the details around as a start.  So if anyone has a chance to have a look, then Ian (& I) would appreciate it.

See ![log plotter image](https://raw.githubusercontent.com/wiki/ISISComputingGroup/ibex_developers_manual/troubleshooting/LogPlotter.png) for plot of interest

**Comment by John-Holt-Tessella** [comment]
Appears SP was not registered by Eurotherm

**Comment by FreddieAkeroyd** [comment]
Hopefully fixed in #1703

**Comment by John-Holt-Tessella** [comment]
Fixed 1703 plus #1707
