### ISSUE TITLE
Automatically check and reissue Eurother setpoint

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1703]
The eurotherm IOC checks that a setpoint has been received, but does not actually do anything if it has not other than set an error PV flag. We need to re-issue the setpoint if there is a mismatch.

**Comment by IsabellaRey** [comment]
I haven't managed to reproduce the issue on the Eurotherm on my desk.  However, as the changes do what they say, I have merged anyway, so I can carry on with #1646.
I will be testing the current ticket on IRIS when they are free; and keep this ticket open until then. If the issue re-appears in the future, it might be that we have to tweak some parameters, like the max number of retries.

**Comment by IsabellaRey** [comment]
Moving to Review complete as this is now running on IRIS
