### ISSUE TITLE
genie_python: add command to disable FIFO veto

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1704]
To avoid the nasty hack for Tino I just did - a bat file to call Open GENIE with

tkgenie32.exe -e "SET_FIFO_VETO/OFF;EXIT"

:-D

**Comment by kjwoodsISIS** [comment]
Needs to be done by February.

**Comment by John-Holt-Tessella** [comment]
Also add to GUI?

**Comment by FreddieAkeroyd** [comment]
It's one that should only be turned off in exceptional circumstances, historically it has not been on the GUI and only available via a command. I'd be cautious about putting it in the GUI in case it got turned off accidentally, if it was on the GUI then it should bein an "advanced" section with appropriate warnings.

**Comment by FreddieAkeroyd** [comment]
Just been requested on IMAT by Winfried

**Comment by FreddieAkeroyd** [comment]
current workaround on IMAT (using opengenie)

    os.system(r”c:\users\spudulike\fifo_off.bat”)

**Comment by FreddieAkeroyd** [comment]
Send the name "FIFO" for fifo veto
