### ISSUE TITLE
Genie Python: Set and confirm

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1707]
Should we add a command to gennie which is set and confirm. It could access the SP:RBV of a block to make sure that the set point is correct?
This would have helped with Ian's issues.

**Comment by GRyall** [comment]
Not re-requested since and an alternative fix was found for the specifics of "Ian's Issue". Whilst the general case remains, no one else has asked in the 8 years since.
