### ISSUE TITLE
IRIS: McLennan set up and testing

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1708]
The McLennan powering the linear sample changer on Iris needs testing to confirm that the IOC and OPI work as expected and can drive the real motor

**Comment by AdrianPotter** [comment]
Some feedback from testing this morning:

- [ ] Need to set up sample changer cmd scripts for the McLennan
- [ ] The current macros do not allow a negative encoder ratio, please fix
- [ ] Please document how macro velocities and accelerations are translated into device values

**Comment by AdrianPotter** [comment]
The first issue is fixed by:

https://github.com/ISISComputingGroup/EPICS-ioc/pull/85

This will need hotfixing to Iris once the PR has been reviewed

- [ ] Hotfix updated McLennan IOC to Iris

**Comment by AdrianPotter** [comment]
2nd checkbox applied to the same PR as the 1st

**Comment by John-Holt-Tessella** [comment]
Because this was released quickly onto IRIS. I have closed, reviewed and deleted the branch it is now on master. Only the documentation needs reviewing.

**Comment by AdrianPotter** [comment]
Documented here: https://github.com/ISISComputingGroup/IBEX/wiki/McLennan-motors

**Comment by AdrianPotter** [comment]
I've also updated the McLennan IOC macros: https://github.com/ISISComputingGroup/EPICS-ioc/pull/86
