### ISSUE TITLE
IRIS: Disconnected PV in run

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1710]
Ian sent:

> Hi David,
> 
> I was trying to run for a long time, and my script to seems to have 
> got halfway, then run into trouble with the Lakeshore 336.
> 
> Output 1 was looking fine, but output 2 was all “Disconnected” pink 
> text. I tried restating the IOC, but it now everything on the 
> lakeshore is showing “Disconnected”
> 
> I tried to see what was happening behind the gui, and got the following:
> 
> g.cshow(Ramp_Ref_top)
> Traceback (most recent call last):
>   File "C:\Instrument\Apps\Python\lib\site-packages\ipython-2.2.0-
> py2.7.egg\IPython\core\interactiveshell.py", line 2883, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-11-9da7b641c7a9>", line 1, in <module>
>     g.cshow(Ramp_Ref_top)
> NameError: name 'Ramp_Ref_top' is not defined
> g.cshow('Ramp_Ref_top')
> ERROR: Non-hexadecimal digit found
> CA.Client.Diagnostic.................................
>     Warning: "Virtual circuit unresponsive"
> Source File: ..\tcpiiu.cpp Line Number: 945 ……………………………………………..
> 
> I’ve left it in the current state for you to have a look at if you 
> want, but I’ve also told John and Adrian they can aply fixes.
> 
> Let me know if you have any thoughts about this.
> 
> Ian

Investigate

**Comment by John-Holt-Tessella** [comment]
Clearly the first cshow is a syntax error but the second is weird. If the block severer is not running this would probably cause problems here.  Not sure about PVs in OPI/blocks.

Avenues of investigation:

It appears that the block server did not start after  a configuration change. It was actively toggled by the block sever. It is not clear why though.  @FreddieAkeroyd  to look at logic in proc serve to make sure autorestart flag is ok. 
Extra logging should be added to C:\Instrument\Apps\EPICS\support\procServControl\master\db\procServControl.template so we can see what happens to it.

We should check what happens to the dashboard when run control is absent.

**Comment by FreddieAkeroyd** [comment]
Is this related to #1711 too?

**Comment by FreddieAkeroyd** [comment]
See comments in PR on how to test
