### ISSUE TITLE
GUI: spaces in config name should not be allowed

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1712]
Steps to reproduce:
1. create a new config
2. in the config name, type a letter and then blank spaces
3. the OK button is enabled and the config can be saved

The Name info field says the name can only contain letters, numbers and underscores.
We should fix so that spaces are not allowed, and have an automated system test covering this

**Comment by kjwoodsISIS** [comment]
Agreed.  Needs to be consistent with other types of object (e.g. PVs, group names, etc.).

**Comment by kjwoodsISIS** [comment]
When we do this, search instruments for any configs with spaces in the names before we deploy to those instruments.

**Comment by kjwoodsISIS** [comment]
This is not so very different from #1830.
