### ISSUE TITLE
CSS weird formatting behaviour

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1714]
The TPG26x OPI behaves differently if it's run from within the GUI or from CSS, which is weird!

Steps to reproduce:
1. Run the TPG26x IOC in recsim mode
1. Set the 1:PRESSURE PV to a very small value, e.g. 1.23456789e-7
1. Open the OPI through CSS and through the GUI
1. In the GUI, the value is displayed as 1.2346E-7, but within CSS it is 0

Note that the widget is a TextUpdate with the following properties:
- Format Type: Compact
- Precision: 2
- Precistion from PV: yes

It looks like from CSS the widget honours the PREC field of the PV (0 in this case, as it's a CALC), whereas from within the GUI it ignores both the PREC of the PV and the Precision property and simply displays up to 4 digits in scientific notation.

Maybe it's not a problem worth fixing, but should we at least document it as a CSS quirk?

**Comment by KathrynBaker** [comment]
Whether frustrating or not, it has not been considered since 2016, closing
