### ISSUE TITLE
TPG26x precision

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1717]
The PRESSURE PVs of the TPC26x are calc fields marked as high interest. They have no PREC field defined, so they default to 0 and no fractional digits are displayed in the corresponding blocks.

The PREC field should probably be 2 or 3.

This error didn't get caught in the db checker script, because the PVs are calc instead of ai. Maybe it would be good to change the calc to output to ai, which is then marked as high interest, so the db checker doesn't miss them (they are also missing an EGU field)

**Comment by John-Holt-Tessella** [comment]
Instrument is has a precision of 4 so I have used that
