### ISSUE TITLE
Dataweb: Refresh occasionally slow

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1718]
When refreshing the new dataweb it will occasionally take 3-4 seconds to get the JSON and display the data.

Best guess is that it's to do with the data being locked in JSON bourne as it's trying to scrape it from the instruments at the same time you read. Some more sophisticated caching is probably the solution

**Comment by Tom-Willemsen** [comment]
New web dashboard is faster
