### ISSUE TITLE
IOC: Eurotherm labview feature transfer

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1720]
As an IBEX user having used SECI I would like the eurotherm to provide the same or more functionality on IBEX.

Investigate the Labview for the Eurotherm and add tickets for any missing features.

**Comment by kjwoodsISIS** [comment]
There are two LabVIEW Eurotherm VIs (no reports  - yet  -  of a 3rd), so need to check both.

**Comment by kjwoodsISIS** [comment]
If we need to enhance the Eurotherm IOC, wait for users to ask for enhancements.
