### ISSUE TITLE
GUI: duplicate config name is being allowed

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1727]
Steps to reproduce:
1. Create a new config through the GUI
1. Create another new config through the GUI, giving it the same name as the previous one

The GUI tells you that a config with the same name already exists, but just as an info message, not an error message, and the OK button is enabled.

When saving, the new config over-writes the old one, and there is no indication to the user that this is going to happen.

If this is a bug, the GUI should not allow duplicate names.
If it's the intended behaviour, the GUI should warn the user and then confirm again that the user is OK with the config being over-written

**Comment by IsabellaRey** [comment]
There should be an automated system test for this, and also an entry in the manual system tests spreadsheet, if it's not there already

**Comment by DominicOram** [comment]
Code good, this should also be tested as part of https://github.com/ISISComputingGroup/IBEX/issues/1848
