### ISSUE TITLE
IRIS: Add "Stuck in waiting" issue to troubleshooting in manual

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1730]
On 18/10, we had an issue whereby IRIS got stuck in a waiting state. The solution was to clear the sql archive files, fire up SECI and end the existing run (which didn't appear either in IBEX or the LabView VI). This cleared the way for an IBEX run to start.

As a developer/support engineer, I would like this incident to be recorded in the troubleshooting manual so that in the future I can refer back to it in case it happens again

**Comment by AdrianPotter** [comment]
Added `1` label to capture time spent diagnosing original issue

**Comment by AdrianPotter** [comment]
I've added a description of the problem to:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Experimental-Runs

**Comment by ChrisM-S** [comment]
Hi Adrian,

I think we did step (1) again after closing SECI so on the restart of IBEX the ICP created these afresh.  Also the kill SECI on the start menu also kills the “isisicp.exe” explicitly which must be gone to allow these files to be deleted.

Chris

**Comment by FreddieAkeroyd** [comment]
Hi,

I don't think you needed to end the run - firing up SECI would have been enough. The ICP had been left in a "sample out of range" state by SECI previously, EPICS had not send an "in range" message when it started as it believe things are already in range. Startup up seci would have sent an in-range message as I suspect the out of range block would have been configured by Open GENIE and hence not preserved between restarts. I'll change the EPICS side to flush the current run control status on a restart even if it thinks it is correctly set already - see #1735
