### ISSUE TITLE
Eurotherm IOC: CHECKSP PV alarm at startup is confusing

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1733]
The _CHECKSP PV checks if the SP and the SP:RBV are equal within tolerance, and goes into an alarm state if they are not. Its alarm state is then displayed in the GUI alarms perspective.

At startup this PV is flagged as an alarm because it is in an UDF state (as it doesn't process until we try to set the SP), which is confusing to a user. However, we don't want to process this PV at startup because it triggers a retry of setting the SP.

We could refactor to have an extra PV to hold and flag its alarm status. This new PV could process at startup so not to be UDF, The current _CHECKSP would then push its own value to this PV

**Comment by FreddieAkeroyd** [comment]
The default status of the STAT and SEVR fields are UDF, INVALID - if we add

field(STAT, "")
field(SEVR, "NO_ALARM")  

to the DB file I think that would fix it

**Comment by FreddieAkeroyd** [comment]
Actually 

field(UDF, 0)

is the thing to do
