### ISSUE TITLE
Flush run control settings on startup

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1735]
This is to prevent a potential issue caused by switching between SECI and IBEX. If SECI has left the instrument in a WAITING state, IBEX will not automatically correct this on startup if it thinks the instrument is already in the correct state. This fix will add an automatic flush of the ibex run control state

**Comment by FreddieAkeroyd** [comment]
An automatic flush at startup has the question "at what point in startup", if you flush too early it may say all is OK before PVs have registered out of range. Currently i have just added a PV that can be manually called to initiate a flush.

**Comment by John-Holt-Tessella** [comment]
Would it be fair to put this on start? So it automatically refreshed run control on start. This would make the move between SECI and IBEX seamless i.e. I don't have to call resest. The run control should be set up when I start the experiment otherwise I am in trouble anyway,

**Comment by FreddieAkeroyd** [comment]
As per my previous comment, yes but you need to do it at the right point - do it too early in startup and the blocks may not have registered they are out of range and you will then send an OK message to the DAE and accidentally start data collection for a short period before it then realises all is not OK. Currently the run control blocks monitor the IOC values and compute run control when they change, if you flush too early they will still be at "all ok". The blocks might have autosaved their run control status, but I hadn't got to looking at that properly.

**Comment by John-Holt-Tessella** [comment]
Sorry I meant  on start of data collecting e.g. start() or pressing the button labeled "begin run"

**Comment by FreddieAkeroyd** [comment]
I was avoiding putting this in the DAE as it creates an additional dependency, run control is governed by the blockserver and I was keeping the DAE independent of this. If we put it elsewhere then is it on the GUI button, genie python begin() command, both... It suggests we might want a higher level interface to "begin" than the DAE - we could put it on both GUI and gene_python but that feels like duplication and so wrong. If we put it in one place, we need to document the behaviour - and then might as well just have a separate special command. I'm not against the idea, it was just that I wasn't sure of the best place to put it at the moment.

**Comment by John-Holt-Tessella** [comment]
OK, I really haven't got a good grasp of the architecture around this area. In which case we will leave it as it is and put a thing in the user docs. Should we think of how to make a ticket to capture this idea of a higher level interface?

**Comment by FreddieAkeroyd** [comment]
I've had a go at adding it anyway as it is already "breaking the rules" by restarting the PV archiver on a begin ...

**Comment by FreddieAkeroyd** [comment]
To test:

The issue really shows itself when moving between seci and ibex, but it might be possible to simulate it as follows:

Before pull requests applied:

Add a block in ibex and run control limits to make it go out of range
begin a run  – this should go into a waiting state
Now stop the ISISDAE IOC (you'll need to toggle autorestart off)
Now remove run control on the block – the dae will miss the “in range” message as the ioc is shutdown
Start isisdae IOC – you should now be in a waiting state
Is you abort / begin again, you should still be waiting

After pull requests applied:

If you repeat above, the abort / begin should get you out of waiting
