### ISSUE TITLE
BLOCKSERVER: do not automatically push configs if on master

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1736]
If the settings/config/NDxxxx/  directory is on "master" do not push any configurations, this is to avoid junk accumulating on master which should be a reference base copy. Maybe raise an iocLog warning message too on startup if branch is "master"?

**Comment by DominicOram** [comment]
Unless I'm misunderstanding the ticket I think this is fixed by https://github.com/ISISComputingGroup/IBEX/issues/1446

**Comment by FreddieAkeroyd** [comment]
It is related, I wasn't sure if a solution had been decided for #1466 but the blockserver pushing on master is definitely wrong as it probably means a machine has been setup and a branch not created. Pushing only on machine name works for instruments, but i know of developers who have used their federal ID as the branch name not their computer name so it would stop them pushing changes

**Comment by DominicOram** [comment]
Will be covered by https://github.com/ISISComputingGroup/IBEX/issues/1446
