### ISSUE TITLE
Blockserver: error message on saving screens.xml

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1741]
The blockserver reports:

INFO: The configuration, Eurotherm, has been modified in the filesystem, ensure it is added to version control

I don't think it causes a problem but it should be fixed.

**Comment by AdrianPotter** [comment]
Expect this might be a consequence of #1500 and #1518

**Comment by AdrianPotter** [comment]
Fixed. No longer occurs
