### ISSUE TITLE
ED: RBNumber PV not set

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1743]
When the RB number is set in the GUI, it is written to %MYPVPREFIX%DAE:_RUNNUMBER. This should then be propogated to %MYPVPREFIX%ED:RBNUMBER. The SP is set properly but it doesn't make it into the read back. Please have a look into the logic and find out why this is. Notably USERNAME follows a similar pattern and does work.

For reference, the DAE DB can be found in:

```
C:\Instrument\Apps\EPICS\support\isisdae
```

and the Experimental Database db can be found in:

```
C:\Instrument\Apps\EPICS\ioc\master\INSTETC\INSTETC-IOC-01App\Db\experiment_data.db
```

The consequence of this bug (which has existed for a while) is that if the server is restarted, the current RB number will be lost

**Comment by FreddieAkeroyd** [comment]
"When the RB number is set in the GUI, it is written to %MYPVPREFIX%DAE:_RUNNUMBER. This should then be propogated to %MYPVPREFIX%ED:RBNUMBER."  I'm assuming you don't really mean _RUNNUMBER ?  It should write to DAE:_RBNUMBER:SP but i think we may need to look at the whole setup as i see that  there is a ED:RBNUMBER:DAE:SP -> DAE:_RBNUMBER:SP but is missing a PP on the link attributes so wouldn't work.

**Comment by AdrianPotter** [comment]
As in #1653, once this is fixed, update GUI to use `ED:RBNUMBER` and `ED:USERNAME` in DAE PVs rather than `DAE:_RBNUMBER` and `DAE:_USERNAME`
