### ISSUE TITLE
Hackathon: Move configure device screens into configurations

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1746]
As a user the device screen configuration is part of a configuration. It should be moved into configurations. Don't forget to hide it if the device screens perspective is hidden.

**Comment by John-Holt-Tessella** [comment]
Device screen configuration is activated with a button on the device screens remove this button (probably).

**Comment by KathrynBaker** [comment]
Isn’t that the button to allow for adding random OPIs outside of a configuration?
