### ISSUE TITLE
genie_python: Add g and inst to default script.

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1749]
On IRIS g is a modules containing all genie python commands and inst contains all instrument commands. Add this to the default ini that is run for all instruments so it is always available. Also find a way of importing all modules into inst instead of having to list them all individually.

**Comment by ChrisM-S** [comment]
Does the inst module contain commands only specific to iris and g commands applicable to all or is there another distinction to be made?

**Comment by John-Holt-Tessella** [comment]
See configs master branch in python for how this could work. Needs documenting; (After brain wave during Demo setup)

**Comment by John-Holt-Tessella** [comment]
Also there is a init_default.py in gennie python which I think always gets run (but checkis is needed)

**Comment by John-Holt-Tessella** [comment]
Do #1666 at the same time.

**Comment by kjwoodsISIS** [comment]
Need to roll back to LARMOR, IMAT, etc.

**Comment by Tom-Willemsen** [comment]
Be careful with LARMOR - existing scripts may break once this is complete. Will need to check all scripts very carefully on release.
