### ISSUE TITLE
Web Dashboard: Add timestamp to page

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1750]
With the page periodically updating (https://github.com/ISISComputingGroup/IBEX/issues/1676) it will be useful for users to see how old the data is on the page. Therefore a time stamp of when the data was taken would be useful. This could be a measure of instrument time when the data is pulled from the instrument

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/JSON_bourne/pull/7
