### ISSUE TITLE
Device screens (formerly Hackathon): Move list out of configurations

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1751]
As an instrument scientist, I want the device screens list to be independent of specific configurations so I can reuse them and open them independently of which configuration I'm currently in.

Please move the device screen list so that it is available per instrument, rather than per configuration

**Comment by AdrianPotter** [comment]
Make sure that the ability to add/edit/remove device screens on the global list is preserved

**Comment by John-Holt-Tessella** [comment]
Not sure if this is an error. Add an xml file to the device screens directory,you get

```
MAJOR: File Watcher: 'DevicesManager' object has no attribute 'delete'
MAJOR: File Watcher: None
```
