### ISSUE TITLE
Device screens (formerly Hackathon): Add device screens "on-the-fly"

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1752]
As a user, I want to be able to open an OPI "on-the-fly". I want to be able to add a device screen, view the OPI, and I don't want the screen to persist on the list of device screens associated with the instrument.

As a result of this ticket I should be able to create, edit and remove device screens during a single GUI session. When the GUI is restarted, the screens will no longer be available.

This shouldn't affect the capability to add screens to the global instrument device screens list.

**Comment by Tom-Willemsen** [comment]
After discussion with @AdrianPotter and @John-Holt-Tessella 

- Go with an extra column with a checkbox or similar to distinguish local vs remote device screens
- Make selection between remote and local a radio button
- Add icon(s) in dialog box and also in table
- Tooltip help in dialog
- Always be able to open edit dialong.
- PVs that you have read-only access to should be greyed out

**Comment by Tom-Willemsen** [comment]
Adding icons/tooltip help can be in seperate tickets, this ticket has a large enough scope already without those extra features.

**Comment by ThomasLohnert** [comment]
The icons in the device screens list look a bit horrible after automatic rescaling - could you please have a look whether there is a feasible alternative that yields higher quality results? If not, you can try making the original icon files small enough so they don't need to be rescaled by SWT.


![resize](https://cloud.githubusercontent.com/assets/18398579/23404710/41aef9cc-fdae-11e6-9dc3-ae8f92887dee.png)
(Left: original - right: after rescaling)

**Comment by Tom-Willemsen** [comment]
Fixed by making the icons 28x28 pixels natively.

**Comment by ThomasLohnert** [comment]
As a last step, please resolve the merge conflicts and add some appropriate entries in the manual system tests spreadsheet.

**Comment by Tom-Willemsen** [comment]
Merge conflicts fixed and manual system tests 28-3 to 28-5 added.
