### ISSUE TITLE
Device screens (formerly Hackathon): Add/edit/remove default device screen labels to a configuration

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1755]
As a user, I want the available device screens to be filtered based on the label(s) set in the configuration I'm using. I should be able to edit the filter and restore it to its default settings whilst using the device screens perspective. The filter would work by having preset labels (see #1754) that would be included in the device screens filter when a configuration is loaded

**Comment by KathrynBaker** [comment]
Closing along with the other labels for device screens tickets.
