### ISSUE TITLE
DAE reporting of Period and Raw frames / uah

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1762]
This need some lower level reworking, the current exposed methods only work when the period card is running in internal/external mode and do not work for software periods. Currently a summary is provided by the XML that gives raw and good frames for the period, but this probably is only correct for software periods

**Comment by Tom-Willemsen** [comment]
Fixed relatively recently in https://github.com/ISISComputingGroup/IBEX/issues/8499
