### ISSUE TITLE
GUI: DAE Title doe not display &

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1766]
reproduce 

1. Set the DAE title to &un
1. Click set
1. Title appears as un  (u becomes underlined)

It is treating the amp as a hotkey specifier.

**Comment by FreddieAkeroyd** [comment]
Does that mean if you set the title directly via the PV it works OK i.e. via

caput -S %MYPVPREFIX%DAE:TITLE:SP  "&un"

**Comment by John-Holt-Tessella** [comment]
This is not very reproducable; either way the `&` sign disapears

**Comment by Tom-Willemsen** [comment]
Test/functionality for the title is all ok.

![image](https://cloud.githubusercontent.com/assets/24375813/23941091/704ceb1a-095f-11e7-915d-0664e57eb991.png)

System test for users not passing because of the behaviour highlighted above.

**Comment by AdrianPotter** [comment]
A few changes to the system test requested
