### ISSUE TITLE
exp_data.py not coping with accents

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1768]
Found during testing, solution prototyped on the fly on developer system, the following will work to allow for accents in the experimental database:

in exp_data.py, updateExperimentID, there is a loop `for member in teammembers`, each of the str functions for fullname, org and role should be changed to unicode, the line `self.ca.caput(self._daenamespv, ",".join(surnames))` should be changed to self.ca.caput(self._daenamespv, str(''.join(c for c in unicodedata.normalize('NFD', ",".join(surnames))
                                                        if unicodedata.category(c) != 'Mn')))`

Some of the json encoding may need changing to `utf-8`

**Comment by AdrianPotter** [comment]
Looks ok but if we're trying to accommodate names with accents then UTF8 may not be sufficient. When trying to set the user to Sørina, a typically Danish name, then I get BLOCKSVR error: `'ascii' codec can't encode character u'\xf8' in position 1: ordinal not in range(128)`

**Comment by ChrisM-S** [comment]
I’m definitely not a specialist in UTF-8 but Unicode 0xf8 looks like it should be encoded in more than one byte in UTF-8 as the decimal equivalent (248) appears in the “invalid” section of the codepage of numbers for a single byte to appear in UTF-8. https://en.wikipedia.org/wiki/UTF-8#Codepage_layout
Chris

**Comment by FreddieAkeroyd** [comment]
@ChrisM-S 0xf8 is actually iso 8859-1 and is indeed an invalid single byte UTF-8 character where it should be represented as two bytes 0xc3 0xb8 - i believe 0xf8 would indicate a 3 byte character. So the error @AdrianPotter is seeing would indicate some incorrect character input and the uf8 -> ascii encoding is not working as it can't interpret the original utf8 correctly.

**Comment by FreddieAkeroyd** [comment]
0xf8 is a Unicode code point, equivalent to ISO-8859-1 and I'm guessing it was not decomposed by NFKD normalisation and hence caused the error. I've added a character translation table for the missing few I discovered, ultimately the python unidecode package may provide better features

**Comment by AdrianPotter** [comment]
Please add manual system tests

**Comment by John-Holt-Tessella** [comment]
I will do the manual system tests
