### ISSUE TITLE
IBEX: System Test ahead of Cycle 2016/04

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1771]
As a developer, I want to conduct comprehensive system testing of IBEX prior to cycle 2016/04 (15th November to 16th December), so that I can be confident that IBEX will run reliably on the instruments to which it is deployed.
#### Acceptance Criteria
1. Team is satisfied regarding the quality of IBEX.
2. Any recent issues reported by instrument scientists are resolved (or, if they can't be resolved, we understand why and can propose a workaround).
#### Post-Testing
1. NDXDEMO is updated with a tested, fixed version of IBEX server
2. LARMOR is updated with a tested, fixed version of IBEX server (do ticket #1610 first)
3. IMAT is updated with a tested, fixed version of IBEX server
4. IRIS is updated with a tested, fixed version of IBEX server
5. MUONFE is updated with a tested, fixed version of IBEX server
6. A tested, fixed version of IBEX client is made available to users
7. Record the version number of the build selected for release.
#### Notes
1. None (as yet)

**Comment by John-Holt-Tessella** [comment]
Release branch is now ready for release, it is V2.2.0. The build is running and should be avaiable on Monday 4th November .

**Comment by John-Holt-Tessella** [comment]
System testing sheet here https://docs.google.com/spreadsheets/d/1kfuzWAiUvQIOVRAn5IAANicrRlw_0_YReuOBLjJc5WY/edit?usp=sharing

**Comment by John-Holt-Tessella** [comment]
Done outcome is we are OK to proceed with the release.

**Comment by John-Holt-Tessella** [comment]
Updated LARMOR 
Updated IRIS

**Comment by mattclarke** [comment]
This has been done, so I am marking it as 'review complete'
