### ISSUE TITLE
Code duplication in TPG DB file

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1773]
The TPG has two sensors and currently there is much duplcaited code in the DB file EPICS-TPG/TPGSup/tpg26x.db to handle sensors 1 and 2, this duplication could be removed by using a DB template

**Comment by ChrisColeExpControl** [comment]
Completed by https://github.com/ISISComputingGroup/EPICS-TPG/commit/99556114d4eb93cc10b4feb2a5220bfc8c1c5542
