### ISSUE TITLE
IOC: BLOCKCACHE autorestart set to off problem

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1778]
During system testing  updated the config (I believe) then ran:

ocshow("VALUE1")
CA exception in thread w/o CA ctx: status=User specified timeout on IO operation expired file=src/_ca314.cpp line=1612: 
py_pend_ioCA exception in thread w/o CA ctx: status=User specified timeout on IO operation expired file=src/_ca314.cpp line=1612: 
py_pend_ioERROR: Unable to find PV IN:DEMO:CS:BLOCKSERVER:BLOCKVALUES
CA exception in thread w/o CA ctx: status=User specified timeout on IO operation expired file=src/_ca314.cpp line=1612: 
py_pend_io

When investigating the blockcahce (which serves this pv) it says:

[2016-11-08 11:14:49] IN:DEMO:CS:SB:TEST_INVISIBLE:RC:HIGH DOWN
[2016-11-08 11:14:49] IN:DEMO:CS:SB:VALUE1:RC:ENABLE DOWN
[2016-11-08 11:14:49] IN:DEMO:CS:SB:VALUE1:RC:LOW DOWN
[2016-11-08 11:14:49] IN:DEMO:CS:SB:VALUE1:RC:HIGH DOWN
[2016-11-08 11:14:49] Unexpected problem with CA circuit to server "NDXDEMO.isis.cclrc.ac.uk:54834" was "An existing connection was forcibly closed by the remote host. " - disconnecting

[2016-11-08 11:14:49] CA.Client.Diagnostic.................................

[2016-11-08 11:14:49]     Warning: "Virtual circuit disconnect"

[2016-11-08 11:14:49] Source File: ..\cac.cpp Line Number: 1215

[2016-11-08 11:14:49] .....................................................

[2016-11-08 11:14:53] 
[2016-11-08 11:14:53] @@@ Toggled auto restart to ON
[2016-11-08 11:14:54] 
[2016-11-08 11:14:54] @@@ Toggled auto restart to OFF
[2016-11-08 11:14:54] 
[2016-11-08 11:14:54] @@@ @@@ @@@ @@@ @@@
[2016-11-08 11:14:54] @@@ Received a sigChild for process 12528. Normal exit status = 1
[2016-11-08 11:14:54] @@@ Current time: 2016-11-08 11:14:54
[2016-11-08 11:14:54] @@@ Child process is shutting down, auto restart is disabled
[2016-11-08 11:14:54] @@@ ^R or ^X restarts the child, ^Q quits the server

The block server around the same time reports:

[Tue Nov  8 09:56:19 2016] INFO: Adding PV SYNOPTICS:A12345:GET
[Tue Nov  8 09:56:19 2016] INFO: Synoptic saved: A12345678901234567890123456789
[Tue Nov  8 09:56:19 2016] UPDATING SYNOPTIC MONITORS
[Tue Nov  8 10:46:41 2016] INFO: Stopping IOC EUROTHERM_01
[Tue Nov  8 10:46:45 2016] INFO: Stopping IOC GALIL_01
[Tue Nov  8 10:46:53 2016] INFO: Stopping IOC SIMPLE
[Tue Nov  8 10:46:57 2016] INFO: Stopping IOC TPG26X_01
[Tue Nov  8 10:53:06 2016] INFO: Synoptic saved: A12345678901234567890123456789
[Tue Nov  8 10:53:06 2016] UPDATING SYNOPTIC MONITORS
[Tue Nov  8 10:54:07 2016] INFO: Adding PV SYNOPTICS:VERY_L:GET
[Tue Nov  8 10:54:07 2016] INFO: Synoptic saved: Very_Long_Named_Synoptic_30chs
[Tue Nov  8 10:54:07 2016] UPDATING SYNOPTIC MONITORS
[Tue Nov  8 10:54:12 2016] INFO: Deleting: A12345678901234567890123456789
[Tue Nov  8 10:54:12 2016] INFO: Removing PV SYNOPTICS:A12345:GET
[Tue Nov  8 10:54:12 2016] UPDATING SYNOPTIC MONITORS
[Tue Nov  8 11:12:08 2016] INFO: Starting IOC SIMPLE
[Tue Nov  8 11:12:08 2016] Re-applying auto-restart setting to SIMPLE
[Tue Nov  8 11:12:09 2016] INFO: Toggling auto-restart for IOC SIMPLE
[Tue Nov  8 11:14:44 2016] Creating block: VALUE2 for SIMPLE:VALUE2
[Tue Nov  8 11:14:44 2016] Creating block: TEST_INVISIBLE for DAE:DAETIMINGSOURCE
[Tue Nov  8 11:14:44 2016] Creating block: VALUE1 for SIMPLE:VALUE1
[Tue Nov  8 11:14:44 2016] INFO: Reloading gateway
[Tue Nov  8 11:14:45 2016] INFO: Gateway reloaded
[Tue Nov  8 11:14:45 2016] UPDATING CONFIG LIST MONITORS
[Tue Nov  8 11:14:45 2016] INFO: Generating archiver configuration file: C:\Instrument\Apps\EPICS\CSS\master\ArchiveEngine\block_config.xml
[Tue Nov  8 11:14:45 2016] INFO: Running archiver settings uploader: C:\Instrument\Apps\EPICS\CSS\master\ArchiveEngine\set_block_config.bat
[Tue Nov  8 11:14:49 2016] INFO: Reusing the existing run-control autosave files
[Tue Nov  8 11:14:49 2016] INFO: Restarting IOC RUNCTRL_01
[Tue Nov  8 11:14:49 2016] INFO: Waiting for runcontrol IOC to start
[Tue Nov  8 11:14:49 2016] INFO: Runcontrol IOC started
[Tue Nov  8 11:14:49 2016] Unexpected problem with CA circuit to server "NDXDEMO.isis.cclrc.ac.uk:54834" was "An existing connection was forcibly closed by the remote host. " - disconnecting

[Tue Nov  8 11:14:49 2016] CA.Client.Diagnostic.................................

[Tue Nov  8 11:14:49 2016]     Warning: "Virtual circuit disconnect"

[Tue Nov  8 11:14:49 2016] Source File: ..\cac.cpp Line Number: 1215

[Tue Nov  8 11:14:49 2016] .....................................................

[Tue Nov  8 11:14:53 2016] UPDATING SYNOPTIC MONITORS
[Tue Nov  8 11:14:53 2016] MINOR: Unable to load devices file. [Errno 2] No such file or directory: u'C:\\Instrument\\Settings\\config\\NDXDEMO\\configurations\\configurations\\demo3\\screens.xml'. The PV data will default to a blank set of devices.
[Tue Nov  8 11:14:53 2016] UPDATING DEVICES MONITORS
[Tue Nov  8 11:14:53 2016] INFO: Restarting block cache...
[Tue Nov  8 11:14:53 2016] INFO: Restarting IOC BLOCKCACHE
[Tue Nov  8 11:14:53 2016] INFO: Toggling auto-restart for IOC BLOCKCACHE
[Tue Nov  8 11:14:54 2016] INFO: Saving active configuration as: demo3
[Tue Nov  8 11:14:54 2016] UPDATING CONFIG LIST MONITORS

On restart of the block server everything came back up and seems to be working.

I am not sure what to do about this options are:

1. Show the user the status of the blockserver, blockcache, dbserver etc so they are at least aware there is a problem
1. Create a watchdog which checks that all ioc which are meant to be up are up
1. Only set the autorestart if needed
1. In the block server ensure that on restart the restarted resource comes up
1. Fix the underlying issue (not sure what this is)

**Comment by Tom-Willemsen** [comment]
The block cache was removed in https://github.com/ISISComputingGroup/IBEX/issues/4136 - this ticket is no longer relevant.
