### ISSUE TITLE
GUI/IOC: Units are missing on angles and others in experiment details table

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1784]
Units are missing on angles and other values in experiment details panel. Check what these should be if blank record this in the test template. If not fix it.

Update manual system test 7-6 with a more specific idea of what the screens should look like

**Comment by KathrynBaker** [comment]
The tests have changed radically since this ticket was created, and this is not currently listed as something to be done.
