### ISSUE TITLE
Server: Remove old JSON_Bourne

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1786]
There's a copy of JSON_Bourne in inst_servers. Is this just an old redundant copy given there's now a dedicated repo? If so, please can it be removed

**Comment by AdrianPotter** [comment]
This adds the further question: Given the standalone git repo is updated more recently than the inst_servers version, how is JSON_Bourne distributed with EPICS? If instruments are using the inst_servers version it will be out of date. If we are supposed to be using the inst_servers version then why does the standalone repo still exist and why are we pushing changes to it.

**Comment by DominicOram** [comment]
There is actually a branch for this that was created as part of https://github.com/ISISComputingGroup/IBEX/issues/1675. It must have been missed when merging that ticket. As to the distribution JSON Bourne is deployed on the extaweb server as discussed at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard. This should potentially be made clearer.

**Comment by DominicOram** [comment]
PR is at https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/84
