### ISSUE TITLE
JSON_Bourne: Documentation please!

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1787]
As far as I can see, there is currently no developer documentation for JSON_Bourne. This means that when Dom and Thomas are out of the office, nobody knows how it works! Combined with ticket #1786 the instrument setup of the web server is opaque. We should not be in a situation where knowledge is restricted to specific parts of the team such that development cannot continue without them. Please make sure that the basics of JSON_Bourne are documented.

**Comment by DominicOram** [comment]
Documentation is here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard. Granted, it wasn't obvious how to get to it and it's ever so slightly out of date (the diagram especially). This ticket should be used to fix this.

**Comment by DominicOram** [comment]
Documentation should now be clearer and linked to from the homepage

**Comment by AdrianPotter** [comment]
Thanks for linking. After reading the documentation I am unclear on:

- How to update the extweb. Presumably it has a machine name and standard network credentials?
- How to run the server locally for developer purposes. Is it a case of starting the server and then navigating to `localhost:60000/default.html?instrument=NDW[INST]`? It'd be good if that was explicit

**Comment by DominicOram** [comment]
Updated docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard. This also now links to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#add-instrument-to-ibex-web-dashboard.
