### ISSUE TITLE
Blockserver: IOC not stopped on config load if originally in recsim mode 

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1789]
1. Create a configuration with an IOC in rec sim mode (not auto restart ot auto start)
1. Start the ioc
1. Switch configuration without IOC in
1. Check IOC is stopped

IOC is not stopped and should be. It appears that the IOC is stopped if it is not in recsim mode in the original configuration.

**Comment by AdrianPotter** [comment]
Fixed by #1789?

**Comment by AdrianPotter** [comment]
Confirmed
