### ISSUE TITLE
Doc: Add how to replace a sensor

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1791]
As a support technician I want to know how to add a new sensor calibration file temporarily to an instrument without the official calibration files custodian being involved.

I.e. if a sensor breaks on Saturday and John Bones has a new sensor and calibration file he needs to know how a visiting scientist can use this file straight away without have to ring up Kathryn.

This should include the step where the support technician informs the file custodian that a new file is available for calibration.

**Comment by KathrynBaker** [comment]
We can write this doc, but I will say that this is a highly unlikely scenario. Usually the sensors are calibrated in batches, and passed to me to upload before they will be used on the beamline. The original calibration files are also in the wrong format, so as well as the simple things like “where do I put this” there needs to be the instructions for how it is changed to be compatible. So maybe a set of instructions for “I know it should be there, but I can’t find it” – which would be best started with doing a git pull, and then the “The user brought this sensor, and wants to use this calibration file, what do I do” which would have the modifications, and include an instruction of sending me the modified file if it needs to be kept in our systems.

BTW, thanks for the new title, I’m not sure I’d have ever considered myself a “calibration file custodian”…

**Comment by KathrynBaker** [comment]
When consulted, the SAG felt that this process was easy enough to understand, and so this was not likely to be necessary.
