### ISSUE TITLE
IBEX Client: .msi installer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1800]
As a support person, I would like the IBEX Client to be installed via a .msi installer, to simplify the installation process for end-users.

#### Acceptance Criteria
1. IBEX client can be installed by double-clicking on a .msi installer.
1. The .msi installer installs:
   1. The IBEX client
   1. genie_python

#### Notes
1. It would be helpful if the installer could also check if the PC meets the pre-requisites:
   1. Java 8 (update 101 or later)
   1. Windows 7 (Professional or Enterprise), Service Pack 1 (or higher), or Windows 10 (Professional or Enterprise), Build 10586 (or higher).
   There is no need for the installer to attempt to install any pre-requistites, merely that it should warn the user that his PC does not meet the pre-requisites.

**Comment by FreddieAkeroyd** [comment]
Covered by #1994

**Comment by KathrynBaker** [comment]
Not only was this covered by #1994, the pre-requisites are now far out of date, and an msi installer is created, although it may just be for the client that should be plenty - I'm calling this ticket closed.
