### ISSUE TITLE
IMAT: Attenuator error intermitently

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1801]
The attenuator connected to the FINS appears to go intermittently disconnected. 

```
IN:IMAT:ATTEN:OPEN             2016-11-14 14:02:14.642907 YES SCAN INVALID
IN:IMAT:ATTEN:OPEN             2016-11-14 14:02:20.044054 YES
IN:IMAT:ATTEN:OPEN             2016-11-14 14:02:20.044054 YES SCAN INVALID
IN:IMAT:ATTEN:OPEN             2016-11-14 14:02:25.246822 YES
IN:IMAT:ATTEN:OPEN             2016-11-14 14:02:25.246822 YES SCAN INVALID
IN:IMAT:ATTEN:OPEN             2016-11-14 14:02:30.446971 YES
```

This behaviour only recently occurred after starting to measure the pressures  through the FINS. If the pressure is disconnected then the scan invalid error disappear. There are no erors for the pressures that we could see.

This is on IMAT found by Gareth.

**Comment by FreddieAkeroyd** [comment]
OK, I think it means the attenuator is scanning too quickly - it is set at .1 seconds which looks like it was fine before we started reading the pressures, now it must be taking more that .1 seconds on average as it has to wait behind pressure reads sometimes. We just need to increase the scan time say to .5 seconds, or if Winfried needs it at .1 maybe we need to drop the scan rate on the pressures.

**Comment by FreddieAkeroyd** [comment]
Dropping scans on pressures was not enough, it looks like 0.1 seconds is a struggle with the way it is currently written (it does 3 separate reads). I've recoded it to do one read and split the answer, but need to test on IMAT.

**Comment by GDH-ISIS** [comment]
Short term fix implemented on IMAT. PLC can accept multiple connections.
Used FINS_01 to cater for the attenuator
Used FINS_02 to cater for the PLC plc pressures (from the TPG pressure gauges)
Appears to now be operational. This may not be the long term solution.

**Comment by FreddieAkeroyd** [comment]
I've added my changes via PR for testing

**Comment by John-Holt-Tessella** [comment]
I can test this on Monday but it involves pointing at IMAT with the FINS. I am not doing that on Friday afternoon.
