### ISSUE TITLE
GUI Configurations: Selecting a group causes pop up

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1803]
To reproduce:
* Right-click edit a block
* Close the Block Configuration Dialog
* Select a group in the group tab
* The block configuration dialog reopens, this is incorrect behaviour

**Comment by AdrianPotter** [comment]
Fixed by #1807

**Comment by AdrianPotter** [comment]
Fixed by #1807. Setting impeded until that ticket is merged
