### ISSUE TITLE
GUI: Monitor and update Units in Blocks

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1805]
The units in a block are not updated if the PV's units are updated.

A good example is the TPG26x. Set up a block pointing at the pressure. Observe the value, change the units. The units do not change on the block.

The problem is that the units and set on connect only. I have tried to solve this as part of the timeboxed ticket https://github.com/ISISComputingGroup/IBEX/issues/1655 by:

1. Setting flag in the PVManager (flags to look at dbe_property and others). See post http://www.aps.anl.gov/epics/tech-talk/2016/msg01150.php.
2. Create a second PV which attaches to the EGU field. The fails because some record, like the motor velocity, do not have the EGU set by this value; also `BLOCKPV.EGU.EGU` resolves to a value which doesn't help.

The only other idea is to add a reconnect of the PV activated either by a button or automatically.

This issue is not a huge problem because very few IOC change their units without having a configuration reloaded.

**Comment by DominicOram** [comment]
Revisit this in E4, it may be better (https://epics.anl.gov/tech-talk/2016/msg01152.php)

**Comment by DominicOram** [comment]
I tried this out. It works on OPIs locally but is flaky at best when going through a gateway. It does not immediately work for blocks but I think once the gateway issue is resolved we could get it working on blocks. I have sent a message on tech talk re the gateway issue.

**Comment by John-Holt-Tessella** [comment]
See also #4019 for crude fix

**Comment by DominicOram** [comment]
Fixed with 2nd option in https://github.com/ISISComputingGroup/IBEX/issues/4019. Closing this is a duplicate.
