### ISSUE TITLE
GUI: Edit block cancel x2

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1807]
If you right-click on a block and select "Edit block" then click "Cancel" the dialog disappears and then reappears, so you have to click "Cancel" again.

The same thing happens for "OK" too.

**Comment by DominicOram** [comment]
Potentially related to https://github.com/ISISComputingGroup/IBEX/issues/1803 ?

**Comment by mattclarke** [comment]
Just for booking keeping purposes: this overrides the behaviour described in: https://github.com/ISISComputingGroup/IBEX/issues/893

Namely `Right clicking on a block should bring up the same edit block dialogue as in the config editor.`

**Comment by DominicOram** [comment]
It does but I would still say this solution is neater. It's certainly more maintainable and less error prone. I don't think the additional pop-up that we had previously adds anything to the UX. What do you think?

**Comment by DominicOram** [comment]
Also, I think the reason that #893 proposes this solution is that it was prior to us having a separate block editing dialog, it was previously all integrated into the tab on the edit config dialog.

**Comment by mattclarke** [comment]
I wasn't saying it was - we just need to keep track of when one ticket overrides another.

**Comment by mattclarke** [comment]
TBH: I have never thought the "edit block" right-click adds value, if anything it confuses the work-flow for the user.

**Comment by mattclarke** [comment]
E.g. Will it be a nice or terrrible surprise to the users that clicking 'OK' on the edit block dialog leads to all the IOCs being restarted?

**Comment by DominicOram** [comment]
I think that's a separate issue. There is no reason to restart IOCs in the case of a block or group being changed, right? Therefore we should change it so that the IOCs don't get restarted, not so that users can't get to the screen.

**Comment by mattclarke** [comment]
There is no indication to the user that click 'OK' causes the configuration to be changed - that was the point I was making. The IOCs were just a stupid way of showing that.

**Comment by mattclarke** [comment]
Telling a user that they have to go through certain steps to edit a configuration except for when it is a block in which case there is a short-cut seems a bit odd to me.
