### ISSUE TITLE
DAE: Error in Spectra Plot Axes

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1808]
Ian Silverwood & Sanghamitra Mukhopadhyay on IRIS have noticed a bug in the drawing of the axes in DAE spectra plots.  The attached screenshots illustrates the problem.  The y-axes of the two lower plots are incorrectly labelled.  

On the plot on the left of the screenshot, the scale labels are not equally spaced.  The gap from 1 to 2 is much smaller than the gap from 0 to 1 and from 2 to 3.

On the plot on the right of the screenshot, the scale labels are incorrect.  The label is always 1 (this might be a rounding problem - e.g. 1.1 and 1.2 will both round to 1).
![wp_20161114_001](https://cloud.githubusercontent.com/assets/7249337/20302373/e3f33e06-ab1e-11e6-9e20-273467cb9c48.jpg)

**Comment by DominicOram** [comment]
Unlikely to be seen again as this is now handled by CSS
