### ISSUE TITLE
Device Screens: Can save "blank" devices

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1810]
When adding or editing device screens, it is possible to save a screen without a target device. If the user then selects it from the list, an error is displayed (see below).

Add a check and disable the confirmation button in the dialog for editing device screens if one or more screens do not have a target device set.

![untitled](https://cloud.githubusercontent.com/assets/18398579/20304380/c8aab4f4-ab27-11e6-8780-83bd88c7d5bf.png)

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/386

**Comment by AdrianPotter** [comment]
Please add a manual system test
