### ISSUE TITLE
Vesuvio: IOC & OPI for Keithley 2400 Source Meter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1826]
As a scientist, I want support for a Keithley 2400 Source Meter in IBEX, so that I can measure electric fields in my experiments.

#### Acceptance Criteria
1. I can use the IBEX GUI to control the Keithley 2400 Source Meter.
1. I can use genie_python to control the Keithley 2400 Source Meter.

#### Notes
1. For more details see (see [Vesuvio](https://github.com/ISISComputingGroup/IBEX/wiki/VESUVIO-Instrument-Details#noteKeithley) )

**Comment by kjwoodsISIS** [comment]
Copy the existing VI.
Create an emulator too.

**Comment by FreddieAkeroyd** [comment]
There looks to be some existing EPICS support

http://www.aps.anl.gov/epics/tech-talk/2014/msg01381.php
http://www.aps.anl.gov/epics/tech-talk/2014/msg01387.php

**Comment by John-Holt-Tessella** [comment]
Practice Keithly requested

**Comment by AdrianPotter** [comment]
Setting to impeded until it can be tested on a real device

**Comment by AdrianPotter** [comment]
Moving back to impeded. @davidkeymer kindly brought us a physical device but on switching on we think it's burnt out (the display doesn't come on and there's a rather strong smell)

**Comment by AdrianPotter** [comment]
We got a new one and it seems to be ok. I'll begin testing.
