### ISSUE TITLE
Vesuvio: IOC & OPI for Neocera LTC-21 Temperature Controller

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1828]
As a scientist, I want support for a Neocera LTC-21 Temperature Controller in IBEX, so that I can measure and control the temperature in my experiments.

#### Acceptance Criteria
1. I can use the IBEX GUI to control the Neocera LTC-21 Temperature Controller.
1. I can use genie_python to control the Neocera LTC-21 Temperature Controller.

#### Notes
1. For more details see (see [Vesuvio](https://github.com/ISISComputingGroup/IBEX/wiki/VESUVIO-Instrument-Details#noteNeocera) )
1. Presumably LTC means low-temperature controller
1. Judging by Neocera's web-site, they seem to have changed the nature of their business.  The LTC-21 may no longer be in production.

**Comment by kjwoodsISIS** [comment]
Pair up with someone to share knowledge of writing emulators.

**Comment by kjwoodsISIS** [comment]
Matthew Krzystyniak has confirmed that the VESUVIO team wants to use the Neocera device.

**Comment by DominicOram** [comment]
Generally works very well, minor issues that can be left if deemed unnecessary
