### ISSUE TITLE
GUI: What happens when there are spaces in the Eurotherm calibration file

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1830]
1. Start a Eurotherm
2. Enter a valid calibration file preceded by a space
3. What happens?

Ian reported an issue on Iris with the Eurotherm. The logs had the following error:

```
sevr=fatal initConversion(IN:IRIS:EUROTHERM1:A01:TEMP): configuration error: File C:/Instrument/Settings/config/common/temp_sensors/ E217.txt is not a valid 1-parameter table
```

We need to investigate what happens when someone accidentally leaves a rogue space in the calibration file text box. Does it flag an error (i.e. red border)?

**Comment by kjwoodsISIS** [comment]
Could we not just check for the existence of the file when the user enters a new file name?  If it doesn't exist, display an error dialog, with a hint to tell the user to check for things like unintended spaces.

**Comment by FreddieAkeroyd** [comment]
The file is on a remote system, so we would need to provide a separate "file check" service for this feature on e.g. the blockserver which could be useful elsewhere. In this case we control the names of calibration files and know that they cannot contain spaces (and may know a few more client side rules we could apply too). But a file check service may be something to consider for another ticket.

**Comment by kjwoodsISIS** [comment]
OK, in the short-term, we can limit the likelihood of this problem occurring by checking for the existence of spaces in the file name (because we know they should not exist).  I will create a new ticket to manage the creation of a "file checking" service in the Blockserver.

**Comment by AdrianPotter** [comment]
Marking as complete:

1. Ticket #1841 covers file checking
2. An error for a non-existent file is displayed as per ticket #1856
