### ISSUE TITLE
Architectural: Review the security of IBEX

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1831]
What are the security issues in IBEX? What is the required level of security? What are the components we control?

This should be documented.

**Comment by John-Holt-Tessella** [comment]
Include in this:

* Public/private repos including list
* ActiveMQ connections
    * iocLogs
    * Alarm client/inst
    * script server admin/client
* mySql schemas

Probably takes the form of a document with list of things (like architectural picture) and then a meeting to discuss the risk and mitigation strategy of each item.

**Comment by John-Holt-Tessella** [comment]
See #95 and #1838 too.

**Comment by kjwoodsISIS** [comment]
1. Meet to discuss
2. Document our views, findings, plans

**Comment by John-Holt-Tessella** [comment]
Add issue to security slack channel

**Comment by kjwoodsISIS** [comment]
Meeting was held on 6th January 2017, 11:00 - 12:00.
We didn't cover all the ground we needed to cover.  So, close this ticket and open a new one for the follow-up meeting (see #1958)
