### ISSUE TITLE
GUI: Runcontrol gets out of sync?

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1832]
When demoing the system we found that the configuration can be changed while a run is in progress. If this happens blocks newly under run control do not update (i.e. they don't get ticks) and the runcontrol dialogue does not reflect the new configuration. Check out what of this is important and wrong.

Q1) Should the configuration be changable when the experiment is running?

**Comment by mattclarke** [comment]
Yes - it might be that something has gone out of range slightly (e.g. methane temperature) which isn't able to be rectified and the user decides they are happy to carry on taking data even though things are not perfect.

**Comment by KathrynBaker** [comment]
Not seen this bug reported from a user, closing as the behaviour is now long standing
