### ISSUE TITLE
GUI: links to user manual and genie docs

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1839]
Add the following links:
* link to user manual from weblinks perspective
* link to user manual from Help menu
* link to genie python documentation from weblinks perspective

**Comment by IsabellaRey** [comment]
NOTE: in the weblinks perspective the GUI only points at this page:
http://dataweb.isis.rl.ac.uk/SeciLinks/default.htm

which contains all the other links. The GUI parses this page to extract the links and display them.

This seems specific to SECI. Need to discuss what the best way forward is

**Comment by ThomasLohnert** [comment]
Has the above been discussed? We could just set up a copy of that page for IBEX and add the IBEX specific stuff like the user manual and such in it (none of the links currently on that website are SECI specific in themselves as far as I can see)
