### ISSUE TITLE
MUONFE: Fix barndoors OPI

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1840]
At the moment the Barndoors OPI does not connect to the correct PVs:

1. The Momentum Slit Gap references `MOMENTUMSLITS' PVs. This should be `MSLITS`.
1. If you go to the motor details panels (click the + button) then none of the PVs are connected. On inspection, all of the PVs contain `MOT:MOT:` so have a duplicated motor prefix.

Please fix.

**Comment by KathrynBaker** [comment]
This should be done after #1424 is complete, which would be something to consider in the January shutdown due to availability of equipment.

**Comment by John-Holt-Tessella** [comment]
Also updated to the new style

**Comment by John-Holt-Tessella** [comment]
Checked with Kathryn it looks like 1424 does not have to be done to do this.
