### ISSUE TITLE
Blockserver: file check service

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1841]
As a developer, I want the Blockserver to provide a file check service, so that the IBEX client can check the attributes of files on the control server (e.g. does a file specified by the user exist?).

#### Acceptance Criteria
1. I can pass a filename to the Blockserver file check service.
1. The Blockserver returns a set of attributes for the named file.

#### Notes
1. It is up to us to determine the file attributes that it would be useful for the Blockserver to return.  These could include:
   1. existence
   1. file size
   1. read-write status
   1. time & date stamps (creation, last update, last access)

There may well be other attributes that might be useful.

**Comment by DominicOram** [comment]
Note: This probably shouldn't be part of the blockserver but rather an entirely separate service (though potentially within inst_servers).

Also, due to the fact that you can't do send/response in EPICS this could be very tricky...

**Comment by FreddieAkeroyd** [comment]
You are right in general, but I think with a channel access server (which is what pycaspy is) you can do send/response. However channel access is not necessarily what we need to do here, this could be classed outside of  instrument control and just done via a web URL.

**Comment by DominicOram** [comment]
The NICOS team are looking into something similar to this. We should see if we can work together on it
