### ISSUE TITLE
ZOOM Detector Monitoring: Emulator and IOC for Nanodac

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1843]
The Detector temperature monitoring system being planned for ZOOM will use a Nanodac http://www.eurotherm.co.uk/products/recorders/graphic/nanodac

This will be used to measure the temperatures, and is an ethernet device, and is made by eurotherm. It is a modbus device from the brief look I have had, so shuld not be a problem to integrate to EPICS.

**Comment by kjwoodsISIS** [comment]
ZOOM team have yet to purchase a Nanodac.
Write an Emulator first.

**Comment by John-Holt-Tessella** [comment]
Confirm whether this is a modbus or ethernet cevice

**Comment by KathrynBaker** [comment]
Have said we would prefer the Ethernet, but can cope with Modbus, so it is likely to be whichever of those options is the cheapest. Once known for certain I will confirm it.

**Comment by DominicOram** [comment]
Matt Pearson has written an IOC/OPI for the Modbus TCP version, which he has sent to me.

**Comment by DominicOram** [comment]
Created a ticket within plankton to create a modbus tcp interface (https://github.com/DMSC-Instrument-Data/plankton/issues/160)

**Comment by DominicOram** [comment]
Lewis' MODBUS support is now sufficient to test that the OPI is working as expected. Awaiting actual hardware.

**Comment by DominicOram** [comment]
OPI not needed as only picking up values for Nagios. Will create another ticket for OPI

**Comment by mattclarke** [comment]
Closed by mistake

**Comment by mattclarke** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/2196
