### ISSUE TITLE
Serve up data that will be used in a DAE "run diagnostics 2" page

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1846]
This page allows the scientist to rapidly see which detectors are counting and which are not counting, they can filter by "show only zero" and "show only non zero" counts and also see count rates. It is often used at the start of cycle and for fault finding. Instruments can have thousands of detectors, so using blocks is not feasible and would not really be useful as in most cases the value is not needed during normal operation.

**Comment by kjwoodsISIS** [comment]
Needs some investigation.  Create an investigation ticket (1 point) to do first.

**Comment by mattclarke** [comment]
Having talked to Freddie, we have decided it will be easier just to send a waveform from the DAE.
The DAE data is already shown in a custom GUI rather than an OPI, so we can format the data how we like.

**Comment by ChrisM-S** [comment]
I realize I wasn’t in the discussion of this, so apologies if I go over ground already covered.

It might be worth keeping an eye on the bandwidth issue in highlighted in

#1652 (IBEX Client network load possibly needs control for remote and or WIFI clients)

Would more channels are being summed give a heavier the network load to the machine running the client or would the DAE IOC do the scaling based on  the channels requested – but what about multiple clients asking for different information.

Actually could the #1652 problem be related to the stopped histogram displays?

**Comment by DominicOram** [comment]
This is for the backend only, front end will be done in https://github.com/ISISComputingGroup/IBEX/issues/2054. Reducing effort to 1.

**Comment by AdrianPotter** [comment]
![image](https://cloud.githubusercontent.com/assets/10273443/23663453/7dbb6b0c-034a-11e7-846e-a378e2a13d49.png)

**Comment by FreddieAkeroyd** [comment]
@AdrianPotter I should work with you on the actual DAE panel
