### ISSUE TITLE
Excessive CaPut log information on moving motors

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1847]
We trap all CA PV writes using CAPutLog and send these to out IOC message logger at an "Info" level. Our central "motors is moving" PV is also caught by this scheme, resulting in e.g. many CHANGED PV: IN:IMAT:CS:MOT:MOVING.E messages in the log. These should be removed.

**Comment by KathrynBaker** [comment]
Removing under review label as my IBEX server isn't behaving I don't want to delay a review because of that
