### ISSUE TITLE
Blockserver: Serve macros from globals.txt

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1849]
For the GUI to know what macros are in globals.txt (https://github.com/ISISComputingGroup/IBEX/issues/1612) it must be served in a PV. The blockserver seems like a good place to do this.

Make sure that when globals.txt is modified the PV is updated.

**Comment by John-Holt-Tessella** [comment]
Moved to #3396 to make it a vertical slice.
