### ISSUE TITLE
GUI: Display group history

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1851]
As a user, I would like to show the history of all blocks in a group with a single click. Currently I can only do it for blocks. When right clicking on a group, as well as getting the show/hide hidden blocks option, the popup should also have an option to show the group history. When clicked, it would bring up a log plot with a plot containing the history of all blocks in the group.

**Comment by kjwoodsISIS** [comment]
Sounds like a good idea.  What would happen if the block is a text value or a boolean?
![image](https://cloud.githubusercontent.com/assets/7249337/20604977/fe424fc4-b260-11e6-8497-e708c4fb205f.png)

**Comment by GRyall** [comment]
Somewhat assumes that all blocks in a group have comparable units. No specific use case or request is presented - I am not convinced this development is worthwhile

**Comment by KathrynBaker** [comment]
I agree, this is no longer applicable as it has not been re-requested, and you are able to add blocks to existing plots.
