### ISSUE TITLE
GUI/IOC: Make error on non-existant calibration file obvious

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1856]
As a user if I pick a non-existent calibration file, because I have an extra space or have transposed some numbers, the GUI needs to make me aware of this with an error message stating that the file can not be found.

This has caused experiments to stall. Let Sanghamitra Mukhopadhyay know when this is done.

**Comment by kjwoodsISIS** [comment]
See also #1841.

**Comment by kjwoodsISIS** [comment]
Alternatively, give the user a list of files (therefore, no scope for typos).
