### ISSUE TITLE
Build: Install/check genie_python

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1858]
The build system should install the correct version of genie_python when running the build.

**Comment by mattclarke** [comment]
Not really how to test this beyond forcing genie_python to build and checking that it also causes this to build.
I guess you could check that the genie installation on NDWVEGAS is updated.

**Comment by DominicOram** [comment]
This works as intended but can we also kick off a build on reno at the same time? Just in case we start doing genie-python dependent things on there too. Quick google shows that maybe https://www.quora.com/How-can-I-run-a-single-job-parallely-on-multiple-Jenkins-slave might help?

**Comment by mattclarke** [comment]
In theory Reno should get a clean install of everything before the system tests start.

Which it appear not to so I will create a ticket for that.

**Comment by FreddieAkeroyd** [comment]
The system tests do install the latest genie python on reno, but in jenkins.bat rather than get_latest_builds.py

Currently previous builds of genie python are not kept, moving the copy from jenkins.bat to using get_latest_builds.py would make this easier to handle if/when it happens
