### ISSUE TITLE
IOC Inhibitor: Disable a record

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1864]
To enable us to limit the setting of a PV we need to disable a PV. This ticket is to investigate how to do this. The suggested step is to set the disable link record from pointing at the disable of the device to point at another record without changing the DB file if possible). 

See docs https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor. 

Acceptance Criteria:

1. A set of steps which stops a user from setting the voltage of a CAEN.
1. A set of steps which stops a user from moving a motor (simulate Galil will do)

**Comment by FreddieAkeroyd** [comment]
Disabling a record disables scanning, there are other options that we can consider if need be which are to use access control to disable writes or to use the DISP field to disable external channel access puts. If you disable the motor record for example, does it stop updating its readbacks?

**Comment by ThomasLohnert** [comment]
For review: edited the "Disabling a group" section on the wiki page: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor
