### ISSUE TITLE
Ibex Server and SECI Interactions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1871]
In amongst the stop_ibex_server.bat there are commands to kill SECI. This means on SANS2D we can't easily add it to the startup menu as if SECI starts first it would kill it. However on IRIS this might be handy.

A few things to consider:
* Should IBEX be killing SECI? Or are the systems separate enough that we can decouple them completely?
* Should the automatic stop_ibex_server.bat in start_ibex_server.bat be parameterised? Default would be to run the stop, but then a bat script could be run on computer startup that just calls start_ibex_server.bat with the appropriate parameter so that the stop doesn't happen.
* Does the mini startup actually work as we expect it to? The implication in the stop_ibex_server.bat is that the various taskkills should be skipped, but this is not what happens on SANS2D - does that logic just need correcting somehow, or has there been a mistake in setup?

**Comment by John-Holt-Tessella** [comment]
Booked meeting for 5th Jan at 10:30 after standup

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Startup-and-Shutdown for extra info

**Comment by FreddieAkeroyd** [comment]
SANS2D is running an old version of the stop script (stop_inst) that will kill seci every time - the one currently in Git (stop_ibex_server) has logic to prevent this

**Comment by John-Holt-Tessella** [comment]
See #1950, #1951, #1952 and #1953 and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Startup-and-Shutdown.

**Comment by John-Holt-Tessella** [comment]
Assumed that people have read and are happy moving to review complete
