### ISSUE TITLE
System Tests: Look into rescoping them

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1876]
Currently the RCPTT system tests are pretty much useless. We should rescope them to make them stable. A large part of the instability comes from restarting the blockserver. This can be fixed by either:
* Only starting the blockserver at the beginning of the tests, rely on each test properly cleaning itself up (this will mean tests are no longer independent)
* Removing the blockserver from the tests all together, only use RCPTT for testing pure GUI functions.

**Comment by AdrianPotter** [comment]
The system tests are now stable. I don't think rescoping is necessay
