### ISSUE TITLE
ZOOM: Commission the PGC motor settings

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1879]
As well as the axes setup (which should be done as part of #1233, but if that ticket is still outstanding should be done here), the motor setup is needed for the Polariser, Guide and Collimation Unit on ZOOM. This would be the particular setups, and the tweaking of setpoints in the position file for the device.

**Comment by KathrynBaker** [comment]
With help from Gareth this is now partially commissioned, in that we have a lot of numbers, and just need to finish the port of the data into IBEX and verify behaviour.

**Comment by KathrynBaker** [comment]
This is on the whole complete, the numbers as calculated by the motion control team have been input and the axes configuration is done.

The numbers are not necessarily correct to the neutron beam, but for the PGC (and the jaws) those positions are needed from the Instrument Scientists - these values may now be available, and I will confirm this, at which point we can apply homing sequences and positions as required (which should take about 30 minutes).

Moving this to the backlog and awaiting as we can do no more without that information.

**Comment by DominicOram** [comment]
Are we happy this is done or are we folding the stall error into this ticket?

**Comment by KathrynBaker** [comment]
Stall error is ticket #3015, so this is probably done.

Regards,
Kathryn

**Comment by DominicOram** [comment]
Ok, I think enough of us looked at it that I'll put it straight into review complete
