### ISSUE TITLE
ZOOM: Commission the DMS motor settings

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1880]
As well as the axes setup (which should be done as part of #1236, but if that ticket is still outstanding should be done here), the motor setup is needed for the Detector Motion System on ZOOM. This would be the particular setups, and the tweaking of setpoints in the position files for the device.

**Comment by Tom-Willemsen** [comment]
@KathrynBaker to review this

**Comment by KathrynBaker** [comment]
All seems to be fine, so marking this as done.
