### ISSUE TITLE
PCASPY: diagnose startup issue

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1882]
Kathryn is having trouble starting the blockserver, traced to an issue in pcaspy but need a version with debug symbols to get much further.

**Comment by FreddieAkeroyd** [comment]
three different builds of pcaspy placed in \\isis\inst$\Kits$\CompGroup\ICP\pcaspy for test (see README.txt) – they all have debug symbols, but are not compiler debug builds as that requires a debug build of python (using python27_d.dll) which we don’t currently have for genie-python. I think that would be worth us creating such for the future though (#1883). Hopefully one or two of the builds work. I’m hoping “static_with_undef” crashes as that is my nearest attempt at what I think it currently is (though I have applied the fix described in https://github.com/paulscherrerinstitute/pcaspy/issues/25 to our epics base), “static” and “dynamic” are a (hopefully fixed) static build and a DLL (as in linked to bundled epics DLLs) build.

**Comment by FreddieAkeroyd** [comment]
Original crash is in MSVCR90.DLL with traceback to _cas.pyd

**Comment by KathrynBaker** [comment]
A quick update in the ticket records of what was found. Using versions of pcaspy that had been built by Freddie I had no trouble using python within my IBEX server. static_with_undef worked, as did the static_with_undef_old_base. I now have a workaround, but we are not yet able to define the actual issue.

**Comment by FreddieAkeroyd** [comment]
Problem located - NI process taking exclusive access of EPICS port http://www.aps.anl.gov/epics/tech-talk/2017/msg00077.php EPICS base has been patched, official pcaspy with new version will be installed when available
