### ISSUE TITLE
Debug version of genie_python

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1883]
This would be useful for debugging, it is a version build against python27_d.dll rather than python27.dll

**Comment by GRyall** [comment]
Given we have moved to Python 3, this seems unlikely to still be required. Can be reopened if I am incorrect.

**Comment by FreddieAkeroyd** [comment]
The same applies to python 3 but may become easier when we move genie python to a pip installable package
