### ISSUE TITLE
System testing: Refactor test list into stories

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1886]
Currently, the manual system testing is an Excel spreadsheet with a rapidly growing list of tests.

Much of the effort expended in these tests is duplicated, for example:

- Add a synoptic
- Add a synoptic then edit it
- Add a synoptic then delete it

As a tester, I would like the manual system tests could be arranged into a set of stories so I could run through them faster.

The stories should try and balance keeping the stories limited to individual components (e.g. synoptics) so that they don't get excessively long and can be partitioned between multiple developers whilst at the same time minimising code duplication.

**Comment by kjwoodsISIS** [comment]
Possible ticket for Morgan

**Comment by AdrianPotter** [comment]
We've made good progress automating our other tests
