### ISSUE TITLE
LARMOR: Danfysik 9100 - check EOL characters

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1887]
Rob has reported a problem communicating with a Danfysik 9100 on LARMOR.

Initial investigation seems to indicate that there may be a problem with the end-of-line (EOL) characters.  Please check the Danfysik manual to determine the correct EOL characters and then check the IOC to ensure that the implementation is correct.

**Comment by kjwoodsISIS** [comment]
Some background information:
> From: > Facilities IT
> Sent: 05 December 2016 22:09
> To: Dalgliesh, Robert (STFC,RAL,ISIS)
> Subject: INSTRUMENT (LARMOR): Computing: Sample environment/Device Control: Danfysik 9100 IOC ... ISSUE=67593 PROJ=15
> 
> [Duplicate message snipped]
> Entered on 05/12/2016 at 22:09:20 GMT (GMT+0000) by Akeroyd, Freddie:
> According to the manual: Default setting is “9600Baud, No party, 8 Bits, 1 Stop bits” for local and “115200Baud, No party, 8 Bits, 1 Stop bits” for remote line. SDTEST is using 1 stop bit, the IOC is using 2 stop bits, the power supply can be configured to use either 1 or 2 stop bits. I’m not sure if it means anything, but just a difference I spotted 
> 
> Freddie 
>
> From: Facilities IT
> Sent: 05 December 2016 22:02
> To: isisinstrument@sparrowhawk.nd.rl.ac.uk
> Subject: INSTRUMENT (LARMOR): Computing: Sample environment/Device Control: Danfysik 9100 IOC ... ISSUE=67593 PROJ=15
> 
> [Duplicate message snipped]
> Entered on 05/12/2016 at 22:02:42 GMT (GMT+0000) by Baker, Kathryn:
> So did SD test start working? as when we were on the phone using DA had no effect and WA was only setting it to 100 A whatever the input was given.
> Entered on 05/12/2016 at 21:55:52 GMT (GMT+0000) by Akeroyd, Freddie:
> It would seem that “\n\r” is actually the correct sequence for input, so I am surprised SDTEST is working. Or are you just setting and not doing any readbacks with SDTEST?
> 
> Freddie
> 
> > From: Facilities IT
> Sent: 05 December 2016 21:10
> To: isisinstrument@sparrowhawk.nd.rl.ac.uk
> Subject: INSTRUMENT (LARMOR): Computing: Sample environment/Device Control: Danfysik 9100 IOC ... ISSUE=67593 PROJ=15
> 
> [Duplicate message snipped]
> Entered on 05/12/2016 at 21:10:26 GMT (GMT+0000) by Akeroyd, Freddie:
> Hi Rob,
> 
> I’ve looked in your globals.txt for SDTEST and can see:
> 
> SDTEST_01__PORT1=COM42
> 
> SDTEST_01__BAUD1=115200
> 
> SDTEST_01__IEOS1=\\r\\n
> 
> SDTEST_01__OEOS1=\\r
> 
> In the IOCS log for DFKPS I see:
> 
> [2016-12-05 15:20:28] asynOctetSetInputEos("L0",0,"\n\r")
> 
> [2016-12-05 15:20:28] asynOctetSetOutputEos("L0",0,"\r")
> 
> So the input end of line terminator is different (swapped) between the two. I believe Kathryn is out tomorrow, but maybe somebody else from the IBEX team could confirm what the EOL characters should really be. I’m assuming “\n\r” is correct for some model of Danfysik, but I’m surprised they would vary in that way between models
> 
> Regards,
> 
> Freddie 
> > 
> From: > Facilities IT 
> Sent: 05 December 2016 20:31
> To: Akeroyd, Freddie (STFC,RAL,ISIS)
> Subject: INSTRUMENT (LARMOR): Computing: Sample environment/Device Control: Danfysik 9100 IOC ... ISSUE=67593 PROJ=15
> 
> [Duplicate message snipped]
> Entered on 05/12/2016 at 20:31:23 GMT (GMT+0000) by ISIS Computing Support:
> The DFSK IOC being used on Larmor stopped working. It worked previously at the 
> start of cycle but now seem to slow down and fails to respond. In the end I was 
> forced to resort to using SDTEST. This seems to work perfectly reliably suggesting 
> that there a problem with the purpose built IOC.
> This is the second time this cycle that we have had problems with the IOC after 
> changes made during the shutdown caused us to accidentally send the device to max 
> current.
> A fix needs to be found as these devices are used in a number of places and will 
> continue be needed on Larmor and ZOOM.
>

**Comment by FreddieAkeroyd** [comment]
I believe input EOL in the IOC is correct, it is incorrect in the SDTEST configuration but Rob was just setting and not reading. The only difference I could see was stop bits

**Comment by kjwoodsISIS** [comment]
OK.  So the EOL is not the problem.  But there is still an underlying problem, right?  Do we understand what it is yet?

**Comment by FreddieAkeroyd** [comment]
I don't think we do understand yet, somebody needs to talk to Rob about trying it again (maybe with less stop bits). He is currently managing by using SDTEST and not having a readback, I don't know if doing that will be sufficient for the rest of cycle or not.

**Comment by kjwoodsISIS** [comment]
OK.  I will ask someone to chat with Rob at tomorrow's stand-up meeting.

**Comment by KathrynBaker** [comment]
Please note, there are 7 of these 9100s on Muon Front End which are working, I looked at the settings for UQ9 (DFKPS_08 on MFE) for comparison in settings and macros, just in case the information helps anyone else looking into this...
On Muon Front End the only macros not using default values are:
In global.txt:
FACTOR_READ_I = 0.01
FACTOR_READ_V = 0.1
In the config settings:
SP_AT_STARTUP = YES
CALIBRATED = 0
PORT

On LARMOR, the FACTOR_READ_I should probably match (assuming Rob actually wants to read his values in Amps), the PORT should obviously be updated, CALIBRATED should also probably be 0, SP_AT_STARTUP should be NO, and I don't think Rob cares about the voltage, but it should probably match to the value as above.

That would get you to a state that is close to the existing, working examples. If the system doesn't work in the same way it is going to be down to the settings on that particular Danfysik, and may need to involve the electrical folks to get the boards out and double check the settings - there are no settings on the 9100 that can usefully be changed on the front panel, it is all jumpers and internal settings.

**Comment by kjwoodsISIS** [comment]
Still need to follow up and check differences between LARMOR & Muons.

**Comment by KathrynBaker** [comment]
Just seen Rob who said that this will be used on LARMOR w/c 29/5/17 - need to chase up with Diego that this gets turned on beforehand and that we have the correct settings, and ideally on LARMOR before it is needed (test on LARMOR might be last minute). If anyone else is available when it comes up, sharing this set up method/info would be good.

**Comment by KathrynBaker** [comment]
I have now had the time with the Danfysik on LARMOR, the settings are now correct so that IN:LARMOR:DFKPS_01:CURR and the CURR:SP work as expected with the one currently selected.

The magic numbers for this 9100 was FACTOR_READ_I = 1e-2 and FACTOR_WRITE_1 = 1000

**Comment by KathrynBaker** [comment]
Moved directly to review complete as this was purely a settings issue, Diego (Instrument Scientist) was there at the time I was making these changes.
