### ISSUE TITLE
IRIS: Fault on Eurotherm A03

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1889]
Iris encountered an issue today using the Sample_changer configuration. The temperature is not being read from channel 3 on either EUROTHERM1 on EUROTHERM2.

I've looked at the IOC and it looks like it's running ok. We tried all the usual things of restarts, changing calibration files, inspecting the macros have been set properly. We also tried switching around the sensors. It was always EUROTHERM1:A03 (and equivalent on EUROTHERM2) that wouldn't read. We switched from using channel 3 to channel 4 and the problem persistd. The problem did not occur with SECI.

The log does show the following error:

`[2016-12-06 12:59:20] dbFindRecord for 'IN:IRIS:EUROTHERM1:A03:CAL:SEL.VAL' failed`

It's possible that the calibration isn't being set up correctly, though that wasn't evident from polling the IOC's PVs after the fact.

I've been unable to reproduce the issue locally using a copy of NDXIRIS but with recsimmed Eurotherms.

One suggestion Gareth had was that the scan rate for the Eurotherms was too high and so signals weren't coming through. I've tried the setup with a 2-Eurotherm crate and increased the scan rate by a factor of 10. The system didn't have any difficulty.

Please could this issue be revisited when any of the following are true:

- when IRIS is next free, possibly during the next shutdown 
- when a 3-crate Eurotherm is available for testing
- if someone has an idea not covered above

**Comment by FreddieAkeroyd** [comment]
The dbFindRecord() error can be ignored - it occurred after switching from channel 3 to channel 4 and was the IOC autosave attempting to restore the calibration file PV for a no longer running channel.

**Comment by FreddieAkeroyd** [comment]
Did you try running A03 with A01 and A02 disabled? That would indicate if it was an issue with polling too much

**Comment by kjwoodsISIS** [comment]
For the future: what can we do to try to reproduce these types of condition in testing, so that we don't encounter them during operations?

**Comment by ChrisM-S** [comment]
It would be good keep a MOXA connection in the loop with your Eurotherm test in the office and (not joking)  50m of RJ45 cable made up with 5 x 10m cables joined to simulate a long serial run before we get to the kit.  I'm happy to supply MOXA to be used on the test system - can you do the cables and adaptors Kathryn?  As long as the system can be made to fail at some scan rate, we will have a useful emulation of some non-ideal instrument conditions!

**Comment by FreddieAkeroyd** [comment]
How about a plankton emulator, it could be used to introduce delays?

**Comment by FreddieAkeroyd** [comment]
BTW Have they ever used A03 before on IRIS?

**Comment by ChrisM-S** [comment]
For the sake of completeness, a similar setup (which would have to be on a private second socket of a machine) would consist of an old 100Mb netgear (lower speed than our normal 1Gb so some packet queing can occur) and possibly a similar cable - but with maybe lots of old short odds and ends cables and still a lot of joiners - to ensure some network errors and dropped packets.

**Comment by ChrisM-S** [comment]
(Sorry just been audited whilst I was typing the last comment!) yes, we could use an emulator to put in delays and worthwhile on system tests, but there's nothing like seeing how kit and software respond to real comms failures, incomplete characters, packets which return disconnects or error statuses which are not expect etc.
And we've demonstrably had all of these at least at some of the time in our existing system over the years (and there are probably some still there).

**Comment by KathrynBaker** [comment]
I don't have that many 10m cables in stock, but you would be welcome to a 30m one and a 20m one

**Comment by FreddieAkeroyd** [comment]
@AdrianPotter I think you could test it without a 3 crate eurotherm, just define A3 to point at the same sensor address as either A1 or A2 - the DB logic just does a sequential poll so the actual physical destination shouldn't matter I think

**Comment by AdrianPotter** [comment]
I just tried the above with original and increased scan rate. I couldn't reproduce the issue.

```
Did you try running A03 with A01 and A02 disabled? That would indicate if it was an issue with polling too much
```

I didn't try that, just the sensor reordering. Something to try when we get back on Iris

**Comment by FreddieAkeroyd** [comment]
I noticed a couple of the drivers used by the eurotherm were synchronous rather than asynchronous - don't know if this is related #1892 maybe if there are a lot of sensor files is can cause a delay? But then why for A03 ...

**Comment by AdrianPotter** [comment]
Duplicate of #1903
