### ISSUE TITLE
GUI: Motor details OPI is unclear about units

### ISSUE THREAD

**Issue by jonelmer** [ISISComputingGroup/IBEX#1890]
Is it possible to display the correct units for displacements/speeds/accelerations next to/within the fields?

At present, the engineering unit for the motor (EGU or EG - these terms are used interchangeably) is displayed at the top of the screen.

In the "Drive" section, no units are displayed, but there is space for the EGU to be added next to each value.

In the "Dynamics" section, speeds are labelled in "EGU/sec" (should be mm/s or deg/s) along the right hand side. Further confusion is added by the "Accel." row, which is labeled with "sec" and "EGU/sec^2". The "Normal" and "Backlash" accelerations are, according to the motor record: _the length, in seconds, of the acceleration and deceleration phases of a motor motion_ whereas the "Jog" is a true "mm/s²" or "deg/s²" acceleration depending on the motor EGU. The ambiguous labeling of the units led me to think that all accelerations were expressed in "EGU/sec^2". 

The "Resolution" section is clearer, but could still benefit from displaying the actual unit alongside its values.

![image](https://cloud.githubusercontent.com/assets/23215573/20963829/f6d8346e-bc66-11e6-9288-24e26b93bce6.png)

(Motor record docs: [http://www.aps.anl.gov/bcda/synApps/motor/R6-9/motorRecord.html#Fields_motion](http://www.aps.anl.gov/bcda/synApps/motor/R6-9/motorRecord.html#Fields_motion))

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/750
