### ISSUE TITLE
Shorten MK3CHOPPER IOC name

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1895]
New IOC rules would have this at 8 characters, we should probably consider shortening this before ZOOM comes up, and as part of the mini release for the EUROTHERM name change.

**Comment by IsabellaRey** [comment]
QUESTION: the mk3 chopper OPI has the IOC name MK3CHOPPER_01 hard-coded in it. Should this be a macro settable from the synoptic instead and is it worh doing it as part of/together with this ticket? (is there only ever going to be one of these per instrument? In which case we probably don't care)

**Comment by KathrynBaker** [comment]
I know instruments can have multiple choppers, not sure if we have any with multiple mark 3s, or will do. It should probably be set as standard for OPIs.
