### ISSUE TITLE
Script Generator: Should be able to tab within the table

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1898]
I couldn't find any reference to this, but it is likely to get really frustrating if you go into the table to start editing values, and press tab to move to the next column, only to find that you can't as tab moves between the major items and doesn't allow you to move between columns.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
