### ISSUE TITLE
Kepco OPI macro & new style

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1904]
The Kepco OPI expects the IOC_NUM macro instead of the IOC name, i.e. "01" instead of KEPCO_01.

It should be changed to the IOC name for consistency with other OPIs.

While doing this ticket, the OPI itself could be changed to the new style (it's a very simple OPI)

**Comment by IsabellaRey** [comment]
NOTE: existing synoptics will need checking

**Comment by Tom-Willemsen** [comment]
Make sure simulation mode starts correctly

**Comment by Tom-Willemsen** [comment]
Also investigate why kepco voltage is reported in Amps

**Comment by Tom-Willemsen** [comment]
Changes in the simulation mode have been moved into ticket #1938, and the units issue has been moved into #1939
