### ISSUE TITLE
OPIs: Write a script to check formatting

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1906]
With the new templates, we've introduced a lot of rules. I didn't realise a lot of them until Isabella reviewed my new Eurotherm OPI:

https://github.com/ISISComputingGroup/ibex_gui/pull/390

It seems that a lot of the rules are scriptable, rather relying on visual checks. It may even be possible to do a rough conversion from the old style to the new style. Such a script would make it immensely easier to create new OPIs and update the existing ones to the new style.

**Comment by Tom-Willemsen** [comment]
What is the set of rules that we can (reasonably) expect this script to check?

1) Colours are the ISIS_* colours
2) Alignment (not sure this is easy/possible)
3) ?
