### ISSUE TITLE
SKF Chopper OPI: fix rules, scripts and macros

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1907]
The tabbed container of the SKF chopper OPI has a rule using a local PV and a macro to decide which tab is active by default when the OPI is loaded. This rule doesn't seem to work and needs fixing.

Also double-check the script that determines which tabs are enabled/disabled - I tried quickly with local PVs as triggers on my machine and it didn't work, but maybe it had to with the local PVs

NOTE: in case the rule for the active tab is fixed:
Currently the user has to specify the macro as 0 to 4, whereas the tabs are numbered 1 to 5. This can be confusing, it would be better to either change the macro value to be 1 to 5 or change the tab labels to 0 to 4. (if the macro is changed, any synoptic using this OPI will need to be updated when releasing!)

**Comment by davidkeymer** [comment]
Ticket possibly duplicated here: https://github.com/ISISComputingGroup/IBEX/issues/2757

If so, will need to close it too.

**Comment by John-Holt-Tessella** [comment]
Shown to Winfried want it in the release if possible
