### ISSUE TITLE
ZOOM: GUI: Alignment Laser

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1909]
There is an alignment laser on ZOOM which will be a simple in/out automation. This is much the same as the in/out monitor, but the labelling and thumbnails are not appropriate for this really, as such updates should be made to the GUI/OPI/motion axes to allow for the use of an alignment laser.

As a scientist I want to be able to move the alignment laser in/out of the line of the beam on ZOOM.

#### Acceptance Criteria ####
1. I can move the ZOOM alignment laser to pre-defined positions (labelled IN and OUT) using the IBEX GUI or a genie_python script.
2. There is an OPI for the ZOOM Alignment Laser, which allows the alignment laser to be moved to the (pre-defined) IN and OUT positions.

#### Notes ####
1. Moving the alignment laser in/out of the line of the beam is analogous to moving a Monitor in/out of the beam.

**Comment by kjwoodsISIS** [comment]
Attached is a sketch showing how the OPI for the Alignment Laser might appear.  The sketch also shows a suggestion for the synoptic icon for the Alignment Laser.
![alignment_laser](https://cloud.githubusercontent.com/assets/7249337/21233711/1173fcae-c2e8-11e6-8a67-814c3d074877.png)

**Comment by KathrynBaker** [comment]
Having been aware of further discussions, now that the laser in the process of being installed, this will probably be static for the first couple of years, and will be treated as a straightforward in/out system.

The next couple of years it is likely to be kept in the beam, and it is worth us being aware and providing some information for this as that position is likely to be a short distance away from a high precision home - so this might require a specific routine to move in, or it may need more frequent homing somehow.

Any other details are still TBC.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/707
