### ISSUE TITLE
System tests should get the latest genie_python too

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1912]
The system tests install the latest EPICS and GUI builds but not genie_python.

Please add installing genie_python to the get_latest_builds.py

**Comment by FreddieAkeroyd** [comment]
The system tests do install the latest genie python, but in jenkins.bat rather than get_latest_builds.py 

Currently previous builds of genie python are not kept,  moving to using get_latest_builds.py  would make this easier to handle if/when it happens
