### ISSUE TITLE
Muon Front End: NGPS PSU

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1922]
As a Muon instrument Scientist I need to be able to control the new PSUs that are being ordered for use on the front end.

Due to the bidding process these next PSUs will be NGPS (New Generation Power Supply Series) by OCEM Power Electronics/CAENelts.

For more information from OCEM:
http://www.ocem.eu/en/project/ngps-high-stability-digital-power-supply-series-up-to-10-kw/

For more information from CAEN (including a manual):
http://www.caenels.com/products/ngps/

This will need:
* Emulator
* IOC
* OPI

There is no date known for arrival and use at this point in time, this ticket is to ensure that this is known of.
These are in addition to the existing PSUs.
These are ethernet devices rather than serial, so there are some potential issues with this, such as whether or not they will need to be placed behind a firewall rather than being on the standard network.
There are not presently enough ethernet points in the location these will need to go into.

**Comment by KathrynBaker** [comment]
Update from the magnet groups, the PSUs this ticket relates to have just passed factory acceptance testing, and will (hopefully) be on site and testable in the magnet lab by the Summer 2018 shutdown. As soon as the magnet teams are able to I will get an update on when they will be available to talk to. There has been one change at least made to the system, as well as the network connection they have spit that out and added in a serial converter, so both comms methods can be used. We will need to remember that when writing the ASYN part of that driver. The protocol should be the same as that detailed in the manuals that have already been linked. 

If needed I can go through the manual and provide a list of the commands/PVs that are needed to my best guess, until they are in use we won't get much more information from the scientists than I can make an educated guess about.

**Comment by ChrisM-S** [comment]
It would be interesting to see if they maintain a "Native" and (possibly more trusted) set of commands below their inboard IOC.  Also if their IOC source code  is available as a good starting point for ours it might make sense to use as much of this as possible.

I'm very sceptical of devices which encompass an OS which is anything more than bootable firmware and a scratch RAM for configuration.   These will potentially need patching up to date, even if we put them on the private instrument network and this would be best to avoid (note all the issues with needing to patch oscilloscopes recently).

**Comment by KathrynBaker** [comment]
This native code is no different to the other CAEN systems on the network (any instrument HV), there are a few of the newer models which have that similar style of inbuilt IOC, and the last time one was booted up in a state that would have allowed that, because it also incorporated a DHCP server it caused some interesting issues.

I certainly am far keener to see these brought up and treated as more standard pieces of equipment.

To my knowledge there is currently no plan for the patching etc. of these devices – I wasn’t involved in the tender of them, and am at the tail end having been told, “this is what we have ordered”, so there may be a discussion for the ‘management’ side of things with the people who will be looking after the PSU to make sure that happens.

**Comment by Rory-Potter-Tessella** [comment]
Pull requests:

- [IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/304)
- [Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/76)
- [IOC Test Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/114)
- [EPICS]()
- [OPI](https://github.com/ISISComputingGroup/ibex_gui/pull/767)
- [Wiki page for the device](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/NGPS-PSU)

**Comment by Rory-Potter-Tessella** [comment]
Updated pull requests above with reworked code.
