### ISSUE TITLE
GUI: Ensure that all synoptic icons conform to standards

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1929]
There are standards at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Synoptic-Icons for component icons in the synoptic. Ensure that all current icons conform to these (notably the colour of the mercury does not)

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1192
