### ISSUE TITLE
GUI: Ampersands appearing on perspective buttons

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1934]
To reproduce bug:
* On any GUI window hold shift
* Press any key a number of times while shift is held
* Ampersands will appear on the perspective buttons

This is clearly due to a bug in https://github.com/ISISComputingGroup/IBEX/issues/369

**Comment by AdrianPotter** [comment]
There's an issue with the alarm button flashing when the shortcut is used. I've submitted as a separate ticket:

https://github.com/ISISComputingGroup/IBEX/issues/1957
