### ISSUE TITLE
Synoptic Editor: PV address validation in titlebar

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1936]
As of https://github.com/ISISComputingGroup/IBEX/issues/1611 the synoptic editor has a title bar to display errors like the config editor. When an invalid PV is set in the synoptic it should be displayed in this bar along with a note of which component has the offending PV. The user should not be able to save the synoptic until this error has been resolved.

**Comment by KathrynBaker** [comment]
Awaiting tests
