### ISSUE TITLE
GUI: bundle JRE on Windows

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1941]
To make life easier we can bundle the JRE with the GUI. It makes the disk footprint bigger by about 30% but it might make life easier for users as they don't need to install Java (and all the associated crud).
And it makes our life easier as we can ensure the correct JRE is being used.

It only requires a top-level folder called jre adding with the standard jre layout; Eclipse will then use that by default.

**Comment by ChrisM-S** [comment]
Sounds like good trade off to me, there are some things to think about too.

* How does it play on a system with an already installed Java of earlier or later version?
* Could we also get the server to use the same version when the client is running on IBEX server?
* What is our strategy if we/FIT are required to patch Java across the board/regularly or urgently?

**Comment by mattclarke** [comment]
I have merged the branch to confirm it works, but there is still stuff to review on the PR
