### ISSUE TITLE
Add IFDEVSIM to all existing IOCs

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1942]
The macros for enabling DEVSIM should be added to all existing IOCs so they are ready for Lewis even if a simulator does not exist yet.

Here is an example from the Lakeshore 336:

```## For emulator use:
$(IFDEVSIM) drvAsynIPPortConfigure("$(DEVICE)", "localhost:55626")

## For real device use:
$(IFNOTDEVSIM) drvAsynIPPortConfigure ("$(DEVICE)", "$(HOST):7777")```

**Comment by kjwoodsISIS** [comment]
Need to think if we can do this another way.  Postpone for now.

**Comment by GRyall** [comment]
Emulators are now in place for the majority of IOCs, so this ticket has been overtaken.
