### ISSUE TITLE
IOCLog & ActiveMQ: Investigate sender host

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1943]
When I double click on a log message in the GUI I get some useful information about the message. However, regardless of the instrument I am pointing to I am told that the sender host is 127.0.0.1, this is annoying. Investigate and fix if easy to do.

**Comment by FreddieAkeroyd** [comment]
All our IOCs run on loopback, so the sender IP address will always appear to be 127.0.0.1 if it is added by the log server

**Comment by FreddieAkeroyd** [comment]
I'll supply a hostname in the XML log message in #1945 so you'll just need to update the java iocLogServer etc

**Comment by DominicOram** [comment]
Ok, I will modify this ticket to be the GUI side of https://github.com/ISISComputingGroup/IBEX/issues/1945

**Comment by KathrynBaker** [comment]
The limited use of this system makes this change unnecessary
