### ISSUE TITLE
SECI: On start SECI kills IBEX

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1951]
As a scientist on systems which run both SECI and full IBEX server when SECI is started it should stop IBEX first using the stop IBEX script. It should *not* be configured to do this on system which run mini IBEX server.

Edit https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Startup-and-Shutdown to put full behaviour in.

**Comment by KathrynBaker** [comment]
Proposing as it is possible to get very confused when switching between the two control systems - we ought to get this done for cycle 17/2 (September 2017)

**Comment by KathrynBaker** [comment]
With the minimal number of remaining migrations (all but three instruments ran IBEX in the most recent cycle) this will not be something to revisit if this is still outstanding as an issue
