### ISSUE TITLE
IOC LVDCOM: Create flag to start vi but not labview

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1952]
Add a flag to lvdcom so that a vi can be started if it isn't running but it will not start labeview. This is to enable mini Ibex to started before SECI with an LVDCOM IOC and for them both to talk to the same labview.

Once done add this flag to [making lvdcom IOC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-IOC-wrapper-VI)

**Comment by FreddieAkeroyd** [comment]
The work has been done as part of #1695
