### ISSUE TITLE
Server: Only start procserves for IOC in startup.txt

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1953]
When a min Ibex server is started use the startup IOC list to limit the number of procserv processes started to those on the list.

This makes the process of running a mini Ibex cleaner.

**Comment by FreddieAkeroyd** [comment]
Should also restrict conserver consoles. This is a simpler version of #3858

**Comment by KathrynBaker** [comment]
Closing as there are better actions elsewhere as per #3858
