### ISSUE TITLE
Architectural:review the security of IBEX - take II

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1958]
On 6th January we held a meeting to review security issues.  A follow-up meeting would be helpful.  We need to consider:

1. What things (assets, systems, information, etc.) need to be protected?
2. What threats are these things exposed to?
3. What steps must/should/can we take to eliminate or reduce these threats.

Continue compiling the list and actions we need to take.

**Comment by John-Holt-Tessella** [comment]
Arranging meeting

**Comment by John-Holt-Tessella** [comment]
Create part III
