### ISSUE TITLE
Script Generator: Add helpful constraints

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#1963]
The Script Generator table currently does not handle wrong input very well, either allowing it (thus creating a script with nonsensical parameter values), or discarding it without feedback.

Suggested changes:

* Add constraints to `POSITION` field value (currently: any string):
> POSITION - The sample's position in the rack. Rack contains a top (T) and bottom row (B), with 20 columns (A to T). A position can range from AT to TB.
(taken from https://github.com/ISISComputingGroup/IBEX/issues/1560)

* Add constraints to `SAMPLE_NAME` field to allow alphanumeric only (currently: any string)
* Add some sort of feedback in case of wrong input that gets discarded, e.g. a temporary message displayed above the table.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
