### ISSUE TITLE
Initial discussion about IRIS script generator

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1970]
Meet with Ian and Vicky to discuss what their requirements are for a script generator for use on IRIS/OSIRIS.

The output should be tickets for a later sprint.

**Comment by ThomasLohnert** [comment]
After discussing this with Matt, I will move this ticket back into the backlog for now. I will continue work on the Script Generator after returning from Mantid in September. If we start gathering requirements now scientists will (reasonably) expect something to be delivered in the near future.

**Comment by John-Holt-Tessella** [comment]
Scientists at the training course were interested too. They said "script gerenator, especially for IRIS. Muon one is intuitive and liked, and easy rather than the SANS one. Vicky, Dom and Ron were interersted.

**Comment by Tom-Willemsen** [comment]
Re-requested by IRIS team.

**Comment by kjwoodsISIS** [comment]
This ticket is no longer relevant.  New Script Generator has been created and will shortly be released..
