### ISSUE TITLE
GUI: Can the version of CS-Studio we are using handle V4?

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1974]
Don't worry about the OPIs for now, just see if we can talk to V4 from a custom widget as a test (remove the widget afterwards).

If we cannot talk to V4 create a new ticket to see if we can update the PV manager to the latest version without breaking anything.

**Comment by kjwoodsISIS** [comment]
We are migrating to Eclipse V4.  This ticket is now obsolete.
