### ISSUE TITLE
LARMOR: no communication to 3D Magnet

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1979]
The following problem was reported by Rob.  Gareth believes the problem to be as simple as a missing flag (see e-mail below)

> From: Howells, Gareth (STFC,RAL,ISIS)
> Sent: 17 January 2017 11:29
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Subject: LVDCOM 3D Magnet
> 
> Dear Kevin,
> 
> I’ve had a call from Rob this morning regarding the 3D Magnet which uses a LabVIEW vi. 
> On loading the configuration, he had no communication with the equipment. I manually set the 
> LabVIEW vi running and all was well. There is no imminent problem.
> 
> I believe that all that is missing is a flag to run the vi which I believe is possible (lvDCOMConfigure). 
> There is no appropriate reference I can find in the settings directory on LARMOR for the Magnet vi 
> or LVDCOM.  I believe the flag might be in `c:\Instrument\Apps\EPICS\ioc\master\SCIMAG3D\iocBoot\iocSCIMAG3D-IOC-01\st.cmd`
> 
> Would it please be possible to create a ticket for this to be updated for (and on) LARMOR? 
> I was expecting the option to be possible in the settings directory and for it to be configurable. 
> Maybe that could be raised as a query to discuss.
> 
> Regards,
> 
> Gareth

**Comment by John-Holt-Tessella** [comment]
I think the right thing to do here is to add a macro for the setting (LVDCOM_MODE) so that the configuration can contain the mode that the 3D magnet should start in. This macro is the lvdcom option flag mentioned in http://epics.isis.stfc.ac.uk/doxygen/lvDCOM/lvDCOMInterface_8h.html#abc97e5fb937c746684ce45dea3586291. We should talk to @FreddieAkeroyd to find out what it should default to in general.

**Comment by KathrynBaker** [comment]
Especially as this might have an impact on #1952 as well

**Comment by FreddieAkeroyd** [comment]
LVDCOM_OPTIONS might be a better name for the macro. I guess you mean "default in general" for the IOC as opposed to globally? warnIfNotRunning is probably reasonable, but some may want to auto-start by default I guess

**Comment by John-Holt-Tessella** [comment]
Add macros for other options too.
