### ISSUE TITLE
VESUVIO: Create configurations, synoptics and scripts

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1981]
VESUVIO needs some of the top configurations, syoptics and scripts converting from SECI to give the instrument scientists something to deal with.

**Comment by John-Holt-Tessella** [comment]
Configurations create some component:

1. Temperature Component based on Sub_EVS_Eurotherm_CCR (this includes both cold and furnance temperature variants they just change the calibration file based on the sensor)
1. Foils component based on Sub_EVS_Base (and current foils)
1. Keithly component (new)

Scripts that need converting:

1. evs_routines (in c:\scripts or a t least linked from here).

**Comment by AdrianPotter** [comment]
Setting to impeded. We can't set up a Keithley component until we upgrade to 3.1.0

**Comment by AdrianPotter** [comment]
Move to review. Scientists have been shown the configurations and scripts. The Keithley won't be available until later. I've told Giovanni and Matt that it will need testing before running. By then they should be happy enough with the system to add the Keithley to the relevant configuration

**Comment by Tom-Willemsen** [comment]
A few comments on the translation of 'evs_routines.gcl` to `vesuvio_routines.py` (accessible at  \\\\Ndxvesuvio\c$\ ):

The script is functional and much clearer than the genie version. Just a minor comments as discussed: The list of runs could be refactored from `runs.append((2, 0))` to `runs.append("B0")`. This should be clearer for the instrument scientists.
