### ISSUE TITLE
IOC: Danfysik and Genesys discontect error on reading

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1983]
As a scientist I would like a block based on the value from a danfysik or Lambda Genesys to show as disconnected when the device is disconnected.

**Comment by KathrynBaker** [comment]
This might be true of all asyn devices – we just noticed it with these that with the PSUs switched off there were a lot of errors, but the blocks were still showing as connected.

**Comment by John-Holt-Tessella** [comment]
See #2604 Fixed more generally
