### ISSUE TITLE
Motors View: Parts of the motor details can be hidden

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1987]
If you drill down from the motor table, to an individual motor, to the motor details you get an OPI that is bigger than the area available, and no scrollbars. It is possible to move the partition to increase the width, but not the height. This is fine if you are on a large enough screen, but on smaller screens this can still be an issue.

There is a work around, you can view the hidden items by zooming the view of the OPI, but that does involve a sacrifice in readability.

It may be possible to add scrollbars at that level to improve the situation, and this ought to be considered.

This has not been checked on the synoptics, or on device screens, so these may have the same problem.

**Comment by Tom-Willemsen** [comment]
This is a problem with the motor details OPI itself. 

If all the objects in the OPI are copied to a new OPI, it works fine. XML diff doesn't show anything obvious other than a bunch of extra objects in the new OPI, which is interesting given that the new one should just have been a copy of the old one.

One line of investigation would be that the motor details OPI was created with a very old version of CSS and therefore is not quite compatible with newer versions... (?)
