### ISSUE TITLE
Web Dashboard: Strange characters

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1988]
There were a couple of strange characters appearing on the LARMOR dashboard. Work out what is causing them and fix it

See attached picture

**Comment by mattclarke** [comment]
![image](https://cloud.githubusercontent.com/assets/3032495/22140969/82ecd96c-dee7-11e6-83c9-c7780689b3f2.png)

**Comment by Tom-Willemsen** [comment]
The values from the PVs seem to be correct.

`caget -t -S IN:LARMOR:DAE:RUNDURATION` returns a number (`111`) but is being reported in the web dashboard as `o`.

Interesting PVs are:
`RUNDURATION`, `RUNDURATION_PD`, `NUMTIMECHANNELS`

The PV units are blank, so the stray characters must be appearing somewhere in the webserver/front end.

**Comment by Tom-Willemsen** [comment]
`111` is the ASCII character code of `o` and `104` is the ascii character code of `h`. So what is happening is that the number is being interpreted as an ASCII character when it shouldn't be.

**Comment by Tom-Willemsen** [comment]
Marking as impeded because we cannot test until #1991 is fixed.

**Comment by Tom-Willemsen** [comment]
This should have been fixed by #1991

**Comment by DominicOram** [comment]
Deleted the branch for this as it has already been fixed
