### ISSUE TITLE
Device screens: Unknown instrument

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#1992]
When the device screens are opened on an unknown instrument and I press on "Edit device screens", the following exception is thrown in the console:

`*2017-01-27 09:25:49.789 [main] ERROR org.eclipse.ui.workbench - null`

The "Edit device screens" button should be greyed out when on an unknown instrument to prevent this from happening.

**Comment by Tom-Willemsen** [comment]
No longer occurs on latest master.

**Comment by DominicOram** [comment]
Switching instruments also seems to make a difference to this bug. If you switch to a running instrument and then switch back you can open the edit device screens. I'm also not sure if the button should be greyed out, there's no reason why you can't create a local device screen even if the block server isn't running...

**Comment by Tom-Willemsen** [comment]
This ticket predates the ability to create local device screens :) But yes I agree that it would be useful to be able to open device screens without a blockserver running.
