### ISSUE TITLE
Add OPI format checker to Jenkins

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1998]
Now that we have a OPI format checker (https://github.com/ISISComputingGroup/IBEX/issues/1906) it would be good to do this as part of the build. Like checkstyle it should not be an error if it fails but we should aim for it not to increase.

**Comment by KathrynBaker** [comment]
This is available as a githook, so issues should be resolved before the files get to Jenkins, in theory,
