### ISSUE TITLE
GUI: More info on delete component

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2001]
As a scientist I want to know that I can not delete a component when it is in configuration. The delete screen should show my this component grayed out with an explanation of the configurations it is in.

Reported by Ian

**Comment by kjwoodsISIS** [comment]
See also #2007 - it is clearly related to this.

**Comment by kjwoodsISIS** [comment]
Need to write down all the scenarios:
e.g. remove a component from a configuration, before deleting the component.

**Comment by John-Holt-Tessella** [comment]
Also want a force rename and force delete

**Comment by AdrianPotter** [comment]
In the interests of being thorough, I'd like to finish testing this once #2085 is fixed

**Comment by AdrianPotter** [comment]
![image](https://cloud.githubusercontent.com/assets/10273443/22984506/7420dc7e-f39d-11e6-8c96-347b8d5e7059.png)

The functionality looks good so far, though I haven't been able to finish owing to ticket #2085.

In the error dialog, there are a couple of things I'd tweak:

- [ ] There appear to be two blank lines after the component list which gives uneven spacing compared to the introductory line
- [ ] The list might look better as:

```
Component: My_component
Contained in configurations: Config_1, Config_2
```

**Comment by AdrianPotter** [comment]
I haven't yet checked the behaviour when deleting multiple components

**Comment by AdrianPotter** [comment]
Functionality looks good. One tiny change:

```
... and thus can not ...
```

In the error dialog text, please could you

- [ ] Make `can not` into `cannot`. Both are technically correct but the latter is more standard.
- [ ] Use `so` instead of `thus`. Again, both technically correct but `so` is more natural language.

Sorry, I should have spotted both of those on the first pass.
