### ISSUE TITLE
Review security and update version on MySQL

### ISSUE THREAD

**Issue by tomgriffinstfc** [ISISComputingGroup/IBEX#2004]
As a developer, I want to use the most secure, stable version of MySQL in IBEX, so that I can be sure we are taking appropriate steps to minimise security risks.

### Acceptance Criteria ###
1. Download the most recent, secure and stable version of MySQL.
1. Install and test with IBEX to determine the most suitable configuration of MySQL for our purposes
1. Update the IBEX installation instructions to reflect any changes to the MySQL installation step
1. Document, in the wiki, any particular steps that are required to ensure that MySQL is secure (see note 1 below).

### Notes ###
1. The most recent, secure and stable version of MySQL is v5.7.17 (MySQL Community Server).
1. The MySQL documentation includes a chapter on security practices (see https://dev.mysql.com/doc/refman/5.7/en/security.html).  We should ensure that adopt all appropriate measures.
1. This ticket originated as the following request:
```
From: Tom Griffin [mailto:notifications@github.com] 
Sent: 01 February 2017 09:05
To: ISISComputingGroup/IBEX
Cc: Subscribed
Subject: [ISISComputingGroup/IBEX] Review security and update version on MySQL (#2004)

A recent vulnerability scan reported a large number of high threat security issues relating to MySQL.
The majority of reports were from PCs that appear to be owned by IBEX developers.

Oracle Mysql 'my.conf' Security Bypass Vulnerability (Windows)
Oracle MySQL Security Updates (oct2016-2881722) 09 - Windows
Oracle MySQL Multiple Unspecified Vulnerabilities-05 April16 (Windows)

Please review the versions of MySQL in use and update to the most appropriate secure version.
```

**Comment by Tom-Willemsen** [comment]
[Installation instructions](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)) currently specify an exact version of MySQL to be used (5.6)

Check compatibility of newer versions with IBEX.

**Comment by ChrisM-S** [comment]
For John the detail for doing a full install of MySQL 5.7.xx into the correct paths is given at the end of a comment on 
  "#1994 Rethink The Client installer"
as an example.

The documentation from MySQL reference manual on this link with the MSI non-interactive install is very thin, but this is just an "escape" mechanism allowing passing of the parameters of a my.ini from the command line.

**Comment by AdrianPotter** [comment]
We can install the latest version of MySQL using the old installer. That way we get all of the security updates but we can still easily set the data directory. I've updated the following pages:

- [Deployment](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC): Updated instructions on installing/updating MySQL
- [Getting started](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)): Updated instructions on installing MySQL
- [Dev release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev): Added versions of MySQL and Java (the latter needs filling in).
- [Creating a release](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release): Added instructions to add MySQL and Java versions to the release notes.

**Comment by AdrianPotter** [comment]
Having reviewed https://dev.mysql.com/doc/refman/5.7/en/security.html we potentially have an issue with the current granted user privileges. It's not obvious to me that all of the options granted are needed. I will review.

**Comment by AdrianPotter** [comment]
After discussions on the Slack channel, I will open a new ticket for reviewing the DB users

**Comment by AdrianPotter** [comment]
#2153

**Comment by Tom-Willemsen** [comment]
Appears to work fine. I haven't spotted any regressions in my testing.
