### ISSUE TITLE
GUI: Make component details available when editing configs

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2006]
The details of selected components should be made available when editing a configuration, so they can be instantly displayed and checked against duplicates etc. Currently all that is available in EditableConfiguration are lists of the (names of) selected and unselected components. The blocks etc. from a component are then added in the blockserver based on those lists, thus the config does not know whats in a component until saved.

There is already a component() method in ConfigServerVariables which can be used to return the details of a component given its name, which may be a good place to start.

Prerequisite for https://github.com/ISISComputingGroup/IBEX/issues/1355, https://github.com/ISISComputingGroup/IBEX/issues/1357, https://github.com/ISISComputingGroup/IBEX/issues/1884

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/432
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/112

**Comment by DominicOram** [comment]
Conflicts on both branches, will merge once fixed
