### ISSUE TITLE
Motor OPIs: New style

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2008]
As a user, I would like the motors to use a new style OPI. 

A consistent look and feel to OPIs will help users find their way around, and motors are one of the most frequently used OPIs.

This ticket should encompass #1890 and maybe #1987 at the same time.

Acceptance criteria:
- There are new-style motor OPIs for both the 'normal' and 'detailed' views, which conform to the style guidelines on the wiki.
- The motor OPIs function as before.

**Comment by KathrynBaker** [comment]
The one thing to be aware of with this is that the detailed view is one we have taken from the motor driver, so this might not be one for us to take on and edit necessarily. We can, of course, but it does mean that we will have to update it to keep it in line with any changes to the motor record ourselves.

**Comment by kjwoodsISIS** [comment]
Yes, I agree with Kathryn.  We need to be careful with the scope of this ticket.
We can control the style of the motor OPIs we have created.  However, the deeper, more detailed views come from CSS (I guess).  If we are not careful, we will only make additional work for ourselves.

**Comment by Tom-Willemsen** [comment]
OK - it seems that I missed a layer of complexity here when I initially wrote the ticket. Looks like the detailed view(s) is/are best left alone in that case.

**Comment by DominicOram** [comment]
This is worth reviewing, yes the detailed screen is not ours but it is really not very complex and IMHO making changes to it is not that big a deal...

**Comment by RichardTysonIsis** [comment]
Changing the motor details OPI to the new style has been moved to #3344 .

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/738
