### ISSUE TITLE
GUI: Can not delete recommended synoptics

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2014]
From the synoptic menu, attempting to delete the recommended synoptic silently fails. This should either succeed or alert the user that it's failed. 
NB a block server error does appear which says "Delete list contains unknown configurations" this is not timely and does not make sense. 
I suspect this is responding to a thrown exception in a generic way.

**Comment by AdrianPotter** [comment]
Fixed as a by-product of #2527

**Comment by AdrianPotter** [comment]
I've added manual system test 15-66
