### ISSUE TITLE
Editing configurations a lot causes the GUI to gradually slow down and eventually crash [TIMEBOX: 2]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2017]
This issue was first spotted on NDXIRISTEST1 while doing manual system tests, and reproduced in a development environment. The GUI will slow down gradually and eventually crash. Symptoms to look out for are high CPU usage and a sluggish GUI.

Steps to reproduce:
Run through all the manual system tests that are to do with the configurations panel.

Task manager screenshots:
![image](https://cloud.githubusercontent.com/assets/24375813/22600529/d8611a88-ea32-11e6-9b8c-cfaf0dd4f0bc.png)
![image](https://cloud.githubusercontent.com/assets/24375813/22600544/ec5b3bc2-ea32-11e6-9df4-bf641c9b4a1b.png)

**Comment by AdrianPotter** [comment]
We've been getting reports of excess CPU usage from the end of last year and notably more have arrived now cycle is starting

```
***** Nagios *****

Notification Type: RECOVERY

Service: IBEX CLIENT CPU
Host: NDEMUONFE
Address: NDEMUONFE
State: OK

Date/Time: Fri Feb 10 12:51:25 GMT 2017

Additional Info:

OK (Sample Period 599 sec) - Found 1 Instance(s) of ibex-client running. CPU_ibex-client(PID=13716)=59.4%
```

Notably I started receiving alerts on 16/11/2016 shortly after v2.2 was deployed. The release notes for that version might be a good starting point.

**Comment by KathrynBaker** [comment]
MUONFE may be a minor red herring, as it is probably pointing to something else that we ought to be fixing. The PSUs that MUONFE talk to are currently off, so there are a large number of messages being generated by the IOCs – so this is likely to be a lot of IOC messages, which is still a problem, but is a different one to the title of this ticket. I thought there was a ticket, and it certainly is a similar issue to #1580, as there isn’t an existing ticket I have created #2062 to ensure we look at the log messages as log messages.

**Comment by Tom-Willemsen** [comment]
The nagios alerts aren't exclusive to MUONFE; here are a couple from IMAT (which appear to show gradually increasing CPU usage):

```
***** Nagios *****

Notification Type: PROBLEM

Service: IBEX CLIENT CPU
Host: NDXIMAT
Address: NDXIMAT
State: WARNING

Date/Time: Sat Feb 11 20:17:22 GMT 2017

Additional Info:

WARNING (Sample Period 600 sec) - [Triggered by _AvgCPU70] - Found 1 Instance(s) of ibex-client running. CPU_ibex-client(PID=10424)=83.8%
```

```
***** Nagios *****

Notification Type: PROBLEM

Service: IBEX CLIENT CPU
Host: NDXIMAT
Address: NDXIMAT
State: CRITICAL

Date/Time: Sat Feb 11 20:27:22 GMT 2017

Additional Info:

CRITICAL (Sample Period 599 sec) - [Triggered by _AvgCPU85] - Found 1 Instance(s) of ibex-client running. CPU_ibex-client(PID=10424)=100.0%
```

Could (should?) we check with the relevant instrument scientists what they were doing at that time, and any behaviour they observed?

**Comment by Tom-Willemsen** [comment]
I emailed Winfried about the reports above, and he mentioned that one of his IOCs (a chopper) was disconnected at the time, which lends credence to the theory that this issue is caused by having disconnected IOCs rather than by editing configurations a lot (although editing configurations a lot in a development environment is likely to give you a few disconnected IOCs!)

Although #2062 is about memory and this is about CPU, it seems quite likely that they'll be part of the same resource leak.

**Comment by Tom-Willemsen** [comment]
Resource leak appears to be due to ActiveMQ.

![image](https://cloud.githubusercontent.com/assets/24375813/23020549/805df3b2-f43f-11e6-8b42-1a3b71325200.png)

![image](https://cloud.githubusercontent.com/assets/24375813/23020554/83424a42-f43f-11e6-9e43-fb6ed4b8debc.png)

In the above screenshots (from java visual VM) you can see that at some point ActiveMQ starts creating approximately 4 new threads per second. This then continues on a linear trajectory upwards. Java supports a variable number of threads depending on the host, but it's [of the order of ~10,000](http://stackoverflow.com/questions/763579/how-many-threads-can-a-java-vm-support), at which point the garbage collector will no longer be able to cope and the program will crash. 

This now gives us a much easier way of reproducing this issue - check in the java visual VM (`C:\Program Files\Java\jdk1.8.0_73\bin\jvisualvm.exe`) for the point at which the number of threads starts it's upwards trajectory.
