### ISSUE TITLE
IOC: McLennan reverse to home mode 0s position if home aborted

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2020]
As a user, I don't want the McLennan homing mode 2 to 0 the position of the motor if homing is aborted.

To reproduce:

1. Set a McLennan to homing mode 2 using the HOMEn macro
2. Home the motor (it doesn't matter if it doesn't have a home switch)
3. Observe that the position is zeroed

Note that the motor doesn't report when it's homed so there are some circumstances such as reaching a limit switch where I would still expect it to 0. We can catch the state though where the motor is actively stopped by the user.

**Comment by AdrianPotter** [comment]
I've discussed this ticket with @davidkeymer. The current VI behaves the same way as the IOC: the motor position is reset to 0 when it becomes idle, whether that's because it reaches home or is stopped some other way.

It may be desirable that we implement this change regardless of the VI but the motor doesn't make this option available.

1. We could not reset the position if the `[PV].STOP` field becomes set. This unfortunately doesn't work because the 'set' value isn't persisted long enough for SNL to pick it up. Further, there are many other ways the motor might be stopped prematurely of reaching the home position leading to inconsistent behaviour if we don't 0 on one kind of stop
2. Examining the traffic with the motor, there is no other way to distinguish between the motor reaching its home position versus stopping by some other means excepting any additional commands inciting the stop as discussed in 1.

Based on this, I'm setting this ticket to won't fix. The current behaviour is preserved from the VI and enhancing the behaviour is beyond the means provided by the motor.

**Comment by kjwoodsISIS** [comment]
Do we need to communicate this to the scientists?
