### ISSUE TITLE
IOC: McLennan gets stuck after multiple homes

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2021]
As a user, I don't want my McLennan to get stuck if I request multiple identical homes. To reproduce:

1. Find the upper limit switch and ensure the soft limit is set to the same value
2. As above for the lower limit switch
3. Set the McLennan home mode to 1
4. Home the motor to the limit switch
5. Click the same home button, no movement is expected
6. Try moving the motor back

When we did this on Vesuvio the motor would not move until the IOC was restarted. It complained of soft limit violations even though the reported position was in range.

**Comment by FreddieAkeroyd** [comment]
Do you clear the HOMR / HOMF or JOGR / JOGF fields after a home/jog has finished?

**Comment by John-Holt-Tessella** [comment]
Impeded until #2000. and #1975 are done

**Comment by AdrianPotter** [comment]
I think you meant #1875, rather than #1975

**Comment by John-Holt-Tessella** [comment]
OPI doesn't respond correctly see pull request
