### ISSUE TITLE
Installation/upgrade process: automate as much as possible

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2022]
As a developer, it would save a significant amount of time if parts of the upgrade/installation process were automated.

Create scripts to automate [these instructions](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC) as much as possible.

**Comment by kjwoodsISIS** [comment]
See #2152

**Comment by kjwoodsISIS** [comment]
Redundant now that we've had a discussion.
