### ISSUE TITLE
genie_python/NICOS: Is a PYTHON environment variable required?

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2024]
On a system that had genie_python installed, but no other versions of python (so no system environment variables), despite having set the MQ passwords, NICOS was continually launching a command window.

Adding an environment variable called PYTHON to the system stopped this issue occurring.

Some checks need to be made to verify that this solution is correct and appropriate. After which a suitable course of action can be found to ensure that this does not occur in the future. At a bare minimum, if this is required, it should be added as a step to the setup instructions on the wiki.

**Comment by FreddieAkeroyd** [comment]
My system only has genie_python installed (so no PYTHON environment variable in a non-EPICS terminal) and start_ibex_server started nicos OK. NICOS is running via %PYTHONW% so having to set %PYTHON% sounds a little strange - have you previously edited you nicos startup when hunting for other issues?

**Comment by KathrynBaker** [comment]
No, the only thing I ever do to stop NICOS starting is edit the line in the bat file which starts it, I have not done anything else with it.

**Comment by FreddieAkeroyd** [comment]
After I have started the instrument I have six   pythonw.exe   processes running (two nicos related) but no  python.exe   processes, what does you task manager process view look like?

**Comment by KathrynBaker** [comment]
Six pythonw, 2 Nicos related. I’ll try again tomorrow to see what I get without the environment variable set.

**Comment by KathrynBaker** [comment]
Without that environment variable set, I get the same 6 pythonw processes, including 2 for NICOS, and this time the window hasn't started up again. So there is something odd on first startup possibly? Something to keep an eye on or to test with a new build instrument type?

**Comment by John-Holt-Tessella** [comment]
Test on HRPD test machine

**Comment by AdrianPotter** [comment]
No problems on HRPDTEST using:

Client: 3.1.1.43
Server: 3.1.0.46dd4e1
Java: 1.8.0_121

I'm moving to review for now. Do you have any other tests you'd suggest @KathrynBaker?

**Comment by KathrynBaker** [comment]
Assuming you have actually started Nicos up and it runs, then that should be fine.

**Comment by Tom-Willemsen** [comment]
Logged into HRPDTEST, checked environment variables, no environment variables called python were present.

No flashing window. Looked at logs, no signs that nicos had been throwing a fit (a couple of restarts consistent with manually starting/stopping server but nothing that looked wrong).

Marking this as complete.

**Comment by John-Holt-Tessella** [comment]
OK this happened on ndxtest1. It appears that if you start_ibex_server in the same windows in which you ran the install script it doesn't have the variable. The solution is just to close the window and start a new terminal. I have added it to the deployment instructions.
