### ISSUE TITLE
DAE3: Adapt Larmor DAE IOC for parallel running

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2026]
To run a DAE2 and DAE3 in parallel the DAE db must be modified to include the following behaviour:

When a begin is sent to the DAE2:
* Send a begin to the DAE3
* Send a begin to the DAE2
* Turn off veto (using PVs on the TEKAFG3XXX)

When an end is sent to the DAE2:
* Turn on the veto (using PVs on the TEKAFG3XXX)
* Send an end to the DAE2
* Send an end to the DAE3

Similar logic should be applied to pause/resumes and to runcontrol but is less important.

**Comment by FreddieAkeroyd** [comment]
Hi Dominic,

the mechanism of trying to trigger something extra on a begin is general, however it being DAE3 is a special case. Thus I think it would be worth generalising things a bit:

- beginrun forward links to $(BEGINRUNA=BEGINRUN1) and endrun to $(ENDRUNA=ENDRUN1) 
- in this case you load isisdae.db passing BEGINRUNA=BEGINRUN_DAE3 and ENDRUNA=ENDRUN_DAE3 
- you load a separate db file containing the specific BEGINRUN_DAE3 and ENDRUN_DAE3 logic

**Comment by DominicOram** [comment]
Ok Freddie, I've made it a bit more generic. I've also changed it so that to start parallel running you just need to set `ISISDAE_01__PARALLEL=#` in globals.txt

**Comment by FreddieAkeroyd** [comment]
Looks good now - I've added a release notes entry
