### ISSUE TITLE
GUI/blockserver:Blocks in a config can not be added to a group in a component

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2033]
If a group is defined within a component a block within a config that uses that component can not place the block within the group. Although from the GUI it appears you can when you save the changes are ignored.

**Comment by Tom-Willemsen** [comment]
Cannot reproduce. Can anyone else?

**Comment by KathrynBaker** [comment]
Cannot reproduce, closing issue - we can create a new one if we find that this is the case
