### ISSUE TITLE
User: Shared code repository

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2034]
The users would like to share code between some experiments. Can we add a shared code repository to allow them to do this. Initially for SANS2D team. Would it make sense to be able to share configurations too? This area needs some requirements gathering to how it should be implemented.

**Comment by KathrynBaker** [comment]
This particular need at the moment is experiment type, so would be all SANS experiments. In some cases it will want to be by group (e.g. excitiations).

**Comment by ChrisM-S** [comment]
The definition of code is a bit loose here, is this:


1.       Scripts that the users will use in real time to control individual runs to collect data (or a library from which they will pick and customize for each experiment)?

2.       Mantid scripts to analyse or reduce data while the experiment is going?

3.       Other code or things run offline/at home by users?

**Comment by KathrynBaker** [comment]
This is ‘instrument’ type scripts. So written in house by the instrument scientists to do standard things on their beamline(s). Putting these through git, and using a shared repo will give us the easy distribution method (as per calibrations), and them versioning.

User scripts are separate to this, mantid is not a consideration, and anything offline/at home is well and truly outside of our scope. This is only the library of ‘functions’ to be used.

**Comment by ChrisM-S** [comment]
Yes that does make sense.  We could probably do with not having the code so far down the tree as we do with the Open GENIE scripts. Could also let users git their scripts on the U: drive if they are up to it - that's a bit of a hole currently as I only backup the user drive once per cycle.

**Comment by kjwoodsISIS** [comment]
This ticket looks to have been superseded by #2713 & #2716 - so closing.
