### ISSUE TITLE
Blockserver: Commit other files to repo

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2035]
At the moment the repository for settings does not include code or motor settings, etc. Should it contain this and when should it be updated? Once known implement this.

**Comment by AdrianPotter** [comment]
Duplicate of #2134

**Comment by AdrianPotter** [comment]
We may finish this ticket as part of the backlog preparation. This ticket asks should we do it, #2134 is the implementation ticket. If we decide to include #2134 in the sprint then the work of this ticket is done.

**Comment by AdrianPotter** [comment]
Decided to do #2134. Closing ticket
