### ISSUE TITLE
Training: Enhance IBEX training course

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2036]
Feedback from users suggested that the course needs:

1. Synoptics adding to the course
1. Possibly a chance to use the programming with material before coming to a questions session
1. `IN:IRISTEST` needs to be replaced with `<inst name>`
1. Scripting slides need to remove g.start_change()
1. Scripting slide for use of inst needs to be made to work correctly.
1. Integration to Mantid/Advanced Scripting (such as scanning an axis)
1. DAE tabs
1. Better explanation of relationship between block/PV/scripting including naming conventions

**Comment by John-Holt-Tessella** [comment]
As part of #2203

**Comment by AdrianPotter** [comment]
All good. I've made a few minor changes to the wiki and slides (mostly typos) and uploaded a new version of the slides to SharePoint.

For point 2. we've decided to continue to gauge interest on whether to provide material in advance to see how much demand there is.
