### ISSUE TITLE
ZOOM: Update Sample Stack OPI for Beckhoff axis

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2038]
As a scientist, I want the Sample Stack OPI to report the position of the sample stack on the rails (used to move the entire sample stack parallel to the x-axis).

The motor that drives the Sample Stack  is controlled by a Beckhoff controller.  We are awaiting confirmation of how the Beckhoff is to be set up and how we will communicate with it.  This ticket cannot be tackled until we have this information.

#### Acceptance Criteria ####
1. The Sample Stack OPI on ZOOM reports the position of the stack on the rails .

#### Notes ####
1. See ([schematic diagram](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/ZOOM/ZOOM_Sample_Stack_Schematic.pptx)) showing how entire sample stack moves along the rails.
1. The initial implementation of the ZOOM Sample Stack was performed in ticket #1238.

**Comment by Tom-Willemsen** [comment]
See also #2042 and check if it can be done at the same time.

**Comment by KathrynBaker** [comment]
Having moved to the generic sample stack this is no longer applicable - it should just be some configuration, that will still need doing but can be done with the end of the commissioning.
