### ISSUE TITLE
ZOOM: Update Sample Stack OPI with sample changer

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2042]
As a scientist, I want the Sample Stack OPI to report the sample changer position.

We are currently awaiting details of what the sample changer will be and how it will be set up. This ticket cannot be tackled until we have this information.

Check if #2038 can be done at the same time.

#### Acceptance Criteria ####
1. The Sample Stack OPI on ZOOM reports the sample changer position.

#### Notes ####
1. The initial implementation of the ZOOM Sample Stack was performed in ticket #1238.
1. The [motion setpoint documentation](https://github.com/ISISComputingGroup/IBEX/wiki/Motion-Control) should be updated to include information about how to set up this sample changer, with file snippets as appropriate.

**Comment by KathrynBaker** [comment]
No longer relevant as ZOOM is now using the generic sample stack OPI.
