### ISSUE TITLE
GUI: Tooltips for auto-start/auto-restart

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2046]
As a user, I would like tooltips for the auto-start and auto-restart properties of IOCs to tell me what they do.

At the Sans2D training workshop on 6/2/2017, users instinctively hovered over auto-start and auto-restart labels in the GUI to try and discover what they mean. These particular terms are not intuitive and so would benefit from tooltips.

This ticket may be affected by Thomas' IOC rework.

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1237
