### ISSUE TITLE
GUI: IOC descriptions blank

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2048]
As a user, I would like the IOC descriptions column in the IOC/configuration editor to either be generally populated or not exist. At the moment it takes up space for no value

**Comment by kjwoodsISIS** [comment]
What is the problem here?
* is it that the description field in the IOC is being left blank (if so, why?), so that the GUI has nothing to display?
* is the GUI ignoring the IOC description field?

**Comment by AdrianPotter** [comment]
- The GUI is ignoring the IOC description field
- The descriptions in the DB are generally just the IOC name which wouldn't be especially helpful

I've changed the first property. Now I need to populate the IOC descriptions which is done by adding the <ioc_descr> element to the <config_part> of each IOC's config.xml

**Comment by AdrianPotter** [comment]
This had to touch a lot of repos. Make sure they all get merged and synced with the main EPICS branch.

**Comment by ThomasLohnert** [comment]
`make iocstartups` is complaining about missing config.xml for the following IOCs:
CCD100
INSTETC
PSCTRL
RUNCTRL
SimpleIoc

**Comment by AdrianPotter** [comment]
I've added descriptions for the CCD100 and simple IOC. The others are not user IOCs so the description is unused. Is there any particular reason to add them?

**Comment by AdrianPotter** [comment]
Done. No new PRs, all in EPICS\IOC.
