### ISSUE TITLE
GUI: Add filter to start/stop IOC window

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2051]
My understanding is that the majority of the time people interact with the start/stop IOC dialog, it's to start or stop IOCs that are part of the config. 
I propose adding a filter (e.g. checkbox) to toggle between displaying all IOCs and config IOCs only in order to make the list easier to read.

**Comment by DominicOram** [comment]
Also see https://github.com/ISISComputingGroup/IBEX/issues/1609

**Comment by DominicOram** [comment]
@ThomasLohnert Is this covered by being able to sort the column?

**Comment by John-Holt-Tessella** [comment]
No not covered by sorting.

+1 Muons

**Comment by KathrynBaker** [comment]
Proposing as there are other considerations at present relating to filtering of IOCs

**Comment by KathrynBaker** [comment]
Suggest closing this, based on discussion in #6272

**Comment by KathrynBaker** [comment]
Closing in favour of #6272 as per previous comment
