### ISSUE TITLE
GUI: Increment spectra plots button

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2052]
This request has come in from Giovanni Romanelli on Vesuvio

As a user, I would like to be able to quickly switch between spectra plots in the DAE system view. The current method is a little bit too cumbersome.

Giovanni suggests adding increment/decrement buttons alongside the set plot buttons which seems like a reasonably good solution

**Comment by AdrianPotter** [comment]
Perhaps change control to a spinner. See DAE data acquisition tab, monitors spectrum

**Comment by ChrisM-S** [comment]
Something that offers drop downs of spectrum numbers selected earlier might be useful like browser hints - saves typos and gives clues to people unfamiliar with that instrument who might not know the useful spectra.  Also, possibly a choice to make monitor numbers always selectable/identifiable - as I'm sure these spectra feature very heavily in the use of these graphs!  I suspect Giovanni's request is based on something in the SECI LabVIEW VI which has not transferred this this does have spinners...
