### ISSUE TITLE
GUI: Add run diagnostics 2 page

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2054]
Create a page in the DAE perspective that is similar to the run diagnostics 2 page in SECI. The back end for this will be done in https://github.com/ISISComputingGroup/IBEX/issues/1846

**Comment by AdrianPotter** [comment]
![image](https://cloud.githubusercontent.com/assets/10273443/24654827/5cfc63a4-1933-11e7-82cf-346493eedf5c.png)

**Comment by kjwoodsISIS** [comment]
Branch from candidate release.

**Comment by AdrianPotter** [comment]
The screenshot above shows the current layout. It would be instructive to interview some instrument scientists to see what they actually want it to do. My impression from Freddie is that it was largely used to see which spectra had counts so much of the information and a few of the controls might be irrelevant.

**Comment by AdrianPotter** [comment]
I've just emailed the instrument scientists. Awaiting responses.

**Comment by AdrianPotter** [comment]
Setting as impeded while we wait a week for responses. I'll go prodding people if we haven't had feedback by then.

**Comment by AdrianPotter** [comment]
Meeting with Russell on Tuesday

**Comment by AdrianPotter** [comment]
Feedback from Russell (Alf) and Ian (Iris):

- Non-contiguous spectra are currently unsupported. Instrument scientists may want to look at a number of different blocks of spectra simultaneously but they won't always be next to each other numerically.
- All of the functions currently supported by the VI are useful to instrument scientists, but some less than others
- It would be nice to be able to specify different integral ranges for different spectra. Iris wouldn't use it but others would. 
- Russell doesn't look for any particular conditions when looking at the current table but Ian specifically looks to identify 0 blocks. Perhaps these could be highlighted somehow, but subtly. A zero spectra may be intentionally that way.
- Russell often uses the relationship of a spectrum to its neighbours to identify outliers. This may not be something we can do anything with but worth noting

**Comment by DominicOram** [comment]
Feedback from Ron (POLARIS) was that he mainly looks for abnormally high counts (when he expects none) and zero counts when he expects some. I.e. he uses this to test his detector is working correctly.

**Comment by Tom-Willemsen** [comment]
#2298 should be completed first

**Comment by Tom-Willemsen** [comment]
Check with @FreddieAkeroyd what the purpose of having an enable/disable PV is as this adds a few extra complications in terms of maintaining a client/server architecture
