### ISSUE TITLE
IOC: TPG300_02 & _03 don't start

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2063]
TPG300 02 and 03 do not start correctl. Report missing st-common files. Change the line 17 in  C:\Instrument\Apps\EPICS\ioc\master\TPG300\iocBoot\iocTPG300-IOC-02\st.cmd and 03:

to

< ${TOP}/iocBoot/iocTPG300-IOC-01/st-common.cmd

Reported by Ian and fixed on IRIS MUST be in next update.

**Comment by KathrynBaker** [comment]
I know this is closed, but the problem has just been seen on LARMOR too - fixing it there
