### ISSUE TITLE
Add serial device support to VISAdrv

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2066]
The module should be already able to provide simple NI GPIB support to stream device, this ticket is to extend it to provide simple serial device support which means:
- supporting asyn get/set options for baud rate, parity etc.
- checking on EOL handling for which NI visa has some extra serial device properties

**Comment by KathrynBaker** [comment]
After a bit of to and fro to resolve some oddities in the behaviour of the system, it has at least passed my testing. I ran my dummy python device (physical cables between two MOXA ports, python one end as the device, other items on the other end), which I can talk to from LabVIEW, using the ASYN driver, and using this VISA driver.
