### ISSUE TITLE
Web Dashboard: Value formatting

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2069]
As an POLARIS and IRIS instrument scientists I want the dashboard to show small numbers the same as the IBEX dashboard, not to truncate them. This is caused by the archiver json representation of the value which is truncated using the epics precision. We need to update this and then change the formatting rules in JSON Borne.

Ian found a couple of minor formatting issues on the web dashboard:

The “Monitor From” and “Monitor To” are showing 3 decimal places, which is unnecessary, and the vacuum gauges (mostly a problem for the bin vac) are showing linear scale. For these it would be better reported as an exponent.

**Comment by DominicOram** [comment]
For the exponent issue we have recently added formatting rules to the GUI, these should probably be followed in the web dashboard.

**Comment by DominicOram** [comment]
This is especially bad when the value is very low. Ian saw values at 1e-7 reported as 0.000

**Comment by Tom-Willemsen** [comment]
POLARIS have also reported that this truncation happened to some of their numbers, causing some confusion.

Apparently a `furnace_vac` block displayed as `0.000...`on the web dashboard when the real value was `0.0005`. (Number of zeroes is illustrative only)

Inform Ron/Helen on POLARIS when this ticket is done as they seemed quite keen for this to be fixed.

**Comment by John-Holt-Tessella** [comment]
+ 1 from sprint review with Ian and Vicky today

**Comment by Tom-Willemsen** [comment]
Raised again by HRPD in their demo today.

**Comment by DominicOram** [comment]
I've modified the archive engine to give non-formatted values and precision in the JSON. Please review as part of this ticket.

Code changes at: https://github.com/ISISComputingGroup/cs-studio/compare/master...ISISComputingGroup:archive_engine_json_formatting_2265

Built version is at \\isis\inst$\Kits$\CompGroup\ICP\archive_engine_with_json
To test built version:
* Copy the new version of the archiver from \\isis\inst$\Kits$\CompGroup\ICP\archive_engine_with_json (can put this anywhere on your machine)
* Run an instrument
* Stop your ARBLOCK
* Confirm that http://localhost:4813/main is not available
* Run ArchiveEngine.exe in an EPICSTerm (When this is run it will just start up in the background, the only indication it is running is by looking at the website)
* Confirm you can see all the webpages at http://localhost:4813/main as normal
* Confirm that the JSON at http://localhost:4813/group?name=BLOCKS&format=json contains un-formatted block values and precision fields

Once reviewed we need to:
- [ ] Change the version that we have in C:\Instrument\Apps\EPICS\ICP_Binaries\CSS
- [ ] Put in a PR for the changes to be merged into csstudio

**Comment by DominicOram** [comment]
Moving to impeded as new ArchiveEngine doesn't work on some machines, will look into before finishing ticket

**Comment by Tom-Willemsen** [comment]
The archive engine on the share (`compgroup\icp\archive_engine_with_json`) should work but is hotfixed. Dom is doing ticket https://github.com/ISISComputingGroup/IBEX/issues/3206 to document how to build it sensibly.

**Comment by John-Holt-Tessella** [comment]
Rework:

- [ ] Fix review comments in dataweb code
- [ ] Make archive engine build

Run whole thing together.

**Comment by DominicOram** [comment]
@John-Holt-Tessella New archive engine build on share. Does it work for you?

**Comment by John-Holt-Tessella** [comment]
Yes it works
