### ISSUE TITLE
DAE IOC initialize DAE registers on Startup?

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#2073]
As a supporter, *3* times this startup I have had to fix a hung instrument, on SECI with no useable DAE buttons showing or an EPICS instrument with an uninformative error instead of a DAE panel.

The fix is stop the DAEII process, run the Electronics supplied W2DT DAE test program on the DAE registers to initialize the DAE (the problem usually occurs after a power on) and then restart the DAE process to allow the user to do a BEGIN.

Is it possible to modify the DAE IOC code such that this random electronic state is detected and fixed as part of the normal DAEII initialisation process?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - does this initialisation (or lack of it) happen in the DAE IOC or with the ICP itself?  I am guessing it is the ICP, because neither SECI or IBEX seem to handle this condition.

**Comment by FreddieAkeroyd** [comment]
Hi Chris, which instruments were these? There was an issue with older versions of the control program that on DAE power on it could return a number that couldn't be displayed in LabVIEW which caused the VI front panel to stop working, but underneath all was fine and you could begin/abort in Open GENIE to clear things.  That is fixed on newer SECI instruments - it was really a signed / unsigned variable type mismatch that only caused an issue if a register got initialised to 2^32 etc.  

On which instrument and what was the IBEX error? Maybe it is suffering the same problem as the LabVIEW from panel used to suffer? At this point I'm not sure I need to specifically initialise the DAE, just we need to handle formatting of unexpected replies better.

**Comment by ChrisM-S** [comment]
That would be consistent with what I've experienced - I have to guess but I think it might have been something like CRISP or SURF, OSIRIS, maybe PEARL and possibly IMAT or VESUVIO for the EPICS one.  Could have been 4 but I'm afraid I was chasing other things including VISA server ownership for Electronics and disks, and updates... and beginning to conclude that when the DAEs were switched on, they may not all have been tested with WD2T by Electronics as they usually don't seem to be this bad.  Certainly one DAE VI did not jump back into SECI on restart - so that would have been an old one.

**Comment by KathrynBaker** [comment]
I'm not aware of this error having reoccured recently, closing
