### ISSUE TITLE
Synoptics: Cannot view synoptics after startup

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2074]
Reported by Rob on Larmor. I've witnessed it once locally too.

As a user, sometimes when I open the GUI and go to the synoptics view, none of the synoptics will appear. This seems to occur after restarting the server.

It might be a problem if the synoptics view is opened before the block server has started.

Solution is to restart to client but it'd be nice if users didn't have to do that

**Comment by ThomasLohnert** [comment]
Also reported by Winfried on IMAT

**Comment by kjwoodsISIS** [comment]
> From: Facilities IT [mailto:FITservicedesk@stfc.ac.uk] 
> Sent: 20 February 2017 19:57
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Subject: INSTRUMENT (IMAT): Computing: User Interface: Synoptic view on IBEX gone after restar... ISSUE=68607 PROJ=15
> 
> When replying, type your text above this line. 
> ________________________________________
> Query Number 68607
>   
> This is a copy of the most recent response to query number 68607 in the FBU IT Servicedesk.
>   
> Customer : IMAT Instrument
>   
> Query Subject : INSTRUMENT (IMAT): Computing: User Interface: Synoptic view on IBEX gone after restart
>   
> Query Status : New Instrument Request
>   
> This email has been CC'd to : (permanent) kevin.woods@stfc.ac.uk, john.holt@stfc.ac.uk, adrian.potter@stfc.ac.uk, winfried.kockelmann@stfc.ac.uk, genoveva.burca@stfc.ac.uk
> ________________________________________
> Query Description (newest entry at top)	
>   	
> Entered on 20/02/2017 at 19:57:47 GMT (GMT+0000) by ISIS Computing Support:
> Synoptic view on IMAT gone after restart. This is my only way to some of the 
> components, like choppers.
> 
> Reported by: Winfried Kockelmann (mailto:winfried.kockelmann@stfc.ac.uk)
> ISIS Instrument: IMAT
> Name of computer problem was submitted from: ndximat.isis.cclrc.ac.uk
> Current ISIS Cycle: 16/5
> Product: Instrument Problem/Bug Report
> Category: Computing: User Interface
> Severity: major
> Priority: P1
> Scientist Contact Information: http://www.isis.stfc.ac.uk/people/instrument-scientists-4398.html
> Instrument Contact List (i.e. who gets these sorts of emails): http://sparrowhawk.nd.rl.ac.uk/footprints/contacts.html 
>

**Comment by DominicOram** [comment]
This just happened again on IMAT. Having looked at the logs it appears that IMAT has not restarted their blockserver recently so this is not root cause.

**Comment by KathrynBaker** [comment]
Rob has reported this again, highly unlikely to be server related as he did just close the client and restart and lost his synoptics, another close and restart got them back. I'm upping this to the top of the column as it is a recurring issue.

**Comment by kjwoodsISIS** [comment]
OK.  At stand-up tomorrow, let's agree who is going to look at this as a matter of urgency.

**Comment by GDH-ISIS** [comment]
I can confirm the case on IMAT. Restarted the whole of IBEX to get motion control operational. After fault finding the motion control side of things, the synoptic was no longer present.
Server side left alone.
Closed and restarted client.
Synoptics came back.
