### ISSUE TITLE
Add "ISIS (TS1 only)" to DAE timing source

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2076]
A "ISIS (TS1 only)" option needs adding to the DAE timing source dropdown on the Data Acquisition panel - it should come at the end of the list and have an enum value of 6

**Comment by Tom-Willemsen** [comment]
Requires rework on #2075 to test this.

**Comment by Tom-Willemsen** [comment]
Moving back into review for the second pull request (which just fixes checkstyle warnings from the first, so shouldn't be difficult to review!)
