### ISSUE TITLE
Genie Python: Remove printed error when PV doesn't exist

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2079]
When calling pv_exists in genie_cachannel_wrapper.py if the pv does not exist then an error is printed to screen. Rob first noticed this when trying to do a cset on an axis. This error comes from CaChannel and may be hard to suppress, potentially we could redirect the stderr when checking for the existence of pvs.

**Comment by DominicOram** [comment]
![capture](https://cloud.githubusercontent.com/assets/10086797/22935133/7c3ecc56-f2c9-11e6-821c-a15b5845ab02.JPG) This is the error Rob found. Can we also take a moment to appreciate the very straight line that @mattclarke drew on this image?

**Comment by FreddieAkeroyd** [comment]
The blue line is us raising an exception in genie_cachannel_wrapper.py - the other bit is
the usage of      SEVCHK(status, "py_pend_io")         in CaChannel itself. I'm not sure if this SEVCHK usage is actually needed as the error code is returned by the function anyway, but we'd need to review the rest of the code before removing to make sure we don't miss an error in an important place

**Comment by DominicOram** [comment]
Yes, we could easily remove our error but I don't know if we want to start modding CaChannel? Maybe we can just look at capturing any stderr/stdout that CaChannel spits out?

**Comment by ChrisM-S** [comment]
And for my next trick, how about drawing a perfect circle without a compass…☺

**Comment by FreddieAkeroyd** [comment]
We are actually already running a modded CaChannel as there was a 64bit windows issue I had to fix, though I see my patch is in CaChannel 2.4    

I think the way round this is to use search_and_connect() and pend_event() rather than searchw()

**Comment by FreddieAkeroyd** [comment]
... partly because pend_event doesn't call SEVCHK on error!

**Comment by AdrianPotter** [comment]
Sorry. Above merge was accidental. Have reverted and created a new branch

**Comment by AdrianPotter** [comment]
Ooops. Above merge was accidental. Have reverted and created a new PR
