### ISSUE TITLE
IOC error log message from chopper

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2081]
Reported by Vicky

Forward-link uses Channel Access without pointing to PROC field
IN:IRIS:MK3CHOPR_01:SIM.FLNK = IN:IRIS:MK3CHOPR_01:VERSION

**Comment by FreddieAkeroyd** [comment]
VERSION PV doesn't look to exist in DB FILE - I guess remove the forward link?

**Comment by John-Holt-Tessella** [comment]
Duplicate #1583
