### ISSUE TITLE
POLARIS: Stop unauthorised users setting Jaw set 5

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2082]
As a scientist, I would like the IBEX Client to display the controls for the 4 external jaws on a single panel, so that I can adjust all 4 from a single place.  It should also display the current settings for jaw set 5 (but not allow the settings to be changed). This should be achieved by adding an authorize section to the OPI into which a instrument scientist can type a password. This could then set the access for the 5th jaw set to readonly/full write.

#### Acceptance Criteria
As a scientists:
1. I can adjust the settings (i.e. blade positions) of jaw sets 1 - 4.
1. I can view the calculated and actual jaw gaps (vertical and horizontal).
As an instrument scientist:
1. I can authorize myself
1. I can adjust the 5th jaw set
1. I can revoke my privilege

#### Notes
1. The current jaws IOC can also display the position of the centre (vertical and horizontal) of the centre of the jaws.  Is this functionality useful?
1. The current POLARIS jaws VI displays beam height & width at the sample.  How are these calculated?
1. The current POLARIS jaws VI displays jaws 1-4 on one tab and jaw set 5 on a separate tab.  How important is it to reproduce this arrangement?
1. POLARIS jaws are JJ X-Ray jaws, driven by Galils.  The Galils IOC has logic for managing jaws.
1. There is an existing jaws OPI.  Perhaps we can adapt it for use in this OPI.

**Comment by John-Holt-Tessella** [comment]
See #2082

**Comment by kjwoodsISIS** [comment]
I have a printed screenshot of the current LabVIEW UI of the POLARIS jaws.  Come and ask for it.

**Comment by Tom-Willemsen** [comment]
Review at the same time as 2083
https://github.com/ISISComputingGroup/ibex_gui/pull/475

**Comment by KathrynBaker** [comment]
Missing PR for the brand new submodule

**Comment by Tom-Willemsen** [comment]
New submodule had already been added. See https://github.com/ISISComputingGroup/EPICS/commit/36eeba1b0b317cb29451326a146771f087887b27

**Comment by KathrynBaker** [comment]
See comments in #2083
