### ISSUE TITLE
POLARIS: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2084]
As an instrument scientist, I would like to migrate POLARIS to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on POLARIS
1. Configuration files matching the current SECI config files are created
1. IBEX is configured for the devices on POLARIS.
1. POLARIS scripts are converted to genie_python
1. POLARIS scientists are trained in how to use IBEX
1. IBEX is tested on POLARIS

#### Notes
1. Rather than tackle this a s a single ticket, it would be wise to create individual tickets for each sub-task.
1. The devices on POLARIS are listed on the [POLARIS Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/POLARIS-Instrument-Details) list

**Comment by kjwoodsISIS** [comment]
In Cycle 2017/01 (starting 2nd May 2017), POLARIS will use:
1. [OC100-11](http://www.isis.stfc.ac.uk/sample-environment/low-temperature/cryostats/cryostat-parameters---pdf9781.pdf) Orange (ILL MAXI) Cryostat
1. [CS155](http://www.isis.stfc.ac.uk/groups/electronics-and-sample-control/electronics-and-sample-control7146.html) high voltage centre stick
1. Spellman SL600 (6kV, 100mA, 600W, DC) high-voltage power supply

**Comment by Tom-Willemsen** [comment]
This ticket is now superseded by #2212 #2213 #2214 #2215 #2216
