### ISSUE TITLE
GUI: Cannot add components to a configuration

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2085]
Components can no longer be added to configurations. When the configuration editor dialog is opened, no components are listed on the components tab. Possibly a result of #2006.

**Comment by AdrianPotter** [comment]
Note that this is a new bug and doesn't affect 3.1.0

**Comment by ThomasLohnert** [comment]
It's working on my machine - could it be because you have not updated the blockserver? I created a new PV for the component details which is where the GUI is now getting it from - sorry, I should have mentioned it on Slack!

**Comment by DominicOram** [comment]
This also worked on my machine. Though it appeared that Adrian still saw it after updating his blockserver. We should also have a look a why this didn't get picked up in the system tests.

**Comment by ThomasLohnert** [comment]
Rseolved, the submodule was not added to git properly.
