### ISSUE TITLE
Investigate potential slow serial performance

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2086]
When looking at the asyn win32 serial driver it looks to be reading 1 character at a time, see if it is possible to read larger buffers in one go (as per other asyn serial drivers)

**Comment by kjwoodsISIS** [comment]
Assign to a specific sprint when this ticket is no longer impeded.

**Comment by FreddieAkeroyd** [comment]
To test: (short) 
* Find a serial device
* check it still works properly with new driver.
(long)
Use      asynSetTraceMask("L0",-1,0x9)      and note that you see lots of "read 1" messages
switch to the new asyn driver
Again Use      asynSetTraceMask("L0",-1,0x9)      and note that the reads size is now larger

**Comment by Tom-Willemsen** [comment]
Tested on office eurotherm. Seems to talk as before.
