### ISSUE TITLE
Nicos scripting perspective: resource leak

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2088]
Currently, clicking on the Nicos scripting perspective will cause a resource leak. Noticed this while testing for ticket 2017.

Opening the Nicos scripting perspective will cause approximately 4 threads/second to be created, which after an hour or two will make the GUI unuseably slow.

![image](https://cloud.githubusercontent.com/assets/24375813/23023567/2791242a-f44e-11e6-8d93-cdf3b2bbd327.png)
![image](https://cloud.githubusercontent.com/assets/24375813/23023569/2a3066fa-f44e-11e6-8765-f0e4edabe51f.png)

Use the java visual VM in `C:\Program Files\Java\jdk1.8.0_73\bin\jvisualvm.exe` to see this.

(This might go away once the Nicos scripting is all connected up properly, but I felt that it should be documented regardless).

**Comment by DominicOram** [comment]
This could also be related to https://github.com/ISISComputingGroup/IBEX/issues/2087. Once that ticket has been done this should be investigated again.

**Comment by John-Holt-Tessella** [comment]
John to check this isn't sorted in his change

**Comment by Tom-Willemsen** [comment]
I reopened this because I thought I saw it again, but on double checking it no longer happens (i.e. John did fix it as part of his change). Moving this back to done.
