### ISSUE TITLE
Large numbers of NAGIOS messages

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2094]
A large number of nagios alerts were received over the weekend of 18-19th February 2017.  The attached screenshot shows the alerts which landed in my Inbox.  Some of them are notifications of recovery, but these are just responses to the initial alert.

We need to understand why such large numbers of nagios alerts are being generated and resolve the problem.

**Comment by Tom-Willemsen** [comment]
Could be related to #2017 which I'm currently working on.

**Comment by kjwoodsISIS** [comment]
Nagios Alerts Screenshot
![nagios_alerts](https://cloud.githubusercontent.com/assets/7249337/23117857/9a44779e-f749-11e6-8929-df86dd334231.png)

**Comment by kjwoodsISIS** [comment]
Yes, quite possibly.  I think this issue just points to the fact that we need to find out what is hogging the resources (memory and CPU).  Once we have determined the cause and resolved it, we should create guidance on how to write code that avoids these types of problem.

**Comment by FreddieAkeroyd** [comment]
The issue is only CPU, memory seems stable on IRIS and LARMOR - the memory warning was from MUONFE and as it was unable to contact the computer ("unknown") rather than it being over any limit. I will upload a graph of the CPU on IRIS over the last week.
![iris](https://cloud.githubusercontent.com/assets/1132753/23118289/89ac143a-f74b-11e6-93de-46e2c5c28ba7.jpg)

**Comment by FreddieAkeroyd** [comment]
Where the graph says "Wed" for example that is noon (12:00) Wednesday

**Comment by Tom-Willemsen** [comment]
I just logged into NDXIRIS while nagios was showing 100% cpu usage, and as @GDH-ISIS suggested this morning at standup, task manager did not show any problem.

![capture](https://cloud.githubusercontent.com/assets/24375813/23408411/d66a8066-fdbf-11e6-9541-34dfafb29ff1.PNG)

![capture2](https://cloud.githubusercontent.com/assets/24375813/23408414/d8970300-fdbf-11e6-8b15-d899e037ccfc.PNG)

So it seems that nagios is not reporting what we think it is, and that there may not be any issue here at all. If anyone ( @ChrisM-S  ??) has any in-depth knowledge of how nagios reporting works, they might be able to shed some light on this?

From a small amount of searching online, it does look like nagios reports aren't necessarily accurate for processors with multiple cores. I'll put this ticket in impeded until we understand how to make nagios report reliably.

**Comment by FreddieAkeroyd** [comment]
100% means you are using one whole core, if you have an 8 core machine this may only show up as 12.5% total usage in task manager. So it's not using all CPU on the computer, but more than you could expect.

**Comment by Tom-Willemsen** [comment]
Is there a way to make nagios report overall usage?

**Comment by FreddieAkeroyd** [comment]
I don't think it is necessarily nagios, this could be what the underlying WMI counters report. Even if we scaled it down by number of cores to say 12.5% we would just end up reducing our warning level to spot unusual behaviour.  From the current graphs and warning levels we can see it is flattening out one core which is not right. As the client is multithreaded, this suggests one thread has probably gone mad somewhere.

**Comment by Tom-Willemsen** [comment]
I've reproduced behaviour that causes one thread in the GUI "to go mad" in ticket #2135

It's too early to tell whether that's the root cause of this ticket or just another red herring though.

**Comment by Tom-Willemsen** [comment]
Cycle has started and there hasn't been a flood of nagios CPU warnings (yet?), so I'm marking this for review. 

Note, the only nagios warnings we "care" about for the purposes of this ticket are the ones that say "CPU is WARNING/CRITICAL". Ignore messages about UNKNOWN or OK items.

**Comment by AdrianPotter** [comment]
Agreed. In the previous cycle, we were receiving around 3 CPU critical alerts per day. Since start of cycle, we've received 1 in total on Friday. The marked difference is sufficient to be confident the problem has been fixed.
