### ISSUE TITLE
Allow multiple build architectures

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2096]
All multiple epics builds to be hosted in the same source tree

**Comment by FreddieAkeroyd** [comment]
This is now implemented using the most recent build.bat from the top level directory - the only module that didn't support this was MySQL which is fixed above. For testing see:
 
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-multiple-architectures

**Comment by AdrianPotter** [comment]
Have asked @DominicOram if this is actually complete. Not clear what still needs doing since it's already been merged.

**Comment by DominicOram** [comment]
Sorry, this is fixed, I must have forgotten to move it properly.
