### ISSUE TITLE
HRPD: LinMot driver for Jaws

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2098]
As a scientist, I would like the IBEX to provide a driver for LinMot motors, so that I can control the 
jaws on HRPD.

#### Acceptance Criteria
1. I can adjust the settings of the single jaw set on HRPD.
1. I can view a schematic representation of the blades (N, S, E, W) of the jaw set
1. I can adjust the settings of the jaw set by setting the N, S, E, W positions or by setting 
   values for the horizontal & vertical gap and horizontal & vertical centre positions.

#### Notes
1. HRPD uses LinMot P0x-23 motors/drives to move the blades in the jaw set.
1. Can LinMot drives be controlled via the EPICS Motor record?  Can we create a simple stream driver to control the LinMot drives?
1. Is the current jaws OPI sufficient for use on HRPD?

**Comment by kjwoodsISIS** [comment]
After discussion with @FreddieAkeroyd , we decided that it would be best to try to control LinMot motors via the Motor Record (that way LinMot motors appear like any other motor to IBEX).  there are two options:

1. write some C++ functions to replace virtual functions
2. like the motor record to a stream device driver which speaks to the LinMot controller.

**Comment by John-Holt-Tessella** [comment]
@davidkeymer to find a test one

**Comment by davidkeymer** [comment]
LinMot calibration: 0.01925 steps/mm

Jaws Set 1 Offsets:

Jaw | Offset (steps)
---- | -------
North | 470
South | 470 
East  | 460 
West  | 500

**Comment by davidkeymer** [comment]
LinMot calibration: 0.01953125 steps/mm

Jaws Set 1 Offsets:

Jaw | Offset (steps)
---- | -------
North | 471
South | 471 
East  | 471
West  | 571

**Comment by davidkeymer** [comment]
Initialization: Set axis (A,B,C,D) maximum speed to 50 steps/s - `!SV50(A,B,C,D)`
Get axis (A,B,C,D) actual position (steps)- `!GP(A,B,C,D)`
Set axis (A,B,C,D) setpoint (xxxx steps) - `!SPxxxx(A,B,C,D)`
Reset controller after position not reached - `!SR-1` , `!SR+1`

**Comment by John-Holt-Tessella** [comment]
The test one is now in the downstairs office.

**Comment by AdrianPotter** [comment]
Ideally would be tested by someone who is somewhat familiar with motors. @davidkeymer is away this week. @KathrynBaker, might you have time? If not, it will need testing by one of the other devs. @ThomasLohnert can't do it because of issues with his version of Visual Studio.

**Comment by KathrynBaker** [comment]
missing entry in makefile for devLinMotMotor in the support module

**Comment by AdrianPotter** [comment]
Corrected

**Comment by KathrynBaker** [comment]
Code tested and sufficient, created ticket #2219 to cover the need to actually commission the jaws themselves.
