### ISSUE TITLE
HRPD: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2099]
As an instrument scientist, I would like to migrate HRPD to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on HRPD
1. Configuration files matching the current SECI config files are created
1. IBEX is configured for the devices on HRPD.
1. HRPD scripts are converted to genie_python
1. HRPD scientists are trained in how to use IBEX
1. IBEX is tested on HRPD

#### Notes
1. The devices on HRPD are listed on the [HRPD Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/HRPD-Instrument-Details) list

**Comment by kjwoodsISIS** [comment]
In Cycle 2017/01 (starting 2nd May 2017), HRPD will use:
1. [MAXI-50-13](http://www.isis.stfc.ac.uk/sample-environment/low-temperature/cryostats/cryostat-parameters---pdf9781.pdf) Orange (ILL MAXI 50) Cryostat 
1. [CCR60 HRPD Top Loader](http://www.isis.stfc.ac.uk/sample-environment/low-temperature/ccrs/ccr-parameters9786.html) - Sumitomo 4K 100mm sample diameter top loading CCR
1. [Furnace / RAL2](http://www.isis.stfc.ac.uk/sample-environment/high-temperature/high-temperature8447.html)
1. [KF40 Double Quartz Gas Flow Centre Stick](http://www.isis.stfc.ac.uk/sample-environment/gas-handling/centre-sticks/high-temperature-centre-sticks/high-temperature-centre-sticks13756.html)
1. [Gas Panel / Mass Flow Control Gas Panel P1](http://www.isis.stfc.ac.uk/sample-environment/gas-handling/gas-panels/gas-panels8932.html)

**Comment by AdrianPotter** [comment]
Waiting for the LinMot (#2098) and Sample changer (#2173)

**Comment by AdrianPotter** [comment]
Configurations and scripts currently set up on HRPDTEST

**Comment by John-Holt-Tessella** [comment]
Items TODO to finish migration:

- [ ] Remove second eurotherm (they only have one)
- [ ] Sample changer (see ticket)
- [ ] Add second set of jaws

After training session we may need to help Dominic change the block names in the configuration and script.

**Comment by AdrianPotter** [comment]
Although HRPD has a Jaws 2 VI, it doesn't connect to anything. I've confirmed with Dominic that he doesn't expect there to be a 2nd set of jaws. I expect this is for a device that has since been removed. There is a 2nd IOC available should they ever need it.

**Comment by AdrianPotter** [comment]
Just logged on to HRPD and it is reliably reporting as setup. Thanks for fixing, was the problem as predicted?

**Comment by John-Holt-Tessella** [comment]
No. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Other-Troubleshooting#instrument-state-keeps-processing-but-always-goes-back-to-unknown

**Comment by FreddieAkeroyd** [comment]
I've added a note to the above page on how to check the version number

**Comment by AdrianPotter** [comment]
Impeded by ticket #2241

**Comment by kjwoodsISIS** [comment]
Given that HRPD is now using IBEX, is this ticket still impeded?

**Comment by AdrianPotter** [comment]
Actually I think it is. #2241 has not yet been closed. HRPD hasn't been finished being migrated because we haven't approved the sample changer testing

**Comment by kjwoodsISIS** [comment]
OK.  How soon can #2241 be reviewed & closed?

**Comment by AdrianPotter** [comment]
Sorry, I missed this comment. I don't think it will take long to rework and close #2241, but someone else should pick it up now that @DominicOram is otherwise occupied.

**Comment by DominicOram** [comment]
Last time I looked at it I was unable to reproduce the behaviour in https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/13.

**Comment by AdrianPotter** [comment]
I can retest it, but you asked me to show you and you haven't been around :). I've asked @John-Holt-Tessella if someone else can pick up this ticket. I'll double check that the issue is a genuine issue.
