### ISSUE TITLE
GUI: Cannot save synoptics

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2105]
This is based on the failing system test:

CurrentConfigNotInDeleteConfigDialog

Having investigated the workflow manually, when I try and create a new synoptic with any number of components, I get the following error:

![image](https://cloud.githubusercontent.com/assets/10273443/23209861/ef33293a-f8f2-11e6-9b03-4e6ef3cfddd6.png)

**Comment by Tom-Willemsen** [comment]
Same issue as #2090
