### ISSUE TITLE
IMAT: Instron (Stress Rig): OPI

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2109]
As a scientist I need an OPI to control the Instron Stress Rig.

**Acceptance Criteria**
There is an OPI that has the same controls as the Mock OPI, unless there is a reason to remove them, in as similar a layout as is possible.

**General Notes**
This ticket is of high priority in relation to the Instron, it is needed for the cycle starting May 2nd 2017.

The rig in use consists of the channels, Position (POS) on Channel 1, Stress (STRESS) on Channel 2, ans Strain (STRAIN) on Channel 3.

There is a lot of information to support the stress rig work in a folder called Instron Stress Rig in the ICP discussions area of our local SharePoint. Items below are highlighted as being relevant to this ticket directly, some of the other information may be required from the other documents.

The PV names may not have included a $(P) or the correct number and position of `:`, and may not be the final names used, as clarity here was chosen over following the guidelines. Please use appropriate names, and if different from those in the documents - update the documents as you go

**Specific Notes**
For the existing LabVIEW GUI, with annotations on behaviour see the file called VI.jpg

For a mock up that suggests the appearance of the OPI see Mock OPI.png

For relationship between the OPI items with the expected PVs see PVs.xlsx. On the tab labelled OPI to PV the PVs to use for the items in the mock are detailed. Look in the notes for behaviours that need to be considered. .

Note that labels should be taken from the VI rather than the mock OPI. EGU units should also be considered.

The main behaviours needed to be aware of:
There are three channels which should be specified as Position (POS), Stress (STRESS) and Strain (STRAIN), only the Go button for the current control channel (CHANNEL) should do anything.
The channel graphs are against time, and should be cleared by the Clear Graphs button.
The graphs ought to persist betwen views of the OPI (this may need to be written into the IOC)
So long as a scroll bar is applied when necessary, the Status box can be 'shorter', so long as `System OK` fits in easily.
When the status is anything other than `System OK` this control needs to change colour.
There is a label on one of the 'drill down' OPIs that needs to vary according to the control channel, this should be `Position Amplitude (mm)` for POS, `Load Amplitude (MPa)` for STRESS and `Strain Amplitude (%)` for STRAIN. If this label cannot be maintained by the GUI, then a record will be needed in the IOC for it.
If using the lvDCOM solution then the Arbitrary Commands can be undertaken using the LabVIEW panel, and could be hidden. Please note, that I would simply hide the button on the Instron panel to limit the work needed, or even to make that a 'preference' to enable Insturment Scientists to access it specifically when required.

**Comment by KathrynBaker** [comment]
Update to the requirements: the clear graph should clear the channels, a separate button is needed for the channel v channel graph

**Comment by Tom-Willemsen** [comment]
In terms of the graphs;

LVDCOM: Get the graphs working as well as possible, but it is acceptable if clearing the graphs and data persisting when the OPI is reopened don't work.

Final solution (IOC): Supply the last n minutes of data from a waveform in the IOC. Clearing the graphs can clear the data from all clients as only one person will be "in charge".

**Comment by KathrynBaker** [comment]
One thing to note, the IOC solution can’t be n minutes, it has to be from start/clear to present time as the graphs are used as a diagnostic.

**Comment by Tom-Willemsen** [comment]
I've done as much as is practical on this OPI without having either an IOC or an lvdcom vi to talk to.

Will pick this ticket up again once either 2110 or 2111 are complete (or nearing completion)

**Comment by ThomasLohnert** [comment]
Been having a look at the OPI while working on the [IOC ticket](https://github.com/ISISComputingGroup/IBEX/issues/2110). Here's some things that still need to be done:
- The "status" value needs to be converted into a string. Matt suggested that adding a python script to the display textbox is the way to go (under properties > actions). In case you run into any issues, I have been told that Dom knows something about doing this.
- Values set through spinner widgets don't propagate properly. I have been looking at other OPIs to see how they do it, but none of them seem to use it (perhaps for that reason). See if you can find a way to make it work or find an alternative, e.g. just replace them with a regular text input box.
- Channel v Channel window: Selecting a value from one of the combo boxes should set a macro $(CHAN1) / $(CHAN2) which is used as the PV address for the graph x/y axis. Currently, the combo widgets are linked to the :CHANNEL PV to get the list of options (Strain, stress, position). However the combo box additionally selects the current value of CHANNEL (i.e. the currently set Control Channel), which we don't want. Not sure what to do here other than just unlink the PV and hard code the options into the combo widget.

**Comment by ThomasLohnert** [comment]
Continued testing, here's round 2 of changes:
- [ ] Set Channel 1 & 2 for the Channel v Channel graph using a local variable. You can see how this is done on the Lakeshore218 OPI - the checkboxes set a local PV which controls trace visibility via rules on the graph.
- [ ] I'm getting the following error for parsing the Status: 
`2017-03-27 11:54:50 ERROR: Failed to register . 
SyntaxError: ("mismatched input 'pvStr0' expecting NEWLINE", ('<script>', 2, 4, 'var pvStr0 = PVUtil.getString(pvs[0])\n'))`

- [ ] Using actions a la "Write 1 to (pv)" does not work on binary records, as it is parsed a string and then rejected by the IOC. You can write a numerical value from the PV by using a python script as action (The "Logging On/Off" button implements it like that). The following buttons require this change:
    - Go (in Single Channel OPI)
    - Clear graph (Channel v Channel)
    - Stop Rig 
    - Panic Stop 
    - Clear Graphs (Commands)
    - Calculate and Set (Shape)
    - Set (Shape)
    - Start (Waveform)
    - Stop (Waveform)
- [ ] The values in the text boxes for Diameter and Cross Section Area do not update to the new value when obtained using the _Calculate and Set_ or _Set_ buttons, as this only updates the readback, but not the setpoint PV the controls are pointed at. Might need to squeeze in a readback label. 
- [ ] The _Send_ button in the arbitrary commands window is kind of useless as you have to set the value by pressing enter on the text entry anyway, so may as well remove it.

**Comment by ThomasLohnert** [comment]
Had another quick look now that my instrument is working again:
- [ ] I don't think we can make the _Clear Graph(s)_ buttons work in that way, so get rid of them. The graphs can still be cleared in the OPI by right clicking on them.
- [ ] The _Go_ buttons should all be pointing at INSTRON_01:MOVE:GO:SP and be disabled for the channels where $(NAME) != INSTRON_01:CHANNEL (the current control channel)
- [ ] The Status window is coloured red even when it's showing SYSTEM OK. Also, it's currently printing the string value on the java console every .1 seconds

**Comment by Tom-Willemsen** [comment]
I tried very hard to get the Go buttons within the linking containers working. Eventually I found a bit on the documentation which says "macro substitution never happens within scripts" which made this impossible. I've moved the "go" button into the "control channel" box.

Not sure how I can get the LVDCOM to say "System OK" to me to be able to test the issue with the red colouring. Will ask @ThomasLohnert how to do this next week.

**Comment by KathrynBaker** [comment]
We have been *specifically* asked by the instrument scientists to move to using three buttons – there are usability issues with the single button in LabVIEW that they want to eliminate, if it can’t be done by macro substitution it might need to be a case of read the name of the button, read the control channel PV, and unless they match disable the button, otherwise write to the go for that channel.

**Comment by Tom-Willemsen** [comment]
Hi @KathrynBaker thanks for that clarification. 

I think the best approach will be to move away from linking containers and just accept that the duplication is a necessary evil here in that case.

**Comment by KathrynBaker** [comment]
It may well be, given the requirements placed on us by the scientists.

**Comment by John-Holt-Tessella** [comment]
[ ] Set button presses calc and set instead.
 [ ] Cross Sectional Area (mm^2) readback and set do not work
 [ ] Waveform settings runing light does not work
 [ ] Can Waveform settings have title stress rig waveform settings.
 [ ] Waveform Start and Stop buttons don't appear to click anything
 [ ] In logging number of points to average
 [ ] Waveform setting do we want readbacks?

Looked at: Loging settings, Shape and waveform.

**Comment by Tom-Willemsen** [comment]
Clarification from @GDH-ISIS 

The strain item in the dropdown menu is disabled if there is no strain sensor connected. Can ask the stress rig whether it has a strain sensor connected by sending it a `Q307, 3` command, which would be fine for a normal IOC but not so much for an lvdcom.

Gareth's suggestion was to add an indicator to the VI for  "Strain sensor connected", which can be read from the lvdcom and hence the OPI. The logic for this already exists in the block diagram, it just needs an indicator adding to the front panel.

**Comment by John-Holt-Tessella** [comment]
Got as far as stop waveform, but it does not seem to work

- [ ] Stop waveform button does not work
