### ISSUE TITLE
IMAT: Instron (Stress Rig): lvDCOM the VI

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2110]
As a programmer I want the backup of being able to use lvDCOM for the Instron if a more standard set of EPICS modules cannot be generated.

**Acceptance Criteria**
There is an lvDCOM using the appropriate PV names for the VI controls.

**General Notes**
This ticket is of high priority in relation to the Instron, it is needed for the cycle starting May 2nd 2017, especially if the EPICS solution is not in place.

The rig in use consists of the channels, Position (POS) on Channel 1, Stress (STRESS) on Channel 2, ans Strain (STRAIN) on Channel 3.

There is a lot of information to support the stress rig work in a folder called Instron Stress Rig in the ICP discussions area of our local SharePoint. Items below are highlighted as being relevant to this ticket directly, some of the other information may be required from the other documents.

The PV names may not have included a $(P) or the correct number and position of `:`, and may not be the final names used, as clarity here was chosen over following the guidelines. Please use appropriate names, and if different from those in the documents - update the documents as you go

**Specific Notes**
In order to limit the amount of GUI rework that would be needed if this has to be used, where possible the final PV names should be used, which may make this a more involved task that is usual for an lvDCOM wrapper.

The PVs to use, and their relationship to the front panel of the LabVIEW VI are detailed in a tab in PVs.xlsx. 

If using this method the Arbitrary commands should be forced to the VI, or hidden, see Ticket #2109 for the OPI work which has suggestions for managing this.

**Comment by KathrynBaker** [comment]
Note - there were some minor changes needed to the VI, get a new version to test this with

**Comment by Tom-Willemsen** [comment]
- [ ] Please publish `$(P)STRESS:DIAMETER:SP:RBV` and `$(P)STRESS:AREA:SP:RBV` PVs as these are needed for readbacks in the OPI

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/130

**Comment by ThomasLohnert** [comment]
Main bit is reviewed and merged but some missing finishing touches were found just afterwards, so putting this back in review. PR for the missing bits: https://github.com/ISISComputingGroup/EPICS-ioc/pull/138

**Comment by GDH-ISIS** [comment]
I have updated the LabVIEW Stress Rig vi so that the "Stop Waveform" button no longer has the stray character at the end that causes LVDCOM problems. I have also updated ndximat for you.

**Comment by FreddieAkeroyd** [comment]
Can you please confirm the units on STRESS:AREA - originally these were mm^2 but i see they have been changed to m^2 although the comments still say mm^2  I merged the PR for the moment as all the builds were failing otherwise and it is only a small later update

**Comment by FreddieAkeroyd** [comment]
You'll need to merge #2237 to handle either  m^2 or mm^2 though

**Comment by ThomasLohnert** [comment]
It should be mm^2, I was playing around with the units for the regex last week and must have left it in the PR by accident. Given the size of the change, would it be ok to just commit it directly on master?

**Comment by FreddieAkeroyd** [comment]
Yes, I'd just commit to master in this case as it is so minor - we've kind of reviewed it now in this conversation
