### ISSUE TITLE
ENGIN-X / IMAT: Instron (Stress Rig): IOC - Rig Commands

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2111]
As an IBEX user I want to be able to control the Instron Stress Rig natively in EPICS in order to leverage the best use of the system.

**Acceptance Criteria**
There is an IOC in IOCs, and a driver in Support for the Instron.
The interactions for the rig generally has been implemented.

**General Notes**
This ticket is of medium priority in relation to the Instron, ideally it would be in place for the cycle starting May 2nd 2017, however, an incomplete lvDCOM solution as specified in Ticket #2110 means that this can be delayed if required.

The rig in use consists of the channels, Position (POS) on Channel 1, Stress (STRESS) on Channel 2, ans Strain (STRAIN) on Channel 3.

There is a lot of information to support the stress rig work in a folder called Instron Stress Rig in the ICP discussions area of our local SharePoint. Items below are highlighted as being relevant to this ticket directly, some of the other information may be required from the other documents.

The PV names may not have included a $(P) or the correct number and position of `:`, and may not be the final names used, as clarity here was chosen over following the guidelines. Please use appropriate names, and if different from those in the documents - update the documents as you go

**Specific Notes**
PVs.xslx contains the list of PVs, and an indication of their interactions, the only entries to undertake as part of this ticket are those in the Rig commands section.

This ticket will see the creation of the initial IOC, other features will be added under other tickets.

Some clarity, and more information can be found in Working through the block diagram.docx.

The Command reference.docx file has the subset of commands that are used by the existing LabVIEW driver, Stress Rig - GPIB.pdf has the full list of commands.

**Comment by Tom-Willemsen** [comment]
review with 2115
