### ISSUE TITLE
ENGIN-X / IMAT: Instron (Stress Rig): IOC - Channel Commands

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2112]
As an IBEX user I want to be able to control the Instron Stress Rig natively in EPICS in order to leverage the best use of the system.

**Acceptance Criteria**
There are additions to the protocol and database files used by the IOC created in Ticket #2111 which covers the interactions for channels

**General Notes**
This ticket is of medium priority in relation to the Instron, ideally it would be in place for the cycle starting May 2nd 2017, however, an incomplete lvDCOM solution as specified in Ticket #2110 means that this can be delayed if required. This ticket should be done after Ticket #2111.

The rig in use consists of the channels, Position (POS) on Channel 1, Stress (STRESS) on Channel 2, ans Strain (STRAIN) on Channel 3.

There is a lot of information to support the stress rig work in a folder called Instron Stress Rig in the ICP discussions area of our local SharePoint. Items below are highlighted as being relevant to this ticket directly, some of the other information may be required from the other documents.

The PV names may not have included a $(P) or the correct number and position of `:`, and may not be the final names used, as clarity here was chosen over following the guidelines. Please use appropriate names, and if different from those in the documents - update the documents as you go

**Specific Notes**
PVs.xslx contains the list of PVs, and an indication of their interactions, the only entries to undertake as part of this ticket are those in the Channel sections - Generic Channel, Position Channel, Stress Channel and Strain Channel.

Note that there are macros and their values to be used listed in the spreadsheet.

The extra information (e.g. the equations TO and FROM) for a channel also needs to be loaded via the st.cmd at this point manually rather than have the IOC automate based on a channel type that is fed in.

Some clarity, and more information can be found in Working through the block diagram.docx.

The Command reference.docx file has the subset of commands that are used by the existing LabVIEW driver, Stress Rig - GPIB.pdf has the full list of commands.

**Comment by kjwoodsISIS** [comment]
Need to do #2111 first.

**Comment by AdrianPotter** [comment]
- [ ] The "Going to setpoint" LED remains lit even when the SP appears to have been reached
- [ ] The Control channel dropdown has a UDF alarm, even though position has been selected as the initial channel
- [ ] The accuracy of the SPs are to 0dp. Is that intentional? It seems like greater accuracy would be needed. I note that the PREC field hasn't been set on those PVs so the 0 is implicit
- [ ] When the Diameter SP is updated, the cross-sectional area SP PV is updated simultaneously but not vice-versa. Changing the CSA SP PV has no effect on the diameter PV

**Comment by Tom-Willemsen** [comment]
A couple of integration tasks still need to be done.

- [ ] The `INIT` routine needs the channel-specific commands adding to it.
- [ ] The `AXES:ABS` PV needs implementing
- [ ] Need to disable MBBI options in `$(P)CHANNEL` if `$(P)$(CHAN):TYPE` != `$(CHAN_EXP_TYPE)`
- [ ] The `STOP` records (`$(P)STOP:_CALC_RAMP`, `"$(P)STOP:_CALC_WAVEFORM` and `$(P)STOP:_STOP_WAVEFORM`) need pointing at the waveform records once they've been implemented as part of #2113

**Comment by AdrianPotter** [comment]
Finish review once missing functionality has been added. Note that `AXES:ABS:TRUE` and `AXES:ABS:FALSE` as detailed on the PVs spreadsheet has been implemented on branch `Ticket2113...`. Reasonably this could be simplified to a single `AXES:ABS` record. Suggest doing it here and then I'll worry about the merge in #2113

**Comment by AdrianPotter** [comment]
Also, Tom is on holiday for the next two weeks so please could someone else pick up the rework

**Comment by AdrianPotter** [comment]
I'll group rework changes here:

- [ ] Fix review request for IOC test framework:
    - RECSIM tests failing owing to no backdoor command in LewisNone
    - Intermittent failures on several DEVSIM tests
- [ ] All control channels disabled by default from the emulator
- [ ] Text in selected channel drop down on the OPI is truncated when a disabled channel is selected
- [ ] Can set position setpoint and GO from the OPI even when the position channel is reportedly disabled

**Comment by AdrianPotter** [comment]
I still get a test failure in RECSIM:

```
Running tests...
----------------------------------------------------------------------
..SSSSSSSS.FSSS.SSSS..SS.........S....
======================================================================
ERROR [15.036s]: test_WHEN_control_channel_is_requested_THEN_an_allowed_value_is_returned (tests.instron_stress_rig.Instron_stress_rigTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\instron_s
tress_rig.py", line 135, in test_WHEN_control_channel_is_requested_THEN_an_allowed_value_is_returned
    self.ca.assert_that_pv_is_one_of("INSTRON_01:CHANNEL", ["Stress", "Strain", "Position"])
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 105, in assert_that_pv_is_one_of
    raise AssertionError(error_message)
AssertionError: Expected one of ['Stress', 'Strain', 'Position']: actual Position - disabled
```
