### ISSUE TITLE
ENGIN-X / IMAT: Instron (Stress Rig): Logging to file

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2114]
As a scientist using the Stress Rig, I want to create a plain text log file log of certain values (position, stress (load) and strain) that is separate to the neutron runs.

#### Acceptance Criteria
1. I can toggle the status of Stress Rig logging to file
   1. permitted states are ON and OFF
   1. I can use a script to toggle between ON and OFF states
1. The Stress Rig OPI must:
   1. clearly display the current status of the Logging to File toggle
   1. allow the user to toggle between ON and OFF states
1. By default (i.e. when the IOC is re-started), logging should be turned OFF
1. <del>The current state of the toggle should be persisted when the Stress Rig IOC is turned off</del>
1. When logging is turned ON (having previously been OFF), the system must note and persist the time of this event (time-A). (This is stored as a record of all event of when logging is switched on or off)
1. When logging is turned OFF (having previously been ON), the system must 
   1. note the time of this event (time-B).
   1. generate a log file covering the period time-A to time-B
   1. erase the persisted value of time-A
1. If the Stress-Rig IOC is switched off while logging is switched ON, the Stress-Rig IOC should generate a log file covering the period time-A to the time of switch-off before terminating.
1. <del>If the Stress Rig IOC is re-started while logging is switched ON, the Stress Rig IOC should note and persist a new time-A.</del>
1. On generating a new Stress Rig log file, the Stress Rig IOC will create a new plain text file
   1. named according to the following naming convention of the form `INSTRON_01_2017-07-26T13_46_50.dat`.
   1. the new file must be created in the `C:\logs\INSTRON_01` folder (so that it gets archived)
1. When the Stress Rig IOC has finished writing a log file, it should mark the file as `read-only` (this is the signal that the file is ready to be archived)
1. A Stress Rig log file must be a tab-separated values file with a 5-line header block, as follows:
   1. Line 1: “Cross Sectional Area = “999.999999   (where 999.999999 represents a positive numerical value with 6 decimal places; there can be any number of 
places to the left of the decimal point)
   1. Line 2: “Gauge Length for Strain = “999.999999   (where 999.999999 represents a numerical value as described above)
   1. Line 3: “RB Number = AAA  (where AAA is a variable number of ascii characters)
   1. Line 4: _intentionally left blank_
   1. Line 5: comprises the fields “Date/time”, “Run Number”, “Position”, “Load”, “Strain” separated by tab `\t` characters
1. From Line 6 onwards, the contents of a Stress Rig log file must comprise the following fields:
   1. Date/Time written as YYYY-mm-DDTHH:MM:SS.sss
   1. Run Number written as  AAA  (where AAA is a variable number of ascii characters)
   1. Position written as s999.999999 (where 999.999999 represents a numerical value with 6 decimal places; there can be any number of places to the left of the decimal point, s represents an optional sign)
   1. Load written as s999.999999 (where 999.999999 represents a numerical value as described above)
   1. Strain written as s999.999999 (where 999.999999 represents a numerical value as described above)
1. Each field in the Stress Rig log file must be separated by a tab `\t` character
1. Each line in the Stress Rig log file must be terminated with a standard terminated command line for the os.

#### General Notes
This ticket is of medium priority in relation to the Instron, ideally it would be in place for the cycle starting May 2nd 2017, however, an incomplete lvDCOM solution as specified in Ticket #2110 means that this can be delayed if required. This would need to be added to the IOC created in Tickets #2110, #2111, #2112 and #2113

The rig in use consists of the channels, Position (POS) on Channel 1, Stress (STRESS) on Channel 2, ans Strain (STRAIN) on Channel 3.

There is a lot of information to support the stress rig work in a folder called Instron Stress Rig in the ICP discussions area of our local SharePoint. Items below are highlighted as being relevant to this ticket directly, some of the other information may be required from the other documents.

The PV names may not have included a $(P) or the correct number and position of `:`, and may not be the final names used, as clarity here was chosen over following the guidelines. Please use appropriate names, and if different from those in the documents - update the documents as you go

**Specific Notes**
There is an example of a log file called New Version - Stress Rig-2017 02 19, February Sunday-11,33,05.dat in the [Instron Stress Rig folder](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FInstron%20Stress%20Rig&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) on the ICP Discussions SharePoint.

It is likely that this will need to be a C function that can be included somehow.

If it can be made a generic solution which reads in a number of PVs and records them to a suitable directory then it could find use elsewhere in time that would be beneficial.

**Comment by kjwoodsISIS** [comment]
We really want to create a generic solution - i.e. create a log file from the archive.

**Comment by samueljackson92** [comment]
If we create a generic solution we should also add the logging to the new Superlogics IOC. See  ISISComputingGroup/IBEX#2378

**Comment by kjwoodsISIS** [comment]
@samueljackson92 - Yes, we should try to use the generic solution where ever it is appropriate.  The Superlogics IOC sounds like another good case.
We should also ask ourselves whether the special log files are better created "on-demand" than "on-the-fly".  At the moment, the special logs are created "on-the-fly" - the user switches logging on, the system continually logs the requested data until the user switches logging off.  However, the data is being logged to the archive anyway, which means that the log file could be created at any point - the user merely needs to say "I want PVs X, Y & Z from time-A to time-B".

**Comment by KathrynBaker** [comment]
Or even the user says “start logging” we note that time, they say “stop logging” and we just get the appropriate PVs as we already know time-A and time-B

**Comment by kjwoodsISIS** [comment]
**Original text of ticket:**
As a scientist I want to write a log of certain values that is separate to the neutron runs.

#### Acceptance Criteria
When logging is turned on the selected values should be logged, a new file should be created every time the IOC is started, whenever logging is restarted after a stop.

**Comment by ChrisM-S** [comment]
Currently, the files are essentially lost on the NDXENGINX data drive in folder `C:\logs\Stress Rig\cycle_yy_n`, (they never get archived permanently), if someone chooses they could be deleted without trace.  The last time they were manually copied to the data archive was 2012!

If any of this is being automated/generalized it would be good to decide on the status of "random" log files and whether they should be archived permanently or not (or how long they should be kept).

**Comment by kjwoodsISIS** [comment]
@Chris - I have revised the ticket description to make it clear that these log files should be archived.  I have said in the acceptance criteria that the files should be saved to the ``/var`` folder and marked as ``read-only``.  Are these the correct criteria for ensuring that a file gets archived automatically?

**Comment by ChrisM-S** [comment]
Thank you @kjwoodsISIS.  Actually, having looked at the situation on IMAT, it would be better to specify that the files are still created in `C:\logs\Stress Rig` this will be linked into the same underlying disk as `\var` anyway and will allow dual working (all instruments have the `C:\logs\Stress Rig` folder now) as does the standalone PC for running the stress rig.  The Read only setting would be very helpful as I can then trigger copying of closed/finished files at the end of run (and then removal from the local machine around the next cycle).

The logs folder is really a special case of the `\data` folder but as you can see everything EPICS (apart from autosave) is in the logs tree now anyway!

![image](https://user-images.githubusercontent.com/3035405/27343799-f80d5efe-55db-11e7-9c5c-b1b4dd5c2c49.png)

To generalize, we might as well bite the bullet and create a "C:\logs\superlogics" folder when it becomes needed.  I think that it will be very easy to create separate size limiting and archiving policies for the different folder trees under logs (I'm already doing most of this for WISH and IMAT)

**Comment by John-Holt-Tessella** [comment]
Following are not in agreement

3. By default (i.e. when IBEX is re-started), logging should be turned OFF
4. The current state of the toggle should be persisted when the Stress Rig IOC is turned off
5.If the Stress-Rig IOC is switched off while logging is switched ON, the Stress-Rig IOC should generate a log file covering the period time-A to the time of switch-off before terminating.
6.If the Stress Rig IOC is re-started while logging is switched ON, the Stress Rig IOC should note and persist a new time-A.

To confim: Initially implemented as when the IOC switches in logging is switched off. A log file we be produced for logging on to switch off.

**Comment by kjwoodsISIS** [comment]
Persisting the state of the logging toggle is proving to be difficult.  After discussion, we agreed that it would be better to keep the logic simple and the behaviour of the logging switch clear.  The Acceptance Criteria have been changed from:
> 3. By default (i.e. when IBEX is re-started), logging should be turned OFF
> 4. The current state of the toggle should be persisted when the Stress Rig IOC is turned off

to

> 3. By default (i.e. when the IOC is re-started), logging should be turned OFF

**Comment by John-Holt-Tessella** [comment]
Superlogics does not having logging after more investigation of the VI

**Comment by kjwoodsISIS** [comment]
Re: Superlogics - in principle, because blocks get logged in the archiver, we could generate a log file for the Superlogics (or any other device for that matter).  However, that is something for the future - no need to to anything about it now.
