### ISSUE TITLE
ENGIN-X / IMAT: Instron (Stress Rig): Emulator

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2115]
As a programmer I would like an emulator of the Instron Stress Rig.

**Acceptance Criteria**
There is an emulator that can be run

**General Notes**
This ticket is of medium priority in relation to the Instron. There are two rigs on site, and until the cycle starting 2nd May 2017, there is a high chance of being able to test by communicating with an actual device.

The rig in use consists of the channels, Position (POS) on Channel 1, Stress (STRESS) on Channel 2, ans Strain (STRAIN) on Channel 3.

There is a lot of information to support the stress rig work in a folder called Instron Stress Rig in the ICP discussions area of our local SharePoint. Items below are highlighted as being relevant to this ticket directly, some of the other information may be required from the other documents.

The PV names may not have included a $(P) or the correct number and position of `:`, and may not be the final names used, as clarity here was chosen over following the guidelines. Please use appropriate names, and if different from those in the documents - update the documents as you go

**Specific Notes**
The Command reference.docx file has the subset of commands that are used by the existing LabVIEW driver, Stress Rig - GPIB.pdf has the full list of commands.

**Comment by Tom-Willemsen** [comment]
review with 2111
