### ISSUE TITLE
GUI: Evaluate use of Codacy

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2123]
Michael has been evaluating Codacy as an evaluation tool for source code and pull requests. An example can be seen here:

https://www.codacy.com/app/michael-hart/ibex_gui/pullRequest?prid=531337

Although we became aware of this accidentally, it looks very useful and caught several issues in the PR for #2001 that had been overlooked by both Thomas and me.

I think it would be valuable for our code quality to review the tool and consider introducing it to Ibex. It reveals a wide range of issues that aren't currently captured by check style including security and error-prone code.

vs code climate vs sonarQube (see ticket)

**Comment by GRyall** [comment]
We have now introduced ruff and pyright checks on our repos that substantially address this issue.
