### ISSUE TITLE
VESUVIO : Dataweb not showing

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#2127]
May I query why the Dataweb page for VESUVIO is not showing? IBEX client appears fine.

Note : It was operational yesterday, so I would expect this not to be a firewall issue (as previously found on IMAT)

**Comment by DominicOram** [comment]
Apologies, I've fixed this now. It's due to a mistake someone made when first deploying to VESUVIO, i'll add in a ticket to make this less likely to happen in the future.

**Comment by DominicOram** [comment]
That's a bit unfair I guess, it was a mistake made when deploying mixed with a mistake I just made when updating something.

**Comment by Tom-Willemsen** [comment]
Vesuvio dataweb is now working and ticket 2128 has been created to look at the root cause, so marking this as completed.
