### ISSUE TITLE
Dataweb: Better deployment strategy

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2128]
The current deployment strategy for JSON bourne on extaweb is to manually copy across files from a git repo. It would be better if it was under a git repo on extaweb and then switched to master/release branches when required. This will avoid the mistake I made in https://github.com/ISISComputingGroup/IBEX/issues/2127 where the addition of VESUVIO to the list of instruments was overwritten when a patch was made.

**Comment by John-Holt-Tessella** [comment]
Check installing git on an external web server is ok.

**Comment by DominicOram** [comment]
* I have installed git on NDAEXTWEB
* Updated documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release
* Updated json_bourne at https://github.com/ISISComputingGroup/JSON_bourne/pull/28

**Comment by DominicOram** [comment]
This has put all the things in place to deploy the dataweb in a better way but I have not actually done the deployment as it will bring the dataweb down. As a final test the steps outlined in the wiki should be performed in  a shutdown. Please leave this ticket open until this is done.

**Comment by Tom-Willemsen** [comment]
Deployment process approved, as discussed, we will need to switch to the deploy process on the maintenance day (don't want to do it during user run).

**Comment by DominicOram** [comment]
Now deployed
