### ISSUE TITLE
ALF : Dataweb not showing

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#2129]
May I query why the Dataweb page for ALF is not showing? IBEX client appears fine.

**Comment by DominicOram** [comment]
Same issue/fix as https://github.com/ISISComputingGroup/IBEX/issues/2127

**Comment by AdrianPotter** [comment]
I should have done this for Vesuvio, but please could we document the problem under troubleshooting:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Other-Troubleshooting

**Comment by DominicOram** [comment]
Added https://github.com/ISISComputingGroup/JSON_bourne/blob/master/webserver.py and made https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#update-the-web-dashboard a little more specific. Ticket #2132 will be a more permanent fix.
