### ISSUE TITLE
POLARIS: IOC and OPI for Mk2 Chopper

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2130]
As a scientist, I need an IOC and OPI for the Mk2 Chopper, so that I can control the chopper on POLARIS

#### Acceptance Criteria
1. I can adjust the settings of the POLARIS chopper via a GUI.
1. I can adjust the settings of the POLARIS chopper via a geneie_python script

#### Notes
1. The Mk2 chopper communicates via a serial port (c.f. the Mk3 chopper which uses an Ethernet port).
1. GEM also uses Mk2 choppers.

**Comment by kjwoodsISIS** [comment]
@davidkeymer believes it is simply a stream device.  It returns a status byte which will need interpretation.

**Comment by FreddieAkeroyd** [comment]
@GDH-ISIS I think this would be a good ticket for you to do, I will arrange any necessary CSS and Stream device training

**Comment by davidkeymer** [comment]
[ISIS_MK2_Chopper_Computer_Interface.pdf](https://github.com/ISISComputingGroup/IBEX/files/840997/ISIS_MK2_Chopper_Computer_Interface.pdf)

All commands in manual used in VI, except `RA` ("Read All") which occasionally causes the communications to hang.  Solution is to read the individual values separately.  See the VI code for more information.
