### ISSUE TITLE
Dataweb: Get list of instruments from the global PV

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2132]
At the moment the list of which instruments JSON_bourne is connected to is hardcoded, we should instead reuse the PV that the GUI looks at. This will avoid mistakes in adding the instrument.

**Comment by John-Holt-Tessella** [comment]
Discuss putting this into central MySQL

**Comment by ThomasLohnert** [comment]
There is also a step in the IBEX install script about adding a new instrument to JSON bourne, that should be removed/edited as appropriate once this has been done

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/JSON_bourne/pull/30
