### ISSUE TITLE
IOC: Allow multiple directories for calibrations

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2133]
Setup IOC which use calibrations to have the base CALIB_BASE_DIR set to `C:/Instrument/Settings/config` and create macros for the dirs containing the files. E.g. eurotherm SENS_DIR is a macro defaulting to common `common/temp_sensors`.
This will allow us to point at a calibration file which is stored locally for the instrument if necessary. 
We should create in the configuration dir a directory for local calibration files on all machines for cases where they want a local config file. Documentation should be updated to reflect the split of configuration. I.e. only calibration which will only ever be used locally and usally temporarily should be added to the configuration all other files should be added to the common repository through the calibration file contrller (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files and )

**Comment by ThomasLohnert** [comment]
Changes by device (for those that use calibration files):
- Eurotherm: Implemented a macro that tells the IOC whether to look in the common calibration directory or the local instrument config directory.
- Danfysik: same as above
- Barndoors: No changes - records are loaded in place in motor configuration files, so macro needs to be set directly in there
- Keithley: Code for loading calibration files not on master branch yet. Can be implemented in the future if needed.

PRs:
https://github.com/ISISComputingGroup/EPICS-ioc/pull/335
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/134

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by ThomasLohnert** [comment]
I would call it a 1.
