### ISSUE TITLE
GUI Log view: high resource usage

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2136]
Currently the log view can be a bit slow and uses lots of CPU when it has lots of messages in it.

This is because we're calling `.refresh()` on the table containing *all* log messages every second or so. This reloads *all* the information from the model (as per the javadoc) and so this is a very heavyweight operation. Doing it once per second with many log messages causes the main (GUI) thread to use a lot of CPU.

See if there is a lighter alternative for putting new data into the table than `.refresh()`. Alternatively we could only load the last 500 messages into the view by default (and only get the full 10,000 which are stored in the model on request). For example we could have a dropdown menu saying "number of log messages to show" with the default at 500 but allowing the user to select higher options if they want.

See the `setMessageData` method in `uk.ac.stfc.isis.ibex.ui.log/widgets/logdisplay.java` for where `refresh` is called.

**Comment by FreddieAkeroyd** [comment]
I think it might also be a good idea to relook at our logging architecture #2137

**Comment by KathrynBaker** [comment]
There is also a long standing ticket to look at how we are getting this data and considering the SQL queries (#734), as at the moment the search is far from ideal – low priority because the only people likely to search it in that way for fault finding is probably us, and I at least would just go straight to the database… Superseding this by reconsidering logging completely – yes, great (#2137), incorporating it into another ticket, please no, just look at the refresh rate as part of this ticket. There are a few other tickets related to this log, #1943, #1945, #1955, #2062 system, all of which are meant to be minor tweaks to improve usability. Maybe this needs a component steward specifically as any changes will need to be made at both GUI and server sides.

**Comment by Tom-Willemsen** [comment]
Yes, I agree, this ticket should be very specifically about getting the GUI to not be slow (and only that - no backend changes to how the logging works as part of this ticket). Hopefully the limited scope of "get the GUI to not be slow" will mean that this ticket isn't massively big in time terms.

I hadn't actually noticed this ticket's similarity to #2062. Depending on which fix is chosen (reduce the refresh rate, or reduce the number of stored messages), it might also fix that one.

**Comment by ChrisM-S** [comment]
For want of a better place to mention this, there is a question about what the client is intended to do.  We've been quite quick to implement what I would term "real" data transfer to the client in two places, and I wonder if this is really appropriate when what we might simply want is a "view" of selected server data.

1) The log records - do we really want them on the client at all? - do they have an onward destination from the client to somewhere else which would require any more than a view of selected records - e.g. a download?

2) The DAE histogram views - ditto? this is costing us a cool 1MB/s of network bandwidth per running client if I remember the figure rightly (roughly low res video bandwith) for just four almost stationary plots!

Imagining the IBEX client as a web client for a moment, either of these would simply be a rendering view (perhaps with a nice bit of HTML5 for the plots) but both simply fed by a query on the required data from the server.

If the client is framed as a means of displaying simple graphics (icons, bitmaps or text) is there any need for more?  the user customisation would be the query supplied to the server for the data - so not every client would show the same things for logs or plots.

**Comment by Tom-Willemsen** [comment]
@ChrisM-S I think that discussion is probably more appropriate for #2137

**Comment by ChrisM-S** [comment]
Thanks Tom, tried it there and thought in the end it deserved its own ticket!

**Comment by John-Holt-Tessella** [comment]
What is an acceptable level of data to pull across the network? 
I thought that we had already decided to monitor the network traffic and respond if it becomes a problem.

**Comment by DominicOram** [comment]
Potentially look at LazyContentProvider for the TableViewer. However, we are currently being pretty poor with our use of databinding to the TableViewer so I suspect cleaning some of this up will increase speed.

**Comment by Tom-Willemsen** [comment]
As a first step, just do the databinding properly. Look at using a `DataboundTable` or similar. See if this improves the situation "enough" or whether we do need to go down the route of a `LazyContentProvider`.

**Comment by Tom-Willemsen** [comment]
There is a certain amount of work towards this ticket on a branch.

The "real" solution is to rewrite the entire view as there's a lot of mess/technical debt in this view

**Comment by KathrynBaker** [comment]
As with #2062, #8364 covers this
