### ISSUE TITLE
IBEX logging - design review

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2137]
I think we should consider if our log message infrastructure is sufficient or whether moving towards some of technologies being investigated by the ESS in-kind work (e.g. graylog) would help. I see InfluxDB for logs was mentioned on the CSStudio mailing list too.

**Comment by mattclarke** [comment]
It would be useful to look at the use cases for this too. Especially regarding the GUI side.

**Comment by mattclarke** [comment]
Stolen from #2140, as I think it is more appropriate here:

```The log records - do we really want them on the client at all? - do they have an onward destination from the client to somewhere else which would require any more than a view of selected records - e.g. a download?```

**Comment by DominicOram** [comment]
We have a couple of places where we have known log messages being produced but they're actually not affecting functionality (https://github.com/ISISComputingGroup/IBEX/issues/2318, https://github.com/ISISComputingGroup/IBEX/issues/1948). This could be overwhelming to a user seeing it on the GUI.

**Comment by KathrynBaker** [comment]
Meeting was held 6/6/2017, and the following tickets were created to cover the first iteration of this work, including some of the later tickets to be taken on:

#2389 
#2390
#2391
#2392
#2393
#2394

**Comment by AdrianPotter** [comment]
Thanks Kathryn. Have the minutes of the meeting been added to the Wiki? From your comment, it sounds like there will be future work after this first iteration. It would be useful if the notes on what that might involved were stored in a team-accessible place. Thanks.

**Comment by KathrynBaker** [comment]
Powerpoint, with notes included from the meeting in the notes area to act as minutes is available from: http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/IBEX%20Logging%20Review.pptx
