### ISSUE TITLE
GEM: IOC and OPI for the "Beamscraper" Jaws

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2138]
As a scientist, I would like the IBEX to provide an IOC and OPI for the "Beamscraper" Jaws, so that I can control them on GEM.

#### Acceptance Criteria
1. I can adjust the settings of the "Beamscraper" jaw set on GEM.
1. I can view a schematic representation of the blades (N, S, E, W) of the jaw set
1. I can adjust the settings of the jaw set by setting the N, S, E, W positions or by setting 
   values for the horizontal & vertical gap and horizontal & vertical centre positions.

#### Notes
1. The GEM "Beamscraper" jaw set is unique to GEM.  The blades are driven by a LinMot (see HRPD #2098).  This is in contrast to all the other jaw sets on GEM, which are driven by Galils.
1. The "Beamscraper" jaw set is controlled by a non-linear mechanism.  The current LabVIEW uses a calibration formula to convert requested jaw positions into motor movements.  The IOC will need to replicate that formula.  Careful testing will be required.

**Comment by davidkeymer** [comment]
LinMot calibration: 0.01953125 steps/mm

Jaw | Offset | Read Calibration Curve | Write Calibration Curve
---- | -------| ------ | ----------
North | 2710 | x + 0.025*x | x - 0.025*x
South | 1530 | x + 0.025*x | x - 0.025*x 
East  | 2200 | 	(-0.12038 + 0.06452 * x  + 0.02998 * x**2)/0.9 | (x - 0.1*x) , ((-0.06452 + sqrt(0.06452**2 + 4*0.02998*(0.12038 + x))) / (2*0.02998)) 
West  | 2200 | 	(-0.12038 + 0.06452 * x  + 0.02998 * x**2)/0.9 | (x - 0.1*x) , ((-0.06452 + sqrt(0.06452**2 + 4*0.02998*(0.12038 + x))) / (2*0.02998))

**Comment by KathrynBaker** [comment]
Notes from the VI:

Number of Nodes: 293
Cyclomatic complexity:  34
Screenshot:
![image](https://user-images.githubusercontent.com/10552381/33212642-0b3c3ef8-d11c-11e7-8bdb-48deaaf6c8a2.png)

Note the calibrations and offsets recorded by David previously (note that the first equation calculates the x used in the second equation where there are two).
Comms is standard serial.
Much of this may be covered by the standard linmot motor and the jaws records.
When writing a setpoint use the equation above, that value is then divided by the calibration. This calculated value is the subtracted from the offset and sent to the linmot. (Except south which is added.)
When reading the value returned is subtracted from the offset, multiplied by the calibration value and put through the equations above before reporting it back to the user. The gaps are set to the sum of the appropriate jaws.
The setpoints are all set to 5 when home is pressed.
The setpoints are set to half the appropriate gap when set symmetrical gaps is used - this might be covered by using a standard jaws setup from our point of view.
There is some tolerance checking, tolerance is set to 1.00, and is based on the presented value.

**Comment by AdrianPotter** [comment]
See the EnginX Jaws for an example of non-linear calibration setup using Linmots

**Comment by DominicOram** [comment]
Maths can be simplified to:

Jaw | Offset | Read Calibration Curve | Write Calibration Curve
---- | -------| ------ | ----------
North | 2710 | 1.025*x | 0.975*x
South | 1530 | 1.025*x | 0.975*x 
East  | 2200 | 	-0.13376 + 0.07169 * x  + 0.03331 * x**2 | (-0.07169 + sqrt(0.07169**2 + 4 * 0.03331 *(0.13376 + x))) / (2*0.03331)
West  | 2200 | 	-0.13376 + 0.07169 * x  + 0.03331 * x**2 | (-0.07169 + sqrt(0.07169**2 + 4 * 0.03331 *(0.13376 + x))) / (2*0.03331)

**Comment by DominicOram** [comment]
The limits for the values that the user can set are:

Axis | Min | Max
--- | --- | ---
H Gap | 0.2 | 25
V Gap | 0.2 | 40
North | 0.1 | 20
South | 0.1 | 20
West | 0.1 | 12.5
East | 0.1 | 12.5

**Comment by DominicOram** [comment]
As I am going away for a week I will put this back in the ready column. The following has already been done:
* Soft motors for the axes (https://github.com/ISISComputingGroup/EPICS-motorExtensions/compare/Ticket2138_gem_beamscrapper_jaws)
* IOC tests for these (https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket2138_GEM_beamscraper_jaws)

The following needs to be done:
* Confirm my maths above
* Confirm that you can set jaws up to point at the soft motors
* Confirm the standard jaws OPI then behaves as expected
* Work out how to implement the south offset in the linmot IOC (its the inverse of other offsets)
* Add the homing
* The linear axes (North & South) potentially don't need the soft motors I've created, you should be able to roll it into the motor resolution. (But i'm not 100% sure because the read and write aren't exact inverses of each other)
