### ISSUE TITLE
IBEX Client - (Short) Design Review of the purpose/functionality of the IBEX client.

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#2140]
maybe could be done in 2 or three minutes in a backlog groom!
There is a question about what the client is intended for going forward - what should it do and what should it not do.  We've been quite quick to implement what I would term "real" data transfer to the client in two places.  I wonder if this is appropriate when what we might simply want is a "rich view" of selected server data.  This ticket is just a placeholder to ask and decide on a few questions.
For example:
1. The log records - do we really want them on the client at all? - do they have an onward destination from the client to somewhere else which would require any more than a view of selected records - e.g. a download?
2. The DAE histogram views - ditto? this is costing us a cool 1MB/s of network bandwidth per running client if I remember the figure rightly (roughly low res video bandwith) for just four almost stationary plots!
Imagining the IBEX client as a web client for a moment, either of these would simply be a rendering view (perhaps with a nice bit of HTML5 for the plots) but fed by a query on the required data from the server and probably transferred as text JSON.
If the client is framed as a means of displaying simple graphics (icons, bitmaps or text) is there any need for more? the user customisation would be the query supplied to the server for the data - so not every client would show the same things for logs or plots.
3. Video (or picture stream i.e. one image then another from an IOC) whilst it might cost some bandwidth depending on the frame rate or resolution, it is quite likely someone would expect to see an image of a device, a heat-map style plot or image from tomography on an OPI as part of the implementation of a control device.
4. Is there anything that the user might wish to save locally/download from the client interface (other than the last instrument settings) which might require data transfer from the server, or extra rendering from the client (e.g. PDF of full synoptic, block details, a print quality representation of the GUI).
## Review - considered

- [x] Do we want the log records on the client or just a view?

- [x] Histogram pictures (rendered from data on the client or a view rendered on the server)?

- [x] Can we do video, possibly the missing thing other clients might show?

- [x] Does the client provide access to any server data in an onward fashion for something else?

- [x] How does our forward look on client usage (location and numbers) affect the above?

**Comment by mattclarke** [comment]
I think point 1 might be better suited to #2137, so I have repeated it there and we can skip it here.

**Comment by ChrisM-S** [comment]
@John-Holt-Tessella asked a very valid question in #2136 which I've moved here because it reminded me to consider client access via WiFi too.

> What is an acceptable level of data to pull across the network?
>  I thought that we had already decided to monitor the network traffic and respond if it becomes a problem
> 

The only pearl of Wisdom I might offer is that (like memory usage and disk space), it can be quite simple things that make big improvements in resource usage - and even if we were never run a client off an instrument machine, it wouldn't do any harm to improve the implementation of the client/server part of the design.

**Comment by FreddieAkeroyd** [comment]
2. Dropping the update frequency would be a simple way to drop the bandwidth. I think it is 4 graphs * 10 Hz * 8000 channels * 4 bytes = only 320Kb /s though? The main issue is the 8000 channels - it is sending more than it needs (larmor is currently only using 1000 channels). Dynamic array sizing in channel access didn't used to be possible, but has been added recently.   
3. Re video: i've already incorporated ffmpeg from areaDetector and was going to try that for ZOOM live view.

**Comment by FreddieAkeroyd** [comment]
epics v4 would solve some of these issues...

**Comment by John-Holt-Tessella** [comment]
Basically we have resolved these issues as either monitor the situation or wait for it to be requested,
