### ISSUE TITLE
GUI: Create release containing fix of #2074

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2141]
A number of users have reported the error of not being able to see synoptics after starting the GUI. This is disruptive to their workflows and has resulted in frequent contact with support. Once #2074 is finished, we should create a patched branch and offer the fix to instrument scientists.

**Comment by AdrianPotter** [comment]
- [ ] Create a release branch for the patch
- [ ] Check that the new contains the fix for #2074
- [ ] Email the instrument scientists offering the patch and asking when a good time would be to upgrade
- [ ] Upgrade clients as requested

**Comment by AdrianPotter** [comment]
Awaiting completion of #2074

**Comment by AdrianPotter** [comment]
I've created the release. Please can someone independently verify it and I will email the instrument scientists to offer an upgrade.

**Comment by Tom-Willemsen** [comment]
The `install_client.bat` script looks for a genie_python in `Y:\Kits$\CompGroup\ICP\Releases\3.1.1` which currently doesn't exist. Either copy the genie_python folder over from 3.1.0 or modify the installation script so that it doesn't install genie_python (which shouldn't be necessary anyway...)

**Comment by AdrianPotter** [comment]
Done :)

**Comment by Tom-Willemsen** [comment]
Release appears to work, moving this to completed.
- Checked under help -> about that the version number is 3.1.1
- Have not reproduced the synoptics bug in #2074 (but it is hard to reproduce)
