### ISSUE TITLE
NICOS: Receive a line-by-line view of a script

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2149]
After https://github.com/ISISComputingGroup/IBEX/issues/1364 we can send a script to NICOS. The next logical step is to get the feedback for which lines are running. 

To complete this ticket you should be able to:
* Send a script to nicos from the gui
* See that script from nicos
* See which line the script is on
* Do the above for scripts not sent by yourself

**Comment by Tom-Willemsen** [comment]
Wait until #2539 is merged
