### ISSUE TITLE
Investigate updating GALIL driver

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2151]
We are currently using an old version of the galil driver that is tied to Visual Studio 2010. We should look at moving to the new driver that will free us of these issues and it may also give more us more options for scanning.

**Comment by kjwoodsISIS** [comment]
Need to finish merging the new code.
Then need to test thoroughly.

**Comment by John-Holt-Tessella** [comment]
At the moment he Galil drivers must be built under VS2010 if this is no longer an issue can we build then in a VS which runs under Windows 2010. If not create a ticket to allow them to be built under 2010.

**Comment by FreddieAkeroyd** [comment]
Hi John, I'm not sure I understand you comment - do you mean Windows 10 rather than 2010, or are you referring to VS2010?

**Comment by FreddieAkeroyd** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/New-Galil-Driver

**Comment by John-Holt-Tessella** [comment]
Review but don't merge. 
Build, test on office gallil (no homing).

**Comment by AdrianPotter** [comment]
- The driver no longer builds on Windows 7. Is that an issue? Certainly we couldn't merge this in until we updated all our build servers
- When I ran this on my Windows 10 machine,  I got the response below, which suggests that communication with the Galil isn't working as expected. I cannot see any other issues in my configuration that might be causing the issue but suggestions would be appreciated.

```
GalilCreateController("Galil", "130.246.51.169", 20)
Galil2.dll wrapper, gclib 142.167.311
sevr=info Connected to 130.246.51.169, DMC2280 Rev 1.0o-CM, 25873
Stopping running threads and moving axes.
sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

GalilCreateAxis("Galil","A",0,"",1)
sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

GalilCreateAxis("Galil","B",0,"",1)
sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

GalilCreateAxis("Galil","C",0,"",1)
sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

GalilCreateAxis("Galil","D",0,"",1)
sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

GalilCreateAxis("Galil","E",0,"",1)
sevr=major acquireDataRecord:DMC2280 Rev 1.0o-CM:130.246.51.169: 1010 TIMEOUT ERROR.  Galil::command() took longer than timeout to return

sevr=info Disconnected from DMC2280 Rev 1.0o-CM at 130.246.51.169
```

**Comment by AdrianPotter** [comment]
My full Galil logs: [GALIL_01-20180208.log](https://github.com/ISISComputingGroup/IBEX/files/1706874/GALIL_01-20180208.log)

**Comment by AdrianPotter** [comment]
Logs: [GALIL_01-20180208.log](https://github.com/ISISComputingGroup/IBEX/files/1706978/GALIL_01-20180208.log)

**Comment by AdrianPotter** [comment]
Works fine. I fixed the build issue on Windows 7 in conjunction with @FreddieAkeroyd. I tested basic moves and homing. All were as expected and I didn't find any issues in the logs. The GalilStartController argument list has changed so we will need an upgrade script to update existing instruments.
