### ISSUE TITLE
Deployment: Plan how to deploy automatically on 30 instruments

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2152]
We need a plan of how to deploy onto 30 instruments in a minimum amount of time. This needs to install/upgrade:

 - IBEX client
 - IBEX server
 - genie_python
 - mySQL
 - Java (see comment this should be bundled into the instrument)
 - 7-Zip (what is this used for?)
 - git
 - any libraries/dll for the galils etc?
 - ISIS ICP software
 - Labview
 - lab view modules needed by IOCs using lvdcom

It might turn out we do not want these systems under the upgrade of IBEX but we should put a plan in place for updating/keeping up-to-date those things we need; we have a dependency on all these things.

@ChrisM-S, @GDH-ISIS, @FreddieAkeroyd and @KathrynBaker MUST be involved in this conversation.

Things to consider:

- Recovery of an instrument onto new hardware after a crash, i.e. we must know the exact configuration on a machine at all times so it can be reproduced
- Minimal disruption to scientists, e.g. not breaking something that works
- Reduce testing between components. At the moment we consider three items in theory we should test each combination of these items which we allow together. E.g. v3.0.0, v3.1.0, v3.2.0 client with v3.1.0, v3.2.0 of the server and v3.0.0, v3.1.0, v3.2.0 of genie_python
- Selected deployment, of components or on instruments.

**Comment by FreddieAkeroyd** [comment]
Some of this might be helped by bundling Java etc. with ibex rather than it being part of the operating system

**Comment by AdrianPotter** [comment]
Meetings scheduled for 24th and 30th May

**Comment by AdrianPotter** [comment]
Awaiting feedback on :

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Plan-how-to-deploy-automatically-on-30-instruments

Continue within next week

**Comment by AdrianPotter** [comment]
The notes above have been updated and the work has been broken down into tickets: #2425, #2426, #2427, #2428, #2429, #2430, #2431, #2432

**Comment by Tom-Willemsen** [comment]
Tickets seem clear enough to me. Wiki page seems to have documented the contents of the meeting appropriately. Marking this as complete.
