### ISSUE TITLE
IMAT : Dataweb not showing

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#2154]
May I query the state of the IMAT Dataweb please? IMAT Instrument up. IMAT Dataweb down …..

**Comment by DominicOram** [comment]
Fixed by deploying https://github.com/ISISComputingGroup/IBEX/issues/2144

**Comment by Tom-Willemsen** [comment]
IMAT dataweb back online, moving this ticket to completed.

**Comment by GDH-ISIS** [comment]
Thank you!
