### ISSUE TITLE
DAE PVs Disconnected in the Archiver

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2155]
Occasionally, although the DAE is running fine, the archiver believes that some of the PVs are disconnected. This is particularly annoying as it's where the web dashboard gets it's data from.

**Comment by DominicOram** [comment]
![image](https://cloud.githubusercontent.com/assets/10086797/23606392/6ba12620-0258-11e7-950e-fcc48eb6eb6b.png)

This has been seen on IMAT and ZOOM. It was fixed on ZOOM through an instrument reset.

**Comment by kjwoodsISIS** [comment]
Well get NAGIOS to watch it first.  Then, when we can reproduce it, we can tackle this ticket.

**Comment by FreddieAkeroyd** [comment]
The blocks say "reconnecting" in the archiver, some PVs do mention the "60 tries" that Dominic referred to yesterday, but there are also one on pure monitor that are not working (e.g. title). I'm guessing it is a java channel access issue and all we can do is restart the inst archiver. There is a check for missing PVs in nagios called WEB-DASHBOARD-ARCHIVER

To test ticket:
- [ ] Look at current ibex web dashboard http://dataweb.isis.rl.ac.uk/Dashboards/default.htm IMAT should be giving problems with disconnected PVS
- [ ] Log into varanus.nd.rl.ac.uk confirm WEB-DASHBOARD-ARCHIVER is showing error
- [ ] Restart inst archiver on IMAT using URL  http://ndximat.isis.cclrc.ac.uk:4812/restart - should be safe to do this anytime, but wait for instrument in setup if possible
- [ ] Go to http://ndximat.isis.cclrc.ac.uk:4812/main and check archiver says "RUNNING"
- [ ] check nagios again and wait for an email

@GDH-ISIS could you please review this ticket

**Comment by GDH-ISIS** [comment]
Did not need to log onto varanus.nd.rl.ac.uk - not sure how and I do not have any user-name or password. Checked IMAT was in Setup. Clicked on the two links above. Dataweb appears to have come back. Forced Nagios to check. Got the email.

**Comment by John-Holt-Tessella** [comment]
John: This is done merge and set status to done
