### ISSUE TITLE
Device screens: Open screens should close on switching instrument

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2157]
Otherwise, one gets a Console error in the device screens if the screen does not exist on the new instrument

**Comment by AdrianPotter** [comment]
I've not had time to finish this. The fix is on [this branch ](https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket2157_Close_device_screns_on_instrument_switch) but it is missing a system test.

**Comment by AdrianPotter** [comment]
Already done
