### ISSUE TITLE
Wed dashboard: create static html (or xml) page

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2159]
I've added the option to pull a dashboard view from slack - this works fine for seci as it has a mostly static html page that I can easily reformat, the current ibex page uses javascript and is much less easy. Is it possible to provide a pure html (or better xml) view of the information?

**Comment by DominicOram** [comment]
Users also requested that we keep the web dashboard as fast as possible, static html might be better for this case. Note that we have the data served as JSON here: http://dataweb.isis.rl.ac.uk:60000/?callback=jQuery171009443563815145262_1488879740313&Instrument=larmor&_=1488879745318

**Comment by FreddieAkeroyd** [comment]
Thanks - the json may well be fine, I'll take a look

**Comment by FreddieAkeroyd** [comment]
I think phantomjs might do what i need

**Comment by FreddieAkeroyd** [comment]
The “run_information” is missing a <ul>  and </ul> around its <li> elements – blocks are OK. With the <ul> added phantomjs can do a pretty good job :-)

**Comment by FreddieAkeroyd** [comment]
Hi, if you go to https://validator.w3.org/ and upload dashboard.html from \\isis\inst$\Kits$\CompGroup\ICP\scratch you will see all the page markup issues

**Comment by FreddieAkeroyd** [comment]
"h3" etc are not valid inside "p" - maybe you need to look at using an outer "div" tag instead? Or just bold instead of h3 etc.

**Comment by drapj002** [comment]
see https://github.com/ISISComputingGroup/JSON_bourne/pull/17
