### ISSUE TITLE
Configurations memory leak

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2166]
This is the same issue as #2017, please read that ticket for detailed information.

The fix in #2017 was reverted in #2165 because it caused some subtle bugs elsewhere. This ticket should fix the issues highlighted in both of the above tickets.

This is likely to be achieved by keeping track of (and closing) observables at their point of use, rather than trying to do it via some central mechanism (which was already attempted in the original fix of 2017).

This ticket should also update/create relevant documentation to ensure that any patterns that we set are adhered to in future.

**Comment by John-Holt-Tessella** [comment]
Just found `Closer.java` which might be useful

**Comment by kjwoodsISIS** [comment]
Confine the scope to Configurations.

**Comment by Tom-Willemsen** [comment]
This looks like it's a no-op change. It appears that the `finalize()` method which was added in #2017 and removed in #2165 was not actually necessary to fix the memory leak, and that the leak has been fixed just by changing `Observable`s to `ClosableObservable`s (which was not reverted).

For the reviewer, this ticket can be marked complete if the acceptance criteria of #2017 are still met despite the partial reversion in #2165
