### ISSUE TITLE
GUI: Validate non-numeric DAE data

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2167]
In the DAE perspective -> Experiment setup -> Data Acquisition, you can enter non-numeric data in various boxes. Can we verify this is handled sensibly?

- What values are set when non-numeric data is sent
- How are comma-separated numbers interpreted. For example, is the default value in the timing box "5,000" interpreted correctly?

**Comment by KathrynBaker** [comment]
Duplicate of #1616
