### ISSUE TITLE
Testing framework for IOCs (slight return)

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2168]
We have looked at this before, but now we have Lewis it should be possible to do a better job.

We can use python to fire up Lewis and the IOC and then run a series of unit tests against the IOC.

This will allow us to check that the IOC runs (paths correct etc.) and that the PVs behave how we and Lewis think they should.

This can be then done as a Jenkins Job. Probably nightly on a separate machine to the other builds. How about the machine we inherited from Mantid?

Initially though let's start with one of the IOCs that has an emulator like the Julabo

**Comment by John-Holt-Tessella** [comment]
We need #1529 to do this.

**Comment by kjwoodsISIS** [comment]
We don't actually need to do #1529 first.

**Comment by kjwoodsISIS** [comment]
Run both RECSIM and DEVSIM

**Comment by mattclarke** [comment]
The framework is here https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework
As it was a new repo I forgot to work on a branch, so I have had to fake a PR.
