### ISSUE TITLE
Dataweb: Add to NAGIOS

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2169]
We had a couple of issues this sprint where the web dashboard died and we had to rely on someone noticing it. We should put this in NAGIOS.

**Comment by FreddieAkeroyd** [comment]
This is now in nagios called WEB-DASHBOARD on any ibex instrument, log into varanus.nd.rla.c.uk to take a look. It only currently checks if the server returns a page, not the content on the page.  In ticket #2155 a check will be done for DAE pv's in disconnected state, hopefully the two cover everything, unless there is something more i can look for on the web pages that would help?

**Comment by FreddieAkeroyd** [comment]
@DominicOram if you let me know the "cannot connect" text that will be displayed I will update the test

**Comment by DominicOram** [comment]
The cannot connect text is the same as if you tried to point to an instrument that does not exist. E.g. http://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=bad

**Comment by DominicOram** [comment]
If you let me know which specific part of the text you are looking for I can put a comment in the code/on the dev wiki. Otherwise I could put in a hidden html tag so that we don't couple the displayed text with NAGIOS?

**Comment by DominicOram** [comment]
@GDH-ISIS If you are going to review 2155 it makes sense to do this one at the same time

**Comment by John-Holt-Tessella** [comment]
Anyone can review this.

**Comment by Tom-Willemsen** [comment]
- [ ] Missing nagios entries for the newly migrated instruments (Polaris, HRPD)
- [ ] Please add instructions to [the developer's manual](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC) to add this nagios check to future instruments we migrate. Include instructions on how exactly to set this up within nagios. If it's something that should only be done by certain people, that's fine, but still add a note to the wiki to ensure this doesn't get forgotten.
- [ ] Have you implemented a search for a string? I'm not 100% certain but it appears as though it's currently just checking for a `HTTP 200 OK` response? If so, the checks will always pass as the dataweb does always return something even if it can't connect (e.g. http://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=bad as Dom pointed out above)

**Comment by FreddieAkeroyd** [comment]
A search string is implemented, but if you do a "view source" the html source is the same whether there is an error or not as everything is done via javascript in the client. So it would need a javascript interpreter such as phantomjs to be used in the nagios check, or an alternative  static version of the web page that could be checked instead

**Comment by FreddieAkeroyd** [comment]
Everything else done

**Comment by Tom-Willemsen** [comment]
#2512 added to check individual instruments, this ticket can now be considered complete.
