### ISSUE TITLE
Create & Test New IBEX Release ahead of Cycle 2017/01

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2170]
As a developer I want to create a new release of IBEX, so that I am ready to deploy new features and bug fixes to instruments prior to the 2017/01 cycle. 

#### Acceptance Criteria
1. Create new release of IBEX
1. Test new release of IBEX

#### Notes
1. Cycle 2016/05 is the current active cycle.  It finishes on 31st March 2017.
1. Cycle 2017/01 starts on 2nd May 2017.  It finishes on 2nd June 2017.
1. Deployment of IBEX to individual machines will be the subject of a separate ticket.

**Comment by AdrianPotter** [comment]
So far I've done up to step 11:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release

Notably I haven't created tags yet. I think that's best done when testing has finished. The release builds are currently queued.

**Comment by AdrianPotter** [comment]
Test report:

[Ibex RC2 manual system testing.xlsx](https://github.com/ISISComputingGroup/IBEX/files/954350/Ibex.RC2.manual.system.testing.xlsx)

**Comment by AdrianPotter** [comment]
All issues detected by testing are ticketed as necessary.  Release has been tagged
