### ISSUE TITLE
GUI: Update macros in the IOC dialog as they are written

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2172]
Currently the dialog has a text box and a set macro button to update the table. Can we not just properly databind it and update the table whenever anything is entered into the text box?

**Comment by Tom-Willemsen** [comment]
Please fix automated system test `CanEditIOCMacros.test`as this relies on the "set macro" button.

Other than that looks fine

**Comment by ThomasLohnert** [comment]
Looks good, could you please just do something about the checkstyle warnings in `MacroValueValidator`?
