### ISSUE TITLE
POLARIS/HRPD/GEM Sample Changer

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2173]
As a scientist I want to use the sample stack on polaris and HRPD which are similar.

Create an emulator, ioc and OPI, see the VI for info; We believe it is a stream device.

**Comment by davidkeymer** [comment]
[HRPD-Sample_Changer-Serial-Protocol.pdf](https://github.com/ISISComputingGroup/IBEX/files/841945/HRPD-Sample_Changer-Serial-Protocol.pdf)
