### ISSUE TITLE
ZOOM: Limit switches not propogating

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2174]
Currently on ZOOM MTR0201 should be at it's lower limit (it is on the VI) however the LLS PV is not set. Note that the icons in the ToM are also broken on the client on NDXZOOM but this has been fixed in https://github.com/ISISComputingGroup/IBEX/issues/1814

**Comment by KathrynBaker** [comment]
Unless someone has been moving them, all the ZOOM axes should be on their forward limits, or that is where we should be leaving them at least, with the exception of the PGC on MTR0101, which should be at 0.

**Comment by DominicOram** [comment]
Should be able to work on NDXZOOM to test this. However, they may be doing DAE3 testing. Contact Simon Moorby to see what their testing schedule is.

**Comment by AdrianPotter** [comment]
The motor record is set up such that the limit switch will only be triggered if the limit switch is hit in the expected direction. That is, the upper limit switch will only become active if the motor reports hitting the upper limit switch and the motor is moving in the positive direction. Vice-versa for the lower limit switch.

If the motor IOC is restarted, CDIR isn't autosaved so the previous status isn't restored. @FreddieAkeroyd: Should we autosave CDIR? Will this have unintended consequences?

**Comment by FreddieAkeroyd** [comment]
@AdrianPotter  CDIR is a private motor record field, TDIR isn't private but both TDIR and CDIR are marked read-only so may not be autosavable. On restart does it get the limit status from MSTA but then decide to ignore it based on CDIR?

**Comment by AdrianPotter** [comment]
That's correct. CDIR only gets processed on executing a command (e.g. home, move). When the IOC is restarted, it always comes back as 0 as far as I can see. The MSTA is read but the limit flag is only set if CDIR is in the correct direction (1 for upper limit).

**Comment by AdrianPotter** [comment]
I just tried adding CDIR to the autosave for a simulated Galil. The value was saved correctly but on restart the value was reset to the initial value (which is 1 for a simulated motor rather than 0)

**Comment by AdrianPotter** [comment]
I've added some advice on the problem here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-And-Device-Trouble-Shooting

I've also sent an email to TechTalk. I think we've sufficiently diagnosed the issue and no sensible fix exists so I'm moving to review. If something comes in via TechTalk, I'll raise a new ticket.

**Comment by Tom-Willemsen** [comment]
Tech talk question at http://www.aps.anl.gov/epics/tech-talk/2017/msg00599.php seems clear enough to me - hopefully it will generate some useful responses.

Developer's manual diagnostic information also seems ok. Remember to update the developer's manual if new information does come to light from tech talk.
