### ISSUE TITLE
The add_sim_records script removes braces

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2179]
When the add_sim_records.py script is run on a db file that contains records not in the 'allowed_sim_type' list it removes braces from them. It should leave them untouched.

**Comment by John-Holt-Tessella** [comment]
Does this fix it? https://github.com/ISISComputingGroup/EPICS-DbChecker/pull/2 it is an old pull request which has not been merged

**Comment by DominicOram** [comment]
Yes, I've merged that ticket, closing this as duplicate.
