### ISSUE TITLE
Release: Create a script to determine which tickets are in the current release

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2185]
As a developer, I would like to streamline the release process. As described in ticket #1874, we are proposing to get a list of tickets in the current release by analysing merged pull requests in the ISIS_Computing_Group repositories. 

### Acceptance Criteria

The script should:

- [ ] Provide a list of tickets not on release notes dev which are in review or rework
- [ ] Provide a list of tickets not on release notes master which are in review complete
- [ ] All tickets from the current release should be included

### Notes

I started this at home:

https://github.com/ISISComputingGroup/ibex_utils/tree/Ticket2185__tickets_not_in_rel_notes

See if this is any good. If not trash the branch and start again

**Comment by DominicOram** [comment]
We currently do this manually in the release notes page but we occasionally miss tickets. We should automate this so that when a ticket is moved into review an entry is created in the table on the release notes. It should not populate the description automatically to encourage developers to write good descriptions. An extension to this would be to not allow merges until the description has been completed.

**Comment by Alistair-McGann-Tessella** [comment]
Proposed because this issue was brought up in the retrospective:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Retrospective-notes-2020.01.08#dev-release-notes

**Comment by DominicOram** [comment]
Merge with the project board checker. @FreddieAkeroyd will put this somewhere we can edit

**Comment by KathrynBaker** [comment]
Discuss this before starting, during conversation in retrospective it had been suggested that empty lines get created on move to review/review complete as appropriate and the project board checker could highlight empty lines

**Comment by DominicOram** [comment]
Meeting between @KathrynBaker, @FreddieAkeroyd, @John-Holt-Tessella, @Tom-Willemsen:
* Move release notes to be a MD file in IBEX repo
* Workflow becomes:
  * There is a "pre release" release notes file (e.g. replacing master one)
  * New tickets should have a PR on the IBEX repo that changes this file
  * On release copy this file over to a new file named after the release
* Make a service that is part of the project board checks that errors if there are tickets in the review column that do not have PRs in this repo and if there are tickets in complete that aren't present in any files in the repo
* Convert the old MD files and put them in this repo
* Delete old page and update links anywhere we can think of
* Update documentation accordingly

**Comment by DominicOram** [comment]
- [ ] All release notes have been moved to https://github.com/ISISComputingGroup/IBEX
- [ ] Updated links in https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information--hotfixes and https://github.com/ISISComputingGroup/IBEX/wiki#releases
- [ ] New workflow documented in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Tickets-and-their-Workflow#movement-of-tickets and in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#standard-release
- [ ] Updated PR templates; https://github.com/ISISComputingGroup/ibex_gui/pull/1231, https://github.com/ISISComputingGroup/EPICS-ioc/pull/571 and https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/336
- [ ] Went through the [Dev notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) and added to [Upcoming Notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md) or made PRs at https://github.com/ISISComputingGroup/IBEX/pulls as appropriate. Delete the ReleaseNotes_Dev page once this is confirmed.
- [ ] Code for checking is at https://github.com/ISISComputingGroup/ProjectBoardUtils/pull/1, can be reviewed locally
- [ ] Will need to talk to @FreddieAkeroyd to get it deployed

**Comment by DominicOram** [comment]
Proposing because I have done the rework, review should take ~10/15 minutes
