### ISSUE TITLE
Release: Update release notes process

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2187]
A new release process is documented in ticket #1874. Once Tickets #2185 and #2186 are complete, migrate to the new release process.

- [ ] Update the developer manual with the new release process
- [ ] Make sure any existing information on the release_notes_dev page is migrated to the appropriate new location
- [ ] Update the pull request templates to reflect the new process
- [ ] Test that the process works in full for the current release

**Comment by GRyall** [comment]
7 years have passed. The [release documentation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release) has been updated repeatedly. In the event we do complete #2186 then updating documentation is part of our workflow anyway and implied by the ticket.
