### ISSUE TITLE
Best way to handle galil failure to send data record

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2191]
Occasionally the galil (as in on IMAT just now) stops sending the UDP data record in DR mode, you get a stream of DR timeout messages. Restarting IOC does not help - a power cycle of galil is required. Swapping to synchronous polling (QR) works fine, which you do by changing the poll frequency to a negative number. Need to work out best way to handle this, automatically if possible but may need adding this option via IOC macros that the user can use.

**Comment by kjwoodsISIS** [comment]
Need to fix this - it's important.

**Comment by AdrianPotter** [comment]
I've created a PR that would switch from async to sync in the case of repeated timeouts:

https://github.com/ISISComputingGroup/EPICS-galil/pull/9

I've asked Rob and Russell whether I can test it on their instruments during shutdown since we can't test this easily locally (even on an instrument it's hard). Setting to impeded while I await replies.

**Comment by AdrianPotter** [comment]
Russell's given me the thumbs up so I'll put the fix on Alf and then analyse the behaviour in a few weeks once it's been running for a while

**Comment by FreddieAkeroyd** [comment]
The update period may need adjusting on switching from DR to QR, udp DR can probably run quicker that polling QR, I've usually dropped it a little when I've swapped manually

**Comment by AdrianPotter** [comment]
Ok, I'll keep that in mind. It's currently running on Alf. I'll check back in a little while to see if there's anything interesting in the logs

**Comment by AdrianPotter** [comment]
It's been running for a month now, and the timeout has not been triggered. I think we should deploy it regardless. At the moment, if the issue occurs then we have to switch the Galil settings and restart them anyway. If the fix doesn't work, we'll have to do the same thing so we won't lose anything. I don't see a better way to test it.

**Comment by FreddieAkeroyd** [comment]
Have you tested it by breaking the galil e.g. sending DR0 by another route to turn off the data record

**Comment by AdrianPotter** [comment]
I've just done a bit of rework based on the above suggestion. Tested by doing the following:

1. Replace the `galil` support module on ALF using this one
1. Restart GALIL_01
1. Launch Putty
1. Connect to Galil using saved connection settings
1. Send command DR0
1. Timeout messages appear 10 times
1. The Galil disconnects and reconnects in sync mode. No further timeout messages are received and the Galil continues to function as before

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd  to review

**Comment by FreddieAkeroyd** [comment]
Additional test step:
8. connect again with putty and type DR0, you should see no timeouts, if you do this means the reconnection was again with DR (async) and not QR (sync)

**Comment by FreddieAkeroyd** [comment]
Above issue fixed, code merged and release notes updated
