### ISSUE TITLE
MySQL: Install/bundle with instrument

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2192]
Look at bundling and installing mysql with the instrument. Options:

1. Run it as a bundle like we do java with the gui (this may not be possible; does mysql need to be running when the instrument is not)
1. Create an install/upgrade script as part of instrument install which will upgrade/install the correct version of mysql.

**Comment by kjwoodsISIS** [comment]
See also #2152
