### ISSUE TITLE
Training: Arrange training for HRPD and POLARIS scientists

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2203]
Scientists using IBEX on HRPD and POLARIS will need to be trained to use IBEX. Organise the standard training session with them.

**Comment by John-Holt-Tessella** [comment]
Fulfill #2009 and #2036 at the same time.

**Comment by DominicOram** [comment]
Following a meeting I had with the motion control group on Monday it may be worth extending an invite to them. Do we have enough space for another 3/4 people?

**Comment by John-Holt-Tessella** [comment]
Maybe I haven't set a date yet. Let me do that tomorrow and then get replies and then if there is room add some people.

**Comment by John-Holt-Tessella** [comment]
Done #2036

**Comment by John-Holt-Tessella** [comment]
Organised for 26/2/2017 in CR21

**Comment by John-Holt-Tessella** [comment]
Laptop request email sent.
