### ISSUE TITLE
GALIL: handling autosave corruption if startup error [TIMEBOX: 1 day]

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2207]
If the galil fails to connect it has been reported #2180 that this leads to corruption of the autosave file. This needs to be investigated, also consider whether we actually need to have a monitor on the autosave files - it may be better to not have a monitor and require use of a "manual save" if changes are made, this would then stop any strange IOC startup from corrupting autosave settings

**Comment by ChrisM-S** [comment]
Would a manual save necessarily be safer?  I'm just wondering whether the frequency of watched auto-saves might be showing up a contention issue which is underlying.

**Comment by FreddieAkeroyd** [comment]
It would stop it autosaving blank/default values, so it should be safer - you would only manual save if you knowingly changed something and it was working OK. What I don't know is where the autosave file got blanked before it was loaded, I'm guessing load was done correctly, values reset, blank values written, but that may be wrong - we'll need to check

**Comment by KathrynBaker** [comment]
There was also an odd hiccough on NDEMUONFE over the year change, where it lost the autosaves and blanked itself, or something else odd happened, that was detailed in ticket #1986, I would assume a manual save would help limit that kind of error as well.

**Comment by FreddieAkeroyd** [comment]
This is probably a general discussion item - are we aware of any cases when we actually want the IOC to be automatically saving settings as opposed to us manually making the decision?

**Comment by ChrisM-S** [comment]
Apart from the slightly curious idea of an auto-save that isn't?,  recovery of an unsaved configuration (or changes to values on an OPI), one off settings etc. to the last working state of the system after a crash/reboot would normally be very desirable.  This is clearly possible, but I'm not sure how much of this down to autosave?

**Comment by KathrynBaker** [comment]
Please refer to some of the muon front end work which deals with exactly that. #1449 is a ticket that would be liked, but has not made it high enough up my priority list to propose – which is to take a snapshot of values for reapplying at a later date. #1209 was done and covers what to do when the IOC is in control of values on startup (not typically the case – usually the device is taken as the required value to allow for people to change them directly and that take precedence). This all does tie in to how we deal with autosaves and similar, at least as far as detailing some requirements go.

**Comment by kjwoodsISIS** [comment]
Note from Pre-Planning Meeting: we need to sit down and work out the various different cases.

**Comment by John-Holt-Tessella** [comment]
Look at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Auto-Save-Ideas to give some more possible ideas

**Comment by kjwoodsISIS** [comment]
Timebox: to investigate the issue and discuss our general approach to autosave.

**Comment by Tom-Willemsen** [comment]
Meeting scheduled on 14/12/2017

**Comment by Tom-Willemsen** [comment]
I have created tickets as a result of today's meeting:
- https://github.com/ISISComputingGroup/IBEX/issues/2831 to address the immediate issue with GALILs only.
- https://github.com/ISISComputingGroup/IBEX/issues/2832 as a more general solution for all IOCs
- https://github.com/ISISComputingGroup/IBEX/issues/2833 as further work which could be done to improve our autosave mechanisms but is not critical

**Comment by AdrianPotter** [comment]
I added a few comments which I thought added a bit more context to the motivations behind the tickets. Otherwise good. Thanks for coordinating the meeting. Nice to see some progress.
