### ISSUE TITLE
ZOOM: Stubs for PLC interactions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2210]
In order to simplify the deployment process for ZOOM should the vacuum PLC be available (must assume it will be), there needs to be at least a blank OPI, and appropriate directories as per the Larmor PLC in place. It is possible once the system is deployed to then update the OPI XML on the fly as well as add dbs to the system, which can then be applied to the repos ready for building next time around.

This is to enable #1232 to be undertaken after the release is built, but in time for cycle start on the 2nd of May.

**Comment by Tom-Willemsen** [comment]
What do you mean by "appropriate directories as per the Larmor PLC in place"? 

Do you just mean the `fins` directory in the configuration?

**Comment by KathrynBaker** [comment]
Quite probably, but there are also db files that get built for the PLCs, and we could do with empty db files in those locations at least. It makes it easier to update when we have the real values. Files should have been included in the requirement as well as directories.
