### ISSUE TITLE
Polaris: install Ibex

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2212]
See also #2084 for links to more details.

This ticket should install IBEX on Polaris.

**Comment by DominicOram** [comment]
IBEX has been installed. We have yet to go down to the instrument and ensure that everything is connected as expected.

**Comment by Tom-Willemsen** [comment]
We went down to Polaris yesterday as part of #2215 and IBEX has been installed successfully (and was able to connect to e.g. eurotherms).
