### ISSUE TITLE
Polaris: configurations

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2213]
See also #2084 for links to more details.

This ticket should migrate the configurations and configuration files used by polaris from seci to ibex.

**Comment by Tom-Willemsen** [comment]
TODO:

- [ ] Set up sample changer (waiting on #2173)
- [ ] ...
- [ ] ...

**Comment by AdrianPotter** [comment]
For the Polaris scripting, the configuration needs blocks associated with P, I, D, auto_tune and max_power for the three Eurotherms. In the scripts I've called these Pn, In, Dn, AUTO_TUNEn and MAX_POWERn. I've left n generic but the original scripts call for n in (1,2,3). Please could the associated blocks be added, or the script updated to reflect the names of existing blocks.

The script also needs blocks for the PEARL pressure cell controller but I'm not sure yet whether we're even supporting that.

**Comment by kjwoodsISIS** [comment]
Hi Adrian,

Do all the POLARIS scripts & configs refer to the PEARL pressure cell controller?

Kevin


----

Kevin Woods, Project Manager
Tessella
T: +44 (0)1235 446986

M: +44 (0)7734 059715
E: kevin.woods@stfc.ac.uk<mailto:kevin.woods@stfc.ac.uk>

________________________________

**Comment by Tom-Willemsen** [comment]
Blocks were called `Autotune_n`, `MaxPower_n`, `Deriv_n`, `Int_n`, `Prop_n` and `Temp_n`. I've updated the script to reflect this.

**Comment by Tom-Willemsen** [comment]
Doesn't need pressure cell controller. Remove this from any configs

**Comment by AdrianPotter** [comment]
Assume this can be completed now the sample changer is available

**Comment by Tom-Willemsen** [comment]
Have just been finalising Polaris' configurations; none of the configurations which I've migrated appear to have any run control under SECI.

![image](https://cloud.githubusercontent.com/assets/24375813/25445588/b0b6ab24-2aa6-11e7-8221-2f8415e26962.png)

**Comment by Tom-Willemsen** [comment]
Ron/Helen have confirmed that they don't expect any run-control by default in any of their configurations.

>Tom,

>Helen and I both believe this behaviour is what we would expect and that nothing's been "lost" along the way.

>Temperature run control would always be done on an experiment-by-experiment (and sample-by sample) basis.

>Occasionally we have run control on sample changer "move finished" - but again this would be on an individual experiment/sample basis, and was never a default SECI start-up option.  Likewise with sample tank vacuum and furnace vacuum values - never normally SECI start-up options either.


>Ron.
