### ISSUE TITLE
Polaris: test IBEX

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2215]
See also #2084 for links to more details.

This ticket should test Ibex on polaris.

Requires #2212 #2213 #2216

**Comment by Tom-Willemsen** [comment]
When setting up the jaws, need to run the VI in `\\Ndxpolaris\c$\LABVIEW MODULES\Drivers\Galil DMC2280\Galil - EPICS.llb` which will generate a batch file to set up the motors properly.

**Comment by Tom-Willemsen** [comment]
Jaw set now done. Just need to ask Ron/Helen if they want to test *actually* moving it next week.

**Comment by Tom-Willemsen** [comment]
I've sent an email to Ron/Helen asking if they want to test physically moving motors next week.

I've also written up as much as I can about migrating motors from SECI to IBEX. Reviewer, please make sure the following instructions make sense. https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX

**Comment by Tom-Willemsen** [comment]
Testing done. Jaws moved successfully.

A couple of minor feedback points; I will create separate tickets to address those.

**Comment by AdrianPotter** [comment]
Please make sure to add any non-standard device behaviour to the instrument's page so we know what's happened in the past and any quirks of the current setup:

https://github.com/ISISComputingGroup/IBEX/wiki/POLARIS-Instrument-Details

**Comment by Tom-Willemsen** [comment]
Added a note about galil_02 to the polaris wiki page.
