### ISSUE TITLE
Polaris: convert scripts to genie python

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2216]
See also #2084 for links to more details.

This ticket should convert Polaris scripts from open genie to genie_python

**Comment by Tom-Willemsen** [comment]
Kevin to email instrument scientists to find out which scripts need to be migrated.

**Comment by kjwoodsISIS** [comment]
> 
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 03 April 2017 15:55
> To: Smith, Ron (STFC,RAL,ISIS); Playford, Helen (STFC,RAL,ISIS)
> Cc: Willemsen, Thomas (Tessella,RAL,ISIS)
> Subject: Migrating POLARIS Scripts to IBEX
> 
> Hi Ron, Hi Helen,
> 
> We’ve been making good progress in creating IOCs & device drivers for the equipment on POLARIS.
> We are now at the point where we can start to convert configs (including sub-configs) and scripts for use on IBEX.
> 
> We have a list of your current configs, but we don’t have a list of your currently active scripts.  Can you please tell us which of your scripts are in active use (many instruments have scripts dating back several years; there is no point in migrating old scripts which are no longer used – we’ll migrate only active/recent scripts).
> 
> Thanks,
> 
> Kevin
>

**Comment by AdrianPotter** [comment]
There's nothing in `C:\scripts` to convert. The directory contains 2 gcl files:

- `myscript.gcl`: This is a test script with a single print statement.
- `sumall.gcl`: This is a numerical analysis script, not an instrument control script.

Similarly the scripts on the U drive are variants of `sumall.gcl`

We will await the reply from Ron and Helen to see if there's a secret stash of scripts somewhere else

**Comment by AdrianPotter** [comment]
Note that there are some routines to migrate in:

\\NDXPOLARIS\c$\Users\spudulike\Documents\Configurations\COMMON\gcl\polaris_routines.gcl

**Comment by AdrianPotter** [comment]
I've migrated the script above. It references the PEARL pressure cell controller which we haven't implemented in IBEX. I've written the routines that will replicate the functionality based on imaginary blocks but I'm waiting to hear how and when we'd support the controller.

**Comment by AdrianPotter** [comment]
I've added some example scripts based on common user functions to the wiki:

https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Scripting

and we've offered to create some template scripts with the Polaris scientists as part of their initial training.
