### ISSUE TITLE
HRPD: Commission the Jaws in IBEX

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2219]
The code to allow this was merged as part of #2098, however the jaws still need to be set up on HRPD and checked as this was tested with a test system not the actual jaws. This could not be done prior to the other ticket being completed.

There are two jaw sets with the following information to consider when adding the commissioning on HRPD:

**Set 1**

Calibration: 0.01925 steps/mm

Offsets:

Jaw | Offset (steps)
---- | -------
North | 470
South | 470 
East  | 460 
West  | 500

**Set 2**

Calibration: 0.01953125 steps/mm

Offsets:

Jaw | Offset (steps)
---- | -------
North | 471
South | 471 
East  | 471
West  | 571

**Comment by AdrianPotter** [comment]
Acceptance criteria:

- [ ] This ticket details a plan of action for ensuring the jaws on HRPD work with IBEX with minimal risk of damaging the hardware.
- [ ] The instrument scientists are aware of the plan and happy to go ahead with deployment.

**Comment by AdrianPotter** [comment]
Once the PRs have been reviewed, please put back in ready. The PRs fix a couple of issues with the LinMot needed for deployment to HRPD. Whilst that's happening, I'll create a test plan and communicate it with the HRPD instrument scientists.

**Comment by AdrianPotter** [comment]
HRPD test plan

1. Install IBEX on HRPD
1. Migrate the configurations from HRPDTEST to HRPD. DO NOT SWITCH CONFIGURATIONS
1. Check that the resting positions match between LabView and EPICS
	1. Making sure the LinMot IOCs are inactive, get the current motor positions from the VI
		1. Open the VI "HRPD Jaws Driver.vi" at C:\LabVIEW Modules\Instruments\HRPD\HRPD Jaws\Screens
		1. Before running the VI, press CTRL+E and check that the User Configurable Values match with those specified for LinMot_01
			1. MRES1-4 should all match the LinMot Calibration value
			1. The offsets OFST1-4 should match the offset values, multiplied by the calibration value, multiplied by -1. The negative value is because LabView has offsets going in the opposite direction from EPICS.
			1. The COM port may be offset by 1. This is a factor of the old VI and will need checking when we get onto the hardware
		1. Run the VI
		1. Note down the current individual Jaws setpoint values
		1. Close the VI
	1. Switch to the main HRPD configurations. The LinMot IOCs should start automatically
	1. Open the Jaws OPI from the synoptic view
	1. Check that the positions of the motors match that of the VI. Any discrepencies should be explained before continuing
1. Check velocities match
    1. The VI uses hard-coded, velocity 50 in motor units
	1. Open a console to the LINMOT_01 IOC
	1. Do a small tweak to the motor position (~0.1)
	1. Verify that the motor sends the "!SV50" command to the motor that has moved
1. Check new positions match
    1. With the IOCs running, perform a small move on the motors (~0.1)
	1. Record the current motor positions
	1. Stop the IOCs
	1. Open the jaws VI again
	1. Verify that the positions on the VI match the values from the OPI
	
Assuming these tests match then we are sufficiently confident that the motor is behaving as expected.

Please ensure to explain the major differences between the old and new setups to the instrument scientists:

1. Offsets are in physical units, not motor steps
2. Offsets work in opposite directions in EPICS vs LabView
3. To reinitialise the controller, go to any of the motors and use the home button (either direction)
4. Many of the controls in the motor OPI do not function as the operations are unsupported by the LinMot (notably STOP and JOG)

**Comment by AdrianPotter** [comment]
For review:

- [ ] Test plan is approved by Kevin/John
- [ ] Changes to the LinMot are approved and merged

Once reviewed, please move back to ready and I'll do the following:

- [ ] Forward the test plan to the instrument scientists for review and approval
- [ ] Set up HRPDTEST with the jaws configuration

**Comment by FreddieAkeroyd** [comment]
Is it worth getting Gareth or David to review the test plan too? Looks good to me though.

**Comment by AdrianPotter** [comment]
Sent to Gareth and David. David has given it the thumbs up. No reply from Gareth yet.

**Comment by AdrianPotter** [comment]
Awaiting
- [ ] New build of IBEX containing LinMot that can be deployed to HRPDTEST
- [ ] Thumbs up on test plan for jaws.

**Comment by AdrianPotter** [comment]
I've deployed the new build version to HRPDTEST. The motors are set up correctly in simulate mode*. Dominic has approved the test plan.

*For simulated motors, using multiple axes operates as one motor. All 4 axes share the same values. This is a new issue and I've noted the same things happen with the McLennan in devsim mode. I'll create a separate issue to look at it.

**Comment by John-Holt-Tessella** [comment]
Test plan enacted as specified (although we switched to configuration slightly early).
Numbers all match between VI and EPICS within rounding and tolerance:
Velocities all checked.

Initial position

dir | IBEX  | VI
--- | --- | ---
N | 9.991 | 9.99
S | 9.991 | 9.99
E | 7.508 | 7.51
W | 7.508 | 7.51

Moved in VI

dir | IBEX  | VI
--- | --- | ---
N | 7.893 | 7.90
S | 8.008 | 8.00
E | 5.005 | 5.00
W | 5.101 | 5.1

Velocities checked all 52<Channel>

Move in IBEX

dir | IBEX  | VI
--- | --- | ---
N | 8.1 | 8.10
S | 7.7 | 7.70
E | 4.79 | 4.79
W | 5.20 | 5.2

Got upper and lower limit violations when set.
