### ISSUE TITLE
System tests: bug in selecting latest EPICS build

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2220]
The script in [https://github.com/ISISComputingGroup/ibex_system_tests/blob/master/get_latest_builds.py](https://github.com/ISISComputingGroup/ibex_system_tests/blob/master/get_latest_builds.py) claims to select the latest EPICS build, but doesn't work.

Fix this

(It's due to the new directory structure now that we have an installer)

**Comment by FreddieAkeroyd** [comment]
Ah, mea culpa

**Comment by FreddieAkeroyd** [comment]
Genie_python also needed its path changing, I've pushed an update for that
