### ISSUE TITLE
GUI: IOC settings persist after cancelling

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2222]
When changing settings on a newly added IOC and confirming the Add/Edit IOC dialog, but then cancelling the Edit Config dialog below it, the GUI remembers the changed settings and fills them in next time you want to add that IOC to any config.

Steps to reproduce:
* Edit a configuration
* Add a new IOC
* Change some of its settings and confirm the Add/Edit IOC dialog
* Cancel the edit config dialog
* Edit (any) configuration again
* Add the same IOC again 
* The settings should be blank but they are not

**Comment by Tom-Willemsen** [comment]
Had a quick look at this is part of the bugs standdown - this is not a completely trivial ticket (but I only got half an hour or so into it and not as far as writing any code)

**Comment by Tom-Willemsen** [comment]
Also happens with the new configuration. To reproduce this case:
- Go to configurations -> new
- Add an ioc with some macros
- Press ok
- Save the configuration as something (doesn't matter what)
- Go to configurations -> new
- Add the same IOC as before
- Bug: macros are populated with the values set in step 2

PR is https://github.com/ISISComputingGroup/ibex_gui/pull/656
