### ISSUE TITLE
Configurations: deleting IOCs

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2226]
When I delete an IOC from a configuration or component, it gets deleted from the table but the "selected:" box at the bottom of the screen doesn't get cleared. It also looks like I can still press the edit/delete buttons, but they don't do anything (beyond throwing a `NullPointerException`).

When an IOC is deleted we should clear the "selected" box and make sure that the "delete IOC" and "Edit IOC" controls get greyed out.

To reproduce:
- Start with a blank config.
- Add an IOC
- Delete the newly added IOC
- Notice that the "Selected: " box at the bottom is still populated
- Press the delete and/or edit IOC buttons - these throw `NullPointerException`s in the eclipse console.

**Comment by DominicOram** [comment]
Started some work on this. waiting for #1355 to be merged as I anticipate conflicts
