### ISSUE TITLE
Emulators: Make repo public

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2228]
It seems that emulators are an obvious thing we can collaborate with others on. Therefore it seems a shame that our repo for them is private, we should make this public.

**Comment by DominicOram** [comment]
To do this we will need to remove the CLF emulator (including from the history)

**Comment by DominicOram** [comment]
The linkam and lakeshore are the only emulators that are in CLF but not lewis. Keep these if they have not been converted. Also, remember that it will be tricky to re-write the history when people have active emulator branches.

**Comment by DominicOram** [comment]
To test search through the history of the repo and confirm there is no reference to the clf framework (individual emulators are fine as we wrote those)

**Comment by DominicOram** [comment]
Also do the following and confirm there are no CLF things in your local repo:
* git pull EPICS top
* cd EPICS/support/DeviceEmulator
* rm -r master
* git submodule update --init .

**Comment by John-Holt-Tessella** [comment]
I also updated the licence to BSD3
