### ISSUE TITLE
E4: Add view to client for EPICS area detector

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2230]
EPICS areaDetector includes an imageJ plugin for displaying and manipulating images, which includes ones served by the ISIS DAE live view.  ImageJ can be added as an eclipse view https://marketplace.eclipse.org/content/imagej-plugin

**Comment by Tom-Willemsen** [comment]
On that site that you linked it suggests we need eclipse 4. I was curious so briefly snooped around in the source code and in [one of the manifests](https://github.com/Bio7/EclipseImageJ1Plugin/blob/master/com.eco.bio7.image/META-INF/MANIFEST.MF) I found that this requires Java 1.8 `Bundle-RequiredExecutionEnvironment: JavaSE-1.8`

It might still be possible to force it to work under eclipse 3 / java 1.7, but that doesn't look like what it was originally written for.

**Comment by DominicOram** [comment]
There may be solutions for this in CSS. We should evaluate all of these options (probably in this order of preference):
* Any pre-existing BOY widgets
* Any display builder widgets
* The aforementioned ImageJ plugin

**Comment by DominicOram** [comment]
Main PR at https://github.com/ISISComputingGroup/ibex_gui/pull/751
