### ISSUE TITLE
GUI: Handle duplicate IOCs

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2234]
With https://github.com/ISISComputingGroup/IBEX/issues/1355, it is possible to introduce duplicate IOCs to a configuration, meaning the user can't be sure which set of IOC settings will be used when you run the IOC.
Possible solutions:
* Prevent duplicate IOCs to be added to a configuration (same as with blocks)
* Let the user choose which set of settings they want to use when running an IOC (don't know if there's a use case for this?)
* ... (other?)

Requires https://github.com/ISISComputingGroup/IBEX/issues/1355

**Comment by DominicOram** [comment]
Fixed by https://github.com/ISISComputingGroup/IBEX/issues/4202
