### ISSUE TITLE
IMAT: Commision Stress Rig (LvDCOM)

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2235]
As a developer I would like the stress rig IOC to be tested using the actual stress rig before start of cycle.

**Comment by kjwoodsISIS** [comment]
The stress rig normally lives on ENGIN-X.  Can you check when it will be moved to IMAT? (it might not be moved until after the start of cycle).  Genoveva could probably tell you when they plan to move it.

**Comment by KathrynBaker** [comment]
There is a second stress rig that could be set up offline, that would need to go via the engine-x scientists, and would likely need some GPIB setup, but could be tested on any computer.

**Comment by kjwoodsISIS** [comment]
Is the second stress rig identical to, or merely similar to, the first?

**Comment by KathrynBaker** [comment]
On,y runs to 50kN, but as far as we are concerned, it is identical

**Comment by John-Holt-Tessella** [comment]
Joe and Saurabh  are would like to help us and trial the interface

**Comment by Tom-Willemsen** [comment]
This was superceded by #2338 and is no longer required.
