### ISSUE TITLE
Polaris jaws: various minor changes

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2236]
After discussion with Ron Smith;

- Change readback value boxes on jaws OPI "animations" to use a non-etched border (Ron's comment was that it was unclear which one was the setpoint and which one was a readback)
- Add a "centre" option to the OPI + Jaws db records (this is always just an offset for each jaw set, there is nothing fancy needed here, functionality for calculating centres already exists in the jaws db records it just needs passing down from the jawset db record)
- Put setpoints (gaps/centres) at the top of the OPI and readbacks at the bottom. This is just a rearrangement, should be very quick and easy.
- In the OPI, add a message if manager mode is disabled and you can't set values. Ron's comment was that it wasn't obvious enough why you couldn't set values.
- Output the calculated values for jaw set 5, without actually causing the jaws to move. This might involve a bit of changing how the DB records work; check that the functionality is unchanged.
- Two decimal places is plenty. Can we just display 2 d.p. throughout the OPIs?
- Double check that the script used to "animate" the northern jaw in jaws manager works properly. When we demoed it the northern jaw didn't appear to move until we reloaded the OPI.

**Comment by John-Holt-Tessella** [comment]
This does not need to be in the candidate release this is an improvement requested during commissioning.

**Comment by Tom-Willemsen** [comment]
Review comments added on both PRs

**Comment by John-Holt-Tessella** [comment]
Added some extra docs https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Polaris-Jaws
