### ISSUE TITLE
Webdashboard: Investigate third party tools

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2240]
There are a number of sites (e.g. freeboard.io) that will allow the user to customise their view based on served up data such as JSON. 

Research the available options and produce a document as to the feasibility of using them, specifically:
* How much would we need to provide and under what format
* Do these tools allow us to add customised controls? E.g. a script server control might be very specific
* How usable are these tools for scientists?
* Are the tools under active development?
* Are there any costs?
* Are any of these tools used elsewhere on site/at other facilities?

**Comment by DominicOram** [comment]
Once this is done go back to #1375 to see what more needs to be done

**Comment by KathrynBaker** [comment]
Not applicable, new dashboard uses different methods,
