### ISSUE TITLE
Motors: Patch fix for motor limit switches

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2242]
In ticket #2174, we noted that the current behaviour of the motor record is dependent on the direction. That creates confusion in instances where the motor is moved externally or the IOC is restarted.

A potential fix for the issue is here:

https://github.com/epics-modules/motor/pull/36

For this ticket please:

- [ ] Examine the changes implemented for the fix to see whether they relate to our issue
- [ ] Cherry pick the fix into our fork of the motor submodule (on a non-master branch obviously)
- [ ] Test to see whether the fix solves our issue. As noted, restarting the IOC is a good way to see whether the limit flag persists.

**Comment by kjwoodsISIS** [comment]
Need to confirm that we still retain the ability to drive back over a limit (i.e. to get it back in range).
