### ISSUE TITLE
GUI: RB number search should use consistent date language

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2245]
As a user, I want the RB search dialog to be clear about dates.

- Open the Experiment Details perspective
- Click search (use NDXDEMO for sample data)
- The date column has header `Start Date` but the search filter is for `On Date`

There is a semantic difference between the two terms. We should be consistent about search categories. Suggest changing `On Date` to `Start Date`

**Comment by KathrynBaker** [comment]
The semantic difference in this case is valid. The date available for an experiment is the start date, but the date you might be searching for is not that date and so the query behind is (or should be) for experiments on a date. For example, the experiment could start on the 8th, but today is the 10th which is the day you want to search on.

**Comment by AdrianPotter** [comment]
That's fair enough but the search dialog only contains the start date. Could the search dialog contain the end date too? It would help with validation of the functionality and provide clarity to the user about the data associated with their experiment.

**Comment by KathrynBaker** [comment]
It could, that would be a different change though, as we don’t have end dates, we have start dates and durations, so that would be a calculation, and we would need to decide where to put that calculation

·         In the EXPDB program as we load things?

·         In the GUI as we display things?

·         In the query in the DBSVR?

Where and when would we want this information, as that would dictate which of the above is appropriate?

**Comment by AdrianPotter** [comment]
I don't have an answer now, that's a solution rather than the problem. I can see the argument for not putting an end date, but I feel that if I can filter by a field, I should be able to readily determine that the returned results meet that criterion.

```
As a user, I want to be able to see the time extent of my experiment so I can verify it and can be confident that search results are/will be accurate
```

**Comment by KathrynBaker** [comment]
Most users are familiar with andworking the system as it stands. Closing as no one has mentioned this outside of ourselves to my knowledge.
