### ISSUE TITLE
Script Generator: Blank row possible on enter sample name

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2251]
A Blank row can be inserted into the table with no clear way of deleting it by:

1. Add a sample name
2. Click on next row add position
3. Delete sample name

**Comment by John-Holt-Tessella** [comment]
Is #1659 related?

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
