### ISSUE TITLE
Script Generator: Disc height not the same as width on start

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2253]
The sample height and width are meant to be kept the same if the sample geometry is Disc but on first boot this is not the case.

1. Start the gui
1. Open the script generator view
1. set sample height to 4
1. Width does not change

If you not select disc as the geometry it will work.

**Comment by ThomasLohnert** [comment]
The current behaviour is that the width and height will not be linked from initialising the perspective to changing to "disk" from any other sample geometry, and always linked thereafter.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
