### ISSUE TITLE
genie_python: waitfor_move unexpected

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2255]
Wait for move does not perform the move is this  unexpected?

I expected

g.waitfor_move(Motor1=2, Motor2=2)

to move motors1 and 2 to 1 and 2 it doesn't. I think it should error if it isn't going to move the motors

**Comment by FreddieAkeroyd** [comment]
Unless it has changed, waitfor_move used to just wait for moves currently in progress to complete

**Comment by ISISBuildServer** [comment]
Waitfor_move waits for the move to finish, it does not do the move.

>>> cset(motor1=123)
>>> cset(motor2=321)
>>> waitfor_move()
>>> begin()

If the docstring doesn’t make this clear feel free to edit it.

Matt

**Comment by ChrisM-S** [comment]
just a query, but does the equivalent of the Open GENIE/SECI system

`    CSET/WAIT motor1=45.0`

exist in genie_python now?  I know waiting for multiple things is problematic with a single command as you can't queue a second request once the first command is waiting!

**Comment by mattclarke** [comment]
Yes, but waitfor_move is recommended for motion. /WAIT is more appropriate for, say, temperatures.

**Comment by John-Holt-Tessella** [comment]
Sorry yes I got mixed up with the syntax.
