### ISSUE TITLE
Turn off autoupdate on Java on Instrument machines

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#2257]
the JRE installer used on the NDX instrument control machines subtly installs an auto update component for Java.  Hopefully the users will ignore prompts to update - but from experience with windows updates in the past they may not - even though it is their experiment they may break by doing so.  The pop ups may also disrupt or confuse the experimenters.

To avoid this, turn off autoupdates permanently and add an instruction to the release instructions for IBEX to ensure that the most recent/secure version of Java is installed and that auto updates remain switched off, comments on this site https://community.spiceworks.com/how_to/65555-how-to-disable-java-update-notifications-on-windows-7-network-computers) suggest that doing an update re-enables auto-updates.

It may be better to run a more controlled explicit MSI uninstall/re-install which appears not to install the auto updater.

**Comment by FreddieAkeroyd** [comment]
Do we actually need Java installed system wide at all? The client bundles the JRE, do we just need to copy an appropriate JRE into the log server and archive server directories?

**Comment by ChrisM-S** [comment]
It would be useful to keep a system installed registration/manifest (ultimately of what IBEX depends on that is third party) - i.e. we are relying on someone else's binary build and their support.  I'm not sure if this would be kept up to date by Java if it is not properly installed.  If it is publicly installed on the system, it's easy for us, and others to check for patch levels etc.  If side by side execution is required, it is also obvious that this is going on.  Although a little more work, incorporating an installer which installs multiple sub package .MSI files, this does achieve both aims (one simple click install for a client user and proper registration of components and dependencies for the system and security management etc.).

![manifest](https://cloud.githubusercontent.com/assets/3035405/25283845/11c3ca08-26ad-11e7-9c12-c2759e3c92cc.png)

**Comment by FreddieAkeroyd** [comment]
It would not be kept up to date by auto-updates, but as we are planning to turn that off anyway I don't think that is an issue. If we plan to update java when ibex is updated, then automatically copying in a jre to the appropriate locations when ibex is updated would achieve that and save running an extra installer. We would also not have a system installed java that may reduce our exposure to other vulnerabilities.

**Comment by kjwoodsISIS** [comment]
1. Yes, we should do it.
1. Work out how to do do it.
1. Do it.

**Comment by kjwoodsISIS** [comment]
Added extra step to Deployment tests section on [Deployment](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC) wiki to make sure this gets checked on each deployment.

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - I have updated the Deployment wiki.  When the next release of IBEX is deployed to each instrument the auto-update feature will be turned off.  I think that should be sufficient for this ticket.  Do you agree?  (I'll set a reminder in my diary to check that it has actually been done before the start of the 2017/02 cycle).

**Comment by ChrisM-S** [comment]
Yes, I think turning off the Java updates on the installed machines from the control panel is sufficient.

### note:
If it becomes necessary to update the Java version, it can be done from the control panel but after the update it is important to re-open the control panel to check and then possibly re-disable the automatic updates.
