### ISSUE TITLE
GUI: Tweaks

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2259]
- [ ] Move the DAE abort buttons to being on its own at the bottom, rather than the save as the abort is more dangerous
- [ ] Make config dialog have a minimum height which includes the add buttons on both the IOC and groups page. At the moment it is possible to reduce the height of the windows so much that the add button disappears.
- [ ] Configurations – IOCs tab – Name column could be narrower to give more room for descriptions

**Comment by kjwoodsISIS** [comment]
Check more widely about moving the Abort button.

**Comment by KathrynBaker** [comment]
I have sent an email asking about the buttons, will look into the other two aspects whilst awaiting responses.

**Comment by KathrynBaker** [comment]
Responses received, 15 of the instrument scientists, those currently using IBEX were asked about the moving of the buttons, with a comment that abstentions were taken as maintaining the current position: 1 answered no, 7 did not reply, 7 asked for the buttons to be moved. As such, at this time, the buttons are not being moved. This may need to be revisited in the future as the vote was close, but that task is not being undertaken at this time.

**Comment by mattclarke** [comment]
Fair enough, but we shouldn't lose the other less controversial tweeks John suggested, so I will make tickets for those.

Assuming tickets don't already exist...

**Comment by mattclarke** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/2382

**Comment by KathrynBaker** [comment]
Apologies for causing confusion, I failed to link the pull request for the non-controversial changes to the issue.

PR is https://github.com/ISISComputingGroup/ibex_gui/pull/510
