### ISSUE TITLE
GUI: Allow blocks to added to preexisting graph instead of a new graph

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2261]
As a scientist if I ask a block or PV (from an OPI) to be plotted I want to have it plotted on a new plot or an existing plot so that I can view variables changing together.

**Comment by DominicOram** [comment]
This will most likely be affected by eclipse 4 changes

**Comment by DominicOram** [comment]
Functionality now exists in IBEX
