### ISSUE TITLE
Dataweb: Order the PVs in the run information section

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2263]
As a scientists viewing the dataweb I would like the PVs within the run information section to be ordered better so I can find them more easily. The old dataweb under SECI was fine.
Requested at the training by Vicky from IRIS.

**Comment by AdrianPotter** [comment]
- [ ] This issue has been raised again by Dominic Fortes on HRPD. Please let him know when it is done.

**Comment by AdrianPotter** [comment]
- [ ] Also raised by Winfried on IMAT

**Comment by mattclarke** [comment]
PR works. Can you tidy up the comments as I have indicated and sort out the merge conflict please?
