### ISSUE TITLE
genie_python: Load_script path functionality may be broken

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2267]
Load script does not see to use the genie script dir anymore to load scripts.
It also does not seem to tab complete the path
Finally does it correct the slashes if wrongly placed?

**Comment by DominicOram** [comment]
On the third point: The issue was in which path was given to the script checker, I think I have fixed this in https://github.com/ISISComputingGroup/genie_python/pull/77

**Comment by AdrianPotter** [comment]
Having tested on master using the scripting perspective and a plain genie_python console:

- load_script does look in the `C:\scripts` directory
- Tab complete works on paths in a genie_python console but not in the scripting perspective. PyDev doesn't use the same completer as IPython. I can't find a way to change it in PyDev
- Incorrect slashes are corrected

Given the above, I haven't made any changes.
