### ISSUE TITLE
Polaris: IOC, OPI and Emulator for INT2-L

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2270]
Polaris need this by the end of May.

The Applied Measurements INT2-L is a pressure transducer. Polaris uses it for the Hydrothermal Reaction Cell.

**Comment by davidkeymer** [comment]
See page 8 in the following manual for the format of the single command to read the pressure when the device is configured to be in "Protocol P1" mode (Polled ASCII).  The command is preceded with the device address, which in the case of that on POLARIS is 0xAB on COM16 with 8n1.

[INT2-Serial-Output-Manual.pdf](https://github.com/ISISComputingGroup/IBEX/files/955028/INT2-Serial-Output-Manual.pdf)

**Comment by kjwoodsISIS** [comment]
POLARIS has experiments scheduled for 22-25 May and 30 May - 1 June.  I assume "end of May" refers to one of these.  Do we know which one?

**Comment by kjwoodsISIS** [comment]
OK, great.  That gives us a clear deadline to aim for.
P.S. could you paste Ron's e-mail to this ticket? Just so we have the full context.

**Comment by DominicOram** [comment]
> Dom,
>
> If we do use it it won't be until the end of May-beginning of June.
>
> Ron.

**Comment by John-Holt-Tessella** [comment]
David is finding us one of these.
