### ISSUE TITLE
Python & genie-python Training Course

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2271]
As a scientist, I would like training in Python, so that I can create Python scripts and use genie-python to control my instrument.

#### Acceptance Criteria
After attending the course, I can 
1. write simple, well-structured Python scripts.
1. use genie-python in my Python scripts to control my instrument effectively.

#### Notes
1. The Mantid team have compiled an [introductory Python programming course](http://www.mantidproject.org/Introduction_To_Python).  Could we adapt that?
   1. the course needs to be specific for IBEX
   1. we could split the course into two sessions: one being an introduction to Python, the other being an introduction to genie-python.  The two sessions could be presented on different days, if there is too much to take in on a single day.
1. Can we recommend a suitable Python-aware editor that scientists could use?  Note:  a Python-aware editor might be more appropriate than an entire Python IDE (we may not want to support an entire IDE).
1. The course should also be suitable for technicians or engineers who might occasionally need to run scripts.
1. We can use the PCs used for the neutron training course, if required (there are ~40 of these).
1. The course should be run once per shutdown
   1. pick a date during the a shutdown (pick this date well in advance)
   1. advertise the course and invite scientists to sign up
   1. if nobody signs up, cancel the course

**Comment by ChrisM-S** [comment]
Just a couple of thoughts about what IDE/editor might be suitable if it was to be run on the instrument machines (not a given that it has to, but we will probably be asked).

Is Notepad++ Python aware enough?  It does have some issues of its own, but we have learnt to live with it on the instrument machines.  Also, what is Nicos using as a client for script development, could this provide an intelligent command line we could adopt?

**Comment by kjwoodsISIS** [comment]
Notepad++ might be suitable - we'd have to check.  But there are other, relatively simple editors (e.g. [Anaconda](http://damnwidget.github.io/anaconda/#anaconda-overview)), which might not be too much of a jump from Notepad++.

The Nicos UI is built on Qt - it is not suitable for use with IBEX.

**Comment by davidkeymer** [comment]
I have two printed copies of the "Introduction to Python" booklet from the training course run by the Mantid team.  Also one printed copy of their booklet "Python in Mantid".  Let me know if anyone would like to borrow them as a reference for creating our own courses.

**Comment by AdrianPotter** [comment]
A step up from Notepad++ would be to use IDLE. It gives additional script checking over Notepad++ and there's less issue with mixed white space. It has the added advantage of already being on instrument machines because it's part of Python

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/genie_python-and-Ibex-%28Introduction%29

**Comment by samueljackson92** [comment]
Some minor comments:
 - Common Commands:
   - Experiment setup: Why wouldn't I want to apply settings immediately?
   - Experiment details: How do I get the state of an experiment? 
 - Scripting
   - Writing scripts: The function definition example is not valid python.
   - Exercise 3 solution seems inconsistent. Shouldn't there be a `waitfor` call somewhere (i.e for 1 or 0.1 seconds)?

Some more general comments:
 - Consider making use of github markdown to [highlight](https://help.github.com/articles/creating-and-highlighting-code-blocks/) the python & fortran code examples
 - Are you planning on have a separate tutorial for the IBEX GUI?
 - Would it be useful to provide users with a default configuration with blocks/iocs etc. ready to go?

**Comment by mattclarke** [comment]
Sorry to chip in late with a comment 

I think it would be better if we could ween them off using the catch-all change command and instead use the more specific command. For example: change_title("dasdas") rather than change(title="dasdas").
I included the change command because it might be useful for automatically migrating scripts, but in hindsight I think that was a mistake.

**Comment by AdrianPotter** [comment]
@mattclarke. Why don't you like the `change` command?

**Comment by mattclarke** [comment]
Nothing major, but I think, for example, `change(title="sdfsdf")` has more things that can go wrong than `change_title("sdfsdf")`.

```
# I am a user who is not totally comfortable with Python
>>> change("title"="my title") 
>>> change(title=my title)
# I am an instrument scientist who has been up all night
>>> change(tilte="my title")    # This would get past PyCharm even
```
If it was in a script then the script-checker should pick it up.

Perhaps, more importantly there is the docstrings:
```
>>> help(change)
    Change experiment parameters.

    Note: it is possible to change more than one item at a time.

    Args:
        title (string, optional): the new title
        period (int, optional): the new period (must be in a non-running state)
        nperiods (int, optional): the new number of software periods (must be in a non-running state)
        user (string, optional): the new user(s) as a comma-separated list
        rb (int, optional): the new RB number

    Examples:
        Change the title:
        >>> change(title="The new title")
        Change the user:
        >>> change(user="Instrument Team")
        Set multiple users:
        >>> change(user="Thouless, Haldane, Kosterlitz")
        Change the RB number and the users:
        >>> change(rb=123456, user="Smith, Jones")
```
versus:

```
>>> help(change_title)
"""
    Sets the current title.

    Args:
        title: the new title

    Example:
        >>> change_title("The new title")
    """
```

**Comment by AdrianPotter** [comment]
Sounds fair to me. I prefer `change` from an extensibility point of view, but it seems likely that the number of new `change` commands will be limited since the scientists generally already have what they need. I agree it's also well offset by the consideration about errors owing to the average user's experience level.

**Comment by FreddieAkeroyd** [comment]
In exercise 5 it says "It's not recommended to put everything as an argument and always provide defaults" - should that be "Rather than hard-coding values or using globals, it's recommended to use arguments with a default".

**Comment by FreddieAkeroyd** [comment]
We have g.waitfor_runstate("WAITING") but then use   g.get_runstate() == "WAITING", should we have a g.is_runstate("WAITING") function? It could then check that the supplied argument is a valid potential runstate too

**Comment by mattclarke** [comment]
Sounds good, but I wonder if we should be go for is_running(), is_waiting(), is_paused(), and is_setup(). Are there any others?
I'll create a ticket.

**Comment by ChrisM-S** [comment]
Oh dear, how about is_processing()…?

**Comment by FreddieAkeroyd** [comment]
or g.is_something_wrong() ...
