### ISSUE TITLE
TDK Lambda Genesys IOC: Modify the setup on MUONFE to use the disable options added in ASYN

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2276]
As part of ticket #1594, a change has been added to our local asyn code to allow an option of setting a couple of the parameters to Off, this needs to be applied to MUONFE, and the testing completed, before cycle 17/2 (September 2017)

**Comment by FreddieAkeroyd** [comment]
This has now been added

**Comment by FreddieAkeroyd** [comment]
Leave a comment
