### ISSUE TITLE
DAE: Wiring Tables: Where should we be looking for them?

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2277]
Some extra wiring tables for the DAE on ZOOM were created, and SM had put them in `C:\Instrument\Tables`, IBEX seems to be looking for them in `C:\Instrument\Settings\config\{Instrument}\configurations\tables`. We need to make sure that the location is correct, and that all who are likely to write these tables know where to put them. Or if both locations are correct, we ought to show both listings in the drop down.

**Comment by FreddieAkeroyd** [comment]
C:\Instrument\Tables  and c:\labview modules\dae were common locations for SECI - we could make c:\instruments\tables a link to  C::\Instrument\Settings\config\{Instrument}\configurations\tables though as an intermediate measure

**Comment by kjwoodsISIS** [comment]
Agree a single location.  Tell Electronics where they should put them.
If you migrate an instrument, need to put wiring tables in the right place.

**Comment by kjwoodsISIS** [comment]
[Deployment](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC) wiki update to ensure that wiring tables get copied.

**Comment by kjwoodsISIS** [comment]
@KathrynBaker : is the update I have made to the Deployment wiki sufficient to address this ticket (apart from the bit about telling Electronics)?

**Comment by KathrynBaker** [comment]
It might be worth deleting the ‘old’ location when we do the migrations (and checking it isn’t there on new instruments), but apart from telling electronics that is about right.

Regards,
Kathryn

**Comment by kjwoodsISIS** [comment]
What is the "old" location?  Do you mean `C:\Instrument\Tables`?

**Comment by KathrynBaker** [comment]
That’s the one.

**Comment by ChrisM-S** [comment]
It might also be worth making sure there are no wiring tables left in `C:\LabVIEW Modules\dae`.  i.e. moving any table files into the final destination (but not removing the folder for obvious reasons).  Better in the instructions to use the word "move" rather than "copy".  There is a temptation to leave files if they are copied - which is how we got into this sorry state in the first place :-).

**Comment by kjwoodsISIS** [comment]
What if the scientist wishes to continue using SECI ( at least for a transition period)?  This might not be an issue for instruments like LARMOR, IMAT or ZOOM, but what about instruments we have migrated?

**Comment by KathrynBaker** [comment]
They just need to load from that location instead, as I understand it there is no limitation on the browsing in SECI, so they should be fine.

**Comment by kjwoodsISIS** [comment]
[Deployment](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC) wiki updated to ensure that wiring tables get moved.

**Comment by KathrynBaker** [comment]
Have we actually told the detectors/electronics teams about this yet? If so, ticket is done, if not, are we going to? If we aren't going to tell them, the ticket is done as well.

**Comment by kjwoodsISIS** [comment]
Electronics have been informed:
> Sent: 15 May 2017 14:22
> Subject: Wiring Tables for IBEX
> 
> Hi Kelvin, Hi Simon,
> 
> There has recently been some discussion about where wiring tables are located in the new IBEX instrument control system.  
> I thought I ought to e-mail you to let you know where the wiring tables in IBEX are stored.
> 
> In IBEX, wiring tables are stored in the following location:
>     C:\Instrument\Settings\config\NDXxxxxx\configurations\tables
> where NDXxxxxx is the name of the instrument control server (e.g. NDXIMAT for IMAT, etc.)
> 
> We have documented the location on our Deployment wiki page.
> 
> If you have any questions or queries, please contact any member of the Controls team.
> 
> Best regards,
> 
> Kevin
