### ISSUE TITLE
Eurotherm: Set units from calibration file

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2279]
If the calibration file for a eurotherm is not in units of Kelvin then the IOC has the wrong units. This is unacceptable. . Solutions could be:

1. Allow a user to set the unit of the calibration file (add/expose PV and OPI field)
2. Split calibration files into folder which are dependent on there unit
3. Add a metadata file with the same name as the calibration file but with a `.info` extension in this file add calibration information like units but also allow things like comments and range.

I like 3 best lets do this.

Extra information:

1. @GDH-ISIS said it would take 1/2 a day to update all labview instance to use a new file format and this would not be a drama.
1. Final format will be documented on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files

**Comment by KathrynBaker** [comment]
I don’t like 3 – it’s an OK option at the moment while we have to maintain the two systems (I’m just thinking about the conversion time which is already a pain, when there are other files for a lot of the sensors which already have this information in a header), but this would be information to keep in a header of the file in the long run, I’d rather 1 and just put it through as a macro if it is just the units, and reconsider the information when we only have one system to support. After all the EPICS one can be given a number of lines of header for the cvt record, which is not available in SECI – so is an easier change when that time comes.

**Comment by kjwoodsISIS** [comment]
What we have agreed to do:
1. Choose a calibration file format, which includes a meta data header
1. Implement it.

**Comment by FreddieAkeroyd** [comment]
The cvt record supports # as a comment in a header http://www-csr.bessy.de/control/SoftDist/csm/index.html

**Comment by KathrynBaker** [comment]
I knew it could take a number of lines, I couldn’t remember about a header character which is why I was being cautious, if it has one, great, less of an issue.

**Comment by Tom-Willemsen** [comment]
Re-requested by Helen Walker (Merlin)

**Comment by John-Holt-Tessella** [comment]
Rerequest Sandals

**Comment by DominicOram** [comment]
+1 Support call from MERLIN regarding this

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/89
- https://github.com/ISISComputingGroup/EPICS-eurotherm2k/pull/6
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/271
- File format examples at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files and full examples added to eurotherm support module `C:\Instrument\Apps\EPICS\support\eurotherm2k\master\example_temp_sensor`

**Comment by FreddieAkeroyd** [comment]
At the controls section meeting we feel we may need to discuss the file format further.

**Comment by Tom-Willemsen** [comment]
In that case, should I put this ticket into impeded awaiting that discussion or is that more of a long-term discussion?

**Comment by KathrynBaker** [comment]
Probably,

Regards,
Kathryn

**Comment by kjwoodsISIS** [comment]
How much additional discussion is required?  What issues do we need to resolve?
Can we arrange this meeting soon, otherwise there is a risk that the ticket drifts...

**Comment by KathrynBaker** [comment]
The main discussion that is required is whether or not the solution designed is actually acceptable on a long-term technical side of things, and if there is a better way of doing it then we should do it right in the first place. I do not want more work in the long run, as the less I have to do by hand, the fewer mistakes I’ll be able to make.
The biggest issue that I can see is that this solution ignores completely the original file formats, which carry this very information. If we can write this to use the provided files, rather than my having to do all that I currently do, and then add a new line at the top it strikes me as a much better solution.
I haven’t tried building or running any of the checkers on this, and I’m already sending it back for rework in my head, as the solution is not adequate in my opinion, and so I would not be happy to see it go through.

**Comment by FreddieAkeroyd** [comment]
We should weight up the existing formats and if we do need to invent our own format, then it should obey the following:

- It should have a unique (magic number) header line indicating it is our format and also a format version number to allow future changes/extensions
- It should be able to store all metadata from any converted file (using common/standard keywords)
- It should use an existing extensible encoding format in the header e.g. YAML or JSON and not one we invent, this will make parsing easier and less error prone
