### ISSUE TITLE
IBEX: Allow instrument scientists to choose units

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2280]
Think about how to change units within IBEX. So for instance can instrument scientists have the Eurotherm temperature in Centigrade? This has lots of knock on questions like do we change the run control limits? Do we send this data raw or converted to the NEXUS file. Do we manage this at the IOC level or higher. Do we try to guess what group the units belong to  (e.g. temeprature, mass) or do we have this specified.

**Comment by KathrynBaker** [comment]
This requires considerable thought and interaction with users, closing as scope is not clear. Eurotherms have an alternative to ensure that the unit is correct, most items have specific units very few are this variable, and each are dealt with as appropriate.
