### ISSUE TITLE
Add IOC description to "Add IOC" dialog

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2287]
As a user, I would like to be able to easily identify IOCs that I want to add to a configuration. At the moment, the "Add IOC" dialog gives me the IOC names which are not necessarily easily understood by users. An obvious solution would be to include the IOC description on this dialog.

**Comment by KathrynBaker** [comment]
See #1447 for similar requirements and extra locations this would be helpful, along with some solutions. Note also that #1471 was partially to solve #1447
