### ISSUE TITLE
ALF: Change goniometer axis name on OPI

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2288]
As a user, I would like the "theta" axis in the OPI goniometer to be called "RRot" to be consistent with the other axes

The Goniometer OPI is used exclusively on ALF. The common terminology for the device for the rotational axis is "RRot" rather than "Theta". Please could the OPI be changed to reflect this. This involves two changes:

1. Update the label on the OPI (note that this may or may not include updating the PV names)
2. Update the diagram. This might need a little photoshopping. In the worst case, Russell said we can go and take a new picture.

**Comment by KathrynBaker** [comment]
The naming on the ALF axes may have come from their previous interfaces.

I may still have an original, pre editing, copy of the photo (actually a screen shot from a webcam)

**Comment by KathrynBaker** [comment]
I do have the original image still.

**Comment by AdrianPotter** [comment]
As per an anonymous suggestion, it might be worth going down and getting a new picture with a better camera than the webcam. The webcam's capabilities are limited :)

**Comment by KathrynBaker** [comment]
However, it has taken me all of two minutes to find the picture and put the correction to the label in (I still had my interim stage with labels). We don’t typically take those kinds of photos. 

Still, as I had the file, I’ve created an updated version of the current photo – for the time it has taken, it doesn’t stop a new photo being taken. I've put a copy of the altered png in the design folder for the wiki (assuming that the folder has taken)

**Comment by AdrianPotter** [comment]
Thanks Kathryn. Please could you quickly check that link. As it's a relative path, it behaves differently where you open it from:

Source page: https://github.com/ISISComputingGroup/IBEX/issues/2288
Destination page: https://github.com/ISISComputingGroup/IBEX/issues/design/ALF-Gonio-RRot.png

Source page: https://waffle.io/ISISComputingGroup/IBEX
Destination page: https://waffle.io/ISISComputingGroup/IBEX/cards/design/ALF-Gonio-RRot.png

**Comment by KathrynBaker** [comment]
Fixed on git, don’t really want to provide it as an absolute path, so is unlikely to work from waffle.

**Comment by Tom-Willemsen** [comment]
Marking this as impeded, awaiting new picture

**Comment by kjwoodsISIS** [comment]
If we need a new picture can someone please arrange to go to ALF and take some photographs.  Please make sure we photograph the goniometer from the right angles, to ensure all the axes are in the shot.
