### ISSUE TITLE
IOC: McLennan reverse home and limit not working on Vesuvio

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2289]
Vesuvio has reported that their back scattering foil, which uses the McLennan in "Reverse home and 0" mode isn't working as expected. On inspection, it was reversing to the limit but not then applying the zero position. In one instance, the motor changed direction mid-home. Please investigate

**Comment by AdrianPotter** [comment]
I've tested this on my local machine with a simulated motor. It is different in the sense that the "Reverse" part of homing won't work with a simulated motor as that's a feature of the McLennan driver. However, the 0 part should work as expected. It doesn't. I've observed direction reversals and failures to zero.

**Comment by kjwoodsISIS** [comment]
Report back to Vesuvio when complete.

**Comment by AdrianPotter** [comment]
We don't have a McLennan with a home switch in the office so I can't test the fix I've put in. I've emailed Giovanni to see if we can do it directly on Vesuvio some time soon

**Comment by AdrianPotter** [comment]
I've tested on Vesuvio and it seems to be working fine. I just want to check on the motor in the office to ensure homing mode 1 has been unaffected by the changes
