### ISSUE TITLE
IRIS: Check that configs are being pushed

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2293]
I just tried to have a look at the Iris configurations with Vicky. I did a clone of the repository on my local machine and it didn't match the configuration files as seen on NDXIRIS. Git was reporting on NDXIRIS that the configuration was up-to-date. This suggests to me that the configuration isn't being pushed to the online repo. Please could someone have a look and check whether that's the case and fix if so

**Comment by John-Holt-Tessella** [comment]
Confirmed this morning that they are the same with last change 26th not sure what this was. We will be vigilant in the future.
