### ISSUE TITLE
Motor: Lin mots and Mclenans do report motors are moving

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2299]
As a user on Vesuvio I want the g.waitfor_move() command to work when my foil moves. It currently does not. 

I have done a small amount of debugging with a simulated mclenan motor and it appears that the PV CS:MOT:MOVING is not being set when the motor moves (i.e. the label Motors are Stationary does not change). I think that this should be set up in `...EPICS\support\motor\master\motorApp\Db\motorUtil.db` in 
record(dfanout, "$(P)_FAN") record where there are macros specific for motor types.

Steps to ticket are:

1. Check this is the problem
1. Check this is the solution
1. Implement it
1. Document it in the IOC workflow

**Comment by AdrianPotter** [comment]
1. Verified on my machine too. Galil's affect global motor status, McLennans do not.

**Comment by AdrianPotter** [comment]
2. Doesn't look so simple to me. The Galils use #IFDMC to indicate which motor "row" to use and can only go up to 8. The Mclennans and Linmots use #MTRCTRL which is set to an integer between 0 and 24 (given that's how many we include in the GUI. There are macros of the form #IFMTRCTRL24 but that would be cumbersome to implement. I also don't know how the motors link into CS:MOT:MOVING.

**Comment by FreddieAkeroyd** [comment]
INSTETC keeps track of the global moving flag, MOVING1 is merged with MOVING so you just need to watch that. As motion is across multiple IOCs splitting each IOC into a different calc record is safest to avoid possible misses, so currently each IOC needs to load motorUtil.db and map to a different calc record input to avoid clashes of values. The mechanism is independent of what table of motors position the ioc occupies, though it might look like that was true from the way the galil is implemented. So it should just require adding IFIOC_MCCLEN_01 to motorUtil.db etc. and loading this into the mclennan ioc

**Comment by FreddieAkeroyd** [comment]
I've added instructions to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Adding-motor-IOC-to-global-motor-moving-and-stop-all
