### ISSUE TITLE
Synoptics: Unavailable on startup

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2306]
Rob (Larmor) has reported that he is still getting the issue from #2074 with release 3.2.0

>Reported by Rob on Larmor. I've witnessed it once locally too.
>
>As a user, sometimes when I open the GUI and go to the synoptics view, none of the synoptics will appear. This seems to occur after restarting the server.
>
>It might be a problem if the synoptics view is opened before the block server has started.
>
>Solution is to restart to client but it'd be nice if users didn't have to do that

**Comment by AdrianPotter** [comment]
Also reported by Winfried on IMAT. Let him know when it's fixed.

**Comment by AdrianPotter** [comment]
This is still a problem, Rob and Winfried have asked for it to be fixed. It's also regularly causing system test failures.

**Comment by John-Holt-Tessella** [comment]
Could this be related to #2527 when you save a config with a syoptic in which is recommeneded it saves it <synopic name> (recommended), when this is loaded could this cause a crash?

**Comment by DominicOram** [comment]
Just seen on ZOOM
