### ISSUE TITLE
genie_python: Add function which alerts the user when script fails

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2310]
As a scientist I want to be optionally informed when a script I am running finishes especially if that script fails. This is so that if my script errors in the middle of the night I do not lose beam time. It does not matter if it is my mistake or instrument failure.

Can we create a way of running script and functions which sends an SMS when the script finishes running and send an error when it fails.

Acceptance Criteria

I get an SMS message if my script can not set a value on an IOC because that IOC has been stopped.
I get an SMS if my script throws an exception
I get an SMS (if asked for) when my script finishes.

Running a script can be by either `g.load_script` or `my_function()` (if you need to we could do alert_on_fail(my_function()) Maybe add a decorator to the script itself to allow me to do this.

**Comment by GRyall** [comment]
This can be written into scripts in an appropriate way using alerts on run state as per [https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Alerts-on-Blocks](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Alerts-on-Blocks).
