### ISSUE TITLE
Galil dummy axis homing routine

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2313]
As a developer It would be useful to have a galil homing routine that can be used by a controller with no motor attached. There is a  galil_Home_Dummy_Axis.gmc   in the distribution, but that is for a different special case.

Acceptance criteria

Can load new gmc file onto galil controller with no motor attached and perform both HOMER and HOMEF from GUI/command line

**Comment by GDH-ISIS** [comment]
Please find attached two homing routines (zip file). Both homing routines do not move an axis as I thought that would be inappropriate if put on a beam line. They complete in roughly 5sec. One shows nothing, the other turns on a power light, then turns it back off.
These files need to be located in :
..\EPICS\support\galil\master\GalilSup\Db\galil_Home_Dummy_Do_Nothing.gmc
..\EPICS\support\galil\master\GalilSup\Db\galil_Home_Dummy_Power_Light.gmc
The file : ..\EPICS\support\galil\master\GalilSup\Db\Makefile needs to include these two file names i.e.
GMC += galil_Home_FIpos.gmc galil_Home_FIneg.gmc galil_Muon_Slits.gmc galil_Home_Dummy_Do_Nothing.gmc galil_Home_Dummy_Power_Light.gmc
I have managed to check them as best I could using LabVIEW TOM and they appear to be ok. I am not sure whether the Galil ioc communicates with the Galil hardware correctly - lots of timeouts going on, but it did download the program to the Galil. 
To test, please edit the GalilStartController line in the file : C:\Instrument\Apps\EPICS\support\galil\master\iocBoot\iocGalilTest\galil.cmd

[gmc.zip](https://github.com/ISISComputingGroup/IBEX/files/1103760/gmc.zip)

**Comment by GDH-ISIS** [comment]
Please note, the file ..EPICS\support\galil\master\GalilSup\Db\galil_Home_Dummy_Axis.gmc should be removed. It does not reflect anything specific in relation to this project and could be configured in error.

**Comment by GDH-ISIS** [comment]
I am afraid this ticket is currently impeded as I am unable to get the Galil ioc to operate correctly - with UDP timeout errors and with TCP unsolicited messages not being received so the homing routine will not assign the home position. I believe the galil procedures would operate correctly as the program is downloaded to the Galil from the EPICS Galil ioc correctly and it does run in the Galil. I have used LabVIEW to confirm that the procedures do run. I have also been to ALF to confirm that the homing routines do actually run with EPICS - which they do. The unsolicited homing messages are received by the Galil ioc correctly on ALF. Not sure if it is just my machine or whether a change has been made.

**Comment by John-Holt-Tessella** [comment]
These can be tested on demo.

**Comment by AdrianPotter** [comment]
Looks fine, does what it says on the tin, please just add a README in the homing folder so that it's clear what the homing routines do. It's not clear to me as an amateur what the power light routine does that the dummy routine doesn't

**Comment by John-Holt-Tessella** [comment]
see readme in folder
