### ISSUE TITLE
MUONFE: OPI: Muon style jaws (just a gap, no individual postions)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2334]
As a scientist using the MUONFE system, I would like a GUI that shows/controls the state of individual jaw sets, so that I can control jaw sets singly.

 #### Acceptance Criteria ####
1. The GUI displays the following fields:
   1. Actual Slit Width
   1. Set Slit Width
   1. Slit Moving status indicator
1. The GUI allows me to change the following field:
   1. Set Slit Width
1. The GUI includes a button which I can use to drill down to the individual motor view.

#### Notes ####
1. There are 4 slits controlled by the Muon Front-End - the Momentum slits (shared by all 3 muon instruments) and one set of "barn-door" slits per instrument.  See [MuonFE_Slit_Schematic](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muon%20FE/MuonFE_Slit_Schematic.pdf) for details.
1. Each slit has a single degree of freedom (namely the width or gap of the slit).
1. Check the width units (presumably measured in mm).
1. The GUI should show the details for a single slit.  See [MuonFE_Slit_OPI_Schematic](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muon%20FE/MuonFE_Slit_OPI_Schematic.pdf) for a schematic of how the GUI could look.
1. The GUI should be configurable for different instruments/motors using macros.

**Comment by KathrynBaker** [comment]
To clarify, there is already an OPI which displays all 4 slits at once, this would be an OPI for an individual slit set which could be called multiple times from different locations in a synoptic.

If we can include a graphic as per the standard 4 motor, 2-way gapped slits it could be nice, but it is not necessary.

It would need to read the gap, set the gap, and link off to the underlying motor screen.

**Comment by kjwoodsISIS** [comment]
Original text of ticket:
As a scientist using the MUONFE system, I have requested a GUI, and would like to be able to look at jaw sets individually not just in the group of four.

**Acceptance Criteria**
1. There is an OPI that can be treated as a slit set, but which shows only the gap - this should not be named to be Muon explicit

**Comment by DominicOram** [comment]
when this is done update the muonfe overview OPI

**Comment by DominicOram** [comment]
For an example of jaws that are coupled to run from 1 motor see ENGINX opis

**Comment by KathrynBaker** [comment]
Moved back to Ready as 2400 is now complete so this is no longer impeded
