### ISSUE TITLE
GUI: Configurations: deleted components still appear as "available"

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2340]
A deleted component can still appear in the list of available components under "new configuration".

To reproduce:
- Create a new component
- Delete the component you just created
- Create a new configuration
- Bug: component appears in list of available components

**Comment by DominicOram** [comment]
I can't reproduce this. Can anyone else?

**Comment by AdrianPotter** [comment]
Tried this a number of times. Could not reproduce
