### ISSUE TITLE
GUI: Right click to edit block contains two "edit block" buttons

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2341]
This happens inconsistently but both @AdrianPotter and I have seen this occur on a number of occasions.

When you right click to edit a block, the dropdown list contains two "Edit block" buttons as shown in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/24375813/26244976/ff5be3da-3c89-11e7-8fea-953fda2e60c0.png)

**Comment by KathrynBaker** [comment]
This now looks to edit the host configuration or component rather than the block, so this is no longer applicable
