### ISSUE TITLE
IOCs/Blocks: disallow writes where it would cause errors

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2343]
Some records in IOCs should be interesting but readonly.

A concrete example of this is the `move_finished` block on the rotating sample changer for polaris. The instrument scientists had accidentally set the value of the `move_finished` block from a script, which had allowed the IOC to get into a strange state because this block's value should never have been set externally.

This ticket is to consider and implement a pattern for having DB records which are "interesting" but should not be written to.

Possible solutions:
- Set the `DISP` field on the relevant record
- Use EPICS access security to make that record read only
- Implement some other mechanism for defining that a block should not be written to
- ...?

Inform Ron Smith and Helen Playford (POLARIS) when this ticket is complete

**Comment by samueljackson92** [comment]
We decided to go with the access security option as this prints a nice error message to the user from the python console. Also decided that interesting `calc`, `calcout` and `transform` PVs should be readonly and have added a check to the `DbUnitChecker`
