### ISSUE TITLE
IOC tests: add timeout

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2348]
If the IOC system tests take too long to run they should fail.

Currently the framework seems "stuck" on Jenkins, this is the tail end of the log file:

```
---------------------------------------
TESTING JULABO Rec Sim

Running tests...
----------------------------------------------------------------------
.S.SS.SS.SS
----------------------------------------------------------------------
Ran 11 tests in 24.109s

OK (skipped=7)

Generating XML reports...
CA.Client.Diagnostic.................................
    Warning: "Virtual circuit unresponsive"
Source File: ..\tcpiiu.cpp Line Number: 945
.....................................................

```

This "test" has been running for over 15 hours. This also causes NDWRENO not to be able to run any other builds in the meantime. We should fix this.

**Comment by John-Holt-Tessella** [comment]
On going to NDWReno I saw an error for JULABO-IOC-01.exe saying that it had stopped working and did I want to close the program or debug it. (probably it is this that has caused the problem. Maybe all we need is a terminate on the exit of an IOC after a time out.

**Comment by FreddieAkeroyd** [comment]
There is an issue with the IOC exit handlers and the IOC log client, I have traced it in the debugger and will commit a fix.

**Comment by DominicOram** [comment]
I have added a step in Jenkins for this. To test:
* Log in to Jenkins
* On the configure screen for the IOC system tests set the timeout to 1 min
* Run the IOC system tests, confirm that it fails after 1 minute (ish)
* Remember to set it back to 60 minutes after this test!
