### ISSUE TITLE
Writing to global PVs: Alert when certain PVs are written too

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2352]
As an IBEX support person I want to know when someone has altered some of the global PVs unexpectedly

**Acceptance Criteria**
1. Some form of monitor is placed on global PVs that should only be altered with care - e.g. the instrument list
1. The monitor ignores items that are kept globally that will change regularly - e.g. the beam logger information
1. When monitored items are changed, some form of alert is generated - e.g. Nagios? Email to IBEX support

**Notes**
1. This follows on from #2197

**Comment by FreddieAkeroyd** [comment]
Rather than monitoring then, shouldn't we just change the update process? For example CS:INSTLIST is loaded from a file on IOC startup and in a read-only PV

**Comment by KathrynBaker** [comment]
It depends on how easy it is to maintain the file – if only a couple of people have access to it then it becomes harder to add to the instrument list than it is now, but is certainly an option, this is just what we ended up with as a solution in the security meeting the other day.

**Comment by ChrisM-S** [comment]
Two things, 

1)	Seems to me that we should keep this file in the top of IBEX client distribution/build and check it into github.  This guarantees that anyone who can commit a change to the client can change it easily, the change is recorded and it is easy to revert. Anyone can refresh the latest version by doing a git update (well perhaps it should be in a private repository or we could just leave of the NDX bit?)

2)	After this,  for my money, the client could then copy the file from off a highly available read-only server area in the normal fashion – copy if the network version has changed but use the current version if it hasn’t or the network is not working.  At the risk of selling my own wares, perhaps like the archive common instrument area where we keep the system wide cycle number (O:\setcycle.cmd on the instruments)?

**Comment by ChrisM-S** [comment]
Just to clarify, lets assume control svcs requires a copy, it just does a git update, as does the archive server for its copy.  Maybe a centrally served PV AND a file distributed to the clients via the appropriate mechanism would be useful?

**Comment by FreddieAkeroyd** [comment]
control-svcs could indeed do a periodic git update and ioc restart to keep the list in sync. I'm not sure the top of the ibex client build repository is the best place though.  I don't think we need a separate network file area - the client may already cache the last PV value it read, or it could be made to do so.

**Comment by ChrisM-S** [comment]
That makes sense, the first time client runs, you would (normally) expect the network to be present to set the cache.

Just going by analogy with the instruments, as we check the individual instrument settings in/out of github, is there the concept of a COMMON instrument.  For example, for common settings like calibrations and possibly common configurations/components which would logically be checked out at the same time?

**Comment by KathrynBaker** [comment]
Nothing has been done with this, and no issues are known of
