### ISSUE TITLE
MERLIN: Fermi Chopper IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2355]
As a MERLIN instrument scientist, I want IBEX to provide a controller to manage the settings of the Fermi Chopper.  

#### Acceptance Criteria
1. The controller must accept the frequency & phase as inputs.
1. The controller must provide the frequency & phase of the Fermi Chopper as outputs.

#### Notes
1. There is a script on MERLIN which calculates the frequency & phase from the energy.  This calculation could be folded into the IOC at a later date if required by scientists.
1. We should create an Emulator for this.  See ticket https://github.com/ISISComputingGroup/IBEX/issues/2476
1. See [MERLIN Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MERLIN-Instrument-Details) for additional information.

**Comment by mattclarke** [comment]
Having spoken Rob Bewley it appears that the set_ei command differs across the instruments (MAPS, MARI, MERLIN, LET).

**Comment by FreddieAkeroyd** [comment]
Is that same algorithm, different constants, or a completely different algorithm?

**Comment by mattclarke** [comment]
Vaguely the same form but different constants and adjustments for the different hardware. It doesn't just change the fermi, it also changes the upstream disc chopper and the TCB file.

Virtual chopper axis? ;)

**Comment by Tom-Willemsen** [comment]
For reference there are a few different versions of the manual around - the latest one that I'm aware of is available here (thanks @davidkeymer for digging this out of old emails):
http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/MERLIN/Fermi%20Chopper%20Communications%20Protocol.pdf

The older version, which I had previously been looking at, is now in the MAPS area of the sharepoint: 
http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/MAPS/Fermi%20Chopper%20Communications%20Protocol.pdf

Notably the checksum algorithm has been modified (slightly) - MERLIN's version checksums the initial `#` in the response packets whereas the older (MAPS) version doesn't.

**Comment by samueljackson92** [comment]
@Tom-Willemsen I volunteer to review.

**Comment by Tom-Willemsen** [comment]
Test framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/13

IOC: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/13

EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/93

Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/23

Support module: https://github.com/ISISComputingGroup/EPICS-FZJ-fermichopper/pull/1

StreamDevice: https://github.com/ISISComputingGroup/EPICS-StreamDevice/pull/2

OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/535
