### ISSUE TITLE
Web Dashboard: Verify sensitive information is hidden

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2356]
As an ISIS user I want to be sure that my title and name are hidden on the web dashboard

**Acceptance Criteria**
1. As per the checkbox on the DAE tab, the title and usernames should be visible/hidden on the web dashboard as appropriate
1. This test is added to the system tests

**Notes**
1. This follows on from #2197
1. If this doesn't behave as expected yet, write a ticket to cover it

**Comment by rerpha** [comment]
old and new hide title/usernames based on preference set on NDX
