### ISSUE TITLE
MERLIN: Fermi Chopper - Instrument Scientist OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2358]
As a MERLIN instrument scientist, I want a protected GUI for the Fermi Chopper, so that 
1. both instruments scientists & visiting scientists can view the settings of the Fermi Chopper
1. only instruments scientists can change the settings of the Fermi Chopper,

#### Acceptance Criteria
1. The GUI must: 
   1. allow instrument scientists to view _and_ change settings
   1. allow visiting scientists to view settings, but prevent them from changing settings.
1. The GUI must display the current speed & phase of the chopper.
1. I can use the GUI to change the frequency & phase settings.
1. In response to new frequency & phase settings, 
   1. the Fermi Chopper controller changes the frequency & phase of the Fermi Chopper
   1. the GUI is updated to reflect the new energy, frequency, speed & phase settings.
1. In response to new frequency & phase settings, 
   1. the Fermi Chopper controller changes the frequency & phase of the Fermi Chopper
   1. the GUI is updated to reflect the new frequency & phase settings.

#### Notes
1. Password protecting the OPI is an acceptable way of preventing visiting scientists for changing the chopper settings.
1. See [MERLIN Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MERLIN-Instrument-Details) for additional information.

**Comment by Tom-Willemsen** [comment]
Basic information on how to set up access security ("manager mode") on the IOC is here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-access-security

**Comment by Tom-Willemsen** [comment]
PR linked in ticket 2355

**Comment by kjwoodsISIS** [comment]
Scientists have confirmed that there is no need to add a label about the Fermi Chopper Lift to the Fermi Chopper OPI.
> From: Keymer, David (STFC,RAL,ISIS) 
> Sent: 03 August 2017 11:39
> To: Woods, Kevin (Tessella,RAL,ISIS); Willemsen, Thomas (Tessella,RAL,ISIS)
> Subject: MERLIN Fermi Chopper and Lift - labelling
> 
> Hello Both
> 
> I've just had a quick word with Helen who would rather not have a label on the chopper OPI to remind users about the lift.
> She said that this is something that only the instruments scientists would get involved in and didn't want to give the 
> users too much information!
