### ISSUE TITLE
MERLIN: T0 Chopper - Instrument Scientist OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2361]
As a MERLIN instrument scientist, I want a protected GUI for the T0 Chopper, so that I can change the settings of the T0 Chopper, but visiting scientists cannot do so.  

#### Acceptance Criteria
1. The GUI must protect the current T0 chopper settings from change by visiting scientists.
1. The GUI must display the current T0 chopper settings.
1. I can use the GUI to change the current T0 chopper settings.

#### Notes
1. Password protecting the OPI is an acceptable way of preventing visiting scientists for changing the chopper settings.
1. See [MERLIN Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MERLIN-Instrument-Details) for additional information.

**Comment by Tom-Willemsen** [comment]
I think this also fixes #2360 , reviewer please check if you agree and if so also close that issue.
