### ISSUE TITLE
EMMA: Fermi Chopper Lift IOC and OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2365]
As scientist/technician using EMMA, I want IBEX to provide a controller and GUI to manage the lifting of the Fermi Chopper in/out of the beam, so that I can only move the Fermi Chopper when it is in the right state to do so.  

#### Acceptance Criteria
1. The GUI reports the current status of the Fermi Chopper Lift.  The GUI should display one of the following states:
   1. Parked, out-of-beam (i.e chopper lift is in a raised position; the chopper is now positioned above the beam)
   1. Lift is in operation (i.e. chopper is being moved - raised or lowered)
   1. Clamped, in-beam (i.e. lift is in a lowered position and clamped in place; the chopper is now positioned in the beam, ready for use)
1. The GUI must include a warning statement to make it clear to the user that he/she should not attempt to move (lift) the Fermi Chopper when it is spinning.
1. I can use the GUI to request that:
   1. the Fermi Chopper be lowered into the beam (if it is not already in that position)
   1. the Fermi Chopper be raised out of the beam (if it is not already in that position)
1. The GUI _could_ report the status of the Fermi Chopper (i.e. spinning/not-spinning or in-use/not-in-use).
1. The GUI should not report the status of the Fermi Chopper Lift interlock (controls team policy).
1. I can **not** operate the Fermi Chopper Lift via the motor GUI (accessible via the Table of Motors)

#### Notes
1. The Fermi Chopper Lift must not be operated when Fermi Chopper is spinning.
   1. It must not be possible to spin the Fermi Chopper when it is out-of-beam (i.e. the only position in which the Fermi Chopper can be operated is when the lift is in the lowered position and is clamped).
   1. The IOC is not required to implement an interlock system - there is a hardware interlock to prevent the user from operating the lift when the Fermi Chopper is spinning.
   1. The hardware interlock system is implemented in the Galil controller (via a Galil program described in the [EMMA chopper lifter - Handover document](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMMA/EMMA%20chopper%20lifter%20-%20Handover.docx)).
   1. The IOC should pass requests to raise/lower the Fermi Chopper to the Galil program.  Check the current Fermi Chopper Lift VI to see how this is done.
1. Apparently, the motor that drives the lift does not have an encoder, so there is no way to absolutely determine the position of the lift, until it encounters one of the switches (home switch and upper & lower limit switches - see Handover document).
1. See [EMMA LabVIEW GUIs](https://github.com/ISISComputingGroup/ControlsWork/issues/239) for images of the current LabVIEW GUIs.
1. See [EMMA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/EMMA-Instrument-Details) for additional information.
1. The Galil used to drive the Fermi Chopper Lift should not be accessible via the Table of Motors or should, at least, be read-only (so that the user cannot control the Fermi Chopper Lift by "the back door").

**Comment by KathrynBaker** [comment]
Notes from the VI:

Number of Nodes: 108
Cyclomatic complexity: 15
Notes: There is a written note on the front panel to make sure the fermi chopper is stopped before moving it, could be a candidate for the inhibit functionality
Controlled via a program in the Galil, 4 status values, 1 = clamped, 2 = parked, 3 = moving, 4 = error. Status is retrieved by sending “status=?” and interpreting the result for display. Position is set by executing the section of galil code, e.g. by sending “#Park” and 5 to the execute program VI, so final command sent is of the form “XQ #Park,5”
IBEX setup:
Motion set up, Adrian best placed possibly to comment
OPI is straightforward
![image](https://user-images.githubusercontent.com/10552381/31999764-65acf424-b98c-11e7-8c5e-1dec8c93a348.png)
![image](https://user-images.githubusercontent.com/10552381/31999769-69ced96e-b98c-11e7-9e49-f2b06db9b539.png)

If we include the inhibitor will take a little longer, John best placed to comment.

**Comment by kjwoodsISIS** [comment]
Regarding an inhibitor system: please see notes (ii) and (iii) above - there already appears to be a (possibly partial) hardware inhibition system.

**Comment by Tom-Willemsen** [comment]
From Jeff Sykora:

> Re chopper lifter: The idea is that no one is able to move the lifter with the chopper running. If it is available in the ToM then anyone can get in and move it. I am happy to have it password protected as you say and I would say that it is relatively critical that motion control can have access to it. They will be aware of the procedures for moving the chopper.

**Comment by Tom-Willemsen** [comment]
In terms of the IOC itself, this is done. I can't test it on the office galil because the thread won't start (maybe needs an encoder and/or limit switches?)

In terms of the access security stuff, we had a meeting and decided to:
- Put an ASG on all the motor records (which would default to "default", same as currently)
- Switch on the access security for Emma's fermi chopper lift meaning that it is controllable while the instrument is in "manager mode" only.
- For the galil, wait until #2787 is done as that ticket will make this work substantially easier.

**Comment by Tom-Willemsen** [comment]
After discussion with @John-Holt-Tessella I've created a separate ticket (#2789) for the ASG stuff and reduced this ticket's points to adjust for the split.

**Comment by AdrianPotter** [comment]
I've tested with the office Galil with a dummy program and it detects and triggers status changes as expected. It will need checking with the original program on Emma itself
