### ISSUE TITLE
EMMA: Y-Z and Rotation Stages

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2366]
As a scientist or technician using EMMA, I want to control the settings of the Y-Z table and rotation stage, so that I can position items in the neutron beam.  

#### Acceptance Criteria
1. I can use the GUI or a script to adjust the height of the Y-Z table (i.e. change the Z-axis setting).
1. I can use the GUI or a script to move the Y-Z table across the beam (i.e. change the Y-axis setting).
1. I can use the GUI or a script to rotate the object mounted on the rotation stage (i.e. change the rotation angle).
1. I can use the GUI or a script to return the settings of the Y and Z positions and the rotation angle to their home settings.
1. The GUI must report the current settings of the Y-Z table and rotation stage.
1. I can use a script to query the current settings of the Y-Z table and rotation stage.
1. I can control the Y-Z table irrespective of whether the rotation stage is mounted or not.

#### Notes
1. The positioning stages on EMMA are limited to:
   1. a Y-Z stage for moving items perpendicular to the beam (there is no X-stage for longitudinal motion parallel to the beam).
   1. a Rotation stage, for rotating items about a vertical axis, perpendicular to the beam
1. The Y-Z table and rotation stage are both controlled by a Galil.
1. The rotation stage, when in use, is mounted on the Y-Z table.  The rotation stage is not always used with the Y-Z table.  It can be removed, when not in use.
1. In SECI, EMMA has separate GUIs for the Y-Z table and rotation stage.  There is no good reason for this (except, possibly, the fact that the rotation stage can be removed from the Y-Z table).  In fact, it would be more convenient for these two GUIs to be combined into a single GUI.
1. See [EMMA LabVIEW GUIs](https://github.com/ISISComputingGroup/ControlsWork/issues/239) for images of the current LabVIEW GUIs.
   1. What does the Define button do on the LabVIEW Rotation GUI?
1. See [EMMA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/EMMA-Instrument-Details) for additional information.

**Comment by John-Holt-Tessella** [comment]
Maybe get generic OPI done (see ticket <insert ticket number here>)

**Comment by kjwoodsISIS** [comment]
Consider implementing ticket #1179 instead of this ticket.

**Comment by kjwoodsISIS** [comment]
#1197 is now implemented.  This ticket is now redundant and can be closed as WONTFIX.
