### ISSUE TITLE
Blockserver: File Watcher fails for moved files

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2367]
To reproduce:

- Start IBEX
- Go to your settings file
- Move a file/folder

In my case, when I moved `blocks.xml` from configuration `blank` to `blocks_2.xml` I get logging information of the form:

```
[Tue May 23 15:44:05 2017] MAJOR: File Watcher: Delete list contains unknown configurations
[Tue May 23 15:44:05 2017] INFO: File Watcher, loading config: Files missing in Blank (blocks.xml)
[Tue May 23 15:44:05 2017] MAJOR: File Watcher: 'NoneType' object has no attribute 'get_config_name'
```

**Comment by AdrianPotter** [comment]
I think the file watcher has been completely overhauled since this ticket was created. Is it fixed?

**Comment by ThomasLohnert** [comment]
In fact the file watcher has been removed as version control is now handled independently from file system events. Closing this issue.
