### ISSUE TITLE
IMAT: driver for GP2 camera

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2370]
This is a new imaging camera developed by a collaboration involving Oxford university and ISIS amongst others. Its backend infrastructure is in LabVIEW, but following conversations with the developer we should be able to access information via network shared variables and our NetShrVar support module. An AreaDetector top level needs to be written to provide file saving, data is currently provided as (x,y,t) events via a shared variable.

**Comment by ChrisM-S** [comment]
Hi @FreddieAkeroyd, are you planning to save these into the Nexus file on the NDX? or into a "standard" imaging file on the PXI box initially.  It would be useful for me to know whether to prepare to zip/transfer as with UCB and Messina PCs (or just wait for a nice imaging .NXS file to archive :smile:  ).  Probably not an issue for the next test, but once they put an interesting sample on which could happen anytime it will become suddenly very real.

**Comment by FreddieAkeroyd** [comment]
For this test, both I and the PXI will be saving files and then we will compare - we are not sure yet if the shared variable mechanism will work. I'm using EPICS area detector so can write nexus/HDF5 reasonable easily

**Comment by ChrisM-S** [comment]
That sounds hopeful, if the LabVIEW saved ones are different I can zip them up manually this time round.  If we do need to keep them, please could you ask them to save these on USB stick if the PXI/laptop is due to go away/off network (and we need to keep them)?

**Comment by kjwoodsISIS** [comment]
Almost done.  Just needs a few tasks to be closed off.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - what is the status of this ticket?  Are the remaining tasks (see previous comment) complete?
