### ISSUE TITLE
Fix EOL issues identified by check script 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2371]
The EPICS_repo_checks Jenkins task currently checks for EOL issues, we should fix those that are currently reported. There are quite a few reported in python files - are we worried?

**Comment by ISISBuildServer** [comment]
It doesn’t really matter but PEP 8 recommends a blank line at the end, so we should try to follow that convention.

**Comment by mattclarke** [comment]
The BlockServer has been done (hopefully).

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/124
