### ISSUE TITLE
Archiver/IMAT: Instrument archiver on IMAT has stopped archiving blocks

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2372]
On IMAT the archiver seems to have stopped logging PVs marked with archive that are not coming from the DAE. 

E.g. IN:IMAT:MOT:MTR0306.RBV
Shows as disconnected in the database and on the archive page. This seems to have happened at 2017/05/10 16:38:51 when a new config was loaded.

Try to reproduce.

NB I haven't fixed it on IMAT so you can still look at the problem there.

Not reported by scientists, Gareth found it.

**Comment by KathrynBaker** [comment]
Please note, this is limited to the INST group (the DATAWEB and BLOCKS seem to be working happily)
