### ISSUE TITLE
GUI: Eclipse-4/CSS-4 Prototype [TIMEBOX: 10d]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2376]
As a developer, I want to create a prototype IBEX GUI using Eclipse-4/CSS-4, so that I understand what it takes to build an Eclipse-4/CSS-4 application.

#### Acceptance Criteria
1. A prototype of the IBEX GUI built using Eclipse-4/CSS-4.
   1. Prototype should attempt to replicate the main features of the current IBEX GUI in Eclipse-4/CSS-4 environment.
1. Written documentation on how to build a fully-fledged IBEX GUI using Eclipse-4/CSS-4.

#### Notes
1. Consult with Diamond to learn about their experience of the process.
1. Prototype is intended to help IBEX developers understand the most effective way to build Eclipse-4/CSS-4 applications.
1. Documentation should:
   1. Set out architectural principles that IBEX GUI developers need to understand
   1. Explain how to "go with the E4/CSS4 flow" (i.e. work with E4/CSS4, rather than against it).
   1. Recommend strategies for migrating the current IBEX GUI to E4/CSS4.
      1. strategies might include using the E3/E4 compatibility layer
1. Prototype may be used to help scientists understand what a new IBEX GUI might look like and to solicit feedback.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eclipse-4-migration-notes

**Comment by kjwoodsISIS** [comment]
I have reviewed the above notes.  All looks good to me.

**Comment by AdrianPotter** [comment]
For code review:

- Make sure that you can create an Eclipse workspace containing the branch
- Make sure you can build and load the application
- Have a look at the main places the code has changed and review:
    - Plugins named `...isis.ibex.e4...`
    - `...ui.dashboard`
    - '...ui.beamstatus'

**Comment by mattclarke** [comment]
The first time you open this in eclipse you need to set the target platform.
