### ISSUE TITLE
System Testing Day [TIMEBOX: 1d]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2377]
As a developer, I want to spend a day automating as many of the manual system tests as possible, so that I can run them as part of the normal system build tests.

#### Acceptance Criteria
1. Manual system test converted to automated system tests.
1. New automated system tests incorporated into the standard system builds

#### Notes
1. Review the current manual tests to determine which ones would be most valuable to automate (i.e. automate these first).
1. Need to pick a day for this happen - sometime in SPRINT_2017_06_01.

**Comment by AdrianPotter** [comment]
All associated PRs should be merged before this is closed
