### ISSUE TITLE
GUI: Component features not added to configuration

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2380]
If you are creating/editing a configuration and add/remove a component, the changes are not propagated to the blocks/IOC/groups tab.

For instance, if I assign a component to a config containing NEW_BLOCK, then the block won't appear (albeit greyed out) in the blocks tab. If I save the config and revisit it, then it will appear.

**Comment by ThomasLohnert** [comment]
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/1357
