### ISSUE TITLE
OPI: Add possible frequencies to Choppers

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2381]
As a scientist I would like to know what frequencies are available to set the chopper at. These should be places on the OPI of MK2 and MK3 choppers. This is a quick ticket to precede #2375 is done.

Let Ian know when it is done and explain there is a fuller ticket later.

**Comment by mattclarke** [comment]
There appears to be no way of getting the valid frequencies from the Mk2. Currently, the VI shows all the possibilities, so the OPI might as well do the same.

The frequencies are: 5; 10; 12.5; 16.67; 25; 50.

**Comment by John-Holt-Tessella** [comment]
Would it be better just to have a mbbi in the IOC which has these values if they are fixed?

**Comment by mattclarke** [comment]
Way ahead of you
;)
