### ISSUE TITLE
GUI: Minor modifications to Config dialog

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2382]
Make config dialog have a minimum height which includes the add buttons on both the IOC and groups page. At the moment it is possible to reduce the height of the windows so much that the add button disappears.

Configurations – IOCs tab – Name column could be narrower to give more room for descriptions

**Comment by KathrynBaker** [comment]
I’m confused Matt, I have done these tweaks under #2259 – there is a pull request.

Regards,
Kathryn

**Comment by KathrynBaker** [comment]
I do apologise, I actually failed to put the reference in for the pull request in the ticket, or for the ticket in the pull request - comes from making those changes too late in the day. I will mark this as complete, and put the other ticket back for review.

**Comment by mattclarke** [comment]
Please link the PR to the ticket, so it is obvious for slow people like me

**Comment by KathrynBaker** [comment]
I do apologise, I just missed it along the way, links now added.
