### ISSUE TITLE
Rename jenkins builder domain account

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2384]
We seem to be having issue with the Mantiod local builder account locking out ISIS\builder. We propose renaming ISIS\Builder to ISIS\ibexbuilder

**Comment by Tom-Willemsen** [comment]
What steps need to be performed to review this ticket?

**Comment by Tom-Willemsen** [comment]
Passwords page has been updated. Can't see that Jenkins is complaining about this issue any more. I think that's sufficient to mark this as complete.
