### ISSUE TITLE
Lewis: Upgrade to latest version

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2386]
As a developer I would like to have the latest version of LeWIS available so that I have access to the latest features/bug fixes when writing emulators.

An upgrade guide to 1.1 is available here: http://lewis.readthedocs.io/en/latest/release_notes/release_1_1_0.html

**Comment by DominicOram** [comment]
Wait for the following to be merged first https://github.com/ISISComputingGroup/IBEX/issues/2465

**Comment by DominicOram** [comment]
1.2 has now been released, this has the change mentioned above. http://lewis.readthedocs.io/en/latest/release_notes/release_1_2_0.html

**Comment by davidkeymer** [comment]
Pull Requests:

https://github.com/ISISComputingGroup/genie_python/pull/117
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/55
