### ISSUE TITLE
EMMA: Create Configs and Synoptics

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2387]
As scientist or technician using EMMA, I would like a set of "starter" Configs and Synoptics, so that I can quickly start using EMMA.  

#### Acceptance Criteria
1. EMMA has a base configuration.
1. EMMA has one or more components which can be added to the base configuration.
1. EMMA has one or more Synoptics, to show what equipment is on the instrument.

#### Notes
1. EMMA currently has no configurations.  Any configurations will need to be created from scratch, in consultation with Jeff Sykora.
1. Baseline equipment on EMMA should consist of the following:
   1. T0 Chopper
   1. Fermi Chopper (and its lift)
   1. 4-blade jaw set
   1. Y-Z Table
   1. 4 monitors
   1. CAEN High-Voltage controller (for the detectors)
1. Optional equipment should consist of the following:
   1. Rotation stage
   1. Eurotherm
   1. other items may be added in due course
1. See [EMMA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/EMMA-Instrument-Details) for additional information.

**Comment by AdrianPotter** [comment]
Awaiting #2843

**Comment by AdrianPotter** [comment]
The CAEN and T0 choppers don't feature in their SECI configurations. I'll email Jeff. We need to write some Fermi Chopper setup scripts anyway

**Comment by AdrianPotter** [comment]
Chaser email sent.

**Comment by AdrianPotter** [comment]
The Fermi chopper lift is currently missing from the configuration. The other devices are manual control

**Comment by AdrianPotter** [comment]
Note that NDXEMMA-A test is using a patched version of EPICS that contains https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/9

It does not yet have a GUI containing https://github.com/ISISComputingGroup/ibex_gui/pull/617 so the Fermi Lifter OPI won't warn about not being in manager mode.

**Comment by DominicOram** [comment]
I have tested the following:
* Blocks/groups are same as SECI
* IOC macros are same as SECI equivalent
* Synoptic contains expected components
* Jaws.cmd ect. are correct

I found the following issues:
* The Jaws in the synoptic do not have the correct icon
* The galil IP should be our galil standard of 192.168.1.201

**Comment by DominicOram** [comment]
Issues have now been corrected
