### ISSUE TITLE
EMMA: Create Setup Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2388]
As scientist or technician using EMMA, I woild like a set of setup scripts, so that I can quickly put EMMA into to pre-defined states.  

#### Acceptance Criteria
1. EMMA has one or more genie_python scripts that can each be used to put the instrument into a known state.

#### Notes
1. EMMA currently has no scripts.  Any scripts will need to be created from scratch, in consultation with Jeff Sykora.
1. The purpose of the scripts is to help the scientist/technician quickly put the instrument into a known state.  The scripts can also serve as an example of how to write well-structured scripts.

**Comment by AdrianPotter** [comment]
I don't understand that EMMA has no scripts. I found a number of gcl scripts in C:\Instrument\Settings. I have migrated a reasonable cross-section of these scripts

**Comment by AdrianPotter** [comment]
@Tom-Willemsen asked whether they had any scripts. No reply so far. Chaser email going out shortly

**Comment by Tom-Willemsen** [comment]
> Hi Tom,
> 
> Sorry for not getting back to you. It must have slipped. We have scripts located on NDXEMMA-A in several locations but these are probably the important ones to migrate for now: C:\Instrument\Settings 
> 
> The other scripts we use at the moment are all small and bespoke for each measurement. It would be good to get a new script for the Fermi chopper once that is ready. I would like to scan through frequencies and phase delays and take data for each setting. Other than that, things are fairly straight forward. I can probably adapt a sample alignment procedure from IMAT or similar.
> 
> Thanks,
> Jeff

**Comment by AdrianPotter** [comment]
That's good, I've already migrated those scripts at `C:\Instrument\Settings`. Once I've set up EMMA's configs, I'll get in touch with Jeff to write a Fermi Chopper script. It will be easier if there's a dummy system we can work with that has all of the blocks already set up.

**Comment by AdrianPotter** [comment]
Waiting on #2387

**Comment by AdrianPotter** [comment]
I had a meeting with Jeff and we wrote `fermi_chopper_scan` together. He said he was pretty happy writing scripts himself and will be attending the training course.

**Comment by DominicOram** [comment]
I did the following:
* Visually compared genie python to open genie scripts. Those that have been converted look correct, others can be easily converted by instrument scientist.
* Added some more comments to aid understanding
* Ran in genie simulation mode, all worked as expected
