### ISSUE TITLE
Log/Alarm Improvements: Downgrade default IOC messages to Minor

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2389]
As a developer who supports IBEX, I want to limit the number of messages being considered in IOC Log as Major, altering the default value of IOC messages to be Minor should do this.

**Acceptance Criteria**
1. All default IOC messages only have a Minor message severity

**Comment by FreddieAkeroyd** [comment]
Error messages that do not specify a severity will now get MINOR rather than MAJOR, ones that explicitly set a level via errlogSevPrintf() will retain their severity

**Comment by FreddieAkeroyd** [comment]
To test: start up instrument before and after change, there should be less MAJOR errors!
