### ISSUE TITLE
GEM: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2395]
As an instrument scientist, I would like to migrate GEM to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on GEM
1. Configuration files matching the current SECI config files are created
1. IBEX is configured for the devices on GEM.
1. GEM scripts are converted to genie_python
1. GEM scientists are trained in how to use IBEX
1. IBEX is tested on GEM

#### Notes
1. The devices on GEM are listed on the [GEM Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/GEM-Instrument-Details) list
1. The following tickets should be implemented prior to deploying IBEX on GEM
   - [x] #2138
   - [x] #2409
   - [ ] #2798
   - [x] #2808
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for GEM.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
- [x] Check that NDXGEM has sufficient disk space to install IBEX
- [x] Check whether GEM uses 5- or 8- digit run-numbers *Uses 5 digit run numbers, needs upgrading*
   - [ ] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [ ] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXGEMTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
   - [ ] test these configurations & scripts
   - [ ] check that all the devices previously supported by SECI (on GEM) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
   - [x] demonstrate the configurations & scripts (created above) to the instrument scientists and check that they are happy with the migrated configurations & scripts

**Comment by AdrianPotter** [comment]
For script migration, EMMA were using a few they'd copied across from GEM. If they haven't diverged very much you may be able to reuse some of the code.

**Comment by AdrianPotter** [comment]
I'm doing the Sandals migration ticket at the moment so will need to email Anthony Shuttle about the private network. I'll mention GEM at the same time.

**Comment by ChrisM-S** [comment]
Anthony did the GEM  VLAN and set the switch ports for GEM back in August, we just need to patch a connection through to the local motion control switch when the motion rack is ready (as discussed a few times but a relatively trivial job for us). @DominicOram, do you know if the Galil rack is ready/testable?  Any other devices directly on private network?

**Comment by DominicOram** [comment]
I'm going down today to have a look, I don't think it is fully ready yet. In any case I was going to commission using the serial comms under SECI first so will patch the network probably some time early next year.

**Comment by Tom-Willemsen** [comment]
- Gem appears to be using 5-digit run numbers (looking at data files in `C:\data`). @FreddieAkeroyd can the ICP be updated on GEM?
- I have sent an email asking about which configurations and scripts they want migrated. No response yet.
- I've migrated their skeletal "base" config and a couple of obvious add-ons. Some of their other recently modified configs contain components we don't support (Kelvinox dilution fridge, 7.5T magnet) but we should wait until it is confirmed that these are needed before creating/prioritising tickets for those devices.

I don't think there's much more that can be done right now without knowledge of which configs and scripts they actually want migrated.

**Comment by kjwoodsISIS** [comment]
The tasks in  [https://github.com/ISISComputingGroup/ControlsWork/issues/158](https://github.com/ISISComputingGroup/ControlsWork/issues/158) are somewhat specific to SECI.  It would be better to have an similar set of instruction for IBEX (and better to have them in a Wiki, rather than an ticket).

**Comment by Tom-Willemsen** [comment]
Have sent a chaser email.

**Comment by Tom-Willemsen** [comment]
GEM scientists have confirmed that neither the Kelvinox nor the 7.5T magnet will be used (at least, not before sept 2018).

**Comment by Tom-Willemsen** [comment]
Meeting scheduled for 8th Jan to discuss what needs to be migrated with the scientists.

**Comment by Tom-Willemsen** [comment]
Configs/components to migrate immediately:
- [ ] Galil jaws
- [ ] 5 axis sample stack
- [ ] Gem furnace
- [ ] Mercury cryostat
- [ ] Sample changer
- [ ] CCR_matt
- [ ] Choppers
- [ ] sample changer_alex
- [ ] Low temperature furnace
- [ ] Furnace pressure
- [ ] 3 eurotherms
- [ ] Gem_base

Configs which will be needed eventually (but not in the immediate future)
- [ ] Kelvinox

Scripts to migrate:
- [ ] bychkov2.gcl
- [ ] UPD.gcl
- [ ] Pcheck.gcl
- [ ] DAK_ccr
- [ ] DAK_furnace
- [ ] DAK_sample changer

**Comment by kjwoodsISIS** [comment]
I am slightly confused by the reference to Kelvinox - my understanding is that Kelvinox hardware has been phased out (Triton hardware is now preferred).  I will seek confirmation.

**Comment by kjwoodsISIS** [comment]
Confirmation from Richard Down (Head of Cryogenics):
> Hi Kevin,
> 
> This is correct, as of now the Kelvinox Systems are all using Triton Gas Handling systems.
> 
> Best, Richard.

**Comment by FreddieAkeroyd** [comment]
I had a chat with Alex Hannon – his GENIE scripts are mostly for analysis of live data and should continue to work OK after moving to IBEX, there are a few separate control specific ones that can be migrated in the usual way. We did briefly discuss long term future of his quick view focus scripts, which is something for another day.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd : when the time comes, perhaps the Mantid team could help Alex develop some new "quick view focus" scripts?

**Comment by Tom-Willemsen** [comment]
To finish the migration, need:
- Mercury cryostat IOC needs to provide additional PVs https://github.com/ISISComputingGroup/IBEX/issues/2840
- Beamscraper jaws need finishing https://github.com/ISISComputingGroup/IBEX/issues/2138
- Vacuum valve status will be provided by https://github.com/ISISComputingGroup/IBEX/issues/2798
- Sample stack setup as per https://github.com/ISISComputingGroup/IBEX/issues/2853
- Galil jaws (waiting on motion control to finish commissioning) https://github.com/ISISComputingGroup/IBEX/issues/2858

**Comment by Tom-Willemsen** [comment]
The migration is done, except for the sample stack (not needed this cycle) 

This ticket can be reviewed.

**Comment by John-Holt-Tessella** [comment]
Talk to @FreddieAkeroyd about #2798 this is on the machine but needs final tidying in master. Will complete without this.
