### ISSUE TITLE
GUI: RB Number 'Search' and 'Set' inconsistent

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2396]
If one selects an RB via the 'Search' button the users box in the dashboard gets populated with the surnames of all the users except the contact (I assume this is by design).

If one then clicks 'Set' the contact's surname gets added to the dashboard.

One of these behaviours is wrong - I would assume it is the second one that is wrong.

**Comment by KathrynBaker** [comment]
Not reproducible anymore
