### ISSUE TITLE
EMMA: Fermi Chopper

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2397]
As scientist or technician using EMMA, I want a controller & GUI for the Fermi Chopper, so that I can change the settings of the Fermi Chopper.

#### Acceptance Criteria
1. The GUI must display the current speed, phase & window.
1. I can use the GUI to change the current speed, phase & window settings.
1. I can use a script to query the current speed, phase & window settings.
1. I can use a script to change the current speed, phase & window settings.

#### Notes
1. The Fermi Chopper on EMMA is controlled via an SKF MB350PC (G3) controller, which uses a Modbus over serial (RS485) communications protocol.
   1. The disk choppers on IMAT are also SKF choppers (G5 models).  It _might_ be possible to adapt the IOC created for IMAT for use on EMMA. See #886 and #1737.
   1. Until recently, LET used to use an SKF MB350PC (G3) controller.  The IOC & GUI could be based on the corresponding SECI VI.
1. See [EMMA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/EMMA-Instrument-Details) for additional information.

**Comment by kjwoodsISIS** [comment]
Note from David Keymer:
>
> In principle, a fermi and disc chopper behave in the same way – they’re still spinning lumps of metal
> in the end – so they have the same operator parameters (frequency, phase, window, etc) that we 
> would set remotely.
>
> However, it all depends on how clever the controller is as to how much logic, if any, is required in 
> the IOC/VI.  From memory, the VI for the G3 is very basic (apart from the MODBUS protocol) and 
> only reads and writes values, leaving the controller to deal with everything else (as it should do of 
> course).  So with any luck, an IOC for a G3 would also only have to have the same basic functionality.
>

**Comment by KathrynBaker** [comment]
Notes from the VI:

Assumption: This is the Mirrortron-SKF MB350PC chopper used previously on LET.

There is no logic in the VI other than the interpretation and building of command packets and responses, but this is specific.

Number of Nodes: 108
Cyclomatic complexity: 15
Screen Shot: 
![image](https://user-images.githubusercontent.com/10552381/32001770-ac92055e-b992-11e7-956c-f7a7a7388de2.png)

The nominal values are read from a file on startup, file is not human readable.
Also on startup there is some initialisation relating to the parking information.
There is a very specific command packet builder and interpreter, this will need to be reproduced.
The status displays are interpreted from a byte array.
When the values are changed they are written to the file that is loaded on startup (autosave should cover this).
There are about 30 commands programmed in the LabVIEW VI that builds the command packet.
May need to be wary of the serial connection along 485, ensuring the pin allocations and expected behaviours.
Including emulator and test suite this may be >5 points.

**Comment by kjwoodsISIS** [comment]
Check that this is the right VI - ask @David

**Comment by Tom-Willemsen** [comment]
I had a chat with @davidkeymer - Apparently Mike Brind and Paul Chorley are the people most likely to know exactly what this chopper is. I will drop them an email.

**Comment by Tom-Willemsen** [comment]
Requires #2768

**Comment by Tom-Willemsen** [comment]
#2768 is now complete and I have contacted Jeff to see if there's a convenient time to retest this against the hardware on emma.

**Comment by Tom-Willemsen** [comment]
Went down to emma this morning - basic comms appear to be working. Didn't try moving anything but the readbacks were updating with the same numbers as LabVIEW.

Device needed an extra sleep before sending a serial break - I hacked this into asyn on the beamline but it needs a sensible fix doing.

**Comment by Tom-Willemsen** [comment]
List of PRs you need to review this ticket:
EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/107
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/195
Support module: https://github.com/ISISComputingGroup/EPICS-SKFMB350/pull/1
Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/44
Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/35
GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/589
Streamdevice: https://github.com/ISISComputingGroup/EPICS-StreamDevice/pull/3
Asyn: https://github.com/ISISComputingGroup/EPICS-asyn/pull/6

Note, to talk to the real device you will need to rebuild both streamdevice and asyn with the above changes. To talk to the emulator you don't need to rebuild asyn but still need the streamdevice changes.

**Comment by John-Holt-Tessella** [comment]
Awesome to have so few problems in such a complicated IOC.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - is this ticket ready for a final review and completion? (we are about to migrate EMMA, after all).

**Comment by Tom-Willemsen** [comment]
@kjwoodsISIS yes I've done the suggested reworks, just requires review.
