### ISSUE TITLE
ENGIN-X: Jaw Sets

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2400]
As an ENGIN-X scientist, I want to adjust the settings of each of the jaw sets, so that I can control the jaw gaps.  

#### Acceptance Criteria
1. The GUI must display the current horizontal and vertical gaps of the jaws.
1. I can use a script to query the horizontal and vertical gaps of the jaws
1. I can use the GUI to independently set the horizontal and vertical gaps of the jaws.
1. I can use a script to adjust the horizontal and vertical gaps of the jaws.

#### Notes
1. ENGIN-X has three sets of coupled jaws (jaws-1 to jaws-3).
   1. all are controlled by LinMot motor controllers.
   1. the jaw blades are coupled, in the sense that the blades operate in pairs:
      1. the North-South blades operate as a single pair, driven by a single motor
      1. the East-West blades operate as a single pair, driven by a single motor
      1. in other words the jaws are driven by only two motors (as opposed to the four needed to adjust each blade independently).
   1. Therefore,
      1. moving the North-South blades allow you to adjust the vertical gap
      1. moving the East-West blades allow you to adjust the horizontal gap 
      1. it is not possible to control the position of the centre of the gap.
1. See [ENGIN-X Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/ENGIN-X-Instrument-Details) for additional information.

**Comment by DominicOram** [comment]
From examining the VI only the third jaw set is coupled (it's also non linear). Jaw set 1 and 2 are more 'traditional' sets with 1 axis per blade.

**Comment by DominicOram** [comment]
Waiting on more info about the possible replacement of the 3rd Jawset

**Comment by DominicOram** [comment]
Confirmed from instrument scientist that they regularly change the quadratics that calibrate the 3rd Jaw set. A meeting should be had with them to discuss:
* Where they want to  change it, OPI or blocks etc?
* If they also change the readback quadratic or if this should be changed automatically to make sense as the inverse.

**Comment by DominicOram** [comment]
* Instrument scientists are happy to have it in the OPI (but not too obvious so that users may change it)
* The readback should the inverse of the write (only automate this if there is time as these should be replaced soon) otherwise have the user be able to change all 4 quads
* They may put a linear equation in for calibration (if we do calculate the inverse we should account for this)

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/3

**Comment by AdrianPotter** [comment]
Cannot build. C:\Instrument\Apps\EPICS\support\motorExtensions\master\enginxJawsApp\Db is missing a makefile

**Comment by DominicOram** [comment]
Apologies, there was a typo in the .gitignore which meant I missed it. Should now build.

**Comment by samueljackson92** [comment]
@DominicOram I'm still getting the last issue. Also when I change something in the calibrate interface and swap to the main interface the set point is not updated until after the move. This looks a little weird. Should it be updated before?

**Comment by DominicOram** [comment]
Updated behaviour so that when changing calibrations the motor is not immediately moved to a new set point. However, the readback is immediately updated.

**Comment by samueljackson92** [comment]
Tested and the RBV now changes but the set points don't. OPI navigational issues are also fixed. This looks good to me.
