### ISSUE TITLE
ENGIN-X: Sample Positioning System

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2401]
As an ENGIN-X scientist, I want to adjust the settings of each of the Sample Positioning System, so that I can control the position and orientation of the sample.  

#### Acceptance Criteria
1. The GUI must display the current value of each of the following parameters:
   1. X - translation of the sample in a direction parallel to the beam (in the horizontal plane)
   1. Y - translation of the sample in a direction perpendicular to the beam (in the horizontal plane)
   1. Z - translation of the sample in a direction perpendicular to the beam (in the vertical plane)
   1. W (omega) - rotation of the sample about the vertical axis
   1. S (slit rails) - translation of slits (i.e. jaws-3) in a direction parallel to the beam (in the horizontal plane)
1. I can use a script to query current value of each of the above parameters.
1. I can use the GUI to set the value of each of the above parameters.
1. I can use a script to set the value of each of the above parameters.
1. I must be able to use the jog box to control the position of the sample independently of IBEX.
   1. Any adjustments to the above parameters made using the jog box must be reflected in IBEX.

#### Notes
1. The ENGIN-X sample positioning system is controlled by Galil controllers.
1. ENGIN-X uses a jog box for positioning samples. There is an existing Galil program (i.e. a program that gets loaded into the Galil firmware) for communicating with the jog box.  The IOC need to be configured to load this program into the Galil controller.
1. The Cybaman positioning system is outside the scope of this ticket.
1. See [ENGIN-X Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/ENGIN-X-Instrument-Details) for additional information.

**Comment by Tom-Willemsen** [comment]
Following a long discussion with @John-Holt-Tessella @KathrynBaker and @FreddieAkeroyd we have decided that the best approach to this ticket is to LvDCOM the VI in the short term as there are several (potentially safety-related) complexities to be solved before this can be done in EPICS.

**Comment by John-Holt-Tessella** [comment]
Use the vi "Galil Remote.vi".
Controls to have on OPI: 

1. Pendant active
1. Light Curtain Active
1. Emergency Stop Active
1. Stop all button
1. In Motion, Position, and SetPoint for x, y, z, omega and S. When set point is set the go button is pressed (lvdcom lets you do this).

**Comment by Tom-Willemsen** [comment]
Ensure you manually enable controls on the "Galil Remote" vi when testing, otherwise it will appear not to work.

**Comment by John-Holt-Tessella** [comment]
Please:

- [ ] Create REC Sim
- [ ] Create rec sim test (just to make sure IOC works)
- [ ] add alarms on at least one PV so we know it is connected

**Comment by Tom-Willemsen** [comment]
Test framework PR at https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/18

Have implemented recsim and alarms
