### ISSUE TITLE
Update CaChannel to 3.0.0?

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2403]
There is a bug in CaChannel 2.3 and 2.4 where it complains if one tries to write an empty string to a char waveform.
This appears to be fixed in 3.0.0, but as 3.0.0 is the first version of a major version change there are risks associated with upgrading.

Options:
* don't worry about it for now - the bug only shows up if the user sets the title to "" or similar
* Thoroughly test CaChannel 3.0.0 then migrate

Either way we probably need to have system tests in place that thoroughly exercise CaChannel, so that we can have confidence that updating CaChannel does not break anything.

**Comment by John-Holt-Tessella** [comment]
Are there any big breaking changes in the upgrade?

I think we should upgrade, in general it is a good idea.

**Comment by mattclarke** [comment]
I'd rather hold off discussion until the planning meeting please.

With that in mind, here is a link to the change-log:

https://cachannel.readthedocs.io/en/latest/changes.html
