### ISSUE TITLE
HRPD: Test updated sample changer

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2404]
The rotating sample changer was updated during cycle after the last release. See ticket #2241. Please coordinate with Dominic Fortes to check that the updated sample changer meets his requirements. This may be delayed if HRPD is still running SECI owing to their DAE issues

**Comment by AdrianPotter** [comment]
Emailed Dominic to find a good time to go down and test it

**Comment by AdrianPotter** [comment]
Meeting with Dominic on Monday

**Comment by AdrianPotter** [comment]
We visited HRPD today and successfully moved the sample changer. Behaviour was as expected. There was an issue with the COM ports which is covered in ticket #2516

**Comment by DominicOram** [comment]
Can confirm that the sample changer worked as expected and that the appropriate configuration blocks were changed
