### ISSUE TITLE
IOC: Chopper frequency test

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2405]
Check that setting the frequency in the chopper to 16.67 that this value gets set in chopper (i.e. electronics accepts value). Ian thought that he tried this value.

**Comment by John-Holt-Tessella** [comment]
Check that setting the frequency in the chopper to 16.67 that this value gets set in chopper (i.e. electronics accepts value). Ian thought that he tried this value.

**Comment by John-Holt-Tessella** [comment]
Email sent to Ian to ask him to test it.
>Hi Ian,
>
>When you start testing your choppers this cycle could you check to see if you can set the >frequency to 16.67 using the OPI. This should be fixed now but we would like to confirm that >it works on the real thing.
>
>Also did you know that there is now a single chopper OPI if you wanted to change the target >for your 6m chopper and 10m Chopper on the TLCCR_Std synoptic so they only show one >chopper. The targets would need to be changed to the below with NUMBER set to CH1 or CH2 >depending on the chopper.

**Comment by KathrynBaker** [comment]
This has either been tested and has been adapted to or resolved in the last 7 years. Closing.
