### ISSUE TITLE
GEM: Oscillating radial collimator IOC / OPI / Emulator

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2409]
GEM will want to use an oscillating radial collimator when they migrate to IBEX in September 2017.

Underneath, the collimator is controlled by a McLennan motor controller. However, we only "talk" to a collimator via another box, which is an in-house design that accepts a set of serial commands and allows control of the oscillating radial collimator motor itself. We never talk directly to the McLennan itself.

An IOC, OPI and emulator need to be written for this device. It should just be a standard stream device, as it's command set is sufficiently abstracted from a motor that it can't be treated as a motor under IBEX.

There is an existing LabVIEW driver for this device, which will need to be reverse-engineered to extract it's command set.

Notes:
- The ORC is permanently on the GEM beamline.
- It would be possible to damage the mechanism if e.g. it is started when it is in the wrong state.

**Comment by KathrynBaker** [comment]
There is now a copy of some of the original documentation available in http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FGEM%2FORC&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence

**Comment by kjwoodsISIS** [comment]
What does the current UI look like?  Can we get a screenshot of the VI?

**Comment by Tom-Willemsen** [comment]
The following VI is used in Gem's SECI config:

![image](https://user-images.githubusercontent.com/24375813/27340674-fdf9e192-55d2-11e7-8a5f-b38869802b92.png)

**Comment by KathrynBaker** [comment]
In addition to the screenshot above here are some complexity notes about the GEM ORC:

Notes from the VI:
Number of Nodes: 427
Cyclomatic complexity: 28

Comms are via a standard serial comms block, so this should be an ASYN driver.
Some of the responses require subsetting a longer string.
There is an extra logfile being kept with records of the count, ORCNUM.txt. During startup this file is copied to the logs directory, it is updated with new values periodically.
There are a set of default values kept in a global VI.
There are about 10 commands, most are straightforward enough, and generally, a success has a response of “OK\r\n”.
There is one command (rq) which returns a large number of values within a string which would need to be decoded.
There are some simple maths related to the Utility Ratio, Period and Frequency.
There is some simple logic which disables certain controls when it is oscillating.
There is some logic that warns when the number of cycles is greater than the optional initialisation time.
Once the automatic initialise total has been reached, send this as an update, stop the ORC, wait 1 second at a time until the returned status is “OK” in response to a stop command, wait 30 seconds, wait 1 second at a time until the returned status is “OK” in response to an initialisation command, there's a little logic here to wait for the initialisation to complete, restart oscillation if it was oscillating beforehand, wait for 5 seconds.

**Comment by AdrianPotter** [comment]
- [ ] The new IOC script generator doesn't seem to put sufficient dependencies in the build.mak file for asy support. Please fix that as part of this ticket.
