### ISSUE TITLE
Update EPICS base to 3.15.5

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2410]
Update underlying EPICS base code from 3.14.12.6 to 3.15.5

To test: build your instrument with the new EPICS base and check that it starts up and expected things still work. 

I had to update my version of strawberry perl as it kept crashing during build, I was on quite an old version though

**Comment by DominicOram** [comment]
As part of review for this ticket please confirm if https://github.com/ISISComputingGroup/IBEX/issues/917 is still an issue.

**Comment by FreddieAkeroyd** [comment]
Good spot - the check I added to 3.14 I merged into the wrong place for 3.15, now moved and should work as before

**Comment by KathrynBaker** [comment]
I have checked for the #917 error, and could not currently reproduce on my system, or on demo, so that was probably fixed by #2411 

That change has meant that the tests ran without any warning dialogues.
