### ISSUE TITLE
VISAdrv: add additional timeout and termination options

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2416]
Using this for GPIB is showing occasional "bus errors", these seem to be related to read timeouts during the way that reading is done. Due to the way stream device does reading and handles termination, the best approach is to "read 1 character with timeout" followed by "read many with no timeout", but the "no timeout" causes issues on GPIB. This ticket will allow it to be configured and also an optional termination character to be specified, this read terminator will not change any processing from the stream device/asyn end and is really just handed to the VISA layer as a hint to terminate a read early for the upper layers

**Comment by Tom-Willemsen** [comment]
Moving back into "in progress" as this work is still ongoing.
