### ISSUE TITLE
FileWatcher: Should error elegantly/noticeably if an expected directory is missing

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2417]
If the configs and git checkouts are out of date, and folders are missing on upgrade/new installation with old setup, the file watcher errors in a very opaque manner, we should probably capture the error, or at least provide a useful message.

To reproduce - convince your installation not to have, for example, config/machine_name/Python. Your blockserver will not start, and at present the error displayed is as follows:
`MAJOR: Error executing write queue command initialise_configserver for state INITIALISING: `

**Comment by FreddieAkeroyd** [comment]
Suggestion is to create this in config_env.bat if it doesn't exist - we already create a few other directories here.

**Comment by KathrynBaker** [comment]
This is now rather old, reopen if this would still be a good to enact.
