### ISSUE TITLE
GUI: Device screens are not saved to server

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2420]
Discovered as part of the hackathon:

https://github.com/ISISComputingGroup/ibex_system_tests/pull/61

- Add a device screen
- Choose to save it on the server
- Restart Ibex
- The device screen is no longer available

**Once this is fixed, please add the test `OnlyServerDeviceScreensArePreservedOnRestart.test` to `AllTests.suite`**

**Comment by DominicOram** [comment]
Merged, it looks like the referenced test has already been included in AllTests is that correct?
