### ISSUE TITLE
Run control is not settable from client 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2421]
Discovered during system testing https://github.com/ISISComputingGroup/ibex_system_tests/pull/59 the run control windows is unable to set all values for run control e.g. it can set low limit but not high limit. The system test checking this has been merged and so is currently failing.

**Comment by DominicOram** [comment]
PR at https://github.com/ISISComputingGroup/ibex_gui/pull/527

**Comment by AdrianPotter** [comment]
System test "RestoreConfigurationValues" is still failing. I'm going to clean out the Jenkins workspace and if it fails on the next run then I'm going to set this to rework
