### ISSUE TITLE
Place Jenkins configuration under version control

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2424]
If for some reason the Jenkins build configuration was lost irrecoverably then it'd be time-consuming to get it set up again. We should put the configuration settings and build information under version control so it'd be easy to restore in the case of critical failure

**Comment by mattclarke** [comment]
The ESS have been using Jenkins pipelines for their builds.
https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin

What they have done is to include the configuration file(s) in the same repository as the code and the Jenkins server picks up the build configuration automatically from that file. I think this is quite elegant.

Here is an example Matt Jones put together:
https://github.com/ess-dmsc/python-nexus-utilities

**Comment by mattclarke** [comment]
You might be able to access this:

https://jenkins.esss.dk/dm/view/ess-dmsc%20master/job/ess-dmsc/job/ad-kafka-interface/job/master/

**Comment by mattclarke** [comment]
I have done this for genie_python and IBEX GUI, I have created a ticket for doing the EPICS part.
https://github.com/ISISComputingGroup/IBEX/issues/2504

**Comment by FreddieAkeroyd** [comment]
Looks nice
