### ISSUE TITLE
Deploy: Create a VHD image for Ibex

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2426]
**Do #2425 first**

As a developer, I would like a standalone VHD containing Ibex that can be mapped to instrument machines. This will make it easier to deploy new releases.

Based on these discussions:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Plan-how-to-deploy-automatically-on-30-instruments

Acceptance criteria:

- A VHD image exists containing the latest version of Ibex (EPICS, gui, genie_python, EPICS_UTILS, MySql8)
- The VHD can be mapped onto a machine and symbolic links used to point C:\Instrument\Apps\* to the expected locations
- The VHD image can be updated
- The updated image can be pushed to systems using it
- The instructions for doing all of that are accessible and can be followed by the development team

**Comment by John-Holt-Tessella** [comment]
Removed requirement for #2425

**Comment by John-Holt-Tessella** [comment]
The vhds is in `Kits$\CompGroup\chris` called apps.vhdx

**Comment by John-Holt-Tessella** [comment]
What to do about

```
REM create a default ipython_config
cd /D %PYDIR%
set "PATH=%PYDIR%;%PYDIR%\DLLs;%PATH%"
set "PYTHONHOME=%PYDIR%"
%PYDIR%\python.exe Scripts\ipython.exe profile create
if %errorlevel% neq 0 (
    echo "ERROR: Creating profile %errorlevel%"
	exit /B %errorlevel%
```

**Comment by Alistair-McGann-Tessella** [comment]
I have had a look at the contents of the VHD, it has a build of epics as well as python and mysql as required
