### ISSUE TITLE
Deploy: Create an Ibex system image

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2427]
As a developer, I would like there to be a system image for instrument machines to make it easier to maintain systems. This is based on the discussion here:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Plan-how-to-deploy-automatically-on-30-instruments

The image will be split into a number of components.

- A read-only VM containing the OS and any software required by the instrument
- Several read-write VHDs which are symbolically linked to the appropriate location
    - A data drive containing logs
    - A system settings drive containing Ibex configurations (I'm suggesting this be separate from the data drive but that's not essential)
    - An Ibex program drive as discussed in #2425

A deployment process for creating, updating and applying the image should be contained in the wiki

Should contain:

1. OS (Windows 7)
1. Java 8 (latest)
1. NPort Adminstartor
1. Git
1. Labview 2010
1. MySql 5.7.18
1. Notepad++ (latest)

**Comment by John-Holt-Tessella** [comment]
removed requirement on #2426

**Comment by John-Holt-Tessella** [comment]
NB The windows 7 end of support in Jan 2020.

**Comment by KathrynBaker** [comment]
This has been well and truly superseded by other things
