### ISSUE TITLE
Deploy: Test Ibex system image on ZOOM

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2428]
As a developer, I would like to check that the Ibex system image works and can be readily updated on a real instrument. As ZOOM is currently being commissioned and is Ibex-only, it is the ideal candidate.

Follow the deployment process created in ticket #2427 and make sure it works for NDXZOOM. Any changes need to be recorded in the wiki

**Requires tickets**

 - [ ] #2427 System VHD
 - [ ] #2493 Setting VHD
 - [ ] A data VHD (I think this is done hence no ticket)
 - [ ] #2426 Ibex VHD

**Comment by AdrianPotter** [comment]
As per Kathryn's suggestion, once confirmed on ZOOM, we might also consider using the setup on MUONFE and RIKENFE too since they are also Ibex-only.

**Comment by John-Holt-Tessella** [comment]
NB We do not need lab view modules for ZOOM. We will "Hot fix this to allow us to do commissioning". However if it is easy lets make this an extra VHD mounted at "c:\labview modules"

**Comment by ChrisM-S** [comment]
At the moment, it seems sensible to modify this ticket in favour of #2555 which is the RIKENFE control VM mentioned above and is more urgent (as there is no pre-existing VM).  The basic layout of the disks in the new system (and on IBEX test systems) is as below.  The targets for the tickets mentioned above
 #2427 System VHD, #2493 Setting VHD, #2426 Ibex VHD can be seen to match the volumes on the two disks deployed below.

The volumes below and VHDs mentioned above are essentially interchangeable from the point of the user and are hidden by links in the `C:\instrument` folder.  If we wished to build the machine with a "DISK 2" which contained the volume with the "appsreadonly" folders, we could then copy a new IBEX release disk and connect this  back to the VM to install IBEX.

For the moment, the objective should probably be to test replacing "DISK 0" at the next shutdown to see if the upgrades to the Windows system and applications (the "platform") can be done smoothly.  The platform image will require automatic installation of Notepad++, MOXA software (and maybe VNC) to be inline with the basic requirements in "Create an Ibex system image" #2427.  LabVIEW 2010 is not a requirement on NDXRIKENFE (although a 32-bit LabVIEW is installed by default which could be used for testing against developing EPICS functionality).

![instrumentdiskpartitions](https://user-images.githubusercontent.com/3035405/29674079-ff217d8e-88e8-11e7-9fc5-86da296951ef.png)

**Comment by KathrynBaker** [comment]
Superseded
