### ISSUE TITLE
Deploy: Automate Apps installation

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2430]
Based on the workflow in:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC

As a developer, I would like for the deployment process on hybrid SECI-IBEX machines to be as automated as possible.

This ticket is to automate as much as possible the Preparatory Steps on the link above:

- [x] Install EPICS
- [ ] Config_mysql if necessary (data MUST be backed up)
- [ ] Upgrade MySQL?
- [x] Install LabView Modules
- [ ] Add instrument to list of instruments
- [x] Install the client, genie_python and EPICS_Utils
- [ ] Create a shortcut?
- [ ] Pin to taskbar?
 
Make sure that the deployment instructions are updated appropriately:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC

**Comment by John-Holt-Tessella** [comment]
How much of this is done?

**Comment by DominicOram** [comment]
Items not ticked above are only part automated. They are in the script but ask the user to do manual steps.

**Comment by Tom-Willemsen** [comment]
These things are done in deploy script
