### ISSUE TITLE
Deploy: Automate post-installation steps

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2431]
Based on the workflow in:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC

As a developer, I would like for the deployment process on hybrid SECI-IBEX machines to be as automated as possible.

This ticket is to automate as much as possible any remaining steps following the installation of Ibex. For example, but not limited to:

- Check Java auto update is disabled
- Update configurations to the latest version (see `C:\Instrument\Apps\EPICS\Misc\upgrade\master`)

- Check for Java
- Download and install if no java
- Stop the server
- Back up old directories
- Install git if not installed
- Create necessary directories
- Install/update calibrations
- Install MySQL? It may not be possible to automate this step

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/10
