### ISSUE TITLE
Deploy: Unify the automated deployment workflow

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2432]
Based on the workflow in:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC

As a developer, I would like for the deployment process on hybrid SECI-IBEX machines to be as automated as possible.

This ticket should involve bringing together the work from tickets #2431, #2430 and #2429, for example into a single script. The steps in the workflow above should now be as automated as far as possible. As part of this ticket, also review the workflow above and add in any remaining steps that might be automated.

**Comment by KathrynBaker** [comment]
All instruments have been using a hybrid system for a while, and most instruments are now migrated, this will cease to be an issue before it will be considered
