### ISSUE TITLE
IMAT: Smaller motion increments on BKHOFF

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2434]
As an IMAT instrument scientists, I would like to be able to move the BKHOFF motor in units smaller than 1mm/1degree so I can have finer control when running an experiment.

The BKHOFF controller can currently only move the motor in increments of 1 unit where a unit is a mm or a degree, although the motor itself is capable of moving in smaller units. IMAT would like finer control than is currently available.

This may require changes to the ESS controller. Contact Steve Cox to see if they can implement it or we'll have to change our own version.

Let Winfried, Genevieve and Tino on IMAT know when this is done

**Comment by AdrianPotter** [comment]
@FreddieAkeroyd, can one of us get in touch with Steve Cox about this or would you be better placed?

**Comment by FreddieAkeroyd** [comment]
I sent him a note asking if he can do something his side, otherwise I can work around it our side

**Comment by FreddieAkeroyd** [comment]
Steve Cox has been busy with motion control contract work, we've briefly discussed this but he hasn't got time to look at it at the moment

**Comment by kjwoodsISIS** [comment]
So, should we implement our own workaround or wait for Steve Cox?

**Comment by GDH-ISIS** [comment]
This has been going on for a very, very long time. Do we have a work around?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd 's comment of 18th Sept implies that there is a workaround.  My question is "should we proceed to implement that workaround, irrespective of what Steve Cox might be able to do at some point in the future?"

**Comment by FreddieAkeroyd** [comment]
IMAT is not running until February, so I don't think there is any need to rush things. I can workaround it by creating a "fake" resolution and then hacking the ESS driver to remove it, the cleaner solution requires input from Steve Cox to change the resolution on the Beckhoff (or provide an alternative input sequence).

**Comment by FreddieAkeroyd** [comment]
Having talked to Torsten @ ESS they are using the next generation motor record with their Beckhoff to set non-integer position, suggest we give this a go

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - so, should we close this ticket and create a new one to use the next generation motor record?  What is required to use the next generation motor record?  a new version of EPICS?

**Comment by kjwoodsISIS** [comment]
There is nothing impeding this ticket, other than planning what needs to be done and scheduling the work.  So, moving this ticket to "awaiting".
