### ISSUE TITLE
IMAT: Sample stack OPI

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2435]
As an IMAT instrument scientist, I would like an OPI for the sample stack that reflects the actual axis configuration so that it's easier to see what I'm doing when I run an experiment.

Currently IMAT use Larmor's sample stack OPI. This works as a solution because each has 7 axes. However, the configuration of axes is different on IMAT so it's rather confusing using this particular OPI.

Please could we create an OPI for IMAT's sample stack similar to the Alf Goniometer where we have a labelled picture of the stack with axes marked, with the motor controls beside. The motor controls should be grouped into related axes.

The axes are: X, Y, Z, "Large rotation", theta, phi, psi. Please talk with Winfried before doing this ticket to nail down exactly what layout they'd like.

Consider whether the solution for a sample stack can be made generic so that the names, motors, number of motors and image can be configured. This will avoid having custom sample stacks for lots of instruments.

See whether Larmor would like to replace their current sample stack solution with the new one

**Comment by KathrynBaker** [comment]
Sounds like #1197 to me

**Comment by Tom-Willemsen** [comment]
#1197 complete, closing this.

**Comment by kjwoodsISIS** [comment]
#1197 implements the requirements of this ticket.  So close with status of WONTFIX.
