### ISSUE TITLE
Larmor: Write emulator, IOC and OPI for new beamstop

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2437]
As a user of LARMOR I would like to be able to remotely control the new beamstop.

The beamstop sits on an arm that is controlled by two different Galil axes.

![image](https://user-images.githubusercontent.com/10086797/27237547-6089f442-52c1-11e7-853d-0a0118a816ba.png)

The user will want to input an x and y for the beamstop (most likely relative to the current x and y). The IOC will have to translate this into w and theta for the actual motor movement. Soft limits on the motors will also have to be converted in some way.

Phil Saunderson knows the details of this, he is also keen to learn how the software will be written, a meeting will be organised to discuss details.

**Comment by AdrianPotter** [comment]
`xyBeamstopApp/Db` needs a `Makefile`

**Comment by samueljackson92** [comment]
@AdrianPotter Done. The `.gitignore` on this repo is wrong, but @DominicOram has already fixed it in another PR. So for now I've just force added the file.

**Comment by AdrianPotter** [comment]
3/5 PRs approved. Please just check:

- [ ] Directory structure in motorExtensions
- [ ] Switching off the MSI in EPICS

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/534
