### ISSUE TITLE
ENGIN-X: Stress Rig Graphs

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2439]
As an ENGIN-X scientist, I want to display the following types of graph in the Stress-Rig OPI:
1. Position as a function of time
1. Stress as a function of time
1. Strain as a function of time
1. Any pair of (position, stress, strain) as (X, Y) pairs
The starting point (in time) need only be the point at which I open the OPI.

#### Acceptance Criteria
1. I can view a plot of position (vertical axis) v time (horizontal axis)
1. I can view a plot of stress (vertical axis) v time (horizontal axis)
1. I can view a plot of strain (vertical axis) v time (horizontal axis)
1. I can view a plot of  any one of (position, stress, strain) (vertical axis) v and one of (position, stress, strain) (horizontal axis)
   * for example: stress v position or strain v stress
   * note: choosing the same variable for both axes (e.g. stress v stress) is pointless and should not be allowed
1. The starting point for the grpahs are:
    1. vs time graphs: 1hr previous to opi open time
    1. stress vs strain should be data collected from the point at which the axes are set.

**Comment by Tom-Willemsen** [comment]
Ron/Helen (Polaris) asked in their sprint demo about displaying historical eurotherm data, so please inform them when this ticket is complete.

**Comment by kjwoodsISIS** [comment]
What sort of display/plot of historical eurotherm data do Ron & Helen want?
This ticket is all about plotting PV_Y as a function of PV_X.  There is no need for us to create something that plots a PV as a function of time, because the Log plotter already does that.
If Ron & Helen want to display temperature as a function of time, then they can use the Log plotter.
So what variables do Ron & Helen want on the X and Y axes?

**Comment by DominicOram** [comment]
This is definitely possible using an OPI's XY Graph:
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56cf00ca60b3850e008f1775/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f52876d7e62bed112a535c5d4cad42585f43f8fcdf29f0a42062c80d55b98e30063e937f03a6aa8019b500be29834a83b6ba8b44c6ec3b37aa.JPG)

I couldn't find any way of doing it in the data browser

**Comment by ChrisM-S** [comment]
That’s a bit of a lame 2-d plot though, see
http://www.wolframalpha.com/input/?i=albert+einstein+curve
☺

**Comment by kjwoodsISIS** [comment]
@Dom: that sounds promising.  Does the OPI X-Y graph support logarithmic scales?  Does it keep updating itself as more PV data is accumulated? (I assume, from your example above that it does).

**Comment by DominicOram** [comment]
Yes, yes and no. If we were going to add this into genie python I guess we would use matplotlib instead.

**Comment by kjwoodsISIS** [comment]
OK, that's great.  So we can create a generic OPI for plotting X-Y graphs - all the user needs to do is say which PVs (or blocks) he wishes to assign to the axes.

**Comment by DominicOram** [comment]
Maybe, but it wouldn't show historic data. Maybe we could create a genie command for doing the same with historic data.

**Comment by John-Holt-Tessella** [comment]
To make it show historic data we _just_ pull the data out of the archive and create them as PVs.

**Comment by John-Holt-Tessella** [comment]
Tech Talk answers:

On 07/04/2017 04:01 PM, John.Holt@tessella.com wrote:
> Hi,
> 
> Is there a way in CSS of plotting data from the archive so that you can
> plot one PV against another; thus forming an X-Y Plot?

Yes, though it's bare bones and well hidden in a context sub-menu.

In the Data Browser prospective.  In the Properties view.  In the Traces
tab.  Right click on a trace and look for "Export Samples", then "Post
Analyzer".  You'll have to export both of the traces you want to compare.

> If so is there a way of embedding this into an OPI?

Not that I'm aware of.

> We have a stress rig which measures stress and strain; these are
> archived as PVs in our archive engine. We would like to recover these
> values out of the archive and plot one against another for a period of
> time. Is this something that has been done as part of CSS or a BOY OPI?
> We have done a similar thing for just Y vs time plots using the CSS data
> browser (although not in a BOY OPI) and we were wondering whether there
> is an extension to allow this form of plotting too.

Depending on how this plot will be used, you might be better off trying
to do this with a script instead of data browser GUI.  Making a
correlation plot from traces with different time bases isn't trivial,
and there are multiple ways to do it.

**Comment by John-Holt-Tessella** [comment]
Chatting we Joe he said:

* Can graphs be longer (size)
* No history for this cycle will be just good enough
* They need at some point to view up to 6hrs of data
* Stress vs Strain vs Position can be in a different view
* Graphs must stay up to date

**Comment by kjwoodsISIS** [comment]
What does "Can graphs be longer (size)" mean?  Larger in size or more data points?

**Comment by kjwoodsISIS** [comment]
It is not possible to implement the full functionality envisaged in this ticket ina a single sprint.  The scope of this ticket has, therefore, been revised (see above).  This comment records the original scope (for future reference).

_Title: X-Y Graphs
As a scientist, I want to display graphs of one PV plotted against second PV, so that I can see how one variable varies w.r.t. another.  

#### Acceptance Criteria
1. I can select any PV to be the X-axis of the graph
1. I can select any PV to be the Y-axis of the graph
1. The system plots Y against X and updates the graph periodically
1. I can save the (X, Y) pairs to a CSV file.
1. I can copy the graph to the clipboard as a .PNG image.

#### Notes
1. Initially, at least, this feature is intended to support the display of graphs on ENGIN-X (ie.e. user can plot any 2 of stress/strain/position ).
1. It is quite possible that the selected PVs are sampled at different times and at different rates.
   1. If this is the case, the Y variable will need to be re-sampled at the times/frequency of the X variable.
   1. Linear interpolation is acceptable for re-sampling the variables (because points on the corresponding PV strip-charts are joined by straight lines anyway).
   1. Initially, at least, it might be acceptable to limit the graphs to variables that are sampled at the same times and rates (meaning no need to re-sample).
   1. Note: In ENGIN-X, the stress/strain/position are sampled at the same times and rates.
1. Because the PV history grows over time, the X-Y graph needs to be refreshed periodically.  There is no point refreshing the graph more frequently than the rate at which the PVs are updated.  Also, as the PV history grows the number of data points will grow, which could eventually impact performance.  We need to be aware of this fact.  It might be worth considering whether the number of points could be "pruned" (e.g. beyond a certain number of points, discard every other point)._

**Comment by John-Holt-Tessella** [comment]
Waiting for help with P2
