### ISSUE TITLE
Eurotherm setpoint graphs

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2440]
Raised by Ron/Helen (Polaris)

The eurotherm OPI graphs do not act how the scientists expect. They expect the set point graph to constantly plot the current set point, but currently it only plots on change.

The difference is illustrated below (please excuse my lack of art skills):

![eurotherm_sp_graphs](https://user-images.githubusercontent.com/24375813/27281455-d7dad59c-54e3-11e7-8c3b-237303d01cfc.png)
(Setpoint in Green, actual temperature in red)

The top "graph" shows what the scientists would expect/like to see. The bottom graph shows what they currently have. I think this can be achieved by forcing the setpoint PV to update e.g. once a second, rather than only updating on change.

**Comment by FreddieAkeroyd** [comment]
When you say force the setpoint PV to update, are you referring to the graph rather than the DB record? We've had something like this before and I think the solution was to attach the graph trigger to the IOC heartbeat, which is once a second. However could you use the current value as a trigger?

**Comment by ChrisM-S** [comment]
What would the scientists expect to see for this in #2438 (plotting PVs from the archive)?  It might be that we would still need to archive repeated (same) values of a PV?  Only commenting on this because the two things are on my email at the same time!

**Comment by FreddieAkeroyd** [comment]
Ideally this would be achieved by the graphing tool. For many things you want to join the points linearly over time, for a setpoint you don't want to just draw a line between them but draw more a histogram with the setpoint being the histogram height.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - so I think we are in agreement.  The set-point, as a function of time, changes as a series of steps.  Whether you plot the set-point as a stepped line or as a histogram is a matter of presentation.  However, I still think that there is a misunderstanding - either the scientists have misunderstood what a set-point really is, or we have misunderstood what they are asking for.

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - #2348 is merely about extracting the history of one or more PVs from the archive and providing that history in a convenient form (i.e. as a conventional array, as distinct from an EPICS waveform).  There is no additional archiving to be done - the PVs are already archived; all we are doing is extracting previously archived data.  
Once the history is in the form of an array, it is easy to manipulate and transform (but the manipulation & transformation will be achieved via other tickets).
If you were to plot the extracted history, the graph would look identical to the one produced by the Log Plotter (it's the same data, after all).

**Comment by John-Holt-Tessella** [comment]
@kjwoodsISIS I am not sure that is true. The archived value may plot more correctly because it knows the value has not changed over the time period so may plot steps. The OPI is plotting vales on change, this is easy to fix and is now the way all graphs are done (see template `To make lines scroll continuously use Trigger PV pointing at heartbeat of IOC $(P)CS:IOC:<DEVICE MACRO>:DEVIOS:HEARTBEAT`) Although this does mean it only updates every second; This is often enough for the Eurotherm because its maximum scan rate is 1s or greater.
