### ISSUE TITLE
Additional button behaviours within the Banner

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2442]
As a scientist I would like to have the `Stop All` button in the banner actually stop all, and not just motion - or have the option to access buttons of a similar nature to stop other items.

** Acceptance Criteria **
1. `Stop all` is labelled in a fashion that makes sense for what it is actually stopping
1. There is a way to define what is stopped by that button

** Notes **
1. When demoing to the muon scientists they commented that stop all is misleading on a system that has no motors, and they would appreciate a similar button to turn off all the magnets at once
1. They also indicated a desire to have something more specific such as the overall voltage status (so if one is off it is an easily seen error), this should be covered by #1460 
1. It might also mean multiple buttons with different behaviours, although this would need to be considered in detail beforehand

**Comment by adamb56789** [comment]
Changed the stop motors button from "Stop All" to stop "Stop All Motors" as part of https://github.com/ISISComputingGroup/IBEX/issues/3562 (this can also be customised). https://github.com/ISISComputingGroup/IBEX/issues/3562 allows buttons to be added to the banner which write to records defined in the instrument's configurations directory [PR.](https://github.com/ISISComputingGroup/EPICS-ioc/pull/403)

**Comment by Tom-Willemsen** [comment]
Being done as part of https://github.com/ISISComputingGroup/IBEX/issues/3562 , this ticket is no longer required
