### ISSUE TITLE
GUI: Requirements Meeting for Buttons to trigger predefined genie_python scripts

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2444]
As an IBEX user sometimes there are recurring steps that need to be undertaken, which are easily written in python, but which need a friendly user interface that is fairly foolproof to run, as such I want a way in the GUI to use a button to trigger a script. This button should be easily accessible by non-computer users in a hurry as well.

** Acceptance Criteria **
1. You can press a button and an associated script is run
1. This button could be integrated into the banner, or be on an OPI/other screen that is easily accessed

** Notes **
1. This may be a function to consider as part of the script server functionality
1. This may need to be a server/client solution
1. How this is to be done can be decided when this ticket is undertaken

**Comment by KathrynBaker** [comment]
This has been brought up again via the Muons as something that could be needed for RIKEN FE

**Comment by Tom-Willemsen** [comment]
Also consider whether we could do this via https://github.com/ISISComputingGroup/IBEX/issues/3271

**Comment by Tom-Willemsen** [comment]
The acceptance of criteria of this ticket have been covered by https://github.com/ISISComputingGroup/IBEX/issues/5410
