### ISSUE TITLE
Archive/Dataweb:  INST archive page does not refresh when config changed

### ISSUE THREAD

**Issue by samueljackson92** [ISISComputingGroup/IBEX#2446]
I want to be able to have an up to archive page for the INST group so that I can read RC values from the page and use them, e.g. for showing RC values on Dataweb. Currently these are only updated when the INST archiver is restarted which does not happen when the the users configuration changes in IBEX. This means that the archive page can become out of sync with what is in IBEX.

#### Acceptance Criteria
I can reliably read values listed on the INST archive webpage or from some other source from dataweb without having to reboot the INST archiver.

#### Notes 
 - This was originally discovered in #2070
 - We cannot just rebuild the inst config every time the user updates there configuration file because it takes several minutes, which is far too slow.

**Comment by DominicOram** [comment]
The issue this causes (#2070) will be fixed in #2448
