### ISSUE TITLE
Question: use anaconda for genie_python?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2449]
This comes partly out of https://github.com/ISISComputingGroup/EPICS-DbUnitChecker/pull/6 - there is a units checking library, but it didn't pip install easily. When I tried it, the issue seemed to be netCDF. However netCDF is included in anaconda, is there any advantage in us using mini-conda as the basis of our python virtual environment build?

**Comment by mattclarke** [comment]
For the Python 3 version of genie_python I based it on WinPython which includes most (all?) of the scientific libraries we need (including netCDF) and has allowed the build script to be simplified significantly.
It would be simple enough to do the same for the Python 2 version, or just wait for Python 2 to fade away.

**Comment by FreddieAkeroyd** [comment]
Given we are testing rolling forward new genie python dependencies, maybe now might be a good time to use WinPython with current genie-python 2?

**Comment by John-Holt-Tessella** [comment]
Ensure that the python in #2932 works
