### ISSUE TITLE
GUI/Block server: Add limits to configurations

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2453]
As a scientists I want to set the allowed limits of certain values within my configuration. This will make it easier for me to set up these limits. I will no longer have to set the PV values and the limits will be shown with the relevant PV/ioc depending on implementation.

**Comment by KathrynBaker** [comment]
This has been referenced again in relation to the alarm server thinking, closing as being superseded by that work.
