### ISSUE TITLE
RIKEN Front End: GUI: OPI to summarise the status of the magnets

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2456]
As an IBEX user working with the RIKEN front end, I want a summary screen for the status of the magnets that mimics the layout of the beamline

**Acceptance Criteria**
1. There is an OPI, much like the one created in #2275 but for the layout of the RIKEN magnets

**Notes**
1. This has been requested for September
1. This should cost about a point
1. The existing Danfysik OPI will do the work for all the drill down aspects, but care will need to be taken that the prefix matches the multi-drop requirements (see the st requirements from #2455, as each is likely to need a name of the style RKNPS_01:n where n is the address of the PSU)

**Comment by DominicOram** [comment]
* Layout on sharepoint (ICPDiscussions/Riken FE/RIKEN Front End Upgrade)
* n is actually going to be the name of the PS (see sharepoint layout)
