### ISSUE TITLE
IOC: Create emulator and tests for Genesys PSU

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2458]
As a developer I would like to be confident that the Genesys PSU works, as such I need an emulator and tests for it.

**Acceptance Criteria**
1. There are tests that run in rec sim (where possible) and dev sim mode to test that the behaviour of the Genesys is mimicked:
   1. set and read current
   1. set and read voltage
   1. power supply on/off
1. All tests run and pass for other devices (use the run_tests.bat run_all_tests.bat will be delete when Stress rig is committed)

**Notes**
1. This is planned as a learning ticket for use by a new starter joining the team during Sprint 2017_06_29 (although at the very tail end, so may not be undertaken until Sprint 2017_07_27)

**Comment by esouthren** [comment]
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/25

https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/15

**Comment by mattclarke** [comment]
The emulator works, but just needs some tidying up.
The tests also need tidying up.
