### ISSUE TITLE
genie_python: No error on incorrect argument

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2466]
I just ran:

```
g.waitfor(uamps=10, max_wait=10)
```

It didn't stop waiting after 10 seconds because it should have been:

```
g.waitfor(uamps=10, maxwait=10)
```

I would have expected an error that the argument was incorrect rather than just ignoring it.

**Comment by FreddieAkeroyd** [comment]
does it try and look for a block called "maxwait" ?

**Comment by AdrianPotter** [comment]
If it did, it didn't say
