### ISSUE TITLE
System Tests: Review missed PRs

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2468]
There are a number of very old PRs for system tests (https://github.com/ISISComputingGroup/ibex_system_tests/pulls). Merge those that are still relevant (tweaking where they are out of date) and delete those that are not.

**Comment by AdrianPotter** [comment]
I've tidied the PRs. There's one left that should be added but I've requested a few edits:

https://github.com/ISISComputingGroup/ibex_system_tests/pull/15
