### ISSUE TITLE
IRIS: ISIS Exchange Gas (IEG) System for the CCR

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2469]
As an IRIS scientist, I want to control the ISIS Exchange Gas (IEG) System for the closed-cycle refrigerator (CCR).

#### Acceptance Criteria
1. I can view the current Sample Pressure (in mbar)
   1. if the Sample Pressure exceeds 350 mbar, the system should dispay the string "> 350 mbar"
1. I can view the current Sample Bin Pressure (in mbar)
   1. the Sample Bin Pressure can be lower than 5.000E-04 mbar, so the field must be able to display small values.
1. The system reports its current operating mode
1. I can change the current operating mode by invoking any of the IEG commands:
   1. Pump, Purge & Fill
   1. Pump
   1. Start/Stop Flow
   1. Shot
   1. Abort – terminates any of the above operations.
1. The system reports its current status

#### Notes
1. 07-07-2017: This system is requested for cycle 2017/02 (starts 19th Sept 2017)
1. 07-07-2017: There is an existing VI - C:\LabVIEW Modules\Drivers\ISIS Exchange Gas\ISIS IEG.
   1. The current ISIS Exchange Gas (IEG) System is being modified, which will introduce some new behaviour.
   1. Matt North will provide an update on the changes to the existing system in w/c 24th July 2107.
1. 07-07-2017: Initial thinking:
   1. It consists of 2 devices – 1 the IEG controller itself, the other a pressure monitor (TPG21x). Pretty simple.
   1. The IEG driver looks like it should be a straightforward stream device via asyn.  There seems to be some maths and response interpretation, but nothing complex.
1. 07-07-2017: A screenshot of the existing VI user interface is attached.
PLEASE DO NOT USE LABVIEW VI AS A REFERENCE WITHOUT TALKING TO MATT NORTH FIRST!!
![isis_ieg_vi_screenshot](https://user-images.githubusercontent.com/7249337/27961123-a1cf0572-6325-11e7-8cff-20e6b8ceeba6.png)
1. 14-08-2017: There is a [sketch](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/IRIS/ISIS_IEG_UI_Sketch.pdf) of the new UI.
1. 14-08-2017: There is a description of the [IEG Message protocol](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/IRIS/IEG%20Message%20Protocol.pdf) (plus [clarifications](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/IRIS/Clarifications%20on%20IRIS%20Exchange%20Gas%20System.pdf)), which describe the operation of the new IEG.

**Comment by GDH-ISIS** [comment]
Please Note : Matt North is currently further developing this controller - on OSIRIS. He is calibrating the equipment also. As a result, the vi is SourceSafe does not contain the correct calibration. In addition, Matt has just mentioned to me that there are changes required- the GUI needs to be updated quite a bit apparently. Sounds to me as though the LabVIEW driver may need to be ditched and the development started again, although I do not currently know the details.

**Comment by kjwoodsISIS** [comment]
Spoke to Matt North at 16:10 on 25th July.  Matt will write a document explaining the command set of the new device.  The new device is quite different from the old device, so the existing VI won't be much use as a guide (as Gareth suspected).  We will then have a meeting with Matt to design a new GUI.
Matt is hoping to have the new document ready by close-of-play, Friday 28th July.

**Comment by kjwoodsISIS** [comment]
Some clarifications provided by Matt in the following document: http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/IRIS/Clarifications%20on%20IRIS%20Exchange%20Gas%20System.pdf

**Comment by Tom-Willemsen** [comment]
IOC/emulator/tests have been implemented.

EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/96
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/171
Support module: https://github.com/ISISComputingGroup/EPICS-IEG/pull/1
Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/32
Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/19


Marking this ticket as impeded, awaiting some discussions about the GUI and a couple of clarifications from Matt North regarding the protocol. Meeting is scheduled 10/8/17 to discuss these with Matt.

**Comment by Tom-Willemsen** [comment]
Kevin is drawing up a mock OPI and will circulate it to scientists and Matt for comments

**Comment by kjwoodsISIS** [comment]
The previous IRIS IEG had a software "safety interlock" (for equipment protection, not personnel protection) implemented in the VI.  A software safety interlock is no longer required - see below:
> From: North, Matt (STFC,RAL,ISIS) 
> Sent: 14 August 2017 16:02
> To: Woods, Kevin (Tessella,RAL,ISIS); Silverwood, Ian (STFC,RAL,ISIS); 
> Garcia Sakai, Victoria (STFC,RAL,ISIS)
> Cc: Willemsen, Thomas (Tessella,RAL,ISIS)
> Subject: RE: Sketch of UI for new IRIS IEG
> 
> The ‘safety interlock’ in software is an interim solution and, as a point of note, ‘safety’ refers 
> to equipment protection not personnel.
> 
> The hardware has been modified so that the a valve cannot operate until the bin vacuum 
> switch is made. There is no need for the interim solution to be copied in IBEX. However a 
> view of the bin pressure on the GUI maybe of value. Ian?
> 
> Thanks,
> Matt
> 
>> From: Woods, Kevin (Tessella,RAL,ISIS) 
>> Sent: 14 August 2017 15:58
>> To: Silverwood, Ian (STFC,RAL,ISIS); Garcia Sakai, Victoria (STFC,RAL,ISIS)
>> Cc: Willemsen, Thomas (Tessella,RAL,ISIS); North, Matt (STFC,RAL,ISIS)
>> Subject: RE: Sketch of UI for new IRIS IEG
>> 
>> Hi Ian,
>> 
>> OK.  Thanks for this.  I suggest we add the Sample Bin Pressure to the user interface.  We 
>> already have support in IBEX for TPG26x devices, so it won’t be hard to include it.
>> 
>> What is new to us is the fact that the Sample Bin Pressure acts as safety interlock.  There is 
>> some logic in the old VI that disables some of the buttons (e.g. Pump, Purge & Fill) if the 
>> pressure exceeds a certain value, but that appears to be all it does.  If the pressure exceeds 
>> the limit during an operation, I don’t believe it actually stops the operation.  That doesn’t 
>> seem quite right to me (I think it ought to stop the current operation).  So, I’d like to 
>> confirm the correct behaviour:
>> 
>> 1.   If the sample bin pressure is less than a threshold value, the IOC will operate normally.
>> 2.   If the sample bin pressure is greater than or equal to a threshold value, the IOC will
>>      a.  Halt the current operation
>>      b.  Disable the Pump, Purge & Fill, Pump, Start/Stop Flow and Shot buttons (the Kill 
>>           button will remain enabled).
>> 
>> Have I got that right?  In particular, if the sample bin pressure does hit the threshold, how 
>> should the user rectify the situation – by pressing the Kill button? By doing something else?
>> 
>> In the current VI, the threshold sample bin pressure is set to 5.00 x 10-4 mbar.  Is that correct?
>> 
>> Kevin
>> 
>>> From: Silverwood, Ian (STFC,RAL,ISIS) 
>>> Sent: 14 August 2017 15:21
>>> To: Woods, Kevin (Tessella,RAL,ISIS); Garcia Sakai, Victoria (STFC,RAL,ISIS)
>>> Cc: Willemsen, Thomas (Tessella,RAL,ISIS); North, Matt (STFC,RAL,ISIS)
>>> Subject: RE: Sketch of UI for new IRIS IEG
>>> 
>>> Hi Kevin,
>>> 
>>> Sorry I did not get back to you earlier. I have spoken to Vicky and we are happy with the 
>>> way it looks. I believe that the sample bin pressure is read from TPG26X_01 and acts as 
>>> a safety interlock to avoid damaging the CCR – if above a certain pressure it will not 
>>> allow the IEG to function.
>>> As for the error codes, they look OK, but Matt is probably better equipped to answer there.
>>> 
>>> Thanks,
>>> 
>>> Ian

**Comment by AdrianPotter** [comment]
A couple of changes requested in IOC Test Framework, and a very minor change in the IOC

**Comment by Tom-Willemsen** [comment]
Have done all reworks. Could not reproduce the failing test though... (I ran them >10 times to check for consistency)
