### ISSUE TITLE
ENGIN-X: Test jawsets

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2470]
The logic contained in the VI for the third ENGIN-X jawset implied that the set point and readback values for the gaps of the third jawset were very different. As this is unusual behaviour we should thoroughly test the jawset under both Labview and IBEX to confirm that it is working as expected.

The jawset in question may be soon to be replaced, making this ticket redundant.

**Comment by DominicOram** [comment]
As part of this ticket we should also set the limits as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/EnginX-Jaws

**Comment by DominicOram** [comment]
We should also confirm that the calibration of jaw 3 matches the VI

**Comment by AdrianPotter** [comment]
![image](https://user-images.githubusercontent.com/10273443/30588128-79ae637a-9d2d-11e7-940a-dc5509cbef4a.png)
