### ISSUE TITLE
Update homing position on instruments

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2471]
Following on from discussion in #2184 it has been decided to use a home position of 0 in dial/raw units for all axes. The next version of the EPICS Galil driver will also remove the HOMEVAL PV and use the above logic, the version we are currently using behaves in this way when HOMEVAL is 0. Thus we need to:

- Set HOMEVAL PV to zero for each axis, with a corresponding change in the motor record OFF (offset) field to give the same readback at home position.
- Make sure the SECI / LabVIEW system also follows this convention on instruments that may need to revert back     

#### Procedure: ####
1. Record the current home position and limits `caget IN:<inst>:MOT:MTR<num>_HOMEVAL_MON IN:<inst>:MOT:MTR<num>.HLM IN:<inst>:MOT:MTR<num>.LLM`
1. Set the value to 0 `caput IN:<inst>:MOT:MTR<num>_HOMEVAL_SP 0`
1. Home the motor (click home)
1. Check position is 0
1. On motor details screen:
   1. click `set` button next to cal (in calibration)
   1. Set the offset value to the former homeval
    1. click `use` button next to cal (in calibration)
   1. set high and low limits in user to former values
1. Home motor check it still homes to original position

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Resetting-HOMEVAL for updated procedure and if you do not want to/cannot home the axis

**Comment by kjwoodsISIS** [comment]
POLARIS is the most likely candidate that uses Galils & IBEX/SECI.

**Comment by Tom-Willemsen** [comment]
Was this fixed by ticket 2551 (upgrade ibex on all instruments)?

**Comment by AdrianPotter** [comment]
No. It wasn't done as part of the upgrade because it would have required moving the motor which we didn't necessarily have permission to do. @FreddieAkeroyd mentioned he had a script or similar that would determine for each instrument whether any updates are needed.

**Comment by John-Holt-Tessella** [comment]
I am just writting a quick script to determin missing settings

**Comment by John-Holt-Tessella** [comment]
Motors needing doing as of 2017-09-19

IN:LARMOR:
      1: 1, 2, 3, 4, 5, 6, 7
      2: 1, 2, 3, 4, 5, 6, 7
      5: 3, 4, 5, 6, 7
      6: 3, 4, 5, 6
      7: 3
IN:ALF:
      1: 1, 2, 3, 4, 5, 6
      2: 1, 2, 3, 4, 5, 6, 7
IN:MUONFE:
      1: 4
IN:IMAT:
      1: 1, 5, 6, 7
      2: 1, 2, 3, 4, 5, 6, 7
      3: 1, 2, 3, 4, 5, 6, 7
      4: 1, 2, 3, 4

**Comment by FreddieAkeroyd** [comment]
Motors still needing doing

IN:LARMOR:
      1: 1, 2, 3, 4, 5, 6, 7
      2: 1, 2, 3, 4, 5, 6, 7
      5: 3, 4, 5, 6, 7
      6: 3, 4, 5, 6
      7: 3

IN:MUONFE:
      1: 4

IN:EMMA-A:
      1: 1, 2, 3, 4

IN:IMAT:
      1: 1, 5, 6, 7
      2: 1, 2, 3, 4, 5, 6, 7
      3: 1, 2, 3, 4, 5, 6, 7
      4: 1, 2, 3, 4

**Comment by rerpha** [comment]
following on from #6988 i am going to propose this to do the others. 

muonfe - is that a barn door axis? if so we can probs ignore

this ticket should involve running the script again to make sure they all still need doing

**Comment by rerpha** [comment]
seems emma-a has been done according to the script so remaining are 

IN:IMAT:
      1: 1, 5, 6, 7
      2: 1, 2, 3, 4, 5, 6, 7
      3: 1, 2, 3, 4, 5, 6, 7
      4: 1, 2, 3, 4
IN:MUONFE:
      1: 4

**Comment by rerpha** [comment]
email sent off to imat scientists asking about upcoming shutdown

**Comment by rerpha** [comment]
Right, there are actually a lot more, so will send emails off in due course(other than SURF) 

 IN:IMAT:      1: 1, 5, 6, 7, 8
      2: 1, 2, 3, 4, 5, 6, 7, 8
      3: 1, 2, 3, 4, 5, 6, 7, 8
      4: 1, 2, 3, 4
IN:MUONFE:
      1: 4
IN:OSIRIS:
      1: 1, 2, 3
IN:INES:
      1: 5
IN:SURF:
      1: 1, 2, 3, 4, 7, 8
      2: 1, 2, 3, 4
      3: 7, 8

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/311/files fixed the homeval script

**Comment by FreddieAkeroyd** [comment]
If SURF is done then labview homeval/offsets would need changing too in case they go back to labview for an experiement. So may be best to delay that one?

**Comment by rerpha** [comment]
imat scheduled for 09/01/23 - just checked and none of the axes have offsets already so it should be fairly straightforward

**Comment by rerpha** [comment]
to review run `%PYTHON3% \instrument\apps\epics\utils\check_homevals.py`

some motors will be down as its shutdown but check the ones in concern (see above)
