### ISSUE TITLE
Engin-X: Commission sample positioning system

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2472]
This is a follow-up ticket to #2401 

The sample positioning system on Engin-X needs to be commissioned. It uses Galil code to talk to a jog box. Under IBEX, this galil code may need to be tweaked to ensure that (a) it always runs correctly on startup and (b) ensure that it is compatible with the homing routines.

This tweaked Galil code will need to be tested on Engin-X itself because we can't easily get hold of all the necessary Galil parts.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - please coordinate with @DominicOram on testing - see #2470.

**Comment by Tom-Willemsen** [comment]
Following a long discussion, we've decided to go down a different route entirely for ticket #2401. As such, this ticket is no longer relevant. Closing.
