### ISSUE TITLE
Update cygwin tools (procServ, conserver, console) to 64bit versions

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2475]
We are getting some problems with instrument startup hangs saying Cygwin heap space is corrupt. A cygwin32 recompile may help, but probably worth moving to cygwin 64bit instead

To test: run start_ibex_server and check all starts up OK

**Comment by FreddieAkeroyd** [comment]
New 64bit Cygwin binaries added in PR

**Comment by Tom-Willemsen** [comment]
Used old version - was able to reproduce the issue. Pulled this ticket's EPICS-tools branch, instrument started successfully. I think that's sufficient to mark this ticket as complete.
