### ISSUE TITLE
MERLIN: Fermi Chopper Emulator

### ISSUE THREAD

**Issue by samueljackson92** [ISISComputingGroup/IBEX#2476]
As a developer, I want IBEX an emulator to write code against for the Fermi Chopper.  

This is a sub issue of #2355 

#### Acceptance Criteria
1. The emulator must accept inputs and return outputs in the format specified by the [manual](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/MERLIN/Fermi%20Chopper%20Communications%20Protocol.pdf).
1. The emulator must be able to interact with existing LabVIEW code.

**Comment by kjwoodsISIS** [comment]
The MERLIN scientists should be able to provide the calculation that relates energy/frequency to speed/phase.

**Comment by Tom-Willemsen** [comment]
PR linked in ticket 2355
