### ISSUE TITLE
Write emulator for Agilent 33220A

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2479]
As a developer I would like to be confident that the Agilent 33220A works, as such I need an emulator and tests for it.

Also the Agilent 33220A IOC is sufficiently old that it does not use a macro for IP address. This should be remedied so that it is easier to set the device up.

**Acceptance Criteria**
1. There are tests that run in rec sim (where possible) and dev sim mode to test that the behaviour of the 33220A is mimicked:
   1. get and set units
   1. get and set function
   1. get and set frequency, amplitude and offset
   1. Turn output on/off
1. All tests run and pass for other devices (use the run_tests.bat run_all_tests.bat will be delete when Stress rig is committed)

**Notes**
1. This is planned as a learning ticket for use by a work experience student joining the team during Sprint 2017_06_29

**Comment by drapj002** [comment]
See https://github.com/ISISComputingGroup/EPICS-ioc/pull/165
