### ISSUE TITLE
activemq password

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2481]
Currently the activemq.xml file is edited to set a password as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ISIS-Proxy but this now leaves a changed file under version control that should not be committed. Ideally this file should not need to be changed locally - could we not load a properties file from "settings" instead to specify these parameters, much like how activemq.xml currently loads  conf/credentials.properties and then use ${macro}

**Comment by John-Holt-Tessella** [comment]
There is a plan see #1995

**Comment by DominicOram** [comment]
Closing as the way we do this has completely changed, also https://github.com/ISISComputingGroup/IBEX/issues/2188 covers some of these concerns
