### ISSUE TITLE
genie python build not setting LATEST_BUILD.txt correctly

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2483]
The genie python build task is not currently setting LATEST_BUILD.txt correctly, this means the update_genie_python_vegas job is unable to update python there correctly and builds on ndwvegas are failing

**Comment by mattclarke** [comment]
It was a small change to the build batch file to put echo on.

To review, just confirm that the build number is correct in \\isis\inst$\Kits$\CompGroup\ICP\genie_python\LATEST_BUILD.txt

For completeness you should probably force Jenkins to do a new build
