### ISSUE TITLE
Make templates for IOCs not complete

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2484]
When creating a new IOC I found that the makefile in the iocBoot/ioc-IOC-01 directory was incomplete, the `TARGETS` line was missing `relPaths.sh runIOC.bat runIOC.sh`, I noticed this as a missing runIOC.bat.

We should check where this is templated from and make sure it is up to date.

**Comment by KathrynBaker** [comment]
Of course, Freddie might just know the answer when he sees this come through

**Comment by FreddieAkeroyd** [comment]
When I merged our 3.14 changes some bits seem to have got missed, the st.cmd and Makefile in the ioc App area are OK, but the Makefile in iocBoot seems to have got missed. However all seems to be OK for "exampleApp", it is just "normal app" that has bits missing. Will re-apply changes.

**Comment by FreddieAkeroyd** [comment]
To test: you probably need to "make clean" to make sure new templates are installed, then try makeBaseApp.pl again and check TARGET etc. are as you expect

**Comment by KathrynBaker** [comment]
Thanks Freddie, I’ll delete and redo the IOCs for the RIKEN PSUs to test this later today.
