### ISSUE TITLE
ENGIN-X: Cybaman

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2489]
As a scientist, I want to to control the Cybaman goniometer, so that I can control the position of the sample in my experiment.

#### Acceptance Criteria
1. I can control the Cybaman goniometer from a GUI.
1. I can control the Cybaman goniometer from a genie_python script.

#### Notes
1. There is currently a LabVIEW VI to control the Cybaman goniometer.
   1. We could use lvDCOM to communicate with the VI.  The GUI could be an OPI that duplicates the (simple) LabVIEW UI.
1. Alternatively, we could create an IOC to replace the LabVIEW VI (the communication with the Cybaman control system is not complex).
1. For more details see https://github.com/ISISComputingGroup/IBEX/wiki/ENGIN-X-Instrument-Details#noteCybaman

**Comment by John-Holt-Tessella** [comment]
Instrument scientists have said they do not need this it is controlled by a separate PC (see IBEX page). However we have found control in the open genie scripts so we will double check that this piece of scripting is old and unused.

**Comment by kjwoodsISIS** [comment]
> From: Kelleher, Joe (STFC,RAL,ISIS) 
> Sent: 20 July 2017 16:49
> To: Woods, Kevin (Tessella,RAL,ISIS); Kabra, Saurabh (STFC,RAL,ISIS)
> Subject: RE: ENGIN-X Scripts & Cybaman
> 
> Hi Kevin, the Cybaman is generally used less often than our other equipment (stress rig, positioner, furnace), perhaps once per cycle on average. We could fall back to SECI for those experiments if necessary. Recently we have been using the Cybaman offline quite a bit too, but I don’t think that will necessarily be the case in future.
> 
> Yes, the Open Genie scripts communicate directly only with the Labview VI, which then talks via a Moxa to the Cybaman. The user would normally make use of the cyba_scan command, and I believe this command calls cyba_measure. I’m not sure what the PROCEDURE  <no-name> is – wouldn’t that be a syntax error?
> 
> 
> Joe Kelleher
> ISIS Pulsed Neutron & Muon Source, Harwell Campus, Didcot, Oxfordshire OX11 0QX
> 01235 446922 / 07754 415535
> 
>> From: Woods, Kevin (Tessella,RAL,ISIS) 
>> Sent: 20 July 2017 16:39
>> To: Kelleher, Joe (STFC,RAL,ISIS); Kabra, Saurabh (STFC,RAL,ISIS)
>> Subject: ENGIN-X Scripts & Cybaman
>> 
>> Hi Joe, Hi Saurabh,
>> 
>> We are currently reviewing the ENGIN-X OpenGENIE scripts, with a view to migrating them to genie_python.
>> We’ve come across a number of procedures which relate to the Cybaman in the file enginx_routines.gcl.
>> PROCEDURE  <no-name>
>> PROCEDURE cyba_measure
>> PROCEDURE cyba_scan
>> 
>> As far as we can tell, these are the only PROCEDUREs which reference the Cybaman.  Furthermore, all the interaction between the PROCEDUREs and the Cybaman is via LabVIEW.  Is that correct? (i.e. you never talk directly to the Cybaman).  How often do you use these PROCEDUREs?  Do you plan to use them at all in the next cycle (Cycle 2017/02)?
>> 
>> Our current thinking is that we preserve the current LabVIEW Cybaman VI and simply create a thin EPICS compatibility layer to allow it to be used from IBEX.  Creating the ability to communicate directly to the Cybaman is likely to be a long, complex process, for potentially very little gain.
>> 
>> I’d be grateful if you could let me know your thoughts as soon as possible – so that we can ensure good communication with the Cybaman device in good time for the next cycle.
>> 
>> Thanks,
>> 
>> Kevin

**Comment by KathrynBaker** [comment]
There is now a flowchart for the cybaman based on the LabVIEW in http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FENGINX

An ASYN/STREAM IOC should be able to fulfil the requirements.

The details for the COM Port are:
Baud: 38400
Data: 8
Parity: None
Stop: 1
Termination Character: Ox6 (ACK, ^F)

**Comment by Tom-Willemsen** [comment]
EPICS: https://github.com/ISISComputingGroup/EPICS/pull/95
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/170
GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/537
Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/17
Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/30

**Comment by Tom-Willemsen** [comment]
With regard to "error code -99998", this apparently means "Position not reached" but it is not clear whether it is even possible to reach this error code in labview, much less the exact set of conditions that cause it. As such, I've left out this bit of logic from the IOC.

Email copied from @KathrynBaker below:
> There are a few defined error codes in the cybaman code which are dealt with as follows:

> -99999, is an “unrecognised serial response”, which shows a status message of “You may need to reinitialise.”
> -99998, is “Position not reached” , which shows a status message of “You may need to reinitialise.”
> -99997 and -99996, are not detailed and shows no message

> Where these values are coming from I have no idea, but that is the best information I can give you. I actually have this strange feeling it might be impossible to reach those error codes.

**Comment by kjwoodsISIS** [comment]
To clarify @Tom-Willemsen comment (above):
The Cybaman IOC has been implemented as a stream device by reverse engineering the existing Cybaman VI, because there is no other documentation available.  As Tom notes, the code relating to error "-99998" appears to be unreachable.  Therefore, because we cannot determine the conditions under which error "-99998" might happen, we are unable to implement a way to handle this (potential) error in the IOC.  On the assumption that error "-99998" is genuinely unreachable in the VI, the risk of this error being unhandled in the IOC seems small.

**Comment by DominicOram** [comment]
As per our discussion can you do the following:
* Refactor the _CALC_TM_AND_SET PV to remove the $(SP_IF_A)'s
* Only add the 2 second delay to the home when required (sorry)

**Comment by John-Holt-Tessella** [comment]
Check 2 requested edits.
