### ISSUE TITLE
Deploy: Create a settings VHD

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2493]
Create a configuration VHD. This should contain:

1. Common calibration files (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)#setting-up-a-calibrations-directory)
1. Configuration directory checked out to master (`git clone http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/inst.git <machine name> C:\Instrument\Settings\config`)

Create a var VHD. This should contain

1. A base MySql database in `C:\Instrument\var\mysql`
1. A base logs directory
1. A base autosave directory

This is specific to an instrument; it will not change after the first deploy.

**Comment by John-Holt-Tessella** [comment]
The vhds are in `...Kits$\CompGroup\chris` please set the calibartion dir to point at R78  branch

**Comment by Tom-Willemsen** [comment]
- The settings VHD does not appear to contain the common calibration files, but the ticket says it should.
- It's not clear to me from the documentation whether the var vhd should have an empty database in it, or no database at all. Please can you edit the documentation to make the expected workflow clearer.

**Comment by John-Holt-Tessella** [comment]
Docs added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mount-or-create-IBEX-VHDs
