### ISSUE TITLE
User Manual: How to use Simulation Mode to check genie_python scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2498]
As a scientist, I want to run a "pre-flight check" on my scripts, so that I can discover as many errors as possible before I actually execute the script.

#### Acceptance Criteria
1. Expand existing paragraph on simulation mode to demonstrate how to use Simulation Mode to check genie_python scripts.
   1. Explain that simulation mode won't catch every error.

#### Notes
1. It would be very helpful if we could list the types of error that simulation mode will/will not catch.

**Comment by Rory-Potter-Tessella** [comment]
+1 Vesuvio and IRIS. They would like to use this but didn't know about it.

**Comment by DominicOram** [comment]
Expanded at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Simulating-Scripts
