### ISSUE TITLE
IBEX Training: Training course ahead of Cycle 2017/02

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2499]
As a scientist, I want to attend an IBEX training course, so that I understand how to use IBEX to control my instrument.

#### Acceptance Criteria
1. Schedule a new IBEX training course to take place before the start of Cycle 2017/02.
1. Invite scientists from ENGIN-X, MERLIN and other interested scientists (e.g. scientists from the LSS group).
1. Run the course.

#### Notes
1. The next cycle is 2017/02, starting on 19th September 2017.
1. If there are too many interested scientists, run two training courses.

**Comment by AdrianPotter** [comment]
Please include Iain Johnson on the list of invitees

**Comment by AdrianPotter** [comment]
To be held on morning of Thursday 7th September 9-12. PC setup to be confirmed on Wednesday 16th August. Once that's ok, send invite to list of interested parties.

**Comment by AdrianPotter** [comment]
Template PCs now set up at CDF

**Comment by kjwoodsISIS** [comment]
See also #2552, #2553

**Comment by kjwoodsISIS** [comment]
Course is now arranged.  Delivery will be accounted for by a separate ticket.  This ticket can be closed.
