### ISSUE TITLE
Creating a group called Other does weird stuff

### ISSUE THREAD

**Issue by samueljackson92** [ISISComputingGroup/IBEX#2503]
In the edit configuration window, if I try to create a group called "Other" the text disappears from the box. 

While I understand that I should not be allowed to create a group called Other as a user this behavior is confusing.

**Comment by kjwoodsISIS** [comment]
I agree.  
Why not provide a helpful explanation to the user of the error he/she is making?
"Other" is a reserved name (i.e. it is reserved as the name of the group for Blocks that are not assigned to a named group).  So why not simply display an error dialog, saying something like "Other is not a valid name (it is reserved for use by IBEX).  Please choose a different name."?
