### ISSUE TITLE
Move the EPICS builds to use pipelines

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2504]
Using pipelines allows us to keep the Jenkins configuration as part of the repository. The GUI and genie_python have both been migrated to pipelines We should move the EPICS build to use pipelines too.

It should be possible to configure multiple different type of builds and where to build them via the Jenkinsfile, but this will require some playing. A good start would be:

https://jenkins.io/doc/pipeline/examples/#parallel-multiple-nodes

The alternative would be to have multiple Jenkinsfiles, one for each build type, e.g. Jenkinsfile.windows_x64, Jenkinsfile.windows_x64_clean etc.
This may turn out to be a pain to maintain in the longer term though.
It does seem possible to call a common file which might remove some of the burden.

**Comment by John-Holt-Tessella** [comment]
Pair to learn from @mattclarke

**Comment by FreddieAkeroyd** [comment]
Though we could parse env.JOB_NAME, I think using build parameters to pass architecture and trigger time to a common Jenkinsfile might work best? We could also use build parameters to control execution of e.g. the deployment to kits$ step for a particular build architecture combination.

**Comment by FreddieAkeroyd** [comment]
Tasks:
- Reorganise Jenkins_build.bat so easier to use build phases and also to call from outside of Jenkins
- Look at using common build tasks repository for e.g. update_genie_python

**Comment by John-Holt-Tessella** [comment]
Impeded awaiting release

**Comment by John-Holt-Tessella** [comment]
Drop pipeline label from job name All jobs should be pipelines.

**Comment by AdrianPotter** [comment]
Is anything impeding this anymore @FreddieAkeroyd now that we've released?

**Comment by FreddieAkeroyd** [comment]
All jobs, except linux ones, now converted to pipeline. Awaiting checks on if "clean after checkout" is honoured when specified in the jenkins config page or whether it needs to be passed via a label etc. or determined from job name or otherwise.

**Comment by John-Holt-Tessella** [comment]
Awesome!!

**Comment by FreddieAkeroyd** [comment]
The following post-build actions are currently missing from the pipeline build:
 
// Unable to convert a post-build action referring to "hudson.plugins.findbugs.FindBugsPublisher". Please verify and convert manually if required.
// Unable to convert a post-build action referring to "hudson.plugins.pmd.PmdPublisher". Please verify and convert manually if required.
// Unable to convert a post-build action referring to "hudson.plugins.warnings.WarningsPublisher". Please verify and convert manually if required.
// Unable to convert a post-build action referring to "hudson.plugins.analysis.collector.AnalysisPublisher". Please verify and convert manually if required.
