### ISSUE TITLE
genie_python: Investigate and fix setting PVs by string rather than value 

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2508]
As a developer/scripter I would like to set mbbo, mbbi and bi based on their string names not just the numbers using the ca wrapper and genie_python. This means my code is more readable.

Example:
```
caput %MYPVPREFIX%SAMPOS:X:GOING NO 
caput %MYPVPREFIX%SAMPOS:X:GOING NO
```

but in genie_python

```
In [6]: g.set_pv("SAMPOS:X:GOING", "NO", is_local=True)
ERROR: invalid literal for int() with base 10: 'NO'
```

This will also fix an issue in the IOC Testing Framework

**Comment by esouthren** [comment]
Pull request:

https://github.com/ISISComputingGroup/genie_python/pull/87

**Comment by esouthren** [comment]
Pull request: [https://github.com/ISISComputingGroup/genie_python/pull/87](https://github.com/ISISComputingGroup/genie_python/pull/87)
