### ISSUE TITLE
Overview status screen for all instruments

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2509]
As a developer i would like to be able to see at a glance what the status of all IBEX instruments is. 

This would involve:
* Add functionality to JSON_bourne to serve overview information for all instruments
* Create a webpage that takes this information and displays it

As a start the information displayed should just be if the blockserver is running (e.g. can JSON_bourne connect to the webserver). A possible layout is a grid with each box labelled as one of the instruments and colour coded based on status.

The webpage should automatically update.

Ideally the webpage will dynamically create the layout so that if more instruments are added it need not be modified.

**Comment by AdrianPotter** [comment]
Can I suggest Twitter Bootstrap for rendering the web page:

http://getbootstrap.com/

It makes it easy to create dynamically-sized grid-based layouts. It also has a lot of handy in-built classes

**Comment by DominicOram** [comment]
Yh, I've used bootstrap before. I like it, it's not too hard and looks quite nice.

**Comment by kjwoodsISIS** [comment]
See also #1095
