### ISSUE TITLE
Add backtrace symbol printing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2510]
As a developer I would like to see sensible function names when EPICS prints a stack trace in response to an epicsAssert() call

**Comment by FreddieAkeroyd** [comment]
Before:

[  000007FEEE71D565]: c:\instrument\apps\epics\base\master\src\libcom\osi\os\win
32\osdbacktrace.cpp(epicsBackTrace+0x45)
[  000007FEEE71D206]
[  000007FEEE714EF8]
[  000007FEF0DD6AD5]
[  000007FEF0DDC21B]
[  000007FEF0DDC29B]
[  000007FEF0DDAF1C]
[  000007FEF0DDAAE5]
[  000007FEEE7177F1]
[  000007FEE0C6B0A8]
[  000007FEE0C6AD11]
[  00000000771459CD]
[  000000007727A561]
EPICS Release EPICS R3.15.5.
Local time is 2017-07-27 17:56:17.794288436 GMT Daylight Time
Please E-mail this message to the author or to tech-talk@aps.anl.gov
Calling epicsThreadSuspendSelf()

After:

A call to 'assert(size <= ntohs ( pMsg->m_postsize ))'
    by thread 'CAS-client' failed in ../../../src/ioc/rsrv/caserverio.c line 357
.
Dumping a stack trace of thread 'CAS-client':
[  000007FEEE71D565]: c:\instrument\apps\epics\base\master\src\libcom\osi\os\win
32\osdbacktrace.cpp(epicsBackTrace+0x45)
[  000007FEEE71D206]: c:\instrument\apps\epics\base\master\src\libcom\osi\epicss
tacktrace.c(epicsStackTrace+0x66)
[  000007FEEE714EF8]: c:\instrument\apps\epics\base\master\src\libcom\osi\os\def
ault\osdassert.c(epicsAssert+0x78)
[  000007FEF0DD6AD5]: c:\instrument\apps\epics\base\master\src\ioc\rsrv\caserver
io.c(cas_commit_msg+0x115)
[  000007FEF0DDC21B]: c:\instrument\apps\epics\base\master\src\ioc\rsrv\camessag
e.c(vsend_err+0x3fb)
[  000007FEF0DDC29B]: c:\instrument\apps\epics\base\master\src\ioc\rsrv\camessag
e.c(send_err+0x5b)
[  000007FEF0DDAF1C]: c:\instrument\apps\epics\base\master\src\ioc\rsrv\camessag
e.c(camessage+0x2cc)
[  000007FEF0DDAAE5]: c:\instrument\apps\epics\base\master\src\ioc\rsrv\camsgtas
k.c(camsgtask+0x345)
[  000007FEEE7177F1]: c:\instrument\apps\epics\base\master\src\libcom\osi\os\win
32\osdthread.c(epicsWin32ThreadEntry+0x91)
[  000007FEE144B0A8](_register_onexit_function+0x4a8)

**Comment by FreddieAkeroyd** [comment]
* change directory to base\master\src\libCom\test\O.windows-x64
* set EPICS_STACK_TRACE_TEST_DEBUG=1
* run    epicsStackTraceTest.exe
* You should see  5 tests pass with function names in listing

**Comment by FreddieAkeroyd** [comment]
Updated at https://github.com/ISISComputingGroup/EPICS-base/blob/7562ba63548e20ab7df41661ab9330919c961335/src/libCom/osi/os/WIN32/osdFindAddr.c

**Comment by Tom-Willemsen** [comment]
Tested as described above - tests passed.
