### ISSUE TITLE
Update st.cmd in preparation for emulators

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2511]
A lot of the IOCs don't have the macros in place for DEVSIM and RECSIM because they don't have emulators.

Rather than waiting it would be good to prepare them now, so all our IOCS are consistent.

We should also create st-common.cmd files.

An example of how it should be done is the AMINT2L IOC.

**Comment by GRyall** [comment]
Emulators are now in place for the majority of IOCs, so this ticket has been overtaken.
