### ISSUE TITLE
Dataweb: Add individual instruments to Nagios

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2512]
This is a follow-up to #2169

In #2169 a nagios check was added that checks if JSON bourne is up, but this does not check whether individual instrument's web dashboards are working.

There are two options for implementing this ticket:
1) Have a static webpage that nagios can read
2) Use PhantomJS (or another javascript library) to read the dynamic webpage properly

Talk to @FreddieAkeroyd before picking this up

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/IBEX/issues/2159

**Comment by FreddieAkeroyd** [comment]
Using phantomJS requires moving to the new nagios server

**Comment by GRyall** [comment]
@Tom-Willemsen Is this still relevant with the new web dashboard?
