### ISSUE TITLE
ISISICP: Ensure it can collect grouped data and it is installed on HRPD

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2514]
HRPD appeared to have a problem with grouped detectors under the latest ISISICP program. Having rolled back this is probably not the case. 

 - [ ] Confirm that the fix in Matid has fixed the problem and that we can release the latest ICP program 
 - [ ] Install the latest ICP onto HRPD.

**Comment by FreddieAkeroyd** [comment]
Tested and working on HRPD
