### ISSUE TITLE
ENGIN-X: Collimator Step-Scan Script

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2521]
As an ENGIN-X scientist, I want a genie_python script to perform a step-scan of the collimators, so that I can quickly determine the optimum position.

#### Acceptance Criteria
1. The genie_python script should allow me to specify:
   1. the collimator I wish to move: North or South.
   1. the axis along which I wish to move the collimator (x-axis or y-axis)
   1. the direction in which to move the collimator 
      1. forward or back, relative to the beam direction,  for the x-axis
      1. towards or away from the beam, for the y-axis
   1. the number of steps to make
   1. the step size (in mm)
   1. the time to pause at each step to collect data (neutron counts).
1. The genie_python script should report any errors encountered during the scan (e.g. encountering a limit switch).

#### Notes
1. The script should only control the scanning.  The scientists will plot the data and determine the optimum position of the collimator.
1. Until the second set of motors is installed (see #2520), selecting the y-axis should return an error.

**Comment by Tom-Willemsen** [comment]
r.e. above comment about runs, they currently do a `begin()` and `end()` on every step, which is what has already been implemented, and what their current analysis scripts expect. The scan script should be simple to change to doing everything in one run in the future, if they want to.

> Hi Kevin 
> 
> Our current mode of scanning is number 2. However a lot of time is wasted in this method while the data is written for each file. We would like number 1 : how do you see it working in terms of separating the data within one file ? would you store it in periods in a nexus file? 
> 
> I guess since we have analysis routines which can deal with number 2 we would definitely like that but also the option of number 1. 
> 
> Best 
> Saurabh
> 
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 16 August 2017 16:40
> To: Kabra, Saurabh (STFC,RAL,ISIS) <saurabh.kabra@stfc.ac.uk>
> Cc: Kelleher, Joe (STFC,RAL,ISIS) <joe.kelleher@stfc.ac.uk>; Willemsen, Thomas (Tessella,RAL,ISIS) <thomas.willemsen@stfc.ac.uk>
> Subject: ENGIN-X Collimators
> 
> Hi Saurabh,
> 
> When we met earlier this month to discuss the ENGIN-X collimators, you talked about having a script to scan the position of the collimators (to help you determine the best position of the collimators).
> 
> As part of the work to control the collimators via IBEX, we thought we’d create a simple genie_python script to help you get started.  You can use it as an example and/or modify it to suit your purposes.  We can structure the script in one of 3 ways (illustrated with some simple pseudocode below):
> 
> 1.	Single run, multiple scan steps
> (i.e. Begin a run, perform the scan, Stop the run)
> Begin()
> for (i = 1; i <= N_STEPS; i++)
> {
> Move collimators to next position()
> Measure()
> }
> Stop()
> 2.	One run per scan step
> (i.e. each scan step is a separate run)
> for (i = 1; i <= N_STEPS; i++)
> {
> Begin()
> Move collimators to next position()
> Measure()
> Stop()
> }
> 3.	Scan steps only
> (i.e. leave the scientist to manually start/stop the run)
> don’t forget to manually start a run before using this script
> for (i = 1; i <= N_STEPS; i++)
> {
> Move collimators to next position()
> Measure()
> }
> don’t forget to manually stop the run after using this script
> 
> Which of these would you prefer?
> 
> Tom Willemsen (cc’d) is the developer working on the Collimators.  Please let Tom know your preference.
> 
> Kevin

**Comment by Tom-Willemsen** [comment]
I've now implemented the option to change between using a separate run at each scan step, or using one run and changing periods at each scan step.

**Comment by John-Holt-Tessella** [comment]
Add loop if user doesn't type y or n on confirm step

**Comment by Tom-Willemsen** [comment]
@John-Holt-Tessella done
