### ISSUE TITLE
ENGIN-X: Collimator Continuous-Scan Script

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2522]
As an ENGIN-X scientist, I want a genie_python script perform a continuous scan of the collimators, so that I can quickly determine the optimum position.

#### Acceptance Criteria
1. The genie_python script should allow me to specify:
   1. the collimator I wish to move: North or South.
   1. the axis along which I wish to move the collimator (x-axis or y-axis)
   1. the direction in which to move the collimator 
      1. forward or back, relative to the beam direction,  for the x-axis
      1. towards or away from the beam, for the y-axis
   1. [Optional] the speed at which the collimators should be moved (in mm per minute)
1. The genie_python script should report any errors encountered during the scan (e.g. encountering a limit switch).

#### Notes
1. The script should only control the scanning.  The scientists will plot the data and determine the optimum position of the collimator.
1. Until the second set of motors is installed (see #2520), selecting the y-axis should return an error.
1. The speed of movement should be of the order of 1mm per minute.

**Comment by Tom-Willemsen** [comment]
@davidkeymer is going to investigate adding "change speed" functionality to the collimators VI in #2520 . 

With the current VI it wouldn't be possible to change the speed of the motors driving the collimators and hence can't do a smooth continuous scan. 

In SECI they would have changed the motor speeds by directly accessing the table of motors VI but since this will be lvDCOMed that option isn't available.

**Comment by kjwoodsISIS** [comment]
Note: please don't allow the "change speed" functionality to hold things up.  It is an entirely optional feature.  If it can't be done in time for the release, it can be done at a later date (in a separate ticket).

**Comment by Tom-Willemsen** [comment]
Review:
- Check out changes in https://github.com/ISISComputingGroup/genie_python/pull/86
- Switch to ENGINX config branch
- Ensure GALIL_01 is running in recsim (the blocks are currently pointing at the GALIL as the collimator IOC has not been written yet)
- New script is on the ENGINX config branch under `Python/inst/collimator_step_scan.py`

Check that:
- [ ] Collimator step scan script defines blocks in an intuitive way at the top of the file
- [ ] Script is documented well enough that the scientists will be ok understanding and modifying it
- [ ] Script does what the acceptance criteria above say that it should do
- [ ] Script has been written in the same style as the other scripts that have been migrated (e.g. prompting the user for parameters that haven't been supplied and asking for confirmation before performing the scan)
- [ ] If a limit is reached during the scan then the scan is stopped.

**Comment by Tom-Willemsen** [comment]
Speed block will not be available so I've removed references to it in the script. The collimators will move at whatever speed they're currently set at.

**Comment by mattclarke** [comment]
I have made some small formatting changes to the code, including changing the docstrings to google style.
I agree with John's comment on #2521 about adding a confirmation loop in case the user mistypes 'y' or 'n'.

The scan doesn't start if you put a travel beyond the motor limit, at least on my system. If this is not something to do with my system, should we handle this somehow? If so, we should make a ticket.

**Comment by Tom-Willemsen** [comment]
I don't think a recsim galil "accepts" a setpoint that's beyond it's soft limits - could that have been the issue?

**Comment by mattclarke** [comment]
Ah, that would make sense.

Except for implementing John's suggestion this is ready to be closed.

**Comment by Tom-Willemsen** [comment]
@mattclarke done
