### ISSUE TITLE
genie_python: preparing for Python3

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2523]
As a developer, I am a bit worried that users will get used to `print "hello"` and then when we move to Python3 there will be issues due to the change to `print("hello")`.

Both forms of print work in Python 2.7. Adding `from __future__ import print_function` to ipython_config.py disables the old style print.

Proposal:
* genie_python and instrument scripts are updated to use the new syntax
* training slides are updated to emphasis use of the new print syntax
* existing users are notified that they should use the new print syntax and after a reasonable period we disable the old style (need to take what Mantid do into account)
* new users (ENGINX, MERLIN etc.) will have the old style disabled from day 1

We need to check that the BlockServer isn't broken by this. If it is it shouldn't take long to move it over to the new syntax.

**Comment by samueljackson92** [comment]
This is bigger than just `print` statements. Some things off the top of my head:
 - `dict`'s are unordered, so iterating over them will give different results (V2 had a hack to effectively make them ordered)
 - Integer rounding is different (`5/2` will equal `2.5`)
 - No `xrange` and `range` is an iterator
 - Loop variables don't leak scope

**Comment by mattclarke** [comment]
Print is the probably the only one that (most) users will encounter, hence that is why I am focusing on that.
A full migration is going to take more effort and will need to be done in stages.

**Comment by kjwoodsISIS** [comment]
Superseded by #2803.  Issue closed.
