### ISSUE TITLE
Create training machines

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2525]
In the week commencing 4th September, we will be running the IBEX and genie_python training courses alongside Mantid.

The CDF at RAL in the Atlas building has been selected as the venue. They have 14 training workstations and a central server that can be used to distribute software.

For practical purposes, it would be advantageous for each trainee to have a working copy of IBEX. Each workstation will need the following:

- IBEX
    - Server
    - Client
    - genie_python
    - prerequisites (e.g. MySQL)
- Utilities
    - Notepad++
- Mantid

We suggest creating a standard machine image using hyper-v terminal and then deploy it to the target machines. Final configuration will be achieved using a script.

I suggest the following steps:

1. Contact CDF
    1. Check this plan is feasible
    1. Establish the best way to transfer and deploy the machine image
1. Create a clean Windows 7 image. Someone in the office with Windows 10 (suggest John) should be able to do this.
1. Access the new machine and install the required software
    1. Check that IBEX runs as expected, especially scripting
    1. Pair with someone from Mantid to install and verify it
        - Mantid installation instructions: http://www.mantidproject.org/MBC_Getting_set_up
        - please install Latest Release 3.10.1 (the link is on that page)
1. Add a configuration that contains everything needed for the `genie_python` course. This can be found in the user_manual repository.
1. Write a script that will update the machine to work with a given instrument name. I expect it will need to do the following:
    1. Change the directory name in `C:\Instrument\settings\configurations\....`
    1. Change the name of the file originally `C:\Instrument\settings\configurations\[Machine name]\Python\init_inst_name.py`
1. Export the machine image (again, you might need someone with hyper-v terminal to do this).
1. Send the image to CDF as agreed
1. Once the image has been deployed to the training machines, run the configuration script to update them to work with the new machine names
1. Verify that the deployment has been successful. For example (but not limited to):
    1. Launch IBEX
    1. Check the DAE, configuration and blocks are accessed successfully
    1. Run a simple script

**Comment by kjwoodsISIS** [comment]
> From: Gibbins, Chris (STFC,RAL,RALSP) 
> Sent: 03 August 2017 17:07
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Subject: RE: PC Training suite
> 
> Hi Kevin, 
> 
> a preconfigured imagine wouldn’t work on our machines due to differences in hardware etc. etc. 
> However what you could do is send over a colleague to install/configure it on a pc already in the 
> suite and I’ll make an image of that machine a distribute accordingly, sound good?  
> 
> Kind Regards
> Chris Gibbins

**Comment by AdrianPotter** [comment]
This is done. We've set the machines up at CDF and conferred with the Mantid team that it meets their requirements. A template of the machine to be used can be seen by remoting into `CDF-CAD3` (formerly `NDXTEST1`). To review:

- Confirm the specification given in the ticket is correct
- Confirm `CDF-CAD3` meets that specification

The actual machines to be used are not accessible from the RAL network so cannot be verified without visiting the CDF. That is possible if the reviewer thinks it's necessary, you can contact Chris Gibbins for access, but I don't think it's needed.

**Comment by kjwoodsISIS** [comment]
It is not convenient to go over to the Atlas centre to check these machines.  Adrian demonstrated that IBEX was running on two machines.  We will have another opportunity to check everything is ready in the week of the course itself.  This ticket can be considered complete.
