### ISSUE TITLE
Blockserver: Configurations change very slowly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2526]
The blockserver currently takes a very long time to update configurations, approximately 4 minutes for a config change with one IOC.

This appears to be because it hasn't properly detected that the runcontrol IOC hasn't started properly. 

From having a quick look it appears that it is doing a comparison of dates inside strings instead of using datetime objects.

See lines 229-251 in `blockserver/runcontrol/runcontrol_manager.py` for the loop which appears to be causing a problem.

**Comment by AdrianPotter** [comment]
Once fixed, please lower the verification time in the system tests: .../Contexts/InstrumentStatusProcedures.ctx - "assert_wait_for_dialog_closed"
