### ISSUE TITLE
RIKEN: Helium Level Meters

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2530]
As an instrument scientist on RIKEN, I want to be able to monitor the level of helium in my cryostats.
As a member of the cryogenics team, I want to be able to monitor the helium levels on RIKEN.

**Acceptance Criteria**
1. As a scientist, I can view the level of helium in my cryostats
1. As a scientist, I am warned by the system if the level of helium is outside predetermined limits
1. As a member of the cryogenics team, I can view the level of helium on all cryostats on RIKEN.
1. As a member of the cryogenics team, I am warned by the system if the level of helium on any cryostat on RIKEN is outside pre-determined limits.

Notes
1. Relates to https://github.com/ISISComputingGroup/ControlsWork/issues/285
1. There is a manual available, currently in source safe
1. The proposed implementation is to:
   1. use an EPICS IOC running on the RIKEN front end system to communicate with the helium level meters
      1. the helium level can be published as a PV.
      1. ideally, warning messages (if any) can be published too
      1. an OPI to display information on the RIKEN front-end or other IBEX client.
   1. a LabVIEW VI to display the value of the level VI and any warning messages to scientists not using IBEX
   1. the same LabVIEW VI can be used to display the level VI and any warning messages to member of the cryogenics team (or, perhaps, 
   1. a new VI which aggregates the information from all the RIKEN helium level meters)
1. Standard suite of IOC (x3), emulator, test framework and OPI need to be created. Note that the third IOC is there to cover future requirements, there are currently 2 of these devices available

**Comment by KathrynBaker** [comment]
Original text:

As an instrument scientist on RIKEN, I want to be able to monitor the level of helium in my cryostats.
As a member of the cryogenics team, I want to be able to monitor the helium levels on RIKEN.
As a member of the computing group, I want to able to provide both of the above solutions, which is easy under EPICS if I use an IOC running on the RIKEN front end system.

Acceptance Criteria

Standard suite of IOC (x3), emulator, test framework and OPI need to be created
The IOC is set up and runs on RIKEN front end
The only value required is the level
Notes

Relates to ISISComputingGroup/ControlsWork#285
There is a manual available, currently in source safe
A VI will be needed to read the PV on the RIKEN systems
Some method of reading the level should be made available to the cryogenics team - this could be the same VI as used on the RIKEN instruments, or another method if necessary.

**Comment by John-Holt-Tessella** [comment]
3.2, 3.3, 3.4  Will be done as controls work
Alarm on the PV is good enough to notify parties

**Comment by John-Holt-Tessella** [comment]
See 5 pull reuests referenced above
