### ISSUE TITLE
SKF Chopper: reduce logging when unable to communicate

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2531]
As an ibex user or developer I would like the SKF chopper IOC to not create 600MB per day of log files when it cannot communicate with the chopper controller hardware.

**Comment by kjwoodsISIS** [comment]
Try out a solution for SKF choppers, then try to genericise it.

**Comment by FreddieAkeroyd** [comment]
Asyn has a check for repeated messages, modbus has a separate underlying driver that reports errors before this. I've ported some of this logic into drvModbusAsyn.c

**Comment by FreddieAkeroyd** [comment]
Need to test on IMAT, have merged PR so jenkins will create a static IOC that i can copy down and test with

**Comment by AdrianPotter** [comment]
I've eyeballed the code and it looks fine. Just awaiting testing on IMAT before closing.

**Comment by FreddieAkeroyd** [comment]
Looks to start up OK on IMAT
