### ISSUE TITLE
Support: IRIS Keithley

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2533]
Ian needs to expand his experiment in short order to include a Lakeshore 336 and 4 Keithley 2000s (as opposed to 2). 
We will support the lakeshore with a second IOC and the Keithleys with SD Tests.

**Comment by John-Holt-Tessella** [comment]
Impeded Waiting for Keithlies to arrive from RS

**Comment by AdrianPotter** [comment]
Set up and working using SDTEST. I wrote a quick guide to the SDTEST IOC at:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SDTest
