### ISSUE TITLE
Galil ToM IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2534]
As an IBEX developer, I want to create an IOC that can communicate with multiple Galil axes controlled by LabVIEW VIs.

#### Acceptance Criteria
1. I can configure the IOC to communicate with multiple Galil axes controlled by a LabVIEW VI.
1. I can control any configured Galil-controlled axis from the IOC (via a script or OPI).

#### Notes
1. This ticket is a generalisation of #2520.
1. Notes from @GDH-ISIS 
   1. Just a  quick note : Regarding the collimators for ENGIN-X – I thought the ticket #2520 would be much better being far more general – not really related to ENGIN-X in any way. By making it general, it could be useful in other awkward cases. There is no need to specify the ENGIN-X collimators – I believe there is nothing special about the axes. The EPICS end could have an IOC that could be named as something like Galil ToM IOC. It might be approached in two ways :
      1. A single VI can have any appearance and refer to lots of axes (selected via a setup dialog - standard with LabVIEW). The VI appearance doesn’t really matter as within reason it is hidden. The EPICS end should have a macro that indexes which axis/axes to refer to on the VI. You can then query/control any axis, across Galils in any way you wish.
      1. Similarly, the VI could just refer to single axis. You could then refer to multiple vis to scale up the number of axes. The EPICS end macro would then refer to the vi front panel index – you would have to check whether this would work – not sure about the epics end as it would have to span multiple VIs that would need configuring on the fly ...

**Comment by FreddieAkeroyd** [comment]
Though we should be general where possible, having completed ENGINX are there any other cases that we are aware of where we might need to consider using LabVIEW Galil control rather than EPICS?

**Comment by KathrynBaker** [comment]
I wouldn’t want to guarantee it, but I doubt any other instrument has quite the peculiarities of ENGINX from a beamline controls point of view

**Comment by kjwoodsISIS** [comment]
Chris's comment highlighted the fact that HRPD was not on a local network.  It is now - Anthony Shuttle upgraded it.
> From: Shuttle, Anthony (STFC,RAL,ISIS) 
> Sent: 25 August 2017 15:10
> To: Woods, Kevin (Tessella,RAL,ISIS); Baker, Kathryn (STFC,RAL,ISIS)
> Cc: Keymer, David (STFC,RAL,ISIS); Moreton-Smith, Christopher (STFC,RAL,ISIS)
> Subject: RE: Private Networks for MERLIN & ENGIN-X
>
> Kevin,
> 
> HRPD is done now also – again, ports ** and ** have been configured with the private 
> network (VLAN ****) but not yet patched through to anything.
> 
> Anthony.
> 
HRPD now has the capability to run Galils controllers, if required.  

When the ENGIN-X collimators are further upgraded ENGIN-X will need a new Galil crate (there are insufficient free ports on the current crate).  The existing collimator motors can be connected to the new crate, along with the new motors, allowing control of all collimator motors from EPICS.

Therefore, I think it unlikely we will need the functionality proposed by this ticket.  This ticket will be closed.  It can be re-opened, if the need does crop up again.
