### ISSUE TITLE
MERLIN: LET Oscillating Collimator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2535]
As an MERLIN scientist, I want to attach the LET Oscillating Collimator to MERLIN, so that I can use it in my experiments (while I wait for the construction of the MERLIN oscillating collimator to be completed). 

#### Acceptance Criteria
1. I can start the LET Oscillating Collimator
1. I can stop the LET Oscillating Collimator
1. I can control the LET Oscillating Collimator IOC (or VI)  via an OPI and script
1. Other ACs - TBD.
1. Needs to be ready by 11th October 2017

#### Notes
1. The  scientists have changed their mind about using an oscillating collimator on MERLIN.  They now wish to borrow the oscillating collimator from LET.
1. The current plan is to install & test the LET Oscillating Collimator during the period 11-18 October 2017. 
1. LET has not yet been migrated to IBEX.
   1. The LET Oscillating Collimator is currently controlled by a VI.
   1. The oscillations are controlled by a dedicated Galil program, installed on the Galil.
   1. The VI is responsible for installing the dedicated Galil program.
   1. Need to check if there is a spare Galil (i.e. an entire crate, not just a spare slot) to run the VI
1. Kathryn has suggested the following solution: <br> There is the alternative of migrating the ORC to IBEX and eliminate the VI. The ORC code could be downloaded alongside the homing routines (can be done as a hot fix), the move command can be superseded by a start program in thread command instead of a move (already available).

**Comment by AdrianPotter** [comment]
Having spoken to Kathryn, the preferred solution to this will be to:

- [ ] Include the Galil program in the galil submodule with our other custom routines. Don't worry about the `gal`/`gmc` file extensions, it's all the same
- [ ] Create template settings that loads the Galil and creates a suitable axis. Put it in motorExtensions for future reference. This can then be transferred onto Merlin when they need it
- [ ] Create an OPI that replicates the current function of the VI. The VI sends Galil commands directly to the collimator. We either need to translate them into the corresponding PV or use the general command PV to send the commands directly. I'm told @FreddieAkeroyd knows what that command is. There is some arithmetic involved in the VI in translating the values entered into direct commands. @davidkeymer  is going to examine the VI and provide the information here.

**Comment by Tom-Willemsen** [comment]
Can't be reviewed by anyone with Windows 10 / VS 2017 as the Galil won't talk.

**Comment by Tom-Willemsen** [comment]
Ensure the following are done before merging:

- [ ] Put the fixes described in https://github.com/ISISComputingGroup/IBEX/issues/2676 onto the branch
- [ ] Set `ADEL` on the underlying motor so that it does not fill the archive
- [ ] Ensure autosave is active for the oscillating collimator DB records (setpoints)
- [ ] Investigate why the motor readback (in the table of motors) is different from the readback in the OPI by a factor of 5
- [ ] See whether it's possible to not stop the oscillations if the IOC restarts, this is unintuitive

**Comment by Tom-Willemsen** [comment]
Talk to @FreddieAkeroyd about a test plan for this. Notably, the option not to stop the thread if the galil IOC is restarted will need some thorough testing.

**Comment by AdrianPotter** [comment]
As above. The main concern is that the homing threads will not restart correctly if the motor is restarted with this option. This can be tested using the office Galil crate.

- You can connect to the crate at IP 130.246.51.169, I do it with Putty on Telnet protocol.
- You can start threads by doing `XQ [JP],[Thread]` where `Thread` is the thread number and `JP` is the jump point as in the Galil control program (e.g. `#HOMER`)
    - The standard Galil startup will have homing threads running on 0 and 1
    - The oscillating collimator is currently set up to run on thread 2 (can be changed via PV)
    - The program downloaded to the motor is here: `C:\Instrument\Apps\EPICS\ioc\master\GALIL\iocBoot\iocGALIL-IOC-01\130.246.51.169.gmc`. You can see the various jump points marked with a `#`.
- You can stop a thread using the command `HX [Thread]` similarly to the above syntax
- You can see the status of a thread by doing `MG _XQ[Thread]`. A positive return value indicates a program is running.

I believe the main test is to check that the correct tests are running at any given moment:

- [ ] Start the galil with a modified control program with default options when thread 2 is not already running. Result: thread 0 and 1 should be running
- [ ] Start the galil with a modified control program with default options when thread 2 is already running. Result: t thread 0 and 1 should be running
- [ ] Start the galil with a modified control program with the new `quiet_start_` option when thread 2 is not already running. Result: thread 0 and 1 should be running
- [ ] Start the galil with a modified control program with the new `quiet_start_` option when thread 2 is already running. Result: thread 0 and 1 should be running

- [ ] Start the galil with an unmodified control program with default options when thread 2 is not already running. Result: thread 0 and 1 should be running
- [ ] Start the galil with an unmodified control program with default options when thread 2 is already running. Result: t thread 0 and 1 should be running
- [ ] Start the galil with an unmodified control program with the new `quiet_start_` option when thread 2 is not already running. Result: thread 0 and 1 should be running
- [ ] Start the galil with an unmodified control program with the new `quiet_start_` option when thread 2 is already running. Result: thread 0, 1 **and 2** should be running

- [ ] Kill thread 0 on the galil. Restart it using the default options. When it restarts, thread 0 should be running again.
- [ ] Kill thread 0 on the galil. Restart it using the the new quiet_start_ option with a modified script. When it restarts, thread 0 should be running again.
- [ ] Kill thread 0 on the galil. Restart it using the the new quiet_start_ option with an unmodified script. When it restarts, thread 0 should be running again.

- [ ] Repeat the above tests for thread 1.

**Comment by FreddieAkeroyd** [comment]
How should thread 2 be stared normally on the instrument? Homing threads were started by thread 0 - is this any different? And do we need to cover the case (in another ticket?) of thread 2 terminating while the IOC is still running?

**Comment by AdrianPotter** [comment]
Thread 2 is started by pressing the `start` button on the oscillating collimator OPI. It isn't started by the homing thread. If thread 2 terminates while the IOC is running, it means something has gone wrong in the oscillator program. It can be stopped manually using the `stop` button on the OPI.

**Comment by AdrianPotter** [comment]
- [ ] Take autosave off position. Will generate a lot of non-useful data
- [ ] Make position PV a monitor rather than a scan

**Comment by FreddieAkeroyd** [comment]
Do you mean "archive" rather than "autosave"?

**Comment by AdrianPotter** [comment]
Did not apply hotfix to galil st.common.cmd since the required macros are all available on master

**Comment by AdrianPotter** [comment]
I've added some basic documentation about the Galils here for future reference:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil

**Comment by Tom-Willemsen** [comment]
IOC tests aren't working. I tried to investigate but didn't get anywhere. Possibly something to do with the new `genie_python` version, although the other IOC tests seem happy enough.

I've merged the other PRs, just the IOC test framework one to fix.
