### ISSUE TITLE
NICOS: Integrate the proxy with NICOS core

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2539]
As a developer I would like our additions to NICOS to be added to their core code to better allow collaboration. We currently have a proxy that sits on top of NICOS and sends JSON to ActiveMQ. NICOS have been working on making their communications code more flexible, we should integrate with this and remove the proxy. This will probably involve modifying some NICOS code as well as modifying the protocol that the GUI is expecting.

**Comment by AdrianPotter** [comment]
@DominicOram, this ticket doesn't appear to have clear acceptance criteria, or a description of what you've done so we can compare the work against it. Please could you add them so it can be effectively reviewed.

**Comment by DominicOram** [comment]
Apologies, I somehow forgot to link the PR to the ticket. The PR is at https://github.com/ISISComputingGroup/ibex_gui/pull/583. Is the acceptance criteria listed there ok? I'm happy to add more detail as it was a reasonably large ticket.
