### ISSUE TITLE
NICOS: Lock access to only be localhost

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2543]
As a user and a developer I do not want someone to be able to run arbitrary scripts on my machine without permission. The full solution to this has been outlined in https://github.com/ISISComputingGroup/IBEX/issues/2188. However, as a quick interim solution we should instead lock the NICOS ActiveMQ so that it can only be written to by localhost.

**Comment by Tom-Willemsen** [comment]
I think this is already done. See https://github.com/ISISComputingGroup/nicos-core/blob/9312e1577efafcfeff39c169c22782ebd2543eca/custom/IbexInstrument/setups/special/daemon.py

I've added https://github.com/ISISComputingGroup/IBEX/issues/3022 to look at configurable security (this is not part of the minimum viable product as oer discussion with @John-Holt-Tessella and @DominicOram )
