### ISSUE TITLE
GUI: Allow user to control NICOS queue

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2544]
As a user I would like to be able to modify the script queue. I should be able to:
* Remove things from the queue (technically this is done in NICOS by marking scripts to skip)
* Modify the contents of a script that is on the queue
* Reorder the queue

Removal is already implemented in the NICOS backend. The other actions may involve some more clientside logic.

**Comment by davidkeymer** [comment]
It was decided to create another ticket to cover the modification of a script in the queue as it involves using a NICOS command that is not fully implemented in our current version.

**Comment by Tom-Willemsen** [comment]
Once merged into E3, let me know and I will merge master E3 with master E4.
