### ISSUE TITLE
MERLIN: Install IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2549]
As a developer and scientist, I want IBEX installed on MERLIN before the start of Cycle 2017/02, so that I can use it control my instrument.  

#### Acceptance Criteria
1. IBEX installed and configured on MERLIN
1. New version of ISISICP installed on MERLIN
1. Confirmation that Java auto-update is switched off
1. Confirmation that I can use IBEX to control devices on MERLIN
1. Demonstrate working instrument to scientist

#### Notes
1. Cycle 2017/02 starts on Tuesday, 19th September 2017.
1. MERLIN currently uses 5-digit run numbers.  To use IBEX, 8-digit numbers are required.  Which implies the ISISICP needs to be upgraded (see #2354).

**Comment by John-Holt-Tessella** [comment]
Going to check it work with Helen

**Comment by FreddieAkeroyd** [comment]
I don't believe the ISISICP has been updated (item 2. above)

**Comment by AdrianPotter** [comment]
Just waiting for the Galil to be switched over to ethernet. Delayed because the crate is currently in a CDM.

@FreddieAkeroyd, how do we go about updating ISISICP?

**Comment by AdrianPotter** [comment]
ISISICP update has now been completed. Correct @FreddieAkeroyd?

I just need to log in to set a deadband on their Galils

**Comment by AdrianPotter** [comment]
Done. I've documented the steps for setting deadbands in the developers manual. We've made several trips down to Merlin to confirm everything is working as expected.

**Comment by Tom-Willemsen** [comment]
Merlin have been using IBEX for a few days now. This can be considered complete.
