### ISSUE TITLE
ENGIN-X: Install IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2550]
As a developer and scientist, I want IBEX installed on ENGIN-X before the start of Cycle 2017/02, so that I can use it control my instrument.  

#### Acceptance Criteria
1. IBEX installed and configured on ENGIN-X
   - [ ] may not be required, but check homing positions (see #2471)
1. Confirmation that Java auto-update is switched off
1. Confirmation that I can use IBEX to control devices on ENGIN-X
1. Demonstrate working instrument to scientist

#### Notes
1. Cycle 2017/02 starts on Tuesday, 19th September 2017.

**Comment by Tom-Willemsen** [comment]
Changes from ticket 2471 are not required for this instrument because Engin-X only have linmots and linmots don't home.

**Comment by Tom-Willemsen** [comment]
Installed. Email sent to scientists to let them know everything is ready.

**Comment by John-Holt-Tessella** [comment]
- [ ]  Check names on JAWS set names for JAW 2 East and West seem to be called JAW 3 and JAW 4
