### ISSUE TITLE
All Instruments: Upgrade IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2551]
As a developer and scientist, I want the lasest version of IBEX installed on my instrument before the start of Cycle 2017/02.

#### Acceptance Criteria
1. Latest version of IBEX installed and configured on each target instrument listed below
   - [ ] includes updates to homing positions (see #2471)
1. Confirmation that Java auto-update is switched off
1. Confirmation that IBEX can correctly control the instrument
1. Demonstrate working instrument to scientist

#### Target Instruments
   - [x] DEMO
   - [x] ALF
   - [x] HRPD
   - [x] IMAT
   - [x] IRIS
   - [x] LARMOR
   - [x] LET
   - [x] MUONFE
   - [x] POLARIS
   - [x] SANS2D
   - [x] VESUVIO
   - [x] ZOOM

#### Notes
1. Cycle 2017/02 starts on Tuesday, 19th September 2017.

**Comment by KathrynBaker** [comment]
Can we add SANS2D to this list, it is using a very old version of the IBEX Server and would benefit from some of the changes that have been made to things like the start scripts (it still uses start_inst not start_ibex_server)?

(Asked as a question to gain agreement, rather than to assume)

**Comment by kjwoodsISIS** [comment]
Good suggestion!  I agree.  The fewer versions we have out in the field, the better.  I have added it to the list (on the assumption that this is not a controversial addition).

**Comment by ChrisM-S** [comment]
ditto NDXLET? (I'm guessing that it might require some of Freddies SKF chopper fixes?)
