### ISSUE TITLE
IBEX Training

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2552]
As scientist, I want to attend an IBEX training session, so that I can use IBEX to control my instrument.  

#### Acceptance Criteria
1. [x] IBEX installed and configured on training PCs
1. [x] Training delivered

#### Notes
1. Training session is scheduled for w/c 4th September.

**Comment by AdrianPotter** [comment]
See also #2250 and #2258

**Comment by AdrianPotter** [comment]
I'd just like to write up the notes from the session but I left my notepad at home so will finalise on Monday

**Comment by AdrianPotter** [comment]
- Created tickets for reported issues
- Updated #2258 with slide improvements

**Comment by kjwoodsISIS** [comment]
Reported issues: tickets created - confirmed.
Slide improvements: ticket updated - confirmed
