### ISSUE TITLE
genie_python Training

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2553]
As scientist, I want to attend an genie_python training session, so that I can use genie_python with IBEX to control my instrument.  

#### Acceptance Criteria
1. [x] genie_python installed and configured on training PCs
1. [x] Training delivered

#### Notes
1. Training session is scheduled for w/c 4th September.

**Comment by AdrianPotter** [comment]
I'd just like to write up the notes from the session but I left my notepad at home so will finalise on Monday

**Comment by AdrianPotter** [comment]
- Created tickets for reported issues
- Updated #2258 with slide improvements

**Comment by kjwoodsISIS** [comment]
Reported issues: tickets created - confirmed.
Slide improvements: ticket updated - confirmed
