### ISSUE TITLE
NDXSELAB: Install IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2554]
As a developer and electronics technician, I want IBEX installed on NDXSELAB, so that I can use IBEX to test electronic devices.  

#### Acceptance Criteria
1. IBEX installed and configured on NDXSELAB
   1. Create one (or more) initial configs and synoptics
   1. Create a config & synoptic for the new IEG device (see #2469)
1. Confirmation that I can use IBEX to control devices on NDXSELAB
1. Demonstrate working instrument to the electronics technicians
1. Demonstrate to the electronics technicians how to switch between SECI and IBEX

#### Notes
1. NDXSELAB is a control server located in the electronics lab
1. The electronics technicans have to be able to run both SECI and IBEX.
1. The first device to be tested using IBEX is the new ISIS Exchange Gas (IEG) device (intended for IRIS) (see #2469).
   1. Need to test the IEG before start of cycle, so try to install IBEX on NDXSELAB before start of September.
1. Electronics technicians might find SDTEST to be useful.

**Comment by Tom-Willemsen** [comment]
I checked via the "backdoor" that IBEX client and server are both installed, and they appear to have at least one configuration and synoptic.

However acceptance criteria 1.2 states that they should have a config & synoptic for the IEG device, but I can't find any reference to it in their existing config.

Can I also query why the "Blank" configuration isn't actually blank but contains a Lakeshore (336)?

Also, have acceptance criteria 3 & 4 been addressed (demo to the technicians) or does this still need to be done?

**Comment by kjwoodsISIS** [comment]
> From: North, Matt (STFC,RAL,ISIS) 
> Sent: 12 September 2017 10:11
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Willemsen, Thomas (Tessella,RAL,ISIS)
> Subject: RE: NDXSELAB / IBEX 
> 
> Morning Kevin/Tom,
> 
> NDXSELAB will be in use over the next couple of days. I will contact Tom when it is 
> free again; at the moment that is scheduled for Thursday.
> 
> Thanks,
> Matt
> 
>> From: Woods, Kevin (Tessella,RAL,ISIS) 
>> Sent: 12 September 2017 09:00
>> To: North, Matt (STFC,RAL,ISIS)
>> Cc: Willemsen, Thomas (Tessella,RAL,ISIS)
>> Subject: RE: NDXSELAB / IBEX 
>> 
>> Hi Matt,
>> 
>> We’ve installed IBEX on NDXSELAB.
>> 
>> All that remains to be done is to 
>> 1.	create a configuration & synoptic view to support the IEG
>> 2.	show you how to switch between IBEX and SECI.
>> 
>> Tom (cc’d) is ready to do these final jobs.  Who should Tom contact to get these two tasks completed?
>> 
>> Kevin

**Comment by AdrianPotter** [comment]
Saw Jaimie when visiting the electronics lab. They've already started using IBEX having installed it on Monday.

**Comment by Tom-Willemsen** [comment]
In that case, I'm happy to call this ticket complete. If they need help setting up the IEG device then that's fine, but it looks like they're feeling confident enough to set things up by themselves...

**Comment by kjwoodsISIS** [comment]
I would like explicit confirmation that the IEG is working correctly.  The Electronics team need to confirm that the IEG is working before they install it on IRIS (for the start of Cycle 2017/02).  I don't want them to be delayed because of something we could solve for them in 5 minutes.  Can we plase make sure we visit them tomorrow (Thursday, 14th Sept).
