### ISSUE TITLE
RIKEN-FE: Install IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2555]
As a developer and muon scientist, I want IBEX installed on RIKEN-FE, so that I can use it control the RIKEN front end.  

#### Acceptance Criteria
1. IBEX installed and configured on RIKEN-FE
1. Confirmation that I can use IBEX to control devices on RIKEN-FE
1. Confirmation that Java auto-update is switched off
1. Demonstrate working instrument to the muon scientists

#### Notes
1. This ticket cannot be started until the server to host RIKEN-FE is purchased and delivered.
   1.  Now done:
   - [x] [ControlsWork: Create a new instrument VM "NDXRIKENFE"](https://github.com/ISISComputingGroup/ControlsWork/issues/298)
   - [x] [ControlsWork: Purchase a new host server for the RIKEN front end VM](https://github.com/ISISComputingGroup/ControlsWork/issues/299)
1. Ideally, the muon scientists would like the new server before the start of Cycle 2017/02 (Tuesday, 19th September 2017), but obviously that is dependent on other events.
1. Our working assumption is that the new host server is to be called "NDHRIKENFE" and it will run a VM called "NDXRIKENFE".  May need to check the name.

**Comment by KathrynBaker** [comment]
NDXRIKENFE now exists.
