### ISSUE TITLE
Release: Create IBEX 4.0.0

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2556]
As a developer, I want to create release 4.0.0 of IBEX.  

#### Acceptance Criteria
1. Create release candidate
1. Perform any manual system tests
1. Make successfully tested release candidate available.

#### Notes
1. None.

**Comment by Tom-Willemsen** [comment]
The release has been created, the tests have been done and the release is being deployed. I don't think there's anything more that can be reviewed for this ticket.
