### ISSUE TITLE
ARACCESS: Write log file on demand

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2566]
As an ENGIN-X instrument scientists I would like to see my log file at an arbitrary time during the run.

We chose to implement this by writing the log file continuously when logging was on. The log is current to either the last sample written to the database or the current time - delay (which was 90s).

Acceptance Criteria:

1. A log file called `<ioc_name>/<ioc name>_<logging start>_continuous.dat` is created in the log directory (`c:\logs`) when the logging is switched on
1. If logging is on when the archive access starts the log is written up to current time
1. If logging is on araccess goes down and comes back up file is rewritten to avoid any problems.
1. After this log is kept up to date to current time.
1. Database disk access is reasonable

Let Engin-X know when this ticket is done

**Comment by FreddieAkeroyd** [comment]
Re 5. and with the snapshot time appended in case multiple snapshots are donw

**Comment by John-Holt-Tessella** [comment]
Original read:

>As an ENGIN-X instrument scientists I would like to see my log file at an arbitrary time during the run.
>
>Acceptance Criteria:
>
>1. A PV can be specified as a snap shot pv using an info record in the db field
>1. When the snapshot PV becomes non zero and then returns to zero then a snap shot log file is created
>1. The snap-shot file contains the data from the start of the last log start to the time of the snap shot
>1. If the PV becomes disconnected this is the same as zero
>1. The snap shot filename should be the same as the current log file but with snapshort-<snapshot time> appended
>1. Database disk access is reasonable
>
>Let Engin-X know when this ticket is done

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/143

**Comment by John-Holt-Tessella** [comment]
LARMOR MYSQL dump is a good source of big database.
