### ISSUE TITLE
SKF Chopper: check chopper parking

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2567]
I see the following in the log for the SKFChoppers
 
[2017-05-10 16:38:56] dbLoadRecords("C:/Instrument/Apps/EPICS/support/SKFChopper/master/db/SKFChopper.db","P=IN:IMAT:SKFCHOPPER_02:,CHOP=c2,NAME=CHOPPER1_DISC2,OPEN=127.8,CLOSED=307.8") 
[2017-05-10 16:38:56] Can't set "IN:IMAT:SKFCHOPPER_02:PARK:POSN:SP.ZRVL" to "127.8" 
[2017-05-10 16:38:56] Error at or before ")" in file "C:/Instrument/Apps/EPICS/support/SKFChopper/master/db/SKFChopper.db" line 277 
[2017-05-10 16:38:56] Can't set "IN:IMAT:SKFCHOPPER_02:PARK:POSN:SP.ONVL" to "307.8"

it looks to be setting a float value in an mbbo, only an integer is allowed there. It seems that the float bit gets truncates, so it will send 127 to park @davidkeymer is that OK or do things need doing differently? If it is OK, then probably better to remove the decimal points and make a note in comments near the DB  record.

**Comment by kjwoodsISIS** [comment]
@davidkeymer : what is happening with this ticket?

**Comment by davidkeymer** [comment]
It may be sufficient to round the two parking angles to the nearest integer (i.e. 128 and 308 degrees).  Need to check with Tim Carter who's on leave at the moment.

**Comment by davidkeymer** [comment]
Tim Carter contacted and now awaiting his reply.

**Comment by davidkeymer** [comment]
Rob Bewley of LET was also consulted.  The consensus between him and Tim is to alter the driver to allow it to send floating point values for the parking angles, which I shall now investigate...

**Comment by FreddieAkeroyd** [comment]
mbbo can only do integers, if you only need 1 decimal place you could multiply all values by 10 and then send them to an analogue output record where you scale by 0.1 before sending to the device

**Comment by FreddieAkeroyd** [comment]
Actually you'll need to use a calc record, I'd forgotten that though you can scale in analogue output it will then round to an integer to send :-(

**Comment by davidkeymer** [comment]
Pull Requests:
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/48
https://github.com/ISISComputingGroup/EPICS-ioc/pull/212
https://github.com/ISISComputingGroup/EPICS-SKFChopper/pull/7

**Comment by ThomasLohnert** [comment]
Everything works fine, as discussed the only thing needed for rework is to fix the Park Open/Closed buttons in the OPI to show the proper angles again.

**Comment by davidkeymer** [comment]
Have made required changes and some other small modifications.

Pull request:
https://github.com/ISISComputingGroup/ibex_gui/pull/632
