### ISSUE TITLE
Merlin: Convert tcb_generator

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2568]
As a Merlin instrument scientist, I would like my instrument scripts to be independent of 3rd party programs  so that I can see all of the logic involved in their execution and maintain them easily.

## Acceptance criteria

- [ ] The Merlin instrument scripts act independently of external executables (namely tcb_generator_multi.exe, see below)
-  [ ] Tests exist for the new scripts that verify the output matches that of the original executable
- [ ] The new script can be run independently of the existence of LabView Modules

## Notes

Merlin currently use an executable for generating TCB parameters. It's originally written in Fortran. I've obtained the source code from Tony Perring.

The executable is problematic for a number of reasons. It's difficult to change, verify and test. Functionally as well, the current executable relies on hard-coded LabView file locations which won't work in the long run once we fully migrate away from SECI.

There are a few hundred lines of code. There's significant duplication. Most of it is very simple arithmetic and may condense down significantly in Python.

Make sure there are tests in place for the converted code and use some sample data generated from the original executable to verify  that it does the correct thing. Talk to Helen Walker to get some suitable input data

**Comment by Tom-Willemsen** [comment]
Try to compile the existing source (pair with @FreddieAkeroyd)

**Comment by Tom-Willemsen** [comment]
Have a discussion about whether we should actually take this on, and if so, to what extent. The instrument scientists on the relevant instruments (MERLIN, MAPS, LET, others?) and Tony Perring should probably be involved in this discussion.

Options include (not an exhaustive list...):
- Science code, instrument scientists to maintain it
- We provide a way to compile it but scientists maintain the source
- We take on "full" maintenance of the Fortran source
- We take on "full" maintenance of the code and convert it to Python

Impeded awaiting resolution of the above.

**Comment by FreddieAkeroyd** [comment]
-ffixed-line-length-132 and -fdec compiler flags needed, the common block warning is fine and due to 3 inetger*4 values being followed by a real*8 which requires padding to avoid alignment issues (re-ordering items in the common block would remove the warning).   Not sure if   -finit-local-zero -fno-automatic  will be needed too

**Comment by FreddieAkeroyd** [comment]
I've emailed Helen Walker Re: support of the code, she said she would check with the rest of the group

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd : any news from Helen?

**Comment by FreddieAkeroyd** [comment]
@kjwoodsISIS no, I will chase

**Comment by Tom-Willemsen** [comment]
Any further news on this? It's been 'impeded' for a long time now.

**Comment by FreddieAkeroyd** [comment]
Helen talked to Toby and he is going to merge the various fortran programs into one, then we will revisit

**Comment by AdrianPotter** [comment]
Can this be moved into won't fix if there's no defined work to be done?

**Comment by kjwoodsISIS** [comment]
Yes, I agree.  Let's create a new ticket when the new Fortran program has been created.
