### ISSUE TITLE
Dataweb: fix

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2569]
IBEX overview page is currently broken, I suspect it has something to do with the following python errors in the logs:

`2017-09-05 16:15:09,586 Failed to get data from instrument: MUONFE at NDEMUONFE error was: local variable 'blocks_all' referenced before assignment`

`2017-09-05 15:27:59,226 Failed to get data from instrument: ZOOM at NDXZOOM error was: local variable 'config' referenced before assignment`

**Comment by KathrynBaker** [comment]
Interestingly, at the moment MUONFE isn’t running IBEX, in fact I’m not sure it is running, as I restarted it yesterday afternoon (probably at about 16:15) and today I can’t remote desktop to it… That is being dealt with (hopefully).

**Comment by Tom-Willemsen** [comment]
Unclear exactly why the errors occured. Possibly because of some unusual condition. I've put extra logging on the webserver (committed to master and deployed). This ticket can be considered complete for now and we'll create a separate one if the issue reoccurs.
