### ISSUE TITLE
Tidy up configurations area

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2576]
This ticket is to make sure that instrument branches are mergable from master
 
On each instrument:
* shutdown instrument
* check "git status" shows all added and pushed
* Check git settings as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)#setting-up-a-configurations-directory are correct
* check "git status" again
* Compare instrument settings branch to master and look at merging master into it (careful!)
* It is possible some line endings will have been corrected, look at what needs committing etc.

**Comment by KathrynBaker** [comment]
I believe this is covered by the config checker, closing
