### ISSUE TITLE
IOC: TPG Sensor numbers

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2578]
As an instrument scientist I may only connect one sensor to my TPG26x and TPG300 in this case I do not want an alarm for sensor not connected.

**Comment by DominicOram** [comment]
As part of this ticket I would also like the OPI to:
* Only show the connected sensors
* Be updated to the modern style

**Comment by John-Holt-Tessella** [comment]
+1 HRPD scientist

**Comment by Alistair-McGann-Tessella** [comment]
Also consider changing the OPI to only graph the connected sensor

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/ibex_gui/pull/769
https://github.com/ISISComputingGroup/EPICS-ioc/pull/305
https://github.com/ISISComputingGroup/EPICS-TPG/pull/6
