### ISSUE TITLE
Improve component detail types

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2579]
As a user, when I am adding components to a synoptic, I would like the types to be grouped by the overall class of device so that I can intuitively find the device I'm looking for. I do not want the type to be for a specific model, manufacturer, or in developer-speak.

This arose as part of the September round of IBEX training.

At the moment, the type of a device is set in the component details pane. The list of types is derived from the keys used in the opi_info.xml. This has several issues:

1. Keys are frequently chosen to be overly concise. (e.g. "CCD100", "KHLY2400")
1. They are in caps case with inconsistent word separation which is not user-friendly (e.g. "SINGLESTAGE", "MOTIONDETECTORSYSTEM")
1. They are inconsistently sometimes named after the manufacturer (e.g. "KEPCO", "JULABO", "LAKESHORE"), other times after the device function (e.g. "JAWS", "POLARISER") and at others after specific devices (e.g. "LINKAM95", "CCD100", "KHLY2400")

We should decide how components are classified and use it in a consistent, intuitive, user-friendly way.

## Acceptance criteria:

- [x] Component details types are self-consistent
- [x] For a given device (e.g. Keithley 2400), a user can easily find the type of component they should set

**Comment by Tom-Willemsen** [comment]
Change training slides once this ticket is complete.

**Comment by DominicOram** [comment]
Does this fix https://github.com/ISISComputingGroup/IBEX/issues/2269?

**Comment by Tom-Willemsen** [comment]
Yes I think so.

**Comment by AdrianPotter** [comment]
Looks good. The system tests just need a quick tweak because the `clear` button has moved.

**Comment by Tom-Willemsen** [comment]
System tests fixed.
