### ISSUE TITLE
Allow dashes in PVs

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2580]
As a user, I want PVs to be able to have dashes in them so that core IBEX functionality works on PCs at the CDF.

The default machine naming for the CDF includes dashes (e.g. CDF-CAD3). We could ask CDF not to do that but:

1. Dashes are common among machine names
1. IBEX will mostly work with dashes in the machine name

Having discussed with Freddie, there's no reason PVs shouldn't be able to have dashes. Blocks can't because we use them as variable names in genie_python.

PVs are disallowed from having dashes when you try to create a block with a dash in the PV, or when you add a PV to a synoptic component. This isn't technically blocking since:

1. You can create a block without the PV prefix. If the PV prefix has a dash, you just leave it out and let IBEX add it for you. The block then functions normally
1. The synoptic dialog gives an error message about adding badly formatted PVs but doesn't actually stop you from saving the synoptic regardless

In spite of the above, the functionality is both overly restrictive and inconsistent. We should fix it.

There is an additional issue on machines with a dash in the name that the Python settings needs an `init_*.py` file both with the dash and without. This should be fixed at the same time.

## Acceptance criteria

- [x] You can add a block to a config with a dash in the PV
- [x] You can add a PV to a synoptic component with a dash in the PV
- [x] You still can't have a dash in a block name
- [x] Scripting using the `inst` prefix works on a machine with a dash in the name. At the moment it seems to require both an `init_*.py` file both with the dash and without

**Comment by John-Holt-Tessella** [comment]
Also change instrument prefix so that it does not include spaces. This needs to be added to:

1. GUI
1. back end
1, genie_python
