### ISSUE TITLE
Don't allow opening an OPI from the synoptic preview

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2583]
As a user, I don't want to be able to open an OPI from the synoptic preview so that I'm not confused when it opens a potentially incomplete OPI in the main viewer.

This came up in the September IBEX training. I'm calling it a bug, it might be a feature.

When you create a synoptic, there's a button called `Synoptic preview` which lets you see what your synoptic will look like. However, all of the controls in the preview are live. This includes:

- Opening an OPI in the main window
- Changing writable PVs

My impression is that a preview shouldn't let you do that.

## Acceptance criteria

- [x] Clicking a component in the synoptic preview doesn't open an OPI
- [x] Changing the value of a writable PV in the synoptic preview changes its value in the preview but doesn't write the value to the PV

**Comment by John-Holt-Tessella** [comment]
There is a duplicate ticket somewhere. Did we want to remove synoptic preview entiterly?

**Comment by AdrianPotter** [comment]
Awaiting instrument scientist responses

**Comment by AdrianPotter** [comment]
So far I've only received 1 response, from Ron Smith, saying they don't use it. I suggest we merge this. If a reply comes in with a strong objection, it's a simple change to revert.

**Comment by AdrianPotter** [comment]
I've reinstated the synoptic preview since Rob says he uses it exactly for previewing the synoptic. It's functionality that can't be achieved any other way. He doesn't use it to open OPIs or set PVs so this ticket should still be fixed.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/736
