### ISSUE TITLE
Eclipse 4 migration [TIMEBOX: 8d]

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2587]
Continuation of the Eclispe 4 migration task. Details to be filled in upon completion of #2547

**Comment by John-Holt-Tessella** [comment]
Branches that should be reviewed:

**Comment by DominicOram** [comment]
Please may someone review:
* https://github.com/ISISComputingGroup/ibex_gui/pull/576
* https://github.com/ISISComputingGroup/ibex_gui/pull/575
* https://github.com/ISISComputingGroup/ibex_gui/pull/574
* https://github.com/ISISComputingGroup/ibex_gui/pull/573

**Comment by ThomasLohnert** [comment]
- [ ] Motors: https://github.com/ISISComputingGroup/ibex_gui/pull/578

**Comment by AdrianPotter** [comment]
- [ ] Device screens: https://github.com/ISISComputingGroup/ibex_gui/pull/569
- [ ] Script generator: https://github.com/ISISComputingGroup/ibex_gui/pull/582

**Comment by John-Holt-Tessella** [comment]
Merge in motors and synoptics

**Comment by John-Holt-Tessella** [comment]
- [x] Nicos Scripting : https://github.com/ISISComputingGroup/ibex_gui/pull/572
