### ISSUE TITLE
Run Control: Precision display

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2596]
As a scientist I would like run control to display the precision of the limits I have set using the same logic that is used when displaying blocks

**Comment by Tom-Willemsen** [comment]
Just make the runcontrol dialog reflect what is in `...:CS:BLOCKSERVER:GET_RC_PARS` (i.e. don't truncate to integer)

**Comment by Tom-Willemsen** [comment]
Actually this seems to be a backend issue rather than GUI - `...:CS:SB:blockname:RC:LOW.PREC` is being set to zero from somewhere. Not sure where yet - doesn't seem to be the blockserver.

**Comment by Tom-Willemsen** [comment]
Was already fixed by https://github.com/ISISComputingGroup/EPICS-RunControl/commit/b6a7ae5b53f8ba53af650c11a9201d35a5a36d1e , I didn't realise those changes had already been made.
