### ISSUE TITLE
HOTFIX: CAEN support in release 4.0.0

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2603]
The update to EPICS base 3.15 introduced an issue with the CAEN that results in failure with:

Bad init_rec return value  PV: IN:SANS2D:CAEN:hv0:1:1:rampup ao: init_record

messages. The following commits need to be cherry picked, recompiled, and new support/HVCAENx527and ioc/master/HVCAEN directories installed: 

https://github.com/ISISComputingGroup/EPICS-HVCAENx527/commit/1c05afe8a71adc34992ef15b3c2c48e2cd0c4fcd

https://github.com/ISISComputingGroup/EPICS-ioc/commit/40c79137790998e39930075c41e78856e1b407b8

The directories can be copied from a recent EPICS_CLEAN build such as 
\\isis\inst$\Kits$\CompGroup\ICP\EPICS\EPICS_CLEAN_win7_x64\BUILD-1626

This will be tested on SANS2D but LARMOR will also need updating

**Comment by KathrynBaker** [comment]
Updated on SANS2D and on LARMOR, IOCs working again
