### ISSUE TITLE
Mk3Chopper: Create a PV and add to OPI to show in local/remote

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2605]
As a user, I would like to know if the chopper crate is set to local mode.
If it is in local mode then the IOC cannot retrieve the values for the PV.

There is a command in the support library called GetComputerMode which returns False when in local mode and True when in remote.

This needs to be added to the IOC and the OPI.

Unfortunately, you cannot switch modes remotely though; it is a case of wandering down to the crate.

**Comment by Tom-Willemsen** [comment]
This would be a good candidate to pair program with @mattclarke 

Additionally, the MK3 chopper only builds using visual studio 10 which I think only runs on Windows 7.

**Comment by kjwoodsISIS** [comment]
I know this is scope creep ...
but, is it worth considering implementing either #2575 or #2572 (or both) at the same time? (e.g. if either ticket is quick).

**Comment by AdrianPotter** [comment]
Other tickets are not quick. I've factored out the macro numbers but uncoupling from the LabView Modules goes deep into the driver into a precompiled DLL that I don't see the source for. Would need to talk to @mattclarke  about this.

The disconnected ticket needs updating the driver with the correct EPICS error code for a disconnected PV. I couldn't find this anywhere in the online documentation. @FreddieAkeroyd might know where to look. Again, not quick so I haven't done it as part of this ticket.

**Comment by FreddieAkeroyd** [comment]
There is "disconnected" as in PV does not exist, but I'm not sure that is what you mean? And I'm not sure you can do that normally - maybe with access control. Do you just want to alarm the PV and change its readback to something non-reasonable? If its a string you can say "disconnected" as the value.

**Comment by AdrianPotter** [comment]
Thanks for the update. I think I'll leave this outside of the "quick and easy" category. It doesn't seem like it should be too difficult but I think there are a few options for the implementation that should probably be discussed on that ticket and not this one.

**Comment by John-Holt-Tessella** [comment]
Can only review if yo uhave visual studio 2010 on your desktop
