### ISSUE TITLE
DAE: RBNumber being resetlost

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2606]
As a POLARIS instrument scientist I want my RB number to be saved between restarts of ibex client and ibex server (if possible).
As a developer I want to check where this is stored and whether it is being retrieved correctly.

Reproduce (Ron told us):

set users and rb number
restart (and possible reinstall ibex server)
rb number gets reset to first rbnumber in current cycle list

If it can not set it reliably it needs to be blank but I expect it is trying to do something under the hood.

**Comment by KathrynBaker** [comment]
The RB Number is no longer getting lost in this scenario.
