### ISSUE TITLE
EPICS base log client: do not add error log listener in all cases 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2611]
It looks like a bug was introduced in base 3.15 whereby all "log clients" become error log listeners, this was not true in 3.14 Unfortunately this means that all ioc log messages also get sent down the putlog route which has caused issues.

acceptance criteria:

currently ioc error messages and messages from isiscip on run begin appear in _putlog.txt, after fix this should not be the case - just "changed pv" messages

**Comment by John-Holt-Tessella** [comment]
This change is in 4.0.1.
Code looks good as far as I can see can we generate two tests:

- [ ] Check contents of put log is only of the form `2017-09-07T09:02:53	Changed PV: TE:NDW1798:CS:PS:RUNCTRL_01:START new=0 old=0 `
- [ ] Check that a put appears in the putlog

Also

- [ ] Post and analysis tech talk reply to why this changed

**Comment by FreddieAkeroyd** [comment]
The test requires multiple components, so I guess should be a system test via RCPTT?
