### ISSUE TITLE
GUI: MCR news update is slow

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2618]
As a Merlin instrument scientist, I would like the MCR news to update within a minute so that I can be immediately informed of items on the MCR news.

Helen Walker reported that the MCR news update on Merlin was a good 13 minutes behind the MCR news alerts she received on her phone. She would like IBEX to be more punctual. We should determine where the source of delay is.

Is this anything to do with replication delay now facilities have moved around the servers?

## Acceptance criteria
- [ ] MCR news in IBEX updates within a minute of it appearing on the main MCR news.
** OR**
- [ ] We have a good explanation of why our MCR news lags behind phone updates

**Comment by FreddieAkeroyd** [comment]
we are using https://www.isis.stfc.ac.uk/gallery/mcrnews.txt from the new isis web site, I've sent them a query as to how often it is updated

**Comment by KathrynBaker** [comment]
This has not been raised since, closing
