### ISSUE TITLE
GUI: Error loading tables

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2619]
As an ALF instrument scientist, I would like the list of tables in the DAE data acquisition tab to not fail to load.

We had an issue on ALF whereby several of the table lists did not load and gave the message "Error: Could not load table list from instrument" (slight paraphrase). I restarted the GUI and the issue went away. Probably a race condition. Hard to reproduce and we might not see it again. This ticket is just to track in case we get more reports of the issue in the future

**Comment by Tom-Willemsen** [comment]
> This ticket is just to track in case we get more reports of the issue in the future

7 years later, no comments mentioning reoccurences, closing.
