### ISSUE TITLE
GUI: Warn on creation of a block pointing at an SP or SP:RBV

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2620]
As a developer or instrument scientist I want to be warned if I create a block which points at a non-standard pv. Such non standard places are:

`<pv name>:SP` - warning is something like "Block should usually point at the measured quantity. Doing cset on the block will set the SP value if it exists"
`<pv name>:SP:RBV` - warning is something like "The setpoint value read back from the device is not a measurement of the value but the value the device is trying to get to."
`CS:SB*` - warning is "This is an IBEX internal pv are you sure you want a block pointing at it?"

I am imagining warning triangles with tool tips on the blocks page but this is not the only implementation.

Acceptance criteria

1. Setting a block to point a bad pv issues a warning
1. Setting multiple blocks to point at multiple bad pvs issues multiple warning
1. The block can still be set to any pv
1. The warning do not get in the way of errors

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/731
