### ISSUE TITLE
Upgrade: Ensure configs and components do not contain invalid IOC [Timebox to 2d]

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2627]
As an Instrument I should only have valid configurations or synoptics so that if I load a configuration or somehow create an invalid configuration it is flagged. This should be a Jenkins job which runs daily to check the current config.

This ticket has 2 days so get as far as possible:

1. Check that latest checked in configs does not contain ISISDAE_01, INSTEC_01
1. Generate a current list of acceptable ioc names and check these are the only IOCs in the configurations
1. Check that only valid IOCs are in components
1. Check that only valid OPIs are in synoptics
1. Check that all configurations are being pushed (may not be possible)
1. Check that only expected files are in configuration directories
1. Any other validity checks

**Comment by Tom-Willemsen** [comment]
I've just been through all the instruments and done a `git checkout NDXxxx && git pull && grep -r INSTETC && grep -r ISISDAE` to check that none of the instruments have these items in their configs anymore. The only results were the expected `_base` components and a few old backups on LARMOR.

**Comment by John-Holt-Tessella** [comment]
Originally said:

As an Instrument I should not have certain iocs in my config. As an upgrade remove these changes and ensure they are in base components instead.

IOCS to remove:

 - ISISDAE_01
 - INSTEC_01

Acceptance criteria:

1. After upgrading configurations and components no longer contain bad iocs
1. After upgrading base components do contain those IOC.

**Comment by kjwoodsISIS** [comment]
Are the backups on LARMOR a potential source of future contamination? (i.e. could restoring one of these backups re-introduce the problem).  If so, we should probably remove these particular backups from LARMOR (with Rob's agreement).  We could keep copies of these backups somewhere else (just in case Rob ever wants something back from one of them).

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-configchecker/pull/1
