### ISSUE TITLE
GUI: Groups intermittently duplicated

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2634]
Groups in the GUI are sometimes duplicated i.e. instead of the blocks panel showing two groups GROUP_1 and OTHER, it would show GROUP_1, OTHER, GROUP_1, OTHER. 
This happens only very intermittently (in the region of once every ~20 startups). After having a brief look, it seems like the groups are already duplicate at the point they are read from the `GET_CURR_CONFIG_DETAILS` blockserver PV.

(Observed on the E4 branch in case that matters)

**Comment by AdrianPotter** [comment]
I haven't seen this at all recently. Do we think this is resolved?

**Comment by Tom-Willemsen** [comment]
I also haven't seen it recently. Based on that I think this can be closed. It can be reopened if we see this issue again.
