### ISSUE TITLE
block gateway crash with array blocks

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2635]
This came up on LARMOR when a waveform array was split to allow blocks to be added. The array was split using subarray, but from a gateway point of view a subarray still looks like an array, and this then seemed to cause the block gateway to continually crash when a block was added pointing at the array. Needs to check if this is reproducible

**Comment by KathrynBaker** [comment]
This is from a long time ago, and can be reopoened if this is still the case.
