### ISSUE TITLE
SUPPORT: hide startseci better on IBEX machines

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2639]
On IBEX migrated computers:
- automatic starting of SECI should be disabled
- the start seci shortcut should be moved off the Start menu (i.e. away from directly next to the genie_python shortcut) to somwhere in say a folder accessed off the start menu. It still needs to be accessible for a while.  

These notes should be added to instrument migration/ibex install and also done on existing instruments.

**Comment by John-Holt-Tessella** [comment]
Can we add this to the system checks. Did we want to start IBEX on those 
machines on reboot?

Cheers,

John

John Holt 
Consultant

Email: John.Holt@tessella.com
Telephone: (+44) (0)1235 429 094
Skype: john.holt.tessella

26 The Quadrant, Abingdon Science Park, Abingdon, Oxfordshire, OX14 3YS
Tessella is part of the Altran Group - www.tessella.com 

Please consider the environment and do not print this e-mail unless you 
really need to. 

This message is commercial in confidence and may be privileged. It is 
intended for the addressee only. Access to this message by anyone else is 
unauthorised and strictly prohibited. If you have received this message in 
error, please inform the sender immediately. Please note that messages 
sent or received by the Tessella e-mail system may be monitored and stored 
in an information retrieval system. Tessella is Registered in England No. 
1466429

**Comment by ChrisM-S** [comment]
It might be good to think about also giving the options of

> Automatically start IBEX if it was running when the PC stopped
> Automatically restart the last script if it was running when IBEX was stopped

This would allow shutdown, say at the end of a cycle, to persist through reboots/updates of the VM and reduce unwanted logging but once started for a cycle (i.e. not explicitly stopped), the server at least would return to continue logging values.

Hopefully we will be able to also rely on the script server to restart a script from its last checkpoint as a default so full control is restored and a nights running is not lost simply because no one restarted the script to continue changing temperatures from the time of the next step.

**Comment by FreddieAkeroyd** [comment]
I think we agreed on "restart on reboot it if was running previously" for exactly the reasons given, there may be a ticket but I haven't found it yet...

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen : did you see @KathrynBaker 's Slack post:
> kathryn [2:46 PM] 
> I'm afraid I forgot something that needs doing this sprint, there are some updates to the temp 
> sensor files that need to be deployed, which as we are aiming to take over each instrument to 
> hide the SECI access more, can I add a task to that list which is update the sensors (navigate to 
> the appropriate folder and git pull), something which should be covered by a deployment 
> normally. I'd rather not backdoor them as that will just annoy us when we do the next deployment.

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/8
