### ISSUE TITLE
Gamry Potentiostat trigger control

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2642]
Keith Allum is developing a trigger control for the Gamry potentiostat for use on IMAT. They plan to have something for testing by 9th of October.

The trigger will require an IBEX IOC / GUI for this device, but should be very simple. Contact Matt North.

**Comment by kjwoodsISIS** [comment]
Note: ticket #2535 is required for 11th October.  Need to make sure these two tickets don't clash.

**Comment by kjwoodsISIS** [comment]
> From: Kockelmann, Winfried (STFC,RAL,ISIS) 
> Sent: 27 October 2017 13:53
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Subject: RE: Gamry Potentiostat trigger control
> 
> Hi Kevin,
> 
> You are right; there is no immediate urgency anymore, as the experiment will not take place next cycle.
> 
> Coincidentally I had sent the email below to Keith Allum this morning. Keith needs to do some work; 
> then we’ll need to get the Gamry controller from UCL, before we can do the testing, before the beam 
> comes back in February. 
> 
> Best wishes
> Winfried
> 
>> Hi Keith,
>> 
>> Here is more information about the required interface for the Gamry controller. Since TS-2 is not 
> running the request is not so urgent anymore but let me know when you can do this. There’s more 
> time fort testing for the experiment on IMAT in February.
>> 
>> A) Gamry interface communication:
>> 1)	Gamry always works with a 5V signal. UCL always triggers on 5V (signal high)
>> 2)	Trigger signal length: 1 sec 
>> 3)	Input into Gamry:   to start charging/decharging cycle: use INPUT PIN 11
>> EPICS: to send trigger signal;
>> 4)	Output from Gamry after charging/decharging step: 5V signal on OUTPUT PIN 7
>> EPICS: to wait for trigger signal;
>> (Berlin adapter uses Pin 7 output / Pin 11 input)

**Comment by FreddieAkeroyd** [comment]
Hi Kevin,

Keith Allum produced an interface for us to communicate with a Gamry potentiostat which we’ll use for charging/discharging batteries; it’s for battery research on IMAT with UCL. Freddie was involved in the discussions. 

We require EPICS communication with Keith’s box, which involves sending and receiving strings via RS232 to the GAMRY.

Each Send/Receive command ends with a Carriage Return.

SEND to Interface            RETURN from interface                 Comment
1)	START01                      STARTED                                 to trigger charging/discharging process; interface confirms with 
string “STARTED”  
 
2)	                                    STOPPED                                 GAMRY has finished charging/discharging process; interface sends 
string “STOPPED” 

3)	                                    NAC                                         Not A Command; interface doesn’t recognise string


Keith has included one more (unrelated) functionality; send an EPICS command to output a TTL signal to MCP.
1)	BEAM_ON                   BEAM_ON                               send one trigger pulse (TTL high) to MCP to end run (if T0 is missing);
2)	BEAM_OFF                  BEAM_OFF                              set TTL low
3)	                                    NAC                                         Not A Command; interface does not recognise string

The interface is required for an experiment end of this cycle (23 March) or beginning of next cycle (mid April). The experiment hasn’t been scheduled yet.

I’ve got the equipment, including the UCL-GAMRY, on IMAT. 

Many thanks.

Winfried

**Comment by John-Holt-Tessella** [comment]
For testing see #3067

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella - how many points was this ticket?

**Comment by FreddieAkeroyd** [comment]
I'd call it 2 points, which includes some of the work moved into #3067
