### ISSUE TITLE
DAE: ApplyChanges button greyed out in SETUP

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2643]
Happed just now on MERLIN, appears it has also happened on ENGINX. On MERLIN starting a new clienet fixed it, on ENGINX Joe did a g.begin()   Looks like the GUI missed a monitor update on RunStatus, may be something out of our control though

**Comment by John-Holt-Tessella** [comment]
![image](https://user-images.githubusercontent.com/7570055/30903410-98a06d7a-a366-11e7-95d8-6307d8d7bc09.png)

+1 for enginx

**Comment by John-Holt-Tessella** [comment]
Instead of finding the bug it might be better to have a refresh button which reattaches to the pvs for the dae. The bug is likely to be in the pvmanager layer (although have we had this reported before, i.e. in 3.0?).

**Comment by ChrisM-S** [comment]
At the risk of pushing this, if we don't fix the bug, let's not have a refresh button but have a thread which does an auto refresh at an appropriate interval in the background to make sure the problem doesn't become a "user facing" one again.  Needing to restart/refresh things looks a bit shabby unless there is a good reason for people to want to see "historic" values on the screen before updating.

**Comment by John-Holt-Tessella** [comment]
see #2648

**Comment by Tom-Willemsen** [comment]
I fixed a race condition that might have caused this issue as part of #2584 , check if that fix solves this issue

**Comment by Tom-Willemsen** [comment]
This happened to me just now on the latest master, so the above-mentioned fix has not fixed the issue.

**Comment by John-Holt-Tessella** [comment]
Suggested approach is to use RCPTT to start and stop runs until it can not and then debug from there.

**Comment by ChrisM-S** [comment]
How fast were you able to begin and end runs @Tom-Willemsen ?

**Comment by Tom-Willemsen** [comment]
I was able to begin runs approximately once every 3 seconds, although I did have to put my ICP into "synchonous end" mode otherwise it was creating data files faster than the ICP could process them and the ICP then used 100% disk/memory and made my computer unusable.
