### ISSUE TITLE
DAE panel: all buttons greyed out

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2648]
Happened a couple of times now - all buttons are greyed out in the DAE panel, but going to the scripting windows and typing g.begin() for example brings things back to life. I'm not sure if it is the panel missing a "monitor" as I though that would lead to the wrong combination of buttons, all buttons greyed out would suggest it had in invalid/unknown runstate? The runstate as displayed in the dashboard was correct, is the logic used for the DAE buttons tied to the same underlying value used here or obtained separately? If the same value, does the dashboard behave differently for invalid value than the DAE buttons?

**Comment by John-Holt-Tessella** [comment]
see #2643

**Comment by Tom-Willemsen** [comment]
Re-reported by Ron Smith (POLARIS)

**Comment by ThomasLohnert** [comment]
Re-reported by Ron Smith again: occurred on 08/11 afternoon on POLARIS - only END RUN button was operational

**Comment by AdrianPotter** [comment]
It's not clear whether there are any issues here beyond #2643. Tom's begin/end run utility of RCPTT has well exercised the UI; it can reproduce the issue reported in #2643 and demonstrates it is now fixed. I'm closing this ticket as a duplicate
