### ISSUE TITLE
IOC: Allow setting TEMP:SP when no sensor is connected

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2653]
As a Merlin instrument scientist, I would like to be able to change the temperature setpoint for a Eurotherm channel while there is no sensor connected to the crate so that I can prevent temperature ramping being applied immediately on connecting a new sensor.

The workflow on Merlin is that they will have a particular sensor connected to a Eurotherm channel on Merlin at a given temperature setpoint. The sensor is then disconnected and the instrument setup is prepared for a new experiment. Once the old sensor is disconnected, you can no longer set the temperature set point from the OPI. That means that when a new sensor is plugged in, the Eurotherm may immediately start ramping the temperature. It would make things much easier if the setpoint could be changed to a different value before the new sensor is plugged in.

## Acceptance criteria

- [ ] The Eurotherm temperature setpoint can be set when no sensor is plugged in

**Comment by kjwoodsISIS** [comment]
Get hold of a physical Eurotherm to test this.

**Comment by mattclarke** [comment]
There is a mini one in the ibex office or it might be in the storeroom

**Comment by KathrynBaker** [comment]
There is indeed, but I don’t think ought to be detaching the sensor from it, which is going to be a necessary test for this ticket.

**Comment by AdrianPotter** [comment]
David is going to try and source one from electronics over the next couple of days

**Comment by ThomasLohnert** [comment]
The Eurotherm cannot ramp when the sensor is disconnected, but you can set the setpoint if you temporarily turn ramping off. 
After discussing with others in the team, the plan is to disable ramping when the sensor is disconnected (accompanied by an appropriate IOC log message and an indicator in the OPI) and revert to the previous setting when the sensor is reconnected. I have messaged the MERLIN scientists to check they are happy with this solution.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/194
https://github.com/ISISComputingGroup/ibex_gui/pull/588

**Comment by ThomasLohnert** [comment]
Added IOC tests: https://github.com/ISISComputingGroup/IBEX/issues/2653
