### ISSUE TITLE
GUI: Veto set points and set point readbacks are unclear

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2654]
As a Merlin instrument scientist, it is unclear to me from the experiment setup panel what the current vetos are. If I change the veto from the scripting window, the controls on the experiment setup panel aren't updated accordingly. I would like the experiment setup panel to be clearer to avoid confusion on the current state of the DAE.

If the DAE state is changed via a script, this can lead to the DAE perspective suggesting that the current DAE state is the old state, rather than the new one, causing confusion.

One solution would be to use the same data layout format as the OPIs where we present data as [Label] [SP:RBV] [SP].

## Acceptance criteria

- [ ] I can tell from the DAE experiment setup tab how the requested state of the DAE relates to the current state

**Comment by FreddieAkeroyd** [comment]
There are quite a lot of veto buttons so a separate [SP:RBV] and [SP] would take a lot of space. I'm not sure if the values come from PVs or XML - can we just display the current value in place when the tab is selected?

**Comment by KathrynBaker** [comment]
The behaviours are likely either understood or at least BAU by now. Can be reopened if necessary.
