### ISSUE TITLE
Connect GUI to Script Server

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#266]
As a support person and scientist, I want to use the GUI to select scripts for execution on the Script Server

'''Acceptance Criteria'''
1. I can select a script.
1. I can submit the script for execution
1. I can view which scripts are in the job queue
1. I can see which script is currently being executed.
1. I can see which scripts have completed and their status.

'''Notes'''
1. Scripts are Genie_Python scripts.
1. What error status indicators does the script server provide?
   1. For example: no error, warning(s) or error(s). (Perhaps?)
1. To select a script simply select the relevant .py file.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 268.  Created by skn09965 on 2014-01-16T15:16:27, last modified: 2014-05-13T16:12:17_

**Comment by AdrianPotter** [comment]
Covered by #1364. Marking as duplicate
