### ISSUE TITLE
IMAT: integrate new camera (Andor Icon-L 936)

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2662]
http://www.andor.com/scientific-cameras/ikon-xl-and-ikon-large-ccd-series/ikon-l-936

**Comment by AdrianPotter** [comment]
Talk to Freddie when you're ready to pick this up. Should be tackle-able by anyone but probably good to catch up on the story so far.

There appears to be something about an EPICS driver here: http://cars9.uchicago.edu/software/epics/andorDoc.html

I'm not familiar with the areaDetector so don't know whether that's useful.

**Comment by FreddieAkeroyd** [comment]
Current driver fails with a 20992 error code similar to that described on https://epics.anl.gov/tech-talk/2016/msg01179.php - first step will be to update area detector as per #2866 and then attach a debugger...

**Comment by John-Holt-Tessella** [comment]
Chat with @FreddieAkeroyd  see if we need to re-estimate this

**Comment by FreddieAkeroyd** [comment]
need to test on IMAT

**Comment by FreddieAkeroyd** [comment]
Tino is testing this
