### ISSUE TITLE
Tech debt: Motors perspective performance and exceptions

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2664]
Found during E4 migration: In Eclipse 4, switching between different tabs in the motor perspective is very slow. This may be down to the general performance decrease in E4, however it makes the problem very noticeable. Furthermore, the MinimalMotionIndicator class (responsible for displaying the arrow and home symbols on each motor) would intermittently throw `SWTExceptions` ("Widget is disposed").

One possible way to alleviate both problems may be to use databinding to change the arrow/home icons dynamically rather than using `asyncExec`.

(Note: it is expected that the GUI is slow the first time you open a view as it gets initialised)

**Comment by DominicOram** [comment]
Under e3:
*17:52:28.474 - TableOfMotorsView - Creating ToM part
*17:52:29.025 - TableOfMotorsView - After setMotorsTable() 
*17:52:29.041 - TableOfMotorsView - Before setMotors()
*17:52:29.525- TableOfMotorsView - End 

The first 500ms pause is the motors backend getting created and hooked to PVs (this should be done on a different thread)
The second 500ms pause is creating and wiring up each small control. Each of these takes ~10 ms and there are 64 on the screen (more databinding could help here)

**Comment by Tom-Willemsen** [comment]
No longer substantially slower than other comparable GUI operations.
