### ISSUE TITLE
Spectra plots not updating

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2668]
Ian Silverwood (IRIS) came in and reported that the spectra plots have frozen again (we thought we had put in a fix for this). On IRIS several of the spectra plots were completely blank, and the only one with data in it was frozen (i.e. the spectrum did not change when changing the spectrum number when it should have)

See screenshot below:

![image](https://user-images.githubusercontent.com/24375813/31231320-706bf8a0-a9de-11e7-826a-122ef07c1c12.png)

(All of the spectra *should* have contained some form of data)

While spectra are frozen other DAE pvs are updates.

Today we saw that the Specra were updating but the diganostic data was not (just showed no data). Restarting the GUI did not fix this; tab was enabled. 

![image](https://user-images.githubusercontent.com/7570055/32771543-e4b26748-c91a-11e7-9a7b-81ae0c103bc8.png)

If diagnostics freeze is not part of above then create a new ticket for it.

**Comment by FreddieAkeroyd** [comment]
Was it enough to just restart the client?

**Comment by Tom-Willemsen** [comment]
Yes opening a new client fixed it, sorry should have mentioned that in the original ticket

**Comment by Tom-Willemsen** [comment]
Re-reported by Vicky (IRIS again)

**Comment by John-Holt-Tessella** [comment]
+1 IMAT: Said it was better this cycle it would freeze after a couple of days.

**Comment by Tom-Willemsen** [comment]
+1 Vesuvio - they said they were using the SECI DAE panel because they didn't trust the IBEX one.

**Comment by AdrianPotter** [comment]
Duplicate #2750
