### ISSUE TITLE
IOC/Support: Remove visual Studio dependency from Mk3Choppers

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2677]
As a developer on windows 10 and VS2017 I want to be able to build the MK3 Chopppers. 
If possible remove visual studio-ness of this project otherwise make a way of using different versions.

**Comment by John-Holt-Tessella** [comment]
I get when I build `EPICS\support\mk3chopper\master` 

    CSC : error CS8111: Invalid instrumentation kind: NDW1798 [C:\Instrument\Apps\EPICS\support\mk3chopper\master\Mk3Wrap
per\Mk3Wrapper.csproj]

**Comment by GRyall** [comment]
We are now moved over to Windows 10 and recent VS versions. Either we are not using this and the work is not required, or we have already done it.
