### ISSUE TITLE
genie_python: Investigate load function

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2678]
Genoveva recently tried to load a script using `load('my_script.py)` rather than `load_script('my_script.py')`. This caused two issues:
* When run in the scripting window the function silently continues as `load` is in-built to ipython.
* When run in a standalone genie_python console it caused a `failed to interpret file as pickle` error as it tries to use the numpy `load` function.

It should be more obvious to the user that they are using the wrong function here.

**Comment by FreddieAkeroyd** [comment]
"load" was the Open GENIE command name for loading files, so it is likely other scientists will encounter this issue too

**Comment by John-Holt-Tessella** [comment]
Reported by an instrument scientist on ALF.

**Comment by John-Holt-Tessella** [comment]
Create a function load and make it print the error:

"This function does not load a script; you probably wanted g.load_script(). If you wanted numpy load please call it directly as import numpy as numpy; numpy.load". Then exit.

**Comment by John-Holt-Tessella** [comment]
Include a script checker.
