### ISSUE TITLE
Archive Engine: Update to 4.5.x

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2685]
The latest cs-studio will have the modifications done by https://github.com/ISISComputingGroup/IBEX/issues/2477. We should move on to this release when it is ready.

**Comment by DominicOram** [comment]
We will need to hotfix the change in https://github.com/ISISComputingGroup/IBEX/issues/2069

**Comment by Tom-Willemsen** [comment]
Have been on 4.6.x for some time
