### ISSUE TITLE
genie_python: Cannot have instrument file called `title`

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2692]
As a Merlin instrument scientist, I would like to be able to call my instrument script "title" so that I can have scripts with sensible names without it causing a failure.

During training, Adroja from Merlin made an instrument script called `title` and it subsequently meant an error while loading `inst` when opening a scripting console. It's not obvious why, and what other keywords might be vulnerable to a similar failure. Either we should fix it, or give a suitable error if it is detected.

**Comment by kjwoodsISIS** [comment]
A script called "title" is poorly named.  We should not be bending our code out of shape to accommodate poor naming practices.  Scripts "do things", therefore, it would better to encourage scientists to use verbs (rather than nouns) to name their scripts.

It would be better to have the system reject the use of scripts with names that clash with keywords, with a helpful error message, of course.  A better user story would be:
As an instrument scientist I would like genie_python to alert me if the name of my script clashes with a reserved keyword, so that I can give my script a more appropriate name.

**Comment by AdrianPotter** [comment]
I couldn't replicate the issue specifically but did try including functions with names already part of the inst module, for instance `loader` and `name`. I've put a check in for this as part of the instrument script loader in the settings directory, you'll find it on branch `Ticket2692_Warn_users_about_loading_instrument_scripts_with_protected_keywords`.

We currently don't have an automated way to push the change to instruments. I'm going to look at incorporating it into the upgrade script.

**Comment by AdrianPotter** [comment]
Just a reminder, there's one PR above but don't forget to review the branch in the configuration repo

**Comment by Tom-Willemsen** [comment]
Upgrade script works well. However I'm getting some errors when running 
```
import inst
reload(inst)
```
with the new loader on your branch in the settings repo. I have a minimal test script in my inst directory defining one function.

**Comment by Tom-Willemsen** [comment]
I get the following traceback from typing `import inst`

```
import inst
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-3f6191cc651a>", line 1, in <module>
    import inst
  File "C:\Instrument\Dev\ibex_gui_e3\.metadata\.plugins\org.eclipse.pde.core\.bundle_pool\plugins\org.python.pydev_4.5.1.201601132212\pysrc\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Instrument\Settings\config\NDW1799\Python\inst\__init__.py", line 26, in <module>
    elif not should_load(name, value):
  File "C:\Instrument\Settings\config\NDW1799\Python\inst\__init__.py", line 13, in should_load
    elif os.path.dirname(os.path.realpath(__file__)) not in globals()[name].func_code.co_filename:
AttributeError: 'module' object has no attribute 'func_code'
reload(inst)
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c9fc93622463>", line 1, in <module>
    reload(inst)
NameError: name 'inst' is not defined
```

I also get an error when loading a simple test script:

test.py:
```
import inst

print("Hello")
```
```
g.load_script("C:\\scripts\\test.py")
ERROR: 'module' object has no attribute 'func_code'
```

**Comment by AdrianPotter** [comment]
Yep, it had issues when there were imports in the scripts. I didn't think to check that case. I've added the extra code now and confirmed it works with the NDXGEM and NDW1836 branches
