### ISSUE TITLE
Keithley 2400: Terminator is configurable

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2695]
On Polaris there was an issue with the Keithley 2400 because the terminator was set to `\r\n` but the device was only sending `\r`. Freddie has dug out the manual and the terminator is configurable on the physical box.

We should make the terminator a macro for this IOC.

**Comment by FreddieAkeroyd** [comment]
The factory default terminator is \r - did you mean \r above (it can be manually set to \n)?

**Comment by Tom-Willemsen** [comment]
Well spotted, corrected above, thanks.
