### ISSUE TITLE
IBEX: running client from private network

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2696]
As a motion control commissioner I would like to run up an IBEX client on my laptop which I have connected to the private network (so that i can use GalilTools).

The concern here is EPICS broadcasts and what the galil might do, however the client could be configured to do unicast name searches or TCP name resolution direct to the instrument. We need to confirm which parts of GalilTools are being used and if this could be provided by the IOC/IBEX directly.

**Comment by GDH-ISIS** [comment]
Does this mean you intend to give write access via IBEX to the laptop on the local network (or ISIS network) please?

**Comment by FreddieAkeroyd** [comment]
Write access isn't necessarily implied, the request was from Ian Collier and I can't remember if he wanted/needed write access via IBEX as would also have GalilTools. We need to capture his requirements, I was just recording the request for discussion. While @DominicOram is on placement would be a good time to follow this up and work out the best solution

**Comment by GDH-ISIS** [comment]
I am trying to appreciate where the responsibility lies for motion control in the future and what the intention is. If another team is going to commission the equipment at the epics level then computing never need get involved for commissioning or when there is a support problem. This is fine. The support route for us then is very simple, as long as communication is established with the equipment. They can come to us with new requirements as and when necessary.

**Comment by GDH-ISIS** [comment]
test

**Comment by DominicOram** [comment]
After discussion with Iain we came to the following solution:
* Write an OPI that will give more access to the Galil (https://github.com/ISISComputingGroup/IBEX/issues/2607)
* Improve their pre-existing commissioning software, which thy can use to access the Galil via serial. (work being done outside of IBEX)

Therefore they will not need access to the private network.
