### ISSUE TITLE
GUI: Allow exporting motor parameters

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2697]
As a member of the motion control group I would like to be able to export calibration information for the specified axis on an instrument.

**Comment by KathrynBaker** [comment]
Isn't this a bit like #2607?

**Comment by DominicOram** [comment]
Yes, I think #2607 could be a part of this but I think there are a number of use cases that might not be covered by a specific galil OPI. For example, outputting data about all instrument axes at once is something that could be tricky using an OPI. I envisage this as something like the ToM where the OPI that you drill down to for each one could well be that made in #2607.

**Comment by DominicOram** [comment]
On reflection I agreed with Kathryn's comment and will make this exporting feature as part of the OPI.
