### ISSUE TITLE
Central gateways: add R2 network presence

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2700]
As a user I would like IBEX to be accessible on the R2 network in the same was as it is on R3/R55/R80.

This requires adding an R2 network adapter to control-svcs and running gateways on this network

**Comment by FreddieAkeroyd** [comment]
Facilities IT have added an R2 adapter, need to configure gateways

**Comment by FreddieAkeroyd** [comment]
Adapter configured with static address on control-svcs, R2 gateway started

**Comment by FreddieAkeroyd** [comment]
@DominicOram can you see if this fixes your client working with instlist from R2?

**Comment by DominicOram** [comment]
Works and merged, thanks. Should the address also be added in config env?

**Comment by FreddieAkeroyd** [comment]
config_env picks it up indirectly via running  get_isis_ip  from utils_win32 which recent versions of are  already doing the right thing.
