### ISSUE TITLE
-1: Journal Viewer: simple viewer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2703]
As a scientist, I want to view the current (i.e. most recent) journal file for my instrument, so that I can inspect the summary details of previous experiments.

#### Acceptance Criteria
1. I can use the IBEX client to view the contents of the current journal on my instrument control PC.
1. The contents of the current journal should be displayed as a table.
1. Each row of the journal table will display the details of a single run
1. The journal table will display the following columns (left-to-right in the order listed below):
   - Run Number
   - Title
   - Start Time (YYYY-MM-DD HH:MM:SS)
   - Duration (HH:MM:SS)
   - uAmp Hours (up to 7 significant figures)
   - RB Number
   - Users
1. The journal table will display a header, stating the title of each column
1. Journal entries should be listed so that the most recent entries are displayed first.
1. I can scroll the table up/down and left/right, as needed.

#### Notes
1. See ticket [#1821](https://github.com/ISISComputingGroup/IBEX/issues/1821)
1. Current journal means journal entries for the current cycle
1. The current journal could be available as:
   1. a file called `journal_YY_cc.xml` in the folder `C$\Data\`, or as
   1. a MySQL database table (see #2723)
1. If the current journal file is to be available as a MySQL database table, creating & populating the table is a pre-requisite (see #2723).
1. **Design constraint:** the journal viewer should be designed so as to make it easy to switch (at the implementation level) from a file based source to a database.
   - if we choose to use a database source from the outset, then this design constraint becomes redundant.

**Comment by John-Holt-Tessella** [comment]
Should we limit this to the most recent 20 entries?

**Comment by mattclarke** [comment]
I don't think we should propose limiting things before we have even started developing it.
Besides, the muon instruments, for example, may do 20+ runs in a few hours.

**Comment by kjwoodsISIS** [comment]
I think the answer is ... it depends!  Some instruments - ENGIN-X springs to mind - do a lot of short experiments.  This means they have a lot of run numbers and, therefore, a lot of journal entries.  Other instruments spend a long time collecting data and, therefore, have relatively few journal entries.  If a scientist want to look over the journal entries for the last two weeks (say), he might have lot of entries to look at or just a few.
I would guess that each journal entry (based on the fields above) is nor more than 1K in size.  I think we could probably afford to view more than 20 at a time.  Maybe 50 or 100?  It might also depend on how quickly we can query the database (if we adopt a database solution).

**Comment by AdrianPotter** [comment]
The first sensible step might be to implement simple pagniation. That could extend to filters on some of the columns. I think in the first instance, users should be able to get to any entry. If you were to do it with pagination, it could potentially mean interval bisection to find the run they want but at least it's possible. You could streamline it later with searches if it's sufficiently valuable.

**Comment by John-Holt-Tessella** [comment]
Try breaking down into smaller <1day tickets as per meeting. (make thi the umbrella tickets).

**Comment by AdrianPotter** [comment]
Looking at breaking down the tickets now...

**Comment by AdrianPotter** [comment]
Changed estimate for 0.5 day for work breakdown, new tickets and re-estimation

**Comment by AdrianPotter** [comment]
I have created tickets to implement these requirements (and in slightly more detail):

- #2900 
- #2901 
- #2902 
- #2903 
- #2904 
- #2905 

This ticket can be closed if the reviewer is satisfied that the implementation of the tickets above would produce a system that would fit the acceptance criteria of this ticket.
