### ISSUE TITLE
Journal Viewer: instrument switching

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2706]
As a scientist, when viewing the journal table, I want the IBEX client to display the journal file for the current instrument.

#### Acceptance Criteria
1. IBEX displays the journal file for the current instrument (as displayed in the IBEX dashboard pane).
1. On switching instrument, IBEX updates the journal table to display the journal file for the new instrument.

#### Notes
1. None.

**Comment by DominicOram** [comment]
This works in latest GUI build
