### ISSUE TITLE
SANDALS: Sample Changer - IOC, OPI & Emulator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2707]
As a SANDALS scientist, I want to control the sample changer, so that I can control which sample is placed in the neutron beam.

#### Acceptance Criteria
1. I can use the IBEX GUI to control which sample is placed in the neutron beam.
1. I can use a genie_python script to control which sample is placed in the neutron beam.

#### Notes
1. The SANDALS sample changer is controlled by a custom controller.  It will require a custom IOC.
1. The custom IOC can be based on `C:\LabVIEW Modules\Instruments\SANDALS\SM300\SM300 Controller.vi`
   * **Note:** The vi makes reference to a Julabo water bath. Please ignore the Julabo; it is no longer relevant. Only consider the sample changer.

**Comment by KathrynBaker** [comment]
Notes from the VI:
Number of Nodes: 637
Cyclomatic complexity: 180
Screen Shot:
![image](https://user-images.githubusercontent.com/10552381/32618576-0c7fb310-c570-11e7-9ede-dc55ed9d8844.png)
Standard comms block, so standard asyn driver should be enough
Some minor string analysis when reading all positions
Pressing home homes both axes, via a command
13 steps in the initialisation routine
2 steps in disconnect routine
There is some maths involved in the moving to positions, relating to offsets and distances relative to sample 0 position, which are coded into the LabVIEW
Extract is a specific position
My instinct for pointing would be 8 (to allow for the decoding of the offsets and recording of them, as well as the standard creations which are 5, it may be less than 8, but it is more than 5)

**Comment by kjwoodsISIS** [comment]
Document the amount of effort actually required for this ticket - 8 points seems excessive.

**Comment by DominicOram** [comment]
Discussed with motion control group, no changes to the sample changer are in the pipeline.

**Comment by John-Holt-Tessella** [comment]
Possibly wait for ticket on creating IOC to start

**Comment by John-Holt-Tessella** [comment]
TODO in January:

* Stop command
* Remove dead code
* Setup sample changer with initialise which does reset then homes both axes

**Comment by John-Holt-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/ibex_utils/pull/9

**Comment by John-Holt-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/ibex_gui/pull/628
https://github.com/ISISComputingGroup/EPICS-ioc/pull/217
https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/6
https://github.com/ISISComputingGroup/EPICS-motor/pull/19
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/51
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/47

**Comment by John-Holt-Tessella** [comment]
There needs to be tests for the motion setpoints. I have created another ticket for those. I expect there will be a rework for this anyway. Please review this ticket apart from that.

**Comment by John-Holt-Tessella** [comment]
> Document the amount of effort actually required for this ticket - 8 points seems excessive. Check if there is an existing EPICS driver for the controller.

It turns out it took a lot longer than the 8 days. The reasons for this are:

* Initial estimate was based on creating a stream device which did a similar thing to the lab view and we created a motor and used the sample changer on top. This seemed like the correct decision at the time. It turned out that this was problematic because the 
    * SM300 doesn't act as much like single independent motors as was expected. (it treats the motors as a single big motor e.g. you can only home one axis at a time)
    * The motor record is itself complicated
* I had difficulties  with the IOC, maybe partly because I had not done a motor IOC before
    * it crashed on autosave because I had called iocinit twice
    * the motion setpoint library would not read xml and crashed. This was because of conflicting dll's which was not seen on the galil.
    * I didn't wire up the records to asyn correctly.
* Adding extra asyn records was not something that I had done before so this took longer too
* Finally the device was not just simple it has strange behaviour which we didn't know about because we didn't treat it like a motor in the lab view

**Comment by AdrianPotter** [comment]
@John-Holt-Tessella In retrospect, do you think the alternative approach of programming the IOC from scratch would have been easier? If so, and given you discussed the decision with me and agreed that using the motor record would be better, what information would we have needed to pick the easier path?

**Comment by John-Holt-Tessella** [comment]
I think this is the right decision it gives us a good start if we need to support the SM300 motor elsewhere and gives us experience of level 3 motor record. We probably just needed to break the ticket down a bit and been a bit luckier.
