### ISSUE TITLE
IOC: SCM100_02

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2709]
As a LARMOR instrument scientists I need a second SMC100 ioc. I used to have this but it no longer exists. (It is is the globals on LARMOR).

This is needed for FEB but should probably be in the next release if possible.

**Comment by FreddieAkeroyd** [comment]
There was never a second SMC100 IOC, the macros on LARMOR define a second port on SMC100_01 for the additional axis so it just need to be uncommented and all should work fine. We could create a second IOC if Rob would prefer them to be separated.
```
SMC100_01__MTRCTRL=15
SMC100_01__PORT1=COM41
#SMC100_01__PORT2=COM39
```
