### ISSUE TITLE
Shared instrument python area - part I

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2713]
As an instrument scientist I would like to deploy and version control a set of python control modules across multiple instruments. 

This arose from a conversation with Rob Dalgliesh, they have common reflectometer and sans python routines that they would like to use on multiple instruments. This ticket should meet with Rob Dalgliesh and Adam Washington to discuss requirements and possible solutions.

This ticket will be split into two:
1.  Part I: meet with the scientists, discuss their requirements, document their requirements (this ticket).
1.  Part II: design and implement the solution. (see #2716)

###Notes
1. Currently all files in configurations/Python are captured by our configuration version control. A solution might be to create a "userlib" directory in configurations/Python which is added to the configuration .gitignore The scientists can then clone additional git repositories into directories in "userlib" which they then maintain and update themselves

**Comment by kjwoodsISIS** [comment]
Mantid team do something similar - speak to Mantid team first.

**Comment by John-Holt-Tessella** [comment]
Sent emails to Rob and Adam; and mantid and started arranging a meeting.

**Comment by John-Holt-Tessella** [comment]
- Who will be sharing the scripts? Is it a one group of instruments with one repository or is it several different groups?
- How should we control the versioning manually or automatically?
    - If automatically what do you want to do about conflicts?
    - If manually what do you want to do about updating the various machines
- Testing: did you need any testing infrastructure? 
- How should the scripts to appear to users within genie_python?
- Who polices the scripts, how does one instrument know that scripts have been tested?

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella - any news from Rob & Adam on this ticket?

**Comment by John-Holt-Tessella** [comment]
No, last word was that he was incredibly busy with Crisp. I will send another email on Monday.

**Comment by John-Holt-Tessella** [comment]
Arrnaged for 4th Jan 2018

**Comment by John-Holt-Tessella** [comment]
Problem
Instrument scientists would like a way of sharing code between instruments to avoid duplication and to share best practice. With the computing group we should:
1.	Decide on a solution to this.
2.	Create a strategy and processes documentation.
3.	Provide infrastructure to allow for this (both to host the solution and to enable it within IBEX/genie_python)
Scope
Applies to code written in genie_python which will control the instruments, eventually this may be expanded to include code that performs interactive analysis. There appear to be at least three levels at which the code needs to be shared:
1.	Code that is explicitly for a single instrument but used by multiple scientists and users, e.g. on Larmor or Zoom.
2.	Code that is for a group of instruments, e.g. reflectometers or SANS. This code may need optional configuration for instruments within the group, e.g. if instrument=SANS2D set property x to y.
3.	Code which can be applied to most instruments, e.g. general scan routines. These routines may call group or instrument specific code.
For the process:
•	When the code is edited it should be possible to tell who has made the change and when.
•	The instrument scientist should be in control of when the code on an instrument is updated.
•	Instrument scientists should be informed if their version of the code is out of date
•	Changes should be able to be made independently, e.g. branches
•	Code can be shared with the world; code is public.
•	Code can be in python 2 or 3, there are no special dependencies except from what is already provided in genie_python (numpy, scipy, matplotlib etc.)
•	If possible code should have some form of testing.
Extra features:
•	Genie_python should report what version of the code is being run if possible.
At the meeting we tentatively suggested git as one large repository with importable python modules, many repositories and many repositories with sub modules. Nothing was ruled out in particular. 
Plan
The plan is to talk with Adam and Joe. Then to meet in the computing group to discuss possible solutions and then to present them back to all.

**Comment by John-Holt-Tessella** [comment]
Updated minutes after meeting with Adam and Joe:

Problem
Instrument scientists would like a way of sharing code between instruments to avoid duplication and to share best practice. With the computing group we should:
1.	Decide on a solution to this.
2.	Create a strategy and processes documentation.
3.	Provide infrastructure to allow for this (both to host the solution and to enable it within IBEX/genie_python)
Scope
Applies to code written in genie_python which will control the instruments, eventually this may be expanded to include code that performs interactive analysis. There appear to be at least three levels at which the code needs to be shared:
1.	Code that is explicitly for a single instrument but used by multiple scientists and users, e.g. on Larmor or Zoom.
2.	Code that is for a group of instruments, e.g. reflectometers or SANS. This code may need optional configuration for instruments within the group, e.g. if instrument=SANS2D set property x to y.
3.	Code which can be applied to most instruments, e.g. general scan routines. These routines may call group or instrument specific code.
4.	Code which is specific to a device, e.g. Berkley camera
For the process:
•	When the code is edited it should be possible to tell who has made the change and when.
•	The instrument scientist should be in control of when the code on an instrument is updated.
•	Instrument scientists should be informed if their version of the code is out of date.
•	Changes should be able to be made independently, e.g. branches.
•	Code can be shared with the world; code is public. We need to check on extra rules if needed to form some guidance, e.g. ip addresses.
•	Code can be in python 2 or 3, there are no special dependencies except from what is already provided in genie_python (numpy, scipy, matplotlib etc.)
•	If possible code should have some form of testing. Advice on document testing and unit testing could be useful.
•	Think about options for versioning strategies, options might include running scripts with older versions, version as part of api, versioning in naming for non-back compatible changes.
•	Documentation generation strategies both at code level and higher level. For example a document talking about how to run a camera and a description of the scripted calls.
Extra features:
•	Genie_python should report what version of the code is being run if possible.
At the meeting we tentatively suggested git as one large repository with importable python modules, many repositories and many repositories with sub modules. Nothing was ruled out in particular. 
Plan
The plan is to talk with Adam and Joe. Then to meet in the computing group to discuss possible solutions and then to present them back to all.
1.	Computing group to meet and put together a list of options. 
2.	Discuss options with interested parties
3.	Decide and implement options, e.g. set up a github repository
