### ISSUE TITLE
Shared instrument python area - part II

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2716]
As an instrument scientist I would like to deploy and version control a set of python control modules across multiple instruments.

This arose from a conversation with Rob Dalgliesh, they have common reflectometer and sans python routines that they would like to use on multiple instruments. This ticket should meet with Rob Dalgliesh and Adam Washington to discuss requirements and possible solutions.

This ticket will be split into two:
1. Part I: meet with the scientists, discuss their requirements, document their requirements (see #2713)
1. Part II: design and implement the solution (this ticket).

###Notes
1. Currently all files in configurations/Python are captured by our configuration version control. A solution might be to create a "userlib" directory in configurations/Python which is added to the configuration .gitignore The scientists can then clone additional git repositories into directories in "userlib" which they then maintain and update themselves

**Comment by ChrisM-S** [comment]
I've put a comment here rather than on #2713 as these are more implementation requirements but as a systems maintainer I would like to ensure that the deployment and maintenance of the script libraries on the NDX machines is "automatic".  By this, it would be good to ensure that in any situation of loss or regeneration of the instrument the "userlib" based files will return the most recent versions that were on the instrument disk (of that instrument).

- Changes to these scripts on a running instrument (if they are allowed) are:
  - checked in automatically (like our configurations)
  - can be recovered/synchronized automatically (like our configurations)

- Changes to scripts on the network library repository are:
  - checked out only if appropriate on each running instrument
  - changes checked in from one instrument do not appear automatically on another :-).

This might be implemented with Git by "saving" to and "restoring" from a default branch which includes the name of the instrument, e.g. "NDXCRISPbranch".  Changes which were tested on one instrument could be "pushed" to a common repository and "pulled" to instruments individually when global changes are required to be deployed to that instrument.

**Comment by kjwoodsISIS** [comment]
I think we need to understand the scientists requirements and expectations first.  I don't know whether they want or expect any degree of automation in this process.  We can determine the most appropriate solution when we have documented the requirements and expectations (see #2713).

**Comment by ChrisM-S** [comment]
A win-win merge of operational and scientific requirements would be ideal :smile:

**Comment by FreddieAkeroyd** [comment]
@ChrisM-S our current settings scheme saves all the area to an instrument specific branch and auto-adds files, however what Rob seems to want is a non instrument specific method. They may have an independent of us github for reflectometry routines that they wish to use on several instruments, but whether they want it pushed back and distributed automatically we would need to ask them. I saw this really as an area they would manage, deciding when or if to push/pull themselves. We would include it in a general system backup of settings, but that would be about it. Anyway, we should wait for requirements.

**Comment by John-Holt-Tessella** [comment]
This ticket should clarify the requirements. Create a new ticket for implementation.

**Comment by John-Holt-Tessella** [comment]
#2713 is done see notes from meting
Problem
Instrument scientists would like a way of sharing code between instruments to avoid duplication and to share best practice. With the computing group we should:
1.	Decide on a solution to this.
2.	Create a strategy and processes documentation.
3.	Provide infrastructure to allow for this (both to host the solution and to enable it within IBEX/genie_python)
Scope
Applies to code written in genie_python which will control the instruments, eventually this may be expanded to include code that performs interactive analysis. There appear to be at least three levels at which the code needs to be shared:
1.	Code that is explicitly for a single instrument but used by multiple scientists and users, e.g. on Larmor or Zoom.
2.	Code that is for a group of instruments, e.g. reflectometers or SANS. This code may need optional configuration for instruments within the group, e.g. if instrument=SANS2D set property x to y.
3.	Code which can be applied to most instruments, e.g. general scan routines. These routines may call group or instrument specific code.
4.	Code which is specific to a device, e.g. Berkley camera
For the process:
•	When the code is edited it should be possible to tell who has made the change and when.
•	The instrument scientist should be in control of when the code on an instrument is updated.
•	Instrument scientists should be informed if their version of the code is out of date.
•	Changes should be able to be made independently, e.g. branches.
•	Code can be shared with the world; code is public. We need to check on extra rules if needed to form some guidance, e.g. ip addresses.
•	Code can be in python 2 or 3, there are no special dependencies except from what is already provided in genie_python (numpy, scipy, matplotlib etc.)
•	If possible code should have some form of testing. Advice on document testing and unit testing could be useful.
•	Think about options for versioning strategies, options might include running scripts with older versions, version as part of api, versioning in naming for non-back compatible changes.
•	Documentation generation strategies both at code level and higher level. For example a document talking about how to run a camera and a description of the scripted calls.
Extra features:
•	Genie_python should report what version of the code is being run if possible.
At the meeting we tentatively suggested git as one large repository with importable python modules, many repositories and many repositories with sub modules. Nothing was ruled out in particular. 
Plan
The plan is to talk with Adam and Joe. Then to meet in the computing group to discuss possible solutions and then to present them back to all.
1.	Computing group to meet and put together a list of options. 
2.	Discuss options with interested parties
3.	Decide and implement options, e.g. set up a github repository

**Comment by Tom-Willemsen** [comment]
Meeting scheduled for Monday at 13:00

**Comment by John-Holt-Tessella** [comment]
Write up see notes on the wiki at https://github.com/ISISNeutronMuon/InstrumentScripts

**Comment by John-Holt-Tessella** [comment]
After review let me know and I will set up a meeting with instrument scientists.

**Comment by Tom-Willemsen** [comment]
I've reviewed the repository documentation and the skeleton structure. As far as I can see, it looks good.
 There are a few TODO items, but these will be sorted in the meeting with the scientists.

**Comment by John-Holt-Tessella** [comment]
Meeting has been scheduled

**Comment by Tom-Willemsen** [comment]
Meeting complete.

- They would like a git hook to check committers have names. I will create a seperate ticket.
- They don't need Jenkins at this time (but may ask us for it later)
- They would like an automated documentation build. I will create a ticket.
