### ISSUE TITLE
TRAIN: Cryogenics group

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2717]
Run IBEX training for cryogenics group. Delivery on 2nd November. Laptops requested from FIT

## Acceptance criteria

- [x] Training delivered
- [x] Feedback incorporated into slides
- [x] Slides distributed to delegates
- [x] Laptops returned to FIT

**Comment by KathrynBaker** [comment]
Tickets in place, manual reference removed from training  - although there are still some examples relating to block names - however, I feel that there is a logic to retaining that reference as it is an important relationship for instrument scientists to be aware of.

A separate conversation with Richard also showed him thinking of the possibilities and of ways of leveraging the system to their advantage.
