### ISSUE TITLE
MAPS: deny remote access to MK3 T0 chopper

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2718]
MAPS will be having some new choppers and wish to commission with them in early December. The choppers are currently in the chopper lab. For the disc chopper, Mike Brind is the contact. MAPS will likely start commissioning with SECI before moving to IBEX, we need to assess if SteamDevice + CALab or separate LabVIEW driver is the best approach.

**Comment by FreddieAkeroyd** [comment]
Note from Russell - they are hoping to bring the instrument back up around 1st December, so would like any new VIs to be ready and tested by then. The choppers (both the new disk and the fermi) will be installed later this week in order to allow offline tests by the chopper group.

**Comment by John-Holt-Tessella** [comment]
Disc choppers are the T0 (which is not being controlled from ECI or IBEX) and an SKF as on Merlin so this should be fine in either system.  @FreddieAkeroyd  if you agree can you close this issue please.

**Comment by davidkeymer** [comment]
Actually, the T0 and Disc will both be MK3 controlled (no SKF), so I don't think we need worry about the S/W for whichever control system is in use.
One slight complication is a request from the instrument scientist that remote access be denied to the T0 (to prevent users from changing critical running parameters).  However in the MK3 system, it is not currently possible to allow _local_ control of one "channel" and not _remote_.  Therefore a custom solution needs to be put in place for both control systems.
I shall rename this ticket to reflect this task.

**Comment by FreddieAkeroyd** [comment]
Is this just a matter of putting access control onto the relevant PV?
