### ISSUE TITLE
MAPS: control of new fermi chopper

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2719]
MAPS will be having some new choppers and wish to commission with them in early December. The choppers are currently in the chopper lab. For the fermi chopper, Paul Chorley is the contact. MAPS will likely start commissioning with SECI before moving to IBEX, we need to assess if SteamDevice + CALab or separate LabVIEW driver is the best approach.

**Comment by FreddieAkeroyd** [comment]
Comment from @davidkeymer "If the fermi chopper is the new prototype from FZJ, which I believe it is, then I have a full manual for it including the TCP command set. It looks fairly straightforward to put something together, probably a stream device, and certainly much easier than the current FZJ fermi!"

**Comment by FreddieAkeroyd** [comment]
Note from Russell - they are hoping to bring the instrument back up around 1st December, so would like any new VIs to be ready and tested by then. The choppers (both the new disk and the fermi) will be installed later this week in order to allow offline tests by the chopper group.

**Comment by John-Holt-Tessella** [comment]
@davidkeymer is going to work out how hard this will be to do. If it is easy then it is to be implemented directly in labview if it is hard then an IOC should be created and calab should be used.

**Comment by davidkeymer** [comment]
Russell is happy for an IOC to be written to avoid duplication of work for the group when the time comes to migrate MAPS to IBEX.  After the beamline is rebuilt, the instrument will be recommissioning with SECI to avoid introducing additional changes.  Therefore a VI will need to be written using CALab to sit between SECI and the IOC.  Suggest a separate ticket for this task.

**Comment by John-Holt-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/EPICS-utilities/pull/7

**Comment by AdrianPotter** [comment]
- [ ] There is no PR for the branch in repo https://github.com/ISISComputingGroup/EPICS-FZJ-DDfermichopper

**Comment by davidkeymer** [comment]
Missing pull request here:
https://github.com/ISISComputingGroup/EPICS-FZJ-DDfermichopper/pulls
