### ISSUE TITLE
MERLIN: unable to read monitor spectra

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2722]
As a MERLIN instrument scientist I would like to be able to view monitor spectra as well as detector spectra in the DAE panel. Currently monitor spectra do not show up properly.

The issue here is that the merlin monitors have a very large number of time channels > what the DAE is configured to allow over channel access. This also needs to be aligned with an appropriate setting of EPICS_CA_MAX_ARRAY_BYTES   We may not want to have the larger size on all instruments, should look to making it configurable by instrument but it may also be possible to make it dynamic. Currently all of an array is sent even if only a subset is used, I think gateways may now support resizing but doe the CS Studio graphs?

**Comment by John-Holt-Tessella** [comment]
Would it be worth considering a spectra "server" (possibly in Epics V4) which serves just bits of the spectra that is requested or a course grained spectra if a wider range is requested?

**Comment by FreddieAkeroyd** [comment]
We'll do something better with v4, but need to fix MERLIN for next cycle
