### ISSUE TITLE
Dataweb: Use scientific notation

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2724]
As an HRPD instrument scientist, I would like the values displayed on the dataweb to use scientific notation, as information is sometimes lost without (e.g. very small values being displayed as 0)

**Comment by ThomasLohnert** [comment]
Requires https://github.com/ISISComputingGroup/IBEX/issues/2478 for non-truncated block values

**Comment by DominicOram** [comment]
Not quite the same but very similar to https://github.com/ISISComputingGroup/IBEX/issues/1198. These should be done at the same time

**Comment by DominicOram** [comment]
Fixed by #2069
