### ISSUE TITLE
Eurotherm ramp resets if connection is lost

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2729]
As a HRPD instrument scientist, I do not want a Eurotherm ramp to start again from 0 if the connection is lost part way through because it takes a very long time.

Reported by Dominic Fortes on HRPD. If a Eurotherm is in the middle of a ramp and the connections is lost (IOC restarted?) then the Eurotherm ramp starts again from 0, rather than its last known location. This causes a severe loss of time.

**Comment by kjwoodsISIS** [comment]
Why not just start each ramp from the current temperature?

**Comment by John-Holt-Tessella** [comment]
I think what is going on is that when it becomes disconnected the reported temp will be 0 and then it ramps from where it is, which is 0

**Comment by AdrianPotter** [comment]
I've tried the following:

- Disconnect sensor mid-ramp
- Disconnect Eurotherm network connection mid-ramp
- Switch off the Eurotherm mid-ramp

In each of these cases, the ramp is not interrupted abnormally.

If the IOC is restarted then the ramp does not resume when the IOC comes back up.

I've relayed this to Dominic. Awaiting response

**Comment by AdrianPotter** [comment]
Dominic says the issue happened once and "it was weird". He doesn't know what caused the error and hasn't seen it since. He said he'd take a look at his logs for clues. If no further response in the next week then I'll make this ticket won't fix

**Comment by AdrianPotter** [comment]
Marking won't fixed as planned. No further update
