### ISSUE TITLE
LogPlotter: Plot multiple PVs

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2730]
As a HRPD instrument scientist, I would like to plot multiple PVs on a single log plot so that I can see how different variables are correlated.

This is technically possible already by right clicking on a log plot and clicking "Add PV". This isn't particularly easy though because you can't add variables by block, you need to remember the PV you need. Since we are trying to abstract PVs away from users, I'm sure we can find a better way. The other problem with going through the context menu is that it might give users ideas about clicking on other things in the context menu that don't work and can get IBEX into a weird state.

**Comment by ThomasLohnert** [comment]
+1 from Polaris

**Comment by KathrynBaker** [comment]
+1 from Muons

**Comment by John-Holt-Tessella** [comment]
Make sure it works in E4.

Expandable meun to display grpah names (call graphs better names)
Needed on block right click and OPI right click.

**Comment by DominicOram** [comment]
I didn't do the check on the OPI right click as I suspect it will be quite different in E4 and we have yet to allow plotting from OPIs. Do this as part of (https://github.com/ISISComputingGroup/IBEX/issues/2881)

**Comment by ThomasLohnert** [comment]
Did a review on the E3 PR - did not get around to reviewing the E4 branch, but I suspect the problems I found will exist on there as well

**Comment by DominicOram** [comment]
Taking rework off of this so that someone picks it up for review in Thomas' absence
