### ISSUE TITLE
SMS alerts on blocks out of range

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2738]
Requested by Helen Walker (Merlin).

As an instrument scientist, I would like a system similar, but separate to, run control that will send me text alerts if blocks go out of a defined range.

This should be independent of run control, because for some blocks I want to be alerted that they are drifting but the data collection should still continue.

**Comment by kjwoodsISIS** [comment]
We need to give this some thought.  We don't want to end up with multiple ways to alert people to out of range blocks, etc.  We need to think about how this relates to the Alarm system.  And we also need to think about whether the alert should be via SMS or Slack or whatever...

**Comment by aaron-long** [comment]
+1 ENGIN-X

Would also like Slack alerts.
