### ISSUE TITLE
Jaws: Setting both horizontal and vertical gap at the same time sometimes leads to final setpoint not being reached

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2739]
Reported by Helen Walker (Merlin)

Sometimes when I set both the horizontal and vertical gaps on the jaws at a similar time, they do not reach the requested setpoint.

Note:
Helen was unable to reproduce this behaviour in the sprint demo meeting. We have asked Helen to notify us when this issue next occurs so that we can investigate the logs. This is a placeholder ticket so that we can log reoccurences of this issue.

**Comment by GDH-ISIS** [comment]
Please use caution with the interpretation here as I believe this is a Galil piezo set of Jaws. This could simply be a tuning issue whereby the vibration or electrical noise of one set of jaw pairs influences another - not necessarily a driver issue. I will try to have a look and see if I can improve the situation.
