### ISSUE TITLE
LET: Triton Dilution Fridge

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2744]
As an instrument scientists I would like to control a Triton Dilution fridge from EPICS. It should be possible to use a stream device driver talking to the attached computer. For documentation and sample LabVIEW code see  C:\LabVIEW Modules\Drivers\Triton

#### Notes
1. Triton Dilution fridges are controlled by their own PCs.  The purpose of this ticket is to create a stream device driver to manage the communication between IBEX and the Triton PC.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - which instrument is requesting this?

**Comment by FreddieAkeroyd** [comment]
No instrument as such yet, but it wasn't present in the backlog

**Comment by davidkeymer** [comment]
From a brief analysis of the SECI configuration files of the remaining instruments, the triton dilution fridge has been used on the following:  LET, MARI, MUSR, OSIRIS, POLREF, WISH.

**Comment by kjwoodsISIS** [comment]
See also #2828

**Comment by Tom-Willemsen** [comment]
I believe the IBEX driver has an equivalent set of functionality to the SECI driver (unless there have been recent updates to the seci driver which I don't know about). Therefore, I believe that this ticket can be considered complete.

**Comment by Kevin-Woods-Tessella** [comment]
Given Tom's comments we can consider this ticket redundant - tickets #2828 & #2886 implement the desired functionality.
