### ISSUE TITLE
Harmonise db checking scripts

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2745]
Currently we have some (quite poor) scripts to check for our db conventions in https://github.com/ISISComputingGroup/EPICS-DbChecker which are not run as part of the build and so are probably very rarely used. 

We also have the unit checker in https://github.com/ISISComputingGroup/EPICS-DbUnitChecker which is much better written and used more widely.

We should amalgamate the two to save having repeated code.

## Acceptance Criteria
* There is one codebase that checks everything we want to about DB files
* There are tests for this checker
* This is run as part of the Jenkins build

**Comment by Tom-Willemsen** [comment]
Also see DbChanges which uses a recursive descent parser for EPICS DBs as opposed to regular expressions

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/DbChanges

**Comment by JamesKingWork** [comment]
Work started, saving for next stand down day or if it gets prioritised. Branch: https://github.com/ISISComputingGroup/EPICS-DbChecker/tree/Ticket2745_harmonise_db_checking

**Comment by DominicOram** [comment]
Can you also update the wiki? https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Units-&-Standards
