### ISSUE TITLE
Genie_python: g.plot_spectrum(1) errors

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2748]
g.plot_spectrum(1) throws ERROR: 'QPixmap' object has no attribute 'setDevicePixelRatio'

This is referred to here:

https://github.com/matplotlib/matplotlib/issues/8562

Something is wrong and needs fixing. Also add an automated and/or manual system test.

**Comment by AdrianPotter** [comment]
Related ticket regarding genie_python system tests: https://github.com/ISISComputingGroup/IBEX/issues/2708
