### ISSUE TITLE
DAE: Spectra fail to update after 1-2 days

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2750]
The IMAT team has reported that DAE spectra stop updating after a day or two.

This is really #2668 it hold way more information

**Comment by FreddieAkeroyd** [comment]
See also #2668

**Comment by John-Holt-Tessella** [comment]
Also detector diagnostics (which may be related)

**Comment by ThomasLohnert** [comment]
+ 1 from Merlin

**Comment by FreddieAkeroyd** [comment]
This might be due to a thread dying on an unhandled exception, the above changes should make it more robust and hopefully stop the issue

**Comment by Tom-Willemsen** [comment]
How do I test that the fixes above really have fixed the issue? I couldn't see testing instructions on either of the linked pull requests.

Given that this issue has been around for a long time, we should also document how we came to the conclusion that it was uncaught windows structured exceptions that were causing this issue. Ensure that this is put on the wiki.

**Comment by FreddieAkeroyd** [comment]
In SpectrumPV::getNewValue() there is the call to getSpectrum now inside a try/catch, you could insert a throw std::runtime_error() here to see if it keeps going, maybe also try RaiseException() from  https://msdn.microsoft.com/en-us/library/windows/desktop/ms680552(v=vs.85).aspx

**Comment by FreddieAkeroyd** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dae-Spectra-Updating-Problem for solution details
