### ISSUE TITLE
IMAT: Out-of-date client

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2751]
Winfried has reported that the IBEX client on his desktop needs updating.

#### Acceptance Criteria
1. Update the client on Winfried's desktop PC.
1. Show Winfried how to install/update the client for himself.

**Comment by AdrianPotter** [comment]
Are there instructions for how to do this on the user manual?

**Comment by DominicOram** [comment]
I have sent Winfried a link to https://github.com/ISISComputingGroup/ibex_user_manual/wiki/InstallingIBEX#installing-ibex-client. Moving this straight to review complete as impossible to review.
