### ISSUE TITLE
GUI: Select block dialog only shows blocks in 'Other' group

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2755]
- Load a configuration with some blocks. It should include blocks both assigned and unassigned to named groups
- Open the "New synoptic" dialog
- Add a component
- Add a PV to the new component
- Click "Select Block" to assign a block to the component
- Only the blocks in group "Other" are available for selection.

## User story

As an instrument scientist, I would like to use the block selector to assign PVs to a synoptic component so I don't have to remember the meaning of PVs. This functionality is currently broken

## Acceptance criteria

- When performing the workflow above, all blocks are available to select
    - While there is no control to hide/show hidden blocks, the list should include hidden blocks

**Comment by AdrianPotter** [comment]
Investigate whether setting the block associates the block or the underlying PV (i.e. if you change the block PV, does it apply here too). Create a new ticket if necessary.

**Comment by DominicOram** [comment]
It does associate with the underlying PV, ticket created at https://github.com/ISISComputingGroup/IBEX/issues/2841
