### ISSUE TITLE
MAPS: Write VI wrapper for Fermi Chopper IOC

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#2759]
A hybrid VI/IOC system will be produced for the new Fermi chopper controller on MAPS to avoid duplication of work when the instrument is migrated to IBEX.  Therefore a VI needs to be written (using CALab) to provide an interface between SECI and the IOC (detailed in ticket https://github.com/ISISComputingGroup/IBEX/issues/2719).

**Comment by davidkeymer** [comment]
Code is in SourceSafe in "..\Drivers\FZJ DD Fermi Chopper"
Needs #2719 to be completed first.

**Comment by AdrianPotter** [comment]
Awaiting completion of #2719

**Comment by John-Holt-Tessella** [comment]
Ticket complete will test and review as part of commisioning ticket
