### ISSUE TITLE
Usernames changed via script do not persist

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2761]
Polaris reported an issue where user names changed as part of a script would revert again after one run. This resulted in a few subsequent runs being labeled with the wrong users. As a scientist I would expect the changes to persist until I explicitly change it again.

**Comment by kjwoodsISIS** [comment]
Some questions:
 - Are user names associated with RB Numbers or Run Numbers or both?
- As I understand it, RB Numbers come from the RB Number system.  If the user starts a new run, does IBEX fetch the RB Numbers details again?
- If the user wants to change user names during an experiment, should that change of names be propagated back to the RB Number system?
- Is there a document somewhere that defines how RB Numbers should be used?
- Is there a common understanding within ISIS of how RB Numbers should be used?

**Comment by mattclarke** [comment]
Are user names associated with RB Numbers or Run Numbers or both?
* Run numbers are just a way of identifying an experiment. The RB number and user end up in a NeXus file which is named as instrument_runnumber.nxs

As I understand it, RB Numbers come from the RB Number system. If the user starts a new run, does IBEX fetch the RB Numbers details again?
* No, or at least it shouldn’t. It should fetch the values already set in IBEX. E.g. if I set the RB to 23456 and put myself as the user then that should persist until I change either myself.

If the user wants to change user names during an experiment, should that change of names be propagated back to the RB Number system?
* There is no way of doing that, and I am sure the idea would be resisted by BusApps.

Is there a document somewhere that defines how RB Numbers should be used?
* No.

Is there a common understanding within ISIS of how RB Numbers should be used?
* Yes, to a point (see previous answer)

**Comment by KathrynBaker** [comment]
Related to this discussion are #2353, which we will have to ensure we have revisited before GDPR comes into force next May, #2669 (rework the whole system), #2606, #2418, #2396, #1976

Any changes to the handling of the RB Numbers and users has an impact on the ICP (the nexus file and potentially Mantid), involves the EXPDB service, INSTETC IOC and the ISISDAE IOC, as well as the GUI handling of the data.

Whilst we need to fix this bug, and the others mentioned above in amongst the rework and improvement tickets I listed, we do need to take great care.

If there is any documentation on how RB numbers should work it will be held by the business apps team, we are merely consumers of their data and attempting to provide it in a usable format locally. Changes to usernames and RB numbers (both can be considered in the same way as they are treated in the same way) are volatile as we only store them in the ‘local’ PVs, and not in our database, and there is no mechanism to alter the scheduler database from our side.

That volatility could mean that a config change would wipe out the changes that have been made.

**Comment by kjwoodsISIS** [comment]
I think Matt's replies helped point the right way to address this particular problem.
- on changing the RB Number, the user name PV should be set to corresponding value provided by the RB Number system.
- if the user changes the _local_ user name PV, then the old _local_ value is lost and the new _local_ value is persisted.
- nothing is sent back to the RB Number system.

If/when we come to re-work the whole system, we should write down (in detail) exactly how we expect the system to work before implementing anything.

**Comment by KathrynBaker** [comment]
But it is worth keeping the behaviour of both in the local system – the information I pointed to was only partially related to re-working the whole system, but even persisting the local changes requires us to be aware of and to ensure that we do not break the involved systems of the GUI, EXPDB, INSETC IOC and ISISDAE IOC.

**Comment by kjwoodsISIS** [comment]
>even persisting the local changes requires us to be aware of and to ensure that we do not 
> break the involved systems of the GUI, EXPDB, INSETC IOC and ISISDAE IOC.
In which case, we must also define how these sub-systems should behave when the user name is changed.  Defining this behaviour is an inherent part of resolving this "bug".

**Comment by KathrynBaker** [comment]
Things are markedly different by now, closing, any changes are liekly part of a larger discussion, reopen if I'm incorrect.
