### ISSUE TITLE
Eurotherm: Heater graph not displaying

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2762]
Polaris have reported an issue where the  heater output would stop being displayed halfway across the graph window on the OPI. The rest of the graphs worked fine. Try to reproduce this and investigate possible causes.

**Comment by AdrianPotter** [comment]
Might be to do with the graph's point buffer

**Comment by John-Holt-Tessella** [comment]
reproduced 
![image](https://user-images.githubusercontent.com/7570055/34936688-44223092-f9da-11e7-849d-6d48d898f1bf.png)

**Comment by John-Holt-Tessella** [comment]
Script to test using a rec simed eurotherm

import time
for i in range(101):
    g.set_pv("EUROTHRM_01:A01:SIM:OUTPUT", i, is_local=True)
    time.sleep(1.1)

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/620
