### ISSUE TITLE
LET: Oxford 9T Chopper Magnet

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2765]
As a scientist on LET I want to use the [9T Chopper Magnet](https://www.isis.stfc.ac.uk/Pages/9T-chopper-magnet.aspx).

#### Acceptance Criteria
1. Check & confirm whether the ILM/IPS/ITC503 combination are the only three drivers that we need to control this chopper magnet.
1. Check & confirm whether there are differences in the control logic between this chopper magnet and the 7.5T magnet.

#### Notes
1. The 9T Chopper magnet, like the 7.5T Cryomagnet, is controlled by 3 devices:
   - IPS (Intelligent power supply) (see tickets: #2593, #3075)
   - ILM (Intelligent level meter) (see ticket: #2593)
   - ITC503 (Intelligent temperature controller) (see tickets: #3189, #3284)

**Comment by kjwoodsISIS** [comment]
The 9T chopper magnet is an Oxford Instruments magnet controlled via 3 devices in a rack:
- IPS (Intelligent power supply)
- ILM (Intelligent level meter)
- ITC (Intelligent temperature controller)

The options for supporting the 9T chopper magnet are:
- pure EPICS solution: one IOC for each of the above devices, plus one over-arching IOC to coordinate the 3 device IOCs
- lvDCOM solution: lvDCOM the following VIs:
   - `C:\LabVIEW Modules\Oxford Software\SOLOITCFRONTPANEL\SoloITC503 - 1.vi`
   - `C:\LabVIEW Modules\Oxford Software\ilmapps.llb\ILMFrontPanel2.vi`
   - `C:\LabVIEW Modules\Oxford Software\Teslatron\Teslatron System Manager2.vi`
   - `C:\LabVIEW Modules\Oxford Software\Teslatron\TeslSetField2.vi`
   - `C:\LabVIEW Modules\Oxford Software\Teslatron\TeslSetTemp2.vi`

The IPS, ILM and ITC devices are due to be phased out over the next 12 months or so.  The current working assumption is the IPS, ILM and ITC devices will be replaced by Oxford Instruments Triton-based hardware control.  We already have plans to create IOCs to communicate with Triton devices.  It seems that implementing a pure EPICS solution could be a lot of work that would not be used for long - we'd only have to create a new solution anyway. Therefore, it woud be a better use of our effort to adopt the lvDCOM solution.  When the time comes for the 9T chopper magnet to be converted to Triton, we ought to have the relevant IOCs.

**Comment by kjwoodsISIS** [comment]
As far as I can determine:
1. `C:\LabVIEW Modules\Oxford Software\SOLOITCFRONTPANEL\SoloITC503 - 1.vi` has 9 read commands, 17 write commands
1. `C:\LabVIEW Modules\Oxford Software\ilmapps.llb\ILMFrontPanel2.vi` - reads 1 status record, outputs 1 status record
1. `C:\LabVIEW Modules\Oxford Software\Teslatron\Teslatron System Manager2.vi` has 6 read commands, 2 write commands
1. `C:\LabVIEW Modules\Oxford Software\Teslatron\TeslSetField2.vi` has 2 read commands, 1 write command
1. `C:\LabVIEW Modules\Oxford Software\Teslatron\TeslSetTemp2.vi` has 1 read command, 1 write command

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - to what extent can this ticket be considered implemented (given #2828 & #2886)?

**Comment by Tom-Willemsen** [comment]
The tickets linked above refer to the triton dilution fridge, so are unrelated. I am going to assume you meant to link the ITC503/IPS/ILM tickets. We have support for these devices in the context of a 7.5T magnet (the drivers have been run against the hardware, but not yet run in combination to ramp a magnet).

To complete this ticket, I think we need to:
- Check whether the ILM/IPS/ITC503 combination are the only three drivers that we need to control this chopper magnet.
- Check whether there are differences in the control logic between this chopper magnet and the 7.5T magnet.

**Comment by kjwoodsISIS** [comment]
Original issue text:

> As a scientist on LET I want to use the [9T Chopper Magnet](https://www.isis.stfc.ac.uk/Pages/9T-chopper-magnet.aspx).
> 
> #### Acceptance Criteria
> 1. I am able to create blocks and interact with the 9T Chopper Magnet in IBEX as I can in SECI - setting/reading the same values.
> 
> #### Notes
> 1. See also #2593 
> 1. The 9T Chopper magnet, like the 7.5T Cryomagnet, is controlled by 3 devices:
>    - IPS (Intelligent power supply)
>    - ILM (Intelligent level meter)
>    - ITC (Intelligent temperature controller)
> 1. Proposed solution - lvDCOM.  See comment below
> 1. All 3 devices listed above are generally connected in series via a ribbon cable and then into a single port of a MOXA.  Consequently, if a communication problem affects one device in the chain, it may make it difficult to communicate with other devices.  Something to be aware of when setting up on a new instrument.

**Comment by John-Holt-Tessella** [comment]
Looking through magnet 9T.comp Seci config. The controlling ini file is in TESLTRON.INI

- ilmapps.llb\ILMFrontPanel2.vi
    - Looks fairly standard assume this is same as all ILMs test on real
- SOLOITCFRONTPANEL\SoloITC503 - X.vi
    - Looks like to is just talking to the solo
TODO:


- Teslatron\Teslatron System Manager2.vi
- Teslatron\TeslSetField2.vi
- Teslatron\TeslSetTemp2.vi
- TeslSystemSetupDialog.vi
- ilmapps.llb\ILMSetupDialog.vi
- itcapps.llb\ITCSetupDialog.vi
- Psapps.llb\PSSetupDialog2.vi

**Comment by John-Holt-Tessella** [comment]
Pull request:

- https://github.com/ISISComputingGroup/EPICS-ioc/pull/346

**Comment by John-Holt-Tessella** [comment]
Tom/David: Test ok, changes to be made see ticket

**Comment by Tom-Willemsen** [comment]
Tests all ok with cryogenics. Nothing major showed up. I think this ticket can be considered complete (nothing to review).

A couple of small tweaks were requested by scientists / cryogenics, which are in #3942
