### ISSUE TITLE
SANDALS: Plot more than 4 spectra

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2766]
As a SANDALS scientist, I would like to be able to plot more than 4 spectra, so that I can see as many spectra graphs as I need.  A default of 4 spectra is fine, but I'd like to be able to add more spectra graphs, if I need them.

**Comment by Tom-Willemsen** [comment]
In response to an email asking to clarify the requirements:

> Hi Thomas,
> 
> This is probably a discussion to have with all four SANDALS and NIMROD instrument scientists (cc’d).  **At this very moment I can’t think of a compelling reason to have more than four spectra displayed simultaneously on either instrument**, but perhaps somebody else has?  One possible improvement might be to keep four graphs, but allow more than one spectrum to be plotted on each.  At the very least, having the option to display two spectra simultaneously on one graph might be useful in terms of displaying the incident / transmission monitors side-by-side.
> 
> Cheers,
> Tris.

(Emphasis mine)

**Comment by kjwoodsISIS** [comment]
If the scientists do change their mind, we'll create a new ticket.
