### ISSUE TITLE
GUI: Enable Auto-restart setting only when auto-start is enabled

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2767]
The user manual states on [Auto-Restart](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/CreateandManageConfigurations#iocs-tab):
>This setting only applies if auto start has been selected as well, otherwise it does nothing. [...]

If this is the case, then the auto-restart checkbox should only be enabled when auto-start is selected.

**Comment by kjwoodsISIS** [comment]
In this instance the manual should be updated to reflect the actual behaviour.
Also: write a test to make sure the behaviour does not regress.

**Comment by ThomasLohnert** [comment]
Updated the user manual to reflect actual behaviour. There are tests that cover this functionality in the manual system tests spreadsheet. Closing this issue.
