### ISSUE TITLE
Asyn: add a "break on every write" option.

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2768]
A serial break is not a series of characters but a fundamental "thing" you can do to a serial line.

This is required for ticket #2397 (fermi chopper).

Plan is to implement an option in the asyn driver that sends a serial break on the end of every message.

**Comment by FreddieAkeroyd** [comment]
* Added a "break" option to asynSetOption - specify break length in milliseconds
* A break will be asserted after every write

To test:
* if kit requiring a serial break is not available, try it on existing equipment to see what happens
* enable ASYN_TRACE - you should see the words "with BREAK" displayed when number of bytes written is printed
* you might be able to see a break with a serial port sniffer

**Comment by Tom-Willemsen** [comment]
Tested by:
- Connected to eurotherm without asyn break option - behaviour was unchanged
- Connected to eurotherm with new asyn break option - things started timing out indicating that something was happening differently.
- Enabled asyn trace and the new message was correctly printed ("with BREAK")
- We don't have access to a device that requires serial breaks so I can't test that it works 100% correctly but I've reviewed the code and it looks sensible.
