### ISSUE TITLE
web dashboard: display shutter status

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2769]
As a MERLIN instrument scientist I would like to see the shutter status displayed on the IBEX web dashboard.

NOTE:  shutter status is displayed on SECI web dashboard

NOTE: muons don't have a shutter and the status of their kicker is displayed instead, so the code changes should allow for a "group of instruments" alternative to shutter to be used at a future date.

**Comment by DominicOram** [comment]
RE note about different shutter status at a future date, this uses the same PV as the GUI's shutter status, a future solution for groups of instruments should be done as a separate ticket that will change this PV.
