### ISSUE TITLE
Indication that detectors have failed

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2771]
Requested by Vesuvio at their sprint demo.

As an instrument scientist, I would like some visual indication if the detectors on my instrument fail, 
 
Some ideas of potential implementations (suitability to be discussed):
- Create blocks for detectors
- Count rate zero while shutter open and ISIS beam up.
- Read the state of the detector power supply directly. Might be a CAEN.

**Comment by FreddieAkeroyd** [comment]
The ISISICP has the basis of this sort of functionality, I started to add it for WISH. It can look for zero counts in a spectrum or (better) a detector module that sums to zero counts, having zero counts/count rate for a single detector element could be expected for a single crystal or short run so one has to be careful about false positives.

**Comment by ChrisM-S** [comment]
Do they have a 2-d detector bank plot on Vesuvio?
This can be a very intuitive visual way of seeing detectors that are simply are not counting (they just show up as black squares/lines amongst others with a heat map for counts).  The pattern of blanked elements can also lead to diagnosis of a fail PM tube or PSU channel.

**Comment by FreddieAkeroyd** [comment]
Indeed failed detectors do show up quite easily in the Mantid instrument view, but the data may not be looked at until some time after the event so an early warning would be useful to save beamtime loss.

**Comment by Tom-Willemsen** [comment]
detector diagnostics view can be used for this
