### ISSUE TITLE
genie_python: ValueError when setting enumerated values

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2775]
As anyone running genie_python, I would like to be able to set PV values on enumerated types without it generating an error so that I can reliably run my scripts.

This was discovered whilst doing the IEG automated system tests. To reproduce the bug:

- Make sure you have the latest version of `genie_python`
- Change the IEG automated system tests to write directly the values `LOCAL` and `REMOTE` instead of `0` and `1`
- Run the tests

You should get an error saying that the given value is not a valid alarm severity.

This appears to be an issue in our channel access wrapper that was introduced when we moved to CA 3.0.

**Comment by John-Holt-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/genie_python_system_tests/pull/1
https://github.com/ISISComputingGroup/genie_python/pull/99

**Comment by John-Holt-Tessella** [comment]
- [ ] Once merged point the build gen_pytho System tests at the master branch
