### ISSUE TITLE
General: User Defined Arbitary PVs

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2776]
As a LARMOR and MUONFE instrument scientist I would like to have a PV which I can use to store information so that I can either replace a block from a (faulty) device or add information to my NEXUS file or keep track of some long term instrument value.

**Comment by FreddieAkeroyd** [comment]
I believe this feature already exists via   user_parameres.db   that is loaded by INSTETC

**Comment by John-Holt-Tessella** [comment]
Indeed there is. We should document this in the user manual. I will propose.

**Comment by John-Holt-Tessella** [comment]
It may also be useful for users to create arbitrarily many variables. Add a macro for this that can be set in globals.txt.
