### ISSUE TITLE
Dataweb: Order blocks to be in the same order as in IBEX dashboard

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2777]
As an MuonFE instrument scientist I would like the blocks on the dataweb to be ordered the same as in my IBEX dashboard.

Acceptance Criteria:

1. Groups are ordered top to bottom as they are order left to right in the dashboard.
1. Within each group blocks are ordered the same

**Comment by Tom-Willemsen** [comment]
Re-requested by James Lord
