### ISSUE TITLE
GUI: Reconnect to NICOS when connection fails

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2781]
As a user I would like the connection to NICOS to be re-established when it fails. To do this we should implement a heartbeat to NICOS and retry the connection when this heartbeat fails.

**Comment by ThomasLohnert** [comment]
Something I found testing https://github.com/ISISComputingGroup/ibex_gui/pull/583 which might be good to know for this is that the `nicos-daemon` automatically disconnects the client after 1 hour of inactivity

**Comment by ThomasLohnert** [comment]
Also make sure Nicos reacts to changing instruments (i.e. does not just stay connected to the previous instrument's script server)

**Comment by kjwoodsISIS** [comment]
Already fixed.
