### ISSUE TITLE
Climbing CPU usage in client

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2790]
As a developer, I would like the IBEX client not to use a constantly increasing amount of CPU. 
As an instrument scientist, I don't want to have to restart my IBEX client every so often because it becomes too slow.

@GDH-ISIS pointed out a nagios graph where the IBEX client CPU usage was climbing constantly (on Merlin, 19/11/2017).

I have also seen high CPU usage on my local client after leaving it open for a long time.

We should find the root cause and eliminate it.

**Comment by kjwoodsISIS** [comment]
Please recommend some profiling tools to identify which parts of the client are consuming the CPU time.

**Comment by Tom-Willemsen** [comment]
I've used the Java visual VM before for debugging a memory leak and it's fairly good - it will show quite clearly how many threads the GUI has, and which methods are using the most CPU time.

**Comment by GDH-ISIS** [comment]
![ibex client cpu](https://user-images.githubusercontent.com/13995522/33012417-b87291fe-cdd8-11e7-9124-f28bf717ba58.jpg)

**Comment by Tom-Willemsen** [comment]
Has also been seen on ENGIN-X, see nagios graph 23/3/2018
