### ISSUE TITLE
mk3chopper: investigate recovery from connection failure

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2791]
On ENGINX the chopper IOC started up after the power outage, was unable to talk to the chopper and so configured 0 choppers and loaded no DB files. It was then happy as there was no communication configured, and required a manual restart once the network was recovered:

2017-11-20 12:32:44] mk3DriverConfigure("MK3", "C:/LabVIEW Modules/Drivers/ISIS MK3 Disc Chopper/MK3_Chopper.config", 0) 
[2017-11-20 12:32:44] *** Initialising MK3 Interface *** 
[2017-11-20 12:32:44] Using real chopper 
[2017-11-20 12:32:44] Config file = C:/LabVIEW Modules/Drivers/ISIS MK3 Disc Chopper/MK3_Chopper.config 
[2017-11-20 12:34:08] sevr=major Unknown .NET errorThere are 0 choppers on this controller

However on IRIS it also reported 0 choppers but this time loaded 2 DB files and so then continued to report

[2017-11-20 17:17:05] sevr=major Unknown .NET error

They moved to SECI so I don't know if it would have auto-recovered OK. 

I notice on IRIS they have in globals.txt

MK3CHOPR_01__CHOPPER_1_PRESENT=" "

whereas on enginx they have

MK3CHOPR_01__CHOPPER_1_PRESENT= 

The IRIS definition style looks to ensure choppers are always configured,  but maybe we don't want to assume 0 choppers on a .NET failure if things are set to auto-detect choppers

**Comment by John-Holt-Tessella** [comment]
I think the configuration should detect what the sample environment should look like. If the users can not talk to a device that should be there, there should be an alarm. If they did an experiment without a chopper this would presumably be not useful.

**Comment by KathrynBaker** [comment]
I think something similar has just been seen on ZOOM, restarting the IOC reconnected the chopper, and it did keep saying that it was disconnected.

**Comment by KathrynBaker** [comment]
Seen again on IRIS, call to support phone about it

**Comment by John-Holt-Tessella** [comment]
See #2943 does this fix it? If so we need to think about a release of this either as a hot fix or as a full release.

**Comment by KathrynBaker** [comment]
That’ll be the error in question. It might be worth considering a hotfix of that particular IOC

**Comment by John-Holt-Tessella** [comment]
Email sent out I am changing this to a support ticket.

**Comment by John-Holt-Tessella** [comment]
Impeded: Waiting for replies to emails.

**Comment by John-Holt-Tessella** [comment]
Doing everything during shutdown

**Comment by kjwoodsISIS** [comment]
How many points was this?
