### ISSUE TITLE
SANDALS: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2797]
As an instrument scientist, I would like to migrate SANDALS to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on SANDALS
1. Configuration files matching the current SECI config files are created
1. IBEX is configured for the devices on SANDALS.
1. SANDALS scripts are converted to genie_python
1. SANDALS scientists are trained in how to use IBEX
1. IBEX is tested on SANDALS

#### Notes
1. The devices on SANDALS are listed on the [SANDALS Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/SANDALS-Instrument-Details) list
1. The following tickets should be implemented prior to deploying IBEX on SANDALS
   - [x] #2707
   - [x] #2687
   - [x] #2839
   - [x] ~#2840~
       - GEM Mercury Cryostat "highly unlikely" to be used this cycle
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for SANDALS.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
- [x] Check that NDXSANDALS has sufficient disk space to install IBEX
- [x] Check whether SANDALS uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [ ] Create a virtual instrument for testing purposes
   - [x] Set up a test system, NDXSANDALSTEST.
   - [ ] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
   - [ ] test these configurations & scripts
   - [ ] check that all the devices previously supported by SECI (on SANDALS) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
   - [x] demonstrate the configurations & scripts (created above) to the instrument scientists and check that they are happy with the migrated configurations & scripts

**Comment by Kevin-Woods-Tessella** [comment]
I have (twice) e-mailed the SANDALS scientists to ask them to identify the configs & scripts they wish to migrate.
if they don't respond soon, I suggest you log on to NDXSANDALS and pick the most recently used config(s) and script(s) as a starting point.  You can use the "last access date" (as provided by the DIR command) as a proxy for "most recently used".

**Comment by AdrianPotter** [comment]
Emailed Anthony Shuttle/FIT to ask about private networks

**Comment by ChrisM-S** [comment]
For steps to change an instrument to 8 digit run numbers (quite a few things to do in different places), please see control tasks [https://github.com/ISISComputingGroup/ControlsWork/issues/158]().

**Comment by kjwoodsISIS** [comment]
The tasks in  [https://github.com/ISISComputingGroup/ControlsWork/issues/158](https://github.com/ISISComputingGroup/ControlsWork/issues/158) are somewhat specific to SECI.  It would be better to have an similar set of instruction for IBEX (and better to have them in a Wiki, rather than an ticket).

**Comment by ChrisM-S** [comment]
Agreed, except that we can't take anything SECI specific out until we remove any possibility of reversion to it (or we will have really screwed up data files).

**Comment by AdrianPotter** [comment]
Setting to impeded awaiting outstanding tickets

**Comment by FreddieAkeroyd** [comment]
Just for clarification: 5 or 8 digit runs numbers are supported both by IBEX and SECI and the use of 5 digits rather than 8 does not indicate any particular age of the ISISICP rather a preference of the instrument (the ISISICP on SANDALS is fully capable of 8 digits). MERLIN remained with 5 digits when moving to IBEX, SANDALS can do the same if they wish (they have only taken 66000 runs to date so are unlikely to overflow 5 digits for a while). While the full instrument name + 8 digits is preferred, there are sometimes operational reasons (e.g. analysis software) to remain with 5; any change in raw file naming also needs to be coordinated with Mantid. Sandals will need an ISISICP update though to correctly write sample environment information with IBEX, as per http://beamlog.nd.rl.ac.uk/inst_summary.xml SANSALS are running SVN revision 842 of ISISICP which is the original TS2 version (what HRPD were running prior to moving to IBEX), they need to be running at least SVN 1633 for IBEX

**Comment by AdrianPotter** [comment]
Thanks for the clarification @FreddieAkeroyd. Does this need a Controls Work ticket do do or can I leave it with you?

**Comment by AdrianPotter** [comment]
Follow up from my meeting with Sabrina this morning

- Sandals has plenty of disk space free (>100GB)
- They don't use the Mercury very often. Sabrina will find out whether it's being used next cycle
- I could not find the OpenGENIE file where the procedure "sample" is defined anywhere on their system. I will post to Slack to see if someone knows where I might look

**Comment by GDH-ISIS** [comment]
Not sure, but try :
\\ndxsandals\c$\Users\spudulike\Documents\Configurations\COMMON\gcl\sandals_routines.gcl
At the bottom, you will see 
ALIAS "sample" "sandals_sample"

**Comment by AdrianPotter** [comment]
Yep, thanks. Found as per the discussion on Slack. I'll add the (slightly obfuscated) path to the wiki for future reference.

**Comment by AdrianPotter** [comment]
There are 3 routines to be migrated in `sandals_routines.gcl`

- [x] ~START_DAE_MONITOR~: Just opens the associated VI. Won't be migrated
- [ ] SETEURO1: Sets the Eurotherm. Fairly straightforward.
- [x] ~SANDALS_SAMPLE~: Aliased to "SAMPLE". Opens the Sample changer VI, moves to a new position and closes the VI. I don't think (and @John-Holt-Tessella agreed) that this needs migrating. It should just be done in place with a `cset`. I'll do it that way in the migrated scripts.

**Comment by AdrianPotter** [comment]
Setting back to impeded awaiting the sample changer

**Comment by John-Holt-Tessella** [comment]
I have added motion setpoints and axes the sample changer will need to be setup. It needs a motor SM300 and a synoptic which includes the SM300 sample changer.

**Comment by FreddieAkeroyd** [comment]
ISISICP now updated, but not yet enabled for MySQL

**Comment by AdrianPotter** [comment]
Sandals installed, just awaiting meeting with instrument scientists. 

@FreddieAkeroyd, what does it mean that ISISICP isn't enabled for MySQL? Does that mean it won't write run info to the DB? MySQL is now installed, so can it be enabled?

**Comment by AdrianPotter** [comment]
MYSQL has been enabled

I've been down to the instrument and demonstrated the system to Sabrina and Silvia and they seem happy with the setup. There is some work they'd still like to do to get their instrument scripts exactly how they'd like. I'll do that under a different ticket

**Comment by Tom-Willemsen** [comment]
IBEX is deployed on SANDALS.

In terms of the review:
- I've had a look at their configs, synoptics, DAE tables. They all look plausible.
- I had a look at the scripts and they seem nicely written (though I am aware that there is another ticket to look at these a bit more).
- I had a look at the logs that have been generated during their first few days using IBEX to scan for any obvious configuration errors, and didn't find any.
