### ISSUE TITLE
GEM: Vacuum Valve Status

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2798]
As a GEM scientist, I want IBEX to monitor & log the status of the vacuum valves.  

#### Acceptance Criteria
1. I can view the status of the GEM vacuum valves on the IBEX GUI
1. I can query the status of the GEM vacuum valves from genie_python
1. The status of the GEM vacuum valves is logged.

#### Notes
1. GEM is to have two vacuum valves
   1. one controls vacuum to the beam pipe
   1. the other controls vacuum to the sample tank
1. The valves will be controlled by a PLC
   1. IBEX only needs to monitor and log the status of the valves
   1. The PLC controls the valves (not IBEX).
   1. The valve statuses should be created as blocks in the base configuration
   1. The PLC is a [Schneider Electric Quantum PLC](https://www.schneider-electric.co.uk/en/product-range-download/538-modicon-quantum)
1. There may or may not be TPG-300 pressure gauges involved (to be confirmed).
1. PLC output locations to be advised by Tim Carter.

**Comment by DominicOram** [comment]
Are we also creating/do we already have a VI for this so that GEM has a SECI fallback?

**Comment by kjwoodsISIS** [comment]
Good question.  I can see no sign of a Schneider PLC in the current set of LabVIEW modules.  I think we'll have to create one.

**Comment by kjwoodsISIS** [comment]
> 
> From: ICP On Behalf Of Freddie Akeroyd
> Sent: 30 November 2017 12:51
> To: ICP
> Subject: Re: [ICP] GEM Vaccum System & Schneider PLC
> 
> Looks like you can use the EPICS Modbus driver 
> http://www.lnl.infn.it/~annrep/read_ar/2013/contributions/pdfs_05-07-2014/217_G_48_G043.pdf
> 
> 
> From: ICP On Behalf Of Freddie Akeroyd
> Sent: 29 November 2017 15:54
> To: ICP
> Subject: Re: [ICP] GEM Vaccum System & Schneider PLC
> 
> The muon front end has a Schneider PLC, but probably a different model. That one speaks MODBUS, but we are currently pulling values off its web interface for Nagios. 
> 
> Freddie
>

**Comment by kjwoodsISIS** [comment]
> 
> From: Carter, Tim (STFC,RAL,ISIS) 
> Sent: 01 December 2017 17:00
> To: Akeroyd, Freddie (STFC,RAL,ISIS)
> Cc: Baker, Kathryn (STFC,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Subject: RE: Test PLC for GEM work
> 
> Hi Freddie / Kathryn,
> 
> We can lend you the Quantum PLC in the attached, shown with reference to a PC monitor. 
> This has the full suite of Modbus, Modbus Plus and Modbus TCP/IP ports. 
> 
> I will need to get it PAT tested, as it is mains powered, and hopefully we can get that done 
> on Monday. I would have preferred to give you a 24V powered version, but we don’t have 
> many spares so require these for operational purposes. 
> 
> As it is, the PLC is as silent as it can be.  
> 
> We will need to set up the PLC’s Network settings for you. Please can you let me know 
> what IP Address, Subnet Mask and Gateway settings you wish us to program into the 
> Ethernet module?
> 
> Many thanks,
> 
> Tim
>

**Comment by KathrynBaker** [comment]
Please note that this work will also have an impact on RIKEN Front End

**Comment by FreddieAkeroyd** [comment]
We have a loan PLC from Tim Carter and I was able to create an initial test IOC and talk to it with Modbus tcp

**Comment by AdrianPotter** [comment]
Assigning to @FreddieAkeroyd who has already started working on it. As far as I can see the code is not yet in GitHub. Is that correct?

**Comment by FreddieAkeroyd** [comment]
Branch not pushed yet as very little to push (a few lines in a st.cmd to configure Modbus). TCP worked straight away, RS232 didn't seem to work before Christmas but does now! Need to use a Schneider RS232 cable but works OK when this is fed into a moxa cable.

**Comment by FreddieAkeroyd** [comment]
Will merge base code now for initial release, but awaiting details of PLC registers
