### ISSUE TITLE
Block disconnected on IOC restart

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2799]
Reported by Saurabh - he restarted the instron IOC and the position/stresss/strain PV went disconnected and never came back. If you right click on the PV and go to block history, then it gives a graph that updates OK. So it looks like PVManager is working OK, but somehow the block -> pvmanager interaction has missed the change of state from disconnected to available?

**Comment by John-Holt-Tessella** [comment]
It would be worth looking at the block object and making sure it has the correct synchronisation, see if it suffers from a similar bug as the dae command buttons. If it isn't this it could be a lot of effort and then it will be replaced by the Eclipse 4 layer. Shall we change the ticket to ensure that the synchronisation is correct and if it is add it to the issues we can not trace page (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Issues-which-arise-which-we-can-not-trace).

**Comment by Tom-Willemsen** [comment]
Mitigated by "refresh pvs" functionality, other tickets track general slow reconnections in the gui more generally.
