### ISSUE TITLE
Issue with title/rb/users when moving between SECI and IBEX

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2800]
Reported by Dominc Fortes on HRPD.

We switched HRPD back from SECI to IBEX on Saturday morning, and this was done in the manner stipulated without any apparent problems. However, the first scripted change in run title resulted in IBEX (and the Dataweb) displaying the last title from the previous user, as well as resetting the RB number and other user details.  I changed these back by hand when I noticed it and all subsequent title changes proceeded as scripted. What I failed to notice until last night is that, although IBEX was displaying the correct RB and users, the Dataweb was not and what is recorded in the Journal Viewer is actually the previous user’s RB number and names. Runs 68900 – 68917 thus have the incorrect rb/user.

Sequence of events was IBEX started and user and rb set in Ibex, but the first scripted change of title lead to an incorrect title and the rb and user being reset, and a subsequent reset of user/rb in ibex didn’t change what was recorded in the journal/dataweb/data files. Indeed when we changed user this morning (Monday), Alex stopped and restarted the IBEX server in an effort to clear this problem and the first thing it did on re-opening was to show the title from the last run done in SECI by Simm et al., two days previously

**Comment by Tom-Willemsen** [comment]
I think Ron Smith (Polaris) may have reported this in the past as well, but I couldn't find the ticket.

**Comment by kjwoodsISIS** [comment]
The issue reported by Ron Smith is #2761

**Comment by FreddieAkeroyd** [comment]
Correct RB is 1720175 and users "Tarakina and Fortes"

**Comment by FreddieAkeroyd** [comment]
It looks like SECI was briefly started again on both Saturday afternoon and Monday morning, I'm not sure yet how/why that happened but is likely the cause of the RB number and username being reset.

**Comment by FreddieAkeroyd** [comment]
Both incidents have now been confirmed as accidental SECI restarts, SECI has now been unpinned from the task bar on HRPD. It might be possible to get SECI to resync the RB number back from IBEX, but I'm not sure it is worth it - avoiding the potential for accidental restarts is probably enough (and updating notes to scientists that starting SECI will reset RB/user etc.)
