### ISSUE TITLE
Webdashboard: Give others access to the hosting machine

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2804]
As a developer I would like to be able to update the web dashboard without asking a specific developer to do it for me.

Currently there are only 2 or 3 people that have access to the externally facing machine that hosts the webdashboard and others. This introduces a risk if there is a webdashboard issue and these people aren't around.

There should be a joint account (IBEX builder?) that all devs can use to update the website.

**Comment by AdrianPotter** [comment]
Related to: https://github.com/ISISComputingGroup/IBEX/issues/2128?

**Comment by DominicOram** [comment]
IBEX builder now has access.
