### ISSUE TITLE
RIKEN Front End: Changeover logic

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2813]
As a RIKEN scientist, I need to be able to undertake a port changeover with minimal button presses and interactions, this will involve interactions between the PSU IOCs and the PLC.

**Acceptance Criteria**
1. There is an IOC which has the ability to enact the logic as is available [here](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/RIKEN%20FE/RIKEN%20PSU%20Controls.ppt)

**Notes**
1. There are **2** different changeover sequences to code.
1. This IOC will need to deal with the PSUs, turning them off and inhibiting as appropriate.
1. This IOC will need to be able to accept an input from the PLC, this might be direct, or via some cDAQ, and as such should be configurable.
1. This is needed to avoid lost time
1. Ticket #2798 is a similar PLC, and whether these can be interacted with directly or not will affect whether or not to use the PLC directly or a cDAQ solution.

**Comment by kjwoodsISIS** [comment]
Where is the changeover logic documented?  What is the sequence of operations? How should errors be handled (e.g. if a device fails to respond as expected)?

**Comment by KathrynBaker** [comment]
There is a link, which is active on GitHub, but might not be active in the email, sequence of operations is in the same document.

Errors are more of a standard operating issue for this rather than something to consider specifically.
