### ISSUE TITLE
MAPS: OPI for FZJ Prototype Fermi Chopper

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#2814]
An OPI is required for the FZJ Fermi Chopper (IOC detailed in ticket https://github.com/ISISComputingGroup/IBEX/issues/2719) when MAPS is migrated to IBEX.

Strictly speaking, the work doesn't need to be done until the sprint before the migration (at the latest).  However while the IOC and associated work is in progress, the OPI would be easier to produce.

The OPI may be able to be based on that for the MERLIN Fermi chopper (also manufactured by FZJ), which has a very similar set of parameters.  See ticket https://github.com/ISISComputingGroup/IBEX/issues/2358 for details.

**Comment by Tom-Willemsen** [comment]
When done, please update synoptics on MAPS config to point at this OPI.

**Comment by Tom-Willemsen** [comment]
Re-proposing because they are now using this chopper.

**Comment by davidkeymer** [comment]
needs #2856

**Comment by davidkeymer** [comment]
Pull Request: https://github.com/ISISComputingGroup/ibex_gui/pull/693

**Comment by AdrianPotter** [comment]
Freeing up so someone else can review
