### ISSUE TITLE
IRIS: missing values from NeXus file

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2818]
IRIS reported some sample environment values were missing from their Nexus data file. For example run 76847 is missing the Sample block that is present in 76846 and 76848. This value is not changing very much, and it is present in the .LOG file. Normally you should see an unchanging value twice, it is flushed at start and end of run. in 76846 and 76848 both values are seen, but in 76847 only the final value is seen. So missing values in the Nexus file seem to correlate with a missing initial flush of values from the archive engine.

**Comment by FreddieAkeroyd** [comment]
This looks to be a combination of things. The values are missing as MySQL queries are taking a long time in some circumstances, as detailed in the MySQL slow query log. The ones with "grp_id" are from the ISISICP at end of run, queries over 10 seconds appear in the log. The ISISICP has a timeout on waiting for data, if the query is not much over 10 seconds you are probably OK. Also if the time between runs is reasonable you will be OK too as in cases of short run turnaround the MySQL query took so long the values flushed from the start of the next run ended up in the previous run. Though there seems to have been slow queries for some while, having an unpatched ARACCESS process running leads to some very long queries (~minute). The ARACCESS process has been disabled on all but ENGINX, though the remaining slow queries are a concern they have probably been present for a while and noticeable problems not been reported. Their presence is instrument/database size dependent - not all instruments are showing issues.

The slow queries can likely be fixed by a change to the ISISICP to optimise one of the SELECT queries, also better handling of long queries can be looked at.

**Comment by Tom-Willemsen** [comment]
Verified on a selection of beamlines that there are no slow queries any more. Checked IRIS, ENGINX, VESUVIO, HRPD.
