### ISSUE TITLE
Evaluate Test Frameworks for Eclipse 4 UIs

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2819]
RCPTT does not work in eclipse 4. At a meeting, it was decided to create prototype UI tests in a small number of frameworks to test their suitability.

For each testing framework:
- Configure it to launch our E4 client. Document how easy it is to configure.
- Migrate a simple, stable test. Document how difficult it is to create a simple test.
- Migrate a more complicated/unstable test. Document how easy it is. Document whether it is more or less stable than the equivalent RCPTT test.
- (If possible) Set up the test to run on Jenkins.

The same tests should be migrated for each framework. The suggested testing frameworks to start with are:
- Squish
- SWT bot
- ~Julaba~ Jubula
- AutoIt (?)

Kevin to check with Tom G about licensing fees for the commercial frameworks.

Acceptance criteria:
- [ ] Prototypes are created for each of the test frameworks above
- [ ] A list of pros/cons for each of the test frameworks is produced

**Comment by kjwoodsISIS** [comment]
I have obtained list prices for Squish.  They also offer discounts if we can contribute an article/case-study for their web-site.  Tom G is considering these.

**Comment by kjwoodsISIS** [comment]
Licensing Squish seems to be a real possibility - it would make sense to evaluate it first.  FrogLogic offer a [free-trial of Squish](https://www.froglogic.com/squish/free-trial/).

**Comment by kjwoodsISIS** [comment]
Other tools are noted here: http://www.softwaretestinghelp.com/best-gui-testing-tools/

**Comment by AdrianPotter** [comment]
AutoIt is the first framework I've been able to get working. 

- Squish is waiting for approval to use the evaluation copy 
- SWTBot appears to be having difficulty downloading from the Eclipse marketplace
- Jubula is blocked by the SWTBot download.

-----------------------------------

# AutoIt

First impressions are that this won't work for us as a system testings framework. The installation is very easy and I've gone through the getting started guide quite quickly. The big thing to point out is that this is an automation program, not a testing program. You can create scripts for it to run through, but there's no feedback as to whether a test passes, certainly not in an xUnit form consumable by Jenkins. I found a 3rd party script that functioned nominally as a unit test framework but the non-native support does not count in AutoIt's favour.

Similarly, the scripting is not straightforward. We'd require learning a new scripting language as Java and Python are not supported. Further, the recording tool that was available in earlier versions has been removed, making the writing of complex tests potentially very complicated.

Based on these criteria, I don't think it is a contender.
As per the original test criteria:

- Configure it to launch our E4 client. Document how easy it is to configure.
- Migrate a simple, stable test. Document how difficult it is to create a simple test.
- Migrate a more complicated/unstable test. Document how easy it is. Document whether it is more or less stable than the equivalent RCPTT test.
- (If possible) Set up the test to run on Jenkins.

**Comment by AdrianPotter** [comment]
@Kevin-Woods-Tessella, do you have any suggestions for how this ticket should be reviewed? If the recommendation is accepted, what is the next step?

**Comment by kjwoodsISIS** [comment]
I think we can do one of two things:
1. we can ask people to read the findings (documented in this ticket) ahead of next week's stand-down day.  We can then have a short discussion and make a decision.
2. Do the same thing ahead of the normal Sprint Review.
In any event, we should reach a decision by the end of the current sprint.

If the recommendation is accepted, we should proceed to purchase.  We'll need to do this via Tom, but we already have authorisation in principle to go ahead.  FrogLogic are offering us a discount on Squish, provided we provide a short article, by way of a reference.  STFC policy means this reference cannot be an endorsement of Squish, but we can describe why we chose it and how we are using it.

**Comment by kjwoodsISIS** [comment]
Having read @AdrianPotter 's analysis of testing frameworks, it does seem that Squish is the stand-out leader.  Given the view that it is far superior to RCPTT, what is there to lose by choosing not to use it?  I should also say that my previous experience of FrogLogic was that they provide excellent technical support.  I am sure they could help us resolve some of the limitations we have encountered.

**Comment by AdrianPotter** [comment]
I think a short demonstration and discussion at the sprint review would make sense.

By not using it, we'll no longer be able to keep doing automated UI tests when we migrate to E4. We can continue to use RCPTT in E3 if we choose. If we have no automated UI tests then:

- Manual testing at release time will take much longer. Our release testing currently takes about a day, which is down from five days when we did it all by hand.
- We won't catch failures in the UI as quickly when they are introduced. Arguably the existing tests have found far more false positives than true positives but that may be more of an RCPTT issue than UI testing in general. We have caught several notable failures.
- It becomes harder for us to interact with the GUI via a script. This has notably been invaluable when bugs are found that are only triggered under hard to reproduce conditions.

One thing I haven't tested with Squish is automated OPI testing. We could do that in RCPTT owing to limitations in the framework.

**Comment by AdrianPotter** [comment]
You have to drill down through about 30 layers of object hierarchy but from my limited test you can interact directly with controls in OPIs which is a major potential advantage over RCPTT.

**Comment by AdrianPotter** [comment]
Discussed at sprint review. Consensus was to proceed with purchase
