### ISSUE TITLE
IRIS: run control never exits

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2820]
Reported as loss time report 1838. Two blocks (H2Temp and ISIS_freq) went briefly out of range at around 18:30 on 5th December, the message to the DAE to resume collection after they went back into range was not received for as yet unknown reasons. The situation was fixed when a new run was started, this forces a recheck of all run-control ranges and status. 

To fix this, add an automatic periodic check of run control consistency to ibex so if a stop/start message gets lost in future it should spot the situation and correct it

**Comment by FreddieAkeroyd** [comment]
To test:

You can put the DAE in and out of waiting by writing to $(P)DAE:STARTSEWAIT and $(P)DAE:ENDSEWAIT respectively, note that you only go into waiting if you are, or would be, "running" so for example sending "startsewait" when you are PAUSED will leave you in paused, but when you next resume it will have remembered the "startsewait" and put you into WAITING rather than RUNNING etc.

So test various combinations of sending startsewait and endsewait and check the system recovers correctly after its ~5second poll time. E.g.:
- no run control or everything in range, put in into waiting and check it goes back to running
- in waiting, write to "endsewait" to make it running and then check it automatically recovers waiting
- in paused, adjust limits and/or write to start/end sewait and check it stays in paused and then resumes to the correct state when asked (or to the correct state within 5 seconds of resuming)

**Comment by Tom-Willemsen** [comment]
Tested as described, appears to work.

I added release notes for you.

**Comment by FreddieAkeroyd** [comment]
Thanks - I did add it in a bit of a rush and forgot!
