### ISSUE TITLE
MYSQL error log messages

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2822]
Since September LogError.err on NDXIRIS and elsewhere are showing quite a few "Aborted connection" messages at level [Note], the old (pre September) NDXIRIS.err does not have these but has other entries at [Note] level so I assume it is not just a log level setting. Maybe the newer MySQL logs aborted connections whereas the older one didn't, or do we have an issue with connection management? I've seen some reports that this might be due to connection pooling in the MySQL connector, it re-uses client connections but the server might already have closed the connection if there is a disagreement over timeouts between the two. Is it we need to update the MySQL python connector or check some of our timeout values?

**Comment by Tom-Willemsen** [comment]
No longer happening. MySQL & connectors have been updated many times since 2017.
