### ISSUE TITLE
MUONFE: recover from disconnected power supplies

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2823]
As an instrument scientist I would like my power supplies to recover from a network outage. The R55 hub room switch was power cycled this morning to fix a network issue, this temporary outage caused the TDK power supplies on MUONFE to stop working (the danfysik ones recovered ok). The failure modes appears to be that you can still send commands to the power supply with no error in communication, but no reply is ever received and so all the epics records go into alarm timeout. Restarting the IOC fixes things, I suspect the power supply needs a reinitialisation command sending to it or something like that. 

We need to investigate if such a situation of excessive timeouts can be detected and handled in a generic way within stream device and/or asyn. Maybe an @replytimeout handler on one of the values would be enough.

**Comment by KathrynBaker** [comment]
That would probably fix it, there is a 'handshaking' exercise that is done on startup, otherwise, the Genesys doesn't get into the right state. I have added this ticket into my priority lists, having picked it up from the IBEX Roadmap

**Comment by John-Holt-Tessella** [comment]
This also needs to be done for the DANFYSIK 8800s. They send the address on connection and if this doesn't happen the DANFYSIK ignores the ioc.

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/65
- https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/7
- https://github.com/ISISComputingGroup/EPICS-TDKLambdaGenesys/pull/3
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/288
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/100
