### ISSUE TITLE
2915-1: Triton Dilution Fridge IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2828]
As a scientist working on MERLIN, I would like to be able to use a dilution fridge for some very low temperature experiments.

#### Acceptance Criteria
1. TBD

#### Notes
1. TBD

**Comment by kjwoodsISIS** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 12 December 2017 16:10
> To: Walker, Helen (STFC,RAL,ISIS)
> Cc: Holt, John (Tessella,RAL,ISIS); Potter, Adrian (Tessella,RAL,ISIS); Adroja, Devashibhai (STFC,RAL,ISIS)
> Subject: RE: IBEX developments on Merlin
> 
> Hi Helen, 
> 
> Thanks for letting us know that you will be using a dilution fridge.
> 
> I have two immediate questions:
> 1. Do you know which model of dilution fridge you will be using?  My working assumption is 
> that it will be a Triton fridge.  Can you please confirm exactly which model you will be using.
> 2. When is the experiment scheduled?  Is there a definite date yet?
> 
> Thanks,
> 
> Kevin
> 
>> ________________________________________
>> From: Holt, John (Tessella,RAL,ISIS)
>> Sent: 12 December 2017 15:58
>> To: Woods, Kevin (Tessella,RAL,ISIS)
>> Subject: FW: IBEX developments on Merlin
>> Fyi… I will create a ticket.
>>  
>> Cheers,
>>  
>> John
>>  
>>> From: Walker, Helen (STFC,RAL,ISIS) 
>>> Sent: 12 December 2017 15:56
>>> To: Potter, Adrian (Tessella,RAL,ISIS) <adrian.potter@stfc.ac.uk>; 
>>> Holt, John (Tessella,RAL,ISIS) <john.holt@stfc.ac.uk>
>>> Cc: Adroja, Devashibhai (STFC,RAL,ISIS) <devashibhai.adroja@stfc.ac.uk>
>>> Subject: IBEX developments on Merlin
>>>  
>>> Hi, I’m sorry if this should go through the footprints system, but it didn’t seem to fit in with 
>>> any of the severity categories. It is a very important issue, and will become urgent, but that 
>>> urgency is on the basis of a couple of months time.
>>>  
>>> We have now accepted a proposal for an experiment on Merlin which will use a dilution fridge. 
>>> It is therefore essential that we should be able to implement this in IBEX. Do you have any 
>>> ideas about a timeframe for doing this?
>>>  
>>> Many thanks
>>> Helen
>>>

**Comment by kjwoodsISIS** [comment]
The Triton details can be found at :C:\LabVIEW Modules\Drivers\Triton
The manuals can be found at : C:\LabVIEW Modules\Drivers\Triton\Documentation
The manual of most interest is likely to be:
C:\LabVIEW Modules\Drivers\Triton\Documentation\Triton System Manuals\Triton User Manual Version 3.pdf

**Comment by GDH-ISIS** [comment]
Communication : TCP Port : 33576. Make sure the Oxford software is running first. The computer may not respond to a ping due to firewall settings.

**Comment by Kevin-Woods-Tessella** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS)
> Sent: 18 December 2017 08:39
> To: Walker, Helen (STFC,RAL,ISIS); Adroja, Devashibhai (STFC,RAL,ISIS)
> Cc: Holt, John (Tessella,RAL,ISIS); Potter, Adrian (Tessella,RAL,ISIS)
> Subject: RE: IBEX developments on Merlin
> 
> Hi Helen,
> 
> OK.  Thanks for the update.  Please let us know when you have scheduled the experiment.
> 
> The Orange Cryostat should be fine - it is controlled via a Eurotherm.  However, I know 
> that the Cryogenics teams are planning an upgrade to all the Orange Cryostats, which 
> might require some changes to the way they are controlled (we are still trying to 
> understand the implications of the changes).
> 
> Kevin
> 
> ----
> 
>> From: Walker, Helen (STFC,RAL,ISIS)
>> Sent: 15 December 2017 16:38
>> To: Woods, Kevin (Tessella,RAL,ISIS); Adroja, Devashibhai (STFC,RAL,ISIS)
>> Cc: Holt, John (Tessella,RAL,ISIS); Potter, Adrian (Tessella,RAL,ISIS)
>> Subject: RE: IBEX developments on Merlin
>> 
>> Hi Kevin,
>> 
>> None of those experiments will be using a dilution fridge. We have yet to schedule the 
>> dilution fridge experiment, but it will be some time between March and September, and 
>> will also involve an orange cryostat.
>> 
>> Many thanks
>> Helen
>>
>> -------
>> From: Woods, Kevin (Tessella,RAL,ISIS)
>> Sent: 15 December 2017 09:50
>> To: Walker, Helen (STFC,RAL,ISIS); Adroja, Devashibhai (STFC,RAL,ISIS)
>> Cc: Holt, John (Tessella,RAL,ISIS); Potter, Adrian (Tessella,RAL,ISIS)
>> Subject: RE: IBEX developments on Merlin
>> 
>>> Hi Helen, Hi Adroja,
>>>
>>> I had a quick look on the Scheduler this morning.  I can see that you have several 
>>> experiments scheduled for February & March that all use CCR62 – the MERLIN top 
>>> loading closed cycle refrigerator.   But I can’t see which of these experiments 
>>> will be using a dilution fridge.
>>>
>>> Can you let me know which experiment(s) will be using a dilution fridge?  And 
>>> which model of dilution fridge?
>>>
>>> Thanks,
>>>
>>> Kevin
>>>

**Comment by John-Holt-Tessella** [comment]
Impeded @Tom-Willemsen  waiting for labview driver stable

**Comment by Tom-Willemsen** [comment]
PRs to review:
https://github.com/ISISComputingGroup/EPICS-Triton/pull/1
https://github.com/ISISComputingGroup/EPICS-ioc/pull/226
https://github.com/ISISComputingGroup/ibex_gui/pull/636
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/53
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/48
https://github.com/ISISComputingGroup/EPICS/pull/114

**Comment by Tom-Willemsen** [comment]
Need to also add % heater range to the IOC (see also https://github.com/ISISComputingGroup/ControlsWork/issues/385)

**Comment by Tom-Willemsen** [comment]
I used a slightly different process to get heater % than the labview, using an additional command `READ:DEV:<HTR UID>:HTR:SIG:CURR`. I've assumed it returns in units of mA but that will need checking against the real hardware when we next get access to it.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen : does your slightly different method give the same answer as the LabVIEW method?

**Comment by GDH-ISIS** [comment]
The command READ:DEV:<HTR UID>:HTR:SIG:CURR returns INVALID as a command. This is in both open loop and closed loop modes. As a result, I do not believe this approach is possible. I have checked this with the hardware and shown Tom so that he is aware.
PS. The LabVIEW code does show the heater percentage at present.

**Comment by Tom-Willemsen** [comment]
Removed the offending command and replaced it with one that works (`READ:DEV:<id>:HTR:RES`)
