### ISSUE TITLE
GALIL: Do not run autosave if GALILADDR macro is not set.

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2831]
Currently, if a galil IOC is started without the GALILADDR macro, it autosaves an empty set of values. This has caused issues e.g. https://github.com/ISISComputingGroup/IBEX/issues/2180. 

If the GALILADDR macro is not set the galil should:
- Not autosave anything
- Display a high severity log message (which should be visible in the GUI's IOC log messages view).
- The IOC should not stop/crash, otherwise it will enter an autorestart loop.

**Comment by AdrianPotter** [comment]
To the best of my understanding, the following workflow should be broken prior to the change and be fixed after.
    - Set some Galil values and check they are captured in the auto save file
    - Start the Galil without GALILADDR
    - Stop the Galil
    - Set GALILADDR
    - Start the IOC. The autosave values should be used

**Comment by DominicOram** [comment]
Since https://github.com/ISISComputingGroup/IBEX/issues/2787 this issue has changed and the broken behaviour is:
- Start a galil pointing to MTRCTRL=02
- Set a value
- Start the galil with no MTRCTRL
- Stop the galil
- Start the galil with MTRCTRL=02, the value set in step 2 should be used
