### ISSUE TITLE
NICOS: Highlight current line

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2834]
Since https://github.com/ISISComputingGroup/IBEX/issues/2149 the current line of the script running in NICOS has been available to the GUI. As a user I would like this line to be highlighted in the current script rather than just told to me.

**Comment by John-Holt-Tessella** [comment]
Think about type of control script sits in a controls around it. See mock up @ThomasLohnert  to add. 
Look at using a pydev control??

**Comment by ThomasLohnert** [comment]
[Script server front end design document](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Script-Server-Front-End-Design-Document), mockups at the bottom of the page

**Comment by davidkeymer** [comment]
As part of this ticket,  the ability to display line numbers in both the script creation/edit window and the current script view would be beneficial.  Something like that in Notepad++.
![Notepad++ Line Numbering.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56cf04ae52796f0e00328970/125516c66e82c728ace21e0d46c69b8e269282adc4a2ff6fad53f5d407532a712c16aa2577c7af6aaf50740b0a0c0abe4b4a5a42afaf8b7ef5b43f71885f09efd06e5f74c13914fabad40da313f871d51bdaebe5c01982fa3737e68c854e3b1c0c1d8efe5d33a89c4fcc4abb.PNG)
