### ISSUE TITLE
Journal Parser: Deployment strategy

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2837]
As an IBEX developer I would like to know the deployment strategy for the Journal Parser executable so that I know how it will interact with the IBEX deployment pipeline.

New functionality has been recently added to the Journal Parser (#2723) to support display of the journal in IBEX. The deployment instructions on the PR for that ticket involve significant system updates that are not performed as part of the IBEX deployment.

We should establish where responsibility lies for deploying new versions of the journal viewer to instruments so that we have a clear understanding for how resilient IBEX needs to be when it encounters different versions of the executable. Alternatively, if responsibility lies with the IBEX project then we need to integrate the deployment into our standard process so the executable can be kept up-to-date.

## Acceptance criteria

- [ ] The deployment process for the Journal Parser executable is understood, and the knowledge shared.
- [ ] Information pertinent to IBEX is recorded in the developer manual

**Comment by kjwoodsISIS** [comment]
@AdrianPotter  - I am not sure I understand what you mean by the Journal Viewer executable.  Do you mean the Journal Viewer written by one of the scientists, or the new Journal Viewer feature of IBEX?

**Comment by AdrianPotter** [comment]
Sorry. As discussed, "Journal Viewer" should have said "Journal Parser". Corrected above. It is the program the ISISICP interacts with to produce data files consumed by journal viewers. In this case it has been updated to push information to the IBEX DB

**Comment by AdrianPotter** [comment]
The deployment instructions I alluded to are in:

https://github.com/ISISComputingGroup/JournalParser/pull/1

**Comment by AdrianPotter** [comment]
Interested parties requested on Slack. I would expect to invite at least:

## Definite
Me: Since I'm coordinating the ticket
@FreddieAkeroyd: Knowledge of the DAE program and how it is currently deployed and maintained
@Tom-Willemsen: Developer on the original ticket

## Probable
@John-Holt-Tessella: Tech lead
@Kevin-Woods-Tessella: PM

**Comment by FreddieAkeroyd** [comment]
The journal parser is used on both SECI and IBEX instruments, on SECI instruments it will just send out slack alerts, on IBEX instruments it can also write to the MySQL database. It is currently installed to c:\labviewmodules\dae and deployed from SourceSafe along with the ISISICP. It is called from end_of_run.cmd which is executed by the ISISICP when a run ends.

**Comment by FreddieAkeroyd** [comment]
Also it only builds on Visual Studio 2015 and above due to the slack library compiler requirements, and for installation on SECI instruments a static build is useful

**Comment by AdrianPotter** [comment]
Meeting set up for 5th Feb

**Comment by AdrianPotter** [comment]
Actions in tickets:

#2952 
#2953
