### ISSUE TITLE
IOC: Individual interlocks for Danfysiks

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2838]
As a Muone FE Instrument scientist I would like to see the individual interlocks statuses so that I can diagnose errors without having to pysically go to the device.

**Comment by John-Holt-Tessella** [comment]
> Priority of differentiating interlocks: this would be useful if a power supply fails, because we’d be able to see what the fault is from home and decide who to call in to fix it (plant services, electrical, etc). If everything else works we’d never need to use it :-) Maybe it’s about “helpful” on your scale.
>> ? Is it mission critical, really useful, helpful, would be good for completeness

>>>All these supplies can be queried for the status byte/word, in which individual bits indicate the different errors. You need to refer to the manuals to find out the meaning of each. You could then have a row of LEDs, one for each bit, labelled with the meanings. Or an alternative would be to have a text field and put the active message(s) there, or leave it blank if all is OK. I think the Labview VI for the Danfysik power supplies on MUSR/EMU (which I wrote some of) does this. The row/column of red LEDs with labels is probably best.

>>>For some status bits such as external interlock it may be useful to explain further where they come from, in our setup. For example the user interlock input no.3 for UQ10 may come from the PLC and might mean magnet water flow failure. These enhanced labels/messages could be set by PV macros rather than hard-coding them into the IOC.

>>>Does the OPI work by merely displaying the values of PVs, or is it also configurable (labels, etc)? Being able to get the status in a script by reading a PV might also be useful.

**Comment by AdrianPotter** [comment]
Values must be archived for future review

**Comment by AdrianPotter** [comment]
Todo: Link to other Danfysik tickets

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/1208

**Comment by Tom-Willemsen** [comment]
Pull requests:
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/53
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/64
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/246
- https://github.com/ISISComputingGroup/ibex_gui/pull/658
- https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/6
