### ISSUE TITLE
SANDALS/GEM: Support PVs for Mercury cryostat that are used in SECI config

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2840]
As a SANDALS instrument scientist, I would like the same controls to be available to me in IBEX that were available in SECI so that I can continue to use the same functionality as I did before.

There are a number of blocks in the SANDALS SECI component "GEM - Mercury.comp" that are not available from the IOC:

- Nitrogen: Nitrogen level
- Helium: Helium level
- Cryo_VLim: Voltage limit
- Cryo_Heat: Heat %
- Cryo_NV: Flow %
- Cryo_I: I
- Cryo_P: P
- Cryo_D: D 
- Cryo_res: Resistance

These should be added so that equivalent IBEX blocks can be created.

**Comment by AdrianPotter** [comment]
Needed for #2797

**Comment by AdrianPotter** [comment]
I will ask on Thursday when I go down to the instrument whether they want the OPI updating as well. If they do, I'll make it a separate ticket.

**Comment by AdrianPotter** [comment]
I asked Sabrina about the Mercury Cryostat when I went down to the instrument before Christmas. They've been using a lot of GEM equipment owing to doing some of their experiments while TS2 is down. It's anticipated that they won't need to do so again next cycle:

From Sabrina, 21/12/17:

>I’ve just spoken to Alex, it is highly unlikely that we will need the GEM Mercury cryostat next cycle, but > we are not 100 % sure. So, I leave it to you whether you want to transfer that configuration as well, or > park it for now.  It would be nice to have it (just in case), but it does not have a high priority from our > side.

**Comment by AdrianPotter** [comment]
Putting back into backlog awaiting need.

**Comment by Tom-Willemsen** [comment]
Required for GEM.
