### ISSUE TITLE
genie_python: `waitfor` methods fail for large input

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2846]
As a developer, I would like `waitfor` methods not to fail if I ask them to wait for an extremely long time.

Discovered as part of ticket #2727.

If I put 2**31 as an integer into a `waitfor` commands, it says it's invalid. This is likely to do with the underlying crossover in Python between plain integer and long integer.

I cannot think of any realistic situation where this would affect an instrument scientist. Feel free to correct me! However, we should engineer our systems to be resilient if at all possible.

**Comment by kjwoodsISIS** [comment]
The above description does not make sense to me:
Are you saying that the value 2147483648 (which is the decimal representation of 2**31) causes problems for Python?  Why should it cause a problem?  (someone would have noticed by now!)  It suggests to me that the problem may in fact be in the way we are using the relevant argument.
