### ISSUE TITLE
VESUVIO: Foil Changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2851]
As a user I would like to be able to control the new foil changer on VESUVIO.

The new changer will consist of two banks of 5 foils that can be moved into the beam, each foil position will be marked by a switch. It will be controlled using a Galil DMC-4040 and the logic will be done in a Galil program (not written by us). We will need to:
* Create an IOC that connects to the changer (much like the EMMA chopper lifter IOC)
* Create an appropriate OPI
* Arrange for private network to where the galil will be located (which is TBC)

The device is expected to be ready for commissioning/testing in April/May.

@jonelmer, can you please upload a picture for info?

**Comment by jonelmer** [comment]
The foil changer will consist of 2x identical stages (front + back), each comprising:
- Stepper motor
- Gearbox
- Lead screw
- Rotary encoder
- 2x Limit switches
- 5x foil position switches

![image](https://user-images.githubusercontent.com/23215573/34676465-d2634fea-f484-11e7-96c6-712a3285b4bd.png)

**Comment by jonelmer** [comment]
Update

@IainJohnson is currently assembling this in R6, with the aim of installing during the summer shutdown.

**Comment by DominicOram** [comment]
@jonelmer is the info above still correct? If so we probably should have a chat about what the gmc will look like.

**Comment by jonelmer** [comment]
It is still correct, and indeed we should.

I'll put a meeting together with @DominicOram and @IainJohnson to discuss this further

**Comment by kjwoodsISIS** [comment]
When you meet to discuss this work, can you please provide a proposed timetable for this work, so that I can understand how it might be scheduled with other work we are doing over the summer.

**Comment by DominicOram** [comment]
Just met with @jonelmer. Install is planned on 24th July, after which it will be buried so we should do as much work as possible before then. @IainJohnson is working on commissioning it and will be finished around 4th July. The following will be required:
- [ ] Write some gmc to move to the specified foil (this may be done by @IainJohnson or @jonelmer, TBD)
- [ ] Write a motorExtenisions db to interact with the changer
- [ ] Install private network to the rack for the galil
- [ ] Create a suitable OPI

**Comment by DominicOram** [comment]
Bit of a change of plan, this will now be done using motion set points with the switches as a back up. @IainJohnson will provide numbers and has some idea of homing routines. Install is now going to be around 6th August.

**Comment by DominicOram** [comment]
I have emailed to ask for private VLAN

**Comment by DominicOram** [comment]
Jon and I just put the network in between where the galil will sit and a port in the blockhouse

**Comment by John-Holt-Tessella** [comment]
Not for release as this is now just configuration of set points.

**Comment by DominicOram** [comment]
Last email from scientists was that they were are happy with the set up. To test:
* Confirm that the foil changer is in the synoptic
* Confirm the motion set points look sensible
