### ISSUE TITLE
GEM: set up sample stack

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2853]
The sample stack on GEM needs to be set up:

- Figure out how to (physically) route private network to galils and patch the connection through
- Ensure galil settings do not clash with the new galils that have been set up for the jaws
- Set up GALIL axes

**Comment by John-Holt-Tessella** [comment]
Patching might have done check with @DominicOram

**Comment by DominicOram** [comment]
Patching not quite complete, waiting on an additional network switch from Facilities IT. Even when it is complete the ongoing upgrade work means that it is physically very difficult to get the sample stack plugged in. Will update when GEM is in better position for this.

**Comment by DominicOram** [comment]
This will not be required this cycle.

**Comment by kjwoodsISIS** [comment]
Winfried has an experiment scheduled on GEM that requires the use of the "GEM: 5-axis Goniometer". The experiment starts on 7th May.

Curiously, the "5-axis" Goniometer has only 4 axes - x, y, z and omega.  It also appears that the "GEM: 5-axis Goniometer" and the "GEM Sample Stack" are one and the same.  The 5-axis Goniometer can be driven by a Galil. We may need to create an OPI.  Alternatively, there is a LabVIEW driver.

7th May is a bank holiday, so this needs to be implemented and tested ahead of time.

**Comment by Tom-Willemsen** [comment]
I've checked on GEM that there is a suitable item in their synoptic and it is connected sensibly.
