### ISSUE TITLE
GEM: sample changer: test on beamline

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2854]
GEM's sample changer is, in principle, the same one as used on POLARIS and HRPD. However there may be some subtle differences, so we need to verify that the IOC works correctly with GEM's hardware.

*Acceptance criteria*
The ROTSC IOC has been tested against GEM's sample changer and any necessary changes have been made.

**Comment by DominicOram** [comment]
I have checked the labview. The VI is exactly the same as that on POLARIS other than the title.  We should obviously still check it connects and talks but I don't anticipate any major changes will be required.

**Comment by DominicOram** [comment]
I did went down and confirmed that it worked a few weeks ago, GEM ran using it last cycle with no complaints.
