### ISSUE TITLE
Unit Tests: Add to Jenkins

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2857]
The following unit tests are not being run in Jenkins, they should be run so we are aware when items break:
* ArchiverAccess
* BlockServerToKafka
* inst_servers\server_common
* misc\upgrade

**Comment by AdrianPotter** [comment]
It seems to work ok, but the upgrade script tests fail. It doesn't look like a big fix so I think we should sort them out prior to merging rather than breaking the builds.

**Comment by DominicOram** [comment]
Yes, I'm fixing those as part of https://github.com/ISISComputingGroup/IBEX/issues/2844.

**Comment by AdrianPotter** [comment]
Can we impede this until those are fixed then please?

**Comment by esouthren** [comment]
One (non-vital?) issues - 

Running DatabaseServer unit tests returns:
``` MINOR: Cannot find config path: C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\test_files/config.xml```

**Comment by DominicOram** [comment]
Good catch, fixed the relative pathing issue. Some of the other tests do throw warnings like these, in general we're happy to ignore but in an ideal world we should be suppressing them...
