### ISSUE TITLE
GEM: Galil jaws: commission

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2858]
The jaws on GEM have been replaced with galil jaws. The motion control group has not yet finished commissioning the jaws on their side.

Once motion control have finished commissioning we will need to copy the various motor settings, homing modes etc across to IBEX.

Follow the steps in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX

**Comment by IainJohnson** [comment]
Here is a link to a spreadsheet with useful information: http://www.facilities.rl.ac.uk/isis/electricalusersupport/Files/02%20-%20Beamline%20Equipment/TS1/GEM/Slits_Sets_JJ_X_Ray/Commissioning_Reports_Gem/GEM_Slits_Computing_Factsheet.xlsx

**Comment by kjwoodsISIS** [comment]
@IainJohnson - we now have access to the Sharepoint site.

**Comment by IainJohnson** [comment]
@kjwoodsISIS here is the very latest place masquerading as a network drive: http://www.facilities.rl.ac.uk/isis/Motion/TestDocuments/Forms/AllItems.aspx

**Comment by kjwoodsISIS** [comment]
http://www.facilities.rl.ac.uk/isis/Motion/TestDocuments/Forms/AllItems.aspx should now also be available to all members of the Experiement Controls team.

**Comment by Tom-Willemsen** [comment]
As part of the commissioning, please confirm distances along beamline of new jaws and adjust the scale factors in `configurations/galil/jaws.cmd` to match the new distances. May need to ask motion control (?) if the new jaws have been surveyed if we're not sure of the distances.

I've got the following scale factors (between sample position and moderator) for the old jaws (extracted from labview driver):
Set 5 - 0.097
Set 4 - 0.2545
Set 3 - 0.396
Set 2 - 0.521
Set 1 - 0.627

**Comment by DominicOram** [comment]
Network is now all correctly set up for the Galils. We just need to:
[ ] Confirm that they are working correctly under SECI
[ ] Migrate them to IBEX

Scientists have confirmed that those distances are currently fine and will pass on some more up to date distances when they have some.

**Comment by Tom-Willemsen** [comment]
Installed values for the centres of the slit boxes are 

GEM1      6.322m
GEM2      8.128m
GEM3    10.329m
GEM4    12.643m
GEM5    15.389m (not final position)
SAMPLE Position (under vacuum) 17.000m

**Comment by DominicOram** [comment]
To test (on NDXGEM):
- [ ] Confirm that all the Galil motors in the jaws component start up correctly, have correct descriptions etc. and can be homed
- [ ] Confirm that when switching between IBEX/SECI the positions are retained
- [ ] Confirm that the Jaws OPI gives the correct values for the jaw positions based on the Galil positions

**Comment by AdrianPotter** [comment]
Note that I would say the IOC system tests should be fixed before this ticket is marked complete. I'd also like the IOC system tests to cover the East, South and North blades to verify their calculations are correct.

**Comment by John-Holt-Tessella** [comment]
Confirmed the Dom homed all jaws and that he checked the positions between SECI and IBEX.

**Comment by John-Holt-Tessella** [comment]
Calc: distance from sample to jaws and width(height) - width(height) at sample. Then take ration. All ratios agree to 2sf.

  | Distance to Jaws | Width horz | Width Vertical |   | Distance from jaws to sample | Width - width at sample | Height - Height at sample | ratio horz | ratio vert
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
MODERATOR | 0 | 90 | 84 |   | 17 | 80 | 44 | 4.705882 | 2.588235
GEM1 | 6.322 | 60.25 | 67.64 |   | 10.678 | 50.25 | 27.64 | 4.705937 | 2.5885
GEM2 | 8.128 | 51.75 | 62.96 |   | 8.872 | 41.75 | 22.96 | 4.705816 | 2.587917
GEM3 | 10.329 | 41.39 | 57.3 |   | 6.671 | 31.39 | 17.3 | 4.705441 | 2.593314
GEM4 | 12.643 | 30.5 | 51.24 |   | 4.357 | 20.5 | 11.24 | 4.705072 | 2.579757
GEM5 | 15.389 | 17.58 | 44.15 |   | 1.611 | 7.58 | 4.15 | 4.705152 | 2.57604
SAMPLE | 17 | 10 | 40 |   | 0 | 0 | 0 | #DIV/0! | #DIV/0!

**Comment by DominicOram** [comment]
Note that the numbers noted in Iain's spreadsheet for axes 1-8 assume home is the first index from the limit. IBEX has a 1mm difference as it homes on the 2nd index.
