### ISSUE TITLE
Install Release

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2864]
As an instrument scientist I want the latest version of IBEX installed so I have access to all the newest shiniest features.

Acceptance Criteria

Upgraded and installed on (first box is started, second is done):

- ALF
    - [x] Started
    - [x] Done
- ENGINX
    - [x] Started
    - [x] Done
- EMMA
    - [x] Started
    - [x] ~Done~ #2364 impeded awaiting Fermi chopper hardware fix
- ~GEM~ (Doesn't need to be done this time)
- HRPD
    - [X] Started
    - [X] Done
- IMAT
    - [X] Started
    - [X] Done
- IRIS
    - [x] Started
    - [x] Done
- LARMOR
    - [x] Started
    - [X] Done
- MERLIN
    - [x] Started
    - [x] Done
- MUONFE
    - [X] Started
    - [X] Done
- POLARIS
    - [x] Started
    - [x] Done
- RIKENFE
    - [x] Started
    - [x] Done
- SANDALS
    - [x] Started
    - [x] Done
- SELAB (Don't do until Matt gives clearence ask again on 8th Feb)
    - [x] Started
    - [x] Done
- VESUVIO
    - [x] Started
    - [x] Done
- ZOOM
    - [x] Started
    - [x] Done

"mini" hybrid instruments:

-~ HIFI_CRYOMAG~ Will wait for next upgrade
-~ SANS2D~ ~ Will wait for next upgrade
-LET
    - [x] Started
    - [x] Done
-~MUSR~ Will wait for next upgrade
-~MAPS~ - not required as prototype Fermi chopper unavailable. see #2856.  Full conversion to IBEX in due course.

**Comment by Tom-Willemsen** [comment]
When deploying on POLARIS ensure the steps under "reducing database disk space" at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting are done

**Comment by DominicOram** [comment]
Once all complete deploy the new web dashboard.

**Comment by John-Holt-Tessella** [comment]
Fix the error in the upgrade script:

```
Do step 'Backup database'? : Y
Backup database ...
Enter password: ************
Enter password: ************
Copying C:\Instrument\var\mysql to C:\data\old\ibex_backup_2018_02_02\mysql
Traceback (most recent call last):
  File "c:\Instrument\installation_and_upgrade\IBEX_upgrade.py", line 94, in <mo
dule>
    upgrade_instrument.run_instrument_deploy_main()
  File "c:\Instrument\installation_and_upgrade\ibex_install_utils\install_tasks.
py", line 628, in run_instrument_deploy_main
    self._upgrade_tasks.backup_database()
  File "c:\Instrument\installation_and_upgrade\ibex_install_utils\install_tasks.
py", line 420, in backup_database
    self._backup_dir(os.path.join("C:\\", "Instrument", "var", "mysql"))
  File "c:\Instrument\installation_and_upgrade\ibex_install_utils\install_tasks.
py", line 342, in _backup_dir
    shutil.copytree(src, backup_dir)
  File "Y:\Kits$\CompGroup\ICP\genie_python\BUILD-182\Python\lib\shutil.py", lin
e 222, in copytree
    raise Error, errors
shutil.Error: [('C:\\Instrument\\var\\mysql\\data\\NDEMUONFE.pid', 'C:\\data\\ol
d\\ibex_backup_2018_02_02\\mysql\\data\\NDEMUONFE.pid', "[Errno 2] No such file
or directory: 'C:\\\\Instrument\\\\var\\\\mysql\\\\data\\\\NDEMUONFE.pid'")]
```

**Comment by John-Holt-Tessella** [comment]
Check this still works:

https://github.com/ISISComputingGroup/ibex_utils/pull/11

Instrument deploy on Demo would be good because it is not running the latest (it is running a release candidate).

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella , @AdrianPotter , @Tom-Willemsen - what needs to be done to review this ticket?

**Comment by AdrianPotter** [comment]
@Kevin-Woods-Tessella I'd say given that we're several weeks into cycle now, there's very little to be done to review this and it should be moved straight to Review complete

**Comment by Kevin-Woods-Tessella** [comment]
Release was deployed in time for Cycle 2017/04 (started 6th Feb).  Instruments running well.
Nothing further to review.

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella it says in the ticket:

    Check this still works:
    
    ISISComputingGroup/ibex_utils#11
    
    Instrument deploy on Demo would be good because it is not running the latest (it is running a release candidate).

it needs to be reviewed.
