### ISSUE TITLE
GUI: Simulation mode: Make DAE simulation mode more obvious

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2869]
As an instrument scientist, I would like the GUI to tell me whether it is in simulation mode more obviously than it currently does.

The state of the DAE simulation mode is reflected in the GUI as of https://github.com/ISISComputingGroup/IBEX/issues/2657 but there were some concerns at sprint review that this may not be obvious enough, therefore, this ticket is to make simulation mode more obvious. One suggestion would be to put it in large letters in the dashboard, maybe something like the following mockup:

![image](https://user-images.githubusercontent.com/24375813/35096675-f9f486ba-fc44-11e7-9de5-dd2814958145.png)
(If this is used, need to make sure the red text is still visible in all possible run states)

**Comment by kjwoodsISIS** [comment]
In addition to making sure the text SIMULATION MODE is visible in all states, we need to ensure it is also visible to colour blind people in all states - what looks high contrast to you, might not be high-contrast to a colour blind person.  See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Designing-for-Colour-Blindness for more advice.
