### ISSUE TITLE
SANDALS: Motion setpoint tests

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2870]
As part of #2707:
Create motion setpoints tests to test:

1. 1D with axis
1. 1D with motor
1. 2D with axis
1. 2D with motor
1. Dynamic setpoints

**Comment by John-Holt-Tessella** [comment]
Pull requests:

- https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/7
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/52

**Comment by AdrianPotter** [comment]
The tests are passing. The logs still give warnings of the follwoing form though:

```
devMotorAsyn::init_record TE:NDW1836:LKUP:2DAXIS::MTR bad link Link must be INST_IO or VME_IO
2018/01/31 11:21:29.154 devMotorAsyn::build_trans: TE:NDW1836:LKUP:2DAXIS::MTR error calling queueRequest, asynManager::queueRequest asynUser not associated with a port
2018/01/31 11:21:29.155 devMotorAsyn::build_trans: TE:NDW1836:LKUP:2DAXIS::MTR error calling queueRequest, asynManager::queueRequest asynUser not associated with a port
```


- Please investigate so we know whether this is something we need to worry about
- Fix if needed
- If you're in the code, please could you remove the double colon from the setpoint setup (e.g. `TE:NDW1836:LKUP:2DAXIS::MTR`). It doesn't seem to affect the test.
