### ISSUE TITLE
E4: Preference Menu

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2871]
CTRL + ALT + P preference menu currently does not work in Eclipse 4 as the `preferencePages` extension point is not available anymore. Investigate if there is a way to get it back or whether there are feasible alternatives like creating our own dialog. Follow up with an implementation ticket.

There is a [plugin](https://github.com/opcoach/e4Preferences) someone developed which provides a preference page extension point for E4 applications, but I don't know if this is something we would want to use.

I guess the first question we should ask is what functionality we actually need from the preference pages. I am aware that we use it to show/hide perspectives - I'm sure we can find another way to do this. What other settings are in there that we readily need to be able to modify?

**Comment by John-Holt-Tessella** [comment]
Look for ini file and document how to edit it.

**Comment by Tom-Willemsen** [comment]
This was fixed by setting up the preference store in https://github.com/ISISComputingGroup/ibex_gui/pull/671 . CTRL-ALT-P works similarly to E3. Closing this.
