### ISSUE TITLE
E4: Re-implement label showing active configuration

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2873]
The label showing the active configuration (previously found at the bottom of the E3 application) is gone. Re-implement it somewhere in the GUI. We could just add it to the spangle banner (now found at the bottom of the E4 window)

**Comment by John-Holt-Tessella** [comment]
Add to banner which is at the bottom

**Comment by Rhundas** [comment]
Commited to master_e4 by mistake (thanks John).
Commits are: 
https://github.com/ISISComputingGroup/ibex_gui/commit/e88ce2b5ffd411ef7197f08ed94df273dd022c60
https://github.com/ISISComputingGroup/ibex_gui/commit/50518102af9f6602af534122d6e1a8ecc0002aaa
https://github.com/ISISComputingGroup/ibex_gui/commit/fd897fafa60b8200a0be620cb879f738b9107605

**Comment by DominicOram** [comment]
I see that you refactored the way that the DAE Simulation Indicator worked. After discussion with @Tom-Willemsen  (Who wrote that indicator) I think there is a lot of duplicated code that we could remove. We can look at it together, just grab me when you're ready.
