### ISSUE TITLE
E4: Scripting perspective

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2876]
There are currently a few issues with the scripting perspective, taken from the E4 TODO list:

- The scripting perspective does not switch instruments once created

- If you open the scripting perspective too soon after launching the GUI, the console does not get instantiated properly

- The way the scripting perspective is created is confusing and messy. We should try and fix it 

- Switching to the scripting perspective is very slow, and the "Creating console" popup dialog is gone. If we are not able to make the switching significantly faster we should at least add a dialog back in to provide feedback for the user.

**Comment by John-Holt-Tessella** [comment]
It would be worth looking at DAWN to see how they have done this.
