### ISSUE TITLE
E4: Beam status view layout

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2879]
From E4 TODO list:

>  `BeamStatusView.java`: We may want to change that entire part eventually to just be two databrowsers in different tabs rather than embedding the graph in a separate view.

Decide on a solution and implement if needed.

**Comment by Tom-Willemsen** [comment]
I'm not aware of any calls to change the beam status view particularly, it has been in E4 and working acceptably for some time now.

Can re-open if we get a more concrete user requirement.
