### ISSUE TITLE
E4: Finish migrating script generator perspective

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2880]
Taken from E4 TODO list:

> The script generator perspective has only been partially migrated. 
>     - The different parts are not linked by an underlying model so the functionality will not work. 
>     - The layout has not been updated to scale correctly. 
>     - There are several buttons from the original view which no longer appear in the perspective.

**Comment by kjwoodsISIS** [comment]
This ticket refers to the old Script Generator, which has been superseded.
See #3702 and #3704 and subsequent tickets.
