### ISSUE TITLE
E4: Fix log plotter within OPIs

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2881]
Taken from E4 TODO list:

> Log plotter within OPIs do not work. They need the changes to CSStudio from this pull request (https://github.com/ISISComputingGroup/CSStudio_3_3/pull/2/files). Currently the e4 gui just points at download.csstudio.org so doesn't have this change.

Had a brief discussion with @John-Holt-Tessella and @DominicOram about this. The conclusion was we should set up a P2 site to host our own version of CSS 4.x as we do with CSS 3.x in case they change it. We should at the same time be mindful that our version remain as close as possible to vanilla CSS

**Comment by AdrianPotter** [comment]
This feature has been added to the target platform via the PR:

https://github.com/ISISComputingGroup/ibex_gui/pull/679

They need some visual adjustment where they exist. I think that's just the stress rig and is covered by:

https://github.com/ISISComputingGroup/IBEX/issues/3136
