### ISSUE TITLE
E4: Get genie_python talking to PVs

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2882]
From E4 TODO list:
> Currently genie_python is getting `null` as it's `CA_ADDR_LIST` which causes issues.

**Comment by Tom-Willemsen** [comment]
Check if https://github.com/ISISComputingGroup/ibex_gui/pull/671 fixes this instead. It makes the preference store work as opposed to hard-coding values.

**Comment by AdrianPotter** [comment]
I forgot I had assigned myself to this, but am doing now...
