### ISSUE TITLE
E4: Select default synoptic in edit config dialog

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2883]
When editing a configuration, the default synoptic drop down remains blank. The selection should default to the default synoptic of that configuration.

Check if changes from https://github.com/ISISComputingGroup/ibex_gui/pull/623 affect the behaviour.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/748
