### ISSUE TITLE
MERLIN: Dilution Stick & Orange Cryostat from LET

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2886]
As a MERLIN scientist, I want to use the dilution stick & Orange Cryostat from LET, so that I can perform cryogenics experiments on MERLIN.  

#### Acceptance Criteria
1. I can control the temperature of the Orange Cryostat via IBEX.
1. I can control the temperature of the dilution stick via IBEX.
1. Support for these devices needs to be tested, installed & ready before 26th April 2018.

#### Notes
1. MERLIN is borrowing the Orange Cryostat & Dilution Stick from LET
   1.  The Orange Cryostat is: OC100-07 - an ILL MAXI Cryostat with an aluminium tail. 
   1.  The Dilution Stick (refrigerator) is: NDRI1, Neutron dilution Insert
1. Control of the Orange Cryostat is via a Eurotherm.
1. Control of the Dilution Stick is via a Triton system.  See #2828.
1. Experiment requiring these devices is scheduled for 27th-28th April 2018.  The 26th April has been set aside as a day for installation & setup of the equipment.

**Comment by kjwoodsISIS** [comment]
> Hi Helen,
> 
> Yes, this should be possible, in principle.
> 
> In practice, we’ll need to understand where the cryostat (OC100-07) and dilution fridge (NDRI1) (and any gas handling equipment) are going to be during the preceding shutdown (25 Mar 2018 - 17 Apr 2018).  Will they be on LET?
> 
> Kevin
> 
> 
> From: Walker, Helen (STFC,RAL,ISIS) 
> Sent: 19 January 2018 15:03
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Keymer, David (STFC,RAL,ISIS); Akeroyd, Freddie (STFC,RAL,ISIS); Willemsen, Thomas (Tessella,RAL,ISIS); Howells, Gareth (STFC,RAL,ISIS)
> Subject: RE: dilution stick in LET orange cryostat on Merlin
> 
> Thanks Kevin,
> 
> Is there any chance of aiming to have it ready to try some testing prior to the cycle starting in mid April?
> 
> Thanks
> Helen

**Comment by kjwoodsISIS** [comment]
Contact Cryogenics to get time to test.

**Comment by kjwoodsISIS** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 15 February 2018 16:02
> To: Walker, Helen (STFC,RAL,ISIS)
> Cc: Down, Richard (STFC,RAL,ISIS)
> Subject: RE: dilution stick in LET orange cryostat on Merlin
> 
> Hi Helen,
> 
> I’ve been in touch with Richard Down to let him know we need to do a communications-only test 
> of the dilution stick & Orange Cryostat prior to Cycle 2018/01a.  Richard says it is straightforward to 
> move the equipment from LET to MERLIN for this type of test but, obviously, we’ll need to agree a 
> date on which it can happen.   Are there some available days on LET & MERLIN during the period 
> 26/03 – 16/04 (remembering that it is Easter from 30/03-02/04)?
> 
> Thanks,
> 
> Kevin

**Comment by kjwoodsISIS** [comment]
Suggested testing time is one day during the period 3rd-13th April.  I have asked David Voneshen, the LET instrument scientist who will be involved in the experiment (1810266) on 26th/27th April, to confirm a convenient date.

**Comment by Tom-Willemsen** [comment]
We need to ask cryogenics whether this will use a fridge with old or new software (ref https://github.com/ISISComputingGroup/IBEX/issues/3030)

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - OK, will do.

**Comment by kjwoodsISIS** [comment]
> From: Down, Richard (STFC,RAL,ISIS) 
> Sent: 22 March 2018 07:44
> To: Woods, Kevin (Tessella,RAL,ISIS) 
> Cc: Keeping, Jeff (STFC,RAL,ISIS) 
> Subject: RE: dilution stick in LET orange cryostat on Merlin
> 
> Hi Kevin,
> 
> Currently NDRi1 is scheduled which is the new software.
> 
> We have a new version from Oxford Instruments that we are trialling on Musr over the 
> next week which may replace the new software.
> 
> Best, Richard.

**Comment by kjwoodsISIS** [comment]
Testing on MERLIN is scheduled for 9th April (confirmed with Richard Down).

**Comment by Tom-Willemsen** [comment]
Moving to 10th April as cryogenics are busy on the 9th.

**Comment by Tom-Willemsen** [comment]
Tested with David Voneshen and Chris Lawson. A couple of very minor fixes were needed which I will lump into ticket 3030. 

There is an open question about whether they are also going to use an additional (external) Lakeshore 340 for this experiment, or whether they are going to use one of the channels on the Triton systems' internal lakeshore unit. David Voneshen and Chris Lawson are going to discuss this and get back to us.

**Comment by kjwoodsISIS** [comment]
The use of an "additional (external) Lakeshore 340" sounds like a somewhat different use-case.  Are they thinking of this somehow being integrated with the existing Triton solution?  Or simply using the existing Lakeshore 340 IOC & OPI?  I think we need more detail and clarity from David & Chris in good time for the experiment on 26/27 April.
