### ISSUE TITLE
Log Plotter: Display units on graphs

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2889]
As an IBEX user, I would like the units of PVs to be displayed on the log plotter graphs

**Comment by KathrynBaker** [comment]
This was requested during a demo to Muon scientists

**Comment by Tom-Willemsen** [comment]
How should this handle dynamic units? One solution is to get the current unit via channel access, but this may not necessarily be the unit of the data being displayed. The units are not (in the general case) being archived with the data.

**Comment by DominicOram** [comment]
Note that this is native to the latest databrowser in E4. I will merge this change anyway for E3 but will remove it in the E4 master
