### ISSUE TITLE
DEVELOPMENT: Update compiler to 2017

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2890]
As a developer I want to use the same compiler on my desktop as we are using in the build. This must be 2017 because this is the only compiler which works on windows 10.

Tasks:

1. Ticket for testing Galil must be done
1. MK3 Chopper must be migrated (as part of this ticket)
1. Any other 2010 specific stuff must be converted
1. Reinstate journal parser system tests

**Comment by Tom-Willemsen** [comment]
The default visual studio if you install from microsoft is now 2019. Should we be aiming to switch to VS2019 instead of VS2017?

**Comment by DominicOram** [comment]
Closing in favour of https://github.com/ISISComputingGroup/IBEX/issues/6753
