### ISSUE TITLE
GUI: Review DAE perspective

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2894]
The DAE perspective is cluttered and messy. Review the layout and create mockups with improvements to the design.

Some ideas/issues to address which came out of a meeting with @mattclarke and @DominicOram :
1. Declutter
    1.  Run summary repeats information found in dashboard
    1. What value does the DAE log add compared to the general IOC log?
    1. In `Experiment Setup > Time Channels`, There are arbitrarily 6 time regimes which arbitrarily contain 6 rows each. Rarely are more than a couple of those used. (Could be added on the fly instead?)
    1. There are arbitrarily 4 plots to show spectra. Is there a better way? e.g. just 1 plot that you can add multiple traces to
1. Should start/stop/...  run buttons persist outside tabs?
1. Is there a better way to arrange the experiment setup? (without tabs in tabs)
1. Move vetos into run information page?
1. Summary page: "Show Title in Dataweb Dashboard" checkbox might not mean anything to users

**Comment by ThomasLohnert** [comment]
> Should start/stop/... run buttons persist outside tabs?

As an example to support this idea, during IBEX training, one of the attendees could not find the "Start" button when instructed to switch to the DAE perspective and start the run, because a tab other than the run summary tab was open on the DAE perspective.

**Comment by KathrynBaker** [comment]
DAE perspective hasn't changed yet, but given the age of this ticket, closing it anyway
