### ISSUE TITLE
Motor extensions use out of date macros

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2895]
As a developer, I want the example settings files in motorExtensions to work with the current version of IBEX so that I don't have to reconfigure them when I want to use them.

Some of the example settings in motorExtensions use the out of date `$(IFDMC0n)` macros for Galil settings. These are no longer used so these example settings won't work as expected. Please could the macros be updated so that they work out of the box.

**Comment by DominicOram** [comment]
Also do motionsetpoints at the same time

**Comment by DominicOram** [comment]
Done in https://github.com/ISISComputingGroup/EPICS-motionSetPoints/search?q=DMC
