### ISSUE TITLE
LARMOR Jaws: Target Position increments by itself

### ISSUE THREAD

**Issue by IainJohnson** [ISISComputingGroup/IBEX#2898]
Observation: After a move, Target Position increments itself, possibly by the magnitude of the following error. The axis then slowly creeps in one direction.

I saw this on Larmor Aperture 1 (Slits 2 (?!)), piezo servo motor with encoder.

**Comment by IainJohnson** [comment]
https://drive.google.com/open?id=13EO2Vx266BMxmRChUK0TSnLpwYh9ngbW

52MB video of the behaviour

**Comment by Kevin-Woods-Tessella** [comment]
@IainJohnson - thanks for reporting this.  Does the "auto-increment" affect only this one slit or, more specifically, the S2 South motor?
Is there anything different about this motor, compared to other motors on LARMOR?

**Comment by IainJohnson** [comment]
@Kevin-Woods-Tessella Hi Kevin, it seems to do it on any axis of these slits. I've ruled out retries, it does this even if the retry count is zero, or if I disable by setting to zero. I've also tried zeroing the unused motor counter in the Galil. These motors have sprung feet that tend to 'relax' a few seconds after moving. It appears if the encoder increments after the Moving Flag is extinguished, this gets added to the Target Position. Note that these piezo motors are true closed-loop at the low level, so error/counter correction appropriate for an openloop stepper, might not work in this case, I wonder if that's what's happening?

**Comment by kjwoodsISIS** [comment]
@IainJohnson - thanks for the extra information.  We'll need to investigate what is going on.  What you say about piezo motors vs openloop stepper motors could well be true.

**Comment by FreddieAkeroyd** [comment]
Went down to LARMOR today to have a look with Iain, it seems the epics target position can be updated from the Galil as we moved independent of EPICS and the target in EPICS updated to reflect this. Need to confirm if this is what TD would report as that is used internally for "motor position" whereas TP is used for "encoder position"

**Comment by Tom-Willemsen** [comment]
Impeded as it's not currently clear whether EPICS is causing the drift or whether something in the galil is causing the drift. 

@IainJohnson - have you had any more thoughts on this issue?

**Comment by IainJohnson** [comment]
@Tom-Willemsen hi Tom, I don't have access to Larmor right now to try anyhting else. As Freddie noted above, it does this behaviour if you command a move from the low level. It would be good to know if the Galil RPn value is being written by the Galil itself, or the motor record.

**Comment by FreddieAkeroyd** [comment]
The jaws have been retuned which may have helped, Iain suggested a good test would be to turn the IOC off and send some terminal PR or PA moves and see if the behaviour remains (assuming it is still there)

**Comment by FreddieAkeroyd** [comment]
Rob Dalgliesh thinks the retune fixed it - thank you @IainJohnson and I will close this ticket
