### ISSUE TITLE
DEPLOY: Add status after updating calibration directory

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2899]
As a developer I want to be warned by the upgrade step if an instrument scientist has updated their calibration directory because I need to challenge it.

**Comment by KathrynBaker** [comment]
It is also worth remembering in this situation, that if it is just a file added, then there is a chance this was a failed pull previously, or is was a new sensor back-doored onto the system, at which point there is no need to challenge, just move it to using the repo one.

If there is a difference in a file, then we need to spend longer looking into the difference and then hunting out why it is different.

**Comment by KathrynBaker** [comment]
#8315 is a better version of this. Closing
