### ISSUE TITLE
Journal Viewer: Display connection status

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2901]
As a user, I would like the journal viewer to display whether it can successfully connect to the underlying journal database so that I know whether my system is correctly configured to display journal information

This ticket is dependent on #2900.

This ticket should facilitate creating a basic MVVM stack between the top level view and the underlying database. 

## Acceptance criteria
- [ ] The architecture of the new perspective conforms to the IBEX MVVM standard
- [ ] The connection corresponds to the current instrument, not the local instrument.
- [ ] The functionality is available in both E3 and E4
- [ ] The journal viewer displays a clearly visible warning when no database connection can be established
- [ ] The journal viewer does not need to give a visible signal if the database connection is successful.

**Comment by ThomasLohnert** [comment]
- [ ] E3: https://github.com/ISISComputingGroup/ibex_gui/pull/640
- [ ] E4: https://github.com/ISISComputingGroup/ibex_gui/pull/641
