### ISSUE TITLE
IOC: Motionset point report in position even if not

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2906]
If the motors supporting a motion set points stop then it is assumed that they are at the correct position. Originally I can see that the code had a tolerance but this was removed; author does not remember why. 
We should reinstate the tolerance because it could lead to reporting the sample is in position incorrectly. If anyone can remember anything about its removal please let me know.

**Comment by John-Holt-Tessella** [comment]
Make sure all instruments have good tolerances on them.

**Comment by FreddieAkeroyd** [comment]
I'm not sure if this is related but the currentPosn() function looks to assume that you will never have a name position of 0.0? Anyway, taking a look at the whole codebase

**Comment by Tom-Willemsen** [comment]
Fixed by https://github.com/ISISComputingGroup/IBEX/issues/2983
