### ISSUE TITLE
Support groups: Lock certain variables from users and instrument scientists

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2907]
As a member of a support team, I would like to restrict setting certain values on IOCs to authorized maintainers.

Relevant support groups:
- Cryogenics
- Pressure and furnace - e.g. want to restrict setting maximum heater power
- Motion control - e.g. want to restrict setting motor speed

This ticket is to have a meeting with the relevant support groups to capture the requirements properly. 

We may also need to discuss the "politics" of this change - that is, instrument scientists might not necessarily be happy that we are taking power away from them.

Notes:
In this case the need was raised by cryogenics at an IBEX training session. Very similar requests have come from motion control in the past.

**Comment by KathrynBaker** [comment]
There may be some useful information relating to expectations of these kinds of interactions in this document: http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Control%20of%20a%20Beamline%20from%20a%20Mobile%20Device.docx

**Comment by kjwoodsISIS** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 16 February 2018 12:17
> To: Down, Richard (STFC,RAL,ISIS); Church, Andy (STFC,RAL,ISIS); 
>     Goodway, Chris (STFC,RAL,ISIS); Brind, Mike (STFC,RAL,ISIS)
> Cc: Akeroyd, Freddie (STFC,RAL,ISIS) <freddie.akeroyd@stfc.ac.uk>
> Subject: IBEX Instrument Control: Lock selected control variables from users & instrument scientists
> 
> Hello All,
> 
> During the most recent IBEX training sessions, which we ran in January, and which some of you attended, it was suggested that it would be sensible to lock certain key control variables, to prevent them being changed by individuals who lack appropriate training and/or experience (for example, prevent users from changing the maximum heater power).  This is something that can certainly be done in IBEX.  Indeed, some of the instrument scientists have asked us to use this feature to prevent visiting scientists from inadvertently changing the setup of certain devices (e.g. settings of jaws, settings & use of Fermi choppers).
> 
> It is not easy for a software developer to know which control variables should not be exposed to general use – we really need your guidance on which devices need protection.  I am not suggesting that we exhaustively list how each different type of device at ISIS should be handled but rather, to identify the key devices and who we should approach for detailed advice.  We also need to understand which devices scientists are used to having full (or extensive) control over, so that we don’t surprise them by removing a capability that they previously had.
> 
> Would you have some time in the next few weeks to meet & discuss?  If you can let me know your availability (or I can check your calendars), I’ll arrange a meeting.
> 
> Thanks,
> 
> Kevin

**Comment by DominicOram** [comment]
We had the meeting with the motion control group. It was decided that the for each motor the VEL, OFF and soft limits will be accessible via the top level motor panel. All other parameters will stay on the more details panel but access to this will be behind a password with a message asking scientists to contact motion control. Before this is done action is on the motion control group to further discuss with scientists.

**Comment by kjwoodsISIS** [comment]
As Dom noted, we have discussed this with the Motion Control team.  We can now proceed to implement a solution for motion control PVs. 
The other SE groups have yet to reply.  Rather than delay things, we should consider this ticket closed.  We'll keep chasing the other SE groups and will implement similar solutions when they have had a chance to come back to us.

**Comment by Tom-Willemsen** [comment]
Implementation ticket is #3014 

Marking this one as complete.
