### ISSUE TITLE
GUI: Display prompt in blocks panel when no blocks in config

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2911]
As a user, I would like to see a prompt with instructions on how to add blocks in the place of the blocks panel when none are present in the current configuration, rather than just blank space. 
This can be just some text similar to what you see in the blank Log Plotter perspective.

**Comment by DominicOram** [comment]
Has this been fixed by #3420?

**Comment by ThomasLohnert** [comment]
Not really, it just says "no groups present". Could use some simple instructions like "add blocks by editing the current configuration"
