### ISSUE TITLE
Slow IOC Log filtering

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2918]
As a user, I would like the IOC log to show results after applying a filter within a reasonable amount of time.

While performing manual system tests on DEMO, the IOC log perspective would often take a very long time (~5 min) to show the results after applying a log message filter. We should try to improve the performance of this operation.

**Comment by KathrynBaker** [comment]
These are now fairly quick. and the content is kept minimal, closing
