### ISSUE TITLE
GUI: "Restart" button in IOC dialog should restart any IOC

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2923]
As a user, I would like the "Restart" button in the start/stop IOC dialog to do what it claims. Currently it only restarts IOCs with auto-restart enabled while it just stops the IOC otherwise. Since this is an explicit instruction to restart the IOC and we already have a "Stop IOC" button, the behaviour should be consistent regardless of the IOCs auto-restart setting.

Steps to reproduce:
1. Start an IOC with autorestart disabled.
1. Start the IOC. 
1. In the IOC start/stop dialog, select the running IOC and press the "Restart" button. The IOC just stops.

**Comment by Tom-Willemsen** [comment]
Now does restart ioc

(it also sets autorestart on the ioc, which is kind of questionable - but the bug described in this ticket is "fixed")
