### ISSUE TITLE
Review defaults for galil ceramic parameters

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2926]
The CP parameters is not valid for steppers, we should also check the others for sensible defaults in both the conversion script and EPICS

https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/GALIL/GALIL-IOC-01App/Db/galil_userdef_records8.substitutions

**Comment by DominicOram** [comment]
Added notes from the meeting at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil-default-parameters. Also added https://github.com/ISISComputingGroup/IBEX/issues/3027. Does anyone think I forgot anything?

**Comment by KathrynBaker** [comment]
Looks right to me

Regards,
Kathryn
