### ISSUE TITLE
Add IOC for exporting SECI values to IBEX

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2928]
As a muon instrument scientist I would like my SECI blocks available is PVs as this will allow me to perform monitoring operations on them more easily. Initially needed for HIFI for detector temperatures.

lvDCOM already as a lvDCOMSECIConfig option to perform this, which has been tested on CRISP. This ticket is to create a formal IOC as the CRISP test was run by modifying the lvdcom example app in place. 

commands needed are on http://epics.isis.stfc.ac.uk/doxygen/lvDCOM/ in the "seci (isis only)" section

**Comment by FreddieAkeroyd** [comment]
Running on HIFI as part of HIFI magnet IOC, but needs own ioc really

**Comment by KathrynBaker** [comment]
SECI_2_IBEX was widely used in the end, and as most instruments are nearly migrated this work is not likely to be completed.
