### ISSUE TITLE
ZOOM: GUI for motion safety system [Timebox 2d]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2937]
As part of the motion safety system on ZOOM, there needs to be an easy way to set locations to drive to alongside permitting movements using the "hold to move" system.

**Acceptance Criteria**
1. There is a suitable GUI that can be run on a tablet/mobile/embedded system, which is attached/integrated into the "hold to move" system.

**Notes**
1. The requirements for this are still to be confirmed, and as such this could become an umbrella ticket for the various stages, the requirements, the solution and the testing.
1. It is likely that the requirements will be driven by the various options we can offer.

requires #2934
requires #3269

**Comment by DominicOram** [comment]
Closed in favour of #4238
