### ISSUE TITLE
Instrument deploy script does not work for new instruments

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2939]
Whilst doing the instrument deploy on Sandals, I encountered the following errors running the deployment script:

- The script will not start unless Git is installed. The script should prompt the user to install it if it isn't installed already. That should be quite easy to check.
- The release in the deploy batch script was set to 4.0.0 when I first ran it. It's an easy change but we should either detect the latest release or update the deploy scripts as part of release creation.
- The install java step fails
- A number of "install" steps are not performed by the deploy script on new instruments. For example (but not limited to):
    - config_mysql.bat
    - Installing MySQL
- The script exits immediately if upgrade.bat returns a non-zero error code
- The automatic launch of IBEX from the script does not work properly, the views all fail to initialise

Please go through on a clean VM and make sure that the deploy script, or a variant of it, can be used to get a new system into a working state.

**Comment by ThomasLohnert** [comment]
> The script exits immediately if upgrade.bat returns a non-zero error code

What is the desired behaviour? Is this just about keeping the window open to see the log, or should any other actions be performed?

**Comment by John-Holt-Tessella** [comment]
Having hit these problems I think it would be nice if the python script could catch the error and then offer to rerun the task. This would have been useful a couple of times.
