### ISSUE TITLE
EMMA: Commission fermi chopper

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2940]
As an EMMA instrument scientist, I want to check that the new IBEX fermi chopper support works correctly with the hardware so I can avoid any nasty surprises during cycle.

EMMA has been migrated to IBEX but we haven't yet had a chance to test the fermi chopper because it is broken (see #2364). Once it's fixed, we need to go down and check the chopper is working as expected.

**Comment by davidkeymer** [comment]
Fermi chopper tested, commissioned and in use.
