### ISSUE TITLE
Check for db changes that might have an impact on other functions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2942]
As an IBEX developer I would like some forewarning of when a db change might have an impact on existing behaviours, e.g. changes to ZNAM/ONAM string in bi/bo records, or ZRST/ONST/TWST etc in mbbi/mbbo records, or deleted PVs.

**Acceptance Criteria**
1. There is a script to aid in noticing these types of changes so that they can be documented and included in release notes/processes.

**Notes**
1. This does not need to be a release note for all db changes, only those which have an impact.
1. It may be nice to also check the configs, synoptics and scripts for these items as well.
1. This is in response to a bug that was raised on the muon instruments, quite legitimately as part of Ticket #2458 the ZNAM and ONAM of the POWER records were altered to our agreed upon standard of upper case text. This was integrated into release 4.0.0, although the issue was not highlighted in a way for computing to understand/be aware of it until just after release 4.2.0. This involved a change to one out of two similar IOCs and lead to a situation that some items still worked and others didn't, as it related to whether a power supply was "On" or "Off", and checks relating to that status via a block rather than directly to the underlying PV. It is important to realise, that the ticket related to the creation of an emulator and test framework additions for an existing IOC, and was therefore not listed against any changes that would be needed, whether in scripting or in other mechanisms that were reading and acting on it (in this case LabVIEW).

**Comment by davidkeymer** [comment]
Add some docs on wiki (it should be in the creating release procedure at least) also see comment in code.
