### ISSUE TITLE
WISH: Comission sample environment jaws

### ISSUE THREAD

**Issue by jelmer04** [ISISComputingGroup/IBEX#2946]
The sample environment jaws on WISH need commissioning. These jaws are Galil controlled, and use SmarAct piezo stages. A dedicated control box contains the Galil and drives, so commissioning can take place offline in R78. 

The equipment _should_ be available from March. *Kyle Birtwell* is the IDD motion contact for this job.

**Comment by kjwoodsISIS** [comment]
Submitted to ISISComputingGroup/IBEX in error.  Target control system is SECI, not IBEX.  Should really be in ISISComputingGroup/ControlsWork.  @jonelmer will contact @GDH-ISIS.
