### ISSUE TITLE
GALIL: indicate reason for begin failure

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2947]
It would be helpful if the galil driver printed details of why a BG command failed into its log file - I believe this can be obtained by e.g.  MG _SCA for axis A etc. 

It should also resync the motor position to the encoder position if it exists. We believe that this is why moves have failed.

Acceptance Criteria

1. After moving encoder without motor on next move motor is synced back to encoder
1. Move motor to limit. Move encoder to below the limit and then move motor to limit check that motor moves
1. Test #3112:
    1. On IMAT set axis with absolute encoder (Y) to central point. 
    1. Power cycle the galil controller.
    1. Move motor in both directions (Before this ticket this will fail)
    1. Ticket can now be closed

**Comment by FreddieAkeroyd** [comment]
Awaiting test on a Galil

**Comment by FreddieAkeroyd** [comment]
Putting into review, but to test properly would need a beamline with encoders. Ideally you need encoder and motor to get out of sync, manually redefining the motor position through DP in a telnet session may be enough, or physically moving/pushing the system to change the encoder but not remembered motor position. It will only come report and fix issues if  MTR0101_MOT_ENC_SYNC_TOL_SP is greater than 0 (in EGU)

**Comment by John-Holt-Tessella** [comment]
This doesn't seem to do the right thing. We set motor and encoder to 45, then hand moved it to 0. (At this point encoder shows 0 and motor pulses show MRES*45). Then move to 45 and get bad move. Moving to 90 moves to 45.

**Comment by FreddieAkeroyd** [comment]
A "bad move" is indicated if you are told to move to where you already are and that was not trapped earlier by the motor record. The motor records looks at the encoder, so thinks it is at 0, so passes it onto the driver that thinks it is still at 45. It looks like the out of syncness is not being spotted, I need to check that the new code is actually being executed - if it is then it thinks they are in sync as no message indicating attempted correction is displayed.

**Comment by FreddieAkeroyd** [comment]
Need to retest on stage on IMAT

**Comment by FreddieAkeroyd** [comment]
Seems to work fine, will merge
