### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2950]
As a developer I would like no longer used directories to be removed from the build tree. Candidates are:
   * ISIS/isisbeam
   * ISIS/diskspace
   * ISIS/epics web
   * ISIS/instrument regression test
   * ISIS/startup config
   * ISIS/testing framework
   * support/fake isis dae
   * support/pilot 
   * ioc/test (replace with simple from isis)

Initially just remove from .gitmodules but leave in GitHub

Also remove any macro from configure/MASTER_RELEASE that refers to them

**Comment by FreddieAkeroyd** [comment]
Also to consider:

* ISIS/SimpleIOC - compare to ioc/TEST etc
* ISIS/Common - where is this used?
* ISIS/choppersim - merge with mk3chopper or no longer needed?

**Comment by FreddieAkeroyd** [comment]
First batch removed

**Comment by DominicOram** [comment]
Common removed in https://github.com/ISISComputingGroup/EPICS/pull/240/files

**Comment by Tom-Willemsen** [comment]
Have been quite good at archiving old/unused repos of late, and we now have an automated check to make sure we're not building archived code. This is broadly complete, any follow up removals can be done in separate issues/flash reviews.
