### ISSUE TITLE
fermi chopper issue on MERLIN

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2951]
Reported by Helen Walker on MERLIN:

Hi, I am running a script this evening which does multiple monovan measurements, working through different frequencies and delays. Just now (21:00) it was meant to be setting a delay of 4000 odd, but it settled at 309us, and the green light went on to say it was within the gate, when it most definitely wasn’t, and this led to it vetoing. I then had to send the command again.
I spotted it this time, but it would be a problem if it happened in the middle of the night.
Any ideas?

**Comment by FreddieAkeroyd** [comment]
I talked to Helen and tried increased the delay in set_with_retry()

**Comment by Tom-Willemsen** [comment]
Sounds like it might potentially be ignoring the high byte of the delay setpoint. Check if https://github.com/ISISComputingGroup/IBEX/issues/2628 is similar?

Although I believe the above issue was resolved by
https://github.com/ISISComputingGroup/EPICS-FZJ-fermichopper/commit/93e711c829398a0a7c1c615f51b5f5331ca43351
https://github.com/ISISComputingGroup/EPICS-ioc/commit/97053994ce78dd635af14a3f7f1fec82ed60a2d4

**Comment by Tom-Willemsen** [comment]
1. Write their set_ei script in a defensive way so that it can recover from this issue.
2. Try to fix the underlying issue against the hardware (I'm going down to Merlin later to do this)

**Comment by Tom-Willemsen** [comment]
Part 1 implemented on NDXMERLIN config branch (set_ei command)

Part 2 implemented in pull requests above


This was never a consistent bug so it's hard to tell exactly when something is fixed or not. However the PRs above *appear* to have improved communication with the hardware, and the error handler in the script should be able to recover from this failure if it happens again.

**Comment by Tom-Willemsen** [comment]
Follow-up email sent to check whether the modifications I made improved the communications; looks like they did.

> Hi Tom,
> 
> Since the modification was made, it has been behaving perfectly.
> 
> Thanks
> Helen
> 
> From: Willemsen, Thomas (Tessella,RAL,ISIS) 
> Sent: 14 February 2018 11:04
> To: Walker, Helen (STFC,RAL,ISIS) <helen.c.walker@stfc.ac.uk>
> Subject: RE: progress?
> 
> Hi Helen,
> 
> Have you had any further issues with the chopper since I looked at it last week?
> 
> Thanks
> Tom
