### ISSUE TITLE
Journal Parser: Create automated build for joint IBEX/SECI instruments

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2952]
As a developer, I would like an automated build for the journal parser that will work on joint IBEX/SECI machines so that I can deploy updates to the journal parser to instruments without relying on a manual build process.

The journal parser is currently deployed as a statically built executable to its install location in LabView Modules on instrument machines. This is done as a manual process.

As part of ticket #2837 we decided that we would deploy the journal parser to IBEX machines as part of our deployment process. To do this effectively, we should have an automated build.

- The build should be termed something along the lines of "Shared control system tools", indicating that these are systems that are used by SECI and IBEX. It also gives us the option of adding more components later.
- The build may be static of dynamic. There was uncertainty about whether MySQL could be built statically
- Details of the existing system can be found in #2723

## Acceptance criteria

- A stable build exists in Jenkins that creates an executable form of the journal parser whenever it is updated
- A build exists in Jenkins that builds release branches of the journal parser
- When deployed on a test machine, subject to recorded deployment instructions, the journal parser works with both SECI and IBEX. That is:
    - The acceptance criteria of #2723 are met with the new executable
    - When used with SECI, runs are accepted by the system and published via Slack

**Comment by FreddieAkeroyd** [comment]
There is now a static VS2017 build of IBEX on Jenkins, this will build a JournalParser which currently just depends on mysql.dll    This MySQL DLL can be replaced by the VS2010 already on an instrument as the interfaces are compatible

**Comment by KathrynBaker** [comment]
There are now very few SECI instruments, and they won't be in place for much longer. Closing.
