### ISSUE TITLE
System tests: Set up Squish build

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2954]
As a developer, I would like a UI system test build that runs reliably via Jenkins that utilises our new Squish license.

This follows on from the UI test framework evaluation #2819.

It would be easiest to run the UI tests on a dedicated machine so that it can easily utilise the display. It should have VNC server installed which should be used for remote connections to avoid remote desktop stealing and then closing the display. Remote desktop should be disabled if possible.

Talk to Freddie and/or Chris about getting a dedicated machine set up in the cupboard.

## Acceptance criteria
- Squish build exists
- The build runs at least two short tests on the IBEX system
- The tests run independently (i.e. the server is cleaned between tests)
- The build uses the latest version of IBEX
- The build only runs between 7pm and 7am to avoid taking up licenses when they might be used by developers.
- The build runs at least once per day
- Remote desktop to build machine disabled if possible
- Suite_migrated_tests is converted to consistent style

**Comment by AdrianPotter** [comment]
Moving back to ready since I'm unlikely to get a significant amount done before I leave on Friday

**Comment by John-Holt-Tessella** [comment]
Umberella Ticket contains:
#3035

**Comment by John-Holt-Tessella** [comment]
All the jobs are setup and the computer is being updated to the latest version of windows.
Plan:

1. Install squish
1. Run jobs
1. Expand to include all test suites

**Comment by John-Holt-Tessella** [comment]
Impeded until the licence is paid for. After that it just needs the build to go green and then reviewing
