### ISSUE TITLE
MERLIN: error message in IOCLOG log

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2956]
Since 13:50 today merlin has been writing once a second to its IOCLOG

[Thu Feb  8 13:50:45 2018] Database error, error: 'Message Type "-" not recognised' Will retry.

It doesn't seem to have been doing it prior to then

**Comment by FreddieAkeroyd** [comment]
See #3240

**Comment by DominicOram** [comment]
Closing as duplicate of #3240
