### ISSUE TITLE
IMAT: unable to load scripts with load_script 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2957]
Winfried has reported that he is unable to load scripts - he gets syntax errors about all his print statements.  It sounds like load_script() might now be enforcing python 3 syntax?  Please contact him on Friday, it doesn't need to be fixed immediately but needs to be fixed in time for TS2 beam at the weekend.

**Comment by John-Holt-Tessella** [comment]
@Tom-Willemsen will contact Winfried and sort.
This is not an error from the script checker which does this:

    ERROR: script not loaded as errors found in script:
        Line 4: 'end' command without brackets

If it was then the error can be turned off and on with the parameter "warnings_as_error". This is not in the documentation but is in the codes do string (why is this?).

**Comment by Tom-Willemsen** [comment]
To be hotfixed on:
- [ ] ALF
- [ ] DEMO
- [ ] EMMA
- [ ] ENGINX
- [ ] HRPD
- [ ] IMAT
- [ ] IRIS
- [ ] LARMOR
- [ ] MERLIN
- [ ] MUONFE
- [ ] POLARIS
- [ ] RIKENFE
- [ ] SANDALS
- [ ] VESUVIO
- [ ] ZOOM
