### ISSUE TITLE
genie_python: Documentation is not updating

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2958]
The autogenerated manual documentation is not being updated! Examples are load script and waitfor. (notice they are not the same as the documentation in the code http://shadow.nd.rl.ac.uk/genie_python/sphinx/genie_python.html)

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd how is this meant to be updated? Is there a script or is it manual?

**Comment by Tom-Willemsen** [comment]
Docs now updating using code from https://github.com/ISISComputingGroup/genie_python/commit/4afa1b331c152a3162b3a7f913de9dd44ad72180 in this jenkins job: http://epics-jenkins.isis.rl.ac.uk/job/genie_python_docs/
