### ISSUE TITLE
Galil: Investigate different accelerations when homing

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2961]
As a ZOOM instrument scientist I would like to be able to home the baffle and detector. Currently, when trying to home, they do not use the same acceleration/velocity as when doing a conventional move, resulting in stalls or running speeds the axis isn't 'happy' with. We should ensure that homing uses the same parameters as a conventional move.

**Comment by DominicOram** [comment]
This can be repeated on the galil in the office:
* Start a galil ioc connected to the office galil
* Set the VELO and HVEL of the first axis to the same value
* Do a normal move on the first axis
* Open a terminal to the Galil, note down the value returned from ACA (this is the acceleration)
* Do a home move
* Note that the value returned from ACA now is different, they should be the same

**Comment by IainJohnson** [comment]
Hi Dom, similar observations in IMAT, but with Acceleration / deceleration.

I set the Accel/Decel by either or - Low-level using Galiltools, or CAPUT ACCL JAR, or in the IBEX GUI Fields.
If I use the Home Toggle Buttons to make a move, ACA DCA then return a value of 499712.(!?)
If I use the Jog Toggle Buttons, it does write down the correct values to ACA DCA.
If I do setpoint moves, ACA DCA always return 1024 no matter what I've previously set them to, using any method.

**Comment by DominicOram** [comment]
Yep, that's the exact behaviour i'm seeing here. I think I have a fix, which I might apply to ZOOM this afternoon. Would you like me to apply it on IMAT too?

**Comment by IainJohnson** [comment]
Yes please. - I can test it safely here, I'm currently using a test motor & switchbox. Thanks.

**Comment by AdrianPotter** [comment]
Does what it says on the tin. Please just confirm why the Piezo homing routine hasn't been changed like the others.

**Comment by AdrianPotter** [comment]
I know rework is a little harsh but since this is my last day in the office I wanted it to be obvious what state it was in.
