### ISSUE TITLE
IOC test framework: stabilize XY beamstop

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2967]
As a developer, I don't want to have disabled test suites in the code.

Several tests for the XY beamstop have been temporarily disabled because they were too unstable to allow the IOC test framework jenkins build to pass reliably.

These tests need looking at in depth to find out what is sometimes going wrong with them.

Acceptance criteria:
- [ ] If I run the XY beamstop test suite 10 times in a row, all runs pass.
- [ ] The problem and solution for this test suite are documented on the wiki

**Comment by DominicOram** [comment]
This has been successfully stabilised by removing the tests as they were no longer required
