### ISSUE TITLE
Enginx Jaws: Harmonise with GEM Jaws

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2968]
As a developer I would like to improve the code reuse of in the Enginx Jaws. The GEM jaws (#2138) are better written than the Enginx ones, despite being very similar, the two can probably share code so that:
* The OPI uses the same representation diagram (this may also effect other coupled_jaws)
* The inverse quadratic is used

**Comment by DominicOram** [comment]
Superseded by #4191

**Comment by KathrynBaker** [comment]
Closing as superseded
