### ISSUE TITLE
IMAT: disconnected monitor blocks

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2971]
Winfried sent via footprints:

> Monitors blocks are shown sometimes disconnected, connected etc on IBEX.

**Comment by Tom-Willemsen** [comment]
Difficult to reproduce (but I have reproduced it once, and no client or DAE logs were obviously wrong). Might be the same issue as #2750 given that it's PVs coming from the DAE.

Symptoms are that all the monitor blocks appear as disconnected. Switching instrument back to the same instrument cleared the problem. 

I'm not sure this is worth prioritising right now so leaving in backlog.

**Comment by Tom-Willemsen** [comment]
Note: appears to be a server issue. I had 8 clients open looking at IMAT and the blocks all became "disconnected" at the same time.

![image](https://user-images.githubusercontent.com/24375813/36201589-5eb0c328-1178-11e8-8716-97b22faaaa3c.png)

Some time later (a few minutes) all of the clients seemed to simultaneously start receiving updates again, and the blocks became reconnected.

**Comment by FreddieAkeroyd** [comment]
Your 8 clients would all be looking at the IMAT gateway so worth checking that log too.

**Comment by FreddieAkeroyd** [comment]
After looking a bit more with @Tom-Willemsen there are breaks in connection recorded in the gateway that correspond with end of one run / start of the next.

**Comment by FreddieAkeroyd** [comment]
Having looked at the channel access code, monitors are done via timer callbacks - so a camonitor would be ok at a start/end as though the timer thread may take a long time that is separate to channel access.  A direct caget of a PV that is not being monitored would result in a delay as that is done directly, but it is not clear how this would upset other monitors unless all channel access was on the same thread or shared a lock in some way. If this is the problem, then doing a caget of a non monitored monitor/spectrum during a begin/end would cause the issue - maybe we need to check imat's script to see if anything like this is being done

**Comment by FreddieAkeroyd** [comment]
The PR makes the call wait a maximum of 5 seconds for a caget on a non monitored pv (if the pv is monitored, the last monitored value is returned with no delay). Testing wise, you could add a large sleep value to the reading loop and the check performance before and after the change, previously it would hang for the value of the sleep you set, after patch the caget should return within 5 seconds.
