### ISSUE TITLE
Technical debt stand down: Feb/March 2018

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2972]
Technical debt stand down for February/March sprint 2018. Provisional topic is IOC testing. Confirm with the team before finalising.

In the event that we do IOC testing, we need to decide how emulators should work. Should they provide pseudo-realistic behaviour (i.e. values change in intuitive ways that make sense for the device in question) or whether they should just be a collection of properties set via the back door. This dichotomy arose during the discussion of the FZJ Fermi chopper.

An alternative to the tech debt stand down day would be to have a stand down day for Nicos. Knowledge of this side of the system is currently slightly silo-ed with @DominicOram and it would align well with our goal to have an MVP ready this sprint.

**Comment by AdrianPotter** [comment]
An alternate suggestion from the sprint retrospective would be to look at speeding up the build system. Part of that could be a group effort to finish: https://github.com/ISISComputingGroup/IBEX/issues/2320, enabling us to do parallel builds

**Comment by AdrianPotter** [comment]
First send out a poll to decide on date

**Comment by AdrianPotter** [comment]
Awaiting team feedback from Slack poll

**Comment by AdrianPotter** [comment]
I'm out for the next couple of days so Tom is going to sort out choice of topic

**Comment by AdrianPotter** [comment]
Stand down complete. The builds are in a bit of a state, we need to sort them out before this is considered complete

**Comment by Tom-Willemsen** [comment]
Builds are stable, passing, and much faster. Marking as complete.
