### ISSUE TITLE
E4: Alarms "Server Timeout" label

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#2974]
Although the data in the alarms perspective seems to update properly, there is a "server timeout" label displayed in the top right corner. Investigate and make sure the label accurately reflects the status of the connection to the alarm server.

**Comment by John-Holt-Tessella** [comment]
The alarm server uses both JMS and MySQL to get data and I believe that these back each other up. Maybe one of these is not connecting correctly.

**Comment by AdrianPotter** [comment]
As part of #2872, the alarm view has too much grey-space at the top of the view and the layout of the refresh button and server timeout messages are poorly handled. Please look at it as part of this ticket if possible

**Comment by Tom-Willemsen** [comment]
No longer an issue
