### ISSUE TITLE
HOTFIX: update instrument galil startups

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2975]
Instrument startups need to be updated to avoid galil startup issues with missing motor control macos 

https://github.com/ISISComputingGroup/EPICS-ioc/commit/5e662e676afb55c55c5a07546a046bd2bd846930

**Comment by DominicOram** [comment]
To be hotfixed on:
- [ ] ALF
- [ ] DEMO
- [ ] EMMA
- [ ] ENGINX
- [ ] HRPD
- [ ] IMAT
- [ ] IRIS
- [ ] LARMOR
- [ ] MERLIN
- [ ] MUONFE
- [ ] POLARIS
- [ ] RIKENFE
- [ ] SANDALS
- [ ] VESUVIO
- [ ] ZOOM

**Comment by Tom-Willemsen** [comment]
Checked on a selection of beamlines that this fix has been deployed. Documented appropriately on IBEX wiki.
