### ISSUE TITLE
globals.txt: check MTRCTRL is defined if GALILAADR is 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2977]
This needs to be done quickly on the instruments now, the upgrade script will needs to be enhanced to do this too

**Comment by FreddieAkeroyd** [comment]
Now fixed - IMAT, LARMOR, LET and ZOOM have such definitions in globals.txt

**Comment by DominicOram** [comment]
Confirmed listed globals.txt have been updated and other globals.txt contain no split macros
