### ISSUE TITLE
LARMOR: loss of motor positions

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2979]
Rob added a new configuration and this resulted in him losing motor positions. The trigger for this was that he loaded his base component, which stared all the IOCs but didn't have the new MTRCTRL macro defined. The galil addresses were defined in globals.txt but MTRCTRL must have been added to a configuration, but then loading just the base component caused all galils to start thinking they were GALIL01. These issues are being addressed in #2976, #2977 

Having restored the settings from autosave, motor positions had been reset to strange values, some were 0, several were -1, some others randomis numbers. The only galil with sensible values was GALIL 01. It is not clear why the positions got reset, something similar happened on ZOOM though when MTRCTRL was undefined.

**Comment by Tom-Willemsen** [comment]
Ttickets for underlying cause have been fixed, larmor positions were clearly recovered at some point between 2018 and now.
