### ISSUE TITLE
Motion Set Points Lookups: Can't have multiple items with exactly the same co-ordinates

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2983]
As an IBEX user, I want to be able to provide different labels to the same co-ordinates when they have different logical functions.

**Acceptance Criteria**
1. There is a way to provide this functionality
1. If this cannot be provided there are notes and explanations as to how the setup should be done, and this is clear to users and developers, and a more graceful exit from the error condition

**Notes**
1. This was discovered to generate a bug on SANDALS when there were two items with the same value in the Lookup list for the sample changer, going to one of the items then caused the whole IOC to disconnect, providing an implied coms failure
1. See also #2870

**Comment by AdrianPotter** [comment]
Not clear if this is motion set points or SM300

**Comment by GDH-ISIS** [comment]
A problem occurred again on SANDALS that I think related to this problem. Found another duplication on position 9 in the motionsetpoints\sample.txt file. Removed the duplication, restarted the IOC a few times, and it looks operation again. Not certain if this is the full solution to the problem on SANDALS.

**Comment by AdrianPotter** [comment]
The duplication on position 9 was introduced during testing on the Friday. It should have been removed. We subsequently fixed the related issue in the sample changer as part of ticket #2992. I've tested `motionsetpoints` with a simulated motor and found no issues. Following fix #2992, the next step is to verify that this issue no longer occurs on a live instrument (i.e. SANDALS)

**Comment by FreddieAkeroyd** [comment]
Various things fixed as detailed in PR and tests

**Comment by FreddieAkeroyd** [comment]
Should fix #2906 too
