### ISSUE TITLE
SECI -> IBEX Galil parameter converter: is it setting HOMEVAL?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#2985]
As per #2471 the default home positions should now be zero, however the recently converted EMMA-A instrument has non-zero HOMEVAL on  its axes e.g.    IN:EMMA-A:MOT:MTR0101_HOMEVAL_MON  returns 76.5   I am guessing that is because the Galil converter script is still generating HOMEVAL - if this is the case could it please be changed to instead set the motor record OFF (user offset) field to the previous home position and set  HOMEVAL_SP to zero

**Comment by FreddieAkeroyd** [comment]
In future there will be no HOMEVAL available in the GALIL IOC, so assigning the LabVIEW home position by that route will no longer be possible. Setting the user offset to the HOMEVAL will cause the position to shift compared to the previous readback, that should be fixed by a rehome which I'm guessing is likely to happen after an IBX conversion to check the IBEX homing is working? If a home is not possible/desirable the current motor position would need to be redefined back to where it was before - maybe it would be best if the generated conversion script did this anyway? Or would it be better to redefine the home position to zero and set a user offset in LabVIEW before doing a conversion, that way the Galil.ini would still be correct after conversion?

**Comment by AdrianPotter** [comment]
It sounds like we need to better understand how the HOMEVAL conversion is being done by the existing script.

Please could the following be done:

- Decide how SECI HOMEVALs should be treated in IBEX
- Make the appropriate changes to the conversion VI
- Put the updated VI somewhere accessible to the dev team
- Record the changes and steps in the appropriate [wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX)

**Comment by FreddieAkeroyd** [comment]
For info, the procedure to reset a HOMEVAL is described here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Resetting-HOMEVAL

**Comment by FreddieAkeroyd** [comment]
With regard to the first point above, SECI homevals should ultimately be converted to offsets as agreed in   #2184 / #2471 - the question I think is at what stage this is done: manually prior conversion (so Galil.ini remains valid for example), during running of the conversion Vi, or afterwards as a separate step. If the instrument is ever likely to swap back to SECI then a correct Galil.ini is required, so maybe the solution is to zero the home position and set an offset in LabVIEW prior to conversion?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd , @GDH-ISIS - what's the status of this ticket?  Is it complete?  Can it be closed?

**Comment by John-Holt-Tessella** [comment]
OK instructions for getting the latest VI is now on the wiki under migrating motors see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX#copy-across-the-motor-setup

**Comment by John-Holt-Tessella** [comment]
The conversion in the labview is incorrect as demonstrated on MARI. The problem is for absolute encoder which can not have a home offset set because the encoder can not be set to a value. So this is not the correct value of offset in IBEX.

 I **think** it needs to do the following. Can someone who understands motors and labview look at the second part of this calulcation. Then can someone who understands lab view do the fix.

If the motor has an absolute encoder (ignore home offset this can never be applied):
    - Epics HOMEVAL = 0
    - Epics OFFSET = Offset

If the motor does not have an absolute encoder :

    - I don't know what to do if the home offset and offset are both set because I can't find the Labview code. I suspect that the offset needs to be a combination of them; this depends on where the offset is included when the home offset is set or not.

**Comment by FreddieAkeroyd** [comment]
In don't think offsets were ever used in LabVIEW though there is some code to support it i believe

**Comment by John-Holt-Tessella** [comment]
They were definitely used in MARI. Maybe it is only for absolute ecoders.

**Comment by FreddieAkeroyd** [comment]
Maybe there is more than one type of offset in the LabVIEW - when it was suggested changing LabVIEW to use a 0 home position and an offset rather than redefining the motor position I believe the answer was that the code/approach hadn't been used/tested before. But as you can't "define position" for an absolute encoder it must be doing something offsetty, maybe as a special case?

**Comment by ChrisM-S** [comment]
I don't want to muddy the waters here as I don't understand offsets in the the LabVIEW ToM but I believe there are implicit offsets in VIs for some things like rotation stages were a zero is "set" from the users point of view when the stage is lined up with a fixed sample position for example.  This just allows the scripts to be written to go from -180 to +180 (say).

**Comment by KathrynBaker** [comment]
Absolute Galils are a very specific case, they use home in a different way. Some VIs do indeed have implicit offsets, but this is the standard script for converting parameters underneath. Specific IOCs are a different set of issues, and should be dealt with in a different place to this.

**Comment by ThomasLohnert** [comment]
Some more points to check that came out of CRISP testing:
- It seems like the SECI Galil de-energise setting is not getting migrated. I believe the IBEX default is that de-energise is `enabled`. If it is `disabled` in SECI, you need to set `MOT:MTRXXXX_AUTOONOFF_CMD` to 0 and `MOT:MTRXXXX_ON_CMD` to 1 as part of the conversion. (This means the controller is always on)
- Backlash is set up slightly differently in SECI in that you can specify a backlash for each direction which somehow informs the `Backlash distance` setting for the Galil in IBEX. It is not clear whether this is / should be a direct mapping, or which value the conversion script uses, i.e. only one, either, both ... ? Check the behaviour in SECI and ensure this is translated properly to IOC settings.

**Comment by kjwoodsISIS** [comment]
This ticket has been open for more than 1 year.  When is it going to be completed?

**Comment by DominicOram** [comment]
Can we also confirm whether

**Comment by John-Holt-Tessella** [comment]
Split into smaller more targtted tickets

**Comment by KathrynBaker** [comment]
The split of the tickets into lower ones makes good sense to me, and this should cover the areas that are not currently handled well.

**Comment by FreddieAkeroyd** [comment]
The motor record now supports "setpoint deadband" - did labview have this concept?
