### ISSUE TITLE
SANDALS: Unable to communicate with sample changer

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2992]
The SANDALS sample changer has recently entered a state where it cannot communicate with IBEX. Testing with the VI suggests this is not a hardware of networking issue. The logs report an error communicating with the COM port

**Comment by AdrianPotter** [comment]
This has been fixed on SANDALS. We discovered two issues:

- The IOC seemed to break when we moved the sample changer to a position that matched more than one position in the motion set points file. Preliminary inspection of the code by @FreddieAkeroyd didn't reveal why that might be. This needs investigating further. For the time being, we've removed the degeneracy in positions on GEM.
- The settings used in the `st-common.cmd` file for the SM300 use software flow control. We suspect this was copied from the McLennan. Unlike the McLennan, the SM300 communicates with non ASCII characters, some of which can interrupt the flow control. The VI doesn't use flow control at all. Once we switched it off in SANDALS's IOC, the sample changer worked as expected. This change needs adding to the master branch and recording in the manual.

**Comment by AdrianPotter** [comment]
Debugging conducted by @FreddieAkeroyd , @DominicOram , @Tom-Willemsen and me. Removing others from assignment to avoid confusion about who's currently working on it

**Comment by AdrianPotter** [comment]
1. I've added the changes made to SANDALS to the IOC. PR to follow
2. I've tested SANDALS's setup on DEMO with a simulated motor. I tried with lots of variations of duplicated position. In no cases did it crash the IOC. The current position is always the first position in the list that matches the reported position, so it doesn't always match the target position. However, I think that behaviour is acceptable for the time being and the lack of crash suggests that the reported bug was a red herring.

**Comment by AdrianPotter** [comment]
Note that the symptoms of this problem were that the IOC logs reported connection issues with the associated port. Switching on asyn traces indicated that data was being written to the port but not was being read back. Examining the MOXA traffic indicated that no data was being transferred.

**Comment by kjwoodsISIS** [comment]
OK.  Good work in getting to the bottom of this.  What lessons can we learn from this?
1. one lesson appears to be that we should be careful about copying from other the `st-common.cmd` files - we don't want to inherit invalid settings.
1. The VI doesn't use flow control.  Ideally, there would be a comment in the VI to make a positive statement to the effect that "flow control is not used".  If there is no comment, it would be a good idea to ask Gareth, Kathryn or David, although there is no guarantee that they might know - absence of a comment doesn't signify anything, except the absence of a comment.
1. other lessons?

**Comment by KathrynBaker** [comment]
Where a VI doesn’t use flow control it is always explicit as a command, the Flow Control option is set to “None”, or if there is no setting set in a VI then it is “None”, as that is the default that LabVIEW uses, so a lack of comment, or any other setting means that the flow control is “None”.

**Comment by FreddieAkeroyd** [comment]
I recently improved the diagnostic output from the "dbior" command for asyn serial, it would now print 
 "waiting as seen Xoff"  in such cases
