### ISSUE TITLE
genie_python: Report block state on cset

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3000]
As a Polaris instrument scientist, I would like cset to report what the new block state is as a result of the command so that I can verify the state I thought I set is what has been set.

The output would be similar to doing a cshow at the end of the cset command. It may be triggered only by a verbosity flag, although it's not clear that:

```
g.cset("Block", 1, verbose=True)
```

is much different from

```
g.cset("Block", 1)
g.cshow("Block")
```

**Comment by kjwoodsISIS** [comment]
What would be the view of scientists from other instruments regarding this proposal?  Would they welcome it, or find it a nuisance?

**Comment by AdrianPotter** [comment]
It's not clear whether they'd want the `SP` or `SP:RBV` value displayed. Also, a global option for verbosity would presumably apply to everything, including run state changes? They might then consider that to be too verbose.

If it turns out this isn't sensible to implement, please add a `wontfix` label and could we make sure it is fed back to Polaris to explain why.

**Comment by ChrisM-S** [comment]
`g.toggle(verbose=True, debug=False)
`etc.
a.k.a. Open GENIE?

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/305
