### ISSUE TITLE
CAEN: Extend the GUI scripts for the CHANLIST to cover more channels

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3002]
The scripts to read the number of channels etc. for the CAEN currently uses hard-coded limits for the number of channels to read more channels (23 in the case of ZOOM, not the 10 it is currently set to).

The scripts could also be refactored and improved as part of this ticket.

It might also be worth considering revisiting #896 and ensuring that the additions in #1006 don't solve the scenario.

**Comment by John-Holt-Tessella** [comment]
Refactor to puthon if possible

**Comment by AdrianPotter** [comment]
@KathrynBaker, please can you comment on @John-Holt-Tessella's latest feedback?
