### ISSUE TITLE
CAEN: Being turned on should not be a minor alarm

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3004]
The HVCAEN IOC categorises the channel being on as a minor severity, this isn't typically appropriate and should be changed ~to a non-alarm state~. It is not clear that all groups will use the CAEM in the same way so for the minute make this a hidden macro so it can be changed on the fly if needed.

Acceptance

1. CAEN and SIM CAEN can be placed in ramping up, ramping down and on state and this causes no alarm
1. Two macros can be set within the globals.txt to alter the alarm of both ramping states (up and down) and on state.

**Comment by AdrianPotter** [comment]
Just awaiting Slack feedback from @jeremyspencer39171 and @KathrynBaker. The ticket description and implicit acceptance are that the MINOR alarm should be switched off. Instead it has been macroed. The code looks fine, but it adds additional complexity, the need for which is undocumented.

**Comment by John-Holt-Tessella** [comment]
I will update the ticket
