### ISSUE TITLE
ENGINX: LINMOTS not starting

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3006]
LINMOT iocs 01, 02 and 03 failed to start on ENGINX - it looked like the procserv port was being used, seems a strange coincidence all 3 at the same time. netstat gave a process id that was still using the port, claimed to be connected, but did not exist in the system. Ran iocs up by hand as temporary measure.

**Comment by Kevin-Woods-Tessella** [comment]
Is this related to #2998?

**Comment by FreddieAkeroyd** [comment]
It could be, if the slow serial meant the process didn't die quickly enough, but the tcp port seemed to be owned by a dead process but "connected" rather than "time_wait". Doing #1484 would fix this sort of problem. They seemed to get the issue if they run "start_ibex_server", I told them to run stop_ibex_server, wait 30 seconds, and then run start_ibex_server - that seemed to work OK

**Comment by FreddieAkeroyd** [comment]
Likely same as #2998 so closing
