### ISSUE TITLE
Tech debt stand down: March/April 2018

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3007]
At the previous tech debt stand down, we focused on the build system, #2320. We have made significant progress in that error and the builds are subsequently much quicker.

We haven't yet finished that ticket because the IOCs still need their dependencies mapping correctly. We should make sure that any IOC whose dependencies are changed have a basic emulator and IOC tests to ensure that there aren't any issues with dynamic dependencies and macro mapping.

The current proposal is to look at IOC testing in the next stand down.

- Decide fundamentally whether emulators should be usable (i.e. respond in intuitively via the OPI), or do just enough to pass IOC tests. 
    - I'll be away when this is discussed. My feeling is that I find it clarifies both my understanding of the device and makes development easier to make the emulator usable. It also means I can better leverage the knowledge contained in the VI if the emulator can interact with it sensibly. If the emulator is intentionally programmed to just provide the data the IOC test expects then there's no logical link between the physical hardware and our test stack, which seems wrong.
- Rework the IOC test framework API
    - It's a good framework but the API has grown wild over time as we've added more functions. There's a lack of consistency in function scope and naming.
- Tighter Lewis integration
    - At the moment, Lewis is launched as a separate process. As it's Python we should be able to access it directly from within the framework which would grant much greater control
- Launch from st.cmd
    - If we could launch emulators directly from the st.cmd files then we would have seamless access to them in DEVSIM mode. It would also make launching easier.
- Add tests/emulators for missing IOCs
    - This would be the major piece of the work. To ensure we haven't broken any of the existing IOCs, they would ideally have some automated tests. We could manually test, but it is unreliable.
- Parallelize the tests. This should be possible with the new style test framework but will need some locking logic to ensure the same IOC isn't launched twice at the same time

IOC testing isn't a forgone conclusion as the topic for the stand down but it has been a candidate for a number of sprints and has a number of advocates.

**Comment by Tom-Willemsen** [comment]
Scheduled for 29th March

**Comment by Tom-Willemsen** [comment]
There are still a handful of PRs to be merged before this ticket can be considered complete:
- [ ] Linkam 95 https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/81
- [ ] Inhibitor https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/83
- [ ] PDR 2000 https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/82
- [ ] Neocera https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/78
- [ ] Fins https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/73
