### ISSUE TITLE
Link to external journalviewer script

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3013]
Requested from Matthew on VESUVIO:

> Would it be possible to include the link to the journal in IBEX and run the HTML script linked to it page to be working under IBEX?
>
> \\\isis\inst$\NDXVESUVIO\Instrument\logs\journal\journal_main.html
>
> This would enable updatable, filterable “last list experiments view” that could be put into the DAE Control Program pane of the IBEX dashboard…
>
> I can currently work on this script off-line without the internet and display the list for experiment planning.
> However, such functionality used to be integrated into SECI before without the need to ‘change gears’ and hop on and off from program to program when running the instrument..

Obviously, we have the IBEX integrated journal viewer forthcoming, but some of its features are not yet prioritised. Is this likely to be ready for the next release, and if not, is it worth including a link to the above page in the journalviewer perspective until our solution provides the same level of functionality?

**Comment by KathrynBaker** [comment]
No longer viewed as necessary by the SAG, the existing functionality in IBEX is enough there when combined with the external viewer which has since been updated.
