### ISSUE TITLE
Calibration File Update outside of IBEX Release

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3016]
As a support member of staff, I want to be able to access the latest calibration files on the instruments

**Acceptance Criteria**
1. There is a method of pushing these files to all instruments that is well documented or easy to run that does not involve logging onto the instruments individually to do a git pull, and which does not upset git later
1. This needs to be done during the shutdown over Easter 2018

**Notes**
1. Needs the calibration files to be converted first (see ControlsWork/issues/409)

**Comment by ChrisM-S** [comment]
The logic of a simple "git pull" can be retained if this is done with PS-remoting but (this is still a push in terms of managing the instruments, e.g. but the local command is the same as if you were on the machine and is a normal pull.

```powershell
C:\> powershell
PS D:\> function wa { $args }
PS D:\>  wa NDXTEST NDXINTER NDXEMMA | %{ Invoke-Command $_ {cd calibration; git pull } }
```

I use this for lots of things (but you could also use psexec).

**Comment by KathrynBaker** [comment]
Thanks Chris,

Having this documented on the wiki in the right place to be found easily would be enough to complete this ticket once the steps have been applied to the files and instruments, but whilst I know there are ways to do this, I don’t know what they are, and which is the best for us to use within the IBEX framework.

Regards,
Kathryn

**Comment by KathrynBaker** [comment]
Calibrations have been converted and pushed to the appropriate git repo, just need to deploy them to the instruments

**Comment by John-Holt-Tessella** [comment]
Talk to Chris

**Comment by John-Holt-Tessella** [comment]
Calibration files not found in repository. Will talk to Kathryn when she returns.

**Comment by KathrynBaker** [comment]
I had failed to actually commit the files, I was doing the work too fast and then failed to realise that it didn't actually add them. They have no been added.
