### ISSUE TITLE
GEM: Make centre of beamline jaws propagate to beamscraper jaws

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3018]
As an instrument scientist on GEM, I would like the beam centre setting that I set on the beamline jaws to propagate through to the beamscraper jaws.

**Comment by Rory-Potter-Tessella** [comment]
The button appears to work and does what it says it should.

However, I discovered an intermittent failure to set Horizontal and vertical gap of the LIMNOT motor on JAWS6 Motor on GEM. I have created a ticket for this.
