### ISSUE TITLE
TRITON: new Oxford instruments software

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3030]
Oxford instruments are updating the software on the triton systems. They have made some modifications to the communications protocol, so the IOC will need changing to keep up.

- Remove Valve statuses (this causes large log files to build up on the Triton system
- Ensure channel indexing is correct. Their software had a bug where asking for channel N actually yielded the information for channel N+1, which we compensated for in the IOC. They have now fixed this.

Notes:
- Cryogenics have not yet updated any fridges - we can't test this until the updates are done. They likely won't update any fridges before the shutdown.

**Comment by kjwoodsISIS** [comment]
How many points?
