### ISSUE TITLE
2954-1: Add Clean Ibex Server

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3035]
Create 2 tests which won't run unless "Clean IBEX server" script is run and then add clean ibex server script from RCPTT so that the testing environment can be made better.

See umbrella #2954

**Comment by John-Holt-Tessella** [comment]
Repo at https://github.com/ISISComputingGroup/System_Tests_UI_E4

**Comment by Tom-Willemsen** [comment]
Code looks sensible. Haven't been able to run the tests as we don't have a license yet but @John-Holt-Tessella assures me that they work.
