### ISSUE TITLE
New Motor record (Axis Record)

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3037]
To address issues in #2434 we should try the new version of the motor record

**Comment by John-Holt-Tessella** [comment]
Supported in: https://github.com/ISISComputingGroup/EPICS-ioc/commit/7146c7d4b3c46c75e3bab4185ef1a2f34e888e6b
https://github.com/ISISComputingGroup/EPICS-MCAG_Base_Project
https://github.com/ISISComputingGroup/EPICS-axisRecord

**Comment by FreddieAkeroyd** [comment]
Installed on IMAT, readback looks to be working, sample stacked locked off so cannot do final test yet.

**Comment by FreddieAkeroyd** [comment]
I'd guess about 2 so far, but there is a final test to do when the SPS is unlocked

**Comment by FreddieAkeroyd** [comment]
Reported as working by Winfried
