### ISSUE TITLE
Web dashboard: Redirect webpages to appropriate IBEX/SECI page

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3048]
As a user I would like to not have to worry about whether I am running IBEX/SECI when going to the web dashboard. As such there should be one url (preferably the same one scientists were previously using) that will direct me to the correct dashboard based on what the instrument is running.

**Comment by KathrynBaker** [comment]
+1 of sorts, GEM have a link on their external web page to their dashboard, we should have told GEM about this change so that they updated their link (Footprints 10 #77378) but had we implemented this then we would not have had the bug.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISNeutronMuon/SECI-WebDashboard/pull/1
