### ISSUE TITLE
CALab: Upgrade to version 1.6.0.9

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3057]
As an IBEX supporter I want to keep my modules up to date, a new version of CA Lab has been released (announcement on Tech Talk 20/3/18) and I would like to evaluate changes and upgrade to that version, 1.6.0.9.

**Acceptance Criteria**
1. Version 1.6.0.9 has been considered
2. The version in LabVIEW Modules has been upgraded to 1.6.0.9
3. The version in IBEX has been upgraded to 1.6.0.9

**Notes**
1. It may be that the changes are too big or further tickets will be required to complete this if there needs to be alterations to the existing code base beyond simply updating the version in use.

**Comment by FreddieAkeroyd** [comment]
Should be relatively easy to upgrade, we haven't changed much:
* small fixes for compiling in base 3.15
* hide disconnect error window by default, with messages going to c:\data\log
 
https://github.com/ISISComputingGroup/EPICS-CALab/compare/vendor_1_5_0_5...master?w=1

**Comment by kjwoodsISIS** [comment]
See also #1188.

**Comment by kjwoodsISIS** [comment]
CALab is not used by IBEX.  It is used by SECI.

**Comment by FreddieAkeroyd** [comment]
caLab consists of a DLL (which we have modified slightly and build as part of IBEX but do not use) and a set of labview Vis (that are put into the seci version control system).  We are currently running caLab 1.5.0.5 the release notes are at https://www.helmholtz-berlin.de/zentrum/locations/it/software/exsteuer/calab/changelog_en.html - is there anything of particular urgency we need there?

**Comment by AdrianPotter** [comment]
An update of IBEX dependencies should be done as part of #3154

**Comment by FreddieAkeroyd** [comment]
Upgrading to 1.6.0.10 as it increases PV name lengths (which I was just about to look at)

**Comment by FreddieAkeroyd** [comment]
Binaries building on jenkins, new version in soucre safe for SECI

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by davidkeymer** [comment]
Review consisted of testing the new version of CALab on NDXTEST as it's more like a SECI-only instrument:
- Checked that the beam logger VI compiled, ran, and read facility PVs
- Read other remote PVs on G39 development machines via CALab's "Get PV" subVI
- Configured and ran the SKF G5 VI to communicate with LET's and IMAT's chopper controllers
