### ISSUE TITLE
Graph Plotting: Display plots and scripts together

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3058]
As a scientist, I would like to have a perspective that shows scripts and plots together, so that I can see the plot evolve dynamically as the script executes.

#### Acceptance Criteria
1. IBEX provides a perspective that contains a script pane and a plotting pane.
1. I can execute my scripts via the script pane.
1. I can draw plots (in the plotting pane) via my script.

#### Notes
1. The attached sketch shows how the scripting/plotting perspective might appear.
1. The scripting/plotting perspective doesn't have to be a brand new perspective; it could be an adaptation of an existing perspective.
1. The scripting/plotting perspective could show the output from the script in a separate pane
1. Matplotlib could be a very good way to provide dynamic plotting via scripts (see comment below).
1. The plotting pane is not intended to be a strip chart (i.e. a plot of a variable as a function of time).  It is intended to display plots of one variable against another
1. The plotting pane should be capable of displaying more than one trace on a plot (i.e. more than one variable on the vertical axis)
1. To demonstrate this feature we should write a script that shows the above capabilities (if it can use real PVs, so much the better; but just using made up variables would be acceptable.  Hint: consider creating a script that plots 2 or 3 gaussian functions).

**Comment by kjwoodsISIS** [comment]
![image](https://user-images.githubusercontent.com/7249337/37670124-6daa6e58-2c60-11e8-8d78-1786ffd17e26.png)

**Comment by kjwoodsISIS** [comment]
Possible solutions for incorporating matplotlib include:
   1.  https://github.com/sh0nk/matplotlib4j 
   1.  https://github.com/aliceinnets/java-jyplot 
   1.  https://github.com/LeeKamentsky/backend_swing (this may the most promising option).

**Comment by FreddieAkeroyd** [comment]
If javabridge (used in 3) is not the right technology, https://www.py4j.org/ might be useful

**Comment by Tom-Willemsen** [comment]
impeded as discussions still ongoing

**Comment by Tom-Willemsen** [comment]
Having discussed a proposed solution with Andrew Caruana and Adam Washington, the following are required functionality of the plotting window for reflectometry and SANS workflows:
- Plotting both the raw data points and their fit function
- **Error bars**
- Plotting multiple series on a single plot
- Legend / Axis labels - may be dynamic as the plot evolves
- Different shapes & colours for different data series
- Ability to set auto-scale independently on x and y axes

Nice to have:
- 2D heat map support
- Switching between log/linear scales
- Zooming in and picking particular data points
- Multiple plots (?)

**Comment by kjwoodsISIS** [comment]
How much of this functionality is provided by existing CSS capability?
I guess matplotlib can provide it all - is that correct?

**Comment by John-Holt-Tessella** [comment]
Most of this is provided by CSS but the Error bars are not and this is a definite requirement. We could fake them with dashes but I don't think this is a good start.

Matplotlib does have this capability I believe but not sure whether matplotlib in java does.

**Comment by John-Holt-Tessella** [comment]
I started writing up [old meeting](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Graphing)

**Comment by kjwoodsISIS** [comment]
OK.  We should investigate the feasibility of displaying a matplotlib graph in Java.  If we can run the Python code on this page (suitably adapted, of course), then we'll have demonstrated the capability.

**Comment by FreddieAkeroyd** [comment]
A different matplotlib backend https://matplotlib.org/faq/usage_faq.html#what-is-a-backend could do the job, the one mentioned above https://github.com/LeeKamentsky/backend_swing sounds promising but something based on other existing matplotlib vector graphics backends is an option too. If they know what commands they need, then we could always develop our own genie_python plot interface and then how that interacts with java is up to us, this could be an option if a java backend looks awkward for example

**Comment by Kevin-Woods-Tessella** [comment]
Attaching screenshots with show plots of:
1. Field as a function of current: ![muon_field_amps](https://user-images.githubusercontent.com/34268759/42496162-19d9a072-841d-11e8-9497-c4d23799bb57.png)

2. Muon counts as a function of current: ![muon_tuning_graph](https://user-images.githubusercontent.com/34268759/42496176-23dcf1b4-841d-11e8-8797-3f89788ae3c2.jpg)
