### ISSUE TITLE
MAPS: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3059]
As an instrument scientist, I would like to migrate MAPS to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on MAPS
1. Configuration files matching the current SECI config files are created 
1. IBEX is configured for the devices on MAPS.
1. MAPS scripts are converted to genie_python
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
1. MAPS scientists are trained in how to use IBEX
1. IBEX is tested on MAPS

#### Notes
1. The devices on MAPS are listed on the [MAPS Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MAPS-Instrument-Details) list
1. The Fermi chopper may not be ready in time for the migration of MAPS to IBEX.  The instrument scientist wishes to proceed with the migration even if the Fermi chopper is not ready.
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for MAPS.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
- [x] Check that NDXMAPS has sufficient disk space to install IBEX
  * MAPS has 30Gb of free space.
- [x] Check whether MAPS uses 5- or 8- digit run-numbers
   - [x] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [x] Create a virtual instrument for testing purposes
   - [x] Set up a test system, NDXMAPSTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
   - [x] test these configurations & scripts *Email sent to Ross to check he is happy - Tom*
   - [x] check that all the devices previously supported by SECI (on MAPS) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX *I have checked with Ross that he is signed up for the training course - Tom*
   - [x] demonstrate the configurations & scripts (created above) to the instrument scientists and check that they are happy with the migrated configurations & scripts *I have had a meeting with Ross to Discuss the scripts, and I have given him access to the test machine to have a look at - Tom*

**Comment by kjwoodsISIS** [comment]
Speak with Russell to ask if he wishes the script conversion to be a collaborative process.

**Comment by kjwoodsISIS** [comment]
> From: Woods, Kevin (Tessella,RAL,ISIS) 
> Sent: 05 April 2018 11:50
> To: Shuttle, Anthony (STFC,RAL,ISIS)
> Cc: Keymer, David (STFC,RAL,ISIS)
> Subject: MAPS: Private Network for Cycle 2018/01
> 
> Hi Anthony,
> 
> We are planning to migrate MAPS to IBEX in the shutdown prior to Cycle 2018/01 (i.e. during the period 19th May – 4th June).
> 
> I’d like to request that MAPS be converted to a private network (like the other instruments we’ve migrated) during the shutdown prior to Cycle 2018/01.
> 
> Thanks,
> 
> Kevin

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd MAPS is using ICP version `SVN R1641 (2014/04/25 13:33:09, Mixed revision WC 1577:1641, Modified)` with 5-digit run numbers. Is this ok to use with IBEX or does it need to be upgraded next shutdown?

**Comment by FreddieAkeroyd** [comment]
It will need an update, that version doesn't know about pulling log values from MySQL. 5 digit run numbers are OK and can remain.

**Comment by Tom-Willemsen** [comment]
Scripts to be migrated from maps_routines.gcl (as a result of discussion with Ross Stewart):
- set_ei_disc
- set_ei_fermi
- set_ei
- chopper_ready
- upd_uamp

All the other scripts in maps_routines.gcl are either not needed or superceded. 

I did ask about user scripts, they said their user scripts are so similar to Merlin's that they are happy to look at Merlin's for examples.

**Comment by Tom-Willemsen** [comment]
I have set up their scripts and configs on NDXTEST1 and will let Ross know that he can have a play with it whenever he likes.

Things that need doing when actually deploying to MAPS:
- In synoptic "MAPS_CCR", under the eurotherm component, change the two "Rot" PVS to point at `IN:MAPS:...` rather than `IN:TEST1:...`
- In `maps_routines.py`, on line 10 change "NDXTEST1" to "NDXMAPS"
- Change all the IOCs back to non-simulation mode (they should all already have the correct macros for running on MAPS, they have just been configured as simulation mode so that Ross can test scripts)

**Comment by Tom-Willemsen** [comment]
Impeded awaiting:
- ICP update (do during shutdown)
- Confirmation from Ross that he is happy with migrated configs and scripts (I have given him access to the test machine)
