### ISSUE TITLE
SANDALS: Sample Changer Positions

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3060]
Sylvia on SANDALS reported an issue where the sample positions seemed to not correspond to the correct motor positions based on getting unexpected readings from the samples.
This appears to have been a false alarm. Regardless, I have supplied Sylvia with the lookup table currently used in IBEX upon her request. I also told her we can set up some blocks pointing at the sample changer's linear and angular position to make these easier to track going forward.

**Comment by Tom-Willemsen** [comment]
It doesn't sound like there is anything to review for this ticket. Moving straight to review complete.
