### ISSUE TITLE
ENGINX : Positioner Error

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3066]
On ENGINX, the sample positioner is done via LabVIEW. It has been noticed during the last cycle that communication to the equipment has stopped - hence causing problems for the experiment. "NaN" is shown on the dashboard. This needs to be fixed.

Contact : Tung Lik Lee

**Comment by GDH-ISIS** [comment]
The error message for the LabVIEW Galil code issues a dialog box for when an error appears. This then stops the LabVIEW code from executing. This was observed directly on ENGINX. There is an additional error code in the logs of -1073807360 - I can not trace an explanation currently. In the past, SECI managed the error messages and a dialog box was not shown.

**Comment by ChrisM-S** [comment]
I found this after translating to Hex, not a solution though, but maybe some ideas...

[https://forums.ni.com/t5/LabVIEW/Reasons-for-Error-code-in-viWrite-0xBFFF0000/td-p/2101734](https://forums.ni.com/t5/LabVIEW/Reasons-for-Error-code-in-viWrite-0xBFFF0000/td-p/2101734)

**Comment by FreddieAkeroyd** [comment]
Is the labview using "send message to message panel.vi" ?

**Comment by KathrynBaker** [comment]
I would imagine so, that way it is captured in SECI, although that does mean a dialog box will be displayed when running outside of SECI.

**Comment by FreddieAkeroyd** [comment]
We could either:
* implement an lvDCOM interface to "send message to message panel" 
or 
* modify "send message to message panel" to detect EPICS and instead post to epics error log
I have a leaning to the latter as it is more general

**Comment by KathrynBaker** [comment]
I think the latter option is probably a good one as well, but it may be a separate ticket to this one – which relates to a specific error on a specific instrument.

**Comment by GDH-ISIS** [comment]
Sorry to push this through. This has been an issue on ENGINX recently. Reviewed independently with for SECI and IBEX. Looks fine. In SourceSafe. Put on ENGINX. Forced error message. Message appeared fine in IBEX.
