### ISSUE TITLE
Muon Front End: Set HV Setpoint for Kicker and Separator

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3073]
As a Muon scientist, I want to be able to set the HV setpoint of the Kicker and Separator remotely, to save time when tuning the beam, and to maintain the tuning more easily during a cycle.

**Acceptance Criteria**
1. There is an IOC (or two, decide when undertaking the ticket) which sets an appropriate voltage that is then interpreted by the PSU to the required value
1. There is feedback relating to the relay state which allows for the movement between remote and local mode

**Notes**
1. This will require some time working with the PLC teams to ensure that requirements and expectations are managed properly by both teams

**Comment by kjwoodsISIS** [comment]
At present, the Kicker setpoints cannot be set (there are no Analog Output signals from the NI DAQ-Mx to which the Kicker PSU is connected).  If the hardware is upgraded at some point in the future, a new ticket can be raised.

Management of Separator setpoints is now handled by #3408.

This ticket can now be closed.
