### ISSUE TITLE
Add Emulator for Oxford IPS

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3075]
The Oxford IPS requires a Lewis emulator and IOC tests

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/59
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/92

Probably worth reviewing alongside #2593 which adds the IOC itself

**Comment by AdrianPotter** [comment]
Approved. Can be merged as soon as #2593 is done
