### ISSUE TITLE
Add a flag for event mode

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3078]
As a GEM instrument scientist I would like to be certain of whether I am in event or histogram mode. It was suggested that an indicator on the dashboard would be good but it's obviously a bit cluttered. It would also be nice to have a button to easily select between event/histogram (and change the wiring tables for you)

**Comment by FreddieAkeroyd** [comment]
Event/histogram mode can be decided on a detector card by card basis, so some instruments have more than one "event mode" setup as they also have more than one "histogram mode" setup. Do GEM only plan to have two detector/wiring/spectra combination in total?

There is currently a variable "event mode fraction" that is displayed on the DAE run information, it is the fraction of detector cards running in event mode. So > 0.0 means something is running in event mode. It is not usually 1.0 as many instruments keep monitors in histogram mode when detectors are in event mode.
