### ISSUE TITLE
MySQL: can it be built statically within IBEX

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3083]
Currently MySQL is built dynamically in all circumstances, I can't remember the exact reason but probably related to it being a bit awkward with the CMake build and not being necessary at the time.   Would be useful for #2952 so should investigate again, may be worth updating MySQL connector in case more recent build system is easier.

**Comment by Tom-Willemsen** [comment]
Recent mysql binding changes mean this ticket is obsolete
