### ISSUE TITLE
Additional COM port diagnostics

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3084]
As a developer I would like even more COM port diagnostics than provided by  #2836 when I type:

    dbior "drvAsyn" 2

**Comment by FreddieAkeroyd** [comment]
Details are now provided about input buffer size and modem control line status

**Comment by DominicOram** [comment]
Ran connected to a device, additional values print and look sensible.

**Comment by DominicOram** [comment]
Is this something worth feeding back into asyn?
