### ISSUE TITLE
GEM: Extend limits on beamscraper

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3086]
As a GEM instrument scientist I would like to be able to move the jaws wider (North to 26.5 and South to -23.5) and slower (to around half speed). As a developer I would like the limits to not be hard coded so a change like this in the future only requires configuration changes.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by DominicOram** [comment]
See code changes at https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/15 and https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/85/files.  Once reviewed I will hotfix to GEM (along with the change of speed).
