### ISSUE TITLE
EUROTHERM: hang on startup

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3090]
The eurotherm on IMAT hung on startup, debugger suggests it was trying to read a value from the device but getting no reply. The read should have a 200ms timeout, but this didn't seem to be working as expected. Will check later what state eurotherm is in, but need to investigate read timeout situation.

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella can you confirm if this was fixed by a moxa reboot, computer reboot, or both. Thanks.

**Comment by John-Holt-Tessella** [comment]
Yes this was fixed by a moxa reboot.
