### ISSUE TITLE
Triton: run the IOC on the triton PCs rather than the instruments

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3091]
As a member of the cryogenics team, I would like the Triton IOC to run on the triton control PC rather than the instrument PC so that I can run diagnostics easily, without depending on which beamline the fridge is on.

Questions to be answered as part of this ticket:
- How we do the access security
- How this can work alongside the labview driver (only one driver can connect to the Triton system at any time)
- How do we configure a beamline to use a particular fridge? Who's responsibility is this?

In the first instance this ticket is probably a meeting to decide how to do this. A separate ticket can be created for the technical implementation.

**Comment by ChrisM-S** [comment]
Could we also add:

- how and when do we update the IOC and any other IBEX components installed on this PC?
- Do we do this along with IBEX releases for example?

this also has relevance to other ancillary control PCs with EPICS/IBEX components installed.

**Comment by ChrisM-S** [comment]
I will add this question as it is pertinent for issues with moving equipment living on the general network and which may be addressed from several instruments (ideally one at a time as it moves around).

Is there a way we may be able to keep PV access to the device within the same PV namespace as the parent instrument at the time? 
(This would potentially be an IBEX solution to the risk of accidental control from another instrument which has the device available in a configuration where machine names cannot change).

**Comment by FreddieAkeroyd** [comment]
Do we need to think about how we start/stop of the IOC from an IBEX client, also adding blocks (we currently write block information to MySQL on localhost, where should the triton plc write to if at all?). Will the triton have device specific PV's with instrument aliases to these? This may partly cover Chris' question if we boot with device specific PVs and then have a local aliases (via gateway or otherwise) on the triton to map these to whichever IN: prefix is required for the current experiment.

**Comment by Tom-Willemsen** [comment]
Meeting scheduled 24/4 at 13:00

**Comment by Tom-Willemsen** [comment]
Solution we discussed:
- Run the control pc as a mini-inst.
- Central services archiver needs to point to moveable PVs
- Have a PV which lives on the equipment control PC and contains the name of the instrument that is currently controlling this device.
  * This PV should only be writable from the control PC, cryogenics and us.
  * This should live in an `IOCCTRL` ioc of some description. 
  * When the PV is written to, it will restart the triton IOC with the correct configuration to make the triton publish the correct instrument-specific PVs.
- Triton IOC will live on the triton control PC and publish equipment-specific PVs such as `ME:TRITON-1:TEMPERATURE`. These will be aliased to instrument-specific PVs such as `IN:INSTRUMENT:TRITON_01:TEMPERATURE` by the gateway.
- Triton IOC on control PC will be set up to push to IOC database on instrument PC

There was some discussion about whether we should put the Triton systems onto private networks so that they can become more plug-and-play. I think the tickets to come out of this meeting (in order) are:
- Implement the system described above
- Have a meeting to discuss longer-term solutions to make the systems easier to plug-and-play. This may involve private networks.
