### ISSUE TITLE
Power Cut: Check after power cut

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3092]
Check instruments after power cut:

 - [X] HRPD
 - [X] ALF
 - [X] EMMA-A
 - [x] ENGINX
 - [x] GEM
 - [ ] IMAT
 - [x] IRIS
 - [ ] LARMOR
 - [x] MERLIN
 - [x] MUONFE
 - [X] POLARIS
 - [X] SANDALS
 - [X] VESUVIO
 - [X] ZOOM

Check choppers (are active) and motors (are not all 0)

**Comment by kjwoodsISIS** [comment]
Power cut affected only TS1.  Therefore, IMAT, LARMOR & ZOOM should be unaffected.

**Comment by Tom-Willemsen** [comment]
HRPD: MySQL service hadn't started, this made various things unhappy. It was set to autostart so not sure why it didn't start. I manually started the service and it seems ok now.

MUONFE: Galils and power supplies not talking to the hardware. I have contacted the scientists, they are aware of this and will power on their galils and PSUs later this week they have said.

VESUVIO: McLennan motor positions have been lost. I have contacted the instrument scientists to let them know they will need to be rehomed.

**Comment by AdrianPotter** [comment]
I've reverted to MK3Chopper_old on Larmor, Zoom, and HRPD for the time being to avoid the memory leak issue while we investigate.

**Comment by AdrianPotter** [comment]
ENGINX too

**Comment by AdrianPotter** [comment]
And IRIS

**Comment by DominicOram** [comment]
We are now a week into cycle, affected instruments seem to be running OK with no adverse side effects. Therefore closing this ticket.
