### ISSUE TITLE
GEM: 5-axis Goniometer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3096]
Winfried has an experiment scheduled on GEM that requires the use of the "GEM: 5-axis Goniometer".  the experiment starts on 7th May.

Curiously, the "5-axis" Goniometer has only 4 axes - x, y, z and omega.
The 5-axis Goniometer can be driven by a Galil.  We may need to create an OPI.
Alternatively, there is a LabVIEW driver.

7th May is a bank holiday, so this needs to be implemented and tested ahead of time.

**Comment by DominicOram** [comment]
Duplicat of https://github.com/ISISComputingGroup/IBEX/issues/2853
