### ISSUE TITLE
Julabo: Internal/External Sensor control

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3097]
As a sandals instrument scientist I want to be able to swap between internal and external mode and see this on the dashboard so that I can swap my julabo without having to navigate the menus.

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/ibex_gui/pull/675
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/263
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/57
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/87
- No PR for support module as it already had the relevant command

**Comment by AdrianPotter** [comment]
A few comments on the OPI style
