### ISSUE TITLE
MK3CHOPR: Fix memory leak if there is no server

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3103]
The MK3 Chopper IOC leaks memory if it can not connect to the chopper server. Find out where the problem is and fix it.

Needed for cycle if possible.

**Comment by FreddieAkeroyd** [comment]
If you can't find it quickly, the other option is to terminate the process, procServ will then restart it.

**Comment by John-Holt-Tessella** [comment]
Is it possible to limit the memory use of a process in procServ so that it will reboot when it runs away. If it is, is it something we shoud do for all processes?

With regards to this specific IOC I think I have found the problem and fixed it. Not in time for cycle but we have gone back to the previous version of the driver which does not leak memory; this version will not reconnect if the network drops.

**Comment by John-Holt-Tessella** [comment]
The new version will do both but it won't be ready for cycle (i.e. yesterday so it could be built and installed).

**Comment by kjwoodsISIS** [comment]
Excellent.  Thanks for the clarification.  We can make the new version available in the next release (which, as you say, won't be available for Cycle 2018a).

**Comment by John-Holt-Tessella** [comment]
Pull request:

https://github.com/ISISComputingGroup/EPICS-mk3chopper/pull/4
