### ISSUE TITLE
LARMOR: Couette Cell

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3105]
As a scientist, I wish to control a Couette cell, so that I can perform shear flow experiments.  The first experiment that requires this equipment is scheduled for Cycle 2018a (17 April - 18 May).  The experiment will be performed on 6-8 May 2018.

#### Acceptance Criteria
1. I can control the  Couette Cell via IBEX
1. IBEX provides an OPI similar to the existing LabVIEW VI

#### Notes
1. The Couette cell is described here: https://www.isis.stfc.ac.uk/Pages/Unilever-Extensional-Shear-Cell.aspx
   * The description implies that there is a heating capability.  How is this controlled?
1. The Couette Cell was originally driven by a McLennan PM341.  It is now driven by a [McLennan PM1000](https://www.mclennan.co.uk/product/pm1000-motion-controller) system ([compatible](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Motion%20Control/McLennan/pm1000-motion-controller-datasheet.pdf) with a PM600).
1. LabVIEW VIs are here:
   * McLennan PM341: C:\LabVIEW Modules\Instruments\LOQ\LOQ Couette Cell\LOQ - Couette Cell.llb\LOQ - Couette Cell - Front Panel.vi
   * McLennan PM600: C:\LabVIEW Modules\Instruments\LOQ\LOQ Couette Cell\LOQ - Couette Cell - PM600.llb\LOQ - Couette Cell - PM600 - Front Panel.vi

**Comment by kjwoodsISIS** [comment]
Background e-mail:

> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 12 April 2018 00:44
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Akeroyd, Freddie (STFC,RAL,ISIS); Dalgliesh, Robert (STFC,RAL,ISIS); Nutter, Jamie (STFC,RAL,ISIS) 
> Subject: LARMOR : Couette Cell
> 
> Dear Kevin and Freddie,
> 
> There is some old experimental equipment called a Couette cell that was originally to be used on LOQ/SANS2D. However, it has now been recently allocated to LARMOR. It is based on a motion controller Mclennan PM341 or a Mclennen PM600 control crate. The LabVIEW driver is located at :
> 
> Mclennan PM341
C:\LabVIEW Modules\Instruments\LOQ\LOQ Couette Cell\LOQ - Couette Cell.llb\LOQ - Couette Cell - Front Panel.vi
> 
> Mclennan PM600
C:\LabVIEW Modules\Instruments\LOQ\LOQ Couette Cell\LOQ - Couette Cell - PM600.llb\LOQ - Couette Cell - PM600 - Front Panel.vi
> 
> The original control crate was a Mclennan PM341. However, the sample environment group decided that, as the original crate was old, it would be better to transfer it to a newer PM1000 controller (compatible with a PM600). I therefore converted the vi to a new vi to use the newer crate – hence the two vis shown above. Both crates look operational.
> 
> This experiment is now to be done on LARMOR – the equipment was moved to LARMOR earlier today for a trial fit. I demonstrated the equipment to Rob Dalgliesh today – along with Jamie Nutter to resolve a last minute top speed issue. Both Mclennan crates are connected and configured to COM52 with LabVIEW.
> 
> I thought that people were aware of this, but in going through the email trail this evening, I did not notice LARMOR and IBEX formally mentioned – hence the email. I believe it is expected for this cycle – early May – Rob implied the bank holiday weekend.
> 
> Regards,
> 
> Gareth

**Comment by kjwoodsISIS** [comment]
Rob suggests using lvDCOM for this:

> From: Dalgliesh, Robert (STFC,RAL,ISIS) 
> Sent: 12 April 2018 13:44
> To: Woods, Kevin (Tessella,RAL,ISIS); Howells, Gareth (STFC,RAL,ISIS) 
Cc: Akeroyd, Freddie (STFC,RAL,ISIS); Nutter, Jamie (STFC,RAL,ISIS)
Subject: RE: LARMOR : Couette Cell
>
>HI Kevin,
> Yes that’s the one.
> Unfortunately there is a bit more to do than just the mclennan controller.
> There is another Vi that sits above this to give experimentally relevant information.
> 
> I suspect it will be easier to go down the route of an IOC to talk to the appropriate Vi at this point.
> 
> We also know the that the Vi is working fine.
> 
> Rob

**Comment by John-Holt-Tessella** [comment]
Release Plan:

1. Build 3.4.3 release of EPICS with Couettes cell in
1. Copy IOC directory from release to Larmor
1. Copy Lab view VIs to Larmor:
    1. Couettes cell vi and associated ` LOQ - Couette Cell - PM600.llb`
    1. Mclennan PM600 vis
    1. New caputure message box vi
1. Run `%PYTHON% build_ioc_startups.py`
1. Setup component with it in (I would set LVDCom Options to 6)

Test the plan on demo
- [ ] Tested on Demo (record who you are)

**Comment by John-Holt-Tessella** [comment]
Code is merged do release plan and then for real on Larmor
