### ISSUE TITLE
Modify labview error handling to post to IBEX as well as SECI

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3108]
Change "send message to message panel" so it will send to ibex rather than create a modal dialogue box, this will fix issue #3066

**Comment by FreddieAkeroyd** [comment]
Version pushed to SourceSafe for testing

**Comment by FreddieAkeroyd** [comment]
@GDH-ISIS can you check this

**Comment by GDH-ISIS** [comment]
Checked. Reviewed. Completed. Put on ENGINX as it is needed for the sample positioner.
