### ISSUE TITLE
CRISP: ethernet Galils

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3109]
As an instrument scientists I would like to use CRISP for testing IBEX and so need the Galils available via ethernet

Once confirmed set up a configuration with them in.

**Comment by FreddieAkeroyd** [comment]
I think CRISP once ran Galils on Ethernet, so there might be something left over from that, but I don't expect it will have a VLAN set up for example.

**Comment by GDH-ISIS** [comment]
Legacy : CRISP did once have Galils on a private network when I first put the system together. This was because many commands were sent to the Galils and this affected the system response. i.e. pre data record. As things improved i.e. the data record was implemented, they were converted to MOXA units and the network was removed.

**Comment by GDH-ISIS** [comment]
CRISP Galil units are now cabled and connected direct to the ndh\ndx on a private network.
Standard addressing for the units has been used.
I have confirmed with Anthony that CRISP has no VLAN currently. I will create another ticket to get the VLAN organised.
Nothing regarding IBEX has currently been done. Network all confirmed using the LabVIEW code.
No IBEX configuration currently set up. 
LabVIEW Galil driver updated. As part of this, the LabVIEW EPICS conversion tool is included (it sets the HOMEVAL to zero and the OFF to the home position).

**Comment by GDH-ISIS** [comment]
CRISP Galil units are now available on a private network via a VLAN setup on the instrument switch.

**Comment by kjwoodsISIS** [comment]
Is there any more work to do on this ticket?  Can it be moved to review? (which I hope will be rapid).

**Comment by John-Holt-Tessella** [comment]
Yes just need to create some configurations with Galils with the correct address in.

**Comment by kjwoodsISIS** [comment]
I am guessing this ticket can now be closed?  Is that true?
