### ISSUE TITLE
Update "send message to message panel" on IBEX instruments

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3111]
When we are happy with #3108 being used on ENGINX (for #3066) we should deploy it to other IBEX instruments as they might too run a labview Vi in future that does something similar

In SourceSafe the file concerned is "Send message to Message Panel (and wait for response).vi" and is located in c:\labview modules\common.

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd or @GDH-ISIS  can we do rhis as a release task?

**Comment by John-Holt-Tessella** [comment]
No longer doing this because no longer visiting all machines.
