### ISSUE TITLE
Galil: IMAT galil with encoder does not reverse

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3112]
Went to IMAT all axes will not reverse can only move forward. When requested to move backwards you here the motor energise but there is no movement. SW_LIM is reported in the log file.

Steps to reproduce:
1. Ensure controller has Encoder is Yes
1. Turn off IOC
1. Power cycle controller
1. Turn on IOC
1. Stack now refuses to go backwards.
1. Turn encoder off then on again
1. Motor now acts as expected.

We have done the above and said if the Galil power cycles to increase the limits to be very large (this also appears to fix it).

Acceptance:

Galil can be power cycled and moved afterwards and movement respects limits.

**Comment by John-Holt-Tessella** [comment]
Things we looked at:

1. Limits appear to be correct in the galil using `FLF=?` and `BLF=?`
1. `CE` doe not change and channing it doesn't appear to effect anything
1. Occasionally (not every time) switching the encoder on made the motor move
1. Setting `uiepF=1` did nothing but this may be because it didn't poll
1. We did *not* look at the asyn output when encoder was switched on.
1. When moving to the limit the exact position was off by more than the motor resolution
1. We saw the setpoint change to reflect the new position.

**Comment by John-Holt-Tessella** [comment]
Final instructions to IMAT scientists if they have a problem set the limits to be large on all axes so they can move their motors.

**Comment by kjwoodsISIS** [comment]
I can't help asking myself "what changed (between 16th April and the previous week (or whenever it last worked successfully))?"  Did something change in the software or in the hardware?

**Comment by John-Holt-Tessella** [comment]
OK this is too hard to reproduce without an axis to play with. 

Impeded until the next shutdown.

**Comment by FreddieAkeroyd** [comment]
I think this is now being covered as part of #2947

**Comment by John-Holt-Tessella** [comment]
Yes once we have fix for this can we test it on IMAT please

**Comment by John-Holt-Tessella** [comment]
Fixed.
