### ISSUE TITLE
Improve messages for simple console errors

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3113]
As an instrument user and not a specialist programmer, if I miss-type a command at the IBEX console, the error message is truly frightening and colourful and not helpful.  I would prefer a simple message which would suggest a few things which might help me more and avoid me having to call for help.  For example.

`>>> Unknown command, please check the spelling or see if you need to prefix with “inst.” or “g.”`

Can we add a general handler at the command line to catch this and other simple errors?

**Comment by Tom-Willemsen** [comment]
This currently gives something like

```
NameError: name 'foobar' is not defined
```

That error seems both _reasonably_ clear, and very easy to put into google/chatgpt for an explanation for anyone who doesn't understand it (being a completely standard python error). I fear a custom handler would end up being less searchable - and therefore less helpful.

---

As I've not heard this requested much/at all by scientists/users I'm going to tentatively close this, but feel free to re-open @ChrisM-S if you feel strongly about it.
