### ISSUE TITLE
IBEX Client : Extended Block Information in Dashboard

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3115]
As a developer and user of an IBEX control system, would it please be possible to extend the block information shown in the dashboard tip strip to include the PV that a block is associated with as well as the configuration/component in which it has been configured (as well as the edit mouse button). This will help in understanding which configurations/components to edit when they are not correct. Also, for those blocks that have run control enabled, could we display the run control values as a tip strip on the dashboard.

**Comment by KathrynBaker** [comment]
It may not be direct but most of this is now covered - can edit the host configuration of a block via a right click, access the run control settings through a right click, the PV is shown in the tooltip. Closing.
