### ISSUE TITLE
IBEX Training: 23rd May 2018

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3116]
As an instrument scientist, I would like another Introduction to IBEX and genie_python with IBEX training course so that 
1. I can learn how to use IBEX
1. I can support visiting scientists
As an IBEX developer, I would like another instrument scientists to receive training in IBEX so that they can use IBEX with minimal support from me.

The next training courses are scheduled for the 23rd May 2018.

#### Acceptance Criteria
- [x] Advertise training
- [x] Book venue
   - [x] CDF room in Atlas Centre has been booked
- [x] Assign trainers
- [x] Review course materials
- [x] Send delegate list to CDF
- [x] Send joining instructions to delegates
- [x] Book tea, coffee ~and lunch~ as necessary
- [x] Set up machines
- [x] Deliver training
- [x] Apply retrospective changes to process/wiki/slides

#### Notes
1. Additional instructions for setting up training can be found here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
1. The courses are scheduled as follows:
   - 23rd May 2018 (AM): Introduction to IBEX
   - 23rd May 2018 (PM): genie_python with IBEX
These are two separate courses.  Delegates will be expected to purchase their own lunch.

**Comment by AdrianPotter** [comment]
All of the retrospective corrections have been either applied or ticketed. There is one PR associated with the changes for a minor change to the Eurotherm OPI. The tickets associated with the training are:

#3217
#3216
#3215
#3205
#3204
#3203
