### ISSUE TITLE
axisRecord does not include inMotion and allStop additions

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3121]
The axisRecord (motor record replacement) uses axisUtil.db rather than motorUtil.db and consequently does not load our additions for allStop and inMotion. Only the Beckhoff uses axisRecord / axisUtil and so the issue will only be present on IMAT.

**Comment by FreddieAkeroyd** [comment]
To test:
* copy updated axisUtil.db to support/axisRecord/master/db on NDXIMAT
* restart the BKHOFF_01 IOC
* check ioc log for any errors in loading axisUtil.db
* move Z or LargeRot blocks, the "Motor Are Moving" client indicator should work
* start a large move and check the "stop all" button in the client works

**Comment by John-Holt-Tessella** [comment]
Can I review this since I put it on IMAT
