### ISSUE TITLE
GUI: Beam status stops responding

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3122]
On SANDALS the beam status graphs stopped updating sensibly. So it appeared to be showing the latest time date on the axis but the data was not updating. In addition clicking on the last hour/last24 hour radio buttons did nothing. 
User was mid setup so couldn't explore more. I suggest leaving the client open for an extended period.

**Comment by John-Holt-Tessella** [comment]
Starting a new client showed a working beam status.

**Comment by AdrianPotter** [comment]
There's an outside chance this might have been fixed by the recent changes to the observable stack as part of #2306. If you can reproduce with version 4.3.2, test with the upcoming version (presumably 4.4) to see if the problem goes away.

**Comment by Rory-Potter-Tessella** [comment]
IRIS and VESUVIO reported that the Beam Status view did not live update at their instrument demo (2018-11-22)

**Comment by John-Holt-Tessella** [comment]
See #3856

**Comment by kjwoodsISIS** [comment]
either make an opi or web browser onto mcr screen (prefer opi)

**Comment by Tom-Willemsen** [comment]
Re-requested by HRPD/IMAT/ENGIN-X in their demo meeting

**Comment by KathrynBaker** [comment]
Not aware of any re-reports in the last 6 years, closing
