### ISSUE TITLE
SANDALS: Fix title in script

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3123]
As an instrument scientist I do not want my users worrying about the title of the data being set incorrectly. On larger runs using the sample_changer_scloop The title printed on the second sample is the one from the previous sample and similarly for all other samples.

**Comment by kjwoodsISIS** [comment]
If the problem is that the script running ahead of the end of the previous run, would it be better to use a `g.waitfor_endofrun()` command, or similar? - assuming that there is such a command (I would have checked the genie_python reference first, but it is broken at the moment!)

**Comment by John-Holt-Tessella** [comment]
No, I think this is better because they can get on with the next run without having to wait.
