### ISSUE TITLE
IMAT: disconnected blocks and gateway crash

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3124]
The monitor blocks on IMAT are becoming disconnected and if an external client is viewing this causes a

[Mon Apr 23 12:01:21 2018] Apr 23 12:01:21 Warning: Virtual circuit unresponsive NDXIMAT:51083 
[Mon Apr 23 12:01:21 2018] Apr 23 12:01:21 PV Gateway Aborting (SIGSEGV)

crash of the external gateway. Attaching a debugger suggested the gateway was trying to copy memory from an area it could not read. The blocks dropping out may be #2971 which IMAT doesn't have the fix for, the gateway crash is just a symptom of the disconnection. IMAT ended a run at 11:30 and had been idle in setup since then, so the disconnected blocks is not obviously due to load on the DAE.

Will try and install a debug gateway build to check that side, also test on DEMO.

**Comment by FreddieAkeroyd** [comment]
Forgot to add, I believe we only see this on IMAT as they have blocks pointing at their summed monitor counts which nobody else does.

**Comment by KathrynBaker** [comment]
Given the age of this ticket I doubt it is still in place, please reopen if this should still be done.
