### ISSUE TITLE
NICOS: Syntax highlighting and code completion

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3128]
As a user I would like syntax highlighting wherever I have to read python code in the NICOS view and code completion wherever I have to write code.

**Comment by DominicOram** [comment]
I spent some time looking at using pydev for this (which I think we should do to save us reinventing the wheel). Unfortunately the only thing I can get out of pydev is a whole EditorPart as opposed to a single widget. We could try and import the whole editor part into our NICOS view (maybe in a similar way to the databrowser) or we could keep digging into pydev to see if we can reuse some of their underlying code complete/highlighting logic.

**Comment by DominicOram** [comment]
Rob would also like to be able to collapse loops

**Comment by Tom-Willemsen** [comment]
I think this is highly unlikely to get done in the current iteration of the GUI. Technology choices for new gui may obviate the need for this ticket (e.g. if we go towards something like jupyter then we'd get this for free).
