### ISSUE TITLE
E4: Prettify the data browser widget in the stress rig OPI

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3136]
As an instrument scientist using the Instron Stress Rig, when I migrate to E4 I would like the stress rig OPI to maintain its aesthetic quality. In particular, the amount of space dedicated to the graph in the widget should be roughly maintained so that the data is presented in a readable way.

In the latest version of CSS, the data browser widget has been updated such that the amount of space that is left blank or is taken up by labels/legends/toolbars. This reduces the dramatically the amount of space for data.

Please update the *.plt files for the widgets so they're presented in a suitably user-friendly way.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/747
