### ISSUE TITLE
JAWS: propagate low level motor setpoint to upper level

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3138]
As a user I would like the top level jaws GUI to always reflect the motor setpoints on the low level, they are currently synchronised on startup but not subsequently. The low level screen is not used often directly, but this would avoid problems when it is. The top level jaws GUI works fine is updating other parameters.

Acceptance criteria:
 setting a setpoint on the low level motor screen is reflected in the appropriate jaws N/S/E/W setpoint

**Comment by GDH-ISIS** [comment]
There is a high probability that this has all been done before - Diamond has jaw sets I believe. May I ask whether we should be using the same approach as these other facilities?

**Comment by FreddieAkeroyd** [comment]
When we talked to Diamond, they were doing all their jaws logic in the controller and did not use Db files, they had used Db in the past but found it didn't scan the centre smoothly enough for example. Our jaws Db files are based on the EPICS optics module, so is using the same approach as other facilities if not exactly the same.

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella yes it is the same approach as in labview.

**Comment by FreddieAkeroyd** [comment]
@GDH-ISIS I believe Diamond do have terms like N, S, E, W, Hgap, Vgap, Hcentre and Vcentre, but when they, for example, set a PV called Hgap it interacts with a virtual axis defined within the delta tau controller itself that moves the two relevant motors (i.e. the DB file does not calculate and send E and W positions). I think this makes keeping things in sync easier for them as at the DB level it is all 1:1
