### ISSUE TITLE
Check flow control settings on IOCs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3139]
There have been a couple of moxa hangs recently that may be related to flow control settings. We should check that these are appropriate for all IOCs that we have.

A grep of out repositories returned the following:

## Software flow control enabled, hardware flow control disabled

- [x] CONEXAGP
    - Adrian: I cannot find any VI or communication settings for RS232/serial in any manual online. The closest I can find is [here](https://www.newport.com/medias/sys_master/images/images/h80/h9e/9024862158878/CONEX-AGP-Controller-Documentation.pdf). The USB comm settings are the same as in the `st.cmd` except for the baud rate which I have confirmed with Rob is correctly half that of USB using the real device
- [x] KEPCO
    - Adrian: Matched against VI
- [x] MCLEN
- [x] PIMOT
    - Adrian: Also made some improvements to the `st.cmd`, and standardised the port names. There will be a PR for the upgrade step too.
- [x] SCHNDR
    - Adrian: No change but I did tidy the 02 IOC up a bit while I was there
- [x] SMC100
    - Adrian: Verified with [manual](https://www.newport.com/medias/sys_master/images/images/h8d/h3a/8797263101982/SMC100CC-SMC100PP-User-Manual.pdf)

## software flow control disabled, hardware flow control disabled

- [X] GAMRY
    - Adrian: As commented below, there is no manual or VI to refer to. There is no explicit record of the flow control settings, they were either assumed or communicated verbally to @FreddieAkeroyd 
- [X] LINMOT
    - Adrian: Verified against manual and VI
- [X] SM300
    - Adrian: Matches VI. There were some macros defined in the config that were unused. ~I've made the terminators configurable to allow future support of the SM300-5 listed on @KathrynBaker's spreadsheet~ not added termination characters set in driver
- [X] TDK_LAMBDA_GENESYS
    - Adrian: Verified with [manual](https://uk.tdk-lambda.com/KB/GenesysTM-Half-Rack-User-Manual.pdf)

This ticket is to explicitly check the above and correct them if needed. All IOC are to be done as part of another ticket.

**Comment by FreddieAkeroyd** [comment]
The above are devices where a choice has been made, some IOCs do not specify a preference in the st.cmd but probably should in case they inherit an inappropriate previous value.

**Comment by FreddieAkeroyd** [comment]
MCLEN updated, fix in #3140

**Comment by KathrynBaker** [comment]
Here are the settings I could find in the LabVIEW for the named devices (hopefully the spreadsheet is attached). Whilst you’re in the settings for these, do check on the other comms settings, where they might be different, and especially where they are variable.

**Comment by KathrynBaker** [comment]
[Serial settings.xlsx](https://github.com/ISISComputingGroup/IBEX/files/1955741/Serial.settings.xlsx)

So the email didn't add it - do so manually.

**Comment by AdrianPotter** [comment]
The only device I haven't been able to verify is the Gamry Potentiostat. I can't find any existing VI, or a manual with a reference to flow control. @John-Holt-Tessella, as the developer can you tell me where the information came from. Alternatively @FreddieAkeroyd, you provided a lot of info on the original ticket, do you know? Otherwise I suspect from the ticket Matt North might be the one to talk to?

**Comment by AdrianPotter** [comment]
Impeding until I can follow up. Expected Monday

**Comment by AdrianPotter** [comment]
@John-Holt-Tessella didn't know. @FreddieAkeroyd?

**Comment by FreddieAkeroyd** [comment]
The Gamry is controlled by a new locally produced piece of hardware, there is no manual or LabVIEW VI, I had all the command details in an email from Winfried when I wrote the IOC. The email didn't mention flow control, so either I guessed "none" (which is usually the case) or I had it confirmed verbally.

**Comment by AdrianPotter** [comment]
Ok, I'll add that information to the `st.cmd` and move the ticket to review.
