### ISSUE TITLE
CCD100: Tidy Up

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3142]
As a user of the CCD100 there are a number of issues that I would like resolved:
* The reading has no equivalent SP for when I put a block on it (however READING:SP makes no sense for a PV name so you may need to change the READING PV which will require modifying configs on some instruments)
* On IOC start the IOC sets 0 to the device, it should instead set the last SP or set nothing at all
* The label on the OPI reads flow but the IOC refers to pressure, the CCD can in fact measure both.
* When no setpoint is given to the IOC it produces a number of logs

**Comment by kjwoodsISIS** [comment]
@DominicOram - you say the CCD can measure both pressure & flow.  Does it measure both simultaneously, or is it a matter of interpreting the signal via an appropriate calibration file?

**Comment by DominicOram** [comment]
@kjwoodsISIS All we get from the device is a value reading and a units string (which is set into the device manually by another group), the calibration is done internally to the device so we do not have a calibration file. In this way I suspect you could read whatever you like with it (like a eurotherm) but at ISIS we mainly use it to measure pressure/flow. The easiest thing to do would be change the IOC description to cover both pressure/flow and the OPI to not mention either as it already has a user set label and units.

**Comment by Tom-Willemsen** [comment]
Points 1, 2 and 4 are covered by the pull requests in https://github.com/ISISComputingGroup/IBEX/issues/2916

Point 3 is covered by https://github.com/ISISComputingGroup/ibex_gui/pull/686

**Comment by kjwoodsISIS** [comment]
How many points for this ticket?
