### ISSUE TITLE
GEM: 20Gb archive database

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3144]
- Figure out why it is logging so much
- Stop it from logging such a huge amount
- Recover the space that it has used so that GEM gets back a reasonable amount of free space

**Comment by Tom-Willemsen** [comment]
Something to do with MDEL on the jaws records being set to -1.

This is sensible:
```
C:\Instrument\Apps\EPICS\utils>caget IN:GEM:MOT:JAWS6:CAL_N.MDEL
IN:GEM:MOT:JAWS6:CAL_N.MDEL    0
```

This is not:
```
C:\Instrument\Apps\EPICS\utils>caget IN:GEM:MOT:JAWS6:JN.MDEL
IN:GEM:MOT:JAWS6:JN.MDEL       -1
```

I'm not sure why it is being set to -1 (there is logic to set it to propagate the value from the underlying axis so it should be being set to zero). Look at this on GEM on the maintenance day. I will put a task into the task list.

**Comment by FreddieAkeroyd** [comment]
I noticed the -1 MDEL last Friday and @DominicOram was looking at it, it is only causing an issue due to  #3137 meaning MDEL is being used for archiving rather than ADEL

**Comment by DominicOram** [comment]
I corrected the underlying motor on Friday, I forgot that without a restart the correction would not propagate to the jaw motors. It's safe to remove change it to 0 if this has not already been done.

**Comment by Tom-Willemsen** [comment]
I've emailed the GEM scientists, we can go onto NDXGEM late morning tomorrow to trim the database.

> I would guess that sometime in the late morning would be best – this gives the previous users time to finish off their experiment beforehand and plenty of time in the afternoon to set up things for the next user…

**Comment by Tom-Willemsen** [comment]
Tried to do a `DELETE FROM` but query took a very long time and eventually ran out of memory, so I did a backup+truncate instead.

GEM now has 24Gb free space.
