### ISSUE TITLE
IMAT : Virtual Circuit Unresponsive

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3145]
On Sunday 29/04/2018, 08:30 IMAT called with a script that was not executing correctly - appeared to have stalled around 07:40. Python window showed errors of the form : 
[Sun Apr 29 07:40:55 2018] Apr 29 07:40:55 Warning: Virtual circuit unresponsive NDXIMAT:51083

Issue started : 07:40. Restarted script at : 08:55. Client not restarted. IBEX ioc etc not restarted. Run continued i.e. no end of run. It looks as though maybe no image was received from the camera. Files copied from Messina camera imply that images stopped being taken around this time. Once restarted, image number was reset to back to zero I believe - luckily the files went into a different directory and were saved but with the incorrect index.

File references of interest : 
inst :: \Instrument\Var\logs\gateway\blockserver\GWBLOCK-20180429.log
inst :: \Instrument\Var\logs\gateway\external\GWEXT-20180429.log
inst :: \Instrument\Var\logs\genie_python\genie-2018-04-29-Sun.log
inst :: \Instrument\Var\logs\conserver\consoles-20180409.log
archive :: \NDXIMAT\user\scripts\IMAT_CMOS_Zyla_library.py
archive :: \NDXIMAT\user\scripts\CMOS_Tomo_sal12.py
camera PC :: \c$\Data\copy-messina-9.log

**Comment by FreddieAkeroyd** [comment]
This may be related to #3124 - I see the external gateway crashed in the same way. I could cause that  problem by just connecting an IBEX client on an outside computer to IMAT, it looks to be the monitor count blocks that are causing an issue. Connecting a debugger to the gateway did not help as it was compile in release mode, I was going to substitute a debug build gateway in maintenance day.

**Comment by KathrynBaker** [comment]
This was 6 years ago for a typical kind of error. Closing and new instances can be created new,
