### ISSUE TITLE
E4: Add alerts to the perspective switcher

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3153]
In E3, I was alerted when there were alarms or IOC log messages that required my attention. As an instrument scientist, I would like similar functionality to be available in E4 so that I can see when there is something that needs my attention.

As an implementation note, the E4 perspective switcher is very different from E3. I don't know how hard it will be to get the same behaviour. We may have to consider a different alert mechanism if it proves to be unfeasible

**Comment by John-Holt-Tessella** [comment]
Just do for Alarms we are not sure we want this for IOC logs

**Comment by AdrianPotter** [comment]
I've made a start on this here:

https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3153_Add_alerts_to_the_perspective_switcher

Notably it will also fix #3156. I haven't finished the databinding so the updates to the GUI aren't currently working properly. Notably it's also missing javadocs. There was also some issue with the CLabels in E4 in that the mouseOver event isn't always being triggered, meaning the highlighting on the buttons wasn't as responsive as it should be.

**Comment by jeremyspencer39171** [comment]
This pull request: https://github.com/ISISComputingGroup/ibex_gui/pull/708
Addresses both this ticket and: https://github.com/ISISComputingGroup/IBEX/issues/3156
