### ISSUE TITLE
Release: Do deployment

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3155]
As an instrument scientist I want the latest version of IBEX installed so I have access to all the newest shiniest features.

Acceptance Criteria

Upgraded and installed on (first box is started, second is done):

- ALF
    - [X] Started
    - [x] Done
- ENGINX
    - [X] Started
    - [X] Done
- EMMA
    - [X] Started
    - [X] Done
- GEM
    - [X] Started
    - [X] Done
- HRPD
    - [X] Started
    - [X] Done
- IMAT
    - [X] Started
    - [X] Done
- IRIS
    - [X] Started
    - [X] Done
- LARMOR
    - [x] Started
    - [X] Done
- MAPS
    - [X] Started
    - [X] Done
- MERLIN
    - [X] Started
    - [X] Done
- MUONFE
    - [X] Started
    - [X] Done
   - **Note:** Please consult with Kathryn before deploying to MUONFE as there is testing ongoing
- POLARIS
    - [X] Started
    - [X] Done
      - **Note:** Consult with instrument scientists before deploying to POLARIS (they need to cool a sample for ~1 month).  May need to postpone deployment until after end of Cycle 2018/01.
- RIKENFE
    - [X] Started
    - [X] Done
- SANDALS
    - [X] Started
    - [X] Done
- SELAB 
    - [x] Started
    - [x] Done
- VESUVIO
    - [X] Started
    - [X] Done
- ZOOM
    - [X] Started
    - [X] Done

"mini" hybrid instruments: not updating this time

- ~HIFI_CRYOMAG~
- ~SANS2D~
- ~LET~
- ~MUSR~

**Comment by RichardTysonIsis** [comment]
This seems fine, the only thing was that DEMO is running version 4.4.1 but the IBEX wiki said 4.4.0 so I changed that.
