### ISSUE TITLE
E4: Improve perspective switcher aesthetics

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3156]
The perspective switcher in E4 is functional but doesn't look as good as in E3. As a user, I would like the switcher to look better as:

- the aesthetics give me confidence in the overall product
- the current buttons also don't have clearly marked boundaries, making it harder to identify where to click
- the active perspective isn't indicated in any way
- the reset perspective button isn't segregated from the other perspective buttons which is counter-intuitive given it has a very different function (put at top)

**Comment by AdrianPotter** [comment]
This is likely to be largely addressed by #3153

**Comment by jeremyspencer39171** [comment]
This pull request: https://github.com/ISISComputingGroup/ibex_gui/pull/708
Addresses both this ticket and: https://github.com/ISISComputingGroup/IBEX/issues/3153
