### ISSUE TITLE
Beckhoff: build emulator

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3162]
The beckhoff comes with a basic emulator - get it working on windows

To test:

* Run doit.bat in simulator directory from an epics terminal
* Tell beckhoff IOC to connect to HOST   127.0.0.1:5024

**Comment by Rory-Potter-Tessella** [comment]
The emulator compiles on windows and communicates with the Beckhoff IOC on 127.0.0.1:5024.

The simulator does appear to set the High and low limit values of the second motor (Z-axis) to be really small and different from the settings in the Axis record.
