### ISSUE TITLE
ZOOM:issue with SPS Y axis

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3164]
The ZOOM SPS Y axis (MTR0402) is giving problems when driven in a negative direction, it starts to move and then stops, and then retries kick in. It doesn't look to have "stalled" in that the log has no stall messages, it more looks like the move just terminated early without error and then the motor record higher layer noticed it hadn't reached the requested setpoint and so begins retries. The retries all result in "begin failure" messages, but no further error messages.

Ian Johnson has been taking a look and has some further information

**Comment by IainJohnson** [comment]
Hello, when changing direction the Retries rack up to 11 and gives up before the motor has chance to travel through the backlash. Visually the motor shaft pulses 11 times without going very far. De-energised, the axis can be moved both ways by hand, so I don't believe this is a loading issue.
EPICS Backlash distance needs to be set slightly larger than the measured amount,
And / Or
The Position/Following Error value needs to be slightly bigger than the mechanical backlash distance.
(It might be useful to empirically find the backlash value by trial and error to help with the above numbers. - a quick twist of the motor today reveals about 20 degrees of motor rotation before the gears wind-up and the encoder moves )
The Retries happen in rapid succession, so It may also help to delay the energise -> move to give the amplifier chance to energise and stablise.

Best regards, Iain Johnson
Operations EEUSG
IDD TIM

**Comment by FreddieAkeroyd** [comment]
Hi Ian,

there is a PV   MTR0402_ONDELAY_SP    for the power on delay, how long do you think is reasonable to set it to?

MTR0402.BDST is currently 0 - do you know what 20degrees might equate to?

Thanks,

Freddie

**Comment by FreddieAkeroyd** [comment]
I should implement #2947

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by FreddieAkeroyd** [comment]
I've put 0.5 which assumes it is just setting BDST, but if that doesn't work we may need a further ticket. I've also moved to awaiting after talking to Steve Cox, they will get us a value for BDST but it may need to wait until shutdown. I'll push through #2947 to improve diagnostics.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - is this ticket still impeded?  If so, what is preventing us from making progress?

**Comment by IainJohnson** [comment]
Hi @FreddieAkeroyd

This problem turned out to be a combination of 1) stalling due to the speed contraints of the mechanics and setup and 2) stalling caused the motor and encoder counters to become way out of sync, then the Galil prevented motion past the soft limit.

1) has been solved by fitting a more favourable ratio gearbox and reducing the microstepping value
2) I think you had a look at a feature to re-sync motor and encoder to prevent hitting a phantom soft limit?

I have not had any calls to Zoom SPS Y since re-commissioning, and I spoke to the scientists the other day, they are very pleased with the Y motion and faster sample changes.

Cheers, Iain

**Comment by FreddieAkeroyd** [comment]
Hi @IainJohnson  thanks for the update.  The auto resync of encoder and motor position is indeed enabled on that axis, i haven't looked at the logs to see how often it might have kicked in, but thank you for fixing (1) above

Freddie

**Comment by GRyall** [comment]
The problem was resolved. Closing ticket.
