### ISSUE TITLE
IOC: Set eurotherm calibration file in configuration

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3165]
As a Sandals instrument scientist I want to be a able to use a macro in my configuration to set the calibration file, so that my two configurations use the correct sensor calibration file and I don't have to remember which file to use when I swap calibrations.

Acceptance criteria

1. Setting a macro sets the calibration file to use
1. If a macro is set then the field is not restored from autosave and is not saved to autosave
1. If the macro is blank then the autosave value is used

Ask? What happens if no file is set? Do we really need a macro, can it just be PV sets?

**Comment by John-Holt-Tessella** [comment]
Bumped into Sabrina today she said she is happy for it to be added to a config as a PV value and then see if this is ok to use.

We should do this because it is super quick. I will arrange a time to do this.

**Comment by John-Holt-Tessella** [comment]
Set but resulted in a bug #3342

**Comment by Tom-Willemsen** [comment]
New ticket is created as appropriate and can be re-estimated (and re-prioritised) at that point. This ticket can be considered complete.
