### ISSUE TITLE
GEM oscillating radial collimator not responding

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3167]
We received a support call from Ivan on GEM. The oscillating radial collimator had stopped responding. On investigation, the VI and OPI responded equally so a hardware fault was suspected.

On visiting the instrument, with help from Graham Burgess, we power cycled the hardware. This requires physically unplugging the power cable at the back of the controller as the power switch doesn't completely turn it off. This fully reset the hardware and normal operation resumed. We also added a block for the number of cycles to make it easier to see when the hardware stops responding in the future.

Also while we were there, they started their Mercury cryostat. The data from the device didn't appear on the OPI and required manually starting the VI. From the `st*.cmd` files, it appears the appropriate option flags aren't sent to start the necessary VIs.

For this ticket:

- [x] Record the information above on the instrument's wiki page
- [x] Fix the Mercury startup files
- ~Hotfix to GEM~
- [x] Add shutdown task to update GEM
- [x] Make sure the hotfix is recorded in the wiki

**Comment by kjwoodsISIS** [comment]
You say "From the st*.cmd files, it appears the appropriate option flags aren't sent to start the necessary VIs.".  Does this imply that there ought to have been a check that the correct option flags are set?  Should we update the relevant documentation to make sure that such a check is explicitly performed?

**Comment by AdrianPotter** [comment]
Yes, it's interesting that wasn't caught in testing. I'll try and determine the root cause and update the documentation for LvDCOM IOCs if necessary.

**Comment by FreddieAkeroyd** [comment]
Maybe it was tested without the hardware being present, which is why autostart got missed?

**Comment by AdrianPotter** [comment]
I will create a ticket for the hotfix and add to shutdown tasks. Ivan said they're unlikely to stop the ibex server in the mean time so the problem with the Mercury's shouldn't reoccur before then
