### ISSUE TITLE
E4: Move to Eclipse Oxygen / JDK 10

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3169]
The next version of CSS will be out by the end of May. The only major change will be that it is running on Eclipse Oxygen and Java 10. We should start investigating moving this in our own GUI so that we can move with them as quickly as possible when the time comes.

**Comment by kjwoodsISIS** [comment]
[InfoQ: Java 10](https://www.infoq.com/news/2018/03/Java10GAReleased?utm_source=infoqEmail&utm_medium=SpecialNL_EditorialContent&utm_campaign=05102018_SpecialNL&forceSponsorshipId=1656)

**Comment by kjwoodsISIS** [comment]
We are already using Eclipse Oxygen.

**Comment by DominicOram** [comment]
I don't think we are. The target platform still points to 4.6, which is Neon, see https://wiki.eclipse.org/Older_Versions_Of_Eclipse

**Comment by Tom-Willemsen** [comment]
We are moving to Eclipse 4.8 in https://github.com/ISISComputingGroup/IBEX/issues/3506 and to Java 11 in https://github.com/ISISComputingGroup/IBEX/issues/3378 , this ticket is no longer required
