### ISSUE TITLE
Technical debt stand down: June/July 2018

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3170]
As a developer, I would like to run a technical debt stand down in the May/June sprint because they are good for tackling technical debt and sharing knowledge.

Topic TBD

**Comment by AdrianPotter** [comment]
Proposed date: 29th May

**Comment by AdrianPotter** [comment]
Calendar event set up. Awaiting topic feedback

**Comment by AdrianPotter** [comment]
We have cancelled the tech debt stand down for the May sprint owing to conflicts with preparing for the upcoming release. We've reused the ticket for next sprint.

The topics are currently being voted on in Slack:

0️⃣  Deployment/release process
1️⃣  Block server exception handling
2️⃣  Squish tests
3️⃣  Eclipse/CSS interactions
4️⃣  "Tech debt" labelled tickets
5️⃣  Dataweb
6️⃣  Excess logging (which may not even still be a problem)
7️⃣  Emulators/IOC tests
8️⃣  Bugs
9️⃣  E4

Currently 2️⃣  has 1 vote and 0️⃣ has 2 votes. Refer to #isis-internal on Slack for up to date results

**Comment by DominicOram** [comment]
New date of 12th June.
