### ISSUE TITLE
Friday-ticket day

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3174]
As a team, we would like to dedicate some time to developments on IBEX that individually we think would enhance the user experience, but aren't necessarily high priority. Our hope is that this will deliver interesting new features, increase motivation, and decrease the number of tickets being added uncontrolled to the sprint.

- Pick a day (not necessarily Friday)
- Set the format
    - Review only after 3pm
    - Stand up at 3pm to discuss work done
- Run the day
- Discuss at the retrospective

**Comment by AdrianPotter** [comment]
Proposed date: 5th June

**Comment by AdrianPotter** [comment]
Meeting in calendar. It will need a coordinator on the day since I'll be gone by then.

**Comment by kjwoodsISIS** [comment]
Done.
