### ISSUE TITLE
Keithley 2400 IOC : Write Output Voltage

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3176]
The current Keithley IOC is unable to set the voltage output for the voltage source part of the Keithley 2400 meter. Could we please add this functionality.

(As part of this ticket, would it please be possible to confirm that the Keithley 2400 ioc can also set the  current output if necessary)

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/66
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/101
https://github.com/ISISComputingGroup/EPICS-Keithley2400/pull/2/
https://github.com/ISISComputingGroup/EPICS-ioc/pull/289
https://github.com/ISISComputingGroup/ibex_gui/pull/744
