### ISSUE TITLE
AXIS record: check behaviour on new motor position

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3181]
Winfried reported a change in behaviour - if a new position was sent while motion was still in progress, the previous move completes before the new motion starts. With the motor record the previous motion was abandoned and the new motion started immediately. Check the behaviour and correct to be consistent.

**Comment by Rory-Potter-Tessella** [comment]
Are we still using the axis record after the Beckhoff changes? If not, do we need to do this ticket?
