### ISSUE TITLE
IBEX user manual: provide link to github from GUI

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3184]
As an instrument scientist, I would like to have an alternative address for viewing the IBEX user manual in case shadow goes down.

This was reported by Russell on ALF - he wanted to know how to restart the IBEX server but was unable to see the user manual.

Currently the user manual is available from:
- http://shadow.nd.rl.ac.uk/ibex_user_manual/Home
- https://github.com/ISISComputingGroup/ibex_user_manual/wiki

I think both links should be available from the GUI, so that if one service goes down we have redundancy. This ticket should simply add the github link to the web links perspective alongside the existing link.

**Comment by kjwoodsISIS** [comment]
I am not entirely convinced.  It would be better if more than one person could re-start shadow.
