### ISSUE TITLE
KEPCO: Not reliably starting up in remote mode

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3185]
As a user of KEPCOs I want to be able to rely on them starting in a controllable mode

**Notes**
This is based on a support call from ZOOM, where the KEPCOs were not communicating, but on inspection of the front panel they were not in remote mode.
The scientist had tried restarting the IOC with no luck, but when I did so he was able to observe them going into remote mode.
They were at least seeming to accept the setpoints etc, but were not going into remote mode, and were not actioning the settings. The KEPCOs do require initial addressing, and I wonder if there was something else going on that impacted on this.

**Comment by Tom-Willemsen** [comment]
+1 emu zero-field kepcos

**Comment by KathrynBaker** [comment]
I wonder if this is based on age/model/firmware in the KEPCOs? We may need to get the version of the KEPCO to see if it has the REM command available and use that to decide whether we need to reset and send parameters or just go into remote mode. Most of the KEPCOs at ISIS which are BOPs do not have the REM command, only the more recent digital display ones, and possibly some of the dial display ones that were bought more recently (hence there being a manual labelled "firmware not in use")

**Comment by John-Holt-Tessella** [comment]
Above added to wiki https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Kepco

**Comment by DominicOram** [comment]
Also change zero field to use this

**Comment by JamesKingWork** [comment]
The plan is on startup to either set into remote or reset and send parameters. However one concern I have is the manuals caution: "PRESSING RESET WILL CAUSE VOLTAGE TRANSIENTS TO APPEAR AT THE OUTPUT WHICH MAY DAMAGE A CONNECTED LOAD"

**Comment by KathrynBaker** [comment]
SECI would have always sent a reset, most Kepcos actually have a smoothing filter on the front as well, so if we actively check the firmware, reset if we can, and only reset when the PSU hasn't been updated to a newer version it should be fine

**Comment by JamesKingWork** [comment]
Docs added on how to force autosave to write at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Autosave#forcing-autosave-to-save-at-a-given-point-useful-for-testing

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-kepco/pull/7
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/540
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/376
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/89
- https://github.com/ISISComputingGroup/ibex_gui/pull/1201

**Comment by Tom-Willemsen** [comment]
Some comments on the PRs. Additionally:
- Do we have a ticket/pending task to test this with hardware (e.g. on EMU zero field and/or ZOOM). I couldn't see one but may have missed it, if so link it from here
- Can you write a few sentences in the [user manual](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Kepco-Power-Supply) about what this option does from a user's perspective

**Comment by Tom-Willemsen** [comment]
This is currently the highest priority item on EMU's wishlist. EMU should be available during the short shutdown if we want to test this change against hardware.

**Comment by JamesKingWork** [comment]
Updated docs: https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Kepco-Power-Supply#macros

**Comment by JamesKingWork** [comment]
Ticket to test on hardware: https://github.com/ISISComputingGroup/IBEX/issues/5851
