### ISSUE TITLE
deploy: Make config upgrade better

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3193]
Currently configuration upgrades including globals.txt upgrade do weird things with generators. They expose a generator and save changes in the items generated this is slightly unexpected. Think of a better way to do this and maybe make it work the same for both configurations and globals.txt. Eg Pass in a dictionary with tells the function how to alter the for a given IOC the macros or IOC name

**Comment by Alistair-McGann-Tessella** [comment]
Pull request:
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/17

- The unexpected behaviour of the save being hidden in a generator has been moved. 
- The xml trees and globals file have been split up into two classes, with a unified input
   - This is a dictionary containing the new and old macro name/value

Why is this good?
- Changing macros during upgrades should be more intuitive

**Comment by Rory-Potter-Tessella** [comment]
Updated [pull request](https://github.com/ISISComputingGroup/EPICS-upgrade/pull/17). 

### Description of work done

- Implemented the changes Dom asked for and refactored the code.
- Replaced the `macros to change` dictionary to pass into the change macros functions as a list of 2-tuples of macro objects (defined in ` src\common_upgrades\utils\macro.py`) which specify the macro to change from and the macro to change to.

### Issue

[#3193](https://github.com/ISISComputingGroup/IBEX/issues/3193).

### Acceptence Criteria

- [ ] The code is of acceptable quality
- [ ] All unit tests pass.

**Comment by Rory-Potter-Tessella** [comment]
Tidied up the code to meet PEP8 standards as requested.
