### ISSUE TITLE
Muon Front End: Issues with the Instrument Slits

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3196]
There is something almost impossible going on with the instrument slit sets, details will be added to the comments for this ticket. The purpose of this ticket is to ensure we spend some time looking at this before the next shutdown and can hopefully try again then to get these items converted to IBEX

**Comment by KathrynBaker** [comment]
A number of issues have been found with this, and there have been some changes undertaken to attempt to resolve this.

1. There was an issue relating to the raw values being integers for the Voltages in use, this was mitigated by using a different value in the C code for _MOVE_CMD, and is listed against the test ticket #1424. This could be revisited to use the axis record (floating point numbers), or to use a different print statement to allow for the field to use to be parameterised. This resolution should be undertaken as a separate ticket, but the choice of the solution should be made during this ticket.
1. There is an issue with the soft motor that uses the converted voltage updating in inappropriate ways.
   1. Without an explicit write of some kind, it isn't updating the position, however, this means that the setpoint ends up being overwritten, which isn't helpful
   1. The soft motor works better with a large number of retries (think 100s), which doesn't feel right either.
1. To resolve these issues there are a number of options, ranging from altering the slit position to being altered to an ai instead of being a motor, and revisiting the various links. The first part of this will be to reproduce these kinds of behaviours with soft motors, which may be impossible given the oddities of how the hard motors here work - they use an RDBL of an Analog Input and move using a routine within the Galil. If it can be reproduced, then further testing can be undertaken. If it cannot be undertaken then the various alternatives should be explored and those which can be written done so in order to improve the ability to test the options next time we have access to the hardware.

**Comment by kjwoodsISIS** [comment]
I think we should use this ticket to:
   1. Analyse the problems encountered (I think that's what @KathrynBaker is implying in the original comment).
   2. Create tickets to resolve each of the issues uncovered by the analysis (one issue per ticket).
After these tasks are done, this ticket can be considered complete.

**Comment by John-Holt-Tessella** [comment]
Steps to reproduce:

1. Open the slit by a small amount, underlying motor does not move. Maybe because the integer motor steps are not changed.

2. Move the motor a long distance/for a long time (only happened on momentum slits). Halfway through the motion the setpoint appears to change and motion stops

**Comment by KathrynBaker** [comment]
I will need to do so, but won’t be able to confirm that requirement until the end of next week when there is a meeting about the project to replace the physical slits. If that is going to happen within the next year or so, it will not be worth our doing this work, otherwise we ought to complete this work.

**Comment by KathrynBaker** [comment]
However, we should remember that we have potentially seen similar issues in the past, and the soft motor/real motor interaction should be considered anyway

**Comment by KathrynBaker** [comment]
As these are going to be replaced in the next 6 months, and the current system has been working for a long time now, marking this as wontfix.
