### ISSUE TITLE
JAWS: Sometimes sends zero to controller

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3201]
As a scientist, I do not want a setpoint of zero to  be applied to my motors when the jaws DB is loaded.

This was noticed when commissioning MAPS - motors would occasionally be set to a setpoint of zero (and perform the move) as the IOC was started. We have narrowed this down to the jaws DB by trial and error.

Occasionally (about 10% of the time) a setpoint of zero will be applied to a motor that is part of a jawset when the ioc is loaded. I suspect this change was accidentally introduced as part of https://github.com/ISISComputingGroup/IBEX/issues/3138

**Comment by FreddieAkeroyd** [comment]
A transform record is used to propagate motor setpoints to jaws setpoint on startup, this seems to work OK; however using this approach to monitor motor setpoints to resync back to jaws SP it looked like it sent an occasional zero on startup, though sometimes a zero was sent followed by the correct value so the motor moved to 0 then back to where it was originally. I'm not sure how this is happening - the monitoring is by channel access, that should start after a motor is initialised. I changed it to use two calcout records instead with initial values pushed from the startup transform record and this seems fine. Currently installed on MAPS.

**Comment by John-Holt-Tessella** [comment]
Tested: @FreddieAkeroyd restarted on MAPS multiple times no change. @AdrianPotter 
 looked at code everything looks good. It will not be reproducable using simulated motors.
