### ISSUE TITLE
Start/Stop IOCs: Indicate current configuration IOCs

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3204]
As a user, I would like it to be easier to find IOCs in my current config in the start/stop IOCs dialog so that I can reduce the amount of time searching the list for my IOC.

This might be achieved by an icon showing which IOCs are in the current config, or maybe a drop down to allow changing a filter, or something else entirely.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/712
