### ISSUE TITLE
Synoptics: Remove icon from writable PV components?

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3205]
As a user, I find the tick box next to writable PVs associated with synoptic components confusing. It is currently a tick, which makes me associate it with run control. Also, since OPIs do not provide a manual confirmation mechanism for setpoints, I find it strange that controls in the rest of the synoptic window do. I would rather have no control than an unclear one.

**Comment by RichardTysonIsis** [comment]
- https://github.com/ISISComputingGroup/ibex_gui/pull/704
