### ISSUE TITLE
ArchiveEngine: Document code location and build process

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3206]
As a developer, I would like to be able to find out how to build the archive engine because it makes investigating or modifying it impractical otherwise.

This ticket is a follow up from #3137. 

- The documentation for building the archive engine isn't sufficient/is incorrect and can't be followed to rebuild the archive engine
- The location of the archived code isn't recorded in the wiki
- We need to come up with a reliable way of building the archive engine. @DominicOram and @Tom-Willemsen reported this was difficult. Without it, we can't deploy new changes or roll back to old versions without great difficulty.

## Acceptance criteria

- A developer with no specialist knowledge of the archive engine can do the following without external guidance
    - Access the code
    - Set up a working development environment
    - Build the archive engine
    - Deploy a new version

**Comment by kjwoodsISIS** [comment]
How many points is this?

**Comment by DominicOram** [comment]
The build has been documented at  https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-CSS#source-code

The two previous Archive Engine pages (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Using-the-archive-engine-with-mysql) and (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-the-archive-engine-for-mysql) have been reduced to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CSS-Archive-Engine.

When this ticket is approved please delete the old pages.
