### ISSUE TITLE
GUI: Memory

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3208]
The memory seems to increase while running the manual system tests at around test 33-41. The graph is:

![image](https://user-images.githubusercontent.com/7570055/40548174-dc194004-602b-11e8-85ff-08db8f4fde44.png)

Investigate and fix it.

**Comment by Tom-Willemsen** [comment]
many comparable issues found & fixed since this ticket was written. This ticket no longer useful.
