### ISSUE TITLE
SystemTesting: Synoptics are committed to git

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3209]
As a developer I would like test synoptics with the prefix `rcptt_` not to be committed to git. The [ConfigVersionControl](https://github.com/ISISComputingGroup/EPICS-inst_servers/tree/master/ConfigVersionControl) service is responsible for doing this and should make an exception for synoptics beginning `rcptt_`. To reproduce:
* In the GUI go to synoptic->New
* Save a synoptic as `rcptt_something`
* In `C:\Instrument\Settings\congfig\NDXXX\configurations\synoptics` confirm that the `rcptt_` synoptic is pushed to git, it shouldn't be

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/45
