### ISSUE TITLE
Maps: Analogue fermi chopper: communicate

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3212]
The analogue fermi on MAPS responds with a subtly different syntax to Merlin's.

Main differences are:
- Nominal frequency comes back as a hexed number rather than an enum/lookup
- Nominal frequency setting also needs to be done using a hexed number rather than enum/lookup
- Chopper clock speed is different on MAPS.
- Autozero calibrations are different

**Comment by FreddieAkeroyd** [comment]
If you can use "visa serial" from EPICS can you run NI Spy on both labview and EPICS and see what is different? I guess an asyn trace suggests all ten out commands look the same? If the protocol only sends the command once, do you need to write to the PV 10 times to get it to work, or does it never wirk? Have you tried setting "clocal" and "crtscts" set to "D"? Does the moxa web interface confirm COM settings are the same when both are connected? We can discuss more tomorrow - where is the LabVIEW Vi by the way?

**Comment by FreddieAkeroyd** [comment]
Hi, just looked at Vi and it seems to set the serial port read and write buffer sizes, these are something like  4096 characters by default but the Fermi sets these to 128 bytes for read and only 16 bytes for write. Given each command is 9 characters, the serial port write buffer will not hold two commands. Maybe there is some funny writing/flushing interaction that setting low buffer sizes gets around? Currently it is not possible to set the buffer sizes in asyn, but it could be added. You could configure the port to do a small serial break after a write, that does a flush before it does the break, maybe the "flush" will help the command when the buffer size is larger than in labview.

**Comment by FreddieAkeroyd** [comment]
recompile asyn with the following to temporarily set the buffers to what labview does

in the connectIt() function in drvAsynSerial/drvAsynSerialWin32.c after the call to CreateFile() add:

    if ( SetupComm(tty->commHandle, 128, 16) == 0 )
    {
        printf("error setting com buffer sizes\n");
    }


Other things to try are, at end of    writeIt()   function in the same file add:

    FlushFileBuffers(tty->commHandle);

maybe using a serial break will help too?

**Comment by FreddieAkeroyd** [comment]
Can you use NiSpy with the emulator?

**Comment by FreddieAkeroyd** [comment]
It may show all visa calls, though the IOC will probably work it may help trace subtle differences

**Comment by Tom-Willemsen** [comment]
@davidkeymer dug out an emulator that FZJ provided a long time ago, so I have tried to get that talking just in case that helped diagnose a bit more while we don't have hardware access.
- It's a DOS program so I'm running it in a FreeDOS VM in virtualbox
- I'm planning to tunnel the COM port through from the VM to a real port on my computer, at which point I can use the MOXA physical loopback to connect the labview driver
- Their emulator is still not happy because of a divide-by-zero error. From the syntax of the error message it looks like Turbo Pascal was used - Turbo Pascal had a bug in one of it's libraries which means compiled programs can't be run on CPUs faster than 200MHz
  * I've tried limiting CPU utilization in virtualbox but this doesn't look to have helped
  * I downloaded a patch for the above problem from http://www.ipnet6.org/tppatch.html
  * Their chopper emulator is now running so may be able to test against this

![image](https://user-images.githubusercontent.com/24375813/40794780-16ba6334-64f8-11e8-8f97-4f1356eb73c3.png)

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen & @davidkeymer - good sleuthing to find this & try it out.
I am trying to understand where responsibility lies for sorting the problems we are having with the FZJ chopper.  Are we being made to jump through hoops because there is a problem on the FZJ side?  Or have we been provided with inadequate documentation?

**Comment by Tom-Willemsen** [comment]
Now seems to talk ok using asyn serial. The only thing that changed was that Paul Chorley swapped out the controller (for one which is allegedly identical). Perhaps the hardware issues with the old controller were also confusing the software in a strange way?

Attempting to use VISA serial upsets the crate. Not clear why. I will release the latest version onto maps then hotfix on the chopper

**Comment by Tom-Willemsen** [comment]
There is a version on MAPS. I have shown it to Ross Stewart and he is happy.
