### ISSUE TITLE
GUI: Manager mode dialog always fails on first try

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3213]
- Open the GUI
- Try to access manager mode
- An error dialog appears (see below)
- Try again
- It works

## Acceptance criteria

Follow the workflow above. The manager mode dialog should work first time.

Please make sure this gets a system test!

**Comment by AdrianPotter** [comment]
![image](https://user-images.githubusercontent.com/10273443/40651970-e8b20e9e-632e-11e8-8d13-1f3465d13a48.png)

**Comment by jeremyspencer39171** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/713
