### ISSUE TITLE
IOC: Test TPG300

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3214]
As a developer I would like the TPG300 to be fully tested so that it will always work!!

Acceptance Criteria:

- all functionality of the TPG is tested
    - in dev sim mode
    - in rec si mode where possible
- Disconnected status is shown in fields when the emulator does not reply

**Comment by Rory-Potter-Tessella** [comment]
### Related pull requests

[IOC Test Framework pull request](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/95)
[IOC pull request](https://github.com/ISISComputingGroup/EPICS-ioc/pull/280)
[Device Emulator pull request](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/61)

**Comment by Rory-Potter-Tessella** [comment]
Updated the following pull requests:

- [IOC Test Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/95)
- [Device Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/61)

IOC pull request was approved and no changes have been made to it.

**Comment by RichardTysonIsis** [comment]
Tom helped me review this.
