### ISSUE TITLE
Training: Add basics of scripting

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3215]
As a training delegate, I would like to cover the very basics of scripting in the introduction to IBEX training course so that I can run some simple commands having attended the training.

We used to run a basic scripting session during the Introduction to IBEX but removed it in favour of putting all scripting in the afternoon. A delegate reported at the May training that they would be keen to see how to launch the console and run basic commands without needing to know everything about scripting.

These could be included as an optional extra, time permitting. In the May run of the course we had time to spare.

One consideration is that if delegates are only partially trained in scripting, it may lead to an increased support load as they try and do things they haven't been trained on. It will be hard to define a natural cut off for the training.

**Comment by kjwoodsISIS** [comment]
> One consideration is that if delegates are only partially trained in scripting, 
> it may lead to an increased support load as they try and do things they haven't 
> been trained on. It will be hard to define a natural cut off for the training.

We can make it clear in the training that the "basic scripting" in the Introduction to IBEX is not sufficient for controlling an instrument.  If a scientist wishes to use scripts to control an instrument, he or she can attend the IBEX with genie_python course.

**Comment by DominicOram** [comment]
See http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FTraining&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View=%7BF2C33C51-70E6-4343-B937-2C59A2568306%7D

I've added 4 slides, I think this covers the very basics.

**Comment by Tom-Willemsen** [comment]
On slide 51, the slides currently say:
> g.cget(MY_BLOCK)

I think we should be clearer that MY_BLOCK should be in quotes - as it stands it will fail with a syntax error

On the same slide:
> g.cset(MY_BLOCK=1)

I think we are encouraging the use of `g.cset("MY_BLOCK", 1)` over `g.cset(MY_BLOCK=1)` to eliminate confusion with the other keyword args that cset can take.

On slide 52:
> g.load_script(‘run_my_experiment.py')

This has different quotes at the start and the end of the string which will cause an obscure-looking syntax error if someone tries to copy/paste from the powerpoint

Other than those minor points I think this is good

**Comment by DominicOram** [comment]
Updated with changes
