### ISSUE TITLE
E4: Unable to parse banner

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3221]
As a result of the changes in #3010, the format of the banner has changed. The result is that the E4 prototype can no longer process and display the banner. In fact it causes a null pointer exception on startup. Please fix so that the E4 banner functionality matches E3.

**Comment by AdrianPotter** [comment]
Start by merging `master` into `master_E4`. Should sort out all the back end logic.

**Comment by Tom-Willemsen** [comment]
I fixed this as part of https://github.com/ISISComputingGroup/IBEX/issues/2873
