### ISSUE TITLE
ORC: archive frequency as measured by device

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3222]
As a developer, I would like to know and archive the **measured** frequency of signals which oscillate.

Example: Merlin Oscillating radial collimator.
- We do not want to archive all motor positions, this is too much data and will fill up the archive
- We want to be able to look back over historical data and check what the frequency was at a given time
- Devices may not always "accept" setpoints (or might not be able to get there), and also, may not directly provide a frequency readback command. Therefore, we should be able to derive the frequency from an oscillating signal.

**Comment by John-Holt-Tessella** [comment]
Won't fix the deadband on this is large so it is not being archived. We think instrument scientists are happy with just the frequency. 
Problem with archive filling up was jaw set which has analogue return.
