### ISSUE TITLE
IOC: Test Lakeshore 218

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3223]
As a developer I would like the lakeshore 228 to have tests for all its functions so that I can test it without the hardware.

Acceptance Criteria

1. All functions of the lakeshore 218 are tested
1. Disconnection function is tested
1. All (finishing touches)[https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches] for IOC are done

**Comment by Rory-Potter-Tessella** [comment]
### Related pull requests
- [Device Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/63)
- [IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/282)
- [Tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/97)
