### ISSUE TITLE
IOC: LARMOR motion set-points

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3225]
On Larmor in motion setpoints db file many of the `AXIS1` macros have been set to `AXIS1=` I changed them on LARMOR but would rather it was as it is on master. Can we check that we do not need to do this next time and if we do add this change into the master.

**Comment by Rory-Potter-Tessella** [comment]
Appears to work. 

Added IFIOC_GALIL_0# = "#" environment variables to st-common before init.cmd to get rid of maclib errors. See the following [pull request](https://github.com/ISISComputingGroup/EPICS-ioc/pull/287).

**Comment by Rory-Potter-Tessella** [comment]
There is an error which occurs in motion set points on GALIL motors 5 and 6 on LAMOR. Created a new ticket to address this issue [3255](https://github.com/ISISComputingGroup/IBEX/issues/3255).
