### ISSUE TITLE
Generate List of Equipment on Unmigrated Instruments

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3226]
As a PM, I would like to generate a list of all the equipment used by instruments which we have yet to migrate to IBEX, to help plan future migrations.

#### Acceptance Criteria
1. A list of equipment used by each of the following instruments (i.e. one list per instrument):
ARGUS, ChipIR, CHRONUS, ~CRISP~, EMU, HIFI, INES, INTER, LET, LOQ, ~MARI~, MuSR, ~NIMROD~, OFFSPEC, ~OSIRIS~, PEARL, POLREF, SANS2D, SURF, SXD, TOSCA, WISH.
1. The list should be a plain text file (CSV or tab-delimited is perfectly acceptable).

#### Notes
1. @davidkeymer  has created a script that extracts this information from SECI config files.
1. The tasks to be performed is simply a matter of running David's script for each of the instruments listed above.

**Comment by KathrynBaker** [comment]
Whilst not heavily supported, can we also consider ARGUS and CHRONUS, as we will want to remove their SECI systems, and possibly before we get to the stage in the project where we adopt the instruments. There are limited items, and I believe they are a subset of the other muon instrument items, but they do at least vaguely exist.

**Comment by ChrisM-S** [comment]
Please can we also add to this list anything which is likely to run on "setup" machines.  These have roughly three uses:
1) Setup of existing kit whilst the previous experiment is going on - Same devices
2) Use of "offline" equipment for characterisation or offline experiments, in or out of cycle.
       - maybe not always equipment to be used online (is the Sorenson for example in this category?)
3) As we have now unbundled most bits of Oxford equipment from the Triton for separate IOCs, the Triton and other similar PCs might be worth evaluating (we still have the choice not to write the IOCs).
currently it might be worth listing the Tritons (for themselves) and the new WISH and PEARL setup machines which are starting life as SECI clones.

**Comment by ChrisM-S** [comment]
sorry wrong button :-(

**Comment by kjwoodsISIS** [comment]
Completed 04/07/2018 by @davidkeymer.

There are now [Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki) pages for all instruments
