### ISSUE TITLE
VESUVIO: spectra plots not working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3238]
The graphs on vesuvio are not working, either from the client on vesuvio or from a new client on my desktop. However the PVs look to be updating OK i.e. I can:

camonitor IN:VESUVIO:DAE:SPEC:1:1:Y

and see values, also displaying a spectrum with genie_python via

g.plot_spectrum(1)

works OK too. So it suggests something else is upsetting the client?

**Comment by kjwoodsISIS** [comment]
Are spectra plots working OK on other instruments?

**Comment by FreddieAkeroyd** [comment]
The client on larmor looks to be working, and I can look at larmor from my desktop, but VESUVIO doesn't currently work from the ibex client on either vesuvio or my desktop. The graph just shows 0-1 on all axes, it looks like it is not reading any data. genie-python and camonitor can read spectra 1,2 and 4 ok but don't see spectrum 3 (I only looked at spectrum 1 yesterday). The 4 graphs default to showing spectra 1,2 ,3 and 4. If one spectrum is unavailable will it stop all graphs working?

**Comment by FreddieAkeroyd** [comment]
Spectrum 3 has reappeared, but graphs are still not working

**Comment by FreddieAkeroyd** [comment]
The data is there, but the EGU field is missing sometimes. What metadata does the client need?

**Comment by FreddieAkeroyd** [comment]
I ran the   isisdaeShowPCAS    command I recently added on vesuvio, on one run it looked like it had timers with negative amounts of time to expire, but now looks OK.  However spectra still not OK in GUI, but fine from genie_python. It is using timers for some things that it doesn't need to, so i will elimate these.  Larmor is working OK and has far more timers in the queue than vesuvio...

**Comment by Tom-Willemsen** [comment]
Replace the DAE spectra plots with an OPI. OPI appears to work.

**Comment by FreddieAkeroyd** [comment]
Thank you to @Tom-Willemsen @DominicOram and @John-Holt-Tessella for investigating this morning. It looked like IBEX made connections to the PVs using PVManager, but then didn't receive any updates for values. It did get updates at start of cycle, so something has happened to the data and it no longer gets these updates even though other EPICS tools on the same computer are still happy. When an OPI was created, this was able to read and display the data - however the OPI should be using the same PVManger instance as the IBEX graphs! It was decided to create a ticket to replacing the graphs by OPIs rather than try and diagnose more (unless we see further IBEX/PVManager interaction issues)

**Comment by FreddieAkeroyd** [comment]
For info, detector diagnostics table is still working on Vesuvio itself, just the spectra plots that are not

**Comment by Tom-Willemsen** [comment]
Note to reviewer: just review the GUI pull request not the one onto isisdae
