### ISSUE TITLE
Friday Ticket Day

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3242]
As a team, we would like to dedicate some time to developments on IBEX that individually we think would enhance the user experience, but aren't necessarily high priority. Our hope is that this will deliver interesting new features, increase motivation, and decrease the number of tickets being added uncontrolled to the sprint.

- Pick a day (not necessarily Friday)
- Set the format
    - Review only after 4:30pm
    - Stand up at 4:30pm to discuss work done
- Run the day
- Discuss at the retrospective

**Comment by Rory-Potter-Tessella** [comment]
Sent an email booking the 20th of June as a Friday Ticket day.
