### ISSUE TITLE
Client: Update location for MCR news feed

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3244]
The location for MCR news has changed from https://www.isis.stfc.ac.uk/gallery/mcrnews.txt  to https://www.isis.stfc.ac.uk/gallery/beam-status/mcrnews.txt

This needs to be changed in the IBEX client

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd : when will this change happen?  (or has it already happened?)
