### ISSUE TITLE
IOC: Beckhoff find problem in limits

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3248]
The limits in the Beckhoff get set to 0 on start this means it can not be moved. This was discovered as part of #3245.

Reproduce:

1. Use IOC from 4.4.0
1. Start IOC, limits are set to 0 and can not be set to anything else.

I started to debug it but only got so far. Here is what I have found:

In the logs there is a from 2018-06-04 there are lines of the form

`BKHOFF_01-20180604.log:[2018-06-04 14:15:43] ../axisRecord.cc:3724 IN:IMAT:MOT:MTR0901 pmr->dhlm=181 maxValue=1.99835e-316`

And the line before that is:

    BKHOFF_01-20180601.log:[2018-06-01 12:17:36] 2018/06/01 12:17:36.602 devMotorAsyn::update_soft_limits IN:IMAT:MOT:MTR0901 RawHLM_RO=0.000000 RawLLM_RO=0.000000 valid=1 DHLM_RO=0.000000 DLLM_RO=0.000000

before 2018-06-04 the lines read:

     BKHOFF_01-20180601.log:[2018-06-01 12:17:36] 2018/06/01 12:17:36.602 devMotorAsyn::update_soft_limits IN:IMAT:MOT:MTR0901 RawHLM_RO=0.000000 RawLLM_RO=0.000000 valid=0 DHLM_RO=0.000000 DLLM_RO=0.000000

valid is now 1 not 0.

In the code, `axisRecord.cc:3724`,  it says:

```
    if (pmr->priv->softLimitRO.motorDialLimitsValid)
    {
        double maxValue = pmr->priv->softLimitRO.motorDialHighLimitRO;
        fprintf(stdout,
                "%s:%d %s pmr->dhlm=%g maxValue=%g\n",
                __FILE__, __LINE__, pmr->name,
                pmr->dhlm, maxValue);
        fflush(stdout);
        if (pmr->dhlm > maxValue) pmr->dhlm = maxValue;
    }
```

So I think now the limits read from the controller are now valid but both 0, but before they were not valid. This in turn means that we can no longer set the limits to bigger than those in the controller.

The next step is to work out where the validity flag is set and why this has changed. Probably we want to keep this if possible but with the correct values for those limits. This would allow users to set the limits smaller than the current values.

To help test Steve Cox mentioned you can download the Beckhoff controller program and run it without a licence, unless it is controlling a motor, this might allow for some testing without an actual Beckhoff.

**Comment by FreddieAkeroyd** [comment]
Did removing the autosave directory help, or did you need to revert the controller too? Removing the autosave directory would only work once and it would get created by the ioc for next boot, so reverting (or commenting out autosave fields) would likely be needed.

**Comment by John-Holt-Tessella** [comment]
Neither removing and changing the values in autosave values worked. I also tried to comment out what I thought were the autosave lines to read:

```
# Save motor positions every 5 seconds
# $(IFHASMTRCTRL) $(IFNOTDEVSIM) $(IFNOTRECSIM) create_monitor_set("$(IOCNAME)_positions.req", 5, "P=$(MYPVPREFIX)MOT:,CCP=$(MTRCTRL)")

# Save motor settings every 30 seconds
# $(IFHASMTRCTRL) $(IFNOTDEVSIM) $(IFNOTRECSIM) create_monitor_set("$(IOCNAME)_settings.req", 30, "P=$(MYPVPREFIX)MOT:,CCP=$(MTRCTRL)")
```

and deleted the require lines. This also didn't seem to help. So I am a bit unsure why.

**Comment by FreddieAkeroyd** [comment]
The above lines stop it autosaving values for next startup, reading is done earlier on - easiest to delete the autosave directory so it has nothing to read! The actual reading is determined by .req or DB info lines depending on what the PV is

**Comment by FreddieAkeroyd** [comment]
The axis record has now been reverted in #3343 and I believe this will fix the issue, putting into impeded until can be checked on an instrument

**Comment by FreddieAkeroyd** [comment]
Plan to test week of 23rd July before SPS is locked off for other work

**Comment by Rory-Potter-Tessella** [comment]
This was tested on the 24th of July on IMAT. The limits are now set to sensible values.
