### ISSUE TITLE
POLARIS : TS1 Beamcurrent logging error

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3249]
Archived POLARIS log files show a TS1_beam_current with large negative values. The log files show this. It is confirmed in the nexus file as well. An example file is :
\\isis\inst$\NDXPOLARIS\Instrument\data\cycle_18_1\POLARIS00110930.log
\\isis\inst$\NDXPOLARIS\Instrument\data\cycle_18_1\POLARIS00110930.nxs
2018-06-11T08:21:52	TS1_beam_current	-182574

On looking at POLARIS configurations, this relates to the PV called IN:POLARIS:DAE:BEAMCURRENT
(the value looks to be negated and multiplied by 1000)

**Comment by FreddieAkeroyd** [comment]
This value is derived from the DAE microamp values rather than the accelerator, I see the "Actual_beam_current" block was behaving sensibly. This doesn't look to be new behaviour this cycle e.g. run 106859 from April shows this behaviour too, I haven't looked any further back as yet. Probably a software issue, will take a look.

**Comment by GDH-ISIS** [comment]
No one has highlighted anything so there is nothing pressing. Mentioned only as it may relate to something such as a race condition at the start of a run. Fingers crossed it is not the case.

**Comment by FreddieAkeroyd** [comment]
It looks like it would have always done this, and will be doing it on SECI too. The first uamp difference would have used microamp hours from the last ended last run, but assumed collected in 5 seconds (poll time). So the size of the negative number should vary depending on duration of previous run.

**Comment by FreddieAkeroyd** [comment]
Fixed in ISISComputingGroup/EPICS-isisdae@51090d8
