### ISSUE TITLE
ZOOM: Motor encoder problem

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3250]
Beam stop 2 Z Motor 0505 had a problem on 2018-06-11 at 9:13. A request was made for the motor to move but the encoder does not register the move. The user reports that the motor is moving. 
After going down to the beamline it everything works and I homed it. The only difference was that the tank is now under vacuum we should check this after cycle.

![image](https://user-images.githubusercontent.com/7570055/41236054-0f0e058a-6d88-11e8-811b-ac1a203a6a40.png)

**Comment by kjwoodsISIS** [comment]
How many points was this? (not many, presumably).

**Comment by John-Holt-Tessella** [comment]
No. It took about a couple of hours though, I had to go down to the hall and then find out what the problem was and deal with the post actions
