### ISSUE TITLE
genie_python: Python 3 dependencies differ from Python 2 dependencies 

### ISSUE THREAD

**Issue by ghost** [ISISComputingGroup/IBEX#3256]
The package dependencies in the `requirements.txt` file for the python 3 build of genie python differ from the package dependencies `common_build_python.bat` file in ways one would not expect. E.g. matplotlib and iPython are included in `common_build_python.bat` but not in `requirements.txt` file.

It may be that these other packages are installed as dependencies of packages in `requirements.txt` but it would be better to explicitly state the required package and version in `requirements.txt`.

Possible solution: add packages and version numbers from `common_build_python.bat` file to `requirements.txt` file.

**Comment by rerpha** [comment]
No longer needed as python 2 is being removed.
