### ISSUE TITLE
Keyence TM3001-P: IBEX and SECI control

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3258]
Control is required for a Keyence TM3001-P Optical micrometer which will be used to measure the blade gap of Jawsets. To sync encoder data and optical data onto the same clock, they require the micrometer to be logged by both SECI and IBEX. The device will be used both offline (R78) and on an instrument. It is planned to install on on OFFSPEC over the long shutdown, so control would be required by and of cycle  18/1 in time for summer. OFFSPEC is a SECI instrument, but we should implement as CaLab plus EPICS driver if possible. The logging rate is not required to be very high, so logging via a "block" in either system would be sufficient.   

https://www.keyence.com/products/measure/micrometer/tm-3000/models/tm-3001p/index.jsp

Customer: Jamie Nutter

@jonelmer can provide further details on communication, there are manuals available on the above link

**Comment by kjwoodsISIS** [comment]
Whoever picks this up: please estimate the number of story points.

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/ibex_gui/pull/737
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/110
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/72
https://github.com/ISISComputingGroup/EPICS/pull/121
https://github.com/ISISComputingGroup/EPICS-ioc/pull/297
https://github.com/ISISComputingGroup/EPICS-Kynctm3K/pull/2
