### ISSUE TITLE
SANDALS: old motion control being replaced with Galil

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3259]
Over the summer long shutdown it is planned to replace the two different obsolete motion controllers on SANDALS with a single Galil DMC4040 controller.
* Two axis Jawset current controller by a parker crate. (Stepper motors)
* Two axis sample changer controller  (Stepper motors with encoder feedback)

Though this is a Galil 40xx there will be no absolute encoders involved.

From an ibex point of view I believe it will be a reasonably simple change as we interface via the motor record?

Customer: Jamie Nutter

**Comment by DominicOram** [comment]
Anthony has set up private network on ports 21 & 22

**Comment by DominicOram** [comment]
Delayed until December shutdown

**Comment by DominicOram** [comment]
This is no longer happening

**Comment by bnwthrswrk** [comment]
Does the two axis sample changer readily move over to Beckhoff?

**Comment by DominicOram** [comment]
I don't know, I think we need to discuss with Jamie
