### ISSUE TITLE
ZOOM: update ISISICP

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3260]
This is to fix an issue when DAE3 memory wraps (after about 1 billion counts in event mode) - unlike DAE2 an invalid packet is generated at transition and this caused a software error.   

Had only occurred once previously as they do not do event mode runs that long regularly

**Comment by FreddieAkeroyd** [comment]
Believe it works but waiting for ZOOM to run a long test

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - any news on this?  Has the fix been applied to ZOOM?

**Comment by FreddieAkeroyd** [comment]
ZOOM have been running with the fix since 21st July, but haven't done a long enough run recently that would confirm it works. I believe it does work from other testing.

**Comment by kjwoodsISIS** [comment]
In that case, I don't believe that this ticket needs to remain as impeded.  The work has been done and tested as far as possible.  If we discover a problem when ZOOM do eventually do a longer run, then we can raise a new ticket.
