### ISSUE TITLE
IMAT: WPI Syringe Pump IOC & OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3261]
As an IMAT scientist, I need a driver so that I can use a WPI SP2XX Syringe Pump in my experiment.

#### Acceptance Criteria ####
1. Solution to be ready for 26th June.
1. Other acceptance criteria - TBD (depending on chosen solution)

#### Notes ####
1. Scientist requesting this work is Genoveva Burca.
1. LabVIEW VI for WPI SP2XX Syringe Pump already exists:
   1. Front Panel VI: `C:\LabVIEW Modules\Drivers\WPI SP2XX Pumps\WPI SP2XX Pump - System.llb\WPI SP2XX Pump - System - Front Panel.vi`
   1. Setup Dialog: `C:\LabVIEW Modules\Drivers\WPI SP2XX Pumps\WPI SP2XX Pump - System.llb\WPI SP2XX Pump - System - Setup Dialog.vi`
   1. Documentation: `C:\LabVIEW Modules\Drivers\WPI SP2XX Pumps\Documentation`
1. The work to be done for this ticket is as follows:
   1. Determine if support for WPI SP2XX Syringe Pump can be implemented via lvDCOM.
      1. If so, do it (create appropriate XML file, front-panel OPI & setup dialog OPI)
      1. If not, proceed to steps ii - iv.
   1. Examine existing VIs to discover which sub-set of commands are supported.
   1. Implement these as an IOC
   1. Create OPIs corresponding to the Front Panel & Setup Dialog.
1. For reference: [WPI SP2xx Syringe Pump](https://www.wpi-europe.com/products/pumps-and-microinjection/laboratory-syringe-pumps.aspx).
1. It would be worth discussing the functionality required with Gareth and/or the scientist .

**Comment by kjwoodsISIS** [comment]
Whoever picks this up: please estimate the number of story points.

**Comment by GDH-ISIS** [comment]
WPI SP2XX Syringe Pump hardware now in office. Connected to MOXA - port 8. Device is talking so the cabling is correct. Documentation forwarded.

**Comment by GDH-ISIS** [comment]
For anybody developing this device driver and uses LabVIEW as a reference, please ensure they are using the latest version from SourceSafe. It was modified recently.

**Comment by Rory-Potter-Tessella** [comment]
Added the following features to the IOC:

- run: starts the device
- stop: stops the device
- dia: sets the diameter
- dia?: gets the present diameter settings
- run?: gets the current run status
- mode: sets the mode of the device
- mode?: gets the mode of the device
- dir?: gets the direction of the device
- dir rev: reverses the direction of the device.
- error?: queries for the error
- Also added mismatch for errors raised using "\r\nE".
- Added PV to check when NA is returned as a prompt when setting run, stop, dir rev or dia.

Note: the tests use [parameterized ](https://github.com/wolever/parameterized )0.6.1. Please install this package to run the tests correctly.

**Comment by John-Holt-Tessella** [comment]
Commands left to do (from the manual) looks like:

- del?
- ratei
- ratei?
- ratew?
- ratew
- voli
- volw
- voli?
- rev

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/293
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/105
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/70
https://github.com/ISISComputingGroup/EPICS-Sp2XX/pull/2
https://github.com/ISISComputingGroup/EPICS/pull/122
https://github.com/ISISComputingGroup/ibex_gui/pull/718

**Comment by DominicOram** [comment]
Also tested #3275 as part of this. Issues I found were mostly just tidying up. In the interest of speed I will merge this and further issues are in #3287. Note that I could not get the device to produce any errors so had to rely on IOCTests for error cases.
