### ISSUE TITLE
LARMOR or ZOOM: Knauer HPLC 1050 IOC & OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3262]
As a scientist using LARMOR or ZOOM, I need a driver so that I can use a Knauer HPLC 1050 pump in my experiment.

#### Acceptance Criteria ####
1. Solution provide equivalent functionality to existing SECI VI.
1. Solution to be ready for Cycle 2018/03 (experiment is scheduled for 14th December).
1. I can control the Knauer HPLC 1050 pump from the IBEX GUI
1. I can control the Knauer HPLC 1050 pump from genie_python

#### Notes ####
1. LabVIEW VI for Knauer HPLC 1050 pump already exists:
   1. Front Panel VI: `C:\LabVIEW Modules\Drivers\Knauer HPLC 1050\Knauer HPLC 1050 - System Functions.llb\Knauer HPLC 1050 - Front Panel 1.vi`
   1. Setup Dialog: `C:\LabVIEW Modules\Drivers\Knauer HPLC 1050\Knauer HPLC 1050 - System Functions.llb\Knauer HPLC 1050 - Setup Dialog.vi`
   1. Documentation: `C:\LabVIEW Modules\Drivers\Knauer HPLC 1050\Documentation
1. [Knauer HPLC 1050](https://www.knauer.net/en/discontinued-smartline-pump-1050-successor-azura-p-61l/p14161) appears to be a discontinued model.  May need to rely on existing VI for logic and manual.
1. The work to be done for this ticket is as follows:
   1. Determine if support for Knauer HPLC 1050 pump can be implemented via lvDCOM.
      1. If so, do it (create appropriate XML file, front-panel OPI & setup dialog OPI)
      1. If not, proceed to next step.
   1. Examine existing VIs to discover which sub-set of commands are supported.
   1. Implement these as an IOC
   1. Create OPIs corresponding to the Front Panel & Setup Dialog.
1. Supporting the Knauer HPLC 1050 will also benefit other LSS instruments.
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).

**Comment by John-Holt-Tessella** [comment]
Confirm whether this is the right pump.

**Comment by FreddieAkeroyd** [comment]
Confirmed that this will be needed for NURF experiment in December

**Comment by GDH-ISIS** [comment]
I have just confirmed with Rob that for the experiment in December, the driver for the Knauer HPLC 1050 is required.
(I should not have raised the question regarding the JASCO HPLC unit. A new ticket should be raised for the JASCO unit for use in the new year.)

**Comment by davidkeymer** [comment]
Main VI located here:
`C:\LabVIEW Modules\Drivers\Knauer HPLC 1050\Knauer HPLC 1050 - System Functions.llb\Knauer HPLC 1050 - Front Panel 1.vi`

**Comment by FreddieAkeroyd** [comment]
ORNL may have a driver, I've requested details

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS-Knr1050/pull/1
- https://github.com/ISISComputingGroup/EPICS/pull/144
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/135
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/5
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/336

**Comment by GDH-ISIS** [comment]
I have confirmed that for the experiment in December 2018, the Knauer switch valve is NOT required.

**Comment by GDH-ISIS** [comment]
Hardware arranged and made available for development.

**Comment by ThomasLohnert** [comment]
Good work! IOC works well as far as I can tell. Changes are already merged as it is needed on the instrument and rework is not critical for functionality, but here are some suggestions for minor changes and general tidying up:
- [ ] Split start/stop toggle button into two buttons and disable "Start" when you cannot actually start the IOC (when it is in local mode or has wrong sum of concentrations)
- [ ] Add a readback label for sum of concentrations
- [ ] Rename "Run Control" widget group to "Pump Control" (Run control has a specific meaning in IBEX)
- [ ] Rename "Start Ramp" to "Start Pump" - makes the purpose clearer for the user
- [ ] Make more clear to the user that the gradient concentrations are set when starting the pump, e.g. by adding a label that says this, or descriptive column headers for the different values.
- [ ] Typo in label: "Gradiant A" -> "Gradient A"
- [ ] Open a new ticket for adding missing controls from the VI
- [ ] OPI Checker is complaining, fix as appropriate
- [ ] ibex_gui PR is missing
- [ ] The OPI Target appears as "KNR1050" in the list - alias this to "Knauer 1050 HPLC pump" in line with the rest of the OPIs
- Some more inline comments on individual PRs
    - [ ] https://github.com/ISISComputingGroup/EPICS-Knr1050/pull/1
    - [ ] https://github.com/ISISComputingGroup/EPICS-ioc/pull/336

**Comment by aaron-long** [comment]
New pull requests based on rework:

- https://github.com/ISISComputingGroup/ibex_gui/pull/836
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/340
