### ISSUE TITLE
OPI: Eurotherm display units on ramp

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3263]
A Polaris instrument scientist I would like the ramp rate on the OPI to show its units.

Units can change based on the calibration file so make sure that the units are updated based on this.

**Comment by DominicOram** [comment]
Attempted to do by fixing https://github.com/ISISComputingGroup/IBEX/issues/1805 but didn't get anywhere

**Comment by John-Holt-Tessella** [comment]
Just add a label pointing at the units. It isn't as clean but is ok.

**Comment by LiamPanchaud** [comment]
Branches: 

https://github.com/ISISComputingGroup/EPICS-ReadASCII/tree/Ticket3263_eurotherm_ramp_unit

https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3263_eurotherm_ramp_units

https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket3263_eurotherm_ramp_units

**Comment by LiamPanchaud** [comment]
PRs:

https://github.com/ISISComputingGroup/ibex_gui/pull/776

https://github.com/ISISComputingGroup/EPICS-ReadASCII/pull/10

https://github.com/ISISComputingGroup/EPICS-ioc/pull/307

https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/117
