### ISSUE TITLE
RIKEN FE: NI DAQ setup for PLC interactions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3266]
As a member of the computing group I want to be sure that I can use DIO via the NI cDAQ systems to perform the changeover logic switching with the RIKEN Front End PLC

**Acceptance Criteria**
1. This will be tested with a real PLC on the 3rd of July as part of #3150 
1. The cDAQ IOC can be run with suitable PVs for the logic IOC
1. The cDAQ IOC has been tested with emulated PSUs, the logic IOC and some in/out signals in G39 and that it reads/sets lines as expected

**Notes**
1. The PLC will drive the line to low to signal that the logic will be changed
1. Some prototyping of a circuit may be required, although using the other I/O pins via a method such as LabVIEW/NI MAX may be enough for this testing
1. @Tom-Willemsen should be able to help with the logic IOC
1. @FreddieAkeroyd is most familiar with the DAQmx IOC
1. Both Tom and @KathrynBaker have some familiarity with the PSU Emulators in question

**Comment by FreddieAkeroyd** [comment]
I will spend a small amount of time on the existing DAQmx ioc, it appears to work but may need a bit more understanding of how it works. Given we are happy talking to LabVIEW from an IOC already, it may be easier to prototype this way and then do the full IOC later.

**Comment by FreddieAkeroyd** [comment]
Now working OK after last PR

**Comment by FreddieAkeroyd** [comment]
The merged PR code was tested using NI hardware and with a demo system provided by Tim Carter. The PRs just patched the existing daqmx code and generalised a few DB files with macros. I have not committed the modified st.cmd used as it would be very riken specific and live better elsewhere, we will likely merge daqmx, riken power supplies and changeover logic into a single IOC in a separate ticket. So I think this ticket could be considered complete.

**Comment by kjwoodsISIS** [comment]
After discussion at stand-up, this ticket is now considered complete.
