### ISSUE TITLE
RIKEN FE: Arduino setup for PLC interactions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3267]
As a member of the computing group I want to be able to use an Arduino to perform the changeover logic switching with the RIKEN Front End PLC

**Acceptance Criteria**
1. This will be tested with a real PLC on the 3rd of July as part of #3150
1. There is Arduino code to set/read the DIO as required - Done
1. There is Arduino code to wrap the Arduino logic for interaction on the Serial line - Done
1. There is an IOC for interacting with the Arduino - Done
1. There is an emulator for the Arduino IOC (at this point simple LeWIS, but it should be programmed so that it is not difficult to include an Arduino emulator in time) - Done
1. There are tests in the IOC test framework for the IOC - Done
1. The Arduino IOC can be run with suitable PVs for the logic IOC - Done
1. The Arduino IOC has been tested with emulated PSUs, the logic IOC and some in/out signals in G39 and that it reads/sets lines as expected

**Notes**
1. The PLC will drive the line to low to signal that the logic will be changed
1. Some prototyping of a circuit may be required
1. @Tom-Willemsen should be able to help with the logic IOC
1. Both Tom and @KathrynBaker have some familiarity with the PSU Emulators in question

**Comment by KathrynBaker** [comment]
Notes for writing the IOC

If the Arduino loses power then the COM port has to be disconnected and reconnected

Has the following command protocol:

| *Send* | *Receive* | *Notes* |
| --- | --- | --- |
|*IDN?|`RIKENFE Prototype v1.0`|There are changes planned to the protocol which may invlve that number changing|
|STATUS|The error string|The error string is `No Error` or a string detailing the error|
|ERR|The error string|The error string is `No Error` or a string detailing the error|
|READ n|`True` or `False`|n is a digit for the hardcoded list of digital inputs|
|WRITE n state|`OK` or `Error`|n is a digit for the hardcoded list of digital outputs, state is `TRUE` or `FALSE`|

**Comment by Tom-Willemsen** [comment]
Should we be moving (or forking) the arduino code for this into an IBEX git repository as opposed to a personal one?

**Comment by Rory-Potter-Tessella** [comment]
Created a wiki entry for the device https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Arduino-RKNDIO-PLC-control

**Comment by KathrynBaker** [comment]
There is a separate discussion to be had as to whether or not this should be IBEX code, or ISIS code – there are two potential organisations it could belong to, and until we answer the question as to whether it is limited to IBEX or will be used wider we can’t move it. However, it still needed to be recorded and versioned and accessible, hence in a personal repo at the moment. Once we know which organisation is going to look after it, it will be moved.

Regards,
Kathryn

**Comment by KathrynBaker** [comment]
In order to limit the number of parts that can go wrong, we are not planning to pursue the Arduino any further - although it is still a viable solution the lack of extra hardware needed for the NI DAQ solution was considered preferable. Work has been done, and so I will move this to review so that someone can review the code for the Arduino (the IOC has all been checked). The code has now been transferred to ISISNEutronMuon (https://github.com/ISISNeutronMuon/se-arduino-devices) as there was interest in collaborating from the USG, so this is the appropriate place for it, rather than an IBEX repo.

**Comment by kjwoodsISIS** [comment]
After discussion at stand-up, this ticket is now considered complete.  The Arduino code will not form part of IBEX (at least, for the forseeable future).  The code will be reviewed if and when it is picked up by the Electronics group.
