### ISSUE TITLE
GUI: IN/OUT Monitor OPI needs configurable Monitor CAEN Slot

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3268]
The monitor OPI contains a linking container which displays a single monitor. Currently this always shows the same monitor (0) make it display a monitor number configured via a opi macro. See double monitor for name.

For both make the slot configurable too.

Default both values to 0

**Comment by RichardTysonIsis** [comment]
It seems like the monitor already has a macro to display it's name (see picture below).

**Comment by RichardTysonIsis** [comment]
![monitor opi](https://user-images.githubusercontent.com/40176733/41785841-b8693724-763b-11e8-968c-78f54fa96ea1.png)

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/723
