### ISSUE TITLE
Nicos: merge with upstream

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3273]
As a developer I would like all the latest features that Nicos has to offer. 

Currently we maintain a hard fork of the nicos repository, this means that it is difficult to integrate changes/bug fixes that have been made by nicos. Currently it is very difficult to upgrade to their latest release as quite a few directory structures have been changed.

**Notes**
- We don't currently maintain a fork because their repository contains mangled email addresses
- Talk to Nicos people about the development workflow
  * If we can use their workflow, great
- If we can't use the NICOS workflow, we should figure out how to maintain a fork with history
  * This may need a script to filter out the mangled email addresses

**Acceptance criteria**
- [x] Our nicos repository is up to date with the latest nicos release
- [x] Our nicos repository is mergeable with the latest nicos, or there is documentation for how to perform a merge

**Comment by DominicOram** [comment]
I've updated all documentation regarding NICOS in the dev wiki (particularly removing references to the proxy). I've also added a page about how to develop with it at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Developing-NICOS.
