### ISSUE TITLE
Nicos: edit the contents of a script in the queue

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3274]
This is a spin-off ticket from #2544

As a user, I would like to be able to edit the contents of a script that I've already submitted to the queue.

This requires #3273 as the `update` function in nicos does not work in the release of NICOS which we're currently using.

**Comment by ThomasLohnert** [comment]
+1 from Muons

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/840
