### ISSUE TITLE
IMAT: WPI Syringe Pump IOC Start up and error handling

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3275]
See Issue [#3261](https://github.com/ISISComputingGroup/IBEX/issues/3261) for more details.

The following features have been added:
- Created IOC, device emulator and tests.
- Added the following functionality:
    - Starting the device
    - Stopping the device
    - Query the run status of the device
    - Handle errors correctly.

**Acceptance Criteria**

- [ ] All tests pass.
- [ ] The IOC communicates with the syringe pump in the office successfully.
    - [ ] Can start and stop the syringe.
    - [ ] Can query the run status.
    - [ ] Handles errors as appropriate.

**Comment by Rory-Potter-Tessella** [comment]
The following pull requests are related to this issue:

- [Parameterized Testing added to python setups](https://github.com/ISISComputingGroup/genie_python/pull/135)
- [Support module for SP2XX IOC](https://github.com/ISISComputingGroup/EPICS-Sp2XX/pull/1)
- [IOC ](https://github.com/ISISComputingGroup/EPICS-ioc/pull/290)
- [Device Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/67)
- [IocTestFramework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/102)

Updated the wiki on IOC Test Framework to include running by test name (https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/master/README.md).

**Comment by John-Holt-Tessella** [comment]
For release:

1. Copy IOC and Support modules from build to release folder Build105_syringe_pump
1. Copy to instrument
1. Run build_iocstartups.py
