### ISSUE TITLE
Motion Control: Stop, Pause, Move, Go

### ISSUE THREAD

**Issue by Steve-Cox-IDD-Motion** [ISISComputingGroup/IBEX#3277]
**Problem**

These buttons appear to cause confusion to users of the motor record detailed view. Do they need to be visible?

**Comment by FreddieAkeroyd** [comment]
They could be removed - we don't use them as far as I know, and the functionality would still be available to scripts if needed

**Comment by kjwoodsISIS** [comment]
Following a discussion, plus additional information from Iain Johnson, this ticket is superseded by #3294.
