### ISSUE TITLE
ITC503 ioc : 2 instances available

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3282]
There are instances on ISIS beam lines that more than 1 ITC503 has been under remote operation. Would it please be possible to make one more available? I believe only 1 is created at the moment. That should then cover most circumstances.

**Comment by Tom-Willemsen** [comment]
Consider doing this ticket at the same time as https://github.com/ISISComputingGroup/IBEX/issues/3284

**Comment by Tom-Willemsen** [comment]
Done in #3284
