### ISSUE TITLE
E4: Reset Layout creates a new python scripting session

### ISSUE THREAD

**Issue by jeremyspencer39171** [ISISComputingGroup/IBEX#3283]
If you are on the Scripting perspective and you press Reset Layout, a new scripting session is created and switched to. The old session is left running in the background, it can be switched to, but this is likely to cause confusion.

When the Reset Layout button is pressed, the scripting window should not change the session (or create a new one).

**Comment by Tom-Willemsen** [comment]
I am looking at this as part of https://github.com/ISISComputingGroup/IBEX/issues/2876
