### ISSUE TITLE
ITC503 tidy-ups

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3284]
- Create aliases for `TEMP:1:SP` -> `TEMP:SP` and the same for channels 2 and 3
- OPI: gas flow and heater power setpoint aren't in line with their readbacks 
- OPI: Buttons to set Auto PID don't work (setting the PV directly does work)
- Diagnose why gas flow mode and heater mode are being reset at IOC startup
- Figure out a common protocol that works for all ITC 503's at ISIS. Currently GEM has local modifications:
  * The response string returns `...S00...` as opposed to `...S0...` on Zoom's ITC
  * The auto PID on command needs to be `L1` on GEM and `L` on Zoom's ITC.

**Comment by John-Holt-Tessella** [comment]
For @GDH-ISIS to review
