### ISSUE TITLE
IMAT: WPI Syringe Pump Tidy Up

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3287]
As a developer I would like the code written in #3275 to be cleaner. The device had to be supported quickly and so was merged but the following should be done before it is really finished:

* The two IOCs should share an st-common and build.mak
* Add interest levels and archiving details to appropriate PVs
* The test classes all share a number of copy and pasted methods, refactor to be the same method. e.g. Setup, reset device, start running, stop running
* The name of the OPI could be a bit clearer
* There's no icon for the OPI
* The longer items in the mode drop-down do not fit
* As units don't update dynamically in E3 it would probably be better to just have the drop downs in the OPI and no units on the label/text box otherwise behaviour is confusing [Added labels with the units so they do change it is ever so slightly ugly but I think it is worth having]
* REC SIM Mode

**Comment by John-Holt-Tessella** [comment]
Pull request list:

 - https://github.com/ISISComputingGroup/IBEX_device_generator/pull/7
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/295

**Comment by Rory-Potter-Tessella** [comment]
Found a problem when running the IOC in DEVSIM mode. The reverse button doesn't appear to change the run status of the device. It does in RECSIM (see the [Emulator pull request](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/74#pullrequestreview-139456946)).

Everything else looks good.

**Comment by John-Holt-Tessella** [comment]
Do we know which behaviour is correct? Do you remember?

**Comment by John-Holt-Tessella** [comment]
Discussed, Status should be current direction or stopped. Direction should be direction that it is moving in or the direction is will move in. Mode is mode that was set.
