### ISSUE TITLE
Muon Front End: 8800 Danfysik OPI does not show the water flow interlock

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3292]
As someone looking at the OPI for reasons behind interlock failures, I'd like to see the status of the water interlock.

**Acceptance Criteria**
1. There is a display that reflects the water interlock PV

**Notes**
1. The PV already exists, it just needs adding to the OPI

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/725
