### ISSUE TITLE
Disable EPICS-SPMG Buttons on Motor OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3294]
As a motion control support person, I would like the EPICS Stop-Pause-Move-Go buttons to be removed from the high-level Motor OPI, because it confuses visiting scientists.

#### Acceptance Criteria
1. The Stop, Pause, Move and Go buttons are removed from the high-level Motor OPI (see attached diagram).
1. Access to the detailed Motor OPI is protected by "manager mode" (i.e. on pressing the "More Details..." button I am prompted to provide the manager mode password)
1. The high-level Motor OPI is updated to conform to the new OPI style.

#### Notes
1. The Stop, Pause, Move and Go buttons refer to the EPICS PV <name>.SPMG.
1. The red "STOP" button must remain unchanged (it has a different meaning to the Stop button).
1. Refer to the attached diagram to see which buttons must be removed, protected or left unchanged.
![remove_spmg](https://user-images.githubusercontent.com/7249337/41981126-145f70e2-7a20-11e8-8fc0-adaf81150596.png)
1. The functionality of the Stop, Pause, Move and Go buttons is available on the detailed Motor OPI (for those who understand how to use it).

**Comment by DominicOram** [comment]
We can probably just switch to using the OPI created in #2008

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/741
