### ISSUE TITLE
Add a STOP button to the Detailed Motor OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3295]
As a motion control support person, I would like the detailed Motor OPI to have a STOP button, because I need a simple, straightforward way to halt motion when I am viewing the detailed Motor OPI.

#### Acceptance Criteria
1. A STOP button is clearly positioned on the detailed Motor OPI.
1. The STOP button should have a red background, with the text "STOP" in yellow.

#### Notes
1. The "STOP" button on the detailed Motor OPI is intended to have exactly the same purpose and functionality as the "STOP" button on the high-level Motor OPI.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/750
