### ISSUE TITLE
GEM/POLARIS: Induction furnace

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3296]
As someone working on developing an induction furnace, I would like to be able to test my device using the control system that will be used to control my equipment on the beamline. As a user on Gem or Polaris, I would like to use the new induction furnace that is being developed.

An induction furnace is being developed for GEM and POLARIS by Jakob Ahlburg. From an initial meeting, this should be a relatively simple device from our perspective:
- Should be a standard stream device:
  * RS-232 comms are being added for us
  * The device already supports a set of sensible-looking commands (exact command set to be confirmed by Jakob)
  * I have asked for commands to read back setpoints
  * They have implemented some equipment safety checks on their end - it does not sound like we will need to worry about these.
  * They would like a facility to input an arbitrary command (protected by manager mode)

**Notes**
- We don't yet have a detailed protocol document - but the engineer has promised to send us one
- This is being developed for the September/October cycle
- Internally, this uses a power supply, a Julabo (or maybe some other source of cool water) and an Arduino but we will only be talking to the Arduino (via serial comms).

**Comment by Tom-Willemsen** [comment]
> Hi Thomas,
> 
> I June we meet in the electric workshop to discuss how to implement a new induction furnace to the IBEX system of POLARIS. I have now had the time to discuss matters with the electrician at Aarhus university and we have made a list of commands that is needed for the software to work. Our control unit consist, as you saw, of an Arduino unit that will be able to communicate through a RS-232 connection. All of the control software will be run by the Arduino and we only need to build up a working communication between the unit and the IBEX system. We are currently changing a bit in the programming but the general communication will be the same as described in the Protocol_for_IBEX.txt file. Ones the work is done we can send an Arduino module to you containing the software so you will have the opportunity to test the communication between the two systems. 
> Also we have been granted beamtime to test the setup in the November-december cycle, I personally hope we will be able to live test the software by then.
> 
> Let me know if you need more information or if something is not clear.
> 
> Cheers,
> 
> Jakob Voldum Ahlburg
> PhD Student

[Protocol_for_IBEX.txt](https://github.com/ISISComputingGroup/IBEX/files/2331984/Protocol_for_IBEX.txt)

From a brief read of the protocol document it looks pretty standard from our perspective. ~30 commands so probably ~5 points as a standard IOC/opi/emulator/test combination

**Comment by DominicOram** [comment]
Is it worth looking into running the the Arduino code up as the emulator for this rather than rewriting it in lewis?

**Comment by Tom-Willemsen** [comment]
I think it's a good idea but I'm worried that it will make this ticket's scope creep a bit too much given that this is on a deadline. I've opened a new ticket at https://github.com/ISISComputingGroup/IBEX/issues/3486 for it though

**Comment by DominicOram** [comment]
I agree but I don't want to spend time writing a lewis emulator that we then might throw away in favour of the Arduino. I think it's worth investigating the feasibility as part of this.
