### ISSUE TITLE
Requirements: Composite Axes For Reflectometers

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3299]
As a developer I need to understand the requirements for the reflectometors so that I can define the work that needs doing.

**Comment by John-Holt-Tessella** [comment]
Second meeting arranged.
 
Notes of stuff we know at: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometers

**Comment by kjwoodsISIS** [comment]
Notes on above wiki page - reviewed.  All OK.  We need to collect further information, but that will come from subsequent meetings.
