### ISSUE TITLE
Detailed Motor OPI: Show the state of the Motor Record "Command" (SPMG) feature

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3300]
As a motion control support person, I would like the detailed Motor OPI to make the state of the Motor Record "Command" (SPMG) feature to be made more obvious, to minimise the risk of confusion.

The 4 states (or modes) of the Motor Record "Command" feature are:
1. Stop
1. Pause
1. Move
1. Go

These are currently displayed by the Detailed Motor OPI as square push-buttons (see below). 
![convert_spmg](https://user-images.githubusercontent.com/7249337/42044930-2d98ab5a-7af2-11e8-86fd-e3e41c383aea.png)

In practice, they behave as radio buttons, but this is not made obvious by the choice of display style.
It would be better to use a GUI control that makes this behaviour obvious.  For example: genuine radio buttons or a combo-box/drop-down (as shown below).
![show_spmg_state](https://user-images.githubusercontent.com/7249337/42044951-3dc42d6a-7af2-11e8-8c1a-7346b7bd2cd0.png)

#### Acceptance Criteria
1. The state of the Motor Record "Command" feature is made obvious by an appropriate choice of GUI control.

#### Notes
1. Iain Johnson has created a [short presentation](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Motion%20Control/EPICS%20Motor%20Record/SPMG_Presentation.ppt) that explains the Stop-Pause-Move-Go states in the Motor Record.

**Comment by kjwoodsISIS** [comment]
See also tickets  #3294 & #3295

**Comment by DominicOram** [comment]
@IainJohnson Does this cover what you wanted? Can you also add to this any other improvements you wanted to that OPI?

**Comment by IainJohnson** [comment]
Yes - This looks good, the Radio buttons is a great observation.

I would promote explicitly adding a STOP pushbutton near to any field / screen that can initiate a move. i.e. if you end up putting these SPMG in a drop down menu, then I recommend adding a STOP pushbutton to the Detailed Motor OPI as with the front screen.

On IMAT Winfried observed that if he accidently entered an incorrect setpoint, but then immediately corrects the setpoint, the hardware still completes moving to the first erronous setpoint before heading to the intended target. - Having a Stop button is always handy!

**Comment by DominicOram** [comment]
@IainJohnson Yep, we have a stop button on https://github.com/ISISComputingGroup/IBEX/issues/3295 (which probably makes sense to do as part of this ticket). Was there also some stuff you wanted to do with making the home/limit etc. flags more visible?

**Comment by kjwoodsISIS** [comment]
I'd prefer that we keep the two tickets separate - they are "atomic" pieces of work.  They can, of course, be done at the same time (and it would make sense to do so).

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/750
