### ISSUE TITLE
IOC: RAMAN Spectrometer meeting for requirements

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3302]
As an HRPD instrument scientists I want to use a RAMAN spectrometer on my system sometime in the new year so that simultaneous light scattering and neutron powder diffraction.

The Raman suppliers sold a developer’s kit for exactly the purpose of creating a custom interface. However, we currently run the spectrometer via a laptop and it would be equally possible for IBEX to send instructions to the software running on the laptop rather than directly to the spectrometer. I guess, whichever solution is easiest.

For reference, the spectrometer is a B&WTek i-Raman Plus. If you need more info and access to the developer’s kit, then please Dom know. From the point of view of timescales, we expect to have the optical stick ready in the new year, although we can run it as a standalone during the commissioning phase.

**Comment by kjwoodsISIS** [comment]
Link to B&WTek i-Raman Plus is on [HRPD Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/HRPD-Instrument-Details#noteRamanSpect) page.

**Comment by Rory-Potter-Tessella** [comment]
Added notes from meeting on 2018-07-10 at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/RAMAN-Spectrometer.

I will have a look at the SDK and possibilities to interface with the device directly before we interact with the device on Friday afternoon.

**Comment by FreddieAkeroyd** [comment]
The device is USB so will either need a USB->Ethernet box or running the IOC on a directly attached computer. The SDK sounds like it would do the job and interface with asyn, but I note it mentions "visual C++ 6" which I hope is not a requirement of using their DLL

**Comment by KathrynBaker** [comment]
If the device is USB 1 speeds, there is a chance the USB to Ethernet boxes we have would work. If not, then we either need to re-evaluate what USB to Ethernet capabilities there are, or we need to include a computer with it in some form or another.

**Comment by ChrisM-S** [comment]
I'm guessing that the output of the device after a simultaneous neutron/raman run would be a complementary spectrum to the neutron spectrum and so it might be worth asking whether the file should be named something like HRPDnnnnnnnn_raman.txt by a script run with the neutron END command. In this way it would be automatically copied to the archive at the end of run and linked with the neutron data.  Easiest if the save was to the data area on the NDX but copying files at the end of run from a second PC wouldn't be a new problem :-).

**Comment by ChrisM-S** [comment]
The Silex devices get nearer to USB 2.0 speeds (and I have one device which I tested with some success - but not on an NiDAQ card in DAQ mode).  I notice that apart from providing a USB3.0 model now, there is another model [http://www.silexeurope.com/0ddb29ddeeba4ebf2fd19d8f3a138475/en/home/products/usb-device-servers/ds-510.html]() which aims at compatibility and supporting ISO Synchronous transfer modes.  Probably worth buying one for testing anyway.

**Comment by Rory-Potter-Tessella** [comment]
After looking at the SDK, there are different commands depending on the exact model number of the spectrometer and the connection type (either USB2.0 or USB3.0) so we need to know the exact model number and the USB connection type of the spectrometer that is going to be used.

We can interface with the spectrometer's .DLL file using one of:
- Visual C++ 2008 
- C# 2008
- Matlab 7
- Labview 8
- Visual Basic .NET 2008

Unfortunately, it appears that we cannot interface with the GUI software directly.

Other questions that we need to ask:
- Do they want to control the spectrometer and GUI at the same time (multiple access points)?
- How do they want to use the spectrometer through IBEX? 
    - Do they just want to set the integration time and number of scans in IBEX? 
    - Do they want to view the spectra plot in IBEX?
    - How much of the GUI would we have to rewrite?
- Do they want all of the data from the spectrometer in the same file as the neutron file?

**Comment by FreddieAkeroyd** [comment]
It looks like the DLL has been statically linked to the C RTL and so would not need a VS20008 runtime kit, it should also not show any cross DLL boundary resource issues. Functions look to have standard C decoration, so I think an asyn driver would have no trouble using the DLL

**Comment by Rory-Potter-Tessella** [comment]
Updated minutes of today's meeting with Dom in HRPD on the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/RAMAN-Spectrometer).

**Comment by Rory-Potter-Tessella** [comment]
Talked with Chris and updated the [wiki ](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/RAMAN-Spectrometer) with steps we'll take to try and talk to the device over ethernet.

**Comment by DominicOram** [comment]
Meeting minutes answer questions posed above.
