### ISSUE TITLE
On save of a current configuration, the IOC log displays an error.

### ISSUE THREAD

**Issue by RichardTysonIsis** [ISISComputingGroup/IBEX#3303]
When trying to edit and save the current configuration, the ioc log displays: MAJOR: Error executing write queue command save_inactive_config for state SAVING_NEW_CONFIG: Cannot change config, use SET_CURR_CONFIG_DETAILS to change the active config
However, when you try to do "save as" the same error doesn't appear.

Similarly, when editing a non current configuration, upon "save as" and confirmation to switch to the new configuration, the configuration does not switch to the new configuration. I think both these issues comes from the if statements around line 68 of src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java .

Reproduce:
- Go to edit current configuration and edit it and save it.
- The IOC log now displays the above error message.

or

- Go to edit configuration and choose a configuration that isn't the current one to edit.
- Do "save as" and choose to switch to the new configuration.
- The current configuration is not the new configuration.

Acceptance Criteria:
- Saving the current configuration does not produce the ioc log error.
- Save as on a non current configuration allows to switch to the new configuration.
- Any other configuration save pattern works.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/728

**Comment by Tom-Willemsen** [comment]
After review check RCPTT/Squish tests build, test failures should go back down to the usual fluctuations. If not then open a new ticket to investigate RCPTT/Squish tests.
