### ISSUE TITLE
RIKEN FE: Arduino setup for PLC interactions - IOC.

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3304]
Created an IOC,  for a digital input/output logic device for use on RIKEN FE. This IOC is called `RKNDIO`.

This ticket is part of [#3267](https://github.com/ISISComputingGroup/IBEX/issues/3267).

**Comment by Rory-Potter-Tessella** [comment]
Related pull requests:

-  (RKNDIO IOC)[https://github.com/ISISComputingGroup/EPICS-ioc/pull/294]
- (RKNDIO support module)[https://github.com/ISISComputingGroup/EPICS-RKNDIO/pull/1]
- (RKNDIO emulator tests)[https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/107]
-  (RKNDIO emulator)[https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/71]

**Comment by Rory-Potter-Tessella** [comment]
Created a wiki entry for the device https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Arduino-RKNDIO-PLC-control

**Comment by Rory-Potter-Tessella** [comment]
Updated all pull requests with fixes.

EPICS level pull request is https://github.com/ISISComputingGroup/EPICS/pull/124.

**Comment by kjwoodsISIS** [comment]
How many points?
