### ISSUE TITLE
GUI: Spaces are not trimmed from experiment team

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3305]
As a sandals instrument scientist I do not want a space a the end of a name to signal that the surname should be blank.

Reproduce:

1. Add name `peter the great ` (notice space on end)
1. Click set 
1. Users field in dashboard becomes blank (data web also reports incorrectly)

- [ ] Institute should be trimmed too.
- [ ] Tabs and other white space should be trimmed

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/729
