### ISSUE TITLE
Log plotter: removes formatting when rescaled

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3306]
As a user, I do not want my formatting to be removed from plots when I rescale the axes.

Notes:
- The was reported by Russel (ALF/MAPS)
- Russell brought up the specific example of custom grid lines being removed when the plot is rescaled
- This applies to the log plotter view, not the graphs within OPIs (those can be tackled in a separate ticket)

**Comment by DominicOram** [comment]
Cannot reproduce this in the latest GUI, grid lines are retained on scaling
