### ISSUE TITLE
RIKEN Front End: Update RIKEN and install

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3314]
As a user fo the RIKEN Front End system I want to update and test the system during the summer 2018 shutdown

**Acceptance Criteria**
- [x] RIKEN FE is updated to use a version of IBEX post the last release, containing #3266
- [x] The logic, DAQmx, and all other aspects are tested and ready to hand over to the scientists

**Notes**
1. The testing has to be undertaken with reference to the PLC changes
1. It is unlikely that the system will be ready to test until the week commencing the 23rd of July
1. Requires #3315
1. Requires #3440

**Comment by John-Holt-Tessella** [comment]
Delay until we know

**Comment by KathrynBaker** [comment]
Requires #3340

Please talk with @Tom-Willemsen before doing too much with this as he is aware of the outstanding changes that need to be done from #3340.

Needs to be done ASAP to allow the scientists to undertake their testing.

Was awaiting before this

**Comment by KathrynBaker** [comment]
Marked as for release, but in reality is pre release

**Comment by Tom-Willemsen** [comment]
Note: also make sure it is visible via EPICS. Maybe something about the address list but it's PVs are not currently accessible via a caget.

**Comment by Tom-Willemsen** [comment]
The scope of this ticket has crept up from "update and install" to "update, install and debug power supplies", so I've lumped some changes that were required for the real magnets into this ticket.

For the "Update and install" part:
- Check that riken has a sensible IBEX on it (note: it is in use so don't remote desktop but you can view remotely)

For the "debug" part:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/324
- https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/9
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/3
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/127
- Check that the IOC and protocol files for the danfysikis match the ones currently on RIKEN
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Riken-power-supplies
