### ISSUE TITLE
RIKEN-FE: Merge RIKEN PLC code into a single IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3315]
As an IBEX developer, I want to merge the st.cmd used for the RIKEN fron-end PLC, along with the daqmx, riken power supplies and changeover logic into a single IOC, because it is very RIKEN specific and is best kept together in a single logical bundle.

## Acceptance Criteria ##
1. RIKEN st.cmd, daqmx, riken power supplies and changeover logic merged into a single IOC

## Notes ##
1. See ticket #3266

**Comment by FreddieAkeroyd** [comment]
For RECSIM you need to merge ISISComputingGroup/IBEX#3412 first

**Comment by FreddieAkeroyd** [comment]
@Tom-Willemsen this should be a start - the st.cmd probably needs a bit of reorganisation to combine the three IOCS, we can have a chat

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/303
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/116
- https://github.com/ISISComputingGroup/EPICS-DAQmxBase/pull/3

To review, check the IOC tests work. Re-testing with hardware and final configuration etc will be done separately - likely to be either next week or the week after.

**Comment by Tom-Willemsen** [comment]
Full solution to be tested tomorrow afternoon (8/8/18) on RIKEN FE.
