### ISSUE TITLE
E4 presentation for Scientists

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3316]
As an IBEX developer, I want to create a presentation about the E4 migration for scientists, so that they understand the rationale for the changes we are making.

We should assemble a short presentation, so that we give scientists a consistent message and we make sure that we cover all the key points.

## Acceptance Criteria ##
1. Create a PowerPoint presentation that explains the E4 migration
1. The presentation should cover the following topics:
   1. Background - what are the forces that are moving us in this direction
   1. What changes are we making
   1. Demonstration of E4 version of IBEX Client
   1. Future developments (e.g. Phoebus)

## Notes ##
1. Some obvious questions people might ask - we should have answers for these:
   1. Q: I prefer a fixed window.  Can I stick with the E3 version of IBEX Client?  A: No.
   1. Q: When will the E4 version of IBEX Client be released?  A: TBD
   1. Q: Will there be training in the new version of IBEX Client?  A: TBD
   1. Q: What happens when users "lose" windows?  A: Use the reset button/keyboard-shortcut.
   1. Q: Can I define my own preferred layout of windows?  A: TBD.

**Comment by Tom-Willemsen** [comment]
For acceptance criteria 2.2, the list of user-facing changes is described in https://github.com/ISISComputingGroup/IBEX/issues/3309

**Comment by Tom-Willemsen** [comment]
Discussed with @John-Holt-Tessella : 

> Q: When will the E4 version of IBEX Client be released? A: TBD

In time for september cycle.

> Q: Will there be training in the new version of IBEX Client? A: TBD

We will not provide formal training - the slides produced for this ticket will be sufficient to highlight the differences. From a user perspective the vast majority of things have stayed the same - nothing that is covered in the IBEX training course has changed substantially in E4.

> Q: Can I define my own preferred layout of windows? A: TBD.

Not in time for September 2018.

**Comment by Tom-Willemsen** [comment]
Presentation available at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/eclipse_4_changes.ppt

We should decide how we plan to give this and the related nicos presentation. I suspect it will be hard to find times to meet with all the scientists before cycle start - may be best to email it round and supplement it with drop-in sessions? discuss

**Comment by DominicOram** [comment]
Some initial thoughts:
* Slide 5: I think emphasise a bit more what this means for the instrument:
   - You can switch over to E3 easily
   - There is no risk that device controllers have broken (this is a purely aestetic change)
   - All scripting is exactly the same
* Slide 6: If #3319 is in MVP mention that here
* Slide 9: Mention that the save dialog has also now been suppressed
* Slide 10: From a scientist I don't think labelling this as matplotlib is helpful. Maybe something like embedded python graphs is a more useful description, also the fact they are live should be mentioned. A demo of this is obviously much more useful than the slide
* Slide 11: We should probably be able to get a screen shot for this
* Slide 12: I think the VNC issue is the wrong thing to sell the script server on, scientists are quite happy with this workflow. Better selling points are:
   - Gives you a view of which line a script is currently on
   - Allows queuing up scripts
   - Makes it easier to ensure different scripting windows aren't fighting each other
   - Will allow dry runs and estimates of how long the script will take in the future
* In general, please be consistent with the capitalisation of Eclipse
* I think a single review isn't sufficient for this. Once #3317 is done we should have a meeting to talk about the content of both presentations and how we're going to give them.

**Comment by kjwoodsISIS** [comment]
The purpose of the E4 presentation is to support our explanation, **_in person_**, to scientists of why we are migrating to Eclipse-4.  If we e-mail it to scientists there is a risk that it is misinterpreted (e.g. because they skim read it).  Therefore, the E4 presentation should be presented to the scientists in person, so that the right emphasis is placed on the key points.
When inviting scientists to meetings we should be clear that the changes we are proposing are important and that we would value their attendance, prior to the start of the new cycle.
