### ISSUE TITLE
Script Server presentation for Scientists

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3317]
As an IBEX developer, I want to create a presentation about Script Server for scientists, so that they understand its capabilities, how to use it and our plans for future enhancements.

We should assemble a short presentation, so that we give scientists a consistent message and we make sure that we cover all the key points.

## Acceptance Criteria ##
1. Create a PowerPoint presentation that explains the new Script Server feature
1. The presentation should cover the following topics:
   1. Background - how does Script Server work
   1. What can Script Server do
   1. How to use Script Server
   1. Future developments

## Notes ##
1. Some obvious questions people might ask - we should have answers for these:
   1. Q: Do I need to make changes to my scripts?  A: No.
   1. Q: Can I still use the existing scripting perspective?  A: \<provide-the-answer\>.
   1. Q: Will you support Python 3?  A: Yes, when ISIS is ready to move to Python 3.
   1. Q: Can I step through my script?  A: \<provide-the-answer\>.
   1. Q: Can I edit my scripts on-the-fly?  A: Not yet.  We are still working on that.

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/nicos_changes.ppt

**Comment by DominicOram** [comment]
Looks good to me, only comment is that it might be worth mentioning that this is still a prototype and that it will not be replacing the scripting window any time soon.

**Comment by DominicOram** [comment]
Look good to me, thanks.
