### ISSUE TITLE
GUI: Reverse search in scripting console

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3320]
As an ENGINX/HRPD instrument scientist I would like to be able to reverse search in the scripting console so that I can find previous commands I issued easily.

**Comment by DominicOram** [comment]
+1 from MS on INTER

**Comment by John-Holt-Tessella** [comment]
I think you can type the search expression and press up arrow.

**Comment by ThomasLohnert** [comment]
Updated documentation at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/The-Scripting-Console
