### ISSUE TITLE
Log plotter: No autoscale on log plotter

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3322]
As an HRPD/ENGINX instrument scientist I want autoscaling not to happen when I have it switched off when I plan/zoom a graph. It should *not* scale to the max and min of the data (or limits) if I have told it not to and the default should be not to. So that when I look at graphs random large points don't effect my view of the data.

Reproduce:

1. Select some data
1. Ensure autoscaling is turned off
1. Either
    1. Pan to previous data
    1. Zoom out
1. Graph is scaled

Check the behaviour in E4 this may no longer be a bug.

**Comment by KathrynBaker** [comment]
Decision was made to only undertake this in E4

**Comment by Tom-Willemsen** [comment]
Re-requested by GEM

**Comment by Tom-Willemsen** [comment]
Check if this was fixed by #3080

**Comment by ThomasLohnert** [comment]
Closing the issue as outdated. Log plotter does not autoscale.
