### ISSUE TITLE
HRPD intermediate shutter

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3327]
HRPD currently have the following hotfix to enable them to get intermediate shutter status from the DAE, it needs to be added to master in a more general/better way  

in isisdae.db

record(calcout, "$(P)$(Q)_HRPDINT")
{
        field(INPA,  "$(P)$(Q)VETO:EXT3:PC CP")
	field(INPB, "$(P)$(Q)RUNSTATE CP")
	field(CALC, "(B=5||B=2)?(A > 50 ? 0 : 1) : 2")
	field(OUT, "$(P)$(Q)HRPDINT PP")
	field(OOPT, "On Change")
}
record(mbbi, "$(P)$(Q)HRPDINT")
{
    field(ZRVL, 0)
    field(ONVL, 1)
    field(TWVL, 2)
	field(ZRST, "CLOSED")
	field(ONST, "OPEN")
	field(TWST, "UNKNOWN")
	field(ZRSV, "MINOR")
	field(TWSV, "MINOR")
}

**Comment by Tom-Willemsen** [comment]
Maybe think about disabling these records using macros so that they don't appear on other beamlines
