### ISSUE TITLE
GUI: Remove motor details button from motion set points opis

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3329]
As a user I do not need to look at the motor that my motion set point depends on this button should be removed.

Remove from both motion setpoint opis.

**Comment by Tom-Willemsen** [comment]
Some scientists seem to find this useful. Others might not necessarily use it but equally don't seem to be pushing very hard for it's removal...

Closing for now, if a specific instrument comes up with a real need to remove it we can do it as a flash review to add a macro in the opi to hide the button quite easily - doesn't need a whole ticket.
