### ISSUE TITLE
GUI: Memory leak in E3 alarm perspective when JMS is disconnected

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3330]
When in the alarm perspective of the E3 GUI and the JMS server is disconnected, the GUI locks up a thread and memory usage increases.

**Comment by Tom-Willemsen** [comment]
Also occurs in E4. Make sure fix is applied to both E3 and E4.

**Comment by Tom-Willemsen** [comment]
To reproduce:
- Open java visual VM ('C:\Program Files (x86)\Java\jdk1.8.0_131\bin\jvisualvm.exe')
- Connect to IBEX instance (look in the "threads" view for threads named "PV manager worker" to confirm it is IBEX and not the eclipse IDE)
- Open the IOC log perspective to any instrument where the connection is up
- Switch to an instrument where the connection is down
- Look at the CPU graph in the visual VM - it will have locked out one core and eventually will start leaking memory.

**Comment by Tom-Willemsen** [comment]
E3: https://github.com/ISISComputingGroup/ibex_gui/pull/757
E4: https://github.com/ISISComputingGroup/ibex_gui/pull/758
