### ISSUE TITLE
E4: document how to hide perspectives

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3338]
As a user, I do not want to be confused by unfinished perspectives.

It is possible via the `CTRL-ALT-P` preference menu to remove a perspective, however this does not seem to be working with our custom perspective switcher.

**Comment by DominicOram** [comment]
Did some work in linked PR but a more flexible solution is probably required.

**Comment by Tom-Willemsen** [comment]
Pull Request: https://github.com/ISISComputingGroup/ibex_gui/pull/764
