### ISSUE TITLE
Log Plotter: close log plotter graphs on instrument switch

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3341]
Currently, open log plotter graphs persist after switching to another instrument. Since the new instrument will have an entirely different set of blocks/PVs (except for possibly a few global ISIS ones), these plots should close automatically on instrument switch.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/787

**Comment by Tom-Willemsen** [comment]
I've reviewed this and immediately done the rework as Richard is no longer here.

So, someone just needs to check that my rework is sensible.
