### ISSUE TITLE
Keyence TM-3001P: SECI interface

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3345]
As an instrument scientist I would like to be able to control the Keyence TM-3001P using my existing SECI software. This should be using the IBEX/EPICS control system as the backend.

This is an extension of #3258 

Acceptance criteria:
- [ ] All 16 OUT channels need to be accessible through this interface
- [ ] The engineering units need to be able to be set in the system for each OUT channel

**Comment by davidkeymer** [comment]
VI in `C:\LabVIEW Modules\Drivers\Keyence TM-3001P\`

**Comment by davidkeymer** [comment]
This VI is now in use on OFFSPEC for an offline slits test.
