### ISSUE TITLE
EUROTHERM: setpoint and autotune interactions

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3346]
There was an alarm noticed on SANDALS that related to a setpoint that was not being accepted by a system that was under autotune. The setpoint readback did not match the setpoint, but it seemed to be travelling in an appropriate manner.

The error disappeared after turning off autotune.

Whether in error or not, the eurotherm was heading towards the required setpoint.

This may need to be documented in a different way in the user manual, but the error should not occur.

Discuss the solution with people before implementing.

**Comment by GDH-ISIS** [comment]
In the past I had been asked to remove the autotune from the SECI system. I can understand how it could potentially cause an issue.
Some simple logic could mitigate the issue. Two possible options are :
1) If set point is sent, set autotune off if it is currently on.
2) If autotune is on, disable set point availability

**Comment by GRyall** [comment]
Autotune does not appear in current user or developer wikis. I assume it to be something in SECI (as implied in comment) and so no longer relevant.
