### ISSUE TITLE
PyDev : Keyboard Interrupt Inconsistent in IBEX

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3350]
I believe the keyboard interrupt for the PyDev console appears to be inconsistent. This can be demonstrated with a tight loop setting a block.
For example : 
while True: g.cset(Volt=0)

Pressing CTRL +c, the PyDev console prompt sometimes comes back with ">>>" - however the keyboard interrupt message is not returned. CTRL+c must be pressed once again for the "KeyboardInterrupt" message to be displayed.
Pressing the yellow button on the PyDev console in the IBEX GUI has the same issue.
This was first noticed when rapidly setting a PV with a ramp script. When CTRL+c was pressed, the script window returned with ">>>" - however, the PV was still being ramped even though I thought the script had stopped. I do not believe the script had stopped executing the ramp.
Note : the keyboard interrupt for the following example does appear to work i.e. no cset involved.
i=0
while True: i+=1

**Comment by John-Holt-Tessella** [comment]
I suspect this is caused because all exceptions are caught in cset not just a specific exception to do with cset. There are two solutions:

1. Catch specific exceptions only
1. Catch all exceptions but break on a keyboard exception
