### ISSUE TITLE
CRISP : VLAN setup for sample environment and Galils

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3351]
Ask networking to put together VLAN for Galils on the managed CRISP cabin network switch.
Once arranged, ensure the Galils network connection is moved from the direct ndh connection currently set up, to the cabin network switch on the appropriate port for the private VLAN.
Note : Galil addressing is already set up and operational.
Ref : https://github.com/ISISComputingGroup/IBEX/issues/3109

**Comment by DominicOram** [comment]
VLAN is on 21 and 22. I went down and wired it up this afternoon. To review ping the Galils (192.1.168.201...206) from NDXCRISP.

**Comment by GDH-ISIS** [comment]
All 6 Galils ping fine. LabVIEW talks to all 6. Complete
