### ISSUE TITLE
GEM Sample Changer: Do not move when already at position

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3353]
As a GEM instrument scientist I would like the sample changer not to move when I move it to the position that it is currently in.

**Comment by DominicOram** [comment]
From Dave:

> It appears that the sample changer script raises the arm and then lowers it when we set the sample changer to ‘move’ to the position that it is already in.  It is of course slightly perverse to ask it to do this, but in practice it is something that we do a lot – you set things up ‘manually’ and when you are happy you then start a run-control script, the first command of which is to set the position of the sample changer, usually to the same position.
 
Is it possible to modify g.cset(sample…) so that it checks whether a move is actually required before trying to move anything.  As it takes some time to raise and then lower the arm this quick check in software would allow us to collect more data...!

**Comment by John-Holt-Tessella** [comment]
Can we get either:

1. Get the scientists themselves to write this script
1. Include it in the driver

**Comment by davidkeymer** [comment]
I'm surprised the controller itself doesn't deal with this behaviour.  It might be worth checking exactly which commands are being sent to it in case there's a superfluous "retract/insert" or equivalent.

**Comment by DominicOram** [comment]
If I remember correctly this behaviour is built into the controller itself, it's currently on the instrument so we can go and double check. I think doing the logic in the driver is the best way to do this.

**Comment by DominicOram** [comment]
Similar logic is already in the fermi chopper see SPEED:SP:_SEND_IF_OK at https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db

**Comment by Rory-Potter-Tessella** [comment]
I've recently done a similar thing for my NGPS PSU power supply using the logic Dom mentioned (https://github.com/ISISComputingGroup/EPICS-NGPSPSU/blob/Ticket1922_Add_IOC_NGPSPSU/ngpspsuSup/ngpspsu.db - look at for POWER:SP:_SEND_IF_OKAY calc record)

**Comment by LiamPanchaud** [comment]
Branches: 

https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket3353_GEM_sample_changer_fix

https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/tree/Ticket3353_GEM_sample_changer_fix

https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket3353_GEM_sample_changer_fix

https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/tree/Ticket3353_GEM_sample_changer_fix

**Comment by LiamPanchaud** [comment]
Small issue with recsim testing due to a problem with a link between `INIT` `and SIM:INIT`. Seems like `INIT` does not forward values to `SIM:INIT` so in recsim the ioc does not look like it has initialised so fails the set up. Worked around by setting SIM in set up, then everything seems to work.

**Comment by LiamPanchaud** [comment]
Pull requests: 

https://github.com/ISISComputingGroup/EPICS-ioc/pull/306

https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/pull/2

https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/115

https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/77

(pls note this is my first _relatively_ independent pull request, I hope I haven't made any glaring errors)

**Comment by DominicOram** [comment]
Tested on actual device, works as expected.
