### ISSUE TITLE
Require an up to date version of CSS.

### ISSUE THREAD

**Issue by RichardTysonIsis** [ISISComputingGroup/IBEX#3356]
In #3136 I realised that E4 used a more recent version of CSS than the one currently shared in the build. This meant that CSS couldn't display options used by E4.
The shared version of CSS must therefore be updated to a current stable release of CSS. This will involve modifying build scripts.

**Comment by Tom-Willemsen** [comment]
Added latest SNS version to ICP binaries, setup documented in PR below:

https://github.com/ISISComputingGroup/EPICS-CSS/pull/8

(I used the SNS distribution because that includes all the tools we use at ISIS already; the base build doesn't)
