### ISSUE TITLE
IBEX client : Eclipse 4 : Cannot set blocks from PyDev

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3357]
New Eclipse 4 Ibex client does not appear to be able to set blocks from the PyDev window. Client running as stand alone (not as a development environment)
(Old client running in parallel has no problem)
![set block](https://user-images.githubusercontent.com/13995522/42896045-99e60fca-8ab3-11e8-850b-461ca1722dbc.JPG)

**Comment by Tom-Willemsen** [comment]
Both John and I tested this locally and could not reproduce. I also put the latest two jenkins builds on NDXDEMO and also could not reproduce there either.

I suspect you may not have the latest version of E4 as your genie_python log says "version 4.4.2.qualifier", this would be installed along with the latest client when running the `install_client.bat` script and would say "0.0.0.qualifier" for a development version

**Comment by GDH-ISIS** [comment]
I had a look with @Tom-Willemsen and the latest E4 client does not appear to have the problem - installed from kit$ using the batch file. Will close this ticket as it is believed to be a one off that looks to be resolved.
