### ISSUE TITLE
NICOS: Prevent disconnection error on sending multiple requests to server

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3360]
As a user of NICOS, I would like the sending of a rapid succession of requests to the server (e.g. by pushing the "dequeue" button repeatedly) not to cause a disconnection error.

When this happens currently, the IBEX client reconnects automatically after a few seconds, but it is disconcerting to the user to see an error with no explanation.

**Comment by Tom-Willemsen** [comment]
Requires https://github.com/ISISComputingGroup/IBEX/issues/3273 - it may have already been fixed on the NICOS side.
