### ISSUE TITLE
BLOCKSERVER : Changing COM port on SE device did not work [Timebox 1day]

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3367]
In changing the COM port on a SE device, the ioc kept talking to the original COM port i.e. it does not swop to the new COM port entered. 
Note : 
Example: Eurotherm and TTIPLP iocs.
IOC was running at the time - if stopped, then config edited, things did appear to work correctly.
Simple edit to the existing configuration - no components.
Might be a race condition between the edit and the ioc restart.

**Comment by GDH-ISIS** [comment]
Actually, I am not convinced the IOC is asked to restart ... so it is not a fair race after all.

**Comment by donpatrice** [comment]
Checking the both check boxes Auto-start and Auto-restart I cannot reproduce the issue.

**Comment by Tom-Willemsen** [comment]
I think this happens by using the following workflow:
- Create an empty config with any IOC on it talking on COM port A
- Set both autostart and autorestart to OFF
- Start the IOC manually (via the IOC menu or a console)
- Edit the config to talk on COM port B
- The IOC does not get restarted, so the new com port setting is not applied
- When the IOC is next manually restarted, it picks up the new setting

I believe this is a conscious decision. The user manual says
> Auto start: If set, the IOC will be started/restarted whenever the configuration is changed.

i.e. if auto-start is **not** set then the IOC will **not** be started/restarted when the config is changed and so will not pick up any new macro settings.

**Comment by John-Holt-Tessella** [comment]
I have updated it to:

`  - Auto start: If set, the IOC will be started/restarted whenever the configuration is changed. If not set then if the IOC is not running it will remained stopped after config change, if it is running it will remain running throughout the config change. (Warning: if not set and the IOC is running any changes you make, e.g. a macro change, will not be set on the IOC until you restart it manually.)`

see https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Create-And-Manage-Configurations
