### ISSUE TITLE
EnginX Galil IOCs not loading

### ISSUE THREAD

**Issue by IainJohnson** [ISISComputingGroup/IBEX#3368]
As a Motion Stop / light curtain / bumps strip functional testing operative, I need to be able to prove motion before and after my tests.

EnginX IBEX server was not running, launched server from command line, re-started client, Galil motors did not connect, started all the Galil IOCs from the IOC menu, still would not connect, re-started the client again, no luck.

**Comment by IainJohnson** [comment]
As a Motion Stop / light curtain / bumps strip functional testing operative, I need to be able to prove motion before and after my tests.

EnginX IBEX server was not running, launched server from command line, re-started client, Galil motors did not connect, started all the Galil IOCs from the IOC menu, still would not connect, re-started the client again, no luck.

**Comment by IainJohnson** [comment]
@GDH-ISIS Gareth has kindly explained the motors are done differently on Engin X, routed via matlab TOM below IBEX, this is why restarting the Galil IOCs did not work for me.

**Comment by kjwoodsISIS** [comment]
@GDH-ISIS's explanation has clarified the problem.  No further action required.  Issue can be closed.
