### ISSUE TITLE
NICOS: Clearly display name of currently executing script

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3369]
As a user of the script server, I would like the name of the currently executing script to be clearly displayed on the perspective.  At the moment, it is only shown in the output box surrounded by other text.

Suggest displaying the name next to the title of the box showing the script's contents.  e.g:

![image](https://user-images.githubusercontent.com/10550207/43080355-7e65b926-8e87-11e8-9906-700e53a7177c.png)

May also be worth considering displaying the name (and/or NICOS status) in the banner so that it can be seen when viewing another perspective.

**Comment by LiamPanchaud** [comment]
Difficult to continue due to NICOS not providing currently running script's name. 

Branch created: https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3369_Display_name_of_executing_nicos_scripts

**Comment by kjwoodsISIS** [comment]
Surely we can know the name of the script prior to it being submitted to the ScriptServer?
   1. If the script is to be loaded from file, it is the name specified the user.
   1. If the script has been created from scratch (and has not been saved prior to being submitted), then we can use "Untitled" (or similar).

**Comment by John-Holt-Tessella** [comment]
Sadly we have to get the name of the currently running script from the script server. Remember it may not have come from our GUI. We may not have seen it going into the queue.

**Comment by DominicOram** [comment]
NICOS have put this update in for us at https://forge.frm2.tum.de/review/#/c/18801/
