### ISSUE TITLE
Implement a "tray icon" to re-start IBEX server

### ISSUE THREAD

**Issue by IainJohnson** [ISISComputingGroup/IBEX#3370]
As a generic EEUSG/motion person doing shutdown work, I sometimes arrive at an instrument where IBEX server is not running. This is not always obvious, if the client is running it might say 'simulation', but I'm not sure if this is a good indicator. Could this be clearer?
The server can be launched from a batch file in the Instrument Epics Apps, but this requires some  command-prompt know-how.  Instead, could the client detect the server not running, and launch the server itself?

**Comment by John-Holt-Tessella** [comment]
The client in general should probably not be able to start the server. The client and server a quite separate and should remain so. However there should be a better indication that the server is running or not and start/stopping the server should be easier. Something like a tray icon indicating the servers readyness.
For now you know the server is running if the dashboard is showing anything but unknown or the current config is anything but unknown.

**Comment by ChrisM-S** [comment]
I sort of agree, as remote clients would not be able to start a remote server anyway... but there is very little case for a client running on an active instrument system without a server for an ordinary user...  The logical thing might be to make the client start button on the toolbar run a script to check/start the server if it is not running.  The tray icon could also provide shutdown and restart options for the server on a right-click.

**Comment by kjwoodsISIS** [comment]
After discussion we have decided that the client should not re-start the server.
Chris's suggestion of the tray icon is more appropriate.

**Comment by KathrynBaker** [comment]
There is usually a pinned file to start the server, and there is an indicator of whether the server is up or partially up with greater details as to what may be faulty, this may still be useful, but feels unnecessary. Reopen if you disagree with me.
