### ISSUE TITLE
Migrate to Java 11

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3378]
As a developer, I want to migrate IBEX to run on Java 11, so that it will not be dependent on an unsupported version of Java (which is at risk of being deemed insecure).

#### Acceptance Criteria
1. IBEX is updated to use Java 11.
1. IBEX client is bundled with Java 11.
1. IBEX server is bundled with Java 11 (see #3392).
1. A Java 11 version of IBEX is ready for Cycle 2018/03 (13/11/2018 - 18/12/2018)

#### Notes
1. parent of #3392 
1. Oracle have moved to a [new release & support model](http://www.oracle.com/technetwork/java/javase/tech/eol-135779.html).
   1. From January 2019, Oracle will no longer make updates to Java 8 available to Commercial Users.
   1. ISIS (and more generally STFC) fall inside Oracle's definition of Commercial Users (being an academic institution is not relevant in this context).
   1. Oracle will release of new versions of Java every 6 months.
   1. Once an existing version of Java has been superseded by a new one, the existing version becomes unsupported (i.e. no bug fixes, no security fixes, etc.)
   1. Oracle will designate some versions of Java as "long-term support" (LTS).  LTS is only available if you pay for it.
1. Java 11 will be released in September 2018.  Java 11 will be the first LTS version of Java.
1. There is no point in migrating first to Java 9 and then Java 10. Java 9 is already obsolete - it was superseded by Java 10 in March 2018.  Java 10 will be made obsolete by Java 11.
1. Once a version of Java becomes unsupported, it will no longer be updated to take account of new security threats.  Therefore, it is certain that, sooner or later, STFC's central IT function will declare it to be insecure and require it to be replaced with a secure version.  We need to be ready for such event.
1. In case you are wondering, this scenario will recur roughly every 6 months (in step with each new release of Java).  We should take steps now to make life easier for ourselves in future.
1. Bundling Java with both IBEX client & server has some advantages:
   1. we control which version of Java is used; we no longer have to worry about which other versions of Java the user might have installed.
   1. we control when IBEX moves to the next version of Java.
   1. the Java auto-update feature will be redundant (Oracle will remove it).
1. We do, however, need to be mindful of how well Eclipse 4 and/or CS-Studio 4 support Java 11 (and, in due course, future versions of Java).  This could put a limit on how fast we can move to each new version of Java.

**Comment by Tom-Willemsen** [comment]
> We do, however, need to be mindful of how well Eclipse 4 and/or CS-Studio 4 support Java 11 (and, in due course, future versions of Java). This could put a limit on how fast we can move to each new version of Java.

Indeed,  eclipse itself (the IDE) does not support java 11 currently - it is highly unlikely that we will be able to use java 11 before eclipse can. Look at https://bugs.eclipse.org/bugs/show_bug.cgi?id=531708 (and it's dependencies) to track eclipse's progress towards java 11 support.

**Comment by DominicOram** [comment]
CS-Studio are also looking to potentially skip 9/10 and move on to 11. However, they are stuck on a number of external dependencies, which are still on 8. If we're to do this we should leverage the work they've been doing, Will Rogers will know more.

**Comment by ChrisM-S** [comment]
Doesn't `6.ii` operate exactly the other way if we bundle Java?
i.e.  We must release a complete version of IBEX(+Java) at the time any deployed version of IBEX(+Java) is deemed insecure because Java is no longer a supported version (a criteria made in our update policy).
Are we considering paying for the LTS branch?

**Comment by kjwoodsISIS** [comment]
The rationale behind this ticket is to migrate to Java 11 _before_ Java 8 becomes unsupported (and subsequently to migrate to Java N+1 before Java N becomes unsupported - provided such a thing is feasible (Oracle says future steps from Java N to N+1 will be small (much smaller than, say, the step from Java 7 to Java 8)), so individual migrations might be fairly simple).  In this sense, we control when IBEX moves to the next version of Java.

We could consider paying for LTS.  But to find out more, such as the actual cost, requires talking to Oracle.  Do we have an existing support account?  If so, who controls it?  Who is responsible for ISIS's/STFC's relationship with Oracle?

**Comment by Tom-Willemsen** [comment]
- Client now moved to java (openjdk) 11
- Server still on java (openjdk) 8 as CSS can't be built on 11 yet and we need some of their tools for the server (e.g. AlarmServer, AlarmConfigTool, ArchiveEngine, etc.)

**Comment by DominicOram** [comment]
Everything is now on Java 11
