### ISSUE TITLE
LOQ: IOC & OPI for OMEGA™ iBTHX transmitter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3379]
As a scientist, I want an IOC & OPI for a OMEGA™ iBTHX transmitter, so that I can monitor & log ambient temperature, pressure & humidity in my experiments.

#### Acceptance Criteria
1. I can add/delete a OMEGA™ iBTHX transmitter from my configurations.
1. There is an icon for the OMEGA™ iBTHX transmitter (may need to invent one).
1. I can control a OMEGA™ iBTHX transmitter via the IBEX GUI.
1. I can control a OMEGA™ iBTHX transmitter via genie_python.

#### Notes
1. Check the functionality provided by the existing SECI VI.  We should provide equivalent functionality.
1. The OMEGA™ iBTHX transmitter is a monitoring & recording device (so limited in what can be set).
1. Information about [OMEGA™ iBTHX transmitter](https://www.omega.co.uk/pptst/IBTX_IBTHX.html).
1. SANS2D & INTER also use OMEGA™ iBTHX transmitters.

**Comment by FreddieAkeroyd** [comment]
It looks to be driven by commands over TCP, so should be a simple Stream Device driver

**Comment by GDH-ISIS** [comment]
Note : I had trouble with this device communicating reliably. I am surprised they are still using it. 

LabVIEW driver located in C:\LabVIEW Modules\Drivers\Omega iBTHX. 
Documentation located in C:\LabVIEW Modules\Drivers\Omega iBTHX\Documentation

Initially used on SANS2D I believe.

**Comment by Tom-Willemsen** [comment]
To elaborate slightly on Gareth's comment above:

The device is faulty from a communications perspective. This is a fundamental problem (getting thrown off a TCP port) rather than a driver-specific problem - so it will occur regardless of whether we use the labview driver or a pure epics solution. As such, we can only get a response from the device every so often (for example, getting values every 5-20 minutes, despite polling continuously). 

I think we need to talk to the scientist(s) to see if:
1. They don't use it. Great, we can just get rid of it.
1. They use it but they don't mind that it is unreliable. This is ok, we can produce an EPICS driver with broadly similar reliability to the labview
1. They use it and require it to be reliable. We should discuss with them what their plans are for replacing the device.

I will assume (2) for now until Steve King is back, and then ask him what the state of play is for this device.

**Comment by kjwoodsISIS** [comment]
I am meeting with Steve King on Monday, 6th August 2018.  I will ask him about it then.

**Comment by Tom-Willemsen** [comment]
After discussion with @Kevin-Woods-Tessella , park this ticket until after discussion with Steve King, to make sure we have an actual requirement for this.

**Comment by FreddieAkeroyd** [comment]
I'm not sure if the one in the office thinks it has a sensor? I got consistent answers using the httpget approach on port 1000 but the answer was always "serial timeout". Maybe it needs a firmware update?

**Comment by Tom-Willemsen** [comment]
Hi Freddie, the one in the office definitely has a sensor as I have had sensible numbers out of it.

"Serial timeout" is one of it's failure modes - the other failure mode is kicking you off the connection / refusing to connect entirely. I've seen it say "Serial timeout" consistently-ish for 20+ minutes, after which it might either start replying (occasionally) or disconnect you (more likely)

You can see it's configuration by navigating to it's IP address and port 80, but only using IE - modern browsers didn't work for me

**Comment by John-Holt-Tessella** [comment]
Putting back into backlog no longer needed for LOQ. Branches started are:

- https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket3379_Add_IOC_OMIBTHX 
- https://github.com/ISISComputingGroup/EPICS/tree/Ticket3379_Add_IOC_OMIBTHX
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket3379_Add_IOC_OMIBTHX
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/tree/Ticket3379_Add_IOC_OMIBTHX
- https://github.com/ISISComputingGroup/EPICS-Omibthx/tree/Ticket3379_Add_IOC_OMIBTHX

Communication is sporadic. Prefer uses a different device if possible for this.

**Comment by kjwoodsISIS** [comment]
LOQ will use a nanoDAC instead of the OMEGA™ iBTHX transmitter.  I suspect we'll adopt the same approach for other instruments that use the OMEGA™ iBTHX transmitter, so closing this ticket.  We can open a new ticket if someone really insists on using a OMEGA™ iBTHX transmitter.

**Comment by radio-dave** [comment]
Just activated Omega's marketing VP by explaining the issues with the iBTHX. Omega engineering was lit up and is now actively looking into these issues. If they falter, this thread may help.
