### ISSUE TITLE
ISISDAE: link to liveView OPI

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3381]
The ISISDAE IOC needs to be configured to generate appropriate data for #2230 - this infrastructure is already in the support module and just needs enabling.

Document this process,

**Comment by FreddieAkeroyd** [comment]
Also need to create count rate PVs for whole and per pixel, basically make it have everything that the LOQ and SANS2D live view have. The count rate PVs need adding to the OPI too.

**Comment by FreddieAkeroyd** [comment]
log or linear scale, new or changed counts, display update rate

**Comment by FreddieAkeroyd** [comment]
...and may need to rotate or flip detector

**Comment by John-Holt-Tessella** [comment]
For the release this may need to be patched in later if it is not ready in time.

**Comment by Tom-Willemsen** [comment]
In the presentations so far we have been saying that the live view is coming in time for start of cycle. If this is getting pushed back, should we be holding off from telling people about it?

**Comment by FreddieAkeroyd** [comment]
Using the liveview device screen you should be able to add a view with DET macro as 1 or 2

Livewview PVs have a root at %MYPVPREFIX%DAE:AD1 and %MYPVPREFIX%DAE:AD2

You need to tell it the spectra to use for the liveview

caput %MYPVPREFIX%DAE:AD1:INTG:SPEC:START:SP 11
caput %MYPVPREFIX%DAE:AD1:SizeX 80
caput %MYPVPREFIX%DAE:AD1:SizeY 80

will tell it to start from spectrum 11 and use consecutive spectra as an 80x80 grid

Liveview is disabled by default, it is enabled with

caput %MYPVPREFIX%DAE:AD1:INTG:ENABLE:SP 1

depending on the number of spectra, MAX_ARRAY_BYTES may need adjusting

**Comment by DominicOram** [comment]
Can you update the documentation on how to test this at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Live-View
