### ISSUE TITLE
LARMOR: IOC & OPI for Anton-Paar DMA4500 densitometer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3382]
As a scientist, I need an IOC & OPI for a Anton-Paar DMA4500 densitometer, so that I can control the device in my planned NURF experiment.

#### Acceptance Criteria
1. I can control the Anton-Paar DMA4500 densitometer from the IBEX GUI
1. I can control the Anton-Paar DMA4500 densitometer from genie_python
1. Solution to be ready for Cycle 2018/03 (experiment is scheduled for 14th December).

#### Notes
1. Information on [DMA™ 4500 M density meter](https://www.anton-paar.com/corp-en/products/details/dmatm-4500-m-density-meter/).
1. The NURF experiment originates in some work done at ESS.  There is already some existing code for the Anton-Paar DMA4500 densitometer: see https://bitbucket.org/europeanspallationsource/m-epics-dma4500m/src/master/.
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).
1. See also #3383 and #3384

**Comment by John-Holt-Tessella** [comment]
After quick review, I don't see how the protocol is ever found. When I look on Larmor there is a different set of files. Should these have been copied back into the repository?
I will wait to review until I have the answer.

**Comment by John-Holt-Tessella** [comment]
See #3922 for improvements
