### ISSUE TITLE
LARMOR: IOC & OPI for Ocean Optics TXR1-ES spectrometer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3383]
As a scientist, I need an IOC & OPI for a Ocean Optics TXR1-ES spectrometer, so that I can control the device in my planned NURF experiment.

#### Acceptance Criteria
1. I can control the Ocean Optics TXR1-ES spectrometer from the IBEX GUI
1. I can control the Ocean Optics TXR1-ES spectrometer from genie_python
1. Solution to be ready for Cycle 2018/03 (experiment is scheduled for 14th December).

#### Notes
1. The specific model of spectrometer is a UV Flame TXR1-ES spectrometer manufactured by [Ocean Optics](https://oceanoptics.com/product-category/flame-series/).
1. **N.B.**  This device has a USB interface.
1. The NURF experiment originates in some work done at ESS.  There is already some existing code for the Ocean Optics TXR1-ES spectrometer: see https://bitbucket.org/europeanspallationsource/m-epics-qeproasyn/src/master/
   * This code should also be capable of controlling an Ocean Optics Fluorescence QEPro spectrometer (see ticket #3384 ).
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).

**Comment by DominicOram** [comment]
After discussion with @FreddieAkeroyd this was successfully supported by the same code as in https://github.com/ISISComputingGroup/IBEX/issues/3384. So I'm reviewing this as complete and will fully review the other one.
