### ISSUE TITLE
LARMOR: NURF Experiment

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3385]
As a LARMOR scientist, I wish to perform a NURF experiment in Cycle 2018/03 (scheduled for 14th December).
The NURF experiement requires support for a number of new devices.  This is an umbrella ticket for the NURF experiement.

- [x] requires #3262 
- [x] requires #3382
- [x] requires #3383
- [x] requires #3384
- [x] requires #3386 (may not be needed)
- [x] requires #3387
- [x] requires #3398

#### Notes
1. The NURF experiment originates in some work done already done at ESS.
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).
   * experiment will be performed on LARMOR
1. #3386 may not be needed.  Leave this ticket until last.

**Comment by FreddieAkeroyd** [comment]
Th experiment will now take place on LARMOR on 16th and 17th December (last two days of that cycle). There will be intervening meetings to confirm details of the work required.

**Comment by FreddieAkeroyd** [comment]
See \\ISIS\Shares\ISIS_Experimental_Controls\Manuals\NURF

**Comment by kjwoodsISIS** [comment]
I assume the NURF experiment is now complete, therefore, this ticket and it's sub-tickets should now be ready for review?

**Comment by DominicOram** [comment]
Moving into review as all required tickets are complete.
