### ISSUE TITLE
LARMOR: IOC & OPI for Ocean Optics DH-2000-BAL Light Source

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3386]
As a scientist, I need an IOC & OPI for a Ocean Optics DH-2000-BAL Light Source, so that I can control the device in my planned NURF experiment.

#### Acceptance Criteria
1. I can control the Ocean Optics DH-2000-BAL Light Source from the IBEX GUI
1. I can control the Ocean Optics DH-2000-BAL Light Source from genie_python
1. Solution to be ready for Cycle 2018/03 (experiment is scheduled for 14th December).

#### Notes
1. Information about the [Ocean Optics DH-2000-BAL Light Source](https://oceanoptics.com/product/dh-2000-bal/).
1. The NURF experiment originates in some work done at ESS.
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).
1. Not surprisingly, the DH-2000-BAL Light Source seems somewhat limited in its capability.  It appears to have the following states: ON or OFF and the shutter can be OPEN or CLOSED.
1. The DH-2000-BAL Light Source uses TTL control.

**Comment by FreddieAkeroyd** [comment]
A box to test this on should be ready by end of week, we will get a protocol document Wednesday

**Comment by kjwoodsISIS** [comment]
How many points?
