### ISSUE TITLE
LARMOR: IOC & OPI for Ocean Optics TTL Shutter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3387]
As a scientist, I need an IOC & OPI for a Ocean Optics TTL Shutter, so that I can control the light sources in my planned NURF experiment.

#### Acceptance Criteria
1. I can control the Ocean Optics TTL Shutter from the IBEX GUI
1. I can control the Ocean Optics TTL Shutter from genie_python
1. Solution to be ready for Cycle 2018/03 (experiment is scheduled for 14th December).

#### Notes
1. Information about the [Ocean Optics TTL Shutter](https://oceanoptics.com/product/electronic-shutters/).
1. The NURF experiment originates in some work done at ESS.
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).

**Comment by FreddieAkeroyd** [comment]
There is now a box produced by sample environment that we can use to control the shutter

**Comment by FreddieAkeroyd** [comment]
I think this may be covered by #3386

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd is this a duplicate then

Don't review until we know.

**Comment by John-Holt-Tessella** [comment]
It was covered by the other ticket/an SD test verses arduino solution so will not be used again.
