### ISSUE TITLE
Nicos: Load and Save scripts in the GUI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3391]
As an instrument scientist I want to load and save a python script which I have/will edit before sending it to NICOS so that I don't have to use an external editor and paste my script between windows.

NB. Check this requirement with an instrument scientist.

**Comment by John-Holt-Tessella** [comment]
Although I don't mind using external tool I get the impression there is a push from instrument scientists to have everything users need in a single application. Can someone correct me/support this view.

**Comment by Kevin-Woods-Tessella** [comment]
Yes, I agree - there is a desire (from some scientists, at least) to have everything users need in a single application.  However, we should be mindful of other priorities and other factors before we implement this request.
* Adding every feature the scientists request puts IBEX at risk of becoming bloated and unwieldy.  So it is reasonable to ask the question - "if another application can provide something equivalent, then why not use it?"  
* One could at least use the alternative application as a temporary measure, while we implement other more important features.  If Notepad++ is "good enough" as a stop-gap, then we should focus on other features first.  
* I suspect the desire to make IBEX into a "one-stop-shop" comes (in part, at least) from visiting scientists getting confused as to which application they should be using.  I think this is understandable, but there may be better ways of addressing the problem - perhaps better training for visiting scientists?
