### ISSUE TITLE
Bundle Java with IBEX Server

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3392]
As a developer, I want to bundle Java with IBEX Server, so that I can control which version of Java is used by IBEX.

#### Acceptance Criteria
1. Java is installed automatically when IBEX server is installed.
   1. In case it is not clear, Chris's suggestions (see comment below) are implied by this acceptance criterion.

#### Notes
1. Suggestion: install Java in `C:\Instrument\Java` (or similar location).
1. Given that, in future, Java will be updating every 6 months, we should aim to make it easy to replace old versions of Java with new versions.
1. required by #3378 
1. Again, as suggested by Chris, the bundled instance of Java is for the exclusive use of IBEX.  Other applications should not use it (instead, they should bundle their preferred version of Java with their own application).  Any application "piggy-backing" on IBEX's version of Java does so at its own risk.

**Comment by ChrisM-S** [comment]
I would be tempted to say in the acceptance criteria that.

1. A private version of Java is now part of the IBEX installation.
2. As with other parts of the IBEX software, an updated installation will replace the private Java version.

also an additional **note**
4. No non-IBEX other applications should have access to or even be able to find and use the IBEX private Java.  This is to prevent IBEX breaking something else when it updates its private Java!

**Comment by KathrynBaker** [comment]
We interact with Java quite differently now, and it is not installed on systems so by default I believe we are doing this.
