### ISSUE TITLE
Script Generator: revisit and plan way forward

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3394]
Now we have a working Script Server we need to revisit the script generator. Such a concept is used on several SECI instruments, of particular relevance would be LOQ which would likely count not having a script generator for users as a blocker to moving to IBEX. There are many existing tickets with "script generator" in the title e.g.  #1970  #1963  #1568  #1558 

This ticket should review the current state of the script generator and decide on the path ahead, maybe a meeting is best?

**Comment by Kevin-Woods-Tessella** [comment]
Yes, I agree, we should meet to review the current state-of-play.  I am not convinced that the existing Script Generator is worth keeping.  It may be worth starting afresh.  But I am open to persuasion.

**Comment by kjwoodsISIS** [comment]
We held a meeting and agreed to discuss new requirements with the scientists.
When we have clear, new requirements, our options are:
   1. create a new version of the stand-alone tool, MkScript (which can be used on-site or off-site)
   1. create a brand new stand-alone tool (which can be used on-site or off-site)
   1. create brand new tool which is integrated with IBEX (could not be used off-site)
Once we have requirements from the scientists, we'll create new tickets as appropriate.
