### ISSUE TITLE
LARMOR: IOC for LOTQD MSH150 Monochromator

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3398]
As a scientist, I need an IOC LOTQD MSH150 Monochromator, so that I can control the device in my planned NURF experiment.

#### Acceptance Criteria
1. I can control the LOTQD MSH150 Monochromator from the IBEX GUI
1. I can control the LOTQD MSH150 Monochromator from genie_python
1. Solution to be ready for Cycle 2018/03 (experiment is scheduled for 14th December).

#### Notes
1. The NURF experiment originates in some work done at ESS.
1. This is a "nice to have" for the NURF experiment, will add more details after meeting with people involved.
1. Control via the IBEX GUI will likely be as part of another OPI.
1. The manual for the LOTQD MSH150 Monochromator is located at \\\isis\shares\ISIS_Experimental_Controls\Manuals\LOTQD-Monochromator-MSH150
1. [Background to experiment](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLarmor%2FNURF%20Experiment&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) on LARMOR (or ZOOM).

**Comment by John-Holt-Tessella** [comment]
IOC refers to `C:/Users/Public/Documents/LOT/Monochromator Control/Configurations/ccgData_LOT_MSH-150_SN25606.xml` do we need this file?

**Comment by John-Holt-Tessella** [comment]
See #3919 for improvements

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella the monochromator has a USB connection and so will never be installed on an NDX computer, the /users/public is where the vendor installer puts it, i'm not sure if there is any option to change that. The IOC will run in simulation mode and i have put a workable tst XML file in the IBEX support module. 

LOT.substitutions is generated by the IOC on startup, it reads the XMl configuratiin of what is present and then creates it. So it will be there on the NURF laptop and also on an ibex machine after you have run the ioc.

**Comment by kjwoodsISIS** [comment]
If we have documented the required improvements in #3919, do we need this ticket to be in re-work?  If, and when, the LOTQD MSH150 Monochromator needs to be used again, we can implement #3919.

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella  and @FreddieAkeroyd I will capture that info on the web page for the device and then leave the rest on the ticket. (I need to build it first)
