### ISSUE TITLE
Motors: stop all button

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3399]
The stop all button for motors is permanently greyed out.

Investigate, fix, and add a system test for this.

**Comment by Tom-Willemsen** [comment]
The ticket, as written, is wrong, The stop all button does work in E4. 

The confusion was because the E3 client enables the button if the server is up, but the E4 client uses the stronger condition that the server is up AND the motors are moving.

**Comment by Kevin-Woods-Tessella** [comment]
Probably worth emphasizing this change when demonstrating the new release to scientists.

**Comment by John-Holt-Tessella** [comment]
I think this is not desirable; we should go back to E3's definition. I think it should be enabled at all times, so we can "stop" a non-moving motor. This means if the button misses a motor moving event it can still send a stop. It is also good for peace of mind that the button is lit so users always feel in control.

**Comment by Tom-Willemsen** [comment]
Discussed at stand-up, make the behaviour in E4 the same as E3.
