### ISSUE TITLE
Muon Kicker: Monitor Oscilloscope Trace

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3406]
As a muon scientist, I want to view the Kicker oscilloscope trace, so that I can monitor the voltage as a function of time.

#### Acceptance Criteria
1. I can view an oscilloscope trace of the Kicker voltage.
   1. I can switch the timebase of the oscilloscope trace between long and short

#### Notes
1. required by #3071
1. The Oscilloscope attached to the Kicker PSU is a Tektronix TDS 3014C.
   * Web page: https://uk.tek.com/oscilloscope/tds3000
   * EPICS Support: https://epics.anl.gov/modules/instrument/tds3000/R2-4/tds3000Device.html
1. Tektronix TDS 3000 series oscilloscopes have a built-in web-server, which can display the oscilloscope trace (see manual).  It might be acceptable to simply display the image served up by the web-server.

**Comment by davidkeymer** [comment]
We have an IOC and OPI for a Tektronix MSO 4104B oscilloscope which may act as a basis for this ticket if the command set is similar.  They (only) provide the ability to read the traces as waveforms and plot them in an OPI.

https://github.com/ISISComputingGroup/EPICS-Tektronix_MSO_4104B

**Comment by Tom-Willemsen** [comment]
Is it possible to get hold of the hardware (e.g. in our office)? If not, it is possible to get access to the hardware in place on the beamline? Who would I contact to get permission/details about this?

I think displaying the trace from the webpage that the scope publishes is an approach worth trying - but I would need access to the hardware to check if this is a viable approach

**Comment by FreddieAkeroyd** [comment]
The EPICS code for the TDS3000 is merged in our build, James has assigned an IP address for the TD3000 on the beamline that we can use to test (i'll put the ip address in an email)

**Comment by FreddieAkeroyd** [comment]
Basic IOC in https://github.com/ISISComputingGroup/EPICS-tds3000/tree/master/iocBoot/iocscope for testing

**Comment by Tom-Willemsen** [comment]
Hi Freddie - do we need a full IOC for this? Using the scope's built-in webserver I can quite easily display what is on the screen of the scope e.g.

![image](https://user-images.githubusercontent.com/24375813/44198620-d0050d80-a139-11e8-9437-5e6d32dde491.png)

We can try to implement an equivalent screen in CSS using the IOC you've linked above, but if all they want to do is see the trace, I'm wondering whether that's necessary?

**Comment by Tom-Willemsen** [comment]
The web interface lets you load & save arbitrary "instrument setups", as well as tweaking any parameters via arbitrary commands. I think this adequately covers the requirement to "switch between long and short timebase modes".

To review this ticket, you will need the IP address of the scope, which I have put on the sharepoint site in the MUONFE folder.
