### ISSUE TITLE
GUI: Address list in DIIRT config

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3419]
Check the address list in the diirt config in the GUI to make sure it is correct. Worried that it is not the same as the one in EPICS base. This may meaning running the client over edurome.

**Comment by FreddieAkeroyd** [comment]
In EPICS base specifying an auto address list and a manual address list will add the two together, we just need to make sure:
* Loopback is included
* If we are on a non-isis network we add  130.246.39.152:5066
It doesn't matter if we add 130.246.39.152:5066 on an ISIS network as i firewalled this off, so it mayu just be a matter of setting 130.246.39.152:5066 as the address list and leaving auto enabled.

To test, without 130.246.39.152:5066 the client should fail to work on WiFi / VPN or Eduroam

**Comment by FreddieAkeroyd** [comment]
Though "auto address enabled" will work, it is not a good idea on an NDX computer as it will potentially broadcast to the 192.168 private network. This is likely why the one in EPICS base is set the 
way it is, I forgot about the client on NDX when commenting above.
