### ISSUE TITLE
GUI: What to do if the server is not started

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3420]
As a developer I need to know what the GUI should do if the server is not started so that I can program it. Gather idea and decide.
If it is quick to implement, implement otherwise create a ticket and prioritise.

**Comment by LiamPanchaud** [comment]
After a discussion (between me, @DominicOram, and @John-Holt-Tessella) it was decided to display a message in the blocks view when the blockserver is unavailable/disconnected/etc.

**Comment by LiamPanchaud** [comment]
PR:

https://github.com/ISISComputingGroup/ibex_gui/pull/780

**Comment by LiamPanchaud** [comment]
Note that there is an edge case when the message interacts badly with a blocks view that _only_ contains hidden blocks. I discussed this with @John-Holt-Tessella and we decided that this would virtually never happen for users since they will always have visible blocks in the view.
