### ISSUE TITLE
build_ioc_startups.py doesn't search for IOCs in directories other than master

### ISSUE THREAD

**Issue by donpatrice** [ISISComputingGroup/IBEX#3422]
When I have a directory in C:\Instrument\Apps\EPICS\ioc\tests build_ioc_startups.py doesn't look for IOCs inside there. Even worse the script stops with a KeyError, when there is an even empty directory beside master.

I cannot remember why, but I had a test directory there, it must has been created automatically. So wouldn't it be better to search in all sub-directories of ioc?

**Comment by donpatrice** [comment]
At least it shouldn't stop with a KeyError when there are other directories beside master.

**Comment by John-Holt-Tessella** [comment]
This has caused a bug the file `EPICS\iocstartup\procserv.bat` no longer contains all IOC proc serves e.g. ISISDAE_01. Compare build 310 to latest.
