### ISSUE TITLE
Galil : Home routine that does nothing

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3423]
As a developer and user, I would like to be able to define a homing routine for an axis that does nothing and does not redefine the axis position at the end. This effectively defines the axis homing routine as disabled.

Would it please be possible to add the attached homing routine to the Galil driver.

NOTE : At this point in time, this has been added to CRISP manually already so that the axes can not be re-defined by requesting a homing routine.

**Comment by GDH-ISIS** [comment]
Please find attached homing routine.

[galil_Home_No_Home.zip](https://github.com/ISISComputingGroup/IBEX/files/2254043/galil_Home_No_Home.zip)

**Comment by John-Holt-Tessella** [comment]
Can @FreddieAkeroyd review. Does this returned not homed? I can't tell

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella  it sets   homed${AXIS}=0   at the end to indicate homing failure/incomplete, other routines set    homed${AXIS}=1     to indicate success. The Galil IOC will only apply a home position if homed${AXIS} == 1  after running the routine so I think it is all good.
