### ISSUE TITLE
SUPPORT: Danfsik on Larmor

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3424]
An instrument scientist on LARMOR has reported that the Danfsik does not work for him. Freddie has spotted a problem in the globals.txt and thi si snow fixed but has not been tried. The instrument scientist will try to use it this shutdown.

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella , @FreddieAkeroyd - has the test been done?  Is this ticket still impeded?

**Comment by John-Holt-Tessella** [comment]
We have asked Rob to confirm and he has not come back to us. Rob has not complained so we assume it is ok. Closing
