### ISSUE TITLE
Live View: Create separate view to give X and Y profiles

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3427]
As a user I would like to be able to plot an X or Y profile of my live view. CS-Studio has a method to do this, which can be seen in their intensity plot examples. This should be a separate view available to users so as not to clutter the vanilla live view.

**Comment by kjwoodsISIS** [comment]
I can see some users wanting to have the profile displayed next to the live view itself (one horizontal, the other vertical).  Perhaps there is a need for both types of display?

**Comment by DominicOram** [comment]
Sorry if I wasn't clear, that's what I meant by this ticket. This is how it looks in CSS: 
![image](https://user-images.githubusercontent.com/10086797/43714576-581345a6-9975-11e8-8d34-3b42b12d412c.png) The yellow lines can be dragged around to see the profiles.

**Comment by DominicOram** [comment]
But they also wanted a view that was just the picture, no profiles.

**Comment by Kevin-Woods-Tessella** [comment]
OK, cool.  I think we're on the same page.  :-)
