### ISSUE TITLE
PROCESS: Add preflight checks to device_generator

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3431]
As  a developer I can sometimes get causght out with the device generator script when my git repo is not in the expected state fix this with a check that it is.

Things to fix:

1. Repo that is being branched must be in master and up-to-date and not in about to merge state
1. Files must be added individually not with the `-A` glag
1. Check that resetting a name for the IOC works throughout.

**Comment by GRyall** [comment]
This ticket is no longer relevant following the creation of the [device-generator](https://github.com/ISISComputingGroup/IBEX-device-generator)  and deprecation of the device_generator
