### ISSUE TITLE
MK3 Chopper IOC: Update with new DLL

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3432]
The MK3 chopper servers have recently been updated with a new version of the communications DLL (v8.4 to v8.6).  The IOC will therefore also need to be updated to restore communications with the servers.

The new DLL is located in the chopper VI area of SourceSafe, but is also present on selected instruments after initial testing.

**Comment by davidkeymer** [comment]
To check a version of a DLL in Windows Explorer, right-click on the file and select "Properties", then the "Details" tab.  This will show the version of the DLL in the displayed table next to "Product version".

**Comment by LiamPanchaud** [comment]
PR:

https://github.com/ISISComputingGroup/EPICS-mk3chopper/pull/5
