### ISSUE TITLE
LOQ: Connect front-end TPG to MOXA

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3433]
As a LOQ scientist, I would like the pressure readings from the front-end TPG to be available via IBEX.

#### Acceptance Criteria
1. Front-end TPG to be connected to LOQ MOXA
1. IBEX to be configured to collect data from the front-end TPG

#### Notes
1. LOQ has three TPGs - detector tank, detector tank pump, front-end (monitoring the collimation).  See [LOQ Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details#noteVacuum) for more information.
   1. At present (August 2018) only the detector tank and detector tank pump TPGs are connected to the MOXA (and thus, can currently be read by SECI).
   1. The front-end TPG does have a serial card, so there is no reason why it cannot also be read.
1. IBEX can be configured to collect data from the front-end TPG when LOQ is migrated to IBEX.

**Comment by John-Holt-Tessella** [comment]
Done as part of controls
