### ISSUE TITLE
SUPPORT: Wish can not start a simulated run

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3435]
Wish could not start a simulated run. It complained that cards were not detected. I followed the instructions in the trouble shooting and added.

```
isisicp.simulation.detcards.crate0.number = 10
isisicp.simulation.detcards.crate1.number = 10
isisicp.simulation.detcards.crate2.number = 12
```
to isisicp.properties.

Originally:

```
isisicp.simulation.detcards.crate0.number = 10
isisicp.simulation.detcards.crate1.number = 6
```

Acceptance Criteria:

This is ok and does not need to be reverted.

**Comment by John-Holt-Tessella** [comment]
To be reviewed by someone who understands this.

**Comment by kjwoodsISIS** [comment]
Why is this an IBEX issue?  WISH currently runs SECI.  Surely this should be a [ControlsWork](https://github.com/ISISComputingGroup/ControlsWork/issues) issue?

**Comment by FreddieAkeroyd** [comment]
Thank you @John-Holt-Tessella for doing that, the procedure on the ibex wiki equally applies to seci instruments and was the correct thing to do. In the case of an instrument like WISH i would also recommend

isisicp.simulation.detcards.shared = true

which I think was already present in the wish isisicp.properties file. Each simulated card takes 128MB of real memory, so on wish it would grab an extra few GB which it could  probably handle, but be a bit of a waste. the shared=true makes all simulated cards use the same 128MB, which means you have less options for data simulation, but simulated data is disabled by default on instruments anyway.
