### ISSUE TITLE
GUI: Review icon crediting

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3439]
As a developer I would like to make sure icons I use are properly credited.Most of our icons are used under https://creativecommons.org/licenses/by/3.0/. In E3 we credited authors in a comment next to the code. These comments have been removed in E4. We should come up with a policy on how we do this in E4 and implement it.

**Comment by LiamPanchaud** [comment]
There's a licensing section in `ibex.product` which is where I put the credit for an icon I used for the scripting server. There was alread an icon credit in there (in HTML, not sure why) but as far as I can tell it doesn't specify which icon it's for. There are some other licenses in `p2content.xml`.

**Comment by LiamPanchaud** [comment]
Branch: https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3439_icon_crediting

PR: https://github.com/ISISComputingGroup/ibex_gui/pull/809#
