### ISSUE TITLE
Riken PSU / DAQ / Changeover tests

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3440]
Test all riken changeover sequences / PSUs / DAQs in place on the riken beam line with Tim Carter.

**Comment by KathrynBaker** [comment]
How does this ticket differ to #3314? (Other than length)

**Comment by Tom-Willemsen** [comment]
Testing with Tim Carter complete.

Changes required on our end:
- [ ] I've lowered the reply timeouts in the protocol to 100ms and increased the lock timeout to 10s for the power supplies. This is because switched off power supplies won't reply and we don't want to wait around too long for a reply which isn't going to show up. Seems that stability is improved with these timeouts.
- [ ] DAQMX scan rate is too high - lower it
- [ ] The danfysik OPI depends on the presence of `IS_CALIBRATED` and `IS_BIPOLAR` records to know what to display. Add these to riken PSU dbs
- [ ] The OPI needs some power supplies renaming to match the convention used by Tim on the PLC.
  * [ ] `XFn` should be renamed to `XFDn`
  * [ ] Don't talk to `SEP` power supplies
  * [ ] `RB2-2` has appeared. This is a semi-imaginary power supply which is only used in septum mode (because BEND1 and BEND2 modes only require 1 current, which is provided by RB2, whereas SEPTUM requires two currents)
  * [ ] `RQ21`, `RQ22` and `RQ23` are fake power supplies that are really just `RQ18`, `RQ19` and `RQ20` in a different mode (port 4 vs port 3)
- [ ] For the RB2 mode change sequence, need to check the status of both `RB2` and `RB2-2`

I've done most of these patches on RIKENFE, they just need putting back into git so that IBEX can be built and installed on RIKEN in ticket #3314

**Comment by FreddieAkeroyd** [comment]
What happened about "stop bits" in the end?

**Comment by Tom-Willemsen** [comment]
Using either 1 or 2 stop bits seemed equally consistent so I left it set as 2.

**Comment by FreddieAkeroyd** [comment]
The average of 1 and 2 is of course 1.5 stop bits :-D

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/119
- https://github.com/ISISComputingGroup/EPICS-DAQmxBase/pull/4
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/309
- https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/8
- https://github.com/ISISComputingGroup/ibex_gui/pull/785

Documentation:
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Riken-power-supplies
