### ISSUE TITLE
Setup NDXSCIDEMO

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3441]
The new NDXSCIDEMO VM is now ready, it just needs IBEX installing to be usable by scientists wishing to play around with e.g. the new E4 interface in a test computer  environment

**Comment by FreddieAkeroyd** [comment]
See #3316

**Comment by Tom-Willemsen** [comment]
Done and details given to scientists after first set of presentations

**Comment by DominicOram** [comment]
I used NDXSCIDEMO as part of last E4/NICOS training, works as described
