### ISSUE TITLE
Update Training Material for new release of IBEX 

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3442]
As a user, I want the the IBEX Training Material to reflect the new capabilities of IBEX, so that I can be trained in the new version of the IBEX.
#### Acceptance Criteria
1. Introduction to IBEX is updated for new release of IBEX Client.
1. Scripting with genie_python is updated with material for using genie_python with ScriptServer.

#### Notes
1. Need to include material on:
   1. moveable windows and how to restore default layout.
   1. Graphing & scripting
   1. LiveView
   1. ScriptServer.  For example,
      1. explain difference between local and remote execution of scripts.
      1. "gotchas" (i.e. common errors)
      1. can't create graphs using ScriptServer

**Comment by Rory-Potter-Tessella** [comment]
Pages updated (in progress):

- [IBEX GUI Features](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/IBEXGUIFeatures)
    - Uploaded a new IBEX schematic.
    - Added Banner section to replace status bar and notification banner.
    - Removed StatusBar and NotificationBanner pages.
- [Banner](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Banner)
- [Menu Bar](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/MenuBar)
- [Views](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Views)

**Comment by Rory-Potter-Tessella** [comment]
To review this ticket, please check:

- [ ] Material on movable panels can be found in views.
- [ ] Material on graphing and scripting can be found on the scripting page and matplotlib page.
- [ ] Live View documentation is adequate on the Live View page.
- [ ] The script server is adequately documented on the script server page.
- [ ] All the links work correctly.
- [ ] The sidebar displays consistently on each page.
- [ ] The schematic for the IBEX UI has been updated for the E4 version of IBEX.
- [ ] The documentation changes have not adversely affected the copy of the user manual on shadow (can be found at http://shadow.nd.rl.ac.uk/ibex_user_manual/Home). Some pages on the shadow version of the user manual are broken, but this is outside the scope of this ticket - see [#3216](https://github.com/ISISComputingGroup/IBEX/issues/3216) for more details.
- [ ] The reorganization of the scripting material makes sense.

**Comment by donpatrice** [comment]
- The g.home link on https://github.com/ISISComputingGroup/ibex_user_manual/wiki/IMAT-motors#id1 is not working
- Some of the screen shots are hard to read, e.g. https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Script-Server. Is it possible to make them enlargeable?
- On some sites there are no contents at the top, that seems inconsistent. At least I was not able to figure out, when there should be a contents part and when not, e.g.
    - https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Converting-Open-GENIE-to-genie_python
    - https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Plot-a-Block-Graph
    - https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Matplotlib
-  What do you mean with
    > The reorganization of the scripting material makes sense.
    
    I cannot see big differences in the organization.

**Comment by LiamPanchaud** [comment]
Current rework changes: 

- Removed link highlighting [here](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/IMAT-motors#id1)

-  Made the [script server image](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Script-Server) clickable to see a larger image

- Reorganisation of Scripting in that it's been split into multiple pages instead of one huge one

**Comment by donpatrice** [comment]
All suggestions for improvements were addressed. Good job!
