### ISSUE TITLE
After using scipy.optimize in the python shell, using CTRL-C crashes the python session

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3443]
Reported by Adam Washington (LARMOR)

> Dear Tom,
> 
> I’ve been playing around with the new IBEX version and I’ve found an old bug that’s still haunting us.  Specifically, if you run the following three lines
> 
> import scipy.optimize
> while True:
>     pass
> 
> And then hit the yellow Ctrl-C button, the entire Python session crashes.  It seems to be related to the Intel MKL DLLs installing their own Ctrl-C handler that overrides the default Python one, as described at https://software.intel.com/en-us/node/678478 .  However, I’ve tried setting the environment variable via
> 
> os.environ['FOR_DISABLE_CONSOLE_CTRL_HANDLER'] = 1
> 
> And it doesn’t seem to register when loading the actual DLL.
> 
> I realise that this is only tangentially related to your original reasoning for the demo, but I wasn’t sure if there was an official place to submit tickets.  Plus, with the plotting functionality now working, not being able to use scipy’s curve_fit function becomes a much larger nuisance.
> 
> Regards,
> Adam
>

**Comment by Tom-Willemsen** [comment]
![image](https://user-images.githubusercontent.com/24375813/44148293-a5ce4568-a08f-11e8-91b4-e24166cd68c3.png)

**Comment by kjwoodsISIS** [comment]
I believe @FreddieAkeroyd has investigated the Intel MKL DLLs Ctrl-C handler problem.
Can we work around this with an alternative keystroke?  For example, Ctrl+Shift+C?

**Comment by rprospero** [comment]
@FreddieAkeroyd  The handler method seems to be working, with a small modification for the correct file paths

```
import ctypes
import os

def handler(sig):
    try:
        import _thread
    except ImportError:
        import thread as _thread
    _thread.interrupt_main()
    return 1
basepath = r"C:\Instrument\Apps\Python\Lib\site-packages\numpy\core"
ctypes.CDLL(os.path.join(basepath,"libmmd.dll"))
Out[9]: <CDLL 'C:\Instrument\Apps\Python\Lib\site-packages\numpy\core\libmmd.dll', handle ee450000 at aa07668>
ctypes.CDLL(os.path.join(basepath,"libifcoremd.dll"))
Out[10]: <CDLL 'C:\Instrument\Apps\Python\Lib\site-packages\numpy\core\libifcoremd.dll', handle ee2c0000 at aa07978>
routine = ctypes.WINFUNCTYPE(ctypes.c_int, ctypes.c_uint)(handler)
ctypes.windll.kernel32.SetConsoleCtrlHandler(routine, 1)
```

I think that we can call this one closed for now.

**Comment by kjwoodsISIS** [comment]
See also: [intel fortran DLL is klobbering my SIGINT handler!](https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/550628)

**Comment by Tom-Willemsen** [comment]
We should fix this more generally than just in the Larmor scripts - preferably in genie_python itself.

Genie python already runs some initialization code when it is first imported, can these handlers be installed at that point?

**Comment by FreddieAkeroyd** [comment]
Indeed, it should be part of genie_python startup. The python to install the new handler needs to be run after the intel fortran has replaced the existing handler, which is what the first two ctypes calls do by forcing a DLL load. However it looks like "import scipy.optimize" is enough to install the bad handler so just the final ctype call after an "import scipy.optimize" should be all that is needed in genie_python init

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/141
