### ISSUE TITLE
TOSCA: Prepare to Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3444]
As a developer, I want to complete the preparatory steps prior to migrating TOSCA to use the IBEX instrument control system.

**Note:** TOSCA has a full programme of experiments from the start of Cycle 2018/03 (13th November 2018 onwards).

#### Acceptance Criteria
1.  [x] Facilities IT have confirmed they will create a private network on TOSCA 
1.  [x] NDXTOSCA has sufficient free disk space to install IBEX 
1.  [x] IBEX has support for the devices used on TOSCA 
1.  [x] The version of the ICP program on TOSCA has been checked 
1.  [x] Configuration files matching the current SECI config files used on TOSCA are created 
1.  [x] TOSCA scripts are converted to genie_python
1.  [x] TOSCA configuration files and genie_python scripts are tested on a test instance of IBEX

#### Notes
1. The devices on TOSCA are listed on the [TOSCA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/TOSCA-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for TOSCA.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   -  [TOSCA VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/TOSCA/TOSCA_VLAN_Settings.txt)
- [x] Check that NDXTOSCA has sufficient disk space to install IBEX
  * TOSCA has 41.5-Gb of free space.
- [x] Check whether TOSCA uses 5- or 8- digit run-numbers
   - [x] If it uses 5-digit run-numbers, plan to upgrade the ICP program (to permit 8-digit run-numbers)
- [x] Create a virtual instrument for testing purposes
   - [x] Set up a test system, NDXTEST3.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [x] test these configurations & scripts
   - [x] check that all the devices previously supported by SECI (on TOSCA) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
   * Done!  Training arranged for 1st November 2018.

**Comment by John-Holt-Tessella** [comment]
Blocks used in Mantid:

>For TOSCA and OSIRIS there are a few names that are currently used but the scripts have also been recently updated so that the user can provide these names on the GUI if they need to so it won't be a drastic problem if they did change. The ones they currently use in scripts but I don't think are in every run are:
>
> - Sample
> - Position
> - Temperature
> - Bottom_can,
> - Middle_can
> - Top_can

**Comment by Tom-Willemsen** [comment]
Current TOSCA viewing machine monitor is very old and highly unlikely to be 1920x1080. Probably needs replacing for IBEX to display sensibly / usefully.

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - can you arrange for TOSCA to get a new monitor (as per Tom's comment above)?

**Comment by ChrisM-S** [comment]
Will do, have emailed and will chase.

**Comment by ChrisM-S** [comment]
I spoke to him about monitors and recommended he look at a Dell U2412M monitor which is now quite cheap.  This is one which still does the full 1920x1200 resolution (which was our standard before the popularity of 16:10 stole the extra menu bar space given by 16:9!).  Other details are listed below.

> Size: 24 inches
> Resolution: 1920 x 1200
> Display type: LED Backlit
> Connector type: HDMI, DisplayPort, VGA, DVI
> Maximum refresh rate: 60 Hz

**Comment by Rory-Potter-Tessella** [comment]
I have been trying to set up a McLennan motor (PM600) to control the rotating centre stick. Does someone know if this motor has an encoder? I can't see an encoder in the LabView code.

**Comment by Rory-Potter-Tessella** [comment]
When migrating TOSCA, the attached script needs to be run to set up the GALIL motors for the beam profiler.

[tosca_galil-setup.zip](https://github.com/ISISComputingGroup/IBEX/files/2525383/tosca_galil-setup.zip)

**Comment by Tom-Willemsen** [comment]
Check a few functions in `C:\Users\spudulike\Documents\Configurations\COMMON\gcl\tosca_routines.gcl` and check explicitly whether they need to be migrated. In particular:
- setup_50Hz
- setup_10Hz
- rephase
- rephase_loop
- Tosca's own version of waitformove

It may be that these are no longer relevant, but we should explicitly check.

Everything else looks good :)

**Comment by Rory-Potter-Tessella** [comment]
I have emailed the scientists asking if they still use any of the functions in `tosca_routines`.

**Comment by Rory-Potter-Tessella** [comment]
The scientists did not know about `tosca_routines.gcl` when I asked them today (2018-11-09) so these are no longer used.
