### ISSUE TITLE
TOSCA: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3448]
As an instrument scientist, I would like to use the IBEX instrument control system on TOSCA.
As a developer, I want to complete the migration of TOSCA to IBEX (see #3444).

#### Acceptance Criteria
1. [x] Preparations for migrating TOSCA to IBEX are complete (requires #3444)
1. [x] TOSCA scientists are trained in how to use IBEX
1. [x] An appropriate version of the ICP program is installed on TOSCA
1. [x] IBEX is installed on TOSCA.
1. [x] IBEX is configured for the devices on TOSCA.
1. [x] IBEX is tested on TOSCA.
1. [x] Demonstrate the migrated configurations & scripts (created above) to the instrument scientists.. Confirm they are happy with the migrated configurations & scripts.

#### Notes
1. The devices on TOSCA are listed on the [TOSCA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/TOSCA-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process.
1. Refer to #3444 to check whether the ICP program needs to be upgraded.
1. Scientists are usually invited to a training session a week or two before the migration takes place.
1. **Note:** TOSCA has a full programme of experiments from the start of Cycle 2018/03 (13th November 2018 onwards).

**Comment by Rory-Potter-Tessella** [comment]
I have emailed the scientists that IBEX has been installed on TOSCA and given them links to updated training slides and the moving between SECI and IBEX page on the user manual. 

I am meeting with Svemir on Friday to talk about the migration and the migrated scripts.

**Comment by Rory-Potter-Tessella** [comment]
I have met with the scientists and explained the changes made to TOSCA. They are happy with the changes made and the configurations.

They plan to run with SECI over the weekend before the cycle starts to use any beam they can get. They intend to start using IBEX on Monday for experiments.
