### ISSUE TITLE
INES: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3449]
As an instrument scientist, I would like to use the IBEX instrument control system on INES.
As a developer, I want to complete the migration of INES to IBEX (see #3445).

#### Acceptance Criteria
1. [x] Preparations for migrating INES to IBEX are complete (requires #3445)
1. [x] INES scientists are trained in how to use IBEX
1. [x] An appropriate version of the ICP program is installed on INES
1. [x] IBEX is installed on INES.
1. [x] IBEX is configured for the devices on INES.
1. [x] IBEX is tested on INES.
1. [x] Demonstrate the migrated configurations & scripts (created above) to the instrument scientists.. Confirm they are happy with the migrated configurations & scripts.

#### Notes
1. The devices on INES are listed on the [INES Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/INES-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process.
1. Refer to #3445 to check whether the ICP program needs to be upgraded.
1. Scientists are usually invited to a training session a week or two before the migration takes place.

**Comment by Rory-Potter-Tessella** [comment]
Remember to put the IBEX server boot script in the correct startup place. See #3661 and the [ibex auto start up wiki entry](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup).
