### ISSUE TITLE
Confirm which models of Julabo Water Bath are supported

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3451]
As a developer, I want to know which models of Julabo water bath are currently supported, so that I can create tickets for any models that are not yet supported.

#### Acceptance Criteria
1. Written statement of supported Julabo models
   * can state list of supported models in this ticket.

#### Notes
1. Models of Julabo water bath in use at ISIS are:
   * FP-50
   * FP-51
   * FP-52
1. Ultimate objective is to ensure all 3 models are supported.  If we find that a particular model is not (yet) supported, we will create a ticket to implement support.

**Comment by Tom-Willemsen** [comment]
I have compared the [spreadsheet on the wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Julabo) against the list of water bath models at ISIS at https://www.isis.stfc.ac.uk/Pages/Water-Baths.aspx (note that this is a significantly longer list than the three models mentioned above) .

We have support for:
- FP50-MH
- FL300

I believe we do **not** have support for:
- FPW55-SL
- FP52-SP
- FP50-HP
- FP52-SL
- FB52-SL
- FP50-HE

All other models, we have support for in theory (as the labview "default" command set is compatible with the FP50-MH) but we have not tested.

**Comment by kjwoodsISIS** [comment]
LOQ claims to have an FP-51.  The Water Baths page says that LARMOR has an FP-51.  I interpret your comment above to mean that FP-51 models are supported because their command set is compatible with the LabVIEW "default" command set.

**Comment by kjwoodsISIS** [comment]
Ticket reviewed.
New ticket to implement "small" configuration for LOQ Julabos (see #3621).
#3261 supersedes ticket #3477.
