### ISSUE TITLE
TOSCA: Sample Positioner OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3455]
As a scientist, I want a Sample Positioner OPI with coarse and fine level positioning controls, so that I can control the position of the sample accurately.  I also want to view the position of the sample positioner on a web-cam.

#### Acceptance Criteria
1. I can initialise the Sample Changer controller
1. I can reset any error conditions reported by the Sample Changer controller
1. I can immediately stop the motion of the Sample Changer (big red STOP button)
1. The IBEX GUI must report the current position of the Sample Positioner 
1. Using the IBEX GUI, I can use the coarse control to rapidly position the Sample Positioner 
1. Using the IBEX GUI, I can use the fine control to accurately position the Sample Positioner 
1. Using the IBEX GUI, I can view the position of the Sample Positioner on a web-cam
1. I can use genie_python to position the Sample Positioner

#### Notes
1. Check the existing VI, to see how it works.  Make sure we provide, at least, equivalent functionality.  (See C:\LabVIEW Modules\Instruments\TOSCA\TOSCA New Sample Changer\TOSCA New SC - Front Panel.vi).  Consult with Gareth on its operation.
   1. Here is a [schematic illustrating how the new sample changer OPI might appear](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/TOSCA/TOSCA_Sample_Changer_v1.pdf). 
1. The Sample Positioner is controlled using a McLennan motor controller.
1. The Sample Positioner on TOSCA is positioned using a mix of coarse and fine steps.  Coarse steps (corresponding to many individual motor steps) are used to get the Sample Positioner in roughly the right position (relative to the beam).  Fine steps (corresponding to a few motor steps) are used to adjust the position of the Sample Positioner more accurately.
   1. A medium step might also be a useful feature.
1. Each coarse step and each fine step is a pre-determined number of motor steps.  For example, a coarse step might be, say, 1000 motor steps; a fine step might be, say, 100 motor steps.  The number of motor steps per coarse/fine step should be configurable.
1. A web-cam helps the scientist position the Sample Positioner.  It is essential that the output from the web-cam is displayed on the Sample Positioner OPI (i.e. it has to be on the same screen as the coarse & fine controls).
   1. The web-cam is not used in every experiment.  Sometimes it is not attached to the equipment that gets lowered into the beam area.  The OPI needs to be able to cope with the web-cam being disconnected.
1. The output from a web-cam could be viewed in one of two ways:
   1. directly, from a URL, perhaps using the manufacturer's own software
   1. using an area-detector IOC (again, using the URL of the web-cam).
1. [ControlsWork ticket: 518](https://github.com/ISISComputingGroup/ControlsWork/issues/518) has been raised to advise TOSCA scientists on purchase of a new web-cam.
   1. **Outcome:** No need to buy a new web-cam.  We can still use the one they've got (the problem is with the ActiveX plug-in used by LabVIEW, not with the camera).

**Comment by GDH-ISIS** [comment]
@kjwoodsISIS - I have looked at the TOSCA sample changer vi and it does talk directly to the Mclennan crate as a standard Mclennan motor i.e. there is no ISIS Mclennan firmware to consider (unlike the GEM sample changer). I think the Mclennan ioc will be fine along with the IBEX sample changer. TOSCA currently just have a "next sample" and "previous sample" as a form of control - interestingly, I do not think there is a read back other than the camera.

**Comment by kjwoodsISIS** [comment]
@GDH - yes, the TOSCA scientists have said they are quite happy with using the camera as a "read-back" mechanism.  They only extra thing they have asked for is the ability to have the option for a finer level of control (essentially to adjust the first sample to the best position, then the "next sample"/"previous sample" buttons will be fine for the remaining samples).
