### ISSUE TITLE
OSIRIS: Beryllium Filter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3460]
As a scientist, I want a Beryllium Filter OPI, so that I can monitor its temperature and control its position.

#### Acceptance Criteria
1. The IBEX GUI must report the current temperature of the Be filter
1. Using the IBEX GUI, I can move the Be filter IN/OUT of the beam
1. I can use genie_python to move the Be filter IN/OUT of the beam

#### Notes
1. The temperature of the Be filter is monitored by a Lakeshore-218 device.
1. The Be filter can be placed IN or OUT of the beam (like a monitor).  The motion of the Be filter is controlled by a Galil.
1. The Be filter OPI could resemble the existing Monitor OPI.
   1. [Schematic illustration of Be filter OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/OSIRIS/OSIRIS_Be_Filter_v1.pdf)

**Comment by LiamPanchaud** [comment]
Branch: 

https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3460_Beryllium_filter_opi

**Comment by LiamPanchaud** [comment]
PR:

https://github.com/ISISComputingGroup/ibex_gui/pull/802

**Comment by LiamPanchaud** [comment]
Waiting for a reply from instrument scientists about whether they want/need motion set point controls, or just absolute motor position
