### ISSUE TITLE
Reflectometer code: test/upgrade/improve/configure

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3462]
As a developer I would like to do the next step of the reflectometer code.

**Comment by John-Holt-Tessella** [comment]
Test 1: Compare and contrast against Labview

Tests various angles for super mirror and theta. Looked at height of detector, angle of detector, height of north and south jaws of slit 3.

Numbers are not the same, presented here are detector height, similar for jaws. The measurement sample to detector is 1860.7 but it is not clear whether this is along the floor or along the beam.
At 4 degrees theta, 0 degrees super mirror. The height is:

Labview: 261.504
IBEX dist is along floor: 260.724  (delta 0.780)
IBEX dist is along beam: 260.634 (delta 0.870)

The difference is explained by crisp calculations not taking into account the pitch of the incoming beam which is -1.5  degrees wrt the floor (talk with @GDH-ISIS about labview system).

Outcome: Talk with Christy et al. about the new calculation.

**Comment by ThomasLohnert** [comment]
I believe this was sort of a stand-in for the testing phase on CRISP which is completed. I have put the spreadsheets comparing scan and dance test results from IBEX against SECI in the instrument controls share.
Further work is now captured here: https://github.com/ISISComputingGroup/IBEX/issues/4207

Moving to review.

**Comment by Tom-Willemsen** [comment]
Spreadsheets are on share as advertised. Further work captured in #4207 . No need for this ticket to remain open any longer.
