### ISSUE TITLE
OSIRIS: Jaws OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3463]
As a scientist, I need an OSIRIS specific jaws OPI, so that I can control the jaws vertical gap and vertical centre.

#### Acceptance Criteria
1. The IBEX GUI must report the current jaw vertical centre.
1. The IBEX GUI must report the current jaw vertical gap.
1. I can use the IBEX GUI to set the jaw vertical centre.
1. I can use the IBEX GUI to set the jaw vertical gap.
1. I can use genie_python to get and set the jaw vertical centre & vertical gap.

#### Notes
1. The jaws on OSIRIS consists of 2 independent blades (i.e. not four blades, as is more usual).
   1. the jaws move up/down (i.e. they are North/South blades)
   1. the user can, therefore, set only the vertical centre and vertical gap
1. The jaws are controlled by a Galil motor controller.

**Comment by kjwoodsISIS** [comment]
There are other OPIs which control 2 blades.  Check if these are suitable or can be adapted.

**Comment by LiamPanchaud** [comment]
Issues with unexpected motion. It takes severeal attempts for the SP to actually match the one you give it. It goes up in incremental steps.

For the reviewer, keep an eye out for this galil motion, I don't think it's expected behaviour and it may just be my machine. I also think I'm on an old version of the Galil driver, but I'm not sure. For more info on it come and ask me when you're reviewing

**Comment by LiamPanchaud** [comment]
Branches: 

https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3463_OSIRIS_jaws_OPI

https://github.com/ISISComputingGroup/EPICS-jaws/tree/Ticket3463_OSIRIS_jaws

**Comment by kjwoodsISIS** [comment]
@LiamPanchaud - the jaws component is one of our oldest.  I am surprised that it would misbehave (we'd have seen such behaviour by now).  Does the normal 4-blade jaws OPI misbehave on your system?

**Comment by LiamPanchaud** [comment]
Tom helped me find the issue. It turns out that 2 configs were being loaded to control the same motor and they were interfering with each other in weird ways. The issue is resolved now and the jaws seem to work fine
