### ISSUE TITLE
Reflectometry: Reflectometry bench driver

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3465]
As an OFFSPEC and POLREF scientists I would like to control my bench using the new reflectometry software. We need a driver in the driver layer to control the jacks.

# Acceptance Criteria

- Driver exists and is controlled by the component layer setting seesaw, height of pivot and angle at the pivot
    - seesaw is value to add to j2 and take from j1
- Errors in jack motors are transmitted to components
- Error in slide axis is transmitted to components
- read back has two cases:
    1. seesaw setpoint is 0: readback is of angle and height; seesaw readback is 0
    1. seesaw setpoint is non-zero:  readback is of seesaw and height; angle readback is fixed at setpoint
- seesaw must be autosaved so always has a value on init; if init is corrupt then its value is 0.
- corrections due to pivots (see spreadsheet are taken into account)

# Notes

There are 4 axes to drive (height, angle, seesaw and slide) but only 3 axes in the bench (height of j1 and j2 and slide) so there is a free parameter. Slide is weird because it is a constant value for some angles. Just letting the component layer set height, angle and seesaw. This is where the above rules for readback come from

**Comment by kjwoodsISIS** [comment]
Put ticket back on the backlog until we are ready to do it.

**Comment by John-Holt-Tessella** [comment]
pull request:

- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/303

**Comment by kjwoodsISIS** [comment]
Re-pointed by @John-Holt-Tessella from 13 -> 3.

**Comment by ThomasLohnert** [comment]
- Found a potential bug related to server initialisation, see comment on PR
- Could you please add an config snippet for setting up an example bench somewhere in the config documentation? (in the examples for the components section, or in the full example config)

**Comment by ThomasLohnert** [comment]
How to get PR from inst_servers into new repo:

In local `support/refl` repo where origin is `EPICS_refl`:
```
# Add old repo as second remote called inst_servers
git remote add inst_servers https://github.com/ISISComputingGroup/EPICS-inst_servers.git`

# Fetch remote branches
git remote update

# Checkout ticket branch from old repo
git checkout inst_servers/TicketXXXX
git pull

# Push changes into branch on new remote
git push --set-upstream origin TicketXXXX
```

Merge the latest changes from `origin/master`, resolve any conflicts. Now you can make a PR from `origin/TicketXXXX`

**Comment by John-Holt-Tessella** [comment]
Documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/reflectometry-bench-configuration
