### ISSUE TITLE
IOC: Reflectometry configurations

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3466]
As reflectometry scientists I would like a configuration for my instrument for the reflectometry software so that I can test it.

**Comment by LiamPanchaud** [comment]
We need to make reflectometry configurable by users, which involves loading a configuration of some sort from the configurations folder. I'm going to try to make it such that the user writes this in Python, and the python is then loaded by the reflectometry inst_server. 

The config will need to allow the user to potentially configure:
- Components
- Beamline parameters
- IOC Drivers
- Modes

I will look into how best to configure python using python. It may be an `import` statement, it may be more complicated than that. If anyone has any suggestions feel free to let me know.

**Comment by LiamPanchaud** [comment]
`import` can't be used because python only searches the current directory by default. 

Using purely python, sys can be used to alter the path to include the config

```python
import sys
sys.path.insert(0, '/path/to/config/folder/config.py')

import config
```

Or we can use `importlib` or `imp` to essentially treat it as an imported module. This depends on the version of python being used though.

**Comment by LiamPanchaud** [comment]
Branches: 

https://github.com/ISISComputingGroup/EPICS-inst_servers/tree/Ticket3466_Reflectometry_configurations

**Comment by LiamPanchaud** [comment]
PR:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/168

**Comment by LiamPanchaud** [comment]
I need to add tests for loading configs (valid and invalid)
