### ISSUE TITLE
IOC: McLennan new homing behaviour

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3469]
Vesuvio want a homing mode which will set the Dial position to 0 after a cv and maintains an offset. The current mode 3 sets both the dial and the user position thus the offset is always 0. It may be that this can be modified.
In addition the offset should be a macro that can be set in the configuration.
Once done create a ticket to configure from left and right foils on Vesuvio and ask instrument scientists if they want motion set points.

Required by #3469

**Comment by kjwoodsISIS** [comment]
This ticket has been ready for review since 18th October.  When is it going to be reviewed and completed?

**Comment by John-Holt-Tessella** [comment]
It is my fault, I am meant to be reviewing it and I have been busy.
