### ISSUE TITLE
IOC: McLennan CMOD  should be used

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3470]
There is an error in the IOC boot which means that the macro CMOD has no effect. In essence it needs the following line adding (can we check that this works):

```
## Check if open loop mode has been requested
$(IFNOTSIM) stringiftest("CMOPEN", "$(CMOD$(MN)=)",4,"OPEN")
```

**Comment by Tom-Willemsen** [comment]
@Alistair-McGann-Tessella since you have the mclennan set up in your office, could you do this ticket at the same time?

**Comment by Alistair-McGann-Tessella** [comment]
This line appears to already be in the st-motor-init.cmd file for this IOC

**Comment by Alistair-McGann-Tessella** [comment]
The motor LED which should be pointing to this parameter does not seem to getting updated even after this change, see: https://github.com/ISISComputingGroup/IBEX/issues/3596.
