### ISSUE TITLE
LiveView: add additional PVs to display

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3471]
The following additional PVs in ADisisdae.template should be added to LiveView

They all have a   $(P)DAE:AD$(DET):   prefix where DET is the macro indicating detector number

INTG:ENABLE:SP – enable or disable live view (which should effectively pause the display)
INTG:MODE:SP –  allows to see total counts or difference from last call
INTG:UPD:RATE - display update rate (Hz)
INTG:RATE - count rate across whole detector (Hz)
INTG:SPEC:RATE - highest count rate in a spectrum
INTG:TRANS:MODE:SP  - choose linear, square root or log based viewing of counts

The INTG:SPEC:START:SP, SizeX and SizeY PVs don't usually change and are autosaved, probablty best to leave them off for now.

**Comment by FreddieAkeroyd** [comment]
Extra PVS from #3381

**Comment by DominicOram** [comment]
The colour map should also autoscale based on $(P)DAE:AD$(DET):INTG:SPEC:MAX

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/ibex_gui/pull/792
