### ISSUE TITLE
LOQ: Migrate to IBEX

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3472]
As an instrument scientist, I would like to use the IBEX instrument control system on LOQ.
As a developer, I want to complete the migration of LOQ to IBEX (see #3461).

#### Acceptance Criteria
1. [x] Preparations for migrating LOQ to IBEX are complete (requires #3461)
1. [x] LOQ scientists are trained in how to use IBEX
1. [x] An appropriate version of the ICP program is installed on LOQ
1. [x] IBEX is installed on LOQ.
1. [x] IBEX is configured for the devices on LOQ.
1. [x] IBEX is tested on LOQ.
1. [x] LOQ is added to the list of available instruments
1. [x] Transfer beamline parameters from `c:\LabVIEW Modules\Common\Experiment Parameters\Beamline Parameters.xml` to experimental parameters in IBEX.
1. [x] Demonstrate the migrated configurations & scripts (created above) to the instrument scientists.. Confirm they are happy with the migrated configurations & scripts.

#### Notes
1. The devices on LOQ are listed on the [LOQ Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process.
1. Refer to #3461 to check whether the ICP program needs to be upgraded.
1. Scientists are usually invited to a training session a week or two before the migration takes place.

**Comment by John-Holt-Tessella** [comment]
All done as part of #3461 except for scripting with Rob is doing. I think we will hear more about that but I am happy to open a new ticket which says something like create functions needed for script generator.
