### ISSUE TITLE
Jenkins: make EPICS release build a multibranch pipeline

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3473]
The genie and ibex client release builds are multibranch pipelines, the EPICS release build is not and so needs to have the release number updated manually in the job. Ideally it should be made like the others, unless there is some technical reason why it wouldn't work as a multibranch pipeline?

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/137
