### ISSUE TITLE
LOQ: Implement GALIL controls in IBEX

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3475]
As a LOQ scientist I want to be able to control my Galil motors from IBEX. There are four axes to control, two for the sample changer (moves in x and y), one to control the aperture plate and one to control the transmission monitor, all of these will need to be controlled in the new system.

I would like motor aliases for 4 aperture positions, one of which (a temporary 'beam stop') will be a new addition.

The sample changer follows different naming conventions depending on which rack is in use, and can also be driven to a position in mm. I require that preset positions for some of the racks are also built into the system (see https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details)

**Comment by John-Holt-Tessella** [comment]
Done as part of #3461
