### ISSUE TITLE
LOQ: Implement Julabo FP-51 and FP-52 IOCs

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3477]
As a LOQ scientist I need to control Julabo FP-51 water baths. This will need to be implemented as a new IOC, or added on to the existing IBEX driver.

For redundency, it would also be useful to be able to control FP-50 and -52 water baths from the ISIS inventory. More information can be found here (https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details#noteWaterBath)

Requires #3451.

**Comment by kjwoodsISIS** [comment]
Ticket #3451 requests confirmation of which Julabo devices are supported by the current driver.  It may be that the current driver is capable of supporting all 3 models of Julabo, or it may require modification to support all 3, or maybe we need 3 different drivers.  Let's do #3451 first, then we can decide how to provide support for FP-51s.  In effect, this ticket requires #3451.

**Comment by kjwoodsISIS** [comment]
LOQ has two Julabo devices (labelled Julabo 1 and Julabo 2).  According to the model numbers printed on the Julabo cases, both are FP51 models.
   * [Julabo 1 is labelled WB13](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/LOQ/LOQ_Julabo_1.jpg)
   * [Julabo 2 is labelled WB14](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/LOQ/LOQ_Julabo_2.jpg)
The [Water Baths](https://www.isis.stfc.ac.uk/Pages/Water-Baths.aspx) page contains a look up table, matching the labels WB13 and WB14 to Julabo model numbers.  Unfortunately, the table contradicts the numbers printed on the cases.

**Comment by Tom-Willemsen** [comment]
In the LOQ seci configs:

```
<EW>
<Name>Bath Type</Name>
<Choice>Big</Choice>
<Choice>Small</Choice>
<Choice>WB-01</Choice>
<Choice>WB-02</Choice>
<Choice>WB-03</Choice>
<Choice>WB-04</Choice>
<Choice>WB-05</Choice>
<Choice>WB-06</Choice>
<Choice>WB-07</Choice>
<Choice>WB-08</Choice>
<Choice>WB-09</Choice>
<Choice>WB-10</Choice>
<Choice>WB-11</Choice>
<Choice>WB-12</Choice>
<Choice>WB-13</Choice>
<Choice>WB-14</Choice>
<Choice>WB-15</Choice>
<Choice>WB-16</Choice>
<Choice>WB-21</Choice>
<Choice>WB-29</Choice>
<Choice>WB-30</Choice>
<Choice>A40</Choice>
<Val>1</Val>
</EW>
```

I believe this means that LOQ are using water baths with the "small" labview configuration.

The "small" labview configuration is not compatible with the current EPICS IOC. So, the existing IOC will need to be modified for LOQ.

**Comment by kjwoodsISIS** [comment]
Superseded by #3621.
