### ISSUE TITLE
SURF : IOC and OPI for TPG361-362

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3484]
As a user I would like to monitor a TPG361 pressure gauge in SURF. This requires an IOC and OPI.

Note : This is very close to the TPG26x IOC, which appears to nearly work. This unit has to use RS485 for communication along with a MOXA 5650 (rather than a MOXA 5610). MOXA has already been replaced and the cabling is complete.

Ref : 
https://github.com/ISISComputingGroup/ControlsWork/issues/326
C:\LabVIEW Modules\Drivers\Pfeiffer TPG36x
C:\LabVIEW Modules\Drivers\Pfeiffer TPG36x\Documentation

**Comment by GDH-ISIS** [comment]
Partially working protocol and db files which may be of use for the development. Altered from the ISIS TPG26x

[tpg36x.zip](https://github.com/ISISComputingGroup/IBEX/files/2599405/tpg36x.zip)

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-TPG/pull/7
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/380/files
- https://github.com/ISISComputingGroup/ibex_gui/pull/883
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/33/files
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/183/files

I have tested this locally by running the emulator against the labview code to check that the command syntax is as expected. There will be an opportunity to test with the real hardware as part of https://github.com/ISISComputingGroup/IBEX/issues/4162 .

**Comment by DominicOram** [comment]
There's so much commonality between these two devices that it seems silly that we have two different IOCs and OPIs. @Tom-Willemsen is not worth just putting this in a macro for the one IOC?

**Comment by Tom-Willemsen** [comment]
The reason I did it that way was just to be consistent with the existing tpg300/tpg26x (which have separate IOCs). In general I think it is easier for a scientist to look down the list of available IOCs and find the one they need rather than figuring out which macro to provide to a generic ioc.

I thought the 26x and 36x were already sharing an OPI via linking containers, did I mess something up?

**Comment by DominicOram** [comment]
Further discussed in the office between @DominicOram @Tom-Willemsen and @davidkeymer. The way to go is have two IOCs because:
* It fits the current user workflow
* In this case the device is a fixed piece of kit so the IOCs will never need to be interchanged
