### ISSUE TITLE
Can't delete a synoptic

### ISSUE THREAD

**Issue by LiamPanchaud** [ISISComputingGroup/IBEX#3488]
As a user I want to be able to delete synoptics.

**Comment by kjwoodsISIS** [comment]
Will you be creating a Squish test for this as part of the fix?

**Comment by LiamPanchaud** [comment]
Yes, that's in progress now with Rory

**Comment by LiamPanchaud** [comment]
PR:

https://github.com/ISISComputingGroup/ibex_gui/pull/794

**Comment by DominicOram** [comment]
I have reviewed the fix so that we could get it in the release, someone else can review the system test if they want.

**Comment by Rory-Potter-Tessella** [comment]
[Squish tests pull request](https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/13)

**Comment by LiamPanchaud** [comment]
I'd say 0.5
