### ISSUE TITLE
RIKENFE: read current state of changeover

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3490]
As a RIKEN instrument scientist, I would like to know what state the changeover switches are currently in so that my scripts can act appropriately.

This information is available from the logic lines on the PLC, which we can read via DaqMX. 

This may also need to change the `RB2` and `RB2-2` calibration numbers dynamically. Currently this is done in an instrument script, and the calibration numbers in each case are documented in a document on the shared drive. If unsure about the calibration numbers for each mode, ask James Lord for clarification.

**Comment by KathrynBaker** [comment]
Moving to be a proposal, as this came up again as a footprints issue. I could see no reason for it to be awaiting.

**Comment by LiamPanchaud** [comment]
PVs now in place to read the status of RB2 mode and Port 3/4 mode. Dynamically changing RB2/RB2-2 has been moved to ticket #4249

**Comment by LiamPanchaud** [comment]
PRs: 

[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/374)

[IOC test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/177)

**Comment by kjwoodsISIS** [comment]
@LiamPanchaud  - what is impeding this ticket?

**Comment by LiamPanchaud** [comment]
Wrong column, my bad
