### ISSUE TITLE
Riken front end: set polarity in driver

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3491]
As a riken instrument scientist, I want the interface to the power supplies to be as transparent as possible. If I set a "current" of -5A it should set the polarity to "-" and the current to "5A" for me.

**Notes:**
- I've written a python script that does this as a stop-gap measure but it would be best to do this at the driver level. The script is `set_current` and is on riken in `inst/front_end.py`.
- After changing polarity, the driver **must** wait for the polarity readback to be correct before sending the current (otherwise, the current setpoint will be ignored). Physically the changeover between polarities is not instantaneous: on most supplies it takes about 5-10 seconds. We should try not to introduce unnecessary delays if the polarity is not changing.
  * Setting a current of zero should not change the polarity either way
  * Occasionally some power supplies ignore a polarity change request, so the driver should retry sending the polarity if it didn't change within a reasonable interval (e.g. 20 seconds). If retries are too fast, you may upset the power supply and it will require a power cycle to recover.
  * May be easiest to implement using an SNL program
- Beware of inconsistencies between danfysiks, GECs, Tolkens and RB2 when picking up this ticket. We need a general solution that works for all of the supplies as transparently as possible.
  * Danfysiks allow you to set a signed current and will do the polarity reversal for you if necessary
  * I believe the GECs ignore the sign and just set absolute values
  * As far as I could tell, the Tolken supplies ignore a set current command that is negative
  * RB2 and RB2-2 do something wierd, this may be to do with the fact that their polarity switches are shared.

**Comment by davidkeymer** [comment]
No longer relevant since RIKEN refurbishment when PSUs replaced.
