### ISSUE TITLE
Deployment: Update the upgrade script

### ISSUE THREAD

**Issue by ghost** [ISISComputingGroup/IBEX#3492]
As a developer, I want the upgrade script to be up to date so that I can install the latest version of IBEX on instruments more easily.

Include:
- Tell the user to copy the third part installs from the share before installing.
- Run the java panel updater as admin to check that auto-update is off.
- Python does not always install (does it maybe use something local and then can't delete the python dir)
- Sometime python can't find ps utils after restart is it using the wrong python in the script (should be using the network python and libraries)
- Error should be produced if upgrade script fails to run
- Got `Checking that configurations are being pushed to the appropriate repository
Current repository status is: On branch NDXEMMA-A
Your branch is up to date with 'origin/NDXEMMA-A'.

nothing to commit, working tree clean
Unexpected git status. Please confirm that configurations are being pushed to the appropriate remote repository` eevben though this is fine.

This came about while upgrading instruments to IBEX version 5.0.1 (see [#3414](https://github.com/ISISComputingGroup/IBEX/issues/3414))

**Comment by FreddieAkeroyd** [comment]
The current upgrade script asks you to copy ibex_system_boot.bat into the “ProgramData” all users startup area. This requires administrator (gamekeeper) privilege and also means ibex would start if e.g. gamekeeper logged onto console itself. 

I think a better approach would be to have ibex run as part of spudulike login only and also to use a shortcut in the startup area so the file does not need to be updated again if ibex_system_boot was to change in future. 

So the new procedure would be:
* Go to start -> all programs and right click on the startup folder and select “open”
* In the directory do new -> shortcut and browse to c:\instrument\apps\epics and choose ibex_system_boot.bat

The upgrade script could check for this shortcut and create it if it is not present

**Comment by davidkeymer** [comment]
The script should also install and configure Git, if required, as per the instructions on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Getting-started-with-Git-and-GitHub

**Comment by davidkeymer** [comment]
The script produces this output, which is now no longer correct.

```Do step 'Update web dashboard'? : y
Update web dashboard ...
Add the host name of the instrument to NDX_INSTS or ALL_INSTS in webserver.py in the JSON_bourne repository.```

**Comment by davidkeymer** [comment]
Also wrong output:

"On NDAEXTWEB1, pull the updated code and add a link to the instrument dashboard on the main dataweb page under C:inetpub\wwwroot\Dat
aWeb\Dashboards\redirect.html"

**Comment by davidkeymer** [comment]
Script provides confusing/incorrect instructions for creating shortcut to `ibex_system_boot.bat` in Startup Group of start menu.

Correct procedure here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup

**Comment by John-Holt-Tessella** [comment]
Add a step which selects a blank configuration or the top configuration in the list. After boot.

**Comment by LiamPanchaud** [comment]
- [ ] Copy third party installs
- [x] Change autostart location
- [x] Fix incorrect git error message
- [ ] Error if script fails to run
- [ ] Python can't find ps utils
- [ ] Python does not always install 
- [ ] Run Java updater as admin 
- [x] Remove web dashboard stuff
- [ ] Add blank config

**Comment by LiamPanchaud** [comment]
PR: https://github.com/ISISComputingGroup/ibex_utils/pull/32

**Comment by FreddieAkeroyd** [comment]
Wiki page for ibex_system_boot.bat corrected

**Comment by ThomasLohnert** [comment]
Some more issues I noticed in this round of deployments
- [ ] "Upgrade Config" step tries to run `misc/upgrade.bat` without prompting for admin rights. This always fails and then has to be done manually
- [ ] The script tries to be smart and automatically find the highest version number in the release folder. However this currently does not cater for installing from multiple release versions e.g. `5.4.1\Client_E4` and `5.4.0\EPICS` - script would try to find both in `5.4.1`. This is awkward to work around at the moment. We should make the script smarter and/or make it easier to manually pass in different release numbers for different system components
