### ISSUE TITLE
python: reload(inst) does not work

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3493]
As a user I would like `reload(inst)` to reload the instrument scripts module.

Actual behaviour: it silently fails to reload the inst module

Once fixed we need to patch this onto all the instruments as a hotfix.

**Comment by Rory-Potter-Tessella** [comment]
Work is on `Ticket3493_reload_inst_fix` branch in `Settings\config\<instrument-name>\Python` directory. Includes `a.py` and `b.py` files for testing.

**Comment by Tom-Willemsen** [comment]
I think what we've actually done for this ticket is to revert https://github.com/ISISComputingGroup/IBEX/issues/3217 to get us back to a state where we know what works and create https://github.com/ISISComputingGroup/IBEX/issues/3496 to think about our approach better going forwards

**Comment by John-Holt-Tessella** [comment]
After meeting this is not going to be used.
