### ISSUE TITLE
Riken front end: RB2 and RB2-2

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3495]
Riken front end has two power supplies called `RB2` and `RB2-2`. This is physically one supply but has two danfysik control boards.

There are a number of edge cases with this power supply:
- It's interpretation can be different based on whether riken is running to port 3 or 4, as well as the "RB2 mode"
- The polarity reversal and main on/off switches are shared (but the current settings are not). With the current system this means they have to be set in a specific order
- Not sure if interlocks are shared
- It does not reset successfully remotely - have to wander down to it and press a button

### Work that needs doing as part of this ticket:
- Figure out how RB2 and RB2-2 actually work
  * This will need a meeting with (at least) Electrical group (e.g. Richard Hale), RIKEN instrument scientists (e.g. James Lord) and Tim Carter.
- Figure out how the muon scientists would like RB2 and RB2-2 to work, for each case.
- Figure out whether we can make this a "special case" of the general danfysik driver or whether it is better to give it it's own DB and protocol file

### Notes
- RB2 also has a mode change sequence. As part of this work we need to be careful not to break that logic.

requires #3490

**Comment by KathrynBaker** [comment]
Whilst discussing something else at the time of adding this comment Adam had switched to manual control of RB2 as there were issues controlling it, including via the command James had created.

**Comment by kjwoodsISIS** [comment]
If this issue is not causing problems in practice maybe we should just close it (it can be re-opened, if necessary).

**Comment by davidkeymer** [comment]
Superseded by #7556
