### ISSUE TITLE
Genie_Python: inst automatic importing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3496]
As developer we need to have a meeting about the automatic namespace importing being done in  inst. Ticket #3217 broke scripts and needed to be reverted before cycle. Lets find a solution for this issue.

HRPD did an import from hrdp_routines
Many instruments have the function in a module with the same name so would have lost that function.

**Comment by Tom-Willemsen** [comment]
Meeting notes here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/instrument-scripts
