### ISSUE TITLE
genie_python: Discussion of scans routine

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3501]
As a scans author (Adam) I want to know how to include my code into IBEX and genie_python. Currently I have copied the routines with the instrument specific routines directly into inst but I want to run it from the shared area. However there are some routines in it that rely on instrument specific subclasses. How should I structure this and make it work with genie_python. Please include me in the discussion.

**Comment by Tom-Willemsen** [comment]
Discussion complete. New ticket created at https://github.com/ISISComputingGroup/IBEX/issues/3670 .
