### ISSUE TITLE
Larmor: configure huber sample stack

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3502]
LARMOR are using a huber sample stack (galil) which usually lives on POLREF. Configure it.

Cable was initially wrong. Electronics have changed the wiring. Stage now moves but limits are wrong way round. Electronics are swapping the limits in hardware. Once they are done check all motion is sensible and set up homing.

**Comment by Tom-Willemsen** [comment]
configured on larmor and given to scientist. Nothing really to review - it is all setup

**Comment by GDH-ISIS** [comment]
The Huber sample stack - the POLREF analyser - has now been moved back to POLREF for the start of the cycle. In addition, the amplifier cards had to move back to PORLEF as well. I have shown Adam what is involved to put it all back for LARMOR.

Note : In moving the motor system back to POLREF, the amplifier cards need to be taken from POLREF to LARMOR as well. These cards also need to be installed in the correct order for the correct axis as they are configured differently for each axis. The order can be taken from the table of motors.
