### ISSUE TITLE
DAE GUI: Total uAh is incorrect on run information panel

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3504]
The "Total uAh" item on the DAE run information panel is displaying the beam current rather than the microamp total - it should be displaying $(P)DAE:GOODUAH

**Comment by John-Holt-Tessella** [comment]
How important is this:

1. We need to patch it on all machines before cycle
1. We need to warn instrument scientists
1. We can wait until next cycle

**Comment by FreddieAkeroyd** [comment]
I'm not sure if it has always been there or is new, the current E3 client shows the behaviour too. I though i might have noticed before if it had always been there though. The dashboard is correct, and to most people it would be obvious the number is wrong on that tab, so it is probably not urgent.
