### ISSUE TITLE
Update dependencies and test

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3506]
Now that we have done release 5 we should update all dependencies and test that they still work.

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates

**Comment by Tom-Willemsen** [comment]
Mostly complete. Tasks still to complete:
- GUI: update eclipse dependency
- Try to build a new CS-Studio locally with an updated MySQL connector and see whether it can connect to MYSQL server 8. If it works then submit the dependency update as a patch to cs-studio.

Both of these tasks require the eclipse software repositories to be online. Currently they are offline/timing out (for example try connecting to http://download.eclipse.org/eclipse/updates/4.7 ). This ticket is impeded until the update sites are back online.

**Comment by Tom-Willemsen** [comment]
Connecting to the update sites seems to work reliably from outside the RAL network. Is it possible that we are getting caught out by a site firewall rule or something similar?

**Comment by FreddieAkeroyd** [comment]
It could be site or it could be JANET, I think the previous GitHub connection issue on site was a JANET wide issue. Best to email facilities IT and they can raise it with site networking.

**Comment by Tom-Willemsen** [comment]
I have raised a ticket with FIT about the connection issues to eclipse.org. It is apparently a firewall issue of some sort and they have escalated it to a different service desk.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - can you please keep an eye on this.  FIT have recently escalated several issues for me to other service desks, only for the other service desk to fail to respond in a timely fashion.  If you haven't got a response by Tuesday or Wednesday next week, we need to escalate again.

**Comment by John-Holt-Tessella** [comment]
I think this has now been done :-)

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - what do we need to do to get this ticket completed?

**Comment by John-Holt-Tessella** [comment]
Yes but I think we should leave it until after the release now. What do you think @Tom-Willemsen

**Comment by Tom-Willemsen** [comment]
I agree with @John-Holt-Tessella  - let's do this after the release

**Comment by DominicOram** [comment]
Is this ready to review now that the update site is accessible and we've released?

**Comment by Tom-Willemsen** [comment]
Not yet - see my comment from 13th Nov for tasks still outstanding. I haven't had a chance to look at these yet since we regained access to the eclipse update sites.

**Comment by Tom-Willemsen** [comment]
MySQL 8 install instructions are here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Upgrading-to-MySQL-8

I will make them into an upgrade script after someone else has gone through them to confirm the process works ok - I would like to check that I've captured all the steps correctly first.
