### ISSUE TITLE
GUI: Show DAE is switched off when it is in the dashboard

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3507]
As a SANDALS instrument scientist I would like the dashboard to indicate that the dae is switched off when the DAE is switched off not show status unknown and simulation mode. This is confusing.

Technically I am not sure how easy this is to achieve.

**Comment by FreddieAkeroyd** [comment]
Can you clarify "not show status unknown and simulation mode" - it will only show simulation mode if that has been requested and I assume it would still be relevant to display that even if the DAE is off? So would they like an additional DAE ON/OFF indicator independent of simulation mode?

DAE off is hard to determine, it is really "unable to communicate with DAE - is it switched off?" The isisicp tries to talk to the DAE very early on and aborts if it cannot, so a PV in the DAE IOC that starts with "DAE UNAVAILABLE" and becomes "DAE AVAILABLE" is possible, however if the isisicp is in simulation mode it never tries to access the DAE and so a reliable "dae unavailable" indicator would not be available currently .

**Comment by John-Holt-Tessella** [comment]
At the moment if the dae is switched off the display looks like:
![image](https://user-images.githubusercontent.com/7570055/45206691-8a8db900-b27d-11e8-9ca4-95941e6d674b.png)

I think it should show "not available" instead of SIMULATION

**Comment by John-Holt-Tessella** [comment]
Just remove simulation mode, being unknown is fine.
