### ISSUE TITLE
LARMOR & ZOOM: Update Synoptics

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3509]
The synoptics of ZOOM and LARMOR need to be updated so that the channels and slots are configurable and set to the correct values. On LARMOR, Monitor 3 needs to have slot 0 and channel 2, and Monitor 4 should have slot 0 and channel 3. The instrument scientists on ZOOM said that the synoptic is out of date, as five monitors are currently used on the beamline (whereas the synoptic display only has one). They think that Monitor in the synoptic perspective should have slot 4 channel 22, but they're not sure. They also said that they would update the synoptic perspective to display all monitors.

See also #3268 .

**Comment by Rory-Potter-Tessella** [comment]
ZOOM has updated the synoptic, so they now only have one monitor on their synoptic. I've set `CHANNUM` to 22, and monitor number `M` to 4 per the ticket.

**Comment by John-Holt-Tessella** [comment]
Larmor done

**Comment by kjwoodsISIS** [comment]
How many points?
