### ISSUE TITLE
Dataweb: do not display certain quantities in scientific notation

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3514]
As an instrument scientist, there are some quantities which I do not want displayed in scientific notation on the dataweb.

These include:
- Good frames
- Raw frames

Notes:
- Some things (e.g. run number) are already excluded in the dataweb code

**Comment by aaron-long** [comment]
+1 HRPD

Specifically for monitor counts so they can see them changing over time.

**Comment by aaron-long** [comment]
@DominicOram will modify the archive engine to pass type information, so that we can make a simple type check when formatting the blocks into JSON. 

We want to have parity with the IBEX GUI which does not format intgers.

**Comment by KathrynBaker** [comment]
New webdashboard uses the PVs, this is no longer applicable
