### ISSUE TITLE
SUPPORT: IMAT Motors

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3520]
Winfried reported:

> IMAT Galil SPS axes not working. Wrong absolute positions.
> STOP ALL: does not stop motors moving

**Comment by John-Holt-Tessella** [comment]
When I arrived the cause was that Galil_05 and Galil_04 were not communicating correctly with IBEX. The motor in Galil_05 had been told to move and was still moving but it couldn't stop because of communication status hence then "STOP ALL does not work".

I needed to reboot the Galil_05 to make it start communicating (I couldn't ping it before this).
I also restarted the IOC. This then caused it to go into its I can not move the axis because of software limits (see ticket #2947) I added the new flags and this made the axis move correctly.

Galil_04 however did not respond even after a reboot. Called @ChrisM-S  to help with network and @FreddieAkeroyd also came to help. But we got no futher. Winfried doesn't need that this week but will go down with a serial line and test today (we couldn't get it to talk via the moxa).

**Comment by GDH-ISIS** [comment]
Note : Would it please be possible to fault find the "Motors are moving" issue first - it looks as though there is a problem with the definition of "Motors are moving". This may then contribute to "Stop all motors" - although maybe that should send the request to stop unconditionally.

**Comment by FreddieAkeroyd** [comment]
"Motors are moving" will likely be defined from the "in motion" indicator read from the galil data record, if it can't communicate with the galil it will probably leave the status as it was before i.e. moving. Stop all will (try to) send a stop to the motor, but will not assume that the motor has stopped, it will rely on readback from the controller to determine this for sure.

**Comment by John-Holt-Tessella** [comment]
I can confirm @FreddieAkeroyd description. Having looked at the problem and the follow on this morning. 

Myself and @KathrynBaker have been down. Galil5 was in a weird mode where Galil tools could not talk to the serial port. Returned `>` instead of `:` at the prompt. The error light was on. We reset it and it rebooted fine. Winfried has agreed to keep an eye on it and if it trips again we will ask for a replacement.
Galil 4 had no error light but also wouldn't respond on the serial line. We rebooted this too and it is also fine now. Again we will keep an eye on this.

Issues to take away:

1. Blocks monitoring motors which go into communication error should report error
1. A move seems to clear the com error; if a new error is produced then it should be reported
1. If a motor is moving on comm error we decided it should continue to report moving

**Comment by ChrisM-S** [comment]
Does anyone know what the serial parameters for these should be?

**Comment by Tom-Willemsen** [comment]
Just documentation to sort before this ticket can be considered complete.
- [ ] Please can we add any symptoms (and any possible resolutions, even if only temporary) to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting
- [ ] I couldn't find tickets for the three issues mentioned above.

**Comment by FreddieAkeroyd** [comment]
After further issues with the hardware we have moved the 4000 series galils onto serial #3546 #3547

**Comment by Tom-Willemsen** [comment]
We have been getting a nagios notification about CPU usage of galil_05 on IMAT: `CRITICAL - [Triggered by _AvgCPU>85] - CPU for GALIL-IOC-05 (PID=13540)=85.6%` 

I wonder if it might be related to this change and if so whether it's something we need to worry about?

**Comment by FreddieAkeroyd** [comment]
We could drop the polling rate, i think it is currently 100ms?

**Comment by John-Holt-Tessella** [comment]
Done documentation
