### ISSUE TITLE
INES: Chopper

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3524]
INES shares a chopper with TOSCA.  TOSCA is first in line in the beamline, so the chopper is controlled by TOSCA.  As an INES scientist, I need to know the chopper settings; I do not need to be able to change the chopper settings.

#### Acceptance Criteria
1. I can view the current settings of the TOSCA chopper.
1. There are blocks defined on INES that allow me to view and log the TOSCA chopper settings.

#### Notes
1. Being able to view the relevant blocks from TOSCA would be sufficient.  May also be worth checking to see how SECI displays this information.

**Comment by ThomasLohnert** [comment]
Added an instrument prefix macro to the MK3 Chopper OPI. 
Will add a MK3 Chopper OPI pointing at TOSCA to relevant INES synoptics.

PR: https://github.com/ISISComputingGroup/ibex_gui/pull/813
