### ISSUE TITLE
INES: Shutter

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3525]
INES shares a shutter with TOSCA.  As an INES scientist, I need to know the status of the shared shutter.

#### Acceptance Criteria
1. I can view the current status of the shared TOSCA/INES shutter.

#### Notes
1. Can the dashboard be configured to display the status of the shared TOSCA/INES shutter?

**Comment by FreddieAkeroyd** [comment]
I think this will need some electronics work like that done on HRPD to be able to see the intermediate shutter status

**Comment by Kevin-Woods-Tessella** [comment]
We probably need a simple sketch showing the relative positions of primary & intermediate shutters.

**Comment by kjwoodsISIS** [comment]
At the present time, there is no requirement for INES to see the state of the secondary (intermediate) shutter.  They can see the state of the secondary shutter from within the instrument cabin.
