### ISSUE TITLE
Merlin: TPG300 support

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3527]
TPG300 won't talk on MERLIN. Diagnose and fix.

- Moxa port 15 on moxa in merlin cabin was dead. Any attempt to serial read/write would hang (from hyperterm, hterm, putty etc). I switched it over to moxa port 13
  * on port 15, I could see the "reply" LED flashing on the front of the moxa
  * according to the moxa web interface I was recieving bytes (equal to number of bytes I sent)
  * None of the terminal emulators I used could read these reply bytes
  * Once I moved it over to port 13, I could see the reply bytes, which were just the bytes that I had sent being echoed back to me by the device
- Cable needed wiggling in back on TPG unit. Unclear why (it was not loose)
  * Before it was wiggled, the unit was simply echoing the bytes I sent it straight back to me as I typed them.

**Comment by ChrisM-S** [comment]
+1 on MERLIN

Checked light on MOXA and no sign of an attempt to write (would be very obvious at 9600 baud.  Changed macro to move the connection to an empty port 15 (from port 13 which was stuck).  Immediately on the restart of the IOC, the new port showed showed a yellow light (attempt to write).  Connecting up to the TPG300 things went off normally.  Looking at the MOXA, the ports (below) on the monitor show DSR, CTS and DCD all ON even though the device is listed [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-flow-control-settings) as no flow control (hardware or software).  Given that there is a very long history of instrument lockups if any form of hardware flow control is accidentally selected for devices not doing flow control (even before MOXAs and VMs if I remember rightly), it would seem at least worth trying to not have an asyn default which activates hardware lines either way unnecessarily.  No flow control means NO FLOW CONTROL!

The days of 3-wire connections and loopbacks are past from our perspective but the Nport/MOXA behaviour we see may be triggered by accurately emulating the necessary behaviour of a real physical UART when serial signals sent might simply be looped back.

![image](https://user-images.githubusercontent.com/3035405/58818391-bfb91300-8625-11e9-8ba8-371a7be38501.png)

**Comment by FreddieAkeroyd** [comment]
So port 15 works and is listed as "ON, ON, ON" and port 13 that didn't work was "OFF, OFF, OFF"? The default IOC no hardware flow control would enable RTS and ignore CTS, so CTS being on would look to be done by the TPG300 itself (or a loopbacked wired connector)?

**Comment by ChrisM-S** [comment]
Yes, I'm not 100% sure what this line refers to (i.e. what we set or what we see the incoming signals as) but the ILM we tested on ZOOM did appear to set (D)CD regardless of how we set the other lines - so it could be what what the TPG is or is not doing!

**Comment by FreddieAkeroyd** [comment]
DCD should be set by the "DCE" (modem) side of the RS232 connection, as the PC is "DTE" it doesn't have a command to set this. I'm not sure what moxa or nport might decide to do by themselves though, but it is nothing that EPICS would be able to control itself on the Windows COM port. In the old modem world I don't think things would work if DCD wasn't high as it would indicate the phone line was down?
