### ISSUE TITLE
SUPPORT: Journal view not working

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3528]
Journal viewer is not working, fix this on all instruments that want it.

Run install.bat in `ISIS Shares\ISIS_Experimental_Controls_Public\journalparser_static_new`

**Comment by John-Holt-Tessella** [comment]
Done:

MERLIN
IRIS
HRPD
ALF
EMMA

TODO:

Vesuvio (tomorrow morning)
Engin-x
GEM
IMAT
LARMOR
MAPS
POLARIS
SANDALS
ZOOM

**Comment by FreddieAkeroyd** [comment]
We need to implement #2953  We may decide we don't need a separate job as in #2952 but can instead pull out journal parser from a static jenkins build that publishes it to a separate directory.
