### ISSUE TITLE
IBEX GUI: dashboard and DAE panel issues

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3529]
From Ron on POLARIS:

1. The Polaris dashboard is showing "Period: unknown" - while I think 
everything's OK, I'd like the reassurance that it is by seeing this read "1"...

2. In the DAE perspective, the information in the Detector Diagnostics tab is 
all greyed out. As I was able to check on some detector faults using this view 
at the end of last week, this is a new fault which has developed over the past 
couple of days.

He restarted the GUI and all came back OK

**Comment by John-Holt-Tessella** [comment]
I am not quite clear what to do for this ticket. Do we feel this is a problem that develops after the GUI has been running for a while? In which case do we need to set up a GUI on a test sysem and leave it running and see if it drop both detector diagnostics and Period?

**Comment by FreddieAkeroyd** [comment]
Period Unknown Seen on INES too, also frames were showing Unknown/Unknown until they started a run. Looks like a monitor was missed and as period never changes on Ines it will probably stay as Unknown

**Comment by KathrynBaker** [comment]
Not aware of this being seen recently, closing
