### ISSUE TITLE
Jenkins: don't publish python 3 genie_python, or at least hide it better 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3530]
User had installed genie_python_3 which didn't work for them. We currently have genie_python and genie_python_3 sat next to each other in the "Releases" folder,  as we don't support python 3 yet we should either remove this or put it into a "test" subdirectory to avoid accidental install

**Comment by FreddieAkeroyd** [comment]
I've created a "test" folder in Releases for the moment

**Comment by DominicOram** [comment]
We're now on python 3, this is no longer relevant
