### ISSUE TITLE
Reflectometry: Add logging to IOC

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3535]
As a user/developer, I would like logging to be added in relevant places in the reflectometry server to track its behaviour and facilitate diagnosing any issues that may arise.

### Acceptance Criteria

Is existing logging suffiecient and consistent?
On move either all beamline parameters print there new position if in mode or changed
On move of paramaeter there new position if in mode (or it is this parameter)
On driver move all set points sent are recorded (with engineering corrections).
Consider writing all logs to central log so it is shown in the server (see put log message server but using the log port )

**Comment by ThomasLohnert** [comment]
Do we still need this ticket or is it acceptable to just add sensible logging when and where we touch the code? I feel like the current level of logging in the reflectometry IOC is adequate. @John-Holt-Tessella thoughts?

**Comment by John-Holt-Tessella** [comment]
I like this approach, I think I would like to have a quick review though.
