### ISSUE TITLE
Reflectometry: 3D coordinates

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3536]
Currently, the reflectometry server tracks component positions in a 2D coordinate system in the vertical beam plane. In order to enable running experiments in vertical sample mode, and to future proof the system for other use cases that require 3D positioning of components, the horizontal X coordinate (perpendicular to the beam direction) should be added.

**Comment by John-Holt-Tessella** [comment]
Not needed, horizontal and vertical modes on INTER convered by separate configs.
