### ISSUE TITLE
Reflectometry: Readback values

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3538]
As a user, I would like to be able to see the readback values from the actual physical devices and resultant values for beamline parameters on a reflectometer.

**Comment by ThomasLohnert** [comment]
Started on branch `Readback_from_components_to_parameters`

**Comment by John-Holt-Tessella** [comment]
Pull requests:

1. https://github.com/ISISComputingGroup/genie_python/pull/146

**Comment by ThomasLohnert** [comment]
Minor rework mostly related to code readability / documentation:
- [ ] [inst_servers](https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/176)
- [ ] [IocTestFramework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/140)
