### ISSUE TITLE
Reflectometry: Do not move unchanged components

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3539]
As a user on a reflectometer, I only want components to move to their setpoint if they have actively been changed (i.e. prevent motor twitching if they are slightly off the setpoint after the previous move). To do this, components need a changed flag, same as beamline parameters do, which is taken into account when recalculating positions down the beamline.

**Comment by ThomasLohnert** [comment]
Rework done. PRs:
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/190
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/174

**Comment by aaron-long** [comment]
While reviewing I found these two bugs which tickets have been created for:
- https://github.com/ISISComputingGroup/IBEX/issues/4251
- https://github.com/ISISComputingGroup/IBEX/issues/4252
