### ISSUE TITLE
DAE: add support for TOF v Pixel live view

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3545]
For 1D detectors a two dimensional view of TOF v pixel would be very useful. This should not be hard to add as all the information is pretty much already available.

**Comment by FreddieAkeroyd** [comment]
To test see "1d detector with TOF axis" section of https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Live-View

**Comment by Tom-Willemsen** [comment]
How would a user set this currently? I think it probably needs a control on the OPI

**Comment by FreddieAkeroyd** [comment]
There is a ticket to add user control #3575 however it could currently be set up by writing to PVs as detailed on the wiki, which is what we do for the existing liveview. As multiple detector device screens can be created, setting the PVs would only need to be done once and so an OPI is a bonus but not essential at this stage
