### ISSUE TITLE
IMAT: move galil 5 from ethernet to serial

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3546]
Galil 5 (the 40x0 model) suffered another failure and required a power cycle. The issue has been raised with Galil via motionlink, in the meanwhile Steve Cox has asked if we can put the galil onto serial. 

- I believe there is already a serial cable there, but not sure which moxa port it is using
- check baud rate jumpers, we normally use 115200
- I though the galil 20x0 needed to have software flow control enabled, the 40x0 manual would seem to suggest rts/cts is the only option and always enabled. 
- Rather than an IP address the connection string is e.g. "COM23 115200"

**Comment by GDH-ISIS** [comment]
IMAT GAlil_05 now converted to serial with Baud Rate at 38400. Appears to be ok. Network cable now disconnected.

Note : Galil found with red light on – no ping. On power cycling, network recovered with no problems. Tried to remove the program in the Galil all together, but it defaults to using all 8 threads and a default program.

**Comment by DominicOram** [comment]
I've confirmed that they galil is set up to be serial and spoke to Winfried about it yesterday, he said it's now running ok so closing this as reviewed.
