### ISSUE TITLE
ZOOM: move PGC galil from ethernet to serial

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3547]
For same reasons, and with same procedure, as in #3546

**Comment by KathrynBaker** [comment]
#3522 Has the serial details for ZOOM as it currently stands

.

**Comment by FreddieAkeroyd** [comment]
Thanks - we increased baud to 38400 and it looks to be talking, but we haven't moved anything

**Comment by KathrynBaker** [comment]
I’ve asked them to get in touch ASAP if they notice any issues with the axes on that controller, so hopefully it will all be OK.
