### ISSUE TITLE
MK3 Chopper OPI: Make 'Local control mode' more obvious

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3550]
Currently the OPI displays a green LED when the chopper server is in remote mode i.e. working normally for the scientists.  However, when in local mode (i.e. unable to do anything remotely and potentially affect data collection), the LED goes out which is not entirely obvious as to what has happened.  An alarm is also generated in this case, but often ignored.

The suggestion here is to change the 'Remote' indicator to 'Local' and display a red (possibly flashing) LED instead.  The OPI could even go so far as to disable all of the controls when in local mode and only display the 'Local LED' to make it even more obvious what the problem is.

**Comment by Kevin-Woods-Tessella** [comment]
If we disable all the controls when the chopper is in "local" mode, how does the user re-enable the controls?  Do they have to go to the chopper console and restore "remote" access?

I think you could do the following:
1. Leave the "Local" indicator 'as is'.
1. Remove the generation of an alarm (if it gets ignored more often than not, then why have it?)
1. Add a "Remote", which behaves as you suggest.
1. Log every change to/from local/remote mode.

**Comment by John-Holt-Tessella** [comment]
I would like the alarm view to become more useful please don't remove the alarm.

Adding the remote alarm is a good idea. We should make it obvious with a description that appears when it is in local mode. I.e. in local mode a description reading "Chopper is set in local mode, this means you can not change any setting. Chopper can be switch to remote mode only on the front panel by you local contact".

**Comment by kjwoodsISIS** [comment]
OK.  If we want to keep the alarm, that's fine by me.

I think the local-mode description is a good idea.  How about the following wording:
"Chopper is set to local mode.  In local mode, the chopper setings cannot be changed via IBEX.
To change the chopper settings via IBEX, the chopper must be set to remote mode.
The chopper can only be switched to remote mode by your local contact (via the chopper front panel)."
