### ISSUE TITLE
ISISDAE: do counts  / microsecond calculation on server

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3559]
It would be best for the DAE to serve counts and count rate per microsecond as two distinct PVs rather than the calculation from counts to counts / microsecond being done client-side.

This would also enable a future move towards using the standard CSS widgets for the spectra graphs.

**Comment by Tom-Willemsen** [comment]
Could you add some documentation on the wiki about what each of the PVs are and what they mean.

**Comment by FreddieAkeroyd** [comment]
Added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-PVs
