### ISSUE TITLE
GUI: add TMIN/TMAX cutoff parameters to live view

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3568]
Ticket #3545 added some new PVs to control the (min,max) time of flight window to be used in calculating a live view integral. The live view OPI needs to be updated to display these new variables. 
 
I don’t know if it would work better to add them to the existing options box or create a new box e.g. “TOF Window”. The relevant PVs are:

Min TOF cutoff (readback)                $(DAE)INTG:TMIN
Min TOF cutoff (setpoint)                 $(DAE)INTG:TMIN:SP
Max TOF cutoff (readback)               $(DAE)INTG:TMAX
Max TOF cutoff (setpoint)                $(DAE)INTG:TMAX:SP

If space is short, as readback and SP should always be the same the following would be adequate:

TOF Window:   Min  $(DAE)INTG:TMIN:SP  Max  $(DAE)INTG:TMAX:SP

**Comment by aaron-long** [comment]
Work for this has already been completed. See release notes for 5.1.0.
