### ISSUE TITLE
Deploy: Release

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3573]
As a developer I want an IBEX release so I can install it on the instrument machines for the start of machine physics on 29th Oct.

Acceptance Criteria:

- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [ ] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)

Full release not needed because of shutdown. Just do targeted testing,

**Comment by FreddieAkeroyd** [comment]
Install on TOSCA, INES, OSIRIS as new migrations

Also install on MERLIN for #3626 and related

**Comment by Tom-Willemsen** [comment]
Targeted testing of DAE-related changes done - I didn't find any new bugs by running the manual system tests. 

@FreddieAkeroyd has put in a last-minute fix to the ISISDAE ioc (potential pop from empty list), once this is built into the release then it is ready to deploy to the beamlines that need it.
