### ISSUE TITLE
LiveView: add setup menu to OPI

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3575]
As detailed in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Live-View there are a few setup values that need to be set for a liveview display, these are currrently done by setting the PVs separately as they were unlikely to change, but it is possible loading different wiring tables will necessitate changing the parameters. As this is less likely, it should be in a separate "setup" menu.

staring spectrum number for detector pixels  %MYPVPREFIX%DAE:AD1:INTG:SPEC:START:SP 
Size of detector in direction of increasing spectrum number %MYPVPREFIX%DAE:AD1:INTG:SPEC:SIZEX:SP 
Size other detector dimension %MYPVPREFIX%DAE:AD1:INTG:SPEC:SIZEY:SP 
This is TOFSummed or TOFChannel  %MYPVPREFIX%DAE:AD1:INTG:DATAMODE:SP 
Histogram or event source mode %MYPVPREFIX%DAE:AD1:INTG:SPEC:MODE:SP 
Any rotation to apply to image %MYPVPREFIX%DAE:AD1:rawimage1:Type

**Comment by aaron-long** [comment]
Work for this has already been completed.
