### ISSUE TITLE
INES: Sample Changer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3576]
As a scientist working on INES, I want a Sample Changer OPI, so that I can select the sample to be placed in the beam.

#### Acceptance Criteria
1. The IBEX GUI must report which sample position is currently in the beam
1. Using the IBEX GUI, I can change which sample position is currently in the beam
1. I can use genie_python to change which sample position is currently in the beam 

#### Notes
1. The Sample Changer on INES is controlled by a McLennan.
   * [INES Sample Changer (top view)](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_Sample_Changer_top.jpg) and [INES Sample Changer (McLennan)](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_Sample_Changer_McLennan.jpg)
1. The INES Sample Changer has 4 arms (i.e. 4 positions).
   * [INES Sample Changer (bottom view)](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_Sample_Changer_below.jpg)

**Comment by John-Holt-Tessella** [comment]
Base mclenan

**Comment by ThomasLohnert** [comment]
Done as part of config migration.
