### ISSUE TITLE
INES: Neutron Camera Positioner

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3577]
As a visiting or instrument scientist working on INES, I want to move my neutron camera in/out of the beam so that I can perform imaging or diffraction experiements as appropriate.
As an instrument scientist (but not as a visiting scientist) working on INES, I want to be able to position my neutron camera at any point on its axis.

#### Acceptance Criteria
1. The IBEX GUI must report whether the neutron camera is IN or OUT of the beam
1. Using the IBEX GUI, I can move the neutron camera to be IN the beam
1. Using the IBEX GUI, I can move the neutron camera to be OUT of the beam
1. I can use genie_python to change the neutron camera position to be IN or OUT of the beam
1. As an instrument scientist (but not as a visiting scientist) I can move the neutron camera to any position on its axis (i.e. greater control over camera position, using Manager Mode).

#### Notes
1. The INES neutron camera is mounted on a single vertical axis.  It is moved up to be in the beam, down to be out of the beam.
   * [INES neutron camera positioner](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_XY_Table_and_Neutron_Camera.jpg)
1. The instrument scientist would like a positive indication that the neutron camera is in position (e.g. an LED that illuminates when the camera is IN the beam; a separate LED that illuminates when the camera is OUT of the beam).

**Comment by John-Holt-Tessella** [comment]
This is a Galil motor. Should be in-out setpoint

**Comment by ThomasLohnert** [comment]
Done as part of the config migration using motion setpoints on the galil but need to implement the two position LEDs in a sensible way. The motion setpoints OPI currently only provides one for whether it is in target position or not.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/812
https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/11
