### ISSUE TITLE
INES: XY Table

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3579]
As a scientist working on INES, I need an OPI so that I can control the XY table.

#### Acceptance Criteria
1. The IBEX GUI must report the current settings of the XY table
1. Using the IBEX GUI, I can move the X-axis (perpendicular to the beam) of the XY table.
1. Using the IBEX GUI, I can move the Y-axis (parallel to the beam) of the XY table.
1. I can use genie_python to move the X- and Y- axes to any desired position 

#### Notes
1. The XY table is driven by a Galil controller.
   * [INES XY Table](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_XY_Table_and_Neutron_Camera.jpg)

**Comment by ThomasLohnert** [comment]
Done as part of config migration.
