### ISSUE TITLE
INES: Goniometers

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3580]
As a scientist working on INES, I need an OPI so that I can control the Goniometers.
INES has two Goniometers: one large, one small; so perhaps we will need two OPIs

#### Acceptance Criteria
1. The IBEX GUI must report the current settings of the Goniometer
1. Using the IBEX GUI, I can move the Goniometer to the desired orientation
1. I can use genie_python to move the Goniometer to the desired orientation

#### Notes
1. The check the SECI VI(s) used to control the Goniometers; replicate its (their) functionality.
1. The Goniometers are driven by a Galil controller.
   * [INES Goniometer](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_Goniometer.jpg)

**Comment by ThomasLohnert** [comment]
These are simply two motor axes (small and large goniometer).  These can be controlled via the generic sample stack OPI along with the XY table positions. The only change they requested is that the sample OPI displays the units for each axis.
