### ISSUE TITLE
Danfysik OPI: emphasise power more strongly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3583]
From James Lord:

> On the magnet supply OPIs, the Power indicator should go in the top box along with Current, etc, be labelled “Power” instead of “Status” (the PV is POWER of course), have a green LED like the one on the overview, and have separate “On” and “Off” buttons instead of the drop down selector. At the moment it’s hiding below the Interlock status, suggesting it is of low importance.

Fix is applied to normal and daisy chained Danfyiks

**Comment by DominicOram** [comment]
Review as part of https://github.com/ISISComputingGroup/IBEX/issues/4348
