### ISSUE TITLE
IBEX Discussion Forum

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3587]
As a scientist, I would like an on-line discussion forum for IBEX, so that I can exchange ideas, hints & tips about using IBEX with my colleagues.
As a developer, I would like an on-line discussion forum for IBEX, so that I share hints & tips with scientists and can also monitor it for discussions that might point towards the need for new features.

#### Acceptance Criteria
1. As a scientist or developer I am able to logon to an IBEX discussion forum 
1. As a scientist or developer, I can contribute to on-line discussions.
1. As a scientist or developer, I can receive a regular digest of posts via e-mail (configurable to be, say, weekly or monthly).
1. As a designated developer, I can administer the on-line discussion forum.

#### Notes
1. The Mantid team use [Discourse](https://www.discourse.org/) on their external cloud server (they run it in a Docker container).  We could do something similar on an internal server or even better piggy back on their server.
   1. Contact Martyn Gigg on the Mantid team for details on Discourse

**Comment by Tom-Willemsen** [comment]
Impeded, waiting for SCD to set up a suitable machine (visible to an external network).

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen : have SCD set up a suitable machine yet?

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen : any news on a suitable machine?

**Comment by ChrisM-S** [comment]
Silly question, but can SCD set up a discourse instance as a service or are they leaving us with a machine which we then need to support/upgrade/manage separately?

**Comment by Tom-Willemsen** [comment]
Currently they are just giving us a linux machine. It is up to us to configure/support/upgrade/manage the discourse instance.

**Comment by kjwoodsISIS** [comment]
OK.  So, for us to make progress with this ticket, we need SCD to fire up a Linux machine for us.  Have they done so?  If yes, then we can make progress (i.e. we can set up the Discourse instance) and this ticket is no longer impeded.  If no, what is stopping them from doing so?  Are they waiting on something from us?  If so, what?

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - what is the status of this ticket?  Have we got the Linux machine?  What is stopping progress?

**Comment by Tom-Willemsen** [comment]
No - `Access denied`

**Comment by Kevin-Woods-Tessella** [comment]
@FreddieAkeroyd , @Tom-Willemsen - any more news on this?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd, @Tom-Willemsen - any more news?

**Comment by Tom-Willemsen** [comment]
It looks like a machine is there and possibly ready to set up, but I think Freddie was chasing up some issues about whether this machine was suitable long-term (the last I had heard, SCD said we were on an "unsupported" machine configuration).

**Comment by FreddieAkeroyd** [comment]
Machine has now been recreated as somehow I had created a machine type i was not supposed to be able to create! Also now DNS registered as ibex-forum.isis.stfc.ac.uk

**Comment by Tom-Willemsen** [comment]
Discourse set up on scd cloud. Not currently accessible from outside - looks like there is some firewall around the SCD cluster (can access from another machine on the cluster, can't access from outside the cluster). @FreddieAkeroyd has sent an email to scd support asking whether it's possible to open the relevant ports on the firewall

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - have SCD responded to your query?  If so, what was the response?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd has received new instructions for SCD (on how to create a certificate).  Please share the instructions so that this ticket can be completed.

**Comment by Tom-Willemsen** [comment]
The discourse install is up at https://ibex-forum.isis.stfc.ac.uk/ 

There is some administration documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Discourse

I added https://github.com/ISISComputingGroup/IBEX/issues/4353 to investigate other auth methods in future

I suggest we keep the forum within our group for a week or so until we are all used to it and happy with the setup, at which point we can advertise it to the scientists.
