### ISSUE TITLE
IOC Generator: Get rid off extra files commited on EPICS branch.

### ISSUE THREAD

**Issue by ghost** [ISISComputingGroup/IBEX#3588]
As a developer, I want the IOC device generator not to add any extra files committed to the main EPICS branch of the IOC so that I can not spend time cleaning up git when creating IOCs.

**Comment by John-Holt-Tessella** [comment]
This includes the main epics branch.

**Comment by Rory-Potter-Tessella** [comment]
The work so far has been done on `TIcket3588_get_rid_of_extra_files_commited_to_EPICS` branch in the IOC device_generator repository.

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/9

**Comment by kjwoodsISIS** [comment]
Return to Backlog (Sprint Planning 25-04-2019 decision).
Re-consider with all reflectometry tickets

**Comment by GRyall** [comment]
This ticket is no longer relevant following the creation of the [device-generator](https://github.com/ISISComputingGroup/IBEX-device-generator)  and deprecation of the device_generator
