### ISSUE TITLE
Allow acknowledgement of alarms in alarms view

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3594]
As a user I would like to be able to acknowledge alarms as seen. CSS allows you to do this via its authorisation mechanism. See https://github.com/ControlSystemStudio/cs-studio/blob/master/core/utility/utility-plugins/org.csstudio.security/preferences.ini

## Acceptance Criteria
* The alarms in the alarms view can be acknowledged
* This does not affect borders around blocks
* It is documented and discussed with users when the alarms reappear

**Comment by ThomasLohnert** [comment]
+1 from INES

**Comment by Tom-Willemsen** [comment]
+1 MAPS who would like to acknowledge that their MK3 chopper is in local mode.

**Comment by KathrynBaker** [comment]
This has now been implemented.
