### ISSUE TITLE
GUI: Redesign icons for Disc Choppers

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3597]
As a user, I would like to see icons for disc choppers in the synoptic and device screens in the same "3D" style as the others.  After recent makeovers for both the T0 and Fermi chopper icons, the disc now looks a little out of place.

**Comment by daryakoskeroglu** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1404

**Comment by rerpha** [comment]
Looks good, could you add to release notes pls?

**Comment by daryakoskeroglu** [comment]
Oh yes, sorry! Here is the link to PR for release notes: https://github.com/ISISComputingGroup/IBEX/pull/7079
