### ISSUE TITLE
Reflectometry: 3494-1 Improve OPI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3604]
#3494 was the start of creating an IOC. The TODOs need to be fixed also:

1. Icon for reflectometry
1. Heights of labels should be same as template
1. Ask instrument scientists if they want the spinners
1. Point stop and move to correct PVs
1. Maybe move jaw gaps to left, sample stack next then beamline parameters to right

**Comment by ThomasLohnert** [comment]
- Left to Right = More general to more instrument specific 
- Connect sample stack and HGap widgets to PVs. 
- Consider disabling controls for parameters not in mode
