### ISSUE TITLE
IOC: Automatically auto-start on add

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3605]
The "Auto-start" option is a leftover from a time before users "added" IOCs to a config. Adding an IOC to a config should just automatically set auto-start on it, and we should get rid of the option in the GUI.

Auto-restart should also be set by default as we only do not want it in edge cases.

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/839
