### ISSUE TITLE
Run java remote monitoring on instrument machines

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3606]
As a developer, it would be helpful if I could remotely monitor memory/cpu/thread usage of java applications.

To do this, there is a utility that comes with a JDK called `jstatd` which lets the java visual VM connect to remote applications (for monitoring only; remote debugging is not supported).

Remote monitoring is documented here: https://docs.oracle.com/javase/8/docs/technotes/guides/visualvm/applications_remote.html and `jstatd` is documented here: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jstatd.html

Doing this ticket would help with https://github.com/ISISComputingGroup/IBEX/issues/3574

**Comment by kjwoodsISIS** [comment]
We ought to check the licensing conditions of `jstatd` - some Java components now attract licensing fees.

**Comment by DominicOram** [comment]
Check after install that it doesn't grab too much resource

**Comment by DominicOram** [comment]
jstatd will give us memory usage but not CPU. For CPU we will need to add jmx flags to the client (https://docs.oracle.com/javase/8/docs/technotes/guides/visualvm/jmx_connections.html)

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/859

**Comment by DominicOram** [comment]
This means only one client can be started, rethink
