### ISSUE TITLE
NICOS: Update to release version

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3609]
We are currently using the master branch of nicos. This will cause a problem when deploying as nicos expects to either be in git or have a release file. Once nicos creates it's latest release we should move over to it

**Comment by DominicOram** [comment]
I've contacted the collaboration to ask when we can expect the next release

**Comment by John-Holt-Tessella** [comment]
If the release can not be made place a file called `RELEASE-VERSION` in `EPICS\ISIS\ScriptServer\master\nicos` containing a random version number, otherwise the server will fail to start.

**Comment by Tom-Willemsen** [comment]
Since nicos have not made a release, I will add a step to the deploy script to add the file as above.
