### ISSUE TITLE
RIKENFE: update RB3 / RB4 banner messages

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3615]
As a scientist on RIKEN I would like the messages in the banner to be:

“RB3 off: ports 1,2 safe” in black
“RB3 on: beam to ports 1,2” in red
“RB4 off: ports 3,4 safe” in black
“RB4 on: beam to ports 3,4” in red

To do this we need to create a new PV which monitors the underlying power supply PV, has the above strings as it's states, and goes into alarm (or not) to make the messages red

**Comment by Tom-Willemsen** [comment]
Note: this change is already on RIKEN

**Comment by John-Holt-Tessella** [comment]
Pull requests:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/329
