### ISSUE TITLE
LOQ: IOC and OPI for Julabo "small" configuration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3621]
As a LOQ scientist, I want IBEX to support the Julabo water baths on my instrument, so that I can use them with IBEX in my experiments.
LOQ has two Julabo water baths (labelled WB13 & WB14), both of which are currently configured to use the LabVIEW "small" configuration.
The existing Julabo IOC & OPI should be extended (or new ones created) which replicate the functionality of the LabVIEW "small" configuration.

#### Acceptance Criteria
1. I can control Julabo water baths WB13 & WB14 via the IBEX GUI
1. I can control Julabo water baths WB13 & WB14 via genie_python

#### Notes
1. This ticket supersedes #3477.
1. LOQ has two Julabo water baths (labelled WB13 & WB14).
   1. Both water baths use the LabVIEW "small" configuration (see [Julabo Commands](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/backend_system/IOCs/julabo_commands.xlsx) spreadsheet for details)
1. The Julabo IOC is constructed from a number of "building blocks".  Adding support for the "small" configuration should be a matter of including the appropriate building blocks (see the Julabo Commands spreadsheet).
1. According to the model numbers printed on the Julabo cases, both are FP51 models.
   * [Julabo 1 is labelled WB13](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/LOQ/LOQ_Julabo_1.jpg)
   * [Julabo 2 is labelled WB14](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/LOQ/LOQ_Julabo_2.jpg)
The [Water Baths](https://www.isis.stfc.ac.uk/Pages/Water-Baths.aspx) page contains a look up table, matching the labels WB13 and WB14 to Julabo model numbers.  Unfortunately, the table contradicts the numbers printed on the cases.  The table claims that WB13 is a FP52-SP model and WB14 is a FP52-SL model.  We should follow the information in the Julabo Commands spreadsheet.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/333
- https://github.com/ISISComputingGroup/ibex_gui/pull/829
