### ISSUE TITLE
LOQ: "Julabo" Valve (IOC & OPI)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3622]
As a LOQ scientist, I want to control a valve which is used to control which water bath is used to thermostat the sample environment.  The valve is called the "Julabo" valve, but it is not a Julabo manufactured device.  It is merely an electrically-operated solenoid valve, which controls which water bath is connected to the sample changer.

#### Acceptance Criteria
1. The IBEX GUI must report the current state of the "Julabo" Valve
1. Using the IBEX GUI, I can set the state of the valve to Julabo 1 or to Julabo 2. 
1. I can control Julabo valve via genie_python.

#### Notes
1. The Julabo valve is most often controlled via a script.
1. Other instruments (e.g. SANS2D) also use a "Julabo" valve.
1. Check the functionality of the "Julabo" valve VI in SECI and replicate its functionality.

**Comment by GDH-ISIS** [comment]
I have been informed that there is no formal documentation for this - it is on the to do list of the SE group. I do not think we currently need it to write the ioc - it is only a couple of commands as highlighted above. The vi is simple.

**Comment by John-Holt-Tessella** [comment]
Why do we not need to write the IOC? Do they not want to control it? Or does this mean it will be replaced within 3 months? As you say there are only 2 commands the IOC will be really quick.

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella - I think you mis-read @GDH-ISIS 's comment.  What Gareth is saying is that the command set of the Julabo valve is so trivial, we don't need a manual to write it.  We can just look at the VI and translate it into an IOC.

**Comment by GDH-ISIS** [comment]
I think it might be worth commenting that there are some Genie procedures that have some logic in them for this - the file is : 
\\ndxloq\c$\Users\spudulike\Documents\Configurations\COMMON\gcl\loq_routines.gcl.
The procedures are called PROCEDURE J1 and PROCEDURE J2.
The logic might be possible within an ioc - the instrument scientists may have an opinion for this.

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/331
https://github.com/ISISComputingGroup/EPICS-Wbvalve/pull/1
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/4
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/132

**Comment by John-Holt-Tessella** [comment]
I have sent an email to the instrument scientists asking about this logic. It will be done as a new ticket if it is needed.

**Comment by Tom-Willemsen** [comment]
There is still a review comment pending from last time - the terminators don't between the emulator and the support module.

**Comment by kjwoodsISIS** [comment]
Can we please get this ticket completed promptly.

**Comment by aaron-long** [comment]
I had forgotten to push the branch. It's updated now.
