### ISSUE TITLE
LOQ: Aperture Device

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3623]
As a LOQ scientist, I want to control the position of the aperture device (i.e. move it to any of 7 defined positions).  The aperture device has 3 open positions (corresponding to open apertures) and 4 closed positions (corresponding to solid portions of the aperture device).

#### Acceptance Criteria
1. The IBEX GUI must report the current state of the LOQ aperture device (i.e. which of the 7 aperture positions is selected)
   * the GUI must report whether the current position is an open aperture or a closed position.
1. Using the IBEX GUI, I can select any one of the 7 apertures positions. 
1. I can select any one of the 7 aperture positions via genie_python.

#### Notes
1. See the [LOQ-Instrument](https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details) page for details.
1. The aperture device is controlled by a Galil.
1. The aperture device is essentially a rectangular strip with 3 holes cut into it.  Different apertures can be brought into position by moving the strip left/right across the beam.
1. The aperture device has three discrete positions for normal operation.
   1. In SECI, the scientist can select any one of the 3 open aperture positions.  
   1. In IBEX, the scientist must be able to select each of these same 3 aperture positions.  In addition, he would like to be able to move the aperture device to any one of the 4 position corresponding to solid portions of the aperture strip - these are called "closed" aperture positions.  The purpose of being able to move to a closed aperture position is to block the neutron beam.
   1. When instructed to move to a closed position, the aperture device should move to the closest closed position.  This is important; closed positions will be used to protect the ORDELA detector, so the device should not spend any more time than is necessary moving to a closed position.

**Comment by kjwoodsISIS** [comment]
![image](https://user-images.githubusercontent.com/7249337/47802830-10335f80-dd29-11e8-99b8-493903e05190.png)

The LOQ aperture device is a rectangular plate, with 3 aperture holes arranged in a line.
The illustration above is a schematic drawing of the aperture plate.  Check the actual 
aperture sizes, positions & arrangement with the instrument scientist.

In the schematic drawing:
   * the 3 apertures are labelled A1, A2, A3.
   * seven positions, P1 - P7, are also identified (each marked with a red X).
   * positions P2, P4 and P6 are intended to represent the centres of apertures A1, A2, A3 respectively.
   * positions P1, P3, P5 and P7 represent "closed" positions (meaning that if the aperture device is in one of these positions, it will block the beam).

The instrument scientist wishes to be able to:
   1. move the aperture device to any of the 3 apertures
   2. move the aperture device to a closed position
      * this provides a way of blocking the beam without having to close the shutter
      * blocking the beam provides protection for the detector (e.g. when changing samples)
      * when moving the a closed position, the aperture device should be moved to the closest closed position (to minimise the time in which the detector is exposed to the beam).

Based on the above schematic, a simple algorithm could be defined as follows:
1. First of all define the concept of a "next closed position" - that is the next position that blocks the beam the device will move to if asked to move to a closed position.
1. For each position, P1 - P7, define a "next closed position" as follows:
      * P1: "next closed position" = P1
      * P2: "next closed position" = P3
      * P3: "next closed position" = P3
      * P4: "next closed position" = P5
      * P5: "next closed position" = P5
      * P6: "next closed position" = P5
      * P7: "next closed position" = P7
1. The "next closed position"s are deliberately chosen to minimise the amount of movement when the device is asked to move to another position.
   * for P1, P3, P5 and P7, the "next closed position" is always the current position; therefore, if the device is already at a closed position and it is asked to move to a closed position, it will simply stay where it is.
   * for P2, P4 and P6, the "next closed position" is always an adjacent closed position; therefore, if the device is asked to move to a closed position, it will move to a nearby position.
   * for A2 (the central aperture), it is moot as to which is the "next closed position".  It could be either P3 or P5: a choice has to be made.
1. When the user requests that one of the 3 apertures be selected, simply move to the corresponding position and update the "current position" & the "next closed position" (using the above table).
1. When the user requests that the aperture be closed, simply move to the "next closed position" and again update the "current position" & the "next closed position" appropriately.
1. The positions P1 - P7 are, of course, position set points.  P2, P4, P6 are just the centres of each aperture.  P1 and P7 are  suitable points the the left/right of apertures A1/A3.  P3 and P5 are just the mid-points between A1/A2 and A2/A3.

To see how this works in practice, consider the following example:
   1. assume the aperture device is initially in a closed position (it can be any closed position, but let's say P1)
      * initialise the "current position" as P1 and the "next closed position" as P1
   1. now, suppose the scientist selects A1, then
      * move to position P2, set the "current position" as P2 and the "next closed position" as P3
   1. now, suppose the scientist wants to close the aperture, then
      * move to the "next closed position" (i.e. P3), define the "current position" as P3 and the "next closed position" as P3
   1. now, suppose the scientist selects A3, then, then
      * move to position P6, set the "current position" as P6 and the "next closed position" as P5
   1. now, suppose the scientist wants to close the aperture again, then
      * move to the "next closed position" (i.e. P5), set the "current position" as P5 and the "next closed position" as P5
   1. now, suppose the scientist selects A2, then
      * move to position P4 and set the "current position" as P4 and the "next closed position" as P5
   1. now, suppose the scientist wants to close the aperture again, then
      * move to position P5 and set the "current position" as P5 and the "next closed position" as P5
   1. now, suppose the scientist repeats the request to close the aperture, then
      * move to the "next closed position" (i.e. P5; which will (should) be a null operation, because its already at P5) and set the current position" as P5 and the "next closed position" as P5
   1. etc, etc.

It is easy to work out similar examples starting from other initial positions.

**Comment by Alistair-McGann-Tessella** [comment]
I had a chat with a LOQ instrument scientist about the positions of the apertures and stops. We shouldn't allow the system to park on positions P1 or P7, as there are microswitches on the edges of the plate which shouldn't be in the path of the beam.

The coordinates of P3 and P5 are given by (P2+P4)/2 and (P4+P6)/2, which we have from the SECI VI

**Comment by Kevin-Woods-Tessella** [comment]
@Alistair-McGann-Tessella - OK.  I guess it is straightforward to modify the algorithm to prevent use of positions P1 & P7 (in fact, come to think of it, you could just eliminate them entirely).
