### ISSUE TITLE
LOQ: Sample Changer Scan

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3624]
As a LOQ scientist, I want to use the existing LOQ Sample Changer Scan facility in IBEX.
The LOQ SC Scan allows the sample positions on the Sample Changer to be 'scanned in' using the LOQ alignment laser and the output recorded on a photocell.

#### Acceptance Criteria
1. TBD - following consultation with Gareth.

#### Notes
1. See the [LOQ-Instrument](https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details) page for details.
1. The photocell is connected to a Thor Labs Model PM100A power meter.
1. Consult with Gareth about the existing LOQ SC Scan VI (used with SECI)

**Comment by Tom-Willemsen** [comment]
I have queried whether we can use the `pygenie-scans` library for this (it is already in use for similar scan-and-optimize operations on zoom and larmor)

**Comment by Tom-Willemsen** [comment]
Shape of real data:

![image](https://user-images.githubusercontent.com/24375813/49092414-e2730500-f259-11e8-92d0-e18b4389c93a.png)

**Comment by Tom-Willemsen** [comment]
PR: https://github.com/ISISNeutronMuon/InstrumentScripts/pull/13
