### ISSUE TITLE
genie_python: wait for dae to be non-busy before changing DAE settings 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3626]
Currently if genie_python changes any DAE settings e.g. time channels or chopper vetos if needs to read all the previous DAE settings XML, make it changes, and then push them back. A problem occurs if a user changes e.g. the wiring tables in the GUI and then before that has completed issues a command in genie python that needs to change other dae settings, this command could get an outdates version of the setting onto which it makes changes and then overwrites those done by the GUI. 

There is a PV in the DAE called    $(P)DAE:STATETRANS   that indicates if the DAE is in a "state transition", this usually means it is beginning or ending a run, but this will be changed to also indicate the DAE is updating settings. It was decided that an explicit CHANGING state on the DAE, though potentially useful, could create issues as potential DAE runstates are encoded  in several places (e.g. GUI and genie python)

So this ticket should update the initial command of the genie python "change" sequence so that it does not copy the DAE settings XML if the $(P)DAE:STATETRANS  is 1 / Yes. Currently STATETRANS will not go to Yes during a DAE change operation, this will be added in another ticket. 

Using MERLIN wiring tables would be recommended during testing as they take a while to load

**Comment by FreddieAkeroyd** [comment]
To test:
If you load a big wiring table (e.g. merlin) from GUI and then try to do something from genie python it should print:  "Another DAE change operation is currently in progress, waiting..." until that change completes.

**Comment by FreddieAkeroyd** [comment]
You need to have updated to get changes from #3627

**Comment by Alistair-McGann-Tessella** [comment]
I tried to generate the warning messge that the DAE change operation is in progress using the merlin wiring tables, but the load time of the tables was quite fast (<2s). I don't this is enough time for genie python to detect the operation, and I wasn't getting the warning. Do you have any advice which could help me test this? I tried on my developer machine and ndxdemo and had the same issues.
