### ISSUE TITLE
GUI: maintain DAE "updating instrument" dialog until changes completed

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3628]
Currently when DAE settings are applied, an "updating" dialog box is displayed for a second which is not a true indication that changes have been applied. This box should be held on screen while the $(P)DAE:STATETRANS PV is Yes/1. 

A box should also appear if another client/genie python has issued a change. It would be best if this just appeared in the DAE tab in the client, so the user would not notice if they are not doing DAE orientated items.

Requires #3627 To be completed first

Related to #3626

**Comment by FreddieAkeroyd** [comment]
The DAE settings are spread across 3 PVS, i'm not sure how the gui logic is done but you may need to check STATETRANS separately for each and allow time for it to got to 1 before waiting for 0

**Comment by Tom-Willemsen** [comment]
Waiting for the DAE:STATETRANS pv works but it also triggers on beginning/ending a run which makes it flash up on screen annoyingly if the instrument is doing short runs. Could we perhaps use a separate PV for "settings change in progress" as opposed to re-using STATETRANS?

I'm reluctant to rely too much on client-side state for this (e.g. only displaying the box after the "apply changes" button is pressed) as this will confuse the issue when we have multiple clients looking at the same server.

**Comment by FreddieAkeroyd** [comment]
Could you not check RunStatus == SETUP too?

**Comment by Tom-Willemsen** [comment]
Doing that would lead to race conditions depending on which order the GUI sees the PV updates (STATETRANS going to OFF as opposed to RUNSTATE going to SETUP for instance).

**Comment by FreddieAkeroyd** [comment]
After discussion with @Tom-Willemsen  a new PV will be added to the DAE to indicate just a wiring table change, it seems the GUI logic is not easy to change to handle a more selective check. A more consistent fix, potentially involving a CHANGING run state, will be discussed in a separate ticket

**Comment by Tom-Willemsen** [comment]
PRs for this ticket:
- https://github.com/ISISComputingGroup/ibex_gui/pull/819
- https://github.com/ISISComputingGroup/EPICS-isisdae/pull/48/files

**Comment by kjwoodsISIS** [comment]
How many points?
