### ISSUE TITLE
OSIRIS: Be filter motor set points and Lakeshore IOC

### ISSUE THREAD

**Issue by LiamPanchaud** [ISISComputingGroup/IBEX#3629]
As an OSIRIS scientist, I don't want both motor set points and an absolute movement option to be present in the OPI. This could be confusing for users, and IN/OUT is not adequate for the way that the Be filter is used.

This is a very quick fix, just delete a part of the OPI.

**Comment by LiamPanchaud** [comment]
Also:
- Add a third Lakeshore 218 for the Be Filter and point OPI to the third one

**Comment by kjwoodsISIS** [comment]
The description above says what is not required.  Can you please state what **_is_** required.

**Comment by LiamPanchaud** [comment]
The OPI contains a motion set points panel (which is a linking container) that the scientists want removed in favour of keeping only the absolute position panel so that they have transparent ocntrol of its position
