### ISSUE TITLE
POLARIS : Galil communication issue

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3632]
Polaris called 01-10-2018 outlining motors that did not move on GALIL_02. Motors left in a "motors are moving" state also. Looks like they were in an unconnected state since 28-09-2018
Date : 28-09-2018
Time : 10:33:02 Connected
TIme : 10:33:05 Time out error while uploading program.

No red error light on Galil. It does not ping from ndxpolaris. The Galil is a DMC2280 (not a 4280). Other Galil units ping ok.

**Comment by GDH-ISIS** [comment]
Galil looks fine on serial.
![poalris_galil_02](https://user-images.githubusercontent.com/13995522/46290509-efd68080-c583-11e8-9620-dc0624474d1f.jpg)

**Comment by GDH-ISIS** [comment]
Original Ping
![polaris_galil_02_ping](https://user-images.githubusercontent.com/13995522/46290723-8014c580-c584-11e8-8850-36326fa660f2.jpg)

**Comment by GDH-ISIS** [comment]
No program running in Galil - all threads are in a stopped state.

**Comment by GDH-ISIS** [comment]
Last error is reported as a bad Ethernet packet. Galil clock looks fine - no wrap around.
![polaris_galil_02_error_and_time](https://user-images.githubusercontent.com/13995522/46292304-7e4d0100-c588-11e8-9cdf-ebdd032c4fb5.png)

**Comment by GDH-ISIS** [comment]
Set IP address to 0.0.0.0 - then re-applied the IP address it should be on. No change. No power cycle at this point.

**Comment by GDH-ISIS** [comment]
Anthony Shuttle confirmed traffic at the network switch port was going out to the Galil - nothing coming back.

**Comment by GDH-ISIS** [comment]
After Serial "RS" command, ethernet comms established and I think looks fine. Left serial cable in on COM21, 115200 baud.

**Comment by GDH-ISIS** [comment]
Re-homed axes one at a time. No problems. All back with instrument scientist now.

**Comment by GDH-ISIS** [comment]
This has happened again on 09/11/2018 - could not find out anything from the DMC 2280 unit as it was not possible to communicate with it. Details were :

NO red error light.
Ping to Galil IP address from ndxpolaris DID work - no problems.
Ethernet communication would not connect (using hyperterminal).
Serial communication on COM21 115200 Baud did not return any characters.

The only way to recover was to power cycle the unit. Everything then worked.

**Comment by John-Holt-Tessella** [comment]
This happened again on 12/11/2018 this time it was pingable but the serial connection had died. Did restart see #3747
