### ISSUE TITLE
LOQ: Thar Pressure Cell

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3633]
As a LOQ scientist, I want to use Thar Pressure Cell in conjunction with a Eurotherm.
In essence, a Eurotherm device simply measures the voltage generated by a sensor.  Depending on the type of sensor and how it is calibrated, a Eurotherm can be used to measure temperature (the most common application) or pressure.

#### Acceptance Criteria
1. A calibration file to convert sensor voltages into pressure readings.
   1. The calibration file to contain appropriate metadata defining the pressure units.

#### Notes
1. See the [LOQ-Instrument](https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details) page for details.

Requires #2133

**Comment by John-Holt-Tessella** [comment]
We may need to allow different directories to be set for the base of the calibration file (e.g. pressure sensors), think about this. See ticket #2133 which might cover some of this.

**Comment by John-Holt-Tessella** [comment]
Where is the eurotherm can we talk with it directly or is it via something else.

**Comment by Tom-Willemsen** [comment]
Support for this device is additionally requested for LARMOR (as well as LOQ).

**Comment by Tom-Willemsen** [comment]
Having spoken to @Alistair-McGann-Tessella this is just a Eurotherm measuring temperature (*not* pressure) with no calibration file. There is no work needed to support this device, it is simply a matter of configuring the eurotherm as usual and selecting `None.txt` as the calibration file.
