### ISSUE TITLE
IOC : Blocked Port : Failover

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3634]
When an IOC is asked to restart via procserv, would it be possible to see whether the port is available first. If the port is already in use, use a failover port instead. 

Alternatively, would it be possible to use dynamic port allocation for processes, also highlighted in ticket https://github.com/ISISComputingGroup/IBEX/issues/1484

**Comment by FreddieAkeroyd** [comment]
This depends on the IOC. Most IOCs use dynamic ports for epics traffic anyway as 5064 is never going to be free for everybody. The block archive engine uses port 4813 for its web interface, this could be adjusted dynamically but all dependencies on this port would need to be told about the new port too. In this case the ISISDAE needs to know to be able to restart and check on the engines,  but also nagios needs to know the port to send alerts when it isn't responding properly. So possible with some caveats.

**Comment by John-Holt-Tessella** [comment]
Can we set the ports to be reusable?

**Comment by FreddieAkeroyd** [comment]
A lot of this can be covered by  #4314
