### ISSUE TITLE
JSON_Bourne: Discuss High bandwidth usage

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#3635]
As a developer I would like ot investigate the bandwidth used by JSON Bourne.

I noticed that the InstrumentInformationCollator() call uses quite a high amount bandwidth. This is due to the fact it pulls JSON info for Blocks (~2k per instrument) and INST (~500k) every 3 seconds. On my machine my network performance in task manager is showing 50Mbps average.

We need to have a meeting to discuss if there is a better solution.

**Comment by KathrynBaker** [comment]
Hopefully going soon, and it has been in this state for a long time now.
