### ISSUE TITLE
IMAT: cachannel error in script

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3639]
> Via footprints:
> 
> Script crashed because of CaChannelExecption Error; 
> 
> Certainly not a sporadic crashed, as it happened at exactly the same step of 
> the script. I think it is a comminication/time out problem.
> 
> Reported by: Winfried Kockelmann 

Screenshot:

![image](https://user-images.githubusercontent.com/24375813/46411726-6f935500-c714-11e8-8760-b9924802be07.png)

**Comment by Tom-Willemsen** [comment]
PV pointing at one of the monitors timed out. Not clear why - I thought the DAE IOC would serve those PVs quickly even if the DAE itself was busy? Anyway I have replied to winfired offering to:
- Increase the timeout in the script
- Put a retry around the function so that if there is a problem the script recovers

**Comment by GRyall** [comment]
Support issue from over 5 years ago. Not clear what could be actioned in this ticket.
