### ISSUE TITLE
GUI: Danfysik OPI - separate buttons for on/off

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3641]
Reported by Aidy via footprints - specifically referring to RIKENFE but there is potential for the same issue on MUONFE as they use the same danfysik OPI.

> When turning a magnet on and off (RB3) using the IBEX Client GUI. The focus 
> remained on the on/off dropdown menu. Moving the mouse and slightly moving the 
> roller ball turned the magnet supply off when it was on. The focus is not shown 
> so you have no idea what the roller ball will change. It would be very useful 
> to have a send button.

It is probably best to give them separate on/off buttons on the OPI which will prevent the issue mentioned above, while staying consistent with other OPIs

**Comment by DominicOram** [comment]
As part of this ticket we should check that we're not using drop downs in other OPIs that could be worrying if accidentally set.

**Comment by aaron-long** [comment]
OPI Change: https://github.com/ISISComputingGroup/ibex_gui/pull/817
IOC Sim mode fix: https://github.com/ISISComputingGroup/EPICS-ioc/pull/327

**Comment by Tom-Willemsen** [comment]
Incidentally, there was a message about a very similar issue on tech-talk just now and it looks like this issue is fixed on the CS-Studio end https://github.com/ControlSystemStudio/cs-studio/issues/2276
