### ISSUE TITLE
Instrument time does not respect timezone changes

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3643]
As a user I would like the instrument time to accurately reflect the system time on the instrument computer (or always report in a consistent time zone such as UTC).

To reproduce bug:

- `camonitor %MYPVPREFIX%CS:IOC:INSTETC_01:DEVIOS:TOD`
- Change system timezone
- Notice that IOC is still updating the time but is not respecting the new timezone setting
- Restart `INSTETC_01`
- The time is now correct and respecting the new timezone setting

This might potentially catch us around the GMT/BST transitions. I noticed this when reviewing https://github.com/ISISComputingGroup/IBEX/issues/3243

**Comment by FreddieAkeroyd** [comment]
I'm not sure it will be a problem, I think GMT/BST is handled by a change of daylight saving time rather than a change of timezone, and the underlying "struct tm" has an "is daylight saving" flag which is set by localtime()

**Comment by FreddieAkeroyd** [comment]
If you just turn off "adjust for daylight saving time" in windows control panel rather than changing timezone does it work OK?

**Comment by FreddieAkeroyd** [comment]
I'm still not sure we have found a real problem. EPICS uses the C RTL strftime() like the ICP and looking back i see the time in its log files jump on GMT/BST. I think the C runtime library may cache the timezone and daylight saving time changeover rules on startup, so it will behave correctly when the march/october summer time switches are due, but not notice a changes in the external system until an ioc  restart and then the CRTL will load the new data. It might be calling tzset() explicly in the code would make it pick up an external change, but i think this is maybe a heavy operation as it has to read timezone files on disk as well.

**Comment by FreddieAkeroyd** [comment]
Procserv certainly jumps e.g. blockserver log from IMAT

[Sun Mar 25 00:43:52 2018] [1521938632.72] INFO: GIT: Nothing to commit
[Sun Mar 25 00:48:53 2018] [1521938933.24] INFO: GIT: Nothing to commit
[Sun Mar 25 00:53:53 2018] [1521939233.81] INFO: GIT: Nothing to commit
[Sun Mar 25 00:58:54 2018] [1521939534.32] INFO: GIT: Nothing to commit
[Sun Mar 25 02:03:54 2018] [1521939834.92] INFO: GIT: Nothing to commit
[Sun Mar 25 02:08:55 2018] [1521940135.42] INFO: GIT: Nothing to commit
[Sun Mar 25 02:13:55 2018] [1521940435.83] INFO: GIT: Nothing to commit

**Comment by FreddieAkeroyd** [comment]
I left a "camonitor -t cs" running yesterday and it moved from BST to GMT OK  

IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:59:57.991380(2018-10-28 01:59:58.176802) 10/28/2018 01:59:57  
IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:59:58.989675(2018-10-28 01:59:59.179939) 10/28/2018 01:59:58  
IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:59:59.992431(2018-10-28 01:00:00.187393) 10/28/2018 01:59:59  
IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:00:00.990341(2018-10-28 01:00:01.172022) 10/28/2018 01:00:00  
IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:00:01.991154(2018-10-28 01:00:02.185928) 10/28/2018 01:00:01  
IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:00:02.992455(2018-10-28 01:00:03.186135) 10/28/2018 01:00:02  
IN:LARMOR:CS:IOC:INSTETC_01:DEVIOS:TOD 2018-10-28 01:00:03.992649(2018-10-28 01:00:04.186393) 10/28/2018 01:00:03

**Comment by DominicOram** [comment]
@Tom-Willemsen @FreddieAkeroyd Can we close this off as if it's OK for BST/GMT then I see no way this is likely to affect us?
