### ISSUE TITLE
GUI: Blocks should be limited in length

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3647]
If the block name is too long it does not get passed correctly to `addToSet`. It gets truncated in the run control settings file:

```
[2018-10-09 15:30:08] dbLoadRecords("C:/Instrument/Apps/EPICS/support/RunControl/master/db/runcontrol.db","P=TE:NDW1032:,PV=TE:NDW1032:CS:SB:rcptt_d5436e501bad4797b281a0ee")

[2018-10-09 15:30:08] Can't set "TE:NDW1032:CS:SB:rcptt_d5436e501bad4797b281a0ee:RC:_SEQ.STR2" to "TE:NDW1032:CS:SB:rcptt_d5436e501bad4797b281a0ee"
```

If it is much too long then you get:
```
[2018-10-09 16:50:54] Can't create record "TE:NDW1798:CS:SB:a23456789012345678901234567890123456789012345678901234567890123456789012345678901245678901234568789012345678901234567801234567865604:RC:HIGH" of type "ao"
```

1. Find out what the limit is for this and place a restriction in the gui configuration.
1. Write a test which checks that the run control works for long pv names.
1. Check all current configurations for blocknames that are too long.

Work out what `addToSet` (`EPICS\support\asubFunctions\master\asubFunctionsApp\src\setFunctions.c`) does and add documetnations to function and to records (`record(aSub, "$(PV):RC:_OUT:DO")`, `record(sseq, "$(PV):RC:_SEQ")` that calls it (in EPICS\support\RunControl\master\db\runcontrol.db).

See #2773 for limit in archiver

**Comment by John-Holt-Tessella** [comment]
Add to config checker

**Comment by John-Holt-Tessella** [comment]
+1 Seen on LOQ in the wild

**Comment by John-Holt-Tessella** [comment]
Block limit is 20.

18 character for prefix + CS:SB: total length into the PV is 40 characters so 20 is a nice number.

This can be lengthened when EPICS 7 is done #4416

Make sure this does not invalidate too many blocks before adding it by using config checker.

**Comment by kjwoodsISIS** [comment]
Consider enforcing a limit of 80 in the GUI, so that no-one can violate the EPICS 7 limit.

**Comment by FreddieAkeroyd** [comment]
Should we consider  https://github.com/ISISComputingGroup/EPICS-RunControl/pull/14 (a fix for #5215) at the same time? currently a block name is limited by a 40 character pv limit due to an intermediate string record, the PR increases this to 60 chars for the PV. This is the "We should instead fix run control with epics 7." which should allow longer block names

**Comment by FreddieAkeroyd** [comment]
After above PR, the previous logic `Then 60 characters for a pv name so PV + block prefix and instrument and :AC:_CALCSCAN postfix: 60 - 18 - 13 = 29.` will apply.  So a block could theoretically be 29 characters, do we leave at 20 or increase to say 25 ?

**Comment by boeuf-codes** [comment]
Pull requests: 
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/368
- https://github.com/ISISComputingGroup/InstrumentChecker/pull/41
- (release notes) https://github.com/ISISComputingGroup/IBEX/pull/7288
