### ISSUE TITLE
IBEX: Training (1st November 2018)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3648]
As an instrument scientist, I would like to participate in the Introduction to IBEX and genie_python with IBEX training courses so that 
1. I can learn how to use IBEX
1. I can support visiting scientists

As an IBEX developer, I would like more instrument scientists to receive training in IBEX so that they can use IBEX with minimal support from me.

The next training courses are scheduled for the 1st November 2018.

#### Acceptance Criteria
- [x] Advertise training
- [x] Book venue
   - [x] CDF room in Atlas Centre has been booked
- [x] Assign trainers
- [x] Review course materials
- [x] Send delegate list to CDF
- [x] Send joining instructions to delegates
- [x] Book tea & coffee (but not lunch) as necessary
- [x] Set up machines
- [x] Deliver training
- [ ] Apply retrospective changes to process/wiki/slides

#### Notes
1. Additional instructions for setting up training can be found here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
1. The courses are scheduled as follows:
   - 1st November 2018 (AM): Introduction to IBEX
   - 1st November 2018 (PM): genie_python with IBEX
These are two separate courses.  Delegates will be expected to purchase their own lunch.

**Comment by Tom-Willemsen** [comment]
This is impeded until the training retrospective on Friday.

**Comment by ThomasLohnert** [comment]
Follow-up ticket for reworking training material: https://github.com/ISISComputingGroup/IBEX/issues/3792

**Comment by davidkeymer** [comment]
Considered reviewed as the training session went ahead, a retrospective meeting was held and a ticket for improving the training material was created.
