### ISSUE TITLE
GUI: Pin Views

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#366]
As a scientist, I want to pin some views to the GUI window, so that they are always displayed and I can't "lose" them.

'''Acceptance Criteria'''
1. I can pin any view within the GUI window.
1. The position of a pinned view does not change.

'''Notes'''
1. Pinning a view limits the scope for re-arranging other windows.
1. May be consider dividing GUI window into two areas:
   1. a region where views can be (or are) pinned
   1. a region where views can float
1. This story might be redundant if users have an easy way to recover "lost" views.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 367.  Created by skn09965 on 2014-04-04T14:49:25, last modified: 2015-01-07T11:37:50_

**Comment by AdrianPotter** [comment]
Following discussion with Dom. Ticket relates to not losing things like banner, block display etc. This is now true so marking ticket as complete
