### ISSUE TITLE
IMAT: command to move and correct stage position

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3665]
IMAT is currently using the small 3 axis portable stage, it is on galil 8 and has blocks axa, axb and axc
If we look at axis b (0802) then currently the motor is left ON (IN:IMAT:MOT:MTR0802_ON_CMD = 1)  and auto on/off is disabled  (IN:IMAT:MOT:MTR0802_AUTOONOFF_CMD = 0). If the motor is turned off, then it loses position a bit, however if it is left ON then it looks to be vibrating a bit, but it could be an encoder artifact. I briefly tried: move to P, turn off, record new position PN, turn on, move to P + (P - PN), turn off, (hopefully) it now adjusts to P which is what you wanted! They may call tomorrow asking for a python command to do this for them.

**Comment by FreddieAkeroyd** [comment]
The new command may want to manually turn motor off and on, if it sets auto on/off the problem would be just knowing for sure when it is off as there is a delay.

**Comment by GRyall** [comment]
Given time that has passed, closing this issue as it is not clear what the acceptance requirement would be at this point.
