### ISSUE TITLE
MOXA NPorts: Automate restarts

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3672]
As a support person, I'd like some simple automated way of restarting a MOXA NPort without having to log into and navigate web pages.

**Acceptance Criteria**
1. There is a simple one-line command that will connect to and restart a MOXA NPort device

**Notes**
1. There was a go-slow issue on the Muon front end that was rescued by simply restarting the Moxa NPort
1. A couple of minutes was taken looking at the manual, and as well as the web page there is a Telnet console that could potentially be scripted to make it one line to restart the NPort
1. It may be possible to expand this to other areas of the Telnet menu, but a restart is a minimum command needed
1. Ticket #3671 provides another option for this particular automation, and should be explored in time

**Comment by FreddieAkeroyd** [comment]
To test see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MOXAUTIL-command
