### ISSUE TITLE
GUI: viewing config remotely: enable scroll bars

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3677]
As a developer, I would like to be able to scroll when I am viewing a config on a remote machine (i.e. when I am not allowed to edit).

**Comment by John-Holt-Tessella** [comment]
me too!

**Comment by aaron-long** [comment]
IOC Macros

**Comment by aaron-long** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/823
