### ISSUE TITLE
IMAT: prune database

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3678]
IMAT's mysql database is 15GB, this has triggered a disk usage warning on Nagios.

Reduce database disk space by following instructions at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space

I have contacted scientists to ask them when there is an opportunity to do this.

**Comment by FreddieAkeroyd** [comment]
What is generating the data? Have you run utils\archive_rates.py ?

**Comment by Tom-Willemsen** [comment]
The most frequent entry in the database is `IN:IMAT:CS:MOT:MOVING.VAL`
