### ISSUE TITLE
FERMI CHOPPER: better logging of transient errors

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3679]
As a supporter I would like more diagnostics in the log as to transient problems. If the "interlock open" error occurs momentarily for example, it will cause the chopper to spin down, but this is not obvious without plotting the status word. To improve error tracking:

archive some of the mbbiDirect bits individually to make plotting easier

Write a message to the IOC log when the "interlock open" warning is spotted, this would be a combination of a calcout triggering a stringout using the @errlog device

It feels like the alarm system might ultimately be the place designed for this sort of thing as i think errors can be latched if needed.

**Comment by Tom-Willemsen** [comment]
I've had a discussion about this with Paul Chorley. 

The solution which we came to is:
- Put conditions that may cause the chopper to stop into the error log when we detect them (interlock, overspeed, overheat, etc).
- Put a note on the user interface saying where the logs are kept (simple version is to point the user at `C:\Instrument\var\logs\FERMCHOP`, fancy version could automatically open it)

We might not *always* be able to detect these conditions (e.g. if the interlock lasts less than a second we might not poll the chopper in that time) but it should improve diagnostics for the chopper group.
