### ISSUE TITLE
DEPLOY: Update master configuration

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3682]
The master configuration repository has got out of date. We should run the upgrade script on it and commit the result. This will cause us problems when we upgrade instruments because there will be a conflict when merging in master. Pick a longer shutdown to do this in.

This isn't important for the moment because the upgrade script will take it from 3.5.1 to 5.0.1 when the instrument is installed. However in the future this will be a pain.

**Comment by GRyall** [comment]
Closing as overtaken by 6 years of development.
