### ISSUE TITLE
GEM : Cryostat control

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3683]
GEM : Cryogenics may possibly want to use a cryostat controller that uses an Oxford Instruments Mercury controller. They did not commit to a definite requirement. LabVIEW details can be found at :

C:\LabVIEW Modules\Drivers\Oxford Instruments\MERCURY\Mercury - Cryostat.llb\Mercury - Cryostat - Front Panel.vi

Note : LabVIEW driver still going through minor development and testing.

**Comment by GDH-ISIS** [comment]
I have already started on the LVDCOM development.

**Comment by GDH-ISIS** [comment]
Work started in the following branches : 
https://github.com/ISISComputingGroup/EPICS-MercuryCryo
https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket3683_Mercury_Cryostat

**Comment by KathrynBaker** [comment]
Mercury controllers are used on GEM, there is a component for this, closing this ticket.
