### ISSUE TITLE
Check archiving rates on MERLIN and IMAT

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3686]
The nagios page https://varanus.nd.rl.ac.uk/nagios/cgi-bin/status.cgi?servicegroup=epics_archive&style=detail  indicates MERLIN and IMAT are creating over 300MB per day, most others are in the 10s of MB. We should look at ADEL values on these instruments.

**Comment by John-Holt-Tessella** [comment]
IMAT

Motor 0801 had adel and edel set to 0. Have set them to 2*ERES and manual set the axis adel so I don't have to restart. These should all be autosaved.

Also added for motors 0802 and 0803.

Taken highest frequency archiving from 5Hz to 0.5Hz

**Comment by Tom-Willemsen** [comment]
The merlin chopper ADELs have been set as part of 3679
