### ISSUE TITLE
genie_python: Confirm wiring table file paths after write

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3688]
As a scientist I want to confirm that DAE table changes have completed after I excecute change_table commands in genie python. Currently if I set an invalid wiring table path the DAE silently rejects this. I would like genie python to check the wiring table file path PVs to ensure that the write has successfully completed.

**Comment by SophieKSTFC** [comment]
The change_tables() command in genie python takes an optional three parameters to set the spectra, detector and wiring table paths. The ticket requires that all three paths are checked.

**Comment by SophieKSTFC** [comment]
Changes have been made to genie_python and system_tests. See:
https://github.com/ISISComputingGroup/system_tests/pull/13
https://github.com/ISISComputingGroup/genie_python/pull/161

**Comment by SophieKSTFC** [comment]
I have updated the features in this ticket to also cover the requirements of https://github.com/ISISComputingGroup/IBEX/issues/4330

For this, there are three new functions in genie:
```
g.get_wiring_table() 
g.get_spectra_table() 
g.get_detector_table() 
```
There are new system tests that verify that the file path returned is correct from the above functions and that when the ISIS DAE is shutdown, an exception is raised. 

No test has been written for whether there are no file paths set. This requires that /data is deleted and would be too difficult to system test, this would never happen on an instrument anyway.

**Comment by ThomasLohnert** [comment]
See comments on PRs for rework
