### ISSUE TITLE
LOQ: Write IOC for Omega WISE-7118Z temperature logger

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3689]
As a LOQ scientist I need to be able to record my detector temperature using an Omega WISE-71182Z data logger. This device has 10 analogue inputs, each of which should be able to flexibly take a thermocouple or a voltage probe.

This appears to be a modbus device.

Datasheets available at https://www.omega.co.uk/pptst/OME-WISE-7000_SERIES.html

### Acceptance criteria

 - [ ] Be able to connect a thermocouple or voltage probe to all 10 analogue inputs in the device

- [ ] These temperature/voltage measurements are exposed as PVs so they can be monitored and logged

- [ ] A NAGIOS alarm is set up to monitor the thermocouple readings

### To be confirmed

- [ ] Apply a calibration for the thermocouples to convert to temperature

**Comment by KathrynBaker** [comment]
I have been looking at the device on my desk to see about the initial talking to it (I had been asked to by Jamie Nutter), and there are some nuisances in relation to this and the network side of things. I have been unable to convert it to DHCP, as such a fixed IP will be needed for setting it in R3 - this needs to be requested, and one will be needed in R55 for use in production. Although, if it is attached to a suitable switch it can be on any network as this will need to be monitored from the central point.

To set the IP address this needs to be scanned and accessed using the Omega MiniOS7 utility software, which can be downloaded from ftp://ftp.omega.com/public/DASGroup/products/OME-WISE-7000/ or is available on a CD that is in the box with the device.

**Comment by KathrynBaker** [comment]
I’ve tried that Chris, I’m also having issues with the web pages rendering. This is also a secondary issue compared to the programming of the IOC and the two parts can be undertaken in parallel (whether this should be in a ticket or not is another discussion again).

Jamie is aware of the situation, and we are considering contacting Omega about this to at least get guidance about why it isn’t accepting the changes. It may also be worth trying it with Windows 7 as opposed to 10, and other browsers that I have yet to try. However, to access the web page you need to be able to connect to it, and the network isn’t allowing connection on the 192.168 default address the device has, and I didn’t get very far with a crossover cable either.

As this is below the NURF experiment in priority, we can probably spare it, but I’d rather keep it in G39 so that whoever picks this ticket up isn’t delayed by hunting out the hardware.

**Comment by Alistair-McGann-Tessella** [comment]
This has been moved to impeded until the issue of the WISE not being able to connect to the network through DHCP is discussed or resolved

**Comment by Kevin-Woods-Tessella** [comment]
@Alistair-McGann-Tessella - who is responsible for removing the impediment? (i.e. who is resolving the DHCP problem?).

**Comment by KathrynBaker** [comment]
We can’t remove that impediment, and at the moment there is a lack of clarity over who has the responsibility/authority – it is being discussed in a separate chain – this confusion has only come up this morning.

**Comment by Kevin-Woods-Tessella** [comment]
@KathrynBaker - can you please provide a link to the discussion chain.  Thanks.

**Comment by Alistair-McGann-Tessella** [comment]
The discussion chain was an email chain that can't be linked here. Because of the issues with the DHCP we've decided to use a different product, so this product will not be supported.

**Comment by Alistair-McGann-Tessella** [comment]
Attached is the email chain outlining this decision:

---

From: Baker, Kathryn  
Sent: 26 November 2018 12:53
Subject: RE: Omega WISE

Certainly Steve,

Do we go with:
a)	The Omega WISE that we already have, which is not ideal from a computing perspective as it requires a fixed address rather than being able to assign one dynamically
Or, do we order:
b)	Two devices that would be suitable for both computing and the hardware side of things which will not be available to use until the new year? 

Regards,
Kathryn

---

From: King, Stephen  
Sent: 26 November 2018 13:54
Subject: RE: Omega WISE

From my perspective, going by present experience, whichever unit(s) get(s) chosen is likely to be there for a decade. Which could be longer than Ibex is in use! So go with the option that is most future-proofed.

We have until Feb to get whichever unit(s) operational and integrated, so even a 4 week lead time is ok at this point.

Does that help?


Steve

---
From: Baker, Kathryn  
Sent: 26 November 2018 14:31
Subject: RE: Omega WISE

In which case, with some regret over the time already spent, and after a brief conversation elsewhere – let’s get the Moxa devices – and chalk the omega ones up to “read the manual more carefully next time” – the moxa is more likely to be future proofed – and Alistair has already beaten one into submission on a beamline already.

Regards,
Kathryn

---

From: King, Stephen  
Sent: 26 November 2018 14:35
Subject: RE: Omega WISE

Sorry Alistair! But I guess if we have others in use then commonality is an added advantage…

Ok, Jamie?


Steve

---

From: Baker, Kathryn  
Sent: 26 November 2018 14:40
Subject: RE: Omega WISE

Commonality is the main reason for my saying let’s switch our plan over. The Omega WISE is still useful, as whilst it might need a static IP address assigned, it does have a web interface that could be used for something in a pinch.

Regards,
Kathryn

---

From: Nutter, Jamie  
Sent: 26 November 2018 15:07
Subject: RE: Omega WISE

All good with me, I’ll submit an order ASAP

Cheers
Jamie
