### ISSUE TITLE
IBEX client: high CPU on ENGINX and MERLIN

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3690]
Nagios is reporting high CPU usage by the IBEX client on NDXENGINX and NDXMERLIN. 

- Find out whether this is a genuine problem
- If it is a real problem, write a ticket to diagnose and fix
- May be difficult to diagnose as it has only come up right at the end of cycle when the clients have been running a long time

**Comment by ChrisM-S** [comment]
I've put process logging on these since this morning so if there is any process info, CPU/memory etc. which might help over the next few days it's available from then on (at 15min intervals).

**Comment by Tom-Willemsen** [comment]
Today nagios reports that ENGIN-X, IMAT and IRIS are all using high CPU for ibex-client.

**Comment by Tom-Willemsen** [comment]
IMAT does not look to be caused by memory - still has 50% of the IBEX-gui's memory cap free. Unfortunately I cannot sample CPU on IMAT as they run a JRE not a JDK

![image](https://user-images.githubusercontent.com/24375813/49508567-f4b4fa80-f87a-11e8-831f-3bf7c780b988.png)

**Comment by Tom-Willemsen** [comment]
Very old ticket, we've fixed a number of these issues since this ticket was written, and the ticket does not have enough information with it to be actionable. Closing.
