### ISSUE TITLE
NDXIRIS_SETUP cannot begin a run

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3695]
NDXIRIS_SETUP was unable to begin a run, it complained about missing detetcor card 11. The card is question was from "data into dae" and not the wiring tables, it looks like the isisicp.properties file had come from WISH but not configured fully for simulation mode runniong. Following https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting I disabled the use of a data_dae card and it was able to start a run. 

I also needed to tidy up the following as this system was not set up for IBEX and so not generating any log files:
- isisicp.properties needed epicsdb = true (see above guide)
- the wiring tables were not in instrument\setting\... and so not loadable buy the GUI
- it was loading some particularly big wiring tables, these worked but would create unnecessarily larger data files. I changed it to use the "_monitorsonly" files

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - is this ticket done?
