### ISSUE TITLE
Device screens: Convert Lakeshore 218 OPI to new style

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3699]
As a user, I want the Lakeshore 218 device screen to be easier to use.

### Acceptance Criteria:

1. The Lakeshore 218 OPI has been converted to the new style.
1. Graphs update on heartbeat trigger NOT when PV updates as per new style.

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/825

**Comment by John-Holt-Tessella** [comment]
- turn off zoom enable
- turn on trace 2 concaternate
- add time label to axis with time points
- update buffer size should be 1000 for all traces
- Also are scientists happy that values are on the second page?

**Comment by ThomasLohnert** [comment]
Looks good, couple of notes:
- [ ] "Auto Zoom to Fit All" is still enabled
- [ ] I think the trace visibility controls make more sense next to the actual graph so you see immediately what you turn on/off
