### ISSUE TITLE
Archive: use MEDIUMBLOB rather than LONGBLOB for array table

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3701]
As a developer and user I do not want the isisicp to have to use unnecessary memory to process log values.

Recent changes to the ISISICP allow it to handle processing of existing array data. Such data is stored in the archive in a LONGBLOB type column, which can store up to 4GB of data. Unfortunately during testing it was discovered that the poco-mysql bindings used by the ISISICP allocate a buffer to take the max potential data size of a column entry, so it now allocates 4GB every time it checks for array data even if none is present. This memory is immediately deallocated, but causes unnecessary load on the instrument. As this logic is buried in a third party library I think the best solution is to change the column to a  MEDIUMBLOB, this will still allow an array of up to 16MB to be stored per log point.

On an existing system, you will need to run mysql as root and type:
```
USE archive;
ALTER TABLE sample MODIFY COLUMN array_val MEDIUMBLOB;
```
As this rewrites the entire table, it can take a while. On a developer computer you may wish to discard old log data first with:
```
TRUNCATE TABLE sample;
``` 
On an instrument you should do the ALTER TABLE after the archive has been backed up and truncated.

The ISISICP with array logging is not currently deployed, but is in ICP_Binaries

**Comment by John-Holt-Tessella** [comment]
Is this in our upgrade script?

**Comment by FreddieAkeroyd** [comment]
The upgrade script appears to back the database up but not drop the sample table, it would not be recommended to run this command on a big table. If we add the alter table to the upgrade script, is it OK to drop the table first too? Or is it best to leave both of these steps to do manually and just print a warning from the upgrade script?

**Comment by John-Holt-Tessella** [comment]
I think we should do the database backup as part of the upgrade script. I am happy for the moment if we just add a manual command, but it would be better if we could add it as an automated step. Did you want me to do this?

**Comment by FreddieAkeroyd** [comment]
Yes @John-Holt-Tessella go ahead

**Comment by John-Holt-Tessella** [comment]
Done manually on LARMOR

**Comment by John-Holt-Tessella** [comment]
Pull request:

- https://github.com/ISISComputingGroup/EPICS-upgrade/pull/22
