### ISSUE TITLE
Script generator: define requirements

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3702]
As a user, I would like a script generator which is integrated with IBEX.

This ticket is to generate a starting set of requirements for a script generator. There is information about the current script generators here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Script-generator

The output of this ticket should be a small collection of requirements with some idea of relative priority for the new script generator from an instrument scientist's perspective.

**Comment by Tom-Willemsen** [comment]
By "integrated with ibex" I should have said "can be integrated with ibex". There seems to be need for both an integrated and a standalone solution (but those needs should be clarified as part of this ticket).

**Comment by ChrisM-S** [comment]
Just to clarify, (only rhetorical questions)

1) the standalone script generator can be run on a different machine?
2) the scripts generated can only be run on an IBEX control machine?
    (not for example on a minimal EPICS enabled machine - like a camera server?)
3) the IBEX/Nicos scripts generated are interchangeable?
4) the script generator could have a wider use than IBEX and be a (small) product itself?

**Comment by kjwoodsISIS** [comment]
@ChrisM-S 
1. A stand-alone script generator can be run on any Windows PC, including machines external to ISIS (e.g. a visiting scientist's PC when he is sitting in his office at his home university)
1. scripts can only be run on a control machine with a NICOS engine (in general an IBEX control machine).
1. There is no such thing as an "IBEX script" or a "NICOS script".  We only support Python scripts (with the genie_python library).  The NICOS engine is a Python interpreter, so it will run genie_python scripts.
1. **No.**  A script generator that has wider use than IBEX is **NOT** in the scope of the IBEX project.

**Comment by Tom-Willemsen** [comment]
Tickets created after discussion in implementation meeting:
- https://github.com/ISISComputingGroup/IBEX/issues/4164
- https://github.com/ISISComputingGroup/IBEX/issues/4165
- https://github.com/ISISComputingGroup/IBEX/issues/4166
- https://github.com/ISISComputingGroup/IBEX/issues/4167
- https://github.com/ISISComputingGroup/IBEX/issues/4168
- https://github.com/ISISComputingGroup/IBEX/issues/4169
- https://github.com/ISISComputingGroup/IBEX/issues/4170
- https://github.com/ISISComputingGroup/IBEX/issues/4171
- https://github.com/ISISComputingGroup/IBEX/issues/4172

**Comment by davidkeymer** [comment]
Generated tickets checked.
