### ISSUE TITLE
LOQ: Script Generator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3704]
As a LOQ scientist, I need a stand-alone script generator, so that I can script sample changer operations.  The script generator needs to be stand-alone, so that I can distribute it to visiting scientists (prior to their visit to ISIS).

#### Acceptance Criteria
1. A stand-alone script generator that generates genie_python scripts with functionality equivalent to the existing LOQscript utility.

#### Notes
1. See the [LOQ-Instrument](https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details#noteSampleChanger) page for details.

**Comment by FreddieAkeroyd** [comment]
There are 3 script generator projects:

A “SANS_SCRIPT” project that creates  LOQ_Script_gui.exe
A “LOQ_Script” project that creates LOQ_Script.exe
A “LOQ_Script_GUI” project that creates  LOQ_Script_gui.exe

Repositories are https://github.com/ISISComputingGroup/SANS_Script and https://github.com/ISISNeutronMuon/ScriptGenerators Just checkout and build with VS2017

**Comment by FreddieAkeroyd** [comment]
Both LOQ_Scriopt_GUI programs can already generate python

**Comment by John-Holt-Tessella** [comment]
Is it clear which one we should use?

**Comment by kjwoodsISIS** [comment]
No, not yet.  We should check with Steve King.

**Comment by John-Holt-Tessella** [comment]
Steve says:
> Yes, the program LOQ uses at the moment is LOQ_Script.exe which produces OG. 
> 
> Now, SANS2D uses a subtly different version they call SANS2D_Script.exe, but I **think** it is the same program but with a different switch setting in the XML config file?
> 
> I don’t know anything about the _GUI apps, as in I’ve never seen them demonstrated, but I do recall a meeting where we talked – sorry, can’t remember with who – about a generic program for LOQ, SANS2D & LARMOR. We also need to include ZOOM now of course.

I think we should take the `LOQ_Script.exe` which is in `ScriptGenerators.git` `LOQ_Script\LOQ_Script` and modify all genie output to be python outputs. The lines are mostly in `LOQDataGrid.cs` and mostly script +=.

This will only be used until the new script generator is added to IBEX.

**Comment by ThomasLohnert** [comment]
Work started on branch `Ticket3704_generate_python`. They have found a different solution, moving it back into the backlog in case we want to pick this up again in the future.

I got as far as generating the script in the correct structure in terms of creating loops and indenting blocks etc. such that it executes the instructions in the [appropriate order](https://cloud.githubusercontent.com/assets/18398579/21008735/ed47c412-bd3a-11e6-9433-1dabdbfc7743.png). It does this by building a tree structure of python code blocks which gets flattened into a string at the end.

Still to be done: replace the `OPEN_GENIE` commands with their `genie_python` equivalents.

**Comment by kjwoodsISIS** [comment]
No longer required
