### ISSUE TITLE
Wiki: Wiki check improvements

### ISSUE THREAD

**Issue by LiamPanchaud** [ISISComputingGroup/IBEX#3705]
As a developer, I want the wiki checks to be more intelligent. Currently it is a matter of adding 'words' not inlcuded in the dictionary to `words.txt`, which is rapidly growing (more than 2300 words). 

We can expect `words.txt` to be relatively large becasue instrument and device (and staff) names, programming terms, etc. won't be in the dictionary so must be added to the ignored words list. 

The problem is that code (such as variable and method names) is being added to `words.txt` such as:

- `addhandlerlistener`
- `addpropertychangelistener`
- `bannercomposite`

The checker is also parsing the markdown, rather than the compiled article. This means that anchor points are being checked, such as:

- `NoteAtToCube`
- `NoteCollimator`

The solution is probably to use a markdown parser which then knows not to check for anchor points and other markdown syntax. The checker also doesn't look at words inside codeblocks (including inline code).

To do this ticket: 

- [ ] Put all code into `backticks` 
- [ ] Use a markdown parser to ensure the right parts of a document are checked
- [ ] Remove all code and markdown from `words.txt`

**Comment by LiamPanchaud** [comment]
The User manual has now been included in the wiki checks. This presents a problem because it is all in RST, rather than GitHub flavoured Markdown. This means that parts of the checking script just don't work, because RST syntax is different from MD syntax. e.g. all code snippets are ignored in MD, bu they are checked in RST because of the way that RST implemets code snippets. 

There is another error now in that this ticket will also need to include an RST compiler/parser, as well as an MD compiler/parser. 

Solutions to the issue are: 

- Keep the user manual as it is, include a new set of checks for the RST pages
  - Significant effort required to keep tests working
  - Shadow still works?
- Convert all the user manual pages to MD
  - Significant effort needed to convert user wiki to MD
  - Changes to shadow needed?
- Or remove the user manual from the wiki checks. This is the easiest, least time consuming, but least desirable in terms of test coverage.

**Comment by LiamPanchaud** [comment]
The checker also ignores symbols like `*` (reasonably).  Because RST code snippests are checked, something like `steps*i` is parsed into `stepsi` which clearly isn't a word, but the checker doesn't recognise it as code so it's being compared to `words.txt`and the standard dictionary. 

The user manual's inclusion has bloated `words.txt` significantly due to uncluding so many code variable names and things like `stepsi`

**Comment by GRyall** [comment]
The wiki checks are functionally working. This hasn't been requested again in the 6 years since submitted. Whilst it may not be the most elegant solution, the current checks work in that they produce the correct outcome (even if not by the most efficient route). Closing, can be reopened if others feel this is important.
