### ISSUE TITLE
Squish: Transfer tests

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3707]
Transfer the following tests (<class of test> <number>):

- [ ] Beam status tests 1
- [ ] Blocks Tests 1
- [ ] Congifuration Tests ~20 (some done)
- [ ] DAE Tests ~10
- [ ] Device screen tests 3
- [ ] Experiment Details 3
- [ ] Group Tests ~10
- [ ] Motor Tests 1
- [ ] Run Control Tests 4
- [ ] Scripting tests 2
- [ ] Switch instrument tests 2
- [ ] Synoptic Tests ~10
- [ ] Weblinks tests 2

**Comment by GRyall** [comment]
Given Squish tests have been running for some time, it seems unlikely this ticket is still relevant (if the work has not already been done and not tracked here).
