### ISSUE TITLE
IBEX: Meeting to define - balance real-time System Constraints against available development effort

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3709]
As one of the designers and a maintainer of the ISIS Instrument control system, I would like to ensure that that sufficient IBEX development effort is directed to making the deployed product efficient, scale-able and robust when deployed into the existing hardware and software infrastructure.

The ISIS Instrument control system is a [**real-time** [1]](https://en.wikipedia.org/wiki/Real-time_computing) system and as such needs in particular to be able to satisfy both response and reliability requirements for extended periods (24x7) usually up to the length of an ISIS cycle.

In a real-time system,  there are three key (and limited) resources which will affect this ability.

  1) CPU time
  2) Persistent local storage space (disk)
  3) Memory

It is important that IBEX as a real-time software product meets its side of the contract to manage these resources so that the system does not fail to meet the system's real-time "deadlines".  i.e. loss of data or valuable beam-time.

[1] https://en.wikipedia.org/wiki/Real-time_computing

**Comment by ChrisM-S** [comment]
### Notes:

Some key indicators of success in managing resources are that they
1) Are the minimum _reasonably_ achievable (possibly measured by benchmarking with the existing system)
2) Use is allowed to increase,  to a pre-defined maximum but the maximum is never exceeded and the recovery of resources is automated as part of the product and as has no impact on the proper functioning of the system.

**Comment by ChrisM-S** [comment]
Linked tickets to this one to address each of the three main resources, the list may not be exhaustive, available process slots and handles are example of others which may lead to other failure modes and should be monitored/controlled if necessary.

  - [ ] Memory (#3864)
  - [ ] Disk(tbd.)
  - [ ] CPU(tbd.)

These tickets should each result in an automated test (after clean building an IBEX control system) which will ensures the system continues to meet the specified requirements (from this ticket ultimately).

**Comment by kjwoodsISIS** [comment]
The meeting took place.  There is no point in leaving this open any longer.  If further tickets are required to implement the things discussed in this ticket, those tickets should be created.
