### ISSUE TITLE
GUI: Macros not changing while IOC is running

### ISSUE THREAD

**Issue by ghost** [ISISComputingGroup/IBEX#3710]
Sometimes when you try to set IOC macros when an IOC is running, they won't set.

I can't find a way to reliably replicate this. I have seen it when I do the following:

1. Click edit in configurations for an IOC
1. Change macro value
1. Do not click away just click OK
1. Click edit 
1. Edited macro is now blank

**Comment by KathrynBaker** [comment]
Unsure of this, and as I can't even link it to the reporter to make a guess as to context, closing
