### ISSUE TITLE
Journal Parser: do not build on VS2013

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3712]
Journal Parser does not build on VS2013, this is because the "slacking" module uses some c++ constructs that are not present in this version. The Makefile disables builds on VS2010 but assumes that if you are not 2010 then you will be OK.

Update Makefile to do a better version check

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - what is happening with this ticket?  Is it still required?

**Comment by kjwoodsISIS** [comment]
No longer relevant.
