### ISSUE TITLE
RIKENFE: check that alarms propagate correctly through the calibration functions

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3714]
As an instrument scientist on RIKEN I want the top-level alarms that I can see to accurately reflect the communication status with the underlying hardware.

Check that a comms alarm on the underlying hardware propagates correctly through the logic which calibrates the power supplies.

**Comment by aaron-long** [comment]
Confirmed: Alarms do propagate through the calibration functions.

I tested this using the Lewis Emulator and the  python scripts on NDXRIKEN. Previous work had ensured various calculation records had the MS flag on them to ensure alarms would pass through correctly. The RIKEN scripts set CALC fields (i.e., changing the calculation performed), so I manually wrote to these and checked against a connected/disconnected lewis emulator.

Flash reviewed by Tom.
