### ISSUE TITLE
Live view: reconfigure on larmor and zoom

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3716]
[Pending task]

Liveview has been substantially enhanced, but now some settings are in different places and it will need to be reconfigured. It is currently only used on ZOOM and LARMOR and the following settings need applying:

### LARMOR

x pixels:   512
y pixels:     80
starting spectrum:   11
spec mode : event
data mode: tofsummed
rotation:     Rot270Mirror

### ZOOM

x pixels:   512
y pixels:     192
starting spectrum:   9 
spec mode: event
data mode: tofsummed
rotation:     Rot180

**Comment by John-Holt-Tessella** [comment]
Done Lamor
Feddie has done ZOOM

**Comment by kjwoodsISIS** [comment]
How many points?
