### ISSUE TITLE
LOQ: GEC/Danfysik

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3720]
As a LOQ scientist, I need to control a GEC power supply fitted with a Danfysik control system.

#### Acceptance Criteria
1. I can control the GEC/Danfysik from the IBEX GUI
1. I can control the GEC/Danfysik from genie_python scripts

#### Notes
1. This ticket is **NOT** required for the initial migration of LOQ to IBEX.  The time-scale for installing the hardware is not yet certain, but is expected to happen sometime in Spring 2019 (but after the start of Cycle 2018/04).  
1. The existing GEC power supply on LOQ (not currently used) will be replaced by a refurbished unit sporting a Danfysik front-panel/control system.
1. Presumably, one of the existing Danfysik IOCs will be sufficient to control the PSU.  Need to check exactly which model of Danfysik this refurbished PSU appears to be.
1. Need to check with instrument scientist on what is required in terms of an OPI.
1. Also need to check whether this device should be controllable by visiting scientists or not (i.e. does it need a manager mode?).

**Comment by Tom-Willemsen** [comment]
Supply is being physically swapped now (or very soon).

Hard requirement for LOQ is for an experiment on 14th June, but the scientist would like testing time before then (at the latest w/c 13th May)

**Comment by Tom-Willemsen** [comment]
Further details:
- Uses a 25-way serial connector
- There is a 25-way cable from LOQ to the old danfysik, but this won't reach the new danfysik. The easiest thing would probably be to obtain a 25-way extension cable (15m should be sufficient). I'm not sure we currently have any of these?
- The power supply is currently plugged into the MCR controls network (but it's off/isolated). Is unplugging things from the MCR controls network within our remit or do we need to get someone from accelerator controls to approve it?

**Comment by kjwoodsISIS** [comment]
I think we should check with the accelerator controls group before unplugging it.  Also, why would it be plugged in there in the first place?  It is not a piece of accelerator control equipment.

**Comment by KathrynBaker** [comment]
We also have the option, if using a MOXA of extending with a CAT cable rather than a serial cable.

**Comment by Alistair-McGann-Tessella** [comment]
We are waiting for the danfysik to be connected physically to the LOQ cabin. I've had an email from the ISIS engineer doing this work, who expects this to be done before the end of Tuesday the 7th of May.

**Comment by Tom-Willemsen** [comment]
Basic communication with danfysik established via hterm.

- Currently in port 11 of first moxa on LOQ (COM15) but may be moved.
- Baud: 9600
- Data bits: 8
- Stop bits: 2
- Parity: None
- Danfysik address: 75
- "Remote" jumper on danfysik control board needed to be set to RS232 mode (as opposed to RS422 mode)
- Needed a 25-way null modem between the 25-way cable and the danfysik control board.

To get a status message send:
```
ADR 75<cr><lf>
S1<cr><lf>
```

**Comment by Alistair-McGann-Tessella** [comment]
PRs:

[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/384
[Device emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/35
[Support module](https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/11
[IOC test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/186)

**Comment by Alistair-McGann-Tessella** [comment]
For the reviewer: Do not move this ticket into completed until you have seen this work against the LOQ hardware.

**Comment by Tom-Willemsen** [comment]
Tested and working OK on LOQ. Steve King measured real magnetic field by dangling a hall probe into the magnet - all currents/fields as expected from the calibration curve. Also tested that an interlock (magnet water flow) could be read successfully.

There is some further work/tidying noted in https://github.com/ISISComputingGroup/IBEX/issues/4355 , which will capture the hotfixes that were done on top of this ticket to get the magnet working on LOQ.
