### ISSUE TITLE
Deploy: Truncate databases on instruments

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3721]
On Instruments on which there was no release backup and remove instrument databases.

**Comment by John-Holt-Tessella** [comment]
Done:

- ALF
- ENGINX

**Comment by Tom-Willemsen** [comment]
MAPS is not on the list above, nor was it one of the ones we released to. Is there a reason it wasn't done?

**Comment by ChrisM-S** [comment]
Might just be down to PAT testing, I will investigate its status and switch on if possible.

**Comment by John-Holt-Tessella** [comment]
Done maps
