### ISSUE TITLE
Deployment: Common config settings not being added

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3722]
The common config folder in `C:\Instruments\settings\config\commmon` was empty after deploying on TOSCA. 

We need to check the common config directories are set up correctly on INES and OSIRIS.

The deployment script should be fixed to make sure that the common config folder is set up.

**Comment by Rory-Potter-Tessella** [comment]
The instructions for setting up the common config directory can be found at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files.

**Comment by John-Holt-Tessella** [comment]
There is a function called `setup_calibrations_repository` I suspect that it errored but did not shout loudly enough. Modify this ticket for it to shout more loudly when there is an error.

**Comment by ThomasLohnert** [comment]
PR: https://github.com/ISISComputingGroup/ibex_utils/pull/31
