### ISSUE TITLE
SUPPORT: Disk space MUONFE

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3727]
Reduce the disk space usage on MUONFE.

Due to separator, created ticket #3725

Also cleared out all data file and logs to share.

Have asked for disk space increase by FIT.

**Comment by FreddieAkeroyd** [comment]
We should ask them if we can end a run, that will clear out the selog.sq3 file. It might take a while to end though (selog is 2GB). After it ends we should stop and delete the selog files so it can update the "auto vacuum" settings.
