### ISSUE TITLE
genie_python: Add a function to begin a run, collect uamps, the end the run.

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3729]
As a user, I want to call a genie_python function which begins a run, wait for a specified number of uamps, then ends the run so that it is easier for me to write scripts.

### Notes:
This arose from migrating scripts for Tosca (#3444) and reviewing the OSIRIS migration (#3446). The following function is used a lot:

```python
def run_for_uamps(uamps):
    g.begin()
    g.waitfor_uamps(uamps)
    g.end()
```
You could also allow optional arguments to change the run title/users.

This function is used in the user scripts which were migrated for TOSCA and OSIRIS so often that it is worth thinking about if it should be a `genie_python` function and not just an `inst` function as at least two instruments (TOSCA and OSIRIS) would use this a lot.

**Comment by DominicOram** [comment]
After discussion in the office @Tom-Willemsen, @FreddieAkeroyd, @SophieKSTFC and I felt that we should not do this ticket as:
* It saves a minimal amount of code duplication
* We can see the requirements growing (e.g. I want to do the same with frames)
* The API for genie_python should be as concise as possible
