### ISSUE TITLE
CSS: Update to latest version

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3731]
As a developer and user I would like the latest versions of CSS, including databrowser 3. https://github.com/ISISComputingGroup/IBEX/issues/3641 would have been fixed as part of this ticket and CSS are dropping support for db 2. There are probably a number of other features we will get.

**Comment by KathrynBaker** [comment]
This has either been done, and/or has been considered and is therefore worth considering differently at this stage.
