### ISSUE TITLE
Move Instrument PVs to Archive Appliance

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3732]
As a developer I would like to use archive appliance as it offers a number of features:
* Better optimised for time series data
* More widely used by other facilities
* Can more intelligently truncate data
* Will help us get round issues such as #2177

As a starting point for this we can move the instrument PVs (rather than block PVs) as this will cause minimal disruption.

**Comment by DominicOram** [comment]
Archive Appliance is documented at http://slacmshankar.github.io/epicsarchiver_docs/details.html.

It has the concept of different "stages" of storage, that could hold data for different lengths of time, data can also be modified as it moves through the stages (e.g. decimated). It also works with CSS out of the box.

It does not appear to have the functionality required for https://github.com/ISISComputingGroup/IBEX/issues/5770 out of the box but has a web interface for interactions like this, which they may accept additions to (http://slacmshankar.github.io/epicsarchiver_docs/api/mgmt_scriptables.html).

We would need to modify how JSON bourne retrieves the data, though they have a similar web interface for this (http://slacmshankar.github.io/epicsarchiver_docs/userguide.html).

**Comment by John-Holt-Tessella** [comment]
Can it host the data on differnet servers at differnet level. I.e. I would like to log plot a line and I want the last 30 days from the instrument and last year from the central server. (I am not sure that the current one can do that)

**Comment by DominicOram** [comment]
I think that's actually two questions:
1. Can it host the data on different servers? Yes, the "stages" can be placed on different mediums/servers.
2. Can data be pulled off these different servers intelligently, e.g. as a user if I ask for 2 days data will I get it all even if only the first day is stored locally? I think the answer here is yes, I believe CSS is clever enough to do it for you. It may also be that the archive appliance has some internal logic for it

**Comment by FreddieAkeroyd** [comment]
The documentation suggests it only runs on linux, but tomcat is available on windows. We should check with the developer if he is aware of any show stoppers that would prevent it working on linux, but we may need to do that migration work ourselves.

**Comment by DominicOram** [comment]
Oops, I missed that! It's Java though so should port relatively well. I'll get in touch with the developer

**Comment by kjwoodsISIS** [comment]
I can't attend the "How to Implement Better Archiving Solutions" meeting, but here are some thoughts:
1. The EPICS archiver appliance requires dedicated Linux hardware (if I read the web page correctly).  Do we have suitable hardware already, or would we need to purchase?
   * There seems to be a very deliberate mix of fast, medium & slow storage (at least in the way that SLAC use it).  Will we need to do something similar?
   * long-term (archived) storage seems to be a key part of the SLAC strategy. What's our equivalent?  and how would we automate it?
1. It would be useful provide an overview to the group about how the EPICS archiver appliance works and how it would collect data from each of the IBEX instances.
1. We should have an EPICS archiver appliance pilot project, to make sure we understand how it works in detail and to iron out any snags before deploying widely.

**Comment by FreddieAkeroyd** [comment]
@kjwoodsISIS if the EPICS archiver appliance requires dedicated Linux hardware then it is likely a non-starter for us, we need it to run on the NDX under windows.

**Comment by GRyall** [comment]
superseded by #7536. Closing this as a duplicate ticket.

**Comment by GRyall** [comment]
superseded by #7536. Closing this as a duplicate ticket.

**Comment by GRyall** [comment]
superseded by #7536. Closing this as a duplicate ticket.
