### ISSUE TITLE
LET: Mezei Neutron Spin Flipper

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3738]
As a LET scientist, I want to control the Mezei Neutron Spin Flipper, so that I can perform experiments with polarised neutrons.

The Mezei Neutron Spin Flipper is a collection of devices (power supplies, signal generators & control PC) housed in a mobile rack.  The control PC runs a Python script to control the power supplies & signal generators.  The Python script accepts a set of simple commands.  SECI provides a simple GUI which sends the appropriate commands to the Python script.  All IBEX needs to do is replicate the functionality of the existing SECI GUI (VI), sending the appropriate commands to the Python script running on the control PC (housed in the mobile rack).

The Mezei Neutron Spin Flipper is currently used on LET and POLREF, although it could be used on other instruments, if required.

#### Acceptance Criteria
   1. I can control the Mezei Neutron Spin Flipper from the IBEX GUI
   1. I can control the Mezei Neutron Spin Flipper from genie_python
   1. I can control more than one Mezei Neutron Spin Flipper from either IBEX GUI or genie_python.
   1. Solution to be ready for mid-Cycle 2018/04 (experiment is scheduled for 13th March).

#### Notes
1. The Mezei Neutron Spin Flipper **_will_** be used in Cycle 2018/04.
1. For details see the [LET Wiki](https://github.com/ISISComputingGroup/IBEX/wiki/LET-Instrument-Details) page.
1. There is an existing VI to control the Mezei Neutron Spin Flipper, located here: `C:\LabVIEW Modules\Instruments\POLREF\POLREF Flipper`. Consult with Goran Nilsson or Andrew Caruana for more details.
1. See also the notes provided by Tom & Gareth below.
1. For the avoidance of doubt: any mention of He3 in relation to this ticket is a red-herring (caused by an initial misunderstanding of which equipment was to be used).

**Comment by Tom-Willemsen** [comment]
Talk with Christy and Andrew (Polref) as well as LET.

It is currently controlled by an instrument-scientist written python script. Discuss whether this is the best solution. The IOC may need to run on a different computer to recieve the trigger pulse (either from the synchrotron or a chopper)

Confirm how many flippers they are using (1 or 2)

**Comment by Kevin-Woods-Tessella** [comment]
@Tom-Willemsen - is the He3 flipper on LET the same as the one on POLREF (i.e. is it the same device or the same design (if there is more than one He3 flipper))?

**Comment by John-Holt-Tessella** [comment]
Ask Rob H who is responsible for this code?

**Comment by GDH-ISIS** [comment]
The original development for this equipment came from Goran Nilsen on LET. Written with LabVIEW server and client. Used a Daq card with dual output and located on a seperate PC and four Genesys power supplies. This was then subsequently developed on the server side using a Python script by a PC under the supervision of Goran.

Subsequently, POLREF has adopted a similar system, but the system has been further developed. POLREF instrument scientist Andrew Caruana has further developed the python code, and the SECI LabVIEW client has been updated to cater for this. A version of this LabVIEW client has been put on LET.

To cut a long story short, before this work is undertaken, I think it would be worth talking to Goran Nilsen with the POLREF and LET instrument scientists for clarification of everything - there is certainly some common development here, although LET may be a single flipper, POLREF a dual Flipper.

Please note : this equipment is still going through development on POLREF. I am less certain of circumstances on LET. That said, the server client relationship has been via simple TCP protocol for both systems.

**Comment by kjwoodsISIS** [comment]
Update information from David Voneshen:  He3 spin flipper is not likely to be needed until mid-March.
> From: Voneshen, David (STFC,RAL,ISIS)
> Sent: 08 January 2019 15:16
> To: Woods, Kevin (Tessella,RAL,ISIS); Bewley, Robert (STFC,RAL,ISIS)
> Cc: Howells, Gareth (STFC,RAL,ISIS)
> Subject: RE: LET: He3 Spin Flipper
> 
> Hi Kevin,
> 
> Yes, we haven’t scheduled from 1st March yet but there will likely be an experiment 
> starting on the 13th of March which will need this (I wont be able to confirm for 
> another week or so but I am 95% sure it will be here).
> 
> If you need any more details on this I would suggest speaking to Gøran Nilsen about 
> this as it is really his equipment.
>

**Comment by Tom-Willemsen** [comment]
Andrew has given us the code used on the remote machine as a reference point, it is located here: `\\isis\shares\ISIS_Experimental_Controls\external_code\Mezei Neutron Spin Flipper`

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-Mezflipr/pull/1
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/358
- https://github.com/ISISComputingGroup/ibex_gui/pull/857
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/20
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/161
- https://github.com/ISISComputingGroup/EPICS/pull/155
