### ISSUE TITLE
LET: IOC & OPI for Astrium High-Speed Chopper

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3740]
As a LET scientist, I need to control the Astrium High-Speed Choppers on LET.

#### Acceptance Criteria
1. I can control the Astrium High-Speed Choppers via the IBEX GUI.
1. I can control the Astrium High-Speed Choppers via genie_python.
1. IBEX provides the same levels of control to the existing SECI VI.

#### Notes
1. LET has two Astrium High-Speed Choppers.
   * Previously, each Astrium chopper had its own dedicated control PC.  These PCs are now obsolete.  Each Astrium chopper is now controlled by a VM (running on NDHLET) which runs the Astrium control software.
   * In SECI, a VI communicates with each instance of the Astrium control software (via a .NET channel).
   * It is proposed that the SECI VI be replaced with an IOC & OPI, the IOC communicating with the Astrium control software.
1. For more details see the [LET Wiki](https://github.com/ISISComputingGroup/IBEX/wiki/LET-Instrument-Details) page.

**Comment by John-Holt-Tessella** [comment]
This might need to create .NET connection from IOC, @davidkeymer and @FreddieAkeroyd to check

**Comment by FreddieAkeroyd** [comment]
I believe the code for the Astrium chooper is at https://github.com/ISISComputingGroup/AstriumChopper

In there is a project for a test client, my guess will be that the other projects build a .NET dll that is used by the test client. So IBEX will need to do something along the same lines as the Mk3Chopper which:
* Builds Mk3BridgeLib which exports C style functions that call the .NET remoting functions. 
* Has an asyn EPICS IOC that calls these exported C functions.

**Comment by DominicOram** [comment]
Minor changes to DbChecker: https://github.com/ISISComputingGroup/EPICS-DbChecker/pull/4
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/347
Support added to top (work on support repo was done on master) https://github.com/ISISComputingGroup/EPICS/pull/151
Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/152
OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/844

**Comment by Tom-Willemsen** [comment]
- [ ] I think the restriction that chopper speed must not be 180Hz should be implemented in the IOC, not just in LET's control scripts.
- [ ] The support module doesn't compile under VS 2017, the error is:
```
C:\Instrument\Apps\EPICS\libraries\master\boost\include\boost/type_traits/detail/is_member_function_pointer_cxx_11.hpp(129): error C2764: 'C': template parameter not used or deducible in partial specialization 'boost::is_member_function_pointer<Ret(Args...) const>' [C:\Instrument\Apps\EPICS\support\astriumchopper\master\AstriumBridgeLib\AstriumBridgeLib.vcxproj]
```
Having spoken with @FreddieAkeroyd we think boost is unable to correctly handle managed types
