### ISSUE TITLE
LET: Prepare to Migrate to IBEX

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3741]
As a developer, I want to complete the preparatory steps prior to migrating LET to use the IBEX instrument control system.

#### Acceptance Criteria
1.  [x] Facilities IT have confirmed they will create a private network on LET 
1.  [x] NDXLET has sufficient free disk space to install IBEX 
1.  [x] IBEX has support for the devices used on LET 
1.  [x] The version of the ICP program on LET has been checked 
1.  [x] Configuration files matching the current SECI config files used on LET are created 
1.  [x] LET scripts are converted to genie_python
1.  [x] LET configuration files and genie_python scripts are tested on a test instance of IBEX

#### Notes
1. The devices on LET are listed on the [LET Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/LET-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for LET.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   - Done (30-11-2018)
   - [LET VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/LET/LET_VLAN_Settings.txt)
- [x] Check that NDXLET has sufficient disk space to install IBEX
  * LET has NN-Gb of free space.
- [x] Check whether LET uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, plan to upgrade the ICP program (to permit 8-digit run-numbers)
- [ ] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXLETTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
      * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [x] test these configurations & scripts
   - [x] check that all the devices previously supported by SECI (on LET) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
      * training cancelled (scientists have attended previous training sessions)

**Comment by kjwoodsISIS** [comment]
@davidkeymer - is this ticket complete?  After all, LET is running IBEX already!
