### ISSUE TITLE
SURF: IOC and OPI for Julabo "small" configuration

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#3742]
As a SURF scientist, I want IBEX to support the Julabo water baths on my instrument, so that I can use them with IBEX in my experiments.
SURF has two Julabo water baths (labelled WB7 & WB30), both of which are currently configured to use the LabVIEW "small" configuration.

#### Acceptance Criteria
1. I can control Julabo water baths WB7 & WB30 via the IBEX GUI
1. I can control Julabo water baths WB7 & WB30 via genie_python

#### Notes
1. SURF has two Julabo water baths (labelled WB7 & WB30).
   1. Both water baths use the LabVIEW "small" configuration (see [Julabo Commands](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/backend_system/IOCs/julabo_commands.xlsx) spreadsheet for details)
1. The Julabo IOC is constructed from a number of "building blocks".  Adding support for the "small" configuration should be a matter of including the appropriate building blocks (see the Julabo Commands spreadsheet).
1. According to the [Water Baths](https://www.isis.stfc.ac.uk/Pages/Water-Baths.aspx) list, both are FP50 models.
   * Julabo WB7 is a FP50-MH model
   * Julabo WB30 is a FP50-HE model

**Comment by Kevin-Woods-Tessella** [comment]
See also related ticket: #3621

**Comment by John-Holt-Tessella** [comment]
Won't fix see #3621
