### ISSUE TITLE
JASCO : HPLC Pump [Time Box 2d]

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3743]
There is a requirement to control a HPLC Pump from a company called JASCO remotely from our instrument beam lines.
There is no ISIS LabVIEW driver. The support group would like this to be available reasonably soon - potentially February 2019. IBEX and SECI beam lines.

The documentation that I aware of can be found at (it includes a command set) :
C:\LabVIEW Modules\Drivers\Jasco PU-4180 HPLC Pump\Documentation

Contact : Andy Church, Thomas Charleston

During the first 2 days if it is not easay report back instead of doing driver.

**Comment by FreddieAkeroyd** [comment]
Andy Church has asked if we could create a driver ASAP as he would like to order more before Christmas, but doesn't want to place the order until we have confirmed they work.

**Comment by kjwoodsISIS** [comment]
Apparently, the intention is for the JASCO HPLC pumps to replace the old Hitachi HPLC pumps (starting in February).

**Comment by davidkeymer** [comment]
Manual now in shared area.

**Comment by GDH-ISIS** [comment]
The pump operated as I would have expected. There is some capacity for some future scope as well with the adoption of event mode. It feels as though it may be a little old i.e. the serial baud rate is 4800 and the documentation is a scanned pdf. That said, it did what was asked of it. Specifics follow.

**Comment by John-Holt-Tessella** [comment]
Comments copied to web page https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/JASCO-HPLC-Pump.
JASCO ticket created and Kevin informed to find out when to schedule this.
