### ISSUE TITLE
SURF: IOC and OPI for Keyence LK-G laser positioning sensor

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3745]
As a SURF scientist, I want IBEX to support the Keyence LK-G laser positioning sensor, on my instrument, so that I can control it from IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing SECI VI.
1. I can control the Keyence LK-G laser positioning sensor via the IBEX GUI
1. I can control the Keyence LK-G laser positioning sensor via genie_python

#### Notes
1. For the avoidance of doubt, the Keyence LK-G laser positioning sensor is **NOT** the same thing as a Keyence TM3001-P Optical micrometer.
1. There is an existing VI for the Keyence LK-G laser positioning sensor. Please consult it when creating the IOC & OPI.
1. Documentation for the Keyence LK-G laser positioning sensor: `C:\LabVIEW Modules\Instruments\INTER\Keyence LK-G`

**Comment by John-Holt-Tessella** [comment]
Stream one or two commands

**Comment by KathrynBaker** [comment]
7 functions in the LabView, so more than one or two commands, but not that many, certainly stream device

**Comment by aaron-long** [comment]
- SUPPORT: https://github.com/ISISComputingGroup/EPICS-Keylkg/pull/1
- GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/864
- IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/362
- Device Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/23
- IoC Test Framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/164
- EPICS: https://github.com/ISISComputingGroup/EPICS/pull/158

**Comment by LiamPanchaud** [comment]
Good stuff so far. Just a few small changes and some extra tests as noted in the review comments
