### ISSUE TITLE
IOC: IBEX - Galil comms stop

### ISSUE THREAD

**Issue by IainJohnson** [ISISComputingGroup/IBEX#3749]
Hello,

When I visit IMAT to help with the tomography stages, IBEX and the Galil are not talking with no outward indication (not sure if I've looked everywhere mind!)

To fix I must stop the IOC, cycle the Galil power, wait, start the IOC. This fixes it for the duration of my visit but gives up sometime after I leave.

(Servostep Galil 4040, ethernet, private, axes 0801 0802 0803)

**Comment by John-Holt-Tessella** [comment]
Also see #3521 which is error appears to be cleared on move.

**Comment by IainJohnson** [comment]
Hi John, thanks. In my case on IMAT, trying moves did not clear it. However this is a 4nnn family Galil, so the issue in #3520 might be similar.

**Comment by ChrisM-S** [comment]
I may be out of touch, but I thought this Galil was on serial?  If so, there will be indication of activity (green,orange) lights on the MOXA ports in the network cabinet outside the pod.

**Comment by FreddieAkeroyd** [comment]
The 4000 series fixed galil on IMAT is on serial, this is a portable 4 axis galil that is currently on ethernet (192.168.1.208). It has been used before with no issue, but that is true for the other 4000 series ones in the hall too. @IainJohnson do we need to convert this to serial?

**Comment by IainJohnson** [comment]
Hi @FreddieAkeroyd

No comms on arrival:
1/11/18 0800ish stopped IOC, cycled power, started IOC, ok
8/11/18 1545ish restarted IOC, did not clear, stopped IOC, cycled power, started IOC, ok.

Serial:
We could change this to use Serial if we think it's suffering from the same problems as the other 4000 rack mounted Galils, although having access to the serial port with my laptop and Galil tools is useful for debugging the motion stages themselves.

**Comment by IainJohnson** [comment]
To clarify, this is Galil 8, a flatbed DMC4040 housed inside a stepservo crate, usually mounted in the detector rack behind the sample position. It has the ip 192.168.1.208.

BUT I've taken it upstairs on top of IMAT to try these stages offline, so it is not currently plumbed to the IMAT network.

It does have a serial connector that we *could* use, but I'm currently using that to debug the motions using Galiltools on my laptop.

**Comment by FreddieAkeroyd** [comment]
@IainJohnson Let us know what you want to do, it is easy enough to swap IBEX to use serial for this.

**Comment by John-Holt-Tessella** [comment]
Check it is not fixed in latest driver.
