### ISSUE TITLE
EMMA: Fermi Chopper Lift OPI: consider levitation state of chopper

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3751]
Currently a user of the above OPI is able to operate the lift regardless of whether or not the chopper is levitated.  (There is a hardware interlock and so no harm can be done, but it's still possible to ask the motor to move.)  On doing so, the motor position updates and looks like all is well.  However, as there's no encoder, all that is happening is the that the motor step count is changing (although it's not physically moving).

The suggestion is to read the "levitation state" of the chopper via an existing PV, display it on the lift OPI and use it to control the enablement state of the "raise" and "lower" buttons.

It was also suggested that the wording of the warning on the OPI be changed from "Please do not attempt to move the chopper while it is _running!_" to "Please do not attempt to move the chopper while it is _levitated!_"

**Comment by John-Holt-Tessella** [comment]
Is there already a PV that shows this (If there is please put a reference to it )?

**Comment by SophieKSTFC** [comment]
As a user of the Fermi Chopper Lift OPI I also want to be able to use the raise or lower buttons if the SKFMB350 is disconnected.
