### ISSUE TITLE
MARI: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3753]
As a developer, I want to migrate MARI to use the IBEX instrument control system.  As a scientist I would like to migrate MARI to IBEX before the December 2018 shutdown, so that it does not clash with commissioning activities taking place in January 2019.  The ideal time would be the December maintenance day - 5th December 2018.

#### Acceptance Criteria
1. IBEX is installed on MARI
   1. The IBEX server boot script is installed (see [IBEX auto-startup](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup))
1. Configuration files matching the current SECI config files are created 
1. MARI is added to the list of available instruments.
1. IBEX is configured for the devices on MARI.
1. MARI scripts are converted to genie_python
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
1. IBEX is tested on MARI

#### Notes
1. The devices on MARI are listed on the [MARI Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MARI-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for MARI.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   - Done (30-11-2018)
   - [MARI VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/MARI/MARI_VLAN_Settings.txt)
- [x] Check that NDXMARI has sufficient disk space to install IBEX
  * MARI has 12Gb of free space.
      - MARI now has 27GB of free disk space (see comment below)
- [x] Check whether MARI uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [ ] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXMARITEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
   - [x] test these configurations & scripts
   - [x] check that all the devices previously supported by SECI (on MARI) are supported by IBEX

**Comment by kjwoodsISIS** [comment]
Does MARI have only 12Gb of free space because its disk is full of old files, or because it has a small hard drive?  How much space could be made available if the disk were purged of old files?

**Comment by kjwoodsISIS** [comment]
64GB!!  I can buy a laptop with a 500GB hard drive for less than £500!

@ChrisM-S  - can we get the hard drive on MARI upgraded in time for Cycle 2018/04?

**Comment by ChrisM-S** [comment]
I don’t think it should be necessary, the system disk is a virtual disk (adjusted to take as little scientific data space as possible from the physical drive on which they both sit).

The original SECI capacity for the system disks on the instruments was around 45GB and I added just under 20GB for the IBEX upgrades over time as I’ve been round the machines, MARI was moved up to 63GB along with the others.  This allows about 10GB for IBEX files/logs and another 10GB for unusual database growth. There is a spreadsheet here (http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Usage%20of%20Instrument%20C%20Drives%20vs.%20Capacity%20and%20Free%20space%20(14th%20December%202018).xlsx) which shows the current status of all the instrument drives, capacity, free space and space used.  Generally the IBEX machines seem to be fitting in with this fairly well.

There was some variability on the “junk” level for the SECI systems so if after checking MARI appears to have less than 10GB which can be retrieved we could up the size a bit.

If there is nothing too obvious I can take a look, but it’s usually possible to pull back a few GB by running up treesize (as admin) to get 20GB or so free to allow the installation.  The wastebasket, ICP log folders, multiple copies of LabVIEW modules are generally good places to look!

**Comment by ChrisM-S** [comment]
Sorry, github included my final bracket in the previous link when it emailed it out, hopefully this will translate OK.

http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Usage%20of%20Instrument%20C%20Drives%20vs.%20Capacity%20and%20Free%20space%20(14th%20December%202018).xlsx

**Comment by ChrisM-S** [comment]
MARI now has 27GB free

**Comment by ThomasLohnert** [comment]
Review notes:
- MARI seems to still be producing 5-digit run numbers. Has the ICP been updated?
- It looks like the [motor setup](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX#copy-across-the-motor-setup) has not been copied over yet
- The instrument info page says they don't want users changing the settings on the T0 and Fermi choppers. Please double check they are happy with the OPIs since they do let users fiddle with the settings.

**Comment by Tom-Willemsen** [comment]
Email sent to scientists regarding the point above, impeded awaiting reply

**Comment by Tom-Willemsen** [comment]
Set up on MARI, instrument scientists have approved change.
