### ISSUE TITLE
NICOS: Update to release

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3762]
NICOS now have a release that we can use, we should update to this (see https://github.com/ISISComputingGroup/IBEX/issues/3609)

**Comment by kjwoodsISIS** [comment]
What new features, bug fixes, etc. does this new release provide?

**Comment by DominicOram** [comment]
Release notes are here: https://forge.frm2.tum.de/cgit/cgit.cgi/frm2/nicos/nicos-core.git/commit/?h=3.4.0 The major new feature is the changes to the transport protocol, which were done for us to be able to use NICOS. We're currently on the master branch that has these changes but it would be good to be on a proper release.

**Comment by kjwoodsISIS** [comment]
I don't see any mention of "editing on-the-fly".  Is it scheduled for a future release, or did I miss it in a previous release?

**Comment by DominicOram** [comment]
I don't think we're sure about the status of the editing on the fly stuff at all. There's a separate ticket to look into it at https://github.com/ISISComputingGroup/IBEX/issues/3737. The update to the latest version is unrelated I think?
