### ISSUE TITLE
Web Dashboard Fails to work for users with Internet explorer

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3766]
As a user of an ISIS instrument I cannot connect to the Web dashboard to see the status of my running instrument (on SECI _or_ IBEX)
The Web dashboard site at http://dataweb.isis.rl.ac.uk is broken for users of Internet explorer with the rl.ac.uk extension set to compatibility mode.  more details in controls ticket https://github.com/ISISComputingGroup/ControlsWork/issues/539 but 
 somewhere the logic to allow switching sites for IBEX or the SECI dashboard is broken by a server test and needs fixing. This problem is evident in the default IE installation on Windows 7 and also the new standard installation on Windows 10.

Acceptance Criteria:

1. The redirect to ibex/seci works under internet explorer 11 compatibility mode

**Comment by ChrisM-S** [comment]
### Note:
I think this now stands at a least +3 support calls now (last one to be confirmed).  Whilst there is a configuration solution to each client, there are a lot of clients which we cannot easily change so a more urgent server solution is required.  This could be as simple as just listing explicit links on the jump off page which work for all cases.

**Comment by ChrisM-S** [comment]
Hi @Kevin-Woods-Tessella, apparently it's the use of Jquery which is not available in IE when forced into compatibility mode (IE7 emulation).

**Comment by kjwoodsISIS** [comment]
Thanks Chris.  But this problem didn't exist in the previous cycle.  What made it happen this time?  Are you saying that Jquery was introduced into the environment during the shutdown?

Also, what services at ISIS still rely on having an IE7 compatible browser?  Do scientists really need access to these from a control server?  Not being able to run modern components like Jquery is a real hindrance.

**Comment by ChrisM-S** [comment]
It was actually reported on MUSR on October 3rd and I had another scientist in my office a few days later (9th Oct) where I had to find out what was going on and how to fix it for the client - this is all documented in controls task (https://github.com/ISISComputingGroup/ControlsWork/issues/539).  I created an IBEX task yesterday when I realised this was going to keep happening unless the logic on the server website was changed - which I think is Jason Bourne (IBEX) code?  It's just when I realised with websites, you can't fix the users, you have to fix the site or the problems will just keep returning and taking up our time!  No one is running IE7, just up to date IE11 with the 

> "Display intranet sites with compatibility view"

 check box ticked.

**Comment by kjwoodsISIS** [comment]
But why, in 2018, does anyone need to run IE11 with the "Display intranet sites with compatibility view" box checked?

**Comment by ChrisM-S** [comment]
A very good question – but this is how it is currently deployed, even to Windows 10!

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella I think it was introduce this cycle when we did the ticket #3048

**Comment by kjwoodsISIS** [comment]
Given the e-mail below, does use of the UK SBS Oracle Portal still require the use of IE11 with the "Display intranet sites with compatibility view" box checked?  Please check whether the UK SBS Oracle Portal can be used by IE11 with the "Display intranet sites with compatibility view" box unchecked.

> From: Facilities IT (RAL)
> Sent: 27 November 2018 09:40
> To: Facilities IT (RAL); ISIS Department (Staff); ISIS Instrument Scientists + Others;
> CLF Full mailing list; SC (RAL); Hartree Staff RAL
> Subject: FW: Oracle update
> 
> Dear All,
> 
> Following our previous message, we have now rolled out a fix which will allow you to 
> log in and use the UK SBS Oracle portal using Internet Explorer.  The fix will automatically 
> apply to your Windows computer the next time you restart your machine.  Alternatively, you 
> can force the fix to apply without restarting by doing the following:

> 1)  Close down all open Internet Explorer windows.
> 2)  Open the Windows Command Prompt (type “cmd” in the search box next to the 
>     Windows start button).
> 3)  Type in the following:  gpupdate /force and then press the return key.
> 4)  After a brief delay, the fix will apply and you will see that the command 
>     completed successfully.
> 5)  Open Internet Explorer and log in to the UK SBS Oracle portal. 
> 
> If you would like further assistance then please do not hesitate to contact us on x8822 
> or by emailing fitservicedesk@stfc.ac.uk 
> 
> Best regards,
> Facilities IT

**Comment by KathrynBaker** [comment]
change is not related to the functionality and needed support for compatibility mode – if you want more information, please ask me on Thursday.

**Comment by kjwoodsISIS** [comment]
Why do we need to continue to support compatibility mode?

**Comment by kjwoodsISIS** [comment]
I don't think we need a meeting.  We just need to agree (and document) what we support.
Here a starter for 10 ...
   1. Chrome (always the latest version, never earlier versions)
   1. Firefox (always the latest version, never earlier versions)
   1. Edge (always the latest version, never earlier versions)
   1. IE11 (update version 11.0.90, not running in compatibility mode)
   1. No other browsers

Given that Chrome, Firefox and Edge are all capable of updating themselves, I see no need to support a long tail of old versions.

For those who insist on using IE11, I guess we can support it.  It is the last ever version of IE.  But I don't think we should constrain  the web dashboard by conforming to the limitations of the "Display intranet sites with compatibility view".  If people have the "Display intranet sites with compatibility view" checked, we can direct them to a page that says (words to the effect of) "choose a different browser or switch of IE7 compatibility".

If there are still intranet sites that require the use of IE11 with the "Display intranet sites with compatibility view" box checked, there is nothing to stop users switching on that checkbox in order to view those sites.  Are there any such sites?  If so, which ones?

**Comment by DominicOram** [comment]
Yes we do need to agree and document. But I don't think we can do so in this ticket without a lot of back and forth. Therefore a discussion would be better, it doesn't need to be formal. Maybe after stand up at some point? I think @ChrisM-S should also be involved.

**Comment by KathrynBaker** [comment]
It is probably worth asking the service desk for their supported browsers, as part of what we need to support is what is used by instrument scientists on their office PCs – not just what we want people to use, and sometimes that isn’t as simple as the most recent version, as they need to support multiple users with multiple roles.

**Comment by kjwoodsISIS** [comment]
I already did so:
> 27/11/2018 16:13 PM | Warner, Richard: 
> Hi Kevin,
> We generally recommend using IE11 but in no way is it or any other browser mandatory, but we don't 
> recommend using Edge. You are free to use your personal choice of browser but you might find that 
> some things work better in a particular browser than another so may need to swap browsers are 
> having two running at the same time.
> I'm not aware of any sites that require compatibility mode currently.
> Regards
> Richard

**Comment by kjwoodsISIS** [comment]
Further clarification:
> 28/11/2018 08:44 AM | Warner, Richard: 
> Hi Kevin,
> IE11 is the only fully supported browser, recommended for SBS Oracle, STFC intranet etc,  currently 
> the latest version is version 11.345.17134.0. However, you are welcome to use Firefox, current 
> version 62.0 or Chrome, current version 70.0.3538.102 although these browser are not fully 
> supported.
> Regards
> Richard
