### ISSUE TITLE
Scripting: Discuss how to fix this and scripting and console server

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3769]
As a scientist, I would like to be made aware with a warning when I accidentally start a second console in IBEX as it was not obvious that I was running two scripts at the same time overnight (which interfered with each other).

**Comment by ChrisM-S** [comment]
### Note:
1) There is no extra tab shown when a second console is accidentally (or intentionally) created so it is not  at all obvious that two consoles are in operation.
2) There is only a relatively small window of time in which a "click happy" user can create two consoles accidentally (unless they create them from the console dropdown control).
3) This ideally should be addressed by using the script server rather than the IBEX console (only one script is allowed).

**Comment by John-Holt-Tessella** [comment]
+1 SANDALS/POLARIS/INDES/GEM review consoles opening in different tabs.

**Thought**: can genie python signal to the instrument when it is alive (background thread)?

**Comment by DominicOram** [comment]
Notes from meeting are at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Scripting-use-cases

Tickets #3885 and #3886 have been created
