### ISSUE TITLE
GUI/BUG: Scripting window appearing in non-scripting views

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3773]
As a user, I don't want the scripting window to appear suddenly in a non-scripting view after switching from the scripting view to another view so that I don't generate extra windows in other views.

**Comment by Tom-Willemsen** [comment]
Issue was noticed by polaris

**Comment by kjwoodsISIS** [comment]
Attaching screenshot of issue on POLARIS (originally reported in FIT-6448)
![polaris_scripting_window _issue fit-6448](https://user-images.githubusercontent.com/7249337/53009871-604b4480-3434-11e9-9cce-d9dd95caaee7.jpg)
