### ISSUE TITLE
MARI: Discussion - fermi chopper interlock

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3775]
On MARI there is an interlock on the Fermi PLC lifting that prevents the chopper from being lifted if spinning, but once it has been lifted nothing prevents a request to start spinning. It would be useful if a request to spin could be disabled if the chopper is lifted.

Also if the vacuum is not good enough, the chopper is left running. It would be good if the IOC could stop the chopper running if it detects vacuum fails.

**Comment by davidkeymer** [comment]
Both of these conditions (lift and vacuum) are supposed to be monitored by a hardware interlock (as on MAPS and MERLIN), which is believed to be malfunctioning currently.  A meeting between members of the various groups involved will be held in the near future to discuss the matter.

**Comment by davidkeymer** [comment]
Moved to impeded column until meeting invitation received.

**Comment by davidkeymer** [comment]
Update from Rebecca:
> … I’ve not forgotten about the Fermi lift system interlock. Indeed, I’ve been asking around about how we could make this interlock a hard interlock as opposed to a software interlock. However, the problem comes back to the current suite of Fermi choppers; the interlocks are all designed as part of the system by Juelich. We have had quite a few difficulties with support from them. The quickest solution will be to get new chopper systems, as we are not getting much out of them at the moment. So I’m sorry I can’t do more at the moment, but the Fermi tender document is going to be our quickest way of getting this issue sorted.

It looks like we're stuck with the issue until the choppers and lifters are replaced.

Closing ticket.
