### ISSUE TITLE
GUI: Block values tooltip shows "disconnected"

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3778]
When hovering over the value of a block in the client's blocks panel, the tooltip says "disconnected". This is because I added the full block name to the tooltip of the block name label as part of https://github.com/ISISComputingGroup/IBEX/issues/3554 in case the name gets truncated. However this does not work for the value label and thus defaults to "disconnected", which may cause confusion.

**Comment by FreddieAkeroyd** [comment]
Looking at LARMOR if there is a description available i see value + description in the tool tip, if there is no description i see "disconnected. no description". Is this the same issue?

**Comment by John-Holt-Tessella** [comment]
Not sure but investigate and fix all these issues including:

>Descriptions are found as tool tips when hovering over blocks. Sometimes these loose their value and say "No description available". I have notice this especially when you change instrument and when changing config. I would guess it is a race conditions because only some of the blocks don't have descriptions.
> Which was #3638 that I closed.

**Comment by Alistair-McGann-Tessella** [comment]
This issue has been re-requested by a LOQ instrument scientist
