### ISSUE TITLE
SURF: IOC and OPI for Knauer K-6 Electric Valve Drive

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3781]
As a SURF scientist, I want IBEX to support the Knauer K-6 Electric Valve Drive, on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing SECI VI.
1. I can control Knauer K-6 Electric Valve Drive via the IBEX GUI
1. I can control Knauer K-6 Electric Valve Drive via genie_python

#### Notes
1. There is an existing VI for Knauer K-6 Electric Valve Drive. Please consult it when creating the IOC & OPI.
1. Documentation for the Knauer K-6 Electric Valve Drive lives here: `C:\LabVIEW Modules\Drivers\Knauer Electric Valve Drive K-6\Documentation`
1. Knauer K-6 appears to be an osolete model - need to rely on existing documentation (see above). 
1. Knauer K-6 Electric Valve Drive is often used in conjunction with multiple Knauer HPLC 1050 pumps (see #3262).

**Comment by KathrynBaker** [comment]
For information relating to complexity etc.:
* The K-6 driver has 5 functions/commands in use in the LabVIEW code
* Only the COM Port and name for display on the VI are identified in the setup
* There are 3 instances of the front panel, so this should be considered as multiple devices on the same instrument, so 3 IOCs and use common and specific st files
* The only complexity relates to the front panel display, as this is undertaken by two dials layered on top of each other, one indicating the current position the other the requested setpoint with the 6 positions layed out as if they were every other number on a clockface with 1 in the 12 o'clock position as in the image. The Blue is the current position, yellow the requested position, the requested indicator goes green once it has been sent to the device, and to blue when the two values are the same
![image](https://user-images.githubusercontent.com/10552381/51759757-d623f080-20c0-11e9-87d4-f893252d4bc4.png)

**Comment by kjwoodsISIS** [comment]
We don't have to reproduce the LabVIEW dial.  How about re-using or adapting the aperture/pinhole selector from IMAT? (ask @davidkeymer)

**Comment by KathrynBaker** [comment]
It is worth noting that there is some driver design documentation for this device in the LabVIEW which specifies the colours and behaviours better than my notes above. Those kinds of things might not be possible in an OPI. I'm not sure how similar the behaviour for IMAT is to what this is, this is a static position with an indicator as to which is active rather than rotating the numbered positions to a static position. They are different concepts and interactions, but it should provide a starting point.

**Comment by KathrynBaker** [comment]
I've also moved the documentation to our manuals folder

**Comment by aaron-long** [comment]
- IBEX GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/860
- IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/359
- SUPPORT: https://github.com/ISISComputingGroup/EPICS-knrk6/pull/1
- Device Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/21
- IoC Test Framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/162
