### ISSUE TITLE
SURF: Control multiple Knauer HPLC 1050 pumps

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3782]
As a SURF scientist, I often need to control multiple Knauer HPLC 1050 pumps (usually two) in my experiements, so I need IBEX to support multiple Knauer HPLC 1050 pumps.

#### Acceptance Criteria
1. I can control at least two Knauer HPLC 1050 pumps via the IBEX GUI
1. I can control at least two Knauer HPLC 1050 pumps via genie_python

#### Notes
1. An IOC & OPI for Knauer pumps has been created (see #3262). Check that they provide equivalent functionality to existing SECI VI.
1. The existing SECI VI and documentation for the Knauer HPLC 1050 pump lives here: C:\LabVIEW Modules\Drivers\Knauer HPLC 1050\Documentation.
1. Knauer no longer manufacture the HPLC 1050 pump - need to rely on existing documentation (see above).

**Comment by aaron-long** [comment]
See PR: https://github.com/ISISComputingGroup/EPICS-ioc/pull/336 

I have generated two IOC templates for the KNR1050.

**Comment by ThomasLohnert** [comment]
See https://github.com/ISISComputingGroup/IBEX/issues/3262
