### ISSUE TITLE
SURF: IOC and OPI for Thurlby EXP355P PSU

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3784]
As a SURF scientist, I want IBEX to support the Thurlby EXP355P PSU on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Confirm that the existing Thurlby EXP355P PSU IOC & OPI (see #155 and #198) are suitable for SURF. 
1. I can control the Thurlby EXP355P PSU via the IBEX GUI
1. I can control the Thurlby EXP355P PSU via genie_python
   * in particular, I need to control the Thurlby EXP355P PSU via my `Analog_Digital_IO` script.
   * migrate script when we do all SURF scripts.  Will need to verify it works.
1. I have not lost functionality from the old EXP335 and there is a ioc change script or it is in no-ones configs
1. When complete delete old EXP355

#### Notes
1. We already have an IOC & OPI for the Thurlby EXP355P PSU (see #155 and #198).  However, these were some of the earliest IOCs & OPIs that we created.  We need to check that they are suitable for SURF (no reason why they shouldn't be, but it is worth checking).
1. The `Analog_Digital_IO` script is an OpenGENIE script - it will need to be migrated to genie_python.

**Comment by Tom-Willemsen** [comment]
I have emailed Mario to ask for a copy of the script (I couldn't find it in any of the usual places on surf) and some details about how (if?) it uses a galil.

**Comment by davidkeymer** [comment]
A brief look in the [repository](https://github.com/ISISComputingGroup/EPICS-ttiEX355P) revealed some useful code (from DLS) that will need refactoring to comply with our current standards and conventions.  It's expected that the OPI won't be of much use, but the DB and protocol files will be.

**Comment by SophieKSTFC** [comment]
The final testing to be done with the device requires that a load can be provided. Currently waiting for an appropriate load to be found so that the emulator logic can be confirmed as correct.

**Comment by kjwoodsISIS** [comment]
@SophieKSTFC  - who is arranging a load so that we can test the IOC with the real hardware?  When do they expect to have something that we can use?

**Comment by SophieKSTFC** [comment]
@Kevin-Woods-Tessella a load has been found and now that my other tickets have been completed I can pick this work back up tomorrow. Will remove this from the impeded column.

**Comment by kjwoodsISIS** [comment]
Great!  Thanks Sophie.

Kevin

**Comment by SophieKSTFC** [comment]
There is an existing TTIEX355P support repository (see #155 and #198) as noted in the ticket. This device was created very early on and does not meet the current IBEX standards. It has no tests, device emulator or up to date OPI. The decision was made to start from scratch and develop a fresh IOC, OPI, emulator and test framework. This work has been completed in the following PRs: 

[IBEX GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/908)
[IOC Test Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/197)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/391)
[Device Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/37)
[Support](https://github.com/ISISComputingGroup/EPICS-Tti355/pull/1)

**Documentation**

- A note was added in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)
- The user manual placed in the ISIS share
- A page has been added in [Specific Device IOCs](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Thurlby-Thandar-TTiEX355P-Power-Supply-Unit)

**Testing**

- This device is readily available (in the office) to test with.

**Point 3**

> " in particular, I need to control the Thurlby EXP355P PSU via my Analog_Digital_IO script.
> migrate script when we do all SURF scripts. Will need to verify it works." 

has been moved to a [separate ticket](https://github.com/ISISComputingGroup/IBEX/issues/4463) as the Analog_Digital_IO script was not located.  However, the device can be operated through genie_python.
