### ISSUE TITLE
SURF: IOC and OPI for Watson-Marlow 323 Peristaltic Pump

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3786]
As a SURF scientist, I want IBEX to support the Watson-Marlow 323 Peristaltic Pump on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing SECI VI.
1. I can control the Watson-Marlow 323 Peristaltic Pump via the IBEX GUI
1. I can control the Watson-Marlow 323 Peristaltic Pump via genie_python

#### Notes
1. There is an existing VI for the Watson-Marlow 323 Syringe Pump. Please consult it when creating the IOC & OPI.
1. Documentation for the Watson-Marlow 323 Peristaltic Pump lives here: `C:\LabVIEW Modules\Drivers\Watson Marlow 323 Pump`
   * [Watson-Marlow 323 web-page](http://www.watson-marlow.com/gb-en/range/watson-marlow/300-tube-pumps/323d/)
1. Peristaltic pumps differ from syringe pumps, so they can't share an interface with a syringe pump.
1. SURF tends to use both Watson-Marlow 323 & WPI Aladdin-1000 Syringe Pumps (support for both is needed).

**Comment by kjwoodsISIS** [comment]
Return to Backlog (Sprint Planning 25-04-2019 decision).
/remind me re-propose 28th May

**Comment by adamb56789** [comment]
Wiki page: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Watson-Marlow-323-Peristaltic-Pump

#### Things that should ideally be investigated once we get a physical device:

- How does the 1.5-220 rpm speed control mode work? Website suggests that digital control can only do 3-400 rpm, but it is nor clear and does mention 1.5-220 rpm
- VI suggests that the speed readback is in float, disagrees with manual, what is it actually? Maybe it is an integer except when it is 1.5?
- What does the command 1ZY respond with? (Ambiguous manual, "1ZY: Show running status of the pump. STARTed 1 or STOPped 0")
- What does it mean by RS232 Echo: On? (Does it echo back commands?)
- VI does not set speed if it has not changed, is this important?
- Check that data returned from the device ends with CR (commands you send to it end with CR according to the manual)

**Comment by Tom-Willemsen** [comment]
In general this is a really good first IOC - I've put some comments on various PRs but most of them are pretty minor. Also a couple of points that didn't fit onto any particular PR:
- I think you are missing a PR on top-level EPICS (to add the submodule/makefiles/etc). The PR should look something like this: https://github.com/ISISComputingGroup/EPICS/pull/174/files
- Can you add a comment on https://github.com/ISISComputingGroup/IBEX/issues/4162 pointing back to this ticket, so that we know what we need to test when we do the SURF SE tests.

**Comment by adamb56789** [comment]
Top level EPICS PR: https://github.com/ISISComputingGroup/EPICS/pull/179
