### ISSUE TITLE
SURF: IOC and OPI for WPI Aladdin-1000 Syringe Pump

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3787]
As a SURF scientist, I want IBEX to support the WPI Aladdin-1000 Syringe Pump on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing SECI VI.
1. I can control the WPI Aladdin-1000 Syringe Pump via the IBEX GUI
1. I can control the WPI Aladdin-1000 Syringe Pump via genie_python

#### Notes
1. There is an existing VI for the WPI Aladdin-1000 Syringe Pump. Please consult it when creating the IOC & OPI.
1. Documentation for the WPI Aladdin-1000 Syringe Pump lives here: `C:\LabVIEW Modules\Drivers\WPI Aladdin-1000 Syringe Pump`
   * [WPI Aladdin web-page](https://www.wpi-europe.com/products/pumps-and-microinjection/laboratory-syringe-pumps/al1000-220.aspx)
1. There may be similarities (in terms of functionality) between the WPI Aladdin-1000 Syringe Pump and other types of syringe pump.  It may be worth consulting the following tickets: #3261, #3275, #3287.
1. SURF tends to use both Watson-Marlow 323 & WPI Aladdin-1000 Syringe Pumps (so support for both is needed).

**Comment by aaron-long** [comment]
- GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/887
- IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/383
- IoCTestFramework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/185
- DeviceEmulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/34
- Support: https://github.com/ISISComputingGroup/EPICS-Aldn1000/pull/1

**Comment by DominicOram** [comment]
Some general things:
* Can you add the manual to \\isis\shares\ISIS_Experimental_Controls\Manuals
* Can you post to https://epics.anl.gov/modules/bus.php to say we've done the device
* Do you have a real device set up that I can review this against?
