### ISSUE TITLE
TOSCA/SUPPORT: Helping Instrument scientist with scripts

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3788]
This is a support ticket for helping to create a couple of straightforward user scripts for an Instrument scientist on TOSCA. They also wanted these scripts to be simple enough to give to users to edit and use.

**Comment by Kevin-Woods-Tessella** [comment]
It is fine to help the scientists out like this in the short-term, but we need to keep an eye on activities like this.  Long-term, the Computing Controls team does not have the capacity to provide a script writing service.
