### ISSUE TITLE
SANDALS : Julabo : Presto A40

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3789]
SANDALS has a Julabo experiment starting on 19th November. This will be using a Julabo Presto A40 - which I believe will require a protocol file modification.

**Comment by Tom-Willemsen** [comment]
When this experiment is over, go to SANDALS and rename in `C:\instrument\apps\epics\support\julabo\master\julaboapp\protocol`:
- `julaboVariable.proto` -> `JulaboVariable_A40.proto`
- `julaboVariable_normal.proto` -> `JulaboVariable.proto`

I have listed this as a pending task.

In future, this type of ticket will be handled as part of the configurations - see https://github.com/ISISComputingGroup/IBEX/issues/3621

**Comment by Tom-Willemsen** [comment]
@GDH-ISIS has now done the revert noted above. I don't think there is anything to review as part of this ticket. Moving straight to review complete.

**Comment by GDH-ISIS** [comment]
On talking to the instrument scientist, they would like to swop back to the Julabo Presto A40 again this cycle.
