### ISSUE TITLE
IOC: Add a crashed IOC test case to simple IOC

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3795]
As a developer I need to know if the restarted behaviour of the procserv is correct when an IOC crashes. This should be done by adding a subroutine which will guarantee a crash (e.g. segfault) as soon as it boots.

A system test should be written which tests whether the IOC restarts in the case of a crashed IOC, or does not restart if the IOC is not set to auto restart in the configuration.

**Comment by FreddieAkeroyd** [comment]
There is also the case of a "do you want to debug" dialogue that may stop a restart.

**Comment by Alistair-McGann-Tessella** [comment]
Pull request:
https://github.com/ISISComputingGroup/EPICS-SimpleIoc/pull/6

The automated system test was becoming too much work for this small ticket. A manual test has been added to the manual system tests:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/testing/manual_system_tests_template.xlsx

The work performed on allowing arbitrary code to be launched via the IOC test framework is parked on this branch:
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket3795_crashed_IOC

**Comment by John-Holt-Tessella** [comment]
Ended up merging the branch because we wanted to use the code for something else. So start from master
