### ISSUE TITLE
IOC: Eurotherm disaply error when out of calibration range

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3803]
As an instrument scientist if my Eurotherm is using a calibration reading outside of my calibration curve I should get an error/message indicating this is the case. I must be allowed to continue taking readings though.

**Comment by Rory-Potter-Tessella** [comment]
+1 VESUVIO from Instrument Demo (2018-11-22)

**Comment by Rory-Potter-Tessella** [comment]
Is this a duplicate of #3770?

**Comment by John-Holt-Tessella** [comment]
duplicate of #3770

**Comment by kjwoodsISIS** [comment]
If this is fixed, it should be closed.
