### ISSUE TITLE
IOC Test Framework: Command Builder improvements

### ISSUE THREAD

**Issue by LiamPanchaud** [ISISComputingGroup/IBEX#3805]
As a developer, I want command builder to have the option to ignore variables in commands, 

For example, in the command `CmdBuilder("set_example").escape("SCPI:CMND ").int().eos().build()`

The corresponding `set_example` function must include the `int` in its list of parameters. On more complex commands, if there is an input I don't care about I don't want it to bloat the function's parameters.

To do that currently, a `.regex()` is needed. e.g `CmdBuilder("set_example").escape("SCPI:CMND ").regex("[+-]?\d+").eos().build()`

What would be better is a setting in the parameters of `.int()` (and the other options) which allows me to ignore the input. 

e.g `CmdBuilder("set_example").escape("SCPI:CMND ").int(ignore=true).eos().build()`

* Add an ignore flag (or similar implemetation) to `.string()`, `.int()`, `.float()`, and the other input parsing functions

**Comment by LiamPanchaud** [comment]
It looks like there already is something like this in the `_add_to_regex` function, but the ability to toggle the flag is not exposed. At least, there is something similar which can probably be expanded/refactored to provide the desired functionality

**Comment by John-Holt-Tessella** [comment]
Don't feel constrained by the framework. If you need the functionality just add it in if it makes sense at the time when you are using it; although make it backwards compatible. Unless this is done as a Friday ticket it will never get high enough priority to get done.
