### ISSUE TITLE
GUI: High level OPI for RIKEN

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3810]
As a Riken instrument scientist I would like a hightlevel OPI so that I can see the status and control my instrument easily.

Aceptance Criteria:

1. Talk with Aidy about requirements and make a paper prototype which is agreed
1. Create the OPI

**Comment by John-Holt-Tessella** [comment]
May require #3271 waiting for email reply

**Comment by davidkeymer** [comment]
Superseded by #5876 #5878 #5873 #5872
