### ISSUE TITLE
IOC/GUI: Requirements for contact/notify an instrument scientist (e.g. SMS) if something is wrong, e.g. alarm, out of run control, vetoing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3811]
As a MERLIN/HRPD/ENGIN-X/INES instrument scientist I would like to define conditions under which IBEX should contact me so that if there is an error in my experiment I don't waste beam time while I am not at work.

This could be an SMS or slack message. This should potentially be on run control or alarms (see #2738).

Acceptance Criteria:

1. A number of scientists have been contacted
1. A general specification has been created
1. Ticket to implement specification have been done.

**Comment by FreddieAkeroyd** [comment]
LOQ and SANS2D currently get an SMS alert when their fast shutter overcount is triggered

**Comment by FreddieAkeroyd** [comment]
LOQ also uses this feature in SECI on other blocks, so we should look to implement ASAP

**Comment by ThomasLohnert** [comment]
is this ticket obsolete? we have https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Alerts-on-Blocks

**Comment by John-Holt-Tessella** [comment]
Yes good call #5493 is the gui tickets and the other bit is in already
