### ISSUE TITLE
GUI: Add Help links from all pages

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3814]
As an instrument scientist I would like a helplink on the screen to link into the user manual so I can easily find help.

Acceptance Criteria:

1. A help link should be added to views and significant components - done
1. A test should be created which finds all references and checks that they are real pages in the wiki.

**Comment by KathrynBaker** [comment]
This is done at a suitable level and improved on at least once since, closing
