### ISSUE TITLE
Polaris: rotation stage

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3820]
As an instrument scientist on Polaris, I need to be able to control a rotation stage for an experiment starting this Friday (30/11/2018). This is the same McLennan rotation stage that was recently used on HRPD.

See https://github.com/ISISComputingGroup/IBEX/issues/3664 for corresponding ticket from when we did HRPD.

**Comment by Tom-Willemsen** [comment]
Ron would like this set up "at about 9:30" tomorrow.

- Connect to moxa
- Copy over inst. script from hrpd onto polaris
- Apply motor settings from the linked hrpd ticket
- Check it moves sensibly

**Comment by Tom-Willemsen** [comment]
Configured on POLARIS. Instrument scientists told about `zero_after_home` script. Checked it moved sensibly.

**Comment by Tom-Willemsen** [comment]
They had an issue with this where the McLennan no longer moved after a few hours of (non-continuous) use - neither from software nor from jog on front of crate. No error status on front of crate (it claimed "moving" but never moved anywhere). 3rd Power cycle brought it back and software reconnected happily.

**Comment by ChrisM-S** [comment]
Just wondered, were bytes still going back and forth from the controller - i.e. did/would a "QA" have worked from hyper term - or does it look more like a hardware problem within the crate?

**Comment by Tom-Willemsen** [comment]
Yes, communication was still ok with the crate. The problem was somewhere between the mclennan crate and the motor.

**Comment by davidkeymer** [comment]
Reviewed by confirming that the macro values used on HRPD mentioned above match those applied to POLARIS (except COM port, name, etc).
