### ISSUE TITLE
IBEX: Training (22nd January 2019)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3823]
The next training courses are scheduled for the 22nd January 2019.

#### Acceptance Criteria
- [ ] Advertise training
- [X] Book venue
   - [X] CDF room in Atlas Centre has been booked
- [ ] Assign trainers
- [ ] Review course materials
- [ ] Send delegate list to CDF
- [ ] Send joining instructions to delegates
- [ ] Book tea & coffee (but not lunch) as necessary
- [ ] Set up machines
- [ ] Deliver training
- [ ] Apply retrospective changes to process/wiki/slides

#### Notes
1. Additional instructions for setting up training can be found here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
1. The courses are scheduled as follows:
   - 22nd January 2019 (AM): Introduction to IBEX
   - 22nd January 2019 (PM): genie_python with IBEX
These are two separate courses.  Delegates will be expected to purchase their own lunch.

**Comment by kjwoodsISIS** [comment]
consider doing parts of https://github.com/ISISComputingGroup/IBEX/issues/3792 at the same time

**Comment by Tom-Willemsen** [comment]
I presume this ticket no longer needs to be in "ready"?

**Comment by John-Holt-Tessella** [comment]
Not doing this!

**Comment by kjwoodsISIS** [comment]
Training was cancelled because only one scientist accepted the invitation to attend (others declined or did not reply).  For the scientist who did reply, we are not migrating his instrument for Cycle 2018/04, so there is no loss - he can attend a future training session.
