### ISSUE TITLE
genie_python: implement way to get fields from block

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3824]
As a user, I may be interested in the fields of my block. For example if I have a block on a motor I may be interested in it's limits, velocity, deadbands.

A possible implementation would be to add a `get_pv_from_block(blockname)` function to genie python, to allow scripts to get arbitrary fields without hard-coding PV names.

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/148
