### ISSUE TITLE
OSIRIS: Install and test modified Mercury OPI

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3827]
Install and test the above OPI and associated script on OSIRIS ready for the cryogenic experiment starting on 13th December.
See the original ticket for more details:

Requires #3776

**Comment by Tom-Willemsen** [comment]
Installed on OSIRIS. Shown to Franz, he was happy that it contained the controls he needed. OSIRIS is now running with ibex using this modified OPI.

**Comment by Rory-Potter-Tessella** [comment]
The OPI and script are on OSIRIS. However, OSIRIS did stop using IBEX around midday. Worth checking in with Franz why this was the case.
