### ISSUE TITLE
IOC: Non-communication not resulting in errors

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3829]
As a RIKEN instrument scientist I want my Danfsyk to show an error alarm on the current and voltage pvs when there is no commiunication. so that I can tell if there is an error in my pv.
This is urgent because I would like Muon scitenists to see we are responding to their problems.

Acceptance criteria:

1. A non-communicating Danfysk produces an alarm on the voltage and current pvs
1. There is a test in the IOC framework for this.

Idea: How hard is it to generalise this test to test all IOCs in non communication mode for interesting PVs?

**Comment by aaron-long** [comment]
Danfsik
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/342
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/146
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/13


Riken
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/147
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/14
- https://github.com/ISISComputingGroup/EPICS-ioc/commit/7186bec8c4225c82f418052d55c590fcbd50b612 - See commit to master :'(
