### ISSUE TITLE
Imat: truncate DB

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3831]
IMAT's DB is 8 GB truncate it on maintenance day https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space

Using the script in `utils\archive_rates.py`, nothing is logging at more than 1Hz currently.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by davidkeymer** [comment]
Reviewed by checking current database size:

The volume of data in `\\ndximat\c$\Instrument\Var\mysql\data` is ~2.2GB as at 10/12/18.  The database has therefore been truncated successfully.
