### ISSUE TITLE
ENGINX: create ENGINX_SETUP machine

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3835]
As an instrument scientist on ENGIN-X, I would like a setup machine so that I can run my second stress rig and it's associated scripts offline while the main instrument is in use.

- [x] Create ENGINX_SETUP (similar to IRIS_SETUP)
- [x] Install IBEX on it
- [x] Check it can control second stress rig

Scientist would like it by the 12th/13th

**Comment by Kevin-Woods-Tessella** [comment]
Is there a machine available for this?

**Comment by Tom-Willemsen** [comment]
I have spoken to @ChrisM-S about this, apparently we may be able to re-use the wish_setup machine which isn't currently in use.

**Comment by KathrynBaker** [comment]
Don’t forget to watch out for the settings etc. for the GPIB-ENET in relation to this as well. That will need setting up as well as the machine to use the stress rig.

**Comment by Tom-Willemsen** [comment]
Setup machine is set up controlling the stress rig and the furnace (eurotherm). 
- Mapped counting house MOXA from setup machine to connect to eurotherm.
- Ni-GPIB 2.7 installed to talk to stress rig and added as a device in NI-MAX. Note that the latest versions of the NI GPIB drivers **do not** work with the stress rig (I have noted this on the wiki)

Showed machine to instrument scientist and they are happy that they can control what they need to control. Made sure that they know that they can't talk to the same device from multiple computers. Told them to simply run `stop_ibex_server` on the setup machine when they are finished with it.

**Comment by Rory-Potter-Tessella** [comment]
The machine is up and running and in use. The stress rig is being used on it.
