### ISSUE TITLE
Moxa e1210: Stop logging asyn comms information

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3845]
As a user/developer I don't want log files to contain all communications with the moxa e1210. Asyn trace masks are currently set in the st-common file which need to be removed.

**Comment by Alistair-McGann-Tessella** [comment]
Pull request: https://github.com/ISISComputingGroup/EPICS-ioc/pull/337

**Comment by kjwoodsISIS** [comment]
Was this really 0 points?

**Comment by John-Holt-Tessella** [comment]
yes it is removal of 6 lines
