### ISSUE TITLE
RKNPS: RQ22 polarity change not noticed until new setpoint is sent

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3849]
As a user of RIKEN, if I (manually) change the polarity of RQ22, I want IBEX to reflect this.

James and Aidy report that they had to send a new setpoint before the polarity readback updated. Investigate whether this is a hardware or software issue.

**Comment by KathrynBaker** [comment]
Given the updates to the whole system on RIKEN, this has been superseded
