### ISSUE TITLE
DAQMXBASE: Read disconnected errors

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3850]
As a Muon Instrument scientist, I want the voltage and current PVs to show when the IOC is disconnected from the DAQ.

The IOC became disconnected from the  DAQ and started creating lots of error messages

```
Ensure the device is properly connected and turned on. Ensure the device and/or chassis is supported in the current version of the driver. Check the device's status in NI MAX. Turn the computer off and on again. If you suspect that the device is damaged, contact Na
2018/12/05 11:42:25.805 ### DAQmx ERROR (CreateAI): Device cannot be accessed.  Possible causes:

Device is no longer present in the system.
Device is not powered.
Device is powered, but was temporarily without power.
Device and/or chassis driver support may have been removed.
Device is damaged.
``` 

However, the disconnected status was not shown on the PVs for voltage and current. This may be because the device uses I/O Interrupt to get data off the DAQ and so waits for data to be sent to it rather than fetching it. Thus if no data is sent from the DAQ to the IOC, it doesn't go into error as it didn't ask for any.

This will be a generic problem for any device using a cDAQ through DAQmx/DAQmxbase.

**Comment by kjwoodsISIS** [comment]
If this is a generic problem for such devices, then I think we need to capture this in developer guidance, so that we can avoid the same problem in future.

**Comment by KathrynBaker** [comment]
We need to watch the differences here – the devices are getting pickier and pickier the more of them there are on the network (best guess, as the ones on the dodgier network on the RIKEN side are more prone to failure than on the South Side on the whole), so there can be the disconnection to the device, but there is also the nature of I/O intr, which is available across many devices which does not propagate the data.

The content of the ticket implies the fault to fix is the latter, but we should be careful to make sure we only fix one of this issues in this ticket, and a separate ticket needs to cover the other fault scenario.

**Comment by Rory-Potter-Tessella** [comment]
The error that is shown on the original ticket is from a local separator IOC I was still running not from MUONFE's as I got in a mess with consoling into a remote IOC. The actual log is 

```
[2018-12-05 09:14:01] 2018/12/05 09:14:01.154 ### DAQmx ERROR (ReadAnalogF64): Some or all of the samples requested have not yet been acquired.

[2018-12-05 09:14:01] 

[2018-12-05 09:14:01] To wait for the samples to become available use a longer read timeout or read later in your program. To make the samples available sooner, increase the sample rate. If your task uses a start trigger,  make sure that your start trigger is configured correctly. It is also possible that you configured the task for external timing, and no clock was supplied. If this is the case, supply an external clock.

[2018-12-05 09:14:01] Property: DAQmx_Read_RelativeTo

[2018-12-05 09:14:01] Correspon
```

**Comment by Tom-Willemsen** [comment]
Brought up as a support issue by James - no-one noticed that the separator wasn't reading correctly after a network outage as there were no comms alarms on the PVs. Re-proposing this ticket.

**Comment by FreddieAkeroyd** [comment]
If a createAI error occurs, the STATE PV (and internal daqmx state) becomes "unconfigured". If ReadAnalogF64 fails it looks to go to a "stop" state. I think an alarm could be raised at the point of error, iguess it is possible to test this in the office?

**Comment by kjwoodsISIS** [comment]
Return to Backlog (Sprint Planning 25-04-2019 decision).
/remind me re-propose 28th May

**Comment by Alistair-McGann-Tessella** [comment]
I have started work on this ticket as this is also affects the Muon Zero Field magnetometer readback, part of the MVP for EMU.

**Comment by Alistair-McGann-Tessella** [comment]
PR for zero field mangetometer IOC:
https://github.com/ISISComputingGroup/EPICS-DAQmxBase/pull/5

**Comment by kjwoodsISIS** [comment]
How many points is this?

**Comment by Alistair-McGann-Tessella** [comment]
Updated separator to forward alarms properly: ISISComputingGroup/EPICS-SEPRTR#6
