### ISSUE TITLE
SXD: Attocube Controller

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3854]
As an SXD instrument scientist I would like to be able to control the Attocube CCR controller that will be attached to the new goniometer being delivered in Summer 2019. Contact Matt North for a controller to test with.

**Comment by DominicOram** [comment]
Controller is in the office. I didn't get the stage as it's very delicate but we should be able to go and get it when we're ready to test.

**Comment by DominicOram** [comment]
Stage will be mounted in a couple of weeks so have until then to test with it. Motion commissioning will be the end of July.

**Comment by kjwoodsISIS** [comment]
How many points is this?  or should it be time-boxed?

**Comment by DominicOram** [comment]
Pointed based on the fact that it looks like a driver already exists. May have to revisit if this driver is a non-starter.

**Comment by DominicOram** [comment]
Device has all the hardware for Ethernet comms but can only communicate over USB currently. I believe the ethernet requires unlocking in the firmware. Have asked electronics for advice.

**Comment by kjwoodsISIS** [comment]
I've just noticed that the SXD directory in `C:\LabVIEW Modules\Instruments\SXD\AttoCube` has an AttoCube VI.  Is it able to control the  AttoCube CCR device?

**Comment by DominicOram** [comment]
No, Kathryn and I had a look over it before I started this ticket. It appears to be a galil controlling an Attocube stage. This is an Attocube controller. Either way, given that this is going to be on SXD around the same time we move it to IBEX now seems like a good opportunity to get EPICS support working.

**Comment by DominicOram** [comment]
Unfortunately the stage itself is now undergoing vac testing etc. I've got as far as I can with this with only having a controller to talk to and not a valid stage. Documentation is at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Attocube. The emulator works for testing basic movements and is based on a bit of guesswork of how the controller would behave if it had an axis, I couldn't take it much further without making more assumptions. Further work needs to be done to commission the axis (https://github.com/ISISComputingGroup/IBEX/issues/4488), the emulator can be improved as this is undertaken.

**Comment by DominicOram** [comment]
Controller has now left the office to be wired up. Might be able to get it again in a couple of weeks. Hopefully the review can still be done without it.

**Comment by Tom-Willemsen** [comment]
I have reviewed as much as I can without testing against the hardware - as Dom points out, there will be further comissioning required before we can call support for this device "done".
