### ISSUE TITLE
Memory usage: Procserv: dynamically start procserv processes as they are needed

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3858]
As a developer and maintainer, I want to make sure that the IBEX system is not using too much memory.

As discussed in a meeting, this ticket is to dynamically launch procserv processes as they are needed rather than statically. This will save us a significant amount of memory.

**Comment by FreddieAkeroyd** [comment]
Note that conserver creates a console for each procServ, so we need to check whether we can still crate a conserver console in a "down" state prior to the procserv being there; otherwise we  will need to reconfigure conserver at the same time

**Comment by ChrisM-S** [comment]
Just a minor point - a slight aside to this, but does the terminal (conhost.exe) have to be made visible for conserver to work? I can remember a switch to turn off/hide visible console display from the Genie days but it may not be relevant. Not having random console screens appearing and then disappearing for up to a minute on startup/restart would be a really nice benefit if it could be switched off.  Alternatively, I guess they could just be started iconized so they wouldn't grab focus?

**Comment by kjwoodsISIS** [comment]
If short on time consider just doing #1953 instead.

**Comment by KathrynBaker** [comment]
Would this help with the DAEIII port issues as well potentially?
With a (very) rough check based on the number of lines output by `netstat -a` without Ibex < 500 lines, with IBEX > 3000. This is a very rough check, and the proportion of 6:1 with:without IBEX running is probably more useful as a metric than the absolute values.

**Comment by FreddieAkeroyd** [comment]
The DAE3 port issue is that the vendor software uses a port in the dynamic range that is not guaranteed to be given to another process, it uses one at the end of this range so if isisicp is started and connects to dae soon after a system boot all is OK. Problem occurs if this is done after a long while, or if the instrument is put in dae simulation mode for a while. Reducing the number of ports ibex uses will not stop this happening, but might make it take a bit longer to occur.

**Comment by KathrynBaker** [comment]
Discussion on 20/10/2022 between FA, TW, DK, KB, LC, JH

This would be best resolved by creating a python server which undertakes the same function as the procserv functionality, this would give us better control, make it easier to support any cut down instruments. Make sure that the logic and communication protocol are encapsulated/abstracted enough to not be a hassle to change, and initially use pcaspy.

There also needs to be a look at how mini-insts/cut down systems are run, as this may be a solution there.

**Comment by KathrynBaker** [comment]
Two tickets have been created, #7450 and #7451 to undertake the items discussed above. This ticket is being closed as it is superseded by more detailed and definite actions.

**Comment by FreddieAkeroyd** [comment]
Now covered by #8558
