### ISSUE TITLE
Memory usage: increase instrument machine memory to 14GB

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3860]
As a developer and system maintainer, I do not want processes to be unnecessarily starved of memory.

As discussed in the memory usage meeting, increase the RAM on instrument NDX machines to 14GB.

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - document the process, so that anyone can do this.

**Comment by ChrisM-S** [comment]
Example now documented in controls ticket https://github.com/ISISComputingGroup/ControlsWork/issues/613.

**Comment by Tom-Willemsen** [comment]
PR which adds a prompt with these instructions to the upgrade script: https://github.com/ISISComputingGroup/ibex_utils/pull/36
