### ISSUE TITLE
Memory usage: increase setup machine memory to 8GB

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3861]
As a developer and system maintainer, I do not want processes to be unnecessarily starved of memory.

As discussed in the memory usage meeting, increase the RAM on instrument setup NDX machines to 8GB or more.

**Comment by kjwoodsISIS** [comment]
Needs a bit of investigation (r.e. physical memory) first. Create a different ticket to investigate before this one can be done.

**Comment by Tom-Willemsen** [comment]
Anyone can pick up this ticket, but talk to @ChrisM-S as you pick it up to clarify exactly what needs to be done.

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella why has this been moved to impeeded?

**Comment by Kevin-Woods-Tessella** [comment]
@John-Holt-Tessella I don't know why it was move to impeded - it wasn't intentional.

**Comment by KathrynBaker** [comment]
Most systems now have a minimum of 10Gb, but aiming to use 14Gb - closing.
