### ISSUE TITLE
Memory usage: add test to check overall memory usage does not exceed limits

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3862]
As a developer and system maintainer, I want to make sure that we will not run into any problems with instruments using more memory than they should be

This ticket is to create a system test which loads up a "typical" system configuration (e.g. 20 IOCS, 20 blocks, 1 LvDCOM IOC, doing a simulated run with "typical" wiring/spectra/detector tables) and measures the system memory usage. The test should fail if the total system memory usage exceeds 8GB when not running / 10GB while running. 

This will give us early warning if IBEX is nearing the limits of system memory.

**Comment by Alistair-McGann-Tessella** [comment]
Pull request:

[System tests](https://github.com/ISISComputingGroup/system_tests/pull/10)
