### ISSUE TITLE
NURF: Copy Knaur and DH2000 to Larmor

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3872]
Make Knaur and DH200 work on Larmor:

1. [X] Copy ioc and support dirs to instrument
1. [x] run build_ioc_startups.py
1. [x] restart server

Make sure it works.

**Comment by Tom-Willemsen** [comment]
The DH2000 wasn't copied to LARMOR. I have now done it.
