### ISSUE TITLE
MOXA : Sample environment connection details

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3874]
As a user, instrument scientist and developer, I would like to know the details of where to connect my sample environment device to an existing MOXA. This would help users to locate where to connect the device in question, thereby reducing support calls. A dynamic list of all devices used historically would also help users keep track of the beam lines.

**Acceptance criteria :**
1. The IP address and network name of the MOXA should be displayed.
2. The port that the device should be connected to should be available.
3. A full list of which devices and ports used should be maintained live on the instrument as a point of reference.

**Notes :**
A question should be raised as to whether this should be broadened to include all device address information e.g. IP address of network equipment or device address e.g. Eurotherm
This should include whether the MOXA is referred to by mapped COM ports (NPort) or via IP Serial.

**Comment by GDH-ISIS** [comment]
The registry entries for the MOXA NPort details can be found in the vi : 
C:\LabVIEW Modules\Drivers\MOXA\MOXA - System Functions.llb\MOXA - Front Panel.vi

**Comment by John-Holt-Tessella** [comment]
It should be possible to pull the IOC name and description and COM port from the combination of all configurations on an instrument.

**Comment by FreddieAkeroyd** [comment]
There are also details available by SNMP that we could show on communication status. Mapping used com port -> pid -> process name would also be useful e.g. it would pick also pick up a terminal session that would not be mentioned in a configuration for example

**Comment by rerpha** [comment]
duplicated by #7720  - we are going to use the registry though.
