### ISSUE TITLE
Muons : ICE Dilution Fridge

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#3876]
As a user and instrument scientists I would like to control a dilution fridge from a company called ICE.

Notes
1. This is a dilution fridge from a different manufacturer and can not be compared to Triton.
2. The ICE control PC is referred to as an ICECube and is Windows XP and should not go onto the ISIS network. Communication with the equipment is via serial and a MOXA unit.
3. The dilution fridge temperature at low temperatures is controlled via a Lakeshore 370.
4. There is only one ICE dilution fridge which is used on MUSR mainly. It is avaiable for EMU and I believe there is an expectation that it will be an option for the RIKEN beam lines also.

**Comment by GDH-ISIS** [comment]
Note : There is an option to control the system at low temperature as there is a remote option to control the Lakeshore 370 directly. This can be found in the documentation command set and the two commands are LS-DIRECT-SET and LS-DIRECT-READ. These two commands will pass any command that you wish on to the Lakeshore 370 directly - as though you were talking to the device itself. This may prove helpful.

I believe there is an EPICS driver for the Lakeshore 370 already and is referenced at : https://epics.anl.gov/modules/manufacturer.php#Lakeshore

**Comment by GDH-ISIS** [comment]
The cryostat temperature control is via a CRYOCON 24C. There is a remote direct command also for this namely CRYO-DIRECT-SET and CRYO-DIRECT-READ. (Looks like there is a type in the documentation). Not sure if and EPICS driver exists for this.

**Comment by GDH-ISIS** [comment]
The ICE dilution fridge could potentially be treated as a temperature controller (similar to the Triton systems). I think this should be agreed with the instrument scientists as acceptable though.

**Comment by Tom-Willemsen** [comment]
Note from EMU migration meeting: it is critical to reproduce the diagram seen on the front panel of the VI on the OPI, as the information does not make sense to the scientists without the diagram for context.

**Comment by Alexandru-Dascalu** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/194

https://github.com/ISISComputingGroup/EPICS-ioc/pull/445

https://github.com/ISISComputingGroup/EPICS-icefrdge/pull/1

https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/59


https://github.com/ISISComputingGroup/ibex_gui/pull/1002

**Comment by Alexandru-Dascalu** [comment]
Documentation for the IOC is found at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ICE-Dilution-Fridge .

I also added some documentation about the different ways to process calc records here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Tips-and-Tricks . It is in the last section of the page.

A list of things we need to clarify when we test the IOC against the real hardware in January as part of  #4926 is found here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/To-do-list-for-ICE-dilution-fridge-IOC-for-testing-on-actual-device .
