### ISSUE TITLE
Investigate gui SWT segmentation fault causing JVM hard crash [TIMEBOX: 3d]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3877]
Noticed a log on OSIRIS of a "hard" Java VM crash caused by a segmentation fault in an SWT DLL. Note, this is not a "normal" java exception, but a full JVM crash. It may be that this problem has been reported and fixed in a newer version of SWT.

I have copied the log files of interest to: `\\isis\shares\ISIS_Experimental_Controls\Ticket3877`

From logs, crash happened at 18:19 on 27/11/2018. This was not (as far as I know) reported by the scientist.

**Comment by Tom-Willemsen** [comment]
Polaris complained about a client crash at "about 11:00 on Saturday [9/3/2019]" when I went down to set up the furnace. This coincides with the log of a JVM hard crash (as described above). They were apparently changing perspectives at the time.

**Comment by KathrynBaker** [comment]
Seen again on MERLIN at 11:49 on the 18th of March, again it corresponds to a perspective change, the thought here was that it was a request to change to the scripting perspective, but it may also be that there was a couple of quick changes in relation to each other as this may have been a misselect as well.

**Comment by Tom-Willemsen** [comment]
Was unable to reproduce within 3 day timebox. Here is what I found:

- The crash seems to be a segmentation fault in a windows DLL called `USP10.DLL` which deals with writing text to screen.
- I believe the original update which caused the crash came via databinding (but because of the nature of databinding, it's impossible to see exactly which item it came from.
  * This is because there are entries like `org.eclipse.core.databinding.observable.Realm.runWithDefault` in the java stack at the time of the crash.
- The crash seems to have started sometime between November-Janurary. In the Feb-Mar cycle we had multiple crashes on several beamlines. In the Sept-Nov 2018 period, we had none.
  * This is true even for instruments which have not had an IBEX update since september 2018, which leads me to believe something else may have changed. 
- Based on the above two findings, I did several tests across my machine and DEMO:
  * Changing title and users very rapidly including strange unicode characters
  * Set up hundreds of blocks all pointing at the same, rapidly updating, PV (to check whether it was a concurrency issue)
  * Use Squish to repeatedly change perspectives while the above was happening (one scientist reported that the crash occured during perspective change).
  * These tests were all run with ~10 clients open on DEMO and ~20 on my machine to try to amplify the chances of hitting a "random" condition.
  * Unfortunately I was totally unable to reproduce this fault using the above methods.
  * I did run into some bugs that cause memory leaks ( https://github.com/ISISComputingGroup/IBEX/issues/4239 and https://github.com/ISISComputingGroup/IBEX/issues/4146 ), so I let the client run into these problems, but this still did not reproduce the segmentation fault (it merely caused the clients to go very slowly).



For reference, here are the instruments which saw the crash. As far as I can see there is no correlation between the crash happening and the GUI version. If someone else spots a correlation here please shout.

| Instrument | GUI version | Dates of crashes |
| --- | --- | --- |
| ALF | 5.0.1 | None |
| ENGINX | 5.0.1 | None |
| ENGINX_SETUP | 5.1.0 | None |
| EMMA-A | 5.0.1 | None |
| GEM | 5.0.1 | 30/11/2018, 18/2/2019, 7/3/2019, 28/3/2019 |
| HRPD | | |
| IMAT | 5.0.1 | 15/3/2019 |
| INES | 5.1.0 | None |
| IRIS | 5.2.1 | 22/2/2019, 8/3/2019, 18/3/2019 |
| IRIS_SETUP | 5.0.1 | 7/1/2019 |
| LARMOR | 5.2.2 | None |
| LET | 5.2.2 | None |
| LOQ | 5.2.1 | None |
| MAPS | 5.2.1 | None |
| MARI | 5.2.1 | 12/2/2019, 5/3/2019 |
| MERLIN | 5.2.1 | 18/3/2019 |
| MUONFE | | |
| OSIRIS | 5.1.0 | 27/11/2018, 18/3/2019 |
| POLARIS | 5.2.1 | 15/2/2019, 2/3/2019, 9/3/2019, 26/3/2019 |
| RIKENFE | | |
| SANDALS | 5.2.1 | None |
| SELAB | 5.0.1 | None |
| TOSCA | 5.1.0 | 14/2/2019 |
| VESUVIO | | |
| ZOOM | 5.2.2 | None |



What I've ended up doing as part of this ticket:
- Add an extra debugging flag to the GUI which tells the JVM to generate crash dumps. PR: https://github.com/ISISComputingGroup/ibex_gui/pull/877
- Add a new ticket to monitor for re-occurences of this bug: https://github.com/ISISComputingGroup/IBEX/issues/4246

**Comment by aaron-long** [comment]
Around the time this issue started to happen, there were issues investigated on the `inst_servers` (Issue)[https://github.com/ISISComputingGroup/IBEX/issues/3240] that were caused by invalid Unicode. However, I don't believe any changes made as a result of these were put in until the April release.
