### ISSUE TITLE
MUONFE: Implement filtering in separator IOC

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3880]
As a MuonFE instrument scientist, I want an accurate voltage and current signal outputted from the Separator IOC so that I can monitor the Separator PSU more accurately.

- This ticket is to implement the filtering decided on in #3612. 
- This ticket requires #3612.

#### Possible solution

-  Create an aSub record which takes in the calibrated data and performs the filtering decided on in #3612, outputs the filtered array as a waveform.
    - The voltage and current readings will be the first element of this filtered packet of data.

#### Acceptance Criteria

- The aSub record has been sufficiently unit tested using [googleTest](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Setting-up-googleTest-to-work-with-EPICS-build-process).
- The current suite of IOC tests still pass.
- I can see filtered data displayed on the Separator IOC graph.

**Comment by John-Holt-Tessella** [comment]
Kevin would like this to be deployed for the end of this cycle if possible I have bumped it up the list,

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:
[IOC](https://github.com/ISISComputingGroup/EPICS-SEPRTR/pull/4)
[IOC Test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/166)
