### ISSUE TITLE
Discussion: NDX Page Files - ensure consistency 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3882]
The page files are currently various sizes on the NDX computers, 800MB on NDXLET, many are 2 or 4 GB but some are 8GB and 14GB. Though paging is not desirable from a performance viewpoint, it is better than the O/S having to start e.g. killing idle processes. As we have agreed a standard for NDX physical memory, should we also agree on a standard for virtual memory?

**Comment by John-Holt-Tessella** [comment]
Couple of questions:

1. What are we using the oage file for
1. Does it depend on the machines size
1. Is the page file on the same VHD as the OS or var?

**Comment by ChrisM-S** [comment]
All control systems VMs/Hosts are sized to provide **ample** physical memory for instrument control (i.e. needed x 2).  The page files are provided in separate partitions on all VMs to allow growth of virtual memory smoothly up to a  "run out of ~8GB" to cope with an unexpected problem which devour memory without risking loss of data or control - for at least a while.  The page files on many NDX systems are grown by the system as necessary - this growth often triggers useful Nagios messages which can be viewed as saying the system is no longer running optimally (the size reported in the message is important here as it gives an indication of time to eventual failure!).

Most of the physical memory space and CPU resources on the control machines is dedicated to allowing in memory processing of event mode neutron spectra into histograms/live views and creating Nexus files in real-time by the ICP (by real-time I mean before the next but one run is started - so we don't accumulate unprocessed data which the scientists might need for making decisions). the 14GB we have on WISH is probably the largest detector array we deal with hence the maximum space we need.

The size of the pagefile(s) for us is NOT dependent on physical memory (although this is usually the case with default installations of Windows where the pagefile size often mirrors the memory size).  I think the standard size for the pagefile if we did chose one would have to be related to rate at which a problem might occur.  A bit like having a 10GB critical limit for remaining disk space, it is arbitrary.

does this answer most of the questions? not sure if we need to keep this ticket unless the 8GB default level needs reviewing?

**Comment by John-Holt-Tessella** [comment]
It does answers the questions. 

Last question when we create our VHD solution will the page size be the same for all machines? I think you have said yes. If so how big, if it is arbitary.

**Comment by ChrisM-S** [comment]
Yes, as the things that might go wrong are usually of the same scale across machines they would be the same size (i.e. leaks are not normally faster on bigger memory machines - MUSR excepted!).

This has to be balanced against permanently taking away space for new raw data to be stored (which may be the only copy if there are archive server/network problems centrally and there is no where to move new data to).  I would probably stick to 8GB as there is little sign to date that we would currently have gained anything in time if we had not already seen a problem in monitoring!  When we refresh the older servers (2020) and get a larger minimum system disk across the servers we can rejig the limits.

**Comment by John-Holt-Tessella** [comment]
So is this ticket to write down the specification of a machine and the reasons behind it then. I can do that and close the ticket if that is everything.

**Comment by ChrisM-S** [comment]
Essentially yes.  I think the strategy is largely sitting in my head so it would be good to spend some time extracting it.  Particularly worth writing down are things that are not intuitive (e.g. we always buy control servers at a price point - nothing really do to with functionality!).
I'm happy to spend some time "pair documenting" doing some Q & A and following things to points in the strategy - we can always discuss once it's written down and fill in details or at least leave questions to be answered later.

**Comment by KathrynBaker** [comment]
This is certainly a setup that is different with regards to page file. Reopen if this is still valid.
