### ISSUE TITLE
MARI: LabVIEW 2012 installation or runtime 2017 installation

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3883]
MARI is due to be migrated to IBEX before the December 2018 shutdown as stated in ticket #3753.  They need to commission DAEIII with a full set of detectors and the program written by electronics appears to need a more recent version of LABVIEW than the default.  We can install a later version or a later runtime and a LabVIEW executeable.  It may also be possible to back port to the default version.

We just need to decide which.  They need to configure the DAEIII this afternoon.

**Comment by John-Holt-Tessella** [comment]
For my money if we can not use the 2010 version then we may as well go the whole way and use the latest version, but with the caveat that SECI/labview may or may not work. Are they happy with that?

Plus we need to be aware of this if they want to use any LVDCom components. 

I assume that this decision is reverable so if we decide that it is not working in the latest version we can install an older version?

**Comment by ChrisM-S** [comment]
It turns out that we had the same issue on IMAT a while back 2016 and saved the code from LabVIEW 2016 back to LabVIEW 2010 so we could put the VIs in as normal (this also gives us the ability to LVDCOM if scripted parameter changes to the electronics are needed).  The good news is that the new VI from technology had a "LV10" sub-folder with a back compiled version in 2010.  So hopefully we are in the clear (although there are some issues with comms, it looks like the VI is OK).

I will de-propose this and close.  Thinking about it, this will be fixable once we are automatically building instrument platforms as we can simply choose a later version of LabVIEW and will hopefully have fewer VIs to test/check under later versions.
