### ISSUE TITLE
LARMOR: Blocks failing to log [Timebox: 1D]

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3884]
various blocks were added to larmor on Friday14th, some were in a component (knauer) but rest were in  the "larmor nurf" configuration. Initially the array blocks were seen to be logging ok, but subsequently none of the new blocks (array + knauer) appeared in the data file. Runs up to 35937 report having 47 blocks, after Rob restarted ibex server at  17:30 on Saturday 15th it found 61 blocks in runs 35938 onwards. So it  was logging some but not all blocks until a full ibex restart.  

See #4006 for posssibly a similar case

**Comment by FreddieAkeroyd** [comment]
Key details are probably in the BLOCKSVR log on larmor for 14th december

[Fri Dec 14 18:19:47 2018] [1544811587.82] INFO: Loading configuration: Larmor_Base_Nurf
[Fri Dec 14 18:19:50 2018] [1544811590.16] INFO: Reloading gateway
[Fri Dec 14 18:19:51 2018] [1544811591.17] INFO: Gateway reloaded
[Fri Dec 14 18:19:51 2018] [1544811591.17] INFO: UPDATING CONFIG LIST MONITORS
[Fri Dec 14 18:19:51 2018] [1544811591.17] INFO: Start creating runcontrol PVs
[Fri Dec 14 18:19:51 2018] [1544811591.18] INFO: Removing the run-control autosave files
[Fri Dec 14 18:19:51 2018] [1544811591.18] INFO: Restarting IOC RUNCTRL_01

What is missing is a line saying "Generating archiver configuration" after "UPDATING CONFIG LIST MONITORS" - it had created all the right blocks, but decided it did not need to update the archiver? This resulted in the previous config archiver values (larmor julabo) being used.

**Comment by John-Holt-Tessella** [comment]
As part of this ticket should we create a health monitor which makes sure that all blocks in the configuration are in the block archive?

**Comment by John-Holt-Tessella** [comment]
Add system test and see if it triggers. If so look at code to see where it triggers.

**Comment by John-Holt-Tessella** [comment]
Found in #4090

**Comment by DominicOram** [comment]
Can we close one of these then?

**Comment by John-Holt-Tessella** [comment]
Have we created a health check as it says above which runs as part of the instrument?
