### ISSUE TITLE
Reflectometry: Propagate alarms

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3892]
As an instrument scientist I want to know on the reflectometry screen if one of my motors is in alarm because I need to stop experimenting and investigate the problem.

This means propagating the alarms from the motor up to the beamline parameter which it controls.
For Theta which is the main parameter  (be espeacilly careful for Theta which for a readback relies on multiple components). The main status should alarm if *any* motor that we rely on has a problem.

To get the alarms try to use the monitor in CaChannel; it should tell you about alarams but I am not convinced that these works (https://cachannel.readthedocs.io/en/latest/cachannel.html#CaChannel.CaChannel.array_get_callback I think I have not passed the correct request type it should be DBR_STS_XXX). If not instead you may need to monitor the status and severity fields of the motor pv.

**Comment by John-Holt-Tessella** [comment]
Use @observable at driver level. then add in alarms to that named tuple
Then beamline update event triggers for alarm
Beamline parameters pull alarm value up (maybe as one object)
Get alarm into pv, make pv send alaram and .stat and .serv field for pv. e.g. PARAM:DET_POS needs to be in alarm AND .stat fiel needs to show value for that and .SERV field needs to show value (maybe create non Simple PV which does this automagically)

**Comment by ThomasLohnert** [comment]
- [ ] https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/244
- [ ] https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/258
- [ ] https://github.com/ISISComputingGroup/ibex_gui/pull/987

**Comment by John-Holt-Tessella** [comment]
Also added https://github.com/ISISComputingGroup/genie_python/pull/197
