### ISSUE TITLE
Reflectometry: Disable mode save

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3897]
As an instrument scientist if I restart my reflectometry server I want it to recover to disable mode if that was the mode I was in, including the incoming beam positions.

### Acceptance Tests

1. On enter disable mode all component incoming beam are saved to disk in autosave area
1. On restart if in disable mode and file exists it is loaded
    1. All components are disabled
1. On restart if in disable mode but no file exists 
    1. error
    1. all beam paths set to incoming beam path
1. Test values by:
    1.  setting super mirror and theta angles in Polarised NR mode
    1. change to disable mode
    1. move super mirror, theta and one offset
    1. record motor positions
    1. Restart IOC
    1. Move back to position given
    1. motors should be at same place

**Comment by aaron-long** [comment]
- Can you please clarify more explicitly the test steps. Specifically what you mean by "Move back to position given".

**Comment by John-Holt-Tessella** [comment]
feedback:

> 3.	If I change theta then the component which theta is based on updates so that on CRISP/SURF it is the height and angle of the detector which both change; on polref it is just the bench angle.

**Comment by ThomasLohnert** [comment]
Sorry, something is wrong when exiting disabled mode after making changes - I think the beam path needs to be re-evaluated at this point. 

Steps to reproduce (assuming SURF-like config):
1. Set beamline positions to 0
1. Enter `PNR` mode
1. Move `sm_angle` to 1
1. Enter `Disabled` mode
1. Move `sm_angle` to 0
1. Go back to `PNR` mode
    - What I would expect: Motors stay where they are, parameter readback values of components further along the bea, update to show they are offset from the beam (equivalent to 1 deg)
    - What happens: Motors stay where they are, parameter readback values continue to show 0. Can be forced to update by triggering a monitor update (e.g. move any motor axis used by the reflectometry IOC)

**Comment by John-Holt-Tessella** [comment]
Pull requests:

- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/302
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/265

**Comment by ThomasLohnert** [comment]
The unittest  `test_GIVEN_beam_line_with_disable_autosave_position_WHEN_init_THEN_incoming_beams_set_correctly_on_start` is now failing. 

The failure message is a bit cryptic (`TypeError: coercing to Unicode: need string or buffer, PositionAndAngle found`) but I think it is just because the actual PositionAndAngle from the result is different from the expected (y=0, z=0, angle=0) when it should be (0, 1, 0). Could you please fix it ?
