### ISSUE TITLE
IOC: KEPCO: Revisit and make better

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3900]
As a supporter of IBEX, I want the Kepco IOC and the associated PSUs to interact in a stable and suitable manner

**Acceptance Criteria**
1. The IOC has been revisited and refactored as appropriate
1. If it has been refactored the IOC is tested against both a BOP card and a digital interface PSU

**Notes**
1. A number of faults have been logged for Kepcos, including #3185, #3794, #3912, #3913
1. The Kepco was one of the earliest IOCs written, and as it obviously has some issues, reviewing it with our greater knowledge and skill in EPICS would likely be beneficial
1. This ticket acts an umbrella for the following tickets:
   * Requires #3794 
   * Requires #3912
   * Requires #3713

**Comment by FreddieAkeroyd** [comment]
A few things i noticed, the protocol file does not often check for replies and has “ExtraInput=ignore” in many places, is this required?  Would it be possible to wrap commands that donot naturally reply in a *OPC / *OPC? sequence for example to get acknowledgement of when they are complete? Or use ECHO mode? I also note that the IOC is set for software flow control (recommended) but are we sure this is enabled on the device?  We don’t look to send “SYST:COMM:SER:PACE XON” as far as I can tell, is it set via the front panel instead? We should also probably send an escape character to the kepco on initialisation to clear its input buffer. This does all assume I am looking at the right manual of course!

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella - this ticket appears to have made no progress since 25th Jan.  Is it likely to make progress any time soon.  If not, it should return to the backlog.

**Comment by John-Holt-Tessella** [comment]
OPC didn't work.
ECHO is also bad
Flow control is worth turning on and is on the ticket #3794 

So closing ticket.
