### ISSUE TITLE
GUI: Visual indicator that nicos is running a script

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3905]
As an POLARIS/SANDALS instrument scientist I want an indicator that a script is running in the script server on the GUI that I can see from anywhere (originally just scripting).

Try to see whether placing an icon on the script server button works (prototype this and ask users.).

**Comment by ChrisColeExpControl** [comment]
Some minor changes to the code and a design comment on pr.
