### ISSUE TITLE
Jenkins: Rationalise build servers

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3907]
As a developer I would like Jenkins to build my code as quickly as possible. Currently the way that we assign jobs to nodes isn't well organised or well thought out. This leads to times when only 1 or 2 nodes are running but there is a queue of 5 or 6 jobs. This shouldn't happen for python or GUI builds, which should run on any machine configuration.

This ticket should standardise the build servers as much as possible and make sure that each job is able to run on as many nodes as possible. The process for how we assign jobs to nodes should also be documented.

**Comment by KathrynBaker** [comment]
Our build server setup has changed since this, and is likely to be looked at for other reasons soon, but I believe this to no longer be required.
