### ISSUE TITLE
INTER: humidity chamber experiment

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3911]
There is an upcoming experiment on INTER involving a humidity chamber developed by external collaborators. This equipment is controlled by a Beckhoff PLC, INTER is currently on SECI but as the equipment is likely to be used many times in the future developing an IBEX based solution may be best. I am talking to the external users next week and will fill in more details after that.

**Comment by kjwoodsISIS** [comment]
Is this the experiment that requires a humidity chamber?
   Experiment Reference: 1820538
   Principal Investigator: Professor Jayne Lawrence 
   Title: Interaction of the nucleic acid, DNA, with a model biomembranes of varying 
            rigidity at the oil-water interface
   Date: 8-11 Feb 2019

**Comment by FreddieAkeroyd** [comment]
It looks like tcIoc with a caLab wrapper is the best option

**Comment by kjwoodsISIS** [comment]
Remove from SPRINT_2019_04_25 while ticket is is "awaiting" state.

**Comment by GRyall** [comment]
This experiment will now have happened. Either we now support the device, or it is far enough in the past that the acquirements will have changed. We can open a new ticket if details become available.

**Comment by GRyall** [comment]
Meant to close this with my previous comment.
