### ISSUE TITLE
IOC: KEPCO

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3912]
As a LARMOR instrument scientist I want to be able to set the KEPCO to use -ve current. This does not work on the 50 BOPs model. You must set a negative voltage then a negative current.

Acceptance Criteria:

1. Current can be switched to -ve
1. Test and emulator are written to capture behaviour
1. -ve current still works on the digital KEPCOs

Note:

It is not clear to me whether there is a protocol difference between BOPs and digital KEPCOs.

**Comment by Tom-Willemsen** [comment]
The explanations of what current/voltage setpoints do in each mode that you've just given me in person is confusing and needs to be better explained on the wiki

**Comment by John-Holt-Tessella** [comment]
Added words and link to opi

- https://github.com/ISISComputingGroup/ibex_gui/pull/850
