### ISSUE TITLE
LOQ: MOXA ioLogik 1240 and 1262

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3918]
As a LOQ instrument scientist, I want to be measure my ORDELA detector temperature and voltage using MOXA ioLogik hardware. The voltages will be recorded using a MOXA E1240, the temperatures measured using a thermocouple connected to a MOXA E1262. These are modbus devices.

#### Acceptance Criteria
- [ ] Voltages can be read back from an e1240
- [ ] Temperatures can be recorded using thermocouples connected to an e1262
- [ ] These measurements are exposed as PVs so they can be monitored and logged
- [ ] A NAGIOS alarm is set up to monitor the thermocouple readings

### After merging
- [ ] Rename the existing moxa 1210 repository to `-E12XX` and update the git submodule

#### Notes
1. The e1240 and e1262 share a user manual. This can be found in the manuals share under the MOXA 1200 Series
1. The e1240 should already be supported by the moxa e1210 driver here: https://github.com/ISISComputingGroup/EPICS-MOXA-IOLOGIK-E1210
1. It is likely our existing driver could be modified to accommodate the e1262. If this is not possible there is a vendor driver for a moxa e1260 which could be easier: https://gitlab.com/LBCS-ELI-BL/epics-ioc-moxa-e1260_pub
1. To locate the IP address of the device on the network, use the moxa ioSearch utility found in the manuals share at `<manuals share>\MOXA E1200 Series\moxa-iologik-e1200-series-iosearch-utility-v2.0.0.zip`. See the wiki for details on how to use this tool

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella - please define this ticket to accurately reflect what needs to be done.

**Comment by Alistair-McGann-Tessella** [comment]
PRs:
[EPICS base](https://github.com/ISISComputingGroup/EPICS/pull/152)
[Upgrade steps](https://github.com/ISISComputingGroup/EPICS-upgrade/pull/23)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/348)
[Emulators](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/15)
[IOC Test Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/153)
[Support module](https://github.com/ISISComputingGroup/EPICS-MOXA-IOLOGIK-E1210/pull/4)
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/846)
