### ISSUE TITLE
Offline experiment Keithley 2420

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3920]
Seb Long will be doing an offline experiment using a Keithley 2420 next week (starting 15th/16th)

- [x] Find out which control machine they are using (SELAB? POLARIS?)
- [x] Set up Keithley 2420 using instructions at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-2420-(POLARIS-Thermoelectric-cell)
- [x] Test that user is happy with the setup

**Comment by Tom-Willemsen** [comment]
Set up on SELAB. Two eurotherm crates and Keithley set up, shown to user, and user is happy.

**Comment by ThomasLohnert** [comment]
Anything to be done for review?

**Comment by John-Holt-Tessella** [comment]
Check SELab is happy and make sure connection info has been recorded on the specific ioc web page:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-2420-(POLARIS-Thermoelectric-cell)

**Comment by Alistair-McGann-Tessella** [comment]
The user was happy with the set-up done here. The cabling was performed before this work was started so the connection information can't be written down for it.
