### ISSUE TITLE
IOC: JASCO: Create IOC

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3923]
As an instrument scientist I would like to control the JASCO pump so that I can do experiments with it.

The JASCO pump has been looked at and found to be ok to talk to see #3743. There are no nasty suprises as far as we can see.

As normal we need IOC, emmulator and OPI.

**Comment by John-Holt-Tessella** [comment]
This is a serial device, has about 15 commands. The only slight difficulty is you can send it programs which might be useful to users. I.e. pump this x minutes and this for y etc.
I think we should probably expose this as a typical program with values you can set but it does make the IOC more complicated.

**Comment by kjwoodsISIS** [comment]
Please don't forget to estimate the points.

**Comment by DominicOram** [comment]
@FreddieAkeroyd: When is this needed and by which instrument?

**Comment by aaron-long** [comment]
IOC Device Generator fix
- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/10

**Comment by FreddieAkeroyd** [comment]
Potential beamlines are:

OFFSPEC
SURF
POLREF
LARMOR
INTER

**Comment by ThomasLohnert** [comment]
Functionality looks good to me! Some minor points:
- Would it be feasible / useful to validate the sum of the gradients similar to what I believe you did for the Knauer?
- `COMP:`-related things are referred throughout the `.db`  and tests as "Composition", whereas on this front panel, and in the wiki entry, it says "Component".  Can you please make it consistent?
- The device response is a bit odd when in `RECSIM`: Setting the flow rate sets the pump status to running, while start/stop/timed don't seem to work.
- Little bits of tidying up on these branches:
    - [ ] [EPICS](https://github.com/ISISComputingGroup/EPICS/pull/154)
    - [ ] [ibex_gui](https://github.com/ISISComputingGroup/ibex_gui/pull/847)
    - [ ] [Device Generator](https://github.com/ISISComputingGroup/IBEX_device_generator/pull/10)

**Comment by aaron-long** [comment]
Rework:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/157
- https://github.com/ISISComputingGroup/EPICS-Jsco4180/pull/2
