### ISSUE TITLE
Import tcIoc repository

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3925]
The TwinCAT IOC repository is currently in FreddieAkeroyd on GitHub - move to ISISComputingGroup and integrate into standard builds. Needed for #3911

**Comment by FreddieAkeroyd** [comment]
Twincat imported into https://github.com/ISISComputingGroup/EPICS-tcIoc and modified so will use standard EPICS build system rather than visual studio.

It will build a tcIoc.exe that will read a beckhoff typ file etc as per instructions for the LIGO driver. It builds on x64, but from the warnings I saw will probably not work there as it casts a pointer to a LONG leading to truncation. SHould work OK on win32 build

**Comment by FreddieAkeroyd** [comment]
64bit issue now believed fixed

**Comment by FreddieAkeroyd** [comment]
@DominicOram is probably best placed to review this

**Comment by DominicOram** [comment]
Builds and works, added tickets for writing automated tests.
