### ISSUE TITLE
Deploy: Update ISISICP as part of the upgrade script

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3928]
Add to deployment script a step to automatically install latest icp. This needs to differentiate between DAE2 and DAE 3.

### Acceptance Criteria

- upgrade script deploys correct ICP on machines where ICP is in `labview modules`
- On machines where it is in `icp_binaries` double check that `create_icp_binaries` is run and the ICP is registered

**Comment by DominicOram** [comment]
Look at the existing config.xml to work out to use DAE2/3.

**Comment by FreddieAkeroyd** [comment]
Look at ISISICP/DAEType in icp_config.xml - if it is 1 or 2  then you need DAE2, if it is 3 or 4 you need DAE3. This file is located in c:\labview modules\dae on an instrument

**Comment by Tom-Willemsen** [comment]
I guess we also need to fall back to looking at the configuration files in `c:\instrument\apps\epics\icp_binaries` for the non-instrument machines (muon front end, riken front end, SELAB, SOFTMAT, etc). Or should we always assume DAE2 if `c:\labview modules\dae` doesn't exist?

**Comment by FreddieAkeroyd** [comment]
ICP_Binaries always has the latest appropriate version, it was only really meant for developer machines. So if c:\labview modules\dae does not exist then you should not run the script at all - if you do it will create c:\labview modules\dae for you which may not be what you wish

**Comment by FreddieAkeroyd** [comment]
The current `icp_binaries` contains files needed to compile and test on a developer machine, it was not intended for deployment. I would prefer we separate off the files we need for runtime and have e.g.   `c:\instrument\apps\ISISICP` with `icp_config.xml` and `isisicp.properties` somewhere like `c:\insrument\setting\config\NDXaaa\configurations\ISISICP`

**Comment by ChrisM-S** [comment]
Thanks @FreddieAkeroyd, I think that has cleared up any issues w.r.t. locating and necessary links for the VHD deployment as well.  Does this present any opportunities for deploying both DAEII & DAEIII binaries and leaving a decision to be able to switch at boot/runtime by registering/linking the appropriate versions of the DLLs (in our custom of deploying all code and choosing to use what we ed on a per instrument basis)?  We do have the IP admin assignment step for DAEIII MACs which could possibly do this sort of switch?

**Comment by DominicOram** [comment]
I've added https://github.com/ISISComputingGroup/IBEX/issues/5518 for changing where the ICP is stored in the long run. For this ticket I propose we should fail the automated step if the ICP is not in `labview modules` and instead give instructions on how to manually update.

**Comment by FreddieAkeroyd** [comment]
If  `c:\labview modules\dae` does not exist, then the recent version of the isisicp will already be available in the installed `icp_binaries` so I don't think there is anything extra to update manually. I believe running `create_icp_binaries` is already done, or suggested, as part of install for these instruments?

**Comment by DominicOram** [comment]
Ok, then as part of this ticket we should ensure that `create_icp_binaries` and registering the ICP is done on these machines as part of the install

**Comment by DominicOram** [comment]
@FreddieAkeroyd do you need to re-run regserver if you're just replacing the executable? I think it's been fine for me locally as long as the path to the executable doesn't change

**Comment by DominicOram** [comment]
Also, which file do I want to run? `\\isis\inst$\Kits$\CompGroup\ICP\ISISICP\DAE*version_from_config*\*LATEST_BUILD*\update_inst_main.cmd`?

**Comment by FreddieAkeroyd** [comment]
You run `update_inst.cmd` - see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Upgrade-ISISICP

register_programs doesn't just register the program location, i believe it also registers the functions available via DCOM. So if a new function was exported by isisicp and used by ISISDAE IOC then ISISDAE IOC would not work - or that is what has happened in the past anyway. In practice I vary rarely add new functions, the last were for live view, so you usually get away without running it. If you are moving an instrument from SECI to IBEX which had an old isisicp you certainly would need to run register

**Comment by DominicOram** [comment]
Thanks! I will always run the register, just in case we add some functions in the future.

**Comment by DominicOram** [comment]
Also requires https://github.com/ISISNeutronMuon/ISISICP/pull/23
