### ISSUE TITLE
Moxa 12XX: Add tests for counters

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3929]
As a developer I would like to know if the DI counting has been broken by something through automated tests. The moxa 1210 includes a basic test which could be built on.

### Acceptance criteria

1. The counting function of the moxa e1210 IOC is tested in the IOC testing framework

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/150
