### ISSUE TITLE
motionsepoints: add PV to report nearest position (ignoring tolerance)

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3930]
Currrently motionsetpoints tells you your nearest named position withing the specified tolerance, it would be useful to also have the nearest named position (regardless of tolerance)

**Comment by John-Holt-Tessella** [comment]
After this plug this into the loq aperture so that we can reduce the tolerances on it.

**Comment by kjwoodsISIS** [comment]
How many points?
