### ISSUE TITLE
support: gem mercury iTC

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3933]
GEM are testing a repaired mercury iTC temperature controller this afternoon/evening. 

Comms look ok via hyperterm at 115200 baud, example command `READ:SYS:TIME<CR><LF>` but labview driver at same baud rate doesn't talk (the ibex driver is an lvdcom)

**Comment by Tom-Willemsen** [comment]
Underlying issue was that the baud rate in the labview setup dialog is ignored by the driver, and it actually uses a constant baud rate fixed in the low level VI at 57600.
- I have changed the fixed number on gem to 57600 to get them operational
- @davidkeymer will look at correctly propagating the setting in the setup down to the low level VI

**Comment by kjwoodsISIS** [comment]
I am guessing that the low-level VI is supplied by Oxford Instruments as part of the iTC.  Is that correct? 
 If so, why does @davidkeymer need to fix the propagation of the baud rate.  Why aren't Oxford Instruments doing this?  Who at ISIS deals with OI?  Can they get OI to fix the issue?

**Comment by ChrisM-S** [comment]
There is an urgent follow up issue in that when this disappears from GEM it will likely turn up somewhere else with a baud rate which is un-programmable without a support call... (Saturday evening anyone?)  unless anyone objects could we ask that cryogenics set this back to 57KBaud asap (if possible?).

This does bring back an old issue of agreeing standard standard baud rates with SE and Cryogenics (at least for the same types of kit).  I'm also unsure of why we need such a high rate anyway (probably OIs fault) - it will rapidly find any overly long cable runs with transmission errors - more support calls... :unamused:

**Comment by GDH-ISIS** [comment]
The LabVIEW Mercury software on GEM is out of date - Sorry. All that is needed is an update from SourceSafe.
C:\LabVIEW Modules\Drivers\Oxford Instruments
C:\LabVIEW Modules\Common
That should solve the issue. I agree with @ChrisM-S above. To date, I have configured all the Mercury units to be 57600 baud rate as I also believed that there was an element of risk using 115200 baud rate.

**Comment by John-Holt-Tessella** [comment]
Directories updated on GEM I will assume this works since the mercury is no longer connected I can not test.
