### ISSUE TITLE
INES: new sample stack

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3937]
A new sample stack is being installed on INES, it will use the existing Galil. Work will start  11th February and it will need to be operational for scientists 4th March. It will be 4 stepper axes, normal home and limit switches. I believe top is a huber stage. There will be a safety system, we may need to read status from Galil inputs. They will contact us later, Iain Johnson will commission so hopefully not a lot for us to do.

**Comment by FreddieAkeroyd** [comment]
John Crawford is running the project

**Comment by John-Holt-Tessella** [comment]
waiting on hardware

**Comment by FreddieAkeroyd** [comment]
Now configured on INES.
