### ISSUE TITLE
IPS tweaks

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3942]
Based on feedback from scientists and cryogenics:
- [x] Put sweep rate control under an "advanced" tab of some sort and put manager mode on it
- [x] Move the diagnostics information to an "advanced" tab
- [x] Increase heater dwell time from 30s to 60s (this is more conservative)
- [x] The magnet only actually goes up to 8.8T

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/ibex_gui/pull/845
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/154
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/349
