### ISSUE TITLE
INES: IBEX startup batch file failed to run

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3943]
On rebooting after updates, the startup script failed to run for the instrument.  I rebooted just in case this was something to do with the upgrade but it did the same thing so the server does not restart after a crash currently

**Comment by ChrisM-S** [comment]
It looks like the instrument is referring to a location from its disk via a network path (rather than C:\).  Not sure quite why this is, the file does not appear to be "blocked" as it might be if it was an internet download.
![image](https://user-images.githubusercontent.com/3035405/51552096-c78ecc80-1e67-11e9-97a5-9dfed200e16d.png)

**Comment by KathrynBaker** [comment]
The situation is quite different by now I believe, closing.
