### ISSUE TITLE
Muon Front End: NGPS PSU - Ethernet Comms [TIMEBOX: 1 day]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3944]
As a muon scientist I want to be able to control the NGPS/OCEM PSUs from NDEMUONFE

**Acceptance Criteria**
1. The Ethernet interface on the NGPS/OCEM PSUs is activated.
1. The IOCs are able to connect to the PSUs and read and set/commands as per #1922

**Notes**
1.  We have previously tried to communicate with the NGPS/OCEM PSUs using serial communications.  This did not work (see #3447).  The purpose of this ticket is to attempt to get ethernet communications working on the NGPS/OCEM PSUs.
1.  This ticket is deliberately timeboxed.  If we can't establish ethernet communications in a straightforward manner, we need to re-think how we communicate with this device.

**Comment by FreddieAkeroyd** [comment]
Firewall box configured, telnet from outside seems to work OK. @Tom-Willemsen will test with IOC

**Comment by Tom-Willemsen** [comment]
Communication with IOC looks good. Values reading back as expected (currently reading errors due to interlocks). 

- https://github.com/ISISComputingGroup/EPICS-ioc/pull/351

I will contact the muon scientists and schedule a short test with setting currents etc.

**Comment by ChrisM-S** [comment]
When you are happy with this @FreddieAkeroyd I can get another similar box for a spare.  Does it allow you to save its whole configuration to a file like the Netgear to make it it easy to replace (or configure similar ones)?

**Comment by FreddieAkeroyd** [comment]
Looks like you can save the configuration to a file on a USB stick and later restore from that

**Comment by FreddieAkeroyd** [comment]
Setup documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Muon-NGS-Power-Supply-Firewall

**Comment by FreddieAkeroyd** [comment]
Currently an issue with slow network from NDEMUONFE to the supplies

**Comment by kjwoodsISIS** [comment]
Can we call this resolved now?

**Comment by FreddieAkeroyd** [comment]
I have found a workaround by deleting the local routing path so that all subnet traffic goes via the gateway. Facilities IT are investigating the HyperV network configuration, but have confirmed it is OK for us to run with the route removed. I just need to make sure it gets removed at boot time, but I think we are now complete from the ethernetting point of view. So we just need to demo to the scientists.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - is this ticket now resolved?

**Comment by KathrynBaker** [comment]
As the ticket is listed for review, I will review this. The scientists have been using these PSUs, and so the comms is valid. The routing is still an outstanding issue, but is separate to this ticket and is not limited to these devices. The resolution is being looked at by the network infrastructure expert for ISIS.

The associated PR had been flash reviewed in January, so this ticket can be considered resolved.
