### ISSUE TITLE
Talk to cryogenics about Baud rate on Mercury

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#3945]
As a supporter, I would like to avoid unnecessary support calls when the mercury device in #3933 is connected anywhere other than on GEM.

1) ensure that the baud rate on the Mercury tested on GEM this shutdown is changed if possible to the standard 56K for these devices.

2) The GEM configuration for this device is set to 56K as well (so on return of any mercury it is set correctly).

note: this will need someone to chat with cryogenics who knows the device.

**Comment by FreddieAkeroyd** [comment]
According to cryogenics, the baud rate can be changed from the device front panel so long as it is in local/manual mode

**Comment by John-Holt-Tessella** [comment]
Is noted on IOC specific page.
