### ISSUE TITLE
EMU: Control of Stanford DG645 Digital Delay Generator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3947]
As an EMU scientist, I want IBEX to support the Stanford DG645 Digital Delay Generator on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing solution in SECI.
1. I can control the Stanford DG645 Digital Delay Generator via the IBEX GUI
1. I can control the Stanford DG645 Digital Delay Generator via genie_python

#### Notes
1. The SECI VI is located here: `C:\LabVIEW Modules\Drivers\Stanford DG645`.  Please consult the VI to ensure the IOC and OPI provide equivalent functionality.
1. Consult the [EMU instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/EMU-Instrument-Details) page for additional documentation
1. The DG645 is used in RF experiments on muon instruments.  Check `C:\LabVIEW Modules\Muon RF` and `C:\LabVIEW Modules\Instruments\MUSR\RF Experiment` to see how the DG645 driver is used.  Also ask the scientists how they use the RF equipment.

**Comment by FreddieAkeroyd** [comment]
The synApps delaygen module mentioes this device https://epics.anl.gov/bcda/synApps/synApps.html and there is also a driver at NSLS2 https://github.com/NSLS-II-CSX/stanfordDG645

**Comment by Tom-Willemsen** [comment]
From @KathrynBaker 
- Not too difficult to talk to
- Lots of parameters - but a lot of these can be templated/substituted
- Potentially some device-specific logic on top
- If AMINT2L = 1 and stress rig = 8 then this is a 6.
- Consider splitting this ticket into multiple tickets once we understand a bit more about this device
- Initial estimate: 8 pts

**Comment by FreddieAkeroyd** [comment]
There is some existing EPICS work:

https://github.com/NSLS-II-CSX/stanfordDG645
https://epics.anl.gov/bcda/synApps/delaygen/delaygen.html

Also a TANGO driver too

https://sourceforge.net/p/tango-ds/code/HEAD/tree/DeviceClasses/CounterTimer/DelGen645/trunk/

**Comment by davidkeymer** [comment]
This device is **_not_** required as part of the minimum set of equipment for EMU to operate.  It may be used, along with the signal generator in #3948, in as yet unscheduled experiments.

**Comment by Tom-Willemsen** [comment]
According to the scientists, the next time the RF kit is likely to be used *on emu* in September at the earliest. Other instruments (e.g. musr) may use it sooner.

**Comment by Tom-Willemsen** [comment]
On discussion with EMU scientists, this is no longer a requirement for the Sept cycle.

**Comment by kjwoodsISIS** [comment]
Ticket #5154 is identical to this.  Closing this ticket in favour of #5154.
