### ISSUE TITLE
EMU: Control of Aeroflex/IFR 2030 Signal Generator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3948]
As an EMU scientist, I want IBEX to support the Aeroflex/IFR 2030 Signal Generator on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing solution in SECI.
1. I can control the Aeroflex/IFR 2030 Signal Generator via the IBEX GUI
1. I can control the Aeroflex/IFR 2030 Signal Generator via genie_python

#### Notes
1. The SECI VI is located here: `C:\LabVIEW Modules\Drivers\Aeroflex 2030`.  Please consult the VI to ensure the IOC and OPI provide equivalent functionality.
1. Consult the [EMU instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/EMU-Instrument-Details) page for additional documentation

**Comment by Tom-Willemsen** [comment]
From @KathrynBaker 
- Responses from device will need splitting at the protocol level
- Serial, but talking to the device might be troublesome
- if AMINT2L = 1 and Stress rig = 8 then this is a 4.
- Initial estimate: 5 pts

**Comment by davidkeymer** [comment]
This device is **_not_** required as part of the minimum set of equipment for EMU to operate.  It may be used, along with the delay generator in #3947, in as yet unscheduled experiments.

**Comment by Tom-Willemsen** [comment]
According to the scientists, the next time the RF kit is likely to be used *on emu* in September at the earliest. Other instruments (e.g. musr) may use it sooner.

**Comment by Tom-Willemsen** [comment]
On discussion with EMU scientists, this is no longer a requirement for the Sept cycle.

**Comment by kjwoodsISIS** [comment]
Superseded by #6079.
