### ISSUE TITLE
Tech Debt Standdown Day

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3951]
As a developer I would like to fix technical debt on my project.

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Technical-Debt-Stand-down

**Comment by DominicOram** [comment]
Squish tests this time round?

**Comment by DominicOram** [comment]
Squish tests were done, I want to wait for #4040 to be reviewed before this is reviewed

**Comment by DominicOram** [comment]
PR at https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/22/

**Comment by kjwoodsISIS** [comment]
This ticket is now technical debt arising from a Tech Debt stand down day.  Can we get it completed asap please.

**Comment by kjwoodsISIS** [comment]
PR can be completed at a later date (when we have the capacity to do so).   Completion tasks moved to ticket #4282.
