### ISSUE TITLE
MUONS: Zero-field Controller Discussion

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3957]
As a developer, I need to understand, in detail, the operation of the muon zero-field controller, so that I can correctly implement control software for it.   There I need to review  the current [zero-field controller documentation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller) with a muon scientist, to get confirmation that the documentation is accurate and correct.

#### Acceptance Criteria
1. A meeting with the muon scientists is held to review the documentation.
1. The muon scientists confirm that the documentation is accurate and correct.

#### Notes
1. Consider asking the muon scientists to review the wiki page in advance.

**Comment by DominicOram** [comment]
@Kevin-Woods-Tessella Can we clarify exactly what questions we need to ask the scientists for this?

**Comment by kjwoodsISIS** [comment]
We are not ready to do this yet.  Put it back on the backlog.

**Comment by John-Holt-Tessella** [comment]
Is this not just a check that the document we wrote is correct? In fact should we not just send them an email and check?
