### ISSUE TITLE
VESUVIO: Latest journal entry is delayed

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3959]
The VESUVIO scientists have noticed that there is a delay in displaying the journal entry for the latest run.  Refreshing the Journal Viewer does not always display the run.  It seems that they have to complete another run, before they can see the journal entry for the run they were trying to view.  This issues needs investigation.
Issue noted at SAG meeting (24-01-2019)

**Comment by DominicOram** [comment]
Is a fix for this required before release?

**Comment by kjwoodsISIS** [comment]
No.  It is not urgent.

**Comment by Tom-Willemsen** [comment]
All looks normal on Vesuvio at the moment (the last run from last cycle is displayed correctly). I have had a chat with Matthew K. and he will re-report this issue if he sees it again. I suspect it was just scrolled down (as described above)
