### ISSUE TITLE
genie_python: cset/cget issue an error

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3960]
As a larmor instrument scientist when I issue a cset or cget I want an error to be writtern to stderr if it is in alarm so that there is a visual indicator in the scripting windows that there may be a problem with setting/getting a value in my scripy.

Acceptance Criteria

1) After finishing cset if the record I have set is in alarm or value readback  is in alarm then a exception is thrown which is caught by the api layer and prinnting to std_out
2) If the alarm is triggered after the set (i.e. on next read) the exception does not need to be thrown
3) Value must still be returned

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/153
