### ISSUE TITLE
POLARIS: install and configure new moxa

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3961]
A second Moxa box is to be located on the shielding enclosure surrounding the Polaris sample position in order to tidy up a few network cables in the experiment working area on the beamline (and removing potential trip hazards). They already have a second Moxa box and a mounting bracket has already been screwed to the Polaris enclosure wall ready for the Moxa box. They require:

1. that we connect a few (much shorter) cables between sample environment kit and this Moxa box
2. the second Moxa is connected to the network
3. the IBEX OPIs are tweaked if necessary to reflect the new COM port numbers

They would like this done before the start of 2018/4 - but it's not a show stopper if it needs to wait until the April/May shutdown...

**Comment by ChrisM-S** [comment]
2nd Moxa now connected up and talking to rotation stage and furnace.  Furnace OPI doesn't seem to be making any sense. Will pass Moxa so SE electronics to rotate power socket tomorrow.
