### ISSUE TITLE
IOC tests: make stable

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3962]
As a developer I would like to be confident that the devices I test using the IOC test framework work properly.

The following tests are failing consistently:
- [x] `tests.moxa1240.Moxa1240TestsFromBase.test_WHEN_device_voltage_is_above_high_limit_THEN_PV_shows_major_alarm`
- [x] `tests.moxa1240.Moxa1240TestsFromBase.test_WHEN_device_voltage_is_below_low_limit_THEN_PV_shows_major_alarm`
-  [x] `tests.wbvalve.WbvalveTests.test_GIVEN_an_ioc_WHEN_set_valve_to_wb1on_THEN_status_is_wb1on_0_wb1`
- [x] `tests.wbvalve.WbvalveTests.test_GIVEN_an_ioc_WHEN_set_valve_to_wb1on_THEN_status_is_wb1on_1_wb2`
- [x] `tests.loq_aperture.LoqApertureTests.test_GIVEN_motor_between_setpoint_positions_WHEN_motor_set_to_closest_beamstop_THEN_motor_moves_to_closest_beamstop_2_Aperture_medium`
- [x] `tests.loq_aperture.LoqApertureTests.test_GIVEN_motor_between_setpoint_positions_WHEN_motor_set_to_closest_beamstop_THEN_motor_moves_to_closest_beamstop_3_Stop_02`

**Comment by Alistair-McGann-Tessella** [comment]
LOQ aperture issues addressed in these pull requests:
[Motor Extensions](https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/21)
[IOC test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/156)

**Comment by Alistair-McGann-Tessella** [comment]
The IOC system tests are failing for different reasons now, which makes it difficult to see whether the non-aperture IOCs are still an issue. As a result I am submitting the current work done on this without changes to the kepco or ag33220a; if these are still a problem when the build starts running again then they can be addressed separately.

**Comment by Alistair-McGann-Tessella** [comment]
I've updated the ticket with the tests which are now failing consistently.

Pull request for the Moxa 12XX and wbvalve fixes:
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/159
