### ISSUE TITLE
Eurotherm: make ramp rate setpoint clearer

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3964]
As an instrument scientist on MARI, I would like the Eurotherm OPI to be more explicit about exactly what is being set when I type a number into the ramp rate setpoint box. It would be helpful if it was labelled "ramp rate setpoint" or something equally descriptive. In the current user interface, I could confuse this with the temperature setpoint.

![image](https://user-images.githubusercontent.com/24375813/51927925-a50f2d00-23ec-11e9-8920-88779537177b.png)

**Comment by aaron-long** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/851

**Comment by kjwoodsISIS** [comment]
How many points?
