### ISSUE TITLE
GUI: Blocks fill their perspective more efficiently

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3966]
As an instrument scientist or user I want to be able to see as many of my blocks in one view as possible. The blocks perspective appears to have a lot of white space on instruments which have a many groups with only a few blocks in each. This means that some blocks will be hidden to the right of the screen, even though there may be enough room on the perspective to show all information without a scroll bar.

## Acceptance criteria
- [ ] Multiple groups may be placed in the same vertical column in the blocks perspective

**Comment by Tom-Willemsen** [comment]
Is this the same as https://github.com/ISISComputingGroup/IBEX/issues/3512 ?

**Comment by kjwoodsISIS** [comment]
How about providing an option to display blocks "ungrouped" (i.e. simply display them in alphabetical order (probably best), or in order of creation (I think this is less good))?
