### ISSUE TITLE
motionsetpoints: remove limit

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3967]
As per comment in ISISComputingGroup/EPICS-motionSetPoints#13 the internal c++ logic should use std::string and not a fixed buffer to avoid any future issues (you will still need to edit the db file at two places, but it will save forgetting to do the c++ code)

**Comment by JamesKingWork** [comment]
Fixed as part of https://github.com/ISISComputingGroup/IBEX/issues/4573
