### ISSUE TITLE
LOQ: Patches

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3970]
As a LOQ innstrument scientist I had these patches done to my system and don't want to loose them when I update my system.

1. Water bath valve labels are no "J1" and "J2" not wb1 and wb2
1. Waterbath valve uses "\r\n" as a terminator not "\r"

**Comment by Alistair-McGann-Tessella** [comment]
Pull request:
https://github.com/ISISComputingGroup/EPICS-Wbvalve/pull/2

**Comment by kjwoodsISIS** [comment]
How many points?
