### ISSUE TITLE
IOC: Julabo flow control

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3971]
As a ZOOM instrument scientist I need flow control to be on for my Julabos.

Accetance Criteria

1. There is a macro which allows software flow control to be switched on
1. The macro defaults to OFF
1. On ZOOM the macro is set on on.

**Comment by FreddieAkeroyd** [comment]
As per PR comment there should also be a macro for hardware flow control as i believe the julabo can be in either software or hardware flow control; i'm not sure i saw no flow control as an option when i had the issue on ZOOM? We should confirm the default with Andy Church.

**Comment by Alistair-McGann-Tessella** [comment]
The ISIS default has been both hardware and software flow control is off. Is it a good idea to change this for all established users of Julabos? Flow control was also set to off in the SECI VI.

**Comment by FreddieAkeroyd** [comment]
I don't think the Julabo supports flow control off, the menu only appears to allow you to choose between "software on" or "hardware on". The factory default is hardware on according to the manual, if ibex/seci is set for no flow control then it will probably work unless the device asks for ibex/seci to stop sending it data (which seci/ibex will ignore). So flow control off will probably work, but is strictly not a correct setting for the device.
