### ISSUE TITLE
IMAT: error with init_imat when starting genie_python

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3973]
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

genie_python version 5.0.1
No instrument specified - loading local instrument
pv prefix NDXIMAT
THIS IS IMAT!
There was a problem with loading init_imat so will use default.
Error was name 'load_script' is not defined
PV prefix is IN:IMAT:

In [1]:

**Comment by DominicOram** [comment]
Instrument scientist responded saying they were happy so closing this off.
