### ISSUE TITLE
Muons: power supplies

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3975]
As a muon instrument scientist I want my power supplies to work
- An RS232 danfysik was plugged into a moxa port configured for RS422. This (unsurprisingly) didn't work
- An ioc didn't release a serial port when killed. This is a similar issue to the "undead processes" that we saw a couple of cycles ago
- When muonfe was restarted to fix the above, the NGPS power supplies didn't talk as the network needs a configuration command before it's functional
- One of the danfysiks on riken front end doesn't read voltage. This turned out to be a hardware issue.
- Two of the danfysiks on MFE report `HIGH_ALARM` because the raw readings are more than 100,000.

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/EPICS-NGPSPSU/pull/2
- https://github.com/ISISComputingGroup/EPICS-SEPRTR/pull/3

Both PRs were hotfixed on MFE at start of cycle to make calab wrapper work, this just puts the fixes back into git

**Comment by KathrynBaker** [comment]
Given the PSUs are talking and the scientists aren't still asking us to fix them, I'd say those parts are all fixed.
Code changes also acceptable.
