### ISSUE TITLE
LOQ: Galil offset not defined correctly

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3976]
As a LOQ instrument scientist I need my Galil positions to be read back correctly. Currently there appears to be a 10mm offset applied to all of the values on the translation stage (sample changer). When SECI is used to control the motor after IBEX was used, a different offset is apparent until the galil is hard rebooted. Hard rebooting did not solve the issue for IBEX.

## Acceptance criteria
- [ ] LOQ's translation stage correctly reads back the position

**Comment by Alistair-McGann-Tessella** [comment]
This only affected axis 3 of the gailil, the sample changer. It appeared that the Galil driver in SECI had extra logic on this axis for the sample changer scan which meant that the homing routine was not the same as other galil homing routines. When the axis was homed in both SECI and IBEX the axis was left in different positions. The issue was resolved by homing the axis in IBEX and running the sample changer scan to re-calculate the offset. The axis appears to be functioning normally now

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella - thanks for clearing this up.  Any suggestions for how we might avoid being burned by a similar issue in future?

**Comment by Alistair-McGann-Tessella** [comment]
It might be useful to compare the encoder positions after a home in both SECI and IBEX; this lets us know much earlier if there is a problem (a big discrepancy). It also looks like the SECI VI is different to IBEX homing routine, so it might not always be appropriate to copy over the parameters (e.g. offsets) exactly. However, this has worked reasonably well for us so far, so it's unclear when copying parameters over is/isn't the right thing to do.

I'll leave this ticket in progress for a bit longer to make sure that the LOQ instrument scientist is still happy with the solution

**Comment by John-Holt-Tessella** [comment]
Put the hotfix #4090 on to LOQ and see if this fixes the above.

**Comment by Alistair-McGann-Tessella** [comment]
I've spoken with a LOQ instrument scientist, he is happy that the galils are now operating correctly. If this issue happens again a new ticket should be raised
