### ISSUE TITLE
Dataweb: False alarms showing on LOQ blocks

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3978]
As a LOQ instrument scientist I don't want my dataweb to show alarms when the underlying PVs are not in alarm and these are not showing up on the GUI.

When this issue was raised, the SampleStack Changer and Height blocks were both in alarm, even though the underlying PVs were not. Data_acquisition Tx_Mon and Aperture_2 were also falsly showing alarms.

**Comment by John-Holt-Tessella** [comment]
We should investifgate this or close it as a one off. What was the solution @Alistair-McGann-Tessella?

**Comment by Alistair-McGann-Tessella** [comment]
This has not been raised again, so I am closing this as a one-off
