### ISSUE TITLE
SUPP: SANDALS - Gem sample changer

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3983]
Alex wants to use the GEM sample changer on SANDALS. I have said to give us a call when it is down on SANDALS if he needs a hand configuring it.

**Comment by kjwoodsISIS** [comment]
According to the scheduler, Alex will be using SANDALS on Monday, 11th Feb (starting at 8:00AM).  The ticket on the scheduler says nothing about using the GEM sample changer (but I don't think we should attach any significant to that fact).  It might be worth checking with Alex when he is doing the setup and when the experiment actually starts.

**Comment by John-Holt-Tessella** [comment]
email sent

**Comment by DominicOram** [comment]
@aaron-long and I went down and did this today. Scientists seemed happy
