### ISSUE TITLE
EUROTHERM: Minor changes to the rate PV

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3984]
As an instrument scientist the rate PV is of HIGH interest, and when creating a block I want it to have at least 2 decimal places, not be an integer.

**Acceptance Criteria**
1. The Rate has an interest level of HIGH
1. The Block displays 2 digits of precision

**Notes**
1. This came up as a support issue, but was not urgent

**Comment by kjwoodsISIS** [comment]
@KathrynBaker & @aaron-long  - can this ticket be combined with #3964?

**Comment by KathrynBaker** [comment]
It could be, the other one is a minor change, the only complexity is extra repos involved.

**Comment by aaron-long** [comment]
@kjwoodsISIS , Do you want all the work to be combined into #3964 and this ticket be deleted?

**Comment by kjwoodsISIS** [comment]
@aaron-long - in effect, yes.  I will close it.

**Comment by kjwoodsISIS** [comment]
This ticket will be implemented under #3964.  This ticket can now be closed.
