### ISSUE TITLE
MOTION Set Points: Tidy up the extra :

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3989]
As an IBEX support person I would like to eliminate the extra : I get when loading sample changers.

**Acceptance Criteria**
1. Either the requirement for the extra : is documented and obvious, or (ideally) the PVs all look sensible

**Notes**
1. The dbload in question is:
`$(IFIOC_GALIL_04) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,TARGET_PV1=$(MYPVPREFIX)MOT:STACK:Y:MTR,TARGET_RBV1=$(MYPVPREFIX)MOT:STACK:Y:MTR.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:STACK:Y:MTR.DMOV,TARGET_PV2=$(MYPVPREFIX)MOT:STACK:ZLO:MTR,TARGET_RBV2=$(MYPVPREFIX)MOT:STACK:ZLO:MTR.RBV,TARGET_DONE2=$(MYPVPREFIX)MOT:STACK:ZLO:MTR.DMOV,TOL=1,LOOKUP=LOOKUPFILE2")`
1. A portion of the `dbgrep *SAMPLE*` that looks wrong is:
```
IN:INST:LKUP:SAMPLE::MTR
IN:INST:LKUP:SAMPLE:STATIONARY
IN:INST:LKUP:SAMPLE::DMOV
IN:INST:LKUP:SAMPLE:STATIONARY2
IN:INST:LKUP:SAMPLE:COORD1:NO_OFFSET
IN:INST:LKUP:SAMPLE:COORD1:OFFSET
IN:INST:LKUP:SAMPLE:COORD1:OFFSET:SP
IN:INST:LKUP:SAMPLE:COORD2:OFFSET
IN:INST:LKUP:SAMPLE:COORD2:OFFSET:SP
IN:INST:LKUP:SAMPLE:COORD2:NO_OFFSET
IN:INST:LKUP:SAMPLE::SP
IN:INST:LKUP:SAMPLE:NUMAXES
IN:INST:LKUP:SAMPLE:POSDIFF
```

**Comment by John-Holt-Tessella** [comment]
See if this also happens when the motion set points are poited directly at the axis using AXIS1= and AXIS2= instead pf target_pv1 etc. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motion-Set-points.

**Comment by ChrisM-S** [comment]
Being super naïve, but are the spaces legal/wise/allowed in ISIS (or any) PVs?

E.g. …:NUMAXES IN:…

**Comment by John-Holt-Tessella** [comment]
Definietly not wise I don't think allowed or legal. Above you are seeing multiple pvs:

1. IN:INST:LKUP:SAMPLE::MTR 
1. IN:INST:LKUP:SAMPLE:STATIONARY 
1. IN:INST:LKUP:SAMPLE::DMOV

**Comment by davidkeymer** [comment]
There seem to be double colons in a couple of PV addresses.  Is this really how they are defined or a simple typo in the ticket?

**Comment by KathrynBaker** [comment]
This is how they look when asking for a dbl/dbgrep – I did alter the copy and paste as this has been seen on multiple instruments, and is likely on *all* of them, so I didn’t want to muddy the waters with a specific instrument name at this point in time. That double colon removal is the purpose of the ticket, tidying up the extra “:” so we get rid of it.

**Comment by ChrisM-S** [comment]
Many thanks @John-Holt-Tessella my parser is not what it used to be!  I don't suppose the double ups are unprefixed PV's adjacent to prefixes rather than real doubles?

**Comment by KathrynBaker** [comment]
For info, I’ve altered the ticket as it displays on github to be more easily read – I’d created it quickly to avoid losing the issue and the bit that got lost was formatting on the list of the PVs – which is a markdown issue, and/or an email display issue depending on how you view the tickets.

**Comment by JamesKingWork** [comment]
Completed as part of https://github.com/ISISComputingGroup/IBEX/issues/4573
