### ISSUE TITLE
Beckhoff: Run system tests

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#3991]
As a developer (IBEX or motion control) I would like to be confident in the beckhoff stack (both the code on the controller and the IOC). Now that we have an automated build (#3987) and a functional IOC (#3925) this ticket should be to bring the two together in the IocTestFramework to test the IOC against a simulated Beckhoff.

**Comment by DominicOram** [comment]
Now also being tracked by the TwinCat collaboration at https://jira.esss.lu.se/browse/MBP-88

**Comment by DominicOram** [comment]
Main PR at https://github.com/ISISComputingGroup/BeckhoffPLCCode/pull/19

**Comment by ThomasLohnert** [comment]
Tests run fine. Could you please add some more documentation, namely:
- Document the `emulator_wait_to_finish` and custom test path options in the IocTestFramework wiki
- Create a step-by-step guide on the wiki for setting up and running the Beckhoff tests
- Perhaps add a diagram for how the Beckhoff tests fit into the test framework
- Add an entry in developer release notes

**Comment by DominicOram** [comment]
Additional documentation at:
* https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket3991_tcIoc_system_tests#other-emulators
* https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff

Also updated some of the naming at https://github.com/ISISComputingGroup/BeckhoffPLCCode/pull/19 so confirm this still runs.

**Comment by DominicOram** [comment]
I've now added some tests for enums too, which would have failed prior to https://github.com/ISISComputingGroup/IBEX/issues/4521

**Comment by Tom-Willemsen** [comment]
Confirmed (eventually) that tests still run.
