### ISSUE TITLE
LET: lakeshore 340

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3992]
As an instrument scientist on LET I need to use a lakeshore 340 to measure the sample temperature when I use the dilution fridge and magnet together. This is "frequently" (i.e. multiple times per cycle) according to the instrument scientist.

This has been implemented using SDTEST on LET to get them going, but should be implemented as a proper driver.

It has a similar (but not identical) command set to the lakeshore 336 driver we already have.

**Comment by kjwoodsISIS** [comment]
Lakeshore 340 is not listed on the [LET wiki](https://github.com/ISISComputingGroup/IBEX/wiki/LET-Instrument-Details) page.  I think they may have forgotten to tell us about it.
I will update the wiki page.

**Comment by Tom-Willemsen** [comment]
Functionality of the labview driver for the lakeshore 340 (in `C:\LabVIEW Modules\Drivers\Lakeshore 340`) looks to be the following, we should aim to replicate this set of functionality:
- [ ] Set and read back a temperature setpoint (it only ever sets and reads back the setpoint for control loop 1 as far as I can tell).
- [ ] Reads 4 temperature channels
- [ ] Reads the "raw" measurements from these same 4 channels
- [ ] Reads the heater output as a percentage
- [ ] Set and read P, I and D values
- [ ] Set and read the PID mode (one of `Manual PID`, `Zone`, `Open Loop`, `Auto-tune PID`, `Auto-tune PI` or `Auto-tune P`)
- [ ] Set and read whether the control loop is on
- [ ] Set and read the maximum temperature setpoint
- [ ] Set and read maximum heater power as a percentage (the device actually looks to give a range rather than a percentage, the conversion to percentage is done in labview code).

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS/pull/160
- https://github.com/ISISComputingGroup/ibex_gui/pull/870
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/368
- https://github.com/ISISComputingGroup/EPICS-lakeshore340/pull/1
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/28
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/171

**Comment by Tom-Willemsen** [comment]
Cryogenics will give us the opportunity to test this driver against the real hardware over this shutdown.
