### ISSUE TITLE
Triton: discuss set-up with cryogenics

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3993]
As an instrument scientist, I want to understand the numbers read back from a triton system.

Currently both the IOC and the labview driver assume that "Stage 1" (Pt1) is configured as a J-T heat exchanger and that "Stage 2" (Pt2) is configured as a 4K heat exchanger. On osiris, the triton was configured in a different way, and this caused confusion for the scientist. Note that this configuration occurs on the Oxford Instruments software on the triton control PC.

This ticket is to have a meeting with cryogenics to figure out exactly how the fridges are being configured, so that we can implement a solution which works for all of the triton systems. The best contact would be  Chris Lawson. Any necessary changes to the IOC or to the VI following on from the meeting can be put in separate tickets.

**Comment by Tom-Willemsen** [comment]
More questions to ask cryogenics at the same time:
- Triton systems, closed loop mode. The scientists would like closed loop mode to be set to ON when a temperature setpoint is set, but this causes weird behaviour as the triton system changes it's temperature setpoint when closed loop is switched on/off.
  * Do we ever need closed loop to be off? Maybe leaving closed loop on should be the standard setup from cryogenics.
- Can we borrow a lakeshore 340 out of cycle to test https://github.com/ISISComputingGroup/IBEX/issues/3992

**Comment by Tom-Willemsen** [comment]
Meeting with Chris Lawson pencilled in for 4th April

**Comment by Tom-Willemsen** [comment]
Setup has been discussed - the channel mapping which we are using is the correct one. They will ensure that all fridges conform to this standard over the shutdown.

The other questions have been asked and the answers are noted on the appropriate tickets.

**Comment by SophieKSTFC** [comment]
Outcomes of the meetings have been written on relevant tickets, @DominicOram and I are happy with this.
