### ISSUE TITLE
IPS: field pv should dynamically choose which value to report

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3995]
As an instrument scientist on LET, I want a single PV I can point at which always tells me the field, independent of whether I am in persistent mode.

At the moment two PVs are available:
- `FIELD` - what the power supply is producing (drops to zero in persistent mode)
- `MAGNET:FIELD:PERSISTENT` - the persistent field in the magnet. (will always be zero in non-persistent mode)

**Notes**
- There is not a command as far as I am aware to ask the IPS whether it is in persistent mode or not. 
- The "persistent mode" toggle on the OPI is in the driver only so we should be careful about edge cases (driver restarts, hardware restarts, changes on hardware front panel, ...) if we use this
- We may be able to use whether the switch heater is turned on as a proxy for whether the magnet is in persistent mode or not.

**Comment by ThomasLohnert** [comment]
Check what labview is doing to determine this

**Comment by Tom-Willemsen** [comment]
Re-requested by LET

**Comment by Tom-Willemsen** [comment]
I checked what the labview does - as suspected it uses the switch heater as a proxy for being in persistent mode or not (see `ReadEffectiveField2.vi`).

PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/363
- https://github.com/ISISComputingGroup/ibex_gui/pull/868
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/165

**Comment by Tom-Willemsen** [comment]
It would be good to get this change reviewed in time for an experiment on LET 22/3/2019
