### ISSUE TITLE
Documentation: run control

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3996]
As a user I would like better documentation on the user manual about run-control. In particular, I would like the user manual to clarify that:

- The run-control settings saved in a configuration are permanent (to that config)
- The run-control settings set via the run-control menu are temporary (until removed or a config is loaded)
- The run-control settings set via a script are temporary (until removed or a config is loaded)

**Comment by DominicOram** [comment]
Are you still doing this @daryakoskeroglu? If you are can you add it on to the IBEX project board? If not can you remove the current milestone?

**Comment by daryakoskeroglu** [comment]
Yes, I finished it! Will do that now
