### ISSUE TITLE
galil ioc: print out more details of home position applied

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4003]
The IOC should print out the current encoder and motor positions (as well as the real world converted values) to its log file before applying a home position (raw home position = 0 in our case).

If we home an axis multiple times, the motor and encoder positions should be zero before we apply a home, so this will show us the repeatability of a home.

If the axis had been homed in SECI and we start IBEX and home, we can compare the real world position prior to applying home to give us an idea of the difference in homing positions.   See #3976

**Comment by DominicOram** [comment]
Closing as appears fixed in https://github.com/ISISComputingGroup/EPICS-galil/pull/41
