### ISSUE TITLE
Infrastructure: migrate Windows 7 and Server 2008R2 cluster machines

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4005]
Windows 7 and Windows Server 2008 have an end of life of January 2020, but the general site aim is to complete upgrades by September 2019. We have the following machines on the facilities cluster that will need upgrading to Windows 10 / Windows server 2016/2019 or decommissioning by that date. 

- [ ] NDXSELAB
- [ ] NDADETMON
- [ ] NDWRENO
- [ ] NDWVEGAS
- [ ] NDXDEMO
- [ ] NDXSCIDEMO

* NDADETMON - I need to see what it is doing, I think it was set up for detector group some time ago for monitoring but i have no idea if it is still in use.
* RENO, VEGAS - build and test servers, I'm guessing we just delete them when we no longer need a W7 build server. We can create new W10 servers prior to that.
* DEMO, SCIDEMO - pure ibex test installations, delete when time comes?
* SELAB - upgraded SECI instrument, one to test in-place upgrade W7->W10 upgrade on?

**Comment by kjwoodsISIS** [comment]
* Given that DEMO and SCIDEMo are VMs, the obvious thing to do is delete the existing DEMO and SCIDEMO machines and create new DEMO and SCIDEMO machines using W10.
* Alternatively, we could upgrade the existing DEMO and SCIDEMO machines from W7 to W10.  Would that be a worthwhile test of the W7->W10 migration process?

**Comment by FreddieAkeroyd** [comment]
I'd leave that to @ChrisM-S to decide if he wishes to test an upgrade on DEMO or SCIDEMO, I believe they were clean W7 machines with IBEX installed rather than based on an instrument clone, so it wouldn't be representative of an upgrade on a real instrument but might be a useful test in other ways.

**Comment by ChrisM-S** [comment]
Yes, I think it would just be a case of giving FIT the go-ahead to do the upgrade when it would be appropriate to do these from the IBEX point of view (making sure it is an upgrade with apps and data kept).  SELAB is the only one which is is an instrument clone so I would do this along with the rest of the clones.

DEMO and SCIDEMO are in the same situation as FIT installed Win7 ancillary machines like the IMAT camera computers so a standard FIT upgrade to 1803 might show up any potential issues with non-NDX conversion of a machine with IBEX installed (probably nothing major).

**Comment by DominicOram** [comment]
Separate ticket for NDAEXTWEB at #4036

**Comment by KathrynBaker** [comment]
Superseded by other work
