### ISSUE TITLE
Add support for Edwards nEXT240D Turbomolecular Pump

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4010]
Required on NIMROD to replace failed pump - driver available from Diamond that may do the job, will require caLab interface too for SECI

**Comment by DominicOram** [comment]
NIMROD only required reading the gauge, not controlling the pump. This is a different interface,  called the Turbo Instrument Controller. It looks like someone in Daresbury has written an IOC for this and I've reached out to them. In the meantime, given that only a single, simple command is required @davidkeymer is going to write a very quick VI.

**Comment by DominicOram** [comment]
I'll add a ticket for the IBEX support.

**Comment by davidkeymer** [comment]
VI written and added to current SECI configuration.

**Comment by DominicOram** [comment]
Had an unrelated meeting with NIMROD scientists last week. They seem happy with the current functionality of the driver. So marking this as done.
