### ISSUE TITLE
NIMROD: Edwards Turbo Instrument Controller

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4011]
As a user on NIMROD I would like to control the turbo instrument controller. This controller consists of two parts, a pump and a valve. An IOC for the pump has been taken from diamond (see #4010). There is a manual on the share for the TIC in general, which specifies the valve command. An IOC is also listed on the epics website and I have reached out to the author.

**Comment by DominicOram** [comment]
Initial vendor code added to git at https://github.com/ISISComputingGroup/EPICS-EdwardsTIC. Not yet integrated into our build system.

**Comment by kjwoodsISIS** [comment]
@DominicOram - did you hear back from the author of the IOC mentioned in the description?

**Comment by DominicOram** [comment]
Yes, the author sent me the code that I linked to in the second comment. All that is now required of this ticket is to:
* Get the IOC building in our build system
* Confirm the IOC talks to the device
* Create emulator/tests
* Create an OPI

**Comment by Kevin-Woods-Tessella** [comment]
Ah, OK.  I misunderstood the second comment.  Thanks for confirming.

**Comment by Kevin-Woods-Tessella** [comment]
Update from Tris:

> Not sure what extra functionality we would want beyond reading the pressure from the Edwards, so that’s probably fine as-is. 

So, we just need a pressure reading and a graph of pressure against time (c.f. Oerlikon IOC & OPI - see #4115).

**Comment by Kevin-Woods-Tessella** [comment]
Ticket is "in progress".  No longer needs to be in the "bucket".

**Comment by Alistair-McGann-Tessella** [comment]
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/952)
[IOC tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/228)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/422)
[Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/49)
[Support module](https://github.com/ISISComputingGroup/EPICS-EdwardsTIC/pull/1)
[Top level epics](https://github.com/ISISComputingGroup/EPICS/pull/182)

**Comment by Tom-Willemsen** [comment]
Some comments on various PRs. Largely good. Please also add release notes.
