### ISSUE TITLE
Disk full on IRIS_SETUP

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4012]
As a user and developer I want to ensure that the IRIS_SETUP machine is working correctly. 

Problem with blockserver was flagged up by configchecker, initial indication is that the disk may be full:

```
[2019-02-16 04:10:46] 2019-02-16 04:10:46.735 WARNING [Thread 29] org.csstudio.archive.engine.model.WriteThread (run) - Error, will try to reconnect
[2019-02-16 04:10:46] java.sql.BatchUpdateException: The table 'sample' is full
```

**Comment by Tom-Willemsen** [comment]
1. I have recovered a few hundred MB by moving some log files onto the usual shared drive
1. I have sent an email to the scientists asking if it's ok to go onto the machine to trim the database which is the main culprit in this case
1. We should add the setup machines to nagios (treating them like the other instrument machines) to reduce the chances of this happening again

**Comment by kjwoodsISIS** [comment]
It would be worth knowing (if possible) why the database got so large.  Has something been logging at too high a rate?

**Comment by Tom-Willemsen** [comment]
The reason is mostly that IRIS_SETUP didn't get upgraded (and hence, it's database didn't get truncated) during last shutdown. In fact, it is still on version 5.0.1 (from September last year), so it has had ~6 months worth of data that accumulated.
