### ISSUE TITLE
OSIRIS: mclennan rotation stage

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4013]
As an instrument scientist on Osiris I need to be able to control a mclennan rotation stage for an experiment starting next monday (25 Feb).

This rotation stage has been used in the past on Merlin. Ideally the scientist would like to test it at some point this week - they will enquire whether the hardware is available to connect it this week.

**Comment by davidkeymer** [comment]
I've copied the relevant component from MERLIN to OSIRIS in preparation for the installation of the (CCR) stage.  I've also renamed it to `CCR_Rotation` and edited the COM port number.  I expect the block names and groups they're in will also need to be changed.

**Comment by davidkeymer** [comment]
Now required for the morning of Tuesday 26th February.

**Comment by John-Holt-Tessella** [comment]
Gone down to look at it.

**Comment by DominicOram** [comment]
Looks fine, closing this as reviewed.
