### ISSUE TITLE
genie_python: always returns a distribution

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4014]
The get_spectrum command has a dist argument to return a distribution (i.e. counts per microsecond). This value defaults to False, however its value is ignored and a distribution is returned in all circumstances.

* make    dist=True    the default argument value to accurately reflect current default behaviour
* make    dist=False   actually return pure counts

**Comment by FreddieAkeroyd** [comment]
Currently the code uses PV     DAE:SPEC:%d:%d:Y     however for pure counts it should use   DAE:SPEC:%d:%d:YC

**Comment by FreddieAkeroyd** [comment]
To Test:
* plot_spectrum() and get_spectrum() have a dist parameter, previously this was ignored and even though it defaulted to False it behaved as if it was True

**Comment by ThomasLohnert** [comment]
As part of this ticket, performance can be improved by reducing the number of `caget` calls in `get_spectrum`. Instead of getting both y_size and x_size, get only y_size and set
- x_size = y_size if `dist=True`
- x_size = y_size + 1 if `dist=False`

**Comment by JamesKingWork** [comment]
Added testing, the suggested performance improvements and a docstring change.

To review: https://github.com/ISISComputingGroup/genie_python/pull/159
