### ISSUE TITLE
IRIS: Dilution Fridge & Rotation config needed for 21/02/2019

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4016]
As an instrument scientist on IRIS, I need to have a new configuration setup for me to run a Dilution Fridge and rotating centre stick this Thursday (21st Feb).

We will be using NDRI1 (dilution fridge) with rotation stage (no specific one) and an OX-50-08 cryostat with mercury controllers.

It will be the first time to run on IRIS, so we need a new IBEX config.

I believe this configuration or something similar has already been run on MERLIN and LET so is probably not new.  The equipment will probably be arriving Thursday Morning but there will be another user working Wednesday anyway.

**Comment by kjwoodsISIS** [comment]
Changed title to make it clear when new config is required.

**Comment by Tom-Willemsen** [comment]
Set up on IRIS, blocks created, comms checked and scientist happy.
