### ISSUE TITLE
ZOOM: Cryomagnet config needed for 20/02/2019

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4017]
As an instrument scientist I need a configuration to run a Triton Dilution fridge on ZOOM for tomorrow (Feb 20th).

**Comment by ChrisM-S** [comment]
My apologies, ZOOM is getting a **cryomagnet** tomorrow not a dilution fridge but they will set up the IPS IOC and a Neocera IOC so they will quite likely be OK to sort this unless something unexpected happens (like it suddenly morphs back into a dilution fridge :smile:

**Comment by kjwoodsISIS** [comment]
Changed title because "tomorrow" is only relevant if you are reading the ticket "today"  :-)

**Comment by Tom-Willemsen** [comment]
Set up on ZOOM with @davidkeymer and handed over to scientists (they were happy to set up their own blocks etc).

**Comment by kjwoodsISIS** [comment]
What's the impediment?  If the scientists are happy to define their own blocks, what else needs to be done?

**Comment by Tom-Willemsen** [comment]
Nothing - the ticket is in review not impeded (unless my waffle board is being silly?)

**Comment by kjwoodsISIS** [comment]
Oops.  I saw the impeded label (in the ticket) but failed see that it had been removed.

**Comment by DominicOram** [comment]
Looks like it's running fine

**Comment by kjwoodsISIS** [comment]
How many points?
