### ISSUE TITLE
Client appears to go into CPU bound loop on selecting Eurotherm OPI from synoptic

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4018]
As a MERLIN instrument scientist, I found the IBEX client seemed to get stuck and give me a white screen for a long period of time. The mouse pointer also showed a ring suggesting the client task had hung.  After restarting the client which happened quickly all looked OK until I selected the Eurotherm on the synoptic. At this point the screen went white as before for about 10-20s.  After this delay the Eurotherm OPI appeared and the screen recovered.  Behaviour since has been normal.  As someone using this instrument this was not a normal problem I see.

**Comment by Tom-Willemsen** [comment]
Rob has also reported this problem. I am not convinced it is to do with opening the Eurotherm OPI - I think it may be some kind of (semi-random?) problem. 

In any case, I think clients crashing on multiple instruments qualifies this as urgent enough to pull into the current sprint.

**Comment by DominicOram** [comment]
After discussion between myself and @Tom-Willemsen plan is to:
* Create a squish test that repeatedly opens an OPI (probably eurotherm)
* Run this with the visualVM watching it
* Hope this reproduces the issue

We found no indication of increased CPU usage in Nagios at the time of reporting and no indication of the cause in the logs.  We should also do #3606 on as many v5.2 instruments as possible during the maintenance day and some v5.1 as a baseline.

**Comment by John-Holt-Tessella** [comment]
The first time a OPI is loaded is always slower than after that. I think it must do a module load in the background. Maybe we preload the OPI module. If so create a ticket for this.

**Comment by DominicOram** [comment]
Squish tests didn't reveal any issues. #3606 is currently running on LARMOR but AFAIK they haven't seen the original issue again. I've been periodically looking at their CPU and seen nothing out of the ordinary. I've added a pending task to add this monitoring to LET and MERLIN in a maintenance day. In the mean time I can't think of anything more to do on this ticket so if anyone has any ideas please let me know.

**Comment by kjwoodsISIS** [comment]
How many points?
