### ISSUE TITLE
GUI: Update blocks in dashboard when units change

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4019]
As a scientist I can see the readback of the eurotherm block value is showing K even though the setpoint is in C.

I've tried editing the block/IOC with a right click and can't find anything to change.

Searching User manual does not seem to give any obvious way of doing this. Searching developer manual suggests editing configurations files - this seems not what one would want to do...

Is there an easy way which is undocumented or is it really as tricky as fiddling with calibration files?

### Acceptance Criteria:
1. When units change the block is updated to reflect the changes made
2. A wrapper that can be used elsewhere is appropriate (e.g. synoptic)

**Comment by ChrisM-S** [comment]
This is what the user sees currently.

![image](https://user-images.githubusercontent.com/3035405/53027027-09596580-345c-11e9-898f-c9b3f3a405a0.png)

**Comment by Tom-Willemsen** [comment]
The block doesn't notice that the units have changed as PVManager (from cs-studio) doesn't monitor .EGU fields. A restart of the GUI will force it to be picked up - but I agree that this is not ideal and we should find a way to fix it.

**Comment by ChrisM-S** [comment]
Many thanks @Tom-Willemsen I will check with them and then restart the client to fix it and leave this ticket proposed (either for documentation or a fix).

**Comment by davidkeymer** [comment]
Would a switch to another instrument and then back suffice?

**Comment by ChrisM-S** [comment]
Good thought @davidkeymer, I will first try a switch to the same instrument once I can get hold of them again!

**Comment by ChrisM-S** [comment]
OK, switching to the same instrument works and updates the units - seems pretty quick.  It still would have killed the script though (but there was a warning message and there was no script running this time).

**Comment by kjwoodsISIS** [comment]
Here's a suggestion: if the user could refresh the Blocks dashboard would it be sufficient to update the units?  I am thinking of a menu item or button that the user can press to refresh the display.
   * Yes, I know it's not ideal.  It would be much better if the units simply updated automatically.  However, unless there is a straightforward fix to make the units update automatically, an easy-to-use refresh feature might be acceptable.

**Comment by kjwoodsISIS** [comment]
Check if this bug fixed in next version of CS-Studio.

**Comment by aaron-long** [comment]
+1 MARI

**Comment by Tom-Willemsen** [comment]
+1 osiris

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - is this something we could assign to Adam?

**Comment by Tom-Willemsen** [comment]
I suspect this needs either:
- Modifications to CS-Studio code (which we can do, but I suspect is harder than a typical "training" ticket...)
- A general wrapper around PVManager which forces units to update (relatively involved with potentially a lot of threading stuff)

I'm not sure it's entirely appropriate as a training ticket, but maybe could be done as pair-programming with someone more experienced in the GUI code?

**Comment by aaron-long** [comment]
+1 ZOOM

**Comment by DominicOram** [comment]
+1 Electronics (https://github.com/ISISComputingGroup/IBEX/wiki/06-03-2020-Support-Groups-Instrument-Demo)

**Comment by DominicOram** [comment]
I don't think this requires a refresh button or mods to CSS. Can't we just put a monitor on the EGU field and modify the block value text in the view model. An EGU field monitor works fine:
![Updating units](https://user-images.githubusercontent.com/10086797/76241229-8e144e80-622c-11ea-8c4a-2ae34eb792af.gif)

**Comment by John-Holt-Tessella** [comment]
Yes, we probably could, although it is not as neat because the units are now coming from a different pv and would need syncing. Do we get other cases where a refresh button would be nice anyway? Where blocks get stuck/don't refresh as quickly as they should?

**Comment by DominicOram** [comment]
In that view we already monitor:
* Value
* Alarm status
* Description
* Under run control
* In run control range
and we keep them all in sync quite well. A refresh button may help with other bugs but we should try and fix the underlying bug rather than add a workaround...

**Comment by John-Holt-Tessella** [comment]
+1 sandals

**Comment by John-Holt-Tessella** [comment]
Also close #1805 if possible
