### ISSUE TITLE
MAPS: unable to change wiring tables 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4023]
MAPS were unable to change wiring tables - the maps routines.py file was making a call to g.get_current_directory_path_existing() which didn't seem to exist (i assume it did once?). I edited the file to use g.get_current_filepath_existing() and that seemed to fix things

**Comment by kjwoodsISIS** [comment]
Is this issue fixed?  If so, the ticket should not remain open.
