### ISSUE TITLE
IMAT: humidity controller experiment

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4025]
As a user on IMAT I would like to read and log the values from an external user's humidity controller.

**Notes:**
- The humidity controller uses proprietary software written in VB6 - As far as I am aware we can **not** talk to the hardware directly
- This software exposes a DDE interface
- The software also writes files in an excel spreadsheet. If communication via DDE fails, we could try extracting the values from excel

**Comment by FreddieAkeroyd** [comment]
PyDDE did not work, but writing a C++ DDE client seemed to work - now running on IMAT

**Comment by Kevin-Woods-Tessella** [comment]
This program is running on the imat-messina-detect pc, it reads the humidity via DDE and writes it into a user pv  `IN:IMAT:PARS:USER:R0`   If the imat-messina-detect pc reboots the program will need restarting, I have given Genoveva instructions but the procedure is:
-   On messina PC open the directory  `C:\Instrument\Apps\EPICS`  in windows explorer
-   Double click on  `start_rhcontroller.bat`
This will create a new window with the program running inside it, this window can then be minimised

Freddie
