### ISSUE TITLE
OSIRIS: spectra plots not updating

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4026]
Spectra plots currently frozen on OSIRIS, started another client and still not updating.

**Comment by FreddieAkeroyd** [comment]
It seems channel access has stopped working for the spectra i.e. caget no longer works. There were quite a lot of spectra in the PV table when i dumped out diagnostics.

**Comment by FreddieAkeroyd** [comment]
I wonder if this is related to #3979 - OSIRIS have an environment card and maybe these slowdowns cause an issue with spectra channel access.

**Comment by FreddieAkeroyd** [comment]
ISISICP updated to stop pauses in frames, will update spectra graphs to OPIs if happens again

**Comment by John-Holt-Tessella** [comment]
Closing the tickets will open a new one if we see this again.
