### ISSUE TITLE
LET: oscillating collimator failed to restart after ibex restart

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4027]
IBEX was restarted around 7am on 20th February, it appears data collected after that time shows shadowing indicating the collimator was stopped whereas data before was OK.

We need to determine why the collimator stopped and make sure IBEX does not do this

**Comment by DominicOram** [comment]
This also happened on MERLIN (original problem may also have been MERLIN?). Two things should be done about this:
* Create a PV to calculate whether we are actually oscillating based on whether the counts are increasing (Ask MERLIN/LET/GEM if they want this hotfixed and suggest run control on this PV) 
* Have a look at the Galil code and diagnose the issue. In particular it looks like there is a potentially infinite loop in the CHECK1 label. Add some logging or remove this if unnecessary

**Comment by Tom-Willemsen** [comment]
GEM ORC is an entirely different device - this ORC is only used on MERLIN and LET

**Comment by davidkeymer** [comment]
And the original one on WISH (albeit with a different mechanical arrangement - the basis of the software is the same).

**Comment by FreddieAkeroyd** [comment]
I don't know if this could be an issue, but autoonoff is enabled for the collimator. The galil program looks to always turn the motor on anyway though.

**Comment by davidkeymer** [comment]
Could this also be related to the issue of having trouble starting the collimator from the OPI?
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MERLIN-and-LET-Oscillating-radial-collimators for details

**Comment by Tom-Willemsen** [comment]
Brought up again by LET

**Comment by Tom-Willemsen** [comment]
We can test this on LET from now until the end of the shutdown. The scientists are going to be leaving the top off LET, so we are able to look down and see the collimator plate moving if necessary.

**Comment by Tom-Willemsen** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/22
