### ISSUE TITLE
GEM Sample Changer: Gracefully handle dropped sample

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4028]
As a user on GEM I would like my experiment to continue despite finding a dropped sample. The current behaviour is:
* The sample changer will try and pull a sample up out of the beam
* If this fails (most likely because the sample is empty and has been mounted lower than the sample arm can reach) then the sample changer will continue to move out of the beam and rotate one step
* A number 7 error will then occur and the sample changer will not move on

I would like the sample changer to move on anyway. I would also like the move finished LED to be more accurate by telling me that I have made it to the correct position with the arm lowered.

**Comment by DominicOram** [comment]
There is also an issue with the readback being incorrect with:
```
[2019-02-21 13:56:16] Illegal choice PV: IN:GEM:ROTSC_01:MOTOR_0_ACTIVE M

[2019-02-21 13:56:16] 

[2019-02-21 13:56:16] Illegal choice PV: IN:GEM:ROTSC_01:MOTOR_1_ACTIVE  
```

**Comment by DominicOram** [comment]
It looks like the case seen on GEM is not the one mentioned above but is fixed by retrying the position a number of times, which the IOC should do if the move fails.

**Comment by davidkeymer** [comment]
A retry loop is implemented in the Fermi Chopper IOC, according to @Tom-Willemsen .  It may be worth looking at this code for inspiration.

Retries are also used in the Eurotherm IOC, I believe.

**Comment by Tom-Willemsen** [comment]
This would be worth testing on the real hardware out of cycle, if possible.

PRs:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/168
- https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/pull/3
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/26
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/365
