### ISSUE TITLE
JASCO: Remove control race condition

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4029]
As a user of the JASCO pump I don't want to be able to set both the Time and Volume control setpoints "at the same time"

**Acceptance Criteria**
1. There is no opportunity for a race condition

**Notes**
1. This was found when looking at the VI for use in SECI
1. This is not an issue in the use of the OPI as people aren't quick enough to hit
1. This could be a problem in scripting, although the scenario is unlikely
1. As there are two separate, forward linked PVs relating to the two types of setpoint it is possible to hit a race condition if commands are sent quickly/out of sequence
1. Each setpoint updates the other, which is quick enough using the OPI, but when interacting with the PVs (caLab interface, scripting) there is no limiting factor and as such contradictory commands can be sent quite quickly - which can lead to confusion
1. Suggested solution, which adds complexity: specify which item has control and ignore sets from the other

**Comment by aaron-long** [comment]
Another solution is to remove the auto-calculations on setting a time/volume/flowrate and and a pump state for volume, giving `PUMP:STOP/START/TIMED/VOLUME:SP`.

**Comment by ThomasLohnert** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-Jsco4180/pull/4
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/189
https://github.com/ISISComputingGroup/ibex_gui/pull/891

Created a separate ticket for reflecting changes on the SECI side:
https://github.com/ISISComputingGroup/IBEX/issues/4361
