### ISSUE TITLE
RIKENFE: scripting support

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4030]
From James:

> I'm trying to set up a script in the "inst" directory on RIKENFE which needs to import routines from a couple of other files (not part of the standard library or other published packages like numpy). A plain "import xyz" fails even if xyz.py is also in the inst directory. What is the search path being used? What is the "best practice" here? The routines being imported do not need to be available to the user in the scripting window.
> A bad work around for now is to paste everything into one huge file :-(

**Comment by DominicOram** [comment]
Sent the following to James:

>In some cases what you are doing will work but there is a known bug where it will not work if you are trying to import something that is alphabetically later than the script you are currently in (https://github.com/ISISComputingGroup/IBEX/issues/3217). E.g. you can run:
>
>from abc import abc
>
>but not
>
>from xyz import abc
>
>The underlying reason for this is that we’re doing something quite unusual to get all the functions within the inst folder into the inst namespace so that users can call inst.my_function() rather than inst.my_file.my_function(). We’re working on a solution to this but it’s hard to do without breaking backwards functionality. In the meantime there are two solutions to your issue:
>
>1. Put the functions you want to call in an alphabetically earlier file
>2. Put the files in a separate folder e.g. config\NDXRIKENFE\Python\general and modify your script to call from general.xyz import abc. This folder will also need to contain a file called __init__.py, which can be empty, for python to see it.
>
>I would say 2 is preferably as it then separates your code up nicely but obviously it’s up to you. Please let me know if this doesn’t fix your problem.

He has said he will give 2 a go and have not heard back since

**Comment by DominicOram** [comment]
Still no reply so marking this as done for now
