### ISSUE TITLE
ITC

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4033]
#Acceptance Criteria

- [ ] As an ITC user I need to be able to switch between auto and manual heater and gas flow modes. Currently this doesn't work from the OPI (but setting the low-level underlying PV works correctly) (on Zoom - may already have been fixed on master?)
- [x] The heater volts setpoint command actually sets the heater power (in %).
- [x] Can we make it more obvious on the OPI if the device is in local control mode (e.g. big red text somewhere obvious)
- [x] Any change in PV names are accompanied by an upgrade step

**Comment by Tom-Willemsen** [comment]
re-request LET

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/894)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/389)
[Upgrade script](https://github.com/ISISComputingGroup/EPICS-upgrade/pull/28)

**Comment by DominicOram** [comment]
All absolutely fine apart from comment on upgrade script
