### ISSUE TITLE
NDAEXTWEB: Move away from windows server 2008

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4036]
We should move NDAEXTWEB off of a OS that is going to become depreciated. We should take this as an opportunity to remove the things that it's hosting that are no longer used e.g. WAP.

Acceptance criteria:
- Find out what services are running on this machine that are actually required and who is responsile for each service
- Define a plan for how we intend to migrate the machine and each of the services above
- Decide whether we are going to upgrade in-place or whether to build a new machine
- Comission new machine. This only means that windows is up, not to migrate over services
- Create ticket[s] to install and test all services listed above onto the new machine

Notes:
- We can't actually turn this on as a live machine until shutdown

**Comment by FreddieAkeroyd** [comment]
There is now a Windows Server 2019 VM on the cluster NDAEXTWEB3 - we need to migrate required content off NDAEXTWEB1 Given the MCR messages are also on this server, we will need to talk to ISIS Bus Apps too

**Comment by Tom-Willemsen** [comment]
List all the services we currently run on it.

**Comment by DominicOram** [comment]
@FreddieAkeroyd is looking into migrating the sites. I will document and tidy up afterwards.

**Comment by FreddieAkeroyd** [comment]
I have migrated SECI and MCR news and it looks to be working, @DominicOram has installed json bourne as that is looking OK too. I have requested DNS changes so hopefully new server will go live tomorrow

**Comment by DominicOram** [comment]
JSON Bourne has a bit to go. Issues still to resolve:
[ ] Can't get the instrument list from `NDAEXTWEB` - likely DMZ issue (we could hard code the instrument list to fix temporarily if required)
[ ] Can't get instrument ports 8008, 4812, 4813 from `NDAEXTWEB` - likely DMZ issue (These are required)
[ ] Need to add JSON bourne as a service
[ ] Need to clean up the python installation as it has some unnecessary modules

@FreddieAkeroyd is continuing  to discuss DMZ issues with FIT

**Comment by FreddieAkeroyd** [comment]
8008 and channel access are working, 4812 and 4813 don't seem to be available yet

**Comment by JamesKingWork** [comment]
> 
> 
> List all the services we currently run on it.

Has this been done anywhere?

**Comment by DominicOram** [comment]
> > List all the services we currently run on it.
> 
> Has this been done anywhere?

No, it hasn't good spot. Put it into rework and I will do this when I have time.

**Comment by JamesKingWork** [comment]
Also were tickets created to install and test services? Or were they simply done as part of this ticket?

**Comment by DominicOram** [comment]
> Also were tickets created to install and test services? Or were they simply done as part of this ticket?

They were done as part of this ticket.

**Comment by DominicOram** [comment]
> > List all the services we currently run on it.
> 
> Has this been done anywhere?

Documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Webserver
