### ISSUE TITLE
LOQ: Coherent OBIS laser remote

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4038]
As a LOQ instrument scientist I want to be able to control a laser using a Coherent OBIS laser remote. This device has an RS-232 interface. There is a manual for it in the manuals share under LSI Correlator. Table C-8 on page 305 lists the available commands

## Acceptance criteria
- [ ] The laser can be turned on and off
- [ ] The status of the laser (on/off) is presented to the user
- [ ] The status of the laser interlock is presented to the user
- [ ] The fault condition is presented to the user
- [ ] The laser ready status is presented to the user

**Comment by davidkeymer** [comment]
It is not possible to turn the laser on and off remotely using this device as there is no command.  The instrument scientist is aware and accepting of this behaviour.

**Comment by davidkeymer** [comment]
### Pull requests: ###

EPICS top level: https://github.com/ISISComputingGroup/EPICS/pull/169
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/385
Support: https://github.com/ISISComputingGroup/EPICS-Chtobisr/pull/1
Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/36
IOC Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/187
GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/888

Sufficient testing with the hardware has taken place in the presence of the instrument scientists.  The device in question is still connected should the reviewer wish to test further.  However, please ask for details.
