### ISSUE TITLE
IBEX device generator: check logic and error handling 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4041]
There have been two cases recently where files have been generated incorrectly and ended up in the top EPICS git repository rather than a submodule. In one instance there was a local error during the running of the script, but it continued to run makeBaseApp. No further details on the other case.

* make sure makeBaseApp etc is not called unless the submodule is properly added i.e. there is a .git file (but not a .git directory) in the support directory
* check user prompts and procedure is correct, and it stops on errors

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/11

**Comment by John-Holt-Tessella** [comment]
Freddie says: Code looks fine but need to test it.

**Comment by Alistair-McGann-Tessella** [comment]
I've tested it, the behaviour is now as expected in the ticket
