### ISSUE TITLE
Reflectometry: Revert Motor Settings after Beamline move

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4045]
Currently, moving a beamline via reflectometry IOC changes the speeds for all affected axes such that they finish at the same time. However, after the move, they do not revert back to their original setting. This means that if a user is trying to move a motor directly after a move via reflectometry IOC, the motor may move at a much slower speed than they are normally configured to.

Acceptance criteria

1. A synchronised move is made after the move is complete motor velocities returned to the original value (not maximum but value it was before starting)
1. A synchronised move is started, all motor told to stop motor velocities returned to the original value
1. A synchronised move is started, a second synchronised move is made after the move finished the velocity all motors returned to the original value (move any synchronised move)
1. A synchronised move is started, then a user changes the velocity, after the move is finished velocity is not changed back to original value but remains as the user typed it.

**Comment by ThomasLohnert** [comment]
Work is done save for some minor tweaks that should be done once changes from https://github.com/ISISComputingGroup/IBEX/issues/3542 are merged. Putting this in impeded until the other ticket is through review.

**Comment by kjwoodsISIS** [comment]
@ThomasLohnert - can we get #3542 through review promptly.  We should try to avoid tickets waiting for reviews holding up other tickets - it just creates a "log jam".

**Comment by ThomasLohnert** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/203
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/192
