### ISSUE TITLE
Reflectometry: Investigate IOC crash when moving after aborted move

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4046]
As a reflectometry scientist, I would like to be able to move my beamline after a move has been aborted without the reflectometry IOC crashing. Find out why this happens.

**Comment by ThomasLohnert** [comment]
Also happens when issuing a move while a move is ongoing. Stacktrace:
![untitled](https://user-images.githubusercontent.com/18398579/53638036-d9a91b00-3c1c-11e9-85cb-45bfcfab3920.png)

**Comment by ThomasLohnert** [comment]
Needed for CRISP blind test end of March.

**Comment by ThomasLohnert** [comment]
PR that should improve robustness: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/193

This will also require testing on CRISP to confirm this is fully fixed.

**Comment by DominicOram** [comment]
I'll take over review of this as it's urgent
