### ISSUE TITLE
Reflectometry: Convert procedures

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4047]
As a reflectometry scientist, I need to have equivalents in IBEX to the OpenGENIE procedures that are routinely used and present the minimum requirement for performing simple neutron reflection experiments. 

The procedures in question can be found in the experiment controls share.

**Comment by John-Holt-Tessella** [comment]
Do surf 's script as well if possible.

**Comment by ThomasLohnert** [comment]
Meeting with instrument scientists on Thursday to discuss these routines

**Comment by John-Holt-Tessella** [comment]
Was not possible to do surf as well. Tried to create all the items needed for CRISP

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/19

The directory contains an example script techniques/reflectometry/typical_solid.py

**Comment by kjwoodsISIS** [comment]
This ticket was marked as urgent on 5th March.  Why has it not been completed by now?

**Comment by ThomasLohnert** [comment]
I marked it as urgent as it was needed for the CRISP test experiment. John got the scripts working well enough to run it but we ran out of time to do the full in-depth review and rework etc. There are still improvements to be made but it is not as urgent.

**Comment by kjwoodsISIS** [comment]
Return to Backlog (Sprint Planning 25-04-2019 decision).
Re-consider with all reflectometry tickets

**Comment by ThomasLohnert** [comment]
Things to be fixed:

> - The help in contrast change needs to define the concentration as an array with 4 values in, with example.
> - The title in the run scripts include HGaps but it uses the set version not values so that if you don't set them the title becomes `[None None None None]`
> - The documentation of procedures contrast change does not contain units for flow
> - Have used `set period` not `change period number` in various places. run angle and transmission should use a single period (and set this up before starting)
> - Title of the experiment in runangle and transmission should contain all svgs and hvgs

**Comment by John-Holt-Tessella** [comment]
Not all changes are the same as surf but should do the same thing

**Comment by kjwoodsISIS** [comment]
Oops...  accidentally closed.

**Comment by ThomasLohnert** [comment]
As discussed, rework is just add examples to `run_angle` and `transmission` doc strings + perhaps an entry in the changelog.
