### ISSUE TITLE
CRISP: Sample environment for Blind Tests

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4048]
Check with CRISP scientists which bits of sample environment are needed for performing a blind test (to evaluate the IBEX reflectometry system).
Find out which bits are already covered.
Create tickets for kit that is not yet supported.

**Comment by ThomasLohnert** [comment]
CRISP just needs an HPLC pump and a K6 Valve. We have told the scientists to make it a Jasco or Knauer 1050 pump as it is already supported. Awaiting confirmation what we can get.

**Comment by kjwoodsISIS** [comment]
@ThomasLohnert - now that we have an experiment running on CRISP, I guess this ticket is no longer impeded.  Right?

**Comment by ThomasLohnert** [comment]
Set up and ran with a Jasco pump. Nothing to be reviewed at this point.
Scientists have identified some bits that need improvement in the Jasco OPI, see https://github.com/ISISComputingGroup/IBEX/issues/4207
