### ISSUE TITLE
Reflectometry: Investigate IOC performance

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4049]
The reflectometry front panel is currently a bit slow to update values (e.g. readback values still ticking down seconds after relevant motors have finished moving). This is likely due to performance issues in the IOC.
Investigate ways to speed the IOC up. 

A good place to start improving this is by reducing the excessive amount of printing currently done by the pcaspy server for every value change on every PV and seeing if that helps.

**Comment by John-Holt-Tessella** [comment]
Is fine on CRISP once we removed the pycaspy logging, which we did for another purpose
