### ISSUE TITLE
database server - excessive CPU?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4050]
Seems to be using quite a bit on OSIRIS.

~20% (1core) sample for 5 minute ~ 15:00 on 27 Feb.

Investigate slow queries log?

Acceptance Criteria:

1) Database is not using CPU or cause is know and ticket is in.

**Comment by Tom-Willemsen** [comment]
We monitor cpu of all python processes via nagios - it warns when it goes cpu-bound on one core. I don't recall seeing any of these for DBSVR recently - and many changes e.g. database / python updates done since. Close for now, reopen/create new issue if it recurs.
