### ISSUE TITLE
HIFI: CRYOMAGNET: PSU: Cabling - PSUs not showing in Device Manager

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4051]
The USB to PSU connections on the HIFI Cryomagnet were found to be failing, and this was raised as a Footprints ticket for the X and Y PSUs (FIT-6819), for details of the solution see the ticket or the PSU COM Ports disappearing information on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Cryogenic-Inc-Systems

Looking into replacing the USB hub in the first instance

**Comment by KathrynBaker** [comment]
Replacement USB has been ordered, once that is available this may be a scheduled task or it may need to be managed as an emergency

**Comment by KathrynBaker** [comment]
New USB hub installed by instrument scientist - no further issues raised.

The best option to review would be to ask the instrument scientist if these are now behaving acceptably.

**Comment by ChrisM-S** [comment]
Is the old one a viable spare? i.e. do they or we need to order another?

**Comment by KathrynBaker** [comment]
The old one isn’t a viable spare – it was faulty, but two were purchased, one as a replacement, one as a spare. If the spare is used we should replace it.
