### ISSUE TITLE
MUONFE: Move to local instrument control server Discussion

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4052]
As a muon scientist I would like the critical South Side muon front end to run on a reliable control system to avoid regular problems related to networks and sharing space on a remote Virtual machine cluster which is not managed like a critical instrument control machine.

Discuss how to do this, Windows 7,Windows 10 or server move:

This ticket consists of three parts:
1) Get the host server running and configured on the new hardware (which is now powered and networked).
2) Create a new VM clone for the Instrument control machine.  This will be a clone of an existing already configured instrument to reduce the risk of creating a new system.
3) Re-install IBEX and re-commission the IBEX system on the new server (with the same settings).

To be done at the same time as #4053

**Comment by Kevin-Woods-Tessella** [comment]
Discussion held: 15/03/2019

We agreed the following:
   * existing MUONFE and RIKENFE control servers will be migrated to a conventional instrument control server (i.e. Windows VM running on top of Windows Server)
      * MUONFE current runs as a VM on the VM cluster
      * RIKENFE current runs as a VM on NDXARGUS
   * copy the existing Win7 images from the MUONFE and RIKENFE to new control servers
   * the machine names will stay unchanged until the migration to Win10 (later)
      * we want to minimise the potential for risk by limiting the number of changes being made
   * the old images will be retained as backup/fallback for one cycle (i.e. to end of Cycle 2019/01).

We agreed the following timetable:
   1. New control servers physically installed by start of April (Monday, 1st April, 2019).
   1. New IBEX release created before mid-April (Friday 12th, April).
   1. New IBEX release installed on new control servers by mid-April (Friday, 19th April).
   1. New IBEX release configured and tested to our satisfaction by late April (Friday, 26th April).
   1. New control servers handed over to muons group by early May (Monday, 6th May, 2019).
      * Muons group to do their own testing ahead of Cycle 2019/01 (starts 4th June 2019).

**Comment by kjwoodsISIS** [comment]
Requires #4155 
Requires #4156  
Requires #4157 
Requires #4158 
Requires #4159

**Comment by kjwoodsISIS** [comment]
Tickets defining work required have been created.  This ticket is now complete.
