### ISSUE TITLE
RIKENFE(NMUONFE): Move to new control server discuss

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4053]
As a muon scientist I would like the critical North Side muon front end to run on a reliable control system to avoid problems related to sharing its virtual host machine with another instrument.  A configuration which has caused problems this cycle.

This ticket consists of three parts:
1) Get the host server running and configured on the new hardware (which can be powered and networked easily).
2) Create a new VM clone for the Instrument control machine.  This will be a clone of an existing already configured instrument to reduce the risk of creating a new system.
3) Re-install IBEX and re-commission the IBEX system on the new server (with the same settings).

Same as #4052 needs discussion.

**Comment by Kevin-Woods-Tessella** [comment]
See comment in #4052 describing discussion.

**Comment by kjwoodsISIS** [comment]
Requires #4155 
Requires #4156  
Requires #4157 
Requires #4158 
Requires #4159

**Comment by kjwoodsISIS** [comment]
Tickets defining work required have been created.  This ticket is now complete.
