### ISSUE TITLE
Wiki:Create a support workflow [Timebox: 1D]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4057]
As a developer providing support for a user I would like an easy workflow to guide me. This should be on the developer's wiki. Existing support information on the wiki may have to be moved/tidied up. The acceptance criteria for this is for someone not used to support successfully work through some old support issues using this.

**Comment by KathrynBaker** [comment]
Does https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Providing-Support cover this?

**Comment by GRyall** [comment]
I would argue it gets  close enough that we can close this ticket.
