### ISSUE TITLE
Changing IOC macro in component did not restart ioc 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4061]
Happened on LET with the triton IOC. The triton is in a component, the component was modified as the name of the triton PC had changed, the usual configuarion change box came up, but the triton IOC was not restarted and continued to communicate with an incorrect hostname. Manually restarting the IOC fixed this.

* Check if this is easily repeatable
* If not, write an automated test and run repeatedly to reproduce
* fix!

**Comment by John-Holt-Tessella** [comment]
Fixed by #4090?
