### ISSUE TITLE
Merlin: Check scripts on load

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4062]
As a MERLIN user, I would like to have some mechanism that checks the validity of commands in a user script on loading the script.

The specific use case they want covered was checking that the argument for chopper frequency is a multiple of 50. There was a case recently where a user had entered the value with a 0 missing due to a typo which lost them several hours of beam time, so it would be good if we could prevent this sort of thing from happening in the future.

**Comment by Tom-Willemsen** [comment]
Recent pyright additions along with python's `typing.Literal` solve this and similar cases.

i.e.

```
type ChopFreq = Literal[0, 50, 100, ...]
def set_chopper(freq: ChopFreq) -> None:
    ...
```

Then in user scripts:
```
set_chopper(0) # ok
set_chopper(49) # static analysis (pyright) error
set_chopper(50) # ok
```

(When we deploy pyright, we should link to python tutorials about how to do this sort of thing so that scientists can insert these relevant checks where they're useful)
