### ISSUE TITLE
ALF: reporting low memory

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4066]
ALF is reporting low memory in nagios, a quick looked showed a large activeMQ process was running in addition to 3 ibex clients. I think it is surviving, but we should contact the scientist next week.

**Comment by John-Holt-Tessella** [comment]
There is nothing we can learn from this.

**Comment by ChrisM-S** [comment]
Was that a question or a statement? :smile:
