### ISSUE TITLE
LET: collimator not responding

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4067]
This was due to the galil controller not having power, which was due to the UPS having failed. The UPS also controls MOXA_LET_BEAMLINE which is in the same cabinet.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - how will this ticket be progressed?

**Comment by John-Holt-Tessella** [comment]
UPS should be monitored see #4175
