### ISSUE TITLE
TOSCA: Cannot run sample changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4068]
As an instrument scientist on TOSCA I would like the sample changer to work correctly in IBEX as it does in SECI. I have seen the following behaviour:

* Moving multiple steps when it should move one
* Occasional moves cause the device to go in the wrong direction
* Changing the number of steps for a small/large move is not correctly updating

I would like to meet to discuss these issues further.

**Comment by DominicOram** [comment]
Meeting set for 16/04

**Comment by FreddieAkeroyd** [comment]
It looks like is was not used in the cycle before Christmas, so this may have been the first use

**Comment by DominicOram** [comment]
This will not be used until after the summer shutdown

**Comment by DominicOram** [comment]
/remind me we need to look at this again in July

**Comment by kjwoodsISIS** [comment]
Proposed for SPRINT_2019_07_18, so that it can be considered for the shutdown after Cycle 2019/01 is complete.

**Comment by kjwoodsISIS** [comment]
Discuss with Instrument Scientists.  Get a definitive answer on what they wish to do.

**Comment by Tom-Willemsen** [comment]
Contact Stewart p. to organise this

**Comment by kjwoodsISIS** [comment]
08/08/2019: E-mailed TOSCA scientists to ask what they want to do about the sample changer.

**Comment by John-Holt-Tessella** [comment]
Rory says of initial commissioning:

>I configured the TOSCA sample changer motor as best I could when I migrated TOSCA. They did not test that it worked at the time but I translated the SECI details and David checked over it with me.

**Comment by ThomasLohnert** [comment]
Fixed with https://github.com/ISISComputingGroup/IBEX/issues/6101.
