### ISSUE TITLE
LARMOR: ibex not waiting for correct microamps values

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4069]
A sequence of runs numbered 39207 - 39219 were done on larmor around midnight 3/4 march. Each run was scripted with a waitfor microamps of 0.15 which should take about 15 seconds.   Runs 39207-39213 were OK, run 39214 tool 1 minute 19 seconds and recorded 0.86 microamps and subsequent runs were taking about double the time and recording double the requested microamps.

**Comment by FreddieAkeroyd** [comment]
Run 39214 2019-03-03 23:41:24 start 23:42:43 end

In the genie python log i see details for begin/waitfor/end for a run at 23:30 but not for this one?

pulog has begin and end details, nothing strange in icp log.

**Comment by FreddieAkeroyd** [comment]
After 23:30 on 3rd there is no logged BEGIN in genie python until 21:45 on 4th and a lot of runs were done inbetween these times

**Comment by Tom-Willemsen** [comment]
Highly unlikely to be actionable 5+ years later - many ICP, ISISDAE, genie_python, instrument script updates done in the intervening years.
