### ISSUE TITLE
Reflectometry: Investigate scan fitting capabilities

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4075]
As a reflectometry scientist, I need to be able to perform
- A Gaussian Fit
- An Error Fit (in both directions)
on my scan results so that I can read a value for the centre of mass.

Investigate whether the scans library covers these cases adequately and discuss with the scans developer / fix if not.

This is needed for the CRISP blind test end of March.

**Comment by ThomasLohnert** [comment]
Errorfit seemed to be working fine. Gaussian had some issues, but should now be resolved with these changes: https://github.com/ISISNeutronMuon/InstrumentScripts/pull/18

To test:
1. Install the scans library (https://github.com/ISISNeutronMuon/InstrumentScripts)
2. Get scan data from the Experiment Controls Share
3. Load it in as a scan object using this code:
```
from scans.general.scans.scans import ReplayScan

class ScanValue(object):
    def __init__(self, y, e):
        self.y = y
        self.e = e

    def __float__(self):
        return float(self.y)

    def __repr__(self):
        return str(self.y)

    def err(self):
        return float(self.e)

def read_scan(path):
    with open(path) as f:
        xs = []
        ys = []
        lines = f.readlines()
        for line in lines:
            x, y, e = line.split()
            xs.append(float(x))
            ys.append(ScanValue(y, e))
        return xs, ys


xs, ys = read_file(<path to file>)
some_scan = ReplayScan(xs, ys, "axis name")
```
4. Finally, perform fits on the scan with:
```
from scans.general.scans.fit import Gaussian, Erf

gaussian_fit = some_scan.fit(Gaussian)
# or
erf_fit = some_scan.fit(Erf)
```
This will create a plot of the data with a fit. `some_scan.fit()` also returns the fitting parameters as a dict. 
I do not have reverse height scans (needed to test the reverse Error Fit, as it is directional), but you should be able to emulate it by just inverting each `x` value read in `read_scan` above.

**Comment by Tom-Willemsen** [comment]
The updated initial guesses for the gaussian fit seem to be working nicely - it seems to fit sensibly even when I intentionally supply it with slightly dodgy data.

Error fit seems to work well with the supplied data.
