### ISSUE TITLE
Muon separator: reconnect from lost network

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4078]
As a muon scientist, I would like the separator IOC to automatically reconnect if the network drops out and then later comes back online. Currently an IOC restart is required to reconnect to the DAQ.

Acceptance criteria:
- [ ] The following workflow works:
  * Connect the IOC to the DAQ unit, check it is reading correctly
  * Unplug the DAQ unit
  * Plug the DAQ unit back in
  * IOC should reconnect and read values successfully without the need for an IOC restart

Notes:
- There is also a ticket ( https://github.com/ISISComputingGroup/IBEX/issues/3850 ) to ensure comms errors are reported correctly. It may be worth doing this at the same time.

**Comment by DominicOram** [comment]
Fixed in https://github.com/ISISComputingGroup/IBEX/issues/5266 and https://github.com/ISISComputingGroup/IBEX/issues/5752
