### ISSUE TITLE
POLARIS: configure IOC, OPI and component for MK3 chopper

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4079]
POLARIS is due to have its chopper timing system upgraded from a MK2 to a MK3.  Therefore its base component (I assume) will need to be edited to reflect this change.
This work is provisionally due to be handed over to our group on/from 18th May 2019.

**Comment by davidkeymer** [comment]
New dates for this work: 20th - 25th May, unless the system is available sooner (or probably later!) than that.

**Comment by davidkeymer** [comment]
The upgrade is going well and is currently on schedule, if not a little ahead.  The above dates are still valid.

**Comment by davidkeymer** [comment]
I've just heard that the upgrade is complete and so the IOC configuration can now go ahead.

**Comment by Tom-Willemsen** [comment]
Swapped configs/synoptics over to using MK3 on Polaris.
