### ISSUE TITLE
ISISDAE: change mechanism for sending sample parameters

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4083]
This currently goes through a queue using completion callbacks, this means it is very generic but also maybe more complicated than needed. As adding arbitrary sample/beamline parameters is not probably needed, this could be changed to more static PVs   

might avoid #4082

**Comment by FreddieAkeroyd** [comment]
The purpose of this ticket is to remove a sequencer PV library dependency and also move the samaple/beamline parameter PVs from INSTETC to ISISDAE. The result of the move from the outside should be no visible change from before. 

To test:

make sure setting values in experiment details works. The only way to be sure they have gone through correctly would be to end a run and look into the data file using HDF view to check they were there.

**Comment by FreddieAkeroyd** [comment]
Title should be in 	/raw_data_1/title
	
/raw_data_1/instrument/moderator/distance    should be negative of primary flight path (L1) beamline parameters

sample height, width, thickness should appear in

	/raw_data_1/sample/height
	/raw_data_1/sample/width
	/raw_data_1/sample/thickness

**Comment by kjwoodsISIS** [comment]
Complete #4279 with this ticket.

**Comment by FreddieAkeroyd** [comment]
Tests now added in #4279
