### ISSUE TITLE
Blockserver: MARI: did not set up block logging settings correctly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4084]
MARI changed configs at 9am to a configuration with different blocks (a CCR instead of a cryostat).

The blockserver did not apply new block settings correctly. This was noticed on the dataweb pages, but also was not logging into the data file.

Blockserver log is in the shares under `Ticket4084`

- Restarting `ARBLOCK` did not help
- `g.reload_current_config()` did not help
- Restarting the blockserver fixed the issue (at 14:46 in the log file)

**Comment by FreddieAkeroyd** [comment]
Is this the same as #3884? It looks to be missing "Generating archiver configuration file:" lines too after a gateway restart

**Comment by Tom-Willemsen** [comment]
Yes. I will close this ticket.
