### ISSUE TITLE
RIKENFE: read individual interlocks

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4091]
As an instrument scientist on RIKENFE, I would like individual interlocks statuses to be available as well as the overall interlock status.

The "expected" protocol is in the documentation share, however some power supplies may not follow this standard, so all interlocks on all of the power supplies will likely need to be checked as part of this ticket.

**Comment by Tom-Willemsen** [comment]
As part of this ticket:
- Also add a reset button (needs testing with actual hardware - the command in the manual is not the correct one)
- Check that we display individual interlock statuses for other models of danfysik

**Comment by KathrynBaker** [comment]
If possible, as we distinguish between the RIKEN PSUs and other Danfysiks due to the comms setup, the users won’t – so please do keep in mind that this and the standard DFKPS should be kept at least somewhat in step from the point of view of user interface.

**Comment by KathrynBaker** [comment]
For reference the command to reset interlocks is `RS`

**Comment by KathrynBaker** [comment]
One extra requirement (hence the re-requested mark - same instrument, different scientist)
* the interlock status should be shown as "Tripped" vs. "OK". Saying "True" or "Yes" or an indicator LED being lit is ambiguous

**Comment by KathrynBaker** [comment]
We shall assume that the interlocks are in order as per the manual, if they are found to be different that will be a new ticket raised when found to be incorrect

**Comment by Alistair-McGann-Tessella** [comment]
PRs:
[IOC (db files)](https://github.com/ISISComputingGroup/EPICS-ioc/pull/373)
[Support module](https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/10)
[IOC test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/176)
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/878)
[Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/29)
