### ISSUE TITLE
beamlogger: details not updating

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4097]
Blocks for facility PVs, such as the beam current, were showing as disconnected on HRPD and POLARIS and probably others. The PVs were visible via caget in R3, so it looked like a gateway issue. Restarting gateways  on control-svcs fixed this

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - how will this ticket be progressed?
