### ISSUE TITLE
LET: set_ei not reliable

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4101]
As an instrument scientist on LET I need `set_ei` to work reliably. Email from LET scientist states:

> ... On IBEX when you run this command its sets all the correct values in the set boxes in the synoptic but the problem is that the choppers often seem to ignore some of the values. I usually then have to go through and press return several times in all the set boxes before the choppers react. I never had this problem on SECI. It does mean that we cannot script overnight at the moment with any changes in energy as I cannot trust that the choppers will obey.

We need to find out which choppers it is (if it is just one type or whether all of the choppers are unreliable)

**Comment by DominicOram** [comment]
> It does mean that we cannot script overnight at the moment with any changes in energy

Seems like a big deal, is it worth trying to hotfix?

**Comment by Tom-Willemsen** [comment]
yes

**Comment by DominicOram** [comment]
Possibly do #4103 as part of this if we need to modify the choppers

**Comment by Tom-Willemsen** [comment]
Discussed this with LET scientists. We think it is a timing condition of some sort in the communications. I suggested putting some sleeps into their `set_ei` script as a stop-gap measure until we can sort the communications with the chopper correctly in the driver.

**Comment by kjwoodsISIS** [comment]
#4123 may actually fix this issue too.  Check first.

**Comment by Tom-Willemsen** [comment]
We have been given permission to test things on LET from now until the end of the shutdown. Don't run chopper 5 at more than 10Hz if the small blockhouse is unlocked, otherwise we are free to test whatever we need.

**Comment by Tom-Willemsen** [comment]
This appears to be fixed by #4123 and the changes that the scientists made to their scripts.

I will confirm with the scientists whether there are any other tests worth doing to ensure the choppers are now fully behaving themselves.

**Comment by DominicOram** [comment]
I ran `inst.set_ei5(ei=5, freq1=10, freq2=20, slot="HF", dum="exe")` on the instrument after #4123. Worked as expected so closing this ticket. Might be worth emailing the instrument scientist telling them that they're can likely take out the waits if they want? I'll leave that to @Tom-Willemsen has he spoke to them about it previously and should get the credit for fixing it...
