### ISSUE TITLE
Triton: behaviour on switching to/from closed loop mode

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4103]
As an LET instrument scientist I want the Triton system to behave correctly in closed loop mode.

From LET scientist:

> The user wanted to warm the dilution to 0.3k so we put the value in the set temperature box and nothing happened. I found out that you then have to press a button for closed loop on. Again this should be automatic and the user should not have to see this as it was on SECI. You just want to give the temperature and that’s it.  After turning closed loop on nothing happened still. It then turns out we have to tell it where to get a PID file in another tab. I did this and it finally started working. I then changed something in the blocks and found I could not change temperature again. It turns out it had now turned the closed loop off and lost the PID file so I had to go and put it all in again. It seems its like with the collimator that when you do anything in the blocks it forgets everything and you have to restart it all.

We should clarify exactly what the oxford triton software does when set to closed loop mode - I think it may reset the setpoint to the current temperature, but this needs testing.

Also test that the PID file is preserved on IOC restart - this applies to all the drivers that use ReadASCII (e.g. would also apply to Eurotherm)

**Comment by John-Holt-Tessella** [comment]
We need to decide whether the PID file and closed loop should be autosaved or a setting in the macros I do not know which make sense here.

**Comment by Tom-Willemsen** [comment]
On checking the labview driver, it ALWAYS sets closed loop mode on when any temperature is set. The IOC should also do this.

**Comment by Tom-Willemsen** [comment]
To do as part of this ticket:
- [ ] Set PID file from configuration (make it a macro)
- [ ] Set whether the driver should use the PID file from the config (could either make it a separate macro, or do a `stringiftest`-style check on whether the calibration file name is non-empty)
- [ ] Set closed loop mode to ON on when any temperature is set

These changes would be good to get in in time for an experiment on LET 22/3/2019

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-Triton/pull/3
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/366
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/169

**Comment by Tom-Willemsen** [comment]
Switching PID files from config: worked ok on actual hardware on LET

Turning closed loop mode on whenever temperature is set: on real triton fridge on LET, turning closed loop on/off makes the fridge reset it's temperature setpoint to the current temperature. This caused very odd behaviour with the changeset above, so I removed it again. I think it would be best to meet with cryogenics to talk about this and find what approach would work best.

**Comment by Tom-Willemsen** [comment]
Discussed this with cryogenics, there are several additional subtle issues:
- While closed loop mode is on, the diagnostics from the fridge are severely limited. This is why cryogenics do not want to run tritons in closed loop mode all the time.
- With closed loop off, a setpoint can be sent to the fridge, but it doesn't do anything. This is confusing for the scientists.
- Setting closed loop mode to ON immediately after setting a temperature setpoint doesn't work correctly because the triton system changes TSet to match the current temperature on entering closed loop mode
- Setting closed loop mode to ON immediately before setting a temperature setpoint, which is what the labview does, may be acceptable but needs further testing as cryogenics believe this may have contributed to a fault on WISH.

Cryogenics will be running a fridge down to low temperature over shutdown, and they will give us an opportunity to test on the real hardware and work with them to try and find the "least bad" solution to this issue. We will then need to apply this solution to both LabVIEW and IBEX drivers.

**Comment by kjwoodsISIS** [comment]
When all these issues have been investigated and resolved, we must ensure to explain the behaviour of the Triton systems to the scientists, so that they understand what is and is not possible.

**Comment by Tom-Willemsen** [comment]
Triton fridge NDRI1 will be available for us to test with Tomorrow (17/4/2019).

**Comment by Tom-Willemsen** [comment]
Tested on a real Triton (NDRI1) with help from cryogenics, a sequence that seems to work ok is:
- Send temperature setpoint
- Wait 500ms
- Set closed loop mode on
- Wait 500ms
- Send temperature setpoint again
