### ISSUE TITLE
HOTFIX: Apply block issue hotfix

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4107]
Apply the following files to `...EPICS\ISIS\inst_server\master`

1. https://github.com/ISISComputingGroup/EPICS-inst_servers/blob/b6164af758080616c99b518de505b19a6f51e1d7/BlockServer/core/active_config_holder.py
2. https://github.com/ISISComputingGroup/EPICS-inst_servers/blob/b6164af758080616c99b518de505b19a6f51e1d7/BlockServer/core/config_holder.py
3. https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/192/files#diff-36a4744d077e23a14d65c663c42f5f89

**Comment by kjwoodsISIS** [comment]
How many points?
