### ISSUE TITLE
MUSR: Data not appearing in TopCAT

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4109]
MUSR called as their data had stopped appearing in TopCAT. Forwarded the query to the people who manage the service. (It had fallen over and needed to be restarted)

**Comment by kjwoodsISIS** [comment]
This does not seem like an IBEX issue?  Would it not be better to record it in the ControlsWork repository?

**Comment by ThomasLohnert** [comment]
Yes, I was not sure about adding this as a ticket but we recently discussed that creating support tickets is useful for building an archive to track which sort of requests come up / how frequently they come up and my feeling was that it's not a good idea to scatter this across several places. 
Perhaps we should have a separate "archive" solution and keep Github issues for tracking IBEX effort? I will add a note to discuss this in retrospective.
