### ISSUE TITLE
IMAT: Re-Enable T0 Chopper in IOC

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4111]
The T0 chopper on IMAT is being re-installed and therefore the software needs configuring.  I believe that all that is required is to uncomment the address macro defined in `globals.txt` and the SKF G5 IOC restarted - the OPI will pick up that the PVs for the T0 controller are available and enable the appropriate tab.

Some background from Rebecca:

> The IMAT T0 was previously in the beamline a few years ago, and I believe that it was commissioned then. There were some issues with the bearings which resulted in the chopper being taken out and different bearing combinations tested. We’ve now finished the testing and found … that we’re going to go back to having standard steel greased bearings; the chopper will sit in a vacuum enclosure but have windows on it to isolate it from the rest of the beamline. 

> The same firmware and software will be used as previously, so we are hopeful that little to no setup will be required in relation to getting the T0 back onto the software system. However, as it’s been a few years … we’re not sure!

**Comment by davidkeymer** [comment]
This project is running a little behind schedule due to vacuum issues.  However, it is still envisaged that it will be complete by the end of the shutdown.

**Comment by davidkeymer** [comment]
I've just been informed that the ongoing hardware problems do not affect the controller or remote interface, so this ticket can still be done when we'd planned.  I will be contacted by someone from the chopper group during the week commencing 20th May to make arrangements for confirguration and testing time on the instrument.

**Comment by Tom-Willemsen** [comment]
This has been done on IMAT.

There was a change requested to treat the T0 in the same way as other choppers. This change is in the PR below and is already patched on IMAT. I went down with Tim Carter and we tested that the change works appropriately on the real hardware.

https://github.com/ISISComputingGroup/ibex_gui/pull/892
