### ISSUE TITLE
NIMROD: Candlestick

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4114]
As a scientist, I want to control the position of the "candlestick" device, so that I can measure temperatures (using the attached probes) during my experiments.

#### Acceptance Criteria
1. I can view the temperature readouts on the UI.
1. I can obtain the temperature readouts via a genie_python script.
1. I can position the "candlestick" device at any point along its axis.

#### Notes
1. The "candlestick" device holds 3 temperature probes, connected to Eurotherm controllers.
1. The "candlestick" device can be moved on a single, horizontal axis (Galil controlled).
1. Need to check with the scientists about what type of UI they want.  For example, should the UI simply control the movement of the "candlestick" (leaving the temperatures to be read from the Eurotherm UI)?  Or would they like temperature & position all on a single UI?
1. See also the [NIMROD wiki](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) page.

**Comment by davidkeymer** [comment]
This device may not exist.  Awaiting confirmation from second instrument scientist.

**Comment by davidkeymer** [comment]
Nobody questioned has any knowledge of this device.  I've therefore removed it from the table of equipment on the [instrument details page](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) to avoid further confusion.
Labelling ticket with `won't fix` and closing.
