### ISSUE TITLE
NIMROD: IOC & OPI for Oerlikon Centre-One Pressure Gauge

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4115]
As a scientist, I want to use an Oerlikon Centre-One pressure gauge, so that I can measure pressure during my experiments.

#### Acceptance Criteria
1. The solution must provide equivalent functionality to the existing SECI VI.
1. I can view the pressure from the UI.
1. I can obtain the pressure via a genie_python script.

#### Notes
1. The existing SECI VI is located here: `C:\LabVIEW Modules\Drivers\Oerlikon Centre One`.
1. See also the [NIMROD wiki](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) page.

**Comment by KathrynBaker** [comment]
COM settings are a single port, 9600,8,None,1, Line Feed as termination character, No flow control.

Guages are read by sending `PR1<CR><LF>`, waiting 100ms, then sending `05` in Hex and reading back the response in the format `%d,%f` into a status and Gauge value respectively. The gauge value is then displayed and plotted on a graph.

Extremely simple

**Comment by DominicOram** [comment]
After discussion with cryogenics and the NIMROD instrument scientists it sounds like this guage may no longer be used. They are going to investigate further but we should hold off on doing this in the mean time.

**Comment by kjwoodsISIS** [comment]
@DominicOram - did you hear back about this device?

**Comment by DominicOram** [comment]
@kjwoodsISIS - No news, I can chase again.

**Comment by Kevin-Woods-Tessella** [comment]
I check with Tris.  They do use the Oerlikon device, so we need to support it.

**Comment by JamesKingWork** [comment]
To review:
* https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/226
* https://github.com/ISISComputingGroup/EPICS/pull/181
* https://github.com/ISISComputingGroup/ibex_gui/pull/950
* https://github.com/ISISComputingGroup/EPICS-Oercone/pull/1
* https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/48
* https://github.com/ISISComputingGroup/EPICS-ioc/pull/418
* https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OERCONE

Note:
The IOC still needs to be tested against the hardware
