### ISSUE TITLE
ProcServControl - asking an IOC to stop twice quickly causes it to restart

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4116]
As a developer, I want IOCs to stop if I ask procserv to stop them. Currently if I ask procserv to stop the same IOC multiple times in a row (in quick succession) it causes the IOC to restart.

e.g. With `AMINT2L_01` running, run the following commands:

```
caput TE:NDW1799:CS:PS:AMINT2L_01:STOP 1  && caput TE:NDW1799:CS:PS:AMINT2L_01:STOP 1 && caput TE:NDW1799:CS:PS:AMINT2L_01:STOP 1 && caput TE:NDW1799:CS:PS:AMINT2L_01:STOP 1 && caput TE:NDW1799:CS:PS:AMINT2L_01:STOP 1
```

This will (at least sometimes) cause the IOC to restart rather than stop.

**Comment by Alistair-McGann-Tessella** [comment]
Can you please add tests for this functionality? There is a class in the IOC test framework which launches IOCs through procserv (in `utils/ioc_launcher.py`) which will probably be useful for this.

**Comment by FreddieAkeroyd** [comment]
Ok will add a test, however utils/ioc_launcher.py will not be applicable here as we need to launch the IOC through procServControl and not directly through procServ

**Comment by John-Holt-Tessella** [comment]
I will add the test now :-)

**Comment by John-Holt-Tessella** [comment]
Pull requests:

- https://github.com/ISISComputingGroup/system_tests/pull/14
- https://github.com/ISISComputingGroup/EPICS-procServControl/pull/2
