### ISSUE TITLE
RIKENFE: PSU communication breakdown

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4118]
When the network came back on RIKEN after a recent outage, the PSU IOC still failed to communicate with the ports for chain 1 and 3 until the IOC had been restarted. 

As a RIKENFE scientist, I want communications to the power supplies to come back after a connection breakdown without the need for manual intervention - investigate where it went wrong.

**Comment by DominicOram** [comment]
Closed as it's unclear how to action this
