### ISSUE TITLE
LET: astrium chopper setpoint readback can be wrong

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4123]
As an instrument scientist on LET, I have noticed that disks on astrium choppers can sometimes claim that they are phasing to one value, but actually phase to a different value.

The workflow is:
- Set phases on both disks of an astrium chopper simultaneously (or very close to each other in time)
- The setpoint readback (from the device) will be correct for both choppers
- When looking in the astrium software, the correct setpoints have been received for both choppers
- Both disks will then home in and phase onto the first disk's phase setpoint

Notes:
- This does not happen if setting phases manually - I think it is some form of timing condition in the astrium software
- We may be able to avoid this issue by forcing the comms layer to wait between each message it sends
- We have had similar issues with julich fermi choppers, which implement an aggressive retry strategy to try to mitigate the problem
- Resending the setpoints again slowly causes the chopper to pick up the correct settings.

**Comment by Tom-Willemsen** [comment]
We have been given permission to test things on LET from now until the end of the shutdown. Don't run chopper 5 at more than 10Hz if the small blockhouse is unlocked, otherwise we are free to test whatever we need.

David (Voneshen) thinks he has solved the issue from the script by sending speed first, then phase (as opposed to phase and then speed). We should verify that this is a fix, and then implement it in the driver (as opposed to the scripts).

**Comment by Tom-Willemsen** [comment]
I have reproduced this issue on LET using this command:

```
g.cset("Chopper1_Disk1_phase", 11);g.cset("Chopper1_Disk2_phase", 22);g.cset("Chopper1_Disk1_speed", 10);g.cset("Chopper1_Disk2_speed", 10)
```

Both disks phased to 22 degrees, even though the phase setpoint (and the phase setpoint readback) of disk 1 were correctly set to 11 degrees.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/379
- https://github.com/ISISComputingGroup/EPICS-AstriumChopper/pull/1
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/181

**Comment by aaron-long** [comment]
In testing on LET it was found that there was still some sensitivity in the timings. It was agreed that the wait commands would be increased to 1 s (from 0.1). After testing this the bug seems to have been fixed.
