### ISSUE TITLE
Test: Ensure that resume button is enabled when in paused mode

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4128]
As a developer and ZOOM instrument scientist, I want to be sure that the resume button not being highlighted on ZOOM was a one-off error. Create a squish test to prove this, it should pause and resume the dae multiple times.

The error was: with dae paused the resume button was not enabled. Could be resumed from a script.

**Comment by DominicOram** [comment]
I added some DAE squish tests as part of #3591. I think they might cover this case, if not they addition is minimal.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by kjwoodsISIS** [comment]
Return to Backlog (Sprint Planning 25-04-2019 decision).
Issue is believed fixed.  test can be created when have the capacity to do it.

**Comment by DominicOram** [comment]
@kjwoodsISIS The test is created, only minor rework is required, have we decided not to do this rework?

**Comment by kjwoodsISIS** [comment]
@DominicOram - yes, we still want to do this.  We just don't have the capacity to do in the current sprint.  We can bring it back when we have completed everything that is necessary for the mid-May release.  I will set a reminder to bring it back in after the mid-May release is deployed.

**Comment by Tom-Willemsen** [comment]
@DominicOram I am still unable to get these tests to pass. When you're available, maybe we should sit down and look at them together?

**Comment by DominicOram** [comment]
Should now work, sorry @Tom-Willemsen
