### ISSUE TITLE
CAEN: Summary OPI: keep power control buttons within summary box

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4130]
As an IBEX user I don't want random buttons appearing outside of my summary display as per the pictures below.

**Acceptance Criteria**
1. There are no random buttons in odd places

**Notes**
1. This was noticed on a dev system when a large number of channels were added to the screen
1. The simulated CAEN may need to be altered to provide more channels than fit easily into the OPI as it stands

![image](https://user-images.githubusercontent.com/10552381/54376879-e6495c80-467b-11e9-867a-cfbcbbb0d980.png)
![image](https://user-images.githubusercontent.com/10552381/54376897-f2cdb500-467b-11e9-9dae-845925b11807.png)

**Comment by JamesKingWork** [comment]
+1 from MuSR
