### ISSUE TITLE
Polaris: Mass Flow Experiment

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4132]
As a Polaris instrument scientist I would like to control a mass flow experiment next week which uses 2-4 daisychained CCD100s. 

We need to confirm that we can talk to these daisychained and help with set up.

**Comment by Tom-Willemsen** [comment]
Which day does this experiment start?

**Comment by DominicOram** [comment]
I don't know they've pushed the date but I don't know when to. I'll chase it again.

**Comment by DominicOram** [comment]
Experiment has been moved indefinitely. Closing this ticket.
