### ISSUE TITLE
3506-2: Install script to migrate instruments to MySQL 8

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4135]
As part of https://github.com/ISISComputingGroup/ibex/issues/3506 we have migrated to MySQL 8. There are instructions for how to migrate developer machines here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Upgrading-to-MySQL-8

This ticket is to create an upgrade script to install MySQL 8 on instrument machines. It is likely to be a subset of the steps noted on the wiki page above.

**Acceptance criteria:**
- [ ] Script upgrades an instrument machine from MySQL 5.7 to MySQL 8.0 - e.g. try on DEMO

**Notes:**
- The MySQL (un)installer is tricky to call on a command line. We may need to make the uninstall of 5.7 a manual step.
- Some steps will need to be run as Administrator (e.g. managing services).

**Comment by Tom-Willemsen** [comment]
Note: review once there is a recent `windows7-x64-clean` build available on the share (needs to be more recent than 18/3/2019).

On a test machine (such as demo or ndxtest) you should be able to run `install_latest_build_only.bat` and then `upgrade_mysql.bat` to test this. DEMO already has MySQL 8, the test systems don't.

https://github.com/ISISComputingGroup/ibex_utils/pull/34

**Comment by davidkeymer** [comment]
- Not all machines can see the kits area without specifying the full name. Make the script use the fully qualified name
- MySQL8 depends on visual c++ runtime 140 which is not on windows 7 by default, make the script install this automatically first (it is only ~14MB)

**Comment by Tom-Willemsen** [comment]
The two updates listed above have been made.
