### ISSUE TITLE
GUI/Scripting: config change and block names

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4136]
There was an issue raised on POLARIS, where running a script failed with:
```
UnableToConnectToPVException(name,  'does not exist')
UnableToConnectToPVException: Unable to connect to PV IN:POLARIS:CS:BLOCKSERVER:BLOCKNAMES: does not exist
```
There was a config change and the previous config did not have the blocks in use for this script, but as the scripting window remained open, this required a get_blocks()
Whilst this is a reasonable response, a way to avoid this manual step would be to potentially find a way to trigger the function automatically after a config change, or at least provide a better solution which includes the need to run that function

### Acceptance Criteria:

Decided on no caching.

1) Every block not in upper case has an alias created for it in upper case
1) cset, cshow, cget use the upper case alias to set and get the pv. They no longer query the block server but just use the aliases
1) Config checker tests configs do not contain blocks which are the same except for their case
1) Scans library author is informed of these aliases to make it easier for him
1) The rest of the ticket time has been used to look for and fix the underlying cause of this problem
1) Decision log is updated with reasons behind no caching

### Notes

Documented after the fact but I think this is what was agreed:

1) No caching was decided on in this use case because creating aliases is much easier and relies on only having a single get pv
1) It fixes the size requirements introduced by #4941 i.e. there are no requirements
1) Once these things no longer use the cache this is the only reference we can find so it can be deleted (double check this)
1) Decision was thought about by at least John, Tom, Freddie and Kathryn
1) It is not clear why the original cache was created, it maybe because of the speed of reading multiple values. However the speed seems to be faster after fix on speed for reflectometry by Freddie. Fix #4338

**Comment by FreddieAkeroyd** [comment]
As far as I know, the get_blocks() command just prints a list of blocks (in Open GENIE it did a bit more and updated command arguments). It looks like the IN:POLARIS:CS:BLOCKSERVER:BLOCKNAMES PV did not exist, this is queried by the cset command so it can match the block name passed to the available list and be kind by matching in a case insensitive way. So it looks like the blockserver was either busy or there was some other transient CA error. This should be more robust, on way would be:
* query blockserver for list of names
* if that failes, use cached version from last time you queried it
* if that fails, construct PV name using case as is (which only works if case is correct!)  

We could remove the blockserver interaction in the following way if we wished:
* on config change, blockserver creates aliases for gateway with "as is" and "all uppercase" names
* when writing to PVs, genie python uppercases block name to create PV name to use

**Comment by John-Holt-Tessella** [comment]
This occurred again at that time we saw the following error:

```
2019-04-01T09:19:31	(CMD)	(5616)	cset {'args': ('UQ12_POWER', 0), 'kwargs': {}}
2019-04-01T09:19:40	(CA)	(5616)	ERROR: CAException: type=-1 state=192 op=5 file=..\cac.cpp lineNo=1223
```

but this may have been coincidental.

**Comment by Tom-Willemsen** [comment]
Also seen on LARMOR, who were running the following command:

```
g.begin();g.waitfor_uamps(25);g.end()
```

**Comment by Tom-Willemsen** [comment]
+1 from MAPS while running `set_ei`

**Comment by KathrynBaker** [comment]
A late +1 that I'd meant to add in from IMAT, seen when setting up the PI rotation stage

**Comment by Tom-Willemsen** [comment]
+1 LOQ
+1 OSIRIS

**Comment by FreddieAkeroyd** [comment]
Reported on ENGINX again today (footprints 13137) - ran command, failed with this error, ran command again, worked. We need to provide some sort of fix, we have discussed options that may eliminate the need for this PV to be queried every time, but in the short term could something along the lines of the retry on pv error we have added to waitfor be used here too?

**Comment by DominicOram** [comment]
Spun out half of this into #5413. changing estimation accordingly.

**Comment by DominicOram** [comment]
Once the following are merged:
* https://github.com/ISISComputingGroup/EPICS/pull/216
* https://github.com/ISISComputingGroup/genie_python/pull/256
* https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/297

I will remove reference to block cache in:
- [ ] https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Python-versions---2-vs-3
- [ ] https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IBEX-Ports
- [ ] https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-components
- [ ] https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/BlockServer-Structure

The following tickets can also be closed:
- [ ] https://github.com/ISISComputingGroup/IBEX/issues/4941
- [ ] https://github.com/ISISComputingGroup/IBEX/issues/4881
- [ ] https://github.com/ISISComputingGroup/IBEX/issues/4739
- [ ] https://github.com/ISISComputingGroup/IBEX/issues/1778

The following ticket should be re-evaluated:
- [ ] https://github.com/ISISComputingGroup/IBEX/issues/4338
