### ISSUE TITLE
Migrate away from Waffle

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4137]
Waffle is closing down on 16th May (https://waffle.io/closing-its-doors). We should find a good alternative.

**Comment by Kevin-Woods-Tessella** [comment]
GitHub has its own Project feature, which is similar to waffle.

**Comment by kjwoodsISIS** [comment]
New project board set up in GitHub - see https://github.com/ISISComputingGroup/IBEX/projects/1

Links to waffle in Developer Wiki replaced by links to IBEX Project Board
