### ISSUE TITLE
Make support number more obvious

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4138]
As a user/instrument scientist I would like to know the support number. Therefore:

* It should be displayed more prominently on the GUI
* It should be added to https://www.isis.stfc.ac.uk/Pages/Support-staff.aspx

**Comment by SophieKSTFC** [comment]
Not sure who has access to the https://www.isis.stfc.ac.uk/Pages/Support-staff.aspx page so not required as part of this ticket.
