### ISSUE TITLE
Auto-populate title with blocks

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4140]
As a user I would like to be able to specify some blocks whose values are then put into the run title. This was possible in SECI as I could write `sample with temp of @temp@` and temp would be populated. Make sure this feature is documented to users and developers.

**Comment by FreddieAkeroyd** [comment]
Had a look at the code, not hard to fix but touches quite a few places (isisicp, isisdae ioc and GUI)

**Comment by DominicOram** [comment]
After discussion at planning meeting:
* This needs to system tests
* Waiting until after the release to merge otherwise

**Comment by DominicOram** [comment]
As discussed, I'm happy to write tests/documentation for this but can't currently get it to work. I have a:

* ICP svn version 2009
* A block called `NEW_BLOCK` with a valid integer value
* A title of `MY BLOCK: @NEW_BLOCK@`
* The value of `NEW_BLOCK` appears fine in the the sample log but the title is displayed as `MY BLOCK: NaN`

**Comment by FreddieAkeroyd** [comment]
Updated isisicp on share, so you just need to run a create_icp_binaries.bat if not building from top directory

**Comment by DominicOram** [comment]
I'm taking Freddie and myself off of this to encourage someone else to pick up the testing + documentation which can be done by anyone

**Comment by Alistair-McGann-Tessella** [comment]
System tests:
https://github.com/ISISComputingGroup/system_tests/pull/21
