### ISSUE TITLE
Documentation: Log plotter time control

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4142]
As a user I would like to be made more aware of how I can scale the time axis on the log plotter. This is nicely done with the time button but is not documented in the user manual

**Comment by RaiBishal** [comment]
@DominicOram I have now documented the log plotter time control feature and it could be found in the user manual.
Link: https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Plot-a-Block-Graph

**Comment by DominicOram** [comment]
This looks like a good start, can you do the following:
- [ ] Highlight the button you mean in the image
- [ ] Add a screenshot for the window that pops up and a bit of text explaining it, including the absolute and relative time stuff.
