### ISSUE TITLE
Knauer HPLC: delay in turning on?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4143]
Noticed during the previous NURF experiment. Sometimes when starting a new script, the pump seemed to take a long time to turn on. On a few occasions they found they had to restart the script and then it worked.

**Comment by aaron-long** [comment]
- support: https://github.com/ISISComputingGroup/EPICS-Knr1050/pull/4

**Comment by aaron-long** [comment]
Updated the IOC to have better error handling (inc tests). The OPI now has a tabbed container that has a User and Advanced section. Error info can be seen under advanced (keeping the user facing interface clean). Minor bug fixes were also made.

In the original NURF experiment they were using a old driver, which has subsequently been updated multiple times. The issue with a long "turn on" time I believe has been fixed, and relates to the original drivers start/stop records that was redesigned when this was updated to match the design of the JASCO 4180. 

The ZOOM instrument scientists have confirmed that these drivers can be updated on the instrument on Friday morning (22/03/19): Added to pending tasks.
