### ISSUE TITLE
LET: Adding Eurotherm Block

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4145]
Instrument scientist wondered why he couldn't add a block to point to a Eurotherm channel as the values were greyed out.
Suggested that was because they were part of a component and that it had to be edited to reflect the desired changes in the configuration.

**Comment by DominicOram** [comment]
Can you add to the FAQ? (https://github.com/ISISComputingGroup/ibex_user_manual/wiki/FAQ)

**Comment by davidkeymer** [comment]
Question and answer added.

**Comment by DominicOram** [comment]
Thank you!
