### ISSUE TITLE
Client: printing from python in a tight loop causes excessive memory consumption

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4146]
As a user, I don't want my client to get very slow after I run a script that prints a lot

As a developer, I don't want the client to run into memory issues

Running a script that looks like:

```
while True:
    print("Hi")
```

This is the graph of CPU/memory. The CPU goes high while the script is in a tight loop as expected, however the memory also climbs steeply. Importantly, the memory is **not** recovered when the script is killed, nor is it recovered when the pydev console is killed. The only way I can see to recover the memory is to kill the client.

![image](https://user-images.githubusercontent.com/24375813/54524728-9cf25900-496a-11e9-88b2-55cda9c41f66.png)

The fix is probably to tell pydev to only keep the last n lines of script output - I think there is a pydev option for this, we should figure out how to set it and make sure it fixes this bug.

**Comment by Tom-Willemsen** [comment]
I did investigate this briefly a short while ago - there is an option in the eclipse preference store to limit output lines in some eclipse consoles, but not in the eclipse console implementation that PyDEV uses. We may need to dig deeper into the code for this ticket, and may end up needing to implement this logic ourselves.

**Comment by Tom-Willemsen** [comment]
Pulling this ticket into the sprint from the "bucket" as we have run out of non-labview tickets in ready.

**Comment by kjwoodsISIS** [comment]
Does the user get a warning if the system is about to clear the pydev console?  Do they get the option to save the output anywhere?

**Comment by John-Holt-Tessella** [comment]
No, when the buffer is full 1 million characters the buffer is emptied. @Tom-Willemsen said that he tried making it rolling but it is complicated code inside pydev. I think that we are unlikely to fill 1e6 characters so I am happy with this vs crashing the local computer. The user can choose to clear the buffer manually.

**Comment by kjwoodsISIS** [comment]
No need for this ticket to be in the "bucket" category any longer.
