### ISSUE TITLE
genie_python: waitfor_blocks -  should we be able to set just a high or lowlimit?

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4147]
When using waitfor_block it seemed that a waitfor with just one limit (the other limit interpreted as none) was ignoring the waitfor command. This is from a support call, and no attempt has yet been made to reproduce, The situation was a script that was waiting for a temperature that was ramping down, a `g.waitfor_block('blockname', highlimit = val)` where val was less than the current reading went immediately to the next line (this was bracketed by a `g.begin` and a `g.abort`).

If this can be reproduced we should ascertain whether this is the desired behaviour or not.
If this is desired behaviour the help files should reflect this more obviously as the impression I got was that only the one limit had to be specified.
If this is not the desired behaviour we need to fix the logic.

**Comment by adamb56789** [comment]
PR: https://github.com/ISISComputingGroup/system_tests/pull/16
