### ISSUE TITLE
GUI: dashboard tooltip shows incorrect value

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4149]
The tooltip for an item on the dashboard includes the value of the block, but it seems to be wrong on IRIS. The Sample block is showing 400K but the tooltip says it is at 390K (which it may have been at some time previously). I changed instrument and back again and the value was then correct, so it seems it reads it at client connect but what is the refresh interval after that?

**Comment by KathrynBaker** [comment]
No longer seems to be the case, I have just watched a tooltip updating alongside the value in real time on an instrument (WISH, G5_RP1_PIR)
