### ISSUE TITLE
4090-2: blockserver does not stop IOCs correctly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4150]
If I have a base configuration plus an IOC in a component, and I remove the component from the current configuration, the IOC does not get stopped.

**Comment by John-Holt-Tessella** [comment]
I want to define the behaviour for this. I think it should be:

On load of new config or edit of the current config (including components)

1. Any IOC which was in the old config and is not in the new config is stopped
1. Any IOC which wasn't in the old config and is indicated as `start` is started
1. Any IOC which was in the old config and is in the new config is restarted if:
    - Any macro has changed (not including globals)
    - Any PV default has changed
    - Any PV sets has changed
1. If any IOC has been stopped or started the Alarm server needs to be restarted
1. In addition the block gateway and block archiver (and possibly run control) and restarted if any blocks have been added/removed or their PVs/logging have changed.

Note this means any IOC not in either config remains running/stopped (e.g. if you start an IOC outside a config). It also means if globals changes IOC need to be restarted manually.

On g.reload_current_config() *all* ioc's including those not mentioned in any config should be stopped and then started again if set to `start` in the config.

**Comment by kjwoodsISIS** [comment]
Ensure we create tests to prevent regression.

**Comment by kjwoodsISIS** [comment]
This ticket will be done when #4110 is done.
