### ISSUE TITLE
MUONFE: New Server

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4155]
As a support person, I want to set up a new server to host the IBEX system used to control the MUON Front End.

#### Acceptance Criteria
1. New server provisioned with Windows Server and the NDEMUONFE VM.
1. New server physically installed in a cabinet (south side of R55) and connected to the network.
1. Task to be completed by 1st April 2019.

#### Notes
1. See ticket #4502 for outcome of discussion about new MUONFE server.
1. See also ControlsWork tickets [#557](https://github.com/ISISComputingGroup/ControlsWork/issues/557) and [#601](https://github.com/ISISComputingGroup/ControlsWork/issues/601)
1. **Note:** Check for network routing problems or firewalls that might prevent communication to instances of SECI on muon instruments.

**Comment by Tom-Willemsen** [comment]
I have verified that:
- The NDEMUONFE machine is available
- It is talking to some of it's power supplies correctly (some are not responding; I assume they are interlocked off out of cycle)
- It is talking to the NGPS supplies, with which we have had some communication troubles in the past
- It is available via EPICS over the network (this used to require an extra variable being set, but now that they are on a standard system, appears to be fixed).

I note that this machine has **not** come up with 14GB of RAM like RIKENFE, and that it will still need to be upgraded as part of https://github.com/ISISComputingGroup/IBEX/issues/3860 . However that is not in scope of this ticket. Therefore, as far as I can tell, this ticket is complete.
