### ISSUE TITLE
Deploy: Check configuration (MUONFE & RIKENFE)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4159]
As a developer I want to check the configuration of the release of IBEX on the new MUONFE and RIKENFE servers, so that I am confident that it is working as expected.  The configuration of the release needs to be checked by 26th April so that there is time to remedy any problems before handing over the the muons group.

#### Acceptance Criteria:
1. Check that the configurations of each device match those in use prior to the migration.
1. Check that on MUONFE, IBEX can communicate with the configured hardware devices.
    - [x] Magnet control communications checked (subject to interlocks, see note below)
    - [x] Communication to momentum slits checked
    - [x] Communication to separator DAQ checked (will read 0 kV and 0 mA (+/- noise) because the separator PSU itself will be switched off).
    - [x] Communication to SECI instances on EMU, HIFI & MUSR checked
    - [x] Check NAGIOS alerts are still working
    - [x] All problems (if any) resolved
1. Check that on RIKENFE, IBEX can communicate with the configured hardware devices.
    - [x] Magnet control communications checked (subject to interlocks, see note below)
    - [x] Communication to SECI instances on ARGUS, CHRONUS checked (not sure if this required)
    - [x] Check NAGIOS alerts are still working
    - [x] All problems (if any) resolved

#### Notes
1. Perform this ticket after [#4157](https://github.com/ISISComputingGroup/IBEX/issues/4157)
1. See ticket [#4502](https://github.com/ISISComputingGroup/IBEX/issues/4052) for outcome of discussion about new MUONFE & RIKENFE servers.
1. **Note:** The RIKENFE PLC is being upgraded during April and early May 2019.  We have been assured that the upgrade will have no impact on how IBEX interacts with the PLC.  However, during the upgrade process we are limted to testing read-only communications.  Full testing will have to wait until after the new servers have been handed over to the muons group.  We may need to liaise with Tim Carter and/or Andrew Sanders during this process.
1. **Note:** Most of the magnet power supplies on both sides will still have “control” power, i.e. be able to report the output reading and interlock status. Some will have interlocks keeping them off, for example: 
   * UB1 and UB2 PSUs on MUONFE 
   * all PSUs on RIKENFE while the PLC is upgraded. 
   * the Lambda Genesys supplies on MUONFE might lose all power if there is no water.
1. **Note:** Check for network routing problems or firewalls that might prevent communication to instances of SECI on muon instruments.

**Comment by LiamPanchaud** [comment]
It would also be worth testing that the PVs for monitoring changeover status (added in #3490) work as expected. Just in case data is being pulled from the wrong DAQ lines

* PV `RKNPS_01:RB2:MODE` 

| `RKNPS_01:DAQ:R04:DATA` | `RKNPS_01:DAQ:R05:DATA` | `RKNPS_01:RB2:MODE` |
| --- | --- | --- |
| 0 | 0 | FAULT |
| 1 | 0 | BEND 1 |
| 0 | 1 | BEND 2 |
| 1 | 1 | SEPTUM |

* PV `RKNPS_01:PORT3_4` 

| `RKNPS_01:DAQ:R02:DATA` | `RKNPS_01:DAQ:R03:DATA` | `RKNPS_01:PORT3_4` |
| --- | --- | --- |
| 0 | 0 | FAULT ( LOW) |
| 1 | 0 | PORT 3 (RQ18-20) |
| 0 | 1 | PORT 4 (RQ21-23) |
| 1 | 1 | FAULT (HIGH) |

**Comment by Alistair-McGann-Tessella** [comment]
Notes:

 - MUSR was the only beamline which had SECI running when the tests were performed. EMU and HIFI need to have SECI started before we can confirm the communication is correct
 - The DAQs were all off when the tests were performed, so these are reading disconnected (appropriately, as the DAQs aren't on)

**Comment by Tom-Willemsen** [comment]
- The RIKENFE DAQ wasn't off, it just needed reconnecting from within MAX (I think this needs to be done if the DAQ is power-cycled?). This is now tested and verified as working properly on RIKENFE.
  * I have not touched the MUONFE DAQ, but if the scientist says it is switched on, it may just need reconnecting from within MAX.
- Per @LiamPanchaud comment above, the DAQ lines on RFE mentioned above are now tested (the mapping is correct).

**Comment by Tom-Willemsen** [comment]
We have checked the configuration as far as possible. All the items listed in the original ticket have been checked (and fixed if necessary).
