### ISSUE TITLE
Script generator: create simple view and build process

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4164]
As a developer, I need some basic infrastructure to begin building the script generator.

Acceptance criteria:
- As a user, I can see a simple view in both the standard IBEX GUI and a standalone "script generator" application
  * For this ticket, a simple static table (and corresponding, basic viewmodel and model) will be sufficient to prove that the build process works correctly. This table doesn't need to be configurable as part of this ticket.
- Both the standard GUI application and the standalone application can be built:
  * Via eclipse IDE
  * Via maven
  * Via Jenkins
- The build process is adequately documented

After review:
 - Change the branch of the script generator Jenkins build to master

**Comment by Tom-Willemsen** [comment]
When starting this ticket, investigate whether parts of the existing script generator perspective are worth re-using or whether it will be easier to start completely from scratch.

**Comment by Alistair-McGann-Tessella** [comment]
@John-Holt-Tessella: Seems like this should be done using a second product in the standard build. That way we don;'t need to share code between two projects.
