### ISSUE TITLE
Script generator: load configuration from file

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4165]
As an instrument scientist, I need to be able to configure the script generator. I need to be able to load an instrument-specific configuration file into the script generator which tells it what “actions” are available, as well as other instrument-specific items.

Acceptance criteria:
- As a user, I can configure the types of entry which I can add to the table from a configuration file
- The format we chose in the implementation meeting is Python, see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Script-generator-high-level-design#the-action-class
- The headers of the table displayed in the GUI should change appropriately when a new configuration file is selected.

Notes:
- To interpret the python config file, we will need to bundle a python interpreter with the GUI. That is part of this ticket. Java <-> Python communication can be achieved by using `py4j`, which is already included in both `genie_python` and the GUI build.
- To generate a new action (row) in the table a default value needs to be set for each of the fields in this action. Ticket #4166 implemented a trivial default value for each field which should be set more appropriately in this ticket

**Comment by DominicOram** [comment]
Pulled the two points made in the notes out into:
* https://github.com/ISISComputingGroup/IBEX/issues/4910
* https://github.com/ISISComputingGroup/IBEX/issues/4907
due to time constraints

**Comment by JamesKingWork** [comment]
Once #4166 is finished we should merge the changes into here as this has old commits from the branch in #4166

**Comment by JamesKingWork** [comment]
> Once #4166 is finished we should merge the changes into here as this has old commits from the branch in #4166

Done in commit b2faeca on https://github.com/ISISComputingGroup/ibex_gui/pull/983

**Comment by Alistair-McGann-Tessella** [comment]
Updated ticket to include test issues: https://github.com/ISISComputingGroup/IBEX/issues/4759
