### ISSUE TITLE
Script generator: add/edit/delete/move/duplicate rows

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4166]
As a user of the script generator, I need to be able to manipulate the contents of the script generator table.

Acceptance criteria:
- As a user, I can add a new row to the script generator table
- As a user, I can edit an existing row
- As a user, I can delete an existing row
- As a user, I can re-order rows
- As a user, I can duplicate an existing row

**Comment by Alistair-McGann-Tessella** [comment]
Pull request:
https://github.com/ISISComputingGroup/ibex_gui/pull/978
