### ISSUE TITLE
Script generator: parameter limits

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4168]
As a user of the script generator, I need to be able to set arbitrary conditions which make inputs valid/invalid in the script generator.

Acceptance criteria:
- As an instrument scientist, I can define an arbitrary python function which tells the script generator whether a given set of inputs are valid or not
- This arbitrary function is loaded from the same place that defines the available actions to configure the script generator.
- When a user creates a script, the parameters are checked in real time (or close to real time) 
- When a user inputs invalid parameters, these a highlighted in an obvious way

**Comment by JamesKingWork** [comment]
We have decided to pass all parameters as strings from java to python and handle them in the python code by providing a decorator to pass casting operations to e.g. `@cast_parameters_to(temperature=float, field=str, uamps=float)`

This will allow them to define their own casting operations to deal with funny edge cases in a nice way. It also reduces the amount of edge cases we may find with py4j handling the difference between python and java class.
