### ISSUE TITLE
Script generator: send script directly to nicos

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4169]
As a user, I would like to send a script directly from the script generator to nicos.

Acceptance criteria:
- A script can be sent to nicos in one click (or at least, without requiring saving the script)
- Should include squish tests

Notes:
- Feedback (e.g. displaying which row is currently running) is not part of this ticket
- Think about how the import of the ActionDefinition class works (this is needed to run a script)

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by DominicOram** [comment]
+1 from MARI

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1302

**Comment by aaron-long** [comment]
Only one tiny change, good stuff.

After some discussion between Dom and I, we think that maybe (a later ticket) would be that each action of the Script Generator is submitted as a separate  script to the Nicos queue. This way you could easily make changes during the run and re-seed the scripts in their queue position during an execution. Will maybe append #4176
