### ISSUE TITLE
Script generator: time estimation

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4172]
As a user, I would like the script generator to provide time estimates. 

Acceptance criteria:
- As a user I get a total time estimate for scripts generated in the script generator
- As a user I get a time estimate for each row of the script generator (for example, an extra column which displays the estimated time).
- As a scientist, I can define a relationship between the script generator parameters and the estimated time. 

Notes:
- We will need to make some assumptions (e.g. beam rates)
- These assumptions may be instrument specific, so should be able to be changed by scientists (getting a sample to temperature may take longer on one instrument than another)

Suggested implementation: another function in the script generator config files, similar to `parameters_valid`, which takes a given set of parameters are returns an estimated time for this action in seconds. The script generator UI can then add these up for each row and display the total.

**Comment by Tom-Willemsen** [comment]
+1 emu scientists.

**Comment by kjwoodsISIS** [comment]
+1 all scientists

**Comment by Tom-Willemsen** [comment]
Thoughts from scientists at training session: it is useful to see the expected time for a particular row as well as a total. Perhaps we can add an extra column, like we have for validity which shows the estimated time for an individual row, as well as a "grand total" somewhere.

It would be useful to be able to access all of the rows in some way in the time estimation function, so that scientists can make the estimated time dependent on previous rows (this is important where ramps of temperature/field etc can take a long time).

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by DominicOram** [comment]
+1 from MARI

**Comment by mr-field** [comment]
PRs:
- GUI and Python interface: https://github.com/ISISComputingGroup/ibex_gui/pull/1106
- Genie Python: https://github.com/ISISComputingGroup/genie_python/pull/247
- Script definitions: https://github.com/ISISComputingGroup/ScriptGeneratorConfigs/pull/3

**Comment by mr-field** [comment]
Comments from demo:
- Use a auto-updated textbox rather than a button to display total estimated time
- Add units (seconds) to estimated time column
- Try to implement `estimate_time` in  the base ScriptDefinition class to avoid forcing everyone to implement it

**Comment by mr-field** [comment]
This is now ready for re-review

**Comment by DominicOram** [comment]
With @mr-field not here someone else should pick up this rework
