### ISSUE TITLE
UPS: Monitor Eaton 5p 650 and similar power supplies

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4175]
UPS of this model and similar are installed on instruments, usually for Galil controllers etc. They have a network or serial interface depending on model - this is the model on POLREF. It looks like http://powerquality.eaton.com/Products-services/Backup-Power-UPS/5P.aspx?cx=101 is the device. There seem to be various options available for network, so modbus or snmp are possibilities.

* meet with Jamie Nutter to get list of locations and models of UPS that are critical.
* determine best connection method, may need an options card purchasing for power supply
* determine monitoring method - local IOC or nagios

**Comment by kjwoodsISIS** [comment]
Needs UPS to be upgraded with a network card first.

**Comment by DominicOram** [comment]
@KathrynBaker and I attended a meeting this morning about this. JN has got a network card to test it with. Eaton provide some software that can do the monitoring for us. He's going to get a free trial and give it a go. Therefore this ticket probably wont require any work from us but leaving it here encase the situation changes.

**Comment by KathrynBaker** [comment]
Since then the UPSs are instead being removed from the system making this work unnecessary.
