### ISSUE TITLE
DETMON: Write the Wiki page to explain it to others

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4179]
As an IBEX developer, I want to know what the DETMON work is all about

**Acceptance Criteria**
1. There is a wiki page that details what this is all about!

**Comment by KathrynBaker** [comment]
Wiki page created at [DETMON](DETMON-Instrument-Details)

I anticipate rework as I'm sure I've not listed things that are needed by others to understand what is going on, please detail the questions that you can't find an answer to that is not covered between the wiki and the tickets listed within the umbrella ticket #4178

**Comment by Tom-Willemsen** [comment]
Wiki page is good

A couple of comments on the individual tickets:
- https://github.com/ISISComputingGroup/IBEX/issues/4181
  * Note 3: Why would we not be able to add this to the instrument list?
- https://github.com/ISISComputingGroup/IBEX/issues/4184
  * I have changed the title to "read only" as opposed to "write only"
- https://github.com/ISISComputingGroup/IBEX/issues/4186
  * I don't currently understand why we are required to use the instrument archive as opposed to the block archive for this.

**Comment by KathrynBaker** [comment]
RE #4181 – NDA not NDX – or have we managed to dissociate those aspects now that we can have non-NDXs in the list?
RE #4184 – Thank you
Re #4186 – At the moment none of these values are archived in the instrument archive, and there is a chance that the Blockserver setup won’t cope with in excess of 1000 blocks, plus at the moment the potentially interesting/useful items are not being saved unless a specific block is made for them
