### ISSUE TITLE
DETMON: Install IBEX as new instrument

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4181]
As an IBEX/Detector support person, I want IBEX installed on NDADETMON as if it were an instrument

**Acceptance Criteria**
1. NDADETMON is a Windows 10 system (requested in #4180)
1. NDADETMON exists as a new instrument

**Notes**
1. This will not have a DAE, but may need to create nexus files and so should have a simulated DAE setup
1. Being an NDA there may need to be an alteration to the config_env so that the system has a more standard name - this should be tested on installation, a hotfix applied if necessary, and a new ticket created to ensure that the hotfix is captured into the git systems
1. It may be that we cannot add this to the instrument drop down list at this time
1. See [Detmon](https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details) for background information/more details if required

**Comment by JamesKingWork** [comment]
It is unbearably slow, I will ask Chris to upgrade the CPU and Disk speed.

Seems all installed and set up correctly, many thanks for the help @Tom-Willemsen .

**Comment by KathrynBaker** [comment]
As I said, not a Chris machine (although he may be able to do that upgrade) – ask Facilities IT for these changes.

**Comment by JamesKingWork** [comment]
I have lodged a request with Facilities IT for this.
