### ISSUE TITLE
DETMON: Pilot Configuration setup

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4182]
As someone supporting IBEX and the detector monitoring systems at ISIS, I want to see if IBEX is a suitable solution, or if the IOC needs to be run in a different way

**Acceptance Criteria**
1. One HVCAEN_01 IOC running – talking to at least 1 CAEN crate on the DETMON IBEX server
1. A config exists for IBEX which has blocks for the HVCAEN channels running locally, and looking at each instrument that runs a CAEN
1. The pilot configuration logs the channel data as blocks

**Notes**
1. This setup will help to gain an understanding of the amount of data, and whether the saving format is suitable. This may lead to further actions being needed
1. Depending on the resolution of this test, the other tickets related to DETMON may need to be altered
1. See [Detmon](https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details) for background information/more details if required

**Comment by JamesKingWork** [comment]
Cron job used to restart run at midnight to tick over log file. See [cron jobs](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/cron-jobs-and-windows-scheduled-tasks)

**Comment by JamesKingWork** [comment]
Hotfix: 
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/231

**Comment by Alistair-McGann-Tessella** [comment]
The pilot config of DETMON looks good. It looks like there is an issue with the cron script, it doesn't run succesfully even when I trigger it manually. I had a quick look, it could be because the user doesn't have the 'Log in as batch' privilege but couldn't sort it out myself.

**Comment by JamesKingWork** [comment]
It has been noted that the ibex client is starved of resources and is running very slowly. This is highly likely to be due to the large amount of blocks being logged. Attempting to improve this is beyond the scope of this ticket, but the work should be added in another ticket.

**Comment by Alistair-McGann-Tessella** [comment]
Configuration is set up as required, and a new run starts once a day
