### ISSUE TITLE
DETMON: Board parameters available as PVs

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4187]
As someone supporting the detectors at ISIS I want the board parameters listed to be available for monitoring and archiving

**Acceptance Criteria**
1. The HVCAEN_IOC in use has the following information available for each board in a crate:
  * Model
  * Firmware release
  * Serial number
  * Number of Channels
  * ~Temperature~
  * ~Max Voltage~
  * ~Board Status~
2. Script to set up blocks also adds board parameters

**Notes**
1. The vendor code should be checked to see if this has been implemented before doing so ourselves
1. If this cannot be undertaken via the dll in the same way as the channel information, the OPC version of the IOC should be considered, but this should be generated as a new ticket and added to the umbrella ticket #4178 
1. See [Detmon](https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details) for background information/more details if required

**Comment by JamesKingWork** [comment]
Davide is mostly interested in the Temperature and Board Status. These should have alarms placed on them.

**Comment by JamesKingWork** [comment]
New driver added in https://github.com/ISISComputingGroup/IBEX/issues/5544 contains temperature (TEMP), max voltage (HVMAX), and status (BDSTATUS)

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/CAENHVAsyn/pull/6
RN: https://github.com/ISISComputingGroup/IBEX/pull/6902

**Comment by DominicOram** [comment]
Linked PR works great and I've merged it. Do we need to add it into the script that makes the DETMON configs though?

**Comment by JamesKingWork** [comment]
> Linked PR works great and I've merged it. Do we need to add it into the script that makes the DETMON configs though?

I've added them to the script, see commit f85051d4e3612104ea882186e438459437bd6d6f to NDADETMON branch on instconfigs.
