### ISSUE TITLE
DETMON: Launch 30+ HVCAEN_IOCs

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4189]
As a supporter of the detector systems at ISIS, I want to be able to monitor all my CAEN crates without relying on the instruments to be running the CAEN IOCs

**Acceptance Criteria**
1. We have a number of suitable tickets to ensure that 30+ of the same IOC can be launched without flooding the selection list in the config builder

**Notes**
1. There are various ways of launching IOCs, and there could be options better within the GUI for managing the information being shown
1. This ticket should be a discussion that raises more tickets which list the methods to try launching the IOCs, and/or changes to the GUI to manage this
1. The tickets created should be added to #4178 
1. If the solution is generic then similar tickets for the change should be added for the Danfysiks and Galils so that we can reduce the number of those IOCs listed as well
1. See [Detmon](https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details) for background information/more details if required

Requires #4217

**Comment by DominicOram** [comment]
Can connect to 8 with one IOC (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN) to do this properly we will need:
* Create another 3+ IOCs
* Add macros for the other 7 addresses

If 4+ IOCs are still too many for us to put in the GUI we would need to look into better ways of launching as discussed in this ticket or increase the number that 1 IOC can communicate with.

**Comment by FreddieAkeroyd** [comment]
It looks like the limit on 8 is from the CAEN library itself, the header defines MAX_CRATES as 8 and a "too many connections" error code is listed amongst the many possible return values. So without some trickery to load the library multiple times into one IOC we are likely stuck at 8 per IOC.

**Comment by KathrynBaker** [comment]
8 per IOC and 4/5 IOCs is perfectly acceptable in my opinion – 30 would have clogged the instrument machines up painfully, 5 is still fewer than there are Danfysiks and Galils, and to my knowledge no one has complained about the number of either of those yet.

**Comment by KathrynBaker** [comment]
After the consideration of needing 30+ IOCs for Danfysiks on the Riken Front End, it is worth closing this ticket as #6272 would cover anything if this is still needed
