### ISSUE TITLE
Reflectometry: Provide better errors in OPI

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4190]
As a user of the reflectometry server I would like to know what has happened if something goes wrong. There are `BL:STAT` and `BL:MSG` fields but there are a couple of issues with them:
* Its not very obvious in the OPI when the STAT is not OKAY
* The message gets truncated to 40 chars and so might not be useful

**Comment by ThomasLohnert** [comment]
Latest OPI displays `BL:STAT` and gives `BL:MSG` more space. However in the backend `BL:STAT` is still a string PV which is limited to 40 characters. This should be a char array, which is a trivial change but will require a script in the OPI to convert the string from ASCII back into text for display.
