### ISSUE TITLE
INES: Motion Safety Reporting

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4192]
As someone responsible for supporting INES, I would like to know the status of the motion safety system.

**Acceptance Criteria**
1. The ioLogik (model 1210 as on ZOOM - certainly a model 12xx) is available on the ISIS network
1. The IOC has been configured on INES to read the ioLogik
1, The OPI has been set to display the appropriate information
1. Any blocks/warnings have been identified and either set up, or a new ticket created as appropriate.

**Notes**
1. Details as to which channel is what is not currently available at the time of writing the ticket
1. To make the ioLogik usable in our systems we need to get hold of the module for a brief time beforehand to set it up for our network systems (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MOXA-e12XX for details)
1. This is likely to be installed during the shutdown prior to cycle 2019-01, but is a task that can be undertaken after the release provided the network has been set up before the device in installed
   * now looks likely for shutdown prior to cycle 2019-02
1. Contact Kyle Birtwell to get the mapping of inputs.

**Comment by KathrynBaker** [comment]
/remind me this needs adding to the proposals list on 20/5/19

**Comment by KathrynBaker** [comment]
It is worth noting that the spare for ZOOM has been taken for installation in this, and the new one ordered will become the spare

**Comment by KathrynBaker** [comment]
This has been chased and is delayed, it may come online in cycle, but is now more likely next shutdown. As such, removing the proposal label, although if it appears suddenly it may need to be dragged in, but is simply set up work so unlikely to be a significant issue

**Comment by Alistair-McGann-Tessella** [comment]
I've emailed our contact, moved into impeded until we hear back for a time to do this

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by Alistair-McGann-Tessella** [comment]
I have made a component on INES which includes connection and label information for the moxa 1210 used here. The device now has a DHCP reservation so is available on the ISIS network.

To test this work please confirm:
* The component exists on INES
* The IP address, channel names and device type are set in IOC macros for the moxa 12xx.

**Comment by DominicOram** [comment]
Config looks sensible
