### ISSUE TITLE
POLARIS: Settings for Gas Flow Panel

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4197]
As an instrument scientist on POLARIS, I would like the gas panel set up to make use of the permanent Moxa, and would appreciate someone popping down to look over things.

**Acceptance Criteria**
1. The gas panel uses the permanent Moxa

**Notes**
1. Was submitted as a Footprints request

**Comment by Tom-Willemsen** [comment]
4x CCD100 IOCS configured on Polaris via the new permanent moxa, set up blocks, verified readbacks were sensible, checked setpoints could be sent. Left with user.

**Comment by KathrynBaker** [comment]
Awaiting confirmation from the requestor, but in principle, this seems to be done.

**Comment by KathrynBaker** [comment]
REquestor has confirmed that the task is complete.
