### ISSUE TITLE
OPI JASCO 4180 - Create user and advanced panels

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4198]
The JASCO 4180 OPI has a hidden developer panel containing information on errors and program files. This is inconvenient to refer to when on a beamline instrument, rather than a developer machine.

The OPI should be updated so that there are two tabbed containers, User and Advanced. Advanced should contain this error and program information.

**Comment by ThomasLohnert** [comment]
Consider whether error status should be visible on front panel rather than in a secondary tab.
(listed as a desired improvement on https://github.com/ISISComputingGroup/IBEX/issues/4207)

**Comment by ThomasLohnert** [comment]
Fixed with https://github.com/ISISComputingGroup/IBEX/issues/4199.
