### ISSUE TITLE
Configurations: can have the same IOC listed multiple times in a configuration.

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4202]
As a user, I want to be warned if I add the same IOC twice to a configuration.

Currently LET have two `MCLEN_01` iocs in their current config (one of which has correctly filled in macros, the other does not). I do not think this makes sense as-is.

![image](https://user-images.githubusercontent.com/24375813/55015327-88eecd00-4fe4-11e9-9591-2e0b25915030.png)

I reproduced this locally by:
- Creating a new config
- Adding AMINT2L_01 to it
- Creating a new component
- Adding AMINT2L_01 to it
- Adding the component to the configuration
- Switching to the configuration

We should warn users (like we do for blocks) if an action would result in the same IOC being added twice. We should also have a test in the ConfigChecker which asserts that IOCs are only listed once in the current config.

**Comment by adamb56789** [comment]
Once this has been released to the instruments, if https://github.com/ISISComputingGroup/IBEX/issues/4540 has not been completed, it would get partially solved "automatically", as users will be unable to save or load any configurations or components which have conflicts, so will be forced to fix them.

**Comment by kjwoodsISIS** [comment]
It would be better to manually remove the duplicate IOCs - not everyone likes being forced to fix things they didn't realise were broken.

**Comment by ThomasLohnert** [comment]
Changes reviewed and approved. 

Re: the last comment, I'm not sure what the best course of action would be:
- Wait with merging these changes until existing duplicates on all instruments are resolved (move to impeded pending https://github.com/ISISComputingGroup/IBEX/issues/4540)
- Merge now and try to complete https://github.com/ISISComputingGroup/IBEX/issues/4540 asap (or accept that instrument scientists may be forced to change their configs)
- Add an option to ignore the warning and "load anyway" while clearly communicating the possible consequences

Any thoughts?

**Comment by kjwoodsISIS** [comment]
Why do we have to delay merging until #4540 is done?  The instrument scientists won't notice the change until we deploy the next version of IBEX.  What we have to do is edit the configs **_before_** we deploy.  We can complete this ticket and then make sure we do #4540 before the next cycle starts (in other words, option 2 above).
