### ISSUE TITLE
LET: ITC: verify cool-down procedure

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4212]
LET had a problem with their cryomagnet where IBEX reported that the needle valve was closed, but in reality the valve was physically open. The magnet was at zero, so it did not cause a serious problem this time, but it could potentially cause a magnet quench if it happened while the magnet was at field. This issue happened overnight from 28-29 March.

The scientists have two hypotheses about what may have gone wrong:
- There was a mechanical fault in the needle valve which meant that the valve could not (physically) close. 
  * It's possible that the ITC did not send the correct state back to ibex
  * If this is the case, it is not an IBEX issue
  * There were some problems with the hardware earlier in the evening (with the physical setup of the magnet).
- IBEX stopped reading the gas flow from the ITC correctly
  * IBEX had been correctly reading the gas flow from the ITC correctly earlier that day
  * Scientist reports that there were no purple borders around the number
  * The log files do not indicate a communication failure on reading the gas flow through the valve
  * IBEX was correctly reading other items from the ITC controller throughout (e.g. temperature fluctuations are visible in the log plotter)

The scientists and cryogenics will be cooling the magnet back down towards the end of the shutdown (in May). The scientists would like us to be available to help check whether it was a hardware or a software fault. This work will be being coordinated by cryogenics section.

**Comment by GRyall** [comment]
Either we supported them in May 2019 and forgot to close the ticket, or we didn't and they managed without us.
