### ISSUE TITLE
DETMON: Check if multiple crates can be accessed from the same IOC

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4217]
As someone supporting the use of CAENs in IBEX I want to know if I can access more than one crate from within the same IOC

**Acceptance Criteria**
1. Whether or not multiple creates can be accessed in the same IOC is documented in the wiki on a CAEN specific page, along with methods tried and their success
1. #4189 has been updated with this information so that a suitable solution can be enacted within that ticket

**Notes**
1. This should be a quick test, and not take more than half a day - if it takes longer, the answer is that this cannot be done, and the solution(s) attempted logged alongside 
1. This is *just* a test. Any code changes that are needed, or complexities to introduce to the st.cmds should be noted to be included in the work for #4189

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN and comment on https://github.com/ISISComputingGroup/IBEX/issues/4189.

**Comment by KathrynBaker** [comment]
Documentation exists and is easily understandable, I'm happy that we can run multiple crates in an IOC.
