### ISSUE TITLE
iocstartups: add miniinst build option 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4218]
On a mini-inst only a subset of IOCs are needed and these are listed in the startup.txt file on the instrument. The number of procServ processes could be reduced if the "make iocstartups" command looked for a startup.txt file and then restricted output (procServ, conserver) files to these IOCs. As it would require running "make iocstartups" on the instrument concerned, it may be better to create a new target "miniinst" so after updating you would type

make miniinst

which would run the iocstartups build, but only add IOCs that were also present in startup.txt

**Comment by KathrynBaker** [comment]
This would also solve #4216 if we did this in advance of an update on MUSR

**Comment by FreddieAkeroyd** [comment]
To test:

make iocstartups should run as before and create lots of ioc names in files such as iocstartup/procserv.bat

if you declare a mini-inst by creating a startup.txt file in the configurations directory, then when you run make iocstartups it will generate files only containing these iocs

**Comment by FreddieAkeroyd** [comment]
You would then run "make iocstartups" on MUSR after an install
