### ISSUE TITLE
Squish tests: fix on buildserver

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4221]
The Squish tests running on Jenkins are consistently failing to run all tests.

The error suggests that it can't find "switch instrument" in the IBEX menu, which suggests that the GUI may not have even launched correctly.

Error trace:

```
LookupError: Item 'Switch instrument' in object ':IBEX_Menu' not found or not ready.
Called from:
C:\Jenkins\workspace\System_Tests_Squish\suite_alarms_tests\tst_alarm_perspective_opens_when_button_selected\test.py: 13
C:\Jenkins\workspace\System_Tests_Squish\global_scripts\test_running.py: 26
C:\Jenkins\workspace\System_Tests_Squish\global_scripts\misc_dialogues.py: 26
C:\Jenkins\workspace\System_Tests_Squish\global_scripts\menu.py: 75|
```

**Comment by Tom-Willemsen** [comment]
Looks to be because the server/client are not installing correctly on the squish machine, it does not have a correct environment variable for the mysql password to upgrade it's database

**Comment by Tom-Willemsen** [comment]
- Added environment variable that squish needed
- Upgraded squish machine to Mysql 8 using script on share
- Set Jenkins build to use master as opposed to a ticket branch

Tests now look to be running correctly, but still failing for various reasons

**Comment by DominicOram** [comment]
Squish tests are now passing, albeit sporadically, but now fixing in a more ad hoc way
