### ISSUE TITLE
forward epics to kafka doesn't build using cmake 3.14.1

### ISSUE THREAD

**Issue by SophieKSTFC** [ISISComputingGroup/IBEX#4222]
As a developer I am unable to build forward epics to kafka using 3.14.1. 

Acceptance Criteria:
- [ ] I am able to build forward epics to kafka using cmake 3.14.1

**Comment by LiamPanchaud** [comment]
Cherry-picked commit `a477632374b9ebed974d7bed40aa9bb985c52e00` from `ess-dmsc/forward-epics-to-kafka` into our `master`
