### ISSUE TITLE
NDXCRYOLAB: install IBEX

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4226]
As a cryogenics support person I would like an IBEX installation which I can use to test equipment.

I believe there is an existing NDXCRYOLAB_R80 machine:
- [ ] Ensure the existing machine is suitable
  * [x] At least 30GB free disk space *NDXCRYOLAB_R80 has 90GB free*
  * [ ] Increase memory from 4GB (current) to [at least 8GB](https://github.com/ISISComputingGroup/IBEX/issues/3861)
- [ ] Install IBEX on it
- [ ] Configure IBEX as a test system, similar to SELAB
  * [ ] DAE in simulation mode
- [ ] Demo to cryogenics group

**Comment by KathrynBaker** [comment]
The Cryolab systems have IBEX available, this is no longer applicable I believe
