### ISSUE TITLE
REFL: Setting wiring tables

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4228]
As an INTER (and possibly other) instrument scientist I want the wiring table to be set when I put my multi-detector or point detector in so that I do not forget to change the table.

This could be implemented as a genie_python call in a special type of component but it might be better to implement it as a user defined function that can be added in the config which allows users to run arbitary python code based on the value set. This can then be called on "move". The advantage is that any user action could be taken on a set. Thus protecting us against this sort of change in the future.

**Comment by ChrisM-S** [comment]
This feels to me a bit more like the need to associate a file (or a file location) with a config - but in an intelligent/safe way.  I'm a bit leery about the way this might crash out if a user script is defined which doesn't work (for example, what tables are left after a failed move?) we've already had several synchronisation problems with the MERLIN tables...
There also raises the question we did get occasionally in SECI and that is can we script the selection of a config or a component.

**Comment by FreddieAkeroyd** [comment]
Like @ChrisM-S I would be cautious about mixing code and configuration files. Could this particular case be done as a DAE component? Note that wiring tables can only be changed in SETUP, so changing to multidetector configuration while still running would need to be handled.

**Comment by John-Holt-Tessella** [comment]
Should have been clearer that this is the reflectometry configuration. So it is defined in the reflectometry configuration file. This is already written in python. Not sure what a dae component is so will have to talk to you about that.

**Comment by John-Holt-Tessella** [comment]
Not needed misunderstood requirement. They will set the wiring table from the script.
