### ISSUE TITLE
MIGRATE: 2985-1 SECI->IBEX Galil offset and Homeval

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4231]
As a migrator I want the offsets and homeval to be correctly converted from SECI. This is s small part of #2985. This is done but needs checking and correcting if needed.

Acceptance Criteria

Offsets are correctly transfered for:

1. Absolute encoders
1. Non-absolute encoders
1. User offsets
1. Normal offsets
1. Any other offsets on the galil setup screen

In all cases the HOMEVAL should be 0. This assumes that the user never wants to return to SECI without homing once in SECI.

NB This needs a labview programmer.

**Comment by KathrynBaker** [comment]
The offset usages still need to be verified - this increase the complexity of the task, I would estimate it at 1, including the reworking of the conversion tool

**Comment by KathrynBaker** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI has information on how SECI deals with this and suggestions on values to use

**Comment by ThomasLohnert** [comment]
Not needed for reflectometry anymore as all axes have been migrated, perhaps still useful for other future migrations? Otherwise this can be closed.

**Comment by KathrynBaker** [comment]
There are no Galil axes on the last instrument to migrate, and this is too late for the last Galil migrations,
