### ISSUE TITLE
MIGRATE: 2985-3 SECI->IBEX Galil De-energise

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4233]
As a migrator I want the deenergise settings to be correctly converted from SECI. This is s small part of #2985. This is done but needs checking and correcting if needed.

Acceptance Criteria

1. If keep energised setting is set then IBEX should do the same (auto denergise false and energies true + make sure that this is autosaved)
1. If keep energised is set to false IBEX should be kept the same
1. The motor off deadband should be set to -1 (this causes problems with the motor deeregising after a move is auto deenergise is false)

NB. This needs a labview programmer

**Comment by KathrynBaker** [comment]
These changes are understood, although the documentation explaining this may be lacking, 0.5 as far as complexity is concerned

**Comment by John-Holt-Tessella** [comment]
Updated the acceptance criteria to make sure that the motor off deadband is -1. PV for this is `<inst>:MOT:MTR<motor e.g. 0305>_CP_SP`

**Comment by KathrynBaker** [comment]
I have added the following paragraph:
```Auto On/Off

This relates to the De-energise setting, it is also worth noting that when this is set to false then the motor off deadband has to be set to -1.```
to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI

The LabVIEW code has been changed so that De-energise will set autoonoff to match it, and the CP_SP has been moved from the 1 to 1 mappings to calculated values, it will now give values as before. unless de-energise is false, in which case it will always return -1.

**Comment by KathrynBaker** [comment]
The best way to test is just get the latest version from Source Safe and run it against a galil setup and see that it comes up with the expected outputs.

**Comment by KathrynBaker** [comment]
Consider testing #4233, #4234, #4509, #4510 and #4512 together

**Comment by John-Holt-Tessella** [comment]
Review:

- [ ] Can you remove `AUTOONOFF_CMD` from constants section, it is set there and then unset later. This is probably fine but it might catch an unwary person

**Comment by KathrynBaker** [comment]
Done and in the latest version in source safe
