### ISSUE TITLE
MIGRATE: 2985-1 SECI ->IBEX Galil piezo values

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4235]
As a migrator I want the piezo values to be correctly converted from SECI. This is s small part of #2985. This is done but needs checking and correcting if needed.

Acceptance Criteria

1. If this is not a PIEZO motor settings are 0
1. If this is a PIEZO motor settings  are correctly converted

NB This needs a LabVIEW programmer

**Comment by KathrynBaker** [comment]
This has not been considered in detail as yet, the information in LabVIEW is potentially structured in a very different way. I would estimate the complexity at 2 points - as the piezo motors are slightly more intricate than steppers. This is slightly higher than is realistic, but it is most certainly likely to be more complicated than 1 point.

**Comment by ThomasLohnert** [comment]
Looking at the output of the motor setup migration script run on SURF motors, it looked like the piezo settings were transferred correctly, specifically I am talking about these properties:
`K1` 
`K2`
`K3`
`ZP`
`NP`
`TL` 
`CP`
`CT`

What I am not sure about is the PID values. In IBEX, the PID values on the engineering screen just point at `K1`, `K2` and `K3`. In SECI, they are separate properties, but have identical values i.e. 
`K1` = `KP`
`K2` = `KI`
`K3` = `KD`

Not sure what the implications are either way.

**Comment by kjwoodsISIS** [comment]
@ThomasLohnert - you could check with Iain Johnson (or, possibly, with Gareth - he _might_ remember).

**Comment by KathrynBaker** [comment]
The doubling up relates to ceramic motors specifically I believe (there are some extra commands for those), whilst KP, KI and KD are in the standard firmware.

The rule was always to set them to the same value as to all intents and purposes they are. See the “tuning ultrasonic ceramic motors” file in the manuals for more detail on what and how they differ.

**Comment by ThomasLohnert** [comment]
Not needed for reflectometry anymore as all axes have been migrated, perhaps still useful for other future migrations? Otherwise this can be closed.

**Comment by KathrynBaker** [comment]
No instruments remain which need this for migration, this work has been overtaken by time.
