### ISSUE TITLE
Deploy: Update VHD image for IBEX

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4236]
After creating a VHD image in #2426 after we check it works update it with anything we have learnt. This includes solving the issues:

1. IPython when installing copies a profile that we need to users, using the following script:

```
REM create a default ipython_config
cd /D %PYDIR%
set "PATH=%PYDIR%;%PYDIR%\DLLs;%PATH%"
set "PYTHONHOME=%PYDIR%"
%PYDIR%\python.exe Scripts\ipython.exe profile create
if %errorlevel% neq 0 (
    echo "ERROR: Creating profile %errorlevel%"
	exit /B %errorlevel%
```

2. MySql needs a service installed using

```
mysqld.exe --install MYSQL80 --datadir="C:/Instrument/var/mysql/data"
sc start MYSQL80
sc config MYSQL80 start=auto

netsh advfirewall firewall delete rule name=mysqld.exe
netsh advfirewall firewall delete rule name=MYSQL8
netsh advfirewall firewall add rule name=MYSQL8 dir=in action=allow program=C:\Instrument\Apps\MySQL\Bin\mysqld.exe enable=yes

```

3. Remove ICPBinaries from inside EPICS and replace with ISISICP in the root dir.

4. Labview modules is needed to run some items in IBEX at the moment. Either create a C:\labview modules disk or remove the dependency.

**Comment by ChrisM-S** [comment]
OK, first thing is a dependency of mysql on the next VC++ run time library.
![image](https://user-images.githubusercontent.com/3035405/57022317-b3a4f480-6c26-11e9-8511-d3533be8f412.png)
Will add the newer one to the platform and try again!  I had V13 runtimes installed, just not V14!  As we are not using the installer I will see if we can get away without the 32 bit one.

**Comment by Tom-Willemsen** [comment]
@ChrisM-S the above dependency should be sorted by the upgrade script, there's an installer in `Kits$\CompGroup\ICP\vcruntime140_installer` which it references.

**Comment by John-Holt-Tessella** [comment]
The upgrade will not necesserily be run on the system disk. We probably need to write something in for this. I think this is probably a fairly rare event.

@ChrisM-S what java is installed on the windows system disk?

**Comment by ChrisM-S** [comment]
`Kits$\CompGroup\ICP\VMs` now contains the new December 19 "system.vhdx" for the new HIFI Cryomagnet system whcih can be copied down to replace the old one.  A few more details in  `0Readme.txt`.  Steps 1 & 2 [(above)](https://github.com/ISISComputingGroup/IBEX/issues/4236#issue-429842053) need carrying out after a second reboot of the system.  At this point IBEX should be fully back to how it was before, logs, apps, var and settings will remain as they were.  At least that is the theory.   Please note any extra steps down here in the following comments.

**Comment by ChrisM-S** [comment]
This worked OK after re-linking the existing VHDs against the newer system VHD.  Due to the build re-creating the volumes, the GUIDs no longer matched those in the volume mount points.  This will be solved by putting a mount script into the system start-up which searches all attached volumes (GUIDs names only initially) for the volume names, then these can be re-mounted to the appropriate mount points.  This search gets round the problem (because the disks are already connected, just not identified).  Needs testing on another system.

**Comment by KathrynBaker** [comment]
Superseded by other work
