### ISSUE TITLE
ZOOM: Motion tablet

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4238]
As a ZOOM instrument scientist I would like to be able to use a tablet to control my instrument, especially the motion. The tablet has already been purchased, safety will be handled by a deadman's handle that will be connected to the tablet. The motion control team are working on the handle. After discussion on the best solution we decided that:
* The IBEX GUI will be unlikely to be functional on the tablet
* It will be a large amount of work to convert it to be functional
* A single CSS screen will be enough to cover the functionality
* This would be a good opportunity to try using pheobus

**Comment by DominicOram** [comment]
@Steve-Cox-IDD-Motion Do you have an idea on timings for the handle/tablet integration?

**Comment by KathrynBaker** [comment]
Does this supercede #2937? It describes the implementation of the work to meet that need. If it is superceding #2937, then that ticket can be closed.

**Comment by DominicOram** [comment]
Sorry, I missed that ticket. This describes the implementation more accurately, which I think we're agreed upon, so I'll close the other.

**Comment by ThomasLohnert** [comment]
Some requirements that came out of talking to one of the instrument scientists back in December, which may inform the GUI design:
- Readbacks for all axes should be visible on the screen at all times
- Setpoint controls can be visible for just one axis at a time (i.e. can have just one set of controls on the screen and select which axis they point to)
- Textbox for entering a target value and buttons for tweaking the current value are both useful

**Comment by DominicOram** [comment]
Scientists are currently using the tablet with VNC into the NDX. It works but is fiddly. If we were to convert some OPIs to be more tablet friendly their order of preference would be
1. Sample stack and sample changer
2. Julabo

**Comment by JamesKingWork** [comment]
+1

**Comment by JamesKingWork** [comment]
Nick Webb has a tablet we can try this out on

**Comment by DominicOram** [comment]
Have the instrument scientists requested this now? We've known that Motion have had the tablet for a while but it was put on hold as the scientists seemed to go a bit frosty on the idea.

**Comment by JamesKingWork** [comment]
It was requested because it could be useful for motion in the future across all beamlines, but not as a priority to do now

**Comment by KathrynBaker** [comment]
I think thos work has either halted or altered in the intervening years, closing this ticket.
