### ISSUE TITLE
Configurations: editing current config multiple times

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4239]
There is a squish test that checks that the current config can be edited multiple times (by adding a block each time, 30 times). This test is currently failing on the build server complaining that the GUI is using too much memory at the end of the test.

Reproduced on a dev machine, java visual VM indicates that we are probably holding onto objects which we no longer actually need, so memory use increases as the current config is repeatedly edited.

**Comment by Tom-Willemsen** [comment]
The manual system tests for release 5.4.0 also caught this issue.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by kjwoodsISIS** [comment]
Now that ticket is in review, it can be removed from the bucket.
