### ISSUE TITLE
EUROTHERM: MODBUS Control

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4240]
As someone supporting Eurotherms at ISIS I want to be able to use MODBUS to communicate with them as well as the existing EI-BISYNC methods.

**Acceptance Criteria**
1. The Eurotherm can be controlled via either comms protocol mentioned (EI-BISYNC, already existing, or MODBUS)
1. The Eurotherm 32h8i has been confirmed as either working with this IOC, or has had a ticket created to generate an IOC to talk with it

**Notes**
1. All existing Eurotherms can talk MODBUS as well as EI_BISYNC so this can be developed and tested against any Eurotherm
1. It may be needed if greater knowledge of the Quick Cooling Cryostat - Needle Valve Controller is required
1. It would allow the facility to stop ordering the Eurotherms with the extra comms protocol, which whilst not a large cost of itself is a significant proportional cost of each Eurotherm
1. We have a standard Eurotherm available to test with (I believe)
1. A request has been received to interact with a https://www.eurotherm.com/en/products/temperature-controllers-en/indicator-and-alarm-units-en/3200i-indicator-and-alarm-unit/ which uses ModBus RTU (https://www.eurotherm.com/?wpdmdl=27877) after the long shutdown
1. User Support have been asked as to whether or not they have a unit we could test with

**Comment by FreddieAkeroyd** [comment]
https://github.com/dls-controls/eurothermModbus might be of interest

**Comment by Tom-Willemsen** [comment]
Proposed as the long-term solution to https://github.com/ISISComputingGroup/IBEX/issues/5756

**Comment by DominicOram** [comment]
Proposed so that we don't continually hotfix https://github.com/ISISComputingGroup/IBEX/issues/5756

**Comment by FreddieAkeroyd** [comment]
Or we test `replyTimout = 2000` elsewhere and then roll it out?

**Comment by FreddieAkeroyd** [comment]
Interestingly the DLS modbus driver calls `modbusInterposeConfig` to insert a 2000ms timeout...

**Comment by KathrynBaker** [comment]
A recent request has been received to interact with a https://www.eurotherm.com/en/products/temperature-controllers-en/indicator-and-alarm-units-en/3200i-indicator-and-alarm-unit/ which uses ModBus RTU (https://www.eurotherm.com/?wpdmdl=27877).

The initial use for this device is a read only system, and it may need to be treated differently to the existing Eurotherms - but considering the two at the same time and splitting or combining is appropriate (a new ticket may be needed for the specific device mentioned in this comment).

**Comment by KathrynBaker** [comment]
Proposing as there has been a request to consider moving all Eurotherms to modbus (note that older models need to be able to use EI-BISYNCH, so we need both comms methods available!), it also has better response times which may benefit the Muon systems. There are also commands that are only available via the modbus areas needed for WISH.

**Comment by rerpha** [comment]
Just putting on here for reference, the extra commands available are: 

- Switch between Auto and Manual Mode
- In Auto mode, a temperature can be set
- In Manual mode, a flow can be set

**Comment by DominicOram** [comment]
Did you get in touch with the original developer for the DLS driver? I can probably hunt them down if useful?

**Comment by FreddieAkeroyd** [comment]
Changing to Modbus RTU mode in asyn and changing serial data width to 8 bits has allowed communication. Current issue is that driver uses modbus absolute addressing that was not supported until epics modbus 2.9 and we are currently on 2.6 so I will update our version.

**Comment by FreddieAkeroyd** [comment]
Updated epics modbus to 2.10.1 and is now reading fine

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/718
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/556
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/150
- https://github.com/ISISComputingGroup/IBEX/pull/7293

Docs:
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eurotherm

Follow-up issues:
- https://github.com/ISISComputingGroup/IBEX/issues/7345

Note: until https://github.com/ISISComputingGroup/IBEX/issues/7345 has been done, we should prefer to use ei-bisynch comms to eurotherms wherever possible, as the current approach to scaling factors is very error-prone in subtle ways (e.g. wrong PID settings would make a eurotherm *appear* to talk correctly and may even change temperature ok for small changes, but would fail to change temperature during larger changes)
