### ISSUE TITLE
GUI: 3877-2: Monitor for reoccurences of segmentation fault (crash) [TIMEBOX: 5]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4246]
This ticket is a placeholder for re-occurences of the segmentation fault seen in https://github.com/ISISComputingGroup/IBEX/issues/3877

Note any re-occurences on this ticket. The crash dumps added in 3877 should give us some extra information which may allow us to find the root cause.

**Comment by Tom-Willemsen** [comment]
There have been re-occurences of the crash on multiple instruments.

A crash minidump is available on the share: `\\isis\shares\ISIS_Experimental_Controls\Ticket4246_swt_uniscribe_crash`

I have had a quick look through, there is some extra information (it is crashing in the windows uniscribe `USP10.DLL` while trying to retrieve something from an internal cache) but there's not an obvious root cause. This should be investigated in more detail.

**Comment by Alistair-McGann-Tessella** [comment]
+1 Polaris from last cycle. The crash dumps have been added to the share.

The report was that the user had stopped a script in the scripting perspective and was typing another genie python command in the scripting window. The pydev tooltip came up suggesting how to finish the command, and when the user typed an open bracket to finish the command the GUI crashed.

**Comment by Tom-Willemsen** [comment]
Crash has not happened on any instruments so far this cycle.

`USP10.DLL`, where we were having the problem, was updated as part of https://support.microsoft.com/en-gb/help/4507449/windows-7-update-kb4507449 and is on the instruments now, microsoft's release notes don't say exactly what was changed though. It's possible that this has fixed the crash we were seeing but I'm unsure of this. Continue monitoring for crash logs on the instruments and pick up this ticket again if we see a crash again this cycle.

**Comment by Tom-Willemsen** [comment]
In the last cycle, it appears that only MERLIN (which was still on an old release) suffered this crash.

Closing this ticket for now, re-open if we see the crash again.
