### ISSUE TITLE
Reflectometry: Documentation guide of concepts in the IOC to allow Config file to be written

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4250]
As an instrument scientist or developer, I would like to know how to write a configuration file and to understand all the concepts in that file (including where the file is).

Acceptance Criteria

1. Config file on the instrument has a link to wiki
1. Basic config file set out and explained on wiki page
1. Concepts within that page a linked to explanation

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/IBEX/wiki/Reflectometry-at-Isis

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Configuration

**Comment by ThomasLohnert** [comment]
Somebody other than John review this please

**Comment by DominicOram** [comment]
* No breadcrumb
* The page doesn't seem to be linked from anywhere. e.g. I would expect it to be linked from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-IOC

**Comment by ThomasLohnert** [comment]
Changed doc pages (replace duplication with link to config page):
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Geometry-Components
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Beamline-Object#beamline-constants
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Beamline-Parameters
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Composite-Driving-Layer
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-IOC#footprint-calculator

>

**Comment by DominicOram** [comment]
Much better and more interconnected! Acceptance Criteria 1 says that this page should be linked from each of the configs on the instruments. I can't see this link but also these configs don't appear to use the new helper methods. Is there a ticket for updating them?

**Comment by ThomasLohnert** [comment]
The configs have been updated to use helper methods, but might not have been installed on the instruments yet. The latest configs can be found on the private controls share, I have updated them 
now with the link.
