### ISSUE TITLE
Reflectometry: Moving Theta individually applies Slit Gap Parameters

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4251]
Performing an individual move on a Theta parameter will apply any changed setpoints for slit gap parameters and moved to. (it should maintain the current setpoint readback values).

Find out what is going wrong and  fix it.

NOTE: Does not seem to happen for individual moves on other parameters. Neither do other parameters seem to wrongly apply setpoints on an individual move as the slit gaps do.

**Comment by aaron-long** [comment]
Slit gap SPs are also processed when processing the `Move` buttons on the components screen.

**Comment by ThomasLohnert** [comment]
May be related to https://github.com/ISISComputingGroup/IBEX/issues/4394

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/222
