### ISSUE TITLE
Jasco 4180: no errors for disconnected device

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4257]
As a user I would like some visual indication that the JASCO-4180 device is not communicating properly.

Currently the disconnected device looks like this:

![image](https://user-images.githubusercontent.com/24375813/56044166-80152f80-5d36-11e9-8a9c-5027bc52f428.png)

There should be pink borders around all the readbacks if the device can't talk

**Comment by aaron-long** [comment]
- Needs to make use of the error setter template for record redirection

**Comment by aaron-long** [comment]
- IBEX_GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/889

**Comment by kjwoodsISIS** [comment]
How many points was this?

**Comment by aaron-long** [comment]
> 
> 
> How many points was this?

0.5
