### ISSUE TITLE
robocopy: use /MT option

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4262]
I tested multi-threaded copying by adding /MT to the robocopy command in install_to_inst - when tried on NDXTEST1 this reduced the time taken to install EPICS from 10 minutes to 3 minutes. I suggest we enable this option on other robocopy commands used in ibex.

The /MT command by default enables 8 threads - more threads can be used by passing a numeric argument. I tried 16 threads but it made little difference here, so I suggest going with the default for now. Given the factor of  3 speedup it may be that adding threads after about 4 gives little difference, but as results probably depend on disk speed may be worth keeping the default 8 for now.

**Comment by ChrisM-S** [comment]
It may be a win/win with small files but it's be worth checking the fragmentation of the files copied (with sysinternals `Contig` is good), particularly any larger files which may potentially get very fragmented.  I've had really bad experience in the past with `robocopy /mt` archiving files where doing three at once looks like 1/3 of the speed for each to complete but it wasn't as fast as it looked and the files were then neatly knitted into 100s of fragments!
This may not be the case here but it wouldn't be good to chop up a database into too many bits!.

**Comment by FreddieAkeroyd** [comment]
We should check this, according to https://superuser.com/questions/303378/robocopy-and-fragmentation/303439 this may have been an issue with older version of robocopy if they did't pre-allocate space for the file first. It recommends /J for larger files, but doesn't say what "larger" is!

**Comment by FreddieAkeroyd** [comment]
I think /J may be a good option, unfortunately it needs windows 8 or higher.
