### ISSUE TITLE
Reflectometry: Make relative component positions ordered

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4264]
As a reflectometry user, I would like all the relative position parameters on the second OPI tab to always show up in the same order, this being the order in which the components sit on the beamline. Currently they are randomly ordered on each startup. This likely just needs some `dict` to be changed to an `OrderedDict` in the reflectometry IOC.

Acceptance Criteria

1. All beamline parameters are shown on OPI in two lists those in the mode and those not in the mode. 
1. OPI element is configured to be of the correct type
1. Order is order in configuation file

**Comment by SophieKSTFC** [comment]
See PRs: 

https://github.com/ISISComputingGroup/ibex_gui/pull/900
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/194
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/205

**Comment by ThomasLohnert** [comment]
Some minor rework for consistency, see comments on inst_servers PR
