### ISSUE TITLE
Utilities: error_setter.template remove unused alias

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4266]
The error setter template is used by devices such as the DH200 and FJZDDFCH. In the current template an alias is created against a substituted record and a companion simulation record. It was discovered that this was incorrect, and was intended to be an alias to the RAW record (that the template creates).

After some discussion and testing against these IOC's it was found that this alias is unused and not needed.

To test:

1. Build an IOC that uses error_setter such as DH200 or FJZDDFCH
2. Confirm all IoCTestFramework tests pass
3. Confirm link alarms still propitiate across the records and are show in the OPI

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS-utilities/pull/10

**Comment by DominicOram** [comment]
@SophieKSTFC May be a good one for you to review?
