### ISSUE TITLE
Scripting: ensure error text is red rather than black

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4268]
As an instrument scientist, I want errors in genie python to be reported in red text rather than black text.

This corresponds to writing to STDERR as opposed to STDOUT

**Comment by kjwoodsISIS** [comment]
I appreciate this this ticket implies that some error messages are not being written to STDERR and that some work will be required to remedy things.  However, thinking ahead, this is the kind of thing that could go in a checklist - "have you checked that error messages are written to STDERR?"  A few cases might slip through, in which case, they should be caught during the review process (i.e. the reviewer makes the same check).
