### ISSUE TITLE
LOQ: LSi Correlator python vs vendor software

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4271]
As a LOQ instrument scientist I need to be able to control the LSi correlator. Ticket [4021](https://github.com/ISISComputingGroup/IBEX/issues/4021) concluded that we need to test that the python API for the correlator gives the same 'answer' as the vendor provided software. This can be performed by doing DLS runs with the correlator using a standard sample and comparing the correlation functions from the python API and the vendor's software. The two should be in broad agreement, within some experimental noise.

## Acceptance criteria
- [ ] Comparable DLS runs have been taken with both the Python API and vendor software
- [ ] The results of the comparison have been written on the wiki with suggestions about what the next step should be

**Comment by Alistair-McGann-Tessella** [comment]
Result of 5 DLS runs performed in python, and in the vendor software:

![lsi_vs_python](https://user-images.githubusercontent.com/39486445/56360699-5435f600-61dd-11e9-9dd5-2c267605c088.PNG)

Note that while the the python and vendor software do look different, the overall shape of these curves is not as expected.
We will wait for the scientists involved to make sure that the graphs returned by the device are clearer, then re-run the tests and compare the two data sources.

The testing method is described in [the wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LSi-Correlator#python-api-vs-vendor-software)

**Comment by smk78** [comment]
The SANS-DLS (this is now its official name on the ISIS Laser Inventory) has now had all outstanding electrical/electronic work completed (http://www.facilities.rl.ac.uk/isis/Motion/Operations/Equipment Notes). Realignment is now in progress. When complete we will want to repeat the comparisons of the python vs vendor software above (hopefully with better looking curves!!!). A second commissioning experiment on LOQ is scheduled to start on Oct 22.

**Comment by Alistair-McGann-Tessella** [comment]
Conclusions of October experiments:

1. Data taken from the python API are equivalent to the vendor's software
1. The python script was set up using the parameters given on [the wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LSi-Correlator#python-api-vs-vendor-software)
1. `obj.Correlation` and `obj.Lags` are the values of interest to the scientists
1. Python API still needs modifying for python 3 and to make sure the connections are terminated correctly after each set of repetitions
1. The scientists also want to be able to save metadata along with the data from the DLS, see #4918

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella  : In your notes on the wiki, you say "_Python API still needs modifying for python 3 ..._".  Do you mean our API or the device vendor's API?  If the device vendor's API do we know their plans to have a Python 3 compatible API?
