### ISSUE TITLE
Deploy: create mid-May release

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4272]
As a developer I want a suitable mid-May release to be created:

#### Acceptance Criteria:
1. [x] Release to be ready to install by 15h May
1. [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
1. [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
1. [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)

**Comment by Tom-Willemsen** [comment]
Testing spreadsheet: [manual_system_tests_v5.4.0.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584824c871a2f60e0061286a/125516c66e82c728ace21e0d46e5959436838f969cf0ac57a150cf802c5533601612f66524cbb36af3006b1300051bff054a5556f9ffda7da4e36f72895d09eed36f5e77c63d16a8bdd41de913a632c91edbe2e3d7158abd7f37ed998e47341f001d8ef65c37a59148ca50f459ac.xlsx)

**Comment by DominicOram** [comment]
System testing spreadsheet has been filled in and is on the share. Appropriate tickets have been spun out of it. Release has now been deployed on most beamlines and looks good so far so calling this complete.
