### ISSUE TITLE
Deploy: deploy mid may release

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4273]
As a developer I want the mid-May release created in #4272 to be deployed to all instruments.

**Comment by kjwoodsISIS** [comment]
Deploy to SURF (just install, don't configure).
   * Note: SURF already has a mini-inst.  Check SECI->IBEX works

**Comment by kjwoodsISIS** [comment]
Deploy a mini-inst to MuSR.

**Comment by Tom-Willemsen** [comment]
## Instruments to deploy full, standard IBEX installations at release 5.4.0:
- [ ] ALF
- [ ] CRISP
- [ ] EMMA-A
- [ ] ENGINX
- [ ] ENGINX_SETUP
- [ ] GEM
- [ ] HRPD (note: NDX currently down?)
- [ ] IMAT
- [ ] INES
- [ ] IRIS
- [ ] IRIS_SETUP
- [ ] LARMOR
- [ ] LET
- [ ] LOQ
- [ ] MAPS
- [ ] MARI
- [ ] MERLIN
- [ ] OSIRIS
- [ ] POLARIS
- [ ] SANDALS
- [ ] SELAB
- [ ] SOFTMAT
- [ ] TOSCA
- [ ] VESUVIO (note: NDX currently down?)
- [ ] ZOOM

## Instruments to install "special" systems:
- [ ] SURF
  * Just install, don't configure. As such, don't hide SECI etc.
  * Check that SECI -> IBEX works by checking that you can caget SECI blocks.
- [ ] MuSR
  * This is a mini-inst system which uses the CAEN IOC. After deployment, verify that SECI can still talk to the updated IOC.

**Comment by ThomasLohnert** [comment]
Release is deployed to all instruments apart from VESUVIO, which is still being rebuilt (created a separate ticket and entry in pending tasks).

**Comment by Tom-Willemsen** [comment]
All relevant instruments now on release 5.4.0 and noted on https://github.com/ISISComputingGroup/IBEX/wiki (except Vesuvio, see separate ticket). I think this can be considered complete. If any issues with the release come up, we can create a new ticket.
