### ISSUE TITLE
LOQ: Transmission monitor LEDs are disconnected

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4278]
As a LOQ instrument scientist or user I don't want the M3 transmission monitor position LEDs to read disconnected.

The problem can be seen in LOQ's synoptic. The M3 transmission monitor OPI has disconnected LEDs

Check if this issue is fixed by the latest release.

**Comment by smk78** [comment]
Any chance this could be fixed soon, please?
![image](https://user-images.githubusercontent.com/10938679/92499779-2eefc080-f1f4-11ea-8fe0-b15ab1e60e6b.png)

**Comment by John-Holt-Tessella** [comment]
Try restarting galil 01

**Comment by smk78** [comment]
Yay!
![image](https://user-images.githubusercontent.com/10938679/92522119-39bb4d00-f216-11ea-90db-46096f491eec.png)

Thanks, John!

**Comment by kjwoodsISIS** [comment]
Re-opened to go through the normal review process.
