### ISSUE TITLE
Tech Debt: DAE Squish Tests (ref: #3951)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4282]
As a developer, I want to resolve an outstanding item of technical debt that could be resolved on the original Tech Debt Stand-down day, so that the original Tech Debt Stand-down day can be closed.  This item stems from ticket #3951.

A number of Squish tests were created, but they don't quite work.  The Squish tests are defined in the following PR:
   * PR at https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/22/

#### Acceptance Criteria
1. Make the Squish tests work

#### Notes
1. None.

**Comment by DominicOram** [comment]
Linked ticket has now been closed, closing this as well.
