### ISSUE TITLE
Rotating sample changer: changes from tests of 4028

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4287]
As a result of testing the changes in https://github.com/ISISComputingGroup/IBEX/issues/4028 on a real sample changer (on GEM & Polaris), we realised that the change is more complicated than first thought, and that the pull requests that were merged in 4028 are not sufficient (they cover most of the requested functionality, but not all of it, as we did not fully understand some of the subtleties of the device when we implemented that ticket).

### Sample dropped

The workflow that needs to happen in this case is:
- IBEX sends a move request
- Some time later, the sample changer reports a "dropped sample" error
  * The sample changer will stop at this point
- At this point, the sample changer may be one or more positions away from where it originally was, and will not have made it fully to the target position
- IBEX needs to remember the position which the sample changer came from, and send the sample changer back to that position
  * We should not assume that we are only one position away from the old position
  * The sample changer can rotate in either direction, so we can't just add/subtract n positions. We need to remember the old position somewhere.
- IBEX then needs to request a lower/raise of the sample arm to re-attempt to pick up the sample
- IBEX needs to verify that the `SAMPLE_ARM_UP` state is reached
  * Note, `SAMPLE_ARM_UP` is not necessarily the opposite of `SAMPLE_ARM_DOWN` i.e. they are not boolean inverses of each other.
- IBEX then needs to tell the sample changer to go to the position which was originally targeted

All of the above needs to be retried a maximum of 10 times, after which IBEX should give up and display an error.

Currently the change in #4028 doesn't remember the last position, so does not succeed in picking up the dropped sample. This means that it ends up at the target position as expected, but with multiple samples in the beam, which would cause the neutron data to be bad.

---

A similar issue was seen in https://github.com/ISISComputingGroup/IBEX/issues/5027 . When doing this ticket, we should be careful to consider all of the known error cases and react appropriately to them. We may be able to get a list of the possible errors from Electronics.

> The Polaris sample changer Maclennan control crate indicated an error -
position 3 requested, but the sample had failed to lower. However, the
Move_Finished block indicated "1" (i.e. it though the move has been successful)
and started the next run with no sample in the beam.

**Comment by KathrynBaker** [comment]
+1 from POLARIS, along with requests for error message displayed without having to open the synoptic view, and a way to check that the error has not occurred before data collection starts.

**Comment by KathrynBaker** [comment]
Screenshot provided:

![image](https://user-images.githubusercontent.com/10552381/74235472-f839e200-4cc6-11ea-8d7b-eca908196740.png)

So that the message is available but is not acted upon in an error state

**Comment by DominicOram** [comment]
On hardware test what the status bits give when in the `retrieve sample` position.

**Comment by DominicOram** [comment]
Main PR is https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/pull/6. I created a new ticket to test against hardware at https://github.com/ISISComputingGroup/IBEX/issues/5342. I think the additional requests from POLARIS can be done with just a block and run control, ticket at https://github.com/ISISComputingGroup/IBEX/issues/5343

**Comment by DominicOram** [comment]
Also reduced points as I split out some of the work for this

**Comment by DominicOram** [comment]
Ensure we alarm on the position if there was an error from the device

**Comment by DominicOram** [comment]
I think the review for this should take a day

**Comment by ChrisColeExpControl** [comment]
Looks mostly good, only issue is on the [tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/306)
