### ISSUE TITLE
CRISP: Reflectometry Config Detector Setup Laser Mode

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4289]
As a CRISP scientist I would like my reflectometry configuration to include a mode for laser alignment, which moves both detectors to their parked position. This also requires adding a parked position to each detector component.

Except that this is a different park to normal out of beam position.

**Comment by John-Holt-Tessella** [comment]
Pull requests:

- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/322
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/289

**Comment by ThomasLohnert** [comment]
Review:
- See comments on both PRs
    - https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/289
    - https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/322
- in CRISP config: Could you please double check all the SM parameters are added to the right modes ? Currently `SMInBeam` is in the laser mode (with no inits) whereas `SMAngle` and `SMOffset` are not - seems like an odd choice
- in CRISP and SURF config: Should the Multi Detector have an `InBeamParameter` ?
