### ISSUE TITLE
Reflectometry: OPI Improvements

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4295]
As a reflectometry user / scientist I would like the reflectometry UI to be more user friendly.

The following changes should be implemented to the reflectometry front panel OPI:

#### Split OPI
- Have a "basic" and "advanced" OPI, for users and instrument scientists respectively.
- Advanced OPI: Each parameter (including sample stack and slit gaps) should have `RBV`, `SP:RBV` and `SP` values as well as an individual `Move` button
- Basic OPI: Each parameter should just have an `RBV` and `SP`
- Both versions: `RBV`, `SP:RBV` and `SP` columns should be clearly labeled.

#### Add colour indicators
- Both versions: Indicate a moving axis with a green background
- Advanced OPI: Indicate a discrepancy between parameter `SP` and `SP:RBV` by colouring the `SP:RBV` background red.
- Advanced OPI: Indicate a discrepancy between parameter `SP:RBV` and `RBV` by colouring the `RBV` background red.

**Comment by kjwoodsISIS** [comment]
Am I correct in assuming that the proposal here is for a single OPI with "Basic" and "Advanced" tabs?  I think we should be producing a single OPI (with two tabs) rather than two separate OPIs, otherwise we end up having to implement the same thing twice over (with the consequent risk of error - e.g. we make a change in one and forget to change the other).

**Comment by kjwoodsISIS** [comment]
I also assume that this proposal fits with the proposals for a Reflectometry perspective.

**Comment by ThomasLohnert** [comment]
The front panel displays each parameters as linking containers pointing at a `param.opi` (which contains widgets for a single parameter). I think we can have one general front panel implementation which loads one of two versions of `param.opi` based on something (macro, checkbox, manager mode?). I think this should be reasonably easy to maintain

**Comment by ThomasLohnert** [comment]
Decided that this ticket is too broadly scoped. We will only do the colour indicators as part of this ticket as they are the most impactful, other improvements have been spun out into separate, more focused tickets:
https://github.com/ISISComputingGroup/IBEX/issues/4517
https://github.com/ISISComputingGroup/IBEX/issues/4518
https://github.com/ISISComputingGroup/IBEX/issues/4519

**Comment by aaron-long** [comment]
- IoC Test Framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/207
- Inst Server: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/213
