### ISSUE TITLE
Motors: Warn if in "set" mode

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4298]
As a user, I would like it to be more obvious when a the motor is in `set` mode rather than `use` to avoid accidentally redefining the motor positions.

This could be done for examply by setting an alarm on setpoint and readback when in `set` mode.

**Comment by kjwoodsISIS** [comment]
How about displaying a string saying "Motor is in set mode" (possibly in red text)?

**Comment by ThomasLohnert** [comment]
That certainly would work. I feel like setting alarms on the motor could still be useful for catching this condition in ways other than observing the OPI (e.g. scripting)

**Comment by kjwoodsISIS** [comment]
We don't need to do this. We have a better solution.
