### ISSUE TITLE
GUI: Show motor name in tab title

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4299]
As a user I would like to easily distinguish which OPI tab belongs to which motor. Display the name of each motor in its tab title.

**Comment by DominicOram** [comment]
Is this referring to the more details screen? If so I think it's fixed with https://github.com/ISISComputingGroup/ibex_gui/pull/904

**Comment by John-Holt-Tessella** [comment]
Yes
