### ISSUE TITLE
Matplotlib: Limited number of plots

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4308]
Matplotlib in IBEX is currently limited to a maximum number of 6 plots after which they need to be manually cleared with `matplotlib.pyplot.close("all")' (or a specific plot # instead of "all"). This is cumbersome especially for things like reflectometry where dozens of plots are created as part of a beamline alignment. 

Proposed actions to address this issue:

1. Dynamically close old plots when limit is reached
2. Increase the limit of plots (I believe the maximum is 48). Step 1 is much more important since users may still hit the higher limit at inconvenient times (e.g. middle of the night, creating support calls) However, increasing the limit also provides a longer plotting history which could be useful.
3. Create a procedure providing a more memorable/convenient alias to `matplotlib.pyplot.close("all")`

It would also be useful to check as part of this ticket whether the plots could be made to refresh quicker. If this seems hard to do, create a separate ticket.

**Comment by Tom-Willemsen** [comment]
2. See https://github.com/ISISComputingGroup/ControlsWork/issues/499 for registry keys to change the limit to 48 plots (this is a limitation of the internet explorer view which we embed into eclipse).
3. Would it be sufficient to clearly display this command at the bottom of the plotting OPI? I am worried that people will ask us to alias more and more plotting commands and we will end up maintaining (and documenting) a custom interface to MPL.

**Comment by kjwoodsISIS** [comment]
In regard to Tom's response:
2. Would it be wise to increase the plot limit to 48?  Presumably the current limit is set at 6 for a reason.  If we increase it to 48, do we risk encountering performance problems?  Have we tried creating 48 plots?  Would 12 or 24 be an acceptable limit?
3. Agreed - we should not be creating a customer interface to MPL.  Could we have a "Clear All Plots" button on the OPI?

**Comment by Tom-Willemsen** [comment]
2. We had already done and tested this - see linked ticket. It looks like it was missed on CRISP. When we tested it, it did not appear to cause an issue. Indeed, browsers other than internet explorer don't impose a limit at all. I think the maximum which internet explorer could support is 128, but we selected 48 as a "sensible" limit.
3. No, the matplotlib "clear plots" command must be run from the same python session that created the plots, so we can't do this easily from the OPI. However we can make the command more obvious. Currently it is documented [in the user manual](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Matplotlib) and there is a button to open that documentation from the OPI - I suggest putting some of the most commonly used commands on the OPI directly.

**Comment by ThomasLohnert** [comment]
Displaying the command (in a clearly visible way) on the OPI might be good enough if we don't want to go down the alias route.

In any case, 1. would be a better solution to the problem. 2. and 3. just mitigate the cost of having to close the plots manually. If we make 1. work that would by itself be an acceptable solution to the problem in my opinion as the user just does not have to worry about the number of plots at all, making 2. and 3. somewhat redundant / nice to have.

**Comment by ChrisM-S** [comment]
Yes I agree, (1.) is simpler as the number of connections is set on the NDX machines is set to 48 but is unlikely to be set on any another remote client installation.  As well,  it might be worth considering making it a visual a metaphor of a "palette" of (six) visible plot areas, side by side where the new ones appear and overlay the space where older ones were located (I'm not sure where the new plots are placed currently - on the IBEX Client window or free floating).   The plots could then either rotate to the next free window or scroll across as a new one is added at the front.

The benefit of doing this is that it is immediately obvious to the user that the plots are going to get overlaid (as the connections are re-used) and the vanishing of the last plot will not surprise the user (they could then do a screen capture if needed).

If more than one trace can be put on the plot, it might also be more efficient on connections this way.

Just some thoughts!

**Comment by John-Holt-Tessella** [comment]
Code to add to Scans library:

```
def create_new_figure():
    import matplotlib.pyplot as plt
    fignums = plt.get_fignums()
    elif fignums > MAXIMUM_FIGURES: 
        plt.close(fignum[0])
    fig, axis = plt.subplots()
    plt.show()
    return fig, axis
```

replace scans ln 155 with fig,axis=create_new_figure()

**Comment by DominicOram** [comment]
+1 from ZOOM, just got a support call about it. They were happy to have only 6 plots if they have to but would prefer if a new plot replaced one that was already there. I have increased it to 48 on NDXZOOM for now but something more sustainable would be good.

**Comment by DominicOram** [comment]
Running `pyplot.close('all')` also failed to close the plots. I had to kill the python process running the matplotlib backend.
