### ISSUE TITLE
Reflectometry: Multiple Parked Positions

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4309]
As a CRISP scientist, I would like to be able to define more than one parked position on a component. The specific use case is that the point detector is in the way of the multi detector on CRISP, i.e. if the multi detector is in use, we want to park the point detector in a high position for a low theta and in a low position for a high theta.

Check whether this is actually needed anywhere else or if this is just an edge condition on CRISP before picking up this ticket.

**Comment by ThomasLohnert** [comment]
Needed on other reflectometers too.

**Comment by ThomasLohnert** [comment]
Perhaps a good solution would be to expand the "inbeam" parameter to have a list of states rather than a binary choice, like `IN BEAM`, `PARK  HIGH`, `PARK LOW` etc. as this could be useful in a lot of cases (e.g. `PARK LASER` for https://github.com/ISISComputingGroup/IBEX/issues/4289)

**Comment by John-Holt-Tessella** [comment]
This is just in beam an dout of beam parameter but the multiple park positions are in the config as value < x.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/283
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/313
