### ISSUE TITLE
Reflectometry: Stop synchronising some axes (Piezo motor speeds)

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4310]
As an instrument scientist, I want to stop some of my axes synchronising their motion by changing their velocities so that motors that cannot have velocity changed (e.g. piezo), or motors that are very slow (e.g. super mirror) don't get included in the motion.

### Acceptance Criteria

1. Motors which have no sychronisation setting in the config change their speed to synchonise ending their moves together
1. Motors with synchonrise setting as `False` do **not** have their velocities change
1. Motors with synchonrise setting as `True` do have their velocities change

### Notes
Changing speeds as we do for synchronizing moves in reflectometry is not as straight forward as setting a velocity PV for piezo motors. Instead, this involves changing variables in a potentially fairly complex equation which calculates the motor speed based on a variety of factors.

Talk to Ian Johnson about how you would go about changing the speed of piezo motors. Should then be implemented as a PV wrapper subclass in the reflectometry IOC.

**Comment by John-Holt-Tessella** [comment]
Do we know this to be true or is this what CRISP instrument scientist thought might be true?

**Comment by ThomasLohnert** [comment]
This came from a conversation with @KathrynBaker and @DominicOram

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/211

**Comment by John-Holt-Tessella** [comment]
Add IOC System Test
