### ISSUE TITLE
Reflectometry: 3848 - 1 Change PVs to Action from Move

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4322]
As a developer, I want to capture the set pattern used for moves in and use it for all future things of this type. The current pattern needs to be adjusted to comply. This is the pattern for enabling a stop button see web page (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ISIS-PV-Guide)

Acceptance Criteria

1. PVs ending in :MOVE  are :ACTION
1. PVs end in SP_NO_MOVE end in SP_NO_ACTION

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/217
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/221
- https://github.com/ISISComputingGroup/ibex_gui/pull/932
