### ISSUE TITLE
Mercury Cryostat: Flow Cryostat

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4324]
As a scientist on POLREF/OFFSPEC/ZOOM I want to be able to interact with the ISISSTAT in the same way as on SECI

**Acceptance Criteria**
1. There is the same set of information/control information as in the `Mercury - Crysotat + Level` VIs

**Notes**
1. This may be needed on ZOOM before the conversion of OFFSPEC or POLREF is undertaken - if there is not enough time to do this in a suitable fashion then create a separate ticket to hack the MercuryCryo IOC to look at the above VI instead of `Mercury - Cryostat` and include the extra variables
1. The discrete functions may require different IOCs - this analysis has yet to be undertaken, and so the best solution is still to be confirmed

**Comment by DominicOram** [comment]
Fixed in https://github.com/ISISComputingGroup/IBEX/issues/5546
