### ISSUE TITLE
Reflectometry: Repeat blind tests

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4326]
Provide support for repeating acceptance test on Crisp.
Tests repeated during week of 1st July - 5th July. Slightly more than the 2 days effort put in.

### Acceptance Criteria

1. Tests are done
1. Tests are written up

**Comment by John-Holt-Tessella** [comment]
Day 1: Afternoon setup SECI with two blocks (si-gold with protective layer and Silicon). Run the measurements. We are looking at where the critical edge and fringe occur. These seem from initial results to be a bit wrong but as long as they match with IBEX we are good.

**Comment by John-Holt-Tessella** [comment]
Waiting for scientific analysis

**Comment by kjwoodsISIS** [comment]
No further review required.  No longer impeded.
