### ISSUE TITLE
genie_python: Allow get current wiring table

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4330]
As a scans library developer, I would like to get the current wiring table in use by the DAE using genie_python so that I do not need to change to it if it has not changed.

### Notes

Currently, you can set the wiring table, get a list of available wiring tables but not set it. The PV `%MYPVPREFIX%DAE:WIRING_FILE` contains the filename. (Updated after comment below)

### Acceptance Criteria

1. `g.get_wiring_table()` return the current wiring table
1. `g.get_wiring_table()` return None if no wiring table is set
1. `g.get_wiring_table()` raises PVDoesNotExist exception if ISISDAE IOC is not running

**Comment by FreddieAkeroyd** [comment]
You will not need to parse the XML - they are already available as PVs e.g.

get_pv("IN:LARMOR:DAE:WIRING_FILE")
get_pv("IN:LARMOR:DAE:DETECTOR_FILE")
get_pv("IN:LARMOR:DAE:SPECTRA_FILE")

**Comment by ThomasLohnert** [comment]
Fixed as part of https://github.com/ISISComputingGroup/IBEX/issues/3688.
