### ISSUE TITLE
CONFIG: Make description field longer and allow commas

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4334]
As a SANDALS instrument scientist, I want the description field to be longer and allow me to include punctuation so that I can add notes about the configuration that I can refer to in the future.

### Acceptance Criteria

1. Users have a way of recording longer (~256 characters) messages associated with a description which include punctuation, which can be associated with a configuration or component.

**Comment by DominicOram** [comment]
Length seemed arbitrary. Limit was first added in the client >6 years ago, there is no corresponding server limit. I suspect at the time this was added the mechanism for setting/reading descriptions was going via EPICS string PVs and so was limited but now we're using JSON/waveforms I see no reason to have a limit at all.

**Comment by DominicOram** [comment]
(Special characters were fixed in https://github.com/ISISComputingGroup/IBEX/issues/5144)

**Comment by JamesKingWork** [comment]
Is there a PR for this?
