### ISSUE TITLE
GUI: Add IOC dialogue box doesn't allow mouse-wheel scrolling

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4340]
As above.  Nor does it allow jumping to an IOC using the first letter of its name.

This should behave in the same way as the start/stop IOC box.

**Comment by ThomasLohnert** [comment]
Seems to work fine for me? We are talking about the dialog below, right?

![image](https://user-images.githubusercontent.com/18398579/59365159-f8e13980-8d2f-11e9-8f96-50ee789cabaa.png)

**Comment by davidkeymer** [comment]
My mistake.  I've just checked using a local client and the dialogue behaves as I would expect.  I think I may have noticed the strange behaviour during either a remote desktop or VNC session and assumed it was a 'feature'.
Suggest no further action.
