### ISSUE TITLE
waitfor_move throws an exception when trying to find the severity of the motor

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4343]
From manual system test 20-2:

Given that there is a block called `a` pointing at `...:MOT:MTR0101.RBV`, running `g.cset("a", 0);g.waitfor_move("a")` should move a motor to position zero and wait for it to get there. Instead, it throws an error because an internal function got the wrong number of arguments.

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/163
