### ISSUE TITLE
IOC: Danfysik Reset Interlocks

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4348]
As an instrument scientist using a Danfysik I want to be able to reset the interlocks in the same way that I can on the Riken Danfysik (#4091). It is critical that the RICKEN Danfysks and normal Danfysks are kept in sync.

Acceptance Criteria

1. Remote reset of interlocks is possible on single com Danfysik 
1. All functionality on Ricken Danfysiks are reflected in normal Danfysiks and vice versa

**Comment by DominicOram** [comment]
Part 1 basically just involved removing a script on the OPI that hid the reset button on "normal" Danfysiks. I moved towards doing part 2 by harmonising the tests in the IocTestFramework between normal danfysiks and RIKEN ones
