### ISSUE TITLE
Galil: default to QR

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4351]
As a developer i would like the galil to default to QR on ethernet, this is to avoid issue raised in #3935 until a better solution is found

**Comment by FreddieAkeroyd** [comment]
To test: 

previously a +ve poll period would result in a UDP handle being created on the galil, after change QR will always be used. a message about "Requested synchronous poll " should be seen in log

**Comment by FreddieAkeroyd** [comment]
It would be nice to be able to test homing,

**Comment by kjwoodsISIS** [comment]
Added completed label (it was forgotten when moving the ticket to the Review Completed column in the IBEX Project Board).
