### ISSUE TITLE
VESUVIO: Deploy Release 5.4.0

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4357]
VESUVIO is currently still down due to the cabin having to be rebuilt, but it will be back online shortly before cycle 19/1. Deploy IBEX release 5.4.0 to the instrument once it comes back up.

**Comment by ThomasLohnert** [comment]
Finished deploying and hotfixed #4393.

**Comment by DominicOram** [comment]
Looks good!

**Comment by kjwoodsISIS** [comment]
0 points because, technically, it was done in the previous sprint.
