### ISSUE TITLE
MUSR: genie BEGIN fails with "LabVIEW: Memory is full" messasge

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4367]
As as user, when I load a script and type BEGIN I get an endless loop of labview "memory is full" errors.  See below
![image](https://user-images.githubusercontent.com/3035405/58485296-a9114880-815b-11e9-9f8d-4ddfd2c426e4.png)

LabVIEW is only taking up ~500MB and there is no sign  of real memory exhaustion on the system in 64 bit space.  The largest service entries are Sophos and another generic service at around 550MB (components as shown below)

svchost.exe                   2140 AudioEndpointBuilder, Netman, PcaSvc,
                                   SysMain, TrkWks, UmRdpService, UxSms,
                                   vmickvpexchange, vmicshutdown, vmicvss

**Comment by ChrisM-S** [comment]
Restarting SECI appeared to fix this.  LabVIEW memory dropped down to about half of what it had before.

**Comment by KathrynBaker** [comment]
It looks to me like one of the LabVIEW queues was full, rather than system memory, and restarting SECI would restart LabVIEW and clear the problem.

A quick google of the number and I see comments about string lengths in print functions and excel tab renaming.

**Comment by ChrisM-S** [comment]
Thanks @KathrynBaker, maybe things have just accumulated during the shutdown. I will close this.  Possibly also some rubbish came back from the DAE into a string which upset something and after the BEGIN all will be OK now.
