### ISSUE TITLE
SANS2D & LOQ: IOC and OPI for T-jump Cell

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#4370]
As a scientist on LOQ or SANS2D, I want IBEX to support the T-jump cell on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. I can control the T-jump cell via the IBEX GUI
1. I can control the T-jump cell via genie_python
   * the ability to script experiments using this cell is important.
   * check how OpenGENIE is currently used to script the cell (ask the scientists for a copy of the script).
1. The IBEX solution provides _at least_ the same functionality as the current SECI solution.
   * compare the functionality provided by the current IBEX solution (#3175) and the current LabVIEW solution (see note 2 below).

#### Notes
1. A limited "quick & dirty" solution for controlling the T-jump cell was created for LARMOR (see #3175).  For LOQ & SANS2D we should create a more polished IOC and OPI.  When implemented, this solution should be able to supersede #3175.
1. A SECI/LabVIEW solution for the T-jump cell has also been created.  Refer to [ControlsWork #403](https://github.com/ISISComputingGroup/ControlsWork/issues/403) for details.

**Comment by KathrynBaker** [comment]
Is this related to the small ISIS project (813) that is in my list (and I’m not sure if it is progressing), or the Keithley solution that was used rather than the apparatus that was condemned as unusable? If it is the latter, how does this differ to 3175 – or is it actually just a better description of 3175?

**Comment by Kevin-Woods-Tessella** [comment]
@KathrynBaker - we should probably discuss to see whether this ticket and small project 813 are one and the same.

**Comment by kjwoodsISIS** [comment]
After discussion with Kathryn, we decided that small project 813 is a separate issue (if and when the new T-jump apparatus proposed in 813 gets built, we can create a new IOC and OPI).  This ticket refers to the existing T-jump apparatus ("the Keithley solution").

**Comment by KathrynBaker** [comment]
This has been superceded by the imminent arrival of the new T-Jump
