### ISSUE TITLE
SANS2D: IOC and OPI for Rotating Stirrer Rack

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#4371]
As a SANS2D scientist, I want IBEX to support the rotating stirrer rack on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. I can control the rotating stirrer rack via the IBEX GUI
1. I can control the rotating stirrer rack via genie_python
1. The IBEX solution provides the same functionality as the current SECI solution (see note 2 below).

#### Notes
1. The rotating stirrer rack does not use a Galil to drive the motors.  It uses a  TTi PL-P PSU instead.
1. A SECI/LabVIEW solution for the rotating stirrer rack already exists.  Refer to [ControlsWork #553](https://github.com/ISISComputingGroup/ControlsWork/issues/553) for details.
   * See also `C:\LabVIEW Modules\Drivers\TTi PL-P Series` and `C:\LabVIEW Modules\Drivers\TTi PL-P Stirring Stages`
1. See also #3278 - Gareth may have created a suitable IOC already.

**Comment by Tom-Willemsen** [comment]
Check labview solution to verify what is happening

**Comment by Adam-Szw** [comment]
Could someone help point this ticket for me

**Comment by Adam-Szw** [comment]
VI can't be found so Im going to put it back to ready for now

**Comment by Adam-Szw** [comment]
PRs:
ibex gui (opi): https://github.com/ISISComputingGroup/ibex_gui/pull/1391
ioc support: https://github.com/ISISComputingGroup/EPICS_ROTSTIRR/pull/1
ioc master: https://github.com/ISISComputingGroup/EPICS-ioc/pull/667
EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/276
wiki page added: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Rotating-Stirrer-Rack

Tests included in ioc support (run_tests.bat)

**Comment by daryakoskeroglu** [comment]
taking the under review label off this as I have issues with GUI and connecting it to IBEX server
