### ISSUE TITLE
LOQ: galil support

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4373]
Support and investigation relating to power failure on LOQ. 

- Both limit switches showing as active from software
- Both limit lights off when looking at the actual galil crate
  * on very old galil crates both lights off can mean both limits engaged (?)
- Can send messages from PC to galil and it responds as expected

@KathrynBaker and I got electronics group involved after some initial diagnostic steps, looks to have been a failed power supply of some description (which did not kill the controller itself, but did kill the motors and limit switches). Electronics will swap the part.

**Comment by KathrynBaker** [comment]
In the end, the 24V PSU was replaced, the on-off switch was replaced (it was a little dodgy), and the PSU for the Galil was upgraded. After all that, and a restart of the IOC, everything seems to be happy.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by KathrynBaker** [comment]
The 24V power supply had failed, and it looks like the 5V from the Galil was also no longer being passed through. Various bits are being swapped, including potentially the Galil PSU.

**Comment by KathrynBaker** [comment]
0 – it was maybe all of an hour including walking to and from LOQ a few times between two of us. That might be in part my experience to know what I’m looking at that I see this as not at all complicated.
