### ISSUE TITLE
configchecker: test for having multiple instances of same ioc in a configuration

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4374]
Vesuvio have a configuration which contains 2 `EUROTHRM_02` iocs. 

The configchecker should fail this.

**Comment by adamb56789** [comment]
This task is also part of this ticket: https://github.com/ISISComputingGroup/IBEX/issues/4202.

**Comment by adamb56789** [comment]
Don't merge this until https://github.com/ISISComputingGroup/IBEX/issues/4540 is done, otherwise the Jenkins check will always fail and we might miss other issues.

**Comment by davidkeymer** [comment]
Moved to impeded as this ticket needs #4540 to complete first.
