### ISSUE TITLE
ZOOM: caen support

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4375]
As a scientist on ZOOM I have moved some detectors to a different slot on the CAEN, this uses a different board.

Our driver rejected this new board because it checks the board id. The board IDs we support are all 4 digits long. The new slot claimed to have a board ID of 39 million (which our driver then refused to load DB records for).

Need to talk to detector group to figure out what is going on.

**Comment by John-Holt-Tessella** [comment]
The board has since been configured and they can now see the channels they wanted.
