### ISSUE TITLE
Sample parameters lost on upgrade

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4378]
The sample parameters were moved from `INSTETC` to the `ISISDAE` ioc. Consequently, the autosaved values were lost.

**Comment by FreddieAkeroyd** [comment]
Thank you for writing the restore script @John-Holt-Tessella - i checked which instruments were using the relevant parameters and ran it on just them, as far as i can tell only GEM, LOQ, OSIRIS, SANDALS and VESUVIO are using beamline parameters. Others e.g.  LARMOR and ZOOM use sample parameters, but they change these on a per experiment basis.

**Comment by John-Holt-Tessella** [comment]
We have run several cycles since this; scientists would have asked if it was a problem.
