### ISSUE TITLE
POLARIS 4079-1: Change component name for Mk3 chopper

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4381]
As a user I want my chopper component to match its hardware. Currently the component is named Mk2 Chopper, I would like this to be renamed to Mk3 Chopper. The configurations in which the chopper configuration is used in will need to be updated to reflect this change.

### Acceptance criteria:
 - [x] Chopper component is renamed to Mk3 Chopper
 - [x] All configurations which use this component are updated.

**Comment by Alistair-McGann-Tessella** [comment]
See also: https://github.com/ISISComputingGroup/IBEX/issues/4079

**Comment by aaron-long** [comment]
The components have been updated, but the device screens show a MK2 chopper OPI. Should this also have been changed?

**Comment by Alistair-McGann-Tessella** [comment]
It probably should have been changed, but the synoptic is the more important OPI as that will be used more by the instrument scientists, and this has been updated to a MK3. I don't think it's a serious issue that the device screen hasn't changed.

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella - actually, I think we should be consistent in our terminology.  Instrument scientists might be OK (they'll know the history), but users could be confused.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by John-Holt-Tessella** [comment]
Sorry the icons were meant to mean, whopps I didn't see that and I have now fixed it; but I think it looks more like it is ok look I don't need to put points on it.
