### ISSUE TITLE
DAE: Stuck in WAITING state

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4383]
At startup, we saw an issue on MERLIN where the DAE was stuck in a waiting state despite no blocks being outside of runcontrol limits, which prevented them from collecting data. The IOC log shows messages like
```
[2019-06-04 08:46:31] Out of range PVs: 
```
which suggests it believes that PVs are outside of run control limits, except the list is blank.

A restart of the `RUNCTRL` IOC fixed the issue, but we should look into how it got into this state in the first place.

Meanwhile I have updated the [DAE troubleshooting page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting).

**Comment by Tom-Willemsen** [comment]
I believe this issue has been seen before on SANDALS, see also https://github.com/ISISComputingGroup/IBEX/issues/4215

**Comment by FreddieAkeroyd** [comment]
The overall OUT:CNT and both the overall and individual PV INRANGE status is logged to the archive, it would be interesting to see how they tally. I think it will print a blank "out of range PVS" when it thinks it has gone back in range,  so something is certainly amiss

**Comment by Tom-Willemsen** [comment]
+1 LET - although restarting the RUNCTRL ioc was not enough, we had to manually kick a block into and out of runcontrol for the ICP to notice the change.

`IN:LET:CS:RC:OUT:LIST` was empty and `IN:LET:CS:RC:INRANGE` was `YES` but the ICP was still waiting - I think the ICP must have missed an update to the PV?

**Comment by ChrisM-S** [comment]
Random thought, is there any chance this was linked to the 49 day timer issue? (i.e. the ICP timer for checking run control status could have stopped).

**Comment by Tom-Willemsen** [comment]
I don't think so as all PVs were/are scanning normally.

**Comment by KathrynBaker** [comment]
This is certainly a bug/situation that is now in the past, closing this ticket, reopen it if is is still needed.
