### ISSUE TITLE
POLARIS: Fix T0 chopper communications

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4386]
As a POLARIS user/instrument scientist I want to be able to control my T0 chopper. This is a Mk3 Chopper. The chopper is reading back a 0Hz, even when the chopper is spinning.

### Acceptance criteria

- [ ] Frequency, phase, phase error and direction are all read back correctly from the chopper
- [ ] Frequency, phase, phase error and direction can all be written to the chopper

**Comment by Alistair-McGann-Tessella** [comment]
Config file has been changed. We're waiting for feedback from the instrument scientists to confirm that this has fixed the problem.

**Comment by Alistair-McGann-Tessella** [comment]
A Polaris instrument scientist has got back to us. They're happy that the IOC is behaving as expected, so changing the URL in the configuration file seems to have fixed the issue.

**Comment by Tom-Willemsen** [comment]
Note: there is a separate ticket to correctly report the comms errors here: https://github.com/ISISComputingGroup/IBEX/issues/4388
