### ISSUE TITLE
IOC: Mk3 Chopper Remote start, stop, park and unpark

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4389]
As a POLARIS instrument scientist I would like to be able to remotely park, unpark start and stop my Mk3Chopper so that I don't have to go down to the chopper main controls.

*Requirement for starting the ticket* chopper group need to be asked to extend the functionality of the chopper dll to include functions. They may or may not be able to do this.

### Acceptance Criteria

1. User can remotely start the chopper
1. User can remotely stop the chopper
1. User can remotely park the chopper
1. User can remotely unpark the chopper
1. User can tell the start/stop status
1. User can tell the parked/unparked status

### Notes

 This is not done very often so does not need to be high priority.

**Comment by Kevin-Woods-Tessella** [comment]
The intent of this ticket appears to contradict Tom's comments on Slack:
https://ibex-icp.slack.com/archives/G0ARPHT40/p1559652940004600?thread_ts=1559639299.001800&cid=G0ARPHT40

tomwillemsen: 04/06/2019 13:55:40
For info: a MK3 cannot be stopped, started or parked remotely according to @david. This is a hardware limitation.

tomwillemsen: 04/06/2019 13:57:41
It can *only* be done from the physical front panel (remember to put it back in remote mode afterwards)

**Comment by Tom-Willemsen** [comment]
As per Kevin's comment above, I do not think this is possible with current versions of the MK3 chopper. 

If it is needed functionality, I think we would probably need to ask chopper group to add these extra functions to the remote dll (assuming that it's actually possible on their end).

**Comment by John-Holt-Tessella** [comment]
I will document this on the MK3Chopper page and close this ticket.

**Comment by Tom-Willemsen** [comment]
👍 from Polaris (again), chopper group was copied on the email

**Comment by John-Holt-Tessella** [comment]
We should not drive this change. There is a note on the wiki (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MK3-Chopper#user-control) to this effect. I am closing this ticket.

**Comment by Tom-Willemsen** [comment]
Chopper group have responded to the email with justifications about why start/stop is not implemented in the MK3 systems. See  `\\isis\shares\isis_experimental_controls\Ticket4389` for some justification notes from chopper group.
