### ISSUE TITLE
GUI: genie_python IPython autocomplete not working

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4391]
As a LARMOR instrument scientist, I have noticed that autocomplete in ipython no longer works for load script. This is an essential feature for me; fix it or downgrade by version on ipython.

### Acceptance Criteria

1. There are tests
1. For both python console and scripting in the GUI
    1. <TAB> is a tab
    1. g<TAB> shows completions for g
    1. g.<TAB> shows genie python completions
    1. g.load_<TAB> completes to load_script
    1. for both g.load_script("c:\ and load_script("c:\ show files in c:\
    1. <TAB> expands to scripting dir
    1. "<TAB> either expands to scripting dir or does nothing
    1. "C:<TAB> shows files/dir in c:
    1. "C:\<TAB> shows files/dir in c:
    1. "C:\scr<TAB> shows files/dir starting with scr in c:\
    1. "C:\scripts<TAB> does nothing
    1. "C:\scripts\<TAB> shows files/dir starting in c:\scripts
    1. "C:\scripts\pl<TAB> completes to c:\scripts\play shows all file
    1. "C:\scripts\play<TAB> display file
    1. "C:\scripts\play.<TAB> completes to c:\scripts\play.py shows .py and .pyc
    1. "C:\scripts\play <TAB> completes to c:\scripts\play - fun.py
    1. "C:\scripts\play -<TAB> completes to c:\scripts\play - fun.py

c:\Scipts should have files 'play.py' 'play.pyc' 'play - fun.py' 'notplay.py'

### Notes

The autocomplete function is no longer provided by completer (I think) it looks like the newer way to do this is using a module see https://ipython.readthedocs.io/en/5.x/config/integrating.html#tab-completion.
I will have a quick play to see how feasible it is to swap to this.

**Comment by Tom-Willemsen** [comment]
Does this only apply to autocomplete for paths as an argument to load script, or is autocomplete broken more generally (e.g. for method calls)?

**Comment by John-Holt-Tessella** [comment]
Only applies to autocomplete paths of load script.

**Comment by DominicOram** [comment]
All good, I'll leave it up to you to fix on the relevant instruments.
