### ISSUE TITLE
SUPPORT: OSIRIS Filter movement 

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4392]
Filter motor is not moving to top of range, investigate.

**Comment by John-Holt-Tessella** [comment]
Stop due to soft limit violation.

Email sent:

>We have just been supporting the move of the filter on OSIRIS to the top of its range. The movement was stopped just short of the correct position. The reason this happened is because the motor and encoder became out of sync and the solution to this would be to home the axis to resync them. To fix the issue we did the equivalent of a manual home; but in a more inaccurate and error prone way.
>
>To give a bit more depth to this:
>•	The motor position is recorded as the number of steps sent to the motor; this can deviate from the actual position because of missed pulses or inaccurate moves.
>•	The encoder position is recorded as the number of steps read from the motor drive; this can deviate from the actual position because of stalls in the encoder or dirty encoder steps. The encoder steps are what is reported as the position by the software.
>•	To ensure that the motor does not travel too far there are soft limits set within the controller. It will stop at these limits if the motor steps go beyond the range of the soft limit. In the OSIRIS’s case the soft limits were before the desired position because the motor and encoder were out of sync.
>•	When a motor is homed the encoder and motor steps are both synced to a specific place; ideally this is a home switch but it can be a limit switch.
>
>In general using soft limits is a good thing because it will stop the motor if the encoder fails. Also if you home the axes regularly but are still finding that the encoder and motor get of step you can predict failures of motor/encoder and get them replaced.
>
>In summary we recommend that we come and set up a homing routine for you and that you run this roughly once a cycle.


Documentation updated: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting#the-axis-will-not-move-a-message-gets-put-in-the-log-of-move-begin-failure-axis-x-after-xxx-seconds--decelerating-or-stopped-by-fwd-limit-switch-or-soft-limit-fl

**Comment by FreddieAkeroyd** [comment]
Is this the same as #2947 and requires setting  {motor}_MOT_ENC_SYNC_TOL_SP to a small non zero value?

**Comment by John-Holt-Tessella** [comment]
It is the same but for a non-absolute encoder I am unsure that it is appropriate to sync the two because they should always be in sync and them not being in sync shows a problem.

**Comment by ChrisM-S** [comment]
It would be really useful to know about this difference between the motor steps view of the world and the expected “real” position when it occurs gradually or when it occurs suddenly (for example when an encoder has lost power or possibly the Galil too has lost power).

Is it possible to have these values at least recorded in the log and also (possibly) compared with previous ones at some regular point – like the start of a move?  I understand that neither Galil steps or Resolver counts are absolute, but a change in the relationship should be detectable by having a log/record of both values.  A slight drift one way or other might happen +ve or –ve in a move forwards or backwards but simply having the numbers would allow some analysis and particularly a warning if the relationship has changed or is changing particularly asymmetrically?

**Comment by DominicOram** [comment]
@ChrisM-S Yes, we don't archive these things currently but it would be trivial to do so. The problem is that due to space constraints on the NDX and a rather dumb logging system we log a lot less than we could and it's quite hard to get data out that's over a cycle old. We have some ideas to improve this https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Data-Generation-and-Storage

**Comment by FreddieAkeroyd** [comment]
A warning is printed to the log file when a resync is done, but something could be done to alert on a differenece. The question is how much of a difference is a problem. I had a feeling we were resyncing in two places, ZOOM and IMAT? One case was an absolute encoder, the other was just an axis with issues.

**Comment by John-Holt-Tessella** [comment]
We should start logging the motor steps but at a really low resolution like 1 per minute. This would probably be enough to see any large differences, but not produce us too much data.

**Comment by FreddieAkeroyd** [comment]
Or just log the difference between motor and encoder?

**Comment by ChrisM-S** [comment]
Yes, it’s probably only worth logging (for this purpose) when the scaled difference gets beyond a delta (jiggling around a bit is probably not an issue). Or at say 1% of range, 10% of range – a bit like a nagios warning/error level?  i.e. not logging the difference but just logging as an error when it becomes a warning or error (maybe at that point with the differing values for reference).  That would be almost costless as a logging issue.

For a relative setup the auto resync option is probably something we should make impossible as it would essentially be an automatic home without reference! but we could interpret the delta difference as a “re-home needed n% positional error detected” and display on the OPI.  Might encourage the adoption of homing buttons…

**Comment by Tom-Willemsen** [comment]
Moving back to rework, as it looks like this ticket needs either:
- Further work doing as part of this ticket to address some of the points in comments above
- An appropriate new ticket writing to capture the points above

**Comment by John-Holt-Tessella** [comment]
OK Ticket created for it #4449
