### ISSUE TITLE
SUPPORT: Runcontrol does not work for certain PVs

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4393]
Run control has stopped working for methane temperature on sandals. If you change the limits the DAE does not pause, other run control settings do generate a pause.

### Acceptance Criteria

1. A PV outside the limits of run control cause the DAE to go into a waiting state
1. With multiple PVs any one of those PVs causes the DAE to go into a waiting state
1. Fix is released to all full instruments except Rikenfe and Muonfe (they don't use run control)
1. There is a test which tests run control

### Notes

The only part of this ticket left is to write the test. As below it should be written against 2 blocks one from simple IOC and the Methane temperature. The test with Methane temperature should be skipped if the PV does not exist. There should also be a test for two blocks pointing at the same PV. There should be a test for two blocks pointing at the sam PV which are identical apart from the last character.

**Comment by John-Holt-Tessella** [comment]
This has been reproduced on DEMO using the blocks:

![image](https://user-images.githubusercontent.com/7570055/58957629-dd5ab980-8798-11e9-9c00-ffdd92bd9a96.png)

For Meth2 changing the bounds of run control makes the cross appear but the DAE doe not stop collecting data. For MethanTemp it does the correct thing.

The cause appears to be `record(waveform, "$(PV):RC:_OUT")` which can not read the name from the PV. It is generating `IN:DEMO:CS:SB:MethanTemp:RC:_IN 2019-06-05 12:02:33.933869  LINK INVALID` on a camonitor. This then is blank when adding it to the set of out of range pvs.

**Comment by FreddieAkeroyd** [comment]
Can you confirm which block works - the above says"MathanTemp" works, but it seems to be the block  that is mentioned as having an invalid link? Is it the name of the block or something about the order/number of blocks that causes the issue?

**Comment by John-Holt-Tessella** [comment]
Release procedure:

1. Copy file from "\\isis\inst$\Kits$\CompGroup\ICP\Releases\TicketXXX_runcontrol_fix\ioc\RUNCTRL\db" to "EPICS\ioc\master\RUNCTRL\db"
1. Restart the run control
1. Note change on IBEX page

**Comment by FreddieAkeroyd** [comment]
Is this only an issue for blocks pointing at PVs such as moderator temperatures? I think they do not have the long string NAME$ field as the IOC there is old.

**Comment by John-Holt-Tessella** [comment]
Maybe I will have a look.

**Comment by FreddieAkeroyd** [comment]
With regard to Meth2 and MethanTemp blocks above, if two blocks point at the same PV then you may get funny behaviour as the underlying PV name is used as the key.

**Comment by Tom-Willemsen** [comment]
Impeded until we do https://github.com/ISISComputingGroup/IBEX/issues/4416 .

This was discussed at length with @FreddieAkeroyd and @John-Holt-Tessella , the solution for this ticket will be much easier in EPICS 7, and we are unlikely to be able to patch this on instruments before the end of cycle anyway. Effort spent fixing this bug under pure EPICS 3 would be wasted, we feel.

A quick check of instruments with block names longer than 20 characters threw up the following: LARMOR, DEMO, IRIS, IRIS_SETUP, ENGINX_SETUP, POLARIS, VESUVIO, ENGINX, MERLIN, SELAB, GEM, LOQ. We think this is too many instruments to shorten block names on. The configchecker code for this check is on branch `Ticket4393_check_block_name_length`.

**Comment by FreddieAkeroyd** [comment]
I think EPICS 7 extended link support will help us "The const link type is almost equivalent to the old CONSTANT link type with the updates described below to accept arrays and strings, except that there is no need to wrap a scalar string constant inside array brackets since a constant string will never be confused with a PV name." https://epics.anl.gov/base/R7-0/2-docs/links.html

But i need to test this...

**Comment by Tom-Willemsen** [comment]
We are now on EPICS 7; this issue is no longer impeded.

**Comment by John-Holt-Tessella** [comment]
Closing it looks like this is done. I have created a ticket #5215 to capture the possible need.
