### ISSUE TITLE
Merlin: TPG300 stops communicating every cycle on startup and the port needs to be moved [Tasks: Shutdown]

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4395]
As a supporter, I would like to not have to keep fixing the MERLIN TPG300 by moving ports back and forth on the MOXA each cycle (probably after the TPG300 in the rack has been powered off and on again).

### Acceptance Criteria

1. Find the cause of the issue probably by switching the device on and off. The cause may be hardware flow control.
1. The reproduced issue is no longer triggered
1. The solution is considered in the context of other devices and tickets made

### Notes

The issue may be flow control because the MERLIN TPG IOC implements _purely_ software flow control so there is no chance the MOXA port can become deadlocked in what is probably a hardware handshake deadlock triggered by raised/unacknowledged hardware flow control signals.  This can be checked by seeing that the MOXA ports shown when connected say "OFF" "OFF" "OFF" instead of ON in the hardware control columns shown in ticket #3527 

The TPG only reads vacuum gauges over long time periods so even if there was the occasional dropped value as the result of this change there would be a benefit as the lockup of the port is a real nuisance.  This solution may well benefit any other situations where apparently "software flow control" equipment is being interfered with by hardware flow control signals being set by the asyn based IOC.

**Comment by FreddieAkeroyd** [comment]
@ChrisM-S  You mention that "MERLIN TPG IOC implements purely software flow control", did you mean something other than xon/xoff as this is enabled in the IOC st.cmd ?

**Comment by FreddieAkeroyd** [comment]
Fixed by #4435 ?

**Comment by aaron-long** [comment]
Tasks: Test TPG300

**Comment by ChrisM-S** [comment]
I'm happy shelve this one (and have removed it from pending tasks for the moment). After @FreddieAkeroyd's comment about the solution bing in #4435 and the issue did not happen during this cycle.

**Comment by John-Holt-Tessella** [comment]
We did not upgrade Merlin this cycle so the fix is not on MERLIN. However I am also happy to consider it done. Especially if it does not come back after we upgrade MERLIN this shutdown.
