### ISSUE TITLE
SUPPORT: RB Number are not being pushed to instruments

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4402]
RB numbers not being pushed to instruments. Resolution: the process was not started on controls machine and it was not configured to start on restart. 

### Acceptance Criteria

1. RB Numbers are being pushed to all instruments
1. Service is setup to start on a reboot
1. There is some way to tell on a daily basis that RB numbers are not being pushed 
1. Service is well documented on the wiki

**Comment by DominicOram** [comment]
1) I have updated the [populator](https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/pull/1) and the [database users](https://github.com/ISISComputingGroup/EPICS/pull/171) to fix the underlying errors
2) Service is now running as cronjob so will be run on reboot
3) I can't think of a great way to do this `SELECT UPDATE_TIME FROM information_schema.tables WHERE table_name='experiment';` can be run as `report` but it will only show if the data has actually changed and most of the time when this is run it will not change the data.
4) I've improved the documentation on the wiki at (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Experimental-Database).

**Comment by John-Holt-Tessella** [comment]
3. We could:
    - write an item to the database declaring the error status
    - get the service to send us an email if it fails
    - get linux to monitor that it runs correctly and send us an email

**Comment by DominicOram** [comment]
Pulled out Nagios stuff into separate ticket.
