### ISSUE TITLE
Jasco VI: report error when underlying IOC in in comms/timeout alarm

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4403]
As an instrument scientist using the Jasco 4180 VI (which is a CaLab wrapper), I would like an error to be reported via the usual SECI mechanism if the underlying pvs are in comms alarm.

**Comment by davidkeymer** [comment]
Notes for reviewer:
* VI now checked back in to SourceSafe (`\LabVIEW Modules\Drivers\Jasco PU-4180 HPLC Pump`).
* I used the IOC, Emulator & OPI from ticket #4401 during development and testing (unmerged at the time).

**Comment by Tom-Willemsen** [comment]
Works as expected when the connection between the IOC and the emulator is broken.

When the connection between the IOC and the VI is broken, the VI gets stuck in an infinite pop-up loop and can only be recovered by forcibly restarting the entire vi.

**Comment by davidkeymer** [comment]
Pop-Up error boxes can be supressed by deselecting the two `Enable Automatic Error Handling` options in the `Block Diagram` section of the main LabVIEW options.  This has been done on all of the instrument machines, but probably not on most of the developer machines, hence the above review comment.
Once this has been done, the VI recovers automatically from a disconnection from the IOC.
As part of this ticket, I have also addressed some of the issues in #4425.
