### ISSUE TITLE
Jasco: hide certain parameters on an "advanced" panel

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4404]
As an instrument scientist using the Jasco, I do not want the following parameters to be directly exposed to users:
- High pressure limit
- Low pressure limit

These parameters should be hidden on an "advanced" tab (or via some other mechanism which hides them from users but allows them to be accessed by scientists/support staff).

This change should be applied to both:
- [x] The OPI
- [x] The VI

**Comment by DominicOram** [comment]
I don't think this is worth doing on the VI now that it will 90% be used in IBEX

**Comment by RaiBishal** [comment]
OPI done in https://github.com/ISISComputingGroup/IBEX/issues/6551

**Comment by RaiBishal** [comment]
OPI done in https://github.com/ISISComputingGroup/IBEX/issues/6551
