### ISSUE TITLE
GUI: Log plotter didn't deal with BST

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4406]
As an IRIS instrument scientist I did not want the log plotter to lose its connection to the database because I was worried it was not collecting my data.

Reproduce

1. right click on block and plot it
1. only current data is shown, no historic data

developer investigation (quick)

1. Properties did not have an Archive data source and adding the default flashed up and then disappeared.
1. A new GUI had no problem finding the data
1. It was not clear how long the GUI had been up for or if it has been switched to look at a different instrument

**Comment by John-Holt-Tessella** [comment]
We think this is because the log plotter is getting data in UTC but the data is actually in BST.

Setting /uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterSettings.java
timezone to europe london then this is now a smooth change.

**Comment by Tom-Willemsen** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/896

**Comment by John-Holt-Tessella** [comment]
Installed via copying client not install client
