### ISSUE TITLE
LARMOR: stuck in "moving" state after removing SMC100 from configuration

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4409]
As an instrument scientist on LARMOR I am confused by the indication "motors are moving" when none of my motors are moving. My scripts also cannot continue because they contain `g.waitfor_move()` which won't return if the moving state is stuck.

After investigation, this looked to be a "ghost" moving state from an IOC which was no longer in the configuration (`SMC100_01`). I fixed this state by doing `caput IN:LARMOR:CS:MOT:_MOVING1.A 0`.

This ticket is to make sure that "ghost" moving states get cleared (e.g. by a periodic catch-up scan)?

**Comment by John-Holt-Tessella** [comment]
Same as #3158?

**Comment by Tom-Willemsen** [comment]
Yes, will close this as a duplicate of https://github.com/ISISComputingGroup/IBEX/issues/3158
