### ISSUE TITLE
JASCO: improve interaction on SECI instruments

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4410]
If the JASCO IOC is started at boot time, it can lock out the COM port required for e.g. the Knauer pump (as seen on POLREF). The JASCO Vi needs to control the IOC more directly, for example procServ counld not start the IOC and it was LabVIEW that sent the start command. The mechanism for stopping the IOC would need to be considered, this is easy of the "stop" button is pressed on the Vi but not if there is a "hard stop". A watchdog timer reset by LabVIEW might be one option e.g. the IOC will automatically stop if a counter reaches zero, after labview starts the IOC it will periodically reset this timer so if labview terminates the IOC will terminate itself automatically a short while afterwards.

**Comment by davidkeymer** [comment]
Just to confirm, on POLREF at least, the Jasco IOC is (always) started on running the IBEX server as it's present in the `startup.txt` file.  It also has a fixed comport specified in the `globals.txt` file.

**Comment by KathrynBaker** [comment]
90+% of all stops are hard stops, so this is not going to be an easy fix. We would have to make sure the IOC isn’t in an auto-restart mode.

One solution might be to stop IOCs as part of a SECI config change then on start of the VI, and periodically (on errors, or if we hit a race condition compared to the stop), as part of standard running the JASCO VI checks for the IOC, and starts the IOC if there are any issue.

Whether we have a way to add that stop to SECI I don’t know.

**Comment by FreddieAkeroyd** [comment]
Some instruments don't change config, they just start and stop Vis. What do reflectometers usually do? It may be a watchdog timer is the only way to make sure the IOC is stopped if the Vi is stopped. I removed the JASCO from startup.txt on POLREF, is wasn't present on INTER but is currently on OFFSPEC. If we leave it out of startup.txt we need the LabVIEW Vi to talk to either procServ or the PVS for PSCTRL to start the IOC if it is not running.

**Comment by John-Holt-Tessella** [comment]
Can we just get them to plug the Jasco into a port which is different to Knaur? We can give them a new moxa for this purpose. Then we don't have to do anything.

**Comment by ChrisM-S** [comment]
Normally we spend time solving hardware problems we shouldn’t be in software, this seems to be the converse…

**Comment by davidkeymer** [comment]
The consensus for the moment seems to be to assign different ports to the pumps, and have the Jasco IOC run permanently (but keep an eye on its log files).  This will be a short-term solution until a better one can be found (e.g. @FreddieAkeroyd's suggestion to have the VI control the running of the IOC).
I shall contact the appropriate instrument scientists to arrange reconfiguring the connections to the MOXA.

**Comment by FreddieAkeroyd** [comment]
Is the problem lack of moxa ports or only having one physical RJ45 connection near the sample and so it is easier to reuse the com port rather than change physical moxa port cable?

**Comment by davidkeymer** [comment]
I think it's just convenience!  Staff just have to remember that pumps always connect to the same port.
PS No replies from scientists yet.

**Comment by Alistair-McGann-Tessella** [comment]
The solution here is to enforce using a different port for the JASCO and Knauer pumps, David has updated the wiki page accordingly:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/JASCO-PU--4180-HPLC-Pump#connection-details
