### ISSUE TITLE
Update to EPICS7

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4416]
As a developer I would like to run EPICS 7 to access the newest features and also avoid technical debt.

Notes: as EPICS 7 includes epics 3 and epics 4 in a new directory structure, adjustments to the IBEX build system may be required. This will include removing our existing EPICS 4 installation and adjusting link on all IOCs using EPICS4, but may extend wider.
  
Acceptance criteria:
- all IOCS build and tests pass
- run control is modded to allow the PV names to be a waveform and initialised by the block PV name. See #3647 and #4393

**Comment by FreddieAkeroyd** [comment]
Preparation work in #4599

**Comment by JamesKingWork** [comment]
Should we remove EPICS 7 from our unupdated dependencies?
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Unupdated-dependencies

**Comment by FreddieAkeroyd** [comment]
seeing we have now updated it, yes
