### ISSUE TITLE
Build: add RELEASE.local support

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4417]
EPICS now supports RELEASE.local and new template files automatically include RELEASE.local from a parent directory. As per recent tech-talk messages, module owners are encouraged to update their modules to support this scheme for eacie use at other facilities. We should update out IOCs and build rules to comply. 

This should be done after #4416

**Comment by KathrynBaker** [comment]
`release.local` has more than 450 code hits in our github organisation, I'm not sure that we can easily tell which repos have this or not at this time, but most may well do. Closing, but feel free to reopen if this is still valid.
