### ISSUE TITLE
ZOOM: support for cryogenic kit

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4421]
As a scientist on zoom I want to talk to various cryogenic kit: ITC, IPS, ILM, Neocera.

Problems:
- IPS and ILM com ports were set the wrong way round (resolution: swap in configuration)
- ILM COM port was stuck (resolution: move to different physical port on moxa)
- Neocera was not patched to MOXA (resolution: Move the Neocera to a different wall port which is patched to the moxa)

**Comment by Tom-Willemsen** [comment]
Tried to diagnose "stuck" com port with @FreddieAkeroyd and @ChrisM-S today. 
- It appears that the low-level windows API call to `ReadFile` is hanging, despite being called with timeout(s)
- We wrote a minimal test program in C++ that reproduced this behaviour (to eliminate the complexity of asyn, streamdevice, etc). This did run into exactly the same issue.
- hterm is able to talk successfully using the "stuck" port. It is not clear whether it uses windows' `ReadFile` API or some other driver to access the port.
- The physical state of all hardware lines is the same between hterm in it's working configuration and EPICS using "disable" flow control mode.
  * This was checked using a hardware serial line "sniffer" which just shows whether each line is high/low/inactive
- Based on the above, we suspect something at the nport/windows layer may be causing us problems.

**Comment by kjwoodsISIS** [comment]
Thanks for the update.  The conclusion suggests to me that we should investigate the  behaviour of the nport/windows layer in a separate ticket.  Do you agree?

**Comment by Tom-Willemsen** [comment]
Yes, I think that is sensible.

We do not yet know whether this has overlap with https://github.com/ISISComputingGroup/IBEX/issues/4420 , the symptoms are different but it might or might not be the same underlying problem.

**Comment by DominicOram** [comment]
This was long ago and I don't think there's much more to learn
