### ISSUE TITLE
Deploy: Install release for Cycle 2019/02

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4423]
Release the new version of IBEX to needed machines.

#### Instruments
- ALF
    - [x] Started
    - [x] Finished
- EMMA-A
    - [ ] Started
    - [ ] Finished
- ENGINX
    - [x] Started
    - [x] Finished
- ENGINX_SETUP
    - [x] Started
    - [x] Finished
- GEM
    - [x] Started
    - [x] Finished
- HRPD
    - [x] Started
    - [x] Finished
- IMAT
    - [x] Started
    - [x] Finished
- INES
    - [x] Started
    - [x] Finished
- IRIS
    - [x] Started
    - [x] Finished
- IRIS_SETUP
    - [x] Started
    - [x] Finished
- LARMOR
    - [x] Started
    - [x] Finished
- LET
    - [x] Started
    - [x] Finished
- LOQ
    - [x] Started
    - [x] Finished
- MAPS
    - [x] Started
    - [x] Finished
- MARI
    - [x] Started
    - [x] Finished
- MERLIN
    - [ ] Started
    - [ ] Finished
- MUONFE
    - [x] Started
    - [x] Finished
- OSIRIS
    - [x] Started
    - [x] Finished
- POLARIS
    - [x] Started
    - [x] Finished
- RIKENFE
    - [x] Started
    - [x] Finished
- SANDALS
    - [x] Started
    - [x] Finished
- SELAB
    - [x] Started
    - [x] Finished
- SOFTMAT
    - [x] Started
    - [x] Finished
- TOSCA
    - [x] Started
    - [x] Finished
- VESUVIO
    - [x] Started
    - [x] Finished
- ZOOM
    - [x] Started
    - [x] Finished

#### Mini instruments (for JASCO) - delay for now

- CRISP
    - [x] Started
    - [x] Finished
- INTER
    - [x] Started
    - [x] Finished
- OFFSPEC
    - [x] Started
    - [x] Finished
- POLREF
    - [x] Started
    - [x] Finished
- SURF
    - [x] Started
    - [x] Finished

#### "Special" deployments

- NIMROD - delay until all devices are supported
    - [x] Started
    - [x] Finished
- SXD - delay until attocube work is complete
    - [x] Started
    - [x] Finished

#### Notes
1. Need to create new release about 3 weeks before Cycle 2019/02 to give scientists sufficient time to test it.

**Comment by DominicOram** [comment]
SXD will need a mini-inst to run the new attocube.

**Comment by Tom-Willemsen** [comment]
Email sent to "standard" instruments

- Not yet NIMROD as they are getting a separate release
- Not yet SXD as I think work may be ongoing on the attocube driver?
- Not yet Reflectometers as the jasco has not gone through yet

**Comment by ThomasLohnert** [comment]
Fixed duplicate IOCs on LARMOR, deploy anytime **after** 28/08.

**Comment by Tom-Willemsen** [comment]
OSIRIS were trying to do quiet counts but their DAE has been hanging. This sounds like potentially the same issue that IRIS had at the beginning of last cycle.

I suggested to Franz that we can try upgrading IBEX to see whether that resolves his DAE problem - he is happy for us to do a deploy anytime today.

**Comment by John-Holt-Tessella** [comment]
@Tom-Willemsen has done the deploy and it looks good (although only tested on short notice).

**Comment by Tom-Willemsen** [comment]
Release 5.6.0 is now available on the share with support for:
- MKS gas panel (NIMROD)
- Oerlikon centre-one (NIMROD)
- Edwards turbo instrument controller (NIMROD)
- Jasco (CRISP, SURF, OFFSPEC, POLREF, INTER)
- Attocube (SXD)
- Beckhoff (CRISP)

These instruments can now be deployed to.

**Comment by John-Holt-Tessella** [comment]
Not dong MERLIN or EMMA because we didn't have access.
