### ISSUE TITLE
IPS: non-persistent mode should trigger a warning

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4426]
As a cryogenics technician, I want the IPS user interface to warn the user if non-persistent mode has been selected. Non-persistent mode being selected causes the cryostat to use significantly more helium than persistent mode (due to the switch heater being on?).

Acceptance criteria:
- Red warning text appears on the OPI if non-persistent mode is selected

> Warning: running this magnet in non-persistent mode can cause it to use liquid Helium at a greater rate than normal. Please only use non-persistent mode if you understand the implications.

Notes:
- The *option* to run in non-persistent mode should remain accessible, as it may be useful in specific circumstances. This ticket is just to provide a warning, not to disable the functionality.

**Comment by DominicOram** [comment]
Should changing non-persistent mode also only be available in the advanced pane?

**Comment by Tom-Willemsen** [comment]
Yes, that would be fine (as long as "advanced" users can still get to it when necessary).
