### ISSUE TITLE
GUI: OPIs slow on start

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4428]
As a user I would like the GUI to be responsive. When I open an OPI it is quite slow, this should be as fast as possible. Note:

* It is ok that the first time I ever open any OPI is slower than usual but opening new OPIs after this should be fast
* Scripts are known to slow down OPIs, this ticket is to speed up all OPIs, not just those with scripts
* It appears opening OPIs in vanilla CSS is faster so this should be possible

First step is to profile an OPI load.

**Comment by Tom-Willemsen** [comment]
See also some discussion here https://github.com/ControlSystemStudio/cs-studio/pull/1198

**Comment by Tom-Willemsen** [comment]
OPIs are quite significantly faster after e.g. https://github.com/ISISComputingGroup/IBEX/issues/7212#issuecomment-1204023497, and we now start the GUI on the web links perspective which mitigates some of the "first OPI to be opened" issues into part of startup.

Hard to say whether the above has "completely" solved this issue (how much performance improvement is enough?), but for the moment I am inclined to close until we get more user requests about it.
