### ISSUE TITLE
LOQ: Take image of ORDELA detector control PC disk

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4429]
An image of the HDD of the ORDELA detector control PC should be taken as a backup, to create a virtual machine should the hardware fail, and potentially assist with the decoding of the communications protocol.
This will be done on the upcoming maintenance day (19/06/2019).
See ticket #3544 for full details.

**Comment by davidkeymer** [comment]
An image was taken and with the assistance of @ChrisM-S, successfully booted as a VM within the Hyper-V Manager.

**Comment by DominicOram** [comment]
Is there any plan to move over to using a VM now? Can you write some information up on the wiki about this please? Some questions that come to the top of my head about it:
* Where is the image stored?
* How do I know if the image is running as expected?
* How do I restart the image if required?

Basically, how can I support this if I get a call about it?

**Comment by davidkeymer** [comment]
Those are fair questions and I don't know the answers to them until I've spoken with the instrument scientist (who's currently away for a few days).

This is not as simple a problem as we first thought because the PC (Win7) that runs the detector control program also has a DAQ card which independently monitors detector parameters.  If this PC has to stay because of this card, then it might as well also continue to run the control program.  In which case, the VM we created is only a backup.

However, if this card can be replaced with something less reliant on a PC (cDAQ?), then the control program no longer needs to be run on a dedicated PC.  We could then either use the VM and a MOXA to control the detector or create an IOC to replicate its functionality (which was the original point of this and ticket #3544).

Both options (if Win7 has to remain on the machines after September 2019) would require the system to be isolated on a private (instrument?) network, probably in the same way as the Astrium chopper VMs are currently.

As you can see, there are various scenarios as to how this system could be run depending on the software and hardware requirements.  Hopefully all will be revealed when I've got some more information.

**Comment by davidkeymer** [comment]
Impeded until more information gathered.

**Comment by davidkeymer** [comment]
After meeting with the instrument scientist, it was decided the first thing to try is running the various functions of the current physical PC on an equivalent Windows10 machine.  This would satisfy the ISIS requirement to remove all Windows7 machines by September 2019 as well as prolong the life of the machine by running with newer hardware.

If this worked, then no further development would be required as the instrument scientist would be happy with the current level of functionality.  If not, then various options are available and would be discussed at the time.

**Comment by DominicOram** [comment]
Great, thanks @davidkeymer. It sounds like that work should probably be done as a separate ticket, can you write one up please?

**Comment by davidkeymer** [comment]
I've created a ticket in "Controls Work" as this task no longer involves IBEX.

https://github.com/ISISComputingGroup/ControlsWork/issues/633
