### ISSUE TITLE
genie python: white text on white background 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4433]
Genie python appears to default to white text even if the background is white, this is an issue if the default console cmd background has been changed. Could it use the default console foreground colour or query the background colour and adjust accordingly? Issue reported on IMAT running genie_python.bat

**Comment by Tom-Willemsen** [comment]
The solution to this (which is just to change the console colours to something visible) is already in the upgrade script:

https://github.com/ISISComputingGroup/ibex_utils/blob/f787b8b870ffa6ac462df4f085c1a1976d839e34/installation_and_upgrade/ibex_install_utils/install_tasks.py#L967

**Comment by kjwoodsISIS** [comment]
You can change the **_default_** cmd console colours:
1. right-click on the window title bar
1. choose Defaults from the pop-up menu
1. select the Colours tab from the dialog
1. choose your preferred colour combination
1. start a new cmd console (the defaults don't apply to the current console)
It's a 30s job!  Much quicker than changing genie_python.  It should resolve Winfried's problem (at least until someone else changes the defaults again).

**Comment by FreddieAkeroyd** [comment]
Indeed, but do we need to rely on the default console colours being white on black? I find black on white is easier on the eyes. We can try and mandate white on black on an instrument, but genie_python can be installed and run on a scientists desktop too. We could probably change the colour in genie_python.bat but it just seems strange that we can't use the default foreground and background?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - I may have misunderstood.  Are you saying that genie_python _actively_ sets the foreground colour to be white?  If so, then I tend to agree - genie_python should simply use the default foreground and background colours.

**Comment by FreddieAkeroyd** [comment]
@kjwoodsISIS genie_python doesn't change the colours, it appears to assume they are a certain way which leads to white on white. If it were to set them it that would solve the immediate issue, but I'm not sure why it can't use the existing defaults?

**Comment by kjwoodsISIS** [comment]
That sounds bizarre.  Why should genie_python even care about the colours?  The colours are properly the concern of the environment (i.e. the cmd console).

**Comment by ChrisM-S** [comment]
With my aged eyes, I'm a black on white person, but as it stands, the whole client is black on white(/grey) currently.  What we should take notice of is what things look like when we use the high contrast options so there is definitely something inconsistent with the Genie python window if you set the "High contrast black" theme! Apart from the selection on the LHS of the client (where the text vanishes) and Genie Python, most things seem to reverse quite well - which I guess means that most things in CSS/Java respect the defaults.

**High contrast black**
![image](https://user-images.githubusercontent.com/3035405/59674271-dda47d00-91ba-11e9-9705-cdc50748f782.png)

**High contrast white**
![image](https://user-images.githubusercontent.com/3035405/59674341-0593e080-91bb-11e9-9986-acffbdb687c1.png)

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - we are talking about the Windows cmd console (not the entire IBEX UI).

**Comment by ChrisM-S** [comment]
Ah, yes, I read the footprints note from IMAT afterwards!  (although the above doesn't look to be the correct behaviour).

However, just checking, in the version of GENIE python I have on my test machine Python `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]` the python console appears to select the colour intelligently from the "screen text" colour in the console on startup.  It does seem keep the colour until it is restarted though (is it possible that they changed the terminal colour but didn't restart GENIE python?).

**Comment by kjwoodsISIS** [comment]
Can we close this ticket?  I think we have an effective workaround.

**Comment by Tom-Willemsen** [comment]
Yes.
