### ISSUE TITLE
ASYN: re-implement WIN32 serial driver to avoid port lockup

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4435]
The current ASYN serial implementation uses synchronous I/O on Windows, while this is a perfectly valid approach it seems to be unable to handle stuck serial ports such as #4421 where further testing indicated that the ReadFile() function never returned even though a timeout had been specified. 

The hTerm program appears to still work in these cases, it is probably using either one or both of:
- Overlapped I/O
- Responding to events via WaitCommEvent()

The asyn driver should be changed to use this approach.

Acceptance criteria:

- asyn driver re-implemented and passes tests on available devices
- initially old code left and a flag provided to switch behaviour from synchronous to asynchronous at IOC startup
- simple read/write command line program created that can be used to test a stuck port (which could them be tried on an existing instrument stuck port before this is rolled out more widely)   

Spun out ticket #4436 which will create a test program

**Comment by Tom-Willemsen** [comment]
Could we use the VISA asyn serial driver instead, or will that also be calling `ReadFile` under the hood?

**Comment by FreddieAkeroyd** [comment]
VISA probably uses ReadFile(), but may use it with overlapped io - difficult to know without testing.

With above PR you can now set a COMM event mask via e.g.

    asynSetOption("L0",-1,"eventmask",5)

See windows SetCommMask documentation for valid values. The overlapped IO should now mean that dbior will not hang when a port hangs and give more details.

I will create a new top level build, to try on an instrument with a hung com port you would need to:

- stop IOC concerned
- copy asyn.dll from Ticket4435 build to same directory as .exe for IOC (so it will load in preference to existing asyn.dll)
- start IOC
- when done, remove new asyn.dll

**Comment by FreddieAkeroyd** [comment]
asyn.dll will be built by asyn_ovio jenkins job, file can then be copied from workspace of this job

**Comment by ChrisM-S** [comment]
I have a copy of MTTTY.exe which may be worth running against an existing stuck port to see if it reads.  It’s an example piece of code from the MSDN including overlapped reads etc. it’s probably not as good as “hterm” but from the way the interface looks it could be where hterm was developed from and provides a model/benchmark for reference in compileable form (and can be compiled with debug if necessary).

**Comment by FreddieAkeroyd** [comment]
The above PR will build a testSerialPort.exe program that can be run against a stuck port (once IOC is closed) to test read/write and also report port settings and current status of hardware control lines etc

**Comment by FreddieAkeroyd** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TestSerialPort for docs on TestSerialPort command

**Comment by FreddieAkeroyd** [comment]
See also https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Serial-Port-Debug

**Comment by FreddieAkeroyd** [comment]
Looks like using overlapped IO and waiting for bytes to become available before a read worked on above MARI stuck COM port.
