### ISSUE TITLE
NICOS: console window repeatedly appearing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4440]
Reported on IMAT - a back background console kept popping up once in a while, but recently a few times per minute. This looked to be from the NICOS script server, as they are not using it i terminated NICOS on IMAT for the moment.

Investigate why this is happening

**Comment by FreddieAkeroyd** [comment]
See #4511

**Comment by DominicOram** [comment]
Sorry, I missed this when I created the other ticket, I'll close this one as a duplicate as the other contains a bit more info.
