### ISSUE TITLE
MySQL: service does not auto restart

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4444]
The MYSQL service recovery action is not set to auto-restart, the service stopped on IMAT and resulted in values not being logged. A nagios warning was sent but not seen immediately. The service was restarted manually later in the evening. 

Follow up: auto-restart needs enabling on all instruments

**Comment by Tom-Willemsen** [comment]
Have used PS remote to enable autorestart on all instruments this morning.

PR for deploy script: https://github.com/ISISComputingGroup/ibex_utils/pull/39

**Comment by DominicOram** [comment]
Queried the failure settings on a cross section of instruments and confirmed that they are now correct.

**Comment by kjwoodsISIS** [comment]
How many points?
