### ISSUE TITLE
EUROTHERM: crash when no calibration file read

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4447]
find_calibration_range_impl() does not check it has read lines from a file before using the vector, so if no file was read this results in a crash when lines[0] is referenced

To reproduce:
* Rename `C:\Instrument\Apps\EPICS-DEBUG2\support\ReadASCII\master\example_settings\Default.txt`
* Start the IOC e.g. `%PYTHON3% run_tests.py -t eurotherm -a`
* Confirm IOC crashes

**Comment by FreddieAkeroyd** [comment]
Function is in https://github.com/ISISComputingGroup/EPICS-utilities

**Comment by FreddieAkeroyd** [comment]
On file rename i see
```
[2022-08-03 12:50:38] ReadASCII: File Open Failed: C:/Instrument/Apps/EPICS-DEBUG2/support/ReadASCII/master/example_settings/Default.txt: No such file or directory
```
but it doesn't seem to crash for me at the moment!

**Comment by FreddieAkeroyd** [comment]
There are some tests of the c/c++ code in https://github.com/ISISComputingGroup/EPICS-utilities/tree/master/utilitiesApp/tests but none for the find_calibration_range_impl function, which takes an asub record as argument. We could:
- either refactor to allow it to be more easily tested
- or create a dummy aSub record to pass as done in https://github.com/ISISComputingGroup/EPICS-webget/blob/master/webgetApp/src/webget_tests.cc

**Comment by Scott-James-Hurley** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7309
