### ISSUE TITLE
IOC: Log difference between motor steps and encoder steps

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4449]
As an instrument scientist, supporter and motor support I want to be able to see the difference between motor steps and encoder steps so that I know if my encoder/motor is becoming unreliable. The difference should be logged in the archive. If it appears the motor and encoder are out of sync this needs to be flagged as an alert to instrument scientists.

This should probably be a calc record which records the difference between MOT:MTR0101.RMP and MOT:MTR0101.REP. 

### Acceptance criteria

1. Record added to galil
1. Record added to motor record
1. Record archived only change at 1s max (to avoid filling the archive)
1. Instrument scientists are alerted if the motor and encoder appear out of sync.

### Notes

I think this is different to DIFF and RDIFF.
There is some code in galils which calculates this so it can be reset but we would like this for all motors

**Comment by ChrisM-S** [comment]
As in #4392, at (3) also consider values set (MDEL or ADEL?) so that after calculating the difference, only significant variation of values is logged.  It might be that faster logging at the point values diverge is useful? but logging the same number every second is wasteful.  Also would autosaving the difference be important to ensure the error is accumulated?

**Comment by FreddieAkeroyd** [comment]
The "1s max" will mean that at most 1 value will be logged per second, but only if it has changed. If values accumulate at a faster rate they are lost. The value should not need to be autosaved as it can always be calculated appropriately from the hardware.

**Comment by FreddieAkeroyd** [comment]
A difference will be calculated during motion, but a value will only be logged when motion is complete (DMOV=1). If this is still too much we can set ADEL
