### ISSUE TITLE
SUPPORT: LOQ: Veto confusion

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4451]
Support call from LOQ, vetoing with no run control issues (I pointed IS to the veto tab on the DAE page), and it seemed that the SMP (Chopper) is vetoing the data, and is continuing to do so intermittently.

Checked with @davidkeymer that I was correct and this scenario is a physical connection, which it should be.

IS who was local contacting will try one of the other ISs for more info, instinct that this would need to involve DAE/Chopper types

**Comment by KathrynBaker** [comment]
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Key-Concepts-in-IBEX#vetoes

Already exists to cover this scenario.

**Comment by DominicOram** [comment]
Documentation covers the scenario, may be worth a follow up email to point the IS at the documentation but at your discretion.
