### ISSUE TITLE
IPS: send remote mode before every write command and provide warning for clamped state

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4452]
As a scientist using the IPS-based cryomagnets, I would like the following two behaviours to be implemented:
- Send "remote & unlocked" mode before every write command in the IPS and ITC503 IOCS. This means that the scientists don't have to remember to explicitly put the device into remote mode. This has been checked with cryogenics and is acceptable.
- If the "activity" of the IPS reports "clamped", put the record into a MAJOR state alarm and display a warning text on the OPI:

`The magnet is currently clamped. IBEX is unable to set fields when the magnet is in this configuration. Please let your local contact know in the first instance, and they will request help from cryogenics section.`

Notes:
- Both of these solutions have been discussed with LET scientists (heaviest magnet users so far) and cryogenics section, and have been agreed as acceptable.

**Comment by kjwoodsISIS** [comment]
Confirmed in meeting with scientists & Cryogenics section - 24/06/2019, 11:00 AM.

**Comment by JamesKingWork** [comment]
To review:

- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/52
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/231
- https://github.com/ISISComputingGroup/EPICS-Itc503/pull/3
- https://github.com/ISISComputingGroup/EPICS-IPS/pull/6
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/425
- https://github.com/ISISComputingGroup/ibex_gui/pull/953

Note: These haven't been tested against hardware yet

**Comment by DominicOram** [comment]
Very minor changes suggested in tests. Also, we tend to use title case for branch names i.e. `Ticket4452_...`. Obviously extremely minor point but git bash is case sensitive so took me a minute to find the branch.
