### ISSUE TITLE
SUPPORT: SANDALS: Add Eurotherm component to Config

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4453]
Phone call received about adding a Eurotherm to the existing configuration. Talked IS through checking for the component, which they had, with a little moral support they added the component to the configuration. (configuration = superstick_julabo_oil_bath)

**Comment by KathrynBaker** [comment]
There is plenty of information on how to do this, this really was a case of providing moral support as most of the 'work' was undertaken whilst walking across site.

**Comment by DominicOram** [comment]
Sandals still running with specified configuration, all seems to be fine.
