### ISSUE TITLE
LARMOR: Set up new beamstop

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4460]
As a user on Larmor I would like to be able to control my beamstop. The design has changed quite dramatically from the original one outlined in https://github.com/ISISComputingGroup/IBEX/issues/2486. It is now a single axis device being controlled by a pre-existing galil. The requirements for this are:

- The axis is commissioned into IBEX (@IainJohnson may help with some of the commissioning)
- An OPI is designed for the device (in discussion with the instrument scientist on what they want)
- Remove code for controlling the original design

The device will (hopefully) be installed in the 2019 summer shutdown. The lead engineer to contact for this is Nick Webb.

**Comment by kjwoodsISIS** [comment]
What exactly is needed?
Is this just commission a Galil axis?  Or is there more to it?

**Comment by DominicOram** [comment]
As specified in the acceptance criteria above the following is needed:
* Commission a standard galil single axis
* Have an OPI, one of the generic axis ones may be fine for this but we should check
* Remove old code related to the more complicated design

This is all there is to it so I agree that 1 day is fine, it may even be 0.5

**Comment by John-Holt-Tessella** [comment]
Awaiting info from motion

**Comment by DominicOram** [comment]
@IainJohnson will give us a ring when this is going in. Should be sometime this week.

**Comment by DominicOram** [comment]
Everything installed @IainJohnson kindly did the set up for us. He's going to confirm with Rob that he's happy then we can call this done.

**Comment by DominicOram** [comment]
@IainJohnson has put some notes about the hardware at http://www.facilities.rl.ac.uk/isis/Motion/Operations/Equipment%20Notes.
