### ISSUE TITLE
SURF: TTIEX355P test and migrate Analog_Digital_IO Script 

### ISSUE THREAD

**Issue by SophieKSTFC** [ISISComputingGroup/IBEX#4463]
As a surf instrument scientist I want to be able to control the TTIEX355P psu through my analog_Digital_IO script. 

This work was originally part of  [#3784](https://github.com/ISISComputingGroup/IBEX/issues/3784) but the script could not be located. Mario was contacted but no reply was received. This ticket requires that: 

- [ ] The script is found and analysed.

- [ ] We check to see if the functionality is needed. 

- [ ] If this script is needed, migrate the features into genie python.

**Comment by aaron-long** [comment]
Spoke to M, he has never used the script, however he noted AH uses it and will know where it is kept. He said that it is something that they would like to have available.

**Comment by GRyall** [comment]
Not clear this script is still required. Given time that has passed, closing until re-requested.
