### ISSUE TITLE
Jenkins: concurrent builds

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4475]
Through two EPICS builds cannot run at the same time (due to directory limitations), there is no reason why a python and gui build couldn't run together.

The Jenkins lockable resources plugin may solve this by just locking EPICS builds

https://stackoverflow.com/questions/36454130/how-do-i-prevent-two-pipeline-jenkins-jobs-of-the-same-type-to-run-in-parallel-o

**Comment by FreddieAkeroyd** [comment]
Lockable resources added - see "lockable resources" on Jenkins overview page. jenkins build updated to add extra stages so deployment and cleanup can be run in parallel (only build needs to be locked). Genie python is now installed locally in each epics build workspace. The number of concurrrent executors has been increased on each node

**Comment by FreddieAkeroyd** [comment]
See also #4486

**Comment by Tom-Willemsen** [comment]
The Jenkins builds have now been running concurrently for a little while with no major issues. I am calling this complete.
