### ISSUE TITLE
Pydev console: search history

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4477]
As an instrument scientist on LARMOR (Rob) I would like to be able to search my command history in the PyDEV console in the GUI.

In the standalone python console this works: press ctrl-R and then type a search string. I'm not sure if pydev has a way of implementing this functionality.

This feature request is currently low priority.

**Comment by John-Holt-Tessella** [comment]
This already works. If you type the command and press up it will match only matching lines or did he want a search which matches anything in a line?

**Comment by Tom-Willemsen** [comment]
Yes, the standalone one matches anything within a line, e.g. if he types `H2O` it will match `g.load_script("H2O.py")` if that is in the history. I think this is what Rob meant.

**Comment by ThomasLohnert** [comment]
This functionality exists (see updated documentation at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/The-Scripting-Console). I have sent Rob an email with instructions so calling this done.
