### ISSUE TITLE
GUI: Journal Viewer page number control is counter-intuitive

### ISSUE THREAD

**Issue by adamb56789** [ISISComputingGroup/IBEX#4479]
As a user I would expect the the buttons to change page in the journal viewer to be more intuitive.
![image](https://user-images.githubusercontent.com/17644409/60451665-7bb92e00-9c24-11e9-8ba4-5e815ff22ce8.png)
At the moment, you can change the page number by typing in the spinner or by clicking the arrows. The up arrow on the spinner moves to the next page, which is counter-intuitive as it decreases the run number, and because it does not feel natural. Instinctively, the buttons to switch pages would be left and right arrows. This also would not be dependent on the sorting direction, and is the standard (back buttons on web browsers, for example).
This would require re-implementing much of the functionality of the spinner while using separate buttons for changing page.

Acceptance criteria:
1. The page number spinner is replaced with something more intuitive.
2. Functionality is equivalent to the spinner.

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1183
