### ISSUE TITLE
OSIRIS: fix web dashboard exponential display

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4484]
Reported by Franz - required #4364 to be applied

**Comment by FreddieAkeroyd** [comment]
Franz says OK to restart IBEX on OSIRIS today

**Comment by FreddieAkeroyd** [comment]
OSIRIS updated

**Comment by Tom-Willemsen** [comment]
Web dashboard at http://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=OSIRIS now displaying sensibly in exponential notation for vacuum statuses etc.
