### ISSUE TITLE
SURF: Add SURF to instrument list

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4485]
Add SURF to instrument list

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/commit/bfaf28e071a96ab51ecdc0dd942ab5806ec43549

**Comment by aaron-long** [comment]
As per our discussion: Please update both SURF and CRISP to have the default `is_scheduled=True`.

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/220
