### ISSUE TITLE
SXD: Commission Goniometer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4488]
As a user on SXD I would like to be able to control my new goniometer. This is made up of a number of different stages:

* A mclennan stage for the rotation of the whole assembly
* A mclennan stage for the rotation of the sample assembly in an arc
* An attocube stage for the fine rotation of the sample (support for which has been added https://github.com/ISISComputingGroup/IBEX/issues/3854)

This is a ticket to commission all three of these axes.

Notes: 

- The attocube should only be movable between -180 and 180 to avoid collisions.
- SXD is current a SECI system. A mini-inst must be installed to cover the Attocube and a VI written as the user interface.

**Comment by davidkeymer** [comment]
VI successfully tested with simulated Galil axis as, to date, Attocube emulator is not fully implemented.
VI not tested with either Mclennan nor Attocube hardware.  Hopefully when goniometer device itself has been assembled, tested and commissioned, further software testing can be undertaken.

**Comment by DominicOram** [comment]
Works well in general minor niggles as discussed:
* The name of the axis at the top should be populated by the PV DESC field
* The units of the axis should be those from the PV EGU field
* The `enable set` and `enable initialise` are both off on start up but I am still allowed to set/initialise

**Comment by davidkeymer** [comment]
All review comments addressed and VIs retested.

Updated driver in SourceSafe: `\LabVIEW Modules\Instruments\SXD\SXD Goniometer\`

**Comment by DominicOram** [comment]
Rework done and all works with the caveat that you need to enable 3 axes in the Mclennan ini file, despite only having 2 Mclennan axes and the 3rd being the attocube. We should remember this when we come to commissioning with hardware. I'm moving this ticket into awaiting as I think we have done all that we can our end and now waiting on hardware.

**Comment by DominicOram** [comment]
The date of 12/02/2020 is now looking less likely due to hardware issues.

**Comment by DominicOram** [comment]
Date now TBD

**Comment by DominicOram** [comment]
Looks like this is going back to the drawing board. It may come back in some form but will not use the attocube. I will remove the attocube from our build but not delete the repository, it may be useful in the future.

**Comment by DominicOram** [comment]
See linked PRs, also updated docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Attocube

**Comment by DominicOram** [comment]
I'm not sure if it's worth removing the Labview code? @davidkeymer?

**Comment by FreddieAkeroyd** [comment]
Is it worth leaving the emulator?

**Comment by DominicOram** [comment]
It will all still be in git if we want to get it back.

**Comment by FreddieAkeroyd** [comment]
But you need to remember it is there and also find it later ... it is also not there for anybody outside of ISIS to use if they wish

**Comment by DominicOram** [comment]
Ok, lets keep the emulator
