### ISSUE TITLE
LET and MARI: spectra truncated

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4490]
It has been reported that spectra are truncated in the client live view,  this requires ISISDAE_MAX_NTC environment variable to be set for the ISISDAE IOC and also likely EPICS_CA_MAX_ARRAY_BYTES too

**Comment by John-Holt-Tessella** [comment]
Do we need to set these automatically on these instruments during start_ibex_server?

**Comment by FreddieAkeroyd** [comment]
They can be set in ISISDAE, its just that I think you transfer ISISDAE_MAX_NTC elements for every spectra so an unnecessarily large value is inefficient if not needed, but setting it higher for everybody would avoid it getting lost (which is i think is what has happened)

**Comment by FreddieAkeroyd** [comment]
It looks like this has been added to globals.txt on MARI and LET? So can be closed?

**Comment by Tom-Willemsen** [comment]
Yes.
