### ISSUE TITLE
MARI: unable to change DAE setting in GUI after DAE error

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4491]
Reported by Duc: if DAE settings are changed and an exception occurs, IBEX still thinks that the new parameters are ok and refuse to let you click on "Apply Changes" again. Is there a way for IBEX to catch the exceptions and then revert parameters back to the old settings which the hardware is actually using if an error occurs?

**Comment by John-Holt-Tessella** [comment]
A workaround would be to set it to a third value and set it back again or open a new client.
There is a ticket to fix this #3563. I think it needs naming better (I will do)

**Comment by GRyall** [comment]
Ticket exists to fix underlying issue. This is effectively a duplicate of that ticket.
