### ISSUE TITLE
MERLIN: DAE takes a long time to abort

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4494]
Had call from MERLIN that their DAE was taking ages to end runs. The data then looked very strange, and the ICP log was showing a lot of errors of the format 
`2019-07-04 09:33:04  (16) NeXusEventCallback: [Warning] (NeXusEventCallback<class DAE2DetCardPolicy>::allFrameCallback) Invalid DAE time value 4611686018427224319(offset 7.9027e+010 seconds) for frame 95`.

This seems to have been a hardware/wiring issue and was eventually resolved by the Electronics team.

The issue had already been flagged up the day before and communicated to Electronics and the Instrument Scientists, however it seems at the time this call came in, it had not been addressed yet and the scientist who had taken over MERLIN had not been informed.

**Comment by DominicOram** [comment]
Doesn't sound like there's much more we could learn from this, calling it done.
