### ISSUE TITLE
MAPS: spectra truncated

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4496]
Spectra won't display on MAPS correctly as they are running with many time channels

I think the following lines in the ISISDAE st.cmd fixes it (at least, they fixed it on my local setup):

```
epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES", 1000000)
epicsEnvSet("ISISDAE_MAX_NTC", 25000)
```

We need a more sustainable solution for this e.g. the DAE ioc calling cmd files in the settings area, like the GALIL.

**Comment by FreddieAkeroyd** [comment]
There is already a epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES",  "1500000") in the liveview.cmd loaded by isisdae st.cmd but maybe this is not defined early enough? Given it is larger than above it could just be moved earlier.

Would setting   ISISDAE_01__ISISDAE_MAX_NTC  in globals.txt work?

**Comment by Tom-Willemsen** [comment]
Also seen on LET (reported via footprints)
