### ISSUE TITLE
IOC Test Framework: Launch without running tests

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4499]
As a developer I would like to run up an IOC and emulator quickly and easily for a variety of reasons. Currently I can do this by:
* Run Lewis from command line then the IOC with correct macros (This is a faff)
* Create a dummy test in the IOCTestFramework that just sleeps for a while (Means commenting out all other tests and I can forget I put it in there)

It would be good if the IocTestFramework had a `no-tests` flag where it would boot up my emulator and connect an IOC to it and just run in that state indefinitely.

**Comment by RaiBishal** [comment]
@John-Holt-Tessella says he has started this in his current ticket

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/IBEX/issues/4131
pull request https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/232
