### ISSUE TITLE
Vesuvio: set up furnace pressure

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4501]
As an instrument scientist on Vesuvio I need a TPG26X configuring on vesuvio so that I can monitor the pressure in the furnace.

I would also like some help writing an instrument script to ramp the furnace temperature.

Required for 8am 5/7/2019

**Comment by Tom-Willemsen** [comment]
TPG26x set up on port 15 of Vesuvio's moxa (COM19) and block configured to read it.

Script tested on beamline with scientist present. It is in `vesuvio_routines.py`

**Comment by davidkeymer** [comment]
IOC and OPI (in Device Screen) reporting valid value.  Block reflecting this.

Script checked and discovered that there is a mixture of tabs and spaces throughout the indentation of the whole file.  However, the currently used Python interpreter (v2) allows for this as long as the indentation character is consistent within each block of code, which means that this script works.

It was decided not to correct this (although not technically an error) and to wait for the move to Python v3, whereupon very many scripts will break and this particular one will be fixed as part of that work.
