### ISSUE TITLE
SANDALS: GUI: Log Plotter not showing historic values

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4503]
SANDALS reported that the IBEX client was not showing historic values for current and newly created plots.

Archive database was checked (remotely using SQL Workbench) and shown to have past data and to be recording current values.

Cause suspected to be that detailed in #4406 (BST/UTC data timestamp) and outdated client version.

Issue resolved by copying client v5.4.1 to NDXSANDALS and swapping directory names.

**Comment by Tom-Willemsen** [comment]
Version 5.4.1 is on SANDALS. Not much more to review here.
