### ISSUE TITLE
Wiki Checker: Check page links are correct

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4507]
As a developer I would like the wiki checker to understand page links of the form:
```
[My Link](#Link)

...

<a name="Link"></a>
##### My Link #####
```

It should do two things for these links:
* Check that the link has a corresponding place to go
* Make sure we don't check the link against the spell checker

**Comment by Tom-Willemsen** [comment]
Note: part 1 of this was started ~18 months ago but was abandoned because we couldn't justify the time on it

See branch: https://github.com/ISISComputingGroup/ibex_wiki_checker/compare/link_checker?expand=1 . There may be a useful starting point there.
