### ISSUE TITLE
MIGRATE: 2985-1 SECI ->IBEX Galil Motor Direction

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4509]
As a developer, I want the motor direction (positive/negative) to be transferred correctly when migrating motors from SECI to IBEX. This is a subtask of #2985. 

Acceptance criteria:
- If `Negate motor direction` is checked for a motor in SECI, the output script sets `.DIR` to 1 for that motor.
- If `Negate motor direction` is not checked for a motor in SECI, the output script sets `.DIR` to 0 for that motor.

**Comment by KathrynBaker** [comment]
This was just done in the LabVIEW code, and is in source safe - it was a simple addition so no notes were added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI

**Comment by KathrynBaker** [comment]
The best way to test is just get the latest version from Source Safe and run it against a galil setup and see that it comes up with the expected outputs.

**Comment by KathrynBaker** [comment]
Consider testing #4233, #4234, #4509, #4510 and #4512 together
