### ISSUE TITLE
MIGRATE: 2985-1 SECI ->IBEX Galil Jog Acceleration

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4510]
As a developer, I want the Jog acceleration (`.JAR`) to be set to something sensible when migrating motors from SECI to IBEX. This property does not exist in SECI, so I'm not sure what this value should be. Perhaps it could just be set to the same value as `.ACCL`? 

This is a subtask of #2985.

**Comment by KathrynBaker** [comment]
Neither `JAR` nor `JVEL` are set. These are now set in the LabVIEW to the same as the move values after a brief discussion, as those standard values have enough confidence in relation to them.

The LabVIEW has been changed and updated in SourceSafe, and the text below was added to

```
Jog Values

Both JAR and JVEL are set to the same values as standard move velocity and acceleration
```

**Comment by KathrynBaker** [comment]
The best way to test is just get the latest version from Source Safe and run it against a galil setup and see that it comes up with the expected outputs.

**Comment by KathrynBaker** [comment]
Consider testing #4233, #4234, #4509, #4510 and #4512 together
