### ISSUE TITLE
MIGRATE: 2985-1 SECI ->IBEX Galil Soft limits

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4512]
As a developer, I want soft limits to be set correctly when migrating a motor from SECI to IBEX. Current behaviour is that SECI `User min / max` are set as `.LLM` / `.HLM`, while `Soft min / max` are ignored. This does not make sense e.g. in the case of reflectometers, where we want a limit on the (persistent) dial values, but not on the user values as we do not know what the offset etc. would be since axes in reflectometry get realigned constantly. In this case, SECI `Soft min / max` values should be used instead to set `.DLLM` / `.DHLM` in IBEX.

Since dial and user limits are linked in IBEX, we need to think about which one should win in case both are present in SECI.

This is a subtask of #2985.

**Comment by KathrynBaker** [comment]
Within SECI the `soft` values are the final values used so should always win, the following is what has now been added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI.

This has also been enacted into the LabVIEW which has been checked in to Source Safe.

```
Limits

The SECI user limits map to the drive limits for IBEX, and the soft limits to the other limits.
Where the soft limits are set, but the user limits are either set to infinity or 0, then the drive limits should be set to the same value as the soft limits
Where the soft limits are set to infinity or 0 then the limits will be set to 0 and a message added to the 'things to be aware of' part of the system
If the user limits are larger than the soft limits, but not infinite, then the soft limits will win as those are the final limits used within the move normally
```

**Comment by KathrynBaker** [comment]
The best way to test is just get the latest version from Source Safe and run it against a galil setup and see that it comes up with the expected outputs.

**Comment by KathrynBaker** [comment]
Consider testing #4233, #4234, #4509, #4510 and #4512 together

**Comment by John-Holt-Tessella** [comment]
Review:

- [ ] If an offset is set the limits are incorrect since HLM should not be the same as DHLM (I am unsure whether we are setting dial or user limits)
- [ ] If a negative value is set then the limits are incorrect since HLM should be -ve of DHLM (I am unsure whether we are setting dial or user limits)

It may be better just to set either dial or user limits whichever is correct (I am still not sure which is correct).

**Comment by KathrynBaker** [comment]
@John-Holt-Tessella and I had a conversation, came to the conclusion that we would just set HLM and LLM using the most appropriate value. The wiki page and VI have been updated to the latest version of this.
