### ISSUE TITLE
Reflectometry: OPI refactoring

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4519]
As a reflectometry scientist, I want the reflectometry front panel OPI to be easy to reconfigure for different beamlines, i.e. minimize the amount of hardcoded items. This brings the OPI more in line with the reconfigurable design of the beamline model in the reflectometry IOC.

Proposed changes:
- OPI should take a macro for no. slits and automatically populate VGAP / HGAP groups
- Important beamline parameters should be taggable as such (e.g. in the config) so that they automatically show up on the front panel

**Comment by John-Holt-Tessella** [comment]
Duplicate #5408
