### ISSUE TITLE
IBEX: Training (January 2020)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4522]
The next training courses are scheduled for the 31st January 2020. (~31st is only proposed, not yet confirmed~).

#### Acceptance Criteria
- [x] Select Date
- [x] Advertise training
- [x] Book venue
   - [x] CDF room in Atlas Centre has been booked
- [x] Assign trainers
- [x] Review course materials
- [x] Send delegate list to CDF
- [x] Send joining instructions to delegates
- [x] Book tea & coffee (but not lunch) as necessary
- [x] Set up machines
- [x] Deliver training
- [x] Apply retrospective changes to process/wiki/slides
  * See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
  * Updated documents in http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FTraining&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View=%7BF2C33C51-70E6-4343-B937-2C59A2568306%7D

#### Notes
1. Additional instructions for setting up training can be found here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
1. The courses are scheduled as follows:
   - 31st January 2020 (AM): Introduction to IBEX
   - 31st January 2020 (PM): genie_python with IBEX
These are two separate courses.  Delegates will be expected to purchase their own lunch.

**Comment by kjwoodsISIS** [comment]
Ask if anyone needs "Intro to Python".

**Comment by DominicOram** [comment]
Bumped into Jamie Nutter, he suggested it would be a good idea to invite some of Operations along too.

**Comment by John-Holt-Tessella** [comment]
Stuff done for install:

- https://github.com/ISISComputingGroup/ibex_gui/pull/1034

**Comment by DominicOram** [comment]
Happy to call this done.
