### ISSUE TITLE
SANS2D: Connect Birmingham 17T Magnet controller

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4523]
SANS2D instrument scientist and users required assistance with connecting the magnet control rack to the instrument control system.

Having talked the instrument scientist through various potential solutions, a personal visit was requested.  On arriving at the sample area, very many combinations of cables (patch, MOXA), couplers, null-modem and MOXA port were tried to no avail.

It eventually transpired that an additional Lakeshore device had been added to the system and the original remote interface cable has been used to connect this to the magnet control machine.  Once this cable had been returned to its original position, connection was immediately established and the VI on the NDX control machine sprang into life.  An alternative cable for the Lakeshore was sourced from stock enabling the magnet system to function as intended.

**Comment by kjwoodsISIS** [comment]
Perhaps it would be sensible to compile a list of all the cables required and describe how they should be connected.  We could even take photos of the setup.  Then the documentation could be added to the Developer wiki.

**Comment by davidkeymer** [comment]
Ultimately, the only oddity in the system was a serial cable (DB9F <-> DB9F) connected to the magnet control PC.  The cabling on our side wasn't anything unusual - just MOXA cable, coupler and patch cable.

**Comment by KathrynBaker** [comment]
The downside to this setup is that it isn’t entirely in our control.

Just to clarify the original problem, was the Lakeshore added to SANS2D or to the Birmingham computer?

(For those less familiar with the Birmingham 17T, I believe it is a Cryognenic Inc. system, as with the HIFI cryomagnet but with a different way of interacting remotely, via the RS232 port on the computer hosting the LabVIEW driver.)
