### ISSUE TITLE
Commission Muon Barndoors in the Motion Lab

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4524]
As a Muon user I would like to be able to control my barndoors. These will be a Beckhoff system and most of the logic of they run will be handled in the Beckhoff PLC. From our point of view we will need a motor record that talks to all axes on the Backhoff. Most of this will be covered in https://github.com/ISISComputingGroup/IBEX/issues/4303

## Acceptance Criteria
* The muon barn doors can be moved and homed repeatedly in the motion lab

**Comment by kjwoodsISIS** [comment]
Go - No Go decision on Wednesday 24th July.  Awaiting outcome.

**Comment by DominicOram** [comment]
The majority of the work for this will now be covered by https://github.com/ISISComputingGroup/IBEX/issues/4919. This ticket will remain to do the final commissioning of the barn doors. @Steve-Cox-IDD-Motion can help with this.

**Comment by John-Holt-Tessella** [comment]
Added to sprint because will be w/c 14/12/2020

**Comment by DominicOram** [comment]
Impeded on mechanical work

**Comment by DominicOram** [comment]
Went down and successfully moved them today. Some issues were found, no showstoppers but we need to think about them:
* I could only communicate with it by having static IPs on my machine and on the Beckhoff, I hope we can move it off static IPs but if not we will need a private network on MUONFE
* The code had no OPC tags originally, adding them into the code didn't result in them propagating to the tpy file, I'm not sure why. I got round this by adding them manually into the tpy file but this isn't a long term solution. I should document what this means
* The muon barn doors have 10 axes (3*1 gaps, 3*2 blades and 1 spare). In general in IBEX we've assumed controllers have a max of 8. We need to make sure the extra 2 work, particularly:
   * There are motor records loaded for them in the TWINCAT IOC
   * They contribute to the motors moving status
   * They are stopped by stop all
   * A further ticket is created to discuss how we generalise for > 8 axes in the ToM etc. (bearing in mind that in the future a Beckhoff may have > 10 axes)
* There is no longer a direction variable in the PLC code, @Simon-Cooper is working on this
* The busy record is not exactly analogous to moving, but probably doesn't matter in the short term, document the difference at least
* I've yet to test any of the following on the barn doors:
   * Homing
   * Limits
   * Jogging?

**Comment by DominicOram** [comment]
Delayed again until long shutdown

**Comment by rerpha** [comment]
Pretty sure I saw these actually move in person as I followed Dom down to the motion lab, may have even been before I'd started in IBEX!
