### ISSUE TITLE
SANS2D: journal file being truncated

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4526]
As an instrument scientist on SANS2D I would like my journal file to be written correctly, so that I can view my runs in a journal viewer.

`journal.xml` is being truncated while trying to write a particular block.

**Comment by FreddieAkeroyd** [comment]
I think the "journal blocks" entry *how many blocks to log into the XML) has got too long, I have a fix and am in contact with Sarah

**Comment by aaron-long** [comment]
+1 SANS2D support call.

J.D. had switched to the 17t magnet configuration and back to the standard configuration (the instrument will be run for the rest of cycle in the standard config). I fixed the XML file.

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd you mentioned you had a fix for this issue - where is the code for this/how do we deploy it on an instrument? Is it just a newer version of isisicp that we need to deploy or is it something more?

I've added some documentation about this issue to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting#isisicp-writes-a-corrupted-journal-file

**Comment by FreddieAkeroyd** [comment]
It is just a new ISISICP so can be deployed in the usual way with the next IBEX release

**Comment by FreddieAkeroyd** [comment]
ISISICP SVN 2015 and above has the fix, though as SANS2D are not running IBEX the will not get it with the next IBEX release!

**Comment by FreddieAkeroyd** [comment]
The XML file on SANS2D looked a little strange - it had a closing </NXroot> but  then there was part of a truncated entry after this. Was </NXroot> the last thing in the file when you edited it? I've removed the trailing rubbish and will see what happens next time they end a run.

**Comment by Tom-Willemsen** [comment]
I helped @aaron-long fix the XML this morning, and the closing `<nxroot>` tag was definitely the last item in the file at that point...

**Comment by FreddieAkeroyd** [comment]
It was the one in c:\data you fixed? They ended a run at 21:10 and it seems to be working OK now

**Comment by aaron-long** [comment]
Yep, it was the file in c:/data and dated for today’s date. Glad it’s OK.
