### ISSUE TITLE
IRIS: Edit synoptic to add additional Lakeshore device

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4527]
IRIS scientist required assistance to edit synoptic.  Original had one Lakeshore component with PV details referring to two devices.  Scientist wanted to be able to open OPI for second device from synoptic.  Device screens already existed for both devices and so the aim was to make these and the synoptic consistent.

Additional Lakeshore component created by copying original and removing PV details referring to first device.  Original Lakeshore component then edited to remove PV details referring to second device.

**Comment by DominicOram** [comment]
Confirmed synoptic has been modified. Did the scientists attempt to edit the synoptic themselves first? It may be worth pointing them towards https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Create-and-Manage-Synoptics if they want to be able to do this quickly in the future.
