### ISSUE TITLE
OSIRIS: Connect ITC and ILM

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4532]
OSIRIS instrument scientist required assistance connecting and configuring an ITC and ILM to run an Oxford Instruments cryostat (blue in colour).

These two devices are contained in a small portable crate along with an ISOBUS expander box`*`.  Due to the way the IOCs are written, individual connections are required to each device, rather than using the bus method.  Therefore, one of the devices was disconnected from the ISOBUS expander and directly patched through to an unused MOXA port.  The other device, now the only one on the bus, communicated successfully with its IOC.

`*` This is an ISIS invention which amplifies the signals on the ISOBUS (Oxford Instruments serial communications bus) and provides a DB9F (9-pin female serial socket) for the remote interface cable.

**Comment by DominicOram** [comment]
Is the fact that this is different in IBEX/SECIin the developers manual? I couldn't see it on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ITC-503 or https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Cryogenics

**Comment by Tom-Willemsen** [comment]
Added this information to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Cryogenics#note-about-oxford-instruments-itcilmips-controllers

**Comment by DominicOram** [comment]
Great, thanks @Tom-Willemsen
