### ISSUE TITLE
MARI: disk space

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4534]
MARI is down to ~7GB free on main instrument C drive, which has triggered a nagios "critical" warning. Free up some space.

**Comment by Tom-Willemsen** [comment]
I have freed up just over 3GB by removing old log files, which brings them to ~10GB free space. This is no longer at nagios' critical level and should be fine for the remaining few days of cycle.

**Comment by davidkeymer** [comment]
Confirmed free space on NDXMARI is ~10GB (used 65.1GB, free 9.87GB, total 74.9GB)
