### ISSUE TITLE
Deploy: Create release for Cycle 2019/02

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4539]
As a developer I would like to create a release suitable for deployment in time for the September cycle.

To do:
- [x] Decide which instruments we are deploying this release to
- [x] Find any tickets which are critical for the release, and ensure they are tagged with a for release label
- [x] Follow the [usual release & testing process](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release)

**Comment by Tom-Willemsen** [comment]
If https://github.com/ISISComputingGroup/IBEX/issues/4511 has not been done and merged by release creation time, disable nicos as part of the release process.

**Comment by Tom-Willemsen** [comment]
Outcome of discussion deciding where to deploy this release:
- Deploy to all standard instruments as it contains some fixes relevant to many instruments (e.g. stuck com ports), and we are unlikely to do a full release in next shutdown as it is short.
- Deploy to mini-instruments only if they use the JASCO device (LSS and reflectometers).
- A further patch release will be created for NIMROD once all of it's IOCs have been written.

**Comment by Tom-Willemsen** [comment]
Manual testing revealed the following bugs:

### Non-critical bugs
- The beam status UI is confusing if the accelerator PVs are down. Marked as "non-critical" as this is unlikely to be the case during cycle. See https://github.com/ISISComputingGroup/IBEX/issues/4640
- Memory leak while doing configuration tests. Likely the same as https://github.com/ISISComputingGroup/IBEX/issues/4239
- Groups only containing hidden blocks aren't displayed when "show hidden blocks" is enabled. This has been the case for a little while. See https://github.com/ISISComputingGroup/IBEX/issues/3334
- Can appear to edit a read-only config. This is an unlikely scenario on an instrument and does not actually allow config editing. See https://github.com/ISISComputingGroup/IBEX/issues/4644

### Potentially critical bugs
- Rendering issue on PV selector, see https://github.com/ISISComputingGroup/IBEX/issues/4643 . This makes the PV selector unusable. If unsure how to fix it, we could just disable that dialog for the time being (but this will mean people find it much harder to set up their own blocks, and may cause additional support calls).
- Rendering issue on "buffer % full" indicator in scripting console. See https://github.com/ISISComputingGroup/IBEX/issues/4642 . If it can't be fixed, just revert the merge of the branch where it was added - we ran without it last cycle so should be able to go without it next cycle too.
- Device screens menu is inaccessible. This only occured on SCIDEMO and not on DEMO or my dev machine but is consistent and needs some further investigation to understand it. If, after investigation, we think it is rare then we could add a simple task to the deployment script to check it works on each machine where we install it. See https://github.com/ISISComputingGroup/IBEX/issues/4641

**Comment by DominicOram** [comment]
Confirmed that all bugs listed in the manual tests have been addressed here. Release notes look good. I'm happy to call this complete
