### ISSUE TITLE
ZOOM: Unable to move in detector past a point

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4543]
As an instrument scientist on ZOOM I was attempting to move the detector to one extreme of travel. It was unable to go past a point, ~8200mm, despite this point being well before the high limit ~10,000mm.

This was ultimately caused by a mix of a number of things:
* Due to a severed cable earlier in the cycle the motor and encoder values had got out of sync
* Once this was repaired the axis was not homed
* Instead the scientists corrected for this by changing the offset
* The soft limit of the axis are based on the motor steps of the drive rather than the encoder steps meaning that although the readback from encoder now seemed fine it was not going past where the motor steps crossed the limit.

This ticket most likely requires a small, focused meeting to discuss what the best solution to this is. Potential solutions are:
* Turn on the resyncing of motor and encoder positions https://github.com/ISISComputingGroup/IBEX/issues/2947
* Flag to user more obviously when these are out of sync and ask them to home
* Use encoder for limits rather than motor steps

**Comment by Alistair-McGann-Tessella** [comment]
We have had this discussion; the outcome is that flagging to the user that the motor and encoder positions are out of sync is the best solution. Ticket #4449 lets the difference in motor and encoders be calculated, this has been updated following this discussion and proposed.

**Comment by kjwoodsISIS** [comment]
The SANS2D VIs on SECI use a simple LED (labelled "Positional Error") to indicate when motors & encoders get out of sync, as shown here: 
![image](https://user-images.githubusercontent.com/7249337/61854165-6d71d100-aeb5-11e9-8c1a-db014c931ab5.png)

**Comment by John-Holt-Tessella** [comment]
As Alistair says it would also be nice to track the difference over time and archive it (hence #4449). This would allow the mechatronics group to monitor motors/encoders which are about to die.
