### ISSUE TITLE
MARI: Set up sample changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4545]
As a user on MARI I would like to be able to use my sample changer. Currently the sample changer is set up as a maclennan on MTR0301 and they are moving it to fixed positions using a script. It was set up without using motion setpoints for expediency. We should instead use motion set points properly. Contact instrument scientists for the exact points.

Furthermore the mechanics of the device means that it should only ever rotate in one direction, if it rotates in the other direction too much it will eventually break. If we think of a good way to do this we should implement it too.

**Comment by DominicOram** [comment]
This may be moving to a beckhoff soon and so it might make sense to hold off until then. @Steve-Cox-IDD-Motion will probably have a good idea of timelines on the move to beckhoff. We should discuss with instrument scientists what timeframe they would like for the above work.

**Comment by rerpha** [comment]
scientists are happy.
