### ISSUE TITLE
Support MARI: use Maclennan motor controller

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4546]
MARI have a sample changer and while their long term goal is to use a new Beckhoff controller, they want to use a Mclennan controller in the short term.

They had connected the controller and the sample changer but the device would not communicate. After checking it was found the incorrect MOXA port had been used.

They have requested an OPI to control the sample changer, I will create a separate ticket for this.

**Comment by KathrynBaker** [comment]
There is a McLennan set up, there is a block, all seems to be good.
