### ISSUE TITLE
LARMOR: potential slit issue?

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4548]
Reported by Rob as an electronics fault yesterday (2019/07/17 15:21) but we should confirm IBEX was performing correctly/as expected.

During run number 42967 Larmor slit 2 (in the blockhouse closest to the 
intermediate wall) reported that it had closed to a position of -37mm
Having checked the data it appears that the jaw had not moved.
The problem seems to have been with the south jaw. On attempting to make the 
jaw move to +20mm nothing happend
After starting and stopping IBEX/EPICS the jaw could be homed and the aperture 
reset successfully.
This would tend to suggest the start of a probelm with the encoder or some 
other part of the system.

**Comment by FreddieAkeroyd** [comment]
This would be MTR0106, IOC GALIL_01 axis F 
```
[2019-07-17 14:51:16] MTR0106 HW_LIM+ 
[2019-07-17 14:52:29] GalilAxis::beginMotion:GalilController::writeReadController:BGF:2010 COMMAND ERROR.  Galil::command("BGF") got ? instead of : response.  TC1 returned "22 Begin not possible due to limit switch"
[2019-07-17 14:52:29] sevr=major BGF: 22 Begin not possible due to limit switch
```

**Comment by Tom-Willemsen** [comment]
Jamie Nutter has asked us to investigate this by email, so adding to proposals.

**Comment by DominicOram** [comment]
I followed the email chain and agree with @Tom-Willemsen that this is done from our side.
