### ISSUE TITLE
GUI: values put in to and from fields in wrong order

### ISSUE THREAD

**Issue by adamb56789** [ISISComputingGroup/IBEX#4550]
As a user I want to be warned if I put values into to and from fields in the wrong order. This can currently be done in at least the following places:
- Searching by run number in the journal viewer
- Searching by start time in the journal viewer
- Filtering by time in the IOC log messages

Automatically swapping the values if they are the wrong way round is an alternative that could be considered.

#### Acceptance criteria
1. When values are in the wrong order, a message is displayed which informs the user that this is the case.
1. Alternatively, when values are the wrong way round, swap them automatically.

**Comment by Kevin-Woods-Tessella** [comment]
I think automatically swapping them would be better.

**Comment by John-Holt-Tessella** [comment]
To review in java11 gui you may need #4777

**Comment by JamesKingWork** [comment]
> To review in java11 gui you may need #4777

Merged these changes into the branch to review

**Comment by JamesKingWork** [comment]
> I think automatically swapping them would be better.

It was decided that we should not automatically swap the values as that functionality may annoy users in the case that they do not want search the values they entered by mistake
