### ISSUE TITLE
Support: IMAT Camera (MOT0104 - MC Lens Adj) unable to move to low limit.

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4553]
Support call from IMAT about the camera on the Galil mapped as MOT0104 - MC Lens Adj. 

- The axis has a high limit of 20 and a low limit of -25. And the user wanted to drive the axis to 17.500 to focus the camera. 
- The axis would only move to the high limit and a lower value of ~1.160
- The Hi limit and low limit alarms would trigger if the motor was stopped (at any point on the axis, and at the high limit and ~1.160)
- Trying to home the axis would not work (no response from commands)

I checked the logs and an error associated with the limit switch was being output:
```
[2019-07-18 21:13:49] MOVE: axis D to -154.4 (relative)  current readback 3534

[2019-07-18 21:13:49] Premove CB 1

[2019-07-18 21:13:49] GalilAxis::beginMotion:GalilController::writeReadController:BGD:2010 COMMAND ERROR.  Galil::command("BGD") got ? instead of : response.  TC1 returned "22 Begin not possible due to limit switch"

[2019-07-18 21:13:49] sevr=major BGD: 22 Begin not possible due to limit switch

[2019-07-18 21:13:49] 
```

They checked all cables were connected and the toggle switches on the front of the galil were identical to the other galils in the crate; everything checked out OK. They noted that someone had completed some work on the axis that day re: encoder, but had left no notes and the axis had not been used to focus the camera since before then.

They noted that since the beam was going off tomorrow they would try a different camera (different focus position within range) to use in the immediate moment.

EDIT: The user called back. After testing with the camera manually they were able to focus using a value of 9.405. Both limit switches were in alarm still however.

**Comment by Tom-Willemsen** [comment]
I think the home doesn't work from the standard motor screen because this is the axis where encoder power gets cut when not moving (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IMAT-Lens-Adjustment ). I think Dom wrote a utility script to home it - were you using that?
