### ISSUE TITLE
SANS2D: Vacuum System - document control variables

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4555]
As a developer, I want to know which items of information (control variables) I need, so that I can create the SANS2D vacuum system OPI.

#### Acceptance Criteria
1. All IBEX developers can view the list of SANS2D vacuum system control variables and associated notes.
1. Create PVs to correspond to the relevant FINS PLC control settings.

#### Notes
1. The SANS2D OPIs information (control variables) from multiple devices.  It makes sense to gather this information before starting to create the SANS2D OPIs.  The control variables are defined in the existing SANS2D VIs.  In IBEX, these control variables will be expressed as PVs.
1. Control variables required to create the SANS2D vacuum system OPI  will come from several sources:
   1. FINS PLC: the SANS2D vacuum system is controlled by a FINS PLC.  Information about the vacuum system has to be read from the FINS PLC.  This information should be documented so that future developers do not have to work it out by inspecting the code.  
The information is in the [SANS2D folder](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/MEMORY%20MAP.xls) on the ICPDiscussions site.
   1. DAE: information about monitors & detectors may come from the DAE
   1. Motion control: motion status & setpoints will come from various Galil controllers
      * the motion inhibit signal will come from the FINS PLC
   1. Pressure information: may come from the FINS PLC, may also be read directly from TPG-300s.
   1. Some of these control variables will also be required by other SANS2D OPIs.
1. Consult the existing LabVIEW VI to determine what items of information are required:
   * See the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb` in directory `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`.

**Comment by John-Holt-Tessella** [comment]
@KathrynBaker has a memory map for the PLC which she can provide

**Comment by KathrynBaker** [comment]
The Memory Map (which relates just to what I believe we need) is now in the SANS2D Folder in ICP Discussions. For reference - it is also in the Documentation folder alongside the VI in > LabVIEW Modules > Instruments > SANS2D > Vaccum System

**Comment by DominicOram** [comment]
I have emailed the scientists a picture of the OPI, they're happy with it.

**Comment by John-Holt-Tessella** [comment]
pull requests:

- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/332
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/501
- https://github.com/ISISComputingGroup/ibex_gui/pull/1105
