### ISSUE TITLE
SANS2D: Vacuum System OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4556]
As a SANS2D scientist, I want IBEX to provide me with an OPI for the SANS2D vacuum system, so that I have an overview of the vacuum system and can control appropriate parts of it.

#### Acceptance Criteria
1. The IBEX GUI provides a blank OPI, ready to accept additional controls for the SANS2D vacuum system.

#### Notes
1. This ticket is deliberately very simple.  Its sole purpose is to create a blank OPI.  The OPI will be populated with controls for the SANS2D vacuum system via a number of other tickets.  This ticket can be done as the first step in implementing the first of the substantial SANS2D vacuum system tickets (see #4554).
1. The SANS2D vacuum system OPI will need to be quite large, because it will 
   1. collate information from several different devices
   1. contain a large number of controls.
   1. Check the schematic diagrams to see how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.

**Comment by John-Holt-Tessella** [comment]
Done in #4555
