### ISSUE TITLE
SANS2D: Miscellaneous Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4557]
As a SANS2D scientist, I want IBEX to provide a number of controls (detailed below) on the SANS2D vacuum system OPI, so that I can control my experiments.

#### Acceptance Criteria
1. The IBEX GUI provides the following controls:
   1. a Common Alarm Signal LED (red): lit/unlit if there is a common alarm signal
   1. a motion indicator:
      * the motion indicator should clearly show ENABLED or DISABLED
      * if the motion status cannot be determined, the motion indicator should clearly show ERROR: STATUS UNKNOWN and IBEX should raise an alarm
1. IBEX provides at least the same level of functionality as the "Common Alarm Signal" and "Galil Permission to Move" controls on the existing LabVIEW VI (excluding the overcount controls - see below).

#### Notes
1. This ticket is sub-ticket of #4554.
1. The information required for each of these controls needs to be determined (e.g. by inspecting the LabVIEW code):
   * Common Alarm Signal - probably provided by the FINS PLC
   * motion indicator - probably the motion inhibit signal provided by the FINS PLC
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)
1. The LabVIEW VIs contain Detector Overcount controls.  It is believed (by the scientists) that these refer to the old Ordela detector, which is no longer used on SANS2D.  The Detector Overcount controls are not required for IBEX.

**Comment by John-Holt-Tessella** [comment]
Motion indicator is can move cannot move and alarm if disconnected/error and show last value

**Comment by John-Holt-Tessella** [comment]
Done in #4555
