### ISSUE TITLE
SANS2D: Vacuum Pump Status Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4558]
As a SANS2D scientist, I want IBEX to show me the status of the vacuum pumps on SANS2D, so that I can check whether they are operating correctly.

#### Acceptance Criteria
1. The IBEX GUI provides an indicator control for each of the 4 vacuum pumps on SANS2D
1. The vacuum pump indicator control should provide the following indicators:
   1. a Pump Running LED (green): lit/unlit if the pump is running/not running
   1. a Pump Overload Tripped LED (red): lit/unlit if the pump overload is tripped/not tripped
   1. a Pump Emergency Stop LED (red): lit/unlit if the pump emergency stop is tripped/not tripped
   1. a Pump SP Guard - Warning LED (red): lit if the pump SP Guard is in a warning state, otherwise unlit
   1. a Pump SP Guard - Fault LED (red): lit if the pump SP Guard is in a fault state, otherwise unlit
1. Pumps 1 to 3 should contain all 5 indicators described above.
1. Pump 4 should contain only the first two indicators described above.
1. IBEX provides at least the same level of functionality as the 4 pump controls in the existing LabVIEW VI (excluding the Heartbeat field).

#### Notes
1. This ticket is sub-ticket of #4554.
1. The state of the vacuum pumps should be obtained from the FINS PLC used to control the vacuum system.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)

**Comment by John-Holt-Tessella** [comment]
Done in #4555
