### ISSUE TITLE
SANS2D: Fast Shutter Control

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4560]
As a SANS2D scientist, I want IBEX to provide controls for the fast shutter, so that I can control it during my experiments.

#### Acceptance Criteria
1. The IBEX GUI provides a fast shutter control group
1. The fast shutter control group should provide the following indicators & fields:
   1. a coloured indicator showing the status of the fast shutter, displaying
      * OPEN if the fast shutter is open,
      * CLOSED if the fast shutter is closed
      * ERROR: STATUS UNKNOWN, if the state of the fast shutter cannot be determined
   1. an LED (green, labelled "Open:"): lit/unlit if the fast shutter is open/closed
   1. an LED (red, labelled "Error:"): lit if the fast shutter is in an error state, otherwise unlit
   1. a status field (showing what?)
1. IBEX provides at least the same level of functionality as the Fast Shutter section of the existing LabVIEW VI.

#### Notes
1. This ticket is sub-ticket of #4554.
1. Information regarding the fast shutter should be obtained from the FINS PLC used to control the vacuum system.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)

**Comment by John-Holt-Tessella** [comment]
Done in #4555 

(Alarm is used if status can not be read)
