### ISSUE TITLE
SANS2D: Monitor 3 (genie_python)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4561]
As a SANS2D scientist, I want to control the position of monitor 3 during my experiments via a genie_python script.

#### Acceptance Criteria
1. Motion setpoints for Monitor 3 are defined
   * IN: meaning monitor 3 is positioned in the beam
   * OUT: meaning monitor 3 is retracted out of the beam
1. I can control the position of Monitor 3 via genie_python (usually via the DO_SANS and DO_TRANS commands).

#### Notes
1. This ticket is sub-ticket of #4554.
1. Check the paragraph labelled M3 in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
Done in #4555
