### ISSUE TITLE
SANS2D: Monitor 3 (GUI)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4562]
As a SANS2D scientist, I want IBEX to provide with controls for Monitor 3, so that I can control it during my experiments.

#### Acceptance Criteria
1. The IBEX GUI provides a Monitor 3 control group
1. The Monitor 3 control group should provide the following indicators & fields:
   1. an LED (green, labelled "In:"): lit if monitor 3 is fully in position in the beam, otherwise unlit
   1. an LED (green, labelled "Out:"): lit if monitor 3 is full retracted out of the beam, otherwise unlit
   1. an LED (red, labelled "Error:"): lit if monitor 3 is in an error state, otherwise unlit
   1. a button labelled "Insert"
      * on pressing Insert, monitor 3 is moved to the "IN" position (i.e. in the beam).
      * on completing the insert operation, the state of the 3 LEDs above should be updated.
      * if monitor 3 is already inserted, pressing Insert should have no effect.
   1. a button labelled "Extract"
      * on pressing Extract, monitor 3 is moved to the "OUT" position (i.e. out of the beam).
      * on completing the extract operation, the state of the 3 LEDs above should be updated.
      * if monitor 3 is already extracted, pressing Extract should have no effect.
   1. a status field (showing what?)
1. IBEX provides at least the same level of functionality as the Monitor 3 section of the existing LabVIEW VI.

#### Notes
1. This ticket is sub-ticket of #4554.
1. This ticket is related to #4561.
1. The IN/OUT positions of monitor 3 are defined as motion setpoints.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)
1. Check the paragraph labelled M3 in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
Done in #4555 

(INSERT is set by PLC not by pressing button. Same for extract)
