### ISSUE TITLE
SANS2D: Valve 8 Status

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4563]
As a SANS2D scientist, I want IBEX to show me the status of valve 8 on SANS2D, so that I can check it is operating correctly.

#### Acceptance Criteria
1. The IBEX GUI provides a Valve 8 control group
1. The Valve 8 control group should provide the following indicators :
   1. an LED (green, labelled "Valve Open:"): lit if the valve is open, otherwise unlit
   1. an LED (red, labelled "Error:"): lit if the valve is in an error state, otherwise unlit
1. IBEX provides at least the same level of functionality as the Valve 8 section of the existing LabVIEW VI

#### Notes
1. This ticket is sub-ticket of #4554.
1. Information regarding valve 8 should be obtained from the FINS PLC used to control the vacuum system.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)
1. Check the paragraph describing the Snout valve (aka V8) in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
Done in #4555
