### ISSUE TITLE
SANS2D: Seal Pressure Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4564]
As a SANS2D scientist, I want IBEX to display the seal pressures on SANS2D apertures & waveguides, so that I can check the pressures.

#### Acceptance Criteria
1. The IBEX GUI provides a seal pressure control
1. The seal pressure control should contain the following fields:
   1. Supply field, showing the supply pressure
   1. Inflation field, showing the inflation pressure
1. IBEX provides at least the same level of functionality as the Seal pressures section of the existing LabVIEW VI.

#### Notes
1. This ticket is sub-ticket of #4554.
1. Information regarding the seal pressures should be obtained from the FINS PLC used to control the vacuum system.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)
1. Check the paragraph describing the Vacuum Seals in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
Done in #4555
