### ISSUE TITLE
SANS2D: Guide System Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4565]
As a SANS2D scientist, I want IBEX to provide guide system controls SANS2D apertures & waveguides, so that I can control the inflation of the vacuum seals.

#### Acceptance Criteria
1. The IBEX GUI provides a Guide System control
1. The Guide System control should contain the following fields & controls:
   1. Status field, showing the status string reported by the FINS PLC
   1. Start Guide button, which tells the FINS PLC to inflate the seals
   1. Stop Guide button, which tells the FINS PLC to deflate the seals
1. IBEX provides at least the same level of functionality as the Guide System section of the existing LabVIEW VI.

#### Notes
1. This ticket is sub-ticket of #4554.
1. The vacuum seals have to be inflated and deflated in a specific order.  This is managed by the PLC.  All IBEX has to do is the tell the FINS PLC to start the inflation and deflation processes.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf)
 could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)

**Comment by John-Holt-Tessella** [comment]
Done in #4555
