### ISSUE TITLE
SANS2D: Guides - Vacuum & Motor Status

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4570]
As a SANS2D scientist, I want IBEX to provide me with vacuum & motion status indicators for the aperture & waveguide section of SANS2D, so that I can see when it is safe to move the apertures & waveguides.

#### Acceptance Criteria
1. The IBEX GUI provides a visible indicator showing the status of the vacuum in the aperture & waveguide section of SANS2D
   * the vacuum indicator should clearly show ON or OFF
   * if the vacuum status cannot be determined, the vacuum indicator should clearly show ERROR: STATUS UNKNOWN and IBEX should raise an alarm
1. The IBEX GUI provides a visible indicator showing the motion status for the aperture & waveguide section of SANS2D
   * the motion indicator should clearly show ENABLED or DISABLED
   * if the motion status cannot be determined, the motion indicator should clearly show ERROR: STATUS UNKNOWN and IBEX should raise an alarm
1. genie_python provides a means of querying the vacuum status in the aperture & waveguide section of SANS2D.
1. genie_python provides a means of querying the motion status in the aperture & waveguide section of SANS2D.
1. The Vacuum & Motor Status should appear on both the "normal" and "advanced" tabs.

#### Notes
1. This ticket is a sub-ticket of #4568.
1. Information about the vacuum is provided by a FINS PLC.
   * consult the SECI VI to discover which registers on the PLC provide the relevant information
1. On SANS2D, the apertures & waveguides *must not* be moved when under vacuum.  This is an equipment safety requirement.
1. The SANS2D vacuum PLC provides an inhibit signal to prevent the Galils moving the apertures & waveguides when under vacuum.  The purpose of this ticket is to ensure that the IBEX GUI reflects the status of the inhibit signal.
   1. if the inhibit signal is ON: the vacuum indicator should display ON, the motion indicator should display DISABLED
   1. if the inhibit signal is OFF: the vacuum indicator should display OFF, the motion indicator should display ENABLED
   1. if the inhibit signal cannot be determined (e.g. communication error): the vacuum indicator should display ERROR: STATUS UNKNOWN, the motion indicator should display ERROR: STATUS UNKNOWN and IBEX should raise an alarm.
   1. Yes, the vacuum indicator and motion indicator are opposites of each other.  The purpose of having two indicators is to make the state of the aperture & waveguide section of SANS2D very clear to the user.
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Waveguide`  (for more details see the `S2d - Waveguide Front Panel.vi` in the file `Sans2d - Waveguide Motion.llb`)

**Comment by DominicOram** [comment]
Work done as part of #4575
