### ISSUE TITLE
SANS2D: Aperture & Waveguide motion - STOP

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4571]
As a SANS2D scientist, I want IBEX to provide me with a STOP button, so that I can stop all motion of the moveable elements of the SANS2D waveguides & apertures section.

#### Acceptance Criteria
1. The IBEX GUI provides a clear, visible STOP button on the SANS2D apertures and waveguides OPI
1. On pressing the STOP button:
   1. if motion is enabled, all motors driving the SANS2D apertures and waveguides are halted immediately.
   1. if motion is disabled, IBEX ignores the button push.
1. The STOP button should appear on both the "user" and "advanced" tabs.
1. IOC Tests

#### Notes
1. This ticket is a sub-ticket of #4568.
1. The purpose of this ticket is to provide an "emergency STOP" button.
1. The apertures are heavy and there is a risk they can fall under their own gravity.  Therefore, the motors *must* remain energised (they require power to hold the load).
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/IBEX/issues/4579 for implementation that could be reproduced for this

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/27
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/355
- https://github.com/ISISComputingGroup/ibex_gui/pull/1165
