### ISSUE TITLE
SANS2D: Aperture & Waveguide motion - Positional Error

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4572]
As a SANS2D scientist, I want IBEX to alert me to positional errors relating to the apertures & guides, so that I know when the motor positions need to be re-calibrated.

#### Acceptance Criteria
1. The IBEX GUI alerts me when there is a discrepancy between the motor position and the motor encoder on any of the aperture & guide motors.
1. The positional error indicator should appear on both the "user" and "advanced" tabs.
1. Any positional error should be logged (see #4449).

#### Notes
1. This ticket is a sub-ticket of #4568.
1. See also ticket #4449
1. Check the existing VI to see how the calculation is performed.
   * the permissible tolerance between motor & encoder positions should be configurable
1. The LabVIEW VI for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Waveguide`  (for more details see the `S2d - Waveguide Front Panel.vi` in the file `Sans2d - Waveguide Motion.llb`)
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.
1. Check the paragraphs labelled S1-S5 and G1-G5 in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by JamesKingWork** [comment]
Use SECI to find tolerance

**Comment by KathrynBaker** [comment]
The underlying decision for the error is complicated - and we may need to consider what states and interactions are actually important and what we can ignore as there is a lot of reliance in the decision making on the driver in use and the states it goes through.

**Comment by RaiBishal** [comment]
Review also required for `custom_record.db` file in SANS2D config area. The follow PVs were added:

- **$(P)_POSITIONAL_ERROR_**
- **$(P)_POSITIONAL_ERROR**

**Comment by Tom-Willemsen** [comment]
Did we investigate the potentially complicated decision for positional error, and if so, where are the findings documented?

**Comment by KathrynBaker** [comment]
Not to my knowledge, the LabVIEW side hasn't been done, and the only place the equation has been considered is in the message in teams

**Comment by KathrynBaker** [comment]
For reference here - the positional error for each axis in LabVIEW which is then OR'd together is as follows:

```Positional error = Not(Monitor Only) AND ((Encoder Position = NaN) OR ((Absolute(To Apply Motion.Set Point - Encoder Position) > Positional Accuracy) AND ((Stop Code != Contour Running AND Present Motion.Motion Type = "Idle") AND Not(((Stop Code != Contour Running AND Present Motion.Motion Type != "Idle")) OR ((Move in Progress) OR (Stop Code = Contour Running)))) AND (To Apply Motion.MOtion Type = "Idle")))```

We should be able to eliminate most of the above, but it does need verifying

**Comment by KathrynBaker** [comment]
The below will need adding to the wiki somewhere, and the positional error equation at the end compared to existing EPICS fields and used to decide the overall positional error.

Calculation of positional error in SECI uses the following equation:

```
Positional error = Not(Monitor Only) AND ((Encoder Position = NaN) OR ((Absolute(To Apply Motion.Set Point - Encoder Position) > Positional Accuracy) AND ((Stop Code != Contour Running AND Present Motion.Motion Type = "Idle") AND Not(((Stop Code != Contour Running AND Present Motion.Motion Type != "Idle")) OR ((Move in Progress) OR (Stop Code = Contour Running)))) AND (To Apply Motion.Motion Type = "Idle")))
```

For SANS2D these positional errors are important in relation to the aperture and waveguides, and so more detail for those axis is considered

None of the axes under consideration are monitor only, so we can eliminate that term, it will always be True.

```
Positional error = ((Encoder Position = NaN) OR ((Absolute(To Apply Motion.Set Point - Encoder Position) > Positional Accuracy) AND ((Stop Code != Contour Running AND Present Motion.Motion Type = "Idle") AND Not(((Stop Code != Contour Running AND Present Motion.Motion Type != "Idle")) OR ((Move in Progress) OR (Stop Code = Contour Running)))) AND (To Apply Motion.Motion Type = "Idle")))
```

It is safe to assume that `Encoder Position = NaN` is indicative of an error in communicating with the axis in some way, as such should be replaced with whether or not the axis is in alarm, although that should be double-checked with the scientists. However, I think that is is appropriate as if the axis is in error we cannot guarantee the position so stating a positional error would be accurate, this changes that term to `record in alarm`.

```
Positional error = ((`record in alarm`) OR ((Absolute(To Apply Motion.Set Point - Encoder Position) > Positional Accuracy) AND ((Stop Code != Contour Running AND Present Motion.Motion Type = "Idle") AND Not(((Stop Code != Contour Running AND Present Motion.Motion Type != "Idle")) OR ((Move in Progress) OR (Stop Code = Contour Running)))) AND (To Apply Motion.Motion Type = "Idle")))
```

`To Apply` is about the setpoint to go after you hit send in the LabVIEW, so this can be taken as the requested val, and the whole absoulted value is the `.DIFF` field, and we can take the positional accuracy to be the `.RDBD` field, as this is the same logic requirement as whether or not to retry. Which would give us:

```
Positional error = ((`record in alarm`) OR (`.DIFF` > `.RDBD`) AND ((Stop Code != Contour Running AND Present Motion.Motion Type = "Idle") AND Not(((Stop Code != Contour Running AND Present Motion.Motion Type != "Idle")) OR ((Move in Progress) OR (Stop Code = Contour Running)))) AND (To Apply Motion.Motion Type = "Idle")))
```

Stop code is the one from the Galil, I'm not certain whether or not this is available, but as the axes in question don't use contours we can assume that the stop will not be contour running. 

```
Positional error = ((`record in alarm`) OR ((`.DIFF` > `.RDBD`) AND (Present Motion.Motion Type = "Idle" AND Not(Present Motion.Motion Type != "Idle" OR Move in Progress) AND To Apply Motion.Motion Type = "Idle"))
```

Present Motion as Idle would be the move is complete, `.DMOV` is true, and Move in Progress would therefore be `.MOVN` is True, as the To Apply concept is not applicable we can eliminate those terms as well.

```
Positional error = ((`record in alarm`) OR ((`.DIFF` > `.RDBD`) AND (`.DMOV` = True AND `.MOVN` = False))
```
