### ISSUE TITLE
SANS2D: Named Aperture & Guide Positions

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4573]
As a SANS2D scientist, I want IBEX to provide me with a set of named positions for all moveable waveguides & apertures on SANS2D, so that I can easily position all of them in a single operation.

#### Acceptance Criteria
1. The IBEX GUI provides a control to allow me to select a named position
   * the position selector could be a drop-down box control
   * the position selector appears only on the "user" tab of the IBEX GUI.
1. IBEX allows me to select from the following named positions:
   * 4m_20_8mm
   * 4m_20_12mm
   * 4m_30x20_12mm
   * 6m_20_8mm
   * 6m_16_8mm
   * 6m_GISANS
   * 8m_20_8mm
   * 8m_GISANS
   * 12m_20_8mm
   * 12m_GISANS
1. Motion is disabled/enabled if the PLC inhibit signal is on/off.
1. On selecting a named position, 
   1. if motion is enabled, IBEX moves all of the moveable waveguides & apertures to their corresponding positions (defined in a configuration file).
   1. if motion is disabled, IBEX does not move any aperture or waveguide. 
      * the position selector should be greyed out when motion is inhibited
      * genie_python should report that it cannot move the relevant axis. 
1. I can move all 5 moveable waveguides & apertures to named positions via the IBEX GUI
1. I can move all 5 moveable waveguides & apertures to named positions via genie_python
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Notes
1. This ticket is a sub-ticket of #4568.
1. Each moveable waveguide and each moveable aperture has its own defined positions.  When the user selects a named position, all of the moveable waveguides and all of the moveable apertures should move (together) to their respective named positions.
1. The position of each moveable aperture is controlled by a Galil controller & stepper motor.
   * The apertures are heavy - there is a risk that they can fall under their own gravity.  Therefore, when movement of the apertures is complete, the motors *must* remain energised (they require power to hold the load).
1. The position of each moveable waveguide is controlled by a Galil controller.  The waveguides are heavy, so they are actually moved by Baldor drives.  The Baldor drives are slaved to the Galils.  For the avoidance of doubt, from the perspective of IBEX, the motion is controlled solely by Galils; IBEX does *not* (and *should not*) control the Baldor drives directly.
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Waveguide`  (for more details see the `S2d - Waveguide Front Panel.vi` in the file `Sans2d - Waveguide Motion.llb`)
1. The LabVIEW configuration file for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\S2D Front End Positions.ini`.
1. Check the paragraphs labelled S1-S5 and G1-G5 in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by DominicOram** [comment]
In discussion with @John-Holt-Tessella, @KathrynBaker and @Tom-Willemsen it was decided that removing bare motor support from the motionsetpoints

**Comment by John-Holt-Tessella** [comment]
Can we check that the decision is recorded correctly in decision log https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Decision-Log

**Comment by DominicOram** [comment]
Thanks @John-Holt-Tessella

**Comment by DominicOram** [comment]
- [ ] Main PR is https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/14.
- [ ] Tests https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/360
- [ ]  GUI https://github.com/ISISComputingGroup/ibex_gui/pull/1173
- [ ]  Upgrade scripts https://github.com/ISISComputingGroup/EPICS-upgrade/pull/46
- [ ] Docs https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motion-Set-points

**Comment by JamesKingWork** [comment]
I found it quite difficult to follow the flow of the asyn records so created what I hope is a useful and accurate diagram for others who look at the inner workings of the motionSetpoints support module. https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motion-Set-points#diagram. If anything on it is incorrect or not clear please let me know.

**Comment by DominicOram** [comment]
Once merged confirm it hasn't broken anything in https://github.com/ISISComputingGroup/IBEX/issues/5719
