### ISSUE TITLE
SANS2D: Aperture Position Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4574]
As a SANS2D scientist, I want IBEX to provide me with aperture position controls, so that I can adjust the position of any moveable aperture.

#### Acceptance Criteria
1. The Aperture Position Controls appears only on the "advanced" tab of the IBEX GUI.
1. Motion is disabled/enabled if the PLC inhibit signal is on/off.
1. If motion is enabled, 
   1. I can move each moveable aperture to any position in its range via the IBEX GUI
      * there should be one position control per aperture (to allow each aperture to be moved independently of the others)
   1. Each aperture position control should:
      1. allow the user to define the position setpoint of the aperture
      1. reflect the position of the aperture in a readback field
   1. I can move each moveable aperture to any position in its range via genie_python
1. If motion is disabled, I am unable to move any aperture (the aperture position control is disabled)
      * the Aperture Position Controls should be greyed out when motion is inhibited
      * genie_python should report that it cannot move the relevant axis. 
~~1. The "advanced" tab OPI provides a "Move All" button (c.f. Reflectometry), so that I can enter all the positions of the apertures (& guides - see #4575)  and make sure they are correct before anything moves.~~ See https://github.com/ISISComputingGroup/IBEX/issues/5499#issuecomment-648261738
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Notes
1. This ticket is a sub-ticket of #4568.
1. See also #4575.
1. Although each moveable aperture has named positions, scientists sometimes need to adjust the position of the aperture.
1. A slider style control + spinner is suggested for the aperture position controls:
   * the spinner should be used to change the position
   * the slider should merely reflect the current position of the motor driving the aperture
   * there is no requirement that the slider operate by a drag operation
1. The position of each moveable aperture is controlled by a Galil controller & stepper motor.
1. The apertures are heavy - there is a risk that they can fall under their own gravity.  Therefore, when movement of the apertures is complete, the motors *must* remain energised (they require power to hold the load).
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Waveguide`  (for more details see the `S2d - Waveguide Front Panel.vi` in the file `Sans2d - Waveguide Motion.llb`)
1. Check the paragraph labelled S1-S5 in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by DominicOram** [comment]
Work done as part of #4575
