### ISSUE TITLE
SANS2D: Waveguide Position Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4575]
As a SANS2D scientist, I want IBEX to provide me with waveguide position controls, so that I can adjust the position of any moveable waveguide.

#### Acceptance Criteria
1. The Waveguide Position Controls appears only on the "advanced" tab of the IBEX GUI.
1. Motion is disabled/enabled if the PLC inhibit signal is on/off.
1. If motion is enabled, 
   1. I can move each moveable waveguide to any position in its range via the IBEX GUI
      * there should be one position control per waveguide (to allow each waveguide to be moved independently of the others)
   1. Each waveguide position control should:
      1. allow the user to define the position setpoint of the waveguide
      1. reflect the position of the waveguide in a readback field
   1. I can move each moveable waveguide to any position in its range via genie_python
1. If motion is disabled, I am unable to move any waveguide (the waveguide position control is disabled)
      * the Waveguide Position Controls should be greyed out when motion is inhibited
      * genie_python should report that it cannot move the relevant axis. 
~~1. The "advanced" tab OPI provides a "Move All" button (c.f. Reflectometry), so that I can enter all the positions of the guides (& apertures - see #4574)  and make sure they are correct before anything moves.~~
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Notes
1. This ticket is a sub-ticket of #4568.
1. See also #4574.
1. Although each moveable waveguide has named positions, scientists sometimes need to adjust the position of the waveguide.
   * 1. The waveguides are usually moved using the pre-defined motion set-points.  Occasionally, the scientists will run a scan of the waveguides to check the validity of  the motion set-points.
1. A slider style control + spinner is suggested for the waveguide position controls:
   * the spinner should be used to change the position
   * the slider should merely reflect the current position of the motor driving the waveguide
   * there is no requirement that the slider operate by a drag operation
1. The position of each moveable waveguide is controlled by a Galil controller.  The waveguides are very heavy, so they are actually moved by Baldor drives.  The Baldor drives are slaved to the Galils.  For the avoidance of doubt, from the perspective of IBEX, the motion is controlled solely by Galils; IBEX does *not* (and *should not*) control the Baldor drives directly.
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Waveguide`  (for more details see the `S2d - Waveguide Front Panel.vi` in the file `Sans2d - Waveguide Motion.llb`)
1. Check the paragraph labelled G1-G5 in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by Alistair-McGann-Tessella** [comment]
Added feedback to the PR

**Comment by RaiBishal** [comment]
Ticket #4574 is being done as part of this ticket

**Comment by DominicOram** [comment]
Note `Move All` is not required for first implementation, see https://github.com/ISISComputingGroup/IBEX/issues/5499#issuecomment-648261738

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-ioc/pull/512
https://github.com/ISISComputingGroup/ibex_gui/pull/1111
