### ISSUE TITLE
SANS2D: Vacuum Tank OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4577]
As a SANS2D scientist, I want IBEX to provide me with an OPI for the SANS2D vacuum tank, so that I can control the positions of the detectors & baffles during my experiments.

#### Acceptance Criteria
1. The IBEX GUI provides a blank OPI, ready to accept additional controls for the SANS2D vacuum tank.
1. The Vacuum Tank OPI could have "user" and "advanced" tabs
1. The "advanced" tab is under password control (manager mode)
~~1. The Vacuum Tank OPI provides a "Move All" button (c.f. Reflectometry), so that I can enter all the positions of the baffles & detectors and make sure they are correct before anything moves.~~

#### Notes
1. This ticket is deliberately very simple.  Its sole purpose is to create a blank OPI.  The OPI will be populated with controls for the SANS2D vacuum tank via a number of other tickets.  This ticket can be done as the first step in implementing the first of the substantial SANS2D vacuum tank tickets (see #4576).
1. The SANS2D vacuum tank OPI will need to be quite large, because 
   1. it will collate information from several different devices
   1. the user tab will contain a large number of controls.
1. Check the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. Rarely used controls (e.g. the detector strip beam stops) could be relegated to an Advanced tab (under password control).

**Comment by DominicOram** [comment]
The `Move All` feature is not required for a first implementation, see https://github.com/ISISComputingGroup/IBEX/issues/5499#issuecomment-648261738

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1138
