### ISSUE TITLE
SANS2D: Vacuum Tank - Vacuum Status

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4578]
As a SANS2D scientist, I want IBEX to provide me with a vacuum status indicator for the SANS2D vacuum tank.

#### Acceptance Criteria
1. The IBEX GUI provides a visible indicator showing the status of the vacuum in the SANS2D vacuum tank
   * a status message should clearly show the vacuum status: `ATMOSPHERE`, `VAC DOWN`, `AT VACUUM`, or `VENTING`
   * if the vacuum status cannot be determined, the vacuum indicator should clearly show ERROR: STATUS UNKNOWN and IBEX should raise an alarm
1. genie_python provides a means of querying the vacuum status in the tank section of SANS2D.
1. The vacuum indicator should be duplicated on the Advanced tab.

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The purpose this ticket is simply to make the tank vacuum status very clear to the user.
1. The vacuum status should be determined from the FINS PLC that controls the vacuum system.
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank`  (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)

**Comment by JamesKingWork** [comment]
Branches: 
- https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket4578_vacuum_tank_status
- https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket4578_vacuum_tank_status

**Comment by kjwoodsISIS** [comment]
Two new pieces of information (discussed with @JamesKingWork :
   1. The TANK:STATUS PV actually has 4 states
      * "ATMOSPHERE" (meaning the tank is at atmospheric pressure)
      * "VAC DOWN"  (meaning pressure in the tank is decreasing)
      * "AT VACUUM" (meaning the tank is at its normal vacuum pressure)
      * "VENTING" (meaning pressure in the tank is increasing)
   1. The scientists are happy to move equipment inside the tank under vacuum conditions.

Item 1 means that a simple ON/OFF indicator is not sufficient.  It would be better to simply display the vacuum status (e.g. Vacuum Status: AT VACUUM).

Item 2 means that the tank motion controls (detectors, baffles, etc.) don't need to take account of the vacuum status when determining whether they can move.

**Comment by JamesKingWork** [comment]
This ticket is currently impeded waiting on a discussion with the scientist about the OPI

**Comment by JamesKingWork** [comment]
Removing impeded so we have something to demonstrate to the scientists

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1147

**Comment by JamesKingWork** [comment]
Documentation: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-vacuum-PLC
