### ISSUE TITLE
SANS2D: Vacuum Tank motion - STOP

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4579]
As a SANS2D scientist, I want IBEX to provide me with a STOP button, so that I can stop all motion of the moveable equipment in the SANS2D vacuum tank.

#### Acceptance Criteria
1. The IBEX GUI provides a clear, visible STOP button on the SANS2D vacuum tank OPI
1. On pressing the STOP button all motors driving the moveable equipment in the SANS2D vacuum tank are halted immediately.
1. The STOP button should be duplicated on the Advanced tab.

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The purpose of this ticket is to provide an "emergency STOP" button.
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-axis/pull/5

**Comment by JamesKingWork** [comment]
Ignore that last ibex_gui mention (I linked the wrong ticket by accident)
