### ISSUE TITLE
SANS2D: Detector & Baffle Schematic Indicator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4580]
As a SANS2D scientist, I want IBEX to provide a GUI element that indicates (schematically) the position of the two detector arrays (front & rear) and two baffles (front and rear), so that I can easily see their relative positions.

#### Acceptance Criteria
1. The IBEX GUI provides an indicator that illustrates the relative position of each of the front & rear detectors and front & rear baffles
   * the detectors & baffles all move, in effect, on a shared, linear axis (the z-axis)
   * from low z to high z, the order of the elements is:
      1. front detector
      1. front baffle
      1. rear baffle
      1. rear detector
1. There should be 4 items on the indicator (one for each element listed above)
1. Detectors should be illustrated in a different colour from baffles.
1. The indicator should have a scale to provide a numerical indication of the position of each element.
1. The indicator should display the distances between:
   1. the front detector and the front baffle
   1. the front baffle and the rear baffle
   1. the rear baffle and the rear detector 
1. The fields showing the inter detector/baffle distances should change colour as the distances approach the minimum allowed distances (see #4587):
   * orange background when distance is within 10 cm (configurable) of the minimum
   * red background when distance is within 5 cm (configurable) of the minimum
1. As the motor positions of the detectors & baffles change, the sliders should move accordingly. 
1. IBEX provides at least the same level of functionality as the existing LabVIEW VI.

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The detectors & baffles are each mounted on a trolley; the trolleys move on shared rails.
1. A slider style control is suggested for the Detector & Baffle Indicator:
   * the slider control should reflect the current position of the motor driving each element (detector trolley or baffle trolley)
   * there is no requirement that the control operates by a drag operation
1. A slider style control also provides a simple visual indication of how close the detectors & baffles are to each other, which could help the user avoid a collision of detectors & baffles.
   * For the avoidance of doubt, the Detector & Baffle Schematic Indicator is **not** intended to provide a collision prevention mechanism.
   * in the event of a collision between detectors & baffles, there are routines in the Galil controller(s) which initiate a rapid deceleration to avoid (or at least minimise) damage to devices.
1. The OPI could display two sets of intervals - one based on readbacks of the current positions of the detectors & baffles; the other based on setpoints for the detector & baffle positions.
   1. Current interval = readback_B - readback_A
   1. Requested interval = setpoint_B - setpoint_A
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank` (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1143
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/513

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PLCs#omron-fins to start the FINS IOC for the vacuum tanks correctly.

I have also create the configuration branch NDXSANS2D_vacuum. Run the configuration/galils/setupmotors.bat script to set up the sans2D motors. When approving please merge this branch into NDXSANS2D.
