### ISSUE TITLE
SANS2D: Front Detector Beam Stop

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4581]
As a SANS2D scientist, I want IBEX to provide control for the front beam stop, so that I can control its position.

#### Acceptance Criteria
1. If the detector rotation is greater than 0 degrees, motion of the front beam stop must be inhibited.
1. I can control the rotation of the front beam stop via the IBEX GUI.
1. I can control the rotation of the front beam stop via genie_python.
1. Beam stop motors are de-energised when motion is complete.

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The front beamstop must not be operated if the front detector is rotated.
1. Because the motors that move the beam stops operate in a vacuum, they should be de-energised when a move is complete (otherwise they are at risk of over-heating).
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank`  (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)
1. Check the paragraph describing the Front Detector Beamstop in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
Inhibition:

- On rbv or sp change of detector angle do the following logic
- if rbv or sp > 0:
   - call, stop motor and DISP = True
- else set DISP=False

**Comment by FreddieAkeroyd** [comment]
Would we need to set DISP on both the motor and axis for safety? DISP only disables channel access puts and not ones linked from within the IOC, if this is a potential concern would it be better to disable the motor record itself from scanning?

**Comment by John-Holt-Tessella** [comment]
Would that not stop the Stop button from working on the motor because it is a field

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/515
- https://github.com/ISISComputingGroup/ibex_gui/pull/1146

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella Do we need to be able to use the stop button if we are not able to start motion?

**Comment by FreddieAkeroyd** [comment]
A recent tech talk post suggests people set DISP and also disable the motor record (either by linking SDIS or writing to DISA). The only side effect of disabling the motor record is it stops the endoder readback updating on the record, so if the axis was (manually) moved this would not be displayed until the record was re-enabled.

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd I would like not to disable the stop button if something goes wrong and we somehow disable the stop button but don't stop the motor that would be bad.
@JamesKingWork said he would try DISP and see if it stopped the stop button working, not sure what he found out. If we don't disable the motor record it means that if people are fiddling at that lower level they can collide the items but in normal usage they can't.

**Comment by FreddieAkeroyd** [comment]
DISP will disable direct channel access but not indirect record processing, so setting motor.DISP will stop access to MOTOR.STOP via the GUI channel access, but would not access to motor.STOP from a record in the same IOC. It seems to follows the same rules as access control. However the docs said "stops dbPutField (usually channel access)" - i am not sure what else uses dbPutField. So I think you can't disable sending moves on the low level motor GUI screen unless you also disable the stop button on that GUI. However if the DB logic sends a stop if it sees movement then maybe that is good enough? Could you also use the SPMG field?

**Comment by JamesKingWork** [comment]
See docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-Front-Beam-Stop-inhibit-movement

**Comment by DominicOram** [comment]
Works as advertised and good tests. The labview also inhibits the detector if the beamstop is rotated. The logic is the same, that the detector can only rotate if -2 < beamstop rotation < 2. This makes sense as if they're going to collide when both rotated it doesn't matter what the order of rotation is. If this is no longer required can you document why.

I also think the documentation could be a bit clearer, it took me a while to work out what it was saying and the distinction between setting DISP on the axis/motor record (sorry that's a vague review comment).
