### ISSUE TITLE
SANS2D: Rear Detector Beam Stops

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4583]
As a SANS2D scientist, I want IBEX to provide controls for the rear beam stops, so that I can control their positions.

#### Acceptance Criteria
1. I can independently control the y-axis position of each of the 3 rear beam stops via the IBEX GUI.
1. I can independently control the y-axis position of each of the 3 rear beam stops via genie_python.
1. I can control the x-axis position of the beam stop pillar via the IBEX GUI.
1. I can control the x-axis position of the beam stop pillar via genie_python.
1. Beam stop motors are de-energised when motion is complete.

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The 3 rear beam stops are mounted on a vertical pillar (attached to the rear detector trolley).
   1. The pillar moves left-right (x-axis) across the face of the rear detector array.  When the pillar moves, all 3 beams stops move with it.
   1. Each of the 3 beams stops can move vertically up/down (y-axis) independently of the others.
1. Because the motors that move the beam stops operate in a vacuum, they should be de-energised when a move is complete (otherwise they are at risk of over-heating).
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank`  (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)

**Comment by Alistair-McGann-Tessella** [comment]
PRs:
* GUI/OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1161
* I also enabled de-energise after move by modifying `setup_motors.bat` in the SANS2D configuration
