### ISSUE TITLE
SANS2D: Baffle Position Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4585]
As a SANS2D scientist, I want IBEX to provide me with two baffle position controls, so that I can independently adjust the position of either baffle (front/rear).

#### Acceptance Criteria
1. I can move the front baffle along the z-axis via the IBEX GUI.
1. I can move the front baffle along the z-axis via genie_python.
1. I can move the rear baffle along the z-axis via the IBEX GUI.
1. I can move the rear baffle along the z-axis via genie_python.
1. Baffle trolley motors are de-energised when motion is complete.
~~1. The baffle position controls operate with the "Move All" button (see #4577), so that the user can enter new positions but the baffle doesn't move until the "Move All" is pressed.~~ (No longer required https://github.com/ISISComputingGroup/IBEX/issues/5499#issuecomment-648261738)
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The front and rear baffles are physically mounted on trolleys sharing a single set of rails parallel to the z-axis.
   1. the trolleys are free to move along the entire length of the rails, constrained only by each other and the front and rear detector trolleys.
   1. there is a risk that the baffle trolleys could collide with each other or with the detector trolleys.
      * in the event of a collision between detectors & baffles, there are routines in the Galil controller(s) which initiate a rapid deceleration to avoid (or at least minimise) damage to devices.
   1. See ticket #4587 for minimum distances (to prevent collisions).
1. Each baffle position control should:
      1. allow the user to define the position setpoint of the baffle
      1. reflect the position of the baffle in a readback field
1. Because the motors that drive the baffle trolleys operate in a vacuum, they should be de-energised when a move is complete (otherwise they are at risk of over-heating).
1. Note the homing of baffle trolleys:
   1. for the front baffle , the z-direction home must start in a forwards direction (i.e. towards the sample position). 
   1. for the rear baffle, the z-direction home must start in a backwards direction (i.e. towards the rear of the tank). 
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank`  (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)
1. Check the paragraphs describing the Front & Rear Baffles in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by JamesKingWork** [comment]
This has been partially fulfilled in https://github.com/ISISComputingGroup/IBEX/issues/4580 which allows you to move baffles along the x axis in the IBEX GUI using the text inputs.
