### ISSUE TITLE
SANS2D: Detector Position Controls

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4586]
As a SANS2D scientist, I want IBEX to provide me with two detector position controls, so that I can independently adjust the position of either detector (front/rear).

#### Acceptance Criteria
1. The IBEX GUI provides one position control per detector array (to allow each detector array to be moved independently of the other)
1. Motion is disabled/enabled if the detector array CAEN high-voltage PSU is on/off.
1. If the CAEN high-voltage PSU is on/off, the PS Energised LED should be lit/unlit
1. If motion is enabled, 
   1. I can move each detector array along the z-axis (i.e. parallel to the beam) using the IBEX GUI or genie_python.
   1. I can move each detector array along the x-axis (i.e. horizontally across the beam) using the IBEX GUI or genie_python.
   1. I can rotate the front detector array about its axis of rotation using the IBEX GUI or genie_python.
   1. In the IBEX GUI, each detector array position control should:
      1. allow the user to define the z-axis position setpoint of the detector array
      1. reflect the z-axis position of the detector array in a readback field
      1. allow the user to define the x-axis position setpoint of the detector array
      1. reflect the x-axis position of the detector array in a readback field
      1. For the front detector array only:
         1. allow the user to define the rotation setpoint of the detector array
         1. reflect the rotation of the detector array in a readback field
1. If motion is disabled, I am unable to move the relevant detector array.  The detector array position control is disabled in the IBEX GUI; genie_python reports that it cannot move the relevant axis. 
1. Detector array trolley motors are de-energised when motion is complete.
~~1. The detector position controls operate with the "Move All" button (see #4577), so that the user can enter new positions but the detector doesn't move until the "Move All" is pressed.~~ (No long required, see https://github.com/ISISComputingGroup/IBEX/issues/5499#issuecomment-648261738)
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Notes
1. This ticket is a sub-ticket of #4576.
1. The front and rear detector arrays are physically mounted on trolleys sharing a single set of rails parallel to the z-axis.
   1. the trolleys are free to move along the entire length of the rails, constrained only by the front and rear baffle trolleys respectively.
   1. there is a risk that the detector trolleys could collide with the baffle trolleys.
   1. there is a risk that when the front detector array is rotated, it could collide with the front baffle.
      * in the event of a collision between detectors & baffles, there are routines in the Galil controller(s) which initiate a rapid deceleration to avoid (or at least minimise) damage to devices.
   1. See ticket #4587 for minimum distances (to prevent collisions).
1. Because the motors that drive the detector array trolleys operate in a vacuum, they should be de-energised when a move is complete (otherwise they are at risk of over-heating).
   * *Note:* do not confuse energising of the motors with energising of the CAEN power supplies.
1. Note the homing of detectors:
   1. on both detectors all directions of motion have encoders and a home position.
   1. on the front detector, the z-direction home must start in a forwards direction (i.e. towards the sample position). 
   1. on the rear detector, the z-direction home must start in a backwards direction (i.e. towards the rear of the tank). 
1. The detector trolleys are driven (in the z-direction) by belts.  Belts are not as precise as direct drive, so positioning can be tricky.  Motion correction on these axes is switched off for this reason.
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank`  (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)
1. Check the paragraphs describing the Front and Rear Detectors in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by JamesKingWork** [comment]
This has been partially fulfilled in https://github.com/ISISComputingGroup/IBEX/issues/4580 which allows you to move detectors along the z-axis in the IBEX GUI using the text inputs.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-galil/pull/40 ( @KathrynBaker and @DominicOram , you may be interested in this one)
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/530
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/358
- https://github.com/ISISComputingGroup/ibex_gui/pull/1167

You will also need the latest NDXSANS2D config branch.

To test this:
- Verify that if `TE:NDW1799:REARDET:ON` is `On`, you can't move the rear detector (check both the underlying motor `MTR0401` and the axis `REARDET:SP`)
  * Note, the CAEN does not simulate switching on properly, so you will have to test by manually `caput`ing to `TE:NDW1799:REARDET:ON`
- Verify that if any axis on the rear detector is moving, the `DISP` flag is set on all relevant detector channels
- Verify that a sensible message comes up on the OPI when attempting to do a move with the detectors powered on
- Repeat the above tests for all the axes on the front & rear detectors
