### ISSUE TITLE
Reflectometry: Connection loss recovery

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4588]
Currently, the reflectometry server does not recover well from temporarily losing connection to underlying motors with CA raising an exception of the form 

>  UnCAERROR: CAException: type=-1 state=192 op=5 file=..\cac.cpp lineNo=1223
expected problem with CA circuit to server "NDLT882.isis.cclrc.ac.uk:59999" was "An existing connection was forcibly closed by the remote host. " - disconnecting

The most notable symptom of the failed recovery is that readback values of reflectometry parameters will not update after such an event until the reflectometry IOC is restarted (although the motors still move to the proper positions etc.). This would suggest that the monitor processes (which are posted on relevant motor PVs once on startup) die, which means any new values in the motor do not get propagated up to the parameter level. The same would likely be true for monitors on moving state, velocity etc. The reflectometry server needs to be robust enough to handle this. Find a way to detect monitor failure and reinstate them in a disconnection event.

Acceptance criteria:
- Monitors continue to update relevant reflectometry values via monitors after a temporary channel access failure

**Comment by John-Holt-Tessella** [comment]
Will this fix #4127

**Comment by ThomasLohnert** [comment]
After investigation with @FreddieAkeroyd and @John-Holt-Tessella , the actual issue seems to be that all the monitor processes all run on the same thread, and there is a race condition in one of the callback functions which makes all monitors stall indefinitely. 

Planning to fix this by using a threadpool / event queue.

**Comment by ThomasLohnert** [comment]
Fixed on branch `Ticket4588_monitor_stall` - monitor callback functions are now sent to a threadpool for execution. This needs a unit tests, which requires setting up some mocked PVs. I don't think I will get around to this before I go away Thursday - moving it back to ready for now in case someone else wants to pick it up.

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/tree/Ticket4588_monitor_stall

**Comment by aaron-long** [comment]
After some discussion with @Tom-Willemsen, @John-Holt-Tessella and @DominicOram we have decided that the way we will move forward with this issue is to remove parts of the code that deal with "restoring a user-input velocity during a move".

**Comment by aaron-long** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/43140680/66121504-44686d80-e5d5-11e9-916d-f21c9ee5f80e.png)

**Comment by aaron-long** [comment]
After some discussion with John: Velocity caching and restoring will only be implemented for `PVWrapper` and not `JawsAxisPVWrapper`. We do not currently (or expect to)  synchronise  jaws slit gaps with a move of the beamline (i.e., translation stages). Instead the translation stage of a jaws set would move in this synchronisation.

**Comment by ThomasLohnert** [comment]
Some minor bits of rework, see comments:

- [ ] ISISComputingGroup/EPICS-inst_servers#234
- [ ] ISISComputingGroup/EPICS-IOC_Test_Framework#248

**Comment by ThomasLohnert** [comment]
Looks good, back for a quick rework with suggestions for improving the new unit tests. Also you checked off the IOC test framework above but there are no new changes since my last review - is it just missing a git push?
