### ISSUE TITLE
SANS2D: DO_SANS and DO_TRANS Commands

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4591]
As a SANS2D scientist, I want IBEX to provide me with commands for the scraper aperture, so that I can control it.

#### Acceptance Criteria
1. On invoking the DO_SANS command in genie_python:
   1. the scraper aperture is moved to the XXX position
   1. the monitor M3 is moved to the XXX (IN or OUT) position
1. On invoking the DO_TRANS command in genie_python:
   1. the scraper aperture is moved to the YYY position
   1. the monitor M3 is moved to the YYY (IN or OUT) position
1. I can use appropriate commands to manually control the scraper aperture via the IBEX GUI.

#### Notes
1. This ticket is a sub-ticket of #4589.
1. Need to check with Adam on this.  It may be that he implements the commands in the scans library (there are similar commands for LOQ).
1. Check the paragraph describing the S6 (Scraper) Aperture in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by Tom-Willemsen** [comment]
It makes sense for https://github.com/ISISComputingGroup/IBEX/issues/4592 to be done first.

**Comment by Tom-Willemsen** [comment]
PR at https://github.com/ISISNeutronMuon/InstrumentScripts/pull/66

(Note: fast shutter commands are not needed as part of do_sans/do_trans any more as they are now done automatically on any `begin`/`end` - see https://github.com/ISISComputingGroup/IBEX/issues/4590 for details)

I will check with the scientists that differences in behaviour between the scans library and their existing do_sans/do_trans commands are acceptable.
