### ISSUE TITLE
SANS2D: Scraper Aperture

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4592]
As a SANS2D scientist, I want IBEX to provide me with an OPI for the scraper aperture, so that I can control it.

#### Acceptance Criteria
1. The Scraper Aperture OPI should have a "user" tab and an "advanced" tab
1. Using the "normal" tab, I can use the IBEX GUI to
   1. move the scraper aperture to a named motion set-point
   1. IBEX allows me to select from the following named set-points:
         * Small
         * Medium
         * Large
         * Extra-Large
1. Using the "advanced" tab, I can use the IBEX GUI to
   1. move the scraper aperture to any position in its range
1. The IBEX GUI provides me with a STOP button, to stop the movement of the Scraper Aperture
1. The IBEX GUI provides me with vacuum status indicator (indicating the status of the guide/aperture vacuum)
1. I can move the scraper aperture to any named position using genie_python.
1. I can move the scraper aperture to any position in its range using genie_python.

#### Notes
1. This ticket is a sub-ticket of #4589.
1. The scraper aperture is usually moved using the named motion set-points.  Occasionally, the scientists will run a scan of the scraper aperture to check the validity of the motion set-points.
1. See also #4591 to understand how the named positions relate to the DO_SANS and DO_TRANS commands.
1. In SECI, the set points are defined in the file `C:\LabVIEW Modules\Instruments\Drivers\Motion Control\S2D Sample Changer.ini`. (yes, sample changer, because SECI uses the sample changer VI to control the scraper aperture).
1. There is a schematic diagram showing the how the [SANS2D Scraper Aperture OPIs (user and advanced)]( http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Scraper_OPI.pdf) could look.
1. Check the paragraph describing the S6 (Scraper) Aperture in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by DominicOram** [comment]
This is controlled via a Galil

**Comment by Tom-Willemsen** [comment]
- OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1135
- Motion set points configured on configs repo branch `NDXSANS2D` on motor `0507` (`GALIL_05`)
- Positions taken from `LabVIEW Modules\Drivers\Motion Control\Sample Changer\Sample Changer Positions 1.ini`
