### ISSUE TITLE
SANS2D: Sample Parameters

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4593]
As a SANS2D scientist, I want to define sample parameters via genie_python script, so that IBEX can record them in the NeXus file.

#### Acceptance Criteria
1. I can use the genie_python to:
   1. define the geometry of the A2 aperture
   1. define the size of the A2 aperture
   1. define the thickness of the sample
1. The settings of the A2 aperture and sample thickness are recorded in the NeXus file (to be picked up by Mantid).

#### Notes
1. This ticket is a sub-ticket of #4589.
1. The A2 aperture can only be controlled manually (for the avoidance of doubt, there is no requirement for remote control of the A2 aperture).  The purpose of this ticket is simply to provide a way for scientists to record the setting of the A2 aperture, so that they can be passed to Mantid.
1. Check the paragraphs describing the A2 Aperture and Sample in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by FreddieAkeroyd** [comment]
This should already be in place - LOQ has an Aperture 2 and its values is recorded in the NeXus file

**Comment by kjwoodsISIS** [comment]
OK, great.  How is it done on LOQ?  Do we have the names of the relevant script(s)?

**Comment by DominicOram** [comment]
A2 size is a beamline parameter that can be written to using `g.set_beamline_par()` and sample thickness is a sample parameter that can be set with `g.set_sample_par()` both can be changed in the `Experiment Details` screen in the GUI. I don't see anywhere for A2 geometry to be set, is this in IBEX @FreddieAkeroyd?

**Comment by FreddieAkeroyd** [comment]
There wasn't an A2 geometry in SECI, just size. There is a sample geometry. @kjwoodsISIS did you mean "sample geometry" rather than "geometry of the A2 aperture"?

**Comment by Kevin-Woods-Tessella** [comment]
I mean what is said in the scientists "Beam_line_descriptors" document (link above), which says this:
"**A2:**	final apertures that defines the beam size at the sample.  The only SECI/IBEX requirement is that it’s geometry and size are input in scripts and then picked up in Mantid for data reduction.
**Sample:**	The only SECI/IBEX requirement is that it’s thickness is input in scripts and then picked up in Mantid for data reduction."
The scientists clearly think that the A2 aperture has two parameters - geometry & size - while the sample has only one - thickness.  Perhaps they are wrong?

**Comment by FreddieAkeroyd** [comment]
I'll ask Sarah what was intended/required

**Comment by DominicOram** [comment]
@FreddieAkeroyd did you ask about this in the end?

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd any updates from the scientist?

**Comment by kjwoodsISIS** [comment]
I will ask Sarah.

**Comment by kjwoodsISIS** [comment]
Here is Sarah's response:

> A2 is the aperture of the end of the snout.
> 
> To answer your question (I think!) this is defined in SECI in the Experiment Details section and then in the Sample Parameters table where there is Sample Geometry (which is either disc, Flat plate or cylinder - and these need to match the Mantid description of sample shape/geometry or they are not picked up correctly in a reduction) and then Sample Height (which is the height of A2 in mm) and Sample Width (which is the width of A2 in mm).  If disc (i.e. a circular A2) is selected then height and width are the same but often a rectangular or square A2 is used and then these two values can be different.  We use cylinder very infrequently as we usually try and make our samples look like flat plates by under illuminating the sample!  We also use the Sample Thickness from the Sample Parameters table in the same way.  All these parameters are used in Mantid and are there so we can calculate the sample volume in the beam.
> 
> Currently in our scripts (usually towards the top before we start any measurement) we set these as follows, for example:
> 
> `Sample_par width=8 height=8 thickness=2 geometry="Disc"`
> 
> And then if we we’re using the sample changer (where the thickness of cuvette can vary from sample to sample) we also have the thickness in our move command:
> `MOVE pos="AT" thick=2 uAhr=6 title="RB2010810_Tris_buffer_D2O_TRANS"`
> 
> Larmor, Zoom and Loq are already doing all of the above so I don’t think there’s anything new that needs doing for Sans2d.
> 
> In addition to this I will also say the following.  We discussed the use of Beamline Parameter box in a meeting onsite (quite a while ago) and this box is redundant for Sans2d (for all the SANS beamlines to be honest and we only use it on Loq out of habit from when those parameters were used in Colette!).  Loq used the Table Names of Aperture 1, 2 and 3 (incorrectly strictly speaking as SANS beamline only have two apertures and they are pin-hole instruments) to describe the size of the beam entering the beamline, a scraper aperture part way down the instrument and the size of the beam hitting the sample.  For the data reduction we only care about the final aperture and as long as the other parameters are logged (which they are on Sans2d as blocks – this is not the case for the first aperture on Loq but we never change this as the movement is not trustworthy and to be honest it doesn’t need to change).  All the other beamline parameter we use for reduction (such as beam centre and primary flight path) are either in the Mantid instrument definition file or in the user files (which are usually the offsets from the standard positions).

**Comment by kjwoodsISIS** [comment]
I suspect that what IBEX does already is sufficient - because LARMOR, ZOOM & LOQ seem to be happy.  However, I think what Sarah's response shows is that current practice relies on a lot of history and undocumented convention.  It would be good to document the convention.

**Comment by FreddieAkeroyd** [comment]
OK, to summarise what I know from Sarah. Sample height, width and geometry refer to the aperture A2 - this dictates the size and shape of the beam on the sample, which is the effective sample size. Sample thickness refers to the real sample thickness, so from these values they can calculate a sample volume.  LOQ was named differently: A2 on LOQ is S6 on SANS2D, A3 on LOQ is A2 on SANS2D. The MOVE command sets the "Aperture 2 Diameter" beamline parameter (meaning A2 on LOQ, but S6 on SANS2D), however this beamline parameter is not used by Mantid - I think it was just used by the old VMS Colette analysis program. 

So from an IBEX point of view all we need to do is set the sample width, height, thickness and geometry from genie_python and GUI, which we can already do.
