### ISSUE TITLE
SANS2D: Monitor Detector Temperatures IOC and OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4594]
As a SANS2D scientist, I want IBEX to display the temperatures of the detectors, so that I can monitor them during my experiments.

#### Acceptance Criteria
1. IBEX provides an IOC for the Superlogics 8018R 8-channel thermocouple.
1. Using the IBEX GUI, I can:
   1. monitor the value of the temperature from any one of the 8 input channels.
   1. plot a graph showing temperature as a function of time for each of the 8 input channels.
1. Using genie_python, I can obtain the value of the temperature for each of the 8 input channels.

#### Notes
1. This ticket is a sub-ticket of #4589.
1. There are 4 temperature sensors on each of the two detector panels
1. The [Superlogics 8018R 8-channel thermocouple](https://www.superlogics.com/data-acquisition-99/data-acq-sensor-specific/sensor-specific-rs485/8018.html) is a read-only device.
   * ENGIN-X also uses a Superlogics 8018 device.
1. The Superlogics 8018R 8-channel thermocouple is used on SANS2D to monitor the detector temperatures.
1. For more details, consult the [SANS2D Instrument page](https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details).
1. There is a schematic diagram showing the how the [SANS2D Detector Temperatures OPI]( http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Det_Temperature_OPI.pdf) could look.
1. Check the paragraph describing the Detector Temperature VI in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
Current OPI:

![image](https://user-images.githubusercontent.com/7570055/61621588-209aba00-ac6b-11e9-8d8a-81e0e79cd75e.png)

**Comment by kjwoodsISIS** [comment]
Yes, the existing OPI would be a good basis for an OPI for SANS2D.  The strain graph is not relevant to SANS2D.

**Comment by John-Holt-Tessella** [comment]
Make into two linking containers and then separate IOC one for "superlogics" and one for ENGINX

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/511
- https://github.com/ISISComputingGroup/EPICS-superlogics/pull/3
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/340
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/82
- https://github.com/ISISComputingGroup/ibex_gui/pull/1142
