### ISSUE TITLE
SANS2D: Control "Big" Jaws

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4595]
As a scientist working on SANS2D, I need to control the "Big" jaws on SANS2D.

#### Acceptance Criteria
1. I can use the IBEX GUI to control the jaw centre and gaps
1. I can use the IBEX GUI to control the positions of the jaw blades
1. I can use the IBEX GUI to set the jaw blades to named positions
1. I can use genie_python to control the jaw centre and gaps
1. I can use genie_python to control the positions of the jaw blades
1. I can use genie_python to set the jaw blades to named positions
1. The "big" jaw motors are de-energised when motion is complete.
1. IBEX provides the same level of functionality as SECI

#### Notes
1. The "big" jaws are located in the SANS2D vacuum tank, which means the motors operate under vacuum.  The motors *MUST* be de-energised when a move is complete (otherwise they are at risk of over-heating).
1. The "big" jaws are custom jaws, driven by Galils
1. For more details, consult the [SANS2D Instrument page](https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details).
1. See also [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) for more information about the "big" jaws.
1. The "SAMPLE Jaws" motors are split over crate 1 and 2 and so if the "BIG" Jaws use the sample jaws the jaws db will need to be split and tested.

**Comment by John-Holt-Tessella** [comment]
Current motors auto de-energise, unless the feature is switched off, do we need to but an extra-alarm/check on the energised status?

**Comment by Kevin-Woods-Tessella** [comment]
If the default is for "auto de-energise" to be switched on, it might be worth having a light on the OPI that illuminates when the motors are energised.  That way it will be unlit when the motion stops - if it does remain lit, it should be obvious to the scientist.  the same consideration could apply to all devices on the SANS2D vacuum tank.

**Comment by Tom-Willemsen** [comment]
PRs for adding a multi-galil controller:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/343
- https://github.com/ISISComputingGroup/EPICS-jaws/pull/12
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/516

Jaws settings have been pushed to SANS2D config branch, assuming the motors are set up in the following way:
- `GALILMUL_01` controlling motor controllers 1 & 2
- `GALIL_03` controlling motor controller 3
