### ISSUE TITLE
SANS2D: Control "Little" Jaws

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4596]
As a scientist working on SANS2D, I need to control the "little" jaws on SANS2D when I am performing GISANS experiments

#### Acceptance Criteria
1. I can use the IBEX GUI to control the jaw centre and gaps
1. I can use the IBEX GUI to control the positions of the jaw blades
1. I can use genie_python to control the jaw centre and gaps
1. I can use genie_python to control the positions of the jaw blades
1. IBEX provides the same level of functionality as SECI

#### Notes
1. The "little" jaws are standard JJ-Xray jaws, connected to a moveable Galil rack.  They are installed on SANS2D only when performing GISANS experiments.
1. For more details, consult the [SANS2D Instrument page](https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details).
1. The "SAMPLE Jaws" motors are split over crate 1 and 2 and so if the "Little" Jaws use the sample jaws the jaws db will need to be split and tested.

**Comment by John-Holt-Tessella** [comment]
We already have jaws in IBEX is the level of functionality the same as in SECI? How would I test that?
To implement this ticket is this anything more than configuration?

**Comment by KathrynBaker** [comment]
Moveable Galil rack provides this variation - so there is probably component level configuration for that and some specific instructions needed for the scientist.

**Comment by kjwoodsISIS** [comment]
I would expect our current jaws IOC/OPI is sufficient for the SANS2D little jaws (many of the jaws that we control are JJ-XRay jaws).  In that sense, this ticket should be a matter of configuration.

However, it is worth checking the existing SECI configs  & VIs on SANS2D, to make sure there isn't some special customised thing that was done specifically for SANS2D.  Also worth double-checking the axes conventions.  On SANS2D, the z-axis is parallel to the direction of neutron flight, so increasing x moves right, decreasing x moves left, increasing y moves up, decreasing y moves down.  I believe this matches our current jaws convention.

**Comment by Tom-Willemsen** [comment]
Review with https://github.com/ISISComputingGroup/IBEX/issues/4595
