### ISSUE TITLE
MARI: cannot stop fermi chopper (stuck com port)

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4598]
MARI phoned the support phone because they could not stop their fermi chopper.

On investigation, this was a re-occurence of https://github.com/ISISComputingGroup/IBEX/issues/4420 (stuck com ports) meaning that the IOC could not send or recieve any bytes.

@FreddieAkeroyd and I tested with the overlapped IO changes in https://github.com/ISISComputingGroup/IBEX/issues/4435 , this did not fix the issue immediately. Instead it caused the connection to the port to appear to close under the IOC (but it still appeared "in use", so neither a `mode` command nor the IOC could reconnect to the port).

Using the overlapped IO dll and `epicsEnvSet("WAITFORBYTES",1)` at the top of the `st.cmd`, normal comms were re-established and the IOC worked again as normal.

**Comment by FreddieAkeroyd** [comment]
Setting WAITFORBYTES to 1 causes the IOC to only read a com port if there are bytes available, something strange seems to happen on these ports if you do a "read with timeout" before bytes are available. From adding event tracing it looks like the bytes arrive in the previous case but are not picked up.

I propose making the additional code used by setting WAITFORBYTES==1 to be made the default in the PR, also i propose moving to overlapped IO as it gives us more options in the case of a stuck port as it does not totally hang the IOC but instead disconnects the port and retries an open

**Comment by FreddieAkeroyd** [comment]
Procedure followed was as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Serial-Port-Debug
