### ISSUE TITLE
EPICS 7: tidy up existing infrastructure in preparation

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4599]
As a developer i would like the existing build infrastructure to be ready for EPICS 7

In preparation for a move to EPICS 7 several modules need to be updated and small edits made to others: 
* The EPICS busy, calc, gateway and motor modules need to be updated
* It looks like the areaDetector module just needs a few small EPIC7 changes backported, mainly related to changes in epics v4 function syntax between releases
* Some other modules need minor local changes, usually related to testing the epics version and deciding which code path to use. Often they assume 3.* and so only tested the 14.8 part of  3.14.8 etc so get it wrong with 7.0.2. I expect this is fixed in later releases, but a one line local change to our existing modules seems to be sufficient. 

For initial preparation:
* Update modules (busy, calc etc) and apply epics 7 related fixes to our other modules
* Check ibex builds and starts as expected with our existing 3.15 base

The procServControl module makes heavy use of the busy record, we should also run some manual tests on galils with the newer motor record.

**Comment by Tom-Willemsen** [comment]
I think we should only merge this after the release as it contains some pretty large changes to some core modules e.g. gateway, calc, motor, busy. Please move into impeded (awaiting release) once the rework is done.

In addition, I couldn't find anything on the wiki about why some of these changes had to be made. Please add the reasoning behind these changes to the wiki (e.g. library ordering, variables which had to be renamed, extra headers that needed to be included etc)

**Comment by FreddieAkeroyd** [comment]
Link ordering on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Libraries-to-include-with-order

**Comment by FreddieAkeroyd** [comment]
callback.h notes added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Compile-Errors

**Comment by FreddieAkeroyd** [comment]
Brief summary of changes

* sscan seq pv need to be after calc as new module depends on them
* pcas is a new module because pcas is no longer part of epics base
* cas and gdd libraries are not in new pcas module
* a new macro EPICS_BASE_PVA_CORE_LIBS for epics v4 linking
* many modules assumed EPICS_VERSION was always 3 and only checked EPICS_REVISION
* hvcaen needed windows.h included to stop clash with callback.h

**Comment by FreddieAkeroyd** [comment]
Moving to impeded awaiting release
