### ISSUE TITLE
IBEX GUI: Place instrument status in the sidebar

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4600]
As a scientist or user I have limited screen space for my control system and the information it provides. I would like to be able to have more screen available for blocks and other perspective OPI's, such as scripting, data plots and, device interfaces. At the same time I would like a clear indication of my instrument status.

In this mock GUI you can see a more compressed but clear instrument status tab is moved to the right hand sidebar:

![gui](https://user-images.githubusercontent.com/43140680/61700070-f9f48600-ad33-11e9-833f-b3321739785a.PNG)

Potentially this could be in a permanent move, or alternatively the ability to move the view into the sidebar and let users choose the formatting.

**Comment by GRyall** [comment]
We've not had any further requests for this and we have since added more things on the sidebar. Can reopen if there is a user request.
