### ISSUE TITLE
SANS2D: Live Display

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4608]
As a scientist working on SANS2D, I need a live view of my detectors.

#### Acceptance Criteria
1. For the front detector:
   1. the IBEX GUI displays a live view of the front detector.
   1. the IBEX GUI displays the current whole detector count rate.
   1. the IBEX GUI displays the current spectrum count rate.
   1. the IBEX GUI displays the maximum whole detector count rate.
   1. the IBEX GUI displays the maximum spectrum count rate.
   1. I can use genie_python to obtain the whole detector count rate and spectrum count rate.
   1. I can use genie_python to set maximum safe whole detector and spectrum count rates.
   1. if the maximum safe whole detector or spectrum count rates are exceeded, the fast shutter is closed.
1. For the rear detector:
   1. the IBEX GUI displays a live view of the rear detector.
   1. the IBEX GUI displays the current whole detector count rate.
   1. the IBEX GUI displays the current spectrum count rate.
   1. the IBEX GUI displays the maximum whole detector count rate.
   1. the IBEX GUI displays the maximum spectrum count rate.
   1. I can use genie_python to obtain the whole detector count rate and spectrum count rate.
   1. I can use genie_python to set maximum safe whole detector and spectrum count rates.
   1. if the maximum safe whole detector or spectrum count rates are exceeded, the fast shutter is closed.
1. IBEX provides at least the same level of functionality as the SECI live view

#### Notes
1. This ticket is a sub-ticket of #4589.
1. LOQ also has two live views.  The SANS2D solution could be similar.
   1. the maximum safe whole detector and spectrum count rates are not changed very often, so it is fine to change them via a command (as LOQ does).  Also users should not change these values, so using a command helps hide the functionality from users.
1. The fast shutter is controlled by the PLC.  If the maximum safe whole detector or spectrum count rates are exceeded, all IBEX 
1. Check the paragraph describing the Live Display in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd write numbers on this ticket

**Comment by DominicOram** [comment]
Main part of this is doing the fast shutter logic, rest is mostly configuration.

**Comment by FreddieAkeroyd** [comment]
Both detectors are 120 * 512 pixels = 61440 spectra
One detector starts at spectrum number 122889    
The other starts at spectrum 184329

**Comment by Adam-Szw** [comment]
DAE live view updated on NDXSANS2D using commented numbers
PR: https://github.com/ISISComputingGroup/EPICS-ioc/pull/653 - shutter logic

**Comment by Adam-Szw** [comment]
Updated everything to work with new sim records
New tests PR: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/523
