### ISSUE TITLE
Fix IOC System tests

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4611]
As a developer I want to be able to rely on my system tests to know if something is wrong with a device. Currently the following tests are failing consistently:

* Attocube
* GEM jaws manager
* POLARIS jaws manager

**Comment by DominicOram** [comment]
Two linked PRs may fix this, can the review merge them (assuming they are good) and not close this ticket unless the system tests pass through jenkins

**Comment by Tom-Willemsen** [comment]
merged prs above, ticket impeded until we see whether they fix the jenkins builds.

**Comment by DominicOram** [comment]
I believe the rest of the linked PRs will fix the tests. Probably best to merge, let them run then call this complete.
