### ISSUE TITLE
Copy dependent DLLs for IOC

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4612]
As a developer I would like to have all the dlls required for an IOC to be copied to the IOC directory, this would make it easy to deploy e.g. a DEBUG ioc to an instrument for testing

Acceptance criteria:

- a   dllCopy.bat   file is created in the iocBoot directory
-  running dllCopy.bat copies all required dlls to the bin/{epics-host-arch} directory
- this could be verified by running the depends program on the IOC EXE file

**Comment by FreddieAkeroyd** [comment]
This is to enable https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deploying-a-DEBUG-build-IOC for testing the galil

**Comment by DominicOram** [comment]
Am I right that the build area referenced in the documentation corresponds to [this](http://epics-jenkins.isis.rl.ac.uk/job/EPICS_IOC_Windows7_x64_static_DEBUG_CLEAN/) Jenkins job? If so, that job has been disabled for some time, do we need to restart it?

**Comment by DominicOram** [comment]
The documentation also says:

> Copy the EXE and all DLL files from the kits/{ioc}/bin/windows-x64-debug directory to the bin/windows-x64 of the target IOC.

Does this mean the DLL files that `dllCopy.bat` puts in iocBoot or am I expecting some DLLs to be in the `windows-x64-debug` folder? Do these DLLs need to be in the same folder as `runIOC.bat`? If not they quickly make the folder quite messy, can we put them in their own folder?

**Comment by FreddieAkeroyd** [comment]
The dllCopy.bat is for use with EPICS_DEBUG_CLEAN_win7_x64 (or any other DLL build) and not EPICS_STATIC_DEBUG_CLEAN_win7_x64 (there are no DLLs to copy in a static build). I have corrected the wiki page. It looks like last nights DLL DEBUG build failed with a git reset error, looks to have passed the checkout this time. The EPICS_STATIC_DEBUG_CLEAN_win7_x64 is disabled as i think it was huge and filled up the build server, we may want to enable it again on a different computer as it is convenient but sometime static builds do not show the same issues as dll builds so it depends what you are trying to debug

**Comment by FreddieAkeroyd** [comment]
dllCopy.bat should not put any files in iocboot, it should put them all in  kits/{ioc}/bin/windows-x64-debug  directory where the ioc exe is and from where you copy them to the target. The DLLs will not work if they are in the same folder as runIOC.bat, they need to be in the same folder as the ioc EXE so they override any paths set by runIOC.bat / dllPATH.bat on the target.  If they were not in the same directory as the IOC exe then we would also have to edit dllPATH.bat on the target computer, if we stick them all in the same folder we don't have to which i though was a simpler approach. We would not be running dllCopy in general, only if we need to debug or replace an ioc on a specific computer

**Comment by DominicOram** [comment]
Thanks for updating the docs. Disregard the second question, I hadn't rebuilt `base` and so was getting copies in the wrong place.
