### ISSUE TITLE
Disk space: MARI & MERLIN

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4615]
Look after machines before their hard disks completely run out. Nagios "critical" warnings for disk space:

- [x] MARI: 6.1 GB free on C:
- [x] MERLIN: 8.5 GB free on C:

**Comment by Tom-Willemsen** [comment]
Databases trimmed and old log files moved to `\\isis\shares\ISIS_Experimental_Controls\FilesMovedFromInstruments`

- MARI now has 16.8 GB free (machine has a very large windows directory at 33GB - EPICS has been trimmed to it's minimum).
- MERLIN now has 30.7 GB free

**Comment by kjwoodsISIS** [comment]
Why is MARI's Windows directory so large?  Can it be reduced? (perhaps via a separate ControlsWork ticket?).

**Comment by Alistair-McGann-Tessella** [comment]
Confirmed that the disk space has been reclaimed
