### ISSUE TITLE
Attocube: Behave properly on comms errors

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4618]
As a user of the attocube motor I would like to be properly informed if I lose comms on the device. The emulator does do this and the IOC will go into alarm on some developer machines but not on the build server. Comms alarms are also cleared when the IOC is written to. This ticket is to do the following:

* Confirm the behaviour of the IOC with the real device when it is disconnected
* Ensure the behaviour is the same with the emulator
* Fix the IOC such that it gives comms alarms reliably and that these alarms persist

**Comment by DominicOram** [comment]
Behaviour on the real device was, after powering off the device the device went into alarm showing:
![image](https://user-images.githubusercontent.com/10086797/62376623-fda8b980-b538-11e9-8978-9f075e89fde4.png)

It took a while ~ 1 minute to go into this state, ideally this would be faster. When the motor PV was written to whilst the IOC was in this state it cleared the alarm, this behaviour should not happen.

**Comment by ChrisColeExpControl** [comment]
For some reason the IOC was waiting for 200 comm errors before raising an alarm, this has now been lowered to 20 to speed things up. When PVs are written to, alarms are cleared, but the IOC should go back into error when it next tries to read from the controller. It used to skip over a part of the code which calls callbacks naturally, so now callbacks are forced whenever reads result in comm errors.
