### ISSUE TITLE
IBEX_wiki_checker: Update to maintained spell-check libary 

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4620]
As a developer I would like the libraries used in my projected to be maintained. The Pyenchant library is officially no longer maintained: [Git comment](https://github.com/rfk/pyenchant/commit/4df35b72a685505546998fadfd0aeaa4cc530429).

Some alternatives are:
1. Hunspell: [Repo](https://github.com/blatinier/pyhunspell)
1. Spellchecker: [Repo](https://github.com/barrust/pyspellchecker)

## Acceptance Criteria
- [ ] The spell check library used by the wiki checker is updated and maintained

**Comment by RaiBishal** [comment]
Pull Request
https://github.com/ISISComputingGroup/ibex_wiki_checker/pull/4

**Comment by RaiBishal** [comment]
Libraries looked at:
PySpellChecker: Very limited words in its internal dictionary and not being able to recognize a wide range of words.

Hunspell: It is bonded to C hunspell library and requires additional so it needs to be compiled beforehand.

JamSpell: Requires SWIG to be installed as it also contains some C/C++ code in its library.

**Comment by Tom-Willemsen** [comment]
The linked PR implies that this should be closed as a wontfix - is there any further work that needs doing?
