### ISSUE TITLE
SXD Attocube: Initial commissioning 

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4623]
As a user on SXD I would like to be able to use my new goniometer, part of which is controlled with an Attocube controller. The basic communications of this were confirmed in https://github.com/ISISComputingGroup/IBEX/issues/3854 but further testing with an axis is required.

**Comment by DominicOram** [comment]
Testing revealed the following issues:
1) The voltage driving the stage should be 60V, it resets to 30V on power outage
2) Motion was only possible between 1 and 330 degrees
3) The Attocube screen will occasionally freeze up
4) The axis needs to be powered on to send commands to it, it is not powered on when the Attocube is first powered up
5) The device retry deadband defaults to a single motor step, given that the device is jittery this causes a lot of retries
6) The PV reads in `um` rather than degrees and reads 10x the value that is displayed on the front of the controller.

**Comment by Tom-Willemsen** [comment]
timebox to 1 day

**Comment by DominicOram** [comment]
1) Fixed by setting `CMD:WR_AMPL` to 60000 and autosaving it
2) Artefact of the hardware, scientists are aware
3) Controller needs returning to supplier, we will do this at some point in the future, scientists are aware
4) See below
5) Set retry of 0
6) Set motor resolution to 0.0001 and units in degrees

**Comment by DominicOram** [comment]
The following script can be used to get/set channels on the device. It can be tested against the updated emulator at https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/47 using: `do_get(0x400)`, `do_set(0x400, 100)`, `do_get(0x400)`. This can be used with the list in https://github.com/ISISComputingGroup/EPICS-attocubeANC350/blob/master/docs/ANC350_Developers_Manual.pdf to see what command needs to be sent for 4) on the list above. This is the part of the ticket that is timeboxed to 1 day.
```python
import socket
import sys

BYTE = 2**8
BYTES_IN_INT = 4

UC_REASON_OK = 0  # All ok

UC_SET = 0  # Set command
UC_GET = 1  # Get command
UC_ACK = 3  # Ack command

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
server_address = ('localhost', 57677)
print(sys.stderr, 'connecting to %s port %s' % server_address)
sock.connect(server_address)

def raw_bytes_to_int(raw_bytes):
    multiplier = 1
    result = 0
    for b in raw_bytes:
        result += ord(b) * multiplier
        multiplier *= BYTE
    return result

def convert_to_ints(command, start, end):
    return [raw_bytes_to_int(command[x:x + BYTES_IN_INT]) for x in range(start, end, BYTES_IN_INT)]

def int_to_raw_bytes(integer):
    result = r""
    for index in range(BYTES_IN_INT):
        result += chr((integer // (BYTE**index)) % BYTE)
    return result

def generate_packet(address, is_set, index, correlation_num, data=None):
    int_responses = [UC_SET if is_set else UC_GET, address, index, correlation_num]
    if data is not None:
        int_responses.append(data)
    response = "".join(int_to_raw_bytes(x) for x in int_responses)
    print("Sending {}".format(response))
    return int_to_raw_bytes(len(response)) + response

def get_response(expected_bytes):
    amount_received = 0
    recieved_data = bytes()
    while amount_received < expected_bytes:
        recieved_data += sock.recv(expected_bytes)
        amount_received = len(recieved_data)
    return recieved_data

def do_get(address):
    global sock
    sock.sendall(generate_packet(address, False, 0, 0))

    data = get_response(28)

    ints = convert_to_ints(data, 0, len(data))

    return ints[-1]

def do_set(address, data):
    global sock
    sock.sendall(generate_packet(address, True, 0, 1, data))

    recieved_data = get_response(20)

    ints = convert_to_ints(recieved_data, 0, len(recieved_data))

    if ints[1] == UC_ACK and ints[4] == 1:
        print("Set successfully")
```

**Comment by DominicOram** [comment]
@JamesKingWork and I spent a while looking through wireshark and found that the command is `0x3030`, this isn't documented anywhere

**Comment by DominicOram** [comment]
Putting this into review for someone to look at code changes before deploying to SXD. All other changes mentioned above should be done during commissioning on SXD. @JamesKingWork and I confirmed with the hardware that 4) has been fixed by the above PRs

**Comment by Tom-Willemsen** [comment]
@DominicOram are you really reviewing your own ticket or was that a mistake?

**Comment by DominicOram** [comment]
Oops, apologies
