### ISSUE TITLE
GUI: improvements to setting macros

### ISSUE THREAD

**Issue by adamb56789** [ISISComputingGroup/IBEX#4624]
As an instrument scientist I want to be able to set an IOC's macros more easily and clearly.

1. The dialog should not sometimes break (#2981)
1. Default values should populate the table if the macro is not set (#2328)
1. There should be an extra column with the header "Use Default" which is ticked by default, which controls the above point
1. Values should be edited directly in the table cell as opposed to a separate box at the bottom
1. If the user clicks in the value cell to edit it while "Use Default" is ticked, "Use Default" is automatically unticked and an empty string will be placed in the value cell
1. The width of the dialog box should be increased to fit everything

This should ensure that it is clear whether a macro isn't set at all (so uses the default), or is set to nothing (a blank string, i.e ""). At the moment the behaviour is both unclear and inconsistent.

These changes will remove the need for a "Clear Macro" button, as its function (or intended function, as it currently doesn't work) will be covered by the "Use Default" tick box. The ticket #4614 to fix this button would therefore be redundant.
Once this ticket has been completed, #2328, #2981, and #4614 can be closed.

**Comment by adamb56789** [comment]
### Pull requests
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/933)
[DatabaseServer]()
[EPICS IOC]()

These separate IOCs also had macros:
[CHIPIR Collimator](https://github.com/ISISComputingGroup/EPICS-CHIPIR_Collimator/pull/2)
[CHIPIR FIlter Set](https://github.com/ISISComputingGroup/EPICS-CHIPIR_Filter_Set/pull/2)
[Chipir LV FP](https://github.com/ISISComputingGroup/EPICS-Chipir_LV_FP/pull/2)
[Chipir XYZ](https://github.com/ISISComputingGroup/EPICS-Chipir_XYZ/pull/2)
[Chopper sim](https://github.com/ISISComputingGroup/EPICS-Chopper_sim/pull/2)

### Documentation
- Updated example on [The DatabaseServer](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/The-DatabaseServer) to match new format
- Added information to [IOC Finishing Touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches) about the macro default values
- From the user manual, updated [Create and Manage Configurations](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Create-And-Manage-Configurations)

Run `make iocstartup` and restart the DatebaseServer and the GUI after changes have been made to the `config.xml` files.

**Comment by DominicOram** [comment]
I started the review of this but wanted to put it into rework to better split the logic in the GUI. Can someone else please review my changes.
