### ISSUE TITLE
ENGIN-X: stress rig scripting

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4627]
As an instrument scientist on Engin-X I would like my stress rig scripts to work correctly.

> I noticed a bug in the stressrig_file_scan() command recently. The command does not seem to apply and update the step time specified in the input script (from the directory C:\scripts\stressrig\) in the stress_rig.opi instead it will just wait for the duration of the step time specified. 
An example stress rig input script is as follows: 

```
SigmaAld_RT                                     
1                                              
3                                              
stress    200         50           10
stress    300         100         10
stress    500         150         10
```

> The second column is the target stress value and the third column is the stress_step_time and the fourth column is the count microamps. 
The stressrig_file_scan() command can be found in `...\Python\inst\stress_rig.py`. I am afraid that I am unable to find the bug in the stress_rig.py script. The current workaround that we have is to write a new Python script to set the step time first before the setpoint to the target stress/position value.
```
inst.stress_rig._update_control_channel("position") #Change to Position Control
inst.stress_rig._set_stressrig_value(PositionRate, "pos_step_time") #Set position ramp time
inst.stress_rig._set_stressrig_setpoint(NewPosition, PositionRate, "position") #Goto target position
```

**Comment by Tom-Willemsen** [comment]
Unable to reproduce bug against emulator, which suggests it may not be a scripting problem - may be a timing condition or similar with the real hardware. Have replied to Tung asking if we can get some time to test this on the real stress rig.

**Comment by kjwoodsISIS** [comment]
> From: ICP On Behalf Of Thomas Willemsen - UKRI STFC
> Sent: 08 August 2019 09:36
> To: Lee, Tung Lik (STFC,RAL,ISIS)
> Cc: Instrument Control Project List
> Subject: Re: [ICP] Bug in ENGIN-X IBEX stressrig_file_scan command
> 
> Hi Tung,
> 
> I’ve had a look through the script and couldn’t see anything obviously wrong that would cause 
> this bug. I then ran the file “C:\scripts\stressrig\Tung_Sigma.txt” with the ENGIN-X scripts against 
> our stress rig emulator, and couldn’t reproduce the fault (it did put the requested step times from 
> the file into the step time box on the OPI, and from there passed it to the emulator etc).
> 
> It is possible that this is a timing condition with the real stress rig where it rejects commands 
> under certain circumstances – to diagnose this, we would have to test it against the real stress rig. 
> Would it be possible to get the rig set up at a convenient time while the beam is off so that we 
> can try to reproduce & fix the problem?
> 
> Thanks,
> Tom

**Comment by Tom-Willemsen** [comment]
Tung has offered to set up the stress rig on Monday for us to diagnose this issue. Impeded until then.

**Comment by Tom-Willemsen** [comment]
Met with Tung on ENGIN-X with real stress rig to test this.

As it turns out, the file provided above does *not* reproduce the issue (which is why I could not see an issue against the emulator). The issue only existed in `rpos`, `rstress` and `rstrain` modes (relative position, stress and strain). 

This was purely a python scripting issue - the relative modes never called the command to set the step time. This has now been modified in ENGINX's instrument scripts and tested with the real rig in the presence of a scientist (in position control mode, as no sample was mounted).

**Comment by DominicOram** [comment]
Changes in script look sensible.
