### ISSUE TITLE
NIMROD: Train Instrument Scientists

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#4628]
As a NIMROD scientist, I would like to be be trained in how to use IBEX.

#### Acceptance Criteria
1. NIMROD scientists receive training in use of IBEX ahead of Cycle 2019/02.

#### Notes
1. NIMROD is the only instrument being migrated for Cycle 2019/02.  
1. There are two NIMROD scientists.  
1. Most scientists in the Disordered Systems group are familiar with IBEX (from SANDALS); we can extend the training invitation to all members of the Disordered Systems group.
1. If we limit the scope of the training to NIMROD, there is no need for a full-scale training session in the Atlas Centre.

**Comment by kjwoodsISIS** [comment]
Training arranged for 09:30-12:30, Thursday, 5th September.
Location: NIMROD Cabin
Trainer: Tom Willemsen (provisional)

**Comment by Tom-Willemsen** [comment]
Training session was delivered this morning. Nothing to review for this ticket so moving straight to review complete.
