### ISSUE TITLE
genie_python: Lint script on load_script

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4630]
Umbrella ticket: [#4903](https://github.com/ISISComputingGroup/IBEX/issues/4903)

An LTR was reported on ZOOM where the "waitfor" command had been mistyped as "aitfor" and this was not picked up when loaded into genie python. As an instrument scientist I would like to lint python scripts when I load them so that I can avoid lost time (6 hours) if I mistype a command in my script. 

### Acceptance Criteria

1. On 'load_script', scripts are parsed through a linter and any error/warning sent to the user; the script is still loaded.
1. Linting can be turned off with a command-line argument in `load-script`
1. Linting catches the error where I misspelt `waitfor_time` as `aitfor_time`
1. Assert whether this fixes #4752 and #2205, if so close, otherwise add some detail.

**Comment by Tom-Willemsen** [comment]
If done as training, pair up with someone else

**Comment by Tom-Willemsen** [comment]
get rid of script checker

**Comment by RaiBishal** [comment]
Currently, the implementation of pylint does not allow us to detect errors such as when `g` or `inst` is redefined in the user script. 
So, we are using the pylint on top of our old script checker. However, some of the old script checker functionality is removed as it became redundant after implementing pylint.

**Comment by JamesKingWork** [comment]
> Check if we can get rid of the script checker after doing this ticket. (Close #2205)

As pylint cannot check for redefinitions of `g` and `inst` we must still use the script checker and as such #2205 is not solved.
