### ISSUE TITLE
Reflectometry: Check for limit violation on move

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4631]
As a reflectometry user, I would like to be made aware when a move I have issued violates limits of one of the motors involved. Currently, that motor will stay stationary while everything else moves ( the speed is calculated as if all motors will move). While unlikely given sensible motor limits, this can potentially lead to clashes.

Instead, it should be checked whether the move is valid for each axis based on the motor soft limits. If yes, proceed as normal. If not, do not issue the move and display a warning for an invalid move on the reflectometry IOC (set `REFL:BL:STAT` and `REFL:BL:MSG`). Essentially what individual motors do for soft limit violations, but on a beamline level.

Acceptance Criteria:
- Beamline does not allow invalid moves to go ahead
- Reflectometry IOC displays message when invalid move has failed
- Behaviour for valid moves is unchanged.

**Comment by John-Holt-Tessella** [comment]
Easiest way to do this is to return move not possible while asking for move duration. Would need cached soft limits on the motor

**Comment by will2201** [comment]
Branch name: Ticket4631_limit_violation_check

**Comment by rerpha** [comment]
We have this working, but we still need to add tests for: 
- Driver layer (test_ioc_driving_layer.py)
- Beamline (test_beamline.py) 

so that we test the whole stack in parts

**Comment by rerpha** [comment]
Tests should cover what has been added, but to manually test: 

- check out X in support\refl\master 
- check out ie. NDXOFFSPEC in your config area 
- start your server 
- change all GALIL IOCs in config to run under RECSIM
- set ie. 0601's soft limits (through ToM more details - > High limit/Low limit) to something very small ie. 1 and -1 respectively
- try and set `theta` in the reflectometry perspective - > front panel
- See that:
  - the motors do not move
  - an error is displayed in the reflectometry status
  - the error log tab shows the offending motors and their limits
