### ISSUE TITLE
GUI: Hide NICOS perspective

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4634]
Due to https://github.com/ISISComputingGroup/IBEX/issues/4511 we saw an extreme crash on IMAT last cycle. We should stop this happening next cycle by hiding the NICOS perspective in the next release. If we are confident that we have fixed the underlying issue before next cycle we can create a patch release for it.

**Comment by kjwoodsISIS** [comment]
How many points?
