### ISSUE TITLE
CRISP: Height stage travel limited in SECI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4635]
The height stage in SECI is not moving its full distance, investigate why. Is this caused by IBEX?

**Comment by John-Holt-Tessella** [comment]
resolution is email:

> I went down to CRISP today to test the behaviour of the height stage. I ascertained that CRISP does not set the soft limits in the Galil on startup. This may be because the SECI version on Crisp is older than the one David was looking at. These soft limits will make the motor stop before it reaches the limits in SECI. When I cleared the limits in SECI using the button in the tools page marked “clear axis limits” (approximate wording) the axis moved its full range again. (To test this I used IBEX limits 0 -> 3)
>
> I have now set the IBEX limits to be the same as SECI limits (-70 -> 66) but I am unsure whether these are correct. The axis should now move correctly. I think that we should try this on SURF to see if it has the same behaviour. In the future limit changes need to be done in both IBEX and SECI; this shouldn’t be too much of a problem because limits will not change often.

**Comment by FreddieAkeroyd** [comment]
Does this need adding to the developer wiki?

**Comment by DominicOram** [comment]
I agree with @FreddieAkeroyd, I can't find anything about this in the troubleshooting in the wiki

**Comment by davidkeymer** [comment]
Galil driver on NDXCRISP is out-of-date.  It does **not** contain the function for removing the soft limits on the Galil when the main table of motors VI starts.

Update required from SourceSafe.

**Comment by John-Holt-Tessella** [comment]
How much of a risk is it to update from source safe?

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SECI-Troubleshooting

**Comment by John-Holt-Tessella** [comment]
Last thing to do @davidkeymer will update CRISP

**Comment by davidkeymer** [comment]
Galil driver updated to latest version from SourceSafe (Backup created in `...\Drivers\` directory first).  SECI restarted and all axes seem to be reading OK, although nothing was asked to move.

Reviewer should check that the height stage can now travel over its entire range, after swapping to SECI from IBEX.
