### ISSUE TITLE
Unknown default IOC macros

### ISSUE THREAD

**Issue by adamb56789** [ISISComputingGroup/IBEX#4646]
As an instrument scientist I want to know for sure whether an IOC macro has a default or not. Currently there are about 100 macros in IOC `config.xml` files which have the attribute `hasDefault="UNKNOWN"`. It should be determined what the default actually is, if there is one, or whether there isn't a default.

This would mean that `hasDefault="UNKNOWN"` would no longer be used, and the `hasDefault` attribute can be got rid of entirely, as the presence or not of the `default` tag would completely replace its function.

This ticket is a follow up to #4624 to clear up technical debt. A script was used to get the default values where it could, but in some cases it still needs a person to check manually.

#### Acceptance criteria
- All macros either have a known default, or we know for sure that there isn't a default
- The `hasDefault` attribute is removed from the xml files, the database server, and the GUI

**Comment by DominicOram** [comment]
Could get the `build_ioc_startups.py` script in `EPICS\utils` to warn if there are defaults set to UNKNOWN

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS/pull/252
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/602
