### ISSUE TITLE
NIMROD: Gas Panel Support in SECI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4651]
As a NIMROD scientist, I want SECI to support the new gas panel, so that I can use it when running my experiments with SECI.

#### Acceptance Criteria
1. I can see, from the UI, whether the gas panel device is connected (i.e. a comms OK light).
1. I can view up to 4 pressure readings in the UI.
1. I can obtain any of the 4 pressure readings via an OpenGenie script.

#### Notes
1. See ticket #4056 for details of the MKS PR4000B pressure controller used in the gas panel.

**Comment by Tom-Willemsen** [comment]
Talk with scientists to figure out if this is actually required in SECI.

**Comment by davidkeymer** [comment]
I have done as @Tom-Willemsen suggested above.  One instrument scientist said it seems unlikely at this stage that a VI would be required for the gas panel as it will be used with well-tested equipment (Eurotherm, etc.).  However, he would like further testing and commissioning time with IBEX before making the final decision.

I shall check with him/them again in a couple of weeks...

**Comment by Tom-Willemsen** [comment]
@davidkeymer check ad close ticket if appropriate

**Comment by davidkeymer** [comment]
Confirmed with both instrument scientists that a LabVIEW driver is _not_ required for the pressure gauge in the gas panel.

Closing ticket...
