### ISSUE TITLE
Config Checker: Check that blocks point to interesting PVs

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4655]
As a user I would like to easily find any interesting PVs. There are many PVs that are currently not tagged as interesting but probably are. A good way to work out what the current PVs are that fall under this category is to have the config checker flag if someone is pointing a block to a non-interesting PV. A developer can then check this PV and either make it interesting if appropriate or have the config checker ignore it for future checks.

**Comment by John-Holt-Tessella** [comment]
Would it be better to rethink the interface and start listing all pvs associated with a device. Is it true that most devices have relatively few pvs that could be truned into blocks.

**Comment by DominicOram** [comment]
Well a better solution would be to use channel finder https://epics.anl.gov/meetings/2013-10/3%20-%20Other%20Services/2%20-%20ChannelFinder.pdf

**Comment by FreddieAkeroyd** [comment]
If we listed all pvs, then channel finder would be a more flexible search interface, however PVs would need to be added to channel finder and also categorised as "interesting"? Checking configs is an interesting adaptive approach to getting a list, is "high, medium, low, uncategorised" still a relevant breakdown? Other approaches are to categorise things by record (or numeric) type - you would typically have blocks on ai records and very unlikely to want one on a seq or fanout record for example.

**Comment by DominicOram** [comment]
Yes, PVs would still need to be tagged in channelfinder. We could also tag them with type, channel finder may already do this for us for free.

**Comment by KathrynBaker** [comment]
Tagging in channel finder would be a reasonable answer.

If thinking about just the data type then I have to ask, what about the Analog Input that is the raw value from a device which has to be converted to useful values? Thinking magnet PSUs here, the PSU could be running in Amps, and the user is looking in Tesla, and there may be an associated setpoint for that output. I’d typically aim to use a db structure that has:

·         A raw value from the device (in Amps), OUTPUT:RAW

·         A record that undertakes the conversion (cvt or calc), populating to Analog Inputs for OUTPUT:FIELD:TESLA, and (for completion) a record that reflects the other mode of working, OUTPUT:CURR

·         OUTPUT would simply echo OUTPUT:FIELD:TESLA

·         The value to set would then be OUTPUT:SP which has to go through all the reverse values to provide the value to send in Amps

If the device can run in Tesla or Amps then there has to be an ability to consider the unit that is sent to the device. You can guarantee that some scientists would want to work in Tesla, some in Amps, so the unit to display may need to be variable. These complexities probably create other interim PVs, which may or may not be interesting.

OUTPUT would be of high interest
OUTPUT:FIELD:TESLA and OUTPUT:CURR would be of medium interest (might want to set up as a block, but that will depend on the scientist)
The rest are a mix of low interest and we don’t really want a scientist to consider it ever (the cvt or calc)

So the purpose of a PV has more impact on whether it is interesting or not than the data type. However, there are a number of types (seq and fan were mentioned previously) which are very unlikely to be interesting and we could always default those to uncategorised – and probably not display them in the UI).
