### ISSUE TITLE
GUI: Fix error on edit configuration when selecting configuration

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4656]
![config_bug](https://user-images.githubusercontent.com/43140680/63172756-52b6f600-c036-11e9-9212-d98d19a2b7ef.PNG)

On SURF if you click `configuration -> configurations ->edit` and then rapidly double click a configuration to edit, this error message can appear. It is not every time, but if the action is performed quickly then it is more frequent. This suggests a race condition is present.

### Acceptance Criteria

- [ ] Rapidly selecting a configuration from the configurations edit window no longer produces this error message

**Comment by GRyall** [comment]
Couldn't reproduce this. Given time that has passed, seems likely this has gone away. Can reopen if noticed again.
