### ISSUE TITLE
IOC generator: issues

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4659]
As a developer I would like the IOC generator to work

Ran the generator with @JamesKingWork on a completely clean install:
- It failed to add the support module (because it didn't init the submodule?) and we had to manually delete it, recreate the structure and re-add it correctly
- It repeatedly warned that it was not pushing to git, but in reality was pushing to git.

**Comment by DominicOram** [comment]
As part of this the IOC generator should be updated to match the new repo structure in https://github.com/ISISComputingGroup/IBEX/issues/6555

**Comment by rerpha** [comment]
> As part of this the IOC generator should be updated to match the new repo structure in #6555

done in https://github.com/ISISComputingGroup/IBEX/issues/6689 to avoid a huge PR that solves several issues.

**Comment by rerpha** [comment]
Right, so it's a bit difficult to create the repository on github locally without messing about with API tokens and so on, so I suggest we prompt the user to go and do so using a link given.

**Comment by JamesKingWork** [comment]
That would be fine, but if possible it would be nice to have it automated, see https://github.com/ISISComputingGroup/ScriptGeneratorReleases/blob/master/create_release.py for an example of using API tokens

**Comment by rerpha** [comment]
Think it;s unlikely I can get this done and ready for review (and someone review it) by the end of the day, so going to unassign myself and leave for the next tech debt week.

**Comment by rerpha** [comment]
I have made the device generator not use git by default: https://github.com/ISISComputingGroup/IBEX_device_generator/pull/14 

whoever does this ticket will need to revert this when the git operations are fixed.

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/IBEX_device_generator/pull/22
