### ISSUE TITLE
RIKEN: power supply interlocks

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4661]
Problems spotted with RIKEN power supplies on deployment:
- The comms now appear to no longer be stable (as if the psus/serial line can no longer keep up with the command rate?)
- The interlocks (neither individual nor overall) are not reading correctly.

**Comment by FreddieAkeroyd** [comment]
It is indicating "parity" and "framing" errors, is the baud rate correct on both ends? Are there any cable issues?

**Comment by Tom-Willemsen** [comment]
It was working pre-deploy so I don't think there are cable issues.

I don't believe the parity has been changed, might try going back to synchronous IO to see if it's that

**Comment by FreddieAkeroyd** [comment]
VRAW and POL are giving mismatches, but were before upgrade. The  _READILKS mismatch does indeed seem new, but interestingly the characters it seems to say are mismatched (rrrrr etc) are similar to the ones RQ*:STATUS usually complains about such as in the log on 2019-08-01 Has the order of reading changed at all in the DB?

**Comment by Tom-Willemsen** [comment]
I think I've got it back to being approximately as reliable as before by adding 10ms waits after each command. Not sure why these are now needed. It also looks like the "spares" don't always report off, so I have modified the protocol to cope with this, see https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/12

**Comment by DominicOram** [comment]
We should cover this behaviour in the emulator, at least the fact that the spares may not always be off. The timing behaviour would be good to emulate too but I understand it's harder. I'm happy to merge this and put the emulator work into a separate ticket if this is urgent but that ticket should have a high priority.

**Comment by Tom-Willemsen** [comment]
No longer urgent for this to be merged as it is already patched onto rikenfe - put it back into rework as normal and I'll take a look when I get the opportunity.

**Comment by Tom-Willemsen** [comment]
- I've emulated the fact that the spares might be both on and off now
- I had a go at the timing, using the decorator that was created for the jasco, but as you suggest this is more difficult (especially as this IOC uses multiple asyn ports concurrently). I've documented the issue on the wiki.
