### ISSUE TITLE
LARMOR: bench encoder drift

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4662]
Message forwarded from Rob on LARMOR:

> Tony and I spent this morning measuring the motion of the Larmor bench.
It seems there is an offset in the rotation that scales linearly with distance.
This suggests that the distance to the encoder may well be wrong.
> The loss of steps seems to be reasonably small at the moment, with a patch of poor encoder performance between 60 and 70 degrees that results in additional mid positioning of ~0.04deg
> What is the  best way to adjust the encoder scaling?

Sounds like it is possibly an MRES/ERES that needs adjusting as the drift is linear with distance

**Comment by rerpha** [comment]
Closing, this is now driven via a Beckhoff, so not our problem to sort out if it drifts
