### ISSUE TITLE
LINMOT: Create emulator and unit test

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4665]
As a developer I would like to be able to test the LinMot motor controller locally against an emulator and have a suite of unit tests.

### Acceptance Criteria 

- [x] The LinMot has an emulator
- [x] Unit tests exist for the LinMot

**Comment by belindaharrison** [comment]
- ioc: https://github.com/ISISComputingGroup/EPICS-ioc/pull/416

**Comment by kjwoodsISIS** [comment]
@aaron-long - now that Belinda is no longer here, what is the plan for this ticket?

**Comment by aaron-long** [comment]
@kjwoodsISIS Sorry for the long delay in replying to this. I only just noticed your comment.

I have updated the code so that is in a good basic use state. There is a small amount of code used for error states (i.e., `ErrorStateCode`) but I will leave it in so that this has the ability to be extended in the future.

**Comment by aaron-long** [comment]
The lewis utility method `get_submodules` was silently failing in import failure causing some debugging issues. I made a fix and submitted this to lewis core: [#278](https://github.com/ess-dmsc/lewis/pull/278).

**Comment by aaron-long** [comment]
@davidkeymer No, it relates to lewis in general. I tagged it here as I completed that work while working on this ticket.
