### ISSUE TITLE
Beckhoff: Include IOC name in PV

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4669]
As a user I may want to run two beckhoff IOCs on my instrument. Currently the prefix provided to tcIOC will not include the IOC name and so this is not possible. This is due to the PV name length being violated if it is included.

**Comment by rerpha** [comment]
As a note for planning, mirroring what Freddie said on the other ticket: the longer we leave this the more blocks etc may be put on tcioc-generated PVs which will lead to issues further down the line if a second Beckhoff is used.

**Comment by FreddieAkeroyd** [comment]
Are we exposing more PV's than we need to? Do we require a mapping file to say what to expose and that could also map to a shorter name? I guess this couldn't be done as part of the OPC tag?

**Comment by rerpha** [comment]
Yes, we could probably not expose `ASTAXES_<X>:STCONFIG-*` as I don't think any of them are useful. We could do that, but as we call `tcLoadRecords()` we'd have to modify it to use the mapping file. 

As far as OPC tags go I'm not sure if you can exclude things from a nested structure by adding an OPC ignore underneath a top-level tag?

**Comment by FreddieAkeroyd** [comment]
Possible change ioc name to `TC_01` from `TWINCAT_01` ?

**Comment by FreddieAkeroyd** [comment]
char limit on PV is 60

**Comment by DominicOram** [comment]
> Are we exposing more PV's than we need to? Do we require a mapping file to say what to expose and that could also map to a shorter name? I guess this couldn't be done as part of the OPC tag?

There is a provision in OPC tags for a user friendly name. Whether this is passed through to the tpy and subsequently used by tcIOC correctly I don't know, you will need to test.

> Yes, we could probably not expose `ASTAXES_<X>:STCONFIG-*` as I don't think any of them are useful. We could do that, but as we call `tcLoadRecords()` we'd have to modify it to use the mapping file.
> 
> As far as OPC tags go I'm not sure if you can exclude things from a nested structure by adding an OPC ignore underneath a top-level tag?

OPC tags will let you hide a nested structure, we already do it with some of the Beckhoff internals.

**Comment by rerpha** [comment]
Cheers Dom, will have a look at the user friendly name stuff. Think we could use OPC_PROP_DESC for that but yeh would have to see what tcioc does with it. or maybe that gets used for the DESC of a field already? 


with my pv prefix of `TE:NDLT1542` using `TC` as the IOC name as a prefix it doesn't stop anything from working, there are more records that aren't loaded but they're all STERROR or STCONFIG fields which we aren't (currently) using and don't care about, it's things like gear ratios, distance to home, lag monitoring etc. 

Anything from STSTATUS or STCONTROL is maximum  53 chars long so we can probably get away with that for now. assuming we have a 256 axis beckhoff (add 2 extra chars, which means we'd use 55 on my setup) that gives another 5 chars for a pv prefix.

Is there a limit for the PVPREFIX? if not, what's the longest potential pv prefix, i guess its going to be a setup machine? not sure if those will ever have a beckhoff installed

**Comment by rerpha** [comment]
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/665
todo: BeckhoffTestRunner

**Comment by rerpha** [comment]
note that #6916 will likely not be affected as the extra fields are likely to be outside of the axis struct

**Comment by rerpha** [comment]
have created https://github.com/ISISComputingGroup/IBEX/issues/6969 to look into user friendly OPC tags as I didn't get time to do this before the release

**Comment by JackEAllen** [comment]
This issue has now been merged into master
