### ISSUE TITLE
NIMROD: jaws setpoints drifting

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4670]
As a user on NIMROD I don't want the setpoints of my motors to drift over time.

I think the following is happening:
- The readbacks are very noisy as they are just voltage readbacks
- The motor record is detecting that the motor is "moving"
- When the "move" is finished the motor record is updating the setpoint to be the current position
- Restart at step 1

This is causing the *setpoint* of the motor to drift as a kind of "random walk" - but notice the drift of around 3mm at 8pm last night:

![image](https://user-images.githubusercontent.com/24375813/63579516-c1daa000-c58a-11e9-8491-e863697d2f4c.png)

I tried setting the readback resolution of the motor to something larger than the noise on the encoder, but the motor record still seemed to detect the move and update the setpoint regardless.

**Comment by FreddieAkeroyd** [comment]
Did setting a larger EDEL fix this?

**Comment by Tom-Willemsen** [comment]
I think setting a larger EDEL has made it better but I think there could still be a drift if there is occasional noise on the encoder > EDEL. Will have a look next week to see if there was any drift over the weekend. It is currently set to 0.25mm which is at the upper end of what the scientists consider acceptable

**Comment by FreddieAkeroyd** [comment]
I don't believe EDEL affects the accuracy of a move, what is concerning the scientists? It may cause the galil to think the motor has stalled if it was large and so the encoder stall time may need to be increased. We could have two EDEL values, EDEL "when in motion" and EDEL "when stopped" - the former being for stall detection and the latter to detect a move not initiated by the galil.

**Comment by FreddieAkeroyd** [comment]
Fixed in #6975 with smoothing in galil
