### ISSUE TITLE
EMMA: raw frames not going up when DAE in "internal test clock" mode

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4671]
As a scientist on EMMA I want to do a run. I have put the DAE into internal test clock mode but the raw frames are not going up. Diagnose.

Raw frames go up correctly if I put the DAE into full-on simulation mode

@FreddieAkeroyd do you have any ideas about what may cause this?

**Comment by FreddieAkeroyd** [comment]
I stopped ibex and ran up Kelvin's test program
```
stop ibex
my document -> utilities -> ECC
click "connect to dae2 then "autofind"
you can then select a timing source and initiate a run 
```
This didn't start collecting frames, I tried re-running NI resman on the external computer, no change either. Suggest contacting electronics group, may need a DAE power cycle.

**Comment by Tom-Willemsen** [comment]
Issue resolved by electronics/detector group.
