### ISSUE TITLE
NIMROD: jaws manager change requests

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4672]
As a scientist on NIMROD I would like the following changes in my jaws manager screen:
- [x] I would like a readback for "size at sample" - this is just equal to the readback of jaws 6.
- [ ] I would like a readback for "size at moderator" - I want this to be back-calculated by extrapolation between jaws 1 and jaws 6. (I did check with the scientists and they were OK with "throwing away" the information from jaws 2-5 for the purpose of this calculation). The scientists have said that this is a nice-to-have and not required for cycle.
- [x] I do not want to be able to set beam centre. This is not useful and potentially confusing on NIMROD.
- [x] When setting the jaws via the collimation logic, I want the existing jaw centres to be preserved. The collimation logic should only compute a new jaw gap, not the individual jaw positions, and then apply that new gap to the underlying jaw sets without updating the centre.
  * The reason for this is that some of the jaw sets is mounted off-centre with respect to the beam, so they have their own special centre value which should not be interfered with.

**Comment by Tom-Willemsen** [comment]
Tested point (4) on my machine, and the jaws logic does actually preserve the centre as long as you only set moderator/sample size (which is what the NIMROD scientists want). I thought the jaws logic might calculate individual jaw blade positions but this is not the case.

I'll write a system test for this case as part of this ticket.

**Comment by kjwoodsISIS** [comment]
Should we provide them with some guidance on how to use the Jaws Manager  - specifically on how to use to achieve what they want and, conversely, how **not** to use it.

**Comment by Tom-Willemsen** [comment]
I've added a test for point 4 and fixed points 1 & 3 in the PRs below:
- https://github.com/ISISComputingGroup/ibex_gui/pull/949
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/225

I think for point 2 it may be best to wait and see if this is still a requirement after it's been used for a little while on the beamline - the scientists have made clear this one is not a "requirement" more of a "nice to have".

**Comment by DominicOram** [comment]
Looks good, I put a note in the tests and a couple of general comments:
* Can you update https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Nimrod-Jaws-Manager with the weirdness of having different centres. Putting the numbers on there and potentially a diagram would be good too.
* Can you spin 2) into a new ticket, even if it's not a huge requirement we should capture it

**Comment by Tom-Willemsen** [comment]
- Added to wiki at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Nimrod-Jaws-Manager#jaw-centres
- Created https://github.com/ISISComputingGroup/IBEX/issues/4675
