### ISSUE TITLE
Eurotherm: allow individual temperature sensor to be added to synoptic

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4673]
As an instrument scientist on NIMROD I would like to be able to add an individual temperature sensor to my synoptic.

This ticket essentially amounts to adding the existing linking container (which is already used by the eurotherm ioc) to the `opi_info.xml` file.

**Comment by Scott-James-Hurley** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7338
