### ISSUE TITLE
control-svcs webserver unavailable

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4674]
As a developer I would like the configchecker script to work.

NDW1757 is currently unable to access http://control-svcs.isis.cclrc.ac.uk/ . Access to control-svcs is needed to download the latest configs from git, to check them.

**Comment by Tom-Willemsen** [comment]
I think the webpage was probably cached on my machine and really wasn't there.

I think I have resolved this by:
- Logging onto the server and checking the status of the webserver using `sudo systemctl status httpd`, which gave me the following:
```
httpd.service start operation timed out. Terminating.
 ...
httpd.service stop-final-sigterm timed out. Killing.
httpd.service: main process exited, code=killed, status=9/KILL
Failed to start The Apache HTTP Server.
Unit httpd.service entered failed state.
httpd.service failed.
Unit httpd.service cannot be reloaded because it is inactive.
```
- I then ran `sudo systemctl start httpd` and `sudo systemctl enable httpd` to make the service start/restart on boot.
- I then checked using `sudo systemctl status httpd` again that the service had started properly
- The webpage now appears to load correctly and the configchecker is running again.

**Comment by DominicOram** [comment]
Thanks @Tom-Willemsen. Can you add a bit to the developers wiki about this?

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/control-svcs#webserver-is-down

**Comment by DominicOram** [comment]
Great, thanks Tom
