### ISSUE TITLE
TPG36X - Support TPG361 single gauge pump

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4680]
As an instrument scientist I would like to use the TPG361 single gauge pump. 

The TPG36X driver was made to support the 361/361 models, but in the protocol the `pres` (get pressure) function calls:

```
# Get pressures (and errors) from both guages
pres {
    out "PRX\r";
    InTerminator = CR LF;
    in ACK;
    
    out ENQ;
    InTerminator = CR;
    in "%(\$1\$2)d,%f,%(\$1\$3)d,%(\$1\$4)f";
}
```

The single gauge 361 model does not support a second pressure return value. The drivers records go into alarm as this results in a protocol mismatch as no second value is returned.

NB: This bug was found on SURF. I made a temporary fix by modifying the protocol to match against a single return value.

### Acceptance Criteria  
- [ ] The TPG361 is supported

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/53

**Comment by Tom-Willemsen** [comment]
Please can you add notes to [the wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TPG36x) to:
- explain the differences between 361 and 362 models in terms of functionality
- describe the symptoms seen if the choice is wrong and what the remedy is (presumably, setting the new macro appropriately).

**Comment by JamesKingWork** [comment]
See notes [TPG36x](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TPG36x)
