### ISSUE TITLE
POLARIS: Offline Experiment starting Mon 2nd Sept

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4684]
As an instrument scientist on POLARIS I would like to make sure that everything is working ready for an offline experiment to start this Monday (2nd September). I've also asked Electronics and Detector groups to check that all things are up and running for this.

As an IBEX developer, I would like to ensure that all deployment is done an tested before this.

**Comment by Tom-Willemsen** [comment]
Polaris was already deployed to and we did the usual post release tests at that time, see https://github.com/ISISComputingGroup/IBEX/issues/4423 . There is nothing to do for this ticket at this time. A separate ticket can be created if any issues are found.
