### ISSUE TITLE
Motionsetpoints: copy units from underlying motor

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4689]
As a user of motion set points, I would like the units of the motion set points axis to be correct. Currently it is hard-coded to `mm`, instead it should copy the units of the underlying motor axis.

This can be done by using the `unit_setter` template in the `utilities` submodule.

**Comment by DominicOram** [comment]
Could do https://github.com/ISISComputingGroup/IBEX/issues/2965 in conjunction

**Comment by JamesKingWork** [comment]
Fixed in https://github.com/ISISComputingGroup/IBEX/issues/4573
