### ISSUE TITLE
SUPPORT: Firewall wall incorrect on instruments, web dashboard not displaying

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4691]
Web dashboard is not displaying for some instuments fix this.

It appears that the block server can run on either `apps\epics\python` or `apps\python`. This is needed for the config to get to jsonborne. There is no firewall rule for the epics python create this on all instruments.

**Comment by John-Holt-Tessella** [comment]
Script run all on instruments except muonfe, rikenfe and crisp (not sure why this didn't work asking Chris).

**Comment by John-Holt-Tessella** [comment]
Ticket 4692 to sort out version and firewall long term for genie_python

**Comment by John-Holt-Tessella** [comment]
cmd /c "netsh advfirewall firewall delete rule name=pythonw_epics & netsh advfirewall firewall delete rule name=pythonw_genie & netsh advfirewall firewall delete rule name=pythonw & netsh advfirewall firewall add rule name=pythonw_genie dir=in action=allow program=C:\Instrument\Apps\Python\pythonw.exe enable=yes & netsh advfirewall firewall add rule name=pythonw_epics dir=in action=allow program=C:\Instrument\Apps\EPICS\Python\pythonw.exe enable=yes"

**Comment by FreddieAkeroyd** [comment]
This was an accidental oversight now that python is installed into the jenkins workspace. An immediate fix on an instrument would be to remove the additional python directory check from config_env_base and then restart the blockserver.

To correct this for future releases an   -XD Python    would need adding to the robocopy command in jenkins_build.bat

**Comment by John-Holt-Tessella** [comment]
Moved @FreddieAkeroyd comment to decide on python versiob ticket #4692. This may be an opportunity to upgrade python to version 3 for internal servers.

**Comment by Tom-Willemsen** [comment]
All relevant instruments are displaying correctly in the web dashboard. I looked in the logs and couldn't see any bad side effects.
