### ISSUE TITLE
Autocomplete block names

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4698]
As a scientist on NIMROD I would like to be able to tab-complete block names in the python console in the GUI when I'm doing a cget/cset

**Comment by DominicOram** [comment]
Is this fixed by https://github.com/ISISComputingGroup/IBEX/issues/5401?

**Comment by John-Holt-Tessella** [comment]
I think broadly yes. They would have to type `g.cset(b.` not quite the same as `g.cset(ab<tab>` but good enough I think.

**Comment by DominicOram** [comment]
Ok, i'll confirm with the IS that I can close this

**Comment by DominicOram** [comment]
Scientists are happy to close this
