### ISSUE TITLE
NIMROD: Change Edwards TIC Units

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4701]
As a NIMROD scientist I want my edwards Turbo Instrument Controller to read back in mbar like the rest of my gas panel. This came out of testing on the real device of ticket #4011. 

# Acceptance criteria
- [ ] Gauge pressure units are in mbar (=Pa/100)
- [ ] Units are no longer automatically copied from the gauge readback
- [ ] Tests are updated to reflect these changes

**Comment by Alistair-McGann-Tessella** [comment]
PRs:
[Support module](https://github.com/ISISComputingGroup/EPICS-EdwardsTIC/pull/2)
[IOC test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/229)
[Device Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/51)

**Comment by Tom-Willemsen** [comment]
Patched onto NIMROD
