### ISSUE TITLE
Reporting Disconnected Blocks & PVs

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4703]
As a scientist, I want IBEX to report disconnected blocks and PVs, so that I know when there is missing or uncertain data in my data files.

#### Acceptance Criteria
On encountering an INVALID alarm, IBEX will behave as follows:
1.  **IBEX GUI** 
    1. In the dashboard, blocks will display the **text "N/A"** and be surrounded by a purple border.
    1. In OPIs, readback fields (which display PVs, not blocks) will display the last-known-good-value and be surrounded by a purple border. 
    1. On hovering the mouse over a readback field, IBEX will display a pop-up box showing the PV name, the last-known-good-value (and its time-stamp) and the alarm status.
1.  **Log & Data Files** 
    1. **In the NeXus data file, blocks will be logged with their last-known-good-value and the alarm status.**  (Implementation is via #4936).
    1. In the IBEX archive, PVs will be logged with their last-known-good-value and the alarm status.
1.  **genie_python** 
    1. `cget` returns the value in a dictionary of a block or PV.
    1. `cget` **returns the alarm status of the block or PV**
    1. **`cshow` does the equivalent of cget**
    1. if there is an alarm on the block or PV, `cget` prints a warning message.
1.  **Run Control** 
    * If a block has run control applied to it and that block goes into alarm (including INVALID alarm) then
         1. if the last-known-good-value was within the run control limits, data collection will continue
         1. **if the last-known-good-value was outside the run control limits, data collection will not resume until the alarm is cleared.**
1.  **Web Dashboard** 
    1. In the web dashboard, blocks will display the following text:
       * <block_name>: <block_value> <block_units> (INVALID/LINK_ALARM), **where the text "INVALID/LINK_ALARM" is a hyperlink to a web-page explaining that the reported value is the last-known-good-value.**

#### Notes
1. We have documented our rationale for [Handling Invalid Values](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Handling-Invalid-Values).
1. This is potentially a large ticket.  It can be broken down into small tickets for implementation purposes.
1. Historically, this issue has been referred to as "NaNs" .
1. Authors of applications or scripts which process log & data files are responsible for checking the alarm status of a block or PV and taking appropriate action.

**Comment by DominicOram** [comment]
Notes from meeting on 11/09:
* The behaviour in 1i) should be optional by putting a value in preference file
* 2) will be a good opportunity for someone that doesn't know the ICP well to gain some knowledge, i.e. this work should not be done by @FreddieAkeroyd 
* 3) is mostly done but there is likely work to look at the behaviour of the block cache in relation to this
* The behaviour of runcontrol when in alarm should be optional to users, there should be a checkbox of when in alarm pause data or not
* The current behaviour of the web dashboard already covers 5). All that needs to be done is to update the docs linked in this page to reflect that current behaviour
* One solution to 2) is to get `STAT` and `SEVR` to be put into the ArchiveEngine as separate PVs. This may make the edits to the ICP easier but it would be better to use the information that is currently already in the ArchiveEngine
* The behaviour of the log plotter when PVs are in alarm is outside the scope of this ticket. See [here](https://github.com/ISISComputingGroup/IBEX/issues/4738)

**Comment by kjwoodsISIS** [comment]
This ticket is **_essential_** for the muon instruments (and other instruments would like it too).  How much work did we get done in the two days (see Tom's comment above)?

**Comment by John-Holt-Tessella** [comment]
This ticket has clearly not yet been started, so nothing has yet been done.

**Comment by Tom-Willemsen** [comment]
We now need to do all of this ticket, not just two days worth

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/genie_python/pull/191
- https://github.com/ISISComputingGroup/ibex_gui/pull/991
- https://github.com/ISISComputingGroup/JSON_bourne/pull/34
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/254
- https://github.com/ISISComputingGroup/EPICS-RunControl/pull/7

Note:
These PRs cover acceptance criteria 1, 3, 4 and 5. Acceptance criteria 2 will be covered in https://github.com/ISISComputingGroup/IBEX/issues/4936

**Comment by JamesKingWork** [comment]
Checklist for the acceptance criteria listed above

- [ ] IBEX gui
- [ ] Log & Data Files
- [ ] genie_python
- [ ] Run Control
- [ ] Web Dashboard
