### ISSUE TITLE
Remove/disable EDNEXT

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4704]
The EDNEXT ioc is not needed or useful - the device is controlled via the edwards turbo instrument controller which has it's own separate IOC.

As a developer I would like to remove/disable this unneeded ioc to:
- reduce our build time
- reduce confusion in list of iocs
- reduce ioc test framework run time

The IOC would still be in git if it was ever needed in future.

## Acceptance Criteria
1. Run the config checker script to ensure it isn't used
2. Remove the IOC if it isn't used

**Comment by DominicOram** [comment]
Confirmed NIMROD is using `EDITC_01`, no other instrument is using a `ED*` IOC

**Comment by DominicOram** [comment]
See attached PRs, also archived https://github.com/ISISComputingGroup/EPICS-EdwardsNextTurbo and updated it's description. I can't see any reference to the device in the wiki.
