### ISSUE TITLE
MERLIN: jaws drifting

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4706]
As a scientist on MERLIN I have noticed my jaws drifting over time, this is wrong.

From an initial inspection seems like a repeat of https://github.com/ISISComputingGroup/IBEX/issues/4670 , but IBEX has not been upgraded on MERLIN so something may have changed on the hardware?

Contacts: Jamie and Adroja

**Comment by Tom-Willemsen** [comment]
Initially I have increased `EDEL` on the jaw axes from 0.2 to 0.5mm. Apparently no physical work has been done on the jaws over shutdown, so unsure why this change is needed.

**Comment by Tom-Willemsen** [comment]
From electronics/motion:
- Nothing has been added/changed around the beamline that they believe would cause increased encoder noise
- They can think about a hardware solution ("decoupling capacitors") but aren't sure that this would work
- They have asked whether there is any averaging/signal processing that we can do in software to make the encoder less noisy

**Comment by davidkeymer** [comment]
Did the jaws drift in the end?  Or is that something for the reviewer to check?
