### ISSUE TITLE
Discussion: Alarm view potentially confusing when compared to blocks

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4707]
This was reported by Aidy on RIKENFE. Some blocks have their magenta borders but looking at the alarms tab doesn’t show them and a user might not understand whether or not there is a problem, and certainly not what the problem is.

**Comment by FreddieAkeroyd** [comment]
![pic](https://user-images.githubusercontent.com/1132753/64494994-f7220600-d28b-11e9-8d37-0e529c021ba5.png)

**Comment by FreddieAkeroyd** [comment]
I'm guessing the PV referred to by the block is not listed for inclusion in the alarm view, or maybe the IOC isn't? Maybe when the blockserver configures the alarm view it needs to automatically add block PVs to this view for the IOC? If the block is added to the IOC with its block name then it would be clear to the user which device was in alarm as it may not be clear from the block name.

**Comment by John-Holt-Tessella** [comment]
The alarm view shows:

> The Alarms View displays the alarm state of all devices attached to the instrument control PC. (https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Views#alarms)

Whereas the block alarm may be a disconnected block or something wrong below this. I think in this case the alarm indicates that an IOC is not talking in which case there should be an alarm. We should look into this. They are not the same, I am unsure whether we want them to be.

**Comment by FreddieAkeroyd** [comment]
The RB2_CURR blocks, which points at  IN:RIKENFE:RKNPS_01:RB2:CURR, is currently pointing at a running IOC but is in "link invalid" alarm status. Should this alarm show up in the alarms view or is it more selective on alarm types? It is not a "device disconnected" alarm, but the user only sees a purple border on the block and may expect it to be in the alarms view.

**Comment by John-Holt-Tessella** [comment]
Sorry I hadn't understood your point. There are two things here:

1. The alarm view does not currently show alarm statis of the blocks it shows alarms an IOC, usually one or two per IOC. We can add alarms status of blocks as a new feature. If we do we would need to associate each block with an IOC. This should be created as a separate ticket if we decide we want it? I don't think it is useful to have the information twice in the GUI, so I would vote no.
1. The alarm view should have an alarm from ther IOC which is generating value for blocks RQ1, Momentum, RB2. I am unsure whether it should be one for each item in the chain or one for the chain to show something is communicating. I think I would prefer one for each item on the chain. This may not be showing up because the alarm view is wrong or the ioc doesn't have an alarmed pv. We should check and fix this.

**Comment by FreddieAkeroyd** [comment]
We could create a separate subsystem in the alarm view for blocks, with the blockname at the top and the alias PV as the next level, or we could try and put the IOC as a sub level of the blocks. Though this may be duplicating the block alarm, I see the current situation is confusing. You see a block in alarms and on RIKENFE nothing is in the alarms view, but even if it was there it is not immediately clear what a block refers to.  It should be possible to know what alarm in the alarms view corresponds to that block, and there should be an alarm in the alarms view if a block is in alarm. When the blockserver is creating the alarm config, it could add all PVs from an IOC that are present as blocks but have not been otherwise added. Alarms can be added in trees, maybe we need to add more alarms but group in trees/subsystem better?

**Comment by Tom-Willemsen** [comment]
Meeting on 27th sept

**Comment by kjwoodsISIS** [comment]
Is this still impeded?

**Comment by John-Holt-Tessella** [comment]
Possibilities for alarm views, we said there were these options:

1. Remove Alarm View (no errors apart from borders)
1. Alarm view is just IOC Statuc (~1 pv per device)
    - Change view name from alarms to IOC Status
    - Add missing alarm statuses for IOCs
1. Add all interesting device PVs for an IOC into the current alarm tree under the correct IOC
1. Add all blocks into current alarm tree under the correct IOC (see picture)
1. Add blocks as second tree after IOC tree, grouped by groups (see picture)
1. Just show blocks as the only tree grouped by groups (as pictre but without IOC tree)

We agreed to mock up and ask instrument scientists unless having seen the pictures it is obvious. Tasks we need them to do with the mock up are:

1. Can you see any errors in the system
1. Can you decide what to do given an error in any line?
1. Is the amount of information too complicated

No Alarms view
![No Alarms view](https://user-images.githubusercontent.com/7570055/66216105-c384a100-e6bc-11e9-9d5d-ed2123922bc4.png)

Alarms with block in IOC
![Alarms with block in IOC](https://user-images.githubusercontent.com/7570055/66216106-c384a100-e6bc-11e9-8b0a-bfd54de126bf.png)

Alarm with block separate
![Alarms with blocks separate](https://user-images.githubusercontent.com/7570055/66216107-c41d3780-e6bc-11e9-823c-fe659ac196e1.png)


We should send this to scientists for reply is this ok? Comments please

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella we will prepare an email could you deliver it either to instrument scientists or next SAG

**Comment by davidkeymer** [comment]
Confirmed email sent to `ISIS Instrument Scientists + Others` by @John-Holt-Tessella asking for comments on the alarm system.
