### ISSUE TITLE
VESUVIO: Alarm server does not start on IBEX restart

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4709]
As an instrument scientist I see a mauve server disconnected message in the alarm server window and was concerned that things did not look as normal.

It looks like the alarm server is not starting on an IBEX restart (I restarted IBEX to see if this went away) - at least on this machine. checked and restarted manually by @Tom-Willemsen so not a fundamental problem - but probably new to this release.

**Comment by John-Holt-Tessella** [comment]
Is there anything in the block server log. When an IOC is started, which will happen on IOC start, the alarm server should be restarted. Is there anythingin the log? What time roughly was this?

**Comment by GRyall** [comment]
There have been no further reports and there has been significant development work since. Closing and we can reopen if anyone is aware this is still an issue or it is reported again.
