### ISSUE TITLE
MUONFE: Separator stable shouldn't have units

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4711]
As an instrument scientist on MUONFE I find the units "s" on the SEPARATOR_STABLE block to be confusing, this is a true or false situation with the stability displayed as 0 (unstable) or 1 (stable), as such I would like the block to display either something more intuitive, or at least not display the units.

**Acceptance Criteria**
1. There is no unit associated with the block SEPARATOR_STABLE

**Nice to Have**
1. The SEPARATOR_STABLE block displays Boolean values rather than 0 and 1

**Notes**
1. This relates to FIT-12018

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella did the original implementation of the separator IOC.  Check with Alistair when starting work on this ticket.

**Comment by DominicOram** [comment]
Nice to have can be solved using `ZNAM` and `ONAM`?
