### ISSUE TITLE
RIKENFE: can't talk to XFD2

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4712]
As a scientist on RIKENFE I want to talk to XFD2, but can't.

Notes:
- Other power supplies on the same PSU chain (and other chains) are replying correctly so I do not think it is a software/moxa issue. I believe the issue is likely to be on the power supply end
- This is not a danfysik, it is one of the old Tokin power supplies. This means it does not have the usual danfysik screen where you would set/check addresses and settings. For local control it only has a mechanical dial.
- Local control of the power supply is working correctly
- Power supplies group opened the PSU up for me but we couldn't see anything obviously wrong. We re-seated the comms cables just in case, but this didn't help. Inside the PSU there was no obvious way to set the address - I suspect there may be jumpers hidden somewhere to do this.
- Power supplies group suspect a bad control board *may potentially* be the cause. They are going to swap the control board with XFD1, which is not currently in use, to see if this is the case.
- A screenshot before the IBEX upgrade shows that XFD2 was also not communicating when we updated IBEX (both before and after the upgrade).
- This power supply is address 13 on chain 3 (com port 7)

**Comment by Tom-Willemsen** [comment]
After power supplies group changed the control board, comms were restored successfully.

**Comment by davidkeymer** [comment]
Confirmed that RIKENFE (via RKNPS_01 IOC) is reading values from XFD2 PSU.
