### ISSUE TITLE
NIMROD: run control not working correctly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4716]
On NIMROD the block "TS2BeamCurrent" is out of range, but the runstate is flashing between WAITING and RUNNING

**Comment by Tom-Willemsen** [comment]
I applied https://github.com/ISISComputingGroup/EPICS-RunControl/pull/6/files on NIMROD which fixed this issue. See https://github.com/ISISComputingGroup/IBEX/issues/4393

Consider: do we want to patch it everywhere? We decided not to last cycle on the basis that we were going to EPICS 7, which then didn't happen...

**Comment by John-Holt-Tessella** [comment]
Yes patch everywhere.

**Comment by Tom-Willemsen** [comment]
Duplicate of https://github.com/ISISComputingGroup/IBEX/issues/4717
