### ISSUE TITLE
SANDALS: Run control on TS1 beam current doesn't seem to work correctly

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4717]
As a scientists on SANDALS I have  run control enabled on the TS1 beam current and with the beam off,the run was waiting (as it should have been, ready to cound when beam returns).

Every now and then, the run would stop WAITING and enter the RUNNING state for a second or two before returning to WAITING.  The beam current does not appear to be anything other than zero during this time but when the instrument starts running I am concerned that my run time and statistics are going to be affected even though there is no real data!

**Comment by John-Holt-Tessella** [comment]
Repeat of #4393 fixed on all instruments. Have you told SANDALS it is fixed? 

This was meant to be fixed after going to Epics7 but we didn't get that far in the sprint. This is a fail in process of checking that hot fix does not need to be reapplied. Will be more careful in the future.

**Comment by FreddieAkeroyd** [comment]
Could probably be fixed by mapping .NAME$ -> .NAME in the central gateway

**Comment by DominicOram** [comment]
Covered by linked ticket @ChrisM-S did you let scientists know this was fixed?

**Comment by ChrisM-S** [comment]
Yes, the SANDALS scientists were keen to be able to stand down and not keep an beady eye on the dashboard in case it went into WAITING.
