### ISSUE TITLE
HRPD: connect sample environment

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4718]
HRPD is mostly rebuilt now. Connect sample environment.

TPG300 and Eurotherms struggling to talk, maybe also Linmots

**Comment by Tom-Willemsen** [comment]
Working:
- Linmots
- Rotating sample changer
- TPG 26X

Not working yet:
- Eurotherm
- TPG300

We tried running a long cable to both the eurotherm and the TPG300 to try to eliminate fixed wiring issues but this did not help. Have tried with/without null modems and various baud rates. Will ask electronics to check the physical units.

**Comment by ChrisM-S** [comment]
To summarize, the ones which didn't come back immediately.  All except (3) would have been fine if the original cables had not been removed lost during the building work!

1.  Linmots needed turning on for the jaws.
2.  Eurotherm needed plugging into the RH 9 pin port labelled "J" not the 25 pin one labelled "H" (at least on this unit).
3.  The wire on the back of the TPG300 RS232 interface card was broken/faulty and was replaced by SP.

**Comment by davidkeymer** [comment]
Confirmed via IBEX client that the devices mentioned are communicating successfully.

**Comment by John-Holt-Tessella** [comment]
@ChrisM-S please make sure that connection information like this is recorded on the wiki we will never find this ticket. I have added it to the eurotherm page on the developer wiki in:

    Wiki > The Backend System > Specific Device IOC > Temperature Controllers > Eurotherm

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eurotherm#connections

**Comment by kjwoodsISIS** [comment]
Was this really a 0 point ticket?

**Comment by Tom-Willemsen** [comment]
Probably about 1 pt.
