### ISSUE TITLE
OSIRIS: set up rotation stage

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4727]
As a scientist I am trying to control a mclennan but it doesn't work

**Comment by Tom-Willemsen** [comment]
OSIRIS has borrowed a different stage than their normal one (from maps)
- Created a rotation_maps component
- Copied over appropriate motor settings from MAPS' config
- Verified that homing works
- Verified that requesting a move of 180deg from the IOC corresponded to a physical rotation of 180 deg.

**Comment by davidkeymer** [comment]
Confirmed that OSIRIS is successfully using the newly created component and borrowed rotation stage.
