### ISSUE TITLE
LARMOR: no RBnumbers for current cycle

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4733]
Rob has reported that he can only see RB numbers from last cycle in IBEX

**Comment by FreddieAkeroyd** [comment]
Looks like it stopped working on 7th September with
```
ModuleNotFoundError: No module named 'peewee'
```

**Comment by FreddieAkeroyd** [comment]
It looks like a system package update on 7th September installed python 3.6 which then became the default python3 installation, the previous python 3.4 is still present. The new pythion 3.4 does not have peewee and the script used the "python3" command. I have changed the script to use "python3.4" as the python command

**Comment by FreddieAkeroyd** [comment]
It is in the cron job for epics

**Comment by FreddieAkeroyd** [comment]
Time info: took 30 minutes

**Comment by DominicOram** [comment]
Calling this done:
* Logs indicate this is now running happily for everyone except SURF (to be expected)
* LARMOR has up to date information
* Additional documentation looks good
