### ISSUE TITLE
Eurotherm: Make it harder to forget to toggle ramp tables

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4735]
As a user on POLARIS when using the Eurotherm ramp with PID/output values from a file I can sometimes forget to turn the lookup button on. My current workflow is `Change Table -> Turn lookup on -> Turn Ramp on`. I would like it to be harder to forget to do step 2. This could be:
* A message when I change the default file and have yet to turn lookup on
* The lookup is turned on automatically when I change the ramp table (probably too dangerous)

**Comment by boeuf-codes** [comment]
**Pull requests:**
- https://github.com/ISISComputingGroup/ibex_gui/pull/1450
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/550
- https://github.com/ISISComputingGroup/EPICS-ReadASCII/pull/15
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/709
- https://github.com/ISISComputingGroup/IBEX/pull/7256
