### ISSUE TITLE
Document the Block Cache

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4739]
As a developer I would like comprehensive documentation on the block cache, specifically what it does and why. Currently the only documentation is:
```
Program which caches block values and provides them via a CS:BLOCKSERVER:BLOCKVALUES. This is done to avoid genie python etc making too many calls to the various block PVs.
```
Which begs the question of why is bad if genie python makes lots of calls to block PVs?

**Comment by Tom-Willemsen** [comment]
The block cache was removed in https://github.com/ISISComputingGroup/IBEX/issues/4136 - this ticket is no longer relevant.
