### ISSUE TITLE
MERLIN: Homing on the rotation stage is _very_ slow

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4740]
As a scientist trying to home the sample rotation stage, whilst motion appears reasonable, homing appears to be extremely slow (.25 degrees per second) and I might have to home for nearly a full rotation this can be a real issue.  This can be worked around by moving the stage near to the home location (at about 2.5 degrees per second), then homing.  Is the homing making some assumption like jog speed or 1/10 of normal speed. Is there a setting that is simply not right?

**Comment by John-Holt-Tessella** [comment]
Email sent:

> Chris asked today about the homing speed of the McLenan and if anything had changed. I can confirm that when the McLenan is using a limit switch to home to (and a reverse jog to that limit switch) that home speed  is the same as the jog velocity. The jog velocity currently defaults to 1/10th of the motor velocity. This can be changed using the macro JVEL<axis> if you want it to go more quickly/slowly.
>
>I hope this is helpful, sorry that you got caught with a slow home.

**Comment by John-Holt-Tessella** [comment]
Instrument scientist will come and see us today to sort this out

**Comment by kjwoodsISIS** [comment]
Did the scientist come to see us on 17th Sept?  Is the issue now sorted out?

**Comment by John-Holt-Tessella** [comment]
No, no they didn't even after sending a chasing email. Shall I just close it or try one more time?

**Comment by John-Holt-Tessella** [comment]
Closing after email to instrument scientists 2/10/2019:

> I assume that the homing velocity was corrected for you or you have decided that it didn’t need I assume that the homing velocity was corrected for you or you have decided that it didn’t need doing. I have closed our ticket,doing. I have closed our ticket,

**Comment by John-Holt-Tessella** [comment]
Organised for 9am 3rd October (Tom)

**Comment by Tom-Willemsen** [comment]
Solved by manually sending creep speed to controller via hterm, long term solution is in https://github.com/ISISComputingGroup/IBEX/issues/4815
