### ISSUE TITLE
TOSCA: Reverting so SECI to use Sample Changer, neither this or Eurotherm communicating

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4741]
As a scientist on TOSCA I've reverted to SECI to make use of the TOSCA sample changer.  Currently things look OK (run numbers etc.) except that the two devices I need are not communicating.  I need the sample changer to be working and also the Eurotherm.

This may be just comms. setup somewhere if something has changed since IBEX was installed?

**Comment by ChrisM-S** [comment]
Problem was forgetting to stop the IBEX server before starting SECI.  Had a discussion with IS, difficulty testing IBEX version is to do with getting hardware configured and testable when it is not used, The two pieces, drive & "belt" hardware need connecting in close proximity ideally in location on cryostat flange - **not easy to do off the beamline**, not a very regularly used piece of kit either.

A suggestion we should act upon from IS is to see if we can leave or schedule the equipment to be in place during the short shutdown and book a specific time in calendars for this.  As this is essentially quite a simple piece of kit (control wise), it will probably not be too trick to test to a satisfactory finish as long a we are clear about jogging behaviours to copy/emulate from the SECI VI.

**Comment by davidkeymer** [comment]
See also tickets #4068 and #4008.

**Comment by John-Holt-Tessella** [comment]
Is there any time between the end of this experiment and the start of the next one?

**Comment by ThomasLohnert** [comment]
Fixed with https://github.com/ISISComputingGroup/IBEX/issues/6101.
