### ISSUE TITLE
LARMOR: Remote desktop connection voluntarily disconnected session

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4742]
the LARMOR RDP connection voluntarily disconnected before lunch due to a protocol error.  Note that just about the same time, the message above is a failed DNS resolution error for the R55 archive server.  Not sure of the specific linkage but maybe this failure to lookup also occurred in the RDP client hence the error.  This is here just in case the same thing happens again in the next few days somewhere else.  Might be due to DNS scavenging...

![image](https://user-images.githubusercontent.com/3035405/64959414-f6d7cb00-d888-11e9-9835-2b2c3909ee87.png)

**Comment by GRyall** [comment]
No further comments, so likely did not reoccur. Closing for now.
