### ISSUE TITLE
SURF: MOXA lost comms with galils early this morning [Tasks: Shutdown] 

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4748]
The SURF Galil MOXA lost communication this morning and was found by JB showing red light and a "-" on the front panel.  A power cycle fixed the issue.  After checking, it looks like this MOXA still has an old (less reliable) PSU.  Normally these fail completely when turned on, but maybe this one lost a component and temporarily hung the CPU.  Recommend taking to electronics to replace the PSU with a newer one on maintenance day (or at next most convenient) time.

### Plan

1. Unplug
1. Take to electonics to replace power supply with Gen 2
1. Replug it in

### Acceptance Criteria

1. Moxa works and is replaced.

**Comment by KathrynBaker** [comment]
MOXA has been in use for a couple of cycles since this, so this work is obsolete, so will close the issue
