### ISSUE TITLE
HRPD: beam current oscillating

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4756]
The dashboard (DAE) beam current on HRPD was oscillating - I have added a "Beam current in Dashboard oscillating" section to DAE troubleshooting https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting

**Comment by DominicOram** [comment]
Great documentation describing the problem but it might not be obvious enough what the solution is for either:
* DAE read timeouts (I'm guessing get in touch with electronics?)
* Chopper syncing to the wrong pulse (I'm guessing get in touch with choppers?)
