### ISSUE TITLE
SUPPORT: Eurotherm PV interest levels not appropriate for PID

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4758]
As an instrument scientist, I want to add PID and blocks for my Eurotherm so that I can script setting them, but they are hard to find as they aren't of high interest.

**Acceptance Criteria**
1. The PID PVs are of high interest

**Notes**
1. This has come out of a support call from OSIRIS

**Comment by DominicOram** [comment]
They were instead classified as medium, I've bumped them up to high but this might highlight a training issue on high/medium.

**Comment by KathrynBaker** [comment]
Possibly, or be reminiscent of the fact that we often do these things for the scientists instead of re-affirming the teaching for them to do so themselves (I did one of the 3 and made the IS do the other two whilst I was on the phone), and/or they don’t undertake this kind of task frequently enough to remember (not in this case, the IS just couldn’t find them because they weren’t in the high list). This is potentially related to #4655.
