### ISSUE TITLE
GUI: reinstate disabled tests once surefire is patched

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4759]
As a developer, I would like to reinstate some unit tests for the GUI which were removed from the maven build in https://github.com/ISISComputingGroup/IBEX/issues/4255

These test plugins are:
```
<module>../uk.ac.stfc.isis.ibex.opis.tests</module>
<module>../uk.ac.stfc.isis.ibex.synoptic.tests</module>
<module>../uk.ac.stfc.isis.ibex.devicescreens.tests</module>
<module>../uk.ac.stfc.isis.ibex.alarm.tests</module>
<module>../uk.ac.stfc.isis.ibex.ui.scripting.tests</module>
```

Notes:
- The tests do still run in eclipse - they have been temporarily removed from the maven build because the maven surefire plugin is currently unable to resolve certain classes correctly.
- To reenable the tests, the above lines need to be re-added to `base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml`

**Comment by John-Holt-Tessella** [comment]
<module>../uk.ac.stfc.isis.ibex.scriptgenerator.tests</module>

can not be added there is a problem with it which is not just surefire. Have added to ticket #4910

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/997
