### ISSUE TITLE
SUPPORT: IOC Not starting for any obvious reason

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4761]
Call from TOSCA, they had some blocks disconnected. The IOC serving the PVs wasn't running and had failed to start on the previous attempt with no obvious reason in the log file. Starting the IOC manually it was fine.

It is unlikely that we can resolve this, but it may be worth considering a way to monitor such situations. This may be indicative of a race condition (if we send a random ctrl-x to the procserv somehow), some fault in the IOC that meant it failed silently in the ioc log, or something else again. Being able to trace rates of such incidents we might be able to find a resolution.

The failed log and subsequent successful log are in a folder on the share

**Comment by ChrisM-S** [comment]
+1
For one machine when I was on support, think it might have been VESUVIO – I connected in but <cr> did nothing, IOC hadn’t started from start/stop IOC – I think if I remember rightly, the procserv had died.

The thing is, we could have a record of what we have started/tried to start and simply monitor that against the current set of running IOCs.  Might also be worth putting in a few attempts to restart (like with windows services where they try two or three times at varying periods but stop after a bit if the problem isn’t resolved).

**Comment by John-Holt-Tessella** [comment]
Was this the LKSHR218_03: If so I can see in the logs:
Blockserver Log
`[Thu Sep 19 11:40:26 2019] [1568889626.62] INFO: Starting IOC LKSH218_03` NB no `Re-applying auto-restart setting to` because auto-restart is not set in the config

The IOC log shows start at

```
[2019-09-19 11:40:27] @@@ Restarting child "LKSH218_03"
```

and a stop showed after start (it has the same timestamp as the start)

```
[2019-09-19 11:40:29] @@@ @@@ @@@ @@@ @@@
[2019-09-19 11:40:29] @@@ Received a sigChild for process 23584. Normal exit status = 0
[2019-09-19 11:40:29] @@@ Current time: 2019-09-19 11:40:29
[2019-09-19 11:40:29] @@@ Child process is shutting down, auto restart is disabled
[2019-09-19 11:40:29] @@@ ^R or ^X restarts the child, ^Q quits the server
```

**Comment by KathrynBaker** [comment]
It was indeed, so it may well be a race condition.

Regards,
Kathryn
