### ISSUE TITLE
Fermi chopper: detect & prevent phase oscillations

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4764]
As a scientist using the Fermi Chopper IOC, I would like it to automatically detect if the phase is oscillating and remedy it.

The phase on MERLIN, for example, will occasionally fail to lock on properly and will instead oscillate around the setpoint with a large amplitude, as in the graph below:

![image](https://user-images.githubusercontent.com/24375813/65411237-4156cb80-dde4-11e9-90e7-a4da69d88e9d.png)

Scientist suggested changing `set_ei` script on MERLIN on maintenance day:

> it would be good if we can change set_ei command/program. Say if after 10 attempts, if Fermi delay is not stable then automatically give new set_ei command with same Ei, but add 50Hz frequency (if it is at 600Hz already then go down to 550Hz) to what it was setting. After says 30 (or 50) second the program can stop this second set_ei command and send first set_ei command, which was given at the start of set_ei.

**Comment by Tom-Willemsen** [comment]
/remind me "Add phase oscillation prevention to merlin set_ei script" on 25th September at 09:30am

**Comment by Tom-Willemsen** [comment]
Now added to Merlin's `set_ei` script and symptoms/resolution added to wiki

**Comment by DominicOram** [comment]
Added a note on the wiki that  links back to this ticket and mentions `set_ei` fix.
