### ISSUE TITLE
IMAT: unable to start mcp camera

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4766]
NDXIMAT was unable to connect to the MCP camera, it turned out this was due to the gateway being passed a truncated IP address (just 130.246) so it was unable to bind to the correct address and forward packets. Killing gateway.exe is not enough, it needs the procserv startup running again as this determines the IP address to pass to gateway.exe   

The address is obtained by running get_isis_ip.bat - maybe the output of ipconfig was truncated somehow?

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd write a ticket to re-write the IP command

**Comment by davidkeymer** [comment]
Confirmed existence of new ticket #4996, so this ticket can be considered reviewed.
