### ISSUE TITLE
IOC: Eurotherm Temperature setpoint readback not in alarm

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4768]
As a user I expect the temperature readback from a eurotherm to show disconnected when the device is not there. There are many other readbacks which also do not show an alarm. 

![image](https://user-images.githubusercontent.com/39486445/65435217-0ff7f300-de18-11e9-89a7-e30339897d30.png)

**Comment by Tom-Willemsen** [comment]
Both SP:RBV and RBV
