### ISSUE TITLE
BUILD: Remove Genie Python from Build Server 1757 after conversion to python 3

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4771]
After converting pythons to genie_python 3 remove genie from build server 1757 because this python is not being updated.

**Comment by Tom-Willemsen** [comment]
Also from NDHSPARE53

**Comment by John-Holt-Tessella** [comment]
Python3 looks like it has been removed from these servers already. Closing the ticket.
