### ISSUE TITLE
DETMON: Sort out connection issues

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4772]
As a support person I want packets from the DETMON 'instrument' machine to be correctly routed through the network. While reviewing #4182 it was noted that a client can't connect to the DETMON IBEX server, despite correct information about it showing up on dataweb.

This ticket is to investigate the connection issues to the DETMON instrument machine, then either resolve them for a simple fix or write up a new ticket.

**Comment by JamesKingWork** [comment]
DETMON is now accessible from the client on the network
