### ISSUE TITLE
Squish: build server crashes in C runtime library

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4773]
As a developer I would like the squish tests to run correctly.

I updated squish on the build server to enable it to run the new java 11 GUI, but the new version of squish hangs with the following error when launching each test:

![image](https://user-images.githubusercontent.com/24375813/65594116-068e9800-df8a-11e9-99d1-22add7eb8291.png)

On pressing "ok" the test seems to continue and run correctly, but while the pop-up is open the process is hung and the tests can't proceed.

**Comment by Tom-Willemsen** [comment]
See https://kb.froglogic.com/pages/viewpage.action?pageId=131185

**Comment by Tom-Willemsen** [comment]
If after brief investigation we get stuck, contact squish support for help diagnosing the problem.

**Comment by Tom-Willemsen** [comment]
Have sent an email describing our problem to squish support - awaiting response

**Comment by Tom-Willemsen** [comment]
After some back-and-forth with Squish support (who were very responsive and helpful), we have narrowed this down to Python's `uuid` library loading an incorrect C runtime version. We use the `uuid` library to generate random names in a number of places.

Possible solutions:
- Rename `C:\Squish\python\msvcr90.dll` to `msvcr90_off.dll` on the build server
- Don't use the python `uuid` library - instead replace it with any other library that can give us randomised strings

Notes:
- Related python bug: https://bugs.python.org/issue17213

**Comment by Tom-Willemsen** [comment]
File renamed on build server and note added to wiki with error text and solution.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by DominicOram** [comment]
This seems like a bit of a hack and will continue to be a pain when every developer installs squish. Why not just stop using uuid and generate a random string ourselves? It's not like we need it to conform to UUID especially?

**Comment by Tom-Willemsen** [comment]
See https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/29
