### ISSUE TITLE
LOQ: issues starting run

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4778]
Several issues, may be correlated or not:
- `g.begin()` hangs if the DAE cannot begin a run
- The tables cannot be changed while tcb settings are all zero - even if the tcb settings would be being changed to non-zero values in part of the same `g.change_start() ... g.change_finish()` block
  * Possibly a change in behaviour from either the scans library or us? Need to check behaviour
- The blocknames PV appears to have been unavailable (we already have a ticket for this)

I think I have got them running by issuing tables and tcb settings manually, but need to investigate to find root causes

**Comment by Tom-Willemsen** [comment]
Organise a meeting with Adam and Steve to try and understand which parts of this issue are in the scans library, and which parts are in IBEX

**Comment by FreddieAkeroyd** [comment]
are the lines to change the tcb before or after the lines that change wiring tables? Is g.begin() hanging on a waitfor_runstate("SETUP",onexit=True) sort of thing?

**Comment by Tom-Willemsen** [comment]
1. I think the workflow I saw in logs was something like:
```
g.change_tcb( <all TCBs set to zero here> )

g.change_start()
g.change_tables(...)
g.change_tcb( <to the actual TCBs that need to be used> )
g.change_finish()
```

2. Yes, quite possibly. But this is not clear to the user from the scripting perspective.

**Comment by kjwoodsISIS** [comment]
How many points?
