### ISSUE TITLE
ZOOM: Chopper OPI should not focus onto the frequency box after phase change

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4785]
From instrument scientist:
> If the frequency box is selected, pressing any of the arrow key on the keyboard 
will change the frequency of the choppers without any warning. The problem is 
increased, as in IBEX for changing the phase of the choppers the number must be 
typed in the apropriate box and then "return" must be pressed, what hightlights 
the frequency box.
It would be ideal if after changing the phase of the choppers the frequency box 
was not auto-selected.

**Comment by JamesKingWork** [comment]
The issue this ticket was fixing has been fixed by #4786. Therefore we do not need to merge these changes.
