### ISSUE TITLE
ZOOM: Configure 3D magnet

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4808]
ZOOM required an IBEX configuration for the Scientific Instruments 2T 3D cryogenic magnet.  Instrument scientist had copied the component from LARMOR where it was last used, but this needed the correct settings for the 3 IOCs (Lakeshore 336, TTi EXP355P, Magnet PSUs).

Found information on Wiki [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Cryogenics#cryomagnets-superconducting-magnets) and then followed instructions on, and deduced details from conversation in original ticket for device: #1398.  (**NB** Suggest this information be compiled into device's own wiki page).

Equipment had been connected, although an Ethernet connection was required for the switch in the rack for the device's own MOXA and the Lakeshore (at least) - the TTi PSU was connected to this MOXA.  The additional COM ports were added to the instrument control machine via NPORT manager.  Latest version of VI (as this is an LVDCOM driver) was from acquired from SourceSafe and configuration file obtained from LARMOR.  VI communicated immediately when run.

Lakeshore 336 hostname noted from front panel and entered as macro for IOC, appropriate COM port entered for TTi PSU.  Both were checked using OPIs in Device Screens perspective.

System left in operational state ready to be used on next User change.

**Comment by Tom-Willemsen** [comment]
Since this is fresh on your mind, please add a wiki page describing the setup.

**Comment by davidkeymer** [comment]
Further work was required on the system on the following two days:
1. Configure needle valve control:  The original VI (currently in SourceSafe) uses a Galil axis to control the valve, as it was originally written to be used on POLREF.  However, LARMOR uses a TTi EXP355P PSU to control the valve motor directly, and therefore so now does ZOOM.  Unbeknownst to support staff and instrument scientist, an edited VI exists on LARMOR for this purpose.  Once discovered, this was duly copied to ZOOM and the PSU COM port configured (modified VI will be captured in SourceSafe).  PSU's individual VI was run first to check connection, but without success because eventually realised the IOC in the previously configured IBEX component was still running and locking the port.  All well once stopped and removed from component.
1. Connect and configure magnet rotation stage:  There are no spare motor connections in the ZOOM sample area, so one axis from the slit set (not needed to be moved during experiment) was disconnected and its cables used for the stage.  The current settings for the slit axis were first extracted from the autosave logs and a batch file created to reinstate them after the experiment had finished (file put in ZOOM area in Scripts network share).  In the same way, the settings for the rotation stage were extracted from the logs on LARMOR where it was last used (file put in IBEX component area on ZOOM).
1. Use Lakeshore 336 to output specific current.
1. Modify user script to work around race condition in VI.
