### ISSUE TITLE
View as Project [Tasks: 02-10-19]

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4809]
As a member of the support team, I would like to be able to create a list of pending tasks in a less clumsy and more robust fashion than the (possibly shared) editing a markdown table.

**Acceptance Criteria**
1) The project view can be shown on the TV screen (not practical before because of the poor TV browser implementation) 
2) Members of the team feel that the approach gives benefits in terms of organization and visibility of pending tasks and their tickets.

**notes;**
1) This should use the ability of the notes facility in a project to include a "magic" link to an issue URL augmented by text in a project note (with sufficient additional info in the note to fulfil the requirements of the existing table).
2) Issues from private and public repos. can be linked and viewed without compromising privacy or ease of viewing (permissions are honoured in what is visible at the end).
3) Notes should be stylized slightly to ensure important information from the table headers is included in an intuitive way (date, instrument, area, description, ticket and champion).

**Comment by davidkeymer** [comment]
Pending Tasks project [here](https://github.com/ISISComputingGroup/IBEX/projects/8)

**Comment by davidkeymer** [comment]
Project board viewed, but no tickets or notes added as it's a "live" prototype system.

Suggest trialling the board as a group once the machine in ticket #4807 is configured and connected to the office display.  Could be done as a short demonstration at a Standing.

**Comment by DominicOram** [comment]
What's happening with this? Are you still reviewing it @ChrisM-S?

**Comment by davidkeymer** [comment]
As comment above, the new board needs demonstrating to the group as part of the ticket's review.

**Comment by Kevin-Woods-Tessella** [comment]
It could be reviewed after the next daily stand-up - no time like the present!

**Comment by ChrisM-S** [comment]
absolutely, it was only waiting for #4807 which I see is now completed.

/remind me before stand-up on Monday at 9:55

**Comment by ChrisM-S** [comment]
Documentation in Wiki now.

**Comment by davidkeymer** [comment]
Wiki page viewed [here](https://github.com/ISISComputingGroup/IBEX/wiki/Pending-Tasks), original "Pending Tasks" page.

Will now trial new board as a group.
