### ISSUE TITLE
EMMA: Could not start Fermi Chopper from OPI

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4813]
Fermi chopper would not run to requested frequency despite being lowered into beam (via chopper lifter IOC/OPI) by instrument scientist.  On OPI, no errors reported, but status readback showed "not ready" and "not levitated" via LEDs.

Instrument scientist advised to check front panel of physical chopper controller (SKF MB350), whereupon it was discovered that an inhibit signal was present, possibly its default power-on state (Emergency stop button was _not_ depressed and latched).

`Reset` button pressed, OPI reported `Ready` and `Levitated`, `Start` button on OPI pressed and chopper starting spinning up to setpoint.

**Comment by Tom-Willemsen** [comment]
Could not find the symptoms/resolution of this on [the wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SKF_MB350_Chopper). Please add. Possibly also link to [fermi chopper lifter page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Fermi-Chopper-Lifter).

**Comment by davidkeymer** [comment]
Both wiki pages updated.
