### ISSUE TITLE
SURF: Slit 3 axis not reaching desired setpoint

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4817]
Instrument scientist and SE Group reported strange behaviour by an axis of the third slit set including: not reaching setpoint, not travelling full range, reversed direction, refusal to move.

This occurred after SECI/IBEX tests on the previous day which was a very similar scenario described in ticket #4635.  The solution detailed therein was also applied here (i.e. updated Galil LabVIEW driver) and all returned to normal.

**Comment by DominicOram** [comment]
How many instruments do not have the latest version of the Galil LabVIEW driver? Is it worth adding a note to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC to make sure the driver is up to date if we think we might be switching between SECI/IBEX?

**Comment by davidkeymer** [comment]
1. I'm not sure but could find out.
1. Yes

**Comment by DominicOram** [comment]
If we have that step in there then I'm happy enough, thanks.
