### ISSUE TITLE
SURF: NIMA Trough VI not communicating

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4818]
Instrument scientist reported no control over NIMA trough from its dedicated VI.

The VI appeared to be communicating with the control box with send and receive LEDs lit on the correct MOXA port.  A sub-VI also showed what seemed like valid status responses.  However, no setpoints were being actioned.

After trying two control boxes and checking the wiring to the trough itself, a direct connection to the MOXA (without an extension patch cable) was tried.  This corrected the problem, which was later found to be a damaged patch cable.  A replacement was supplied and the system left in a working state.

***NOTE*** Unbeknownst to instrument scientist and support staff (until now), the control box lights an LED labelled `V2` when a successful connection to the remote interface is established.

**Comment by John-Holt-Tessella** [comment]
Docs added to:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/NIMA-Trough

**Comment by kjwoodsISIS** [comment]
Again, I am struggling to understand why this is a "0 point" ticket - it needed investigation of the VI's behaviour, trying two control boxes, various cables and a documentation update.  That hardly sounds like 0 points.

**Comment by John-Holt-Tessella** [comment]
No you are right this is definitely not a 0, changed to 0.5. Two of us spent an hour on the instrument, then David finished off for 30 mins (1 for IBEX because we thought it was because it had been on IBEX and one for SECI) and we updated the docs for 30 minutes.
