### ISSUE TITLE
New checkstyle warnings after merge with Nicos ticket

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#4823]
After merging branch https://github.com/ISISComputingGroup/ibex_gui/pull/968 with the master branch, it has created some checkstyle warnings.
http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_pipeline/1625/checkstyleResult/new/

**Comment by DominicOram** [comment]
Closing this as the link is dead and this is covered by the background task of fixing checkstyle issues.
