### ISSUE TITLE
HIFI Cryomag: add PSU IOC CRYOSMS

### ISSUE THREAD

**Issue by ChrisColeExpControl** [ISISComputingGroup/IBEX#4826]
Add the beginnings of the IOC for the HIFI cryomag's Cryogenic Ltd SMS series PSU. Can get and set the outputmode of an emulator. Contains the basics of the read/write system which will be used for this IOC: the setpoints which a user can set do not actually send any commands to the device, instead they go to an asyn driver (which in the future will handle the large amount of logic needed by this IOC, but for now just directly writes), which then writes to a hidden setpoint PV. This hidden PV then writes through streamdevice. All reads are simply handled directly through streamdevice.

**Comment by ChrisColeExpControl** [comment]
List of PRs:
[tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/246)

[EPICS](https://github.com/ISISComputingGroup/EPICS/pull/186)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/434)
[Support](https://github.com/ISISComputingGroup/EPICS-Cryosms/pull/1)

**Comment by DominicOram** [comment]
Is there also an emulator PR for this?

**Comment by ChrisColeExpControl** [comment]
> 
> 
> Is there also an emulator PR for this?

Appologies, was running it with the emulator liam wrote [here](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/tree/Ticket651_hifeCryomag_PSU_Emulator/lewis_emulators/HFMAGPSU), once I've finished the bit I'm working on right now I'll get it cleaned up with the new IOC name and put a PR in.

**Comment by DominicOram** [comment]
Ok, I'll wait until then to review this.

**Comment by ChrisColeExpControl** [comment]
New list of PRs:
[tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/246)

[EPICS](https://github.com/ISISComputingGroup/EPICS/pull/188)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/434)
[Support](https://github.com/ISISComputingGroup/EPICS-Cryosms/pull/1)
[Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/56)

**Comment by DominicOram** [comment]
This all seems mixed up with #651. As such there's loads of different branches prefixed `Ticket651` or `Ticket4826`. If we merge this one does that complete #651? Can you try and rename/delete branches/tickets to get this into a more understandable state?

**Comment by ChrisColeExpControl** [comment]
Initially I was working on this as a single all-encompassing ticket, #651 but after brief discussion it was decided that it would be better to split it up into a series of smaller tickets, of which this is the first. Unfortunately it seems there is no way to rename branches without deleting all discussion on the PRs, do you still think I should do this?

**Comment by DominicOram** [comment]
Let's leave the ones associated with the PRs referenced in this ticket and I can merge them based on the rework. However, there are still a bunch of others out there, [3 on the test framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/branches/all?utf8=✓&query=Ticket651), [4 on the iocs](https://github.com/ISISComputingGroup/EPICS-ioc/branches/all?utf8=%E2%9C%93&query=Ticket651) etc. Some of these have PRs, which in some cases have been open for years, some of them have no PRs. Can we clean these up?

**Comment by DominicOram** [comment]
I appreciate that you didn't make most of these branches but I think you're in the best position to work out what's out there and what's useful to keep.
