### ISSUE TITLE
ISISDAE: Release @s in title for block values

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4828]
As a user `@s` in titles are useful. There is some code in a module but Freddie is unsure it works. @FreddieAkeroyd make sure the code is ok put it into the latest isisicp and add to ICPBinaries.

### Acceptance Criteria

1. `@` in titles works
1. Code is in isisicp
1. Tests are uncommented in `test_genie_python_dae.py`

**Comment by FreddieAkeroyd** [comment]
To TEST:
* you need to run CREATE_ICP_BINARIES in your directory to update executables
* If you have a block called    `TEST`   then including    `@TEST@`   in the title will substitute block value, update time may be ~10 seconds
