### ISSUE TITLE
IMAT: Gamry 1000 

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4834]
G called from IMAT. A user had turned up and wanted to use a Gamry 1000 Potentiostat. IMAT had previously had a user use some unknown model of Gamry for which a ISIS created device had been created to trigger it [#2642](https://github.com/ISISComputingGroup/IBEX/issues/2642). There was some initial confusion as the IOC was titled Gamry and they thought it would be supported.

G was unable to locate the ISIS created device, and instead we arranged for the user to remote desktop to a laptop (placed in the blockhouse) that would control the Gamry.

- Updated the WIKI for support assistance [LINK](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Gamry)

**Comment by DominicOram** [comment]
@aaron-long spoke to G and asked them to come back to us if they want some more robust support. @aaron-long can you please update the description on the GAMRY IOC to make it more obvious what it actually is?

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/435
