### ISSUE TITLE
IOC System tests: Investigate why tests sporadically fail. [Timebox 1d]

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4836]
As a developer in the team, I wants to be AGILE, not FRAGILE. Our IOC system tests seem to have temperamental tests that can fail. We should look at:

- Are there race conditions with IOC or server (if any) start-ups
- Do we have tests that are designed in a fragile way
- Is there any similarities between tests that consistently fail

**Comment by Tom-Willemsen** [comment]
system_tests_common_failures
