### ISSUE TITLE
MUONS: Zero-Field - IOC for Field Strength

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4838]
A magnetometer outputs three analogue voltages (one for each axis of the magnetic field - _Longitudinal_, _Transverse_ and _Vertical_) which are fed into an A-D converter on a NI-cDAQ.  These voltages should be converted to field strengths to be used in the calibration routine implemented in #4839.

***Acceptance criteria:***
1. An IOC to read raw voltages from the cDAQ and convert them to magnetic field strengths using configurable calibration values (offsets).
1. A PV for the _**raw**_ field strength (in units of mG(?)) for each of the three axes.
1. A PV for each of the three _**corrected**_ field strengths (in units of mG(?)).  Details of correction routine given on wiki page [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller)
1. A PV for the magnitude of the corrected field, based on the following equation:
`Magnitude = sqrt(corrected_X_field^2 + corrected_Y_field^2 + corrected_z_field^2)` (this value is used to determine whether or not the field is stable in the auto-feedback routine).
1. The PVs should enter alarm state if the magnetometer is overloaded.  (This state is read by the auto-feedback routine IOC and processing is temporarily disabled accordingly.)

***Notes:***
1. An NI-cDAQ has already been communicated with as part of the Muon Separator project described in #3072

**Comment by Alistair-McGann-Tessella** [comment]
Pull Requests:

[EPICS]()
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/443)
[Support](https://github.com/ISISComputingGroup/EPICS-zfmagfld/pull/1)
[IOC tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/264)
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/999)
[DBUnitChecker](https://github.com/ISISComputingGroup/EPICS-DbUnitChecker/pull/28)

Docs:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-Field-Magnetometer-IOC
