### ISSUE TITLE
MUONS: Zero-Field - Calibration Routine

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4839]
The current procedure is described [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller#zero-field-set-up-procedure), along with further notes throughout the page.

**Acceptance Criteria**
* A working script that the scientists can then adopt.

**Comment by Tom-Willemsen** [comment]
Python script.

**Comment by DominicOram** [comment]
Code at https://github.com/ISISNeutronMuon/InstrumentScripts/pull/47
