### ISSUE TITLE
MUONS: Zero-Field - Test and Commission System

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4840]
Placeholder for ticket - details in due course.

**Comment by Tom-Willemsen** [comment]
Steve has provided some initial data showing the performance of the existing system. I've added it to `<share>\data for tickets\Ticket4840_test_zero_field\EMU ZF Evaluation I.XLSX`

**Comment by Tom-Willemsen** [comment]
@davidkeymer and I performed some tests on EMU, and the EMU scientist is now happy that the system is working as expected.

I have documented the results of the test at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller#performance

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/4
