### ISSUE TITLE
Tests: Fix all tests

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4841]
Fix hard failures of IOC System tests, squich and system tests. Not inconsistently failing tests.

## Acceptance Criteria

1. Day was organised
1. Tests are all passing
1. Removed skip annotations from attocube and nimrod jaws manager tests (https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/250/files)
1. Simple IOC against a parameterized case that writes (or reads) to a PV a million times. The thought here is maybe there's some underlying PV set (or get) issue that fails at times. We might also want to test this on a system that has high CPU usage etc.

**Comment by Tom-Willemsen** [comment]
Tech debt standown day

**Comment by aaron-long** [comment]
Following a discussion with @Tom-Willemsen & @John-Holt-Tessella . It might be useful to try testing:

- Simple IOC against a `parameterized` case that writes (or reads) to a PV a million times. The thought here is maybe there's some underlying PV set (or get) issue that fails at times. We might also want to test this on a system that has high CPU usage etc.

**Comment by Tom-Willemsen** [comment]
Also fix and remove skip annotations from attocube and nimrod jaws manager tests

**Comment by aaron-long** [comment]
I've found that junit as a `factor` feature that allows for differing health contributions based on 10% of tests failing. [Link](https://jenkins.io/doc/pipeline/steps/junit/)

**Comment by DominicOram** [comment]
Date set at Wednesday the 18th Dec

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/270

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/30

**Comment by John-Holt-Tessella** [comment]
Sorry created ticket:
https://github.com/ISISComputingGroup/IBEX/issues/5050

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/5048
