### ISSUE TITLE
HRPD: Add ITC503 to instrument

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4842]
HRPD wanted to use an ITC503. This cryogenics tool is rarely used and there was no component configured for the instruments configuration. They will use the same COM port as the base sample changer (currently disconnected, COM14).

- Created ITC503 Component
- Disabled auto-restart and auto-start on the sample changer component (they were confident they could re-enable this once they had finished using the ITC)
- Created a synoptic device screen for the ITC503

**Comment by kjwoodsISIS** [comment]
How many points?
