### ISSUE TITLE
INVESTIGATE: NIMROD - spectra graphs failing intermittently

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4843]
The spectra PVs on NIMROD are becoming disconnected intermittently and the dashboard PVs look to be updating and pausing regularly.

**Comment by Tom-Willemsen** [comment]
Work out whether we need to be in cycle with real data to reproduce this issue

**Comment by Tom-Willemsen** [comment]
This problem is reproducible while NIMROD is quiet counting (with a real DAE).

**Comment by FreddieAkeroyd** [comment]
OK, can have a look in shutdown

**Comment by John-Holt-Tessella** [comment]
Machine is switched off, moving to task to do when back in the office

**Comment by DominicOram** [comment]
Scientist is not sure if they've seen this happen recently. They suggested we close it and reopen if the issue reappears, I agree.
