### ISSUE TITLE
MERLIN: oscillating collimator stopped

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4845]
Originally by email then support phone, call from merlin as collimator had stopped oscillating. It looks like the IOC lost contact with the galil, which it also did a few says ago. Galil may have lost power? It now seems the jaws have both limits enagaged which may mean the motors are off. @aaron-long  and @Tom-Willemsen are investigating and will pass onto Jamie if appropriate

**Comment by Tom-Willemsen** [comment]
Duplicate https://github.com/ISISComputingGroup/IBEX/issues/4846
