### ISSUE TITLE
MERLIN: Oscillating collimator not responding to inputs

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4846]
A called as the oscillating collimator OPI had different values than those displayed in the blocks, and the frequency displayed NaN on the OPI (with a link alarm). A had attempted to input new values into the OPI but it was not responding. He noted that the previous day (a maintenance day) there had been work conducted on the Galil to replace capacitors and that currently the jaws set was completely turned off. He also noted that no maintenance was conducted this day to his knowledge.

- The logs were checked and it was seen that limits were hi/li triggered (explained by the switched of jaws axes). At some point the Galil had lost connection for some unknown reason.
- The Galil was queried directly using commands and responded as expected.
- The IOC was restarted and behaviour returned to normal.
- A quick demo was shown to A on how to restart the driver in the event this happened again.

**Comment by DominicOram** [comment]
Sounds like an underlying hardware issue, not much I think we can learn here.
