### ISSUE TITLE
SANDALS: Rotating sample changer blocking beam

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4850]
After analysing data taken from running scripts, spectra were noticed that should not have been there for the sample. After investigating the sample changer had drifted and was blocking part of the beam.

- Re-homed sample changer axes. Further data will be taken to check if the problem is resolved.

**Comment by John-Holt-Tessella** [comment]
Is this a specific problem with the sample changer in IBEX or is it that they rehomed the sample changer in SECI more often?
