### ISSUE TITLE
TOSCA: Run wont end.

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4851]
TOSCA had been set to run via script, but when returning the run had not ended. Clicking stop had no effect, nor running a `g.end_run()` command.

The log showed the following:

```
NIVISA: Error "Could not perform operation because of I/O error." (code 0xbfff003e) returned from "viMoveIn32"  while transferring 1001 items at VME address 0x18000fa4
```
WHich has been seen before [link](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting).

The user was worried as there didn't seem to be a raw data file in the normal place and they were worried they would loose data. We restarted the IBEX server, and the End run (from the DAE perspective) worked. After the run data was produced they attempted a Mantid analysis but they noted that the data looked wrong (A single line, no actual data present).

They wanted to try and take more data quickly (by doing a short run) and comparing, just to make sure the system was working and they could compare data to the last run and would contact if they needed further assistance.

**Comment by GRyall** [comment]
This ticket no longer serves a useful purpose. Relevant GL today reported no ongoing issues they are aware of with their use of IBEX.
