### ISSUE TITLE
IMAT: Messina camera PC shutdown

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4852]
G called as at approx 2:40 am the Messina camera had lost connection and their script had halted. From the office we were unable to ping or see the PC on the network. I went down to IMAT and started the PC which then successfully booted. After starting the camera software it worked correctly and connected to IBEX.

The reliability monitor indicated that the PC had failed shutdown correctly. There had been a beam off at 2:30.

- Asked Chris to check the management logs to check if anything specific was at fault. G had lost 7 hours of beam and needed to know why.

**Comment by ChrisM-S** [comment]
I've had a look at the logs and also looked to see if there was a dump file (from a machine bug check), however there is no smoking I can find.  Tt does look like the machine either hung or shutdown, possibly could have been a mains blip or a driver which got upset and went into a tight loop.  @aaron-long could you tell if the system on (showing any lights etc.) when you restarted it or powered down (no fans etc.)?

The machine is basically a desktop so it is quite possible that there are odd faults which we might not see (a single bit DIMM error for example, probably not ECC RAM, could just lead to a hang or crash).

**Comment by GRyall** [comment]
Support issue 5 years ago, nothing more to be done.
