### ISSUE TITLE
MUONS: Zero-Field - Auto-Feedback IOC

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4855]
The current procedure is described [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller#implementation), along with a flowchart and further notes throughout the page.

**Notes**
The IOC will provide closed feedback control of the zero-field by continuously monitoring the magnetometer PVs (#4838) and adjusting the PSU currents accordingly.

**Acceptance Criteria**
* An IOC that will maintain the zero-field

**Comment by Tom-Willemsen** [comment]
COnsder the case where pvs become disconnected

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1004
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/267
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/447
- https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/1
- https://github.com/ISISComputingGroup/EPICS/pull/195

Docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller

Note: this ticket depends on https://github.com/ISISComputingGroup/IBEX/issues/4838 , it makes sense to review that ticket before this one.
