### ISSUE TITLE
IMAT: Set-up SP2XX syringe pump

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4856]
G called as they required the use of the SP2XX syringe pump. They were unsure as to how to add it to their current configuration.

A component existed that had previously been set-up for the instrument (see [#3298](https://github.com/ISISComputingGroup/IBEX/issues/3298)). But (like the previous support) they didn't have the correct cable (RJ11 input). 

The Soft Matter team were contacted and initially we were provided a replacement cable (RJ11->RJ45), but this did not work after testing many configurations. Finally we were given a different pump, which contained the correct cable (RJ11->DB9(female)) which worked without issue.

We tested the pump to ensure the scripting commands would work.

- Updated the wiki for troubleshooting assistance [Link](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/WPI-SP2XX-Syringe-Pump)

**Comment by DominicOram** [comment]
👍
