### ISSUE TITLE
WISH: Set-up Mercury ITC

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4857]
WISH have borrowed GEM's Mercury ITC cryostat. They had set up up next to the normal rack but were struggling to get it to communicate. They had opened all the correct VI's but had not got the correct baud rate set.

- Corrected the baud rate to the correct value so the VI could speak to the controller
- Update wiki for troubleshooting [Link](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC)

**Comment by DominicOram** [comment]
👍
