### ISSUE TITLE
NIMROD: high limit on shutter status being reset to zero on config change

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4858]
As an instrument scientist on NIMROD, I want to ensure my configuration run control settings are being applied correctly.

NIMROD have reported that whenever they change configs their shutter run control settings get changed to:
```
lowlimit = 0.9 highlimit = 0
```

In the configuration, the run control settings are defined as:
```
lowlimit = 0.9 highlimit = 1.1
```

This causes them to go into run control when the shutter is open. Investigate why settings from config are not being applied correctly on config change.

**Comment by Kevin-Woods-Tessella** [comment]
If the `lowlimit = 0.9` and the `highlimit = 0`, then the `lowlimit` is greater than the `highlimit`.  Has the scientist got his limits the wrong way round? (or is there a typo in the initial comment?)

**Comment by Tom-Willemsen** [comment]
There isn't a typo above. In the config it is defined sensibly (low=0.9, high=1.1). It is being reset to the "wrong" order on config change. I am not sure why - that's the point of this ticket.
