### ISSUE TITLE
VESUVIO: Update Mclennan foil offset in macro [Tasks: Shutdown]

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4859]
As a VESUVIO instrument scientist I need to be able to home my motors. The offsets added in ticket #3210 does not work for one of the foils (foil homes in wrong direction).

We need to speak with the instrument scientists to get the exact values required as each of the foil offsets. The macros need to be updated in the mclennan motor component relevant to the foils, and demonstrate how this is done to the instrument scientists. After this it is important that the new configuration is tested, so we know the foils will home correctly.

We have been told that they can run as they are until the end of cycle, but they need a solution that works shortly after the start of shutdown.

### Acceptance criteria
 - [ ] Macros updated to the correct values
 - [ ] Both foils have been demonstrated to home correctly

**Comment by John-Holt-Tessella** [comment]
Scientists contacted arranged for 9am 29th October,

**Comment by Tom-Willemsen** [comment]
This was done on vesuvio oct/nov 2019 - I checked using git log on the relevant config file.
