### ISSUE TITLE
Install latest ISISICP for testing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4861]
As a developer I would like the latest ISISICP installed on the nodes running system and other tests

Also take opportunity to fix some issues in install bat files.

**Comment by FreddieAkeroyd** [comment]
running  install_laetst_isisicp.bat  -> should install isisicp to c:\labview modueles\dae 

instrument_install_latest_build_only.bat  only gets run on build servers

A good test may be to run the run instrument update script on e.g. ndxscidemo

**Comment by DominicOram** [comment]
Ticket actually addressed in https://github.com/ISISComputingGroup/IBEX/issues/3928, modified to just include the error checking bit.

**Comment by DominicOram** [comment]
Added into sprint as it looks like it just needs review
