### ISSUE TITLE
VESUVIO: unable to begin (DAE3 issue)

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4863]
Had call from VESUVIO, ibex hung in BEGIN command. They had tried killing isisicp, but no change. I had a look at log file and lots of retries, restarting DAE process no change. Contacted Simon Moorby who guided them through a DAE3 power cycle via unclipping front card. After this, ethernet adapter 1 on the DAE3 stopped responding. Tried a full power cycle via rear switch, but no change. Simon Moorby is going to change the DAE3 card.

Note: should put pictures of DAE3 power buttons somewhere for general use and power cycle instructions

**Comment by GRyall** [comment]
Call was resolved, no clear requirement in ticket, so closing it.
