### ISSUE TITLE
Jasco: Setpoints not propagating properly

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4867]
During support work setting up a Jasco on POLREF, we noticed a bug where Setpoint values from the VI (e.g. flowrate, pump volume) did not propagate properly, i.e. the readback value would remain unchanged when clicking "set" or "set all". Repeated clicks did not do anything, you would have to set a new SP value to get the RBV to change.

We saw this bug 3-4 times during 5-10 minutes of manual testing, but we could not establish a workflow to recreate it reliably. We are not yet sure where the issue lies, e.g. it would be interesting to monitor the IOC to see whether the readback value actually gets updated or not.

We should try to get a Jasco if we can us for testing in order to recreate this bug. Failing that, try to get some time on POLREF to test with the device there.

**Comment by John-Holt-Tessella** [comment]
This has been superseded by many other tickets.
