### ISSUE TITLE
MERLIN: set up cryomagnet

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4868]
As a scientist on MERLIN I need help setting up a cryomagnet configuration and plugging in associated devices

Set up:
- IPS for controlling the 7T magnet, limited to 2T on MERLIN due to design of the tank
- ITC for magnet cryostat
- ILM
- Magnet rotation stage (Mclennan)
  * Electronics needed to swap the mclennan control crate for a different crate
  * Settings copied from LET's equivalent rotation stage, checked homing and checked it moved sensibly
- Neocera LTC21 measuring 2 temperatures on the sample stick

**Comment by davidkeymer** [comment]
Confirmed by looking through SE log data that the magnet and its various pieces of equipment were used successfully for several days and very many runs with varying parameters.
