### ISSUE TITLE
Reflectometry: Allow for sample position change

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4873]
After a discussion with M: Many reflectometers could make use of being able to move the sample closer to slit 1. Moving the sample closer allows for large % increases in neutron flux for free. The position (or position offset) needs to be saved to the nexus file so Mantid is able to analyse data. 

![move sample position](https://user-images.githubusercontent.com/43140680/67474763-eddad600-f64c-11e9-9374-8fb89c40ce2e.png)

## Acceptance Criteria

- [ ] The sample position is saved to the nexus file
- [ ] Documentation exists on how to set the position in the configuration file for this process (i.e., section for changing sample position)

**Comment by ThomasLohnert** [comment]
We will do this with 2 separate configs with different Zs
