### ISSUE TITLE
Python 3: convert block cache

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4881]
```
./ISIS/inst_servers/master/BlocksCache/blocks_cache.py
```

Remember and char pvs need to be written to with byters not python 3 str.

**Comment by JamesKingWork** [comment]
Ensure tested in Python 3 in EPICS jenkins_build.bat (Line 174 at time of comment)

**Comment by Tom-Willemsen** [comment]
The block cache was removed in https://github.com/ISISComputingGroup/IBEX/issues/4136 - this ticket is no longer relevant.
