### ISSUE TITLE
Python 3: migrate NICOS script server so that it can run a users Python 3 Script

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4887]
As a user and developer I want the (nicos) script server to run on the latest version of Python.

Acceptance criteria:
- A python 3 user script can be run via the NICOS script server.

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS/pull/202
https://github.com/ISISComputingGroup/genie_python/pull/218
