### ISSUE TITLE
Python 3: convert device emulators

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4889]
As a developer I would like all of the lewis emulators in `./support/DeviceEmulator/master/` to run under Python 3.

**Comment by John-Holt-Tessella** [comment]
@aaron-long because you were not included in the sprint planning capacity I have added the training label and set the points to 0. It was not because I think this ticket is easy or that this is necessarily a training ticket.

**Comment by aaron-long** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/87

**Comment by aaron-long** [comment]
Updated emulators to support Python3. Tested using PyCharms Python3 code compatibility inspection (Severity: Error, Scope: All, Version: 3.7) and Pylint 2.6.0 using Python 3.8.1.

Emulators can be run under Python 3 by setting the `_DEFAULT_PY_PATH ` to a Python 3 path in the IoC Test Frameworks `emulator_launcher.py` module.

**Comment by rerpha** [comment]
Just a thought, once this is merged we should update https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Python-versions---2-vs-3

**Comment by rerpha** [comment]
This should also be updated: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Emulating-Devices as it has a few references to the python2 installation dir in how to run the emulators
