### ISSUE TITLE
Python 3: convert deployment/utility scripts

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4893]
As a developer I want the utility scripts in https://github.com/ISISComputingGroup/ibex_utils to run under python 3

Acceptance criteria:

- ibex_utils python scripts are python 3 compatible
- scripts are run in python 3

**Comment by DominicOram** [comment]
As part of https://github.com/ISISComputingGroup/IBEX/issues/5573 I converted the pre/post deploy steps to be python 3
