### ISSUE TITLE
Python 3: convert VmsJournalFileConverter

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4897]
As a developer I want https://github.com/ISISComputingGroup/VmsJournalFileConverter to run under python 3.

**Comment by DominicOram** [comment]
Is VMSJournalFileConverter actually required?

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/VmsJournalFileConverter/pull/1

**Comment by DominicOram** [comment]
Added as a training ticket
