### ISSUE TITLE
Python 3: convert squish tests to run under python 3

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4900]
As a developer I want squish to use python 3

**Comment by JamesKingWork** [comment]
Looks like this might be difficult until we are running on Squish 6.6 or greater https://kb.froglogic.com/squish/howto/changing-python-installation-used-squish-binary-packages/

**Comment by rerpha** [comment]
I'm going to switch the version on the squish runner machine, and write some docs on how to do this locally. Squish comes bundled with python 3 now as of 6.6 as James said, and i'd rather not be maintaining python 2 code if possible!

**Comment by rerpha** [comment]
Added a step in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-Squish

**Comment by rerpha** [comment]
PRs:

squish tests - https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/90
release notes - https://github.com/ISISComputingGroup/IBEX/pull/6529
