### ISSUE TITLE
Script Generator: Provide default values in the configuration

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4907]
As a scientist writing a configuration for the script generator I would like to be able to specify the default values when a new row is added to the script generator by a user.

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by JamesKingWork** [comment]
Will have to edit current squish tests to work with this

**Comment by DominicOram** [comment]
As I put on the PR, can someone double check the merge I did for this?

**Comment by RaiBishal** [comment]
Merged code looks fine. All test passes and Script generator works as expected.

**Comment by DominicOram** [comment]
@RaiBishal If you're happy with it then go ahead and merge it
