### ISSUE TITLE
Script Generator: Bundle python with the GUI

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4910]
Python is a requirement for the script generator and so should be bundled with the GUI and with the standalone script generator so that a user need not install it separately. The script generator should use this bundled version of Python in all the following cases:
* Eclipse build on a dev machine
* Mvn build on a dev machine
* Mvn build on build server

The bundled version should be python 3.

**Comment by DominicOram** [comment]
I have started this work [here](https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket4910_bundle_python_with_GUI)
So far I have:
* A symlink inside `uk.ac.stfc.isis.ibex.scriptgenerator` to your local python 3 install
* This is then copied into the maven build version, such that this version is stand alone

This causes a couple of issues:
* `build.bat` must be run before the eclipse build can work and it must be run as an admin to create the symlink
* `build.bat` now takes significantly longer as it has to copy the whole of the python directory. I think this is unavoidable though as it needs to do the copy so that it can stand alone

The final part of this ticket is to get the bundling to work on the build server as the above is for developers. I have not started this.

**Comment by JamesKingWork** [comment]
Created a pipeline for [branch](https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket4910_bundle_python_with_GUI) to get bundling working on the build server 

http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui_python_bundle_pipeline/

**Comment by JamesKingWork** [comment]
>     * `build.bat` must be run before the eclipse build can work and it must be run as an admin to create the symlink

We either need to:
- Find an alternative to using a symlink
- Run the build as admin in Jenkins (security concerns)
- Give the Jenkins user rights to create a symlink

**Comment by JamesKingWork** [comment]
The decision that we have made is that on the build server we will fully copy Python 3 into the ibex client. This will then be a separate python to a genie python installation, but we are fine with this as we may look towards using only this python on instrument machines when we have converted to python 3. This python will be available to the script generator and ibex in general from the uk.ac.stfc.isis.python

However, on a developers machine, we will want to use the latest version of genie python we have pulled in Instrument\Apps... and as such we will not copy python 3 on dev machines but return the location of the local genie python in uk.ac.stfc.isis.python

**Comment by JamesKingWork** [comment]
Updated documentation: 
* https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Jenkins-Build-Server

**Comment by JamesKingWork** [comment]
Now using branch: https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket4910_2_bundle_python_with_gui

**Comment by JamesKingWork** [comment]
#4759 Script generator tests now pass due to changes made here.

**Comment by KathrynBaker** [comment]
Removing Ready flag as the ticket is in progress

**Comment by DominicOram** [comment]
As discussed we need to decouple starting the `scriptgenerator` plugin and running python. This is because surefire will start the plugin as part of the unit tests and python has not being correctly bundled at this point.
