### ISSUE TITLE
Genie python: Releasable fix for cset/gcet for 5.6.1

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4911]
To avoid  #4136

```
unableToConnectToPVException(name,  'does not exist')
UnableToConnectToPVException: Unable to connect to PV IN:POLARIS:CS:BLOCKSERVER:BLOCKNAMES: does not exist
```

Fix by retrying command every 10s on diconnected pv error. Print a message on first retry at that time. For:

1. cget
1. cset
1. cshow

Create a release 5.6.1

**Comment by FreddieAkeroyd** [comment]
The underlying issue is with contacting the blockcache process, in particular the BLOCKNAMES and BLOCKVALUES pvs.    All access is via the    get_block_names()    and      get_current_block_values()     method so maybe add the retry logic there?

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/186
