### ISSUE TITLE
Release: Do deployment

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4912]
Do the release of genie_python 5.6.1 and GUI 5.6.1 and database truncation .

### Muon instruments, instrument scientists contacted

- RIKENFE
    - [x] Started
    - [x] Finished
- MUONFE
    - [x] Started
    - [x] Finished

### IRIS

- IRIS (contacted by email they have a graph plotting)
    - [x] Started
    - [x] Finished

### SANDALS

- SANDALS - **Leave alone for now, check with @FreddieAkeroyd**
    - [x] Started
    - [x] Finished

### Full deploy 

Then fix [4393](https://github.com/ISISComputingGroup/IBEX/issues/4393)

- EMMA-A
    - [x] Started
    - [x] Finished
- MERLIN
    - [x] Started
    - [x] Finished

### Patch deploy

- ALF
    - [x] Started
    - [x] Finished
- ENGINX
    - [x] Started
    - [x] Finished
- ENGINX_SETUP
    - [x] Started
    - [x] Finished
- GEM
    - [x] Started
    - [x] Finished
- HRPD
    - [x] Started
    - [x] Finished
- IMAT
    - [x] Started
    - [x] Finished
- INES
    - [x] Started
    - [x] Finished
- IRIS_SETUP
    - [x] Started
    - [x] Finished
- LARMOR
    - [x] Started
    - [x] Finished
- LET
    - [x] Started
    - [x] Finished
- LOQ
    - [x] Started
    - [x] Finished
- MAPS
    - [x] Started
    - [x] Finished
- MARI
    - [x] Started
    - [x] Finished
- NIMROD
    - [x] Started
    - [x] Finished
- OSIRIS
    - [x] Started
    - [x] Finished
- POLARIS
    - [x] Started
    - [x] Finished
- SELAB
    - [x] Started
    - [x] Finished
- SOFTMAT
    - [x] Started
    - [x] Finished
- TOSCA
    - [x] Started
    - [x] Finished
- VESUVIO
    - [x] Started
    - [x] Finished
- ZOOM
    - [x] Started
    - [x] Finished

**Comment by John-Holt-Tessella** [comment]
Files for hot fix being put on `...\CompGroup\ICP\Releases\Ticket4912_OPI_Opening_time_improvement_genie_python_fix`

**Comment by Tom-Willemsen** [comment]
Impeded until we can do SANDALS (need database to investigate sample changer issue)

**Comment by davidkeymer** [comment]
As part of review, checked that the two files had been installed on a selection of instruments.  Also that databases had been truncated by using TreeSize to view directory sizes.

While doing this, used Nagios `C:` warnings to determine IBEX instruments with low amounts of free disk space.  Then moved log files (conserver and ioc) to storage area to free up as much space as possible.  However, Nagios warnings still present due to small(er) disk sizes of some instruments.
