### ISSUE TITLE
MUONS: Muon-specific BEGIN and END commands

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4913]
As a muon scientist, I want to be prompted for parameters required for muon experiments when I use the `BEGIN` and `END` commands.

#### Acceptance Criteria
1. On typing `BEGIN`, I am prompted for the run title
1. On typing `END`, I am asked to confirm that the run title is correct
1. IBEX provides the same level of functionality as the muon-specific BEGIN and END commands in OpenGenie
1. The IBEX genie_python documentation is updated to document the muon-specific behaviour.

#### Notes
1. **N.B.** Ensure that the muon-specific `BEGIN` and `END` command behave the same way as their OpenGenie equivalents.
1. The functionality of the muon-specific `BEGIN` and `END` commands in OpenGenie may not be documented.  Check the OpenGenie code to figure out what needs to be done.
1. Are there other required (or optional) muon-specific parameters?
1. How do we ensure that these commands are seen only by users of muon instruments?

**Comment by kjwoodsISIS** [comment]
See also #3952.

**Comment by Tom-Willemsen** [comment]
Implement as instrument scripts

**Comment by JamesKingWork** [comment]
We have decided to create the scripts in the repo: https://github.com/ISISNeutronMuon/InstrumentScripts

**Comment by John-Holt-Tessella** [comment]
This doesn't seem sensible. Add them to 

1. Either a branch in configurations if they are for a single instrument
1. or to the general instrument scripts repository if they are for multiple instruments

**Comment by Tom-Willemsen** [comment]
@John-Holt-Tessella I'm a little confused by your comment suggesting to use the "general instrument scripts repository", as the linked location *is* the general instrument scripts repository (unless I've misunderstood your comment?)

**Comment by Kevin-Woods-Tessella** [comment]
The muon-specific BEGIN and END commands are for all muon instruments (but not for neutron instruments).  If these commands are placed in the general instrument scripts repository will they be visible to neutron instruments?

**Comment by Tom-Willemsen** [comment]
@Kevin-Woods-Tessella yes, the "general" instrument scripts repository already has per-instrument folders and per-technique folders. The proposal is to put the code for these scripts in the muon technique folder.

**Comment by John-Holt-Tessella** [comment]
Sorry I have got my repos mixed up I thought this was a new repo.

**Comment by JamesKingWork** [comment]
PRs:
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/45
https://github.com/ISISComputingGroup/genie_python/pull/198

**Comment by JamesKingWork** [comment]
Additional PR:
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/34

**Comment by JamesKingWork** [comment]
Documentation for precmd and postcmd can be found at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/genie_python-Commands

**Comment by JamesKingWork** [comment]
This is a note to remind me that I need to work out this discrepancy:

It appears that there may be a bit of confusion as to what is meant by "run title" on this ticket. In the OpenGenie version what we call the run title is not set directly by the user but they set various sample parameters, beamline parameters etc. (@FreddieAkeroyd has suggested that from these set parameters a run title is built, but I cannot find where this is done in the OpenGenie code). The meaning of "run title" in the acceptance criteria may refer to the various parameters that are set. Maybe question the scientists over this.

**Comment by kjwoodsISIS** [comment]
OK.  Our confusion over how "run title" is set is a consequence of the current SECI/OpenGenie process being poorly documented.  The scientists will expect IBEX/genie_python to work in the same way as SECI/OpenGenie.  I don't think we need to ask the scientists how it should work - we should inspect the OpenGenie code and work it out (painful as it may be).
@JamesKingWork - can you ask @FreddieAkeroyd if he knows how the run title is assembled?
Alternatively, can we work it out for ourselves?

**Comment by JamesKingWork** [comment]
I cannot find it in the OpenGenie code (it may be on the LabVIEW side) having had a long look and currently, @FreddieAkeroyd isn't certain about how it is constructed. The reason I thought to ask the scientists is that if they search for the run by title and are expecting it to be a certain way then it is best to be consistent with what they expect.

**Comment by JamesKingWork** [comment]
Just to document the decision: "The muons the title is constructed from sample name, temperature label and field label. This construction looks to be done in the "sample parameters" labview vi, the isisicp justs get sent a constructed title along with the other details. Even though it doesn’t construct the title, it still writes the individual bits to the data file."

**Comment by kjwoodsISIS** [comment]
OK.  That sounds to me as if we could construct the title for ourselves.  We have two options:
   1. we write an IOC that does the same thing as `sample parameters.vi` (this doesn't feel like the right thing to do to me - I am only making this suggestion by analogy).
   1. we create a genie_python method to assemble the title.

**Comment by JamesKingWork** [comment]
I was thinking that it may be better to keep this muon specific and have it in the instrument scripts begin_precmd and end_precmd functions. It can then construct the title and set it with the genie.change_title command

**Comment by kjwoodsISIS** [comment]
Exactly.
