### ISSUE TITLE
MUONS: waitfor_events

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4914]
As a muon scientist, I want the `waitfor` command to have an `events=` option.

#### Acceptance Criteria
1. The `waitfor` command provides me with an `events=` option 
1. IBEX provides the same level of functionality as the muon-specific OpenGenie `events=` option of the waitfor command.

#### Notes
1. **N.B.** Ensure that the muon-specific `events=` option of the `waitfor` command behaves the same way as its OpenGenie equivalent.
1. The functionality of the `events=` option of the `waitfor` command in OpenGenie may not be documented.  You may need to inspect the OpenGenie code to figure out what needs to be done.
1. The IBEX genie_python documentation is updated to document the muon-specific behaviour.

**Comment by kjwoodsISIS** [comment]
See also #3952.

**Comment by davidkeymer** [comment]
The new GeniePython `waitfor` argument is named `mevents` (millions of events) and equivalent method, `waitfor_mevents`, as they more accurately reflect the value being used.  OpenGENIE uses `events`, even though the value is actually expressed in millions (and can also be a float which is counterintuitive).

This name change has been sanctioned by an EMU instrument scientist.

**Comment by davidkeymer** [comment]
The GeniePython documentation will be auto-generated by Sphinx when the code has been merged.

**Comment by davidkeymer** [comment]
Pull requests:
[GeniePython](https://github.com/ISISComputingGroup/genie_python/pull/192)
[ISISDAE support module](https://github.com/ISISComputingGroup/EPICS-isisdae/pull/59)
[DB Unit Checker script](https://github.com/ISISComputingGroup/EPICS-DbUnitChecker/pull/27)

**Comment by JamesKingWork** [comment]
OpenGenie code:
```
PROCEDURE _waitfor_events
PARAMETERS events=Real
LOCAL H str str1
LOG_ICP/WAITFOR "EVENTS" events "Started"  
LOOP
    Sleep 10 # allow for DAE panel to update
    H <~ 1.0 * GetLabviewVar($ISC_daeroot + "DAE Control.vi", "TotalDAECounts")
#             H <~ GetMEvents()         
    EXITIF (H > EVENTS)
    str <~ AS_STRING(events,"%.2g")
    str1 <~ AS_STRING(h,"%.2g") 
    printin "Waiting for " str   " MEV (so far " str1 ")"
ENDLOOP
LOG_ICP/WAITFOR "EVENTS" events "Finished" str1
ENDPROCEDURE
```
