### ISSUE TITLE
SANS: IOC and OPI for SANS-DLS

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4918]
As an scientist from a SANS instrument I want to be able to control the SANS-DLS equipment from IBEX. There is an experiment planned using the SANS-DLS system for the 5th of March.

Data collection for the DLS is controlled by the [LSi correlator](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LSi-Correlator). We have been given a python API which controls starting and stopping the hardware. The IOC will need to run the python API, and save the data in an appropriate format.

The user needs to be able to specify a run duration, number of repetitions and a wait time between repetitions. The LSi correlator API takes run duration as a parameter. It will be up to the implmentation of the IOC to control the repetitions and the wait time between them.

After each data collection has completed, the IOC must save the data. The output data used from the python API are: `LSICorrelator.Correlation` and `LSICorrelator.Lags` (See #4271).

We also need to take sample metadata from the users and save it alongside the correlation function and time lags. These are:
- Scattering angle
- Sample temperature
- Solvent viscosity 
- Solvent refractive index 
- Laser wavelength

For the purposes of this ticket, the save file format to use will be a CSV. The actual format requested by the user will be implemented in #4999.

### Acceptance criteria

- [ ] Can control the SANS-DLS data collection through the LSI correlator python API
- [ ] Run duration, number of repetitions and wait time can be set by the user
- [ ] Data collected from the correlator is saved
- [ ] Sample metadata can be input and is passed through to the save file

Notes:
- This is probably best implemented as a PcasPy IOC
- This won't have a lewis emulator. Mock the correlator api in python instead

**Comment by kjwoodsISIS** [comment]
@Alistair: in your [notes](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LSi-Correlator#conclusions-of-october-experiments), you say "Python API still needs modifying for python 3 ...".  Which API?  The API provided by the equipment vendor or an API we have created?  If it is the vendor's API that needs changing, when are they going to do that?

**Comment by Tom-Willemsen** [comment]
Split this into two tickets: one for aquiring the data, one for figuring out how and where to save it

**Comment by Alistair-McGann-Tessella** [comment]
Vendor software repo:
https://github.com/ISISNeutronMuon/LSI-Correlator

This branch will need to be renamed `master` after it is accepted.

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:
Top level EPICS: https://github.com/ISISComputingGroup/EPICS/pull/203
Genie python: https://github.com/ISISComputingGroup/genie_python/pull/220
IOC test framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/294
GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1048
inst servers: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/270
Vendor software: https://github.com/ISISNeutronMuon/LSI-Correlator
Support module: https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/1
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/475
