### ISSUE TITLE
Reflectometry: On Start of IBEX check positions

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4920]
This ticket is still in discussion:

As a user I would like IBEX on startup to compare the current positions of all the motors to those of when it was last running; this includes the positions that were stored within the SECI system if that was the last system running. If there is a deviation by more than the motor retry deadband then a warning should be issued to the user. 
If the motor positions are not available then no warning should be issued; this includes if the name of the motor can not be matched within SECI.
The check should occur after the configuration has loaded and only needs to include motors in the current configuration.

**Comment by ThomasLohnert** [comment]
We are not planning on switching back & forth between SECI & IBEX on the reflectometers. Closing
