### ISSUE TITLE
motor: fix position initialisation

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4921]
The most recent motor record will initialise positions on startup, this fix temporarily removes that change. A proper fix is coming in a new motor record release.

**Comment by FreddieAkeroyd** [comment]
This issue can be demonstrated on the office McLennan, @John-Holt-Tessella  and @FreddieAkeroyd plan to check on CRISP

**Comment by John-Holt-Tessella** [comment]
Also tried on CRISP:

before got line after auto save saying `GalilAxis::setPosition: incorrect ioc state, ignoring request to redefine motor position to 0 on axis A`

afterwards there is no line and motors remain defined as before
