### ISSUE TITLE
EMU: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4927]
As a developer, I want to migrate EMU to use the IBEX instrument control system.  As a scientist, I want EMU to be migrated to IBEX in time for the start of Cycle 2019/04.

#### Acceptance Criteria
1. IBEX is installed on EMU
   1. The IBEX server boot script is installed (see [IBEX auto-startup](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup))
1. EMU is added to the list of available instruments
1. Configuration files matching the current SECI config files are created 
1. IBEX is configured for the devices on EMU.
1. EMU scripts are converted to genie_python
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   * On EMU, the OpenGenie scripts are stored in the file EMU_Routines.gcl
   * The muon instrument scientists have provided a copy of the [EMU Manual](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/emu_manual_20190401.pdf).  Section 7.1.3 lists the most commonly used commands (especially, `begin`, `end`, `settemp`, `setmag`, `slits`, `tf20`, `lf0`, `f0`).
1. IBEX is tested on EMU

#### Notes
1. The devices on EMU are listed on the [EMU Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/EMU-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [ ] Ask Facilities IT (Anthony Shuttle) to create a private network for EMU.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   - Requested (06-11-2019) (Footprints Issue: FIT-13561).  Two private ports have been requested.
   - Done (dd-mm-yyyy)
   - [EMU VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/EMU_VLAN_Settings.txt)
- [x] Check that NDXEMU has sufficient disk space to install IBEX
  * EMU has 30Gb of free space.
- [x] Check whether EMU uses 5- or 8- digit run-numbers
   - [x] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [ ] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXEMUTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
      * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [x] test these configurations & scripts
   - [x] check that all the devices previously supported by SECI (on EMU) are supported by IBEX.
- [x] Check whether Mantid can support v2 of the Muons NeXus file (it's not essential that it does, but it would be good if it did).

**Comment by Tom-Willemsen** [comment]
EMU have two danfysiks: one for high field and one for low field. There was a command called `MAGNET` in SECI that appeared to do this, but after discussion with the scientists, this command does not do the right thing. We have agreed that IBEX can use components to switch between these two danfysiks (it corresponds to a different set of macros in each case).

**Comment by Tom-Willemsen** [comment]
The scientists would also like us to migrate the following scripts, which are used primarily for start-of-cycle calibrations (found in `U:\calibrations\scripts`):
- `KY_beamsteering.gcl`
- `KY_TFSCAN4T0.gcl`
- `KY_SlitsScan.gcl`

**Comment by davidkeymer** [comment]
> The scientists would also like us to migrate the following scripts, which are used primarily for start-of-cycle calibrations (found in U:\calibrations\scripts):
> 
> KY_beamsteering.gcl
> KY_TFSCAN4T0.gcl
> KY_SlitsScan.gcl

I am converting these scripts.

**Comment by Tom-Willemsen** [comment]
Configurations and synoptics for the kit which EMU needs in the upcoming cycle have been created and tested. The scientists have also been shown how to edit their configurations and synoptics themselves. I don't think there is anything remaining to do on this ticket.

**Comment by JamesKingWork** [comment]
Did we find out if MANTID can support v2 of the Muons NeXus file?

**Comment by JamesKingWork** [comment]
> Did we find out if MANTID can support v2 of the Muons NeXus file?

The answer is that MANTID know about it, they can plan it as they see fit
