### ISSUE TITLE
MUONS: Muons version of the BeamLogger

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4928]
As a muon scientist, I want the BeamLogger IOC to have equivalent functionality to the special muons version of the BeamLogger VI, so that muon related beam parameters can be displayed and logged by IBEX.

#### Acceptance Criteria
1. The BeamLogger IOC has a PV corresponding to `<muon-parameter-X> `
1. The BeamLogger OPI has a field displaying the read-back value of the PV corresponding to `<muon-parameter-X>`
1. If required, the BeamLogger OPI plots the PV corresponding to `<muon-parameter-X>` on the graph.
1. IBEX provides the same level of functionality as the existing muons version of the BeamLogger VI.

#### Notes
1. The muons version of the BeamLogger VI is located here: `C:\LabVIEW Modules\<where-is-it?>`
1. You will need to inspect the muons version of the  BeamLogger VI to determine which fields should be displayed by the IOC and OPI.
   1. Does the existing muons version of the BeamLogger VI display a superset of the existing BeamLogger variables?  Or does it display a different set of variables (which overlaps to some degree with the existing BeamLogger variables)?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - can you please update this ticket.  Please duplicate Acceptance Criteria 1. - 3. for each new PV that is required.  If any PVs are not required for the muons, can you also specify these too (so that we know to remove them).  Also, can you tell us where the muons BeamLogger VI is located within SECI?

**Comment by FreddieAkeroyd** [comment]
I don't believe there is a muon specific beamlogger, they requested for some additional accelerator parameters a year or so ago (bunch length extract delay) but i added these to the common beamlogger vi and they are available already in ibex i believe.

**Comment by KathrynBaker** [comment]
They are indeed available in IBEX, they are already on the OPI, and they were even added to the Facility PVs list (for display in the GUI) about a year ago (#3617)

**Comment by kjwoodsISIS** [comment]
OK.  So it appears the muons group do not have a muon-specific beamlogger VI.  The `BUNCH LENGTH` & `EXTRACT DELAY` PVs are indeed present in the IBEX BeamLogger.

For reference, here is a [screenshot of the beamlogger VI on EMU](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/EMU_BeamLogger_VI.png).

**Comment by kjwoodsISIS** [comment]
Given that the IBEX BeamLogger already includes the extra parameters the muons group requested, there is no further work to be done on this ticket.
