### ISSUE TITLE
4918-1: [Spike] Investigate where data from SANS-DLS should be saved

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4935]
Determine from the instrument scientist in charge of the SANS-DLS (aka 'LSI Correlator') what file format the output data needs to be in and where the data needs to be saved.

### Acceptance criteria
- [x] Ticket #4999 is updated with the information about the new file format

**Comment by Alistair-McGann-Tessella** [comment]
On 29/11/19 I asked the instrument scientist who is requesting this what file format would be most useful. The scientist is now asking their collaborators what their requirements are.

So work can get started on the main part of the IOC I have made a new ticket (#4999) to implement the new requirements when they come in.
