### ISSUE TITLE
Logging Connection Status and alarms for Blocks & PVs in NeXus files

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [ISISComputingGroup/IBEX#4936]
As a scientist, I want IBEX to log disconnected blocks and PVs in the NeXus file, so that take account of missing or uncertain data when analysing my data files.

#### Acceptance Criteria
1. On encountering an INVALID alarm, IBEX will log blocks with their last-known-good-value and the alarm status.
    
### Notes
1. The implementation details were discussed with Matt Jones (see e-mail chain titled Invalid values in NeXus files (dated: 06 June 2019 08:27).

**Comment by FreddieAkeroyd** [comment]
I have some ideas of how to do this, I think most of the stuff needed is actually already there

**Comment by JamesKingWork** [comment]
Is this actually in review? Is there a pull request for it?

**Comment by DominicOram** [comment]
@FreddieAkeroyd can you add a link to the ICP PR that did this? Also, can we think of a way to system test it?

**Comment by ChrisColeExpControl** [comment]
@FreddieAkeroyd I'm not entirely sure you meant to put this ticket in review as I can't find any PR which explicitly fulfills only this ticket, so I'm going to put it back in "in progress". If this is actually in review feel free to undo this and link relevant PRs. Did you mean to move [this ticket](https://github.com/ISISComputingGroup/IBEX/issues/5174) for [this PR](https://github.com/ISISNeutronMuon/ISISICP/pull/12/commits) instead?

**Comment by FreddieAkeroyd** [comment]
PRs are https://github.com/ISISNeutronMuon/ISISICP/pull/9 and https://github.com/ISISNeutronMuon/ISISICP/pull/12

**Comment by DominicOram** [comment]
The original text of this ticket says `IBEX to log disconnected blocks`. This change will log `INVALID` alarms e.g. when an IOC loses comms with the hardware but not `disconnected` errors e.g. when the IOC crashes and the PV no longer exists. I don't know enough about the original requirement to know if this is ok or not @FreddieAkeroyd and @Kevin-Woods-Tessella, do you have an idea?

**Comment by kjwoodsISIS** [comment]
Essentially, the scientists want to know if he/she can rely on the sequence of read-backs from a device (i.e. has that sequence been interrupted or not, for whatever reason).  This ticket deals with one specific case - have we detected an INVALID alarm event.  If so, we should log it in the NeXus file. If the implementation meets the acceptance criterion and passes review, then we should mark the ticket as complete.

It sound to me as if you have realised that there is another case, which we have not considered.  If so, then we should create a new ticket, to manage the implementation of the additional scope.  We should not extend the scope of this ticket.

**Comment by FreddieAkeroyd** [comment]
disconnected and archive off  were specifically filterted out previously, they are on a separate branch and enabled by https://github.com/ISISNeutronMuon/ISISICP/pull/18  logging archive_off i.e. indicate when you are no longer logging and not just that value has remained unchanged could be useful,  but mantid at the moment are looking to colour log entries red that have any invalid values, which means if I logged archive off every log would be red due to archive restart on begin. Logging disconnected and archive off are are optional as unless you know how to handle alarms you may get an arbitrary value inserted (I may not have a previous good value to log with the invalid alarm).

**Comment by DominicOram** [comment]
Cool, I'll take a look, thanks.
