### ISSUE TITLE
LOQ: unable to start eurotherm IOC

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4938]
Steve came by office - he is unable to start the eurotherm IOC. Looks like procServControl cannot talk to the console, will see if something else has grabbed the port

**Comment by FreddieAkeroyd** [comment]
The procserv for the eurotherm wasn't running, started it and then all ok. couldn't see any process that was blocking the tcp port.

**Comment by kjwoodsISIS** [comment]
This ticket sounds as if there is nothing left to do.  Can it be reviewed & completed?

**Comment by DominicOram** [comment]
I'm happy that there's nothing else to learn here.
