### ISSUE TITLE
SOFTMATTER: Unable to communicate with ALDN1000

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4939]
AC called as they were unable to communicate via IBEX to the ALDN1000. The IOC had been added to the current configuration and the device had been plugged into the matching macro'd COM port.

The issue was caused by two factors:
- Multiple (see: all) IOCs in the current configurations were using COM10
- The address for the pump had not been set (see below for more information)

The reason all devices are using COM10 is that the MOXA is up on a shoulder high shelf, with the IO in a semi-difficult to reach position. The team have a MOXA cable that they use to connect to devices as they get them in the lab (typically one at a time). I showed AC how to: 1. Disable auto-start/auto-restart for a given IOC, 2. How to add a component that can be switch in/out of the configuration. 3. Examine the list of IOCs running and sort by "in configuration" to turn off drivers not in use.

The pumps address had not been set in the OPI, so the driver was trying to communicate with pump `00`, rather than `02`. The pumps have labels on them that should indicate the address and the user had failed to notice this. I updated the Wiki with an extra paragraph under Networked Pumps.

**Comment by ChrisM-S** [comment]
+1
Similar issue sorted today, MOXA was also reset so needs a rename/password resetting at a convenient moment, it appeared that a couple of "COM10" settings had accidentally not been saved in a configuration.

I did suggest that if it's useful we could easily provide sufficient cables with fixed ports to provide stations for more/most devices to be connected simultaneously without needing to keep re-configuring one port.  We know that on instruments that change devices/ports, errors are more likely than with more fixed/labelled cables.
