### ISSUE TITLE
MAPS: Failure to load instrument script

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4946]
As a scientist on MAPS I would like to know how to reload an instrument script when I have been editing it (as opposed to a user script).
	1) I might be able to restart the python console using the red button
		- but  I see no errors and inst is not defined
	2) I might be able to do "import inst"
		- in this case I see syntax errors.

**Comment by ChrisM-S** [comment]
This issue was traced down after some time and expert involvement to a syntax error in an instrument script which was altered by the scientist.  They had modified some code and typed "`false`" instead of "`False`" in the python code.  Three issues with this:

1) The syntax error was not shown on restarting the python console (and no doubt also when restarting the client).  This left a hidden consequential error in the apparently working console of `inst` not being defined.

2) Restarting the console is not in itself an obvious thing to do - although possibly a good way of clearing up some programming mess-up.

3) The diagnostic to find errors in the script was to type `import inst` not obvious either!

what are we to do to reduce this sort of drain on our support resources.  The scientists was quite capable of understanding his python programming error when it was explained to him???

**Comment by kjwoodsISIS** [comment]
@RaiBishal -  Would the work you have done on #4630 have caught this error?

**Comment by RaiBishal** [comment]
@kjwoodsISIS Unfortunately the work being done on #4630 only catches errors in the user's script because linting is only performed when `g.load_script()` is called.

**Comment by ChrisM-S** [comment]
I've closed this and created #4965 to address this issue directly.
