### ISSUE TITLE
SUPPORT: Larmor Densiometer not working (DMA4500M)

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4947]
The LARMOR densiometry does not work. It appears that the DMA4500M is sending back a different amount of data (maybe it is a different model) updated this on Larmor.

**Comment by John-Holt-Tessella** [comment]
Specific gravity is not produced in the mode that is used at ISIS this should be commented out of the device.

Similarly automeasure does not work and should be commented out.

**Comment by John-Holt-Tessella** [comment]
Created a pull request:

- https://github.com/ISISComputingGroup/EPICS-dma4500m/pull/4

and a ticket:

https://github.com/ISISComputingGroup/IBEX/issues/4948

**Comment by FreddieAkeroyd** [comment]
Do we have a different model of densitometer, or are just running it in a different mode and it could return specific gravity if setup differently? Can't we make the changes macro configurable as now the ESS Nurf densitometer model would not work with this IOC after this PR

**Comment by Tom-Willemsen** [comment]
It returns a different response format depending on which mode it's in according to Rob. They do not plan to run it in the mode where it would return a specific gravity for this experiment. 

I think the intention of the PR in this ticket is to solve the immediate issue on LARMOR, in case we don't get around to doing the wider changes notes in #4948 (which include making the protocol generic/configurable) before the next deployment.
