### ISSUE TITLE
IOC: DMA4500AM Bring up to standard

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4948]
The DMA4500aM should be bought up to the same standard as other IOCs or deleted from the system. The items needing doing are:

1. Emulator
2. System Tests
3. Propagating errors on disconnect to density measurement
4. Handling of different modes of operation, either by setting/checking mode before start or adapting protocol on mode change (see PR on #4947 for format)
5. All finishing touches

This is needed because it has generated a support call #4947.

See also https://github.com/ISISComputingGroup/IBEX/issues/3922

**Comment by kjwoodsISIS** [comment]
Original IOC was created by #3382.

**Comment by FreddieAkeroyd** [comment]
Automeasure should also be fixed, it looks like it is just an error in the calc field that thus made it always 0
```
2019-11-08 17:32:58] Bad assignment target in CALC expression 'A=0?1:(B:=(B=0?A:B-1);B)'
[2019-11-08 17:32:58] Can't set "IN:LARMOR:DMA4500M_01:automeasure.CALC" to "A=0?1:(B:=(B=0?A:B-1);B)"
[2019-11-08 17:32:58] Error at or before ")" in file "C:/Instrument/Apps/EPICS/support/dma4500m/master/db/dma4500m.db" line 33
```
the automeasure feature was originally requested by NURF

**Comment by Alistair-McGann-Tessella** [comment]
Please also fix the build setup for this submodule. Running `make clean uninstall` deletes the db folder, which is where the source is kept in this repo.

**Comment by mr-field** [comment]
Linked PRs:
- IOC startup script (contains main review checklist): https://github.com/ISISComputingGroup/EPICS-ioc/pull/484
- Fixes and improvements to the IOC: https://github.com/ISISComputingGroup/EPICS-dma4500m/pull/5
- New emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/68
- New IOC tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/300
- New OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1075

New documentation has been added to the device's [wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DMA4500m-Density-Meter)

**Comment by mr-field** [comment]
This is now ready to be reviewed again
