### ISSUE TITLE
VESUVIO: cable new tank & guide TPG300 to moxa and set up in config

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4950]
As a scientist on Vesuvio, I would like to be able to read my new TPG300 sensor which has been set up to monitor the tank and guide.

> Sunil has set up a new connector block reads back the pressure readings on the VESUVIO tank and guide into the VESUVIO cabin.
Jon told me that it needs to be connected the same way the furnace pressure is currently read out on the IBEX VESUVIO dashboard.
The cable in the cabin should be connected between the MOXA panel and the DS10 socket, as per the photo attached, and then a new component needs to be added up on the IBEX configuration.

Scientist has requested that this be done on the maintenance day on the 27th. They would like this in place for an experiment with a furnace on 9th of December.

Acceptance criteria:
- [x] Cable route checked and corrected if necessary
- [x] IOC added to Vesuvio's base config
- [x] Appropriate blocks & groups created

**Comment by Tom-Willemsen** [comment]
Physically connected TPG to moxa, set up 3 pressure readings (from a single TPG300) on vesuvio, set up blocks and added to config. Scientist was present for verification that they were happy with the setup.

**Comment by davidkeymer** [comment]
Blocks checked in Base component (`beamline` in this case) and confirmed reading sensible values from device.
