### ISSUE TITLE
LARMOR: blocks not being logged correctly

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4955]
Rob called from LARMOR: apparently blocks are not logging/going into the nexus file correctly.

Possibly related to NURF setup/arrays

Investigate.

**Comment by FreddieAkeroyd** [comment]
Had text from Rob when I was in transit and then a follow up saying "all sorted, blocks were swapped around" - so this is OK now?

**Comment by Tom-Willemsen** [comment]
Yes, Rob called back later in the evening to say that the block had just been pointed at the wrong thing, and that it was in fact ok.

Closing this ticket, there is nothing further to look at here.
