### ISSUE TITLE
Reflectometry: Create reference manual for Reflectometry front panel

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4956]
As a reflectometry user, I would like to have access to a reference page for the reflectometry front panel in the user manual, with explanations of the functionality, what various types of indicators mean etc.

This should be done once the UI is more or less finished and not subject to any major changes.

**Comment by John-Holt-Tessella** [comment]
- https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Reflectometry-View#front-panel
- https://github.com/ISISComputingGroup/ibex_gui/pull/1246
- https://github.com/ISISComputingGroup/IBEX/pull/6150
