### ISSUE TITLE
SANDALS: Temperature logs missing since 11th November

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4960]
User on SANDALS reporting odd temperature “excursion” from the 80 degree set point to 60 for some time - and then a return to 80.  Seems like an artefact but there are no values in the Julabo IOC log to check this.  No sign of run control entries in the IOC log (the temp is under +/- 2.0 degrees C.

**Comment by ChrisM-S** [comment]
Not clear if there should have been a julabo IOC log file or not - seems odd to be missing it -, but values were recorded in the instrument log files on the archive so I could confirm that there had been no significant excursions of the temperature from the 80 degrees C setpoint value since 12 November.

What is the easiest way of plotting a log file on an instrument? is there an equivalent of the load_log command which on SECI machines would load log file data into Open GENIE for display?

**Comment by John-Holt-Tessella** [comment]
Easiest in the GUI, just open it and plot in log plotter.

Can get times out using the script which is `inst_servers/blob/master/scripts/log_file_generator.py` there is another script on the branch to get out events. However this is probably the one you want (yes it should be in genie but it isn't)

**Comment by John-Holt-Tessella** [comment]
![image](https://user-images.githubusercontent.com/7570055/69048596-c978dc00-09f5-11ea-89b9-0d98fa9709f5.png)


out put

![image](https://user-images.githubusercontent.com/7570055/69048627-d4cc0780-09f5-11ea-9c80-feedf74fc3dc.png)

**Comment by John-Holt-Tessella** [comment]
This is more useful:

![image](https://user-images.githubusercontent.com/7570055/69048774-3e4c1600-09f6-11ea-8e22-61e7202d619d.png)

**Comment by ChrisM-S** [comment]
Is the log plotter being inconsistent again?  This looks like the plot the user should have seen but I recall a single step up from around 60C to 80C at around 12-1 yesterday and everything earlier back to the 12th being almost a straight line at 60C.  Could this be the plot coming from a bin width set up much earlier at the time logging was switched on, a bit like the issues we saw this morning on ticket?

**Comment by ChrisM-S** [comment]
I guess the question is what should I be telling SK to close this ticket and answer her query about this behaviour.

**Comment by kjwoodsISIS** [comment]
What is the problem here?  The title of the ticket says "SANDALS: Temperature logs missing since 11th November".  But the body of the ticket talks about "an odd temperature excursion".

Here's a plot of the `julabo_bath` block from 10th - 19th November.  I see no missing log data.
![image](https://user-images.githubusercontent.com/7249337/69130727-f0441a80-0aa8-11ea-822b-f91b1639d513.png)

The log plot does show that, over this period, the temperature rose from 0 to 80 in steps.  And then went back down to the mid-20s.  This doesn't strike me as especially odd, unless the scientist was expecting the temperature to behave in a different way.

**Comment by kjwoodsISIS** [comment]
I would tell the scientists this:
   1.  The log data is all there.  It is not missing.  You could show the scientist how to generate this plot (although I would expect them to know how to do this).
   1.  IBEX is logging the temperature as expected.  The temperature changes don't look unusual to us.  But, if the temperature changes are not what the scientist expects, perhaps there is a problem with the Julabo.

**Comment by ChrisM-S** [comment]
Sent a note to SG.

After discussion earlier, it seems possible that the data missing (in the original log plot only) may be related to the data being added to the plot directly from the PV which is a different data path (the plots above show that when the plot is refreshed/loaded from the archive database all data is there).  Being as this is quite important, is there a log plotter ticket which will fix this (which I can refer to here) or do I need add another one specifically for errors on this data path?

We could, for instance, do a refresh of the plot from the archive on an axis scale change for example or once every few hours as a workaround - or maybe it is possible for the user to force this (dare I say via a reset client? reset/plot?).

**Comment by kjwoodsISIS** [comment]
@ChrisM-S  :  I think there are some important points we need to stress to the scientist:
  1. The log data is not missing
  1. A screenshot of the original plot would have been helpful to us in attempting to diagnose the problem.  Without a screenshot we can only speculate about what _might_ have happened.
      1.  One possibility is simply a drawing glitch.  Re-generating the plot would probably have fixed that.
      1. Another possibility is whether the data being viewed is coming directly from the PV (in which case there is no history prior to the point at which you start plotting) or from the archive (in which there is a full history).  This is a subtle point.  A screenshot could help us distinguish between these two cases.  We can take you through the differences between these two cases.
      1. The plots are generated by library code (i.e. code not written by the IBEX developers).  We recently discovered a bug in the library code, which may possible have caused the problem experienced on SANDALS (but this is speculation).  We believe we have now fixed this bug (see #4722).
   1. I don't think forced refreshes of the plot are appropriate solutions.

**Comment by kjwoodsISIS** [comment]
This issue now seems rather stale - and it was a non-issue anyway.  Case closed!
