### ISSUE TITLE
Genie_python: On set_instrument provide better error description

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4965]
As a user or a support person, I would like ALWAYS like to see errors on the restart of an instrument scripting console IF there are errors in an instrument script because:

1) The script may not work and I will not know and I could lose beamtime.
2) Diagnosing the result of unknown syntax errors by later behaviour is hard for support staff!

**Notes:**
Needs investigating and fixing, savings in support time are going to be increasingly valuable.
I'm not sure why errors might not be reported (see ticket linked in history above) and whether this is by an error or design.  We have struggled with people who have switched off errors/Warnings in Open GENIE because they found some things a bit annoying - but the issue inevitably comes back to bite at some more awkward time!

**Comment by John-Holt-Tessella** [comment]
We need more details for this ticket. If I add a syntax error to my inst scripts I see:

![image](https://user-images.githubusercontent.com/7570055/69858678-6c4d1800-128a-11ea-988c-59f858fd2084.png)

The error is indicated

**Comment by John-Holt-Tessella** [comment]
Also to make clear the linter is not run on the instrument scripts loaded in this way. Maybe it should be but it currently is not.

**Comment by ChrisM-S** [comment]
I guess this plain text error is quite understated for an error which means the instrument will not work from now on! Also it is well masked by red text displayed up above drawing the eye to something that appears not actually to be an error.

1) From my recollection there was no red text on the maps console restart, just blue and black.  The last paragraph also at a glance looks informational and I couldn't say that I would have spotted this if this was what it said, however @Tom-Willemsen and @davidkeymer, I think you both saw the console and @Tom-Willemsen, you suggested we used "import" to find the error.  Both of you would have been more likely to spot this (if shown as above) than me.

2) Is there are record in a log file on MAPS still available which we could use to check what was sent to the console?

3) We could check with RS to see if we could try re-introducing the error at a convenient moment on MAPS to see whether the behaviour matches the above.

**Comment by Tom-Willemsen** [comment]
The error did appear on MAPS on console start, but as you say, isn't hugely obvious as it gets printed alongside some other normal output when the console is first being set up.

In python `import thing` is a pretty standard response to an error of the form `thing not defined`, and I feel that this is within the scope of the python knowledge we expect of scientists. Given that this correctly repeats the error, I don't think there is any more that we need to do on this ticket.

**Comment by ChrisM-S** [comment]
This might be OK in a development environment, but users who likely know very little python need something much more obvious and also need to know there is a serious problem.  Scientists do sadly edit scripts and only discover they are wrong later, particularly simple edits they know they will get right…

Ugly red errors with diagnostics and possibly a refusal to proceed should probably be the minimum if a script is broken – or who knows what will happen later on in the day when a script comes across a weird error.

Could we simply run “import” on the file when an error is reported automatically to get this?

**Comment by John-Holt-Tessella** [comment]
Pull requests:

https://github.com/ISISComputingGroup/genie_python/pull/199

**Comment by John-Holt-Tessella** [comment]
Hopefully better
![image](https://user-images.githubusercontent.com/7570055/70928301-a2c7b880-2028-11ea-92c8-fe3991c01b75.png)

and

![image](https://user-images.githubusercontent.com/7570055/70928310-ab1ff380-2028-11ea-88a1-86c30947ba2b.png)

**Comment by ChrisM-S** [comment]
Excellent, really couldn't be any clearer (at least no way even I could miss this one) hopefully users would also immediately spot this and see the syntax error.

**Comment by John-Holt-Tessella** [comment]
Was already done
