### ISSUE TITLE
Reflectometry: OPI Improvements

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4967]
As a reflectometry user, I would like all parameters on the front panel to look the same and provide an individual move button, including slit gaps and Sample Stack parameters.
Display these parameters using a linking container pointing at `param_move.opi`. To accommodate for the increased width needed to display these parameters, we suggest the layout of the OPI front panel to be changed to the following:

![image](https://user-images.githubusercontent.com/18398579/69170136-7b490300-0af1-11ea-91cc-208e4ba7a855.png)

Further, important parameters are currently hardcoded into the OPI. Better would be if parameters can be tagged as "important" in the constructor (i.e. at the configuration level). This information can then be used in the PV manager to populate a list, which is read by the OPI to populate the important parameters panel.
Parameters already provide means to expose this information at the PV manager level via the `group_names` property.

### Acceptance Criteria:
- Slit gaps and sample stack parameters are displayed on the reflectometry front panel OPI using the `param_move.opi` (same as all other parameters)
- The layout is adjusted to reasonably fit everything
- The "important parameters" panel is populated dynamically based on a tag given to reflectometry parameters at the config level

### Notes:
- There should be a class for beamline parameters that wrap directly around a `PVWrapper` (without needing to track the beam path through a mid-level `Component`). `SlitGapParameter` basically does already does and can be made generic with small changes.

**Comment by aaron-long** [comment]
I think we should have an additional requirement:

- Ensure we have a consistent standard for how we present information
- Give column headers with tooltips

An example of a tooltip is:
![tooltip](https://user-images.githubusercontent.com/43140680/69337764-8e76e280-0c59-11ea-88db-502ada5ceb80.PNG)

In parameters we have no column headers which can be confusing at first glance:
 
![params](https://user-images.githubusercontent.com/43140680/69337779-9767b400-0c59-11ea-8150-482e16ac16d0.PNG)

**Comment by ThomasLohnert** [comment]
- "All Parameters" tab - we are hitting the limit of how many parameters can be displayed (currently: 22). I think for the moment it will be enough if we just increase this by making spacing tighter and the vertical size of the whole OPI larger. If we find this is not enough for other instruments later on we can consider adding a scrollbar after a certain threshold number of parameters.
- Content of the "alignment" tab is slightly oversized so that it appears with an unnecessary scrollbar. Resize to fit.

**Comment by ThomasLohnert** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/290
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/290

To add sample stack params in config (assuming `HEIGHT` and `PHI` should be relative to current beam path):
```
# Sample  # x translation 0305, y height 0306 (only one height like crisp), phi 0307, psi 0308
sample_comp = add_component(TiltingComponent("sample", PositionAndAngle(0.0, z_sample, 90)))
add_parameter(TrackingPosition("SampOffset", sample_comp, autosave=False))
add_parameter(DirectParameter("SampTrans", MotorPVWrapper("MOT:MTR0305")))
add_parameter(AngleParameter("SampPhi", sample_comp, autosave=False))
add_parameter(DirectParameter("SampPsi", MotorPVWrapper("MOT:MTR0308")))
add_parameter(InBeamParameter("SampInBeam", sample_comp, autosave=False))
add_driver(DisplacementDriver(sample_comp, MotorPVWrapper("MOT:MTR0306"), out_of_beam_positions=[park_high]))
add_driver(AngleDriver(sample_comp, MotorPVWrapper("MOT:MTR0307"), 
```
