### ISSUE TITLE
Experiment Controls drop in session 13/Nov/19

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4968]
Only visitors to this were Muon scientists, two things came up.

1. Need to help muons sort their data areas (they have a manual organising process on MUSR which requires manual copying of data at the end of the cycle). Discussed and came to a resolution see Controls ticket [#663](https://github.com/ISISComputingGroup/ControlsWork/issues/663)
2. Permissions for access to move these files didn't appear to be there on the temporary loan analysis machine.  On checking, this turned out to be as simple as logging into the `musr_mgr` account to move the files which `musr` didn't have permission to move.

This can be closed when the above ticket is done (assuming that this is the end of the work from the drop in session).

**Comment by DominicOram** [comment]
@ChrisM-S it looks like the original ticket is done, can we put this into review?

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - what is the point in leaving this ticket open?  The actionable work is defined in Controls ticket [#663](https://github.com/ISISComputingGroup/ControlsWork/issues/663).  
It is now more than 12 months since the drop-in session, what value even remains in doing a review?
