### ISSUE TITLE
Support: Sample changer fail

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4969]
On LARMOR report sample changer fail after changing a position sample changer OPI no longer reports any positions.

Fix was to remove the duplicate position but adding a small offset to one position.

He is now using the sample changer,

**Comment by John-Holt-Tessella** [comment]
New ticket #4970 to create a fix

**Comment by davidkeymer** [comment]
As the sample changer was returned to an operational state and a ticket was created to fix the original problem, this ticket can be considered reviewed.
