### ISSUE TITLE
Support: LARMOR Z Stage Investigation

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4971]
Z stage on Larmor is misbehaving, it was suggested that it might have been a software limit because of inaccuracies in the motor resolution. We tracked it down to a problem in the amplifier card, using the motor encoder drift PV.

Rob is now happy and has reported it to JN.

**Comment by davidkeymer** [comment]
Problem determined to be with hardware and therefore beyond remit of computing group.

Ticket considered reviewed.
