### ISSUE TITLE
build: add distclean target

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4976]
From a recent tech-talk post it looks like "distclean" is used more often than "clean uninstall", and "clean uninstall" doesn't currently remove everything in V4 (a bug)

This ticket is to add distclean to our system - it is not currently propagated via intermediate makefiles

Acceptance criteria:

* Before merge, "make distclean" fails at some point
* After merge, "make distclean" completes (there may be some intermediate perl warnings about Path.pm being missing as it will have been removed)

**Comment by DominicOram** [comment]
I struggled to test this fully due to https://github.com/ISISComputingGroup/IBEX/issues/5017

**Comment by FreddieAkeroyd** [comment]
The #5017 issue looks to be fixed with a newer areaDetector in #5031, suspect it needs updated build rules for EPICS 7
