### ISSUE TITLE
SUPPORT:  missing MERLIN data files

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4977]
Reported by scientist, MERLIN data file 48379 is missing from archive.

**Comment by FreddieAkeroyd** [comment]
It looks like the control program encountered an error while writing the data file

2019-11-23 06:48:10  Writing nexus data file c:\data\MER48379.nxs
2019-11-23 06:48:10  Writing raw data file c:\data\MER48379.raw
2019-11-23 06:48:10  NEXUS ERROR: ERROR: attribute napimount not found

It completed writing the file, but due to the error it did not set the file as ready for archiving. This also seems to have happened with run 48385. I don’t know at the moment if there are any issues with the data in the nxs file, as the program encountered an error it has kept the raw events separately elsewhere so it is possible to “re end” at a later point. The histogram-only .raw file generated should be OK. Not sure why happened twice today and not before.

**Comment by FreddieAkeroyd** [comment]
Issue looks to be due to an error in one thread being incorrectly interpreted in another, leading to it thinking the file writing has failed when it has actually completed OK. To see this issue would require starting a new run to take place at exactly the right point during the previous run completing in the background

**Comment by FreddieAkeroyd** [comment]
Issue just report on LET too (run 67000)

**Comment by FreddieAkeroyd** [comment]
File is in c:\data and OK so just needs marking readonly to get archived

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd  - what's the outcome here?  On the face of it, this ticket appears to be resolved.  Is that true?  Is the ticket ready to be reviewed?

**Comment by FreddieAkeroyd** [comment]
Race condition will be investigated separately in isisicp code

**Comment by DominicOram** [comment]
Added a little bit more documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting#end-of-run-script-not-working-or-data-not-being-copied-to-the-archive in the meantime.
