### ISSUE TITLE
SUPPORT: web dashboard not working for IMAT

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4978]
Reported by scientist that web dashboard had not updated since 20 Nov at 14:00. Restarted json_bourne and that fixed it

**Comment by KathrynBaker** [comment]
Can verify that the web dashboard is still working at this point in time:
![image](https://user-images.githubusercontent.com/10552381/70057761-9fb6dc00-15d5-11ea-88b8-198429f40360.png)
