### ISSUE TITLE
All IOCS: error loading timezone record

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4983]
As a developer I would like to eliminate errors from IOC loads so that these errors do not confuse me in future when I try to debug a device.

All of our IOCs are giving the following error on boot:

```
Error (511,511) PV: TE:NDWRENO:CS:IOC:SIMPLE:DEVIOS:TIMEZONE devStringinEnvVar (init_record) Illegal INP parm field
```

I assume this is an EPICS 3/EPICS 7 difference.

**Comment by FreddieAkeroyd** [comment]
I think this is because the EPICS_TIMEZONE environment variable was replaced by EPICS_TZ in EPICS7

**Comment by kjwoodsISIS** [comment]
We're not using 0.5 points any longer.  1 point is the minimum size.
(The 0.5 label is retained for historical purposes only).
