### ISSUE TITLE
IMAT: unable to start MCP camera

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4984]
IMAT were unable to start the MCP camera, pixelman would crash if started with EPICS support but OK if started without EPICS support. After investigations involving the camera developer, it seems that the problem is related to the ShutterValues.txt file - The maximum number of time slices is lower than it used to be (now ~2900  previously 3100). It is unclear why this is so, the EPICS software plugin is unchanged and doesn't directly refer to this information. This change meant previously working ShutterValue.txt may no longer work. Note added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Pixelman

**Comment by davidkeymer** [comment]
1. Added link to above page from [Specific Device IOC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC) page via "Imaging Cameras" section.
1. Created new page entitled [Imaging Cameras](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Imaging-Cameras) for addition of other cameras.
1. Added breadcrumbs to both pages.
1. Tidied formatting on Pixelman wiki page.

**Comment by davidkeymer** [comment]
Checked with instrument scientists the day after and they reported that the experiment ran successfully overnight.
