### ISSUE TITLE
INTER: Add an interim mid-level to allow an encoder readback

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4985]
There is an email that I forwarded to the experiment controls inbox - need to discuss the midterm solution to decide where and how to allow for it. This interim solution is simply to use a mid-level that is not already in use elsewhere to provide the block for the encoder readback.

This requires a SECI person to be involved, and probably either DK or KB, but is probably best to undertake with someone else as there is still a while for support to be undertaken.

The long term solution is "move to IBEX", there are already easier ways to enact this solution within EPICS/IBEX

**Comment by davidkeymer** [comment]
Guided instrument scientist through process.  "Rotation Stage" mid level VI and SECI block now configured to log encoder value.

IS will ask group for bespoke VI should the need arise to record long-term diagnostic data.

**Comment by KathrynBaker** [comment]
I can confirm that there is a block with a suitable name and that it is undertaken via the VI mentioned
