### ISSUE TITLE
MUONS: Periodic Data Saving

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4988]
As a muon scientist, I need the option to save my data every N frames.

#### Acceptance Criteria
1. The DAE GUI provides an Autosave tab 
1. The Autosave Tab reproduces the functionality of the equivalent tab in the SECI DAE control panel
1. I can set the frequency (in terms of frames) of data saving.
   1. The frequency I set should be remembered between sessions
   1. The default frequency should be 2000 (i.e. every 2000 frames)

#### Notes
1. **N.B.** the "Autosave" feature of the DAE is _**entirely unrelated**_ to EPICS autosave.
1. The muon instruments use a feature of the DAE that allows them to save data every N frames.
   1. Neutron instruments tend not to use this feature (which is why we have not encountered it before).
1. Check the behaviour of the Autosave tab in SECI
1. Check the Autosave tab in SECI for sensible limits on the value of the frequency
1. If in doubt; check the behaviour with Freddie.

**Comment by Tom-Willemsen** [comment]
Ticket completed.

**Comment by kjwoodsISIS** [comment]
Feature is already implemented in IBEX.
