### ISSUE TITLE
Reflectometry: Defining position of a parameter moves motors

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4991]
As a reflectometry scientist, I would like redefining a motor position via beamline parameters to just set the position, and not effect any physical move. At the moment, there is a bug present that when passing a value into `<PARAM>:DEFINE_POSITION_AS`, it moves the underlying motor to the given value instead of redefining the motor position. 

Given an axis `MTRXXXX` being redefined to 1, monitoring `.SET` and `.VAL` reveals that occasionally the sequence of events is

```
MTRXXXX.SET SET
MTRXXXX.SET USE
MTRXXXX.VAL 1 
```
when it should be
```
MTRXXXX.SET SET
MTRXXXX.VAL 1 
MTRXXXX.SET USE
```

Which suggests that the `pv_wrapper._motor_in_set_mode` context manager is not quite working as intended.

Curiously, the bug does not seem to occur for `SlitGapPVWrapper`s.

## Acceptance Criteria
- Redefining a position never moves the underlying motor for the parameter being redefined
- The existing system tests do not seem to catch this bug, possibly because it seems to occur less after the axis being redefined has already been moved. Try to adapt the system tests to catch the bug without the fix
- Redefining the value of a reflection angle updates the readback value of parameters affected by the changed beam path, but does not trigger them to move to their last setpoint.
- Add a system test to check the readback value of subsequent parameters changes appropriately if a reflection angle gets redefined

**Comment by John-Holt-Tessella** [comment]
Pull requests:

- https://github.com/ISISComputingGroup/EPICS-refl/pull/7
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/312
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/359
