### ISSUE TITLE
genie_python: Raise an exception when the period count or period is invalid when set

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4992]
As a ZOOM/LOQ instrument scientist I would like genie_python to show me an error in the scripting window if I try to set the number of periods in the dae bigger than is allowed by its memory. I should also see an error if the period can not be set. This is so I can stop my run if this doesn't run correctly.

### Acceptance Criteria

1. An exception is thrown within change_number_soft_periods if the DAE can not set the number of periods
1. This exception is caught by genie_python and logged to the screen
1. An exception is thrown within change_period if the DAE can not set the period to the correct number.
1. This exception is caught by genie_python and logged to the screen

### Notes

- I think there is already a log message from the DAE for both of these exceptions can we get that out.
- See also #4792 
- Generated by #4964
- If you can't get the error directly from isisicp, poll the period number until it changes or raise an error on a sensible timeout

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/system_tests/pull/32
https://github.com/ISISComputingGroup/genie_python/pull/205
