### ISSUE TITLE
GUI: If Py4J server robustness

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4993]
If the py4j session can not be openeded or crashes currently there is no direct feedback to the user and they can not restart it without reopening the GUI; fix this.

### Acceptance Criteria

1. If the python script doesn't run it is restarted and user is informed of problem

~~2. If the python script crashes the Py4J session is restarted~~

~~3. The tests ../uk.ac.stfc.isis.ibex.scriptgenerator.tests run in tyco. They are currently failing~~
~~because the module can not be started without Py4J running.~~
    ~~- add these tests to the client.tyco module~~

**Comment by JamesKingWork** [comment]
This is being fixed as part of https://github.com/ISISComputingGroup/IBEX/issues/5120

**Comment by RaiBishal** [comment]
> 2. If the python script crashes the Py4J session is restarted
> 3. The tests ../uk.ac.stfc.isis.ibex.scriptgenerator.tests run in tyco. They are currently failing because the module can not be started without Py4J running.
>    
>    * add these tests to the client.tyco module

Fixed as part of #5120
