### ISSUE TITLE
HRPD: Purchase & prepare PC to host HRPD_SETUP 

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4994]
As an HRPD scientist, I would like a setup PC, so that I can prepare experiments offline.

#### Acceptance Criteria
1. New host PC purchased & delivered
1. New host PC prepared ready for IBEX to be installed
1. New host PC to be called `HRPD_SETUP`

#### Notes
1. Installation & configuration of IBEX will be done via #5788

**Comment by KathrynBaker** [comment]
Needed January 2021

**Comment by ChrisM-S** [comment]
/remind me to buy a machine in two weeks

**Comment by kjwoodsISIS** [comment]
Original text:
As a user of the scientific program on HRPD I want to be able to undertake some sample environment style experiments, such as calorimetry, using the same equipment as used on the beamline but without using the neutron beam, as such an 'offline' system would be useful.

**Acceptance Criteria**
1. `HRPD_SETUP` exists as a clone of `HRPD` without a DAE, but with the ability to run as if it were HRPD in every way

**Comment by JamesKingWork** [comment]
Putting as training to placate project board checks

**Comment by ChrisM-S** [comment]
New PCs ordered and budget approved.

/remind me on Monday at 9:45 to check that the orders have gone through FIT. (nice bot please work...)

**Comment by ChrisM-S** [comment]
Ok,
/dontremindme if you are broken, I will talk to the outlook bot instead 😞

**Comment by DominicOram** [comment]
As part of this ticket we should have a discussion about whether this machine should be windows 7 or windows 10

**Comment by ChrisM-S** [comment]
PC is delivered & ready to be set up with Host OS.

**Comment by John-Holt-Tessella** [comment]
Review:

- Machine looks good
- [ ] need an HRPD_setup in stag deleted for storing database backups
- [ ] check that HRPD_setup is on list of systems we look after
- [X] Update DAE to DAE2 so it can run in simulation mode (I have done this)
