### ISSUE TITLE
4918-2: SANS-DLS Implement saving to vendor format

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4999]
As an instrument scientist using the sans-DLS I want my data to be available in the file format which will be most useful to my users.

Ticket #4918 implements a simple CSV file format as a placeholder until we have a better understanding of what the users need. This ticket is to implement a file format for the data we receive from the equipment which is tailored to the users needs. This ticket will be updated after #4935 has been completed with the requirements/acceptance criteria

Acceptance criteria:
- Write out the data in a format that the vendor's analysis software can read
- Ensure repo has no unneeded branches or pull requests

**Comment by John-Holt-Tessella** [comment]
review after DL rework done

**Comment by Alistair-McGann-Tessella** [comment]
Pull requests:
OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1088
support module: https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/3
IOC Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/308
