### ISSUE TITLE
SUPPORT: HRPD: various issues

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5001]
(1) scripting console sometimes not printing output of commands.
(2) Following error appeared in their script:

```
Traceback (most recent call last):
File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", 
line 776, in end
__api.dae.end_run()
File "C:\Instrument\Apps\Python\lib\site-
packages\genie_python\genie_dae.py", line 126, in _wrapper
raise ValueError(e_string)
ValueError: end_run can only be run in the following runstates: RUNNING, 
VETOING, WAITING, PAUSED
```

(3) script output with various errors - see footprints 14597

**Comment by Tom-Willemsen** [comment]
Initial investigation:
(1) is another symptom of https://github.com/ISISComputingGroup/IBEX/issues/4736 . I confirmed that the latest client does not have this issue
(2) was a duplicated `g.end()` command in their script, i.e. something like:

```
def do_run():
    g.begin()
    ...
    g.end()
    g.end()
```

(3) the script starts with a `g.abort()` which implies the instrument needs to be running when the script is started. From the error trace provided it looks like the instrument may not have been running. Have asked for confirmation from the scientist.

**Comment by DominicOram** [comment]
👍
