### ISSUE TITLE
SURF: Improvements for acceptance tests

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5002]
Feedback from acceptance tests

### Reflectometry IOC

1. Readback is sluggish #5025
1. Is footprint calc using radians not degrees "looks off" #5092 
1. In beam parameter does not cause mirror to move if offset is not in the mode #5095
1. Think about what happens if switching disabled mode during move #5094 
1. PD IN Beam parameter moved the sample in beam (click PD in beam physically moves the sample in and out, sample parameters not in mode): Not reproducable retry on SURF in maintenance
1. Readbacks were off in server before restart look at logs see if there is any info. Whole server needed to be restarted not just refl server: Not reproducable retry on SURF in maintenance

### Scripts #5282 

1. Abort transmission does not exit after ctr+c and end (exception is not rethrown)
1. why plots on surf going to c: not u:
1. ctrl + c in start of scan need to abort run
1. Legend on graphs needs to be at top not obscuring graph
1. Print fit after scan (even if the parameter is capture)
1. Why is run script waiting on dry run
1. After overnight run seems that horizontal slits did not reset (problem in transmission?)
1. Matplot lib didn't seem to plot last point of scan

### EPICS

1. Jasco Pump OPI: add label for status, e.g. running/Off not just light #5093
1. Motor off deadband got set to 0 (Y Samp I think) see #5008
1. Motor energise was 0 (Slit 3 Height) see #5008
1. Dash board is not working (On update this will be installed correctly)
1. Journal view is not working (On update this will be installed correctly)

### Config

1. Tolerances for incorrect parameters need to be increased on SURF for at least S2offset, Samp Offset, S3 offset and VB Offset. #5309

### Ideas

1. Idea: setting multiple blocks from cset

**Comment by DominicOram** [comment]
Did you want to keep this as an umbrella ticket for surf work or is it effectively now covered by all the other tickets?

**Comment by John-Holt-Tessella** [comment]
Let us close it

**Comment by John-Holt-Tessella** [comment]
Fixed because created other tickets
