### ISSUE TITLE
GUI: Alarms view improvments

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5005]
Collect feedback on the alarms view and implement plan.

See #4707 for email sent to instrument scientists asking for feedback.

### Acceptance Criteria

- Emails responses collected and colated
- Plan for the alarm view made
- Tickets written for alarm view

**Comment by Tom-Willemsen** [comment]
superceded by later work e.g. https://github.com/ISISComputingGroup/IBEX/issues/8422 among others
