### ISSUE TITLE
WISH: Connect and configure Pressure Cell Controller and associated equipment

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5006]
WISH instrument scientists required assistance connecting the Pressure Cell Controller (usually used on PEARL), a needle valve and rotation stage.  PEARL instrument scientists were also present to offer help and advice on operating the equipment.

This collection of devices had been previously used on WISH a couple of years ago, and so the sub-configurations and configurations (`WISH Base + Pressure Controller.conf`) were already present on the control machine.  The original COM ports used were determined from the VI settings and subsequently connected to.

An update from SourceSafe was required to the cell controller VI (as there had been changes to the hardware since it was last used).  This then communicated successfully with the hardware and allowed full remote control.

The needle valve was controlled by a "spare" Galil axis (0403) and again already had the settings required.  The cable coming up from the ground floor just needed to be connected to the motor and encoder.

The rotation stage is as used on a standard CCR (and was already configured in the Mclennan PM600 VI).  However, it was not required to be remotely controlled and only aligned by hand using the controller's physical jog buttons.  The axis was set to open loop mode (using command `1CM11` via HyperTerminal to avoid changing permanent settings) so that a tracking abort would not be generated while jogging.  No further configuration on the control machine was performed for this device.

Temperature sensors and heaters were also connected, but this was performed by support staff and the Eurotherm VI configured by instrument scientists.

**Comment by DominicOram** [comment]
Sounds run of the mill, I don't think there's anything here we could learn for IBEX.
