### ISSUE TITLE
EMU: Control over Galil Slits

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5009]
As an instrument scientist on EMU I want to maintain my control over the slits for my beamline once I have converted to IBEX before the Beckhoff solution is integrated.

**Acceptance Criteria**
1. I can create blocks that will control my beamline slits
1. I have an OPI which allows me to view both the position and voltage settings being used, as on the VI

**Notes**
1. This should be done via LVDCOM for simplicity and speed
1. These slits are very non-standard at present
1. The VI currently has one control to set the desired position - this is in mm
1. The VI has one major indicator - the current position in mm, and 2 minor indicators - the returned voltage from a potentiometer that is used as the encoder equivalent, and the voltage that is being used to control the setting of the position

**Comment by kjwoodsISIS** [comment]
@KathrynBaker - could you add a screenshot of the VI.

**Comment by KathrynBaker** [comment]
Not without running it, as the secondary values are usually hidden, it is probably quicker and easier in cycle for me to generate a mock of what the code normally looks like

**Comment by kjwoodsISIS** [comment]
OK.

**Comment by KathrynBaker** [comment]
One mocked up image of how the slits usually look

![image](https://user-images.githubusercontent.com/10552381/70250931-93b65000-1776-11ea-8c05-aa54cb83890c.png)

**Comment by KathrynBaker** [comment]
Please note, number of points to assign was discussed in the office and agreed by @KathrynBaker, @John-Holt-Tessella, and @Tom-Willemsen

**Comment by davidkeymer** [comment]
Screenshot of VI running on EMU (captured during VNC connection):

![image](https://user-images.githubusercontent.com/10550207/70536831-5d524980-1b57-11ea-9241-fbccf4a010ec.png)

**Comment by davidkeymer** [comment]
Pull requests:

[EPICS top](https://github.com/ISISComputingGroup/EPICS/pull/196)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/450)
[ISIS support modules](https://github.com/ISISComputingGroup/EPICS-MuonJaws/pull/1)
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/1006)
