### ISSUE TITLE
HIFI: Connect and configure Triton dilution fridge and associated equipment

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5010]
HIFI instrument scientist and cryogenic support staff required assistance connecting and configuring a Triton dilution fridge (uDR3), a Lakeshore 372 and two Mercury ITCs.

This experiment/test was a replica (as far as software is concerned) of the one performed on EMU recently (see ticket #4937).  Therefore the configurations and sub-configurations created then were copied to HIFI to save time and effort.  The individual devices were connected and configured accordingly.

Due to a lack of (working) RJ45 sockets on the beamline, an Ethernet switch was used for the Triton control computer and the Lakeshore 372.  Initially, a non-functioning switch was installed which caused much discombobulation as it appeared to work with both devices, however the Triton would drop its connection occasionally but the Lakeshore seemed fine.

Once this switch was replaced, all was well and the system was left in a state for the tests to proceed.

**Comment by davidkeymer** [comment]
Once we have confirmation that the instrument scientist has successfully controlled the equipment via SECI blocks, this ticket can be reviewed.

**Comment by JamesKingWork** [comment]
Associated calibration file from emu as muon_temperatures.tpar to allow calibration of PID values and heater range. These calibration values are used in the SETTEMP procedure in the hifi_routines.gcl file.
