### ISSUE TITLE
Spike: Automatically run scripts on loading a Config

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5012]
As an instrument scientist, I would like to the ability to automatically load and launch a defined script when I change config, so that I can tailor the IBEX environment for users.

#### Acceptance Criteria
1. I can add the name of an "autoload" script to a config. 
1. On loading a config:
   1. if an "autoload" script is defined, the script is executed before the config loading process completes.
   1. if an "autoload" script is not defined, the config loading process completes as normal.

#### Notes
1. This issue was raised in a discussion with the EMU scientists.  This is a feature of SECI that the muons group uses frequently.  Other groups might also find it useful.
   * The muons group often uses "autoload" to setup a scripting window and a graph window for users.
1. This ticket implies adding a field to a config; the field will point to a script to be executed after the config has loaded.  If no script is defined, then the config will simply load as normal.
1. If "autoload" is not a good name, we can call this feature "auto-execute" or "auto-run" or "auto-launch" ...

**Comment by Tom-Willemsen** [comment]
This may be better implemented as "on console start" as opposed to "on config load". Otherwise the graph that the muons want may be created in the wrong perspective.

**Comment by kjwoodsISIS** [comment]
Yes, perhaps.  But the muons definitely want to associate the script with the config.  If your next run requires you to load a new config, I think they will expect to have the script associated with the new config executed automatically.

**Comment by John-Holt-Tessella** [comment]
We need to be careful here. There is a difference between changing the GUI and doing something to the instrument. I think we need to understand their use cases better. Changing config is an instrument change. The GUI would need to configure itself based on a config change. This needs some higher level thought. (people in a room). Make this an investigation/spike ticket?

**Comment by kjwoodsISIS** [comment]
Yes, that's fine.  It would be good to have someone who knows what SECI actually does.

**Comment by Tom-Willemsen** [comment]
After meeting, we have decided that this ticket is superceded by https://github.com/ISISComputingGroup/IBEX/issues/5015

**Comment by KathrynBaker** [comment]
I appreciate this is closed, but can you please record who attended the meeting and made the decision - more so that we can document who made it and when - possibly even with why #5015 is the answer...
