### ISSUE TITLE
AreaDetector: `make uninstall` should not be so agressive

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5017]
As a developer I would like to be able to run `make uninstall` without producing errors. In the `areaDetector` submodule if I run `make uninstall` on the top it deletes `ADCore/configure/` as part of uninstalling `ADPluginEdge`. This causes the uninstall to later fail. It should not delete these files.

**Comment by FreddieAkeroyd** [comment]
This looks to be fixed by #5031

**Comment by DominicOram** [comment]
Indeed it is.
