### ISSUE TITLE
Reflectometry: Support Acceptance Tests on SURF

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5019]
Run acceptance tests for a fringey sample using a super mirror to treat it as a liquid sample.

### Acceptance Criteria

1. SURF is setup for the tests with the latest release of IBEX patched with the latest version of  inst_servers. This implies:
    - installing python3
    - upgrading configs
1. Update to the latest instrument scripts
1. Run tests in SECI and IBEX (scripts will need writing)
1. Capture improvements that need/could be made to the system

**Comment by John-Holt-Tessella** [comment]
Comments capture in #5002

**Comment by DominicOram** [comment]
I am assuming #5002 contains all comments that were made but it reads like a list of notes to yourself and isn't a proper ticket. Can you split it out into more actionable tickets where appropriate and improve the wording.

**Comment by DominicOram** [comment]
Wording of #5002 is better, thank you.
