### ISSUE TITLE
Support: Document what to do on stuck DAE

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5024]
We have had issues on multiple instruments with the DAE becoming unresponsive seemingly at random with messages in the DAE log of the form 

```
2017-04-13 20:52:14  NIVISA: Error "Could not perform operation because of I/O error." (code 0xbfff003e) returned from "viMoveIn32"  while transferring 1001 items at VME address 0x18000fa4
2017-04-13 20:52:15  NIVISA: Error "Could not perform operation because of I/O error." (code 0xbfff003e) returned from "viMoveIn32"  while transferring 1001 items at VME address 0x18000fa4
2017-04-13 20:52:16  NIVISA: Error "Could not perform operation because of I/O error." (code 0xbfff003e) returned from "viMoveIn32"  while transferring 1001 items at VME address 0x18000fa4
2017-04-13 20:52:17  (0) NIVisa: [Warning] (NIVisa::retryBlock) retryBlock: 1001 items from address 0x18000fa4
2017-04-13 20:52:17  (0) NIVisa: [Information] (NIVisa::reinit) Calling NIVisa::reinit()
2017-04-13 20:52:17  Calling NIVisa::reinit()
2017-04-13 20:52:17  Endian workaround DISABLED, blocks transfers DISABLED
2017-04-13 20:52:17  This is a VXI DAE
```

(See https://github.com/ISISComputingGroup/IBEX/issues/5023, https://github.com/ISISComputingGroup/IBEX/issues/4851)

The currently known solution is to powercycle the DAE. We should investigate a proper fix for this issue.

### Acceptance Criteria:

- Document fault 
    - determine when the issue requires intervention from the DAE electronics team
    - how to report the problem

**Comment by KathrynBaker** [comment]
It is worth noting that *we* might not be able to find or fix the situation – if that error is coming from the VME crate then we aren’t in a position to do any more than report it, and the fix would need to be undertaken by the DAE development team. Do we have a procedure for reporting these kind of incidents to that team? If not, has anyone mentioned the ongoing issues to them?

**Comment by kjwoodsISIS** [comment]
Our documentation for troubleshooting the DAE should describe how to 
(a) determine when the issue requires intervention from the DAE electronics team
(b) how to report the problem

**Comment by John-Holt-Tessella** [comment]
Document on `Wiki > Trouble-shooting > DAE` (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting)

Currently does nto answer either of the above questions

**Comment by ChrisM-S** [comment]
can I also add:
(c) Use of basic diagnostics which can get some issues solved and/or give a better idea of the problem to report to Electronics (wd2t, Dae tester VI, ECC, VISA/VXI software on host via RDP for DAEII and useful quixstearm routines for DAEIII (e.g. reset the network I/F).
(d) A link to sharepoint with details of support hours/who to call (when) and useful mobiles. This extends beyond DAE really - there may be things I'm forgetting which already exist - but I would be lost without my phone currently.

**Comment by FreddieAkeroyd** [comment]
As @KathrynBaker mentioned, if there are "NIVISA:" errors then they are an issue with the DAE or national instruments layer and may ultimately need a DAE power cycle or reporting to electronics. I have details of how we should report an issue to electronics we have fixed (so they can monitor faults) and also how to contact them, but it probably can;t all go on a public wiki. We may need to think about which way round we do our support related pages i.e. could sharepoint with links to wiki have some advantages over wiki with links to sharepoint?

**Comment by DominicOram** [comment]
Added link on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting#dae-switches-from-processing-to-unknown-and-never-goes-into-setup--run-can-not-be-ended for how to contact electronics
