### ISSUE TITLE
POLARIS: Investigate a potential ignoring of an error by IBEX from the Rotating Sample Changer

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5027]
As an instrument scientist on POLARIS, I want to know why IBEX thought a sample was in the beam when the Maclennan crate was displaying an error.

**Acceptance Criteria**
1. There is an explanation as to what happened in the comments of this ticket
1. Any tickets needed to avoid this situation occurring again in the future are created

**Notes**
1. The first comment contains the content of a Footprints that was submitted to motion control
1. This may be related to #4287, at least as far as methods of resolving it go
1. #2173 was the ticket that created this code and has some potentially useful information

**Comment by KathrynBaker** [comment]
The Polaris sample changer Maclennan control crate indicated an error -
position 3 requested, but the sample had failed to lower. However, the
Move_Finished block indicated "1" (i.e. it though the move has been successful)
and started the next run with no sample in the beam.

**Comment by Tom-Willemsen** [comment]
As discussed in planning meeting: I have merged the relevant information from this ticket into https://github.com/ISISComputingGroup/IBEX/issues/4287 as we feel they are probably the same issue.
