### ISSUE TITLE
LET: Configure and test SKF G5 IOC & OPI for chopper 5 (FROM 24/01/2020)

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5033]
LET's SKF G5 (ex Astrium) chopper 5 will have been installed by 24/01/2020 (according to project plan).  An additional IOC and OPI will need to be configured to communicate with it, as well as IBEX configuration(s) edited.

#### Notes
- Check that there are enough IOCs built (4 required in total), bearing in mind that chopper 1 will be replaced by an SKF G5 in the Summer.
- Two IOCs are already running for choppers 3 & 4, and so it should be straightforward to configure one more.

**Comment by John-Holt-Tessella** [comment]
Is this the SKFMB350? If so there are only 2 instance at the moment

**Comment by davidkeymer** [comment]
Some difficulty was experienced in communicating with the two new controllers (each controlling a single disk of the existing double-disk chopper) on the instrument's private network until it was discovered that the address range being used conflicted with that allocated to the DAE group, even though the existing devices in this range connected successfully.  This was remedied by changing the addresses of _all_ devices in the DAE range to move them into the Computing Group's range, and editing the IOC macros accordingly.

Two additional IOCs were added to the instrument's base component and configured for the two new controllers.  The SKF G5 OPI had a sufficient number to tabs to accommodate them, and so its macros were edited on the device screens and synoptic perspectives to suit.

Various basic checks were then carried out, including stopping, starting, parking open and closed, running to frequency setpoints and synchronising to requested phases within a specified tolerance ("phase error").  All passed successfully for both controllers and disks.

Some questions still remain over the chopper veto system, so some further investigation will be performed imminently to check wiring, signals, connections and software configuration for all controllers.

Instrument scientists will now continue with beamline commissioning using runcontrol instead of hardware vetos where and when required.

**Comment by Kevin-Woods-Tessella** [comment]
@davidkeymer  - what do you mean by "_Some questions still remain over the chopper veto system..._"?  Who will be performing the checks you list?  The chopper group, or us?

**Comment by John-Holt-Tessella** [comment]
Rework for:

- [ ] answer Kevin question 
- [ ] add trouble shooting of address range to chopper page or somewhere better on dev wiki
- [ ] also consider adding commissioning tests to mk3chopper page.

**Comment by davidkeymer** [comment]
> @davidkeymer  - what do you mean by "Some questions still remain over the chopper veto system..."?  Who will be performing the checks you list?  The chopper group, or us?

Sorry @Kevin-Woods-Tessella, I forgot to say that this work is being done by the electrical and chopper groups.  We may be asked by instrument scientists to configure the vetoes on the DAE perspective, and then check that data collection is halted when a signal is received from a chopper controller.

**Comment by Kevin-Woods-Tessella** [comment]
@davidkeymer  - OK.  Thanks for the clarification.

**Comment by davidkeymer** [comment]
- [Ticket](https://github.com/ISISComputingGroup/IBEX/issues/5406) created for meeting to discuss networking options.  Link on ticket to further information in `ControlsWork` previously considered.  This ticket has been updated with recent email conversation.
- [Wiki Page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SKF-MB4150g5-Disk-Chopper-Controllers) created detailing current installations and addressing schema.
- Commissioning tests for all choppers simply consist of confirming various demand frequencies and phases are achieved, as well as _Stop_, _Start_ (and _Park_ if available) functions are successful.
