### ISSUE TITLE
GEM: ITC503/ILM is not communicating

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5034]
GEM had connected their ITC503 and ILM but the driver on IBEX was not responding. I checked the driver log and the ITC503 COM5 port was reporting that access was denied. After checking all other components, no others were using COM5, so it looked like the MOXA was holding this COM port. I checked the COM to 16 for the ITC503 driver and plugged in the device to PORT12 on the MOXA. This solved the ITC503 issue. The ILM was not connected to anything, and instead the ISOBUS switch was connected, I connected the ILM to ISOBUS PORT 2 and the driver began communicating.

- Changed ITC503 to COM16 and plugging in device physically to MOXA PORT16
- Connected ILM to ISOBUS PORT 2
- Confirmed readbacks from the ILM worked and performed a test temperature ramp on the ITC503

**Comment by DominicOram** [comment]
Sounds pretty standard
