### ISSUE TITLE
SUPPORT: Triton on OSIRS

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5035]
Set up a Triton on OSIRIS.

**Comment by John-Holt-Tessella** [comment]
Just needed IP address changing because it is a different Tirton.

Temps were not reading because they were not configured. Email sent to CL.

**Comment by DominicOram** [comment]
As discussed, please add some documentation to the wiki to guide people on:
* How to know temperatures are not configured correctly
* How to reconfigure them (if this is our job?)

**Comment by DominicOram** [comment]
Documentation better now, thanks
