### ISSUE TITLE
SANDALS: Set run control defaults

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5040]
The instrument scientist wanted to set run control defaults, such that between configuration changes these would persist.

- VNC'd to the NDX machine and showed the user how to enable run-control on a block such that it creates a default no matter what configuration
- Advised the user that if setting a run control via the menu, then this would override that value until a configuration reload

**Comment by DominicOram** [comment]
Can you make sure this is documented in the [user manual](https://github.com/ISISComputingGroup/ibex_user_manual)? Particularly how the run control set in the menu interacts with that set on configurations

**Comment by aaron-long** [comment]
Added/modified documentation in the user manual:

- https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Create-And-Manage-Configurations#blocks-tab
- https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Menu-Bar#run-control-menu

**Comment by DominicOram** [comment]
Much better, thanks @aaron-long
