### ISSUE TITLE
EMU:  Changes to Danfysik OPI & IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5042]
As a muon scientist, I need some changes to the existing Danfysik OPI & IOC for operation on EMU.

#### Acceptance Criteria
1. The OPI should display the magnet name in its title field.
1. The OPI could display a DAC1 Slew field:
   1. If the DAC1 Slew feature is present in hardware, the DAC1 Slew field should be displayed and active
   1. If the DAC1 Slew feature is not present in hardware, the DAC1 Slew field should not be displayed and should be inactive
1. The OPI Off button should invoke the Danfysik's "sweep to zero and turn off" feature
1. The OPI should provide an Auto On/Off feature:
   1. If the user sets the field to zero:
      1. If the PSU is powered on and Auto Off is selected, the Danfysik should be powered off (via the "sweep to zero and turn off" feature).
      1. Otherwise, do nothing.
   1. If the user sets the field to a non-zero value:
      1. If the PSU is powered off and Auto On is selected, the Danfysik should be powered on and the voltage & current increased to generate the desired field.
      1. Otherwise, do nothing.
1. The Danfysik OPI for EMU contains the following fields
   1. magnetic field set-point
   1. magnetic field set-point readback
   1. magnetic field read-back (i.e. "field now") 
1. The units of the magnetic field are in Gauss
1. The OPI should display a "Field Ready" LED to show the status of the magnetic field:
   1. the LED should be OFF when the magnetic field is ramping.
   1. the LED should be ON when the magnetic field has reached its set-point.
1. The OPI should display a "progress bar" to show the field as a % of full-scale (see notes below).
1. The OPI should provide a remote/local toggle to switch between remote & local modes of operation.
1. The OPI should provide a STOP button:
   1. On pressing the STOP button, the IOC should immediately "sweep to zero and turn off" the PSU (see notes below).

#### Notes
1. The OPI needs to display the same information as the existing Longitudinal field (Danfysik) VI.
1. The existing Danfysik VI is located here: `C:\LabVIEW Modules\Muon Magnets\Danfysik\danfysik controller.vi`
1. the screenshot below shows the current VI (`danfysik controller.vi`)
![Danfysik_Controller_VI](https://user-images.githubusercontent.com/7249337/71012760-82126800-20e7-11ea-9615-01494026c4eb.png)
1. The current/voltage gauges on the VI do not need to be reproduced on the OPI.
1. In SECI, the calibration defining the relation between current and magnetic field is defined in the [`magnet.ini`](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/magnet.ini) file.
1. In SECI, the value of full-scale is set in the [`magnet.ini`](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/magnet.ini) file.  In IBEX, it could be set as a macro.
1. The Auto On/Off control need not be a check-box (as used in the VI) - a check-box is ambiguous in this context.  An alternative choice of control could be clearer.
1. Need to determine what the STOP button in the VI does.  The IOC should do the same thing.

**Comment by John-Holt-Tessella** [comment]
Current has a field set via a calibration file can this ticket be closed?

![image](https://user-images.githubusercontent.com/7570055/70982621-35129f80-20af-11ea-9236-008da7dee3d8.png)

**Comment by KathrynBaker** [comment]
Some notes to aid with pointing, plus some bits that may need clarifying from the acceptance criteria:

1. Not currently a concept in the system as far as I can tell, would need adding, most likely as a macro
2. Slew already in there and should work like this
3. The Off button in the VI just sends an "F" to the Danfysik, as per the `powersp` section in the Protocol file
4. Would need implementing in the IOC
5. and 6. Should already be handled via the sections relating to the `calib` in the existing db, protocol and OPI
7. Would need implementing in the IOC
8. Would need implementing in the IOC
9. REM/LOC is in the protocol (`cmd`), needs adding to the OPI
10. How does this differ to `Off`? The `STOP` button on the VI actually stopped the VI from running. Should it exist and stop the IOC?

**Comment by ThomasLohnert** [comment]
PRs:
- [ ] https://github.com/ISISComputingGroup/EPICS-ioc/pull/460
- [ ] https://github.com/ISISComputingGroup/ibex_gui/pull/1017
- [ ] https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/284

Some notes on select points, please let me know if I got something wrong:

>1. The OPI should display the magnet name in its title field.

It already does this, the OPI `$(NAME)` macro is set via the synoptic target / device screen name

> 3. The OPI Off button should invoke the Danfysik's "sweep to zero and turn off" feature

The "off" button and the "sweep to 0 and turn off" button are two separate things. I have left the "off" button unchanged (it just turns power off) and added a "sweep ..." button which recreates the SECI functionality, i.e. when pressed enable `auto on/off` and set the field/current setpoint to 0. Once the RBV gets there, the device turns off automatically.

>5. The Danfysik OPI for EMU contains the following fields
>   1. magnetic field set-point
>   1. magnetic field set-point readback
>   1. magnetic field read-back (i.e. "field now") 

This was already there other than the SP RBV. Instrument scientists said they do not need it, the IBEX convention of having just one SP field & press enter to apply is fine

> 6. The units of the magnetic field are in Gauss

Already implemented (units can be chosen from drop down menu)

> 10. The OPI should provide a STOP button:
>   1. On pressing the STOP button, the IOC should immediately "sweep to zero and turn off" the PSU (see notes below).

This is referencing the "STOP" button on the VI, which simply stops the VI running. I do not believe this applies to IBEX.

**Comment by ThomasLohnert** [comment]
Reworked to fix issues found during commissioning. 
- Use `CURR` instead of `RAW` for stability  tolerance
- Set a non-zero default stability tolerance
- Add macro for auto-off tolerance
- Do not process `RAW:SP` on startup (was being set to 0 on each IOC restart)
- Add protocol command & records for `RAW`, `CURR` and `FIELD`  setpoint readback values (+ relevant OPI widgets)
- Correctly scale `RAW` value for `RAW:PERCENT` record used for the progress bar
- Fix Auto on/off - spikes on the real device sent it into a continuous cycle of turning on and off. Now takes stability PV into account
- Fix `FIELD:PRECALIB` being calculated incorrectly (was multiplying when it should be dividing by scale factor)

Added PR: 
https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/13

**Comment by KathrynBaker** [comment]
Given that these IOCs are used elsewhere, with calibrations I believe (LARMOR and the Muon Front End), is it a case of changing the maths, or should the scaling factor be inverted?

**Comment by Tom-Willemsen** [comment]
We had a look and the only other instrument to use calibrated danfysiks is LOQ.

As noted in [this ticket](https://github.com/ISISComputingGroup/IBEX/issues/4355), when LOQ ran this magnet, they did so with a patched version of the danfysik (because we weren't able to get scaling to work properly with the existing DB).

I think the scaling factor issue is that, when we attempted to "generalise" the hotfix from the instrument, we got the maths wrong. Our IOC tests did not notice because they have a scaling factor of 1.

**We should write an ioc test with scaling factors not equal to 1 and ensure that the scaling logic works properly.**

**Comment by kjwoodsISIS** [comment]
I seem to recall that there was previous scaling problem with Danfysik PSUs and LARMOR (which caused the device to be set to provide a very large, and potentially unsafe, current).  The previous issue may or may not be related to the current ticket, but we should take care to get the scaling factor right and to test it on hardware.

**Comment by kjwoodsISIS** [comment]
@ThomasLohnert :
Regarding the "Off" and "Sweep to zero and turn off" buttons, my conversations with the scientists indicate that their understanding is the "Off" button performs a "Sweep to zero and turn off", rather than an immediate "Off".  I appreciate that the VI performs an immediate "Off", but how do we know that is correct?  - it is an entirely undocumented VI.  I will ask the scientists.

**Comment by Tom-Willemsen** [comment]
Merged PRs so that they can be built into the release, but putting into rework until:
- tests mentioned in my comment above are written
- @kjwoodsISIS gets confirmation from the scientist about the behaviour of the off button.

**Comment by kjwoodsISIS** [comment]
Clarification from Steve Cottrell:
> Hi Kevin,
>
> It is kinder to the supply (and the magnet!) to ramp down the current before turning 
> off, but it seems to do it no harm to turn the output off even at high current (this 
> is possible from the front panel of the supply). It would be fine to leave things as 
> they are, with the two options for turning off … very few users will interact directly 
> with the IOC, instead using ‘setmag 0’ command from the script window.
>
> Steve
>
Steve has confirmed that it is OK (although not ideal) for the Off button to simply turn off the Danfysik even at high current.  Since most users will use the `setmag()` script to control the PSU, the risk is greatly reduced (in the sense that it is much less likely to occur).

**Comment by ThomasLohnert** [comment]
PRs fixing scaling issue for `CURR` and adding tests mentioned above:
https://github.com/ISISComputingGroup/EPICS-ioc/pull/465
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/286
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/62
