### ISSUE TITLE
EMU: Changes to the TDK Lambda Genesys OPI & IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5043]
As a muon scientist, I need some changes to the existing TDK Lambda Genesys OPI & IOC for operation on EMU.

#### Acceptance Criteria
1. The OPI should display the magnet name in its title field.
1. The OPI should provide an Off button:
   1. On pressing the Off button, the IOC should "sweep to zero and turn off" the PSU (see notes below)
1. The TDK Lambda Genesys OPI for EMU should contain the following fields
   1. magnetic field set-point
   1. magnetic field set-point readback
   1. magnetic field read-back (i.e. "field now") 
1. The units of the magnetic field are in Gauss
1. The OPI should display a "Field Ready" LED to show the status of the magnetic field:
   1. the LED should be OFF when the magnetic field is ramping.
   1. the LED should be ON when the magnetic field has reached its set-point.
1. The OPI should display a "progress bar" to show the field as a % of full-scale (see notes below).
1. ~The OPI should provide a STOP button:~
   1. ~On pressing the STOP button, the IOC should immediately "sweep to zero and turn off" the PSU (see notes below).~
1. The genesys IOC should include read and set offsets, in Amps, which are applied just after reading and just before setting the power supplies, respectively.
   1. These offsets should be adjustable via IOC macros
   1. The readback on the current on the OPI should reflect the current with the offset applied
   1. The setpoint of the current on the OPI should be adjusted by the offset before being sent to the power supply
1. The genesys IOC includes settings for maximum voltage and maximum field

#### Notes
1. Some investigation of the VI, and the settings & configuration files on EMU itself will be required, because the operation of the copy of the Transverse field VI (on NDXDEMO) is not entirely obvious.
1. The OPI needs to display the same information as the existing Transverse field (TDK Lambda Genesys) VI.
1. The existing TDK Lambda Genesys VI is located here: `C:\LabVIEW Modules\Instruments\EMU\Transverse Field Supply`
1. the screenshot below shows the current EMU Transverse field VI
![EMU_Transverse_Field_VI](https://user-images.githubusercontent.com/7249337/70919857-82443200-2019-11ea-93c7-ae7df53004af.png)
1. The current/voltage gauges on the VI do not need to be reproduced on the OPI.
1. The calibration defining the relation between current and magnetic field is defined in a .ini file in SECI
1. The OPI could be a new OPI (i.e. not the same as existing TDK Lambda Genesys OPI)
1. The TDK Lambda Genesys may or may not have a hardware "sweep to zero and turn off" feature.  We need to find out.  If there is no "sweep to zero and turn off" in hardware, we may have to implement it in software (in the IOC or as a script).
1. Need to determine what the STOP button in the VI does.  The IOC should do the same thing.

**Comment by John-Holt-Tessella** [comment]
Is there a calibration file between the current/voltage and field or is it a single number?
Can we add it to the current OPI if the pv/calibration exists rather than creating a new opi?

**Comment by kjwoodsISIS** [comment]
The calibration is in a `.ini` file in SECI.  There isn't a copy of the `.ini` file in `LabVIEW Modules`, so we'll have to get hold of a copy when cycle is over.  I don't know whether it is a table or a single value.

If the existing OPIs are suitable for use, then I would be happy to add the new fields.  We ought to think about where else the OPIs are used (maybe it is only muon instruments that are interested in the magnetic field - I suppose it depends on what you use the PSU for).

**Comment by John-Holt-Tessella** [comment]
OK, probably replicate the Danfysik version of this where the power supply can be calibrated and if it is has a calibration file. If it is a single factor then we just have two entries in the table.

**Comment by kjwoodsISIS** [comment]
The TDK Lambda Genesys OPI is the old style OPI.  We ought to update it to the new style.

**Comment by Tom-Willemsen** [comment]
I have added acceptance criteria (8) to this ticket, as I realised when migrating the scripts that we need to include custom read & set offsets on the currents.

**Comment by KathrynBaker** [comment]
With the exception of point 7 which probably doesn't differ from point 2 (`STOP` button on the VI stops the VI running - so unless we want to stop the IOC running from the OPI this is not going to achieve anything much), all of this needs to be implemented in the IOC.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/279
- https://github.com/ISISComputingGroup/EPICS-TDKLambdaGenesys/pull/4
- https://github.com/ISISComputingGroup/EPICS-utilities/pull/14
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/457
- https://github.com/ISISComputingGroup/ibex_gui/pull/1014

1. Updated OPI to standard format (which includes the device screen/synoptic name as standard)
2. This is already implemented in the IOC - no additional work required
3. Added to IOC
4. Added to IOC
5. implemented in a generic utility and added to IOC
6. Added to IOC
7. Not required - as per comment above
8. Added to IOC
9. Added to IOC
