### ISSUE TITLE
Before IBEX deployment: Update mysql dependency to 8.0.19 for all systems

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5045]
As a support person, I would like to ensure that all systems are running a current version of MySQL (by end of January would be a good deadline).  The current version is 8.0.18 which is available here https://dev.mysql.com/downloads/mysql/

**Acceptance criteria:**
1) IBEX is updated to use MySQL 8.0.19
2) Scidemo is updated with the new version of IBEX (using MySQL 8.0.19)
3) Deployments in for the new cycle use MySQL 8.0.19.

**Comment by John-Holt-Tessella** [comment]
Is there a reason this can not run in our usual update cycle? I.e. after the release we update the version of mysql?

**Comment by aaron-long** [comment]
I'm in the process of updating NDXDEMO to MySQL 8.0.15.

**Comment by DominicOram** [comment]
What's the status of this? It appears that the upgrade script refers to v8.0.17 (https://github.com/ISISComputingGroup/ibex_utils/blob/da4dfc19bece8c06b32021dba8be044f18754c7c/installation_and_upgrade/ibex_install_utils/install_tasks.py#L55) but we only have v8.0.15 on the share

**Comment by John-Holt-Tessella** [comment]
For testing can you use 8.0.18 I will try and fix the script today. It was a simple replacement where you copy the new version in and then it upgrades itself on the first startup.

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_utils/pull/51
