### ISSUE TITLE
SYSTEM TESTS: fix tests

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5048]
Modify run script to upgrade stock configurations (after copying to standard location) before running tests.

**Comment by davidkeymer** [comment]
Pull requests:

[Upgrade script](https://github.com/ISISComputingGroup/EPICS-upgrade/pull/33)
[System Tests](https://github.com/ISISComputingGroup/system_tests/pull/29)

**Comment by John-Holt-Tessella** [comment]
I am not convinced this is the way to handle this sorry. Having thought about it harder this means that any database upgrade gets applied every time, I don't think this is good. Will set up a slightly different workflow for now until you are back to discuss.
