### ISSUE TITLE
IOC system tests: investigate inconsistent motion tests

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5049]
As a developer I would like to understand why several of the IOC system tests which use motors are very inconsistent.

The inconsistency seems to be particularly bad for:
- Jaws managers
- Reflectometry
- Attocube (this may or may not be the same issue as the others - if not, create a new ticket).

Note that these test suites do pass **consistently** on developer machines, so this will need to be debugged on the build server machine. As part of the system tests standown @ChrisColeExpControl @John-Holt-Tessella and I spent several hours attempting to step through the motor record in visual studio's debugger to attempt to diagnose these issues, however we realised that this needs a much more in depth investigation (this ticket).

**Comment by ChrisM-S** [comment]
Depending on the need for real motion hardware, I can offer TESTR78 as a (variably) restricted CPU/Memory testbed.  Hopefully after its move to TESTR106 in Jan, access to at least a set of Jaws will be possible with the help of M/C group in the motion lab.

With remote debugging, it should still be possible to debug on a developer machine whilst probing the system under stress (this split could make concerns a bit easier to separate).

**Comment by FreddieAkeroyd** [comment]
The issue could be RENO itself, or it could be something about running under Jenkins. Is it worth adding another (more powerful) build node to also run the tests on and see what happens?

**Comment by ThomasLohnert** [comment]
Outdated issue, system tests are in a very different state from 4 years ago.
