### ISSUE TITLE
Beckhoff: Refactor test runner code to be generic

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5052]
As a developer (both in Controls and Motion) I would like to be confident that the Beckhoff control software stack works for all applications. Currently the tools for running the IOCTestFramework tests against the PLC code are inside the ISIS PLC code repository. They should be moved into a separate repository so that it is easier to run them against lots of different PLC applications.

**Comment by DominicOram** [comment]
Confirm that http://epics-jenkins.isis.rl.ac.uk/job/beckhoff_build_pipeline/ is running tests against the three current PLC flavours. https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff has been updated. Once https://github.com/ISISComputingGroup/BeckhoffPLCCode/pull/24 is merged we need to update https://github.com/ISISComputingGroup/BeckhoffTestRunner/blob/old_ISIS_PLC_code/.gitmodules to point to master.

**Comment by DominicOram** [comment]
Note that https://github.com/ISISComputingGroup/BeckhoffTestRunner is where all the code has now gone!

**Comment by Alistair-McGann-Tessella** [comment]
I like that this makes it much easier to add a new PLC code to the system. It looks like the testrunner is doing the correct job, although when I tried to run the dummy_PLC branch it hit a timeout.

It is somewhat complex, so I'd recommend adding some more documentation to make it easier to approach in the future. I think a guide for how to add a new branch into the pipeline would be really helpful.
This would cover all of the implementation details and 'difficult' bits like adding the PLC code as a submodule here, without needing to go into too much detail about any particular point. Users/devs should be able to look things up once they know what's going on.

**Comment by DominicOram** [comment]
Thanks. Updated docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff but happy to improve further if you think required?
