### ISSUE TITLE
attocube misbehaving

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5054]
The attocube tests were not working. On compilation of the C source code the following warnings are seen:
```
anc350motorapp\src\anc350asynmotor.c(432): warning C4133: 'function': incompatible types - from 'unsigned int *' to 'size_t *'
anc350motorapp\src\anc350asynmotor.c(509): warning C4133: 'function': incompatible types - from 'unsigned int *' to 'size_t *'
anc350motorapp\src\anc350asynmotor.c(510): warning C4133: 'function': incompatible types - from 'unsigned int *' to 'size_t *'
anc350motorapp\src\anc350asynmotor.c(432): warning C4133: 'function': incompatible types - from 'unsigned int *' to 'size_t *'
```
Such warnings indicate the code is not 64bit clean and will misbehave (they are actually an error in c++ without an explicit cast, but in C they are only a warning)

**Comment by FreddieAkeroyd** [comment]
This may be related to/fix #5049 for the attocube

**Comment by FreddieAkeroyd** [comment]
Re-enabled attocube tests and all now seem to pass on my computer (they were failing before)

**Comment by Tom-Willemsen** [comment]
Could we add compiler flags to promote these warnings to errors in our general build (to prevent this type of issue from getting through again in any other modules)? Or if that would be too restrictive, maybe we should monitor the number of compiler warnings like we do for checkstyle?
