### ISSUE TITLE
GUI: If the MCR/merc pvs are not available when viewing beam status page the GUI should not freeze

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5058]
When control service went down the GUI froze for a small amount of time (seconds) every regular interval (~30s) when viewing the beam status view; it shouldn't.

**Comment by John-Holt-Tessella** [comment]
Probably in uk.ac.stfc.isis.ibex.ui.beamstatus.views.McrNewsPanel.createPartControl where it sets off the timer. Make sure that the run is not on the GUI thread:

Suggestion is (you may not to get rid of run:

```
private TimerTask updateNews() {
        return new TimerTask() {
            @Override
            public void run() {
            	final String mcrNewsText = getMCRNewsText();
                Display.getDefault().asyncExec(new Runnable() {
                    @Override
                    public void run() {
						setText(mcrNewsText);
                    }
                });
            }
        };
    }
```

**Comment by kjwoodsISIS** [comment]
Is this ticket a proposal or is it closed?
