### ISSUE TITLE
DEPLOY: Create Release

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5060]
As a developer I want an IBEX release so I can install it on the instrument machines for the start of machine physics on 21st

Acceptance Criteria:
- genie_python should have 2 and 3 flavours. User python should be python 2.
- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)

**Comment by KathrynBaker** [comment]
According to our milestones list the release is meant to by January 21st…

**Comment by DominicOram** [comment]
Dependency ticket at: https://github.com/ISISComputingGroup/IBEX/issues/5152
To test confirm that release is there and looks good. Also confirm all actions on manual system (shares\ISIS_Experimental_Controls\system_testing) testing spreadsheet have been done, e.g. tests changed or tickets created.

**Comment by JamesKingWork** [comment]
I'm guessing this no longer relies on #5152 ?

**Comment by DominicOram** [comment]
Sorry, my wording was poor. This doesn't depend on #5152. I meant that #5152 is the ticket to update the dependencies (fulfilling the 5th acceptance criteria) and so needs to be done after this.

**Comment by JamesKingWork** [comment]
I take it that this is for release 6.0.0 and the GUI release 6.0.2 and a genie_python release 6.0.1 are patches?

**Comment by DominicOram** [comment]
Let's call it the whole 6.0.X series as I don't think we have separate tickets that cover 6.0.1 and 6.0.2. So if you could review that the documentation for those makes sense as well that would be great.

**Comment by JamesKingWork** [comment]
Are there results for the manual system tests? They don't seem to be linked on the wiki or contained in the wiki folders

**Comment by JamesKingWork** [comment]
Release 6.0.2 hasn't been added to https://github.com/ISISComputingGroup/ibex_gui/releases

**Comment by JamesKingWork** [comment]
Neither has 6.0.1 been linked here https://github.com/ISISComputingGroup/EPICS/releases

**Comment by JamesKingWork** [comment]
Did we create a release for JSON bourne? It's been converted to Python 3 as of 6.0.0 so may be worth it? I'm not sure

**Comment by JamesKingWork** [comment]
Any reason why the following haven't been updated? IRIS_SETUP, VESUVIO, RIKENFE, POLARIS, SELAB, OSIRIS, INES, NIMROD

**Comment by DominicOram** [comment]
> Are there results for the manual system tests? They don't seem to be linked on the wiki or contained in the wiki folders

Now added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests-Results

> Did we create a release for JSON bourne? It's been converted to Python 3 as of 6.0.0 so may be worth it? I'm not sure

Done at https://github.com/ISISComputingGroup/JSON_bourne/releases/tag/6.0.0

> Any reason why the following haven't been updated? IRIS_SETUP, VESUVIO, RIKENFE, POLARIS, OSIRIS, INES, NIMROD, SURF, SXD, POLREF, SANS2D

Should probably be asked on https://github.com/ISISComputingGroup/IBEX/issues/5061

**Comment by JamesKingWork** [comment]
Ok, anything on releases 6.0.1 and 6.0.2? Or do we not do that for patch releases?

> Release 6.0.2 hasn't been added to https://github.com/ISISComputingGroup/ibex_gui/releases
> Neither has 6.0.1 been linked here https://github.com/ISISComputingGroup/EPICS/releases

**Comment by John-Holt-Tessella** [comment]
Good catch, I have added 6.0.2 which I created (it is only a GUI patch). Not sure about 6.0.1
