### ISSUE TITLE
DEPLOY: Release to instruments

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5061]
Release latest version of IBEX to instruments below

* TODO: ticket #5060 should add list of instruments here* Release to all instruments

Acceptance Criteria

- Ensure that version numbers on IBEX page is up to date

**Comment by Tom-Willemsen** [comment]
ZOOM and IMAT have nagios alarms on disk space at the moment. It would be worth checking that these issues are resolved after deploying (it is likely to simply be large databases from last cycle).

**Comment by ThomasLohnert** [comment]
## Full Deployments 
#### ALF
- [ ] Started
- [ ] Completed

#### CRISP
- [ ] Started
- [ ] Completed

#### DETMON
- [ ] Started
- [ ] Completed

#### EMMA
- [ ] Started
- [ ] Completed

#### EMU
- [ ] Started
- [ ] Completed

#### ENGINX
- [ ] Started
- [ ] Completed

#### ENGINX_SETUP
- [ ] Started
- [ ] Completed

#### GEM
- [ ] Started
- [ ] Completed

#### HRPD
- [ ] Started
- [ ] Completed

#### IMAT
- [ ] Started
- [ ] Completed

#### INES
- [ ] Started
- [ ] Completed

#### IRIS (Before Tuesday)
- [ ] Started
- [ ] Completed

#### IRIS_SETUP (Before Tuesday)
- [ ] Started
- [ ] Completed

#### LARMOR
- [ ] Started
- [ ] Completed

#### LET
- [ ] Started
- [ ] Completed

#### LOQ
- [ ] Started
- [ ] Completed

#### MAPS
- [ ] Started
- [ ] Completed

#### MARI
- [ ] Started
- [ ] Completed

#### MERLIN
- [ ] Started
- [ ] Completed

#### MUONFE
- [ ] Started
- [ ] Completed

#### NIMROD
- [ ] Started
- [ ] Completed

#### OSIRIS
- [ ] Started
- [ ] Completed

#### POLARIS
- [ ] Started
- [ ] Completed

#### RIKENFE (Check Tom is done commissioning)
- [ ] Started
- [ ] Completed

#### SANDALS
- [ ] Started
- [ ] Completed

#### SELAB
- [ ] Started
- [ ] Completed

#### SOFTMAT
- [ ] Started
- [ ] Completed

#### TOSCA
- [ ] Started
- [ ] Completed

#### ZOOM (Check they are done setting up sample stack)
- [ ] Started
- [ ] Completed

## Deploy Mini-Inst

#### INTER
- [ ] Started
- [ ] Completed

#### MUSR
- [ ] Started
- [ ] Completed

#### OFFSPEC
- [ ] Started
- [ ] Completed

#### POLREF
- [ ] Started
- [ ] Completed

#### SANS2D
- [ ] Started
- [ ] Completed

#### SURF
- [ ] Started
- [ ] Completed

#### SXD
- [ ] Started
- [ ] Completed


## Configure IE only

#### CHIPIR
- [ ] Started
- [ ] Completed

#### WISH
- [ ] Started
- [ ] Completed

**Comment by ThomasLohnert** [comment]
Issues encountered during running the upgrade script:

#### Deleting backups fails

The upgrade script often fails to remove some of the backup folders. The script will tell you this - just delete it manually, then continue with the script

#### MYSQL install fails 

Sometimes, the script will fall over while updating to the latest version of mysql. It can then happen that when you retry the task, the script thinks it already is on the latest version and skips the upgrade step.

To work around this, you need to edit the install script and comment out the bit that skips the upgrade:
- Copy `<share>\ibex_utils\installation_and_upgrade` somewhere locally onto the NDX machine
- in `\installation_and_upgrade\install_utils\install_tasks.py`, in the method `install_mysql`, comment out the following lines:
```
            if MYSQL_LATEST_VERSION in version and not force:
                print("MySQL already on latest version ({}) - nothing to do.".format(MYSQL_LATEST_VERSION))
                return
```
- Re-run the deploy script in the local directory (you can skip all the steps you have previously completed)

#### IBEX Server does not automatically start

- After the deploy is finished (after the step "Reapply Hotfixes"), the script should automatically start up the IBEX server before going into the last section of manual server/client tests. This does not work properly, you will have to run `start_ibex_server.bat` manually. This may also close your upgrade script, just re-run it. Again, you can skip all steps you have previously completed.

**Comment by aaron-long** [comment]
Instruments using LINMOT motor controllers require the hotfix [#5163]. 

Without the hotfix the controller will not correctly initiate and motor records will go into major alarm.

**Comment by JamesKingWork** [comment]
Any reason why the following haven't been updated? IRIS_SETUP, VESUVIO, RIKENFE, POLARIS, OSIRIS, INES, NIMROD, SURF, SXD, POLREF, SANS2D

**Comment by Tom-Willemsen** [comment]
Polaris, Ines, Nimrod and Osiris all look updated according to the version PV. How are you checking them?

```
c:\Instrument\Apps\tools>caget IN:POLARIS:CS:VERSION:SVN:REV IN:OSIRIS:CS:VERSION:SVN:REV IN:NIMROD:CS:VERSION:SVN:REV IN:INES:CS:VERSION:SVN:REV
IN:POLARIS:CS:VERSION:SVN:REV  6.0.0.465df1d
IN:OSIRIS:CS:VERSION:SVN:REV   6.0.0.465df1d
IN:NIMROD:CS:VERSION:SVN:REV   6.0.0.465df1d
IN:INES:CS:VERSION:SVN:REV     6.0.0.465df1d
```

**Comment by JamesKingWork** [comment]
> 
> 
> Polaris, Ines, Nimrod and Osiris all look updated according to the version PV. How are you checking them?
> 
> ```
> c:\Instrument\Apps\tools>caget IN:POLARIS:CS:VERSION:SVN:REV IN:OSIRIS:CS:VERSION:SVN:REV IN:NIMROD:CS:VERSION:SVN:REV IN:INES:CS:VERSION:SVN:REV
> IN:POLARIS:CS:VERSION:SVN:REV  6.0.0.465df1d
> IN:OSIRIS:CS:VERSION:SVN:REV   6.0.0.465df1d
> IN:NIMROD:CS:VERSION:SVN:REV   6.0.0.465df1d
> IN:INES:CS:VERSION:SVN:REV     6.0.0.465df1d
> ```

I was just checking, the instrument columns https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information I will update that info though

**Comment by JamesKingWork** [comment]
> ZOOM and IMAT have nagios alarms on disk space at the moment. It would be worth checking that these issues are resolved after deploying (it is likely to simply be large databases from last cycle).

There are no longer Nagios warnings on disk space.

**Comment by JamesKingWork** [comment]
Any reason RIKENFE and SELAB haven't been deployed to

```
C:\Instrument\Apps\EPICS>caget IN:SELAB:CS:VERSION:SVN:REV IN:RIKENFE:CS:VERSION:SVN:REV
IN:SELAB:CS:VERSION:SVN:REV    5.5.0.1e45035
IN:RIKENFE:CS:VERSION:SVN:REV  5.5.0.1e45035
```

**Comment by Tom-Willemsen** [comment]
RIKENFE couldn't be deployed to as they were testing PLC code (which required use of IBEX) at the time when we wanted to deploy.
SELAB I think was in use at deployent time - but it is not a "production" instrument so we may be able to update it now if we ask electronics group nicely
