### ISSUE TITLE
GUI: Warning symbol always shown in load config dialogue

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5062]
As a user I don't want to be shown warning symbols when there isn't an issue with IBEX. An update to the load configurations dialogue has a warning symbol permanently displayed:

![image](https://user-images.githubusercontent.com/39486445/71822155-125f1f80-308c-11ea-8724-cd682e006421.png)

If this could be confusing to users, a different way of displaying this information should be considered and implemented.

### Acceptance Criteria

- Choose between:
    - Warning triangle is shown only when there is a protected config in the list
    - Use a padlock(or similar) to show protected icons

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1177
