### ISSUE TITLE
Reflectometry: Switch between standard and advanced table of motors view

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5063]
As an instrument scientist I would like to be able to switch between a standard "simple" table of motors (current) and an advanced table of motors (to be created). 

This ticket will add an option to switch the view but not implement the advanced minimal motor view itself. It is a follow on from [#4035](https://github.com/ISISComputingGroup/IBEX/issues/4035) that splits the advanced table of motors ticket into smaller chunks of work. Information for feedback on proposed layouts can be found on this ticket.

## Acceptance Criteria

- [ ] Users are able to switch between standard and advanced minimal motor views in the table of motors 
- [ ] The difference between a standard or advanced minimal motor view is a label showing "Advanced" etc.
- [ ] The process of switching has been documented in the User Manual

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1011
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/314
- https://github.com/ISISComputingGroup/EPICS-axis/pull/4

This fixes:
- https://github.com/ISISComputingGroup/IBEX/issues/5065
- https://github.com/ISISComputingGroup/IBEX/issues/5064
- https://github.com/ISISComputingGroup/IBEX/issues/5063 (this ticket)
