### ISSUE TITLE
Reflectometry: Advanced table of motors view status information

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5065]
As an instrument scientist I would like to be able to see advanced status information for my table of motors view. This should include:

- Axis movement direction
- Axis homed
- Axis Auto de-energise status
- Axis Encoder present
- Axis hard limits
- Axis soft limits triggered
- Axis Highlight for if SP =/= RBV outside of a tolerance after moved finished

This ticket will extend the advanced table of motors view to add status information. It is a follow on from [#4035](https://github.com/ISISComputingGroup/IBEX/issues/4035) that splits the advanced table of motors ticket into smaller chunks of work. Information for feedback on proposed layouts can be found on this ticket.

## Acceptance Criteria

- [ ] All fields listed above can be observed for a given motor on the advanced table of motors view
- [ ] The table of motors has not significantly changed in size
- [ ] Documentation exists for status information in the developer and user manuals
- [ ] All status flags have tool tips that give a reasonable explanation as to their intent

**Comment by John-Holt-Tessella** [comment]
Review as part of #5064
