### ISSUE TITLE
MUONS: Namespace for reduced set of commands

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5066]
As a muon scientist, I would like to make it easy for my users to understand which are the key commands required to control a muon instrument, so that they do not get confused by commands that they will rarely (if ever) need to use.

#### Acceptance Criteria
1. IBEX provides a so-called "reduced set" of commands for controlling muon instruments
1. The "reduced set" of commands is:
   * `begin()`
   * `end()`
   * `abort()`
   * `pause()`
   * `resume()`
   * `settemp(value)` - to set the temperature in K
   * `setmag(value)` - to set the magnetic field in G
   * `slits(value)` - to set the slit position
   * `tf20()` - to select the PSU for transverse field and set the field to 20G
   * `lf0()` - to select the Danfysik PSU (longitudinal field)
   * `f0()` - to select auto-zerofield
   * `sleep(value)`
   * `cshow_all()`
   * `blue_lt()` - to control the blue cryostat at temperatures below 5K
   * `blue_ht()` - to control the blue cryostat at temperatures above 5K
1. Command completion functions for these commands (e.g. in their own namespace).

#### Notes
1. See also #3952.
1. The muons group document these commands in their instrument manuals (see, for example, section 7.1.3 of the [EMU Manual](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/EMU/emu_manual_20190401.pdf).  In other words, muons group is already trying to make it clear to users that they only need a small set of commands to control the muon instruments.
1. It has been suggested that these commands be provided in their own namespace (i.e. not the usual `g.` namespace).
   1. If we adopted the convention `r.` for this namespace (`r.` for "reduced"), we could use the same convention for neutron instruments (should any wish to adopt it).
1. The `begin()` and `end()` commands should be the muon-specific versions of these commands.
1. Of the commands listed in section 7.1.3 of the EMU Manual, the most commonly used commands are `begin`, `end`, `settemp`, `setmag`, `slits`, `tf20`, `lf0`, `f0`.
   1. The `abort`, `pause`, `resume`, `sleep`, `setlabel`, `cshow_all`, `blue_lt` and `blue_ht` commands are less frequently used.
1. `sleep()` is a Python function.  How should we manage it?
1. The muons list the OpenGenie command `setlabel` as one of their "reduced set".  What is the IBEX equivalent (if any)?

**Comment by Tom-Willemsen** [comment]
This has been implemented as an instrument script - on the `NDXEMU` branch of the configurations repository
