### ISSUE TITLE
MUONS: Muon-specific help() command

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5067]
As a muon instrument scientist, I would like to make it easy for my users to get basic on-screen help for genie_python, so that it is easier for me to provide remote support (e.g. over the phone).

The rationale for this feature is that many muon users do not have English as a first language.  Explaining command syntax over the phone to non-native English speakers is often difficult.  Providing users with some simple, basic help will help them understand what they need to do to execute genie_python commands.  With well-written content, the `help()` command may allow users to complete actions without having to call an instrument scientist.  At the very least, having the text on-screen will also help me explain things to users.  In due course, it may even be possible to provide translations of the basic help (e.g. in Japanese for RIKEN users) - but that will be the subject of a separate ticket (see #5068).

#### Acceptance Criteria
1. IBEX provides a muon specific `muon_help()` command (it could form part of the reduced set of muon commands - see #5066).
1. On typing `muon_help()` (or `r.muon_help()`) at the scripting console prompt, IBEX shall display the basic help information.
   1. the content of this help has yet to be decided.

#### Notes
1. To be clear; the purpose of this feature is to  
   1. make it easier for users to help themselves 
   1. make it easier for instrument scientists to provide remote support to users.<br>
There is no expectation that this is a complete solution to the problem of providing remote support.  Rather it is is just one of a series of measures which, over time, may reduce the level of remote support required.

**Comment by Alexandru-Dascalu** [comment]
We try not to import new methods and into the global namespace, so the command can only be accessed through r.muon_help() and not muon_help(), and that is fine.
