### ISSUE TITLE
DETMON: Enable read-only IOC monitoring

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5069]
As someone supporting IBEX and the detector monitoring systems at ISIS, I want to monitor a number of HVCAENs in read-only mode from DETMON.

A read-only option for the HVCAEN IOC was implemented in https://github.com/ISISComputingGroup/IBEX/issues/4184 and is part of the latest release.

Davide Raspino will provide a number of IP addresses for the HVCAENs to monitor.

Acceptance criteria:

- [x] ~~Latest release is deployed to DETMON containing the read-only HVCAEN IOC option~~ This has already been done in #5596 
- [ ] HVCAEN IOC is loaded in read-only mode and points to the provided IP Addresses
- [ ] There are blocks on the Name, V0Set, I0Set, VMon, IMon and Status variables of each channel we are monitoring 
- [ ] Channel data logged as blocks
- [ ] Modify the blockserver to add the ability to specify a gwblock.pvlist and block_config.xml file in a configuration to configure the block gateway and archiver in a customisable way

Notes:

- See current DETMON config for when to log changes in channel values

**Comment by John-Holt-Tessella** [comment]
Impeded because CAEN will probably be turned off

**Comment by John-Holt-Tessella** [comment]
I will move this to work to do when back on site and remove from impeded

**Comment by JamesKingWork** [comment]
Davide has said that most of the crates are still on, so it is the perfect time to keep going.

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/ibex_utils/pull/80

**Comment by JamesKingWork** [comment]
The Crate IP addresses are available in crates.txt in the shares\ISIS_Experiment_Controls\DETMON folder

**Comment by JamesKingWork** [comment]
To the configuration, I have added new crates from the crates.txt and changed the IOC to read-only mode. Further to this, I have added the relevant blocks and groups using the find_DETMON_channels.py script which can be found at C:\Instrument\Settings\config\NDADETMON\Python\inst.

I found an issue that not all blocks were being written to the nexus file (see NDADETMON00000264.nxs which only contains blocks from LARMOR, SANS2D, MUSR and ZOOM). All the blocks are being monitored by the block archive (see http://ndadetmon:4813/group?name=BLOCKS&format=json) but many are considered disconnected. On further investigation, the block gateway was serving these PVs but they only appear connected if you monitor them for in the 10s of seconds sometimes even past a few minutes.

I think this may be caused by the sheer amount of blocks the block gateway is handling. The latest nexus file NDADETMON00000265.nxs cannot be read by hdfview 3.1.0.

**Comment by JamesKingWork** [comment]
Testing to see if writing a more compact gwblock.pvlist for the block gateway shower a lot of promise, it is much faster with the crates ZOOM, LARMOR, SANS2D and MUSR present.

Whilst testing with an addition 4 crates EMU, ENGINX1, NIMROD1 and POLREF the blockserver failed to start correctly, as did the block archiver. This may be also due to the sheer amount of blocks (now up to about 3700 from 300). This occurs at about the time when the blockserver is trying to set the block config for the archive engine and then restart the ioc alarm. A failure that is seen in the log is that the ioc log has rejected the connection.

**Comment by JamesKingWork** [comment]
> Testing to see if writing a more compact gwblock.pvlist for the block gateway shower a lot of promise, it is much faster with the crates ZOOM, LARMOR, SANS2D and MUSR present.
> 
> Whilst testing with an addition 4 crates EMU, ENGINX1, NIMROD1 and POLREF the blockserver failed to start correctly, as did the block archiver. This may be also due to the sheer amount of blocks (now up to about 3700 from 300). This occurs at about the time when the blockserver is trying to set the block config for the archive engine and then restart the ioc alarm. A failure that is seen in the log is that the ioc log has rejected the connection.

After an hour the blockserver manages to start with the archive engine and the blocks have values in the archive engine and are connected

**Comment by JamesKingWork** [comment]
The slowness is caused by setting the block config from the block_config.xml into MySQL for the archiver. By removing the run control PVs from block_config.xml this took it from 1 hour to 7 minutes.

**Comment by JamesKingWork** [comment]
Meeting to discuss solutions to current problems on Monday the 23rd of November, current ideas:

# Plan for DETMON block management

## Problem and tests to solve it

Currently, the blockserver/block gateway/block archiver is unusable on DETMON for the number of blocks we require.
The block gateway is using a ruleset that is so long it takes too long to reply to the block archiver and the value is considered disconnected.
We have proven that reducing the ruleset by cleverly naming the blocks and using specialised regex for these blocks we can greatly speed up reply time and make it possible to use 3149 blocks.
The block archiver takes an hour to take the values from block_config.xml and get them into the MySQL database.
We have proven that removing run control PVs from the block_config.xml reduces the load time of the block archiver from 1 hour to 7 minutes for 3149 blocks.

## Solution idea

block_server.py can be passed an -as or --archive_settings argument to select what block_config.xml to use.
block_server.py can be passed a -pv or --pvlist_name to give the name of the gwblock.pvlist file (this is just the name, not the directory though).
There is also a switch -cd or --config_dir which contains the configs directory.
So we can pass the blockserver or at least make edits to the blockserver to allow us to pass through where the files are.

There are two possibilities I see. The first being DETMON specific edits to the existing blockserver and the seconds being a DETMON replacement for the blockserver.

These would do the following on config change:

- On config change runs a script similar to the find_DETMON_channels.py script I currently use to set up blocks and groups
- I have also edited the find_DETMON_channels.py to produce a gwblock.pvlist and can edit to add a block_config.xml list
- We would need a configuration to associate HVCAENIP0 to HVACENIP7 to the crate they are on e.g. HVCAENIP2 is a crate on LARMOR and HVCAENIP6 is the NIMROD3 crate
  - This must be available to the blockserver and could be served through the CAEN IOC itself or as a simple JSON/XML file in the configurations
- On config change, we can produce these files and copy them into the correct area
- Prevent the blockserver writing it's standard gwblock.pvlist and block_config.xml
- Then run up the block gateway and archive engine as usual

### New block naming convention

Say we have a block on HVCAENIP2 which is a crate on LARMOR on board number 12, channel number 3, specifically for the status which is the pv CAEN:hv2:12:3:status.
The block would be called `LARMOR_12_3_status`. With `_` as the delimiter and LARMOR replacing HVCAENIP2.
This association between IPs and CAEN crate names must be available for the block server and could be served by configuring macros for the CAEN IOC or a simple JSON/XML config file.
I would prefer through macros because then you are only editing the configuration in one place rather than having to remember to edit the config file as well.

## Other suggestions

- Freddie has suggested using PCRE regular expression for the block gateway which would hopefully improve its performance

**Comment by FreddieAkeroyd** [comment]
Questions:
* Is the inst archiver coping with the number of PVs and archiving them? If so, could an approach based on using that rather than blocks work?
* the run control pvs in `block_config.xml` are just for the web dashboard?

There are also run control PVs in `gwblock.pvlist`. This file is searched bottom up and stops first match, so we may be able to optimise the order of items in this file to put most likely ones at the bottom. We do run a `ALLOW,DENY` evaluation order that means we have to search all of the deny list before we start in the allow list.
 
Currently we groups all items for an individual PV together. If we instead broke the file up differently into grouping the type of rule for all PVS together we may get better performance. For example we put run control rules at the top of the file so they would never get searched unless looking for run control. We also now have rules for as-is and upper case, doubling the number of rules. If we split upper case rules from as-is case we could again reduce number of rules scanned. Or maybe we have a blockserver option to not write upper-case rules? That may also save us needing the DENY rule we currently have and save that list search.

Another option: run multiple block gateways with smaller sets of files, these could then run in parallel

Some other ideas to consider:
- Alias PVs in each IOC rather than via a gateway #5912 
- Using PCRE with Just in time compilation may speed up evaluation #5909

**Comment by JamesKingWork** [comment]
# Agreed solution:

- Add a tag to the meta.xml or blocks.xml (probably blocks as this only relates to blocks themselves) of a config stating that this config carries a gwblock.pvlist and block_config.xml file for use with the block gateway and archiver (tag defaults to no)
- When block server is creating gwblock.pvlist and block_config.xml it checks meta.xml tag and if it is true copy the files from the configuration rather than creating them

**Comment by FreddieAkeroyd** [comment]
Just an update on underlying cause of problems. The 3000 PV in the blockserver gateway cause it to take a little longer to match a name request, but this is only a problem because the gateway then becomes continually busy (in fact CPU bound) looking up lots of requests for non existent PVs forwarded by the external gateway, so any new local request gets put so far back in the queue of pending requests it never gets done in time. Disabling the external gateway returns acceptable local PV lookup performance, and filtering of incoming external name lookup requests is something we should look to do in general #5917 as it may well be the cause of us seeing occasional disconnections reported for PVs. We were probably our own DOS attack :-D

**Comment by kjwoodsISIS** [comment]
In the light of Freddie's note, do we now need to go ahead with the [above changes](https://github.com/ISISComputingGroup/IBEX/issues/5069#issuecomment-732222971)?

**Comment by JamesKingWork** [comment]
The solution we decided on before is almost completed, it just needs tidying up and a system test adding, so I think continuing with that solution for this problem makes sense. Freddie's solution is a general fix and may also help for when we start adding lots more blocks to DETMON when we can launch more CAEN crates

**Comment by JamesKingWork** [comment]
Docs added to:

- https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/BlockServer

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/326
- https://github.com/ISISComputingGroup/EPICS-upgrade/pull/50
- https://github.com/ISISComputingGroup/system_tests/pull/71

**Comment by DominicOram** [comment]
There is some concern that the additional PVs on DETMON have caused issues on other instruments. In the current state everything seems happy but changing configurations on DETMON may change this. As that is probably required for reviewing this ticket I'm going to put this in impeded awaiting https://github.com/ISISComputingGroup/IBEX/issues/5924

**Comment by DominicOram** [comment]
With #5924 not being rolled out now it probably makes sense to just keep this impeded until the end of the cycle.

**Comment by JamesKingWork** [comment]
There are currently no blocks set up on DETMON because the CAEN crates are not giving any data. I have confirmed that this is nothing to do with the read only mode. I will set up blocks when the CAEN crates are back on. Details of how to do this are here https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details#configuration-set-up
