### ISSUE TITLE
DEPLOY: Demo to instruments - Planning

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5071]
As someone supporting IBEX I want to demo the changes being deployed to the instrument scientists and teams that use IBEX.

**Acceptance Criteria**
1. https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos is updated for this release:
   1. There is a list of items to highlight - those applicable to all instruments especially (individual instrument highlights are the responsibility of the hosts of the demo)
   1. The instrument groupings have been updated appropriately based on the list of instruments being deployed to - #5061 should have that list once #5060 has populated it
   1. New Demo host teams have been assigned to the instrument groupings
1. Demo hosts are informed that the table has been updated.
1. All demos have been scheduled.
1. The feedback from the demos have been posted on the IBEX Wiki and have been linked on the Timetable for Instrument Demos page. 

**Notes**
1. Whilst the scheduling of demos is the responsibility of the host teams, this ticket should not be considered closed until the demos have been scheduled. This gives whoever takes on this ticket the requirement to ensure that the hosts at least schedule meetings to undertake the demo, the meetings themselves do not need to take place to consider this ticket done

**Comment by KathrynBaker** [comment]
At least one thing to highlight to all instruments is the change in banner behaviour - those without motors should now be able to remove that stop all button, and we should ask those that attend if they would like a similar aggregated button to do something else - e.g. the "turn all PSUs off" functionality. Tickets should be created based on that feedback, and if there are enough examples we should consider if we can make this appropriately generic and something to include in configurations so that we can be less involved in changes as time goes on.

**Comment by DominicOram** [comment]
Is it worth having a wrap up meeting after demos are done? e.g:
* One person from each demo is nominated
* That person reads notes from all demos
* A 15-30 minute meeting is scheduled with all the nominated people
* The purpose of this meeting is to make sure appropriate tickets are created for all issues and that the tickets in some way reflect priority to users
* This meeting could be considered the review of this ticket

**Comment by John-Holt-Tessella** [comment]
I have been persuaded, this is a great idea

**Comment by DominicOram** [comment]
I did say that meeting would be the review but a lot of tidying up came out of it so it's probably worth someone else just having a quick look

**Comment by DominicOram** [comment]
To review this:
* Find the demo notes for the latest round of demos on the IBEX wiki
* Ensure that there are appropriate tickets next to most things in the notes
