### ISSUE TITLE
EMU: Danfysik: datasockets

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5079]
The labview danfysik IOC creates a datasocket server to share the field to HiFi and MuSR.

We need to replace this mechanism in IBEX.

Suggested solution (from @KathrynBaker ): in the labview VIs on HiFi and MuSR try to get the value via channel access, and fall back to datasockets if that doesn't work. This takes care of the case where EMU might run some experiments on SECI and others on IBEX.

**Comment by KathrynBaker** [comment]
A quick look at the VI shows this info is forwarded to MUSR – Field Viewer, and the datasocket is programmatic – so the suggested solution should be very easy to implement.

I can’t find anything obvious in the HIFI VIs – but it would be worth those involved in the EMU migration ensuring that the scientists on the other instruments are aware that this information could disappear.

Before this ticket can be completed can someone please specify here the PV that will need to be read for the EMU Main field in Gauss

**Comment by Tom-Willemsen** [comment]
It will be `IN:EMU:DFKPS_01:FIELD`

**Comment by KathrynBaker** [comment]
One look showed me it was two minutes worth of work, so I have done this and the code is on MUSR (@davidkeymer saw the code first), the final test will be to make sure that the field viewer on MUSR is reading as expected when things are being tested under IBEX.

**Comment by kjwoodsISIS** [comment]
It is not clear to me what is different about HIFI.  Is it that HIFI simply lacks the information about EMU's fields (and perhaps also MuSR's)?  Or is that that HIFI uses a different mechanism to get the information?

**Comment by KathrynBaker** [comment]
I can’t find anything in HIFI that is currently reading the information from the other two beamlines – but I might have missed it, hence warning the IS about the problem. I also don’t know if EMU is reading the field from MUSR at the moment – if it is and is using datasocket then we have a different issue and item to change there, but if it is, then I’m not certain where it is gaining the information from.

**Comment by KathrynBaker** [comment]
The field I see listed for MUSR is the same address as HIFI. I’ve made the same changes there for EMU as I did on MUSR (this is still a 1 point ticket…)

**Comment by davidkeymer** [comment]
VIs reviewed, loaded and run on both HIFI and MUSR.  EMU field read successfully from both instruments using CA.  Reading via DataSocket not checked as unavailable at time of review.

Relevant VIs in:
`C:\LabVIEW Modules\Instruments\HIFI\HIFI Field Viewer\HIFI - Field Viewer.llb\HIFI - Field Viewer - Front Panel.vi`
`C:\LabVIEW Modules\Instruments\MUSR\Field Viewer\MUSR - Field Viewer.llb\MUSR - Field Viewer - Front Panel.vi`
