### ISSUE TITLE
Multiple Consoles - Provide a Warning Message

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5084]
As a scientist, I would like IBEX to warn me if I open multiple scripting consoles, so that I don't inadvertently have two (or more) consoles running scripts.

#### Acceptance Criteria
1. On opening a second scripting console, I am warned that I already have an open console.
1. IBEX provides me with a choice:
   1. Proceed to open a second console.
   1. Cancel the opening of a second console.

#### Notes
1. This ticket applies to scripting consoles in the GUI.  It does not apply to scripting performed in separate command consoles.
1. This is a particular problem for users, they often don't realise they have multiple consoles open.  There is a risk that they end up running multiple scripts simultaneously.
1. Most instruments do not need to have more than one console open at any one time.
1. A few instruments do run multiple consoles and could find the warning messages irritating.  Ideally, our solution can accommodate both cases.  For example:
   1. There could be a checkbox on the warning dialog saying "Don't show me this warning again." (although this then shuts of the warning for other users).
   1. There could be a setting (under manager-mode control) which toggles the warning.
1. It would also be helpful if the console title could show 
   1. if a script is running
   1. the name of the running script (if any)

**Comment by DominicOram** [comment]
+1 from MARI

**Comment by RaiBishal** [comment]
After Discussing with @DominicOram and @ThomasLohnert. We are not forking PyDev for this ticket. Forking PyDev will be done in https://github.com/ISISComputingGroup/IBEX/issues/5405.

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/ibex_gui/pull/1104
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/45
