### ISSUE TITLE
Reflectometry: Parameter alignment define/move incorrect location

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5089]
![alignment_SG1_wrong_position](https://user-images.githubusercontent.com/43140680/72609353-8a470880-391c-11ea-9cf6-0413359e61d1.PNG)

S1VG's "define to" and "move to" text inputs are incorrectly positioned on the OPI.

## Acceptance Criteria

- All alignment parameters are correctly listed under their column headings

**Comment by John-Holt-Tessella** [comment]
Fixed somewhere else
