### ISSUE TITLE
ScriptGenerator: Behaviour testing

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5090]
As a developer I would like the script generator to be sufficiently tested.

Some parts of the script generator have been difficult to unit test due to their interaction with the user interface. This is a ticket to implement squish behaviour testing to cover those areas that have been missed.

Acceptance criteria:
- Tests are for ibex gui 
- Ticket exists for standalone version.
- [x] GIVEN I am on config one WHEN I switch to config two THEN the table action parameters are updated AND validity checking is reset 
- [x]  GIVEN I am on config one WHEN I add an action THEN an action is added to the table AND the action has the expected default values AND validity checks are update
- [ ] GIVEN there is an action in the table WHEN I delete an action THEN it is removed from the table AND validity checks are update
- [x] GIVEN there is an action in the table WHEN I duplicate the action AND change the original actions values THEN another action is added with the original values AND the new actions values didn't change upon updating the original actions values
- [x] GIVEN there are two actions in the table WHEN I move the bottom action up THEN it is moved up
- [x] GIVEN there are two actions in the table WHEN I move the top action down THEN it is moved down
- [x] GIVEN there are two valid actions in the table THEN the "Get Validity Errors" button is disabled AND the "Generate Script" button is enabled
- [x] GIVEN there are two invalid actions in the table THEN the "Get Validity Errors" button is enabled AND the "Generate Script" button is disabled
- [x] GIVEN there are two invalid actions in the table WHEN I press the "Get Validity Errors" button THEN a message dialog box appears detailing the validity errors
- [x] GIVEN there are two valid actions in the table WHEN I press the "Generate Script" button THEN a file message dialog box appears detailing the location of the file and a button allowing me to open it
- [x] GIVEN I am on config one WHEN I add an invalid action THEN the row is displayed in red AND the row's validity column has a heavy cross mark in it AND the row has a tooltip detailing the validity error
- [x] GIVEN I am on config one WHEN I add a valid action THEN the row is displayed with no color AND the row's validity column is green and has a heavy tick mark in it AND the row has no tooltip
- [x] GIVEN I am on config one WHEN I add an invalid action AND a valid action AND I swap them THEN the invalid action row is displayed in red AND the invalid action row's validity column has a heavy cross mark in it AND the invalid action row has a tooltip detailing the validity error AND the valid row is displayed with no color AND the valid row's validity column is green and has a heavy tick mark in it AND the valid row has no tooltip
- [x] GIVEN I am on config one WHEN I add a valid action AND duplicate that actions THEN both actions are marked as valid
- [x] GIVEN I am on config one WHEN I add an invalid action AND duplicate that actions THEN both actions are marked as invalid

**Comment by JamesKingWork** [comment]
Please take into account loading time as implemented in: https://github.com/ISISComputingGroup/IBEX/issues/5120

**Comment by Tom-Willemsen** [comment]
Also update manual system tests

**Comment by JamesKingWork** [comment]
Ticket for standalone version testing: https://github.com/ISISComputingGroup/IBEX/issues/5218

**Comment by JamesKingWork** [comment]
Ensure server has configs for testing

**Comment by JamesKingWork** [comment]
As part of the review, please consider whether the acceptance criteria and implemented tests are good enough test coverage

**Comment by JamesKingWork** [comment]
This should now include tests for the config help string display and the open manual functionality (to be implemented as part of Friday to prevent scope creep)

**Comment by JamesKingWork** [comment]
Ensure on test server the script generator perspective is not hidden. Ensure that the script generator preference points to the right configs directory.

**Comment by JamesKingWork** [comment]
When merged please ensure it is running correctly on the squish machine

**Comment by JamesKingWork** [comment]
Manual system tests are recorded in testing/manual_system_tests_template.xlsx in the ibex_developers_manual.wiki repo

**Comment by JamesKingWork** [comment]
Now requires: https://github.com/ISISComputingGroup/IBEX/issues/4907

**Comment by JamesKingWork** [comment]
It is probably best to review this ticket and #4907 together

**Comment by JamesKingWork** [comment]
@RaiBishal to take over this ticket

**Comment by Alexandru-Dascalu** [comment]
When this ticket is reviewed and merged, the reviewer should also either finish the review of https://github.com/ISISComputingGroup/IBEX/issues/5121 or let someone else with a Squish license that that ticket needs to be reviewed.

This is because that ticket has a PR that needs to be reviewed after this ticket's PR is merged. I originally reviwed that ticket and sent it for a rework. I do not have a Squish license, and can not re-review that ticket, but because it has a rework label others might avoid it and it may remain in review longer than it should.
