### ISSUE TITLE
EMU: read fields from MUSR and HIFI

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5091]
As an instrument scientist on EMU, I would like to be able to read the (longitudinal) fields from MuSR and HIFI.

Acceptance criteria:
- There are blocks on EMU for `field_hifi` and `field_musr` which read the fields from hifi and musr appropriately.

Notes:
- This is **not** a requirement for cycle. EMU do not currently have this functionality in SECI. It is a nice-to-have.
- The HiFi field is already served via channel access (see Kathryn's comment below)
- MuSR already runs the `SECI2IBEX` ioc which publishes their seci blocks as EPICS PVs

**Comment by KathrynBaker** [comment]
The HIFI field could be added now, this is already a PV coming from the cryomagnet system.

The MuSR field would potentially require some work, unless there is already a block on MuSR that is being fed out as a PV via that part of a mini_inst. Note that as MuSR already runs a mini_inst for the CAEN HV, then running up an extra IOC with an ad hoc/specific db shouldn’t be too hard, and the LabVIEW can be altered to periodically write the field setting to that PV.

**Comment by davidkeymer** [comment]
Confirmed that blocks exist on EMU reading main (selected) magnet's field on both MUSR and HIFI.  In fact, each of the three muon instruments have blocks for the fields on the other two.
