### ISSUE TITLE
Reflectometry: In beam parameter does not action if associated component offset is not in the mode

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5095]
We found this on SURF: The inbeam_sm parameter (in current mode) and SMOffset parameter (not in mode) caused the inbeam_sm paramter to not function. When asked to move in/out of beam the request would not be auctioned.

Thomas tried to reproduce this locally without success.

## Acceptance Criteria
- [ ] Recreate bug on SURF
- [ ] Identify the source of the bug
- [ ] Fix bug so the behaviour is no longer present

**Comment by John-Holt-Tessella** [comment]
Try again on SURF during shutdown

**Comment by John-Holt-Tessella** [comment]
Also see #5814

**Comment by ThomasLohnert** [comment]
Duplicate and fixed, closing issue.
