### ISSUE TITLE
MuSR: Metrolab PT2025 Teslameter IOC & OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5098]
As a muon scientist, I would like IBEX to provide an IOC & OPI for the Metrolab PT2025 Teslameter, so that I can use it on muon instruments.

#### Acceptance Criteria
1. Using IBEX, I can view the magnetic field in Tesla
1. Using IBEX, I can view the magnetic field in Gauss
1. Using IBEX, I can view a graph of the magnetic field (in T) as a function of time
1. Using IBEX, I can clear the plot (e.g. in preparation for another experiment)

#### Notes
1. The LabVIEW VI for the Metrolab PT2025 Teslameter is located here: `C:\LabVIEW Modules\Instruments\HIFI\Metrolab PT2025 NMR`
1. Need to discover the purpose of the Locked LED.
1. Need to discover the purpose of the String field.
1. Technical details of the [Metrolab PT2025 Teslameter](https://www.metrolab.com/products/pt2025/)
1. The screenshot below shows the Metrolab PT2025 Teslameter VI ![Metrolab PT2025 Teslameter](https://user-images.githubusercontent.com/7249337/72724361-03dc3200-3b7b-11ea-97a4-9035ffa3a841.png)

**Comment by davidkeymer** [comment]
From analysis of device VI:

- Communications settings: 9600,8N1 (9600baud, 8 data bits, no parity, 1 stop bit)
- Possible termination character: LF, \\n, 0xA
- No commands required as device continuously transmits `L xxxxxx...` where `xxxxx...` is an unknown number of numeric characters representing a float value of the field strength in units of tesla.

The device _may_ have a mode in which an inquiry command may be sent to it to request the field strength, which may be more compatible with EPICS (certainly easier to deal with).  However, this will need to be researched.  No manual available at time of writing.

**Comment by kjwoodsISIS** [comment]
Required, if we are to migrate MuSR for Cycle 2020/04 (11th February 2021 - 27th March 2021).

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/96
https://github.com/ISISComputingGroup/EPICS/pull/238/files
https://github.com/ISISComputingGroup/EPICS-ioc/pull/561
https://github.com/ISISComputingGroup/EPICS-pt2025/pull/1
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/393

**Comment by rerpha** [comment]
OPI and IOC work nicely, but I think there are a few tweaks to be made on the support module that will make it easier to use
