### ISSUE TITLE
MuSR: Transverse Field PSU

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5099]
As a muon scientist, I would like IBEX to provide support for the Thurlby TTi EX355P for operation on MuSR.  The Thurlby PSU is used to power the transverse magnet on MuSR.

#### Acceptance Criteria
1. The IOC can convert between current and field
1. The OPI should display the magnet name in its title field.
1. The OPI should provide an Off button:
   1. On pressing the Off button, the IOC should "sweep to zero and turn off" the PSU (see notes below)
1. The Transverse Field PSU OPI for MuSR should contain the following fields
   1. magnetic field set-point
   1. magnetic field set-point readback
   1. magnetic field read-back (i.e. "field now") 
1. The units of the magnetic field are in Gauss
1. The OPI should display a "Field Ready" LED to show the status of the magnetic field:
   1. the LED should be OFF when the magnetic field is ramping.
   1. the LED should be ON when the magnetic field has reached its set-point.
1. The OPI should display a "progress bar" to show the field as a % of full-scale (see notes below).

#### Notes
1. This ticket should be very similar to #5042 and #5043.
1. Some investigation of the VI, and the settings & configuration files on MuSR itself will be required, because the operation of the copy of the Transverse field VI (on NDXDEMO) is not entirely obvious.
1. The OPI needs to display the same information as the existing Transverse Field PSU VI.
1. The existing Transverse Field PSU VI is located here: `C:\LabVIEW Modules\Instruments\MUSR\Transverse Field`
   1. ![MuSR_Transverse (Thurlby)](https://user-images.githubusercontent.com/7249337/101517926-33558200-3979-11eb-9140-6f3f6422a5f8.png) <br> is a screenshot of the VI in `C:\LabVIEW Modules\Instruments\MUSR\Transverse Field`
1. The current/voltage gauges on the VI do not need to be reproduced on the OPI.
1. The calibration defining the relation between current and magnetic field is defined in a .ini file in SECI
1. The Thurlby TTi EX355P PSU may or may not have a hardware "sweep to zero and turn off" feature.  We need to find out.  If there is no "sweep to zero and turn off" in hardware, we may have to implement it in software (in the IOC or as a script).

**Comment by ThomasLohnert** [comment]
I get the impression there will be a lot of code duplication between this, Danfysiks and TDK Genesys (Geneses?) Is it worth establishing some kind of `magnet_common.db` for consistency?

**Comment by DominicOram** [comment]
Note that Thurlby TTi EX355P is already support

**Comment by Tom-Willemsen** [comment]
The Labview vi implements offsets on read & write, but these are always set to zero in config files. I have checked the SECI configurations also, and there are no non-zero values present. Therefore we don't need to copy the offsets functionality in IBEX.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/408
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/579
- https://github.com/ISISComputingGroup/ibex_gui/pull/1242
- https://github.com/ISISComputingGroup/IBEX/pull/6106
