### ISSUE TITLE
EMU: Investigate get_block_names failing very frequently

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5113]
As an instrument scientist on EMU I would like to be able to use `cget` and `cset` reliably without getting exceptions about `get_block_names` failing.

In [this ticket](https://github.com/ISISComputingGroup/IBEX/issues/4911) we added a retry loop which retries the cget and cset if it failed. This retry loop is being hit very frequently on EMU, despite the underlying pv (`IN:EMU:CS:BLOCKSERVER:BLOCKNAMES`) being available via a command-line `caget` request.

As a temporary fix we have replaced cget and cset in EMU's instrument scripts with `g.set_pv("CS:SB:blockname", is_local=True)`, but this is unintuitive.

### Acceptance criteria:
- cget and cset work consistently on EMU without entering the retry loop

### Notes
- The cgets and csets do work eventually, but sometimes take up to ~2 minutes to be noticed (due to the retry loop needing to retry several times). This is unacceptable for the workflow on EMU.
- The error is the same as in https://github.com/ISISComputingGroup/IBEX/issues/4136 . The solution to these tickets might be the same. However, it is happening very often on EMU - previously we have only seen it as a sporadic failure.

**Comment by John-Holt-Tessella** [comment]
Just so it is clear:

- BLOCKNAMES is supported by the block server it is a default that is sent back in the last bit of read (block_server.py ln 237)
- Block values is supported by the block cache.

It sounds like it is blocknames which is failing

**Comment by Tom-Willemsen** [comment]
I can no longer reproduce this. It may have been fixed by the updated genie_python locking that we added. Closing for now.
