### ISSUE TITLE
Muons: DAE spectra plots need to be in units of ns not μs

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5116]
As a muon instrument scientist I would like the x scale of my spectra plots to be labelled correctly.

Acceptance criteria:
- The x axis is labelled as nanoseconds on muon instruments
- The x axis remains labelled as microseconds for neutron instruments

Notes:
- We should also consider the drop down menu which switches the mode between `counts/us` and `counts`. It should read `counts/ns` on muon beamlines.
- The appropriate units should be served by the ISISDAE ioc.

**Comment by FreddieAkeroyd** [comment]
To test:
```
caget %MYPVPREFIX%DAE:SPEC:1:1:X.EGU
```
should return us. Then
* edit icp_config.xml and change DAEType to 2
* edit isisicp.properties, add or change line to read 
```
isisicp.simulation.detcards.type = muon
```
the restrat isisicp and ISISDAE ioc. Thus puts you into a simulated Muon DAE and then
``` 
caget %MYPVPREFIX%DAE:SPEC:1:1:X.EGU 
```
should return  ns

**Comment by FreddieAkeroyd** [comment]
GUI will need to be updated to use EGU field

**Comment by JamesKingWork** [comment]
GUI PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1043
