### ISSUE TITLE
RKNPS: Implement AUTOONOFF

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5119]
As a user I would like the RIKEN power supplies and other danfysiks to be kept in sync. See https://github.com/ISISComputingGroup/IBEX/issues/4348. As of https://github.com/ISISComputingGroup/IBEX/issues/5042 there is an `AUTOONOFF` PV on other danfysiks. RKNPS should also have this. The code should be implemented in a way such that they use a common DB.

**Comment by Tom-Willemsen** [comment]
@DominicOram to close this

**Comment by DominicOram** [comment]
After discussion with @KathrynBaker this feature will never be used on RIKEN and so is not required.
