### ISSUE TITLE
Script Generator: UX improvements (tabbing across table)

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5121]
As a user, I want to be able to navigate the script generator actions table without having to laboriously click all the time.

Acceptance criteria:

- [x] When I am editing an action in the table and press tab I switch to editing the next in the row
- [x] When I am editing the last column of the table and press tab a new action is created as a row just below this action and I am editing the first column of this row

**Comment by DominicOram** [comment]
[Here](https://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/examples/org.eclipse.jface.snippets/Eclipse%20JFace%20Snippets/org/eclipse/jface/snippets/viewers/Snippet035TableCursorCellHighlighter.java) is a good place to start. I tried to implement using the `EditingSupport`/`LabelProvider` that we already have but we're doing something wacky inside those classes. If you try and use it exactly as in the example it works so we need to work out what the differences are.

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/41
https://github.com/ISISComputingGroup/ibex_gui/pull/1097

**Comment by RaiBishal** [comment]
This PR: ISISComputingGroup/System_Tests_UI_E4#41 can be reviewed now.
