### ISSUE TITLE
Script generator: UX improvements (Select multiple lines and duplicate or delete)

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5122]
As a user, I want to be able to duplicate or delete multiple actions in the table to optimise my workflow.

Acceptance criteria:

- [ ] When I select multiple lines and click duplicate then all these actions are duplicated
- [ ] When I select multiple lines and click delete then all these actions are removed from the table
- [ ] For now this is a contiguous block
- [ ] There is a system test for this
- [ ] When I select multiple lines and then click move up or move down, the lines all move up or down

**Comment by Tom-Willemsen** [comment]
+1 all muon scientists at training session.

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by adalator** [comment]
Note to self: Does the move action up/down feature still work with multiple selection?

**Comment by adalator** [comment]
Added criterion for moving multiple actions

**Comment by adalator** [comment]
I've done most of the ticket but a rebase broke it, as explained in the PR above.

**Comment by DominicOram** [comment]
GUI PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1117
Tests: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/61

**Comment by DominicOram** [comment]
Repointing as was training but ended up having to be finished off as a non-training ticket.
