### ISSUE TITLE
Script Generator: Drop down for enum type

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5124]
As an instrument scientist, I want to be able to define an enum data type for a script generator table column so that a user can select from one of the enum values from a drop-down list.

Acceptance criteria:

- [x] There is a script generator enum data type
- [x] A scientist can use the data type in a configuration
- [x] When an enum data type is used for a parameter this is loaded as a drop-down in the GUI

**Note:** Deemed "crucial" by Muon group

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by isaachilly** [comment]
#PRS

[ScriptGen](https://github.com/ISISComputingGroup/ibex_gui/pull/1625)

[Script Definitions](https://github.com/ISISComputingGroup/ScriptDefinitions/pull/10)
