### ISSUE TITLE
NIMROD: MOXA Remove or network [Not urgent]

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5131]
The moxa on nimrod has been unplugged from the network. 

Either bring MOXA back or renetwork moxa. To decide look at site and ask the scientists why they unplugged it. It is better to network if possible so we have access to serial lines plugged into Galils.

MOXA is by/in motion racks in the hall.

### Acceptance Criteria

Decide whether galil moxa is needed.

**Comment by Tom-Willemsen** [comment]
The moxa used to be used by the galils. However, the galils are now on ethernet under IBEX, so the moxa is not required. It had to be unplugged from the network because (I believe) there were only enough physical network ports in that area for the galils.

**Comment by ChrisM-S** [comment]
Closing this ticket as there is no easy way of networking this MOXA while the nearby four sockets are occupied by the private network.  However, should the MOXA be needed, it will stay there (plugged in to the Galils if I remember correctly) and can be re-connected to the network fairly easily with a looooong cable or re-assigning one of the Galil connections to the main network.

/remind me in two years to review this :-).
