### ISSUE TITLE
GUI: Memory leak in edit or load configuration [time box 2d]

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5136]
## Issue
Following on from [#4239](https://github.com/ISISComputingGroup/IBEX/issues/4239) it seems like there are still some issues with memory leaks when using configurations.

I've identified and investigated replicating two methods of causing the client to hang due to reaching the heap limit of 512mb. Tested on release 6.0.0 with VisualVM 1.4 on NDXSCIDEMO.

## Acceptance Criteria

- [ ] Editing the configuration does not cause memory to leak
- [ ] Reloading the configuration does not cause memory to leak

# Edit existing configuration:
1. Open fresh instance of IBEX GUI
1. Point VisualVM at the client. The heap size and usage ~225mb.
1. On some configuration duplicate a block and then save
1. Repeat this process (I found 30 edits was enough)

You should see that the client aggressively holds memory and as the heap size limit is reached the garbage collector takes 20-25% CPU. See image:

![memory_leak_using_edit_config_fresh_client](https://user-images.githubusercontent.com/43140680/73538606-5511de80-4423-11ea-9fdf-dde83c953d2f.png)

# Reload configuration
1. Open a fresh client
1. Point VisualVM at the client. The heap size and usage ~225mb.
1. Load some configuration
1. Repeat this process

You should see that the client gradually holds memory and I fully expect for the client to hang as you approach the heap limit. This leak is a lot slower compared to the edit configuration. See image:

![memory_leak_using_load_config_fresh_client](https://user-images.githubusercontent.com/43140680/73538736-aae68680-4423-11ea-85bc-d8c74bfe425e.png)

## Notes
- The investigation was against a fresh client to observe the time taken to cause a client hang. The amount of edits required to hang the client in a more natural setting (i.e., switiching perspectives, holding multiple plots and opening OPI's) result in a faster client hang. This is due to these objects holding a larger memory footprint before introducing the memory leak.
- I believe I have seen this issue on instruments 3 times now

**Comment by DominicOram** [comment]
After discussion with @John-Holt-Tessella, @ChrisM-S and @aaron-long. The plan is to up the memory limit to 1GB for the release and work on fixing this leak to get patched on to the instrument at some point in the coming cycle.

**Comment by aaron-long** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1037

**Comment by John-Holt-Tessella** [comment]
There is at least one memory leak here:

uk.ac.stfc.isis.ibex.configserver.editing.EditableConfiguration.addObserver()

I am looking at that

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1045
