### ISSUE TITLE
EMU: don't complain on begin if run is already in progress

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5141]
As a muon instrument scientist, I would like `begin()` to not throw an error if a run is already in progress - instead I just want it to print something along the lines of `Run x already in progress, continuing run`

Acceptance criteria:
- when typing begin on a muon instrument when already running, no error is printed

Notes:
- This could be implemented either at the script generator level or at the `begin_precmd` level. Decide the implementation as part of this ticket

**Comment by JamesKingWork** [comment]
PRs:

https://github.com/ISISNeutronMuon/InstrumentScripts/pull/55
