### ISSUE TITLE
genie_python: END and PAUSE are missing "immediate" options 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5142]
Both END and PAUSE need to support an "immediate=True" option, this is to tell the control program to not wait until a period sequence is complete when running with the period card in hardware period mode. For pause it just need to do the equivalent of
```
 echo 1 > c:\data\end_now.dae
```
before executing pause. 

For END the genie implementation looks a bit more complex. To avoid getting stuck in end it requests the period card to initiate a "stop after sequence completes" and then it polls from the script to see if this sequence is done until it executes END, which avoid you getting stuck in an unendable run if you forget to use immediate. So this will require some ISISDAE changes.

**Comment by FreddieAkeroyd** [comment]
OK, the complex END with Open GENIE was because the DCOM call would stop a CTRL-C working. So all that needs to be done in either case is
```
 echo 1 > c:\data\end_now.dae
```
before executing the appropriate END/PAUSE. Note that this may need some of the runstate logic in the command adjusting. For example, if you type END and the beam is off you will control-C and then want to type "end immediate=True" while in an "ENDING" state, so the END command would need to have "ENDING" as one of its allowed initial states. Similarly PAUSE would need to be allowed when PAUSING.

**Comment by Tom-Willemsen** [comment]
On discussion with the scientists: this is not a particularly high priority, they would like it as a nice-to-have but it's not a blocker.
