### ISSUE TITLE
Remove EPICS-ExperimentalDatabase 

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5148]
As a developer I would like to not have to be faced with unused code. The functionality in https://github.com/ISISComputingGroup/EPICS-ExperimentalDatabase should have been replaced by https://github.com/ISISComputingGroup/ExperimentDatabasePopulator so remove the former.

- [x] Confirm all functionality the same between the two repositories
- [x] Remove EPICS-ExperimentalDatabase repository
- [x] Remove reference from top EPICS
- [x] Remove references from developer wiki and ensure ExperimentDatabasePopulator covers it
- [x] Remove associated EXPDB
- [x] Remove references in manual testing spreadsheet
- [x] Remove code that uses it in the squish tests

**Comment by rerpha** [comment]
PRs: 
- EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/259
- Squish: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/89
- ExperimentalDatabase: https://github.com/ISISComputingGroup/EPICS-ExperimentalDatabase has been archived
- Dev wiki: edited https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Startup-and-Shutdown as we no longer run the exp db on instrument machines as well as https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-components
- Manual system tests template - removed test for EXPDB on startup
Release notes - https://github.com/ISISComputingGroup/IBEX/pull/6509
