### ISSUE TITLE
ZFCNTRL zero field IOC: stop excessive logging to putlog

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5151]
Ending runs on EMU was taking a long time, this was related to alarm logging as the putlog entries had a random alarm status and it was taking time to build an alarm event array. It was noticed that there were 400000 putlog entries for the run, which were almost entirely setting the current on Kepcos and @Tom-Willemsen confirmed would be from the  ZFCNTRL. It is probably not useful to have all these logged, but it would be useful to see logging of puts to the kepco from other sources than ZFCNTRL.

One solution might be to create a separate (less visible) current set pv on the kepco and then the  ZFCNTRL can use this PV rather than the CURRENT:SP - this PV would need its ASG field set to "NOTRAPW" so an not to trigger the CA trapwrite mechanism used by caPutLog. To be decided is whether this separate PV writes to CURRENT:SP or CURRENT:SP write to this PV, this may depend on whether CURRENT:SP is logged and how value logging wants to be  handled. 

Acceptance criteria:
- zero field writes to the kepco power supplies does not log excessively
- user writing to the kepcos does go to caputlog

**Comment by FreddieAkeroyd** [comment]
The EPICS MySQL archive is already 14GB on EMU

**Comment by Tom-Willemsen** [comment]
Using the archive rate script, the fastest-logging PVs which are writing to the database are as follows:

```
IN:EMU:CS:DASHBOARD:TAB:1:1:VALUE.VAL   count=60        rate=2.00 Hz
IN:EMU:ZFCNTRL_01:FIELD:MAGNITUDE.VAL   count=60        rate=2.00 Hz
IN:EMU:KEPCO_02:CURRENT:SP.VAL  count=58        rate=1.93 Hz
IN:EMU:ZFCNTRL_01:FIELD:MAGNITUDE:MEAS.VAL      count=58        rate=1.93 Hz
IN:EMU:KEPCO_03:CURRENT:SP.VAL  count=56        rate=1.87 Hz
IN:EMU:KEPCO_01:CURRENT:SP.VAL  count=53        rate=1.77 Hz
IN:EMU:KEPCO_02:CURRENT:SP:RBV.VAL      count=52        rate=1.73 Hz
IN:EMU:KEPCO_03:CURRENT:SP:RBV.VAL      count=52        rate=1.73 Hz
IN:EMU:ZFCNTRL_01:FIELD:X.VAL   count=45        rate=1.50 Hz
IN:EMU:KEPCO_01:CURRENT:SP:RBV.VAL      count=44        rate=1.47 Hz
IN:EMU:ZFCNTRL_01:FIELD:X:MEAS.VAL      count=31        rate=1.03 Hz
IN:EMU:KEPCO_03:CURRENT.VAL     count=30        rate=1.00 Hz
IN:EMU:KEPCO_04:VOLTAGE.VAL     count=30        rate=1.00 Hz
IN:EMU:CS:DASHBOARD:TAB:1:2:VALUE.VAL   count=30        rate=1.00 Hz
IN:EMU:DFKPS_01:RAW.VAL count=29        rate=0.97 Hz
IN:EMU:DFKPS_01:CURR.VAL        count=29        rate=0.97 Hz
IN:EMU:DFKPS_01:FIELD.VAL       count=29        rate=0.97 Hz
IN:EMU:KEPCO_01:VOLTAGE.VAL     count=27        rate=0.90 Hz
IN:EMU:CS:DASHBOARD:TAB:3:1:VALUE.VAL   count=26        rate=0.87 Hz
IN:EMU:KEPCO_02:CURRENT.VAL     count=25        rate=0.83 Hz
IN:EMU:KEPCO_02:VOLTAGE.VAL     count=25        rate=0.83 Hz
IN:EMU:KEPCO_03:VOLTAGE.VAL     count=22        rate=0.73 Hz
IN:EMU:KEPCO_01:CURRENT.VAL     count=17        rate=0.57 Hz
IN:EMU:CS:DASHBOARD:TAB:2:1:VALUE.VAL   count=16        rate=0.53 Hz
IN:EMU:MUONJAWS_01:VOLTAGE.VAL  count=16        rate=0.53 Hz
IN:EMU:MUONJAWS_01:POSN.VAL     count=16        rate=0.53 Hz
IN:EMU:KEPCO_04:CURRENT.VAL     count=8 rate=0.27 Hz
IN:EMU:CS:DASHBOARD:TAB:2:2:VALUE.VAL   count=8 rate=0.27 Hz
```

**Comment by Tom-Willemsen** [comment]
Mitigations:
- In EMU's configs, use PV sets to put the zero-field kepco current setpoints into the `NOTRAPW` access security group. Other kepcos (e.g. steering magnet and kepcos on other instruments) are not affected by this change.
- Limit the ZF system to archiving values at most once every 5s (per pv) https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/6
- Limit kepcos to archiving values at most once every 5s (per pv) https://github.com/ISISComputingGroup/EPICS-kepco/pull/6

**Comment by DominicOram** [comment]
Documentation changes are good, thank you
