### ISSUE TITLE
EMU: standalone non-interactive setlabel command

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5153]
As an EMU instrument scientist I would like a non-interactive version of `setlabel` so that I can set parameters explicitly in a script if needed. This version should not ask any questions interactively (unlike the version used by `begin()` and `end()`

It should be made available as `inst.setlabel` and `r.setlabel`

**Comment by JamesKingWork** [comment]
Why is this impeded?
