### ISSUE TITLE
SP300: Add support for CA/CP with limitations techniques

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5158]
As a scientists I would like to use the "with limitations" versions of the CA/CP techniques.

acceptance criteria

ECLAB ioc can be configured with CALIMIT / CPLIMIT techniques

**Comment by FreddieAkeroyd** [comment]
Needed for #5139

**Comment by Tom-Willemsen** [comment]
@FreddieAkeroyd has already "sort of done" this

**Comment by FreddieAkeroyd** [comment]
Implemented in #4788

**Comment by John-Holt-Tessella** [comment]
Impeded until potentionstat works

**Comment by FreddieAkeroyd** [comment]
Done in #4788
