### ISSUE TITLE
EMU: ctrl-c doesn't work correctly during begin/end questions

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5160]
As a scientist on EMU I would like ctrl-c to work during my `begin`/`end` questions. At the moment the keyboard interrupt is ignored and a blank line is assumed.

Acceptance criteria:
- Ctrl-C can break out of the begin/end questions

Notes:
- Looks like https://bugs.python.org/issue26531 from an initial look

**Comment by Tom-Willemsen** [comment]
This has different behaviour in pydev and in a standalone python console:

In a pydev console (bug):

```
from six.moves import input
input()
<ctrl-c>

Out[21]: ''
```

In a standalone console:

```
>>> from six.moves import input
>>> input()
<ctrl-c>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>>
```

**Comment by Tom-Willemsen** [comment]
According to the python bug report for this, this is fixed in python 3. After discussion with the scientists it is not critical for this cycle. Putting this ticket back into the backlog for now.

**Comment by FreddieAkeroyd** [comment]
@Tom-Willemsen  if this is fixed in python 3 can this ticket now be closed?

**Comment by Tom-Willemsen** [comment]
Looks like the simple example above is fixed in 3:

```
import sys
sys.version
Out[6]: '3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]'
from six.moves import input
input()
<ctrl-c>
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  ...
  File "C:\Instrument\Apps\Python3\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```
