### ISSUE TITLE
LET + POLARIS: Set up orange cryostat (--/02/2020)

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5161]
As a user on POLARIS and LET I want to use the orange cryostat. JN has got some new eurotherm firmware that handles more of the logic for the cryostat. From our point of view the only change should be that we will only need 1 eurotherm channel rather than 3. JN is currently testing that this is working using SELAB.

**Comment by John-Holt-Tessella** [comment]
Still on SELab being tested (JN at conference today)

**Comment by DominicOram** [comment]
JN says there is no work required for us now.
