### ISSUE TITLE
LINMOT: port creation

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5163]
Linmot motor controllers require the port to be created before the EOS input/outputs are created.

This is a hotfix for an issue discovered on MAPS during deployment. The patch has been tested against hardware.

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/472

**Comment by DominicOram** [comment]
Will need to hotfix on to:
- [ ] OSIRIS
- [ ] ENGINX
- [ ] HRPD
- [ ] MAPS
- [ ] POLARIS
- [ ] GEM
- [ ] MERLIN
