### ISSUE TITLE
MUONFE: ISISDAE crashing with 6.0.0

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5164]
MUONFE is running ISISDAE in a "no dcom" mode, this has ISISICP linked into the ISISDAE process. AS isisicp is now built with VS2015, this is incompatible with a vs2010 isisdae-ioc in this mode.  Solution was to copy older isisicp biknaries back onto muonfe

**Comment by FreddieAkeroyd** [comment]
Copy all files except isisdae-ioc-01.exe from the ioc/master/isisdae/bin/windows-x64 directory of the 5.5.0 release of IBEX

**Comment by FreddieAkeroyd** [comment]
Wiki release page now updated

**Comment by DominicOram** [comment]
* Where exactly is this written? I couldn't easily find it
* Is this something we will be doing for every release now going forward? If so can we add it to the deployment steps in https://github.com/ISISComputingGroup/ibex_utils/tree/master/installation_and_upgrade

**Comment by FreddieAkeroyd** [comment]
It is listed as a hotfix on https://github.com/ISISComputingGroup/IBEX/wiki and the install process asks to check for hotfixes, it will only be required until we compile EPICS with vs2015 and above i.e. when new galil driver is merged

**Comment by DominicOram** [comment]
From experience I think that it's easy to miss the hotfix step when you're deploying to a dozen instruments, I've added an explicit step

**Comment by DominicOram** [comment]
@FreddieAkeroyd how does this relate to updating the ICP (https://github.com/ISISComputingGroup/IBEX/issues/3928)? Does it mean that we should not be ever updating the ICP on MUONFE or that even if we do it doesn't matter as the IOC isn't communicating with it anyway?
