### ISSUE TITLE
Support: standalone Journal Viewer not getting historic data

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5169]
IS called from IRIS, they couldn't access historic journal entries in the standalone journal viewer but could in the viewer in the IBEX client.

### Acceptance Criteria
* The standalone journal viewer can get historic entries
* There is documentation about the standalone journal viewer on the developers wiki, specifically:
   * Where it's data comes from
   * What parts of it are our responsibility

**Comment by FreddieAkeroyd** [comment]
It seems to be working OK now, so I guess was an issue with the windows domain controller it authenticates from

**Comment by John-Holt-Tessella** [comment]
Have we let the IRIS instrument scientist know?

**Comment by John-Holt-Tessella** [comment]
Can not see any evidence of documentation

**Comment by FreddieAkeroyd** [comment]
Docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Journal-Viewer-Data
