### ISSUE TITLE
LARMOR: Test Scanning & Plotting

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#517]
As an instrument scientist, I want to test scanning & plotting under realistic conditions.

'''Acceptance Criteria'''
1. Work with the LARMOR instrument scientists to confirm that scanning & plotting operate as expected.

'''Notes'''
1. Ideally, scanning & plotting operations will be done from the GUI (rather than from a separate scripting console or from Mantid).
1. Ideally like to test this feature available in January 2015.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 518.  Created by skn09965 on 2014-10-02T15:21:30, last modified: 2015-03-12T08:57:41_

**Comment by kjwoodsISIS** [comment]
This ticket has been overtaken by events.  Scripting is working well on LARMOR (and other instruments).  Can also plot, using matplotlib or use Data Plotter.  It can now be closed.
Any future improvements to scripting can be initiated with a new ticket.

**Comment by kjwoodsISIS** [comment]
Oops.  Closed in error.  Re-opened.

**Comment by DominicOram** [comment]
This is too out of date to be relevant.
