### ISSUE TITLE
Python 3: Make systems run in python 3 that need to

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5175]
Systems that should be running under python 3 should now be switched to that:

If pydev doesn't work spin new tickets and decide on priority

Requires #5241 to be merged before reviewing/merging. (Fixes to matplotlib backend)

### Acceptance Criteria

- [ ] Genie_python is running in python 3
- [ ] Gui scripting perspective is launched so that it runs python3
- [ ] ~Nicos is launched to run python 3~
- [ ] Basic smoke testing - run each command in genie_python once
- [ ] disable unnneeded py2 tests (if any)

**Comment by RaiBishal** [comment]
> * Nicos is launched to run python 3

This is being implemented in this ticket #4887

**Comment by Alistair-McGann-Tessella** [comment]
PRs:
GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1066
Upgrade script: https://github.com/ISISComputingGroup/ibex_utils/pull/57
Genie python: https://github.com/ISISComputingGroup/genie_python/pull/228
EPICS: https://github.com/ISISComputingGroup/EPICS/pull/204

**Comment by RaiBishal** [comment]
**https://github.com/ISISComputingGroup/IBEX/issues/5152 must be merged first** for reviewing this ticket.

**Comment by JamesKingWork** [comment]
> **#5152 must be merged first** for reviewing this ticket.

#5152 is now merged

**Comment by RaiBishal** [comment]
#5241 to be merged before reviewing this ticket.
