### ISSUE TITLE
MuSR: Rotation change investigation

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5178]
@Kevin-Woods-Tessella to complete

### Acceptance Criteria

- look through lab view
- talk with scienitst
- write requires for next ticket #5096

**Comment by kjwoodsISIS** [comment]
Required, if we are to migrate MuSR for Cycle 2020/04 (11th February 2021 - 27th March 2021).

**Comment by DominicOram** [comment]
What's the state of this ticket? The acceptance criteria aren't clear and we've said it's blocking https://github.com/ISISComputingGroup/IBEX/issues/5096 so together they're making up a large part of the sprint.

**Comment by kjwoodsISIS** [comment]
We had a discussion with the instrument scientist on Monday (30th November).  We (@Tom-Willemsen , @davidkeymer & myself) had a further discussion about this today.  The instrument scientist can't remember all the details of how the rotation change VI works, but we beleive we do understand the essentials.  However, what the instrument scientist says is consistent with Kathryn's comment (in #5096).
Here are the salient points:
   1. Rotating MuSR is a manual operation.  There is no automated way of doing it.  There are no interlocks to prevent you from rotating the instrument - you just rotate it.  The instrument scientists want some clear indications as to the state of the instrument before they rotate it.
   1. The rotation of MuSR is managed via the MuSR Geometry VI.
      * the term "managed" is deliberate.  It is not "controlled" in the sense of being automated.
   1. The MuSR Geometry VI has two buttons: Go to Longitudinal and Go to Transverse.
      * On pressing Go to Longitudinal, the MuSR Geometry VI:
          a. stops the zero-field controller and magnet (Danfysik & Thurlby) VIs
          b. modifies the config files to use the appropriate zero-field co-efficients for longitudinal mode
          d. restarts the zero-field controller and magnet (Danfysik & Thurlby) VIs.
      * On pressing Go to Transverse, the MuSR Geometry VI:
          a. stops the zero-field controller and magnet (Danfysik & Thurlby) VIs 
          b. modifies the config files to use the appropriate zero-field co-efficients for transverse mode
          d. restarts the zero-field controller and Danfysik magnet (Danfysik & Thurlby) VIs.
   1. The cDAQ used in the Zerofield controller the 4th channel is "spare".  On EMU (and presumably other muon instruments) the 4th channel is not used at all.  On MuSR, the 4th channel is used to monitor a voltage which indicates the orientation of the instrument.
      * If the voltage is greater than `max_threshold` the instrument is in longitudinal mode
      * If the voltage is less than `min_threshold` the instrument is in transverse mode
      * The instrument scientist cannot remember the values of `max_threshold` and `min_threshold`.  He thinks they might be `+/- 5V`, but it could be `+/- 10V`.  We will need to inspect the LabVIEW code to discover the actual values.
         * @davidkeymer  & I have checked the LabVIEW code in the MuSR Geometry VI, which displays information about the orientation of MuSR.  It makes no reference to the cDAQ.
         * @davidkeymer  & I have also checked the LabVIEW code in the zero-field controller VI.  It does reference the cDAQ, but we can't find the relevant fields.  It needs a deeper look (it is very complex VI).
   1. If the zero-field controller detects a change in the voltage read by the 4th channel on the cDAQ, it will "press" the Go to Longitudinal or Go to Transverse button, as appropriate.  However, the user can simply press the Go to Longitudinal or Go to Transverse button to override what the cDAQ reads from the 4th channel.
   1. From an equipment safety point-of-view, MuSR should not be rotated if the CAEN High-Voltage is switched on.  Therefore, IBEX should provide an indicator to make the state of the CAEN High-Voltage clear to the user.  A simple LED saying "CAEN H-V switched on" would be sufficient.  This could be displayed on a MuSR Orientation OPI.  We could also display the state of the CAEN High-Voltage on the Banner.
   1. The MuSR Geometry VI has two text fields: Zero Field VI status and Magnet VI status.
      * the Zero Field VI status merely reflects the status of the zero field controller VI.  Is it in Manual mode or Automatic mode?
      * the Magnet VI status does what is says on the tin - it reflects the status of the magnet VI (Note: we need to be clear about which magnet).  However, the VI status is just a proxy for the status of the magnet PSU.  We should report the status of the PSU (it would be more useful than reporting the status of the IOC).

@Tom-Willemsen , @davidkeymer  - please let me know if there are any errors in my description.  If there are, I will correct them.

**Comment by KathrynBaker** [comment]
Regarding point 4 - the 4th channel should be considered by the Geometry VI - In the Timeout case, frame 0 in `MUSR Geometry - Front Panel.vi` it calls out to `MUSR Geometry - Check Switches.vi` which in turn calls out to `MUSR Geometry - Translate Switch Values.vi` which goes on to one of the Muon cDAQ functions. It then presses the buttons on the front panel (including a hidden manual button for when we aren't sure what the rotation is). At least, that's the version in my checkout, and should be the version in use on MUSR. The Zerofield VI does not use the 4th channel at all.

**Comment by kjwoodsISIS** [comment]
Hi Kathryn,

Thanks for the clarification.  I will update my comment with your clarification, so that we have a single correct statement.
Can you determine the actual threshold voltage values that indicate longitudinal/transverse mode?

Also, what does the hidden manual button actually do?   Does it just set the state to be longitudinal or transverse?  Or does it set it to be “unknown” (or “indeterminate”)?

Thanks,

Kevin

----------
Kevin Woods, Project Manager
Tessella
T: +44 (0)1235 446986
M: +44 (0)7734 059715
E: kevin.woods@stfc.ac.uk<mailto:kevin.woods@stfc.ac.uk>
