### ISSUE TITLE
LARMOR: Script Writing Application

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#518]
As a scientist, I want a simple application to help me write scripts, so that I can quickly and easily create new scripts.

'''Acceptance Criteria'''
1. I can start the script writing application.
1. I can construct my script.
1. I can save my completed script.

'''Notes'''
1. This ticket is a place holder for a number of individual tickets that will be be created for the actual implementation of the script writing application.
1. It has been suggested that the script writing application be a web-based application (so that users can write their scripts before arriving at ISIS).
1. The ability to cut-copy-paste segments of the script will be important.
1. Rob Dalgliesh & Leo Banuelos will consult with instrument scientists on ideas for the application.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 519.  Created by skn09965 on 2014-10-02T15:22:12, last modified: 2015-07-02T10:44:41_

**Comment by kjwoodsISIS** [comment]
_Trac comment by skn09965 on 2015-01-15 14:14:30:_

Postpone until after meeting to discuss Scripting Application (21st Jan 2015)

**Comment by kjwoodsISIS** [comment]
_Trac comment by skn09965 on 2015-02-12 10:56:25:_

In the first instance we'll demo the SNS script server.

**Comment by DominicOram** [comment]
Covered by Script Generator
