### ISSUE TITLE
Move more build utilities to ICP_Binaries share

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5180]
CMake has already been moved #5171 I believe there are other candidates that can be run from an unzipped central directory too: 

* maven
* perl
* wix
* OpenJDK

This would keep developers and build servers more in step

**Comment by DominicOram** [comment]
Duplicate of #5177 but this one also has openJDK. Other ticket already has acceptance criteria so will add openJDK to other ticket and close this as duplicate.
