### ISSUE TITLE
MERLIN/NIMROD: Twitiching piezo jaws - Fixed hardware

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5181]
Ian contacted us as he had fixed the issue of twitching motor readbacks via hardware fixes. 

In tickets #4953, #5000 we have made a few changes to stop excessive logging via the `ADEL` field, and, read back values via the `EDEL` field, of the motor record.

Ian was confident the twitiching should no longer be so prominent. I ensured the ADEL fields were all at sensible values (~0.2mm) on the jaws for both instruments. They have previously been increased but it looks like at some point they have been restored to the lower values (can't find a history of this). Therefore no actual changes were needed.

**Comment by KathrynBaker** [comment]
Before @Kevin-Woods-Tessella asks @aaron-long - how many points?
