### ISSUE TITLE
CRISP: DAE directory missing so unable to run either SECI or IBEX 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5187]
The c:\labview modules\dae directory is missing on CRISP, I am not sure when it disappeared? Without it neither SECI nor IBEX will work as it contains isisicp.exe

There is a copy of DAE in C:\Data\old\isisdae_backup_2019_02_11 from a previous upgrade - it is a year old, but i'm not sure how much may have changed though. @ChrisM-S do you have a more recent backup?

If you need to use the 2019 copy reffered to above then the procedure would be:
* copy the directory  C:\Data\old\isisdae_backup_2019_02_11\dae to  c:\labview modules\dae
* install the latest isisicp as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Upgrade-ISISICP

**Comment by ChrisM-S** [comment]
I can pull a copy out of the replicated machine from last cycle and mount if for copying (assuming it was there before Christmas!).

**Comment by ChrisM-S** [comment]
OK it's back, hopefully the DAE will not need upgrading as the files are now the same as before Christamas!

**Comment by JamesKingWork** [comment]
The upgrade script looked to complete as expected (according to the logs), IBEX seems to run as expected with the new updates and SECI also looks to run as normal.

**Comment by DominicOram** [comment]
Looks good to me

**Comment by kjwoodsISIS** [comment]
How many points was this?
