### ISSUE TITLE
SUPPORT: ZOOM: Dataweb not updating

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5188]
The Dataweb on ZOOM isn't updating, IS reported this at 10:55 on 10th Feb 2020

Acceptance Criteria

- [x] Zoom is updating
- [x] If possible error is found
- [x] Fix is deployed to Data web (please do after review)

**Comment by DominicOram** [comment]
Restarting JSON bourne fixed specific problem. Underlying cause believed to be https://github.com/ISISComputingGroup/JSON_bourne/pull/40

**Comment by JamesKingWork** [comment]
Fix deployed
