### ISSUE TITLE
EMU: zero field: "stable" indicator

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5190]
As an EMU instrument scientist I would like some changes to the zero-field system. These changes were discussed with the EMU scientists and the scientist who wrote the old ZF system.

Acceptance criteria:
- The "stability" pv should be called "At Setpoint" or similar, with values "Yes" and "No"
- The "At Setpoint" pv should have a value of n/a (or similar) when the controller is in manual mode, regardless of whether the measured field is close to the setpoint or not. This should **not** be an alarm state.

**Comment by mr-field** [comment]
Linked PRs:
- IOC: https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/8
- Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/311

**Comment by DominicOram** [comment]
Great work in general but can you modify the OPI to reflect the change too?

**Comment by mr-field** [comment]
I've renamed the reference in the OPI
