### ISSUE TITLE
Dashboard DB: corrections

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5192]
As an instrument scientist (on Polaris and maybe elsewhere) I would like the following corrections to my dashboard:
- Run time should display as `H:M:S` rather than just seconds
- Monitor counts should point at *accumulated* counts not the count rate

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/38

**Comment by KathrynBaker** [comment]
+1 from SANDALS
+1 from NIMROD

**Comment by KathrynBaker** [comment]
POLARIS can be updated 11/02/2020 between 09:00 and 10:00
SANDALS can be updated any time
NIMROD will confirm when

**Comment by kjwoodsISIS** [comment]
Is this a regression?

**Comment by KathrynBaker** [comment]
+1 LARMOR
