### ISSUE TITLE
SUPPORT: BUG: Dashboard DB Corrections

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5193]
As an instrument scientist (on POLARIS, SANDALS or NIMROD and maybe elsewhere) I have the following errors on my dashboard:

* My run time is displayed in seconds, not HH:MM:SS (see #5192 for the fix with ab associated PR)
* My monitor counts are now displaying the rate rather than the number of accumulated counts (see #5192 for the fix with ab associated PR)
* Sometimes my instrument is being labelled as NDXINST rather than INST (NIMROD was doing this but has returned to normal, SANDALS is still doing this) (#5196)
* In the value for Current / Total the Total should be rounded to 3 decimal places and not the nearest integer (#5195)

**Acceptance Criteria**
1. All the reported errors have a correction
1. Dashboards have been updated to reflect the appropriate corrections
1. There are tickets (or a single ticket) to create tests that would have avoided these errors and the associated support calls

**Notes**
1. This is likely to be an umbrella ticket as further bugs are noticed and reported, this ticket should be able to act as a snag list for what was missed, and therefore guide the creation of tests for expected behaviours in the future

**Comment by kjwoodsISIS** [comment]
Is this a regression?  If so, it would be worthwhile understanding why it happened.

**Comment by KathrynBaker** [comment]
My instinct is that there are regressions, hence my acceptance criteria of tests to avoid them and verify the information.

I would say that we missed some fine detail when we made the dashboard changes for the Muons.

4 reports so far from 3 instruments, I wonder how many haven’t noticed anything amiss yet. I did at least amuse the 2nd IS to report anything by already knowing about two of the bugs they wanted to report.

I will send a message at the end of today highlighting our awareness of these issues, and asking for reports of anything else that is wrong in dashboards, and asking when we can access instruments to apply fixes – with one final release planned for the next maintenance day, in the hopes that each instrument will have already had any of their commonly viewed fields corrected more urgently. I will also ask if any instruments prefer this depiction of the information (others may actually like to see run times in seconds for example).

**Comment by kjwoodsISIS** [comment]
Also, is this a pure client-side issue?  Or does it affect the server too?

**Comment by KathrynBaker** [comment]
Extra requirement added `Current/Total is now displayed as the nearest integer rather than the float value` based on further information from SANDALS/NIMROD

**Comment by JamesKingWork** [comment]
There is now a fix reviewed and in master for the monitor counts and run time in #5192

**Comment by JamesKingWork** [comment]
Current / Total ticket: #5195

**Comment by JamesKingWork** [comment]
Instrument name display ticket: #5196

**Comment by kjwoodsISIS** [comment]
@KathrynBaker , @JamesKingWork - the requirements of this ticket and #5195 now contradict each other.  Only one of these is correct.  Can you please resolve the conflict.

**Comment by KathrynBaker** [comment]
It’s on the list of things to look at – and we are aware of it, at the moment I’m collecting problems I’m told about – I have no idea if they are valid I’m trying to get the problems listed, and then do the triage.

**Comment by KathrynBaker** [comment]
@Kevin-Woods-Tessella I don't think we have anything that is actually contradicting at the moment - things have been corrected to all read as doing the same, and to do all that requires doing in an appropriate way.

**Comment by kjwoodsISIS** [comment]
Ah, I see - the Acceptance Criteria (above) have now been changed to be consistent with #5195.

**Comment by DominicOram** [comment]
Squish tests now added: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/33

**Comment by DominicOram** [comment]
Removing urgent as this just contains tests now

**Comment by JamesKingWork** [comment]
For this ticket, we are now just waiting on deploys. Tests have been implemented and there is a fix. There is also a ticket for the deploys. Should I make this ticket completed or leave it in review until deploys are confirmed successful?

**Comment by kjwoodsISIS** [comment]
How many points for this ticket?
