### ISSUE TITLE
Beam Off Day (26/02/2020) SUPPORT: Dashboard DB Bugs - deploy fix

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5194]
As someone supporting IBEX I would like to ensure that all instruments have a similar and appropriate dashboard configuration file, and that the reported bugs (see #5193) have been fixed on the instruments.

**Acceptance Criteria**
1. On a beam off day make sure that all IBEX instruments are updated to use a dashboard without the bugs listed in#5193:
- [x] ALF
- [x] CRISP
- [x] DEMO - Doesn't take neutrons, could delay
- ~[ ] DETMON - Doesn't take neutrons, could delay~ on version 5.6
- [x] EMMA
- [ ] EMU - Will have a different configuration as this is a muon instrument
- [x] ENGINX
- [ ] ENGINX_SETUP - Doesn't take neutrons, could delay
- [x] GEM
- [ ] HRPD
- [x] IMAT
- [x] INES
- [x] IRIS
- [ ] IRIS_SETUP - Doesn't take neutrons, could delay
- [x] LARMOR
- [x] LET
- [x] LOQ
- [x] MAPS
- [x] MARI
- [x] MERLIN
- [x] MUONFE - Doesn't take neutrons or muons, could delay
- [x] NIMROD
- [x] OSIRIS
- [x] POLARIS
- ~[ ] RIKENFE - Doesn't take neutrons or muons, could delay~ On 5.5
- [x] SANDALS
- ~[ ] SELAB - Doesn't take neutrons, could delay~ On 5.5
- [x] SOFTMAT - Doesn't take neutrons, could delay
- ~[ ] SURF~ on 5.5
- [x] TOSCA
- ~[ ] VESUVIO~ not needed on 5.6
- [x] ZOOM

**Notes**
1. Some of these will likely have been updated if requested earlier in the cycle
1. There may be other bugs so we should not prepare this too far in advance of the beam off day

**Comment by KathrynBaker** [comment]
Marked as impeded as there are still likely to be bugs found

**Comment by DominicOram** [comment]
To fix:
* Copy `EPICS\misc\upgrade\master\data\dashboard.db` into `\\{INST}\Instrument\Settings\config\{INST}\configurations`
* Restart INSTETC `console -M {INST} INSTETC` and `Ctrl+X`

**Comment by DominicOram** [comment]
There is a script in the private share `private_git_repositories\private_scripts.git` that can do the copy via the backdoor

**Comment by John-Holt-Tessella** [comment]
Db files copied across waiting for instruments to be in setup before restarting

**Comment by John-Holt-Tessella** [comment]
Instruments on list have been contacted with script to run they were running and we did not want to risk the data.

**Comment by DominicOram** [comment]
Ran the following script:
```
import genie_python.genie as g
from genie_python.utilities import dehex_and_decompress
import json

inst_list = g.get_pv("CS:INSTLIST")

inst_list = json.loads(dehex_and_decompress(inst_list))

for inst in inst_list:
    prefix = inst["pvPrefix"]
    try:
        time = g.get_pv(prefix + "CS:DASHBOARD:TAB:2:2:VALUE")
        format_ok = len(time.split(":")) == 3
        print("Inst: {}, Time: {}, Formatted ok: {}".format(prefix, time, format_ok))
    except:
        print("Inst {} not running".format(prefix))
```
It flags up HRPD as expected but it also appears that SANDALS still has the old time format, is this expected?

**Comment by DominicOram** [comment]
Turns out SANDALS is on a different client version. @Tom-Willemsen will look into this.

**Comment by DominicOram** [comment]
All instruments are now formatted correctly. I'm happy not to bother with support machines, many of them don't have the latest release anyway

**Comment by kjwoodsISIS** [comment]
It's complete, so it can no longer be impeded.
