### ISSUE TITLE
Dashboard DB: display instrument name correctly

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5196]
As an Instrument Scientist, I would like my instrument to be labeled without the NDX prefix e.g. NIMROD rather than NDXNIMROD.

This issue appeared on NIMROD and then dissapears. It continues to appear on SANDALS.

This ticket is to investigate why this has happened and work out a fix for it.

**Comment by KathrynBaker** [comment]
If you “switch instrument” in the client to your instrument and restart it then it should identify the instrument correctly.

This is a known error after a deploy, and either the step to switch instrument to the instrument you are on is missing from the update script, or undertaking that step was skipped is the best guess for this. NIMROD is now displaying correctly, and I have told Sabrina about the above method to potentially fix this, and to let us know if it persists after that change.

Therefore, checking the deploy script for that instruction should be enough at this point in time.

**Comment by DominicOram** [comment]
@Tom-Willemsen did you think it was part of https://github.com/ISISComputingGroup/ibex_utils/blob/1015a395c5e871b1ebbe2b424f2aa0939af3906d/installation_and_upgrade/ibex_install_utils/install_tasks.py#L1025 or somewhere else?

**Comment by Tom-Willemsen** [comment]
Yes, that's where I thought it was - but I seem to have misremembered...

**Comment by DominicOram** [comment]
Now part of script. For future reference this bug occurs because the instrument name is loaded from the client workspace. Installing a new client will wipe your workspace and the client will default to the name of your local machine.

**Comment by DominicOram** [comment]
Removing urgent as fix is under no time pressure

**Comment by kjwoodsISIS** [comment]
How many points for this ticket?

**Comment by JamesKingWork** [comment]
My bad there was a race condition there somewhere...
