### ISSUE TITLE
LSI Correlator: Add macros

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5198]
As a user I want to be able to change parameters of my IOC without editing the python code. This ticket is to allow the IP address, firmware revision and data file path to be changed as an IOC macro.

## Acceptance criteria:
 - [ ] IP Address can be set as macro
 - [ ] Firmware revision can be set as macro
 - [ ] Data file path can be set as macro
 - [ ] The way to do this is documented so that we can do it for other python IOCs

**Comment by DominicOram** [comment]
Implementation is obviously up to the developer but you could just do this as command line arguments passed into the python code?

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd said there is a program which creates a file with macro values filled out from the current config. There is an easy adjustment to make this output all current macros. @FreddieAkeroyd can you put the location on this ticket.

**Comment by FreddieAkeroyd** [comment]
the icpconfig module will parse the configuration, and has a function called icpconfigReport() that writes a summary to screen. A modified version of this function could easily be made to generate a macro list:
- see icpConfigEnvExpand.cpp and Makefile for how to build an executable
- create new function based on  icpconfigReport and icpconfigEnvExpand that takes an IOC name as argument and returns a string of macro values for that IOC. A single long line should be returned to be parsed, could be comma separated name=value, or maybe XML or json is better?
- command output can be written to an environment variable using e.g.
```FOR /F "usebackq delims=" %a IN ( `dir` ) DO ( set "B=%~a" )```
this avoids a temporary fie
- python program called by passing string as argument. Alternative would be to set an environment variable.

**Comment by FreddieAkeroyd** [comment]
Above PR should provide required functionality to get macros

**Comment by DominicOram** [comment]
@JamesKingWork it's my understanding this is now done, can we close it?

**Comment by JamesKingWork** [comment]
Yes it is done, for future reference docs are here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ioc-pcaspy#accessing-macros-on-start
