### ISSUE TITLE
EMU: investigate danfysik auto on/off failures

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5199]
As an EMU scientist I would like auto on off to work correctly. It is working inconsistently.

**Comment by FreddieAkeroyd** [comment]
After working with @Tom-Willemsen we implemented a partial fix by using a periodic scan and CA output link from the calcout. The issue looked to be related to the multiple CP triggers in the calcout, and after a brief discussion with Andrew Johnson may be related to https://bugs.launchpad.net/epics-base/+bug/1841634 and also to a recent tech-talk message by Mark Rivers https://epics.anl.gov/tech-talk/2020/msg00071.php

**Comment by Tom-Willemsen** [comment]
EMU have run a cycle with this as it is and this issue is not on their snags list. Taking this off pending tasks.

**Comment by davidkeymer** [comment]
Investigation in #5952

**Comment by JamesKingWork** [comment]
This issue was fixed here https://github.com/ISISComputingGroup/IBEX/issues/5952
