### ISSUE TITLE
IMAT: install epics/pixelman on new MCP W10 PC

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5200]
Anton will be visiting on 26/27 february to set up MCP, needs EPICS installing

### Acceptance Criteria

- system works
- system is documented

**Comment by FreddieAkeroyd** [comment]
Anton updated PC, software deployed, worked fine as far as i know

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Pixelman
