### ISSUE TITLE
GUI: Alert instrument scientist if motor and encoder are out of sync

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5201]
As of https://github.com/ISISComputingGroup/IBEX/issues/4449 we log the difference between motor and encoder steps. Part of that ticket was to alert the IS when they got out of sync. We should do that part of the ticket.

### Acceptance Criteria

   1. PV is shown on advanced motor panel
   1. Threshold for the alarm can be set by the instrument scientist
   1. There is a sensible default threshold

### Notes

   1. Default threshold should probably be a factor based on the maximum of the motor and encoder resolution.
   1. Consider adding a tooltip: when the scientist hovers over the LED (or whatever we use to signal the problem) display a tooltip recommending that the scientists contacts the Motion Control Group.
  1. Note that we don't want to worry the user or scientist and make them think they have lost position, they have just lost some motor steps that may indicate a future problem.

**Comment by DominicOram** [comment]
+1 from the motion steering group and from larmor IS

**Comment by FreddieAkeroyd** [comment]
Acceptance criteria 1. suggests putting this in the alarms view, the user would then see this and may think there is a problem when there isn't necessarily one at that point. The information should be available for the IS and motion control, but not the user.

**Comment by DominicOram** [comment]
Agreed, removed

**Comment by DominicOram** [comment]
Could be useful for SANS2d too

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-galil/pull/37
https://github.com/ISISComputingGroup/ibex_gui/pull/1134
