### ISSUE TITLE
SUPPORT NIMROD: Jaw directions need to be fixed

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5202]
The upper jaw is connected to the lower motor and vice-versa for jaw 6, this needs fixing in the config file.

```
$(IFIOC_GALIL_03) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS6:,mXN=MTR0307,mXS=MTR0308,mXW=MTR0305,mXE=MTR0306")
```

should be 
```
$(IFIOC_GALIL_03) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS6:,mXN=MTR0308,mXS=MTR0307,mXW=MTR0305,mXE=MTR0306")
```

Then the jaw centre needs to be set to -ve jaw centre.

Do on beam off day in conjunction with instrument scientists

**Comment by John-Holt-Tessella** [comment]
Done. Before:
![image](https://user-images.githubusercontent.com/7570055/75341199-d6765880-588b-11ea-8d93-b6cbbd66b642.png)

after

![image](https://user-images.githubusercontent.com/7570055/75341210-dbd3a300-588b-11ea-8771-be8c466dffbb.png)

**Comment by Tom-Willemsen** [comment]
North/south axes on jaws 6 have been swapped correctly.

However, it appears that we're forgotten to swap east/west (the whole jaw set is wired back-to-front, not just north/south). New ticket at https://github.com/ISISComputingGroup/IBEX/issues/5276 for east/west after discussion with @John-Holt-Tessella
