### ISSUE TITLE
SUPPORT: EUROTHERM: OPI unresponsive

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5203]
As a Eurotherm user on SANDALS (and possibly elsewhere), I want the OPI to the Eurotherms to be responsive.

**Acceptance Criteria**
1. There is documentation explaining the situation - both the various ways through it and what is going on
1. We have workarounds/a fix for this cycle
1. We have longer-term workarounds and fixes
1. We have tests listed (manual system at the very least) which avoid this reoccurring

**Notes**
1. To recreate the error(s):
   1. Open the Eurotherms OPI from the device screen - this is taking a long time, potentially longer than normal
   1. At this point the graph should be ticking along, updating with time, and it should be possible to provide a setpoint. (Note that for SANDALS which triggered this call this required refreshing the OPI first)
   1. Open the graph tools
   * Change the zoom on the Y axis, the X axis stops updating, and it is no longer possible to provide a setpoint sometimes
   * Autoscale the graph - sometimes this works and everything starts updating in expected fashions, sometimes it doesn't
   * Select the arrow explicitly - sometimes this works and everything starts updating in expected fashions, sometimes it doesn't
   * Attempting to change the setpoint causes the graph to alter

**Comment by John-Holt-Tessella** [comment]
Fix seems to be to put the graph component at the front (in the designed ordered by) menu.

https://github.com/ISISComputingGroup/ibex_gui/pull/1051

thank you @JamesKingWork

**Comment by Kevin-Woods-Tessella** [comment]
Do we understand what changed?  (i.e. what change exposed this bug?)

**Comment by John-Holt-Tessella** [comment]
No, probably update in CSS studio but ticket #5205 should find the cause.
