### ISSUE TITLE
gateway crashing

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5204]
gateway is crashing on zoom if connected to remotely. Connected debugger, but unclear as in release mode. May try replacing with static debug build later. However gateway on my desktop is crashing with
```
[Tue Feb 11 16:21:50 2020] Feb 11 16:21:50 Clean dead PV from PV list failed for pvname=IN:LOQ:CS:SB:sample_changer_scan_intensity:RC:SUSPEND_ON_INVALIDÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ.
```
which i am looking at - maybe pvname is too long

**Comment by FreddieAkeroyd** [comment]
This issue is likely fixed by https://github.com/ISISComputingGroup/EPICS-gateway/pull/2

**Comment by FreddieAkeroyd** [comment]
Gateway update now merged, given ZOOM is suffering we could update the gateway there using the latest windows-x64-static build from jenkins. It is only the external gateway that is suffering, the block gateway is working OK I believe. So there is a risk of breaking the block gateway. One option might be to deploy the new gateway.exe as gateway2.exe and change the start_gateways.bat script to run gateway2.exe for the external gateway (also change  the taskkill line in stop_gatweways to look for gateway2.exe)

**Comment by FreddieAkeroyd** [comment]
Plan to update ZOOM on beam off day

**Comment by FreddieAkeroyd** [comment]
Gateway on ZOOM not crashed since 11th March when it was updated

**Comment by kjwoodsISIS** [comment]
Completed tickets should remain in Review Complete column until after Sprint Review.  Re-opening ticket until Sprint Review for 2020_04_02 is complete.
