### ISSUE TITLE
Rename RC:SUSPEND_ON_INVALID to something shorter

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5207]
EPICS has PV name length restrictions, and using "SUSPEND_ON_INVALID" reduces available characters by more than is really necessary (and has lead to a EPICS gateway crash with a long block name #5204)

### Acceptance criteria

- SUSPEND_ON_INVALID is renamed to something like SOI so the underlying PV used by Ibex would look like e.g.
```
IN:LOQ:CS:SB:sample_changer_scan_intensity:RC:SOI
```
rather than
```
IN:LOQ:CS:SB:sample_changer_scan_intensity:RC:SUSPEND_ON_INVALID
```
- ~Find out what the longest pv name allowed is~
- Check no internal calc exceed this
- See if this cures #5197

**Comment by mr-field** [comment]
Linked PRs:
- Change PV name: https://github.com/ISISComputingGroup/EPICS-RunControl/pull/8
- Update constant in BlockServer: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/276
- Update constant in GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1084

**Comment by RaiBishal** [comment]
Unable to reproduce the issue https://github.com/ISISComputingGroup/IBEX/issues/5197 in this ticket. It could be due to we are out of cycle at this moment.
