### ISSUE TITLE
ALL?: Lots of extra drives mapped on some instrument control PCs

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5208]
As an instrument scientist I'm confused by a large number of "extra" mapped drives on my control PC this cycle, many appear to be pointing to the same place, mainly letters later on in the alphabet.  On trying to disconnect, I often get a message saying that files are open on the drive so I'm not sure about doing this in case the files are in use somehow.  How can I tidy these up?

Acceptance Criteria
===
1. At the end of the upgrade script the only (mapped) drives I see are D:, O:, U: and possibly Z:, Y:, etc. if I have instrument specific mappings in place (not generally advisable).
1. If mapping don't exist then mapping are created
1.  Fixed Drives C:, P:, and sometimes T: are not upset in the process

Notes
===
It looks like this may be due to a problem in the install script?

**Comment by John-Holt-Tessella** [comment]
Do you have a list of the drives that should be mapped on the machines? We should add this to the upgrade script so it can check and unmap.map the unneeded drives.

The extra drives are probably caused by the script dying and therefore not popping a drive. We should fix this.

**Comment by ChrisM-S** [comment]
+1 (from ZOOM), I sorted Larmor and James sorted CRISP.
Re. the above, The mappings on Win 7 seem to need to be done manually from the active session, so cannot do remotely from a script.

`for %n in ( S: T: V: W: Y: Z: <kitpathhere>  ) do @net use /d /y %n`

pasting the above command should remove the random links, <kitpathhere> should be substituted for the UNC link to the internal kits area (which is mounted without a drive letter).

**Comment by Tom-Willemsen** [comment]
The upgrade script should automatically demount the drives

**Comment by Tom-Willemsen** [comment]
we'll just make sure that the script does popd's for every pushd, regardless of whether the script errored or not

**Comment by FreddieAkeroyd** [comment]
Is it documented anywhere why we need to do a pushd in *define_latest_genie_python.bat* ? I removed the pushd and just used a UNC path (so no mapped drive letters at all) and the install looked to go through OK with just
``` 
set KITS_ICP_PATH=\\isis.cclrc.ac.uk\inst$\Kits$\CompGroup\ICP
```
in that file. Maybe there is another issue later? If we don't need to do a pushd, that simplifies having to try and handle an installation failure so i think we should find out if, or why, we need *pushd*

**Comment by John-Holt-Tessella** [comment]
If it works it is good, if it fails on an instrument then we can always revert it after the first install. I don't think it will be documented unless it is on the commit comment.

**Comment by FreddieAkeroyd** [comment]
Installed OK on NDXDEMO using UNC path with pushd/popd removed
