### ISSUE TITLE
EMU: running stalls after one run

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5211]
When back in SECI, EMU were able to do one run but it hung when a second was started.

Various analysis showed that this was an sqlite error hanging SECI, the number of columns in the selog database table had changed and were no longer compatible.

More investigation indicated this happened on a run end, and was due to Open GENIE logging some messages into the database. Open GENIE is 32bit and so activated an older COM component to do the insert, this component had not been updated for years but neither had the database table structure so it had gone unnoticed.

Temporary solution was to remove this component, Open GENIE is currently giving an error message.  Need to rebuild database support for 32bit.

**Comment by FreddieAkeroyd** [comment]
Files rebuilt, the following needs to be done when logged onto NDXEMU

* Kill seci
* Browse to ICP\ISISICP\selog_x86 on kits$
* Double click on deploy.bat
* Check there are no copy error (should be 7 files copied to each of Release and Debug)
* Restart seci

On an END there should no longer be a red error message in the Open GENIE window

**Comment by davidkeymer** [comment]
Koji has just phoned me to say that now is a good time to apply the fix and so I shall carry out the instructions above.

**Comment by FreddieAkeroyd** [comment]
As discussed with David and Chris, regsvr32 failed on the library as it had the wrong msvcr10.dll - this was a leftover of when i tried to get opengenie to use the 64bit version via a COM surrogate. I have restored the 32bit DLLS and regsvr32 now works on the dll

**Comment by FreddieAkeroyd** [comment]
Is working on EMU, however rather than build a 32bit version it may be better to run the 64bit component out of process to allow use by the 32bit process. See #5224. Otherwise this ticket is complete.

**Comment by Alistair-McGann-Tessella** [comment]
EMU has been running in SECI since this ticket, so I'm comfortable this fixed the problem. #5224 will provide the long-term solution to this issue, so there isn't a need for more thorough documentation for this fix.
