### ISSUE TITLE
SUPPORT: Larmor can't lint scripts

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5213]
Larmor can not run a script because they refuse to lint. The problem appears to be that the linter can not see the function exposed by the scan library. 

Acceptance

Disable the linter for load on larmor. 
Long term: make scan library compliant see #5214

**Comment by DominicOram** [comment]
@John-Holt-Tessella's hotfix here was to change the line https://github.com/ISISComputingGroup/genie_python/blob/9f3037b1451caccde63eb94ae5792e6fc1f3cd79/Lib/site-packages/genie_python/genie.py#L1255 to read `check_script=False`. This seems like a good hotfix but something more permanent is required in linked ticket
