### ISSUE TITLE
MUONFE: UQ14A Not communicating

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5227]
The PSU supporters changed the Genesys for UQ14A, and realised that MUONFE couldn't be read the PSU information - the address in the PSU was incorrect, this was altered and the IOC sprang into life

**Comment by DominicOram** [comment]
Updated docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TDK-Lambda-Genesys otherwise all good
