### ISSUE TITLE
GEM: Synoptic not showing motor details

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5230]
The PVs assigned in the synoptic were looking at GEMJAWSET, not JAWMAN - they now look at JAWMAN

**Comment by DominicOram** [comment]
I don't think there's much more to learn here, calling it done.

**Comment by DominicOram** [comment]
Following a rather round about route of Chinese whispers it turns out that this hasn't been done for all the synoptics on GEM, which I should have checked when I reviewed this. I will do this via the backdoor and send them an email about it.
