### ISSUE TITLE
ZOOM: SCIMAG 3D not behaving as expected

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5231]
The system was not behaving in a way that was expected, after a bit of looking this was realised to be some race conditions, another one was found later and some defensive programming techniques suggested

**Comment by DominicOram** [comment]
Don't think there's much more to learn here.

**Comment by kjwoodsISIS** [comment]
Race conditions where?  In our code?  In a scientist's script?

**Comment by DominicOram** [comment]
Apologies, I asked Kathryn similar questions before I closed the ticket and should have commented here. The issue was a race condition in a scientists script and was a specific case that I don't think we can learn much more from in terms of teaching scientists to avoid it.

**Comment by kjwoodsISIS** [comment]
OK.  Thanks for clarifying.
