### ISSUE TITLE
HIFI: Triton Setups

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5232]
Whilst HIFI is a SECI instrument I am including these here as a reminder for mention or discussion during sprint review as the same problem would occur under IBEX.

Despite the correct name, the LS327 was not connecting - the device needed to be in DHCP mode

**Comment by DominicOram** [comment]
I've added a note to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Lakeshore-372 to ensure it is in DHCP mode

**Comment by KathrynBaker** [comment]
Good call, thank you.
