### ISSUE TITLE
ENGINX: Eulerian Cradle set up

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5233]
The Eulerian cradle was returned to ENGINX and needed to be set up again - this time the IOC worked, although there were some questions about the electro-mechanical behaviour of the inner axis (a positive move went negative, a negative move went negative very slowly). The blocks had to be returned to looking at appropriate PVs, and the setup verified as correct.

**Comment by DominicOram** [comment]
I don't think there's much more to learn here, calling it done.
