### ISSUE TITLE
installation scripts: use robocopy in all places 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5240]
Currently it takes 10 minutes to install all of an EPICS build, and the same time to install genie python. EPICS is installed using robocopy, python and the client gui are installed using xcopy.

acceptance criteria

- all install scripts use robocopy
- Time for install_latest_client_server_genie_python  job decreases

notes

- xcopy currently copies new files, but does not remove old files (it didn;t have a mirror option). Is there any reason not to use a mirror option on genie python and client?

**Comment by Tom-Willemsen** [comment]
When doing the dependency updates for Python 3 I found that copying a zip archive and extracting locally was *much* faster than either robocopy or xcopy over the network. Given that the client and python are both relatively small (but with lots of files) might this be a better approach?

**Comment by FreddieAkeroyd** [comment]
Out of interest, did you use multi-threaded robocopy? But yes, creating a zip at the end of the install sounds a good idea. I'm a little suspicious that genie python may get installed multiple times, one of the nice things about robocopy is that it only copies changed files, but it may be the zip still beats this (or we can check the installed python version before unzip?)

**Comment by FreddieAkeroyd** [comment]
Thought of another interesting option for EPICS, maybe applicable more widely. We already create a .git repo in the distribution and efficiently git pack this (it is 86 files in all). So we could copy the packed .git repository and git checkout locally, or maybe even point at the network share and git checkout directly? I'm not sure when and where the latter would unpack, so it might not be very efficient, but the former is worth an investigation

**Comment by FreddieAkeroyd** [comment]
Speed comparison with genie python on NDXDEMO:
7zip from zip on archive - 5 minutes
7zip from zip copied locally 3.5 minutes
multi-threaded robocopy from archive - 3 minutes

**Comment by ChrisM-S** [comment]
Just might be worth running sysinternals `contig.exe -a -s` on the copied folder at the destination to confirm that the files arrive without being fragmented.  I suspect that most will not, but if there are any large chunks (like a database?) it could just be that this happens.

**Comment by FreddieAkeroyd** [comment]
We should be OK in theory - according to https://social.technet.microsoft.com/Forums/windowsserver/en-US/9b35e0db-d2e5-4efe-bc4b-d4e2dd7a390d/will-multithreading-in-robocopy-fragments-large-files?forum=winserverfiles "As RC does pre-allocation there should be little to zero fragmentation (because of MT, other things like natural fragmentation because of a say delete still take place)."
