### ISSUE TITLE
Scripting: Make matplotlib work in python 3

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5241]
As a user I want to be able to make plots in the scripting perspective, and for them to appear in the GUI. In #5175 we have found that plotting in the scripting perspective now blocks the python console, preventing further commands being submitted.

We use a custom WebAgg backend to make python plots in the IBEX scripting perspective. Both matplotlib and tornado have had major version revisions after upgrading to python 3. An initial investigation shows that  `app.listen()` in ibex_web_backend.py is causing the blocking.

We started to change the the initialization method used in the ibex web backend from number 1 in the tornado documentation to number 2:
https://www.tornadoweb.org/en/stable/httpserver.html#http-server

Acceptance criteria
- [x] Plots can be produced in the IBEX scripting perspective
- [x] These plots do not block the the python console
- [x] Matplotlib ibex backend not broken in python 2

**Comment by Alistair-McGann-Tessella** [comment]
PRs:
squish test: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/37
genie python: https://github.com/ISISComputingGroup/genie_python/pull/229

**Comment by John-Holt-Tessella** [comment]
Can not be mergeed until update dependencies and #5157

**Comment by JamesKingWork** [comment]
> Can not be mergeed until update dependencies and #5157

Update dependencies #5152 is done
