### ISSUE TITLE
Script Generator: Loading experimental parameters system tests

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5242]
As a developer, I would like the script generator to be sufficiently tested.

This was not possible as part of the original loading experimental parameters ticket (#5107) because a system testing setup had not been created for the script generator (#5090 Was not complete yet).

Acceptance criteria:

- [ ] The acceptance criteria of #5107 are tested in squish

**Comment by DominicOram** [comment]
Fixed in https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/53
