### ISSUE TITLE
Script Generator: Generate script as given name system tests

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5243]
As a developer, I want the script generator to be sufficiently tested.

This could not be done as part of the original ticket (#5118) because there was no testing setup for the script generator (#5090 was not complete yet).

Acceptance criteria:

- [ ] The acceptance criteria of #5118 is tested in squish tests

**Comment by DominicOram** [comment]
Fixed in https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/52
