### ISSUE TITLE
DEPLOY: Client and server are started correctly by the upgrade script using local resources.

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5254]
As a user I need to be able to use the instrument after a deployment. It was seen in #5253 that pyDev was unusable on LOQ after a deployment. It was found that the genie_python in the scripting perspective was trying to load modules from the network share rather than locally. This was fixed by restarting the client.

We think this is happening because the client was started from the same terminal that the upgrade script was run in, so inherits a 'dirty' environment. Something similar has also been seen during an LET upgrade. This ticket is to prevent the client from being started with the environment variables set in an upgrade terminal.

Possible implementations:
1. Stop the IBEX client from being spawned in the upgrade script, make this a manual process
1. Spawn the IBEX client from the upgrade script, but without the environment variables which are causing trouble

Acceptance criteria:
- [ ] After a deployment, genie_python methods in the scripting perspective called from the local deployment, not a network share.

**Comment by KathrynBaker** [comment]
#5229 is a similar problem from a different location, this time within the server of IBEX, relating to a python based IOC so this might not be limited to the client, and is worth bearing in mind when looking into this issue.

**Comment by FreddieAkeroyd** [comment]
Yes, I think it applies to any process started from the same window as the upgrade. So the upgrade needs to reset its environment properly.

**Comment by FreddieAkeroyd** [comment]
probably needs an extra setlocal scope - setlocal can be nested

**Comment by RaiBishal** [comment]
I believe this issue has been fixed in this commit. 
https://github.com/ISISComputingGroup/ibex_utils/commit/4958d275f73f7b538f18ff771fb6273894f9e686#diff-d326a5fb618c8b6960ab861723c5dbdf
