### ISSUE TITLE
ICEFRIDGE: Forward links do not work on non-process passive record

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5258]
After investigating [#5257] I noticed that there are a number of instance in this record where a forward link is used with the intention to process a record (or record chain). However in all instances these forward links are set to records that SCAN. Therefore (as per the [docs](https://wiki-ext.aps.anl.gov/epics/index.php/RRM_3-14_Concepts#Forward_Links)) these will not actually work as desired. These records end up with long delays (dependant on a 10 second SCAN) and are sluggish.

This can be fixed by forward linking from the SP record to a passive `dfanout` record that has `field(DOL, "1")` and `field(SELM, "All")` set, and writes to the output records `<name>.PROC` field in order to force reprocessing. For example:
```
record(dfanout, "$(P)LS:_VLTG:RANGE:UPDATE_CHANNELS")
{
    field(DESC, "Update the CH5 & CH6 voltage values")
    field(SCAN, "Passive")
    field(DOL, "1")
    field(SELM, "All")
    
    field(OUTA, "$(P)LS:VLTG:RANGE:CH5.PROC")
    field(OUTB, "$(P)LS:VLTG:RANGE:CH6.PROC")
}
```
----
After a discussion with Freddie he noted that a more robust approach (from what I said above) is to instead make your channels `Passive` and have a `fanout` record to process them in sequence, such that you guarantee the processing sequence. You can then also use forward links on this records when needed to successfully process them if required. 

## Acceptance Criteria
- [ ] Records are updated to use `dfanout` to reduce lag in processing updates

**Comment by Alexandru-Dascalu** [comment]
Perhaps a better solution should be to have the readback passive and use a bo record that has active SCAN and that has a forward link to the readback, like in https://github.com/ISISComputingGroup/EPICS-kepco/blob/master/kepcoApp/Db/kepco.db#L76 .

**Comment by KathrynBaker** [comment]
Given that the Ice Fridge is currently retired, this and any other changes can be revisited when there is a need to do so
