### ISSUE TITLE
HIFI Cryomag: switch ramp targets and rates mid-ramp

### ISSUE THREAD

**Issue by ChrisColeExpControl** [ISISComputingGroup/IBEX#5259]
As an instrument scientist, I would like the new HIFI Cryomag IOC to automatically change ramp rates past certain thresholds when ramping. When a ramp is specified, the IOC should check the start and end points against the ramp file and construct, then execute, appropriately sloped ramps.

Acceptance criteria:
 - [x] When ramps are started, they are split into a series of ramps of the form star point -> [ramp file boundary] * n -> end point
- [x] All ramps have the apropriate rate at each point of their ramping
~[ ] This would also be the best time to add a change to the emulator where ramp rates do not suddenly change, but gradually change to the correct rate (as seen on real hardware, may need to confirm acceleration rates instrument scientists).~
- [x] IOC behaves appropriately about zero and for negative fields

**Comment by ChrisColeExpControl** [comment]
PRs:

[Tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/319)
[Emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/74)
[Support](https://github.com/ISISComputingGroup/EPICS-Cryosms/pull/11)

**Comment by John-Holt-Tessella** [comment]
Did you need to add code for acceptance criteria:
- This would also be the best time to add a change to the emulator where ramp rates do not suddenly change, but gradually change to the correct rate (as seen on real hardware, may need to confirm acceleration rates instrument scientists).

**Comment by John-Holt-Tessella** [comment]
On my machine OUTPUT is in link invalid alarm

**Comment by John-Holt-Tessella** [comment]
Notes for tests:

- set up emmulator.
- monitor `camonitor %MYPVPREFIX%CRYOSMS_01:OUTPUT %MYPVPREFIX%CRYOSMS_01:MID:_SP %MYPVPREFIX%CRYOSMS_01:RAMP:RATE:_SP TE:NDW1798:CRYOSMS_01:RAMP:STAT TE:NDW1798:CRYOSMS_01:RAMP:RATE`
- set `caput %MYPVPREFIX%CRYOSMS_01:MID:SP 4000`
- set `caput %MYPVPREFIX%CRYOSMS_01:START:SP 1`

Rates are in C:\Instrument\Apps\EPICS\support\cryosms\master\ramps\test.txt and are in Tessella
