### ISSUE TITLE
Python 3: Implement new import mechanism

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5262]
As a developer, I would like to not do `from * import *` for every instrument script because that causes namespacing issues and isn't good practice. I would like to use the mechanism documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/instrument-scripts#future-new-mechanism which seems more sensible.

Acceptance criteria:

- [x] Configs are updated to use the new mechanism
- [x] ConfigChecker scripting directory tests are updated to reflect this new mechanism
- [x] Instrument scripts are updated to work
- [x] Appropriate documentation for scientists created

**Comment by Tom-Willemsen** [comment]
- [X] ALF
- [X] CRISP
  * No inst scripts
- [X] EMMA-A
- [X] EMU
  * Already on new style
- [X] ENGINX
- [X] ENGINX_SETUP
- [X] GEM
- [X] HRPD
- [X] IMAT
- [X] INES
- [X] IRIS
  * Duplicated definition of `diff` needs investigation/asking scientists
- [X] IRIS_SETUP
  * Duplicated definition of `diff` needs investigation/asking scientists
  * Has duplicate definitions of most functions between iris_routines.py and iris_routines_new.py
- [X] LARMOR
  * LARMOR don't appear to use instrument scripts
- [X] LET
- [X] LOQ
- [ ] MAPS
- [ ] MARI
- [ ] MERLIN
- [ ] MUONFE
- [ ] NIMROD
- [ ] OSIRIS
- [ ] POLARIS
- [ ] RIKENFE
- [ ] SANDALS
- [ ] SELAB
- [ ] SURF
- [ ] TOSCA
- [ ] VESUVIO
- [ ] ZOOM
