### ISSUE TITLE
BUG: Fix interactions where mbbo value fields have been redefined for an ENUM format converter

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5263]
This bug was discovered via the IOC system tests after updating dependencies. The effect is that in an mbbo where the fields `ZRVL,...,FFVL` have been redefined, on convert, the `ZRVL,...,FFVL` values are sent as opposed to `VAL`'s. See [documentation](https://wiki-ext.aps.anl.gov/epics/index.php/RRM_3-14_Multi-Bit_Binary_Output) under "Record Processing".

The pattern which no longer works is:

An mbbo with defined  `ZRVL,...,FFVL`, i.e., 
```
record(mbbo, "PV_NAME")
{
	field(OUT, "@DEVICE.proto setVoltage $(PORT)")

	field(ZRVL, "1")
	field(ONVL, "2")

	field(ZRST, "2.00 uV")
	field(ONST, "4.00 uV")

}
```
and an associated function with an ENUM format converter
```
setVoltage {
   out "%{01|02}";
}
```
where writing 1 to the mbbo results in the ENUM format converter processing a 1, which corresponds to the second (02) string in the ENUM.

From [#5257] I had investigated other records that had the same pattern using `find . -iname "*.db" -exec grep -H "ZRVL, \"1" {} \;`, however we ideally want to check for any records that redefine and `{index}VL` fields other than their defaults and ensure we ensure they work and fix as required.

### Acceptance criteria

- [ ] MBBO's with this pattern have been identified
- [ ] Records that are broken have been fixed
- [ ] We have documented why this is suddenly an issue, and what exactly has changed in EPICS.

### Notes

- We should not be redefining the MBBO values from their defaults (0,15) unless required.
- DEMO has a build from ~28/01 which is dependency update and drivers such as the `icefrdge` had tests that pass. Kits also have static builds from Jan that can be used to test on.

**Comment by Tom-Willemsen** [comment]
We should ask on tech-talk whether this is an expected behaviour change.

**Comment by Alexandru-Dascalu** [comment]
I have added a trace mask to the st.cmd and found that when running the valid value tests (not the ones for testing invalid values) for the Lakeshore heater range and voltage range on the new EPICS build, the voltage range test fails because the IOC sends the value 3 instead of 2 to the emulator. The heater range test still passes.

For the voltage range, I used an input of "6.32 uV" , which is the value of ONST. According to the current EPICS mbbo record reference documentation, the given value should be matched with the string in ONST, which would make the VAL field be 1 (index between 0 and 15), which would make the RVAL field be set to 2, which is the value in ONVL. The value of RVAL should then be sent to the device. However, looking at the devsim log after putting a trace mask shows us that instead the mbbo record writes 3 to the device. If I run the same tests on an old PICS build, before the dependency updates, the tests pass and the IOC sends 2 to the device.

I have also discovered that on the new EPICS, build, the tests pass if in the protocol file I replace the %{01|02|..|12} formatter with a %d formatter.

The heater range test appears to be unaffected because the ZRVL, ONVL, TWVL, etc. are set to 0, 1, 2, etc., so the index matches with the value.

**Comment by Alexandru-Dascalu** [comment]
@FreddieAkeroyd said they might have changed something in EPICS base, in Stream Device or in the mbbo record. He said they may have changed something so it did what the documentation said it should, or changed both the behaviour and the documentation. Unfortunately, old versions of Stream Device Documentation can still be found online.

**Comment by Alexandru-Dascalu** [comment]
Confusingly, on the new EPICS build, and on the master branch, if you use caput to write to the voltage range setpoint with a string, the readback will return that exact string. But on the same build the test fails if it writes that same value.

https://github.com/ISISComputingGroup/genie_python/blob/fd8053e90354c106a5222cfa2b3fc8d679e1d8b5/Lib/site-packages/genie_python/genie_cachannel_wrapper.py#L278 is a method in genie python that replaces string input with the corresponding index.

We should investigate why on the master branch writing using a caput works, but the tests fail. It may be that the above genie python method no longer works correctly, and we should know why.

**Comment by DominicOram** [comment]
The code that made this change was in StreamDevice [here](https://github.com/paulscherrerinstitute/StreamDevice/commit/ae6ebc410693cae1cc890c159dbff89c5415d08c#diff-5c4b88ab0722d03f9598f5d1ca35743f). It has now resulted in the MBBO and MBBI having non symmetric behaviour in  StreamDevice, see ENUM format [here](https://paulscherrerinstitute.github.io/StreamDevice/mbbo.html) and [here](https://paulscherrerinstitute.github.io/StreamDevice/mbbi.html). @FreddieAkeroyd is going to chat to the original developer about why these are asymmetric and whether it should be changed. I will go through our codebase and make sure we're not hitting the problem anywhere else and write a note on the wiki.

**Comment by DominicOram** [comment]
Given the above it's only required to change in IOCs we use and that have `mbbos` connected to `StreamDevice`. Using the regex `(field\().*.*(VL).*.*(\))` (which is probably much more greedy than required) found that we use `ZRVL` etc. on the following dbs:
* `FINS\zoom-vaccum.db`: Soft channel
* `motor\XPSPositionCompare.db`: Asyn channel, unused at ISIS
* `motor\XPSAuxAi.db`: Asyn channel, unused at ISIS
* `optics\xia_slit.db`: Soft channel, unused at ISIS
* `wbvalve.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `std\userMbbos.db`: Soft channel, unused at ISIS
* `tti355.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `ip\TSP.db`: Asyn channel, unused at ISIS
* `motor\trajectoryScan.db`: Soft channel, unused at ISIS
* `tpgx6x.template`: Soft channel
* `ip\TPG261.db`: Asyn channel, unused at ISIS
* `pva2pva\testpvif.db`: Soft channel, unused at ISIS
* `testOutputReadback.db`: Asyn channel, unused at ISIS
* `TestGP2Camera.db`: Asyn Channel
* `asyn\testErrors.db`: Asyn channel, unused at ISIS
* `base\testCaProvider.db`: Soft channel, unused at ISIS
* `asyn\testAsynPortDriver.db`: Asyn channel, unused at ISIS
* `ether_ip\test.db`: EtherIP channel, unused at ISIS
* `Tektronix_DMM_4050.db`: Asyn channel
* `optics\table.db`: Soft channel, unused at ISIS
* `ip\SR570.db`: Soft channel, unused at ISIS
* `split_jaws_header_vertical.db`: Soft channel
* `sp2xxSetting.db`: Soft channel
* `sp2xx.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `SM200_extra.db`: Asyn channel
* `ethercat\SLAVE.template`: Asyn channel, unused at ISIS
* `SKFChopper.db`: Soft channel
* `simple.db`: Soft channel
* `optics\SGM.db`: Soft channel, unused at ISIS
* `std\selector.db`: Soft channel, unused at ISIS
* `SCHINDR.db`: Asyn channel
* `autosave\save_restoreStatus.db`: Soft channel
* `rotating_sample_changer.db`: Soft channel
* `mca\RontecXFlash.db`: Soft channel
* `RIXSCamPVDefinitions.template`: Asyn channel, unused at ISIS
* `RIXSCam.template`: Asyn channel, unused at ISIS
* `optics\qxbpm.db`: Soft channel, unused at ISIS
* `qepro.template`: Asyn channel
* `profileMoveController.template`: Asyn channel
* `pr4000.db` and `pr4000chan.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `pixelman.db`: Asyn channel
* `Phytron_I1AM01.db`: Asyn channel
* Various cameras in areadetctor: all asyn and mostly unused
*  `Pelco_CM6700.db`: Soft channel
*  `OmegaDP41.db` and `Omega_DP41.db`: Soft channel
*  `DELFT\NSV.db`: Asyn channel
* `nGEM.db`: Asyn channel
* Various templates in ADCore: Asyn channels
* Varios nanodac DBs: Asyn channels
* `std\Nano2k.db`: Soft channel
* `MK2CHOPR.db`: Soft channel
* `Mezflipr_common.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `MercuryPressure/Level/Temp`: Asyn channel
* `LINKAM95.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `lakeshore460.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `Lakeshore340.db`: Maps `ZRVL` to `1` but passes through in proto
* `Lakeshore33x.db`: Soft channel
* `knr1050.db`: Soft channel
* `keithley_2001_init.db` & `keithley_2001_buffer.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `Keithley2kDMM.db`: Soft channel
* `jsco4180.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `ITC503.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `ips.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `indfurn.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `ieg.db`: Maps `ONVL` to `1` etc. so not actually an issue
* Various icb* files in mca: Asyn channels
* Various HVCAEN DBs: Own channel type
* `Hameg_8123.db`: Asyn channels
* Various galil DBs: Asyn channels
* `FZJDDFCH.db`: Maps `ZRVL` to `1` but passes through in proto
* `fermchop.db`: Soft channel
* `edwardsTicGauge.db`: Soft channel
* `dma4500m.db`: Maps `ZRVL` to `0` etc. so not actually an issue
* `DFKPS_calibrated.db`: Soft channel
* `devNeocera.db`: Maps `ZRVL` to `3` but passes through in proto

**Comment by DominicOram** [comment]
Re-pointed based on the review just being check a few of those that I mentioned and make sure I got them right. I think @FreddieAkeroyd's discussion with Dirk can be done outside of this ticket.

**Comment by Alexandru-Dascalu** [comment]
If the mbbo record defines ZRVL to 0, and so on, and there is an enum converter used in the protocol, then the redefinition is pointless and should likely be removed.

In addition, for several IOCs you say that they are used as Soft Channel or as an Asyn Channel, but do not mention if they are unused. Why is there nothin left to do for those?

And finally, documenting why this has happened should be part of this ticket I think, as the documention we produce should be reviewed by someone else to make sure it is correct.

**Comment by DominicOram** [comment]
1) I did wonder about doing this but I would want to test all the IOCs once I'd done it and some of them aren't covered by system tests so I would have to write some tests. Also some of it is not our code so will potentially cause us merge conflicts. I'm unsure though.
2) The issue is caused by interactions between `mbbo` and StreamDevice. If it's a soft/asyn channel it doesn't use StreamDevice.
3) Yes, I should have done that, I will put this back `in progress`

**Comment by DominicOram** [comment]
Documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Stream-Device-Tips-and-Tricks#dealing-with-enums
