### ISSUE TITLE
Danfysik: Auto on/off should have to be set explicitly

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5265]
As a ZOOM scientist, I want my to be more in control of the auto off behaviour. Currently auto on/off defaults to being enabled with a tolerance of 1A. It should be off by default with a tolerance of 0 so that it mimics previous behaviour unless auto on/off is explicitly desired and configured by the user.

#### Acceptance Criteria 
- Auto on/off defaults to "Disabled"
- `OFF_TOLERANCE` defaults to 0

**Comment by kjwoodsISIS** [comment]
Thread from Ticket=FIT-17352
> 
> 2020/02/27 08:16 AM | Diego:
> Hi Thomas,
> 
> Thanks for the support, I will tweak the OFF_TOLERANCE macro now. If someone has
> asked for it, it was your job to add it, but I really think that most of the Danfysik users
> will ask for having that utility disable for them.
> 
> Many thanks again,
> Diego
> 
> ==========================================================
> 
> 2020/02/26 18:04 PM | Lohnert, Thomas:
> Hi Diego,
> 
> To elaborate, the auto on/off feature was a requirement for Muon beamlines. It should
> never have been noticeable on beamlines that do not require this feature, this was an
> oversight – my apologies!
> 
> To address this immediately, we will change the IOC so that a) auto on/off is disabled
> by default and b) the OFF_TOLERANCE defaults to 0. This way, the IOC should not
> automatically turn off unless it has been explicitly configured to do so. I will roll this
> change out this evening, the IOC will then use the updated code from the next time it is
> restarted.
> 
> We can also talk about how to make the auto on/off setting more hidden altogether on
> beamlines that do not require this behaviour.
> 
> Thanks,
> Thomas
> 
> ==========================================================
> 
> 2020/02/26 17:24 PM | Diego:
> Hi Tom,
> 
> Who  or how is this decide? 0.05A it is a usable current which is often used, I don’t
> think any tolerance is really usable here. I don’t think this should be an option, since if
> you want to turn off the supply, you just turn off the supply (script or otherwise).
> 
> Thanks,
> Diego
> 
> ==========================================================
> 
> 2020/02/26 17:12 PM | Lohnert, Thomas:
> Hi Diego,
> 
> The default tolerance around 0 to switch off the power is currently set to 1A, I’m
> guessing this is why it is switching off when your current drops below. You can change
> this value by setting the OFF_TOLERANCE macro in the Danfysik IOC, and then see if
> the behaviour persists.
> 
> If you think 1A is not a reasonable default tolerance, please let us know. This can be
> fixed easily with the next release.
> 
> Thanks,
> Thomas
> 
> ==========================================================
> 
> 2020/02/26 16:55 PM | Diego:
> Hi Tom,
> 
> I have set up the magnet and I was trying it, so I was trying smallish fields, always less
> than 1A. As soon as I was setting a non-zero (i.e. 0.5 A), it was reaching the set point
> (it doesn’t take long for the PSU to do it) and switching it off.
> 
> Thanks,
> Diego
> 
> ==========================================================
> 
> 2020/02/26 16:50 PM | Lohnert, Thomas:
> Hi Diego,
> 
> The way the auto on/off feature should work is that the power is automatically turned
> off only when the current is at 0 (within tolerance) and stable (i.e. has held its value for
> at least 5 seconds).
> It sounds like you observed the power being automatically turned off after setting a
> non-zero current. Could you provide more detail on what you were doing when you
> observed this behaviour?
> 
> Thanks,
> Thomas
> 
> ==========================================================
> 
> 2020/02/26 16:49 PM | Steve King
> Hmm…
> 
> Is that toggle really to do with the main power? And not some other feature?
> 
> Steve
> 
> ==========================================================
> 
> 2020/02/26 16:39 PM | Diego:
> 
> I have discovered that there is a toggle button "Auto on/off Disabled/Enabled"
> that kills the power straight away after setting a current. There is any reason
> for that to be in? If the power supply is at max current it SHOULD NOT kill the
> supply, it could be very dangerous. It will drop the magnetic field in the
> magnet generating an induced electro magnetic field. There is any way of
> removing the toggle button from the IOC?
> 
> Many thanks,
> Diego
>

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/478 rolled out to all instruments.

Follow up issue: https://github.com/ISISComputingGroup/IBEX/issues/5268

**Comment by Alexandru-Dascalu** [comment]
The fix makes sense and looks correct, but I think the auto on/off feature and the way it currently works on the muon vs the neutron beamlines and the reason why it was especially needed for the muons should be documented here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Danfysik.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Danfysik#auto-onoff

**Comment by Alexandru-Dascalu** [comment]
Added a clarification in the documentation about stable means exactly.
