### ISSUE TITLE
DAQMX: recover from hardware disconnection when hardware becomes available again

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5266]
As a user of DAQMX-based IOCs, I would like the DAQMX components to recover gracefully if they lose and then regain access to the hardware.

Currently the IOC will get "stuck" in an error state if it momentarily loses connection to the hardware, causing invalid alarms until the IOC is restarted.

Possible solutions:
- [hard] Modify the DAQMX main loop in the driver to do this
- [maybe easier] automatically detect this case and provide the option to automatically reboot the IOC when it is detected.

#### Acceptance criteria
- IOC reconnects when connection to hardware reestablished
- Appropriate tests created

**Comment by Tom-Willemsen** [comment]
Brought up as EMU ZF system momentarily lost connection to DAQ, and subsequently could not adjust the zero-field system.

**Comment by DominicOram** [comment]
Try using a virtual DAQmx. If not working then plug one in at RAL and talk to it remotely or look at using one currently on an instrument. Otherwise take home, discuss with group on what needs to be taken home before going into the lab!
