### ISSUE TITLE
MERLIN: setup lakeshore336

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5267]

**Comment by FreddieAkeroyd** [comment]
Have updated developer wiki - it says macro is IPADDR and it actually looks to be HOST from st.cmd. Need to think if we can generate device documentation from the ioc files, should be possible to parse config.xml and generate a page of macros for user/developer manual

**Comment by GRyall** [comment]
Work was complete and wiki updated, no further action required.
