### ISSUE TITLE
Danfysik: Option to hide auto on/off related functionality

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5268]
As a neutron instrument scientist, I would like the auto on/off feature to be hidden as it can be confusing and potentially dangerous when configured incorrectly.

We could add a macro `ALLOW_AUTO_ONOFF` and then disable the relevant records and show/hide controls accordingly (similar to `USE_SLEW` and `CALIBRATED`. Of course, if you are determined you could still get it into a dangerous state but it would better prevent accidents.

#### Acceptance Criteria
- Danfysiks can be configured to either allow the use of auto on/off or not.
- The "auto on/off" toggle button, and "sweep to 0 and turn off" button are shown/hidden on the front panel as appropriate
- The `AUTOONOFF` record is can either be written to, or is locked to "disabled", as appropriate

**Comment by John-Holt-Tessella** [comment]
+1 MuonFE
