### ISSUE TITLE
POLREF: enable FMR equipment to be controlled remotely

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5270]
The upcoming FMR (Ferro-Magnetic Resonance) experiment consists of various pieces of equipment (primarily a Vector Network Analyser) controlled by a VI written by the users and run on their own PC.

The requirement is to have this equipment be controlled via scripts running on the instrument control machine (NDXPOLREF under SECI).

The suggestion is to wrap this VI in an LVDCOM IOC and run a "mini-inst" on the users' PC.  On the control machine, a CaLAB VI would communicate with this IOC remotely.  This solution would save development time in the long term by using an (LVDCOM) IOC which NDXPOLREF could easily communicate with when it's converted to IBEX.  It would also have the added benefit of removing the need to alter the users' software, potentially other than to make it compatible with LVDCOM.

#### Acceptance Criteria
1. LVDCOM IOC created to wrap users' unmodified VI
1. "Mini-Inst" installed on users' PC
1. IOC runs in parallel with VI on their own PC
1. POLREF control machine (SECI) runs a CaLAB VI to communicate with the IOC

**Comment by kjwoodsISIS** [comment]
When is this experiment scheduled?

**Comment by davidkeymer** [comment]
> When is this experiment scheduled?

Forgot to add to description:  Nominally scheduled for  **10/03/2020@0900 - 13/03/2020@0900**

**Comment by davidkeymer** [comment]
Pull requests:
[EPICS TOP](https://github.com/ISISComputingGroup/EPICS/pull/206)
[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/486)
[Support](https://github.com/ISISComputingGroup/EPICS-FMR/pull/1)

Wiki Page:
[Info](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Ferro-Magnetic_Resonance_equipment)

**Comment by DominicOram** [comment]
This is hard to test without hardware. From inspection the IOC looks like it would work (if the [suggested change](https://github.com/ISISComputingGroup/EPICS-FMR/pull/1#pullrequestreview-405687279) is made). However, as alluded to in the documentation this is far from finished. The following would need to be done before we could call this device supported:
* IOC system tests that the IOC at least starts up
* Improve the documentation to say a bit more about what the device does, e.g. what is Ba?
* Finishing touches to the [DB](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches)
* Potentially a re-write away from using CALAB

When and how much of this we do is reliant on a number of factors. Do we have an idea of how much they are going to use this going forward and whether it will still look the same in terms of the VI?

I also have no idea if the other acceptance criteria were successful, I assume they were?

**Comment by kjwoodsISIS** [comment]
This ticket has been "in progress" since March.  What is the hold up?  Should we put it back in "awaiting" or does it need to get done?

**Comment by davidkeymer** [comment]
To address review points above:

- Macro added to LVDCOM xml configuration file to specify VI path.  Set to `C:\\Instrument\\Apps\\EPICS\\ISIS\\FMR\\master\\VI\\VNA-FMR-POLREF_(LV2010).vi` to run included copy of users' VI.
- Basic test added.  Additional [PR](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/403) created.
- [Documentation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Ferro-Magnetic_Resonance_equipment) improved and expanded
- Units, interest levels, etc. added to DB file.  PV descriptions left as default to enable ease of mapping to LabVIEW controls and indicators.
- Potential future development described on wiki page above.  [Ticket](#6003) created for an OPI as it will be needed at the very least now that POLREF runs IBEX.
- Acceptance criteria satisfied during experiment.

**Comment by davidkeymer** [comment]
[PR](https://github.com/ISISComputingGroup/IBEX/pull/6072) for update to release notes.
