### ISSUE TITLE
web dashboards not working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5279]
Scientists report not working - investigating

**Comment by FreddieAkeroyd** [comment]
json bourne not happy - process oscillating between 1GB and 2GB of memory,  log file has lots of connection errors, errors like
```
2020-02-29 10:23:18,039 Reconnected with IMAT
2020-02-29 10:23:24,321 URL not found or json not understood: http://NDXIMAT:4813/group?name=BLOCKS&format=json
2020-02-29 10:23:24,321 Failed to read blocks: Expecting value: line 1 column 1 (char 0)
```
data is being sent and looks ok in firefox. Other machines getting connection fails

**Comment by FreddieAkeroyd** [comment]
json bourne failed to restart with directory permisison error - was unable to reset permission from GUI but managed to do it using `icacls`

**Comment by FreddieAkeroyd** [comment]
despite above IMAT/LET errors in log file, dashboard seem to be mostly working now

**Comment by FreddieAkeroyd** [comment]
nagios checks added for memory and handle count

**Comment by FreddieAkeroyd** [comment]
perfmon shows small memory leak but large handle leak, ~7000 per hour, so probably need to restart json_bourne daily until #5280 resolved

**Comment by DominicOram** [comment]
Now that #5280 is done can we close this off?

**Comment by DominicOram** [comment]
Dashboard currently working and now using huge amounts of memory, calling this done.
