### ISSUE TITLE
json_bourne: resource leak and other issues

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5280]
json bourne stopped working #5279 and was consuming a large amount of memory. There were multiple log messages about connection failures, so it looks like connection failures cause at least a memory leak. I forgot to check the handle count, but looking at the new process i believe it is also leaking socket handles as the handle count is increasing. Have attached a process monitor to verify this. Error logs are on the server.

acceptance criteria

* running `perfmon` shows no memory or handle leak  in presence of connection failures
* can we write system/unit tests for this?

**Comment by FreddieAkeroyd** [comment]
![image](https://user-images.githubusercontent.com/1132753/75606616-80512180-5ae6-11ea-9132-1208b0dbfff2.png)

**Comment by FreddieAkeroyd** [comment]
red is handle count

**Comment by FreddieAkeroyd** [comment]
note: json bourne is currently using the caffi rather than ca backend to cachannel - this was because ca didn;t seem to be available in python 3.8 when it was installed

**Comment by Tom-Willemsen** [comment]
> note: json bourne is currently using the caffi rather than ca backend to cachannel - this was because ca didn;t seem to be available in python 3.8 when it was installed

https://github.com/ISISComputingGroup/genie_python/pull/221 uses python 3.8 with the full `ca` backend if you want to try it?

**Comment by FreddieAkeroyd** [comment]
@Tom-Willemsen  should i copy the files from the genie python PR pipeline build?

**Comment by FreddieAkeroyd** [comment]
Handle leak still present after moving to 3.8 with native caChannel, lots of connection errors in logs so maybe something is not getting cleaned up on error

**Comment by Tom-Willemsen** [comment]
This looks like it may be a leak in the `requests` library itself - lots of other people are reporting problems when using `requests` in a multithreaded context. See comments on:
- https://github.com/psf/requests/issues/4934
- https://github.com/psf/requests/issues/4601
- https://github.com/psf/requests/issues/4191

I will look for a workaround in our code (some people suggest using `urllib` directly instead of `requests`)

**Comment by Tom-Willemsen** [comment]
Now deployed and no longer looks to be leaking handles.

**Comment by FreddieAkeroyd** [comment]
![image](https://user-images.githubusercontent.com/1132753/75881835-c6282580-5e17-11ea-9ba8-206841e4058a.png)

memory and handle slook good
