### ISSUE TITLE
StreamDevice: Try Fix for Buffer Issues

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5283]
As a developer I would like to not diverge too much from the master version of other people's libraries e.g. StreamDevice. Following a bug found in the latest update (https://github.com/ISISComputingGroup/EPICS-StreamDevice/pull/7) StreamDevice created a fix that's a bit cleaner than ours (https://github.com/paulscherrerinstitute/StreamDevice/commit/7dda6ca77354b2e6979c7d8ddd44f856fe02b77a). We should merge this and see if it fixes the problem for us.

**Comment by John-Holt-Tessella** [comment]
Pushed through so that it can be tested as part of the build
