### ISSUE TITLE
System Tests IOCs: Fix tests that fail silently

### ISSUE THREAD

**Issue by Alexandru-Dascalu** [ISISComputingGroup/IBEX#5285]
As a developer, I want tests not to fail silently so that I can easily see what tests need to be fixed.
 
Currently, there are some tests that fail with the message "IOC appears not to have started after 120 seconds. Looking for 'epics>'"in the Jenkins console output, but they do not appear in the list of failed tests.

**Acceptance criteria:**

- [ ] Make sure that all tests that fail are displayed by Jenkins.

- [ ] Document why some tests fail with the message "IOC appears not to have started after 120 seconds. Looking for 'epics>'".

**Comment by Alexandru-Dascalu** [comment]
The IOCs that Jenkins has a problem with starting are: RKNPS, ATTOCUBE, SEPRTR, ZFMAGFLD.

**Comment by Alexandru-Dascalu** [comment]
The ATTOCUBE IOC start correctly and the tests pass on every second build, but fails on the next one. The SEPRTR, ZFMAGFLD and RKNPS IOCs all consistently fail to start, at least on the last three builds as of writing this ticket.

**Comment by Alexandru-Dascalu** [comment]
The above mentioned IOC tests might not actually be failing silently, but instead they might be the reason for the test pipeline being red instead of yellow.

**Comment by John-Holt-Tessella** [comment]
Errors do fall trhouhg and cause build to fail. Sorry johns faul
