### ISSUE TITLE
Fact Finding: HTS system (11/2020)

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5287]
As a POLREF instrument scientist I would like to commission the HTS system using IBEX in November, so I will need a driver.  As a developer I need to find out more about the system and what controls are appropriate, with expert help (maybe from cryogenics/power supplies too)

#### Acceptance Criteria
1.  All details for system gathered and documented in the appropriate location(s).

#### Notes
1. The power supply appears to be a normal Kepco. Check that this is true - **Confirmed** (28-04-2020)
   1. the power supply is actually two KEPCO BOP 6-125MG units which are connected in parallel
   1. the KEPCO BOP 6-125MG is essentially the same as other Kepco BOP 1kW devices.  However, there are firmware specific differences.  We should [download](https://www.kepcopower.com/support/opmanls.htm#bop-1k) the correct copy of the manual (when we know the firmware version). 
    1. there is an [EPICS driver for Kepco BOP 1kW devices](https://www.kepcopower.com/drivers/drivers-dl3.htm#epics), but it appears to be Linux specific.
1. The smart monitor is an ethernet device.
1. Manuals in HTS folder in the manuals area.
1. Manufacturer's web-site: [https://www.scottautomation.com/hts-110/](https://www.scottautomation.com/hts-110/)
1. HTS is a **H**igh **T**emperature **S**uperconducting device (as distinct from a low temperature superconducting device (LTS))

**Comment by John-Holt-Tessella** [comment]
Email sent:
> From the manual it looks like the power supply is a standard Kepco. Is the hardware the same as the other Kepcos we have at ISIS? If so we already can control:
>
> -	Reset
> -	Remote
> -	Current read/write
> -	Voltage read/write
> -	Mode set read/write (either voltage or current)
> 
> Did you need any other control or readbacks? The power supply is capable of another 50+ commands, we do not want to implement the whole suite if you are not using any of the commands.
> 
> From the look of the smart monitor it can only do 6 things and getting the status is not included; I assume we can just do all the items in the list. I am a bit worried that the status indicator led does not seem to have a direct output. We can get back the “Current temperature and voltages from Magnet” but not the status directly. Is this ok?

**Comment by Tom-Willemsen** [comment]
@kjwoodsISIS to look at this

**Comment by kjwoodsISIS** [comment]
Reply from HTS:
> From: Taotao Huang
> Sent: 19 March 2020 21:30
> To: Christy; John; Diego
> Subject: RE: Manual
> 
> Hi Christy
> 
> We don’t have a specific “status” command that replicates the light on the front panel, however 
> we do have a physical relay contact on the back panel which allows a “Good/Bad” signal to be 
> interrogated.   Will this suffice? 
> 
> Otherwise we can look at the feasibility to alter the software to include a custom 
> command if required.
> 
> Regards
> 
> Taotao
>

**Comment by John-Holt-Tessella** [comment]
1pt for the review

**Comment by kjwoodsISIS** [comment]
Scientist contacted: 23 April 2020 16:35.  Awaiting reply.

**Comment by kjwoodsISIS** [comment]
Response from scientist (in italics):
1. Ticket #5287 suggests that the HTS magnet is needed for November.  
   * Is that still a possibility, given all the disruption to cycles?  Or is it too early to say?
      * _So far HTS110 have said they are doing ok and things may be only slightly delayed. However we may be delayed as we may not be able to provide neutrons top test this with on arrival. But we should continue as if this is coming on time and will be used in November for now. I will check with HTS110 for how things are going._ 
1. The elements of the system that can be controlled are:
   * a Kepco BOP 1KW power supply
   * a Smart Monitor provided by the magnet manufacturer
   Is that correct?  Is there anything else?
      * _I believe this is correct._
1. We already have a Kepco IOC & GUI (see attached screenshot).  
   * Does this provide you with everything you need to control the PSU & magnet?
      * _I will need to check this with Diego and Rob. In the first approximation I believe so. It would be nice to be able to enter a calibration , either a look up table or an equation for the current to field conversion. At least have a process variable that can be logged. This last step may not be worth it, I will discuss with Rob and Diego._
1. The Smart Monitor manual lists 3 commands, which we can use to get status information.  
   * I assume you'd like us to display that information on a GUI.  Is that correct?  
      _a. Yes we would like to display and log that information please._
* This information appears to be "read-only" (which makes sense - it is a monitor, after all).  In fact, the manual states "Dedicated software limits are _programmed into the monitor_ for each sensor allowing safe operation of the magnet." (my italics).  This suggests to me that the limits are burned into firmware on the monitor.  Therefore, it appears that there is no facility for setting things like voltages, current, etc.  Is that your understanding too?
      _b. I will check with HTS110 on this one it is not clear form the manual to me._
1. The Smart Monitor manual describes a status indicator LED, but there is no command which replicates the function of the LED.
   * There seems to have been some correspondence with the manufacturer, asking whether it is possible to replicate the function of the LED as a command.
   * In reply, the manufacturer suggested a "good/bad" relay signal
   * Our preference would be for a custom command.  For example, it could return one of 4 values 
corresponding to the Conditions listed on the table on page 3 of the manual.
   * Has the correspondence reached a conclusion?
      _* Nope we have not reached a conclusion with HTS100 and I will email them after this to ask about this._
   * Is there still an opportunity to persuade the manufacturer to enhance their software?
   * Do you know if the manufacturer is still able to supply the system in time for 
November?  (I guess their operations have been disrupted too.)
      * _I will contact taotao now._

**Comment by kjwoodsISIS** [comment]
Additional response from scientist (Rob) on 24 April 2020 17:50:

I would be surprised if the power supply spec for this is the same as a normal Kepco.
It’s a super conducting device. Do we have anything else superconducting running with a Kepco power supply.
I would expect ramp rates, quench detection etc to be much more prominent.

**Comment by kjwoodsISIS** [comment]
Reply to scientists on 27 April 2020 10:22:

Thanks for the update Christy.
I agree with Rob, I would expect to see more about how the entire system should be controlled to achieve the desired magnetic field.  But, as far as I can tell, we have no such information.  All the information we (in the Experiment Controls team) have about the HTS system is listed in ticket #5287 plus the following manuals.
   * 2281692-r9.pdf (which is the Quick Start Guide for a Kepco BOP 1KW-MG/ME/MGL/MEL power supplies)
   * bop1kw-mg-opr-r22a.pdf (which is the Operator’s Manual for a BOP-MG 1KW High Power Bipolar Power Supply)
   * Smart Monitor User Manual.pdf  (which, on the front page, calls itself Magnet Protection, Installation & User Manual)
      * This document makes explicit reference to the PSU being a Kepco (see diagram on page 4).

This suggests to me that there is a lot more manufacturer documentation that we have not seen.  Has the manufacturer provided additional material?

**Comment by kjwoodsISIS** [comment]
The supplier has confirmed that the device is a high-temperature superconducting (HTS) magnet, not a low-temperature superconducting magnet (LTS).  HTS devices behave differently from LTS devices, therefore, a conventional PSU, such as a Kepco, is sufficient.

Response from Supplier:
> Dear Christy
>  
> As far as you might have known, the quench properties of HTS magnets are very different with those of LTS magnets.
> We do use our smart magnet monitors to protect our magnets.
> We don’t need to use specialist superconducting power supplies as we do not need, nor employ, their quench-detection circuitry which has been developed and optimised for LTS magnets. We also don’t need the persistent switch heater capability commonly built into those types of supplies. Besides this, the conventional supplies offer better flexibility in terms of voltage and current ratings and so can be a better matched to the operating points of our HTS magnets. Further, we have more experience with the ability of the conventional power supplies to absorb energy during magnet discharge.
>  
> Please let me know if you have any further questions.
>  
> Regards
>  
> Taotao

**Comment by kjwoodsISIS** [comment]
Response from scientist (Rob):
> Ok, that’s interesting.
> It will certainly be good to see how they set things up for low currents and maintain stability.
> We found that the low resistance was a problem for standard supplies that was strongly dependent on how they monitored voltage.
e.g. you apply 50A and the system tries to keep everything stable but if the voltage is very low that can be a problem and we had no end of bother on the HTS coils on the Wollaston prism. I’m sure that they’ve worked this all out. I’m more interested in the supplies themselves.
>  
> Can you forward on the exact specs of the supply again. I’m assuming that they come with the unit.
>  
> Thanks
>  
> Rob

**Comment by kjwoodsISIS** [comment]
Additional information from supplier (forwarded by scientists 28/04/2020):
> Sent: 03 March 2020 20:29
> Subject: RE: Manual
>  
> Hi All
> This magnet is driven by two KEPCO BOP 6-125MG units which are connected in parallel to provide up to 250 A @ 6V.
> Regarding the question about the monitor, could you advise your requirement in details.
> Matt, our control engineer who I have copied in, would be very happy to answer the questions.
>  
> Regards
>

**Comment by FreddieAkeroyd** [comment]
For info, the driver on the Kepo web site says it is for Linux but it is actually stream device so should be fine on windows too.

**Comment by kjwoodsISIS** [comment]
Response from supplier regarding LED status on the Smart Monitor front panel.  They have agreed to extend the response from the STAT command (documented in the manual) to include an enumerated status value:
> There’s is a STAT command (accessible via tcp/up serial). At the end of the string of 
> temperatures/voltages etc there is an enumerated status value. (1-4) which corresponds 
> to the table from your email I believe.

**Comment by kjwoodsISIS** [comment]
Additional technical information (reflecting the previous comment) is now in the `Additional Technical Information from HTS.pdf` document in the `Manuals\HTS` folder in the shared directory.

**Comment by kjwoodsISIS** [comment]
Manufacturer is forecasting delivery for early September 2020.

**Comment by kjwoodsISIS** [comment]
Scientists are expecting to commission the HTS system in October (probably 2nd half of October).

**Comment by kjwoodsISIS** [comment]
02/07/2020 - Scientist replied:
> ...the last thing is to with setting the Field either by typing a field or 
> by setting a current directly with appropriate Max and minimum limits. 
>
> You need to be able to set currents for when you inevitably end up running without a calibration. For whatever reason and you calibrate after the fact. We run the GMW like this for the reason we are constantly moving the poles in and out, and calibrating happens as best we can. We just note the pole gap for each case.

> This could be an option you select, wither set field or set current (Which would be in units of amps.)

**Comment by kjwoodsISIS** [comment]
02/07/2020 - Scientist asked HTS Supplier:
Are the ramp rates, current, voltage limits etc set in the controller or can they be set via a VI?
HTS Supplier replied:
> The monitor has limits on differential voltages, current and temperatures for protection.
> Limits on ramping voltage and current can be set in the power supply.
> So you can set a VI to control ramp rates in the power supply.

**Comment by kjwoodsISIS** [comment]
Schematics of OPI are here:

- [Main tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Normal_Tab.pdf)
- [Details Tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Details_Tab.pdf)

**Comment by kjwoodsISIS** [comment]
There is now sufficient information on the HTS magnet to be able to create implementation tickets.  Ready for review.
