### ISSUE TITLE
DEPLOY: Create Release (start 3/4/2020)

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5291]
As a developer I want an IBEX release so I can install it on the instrument machines for the start of machine physics on 26th.
Deployed in #5292 

Acceptance Criteria:

- [ ] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [ ] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [ ] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [ ] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)
- [ ] [Create a ticket to give instrument demos](https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos)
- [ ] Distribute release notes via email [Instrument scientist release email](https://github.com/ISISComputingGroup/IBEX/wiki/Instrument-scientist-release-email)

**Comment by Tom-Willemsen** [comment]
@JamesKingWork can you update this ticket with new template

**Comment by JamesKingWork** [comment]
At the time of this ticket the latest script definitions should be deployed to emu. To do this move the C:\ScriptGeneratorConfigs folder to C:\ScriptDefinitions and pull the latest changes. Please check with Steve and Kojji that they are happy with this (At this point it doesn't look like they've edited the script definitions, but we may need to merge if they have by the time of release).

**Comment by Tom-Willemsen** [comment]
The cycle that this release was being targeted for. There is no longer any use creating a release for this date. Taking out of tasks.

**Comment by FreddieAkeroyd** [comment]
I have removed the milestone as it is no longer in the sprint

**Comment by John-Holt-Tessella** [comment]
Deplot didn't happen corona
