### ISSUE TITLE
Deploy: Deploy release

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5292]
Deploy release created in #5291.

**Comment by JamesKingWork** [comment]
At the time of this ticket the latest script definitions should be deployed to emu. To do this move the C:\ScriptGeneratorConfigs folder to C:\ScriptDefinitions and pull the latest changes. Please check with Steve and Kojji that they are happy with this (At this point it doesn't look like they've edited the script definitions, but we may need to merge if they have by the time of release).

**Comment by John-Holt-Tessella** [comment]
Deplot didn't happen corona
