### ISSUE TITLE
ZOOM: Add Julabo to config

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5294]
As a user on ZOOM I want to be able to use a 'new' Julabo which has not yet been used on zoom. As a zoom instrument scientist I don't want my existing julabo components to be modified so I can continue to use the existing julabos on zoom after this experiment.

Component `julabo_pool` was created to control the new julabo being used on zoom. The component, `julabo` was left unchanged so the two existing julabos could still be controlled from other zoom configurations.

Updated Julabo wiki page (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Julabo) to mention use of null modems which caught us out

**Comment by kjwoodsISIS** [comment]
How many points?
