### ISSUE TITLE
Danfysik: Polarity not being set

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5296]
As a ZOOM scientist, I would like the Danfysik to respond correctly to setting a new value for polarity. They reported seeing a bug where they would click the toggle button but the new value would not be set on the device. They confirmed the Danfysik in question was capable of switching polarity via the machine front panel.

Had a look at the IOC log but saw nothing unusual. It works fine with the device emulator, too. They will not be needing this feature for experiments this cycle, we may use the beamline to investigate this issue some time during shutdown if necessary.

#### Acceptance Criteria
- Fix protocol file (missing space between command and argument)
- Fix `DFKPS_polarity.db`: `POLCMD` should default to `PO` (currently is blank). Check this is true for all (bipolar) models, but seems to be the case for all manuals I can find on the share.
- Add IOC tests
- Put in a safeguard against switching polarity at high currents as this could be dangerous for the equipment. Talk to relevant scientists and either:
    1. Disable polarity setpoint unless motor is at 0 and/or powered off
    1. On setting polarity, execute some logic that ramps down to 0, switches polarity and then ramps to the inverse setpoint.

- Tested against Hardware

#### Notes

- Test and find a fix for RIKEN, if this applies for zoom then good, if not spin out another ticket

**Comment by John-Holt-Tessella** [comment]
This seems important!! Should we add this as a task in shutdown?

**Comment by ThomasLohnert** [comment]
Might be a good idea. 

@KathrynBaker suggested it could be that it could be a configuration issue with the model number. I inquired and the Danfysik they use is a 9100.

**Comment by ThomasLohnert** [comment]
+1 from RIKEN

**Comment by John-Holt-Tessella** [comment]
Must be in lab to do this

**Comment by kjwoodsISIS** [comment]
E-mail sent to scientists:
> The Experiment Controls team has been discussing a report of a problem in setting the polarity of a 
> Danfysik power supply on ZOOM (see #5296).  Initially, we had hoped to be able to resolve this issue 
> during the summer shutdown – but Coronavirus made that impossible.  Working remotely we cannot 
> determine the cause of the problem.  The only way to make further progress is for a member of the 
> team to investigate the problem on-site.
> 
> Of course, in the current circumstances, getting someone on site to perform such an investigation 
> is going to require some advance planning and approval.  To help kick-off the planning, I'd like 
> to check a couple of things with you:
> 1.	Do you plan to use the Danfysik power supply in the coming cycle?
> 2.	If yes, are there convenient times when someone could come on-site to investigate?
> 3.	If not, do you know when you next intend to use it?
> 
> Once we have an idea of when the investigation could be done, we can then work with you to prepare 
> a RAMS document in order to gain the necessary approvals.

**Comment by kjwoodsISIS** [comment]
Response from ZOOM:
> At the moment there is not experiment scheduled for the PSU. I can’t discard the 
> November-December cycle, but I don’t think that is realistic that any PSU experiment 
> will happen this year.

**Comment by kjwoodsISIS** [comment]
Response form RIKEN:
> I don’t recall the details of the incident with RQ23. Looking back, in the group meeting 
> minutes at the time we had “Reversing switch broken, Richard Hale is investigating” which 
> sounds like it could be a hardware fault.

> For testing: next week we have the Fixed Installation testing around the north side of R55 
> and various bits of RIKEN will go off, perhaps including MOXAs, so that would not be a good 
> time. The following week from the 24th should be OK. After the Bank Holiday weekend 
> (2-4 September) may be a bit close to the cycle but there could be an opportunity then.

> Does the test need someone from Experiment Controls to be in the lab watching the supply 
> front panel / connecting a laptop directly to it, or is it sufficient to power it on and 
> let you access it remotely?

> I think whoever is coming in will need an official approval from the User Office to access 
> site (if they haven’t been back in yet) and then the RAMS need to be submitted for approval 
> and the building supervisor asked for permission to go in on a particular day. However, 
> procedures may be changing.

**Comment by ThomasLohnert** [comment]
+1 from POLREF

**Comment by ThomasLohnert** [comment]
Seems like there is simply a space missing in the protocol command (at least this fixed it for the danfysik 8500 on POLREF).

I have asked the electronics guys about the safety of switching polarity while the magnet is powered on and while it does not seem to present a critical risk, they said it is best practice to ramp to zero first. The scientists on POLREF also said they would rather err on the side of caution. I think we have several options:
- Add no further safeguards, leave it up to the scientists to follow best practices
- Disable polarity setpoint unless the magnet is at 0 / powered off
- Add logic so that the current automatically ramps down before (and back up after) actually setting the polarity on the device
- ...?

**Comment by kjwoodsISIS** [comment]
I prefer option 2.  It means that the scientist must explicitly ramp the current to zero before switching polarity.
We should also include a tooltip, to tell the scientists that the polarity setpoint cannot be changed until the current is zero.

We should also check with the muon scientists that they are happy with this behaviour.  If they are not, then we need to have a discussion and agreement as to what the right approach is.

**Comment by KathrynBaker** [comment]
Options 2 and 3 are both potential answers, I can see some users being frustrated with option 2 as they will always have to script that kind of behaviour, and there then gets to be an impact onto things like the script generator (e.g. my changing parameter is the magnetic field, I'm going from +3.5 to -3.5 in steps of 1, what happens between 0.5 and -0.5), which makes 3 safer from an automation point of view. Adding 3 under the hood would change user experience (some PSUs just switch, and the ramps will take time), but would guarantee a sensible behaviour when scripting as well as when using the UI, and no sudden hang in a script because they forgot that a loop would change the polarity and hasn't actually stopped at 0.

**Comment by kjwoodsISIS** [comment]
I think some people will want the automated behaviour and some will not.  I suspect we won't be able to please all of the people all of the time.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/542 - info on implemented solution in description
https://github.com/ISISComputingGroup/EPICS-danfysikMps8000/pull/14
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/378
https://github.com/ISISComputingGroup/ibex_gui/pull/1204

**Comment by aaron-long** [comment]
Can you include an additional branch that is the update to Device Emulator to account for the protocol changes. The DevSim tests have some failures in the `common_tests/danfysik` (lines 92, 95) as the command interface has not been updated.

**Comment by ThomasLohnert** [comment]
new PR: 
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/90

**Comment by aaron-long** [comment]
Code is good. Awaiting hardware testing results.

**Comment by ThomasLohnert** [comment]
To be tested some time next week.

**Comment by ThomasLohnert** [comment]
Tested on POLREF on 26/10/20 with @Tom-Willemsen as witness, setting positive/negative polarity worked fine but the RBV / SP:RBV values need to be signed -> Back into in progress
