### ISSUE TITLE
ISISDAE: add support for streaming liveview over kafka

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5298]
ESS datastreaming would like to test areaDetecr->kafka at ISIS. An ESS plugin is available and just needs to be added to areaDetctor processing chain

acceptance criteria

- liveview images appear in kafka topic provided by ESS

**Comment by FreddieAkeroyd** [comment]
Added during sprint so available for September to complete datastreaming milestones

**Comment by FreddieAkeroyd** [comment]
To test:
- enable liveview as per developer wiki
- you may need to edit the ISISDAE/liveview.cmd to make sure the topic is one that exists. It defaults to $(INSTRUMENT)_areaDetector so on a developer machine you should temporarily change to TEST_areaDetector topic
- check data appears in topic when running in simulated event mode

**Comment by John-Holt-Tessella** [comment]
@DominicOram can you review this? Have you got time?

**Comment by DominicOram** [comment]
I think it makes sense for me to review it, yes. I will find time.
