### ISSUE TITLE
ZOOM, RIKENFE: Critically low on C: drive disk spacee

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5301]
Both these are too high and should not be ignored, can possibly manipulate host volumes to borrow a little space to fix these... but not on Friday evening...

ZOOM  (Used=65.01GB (90.4%), Free=6.87GB)
RIKENFE (C:volumesAppsReadOnly Total=15.62GB, Used=14.23GB (91.1%), Free=1.39GB (8.9%)

**Comment by ThomasLohnert** [comment]
Truncated database on ZOOM and MARI. Not sure what to do about the RIKEN one.

**Comment by kjwoodsISIS** [comment]
Task is Done.  Close the issue.
