### ISSUE TITLE
GUI: BOY Console visible in scripting perspective

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5302]
As a user the BOY console is confusing. I would like to script in python but I'm unaware that a BOY console is not in fact a python console. We should ensure the user encounters python consoles in the scripting section, or at least provide clearer signalling that this is not Python.

### Reproduce issue
Version 1:
1. Open GUI
1. Switch to scripting perspective 
1. BOY console will be the default widget displayed before a console pop's

Version 2:
1. Use the red button to kill the single python console in the scripting perspective
1. BOY console is now the default widget shown

### Acceptance Criteria
- [ ] BOY console is not shown unless specifically requested

**Comment by Tom-Willemsen** [comment]
This will need modifications to CSS code.

Specifically, we'll probably need to add a new option for the preference `org.csstudio.opibuilder/popup_console=NO_POP` to completely disable BOY's console

**Comment by DominicOram** [comment]
+1 on RIKENFE

**Comment by John-Holt-Tessella** [comment]
+1 SANDALS

**Comment by FreddieAkeroyd** [comment]
+1 MERLIN

**Comment by DominicOram** [comment]
Make sure error still gets logged somewhere, just doesn't pop up.

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/cs-studio/pull/7
- https://github.com/ISISComputingGroup/ibex_gui/pull/1252
- https://github.com/ISISComputingGroup/IBEX/pull/6201
