### ISSUE TITLE
LSICORR: Implement user feedback

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5303]
As an instrument scientist I want my feedback for the LSI correlator to be implemented.

### Acceptance criteria
- [ ] Filename PV updates correctly, which was disabled in #5304
- [x] There is a `wait` PV which causes the IOC for the given amount of seconds before taking data
- [x] The Corr/ time lags data set obtained from the correlator can have a minimum time lag set, points where Lags < minimum time lag are removed
- [x] The minimum lag time can be set in the advanced tab on the OPI, and defaults to 200ns
- [x] Default metadata values are changed to:
Scattering angle = 110 degrees
Sample temperature  = 298 Kelvin
Viscosity = 1 mPas
Solvent refractive index = 1.33
Laser wavelength = 642 nm

**Comment by DominicOram** [comment]
Final criteria done in https://github.com/ISISComputingGroup/IBEX/issues/5336

**Comment by JamesKingWork** [comment]
Being done as a work experience project

**Comment by JamesKingWork** [comment]
After the demo the scientists have clarified that they want to have the option not to wait before taking data in the first repetition but instead only waiting in between repetitions, they have asked for a checkbox that allows them to configure it. They have also requested to know more about how they can synchronise starting to take data as a begin() in a script and a start on the LSiCorrelator.

**Comment by JamesKingWork** [comment]
Criteria 1 to be done as part of https://github.com/ISISComputingGroup/IBEX/issues/5304

**Comment by DominicOram** [comment]
Did you discuss synchronising it with a begin with them? It might be able to be done using hardware if they want it properly synchronised. Otherwise they can use the pre/post begin stuff https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Pre-and-Post-Command-Hooks

**Comment by JamesKingWork** [comment]
I did say that there are a few mechanisms to synchronise it with them. They didn't seem to desperate to get it underway, I will write it up as a ticket.
