### ISSUE TITLE
IOC log: GUI not displaying messages in date

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5305]
As someone looking at the IOC log in the GUI, I would like to be able to search the logs by hour on one day. As you will see in the first image there are 3 messages at 09-03-2020 between 12 and 1. In the second image I have searched for those hours in the 09-03-2020, but they are not displayed.

![image](https://user-images.githubusercontent.com/54139864/76214458-b1c39e80-6204-11ea-87f9-779e802049a7.png)

![image](https://user-images.githubusercontent.com/54139864/76214656-1d0d7080-6205-11ea-9f47-a6520b8b1bf1.png)

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1334
