### ISSUE TITLE
SUPPORT: IMAT Turn down Galil Logging

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5308]
See if turning down the polling rate on the IMAT galil serial controller makes the system more responsive.

**Comment by John-Holt-Tessella** [comment]
Seemed to make some difference drop from 100 to -300 (synchronus 300ms). Dropped from ~9% to ~6%. 

Also installed non-memory leaking client,

**Comment by DominicOram** [comment]
I updated https://github.com/ISISComputingGroup/IBEX/wiki to show the client has been updated. Not much more we can learn.
