### ISSUE TITLE
SURF: Setup and Testing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5309]
When surf is next updated ensure:

### Acceptance Criteria
1. IBEX release is updated to latest version
1. Newset ISISICP is installed
1. Journal schema is added and journal file imported
1. Check Reflectometry Config is compatible with latest server
1. Tolerances for incorrect parameters need to be increased on SURF for at least S2offset, Samp Offset, S3 offset and VB Offset.
1. Beamline constants are added to configuration
1. Instrument script is updated

**Comment by ThomasLohnert** [comment]
Scientist said they are not currently using SURF and we are free to use it for testing. They are however in the SURF cabin sometimes so we should just let them know beforehand especially if we are planning to go down there ourselves.
