### ISSUE TITLE
LET: new mezei flipper: commissioning

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5313]
As an LET instrument scientist I need various help commissioning the new mezei spin flipper which was implemented in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mezei-Spin-Flipper

Tasks:
- Deploy new code on LET
- Help scientist debug their instrument script against a simulated flipper and DAE
- Patch ISISICP to allow for a higher limit of periods * time channels * spectra (with help from @FreddieAkeroyd )
- Help scientist debug their instrument script when running against the real hardware

**Comment by DominicOram** [comment]
Given we're now out of cycle what is left to do for this? Is it impeded?

**Comment by Tom-Willemsen** [comment]
I need to write up a couple of items to the wiki and create a PR for a hotfix I needed to do on the instrument.

**Comment by Alistair-McGann-Tessella** [comment]
I've got the following output in the devsim log when run against the emulator:
```
2020/04/17 14:30:24.542017 L0 TE:NDW1836:MEZFLIPR_01:FLIPPER:CURRENT_ANALYTICAL:SP:_SEND: Input "... than 40 characters[7m<0a>[27m" too short.
2020/04/17 14:30:24.542036 L0 No match for "[7m<0a>[27m"
2020/04/17 14:30:58.054492 L0 TE:NDW1836:MEZFLIPR_01:FLIPPER:FILENAME:SP:_SEND: Input "...\than\40\characters[7m<0a>[27m" too short.
2020/04/17 14:30:58.054539 L0 No match for "[7m<0a>[27m"
2020/04/17 14:31:04.543480 L0 TE:NDW1836:MEZFLIPR_01:FLIPPER:CURRENT_STEPS:SP:_SEND: Input "...om, list, of, data][7m<0a>[27m" too short.
2020/04/17 14:31:04.543523 L0 No match for "[7m<0a>[27m"
```
