### ISSUE TITLE
RIKEN: Indicate problems with Daqmx

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5314]
As a RIKEN scientist, I would like to be informed if there is an issue with a DAQmx box. Right now if a power supply cannot talk to a DAQmx, it is assumed that the instrument is in the middle of a changeover and disallows writing to the power supply via setting the `.DISP` field. This is the desired behaviour, but the condition should be flagged up to the user.

#### Acceptance Criteria: 
If a power supply does not allow being written to as a result of not being able to communicate with the DAQmx, 
- The "Alarm" LED on the front panel should light up
- The details OPI for that device should display an appropriate indicator/message describing the issue.
- A PV exists which summarises the status of the DaqMX connection as "good" or "bad", so that as a scientist I can put a block on this and notice that there is a problem without needing to go to the OPI. This should go into alarm when the connection is "bad".

**Comment by John-Holt-Tessella** [comment]
@Alistair-McGann-Tessella is this fixed by disconnection error ticket for the seperator?

**Comment by DominicOram** [comment]
Make sure there are RECSIM tests for this

**Comment by DominicOram** [comment]
After https://github.com/ISISComputingGroup/IBEX/issues/5266 a devsim test should also be possible.

**Comment by Alexandru-Dascalu** [comment]
Originally it was thought the ticket would require changes to .db files and such but it turned out to just need a GUI change in the end. There's no recsim/devsim tests because you can't test GUI changes with them as far as I know, and everything on the IOC side is already covered by tests. Therefore, no new recsim/devsim tests are needed for this ticket.

**Comment by Tom-Willemsen** [comment]
I've added the following acceptance criteria to the ticket as I think a use-case was missed when we thought about this initially:
> - A PV exists which summarises the status of the DaqMX connection as "good" or "bad", so that as a scientist I can put a block on this and notice that there is a problem without needing to go to the OPI. This should go into alarm when the connection is "bad".

(sorry this was not spotted earlier in the process, but I do think it's important for the scientists to be able to spot this error without going to the opi)

**Comment by Alexandru-Dascalu** [comment]
The PV that displays the DAQmx status can use the same logic used for display the warning in the OPI.

**Comment by adalator** [comment]
I've added the PV in the PR above.
