### ISSUE TITLE
RIKEN: Power Supply not talking

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5317]
Scientist phoned from RIKENFE reporting that they could not set RB2/RB2-2 power supplies.

On investigation, the DAQ box which handles the changeover logic had become unhappy. This caused IBEX to believe that a changeover was in progress, which prevents the power supplies from being set (by enabling DISP).

#### Diagnostic steps:

- Looked in IOC log, saw many errors from DaqMX
- Tried unreserving and re-reserving from MAX but this did not help (MAX reported an error state as well as IBEX)
- Power cycled the physical DAQ box
- Tried unreserving and re-reserving from MAX again, this worked again after power cycle
- Rebooted IOC to make it reconnect to DaqMX, all came back happily

#### Follow up actions:

- Ticket created to provide feedback in case the DAQmx is not communicating: https://github.com/ISISComputingGroup/IBEX/issues/5314

- Added documentation of solution: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Riken-power-supplies#individual-psu-is-talking-but-does-not-accept-setpoints

**Comment by DominicOram** [comment]
Awesome write up, thank you!
