### ISSUE TITLE
Block Gateway: Recover from connection issue [TIMEBOX: 1.5 days + 0.5 day review]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5318]
As a user, I would like the block gateway to be able recover from connection issues without any manual intervention. This occurred on Sandals, see `...\shares\ISIS_Experimental_Controls\data\Ticket5318_...` for the error log of the block gateway preceding the issue.

#### Acceptance Criteria
- The block gateway recovers from connection loss without needing a manual restart.

**Comment by DominicOram** [comment]
@ThomasLohnert do we know any more about this? It looks like the underlying problem was SANDALS briefly lost it's connection to `control-svcs` and so couldn't get the methane temp. I can reproduce this locally but the connection is remade after about a minute. Were the blocks still connected after longer on SANDALS? Also, was it all the blocks or just `control-svcs` ones?

**Comment by ThomasLohnert** [comment]
Unfortunately I don't know much more about this. I can say for certain that all blocks visible in the SANDALS blocks panel were disconnected. I suppose it's possible the gateway could have recovered by itself at some point but we probably spent at least 5-10 minutes looking at the issue on SANDALS before we solved the issue by restarting the gateway and the blocks did not come back in that time (not just on the blocks panel, we also tried getting them via command line). Also, SANDALS was presumably in that state for some amount of time before they called the support number. It might make a difference if you leave it disconnected for longer, I don't know if there could be some exponential backoff when trying to reconnect like we have in other places?

**Comment by DominicOram** [comment]
Timeline appears to be that at 12/03 09:47 SANDALS switches from the `GEM_sample_changer_no_SE` config to the `sandals_no_SE` config. The only difference between the two is the lack of the `ROTSC_01` IOC and the `Move_finished` and `sample` blocks. The blockserver claims to have restarted the block gateway correctly but none of the PVs came back. They didn't come back until it was restarted at 13:38. Windows error log looks fine around this time. I'll add a PV showing how many blocks are disconnected and we can put a nagios check on it. I can also look into putting a bit more logging into the gateway as it doesn't really say much when it gets updated. I'm not sure what else to do but open to suggestions.

**Comment by FreddieAkeroyd** [comment]
BLOCKCACHE seems to have noticed, maybe that can serve something of use.

Is it possible the blockserver wrote a blank file of blocks for it to serve, or somehow messed up the prefix?

The gateway takes a  `-debug` flag that can be given a number between 0 and 100. It make take a bit of trial and error to find the best flag, a `git grep gateDebug` will give you some key numbers to try, it looks like one of    2, 3 or 5   may be appropriate

**Comment by DominicOram** [comment]
Yh, `BLOCKCACHE` seems the logically place to monitor from.

> Is it possible the blockserver wrote a blank file of blocks for it to serve, or somehow messed up the prefix?
That would cause the issue but I can't think of a way of finding out after the fact.

> The gateway takes a -debug flag that can be given a number between 0 and 100. It make take a bit of trial and error to find the best flag, a git grep gateDebug will give you some key numbers to try, it looks like one of 2, 3 or 5 may be appropriate

Great, i'll try it out

**Comment by John-Holt-Tessella** [comment]
I think the block cache is going to be delted at some point (there is a ticket) so maybe start a new service to do the monitoring if you do. Possible a health monitor service :-)

**Comment by DominicOram** [comment]
I don't think we decided on deleting the block cache, just look into and document it better. If we decide we want to get rid of it later we can just keep the monitoring part.

**Comment by John-Holt-Tessella** [comment]
See #4136

**Comment by DominicOram** [comment]
> See #4136

I'm unsure what the link is?

**Comment by Tom-Willemsen** [comment]
> 
> 
> > See #4136
> 
> I'm unsure what the link is?

It's the ticket in which we decided to delete the block cache.

**Comment by DominicOram** [comment]
As in the single line of `Decided on no caching.`? This is kind of frustrating in that the ticket doesn't specify:
* That `Decided on no caching.` equates to deleting the BLOCK_CACHE IOC
* Why this decision was come to
* Why caching was implemented in the first place and so what side effects removing it could have
* When this decision was made and by whom

**Comment by FreddieAkeroyd** [comment]
I agreed with @DominicOram the ticket doesn't actually say we will remove "blockcache", it just says we will not use it for case lookup of PV names (or try to cache previous lookups in python). We have discussed removing the "blockcache" service before, but probably in a different ticket

**Comment by FreddieAkeroyd** [comment]
The gateway has also been updated from 2.1.1 to 2.1.2 https://github.com/ISISComputingGroup/EPICS-gateway/blob/master/RELEASE_NOTES.md

**Comment by John-Holt-Tessella** [comment]
Sorry yes that is not clear. I am guilty of not writing stuff down. Let me add some notes to the ticket.

**Comment by DominicOram** [comment]
Thanks @John-Holt-Tessella, sorry if I came across a bit terse.

**Comment by DominicOram** [comment]
I looked into upping the logging level, unfortunately because there is a lot of traffic going back and forth across the gateway it logs quite excessively. There are PVs you can write to that will give you more information of what is happening if this happens again. I added some docs about these at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Access-Gateway#troubleshooting

We could also use the gateway itself as the monitoring service. The `connected` PV gives how many PVs the gateway is successfully connected to and the `unconnected` give those that are dead for whatever reason. So I suggest that we put the following check into nagios:
```
connected = %INST_PREFIX%:CS:GATEWAY:BLOCKSERVER:connected
unconnected= %INST_PREFIX%:CS:GATEWAY:BLOCKSERVER:unconnected
if connected < disconnected:
    #e.g. there are more failed blocks than successful ones   
    ALARM
if connected == 0:
    #e.g. there are no successful blocks
    ALARM
```
This alarm may be a little transient as it will trigger whilst changing configs. But I also believe that it would have alerted us to this issue earlier. I think these two things are enough for us to nail it down if it reappears.

**Comment by Tom-Willemsen** [comment]
I agree that the documentation and check above should be sufficient to get more information if this issue appears next time.

@FreddieAkeroyd could you implement the check above into nagios for the IBEX instruments?
