### ISSUE TITLE
SANDALS: Blocks becoming disconnected

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5319]
SANDALS reported an issue where blocks were showing up as disconnected. 

#### Diagnostics steps:
- Checked underlying PVs were there (yes)
- Restarted `BLOCKSVR`. Was reporting an issue getting the IOC list
- Restarted `DBSVR`. Was running fine
- Checked Block Gateway logs which showed prior connection loss. See `...\shares\ISIS_Experimental_Controls\data for tickets\Ticket5318_gwblock_connection_loss_recovery`
- Restarted Block Gateway, which fixed the issue.

#### Follow up actions:
New ticket: https://github.com/ISISComputingGroup/IBEX/issues/5318

**Comment by DominicOram** [comment]
Great documentation of what happened and what you did, thanks!
