### ISSUE TITLE
MARI: Fix Mclennan Homing

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5322]
As an instrument scientist on MARI I would like my mclennan to home in the opposite direction. Further details TBD.

== Acceptance Criteria ==
* Scientist is met to understand the problem more
* Homing is changed to the routine requested by the scientist

**Comment by DominicOram** [comment]
Meeting arranged for 31st March. Pointed based on the fact that this should just be a minor config change.

**Comment by John-Holt-Tessella** [comment]
Make sure we ask why they don't have a limit switch at both ends. And if they do why it then matters which end we home too. I would rather not poliforate the number of options for homing that they have.

**Comment by DominicOram** [comment]
From memory I think it's a rotation stage that acts like a screw. If it rotates too much in one direction it basically falls off, this was the direction it was homing to. (yes, this design is ridiculous)

**Comment by DominicOram** [comment]
Requires hardware, lets go down when we're back on site.

**Comment by FreddieAkeroyd** [comment]
Reported by scientist: The homing direction is different for each of the two sticks but the IBEX GUI only allows one direction for homing (the EPICS code for the McLennan has both programmed in but the GUI only exposes one)

**Comment by DominicOram** [comment]
From Duc:

> The McClennan uses a simple serial connection where you send it strings to tell it what to do. The homing command is "1HD1" for one sense and "1HD-1" for the other sense, and IBEX only has one of them programmed in (at least from the GUI, although looking at the EPICS code https://github.com/epics-motor/motorMclennan/blob/master/mclennanApp/src/devPM304.cc#L241 both are included but the forward command is "{axis}HD" not "{axis}HD1"; my notes could be wrong or the extra 1 at the end is not necessary). Essentially we just need to have the other programmed in / enabled - I guess that could be done remotely but to test that it works we'd need to go to the lab (especially since nothing is connected up at the moment).

**Comment by DominicOram** [comment]
From looking at https://github.com/ISISComputingGroup/EPICS-motor/blob/master/motorApp/MclennanSrc/homing.st and https://github.com/ISISComputingGroup/EPICS-motor/blob/master/motorApp/MclennanSrc/devPM304.cc it looks like we have negative home implemented but as Duc said it's just not displayed to the user. Ideally this ticket would be:
* Test on the hardware that `caput MOTOR.HOMR 1` gives the correct behaviour
* Add the ability for the user to be able to send this home rather than the forward one

**Comment by DominicOram** [comment]
From going down to MARI here is a crude diagram of the current situation and what they want:

![MARI homing](https://user-images.githubusercontent.com/10086797/92756255-93418a00-f384-11ea-9c91-2bd762664bbe.png)

Reversing the home did not give the correct behaviour, neither did changing the IOC macros.

**Comment by John-Holt-Tessella** [comment]
Is this a rotational sample changer? what are the motor readings? is it 0 at West, 90 at North, -90 at South?

**Comment by DominicOram** [comment]
Issue is that they actually want `1HD1` rather than `1HD-1`. Currently homing mode 0 on the mclennan allows sending either homing direction but does not zero afterwards. Homing mode 2 only sends reverse direction but does set zero afterwards. Hotfix currently was done in https://github.com/ISISComputingGroup/EPICS-motor/tree/Ticket5322_mclennan_homing. Options for long term fix are:
1. Allow homing in both directions in mode 2. This will mean that we will have to make sure on existing instruments if they require negative homing they use `HOMR`
1. Add a new homing mode for home forward and then zero

**Comment by John-Holt-Tessella** [comment]
Option 2 for me then on MARI they always home with the one home button.

**Comment by DominicOram** [comment]
I'm actually erring on the side of option 1. I don't like making this decision based on what we're doing in the OPI. EPICS has a concept of forward/reverse homing, it's perfectly valid that the mclennan driver uses that

**Comment by DominicOram** [comment]
Decided on option 2 with @John-Holt-Tessella, @KathrynBaker and @Tom-Willemsen. I was mainly convinced by the fact that we probably want to restrict homing in the other direction, which option 1 does not allow.

**Comment by DominicOram** [comment]
I don't think I necessarily have to do this tidying up so I will put this back into ready

**Comment by DominicOram** [comment]
Long term solution moved to https://github.com/ISISComputingGroup/IBEX/issues/5729. To review this ticket please review documentation and confirm scientist is happy.

**Comment by DominicOram** [comment]
Documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MARI-Sample-Changer, scientists ran experiments with sample changer this morning and had no issues.
