### ISSUE TITLE
All instruments: multiple IOC stalls

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5323]
Multiple beamlines have reported that various IOCs stalled at 07:30 or so this morning. This affects both "soft" iocs (e.g. RUNCTRL, GWBLOCK) and IOCs that communicate with hardware (both serial and ethernet).

Current solution: restart IBEX server

Beamlines where we've restarted the server:
- MAPS
- GEM
- LET
- INES

Beamlines where we have asked them to restart the server at a convenient time:
- LARMOR
- IRIS

**Comment by ThomasLohnert** [comment]
Also had calls this morning which I though resolved by just restarting individual IOCs. This was before we realised there was a wider issue, so they might still be in an unhappy state.

MARI: lots of blocks showed disconnected, restarted GWBLOCK
IRIS: Eurotherm 01 did not update calibration file readback, restarted Eurotherm IOC

**Comment by Tom-Willemsen** [comment]
Attempt at diagnosis so far:
- We think this may be related to some errors which are coming up in the windows event log at the same sort of time on each instrument
- "Most" of the affected ioc still works - e.g. channel access, console commands, etc.
- It is possible for this issue to affect only some of the PVs within a single IOC
  * This may be because the issue kills only one scan thread within an IOC
- The time of the failure is between 07:00 and 09:00 on most instruments. Not all instruments suffer this problem at exactly the same time.

**Comment by davidkeymer** [comment]
INES reported inconsistencies between jaw gaps reported by the OPI and the relevant motor positions in the table.  A restart of the IBEX server remedied the situation.

**Comment by DominicOram** [comment]
> We think this may be related to some errors which are coming up in the windows event log at the same sort of time on each instrument

What's the error? Might be useful to know if I see it again whilst on call

**Comment by FreddieAkeroyd** [comment]
Error in system log related to WMI performance service having multiple restarts. It seems not all values on an IOC stop updating, so current theory is that the deviocstats module (which monitors some performance counters) had an issue and hung, this then hung the db scan thread (1 second?) that is was using, but channel access and things reading at other polling rates were OK. I have added a nagios alert for IOC time (as per devIocStats) stopping updating.

**Comment by Tom-Willemsen** [comment]
+1 POLARIS, TOSCA, OSIRIS this morning at ~0400 hrs

**Comment by DominicOram** [comment]
A rather thrown together script that should pick up any IOCs that are out of date:
```
import mysql.connector
from genie_python.genie_cachannel_wrapper import CaChannelWrapper
from genie_python.channel_access_exceptions import UnableToConnectToPVException, ReadAccessException
import json
import zlib
from datetime import datetime

def get_value(pv):
    try:
        print("Getting {}".format(pv))
        return CaChannelWrapper.get_pv_value("{}".format(pv, to_string=True))
    except (UnableToConnectToPVException, ReadAccessException):
        print("Warning, couldn't get {}".format(pv))
        return None


def get_inst_list():
    pv_value = get_value("CS:INSTLIST")
    decompressed_json = zlib.decompress(pv_value.decode('hex'))
    return {} if pv_value is None else json.loads(decompressed_json)

inst_list = get_inst_list()

bad_iocs = []
bad_instruments = []

for instrument in inst_list:
    try:
        if instrument['isScheduled']:
            print(instrument)
            mydb = mysql.connector.connect(
              host=instrument['hostName'],
              user="report",
              passwd="$report",
              database="iocdb"
            )

            cursor = mydb.cursor()

            cursor.execute("SELECT iocname FROM iocdb.iocrt WHERE running = 1;")

            for ioc in cursor:
                try:
                    ioc_time = get_value("{}CS:IOC:{}:DEVIOS:TOD".format(instrument['pvPrefix'], ioc[0]))
                    datetime_object = datetime.strptime(ioc_time, '%m/%d/%Y %I:%M:%S')
                    diff = datetime.now() - datetime_object
                    print("{} {}: {}".format(instrument['pvPrefix'], ioc, datetime_object))
                    if diff.seconds > 30:
                        bad_iocs.append((instrument['pvPrefix'], ioc, datetime_object))
                        print("WARNING, {} {} is out of date".format(instrument['pvPrefix'], ioc, datetime_object))
                except:
                    bad_iocs.append((instrument['pvPrefix'], ioc, datetime_object))
    except:
        bad_instruments.append(instrument['pvPrefix'])


print("Out of date iocs: {}".format(bad_iocs))
print("Instruments not connected: ".format(bad_instruments))
```

**Comment by DominicOram** [comment]
It picked up potential issues on IMAT, OSIRIS, MARI

**Comment by FreddieAkeroyd** [comment]
On MARI it is still the issue from last week - they have been emailed about restarting

**Comment by DominicOram** [comment]
Is this ticket still in progress or now covered by https://github.com/ISISComputingGroup/IBEX/issues/5328?

**Comment by Tom-Willemsen** [comment]
+1 LOQ 14th April ~0700, again correlated with WMI restarts

**Comment by FreddieAkeroyd** [comment]
We could put either a static instetc ioc or a new ibex snapshot on LOQ and see if it reoccurs? INSTETC is certainly hung at the time you mention.

**Comment by FreddieAkeroyd** [comment]
HRPD seemed to refuse to hang...

**Comment by Tom-Willemsen** [comment]
Given how infrequently this occurs on each instrument individually, I'm not convinced we'll catch it if we only put a patched version on one or two instruments. I would be tempted to build a static instetc with the changes to devIocStats and run it up standalone on all (or at least a good number) of the ibex instruments, with a nagios check to tell us if and when they fail.

**Comment by DominicOram** [comment]
We could release it as part of https://github.com/ISISComputingGroup/IBEX/issues/5389?

**Comment by FreddieAkeroyd** [comment]
I have updated the above ticket to mention deploying a staic instetc
