### ISSUE TITLE
EMU: Deploy booster heater scripts [Tasks: Shutdown]

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5324]
As an EMU scientist I was to be able to use my booster heater scripts. This work was completed in #5133, but we are waiting for the shutdown to deploy the code.

The code is held in the instrument settings git repo, in branch NDXEMU_booster_scripts

### Acceptance criteria
- [x] Branch NDXEMU_booster_scripts has been merged into NDXEMU

**Comment by kjwoodsISIS** [comment]
How many points?
