### ISSUE TITLE
Update devIocStats module

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5328]
We recently had multiple stalls on IOC #5323 Current theory is this was caused by a hang in the devioc stats module trying to read performance counters. Having looked at the code of the version we are using, the db runs in synchronous rather than asynchronous operation mode and so a hang in reading could stall the database. In later versions of devIocStats the statistics are collected in separate timer queues and so there is no chance of the database scan thread becoming hung. I propose that we update the devIocStats module as soon as possible, certainly in time for next release but we probably sooner in case we have to deploy a hotfix before cycle ends (we currently do not know what caused multiple wmi restarts across multiple instruments at around the same time and so it may happen again - and the consequences are quite bad if it does)

**Comment by FreddieAkeroyd** [comment]
We may be able to mitigate things by disabling selected 1 second scans currently in devIocStats

**Comment by ChrisM-S** [comment]
methinks that updating/reloading performance counters (now that this has happened again at a somewhat random time - and this time out of hours) might be part of the virus checker updating something.  It may be a feature of the current straddle between old and new versions.  Should see if #5323 occurs again on NIMROD, POLREF or OFFSPEC (which would be the counter case).

**Comment by FreddieAkeroyd** [comment]
It is difficult to test this, unless you can reproduce the hang, which we think is WMI related. Maybe stop/start the wmi service a few times and see if any ioc stalls? If you have reprduced the issue then the TOD or HEARTBEAT will stop updating (the issue hangs any task on 1 second scan). 

If you cannot reproduce a hang, treat it like a dependency update and confirm PVs are still working as before e.g. the two above and something like  MEM_USED

**Comment by DominicOram** [comment]
Make sure to try WMI as Freddie said. If this does reproduce the issue create a system test for it.

**Comment by DominicOram** [comment]
If it doesn't then release this on to an instrument and see if it fixes it

**Comment by DominicOram** [comment]
@ChrisM-S is going to check if it's still happening on instruments so that we can test this fix

**Comment by DominicOram** [comment]
The WMI checks are currently still occurring on HRPD:
```
TimeCreated           Id Message                                                                                                                             
-----------           -- -------                                                                                                                             
30/03/2020 15:11:09 1000 Performance counters for the {42ee8dc0-98ba-4455-a673-79bf514ff632} (Sophos Endpoint Defense) service were loaded successfully. The 
                         Record Data in the data section contains the new index values assigned to this service.                                             
30/03/2020 15:11:09 1001 Performance counters for the {42ee8dc0-98ba-4455-a673-79bf514ff632} (Sophos Endpoint Defense) service were removed successfully.    
                         The Record Data contains the new values of the system Last Counter and Last Help registry entries. 
26/03/2020 09:11:08 1000 Performance counters for the {42ee8dc0-98ba-4455-a673-79bf514ff632} (Sophos Endpoint Defense) service were loaded successfully. The 
                         Record Data in the data section contains the new index values assigned to this service.                                             
26/03/2020 09:11:07 1001 Performance counters for the {42ee8dc0-98ba-4455-a673-79bf514ff632} (Sophos Endpoint Defense) service were removed successfully.    
                         The Record Data contains the new values of the system Last Counter and Last Help registry entries.       
```
So we should see if IOCs are still hanging on there before and after this fix

**Comment by FreddieAkeroyd** [comment]
INSTETC started and we just need to check on IN:HRPD:CS:DEVIOS:INSTETC_01:HEARTBEAT and see if it hangs. Interestingly the times look a multiple of 6 hours apart, almost exactly

**Comment by Tom-Willemsen** [comment]
On both my machine and DEMO I tried reproducing the problem by repeatedly starting/restarting the WMI performance adapter service - I could not reproduce the issue using the old code. Treating this like a dependency update.

Do we have a system on which the bug was happening consistently with the old code?

**Comment by FreddieAkeroyd** [comment]
It has not hung on HRPD with old code despite restarts in the log, it is currently hung on MUONFE but I don't know if that is repeatable -  see #5384
