### ISSUE TITLE
NIMROD: disk filling up

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5329]
NIMROD are running in event mode and creating files at the rate of 2GB / hour, this is not their usual data rate and is filling up the disk. Nagios warning for NDHNIMROD C: also export only nagios data rate warning. 

I am deleting files from export only (after checking they are on the archive) as a temporary measure, but this either needs a better purge strategy or a bigger disk

**Comment by FreddieAkeroyd** [comment]
I will check with scientists if 2GB / file is required

**Comment by FreddieAkeroyd** [comment]
I think MINAGE needs to be 1 rather than 3 on the data area (export only) purge script

**Comment by FreddieAkeroyd** [comment]
@ChrisM-S will change MINAGE

**Comment by ChrisM-S** [comment]
This change to MINAGE seemed to work - 24 hour skimming seems to be pretty good (unless someone is collecting with monitors in event mode too - which Tris wasn't!)

**Comment by DominicOram** [comment]
Is this now done @ChrisM-S?

**Comment by ChrisM-S** [comment]
Yes, making the trimming more aggressive flattened the curve.

**Comment by DominicOram** [comment]
I'm happy to accept this fixed the issue but I don't believe there's sufficient documentation for anyone other than @ChrisM-S or @FreddieAkeroyd to be able to diagnose if this happens again. There should be documentation somewhere, preferably on the wiki, that details:
* What the purge script does
* Where it lives
* What MINAGE does and whether this fix needs to be implemented across the board

**Comment by FreddieAkeroyd** [comment]
MINAGE is a robocopy qualifier. @ChrisM-S are you happy for archiving details to be on a public wiki page or should we put them on sharepoint/teams?

**Comment by ChrisM-S** [comment]
Probably best to put more detail in sharepoint/teams in the longer term but in the short term I will create a controls ticket with sufficient detail to record where things are and how they can be changed.  Will link here.

/remind me in 1 week to make sure I've done this.

**Comment by kjwoodsISIS** [comment]
This is a "rework" ticket and is marked as "urgent".  Yet it appears to have made no progress in SPRINT_2020_04_30.  What is preventing it from being completed today?

**Comment by DominicOram** [comment]
I stand by my rework comment, I'm happy to call it done once there is documentation

**Comment by ChrisM-S** [comment]
Now published at

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Computer-Troubleshooting#data-disk-available-space

**Comment by DominicOram** [comment]
Great, thanks @ChrisM-S!
