### ISSUE TITLE
WISH: Unable to communicate with MERCURY

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5330]
Instrument scientists had connected the Mercury in their standard way (COM port 30, MOXA port 10) but the front panel VI was not connected.

After checking the setup for the Mercury VI it was found that the baud rate was set to 115200 but needed to be 57600.

I showed them how to find the setup dialog and edit the baud rate to troubleshoot in the future.

**Comment by DominicOram** [comment]
Sounds good
