### ISSUE TITLE
command prompts: disable quick edit mode

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5331]
As an instrument scientist I would like any scripts running in a windows console window (e.g. start ibex server) to not hang if I click in the window.

@FreddieAkeroyd suggested we could override this behaviour by "disabling quick edit mode".

Acceptance criteria

- running the new program stops "select" appearing in a window when it is clicked on

**Comment by FreddieAkeroyd** [comment]
Acceptance criteria

- running the new program stops "select" appearing in a window when it is clicked on

**Comment by FreddieAkeroyd** [comment]
I have had mixed success with the enclosed PR's in windows 10, works on my laptop, not on office. They try to both disable QuickEdit mode in the registry (for future console) and for the local console, but the "future" may only take effect on a logoff/logon or reboot. Would be interesting to see what Windows 7 does.
