### ISSUE TITLE
FINS PLC: Specify node the PLC is on

### ISSUE THREAD

**Issue by Alexandru-Dascalu** [ISISComputingGroup/IBEX#5332]
Currently, the asyn driver that handles communication with the gas recovery FINS PLC makes the assumption that the node the PLC is on is the same as the last byte of the IP address. This assumption is correct for most PLCs, but not for the gas recovery FINS PLC. 

As a developer, i want the asyn driver in the FINS support module to be able to support nodes that are not the assumed default for the PLC.

**Comment by Alexandru-Dascalu** [comment]
The asyn driver is a Diamond driver modified by us, and it is at https://github.com/ISISComputingGroup/EPICS-FINS/blob/master/FINSApp/src/finsUDP.c .

**Comment by Alexandru-Dascalu** [comment]
I have added some tips about regexes here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches#7-macros-and-details .

**Comment by Alexandru-Dascalu** [comment]
In order to be able to run this for the Helium recovery PLC, you need a cmd file in your config folder, an IP address and a node number that I will publish somewhere private to Experiment Controls and link that here.

**Comment by Alexandru-Dascalu** [comment]
In order to be able to run this IOC for Helium gas recovery PLC, you need to have a FINS folder in your configurations folder, which contains a FINS_01.cmd file with the code:
`#Init and connect
finsUDPInit("PLC", "$(PLCIP)", "TCP", 0, "$(PLCNODE=)")

## Load our record instances
dbLoadRecords("${TOP}/db/he-recovery.db","P=$(MYPVPREFIX),Q=HE-RCVRY:")`

**Comment by Alexandru-Dascalu** [comment]
The reviewer should also check that other PLCs still work and that you can read their heartbeat using the default node macro. The reviewer should DM me on Teams so that I can give them the IP address and heartbeat memory location of another PLC.

**Comment by Alexandru-Dascalu** [comment]
The IP and node number of the Helium gas recovery PLC can be found at http://www.facilities.rl.ac.uk/isis/computing/instruments/Lists/Instrument%20Control%20Computers/AllItems.aspx?InitialTabId=Ribbon%2EListItem&VisibilityContext=WSSTabPersistence&View=%7Bdb428d46-cf6a-4c9a-b2f8-7289856773df%7D&SortField=Manufacturer&SortDir=Desc&FilterField1=Manufacturer&FilterValue1=Omron

**Comment by DominicOram** [comment]
Once this ticket is merged you will presumably want to add `$(PLCNODE=)` to all the other `.cmd` files out there? Otherwise this macro would not work. In which case you should add it in to the upgrade script.

**Comment by DominicOram** [comment]
Tested with the IP address/node supplied, happy that it would fall back to the default case but I can test another PLC if you want, just sent me the details. All looks good, just some minor quires.
