### ISSUE TITLE
LSICORR: Add emulator and tests

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5336]
As a developer I want to be able to automate the testing of the LSI correlator code. The LSI correlator code in IBEX is split in a vendor-supplied python library (https://github.com/ISISNeutronMuon/LSI-Correlator) and a PCASpy EPICS driver (https://github.com/ISISComputingGroup/EPICS-LSICorrelator). The IOC system tests written as part of #4918 only test the ability to read/write values correctly to PVs.

This ticket is to write an emulator for the LSI correlator. This will probably involve mocking out the various function calls in the LSI vendor driver and checking that they have been called at the appropriate times.

### Acceptance criteria:
- [ ] Function calls to the LSI vendor API can be tested with an emulator or similar
- [ ] Tests exist for the API calls used in the LSI correlator

**Comment by DominicOram** [comment]
"Emulator" will likely have to be a flag passed to the IOC to get it to run in a simulated way.

**Comment by John-Holt-Tessella** [comment]
Being done as part of #5633  please move along with it.

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/320
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/372
- https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/8
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/538

**Comment by JamesKingWork** [comment]
Work done in: https://github.com/ISISComputingGroup/IBEX/issues/5633.

Only code needs reviewing not the handover, so review to be done as this ticket

**Comment by DominicOram** [comment]
Can we move some of the points over from the other ticket? At least as much as you estimate is required for any review + potential rework

**Comment by Alistair-McGann-Tessella** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/320
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/372
- https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/8
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/538
- https://github.com/ISISComputingGroup/EPICS-icpconfig/pull/7
- https://github.com/ISISComputingGroup/EPICS/pull/228

**Comment by DominicOram** [comment]
Looks good, I also added https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/icpconfig
