### ISSUE TITLE
IOC: CRISP Flipper system

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5338]
As an instrument scientist I want to run a polarised neutron experiment, this means I need to coordinate a kepco and spin flipper.

### Acceptance Criteria

- An experiment can be run that sets the kepco and ISIS Flipper Power Supply
- An IOC, emmulator and opi exists for the ISIS Flipper Power Supply. It has the following commands, of which I think only up and down are used:
    1. dn: set flipper down reply is OK\r\n
    1. up: sets the flipper to up reply is OK\r\n
    1. id: read identity, identity returned
    1. pl: pulse

### Notes

See vi: ...\LabVIEW Modules\Large Scale Structures\CrispAnalyzerStage\Flip Field - Flipper and Kepco.vi

Connection appears to be 9600, 8 bits 1 stop bit no parity

It looks like you trigger the main vi which sets the flipper either up or down and kepco voltage similarly. The voltage and current are constant. Then you set the flipper to down. But see vi.

I think easiest to do is create the flipper as an IOC and write a script to do the coordination.

**Comment by KathrynBaker** [comment]
It might be easiest to write a script – but this could be a continuously running script, and it may be more usable and sustainable to put the logic for the control in the IOC, or in an IOC at least – I don’t think we would want it reliant on anything else to function if we can avoid it.

**Comment by FreddieAkeroyd** [comment]
Can this logic be done in lua or snl? If this is a piece of equipment controlling both a flipper and a kepco, and it makes sense to bind them together, then an ioc can be created with device support for both

**Comment by John-Holt-Tessella** [comment]
I think the actions that are needed are set kepco voltage, set flipper direction, set flipper to down. 

It looks like this was just triggered from an open genie script. So they already need a script that does everything but this. I should get hold of that script and see what it looks like.

If this is the case I think that a script will suffice. I will double check with the scientists what their current script does.

**Comment by Tom-Willemsen** [comment]
- [ ] This device/setup appears to be lacking a wiki page, could we add one please
- [ ] It's not clear to me that the acceptance criteria of the ticket have been met. In particular, the ticket talks about "coordinating a spin flipper and kepco", but I can't see any logic implementing this coordination.
- [ ] Currently we won't be able to tell when the device is disconnected as we don't poll for anything. I think we should poll for `ID` and alarm when we can't read it (and propogate that alarm to other records as appropriate)
- [ ] Comments on most of the PRs

**Comment by John-Holt-Tessella** [comment]
Sorry my fault I said above I would contact the scientists to ask about the coordination and I haven't. Let me do that now.

**Comment by Tom-Willemsen** [comment]
Coordination logic split into https://github.com/ISISComputingGroup/IBEX/issues/5415

**Comment by adalator** [comment]
Rework summary:
* Added wiki page https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CRISP-Spin-Flipper
* Split off new ticket for kepco coordination
* Added a record to poll the id channel of the device and raise an alarm on no response, along with emulator record and a test that this works
* Tidied up OPI
* Fixed up top level EPICS PR
* Minor fixes in support files, ioc files, test framework, and emulator.

**Comment by DominicOram** [comment]
Leaving to @Tom-Willemsen to re-review but assigning to myself for timebeing
