### ISSUE TITLE
Backup anything required for development

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5339]
As a developer I would like to be able to carry on working if the ISIS networks are not accessible.

Some places that we definitely need to copy things out of:
* Sourcesafe
* ICP_binaries
* P2 repos

== Acceptance Criteria ==
* A comprehensive list is made on this ticket of what needs to be backed up
* These are backed up to somewhere away from the ISIS network
* We do not need to put this somewhere that we can all access yet, we can do this as a separate ticket when if it's required

**Comment by DominicOram** [comment]
@FreddieAkeroyd will ask FIT where they suggest putting this info. In the mean time can we start making a comprehensive list of what we need to backup on this ticket

**Comment by Tom-Willemsen** [comment]
From doing this a few days ago on my Tessella machine, some requirements to get started:

GUI
- `shadow/ICP_P2`
- `shadow/ICP_Binaries`
- `inst$\kits$\compgroup\icp\ibex_client_jre`
- `inst$\kits$\compgroup\icp\Java_utils`

EPICS
- `shadow/ICP_Binaries`

Genie_python
- `inst$\kits$\compgroup\icp\genie_python_dependencies`
- `inst$\kits$\compgroup\icp\genie_python_dependencies_python_3`

General:
- `inst$\Kits$\CompGroup\ICP\Developer Tools`
- `inst$\Kits$\CompGroup\ICP\tools`
- `inst$\Kits$\CompGroup\ICP\MYSQL`
- `\\isis\shares\ISIS_Experimental_Controls_Public\ibex_utils`
- `\\isis\shares\ISIS_Experimental_Controls_Public\third_party_installers`

**Comment by FreddieAkeroyd** [comment]
See #5340

**Comment by ChrisM-S** [comment]
Snapshot of source safe in `inst$\Kits$\CompGroup\VSS-202003.7z` - after unpacking, you would need to point the VSS client to wherever the data folder is now located - it's 4GB compressed.  May contain some proprietary software & manuals.

**Comment by KathrynBaker** [comment]
Can we also add \shares\ISIS_Experimental_Controls\Manuals to the list.

**Comment by DominicOram** [comment]
@FreddieAkeroyd would inst$\Kits$\CompGroup\ICP\EPICS\Symbols be useful too?

**Comment by DominicOram** [comment]
Backed up to my personal OneDrive, if reviewer drops me a message I'll give them a link to it

**Comment by FreddieAkeroyd** [comment]
@DominicOram ICP\EPICS\Symbols is only an aid to debugging, it is a quick lookup of the pdb files already shipped with build kits in kits$.  So it doesn't stop a build and doesn't stop debugging, just speeds it up a bit especially when using a remote debugger and your local symbols may not match that on the remote system
