### ISSUE TITLE
Meeting: discuss critical systems and operations on potential site closure

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5340]
Scheduled for Friday 20/3 - it is likely any closure would be like a Christmas break in the first instance, so people would be allowed on site to fix issues but working on site would be not be possible. So servers would be able to be left on.  Meeting will discuss what systems we and users depend on and consequences if these need to be switched off in the event of an escalation. It will then generate further tickets as required.

**Comment by DominicOram** [comment]
What's left to do on this? I'm happy to call it done given that we had the meeting and https://github.com/ISISComputingGroup/IBEX/issues/5339 was what came out of it
