### ISSUE TITLE
Reflectometry: Mirror and Guide on INTER

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5341]
As an INTER scientist, I would like to be able to swap my mirror/guide between being a mirror and guide. This requires that the component has two states:

- mirror: component acts as a mirror reflecting the beam, component tracks the beam
- guide: component does not effect the beam, component tracks the beam with an offset applied to it

### Acceptance criteria:

- mirror can be in two states

### Notes

I think the best way to do this is to use the inbeam parameter this deals with the reflecting and not effecting the beam. To make it track the beam we add a parameter to OutOfBeamPosition which means that it tracks the position with an offset. This should be a minor change because it already knows where the component is so it can have multiple park positions.

So driver would read:

```
add_driver(IocDriver(sm2_comp, ChangeAxis.POSITION, MotorPVWrapper("MOT:MTR0304"),
                         out_of_beam_positions=[OutOfBeamPosition(offset=-23)]))
```

**Comment by John-Holt-Tessella** [comment]
pull requests:

- https://github.com/ISISComputingGroup/EPICS-refl/pull/10

**Comment by ThomasLohnert** [comment]
Works great! Just missing some little bits of doc
