### ISSUE TITLE
IOC: Danfsyik auto on/off 

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5346]
We got an email from Muonfe instrument scientist:

>My "turn off beamline" script for south side muons turns the magnet power off  with cset ("UB1_POWER",0) etc but does not zero the setpoints (so that manual Power On will restore them if required).
>
> This time, the Danfysik 9000 series supplies all stayed on and at their usual currents. There was no error message or purple borders. Investigation controlling via the OPI and watching/listening in real life shows they turn off and immediately turn back on again. I think it's the Auto Power Off 
feature getting in the way.
>
> As a work around, the new "Sweep to zero and turn off" button sets the current to zero, but does not turn off the power relays. It's then necessary to click "on" (which does nothing) and then "off" which turns the supply off, since the on/off buttons only allow you to send the opposite command to the state the button pair is now showing, unrelated to the adjacent ON indicator!

**Comment by John-Holt-Tessella** [comment]
I said:

>The behaviour you describe sound like it is correct. If the set point is not zero then auto on-off should set the power supply on because the set point isn’t zero. 
I think what you are asking is if I manually set the supply to off then temporarily disable auto on-off and switch it off. Then when I next click on then switch it back on. I think this will lead to multiple edge cases. I think it would be better for you to add the switching off of auto on-off to your script if that is what you want it to do. However I think it might be even better to just have an on script and an off script which just set the voltages.

**Comment by John-Holt-Tessella** [comment]
Point was this shouldn't have been added to the system as is. I agreed and pointed him at #5268

**Comment by DominicOram** [comment]
After discussion with @John-Holt-Tessella I think I agree that this is covered by https://github.com/ISISComputingGroup/IBEX/issues/5265 and https://github.com/ISISComputingGroup/IBEX/issues/5268
