### ISSUE TITLE
Script Generator: Able to append or overwrite parameters from data file.

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#5348]
Currently, when loading parameters, the Script Generator will append the parameters to its table. Having an additional option to overwrite parameters will give users more flexibility.

#### Acceptance Criteria:
- [ ] User is given an option to either overwrite or append parameters from a data file
- [ ] Can successfully append/overwrite parameters to the table
- [ ] If there aren't any actions already in the table, don't ask whether to append or overwrite

**Comment by adalator** [comment]
Added acceptance criteria to not prompt when table has actions in

**Comment by adalator** [comment]
Leaving the group, someone else will need to rework this.

**Comment by JamesKingWork** [comment]
As this was completed not as training, should we point it up?

**Comment by kjwoodsISIS** [comment]
yes.  How many points were required?
