### ISSUE TITLE
script checker: output shown in red

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5350]
When a script is loaded and checked, information is printed in red - this is usually the code for errors.

Acceptance criteria:

- information printed when loading a script is in the correct (or at least not misleading) colour i.e. not in red

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/4268 implies print to stderr will appear in red

**Comment by John-Holt-Tessella** [comment]
+1 for one of SANDALS/POLARIS/HRPD

**Comment by mihai-stfc** [comment]
This may have been fixed as me and @John-Holt-Tessella cannot reproduce the issue.
![image](https://user-images.githubusercontent.com/69153228/105863455-d2e1d900-5fe8-11eb-81a1-595c788a39e2.png)
If we still have an issue we can make a more specific ticket down the line. Closing for now.
