### ISSUE TITLE
DEPLOY: After deployment scientist email should include link to release notes

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5353]
As an IMAT instrument scientists after by instrument has been updated I would like a link to the latest release notes.

### Acceptance criteria

- Upgrade script gives message to send to instrument scientists including link

**Comment by adalator** [comment]
The first PR I made was for the wrong upgrade script and should be ignored, as pointed out by Bish in the first review. The second PR contains the correct changes.
