### ISSUE TITLE
ioc test framework: many tests checking for non-existent PV

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5356]
Many IOC tests are printing a message like
```
Warning, TE:SPARE70:RKNPS_01:DISABLE still does not exist after IOC start
```
they are checking for a non-existent PV as a test the IOC has started. The unit tests seem to get run anyway, so this is just adding an unnecessary delay (10 seconds) to these tests

Is this the right PV to check? Should all IOCs have a disable record? Or should we use something from devIocStats instead?

Acceptance Criteria
* decide if all IOCs should have a disable record, or change to use another PV
* fix IOCs as needed

**Comment by DominicOram** [comment]
You can change the PV it looks for using e.g.:
```
IOCS.append(
        {
            "name": "INSTETC",
            "directory": get_default_ioc_dir("INSTETC"),
            "custom_prefix": "CS",
            "pv_for_existence": "MANAGER",
        })
```

**Comment by FreddieAkeroyd** [comment]
All IOCS load the EPICS devIocStats module and so should have a HEARTBEAT PV somewhere

**Comment by John-Holt-Tessella** [comment]
Added to sprint as training ticket

**Comment by aaron-long** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/367

**Comment by aaron-long** [comment]
### Updated
Updated various tests to check valid PV's for their existence when starting the driver (these failed local testing but now pass):

    - SM300 
    - READASCII 
    - motionSetpoints 
    - GAMRY 


### Works locally but failed on system tests
- RKNPS 

RKNPS has a `DISABLE` record and works fine on manual local test. However in some instances you would see the warning on system tests ioc runs:

```
12:11:32  Generating XML reports...
12:11:32  Terminating IOC (RKNPS_01)
12:11:32  IOC log written to C:\Instrument\Var\logs\IOCTestFramework\log_tests_rikenportchangeover_recsim_RKNPS_01_ioc.log
12:11:32  Testing module tests.rikenrb2modechangeover in Rec sim mode.
12:11:32  Check that IOC is not running
12:11:36  Starting IOC (RKNPS_01)
**12:11:48  Warning, TE:NDWRENO:RKNPS_01:DISABLE still does not exist after IOC start**
12:11:48  
12:11:48  Running tests...
12:11:48  ----------------------------------------------------------------------
12:17:02  ...........
12:17:02  ----------------------------------------------------------------------
12:17:02  Ran 11 tests in 311.995s
12:17:02  
12:17:02  OK
```

### Fails locally
- SIMPLEIOC 

Has `DISABLE` record but fails. I'm unsure why this is behaving this way.

## Unsure on how to proceed
- MOXA12XX: Multiple .db for various versions that are templated. Needs a common record across versions.
- INHIBITR: Tests multiple IOCS (Inhibitr + Simple) in a single run.

**Comment by DominicOram** [comment]
Great start, fixes it for the ones you have modified, thank you. For the others:
* SIMPLE seems fine, it's not failing to find the PV on the build server?
* INHIBITOR and MOXA12XX. The pv to check for is on a per IOC basis so you should still just be able to add it in to the config for that IOC, regardless of whether there's other PVs being started see `sans2d_apertures_guides` for an example
Others that need fixing:
* RKNPS (rikenportchangeover and rikenrb2modechangeover )
* DMA4500M_01
* fermi_chopper_lifter
* linmot

**Comment by John-Holt-Tessella** [comment]
I think I messed this up. It looks like @aaron-long move it to review but didn't update the labels but i missed it and thought Dom had forgotten to move it back to ready. Moving to review with labels, please correct if wrong
