### ISSUE TITLE
GUI: Improve look of IBEX on HD screens

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5364]
As an IBEX user I would like the GUI to look functional on a 4k screen. This has mostly been reported by the cryogenics team.

## Acceptance Criteria
- The IBEX GUI looks similar on HD machines as on standard def

**Comment by John-Holt-Tessella** [comment]
Same/similar to #4328

**Comment by DominicOram** [comment]
Closed in favour of other one
