### ISSUE TITLE
CRISP: IOC & OPI for MicroEpsilon Confocal Rangefinder

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5365]
As a CRISP instrument scientist I would like to control a MicroEpsilon Confocal Rangefinder.

#### Acceptance Criteria
1. I can use IBEX to view two height values provided by the device.
1. I can use genie_python to access PVs corresponding to the two height values.

#### Notes
1. Rob Dalgliesh has already written a VI, called [MicroEpsilon_ConfocalDT.vi](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/CRISP/MicroEpsilon_ConfocalDT.vi) (based on some Python code provided by Freddie).
   1. A copy of the VI can be obtained from the [CRISP folder](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FCRISP&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) on the ICP Discussions site
1. Notes provided by Rob:
   1. The device can be set up in a number of ways but the only one I have got to work serves 2 doubles over the network which are height values in mm in real time. 
   1. The device itself is a bit awkward in that the IP address is assigned via DHCP only after it is told to do so and  so the address needs to be set each time it is setup and plugged.
   1. The VI opens a connection and then looks to make sure that the first 4 characters of the ASCII converted string are ‘DATA’ and then extract the required numeric data. 
      1. If nothing goes wrong the tcpip connection is then left open and data streamed into a SECI block. 
      1. If the first 4 characters are not ‘DATA’ for whatever reason the tcpip connection is closed and then reopened in order to get everything back in sync.
1. Some Python code [MicroEpsilon.py](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/CRISP/MicroEpsilon.py) for reading the data structures served by the device and publishing them onto the Ethernet is available in the [CRISP folder](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FCRISP&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) on the ICP Discussions site

**Comment by Tom-Willemsen** [comment]
Is there a manual for this device? I am aware of the VI and python code but have not been able to find the manual against which they were presumably developed.

**Comment by KathrynBaker** [comment]
Ask the IS - or try https://www.micro-epsilon.co.uk/service/download/manuals/, it is plausible that there is only a hardware manual that was used for the design, hopefully @FreddieAkeroyd can comment on that side of things

**Comment by Tom-Willemsen** [comment]
PRs:
- Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/79
  * Note: needs https://github.com/ess-dmsc/lewis/pull/283
- IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/502
- Support: https://github.com/ISISComputingGroup/EPICS-MECFRF/pull/1
- Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/325
- EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/211
- OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1107
- Docs: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Micro-Epsilon-confocal-rangefinder

**Comment by ThomasLohnert** [comment]
Rework (Fix IOC description and a couple questions):
- [ ] https://github.com/ISISComputingGroup/EPICS-ioc/pull/502
- [ ] https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/325
- [ ] https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/79

**Comment by DominicOram** [comment]
Update to lewis, which this requires, has been done in https://github.com/ISISComputingGroup/IBEX/issues/5400

**Comment by Tom-Willemsen** [comment]
@ThomasLohnert are you able to re-review this before the end of the sprint, or should we take rework off so that someone else can finish the review?

**Comment by Tom-Willemsen** [comment]
@ThomasLohnert I'll take the rework label off this so that someone else can finish the review
