### ISSUE TITLE
Web Dashboard: Discuss use of the WAP dashboard

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5366]
As a support person I would like to be able to monitor instruments on a mobile device.

### Acceptance Criteria

- There is a discussion with support groups (specifically JN's group raised this to start) to see what their requirements are for remote viewing, specifically what kind of devices they are using, bandwidth issues, do they need WAP or HTTP etc.
- These requirements are written down
- A solution to these requirements is implemented

### Notes

- Currently the WAP page is at http://wap.isis.rl.ac.uk/Dashboards/inst.htm
- The current IBEX web dashboard for an instrument needs normal html and javascript to function correctly

**Comment by DominicOram** [comment]
Email sent to JN

**Comment by JamesKingWork** [comment]
+1

**Comment by DominicOram** [comment]
I think there's been a break down in communication for what JN wants here (see emails from ISISExperimentControls). I've got a meeting with him next week to discuss

**Comment by DominicOram** [comment]
Just had a meeting with Jamie, he's happy if we retire the WAP solution and redirect the mobile web pages to http://dataweb.isis.rl.ac.uk/Dashboards/default.htm
