### ISSUE TITLE
Script Generator: Rename params file

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5371]
As a user it's confusing that saving the script generator parameters gives me a `.json` file. JSON is our implementation but to the user it should be a more meaningful file extension e.g. `.script_gen_params`.

## Acceptance Criteria
* Saving a parameters file in the script generator results in a file with a more meaningful extension
* Loading parameters still works correctly with this new extension

**Comment by John-Holt-Tessella** [comment]
Short extensions are more the norm, so maybe `.sgp`

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1248

**Comment by DominicOram** [comment]
Added into sprint as a training ticket
