### ISSUE TITLE
Genie_python: Warn if waiting on an unlikely value

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5380]
As a user I would like to be warned if my script is likely to wait indefinitely. A common thing that I would like to do is set a block to a value and wait for it to get there. However, it normally makes sense to wait for it to get there within some tolerance. This is possible in genie python with:
```python
g.cset("Motor", 20, wait=True, lowlimit=19.5, highlimit=20.5)
```
However, I could accidentally set a range that the block is unlikely to reach e.g.
```python
g.cset("Motor", 20, wait=True, lowlimit=25, highlimit=27)
```
in which case I would like to be warned. Note that this can only be a warning as there are a number of cases where we will pass through 25-27 on the way to 20.

# Acceptance Criteria

1. The user is warned if they do a `cset` with a wait for a range that is possible to be missed

**Comment by DominicOram** [comment]
Requested by MERLIN

**Comment by aaron-long** [comment]
See comments in `Lib/site-packages/genie_python/test_modules/test_genie_epics_api.py` on the PR
