### ISSUE TITLE
Lua: luaUtils calls result in stack traceback.

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5381]
After some testing with @Tom-Willemsen it looks like there's a bug introduced in either luash or luaUtils that results in some lines in a lua file returning errors on execution. 

## Steps to reproduce
1. Start the OERCONE ioc using the runIOC.bat in the iocs iocBoot directory
1. Check the console log for the `luash("st-common.lua")` call
1. You should see a stack trace for the `st-common.lua`, with an error such as: 
```
lua: stdin:1: attempt to index nill value (local 'utils')
```

## Acceptance Criteria
- [ ] Bug identified and fixed
- [ ] IOC's that use luash calls have been checked (TWINCAT, OERCONE, etc) to function as expected

**Comment by aaron-long** [comment]
As far as I can tell no. 

In the case of the TwinCAT `st-common.lua`, the     `local getMacroValue = utils.getMacroValue` line causes the traceback but subsequent calls of the `getMacroValue` method that was defined work.

**Comment by DominicOram** [comment]
@JamesKingWork has discussed LUA and scopes on tech-talk, there may be a patch to help

**Comment by DominicOram** [comment]
Timebox to 2.5 days + 0.5 days for review. If not fixed re-evaluate Lua

**Comment by JamesKingWork** [comment]
> @JamesKingWork has discussed LUA and scopes on tech-talk, there may be a patch to help

I don't recall seeing this before, but yes this could be the utils falls out of scope for some reason, could try just calling utils.getMacroValue from inside the function?

**Comment by DominicOram** [comment]
Repointing as the fix actually only took .5 days (2 points). Expect review to bring it up to 3 points total.
