### ISSUE TITLE
GUI: Autocomplete needs to be fixed in the GUI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5391]
Autocomplete for `g.load_script("` no longer works in the gui and should be fixed. This is probably because of the upgrade in pydev.

### Acceptance Criteria

- tab can be pressed after typing  `g.load_script("` and scripts in c:\scripts are shown
- There are system tests that cover this

### Notes

- It looks like pydev no longer defaults to using IPython underneath. It can be made to I think see `...\workspace\.metadata\.plugins\org.eclipse.pde.core\.bundle_pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevconsole.py` or we should write the plugin for pydev forcompleters

**Comment by DominicOram** [comment]
Can we get a system test on this?

**Comment by DominicOram** [comment]
Timebox to 2.5 days.

**Comment by DominicOram** [comment]
I looked at this briefly. I couldn't find any way of getting out the currently running console in the python. I think there are 4 options:
1. Keep trying to find a way to hook the python in
2. See if we can find a new way of hooking in to the java
3. Modify pydev (should probably be done in conjunction with https://github.com/ISISComputingGroup/IBEX/issues/5405)
4. Make it use ipython (I've done that at https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket5391_fix_autocomplete)

I think the correct way to do this is 3) but I think in the interests of time we should do 4) and add in tests for this ticket then re-evaluate doing 3) when doing https://github.com/ISISComputingGroup/IBEX/issues/5405. Thoughts?

**Comment by Tom-Willemsen** [comment]
I agree with Dom's comments above and have added a squish test to cover the functionality.

PRs:
- https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/51
- https://github.com/ISISComputingGroup/ibex_gui/pull/1122
