### ISSUE TITLE
Check and fix SNL setpoint sync logic in other iocs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5395]
This is a follow on from #5383 to identify places to fix the setpoint sync logic and also to remove use of epicsThreadSleep in SNL

- [x] jacso 

# Acceptance Criteria
- Remove sleep from JASCO
- Check other IOCs
- Write documentation (make sure it's on the wiki)

**Comment by DominicOram** [comment]
#5397 is related

**Comment by DominicOram** [comment]
Make sure there is a note in the wiki saying not to use sleeps and why

**Comment by FreddieAkeroyd** [comment]
Docs updated at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-State-Machine-(Sequencer)

**Comment by FreddieAkeroyd** [comment]
I believe only small sleep values are in remaining snl, which are just for making sure sets are actioned

**Comment by FreddieAkeroyd** [comment]
To Test: Check JACSO tests pass

**Comment by DominicOram** [comment]
Documentation is good and although I can't reproduce the failing test locally code seems fine. There is a similar wait at https://github.com/ISISComputingGroup/EPICS-ioc/blob/666d15c4e55499163cfc5ff338997c0013f0d7c8/IPS/IPS-IOC-01App/src/cryomagnet.st#L180 is this one not an issue?

**Comment by FreddieAkeroyd** [comment]
I remember seeing that and deciding it was OK, but can't remember the chain of thought...

**Comment by FreddieAkeroyd** [comment]
I have confirmed with @Tom-Willemsen that the sleep is not causing an issue (i.e. it is not causing a setpoint check logic issue like above). Removing the sleep, though desirable, is slightly trickier so I have moved to a separate ticket #5510
