### ISSUE TITLE
Configchecker: fix build

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5396]
As a developer I would like the configchecker build to pass.

It is failing with:

```
Cloning into 'E:\Jenkins\workspace\ConfigChecker\\configs'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: protocol error: bad pack header
```

Running the same command manually on the build server works

**Comment by Tom-Willemsen** [comment]
Looks to have been fixed by some combination of updating git and rebooting the machine.

**Comment by DominicOram** [comment]
Confirmed config checker is now happy
