### ISSUE TITLE
PLACEHOLDER: JSON service(s)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#540]
Having a gateway-style service that returns PV values as JSON might be convenient for web pages and other remote clients.

Example of how it might work:

1. Webpage requests a series of PV values as JSON "['BLOCK1', 'BLOCK2']"
1. Service fetches the values and returns the JSON "{ 'BLOCK1':123, 'BLOCK2':321}"
1. Webpage updates

==Notes==
1. Create a simple prototype.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 541.  Created by mjc23 on 2014-10-24T10:29:30, last modified: 2014-12-04T11:49:41_

**Comment by AdrianPotter** [comment]
Completed as part of updated web dashboard (JSON_Bourne)
