### ISSUE TITLE
Add gamry lewis simulator

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5400]
Add a lewis simulator for the gamry device

This code required unsolicited message support in lewis which is enabled via https://github.com/ess-dmsc/lewis/pull/283

**Comment by DominicOram** [comment]
This is just a minimal emulator to get us started, not designed to test full functionality.

**Comment by Alistair-McGann-Tessella** [comment]
This is fine and is in a state to be merged, but it depends on the latest version of Lewis which hasn't been included in a release yet. I'm moving this to impeded until `unsolicited_reply` is on pypi.

**Comment by Tom-Willemsen** [comment]
I think @DominicOram or @aaron-long might have been given access to push to pypi for lewis?

**Comment by DominicOram** [comment]
Note new PR for genie_python
