### ISSUE TITLE
Scans in Shared Python Scripts: Replace populate

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5401]
https://github.com/ISISNeutronMuon/InstrumentScripts/issues/60

As a developer I would recommend getting rid of populate. It can cause really weird effects if a block is the same name as a module e.g. time

Instead replace with a module which has a class member variable for each active block. On most beam lines this is imported as `b.`. `b.block_name` should return something that is interpreted as a string in `scan(<motion>` and `cset` and `cget`. Ideally it should update itself when the blocknames change.

### Acceptance Criteria

- A decision is made on populate and the decision is recorder. (must be agreed in general between scientists)
    - done they are happy to remove it if they can replace it with `b.`
- Populate is removed
- Documentation is updated
- a blocks module is added that has a list of blocks variable in.
- Tests for any code change are added

### Notes

- This is a breaking change so maybe we just shouldn't
    - we should because it is in the build_ins and can cause weird problems in the future

- Its purpose is to create variables which can be used instead of block names so that scan can be written: scan(block, ... instead of scan("block", .... But it comes with caveats that when the user changes config they must remember to rerun populate to get new blocks and it is different to the recommended way of running g.cset i.e. cset("block", value). However I do not know the history and so would like to understand its motivation.

- interpreted as a string: could mean just a return a string but maybe there is a way of returning a more complicated object that will evaluate to a string but have more complicated properties like units etc. This might eventually allow us to do `b.blockname.scan(-0.5, 0.5, 1)` or `b.blockname.cset(10)` or even `b.blockname = 10`.

**Comment by FreddieAkeroyd** [comment]
This is a hang over from VMS and not wanting to add quotes. I created global variables like this in Open GENIE for CSET and they were initialised when a user typed GETBLOCKS on the genie command line, they needed to type this for other reasons than just creating the variables. Whenever you modified blocks in SECI  you were prompted to type "getblocks", if you changed config in SECI genie was killed so it would get reloaded too.

In genie python we didn't implement the global variables, so you don't need to type get_blocks(), but must use quotes. Given removing populate() is a breaking change, we should make the case to the scientists - I think it is worth making that case though.

**Comment by DominicOram** [comment]
@John-Holt-Tessella to change acceptance criteria to be implementation + tests

**Comment by John-Holt-Tessella** [comment]
Larmor, Inter and Polref instrument scineitst were happy to remove populate but wanted to keep a way of defining blocks without typing strings. (Some issues had been found with populate in the past) @FreddieAkeroyd has suggested that we create a "b." modules which lists all the blocks as member variables. This should be doable and may be useful for other beamline too. So I am changing the acceptance criteria for this ticket to include that and will get feedback from the IBEX team

**Comment by John-Holt-Tessella** [comment]
Pull request:

- https://github.com/ISISComputingGroup/genie_python/pull/249
- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/62

Docs at:

- https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Scripting
