### ISSUE TITLE
Reflectometry: Custom script from reflectometry perspective

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5410]
As a reflectometrery user I want to set my instrument into a specific state espeacilly when I go into the block house to setup a sample. On SURF this involves moving the monitor out of the way, on some of the other instruments they need FOMs and charge sheets moving as well. The suggested way to accomplish this is to have a custom script button on the OPI which the user could press which would run user chosen steps in the backend. 
Other people have asked for similar OPI based script buttons is this something we want to implement in the script server or more generally in the system? #3271

### Acceptance Criteria

1. Decide on implementation
1. Have a button on the front panel that allows configurable items to be parked out of the beam
1. Decide if this fulfils #3271 if so close it
1. Decide if this fulfils #2444 if so close it

**Comment by kjwoodsISIS** [comment]
I can see that many instruments might want to use a button on the GUI to run a script.  The use-case is not confined to Reflectometry.  Obviously, we should create a general mechanism that allows the user to execute an arbitrary (configurable) script in response to a button press.  Presumably, in some cases, the user will want to use other fields on the GUI as input to the script.

**Comment by John-Holt-Tessella** [comment]
@Kevin-Woods-Tessella it is probably true that people would want parameterised script but maybe starting small is the way forward, the immediate need is a script which executes on a button press.

**Comment by ChrisM-S** [comment]
Probably worth being really clear about where the script is run if we are providing a general mechanism - even for what looks like a simple monitor parking script rather than a full scan script.
Would/should the script always be run in the script server or are we accepting the permanence of scripts run in the client by the GUI?

**Comment by John-Holt-Tessella** [comment]
@ChrisM-S When I orginally asked the question I saw the reflectometry server running the script. So it is running on the instrument and not in the GUI. I don't want to pass it to the script server because this script might be run at the same time as a user script. But if it is more general maybe the background script server runs it. That would certainly be easy espeacilly if that script monitors pvs set up in the instetc ioc which can be configured in the config directory. Then we have bascially all the moving parts we just need to put them together.
In fact the more I think of it like this the better. I like the separation between script and pvs because the users don't have to understand pycaspy.

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - I do not envisage scripts running in the GUI.  At most, the GUI button invokes the script.  But the script **_always_** executes on the server.

**Comment by KathrynBaker** [comment]
Please see ticket #2444 – this has already been requested (nearly three years ago) by the muon teams for the south side front end, and was re-requested for the north side front end. This already exists as a request outside of reflectometry.

**Comment by DominicOram** [comment]
> I don't want to pass it to the script server because this script might be run at the same time as a user script.

NICOS does have the ability to run commands outside of the currently running script, we could use it if we think it helps.

**Comment by John-Holt-Tessella** [comment]
How hard is that to do? How hard is it to retro-fit?

**Comment by DominicOram** [comment]
There's `exec` and `eval` (https://github.com/mlz-ictrl/nicos/blob/a42d96f1228cde91cf2ad037655a28e88cc44443/nicos/services/daemon/handler.py#L451) Not hard to do but I don't know if it's the best way to go. They're normally meant for doing one or two lines of code.

**Comment by kjwoodsISIS** [comment]
What is the likelihood that a user script will actually be running at the same time as the custom script?  From the description, it sounds as if the custom script is for exceptional situations (e.g. "I need to go into the blockhouse to change a sample.").  In such circumstances, it seems unlikely that a user script will be running at the same time.  Would it be sufficient merely to check that another script was running and warn the user?

**Comment by FreddieAkeroyd** [comment]
There are situations currently when a user script is running and the scientist need to do something and adjust the beamline. Often they will pause collection, close shutter, enter blockhouse and do some csets and then start everything up again. It may be the SE is never going to reach temperature withouit intervention, so they want to leave the script reunning and execute a few other commands.  Or they need to restart a piece of beamline equipment, but ity would cause a spike in data acquisition, so they want to pause dae, execute script, resume dae, leaving script running as it. It may be sufficient for them to type a command in a genie python window as these are probably not user executed operations.

**Comment by John-Holt-Tessella** [comment]
pull request:

- Documentation https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inst-etc-IOC
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/541
- https://github.com/ISISComputingGroup/ibex_gui/pull/1203
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/377
- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/76
