### ISSUE TITLE
IOC system tests: indicate that IOC failed to start (i.e. no tests run)

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5411]
As a developer i would like the IOC system tests to report all reasons for test failures in the Jenkins summary page. Currently only errors for tests that were able to be run (i.e. the IOC can be launched successfully) are reported, if the IOC fails to start and so no tests are run then no error is reported in the jenkins summary. 

The overall test status is marked as bad if an IOC does not start, so the jenkins job would never be marked as success, but this does lead to a misleading summary of the status of the test suite and means that a set of tests could be failing to run at all and this may not be noticed for a long period unless the log file is checked carefully.

## Acceptance criteria

* Failure to start IOC (i.e. to run any tests at all) is clearly indicated as a failure in the test summary log in jenkins

## To test
* check tests run OK
* modify st.cmd of IOC used in test to make sure it fails to start e.g. add msgBox to make st.cmd hang. Check failure reported

**Comment by John-Holt-Tessella** [comment]
Someone else also asked for this. As it is the second request maybe we should do this.

**Comment by FreddieAkeroyd** [comment]
It isn't a complex change and was annoying me in my attempt to get all the system tests working, so PR above from one hour this morning...
