### ISSUE TITLE
IOCTestFramework: restart an IOC mid-test

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5412]
As a developer I would like to be able to test IOC initialization logic using the IOCTestFramework, so that I can test IOCs such as the danfysik which send commands at startup.

### Acceptance criteria

- A general mechanism exists in the IOC test framework for restarting an IOC mid-test.
- Tests are written for the danfysik using this new mechanism which prove that restarting the IOC does not change the state of the emulator (In particular the current and whether it is powered on)

### Notes

There are currently two distinct IOC launchers:
- IocLauncher which is used by most of the tests but doesn't currently have the ability to restart the underlying IOC mid-test.
- ProcServLauncher which can restart IOCs mid-test but seems to be unable to pass macros through to the underlying IOC correctly.

**Comment by DominicOram** [comment]
Made a start on this: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket5412_restart_an_IOC_mid_test procserv now picks up macros and will work for recsim/devsim. Left to do:
* Tidy up more, there's still a lot of shared code between IocLauncher and ProcServLauncher which could be moved into BaseLauncher
* Write the danfysik test

**Comment by DominicOram** [comment]
Linked PR is merged as it was required for another ticket. Can the reviewer just check if the danfysik tests pass (see the linked PR for some details)

**Comment by JamesKingWork** [comment]
> Linked PR is merged as it was required for another ticket. Can the reviewer just check if the danfysik tests pass (see the linked PR for some details)

These tests now work for me, not sure what happened before, must have been in a funny state. Fix for broken calibrated tests done as a flash review https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/351
