### ISSUE TITLE
Config checker: Speed Up

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5414]
As a developer I would like to be able to run the config checker manually in a reasonable time. Currently it takes ~40 minutes to run, which is too long to realistically be run manually. Speed it up

#Acceptance Criteria
* Config checker takes < 5 minutes to run or if not possible document why

**Comment by Tom-Willemsen** [comment]
This may be due to most of the instruments being offline and therefore many channel access calls hitting timeouts. We may be able to shorten the channel access timeouts.

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/InstrumentChecker/pull/29

**Comment by FreddieAkeroyd** [comment]
Could you use `git-worktree` to have multiple branches available from one repository?

**Comment by FreddieAkeroyd** [comment]
@Tom-Willemsen  If an instrument is not "up" is it you don't just want to skip it entirely from "run_all_tests" as you can still check out stuff in the repo?

**Comment by Tom-Willemsen** [comment]
Most tests you can still do even if an instrument is down (e.g. verifying XML). It's only a few tests that require the instrument to be up. They do get automatically skipped if the PVs aren't available (to avoid failing tests when an instrument is just down)
