### ISSUE TITLE
CRISP flipper: co-ordination with kepco

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5415]
As an instrument scientist I need to co-ordinate the flipper which was added in https://github.com/ISISComputingGroup/IBEX/issues/5338 and KEPCO power supplies.

@John-Holt-Tessella is in contact with the scientists to get more details of this coordination logic

### Acceptance Criteria

1. Get feedback from scienitsts of what to do
1. Either:
    - write an IOC which pulls in required 
    - **or** write a script which does the coordination

### Notes

Estimated based on script by HOLJ

**Comment by adalator** [comment]
Please make sure to update the wiki when this ticket is complete: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CRISP-Spin-Flipper

**Comment by John-Holt-Tessella** [comment]
Code is run from a script call pol_run on CRISP so we do not need them coordinated in the IOC. Closing the ticket.

Will write the script with the scientists when we can test on the machine.
