### ISSUE TITLE
Create Jenkins build to make stand-alone Script Generator Releases

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5418]
As an IBEX developer, I would like a Jenkins build to make releases of the stand-alone Script Generator, so that I can generate releases of the stand-alone Script Generator in the same way that I can create releases of IBEX Server and IBEX Client.

#### Acceptance Criteria
1. The build process assigns an identifiable release number to the stand-alone Script Generator.
1. The build process copies the stand-alone Script Generator to the appropriate release folder.

Documentation added: 
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release
#### Notes
1. Release number should follow the usual semantic versioning pattern - M.N.O.
1. Our aim should be to always have a "shippable release" of the stand-alone Script Generator.
1. The stand alone Script Generator will be useful to scientists when ISIS re-starts after the Coronavirus lockdown.  They can send the Script Generator to remote users, who can generate scripts and send them to instrument scientists (who will execute them on behalf of the remote user).  Having a controlled release process for the stand alone Script Generator will help us in providing support for this mode of operation.
1. NB Release number will be defined by the person running the procedure. The release should also appear on the releases page with, IBEX GUI and Script generator should be differentiable (https://github.com/ISISComputingGroup/ibex_gui/releases)

**Comment by John-Holt-Tessella** [comment]
I think we decided that the script generator release number would **not** be the same as the IBEX GUI release number. Are we still happy with this? If so what do the different levels mean

**Comment by Tom-Willemsen** [comment]
We probably want the release-numbering scheme for the script generator to match up with the numbering scheme used by the GUI so that we can refer to both the embedded and standalone versions by the same version number.
