### ISSUE TITLE
HRPD: Low Temperature Sample Changer (testing in beam week commencing 14 December 2020)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5420]
As a scientist on HRPD I'd like to be able to automatically change samples at a low temperature

**Acceptance Criteria**
1. There is a component with
* ~Details for the extra sensors and heaters - these will be controlled by a Eurotherm (there will be an extra crate)~ Using current eurotherm just changed the sensor
* The setup for the McLennan stage which drives the sample changer
1. There are appropriate motion setpoints in place for the three positions that are available

**Notes**
1. This is ISP 857
1. This is currently planned as an interim solution, a new design may be forthcoming after the long shutdown
1. This is *not* the robot!
1. It will be using a linear sample changer borrowed from MERLIN that we may not have used yet for the motion aspect, it will be driven by a McLennan
1. This is simply 3 samples on a vertical linear stage, with the motion setpoints describing which sample is in the beam and the others simply out of the way, samples are 57mm apart, and the limits are beyond those three positions.

**Comment by KathrynBaker** [comment]
Update: Added lakeshore to the above, but this is unlikely to be something we have not encountered before, will verify which closer to installation. Likely to be available next cycle

**Comment by KathrynBaker** [comment]
Manufactured parts due in at the beginning of September, before cycle start - they will need assembly after that

**Comment by KathrynBaker** [comment]
Corrected description based on confirmation from JB about the sensor reading

**Comment by KathrynBaker** [comment]
This is currently being built and wired, adding proposal at least until it is known when this will be used on the beamline.

**Comment by KathrynBaker** [comment]
The window for testing is the last week of the cycle before Christmas, but the bulk of the component should be creatable offline on a test system and transferable to HRPD beforehand.

**Comment by John-Holt-Tessella** [comment]
Controller config is setup but device is not yet present so not working yet. Settings are:

Encoder Ratio 1/20
Steps/mm 400
Upper soft limit 50100
Homing to neg limit
Window 5
Tracking 400
1st position 4400
2nd position 27200
3rd position 50000

**Comment by John-Holt-Tessella** [comment]
Lakeshore not needed
