### ISSUE TITLE
Reflectometry: Create full Polref beamline (probably in simulation mode)

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5424]
As a developer I would like a simulated reflectometry beamline so I can discuss it with the scientists while having a concrete item.

### Acceptance Criteria

1. An initial script to create motor setup
    - initial one in `<share>\Reflectometry\configs\POLREF\POLREF_motor_config.bat` needs check fixing, axis initialisation and axis pre-move command
1. Jaws settings also in that directory with galil settings (home routines set to dummy)
1. A configuration for POLREF
    - there was no NDXPOLREF branch so created one based on the current config.

### Notes

The config may need both a vertical and horizontal config.

**Comment by John-Holt-Tessella** [comment]
List of config stuff from polref


## Must Fix


1. Create Vertical config
    1. In vertical config - how to cope with sample chi=90 +- offset for sample
    1. In vertical config - park position now on trans axis which is a direct parameter  #4902
1. FOM: park set the angle to 0 as well as z
1. Bench: Component which encapsulate seesaw based on tilting components #3465 rewritten
1. Bench: driver for the bench takes angle, displacement and seesaw #3465 rewritten
1. Components: allow them to be `on` something 
1. Analyser Mirror1: park in in trans direction
1. PD/BENDER: Macro read in
1. Swap between vertical and horizontal mode? macro
1. S3: Allow it to act as a beam blocker, in mutliple directions

## Desirable?

1. lots of components have a chi and trans which we treat as direct components, good/bad?


## Unknown info

### Critical
S4: Is this on the pd?
S4: how does this effect the resolution?
S4: If the point detector is not in are these in
S0: Does this effect the resolution?

FOM: unpolarised and polaraised theta are different is this engineering correctiopm, i.e. if I chose theta = 3 would it be somewhere inbetween?   (pol: theta=1.6 and z = 32 unpol: theta=5.8 and z=30)

### Can cope with knowing later
Current Sheet: z position
Current Sheet: park position

Analyser flipper: z position on bench
S3: height stage?
S3: z position on bench
AM1: z position on bench
AM2: z position on bench
S4: z poistion on bench
Bender offspec analyser: Which motor drives chi? Do you need to change motor settings?
Point Detector: z position on bench
Multi Detector: z position on bench

**Comment by John-Holt-Tessella** [comment]
Split into 2 tickets inital investigation #5434 and this one.

**Comment by John-Holt-Tessella** [comment]
Problems with motor config:

15 axis initialisation 
1 after move

Homing routines not know:
Front Guide Z - MTR0107: Home routine does `XQ #GuideHm,2` Do we support this?
Pt Det Z - MOT0503 : Home routine XQ#HmPtDtZ,3
Pt Det Y - MOT0505 : Home routine XQ#HmPtDtZ4
Slit 2 Tilt - MOT0605:  Home routine XQ #Hms2ti,2
Bench Front Z - MOT 0601: #XQ #HmHt,2
Bench Arch - MOTO 0604: #HmArc,4

**Comment by FreddieAkeroyd** [comment]
does labview load lots of custom homing routines then?

**Comment by John-Holt-Tessella** [comment]
I don't know where I would look to find that out but this was what was in the motor config box

**Comment by John-Holt-Tessella** [comment]
Email sent about homing routines:
> I am looking at the homing routines that POLEREF uses. For the minute this is not the most important thing to sort out because we will not be homing in EPICS but at some point we need to set it up. I am slightly puzzled by what I am seeing in SECI. There are 6 custom homing routines defined on the axes but only 2 uploaded to the galils. Do you know what happened to the other homing routines? The details are:
> 
> Two that exist are:
> 
> Front Guide Z - MTR0107: GuideHm
> Slit 2 Tilt - MOT0605: Hms2ti
> 
> The four which don’t are:
> 
> Pt Det Z - MOT0503 : HmPtDtZ
> Pt Det Y - MOT0505 : HmPtDtZ
> Bench Front Z - MOT 0601: HmHt
> Bench Arch - MOTO 0604: HmArc
> 
> Thank you for your help,

**Comment by John-Holt-Tessella** [comment]
Homing routines can wait until long shutdown see ticket #5608.

**Comment by John-Holt-Tessella** [comment]
Pull requests:

- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/67

**Comment by ThomasLohnert** [comment]
Some questions/comments for the actual POLREF `config.py`:
- There are a number of TODO comments still in there, not sure how important they are immediately but I think we should at least have a plan for resolving these:
    - Actual current sheet Z coordinate (currently just uses FOM coordinate)
    - Parameter/Component for monitor in/out  is missing
    - Components on Bench all have placeholder Z coordinates
    - Out of beam positions for current sheet, point detector, bender have placeholder values
- S2 engineering correction is commented out, do we need this?
- `gimble_comp` should be `gimbal_comp` (same goes for given component name)
- outdated reference to marker replacement in comment for theta comp should be removed

**Comment by John-Holt-Tessella** [comment]
TODO comments added to testing ticket #5462 
TODO S2 engineering correction is waiting on Cristy added to testing ticket #5462 

All other instances corrected
