### ISSUE TITLE
Script Generator: Installation Process to Create Necessary Folders & Files

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5428]
As a user of the ScriptGenerator, I would like the installation process to create all the folders & files needed for correct operation, so that I can use it without first having to contact support.

### Acceptance Criteria
1. On installing the ScriptGenerator, the folder containing the script definitions is created.
1. On installing the ScriptGenerator, the script definitions folder is populated with example files.
1. On installing the ScriptGenerator, a folder to contain my generated scripts is created.

### Notes
1. This issue arsies from attempting to install the ScriptGenerator from one of the builds in `\Kits$:\ICP\script_generator` folder.  I do appreciate that this is not a release folder.  However, the problems highlighted in this issue do need to be addressed before we can release the ScriptGenerator.
1. The purpose of the ScriptGenerator is to help people with limited programming skills create genie_python scripts.  It needs to operate in two environments:
   1. docked in the IBEX GUI
   1. in standalone mode (either on the instrument server, on a scientist's office (or home) PC, on a user's office (or home) PC.
      * users, in particular, will be using the ScriptGenerator away from ISIS (i.e. at their home university or research facility).  They won't have easy access to the Experiment Controls group for support.  The ScriptGenerator has to be easy to install and easy to use.
1. On installing the ScriptGenerator from one of the builds in `\Kits$:\ICP\script_generator`, the `C:\ScriptGenerator` folder is not created.  When you then start the ScriptGenerator you are presented with an alarming message: 
![image](https://user-images.githubusercontent.com/7249337/82443591-a826a480-9a99-11ea-8d49-b5b1ac27db86.png)
Some users will find this message perplexing, at best. If the `C:\ScriptGenerator` folder is necessary to the operation of the ScriptGenerator, it needs to be created during the installation process.
1. On installing the ScriptGenerator from one of the builds in `\Kits$:\ICP\script_generator`, no example script definition files are provided.  The user cannot generate scripts without script definition files, which means that he has no obvious way to get started.  We need to provide some examples to get them started.
   * Of course, the instrument scientists will ultimately provide script definition files, but instrument scientists themselves also need a way of getting started.  We should give them a way to do so, instead of presenting them with a blank canvas and no obvious way to proceed.
1. On using the ScriptGenerator to save a generated script, the save operation fails if the `C:\Scripts` folder does not exist: 
![image](https://user-images.githubusercontent.com/7249337/82443492-82010480-9a99-11ea-9b07-b857b8e16a49.png)
If the `C:\Scripts` folder is necessary to the operation of the ScriptGenerator, it needs to be created during the installation process.
1. In the short-term, the installation process could be improved (and the above acceptance criteria satisfied) by providing simple written instructions telling users to create the necessary folders.

**Comment by Tom-Willemsen** [comment]
Acceptance criteria 1 & 2 should probably be done via https://github.com/ISISComputingGroup/IBEX/issues/5026 .

**Comment by John-Holt-Tessella** [comment]
Also we want it to keep itself up-to-date probably so it should be the app itself which update/creates the definitions. I suspect 3 and 4 will also be updated by this.
5 should be covered by allowing the user to save to any directory with the default being that folder.
We should not consider this releasable except in beta until #5026 has been done because we don't want scripts to end up in random places.

**Comment by DominicOram** [comment]
The saving to any directory, which John alluded to is covered by #5425

**Comment by John-Holt-Tessella** [comment]
Right then so 6 see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/The-IBEX-Script-Generator#pre-release-install-instructions which is roughly what I did and sent to instrument scientist.

**Comment by RaiBishal** [comment]
### To summarise:

- Acceptance criteria 1 & 2 to be done in #5026.
- Acceptance criteria 3 corresponding ticket #5425.
