### ISSUE TITLE
Datastreaming: Add system tests for ICP/filewriter integration

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5430]
As a developer I would like to be sure that the ICP continues to integrate with the filewriter to write valid nexus files that contain event data.

## Acceptance Criteria
* There is a system test that starts/stops a run through the ICP and confirms that the filewriter creates a valid NeXus file with event information.

**Comment by DominicOram** [comment]
Pointing to reflect how long I actually spent on this.

**Comment by DominicOram** [comment]
Changing points to reflect only review required

**Comment by DominicOram** [comment]
For testing building the ICP locally is a pain. However the build server will push the result of the ICP PR to `CompGroup\ICP\ISISICP\DAE3\DEV\configure_broker\1\service\x64`. You should then be able to replace your local ICP (at `ICP_Binaries\isisdae\x64`) with this one to test.

**Comment by FreddieAkeroyd** [comment]
Replacing just the isisicp binaries may caused an issue if the isisicp.default.properties is then out of date. I've added a new file to make this easier, if you open the latest numbered subdirectory in  `CompGroup\ICP\ISISICP\DAE2\DEV\configure_broker` you should find an `update_dev.bat` which if you run will update the `ICP_Binaries\isisdae` files on your local computer

**Comment by ThomasLohnert** [comment]
Some questions on https://github.com/ISISComputingGroup/system_tests/pull/45

Please also add information about adding your user to the `docker-users` group at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Datastreaming#system-tests

**Comment by DominicOram** [comment]
Given all associated PRs are merged and system tests are passing I'm going to call this done, thanks @ThomasLohnert and @FreddieAkeroyd
