### ISSUE TITLE
Reflectometry: Bench Component and Beamline Parameters

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5432]
To allow for an extra angle with the bench (see-saw) and for chi and trans on most components in polref I would like the bench component to be written which includes this extra axis. This should be done generically.

# Acceptance Criteria

- I can set a see-saw value on the bench component which is available to a driver to act on. This adds this number to a j1 and takes it away from j2.
- There is a beamline parameter that can set the bench component
- Beamline parameters can be added to a arbitary axis in a component
- Setting the angle on the bench sets the arc which the bench follows.
- setting the height on the bench set the extra height above the floor
- it is clear how theta interacts with the bench
- new configs are created and put on surf and crisp
    - to be done after merge

# Notes

Plan:
1. add beamline parameter which is see-saw (remove distinction between parameters and add axis - either keep old parameter classes or rewrite config)
1. add component for bench which has 4 axis 
   - tracking height
   - tracking angle (theta)
   - chi
   - see-saw
1. movement strategy

**Comment by John-Holt-Tessella** [comment]
pull request:

- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/337
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/298

**Comment by ThomasLohnert** [comment]
Rework:
- [ ] https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/298
- [ ] https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/337
