### ISSUE TITLE
FINS: add TCPNOHEAD protocol option

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5436]
The existing Lewis frameworks assumes TCP connections. To make it easier to develop an emulator, add a TCPNOHEAD option to do TCP connections with no FINS TCP header (i.e. UDP message sover a TCP link)

Lewis is also dynamically allocates an emulator port, to get the IOC to connect to this port rather than the default port 9600 pass the value of  EMULATOR_PORT as follows
``` 
$(IFDEVSIM) finsUDPInit("PLC", "$(PLCIP):$(EMULATOR_PORT=)", "TCPNOHEAD")
```

**Comment by Alexandru-Dascalu** [comment]
Added some documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PLCs#testing-the-fins-ioc-in-devsim .
