### ISSUE TITLE
DEPLOY: Create IBEX Release [After 15th July]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5441]
As a developer I want to create an IBEX release so I can install it on the instrument machines 5 weeks prior to the start of Cycle 02/2020 (i.e. aim to release in w/c 27th July 2020, or earlier).

#### Acceptance Criteria:
- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)
- [X] [Create a ticket to give instrument demos](https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos) 
     - #5443 
- [x] Distribute release notes via email [Instrument scientist release email](https://github.com/ISISComputingGroup/IBEX/wiki/Instrument-scientist-release-email)
- [x] Script definitions on EMU are handled correctly. Currently they are in a separate repository but the repo has been renamed and put inside the script generator itself. So make sure no scripts are lost and that they are up-to-date after deploy. (This may need a step adding to the upgrade script to check)

#### Notes:
1. Cycle 02/2020 is expected to start on 8th September 2020.
1. ISIS has not been operating since mid-March; the return to work will impose unusual operating conditions.  Scientists will need plenty of time to make sure IBEX is running on their instruments.  Therefore, we should aim to complete deployment of IBEX before 3rd August, to provide scientists with 5 weeks to get used to the new release (test their scripts, check for bugs, etc.).

**Comment by DominicOram** [comment]
Repointed based on final tagging and review required

**Comment by DominicOram** [comment]
I believe @ChrisM-S sent the release notes email around as part of another set of emails. Dependency update ticket is https://github.com/ISISComputingGroup/IBEX/issues/5584. @JamesKingWork have you handled the EMU scripts?

**Comment by JamesKingWork** [comment]
I have handled the EMU scripts
