### ISSUE TITLE
DEPLOY: Deploy IBEX to instruments

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5442]
As a developer I want to deploy IBEX to instrument machines 5 weeks prior to the start of Cycle 02/2020 (i.e. aim to complete deployment by 3rd August 2020, or earlier).
#### Acceptance Criteria
 - [ ] Deploy IBEX to instruments listed below
 - [ ] Ensure that version numbers on [IBEX page](https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information) is up to date

#### Notes:
1. Cycle 02/2020 is expected to start on 8th September 2020.
1. ISIS has not been operating since mid-March; the return to work will impose unusual operating conditions.  Scientists will need plenty of time to make sure IBEX is running on their instruments.  Therefore, we should aim to complete deployment of IBEX before 3rd August, to provide scientists with 5 weeks to get used to the new release (test their scripts, check for bugs, etc.).
1. Muons (EMU) have requested that IBEX be installed in late July (rather than early August).
   * suggest deploying to EMU on 23rd or 24th July.

**Comment by kjwoodsISIS** [comment]
## Full Deployments 
#### ALF
- [ ] Started
- [ ] Completed

#### CRISP
- [ ] Started
- [ ] Completed

#### DETMON (impossible to do for now, DETMON can't access shares drive even with the credentials added)
- [ ] Started
- [ ] Completed

#### EMMA
- [ ] Started
- [ ] Completed

#### EMU
- [ ] Started
- [ ] Completed

#### ENGINX
- [ ] Started
- [ ] Completed

#### ENGINX_SETUP
- [ ] Started
- [ ] Completed

#### GEM
- [ ] Started
- [ ] Completed

#### HRPD
- [ ] Started
- [ ] Completed

#### IMAT
- [ ] Started
- [ ] Completed

#### INES
- [ ] Started
- [ ] Completed

#### IRIS 
- [ ] Started
- [ ] Completed

#### IRIS_SETUP 
- [ ] Started
- [ ] Completed

#### LARMOR
- [ ] Started
- [ ] Completed

#### LET
- [ ] Started
- [ ] Completed

#### LOQ
- [ ] Started
- [ ] Completed

#### MAPS
- [ ] Started
- [ ] Completed

#### MARI
- [ ] Started
- [ ] Completed

#### MERLIN
- [ ] Started
- [ ] Completed

#### MUONFE
- [ ] Started
- [ ] Completed

#### NIMROD
- [ ] Started
- [ ] Completed

#### OSIRIS
- [ ] Started
- [ ] Completed

#### POLARIS
- [ ] Started
- [ ] Completed

#### RIKENFE
- [ ] Started
- [ ] Completed

#### SANDALS
- [ ] Started
- [ ] Completed

#### SELAB (check with JN before doing)
- [ ] Started
- [ ] Completed

#### SOFTMAT
- [ ] Started
- [ ] Completed

#### SURF
- [ ] Started
- [ ] Completed

#### TOSCA
- [ ] Started
- [ ] Completed

#### VESUVIO
- [ ] Started
- [ ] Completed

#### ZOOM
- [ ] Started
- [ ] Completed

## Deploy Mini-Inst

#### INTER
- [ ] Started
- [ ] Completed

#### MUSR
- [ ] Started
- [ ] Completed

#### OFFSPEC
- [ ] Started
- [ ] Completed

#### POLREF
- [ ] Started
- [ ] Completed

#### SANS2D
- [ ] Started
- [ ] Completed

#### SXD
- [ ] Started
- [ ] Completed

**Comment by JamesKingWork** [comment]
Instruments with Python 3 issues in their inst scripts:
ENGINX (and ENGINX_SETUP), VESUVIO

**Comment by Alexandru-Dascalu** [comment]
Mini-inst deployments are to be done after Windows updates are installed by @ChrisM-S

**Comment by JamesKingWork** [comment]
IMAT is now an exception and has been put on the pending tasks board https://github.com/ISISComputingGroup/IBEX/issues/5594

**Comment by Tom-Willemsen** [comment]
All machines deployed to or accounted for elsewhere (e.g. reflectometry and IMAT)
