### ISSUE TITLE
DEPLOY: Plan Demos to Instrument Scientists [After 15th July]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5443]
As a developer and supporter of IBEX I want to demo the changes being deployed to the instrument scientists and teams that use IBEX before the start of Cycle 02/2020.

#### Acceptance Criteria
1. https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos is updated for this release:
   1. There is a list of items to highlight - those applicable to all instruments especially (individual instrument highlights are the responsibility of the hosts of the demo)
   1. The instrument groupings have been updated appropriately based on the list of instruments being deployed to (see #5441 and #5442)
   1. New Demo host teams have been assigned to the instrument groupings
1. Demo hosts are informed that the table has been updated.
1. All demos have been scheduled.
1. The feedback from the demos have been posted on the IBEX Wiki and have been linked on the Timetable for Instrument Demos page. 

#### Notes:
1. Cycle 02/2020 is expected to start on 8th September 2020.
1. ISIS has not been operating since mid-March; the return to work will impose unusual operating conditions.  Scientists will be busy restoring their instruments to full operational order.  Please ensure demos are scheduled well ahead of Cycle 02/2020, so that 
   1. there is no rush at the end (when time is tight)
   1. scientists are not informed of an important change only after Cycle 02/2020 has started.
1. Whilst the scheduling of demos is the responsibility of the host teams, this ticket should not be considered closed until the demos have been scheduled. This gives whoever takes on this ticket the requirement to ensure that the hosts at least schedule meetings to undertake the demo, the meetings themselves do not need to take place to consider this ticket done

**Comment by Tom-Willemsen** [comment]
Timetable for demos: https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos
Release highlights appropriate for all instruments: https://github.com/ISISComputingGroup/IBEX/wiki/Instrument-demos-July-2020 (this does not include instrument-specific tickets)

**Comment by JamesKingWork** [comment]
Is this probably impeded waiting for demos to be complete and feedback to be posted?

**Comment by Tom-Willemsen** [comment]
I put it in review based on the following in the notes section:

> the meetings themselves do not need to take place to consider this ticket done

**Comment by JamesKingWork** [comment]
> 
> 
> I put it in review based on the following in the notes section:
> 
> > the meetings themselves do not need to take place to consider this ticket done
> 
> Happy to put it into impeded if you prefer though.

Fair point, I think this may contradict acceptance criteria 4. I suppose that note more refers to the effort that the person has put in planning the demos has been done. Probably makes more sense to drop it in impeded until they have been done, I'll put it into there

**Comment by DominicOram** [comment]
@mihai-stfc and I will review this together tomorrow
