### ISSUE TITLE
Builds: remove use of p: or use different drive letter in different job types

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5445]
A genie python build failed with an error, which is hard to determine exactly from the message, but would be consistent with the p: drive disappearing. Several jobs map p: and if two of these happen to start running at the same time then one could delete/reassign p: from what the other job was expecting.

I'm not sure p: is really needed - I think it was maybe because xcopy had issues with long paths, but robocopy has no such issues. If it is not possible to remove, then different classes of jobs (genie python, client, epics) should map different letters in case they run simultaneously. 

Acceptance criteria

* "net use p:" is removed, or different letters used by different job classes

**Comment by FreddieAkeroyd** [comment]
```
18:48:41   if "3" == "3" (copy E:\Jenkins\workspace\genie_python_pipeline\package_builder\\genie_python_install_3.bat p:\Kits$\CompGroup\ICP\genie_python_3\BUILD-848\genie_python_install.bat )  else (copy E:\Jenkins\workspace\genie_python_pipeline\package_builder\\genie_python_install_2.bat p:\Kits$\CompGroup\ICP\genie_python_3\BUILD-848\genie_python_install.bat ) 
18:48:41  ) 
18:48:51  The system cannot find the drive specified.
```
Happened again ... i think it is when a genie python PR is approved quickly, then both a genie_python_pipeline and genie_python_pr_pipeline are running at same time. The first job to finish does a "net use p: /d" and breaks the other. Could just remove the delete at the end as a temporary measure.

**Comment by DominicOram** [comment]
Fixed by https://github.com/ISISComputingGroup/genie_python/pull/307 so closing
