### ISSUE TITLE
genie_python: usage statistics

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5447]
As a developer I would like to know who is using which parts of our API. This would be useful as:
* It will give us more confidence in knowing how changes to our API will affect users
* We can target demos of changes to the users that will see the difference the most
* We can get a good idea of what errors are occuring

## Acceptance Criteria
- [ ] (Most of the time, see below) When a user calls a genie_python command the following is logged centrally:
    - [ ] The command called
    - [ ] The arguments it was called with
    - [ ] The instrument it was called from
    - [ ] The time
    - [ ] Any errors that occured
    - [ ] Time commands took to respond
- [ ] Developers are able to search this log in a nice way
- [ ] This is transparent to the user, e.g. if genie_python can't log this data it won't slow down or crash
- [ ] It is sufficient that we just catch most calls, e.g. we can ignore calls being made not on the NDX machine and even ignore those outside the GUI if easier

**Comment by John-Holt-Tessella** [comment]
Part one already sort of exists. All genie commands are logged to `C:\Instrument\var\logs\genie_python` which is readable from anywhere. However it isn't particularly easy to access or get statistics from.

**Comment by rerpha** [comment]
assigning myself as I think this would be a good work experience project.

**Comment by rerpha** [comment]
Some thoughts: 
- Graylog should do all of the above and supports custom filters so we can add the instrument name and so on
- graypy is a nice library for this - can also be output into grafana if we need to see metrics on our grafana instance
- We should use the `logging` built-in for logging in genie python anyway, this would be a good opportunity to set it up and use it

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Graylog created

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/6645 created following on from this

**Comment by rerpha** [comment]
Note that this functionality was not added to the simulation API as it wasn't logging beforehand. This is a replacement and addition to what was previously being logged.

**Comment by rerpha** [comment]
To review: 
- Spin up graylog instance using Docker
- Set up a GELF/UDP input on Graylog, found under System -> Inputs
- Use a command such as cset("text")
- Check it gets put into Graylog and \var\logs\genie_python log file

As a note, we can leave it in the code as it silently doesn't push if there is no graylog instance up, it should still log to file. in #6645 we should change this to point to a central instance.

**Comment by DominicOram** [comment]
* Can you make a breadcrumb for the wiki page please?
* Can you add the 2nd bullet above into wiki page?
I couldn't get the graylog server working. I think it's started up correctly:
![image](https://user-images.githubusercontent.com/10086797/126326068-43a567a3-9567-487e-91d7-693fe5a58a2f.png)
But I can't get into the web interface:
![image](https://user-images.githubusercontent.com/10086797/126326155-3c196dd9-b6c6-4197-b5ea-00bd46d5dac1.png)
When you're back can we have a look at this and make sure the documentation is correct?
I also think that a system test would be good, if possible.

**Comment by rerpha** [comment]
>     * Can you make a breadcrumb for the wiki page please?
> 
>     * Can you add the 2nd bullet above into wiki page?
>       I couldn't get the graylog server working. I think it's started up correctly:
>       ![image](https://user-images.githubusercontent.com/10086797/126326068-43a567a3-9567-487e-91d7-693fe5a58a2f.png)
>       But I can't get into the web interface:
>       ![image](https://user-images.githubusercontent.com/10086797/126326155-3c196dd9-b6c6-4197-b5ea-00bd46d5dac1.png)
>       When you're back can we have a look at this and make sure the documentation is correct?
>       I also think that a system test would be good, if possible.

you need to use 127.0.0.1 instead of localhost, not sure if its a bug but i had the same issue 

will finish this ticket up when i have some time

**Comment by rerpha** [comment]
I tried to set up the inputs etc via a content pack but had no luck after a few hours of playing, so we'll have to manually do that on deployment - the wiki page should show instructions on how to add the inputs. I added a breadcrumb as well.  will have a go at system testing now

**Comment by rerpha** [comment]
system testing is going to be a pain to do as we need to automatically set up inputs and extractors each time the graylog docker container is started which i haven't managed to successfully do

**Comment by DominicOram** [comment]
I added system testing to the creating the central graylog instance ticket
