### ISSUE TITLE
Reflectometry: Parked angle

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5448]
As a POLREF scientist, I would like to have the ability to give a reflectometry component a parked angle (in addition to a parked position). 

#### Acceptance Criteria
- `AngleDriver` can be given a parked position (same as `DisplacementDriver`)
- When moving a component out of the beam via `InBeamParameter`, it moves that components underlying rotation axis to its given park angle
- When moving a component into the beam via `InBeamParameter` it moves the underlying rotation axis to the current given angle of the component

**Comment by ThomasLohnert** [comment]
This is actually covered by #5455. Closing this ticket

**Comment by kjwoodsISIS** [comment]
As noted above, this ticket is covered by #5455, therefore, this ticket is, in effect, a duplicate.
