### ISSUE TITLE
Reflectometry: Add IOC Macros

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5452]
As a reflectometry user I want to be able to change aspects of the IOC without editing the python code. This ticket is to allow (parts of) the configuration to be changed via macro.

#### Acceptance criteria:
- Can pass Macros into the reflectometry IOC
- Add macro `CONFIG_NAME` (defaults to `config.py`) which tells the IOC which refl config to load (on restart)
- Add macros (e.g. `OPTIONAL_COMP_1` etc.) which determine whether to load certain parts of the config (e.g. Bender on POLREF)

**Comment by John-Holt-Tessella** [comment]
The major use of this is when the scientists has to swap between vertical and horizontal mode. This is a manual operation so does not need to happen at run time. They can have different configurations to do this and hence different macros set.

**Comment by ThomasLohnert** [comment]
See also https://github.com/ISISComputingGroup/IBEX/issues/5198

**Comment by FreddieAkeroyd** [comment]
Above PR should provide a command to get macros as a JSON list, and an example bat of how to set an environment variable that could then be used by another program

**Comment by FreddieAkeroyd** [comment]
Macros now returned as a json object rather than array

**Comment by ThomasLohnert** [comment]
To test:
- copy config from `<private controls share>\Reflectometry\Ticket5452` to config area
- set refl IOC `CONFIG_FILE` macro to `config-5452.py`. Confirm correct config is loaded
- set `OPTIONAL` macros.  Confirm beamline constants are correctly created, or not created, based on those (see bottom of config file)
- Confirm config file defaults to `config.py`
- Confirm all IOC tests and unit tests pass.

PRs:
- EPICS Top: https://github.com/ISISComputingGroup/EPICS/pull/219
- inst_servers: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/306
- refl: https://github.com/ISISComputingGroup/EPICS-refl/pull/1
- ioc: https://github.com/ISISComputingGroup/EPICS-ioc/pull/519
- ioc test framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/345
- ibex_gui: https://github.com/ISISComputingGroup/ibex_gui/pull/1153
- utilities: https://github.com/ISISComputingGroup/EPICS-utilities/pull/16
- icpconfig: https://github.com/ISISComputingGroup/EPICS-icpconfig/pull/4

Updated Doc at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Configuration
- mentioned required `macros` argument for `get_beamline`
- added info for `optional_is_set` helper method

**Comment by John-Holt-Tessella** [comment]
Outsatnding pull request to be merged #5556
