### ISSUE TITLE
Reflectometry: Change engineering correction based on mode

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5453]
As a reflectometry scientist, I would like to be able to configure my beamline so that different engineering corrections can be applied based on the current mode. 

On mode change, readback value is updated. Any mismatch with SP should make changes in engineering correction visible.

#### Acceptane Criteria
- It is possible to write an engineering correction that takes the current mode of operation into account for the returned correction value.
- Highlight if any parameters are not at setpoint on the reflectometry front panel

**Comment by John-Holt-Tessella** [comment]
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/302
