### ISSUE TITLE
Jaws: Beam Block Mode

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5456]
As a POLREF user, I would like to be able to operate one of the slits in "Beam Block" mode, meaning one of the blades (e.g. `North`) is driven to its limit away from the beam, while its opposite blade (e.g. `South`) is driven up to block part of the beam. This should work for both horizontal and vertical slits.

To do: confirm with scientists which part of the beam exactly the blocking blade should block

Q: how to deal with gap / centre in block mode?
- disable?
- turn into offset on blocking blade?
A: Want to be able to switch this on and off. In off mode gap and centre should not be set able instead position of blades are setable only. On CRISP we want blade to track the beam.

### Acceptance Criteria
- Slits can switch between "Beam Block" and "Beam Shape" mode

### Notes

Does this need a parameter to set it? If it is in block mode then tracking on blade otherwise tracking on gap centre. How does this work?

**Comment by John-Holt-Tessella** [comment]
On polref:
    OptionalParameter("S3State", options= ["blocker", "south", "east", "West"]) OPI can react to this
    Parameter for S2N, S3E, S3W, S3N

On crisp
     OptionalParameter("S3State", options= ["blocker", "south"])

        IocDriver(s3_comp, ChangeAxis.POSITION, JawsCentrePVWrapper("MOT:JAWS3", is_vertical=True, beamlockerpb=s3beamvlock), synchronised=False))

Thought about making it an axis but decided no because it only has this one very specific use case

**Comment by John-Holt-Tessella** [comment]
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/301
- https://github.com/ISISComputingGroup/ibex_gui/pull/1144
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/341

**Comment by ThomasLohnert** [comment]
Works fine, some minor changes:
- Please hide parameter S3S in CRISP config
- `SURF/vgap.opi` should be `SURF/vgaps.opi`
- Could you please add doc for expected `OPI` constant (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Configuration#beamline-constants)
- Could you please add documentation for how the beam blocking works conceptually on CRISP / POLREF? I think it would be a good idea to create some documentation pages for individual reflectometers and their peculiarities from a reflectometry IOC point of view that we can populate over time

**Comment by kjwoodsISIS** [comment]
Re-pointed by @John-Holt-Tessella from 8 -> 3.

**Comment by John-Holt-Tessella** [comment]
Reworks:

> - Please hide parameter S3S in CRISP config

added `s3_params = add_slit_parameters(3, 0.00200 * 2, beam_blocker="S", exclude=["S"])`

> Could you please add doc for expected `OPI` constant (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Configuration#beamline-constants)

 done

> Could you please add documentation for how the beam blocking works conceptually on CRISP / POLREF? 
>    - I think it would be a good idea to create some documentation pages for individual reflectometers and their peculiarities from a reflectometry IOC point of view that we can populate over time

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-SURF and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-CRISP
