### ISSUE TITLE
Reflectometry: Add laser mode

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5458]
As a POLREF user, I would like to be able to easily switch to "laser mode" which applies a number of parameter values (e.g. FOM, current sheet out, fixed offset on certain components..).

**Note:** "Laser mode" is not just another mode. It can be applied on top of other modes (eg. NR or PNR).

- Might be easiest to implement this as a script
- ~Or could we turn this into a common mode "wrapper" pattern along with disabled mode?~

#### Acceptance Criteria
- Can add a "laser mode" in config which contains a set of offsets for beamline parameters
- When enabling laser mode, all the offsets are applied
- When disabling laser mode, all the offsets are taken off
- Edit POLREF config to contain laser mode (to do: define set of values to apply) 

### Notes

- requires #5410

**Comment by John-Holt-Tessella** [comment]
I need to rewrite acceptance criteria before this ticket is started

**Comment by John-Holt-Tessella** [comment]
- see config directory branch `Ticket5458_laser_mode`
   - see back ground script in the python directory 
   - back ground script in python
   - changes in configs (moving inbeam params to constants)
 - https://github.com/ISISComputingGroup/ibex_gui/pull/1211

**Comment by John-Holt-Tessella** [comment]
Email sent to confirm mode components

With a horizontal sample the modes are NR, PNR, PA and ANR, DISABLE
With vertical sample the modes are NR and DISABLE
In addition there is activate and deactivate laser positions

Component | NR | PNR | PA | ANR | Laser
-- | -- | -- | -- | -- | --
FOM | IN | IN | IN | IN | OUT
Current Sheet | OUT | IN | IN | OUT | OUT
Super Mirror | OUT | IN | IN | OUT | Don’t move
Polarising Flipper | OUT | IN | IN | OUT | OUT
Analyser 1 | OUT | OUT | IN | IN | OUT
Analyser 2 | OUT | OUT | OUT | OUT | OUT
Analysing Flipper | OUT | OUT | IN | IN | OUT
Monitor | IN | IN | IN | IN | OUT

Also in laser mode 
with horizontal sample S1VG = 1, S2VG=1, S3VG=1
with vertical sample S1HG = 1, S2HG=1, S3HG=1

**Comment by ThomasLohnert** [comment]
Works great!
- Are the wrapper methods `laser_mode_on` and `laser_mode_off` in `laser_mode.py` redundant? The background script is calling its own wrapper methods defined in `background_script.py` 
- `BGRSCRPT_01` IOC is missing from POLREF configs - unless `register_ioc_start("BGRSCRPT_01")` in `background_script.py` is meant to start the IOC and I'm missing something?

**Comment by John-Holt-Tessella** [comment]
1. No this is for the user when they want to do it from scripting they can call inst.laser_mode_on
1. We will need to add it to the config when we update their instrument

**Comment by DominicOram** [comment]
@ThomasLohnert should this go in the review complete column?
