### ISSUE TITLE
Reflectometry: write vertical config for POLREF

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5459]
As a POLREF scientist, I need a configuration for running the instrument in vertical mode.

Q: do vertical and horizontal jaw blades swap?
   - No, but it would be nice to do some OPI items see #5477

#### Acceptance Criteria:
- Vertical config maps correct motor axes to tracking position and angle of each component
    - FOM / super mirror: `TRANS` becomes `HEIGHT`, `PSI` needs 90° offset (engineering correction)
    - Sample: `TRANS` becomes `HEIGHT`, `CHI` becomes `PHI`
- Footprint calculator uses horizontal slits instead of vertical slits
- Scripts should calculate resolution using vertical slits
- run angle and transmission need hgaps if they don't have them already

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/16
https://github.com/ISISComputingGroup/ibex_gui/pull/1196

Documentation of axes at 
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-POLREF#sample-stack

**Comment by John-Holt-Tessella** [comment]
In documentation:

- [ ] vertical config  BENCHANGLE  has axis listed as CHI I think this should be ANGLE
- [ ] tests for vertical mode
- [ ] In config:
    - has height2 = False (done)
    - lets delete the modes not comment them out
    - do you think we should have a  common file for distances along the beam line?
    - remove `#correction` section
    - double check FOM in vert mode
    - s2 exclude HC (done)
    - a1 & a2 in beam set to false for nr, and laser modes
