### ISSUE TITLE
POLREF: Testing Time

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5462]
Test reflectometry changes for POLREF on the real beamline

#### Acceptance Criteria

- Install latest Version of refl (hotfix release) on INTER and POLREF
- Install latest IBEX on POLREF
- Commission motor axes

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-POLREF
