### ISSUE TITLE
IBEX GUI: Bundling genie_python

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5463]
As a user I would like the installation of a standalone GUI to be as easy as possible, I would also like there to be as little confusion over which python version I am using as possible so that I can install new python modules.

As of https://github.com/ISISComputingGroup/ibex_gui/pull/995 python is now bundled with the client. Currently the script generator uses the bundled version of python and if it can't find it will use genie_python installed in the usual place. The scripting console does not use the bundled version.

In a meeting with @FreddieAkeroyd, @RaiBishal, @John-Holt-Tessella  and @Tom-Willemsen on 05/06/2020 it was decided that the following should be done:

## Acceptance Criteria
- [ ] The script generator should prefer to use the normal install of genier_python and only look for the bundled version if there isn't a normal one. (This means if a user installs a module into genie_python it will be available in the script generator)
- [ ] Anywhere else in the GUI using python (mostly the scripting console window) should also also do the same. Meaning that if the `normal` genie_python isn't found it will look at the bundled version

**Comment by DominicOram** [comment]
@Tom-Willemsen thinks point 2 is done

**Comment by JamesKingWork** [comment]
> @Tom-Willemsen thinks point 2 is done

Point 2 is mostly done. It uses `PreferenceSupplier.pythonInterpreterPath()` but then doesn't attempt to get the bundled python if that doesn't exist. The script generator uses `PreferenceSupplier.getBundledPythonPath()` which finds the bundled path and defaults to the `C:\Instrument\Apps\Python3\python.exe`.

It sounds like the solution is to call the `PreferenceSupplier.pythonInterpreterPath()` first and if that file doesn't exist then use the bundled python path, but throw and handle an error if neither are there. I would suggest that this is harmonized across both.
