### ISSUE TITLE
POLREF: Install IBEX [on 17th August 2020]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5465]
As a developer, I want to migrate POLREF to use the IBEX instrument control system. This enables us to perform testing of the reflectometry server on the POLREF beamline.

#### Acceptance Criteria
- [x] IBEX is installed on POLREF
- [ ] Motor settings are migrated from SECI
    - to be tested this week with scientist

#### Notes
- [X] #5613 will create a new release for POLREF.  Complete #5613 before implementing this ticket.
- [X] Ask Facilities IT (Anthony Shuttle) to create a private network for POLREF.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
    - being installed on 17th
- [X] Check that NDXPOLREF has sufficient disk space to install IBEX
- [X] Check whether POLREF uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)

**Comment by John-Holt-Tessella** [comment]
Just go through motor setup checking questions and the things that are not converted properly
