### ISSUE TITLE
NDHSPARE53: update software

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5466]
As a developer and system maintainer I would like build servers to be up to date so that builds succeed and so that we do not introduce security issues.

Dependencies to remove:
- `cmake` (now included in `ICP_Binaries` so no longer need a system install)

Dependencies to update:
- JDK7.x -> OpenJDK8.x
- MySQL 5.6.x -> 8.0.x
- Maven 3.3.x -> 3.6.x
- git
- TortoiseGit

Dependencies to add:
- (genie) Python 3

To review: log onto NDHSPARE53 and verify that the software listed above is up-to-date.

**Comment by FreddieAkeroyd** [comment]
Maven is already in ICP_Binaries, but I guess we need it separately for the GUI? Do we actually need MySQL on build servers? 

It wasn't clear if the ticket involved running the  "developer upgrade" step or manually installing the packages - can this be automated?

**Comment by Tom-Willemsen** [comment]
Installing MYSQL 8 was done by running developer upgrade script. The others are not automated yet (the dev update script just tells you to do them), so I did them manually. Yes, it is something we should look at automating more. I've added "automate more of the install tasks" to the ideas for tech debt standown.
