### ISSUE TITLE
genie_python: Lookup an RB number

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5469]
As an EMU instrument scientist I would like to be able to get information about an RB number out of the experiment details database. I could then use this information to check that a user's entered RB number is one that I expect to be run on this instrument at this time.

## Acceptance Criteria
1. There is a genie python function (should likely be in the advanced namespace) that will allow me to get information about a given RB number
2. genie_python still works in general if the database is not there
3. Exceptions caused by connecting to the database get handled in the same way as other commands

Note: Once done contact Koji with a link to documentation and assist him in getting this into the muon's begin command

**Comment by KathrynBaker** [comment]
One consideration, would it be worth putting the RB number PV into alarm if the contents are not in the appropriate list of numbers for that instrument. We may need to discuss the format etc. of 'dummy' RB Numbers such as those used for commissioning each cycle on some instruments

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/EPICS-inst_servers/blob/master/server_common/mysql_abstraction_layer.py has some database connection stuff but is not currently in genie_python. If it looks like it might be useful you could move this into genie_python (and update all other references to it)

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/309
