### ISSUE TITLE
Make it more obvious that hide title also hides users

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5470]
As an instrument scientist I occasionally want to hide titles/users on the dashboard if I have sensitive experiments. The current hide title functionality also hides users, this should be made more obvious.

## Acceptance Criteria
1. The hide title checkbox also specifies that it hides users
1. This functionality should also be possible from the experiment details view
1. This functionality should be possible from a script (as an advanced feature)

**Comment by Scott-James-Hurley** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7323
