### ISSUE TITLE
Scans: Set pixel range for multi detector

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5472]
As a reflectometry scientist using the scans scripting library, I would like to be able to set a pixel range for the multi detector. The recorded intensity should be a sum of the spectra for these pixels.

The pixel range should be defined via one of: 
- two arguments for 1) minimum pixel and 2) maximum pixel in the range (INTER, OFFSPEC convention)
- two arguments for 1) centre pixel and 2) offset so that the range min = (centre - offset) and range max = (centre + offset) (POLREF convention)

#### Acceptance Criteria
- Talk to the scientists about whether we can pick one convention
- Implement one (or both) solutions above as optional parameters on the `scan` command

**Comment by DominicOram** [comment]
Is summing done in scans library or DAE?

**Comment by John-Holt-Tessella** [comment]
See #5409

**Comment by ThomasLohnert** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/77
