### ISSUE TITLE
Reflectometry: Allow all parameters to be viewed on OPI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5477]
As a scientist looking at my reflectometry OPI on POLREF I can not see all the parameters I wish to set because there are too many. I would also like to distinguish in vertical sample mode between collimation slit gaps which are now in the horizontal plane.

Solutions for viewing parameters are (both all parameters and alignment parameters):

1. Make the page longer
1. Split into: (preferred)
   - activation paramerers (in beam)
   - collimation plane tracking parameters (offsets and angle offsets)
   - other parameters

Solutions for slits (they still want them called horizontal and vertical slits):

1. Add beamline constant to say which OPI to use (always needs to be set in config). This is currently done by hand but should be moved into the beamline helper, the constant is called OPI. 
1. Create a POLREF_vertical OPI set which has the horizontal slits in the top left

### Acceptance Criteria

1. All parameters can be viewed in the opi
1. Collimation slit gaps are seen easily

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/EPICS-inst_servers/tree/Ticket5477_create_collimator_group_maybe for ideas, once done delete this brnach unless it is used for the ticket

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/9
https://github.com/ISISComputingGroup/ibex_gui/pull/1169
