### ISSUE TITLE
All IOCs have at least 2 numbers

### ISSUE THREAD

**Issue by LilithCole** [ISISComputingGroup/IBEX#5481]
Add to IOC numbers so that all IOCs have at least 2:
 
 - [x] AG33220A
 - [ ] AG3631A
 - [x] AG53220A
 - [x] ALDN1000
 - [x] AMINT2L
 - [x] ASTRIUM
 - [ ] ATTOCUBE
 - [x] BGRSCRPT
 - [x] BKHOFF
 - [x] CAENMCA
 - [x] CAENV895
 - [x] CCD100
 - [x] CHTOBISR
 - [x] CONEXAGP
 - [ ] CONTROLSVCS
 - [x] COUETTE
 - [x] CP2800
 - [x] CRYOSMS
 - [x] CRYVALVE
 - [ ] CYBAMAN
 - [x] DELFTARDUSTEP
 - [x] DELFTBPMAG
 - [x] DELFTDCMAG
 - [x] DELFTSHEAR
 - [x] DETADC
 - [x] DFKPS
 - [x] DH2000
 - [x] DMA4500M
 - [x] ECLAB
 - [ ] EDNEXT
 - [x] EDTIC
 - [x] EGXCOLIM
 - [x] EUROTHRM
 - [x] FERMCHOP
 - [x] FINS
 - [x] FZJDDFCH
 - [x] GALIL
 - [x] GAMRY
 - [x] GEMORC
 - [x] HAMEG8123
 - [x] HELIOX
 - [ ] HIFIMAG
 - [x] HLG
 - [x] HVCAEN
 - [x] ICEFRDGE
 - [x] IEG
 - [x] ILM200
 - [ ] INDFURN
 - [ ] INHIBITR
 - [ ] INSTETC
 - [ ] INSTRON
 - [ ] IPS
 - [ ] ISISDAE
 - [x] ITC503
 - [ ] JSCO4180
 - [x] JULABO
 - [x] KEPCO
 - [x] KEYLKG
 - [ ] KHLY2001
 - [x] KHLY2400
 - [x] KHLY2700
 - [x] KNR1050
 - [x] KNRK6
 - [x] KYNCTM3K
 - [x] LINKAM95
 - [x] LINMOT
 - [x] LKSH218
 - [x] LKSH336
 - [x] LKSH340
 - [x] LKSH372
 - [x] LKSH460
 - [x] LSICORR
 - [x] MCLEN
 - [x] MERCURY_ITC
 - [x] MEZFLIPR
 - [x] MK2CHOPR
 - [ ] MK3CHOPR
 - [x] MKSPR4KB
 - [x] MOXA12XX
 - [ ] MUONJAWS
 - [ ] MUONTPAR
 - [ ] NANODAC
 - [x] NEOCERA
 - [ ] NGEM
 - [x] NGPSPSU
 - [ ] NIMATRO
 - [x] OERCONE
 - [x] PDR2000
 - [x] PIMOT
 - [ ] PSCTRL
 - [x] QEPRO
 - [ ] RKNDIO
 - [ ] RKNPS
 - [ ] ROTSC
 - [ ] RUNCTRL
 - [ ] SAMPOS
 - [x] SCHNDR
 - [ ] SCIMAG3D
 - [x] SDTEST
 - [ ] SECI2IBEX
 - [ ] SEPRTR
 - [x] SKFCHOPPER
 - [x] SKFMB350
 - [ ] SM300
 - [ ] SMC100
 - [x] SP2XX
 - [ ] SPINFLIPPER306015
 - [x] SPRLG
 - [ ] STPS350
 - [ ] STSR400
 - [x] TDK_LAMBDA_GENESYS
 - [x] TEKAFG3XXX
 - [ ] TEKDMM40X0
 - [x] TEKMSO4104B
 - [ ] TEST
 - [x] TPG26x
 - [x] TPG300
 - [x] TPG36x
 - [x] TRITON
 - [x] TTI355
 - [x] TTIEX355P
 - [x] TTIPLP
 - [ ] TWINCAT
 - [ ] WBVALVE
 - [x] WM323
 - [ ] ZFCNTRL
 - [ ] ZFMAGFLD

**Comment by ChrisColeExpControl** [comment]
IOCS remaining:  - [ ] AG3631A
 - [ ] ATTOCUBE
 - [ ] CONTROLSVCS
 - [ ] CYBAMAN
 - [ ] EDNEXT
 - [ ] HIFIMAG
 - [ ] INDFURN
 - [ ] INHIBITR
 - [ ] INSTETC
 - [ ] INSTRON
 - [ ] IPS
 - [ ] ISISDAE
 - [ ] JSCO4180
 - [ ] KHLY2001
 - [ ] MK3CHOPR
 - [ ] MUONJAWS
 - [ ] MUONTPAR
 - [ ] NANODAC
 - [ ] NGEM
 - [ ] NIMATRO
 - [ ] PSCTRL
 - [ ] RKNDIO
 - [ ] RKNPS
 - [ ] ROTSC
 - [ ] RUNCTRL
 - [ ] SAMPOS
 - [ ] SCIMAG3D
 - [ ] SECI2IBEX
 - [ ] SEPRTR
 - [ ] SM300
 - [ ] SMC100
 - [ ] SPINFLIPPER306015
 - [ ] STPS350
 - [ ] STSR400
 - [ ] TEKDMM40X0
 - [ ] TEST
 - [ ] TWINCAT
 - [ ] WBVALVE
 - [ ] ZFCNTRL
 - [ ] ZFMAGFLD

**Comment by ChrisColeExpControl** [comment]
In addition to adding the new IOCs, need to look through the ones already added in this ticket to makke sure they are booting properly (have a correct st-common, etc.)

**Comment by GRyall** [comment]
Work continues in #5482
