### ISSUE TITLE
[When build "pass"] Let windows 7 machines be updated

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5484]
We need to let Chris know that it is ok to update machine to windows 7 we would just like to confirm that we have not broken the build after Stand down first.

**Comment by ChrisM-S** [comment]
Please remember that the Windows 7 IBEX machines will be updated soon and will need a few reboots before they are done (i.e. if they restart they may go down again!).  You can check if they are done by looking in "Control Panel->Windows Update" to see if the highlighted 2020-04 update is there with a "Successful" status.

![image](https://user-images.githubusercontent.com/3035405/85053928-29ee1880-b193-11ea-987a-b2309e4fad90.png)
