### ISSUE TITLE
POLREF: Haake N6 waterbath

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5487]
As a POLREF scientist I sometime use a Haake N6 waterbath when Julabo are broken or used. I need support fore this

### Acceptance Criteria

- IOC
- OPI
- Emmulator
- Tests

**Comment by kjwoodsISIS** [comment]
Woah there!  Haake water baths have been withdrawn from service - see [POLREF Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/POLREF-Instrument-Details#note-water-baths).  the sample environment team no longer supports these devices.

**Comment by John-Holt-Tessella** [comment]
OK will let the scientists know

**Comment by kjwoodsISIS** [comment]
On checking my e-mails, I have an e-mail from the Soft Matter support team saying that the Haake water baths have been scrapped! (and Grant water baths too - just in case the scientists ask about those).

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella  - did you let the scientists know?  Can we close this ticket?

**Comment by John-Holt-Tessella** [comment]
Scientists have been told
