### ISSUE TITLE
Reflectometry: React correctly to bump strip trigger

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5488]
On POLREF if the bump strip is triggered all motors have their amplifier cards switched off. There is a signal which we believe is wired to the galil digital input which tells us if the bump strip is triggered; see labview (this may be the same as LARMOR although that may not work). Once the strip has been triggered and reset the user needs to move the beamline back into place because all the motors will have untensioned.

### Acceptance Criteria

- On bump strip triggering a prominant message is shown on the motors view. Must read  "Bump Strip Hit. Motion Control Disabled. Reset Motion Control in Block House. REMEMBER PRESS MOVE BEFORE PROCEEDING"
- On bump strip triggering relfectometry server shows prominant message. Message must say same as on SECI it is part of the safety case. Must read "Bump Strip Hit. Motion Control Disabled. Reset Motion Control in Block House. REMEMBER PRESS MOVE BEFORE PROCEEDING"
- ~Motors that are stopped should not accept new positions~ Separate ticket: https://github.com/ISISComputingGroup/IBEX/issues/5953

### Notes

- This should be written with the general case in mind of a general IO line indicating that the motors are stopped but should be written to solve POLREF's problem and we will adapt it.
- The easiest way to stop new permissions being sent maybe to use the security group on a pv
- This is critical for user program because users can destroy the alignment for motors without encoders.

**Comment by KathrynBaker** [comment]
It may be worth remembering that this could be more generic and need to be a message and actions based on a DIO (e.g. a broken light curtain)

**Comment by DominicOram** [comment]
Currently LARMOR's bumpstop is loaded into every galil (https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/GALIL/iocBoot/iocGALIL-IOC-01/st.cmd) this should be fixed as part of this ticket

**Comment by DominicOram** [comment]
@John-Holt-Tessella could this be displayed on the banner rather than in the motor view/reflectometry OPI? Will be slightly easier and less code duplication

**Comment by John-Holt-Tessella** [comment]
They definitely want it on the refl OPI because it needs to be right in front of the users so they don't accidentally try and move anything. Probably over the MOVE button would be good. It would be best if it was on the motor details OPI as well but I can negotiate that. We would need a screen shot.

**Comment by DominicOram** [comment]
Ok, I read `motor view` to be the perspective itself? Which combination do we want:
- [ ] On the table of motors itself
- [ ] On the basic motor view (e.g. what you see when you select one motor)
- [ ] On the motor details view (e.g. select a motor then go to more details)

**Comment by John-Holt-Tessella** [comment]
Not sure lets talk after standup

**Comment by ThomasLohnert** [comment]
PRs:
https://github.com/ISISComputingGroup/ibex_gui/pull/1221
https://github.com/ISISComputingGroup/EPICS-ioc/pull/563
https://github.com/ISISComputingGroup/EPICS-Common/pull/1

Documentation:
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Bump-Strip
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil-Instrument-Configuration
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil (just links)

**Comment by DominicOram** [comment]
Documentation looks great, thank you. We will need to make sure we add the relevant `cmd` to LARMOR and POLARIS, can you make a ticket for this and put a reminder in the release notes?

**Comment by ThomasLohnert** [comment]
New PR: 
https://github.com/ISISComputingGroup/EPICS/pull/240

Rather than creating a task, I have just created `bumpStop.cmd` on LARMOR/POLREF so it should just work once this is deployed. I have added an item in https://github.com/ISISComputingGroup/IBEX/issues/5857 to check the bump strip is set up correctly.

I will now also send an email to LARMOR to explain the changes in case they have any comments/questions..
