### ISSUE TITLE
genie_python: Setting alerting on Block ranges from a script

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5491]
As part of #4870 as an instrument scientist I want to be able to set from genie_python the alert range on a block for when I should be alerted in a similar manner to run control.

### Acceptance Criteria

The following genie python commands exist, with tests. They should probably go into a `g.alerts` namespace of they do the "alert" in function name can be removed so call would be `g.alert.set_range(b.my_block, 10, -10)`:

- set_alert_range(block_name, low, high, delay_secs=5) 
    - this sets the alerts range and delay before alert is triggered. On call alert is enabled [high and low should be in space order as cset]
- get_alerts_status()
   - returns a list of alerts and their values (the user can then print this if desired or interrogate it)
- set_alert_enabled(block_name, is_enabled)
    - sets whether the alert is enabled
- set_alert_sms_numbers(num1, num2, num3, ...)
    - sets the alert text numbers to numbers above; variable number of arguments. Calling with no numbers set clears the alerts. A message should be issued saying that these numbers are viewable by anyone at ISIS and will be kept indefinitely in log files. [limit to 5 numbers]
- set_alert_email_addresses(email1, email2, email2, ...)
    - sets the alert email addresses to numbers above; variable number of arguments. Calling with no email addresses clears the list. A message should be issued saying that these email addresses are viewable by anyone at ISIS and will be kept indefinitely in log files.
- feature is documented in the user guide
- there are sufficient system and unit tests

### Notes

See original ticket #4870 and https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/RUNCTRL/README.md for helpful details for implementation.

**Comment by DominicOram** [comment]
Readbacks on some of these functions may also be useful

**Comment by FreddieAkeroyd** [comment]
- As @DominicOram  mentions, readbacks would be useful, how do you e.g. append a number to the alerts list if you don't know what is already there. Or we add an optional "append" and "remove" arguments, which might make this easier
- should adding email addresses and numbers take a list rather than arguments? That would make adding a number easier if the readback returned a list
- the delay for in and out of range can be different, so should be an option to specify both separately
- would "sms" be an alternative for "text_number" in the function name
- similarly just "email" rather than "email_addresses"
- or "notify_sms", "notify_email" to make their use clear

**Comment by FreddieAkeroyd** [comment]
There should also be `g.alerts.status()` command to print the current configured alerts and their status to screen

**Comment by John-Holt-Tessella** [comment]
I deliberately didn't have a readbacks on sms and email sets so that we didn't have to deal with exposing user details. Setting just sets does not add so you must set all the numbers all at once. Not sure that this is the right decision but it is easiest to code (no duplicate checking or reading or concurrency problems)

**Comment by FreddieAkeroyd** [comment]
For September there may be little need for users to be added as they will be remote.  One option is to have  "temporary" and "permanent" sms/email lists which are merged internally, by default commands set the temporary list (user can set themselves) and the scientists are on the permanent list.

**Comment by FreddieAkeroyd** [comment]
To test:

see system tests for basic use of commands

If you open a console to RUNCTRL_01 you will see message like

Out of range AC PVs: UAH
TE:NDW2127:CS:AC:ALERTS:_WEBSEND: POSTing data to URL test
TE:NDW2127:CS:AC:ALERTS:_WEBSEND: TESTING: ignoring url

when alerts are supposed to be sent. You should set the alert URL to "test" with 

caput -S %MYPVPREFIX%CS:AC:ALERTS:URL:SP    test

running e.g.

check_rc_pvs.bat UAH AC

will list out the AC (alert) pvs, similary RC will give run control pvs
