### ISSUE TITLE
NIMROD: Inhibit temperature/pressure when using TiZr cells

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5494]
As an instrument scientist on NIMROD, I only want to be able to set the heater on a TiZr cell to more than 100°C when the vacuum is at a suitable value.

## Acceptance Criteria
1. There is a mechanism to define the two sets of ranges, e.g. PV-A > 100 only if PV-B < 10
1. If a request is made to PV-A that is invalid, it is not enacted and an alarm/warning displayed (e.g. PV-B = 11, PV-A requested to go to 110 would be invalid)
1. If PV-B changes so that PV-A is invalid, PV-A is changed to a 'safe' value (e.g. PV-A starts at 110, PV-B was at 9 but rises to 11, PV-A is no longer valid, set PV-A to a known value e.g. 100)

## Notes
1. THIS IS NOT A SAFETY GUARANTEE, it is merely automating something that the scientists currently only do mentally
1. This should be something we can abstract, and that has been attempted in the acceptance criteria, PV-A representing the temperature, and PV-B the pressure - note that the numbers used are not applicable to the problem in the user story (especially for PV-B)
1. It is assumed that only one of the values is controlled - the other is a readback, PV-A can be controlled, PV-B is just a read value in the acceptance criteria
1. This might be something that can be enabled using the inhibitor: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor
1. There are other tickets relating to the inhibitor in the backlog: #1866, #1867, #1868, #4247 which may be necessary before this, but probably are not
1. This is logic that should be usable at an IOC level, although the background script running system might be enough, the requirements imply that a state machine would be more practical
1. TiZr cells are used regularly on NIMROD, with a specific project designing one for use in a specific way during the next cycle
1. The cell currently on order could be delivered during August, with an aim to undertake offline testing before putting it on the beamline

**Comment by John-Holt-Tessella** [comment]
Spike for 0.5 day

**Comment by KathrynBaker** [comment]
This relates to the cell and information at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TiZr-Sample-Can

**Comment by Alistair-McGann-Tessella** [comment]
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/549
IOC Test Framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/382
EPICS base: https://github.com/ISISComputingGroup/EPICS/pull/231
New submodule: https://github.com/ISISComputingGroup/EPICS-TiZr

**Comment by JamesKingWork** [comment]
TiZr review comments:

- I find the TIZRWARNING PV misleading, I would expect to be warned (or given an alarm) if both PVs are out of range. We can simplify the functionality by describing the OUT_OF_RANGE PV as in major alarm if it has a value of 1 and not in alarm if it has a value of 0. This would remove the TIZRWARNING PV and the _SETWARNING and _RESETWARNING PVs and associated functionality simplifying the IOC.

**Comment by JamesKingWork** [comment]
> TiZr review comments:
> 
>     * I find the TIZRWARNING PV misleading, I would expect to be warned (or given an alarm) if both PVs are out of range. We can simplify the functionality by describing the OUT_OF_RANGE PV as in major alarm if it has a value of 1 and not in alarm if it has a value of 0. This would remove the TIZRWARNING PV and the _SETWARNING and _RESETWARNING PVs and associated functionality simplifying the IOC.
> 
>     * If the above comment is disagreed with the TIZRWARNING contains ONAM and ZNAM fields both of which have a max character length of 25, the current lengths of these field string values are longer than the max lengths

On reflection, if we do it the way I have suggested the alarm will only flicker on for a short time before a setpoint is then reapplied, which would be easy to miss for a scientist. I instead propose to keep the current behaviour, but also keep the TIZRWARNING pv in a state of alarm if the OUT_OF_RANGE PV is still out of range. This continues to provide an alarm for the cases where a setpoint isn't accepted so the PVs are still out of range or the TIZR ioc safe value or max values have been misconfigured.

**Comment by DominicOram** [comment]
As discussed can you ask the scientists the following:
* Is it ok that the setpoint gets sent briefly and then a safe value sent? (If this is unacceptable you can probably set the DRVH on PVONE? 
* How do they want to interact with this system, is a block/value on their synoptic enough?

Also, can we add some documentation to the wiki, given that this is generic I think we should make sure it's obvious it's out there. I would add a note about it on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TiZr-Sample-Can at least. Also add the caveat about the setpoint briefly being set incorrectly to the wiki.

**Comment by DominicOram** [comment]
I also think we could offer that this be patched onto NIMROD if they will find it useful this cycle, seems like an easy win for some brownie points with the scientists...

**Comment by JamesKingWork** [comment]
Email from me to Tom:
```
Hi Tom,

I’m from the IBEX team and I am currently working on the software to inhibit temperature/pressure when using TiZR Cells. I have a couple of requirements I would like to clarify which I’m hoping you can help me with.

Firstly the requirement: “If a request is made to set the temperature/pressure that is invalid, it is not enacted”. Our current solution would allow the setpoint to be set briefly (for about 1 second) and then writes the safe value to it, is this ok? Or shall we do the extra work to ensure the setpoint is not accepted at all?

Second how would you like to interact with the software? Our current solution is to set a block/blocks on the values you’re interested in and then to add them onto your synoptics. The TIZRWARNING pv is the one you’re probably most interested in which tells you whether the value is currently out of range or has been out of range in the last 5 seconds. If this is not enough an alternative would be to create an opi with the temperature/pressure values, the TIZRWARNING value, and a button to write the safe value manually. 

Once we have completed the ticket it would be relatively easy to patch it onto NIMROD for usage so you don’t have to wait for the next release, would you like us to do that for you?

Many thanks,
James 
```

**Comment by JamesKingWork** [comment]
Docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor#tizr-cell-inhibitor and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TiZr-Sample-Can#tizr-cell-inhibitor-ioc

**Comment by JamesKingWork** [comment]
The outcome of the chat with the scientist:

- It is ok that the setpoint gets set briefly and then a safe value is written over the top (The setpoint will be for a heater which will take a long time to enact any setpoint that is set)
- Controlling this through blocks is also perfectly fine
- We want to be able to switch whether we write the safe value on and off with the default being off (this can be done through csets to a block, we will create the pv)
- SANDALS is interested in using this and possibly GEM and POLARIS
- Tom will let us know when there is an experiment where we can test it out

**Comment by kjwoodsISIS** [comment]
OK.  What's the next step?
   * is this re-work done? or
   * do we have to wait until there is an experiment that allows us to test it (Hint: can that be the subject of another ticket?)

**Comment by JamesKingWork** [comment]
The rework is to add a PV that switches on/off whether the safe value is written or not then it will be done. As this is a soft IOC that is not talking to hardware, I think our software tests are sufficient, but more of a thing to be aware of as and when Nimrod test it out, and if need be we can create a ticket then.
