### ISSUE TITLE
Mercury ITC: test with hardware

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5497]
As a developer I would like to test that the newly-migrated mercury ITC driver (https://github.com/ISISComputingGroup/IBEX/issues/1392) works correctly against real hardware.

### Acceptance criteria

- [x] System-level commands tested (e.g. system catalog)
- [x] Communication with temperature cards tested
- [x] Communication with pressure cards tested
- [x] Communication with level cards tested

### Notes

- Clearly this ticket is impacted by the current site working restrictions
  * For the purposes of planning this ticket, assume that someone from cryogenics group will be able to get onto site to set up the hardware in a safe state so that we can test it (probably in the R80 magnet lab), but that we will be performing the tests from offsite. I have checked with cryogenics and they expect (under the current plans) to be able to support this kind of test within the next 4-6 weeks. These plans may change.
  * This ticket may be useful as a test for the general workflow of testing and supporting hardware remotely (e.g. what tools might be needed to help with diagnosing hardware issues from offsite)
- Cryogenics believe they will able to set up a mercury itc with one of each card type and "fake" sensors for temperature/pressure/level such that it will need minimal support from them, but we should still be able to read numbers and check the communication.
  * For clarity - they are proposing to run the mercury without connecting it to a real cryostat - which eliminates a lot of potential support and safety questions.
  * I believe this is acceptable from our perspective as there is no logic in the IOC, so "fake" readings are sufficient to prove that the ioc is working correctly.
- If we are unable to complete this ticket by the time of the release, we should revert the mercury driver back to the LvDCOM version.

**Comment by Tom-Willemsen** [comment]
Double check whether `PRST` or `TSET` is used to read the pressure setpoint from a pressure card as part of testing (the vi appears to use both, it's not immediately obvious which one "wins")

**Comment by Tom-Willemsen** [comment]
update from cryogenics: they expect to be able to support this testing "in the next couple of weeks".

**Comment by Tom-Willemsen** [comment]
Time scheduled to test this on 3rd August

**Comment by Tom-Willemsen** [comment]
Issues found:
- Protocol for `getRes` replies with `R` rather than `O` as the unit
- OPI: remove alarm-sensitive on setpoints
- Need units in DB for heater power (`%`)
- Macro config is too strict (does not allow `MB1.T1` as a macro)
- Change voltage in DB to not have a unit as it can be either `mV` or `V` and is confusing if it switches/displays the wrong one


Potential future improvements:
- Display sensor excitation voltage? Check with cryo group first.

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-MercuryiTC/pull/10/files
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/529/files
- https://github.com/ISISComputingGroup/ibex_gui/pull/1166

**Comment by JamesKingWork** [comment]
Remember to pull these back onto EMU and check the changes match
