### ISSUE TITLE
Remote users: Read-only VNC access

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5501]
As a user working remotely, I would like to be able to monitor the progress of my experiment at ISIS.

To do this, I would like a **read-only** view of the instrument control PC, which can be provided by VNC.

### Remote access requirements satisfied:

All of the following have the caveat that the item must be left open on the screen to be visible by the user - screen real estate will limit the total amount of information which can be shown clearly. The user is not able to change which information they are viewing.

**Some of these may be mutually exclusive, e.g. on an IBEX instrument you cannot look at the synoptic and the table of motors simultaneously.**

- "View hidden items on the web dashboard, but these items remain hidden from public display"
- "View the historic values of blocks (e.g. as a graph)"
- "View the current script being run and anything being printed from the script" (until the relevant output scrolls too far up)
- "View experiment details e.g. sample parameters, RB numbers"
- "View individual device control screens (IBEX OPIs/ SECI LabVIEW VIs)"
- "View the table of motors"
- "View the IBEX instrument synoptic display"
- "View information equivalent to that on the IBEX/SECI Journal Viewer"
- "Visualise live neutron data (single spectra)"
- "Visualise live neutron area (2D detector live view)"

### Notes:
- This solution applies equally to SECI and IBEX beamlines

**Comment by FreddieAkeroyd** [comment]
See #5423

**Comment by John-Holt-Tessella** [comment]
Are there any linux machines we need to do?

**Comment by KathrynBaker** [comment]
Already covered in previous tickets
