### ISSUE TITLE
Remote users: Read-write VNC access

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5502]
As a user working remotely, I would like to be able to monitor and control my experiment at ISIS.

To do this, I would like VNC access to the instrument control PC.

### Remote access requirements satisfied:

- All (but note that this is not necessarily an acceptable solution for all beamlines)

### Notes

- Not all instruments want to give their users this level of access. On some beamlines this level of access will be permitted for "trusted" users only.
- This solution applies equally well to SECI and IBEX instruments

**Comment by FreddieAkeroyd** [comment]
See #5423

**Comment by John-Holt-Tessella** [comment]
Is this done or do we need to install VNC on all machines?

**Comment by ChrisM-S** [comment]
Still needs to be installed - at least on machines where the scientists plan to use it - they will possibly be able to self install (many do already).

**Comment by KathrynBaker** [comment]
Already covered in previous tickets
