### ISSUE TITLE
Remote access: access to journal viewer

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5505]
As a user working remotely, I would like to be able to monitor the progress of my experiment at ISIS.

### Acceptance Criteria

1. To do this I would like to be able to access information equivalent to the current IBEX/SECI journal viewer.
1. Make a start (1 day) and if this look like it is going to be too long stop and review
1. Should not include users
1. Ask scientists can show other meta-data (maybe restrict certain instruments)
1. Restrict to current cycle
1. Code should be in IBEX project 
1. deployed to server (external facing server) accessable by IBEX group

### Notes

- This would be covered by https://github.com/ISISComputingGroup/IBEX/issues/5503 (IBEX client in STFC cloud) for IBEX instruments
- This would be covered by any instrument willing to use https://github.com/ISISComputingGroup/IBEX/issues/5502 (full read-write VNC access)
- There are likely to be at least some instruments covered by neither of the above solutions, so we may need a separate solution for them.
- This is the most heavily requested remote access feature and has been marked "essential" by a large number of groups/beamlines.
- consideration may need to be given about how much detail is given away to the web, and whether authentication is required. In particular how "hide title" is treated for historic runs.  
- There is already an internal site

**Comment by FreddieAkeroyd** [comment]
Note: the journal.xml information is currently available via the web, but access restricted to on-site. Similar details are also available in MySQL on each instrument.

**Comment by FreddieAkeroyd** [comment]
iCAT harvests this information, but is not in the default view - if you drill down into individual data files it is visible. iCAT may not index the files fast enough, and there is currently no weekend cover (but that may change in september). 

Mantid has an iCAT interface that lets you search for files. It uses the iCAT API.

I am not sure if a journal like summary could be added to iCAT/TOPCAT? Or something composed separately using the iCAT API?

**Comment by FreddieAkeroyd** [comment]
Note: Tristan's journal viewer program is already installed on the STFC cloud computers

**Comment by FreddieAkeroyd** [comment]
See #5423

**Comment by kjwoodsISIS** [comment]
A solution showing full journal data has been ruled out - it displays too much potentially sensitive information.  A solution showing limited journal viewer information has been implemented.  Reviewer should check  that acceptance criteria #6 and #7 have been completed; ignore other acceptance criteria.

**Comment by DominicOram** [comment]
It's not overly clear to me how this ticket has been done. I assume this is covered by the online journal viewer at https://data.isis.rl.ac.uk/journals/? What changes were made to limit the data on it? There is a bit of documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Journal-Viewer-Data but it doesn't tell me much about how I could maintain the system if it went down. Some questions that I have off the top of my head:
* How do I access sparrowhawk? I can't see the credentials on the normal passwords page
* Where is the data located on sparrowhawk?
* What is the mechanism being used to serve it?

**Comment by FreddieAkeroyd** [comment]
Documentation part of `\\isis\shares\isis_experiment_controls\web_dashboard_history.docx` as it shares an authentication mechanism, details should not be public so awaiting best location as i think sharepoint is in flux
