### ISSUE TITLE
Google test: use new EPICS mechanism

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5513]
New EPICS integration with Google Test has been published
```
The EPICS build system (using 'make runtests' and related targets) runs Google Tests as part of the regular build.
A TAP listener creates test results in the TAP format that EPICS uses. 
Easy configuration in any EPICS Makefile; EPICS unit tests and Google Tests can live in the same directory.
```
Available at https://github.com/epics-modules/gtest  We currently compile and use GTEST in a few places.

## Acceptance Criteria

- support/gtest replaced by above gtest
- Makefiles changed to build with new system
- test automatically run on build

**Comment by DominicOram** [comment]
Added to sprint as I'm using gmock in https://github.com/ISISComputingGroup/IBEX/issues/4573

**Comment by DominicOram** [comment]
To test:
* Start with https://github.com/ISISComputingGroup/EPICS/pull/220 to make sure you're on the right googletest repo
* Build the new googletest repo
* Check out all linked PRs and rebuild them
* In `C:\Instrument\Apps\epics\` run `make runtests`
* Confirm that this doesn't crash and as part of it any google tests are run (it takes 15/20 minutes to run)
* Confirm that http://epics-jenkins.isis.rl.ac.uk/job/new_runtests_build/14/testReport/(root)/ has not lost any tests compared to http://epics-jenkins.isis.rl.ac.uk/job/EPICS_IOC_Windows10_x64_CLEAN/114/testReport/(root)/

Once this ticket is done we will need to:
* Delete our googletest repo
* Delete the `new_runtests_build` from Jenkins

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Setting-up-googleTest-to-work-with-EPICS-build-process also updated

**Comment by DominicOram** [comment]
Repointing based on only review left
