### ISSUE TITLE
genie_python: build on linux

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5520]
## Acceptance criteria

* A genie_python_linux_pipeline build job

**Comment by DominicOram** [comment]
I think @mducle would be interested in this, what's the state of it?

**Comment by FreddieAkeroyd** [comment]
Adding as will stop linux tests failing in future if python changes.

Most work done previously as part of remote working for IDAaaS

Branch is currently building on Jenkins as `genie_python_linux_pipeline` and then deployed on redhat build server for use by builds

Once merged, you will need to change the `genie_python_linux_pipeline` to build from master rather than the branch
