### ISSUE TITLE
instrument switch: disable epicsdb

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5521]
The seci / ibex instrument switcher should disable / enable the "useepicsdb" option in the isisicp. Normally this is not an issue, as in seci mode there will be no values being written to the mysql database for the isisicp to pick up. However one possibility for september is to run SECI2IBEX and an archive engine on SANS2D, this would result in double counting of values (and possibly misordered timestamps) as both SECI and the archive engine would be queried.

## Acceptance criteria
* switching to SECI    changes    `isisicp.epicsdb.use`   to    false    in    `isisicp.properties` 
* switching to IBEX    changes    `isisicp.epicsdb.use`   to    true    in     `isisicp.properties`

Note: the location of `isisicp.properties` will move with VHDs #5518 so either need to allow for new location in this script or add note to the other ticket to change this script

**Comment by Tom-Willemsen** [comment]
seci is very close to gone now - ticket very likely to be superceded before being completed. Closing.
