### ISSUE TITLE
GUI: check opi_info.xml as part of build

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5522]
As a developer, I would like to be sure that `opi_info.xml` points at valid resources. To do this I would like the following checks to be performed:

### Acceptance criteria

- `opi_info.xml` does not contain windows-style paths (i.e. paths containing `\`)
- The files that `opi_info.xml` refers to should exist
- The file paths should be cased the same way on the filesystem and `opi_info.xml`, e.g. `jaws.opi` vs `JAWS.OPI` should fail.
- There is an automated test that checks the above conditions and is run as part of the build.

### Notes

Consider whether this is part of the existing check_opi_format script or whether it is a separate check.

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1175
