### ISSUE TITLE
SANS2D: High and Lowlimit for Apertures/Guides

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#5523]
As a Scientists on SANS2D, I would like high and low limit set for Apertures and Guides.

## Acceptance Criteria
 - The high limit is present and displayed in the OPI
 - The low limit is present and displayed in the OPI
- The high and low limit is abided by

**Note:**
Currently, the high and low limit for Apertures and Guides are set through OPI Macros. This is not the best way to set the high and low limit.
Galil IOC is used to control Apertures and Guides.

**Comment by kjwoodsISIS** [comment]
I agree that we need a way to define the high and low limits for each aperture and each guide (that is potentially 5 high/low limits for the apertures and 5 high/low limits for the guides).  If macros are not the way to do it, then fine; we should use our standard way to define motor limits.

However, I do not understand why the high/low limits need to be displayed on the OPI.  In fact, I don't think they need to be displayed at all.  The SECI VIS does not display the limits, nor does the sketch of the OPI suggest that the high/low limits need to be displayed.  What is the rationale for displaying them?

I think the scope of this ticket should be limited to defining the high and low limits for each aperture and each guide.

**Comment by RaiBishal** [comment]
Closed as motor high/low limit is used now and OPI macros are removed.
