### ISSUE TITLE
POLREF/SANS2D/OFFSPEC/INTER: Set IP addresses in the galil crates to enable ping for installation of switch

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5527]
We need to set the IP addresses in the galil crates on the following instruments so that when the network is installed they can be pinged to check setup. The instruction for doing this are in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX#network-configuration. Be careful this is a live instrument and we are remote, only change the address nothing else.

### Acceptance Criteria

# All crates on the following instruments have I addresses burned in:

- [x] POLREF
- [x] INTER
- [x] SANS2D
- [x] OFFSPEC

**Comment by DominicOram** [comment]
Consider writing a script if you think it will be quicker

**Comment by davidkeymer** [comment]
It's also possible to access the Galil console from the LabVIEW table of motors (once hidden tabs enabled).  So if SECI is already running, may be the quickest method.

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd worried about burning other things on

**Comment by Alistair-McGann-Tessella** [comment]
I set the IPs by hand, rather than write a script. To review, use the `IA?` command on each galil crate to verify the addresses have been written

**Comment by RaiBishal** [comment]
All crates except INTER is setup.

**Comment by kjwoodsISIS** [comment]
@RaiBishal, @Alistair-McGann-Tessella  - what is the issue with INTER?

**Comment by RaiBishal** [comment]
@kjwoodsISIS The IP address for Galil crate has not been set up in INTER, @Alistair-McGann-Tessella  could have missed this one out by accident as he has set it up for other instruments.
