### ISSUE TITLE
Reflectometry: Create Initial INTER Configuration

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5528]
As a developer I want to create an initial INTER Config in discussion with scientists so that we can see what needs doing to put the beamline into production.

### Acceptance Criteria

- An initial motor setup is produced
- An initial component
- An initial reflectometry config
- A list of issues that need to be completed to allow the reflectometry server to be used on INTER
- Tickets for issues are created.

**Comment by John-Holt-Tessella** [comment]
Items to fix:

- Allow slit number in `add_slit_parameters` to be a string (just type change and documentation for blade 1a)
- Allow an out of beam position to track the beam (we already pass in the intercept so this shouldn't be a problem)
- Finalise beamline configuration
- Fix checks in motor conversion script

**Comment by John-Holt-Tessella** [comment]
Configs in 
- Configs in private shares `Reflectometry\configs\INTER`

**Comment by kjwoodsISIS** [comment]
Re-pointed by @John-Holt-Tessella from 8 -> 2.
