### ISSUE TITLE
INTER: Finalise reflectometry config and motor setup

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5530]
Finish reflectometry server config on INTER.

### Acceptance Criteria

- Finish motor setup script
- Finish reflectometry config

### Notes

Follow on from #5528

**Comment by John-Holt-Tessella** [comment]
pull requests:

- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/68
- config branch NDXINTER
- https://github.com/ISISComputingGroup/ibex_gui/pull/1171

**Comment by ThomasLohnert** [comment]
- INTER_base component should contain `REFL_01` (not `REFL`)
- Config:
   - `add_slit_parameters("1A", exclude=["HG", "HC", "VC"], include_centres=True)` --> `add_slit_parameters("1A", exclude=["HG"])`
   - `THETA` param is not in liquid mode - this seems wrong to me but maybe I am missing something?

**Comment by John-Holt-Tessella** [comment]
All changes made + theta added to disabled mode

**Comment by ThomasLohnert** [comment]
We have been testing INTER using this config last week. Calling this done.
