### ISSUE TITLE
Datastreaming: Turn on streaming by default

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5536]
As a datastreaming developer I would like to load test the Kafka cluster by turning streaming on by default for every ICP.

## Acceptance Criteria
* The ICP streams data to kafka as default
* As part of this confirm that there is no memory leak or dying ICP if Kafka isn't there.

**Comment by FreddieAkeroyd** [comment]
Do we have topics created for all instruments?

**Comment by DominicOram** [comment]
I think so, if not we can make them easily enough

**Comment by ChrisM-S** [comment]
Does this include machines which don't take neutron data, e.g. setup machines, cryomags etc. (not saying it is necessarily a bad thing as they do log data).  I guess data streaming works regardless of BEGINs and ENDs?

**Comment by FreddieAkeroyd** [comment]
it only operates when you are running in event mode, so if you are not running in event mode then enabling it has no effect

**Comment by ChrisM-S** [comment]
I seem to remember that blocks were setup to be streamable, so does it mean that you could trivially switch to event mode (even without neutrons) and then stream the other data? for example could you stream an offline experiment on the ENGINX-X stress rig? given that you started with a BEGIN? - not trying to push a point of view here, just wondering what the limits are!

**Comment by DominicOram** [comment]
Block data is always being streamed, whether you're in event mode or not. As Freddie said, it's a slightly different mechanism. In theory, yes you could stream an offline experiment. The only difference between the setup on a real instrument and anything else is that the real instruments are streaming into the production cluster and everything else is streaming into a test cluster (for sample environment).

**Comment by DominicOram** [comment]
As part of this confirm that there is no memory leak or dying ICP if Kafka isn't there.

**Comment by rerpha** [comment]
> Do we have topics created for all instruments?

There were a few missing a couple of weeks ago when I was deploying the production forwarder, so I created any that were missing. I think all the DETMON topics were missing and a couple of other instruments had one or two topics that didn't already exist.
