### ISSUE TITLE
Inst servers: Fix coverage reports on windows 10 build server [Timebox: 1 day]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5542]
As a developer I would like to know how much coverage the unit tests on the inst_servers have. On some of the windows 10 build servers they are failing and crashing the build (http://epics-jenkins.isis.rl.ac.uk/job/EPICS_newbuildtest/2237/console).

## Acceptance Criteria
* The build servers do not crash when running coverage reports

**Comment by DominicOram** [comment]
If this can't be fixed in a day remove coverage.

**Comment by FreddieAkeroyd** [comment]
python coverage error in "newbuildtest" jenkins job was due to the the word "test" being in its name, I had been meaning to rename the jobs to something more sensible and once done they now pass. Didn't investigate why it was picking it up wrong from the name.

**Comment by DominicOram** [comment]
I think it's fine if we don't know the exact reason why, calling this done
