### ISSUE TITLE
DETMON: Board temperature available as PVs

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5544]
As someone supporting the detectors at ISIS I want to be able to ensure temperatures of my crates are within safe ranges. My remote working workflow is to monitor the temperature and contact MCR if there is a problem.

### Acceptance criteria:

The HVCAEN IOC has the temperature available for each board in a crate. Alarms should be placed on the temperature PV. Temperature changes of greater than 1 degrees should be logged.

### Notes
1. This fulfils a part of the criteria of #4187 but is more important for remote working so has been split off
1. The vendor code should be checked to see if this has been implemented before doing so ourselves
1. If this cannot be undertaken via the dll in the same way as the channel information, the OPC version of the IOC should be considered, but this should be generated as a new ticket and added to the umbrella ticket #4178 
1. See [Detmon](https://github.com/ISISComputingGroup/IBEX/wiki/DETMON-Instrument-Details) for background information/more details if required

**Comment by DominicOram** [comment]
This requires code changes and https://github.com/ISISComputingGroup/IBEX/issues/5069 is to do an actual release to DETMON so presumably makes sense to do this one first?

**Comment by JamesKingWork** [comment]
#5069 is not to do a release (this was done in another ticket and I will remove it from the acceptance criteria). So all is needed is config changes, I don't think either needs to hold up each other.

**Comment by DominicOram** [comment]
Had a quick look between tickets. It appears you can use `CAENHV_GetBdParamProp` and `CAENHV_GetBdParamInfo` to get the temperatures, see page 10/11 of https://github.com/ISISComputingGroup/EPICS-HVCAENx527/blob/master/HVCAENx527App/src/CAENHVWrapper/HV%20Wrapper_REV10.pdf

**Comment by DominicOram** [comment]
So https://github.com/slac-epics-modules/CAENHVAsyn seems to potentially already have this functionality, it's also an ASYN driver rather than a old style driver so should be a bit easier to maintain. I'm not sure I know enough about these devices to decide whether switching driver is a good idea at this point, will open to wider discussion.

**Comment by DominicOram** [comment]
Decision is to try the new driver on DETMON and see if it's stable

**Comment by DominicOram** [comment]
https://github.com/slac-epics-modules/CAENHVAsyn/pull/1

**Comment by DominicOram** [comment]
Davide is setting up a board in a failure state on Monday so we can test the board status more.

**Comment by JamesKingWork** [comment]
As part of the review, make a note if this may have fixed or changed the details of:

- https://github.com/ISISComputingGroup/IBEX/issues/4185
- https://github.com/ISISComputingGroup/IBEX/issues/4188
- https://github.com/ISISComputingGroup/IBEX/issues/4186

**Comment by JamesKingWork** [comment]
Updated docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN

**Comment by JamesKingWork** [comment]
Currently impeded waiting for the CAEN to be turned back on. Initial investigation showed discrepancies between the values given by the old and new iocs.

**Comment by JamesKingWork** [comment]
Crate is back on, but the new IOC now can't seem to talk to it. The old IOC can though.

**Comment by JamesKingWork** [comment]
The new driver now seems to talk happily to the CAEN crate. The new driver's code is much cleaner and more extensible than the older driver however I have some reservations to keep an eye on:

- there are some discrepancies in the values given between the drivers, though generally, the new driver gives more values which could be promising
- the new driver did fail to connect at one point to a crate which the old driver could connect to (I did not manage to find the reason)
- the amount of logs produced when the failed connection occurred was a lot higher than the old driver

The decision is to approve and merge the new driver and have a test run on DETMON
