### ISSUE TITLE
POLREF: Flipper

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5545]
As a POLREF scientist I need the flippers to work so I can do polarisation measurements. The code for the LET flipper has been recently updated and so has our driver. ~it is unclear whether this has been duplicated to POLREF or not~ There is not time or effort to update the POLREF flipper to be the same as the LET flipper so we need to interface with the current flipper code. This should be very similar to the original driver that was written. The plan is to create a new IOC based on this code called POLREF Flipper which can be placed in the system.

### Acceptance Criteria

- Find out the state of the code on POLREF for the flipper for cycle (Done)
    - It is older code which should work with the old IOC code they want to use this
- Create a new IOC based on the old flipper flipper code which works with the POLREF flippers

**Comment by John-Holt-Tessella** [comment]
email:
>We are currently looking at migrating POLREF to IBEX and as part of this we need to run the polarising flipper system which is similar/the same as the one on LET. Tom has worked on the code for this in IBEX. We are aware that the code was recently updated to work on LET and now I am wondering what we need to do to make POLREF work with its flippers both in IBEX and SECI. If the code on POLREF is the same as the LET that means it will work in IBEX but does that mean that the Vi’s need updating. If it is not the same are you updating it/can you let us know what the interface is for the flipper.

**Comment by John-Holt-Tessella** [comment]
organised meeting for this to talk about path forward

**Comment by KathrynBaker** [comment]
Consider a flag rather than two IOCs

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1184
- https://github.com/ISISComputingGroup/EPICS-Mezflipr/pull/6
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/86
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/366
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/535

Docs: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mezei-Spin-Flipper

**Comment by JamesKingWork** [comment]
I believe we should put the correct macros from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mezei-Spin-Flipper#v1 into globals.txt?

**Comment by JamesKingWork** [comment]
> I believe we should put the correct macros from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mezei-Spin-Flipper#v1 into globals.txt?

This is now done
