### ISSUE TITLE
HRPD [week beginning 24th August]: Test sample changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5553]
Following from https://github.com/ISISComputingGroup/IBEX/issues/5342 we should test the new changes on HRPD. The IS is away until 20th August so at that time we should talk to them about what they would like to do. In the mean time we will be testing the original issue on GEM/POLARIS

## Acceptance Criteria
One of the following is done.
* HRPD is reverted to the old sample changer version (HRPD have not seen the issues that the new version addresses so this may be fine)
* HRPD is running the new version but we are confident enough that no further testing is required
*  HRPD is running the new version and we have thoroughly tested it

**Comment by Tom-Willemsen** [comment]
New version has been put on HRPD. Scientist will plug it in tomorrow to check it works.

**Comment by Tom-Willemsen** [comment]
Scientist said they would get back to us if there were any issues with it in testing, and have not got back to us. Think we can consider this complete.
