### ISSUE TITLE
Rotating sample changer: Rename dropped sample error

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5554]
As a GEM instrument scientist I find the term "dropped sample" referring to a failure to pick up the sample after measurement on the rotating sample changer ambiguous:

> Yes, it's possible for the device to fail to raise a sample after it has been measured. It's confusing to use the term "dropped sample" for a failure to raise a sample. Especially so, since samples can drop off the device entirely, say if they are not attached well enough. How about "sample raise failure"?

## Acceptance Criteria
* The dropped sample error is renamed to something less ambiguous

**Comment by ConorMFinn** [comment]
For Review:
- [ ] [IOC Changes](https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/pull/9)
