### ISSUE TITLE
5452-1 Reflectometry: Complete move to refl repo

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5556]
@John-Holt-Tessella needs to merge the last part of the refl move (i.e. deleting code from the inst-servers module after merging in any code needed). Sub ticket of https://github.com/ISISComputingGroup/IBEX/issues/5452

### Acceptance Criteria

- Code merge in refl
- pull request merged (https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/306)

**Comment by John-Holt-Tessella** [comment]
Impeded waiting review/merging of outstanding refl tickets

**Comment by ThomasLohnert** [comment]
Has been done for a while, closing this ticket
