### ISSUE TITLE
IOC macros: remembered on cancel

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5558]
IOC macros are remembered even when you "cancel" the dialog

Found in system tests, decided in meeting with @ThomasLohnert @Alexandru-Dascalu @FreddieAkeroyd @DominicOram @JamesKingWork @John-Holt-Tessella that this needs to be pulled into the sprint and looked at urgently for the release

**Comment by DominicOram** [comment]
The same is also happening for synoptics

**Comment by John-Holt-Tessella** [comment]
Sub ticket #5441

**Comment by Tom-Willemsen** [comment]
> 
> 
> The same is also happening for synoptics

I can't reproduce this using the workflow noted on the spreadsheet, and nor can @JamesKingWork any more. Going to claim that this bit is not a real issue (unless the reviewer can show me how to reproduce on master!)

**Comment by DominicOram** [comment]
Cherry-picked on to release
