### ISSUE TITLE
IOC control dialog does not update

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5559]
During system testing it was found that on some machines when an IOC was started/stopped via the IOC control dialog it would restart the IOC but it didn't update to say the IOC was started. A fix for this is required for release

**Comment by DominicOram** [comment]
The underlying cause for this is https://github.com/ISISComputingGroup/IBEX/issues/5568. As a quick fix I removed all the `CHIPIR` IOCs as we will not be releasing to CHIPIR anyway (https://github.com/ISISComputingGroup/EPICS/pull/221). This should give us enough "wiggle room" for the cycle, however if more IOCs need to be added and we see `***Error: too many procServ state machines defined` again we could also remove:
* RKNDIO
* barndoors
* 2nd multi galil
* 2nd ice fridge

**Comment by DominicOram** [comment]
Subticket of https://github.com/ISISComputingGroup/IBEX/issues/5441

**Comment by Tom-Willemsen** [comment]
Cherry-picked onto release branch
