### ISSUE TITLE
Check limit violations

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5560]
During the system testing it was found that `g.check_limit_violations` did not work as expected. This may be a real issue or a poorly worded test @John-Holt-Tessella to look into

sub ticket of #5441

**Comment by John-Holt-Tessella** [comment]
The test works but is unclear.  Split off the limit violation test and then the text needs to be. Do the following:

1. pick a motor with a block pointing at it
1. Set the position to 0
1. Set the low limit to 1 (above the position)
1. Move the motor to 0.1
1. Make sure you see "Soft-Limit Violation" on the advanced motor opi
1. run `g.check_limit_violations("motor1")`

Result
    `Out[14]: ['motor1']`
