### ISSUE TITLE
IOC Log messages

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5561]
During the system tests it was found that on some machines the IOC log message search had a number of issues:
1. No messages are shown in the DAE view
1. Clearing the search didn't show the most recent messages
1. JMS was not able to connect to remote machines
1. Messages sent through the message simulator in ` C:\Instrument\Apps\EPICS\ISIS\IocLogServer\master\dev-tools` were not getting through to the GUI

**Comment by JamesKingWork** [comment]
1, 2 and 4 do not occur when having just restarted the ibex server and launched the GUI

**Comment by DominicOram** [comment]
How about if you switch machine and switch back?

**Comment by JamesKingWork** [comment]
When switched to DEMO, changing wiring table is picked up in the IOC and DAE perspective logs in the GUI

**Comment by JamesKingWork** [comment]
When switched back messages DAE log messages continue to appear in the DAE view, but the same messages do not seem to appear in the IOC log view and message simulator messages do not get through to the gui

**Comment by JamesKingWork** [comment]
Clearing the search also clears the table completely and doesn't show the most recent messages

**Comment by FreddieAkeroyd** [comment]
Works as indicated
