### ISSUE TITLE
Load_script autocomplete in standalone window

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5565]
As a user when I run a standalone genie_python window (e.g. `C:\Instrument\Apps\Python3\genie_python.bat`) then do `g.load_script(<TAB>` I would expect the scripts inside `C:\Scripts` to populate the autocomplete options but the do not.

Subticket of #5441 

## Acceptance Criteria
* In standalone python console autocomplete works for `g.load_script`

**Comment by Alexandru-Dascalu** [comment]
On 7.1, it fails in the standalone genie python but works in the GUI.

**Comment by RaiBishal** [comment]
@Tom-Willemsen Should this ticket be assigned some point? felt like this was a bit more than flash review

**Comment by Tom-Willemsen** [comment]
Hmm, I'm not sure. I think it would be about 5 points (in terms of time I spent on it + your review time). But as it's a sub-ticket we don't usually point these...

I think I'll ask for the consensus opinion on teams

**Comment by kjwoodsISIS** [comment]
What was this a sub-ticket of?  Were the 5 points included in the estimate of the parent ticket?  If not, they should be counted here.
