### ISSUE TITLE
Run control: Takes ~5s to go in and out of waiting

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5566]
During the system testing it was found that if I set run control on a block and change that block to be inside the runcontrol range it took the ICP ~5s to go into waiting. If I then moved it back out of the range it took the ICP another ~5s to be running again.

**Comment by FreddieAkeroyd** [comment]
So block does into "out of range" quickly, delay is in moving into waiting. Taking a look.

**Comment by FreddieAkeroyd** [comment]
I need to confirm on an old installation, but i guess it may be taking as long as before but just a bit more obvious to a user as the block goes out of range immediately but the action (waiting) happens after a bit of a delay. The default delay is 2 seconds, but a few things on scan loops need to process and it goes up to about 4 seconds. I had a look back at an old instrument autosave and the old delay was actually 0, so we could just drop it back to zero.

**Comment by FreddieAkeroyd** [comment]
Rather than 4 seconds it now takes 2 seconds, we could probably eliminate a second by using event scanning in gencontrolMgr

**Comment by FreddieAkeroyd** [comment]
Note: on an existing instrument, delay will have been autosaved so you will not see an immediate change - you will need to delete the runcontrol autosave files. On a new instrument it will be ok as the pv will not have existed before.

**Comment by FreddieAkeroyd** [comment]
Or do caput `%MYPVPRRFIX%CS:SB:block_name:RC:OUT:DELAY 0`

**Comment by John-Holt-Tessella** [comment]
Merged onto master and release 7.1.0
