### ISSUE TITLE
Procserv control: Avoid 256 IOC limit

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5568]
As a user I would like to be able to restart one of the >256 IOCs in use at ISIS. Currently procserv control has a hard limit of 256 IOCs that it can start (https://github.com/ISISComputingGroup/EPICS-procServControl/blob/bb96a26e01fad9831c77f6c66fcf88912803dec5/procServControlApp/src/procServControl.st#L61). If more than 256 are started there is an error of `***Error: too many procServ state machines defined` in the procserv control log. 

## Notes
* For release 7.1 this was avoided by reducing the number of deployed IOCs
* Is this a good opportunity to think about how we do multiple IOCs of the same type?

## Acceptance Criteria
* Increase the constant in the procserv so that the user can start/stop all of the IOCs that they require
* Confirm this doesn't break anything in procserv
* Make a test that tells us when we hit this limit (potentially start all IOCs and confirm they're running?)

**Comment by KathrynBaker** [comment]
This could also be an opportunity to consider whether we run procserv for all IOCs on all instruments or just those of interest? Something along the lines of #1953? It might also help with memory usage as in #3858.

**Comment by John-Holt-Tessella** [comment]
If proc serve control was python we could dynamically look at the last part of the PV and then only start/stop iocs that were requested. (Might be able to do this in db records too). Then I think the only task is to start the proc serve with the correct ioc in it and register the proc serve with conserver.

**Comment by FreddieAkeroyd** [comment]
https://github.com/ralphlange/procServ/pull/14 might be the basis of something eventually, or http://mdavidsaver.github.io/pyDevSup/   however I would hope just increasing  NSTATEMACHINES in the snl would be enough. We could probably create all the PVs (and maybe conserver configs) for all IOCs, and then only launch procserv on first write to a pv

**Comment by ChrisM-S** [comment]
When this is done, could we also check the MAX process count figure on the NDX and make sure it is not extended past this (or a similar problem may occur).

**Comment by JamesKingWork** [comment]
When finished please remove hotfix on line 413 and 414 of utils/build_ioc_startups.py

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-procServControl/pull/3 (increase max state machines)
- https://github.com/ISISComputingGroup/system_tests/pull/64 (test which should catch this or similar issues if they recur)
