### ISSUE TITLE
Blockserver: investigate cause of slowdown [Timebox 1.5 days]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5572]
In https://github.com/ISISComputingGroup/system_tests/pull/58/files we needed to increase the timeout for waiting for a config to change from 60s to 120s. As a developer, I would like to know what caused this performance regression and fix it.

### Acceptance criteria:
- Cause of performance decrease is understood and documented
- Performance fixed so that it takes less than 60s to change configs
- Test linked above changed back to a 60s timeout and test passes on build server
- If not found, create and propose a further ticket for continued testing.

**Comment by ThomasLohnert** [comment]
+1 from INTER - they often swap components in and out which causes a lot of waiting time to save/reload the config. 

The ideal solution would be the workflow they are used to from SECI, which allows them to add components on the fly without needing to save the config. We don't support at the moment and this may be a more fundamental change, but this ticket will help mitigate the immediate issue (and would be a win for all ISIS instruments)

**Comment by ThomasLohnert** [comment]
I think a large part of the time it takes to reload config is taken up by stopping / restarting all IOCs under procserv, which only gets worse the more IOCs we add to the system. 

Perhaps we could make this a bit smarter, e.g. 
- do not attempt to stop IOCs that are already stopped
- Only restart IOCs that are subject to changes
- (consider adding a "restart all IOCs" option on saving current config)

**Comment by KathrynBaker** [comment]
+1 for EMU for that kind of working method, looking at the RF equipment primarily for that behaviour

**Comment by FreddieAkeroyd** [comment]
need to check if globals.txt has changed too and potentially restart everything if it has

**Comment by Tom-Willemsen** [comment]
Check if change in #7135 has an impact on this

**Comment by KathrynBaker** [comment]
Estimated in [IBEX Pointing (scrumpy)](https://play-game.scrumpypoker.com/#/room/nkkgetpzayqn) to **2**, the average vote was **2.3** story points.

**Comment by KathrynBaker** [comment]
Estimated in [IBEX Pointing (scrumpy)](https://play-game.scrumpypoker.com/#/room/nkkgetpzayqn) to **3**, the average vote was **2.8** story points.

**Comment by Tom-Willemsen** [comment]
`WAIT_FOR_SERVER_TIMEOUT` changed back to 30s in https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/366 , which refactored the blockserver so that it no longer attempts to stop all IOCs. This gets around the performance problem we were having which was an increasing amount of time to change configs due to an expanding list of IOCS.
