### ISSUE TITLE
EMU: eurotherm_01 procserv crashed

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5580]
As a scientist on emu I want to be able to start/stop my eurotherm ioc

The procserv looking after it crashed sometime around 12:00 23/07/2020

### Acceptance criteria
- Investigate cause of crash (see if it is reproducible with lots of stops/starts of ibex server?) - suggest putting a timebox on this bit.
- Update `cygwin1.dll` as mentioned by Freddie in comments below
- In system tests, after running all tests, check that procservs for all iocs are still up (the procserv should be up even if the IOC is not started). This should help us catch the issue if it is reproducible.

**Comment by Tom-Willemsen** [comment]
```
[Thu Jul 23 12:07:55 2020] 2020/07/23 12:07:55.696 EUROTHRM_01 -1 autoConnect could not connect: Can't connect to localhost:20119: Unknown error

[Thu Jul 23 12:08:44 2020] Timeout waiting for RUNNING of IN:EMU:CS:PS:EUROTHRM_01

[Thu Jul 23 12:39:44 2020] Timeout waiting for RUNNING of IN:EMU:CS:PS:EUROTHRM_01

[Thu Jul 23 12:50:07 2020] Timeout waiting for RUNNING of IN:EMU:CS:PS:EUROTHRM_01

[Thu Jul 23 12:52:33 2020] Timeout waiting for RUNNING of IN:EMU:CS:PS:EUROTHRM_01
```

I am guessing this is related to https://github.com/ISISComputingGroup/IBEX/issues/5568

**Comment by FreddieAkeroyd** [comment]
procServ is cygwin, maybe we need an update of cygwin1.dll ?

**Comment by kjwoodsISIS** [comment]
The most recent version of the [Cygwin](https://www.cygwin.com/) DLL is 3.1.6. (dated 9 Jul 2020).

**Comment by DominicOram** [comment]
Make sure update of cygwin is on wiki

**Comment by Tom-Willemsen** [comment]
+1 SANS2D GALIL_05

**Comment by Tom-Willemsen** [comment]
+1 IRIS_SETUP ILM200_02
+1 MARI CRYOSMS_02

(found using script in https://github.com/ISISComputingGroup/IBEX/issues/5642 )

**Comment by FreddieAkeroyd** [comment]
Need to consider whether simple update of cygwin DLL is sufficient or recompile of utilities is required too. I've normally done the latter, but it is a bit more involved.

**Comment by FreddieAkeroyd** [comment]
I have mechanism to build which I will put into a Jenkins job

**Comment by FreddieAkeroyd** [comment]
Jenkins job http://epics-jenkins.isis.rl.ac.uk/job/EPICS_tools/ currently building from build_in_jenkins branch (above PR), job needs switching back to master after merge.

I have added new binaries from build to above PR, when merged they will be available to build server.

To test: difficult as looking for crash, but after merge check that ibex server starts procServ and conserver and console command works

**Comment by DominicOram** [comment]
Plan for this is for @FreddieAkeroyd to add a check in Nagios to check for crashed procservs then to deploy this to EMU and SANS2D to see if it fixes the issue.

**Comment by John-Holt-Tessella** [comment]
+1 #5757

**Comment by FreddieAkeroyd** [comment]
nagios check is awkward as number of procServ processes is variable - it starts an extra instance of each when IOC starts running.

**Comment by FreddieAkeroyd** [comment]
Should we apply new binaries when we do #5584 ?

**Comment by FreddieAkeroyd** [comment]
After merge of PR, the Jenkins EPICS-Tools job needs to have the branch it monitors switched from `*/build_in_jenkins` to `*/master`
