### ISSUE TITLE
SANS2D: Migrate enough of configs to test motors on SANS2D

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5581]
TBD

### Acceptance Criteria

- Install of ibex
- Configuration to show that swapping between SECI and IBEX does not change motor positions

**Comment by Tom-Willemsen** [comment]
Impeded awaiting opportunity to install on sans2d (scientists have been emailed)

**Comment by JamesKingWork** [comment]
Should this ticket also check that we have correctly covered the requirements that the apertures and guides should stay energised and the motors in the vacuum tank deenergise after a move and energise for a move?

**Comment by kjwoodsISIS** [comment]
No, checking that we've implemented the requirements will are correctly implemented as we continue to do more testing.  I will raise a ticket to cover the testing activity.  If we find that requirements have not been correctly implemented, we raise new tickets to resolve the problems.

**Comment by JamesKingWork** [comment]
I agree. Though this is a requirement I'm not sure it has been fully covered in other tickets as it has always been added in the notes section and I don't think we've thought carefully about it. I'm fairly sure the setup_motors.bat script will not have set the energising of the waveguides and apertures correctly, though I believe the vacuum tank is likely correct. I may be wrong but that is what I have seen with a short look. I think it should be covered somewhere prior to testing as we don't want a waveguide or aperture to drop under gravity and be damaged. I would do it as part of https://github.com/ISISComputingGroup/IBEX/issues/4573 but that ticket is big enough as it is.

**Comment by Tom-Willemsen** [comment]
First round of testing has been done using these migrated configs.
