### ISSUE TITLE
background plot: handle errors nicely

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5582]
The background plot sometimes saves a corrupt CSV save file and then goes into a restart loop because it can't reload it

### Acceptance criteria:

- The background plot task does not fall over if it's save files are corrupted
- There are tests available

**Comment by Tom-Willemsen** [comment]
have hacked it on EMU by catching general error and deleting and re-creating the save file - needs a better solution

**Comment by Tom-Willemsen** [comment]
Example of corrupt save file: 
[background_plot_data_01_corrupt.zip](https://github.com/ISISComputingGroup/IBEX/files/4966925/background_plot_data_01_corrupt.zip)

**Comment by KathrynBaker** [comment]
Considerations: stop it corrupting files (unlikely), load corrupt files to a point, warn if the files are too corrupt, write to a temporary file and then write over the main file

**Comment by mihai-stfc** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/86
