### ISSUE TITLE
background plot: only open from within gui

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5583]
As an instrument scientist I don't want the BGRSCRPT ioc on EMU to open plots in the gui.

It does `g.set_instrument()` and therefore runs the `init` function the the instrument scripts area, which opens the plot.

I have hacked it on EMU by only opening the plot if importing a pydev class succeeds, but this is not a proper solution.

### Acceptance criteria:
- There is a "clean" way of determining whether or not we are executing code in the IBEX GUI.
- `init_emu.py` is updated to use this new mechanism

**Comment by John-Holt-Tessella** [comment]
Is the correct solution to do `g.set_instrument(None, import_instrument_init=False)` ?

**Comment by Tom-Willemsen** [comment]
I think that would fix it for BGRSCRPT, but we also don't want it to open the plot from e.g. a standalone python console, so I think it needs some "is gui" logic

**Comment by KathrynBaker** [comment]
Suggestion: the GUI sends some flags to genie python to say that it is the caller which would not be set by other access methods

**Comment by rerpha** [comment]
Could we just use a global variable for this that gets set when loading the console and check if it exists in genie python when about to show a plot?

**Comment by Tom-Willemsen** [comment]
@rerpha yes that is a good approach. There are initialisation commands that only the gui runs in `uk.ac.stfc.isis.ibex.ui.scripting\Commands.java`. Then you just need a variable in genie_python which defaults to False but gets set to True by those init commands.

**Comment by John-Holt-Tessella** [comment]
Please do not make another hidden variable. User may want to use it too. Make it just 'from_ibex' it does not need to be private

**Comment by rerpha** [comment]
these two lines need to be added to the init_emu.py script on EMU:

```
def init(inst):
    set_begin_precmd(begin_precmd)
    set_end_precmd(end_precmd)
    try:
        if not g.from_ibex: # THIS LINE
            raise Exception # AND THIS LINE
        import _pydev_bundle.pydev_ipython_console_011
        g.adv.open_plot_window(is_primary=False)
    except:
	    print("Not running in GUI")
```

**Comment by rerpha** [comment]
PRs: 
- https://github.com/ISISComputingGroup/ibex_gui/pull/1191
- https://github.com/ISISComputingGroup/genie_python/pull/286

To test: 
- Run EMU config in script server with lines modified above
- check that plot opens
- either try and run `g.set_instrument()` from a separate terminal or manually overwrite `g.from_ibex` to `False` in the same console 
- Check plot does not open and `Not running in GUI` is displayed.

**Comment by rerpha** [comment]
EMU script will need to be modified to this: 

```python
import inst
import inst.basic_interface as r

from genie_python.genie_advanced import set_begin_precmd, set_end_precmd
from genie_python import genie as g

import sys
import os

sys.path.append(os.path.join("C:\\", "Instrument", "scripts"))
from technique.muon import zero_field_setup
from technique.muon.muon_begin_end import begin_precmd, end_precmd
# from technique.muon.background_plot import BackgroundBlockPlot

background_plot = None

def init(inst):
    set_begin_precmd(begin_precmd)
    set_end_precmd(end_precmd)
    if g.from_ibex:
        import _pydev_bundle.pydev_ipython_console_011
        g.adv.open_plot_window(is_primary=False)
#    global background_plot
#    background_plot=BackgroundBlockPlot((("Temp_RBV", "Cryostat"), ("Temp_Sample", "Sample"), ("Temp_SP", "Set point")), "Temperature", interval=2.0).start()

```
