### ISSUE TITLE
Install Script: Genie python not picked up correctly first time

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5586]
As someone deploying I would like to only need to run instrument_deploy.bat once. Currently, the first time you run instrument_deploy.bat genie python has not been defined correctly, but if you run it again in the same shell then it does pick up genie python.

#### Acceptance criteria:
- instrument_deploy.bat picks up the correct genie python first time

**Comment by Tom-Willemsen** [comment]
Not an issue for recent deploys.
