### ISSUE TITLE
SANS2D: Aperture & Waveguide motion - inhibit on server side

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5588]
As a SANS2D scientist, when the galil interlock is preventing moves I would like this to inhibit setting movements on the apertures and guides on the server-side as well as the client side. 

Acceptance criteria:

- Given %MYPVPREFIX%FINS_VAC:GALIL_INTERLOCK is set to disable motion when I set APERTURE_X and GUIDE_X with X as 1..5 to move using the PV then the move is prevented
- Genie python reports that it cannot move motors

Notes:

- The current solution is only implemented GUI side and through genie python could be circumvented

**Comment by JamesKingWork** [comment]
This could be a template to use https://github.com/ISISComputingGroup/EPICS-ioc/pull/515/files

**Comment by DominicOram** [comment]
Also do the pre-set positions at the same time e.g. https://github.com/ISISComputingGroup/IBEX/issues/4573
