### ISSUE TITLE
Muons: CAEN V895 Discriminator Reset Values on Config Change [timebox: 1 day]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5590]
As a muon scientist I would like the CAEN V895 to always reset some values when a config changes. @FreddieAkeroyd or @Tom-Willemsen can you add more detail for this please?

Original ticket and discussion on https://github.com/ISISComputingGroup/IBEX/issues/4915

There was a discussion between @FreddieAkeroyd @davidkeymer @Tom-Willemsen and the EMU scientists on 30/07/2020 in which the scientists stated that they need to be able to resend the values to the CAEN v895 on config change.

The CAEN is a write-only device and so we cannot know what values are currently being used. Therefore, the scientists want to resend values "regularly". 

We cannot just do this periodically, because sending values during a run may cause nonsense data to be collected briefly. The scientists also feel that sending the values on each begin is too frequent.

They generally want the same set of values always sent to the CAEN - the exception to this is when they do calibration measurements, and in this case the scientists manually tweak the values. They expect these tweaked values to be kept until the configuration is changed, and then overwritten by the defaults on changing config. Sending the values on IOC start is not frequent enough because IOCs do not necessarily restart on config change (they only restart if iocs or macros have changed between the configs).

**Comment by kjwoodsISIS** [comment]
Is this a problem for EMU or merely an inconvience?  Do they have the same problem in SECI?
How acceptable would it be to have a simple work-around?  

The work-around I have in mind is to write a script to reset the CAEN Discriminator values.  The EMU scientists could then run it manually each time they change config.  In fact, if they script the changing of configs, it can be "automated".

A work-around might be acceptable until such times as we can develop an alternative solution.

**Comment by Tom-Willemsen** [comment]
In meeting with @KathrynBaker @Tom-Willemsen @FreddieAkeroyd @DominicOram @JamesKingWork @Alexandru-Dascalu @Kevin-Woods-Tessella @davidkeymer we have decided to:
- Pull this ticket into the sprint as a high priority
- Investigate how hard it is to modify the blockserver to restart the CAEN specifically on every config change
  * This investigation has a 1 day timebox

We also agreed that the best long term solution is a checkbox in the configuration which controls whether each IOC is always restarted on each config change. The consensus is that this long-term solution is not achievable on a timescale where EMU would be able to test it before cycle.

**Comment by Tom-Willemsen** [comment]
Blockserver: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/310
Test: https://github.com/ISISComputingGroup/system_tests/pull/62
