### ISSUE TITLE
Fix sys.path in genie python

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5591]
In genie python 3 printing `sys.path` has output includes a line
```
'C:\\Instrument\\Apps\\Python\\Lib\\site-packages\\genie_python'
```
This should really be `Apps\\Python3` 

It doesn't appear to be causing an issue as g.__file__ indicates genie_python was imported from Python3 area 

## Acceptance Criteria

- `sys.path` contains `Python3` rather than `Python` directories

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1176
