### ISSUE TITLE
Deploy: DETMON

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5596]
As a supporter of the detectors at ISIS, I would like that latest changes to IBEX. Currently, it is marked as "impossible to do for now, DETMON can't access shares drive even with the credentials added". This ticket is to resolve that issue.

Acceptance criteria:

- DETMON is updated to the latest version of IBEX
- DETMON can be deployed to as part of the next deploy

**Comment by KathrynBaker** [comment]
The request to get access to the permissions would likely be an email to request them from the service desk, then a deploy of the latest version after that
