### ISSUE TITLE
GUI Scripting: Show warning about multiple consoles in scripting toolbar

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5597]
As a SANDALS instrument scientist (SG) I would like an indication in the GUI scripting toolbar that I have multiple consoles open. This came after a demo of https://github.com/ISISComputingGroup/IBEX/issues/5084, where it was suggested that the user will not necessarily read the warning message.

# Acceptance Criteria
1. There is an obvious indication in the GUI scripting toolbar of how many consoles are open

**Comment by Tom-Willemsen** [comment]
+1 IRIS

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1260
