### ISSUE TITLE
SANS2D: investigate homing code for Apertures and Guides

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5602]
As a scientist on SANS2D I want the homing behaviour of the apertures and guides to remain the same.

There are custom non-standard homing routines in SECI for these axes.

# Acceptance criteria:
1. The homing routines are investigated to find out what they do

Either:
- The homing routines are the same (or similar enough) to one of the existing IBEX homing routines - if so document this on wiki and use the appropriate IBEX homing routines

Or:
- The homing routines are not already catered for in IBEX; port the SECI homing routines into the IBEX homing template.

2. Create the testing ticket to actually test the homing routines with hardware

# Notes
1. The custom galil programs to do this are stored in `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Galil`
1. This ticket is best done by someone who is already familiar with galil code.

**Comment by KathrynBaker** [comment]
Will need some support at least from a galil code expert

**Comment by Tom-Willemsen** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-galil/pull/42
