### ISSUE TITLE
SANS2D: jaws: investigate contour move galil code

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5603]
SANS2D has a custom galil program for doing some kind of contour move on the jaws.

# Acceptance criteria
1. Check whether or not there is any extra hardware attached to that specific Galil
1. If there is extra hardware, make sure that we do not overwrite and eliminate the program used for that when downloading the IBEX Galil program and document findings on wiki

# Notes
1. The custom galil programs to do this are stored in `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Galil\Sans2d 3 Big Jaws.gal`

**Comment by KathrynBaker** [comment]
Part 2 could be done by anyone, help is likely to be needed for part 1 and part 3 from experts

**Comment by KathrynBaker** [comment]
@KathrynBaker to look at 1 before sprint planning when this ticket will be pointed

**Comment by KathrynBaker** [comment]
I will update the information at the top, the code is burnt in, so the requirements above are slightly different from that knowledge.

**Comment by Tom-Willemsen** [comment]
The scientists are all unaware of any "contour move" code for this galil, and are also not aware of any extra hardware plugged into this galil crate. They will double check for us tomorrow when they are in. @KathrynBaker do you have a feel for where the extra hardware would be plugged in if present, is it one of the galil digital inputs?

**Comment by KathrynBaker** [comment]
It would indeed be on the digital inputs, so the breakout card to the right of the black Galil box would be the only place it could be plugged in. I think this might be unused code, but if @davidkeymer has a moment to double check that I'm not missing something I'd be grateful

**Comment by Tom-Willemsen** [comment]
Scientist has confirmed that there is no extra/weird hardware physically plugged into the galil.

**Comment by KathrynBaker** [comment]
In which case, there is nothing further to be done - and we can either consider this a `wontfix` or `review complete` I should think
