### ISSUE TITLE
VARIOUS: MOXA NPort systems offline

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5606]
There are a number of MOXA NPorts offline which are needed in order to be able to use the respective instruments. As we are unable to access them remotely (there is no route to host) they will have to be physically looked at, and potentially replaced, which will require access to site and various locations.

## Acceptance Criteria 
1. The following MOXA NPort devices are all available as usual:
   - [x] MOXA_EMMA_BEAMLINE
   - [x] MOXA_ENGINX_BEAMLINE
   - [x] MOXA_HIFI_BLOCKHOUSE
   - [x] MOXA_NIMROD_SAMPLE

## Notes
1. Both ENGINX and NIMORD have been highlighted by ISs being unable to interact with devices on their beamlines
1. If looking at Nagios then there is also MOXA_NIMROD_MOTION offline - this is legitimate and is covered by #5131 
1. None of these MOXA NPorts are currently pingable
1. This ticket supersedes #5592
1. Moxautils was tried on MOXA_ENGINX_BEAMLINE, but as they seem to be off the network it is unlikely that any tools we have available will be effective
1. These will need to be fixed before the start of cycle

**Comment by ChrisM-S** [comment]
USG have offered to sort/repair these.

**Comment by RaiBishal** [comment]
Got following reply from James.

**_Hi Bishal,_**
**_The HIFI MOXA in the instrument area (I think it’s HIFI_BLOCKHOUSE) is currently disconnected while the rack it’s in was moved for maintenance access. We plan to reinstate it tomorrow – but it and others around muons may be powered off again for the Fixed Installation Testing next week._**
 
**_James_**

**Comment by ChrisM-S** [comment]
USG have sorted all except EMMA, they couldn't find this although there appears to be a MOXA in the cabin with working send/receive lights. There is only one MOXA on EMMA in my records so it needs someone to look in case it has fixed address or something else odd is going on!
