### ISSUE TITLE
Reflectometry: Set velocity on all axes before moving

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5607]
As a reflectometry user I want concurrently moving axes to move as synchronously as possible in order to avoid clashes. One thing we can do to improve this is set the synchronous velocity before moving any axis, instead of in between. 

#### Acceptance Criteria
On beamline move, instead of doing

1. 	Set velocity for motor axis 1
2. 	Move motor axis 1 to setpoint
3. 	....
4. 	Set velocity for motor axis n
5. 	Move motor axis n to setpoint

We should do

1. Set velocity for axes 1 - n
2. Move axes 1 - n to setpoint

So the moves are issued in quicker succession without waiting on channel access to set velocities on axes in between moves.

#### Note
May be required for better move synchronisation on OFFSPEC once they start using the front bench/mirrors due to tight clash conditions

**Comment by ThomasLohnert** [comment]
This should be a fairly nice ticket for a non-reflectometry person to pick up!

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/49 - not sure this is the most elegant solution but I think it works.
