### ISSUE TITLE
EMU: CAEN V895 sending values on startup doesn't work consistently

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5609]
As an instrument scientist on EMU, I would like the CAENV895 ioc to send the correct state on startup.

Currently it only sends the correct state for some channels (e.g. ch49 is ok, ch50 gets set to zero). I think this may be a race condition depending on the order of threshold and "enable" being sent. This results in no counts being recorded for some channels.

**This is a requirement for EMU to be able to run IBEX in cycle**

## Acceptance criteria:
- Restarting the CAEN V895 ioc on EMU puts the CAEN into the correct state.

**Comment by FreddieAkeroyd** [comment]
We should enable asyn traceIO in the driver via st.cmd and confirm all values are being sent as well as the order

**Comment by FreddieAkeroyd** [comment]
EMU hotfixed and looks to be OK
