### ISSUE TITLE
Console: Logging

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5612]
As a support person I want the console log to open a new file everyday so that I can delete previously created log files if they take up too much room so I can reclaim disk space.

### Acceptance Criteria

- Log file roles per day

### Notes

- At the moment it seems to create a log file on the day it is started and then write continuously to that until it is restarted.

**Comment by KathrynBaker** [comment]
It may be possible to do this via some of the cygwin and cyg hang up

**Comment by FreddieAkeroyd** [comment]
Send SIGHUP may caue it to reload, or there is a reload_conserver.bat file

**Comment by GRyall** [comment]
Solved as part of #8360?
