### ISSUE TITLE
INTER: Install IBEX [before 17th August 2020]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5614]
As a developer, I want to migrate INTER to use the IBEX instrument control system. This enables us to perform testing of the reflectometry server on the INTER beamline.

#### Acceptance Criteria
- [x] IBEX is installed on INTER 
- [ ] Motor settings are migrated from SECI
   - done as part of testing

#### Notes
- [x] #5613 will create a new release for INTER.  Complete #5613 before implementing this ticket.
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for INTER.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
    - asked for being done week starting 17th
- [X] Check that NDXINTER  has sufficient disk space to install IBEX
- [X] Check whether INTER uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)

**Comment by John-Holt-Tessella** [comment]
Instrument scientist has said:

> then I think it should be fine to go ahead today. SECI is currently open with the DAE in simulation mode
