### ISSUE TITLE
Script generator: Need to be able to set parameters for the whole script

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5616]
As a muon instrument scientist I would like to be able to set a parameter that will change the behaviour of all actions in the script. The concrete example for this is data-rates for an experiment. Data-rates are required for calculating time estimates but are unrelated to the parameters supplied to each action. The data-rates will be the same for one set of actions. 

#### Acceptance Criteria

1. I can specify some global parameters that will effect every action in the script 
    * this including time estimates

#### Notes
* Ticket #5964 is a near duplicate of this ticket, but there is useful material in #5964 (see below):
> As a user, I would like the Script Generator to provide an estimate of the duration of a measurement, based on a rate that I provide.
> 
> #### Acceptance Criteria
> 1. I can provide a rate for each measurement in my script.
> 1. The Script Generator calculates an estimated duration for each measurement
> 
> #### Notes
> 1. This feature is particularly requested by the muons group.  The old script generator had this facility.
> 1. The user wants a box at the top of the view that they put a constant in and this constant will then be used by every line of the script to do the time estimation

**Comment by Tom-Willemsen** [comment]
+1 again from EMU

**Comment by JamesKingWork** [comment]
+1 for EMU

**Comment by JamesKingWork** [comment]
+1 again for MuSR
