### ISSUE TITLE
genie_python: Get unit

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5620]
As an instrument scientist I want the units of a block to be accessible through the api, this is needed when creating graphs with units on (and probably other places too). At the moment there is some code that reaches into the genie_python private api to pull the value back. The should be replaced.

### Acceptance Criteria

- Either: Units for a block are acessible through the api
- Or: pv exists is accessible through the api so that the user can form the pv

### Notes

- code is https://github.com/ISISNeutronMuon/InstrumentScripts/blob/master/general/scans/motion.py#L229
```
def get_units(block_name):
    """
    Get the physical measurement units associated with a block name.

    Parameters
    ----------
    block_name: name of the block

    Returns
    -------
    units of the block
    """
    pv_name = g.adv.get_pv_from_block(block_name)
    if "." in pv_name:
        # Remove any headers
        pv_name = pv_name.split(".")[0]
    unit_name = pv_name + ".EGU"
    # pylint: disable=protected-access
    if g._genie_api.pv_exists(unit_name):
        return g.get_pv(unit_name)
    return ""
```

**Comment by KathrynBaker** [comment]
Think about the motor record fields as not all have a `.EGU` that is appropriate, but that may need to be documented as a known bug and another ticket created if that isn't straightforward.

**Comment by mihai-stfc** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/69
https://github.com/ISISComputingGroup/genie_python/pull/284
