### ISSUE TITLE
INTER: Testing time

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5623]
Test reflectometry on INTER

### Acceptance Critieria

- All motors move in desired directions
- Check limit on following axes with instrument scientists this had a soft and user limit in SECI
    - Horizontal
    - Lower Gonio
- Ask about slit 5 (it was never mentioned but there are axes set up for it

**Comment by ThomasLohnert** [comment]
Slit 5 does not physically exist anymore (motor axes are just left over)

**Comment by ThomasLohnert** [comment]
Write-up of testing activities here: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-INTER#initial-testing

Spreadsheet with mirror tracking comparisons can be found in `<Private Share>/Reflectometry/Inter_info/`
