### ISSUE TITLE
EMU: investigate CAEN v895 behaviour

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5624]
Following on from #5609 check the behaviour of setting thresholds. The boot time behaviour is correct in that it will restore a power cycled crate, but need to confirm behaviour is settings switched at runtime. As the device is write only, this can only be properly confirmed with the hardware.

- do you need to disable a channel before setting a threshold, or can you just re-send the currently enabled status

## acceptance criteria

* above questions answered

**Comment by KathrynBaker** [comment]
The ideal would be a test with a signal in person, can be done with quiet counts but it takes a little longer. Will need discussing availability with scientists and checking the way of working will encounter this.

**Comment by FreddieAkeroyd** [comment]
Testing looked to confirm that setting channels when enabled was OK, however it also highlighted a race condition that did not appear in the simulator until i added a delay between writes. Believe above PRs fix the issue .

**Comment by FreddieAkeroyd** [comment]
Added during sprint as issues discovered

**Comment by FreddieAkeroyd** [comment]
Only DB files need deploying

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - is this ticket waiting for something, or can it go ahead?

**Comment by FreddieAkeroyd** [comment]
Working on EMU as far as i know
