### ISSUE TITLE
SANS2D: Minor issues from demo

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5625]
As a SANS2D instrument scientist I would like the following minor issues corrected before running IBEX on the beamline:

* [x] Drilling down to motor details panel in the scraper aperture showed a disconnected motor, we need to understand why
* [x] In the vacuum tank OPI rotations need to be in degrees and Pillar X needs to be in mm
* [x] The big jaws have very asymmetric limits, particularly the west jaw seems to be able to travel very far, is this an issue?
* [x] The vacuum status on the scraper aperture OPI may not need to be there. Find out why we put it there and remove if there wasn't a good reason
* [x] All the apertures and guides should fit into the OPI without scrolling
* [x] The apertures and guides should grey out motion control if the system is at vac or pumping
* [x] The word Gauge is misspelled (twice) on the Vacuum OPI

## Acceptance Criteria
* The above are all done

**Comment by DominicOram** [comment]
> All the apertures and guides should fit into the OPI without scrolling

Scientists are happy to do this just with making the OPI larger so that it falls outside our normal size standards

**Comment by Tom-Willemsen** [comment]
> The big jaws have very asymmetric limits, particularly the west jaw seems to be able to travel very far, is this an issue?

I think these are best set when commisioning homing on the jaws (added a note to do this in https://github.com/ISISComputingGroup/IBEX/issues/5638)

> The vacuum status on the scraper aperture OPI may not need to be there. Find out why we put it there and remove if there wasn't a good reason

It was acceptance criteria 5 in https://github.com/ISISComputingGroup/IBEX/issues/4592 but I can't see an underlying reason in any documents why this was needed. Removed for now.

> The apertures and guides should grey out motion control if the system is at vac or pumping

This seems to already be done, the fields grey out on the status of `GALIL_INTERLOCK`, which is the boolean inverse of the vacuum being on (see note 4 of https://github.com/ISISComputingGroup/IBEX/issues/4570 )

PR is at https://github.com/ISISComputingGroup/ibex_gui/pull/1182
