### ISSUE TITLE
SANS2D: CAEN inhibit additions

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5626]
As an instrument scientist on SANS2D I have the following issues/additions to the motion inhibit based on CAENs being powered (https://github.com/ISISComputingGroup/IBEX/issues/4586).

* [x] I would like to confirm that the motion is only inhibited if the detectors are powered, not the monitors (email IS with confirmation)
* [x] If I cannot read from the CAENs motion should be inhibited
* [x] I would like to be able to manually override the motion inhibition
* [x] The CAEN status should be shown on the vacuum tank OPI

#### Notes:
1. The status of the motion inhibit & CAEN PSU is stated as a requirement on #4586 and is illustrated on the schematic diagrams of the [SANS2D vacuum tank OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf)

**Comment by DominicOram** [comment]
> I would like to be able to manually override the motion inhibition
Ask if they are happy to drill down to the ToM for this

**Comment by RaiBishal** [comment]
From SANS2D scientists:

-  **_the motion is only inhibited when the detectors are powered on and not the monitors as we always drive the motion when the monitors are on._**
- **_we’re happy to drill down as hopefully it won’t happen very often (as long it’s not too complicated of course)._**
