### ISSUE TITLE
GUI: restrict instrument list

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5627]
For the linux client on IDAaaS in particular it would be useful to have a reduced instrument list, which could be configured on a per-vm group basis to just show the instruments that are part of that group.

This is required for September cycle running.

## acceptance criteria

- instrument list can be specified in a file
- a separate file should be used to any other settings, this makes it easy to upgrade the rest of the client (this file can then be marked as %config(noreplace) in RPM spec) 
- Stop the user typing arbitrary instruments into the switch instrument dialog

**Comment by John-Holt-Tessella** [comment]
This seems like a nicety, they can easily find the instrument by typing the first letter.

**Comment by FreddieAkeroyd** [comment]
Sorry, I should have been clearer in the description. This is to avoid giving access to more instruments than necessary rather than a user enhancement.

**Comment by Tom-Willemsen** [comment]
We should be clear what the requirement is here. They would still be able to do things like:
- Pointing the log plotter at arbitrary instruments to get both live and historic values (you can just change the pv names it's looking at)
- Running `g.set_instrument()` and then reading any instrument using `g.cget()` etc
- Running `g.get_pv("IN:INSTRUMENT:...")`
- Pointing certain OPIs at another instrument (e.g. mk3 chopper) where we have provided an instrument prefix as an opi macro.

**Comment by FreddieAkeroyd** [comment]
We should protect instrument not on IDAaaS from access if possible (gateway or firewall rule), and I would also like to reduce the choice available on individual IDAaaS environments to only those appropriate for that environment. I agree the latter is not bullet proof, but is probably the best we can do given the available information. This is not strictly required as we are providing a snapshot of mostly metadata, but I though would be prudent to implement if possible

**Comment by DominicOram** [comment]
Don't put this in the preferences as we will conflicts when updating?

**Comment by DominicOram** [comment]
IDDas are happy to do the configuring for us

**Comment by FreddieAkeroyd** [comment]
I implemented something at https://github.com/ISISComputingGroup/ibex_gui/compare/linux_rpm as a temporary fix - no PR as it breaks things

**Comment by Alistair-McGann-Tessella** [comment]
PR:
https://github.com/ISISComputingGroup/ibex_gui/pull/1187

**Comment by FreddieAkeroyd** [comment]
We need to check this works on linux. When I run the normal client on IDAaaS it creates the instrument.pref file in the user's own area under a .eclipse directory. I seem to have lost access to the IDAaaS dev environment so I can't confirm if creating such a file in  /usr/local/ibex/client/configuration/.settings has the desired effect at the moment. As the /usr/local directory is not writable by the user i am assuming an instrument.prefs file will still be created in the users own home area, so we need to confirm whether:
(1) the /user/local preferences file is always loaded as well as the user version, or
(2) the /usr/local preferences are appended to the contents of the users version when it is initially created
If the situation is (2) then we may have a problem. The users home area is shared across IDAaaS environments, so this would impose one instrument list across multiple environments. The instrument list has to be specific to the system VM and not to any settings stored in the user's home directory.

**Comment by FreddieAkeroyd** [comment]
I copied the prefs file from my local area to a .settings directory in /usr/local and then deleted the one from my own area, it then did not remember the last instrument I had chosen, so looked like it did not read the central prefs file. This was a test with the existing GUI and not teh above branch, i assumed the logic in which preference file would be read would be the same? Is there any way to configure where such an instrument preference files is read from as it looks currently it will read it on a per user basis leading to the issues mentioned above. Is using a file outside of the eclipse preference system better?

**Comment by Alistair-McGann-Tessella** [comment]
Outcome from meeting 16/10/20
- [ ] Spend half a day figuring out eclipse preferences stores
- [ ] Add group name to instrument list (new key in dict?)
- [ ] If this works, modify this to load in a group name from the preferences and filter on the group name
- [ ] Need to make sure that disabling the instrument dialogue text field still works
- [ ] If it doesn't work, load the group from a different file on disc
- [ ] Need to be able to disable the journal perspective from the preferences store/file as well

**Comment by John-Holt-Tessella** [comment]
maybe @DominicOram  to do investigation on Linux

**Comment by Tom-Willemsen** [comment]
I did a bit more than half a day of investigating the preference stores but didn't get anywhere(*) - hence moving back to a simple file in the PR above.

I believe the journal viewer can already be disabled via a global preference, which could be changed at install time.

PRs:
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/323
- https://github.com/ISISComputingGroup/ibex_gui/pull/1187

Docs:
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Making-an-Instrument-Available-from-the-GUI#restricting-the-gui-to-switching-to-a-reduced-set-of-instruments
