### ISSUE TITLE
GUI: add option to remove journal view 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5628]
For IDAaaS in September it is required to remove the Journal viewer perspective. This is to avoid providing a general search interface to a wider audience than intended.
   
## Acceptance Criteria

- journal viewer perspective can be disabled by a setting in a GUI preference/config file. This can be via an existing preference file.

**Comment by Tom-Willemsen** [comment]
This is already possible and can be done by adding `uk.ac.stfc.isis.ibex.client.e4.product.perspective.journalviewer` to `uk.ac.stfc.isis.ibex.preferences/perspectives_not_shown` in [/base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini](https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini#L2)

**Comment by FreddieAkeroyd** [comment]
Thanks @Tom-Willemsen - I think this may correctly be a 0 point ticket!

**Comment by John-Holt-Tessella** [comment]
Can you add to this ticket the "so that" phrase there is no purpose to removing the journal perspective (why would we want to do that)?

**Comment by DominicOram** [comment]
Remove journal viewer on all linux builds

**Comment by FreddieAkeroyd** [comment]
Now removed on linux_rpm branch

**Comment by DominicOram** [comment]
Confirmed that journal viewer not available on IDAAS
