### ISSUE TITLE
Handover: LSi Correlator (SANS-DLS)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5633]
As a developer I would like to better understand how the LSi Correlator (for SANS-DLS experiements) is supported in IBEX, so that I am well-positioned to take on its future support and development.

#### Acceptance Criteria
1. The [LSi Correlator wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LSi-Correlator) is brought fully up to date.
1. Any known suggestions for improvement or enhancement are documented as tickets and listed below in a comment.
1. ~A set of briefing slides is created and stored in the [LSi Correlator](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FLSi%20Correlator&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) folder on the ICPDiscussions Sharepoint site.~ Should be on wiki
1. A nominated ISIS developer is briefed on the LSi Correlator (using the wiki)
1. Write the tests in #5336

#### Notes
1. If time allows, it would be a good idea for an ISIS developer to implement one or more of the tickets noted in item 2 above.  @Alistair-McGann-Tessella (if he is still here) could then review these tickets.
   - Alistair will leave the team at the end of October 2020.
1. Completion deadline: 16th October 2020.
1. The briefing constitutes the review of the ticket.
1. @JamesKingWork  is the nominated developer (agreed 28-09-2020)

**Comment by DominicOram** [comment]
As part of this organise a meeting with Alistair, handover person and Steve King to say hello.

**Comment by DominicOram** [comment]
@JamesKingWork has been volunteered (unlucky)

**Comment by Alistair-McGann-Tessella** [comment]
Tests to write:
 - [ ] Start is called when `take_data` called
 - [ ] Update no longer called when `MeasurementOn` returns False
 - [ ] `get_data_as_arrays` returns no nans in correlation function/time lags and trace time
 - [ ] `save_data` reproduces dummy data save file

**Comment by JamesKingWork** [comment]
Required PR:

https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/320

**Comment by JamesKingWork** [comment]
I am now confident in working on the LSiCorrelator IOC, the review for this is purely to have someone look over the code and to give someone else a chance to see the workings of the IOC

**Comment by JamesKingWork** [comment]
Moving to review complete as code will be review as part of: https://github.com/ISISComputingGroup/IBEX/issues/5336

**Comment by kjwoodsISIS** [comment]
Clarification from Alistair about location of briefing slides:
> From: Alistair
> Sent: 09 October 2020 17:14
> To: Kevin; James
> Subject: RE: Location of LSi Correlator training material
> 
> Hi Kevin,
> 
> You’re correct, “Should be on the wiki” should be interpreted as “the information required 
> to support and develop the correlator is on the wiki”. I updated the wiki pages with 
> extra information that was missing as part of this ticket.
> 
> I discussed with James the design and implementation of the correlator in quite a lot of 
> detail instead of preparing slides in advance.
> 
> James, if you’re comfortable with this I’ll clarify the acceptance criteria.
> 
> Thanks,
> Alistair
>> 
>> From: Kevin
>> Sent: 09 October 2020 13:03
>> To: James; Alistair
>> Subject: Location of LSi Correlator training material
>> 
>> Hi James, Hi Alistair,
>> 
>> Ticket #5633 Handover: LSi Correlator (SANS-DLS) had as one of its objectives:
>> 3.	A set of briefing slides is created and stored in the LSi Correlator folder 
>>      on the ICPDiscussions Sharepoint site. 
>> 
>> This was replaced by “Should be on wiki”.
>> 
>> I have had a look at the LSi Correlator wiki page.  I can see no briefing slides.  
>> Where are they?  Or should “Should be on wiki” be interpreted to mean “we don’t 
>> need briefing slides, the content of the wiki is all that is required”? (in 
>> which case, I think you should say so).
>> 
>> Thanks,
>> 
>> Kevin

**Comment by kjwoodsISIS** [comment]
> From: James
> Sent: 12 October 2020 10:16
> To: Kevin
> Subject: RE: Location of LSi Correlator training material
> 
> Yes he does now, Alistair sent an email out.
> 
> James 
> 
> > From: Alistair
> > Sent: 09 October 2020 17:41
> > To: Kevin
> > Subject: RE: Location of LSi Correlator training material
> >
> > That’s an excellent point, no he doesn’t. I’ll let him know.
> >
> > Thanks,
> > Alistair
> >
> > > From: Kevin
> > > Sent: 09 October 2020 17:27
> > > To: Alistair; James
> > > Subject: RE: Location of LSi Correlator training material
> > > 
> > > Oh!, before I forget.  One more thing …
> > > 
> > > Does Steve know that James is now the contact person for the LSi correlator?
> > > 
> > > Kevin
