### ISSUE TITLE
Handover: Muon Separator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5634]
As a developer I would like to better understand how the Muon Separator is supported in IBEX, so that I am well-positioned to take on its future support and development.

#### Acceptance Criteria
1. A set of briefing slides describing the operation of the Muon Separator is created and stored in the [Muon FE](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FMuon%20FE&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) folder on the ICPDiscussions Sharepoint site.
1. A nominated ISIS developer is briefed on the Muon Separator (using the above slides).

#### Notes
1. The Muon Separator code has worked well for a long time with little need for intervention.
1. Completion deadline: 30th September 2020.
1. The briefing constitutes the review of the ticket.
1. @DominicOram is the nominated developer (agreed 28-09-2020)

**Comment by DominicOram** [comment]
Meeting counts as review.

**Comment by Alistair-McGann-Tessella** [comment]
Slides uploaded to Muon FE discussions site

**Comment by DominicOram** [comment]
Meeting was good, thanks @Alistair-McGann-Tessella. Happy that with the slides and that meeting I can support this in the future. Slides are now also linked to from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Muon-Separator-Power-Supply
