### ISSUE TITLE
Handover: DAQMx

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5635]
As a developer I would like to better understand how the DAQMx is supported in IBEX, so that I am well-positioned to take on its future support and development.

#### Acceptance Criteria

1. A presentation describing the DAQMx is created is created and stored in the [DAQMx](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FDAQMx&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) folder on the ICPDiscussions Sharepoint site..
1. The DAQMx presentation is delivered in a code-chat session (open to all members of the IBEX team).

#### Notes
1. @Alistair-McGann-Tessella will arrange the code-chat session.
1. Completion deadline: 18th October 2020.
1. The briefing constitutes the review of the ticket.

**Comment by DominicOram** [comment]
Code chat is the review (also slides are put somewhere)

**Comment by kjwoodsISIS** [comment]
Code chat held 28-Sept-2020.
![image](https://user-images.githubusercontent.com/7249337/94463369-ba85bd00-01b4-11eb-9033-b2f2363bbc82.png)

**Comment by Alistair-McGann-Tessella** [comment]
Slides and recording uploaded to ICP Discussions site

**Comment by kjwoodsISIS** [comment]
Acceptance criteria are satisfied:
   - [x] Presentation delivered in Code Chat
   - [x] Presentation stored on ICP Discussion site.
   - [x] The Code Chat was the review.
Ticket is complete.
