### ISSUE TITLE
Handover: Moxa DIO Devices

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5636]
As a developer I would like to better understand how the Moxa DIO devices are supported in IBEX, so that I am well-positioned to take on its future support and development.

#### Acceptance Criteria
1. A presentation describing how the Moxa DIO IOC is implemented and how it should be configured.
1. The Moxa DIO presentation is delivered in a code-chat session (open to all members of the IBEX team).
   * Code chat slides to be stored in the [MoxaDIO](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FMoxaDIO&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) folder on the ICPDiscussions Sharepoint site.

#### Notes
1. The Moxa DIOs are currently used on ZOOM.
1. The Moxa DIOs may be used on INES at some point in the future.
1. Completion deadline: 18th October 2020.
1. The briefing constitutes the review of the ticket.

**Comment by DominicOram** [comment]
Code chat is the review (also slides are put somewhere)

**Comment by kjwoodsISIS** [comment]
Code chat held 28-Sept-2020.
![image](https://user-images.githubusercontent.com/7249337/94463285-9924d100-01b4-11eb-9457-277b33c3fdb5.png)

**Comment by Alistair-McGann-Tessella** [comment]
Slides and recording uploaded to ICPDiscussions

**Comment by kjwoodsISIS** [comment]
Acceptance criteria are satisfied:
   - [x] Presentation delivered in Code Chat
   - [x] Presentation stored on ICP Discussion site.
   - [x] The Code Chat was the review.
Ticket is complete.
