### ISSUE TITLE
SANS2D: Testing (20th August to 25th August) [Timebox: 5 days]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5637]
As a developer, I want to perform testing of IBEX on SANS2D during the period 20th August to 25th August

#### Acceptance Criteria
1. Perform preliminary testing of IBEX on SANS2D.
   1. Check Vacuum System OPI reads same as Vacuum System HMI
   1. Check movement of monitor (in/out)
   1. Check movement of fast shutter
   1. Test motion of "big" jaws in the vacuum tank
   1. If time, test motion of baffles & detectors in tank (test limited movement only - ensure there are no possible collision situations)

#### Notes
1. If there is time test more than just the acceptance criteria, e.g. scripting

**Comment by JamesKingWork** [comment]
Branches:
- https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket5637_sans2d_testing_fixes

**Comment by Tom-Willemsen** [comment]
We tested the vacuum PLC and readbacks from TPG300 - these all work as expected.

The following axes have been tested for movement (but homing has not been set up, so homing will need testing later):
- All big jaws
- Rear detector Z
- Front detector Z
- Front baffle Z
- Rear baffle Z
- Front det rot
- beam stop X
- beam stop 1 Y
- beam stop 2 Y
- beam stop 3 Y
- Rear strip
- Front strip
- Front beam stop

The following axes have been tested and motion does complete, but not "well":
- Rear detector X
  * Makes a "buzzing" noise while accelerating and decellerating which was not present when driving under SECI
- Front detector X
  * Positive moves complete much slower than negative moves, and make a buzzing noise throughout the move. SECI is able to complete the move normally without the slowness or buzzing.

**Comment by Tom-Willemsen** [comment]
Issues with front & rear detector X have been fixed by setting `BVEL` equal to `VELO`. All tank axes listed above now work properly.

We've now run out of testing time and have handed SANS2D back to the scientists for their pre-cycle preparations.

**Comment by JamesKingWork** [comment]
Just realised I didn't make the branch (https://github.com/ISISComputingGroup/IBEX/issues/5637#issuecomment-678120237) into a PR before, here is the PR:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/532
