### ISSUE TITLE
SANS2D: Testing (14th September to 18th September) [Timebox: 5 days]

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5638]
As a developer, I want to perform testing of IBEX on SANS2D during the period 14th September to 18th September.

#### Acceptance Criteria
1. Perform testing of IBEX on SANS2D.
1. `isisicp.epicsdb.use = true` is set is isisicp.propeties [see web](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting#no-log-files-are-produced-in-cdata-even-though-blocks-are-set-to-log)

Including from #5637 (NB this only tested motors on galil 3, 4 and 5)

1. Homing on axes:
    - All big jaws (also set sensible limits in ibex once homing is working properly)
    - Rear detector Z
    - Front detector Z
    - Front baffle Z
    - Rear baffle Z
    - Front det rot
    - beam stop X
    - beam stop 1 Y
    - beam stop 2 Y
    - beam stop 3 Y
    - Rear strip
    - Front strip
    - Front beam stop
1. Scripting

#### Notes
1. N/A

**Comment by KathrynBaker** [comment]
Don't forget to update the points appropriately to cover the missing 8 points

**Comment by Tom-Willemsen** [comment]
@davidkeymer and I did the following:
- Tested homing on all axes listed above
- Moved galils onto ethernet (with help from Freddie, Chris and FIT)
- Set sensible limits on jaws
- Tested fast deceleration galil code (triggered by bump strips)
- Tested collision avoidance
  * It fundamentally works but needs https://github.com/ISISComputingGroup/IBEX/issues/5735 doing and then retesting, as the deceleration on the stops is currently too slow to be useful.
