### ISSUE TITLE
SANS2D: How to deal with mismatching homes

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5639]
As a SANS2D scientist I would like to be able to use galils under IBEX and SECI. IBEX and SECI define motor homes differently. Under IBEX home is defined as 0 inside the controller and any user offset is defined in the software layer. Under SECI after a motor is homed the user offset is sent into the galil. The change of coordinate system is a problem if switching between IBEX/SECI often, which SANS2D may be doing. The following solutions are available:
* Rehome all axes when switching between IBEX/SECI (done on most migrations as we don't expect much switching between IBEX/SECI)
* Remove offsets in IBEX and only do homing in SECI (means we can't test homing in IBEX) 
* Remove offsets in IBEX and modify IBEX to apply home positions to the controller after homing like SECI does. (means that subtle differences between homing routines between SECI/IBEX may become important)
* Change SECI to do what IBEX does (may involve risk in changing SECI)

## Acceptance Criteria
* There is a meeting to discuss the above options and what we should do generally 
* An option is decided upon and implemented
* There is documentation on the wiki about how we generally deal with this issue

**Comment by KathrynBaker** [comment]
If using the home in SECI solution make sure that the home buttons in IBEX are inhibited

**Comment by FreddieAkeroyd** [comment]
Isn't the 1st option also sensitive to differences between the homing routines, like the 3rd one? (unless ibex applies a different offset to compensate for differences in homing). It should be possible to calibrate the difference - after homing in seci, home in ibex and print out position just before applying new home position - in an ideal world you will be applying the same position as where you are, but you will be able to see how close you are and potentially adjust.

**Comment by Alistair-McGann-Tessella** [comment]
The outcome of the meeting was that we are going to make SECI behave more like IBEX on SANS2D. The homevals on SECI will be set to zero, and add what was the homeval to the SECI offset, which is how IBEX homes.

The plan to do this is shown below. Because there are a few steps, and a reasonable number of axes (~10 for the axes in the tank), we should make scripts to do this conversion for us:

1. For each axis, in SECI:

    1. Home the axis in SECI. Make a note of its position.

    1. For each galil axis on SANS2D, add the homeval to the offset in its galil .ini file

    1. Set the axis homeval to zero

    1. Move the axis off the home limit

    1. Re-home the axis. Make sure the home position is consistent with the first home.

1. In IBEX:

    1. Enable the print position in the galil driver (see https://github.com/ISISComputingGroup/EPICS-galil/pull/41)

    1. Make a note of the reported position. This is the reference position which we need the IBEX home to reproduce.

    1.  Apply the new SECI offset as the offset in IBEX (this is the original homeval + whatever offset already existed in SECI).

    1. Home the axis in IBEX

    1. Compare the current position to the SECI home reference position.

    1. Make a note of how different the two homing methods are. If they do not agree, give these values to the instrument scientists. 

1. If the difference between IBEX and SECI homes is repeatable (is always the same), we should just add the difference between the two homing methods to the IBEX offset. This will allow us to reproduce the SECI home position in IBEX.

The axes in the tank should be done first

**Comment by Tom-Willemsen** [comment]
Note that in SECI, setting homeval to 0 doesn't actually define zero in the controller, as the offset & user offset need to be taken into account.

I believe the workflow for an axis with non-zero homeval and zero offset/user offset is:
- Leave homeval unchanged
- Set offset = homeval
- Decrement limits by homeval

In the case where axis is negated need to think about signs, I think all the signs get inverted.

Need to think carefully about what happens when offset isn't zero - it will define as (homeval - offset)/resolution in controller so we may need to also increment homeval by offset first in this case?

**Comment by Alistair-McGann-Tessella** [comment]
PR:
https://github.com/ISISComputingGroup/ibex_utils/pull/90

Documentation:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Changing-motor-homing-from-SECI-to-IBEX-convention

**Comment by DominicOram** [comment]
Some things I think that the wiki needs to make clearer, in both https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Changing-motor-homing-from-SECI-to-IBEX-convention:
* After home the value that is sent to the controller is `Home Position - (User Offset + Offset)`
* There is no difference between `Offset` and `User Offset` they are always added together when applied to/from the controller
* Are the limits refered to in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Changing-motor-homing-from-SECI-to-IBEX-convention `User limits` or `Soft limits`? I believe `Soft Limits` as they are in drive space, not user space
* Be clear that your script doesn't account for `User Limits`
* Changing your offset in SECI does not change your home position in user space, it just changes where this maps to drive space. This effectively means that unless the user has some `soft limits` then changing offsets does nothing user facing
* All limits in SECI are in the software, no limits are ever sent the controller, regardless of whether they are soft limits or user limits

**Comment by JamesKingWork** [comment]
This is in the ready column but labelled in progress, which is it?

**Comment by DominicOram** [comment]
Documentation generally looks better, thanks. Did you have a chance to look at the comments on the PR?

> Changing an offset will not affect the value displayed to the user (on the 'user axis'), but will change what position this corresponds to along the 'real' axis.

I think we're missing some subtlety here. Offsets are always added to the set point and readback, even on a home and so changing the offsets has no effect on how the commanded position relates to what is happening on the real device.

> The limits are set relative to the user axis, so changing the offset will also affect how far you can move forwards/backwards before hitting the limit.

Limits are actually set in drive space, not user space

As discussed we need to add the following three rules to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Changing-motor-homing-from-SECI-to-IBEX-convention, which are what we're trying to conserve during switching between IBEX/SECI:
* The home position must be zero, in SECI this translates to `home_val-offset = 0` as the offset is subtracted from the home_val when a home is done
* When we are on a home switch this always translates to the same position in user space (both before and after migration and on switching IBEX/SECI)
* The distance between the physical home position and the limits must stay the same (both before and after migration and on switching IBEX/SECI). In SECI the limits are defined in drive space and so as we're changing the offset, which moves drive space, we must then change the limits

To make this clearer your diagram should change to have the following:
* Be clear that the solid circle is user space and always on home, the dotted is drive space
* The solid circle shouldn't move
* The labelled distances for limits should be from the dotted circle as this is drive space

As I said, happy to discuss further, we may also want to get another STFC person on this as it's quite complicated?
