### ISSUE TITLE
Install script: ISISICP step fails

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5640]
If copying `isisicp_extMC.dll` fails during the ISISICP deploy step, the script thinks it has encountered an error and crashes. However according to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Upgrade-ISISICP this error should be ignored.

### Acceptance criteria
- A failure in copying extmc does not cause an error in the install script
- Any other copy failure still causes an error.

**Comment by FreddieAkeroyd** [comment]
Believe fixed in https://github.com/ISISNeutronMuon/ISISICP/commit/a4fa5b5cb42a2306a4fae7d3a4eed1493a7b9830

**Comment by DominicOram** [comment]
Added into sprint as it looks like it just needs review
