### ISSUE TITLE
Double check we have avoided 256 ioc limit on release 7.2.0

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5641]
In sprint planning several of us were worried that the fix for https://github.com/ISISComputingGroup/IBEX/issues/5568 may have been missed from release 7.2.0

Acceptance criteria:
- Check whether we missed this
- If so hotfix instruments

**Comment by Alistair-McGann-Tessella** [comment]
As part of https://github.com/ISISComputingGroup/IBEX/issues/5642 I noticed that sans2d running 7.2.0 has more procserv instances running than those on 7.1.0, suggesting that we have gone over the IOC limit

**Comment by JamesKingWork** [comment]
+1 for IMAT which is running 7.2.0 log contains:
```
[Wed Aug 26 15:19:24 2020] sevr=info procServControl[256]: all channels connected & rec***Error: too meived any p1srocSt erv statemonitor
```

**Comment by JamesKingWork** [comment]
+1 for INTER and +1 for POLREF

**Comment by JamesKingWork** [comment]
To review:
- Check machines running 7.2.0 are only INTER, POLREF, SANS2D and IMAT
- Check hotfix reapplied to any 7.2.0 machines
  - Can be found in EPICS/utils/build_ioc_startups.py which is called with `make iocstartups`
  - lines 413 and 414 removes any CHIPIR iocs from procserv control (the hotfix applied in 7.1.0)
- INTER, POLREF and SANS2D are moving between SECI and IBEX so `make iocstartups` has not been run yet but will be run when switching
- IMAT has had `make iocstartups` run so check whether procservs are running correctly i.e. PSCTRL logs from 28/08 don't have error in
- Once happy with changes tag Release_7.2.0 with the hotfix on

**Comment by Tom-Willemsen** [comment]
Changes cherry-picked onto master in https://github.com/ISISComputingGroup/EPICS/commit/20e7bfa058a642d6be0b388202e67a5d61af048d
