### ISSUE TITLE
MARI: Archive has error message for Fermi chopper status

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5644]
The archiver on MARI is giving the following warning every second. Find a way to stop this error:

```
[2020-02-28 23:59:50] 2020-02-28 23:59:50.511 INFO [Thread 28] org.csstudio.archive.writer.rdb.RDBArchiveWriter (batchTextSamples) - Value of IN:MARI:FERMCHOP_01:STATUS:RAW.VAL exceeds 80 chars: VStringArray[[#1000317, #2007F32, #300061C, ...], size 20, 2020/02/28 23:59:39.150]
```

This happened out of cycle the fermi chopper may not be switched on. The value was

```
20 #1000014 #2005923 #3000B28 #4000017 #5A4102E #6000019 #700001A #800001B #9001522 #A002B38 #B01FC4F #C01FE52 #D01F442 #E01E341 #F029135 #G015232 #H01122F
```

Acceptance criteria:

- This error message is no longer logged
- We no longer log raw values

**Comment by Tom-Willemsen** [comment]
As a quick fix we can take `archive(VAL)` off that RAW record - the decoded values should be archived elsewhere.

**Comment by DominicOram** [comment]
Moved into sprint as this is taking up a lot of disk space on MERLIN
