### ISSUE TITLE
POLREF: Current sheet Dual stage motor

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5647]
The polref motor uses `Dual position stage` in SECI we need it to work in IBEX. 

The behaviour is:

1. Setting the setpoint to 0 moves the current sheet to the lower limit and then sets the rbv/sp to 0
1. Setting the setpoint to 1 moves the current sheet to the upper limit and then sets the rbv/sp to 1 (it goes via 130, e.g. 0 -> 130 ->1)

This behaviour was retained under IBEX but it didn't know what to do with it.

### Acceptance Criteria

- Control a dual position stage
- Document solution

**Comment by John-Holt-Tessella** [comment]
@John-Holt-Tessella check this is current sheet not monitor

**Comment by John-Holt-Tessella** [comment]
Fix on beam line just made 0 in beam (with offset) and park be at limit position

**Comment by JamesKingWork** [comment]
Should this be on the IBEX project board as well?

**Comment by John-Holt-Tessella** [comment]
Documented solution at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX#dual-position-stage-axis
