### ISSUE TITLE
Reflectometry: SECI RBV->SP script

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5648]
As a POLREF instrument scientists I would like to be able to set all the setpoints for all my motors to the current readbacks. This is so that when I swap from IBEX to SECI the setpoints look like they have been transferred. I want to be able to run this script manually because it may not always be appropriate. I understand that the value won't be exact but will be close enough, e.g. if the slit gap in IBEX was set to 30 but the motors only got to 29.98 in Seci the gap setpoint will be 29.98.

### Acceptance Criteria

- There is a script which can be run which sets all set points for motors to the current readbacks.

### Notes

- POLREF have decide they do not need this. They are going to stick in IBEX and if they have to go back to SECI they will realign

**Comment by ThomasLohnert** [comment]
We are not planning on swapping back and forth between SECI and IBEX on any beamline anymore, and even so, this is just a nice to have. Closing ticket
