### ISSUE TITLE
POLREF: REFL error PCASpy utf-8 error

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5649]
Reflectomerty server is throwing:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 65: invalid start byte
```

See #5197 for similar issue. Maye be able to fix it if we can find the PV which is too long.

**Comment by FreddieAkeroyd** [comment]
You may be able to see it in "pv name query problems" on http://control-svcs.isis.cclrc.ac.uk/ if the variable is being requested when one of its scans is happening

**Comment by John-Holt-Tessella** [comment]
Longest requested pv was `IN:POLREF:REFL_01:$(PARAM_PV):DEFINE_POSITION_AS`

**Comment by FreddieAkeroyd** [comment]
The DB server log on EMU is slowing a lot of ```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 65: invalid start byte```

**Comment by John-Holt-Tessella** [comment]
Is this because we have a PV that is too long? What is the longest PV alolowed again (60?)

**Comment by ThomasLohnert** [comment]
Outdated issue, closing
