### ISSUE TITLE
Release: Create a downloadable release of the script generator

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5653]
As a user I would like to download and install the current script generator

### Acceptance Criteria

- ~A new release is created which contains the git download mechanism in~
    - release 7.2.0 of the script generator is used `Releases\script_generator_release\Script_Gen_7.2.0\script_generator\script_generator`
- SMS library is removed from the released python. It may need to be replaced with a mock.
- Release is smoke tested
- Downloads page is created with instructions of install on
- Release is available to download
    - the release should not need to include the install script just the directory above which I think needs copying to its final location (anywhere on the system).

### Notes

- This can be served from github page
- May need to be behind a password: no as long as sms library is removed

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/genie_python/pull/285

**Comment by JamesKingWork** [comment]
A release has been created at the linked location in the comment above. This has been done using the script from the ScriptGeneratorRelease PR. The genie_python PR contains the same changes as made to the bundled Python that was then zipped and uploaded to GitHub.
