### ISSUE TITLE
HTS Magnet - Step 1: New OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5660]
As a developer I would like to build up the new OPI and IOCs for the HTS magnet in discrete steps (the parent ticket is #5577).  Step 1 is to create a new OPI that will communicate with the existing Kepco IOC.  The new OPI will also contain some placeholder fields and controls, which will be activated in later steps.

#### Acceptance Criteria
1. The OPI must use the existing Kepco IOC.
1. The OPI must provides two tabs:
   1. a main tab (which will be progressively populated in steps 1 - 4).
   1. a details tab, which will remain blank until step 5
1. The main tab must contain:
   1. a Magnet Status group box (which will remain empty until step 4)
   1. a Power & Field Settings group box (which will be progressively populated in steps 1 - 3).
   1. a Calibration group box (which will remain empty until step 3)
1. The Power & Field Settings group box must contain:
   1. the Power LED, 
   1. Power On/Off switch, 
   1. An operating mode selector (e.g. drop-down menu, with two items "Current" and "Field"):
      * set the value to "Current" mode for the time being
   1. A Current & Voltage group box, containing:
      1. Readback field for the current (units: A) 
      1. Setpoint fields for the current (units: A) 
      1. Readback fields for the voltage (units: V) 
   1. A gauge to display the current readback value (units: A).
   1. A gauge to display the voltage readback value (units: V).
   1. A Ramp Control group box (which will remain empty until step 2)
   1. A Field group box (which will remain empty until step 3)

#### Notes
1. This ticket is a child of #5577.
1. Refer to the schematics to see how the OPI could be laid out:
   * [Main tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Normal_Tab.pdf)
1. The scientists have requested the current & voltage readbacks are displayed as dials (as well as numerical fields) because dials provide immediate visual feedback that the magnet is powered up.
1. The HTS Magnet will use two KEPCO BOP 6-125MG units 
   1. these will connected in parallel - one device is the master; the other is a slave.
   1. IBEX will communicate with the master device.
1. During commissioning, we can ask the scientists to propose maximum and minimum currents.
1. Facts about the HTS Magnet are documented in #5287.
   - HTS = High Temperature Superconductor (110K, I believe)
1. Further information is available in the `Manuals\HTS` folder in the shared directory.
1. The magnet will be shipped to ISIS in September; scientists wish to commission the magnet in October.

**Comment by kjwoodsISIS** [comment]
Question put to scientists:
> Sent: 27 August 2020 11:09
> Subject: Some more questions about the HTS Magnet
> 
> .....
> 
> Finally, is there a maximum allowed current for the HTS magnet?  (We are assuming that there is – we just don’t 
> know what the value is).
>

**Comment by JamesKingWork** [comment]
Requested change: Fulfill acceptance criteria 5 and 6 by adding the functionality to the IOC with comms from the manual (allowing for any currently used KEPCO IOCs to not have minimum or maximum currents set)

**Comment by rerpha** [comment]
I have moved the min/max current acceptance criteria to #5661 as it will be part of the IOC that does not talk to the hardware itself
