### ISSUE TITLE
HTS Magnet - Step 4: Create SmartMonitor IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5663]
As a developer I would like to build up the new OPI and IOCs for the HTS magnet in discrete steps (the parent ticket is #5577).  Step 4 is to create an IOC for the SmartMonitor and to connect it to the OPI.

#### Acceptance Criteria

1. The IOC must poll the SmartMonitor at regular intervals to check the status of the HTS magnet, temperatures, voltages, protection limits and safe operating limits of the HTS magnet.
      * the polling interval should be configurable (I would suggest this is to standard epics timings)
      * suggestion: set the polling interval to be 60s (it can be changed later)
1. The IOC must use the SmartMonitor's STAT command to obtain the magnet status value
      * check the manufacturer's documentation to see what the status values mean
1. The IOC must use the SmartMonitor's LIMS command to obtain the magnet protection limits
1. The IOC must use the SmartMonitor's OPLM command to obtain the magnet safe operating limits
1. The Magnet Status group box must contain:
   1. an indicator, labelled "Magnet is: " showing if the magnet is energised or not:
      1. if the magnet is not energised, the indicator should be coloured green and say "Off"
         * the magnet is not energised if the current is zero
      1. if the magnet is energised, the indicator should be coloured red and say "Energised"
         * the magnet is energised if the current is greater than zero
   1. a coloured indicator, labelled "Status: " showing the magnet status:
         * `At Room Temperature` on a green background
         * `Cooling down` on a yellow background
         * `At Operating Temperature` on a blue background
         * `Magnet Fault` on a red background
         * For the avoidance of doubt there is no status corresponding to `Magnet is warming up`
   1. a magnet status message, labelled "Message: " displaying (according to the magnet status) one of:
         * `Magnet is at Room Temperature`
         * `Magnet is cooling down`
         * `Magnet is at Operating Temperature`
         * `A fault has occurred`
         * For the avoidance of doubt there is no message corresponding to `Magnet is warming up`  

#### Notes
1. This ticket is a child of #5577.
1. Refer to the schematics to see how the OPI could be laid out:
   * [Main tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Normal_Tab.pdf)
1. The manufacturer's manuals are available in the `Manuals\HTS` folder in the shared directory.
   * be sure the consult both `Smart Monitor User Manual.pdf` and `Additional Technical Information from HTS.pdf`.
1. The SmartMonitor is (from our perspective) a very simple, read-only device.  It has only 3 commands.  It should not be difficult to write an emulator for it.

**Comment by rerpha** [comment]
PRs: 

- EPICS - https://github.com/ISISComputingGroup/EPICS/pull/232/
- Device Emulator - https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/91
- IOC test framework - https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/384
- IOC - https://github.com/ISISComputingGroup/EPICS-ioc/pull/548
- support - https://github.com/ISISComputingGroup/EPICS-SMRTMON/pull/1
