### ISSUE TITLE
SUPPORT: MARI Hung on end run

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5665]
MARI is hung on end of run.

### Acceptance Criteria

- Runs can be done

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd assessed that it is a hang somewhere and has put a debugger on and then restarted the program for them. Looks like it might be hardware related because there have been lots of hardware errors in the last coupe of days.

**Comment by FreddieAkeroyd** [comment]
Error of the form:``` 
2020-08-26 08:08:59  (0) ISISDAE: [Information] (ISISDAE::stopRun) Waiting up to 25 seconds for remaining 177244512 events in DAE
2020-08-26 08:09:24  (0) ISISDAE: [Information] (ISISDAE::stopRun) Stopping event reading threads with 177244512 events remaining
```
The fact the numbers are the same means at least one of the detector cards stopped updating, and the program hung when waiting for it to catch up. We had this a few times last year, usually then the program timed out and saved the file with less events, but this time it caused a hang which I will try and understand. It is certainly a hardware related issue, but the software didn't cope as well as it usually does. 

On restarting isisicp and re-ending the run, a data file was created. However most cards had

Last frame: 7508224 good frames: 7508225 raw frames: 7508225

But card 200 had

Last frame: 14498323 good frames: 14498324 raw frames: 14498324

So something was strange on card 200

**Comment by Tom-Willemsen** [comment]
From the comment above it looks like we are still trying to understand why the isisicp didn't cope with the hardware error - so is this ticket ready for review?

**Comment by John-Holt-Tessella** [comment]
Yes, acceptance criteria are filled and it is clear how to get them running again. Is that ok @FreddieAkeroyd if you find something else we will need a new ticket anyway,
