### ISSUE TITLE
POLARIS: Would like a beamline terminal for low staffed working

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5666]
As a scientist I would like to be able to see the status of the instrument screen when I am at the sample position, this is more important to me this cycle as there is less likely to be someone in the cabin to communicate with when setting things up.

**Acceptance Criteria:**
1. I can see everything that goes on on the Viewing PC screen in the cabin
2. I can control the screen as if I was in the cabin with a KVM setup.

**Notes**:
1. Can be a PC or Daxten.  There is no ambiguity with the Daxten, you see exactly what is there and we have the kit, it is instantly part replaceable to fix.  A PC can also be used with VNC but is perhaps a bit more maintenance and it is possible to lose the connection.
2. Both solutions need a survey of what's out on the beamline to check for network socket and the ideal location of the screen, keyboard & mouse.

**Comment by GRyall** [comment]
Given the return to site, anywhere this remains to be completed would appear to not be required. Reopen if you disagree though Chris.
