### ISSUE TITLE
ENGINX [When positional error sorted]: Verify that the Z axis of the positioner works

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5668]
Please see the Experiment Controls email for a little more information, and especially the comment added in teams.

The hardware side has been completed, it is up to us to decide on when we can test it, and to agree that time with someone who can see the movement to ensure that everything is correct - this is not quite a recommission the encoder is fine, the motor is what needs to be verified.

**Comment by John-Holt-Tessella** [comment]
Email sent requesting timescale 15:00 27/08/2020

**Comment by John-Holt-Tessella** [comment]
Still has problems need to set up the BLUAC box. What we did and are doing:

1. BLuAC box was replaced. This sits between the galil controller and the motor to convert a servo motor into a stepper (or the other way round)
1. The setup file has been lost and so they have re set it up
1. It moved with the jog box but we see the position going to a large negative number every couple of reads
1. The galil is using a program to allow the jog box to work
1. We set the motor steps from 2997 to 5000 as requested and tried moving the axis. It starts (we can hear it energise) and it might move a tiny amount and then stops. The final error code is 4 but before that there is a stop error code of 240 and a larger negative value:
```
2020-09-01T12:19:38.470	Z	-16375.036000
2020-09-01T12:19:38.470	Z_SP	367004.492600
2020-09-01T12:19:38.470	Z_Pos Error	383379.528600
2020-09-01T12:19:38.470	Z_SP_FINAL	422.000000
2020-09-01T12:19:38.470	Z_IN_MOTION	0
2020-09-01T12:19:38.470	Z_SWITCHES	0
2020-09-01T12:19:38.470	Z_STATUS	0
2020-09-01T12:19:38.470	Z_STOP_CODE	240
```
1. There was also a positional error on the BLuAC card at the end of some moves
1. They will sort out the positional error and then give us another call to try and get the motion working

**Comment by John-Holt-Tessella** [comment]
Impeded until they have sorted out positional error.

**Comment by John-Holt-Tessella** [comment]
Docs started at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/EnginX-Sample-Positioner

**Comment by John-Holt-Tessella** [comment]
Motor moves corrects up and down with both the jog box and the OPI in IBEX GUI. Distance of 10mm was verified. We could not check limits because of the equipment on the sample table.
