### ISSUE TITLE
Web dashboard: view historical values of blocks

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5669]
As a user or scientists I would like to view historical values of blocks on the web dashboard. This is part of #5504

## Acceptance Criteria

* Block values are linked to graphs

**Comment by FreddieAkeroyd** [comment]
Added as made possible by user office authentication system that was originally investigated for use by VNC

**Comment by FreddieAkeroyd** [comment]
To test: 
* Need to run JSON bourne locally as per wiki notes, then should be able to follo wlinks to graphs
* wiki notes for grafana setup in progress and will be posted here shortly

**Comment by John-Holt-Tessella** [comment]
Is there any documentation for this anywhere, can you add a link.

**Comment by JamesKingWork** [comment]
Code has been approved, but I will put this back in progress as documentation on grafana setup is still in progress

**Comment by FreddieAkeroyd** [comment]
Thank you @JamesKingWork

**Comment by kjwoodsISIS** [comment]
Is the documentation done yet?

**Comment by FreddieAkeroyd** [comment]
Documentation part of \\isis\shares\isis_experiment_controls\web_dashboard_history.docx as it shares an authentication mechanism, details should not be public so awaiting best location as i think sharepoint is in flux

**Comment by JamesKingWork** [comment]
Docs look good! I will link them on the dev wiki
