### ISSUE TITLE
TOSCA: Help in migrating to Python 3

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5675]
TOSCA scientists have requested help to migrate some scripts to Python 3.

Details are of the request are in their  original e-mail.  A [copy of the e-mail](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/TOSCA/TOSCA_Python_3_Query.pdf) is on the ICP Discussions site.

**Comment by Tom-Willemsen** [comment]
awaiting scientist response

**Comment by Tom-Willemsen** [comment]
Main issue was mixed tabs/spaces in `inst.py`. Showed scientist how to use special characters mode in notepad++ to spot tabs vs spaces and replace them.

Tested a small handful of user scripts and they all seemed to work ok, scientist is happy for now and will get back in touch if there are any further questions.
