### ISSUE TITLE
ENGINX: Understand how to commission a new galil

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5676]
As an instrument support person I want to be able to replace enginx galil controller. 

See ticket #5668 and https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/EnginX-Sample-Positioner. During this ticket we tried another controller but were unable to get the jog box to work. We think this was caused by some of the variables not being set in the controller. Understand where these are set if at all and make it possible to transfer the code to another controller.

### Acceptance Criteria 

- A set of instructions exist which  allow the enginX galil controller to be replaced

**Comment by KathrynBaker** [comment]
The code used for this Galil program is too large for our normal comms methods to deal with - it has to be undertaken from a locally connected computer using the manufacturer software. The default values for the variables should be in the code, and generally do not require altering. Typically we would have been at the beamline for this kind of work, so it more of an issue for remote access at this time.

**Comment by John-Holt-Tessella** [comment]
1. Where are the instructions for doing this?
1. Where is the original code to upload all I can find it `Jog Box.dmc` and `jogboxwithpos.gal` neither of which define `TwkD` for instance.

**Comment by KathrynBaker** [comment]
There's a readme alongside the programs which defines both the Mult and Twk values, and actually includes the information about timeouts and how to apply them. I can't guarantee that these values weren't changed and the readme kept up to date, but it is the best starting point I can give you.

**Comment by John-Holt-Tessella** [comment]
Sorry, you are quite right, how did I not see them there. Completely blind, I will add that to the wiki page and close this ticket. Thank you @KathrynBaker

**Comment by John-Holt-Tessella** [comment]
Done
