### ISSUE TITLE
Mol. Spec: Check Scripts are Python 3 compatible

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5677]
Ian wants to check that inst scripts used by the Molecular Spectroscopy group are Python 3 compatible.  He has tried using Futurize (following the instructions in the [IBEX User Manual](http://shadow.nd.rl.ac.uk/ibex_user_manual/Using-Futurize)), but is encountering problems.  He would like some help to complete the checks (e.g. get Futurize working , or some other way of checking the scripts).

**Comment by RaiBishal** [comment]
Updated wiki: https://github.com/ISISComputingGroup/ibex_user_manual/wiki
