### ISSUE TITLE
Exp Database: Update URL

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5681]
As a user I would like to be able to get details on what experiments have been scheduled on my instrument. We gather this data from Bus Apps, who have recently changed the URL for where to get the data. **The old URL will be retired on 1st October**. In https://github.com/ISISComputingGroup/IBEX/issues/5600 this URL was updated for the experiment database populator but Bus Apps still shows the following machines accessing the old webpage:

- [x] NDXWISH
- [x] NDXINTER
- [x] NDXNIMROD
- [x] NDXCHRONUS
- [x] NDXMUSR
- [x] NDXPOLREF
- [x] NDXCHIPIR
- [x] NDXHIFI
- [x] NDXSURF
- [x] NDXSOFTMAT
- [x] NDXEMU
- [x] NDXTEST
- [x] NDXSXD
- [x] NDXSANS2D
- [x] NDXCRISP
- [x] NDXARGUS
- [x] NDXPEARL
- [x] NDXIRIS_SETUP
- [x] NDXPEARL_SETUP
- [x] NDXLET
- [x] NDXOFFSPEC

This instruments need to instead use the new address. Which means:
* If they are SECI instruments the address needs to be updated for SECI and deployed to them
* If they are IBEX instruments we need to stop them independently gathering the information that should be pushed from a central location (potentially see https://github.com/ISISComputingGroup/IBEX/issues/5148)

## Acceptance Critera
* The above machines no longer access the old website

**Comment by DominicOram** [comment]
Code for how SECI does this is still in SVN. It is a C# service that pulls the data and puts it in an XML file, SECI then reads this file. This C# service is what will need updating. Alternatively a new service could be created that creates the XML files for SECI but this will likely be more work for little gain.

**Comment by KathrynBaker** [comment]
In the installed location there are a few .config files - it might be possible to just change the address in that file to the new one without needing to rebuild the system. This is a 32-bit program and is part of the set listed against this facility.

The service RBService is the one to stop.

**Comment by RaiBishal** [comment]
This will need to be done during maintenance day as it requires the installation of .NETFramework 4.5.2 or above for some of the remaining instruments(ARGUS and possibly CHRONUS). The newer version of RBService has been tested with the newer version of .NETFramework in NDXTEST and has run so far without any issues.

**Comment by RaiBishal** [comment]
Update remaining instruments to 4.5.2 and move to 4.8.x to during shutdown.

**Comment by kjwoodsISIS** [comment]
@RaiBishal - was this done yesterday?  is the ticket ready to be moved to Review?

**Comment by RaiBishal** [comment]
@kjwoodsISIS Yes, Just adding few comments on how to review it.

**Comment by RaiBishal** [comment]
How to review on IBEX Machine:
- Make sure RBService is not running as windows service in IBEX Machine

How to review on SECI Machine:
- Check RBService is running as windows service
- In an instrument check `C:\Program Files (x86)\STFC ISIS Facility\RB Number Finder\RBNumberFinderService.exe.config` contains latest URLs `https://api.facilities.rl.ac.uk/ws/UserOfficeWebService` and `https://api.facilities.rl.ac.uk/ws/ScheduleWebService`
-  Check `C:\Data\RBNUM\xxxExperiments.xml` and `C:\Data\RBNUM\xxxExperiments.xml` is generated. (generated every 3-4 hours)

The source for RBService has been updated and is now available in https://github.com/ISISNeutronMuon/RBNumberFinder.

Reviewing New source code:
- New source is mostly the same but the password has been changed
- Check if the password is correct in `DataRetriever.cs`

**Comment by DominicOram** [comment]
Great work, thanks @RaiBishal. I've emailed Panda just to confirm that they're not seeing any new requests recently. I'm happy to assume they're not though and will call this done.
