### ISSUE TITLE
SUPPORT: Fix slack channels #inst_status and #isis_status 

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5683]
Scientist reported slack channels not works, should fix them and let them know (email in shared inbox)

**Comment by JamesKingWork** [comment]
Looks as if slack is not sending requests to control-svcs, Freddie thinks this may be a certificate issue so has requested a new one. If this doesn't solve the issue we will come back to it

**Comment by FreddieAkeroyd** [comment]
This may be because the ssl certificate for control-svcs has expired and slack is no longer trusting posting to it, I will request a new certificate

**Comment by JamesKingWork** [comment]
For review:

- Check you can plot graphs on #isis_status and get run and block information on #isis_status on the slack workspace isisinfo.slack.com

**Comment by Tom-Willemsen** [comment]
From the documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/control-svcs I can't see how someone else would reproduce this fix if it happens again in future.

Can we at least put on that page:
- That control-svcs is required for messages in that slack workspace
- A brief description of how it works/where the code is stored (both in version control and on the server itself)
- What the process is to obtain a new certificate, e.g. who do we need to contact
  * If this bit can't be on a public wiki put it in a private location e.g. sharepoint and link from wiki
- Where & how to install the new certificate once it has been obtained.
