### ISSUE TITLE
SUPPORT: Fix beam status on CRISP and SURF

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5684]
The beam status graph in SECI is reported to not be working on CRISP and SURF, see footprints ticket. When done inform instrument scientist.

**Comment by FreddieAkeroyd** [comment]
Now fixed - script creating file was not python 3 compliant

**Comment by JamesKingWork** [comment]
To review:

- See webpages are updating correctly (http://beamlog.nd.rl.ac.uk/jsbeam.txt, http://dataweb.isis.rl.ac.uk/IsisPPP/BeamCurrents.aspx)
- Check SECI on SURF and CRISP are now displaying correct values
- Check additional troubleshooting at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SECI-Troubleshooting#beam-status-not-updating
