### ISSUE TITLE
Larmor: Newport XPS Controller

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5688]
As an instrument scientist on LARMOR I would like to be able to control my new newport motion controller. The controller is an XPS and it appears that there is already support for it in the motor record. We have the controller in the office to test. This is required for the November cycle. The instrument scientists only requires communication via the ToM/blocks, no specific OPIs or complex additional motion is required.

## Acceptance Criteria
* Create IOC and prove that we can communicate with the newport controller in the office
* Documentation for newport
* Need to be able to run motionsetpoints on it
* ~There is an emulator and tests for the newport XPS (these can be basic tests as we're getting the device support from elsewhere)~ Spin this into new ticket

**Comment by DominicOram** [comment]
IS thinks they will be using this at the start of November cycle

**Comment by DominicOram** [comment]
Controller is set up in the office, ask me if you would like the IP Address. It's not got any drives in it but hopefully we can at least test connecting and interrogating it.

I used https://www.newport.com/mam/celum/celum_assets/resources/XPS-D_-_Start-Up_Manual.pdf?1 to help set it up.

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/EPICS-ioc/pull/557, Once merged let the LARMOR IS know we're ready

**Comment by JamesKingWork** [comment]
Spun out ticket for tests: https://github.com/ISISComputingGroup/IBEX/issues/5945

**Comment by DominicOram** [comment]
Some communications with scientist discussing requirements at \\isis\shares\ISIS_Experiment_Controls\Communications With Scientists

**Comment by DominicOram** [comment]
Changed passwords and updated passwords page
