### ISSUE TITLE
SUPPORT: LOQ script not running correctly

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5689]
do_sans/do_trans script won't run.

**Comment by John-Holt-Tessella** [comment]
Issues:

1. Script won't load because of linter error
1. Add to script top 

    ```
    # Script created by SANSScript at 08/09/2020 14:41:27
    import sys
    from genie_python import genie as g, BLOCK_NAMES as b
    sys.path.append(r"C:\instrument\scripts")
    from instrument.loq import *  # pylint: disable=wildcard-import, unused-wildcard-import
    ```

1. But linter is looking in `c:\scripts` not `c:\instrument\script`  so make it look more like other instruments by putting it in `c:\instrument\scripts` had to do some edits and need to check for further changes
1. Then have problem setting the wiring, detector and spectra files seems this can not be done with no time regiemes anymore.
    - Ticket needed to fix this
    - Ticket to set clear regiemes to a given set without having to clear them
1. This now seems to work
1. Informed original script generator keeper for script generator to add extra lines (some discussion to happen)

### Actions left

- [ ] Create tickers
- [ ] Make sure code in `c:\scripts` matches or is superceeded by code in `c:\instrument\scripts`
- [ ] Make sure new code added is pushed to repo
- [ ] Email scientists about how shared area works and they need to pull from it to get latest changes

**Comment by John-Holt-Tessella** [comment]
Tickets:

- https://github.com/ISISComputingGroup/IBEX/issues/5702
- https://github.com/ISISComputingGroup/IBEX/issues/5704
- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/70

**Comment by DominicOram** [comment]
Reviewing as @JamesKingWork is off this week. Looks good, thanks John.

**Comment by kjwoodsISIS** [comment]
How many points was this?
