### ISSUE TITLE
SUPPORT: ENGINX BLuAC update steps/mm setting

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5690]
On EnginX they want to increase the steps/mm for the Z stage to see if it works better.

**Comment by John-Holt-Tessella** [comment]
Done

**Comment by DominicOram** [comment]
@John-Holt-Tessella am I correct in saying that the BLuAC is part of the positioner system and so this change was done in the labview?

**Comment by KathrynBaker** [comment]
Yes, this would have been setup changes in LabVIEW

**Comment by John-Holt-Tessella** [comment]
Yes
