### ISSUE TITLE
[required by 10/9/2020] EMU: (help to) convert script

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5691]
Script at `\\isis\shares\ISIS_Experiment_Controls\emu` is required in IBEX by Thursday 10th. Contact: Koji

**Comment by Tom-Willemsen** [comment]
ideally sit with scientist and show them how to convert it themselves.

**Comment by FreddieAkeroyd** [comment]
The `setthresholds` command in the script is basically sending its argument `mv` to all of the channels. So it is writing `mv` to all PVs of the form
```
IN:EMU:CAENV895_01:CR0:C$(C):CH$(CH):THOLD:SP
```
Where `$(C)` takes all the values from 0 to 6 
and `$(CH)` takes all the values from 0 to 15

**Comment by JamesKingWork** [comment]
Along with Koji I have converted the setthresholds and setthresholds2 method. They have been appended to emu_routines.py in the instrument scripts directory, they are hoping to test them tomorrow.

**Comment by JamesKingWork** [comment]
Test complete, code worked fine, Koji has said he'll send the histograms to compare but that shouldn't hold this ticket up

**Comment by rerpha** [comment]
Scripts look good, and have checked they exist on the emu config.

**Comment by kjwoodsISIS** [comment]
How many points?
