### ISSUE TITLE
SUPPORT: ZOOM scans script fixes

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5693]
Allow scan scripts to be run on zoom

**Comment by John-Holt-Tessella** [comment]
1. Commit current changes in the scans library
1. Update scans library to latest version
1. Undo commit to get units because it is not in installed version on genie_python
1. Don't use stride in scan function because it doesn't work
 
### Actions

- [ ] Create ticket for stride
- [ ] Put local changes onto master (NB the fix for detector and spectra table setting bug seen on LOQ seems to be it is testing the wrong values)
- [ ] Possibly get instrument scripts on zoom to be master

**Comment by John-Holt-Tessella** [comment]
pull request

- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/74

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/IBEX/issues/5813 for reminder

**Comment by DominicOram** [comment]
We should avoid this in the future, do we need a release cycle for InstrumentScripts?

**Comment by John-Holt-Tessella** [comment]
I think updating genie_python is rare and so this will not happen often. However maybe we should think about how instrument scripts are released and updated. Originally the idea was that scientists would do this however I am unsure whether they can or are aware they should be doing this.
