### ISSUE TITLE
Zoom: Script usage of change_sample_pars, dosans and dotrans cause import error

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5695]
Zoom called asking why scripts that had previously worked now produced errors when loading. These errors were `Undefined variable change_samples_pars` etc. We added:

```
from genie_python.genie import *
from inst import *
```

I have now also said to avoid unneccesary warnings by including `# pylint: disable=wildcard-import, unused-wildcard-import`.

The scripts would still have worked using check_script=False on the load_script call, however it seems best to encourage scientists to use the linter to catch real errors.

Docs added at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Error-Checking-Troubleshooting#errors `Undefined variable <variable_name>`

**Comment by Tom-Willemsen** [comment]
I think the fix for ZOOM is fine but I am not convinced that our documentation should be encouraging our users to use `import *` in their scripts. I think it would be better to encourage either:
- `g.begin()`
- `from genie_python.genie import begin`

**Comment by kjwoodsISIS** [comment]
But why, if the script worked previously, does it not work now?   What is the root cause of the problem?  Is it because the scientists are now using the linter?  Is it the changed import mechanism for the `inst` module (see #5262).

**Comment by John-Holt-Tessella** [comment]
Yes because off the linter. The python script window has the module loaded in already but the linter doesn't know that it wants a script with all references in. I think encouraging them to add the import lines because then it can easily be sent to the script server.

**Comment by JamesKingWork** [comment]
It is because the scientists are now using the linter. I have now updated the docs to reflect the comment (https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Error-Checking-Troubleshooting#errors).
