### ISSUE TITLE
SANS2D: migrate user scripts (with scientists)

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5699]
As a scientist on SANS2D I would like to migrate a small number of user scripts with help from IBEX developers, so that I can be confident migrating them myself in future.

Scientists have provided typical sans2d scripts which are at `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket5699`

Depends on https://github.com/ISISComputingGroup/IBEX/issues/5698

### Acceptance Criteria

- Scripts are converted
- Scientists can maintain them in the future

**Comment by DominicOram** [comment]
Meeting organised for 09/11/2020 11:00-12:00 to do this

**Comment by DominicOram** [comment]
Started this with scientists and have put results in the `\\ISIS\shares\ISIS_Experiment_Controls\data for tickets\Ticket5699\converted`

**Comment by Adam-Szw** [comment]
Most of the work is done for this ticket but it needs some decision making to be made regarding places where scripts control functionality of VI (which doesn't directly translate into Genie Python) and finish off 2 scripts
Thus I put it in impeded, waiting to discuss this with @RaiBishal

**Comment by Adam-Szw** [comment]
Release notes PR: https://github.com/ISISComputingGroup/IBEX/pull/6972
Converted scripts are in the folder as mentioned above
D20_sf and giasans_omega_scan_directs_overnight were discarded following conversation with instrument scientists so they were not converted

**Comment by rerpha** [comment]
Great, thanks, have copied them into c:\\scripts on NDXSANS2D, scientists are aware of these and are going to use them as examples.
