### ISSUE TITLE
Support: Set up GoPro [Timebox: 1 day]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5703]
As a person on support I would like others to see what I'm seeing. We currently have a go pro for this but to use it we will need to set up a RTMP server (otherwise we'll have to stream to facebook/youtube).

## Acceptance Criteria
* We can stream a video from the go pro on site to somewhere accessible by anyone in the team but not publicly accessible.

**Comment by DominicOram** [comment]
A go pro plus subscription may also be a solution

**Comment by JamesKingWork** [comment]
Fire off an email to site security about go pro plus

**Comment by davidkeymer** [comment]
- Does the camera support Bluetooth?  If so, could it be paired with the supporter's telephone and used as the main camera in Zoom?
- Are any other ISIS support groups using this "body cam" idea?  Could be useful for others diagnosing hardware trouble.

**Comment by FreddieAkeroyd** [comment]
I believe it does both bluetooth and WiFi, i've asked facilities about a long life user wifi code. I think if you had the gopro app on your phone you may be able to do something via that, if VLC as Chris found works directly then we may be able to configure vlc on some computer at work and create a zoom meeting sharing the vlc app, we then just join the meeting.

**Comment by KathrynBaker** [comment]
I think this is now beyond necessary, so I shall close this issue.
