### ISSUE TITLE
genie_python/scans Scripts: Set all Time Channel parameters in one go

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5704]
In the shared instrument scripts on LOQ they have the loop
```
gen.change_start()
        for trange in range(1, 6):
            gen.change_tcb(low=0, high=0, step=0, log=0,
                           trange=trange, regime=1)
            sleep(1.5)
        gen.change_tcb(low=0, high=0, step=0, log=0,
                       trange=1, regime=2)
        gen.change_finish()
```

to clear out the tcb setting before they set another set which might be smaller. We should create a command that either clears the ranges or allows a tcb set to be set with everything else in the trange set to 0. See https://github.com/ISISNeutronMuon/InstrumentScripts/blob/master/instrument/loq/sans.py in generic_scan

### Acceptance criteria

- Decide what the command should look like
- Implement the command
- Replace LOQs one with it

**Comment by Tom-Willemsen** [comment]
New bluesky scans library already allow setting multiple tcb ranges at once without the sleeps etc.
