### ISSUE TITLE
LARMOR: Disk space on VM is very tight - risk of database filling disk.

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5709]
LARMOR `C:` is very full, unusually the VHD disk needs to be expanded to 127GB max (80GB currently) but this will require a shutdown of the VM.  Check with scientist and maybe do at changeover time.

**Acceptance Critera**
1. C: volume is expanded to 80GB
2. VHD is expanded to (max) 127GB

**Comment by kjwoodsISIS** [comment]
How many points?
