### ISSUE TITLE
IBEX Training: SANS2D

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5714]
Deliver a training course for SANS2D scientists.  Aim for mid-October 2020.

#### Acceptance Criteria
- [x] Select Date
- [x] Advertise training
- [x] Book venue
   - [x] venue will be Zoom
- [x] Assign trainers
- [x] Review course materials
- [x] Send Zoom joining instructions to delegates
- [x] Set up machines
- [x] Deliver training
- [x] Apply retrospective changes to process/wiki/slides
  * See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
  * Updated documents in http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FTraining&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View=%7BF2C33C51-70E6-4343-B937-2C59A2568306%7D

#### Notes
1. We will need to adapt our training to deliver it on-line
   * Suggest breaking it up into small chunks (e.g. four 1/4-day sessions, rather than two 1/2-day session).
1. Additional instructions for setting up training can be found here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX
   * not all of these instructions will be relevant to on-line training

**Comment by DominicOram** [comment]
Need to think about how to set up machines so that people can remote in

**Comment by DominicOram** [comment]
I'm happy to be a trainer for this and support someone in rewriting the material but I don't have time to lead it.

**Comment by kjwoodsISIS** [comment]
Two things;
1. The graduates should participate in the training - to get the experience.
1. Ideally, an ISIS person should lead this training

**Comment by DominicOram** [comment]
I'm going to get this moving as it will be hard to get it in the shutdown otherwise

**Comment by DominicOram** [comment]
Emailed instrument scientists suggesting the following sessions:
* Introduction to IBEX (30-60 mins)
    * How to start/stop everything
    * What do the different perspectives do
    * A basic overview of what’s going on behind the scenes
* Configurations and Synoptics (60-90 mins)
    * How to create and edit configurations
    * How to create and edit components
    * How to create and edit synoptics
* genie_python and Scripting in IBEX (90-120 min, will include a break at 60 mins)
    * Basic genie_python commands
    * User and instrument scripts
    * The script server/script generator
* Converting between open genie and genie_python (60 mins)
    * The major differences between the languages
    * Some example conversions
    * Hands on conversion of a selection of SANS2D user scripts (therefore will also complete https://github.com/ISISComputingGroup/IBEX/issues/5699)

**Comment by DominicOram** [comment]
/remind me on Monday to invite all scientists

**Comment by DominicOram** [comment]
* Added PR to fix some training install stuff at https://github.com/ISISComputingGroup/ibex_utils/pull/99
* Added a bit of info at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX#decide-which-training-venue-to-use

**Comment by DominicOram** [comment]
Repointing as just review left
