### ISSUE TITLE
Many Instruments: instrument time stops updating

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5717]
This has happened this morning over a windows of an hour, but on zoom seems to have happened earlier.  PVs stop updating, but can still be read.

**Comment by FreddieAkeroyd** [comment]
Looking at IRIS, only thing in system log at 10:15 was
```
The WMI Performance Adapter service entered the stopped state. 
```
This is not uncommon, it seems to stop and start a lot - however usually the time difference between stop and start is very short (1 minute or less). At 10:15 it stopped for 5 minutes before restarting.

At 10:30 there was the following WMI error in the system log
```
Event filter with query "SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA "Win32_Processor" AND TargetInstance.LoadPercentage > 99" could not be reactivated in namespace "//./root/CIMV2" because of error 0x80041003. Events cannot be delivered through this filter until the problem is corrected.  
```

**Comment by ChrisM-S** [comment]
The last time when this happened, one instrument had a WMI error message in the application log and nothing in the system log.  I think the application log was linked with the virus checker.

The message you've seen _may_ be a standard check from the old TBT log manager client - of which there are still odd things which appear - may not matter if the source is from a filter of this it might not matter or just possibly be a symptom of the WMI activity.

**Comment by Tom-Willemsen** [comment]
Related ticket: https://github.com/ISISComputingGroup/IBEX/issues/5323

**Comment by FreddieAkeroyd** [comment]
From the debugger there is no obvious place where it is hung, that may have been the same as before as I mention "guess" so if there had been a nice stack trace hung on a WMI call that would have been more definite. All we can summise is that:
- It affects all IOCS at the same time
- It affected different instruments at different times, but within a few hours window.

**Comment by FreddieAkeroyd** [comment]
Happened on just SANDALS at 10:09 17/9/2020. It looks like is is a hang of the db periodic scan loop. Reading PVs by channel access is file, the `IN:SANDALS:AS:INSTETC_01:SR_heartbeat` pv was happily updating, but IN:SANDALS:CS:IOC:INSTETC_01:DEVIOS:HEARTBEAT was frozen as was UPTIME and TOD. Running generalTimeReport  from IOC console gave sensible result. 

From system log all i can see is a WMI performance adapter service starting at 10:09:57 and stopping at 10:18

**Comment by FreddieAkeroyd** [comment]
Given re-occurrence, this probably requires urgent investigation

**Comment by DominicOram** [comment]
On MARI this also caused the running genie_python session to no longer be able to get pv values (see https://github.com/ISISComputingGroup/IBEX/issues/5731)

**Comment by FreddieAkeroyd** [comment]
The issue has been confirmed to be a timer wrap at 49.7 days of uptime when GetTickCount() overflows, when return values are subtracted in the wait calculation this results in a very large wait being requested and periodic scan loops all hang (i/o intr still work). The GetTickCount64 function returns the same information, but in a larger sized integer, so does not overflow. The return type of the epics function itself is already a 64bit integer.

**Comment by Tom-Willemsen** [comment]
Related threads:
- https://bugs.launchpad.net/epics-base/+bug/1896295
- https://epics.anl.gov/core-talk/2020/msg01336.php

**Comment by DominicOram** [comment]
@FreddieAkeroyd will we need to update the version of EPICS base that we build CaChannel/pcaspy against?
