### ISSUE TITLE
SANS: Sample Changer - select preset positions

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5720]
As a SANS scientist I need to be able to select a sample changer position from a predefined set, so that I can easily move my sample changer to a known position.

#### Acceptance Criteria
1. The following features are available on the main tab of the OPI (see #5719).
1. In order to select a named position from the set of available preset positions, I can:
   1. select the sample changer
   1. select a named position from the preset positions associated with the chosen sample changer.
1. I can select a named position by typing its name (see Note 2)
   * when I have typed the name and pressed the Return key, the move should be initiated.
   * if I type a name that does not exist, no move should occur.
1. The Sample Changer OPI must display:
   * preset setpoint (labelled Target)
   * preset setpoint for the X coordinate
   * preset setpoint for the Y coordinate
   * preset readback (labelled Current)
   * preset readback for the X coordinate
   * preset readback for the Y coordinate
   * the OPI must display setpoint and readback values the dynamic offsets
1. The Sample Changer OPI must display LEDs to indicate if the X and Y motor axes are moving
1. The Sample Changer OPI must display a green border around the Current, X and Y fields when the sample changer is "in position" (to within a defined tolerance).
1. The Sample Changer OPI must display a red border around the Current, X and Y fields if there is a "positional error" (i.e. exceeding the defined tolerance) in the sample changer.

#### Notes
1. Some SANS instruments have very long lists of presets.  The scientists accept that a single, very long list of presets is impractical and that an alternative way of selecting presets is needed.  The two-stage process described in the acceptance criteria has been discussed with the scientists.
1. The SANS scientists know the names of the preset positions that they use regularly.  Being able to type the name in the Target box is convenient.

**Comment by DominicOram** [comment]
> Some SANS instruments have long lists of presets. It must be easy to quickly select one by typing its name or typing the first few letters of its name

This requires a conversation to work out why there are so many and how they're organised. It may be that we have a selection box for which sample changer used and another for the position. @Kevin-Woods-Tessella to do this.

**Comment by Tom-Willemsen** [comment]
Part of the confusion between the different instruments is that they use completely different epics modules underneath.

LARMOR and ZOOM use the code in `support\sampleChanger\master`, LOQ uses the code in `support\motionSetPoints\master`. I had not appreciated this difference.

**Comment by kjwoodsISIS** [comment]
Going forward, we want all the SANS instruments to share the same code underneath.  With the decision that the SANS group will select the sample changer first, then select the pre-sets relevant to the sample changer, I suspect this means that they will all need to use the LARMOR/ZOOM code.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1199
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/375
- https://github.com/ISISComputingGroup/EPICS-sampleChanger/pull/4
- https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/15
- https://github.com/ISISComputingGroup/EPICS-axis/pull/6

Docs: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Sample-Changers#generic-sample-changers-support-module

**Comment by DominicOram** [comment]
> Going forward, we want all the SANS instruments to share the same code underneath. With the decision that the SANS group will select the sample changer first, then select the pre-sets relevant to the sample changer, I suspect this means that they will all need to use the LARMOR/ZOOM code.
> 
> > For the drop-down menu ‘shrinkage issue’ then I think the two menu option might work.
> > As you say it also adds another ‘inconvenience’ but as I wrote I think the manual
> > input will be most commonly used and so having a drop-down where we can at least see
> > all the options on one screen would be better than what we currently have.
> > > One way to limit the length of the drop-down menu would be to split the selection
> > > of a pre-set across two drop-down menus.  One menu to select the sample changer;
> > > a second which displays only the pre-sets associated with the selected sample
> > > changer.  I guess it is a matter of (in)convenience – do you want to choose from
> > > a long list of pre-sets or use two drop-down menus.
> 
> See also [SampleChangerThread.pdf](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SampleChangersThread.pdf).

@Kevin-Woods-Tessella It's great to see this thread to give some background to the ticket. It references some slides, that I assume the scientists created? Would you be able to upload those slides too?

**Comment by Tom-Willemsen** [comment]
> ...It references some slides, that I assume the scientists created? Would you be able to upload those slides too?

Sorry, I got forwarded a copy of these slides but forgot to upload them. Now in SANS2D folder on sharepoint (`Sample_Changer_Stack_v3`)
