### ISSUE TITLE
SANS: Sample Changer - dynamic offsets

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5721]
As a SANS scientist I need to be able to define dynamic offsets, so that I can make small adjustments to the position of my  sample changer.

#### Acceptance Criteria
1. The following features are available on the advanced tab of the OPI (see #5719).
1. I can define dynamic offsets.  The Sample Changer OPI must display:
   * dynamic offset X and Y setpoints (labelled Target)
   * dynamic offset X and Y readbacks (labelled Current)

#### Notes
1. Dynamic offsets are already supported by the existing sample changers used on SANS instruments.

**Comment by Tom-Willemsen** [comment]
This is covered by the existing motionSetPoints logic + the opi in https://github.com/ISISComputingGroup/IBEX/issues/5720

(reviewer: just check that the acceptance criteria on this ticket are covered by the opi in 5720)
