### ISSUE TITLE
SANS: Sample Changer - View Motors

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5722]
As a SANS scientist I need to be able to view and control the details of the motors that move my sample changer.

#### Acceptance Criteria
1. The following features are available on the advanced tab of the OPI (see #5719).
1. For each motor:
   * there is a "View Motor" button
   * labelled with the name of the motor
1. On clicking a "View Motor" button, the OPI should display an OPI displaying the relevant motor details.

#### Notes
1. None, so far.

**Comment by Tom-Willemsen** [comment]
Needs #5720 to be merged first before this can be reviewed.
