### ISSUE TITLE
SUPPORT: Motor has moved to home and doesnt' appear to be able to move off

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5727]
After a move to Home, a motor on ZOOM appears to have to stuck on the home and cannot be moved off it.

**Comment by ChrisM-S** [comment]
Left message on technical in teams, see for contact details.

**Comment by ChrisM-S** [comment]
Hardware problem, both limits activated on OPI and on scientist checking the Galils, this was also showing in hardware.  See diagnostics at 
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting#the-limits-are-both-made

**Comment by DominicOram** [comment]
Looks covered by documentation.
