### ISSUE TITLE
MARI: Add additional homing routine and correctly set up sample changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5729]
As a MARI instrument scientist I would like my sample changer to work regardless of whether it is the "belt" sample changer or the universal joint one. Due to the mechanics of the system each sample changer must always run in the same direction, including when being homed. Currently the logic for this is in the `changer.py` script but it should instead be moved into the Mclennan configuration. See original ticket at https://github.com/ISISComputingGroup/IBEX/issues/5322

## Acceptance Criteria
* There are two configs for the different sample changer types
* The direction is set into the config such that positive moves in both turn the device in the correct direction
* The homing routine is set so that both move in the correct direction when homed
* The offset is set in the configuration rather than the script
* Test this on the hardware with Duc's script
* Duc's script moves 89.4 degrees for each sample rather than 90 to correct for an inaccurate motor resolution. Correct this  and confirm that after a large number of moves the sample changer is still moving accurately (see `NDXMARI/c$/scripts/test_sample_changer.py` to help with this

**Comment by DominicOram** [comment]
Docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MARI-Sample-Changer

**Comment by Tom-Willemsen** [comment]
+1 vesuvio would also like a mclennan homing routine to be able to go in both directions

**Comment by DominicOram** [comment]
This is required to fix the hotfix that's currently on MARI https://github.com/ISISComputingGroup/EPICS-motor/tree/Ticket5322_mclennan_homing

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-motor/pull/38
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/597
- https://github.com/ISISComputingGroup/IBEX/pull/6293

I did look at adding ioc tests for this but it didn't look easy as the mclennan doesn't currently have an emulator, and it felt unreasonable to implement a whole mclennan emulator for this ticket. Happy to discuss if reviewer has ideas.

**Comment by Tom-Willemsen** [comment]
This has now been tested on the office McLennan with help from @DominicOram and it homes in the expected directions in both modes 2 and 4.

**Comment by DominicOram** [comment]
I'm removing the rework label so that others feel they can pick it up now that @John-Holt-Tessella is no longer around
