### ISSUE TITLE
Script generator: Create release

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#5730]
As a user of the script generator I want a new release to fix bugs which were found in release 7.2.0

## Dependencies
- [x] https://github.com/ISISComputingGroup/IBEX/issues/5700
- [x] https://github.com/ISISComputingGroup/IBEX/issues/5708

## Acceptance criteria
- [x] A release of the script generator has been made

**Comment by DominicOram** [comment]
#5708 isn't done as the solution is hacky and so needs something more long term but enough to deploy something

**Comment by kjwoodsISIS** [comment]
Can this ticket continue, despite #5749 ?

**Comment by DominicOram** [comment]
Yes, I'm going to do it manually

**Comment by DominicOram** [comment]
Release created at https://github.com/ISISComputingGroup/ScriptGeneratorReleases/releases/tag/v7.2.1

**Comment by DominicOram** [comment]
Fixed sms import issue, https://github.com/ISISComputingGroup/genie_python/pull/287 should be a permanent fix.
