### ISSUE TITLE
SUPPORT: genie_python in ibex GUI no longer set/reads block pvs

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5731]
Rrot is a valid block.

1. Type `g.cget("RROT")` pv is disconnected
1. get_blocks() shows pv name
1. b.Rrot exists
1. new genie_python session pv has value and is connected
1. get base pv, pv shows disconnected

Eventually restarted console and it was fine.

### Notes

- Had been used the day before without problem (same terminal)
- No errors in any logs that I could see
- time was around 16:00 on 17/09/2020

**Comment by John-Holt-Tessella** [comment]
Doc of what to try at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/genie_python-Troubleshooting#can-not-set-or-get-a-block-reports-diconnected

**Comment by DominicOram** [comment]
I found this same issue on MARI, underlying cause I believe was the same as https://github.com/ISISComputingGroup/IBEX/issues/5717 as it was in such a bad state at the time.

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella Which instrument was that? Helen Playford reported a similar issue on POLARIS yesterday as per email on Teams, in that case it was DAE PVs  
```
2020-09-16T09:36:39       (CMD)   (1636)   2020-09-16 09:36:39.138005: Exception in waitfor loop: UnableToConnectToPVException: Unable to connect to PV IN:POLARIS:DAE:GOODUAH: does not exist
```

**Comment by DominicOram** [comment]
@FreddieAkeroyd had POLARIS hung with #5717 at the time?

**Comment by FreddieAkeroyd** [comment]
@DominicOram  Yes, it happened at the same time as #5717. It is weird that some things can still read PVs and others can't

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd  this was on alf
