### ISSUE TITLE
CRISP: Reinstate Galil positions (from 23/10/2020)

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5732]
As documented in #5511, power was lost to the CRISP Galil controllers and so they will need their original positions reinstated (to avoid homing all axes).

IS is happy to wait for this to be done until after the POLREF tests are complete on the maintenance day on 07/10/2020.  If this turns out not to be possible, then the cycle after that is also a possibility.

Suggest checking with IS on or just before the target date to find out whether or not the plan has changed.

#### Acceptance Criterion

* Current positions of all axes reflect those prior to the power cut

**Comment by davidkeymer** [comment]
Inconvenient for this work to be done on the planned maintenance day.  Issue will now be addressed in the next (short) shutdown (23/10/2020 - 10/11/2020).

**Comment by ThomasLohnert** [comment]
I have put files containing the positions to restore in the private share in the folder `Ticket5732`. Awaiting comms to be restored to Galils on CRISP

**Comment by ThomasLohnert** [comment]
Done as of 05/05/2021. Scientists have been informed.

**Comment by JamesKingWork** [comment]
Based on email chain from 05/05/2021 looks good
