### ISSUE TITLE
IMAT: Disk space on VM is very tight - risk of database filling disk & data loss.

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5733]
The `Var` area on IMAT is currently about 15GB which is 5GB over the agreed upper limit of 10GB.

**Acceptance Criteria:**

1. Var is down to < 5GB (or enough so that it will not overflow before the next IBEX release when it will be cleaned up).
2. A check is done to see if there is anything which is filling it up very quickly (e.g. disconnected equipment).

**Notes:**

There is an 8GB msg log file - not sure why this might be so large?

**Comment by John-Holt-Tessella** [comment]
It is because the eurotherm is logging 60Mb a day and there are 2 of them

**Comment by ChrisM-S** [comment]
in case it's worth 1000 words (I've got treesize eye's on a lot of machines currently!)

IMAT
![image](https://user-images.githubusercontent.com/3035405/93617489-f27b4c00-f9cd-11ea-9ca3-e49b17d403aa.png)

**Comment by ChrisM-S** [comment]
Is the message log a database of something unique @John-Holt-Tessella ?

**Comment by ChrisM-S** [comment]
ahh, think I've answered my own question, this is just messages to message panel? - which are really expendable ?

**Comment by KathrynBaker** [comment]
The original purpose at least was to look in the message log to trace what has gone wrong, the message panel also pulls from that database. Not really expendable (except that most people don't use that log which is meant to be more searchable than the reams of files which contain these errors - basically it should give you the coarse search and info that might be enough to resolve the problem, or gives you a better idea of where to look for it - should save us needing to ask the scientists when something went wrong), but certainly trimmable and less use after a certain length of time.
