### ISSUE TITLE
SANS2D collision avoidance: set deceleration to a high value before stopping motor

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5735]
As an instrument scientist on SANS2D, I would like the collision avoidance system to be able to avoid collisions.

Currently the motor is stopped (via the `.STOP` field of the motor record) when the axes are within a tolerance of each other. However, due to the deceleration time, there is a significant run-on after the stop is sent. In the case of the baffles, this is about 50mm which, which means that the collision avoidance system is actually unable to stop the motor fully before the bump strips are hit.

We should implement the following workflow:
- Remember old deceleration
- Set deceleration to a high value (see fast deceleration galil code, which is activated on bump stops, for sensible values)
- Send STOP
- Put deceleration back to original value

### Acceptance criteria
- Motors stop quickly when a clash condition is detected by the sans2d collision avoidance system.
- Notes are edited to include chaging rate (last paragraph of https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-vacuum-tank-collision-avoidance)

### Notes
For clarity: this ticket refers to the collision avoidance system implemented in DB records for SANS2D - not the fast deceleration galil code, which is triggered by the bump strips.

**Comment by John-Holt-Tessella** [comment]
Would it be possible just to increase the avoidance lengths then the deceleration is slow?

**Comment by Tom-Willemsen** [comment]
If we increase the collision avoidance lengths enough to sort this, we would prevent them from moving to useful positions.

**Comment by John-Holt-Tessella** [comment]
Cool, I am sorry I saw this in review but thought it was part of the system. It is currently in the notes of how the IOC works so will need editing in there; have added to acceptance criteria (end of https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-vacuum-tank-collision-avoidance)

**Comment by Tom-Willemsen** [comment]
Pulled into sprint as we would like to test this during the next SANS2D commisioning time (in shutdown)

**Comment by Tom-Willemsen** [comment]
Impeded until setting deceleration mid-move is tested on real axis. Trying to get hold of a real axis on CRISP (should be possible, scientists just need to check area is locked etc).

**Comment by Tom-Willemsen** [comment]
Tested on a real galil axis on CRISP. Acceleration is only sent on move start. Setting the acceleration mid-move and then stopping uses the old acceleration, not the new acceleration.

For this ticket we will need to use a different approach which is probably to define a fast stop galil routine and then call that routine by passing the galil an appropriate variable.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-galil/pull/46
- https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/32

As this is galil code I don't think it's possible to test in an automated way - we will need to test it against hardware on SANS2D.
