### ISSUE TITLE
RIKENFE: Clear Disk Space

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5740]
RIKENFE has a low amount of disk space left.

Acceptance criteria:

- RIKENFE no longer has a disk space warning on Nagios (except for read only vol which is small)

**Comment by kjwoodsISIS** [comment]
@JamesKingWork - is this ticket actually done?  Does it need to be reviewed or just moved to complete?

**Comment by JamesKingWork** [comment]
@Kevin-Woods-Tessella My mistake I had moved it in the other project board, but not this one. I am not sure it's worth the time to review it as the disk space has been increased?

**Comment by kjwoodsISIS** [comment]
Well, TBH, what is there to review?  Similar tickets don't seem to have had much of a review (see #5728, #5755, #5762).
To my mind, all it needs is some evidence that the disk space has been increased (e.g. a screenshot of the relevant row in Nagios).

**Comment by John-Holt-Tessella** [comment]
Yes, in fact you can just check nagios, no screen shot needed. @Kevin-Woods-Tessella are you reviewing this? Did you want to know how to log into nagios?
