### ISSUE TITLE
System Tests: create background script IOC test

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5743]
Follows on from #5710 

As a developer I would like a system test that tests the functionality of the [background script IOC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Background-Script-IOC). This is difficult at the moment as the background script IOC has a hardcoded path to find a script, which could be made easier for production and testing by passing in a macro argument with the python script's filepath.

### Acceptance criteria
1. Background script IOCs take in a macro of which script to run
1. If no path is given, choose the default path which it is currently using (no test needed for this)
1. system test is created to test the IOC with a macro
1. system test is created to test the `restart_ioc_when_pv_in_alarm` script in the instrument scripts repository

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/715
https://github.com/ISISComputingGroup/EPICS-icpconfig/pull/9
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/555
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7289
