### ISSUE TITLE
Reflectometry: Find out where offset in RBV comers from

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5745]
Suring testing on POLREF it appeared that the RBV for vertical split to showed an additional 0.2 over the set point for several values. This does not make sense and we should try to reproduce and fix this.

Reproduction could be hard, for info we had been using it for a while there are screen shots of the various panels in on `instrument\screenshots\2020_sept\S2Offset Fail*` POLREF.

### Acceptance Criteria

- Error is reproduced
- Error is fixed

**Comment by John-Holt-Tessella** [comment]
Email sent:

Do you remember last week we had the weird offset on the s2v (S2OFFSET) parameter in IBEX, where the readback value and set point were off by roughly 0.2:

sp read -0.16 RBV reads -0.139 (image from OPI showing S2OFFSET)

I have reproduced this on my local machine, it looks like:

sp read -0.16 RBV reads -0.139 (image from OPI showing S2OFFSET)

What I needed to do was to set the polarising mirror to an angle of 0.54980 deg not 0.55 this is a single encoder step different from the set point. Doing this meant that the polariser reflects the beam slightly differently and so it will be offset from the beam. All the angles etc. are written to 3dp which is why we didn’t spot it. This is different behaviour to SECI which will report the motor position which assumes that the beam is bounced correctly. The current setup is

0.000125 Motor resolution
0.0002    Encoder resolution
0.0005    Retry deadband 
0.0005 Set point deadband

I think that because the motor resolution is so fine we might be able to get away with making the retry deadband and set point deadband 0.0003

Now when scanning that parameter I am not sure which is best to use, so if we do it on the value in relation to the beam it means it should be better wherever the beam ends up. 
So in SECI the beam is assumed to be at the set point but isn’t so you set the 0 at the position for the angle of 0.55 instead of 0.54980, so next time it goes to 0.55 the beam is slightly off.
In IBEX the beam is where it is and you set 0 at the point relative to the beam but maybe when requesting 0.55 you always go to 0.54980 so it is less accurate.
I am unsure and probably need to talk with you to work out if this is actually true instead of a feeling. Possibly with diagrams.

**Comment by John-Holt-Tessella** [comment]
Impeded until I can talk with instrument scientist.

**Comment by John-Holt-Tessella** [comment]
Scientists are happy

**Comment by DominicOram** [comment]
Confirmed that the deadband is now less. 

> Now when scanning that parameter I am not sure which is best to use, so if we do it on the value in relation to the beam it means it should be better wherever the beam ends up.
So in SECI the beam is assumed to be at the set point but isn’t so you set the 0 at the position for the angle of 0.55 instead of 0.54980, so next time it goes to 0.55 the beam is slightly off.
In IBEX the beam is where it is and you set 0 at the point relative to the beam but maybe when requesting 0.55 you always go to 0.54980 so it is less accurate.
I am unsure and probably need to talk with you to work out if this is actually true instead of a feeling. Possibly with diagrams.

In the discussion with the scientists was a decision made for one of these directions to take?

**Comment by John-Holt-Tessella** [comment]
Because the deadband was less it meant that there was no offset so the question wasn't important
