### ISSUE TITLE
VESUVIO: Investigate issue with left forward foil [Maintenance Day 23/09/2020]

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5747]
IS reported on 20/09/2020 that after the IBEX server was restarted, control of the left forward foil was lost, whereas the right one behaved normally.

#### Acceptance Criteria
* Causes and solutions are documented
* Additional ticket(s) created as required

#### Notes
* Apparently the problem arises at the start of almost every cycle.
* It is not clear whether or not this happens with a restart of just the Mclennan IOC, or the whole server.
* The most recent occurrence was solved by IS restarting the controller and manually entering the offset and limits in the motor panel, then rehoming the axis.  (IS followed instructions in the Motor section of the Developers' Manual, rather than Mclennan.  Ticket #5748 is to update the documentation)
* It is believed that for the Mclennan IOC, the calibration values are entered/saved via macros in the IBEX client configuration, rather than PVs in the motor panel and autosaved (as in the Galil driver).  If values are entered in the motor panel for any reason, they would be overwritten by the next IOC/server restart.
* It is possible to read the status of the Mclennan controller to determine its error state, and that of the limit switches.  If this would help with a solution, check whether or not the current IOC does this and create a ticket if not.

**Comment by kjwoodsISIS** [comment]
@davidkeymer , @FreddieAkeroyd - is this ticket considered complete?  Does it need review or just moving to complete?

**Comment by FreddieAkeroyd** [comment]
User proceeding as follows until #5739 resolved
```
## Homing left and right foils

Do not home in ibex
Drive the foil with mclennan front panel to appropriate limit (upper limit for left foil, lower limit for right foil). 
Goto the motor details page in ibex

-	Check the led is red next to the appropriate limit to indicate it is on the limit switch 

-	in the calibration section:
-	Don’t change the Off: value 
-	Set calibration to frozen
-	Push “set”
-	Type 0 into the Move Abs Dial column (the corresponding “user” column value should update automatically)
-	Push “use”
-	(it is ok to leave calibration as frozen – no need to set back to variable)

The offset value in the Calibration section should not get altered by this procedure, as the dial position is zero both the user readback value and the offset should be the same and reflect the position you currently expect (42.5 right, -41.75 left). 

To test you could drive to the other limit and back etc. Whenever you drive to the  appropriate homing limit the Dial value should end up being 0 (or very close to)

Note: Ibex stores the “offset” and high/low soft limits as part of the configuration, so if these are changed on the motor details they would also need to be changed on the config page or they will get reset on an ibex restart. I think I have adjusted the left ones to work on the above procedure, but we can check later.
```

**Comment by John-Holt-Tessella** [comment]
Added docs to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Vesuvio-homing-sequence
