### ISSUE TITLE
IBEX Developer's Manual: Edit Motor and Mclennan pages

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#5748]
Some confusion arose when an IS altered Mclennan axis settings via the standard motor panel, which were subsequently overwritten when the IOC was restarted.  This occurred because the settings in question are controlled via macros, rather than PVs and autosave.

This ticket is to update the relevant pages in the Developers' Manual:

* [Standard motor](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Set-the-raw-position-of-the-motor-without-moving-it)
* [Mclennan](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/McLennan-motors)

#### Acceptance Criteria
* Pages updated to provide more accurate documentation and troubleshooting information.

#### Notes
* See #5747 for details of original issue

**Comment by DominicOram** [comment]
Notes added on the two pages

**Comment by DominicOram** [comment]
Added into sprint as it was high anyway and otherwise we'd spend longer discussing the ticket than just doing it.
