### ISSUE TITLE
Script Generator Releases: Cannot create release

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5749]
As a developer I would like the script generator release utility to create the release for me. Currently https://github.com/ISISComputingGroup/ScriptGeneratorReleases fails on the `create a release` step as it is unable to tag a release against the `base` tag as it already has an associated release. To fix this ticket we will need the script to create a new tag in the repo before creating the release. This can be gone though something like `gitpython`.

## Acceptance Criteria
* The script generator release correctly uploads to github

**Comment by JamesKingWork** [comment]
This is likely because we are trying to create a release from a base tag. We probably need to make a new tag and then create the release from that.

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/ScriptGeneratorReleases/pull/2
