### ISSUE TITLE
Script generator: Discuss how scientists should update the definitions

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5754]
As an instrument scientist I would like a reliable way to modify my script definitions such that changes are tracked and users can easily get the latest version without causing issues such as that in https://github.com/ISISComputingGroup/IBEX/issues/5753. Some thoughts for the discussion:

* How much should scientists expect to be aware of git and how to put their definitions in there?
* Where would scientists be modifying their script definitions from?
* What git accounts do we give them to have write access to the definitions?
* Where should script definitions live? Currently they're in `C:\ScriptDefinitions` on the instrument. If this is staying how do we make sure we update the preferences correctly on each new deployment of the script generator? Check on how W10 clone would work

## Acceptance Criteria
* A meeting has been had by developers to work out the suggested workflow
* This is written up somewhere
* This has been discussed with relevant instrument scientists and they are happy with it

**Comment by kjwoodsISIS** [comment]
Some observations/thoughts:
* git is a programmer's tool.  It is not a tool for novices.  If you are not a proficient programmer, you are going to struggle with tools like git.  
* The ScriptGenerator is a tool to help users who might not be familiar or confident in programming to write genie_python scripts.  If all you want to do is generate simple scripts, then all you care about is whether the ScriptGenerator can do the job.  You really don't care what happens under the covers.  In fact, if the inner workings of the ScriptGenerator have to be exposed, it can be confusing or distracting.  
* Users need not and should not be aware of git.  I don't think instrument scientists should be aware of it either.
* Why do we use git at all in the ScriptGenerator?  What problem(s) is it solving?

**Comment by DominicOram** [comment]
* We are assuming the instrument scientists to be programmers by asking them to write the script definitions themselves
* I agree that no user should ever care about how the script generator works, how it stores the script definitions or git but as someone modifying the script definitions (e.g. an instrument scientist) you do have to care to some degree about these things

The major problems git is solving:
* History of script definitions, being able to see what changed and when
* Reverting script definitions, being able to go back to a script definition used for a previous experiment
* Ensuring there is a single definitive version of the script definition that you are using, regardless of where you are using the script generator from e.g. an instrument scientist could make a modification to the script definition at ISIS and this will be available for people using the script generator at home without requiring a new version of the script generator

**Comment by kjwoodsISIS** [comment]
Yes, I agree, we do expect instrument scientists to have some degree of programming proficiency.  They are expected to write their own scripts, after all.  Script definitions are just an extension of that.  But we don't expect users to have any programming proficiency.

Instrument scientists should know where to put new or updated script definitions, but that's about the limit of what they need to know.  I don't believe they need to know about git.  If the ScriptGenerator does not already automatically recognise that a new script definition has been created (or an existing one updated), then I think we should do something like create a simple `.bat` script that checks the new/updated file and explain to the instrument scientists that they need to run the `.bat` script each time they add/modify their script definitions.

**Comment by JamesKingWork** [comment]
Outcome:

- Scientist workflow
  - We will write a python/batch script to manage the git repository
  - Scientists will edit their script definitions and use our script to manage the repository
  - We will prevent them from committing as spudulike, the script will have to ask for a username (e.g. fedid) and password to commit with
  - Script will leave a message that identifies that the push was done in the approved manner i.e. using our script to catch people who try to circumvent the method
  - Script will prevent the user from setting username and password to use all the time for pushing to this repository
  - The script will do: pull, add, commit and push to master
  - Must have git and python installed
  - Must have access to repository origin
- Repository storage
  - We will investigate the use of the site gitlab instance
    - This instance should allow people with a fed id to be able to edit scripts, preventing us from the need to manage who is authorised
  - Alternative is to use our own git instance
  - This must be available for external users of the script generator
- Structure of the repository
  - Similar to the instrument scripts directory have folders for instruments and common areas
  - The script generator itself must be changed to recognise that this is no longer a flat filesystem
- We need to know where script definitions are stored on an instrument
  - This should be standardised: have a preference for using C:\Instrument\Settings... and fall back onto a folder in the same directory as the executable
  - This should be written down in the wiki once standardised and deployed
- As we are using a similar workflow to the instrument scripts we will have similar issue
  - We should write an automated service that checks for any uncommitted changes on instruments similar to https://github.com/ISISComputingGroup/IBEX/issues/5907

I will write this up into a set of tickets and into the decision log

**Comment by kjwoodsISIS** [comment]
I think the workflow should be written much more from the instrument scientist's point of view.  How about this?
The workflow for creating or modifying script definitions is:
1. The instrument scientist creates a new or edits an existing a script definition using a text editor (e.g. Notepad++).
1. The instrument scientist saves the script definition:
   1. if using his/her office (or cabin or home) PC, the script is saved locally (to a directory of the scientist's choosing)
   1. if using the instrument control PC, the script is saved `<where?>` (to a directory of the scientist's choosing?)
1. The instrument scientist transfers the saved script definition to the script definition repository.
   * the scientist will use a command (in practice a python or batch script) to perform the transfer
   * the command will print a message to inform the instrument scientist of success or failure of the save operation
1. If the transfer:
   1. succeeds: the scientist need do nothing more
   1. fails: the scientist should contact the Experiment Controls group for support.

Notes:
1. We expect instrument scientists to create/modify script definitions.  We do not expect users to create/modify script definitions.  We should advise instrument scientists not to allow users to create/modify script definitions.
1. We will create a python/batch script to manage transfer of saved scripts to the git repository
1. We will prevent instrument scientists from committing as `spudulike`, the script will have to ask for a username (e.g. `fedID`) and password to commit with
1. Script will generate a commit message that identifies that the push was done by the script (i.e. to help us to identify situations in which someone has tried to circumvent the script by using git commands directly)
1. Script will prevent the user from setting username and password to use all the time for pushing to this repository
1. The script will do: pull, add, commit and push to master
1. Must have git and python installed
1. Must have access to repository origin

**Comment by JamesKingWork** [comment]
Tickets to carry out the work:

- https://github.com/ISISComputingGroup/IBEX/issues/5935
- https://github.com/ISISComputingGroup/IBEX/issues/5936
- https://github.com/ISISComputingGroup/IBEX/issues/5937
- https://github.com/ISISComputingGroup/IBEX/issues/5938
- https://github.com/ISISComputingGroup/IBEX/issues/5939

**Comment by JamesKingWork** [comment]
Updated decision log see 24: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Decision-Log
