### ISSUE TITLE
Support: ENGINX Log files not being produced

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5757]
ENGINX was no longer getting log file produced for the stress rig

### Acceptance Criteria

- Log files are restored
- Troubleshooting issue can be found to fix this

**Comment by John-Holt-Tessella** [comment]
ARINST seemed to have crashed (console reported as down) going to guess this was a procserve failing bug?

**Comment by Tom-Willemsen** [comment]
Sounds like https://github.com/ISISComputingGroup/IBEX/issues/5580

**Comment by John-Holt-Tessella** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-And-Device-Trouble-Shooting#value-logs-from-ioc-not-producedaraccess-not-creating-log-filesenginx-stress-rig-not-writing-log-files
