### ISSUE TITLE
Support: IMAT computer is down

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5760]
The IMAT control computer stopped working around 2:30am this morning.  After attempting to restart & full power cycle by removing cables there was still no response to the power button.  @ChrisM-S Replacing server with spare now.

** Acceptance criteria **
1. Machine is replaced with spare and disks swapped.
2. IMAT is back in action.
3. Machine records are updated to reflect replacement.

**Comment by DominicOram** [comment]
I've put this on the project board as in progress as I know it's been somewhat done. @ChrisM-S if the records are up to date and you're happy for this to be called done can you put it in review?

**Comment by kjwoodsISIS** [comment]
@ChrisM-S - is this ticket waiting for something to happen or is it actually done now?  Does it need review?  Can it be moved directly to complete?  How many points were required to do the work?

**Comment by ChrisM-S** [comment]
Moved to review complete as we've discussed this one.
