### ISSUE TITLE
IMAT: MySQL service not started

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5761]
As a user on IMAT I would like to be able to see my sample environment data. This data is stored in a MYSQL database, which should be running as a service but is not.

The issue first came to our attention through an email about the web dashboard being down on the morning of the 27/09, on further investigation it appears that the MySQL service had not been running since at least the 25/09. The service was unable to restart (see logs at [LogError.zip](https://github.com/ISISComputingGroup/IBEX/files/5288870/LogError.zip)). I believed that this may be due to some corrupt files and so tried various methods of getting the server back including setting `innodb_force_recovery = 1` and renaming the `ib_logfile`, this did not help matters and may have made them worse.

Eventually I backed up the `Var/mysql/data` directory and recreated an empty database so as to get them running over night. IMAT is now correctly logging blocks but the underlying cause is still unknown.

**Comment by Tom-Willemsen** [comment]
I believe IMAT may no longer have iocs in it's ioc database as configchecker is complaining about all iocs being "unknown" - probably need to rerun `build_ioc_startups`

**Comment by DominicOram** [comment]
@Tom-Willemsen, @FreddieAkeroyd and @JamesKingWork had a meeting to discuss how this problem was left for so long without anyone noticing. From that meeting:
* The [client](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Client-Release-Tests)/[server](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/server-release-tests) tests should be run on any major crash like https://github.com/ISISComputingGroup/IBEX/issues/5760. This would have caught the issue
* We discussed creating a specific page for server crashes and how to recover from them but decided that this was such a rare event that it was unlikely to help
* The ticket for the original issue has not yet gone through the project board, if it had a reviewer may have picked up the issue. We should fast track these major support issues and get them reviewed ASAP.
* The issue unfortunately occurred on a Friday and the nagios message was mixed with a lot of other messages. On a weekday we would have looked at nagios/the web dashboard the following morning and picked it up. Therefore from now on if you are  on call on a weekend you should look at the [nagios overview](https://varanus.nd.rl.ac.uk/nagios/) and the [web dashboard overview](http://dataweb.isis.rl.ac.uk/IbexDataweb/Overview/ibexOverview.html) in the morning to check the status of the instruments

**Comment by DominicOram** [comment]
Sent an email out to the group about the suggestions that came out of the meeting and added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/On-Call-Guidance

**Comment by kjwoodsISIS** [comment]
How many points?
