### ISSUE TITLE
Split Char Waveform: FTE still required when using mode 1

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5764]
As a developer I would like the `splitCharWaveform` asub function(https://github.com/ISISComputingGroup/EPICS-asubFunctions/blob/master/asubFunctionsApp/src/splitCharWaveform.c) to be easier to use. Currently it's behaviour switches based on the mode flag. If the mode is 1 then `INPE` is not used but it still throws an error if `FTE` is not `ULONG`. The function could also use some more documentation/tests.

## Acceptance Criteria
* `FTE` does not always have to be specified
* There are automated tests on the function
* There is some documentation in the wiki pointing to where to find out more about the function

**Comment by Scott-James-Hurley** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7310
