### ISSUE TITLE
Web dashboard: unneeded alarms

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5765]
As an EMU scientist I don't want to be alarmed by seeing alarms on values that I don't care about.

http://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=emu has 4 persistent alarms:
- Beam current (irrelevant for muons)
- Total uamps (irrelevant for muons)
- DAE simulation mode (complaining that it's undefined - can we PINI it or set UDF severity to none)
- N/A - the unused field on the dashboard, we should remove this in JSON_bourne if it is N/A

**Comment by DominicOram** [comment]
@Tom-Willemsen For beam current / total uamps they presumably don't want to see the values at all if they're not useful?

**Comment by DominicOram** [comment]
In a meeting with @John-Holt-Tessella, @mihai-stfc, @FreddieAkeroyd, @Tom-Willemsen and myself this morning we decided to remove all the 'fixed' parameters listed in the Run Information that tend to be duplicated in the variable dashboard parameters. i.e
* Beam Current
* Total Current
* Monitor Counts
* Current Period
* Number of Periods
* Shutter Status

The `variable` parameters should then be put at the top of the list
