### ISSUE TITLE
Alerts: set url and password on all instruments

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5772]
### Acceptance criteria:
- No nagios warnings for urls/passwords not being set

**Comment by Tom-Willemsen** [comment]
Ran the command noted here remotely on all instruments: https://github.com/ISISComputingGroup/IBEX/issues/5575#issuecomment-665580691 . Script now also saved on branch `set_alerts_url_and_password` of private scripts repo in case it is needed again in future (this doesn't need merging)

RIKENFE doesn't work with above script so consoled into `RUNCTRL` and used `dbpf` directly.

To review: check in nagios that there are no alerts about alert URL/PW being unset.

**Comment by DominicOram** [comment]
URL/PW set now, going to leave branch in case we need to do it again imminently
