### ISSUE TITLE
BeamNewsPhoneApps: Android app update

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5774]
Some members of the RF group in the accelerator division have asked about updating the beam news phone app on android and making it available again. Was last touched in 2015 by myself on an apprenticeship placement and a brief look suggests the SDK it uses is no longer available and requires updating to work on the latest versions of Android. I think most phones are running on Android versions 7-11 so would be nice to require 7 as a minimum. 

### Acceptance criteria
- Beam news phone app is updated to newest SDK
- Dependencies are updated alongside sdk update
- MCR news is still displayed on front page
- TS1 & TS2 currents still displayed on 
- Built SDK is published somewhere (whether it's google play store or somewhere ISIS-specific)

### To test
- Download Android Studio
- Import Gradle project into Android Studio 
- Set up an Android 7/8/9/10 emulator and test the project on it

**Comment by rerpha** [comment]
PR: https://github.com/ISISComputingGroup/BeamNewsPhoneApps/pull/1

**Comment by John-Holt-Tessella** [comment]
Could they not just suse the web page. I don't know that it is sensible to support a whole app.

**Comment by kjwoodsISIS** [comment]
This has the feel of a "point solution".  It addresses the needs of one particular group, but does not consider the wider aspects.  Furthermore, it appears to be an apprenticeship project that people have come to rely on.  Before we go any further, there are some questions we should ask ourselves:
1. What is the business problem that we are being asked to address?  Is it "I want MCR news on my phone" or is there more to it than that?  And why just the RF group?  Why not others too?
2. Who is actually responsible for maintaining & supporting the MCR news system? (is it Business Apps, Accelerator Controls or ourselves?)
3. Why support just Android?  Why not iOS?  (I appreciate that Android was probably a good choice for an apprenticeship project, but we are no longer talking about an apprenticeship project.)
4. What other mobile solutions are available (e.g. web pages, as suggested by John)?
5. How important is this work, relative to everything else?

**Comment by FreddieAkeroyd** [comment]
I though we decided in the past to provide beam news for mobiles via Slack to avoid having to support our own an App? Slack has the advantage over a web page as you can get alerted on a new message for example. The instrument scientists currently use Slack, but I'm looking at an MS Teams feed as that is the way things seem to be going at ISIS and most people may end up with Teams on their work mobile for one reason or another. Does the Android App provide any more features than MCR news and graphs? Who in the RF group have asked about it?

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - you say "work mobile".  Is STFC still using Windows Mobile? (I am assuming not ....).  MS Teams is available for Android & iOS.

**Comment by FreddieAkeroyd** [comment]
Indeed, STFC is no longer supplying windows phones

**Comment by kjwoodsISIS** [comment]
What was so high priority about this ticket (compared to all the other tickets that we have in our backlog) that we've gone ahead and implemented and then reviewed it?

**Comment by rerpha** [comment]
Sorry guys, i think this was probably the wrong thing to do, I was doing some personal development and decided to look at Kotlin + Gradle and thought I might try and update the app and convert it to Kotlin to see how straightforward it was as a learning opportunity, then thought I might push the code and ask if it's useful at all. The advantage over just looking at the MCR news webpage is notifications - although this is also offered by the slack/teams approach. It probably doesn't make any sense to support this app if the slack/teams approach is active

**Comment by FreddieAkeroyd** [comment]
Do the RF people who contacted you know about Slack/Teams options?

**Comment by DominicOram** [comment]
Putting this in impeded waiting a discussion with RF people. Which @rerpha is instigating

**Comment by rerpha** [comment]
Have now sent an email from the experimental controls address to the RF group. Moving to review

**Comment by DominicOram** [comment]
As discussed:
* Confirm with the RF group what the teams service will be capable of
* Make sure there is a ticket for the teams service
* Add note at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Decision-Log to say the app is depreciated in favour of teams/slack
* Mark the repo as archived

**Comment by rerpha** [comment]
Sent an email off to stuart to confirm requirements, will make any tickets if they request any additional features for the MCR news MS Teams channel. 
Have updated the decision log and created #5847 and archived the beam news phone apps repo.
