### ISSUE TITLE
Datastreaming: get filewriter writing NeXus files for ZOOM

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5777]
As a developer i would like the filewriter to write a file containing whatever is currently being pushed by the ICP (events) and that matches the filename of the ICP's outputted NeXus files on ZOOM. Currently due to the runInfo topics being individual for all instruments we can only do one topic at a time but this will be fixed by #5778 

### Acceptance criteria
- Filewriter is running on NDHSPARE62 in a docker script 
- Filewriter is outputting files to `C:\filewriter\output-files\`
- These files match the names of the files written out by the ICP 
- The files contain some form of event data even if the structure is incorrect.

**Comment by rerpha** [comment]
Note: https://github.com/ISISComputingGroup/isis-filewriter has been added to start the filewriter

**Comment by DominicOram** [comment]
Could you update https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Datastreaming#filewriting to show that it is now working and link it to our filewriter repo. Then make sure there are details on either the README or on the wiki on how to start and stop it, where files are being written, where the configuration lives, any common errors you might come across etc.

**Comment by DominicOram** [comment]
Great, documentation is better, thank you!
