### ISSUE TITLE
Datastreaming: get filewriter running for all instruments

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5778]
Currently the filewriter is only able to run for one instrument as the runInfo messages are pushed to per-instrument topics on kafka. to get it working for all instruments requires amalgamating all config messages into one topic (could be called `ALL_runInfo`)

### Acceptance criteria 
- Stream processor or similar has been written to aggregate all config messages from every instrument's `_runInfo` topic into `ALL_runInfo` so that it contains filewriter config messages from all instruments
- Filewriter config has been updated to point at `ALL_runInfo` as it's config topic and `ALL_writerStatus` as its status topic. 
- Filewriter is therefore writing files for all instruments.

**Comment by JamesKingWork** [comment]
I'm guessing this has a points of 0 as it is datastreaming?

**Comment by rerpha** [comment]
I will update the acceptance criteria as the stream processor did not work successfully in production (more info [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Datastreaming---File-writing#update---08102020)) and this will now be done as part of the script that fills in the missing data into the filewriter config.

**Comment by rerpha** [comment]
We are going to shelve this for now as some of the metadata isn't easy to set up in the file for all instruments. the main obstacle is that the histogram streams have to have their spectrum map IDs specified and this is different for each instrument.
