### ISSUE TITLE
genie_python: Push CI state to the repository

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5779]
As a developer of genie_python I would like to know if my changes successfully build pass all unit tests. The status of this can be seen at http://epics-jenkins.isis.rl.ac.uk/job/genie_python_pr_pipeline/ but it's not obvious where that is if you're not used to ISIS' processes.

## Acceptance Criteria
* The status of the genie_python PR build gets written to PR

**Comment by Tom-Willemsen** [comment]
done during g_p split
