### ISSUE TITLE
IOC tests: fix danfysik and jaws

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5780]
As a developer I would like the IOC tests which run in Jenkins to pass. Currently the jaws tests and danfysik tests are broken. Investigate why and fix (first issue is that we no longer allow writing to records with `.DISP` set, but there are also other problems with these tests).

### Acceptance criteria
- Danfysik tests run successfully
- Jaws tests run successfully

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen  - what is wrong with the tests?

**Comment by Tom-Willemsen** [comment]
They are broken in Jenkins and I said I would fix them at standup. I have updated the ticket with a clearer description.
