### ISSUE TITLE
Reflectometry: Park axes need movement in order

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5783]
On POLREF the polarising flipper and point detector can not just move to the park positions but need to move through a number of stage, e.g. level then move to position. This is not a feature that appear in IBEX but we can create a type of park position that does this.

### Acceptance Criteria

- When parking a component there is an order to the axis moves.
- Moves are implemented in config for POLREF point detector and polarising flipper

**Comment by ThomasLohnert** [comment]
Needs to work both ways, ie. if moving a component out of beam triggers sequence 
- park angle -> park slide -> park height 

then moving it back in should trigger sequence 
- un-park height -> un-park slide -> un-park angle

**Comment by John-Holt-Tessella** [comment]
Plan:

- Each axis has a sequence of out of beam positions. (None represents no change to axis)
- Each component has a sequence index and a direction (parking, unparking)
- On set in beam on component if not already parked then sequence is set to 1 and direction is set
- On set in beam to out on component if not already out then sequence is set to maximum (or maybe -1 and direction is set)
- Then get_sp returns the sp from the parking sequence and perform move works as normal
- On readback of position if all axes for the component are within tolerance of the sp then the parking number is increased and perform move is retriggered
- If there are no more positions axis is parked and sequence goes back to None.

**Comment by John-Holt-Tessella** [comment]
PR:

- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/332
- https://github.com/ISISComputingGroup/EPICS-refl/pull/23
