### ISSUE TITLE
All Instruments: deploy fix for time rollover

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5784]
As a scientist I would not like to periodically reboot my computer to resolve the 49.7 day rollover issue. The code has been fixed in #5717 but this needs to be deployed in shutdown.

The fix applies to epics base and requires ibex shutting down and a DLL updating. It should be possible to build a patch release and just deploy the DLL rather than a whole ibex. 

## acceptance criteria
* fix deployed on Instruments

#### ALF
- [x] Started
- [x] Completed

#### CRISP
- [x] Started
- [x] Completed

#### DETMON 
- [x] Started
- [x] Completed

#### EMMA
- [x] Started
- [x] Completed

#### EMU 
- [x] Started
- [x] Completed

#### ENGINX
- [x] Started
- [x] Completed

#### ENGINX_SETUP
- [x] Started
- [x] Completed

#### GEM
- [x] Started
- [x] Completed

#### HRPD
- [x] Started
- [x] Completed

#### IMAT
- [x] Started
- [x] Completed

#### INES
- [x] Started
- [x] Completed

#### IRIS 
- [x] Started
- [x] Completed

#### IRIS_SETUP
- [x] Started
- [x] Completed

#### LARMOR
- [x] Started
- [x] Completed

#### LET
- [x] Started
- [x] Completed

#### LOQ
- [x] Started
- [x] Completed

#### MAPS
- [x] Started
- [x] Completed

#### MARI - Note: also need fermi chopper logging fix
- [x] Started
- [x] Completed

#### MERLIN - Note: also need fermi chopper logging fix
- [x] Started
- [x] Completed

#### MUONFE
- [x] Started
- [x] Completed

#### NIMROD
- [x] Started
- [x] Completed

#### OSIRIS
- [x] Started
- [x] Completed

#### POLARIS
- [x] Started
- [x] Completed

#### POLREF
- [x] Started
- [x] Completed

#### RIKENFE
- [x] Started
- [x] Completed

#### SANDALS
- [x] Started
- [x] Completed

#### SELAB 
- [x] Started
- [x] Completed

#### SOFTMAT
- [x] Started
- [x] Completed

#### TOSCA
- [x] Started
- [x] Completed

#### ZOOM 
- [x] Started
- [x] Completed

#### INTER
- [x] Started
- [x] Completed

#### MUSR
- [x] Started
- [x] Completed

#### OFFSPEC
- [x] Started
- [x] Completed

#### SANS2D
- [x] Started
- [x] Completed

#### SURF
- [x] Started
- [x] Completed

#### SXD
- [x] Started
- [x] Completed

#### HIFI
- [x] Started
- [x] Completed

#### VESUVIO
- [x] Started
- [x] Completed

**Comment by Tom-Willemsen** [comment]
Need to write a custom deploy script to:
- Truncate databases
- Fix time rollover
- Runcontrol fix https://github.com/ISISComputingGroup/IBEX/issues/5803 on select instruments

And then run this script everywhere.

**Comment by Tom-Willemsen** [comment]
Deployment script to run is `\\isis\shares\ISIS_Experiment_Controls_Public\ibex_utils\installation_and_upgrade\patch_release.bat`

**Comment by RaiBishal** [comment]
Review Tips:
- Check that `C:\Instrument\Apps\epics\base\master\bin\windows-x64` contains `com.dll` from \\isis\inst$\Kits$\CompGroup\ICP\epics_dll. 
- Check MARI and MERLIN fermi chopper IOC has latest `.db` file

**Comment by DominicOram** [comment]
Confirmed by looking at:
* MARI
* ZOOM
* IMAT
* SANDALS
