### ISSUE TITLE
Scans: ctrl + c fails during scans script if scan is in a loop script keeps going

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5785]
Bug:

1. Run a scan in a loop
1. ctrl + c out of loop
1. next scan step in the loop runs. it shouldn't

### Acceptance Criteria

- script stops running
- System test must be written (probably squish)

**Comment by John-Holt-Tessella** [comment]
Could be that keyboard interupt is caught and not rethrown

**Comment by ThomasLohnert** [comment]
- [ ] https://github.com/ISISNeutronMuon/InstrumentScripts/pull/78
- [ ] https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/73
- [ ] https://github.com/ISISComputingGroup/ibex_utils/pull/94
