### ISSUE TITLE
Fix race condition in run control

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5786]
As an instrument scientist I would like run control to leave my instrument in the correct state on a begin - see #5771

As detailed in comment in #5771 this is due to separate STARTSEWAIT and ENDSEWAIT pvs that mean if both are triggered during a begin (and neither can process until begin is complete) then the order they were initially triggered in is not preserved leading to an incorrect final result. The order needs to be preserved, but only the final call is most important.  

## acceptance criteria

Changes in run control during a long begin command do not produce incorrect waiting states. 

Doing a pure DB fix (using a single PV so results are queued by RPRO) would allow a fix to be easily rolled out in shutdown.

**Comment by DominicOram** [comment]
If in before the release add LET to the list of instruments to release to.

**Comment by Tom-Willemsen** [comment]
I spent quite a bit of time trying to write a test for this by forcing the isisicp to begin very slowly (using the new `isisicp.begindelay` option in `isisicp.properties` - if it doesn't work for you you may need to re-run `create_icp_binaries.bat`) and then changing runcontrol states in various ways before/during/after the begin. I was unable to reproduce the race condition, either on my machine or on DEMO.

I have modified runcontrol such that it uses monitors (which should always get latest value, eventually) and waits for completion callbacks. Using a single PV would have required a lot of changes throughout runcontrol but also alerts and "general action" code.

PRs at:
- https://github.com/ISISComputingGroup/EPICS-RunControl/pull/12
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/565
- https://github.com/ISISComputingGroup/system_tests/pull/73

Note that since we were unable to reproduce the race locally, there is a task on the tasks board to test this on a real instrument in shutdown.

**Comment by FreddieAkeroyd** [comment]
I'm having another go at reproducing, I've looked at asyn and it seems to queue requests, so i'm not sure we are trying to fix the right issue

**Comment by FreddieAkeroyd** [comment]
I have investigated this some more and the problem is indeed sequencing due to their being two PVs (startSEWait/endSEWait) to initiate processing,  but it is not a lock issue in asyn. When I examined asyn I found it has a queueing mechanism, so a single call to either or both of startSEWait/endSEWait during a long begin will sequence correctly. The issue is caused by multiple calls to startSEWait/endSEWait  during a long begin (e.g. a value bounces in and out of range a few times during the begin). The first call to each are absorbed by the asyn queue and subsequently executed in the correct order when the begin has completed; however any additional calls find the DB record already busy (PACT=1) and so queue a DB reprocess (RPRO) – it is this record reprocessing that does not seem to have a guaranteed order when finally executed. I have updated the system test and the test now fails as expected with the original run control DB record logic. 

Though I mentioned a value bouncing around during the begin, there is another related mechanism that can also cause a failure. The begin DB record calls CS:RC:SYNC:SP to immediately push the sample environment state to the icp rather than wait for the next 1 second scan to do that. If for some reason this processing didn’t complete before begin record processing had started then it would requeue a RPRO of an incorrect value to execute after a begin had completed. By inserting a forced call to  CS:RC:SYNC:SP after a begin I can get the system test to fail too. In a normal loop of “out of range, begin, in range” I cannot get a failure, so if this mechanism is the cause then some additional factors/delays on LET must be in play to make it so. However it has the same root as the value bounce – unwanted/unsequenced record reprocessing. 

I ran the updated system test with the changes to add completion callbacks to runcontrol, but these changes do not resolve the problem.  

I believe the best solution is to remove the startSEWait/endSEWait PVs at the DAE end and use a single entry point, then there are no potential ordering issues with e.g. RPRO. To test the principle I have pushed a fix to  https://github.com/ISISComputingGroup/EPICS-isisdae/tree/update_rc that routes the existing startSEWait/endSEWait to a new SEWAIT PV via local CA links all on the DAE side – this passes the tests and requires no changes to run control DBs, however it would be neater to remove the startSEWait/endSEWait calls at the runcontrol end to just use the new SEWAIT PV in the ISISDAE db.

**Comment by John-Holt-Tessella** [comment]
I think the "neater solution" is probably worth aiming, if we don't remove the  potential for adding the race back in we probably will at some point. I have moved it back as rework; sorry @Tom-Willemsen

**Comment by FreddieAkeroyd** [comment]
## To Test

Individual system test can be run locally with
```
run_tests.bat -t test_genie_python_dae.TestDae.test_GIVEN_begin_in_progress_WHEN_runcontrol_changes_quickly_in_and_out_of_range_THEN_correct_state_is_eventually_used
```

**Comment by FreddieAkeroyd** [comment]
Given I have made changes probably best I don't review this now? Should @Tom-Willemsen review the changes or a third person?

**Comment by John-Holt-Tessella** [comment]
I think either is fine, although Tom may find it hard to merge the pull requests
