### ISSUE TITLE
Server: Automatic Database Trimming

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5787]
As an IBEX developer or systems maintainer, I can see that about 14 points were spent recently manually trimming space and copying database files.  I would like to keep this time for development and other more fruitful maintenance.

**Acceptance Criteria**
1. The maximum IBEX database size is controlled by a PV.  When the PV in GB is set lower than the size of the database, the database selects and removes the oldest records to ensure it does not exceed the maximum figure.
2. The process is completed with no significant increase in used disk space (if control is applied in emergency, it is important that it does not become part of the problem itself).
3. records should be removed at the end of a run or on an hourly basis.

**Notes**
1. Choice of records for removal may be something other than first in last out (possibly even controlled by another PV), for example specifying.

**Comment by kjwoodsISIS** [comment]
The acceptance criteria are defining the solution - that's wrong!  The acceptance criteria should define the outcome - the what, not the how.

**Comment by FreddieAkeroyd** [comment]
I think deleting rows does not reclaim the space until an `optimize tables` command is run, but that makes a new copy of the table and then drops the previous table, so temporarily uses the (old+new) space and may take a while. Also during the optimise it may not be able to take any new data, so logging would be disrupted, but i don;t knwo for sure - it may be able to add stuff to the transaction log that can then be played in the new table.

**Comment by DominicOram** [comment]
I believe this superseded by https://github.com/ISISComputingGroup/IBEX/issues/5818
