### ISSUE TITLE
Server: Solution for large database growth

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5789]
### Acceptance Criteria

- find solution for database growth

**Comment by davidkeymer** [comment]
Could the growth of log files also be considered during the meeting?  These also fill up the disk.

**Comment by KathrynBaker** [comment]
It's worth considering the two things separately - whilst they use similar mechanisms the solutions are likely to be quite different. We already have a page about what we plan to do with things (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Data-Generation-and-Storage) , so focussing on acting on these decisions for just one technology at a time would be wiser than increasing the scope

**Comment by JamesKingWork** [comment]
Have we got points for this?

**Comment by DominicOram** [comment]
Pointing based on a meeting of ~5 people for an hour, then a write up and review =1d = 3pt

**Comment by DominicOram** [comment]
Meeting scheduled for tomorrow

**Comment by DominicOram** [comment]
Decision added to decision log (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Decision-Log) Tickets created as above
