### ISSUE TITLE
Scans: Allow working directory to be set

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5794]
As an instrument scientist I want to be able to set a working directory for my scripts and log files so that different experiments can be separated and organised. 

### Acceptance Criteria

- Function exists which can be added to init which will prompt the user to set the directory whenever a python session is started in the GUI (and possibly in the console) [see flag which is set]
- Scan library writes scan results into the genie_python working directory
- Last scan should read entry from this directory

### Notes

Genie already has `g.set_user_script_dir` this should be used.

**Comment by John-Holt-Tessella** [comment]
Confirmed that scripts and results should normally be written to the same directory. Maker it the same for now and we will capture the cases when this is not true.

**Comment by John-Holt-Tessella** [comment]
PR;

- https://github.com/ISISComputingGroup/genie_python/pull/302
- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/85

**Comment by John-Holt-Tessella** [comment]
User changed requirements after demo to:

1. Just allow me to set the dir I do not need a prompt, then it is more like the rest of genie

PR:

https://github.com/ISISComputingGroup/genie_python/pull/308

**Comment by kjwoodsISIS** [comment]
A question: what happens if the directory in question does not exist?
For example, if I try to set a directory and it does not exist, should I get some kind of error message when I set the directory or when I actually attempt to write to it?

**Comment by John-Holt-Tessella** [comment]
See #5867 for what does and should happen in the scans library.
In the above pull request if you ask to change the script directory to one which does not exist it will initially try and create it and if it can not then it will throw and exception which will usually be printed out for the user saying it can not create the directory. However if the user chooses genie_python to allow it to throw exceptions then an exception is thrown into the user code.

**Comment by kjwoodsISIS** [comment]
OK.  That's fine.  I understand.  Thanks.
