### ISSUE TITLE
Scans: Robust fitting

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5795]
Bug: Not sure how to reproduce but if the fit function fails for any reason either while generating points or fitting then the scan terminates early, it shouldn't

### Acceptance Criteria

- Fit functions which cause normal exceptions (i.e. not keyboard interrupt or out of memory) do not stop scan

**Comment by ThomasLohnert** [comment]
POLREF reported all fit variants other than Gaussian currently being broken. Check whether this goes away with better exception handling as per this ticket, create a new ticket if not.

**Comment by John-Holt-Tessella** [comment]
PR

- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/79
