### ISSUE TITLE
Flipper: Update flipper parameters

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5796]
The flipper on POLREF is slightly different to LET update the following parameters so it will work:

### Acceptance Criteria

- adjust min/max amplitude. currently at -3/3, Flipper on POLREF usually operating at 3.5. Currently the only V1 flipper in use at ISIS, maybe we can just update the hardcoded values in `.db`
- Increase precision on Amp, Constant, Compensation and DT values 5dp

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-Mezflipr/pull/7
