### ISSUE TITLE
REFL: Make THETA more important

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5797]
AS a POLREF instrument scientist I want the theta variable to be easier to find on the OPI, so that I can instantly see where it is (it is the most important parameter.

### Acceptance Criteria

- Important parameters are at the top on the right, not in the middle
- The label Theta is a different colour (Blue) and bigger if possible

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1207
