### ISSUE TITLE
REFL: OPI gets slow and crashes

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5798]
There seems to be a resource leak or issue with the refl opi. The longer it is used the slower it gets and it occasionally crashes. The two may or may not be related. Try to reproduce and fix it.

### Accetpance Criteria

- cause is found 
- then discuss how to fix
- either create new ticket or fix

### Notes

- possible causes are:
    - lots of pv changes 
    - slow responses 
    - resource leak
    - parameters not connected to anything
    - rules that break (we occasionally see error in console claiming a rule didn't get a value)

**Comment by ThomasLohnert** [comment]
Symptoms of OPI crash were all PVs showing up as disconnected although the server was running fine (`caget` etc. working fine). One time this happened I noticed the reflectometry server log being flooded with these error messages:

```
Error (521,521) - unexpected problem with client's input - forcing disconnect
CAS Request: [user] on [host name]: cmd=2 cid=178 typ=20 cnt=1 psz=0 avail=1617b
CAS: bad resource id in "c:\instrument\apps\epics\support\pcas\master\src\pcas\generic\casstrmclient.cc" at line 2278
filename="[epics]\support\pcas\master\src\pcas\generic\st\casstreamos.cc" line number=478
```

**Comment by John-Holt-Tessella** [comment]
Also some error in opi log (not at time of crash but might be worth looking into)

```
2020-10-07 10:05:31 ERROR: Error in Border if not at setpoint on Grouping Container.
org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException: PV IN:POLREF:REFL_01:PARAM:THETA:CHANGING has no value. (rule#2)
```

```
2020-10-07 10:05:31 ERROR: Error in Border if not at setpoint on Grouping Container.
org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException: PV IN:POLREF:REFL_01:PARAM:S2VC:RBV:AT_SP has no value. (rule#3)

```

**Comment by John-Holt-Tessella** [comment]
Not a crash but a total pv disconnect, could no longer set manager mode from within the gui:

![image](https://user-images.githubusercontent.com/7570055/95609375-7fa64380-0a56-11eb-94ea-cecb93264974.png)

**Comment by ThomasLohnert** [comment]
POLREF said the performance has improved with the machine upgrade and they are ok for now. They will keep an eye on the performance over the course of next cycle and then we will reconsider priority depending on how it holds up.

**Comment by ThomasLohnert** [comment]
Had a thought what the possible cause might be:
The OPI shows an error log of the refl IOC which is linked to a (10000 char) PV which contains the content. This gets cleared on move, however we have seen some twitching axes on POLREF which gets interpreted by the server as a move outside of the reflectometry server which causes an error to get logged causing the log to fill up, meaning on every twitch, potentially large chunks of data are being fetched. I have not actually checked how this impacts performance (I'm not sure how you'd go about profiling OPI performance) so it's just a hunch at this point, but I think this may be a good place to start looking at when picking up this ticket.

**Comment by John-Holt-Tessella** [comment]
Talking with POLEF it is still slow but now just at the point where you switch into (and possibly outof) the OPI.

There is a definite delay between being in the script window and then clicking on a input box. Once a single box is clicked it is then quick to click on the next box. 

Maybe it is a layers thing we have tabs with linking containers (instrument important parameters) in that have linking containers (parameter) in.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1216

**Comment by ThomasLohnert** [comment]
Added PR for upgrade script:
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/51

Did not change the folder structure for tabs as discussed: this has implications for paths in opi files / scripts further complicated by the fact that a script on the linking container needs a path relative to the linked opi, not the source opi of the linking container  which leads to inconsistencies and probably more confusion than if it's just all in one folder. We decided this is not worth worrying about now
