### ISSUE TITLE
REFL: Check height and height2

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5799]
Check the labelling of height and height2 on the opi (including inter, surf) and in the script.

### Acceptance Criteria

- Height and height2 are the right way round

**Comment by aaron-long** [comment]
- Checked the assigned blocks, parameters and .config settings for INTER, POLREF, SURF, and CRISP.
- SURF and CRISP only have a single height (x-axis) translation. Updated their wiki entries to clarify this ([CRISP](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-CRISP), [SURF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-SURF).
- Updated [POLREF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-POLREF) Blocks subsection to correctly list the nature of Height, Height2.
