### ISSUE TITLE
Alerts: username and password not being reapplied correctly from autosave [Timebox: 2 days]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5803]
As a scientist I would like alerts to work. As a developer I do not want to have to keep manually setting the username and password for alerts onto all the instruments.

The alerts mechanism depends on a URL and password being set in a couple of PVs. These PVs are under autosave, but the autosave values are not getting reapplied correctly, meaning that the alerts mechanism breaks every time the run control ioc is restarted.

### Acceptance criteria
- URL and password are not lost on config change

### Notes
- Consider whether autosave is the best mechanism for this, or whether we can pick these up as macros from somewhere like `globals.txt`.
- The PVs are in the `*.req` file
- The PVs do appear in the autosave file:
```
IN:LET:CS:AC:ALERTS:URL:SP.VAL @array@ { <url as ints representing ascii characters> }
IN:LET:CS:AC:ALERTS:PW:SP.VAL <the password>
```
- Autosave thinks it can't open the autosave file on ioc boot, even though the file is present:
```
[2020-10-08 08:49:12] sevr=info reboot_restore: Found filename 'RUNCTRL_01_info_settings.sav' in restoreFileList.
[2020-10-08 08:49:12] sevr=info *** restoring from 'C:/Instrument/Var/autosave/RUNCTRL_01/RUNCTRL_01_info_settings.sav' at initHookState 6 (before record/device init) ***
[2020-10-08 08:49:12] sevr=info save_restore: Can't open file 'C:/Instrument/Var/autosave/RUNCTRL_01/RUNCTRL_01_info_settings.sav'.
```

**Comment by KathrynBaker** [comment]
Timebox: if not able to fix autosave in the time, change to macros in globals.txt to resolve the issue

**Comment by FreddieAkeroyd** [comment]
It is a waveform, so macros may not work - would need to see if EPICS 7 json const links would allow setting a longer name. But prefer investigating and fixing autosave.

**Comment by FreddieAkeroyd** [comment]
Error comes from
```
	if ((inp_fd = fopen(file, "r")) == NULL) {
		errlogSevPrintf(errlogInfo, "save_restore: Can't open file '%s'.\n", file);
		return(0);
	}
```

**Comment by FreddieAkeroyd** [comment]
I wonder if there is an issue with the autosave directory being `RUNCTRL_01` and the IOC one being `RUNCTRL` - it may be renaming makes it all go away?

**Comment by FreddieAkeroyd** [comment]
Note that the next two loads worked OK, haven't looked further 
```
[2020-10-08 09:10:33] sevr=info reboot_restore: entry for file 'RUNCTRL_01_info_settings.sav'
[2020-10-08 09:10:33] sevr=info reboot_restore: Found filename 'RUNCTRL_01_info_settings.sav' in restoreFileList.
[2020-10-08 09:10:33] sevr=info *** restoring from 'C:/Instrument/Var/autosave/RUNCTRL_01/RUNCTRL_01_info_settings.sav' at initHookState 6 (before record/device init) ***
[2020-10-08 09:10:33] dbFindRecord for 'IN:LET:CS:SB:ROT:RC:SOI.VAL' failed
[2020-10-08 09:10:33] dbFindRecord for 'IN:LET:CS:SB:ROT:RC:ENABLE.VAL' failed
[2020-10-08 09:10:33] sevr=info reboot_restore: done with file 'RUNCTRL_01_info_settings.sav'
```

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd If you fix this could you make sure there is a test

**Comment by Tom-Willemsen** [comment]
> ~@FreddieAkeroyd If you fix this could you make sure there is a test~ Nevermind we don't autosave in the test framework so you won't be able to

I think if you use procserv launcher and restart mid-test you should be able to test autosave. @JamesKingWork recently did this with kepcos I believe.

**Comment by JamesKingWork** [comment]
Yeah this code forces autosave to save and then restarts the ioc which picks it up:
```
self._ioc.telnet.write("manual_save(\"KEPCO_01_info_settings.req\")\n")
self._ioc.start_ioc()
```
http://htmlpreview.github.io/?https://github.com/epics-modules/autosave/blob/R5-7-1/documentation/autoSaveRestore.html

**Comment by FreddieAkeroyd** [comment]
It was working on sandals until 29th September then stopped. I think there is something run control IOC specific that is causing problems, and not every time, but after it has gone wrong once you have lost the data. One thing about the runcontrol IOC is that when it restarts often many of the PVs it tries to restore are no longer present (because you have changed config) - it may thus get a load of timeouts and maybe this leads to some race condition. If there was a general autosave issue we'd have had motors everywhere losing settings etc.

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella  @Tom-Willemsen @DominicOram  OK, I think the real problem is the blockserver is deleting the autosave files via the `clear_autosave_files` function called from ` create_runcontrol_pvs(self, clear_autosave, time_between_tries=2)` 

Anybody know the history of why we are doing this?

**Comment by John-Holt-Tessella** [comment]
OK that makes sense. I guess the config contains the values which would get overridden by autosave. Looking at the code it seems to have been in there for a while original call `create_runcontrol_pvs` (run_control_manager ln 178) written by Matt in 2016. It may be older than that even.

**Comment by John-Holt-Tessella** [comment]
As you say can we be more selective username and password in the normal autosave and run control settings in info_positions equivalent (like motors)?

**Comment by FreddieAkeroyd** [comment]
Autosave applies values by dbaccess, and I thought it applied them before channel access had started, so I would have thought that applying them from the blockserver would have overwritten autosave. Autosave needs to have applied its values by the time PINI runs and that is before channel access is started, so i'm not sure of the blockserver reasoning - maybe it was assumed there was a problem?

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella using `info_positions`  is a good idea, i'd been thinking we would have needed to create a separate autosave set but that is one we have already and could use. We would just need to use "autosaveFields_pass0" rather than "autosaveFields"  - i don't think using pass0 matters as there is no device support, but we could test that.

**Comment by FreddieAkeroyd** [comment]
Both run control and sms alerts use gencontrol.db as a basis, we would want to remove runcontrol but not alerts as they are not currently in the config. So we would need to make the  autosaveFields v autosaveFields_pass0 choice a macro if we use that route. But maybe we first need to conform we really do need to remove autosave files?

**Comment by DominicOram** [comment]
In meeting with @FreddieAkeroyd, @Tom-Willemsen, @John-Holt-Tessella and myself. Decided the following for this ticket:
* Remove clear autosave
Add automated tests for:
* Confirm passwords and runcontrol settings come back when runcontrol IOC restarted
* Confirm that changing the limits and reloading the current config puts it back to the config runcontrol limits and password/alert levels remain the same

**Comment by FreddieAkeroyd** [comment]
Taking myself off ticket following initial investigation and confirming route forward

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/325
- https://github.com/ISISComputingGroup/system_tests/pull/69
