### ISSUE TITLE
Handover: Reflectometry Training

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5806]
As a developer I would like to better understand how Reflectometry is implemented in IBEX, so that I am well-positioned to participate in its future support and development.

#### Acceptance Criteria

1. A nominated ISIS developer is introduced to the Reflectometry IOC through one or more briefing sessions.
1. Server starts quickly (see safe not quick prs below)

#### Notes
1. @ThomasLohnert & @aaron-long  are already familiar with the Reflectometry code.  The purpose of this ticket is ensure that at least one more ISIS developer is familiar with the Reflectometry code in IBEX.
1. There is a wealth of [reflectometry documentation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometers) available as a starting point.
1. Completion deadline: 30th November 2020.
1. The briefing constitutes the review of the ticket.

**Comment by KathrynBaker** [comment]
This needs to be followed up with an actual reflectometry ticket

**Comment by KathrynBaker** [comment]
Publicise the briefing sessions so that people can join if they have the opportunity

**Comment by DominicOram** [comment]
As discussed between myself, @ThomasLohnert, @RaiBishal, @John-Holt-Tessella both Bish and myself will take responsibility for this.

**Comment by John-Holt-Tessella** [comment]
Path:

- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-IOC#design-details 
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Beamline-Object
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Geometry-Components
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Composite-Driving-Layer
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Configuration#footprint-calculator

**Comment by John-Holt-Tessella** [comment]
PR;

- https://github.com/ISISComputingGroup/EPICS-refl/pull/19
- https://github.com/ISISComputingGroup/genie_python/pull/297
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/327

**Comment by John-Holt-Tessella** [comment]
This took much longer than estimated, both hand over time which was 5 of us for 3 hours or so and prep time so increased it to 8. I am unsure whether that is fair or whether it should really be 13.
