### ISSUE TITLE
Handover: Cryogenics Training

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5807]
As a developer I would like to better understand how support for Cryogenics devices is implemented in IBEX, so that I am well-positioned to take on their future support and development.

#### Acceptance Criteria
1. A set of briefing slides describing the support for Cryogenics devices in IBEX is created and stored in the [Cryogenics](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FCryogenics&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) folder on the ICPDiscussions Sharepoint site.
   * there is already documentation relating to Cryogenics devices in the IBEX developer wiki
   * there is already existing code-chat material
   * it is sufficient to re-fresh the existing material - no need to create a lot of new material
1. One or more ISIS developers are briefed on the support for Cryogenics devices in IBEX (using the above slides).
   * this may take the form of a 1-1 briefing or a code-chat
1. A nominated individual from the Experiment Controls team is introduced to the Cryogenics team, so that they have a point-of-contact.

#### Notes
1. There is existing [cryogenics documentation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Cryogenics) available in the [IBEX Developer's Manual](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki).
1. Completion deadline: 31st January 2021.
1. The briefing (or code-chat) constitutes the review of the ticket.

**Comment by Tom-Willemsen** [comment]
Code chat happened; slides are available at https://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/GUI_Chat_Slides/Cryogenics_code_chat.pptx
