### ISSUE TITLE
Handover: IBEX Client Build System

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5808]
As a developer I would like to better understand the build system for the IBEX client, so that I am well-positioned to take on its future support and development.  After training developers should be able to maintain the current IBEX build system and be able perform dependency updates, so that the IBEX Client continues to build successfully as new versions of Java, Eclipse and CS-Studio become available.

#### Acceptance Criteria
1. Identify any IBEX developers not already familiar with the IBEX Client build system.
1. Introduce developers to IBEX Client build system
   * this may take the form of a 1-1 briefing or a code-chat

#### Notes
1. There is existing [building the IBEX client documentation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-the-GUI) available in the [IBEX Developer's Manual](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki).
1. Completion deadline: 30th November 2020.
1. The briefing (or code-chat) constitutes the review of the ticket.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen and @RaiBishal have previously collaborated on build system dependency updates (see #5152, #5584).

**Comment by Tom-Willemsen** [comment]
Code chat happened.

**Comment by KathrynBaker** [comment]
It did indeed
