### ISSUE TITLE
System tests: Failure to get current config name

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5809]
As an IBEX user, I would like to be sure I can correctly load configs.

Acceptance criteria:

- [ ] Cause of failed tests ascertained
- [ ] Either:
    - Cause fixed
    - A ticket has been spun out to fix it
    - We have decided that it is ok and tests are changed accordingly
- [ ] Systems tests when run together on the build server do not fail to retrieve the value of GET_CURR_CONFIG_DETAILS

**Comment by JamesKingWork** [comment]
The issue was first seen when `test_start_stop_ioc_through_proc_control.TestProcControl.test_WHEN_start_iocs_THEN_iocs_started_WHEN_stop_iocs_THEN_iocs_stopped` was added and failed in it's setup on the Jenkins System_Tests. The test failure occurs when trying `load_config_if_not_already_loaded("empty_for_system_tests")` and the tests try to get the pv "CS:BLOCKSERVER:GET_CURR_CONFIG_DETAILS" which causes an UnableToConnectToPvException. This has a timeout of 200 seconds and at each second this failure occurs. Since then 5 other tests have now started failling for the same reason after 4 other (different) tests from another suite were added.

**Comment by JamesKingWork** [comment]
The tests only seem to fail if you run the whole test suite, though strangely the ordering in which the test cases are run does not seem to matter. It is reproducible on both reno and spare70.

**Comment by JamesKingWork** [comment]
Running each file of tests individually and restarting the ibex server each time means that the tests do not fail

**Comment by JamesKingWork** [comment]
However, if you run all the tests separately with `python run_tests.py -t test_name` they also pass

**Comment by JamesKingWork** [comment]
Even when you cannot get the current config details the procserv is up and the blockserver is still running around it's processing loop printing "Blockserver running" each time

**Comment by JamesKingWork** [comment]
Restarting the blockserver alone does not fix the issue suggesting it is something the blockserver relies on being in a state that is causing the issue. We have tried restarting PSCTRL and RUNCTRL_01 and I will try out some more options. We are also considering that it may be due to the 50-day rollover issue, so are restarting ndwreno to test this.

**Comment by JamesKingWork** [comment]
NDWRENO has been restarted and the tests still show the same issue

**Comment by JamesKingWork** [comment]
There doesn't seem to be an orphaned git lock for the config as no index.lock file appears in the config/ND.../.git

**Comment by JamesKingWork** [comment]
Another clue: it seems that when the tests stop running the blockserver starts working even though I have removed the section that does test cleanup and stops the ibex server

**Comment by JamesKingWork** [comment]
After testing with @John-Holt-Tessella we believe the error was highlighted after calling g.set_instrument(None) in each test, which adds another monitor on the block names which exceeded some sort of limit (seems to be about 50 but between 10 and 100 for sure). The error could be in our use of CaChannel or the limit imposed may be incorrect. The solution will be considered in https://github.com/ISISComputingGroup/IBEX/issues/5830. The "fix" here is to not add the monitor if the pv has not changed.

PR: https://github.com/ISISComputingGroup/genie_python/pull/291

**Comment by aaron-long** [comment]
A number of test builds have run since the addition of this code. I've not observed the config name fetch failure and so I'm confident this code has sensibly fixed this issue at hand.
