### ISSUE TITLE
Reflectometry: InBeam parameter does not move if offset not in mode

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5814]
As a reflectometry scientist, I would like to be able to move  any `InBeamParameter`. We have observed a bug on POLREF, where setting a component to "IN" and then pressing move did not move the underlying motors if the offset parameter on the parking axis was not in the mode. Component had to be parked by explicitly moving the offset parameter as well as the  `InBeamParameter`.

#### Acceptance Criteria
- Source of bug is understood and fixed
- If moving to parked position then that is indicated in the logging (and if we shouldn't move because we are at the position this is indicated in the logging) [I have made it indicate when an axis is not moved because it is at its setpoint]
- Following cases should work for components with 1 or 2 axes:

1. Autosave all parameters except in beam and restart server with component out of beam
    1. Moving in with move all and move single causes correct move to autosaved position
2. Autosave in beam parameter
    1. move command should not be sent to motors
    2. move all and move single should work
    3. if restart in sequence then should restart correctly (i.e. does not claim it is in the middle of parking sequence on 2nd restart)
3. Autosave no pramaters when restart
    1. Move in should move to 0 for all parameters
    2. Warning should be issued
4. If  in beam but one axis is in out of beam position make sure moves corrrectly

#### Notes:
- I have not yet managed to recreate this bug on my development machine.

**Comment by ThomasLohnert** [comment]
Did not see this behaviour on development machine, we should put the latest version of the code on POLREF in the shutdown and see if it just goes away, and investigate the specific circumstances on the instrument if it does not.

**Comment by John-Holt-Tessella** [comment]
Reported as:

>the anlayser 1 in button the activation tab no longer seesm to work to drive the analsysr in. (we were in PNR mode and aligining it for PA mode). On startup when a1 was out it looks like the offset is being set to -242 so IN then doesn't work. This value should be set to 0 and should be autosaved to that value (check if there is a problem in this logic).

Maybe on restart if the a1 is out this is setting the wrong offset if there is no auto save (look and see)

**Comment by ThomasLohnert** [comment]
Try to reproduce this on POLREF:
1. Turn off autosave on offset
1. move component out of beam
1. restart server

If it initialises to the wrong SP, investigate cause, otherwise close this issue.

**Comment by John-Holt-Tessella** [comment]
Also see #5095

**Comment by John-Holt-Tessella** [comment]
We think the action to fix this is for init to return zero if it is in its park position and warn the user if it is not autosaved parameter.

**Comment by John-Holt-Tessella** [comment]
Pull request:

- https://github.com/ISISComputingGroup/EPICS-refl/pull/26
