### ISSUE TITLE
Datastreaming: Make filewriter write a file with sample env, events and histogram

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5824]
This is a sub-ticket of #5778 

### Acceptance criteria: 
- Filewriter is configured to write a file from any instrument that contains: 
  - Sample environment (f142)
  - Histogram data (hs00)
  - Events (ev42) 

### Notes: 
Filewriter is running on NDHSPARE62 currently in a docker-compose instance. See [isis-filewriter](https://github.com/ISISComputingGroup/isis-filewriter) 
Will need to be configured to point to `ALL_runInfo` topic for configuration updates, and `ALL_writerStatus` for status messages

**Comment by DominicOram** [comment]
Looks good, thanks
