### ISSUE TITLE
ARGUS: Ensure that we can talk to the Cryogenic LM500

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5832]
As a scientist I want to get replies from my LM500 so that I don't run out of Helium

### Acceptance Criteria
- The LM500 is talking

### Notes
1. Whilst this is LabVIEW and a SECI device, a lot of the basic troubleshooting is standard enough 
1.  There are just no replies visible on the device (IS had checked and the orange light is not flashing), so there is nothing much more we can do remotely
2. this should be a simple stream device, but we are unsure if the existing seci control works

**Comment by KathrynBaker** [comment]
I'm going to remove this from the tasks board, hopefully the requirements will be covered by the migration. @JamesKingWork please check the lists for ARGUS/CHRONUS for this device, and consider whether or not this can be closed.

**Comment by JamesKingWork** [comment]
This is required for ARGUS and CHRONUS to control the Janis cryostats alongside a lakeshore 332 and itc503

**Comment by KathrynBaker** [comment]
This ought to be checked as to whether it is currently an issue or not...

**Comment by KathrynBaker** [comment]
No longer required
