### ISSUE TITLE
Add rotating bench vacuum system

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#584]
As a user I do not want to break the rotating bench vacuum system

== Acceptance Criteria ==
1. If the rotating bench vacuum system is operating, the maximum rotation angle must have a different upper limit from the default.
2. The rotating bench vacuum system appears on the synoptic view.

== Notes ==
1. This was part of Rob's original spec for the rotating bench IOC but was omitted because the vacuum system does not exist yet
1. If it is a TPG300, we may have to use a pressure threshold, because the IOC has no On/Off PV

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 585.  Created by sjb99183 on 2014-12-23T11:40:41, last modified: 2015-04-30T15:17:24_

**Comment by kjwoodsISIS** [comment]
_Trac comment by skn09965 on 2015-03-06 14:15:11:_

Postpone until there is a vacuum system on the LARMOR rotating bench.

**Comment by KathrynBaker** [comment]
Superseded by Beckhoff work
