### ISSUE TITLE
ILM200: intermittent zero readings from device

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5840]
As a user of ILM200 devices, I am confused that the cryogen levels intermittently report "0" before flicking back to a sensible value.

# Acceptance criteria:
- Cryogen levels to not flicker to zero and back 

# Notes
- Unclear whether this is a comms error or whether the ILM really sends back zero.
- If the ILM really sends back zero, we could keep a buffer of last N values and select the max to filter out zeros.

**Comment by FreddieAkeroyd** [comment]
If not comms error, maybe retry read if it returns 0?

**Comment by Tom-Willemsen** [comment]
Investigation:
- The invalid readings only ever seem to appear on channel 1.
- This device scans using `sseq` records so the command order is predictable, reading channel 1's level always comes immediately after a read of the general device status.
- When the device reads a "zero" the logs are complaining about getting the response to the general status command, rather than the level command
- Therefore I think we may be timing out of the status read too quickly, and then getting it's response in the channel read instead.

I would like to try against the hardware setting higher hardware timeouts, e.g.
```
ReplyTimeout = 5000;
ReadTimeout = 5000;
WriteTimeout = 1000;
LockTimeout = 30000;
```

It may also be worth trying to add an explicit read of a response in the general status read. I am not certain exactly how the device replies to `@1C3` but the manuals imply it should respond with `C`.

```
getStatus {
    out "@\$1C3";  # Keep the system in remote unlocked mode
    in "C";
    out "@\$1X";
    in "X%(\$2.A)1d%(\$2.B)1d%(\$2.C)1dS%(\$2.D)2x%(\$2.E)2x%(\$2.F)2xR%(\$2.G)2d";
}
```

I'll contact Steve & Koji to ask whether we can have some time to test this next time they have an ILM available, and put this into impeded for the moment.

**Comment by Tom-Willemsen** [comment]
Fix mentioned above tested & working against real ILM on EMU. @JamesKingWork witnessed the test.
