### ISSUE TITLE
Background plot: breaks after long-term use

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5841]
As a user or instrument scientist on EMU, I would like the background plot to keep working reliably.

"About once per day" I run into the following issues (not necessarily all at the same time):
- The graph stops updating
- The axes get overwritten with values which are not sensible, even if the lines keeps updating correctly. For example the time axis gets replaced with incrementing integers.

Force-refreshing the plot (browser) solves both of the above issues - suggesting that this issue is in the client (webpage) side.

# Acceptance criteria
- Plots keep working reliably even after a long period of use

# Notes
- If we cannot find the issue in a reasonable timeframe, we could add code to the opi and/or webpage to force the page to refresh every 5 minutes.

**Comment by Tom-Willemsen** [comment]
Do the horrible fix.

**Comment by rerpha** [comment]
PR: 
- https://github.com/ISISComputingGroup/genie_python/pull/296
