### ISSUE TITLE
MS Teams: MCR news service

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5847]
Following on from #5774 

As a developer/scientist/user I would like to have a Microsoft Teams workplace that posts the MCR news updates onto a read-only (if possible) channel that is easily available to join. This would be a successor to the slack channel that already exists for this purpose. 

In the future we could have multiple channels for different purposes, so things like #1997 or #3811 could be solved using the same service

### Acceptance criteria
1. Teams channel is set up for this purpose
1. (optionally if possible) channel is made read-only for anyone except the bot, and users are NOT notified when someone else joins the channel
1. Bot or plugin is set up to post MCR news updates
1. Link is published on ISIS intranet which is easy to find for users and staff

**Comment by DominicOram** [comment]
A test channel has been made for this, see note in the announce channel. @FreddieAkeroyd is going to confirm whether it's ready for a full release

**Comment by FreddieAkeroyd** [comment]
The MCR news bit and beam on/off works fine, it doesn't do the full slack stuff yet (alerts, journal, beam graphs). I've got some alerts going into "test" now, i think i've got a journal parser that will push into teams, i'm seeing if there is a way i don't have to manually create a load of channels and add incoming webhook connectors by hand, but it might come to that. I didn't want to publish to scientists until it has all the channels. I need to figure out how to do a beam graph, I tried pinning to a tab but it didn't seem to refresh. I've a few other things to try.

**Comment by ChrisM-S** [comment]
I did wonder if the plots could be done through grafana on an Android/IOS style client app - which might be more plot friendly than the social media style apps?  Might still be hard to get as swish as the original Win phone app though...

**Comment by FreddieAkeroyd** [comment]
Document circulated to group, a few instrument scientists testing

**Comment by FreddieAkeroyd** [comment]
I don't know if grafana would work "in app", it may need to spawn an external browser

**Comment by Tom-Willemsen** [comment]
I couldn't find the developer documentation for this after looking in the wikis (various combinations of keywords - "teams mcr", "microsoft teams", "mcr news" etc), on sharepoint, and in our MS teams instance. 

Please could we make it easier to find, either by putting it on the wiki or linking to it from the wiki with easily found keywords.

**Comment by FreddieAkeroyd** [comment]
Details at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MCR-News-in-Teams
