### ISSUE TITLE
Allow seeing matplotlib window from IDAaaS machine

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5849]
As a reflectometry user, I would like to be able to view plots in matplotlib from a read-only client on the IDAaaS cloud.

#### Acceptance Criteria
- Matplotlib OPI can display plots on a remote instruments

**Comment by Tom-Willemsen** [comment]
Assuming there are no firewall issues, the web browser OPI widget would just need pointing at the remote instrument's hostname as opposed to localhost.

Is it acceptable that a remote instrument can modify (e.g. resize, zoom) the graphs? It is the same graph for all clients.

**Comment by ThomasLohnert** [comment]
I have told POLREF that users can already see the plots by navigating to the right address in the browser (subject to the same issues you mentioned). They are happy with this for the moment.

It would be easy enough to add a "remote host" macro to the OPI, so you don't have to look at it in a separate window, but this also makes it easier for IBEX users to stumble upon and mess with the plots from any instrument. Does anyone have strong feelings about this?

I suppose long term we should aim for creating a separate plot for each client somehow? I am unsure exactly how hard this would be to do.

**Comment by John-Holt-Tessella** [comment]
I would want to check but this should work `g.adv.open_plot_window(is_primary=True, host="NDXPOLREF")`
