### ISSUE TITLE
KEPCO: Test with hardware (restart in remote mode)

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5851]
Original ticket https://github.com/ISISComputingGroup/IBEX/issues/3185. This ticket is to test the changes with hardware (possibly on ZOOM or with the EMU zero field).

Acceptance criteria, the following is tested with hardware:

- [x] The firmware version is retrieved correctly and you can caget it
- [x] KEPCO is correctly set into remote mode
- [x] The 3 permutations of the RESET_ON_START macro act as expected (Details here https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Kepco-Power-Supply#macros)
- [x] Able to control the kepco as normal
- [x] Resetting and resending parameters from the OPI

**Comment by JamesKingWork** [comment]
Planning to do this in the short shutdown 27/10/2020-10/11/2020

**Comment by JamesKingWork** [comment]
In a meeting with @rerpha and EMU we tested the acceptance criteria above. It was confirmed with the LED on the hardware that the device was correctly set to remote mode and we could send reasonable setpoints.

**Comment by Tom-Willemsen** [comment]
Added hotfix to https://github.com/ISISComputingGroup/IBEX/wiki
