### ISSUE TITLE
System tests debug failing [timebox: 0.75 days]

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5856]
System tests debug is failing on two tests:
- restart of caenv895
- restart of mk3chopper

I suspect both of these are due to a crash in the debug build when no device is present. Should such tests be run in e.g. recsim?

## acceptance criteria

- tests fixed or not run in debug mode

**Comment by JamesKingWork** [comment]
If timebox is up put both IOCs into exclusion list.

**Comment by Tom-Willemsen** [comment]
- CAEN: https://github.com/ISISComputingGroup/EPICS-CAENVME/pull/3 (thanks to @FreddieAkeroyd  for helping diagnose/fix)
- MK3CHOPPER: looks to be intentionally hanging on startup if no device present. We have lots of closed tickets about the mk3choppers startup behaviour r.e. memory leaks, so I am weary of trying to change this. Add it to skips instead. https://github.com/ISISComputingGroup/system_tests/pull/70
