### ISSUE TITLE
POLREF: shutdown tasks / testing (refl config and motor offsets)

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5857]
As a POLREF scientist, I would like the reflectometry configuration and motor setup to be tidy and correct to our convention. We should modify and test this on the instrument during the shutdown. See acceptance criteria for changes needed.

### Done

- [x] Pull in changes from #5800
- [x] Reflectometry Server to take the natural beam angle of 2.3 deg into account for tracking. This will make it track the beam more accurately and remove the need for some of the offsets/engineering corrections in use. See INTER config for how this is done
    - [x] All components in the reflectometry configuration are set up so their axis of movement is at 90 + 2.3 deg relative to the beam
     - [x] All distances between components are modified to be along the beam instead of along the floor.
- [x] Add mode inits to all relevant parameters (pending #5781)
- [x] Test Laser Mode
- [x] Check 4 position sample heater stage (should be just eurotherms = config changes)
- [x] Test Bump Strip (MOT:BUMP_STOP shows the right status, signal source is configured in configurations/galil/bumpStop.cmd)

#### Awaiting alignment
- [ ] ~Set offset on polariser flipper height to zero it on beam~
- [ ] ~Set offset on Analyser 1 to zero it on beam~
- [ ] ~Set offset on BOA to zero on beam (? pending scientist reply)~
- [ ] ~Check CS parked position is correct~

Spun out into separate ticket: https://github.com/ISISComputingGroup/IBEX/issues/6476

#### Awaiting Danfysik availability
- [ ] ~Check negative magnetic field is logged as negative field (not the magnitude as it was in current cycle)~

No Danfysik was available for testing before cycle. The scientists know to check that the sign of the readback value is correct when they start using one, and will let us know if there is an issue.

**Comment by JamesKingWork** [comment]
Adding support to avoid need for release notes, please add if they are required

**Comment by DominicOram** [comment]
POLREF is currently running well and appears to have all the above
