### ISSUE TITLE
Instrument Scripts: Test on LOQ [timebox: 1 day]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5858]
As a SANS instrument scientists I would like the sans script in InstrumentScirpts to work to my satisfaction. To make sure everyone understand what is meant by this a selection of instrument scientists and IBEX developers will spend some time on LOQ on the week beginning 9th November to discuss the requirements and fix the script so that they work.

## Acceptance Criteria
* The sans scripts work to the satisfaction of the instrument scientist
* Information on the requirements of the sans scripts and what they are expected to do is written up

**Comment by DominicOram** [comment]
I agree @kjwoodsISIS. I will discuss with scientists how much time we'll have on the beamline and timebox it based on that.

**Comment by FreddieAkeroyd** [comment]
2 people for 1 day plus writeup

**Comment by DominicOram** [comment]
@ThomasLohnert, @RaiBishal and I attended the meeting. The crux of the issue on LOQ was that it wasn’t up to date with the latest scans library. We’re going to do the following:

- Add a step so that when we update IBEX in general we also make sure to update the scans library
- Correct the documentation for the scan command (on LOQ it didn't have the correct arguments from https://github.com/ISISNeutronMuon/InstrumentScripts/pull/77 e.g. `det`)

Given the meeting was significantly less than the 1 day timebox we can do these things in this ticket

**Comment by John-Holt-Tessella** [comment]
People from other instrument can update the shared instrument scripts did we really want to update it, or is this just on LOQ? It is possible for one instrument to break another. As long as everyone knows the situation I am happy

**Comment by DominicOram** [comment]
I think we need to more actively manage it. We can have a discussion if you like?

**Comment by DominicOram** [comment]
In discussion with @John-Holt-Tessella, @Tom-Willemsen, @ThomasLohnert and @RaiBishal the following was decided:
1. When doing a release we will tag a release of InstrumentScripts and release it to all instruments, whether they currently use the library or not
1. We will write an automated service to tell us if instruments have local changes (or if not on the release tag any more)
1. If instruments do have local changes we will discuss with them getting the changes into master for the next release
1. We will block pushing to master, instead requiring people to make PRs which we will review and check for unexpected side effects to the best of our ability. Other instrument scientists are welcome to contribute to this review process

The acceptance criteria of this ticket is now to:
- [ ] Confirm the above process is ok within the Experiment Controls group
- [ ] Confirm it is ok within the SANS/reflectometry groups
- [ ] Document the process

**Comment by DominicOram** [comment]
@ThomasLohnert would you be able to do the documentation side of this ticket? I believe the issue is that https://github.com/ISISNeutronMuon/InstrumentScripts/blob/7e135fb92568bc617bc291888498fdfcf43f6816/general/scans/defaults.py#L80 needs updating? Some follow up questions:
* Crisp/demo/inter/polref/surf override scan but don't seem to do anything other than pass values through, you then need to rewrite all the documentation out again. Is this inheritance required?
* Crisp/demo/inter/polref/surf also document a `detector` argument still e.g. https://github.com/ISISNeutronMuon/InstrumentScripts/blob/7e135fb92568bc617bc291888498fdfcf43f6816/instrument/inter/scans.py#L71 is this superseded by det now and so can be removed?

**Comment by ThomasLohnert** [comment]
Yep, hopefully will get around to it on Monday.

**Comment by DominicOram** [comment]
ZOOM also had issues today due to them not being on the master version of InstrumentScripts

**Comment by ThomasLohnert** [comment]
PR for docs: https://github.com/ISISNeutronMuon/InstrumentScripts/pull/82

> Crisp/demo/inter/polref/surf override scan but don't seem to do anything other than pass values through, you then need to rewrite all the documentation out again. Is this inheritance required?

Not quite, the default args for the general scans command are block, min, max, **step size** ..., whereas the default for the reflectometers is block, min, max, **step count**. We can discuss whether/how we want to homogenize this but I feel this is outside the scope of this ticket.

> Crisp/demo/inter/polref/surf also document a detector argument still e.g. https://github.com/ISISNeutronMuon/InstrumentScripts/blob/7e135fb92568bc617bc291888498fdfcf43f6816/instrument/inter/scans.py#L71 is this superseded by det now and so can be removed?

 `detector` is more powerful as it lets you pass in an entirely different Detector object (root class is `DetectorManager` I believe), which lets you customize how to process the data at each step. `det` is just a number specifying which spectrum to get the data from in the default implementation of the Detector used by the scan (this arg was `detector_number` but we have shortened it for convenience as it's used very frequently).

**Comment by DominicOram** [comment]
Email sent to instrument scientists from ISIS Experiment Controls, will give them until the end of the day to voice any concerns

**Comment by DominicOram** [comment]
Tickets created and linked above. Decision documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Decision-Log
