### ISSUE TITLE
Genie_python: change_users() not updating users in GUI

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5863]
Found this when running the training course on genie python scripting: 

To reproduce: 
1. Open scripting window and type `g.change_users()` with any name as an argument
1. Watch `Users:` field in IBEX - it flashes and only sometimes actually persists with the users names. If you already have a user set when running the GUI it may revert to that?

### Acceptance Criteria
1. Users show up when g.change_users() is set in genie python 
1. If this doesn't work because of permissions (i.e. manager mode) the user should be notified. 

### Notes
- We think this is to do with genie python itself rather than the GUI because `dashboard["user"]` is not getting updated either.

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/322
https://github.com/ISISComputingGroup/genie_python/pull/295

**Comment by DominicOram** [comment]
@RaiBishal I've made some minor changes and added some tests, can you confirm it still fixes it for you? It works for me but is really slow

**Comment by RaiBishal** [comment]
@DominicOram works for me and does not seem to be slow at all.

**Comment by JamesKingWork** [comment]
Is this complete now?

**Comment by DominicOram** [comment]
Sorry, yes, I must have forgot to move it over, will do that now
