### ISSUE TITLE
HIFI: labview crash

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5864]
LabVIEW crashed on HIFI  04:57:21 Sunday 1st November, details in windows event log give
```
Faulting application name: LabVIEW.exe, version: 10.0.0.4033, time stamp: 0x4c9265f7
Faulting module name: ucrtbase.DLL, version: 10.0.14393.2990, time stamp: 0x5caeb96f
Exception code: 0xc0000005
```
After a killseci labview again crashed, so a reboot of NDXHIFI was tried - labview started after this.

Running dependencywalker on labview confirms that ucrtbase.DLL is not loaded initially by labview, that is to be expected as labview predates its introduction. However it looks like some labview interaction leads it to load ucrtbase.dll, maybe a .NET interaction?

**Comment by FreddieAkeroyd** [comment]
Nothing further to do, see if it happens again

**Comment by DominicOram** [comment]
Don't think there's much more to learn from this, calling it done
