### ISSUE TITLE
Lewis: Move to version 1.3

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5866]
As a developer I want to make sure I'm on the latest version of all dependencies. Lewis is about to release a new version (https://github.com/ess-dmsc/lewis/pull/288). We should test that this works for us before they do the release.

## Acceptance Criteria
1. We're on the latest version of Lewis and tests continue to work

**Comment by DominicOram** [comment]
/remind me to look at this on Thursday

**Comment by DominicOram** [comment]
PRs at :
* https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/386
* https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/92

To test:
* Get the latest Lewis version by running `%PYTHON3% -m pip install git+git://github.com/ess-dmsc/lewis.git@v2_0_0_preview`
* Run a few IOC tests and confirm they still pass

This can't be merged until https://github.com/ess-dmsc/lewis/pull/288 is merged, then need to update genie_python dependencies

**Comment by rerpha** [comment]
NB: need to run `%PYTHON3% -m pip install git+git://github.com/ess-dmsc/lewis.git@master` now as the branch has been deleted

**Comment by rerpha** [comment]
Completed review, have put in impeded as we need to wait for the lewis release before merging

**Comment by DominicOram** [comment]
Also updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Emulating-Devices to specify you must run it in python 3
