### ISSUE TITLE
Scans: If folder doesn't exist cannot write plot data

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5867]
When I execute a scan it writes data to a .dat file for plotting. If the .dat file is in a folder that has not been created yet it fails to write this file and I cannot scan `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\scripts\\TEST\\Test_block_2020_11_5_9_39_0.dat'`. Generally on instruments this folder does exist but it would be better to create this folder rather than throwing an excpetion.

## Acceptance criteria:

- [ ] When folder doesn't exist ask if the user wants the script to create it (and either create it or abort the scan)
- [ ] If the folder can't be created inform the user with a warning
- [ ] When the folder does exist the user should not be prompted
- [ ] Add a test for this specific function

**Comment by JamesKingWork** [comment]
To recreate and test:

- Add the following method to the DemoDefaultScan class in instrument/demo/scans.py
```python
@staticmethod
def log_file(info):
    return "C:/Scripts/Test_not_here_100/Test.dat"
```
- Create a config which includes the SIMPLE IOC and a block on <Your instrument prefix>:SIMPLE:LONG
- Start a scripting console and check that instrument/demo/scans.py is where the scan function is located by running
```python
>>> import inspect
>>> inspect.getfile(scan)
```
- Then run `scan("Test_block", 0, 1, 3, seconds=10, save=True)` and you should get the FileNotFoundError

This is increasingly more of an edge case with the use of g.get_script_dir as a default. I have amended the acceptance criteria to ask the user if they would like to create the folder and reinforced that the user should not be prompted if the folder already exists

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/94
