### ISSUE TITLE
RIKEN: IOC & OPI for Danfysik 9700

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5871]
As a muon scientist I would like to control and monitor the Danfysik 9700 power supplies used on the RIKEN front-end.

#### Acceptance Criteria
1. The IOC must make available the same PVs as the existing Danfysik OPI.
1. The OPI must display the same fields as the existing Danfysik OPI.
1. I can control the Danfysik PSU via genie_python scripts.
1. IBEX must support at least 35 Danfysik IOC instances.

#### Notes
1. The RIKEN front-end will feature 33 Danfysik 9700 PSUs.
   * 23 x Quadrupoles: RQ1-RQ23
   * 4 x Bending magnets: RB1, RB2 (2 halves), RB3, RB4
   * 4 x Separator cross fields: XFD1, XFD2, XFD3
   * 2 x Switchyards: SY1, SY2
   ~* That's why we need at least 35 instances of the Danfysik IOC~ Do this separately
~1. It would be useful to support at least 35 Danfysik IOC instances (in case more get added).~ Do this separately
1. Installation/Commissioning Timescales (as of 06-11-2020, subject to change)
   * Danfysik 9700s are due on-site late January 2021.  
   * They will be installed and commissioned in Sept-Nov 2021.
1. PVs provided by this IOC will be consumed by OPIs running on NDXARGUS and NDXCHRONUS (see #6138).

**Comment by davidkeymer** [comment]
Initial testing of single PSU completed in ticket #6544

**Comment by DominicOram** [comment]
As of https://github.com/ISISComputingGroup/IBEX/issues/6867 this is done other than the 35+ IOCs, which is covered by https://github.com/ISISComputingGroup/IBEX/issues/6898
