### ISSUE TITLE
RIKEN: Custom PSU Tabular Summary OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5873]
As a muon scientist I would like an tabular summary of the status of all the PSUs in the RIKEN front-end.  The status information is provided by a PLC.

#### Acceptance Criteria
1. I can see a tabular view of all the RIKEN front-end PSUs.
   * for efficient use of screen real-estate, if the table is too long to fit on the screen, it can be split into two side-by-side tables
1. The table should have 5 columns
1. The first row in the table should be a header row.  Each cell in the header row should be labelled as follows:
   1. cell 1: PSU name
   1. cell 2: ON/OFF status
   1. cell 3: Klixon status (FAULT/OK)
   1. cell 4: Water Flow (FLOW TRIP/OK)
   1. cell 5: Flow (l/m) (1 decimal place)
1. Each row of the table should display status information for a single PSU.
1. In each row,  cell 1 (containing the name of the PSU) should act as a button.
   * on clicking the button, I can drill-down to the individual PSU OPI

#### Notes
1. The PSU status information is provided by a PLC
   * the PLC is a Schneider M580 (Modbus/TCP)
   * configuration covered by this ticket: #7241
   * the PLC is physically located in RIKEN control room
1. Consult the [photograph of the PSUs HMI screen](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/RIKEN%20FE/RIKEN%20Solenoid/PSUs.png) when creating the OPI.
1. The table will need at least 33 PSU rows (see #5871)
1. Some ideas on how the table could look like are sketched in the [RIKEN Handover slides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/RIKEN%20FE/RIKEN_Handover.pptx).
1. The flow is measured in litres/minute (l/m)

**Comment by boeuf-codes** [comment]
This ticket is based off of https://github.com/ISISComputingGroup/IBEX/issues/7241 and should not be merged until that has been. I would also suggest not merging this until https://github.com/ISISComputingGroup/IBEX/issues/5872 has, but it's not necessary.

For testing, ask David for the components needed for this, run the IOCs in record simulation. For testing individual parts of the OPI check:

- For each cell:
  - [ ] Check PSU 'name' column can be clicked to navigate to its associated IOC: see [RIKENFE MOXA NPort Devices and IOCs](https://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/RIKEN%20FE/RIKENFE%20MOXA%20NPort%20Devices%20and%20IOCs.xlsx) for the association between each PSU and their IOC
- For every row:
  - [ ]  Check one cell (that isn't power) and verify it's connected to the correct PSU e.g. `SCHNDR_01:<PSU name>:<PV...>`
  - [ ]  For RB2_1 and RB2_2 check they are both connected to `SCHNDR_01:RB2:<PV...>`
- For each column in 'on/off', 'klixon status' and 'water flow status' pick a random cell:
  - [ ]  Check the background formatting is correct for each state the PV can take
