### ISSUE TITLE
RIKEN: IOC & OPI for Technix PSU

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5874]
As a muon scientist I would like to control and monitor the Technix power supplies for the separators on the RIKEN front-end.

#### Acceptance Criteria
1. The Technix IOC must allow me to control the following variables:
   * voltage
   * current
   * HV status
   * Local/Remote Status
1. The OPI must display the following fields:
   * voltage
   * current
   * HV status
   * Local/Remote Status
   * Fault status
   * Interlock status
1. I can control the Technix PSU via genie_python scripts.
1. IBEX must support at least 6 Technix IOC instances.

#### Notes
1. Technix manual is here: \\isis\shares\ISIS_Experiment_Controls\Manuals\Technix power supply
1. The RIKEN front-end will feature 6 Technix PSUs.
1. IBEX should support at least 6 Technix IOC instances.
1. Note sections 1.7 & 1.8 of the Technix manual: 
   * 1.7 Maximum Frequency (define maximum frequency of communication)
   * 1.8 Use and Safety
1. Installation/Commissioning Timescales (as of 06-11-2020, subject to change)
   * The Technix PSUs are due on-site in May 2021.
   * They will be installed and commissioned in Jan 2022.

**Comment by davidkeymer** [comment]
PSU [homepage](https://www.technix-hv.com/sr-300-to-3000-watts.php)

**Comment by rerpha** [comment]
As Freddie suggested may be able to use https://epics.anl.gov/EpicsDocumentation/AppDevManuals/RecordRef/Recordref-24.html  for the status readback (`E` was the command i think?) - it#s for 16 bits but we could probably just not care about the first 8

**Comment by daryakoskeroglu** [comment]
PR for OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1409
PR for IOC master: https://github.com/ISISComputingGroup/EPICS-ioc/pull/681
PR for IOC support: https://github.com/ISISComputingGroup/EPICS/pull/280

**Comment by rerpha** [comment]
I wonder if we can get one of these in the office for testing - @davidkeymer any ideas if they've been ordered in yet?

**Comment by daryakoskeroglu** [comment]
Wiki page has been created for the device: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Technix-PSU

**Comment by FreddieAkeroyd** [comment]
Though not mentioned on the ticket above, i think it would be useful to also report for diagnostic purposes:
- the inhibit status (in case it got enabled e.g. directly on the device and then stopped ibex from working)
- mains status (F command)
- whether you are in voltage or current control mode (PL1 status bit)

**Comment by FreddieAkeroyd** [comment]
@davidkeymer the voltage and current are set in the range 0-4095 i.e. 12bit ADC. Are the users expecting to set the value this way, or does this need a linear conversion to a real value?

**Comment by davidkeymer** [comment]
I have asked the RIKEN Refurbishment project manager for clarification.

**Comment by FreddieAkeroyd** [comment]
After #7143 we should be able to limit the max command rate to 10Hz as per recommendation in vendor manual

**Comment by FreddieAkeroyd** [comment]
Hi @daryakoskeroglu I had a few comments on the support module https://github.com/ISISComputingGroup/EPICS-Technix but as it isn't a PR i'll need to add them here.
* I thought LINR in a DB would not work unless set_voltage, get_voltage, set_current and get_current used %d,%*d rather than %f,%*f
* ASLO in a db should be the same on both the input and output (ai, ao) for the same item, so ASLO on VOLT:SP should be the same as that on VOLT i.e. 0.0002442
* VOLT does not need to contact the device, I believe it would work with DTYP of "Raw Soft Channel", INP of "$(P)_VRAW.RVAL CP" and SCAN of "Passive"
* The VOLT/VOLT:SP comments apply to CURRENT/CURRENT:SP
* MAINS could be bi record with ZNAM "defective" and ONAM "correct"

**Comment by daryakoskeroglu** [comment]
Hello @FreddieAkeroyd, changes that you mentioned are pushed and should be available in the support module

**Comment by FreddieAkeroyd** [comment]
Thanks @daryakoskeroglu 

@davidkeymer could you please complete the review
