### ISSUE TITLE
RIKEN: IOC & OPI for Kicker Timing

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5875]
Based on the comments and discussion in the planning meeting:

As a scientist on RIKEN I want to be able to easily control my Kicker via a DG645 with a custom OPI

## Acceptance Criteria
- [ ] Check what the scientists actually want this to look like
- [ ] Check that requirements specified in scientists' email (see comment for details) are met by https://github.com/ISISComputingGroup/IBEX/issues/7367

**Comment by davidkeymer** [comment]
DG645 will be used for this purpose, rather than DG535 as originally planned.  Work covered by ticket #5154

**Comment by davidkeymer** [comment]
Custom OPI for kicker timing may still be required.  Consult with instrument scientists.

**Comment by KathrynBaker** [comment]
Original Text:

As a muon scientist I would like to control and monitor Kicker timing settings.
Control of Kicker timing settings will be via a Stanford DG535 Digital Delay Generator.

Acceptance Criteria
I can control a Stanford DG535 Digital Delay Generator via the IBEX GUI
I can control a Stanford DG535 Digital Delay Generator via genie_python
Notes
DG535 manual is here: \\isis\shares\Manuals\Stanford_Research__DG535_Delay_Pulse_Generator
The DG645 model could be a suitable alternative to the DG535.
At the present time (November 2020), it is not clear which DG535 variables are required to control the Kicker timing. Consult the muon scientists for details. It is likely that the IOC will underpin a custom Kicker OPI.
See also https://github.com/ISISComputingGroup/IBEX/issues/2815.
See also [ARGUS_CHRONUS_Questions.docx](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/ARGUS_CHRONUS_Questions.docx) for more information.
scientists highlighted that T0 timing is a problem on ARGUS & CHRONUS. They suggested that information from Kicker timing could help.

**Comment by boeuf-codes** [comment]
See `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket5875_RIKEN_kicker_ioc_opi` for scientists' requirements.

**Comment by NikolaRoev** [comment]
Can confirm requirements will be met by #7367. Saving and loading to device memory slots will be implemented in a follow-up ticket.
