### ISSUE TITLE
RIKEN: Extend TPG300 IOC & OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5877]
As a muon scientist I would like the TPG300 IOC/OPI to report and view 
   1. pressure threshold violations
   1. relay contact status

#### Acceptance Criteria
1. The IOC supports a pressure threshhold setting
1. The IOC reports the relay contact status of the TPG300 device (see Notes below)
1. The OPI displays an indication if the pressure is below the threshhold setting (red LED, lit=BELOW/unlit=ABOVE)
1. The OPI displays the relay contact status (green LED, lit=ON/unlit=OFF)
1. I can query the pressure threshhold status via genie_python
1. I can query the relay contact status via genie_python

#### Notes
1. It may not be possible for the IOC to obtain the relay contact status.  Investigation is required.

**Comment by FreddieAkeroyd** [comment]
The threshold is a device setting
"Lower threshold, defines pressure value
at which the switching function turns on
when pressure is dropping.
Upper threshold, defines pressure value
at which the switching function turns off
when pressure is rising."

**Comment by Adam-Szw** [comment]
It seems that it's impossible to query the device for relay contact status. This conclusion is based on that there is no mention of relays in communication protocol instructions in the manual for the device. [The manual can be found here - page 59 for communication protocol](http://lmu.web.psi.ch/docu/manuals/bulk_manuals/Pfeiffer/TPG_300.pdf)

**Comment by FreddieAkeroyd** [comment]
I agree it looks a little unclear. The relays get mentioned with regard to switching functions (p. 38) and the protocol lets you query switching function status (p. 65) but I don't know if switching function status is what is meant by relay contact status. @davidkeymer @ChrisM-S do you have any more details or a RIKEN contact name who could clarity what is required?

**Comment by davidkeymer** [comment]
I've asked RIKEN refurbishment project manager for clarification.  I'll put any information here if/when I receive it.

**Comment by ChrisM-S** [comment]
After querying with IS, it should be possible to use the SPS command  to set up IOC/OPI for the TPG300 to match our vacuum gauge setup on the front end.

> The command “SPS” looks like it will read the status of all 4 relays (1 to 4) and the two internal virtual relays which switch on the high vacuum Penning gauges (A and B).
Just knowing the thresholds and current pressure is not enough, if the pressure is in the hysteresis band between the upper and lower setpoints.
The readback should be split into four PVs 1,2,3,4. In the synoptic we might then want to label beamline sections as “vacuum good” or “vacuum bad” based on some of those relays, as well as showing the numeric pressure.

> Usually two channels of a TPG500 are connected to sensors of different types (Pirani, Penning) measuring the vacuum at the same point in the system. Can we have “combined” pressure reading PVs from these? So we first read the Penning (A1 or B1), and if it’s on we return that pressure, and if it’s off we fall back to reading the Pirani value (A2 or B2). Rather than configuring via macros, it might be simplest to assume any TPG300 has this setup for (A1,A2) and (B1,B2) and create PVs for Pressure_A_combined and Pressure_B_combined (or other suitable names).

**Comment by Adam-Szw** [comment]
PRs:
IOC master: https://github.com/ISISComputingGroup/EPICS-ioc/pull/680
TPG300 support: https://github.com/ISISComputingGroup/EPICS-TPG/pull/9
Device Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/137
Test Framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/526
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7113

How to review:
- before seeing new OPI, have a look at current TPG300 OPI for comparison
- check out branch on each location
- at IOC master and support directories use 'make clean uninstall' and then 'make'
- test IOC yourself by adding TPG300 to config and seeing the OPI in the device screens
- use existing device emulator to run the IOC in DEVSIM mode (see wiki on emulating devices)
- see if the functionality matches criteria, conversation history in the comments and the manual (see above)
- run the tests and see if they pass and if they are sufficient
- everything else that comes with reviews (see if code is understandable etc.)

**Comment by daryakoskeroglu** [comment]
Taking the "under review" label off as I am attending Lovelace Colloquium and will be on annual leave from tomorrow.

Note for the reviewer: 

- Tests are passing without any problem
- OPI looks good and working
- I can add the device to config
- Can talk to the device from emulator (although had problems with sending using PuTTY so worth to check)
- Freddie made comments on db files, see if conversation is resolved 
- Link to the manual: http://lmu.web.psi.ch/docu/manuals/bulk_manuals/Pfeiffer/TPG_300.pdf

**Comment by FreddieAkeroyd** [comment]
@daryakoskeroglu you mentioned above taking the "under review" label off, but it is still present. Were you still reviewing this or did you want me to do that?

**Comment by daryakoskeroglu** [comment]
@FreddieAkeroyd Apologise, I am not reviewing this at the moment, not sure why "under review" label is still present. Will take the label off now.

**Comment by FreddieAkeroyd** [comment]
Going to look at pearlpc first

**Comment by Adam-Szw** [comment]
Left a few conversations open to highlight that I'm not sure if I reworked those bits correctly

**Comment by Adam-Szw** [comment]
(hopefully) implemented requested changes. Be aware though that the tests passed for me even this rework. They should definitely be passing now so let me know if they dont and we can have a look together

**Comment by Adam-Szw** [comment]
(hopefully) implemented requested changes. Be aware though that the tests passed for me even this rework. They should definitely be passing now so let me know if they dont and we can have a look together
