### ISSUE TITLE
ARGUS: Magnet Status OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5879]
As a muon scientist I would like an OPI to display information about the status of my magnet.

#### Acceptance Criteria
1. The ARGUS Magnet Status OPI displays the following fields.
   1. Magnet Temperature (inferred from water temperature)
   1. Magnet Water Flow rate (l/m) (to 1 decimal place)
   1. Klixon status (FAULT/OK)
   1. Water flow status and rate of PSU (Longitudinal only)
   1. MOL (Magnet On Light) status

#### Notes
1. The ARGUS magnet status information is provided by a PLC via PVs
   * the PLC is a Schneider M580 (Modbus)
   * the PLC is physically located in RIKEN ~~control room~~ area

**Comment by davidkeymer** [comment]
Still required for ARGUS migration to IBEX

**Comment by isaachilly** [comment]
Francis Pratt said it is okay to leave the temperatures of the LONG and TRANS magnets as 'N/A' for now, due to being unable to get this data.  RIKEN front-end ones have temperatures as they are fitted with a **separate** temperature sensor that the LONG and TRANS magnets do not have.

**Comment by isaachilly** [comment]
## PRs
[Code](https://github.com/ISISComputingGroup/ibex_gui/pull/1653)
[Release notes](https://github.com/ISISComputingGroup/IBEX/pull/8139)
