### ISSUE TITLE
CHRONUS: Magnet Status OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5880]
As a muon scientist I would like an OPI to display information about the status of my magnet.

#### Acceptance Criteria
1. The CHRONUS Magnet Status OPI displays the following fields.
   1. Magnet Temperature
   1. Magnet Water Flow rate (l/m) (to 1 decimal place)
   1. Klixon status (FAULT/OK)

#### Notes
1. The CHRONUS magnet status information is provided by a PLC
   * the PLC is a Schneider M580 (Modbus)
   * the PLC is physically located in RIKEN control room

IOC schneider IOC already exists, there is an existing opi for argus but chronus needs a very similar. they are both showing a subset of riken front end

**Comment by davidkeymer** [comment]
Very similar to the [ARGUS](https://github.com/ISISComputingGroup/IBEX/issues/5879) version and should just need some editing of that.

**Comment by isaachilly** [comment]
##PRs 

- https://github.com/ISISComputingGroup/ibex_gui/pull/1683
- https://github.com/ISISComputingGroup/IBEX/pull/8267
