### ISSUE TITLE
instrument checker: add ibex version

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5884]
As a developer i would like the ibex version to be automatically determined and listed on http://beamlog.nd.rl.ac.uk/inst_summary.xml - this is in case it is missed from https://github.com/ISISComputingGroup/IBEX/wiki

## Acceptance Criteria
1. When looking at the above summary page the IBEX version is listed
1. The IBEX version is removed from the Wiki page, and only hotfixes are recorded there

**Comment by FreddieAkeroyd** [comment]
Background - HIFI was not listed on the ibex versions wiki page, and so was running a very old mini inst. COM.DLL was upgraded to fix the IOC time issue and this broke the installation there. If we auto-generated our ibex deployments and version page, then we could avoid such issues potentially happening again.

**Comment by DominicOram** [comment]
Now fixed
