### ISSUE TITLE
System test iocs: Fix current failures

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5888]
As a user, I would like the IOCs I use to be passing their tests so we have some guaranteed behaviour.

Tests failing as of build 5192:
- [x] kepco_rem + kepco_no_rem
- [x] DAQMx_monster
- [x] cryosms
- [x] danfysikdisableautoonoff
- [x] gem_jaws
- [x] ips
- [x] jsc4180
- [x] loq_aperture
- [x] mercuryitc
- [x] mezflipr_v1
- [x] refl (To be handled by @ThomasLohnert please leave a note with issue and solution on ticket)
- [x] rknps
- [x] samplechanger
- [x] tpg26x

Acceptance criteria:

- [ ] Tests all pass locally and on build server
- [ ] Root cause analysis of tests

**Comment by JamesKingWork** [comment]
kepco_rem and kepco_no_rem were failing because the python telnet client failed to send repeat start ioc (ctrl-x) commands to the kepco. I have implemented a retry that closes and reopens the telnet connection after a failure which seems to fix the issue.

**Comment by JamesKingWork** [comment]
danfysikdisableautoonoff was failing because genie python behaviour changed to raise an exception if there is disp set on a pv that you are trying to set. I have now asserted that this exception is raised as we are expecting it.

**Comment by JamesKingWork** [comment]
samplechanger was because ticket https://github.com/ISISComputingGroup/IBEX/issues/5865 had not gone through by time of running.

**Comment by JamesKingWork** [comment]
cryosms is failing because the IOC takes longer to start so running `self.ca.assert_that_pv_is("INIT", "Startup complete",  timeout=30)` fails as the PV is still `Startup incomplete`. The ioc manages to complete startup if we up the timeout to 60 seconds. Along with @ChrisColeExpControl we have agreed that this is ok, so I have upped the timeout.

**Comment by JamesKingWork** [comment]
The jasco, ips and mezflip seem to be fluctuations (they passed in build 5197)

**Comment by JamesKingWork** [comment]
gem_jaws was failing to pass the IFGEMJAWS macro through correctly, define it here https://github.com/ISISComputingGroup/EPICS-ioc/pull/553

**Comment by JamesKingWork** [comment]
> samplechanger and loq_aperture was because ticket #5865 had not gone through by time of running. Copying the files onto the build server caused it to pass.

samplechanger and loq_aperture are now still failing on new tests even with the new changes, I will look at the new errors as well

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-ioc/pull/553
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/387

**Comment by JamesKingWork** [comment]
mercuryitc had some test failures because we were looking for `MercuryGlobal.db` in `$(TOP)/db/MercuryGlobal.db` rather than `$(MERCURY_ITC)/db/MercuryGlobal.db`, other failures are still being diagnosed.

**Comment by kjwoodsISIS** [comment]
@JamesKingWork  - it would be useful to know if there are any patterns to these failures.  I don't expect there to be a single pattern, but there might be a few common themes.  Perhaps, when we get to the end of this ticket, it would be worth doing a root cause analysis of these failures to try to identify any common themes.

**Comment by JamesKingWork** [comment]
> @JamesKingWork - it would be useful to know if there are any patterns to these failures. I don't expect there to be a single pattern, but there might be a few common themes. Perhaps, when we get to the end of this ticket, it would be worth doing a root cause analysis of these failures to try to identify any common themes.

Yes I will do this

**Comment by JamesKingWork** [comment]
> mercuryitc had some test failures because we were looking for `MercuryGlobal.db` in `$(TOP)/db/MercuryGlobal.db` rather than `$(MERCURY_ITC)/db/MercuryGlobal.db`, other failures are still being diagnosed.

Failures on my machine were because I had not recompiled CSM so the cvt record was not working correctly.

**Comment by JamesKingWork** [comment]
The DAQmx_monster was failing because DAQPOSTIOCINITCMD was being set to `DAQmxStart('myport1')` but the macro was not passed through correctly. Having seen this and the gem_jaws fail for a similar reason I am now investigating if environment variables are all being set correctly after the change from running `epicsEnvSet(MACRO, VALUE)` from a Var/tmp/test_config.txt to loading macros with https://github.com/ISISComputingGroup/EPICS-icpconfig/pull/7/files

**Comment by JamesKingWork** [comment]
DAQmx_monster was not passing through macros correctly because the ioc_name was set to DAQmx in the icpconfig and written to test_macros.txt as DAQMXTEST so icpconfig does not know to strip DAQMXTEST from the macro name.

**Comment by JamesKingWork** [comment]
The rknps tests are now no longer failing on either my machine or the build server, I am presuming this was a transient failure

**Comment by JamesKingWork** [comment]
Underlying causes:

Non-related tests:

- kepco_rem and kepco_no_rem was a telnet issue that resided on ndwreno (though this may apply to other windows 7 machines I do not know). It was an issue with the tests and not the IOC itself though I believe.
- disabledanfysikautoonoff was because of a change in the behaviour of genie_python when a DISP is set
- cryosms was because a timeout was to wait for the ioc to startup was set too ambitiously for slower machines e.g. ndwreno
- loqAperture and samplechanger were because during a ticket where the motionsetpoints.cmd syntax was changed the test settings file syntax was not updated accordingly, but this was fixed in a ticket prior to this one
- mercuryitc was looking for a db file in the wrong place because the wrong macro was used when moving the db files to the support directory and the build files to the ioc directory


The following were caused by a change in the way macros are written and loaded for tests (see https://github.com/ISISComputingGroup/EPICS-icpconfig/pull/7/files):

- DAQmx_monster the ioc name written by the test was different to the ioc name expected by the icpconfig
- gem_jaws had a macro being set to a space. It seems that the new way of writing these test macros (without quotation marks) causes the icpconfig to strip the whitespace and thus not set the macro correctly

Transient failures:

- mezflipr_v1
- rknps
- ips
- jsc4180
- tpg26x
