### ISSUE TITLE
SUPPORT: SANDALS eurotherm units

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5891]
Bunch or quick questions from SANDALS

1. Units for the eurotherm (added +1 to #4019)
1. Added a null calibration file with bar as units 
1. Sort out PVs on synioptic, removing keithley as requested and pointing pvs back to sandals on sandal76

**Comment by DominicOram** [comment]
Looks pretty run-of-the-mill
