### ISSUE TITLE
GUI: slow to search PVs

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#5892]
As a developer I would like the PV search to be faster/more responsive when selecting a pv to add to a block, currently typing in a pv prefix when selecting a pv to add to a block causes the GUI to lag on my machine. I think having a faster search would mean the GUI is less frustrating to use for scientists that need to quickly add a PV to a block. 

### Acceptance criteria
- Search is made a bit quicker by using a timer or similar method
- If the search text has not changed the function should not perform a search

### Implementation details
I think we should use a timer instead of a listener, this is the code currently responsible for doing the search (in `uk.ac.stfc.isis.ibex.ui.configserver.editing.pvs.PVSelectorPanel`: 
```
blockPVTable.addSelectionChangedListener(new ISelectionChangedListener() {
            @Override
            public void selectionChanged(SelectionChangedEvent arg0) {
				IStructuredSelection selection = (IStructuredSelection) arg0.getSelection();
				if (selection.size() > 0) {
					PV pv = (PV) selection.getFirstElement();
					pvAddress.setText(pv.getAddress());
				}
			}
		});
		
		pvAddress.addModifyListener(e -> blockPVTable.setSearch(pvAddress.getText()));
```

there are loads of search results if you start typing TE:NDLT or the start of your prefix, i think it'd be a bit faster if you had a timer that either:
1. Polled on regular intervals and searched if the text has changed
_OR_
1. Add a timer that waits for 0.5 seconds after the user has finished entering text

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1253

**Comment by rerpha** [comment]
release notes: https://github.com/ISISComputingGroup/IBEX/pull/6207
