### ISSUE TITLE
LARMOR: error message from genie python

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5893]
At 13:23 a waitfor was started, at 17:20 and then every few minutes after that is now printed: 
```
2020-11-11T17:20:48	(CMD)	(17808)	2020-11-11 17:20:48.374781: Exception in waitfor loop: UnableToConnectToPVException: Unable to connect to PV IN:LARMOR:DAE:GOODUAH: does not exist
2020-11-11T17:20:48	(CMD)	(17808)	2020-11-11 17:20:48.512496: Exception cleared
```
as of now (21:30) it is still printing

## Acceptance Criteria
1. The root cause of the message is identified
1. The cause of the message is eliminated

**Comment by FreddieAkeroyd** [comment]
Occasionally the genie python log gives:
```
2020-11-11T17:34:56	(CA)	(17808)	ERROR: CAException: type=-1 state=200 op=5 file=c:\instrument\apps\epics\base\master\modules\ca\src\client\cac.cpp lineNo=1320
```
This is `pvMultiplyDefinedNotify`

**Comment by FreddieAkeroyd** [comment]
The gap between error messages started out at 30 seconds and has gradually been getting longer, it is now 10 minutes

**Comment by Tom-Willemsen** [comment]
+1 EMU
+1 POLARIS (probably)

**Comment by DominicOram** [comment]
Do we have any idea of a way forward on this? It's next on the ready column but I'm not sure how to pursue it.

**Comment by FreddieAkeroyd** [comment]
I sent email to instrument scientists suggesting they restart python console, this seems to have fixed it. Not sure what underlying issue is.

**Comment by Tom-Willemsen** [comment]
I've written a script on branch `Ticket5893` of the private scripts repo which checks for occurences of this error on all instruments. It looks like it started happening on the 11th for all instruments and continued until they restarted genie_python. However the last few days have been error-free on all instruments.

Given that this feels like a hard-to-reproduce one off error, I think we should leave it at that at the moment and investigate further if it recurs.

Maybe we could add some variant of the above-mentioned script to nagios?

**Comment by JamesKingWork** [comment]
I agree that the best solution to this ticket is to give us better tools to investigate if this happens again and having a check on Nagios for it is a good idea.

I am however not entirely happy with our processes for using the private scripts repo. It would seem better to me to have utility functions available to all scripts such as the search_genie_python_log_files and then create individual scripts we can just invoke for specific tasks. Having branches each with a very specific purpose does not seem a good way to manage this to me, it can become messy very quickly. 

The script provided also only searches genie_python logs from November 2020 and this error may occur at another time not covered by this search.

Can we also add that there is a script to search for these errors in the dev wiki? And that if we spot this occurring again we should investigate more fully.

**Comment by JamesKingWork** [comment]
Is this also no longer considered urgent?

**Comment by kjwoodsISIS** [comment]
I am not sure I understand the reason for putting this ticket back into rework.
   1. The purpose of this ticket was to resolve a problem seen on LARMOR (but present on other instruments too).
   1. It seems like the root cause of the problem is difficult to ascertain and it may be better to wait to see if it recurs, which suggests that there is nothing much left to do.
   1. However, the re-work is suggesting generalising the scripts we created to investigate this occurrence of the problem to make them useful should there be a future occurrence.
   1. I think this rework is outside the scope of this ticket
      1. Yes, the generalised scripts might be very useful if the problem recurs.  But what if it never recurs?
      1. The work to generalise the scripts should be proposed in another ticket, so that it can be prioritised alongside everything else.
   1. If there is no other rework to be done, then I think this ticket can be called complete.

**Comment by JamesKingWork** [comment]
I see your point, I shall propose another ticket for the generalisation. The rework for this ticket is thus limited to making this script removing the November date from the genie_python logs, adding details to the dev wiki about using the script and saying that we should investigate more fully if this occurs again on the wiki.

**Comment by JamesKingWork** [comment]
Looks good

**Comment by JamesKingWork** [comment]
What points should we give to this ticket?

**Comment by FreddieAkeroyd** [comment]
Is it possible this is related to detmon testing? The "gap between error messages started out at 30 seconds and has gradually been getting longer, it is now 10 minutes" is a bit like PV retries, I am wondering if we need to protect instruments with ISISComputingGroup/IBEX#5917 before going further, it is not just the block gateway that sees all this sudden traffic, iocs will to leading to ISISDAE not replaying to `get_uamps` quickly enough etc.
