### ISSUE TITLE
KEPCO: Ensure RESET_ON_START set correctly

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5895]
After giving the option to reset and resend setpoints on kepco IOC start we decided to keep the default option to be zero and therefore not do anything by default. 

ZOOM and EMU are expecting to reset and resend setpoints on IOC start so we need to set the RESET_ON_START for their kepco configurations correctly (we should also tell them that the default has now become zero so that if they set up any new kepcos they will need to set the macro accordingly). 

Further, we are not sure if the original error this is trying to fix is on other beamlines. We can find the devices that have the firmware that we expect not to have the SYST:REM command available by running a `caget %PVPREFIX%KEPCO_01:FIRMWARE` (this PV will only be available after next release). We should then tell instrument scientists who have firmware < 2.0 that if the kepco power cycles and restarts it may not be in remote mode, we should tell them the options that we have given them i.e. the macro settings and restarting the IOC, and the button on the OPI.

Acceptance criteria:

- [x] Set ZOOM and EMU kepco macros correctly
- [x] Notify ZOOM and EMU of the default change and what they need to do if they want to set up other kepcos
- [x] Find devices with firmware < 2.0 and notify instrument scientists of possible issue and available remedies

**Comment by JamesKingWork** [comment]
EMU has been set correctly using EMU_base component for kepco 1 to 4

**Comment by JamesKingWork** [comment]
Currently the following instruments have KEPCOs in their configs:

LARMOR has KEPCO_01
DEMO has KEPCO_01
ZOOM has KEPCO_02
ZOOM has KEPCO_01
CRISP has KEPCO_01
EMU has KEPCO_03
EMU has KEPCO_02
EMU has KEPCO_04
EMU has KEPCO_01
POLREF has KEPCO_03
POLREF has KEPCO_02
POLREF has KEPCO_04
POLREF has KEPCO_01
MUSR has KEPCO_03
MUSR has KEPCO_02
MUSR has KEPCO_04
MUSR has KEPCO_01
MUSR has KEPCO_05

After previous discussions with scientists EMU, MUSR and ZOOM have been set to reset and on IOC start. I will contact CRISP, POLREF and LARMOR to give them the options

**Comment by JamesKingWork** [comment]
I have now set the RESET_ON_START macro on ZOOM to 1, checked that all EMU and MUSR kepcos have the macro set to 1. I have also sent emails out to POLREF, CRISP and LARMOR ISs asking them how they would like the macro to be set. They have come back mostly with a "not sure" as they're not currently using the KEPCOs from IBEX. I have said to contact us for help when they next set one up and given them information about what the macros control.

To review:
- Check emails from experimental controls to IS are satisfactory
- Check ZOOM, EMU and MuSR have macros set correctly

**Comment by JamesKingWork** [comment]
> Sticking this as support for the project board checks - I think it is but feel free to change it if its not

Makes sense as support

**Comment by rerpha** [comment]
Just updated the Julabo config as they have separate kepco entries but otherwise all good.
