### ISSUE TITLE
reflectometry: Inter long axis should set z on move

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5896]
On INTER the long axis is movable, although they do not move it, however if it moves the z of the detector changes we should account for this in the calculations.

### Acceptance Criteria
- allow the z coordinate to be controlled like height and angle

**Comment by ThomasLohnert** [comment]
If this looks like it will take much longer than the estimate, consider just updating Z on move instead

**Comment by DominicOram** [comment]
Bit of documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-IOC#long-axis, I wanted to document the caveats somewhere but not sure there was exactly the right place.
