### ISSUE TITLE
IMAT: web dashboard not working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5897]
The web dashboard is giving "Could not connect to imat, check IBEX server is running." No errors reported on either side, restarting ndaextweb3 side did not fix things, and all the ports mentioned in the dev wiki seemed to be returning data from imat. Instrument scientist will restart ibex server at a convenient point and see if that fixes things.

**Comment by DominicOram** [comment]
I fixed this by restarting the INST archive, it appears for some reason the DAE didn't make it into the INST archive. To review confirm that the IMAT web dashboard is working.
