### ISSUE TITLE
Reflectometry: Custom motor readback next to parameter

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5899]
For some parameters in the reflectometry server it would be useful to have a custom readback PV next to the parameter so that we can easily diagnose where a key motor is.

### Acceptance Criteria

- Parameters can have a custom local PV set on a parameter, e.g. MOT:MTR0101.RBV
- If the parameter is set this is shown on the OPI next to the parameter in question

### Notes

It is unclear where the space will come from, maybe the label can be shorter?

**Comment by ThomasLohnert** [comment]
Only affects collimation plane parameters

**Comment by ThomasLohnert** [comment]
Possible solutions:
- Expose axis displacement via parameter (value is subject to engineering correction)
- Pass an extra PV for motor display value into the parameter

**Comment by John-Holt-Tessella** [comment]
PR;

- https://github.com/ISISComputingGroup/EPICS-refl/pull/29  (add description and characterstic value to info pv)
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/347
- https://github.com/ISISComputingGroup/ibex_gui/pull/1249
- https://github.com/ISISComputingGroup/IBEX/pull/6179

Docs
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Configuration#arguments-2
- https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Reflectometry-View#parametershttps://github.com/ISISComputingGroup/ibex_user_manual/wiki/Reflectometry-View#parameters
