### ISSUE TITLE
Reflectometry: Disable parameters connected to a component which is out of the beam

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5900]
If a parameter is out of the beam it associated with a component which is out of the beam it should be disabled so that the users are not confused by offsets have readbacks and setpoits which don't match.

### Acceptance Criteria

- If a component is disabled and is not the inbeam parameter the parameter is disabled in the OPI. Or at least greyed out, doesn't matter if the user sets it
- The parameter looks "enabled" again before a move if the setpoint for the In Beam parameter is "In"

**Comment by DominicOram** [comment]
Tooltip as to why it's greyed out would be good too

**Comment by ThomasLohnert** [comment]
Just had a support call from POLREF because FTHETA/FOFFSET did not move and it was not clear the reason was because FINBEAM was out. This would have helped

**Comment by DominicOram** [comment]
From a support POV even just a message in the refl log of "1.6 requested on FTHETA but not moving due to FINBEAM OUT" would have probably allowed me to solve the issue without any refl background knowledge

**Comment by John-Holt-Tessella** [comment]
Maybe move this one up in the importance rankings then.

**Comment by ThomasLohnert** [comment]
Make sure the parameter looks "enabled" again before a move if the inbeam SP is "In"

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/31
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/420

**Comment by John-Holt-Tessella** [comment]
![image](https://user-images.githubusercontent.com/7570055/109665311-efcc7780-7b65-11eb-9b6d-6f8f1257310e.png)

The above shows a problem, probably with the acceptance criteria, that even though I have selected that I want the SM in the beam I can not set its position which I need to be able to do. This is held in the the parameter itself so it may be interestingly hard to get this out and linked to the parameter to disable.
Also disabling a parameter does not stop me writing to the pv, I am not sure whether this is required but then it is not really a DISP field, I am slightly unsure what to do here lets have a chat. Whether to disable when DISP is set or whether to make it clearer in the interface

**Comment by John-Holt-Tessella** [comment]
To make it an error to move a parameter when the component is set to be out then we

Set <PARAM>:SP_NO_ACTION>DISP = 0
Set <PARAM>:SP.DISP = (<PARAM INBEAM>:SP:RBV==OUT)
Set <PARAM>:MOVE.DISP = (<PARAM INBEAM>:SP:RBV==OUT)

and make this apply in the param_write in driver_utils so caput sees it too

If MOVE.DISP = 1 then replace button with Out of beam with tool tip explaining what happens if you set param andf why you can't move it.
