### ISSUE TITLE
Client install script: delete old client before installing new

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5904]
As an instrument scientist I would like the client install process to be easier. The current install script assumes that the install location will be empty and copies files into it. However if an old client installation is also present the old plugins may confuse the client startup.

### Acceptance criteria
- Client install always installs a clean client (without any plugins/workspace etc from old client)

### Notes
- This might just be the `/MIR` flag on robocopy?

**Comment by ChrisM-S** [comment]
I'm a bit puzzled, don't we already have an MSI client install for non-instruments?  This would hopefully allow a clean uninstall before a re-install (or just offer an update option).  Much as it's sometimes a nuisance, the default would also to be request a restart if in doubt.  As far as I can see all of these issues would then be under control for minimal effort?

**Comment by kjwoodsISIS** [comment]
@ChrisM-S : we should have a **_single_** way to install the client on **_all_** PCs, whether an instrument or not.  Having two ways is a sure-fire recipe for divergence.  My preference would be for a `.msi`, created as part of the build process.

**Comment by John-Holt-Tessella** [comment]
If installed on an instrument the old client must be copied to data old so that we can roll back to it if there is a problem and server with releases on is down. We should add this to the requirements if we still think this is important.

**Comment by FreddieAkeroyd** [comment]
So we should do #5373

**Comment by ChrisM-S** [comment]
With the MSI kit there will be no need to copy the client folders (because we would just uninstall the current client & then re-install the previous version to return to the earlier version).  If the network is down, we could write keep USB stick or laptop up to date with the previous  client version on it - but we might also have worse problems at this point...

**Comment by FreddieAkeroyd** [comment]
/MIR was added to the install separately
