### ISSUE TITLE
Instrument Scripts: Automatically check if up to date

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5907]
As a user I would like the instrument scripts to remain working and not to break with an update of IBEX. Therefore they should be managed and kept up to date. The decision on how to manage them was made in https://github.com/ISISComputingGroup/IBEX/issues/5858#issuecomment-726889278. This ticket is to implement some of that decision.

## Acceptance Criteria
* A config checker like jenkins job is written to check whether instruments have local changes to InstrumentScripts
* ~Scientists are contacted for any instrument where this is the case and their changes are merged into master (with their input)~ moved to #5983

**Comment by JamesKingWork** [comment]
The service should fit well into our workflow e.g. by including it on Nagios or a Jenkins job that displays on the ibex overview

**Comment by FreddieAkeroyd** [comment]
need to have meeting about how credentials might be done for access

**Comment by JamesKingWork** [comment]
See https://www.jenkins.io/doc/book/using/using-credentials/ if choosing to do it as a Jenkins job

**Comment by RaiBishal** [comment]
As discussed with Dom and Mihai, if we put this in with ConfigChecker, we should rename the config checker to something else (name TBD).

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ConfigChecker/pull/28

**Notes from the discussion after stand-up**:
* To be run manually until a read-only account is prepared for all instruments, after which it will be added as a Jenkins job.
* Currently only compares the HEADs, in the future it should look at the release tags (once they are set up).

**Comment by mihai-stfc** [comment]
Reminder to rename the repo from `ConfigChecker` to something else (`InstrumentChecker`?), as I don't have access to Settings.
