### ISSUE TITLE
Instrument external gateway: filter name lookups 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5917]
Currently `gateway/gwext.pvlist` allows read only access to the instrument IOCs, but it also forwards on all name lookup requests from the rest of ISIS to the local instrument computer. This leads to a lot of unnecessary name lookups being done by e.g. the block gateway, which could cause performance issues.  As all PVs on a computer start with `$(MYPVPREFIX)` it would improve performance to only forward requests with a $(MYPVPREFIX) prefix onto the local computer for consideration

## acceptance criteria

* Rule added to `gateway/gwext.pvlist` to filter name lookups that are forwarded on. 
* confirm external PV lookup and web dashboard still work

**Comment by JamesKingWork** [comment]
Confirmed that this significantly increases the performance on the block gateway on DETMON for around 3000 PVs

**Comment by FreddieAkeroyd** [comment]
In Addition, adding a rule to deny a pattern not matching 
```
$(MYPVPREFIX)CS:SB:.*
```
to the end of gwblock.pvlist would be good too. This would be easiest of we enabled negative regex pattern matching in the gateway.

**Comment by FreddieAkeroyd** [comment]
It would also be optimum to remove the lower -> upper case RC rules in gwlock.pvlist, and move this aliasing to the run control IOC itself.

**Comment by FreddieAkeroyd** [comment]
covered in #5925
