### ISSUE TITLE
LET: mysql stopped working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5918]
The mysql database on LET got into a funny state, ibex journal viewer was not working, also VNC seemed to have crashed and most nagios checks were timing out. Restart of mysql followed by restart of ibex fixed most things, but WMI still appears not top be working.   

need to analyse MySQL error log and system logs to determine what happened.

**Comment by ThomasLohnert** [comment]
Updated docs:
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Other-Troubleshooting#instrument-page-not-working-on-web-dashboard
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Computer-Troubleshooting#cannot-vnc-into-the-machine

**Comment by GRyall** [comment]
Wiki documentation exists. Error was long enough ago that further analysis is unlikely to be useful. Closing ticket as no further action is required.
