### ISSUE TITLE
POLREF: Mercury SPC Fixes

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5921]
### Acceptance Criteria

1. Mercury SPC config parameters are in a config and not in globals
2. Mercury OPI tabs show correct information. At the moment Temp card 1 does not read back information from the Pressure card

### Notes

- Needs to be done after release so new macros are available in config to set
- probably best to make a new component

**Comment by John-Holt-Tessella** [comment]
Yes, I will remove the note in favour of the explicit task. Then change the note to be more this is a great thing we did

**Comment by DominicOram** [comment]
Added as can now be done with new release

**Comment by JamesKingWork** [comment]
Estimate for points?

**Comment by rerpha** [comment]
@ThomasLohnert is this still important/required?

**Comment by ThomasLohnert** [comment]
Yes, I don't think anything has changed.

**Comment by LilithCole** [comment]
Done as part of a support issue
