### ISSUE TITLE
An instrument: Install Windows 10 (Part 2)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5923]
As a Experiment Controls team member, I want to create a reliable, robust process for creating a Windows 10 VM on a VHD, so that I can deploy IBEX quickly and straightforwardly to any instrument.  Some work in this direction has already been performed - see #5489.  Further work is required to iron out the snags in the process.

#### Acceptance Criteria
1. Hold a meeting to 
   1. discuss the progress made so far
   1. identify the steps required to eliminate the snags (the snags list is on https://github.com/ISISComputingGroup/IBEX/issues/5437)
1. Document the discussion (using comments in this ticket)
1. Create one or more tickets to implement the steps identified in 1.(ii) above.

#### Notes
1. See #5489 for the work done so far.
1. The process to build a new windows 10 virtual machine is documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-a-windows-10-instrument-machine-from-MDT
1. The process of building a new MDT build server (rarely needed) is at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-a-windows-10-MDT-build-server
1. All necessary passwords and sensitive info should be on passwords share

**Comment by DominicOram** [comment]
The instructions in https://github.com/ISISComputingGroup/IBEX/issues/5489 to create an MDT server seemed to work fine. The issue was trying to create the VM for the instrument as it was bluescreening about ~5 minutes into the process, see attached gif. 

![win_10_crash](https://user-images.githubusercontent.com/10086797/100474207-059a4e80-30d8-11eb-95a7-2865272be86d.gif)

During the review I tried various methods of fixing it, including:
* Using different versions of the iso
* Removing the update windows task from MDT. Oddly despite removing this and pushing the update from the MDT server the VM still tried to install windows updates and still blue screened

**Comment by ChrisM-S** [comment]
Note that paths for the development MDT share were found in the production MDT share so it is likely that this cross linking and possible differences in the disk configurations may be the cause of the crash.  Documentation in note (3) above may need to be updated for generation of subsequent MDT servers from a clone.  The MDT console does provide the ability to copy task items between deployment shares so this may be a better way of generating a new share from an existing one.

**Comment by Tom-Willemsen** [comment]
impeded until meeting (20th Jan)

**Comment by Tom-Willemsen** [comment]
Meeting happened with input from @ChrisM-S @DominicOram @davidkeymer @FreddieAkeroyd @Kevin-Woods-Tessella and I.

Outcome of the meeting is to split the remaining work into the following tickets:
- https://github.com/ISISComputingGroup/IBEX/issues/6121
- https://github.com/ISISComputingGroup/IBEX/issues/6122
- https://github.com/ISISComputingGroup/IBEX/issues/6123
- https://github.com/ISISComputingGroup/IBEX/issues/6124
- https://github.com/ISISComputingGroup/IBEX/issues/6125
- https://github.com/ISISComputingGroup/IBEX/issues/6126

**Comment by kjwoodsISIS** [comment]
Created #6127 to act as an umbrella ticket - to provide an overview of what needs to be done and progress.

**Comment by DominicOram** [comment]
Happy that this matches what was discussed at the meeting.
