### ISSUE TITLE
Gateway: protect instrument from non-relevant name broadcasts

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5924]
The external gateway currently protects instruments from write access, but not from lots of unnecessary name lookups. This could affect performance of IOCs and block gateway if a large number of requests appear e.g. ndadetmon restarting and querying 3000 blocks across the facility on all instruments and any subsequent retries to look up non-available pvs   

For background see #5069 and #5893

## Acceptance criteria

* gateway file patched on instruments to discard non-local lookups
* instrument gateways restarted
  
## To test

* start gateways, check gwext_expanded.pvlist in instrumt/var/tmp looks sensible
* check instrument/developer machine pvs are still visible from another computer
* optional: run `caSnooper` before and after change and check traffic has reduced. `casnooper -t10 -p20` will print top 20 requests after running for 10 seconds, but you need to `set EPICS_CAS_INTF_ADDR_LIST=127.0.0.1` before running or else you will see traffic from the ISIS network as well as local loopback

**Comment by FreddieAkeroyd** [comment]
Installed on NDXDEMO, seem to still be able to read PV remotely, caSnooper output currently on screen
```
set EPICS_CAS_INTF_ADDR_LIST=127.0.0.1
caSnooper -t10 -p10

PVs with top 10 requests:
   1 NDXDEMO.isis.cclrc.ac.uk:62021 IN:DEMO:MOT:MTR2407.TDIR          0.10
   2 NDXDEMO.isis.cclrc.ac.uk:62021 IN:DEMO:MOT:MTR0807:IN_POSITION   0.10
   3 NDXDEMO.isis.cclrc.ac.uk:62021 IN:DEMO:MOT:MTR0904.DESC          0.10
   4 NDXDEMO.isis.cclrc.ac.uk:62021 IN:DEMO:MOT:MTR0701.ATHM          0.10
   5 NDXDEMO.isis.cclrc.ac.uk:62021 IN:DEMO:MOT:MTR1005.TDIR          0.10
```

**Comment by DominicOram** [comment]
`caSnooper` doesn't seem to be being built (https://github.com/ISISComputingGroup/EPICS-extensions/blob/807f7815654c09fa85aee4c5e37b8b564f9b6a14/src/Makefile#L80)? Even if I do get it building it fails with an error about finding `cas.dll`.

Regardless I think the change is good and have merged it. Acceptance criteria says to release it so I will leave this in review until that's been done.

**Comment by FreddieAkeroyd** [comment]
`caSnooper` does get built ... you just have to be patient :-) Since epics 7 `extensions` needs to be built in two passes, `regex` is needed early, but `caSnooper` requires `pcas` which was unbundled from epics base and is now a separate module in support. So first pass of extensions is a simple make that does not build caSnooper, it is build by the `postbuild` step of the top level Makefile https://github.com/ISISComputingGroup/EPICS/blob/f689f3f21085c56610fc3d1568707ef30d5a2f39/Makefile#L106 and config_env should set the right path for pcas for you https://github.com/ISISComputingGroup/EPICS/blob/f689f3f21085c56610fc3d1568707ef30d5a2f39/config_env.bat#L179 do you have an old config_env, or maybe not re-run it since updating ?

**Comment by FreddieAkeroyd** [comment]
We should probably put `caSnooper` into its own support module as multiple passes of extensions is a little confusing.

**Comment by DominicOram** [comment]
Ah, I was only running make in the extensions directory, assuming it was all I needed.

**Comment by FreddieAkeroyd** [comment]
Unfortunately not - you can either run `make extpost` at top level or `make` in the `caSnooper` subdirectory itself (which you did)

**Comment by FreddieAkeroyd** [comment]
Installed on ALF, CRISP and EMMA so far - needs new fiel copying and `start_gateways.bat` running

**Comment by DominicOram** [comment]
I'm putting this back into in progress for now, as that's what it really is.

**Comment by FreddieAkeroyd** [comment]
Given last week of cycle, I think I will stop deployment - change has been merged so will be in next release.
