### ISSUE TITLE
Build system: create architecture dependent dllPath.bat

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5926]
EPICS traditionally has created an `iocBoot` for each architecture, you may need a different `st.cmd` for example. We only have soft iocs, but use different compiler options, so we set `ARCH` in the iocBoot directory to be `$(EPICS_HOST_ARCH)`. The issue here is that `dllPath.bat` gets made once with the first architecture you see, bit doesn't get reset if you build another architecture. So if you reset your host arch with `config_env` and type `make` you get all the right files built, except that `dllPath.bat` will still point at your original architecture (unless you remember to rebuild it) and so you may end up testing the wrong architecture.

What would stop such issues is if a `dllpath-arch` file was created and used instead by `runIOC`  e.g. separate `dllPath-windows-x64.bat` and `dllPath-windows-x64-debug.bat` with runIOC using the appropriate one based on whatever EPICS_HOST_ARCH was set to at the time it was invoked.

## acceptance criteria

* `dllpath-arch` files created at build time
* runIOC.bat build script updated to use dllPath-arch instead of dllPath

## To test

* `make clean` and `make` in an `iocBoot` area, you should get a `dllPath-$(EPICS_HOST_ARCH)` file
* delete `dllPath.bat` and check `RunIoc.bat` still works

**Comment by DominicOram** [comment]
I've also just thought, we should update the `.gitignore` for other repos that have IOCs in them at least:
- [ ] ioc
- [ ] ISIS

I'll do it this afternoon as a flash review

**Comment by FreddieAkeroyd** [comment]
Thanks

**Comment by DominicOram** [comment]
I'll just do the IOC one as that's 90% of it.
