### ISSUE TITLE
Shared Instrument Scripts: Autoheight function

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5930]
The autoheight function should check the current height on the height gun and use this to reposition the trough height. Check with SURF exactly how this should be done.

### Accetpance Criteria

- Autoheight function works

**Comment by ThomasLohnert** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/88
https://github.com/ISISComputingGroup/IBEX/pull/6164

**Comment by ThomasLohnert** [comment]
There's some discussion amongst INTER scientists how errors reading the laser should be handled, moving into impeded until I have an answer.

**Comment by JamesKingWork** [comment]
Could the decision about how errors should be handled be written on to here or the wiki please?

**Comment by ThomasLohnert** [comment]
From scientists' email about error handling:

> a) Keyence returns NaN for whatever reason (eg. bad reflection)
> b) Keyence returns a value, which would make the height adjustment exceed the axis range (e.g. if an "autoheight()" is requested when the coarse height is at the height for the wrong angle)
>
> In my opinion, in both of these cases we should be able to define the behaviour, as Mario suggested: the user should have a choice to say: If Keyence returns either a NaN or a 'wrong' value, which cannot be corrected, then the script should either stop (and ideally email the user or raise an alert of some sort), or the script should continue with the last known value (i.e. without adjusting anything).
> Of course you could argue that in case 2b, continuing would almost certainly lead to a bad run, so we could try and distinguish between NaN and 'value too large'. I think we will need to refine this by using it.
