### ISSUE TITLE
IMAT (hardware): system failure

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5934]
The IMAT server appears to have crashed and is no longer bootable. No disks appear to be available when looking from the RAC so it looks like there is a problem with the disk adapter.  Trying a cold boot does not appear to have brought the disks on line again.

 **Acceptance Criteria** 
1) Hardware replaced (with new system)
2) Data disks moved from old server
3) DAEII reconnected and checked
4) VM replica restored as of 10:13 this morning
5) Networks connected up to DAE & ISIS
6) User informed

**Comment by ChrisM-S** [comment]
Machine is now back up with VM and running IBEX again.  Checked points 1-6.

Please would someone be kind enough to check that there are no logging issues from IBEX this time :-).

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd checked the logs
