### ISSUE TITLE
Script Generator: script definition locations for client

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5938]
As a maintainer or writer of script definitions, I would like the location of script definitions on a computer to be managed correctly for the script generator client.

This ticket is to investigate and document how they are currently stored and to standardise that storage.

Acceptance criteria:

- How script definitions are stored for a client is documented
- First the script generator looks in C:\Instrument\Settings... then next to the exe if the first is not present

on an external user machine there will only be "next to exe" 

Notes:

- Must work on an instrument and for external users

**Comment by JamesKingWork** [comment]
Ticket created as outcome of #5754

**Comment by kjwoodsISIS** [comment]
I think we need to be clear about where **_all_** script related files get stored.  And this needs to be done for both the Script Generator running on a remote users PC, or a cabin PC, and the Script Generator running on an instrument server (i.e. and NDX machine).

In other words, fill in this table.

File Type         | Description                                         | Location                 |
------------------|-----------------------------------------------------|--------------------------|
Script Definition | A template for creating scripts                     |Remote:  `C:\<DIR>\SUB-DIR\`  <br>Server: `C:\<DIR>\SUB-DIR\`    |
Script            | The structured script defining the specific actions | Remote: `<anywhere - user decides where to store these>` <br>Server:             |
Generated Script  | The Python script generated from the script.        | Remote: `<anywhere - user decides where to store these>` <br>Server:             |

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/ibex_gui/pull/1263
- https://github.com/ISISComputingGroup/IBEX/pull/6278
