### ISSUE TITLE
Pressure Reading on OSIRIS

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#5946]
As an instrument scientist on OSIRIS I want to be able to read the pressure from the Furnace.

## Acceptance Criteria
1. The appropriate pressure readings are available as blocks
1. Any aditional notes are added to wiki page https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Ral-furnaces

## Notes
1. This device has been used on GEM and POLARIS
1. It is actually composite device, part of which is a Turbotronik NT 10, the other part is a Pfeiffer vacuum gauge
1. That vacuum gauge most likely the TPG26X_01 that is referred to on both GEM (furnace pressure component) and POLARIS (eurotherms with barotrons component)
1. The cable was traced from the combined device to DS15, which was then traced to port 8 on the moxa ending .94, but the connection didn't seem to quite work (note that only COM port was checked not Baud etc.)
1. It may actually be on the moxa ending .194

**Comment by KathrynBaker** [comment]
Pointing at 2 as between the work already done, and the set up that is still needed that is probably fair. The IS on OSIRIS will call when there is a chance to undertake the setup.

I have not assigned myself as I don't want to inhibit anyone taking up the ticket when the call comes, but as we are waiting for access to the equipment I have placed into impeded.

**Comment by DominicOram** [comment]
This was the `TPG26X`. We failed to talk to it remotely due to DS15 actually being on the ISIS network, DS14 was port 8 / COM12. I swapped it to DS14 and added labels to the DS ports. Now communicating happily.
