### ISSUE TITLE
MuSR: Steering OPI 

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5949]
As a muon scientist using MuSR, I need to control the horizontal and vertical steering magnets, so that I can steer the muon beam.

#### Acceptance Criteria
1. IBEX provides a dedicated OPI to provide control of the two PSUs (both Kepcos) that power the horizontal and vertical steering magnets.
1. The MuSR Steering OPI should resemble the attached sketch: ![MuSR_Steering_OPI](https://user-images.githubusercontent.com/7249337/101491408-9afcd480-395b-11eb-9909-b053c1592cc4.png)
1. The OPI should display a title label:
   1. "MuSR Steering"
1. The OPI should display a row of labels, as follows:
   1. "Steering Magnet"
   1. "Constant Current Mode"
   1. "Current Setpoint"
   1. "Current Setpoint Readback"
   1. "Current Readback"
   1. "Current Voltage"
1. The OPI should display a row of fields labelled "Horizontal:", containing the following fields/controls (all relating to the horizontal steering magnet PSU):
   1. Constant Current Mode - a greed LED (lit if PSU is operating in CURRENT mode)
   1. Current Setpoint - display/edit field, units A, 3dp
   1. Current Setpoint Readback - display-only field, units A, 3dp
   1. Current Readback - display-only field, units A, 3dp
   1. Current Voltage - display-only field, units V, 3dp
1. The OPI should display a row of fields labelled "Vertical:", containing the following fields/controls (all relating to the vertical steering magnet PSU):
   1. Constant Current Mode - a greed LED (lit if PSU is operating in CURRENT mode)
   1. Current Setpoint - display/edit field, units A, 3dp
   1. Current Setpoint Readback - display-only field, units A, 3dp
   1. Current Readback - display-only field, units A, 3dp
   1. Current Voltage - display-only field, units V, 3dp
1. The OPI must provide a STOP button.
   1. ~On pressing the STOP button, IBEX should halt the change of the current to each PSU (i.e. stop increasing or decreasing towards the desired setpoints).~
   1. On pressing the STOP button, IBEX should switch off the current (same behaviour as the existing VI) .

#### Notes
1. The Kepco manuals (`\\isis\shares\Manuals\Kepco`) uses the terms "constant current mode" and "CURRENT mode" interchangably.
1. Check the Kepco manuals to check how to determine constant current mode.

**Comment by John-Holt-Tessella** [comment]
Thought at planning: 

1. Check how VI uses stop
2. Implement stop pv on each kepco, initial plan send rbv to sp (do not expose on OPI
3. Add record to insetc to trigger both stops

**Comment by rerpha** [comment]
- The STOP button in the VI sets the output to off and then stops the VI - In IBEX we probably don't want to stop the IOC
- We could instead have two buttons that are for turning both magnets off and on at the same time using the INSTETC record. 
- The ramping doesn't appear to be being done in the KEPCO VI

**Comment by John-Holt-Tessella** [comment]
This is weird why are the two definitions of stop so different:

1. VI - Turn magnets off
2. Requirements - stop ramping and keep magnets at the current current

I think we need to resolve this before writing code

**Comment by kjwoodsISIS** [comment]
No, it is not so weird.  It is a misunderstanding caused by the non-existent documentation of the VIs (requiring us to look inside each VI to understand what it does).  The scientists expect the IOC to behave the same way as the VI.  If the VI switches off the current, then the IOC should do the same thing.

**Comment by rerpha** [comment]
PRs: 
- GUI - https://github.com/ISISComputingGroup/ibex_gui/pull/1240
- release notes - https://github.com/ISISComputingGroup/IBEX/pull/6104

have created a record on custom_records.db for sending the "stop" to. This is on configs branch `Ticket5949_musr_steering`

**Comment by DominicOram** [comment]
FYI, I've added a note to check functionality with scientists on https://github.com/ISISComputingGroup/IBEX/issues/6112

**Comment by DominicOram** [comment]
- [ ] We will also need to merge this into the NDXMUSR config area, happy for you to do this or leave it up the reviewer. Either way, tick here when done

**Comment by rerpha** [comment]
Rework done, putting in impeded for now as we’re waiting on scientists response.

**Comment by rerpha** [comment]
No longer impeded as the save functionality will be done in https://github.com/ISISComputingGroup/IBEX/issues/6133 , putting this into review now.
