### ISSUE TITLE
convert config upgrade script to python3 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5954]
An install failed in the config upgrade step, the error I believe is due to the python3 based install script calls `misc/upgrade/upgrade.bat` which tries to use python 2 but will have PYTHONHOME etc pointing at python 3 files due to it being launched from a python 3 process environment, hence ends up loading site packages files with invalid python2 syntax.

## Acceptance criteria
* python files in misc/upgrade made pythin 3 complient
* upgrade completes without error

**Comment by FreddieAkeroyd** [comment]
The error is relayed to #5913 - I though fixing the quoting resolved it, but that was not the whole story

**Comment by John-Holt-Tessella** [comment]
Doing #4888 fixes this, so closing
