### ISSUE TITLE
MuSR: CAEN HV PSU Status

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5955]
As a muon scientist using MuSR I would like IBEX to display the status of my CAEN HV PSUs, so that I can easily check whether they are switched on or not.

#### Acceptance Criteria
1. The status of the CAEN HV PSU is displayed on the MuSR Rotation OPI.
1. The status of the CAEN HV PSU is displayed on the Banner on MuSR's instance of IBEX.

#### Notes
1. The purpose of this ticket is to provide a simple way for the scientists to check if the CAEN HV PSU is switched on or off.  MuSR must not be rotated when the CAEN HV is switched on.  If the scientists see that the CAEN HV PSU is switched on, they can (manually) switch it off before rotating the instrument (and they can manually switch it back on again after they have rotated the instrument).  There is no requirement for this switching on/off to be automated.

**Comment by Tom-Willemsen** [comment]
Needs to be a "slightly careful" logical or between a bunch of CAEN channels. One of the CAEN channels is already the overall status of the HV, so need to check the LabVIEW for details

**Comment by DominicOram** [comment]
Ok to use a hardcoded list of what channels to OR

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/ibex_gui/pull/1244 (see comments in PR)
https://github.com/ISISComputingGroup/IBEX/pull/6120
