### ISSUE TITLE
MuSR: King Fridge (uDR2) Configuration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5956]
As a muon scientist using MuSR I need a King fridge configuration in IBEX, so that I can perform low temperature experiments using my King fridge.

#### Acceptance Criteria
1. For high temperature experiments, I can control the temperature of the sample (via a Mercury temperature controller).
1. For low temperature experiments, I can control the temperature of the sample (via a Lakeshore temperature controller).
1. I can control the temperature of the mixing chamber in the dilution fridge (via the Triton controller).

#### Notes
1. For the avoidance of doubt, IBEX already has support for Triton, Lakeshore & Mercury devices.  This ticket is all about creating  configurations.
1. In the context of this ticket, high and low temperatures have the following meanings:
   * high temperature: T > 20K (in principle as high as 40K, but in practice the muon scientists treat 20K as the threshold)
   * low temperature: T < 20K (again, in principle the threshold could be as high as 40K, in practice it's 20K)
1. Background information on muon fridges is 
   * here: [MuSR Fridge Configurations](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/MuSR_Fridge_Configurations.docx)   and
   * here: [Fridge Schematic](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/Fridge_Schematic.pptx)
1.  The King Fridge is also known as the uDR2 Fridge.

**Comment by Tom-Willemsen** [comment]
Configs are on `NDXMUSR` branch of configs repo. Please let me know if you are going to push to this branch as #5971 is still in progress.

**Comment by John-Holt-Tessella** [comment]
Review:
- [ ] the original configs have ITC503s in should these be in the king configs? 

- [ ] Should there be a Temp_RuO2 block pointing at the lakeshore TSET
- [ ] Should there be blocks point at the triton (Temp_MC, Triton_P1, Triton_P2, Triton_P3, Triton_P5, Triton_Still_Temp, Triton_Sorb_Temp, Triton_4K_HX_Temp, Triton_JT_HX_Temp)
- [ ] Look like the ITC 503 should be configured with ComPort=5, ISOBusAddr=3??
- [ ] ITC PID tables from config copied to in LabVIEW Modules\Oxford Software\NewITCFrontPanel\ITC1PID.txt
- [X] We haven't easily been able to check tesletron setting but it won't communicate if they are wrong, leaving untill testing


low temp

- [ ] Triton blocks(Temp_MC, Triton_P1, Triton_P2, Triton_P3, Triton_P5, Triton_Still_Temp, Triton_Sorb_Temp, Triton_4K_HX_Temp, Triton_JT_HX_Temp)
- [ ]
