### ISSUE TITLE
MuSR: uDR3 & uDR4 Fridge Configurations

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5957]
As a muon scientist using MuSR I need uDR3 & uDR4 configurations in IBEX, so that I can perform low temperature experiments using the uDR3 & uDR4 fridges.

#### Acceptance Criteria
1. For high temperature experiments, I can control the temperature of the sample (via a Mercury temperature controller).
1. For low temperature experiments, I can control the temperature of the sample (via a Lakeshore temperature controller).
1. I can control the temperature of the mixing chamber in the dilution fridge (via the Triton controller).
1. I can control the temperature of the surrounding cryostat (via the Mercury temperature controller (the same one as above)).

#### Notes
1. For the avoidance of doubt, IBEX already has support for Triton, Lakeshore & Mercury devices.  This ticket is all about creating  configurations.
1. In the context of this ticket, high and low temperatures have the following meanings:
   * high temperature: T > 20K (in principle as high as 40K, but in practice the muon scientists treat 20K as the threshold)
   * low temperature: T < 20K (again, in principle the threshold could be as high as 40K, in practice it's 20K)
1. Background information on muon fridges is 
   * here: [MuSR Fridge Configurations](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/MuSR_Fridge_Configurations.docx)   and
   * here: [Fridge Schematic](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/Fridge_Schematic.pptx)

**Comment by Tom-Willemsen** [comment]
Configs are on `NDXMUSR` branch of configs repo. Please let me know if you are going to push to this branch as #5971 is still in progress.

Makes sense to review this with #5956

**Comment by DominicOram** [comment]
Are you still reviewing this @John-Holt-Tessella?

**Comment by rerpha** [comment]
We are part way through reviewing this, we have had a look at udr4 in low temp mode so high temp and udr3 still remains. there were some blocks missing so we will create those for each config however hardware testing will be done as part of #6198

**Comment by John-Holt-Tessella** [comment]
@DominicOram Sorry it is taking so long, I seem to have many other things to attend to and have got side tracked. We are almost done.

**Comment by DominicOram** [comment]
No problem, just wanted to make sure it wasn't forgotten about

**Comment by rerpha** [comment]
Have finished reviewing all the configs, needed to add some triton blocks such as `Temp_MC` and `Triton_Sorb_Temp` and so on to each.
