### ISSUE TITLE
MuSR: 3He Refrigerator Investigation [TIMEBOX for investigation: 1/2D] and implementation

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5959]
As a developer, I would like to investigate the existing LabVIEW solution for controlling the 3He Refrigerator (a Heliox/ITC-503 based system), so that I can assess the feasibility of using it in IBEX.

#### Acceptance Criteria
1. Talk to Muons to get a better understanding of their precise requirements 
1. The existing LabVIEW solution used to control the 3He Refrigerator used on MuSR is reviewed.
   * The LabVIEW solution is believed to be this: `C:\LabVIEW Modules\Oxford Software\Muon Heliox`
      * These are VIs written by Oxford Instruments (not written by ISIS)
1. Make a rough assessment of the effort required to convert the existing LabVIEW solution to EPICS.
1. Make a recommendation on how to proceed in the:
   * short-medium term (i.e. up to the end of Cycle 2020/04, which ends 26-03-2021)
   * long term (i.e. from the end of the TS-1 long shutdown, which ends 25-04-2022)
1. Implement a solution
   
#### Notes
1. This ticket requires someone with experience of LabVIEW.
1. Possibilities for future running of the 3He Refrigerator include:
   1. Run existing LabVIEW solution on NDXMUSR.  Create lvDCOM component to exchange data with LabVIEW.
   1. Run existing LabVIEW solution on a separate PC.  Again, use lvDCOM component to exchange data with LabVIEW.
   1. There may be others ...
1. Note from Cryogenics:
   * "Something I should also add now I’ve thought about it: The very same Heliox with ITC503 is also used on Neutron instruments (almost exclusively WISH actually) with what looks like the same Oxford Instruments VI."
 1. Note from Instrument Scientist (08-01-2021):
    * "As things are currently scheduled we’ll be using uSRi1, which is one of the Mercury-controlled Helioxes. If there were a problem with either the Heliox controlled inserts or the cryostat they use we would need to switch to the ITC503 controlled Heliox. 
To draw a footballing analogy, the Mercury controlled one is in the starting line-up but the ITC503 controlled one will be on the bench when the game starts."

**Comment by John-Holt-Tessella** [comment]
Also worth comparing it to the work in the current driver for the heliox https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mercury-Heliox  to see if we can just modify that driver.

**Comment by davidkeymer** [comment]
Current VI (`C:\LabVIEW Modules\Oxford Software\Muon Heliox\Muon Heliox Front Panel2.vi`) determined from SECI configurations.
Brief investigation of code revealed :
- Mostly consists of configuration and management of up to four ITC503s. 
- The setup VI (`C:\LabVIEW Modules\Oxford Software\Muon Heliox\MUON HELIOX SETUP DIALOG2.vi`) allows the Heliox to be configured and the ITC parameters to be set.
- Main VI contains logic to determine whether or not a recondense cycle is required.
- The recondense VI itself (`C:\LabVIEW Modules\Oxford Software\Muon Heliox\Muon Heliox Recondense2.vi`) contains a reasonable amount of code.

Suggest studying the Mercury Heliox driver and [Wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mercury-Heliox) and liasing with a representative from the Cryogenics team during this work.

**Comment by DominicOram** [comment]
Needs discussion when we talk about cycle change

**Comment by John-Holt-Tessella** [comment]
Plan is to spend time on ticket to do this as an EPICS driver and get rid of the labview. Make a start and see. Tom should not do this but is a good advisor.

**Comment by JamesKingWork** [comment]
# In discussion with @Tom-Willemsen the following was agreed

This ticket has become to create new tickets resulting from the investigation:

- Document VI control logic: https://github.com/ISISComputingGroup/IBEX/issues/6239
- Implement control logic: https://github.com/ISISComputingGroup/IBEX/issues/6240
- Communications: https://github.com/ISISComputingGroup/IBEX/issues/6241
- Machine setup: https://github.com/ISISComputingGroup/IBEX/issues/6242
- Testing on Device: https://github.com/ISISComputingGroup/IBEX/issues/6243

**Comment by KathrynBaker** [comment]
The tickets make some sense, but a ticket to track the moving parts is probably necessary as well, given the 6 new tickets that have been created. I've created that ticket (#6247) and assigned it to @JamesKingWork so that the responsibility can be maintained, and so that we don't lose any parts of the work before considering it complete.

**Comment by kjwoodsISIS** [comment]
@JamesKingWork  - does the 3 points include @davidkeymer 's initial investigation?

**Comment by JamesKingWork** [comment]
> @JamesKingWork - does the 3 points include @davidkeymer 's initial investigation?

Yes, but I have guessed David did about half a day on it, I don't know exactly how long he did spend. I did about half a day and the review, I imagine, was very quick.

**Comment by FreddieAkeroyd** [comment]
Does this ticket need release notes or should it be marked "support" to avoid the release notes check error?

**Comment by John-Holt-Tessella** [comment]
My feeling is most tickets should have release notes. They indicate to the scientists the work we are doing as well as what has changed with IBEX, both from code and configuration point of view.
