### ISSUE TITLE
CAEN: Deploy new IOC to DETMON

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5962]
As a member of the detector group I  would like all the new features that come with the new CAEN IOC (see https://github.com/ISISComputingGroup/IBEX/issues/5544). As such I would like it deployed on DETMON.

## Acceptance Criteria

* The new CAEN IOC is deployed on DETMON
* It is run alongside the old IOC, pointing at additional crates
* New IOC values are checked to match against old IOC values (script available in DETMON config area to do so)

**Comment by JamesKingWork** [comment]
Deploy it as read-only if possible

**Comment by JamesKingWork** [comment]
Closing as covered by https://github.com/ISISComputingGroup/IBEX/issues/6158
