### ISSUE TITLE
Script Generator: Estimate Measurement Duration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5964]
As a user, I would like the Script Generator to provide an estimate of the duration of a measurement, based on a rate that I provide.

#### Acceptance Criteria
1. I can provide a rate for each measurement in my script.
1. The Script Generator calculates an estimated duration for each measurement

#### Notes
1. This feature is particularly requested by the muons group.  The old script generator had this facility.

**Comment by John-Holt-Tessella** [comment]
How is this different from the estimated time facility?

**Comment by kjwoodsISIS** [comment]
It probably isn't.  When I looked for ticket with a "estimated time facility", I couldn't find one - most likely I just missed it.

**Comment by John-Holt-Tessella** [comment]
I believe it is already implemented

**Comment by kjwoodsISIS** [comment]
Well, that's interesting!  The muons don't seem to know about it.

**Comment by John-Holt-Tessella** [comment]
In which case maybe we should change this ticket to let the muons know they can use time estimates in there scripts.

**Comment by DominicOram** [comment]
I think the issue is actually https://github.com/ISISComputingGroup/IBEX/issues/5616. The time estimation does not work for them  because they need to set a global rate for the whole script. I believe we can close this ticket in favour of proposing #5616

**Comment by JamesKingWork** [comment]
When it says "I can provide a rate" does it mean the user can provide a rate or it is provided by the script definition?

**Comment by DominicOram** [comment]
The user. They want a box at the top of the view that they put a constant in and this constant will then be used by every line of the script to do the time estimation

**Comment by John-Holt-Tessella** [comment]
Is it ok to close this for the more general #5616?

**Comment by kjwoodsISIS** [comment]
Closed as a duplicate of #5616.
