### ISSUE TITLE
Script Generator: Copy/Paste Segments of Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5965]
As a user, I would like to copy/paste segments of scripts, so that I can easily build up scripts that perform a series of similar actions.

#### Acceptance Criteria
1. I can copy one contiguous or more lines of a script.
1. I can paste the copied lines to any other point in the script.
   * I can insert the copied lines at the top of my script (i.e. above line 1)
   * I can insert the copied lines in the middle of my script (i.e. at any point after line 1 and before the final line)
   * I can insert the copied lines at the end of my script (i.e. after the final line)

#### Notes
1. This feature is particularly requested by the muons group.  Copy/pasting blocks of script is one of the the things they do most frequently.

**Comment by JamesKingWork** [comment]
Current methods:

- Select line to duplicate, click duplicate action (inserted line below the action you are duplicating), move action by clicking on up and down buttons to the right of the action table
- Select multiple lines to duplicate, click duplicate action (all inserted in order together in the line below the last action in the table you are duplicating), the focus then moves to the first duplicate action so you must then select one or multiple actions you wish to move and move them by clicking on up and down buttons to the right of the action table

Drawbacks:

- Requires a lot of clicking
- Focus goes to single action even if you have duplicated multiple
- Workflow is not a pure copy/paste workflow
- You cannot insert the line at any point in the action table directly (you have to move the line)

Ideas:

- Keyboard shortcut to move actions up and down the table and to duplicate an action (should be documented clearly at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Using-the-Script-Generator)
- Remove duplicate action workflow and replace with a copy/paste workflow
- Modify the duplicate action workflow to insert lines at a given point in the action table
- When duplicating multiple actions do not set focus to the first duplicated action, select all the duplicated actions

**Comment by JamesKingWork** [comment]
After a meeting with the scientists, this is unlikely to be solved with a duplicate action workflow. I suggest we additionally add the ability to copy one or more lines and then select a line to paste them below. The buttons should be labelled well e.g. "Copy Lines" and "Paste Below".

**Comment by John-Holt-Tessella** [comment]
Don't forget edge case when change script definition
Make sure it is a deep copy of arguments so that you can copy, edit lines and paste original values

**Comment by JamesKingWork** [comment]
See https://javadoc.scijava.org/Eclipse/org/eclipse/swt/dnd/Clipboard.html for setContent storing as comma separated values. Consider what happens when you change script definition and thus columns (probably clear clipboard contents).
