### ISSUE TITLE
Script Generator: Insert Lines into Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5966]
As a user, I find the current method of inserting lines into a script to be unintuitive.  Can it be made more intuitive?

#### Acceptance Criteria
1. Review how lines are currently inserted into scripts.
1. Meet with scientists to discover what they find unintuitive.
1. Modify the existing method of inserting lines into scripts accordingly.

#### Notes
1. This feature is particularly requested by the muons group.

**Comment by JamesKingWork** [comment]
Current methods:

Add action method:

- Click "Add Action" button in action control toolbar
- Click on last action in action table, press tab until a new action is created on the next line
- Drawback: Method only adds actions to bottom of action table

Duplicate action method:

- Click on the line you would like to insert action after, click duplicate action in action control toolbar
- Drawback: duplicates action

Ideas:

- On clicking add action, insert it into the line below the one currently with focus or if no focus is given onto the end
- Keyboard shortcut to add action e.g. shift-a or shift-n or shift-tab (reduces clicking required, this should also insert the new line below the current focus or add to the end if no focus)
- Say you are focused on line 3 of 5 when you tab onto the next line should it insert a line or give focus to line 4?
- Document the ability to tab onto a new line (https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Using-the-Script-Generator)

**Comment by JamesKingWork** [comment]
This seems to be a problem with how the buttons are labelled "Add Action" and "Duplicate Action" are not descriptive of the actual behaviour. A solution seems to be to correctly label the buttons e.g. "Add Action To End", "Duplicate Action Below" and to add another button "Insert Action Below".

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/ibex_gui/pull/1227
- https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/81/files
