### ISSUE TITLE
Script Generator: Delete Specific Lines from Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5967]
As a user, I find the current method of deleting specific lines from a script to be unintuitive.  Can it be made more intuitive?

#### Acceptance Criteria
1. Review how lines are currently deleted from scripts.
1. Meet with scientists to discover what they find unintuitive.
1. Modify the existing method of deleting lines into scripts accordingly.

#### Notes
1. This feature is particularly requested by the muons group.

**Comment by JamesKingWork** [comment]
Current method: click on line to correctly get focus, press delete action button in action control toolbar

**Comment by JamesKingWork** [comment]
Scientists were not aware you could select multiple lines to delete in one go. This is an issue with making the user aware of how to do this. Keyboard shortcuts such as selecting multiple lines should be made obvious. I believe that we need to improve the layout and conciseness of the documentation and ensure that undocumented features such as these are documented:

- Keyboard shortcuts should be linked on the script generator
- Documentation should be restructured (currently there is a lot of test and it is not easy to find what you want to find)

They are now less concerned about this issue though think the following to changes would improve the usability further:

- Currently, after deleting an action the focus is lost. The focus should be put on the next action, or if the last action was deleted the new last action.
- A keyboard shortcut to delete the selected lines (this should be clearly documented).

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1328
