### ISSUE TITLE
Script Generator: New Line should inherit Counts from Previous Line

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5968]
As a user, I would like the counts field to inherit its value from the previous line, so that I don't have to keep changing the same default value.

#### Acceptance Criteria
1. In a new line, the counts field should default to the value used in the previous line.

#### Notes
1. This feature is particularly requested by the muons group.

**Comment by rerpha** [comment]
PRs: 
- https://github.com/ISISComputingGroup/ibex_gui/pull/1223
- https://github.com/ISISComputingGroup/genie_python/pull/299

To test: 
1. Add a script that imports CopyPreviousRow from genie python script generator utilities * 
1. Add an action in the script generator and make sure it gets given the default value
1. Change this value to something like 1234
1. Add another action and make sure it copies the previous row's action value (whatever you changed it to)

* For example like this one from EMU: 

```python
from genie_python.genie_script_generator import ScriptDefinition, cast_parameters_to, CopyPreviousRow

class DoRun(ScriptDefinition):
    @cast_parameters_to(temperature=float_or_keep, field=float_or_keep, mevents=int, magnet_device=magnet_device_type)
    def run(self, temperature=CopyPreviousRow(1.0), field=1.0, mevents=10, magnet_device="N/A"):
       ...
```

**Comment by rerpha** [comment]
As discussed we should add a squish test to system test this functionality.

**Comment by JamesKingWork** [comment]
Testing PR: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/80
