### ISSUE TITLE
Script Generator: Display Location of Saved Parameters File

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5969]
As a user, I would like the Script Generator to display the location of the saved parameters file, so that it is obvious to me where the parameters file has been saved.
**N.B.**  This feature is intended to be analogous to the way in which many text editors display the name of the saved file in the window title bar.

#### Acceptance Criteria
1. The Script Generator displays the name of the saved parameters filein an obvious location (e.g. in the window title bar, or just below the menu bar).

#### Notes
1. This feature is particularly requested by the muons group.  
1. Here is an example of how the TextPad editor displays the name of a file: ![TP_Document_Saved](https://user-images.githubusercontent.com/7249337/101886521-860a8600-3b93-11eb-99ae-10758aa367ef.png)

**Comment by kjwoodsISIS** [comment]
Notepad++ does something similar to TextPad:
![NPpp_Document_Saved](https://user-images.githubusercontent.com/7249337/101888131-ac312580-3b95-11eb-9c8d-8536f62cd2ac.png)

**Comment by DominicOram** [comment]
Eclipse has an concept of this internally where you flag editors as `dirty`, we may be able to use this or maybe not.

**Comment by DominicOram** [comment]
Similar to https://github.com/ISISComputingGroup/IBEX/issues/5970 is this location of script or of last saved parameters?

**Comment by DominicOram** [comment]
In meeting on 29/01/21 with @Kevin-Woods-Tessella, @Tom-Willemsen, @John-Holt-Tessella and @JamesKingWork it was decided that this will only relate to the parameters file.

**Comment by kjwoodsISIS** [comment]
OK.  Here are two alternatives for displaying the name of the parameter file being edited (and showing alternative button arrangements).  I am happy with either.
**Option 1:**
![Script_Gen_UI_with_alternative_buttons_option_1](https://user-images.githubusercontent.com/7249337/106744688-fe337c00-6617-11eb-8a5c-0ff41eeacbd8.png)

**Option 2:**
![Script_Gen_UI_with_alternative_buttons_option_2](https://user-images.githubusercontent.com/7249337/106744708-04c1f380-6618-11eb-942d-e86736c1212d.png)

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1250
