### ISSUE TITLE
Script Generator: Indicate if a Parameter File is Unsaved

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5970]
As a user, I would like the Script Generator to provide an indication that a parameter file has not been saved (since it was last modified), so that it is obvious to me that the parameter file needs to be saved.
**N.B.**  This feature is intended to be analogous to the way in which many text editors append an asterisk to the string that displays the name of an unsaved file in the window bar (see examples below).

#### Acceptance Criteria
1. The Script Generator displays an indication that the parameter file has not been saved (since it was last modified).

#### Notes
1. This feature is particularly requested by the muons group.  
1. Here are 4 examples.  In these examples, the TextPad editor displays the name of the file in the title bar.  If the file has been modified but not saved, it appends an asterisk to the text string displayed in the title bar.
   1. New document, no content: <br> ![TP_New_Document](https://user-images.githubusercontent.com/7249337/101887091-4db77780-3b94-11eb-8ea5-de280a4b786d.png)
   1. New document, unsaved content: <br> ![TP_New_Document_Unsaved](https://user-images.githubusercontent.com/7249337/101887183-6758bf00-3b94-11eb-95da-87ab1902f767.png)
   1. Existing document, no unsaved modifications: <br> ![TP_Document_Saved](https://user-images.githubusercontent.com/7249337/101887212-72135400-3b94-11eb-8a15-fa689c4da6af.png)
   1. Existing document, unsaved modifications: <br> ![TP_Document_Modified](https://user-images.githubusercontent.com/7249337/101887246-7f304300-3b94-11eb-9fa5-db3ba2909de6.png)

**Comment by kjwoodsISIS** [comment]
Notepad++ does something similar to TextPad (Notepad++ prefixes the asterisk, TextPad postfixes the asterisk).
![NPpp_Document_Modified](https://user-images.githubusercontent.com/7249337/101888286-d5ea4c80-3b95-11eb-8617-9646b29b0b70.png)

**Comment by DominicOram** [comment]
We first need a discussion/email? with the instrument scientists to decide what they mean by this, along with https://github.com/ISISComputingGroup/IBEX/issues/5969. In a text editor this is easy as there is one file that you are editing and can be compared against. In the script generator you are not editing a file, you are generating one but you can also save parameters. Should this ticket be:
* What you have on the screen has modifications compared to the last saved parameters
* What you have on the screen has modifications compared to the last generated script

**Comment by DominicOram** [comment]
In meeting on 29/01/21 with @Kevin-Woods-Tessella, @Tom-Willemsen, @John-Holt-Tessella and @JamesKingWork it was decided that this will only relate to the parameters file.

**Comment by kjwoodsISIS** [comment]
At the meeting (see above) we agreed:
1. The Script Parameters file is (in effect) the "native" file format for the Script Generator. (you could argue that this is not strictly true, but for all practical purposes it might as well be).
2. We might need to explain carefully to scientists & users the distinction between Script Definition files, Script Parameters files and generated script files.
3. The UI should be modified to:
   1. indicate that the Script Parameters file has changed since it was last saved (we can use a "dirty" flag for this purpose).
   2. display the full path and name of the Script Parameters file

Attached is a mockup of how the UI might appear using smaller, icon buttons, rather than long, wordy button names.  The mockup also show how the name of the file and an indicator that the file has not been saved (since last modified) might appear.

![Script_Gen_UI_with_FileName_and_Icons](https://user-images.githubusercontent.com/7249337/106625023-2f577200-656e-11eb-8b46-71548c327070.png)

The icons are, from left to right:
   * Load Parameters
   * Save Parameters
   * Save Parameters As
   * Generate Script
   * Add Action to End
   * Insert Action Below
   * Delete Selected Action
   * Clear All Actions

**Comment by John-Holt-Tessella** [comment]
I think we suggested that the adding of icons and rearranging of the screen should wait for #6155 for now I would be happy to either add an extra save as button or allow the save button to have a arrow to allow for save and save as eg 
![image](https://user-images.githubusercontent.com/7570055/106723897-7e99b300-65ff-11eb-93c0-9aa9aefac4d8.png)

**Comment by kjwoodsISIS** [comment]
OK.  Here are two alternatives for simpler buttons (and showing if the file needs to be saved).  I am happy with either.
**Option 1:**
![Script_Gen_UI_with_alternative_buttons_option_1](https://user-images.githubusercontent.com/7249337/106744688-fe337c00-6617-11eb-8a5c-0ff41eeacbd8.png)

**Option 2:**
![Script_Gen_UI_with_alternative_buttons_option_2](https://user-images.githubusercontent.com/7249337/106744708-04c1f380-6618-11eb-942d-e86736c1212d.png)

**Comment by DominicOram** [comment]
Eclipse does have a concept of whether something is "dirty" check if this is useful

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1250
