### ISSUE TITLE
MusR: Migrate to IBEX 

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5971]
As a developer, I want to migrate MuSR to use the IBEX instrument control system.  As a scientist, I want MuSR to be migrated to IBEX in time for the start of Cycle 2020/04.

#### Acceptance Criteria
1. IBEX is installed on MuSR
   1. The IBEX server boot script is installed (see [IBEX auto-startup](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup))
1. MuSR is added to the list of available instruments
1. Configuration files matching the current SECI config files are created 
1. IBEX is configured for the devices on MuSR.
1. MuSR scripts are converted to genie_python
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   * MuSR scripts are likely to be very similar (if not identical) to EMU's scripts
1. IBEX is tested on MuSR

#### Notes
1. The devices on MuSR are listed on the [MuSR Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/MuSR-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for MuSR.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   - Requested (11-12-2020) (Footprints Issue: FIT-28275).  Two private ports have been requested.
   - Done (23-12-2020)
   - [MuSR VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/MuSR_VLAN_Settings.txt)
- [x] Check that NDXMUSR has sufficient disk space to install IBEX
  * MuSR has 30Gb of free space.
- [x] Check whether MuSR uses 5- or 8- digit run-numbers
   - [x] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [ ] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXMUSRTEST.
   - [ ] create IBEX configurations to correspond to their SECI equivalents
   - [ ] create genie-python scripts to correspond to their Open-Genie equivalents
      * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [ ] test these configurations & scripts
   - [ ] check that all the devices previously supported by SECI (on MuSR) are supported by IBEX.

**Comment by Tom-Willemsen** [comment]
Have checked with Peter, and it is ok to deploy onto MuSR this week. Instrument is currently in a safe state.

**Comment by Tom-Willemsen** [comment]
Requires https://github.com/ISISComputingGroup/IBEX/issues/6148 to continue (have pulled that ticket into the sprint, Jack and I are working on it)

**Comment by rerpha** [comment]
All builds from 7.3.0 are passing so tomorrow we’ll carry on setting ibex up on MuSR.

**Comment by rerpha** [comment]
- Had to hotfix the steering OPI - https://github.com/ISISComputingGroup/ibex_gui/pull/1247 
- Muon Jaws aren't working - the underlying VI is unhappy, we think this is probably because the Galil is powered off. 
- Checked that all 5 of the KEPCOs can read data
- Checked that the Danfysik can read data (unable to set fields at the moment due to an interlock - this is expected)
- Checked that the Thurlby can read data
- Checked that the Zero Field Magnetometer is giving some readings
-

**Comment by DominicOram** [comment]
As you are currently doing some preliminary testing make sure that https://github.com/ISISComputingGroup/IBEX/issues/6112 is kept up to date.

**Comment by rerpha** [comment]
Notes for musr meeting 

- Tick all boxes on caen opi to show all detectors - maybe we should add functionality to do this with a button in the future 
- Need voltage set points and current limit to be shown for each detector 
- Button to switch all channels on/off would be helpful 
- Board addresses for detectors - board and channel would be helpful in caen opi 
- old front panel they were using was MUSR CAEN - system - front panel 
- Slew rate still needs to be investigated
- Voltage soft limits for steering kepcos - we should put these on 
- Rotation opi looks good 
- Thurlby looks good 
- Individual steering opi is good 
- Still need to test x/y/z and figure out the correct conventions 
- Offsets will need to be checked according to above - probably need to use external magnetometer which is already hooked up to a control box in the cabin - need to try this in longitudinal as well as transverse to calibrate properly
- Will need to fake some events to see if counts are working, or use muons that are coming down from the sky to see if it’s picking them up 

- some of the scripts require someone on the beam line to manually rotate and so will ZF calibration 
- Wednesday afternoon and Thursday next week Peter says he could be on site for this, and possibly Friday morning, Mark will be going in anyway before Wednesday so he’ll see if the interlock can be cleared to test the danfysik properly, we’ll need to get software limit for this 
- May need to use a hall probe to calibrate the danfysik like on emu 
- Mark can do Monday to turn instrument around 
- Still need to test the various temperature components - cryostat is connected - we probably don’t need onsite presence for that 
- Need to test king fridge communication with triton as it differs from EMU 
- boost script might not be the same as EMU - need to test it 
-

**Comment by rerpha** [comment]
Synoptics: I have created all but the udr3&4(High and low) Synoptics, will continue tomorrow.

**Comment by rerpha** [comment]
Testing still remains to be done but will be done as part of #6112 instead. Putting this in review now as all configs that need to exist do now exist with associated synoptics where applicable.

**Comment by rerpha** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6166
