### ISSUE TITLE
Muons: Ask Instrument Scientists to Document Tracebacks

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5975]
The IBEX script console sometimes displays error tracebacks.  Users find these very disconcerting and they don't know what to do about them.  Can they be handled better by IBEX (e.g. diverted to a log, rather than the console).

#### Acceptance Criteria
1. Discuss with instrument scientists to find out the exact tracebacks they are concerned about
2. Decide how we mitigate these e.g. fix the underlying issues, divert to a log etc.

#### Notes
1. It may be the some scientists like seeing the tracebacks, others don't.  Could we create an option to suppress the display (but no the logging) of tracebacks.
1. Feedback from SAG meeting: "Peter commented that the Python traceback on script errors has proven confusing to users on occasion, and asked whether this could be improved."

**Comment by ThomasLohnert** [comment]
The tracebacks may be correct, offer to help the scientists fix their scripts.

**Comment by Tom-Willemsen** [comment]
Has now been explained to Peter from muon group. @rerpha is a witness

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6197
