### ISSUE TITLE
R55 Machines shutdown: (South) Power testing (Start 19th December)

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#5977]
4th to 15th January - electrical isolations will be required for, 

EMU – MUSR –HIFI – HRDP – ENGIN-X – GEM –PEARL- MERLIN – MARI –VESUVIO – SXD – MAPS.

EMU – MUSR were already tested so not needed to be isolated in the end

**Comment by ChrisM-S** [comment]
- [ ] •        HIFI
  - [ ] •        HRPD
  - [ ] •        ENGIN-X
  - [ ] •        ENGINX_SETUP
  - [ ] •        GEM
  - [ ] •        PEARL
  - [ ] •        PEARL_SETUP
  - [ ] •        MERLIN
  - [ ] •        MARI
  - [ ] •        NDEMUONFE
  - [ ] •        VESUVIO
  - [ ] •        SXD
  - [ ] •        MAPS

**Comment by ChrisM-S** [comment]
Machines shutdown, will disconnect cables tomorrow.

**Comment by ChrisM-S** [comment]
All machines unplugged and cables kept using Velcro retainers where possible next to the holes they came from.

**Comment by John-Holt-Tessella** [comment]
No machines ping, looks good

**Comment by ChrisM-S** [comment]
These are all going now as far as I can tell.  Machines, MOXAs, and Daxtens
