### ISSUE TITLE
Long Shutdown: Overview

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5979]
As a member of the ISIS Experiment Controls team, I want to be able to keep track of work being done on each instrument during the long shutdown (from ~April~ June 2021 to ~March~ September 2022).
   *  [Crystallography](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759583785)
   *  [Disordered Materials](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759584068)
   *  [Excitations](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759584688)
   *  [Molecular Spectroscopy](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759584324 )
   *  [Muons](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759585741)
   *  [Reflectometers](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759585411)
   *  [RIKEN](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759586505)
   *  [SANS](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759585097)
   *  [Other](https://github.com/ISISComputingGroup/IBEX/issues/5979#issuecomment-759586784)

At the time of creation (December 2020), this tickets notes known engineering work and expected migrations & support work.  It is highly likely that circumstances will change as the long shutdown progresses.  This ticket needs to be regularly updated throughout the long shutdown, to take account of changing circumstances.

**Comment by kjwoodsISIS** [comment]
### Disordered Materials
#### NIMROD
* No engineering work planned during long shutdown
* Support: 
   1. integrate neutron camera into IBEX (see #6094, #6095).

#### SANDALS
* Planned engineering work:
   1. New chopper (#6096)
   1. New jaws (#6097 )
   1. Upgrade sample changer (#6098)
* Support:
   1. update IBEX to support new chopper, jaws & sample changer (see #6096, #6097, #6098).

**Comment by kjwoodsISIS** [comment]
### Molecular Spectroscopy
#### IRIS 
* No engineering work planned during long shutdown

#### IRIS_SETUP 
* No engineering work planned during long shutdown

#### OSIRIS
* Planned engineering work:
   1. Silicon analyser upgrade (not certain if this will proceed)
* Support:
   1. update IBEX to support upgraded Silicon analyser (if it goes ahead).

#### TOSCA
* Planned engineering work:
   1. TOSCA Cold Head replacement
* Support:
   1. Strong desire to get TOSCA sample changer working (see #6101).
   1. Find out if cold head replacement impacts IBEX.

#### VESUVIO
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

**Comment by kjwoodsISIS** [comment]
### Excitations
#### LET
* Planned engineering work:
   1. Chopper 1 to be replaced by SKF chopper (similar to existing chopper 5)
* Support:
   1. update IBEX to support new SKF chopper (see #6099).

#### MAPS
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### MARI
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### MERLIN
* Planned engineering work:
   1. Existing Julich Fermi chopper to be replaced by new SKF Fermi chopper
* Support
   1. update IBEX to support new SKF Fermi chopper.

**Comment by kjwoodsISIS** [comment]
### SANS
#### LOQ
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### LARMOR
* Planned engineering work:
   1. Replace bench motor controller with a Beckhoff
   1. Absolute encoder will be installed on the bench

#### SANS2D
* Planned engineering work:
   1. Replace Baldor amplifiers
* Migration: complete migration of SANS2D to IBEX

#### ZOOM
* Planned engineering work:
   1. Replace snout.  Not expected to impact IBEX.
* Support: no special IBEX development anticipated.

**Comment by kjwoodsISIS** [comment]
### Reflectometers 
#### CRISP
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### INTER
* Planned engineering work:
   1. New secondary flight path
* Support:
   1. Update IBEX to support new secondary flight path.
   1. Continue updating reflectometry IOC in light of feedback.

#### OFFSPEC
* No engineering work planned during long shutdown
* Migration: migrate OFFSPEC to IBEX

#### POLREF
* No engineering work planned during long shutdown
* Support:
   1. Continue updating reflectometry IOC in light of feedback.

#### SURF
* Planned engineering work:
   1. Engineering work is planned, but no details so far
* Support:
   1. Update IBEX to support SURF upgrade (when we find out what is planned).

**Comment by kjwoodsISIS** [comment]
### Muons 
#### MUONFE
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### EMU
* No engineering work planned during long shutdown
* Support:
   1. complete implementation of support for all SE devices

#### MUSR
* No engineering work planned during long shutdown
* Support:
   1. complete implementation of support for all SE devices

#### HIFI 
* Planned engineering work:
   1. HIFI magnet is being re-furbished (see [HIFI CRYOMAG](#hifi-cryomag))
* Migration: migrate HIFI to IBEX (see #6092)

#### HIFI CRYOMAG
* Planned engineering work:
   1. HIFI magnet is being re-furbished (off-site).  Re-commission when it returns.

**Comment by kjwoodsISIS** [comment]
#### RIKENFE
* Planned engineering work:
   1. Refurbishment of the RIKEN beamline (new power supplies, new PLCs)

**Comment by kjwoodsISIS** [comment]
### Other 
#### ALF
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### CHIPIR 
* Planned engineering work:
   1. compressed air (may not impact IBEX)
   1. jaws and collimator repair
   1. shutter/filter set
   1. PPS installation (may not impact IBEX)
* Migration: migrate CHIPIR to IBEX
* Support: no special IBEX development anticipated.

#### DETMON
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### EMMA
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### SELAB
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

#### SOFTMAT
* No engineering work planned during long shutdown
* Support: no special IBEX development anticipated.

**Comment by kjwoodsISIS** [comment]
### Sample Environment
#### Chopper Group
* Planned equipment work
   1. New chopper on [LET](#let)
   1. New Fermi chopper on [MERLIN](#merlin)
   1. New chopper on [SANDALS ](#sandals)

#### Cryogenics
* Planned equipment work
   1. HTS Magnet (may be complete before long shutdown)
   1. 14T Magnet may be repaired during long shutdown.  If it is repaired, its control will need to be reviewed (expected to be similar to 9T magnet).  Could impact [WISH](#wish)
   1. Helium Recovery Monitoring
   1. New cryostat controller (no details as yet)
   1. Remote re-start of gas handling on Triton
   1. Replacement of ITC-503 by Mercury

#### Electronics
* Planned equipment work
   1. Baldor amplifier replacement (see [SANS2D](#sans2d))
   1. New jaws & sample changer on [SANDALS ](#sandals)

#### Pressure & Furnaces
* Planned equipment work
   1. Yet to be advised of any plans

#### Soft Matter
* Planned equipment work
   1. Yet to be advised of any plans

**Comment by KathrynBaker** [comment]
The long shutdown is over enough that is no longer worth considering as a useful ticket.
