### ISSUE TITLE
Web dashboard: Cannot connect on safari

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5980]
As a larmor instrument scientist I would like to be able to see the web dashboard from my mac. Currently I am able to see data on
http://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=larmor but not on http://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=Larmor.

## Acceptance Criteria
* The user is able to load the webpage regardless of the casing of the link

**Comment by DominicOram** [comment]
Maybe a caching issue? I'm having a zoom call with the user tomorrow to investigate

**Comment by DominicOram** [comment]
web dashboard issues have also been reported by EMU over the last few days, may be related

**Comment by DominicOram** [comment]
Showed the user how to clear the cache, that fixed it.

**Comment by John-Holt-Tessella** [comment]
Added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Other-Troubleshooting#instrument-page-not-working-on-web-dashboard
