### ISSUE TITLE
Check cachannel build

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5982]
As a developer I would like the fix applied after #5886 to be in the epics dlls used

## acceptance criterial

- updated epics distribution used
- tests pass

## to test

- run ususal python build + tests
- confirm removing old files as mentioned on PR does not affect build

**Comment by FreddieAkeroyd** [comment]
Note:
* The pip installed `pcaspy` includes its own bundled EPICS, this only affects `CaChannel`
* A pip installed `CaChannel` also includes its own epics, but we wish to call `eltc` to reduce error messages so use our own EPICS distribution

**Comment by rerpha** [comment]
whoops, sorry, didn't mean to move into in progress
