### ISSUE TITLE
Shared Instrument Scripts: Get instrument scripts all up-to-date with master

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5983]
As a supported I would like the instrument scripts to be up-to-date with each other.

### Acceptance Criteria

- All scripts on all instruments are the same
- Test created in #5907 passes

### Notes

- Instrument scientists may need to be contacted if there are large differences in their local scripts.

**Comment by FreddieAkeroyd** [comment]
put existing work on a branch to allow easy revert

**Comment by GRyall** [comment]
overtaken by more recent work, see e.g. #7914.
