### ISSUE TITLE
nagios: move to new server

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5984]
As a developer I would like the nagios server to move to a new VM with a maintained O/S. There are plans to move from nagios to a new tools, but this is likely to happen in the long shutdown. However a new server VM is already in place for the new server, so it shouldn't be too difficult to just move the varanus installation over to the new server - this may alsoi be useful for when it is migrated.

## acceptance criteria

* nagios config files moved from varanus to new control-mon VM

**Comment by DominicOram** [comment]
Document (at least) some basic things as part of this e.g. where is the server? What credentials are required to get into it?

**Comment by FreddieAkeroyd** [comment]
Brought into sprint as needed to decommission old server rapidly

**Comment by FreddieAkeroyd** [comment]
See nagios server docs in https://www.facilities.rl.ac.uk/isis/computing/instruments/Instrument%20Documents/Forms/AllItems.aspx
