### ISSUE TITLE
SCANS: Customise initial minimum and maximum scaling of  the graph

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5985]
As a user I would like the minimum and maximum y to be included on the graph to be configurable; currently it just sues the min and max values or +-0.05 if there are no points. The specific use case is that I want all my plots to include 0 in the scale. This is so that when I look at a graph I can more easily see that I am on a high plateau and not in the noise.

### Acceptance Criteria

- The plot functions configuration object has a high and low graph setting (call these something sensible)
- When the high/low graph setting is set this value is in the graph y range (the extreme may be this point or the extreme from the data)

### Notes

- I think that if the range is set to the low point/highpoint that the range should start from that point and not include 5% of the data range as it does for the lowest/highest point, but check this looks nice.
- Code to alter is here https://github.com/ISISNeutronMuon/InstrumentScripts/blob/master/general/scans/plot_functions.py#L93

**Comment by DominicOram** [comment]
Is it possible to get the user the user that requested this to make the change themselves?

**Comment by Tom-Willemsen** [comment]
Graphing is different in new bluesky scans library. Best to collect feedback for the new library separately, and create a new issue there if this appears in feedback.
