### ISSUE TITLE
NIMROD: Neutron Camera Motion

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5988]
As a NIMROD scientist, I want to be able to move my neutron camera in/out of the beam, so that I can use it to capture images.

#### Acceptance Criteria
1. Using the IBEX client, I can move my camera in/out of the beam.
1. Using genie_python, I can move my camera in/out of the beam.
1. ~Collection of normal neutron data is vetoed when the camera is in the beam.~ We/the scientists will set this up when actually using it

#### Notes
1. The scientists would like to be able to use the camera in time for ~cycle 2020/04 (16th Feb 2021)~ ~postponed until long shutdown~ cycle 2021/01 (27th April 2021).
   1. However, this ticket is dependent on a project to install & commission a motion device to move the camera
   1. The motion control project is being managed by N. Webb.  The solution will need to be tested when the motion control is complete, which will be prior to cycle 2021/01.
   1. Motion will be controlled by a Galil
1. The camera itself will be connected to a separate laptop.  There is no requirement (within the scope of this ticket) for IBEX to control the camera.
   1. A project to integrate the camera with IBEX will be undertaken during the long shutdown (see #6094).

**Comment by DominicOram** [comment]
Check with NW if it needs homing routine

**Comment by kjwoodsISIS** [comment]
Tier 4 lockdown restrictions mean that this ticket is likely to be postponed until the long shutdown.

> From: Tom (Instrument Scientist) 
> Sent: 13 January 2021 12:52
> Subject: Re: NIMROD: Neutron camera
> 
> Hi Jacob,
> 
> The delay to the long shutdown is fine. Indeed, with homeschooling duties, funding the time to properly commission was looking difficult. 
> 
> As long as the installation is a high priority for the long shutdown I'm happy with this. 
> 
> Tom 
> 
> ________________________________________
> From: Jacob (Operations)
> Sent: Wednesday, January 13, 2021 10:52:59 AM
> Subject: RE: NIMROD: Neutron camera 
>  
> Hello everyone,
>  
> I hope the break was good for you.
>  
> We have received an updated shutdown list which has been looked over to assess the viability of tasks (regarding safety and availability of people) due to tier 4 restrictions.
>  
> It currently has the base plate/camera work as NOT going ahead. I know we were very keen to get this done this shutdown; is that still the case?
> If so I can reassess how we plan to work and argue our corner.
>  
> Many thanks,
> Jacob
> 
> ________________________________________
> From: Jacob (Operations)
> Sent: 16 December 2020 08:47
> To: 
> Cc: 
> Subject: RE: NIMROD: Neutron camera
>  
> Hi all,
>  
> Yes, we are planning to fit the new base plate with blanking flange.
>  
> As far as I’m aware motion are still working on the camera, but if we get the flange in place this can be relatively easily installed another time.
>

**Comment by kjwoodsISIS** [comment]
Moving ticket out of SPRINT_2021_01_07 and into Long Shutdown

**Comment by rerpha** [comment]
Going to do the "online" setup (ie it'll be vertical this time) in a bit so may change points depending on how much time that takes
