### ISSUE TITLE
Add locks and cleanup to system tests

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5991]
As a developer I would like the system tests to be safe to run on a build machine that also builds EPICS kits, currently they will install in a way that breaks a subsequent build, but are not run on any machine that also builds.

## Acceptance criteria

* systems tests can be run on any build node

**Comment by John-Holt-Tessella** [comment]
I am not 100% sure of this code but it is running on the build server as a test so I am happy to merge it.

**Comment by FreddieAkeroyd** [comment]
The code change should make the logic the same as that already in the `Jenkinsfile` for the ioc tests, and that seems to work
