### ISSUE TITLE
IBEX Training (Organise ASAP for early in April, Main work in April)

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5992]
As an instrument scientist I would like to understand how to use IBEX and so be trained in it (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX). People who specifically are known to need training are:
* MuSR instrument scientists
* Greg Smith (new IS on Larmor)
* INTER, SURF, POLREF
* DCLAB
* new SANDALS scientists
* Tom Wood & Matt Cummings of Energy Materials Group (under LSS) (ref R79 lab migration to IBEX)

## Acceptance Criteria
* Training is organised 
* new ticket created for delivering the training - done, #6348

**Comment by DominicOram** [comment]
@John-Holt-Tessella and @ThomasLohnert, any reflectometry people to add?

**Comment by kjwoodsISIS** [comment]
INTER scientists will need training.

**Comment by kjwoodsISIS** [comment]
I think there are also two new scientists on SANDALS.

**Comment by ThomasLohnert** [comment]
SURF should definitely be on that list I think. POLREF have quite a lot of hands on experience with IBEX at this point but I think they would benefit too (I don't believe they have had formal training)

**Comment by DominicOram** [comment]
All organised for week beginning the 12th

**Comment by KathrynBaker** [comment]
Meetings have indeed been arranged and are visible in the calendar.
