### ISSUE TITLE
HIFI Cryomag: Set Device up correct before ramps

### ISSUE THREAD

**Issue by LilithCole** [ISISComputingGroup/IBEX#5993]
As A instrument scientist, I would like the Cryogenic Ltd SMS series PSU to ensure my magnet is in the correct state whenever ramps are started. This includes whether the magnet is in persistent mode, hot or cold, or ramping fast and slow.

Acceptance criteria:
 - When a ramp is started, flow charts detailed in the design specification are followed.
 - New states are added to the state machine to track heating and cooling
 - Heating/cooling states can be aborted if necessary with no possibility of setting magnet output (separate abort function from ramp aborts)
  - status messages reflect whether ramps are persistent, fast and/or going to zero.
  - suitable tests are added to ensure these changes are functional

**Comment by DominicOram** [comment]
Can you point this please?

**Comment by ChrisColeExpControl** [comment]
PRs:
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/6337
Tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/443

Support (the big one): https://github.com/ISISComputingGroup/EPICS-Cryosms/pull/17
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/603
Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/111

**Comment by ThomasLohnert** [comment]
Impeded until Chris returns
