### ISSUE TITLE
Handover: Instron Stress Rig

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5996]
As a developer I would like to better understand how the Instron Stress Rig is supported in IBEX, so that I am well-positioned to take on its future support and development.

#### Acceptance Criteria
1. A presentation or notes describing how the Instron Stress Rig IOC is implemented and how it should be configured.
1. The Instron Stress Rig presentation/notes delivered to selected ISIS developers.
   * Presentation or notes to be stored in the [Instron Stress Rig](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FInstron%20Stress%20Rig&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) folder on the ICPDiscussions Sharepoint site.

#### Notes
1. ENGIN-X is the primary user of the Instron Stress Rig.
1. The Instron Stress Rig will be used on IMAT after the long shutdown.
1. Completion deadline: 26th February 2021.
1. The code-chat constitutes the review of the ticket.

**Comment by Tom-Willemsen** [comment]
Handed over to @DominicOram and @KathrynBaker

**Comment by DominicOram** [comment]
Happy that there is sufficient documentation on the wiki and that I could support the device
