### ISSUE TITLE
Handover: RIKEN Beamline

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5997]
As a developer I would like to better understand how the RIKEN Beamline is supported in IBEX, so that I am well-positioned to take on its future support and development.

#### Acceptance Criteria
1. A presentation describing the RIKEN Beamline and how it is supported in IBEX is created.
   * the RIKEN beamline is being refurbished during the long shutdown
   * much of the existing support for the RIKEN beamline in IBEX will need to be re-developed
   * the primary focus of the presentation should be the refurbished beamline
1. The RIKEN beamline presentation is delivered in a code-chat session (open to all members of the IBEX team).
   * Code chat slides to be stored in the [RIKEN FE](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Forms/AllItems.aspx?RootFolder=%2Fisis%2Fcomputing%2FICPdiscussions%2FRIKEN%20FE&FolderCTID=0x01200027AD8F05966A2748B3B04C98BB5B442B&View={F2C33C51-70E6-4343-B937-2C59A2568306}) folder on the ICPDiscussions Sharepoint site.

#### Notes
1. The IBEX instance used to control the RIKEN beamline is RIKENFE.
1. Completion deadline: 26th February 2021.
1. The code-chat constitutes the review of the ticket.

**Comment by kjwoodsISIS** [comment]
Code-chat scheduled for 8th March 2021.

**Comment by kjwoodsISIS** [comment]
Code chat happened on 8th March 2021.  Slides - [RIKEN_Handover.pptx](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/GUI_Chat_Slides/RIKEN_Handover.pptx)

**Comment by John-Holt-Tessella** [comment]
this is support for others (NB so it can have 0 points and no release notes)
