### ISSUE TITLE
POLREF: OPI for FMR equipment

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#6003]
As an instrument scientist, I would like to be able to control the FMR (Ferro Magnetic Resonance) equipment running on a remote PC.

Discussions on the design of the OPI will need to be had with the instrument scientist.  A basic OPI referencing all PVs will suffice in the short term.

#### Acceptance Criteria
1. An OPI allowing all relevant values to be read from and written to.

#### Notes
1. The original work to create an LVDCOM IOC was done in #5270 and documented on the associated [wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Ferro-Magnetic_Resonance_equipment)
1. This will need to be done for the FMR system to be used remotely as POLREF has now been migrated to IBEX.  Previously, it used a CALab VI.
1. This ticket may be superseded if it is decided to rewrite the FMR control system as a native IOC (see wiki page above).  Although an OPI of some kind will of course be required, and so this may serve as a basis.

**Comment by DominicOram** [comment]
@John-Holt-Tessella, @ThomasLohnert, do we know when this needs to be done?

**Comment by John-Holt-Tessella** [comment]
I don't

**Comment by rerpha** [comment]
VI screenshot: 

![fmrvi](https://user-images.githubusercontent.com/14823767/172621379-612714c8-a4f7-44b2-8ed5-00ad3f205b17.png)

**Comment by rerpha** [comment]
OPI and opi_info.xml: https://github.com/ISISComputingGroup/ibex_gui/pull/1423 

still need to test with recsim and device itself

**Comment by rerpha** [comment]
ticket for testing on equipment and setting up for POLREF: https://github.com/ISISComputingGroup/IBEX/issues/7187

**Comment by rerpha** [comment]
opi needs a tweak to include whole prefix as ioc runs on remote machine

**Comment by rerpha** [comment]
Patched over to POLREF and added to https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information--hotfixes
