### ISSUE TITLE
System tests: failing on NDHSPARE70 and strange mysql issues

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6005]
On NDHSPARE70 the system tests were failing, the tests that fail are because block values are not getting into the title. At this point I noticed that there was no database so installed mysql 8.0.21 into the usual place. After having a look with @FreddieAkeroyd we found that it was because the database that the icp uses to get blocks from did not have the blocks in it. The ArchiveEngine and other CSS tools are failing to right to the database correctly, initially this was because they were using an old version of Java but now we are not sure. Furthermore, the INSTETC tries to write some facility pvs to the database on startup but the following assertion fails:

![image](https://user-images.githubusercontent.com/54139864/102994781-a3d2d600-4517-11eb-8df3-f39ffc5957ec.png)

Attempted:

- Looking at the privileges the CSS archive account uses to see if it was a permission issue
- Reinstalling mysql including deleting the var/mysql (multiple times)
- Writing to database manually (successfully writes facility pvs using root)
- Checking if the database schema is initialised correctly (looks like it is)

Considering:

- Maybe a broken EPICS build
- Update of database to newer version has broken things
- NDHSPARE70 permissions are preventing writing correctly (deleting var/mysql and stopping and restarting mysql service requires admin privileges)
- Builds of ArchiveEngine and other CSS are broken

To attempt:

- Running system tests with a new build

Notes:

- CSS error is as follow `java.lang.RuntimeException: Application "org.csstudio.archive.config.rdb.app" could not be found in the registry. The applications available are: org.eclipse.equinox.app.error`
- Cannot seem to recompile the MySQL support module that instetc uses to write to the database
- There is a strange task that keeps restarting caRepeater in an admin account

**Comment by JamesKingWork** [comment]
I have removed the labels windows install_ibex system_tests_ioc system_tests_ui JSON_Bourne genie_python_system_tests create_vhd from the ndhspare70 node on jenkins and replaced with only ndhspare70 to prevent other builds from running on it whilst we are testing this. Check this is reset correctly as part of the review.

**Comment by FreddieAkeroyd** [comment]
> Cannot seem to recompile the MySQL support module that instetc uses to write to the database
This is just in your desktop? The mysql bindings in the module are a little old, but the recent ones do not compile with VS2010 so we can't upgrade the mysql c++ bindings just yet.

**Comment by JamesKingWork** [comment]
> 
> 
> > Cannot seem to recompile the MySQL support module that instetc uses to write to the database
> 
> This is just in your desktop? The mysql bindings in the module are a little old, but the recent ones do not compile with VS2010 so we can't upgrade the mysql c++ bindings just yet.

This is on NDHSPARE70

**Comment by FreddieAkeroyd** [comment]
Maybe I misunderstood what you meant by "recompile the MySQL support module", NDHSPARE70 does not have a c/c++ compiler - it just runs ioc/system tests after doing an IBEX install and should not need a compiler.

**Comment by FreddieAkeroyd** [comment]
The SQL issue is fixed by https://github.com/ISISComputingGroup/EPICS/commit/a7596c2680d27dd84f9d81607e7e58f537ece442 It seem that the new MYSQL version does not like transactions to be created in the loaded file, I don't know if this is because we are using older bindings, or a new MySQL big/feature. MySQL does not like nested transactions, maybe some change has now caused these to occur e.g. an implicit transaction is created via the API. Anyway, we did not strictly need to create multiple transactions in the file.

**Comment by FreddieAkeroyd** [comment]
Regarding other issues, I installed system updates and re-applied file permissions. The "strange task" you refer to above that creates caRepeater looks to be the vhd scheduled task https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mount-or-create-IBEX-VHDs I have disabled that for the moment, and have not re-applied the vhd label until we are happy things are working.

**Comment by FreddieAkeroyd** [comment]
having disabled the start/stop all iocs via pro9cserv test the system tests are now passing

**Comment by JamesKingWork** [comment]
Yes and they have run on NDHSPARE70, I am a bit baffled as to how the database has fixed itself

**Comment by FreddieAkeroyd** [comment]
I think that was fixed by https://github.com/ISISComputingGroup/EPICS/commit/a7596c2680d27dd84f9d81607e7e58f537ece442

**Comment by JamesKingWork** [comment]
> I think that was fixed by [ISISComputingGroup/EPICS@a7596c2](https://github.com/ISISComputingGroup/EPICS/commit/a7596c2680d27dd84f9d81607e7e58f537ece442) or do you mean the CSS database access issue?

I did mean the CSS database access issue, but come to think of it I'm not sure if the system tests do test that, I will check

**Comment by FreddieAkeroyd** [comment]
Should this ticket go into review now?

**Comment by John-Holt-Tessella** [comment]
Excellent, system tests pass
