### ISSUE TITLE
HLM PV Import: Review Code

### ISSUE THREAD

**Issue by mihai-stfc** [ISISComputingGroup/IBEX#6013]
Review the code for [HLM PV Import](https://github.com/ISISNeutronMuon/HLM_PV_Import).
The repository contains both the PV Import Service and the Service Manager.
### How to run
1. Download the code from https://github.com/ISISNeutronMuon/HLM_PV_Import and pip install requirements.
1. Run `pyinstaller HlmManager.spec` and `pyinstaller HlmService.spec` inside the project root. Both the manager and service should now be bundled, and the .exe files found in `\dist`.
2. Either copy the service `settings.ini` and `pv_config.json` from [HLM Settings, Config and HLM DB.zip](https://github.com/ISISComputingGroup/IBEX/files/5766092/HLM.Settings.Config.and.HLM.DB.zip) to the same directory as `HlmService.exe`, or run `HlmManager\HlmManager.exe` and select the directory path of `HlmService.exe` when prompted, which should create the PV configuration and service settings files.
3. `HlmService.exe install` via terminal with admin rights, or put [service_setup.zip](https://github.com/ISISComputingGroup/IBEX/files/5766153/service_setup.zip) in the same directory and run it (does the same thing).
4. Follow the rest of the [instructions](https://github.com/ISISNeutronMuon/HLM_PV_Import/wiki/Service-Setup-&-Manager-Manual). 

**Notes**: Do not forget to set up the database as well (the schema and some data can be found in the zip above). When first starting the manager, set-up the DB Connection settings. The DB user & password are saved in the windows registry as parameters of the service.  If it helps with setting-up (to check configuration/settings files/registry etc.), the service is currently running on NDAHEMON.

The service directory should look like this (`service_setup.bat` optional, logs will be created once the service has run):

<img alt="hlm_service_dir_example" src="https://user-images.githubusercontent.com/69153228/103566794-92e07800-4eba-11eb-9a82-1770e5849630.png" width="620"/>

The manager can be placed anywhere, as long as it is given the correct service directory path. The service requires the `settings.ini` and `pv_config.json` files.

### Running in an IDE (e.g. PyCharm)
To test the manager or the service in an IDE (as it's easier to make changes), run `\HlmManager.py` for manager, and `\HLM_PV_Import\__main__.py` for service. Note that for running the service script directly from the IDE, the PV config and settings.ini will need to be added to the project root.
Depending on the user, the manager's settings and logs may differ (as they are saved in `<user>\AppData\Local\HLM Service Manager`).

### Manual tests:
[hlm_manual_system_tests_v1.0.0.xlsx](https://github.com/ISISComputingGroup/IBEX/files/5766350/hlm_manual_system_tests_v1.0.0.xlsx) (feel free to add to this as you run your own tests)

**Comment by DominicOram** [comment]
* STFC person should do this
* Spin out new tickets if there are major refactors required

**Comment by DominicOram** [comment]
Initial comments but I'm ye to review functionality/code so more to come:
- [ ] Can you put these instructions in a readme for the repo? 
- [ ] It's not `install HlmService.exe` it's `HlmService.exe install`
- [ ] The instructions reference `service_setup.bat`. Either put this script in the repository or change the instructions to tell you how to do it manually
- [ ] `See the command prompt console messages and confirm the service has been installed` I don't think there is any confirmation the service is installed? It just runs
- [ ] `Do not forget to set up the database as well` I can't find any instructions on how to set up the database? The file that @KathrynBaker sent on teams looks like it works but can you put it in this repo along with some instructions
- [ ] You mentioned over teams that you will need a FINS IOC running and that it's not happy with multiple connections, can you document this somewhere as well
- [ ] Where is the manual test spreadsheet stored? It should be linked from the wiki
- [ ] Documentation in general seems to be spread between the linked wiki, sharepoint and a little bit on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Helium-Recovery-PLC can you make sure they all link up and say where to go for different bits of information

**Comment by DominicOram** [comment]
For the purpose of getting this ticket through the board I'm going to call it done. Can you make new PRs and tickets that cover the requested changes? Try and keep the tickets and PRs a good size e.g. you may want to do:
* A PR/ticket for all the must changes
* A PR/ticket for all the should changes that are just minor refactoring
* A PR/ticket for each should change that is a major refactor
etc.
