### ISSUE TITLE
DCLAB: create machine and install IBEX

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#6014]
As a support person for power supplies, I would like a copy of IBEX available so that I can test power supplies offline, without them being on any instrument.

We should create a DCLAB machine similar to the existing SELAB and SOFTMAT machines.

### Acceptance criteria
- Find space for the VM on an existing or new server
- Put windows 7 on it by modifying clone of existing machine [Chris M-S estimate: 2 days] (unless windows 10 process is sorted out first)
- Install IBEX and other required software (e.g. nport, notepad++) on it
- ~Ensure the DC lab has a moxa so that they can plug in serial equipment [Chris M-S estimate: 1 day]~ Now done
- Work with support group to create a suitable initial configuration

### Notes
- This request is probably related to https://github.com/ISISComputingGroup/IBEX/issues/5976
- ~We will need to check whether the DC lab has appropriate network connections~ It does

**Comment by DominicOram** [comment]
Can we use this as an example for https://github.com/ISISComputingGroup/IBEX/issues/6122?

**Comment by DominicOram** [comment]
This has been done and is being used as of https://github.com/ISISComputingGroup/IBEX/issues/6867
