### ISSUE TITLE
Blockserver: exception on startup, most likely py2/3 issue

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6018]
On startup I get this exception: 

```
[Wed Jan  6 14:09:49 2021]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\database_client.py", line 23, in get_iocs

[Wed Jan  6 14:09:49 2021]     rawjson = dehex_and_decompress(bytes(ChannelAccess.caget(prefix + DatabasePVNames.IOCS, as_string=True),

[Wed Jan  6 14:09:49 2021] TypeError: encoding without a string argument
```

looks like it's being caused when getting the IOC list from the dbserver. Weirdly enough my IOC list seems to sort itself out in the client but i'm not sure if this goes directly off the dbserver? 

### Acceptance criteria
- Bug is fixed and IOC list is populated on startup
- If the IOC list is not being populated we should add a test to make sure this doesn't happen again

## For Review
- Check comments below

**Comment by RaiBishal** [comment]
This seems to only occur when the block server is started with Python2. Starting block server with python3 seems to be fine on my machine as we now have migrated the block server from 2 to 3. 

The IOC list does get populated on my machine.
