### ISSUE TITLE
WISH: IOC & OPI for Stanford RS SR850 Lock-In Amplifier

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6029]
As a WISH scientist I want to be able to control a Stanford RS SR850 Lock-In Amplifier in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Stanford RS SR850
1. Using genie_python, I can control a Stanford RS SR850

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The manufacturer's web-site describes the [Stanford RS SR850](https://www.thinksrs.com/products/sr850.html).
1. A copy of the Stanford RS SR850 manual is located here: \\isis\shares\ISIS_Experiment_Controls\Manuals\Stanford_Research_SR850.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Stanford SR850`).
1. There are EPICS support modules for the Stanford RS SR830 devices at [EPICS Hardware Support](https://epics-controls.org/resources-and-support/modules/hardware-support/).

### Time in Planning
01:08:47 02/05/24

**Comment by rerpha** [comment]
From the VI it looks like they are just using the SR850 to change the frequency, so I may put a training ticket on this

**Comment by davidkeymer** [comment]
Required for WISH student project June/July 2024, and then for experiment Autumn 2024.

MVP requires logging of the frequency (as mentioned above), but setting of basic parameters (unknown at this stage) desirable.

**Comment by davidkeymer** [comment]
VI front panel:

![Image](https://github.com/ISISComputingGroup/IBEX/assets/10550207/fdd967f9-9783-4889-a395-81a4e6788faf)

Brief analysis of VI:

- Device uses serial/RS232 rather than GPIB
- Termination character for reads and writes is a carriage return: `<CR>` or `\r` or `0x0D`
- Sets frequency using `FREQ` command (the only write command used)
- Reads frequency using `FREQ?`
- Reads X, Y, R and Theta using `OUTP ? x`, where x is 1,2,3,4 respectively

**Comment by davidkeymer** [comment]
Have located unit.  Team WISH double-checking it's the correct one.

**Comment by Chsudeepta** [comment]
The IOC and corresponding OPI has been created:

IOC Support: https://github.com/ISISComputingGroup/EPICS-SR850/pull/1
EPIC IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/861
GUI/OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1710
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/8385
wiki: [SR850](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Stanford-SR850)
manual: \\isis\shares\ISIS_Experiment_Controls\Manuals\Stanford_Research_SR850_Lock-In_Amplifier
