### ISSUE TITLE
WISH: IOC & OPI for Keithley 6517B Electrometer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6030]
As a WISH scientist I want to be able to control a Keithley 6517B Electrometer in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Keithley 6517B Electrometer
1. Using genie_python, I can control a Keithley 6517B Electrometer

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The manufacturer's web-site describes the [Keithley Electrometers (Series 6500)](https://uk.tek.com/keithley-low-level-sensitive-and-specialty-instruments/keithley-high-resistance-low-current-electrom).
1. A copy of the Keithley 6517B Electrometer manual is located here: \\\isis\shares\ISIS_Experiment_Controls\Manuals\Keithley_6517B.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Keithley 6517B`).
1. There is an EPICS support module for the Keithley 6517A Electrometer at [EPICS Hardware Support](https://epics-controls.org/resources-and-support/modules/hardware-support/).

**Comment by rerpha** [comment]
VI looks very simple: 
![5071bkeithleyfrontpanelwish](https://user-images.githubusercontent.com/14823767/120640132-08507480-c46a-11eb-81f7-4981d25c7853.PNG)

**Comment by rerpha** [comment]
Email sent off today to scientists about usage.

**Comment by rerpha** [comment]
Ok, to confirm, on the 370 you can't just query the temperature by the looks of things, and the VI looks to do some magic to try and figure out what the temperature is from a given resistance. I am going to create a new IOC to do this rather than try and merge the two as I don't want to have to do some special logic depending on what model it is.

**Comment by FreddieAkeroyd** [comment]
Might be worth checking out this https://epics.anl.gov/tech-talk/2012/msg01757.php we already build the IP module mentioned

**Comment by Adam-Szw** [comment]
Pull Requests:
EPICS Top: https://github.com/ISISComputingGroup/IBEX/pull/6789
EPICS-IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/634
Support submodule added: https://github.com/ISISComputingGroup/EPICS-Keithley6517B
IBEX GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1351
WIKI page added: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-6517B

**Comment by DominicOram** [comment]
Generally looks good, minor comments linked. It's a rather odd way of controlling a device in that you have to ask for a reading explicitly every time, is this the behaviour you were seeing with the VI or would that periodically poll the device for new values? It might be worth reaching out to the scientists to ask if they would like it to poll. It would make using it in scripts easier and would let them view a history of what the device has been doing too.

**Comment by Adam-Szw** [comment]
Still waiting for response from scientists. Impeded

**Comment by Adam-Szw** [comment]
The scientists would like to have option to use both modes on demand. Following this I implemented new buttons and behavior for that + tests
