### ISSUE TITLE
WISH: IOC & OPI for Tektronix AFG3021B

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6031]
As a WISH scientist I want to be able to control a Tektronix AFG3021B Arbitrary Function Generator in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Tektronix AFG3021B
1. Using genie_python, I can control a Tektronix AFG3021B

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The manufacturer's web-site describes the [Tektronix Arbitrary Function Generator (series 3000)](https://uk.tek.com/signal-generator/afg3000-function-generator).
1. A copy of the Tektronix AFG3021B manual is located here: \\isis\shares\ISIS_Experiment_Controls\Manuals\Tektronix AFG3000 Series
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Tektronix AFG 3021B`).
1. There is an existing stream-device IOC for a Tektronix AFG3022B device (see #235).  The AFG3021B and AFG3022B devices may be sufficiently similar to be controlled by the same IOC.
1. The existing AFG3022B IOC is quite old (it was created via ticket #235).  It may be worth using this ticket to bring it up-to-date with current IOC standards.
1. There is an EPICS support module for the Tektronix AFG3XXX series at [EPICS Hardware Support](https://epics-controls.org/resources-and-support/modules/hardware-support/) - supported by the ISIS Computing Group, no less!

**Comment by rerpha** [comment]
The VI is the same, WISH may not actually need any more functionality than what has been done in #6202 (trigger button, voltage offset, amplitude and frequency). If that is the case we can call this ticket done as it'll be ready for them to use.

**Comment by rerpha** [comment]
Email sent off today to scientists about usage.

**Comment by rerpha** [comment]
removing impeded, no longer impeded, just not that high priority from the WISH standpoint

**Comment by rerpha** [comment]
When we spoke to WISH they said they rarely used the AFG3021B and if so they set it up from the front panel and then triggered it remotely. The current IOC and OPI does this already so I am going to call this ticket done.

**Comment by KathrynBaker** [comment]
I know that this is done, but there is another system potentially using this model, so there is a benefit to it being in our system already
