### ISSUE TITLE
WISH: Check Oscillating Radial Collimator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6032]
As a developer I want to know whether the oscillating radial collimator (ORC) on WISH is similar (or even identical) to the oscillating radial collimators used on other instuments (e.g. GEM, LET and MERLIN).

#### Acceptance Criteria
1. Check the ORC on WISH.  Confirm whether it is similar to other ORCs.
1. Confirm whether the existing IOC/OPI can drive the WISH ORC.
1. If not, create the appropriate IOC & OPI.

#### Notes
1. Current belief is that it is similar to the one used on LET.

**Comment by rerpha** [comment]
I have created ORC_cycle and ORC_STATUS blocks as well as the blocks that reference JAWS 6 which is the ORC, these will need changing in the WISH_base component.

**Comment by rerpha** [comment]
As you can see the WISH and LET ORC vis look fairly similar, in fact the LET one actually even has a typo in that it's named "WISH ORC Front Panel" as you can see in the top right of the VI. GEM's VI however looks quite different, though i'm not sure yet how it talks to the hardware. 

![ORCvi](https://user-images.githubusercontent.com/14823767/121875299-32265880-cd00-11eb-84e7-d9c437422fde.png)

**Comment by rerpha** [comment]
The good news is that MERLINs device screen for their ORC (which is actually named "Oscillating Collimator (LET)") contains pretty much all of the info that the WISH VI contains.

**Comment by rerpha** [comment]
Galil code for ORC lives in `C:\LabVIEW Modules\Instruments\WISH\Galil Programs`

**Comment by KathrynBaker** [comment]
GEMs ORC is (or at least was) a McLennan with a system in between that does the comms and the oscillating and we just send it commands like a more 'normal' device, and that version was being created about 20 years ago. WISH and LET are more recent, and are programs in the Galils, so work differently from our point of view, but all of those using Galil programs will be very similar.

**Comment by rerpha** [comment]
Have used the GEM ORC IOC as a placeholder rather than SIMPLE, but as Kathryn says we may have to do something different. GOing to compare the LET and WISH galil code now

**Comment by rerpha** [comment]
ORC Galil code:

```
#WishORC
mode="I"
count=0
SP~a=16384
AC~a=16384
DC~a=16384
mode="H"
HM~a
SH~a
BG~a
AM~a
WT200
DE~a=0
#Start
count=0
SP~a=vel
AC~a=accel
DC~a=accel
SH~a
PA~a=-dist/2
MC~a
'AM~a
#Oscill8
mode="O"
PA~a=dist/2
BG~a
MC~a
'AM~a
PA~a=-dist/2
BG~a
MC~a
'AM~a
count=count+1
JP#Oscill8,count<=cycles
'maintenance rotation
mode="M"
SP~a=16384
AC~a=16384
DC~a=16384
PA~a=fullrev
BG~a
AM~a
WT200
mode="H"
HM~a
SH~a
BG~a
AM~a
DE~a=0
WT200
JP#Start
EN
```

**Comment by rerpha** [comment]
Have added in motorExtensions.cmd, oscillatingCollimator.cmd (following https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MERLIN-and-LET-Oscillating-radial-collimators) onto the NDXWISH branch on mtr01 - should be correct. We should try this on the hardware as the next step for this ticket.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6715

**Comment by DominicOram** [comment]
As discussed, I think the two Galil codes are different enough that we should not merge them at this point, so can you do the following:
* Add the WISH gmc code into https://github.com/ISISComputingGroup/EPICS-galil/blob/master/GalilSup/Db/ (remember to modify the Makefile too)
* Get that code on to the controller in https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=blob;f=configurations/galil/galil01.cmd;h=b2c2b4b9f4255d2a956d7e45119e864fcad20458;hb=refs/heads/NDXWISH
* Create a new DB next to https://github.com/ISISComputingGroup/EPICS-motorExtensions/blob/master/oscillatingCollimatorApp/Db/oscillatingCollimator.db that sets/gets `cycles` and `fullrev` and add these to the OPI

**Comment by rerpha** [comment]
galil code: https://github.com/ISISComputingGroup/EPICS-galil/pull/55
OPI: 
motorextensions: 
instconfigs:

**Comment by rerpha** [comment]
>  (remember to modify the Makefile too)
This seems to be done automatically now?

**Comment by rerpha** [comment]
OK, I am a bit stuck on what to actually call the `fullrev` variable in the OPI (or even expose it!) as to me it looks like it's just a position set - I think some more logic also needs to be done for "estimated time to maintenance rotation" which i'm not sure about.

**Comment by rerpha** [comment]
Right, all the logic looks like it mirrors the VI now, so think we are ready for hardware testing

**Comment by DominicOram** [comment]
Good work, do we have tickets to:
* Test on hardware
* Harmonise the LET/WISH code

**Comment by rerpha** [comment]
> Good work, do we have tickets to:
> 
> * Test on hardware
Think it's being bundled in with https://github.com/ISISComputingGroup/IBEX/issues/6738
> * Harmonise the LET/WISH code
I can create a ticket for this but LET wouldn't benefit from a maintenance rotation - I talked to David about this and it's to do with the type of bearing the collimator is actually mounted on. I think we could possibly add timing info into the wish code but then you still have two different files.

**Comment by DominicOram** [comment]
I think there's still benefit to harmonising the other bits. The TIME stuff could easily be harmonised and we don't sufficiently understand the calculating the swept angle and whether that can be harmonised. I've created https://github.com/ISISComputingGroup/IBEX/issues/6803
