### ISSUE TITLE
WISH: OPI for WISH Jaws

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6033]
As a WISH scientist I want to be able to control the 5 sets of jaws in my beamline.

#### Acceptance Criteria
1. Using the IBEX client, I can control and setup my 5 sets of jaws
1. Using the IBEX client, I can select an experiment type which will be used to setup the jaws
1. Using the IBEX client, I can select an resolution type which will be used to setup the jaws
1. Using the IBEX client, I can select set the dead-band
1. The IBEX client provides me with an indication that there is a position error in my jaws (i.e. an LED)
1. Using genie_python, I can control and setup my 5 sets of jaws
1. Using genie_python, I can select an experiment type which will be used to setup the jaws
1. Using genie_python, I can select an resolution type which will be used to setup the jaws

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The jaws are Galil controlled.
1. GEM & POLARIS have similar OPIs for controlling their jaws.
1. The OPI must offer functionality equivalent to the existing WISH Jaws VI (located here: `C:\LabVIEW Modules\Instruments\WISH\WISH Jaws`).

**Comment by rerpha** [comment]
Looks like the experiment type is just preset gaps for each set of jaws - options are:
- power diffraction 
- single crystal 
- other

Not sure what resolution refers to - looks like there is some sort of averaging going on in the VI?

**Comment by KathrynBaker** [comment]
There is averaging in the VI, because of the noise on the encoder readbacks

**Comment by daryakoskeroglu** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1379

**Comment by daryakoskeroglu** [comment]
New ticket for creating/connecting missing PVs: https://github.com/ISISComputingGroup/IBEX/issues/6917

**Comment by Adam-Szw** [comment]
Small changes required

**Comment by Adam-Szw** [comment]
As I said in the PR review, I'm assuming functionality of the OPI will be reviewed when this is done https://github.com/ISISComputingGroup/IBEX/issues/6917
I'm merging the OPI itself though

**Comment by daryakoskeroglu** [comment]
Deleted unnecessary LED and spinners for OPI that were there before in VI version. This OPI is not fully finished as it is waiting for PV to be implemented to populate "Experiment Type" spinner. Adding it to the release to avoid work patching.

**Comment by daryakoskeroglu** [comment]
PR: ISISComputingGroup/ibex_gui#1379
