### ISSUE TITLE
WISH: OPI for WISH Vacuum PLC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6034]
As a WISH scientist I want to be able to monitor the status of the vacuum on my beamline.

#### Acceptance Criteria
1. Using the IBEX client, I can see whether the vacuum is ON or OFF (an LED is sufficient).
1. Using the IBEX client, I can see whether the PPS Key is in place or not (an LED is sufficient).
1. Using the IBEX client, I can see whether the Guide Vacuum Interlock has been made or not (an LED is sufficient). 
1. The IBEX client must make it clear that the PPS Key must be in place AND the Guide Vacuum Interlock has been made before the vacuum can be started (i.e. provide a clear written message)
1. Using the IBEX client, I can start the vacuum.
  * the Start button should be greyed out if the PPS Key and Guide Vacuum Interlock criteria are not met
1. Using the IBEX client, I can stop the vacuum.

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The vacuum PLC is a FINS-PLC.  We have an existing IOC for FINS-PLC.
1. The OPI must offer functionality equivalent to the existing WISH Vacuum PLC VI (located here: `C:\LabVIEW Modules\Instruments\WISH\WISH Vacuum PLC`).

**Comment by rerpha** [comment]
db already exists (wish-vacuum.db) so just creating an OPI for this and adding into associated component on NDXWISH

**Comment by rerpha** [comment]
PRs: 
IBEX - https://github.com/ISISComputingGroup/ibex_gui/pull/1311
Release notes - https://github.com/ISISComputingGroup/IBEX/pull/6589

To review: 
- make sure OPI looks the same as the VI on wish, located in `C:\LabVIEW Modules\Instruments\WISH\WISH Vacuum PLC`
- make sure start button is greyed out unless PPS key and guide vac made are true
