### ISSUE TITLE
WISH: OPI for WISH Alignment Flange

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6035]
As a WISH scientist I want to be able to control the XYZ stage used to position my ~~samples~~ alignment flange.

#### Acceptance Criteria
1. Using the IBEX client, I can control the X-, Y- and Z- axes on my ~~stage~~ alignment flange.
1. Using the genie_python, I can control the X-, Y- and Z- axes on my ~~stage~~ alignment flange.

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The XYZ stage is controlled by Galil.
1. Instrument scientists also refer to this as the alignment flange
1. This device uses a Galil 4K, which is permanently mounted in the rack at the sample area.  It's connected to the nPort also in the rack.
1. The actual stage that the controller moves is for aligning a camera/sensor/detector(?) for beam measurements.  This is very rarely used and apparently difficult to install.

**Comment by davidkeymer** [comment]
To date, communication with the controller has been successful (it is permanently connected to the MOXA nPort in the same sample-position rack).  The axes have been configured in IBEX, but have been disabled in the motor table for clarity.

The motion stage itself is yet to be tested.

**Comment by davidkeymer** [comment]
It may be that an existing motion stage OPI (e.g. table, sample stack) would suffice for control of the flange, so no additional work would be necessary.
