### ISSUE TITLE
WISH: OPI for Rotation Stages

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6036]
As a WISH scientist I want to be able to control the rotation stages I use with CCRs.<br>
The WISH SECI configs imply that WISH uses the "Rotating CCR (PM600)" and "MAPS CCR (PM600)" stages.  OPIs already exist for these, but it is worth checking to see exactly what the instrument scientists expectations are.

#### Acceptance Criteria
1. Using the IBEX client, I can control the Rotating CCR (PM600) rotation stage.
1. Using the genie_python, I can control the Rotating CCR (PM600) rotation stage.
1. Using the IBEX client, I can control the MAPS CCR (PM600) rotation stage.
1. Using the genie_python, I can control the MAPS CCR (PM600) rotation stage.

#### Notes
1. Check the [WISH Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details).
1. The "Rotating CCR (PM600)" and "MAPS CCR (PM600)" stages are controlled by McLennan devices.
1. The OPIs must offer functionality equivalent to the existing "Rotating CCR (PM600)" and "MAPS CCR (PM600)" VIs, located 
   1. here: `C:\LabVIEW Modules\Rotating CCR` and
   1. here: `C:\LabVIEW Modules\Instruments\MAPS\MAPS CCR`).
   1. The most obvious difference between these two VIs is the rotation range (should be addressable via configuration macros):
      * Rotating CCR (PM600): -158.0 to +158.0 degrees
      * MAPS CCR (PM600): 0.0 to +350.0 degrees

**Comment by davidkeymer** [comment]
To date, the rotation stages have been tested with the standard single axis OPI (accessible from the motor table) and work well.  This may mean that no additional work needs to be done to create a bespoke OPI as most moves are conducted via scripts.  Need to double-check with IS that this is indeed the case.
