### ISSUE TITLE
WISH: Configurations for 7.5T, 9T, 10T & 14T Magnets

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6037]
As a WISH scientist I want to be able to control any of the 7.5T, 9T, 10T & 14T Oxford Instrument magnets.

#### Acceptance Criteria
1. Using IBEX, I can select and use configurations for any of the 7.5T, 9T, 10T & 14T magnets.

#### Notes
1. In SECI, WISH uses configs which reference the OI Teslatron device
   * This refers to control of any of the following: 7.5T, 9T, 10T & 14T magnets
   * In practice the Teslatron means controlling an ITC503, IPS and ILM
   * Similar configurations used on OSIRIS, LET and ZOOM (see #2593, #2765, #3941, #4868, #5310).
1. At the time of writing (January 2021), the 14T magnet is currently broken, but there is talk of it repaired during the long shutdown.
1. Note from Instrument Scientist:
   * "We can use a variety of magnets (our 14T if it ever gets repaired, the 10T magnet and the wide angle 9T magnet, we could also use the 7.5T but we don't tend to).".

**Comment by rerpha** [comment]
@mihai-stfc could you point this so the project board checks are happy please? I suspect it may be a 3 or a 5 but it's up to you if you think it'll take longer.

**Comment by rerpha** [comment]
Assigning myself as well as Mihai and I are going to pair up on this

**Comment by rerpha** [comment]
inst configs branch: 
`Ticket6037_wish_teslatron`

have set up device screens for IPS, ILM and ITC, created a component borrowed from OSIRIS. We are ditching ISOBUS so still to do on this is set up the teslatron with the correct COM ports configured. This should be done as part of testing, rather than this ticket.

**Comment by rerpha** [comment]
OK, doesn't look like there are any meaningful macros set by looking at all of the instruments configs that use the teslatron, so I am calling this ticket done for now. 

To review: 

- checkout above branch 
- check IPS, ILM and ITC503 are present 
- check device screens are correct (one added for each)
- don't worry about COM ports for now as they will need to be set later

if happy, the branch above should be merged into `NDXWISH` which currently only contains the WISH base component.

**Comment by rerpha** [comment]
repointing for review only

**Comment by DominicOram** [comment]
Looks good enough to be able to test on WISH, good work
