### ISSUE TITLE
PEARL: OPI for PEARL Alignment Mirror

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6047]
As a PEARL scientist I want to be able to control the alignment mirror, so that I can control the beam.

#### Acceptance Criteria
1. Using the IBEX client, I can control the PEARL Alignment Mirror
1. Using genie_python, I can control the PEARL Alignment Mirror

#### Notes
1. Check the [PEARL Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
1. The PEARL Alignment Mirror is related to the PEARL Jaws VI.
1. The PEARL Alignment Mirror is controlled by LinMot drives
1. The OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Jaws` - specifically the `PEARL Jaws (Mirror) Driver.vi` file in the `Screens` sub-directory).

**Comment by davidkeymer** [comment]
This is a single axis LinMot-controlled device, with defined IN and OUT positions.  No need for specific setpoint.

From VI:
IN position is 0.18
OUT position is 97.66

**Comment by ThomasLohnert** [comment]
Configure as MotionSetPoints

**Comment by isaachilly** [comment]
Changes for this ticket are on the branch `Ticket6047_PEARL_ALIGNMENT_MIRROR_MOT_SETUP'` on the config server.

**Comment by isaachilly** [comment]
Made an edit on the first comment in [https://github.com/ISISComputingGroup/IBEX/issues/6052](https://github.com/ISISComputingGroup/IBEX/issues/6052) to say that the MTR1101 address in the config will need to be changed to the address it is on the instrument.

**Comment by rerpha** [comment]
can you add a task to the tasks board to change mtr1101  in the config, and also to add a device screen for this (we already have the OPI for this, it's called motion setpoints (few) so just need to add it on NDXPEARL)

**Comment by isaachilly** [comment]
> can you add a task to the tasks board to change mtr1101 in the config once we have deployed to them and/or the setup machine with all the other PEARL changes, and also to add a device screen for this (we already have the OPI for this, it's called motion setpoints (few) so just need to add it on NDXPEARL)

Done.

**Comment by esmith1729** [comment]
We've added the inPos line in that Zsolt suggested, and have also set the motor definitions correctly (tentatively), on PEARL_SETUP
