### ISSUE TITLE
PEARL: OPI for PEARL Sample Alignment

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6048]
As a PEARL scientist I want to be able to control the alignment of ~~`<something>` (the sample?)~~ the sample, so that I can line it up with the beam.

#### Acceptance Criteria
1. Using the IBEX client, I can nudge the ~~`<thing>`~~ sample
1. Using genie_python, I can nudge the ~~`<thing>`~~ sample

#### Notes
1. The **_Tweak_** controls on the standard axis OPI may be sufficient for this purpose.  Check with PEARL scientists before starting work on an separate OPI
1. Check the [PEARL Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
1. It is not entirely clear what is being nudged (the sample, presumably).  **Yes - the _sample_**
   1. The PEARL Alignment VI speaks to Galils (not LinMots) - maybe that's a clue!  **Yes - a single Galil axis**
1. The OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Alignment`).
1. The default (current) nudge values are: **large -> 0.1mm (or 0.5mm); small -> 0.025mm**

**Comment by ThomasLohnert** [comment]
We have a similar OPI for TOSCA, investigate whether we can reuse this

**Comment by isaachilly** [comment]
All merges completed.
