### ISSUE TITLE
PEARL: IOC & OPI for PEARL Thermometry

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6049]
As a PEARL scientist I want to be able to ~control & graph~ view up to 16 temperature channels, so that I can monitor the temperature of my sample.

#### Acceptance Criteria
1. Using the IBEX client, I can ~control & graph~ view up to 16 temperature channels (graph not required, see below)
1. Using genie_python, I can ~control~ view up to 16 temperature channels

#### Notes
1. This is a readonly device, so no control possible
1. Check the [PEARL Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
1. PEARL uses an NI cDAQ 9181 device with 9213 Thermocouple module to acquire temperature readings
   * How is calibration performed?  Need to check VI.
1. The OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Temperature`).  However, OPI graph not required as functionality can be replicated with Log Plotter.
1. Setup details for the [NI cDAQ 9181](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/PEARL/Pearl%20-%20Temperature%20Readme.txt) device.

**Comment by KathrynBaker** [comment]
No calibration is undertaken in the VI, the cDAQ card in use handles that side of things, this is just a lot of reads via the cDAQ.

**Comment by davidkeymer** [comment]
Pull requests:

[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/834)
[Support](https://github.com/ISISComputingGroup/EPICS-Prltherm/pull/1)
[GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/1681)
[Release Notes](https://github.com/ISISComputingGroup/IBEX/pull/8256)

To review with hardware, the cDAQ device will need to be reserved in the NI MAX application (found in the tree under `Devices and Interfaces -> Network Devices`.  It may first need to be be 'released' from the instrument that is currently using it, also via MAX in the same location, but on the local instance.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)#ni-daq for daqmx install
