### ISSUE TITLE
PEARL: OPI for PEARL XYZ Stage

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6050]
As a PEARL scientist I want to be able to control an XYZ stage, so that I can control the position of my sample.

#### Acceptance Criteria
1. Using the IBEX client, I can control the X-, Y- and Z- axes on my stage.
1. Using the genie_python, I can control the X-, Y- and Z- axes on my stage.

#### Notes
1. Check the [PEARL Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
1. PEARL has a SECI configs which use an XYZ stage, but it is not clear which VI is used.  -> **Generic XYZ stage/sample stack VI**
   * XYZ stage is assumed to be controlled using Galils. -> **Yes**

**Comment by davidkeymer** [comment]
It may be sufficient to use the existing sample stack OPI for this purpose - check with IS.

**Comment by esmith1729** [comment]
The sample_stack.opi will suffice for this; XYZ Stage actually needs 2 XYZ, a "Lower" and an "Upper", the upper one also needing a "Rotate"/w axis. Configurations files for galils and axes will be put onto PEARL_SETUP.

**Comment by KathrynBaker** [comment]
The XYZ setup looks OK, I couldn't see and wasn't aware of any extra setup that would be needed.
