### ISSUE TITLE
PEARL: OPI for PEARL Rotation Stage

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6051]
As a PEARL scientist I want to be able to control a rotation stage, so that I can control the orientation of my sample.

#### Acceptance Criteria
1. Using the IBEX client, I can control a rotation stage.
1. Using the genie_python, I can control a rotation stage.

#### Notes
1. Check the [PEARL Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
1. PEARL has a SECI config which use a rotation stage, but it is not clear which VI is used.
   * Rotation stage is assumed to be controlled using McLennan.
   * The most likely VI is the "Rotating CCR (PM600)" VI, located here: `C:\LabVIEW Modules\Rotating CCR`
   * The OPI should aim to offer functionality equivalent to the existing "Rotating CCR (PM600)" 
1. It is highly likely that the existing rotation stage OPI will be sufficient (perhaps with some configuration).

**Comment by davidkeymer** [comment]
As mentioned above, existing single-axis (stage) OPI may be sufficient - check with IS.

**Comment by will2201** [comment]
Checked with instrument scientists, single_stage.opi is sufficient for the rotation stage.

![single_stage OPI](https://github.com/ISISComputingGroup/IBEX/assets/141733136/cc0017ff-2c56-46e1-aed7-7091cd931134)
