### ISSUE TITLE
SXD: IOC & OPI for ISIS Helium Gauge

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6053]
As a scientist I want to be able to control/monitor the levels of helium & nitrogen in my low temperature SE devices.

#### Acceptance Criteria
1. Using the IBEX client, I can control/monitor helium & nitrogen levels
1. Using genie_python, I can control/monitor helium & nitrogen levels

#### Notes
1. Check the [SXD Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/SXD-Instrument-Details).
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\ISIS Helium Gauge Interface`).

**Comment by KathrynBaker** [comment]
Notes for the VI:
Please remember the Front Panel is the UI, so consider for the OPI
The Setup VI should guide which Macros are needed
Upper and Lower Limit are alarms for the Helium Level, these should be applied to the appropriate fields in the appropriate record
A request to check that the probe is connected and the helium level should be displayed if the Helium Level is 0
The write end of command character is `\r`
The read is looking for a `\r\n`

Commands used in the functions (think protocol file):

| Send | Response Format | Variables and notes | When is this run? |
| --- | --- | --- | --- |
| q | T%d SW%s LH%d LN%d | T goes to the height guage; SW goes to a switch position which is either A or B; LH is the Helium Level for the 'tank'; LN is the Nitrogen level for the 'tank' | Every 100ms (ish) |
| gq\s%d | G %d %d %f %d %f | The first %f is the He Gain, the second is the N2 Gain | Every 100ms (ish) |
| gs %d %d %.2f | - | The first %d is based on the Height Gauge, and is set to 0 for None, 1 for Cryogenic, 2 for ILM200, 3 for TSI; The second %d is either 0 for Helium or 1 for Nitrogen; The %,2f is the appropriate gain from the setup | Sent based on the Height Gauge; Only Helium is sent in the VI |

**Comment by zsoltkebel** [comment]
I talked to SXD scientists and Cryogenics and they said they have never used this VI. They said they can confirm that all the level meters that they currently use are already supported by IBEX. (They use the normal iLM200 V)

**Comment by KathrynBaker** [comment]
Agree that this should not be completed on those grounds, this is an example of a scientist thinking they use something being reminded by the appropriate sample environment team that they don't and the message not getting to us before work has been done
