### ISSUE TITLE
Check Why EMU .RAW files are not replicating (i.e. they may be locked open on EMU).

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#6078]
There was a large screed of "file-open preventing replication" errors in the log files of the archive servers related to EMU before Christmas.  Normally there are a few of these where files are not closed before the first replication attempt from several machines but the number was unusual.  A quick check of the end of run script showed there had been no change (should not have had an effect).  As this is obviously important to clear up, the count and total size of the files in the EMU 20_03 cycle was check on all replica servers showing that all replicas were present and complete (note: failure of replication implies that the file was already on one server or the messages would not have appeared).

**Comment by ChrisM-S** [comment]
Following on from this, it is worth noting that the normal end of cycle process (when cycle_20_3 is closed) - see https://github.com/ISISComputingGroup/ControlsWork/issues/213 will involve full checksum comparison of all completed cycle data files.

**Comment by John-Holt-Tessella** [comment]
It is good to start getting a feel for the complexities of the archive replication server. Although this does not yet make 100% sense to me yet I think after a few of these sort of tickets it will start to become clearer.
