### ISSUE TITLE
Muons: IOC & OPI for Aeroflex Signal Generator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6079]
As a muon scientist I want to be able to control the Aeroflex 2030 Signal Generator.

#### Acceptance Criteria
1. Using the IBEX client, I can control the Aeroflex 2030 and 2023A Signal Generator
1. Using genie_python, I can control the Aeroflex 2030 and 2023A Signal Generator
1. There are 3 IOCs available

#### Notes
1. These two devices are very similar, but not identical in the responses to commands sent, or necessarily in the command sent in certain situations
3. It should be possible to control both from the same IOC with a macro switch to define which protocol file should be used for each of the items which varies
4. The db may be able to stay the same for both items
5. The differences are as follows:
- When setting the RF level, the 2030 uses 2 decimal places the 2023A uses 6
- When setting the mode then the 2030 doesn't send a Pulse value except for with FM or PM Modulations, the 2023A always sends it. There is also a 1500ms wait in the 2030 code when sending this value
- The 2023A includes whether the rf level is on/off in the defaults, the 2030 does not
- The reads for both the carrier frequency and the levels are different, there are some extra values passed in the 2023A (carrier frequency for the 2023A includes the mode; reading the rf level includes the type and status for the 2023 A - note that the items exist on the front panels for both but are hidden)
6. Use the 2030 as a basis, then expand to include the variations for the 2023A
7. The Danfysik IOC allows for this kind of 'switching' of device type whilst keeping the IOC the same

**Comment by KathrynBaker** [comment]
Needs 3 IOCs

**Comment by Scott-James-Hurley** [comment]
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7467

**Comment by ThomasLohnert** [comment]
Do we have access to physical devices for either model for testing?

**Comment by Scott-James-Hurley** [comment]
There's an Aeroflex 2030 in the office.
