### ISSUE TITLE
Muons: OPI for RF Kit

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6083]
As a muon scientist I want to be able to control the RF Kit in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can monitor and control the RF Kit
1. Using genie_python, I can monitor and control the RF Kit

#### Notes
1. **Note from Instrument Scientist (18-02-2021):**
   * "We are thinking of simplifying our RF Kit setup - to make it easier to use.  This will probably change the way the VIs/IOCs work.  We'll let you know how we plan to change things"
   * Clearly, there is a need to consult with the muons scientists before starting work on this ticket.  Consult Steve Cottrell.
1. In SECI, this functionality is provided via the MuSR RF Kit VI.  All the muon instruments use the RF Kit (it is not exclusive to MuSR).  IBEX must provide functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\MUSR\RF Experiment`).
1. There are two variants of the RF Kit (in two different racks) with different (but similar) front panel VIs
   * RF Rack 1 
      - Delay Generator (Stanford DG645) (see #5154)
      - Signal Generator (Aeroflex IFR 2023A) (see #6079 - yes, the 2023A and 2030 can probably share the same IOC)
      - Oscilloscope (Tektronix TDS 2024B) (see #6081)
      - see `C:\LabVIEW Modules\Instruments\MUSR\RF Experiment\RF Kit 1`
   * RF Rack 2 
      - Delay Generator (Stanford DG645) (see #5154)
      - Signal Generator (Aeroflex IFR 2030) (see #6079)
      - Oscilloscope (Tektronix TDS 640A) (see #6080)
      - see `C:\LabVIEW Modules\Instruments\MUSR\RF Experiment\RF Kit 2`
1. User documentation for the RF Kit is here: `\\isis\shares\Manuals\Muon RF Kit\Documentation`
1. Consult with the instrument scientist to discover how these VIs are actually used in practice. 
1. Aeroflex devices are documented 
   * here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Aeroflex IFR 2030` and 
   * here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\AeroflexIFR 2023A`.
1. Tektronix oscilloscopes are documented 
   * here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Tektronix TDS 640A Oscilloscope` and
   * here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Tektronix TDS 2024B Oscilloscope` and
   * here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Tektronix TDS 3034B Oscilloscope`.

**Comment by KathrynBaker** [comment]
I need to check this with the instrument scientists, and against the manuals, but there are differences between the Aeroflex 2030 and the IFR2032A VIs that are worth being certain of.

- When setting the RF level, the 2030 uses 2 decimal places the 2023A uses 6 - this might not be a problem
- When setting the mode then the 2030 doesn't send a Pulse value except for with FM or PM Modulations, the 2023A does not. There is also a 1500ms wait in the 2030 code
- The 2023A includes whether the rf level is on/off in the defaults, the 2030 does not
- The reads for both the carrier frequency and the levels are different, there are some extra values passed in the 2023A (carrier frequency for the 2023A includes the mode; reading the rf level includes the type and status for the 2023 A - note that the items exist on the front panels for both but are not updated on the 2030)

**Comment by KathrynBaker** [comment]
Closing this ticket as reusing it when the new interactions have been defined will be confusing.
