### ISSUE TITLE
HIFI: IOC & OPI for Thorlabs Filter Wheel

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6085]
As a muon scientist I want to be able to control the Thorlabs Filter Wheel (essentially, select a numbered aperture).

#### Acceptance Criteria
1. Using the IBEX client, I can control the Thorlabs Filter Wheel
1. Using genie_python, I can control the Thorlabs Filter Wheel

#### Notes
1. Check the [HIFI Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/HIFI-Instrument-Details).
1. The manufacturer's web-site describes a number of [Thorlabs Filter Wheel](https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=988).  Check with the instrument scientist to determine the model in use.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\HIFI\Thorlabs Filter Wheel`).
   1. The VI has two identical front panels.  Check with the instrument scientists as to why this is the case (there may be no good reason, but it is worth checking).

**Comment by iangillingham-stfc** [comment]
Information from a conversation with James Lord re number of VIs:
"_We have two of these filter wheels. For most laser setups we use both of them and want to control them independently. So the VI library has two identical copies of the top level VI (front panel), one will be configured to talk to each wheel and there is a SECI block associated with each. We need the same setup in IBEX – two IOCs which are identical apart from their PV prefix and the macro file they will use (e.g. THORLABS_01 and THORLABS_02) and probably two instances of the OPI (I think we can just set this up with no need to compile multiple copies)._

Both of ours have 6 position wheels (i.e. FW102C) but the motor unit works with both 6 and 12 position wheels._"

**Comment by iangillingham-stfc** [comment]
PRs now ready for review:
IBEX GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1748
IOC support: https://github.com/ISISComputingGroup/EPICS-ThorlabsFW102C/pull/1
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/890

Release notes updated: https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md
Wiki updated: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Thorlabs-FW102C-Filter-Wheel
Manufacturer's manual added to: <cclrc domain>Shares\ISIS_Experiment_Controls\Manuals

**Comment by jackbdoughty** [comment]
Merged changes- needs to be tested on device when convenient
