### ISSUE TITLE
HIFI: IOC and OPI for Group 3 Hall Probe

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6088]
As a muon scientist I want to be able to control a group 3 Hall probe, so that I can use it to monitor the magnetic fields in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can monitor and control a group 3 Hall probe
1. Using genie_python, I can monitor and control a group 3 Hall probe

#### Notes
1. Check the [HIFI Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/HIFI-Instrument-Details).
1. In SECI, this functionality is provided via the Group3 Hall Probe VI.  IBEX must provide functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\HIFI\Group3 Hall probe`).
   * There are 5 VIs that appear to be "front panels".  Some look like they might be development ideas.  It is not clear which ones are actually used.
   * The 5 "front panel" VIs are (in order of increasing complexity)
      1. `G3 Hall Probe panel.vi` (see image HIFI_G3_Hall_Probe_simple_VI.png)
      1. `G3 Hall Probe panel with log.vi` (see image HIFI_G3_Hall_Probe_simple_with_log_VI.png)
      1. `G3 Hall Probe panel 2.vi` (see image HIFI_G3_Hall_Probe_simple_2_with_log_VI.png)
      1. `G3 Hall Probe panel 3 with ZF.vi` (see image HIFI_G3_Hall_Probe_complex_with_ZF_VI.png)
      1. `Copy of G3 Hall Probe panel 3 with ZF.vi` (see also image HIFI_G3_Hall_Probe_complex_with_ZF_VI.png)
1. Consult with the instrument scientist to discover how these VIs are actually used in practice.

**Comment by KathrynBaker** [comment]
Notes whilst reverse engineering to define better what is needed:
- Only `G3 Hall Probe with ZF.vi` is referenced in the configs and components
- There is an ini file which should be replaced at least in places by macros
- The number of probes is in this ini file and is used to drive things like the number of rows for the labels, the ranges etc. There are 6 probes
- Each probe has a section in the ini file giving the name, COM Port, address on that COM port, and an axis which is +/- X, +/- Y, or +/- Z
- Sending `A%d\s` where %d is the address from the ini file beforehand. Then the following is currently appended: `SE0GDR3GCNNUFG` , according to a comment from JL:
	- Initialise.
	- Open serial ports (can be shared, do each once only)
	- Send commands to magnetometers:
	- SE0  (echo off)
	- GD   (DC readings)
	- R3   (Range 3, 6 Tesla) or R0..R2
	- GC   (Continuous readings)
	- NN   (Normal display mode)
	- UFG  (Gauss)
- The plots are named and made visible as appropriate
- The Final Offsets come from the ini file
- The Persistent Gradients also come from the ini file
- The field controls link to the cryomagnet X,Y,Z magnets
- There is a log file generated as well - if still needed this could be looked at via ARACCESS
- Group 3 probe manual: https://wiki.jlab.org/ciswiki/images/6/62/G3_MAN_DTM-151-S.pdf
- Main Loop
	- Toggle The activity light on and off
	- I deleted a lot of information relating to the logging as far as I could tell
	- For each probe:
		- Send `F` to get a field reading, with a default of -infinity
		- If no response is received:
			- Set a value of +infinity
		- Otherwise:
			- Trim any white space from the response
			- Try to convert this into a number (default of -infinity)
			- If this fails:
				- If "OVER RANGE" can be found in the returned string:
					- If the present range for the probe is 0 to 2:
						- Increment the value (Write the address of that probe followed by `R%d`, where `%d` is the new value for the probe range)
					- If the range is presently 3, or any other value:
						- Set the range value to 3
						- Set the field reading to +inifinity
				- Otherwise:
					- Set the field reading to -infinity
			- Otherwise:
				- If the absolute value of the field reading is less than the corresponding move down point (-1, 2500, 5000, 1000, these are all roughly 83% of the previous range level, ranges are 3000, 6000, 12000, 30000):
					- Change the range value down a level
				- Otherwise:
					- If the absolute value is more than the corresponding move down point (2900, 5800, 11600, 999999, which are all roughly 97% of the current range value):
						- Change the range up a level
					- Otherwise
						- Do nothing
		- If Measure T (front panel control) is `True`:
			- Send and read `T`
			- If T can't be read:
				- Set the T value to +infinity
			- Otherwise:
				- If a numeric can't be read from the returned value:
					- Set the T value to -infinity
				- Otherwise:
					- Set the T value to the value returned from the device
	- If the T readings are being read, plot them on the graph
	- `Readings Array = The Field readings are each multiplied by -1 if the fields are reversed (or 1 if it isn't)`
	- (I am going to ignore the test readings option for the moment)
	- `Adjusted Fields = Readings Array`
	- `Interim coil values (context for ease of understanding the next displayed items) = For each PSU: {Adjusted Fields = Adjusted Fields - (multiply each value in the appropriate column in the coil inhomogenities field table with the PSU current readback)}`
	- The appropriate columns are x = 0, y = 1, and z = 2
	- `Corrected for coils = Interim coil values + [x current, y current, z current, x current, y current, z current]`
	- `Persistent grad value = Interim Coil Values[4] - Interim Coil Values[1]`
	- `corrected for persistent fields (context value again) = Interim coil values - (persistent gradients*persistent grad value)`
	- Split the corrected for persistent fields into two arrays, elements 0,1,2 in one and 3,4,5 in the other. Add these two arrays together and divide by 2, and subtract the final offsets, then add these values to the psu current readback to get X, Y, and Z.
	- There is a "cleaner" VI Array Maths Example that may make this easier

**Comment by KathrynBaker** [comment]
Front Panel of the VI:
![Pasted image 20240510163847](https://github.com/ISISComputingGroup/IBEX/assets/10552381/d342377d-02f9-4de4-bb3a-19ec93150aa0)

**Comment by KathrynBaker** [comment]
The ini file contains the following:
[Probes]
number=6
[Log]
enabled=false
[Probe0]
Name="X Upstream"
Port=COM19
Addr=4
Axis=-X
[Probe1]
Name="Y Upstream"
Port=COM19
Addr=2
Axis=+Y
[Probe2]
Name="Z Upstream"
Port=COM19
Addr=3
Axis=-Z
[Probe3]
Name="X Downstream"
Port=COM20
Addr=1
Axis=-X
[Probe4]
Name="Y Downstream"
Port=COM20
Addr=2
Axis=+Y
[Probe5]
Name="Z Downstream"
Port=COM20
Addr=3
Axis=-Z
[Calibration]
Offset0= -1.497
Offset1= +2.48
Offset2= -0.71

Grad0=	-0.043
Grad1=	-0.5406
Grad2=	0.96709
Grad3=	-0.0467
Grad4=	0.4594
Grad5=	0.826051

Inhom00=	0.8491
Inhom01=	0.0463
Inhom02=	0.0481
Inhom10=	-0.0078
Inhom11=	0.953
Inhom12=	0.2554
Inhom20=	0.0042
Inhom21=	-0.0123
Inhom22=	0.9292
Inhom30=	0.8432
Inhom31=	-0.0339
Inhom32=	0.0207
Inhom40=	0.0394
Inhom41=	0.9543
Inhom42=	-0.2509
Inhom50=	-0.01
Inhom51=	0.007
Inhom52=	0.9332
[Magnet]
VI="HIFI - Cryomag - Front Panel.vi"
X="X Output"
Y="Y Output"
Z="Z Output"

**Comment by KathrynBaker** [comment]
There is interaction throughout this with the group 3 hall probe and with the zerofield, rather than maintain this ticket I shall split into one for the probe and another to specify the zerofield as the maths seems to be different to the previous implementation, but that should be checked.

**Comment by KathrynBaker** [comment]
Closing this ticket as #8400 and #8401 will be better placed to achieve this work after the analysis above.
