### ISSUE TITLE
HIFI: Cryomagnet Control

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6091]
As a muon scientist I want to be able to control the HIFI Cryomagnet.

#### Acceptance Criteria
1. Verify that the gateway on the cryomag machine is set up to allow HIFI to control this system.
1. Using the IBEX client, I can control the HIFI Cryomagnet from NDXHIFI.
   - The UI for teh aggregated devices used on the cryomag machine should be appropriate, but the PVs will all be remote and looked at from that system
1. Using genie_python, I can control the HIFI Cryomagnet from NDXHIFI.

#### Notes
1. The existing LabVIEW control system for the HIFI Cryomagnet has been replaced with an EPICS-based control system.  Consult with @KathrynBaker & @LilithCole to determine how to control of the HIFI Cryomagnet should be exposed to the instance of IBEX running on NDXHIFI.

**Comment by LilithCole** [comment]
achievable simply by loading hifimags opi and pointing to cryomag machine
