### ISSUE TITLE
SANDALS: New Chopper (SKF G5)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6096]
As a SANDALS scientist I want to use IBEX to control the new chopper being installed on SANDALS during the long shutdown.

#### Acceptance Criteria
1. Using the IBEX client, I can control the new chopper
1. Using genie_python, I can control the new chopper
1. I am not permitted to set the chopper speed beyond its 50 Hz maximum.

#### Notes
1. At the time of writing (January 2021):
   * this ticket should be updated with more details as and when they are known (e.g. timing of install & commissioning)
   *  Abigail Basham is the PM for the SANDALS upgrade
1. The make and model are:
    *  double-disc chopper (2 x SKF G5 controllers) (see [Comment 1](https://github.com/ISISComputingGroup/IBEX/issues/6096#issuecomment-762258812))
    * Note the 50 Hz maximum speed

**Comment by kjwoodsISIS** [comment]
From: Carter, Tim
Sent: 18 January 2021 11:33
To: Galsworthy, Peter,  Woods, Kevin
Cc: Brind, Mike; Johnson, Erik; Basham, Abigail
Subject: RE: Chopper Plans for Long Shutdown

>> SANDALS
>> This project is a partial upgrade of the SANDALS instrument from target to sample tank. This includes a new Double Disc Chopper fitted with two SKF G5 Spindles and Controllers. This chopper is very similar to the two Double Disc Choppers on IMAT but as this instrument is on TS1, the chopper will have a 50Hz maximum speed. Again, Tim Carter should be able to give you any tech., info. Abigail Basham is the Project Manager and I will ask her to add you to the team and bring you up to speed on the requirements and the programme.

> Agreed – the control will be very similar to IMAT G5 choppers.

**Comment by KathrynBaker** [comment]
Work was done and the chopper is in place and ready to use as part of the instrument control system
