### ISSUE TITLE
LET: Configure and test SKF G5 device for chopper #1

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6099]
As a LET scientist I want IBEX to control the new SKF G5 chopper that will be installed on LET during the long shutdown.<br>
As a developer, I want to configure IBEX on LET to support the new SKF G5 chopper.

#### Acceptance Criteria
1. There are sufficient instances of the SKF G5 chopper IOC to support all the G5 devices on LET
1. The existing SKF G5 chopper OPI can support the additional IOC instance.
1. Using the IBEX client, I can control the new SKF G5 chopper
1. Using genie_python, I can control the new SKF G5 chopper

#### Notes
1. Chopper 5 on LET is the same make/model of chopper (see #5033). This ticket is primarily about configuration.

**Comment by kjwoodsISIS** [comment]
> From: Carter, Tim
> Sent: 18 January 2021 11:33
> To: Galsworthy, Peter,  Woods, Kevin
> Cc: Brind, Mike; Johnson, Erik; Basham, Abigail
> Subject: RE: Chopper Plans for Long Shutdown
> 
> 
>> LET
>> The new chopper, still to be installed, is a replacement for the existing Chopper 1. It is very similar to the recently installed replacement Chopper 5 with two SKF G5 Spindles and Controllers, and the IBEX requirement with be the same. Mike Brind is the Major Task Manager for the Installation, Set-up and Commissions tasks of this project. I will ask him to include you in the Installation team and update you with the programme.
> 
> Yes, Chopper 1 installation will be almost identical to chopper 5 from an IBEX point of view.
>

**Comment by davidkeymer** [comment]
This work is complete.  An extra SKF IOC needed to be created, now 6 in total, as well as an extra tab on the OPI.  Both of which were included in the latest v10 release after a flash review.

LET base configuration and synoptics updated accordingly.  Reordering of controllers on OPI tabs requested by IS (RS).  Now as follows:

Tab 0 - Controller/IOC 01 – Chopper1_Disk1
Tab 1 - Controller/IOC 02 – Chopper1_Disk2
Tab 2 - Controller/IOC 03 – Chopper3
Tab 3 - Controller/IOC 04 – Chopper4
Tab 4 - Controller/IOC 05 – Chopper5_Disk1
Tab 5 - Controller/IOC 06 – Chopper5_Disk2

Private/local IP addresses for each controller are listed in the `GLOBALS.TXT` file.  Also defined are names (as above) and parking angles.  Note IP addresses are not in same order.

Tests of chopper performed with TC on 28/01/2022.  Checked all functions of OPI.

Some additional work/improvements possible as a result (does not seem to be able to read setpoint from hardware).  Still under investigation by TC, but ticket will be written if required.

Also current OPI needs to be updated to current format.  Suggestion to use separate OPI for each controller, as in MK3 chopper, and potential improvements to functionality could be incorporated simultaneously.  Again, ticket will be written if/when required.

**Comment by davidkeymer** [comment]
PR for [release notes](https://github.com/ISISComputingGroup/IBEX/pull/7000)

NB: for v10 (current release), not upcoming as already present.

**Comment by rerpha** [comment]
Cheers for adding it to the release notes, it's good even if we retrospectively add things to release notes. 

For reference, PRs were: 

https://github.com/ISISComputingGroup/EPICS-ioc/pull/666
and 
https://github.com/ISISComputingGroup/ibex_gui/pull/1392
