### ISSUE TITLE
TOSCA: Resolve outstanding sample changer support issues

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6101]
As a TOSCA scientist I want IBEX to control the TOSCA sample changer.  I also want to view the sample chnager when it is installed in my instrument.<br>
As a developer I want to resolve the outstanding support issues associated with the sample changer and webcam.

#### Acceptance Criteria
1. Using the IBEX client, I can control the TOSCA sample changer
1. Using the IBEX client, I can view the TOSCA sample changer using a webcam
1. Using genie_python, I can control the TOSCA sample changer

#### Notes
1. It has been difficult to resolve the support issuesd associated with the "belt & drive" sample changer on TOSCA.  The long shutdown presents a good opportunity to address these issues.
   * the sample changer comprises two main elements - the drive and the "belt" (a chain)
   * to test these, they need to be connected to the cryostat flange (really needs to be done on the instrument, not easy to do offline)
   * liaise with sample environment team to get sample set up, so that it can be tested when the instrument is not being used
   * it is not clear if the TOSCA webcam is properly configured for use with IBEX.  This should be checked and implemented as part of this ticket.  The correct working of the webcam should be demonstrated to the TOSCA instrument scientists.
1. Completing this ticket will resolve the following issues: #4008, #4068, #4741.

**Comment by davidkeymer** [comment]
Visit from IS (SP) on 18/10/2021.  Keen to resolve ongoing issues, especially in light of imminent SECI retirement.  Also would like to buy new webcam for device and check compatibility with group before doing so.

**Comment by KathrynBaker** [comment]
Having checked with IS (SP) 21/10/21, whilst it would be appreciated to complete this before the end of 2021, there was understanding that much of this may need to be delayed. However, sorting out the webcam and sorting out what to get now would help ensure there are no delays on that side when things are in place at a later date.

**Comment by FreddieAkeroyd** [comment]
Contact details for webcam forward to IS

**Comment by rerpha** [comment]
OPI web view fix: https://github.com/ISISComputingGroup/ibex_gui/pull/1410

Have visited the sample changer today, looks like what it needs to do is fairly simple but something isn't quite right - we need to drive it 1400 steps relatively each time a user hits next/previous sample but it may try and repeatedly do this currently or drive the wrong direction. We have basically been given free reign over it for the next few weeks so may see if I can get it at least talking to see what current behaviour is.

**Comment by rerpha** [comment]
ah, we may need to host the html file as i can't seem to reference it relatively..

**Comment by rerpha** [comment]
webcam page now hosted, ask me where it is if you want to see or alternatively wait a bit as it'll be saved in TOSCAs device screens as a macro. 

We are going to upgrade TOSCA today to 10.0.0 and hotfix over https://github.com/ISISComputingGroup/ibex_gui/pull/1410

**Comment by rerpha** [comment]
TOSCA upgraded to V10.0.0 (added [here](https://github.com/ISISComputingGroup/IBEX/wiki)) - OPI in PR above hotfixed. 

To review you could check that the timestamp is updating in the web view on NDXTOSCA + locally with the OPI checked out - movement has been confirmed

**Comment by FreddieAkeroyd** [comment]
The javascript fix avoids the image flicker, but there is a continuous pulsing "hourglass" on the screen that may become offputting and it also need the javascript web page to be hosted somewhere, currently control-svcs but could ultimately be a local web server. As a possible alternative I have investigated using ADURL supplied with areaDetector which then allows a regular OPI to be used to render the image #7146
