### ISSUE TITLE
ALF: New Chopper (ISIS Mk3)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6113]
As an ALF scientist I want to use IBEX to control the new chopper being installed on ALF during the long shutdown.

#### Acceptance Criteria
1. Using the IBEX client, I can control the new chopper
1. Using genie_python, I can control the new chopper

#### Notes
1. At the time of writing (January 2021):
   * this ticket should be updated with more details as and when they are known (e.g. timing of install & commissioning)
   * Abigail Basham is the PM for the ALF upgrade
1. The make and model are:
    * Bosch Rexroth T-Zero and Single Disc chopper systems, controlled by ISIS Mk3 controllers.

**Comment by kjwoodsISIS** [comment]
> From: Carter, Tim
> Sent: 18 January 2021 11:33
> To: Galsworthy, Peter; Woods, Kevin
> Cc: Brind, Mike; Johnson, Erik; Basham, Abigail
> Subject: RE: Chopper Plans for Long Shutdown
> 
> PRISMA/ALF
> There is another project that I am aware of not listed here. This is the upgrade of the Cortina 
> choppers on ALF (T0 and Disc) to our conventional Bosch Rexroth T-Zero and Single Disc chopper systems,  
> controlled in the usual way via Paul Chorley’s MK3 controllers. 
>

**Comment by davidkeymer** [comment]
MK3 IOCs configured, Synoptic updated.  Choppers working well for at least one cycle.  InstSci happy.
