### ISSUE TITLE
Provision and Setup MOXA in DC LAB

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#6116]
As a power supply technician, I would like to test new power supplies in the lab to confirm that the comms. work and that they can be controlled from IBEX.

***Acceptance Criteira***
1) MOXA is attached and checked to work on network port in DC lab.
2) Network and MOXA cables and RJ45 Joiner(s) are provided to allow connection to the PSU(s) under test.
3) The setup is suitable for testing multiple supplies (if required).

***Notes***
1) Some cabling may be necessary to get the MOXA located at a convenient point in the lab.

**Comment by ChrisM-S** [comment]
MOXA supplied and installed by technician, DCLAB MOXA now setup and configured and address registered remotely.  There is a follow on ticket for this #6205 to help them setup appropriate IBEX IOCS and settings to test power supplies using a DEMO machine.

**Comment by DominicOram** [comment]
Great, thanks @ChrisM-S. Can we get the IP address noted down somewhere? The inst summary page seems best. @FreddieAkeroyd can you do this?
