### ISSUE TITLE
Python 3: Switch to python 3 being the default used python

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6132]
As a user I want my instrument to be running a supported version of Python. Now we believe most bits of python code are converted we should do the following.

## Acceptance Criteria
* Discuss how we want to remove Python 2. Outcome:
  * Delete `C:\Instrument\Apps\Python` and keep `C:\Instrument\Apps\Python3` as-is
  * Remove `%PYTHON%`
  * ~Run through all the manual system tests and confirm they work~ -  we will do this at release, for now just smoke test. 
* Implement the solution from the above discussion
* Remove PY2 references from genie_python

**Comment by FreddieAkeroyd** [comment]
when you say rename `C:\Instrument\Apps\Python` to `C:\Instrument\Apps\Python2` this is the default location for the  python 2 installer, however we will no longer install python2 on the instrument?

**Comment by DominicOram** [comment]
I would suggest we install python 2 into a place it won't accidentally be used (hence the rename) such that if we find we need it in a hurry it's there on the instrument. Then remove it the cycle after. But open to discussion

**Comment by DominicOram** [comment]
Note that the genie python 2 tests were removed in https://github.com/ISISComputingGroup/genie_python/pull/315

**Comment by DominicOram** [comment]
Can also probably close https://github.com/ISISComputingGroup/IBEX/issues/3256 as part of this

**Comment by DominicOram** [comment]
The emulator for v1 mezei flipper still requires python 2

**Comment by rerpha** [comment]
It doesn't look like %PYTHON% or %PYTHONW% are actually used anywhere besides defining the variables. The only place that uses \instrument\apps\python now is genie_mantid - not sure if this will cause issues?

**Comment by DominicOram** [comment]
Where did you search for them? What's genie_mantid?

**Comment by rerpha** [comment]
> Where did you search for them? What's genie_mantid?

in the whole of `\instrument\apps\epics` searching .bat and .sh files, and I have no idea, it's in `\instrument\apps\epics\genie_mantid`, part of epics top

**Comment by rerpha** [comment]
Outcome of this morning's discussion: 

- Best option is to remove `\Instrument\Apps\Python` completely and leave `\Instrument\Apps\Python3` as-is
- We will no longer be deploying Python 2 - we should make everyone aware of this and update the wiki accordingly, will do this as part of this ticket and as part of the next release.
- No need to manual test as we'll be doing this at release several times before next deployment anyway, better off just smoke testing
- genie_mantid should either be fixed or removed, but ignored for this ticket - spun out into https://github.com/ISISComputingGroup/IBEX/issues/6510

**Comment by rerpha** [comment]
PRs (in progress, I just like to keep track)

- EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/260

**Comment by rerpha** [comment]
Everything seems to work as it should - I'm not too shocked as very little actually referenced `%PYTHON%` or `\instrument\apps\python` anyway. `update_genie_python` also seems to work.

**Comment by DominicOram** [comment]
I think we still need to work out what we're doing about the v1 mezei flipper?

**Comment by rerpha** [comment]
> I think we still need to work out what we're doing about the v1 mezei flipper? (https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/search?q=DEFAULT_PY_2_PATH)

how many places is it used on site?

**Comment by DominicOram** [comment]
Good question, we should ask the relevant instruments

**Comment by rerpha** [comment]
can do, i guess i need to find who is using the IOC first then contact the instruments from there?

**Comment by rerpha** [comment]
whoops, sorry

**Comment by rerpha** [comment]
sent email off to ISs of POLREF and LET

**Comment by rerpha** [comment]
mezei flipper v1 tests + emulator work fine under python 3, i'm actually wondering if they were originally written in py3 and we just ran them under python 2 for the test framework.

**Comment by rerpha** [comment]
I think regardless of whether LET or POLREF are using the v1 version (which they do appear to be) all of the IOC tests are now passing for the mezei flipper v1 under python 3. I did a few more searches but couldn’t find any other references to python 2 in \instrument\apps\epics so going to put this back in review now
