### ISSUE TITLE
reflectometery: Confirm that logging of Nima trough from database is fast enough

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6135]
As an instrument scientist on SURF I would like to record various measurements so that I can easily plot those measurements versus each other; to do this they must be taken at the same time. Example of this is plotting pressure vs area on the Nima trough.

### Acceptance Criteria

- User has a way of getting data that allows them to easily plot two PVs against each other over a given time period.
- Data is sampled frequently enough that the plot is useful

### Notes

- EnginX does a similar thing with their stress rig explore this as a way of generating data
- Check that the current NEXUS file is not good enough

**Comment by John-Holt-Tessella** [comment]
The user has said they will generate some data such the we can talk about an example to make sure that the mechanism is good enough.

We have suggested that they can either use the NEXUS file or the following script modified for the experiment they want to do:

```
REM script to create a log file from the archive

call c:\instrument\Apps\EPICS\config_env.bat

pushd c:\instrument\Apps\EPICS\ISIS\inst_servers\master\scripts
%PYTHON% log_file_generator.py --start_time %1 --point_count %2 --delta_time 60 --filename_template c:\logs\nima{start_time}.csv --default_field "" PRESSURE %MYPVPREFIX%CS:SB:PRESSURE AREA %MYPVPREFIX%CS:SB:AREA

popd
```

**Comment by ThomasLohnert** [comment]
Have tested the above script on data collected with the nima trough on SURF. Below is the interpolated data compiled by the script plotted against data saved by the SECI VI (the graphs overlap). SURF Scientist has confirmed this is fine.

![image](https://user-images.githubusercontent.com/18398579/113136278-1809cd80-921b-11eb-8803-3d6e4f3d891b.png)

**Comment by John-Holt-Tessella** [comment]
Yay!!!

**Comment by JamesKingWork** [comment]
Adding support to avoid complaints in ProjectBoardChecks about release notes
