### ISSUE TITLE
ARGUS: Investigate requirements for Zero-Field Controller

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6140]
As an ARGUS (and CHRONUS) scientist I want to be able to control the magnetic field at the sample position of my instrument.<br>
The zero-field controller on ARGUS is different to the one used on EMU, MuSR & HIFI; as a developer, I want to understand why it differs, what the differences are and whether they are significant.

#### Acceptance Criteria
1. Determine why ARGUS uses a different Zero-Field Controller to the other muon instruments
1. Determine whether ARGUS can use the same Zero-Field Controller as the other muon instruments (see note 2 below).
1. If ARGUS needs a special Zero-Field Controller:
    1. determine how it differs from the existing Zero-Field Controller
    1. document the ARGUS specific requirements
    1. create new tickets to manage the implementation of an  ARGUS specific Zero-Field Controller

#### Notes
1. The SECI zero-field controller for ARGUS is located here: `C:\LabVIEW Modules\Instruments\ARGUS\Zero Field Controller`.
   * it is similar to, but not quite the same as the SECI zero-field controller used by EMU, MuSR and HIFI
   * we need to understand why
      1. it may simply be an older version that didn't get upgraded when the others were upgraded
      1. there may be some other reason
      1. we need to talk to the scientists to discover why
1. See also [ARGUS_CHRONUS_Questions.docx](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/ARGUS_CHRONUS_Questions.docx) for more information.
   * scientists are keen to have a single, unified zero-field controller that is the same on all muon instruments.
   * in discussions, Adam & Francis were happy to have the same zero-field controller as EMU (and MuSR).
   * there are some hardware differences between current north 7 south side muon zero-field controllers; muon scientists would be happy to be advised on how to minimise the differences (and remaining differences could be managed via configuration).

**Comment by KathrynBaker** [comment]
There were some aspects that were not used by the north side which were used by the south side, so when the code was updated and set to work there the south side were not updated. Hardware differences relate to items that should be abstracted to at least some extent.

**Comment by KathrynBaker** [comment]
For info in PI Planning - this should be as straightforward as "set up the zerofield IOC and OPI on the appropriate instrument", however that may not be as simple as it sounds given the different behaviours seen between EMU and MUSR. From our perspective we should do the setup and be braced for further work needed once the testing is underway

**Comment by FreddieAkeroyd** [comment]
should be same as emu/musr
