### ISSUE TITLE
Release: Create release for cycle 2021/01

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6149]
We should create a release for the next cycle. In a meeting on 27/01/21 we said that this release will look small in the release notes when compared to 7.3 but is actually large compared to 7.1, which is what is on the instruments. To make sure scientists are aware of this when we sent out the release notes we should combine all those since 7.1

As a developer I want a IBEX release so I can install it on the instrument machines for the next cycle, 16th Feb. This will be a major release as it contains dependency updates and Python 3 conversions so we may want to discuss which instruments we release to given the increased risk.

Acceptance Criteria:

- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] We decide where to deploy to and an appropriate deployment ticket is created
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)
 - [x] [Create a ticket to give instrument demos](https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos)
 - [x] Distribute release notes via email [Instrument scientist release email](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Updating-Instrument-Machines#a-new-release)

**Comment by DominicOram** [comment]
We will need to release JSON Bourne for https://github.com/ISISComputingGroup/IBEX/issues/5765

**Comment by DominicOram** [comment]
RD has requested that Larmor and CRISP be deployed to as early as possible as they would like to test https://github.com/ISISComputingGroup/IBEX/issues/5688

**Comment by DominicOram** [comment]
Should do https://github.com/ISISComputingGroup/IBEX/issues/5895 straight after release

**Comment by DominicOram** [comment]
This release will also include the SANS sample changer and so should allow https://github.com/ISISComputingGroup/IBEX/issues/6227 and https://github.com/ISISComputingGroup/IBEX/issues/6226 to be done

**Comment by JamesKingWork** [comment]
MuSR have requested that the script generator be released to them and I believe EMU will also want the latest changes

**Comment by rerpha** [comment]
We should make sure https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-Updates#nicos is up to date before releasing so it doesn't cause flashing nicos windows.

**Comment by DominicOram** [comment]
Added into release as we're getting a number of requests for having it on beamlines soon

**Comment by DominicOram** [comment]
Created https://github.com/ISISComputingGroup/IBEX/issues/6375 for the deployments

**Comment by ThomasLohnert** [comment]
Where are the system test results? I looked on the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests-Results) and on the teams folder but it was in neither. Can we update the [manual system tests page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) with the correct location for results?

**Comment by DominicOram** [comment]
Now linked on wiki. But you're right we should be clearer about where they're meant to be

**Comment by JamesKingWork** [comment]
Adding support to avoid complaints in ProjectBoardChecks about release notes
