### ISSUE TITLE
KEPCO: sends multiple setpoints to hardware per write to CURRENT:SP

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#6152]
As a user of Muon ZF-compensation systems, I care about the kepcos being as fast as possible

It appears that kepcos now send a setpoint twice to hardware per write to `CURRENT:SP`, which has the overall effect of making them twice as slow.

The best fix for this is probably to modify the ramping functionality to make sure it only does one write per setpoint when it is switched off.

### Acceptance criteria:

- A single "set current setpoint" command is sent to the kepco per write to `CURRENT:SP`
- There is a test that proves this

**Comment by DominicOram** [comment]
I believe that the test commented out in https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/411/commits/22bdba239fba170141ca5cc9aaeb758ba51b0489 may be because of this. Confirm fixed after this.

**Comment by JamesKingWork** [comment]
PRS:

- https://github.com/ISISComputingGroup/IBEX/pull/6180
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/412
