### ISSUE TITLE
Beckhoff: Harmonise code

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6153]
As a support person I would like all the Beckhoffs on site to use the same PLC and IBEX code. There are currently 3 versions out there:
* CRISP Jaws - On some homegrown ISIS code (https://github.com/ISISComputingGroup/BeckhoffPLCCode)
* IMAT rotation - On a legacy ESS solution (https://github.com/ISISComputingGroup/EPICS-MCAG_Base_Project)
* Muon Barn doors - On the latest ESS-IBEX collab code

## Acceptance Criteria
* All of the above are brought up to the latest ESS-IBEX collab code
* Confirm they all still work using new code
* Remove MCAG and the PLC_VERSION=0 tcioc code. (these are used to control the old PLC versions)

**Comment by DominicOram** [comment]
FYI @Simon-Cooper and @Steve-Cox-IDD-Motion

**Comment by Steve-Cox-IDD-Motion** [comment]
Thanks Jack

Steve

**Comment by rerpha** [comment]
CRISP won't be used until it's updated, so closing. re-commissioning will take 5 minutes from our end.
