### ISSUE TITLE
HVCAENA: Test on DETMON

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6158]
A new driver for the HV CAEN crates was pulled into the codebase in https://github.com/ISISComputingGroup/IBEX/issues/5544. This was because of the various parameters it had available and it is a more modern form of EPICS to the old driver (and cleaner code). The review bought up some reservations about the driver, namely:

- there are some discrepancies in the values given between the drivers, though generally, the new driver gives more values which could be promising
- the new driver did fail to connect at one point to a crate which the old driver could connect to (I did not manage to find the reason)
- the amount of logs produced when the failed connection occurred was a lot higher than the old driver

The decision was made to approve this new driver and test it on DETMON. This ticket is to do that testing (this should be done whilst the CAEN crates are active, possibly in a cycle).

## Acceptance criteria

- Set up both new and old drivers to look at the same IP addresses
- Blocks are set up on both the new and old drivers
- State of the drivers is monitored over a two week period
- Produced nexus files are reviewed for any discrepancies with Davide
- Amount of logs produced is reviewed
- Notes are written up to inform a decision on how to proceed with the use of old and new drivers

## Notes:

- Docs at: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN 
- You can test the values against the CAEN GECO (General Control Software) installed on NDADETMON

**Comment by FreddieAkeroyd** [comment]
Note: this doesn't build in VS2010 so you will need to deploy a devel build

**Comment by FreddieAkeroyd** [comment]
Or deploy the `EPICS_win10_x64` build already on `kits$` - or just a static version of the caen,  we have a devel static build but not copied to `kits$` currrently

**Comment by JamesKingWork** [comment]
Proposed because this would be preferable to do this with the CAEN crates active whilst in cycle

**Comment by JamesKingWork** [comment]
Added docs just in case we need to do the deploy again: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN#deployment-of-the-hvcaen-and-hvcaena-for-testing-on-detmon

**Comment by JamesKingWork** [comment]
Unfortunately, I am unable to get both drivers talking to the same IP addresses at the same time. Davide has agreed to verify the nexus file from just the new driver on it's own.

**Comment by JamesKingWork** [comment]
Amount of logs produced to be reviewed in https://github.com/ISISComputingGroup/IBEX/issues/6159. This ticket has simply taken much more time than expected so decided to split it off.

**Comment by JamesKingWork** [comment]
Update on this ticket:

- DETMON has now run with the HVCAENA for a couple of weeks and we have managed to produce about 3 days worth of nexus files whilst the driver has been running. The nexus files have been sent to Davide from him to check through
- Initially it took time to deploy the CAEN IOC correctly onto DETMON, I have added to the docs here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CAEN#deployment-of-the-hvcaen-and-hvcaena-for-testing-on-detmon
- Binary parameters were not searched for correctly by the driver, this was fixed here https://github.com/ISISComputingGroup/CAENHVAsyn/pull/4
- The new and old drivers could not talk to the same IPs at the same time (the old driver kept on getting disconnected errors and the new driver continuously printed operating system errors)
- The new driver also filled up the selog.sq3-wal quite regularly and caused troubles with writing nexus files because it stored the channel names as waveforms and updated the value every second, causing large arrays to be written to the sqlite database which is a write-ahead for the nexus file. This was improved here https://github.com/ISISComputingGroup/CAENHVAsyn/pull/5 but could be further improved if we don't need to use waveforms and by using I/O interrupts rather than scan loops (a ticket has been created here to handle that https://github.com/ISISComputingGroup/IBEX/issues/6608)
- After 3 days of running successfully the new driver then started writing a lot of logs reporting OS 10054 errors when trying to read CAEN system properties and channel names I am currently investigating why this is the case

**Comment by JamesKingWork** [comment]
Impeded waiting on a response from IS about the produced nexus files

**Comment by DominicOram** [comment]
Great work and well documented with good follow up tickets. Thanks!
