### ISSUE TITLE
Automatically check the state of InstrumentScripts on the instrument

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6160]
As a developer I would like to know when the instrument scripts are out of date. https://github.com/ISISComputingGroup/IBEX/issues/5907 already does this but there is not a suitable account for it to be run automatically through Jenkins.

## Acceptance Criteria
* There is an account that developers can use to get read-only access to at least C:\Instrument\scripts (or whole C:\Instrument\ tree) on all instruments
* The InstrumentScripts checker is run on jenkins using this account
* The credentials should be stored using jenkins credentials manager (https://www.jenkins.io/doc/book/using/using-credentials/)

**Comment by DominicOram** [comment]
FYI @ChrisM-S. I won't propose tis for now as it's not super urgent but if you manage to get it done whilst doing other things let us know.

**Comment by JamesKingWork** [comment]
Done so far:

- Add Jenkins job using the correct pipeline (put onto WallDisplay). See https://epics-jenkins.isis.rl.ac.uk/job/Instrument%20Scripts%20Checker/
- Create InstScripts$ share on NDXMAPS so we can access Instrument\Scripts in read-only
- Add Jenkins credentials to access InstScripts$
- For script checker changes see: https://github.com/ISISComputingGroup/InstrumentChecker/pull/37

Left to do:

- Add InstScripts$ share to other instruments and reenable them in the scripts_checker.py script
  - Command to do this can be found in shares\ISIS_Experiment_Controls\command_to_add_instscripts_share.txt
- When merged change Jenkins job to look at the master branch
