### ISSUE TITLE
Discuss: Meeting to discuss problems on POLREF

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6171]
POLREF are going to organise a meeting to talk about what happened in #6169 and more generally what happens when IBEX gets strange numbers from motors. We should talk with them. Things they may raise:

1. Is there a chance that motors can have moved when IBEX started with the strange numbers
2. Can we make sure that motors with strange numbers in are not allowed to be moved
3. Can we indicate if a motor get a strange number suddenly, i.e. large/very quick movements in an axis
4. What happens in a script if this happens

### Acceptance Criteria

1. Think about answers to questions, see #6170 
2. Go to meeting
3. Write up meeting and indicate any create tickets for anything we need to do

### Notes

- We should be careful not to make IBEX responsible for safety but if we can help we should do that

**Comment by John-Holt-Tessella** [comment]
Being organised by instrument scientist

**Comment by GRyall** [comment]
The expected meeting appears not to have happened, and given passage of time this ticket is no longer useful
