### ISSUE TITLE
SUPPORT: LET Oscillating Collimator does not run

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6173]
### Acceptance Criteria

- Oscillating collimator on LET should run

**Comment by John-Holt-Tessella** [comment]
![image](https://user-images.githubusercontent.com/7570055/106894307-af084c80-66e6-11eb-8d87-3492ecc79788.png)

Shows two runs I wonder whether it is homing correctly.

**Comment by John-Holt-Tessella** [comment]
email:

> Final thought I think the only place it can get stick is here:
>
> 1.	#OSCIL
> 2.	'****Step 4 - Oscillations************
> 3.	time1=TIME
> 4.	SP~a=vel
> 5.	PA~a=dist/2;BG~a;
> 6.	#CHECK1
> 7.	JP #CHECK1, @IN[7]=0
> 8.	check=_RP~a
> 9.	AM~a
> 10.	PA~a=-dist/2;BG~a;AM~a
> 11.	count=count+1
> 12.	time=TIME-time1
> 13.	'JP #HOMER, check>125
> 14.	JP#OSCIL
> 15.	EN
> 
> Is lines 6/7 which would happen if the home switch is never triggered (assume this is a trigger). Maybe we are not homing > correctly so the home switch is not in the collimator swing. But that is only a thought.

**Comment by John-Holt-Tessella** [comment]
![osciallating collimator](https://user-images.githubusercontent.com/7570055/107042074-3920e580-67b9-11eb-8e7a-e979dfb9d752.png)

Sweep angle and homing switch

**Comment by John-Holt-Tessella** [comment]
Motor was warn hardware to look at it

**Comment by KathrynBaker** [comment]
I've been watching the information flowing through exp controls for this, and the work no longer needs any support from us.
