### ISSUE TITLE
SystemTests: Fix devices with binary interrfaces

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6177]
### Acceptance Criteria

Tests pass for devices with binary interfaces:

- fins (%PYTHON3% run_tests.py -t helium_recovery_plc
- skb chopper (%PYTHON3% run_tests.py -t skf_mb350_chopper )

### Notes

Requires someone with access to lewis repo to merge

**Comment by John-Holt-Tessella** [comment]
PR;

- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/100
- https://github.com/ess-dmsc/lewis/pull/291

You may need to commit for 291 I am unsure how this works

**Comment by John-Holt-Tessella** [comment]
Added during the sprint it was originally a flash review to quickly fix the system tests but code became to complicated for flash review

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/318 will also be required

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6194
