### ISSUE TITLE
SANS2D: Log Diagnostic Information from Stober Drives

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6183]
As a motion control specialist, I want to collect diagnostic information about the performance of the Stober drives on SANS2D.
As a developer, I want IBEX to communicate with the Stober drives and log diagnostic information.

#### Acceptance Criteria
1. IBEX has an IOC capable of collecting diagnostic information from a Stober drive
1. IBEX logs diagnostic information from a Stober drive

#### Notes
1. When the Stober drives are installed on SANS2D, the intention is that they will be wired up to provide diagnostic information, that can be used to monitor their performance.
1. At the time of writing, there are no detail of what sort of diagnostic information a Stober drive can provide.  Liaise with the motion control team to find out.

**Comment by DominicOram** [comment]
It's looking unlikely we will be communicating directly with the Stobers now. If there is diagnostic data we want to log we can pull it through the Beckhoff. @Steve-Cox-IDD-Motion and @Simon-Cooper, is there data you would like us to log?

**Comment by Steve-Cox-IDD-Motion** [comment]
> It's looking unlikely we will be communicating directly with the Stobers now. If there is diagnostic data we want to log we can pull it through the Beckhoff. @Steve-Cox-IDD-Motion and @Simon-Cooper, is there data you would like us to log?

There should be some good diagnostic data that we can get from the drives and we will just need to check that they are setup to pass these process variables on to the Beckhoff. One example is the 'Utilisation %' variable, which shows how much of the available torque is being used. This would be great to be able to record the maximum value of once per axis, per move and log somewhere. We will also be adding some condition monitoring for the motors and gearboxes to record temperature.

I will add a task in the project to check what data can be passed and then schedule a meeting with us and some of the operations teams to select the useful diagnostic data.

**Comment by rerpha** [comment]
Have created blocks for motor temp, gearbox temp and torque value per axis - these live in the "beckhoff_diagnostics" group on SANS2D. 

Demonstrated these on the log plotter to motion and the scientists and they were happy. 

To review: check these blocks exist and you can log them over time - they may be disconnected at the moment as some tweaks are being made to the Beckhoff (it may also be turned off)

**Comment by daryakoskeroglu** [comment]
All good, thank you!
