### ISSUE TITLE
SANS2D: Final Migration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6184]
As a developer, I want to check that IBEX has been correctly migrated to SANS2D prior to the start of Cycle 2021/02.
As a SANS2D scientist, I want to see IBEX successfully controlling my instrument before Cycle 2021/02.

#### Acceptance Criteria
1. Re-check the migration of IBEX to SANS2D
1. Ensure IBEX can correctly control SANS2D

#### Notes
1. The initial migration of SANS2D happened prior to the long shutdown.  The Baldor drives are expected to be replaced during the long shutdown.  The purpose of this ticket is to ensure that everything remains ready for SANS2D to re-start operations using IBEX in Cycle 2021/02

**Comment by KathrynBaker** [comment]
SANS2D has been migrated and is running happily in IBEX. Any further work will be undertaken and managed as operational/other
