### ISSUE TITLE
WISH: Final Migration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6185]
As a developer, I want to check that IBEX has been correctly migrated to WISH prior to the start of Cycle 2021/02.
As a WISH scientist, I want to see IBEX successfully controlling my instrument before cycle 2021/02.

#### Acceptance Criteria
1. Re-check the migration of IBEX to WISH
1. Ensure IBEX can correctly control WISH

#### Notes
1. The initial migration of WISH happened at an earlier stage of the long shutdown.  The purpose of this ticket is to ensure that everything remains ready for WISH to re-start operations using IBEX.

**Comment by KathrynBaker** [comment]
WISH has been running with IBEX, I am closing this ticket as any outstanding work will be captured and managed separately
