### ISSUE TITLE
OFFSPEC: Final Migration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6186]
As a developer, I want to check that IBEX has been correctly migrated to OFFSPEC prior to the start of Cycle 2021/02.
As a OFFSPEC scientist, I want to see IBEX successfully controlling my instrument before cycle 2021/02.

#### Acceptance Criteria
1. Re-check the migration of IBEX to OFFSPEC
1. Ensure IBEX can correctly control OFFSPEC

#### Notes
1. The initial migration of OFFSPEC happened at an earlier stage of the long shutdown.  The purpose of this ticket is to ensure that everything remains ready for OFFSPEC to re-start operations using IBEX.

**Comment by John-Holt-Tessella** [comment]
When we talked earlier it was suggested that this was just the motion part. If it is the whole instrument we will need more tickets.

**Comment by kjwoodsISIS** [comment]
Control of OFFSPEC requires both control of motion and of the spin-echo system.
   * The scope of the Reflectometry IOC is limited to control of motion only.
   * Control of the spin-echo system is currently performed by LabVIEW code (originally developed at Delft University).
      * The future of the spin-echo system requires discussion with the instrument scientists.
         * The current spin-echo system runs on Windows 7 under an old version of LabVIEW.
         * Delft University is unable to provide support for the current spin-echo system (the original developer is understood to have retired).
      * One possible approach is to move the spin-echo system to its own dedicated PC and use lvDCOM to provide a communications interface between it and IBEX.

**Comment by KathrynBaker** [comment]
The most recent round of testing has gone well and according to the Group Leader as well as the contacts in our team they expect to be using IBEX from this point forwards. There will likely be things found in the future, but the migration of IBEX to OFFSPEC is complete.
