### ISSUE TITLE
HIFI: Final Migration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6188]
As a developer, I want to check that IBEX has been correctly migrated to HIFI prior to the start of Cycle 2022/01.
As a HIFI scientist, I want to see IBEX successfully controlling my instrument before cycle 2021/02.

#### Acceptance Criteria
1. Re-check the migration of IBEX to HIFI
1. Ensure IBEX can correctly control HIFI

#### Notes
1. The initial migration of HIFI happened at an earlier stage of the long shutdown.  The purpose of this ticket is to ensure that everything remains ready for HIFI to re-start operations using IBEX.

**Comment by KathrynBaker** [comment]
This process is now handled differently.
