### ISSUE TITLE
MuSR: Test remaining cryo equipment

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6198]
Spun off from https://github.com/ISISComputingGroup/IBEX/issues/6112. 

As noted in the ticket by @Tom-Willemsen there is some remaining cryogenics equipment to test. Both uDR3 and uDR4 are scheduled to be cooled down on MuSR before cycle, we can piggyback onto those tests to check comms. Scientist will let us know when we can do this.

#### Acceptance Criteria:
- uDR3 and uDR4 work as intended

**Comment by rerpha** [comment]
from doing https://github.com/ISISComputingGroup/IBEX/issues/5957 we're not sure how the mercury is controlling certain things, it might be easier to test it fully when the two fridges come on. We will try and do everything we can in that ticket but it'd be good to check that it all works as it should.

**Comment by JamesKingWork** [comment]
> from doing #5957 we're not sure how the mercury is controlling certain things, it might be easier to test it fully when the two fridges come on. We will try and do everything we can in that ticket but it'd be good to check that it all works as it should.

When you say how it is controlling certain things what things do you mean? Also is it the LabVIEW you're not sure about or the EPICS driver or the Mercury itself?

**Comment by rerpha** [comment]
> > from doing #5957 we're not sure how the mercury is controlling certain things, it might be easier to test it fully when the two fridges come on. We will try and do everything we can in that ticket but it'd be good to check that it all works as it should.
> 
> When you say how it is controlling certain things what things do you mean? Also is it the LabVIEW you're not sure about or the EPICS driver or the Mercury itself?

In the udr3/4 low and high configurations we're not sure whether the mercury is controlling some of the fridges or lakeshores. We should double check how it's done in SECI. For now we're just checking TPAR files, adding blocks that don't already exist etc. It's quite difficult to check the COM ports/card addresses for the mercury without the hardware being on for certain so we can compare against the values in the SECI configs.

**Comment by rerpha** [comment]
Perhaps worth noting on this ticket that the king fridge and corresponding configs have already been tested with the hardware on MuSR.

**Comment by JamesKingWork** [comment]
Two problems have emerged from the initial testing:

- Lakeshore372 turns the heater off when set from the front panel and r.settemp
- Triton control system on a separate machine runs slowly when connected to IBEX (possibly due to polling rates)

Investigating today. Specifically testing whether [this PR](https://github.com/ISISComputingGroup/EPICS-lakeshore372/pull/3) fixes Lakeshore372 issue and whether [this PR](https://github.com/ISISComputingGroup/EPICS-ioc/pull/599/files) fixes the Triton issues.

- The lakeshore372 PR changes the setpoint from scanning every second to being passive
- The Triton PR allows two configurable poll rates so we can avoid overloading the device

**Comment by JamesKingWork** [comment]
Further investigation of the lakeshore 372 shows that the script was trying to set the heater range with a float but it requires an integer

**Comment by JamesKingWork** [comment]
When using a polling rate of 15 seconds for each channel the control software for the triton is much faster and there doesn't seem to be any issues with valves not opening. I think the correct solution is to make this configurable via macros with a default polling rate of 15 seconds on the channels and 1 second on everything else.

**Comment by JamesKingWork** [comment]
PRs and tickets:

- https://github.com/ISISComputingGroup/EPICS-ioc/pull/599/files
- https://github.com/ISISComputingGroup/EPICS-lakeshore372/pull/3
- https://github.com/ISISComputingGroup/IBEX/issues/6300

**Comment by JamesKingWork** [comment]
Instrument scientists are going to test condensing soon and will report back any problems. With the 2 above issues fixed they are currently happy that the control of the device is good.

**Comment by JamesKingWork** [comment]
> Further investigation of the lakeshore 372 shows that the script was trying to set the heater range with a float but it requires an integer (bug documented in #6300). The problem of overwriting the value set on the front panel seems to be resolved.

The fix to this was to remove the decimal place and let tpar_loader.py correctly decide what is a float and what is an integer.

**Comment by JamesKingWork** [comment]
Testing with the Triton on MuSR is now complete and they are happy, they want to do a final test with EMU and then consider it complete. The final test they want to do is a representative soak test including a piece of sample environment kit to see temperature changes and switching between field modes.

**Comment by JamesKingWork** [comment]
EMU have also now finished tests and are happy that the new Triton changes will not adversely affect their work
