### ISSUE TITLE
MuSR: Test ZF Stability

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6199]
Spun off from https://github.com/ISISComputingGroup/IBEX/issues/6112.

Requires https://github.com/ISISComputingGroup/IBEX/issues/6152 and as such couldn't be done with the original ticket. Test the stability of the ZF stability on MuSR.

**Comment by Tom-Willemsen** [comment]
Specifically:
- Verify that the loop time displayed on the ZF system comes down from ~1000ms currently to ~500ms or less on average
- Adjust feedback to try and find a compromise between zeroing quickly, and not fluctuating too much at zero. It is currently set at 0.2 which is very conservative, try 0.5 and adjust from there
- Verify that the overall stability of the system, as measured by the fixed magnetometer probe in the cabin, is comparable to the SECI system [note: a scientist will need to be on site for this; the fixed probe has no computer interface, only displays in the cabin]

**Comment by Tom-Willemsen** [comment]
There is also a potential issue with the Y kepco losing comms after extended use. Not clear if this is just due to command rate being too high or faulty hardware. Currently requires an ioc restart to fix - need to investigate.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-kepco/pull/14

**Comment by Tom-Willemsen** [comment]
The system is more noisy than expected. On EMU we achieve a typical stability of around ~1mG, on MuSR it is looking more like ~10mG. This noise is present in both manual and auto mode, which suggests that it may be a problem with the magnetometer itself (in manual mode the kepcos are not adjusted, so the noise cannot be caused by them). I am in conversations with the scientist about this (along with @JamesKingWork @rerpha ).

**Comment by Tom-Willemsen** [comment]
Suggestion from scientist: we may need to smooth the input signal, either in epics via something like a `compress` record which can calculate a moving average over a defined time period, or as some option that we need to configure in the cDAQ.

**Comment by rerpha** [comment]
I have added the smoothing functionality in these PRs:

https://github.com/ISISComputingGroup/EPICS-ioc/pull/590
https://github.com/ISISComputingGroup/EPICS-zfmagfld/pull/6
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/421

**Comment by rerpha** [comment]
We have patched the smoothing onto MuSR and it seems to be zeroing the field out much more nicely. I think #6261 may have been the cause but i'm not certain. Using 10 as the NUM_SAMPLES macro seems to be reliable but i've asked the IS to double check and make sure it doesn't update too slowly.

**Comment by rerpha** [comment]
OK, we have left some smoothing on, it seems to be fairly stable now but there are some other things we should try which I have detailed in #6285 that will attempt to get the ZF fluctuations to a similar state to what SECI was giving. I will respond to IS now with a link to the ticket.
