### ISSUE TITLE
MuSR: Test booster heater scripts

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6200]
Spun off from https://github.com/ISISComputingGroup/IBEX/issues/6112. Test booster heater scripts when cryostat with boost heater is available - scientists hope this will be sometime before cycle.

**Comment by Tom-Willemsen** [comment]
Cryostat is being cooled end of this week and tests are expected to be able to start Friday (12th)

**Comment by Tom-Willemsen** [comment]
Have been doing testing/debugging today. Primary functionality is working ok.

Remaining items to test on Monday:
- Booster heater appears to be being switched off a little bit too early, this could cause a temperature dip and therefore longer equilibration times
- Test with white cryostat

**Comment by Tom-Willemsen** [comment]
Scientist is now happy with the operation of the script after testing basic functionality with the white cryostat (actually the blue cryostat - but they are essentially the same) this morning. 

To review, check that recent changes to the code in `temp_routines.py` on MuSR's config branch are sensible.

**Comment by rerpha** [comment]
Scripts look sensible.
