### ISSUE TITLE
IOC: Create OPI and simple tests for AFG3021B

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6202]
The Tektronic AFG3021B is going to be used on INTER next cycle and although there is an IOC it was written before we created OPIs device emulators and testing framework. Now would be a good time to add these.

### Acceptance Criteria

1. #6314 is finished first
1. Create OPI for device
2. Create tests and device emulator 
3. Complete the documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Tektronix-AFG3XXX
4. Send OPI to INTER and check all functionality is present

### Notes

There is also #6031 which is an extension to add any missing functionality for WISH

**Comment by John-Holt-Tessella** [comment]
PR:

- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/12

**Comment by DominicOram** [comment]
In discussion with INTER they said that they are likely only doing commissioning and one experiment on IBEX, this experiment will be later in the cycle and may not use the AFG3021B.

**Comment by rerpha** [comment]
Can confirm that the VI for INTER and WISH are exactly the same, which makes this job a bit easier!

**Comment by rerpha** [comment]
The VI contains a text box which enables the user to send custom commands to the device, so I'm going to add this into the IOC and OPI

**Comment by rerpha** [comment]
Have sent off an email to INTER to discuss which bits of the device would be useful to control from the OPI, and test with the emulator. 
We will speak to wish about their requirements for the AFG after this cycle, they have said they are very busy at the moment. From a brief discussion they weren't sure the last time they used the AFG so they may not need anything extra from what INTER control.

**Comment by FreddieAkeroyd** [comment]
There looks to be an OPI at https://github.com/icshwi/e3-afg3000 which is for an ESS implementation of the ioc that may be worth a look too https://bitbucket.org/europeanspallationsource/m-epics-afg3000/src/master/

**Comment by rerpha** [comment]
> There looks to be an OPI at https://github.com/icshwi/e3-afg3000 which is for an ESS implementation of the ioc that may be worth a look too https://bitbucket.org/europeanspallationsource/m-epics-afg3000/src/master/

cool, we may be able to use that depending on INTERs requirements. This is a stupid question, but I thought the ESS were using epics v4, will there be any differences in db files etc or is it all the same? is v4 just v3 with PVAccess or are there more changes?

**Comment by FreddieAkeroyd** [comment]
So v4 can be done in two ways - a pure v4 ioc that would use e.g. `pvDatabase` or rpc and have no DB files, or it could be a v3 ioc where v4 data is the v3 pvs over pv access with potentially some groups of db records being exposed as v4 structured data. Most ESS iocs I have seen are v3 iocs with the option to read DB records over pvAccess rather than channel access, but there may be some pure v4 ones. If you do a pure v4 ioc you cannot use of most existing epics support modules, so it would likely be used for specialist applications. This particular driver is a regular v3 stream device ioc, so should be easy to use.

**Comment by rerpha** [comment]
OK, talked to INTER, their typical use is that they set up the front panel physically then remotely trigger it using the button in SECI. Our IOC can't do a manual trigger at the moment so I am going to change the acceptance criteria to
A) create a basic OPI with a trigger button on 
B) implement trigger record in IOC
C) test with emulator

then call this ticket done. If WISH or the SANS group require any more functionality I will spin those out into a separate ticket

**Comment by rerpha** [comment]
PRs:

support(adding trigger record) - https://github.com/ISISComputingGroup/EPICS-Tektronix_AFG3XXX/pull/1
ioc tests - 
emulator - 
opi -

**Comment by rerpha** [comment]
to review: 

check trigger pv looks to be doing something sensible and is tested now
look at conversation with INTER and SANS group scientists to gather requirements and make sure they match the OPI

**Comment by rerpha** [comment]
Just sent off an email to INTER and SANS group of new device screen.
