### ISSUE TITLE
INTER: Weeder WTDAC-M 

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6203]
As an instrument scientists I want to use the Weeder WTDAC-M on INTER; this is part of my usual kits. It is an Analog Output Card on my computer.

### Acceptance Criteria
   1.  Create IOC, emulator and tests
   2.  Create OPI

### Notes
   * This is not needed until after the long shutdown.
   * [Weeder WTDAC-M](https://weedtech.com/analog-out.html) on manufacturer's web-site
   * Manual is here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Weeder WTDAC-M`

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/629

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6707

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/EPICS-weederWTDAC/pull/1
