### ISSUE TITLE
Script generator: exception on entering data

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#6204]
As a developer I would like the script generator to operate without throwing exceptions

As a scientist I would like the correct contents of the script generator table to be saved/generated when I press save/generate.

An exception (see notes) is thrown on entering data into the script generator. Steps to reproduce:
- Load a file into the script generator.
- Tab across the table, entering values where appropriate
- When entering data on the last valid column, the exception above is thrown and the save button remains greyed out, even if the entered data is correct.

### Acceptance criteria
- Exception is no longer thrown & behaviour of save button is correct
- There is a Squish test to ensure this doesn't re-occur

### Notes
Exception stack trace:

```
*2021-02-09 14:45:39.375 [main] ERROR org.eclipse.ui.workbench - Index 4 out of bounds for length 4
	java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	java.base/java.util.Objects.checkIndex(Objects.java:372)
	java.base/java.util.ArrayList.get(ArrayList.java:459)
	uk.ac.stfc.isis.ibex.ui.scriptgenerator.views.ActionsViewTable.setRows(ActionsViewTable.java:214)
	uk.ac.stfc.isis.ibex.ui.scriptgenerator.views.ScriptGeneratorViewModel.lambda$15(ScriptGeneratorViewModel.java:499)
	org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3987)
	org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3615)
	org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	uk.ac.stfc.isis.ibex.scriptgenerator.product.Application.start(Application.java:47)
	org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```
```

**Comment by John-Holt-Tessella** [comment]
Can just tab across rows or copy and paste where you are in the last row

**Comment by John-Holt-Tessella** [comment]
Suspected fix:

```
--- a/base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
+++ b/base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
@@ -233,7 +233,7 @@ public class ActionsViewTable extends DataboundTable<ScriptGeneratorAction> {
                if (!viewer.getTable().isDisposed()) {
                        int focusRow = getSelectionIndex();
                        ScriptGeneratorAction previousSelection = firstSelectedRow();
-                       int focusColumn = NON_EDITABLE_COLUMNS_ON_LEFT;
+                       int focusColumn = 0;

                        if (shiftCellFocusToNewlyAddedRow) {
                                focusRow = viewer.getTable().getSelectionIndex() + 1;
@@ -241,7 +241,7 @@ public class ActionsViewTable extends DataboundTable<ScriptGeneratorAction> {
                                // When no focus is selected getFocusCell returns null
                                var focusCell = Optional.ofNullable(viewer.getColumnViewerEditor().getFocusCell());
                                if (focusCell.isPresent()) {
-                                       focusColumn = focusCell.get().getColumnIndex();
+                                       focusColumn = focusCell.get().getColumnIndex() - NON_EDITABLE_COLUMNS_ON_LEFT;
                                }
                        }

```

But needs tetst

**Comment by John-Holt-Tessella** [comment]
Testable outcome is that the edit value is no longer selected and validation does not run

**Comment by JamesKingWork** [comment]
> Suspected fix:
> 
> ```
> --- a/base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
> +++ b/base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
> @@ -233,7 +233,7 @@ public class ActionsViewTable extends DataboundTable<ScriptGeneratorAction> {
>                 if (!viewer.getTable().isDisposed()) {
>                         int focusRow = getSelectionIndex();
>                         ScriptGeneratorAction previousSelection = firstSelectedRow();
> -                       int focusColumn = NON_EDITABLE_COLUMNS_ON_LEFT;
> +                       int focusColumn = 0;
> 
>                         if (shiftCellFocusToNewlyAddedRow) {
>                                 focusRow = viewer.getTable().getSelectionIndex() + 1;
> @@ -241,7 +241,7 @@ public class ActionsViewTable extends DataboundTable<ScriptGeneratorAction> {
>                                 // When no focus is selected getFocusCell returns null
>                                 var focusCell = Optional.ofNullable(viewer.getColumnViewerEditor().getFocusCell());
>                                 if (focusCell.isPresent()) {
> -                                       focusColumn = focusCell.get().getColumnIndex();
> +                                       focusColumn = focusCell.get().getColumnIndex() - NON_EDITABLE_COLUMNS_ON_LEFT;
>                                 }
>                         }
> ```
> 
> But needs tetst and does not work for slecting a non-editable cell.

This suggested fix causes similar out by one exceptions when selecting non-editable rows e.g. for copy and pasting

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/ibex_gui/pull/1264
