### ISSUE TITLE
DCLAB: Technician needs help with connecting power supplies to IBEX for testing

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#6205]
As a power supply technician, I would like a bit of help to get IBEX on a temporary machine working to control my power supplies as I have several to test.

***Acceptance Criteria***
1. I can connect either of my current types of PSU units to IBEX (Danfysik or Lambda TDK) one at a time for  testing through the MOXA I now have configured in my lab.
2. I'm able to use IBEX with a simple configuration set up to allow me to control a power supply of either type from the appropriate IOCs

***Notes:***
1. There is now a networked DCLAB MOXA configured with cables which can be connected through a 25-way D-connector to the Danfysik or via a straight through RJ45 connector to the Lambda TDK unit.  It might be worth putting corresponding IOCs on COM5 and COM6 so that changing types of PSU only requires choosing the right cable.

**Comment by DominicOram** [comment]
I have set up a TDK and a Danfysik on NDXSCIDEMO. They I have left both IOCs running, with labelled cables in two ports so that they can easily swap them around. They will require https://github.com/ISISComputingGroup/IBEX/issues/5871 but that can be done later.
