### ISSUE TITLE
System: Harmonise end of run scripts

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6206]
As a developer I want to support a single set of end of run script used by all instruments. These should be configured using a configuration script. Currently the script on different instruments may be completely custom so this ticket is to distil these scripts into a single script and configuration file. The initial work and explanation should have been created as part of #6175.

### Acceptance Criteria

- There is a single set of end of run scripts
- All instruments have the necessary configuration file to run these
- Optional (decide in planning): current instruments are modified to use the new scripts

**Comment by DominicOram** [comment]
How does this differ from https://github.com/ISISComputingGroup/IBEX/issues/5902?

**Comment by John-Holt-Tessella** [comment]
duplicate
