### ISSUE TITLE
CHIPIR: IOC & OPI for Hameg HM8123 Universal Counter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6210]
As a CHIPIR scientist I want to be able to control a Hameg HM8123 Universal Counter in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Hameg HM8123 Universal Counter
1. Using genie_python, I can control a Hameg HM8123 Universal Counter

#### Notes
1. Check the [CHIPIR Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details).
1. The manufacturer's web-site describes the [Hameg HM8123 Universal Counter](https://www.rohde-schwarz.com/uk/product/hm8123-productstartpage_63493-44102.html).
1. A copy of the Hameg HM8123 Universal Counter manual is located here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Hameg__HM8123_3GHz_Programmable_Counter`.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Instruments\CHIPIR\CHIPIR - HAMEG 8123\`).
1. We already have an IOC (albeit an old IOC) for the Hameg HM8123 Universal Counter (see #117).

time in planning 01:16 23/5/24

**Comment by rerpha** [comment]
(in progress) 
branches are https://github.com/ISISComputingGroup/EPICS-ioc/pull/867
https://github.com/ISISComputingGroup/EPICS-Hameg_8123/pull/1

**Comment by rerpha** [comment]
Pic of front panel: 
![image](https://github.com/ISISComputingGroup/IBEX/assets/14823767/fc046d34-9831-429a-9532-53a107c7c015)
