### ISSUE TITLE
CHIPIR: IOC & OPI for Tektronix DMM 4040/4050 Multimeter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6211]
As a CHIPIR scientist I want to be able to control a Tektronix DMM 4040 Multimeter in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Tektronix DMM 4040 Multimeter
1. Using genie_python, I can control a Tektronix DMM 4040 Multimeter

#### Notes
1. Check the [CHIPIR Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details).
1. The manufacturer's web-site describes the [Tektronix DMM4050 and DMM4040 Digital Multimeters](https://uk.tek.com/datasheet/dmm4050-4040-digital-multimeter).
1. A copy of the Tektronix DMM 40x0 Multimeter manual is located here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Tektronix__DMM40x0_Digital_Multimeter`.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Tektronix DMM 4040`).
1. We already have an IOC (albeit an old IOC) for the Tektronix DMM 4040 (see #120).

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-Tektronix_DMM_40X0/pull/1
https://github.com/ISISComputingGroup/EPICS-ioc/pull/847
https://github.com/ISISComputingGroup/ibex_gui/pull/1701
https://github.com/ISISComputingGroup/IBEX/pull/8327


As this IOC doesn't really do all that much i decided it wasn't worth writing an emulator and tests for.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/624
