### ISSUE TITLE
CHIPIR: IOC & OPI for Stanford PS350 High Voltage PSU

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6213]
As a CHIPIR scientist I want to be able to control a Stanford PS350 high-voltage PSU in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Stanford PS350 high-voltage PSU 
1. Using genie_python, I can control a Stanford PS350 high-voltage PSU 

#### Notes
1. Check the [CHIPIR Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details).
1. The manufacturer's web-site describes the [Stanford PS300 Series HV PSUs](https://www.thinksrs.com/products/ps300.html).
1. A copy of the Stanford PS300 Series manual is located here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Stanford_Research__Series_300_Power_Supplies`.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Stanford PS350`).
1. There are existing IOCs for Stanford PS3x0 devices (see https://epics-controls.org/resources-and-support/modules/hardware-support).

**Comment by rerpha** [comment]
front panel: ![image](https://github.com/ISISComputingGroup/IBEX/assets/14823767/33d2d77a-8c2d-48c9-9783-dc99aba4347b)
there is an existing streamdevice IOC, but there are some things missing from it - we'd need to add the limits and trips statuses. These are simple one-line commands however.

**Comment by rerpha** [comment]
Have cloned the IOC: https://github.com/ISISComputingGroup/EPICS-SRS_PS3XX - this will need modifying to: 
- include the extra commands 
- be included in epics-top .gitmodules
- build on our system

**Comment by rerpha** [comment]
this is "low hanging fruit" again by the looks of it, so i'm going to just do it.

**Comment by rerpha** [comment]
whoops, we already have an entire ioc for it, idiot

**Comment by rerpha** [comment]
ok, actually, we already have everything needed for this - closing.
