### ISSUE TITLE
CHIPIR: IOC & OPI for Stanford SR400 Photon Counter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6214]
As a CHIPIR scientist I want to be able to control a Stanford SR400 photon counter in my experiments.

#### Acceptance Criteria
1. Using the IBEX client, I can control a Stanford SR400 photon counter
1. Using genie_python, I can control a Stanford SR400 photon counter

#### Notes
1. Check the [CHIPIR Instrument wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CHIPIR-Instrument-Details).
1. The manufacturer's web-site describes the [Stanford SR400](https://www.thinksrs.com/products/sr400.html).
1. A copy of the Stanford SR400 manual is located here: `\\isis\shares\ISIS_Experiment_Controls\Manuals\Stanford_Research__SR400_Gated_Photon_Counter`.
1. The IOC & OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Stanford SR400 Photon Counter`).

timei nplanning 01:23 23/5/24

**Comment by zsoltkebel** [comment]
## PRs

- https://github.com/ISISComputingGroup/ibex_gui/pull/1711
