### ISSUE TITLE
CHIPIR: OPI for Jaws & Height

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6219]
As a CHIPIR scientist I want to be able to control the height of my jaws set and the position of the blades.

#### Acceptance Criteria
1. Using the IBEX client, I can control the jaws height & jaw blade positions
1. Using genie_python, I can control the jaws height & jaw blade positions

#### Notes
1. The CHIPIR jaws (height & blades) are jaws are Galil controlled.
1. Check the [CHIPIR Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details).
1. The OPI must offer functionality equivalent to the existing VI (located here: `C:\LabVIEW Modules\Drivers\Motion Control\Jaws & Height`).

**Comment by rerpha** [comment]
this is covered by the OPI in #6218
