### ISSUE TITLE
HIFI Cryomag: System IOC integrate main magnet ramp tables and further OPI improvements

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6221]
As a user on HIFI I would like to be able to select the ramp table being used by the main magnet from a selection of files so that I can ensure my rates remain suitable for the sample and magnet

** Acceptance Criteria **
1. The ramp table functionality as detailed in the system documents in  http://www.facilities.rl.ac.uk/isis/projects/ts1/HIFICryomagnetSoftwareImprovement/Detailed%20Requirements/Forms/AllItems.aspx are implemented
1. Disabled items on the OPI are greyed out to limit confusion
1. The Icon should be updated to something interesting
1. There are a few values that have the wrong unit in the z switching aspect

**Comment by Tom-Willemsen** [comment]
Item 1 spun out into https://github.com/ISISComputingGroup/IBEX/issues/6342
Items 2 & 3 fixed in https://github.com/ISISComputingGroup/ibex_gui/pull/1275
Item 4 fixed in https://github.com/ISISComputingGroup/EPICS-ioc/pull/604

Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6343
