### ISSUE TITLE
IOC System Test: Remove arbitrary sleep on every caput

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6225]
As a developer I would like the IOC system tests to be as fast as possible (whilst still being as reliable as possible). The biggest factor in slowing down is the 1 second sleep that is done on every call to `set_pv_value`. Whilst this sleep may occasionally improve reliability it is not needed most of the time and so we should remove it as much as possible.

## Acceptance Criteria
* When writing a suite I can specify a default of no sleep
* One of the slowest suits is converted to be default of no sleep, with sleeps potentially used in some places to maintain reliability

**Comment by John-Holt-Tessella** [comment]
The 1 second sleep was introduced when we got rid of wait=True on the cput (I think) because this does not work for some pvs. Maybe instead something like a set and check the pv has been set and then continue would be better.

**Comment by DominicOram** [comment]
If required, setting it to 0 seems fine for most tests

**Comment by FreddieAkeroyd** [comment]
Were we doing wait=True on every set_pv_value ? which pvs did it not work for?

**Comment by DominicOram** [comment]
> The 1 second sleep was introduced when we got rid of wait=True on the cput (I think) because this does not work for some pvs. Maybe instead something like a set and check the pv has been set and then continue would be better.

I'm not 100% sure this is true. Matt added it in 2017 (https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/b529beeba143e1e1fb85026075365b5aa78089f3/utils/channel_access.py) with a comment about waiting for Lewis.

**Comment by FreddieAkeroyd** [comment]
Isn't lewis normally faster than a real device? Or is it related to lewis backdoor interactions? Adding wait=True should not usually break something, but if the pv logic has not been done through tracable operations (FLNK, PP) then the callback will complete before the operation has finished.

**Comment by FreddieAkeroyd** [comment]
As discussed on thread on  ISISComputingGroup/EPICS-IOC_Test_Framework#415 we will work to remove automatic delays in `set_pv_value` and add any necessary delays (for emulator processing etc.) as explicit `sleep` commands with a comment as to why the delay is needed.

**Comment by DominicOram** [comment]
I think we can call this closed with the linked ticket. The mechanism is there, we should migrate tests as and when people edit them.
