### ISSUE TITLE
ZOOM: Test New SANS Sample Changer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6226]
As a developer, I want to test the new SANS sample changer, so that I can be confident it works as expected.
As a ZOOM scientist, I want to see the new sample changer GUI correctly controlling my sample changer.

#### Acceptance Criteria
1. Test the new SANS sample changer
   1. in the IBEX client
   1. in genie_python
1. Confirm with the scientist(s) that it works as expected

#### Notes
1. The new SANS sample changer is common to all the SANS instruments.
1. Contact Diego A-V and/or James D to arrange a specific time/date (in early March)

**Comment by kjwoodsISIS** [comment]
From the instrument scientist:

> From: Diego 
> Sent: 11 February 2021 11:09
> To: Kevin; James
> Subject: RE: Testing new Sample Changer GUI on ZOOM
> 
> Hi Kevin,
> 
> No problem at all, I guess that then you can let us know when the new GUI is ready and then I’m sure that either James or myself can pop onsite.
> 
> Thanks,
> Diego
> 
> ---------------------------------------------------------------
> 
> From: Kevin
> Sent: 11 February 2021 11:01
> To: Diego; James
> Subject: RE: Testing new Sample Changer GUI on ZOOM
> 
> Hi Diego,
> 
> Thanks for the fast reply.  I’m afraid, today is too soon for us.  We’ll need a little time to prepare and to deploy the new GUI to ZOOM.  I am hoping we could do the work in early March.
> 
> Kevin

**Comment by DominicOram** [comment]
Once scientists are happy update their synoptics/device screens

**Comment by DominicOram** [comment]
Scientists are happy, see email thread in Experiment Controls inbox
