### ISSUE TITLE
LOQ: Test New SANS Sample Changer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6227]
As a developer, I want to test the new SANS sample changer, so that I can be confident it works as expected.
As a LOQ scientist, I want to see the new sample changer GUI controlling my sample changer.

#### Acceptance Criteria
1. Test the new SANS sample changer
   1. in the IBEX client
   1. in genie_python
1. Confirm with the scientist(s) that it works as expected

#### Notes
1. The new SANS sample changer is common to all the SANS instruments.
1. Contact Steve K to arrange a specific time/date.  Steve's time is limited in late March, so an early date in March is preferred.

**Comment by kjwoodsISIS** [comment]
From the instrument scientist:

> From: Stephen K
> Sent: 11 February 2021 10:53
> To: Kevin
> Subject: RE: Testing new Sample Changer GUI on LOQ
> 
> Hi Kevin,
> 
> Yes, Sarah did mention it to me. Happy to volunteer.
> 
> So in general, Thursdays & Fridays are better for me. I’m not saying these are the only possibilities, just that my working week tends to be front-loaded.
> 
> I’m going to say I’m totally unavailable the week of Mar 22 and the week of April 12.
> 
> And this coming cycle LOQ does have quite a bit on the schedule. In particular, I am going to need a functioning sample stack by the end of the week before startup (whether that is my current OPI or the new one) so that’s the hard deadline.
> 
> Other than that, I’ll try to be flexible. To be honest, the sooner we can do some of this, the better (i.e, later this month or early Mar), as far as I’m concerned.
> 
> Kind regards,
> Steve
>

**Comment by DominicOram** [comment]
Once scientists are happy update their synoptics/device screens

**Comment by DominicOram** [comment]
Various hotfixes applied to LOQ during this testing, see https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information--hotfixes.

**Comment by DominicOram** [comment]
Now on instrument and happy using it over cycle
