### ISSUE TITLE
LARMOR: New Beckhoff for Bench

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6228]
During the long shutdown, the encoder on the LARMOR bench will be replaced by a new absolute encoder and replaced with a Beckhoff controller.  As a scientist, I want IBEX to support the new controller.

#### Acceptance Criteria
1. When the new controller is installed
   1. update the bench motion settings in IBEX (if required)
   1. test motion of the bench with the motion control group.

#### Notes
1. Liaise with the motion control group to understand requirements & timings.
1. See also #4662.

**Comment by rerpha** [comment]
> * The descriptions on axes 2+ are generic, are these connected to things or not?
No, but I hadn't patched Epics-ioc over so the axes won't be loaded dynamically. The bench is only 1 Axis. 

> * It looks like everything is currently at 0 with both limits engaged, is this expected?
Possibly, Simon likely disabled the Axis and left it at 0.

> * The IOC restarted at 3am this morning and now the ADS routes aren't connecting, any idea why?
No, I'm not sure why that would happen... will investigate
