### ISSUE TITLE
GUI: Add IBEX logo to "About Box"

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#6229]
There is no IBEX logo in the "About" box of the client.  This is not consistent with the splash and "instrument updating" screens.

#### Acceptance Criteria
* A suitably-sized and formatted logo appears in the "About" box in the IBEX client

#### Notes
* Suggest adding logo to the banner area at top of window
* Icons in `...\base\uk.ac.stfc.isis.ibex.e4.product\icons`
* Splash screen in `...\base\uk.ac.stfc.isis.ibex.e4.product`

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1345

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md
