### ISSUE TITLE
Consolidate Julabo IOCs into a single IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#623]
As a support person, I wish to have a single IOC I can use to control all models of Julabo water bath, so that I don't have multiple IOCs to deal with (i.e. multiple IOCs, each slightly different, corresponding to each model of Julabo).

== Acceptance Criteria ==
1. All models of Julabo controlled from a single IOC.
1. Julabo OPI updated to refelect the single IOC

== Notes ==
1. This ticket is the follow-up to ticket #605 (see Note 2).

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 624.  Created by skn09965 on 2015-01-15T14:40:53, last modified: 2015-04-30T15:17:24_

**Comment by kjwoodsISIS** [comment]
_Trac comment by skn09965 on 2015-03-06 14:27:30:_

Current IOC works for Rob's model of Julabo, so no immediate rush.
Need to make sure we do this at some point.

**Comment by KathrynBaker** [comment]
This will also be of use to ZOOM, which needs the models FP50-HE, FPW55-SL (as used on SANS2D) and FP51-SL (as used on SURF) available.

Giving it a milestone in keeping with the expectd need on ZOOM

**Comment by AdrianPotter** [comment]
Related to #1658

**Comment by John-Holt-Tessella** [comment]
See document with various commands in (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Julabo)
