### ISSUE TITLE
Muons: ability to edit tpar file within IBEX

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#6232]
As a muon scientist, I would like the ability to edit TPAR files within IBEX.

### Acceptance criteria

- An editor for TPAR files exists within ibex

### Notes

- According to scientist, this functionality existed in SECI
- It is "particularly convenient for the users when they find their sample has affected the heating times for the fridges"
- Present solution is for the scientists to edit tpar files in notepad++
- can possibly reuse bits and pieces of script gen?

Discussed ~1:04 20/06/24

**Comment by kjwoodsISIS** [comment]
> According to scientist, this functionality existed in SECI
Really?  Could either of @davidkeymer or @KathrynBaker  demo it to us?

Is there any urgency to this request for a TPAR editor?

**Comment by Tom-Willemsen** [comment]
> Is there any urgency to this request for a TPAR editor?

I have enquired about the relative urgency and it is "below script generator improvements" for MuSR.

**Comment by John-Holt-Tessella** [comment]
Think we should ask some questions about why:

- Did they want these values to be tempoary, if so how long is temporary until config change, until next warm up etc
- Can they already set temporary values in the IOC; is this better? 
- Do they only edit it for the coldest temperature or is it for all temps?

**Comment by KathrynBaker** [comment]
After a brief discussion in teams with @Tom-Willemsen and a look through the LabVIEW code, I am not sure where this functionality exists. 

As I recall TPAR files were something used within genie, not LabVIEW, as such we would need to get an instrument scientist to demo it to see how it was used, as it may have been functionality in SECI as opposed to an area I can comment on easily.

However, in the conversation with Tom, these were associated files under SECI, which means that changing config would change the TPAR file, which might be what they are referring to. As such we may be looking for a solution more in keeping with the rotation mode functions.

#5081 might provide some insight as well.

**Comment by JamesKingWork** [comment]
After a discussion with the muon scientists (@KathrynBaker and @rerpha were present so please correct me if I have anything wrong), the following came out:

- In SECI they were only editing a temporary tpar file and would go back to a "safe" tpar file after
- They only need to use a simple text editor "not a fancy table"
- They don't want files to be directly editable and writable to disk

## My proposed solution:

I will take this to the muon scientists to get feedback and check it meets their requirements but thought I should post it first here so interested devs can also give feedback.

- The tpar file contents become a pv which we can read from and write to
- The tpar editor can change the tpar file currently being edited, this file is displayed to the user (should be a PV)
- The tpar editor reads that tpar contents PV and allows the user to make changes, changes are only written to the tpar contents PV when a button is pressed
- When in manager mode the tpar contents PV can be written to file and be made permanent

![tpareditor](https://user-images.githubusercontent.com/54139864/126977913-9faa347a-33a8-4b02-aa1c-e16b8e138672.png)

**Comment by rerpha** [comment]
Looks good. Can this be in the form of an OPI to make things nice and easy to implement?

**Comment by JamesKingWork** [comment]
After showing the muon instrument scientists the design we have decided that we should develop a generic text editor which we can use to make the tpar editor. It will have the following functions:

- The user will be able to open a file (the location where the file can be opened from should be configurable)
- The file that was last opened should be displayed
- The user can set the contents of the editor to a PV (what PV that is should be configurable)
- The contents can be saved as to a file (this can be configured to be protected by manager mode) 
- The title of the editor should be configurable (e.g. to Tpar editor)

New design:

![image](https://user-images.githubusercontent.com/54139864/129591538-8ab1b101-4ef2-4442-9f56-ed749a58e2e6.png)

**Comment by LilithCole** [comment]
re-requested by MuSR, scientist couldn't find how to change a file like they could before migration so couldn't continue with experiment.

**Comment by FreddieAkeroyd** [comment]
I think this is the editor on HIFI

![image](https://github.com/user-attachments/assets/7b45a82a-a979-48a7-8938-e690d660c583)

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-FileServer/pull/2
https://github.com/ISISComputingGroup/ibex_gui/pull/1740
https://github.com/ISISComputingGroup/EPICS-ioc/pull/877

**Comment by Chsudeepta** [comment]
This ticket can be closed. All elements have been reviewed and tested with known limitations.
