### ISSUE TITLE
SANS2D: Preliminary Test of Stober Drives

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6237]
In February/March 2021, the motion control & electronics teams are testing a single Stober drive on SANS2D.  The Stober drive is a potential replacement for the existing Baldor drives.  It would be valuable to perform some preliminary testing of IBEX with the Stober drive while it is attached to SANS2D, to establish that IBEX is capable of driving such a device (via a Galil).  if the test is successful, then the Baldor drives will be replaced by Stober drives during the 2021-22 Long Shutdown.

As a developer, I want to perform a preliminary test of IBEX with a Stober drive, so that I can establish that IBEX is can drive a Stober device via the existing Galil controller.
As a motion control/electronics technician, I want know if IBEX is capable of driving a Stober device via the existing Galil controller.
As a SANS2D scientist, I want to know if IBEX can, in principle, drive a Stober device.

#### Acceptance Criteria
1. IBEX can communicate with a Stober drive (via the existing SANS2D front-end Galils)
1. IBEX can drive the SANS2D apertures and guides to specified positions

#### Notes
1. The basic hardware architecture will not change:
   1. IBEX will communicate directly with the existing Galil controller on the SANS2D front-end.
   1. The Galil will control the Stober drive (just like it already controls the Baldors)
   1. There is no requirement (for this preliminary testing) for IBEX to read diagnostic information from the Stober drive (reading diagnostic information comes later) - see #6183).
 1. More thorough testing will be performed when all the Baldors have been replaced (see #6193).

**Comment by DominicOram** [comment]
This test will be solely checking that the hardware can move the guides, they will not be wiring the Stobers up to the Galil at all. As such there is really no testing that can be done with IBEX, the instrument scientists are happy with this.
