### ISSUE TITLE
MuSR: 3He Refrigerator Document VI Cryogenic Control Logic

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6239]
As a MuSR scientist, I would like the cryogenic control logic for the 3He Refrigerator to be correct and approved with cryogenics.

Acceptance criteria:

- [x] VI Cryogenic Control logic is documented (on the dev manual)
- [x] The logic is approved by the cryogenics team (or is edited to match what they expect)
- [x] An estimate of time to implement the logic is given

Notes:

- The 3He refrigerator is a Heliox/ITC503 based system
- LabVIEW VIs are at `C:\LabVIEW Modules\Oxford Software\Muon Heliox`

3He Refrigerator tickets:

- Document VI control logic: https://github.com/ISISComputingGroup/IBEX/issues/6239
- Implement control logic: https://github.com/ISISComputingGroup/IBEX/issues/6240
- Communications: https://github.com/ISISComputingGroup/IBEX/issues/6241
- OPI: https://github.com/ISISComputingGroup/IBEX/issues/6244
- Machine setup: https://github.com/ISISComputingGroup/IBEX/issues/6242
- Testing on Device: https://github.com/ISISComputingGroup/IBEX/issues/6243

**Comment by JamesKingWork** [comment]
Confirmed with cryogenics and MuSR scientists that this is purely ITC503 and doesn't use ITC502s and ITC601s as the LabVIEW suggests

**Comment by JamesKingWork** [comment]
Impeded waiting meeting for discussion with cryogenics on Friday

[MuSR 3He Cryo Logic.docx](https://github.com/ISISComputingGroup/IBEX/files/6070369/MuSR.3He.Cryo.Logic.docx)

**Comment by JamesKingWork** [comment]
After talking to cryogenics on Friday there were a number of notable differences between my expectations from the VI and the realities of the device. I have updated the document and sent it to cryogenics to get feedback.

[MuSR 3He Cryo Logic Attempt 2.docx](https://github.com/ISISComputingGroup/IBEX/files/6114660/MuSR.3He.Cryo.Logic.Attempt.2.docx)

**Comment by JamesKingWork** [comment]
See [docs](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ITC503-Heliox). After a talk today with cryogenics they have approved the logic.

**Comment by KathrynBaker** [comment]
The docs make enough sense to me, and the progression of documents is visible in this ticket.
