### ISSUE TITLE
MuSR: Discuss 3He Refrigerator Machine Setup

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6242]
As a MuSR scientist, I would like the IOC for the 3He refrigerator to run on a different machine to avoid any complications with IOC restarts.

Acceptance criteria:

- [ ] Discuss whether we need to do this and if so proceed with the other criteria
- [ ] There is a machine that lives with the 3He Refrigerator that runs the 3He Refrigerator IOC
- [ ] NDXMuSR is able to talk to this IOC
- [ ] The IOC is deployed onto the machine

Notes:

- The 3He refrigerator is a Heliox/ITC503 based system
- LabVIEW VIs are at C:\LabVIEW Modules\Oxford Software\Muon Heliox

3He Refrigerator tickets:

- Document VI control logic: https://github.com/ISISComputingGroup/IBEX/issues/6239
- Implement control logic: https://github.com/ISISComputingGroup/IBEX/issues/6240
- Communications: https://github.com/ISISComputingGroup/IBEX/issues/6241
- OPI: https://github.com/ISISComputingGroup/IBEX/issues/6244
- Machine setup: https://github.com/ISISComputingGroup/IBEX/issues/6242
- Testing on Device: https://github.com/ISISComputingGroup/IBEX/issues/6243

**Comment by FreddieAkeroyd** [comment]
The labview VI would have restarted with SECI? We may just need to make sure the ioc doesn't restart on a new block added etc.

**Comment by JamesKingWork** [comment]
Cryogenics are happy enough that we cannot cause damage if we do not write any sets on IOC startup. Therefore this ticket is not needed.
