### ISSUE TITLE
MuSR 3He Refrigerator OPI

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6244]
As a MuSR scientist, I would like to be able to control the 3He Refrigerator through an OPI.

Acceptance criteria:

- [ ] OPI with relevant control fields etc. is created. See VIs (The front panel has a nice diagram of the heliox we could reproduce).

Notes:

- The 3He refrigerator is a Heliox/ITC503 based system
- LabVIEW VIs are at C:\LabVIEW Modules\Oxford Software\Muon Heliox

3He Refrigerator tickets:

- Document VI control logic: https://github.com/ISISComputingGroup/IBEX/issues/6239
- Implement control logic: https://github.com/ISISComputingGroup/IBEX/issues/6240
- Communications: https://github.com/ISISComputingGroup/IBEX/issues/6241
- OPI: https://github.com/ISISComputingGroup/IBEX/issues/6244
- Machine setup: https://github.com/ISISComputingGroup/IBEX/issues/6242
- Testing on Device: https://github.com/ISISComputingGroup/IBEX/issues/6243

**Comment by JamesKingWork** [comment]
Cryogenics think it is best to remove any boxes displaying needle valve gas flows as the insert works purely on thermometers and heaters

**Comment by rerpha** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1266

Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6299
