### ISSUE TITLE
Make an initial OFFSPEC reflectometry configuration

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6245]
As an OFFSPEC user I would like to be able to use IBEX, to do this I will need a configuration for the reflectometry server.

## Acceptance Criteria
* There is an initial reflectometry configuration for OFFSPEC

**Comment by DominicOram** [comment]
# What I've done:
* Created initial config branch for OFFSPEC, includes bat file for setting basic motor values from SECI but haven't corrected these or looked at homing routines
* Took position values along the beamline from forward_geometry_calculation.vi: 
![image](https://user-images.githubusercontent.com/10086797/108082594-2c7a7800-706a-11eb-8360-e31721d2e418.png)
* Took bench length and beam angle from internals forward_geometry_calculation.vi: 
![image](https://user-images.githubusercontent.com/10086797/108082688-45832900-706a-11eb-88b3-70b16ac0c83a.png)
* Removed polariser 1 (referred to as "upper polariser" by scientist) as not needed an more, mapping between polariser 1 and upper can be seen in the High Level VI, where "Beam Deflector" is polarising mode: 
![image](https://user-images.githubusercontent.com/10086797/108079043-45812a00-7066-11eb-9eb3-37aada3e8241.png)
* Linked motors based on names in ToM
* Found out of beam positions from `Offspec High Level.vi`: 
![image](https://user-images.githubusercontent.com/10086797/108249607-2e693780-714d-11eb-96b5-bc2be50d0653.png)


# Questions:
See the TODO comments in the config, additionally:
* I found different parked/mode init positions for the FOM than the IS suggests. I used IS values in config but found:
![image](https://user-images.githubusercontent.com/10086797/108250263-f1ea0b80-714d-11eb-84cc-278772e228fe.png)
![image](https://user-images.githubusercontent.com/10086797/108250301-fd3d3700-714d-11eb-8305-3d2c913bd4b2.png)
![image](https://user-images.githubusercontent.com/10086797/108250322-06c69f00-714e-11eb-830b-4a488e3941e7.png)
* POLREF has a number of corrections in various places, I haven't applied any of these, not sure if we need to?
* I'm not sure how the disabled mode works
* I'm not 100% sure the way I've done GMW is correct
* The VI has a checkbox for vertical samples, is this required?
* There's quite a few of the Z positions I can't find, so I made up sensible values for now

**Comment by RaiBishal** [comment]
> * I'm not 100% sure the way I've done GMW is correct

What is GMW?

**Comment by ThomasLohnert** [comment]
Outdated issue, OFFSPEC has a refl config. Closing
