### ISSUE TITLE
CAEN V895: OPI Font is very small

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6250]
As a presbyopically challenged developer or scientist, I would like the font on the CAEN V895 OPI to be larger, so that I can read it.  Why is it so small?  It is verging on being illegible.

#### Acceptance Criteria
1. The CAEN V895 OPI uses the same size fonts as other OPIs

#### Notes
1. Some of the text on the OPI is normal size.  Some of it is small.   The screenshot below shows where the font is too small.<br>
![CAEN_V895_Fonts](https://user-images.githubusercontent.com/7249337/108342707-015f6800-71d3-11eb-811c-5e839ae63571.png)

**Comment by JamesKingWork** [comment]
![image](https://user-images.githubusercontent.com/54139864/109168860-24f85480-7777-11eb-813a-7923d2e7c57a.png)

Looks fixed to me
