### ISSUE TITLE
Galils: Log every time a define is set

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6254]
Following on from the discussion in #6170 

We should investigate whether we are logging every time a new position is defined in the galil. We think this is already being done but need to double check. If so this suggests that in #6170 the Galil itself wasn't working correctly and didn't log. 

### Acceptance criteria
- ~Logging is investigated, there may be a PR sat somewhere if not and if so this should be reviewed and merged.~
Done, see Freddie's comment
- Motors log every event for redefining position

**Comment by FreddieAkeroyd** [comment]
It is certainly printed on a home e.g.
https://github.com/ISISComputingGroup/EPICS-galil/blob/23db3b0cee395d3265730bdf676ec727e0106ef8/GalilSup/src/GalilAxis.cpp#L1458 but not on an arbitrary position redefine from e.g. request at motor record level. Some additional prints were added as part of debugging at one time on ISISComputingGroup/EPICS-galil#36 and some bits of these could be incorporated in the current driver (this PR itself should not be merged without changes as it disables position setting entirely). The PR does also disable position sets during an autosave restore using inithooks, that bit may be worth keeping as a safety check?

**Comment by ThomasLohnert** [comment]
We should do this before using the new galil driver

**Comment by FreddieAkeroyd** [comment]
Done a part of new galil driver work, adding to this sprint.

**Comment by FreddieAkeroyd** [comment]
To test: when office galil is back, reset position in motor record screen and confirm message printed in log file

**Comment by FreddieAkeroyd** [comment]
Repointed to cover work in expanding motor simulation to add test
