### ISSUE TITLE
ARGUS & CHRONUS: Component for Janis Cryostat

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6257]
As a muon scientist working on ARGUS & CHRONUS, I want a component that brings together all the devices I need to control a Janis cryostat.

Control of the Janis Cryostat is achieved using:
   1. a Lakeshore 332 temperature controller (see #6137)
   1. a Cryomagnetics LM500 helium level meter (see #6136) **_and_**
   1. an ITC-503 temperature controller
      * the ITC-503 is required because the Lakeshore 332 is unable to control the needle valve

#### Acceptance Criteria
1. When IBEX is deployed on ARGUS & CHRONUS there is a Janis Cryostat component that I can use to build my configurations.

#### Notes
1. Check the [ARGUS Instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/ARGUS-Instrument-Details).
1. See also [ARGUS_CHRONUS_Questions.docx](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muons/ARGUS_CHRONUS_Questions.docx) for more information.

**Comment by JamesKingWork** [comment]
Requires https://github.com/ISISComputingGroup/IBEX/issues/5832

**Comment by FreddieAkeroyd** [comment]
task during deployment/testing

**Comment by LilithCole** [comment]
Janis Cryostat likely not in use for the foreseeable future.
