### ISSUE TITLE
ARGUS & CHRONUS: IOC and OPI for Danfysik 9700

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6258]
As a muon scientist working on ARGUS & CHRONUS, my existing Danfysik PSUs will be replaced by new Danfysik 9700 PSUs as part of the RIKEN refurbishment programme.  I need an IOC and OPI for the Danfysik 9700 PSU, so that I can continue to control my power supplies.

**N.B.** Danfysik 9700 PSUs are also used on the RIKEN beamline (see #5871).  ARGUS & CHRONUS need their own Danfysik 9700 PSUs.

#### Acceptance Criteria
1. Using the IBEX client, I can control Danfysik 9700 PSUs
1. Using genie_python, I can control Danfysik 9700 PSUs

#### Notes
1. Danfysik 9700 PSUs are also being installed on the refurbished RIKEN beamline, so an IOC & OPI will, in fact, already exist (see #5871).

**Comment by DominicOram** [comment]
Closing as covered by https://github.com/ISISComputingGroup/IBEX/issues/6867
