### ISSUE TITLE
ARGUS & CHRONUS: T0 timing information for Single & Double Pulses

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6259]
As a muon scientist working on ARGUS & CHRONUS, I would like to have information about T0 timing for Single & Double Pulse events.  Ideally, I would like IBEX to write timing information into NeXuS files, so that I can use it in my analyses.

#### Acceptance Criteria
1. IBEX writes T0 timing information into NeXuS files

#### Notes
1. Scientists speculated that information about timing could come from:
   * Accelerator control system, or
   * Kicker timing (on RIKEN beamline) (see #5875)
1. Consult with @FreddieAkeroyd

**Comment by ThomasLohnert** [comment]
If this is present under SECI, it will be present under IBEX as they are using the same program.

**Comment by LilithCole** [comment]
This is something which they are going to run simply via a script. No nexus file changes are required.
