### ISSUE TITLE
SANS2D: Communicate with Stober drives

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6263]
As an instrument scientist and support person I would like to communicate with the new Stober drives (SD6 series) that are replacing the Baldors on SANS2D. Currently the Baldors are controlled exclusively through a galil and the control system has no direct interaction with them. When the Stobers are installed communication may change to any of the following:
* Communicate through the galil still (we will not get as much diagnostic information as we would like)
* Communicate directly with the Stobers (at a quick glance at the manual this doesn't seem easy)
* Communicate through something else, Beckhoff?

We should discuss which of these will be best with @Steve-Cox-IDD-Motion

## Acceptance Criteria
* We can move the stober drives through IBEX

**Comment by FreddieAkeroyd** [comment]
Will be installed on SANS2D in autumn

**Comment by FreddieAkeroyd** [comment]
Make sure they are using new version of ess plc code (with opc tags branch merged)

**Comment by DominicOram** [comment]
Went down and moved them in the lab successfully with @rerpha. Wrote some documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-apertures-and-guides. Some code changes were required but they're covered by https://github.com/ISISComputingGroup/IBEX/issues/6637

**Comment by rerpha** [comment]
docs look good, can confirm the stober drives were communicating as I saw it first hand!

**Comment by rerpha** [comment]
weird, the labels haven't been taken off
