### ISSUE TITLE
ICEFRIDGE: Scan readbacks faster when SPs set

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6264]
As a user of the icefridge I would like it to be more responsive. As a developer of the icefridge I would like the system tests to run in a timely manor.

A number of the readbacks in the device are at 10 second period scanning (presumably as the device doesn't like shorter scans). However, this means that when PVs are set e.g. `LS:MC:HTR:RANGE:SP` it could take ~10 seconds for a value to be seen on `LS:MC:HTR:RANGE`, this is bad from a uasability point of view.

There is already a `FLNK` between the two with the following comment:
```
	# Scan of readback is not frequent, so we process the readback after we set 
	# the setpoint to update it instantly
	field(FLNK, "$(P)LS:MC:HTR:RANGE")
```
However, `FLNK`s do not work when the record being linked to is not a passive one and so this does nothing. Instead another mechanism should be used to process the record.

## Acceptance Criteria
* When I set values in the icefridge the readback updates promptly

**Comment by rerpha** [comment]
Closing as part of #6318
