### ISSUE TITLE
(8/4/2021) Commissioning ENGINX height stage stepper system

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6274]
As someone using the height stage on ENGINX I want to be able to actually get it to move

**Acceptance Criteria**
1. The new height stage can be driven

**Notes**
1. Majority of the commissioning will be done by the motion control/ops teams
1. This is still run under SECI motion control, so opening the VI for the Table of Motors will be required, and potentially just that

**Comment by KathrynBaker** [comment]
Updating date when it was changed... Now due to occur a week later.

**Comment by DominicOram** [comment]
Commissioning went well, moves fine but want to test it under load at some point next week so leaving this open. I have removed references to the Bluac in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/EnginX-Sample-Positioner as it's no longer used.

**Comment by DominicOram** [comment]
Ops ran out of time to test this under load before cycle. They are confident that they testing we did without load will be sufficient.

**Comment by KathrynBaker** [comment]
I've been aware of the discussions, and to my knowledge there have been no issues this week with the start of cycle, I am calling this reviewed and complete.
