### ISSUE TITLE
MuSR: Zero Field stability

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6285]
As an instrument scientist on MuSR I would like the zero field system to be comparably stable to what it was on SECI. 
IBEX currently reads one single sample from the DAQ every time it loops. 

When the ZF system is in auto-feedback mode we are seeing fluctuations of ~2mG 
In SECI we are seeing fluctuations of <1mG

The way SECI does this is via averaging a number of samples from the DAQ (100 samples) through a rolling average.  We need to do a similar sort of thing via IBEX. 

- We are going to need to configure the DAQ to give us multiple samples
- We will need to change the underlying record type to be a waveform
- We are going to need to compress this to perform a rolling average

I am unsure how this interacts with monster mode in the DAQmx driver. 

### Acceptance Criteria 
- On MuSR with the zero field system in auto mode the fluctuations are less than 1mG
- Above but in manual mode. 
- The time for the zero field system to reach zero from a large field should be comparable to SECI

**Comment by rerpha** [comment]
This follows on from #6199

**Comment by kjwoodsISIS** [comment]
Some questions:
  * We don't see these fluctuations on EMU.  Why does MuSR behave differently?
  * Are there differences between the setup of the Kepcos and/or ZF on EMU and MuSR?
  * Did SECI on EMU use the same averaging process?
     * If so, why did it not get implemented in the IBEX version of the ZF controller?

**Comment by Tom-Willemsen** [comment]
>     * We don't see these fluctuations on EMU (at least, I don't believe we do).  Why does MuSR behave differently?

You  are correct that we don't see these fluctuations on EMU. We don't know what causes this difference.

>     * Are there differences between the setup of the Kepcos and/or ZF on EMU and MuSR?

No significant differences as far as I'm aware.

>     * Did SECI on EMU use the same averaging process?
>       * If so, why did it not get implemented in the IBEX version of the ZF controller?

As far as I'm aware EMU did not perform any averaging and so this requirement was probably missed when we were putting together [the design/requirements wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller-design).

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/440
- https://github.com/ISISComputingGroup/EPICS-zfmagfld/pull/7

**Comment by Tom-Willemsen** [comment]
Note from scientist after testing the above changes on MuSR:

> Now the typical fields seem to stay below 0.2mG in the steady state, below 6mG on the EMU ramp except when the Danfysik spikes as it switches on (I don’t think we’re in a position to fix that for now), and takes <10 seconds to stabilize from the Kepcos being at zero. For comparison SECI is similarly stable in the steady state, stays below 8-9mG as EMU ramps, and takes 7 seconds to zero from the Kepcos being off. This seems like a good result.

**Comment by rerpha** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6323
