### ISSUE TITLE
GUI: Dependency Py4J does not have historic packages this could be a problem

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6289]
As a developer I do not want to have to update py4j module at the same moment a new py4j module is released, I want to update it at during the standard update time so that I don't introduce  bugs just before a release.

### Acceptance Criteria

- ~Look to see if we are getting py4j from the correct place (in target platform)~
- ~Look to see if historic releases are stored somewhere~
- ~Contact the author and see if they can store historic releases~
- Create a onsite copy of the currently use historic release and document how to update this

**Comment by KathrynBaker** [comment]
Suggestion is to just add it as a mirror and add it to the dependency list

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-Updates#py4j
- https://github.com/ISISComputingGroup/ibex_gui/pull/1274
- https://github.com/ISISComputingGroup/IBEX/pull/6332
