### ISSUE TITLE
MuSR: 3He Refrigerator rework communications

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6294]
As a MuSR scientist, I would like the 3He Refrigerator IOC to be able to send commands to set and get values on the 3He Refrigerator IOC. After talking to cryogenics about the 3He Refrigerator, it appears my understanding of the device from the VI was incorrect. The device is a single ITC503 connected to a magic box rather than 4 ITC503s as previously thought. 

Acceptance criteria:

- [x] HLX503 is reworked to account for the 1 ITC503
- [x] He3Pot temperatures can be set and get
- [x] Tpar files can be specified for the He3Pot and Sorb
- [x] Heater can be turned off from one PV
- [x] An emulator is created (or the itc503 emulator is extended) to account for the oddities of the device
  - One control channel could be for the 1K Pot or the He3PotLo and we cannot set the 1KPot temp but can set the He3PotLo temp
  - No needle valve control
- [x] Matches features in [MuSR 3He Cryo Logic Attempt 2.docx](https://github.com/ISISComputingGroup/IBEX/files/6170478/MuSR.3He.Cryo.Logic.Attempt.2.docx) (except recondense logic)

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/431
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/598

**Comment by rerpha** [comment]
Saw some weird errors on my machine only, decided we'd like to see it run on the build servers as no one else could reproduce so have merged and will mark as complete.
