### ISSUE TITLE
GUI: Select group when adding block from OPI

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6307]
As a user I would like to be able to select which group a block gets added to when I add it via the OPI menu (implemented in https://github.com/ISISComputingGroup/IBEX/issues/2582).

## Acceptance Criteria
* When I add a block via the OPI menu I can select which group it goes into
* There is a system test for this

**Comment by rerpha** [comment]
Thought I'd give this a go for PD. 

PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1393

**Comment by rerpha** [comment]
Remaining work involves adding a squish test
