### ISSUE TITLE
GUI: Select which config/component a new block gets added to from OPI menu

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6308]
As a user I would like to be able to easily add a block to a config/component that's not my current one. The work for adding it to the current one was done in https://github.com/ISISComputingGroup/IBEX/issues/2582

## Acceptance Criteria
* A user can choose which config/component a new block gets added to from the OPI menu
* There are tests for this

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1348

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/IBEX/commits/master/release_notes/Release-Notes-v8.0.0.md?author=daryakoskeroglu
