### ISSUE TITLE
GUI: Do not allow adding blocks from OPI if GUI does not have permission

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6309]
As a user I would not like to accidentally try and add a block that I do not have permission to add and get a error box.

## Acceptance Criteria
* The add block option in the OPI menu is greyed out if it is not allowed

**Comment by boeuf-codes** [comment]
- https://github.com/ISISComputingGroup/IBEX/pull/7243  
- https://github.com/ISISComputingGroup/ibex_gui/pull/1446

**Comment by rerpha** [comment]
Cool, thanks. I guess just something to note is that things like DETMON will have to add blocks from other instruments manually, but I think that's an edge case and they probs use the edit config window anyway.
