### ISSUE TITLE
6202-1: AFG3021B Make ready for testing

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6314]
Before attempting to test in #6202 we need to create a device emmulator, test framework and upgrade the IOC to work with the testing framework.

### Acceptance Criteria

- Single dev sim test runs with the AFG3XXX IOC

**Comment by John-Holt-Tessella** [comment]
PR:

- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/12
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/600
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/437
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/109

**Comment by John-Holt-Tessella** [comment]
Added to sprint as sub ticket of 6202

**Comment by rerpha** [comment]
Have updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Python-versions---2-vs-3 to reflect device generator being updated to py3
