### ISSUE TITLE
ICE Fridge: Archive code and take screenshots

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6318]
As a developer I would not like to have to maintain support for code that will not be used. The ICE fridge has been irreparably damaged and cryogenics have said `If we were to initiate a project to repair it (which seems unlikely to be honest) then the timescales would be quite long and we could involve you from the outset.` therefore it makes sense to remove the code. However, the original developer, AD, has requested some screenshots of it before we do this.

## Acceptance Criteria
- [x] The following screenshots are created and sent to AD, @KathrynBaker will be able to provide contact details
   * A screenshot of with valves 1 to 10 opened, and all the other valves closed.
   * A screenshot of the solenoid valves opened, and all the other valves closed.
   * A screenshot of the proportional valves and needle valves opened, and all the others closed.
   * A screenshot of with valves 1 to 10 and the solenoid valves opened, and all the other valves closed.
   * A screenshot of with valves 1 to 10 and the needle and proportional valves opened, and all the other valves closed.
   * A screenshot of with the needle, proportional valves and solenoid opened, and all the other valves closed.
   * A screenshot with all valves opened.
   * A screenshot where the 1k Pump is on, and the valves and other pumps are off.
   * A screenshot where the Sealed Rotary Pump is on, and the valves and other pumps are off.
   * A screenshot where the Sealed Rotary and 1K pumps are on, and all the valves and rotary pump are off.
- [x] The ICE fridge code is no longer built/deployed as part of IBEX
- [x] The ICE fridge repository is archived
- [x] The ICE fridge OPI is no longer present in the GUI
- [x] The ICE fridge IOC is no longer able to be added to new configs
- [x] The ICE fridge system tests are no longer run
- [x] Any tickets concerning additions to the ICE fridge are closed
- [x] No configs on any beamlines contain the ICE fridge

**Comment by DominicOram** [comment]
Added as it would be nice to provide screenshots to AD promptly and we might as well do the rest whilst we're looking at the code

**Comment by rerpha** [comment]
PRs (in progress):

IOC tests: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/439

**Comment by rerpha** [comment]
Just need to remove on EMU. 

Not sure how to fulfil ` The ICE fridge IOC is no longer able to be added to new configs` as we can't run `make iocstartups` on the instrument servers. Any suggestions?

**Comment by DominicOram** [comment]
Sorry, I should have been more specific, it doesn't need to be removed from the list right now, only for the next release. The release will run make IOC startups for you so as long as it clears it out when you run it locally it should all be fine when next deployed.

**Comment by Tom-Willemsen** [comment]
I think we're missing a PR to remove the emulator (unless we decided to keep the emulator for some reason?)

**Comment by rerpha** [comment]
Sorry, forgot to remove the emulator. Think Kathryn has sent the screenshots off.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/110

**Comment by KathrynBaker** [comment]
Screenshots were sent
