### ISSUE TITLE
ZOOM: Galils comms issues

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6319]
As an instrument scientist on ZOOM (JD) I would like to be able to move all my motors.

* JN saw comms errors on the front of galils 2, 3 and 4 and power cycled them
* JD called asking us to reinstate positions/rehome
* It was noticed that, along with positions lost on other galils, the absolute encoders on MTR0101 and MTR0102 were incorrect. This was fixed temporarily but long term requires https://github.com/ISISComputingGroup/IBEX/issues/6312
* Most axes were homed correctly
* MTR0305 and MTR0306 (jaw 4 north and south) are stuck on there lower limit. They will not move through the IOC or by sending commands directly to the Galil. JN will try moving them through a jog box
* MTR0101 (the PGC) will also not move. JN will also try to move them through the jog box

## Acceptance Criteria
* The instrument scientist can move all the axes

**Comment by DominicOram** [comment]
* MTR0305 and MTR0306 had their limit switches physically wired incorrectly
* PGC had lost it's settings for the encoder. I set these manually and I have improved the long term situation a little (See https://github.com/ISISComputingGroup/IBEX/issues/6312#issuecomment-805748925)
* I have added https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting#zoom-pgc

**Comment by KathrynBaker** [comment]
It may seem wrong to mark this complete as I'm listed on the assignees, but in the interest of not needing to carry it over as I wasn't involved in finding the actual solutions I shall review it. The trouble shooting is concise and appropriate, the scientists were happy.
