### ISSUE TITLE
IOC System Tests: Script to check which IOCs are not tested

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6333]
As a developer I would like all the IOCs to be tested, even if they are just smoke tests to confirm that the IOC boots. Currently many are tested but some are not, we should work out which ones are not tested.

## Acceptance Criteria
* There is a script that tells us what IOCs are currently not being run in the IOC test framework

**Comment by aaron-long** [comment]
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/446

**Comment by rerpha** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6444
