### ISSUE TITLE
All System tests: Script to determine common failures

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6334]
As a developer I would like to improve the reliability of all system tests. Currently there are many transient failures, which are hard to pin down. The first step in fixing these is to determine which tests fail more often than others so it would be good to have a count of "in the last 100 builds, this test failed X% of the time".

## Acceptance Criteria
* We have an above metric, run in a jenkins job, for:
  - [ ] IOC System Tests
  - [ ] Squish tests
  - [ ] General System tests
* This job is added to standup links

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_utils/pull/151 was the change, i merged it to test

System_Tests_Common_Failures is the job name, see jenkins
