### ISSUE TITLE
Muons: Move all danfysiks to RS232

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6336]
As someone doing computing support, and power supply support, I would like all the danfysiks on muons to use the same communication method. Currently some of them use RS422 and some use RS232, this was due to switching between them requiring the devices to be opened up and jumpers to be moved, which was not feasible at the time of install.

## Acceptance Criteria
* All danfysiks on muons communicate using RS232
* They all still communicate with IBEX

**Comment by DominicOram** [comment]
To do this get in touch with TP of the power supply group.

**Comment by rerpha** [comment]
whoops, didnt realise there was a ticket for this, i did it a while ago.
