### ISSUE TITLE
IBEX Training

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6348]
As an instrument scientist I would like to understand how to use IBEX and so be trained in it (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX). People who specifically are known to need training are:
* MuSR instrument scientists
* Greg Smith (new IS on Larmor)
* INTER, SURF, POLREF
* DCLAB
* new SANDALS scientists
* Tom Wood & Matt Cummings of Energy Materials Group (under LSS) (ref R79 lab migration to IBEX)

## Acceptance Criteria
* Training is delivered
* New training ticket created listing anyone that was unable to attend this training who showed interest

## Notes
* The training should have been organised in #5992 
* Pointed to 8 as that was agreed and noted in the comments for #5992

**Comment by DominicOram** [comment]
First we need to install the latest IBEX version on some test machines (check experiment controls email for actual names):

### FIT_VM01
 - [ ] Started
 - [ ] Done
### FIT_VM02
 - [ ] Started
 - [ ] Done
### FIT_VM03
 - [ ] Started
 - [ ] Done
### FIT_VM04
 - [ ] Started
 - [ ] Done
### FIT_VM05
 - [ ] Started
 - [ ] Done
### FIT_VM06
 - [ ] Started
 - [ ] Done
### FIT_VM07
 - [ ] Started
 - [ ] Done
### FIT_VM08
 - [ ] Started
 - [ ] Done
### FIT_VM09
 - [ ] Started
 - [ ] Done
### FIT_VM10
 - [ ] Started
 - [ ] Done

### TEST_VM01
 - [ ] Started
 - [ ] Done
### TEST_VM02
 - [ ] Started
 - [ ] Done
### TEST_VM03
 - [ ] Started
 - [ ] Done
### TEST_VM04
 - [ ] Started
 - [ ] Done
### TEST_VM05
 - [ ] Started
 - [ ] Done
### TEST_VM06
 - [ ] Started
 - [ ] Done
### TEST_VM07
 - [ ] Started
 - [ ] Done
### TEST_VM08
 - [ ] Started
 - [ ] Done
### TEST_VM09
 - [ ] Started
 - [ ] Done

**Comment by DominicOram** [comment]
Then need to do the following:
- [ ] Email those attending the course:
   * Confirming that it is a beginners course and won't be going into detail about the latest release
   * Assigning machines to individuals and asking them to test RDP to them
- [ ] Review course material and confirm it is all still sensible
- [ ] Give the courses (should be at least 2 of us in each course)

**Comment by DominicOram** [comment]
Course was given, I updated some of the slides at https://github.com/ISISComputingGroup/ibex_user_manual/wiki/genie_python-and-IBEX-%28Introduction%29

**Comment by KathrynBaker** [comment]
Training was done
Genie python slides updated appropriately
