### ISSUE TITLE
Scans: Stop matplotlib plots from script 

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6351]
As an INTER scientist I do not want matplotlib plot OPIs to appear in random perspectives when running scans from a script.

Each newly started scan will currently send an event to the IBEX gui which just opens the plot OPI in whatever perspective is open at that moment. We should think about sensible ways to restrict this. Some ideas:
- Only open the plot if in one of a list of "valid" perspectives (scripting, reflectometry)
- Record the source of the event and pass it through genie_python back into the GUI to open the plot there (Not sure how feasible this is in practice)
- Optional `scan` argument which means "do not automatically open plot"
- ???

#### Acceptance Criteria
- Brief discussion is had for for how to do this
- Squish test exists for this functionality
When a scan is started as part of a a script execution:
- The plot window does not appear arbitrarily in whatever perspective you are currently in
- Ideally, the plot window does appear in a sensible target perspective

**Comment by RaiBishal** [comment]
+1 from Zoom

**Comment by DominicOram** [comment]
After discussion with @JamesKingWork, @ThomasLohnert, @rerpha, @SamJenkins1 and myself we decided to:
* When the python calls the java to open the plot if it is not on the correct perspective it will set a flag
* On moving to the scripting perspective it will check the flag and pop up the graph if required
* Make sure that the graph still updates on the refl perspective ok
* The plot is popping up on a standalone python, stop this

**Comment by DominicOram** [comment]
Note that this may cause some weird behaviour when running multiple scripting threads but this behaviour was bad previously and makes it no worse, we can improve on this if required later down the line.

**Comment by rerpha** [comment]
Works nicely, thanks, only thing was the squish test was passing too quickly before switching tabs - have fixed it by adding another 2 seconds to the sleep in the script that's written in the console of the scripting tab.
