### ISSUE TITLE
INTER: Correction for Sample Height

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6357]
As an INTER scientist, I would like to add an engineering correction on the Sample Height (Coarse Z in SECI terms) axis. The aim is to replicate a fudge factor they have in SECI which accounts for imperfections in the mirror alignment.

The way this is done in SECI is that a different value for SM1 distance along the beam is used when calculating the sample height (via `run_angle` genie function) than for the rest of the beamline (via Labview VI).

The way this should be done is probably as a user function correction on the sample height parameter which takes SM1 Angle as a parameter. Not sure how the maths works out exactly, will require having a look at the SECI & Genie code / maybe chat to the instrument scientists.

### Acceptance Criteria
- An engineering correction is written for the sample height parameter in IBEX that is equivalent to the correction in SECI

**Comment by ThomasLohnert** [comment]
To test:
- Check out config branch `Ticket6357_inter_sample_height_correction` on your dev machine
- Set Galils to RECSIM mode
- Confirm that the correction has the right value for the given SM1 Angle
     - Correction can be seen on the `Driver Corrections` tab in the reflectometry view
     - Try setting a mirror angle of 22.5 deg (=reflection angle of 45 deg). Correction should be equal to the distance offset `z_diff_for_height_correction` defined at the top of the reflectometry config

https://github.com/ISISComputingGroup/IBEX/pull/6445

See correspondence with the instrument scientist below for information how the correction should be implemented:

Me:
> I’m going to try and summarize the fudge factor back to you to check I have understood correctly:
> - There is a difference in SM1SA distance between the runAngle and SECI/LabVIEW code. 
> - This results in a potential difference in tracking height (let’s call it X)
> - X is applied to the sample height only, counteracting slight inaccuracies in the mirror alignment
> - Similarly in IBEX, we will want to generally use the values as defined in the SECI/LabVIEW code, but add a correction on the sample height in the shape of a user function which takes SM1 angle as a parameter and outputs X, which gets applied to the motor position

Their reply:
> - Yes that summary looks correct.
> - RunAngle: this is a modified version of runAngle to use the SM1. I will dig out the scripts next week but in short (sample-SM2)=1392.35 (as for SECI), and (sample-SM1)=1953.15 (not as in SECI by 1.3).

**Comment by DominicOram** [comment]
Works as described but it's not obvious from the text above that this is how it should work. Can you link the open genie script that does the correction? That might help

**Comment by ThomasLohnert** [comment]
From what I understand there is no specific "correction" script, just that two different SM1-Sample distances are used for setting either the height of the sample (in the `run_angle` script) or the heights of SM2, S2, S3, Detector (in the SECI VI). Here is the original email from the instrument scientist:

> Just to follow up from earlier I have the details of the “fudge-factor” correction we need for the mirror tracking. I hope in the long term we will be able to get rid of this, but it is needed for the time being.
> -          The SM2 distance along the beamline is self-consistent, so the same value is used in the SECI code and the runAngle code.
> -          The SM1 distance along the beamline isn’t. There are different values in the SECI code and the runAngle code. The runAngle code is only used to set the height of the sample bench (coarse_z in SECI terms). The distance in the SECI code is then used to set the heights of SM2, slit2, slit3 and detector.
> Clearly this doesn’t practically make sense, but the alignment requires a lot of angles and distances to be optimised to get full tracking and we aren’t quite there yet. This is the workaround we currently have in SECI and it probably makes most sense to replicate it in a similar way.
> Just to reiterate, it is the distance parallel to the ground which has this extra factor. The sample height is then dependent on this and the SM_Angle, so this factor needs to be implemented into IBEX in such a way as to still take into account the SM_angle.

INTER have also sent me a table of positions reported by SECI for different combinations of angles for SM1 / SM2. Below is a comparison between those and the ones reported by IBEX as evidence the correction is replicated correctly:


SM1 Angle | SM2 Angle | SM2 Height - SECI | SM2 Height - IBEX | Diff SM2 Height | Sample Height - SECI | Sample Height - IBEX | Diff Sample Height
-- | -- | -- | -- | -- | -- | -- | --
0 | 0.45 | 0 | 0 | **0** | 21.894 | 21.895 | **-0.001**
0 | 0.75 | 0 | 0 | **0** | 36.48 | 36.48 | **0**
0 | 0.9 | 0 | 0 | **0** | 43.772 | 43.772 | **0**
0.45 | 0 | -14.161 | -14.161 | **0** | 30.713 | 30.715 | **-0.002**
0.75 | 0 | -8.273 | -8.273 | **0** | 51.174 | 51.174 | **0**
0.9 | 0 | -5.329 | -5.329 | **0** | 61.402 | 61.402 | **0**
0.325 | 0.325 | 6.404 | 6.384 | **0.02** | 37.989 | 37.985 | **0.004**
0.45 | 0.45 | 8.839 | 8.839 | **0** | 52.59 | 52.59 | **0**

**Comment by DominicOram** [comment]
Great, thanks for the clarification and the numbers. I've merged the branch now.
