### ISSUE TITLE
HIFI Cryomag: OPI for main cryomag

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6361]
As an instrument scientist I would like a device screen for controlling the main SMS cryomagnet. 

### Acceptance criteria
- An OPI is created which matches the design spec in `Software Requirements SMS - Main Cryomagnet.docx` (found on sharepoint)
- OPI has a simplified view which hides critical features from the users

**Comment by JamesKingWork** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6386
