### ISSUE TITLE
Release: Create minor release for MuSR

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6366]
Release version 7.4.0 was created so it could be deployed on LARMOR etc. to test hardware early before sprint but we still have some tickets that need to be deployed to MuSR that are incomplete at the time of writing. We will need to create a new release for this and deploy it when these are finished. 

### Acceptance criteria
- Release is created following [the usual procedure](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release), minus the manual testing (not much will have changed for other instruments in theory)  
- Release is deployed to:

#### MUSR
- [x] Started
- [x] Completed

**Comment by JamesKingWork** [comment]
Impeded on https://github.com/ISISComputingGroup/IBEX/issues/6133, https://github.com/ISISComputingGroup/IBEX/issues/6240 and https://github.com/ISISComputingGroup/IBEX/issues/6379

**Comment by JamesKingWork** [comment]
EMU have agreed that they want 7.4.0 release to them now rather than the MUSR release. I will track that deployment as part of https://github.com/ISISComputingGroup/IBEX/issues/6375

**Comment by rerpha** [comment]
I have made some changes to inst configs on #6133  - they will need to be added into this release. 
summary: 
- added "load defaults" button in banner, added steering state in banner, resized other elements in banner to fit all of the above
- custom_records.db now contains the save/load functionality for the steering magnets.

**Comment by JamesKingWork** [comment]
> 
> 
> I have made some changes to inst configs on #6133 on branch `Ticket6133` - they will need to be added into this release.
> summary:
> 
>     * added "load defaults" button in banner, added steering state in banner, resized other elements in banner to fit all of the above
> 
>     * custom_records.db now contains the save/load functionality for the steering magnets.

I have merged this to NDXMUSR now

**Comment by JamesKingWork** [comment]
The release is now ready to go onto NDXMUSR. I have done some short tests on my machine.

**Comment by DominicOram** [comment]
I have added this to the [list of releases](https://github.com/ISISComputingGroup/IBEX/commit/6e9625abb4d27056b4ebabc1b5774e907d201dbb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). Otherwise wiki looks correct, MUSR also claims to be on 7.4.1 so calling this done.
