### ISSUE TITLE
HTS magnet: Configure smart monitor on POLREF to use static IP other than default

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6367]
As a developer I would like the HTS smart monitor on POLREF to be configured to use a non-standard IP address so we can avoid having to use a different netmask setup.

There is some information [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Kepco#hts-smart-monitor) on how to do this but more information can be found in the manuals area.

### Acceptance criteria
- HTS smart monitor on POLREF is set up to use DHCP and then given a static address on the ISIS network
- netmask changes made in #5857 are reverted as we will no longer need the device on 192.168.0.x

**Comment by ThomasLohnert** [comment]
> HTS smart monitor on POLREF is set up to use DHCP and then given a static address on the ISIS network

How does one actually do this?

**Comment by rerpha** [comment]
get the smart monitors mac address i'd think, then put it in our dhcp reserve list ( though not sure how to do this myself) then set the smartmon to dhcp through its front panel

**Comment by KathrynBaker** [comment]
What Jack said, only a couple of people in the group have appropriate access to the DHCP server, but in theory we should be able to go via FIT and infrastructure to achieve the same end

**Comment by rerpha** [comment]
device is free until after christmas, so going to get MAC address today

**Comment by rerpha** [comment]
MAC address acquired

**Comment by rerpha** [comment]
Freddie and I have decided that actually having it on the site wide network may cause issues if two people are trying to talk to it at once, so instead we are going to fix it at 192.168.x.x - TBD. I will make this the default for the SMRTMON IOC

**Comment by rerpha** [comment]
- mac address added to manuals\HTS 
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/HTS-Magnet updated 
- device labelled with new fixed IP (see data for tickets\Ticket6367)
- proof of web page working with IP in data for tickets\Ticket6367
- POLREF config updated to match new IP 
- email sent out via shared inbox

**Comment by rerpha** [comment]
i deliberately didn't put the default ip [here](https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/SMRTMON/iocBoot/iocSMRTMON-IOC-01/config.xml)
