### ISSUE TITLE
genie_python: Numpy error on startup

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6368]
As a user of genie_python I don't want to be alarmed by errors when I start the python console. Currently there are errors of the form:
```
C:\Instrument\Apps\Python3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Instrument\Apps\Python3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Instrument\Apps\Python3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
```
## Acceptance Criteria
* The source of the errors is discovered and removed

**Comment by DominicOram** [comment]
Underlying issue here is that when deploy genie python we don't remove anything that's already there. In this case it meant that an old numpy DLL was left behind, causing numpy to complain. The linked PR fixes this particular issue but a more general fix is required, https://github.com/ISISComputingGroup/IBEX/issues/6369 should cover this.

**Comment by JamesKingWork** [comment]
Adding support to avoid complaints in ProjectBoardChecks about release notes
