### ISSUE TITLE
genie_python: Install more intelligently

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6369]
As an instrument scientist I would like:
1. A new genie_python release to work properly
1. To be able to install my own python packages on the instrument and them not to be overwritten between releases

Currently we copy new genie_python releases without deleting existing files that are on the instrument in an attempt to preserve any installed packages. This caused issues with numpy in the past (https://github.com/ISISComputingGroup/IBEX/issues/6368) and may cause issues with other packages in the future.

## Acceptance Criteria
* There is a mechanism for deploying new genie_python releases that better fulfils both of the above requirements

## Notes
1. What we are currently doing could also break any packages that the scientist has installed e.g. if we update python versions they may have to reinstall packages anyway
2. One option is that we do a `pip freeze` before install and compare it with a vanilla genie_python install. If it's the same completely overwrite everything. If different highlight this to the person doing the install and they can work out how to proceed.
3. We could also ask the scientists to provide us with a requirements file whenever they wish to install a new package on their instrument.

**Comment by FreddieAkeroyd** [comment]
How often is the local genie python different to the clean install?

**Comment by DominicOram** [comment]
I think it's very unlikely to be different but we don't know and we deliberately made the decision to let scientists modify it if they want.

**Comment by Tom-Willemsen** [comment]
Different post g_p split. Newer tickets with substantially similar requirements elsewhere.
