### ISSUE TITLE
Deploy Release 7.4.0

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6375]
As an instrument scientist I would like the latest version of IBEX on my instrument so that I can use the latest features.

## Acceptance criteria

- [x] An [email](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Updating-Instrument-Machines#a-new-release) is sent to all scientists asking them when is a good time to release

The following deployments are all done:

#### CRISP - for reflectometry server changes
- [x] Started
- [x] Completed

#### DETMON 
- [x] Started
- [x] Completed

#### EMMA - low risk so might as well
- [x] Started
- [x] Completed

#### EMU - for muon changes
- [x] Started
- [x] Completed

#### IMAT - For triton changes
- [x] Started
- [x] Completed

#### IRIS - Because IS asked for it
- [x] Started
- [x] Completed

#### LARMOR - For #5688 
- [x] Started
- [x] Completed

#### LET - For #5786
- [x] Started
- [x] Completed

#### LOQ - for #5719 
- [x] Started
- [x] Completed

#### NIMROD - For #5494
- [x] Started
- [x] Completed

#### OSIRIS - For #4019 
- [x] Started
- [x] Completed

#### SELAB (check with JN before doing) - low risk, might as well
- [x] Started
- [x] Completed

#### SOFTMAT - low risk, might as well
- [x] Started
- [x] Completed

#### SURF - for reflectometry changes
- [x] Started
- [x] Completed

#### ZOOM - For #5719 
- [x] Started
- [x] Completed

#### INTER - Install for reflectometry to be done by Dom/Thomas
- [x] Started
- [x] Completed

#### POLREF - Install for reflectometry to be done by Dom/Thomas
- [x] Started
- [x] Completed

**Comment by JamesKingWork** [comment]
MUSR wants the deploy after soak testing next Monday (12/04/2021)

**Comment by DominicOram** [comment]
Moved muon instruments to https://github.com/ISISComputingGroup/IBEX/issues/6366

**Comment by JamesKingWork** [comment]
We should also look at hotfixing the mercury itc fixes from EMU and MUSR (https://github.com/ISISComputingGroup/EPICS-MercuryiTC/pull/18/files) onto:  LARMOR, ZOOM, IRIS, OSIRIS, LET

**Comment by DominicOram** [comment]
We should also hotfix https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/19 to:
- [ ] LARMOR
- [ ] ZOOM
- [ ] LOQ
- [ ] IRIS
- [ ] OSIRIS
- [ ] POLREF
- [ ] SURF
- [ ] NIMROD
- [ ] IMAT

**Comment by JamesKingWork** [comment]
Any new deploys should run https://github.com/ISISComputingGroup/IBEX/issues/6394#issuecomment-816728830. We should also run this for deploys we have already done.

**Comment by DominicOram** [comment]
> Any new deploys should run [#6394 (comment)](https://github.com/ISISComputingGroup/IBEX/issues/6394#issuecomment-816728830). We should also run this for deploys we have already done.

Done on:

- [ ] IMAT
- [ ] LET

**Comment by JamesKingWork** [comment]
I believe all deployments and hotfixes are now complete

**Comment by JamesKingWork** [comment]
Adding support to avoid having to add release notes

**Comment by KathrynBaker** [comment]
Sorry folks, and I'm not going to try and double check, but the hotfixes don't all seem to be listed in the wiki, and did Nimrod complete? Also the same hotfix is decribed in different ways - which is mildly confusing,

For the benefit of any other reviewer - these are all on 7.4, the issues are only relating to the hotfixes which will take a little more checking to be sure of, but I'd be happy if they were listed on the wiki in an easy to read way (the comments above could help that verification by listing which hotfix ticket the lists relate to not just a description and the PR)

**Comment by DominicOram** [comment]
Wiki tidied up. The hotfixes covered by this ticket are listed on the wiki as:
* 6286
* 6394
* `in position fix`

Other hotfixes on the wiki page are covered by other tickets and should be ignored

**Comment by KathrynBaker** [comment]
Thank you, I can cope with those listings as being able to follow what has gone on if we need to reapply things.
