### ISSUE TITLE
Support: various MuSR problems

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6376]
As a musr scientist, I would like a number of problems sorted so I can start my soak testing.

## Problems:

- [x] Zero Field DAQ not talking
- [x] field_emu and field_hifi are disconnected
- [x] RB number database down
- [x] Mercury ITC is flickering in and out of invalid a lot
- [x] Temperature graph from background script loaded into device screen
- [x] DAE in simulation mode
- [x] Script generator isn't available on the machine
- [x] Time to deploy the latest release to MUSR
- [x] CAEN_HV
  - [ ] Can't find the button to turn on/off all detectors
  - [ ] On/Off buttons are displayed strangely
  - [ ] Some buttons have no name on them
  - [ ] Not all boards are shown (board 12 is missing, boards 0 and 4 are shown)
- [x] isisicp is taking up to about 3gb of memory and the machine begins to run low on memory

![image](https://user-images.githubusercontent.com/54139864/113705478-61539480-96d5-11eb-8051-584b3f2137cb.png)

![image](https://user-images.githubusercontent.com/54139864/113705670-9f50b880-96d5-11eb-87ca-06c87b938e56.png)

## Acceptance criteria:

- [ ] Problems are solved or plan is made to solve them

**Comment by JamesKingWork** [comment]
## DAQ

- The DAQ was no longer talking on the network
- Reset the chassis via NI-MAX and then it was talking again

**Comment by JamesKingWork** [comment]
## Script Generator

- Enabled script generator in client
- Created ticket and task to test and deploy script generator https://github.com/ISISComputingGroup/IBEX/issues/6377

**Comment by JamesKingWork** [comment]
## field_emu and field_hifi disconnected

- EMU had renamed block Field_Danfysik to field_danfysik, now corrected in MUSR component
- HIFI is simply not available at the moment, will come back up closer to cycle, but isn't a great concern (Peter will raise it closer to cycle if it is not sorted)

**Comment by JamesKingWork** [comment]
## CAEN_HV

- I have put the latest OPI onto MUSR
- The buttons now have names
- The on/off buttons are still displayed outside of OPI (capture in https://github.com/ISISComputingGroup/IBEX/issues/6378)
- More importantly, there was no requirement capture to be able to turn all crates on/off en masse (only to view whether they are all on/off)
  - I have asked IS how important this feature is and am awaiting response (captured in https://github.com/ISISComputingGroup/IBEX/issues/6379)

**Comment by FreddieAkeroyd** [comment]
CAEN_HV: I guess EMU did not need to do this then? Is it related to powering down things for rotating the instrument?

**Comment by JamesKingWork** [comment]
> CAEN_HV: I guess EMU did not need to do this then? Is it related to powering down things for rotating the instrument?

Yeah they want the button to turn off all of them together to speed up instrument rotation

**Comment by FreddieAkeroyd** [comment]
There was some discussion about this but i'm not sure I was involved, was it going to be done via a script maybe?

**Comment by JamesKingWork** [comment]
I'm not sure we did (or at least I can't find a record). I think the confusion was that in discussions we had different definitions of manual and automated: "If the scientists see that the CAEN HV PSU is switched on, they can (manually) switch it off before rotating the instrument (and they can manually switch it back on again after they have rotated the instrument). There is no requirement for this switching on/off to be automated." from https://github.com/ISISComputingGroup/IBEX/issues/5955. I think they expected a button to allow them to do it en masse "manually" whereas we expected manually to mean "not in IBEX" (this thinking is based on the acceptance criteria of the ticket.

**Comment by JamesKingWork** [comment]
## isisicp is taking up to about 3gb of memory and the machine begins to run low on memory

- As noticed by @FreddieAkeroyd it looks like the db has a very old schema
- Fixed using: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting#isisicpexe-keeps-allocating-4gb-of-memory-and-then-releasing-it

**Comment by JamesKingWork** [comment]
# DAE simulation mode

- DAE is now set to not be in simulation mode

**Comment by JamesKingWork** [comment]
## RB Number database down

- This is because the version released onto MuSR had a bug where we used the instrument name to address the MySQL service, not the machine name
- This is fixed in the latest release, so will be fine for cycle which the IS is happy about
