### ISSUE TITLE
Script Generator: Test and deploy 7.4.0 for EMU and MUSR

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6377]
As a muon scientist, I would like the latest standalone script generator release on my machine.

Acceptance criteria:

- [x] Release created at https://github.com/ISISComputingGroup/ScriptGeneratorReleases/releases
- [x] Manual testing is complete of script generator v7.4.0
- [x] Script generator is deployed to EMU and MUSR

Notes:

- MuSR will be available for deployment on 12/04/2021 so testing should be done prior to this

**Comment by JamesKingWork** [comment]
script_generator.zip on MuSR in Instrument/Apps. Needs to be unzipped and given a smoke test

**Comment by JamesKingWork** [comment]
Impeded waiting on MUSR to be available on 12/04/2021

**Comment by JamesKingWork** [comment]
Script generator now deployed to MuSR as well

**Comment by DominicOram** [comment]
Confirmed that MUSR and EMU have latest script generators
