### ISSUE TITLE
Zero Field System: Enable autosave of auto-feedback mode with macro set

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6383]
Following on from #6360 which involved a hotfix on MuSR

As a developer I would like a way of enabling autosave on the auto-feedback mode record on the zero field controller. This could involve the use of a macro that enabled the autosave field and disabled the initial `VAL` field on the record. 

#1209 is similar but `PINI` is set to yes as default anyway so we can't change this on the record. using the macro to comment out VAL and uncomment the autosave field should be sufficient as this is how the hotfix has been applied on MuSR. 

This means we do not have to keep hotfixing MuSR each time we release. EMU may also want this functionality. 

### Acceptance criteria
- Autosave can be enabled and disabled through a macro value in the ZFCNTRL IOC.
- IOC test is written to confirm autosaving works
- Hotfix is removed from MuSR when we next release

**Comment by JamesKingWork** [comment]
Having looked at the components that are switch when moving between transverse and longitudinal (MuSR_base_transverse and MuSR_base_longitudinal) both contain ZFCTRNL_01 IOCs with differing macros and PV values. Meaning that we cannot avoid restarting the ZFCTRNL IOC even if we were doing a more intelligent config change with configs the way they are at the moment. The other alternative I can see is to move the ZFCTRNL IOC to the MuSR_base component, ensure it isn't restarted on component switching and set the PV values and macros via pv values from the config.

**Comment by rerpha** [comment]
OK, I am going to pick this up. I think the best way of doing it is making the macro not visible to the GUI, so the autosave can't be switched on or off between configs (which could end up being very messy as it'd leave the last known value from the previous config which didnt have the autosave macro set to false, which on restore could be dangerous) - I am proposing they use this by putting it in the `globals.txt` file so it doesn't switch to on/off between configs.

**Comment by rerpha** [comment]
PRs:

ZFCTRL - https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/12
IOC - https://github.com/ISISComputingGroup/EPICS-ioc/pull/618
IOC tests - still to do 

added note about setting `ZFCNTRL_01__SAVEFEEDBACKMODE=YES` in dev wiki - https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Zero-field-controller#autosaving-feedback-mode

**Comment by JamesKingWork** [comment]
Minor rework: Tests do a lot more restarting and sleeping than required greatly extending the length of the tests
