### ISSUE TITLE
SANS sample changer: Do not append names on LOQ

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6392]
As an instrument scientist on LOQ I would not like the name of my rack to be appended on to my sample name. The sample changer code does this by default and is a requirement for other beamlines but not for LOQ. The instrument scientist is going to discuss this with other scientists to come up with a set of common requirements across SANS beamlines. Additionally I would like the OPI to read `Select Rack` rather than `Select Changer`.

## Acceptance Criteria
* The rack name is not appended to the position name on LOQ (other instruments are not affected)
* On the User tab, please could you change:
     * ‘Select Sample…’ to say ‘Select Position’
     * ‘Select Changer…’ to say ‘Select Rack’
     * ‘Changer:’ to say ‘Rack:’

**Comment by DominicOram** [comment]
Added as the sample changer is not usable on LOQ without this.

**Comment by DominicOram** [comment]
Also updated docs at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Sample-Changer-Support-Module#samplechangerxml

**Comment by DominicOram** [comment]
Increasing points estimate as scientists have added a couple more requirements

**Comment by rerpha** [comment]
as a note
this is to review first 
then #6409 
then #6414
