### ISSUE TITLE
DEPLOY: Large commit size from multiple pythonw.exe processes

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6394]
As a scientist/user, I want my computer's memory to be used correctly so I am not prevented from running experiments.

Acceptance criteria:

- [x] Cause of large commit size found
- [x] Fix agreed
- [ ] ~~Fix deployed~~ Tracking now as part of https://github.com/ISISComputingGroup/IBEX/issues/6375

**Comment by JamesKingWork** [comment]
Could be a similar issue to https://github.com/scipy/scipy/issues/12671. I tried bumping the numpy version from 1.19.3 to 1.20.2 and the memory commit size has drastically reduced for all pythonw.exe processes.

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/genie_python/pull/323

**Comment by ChrisM-S** [comment]
nice spot @JamesKingWork !

**Comment by JamesKingWork** [comment]
Sorted on EMMA by stopping the ibex server and running `%PYTHON3% -m pip install numpy==1.20.2`

**Comment by DominicOram** [comment]
Yes, this does fix the issue but we should have a test to ensure something similar doesn't happen again. Ideally as part of the automated system tests but manual would suffice.

**Comment by JamesKingWork** [comment]
Tests: https://github.com/ISISComputingGroup/system_tests/pull/79/files
