### ISSUE TITLE
Patch HRPD, ENGINX and ALF for :MON: PVs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6396]
The :MON: lookup PVs in ISISDAE do not always translate correctly to spectrum number, this is a problem on the  above instruments which are being monitored for moderator performance. 

A fix for this is provided in ISISComputingGroup/EPICS-isisdae#69 but the above instruments have not been deployed to. Hence I have
- created a new branch off release 7.1.0
- cherry picked the relevant isisdae commit
- rebuilt and deployed support/isisdae/bin-windows-x64 (in build `FreddieBuild #35` in Jenkins)
- old code in windows-x64-orig

note: the fix was discovered post release, so a patched release would have been required too, hence a backport

**Comment by FreddieAkeroyd** [comment]
To test

Check `caget IN:ALF:DAE:MON:1:1:S` returns correct spectrum number `2369` and not `1`

**Comment by FreddieAkeroyd** [comment]
ENGINX and HRPD DAEs are not powered on yet

**Comment by rerpha** [comment]
ALF looks correct, I will follow up on HRPD and ENGINX when they are switched on as I still can't reach them.
