### ISSUE TITLE
Support: Thurlby TTIEX335 setpoints out of range

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6397]
As a MuSR scientist/user, I would like to be able to set my transverse field and other settings on the Thurlby correctly. The IOC reported the status `Cmd outside limits` on the ERROR PV when attempting to sweep to zero and turn off and when setting some currents and voltages.

Acceptance criteria:

- [x] Reason for error understood
- [x] I can set reasonable currents and voltages
- [x] I can sweep to zero and turn off
- [x] I can reach reasonable fields

**Comment by JamesKingWork** [comment]
From looking at the database the IOC retrieves the error directly from the device, need to look at logs and probably arrange some time to try out the device on the instrument

**Comment by JamesKingWork** [comment]
Possible ideas:

- Is the conversion with AMPSTOGAUSS incorrect?
- We should look at labview
  - Can we actually set to 0?
- What does sweep to zero and turn off do?
- Who else uses this device?
  - Is this a different device to others?
  - Do they use the 355 as well as the 355P 
- Are we actually sending less than zero because of rounding?

**Comment by FreddieAkeroyd** [comment]
The current setpoint has
```
    field(HOPR, "5.0")
    field(LOPR, "0.01")    
```
while this will not stop a value outside these ranges (unlike DRVH,DRVL) it seems strange LOPR is 0.01 and not 0 ?

Also VOLTAGE:SP and CURRENT:SP are set to PINI but with no autosave, so I am assuming they will send 0 to the device on ioc startup?

**Comment by JamesKingWork** [comment]
It looks like the 0.01 comes from the manual

![image](https://user-images.githubusercontent.com/54139864/114698369-f1698d80-9d16-11eb-8b97-9c1fe196263f.png)

When processing occurs at initialisation because of PINI, will the record be in Invalid/UDF alarm and so not send the setpoint?

**Comment by JamesKingWork** [comment]
What I think occurred was that when attempting to set a field of 0 Gauss we then tried to send a setpoint of 0 Amps which is out of the range above defined by the device. I have tested with an emulator adding the minimum voltage and current to the range and which then gave me the errors we were seeing on MuSR. Using DRVH and DRVL instead of HOPR and LOPR has fixed this issue "clipping" the value into range.

**Comment by JamesKingWork** [comment]
The IS has agreed this is a good fix, we are now testing it on MUSR.

**Comment by FreddieAkeroyd** [comment]
re: PINI, you could check the emulator log and see if it sends 0 at PINI start

**Comment by JamesKingWork** [comment]
> re: PINI, you could check the emulator log and see if it sends 0 at PINI start

By the look of the emulator logs it does send 0 voltage and 0.01 amps at PINI start. I will ask Peter if this or autosave is preferred.

**Comment by FreddieAkeroyd** [comment]
we may need to be careful about automatic autosave if we deploy the ioc elsewhere. If he doesn't want autosave then maybe remove PINI?

**Comment by JamesKingWork** [comment]
> we may need to be careful about automatic autosave if we deploy the ioc elsewhere. If he doesn't want autosave then maybe remove PINI?

Plan is to autosave fields if a macro is set

**Comment by JamesKingWork** [comment]
The TTIEX355P IOC is also present in ZOOM configs

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-ioc/pull/612
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/449
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/114

**Comment by JamesKingWork** [comment]
Testing on MuSR is looking positive. We also noticed that the t20 field was at no point being considered stable, this was due to tolerance on stability being too tight for the gauss to amps calculation. I have now made this a macro so it is configurable.
