### ISSUE TITLE
MuSR: Script failed to run correctly because it could not get the current config name from the blockserver [Timebox: 2 days]

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6398]
As a MuSR scientist, I would like my script not to fail because it could not get the current config name from the blockserver.

The current configuration name could not be retrieved from the server at the exact moment the script requested it. The value `config_name` was then defaulted to be None. When the script then did the check `if “triton” in config_name` Python could not iterate over `config_name` to try and find triton and the exception was thrown. See the image below.

Acceptance criteria (at least one of the following is met):

- [ ] Reason for config name not being available established
- [ ] Risk of issue occurring again is mitigated

![image](https://user-images.githubusercontent.com/54139864/114584491-a0a45700-9c7a-11eb-9872-5b1eea3f0479.png)

**Comment by JamesKingWork** [comment]
Current theory:

- Blockserver was struggling to talk to git (seen in logs)
  - Does this just try and commit or also push?
  - Could it be caused by network issues
  - Could it be caused by a lock?
- This then interrupted the blockserver pcaspy processing loop
- Causing the blockserver to fail to serve the current config name
- This then caused the script failure

We should try and recreate this conditions and test if this is the cause of the error and find a fix from there if it is.

**Comment by JamesKingWork** [comment]
In git_version_control.py the _commit_and_push is done in a different thread, but it references self.remote which was created in the main thread (it runs self.remote.push()). This could be not thread-safe, currently testing this hypothesis.

**Comment by rerpha** [comment]
I have tried freezing both the commit thread AND the main thread and even freezing the main thread just gives a `UnableToConnectToPVException` - I think genie python has done something weird here as i don't think it'd be possible to actually return None otherwise - surely through channel access you couldn't serialise a Python NoneType.

**Comment by rerpha** [comment]
We tried sleeping the git committing, adding and pushing in the git library itself but this didn't hang up the main thread and we could still access the CURR_CONFIG_NAME pv throughout. 

We also tried unplugging james' internet whilst polling for the pv in a loop but we still didn't see the error so now thinking the network issues are actually a red herring.

**Comment by rerpha** [comment]
blockserver log for when this happened: 

[BLOCKSVR-20210412.log](https://github.com/ISISComputingGroup/IBEX/files/6311259/BLOCKSVR-20210412.log)

**Comment by JamesKingWork** [comment]
We have now tried a number of methods to get the blockserver to not serv CURR_CONFIG_NAME, which includes trying to halt the processing with the ComponentSwitcher, simulating network disconnects and git issues. These have all been unsuccessful. In discussion with IS and @rerpha @DominicOram we have agreed the script should retry a number of times and default to a slower slew rate. This will not result in any problems with the equipment but will cause the danfysik to be slower to reach setpoints. @rerpha will write the changes to a branch of the configs

**Comment by JamesKingWork** [comment]
Changes from NDXMUSR_use_is_local branch now merged onto NDXMUSR and pulled onto MUSR instrument

**Comment by rerpha** [comment]
To review: check that setmag() in musr_routines.py contains a more hardy check for the current config name

**Comment by DominicOram** [comment]
Code is hardier and a good stop gap, added https://github.com/ISISComputingGroup/IBEX/issues/6474 to look into whether this is the best way of doing this.
