### ISSUE TITLE
EMU: Web dashboard showing alarms

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6399]
As an EMU scientist, I would like to avoid being called out for alarms on the web dashboard that are incorrect. 

It was reported to the SAG in January that the EMU web dashboard was showing alarms that are incorrect. Currently, the alarms shown on the web dashboard are for the blocks: field_hifi (HIFI currently running tests so the PV is not there), field_musr (May need to be pointed at the correct block/pv), field_t20 (Alarm doesn't appear on PV but does on block), temp_sp (undefined setpoint see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches#12-initialising-setpoints for solution) and m_slits. These alarms match those on the IBEX client. Could this be connected to https://github.com/ISISComputingGroup/IBEX/issues/6286?

Acceptance criteria:

- [ ] Current alarms on the EMU web dashboard are either accounted for or addressed
- [ ] Plan for investigating incorrect alarms on web dashboard is devised and either done or spun out into another ticket

**Comment by DominicOram** [comment]
If these alarms match those on the client then they don't have anything to do with the web dashboard? It sounds like alarms are correct, they just need to be addressed?

**Comment by JamesKingWork** [comment]
I should've made it more clear, there are two sides to this ticket. One is addressing those alarms that match the client and another is investigating the alarms that appear on the web dashboard incorrectly.

**Comment by FreddieAkeroyd** [comment]
EMU reported specifically web dashboard alarms as being incorrect at the SAG, is it possible for the web dashboard and client to get out of sync and disagree?

**Comment by JamesKingWork** [comment]
Having kept an eye on this for a while and having told the ISs to keep an eye out we have not seen an issue where the web dashboard alarms are different to the client. So I think whatever has happened has fixed itself. The dashboard has also had all the other invalid alarm blocks fixed at this time as well.

**Comment by JamesKingWork** [comment]
IS has now reported there is an alarm "Temp_GasAuto" that now appears on the web dashboard and not on the client

**Comment by DominicOram** [comment]
It doesn't appear to be in alarm on the webdashboard now. Is there just a bit of a delay?

**Comment by JamesKingWork** [comment]
JSON_bourne is now logging the web dashboard alarms for EMU. These can be found in C:\JSON_bourne\emu_alarm.log. The code for the logging is on the branch [Ticket6399_emu_web_dashboard_alarms](https://github.com/ISISComputingGroup/JSON_bourne/tree/Ticket6399_emu_web_dashboard_alarms).

**Comment by JamesKingWork** [comment]
Adding data collection script for alarms from the archive in ibex_utils https://github.com/ISISComputingGroup/ibex_utils/tree/Ticket6399_web_dashboard_alarms_investigation

**Comment by Tom-Willemsen** [comment]
Example of inconsistent alarms between web dashboard and GUI:

![image](https://user-images.githubusercontent.com/24375813/202454387-3724bd56-8f71-4955-bcc9-2009a73d83c4.png)
