### ISSUE TITLE
MuSR: CAEN HV slots 4 and 12 lost names

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6403]
As a MuSR scientist, I would like my detectors to have the correct names. Since updating IBEX to 7.4.1 channels on slot 0 have the correct name but slots 4 and 12 have lost them.

Acceptance criteria:

- [x] CAEN HV slot channels on 4 and 12 have correct names
- [x] Fix is deployed to instruments that need it

**Comment by JamesKingWork** [comment]
Confirmed the issue occurs in SECI as well:

![image](https://user-images.githubusercontent.com/54139864/115005713-10dff200-9ea0-11eb-8dca-1388f6c0114d.png)

**Comment by FreddieAkeroyd** [comment]
So the IOC should normally only read from the hardware? If something wrote to the IOC from outside via channel access, then that will be automatically logged in the "putlog" - you can either search the database or look at the `_putlog.txt` files from a previous run on the archive

**Comment by JamesKingWork** [comment]
In normal operation it will only read from the device unless the PV is written to. Having search the database putlog I found no evidence that the PV had been written to, though I suppose this could be due to truncating the database during the upgrade to 7.4.1

**Comment by FreddieAkeroyd** [comment]
or grep the `_putlog.txt` files on the archive

**Comment by JamesKingWork** [comment]
I cannot seem to find any record in the putlog or database of writes to the name PV, so I have left the investigation at that. I have now reapplied the names that are expected as given by the IS as:

"I think that the detectors on slot 12 are det-24 to det-47. Those on slot 4 seem to be det-49 to det-64, then the spare channels that are off, and finally the warning light channel called ‘Light’ which is at 600V".

To review: 
- Check that the detector names on MUSR are as given by the IS

**Comment by JamesKingWork** [comment]
The problem has recurred on MuSR when moving from IBEX to SECI, investigating again.

**Comment by JamesKingWork** [comment]
When the VI is run it restarts the IOC. It is at this point we lose the names. I have tried restarting from the console and this also causes a loss of names on channels 4 and 12. There are a bunch of messages similar to: `Error (514,514) PV: IN:MUSR:CAEN:hv0:0:17:v0set ao: init_record` but these apply to both channels that have and haven't lost names so may be unconnected.

**Comment by JamesKingWork** [comment]
The bug has been discovered. The new CAEN library returns error codes on an empty slot, the CAEN driver then checks this error code and returns if it is not CAENHV_OK. As we were looking at slots 0, 4 and 12, the CAENx527GetAllChName method cut off getting the names at slot 1 because of the error code.

Solution:

- Remove check on return value and add max slot check in the loop

We have confirmed that it works whilst talking to the CAEN on MUSR from Freddie's machine. I am now building the IOC and will deploy it to MUSR (and ask other instruments running 7.4.0 and that use the CAEN IOC whether they care, they haven't lost the names in the crates just the OPI display will be incorrect).

**Comment by JamesKingWork** [comment]
Looking at the instruments that use CAEN IOCs and are on 7.4.0 and greater we only need to deploy to:

- [ ] MUSR
- [ ] ZOOM
- [ ] LARMOR

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6449
