### ISSUE TITLE
Accelerator PVs are not read only

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6410]
It is possible to CAPUT to e.g. `AC:TS1:BEAM:CURR` - though this will likely get overwritten by the next update, it is not ideal.

## Acceptance criteria

* Central accelerator PVS are served read-only

**Comment by FreddieAkeroyd** [comment]
To test: check you can no longer caput, and that cainfo says read-only

**Comment by DominicOram** [comment]
I checked a selection of facility PVs, all were read only. Whilst we could test this I think it's unlikely to regress and would potentially cause issues in the tests being dependent on a central server.
