### ISSUE TITLE
ICE fridge: delete any remaining device screens

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6417]
on EMU at least there is a device screen for the ICE fridge which was removed as the equipment had been decommissioned. We know that cryogenics would give us lots of notice if it were to be recommissioned but it is very unlikely. 

### Acceptance criteria
- [x] Instruments are checked to make sure they have no device screens pointing at the ICE fridge
- [x] instrument scientists are contacted to make sure they are aware that we are going to remove the device screen 
- [x] device screens pointing at the ice fridge are removed.

**Comment by JamesKingWork** [comment]
I have removed it from EMU

**Comment by JamesKingWork** [comment]
ConfigChecker https://epics-jenkins.isis.rl.ac.uk/view/WallDisplay/job/ConfigChecker/1455/console confirmed only MUSR still has it. I have now removed the ICE_dilution.xml synoptic that contained it. No device screens or synoptic on EMU or MUSR now contain the ICE OPI.
