### ISSUE TITLE
InstrumentChecker: get_ioc_usage.bat should check device screens

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6418]
As a developer I would like the configchecker or get_ioc_usage.bat in the config checker to check for device screens pointing at a certain IOC. on EMU after we removed the ICEFRDGE IOC a device screen remained which the scientists were unhappy about. This ticket would make #6417 easier because it involves checking device screens for the IOC that had been removed. 

### Acceptance criteria
- [ ] get_ioc_usage.bat looks in the device screens for instruments (as well as configs, components etc as it is already doing) and checks for the given IOC. (inside configurations/devices/screens.xml)
- [ ] It also checks synoptics (inside configurations/synoptics)

**Comment by aaron-long** [comment]
PR: https://github.com/ISISComputingGroup/InstrumentChecker/pull/33

**Comment by rerpha** [comment]
Looks good, cheers!
