### ISSUE TITLE
HTS Magnet: Allow local control of KEPCO

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6420]
As a scientist on POLREF I would like to be able to control the Kepco used by the HTS magnet locally in case of emergencies. Currently I cannot use the front panel to control it whilst IBEX is talking to it.

## Acceptance Criteria
* The front panel of the HTS kepco is useable whilst IBEX is communicating with it

**Comment by ThomasLohnert** [comment]
Talking to the device via Hyperterm and setting `SYST:REM` to 0/1 produced the desired behaviour, but you can't do the same via the IOC (e.g. writing to `KEPCO_XX:REMOTE`) so it looks like something is wrong at the IOC level that makes it not relinquish control to LOCAL mode (e.g. it implicitly sets the Kepco back to `REMOTE` mode as part of other commands)

**Comment by DominicOram** [comment]
Probably done in https://github.com/ISISComputingGroup/IBEX/issues/5105 but we just need to tone it back a bit

**Comment by ChrisM-S** [comment]
Depending on the possible "emergencies", it might be necessary to simply have an HTS mode set by PV where the risk is on the other foot - so to speak - i.e. in HTS mode, the IOC _never_ sets the remote mode remotely - as local user control (or the switch to it locally) cannot then be compromised by the IOC setting it back into remote mode unexpectedly?  It could be left to an explicit genie_python command (in case it is required to enable communication from an office/home for example).

**Comment by rerpha** [comment]
whoops sorry - looking at the wrong ticket. Will try and pick this up if I can finish the aladdin pump ticket

**Comment by rerpha** [comment]
Will be on site tomorrow so Dom and I will do some investigation then

**Comment by DominicOram** [comment]
It appears that for this model of Kepco sending any command to the device will put it in remote mode, even if that command is just a query. Even worse sending the query of what mode it is in also puts it into remote mode and sending the set point to get it into local mode puts it into remote mode.... @ThomasLohnert is going to send an email to the manufacture about this.

**Comment by rerpha** [comment]
response from manufacturer is that they are asking for a serial number so I will go down as soon as the rad testing is done on POLREF and get some pics of the back of the KEPCOs

**Comment by ThomasLohnert** [comment]
Manufacturer has been supplied with the serial number, awaiting reply

**Comment by FreddieAkeroyd** [comment]
There was a comment above "Talking to the device via Hyperterm and setting SYST:REM to 0/1 produced the desired behaviour, but you can't do the same via the IOC". Is writing SYST:REM 0 the only command sequence that doesn't put it into remote mode?

**Comment by DominicOram** [comment]
I believe that on further testing the `SYST:REM 0` command did not do as expected in hyperterm and would immediately set the device beck to remote. @rerpha and @ThomasLohnert, this is what we were seeing right?

**Comment by ThomasLohnert** [comment]
Yes that was a misunderstanding sorry, SYST:REM behaviour is the same, the difference is that hyperterm unlike the IOC does not constantly steal the control back

**Comment by rerpha** [comment]
> I believe that on further testing the `SYST:REM 0` command did not do as expected in hyperterm and would immediately set the device beck to remote. @rerpha and @ThomasLohnert, this is what we were seeing right?

Yes, an immediate SYST:REM? gave 1 after setting to “local” remotely (implying it switched as soon as we sent the command, regardless of if we set it to local)

**Comment by FreddieAkeroyd** [comment]
So SYST:REM 0 issued from hyperterm with no further command/query issued does not put it into local mode as confirmed by the front panel on the device?

**Comment by rerpha** [comment]
> So SYST:REM 0 issued from hyperterm with no further command/query issued does not put it into local mode as confirmed by the front panel on the device? If that is the case then it sounds completely broken. If it turns out that this is the only command that doesn't immediately put things back into remote mode, and there are no ideas from the manufacturer, then we may have to implement a remote/local button on the OPI which when you choose "local" it disables all records from scanning and sends "SYST:REM 0" and then does absolutey nothing until somebody presses the "go remote" button on the OPI.

Correct. If you put it into local mode via the front panel and then query the mode it then sets itself to remote mode as well.

**Comment by rerpha** [comment]
Going to stick this in impeded as we are waiting on the manufacturer's response

**Comment by DominicOram** [comment]
@ThomasLohnert any response from the manufacturer on this? Can you give them a ring?

**Comment by ThomasLohnert** [comment]
Email from Kepco:

> Thank you for reaching out to me about this, from reading the original query. I believe this behavior is to be expected. In order to have your remote driver running, I don't believe it will be possible to also manipulate the power supply locally at the same time. It must be either or, not both. You may need to send a command to the unit to exit remote mode and then remove the said controller/connectors from the power supply. This will likely help the unit enter local mode completely. I hope this insight was helpful to you today. Please let me know if you have any further questions. 

I think this isn't critical to POLREF right now but I will talk to them about their safety case again to check whether we need to come up with some clever solution in the IOC logic for the long term. The limitation we have to work around is that any query from the IOC puts the device back in remote mode (including checking whether the device is in remote or local mode...)
