### ISSUE TITLE
Training: Provide training for reflectometry server

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6421]
As a scientist on a reflectometry instrument and as a support person I would like to be trained on how to use the reflectometry server.

## Acceptance Criteria
- [x] Training is booked
- [x] Slides are written
- [x] Appropriate training VMs are set up
- [x] Training is presented

**Comment by ThomasLohnert** [comment]
Training was delivered on 07/05. Slides have been circulated among invitees.
