### ISSUE TITLE
POLREF: Control Aladdin Pump

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6422]
As an instrument scientist on POLREF I would like to be able to reliably control my Aladdin pump.

## Acceptance Criteria
* POLREF can reliably control their Aladdin pump

**Comment by ThomasLohnert** [comment]
Connected the pump via serial. IOC seems to be talking to it (ie. it is not timing out) but is failing to initialize records correctly so everything is `INVALID (UDF)`. We have tried adding in a null modem which did not help. Scientist has left the pump on the beamline for us.

**Comment by FreddieAkeroyd** [comment]
I seem to recall this pump being funny about the connection cable plugged into it to give a DB9, there were two types of cable that came with it, one only worked joining pumps, one only worked for connections to the PC.  Also maybe it has got stuck in "safe mode". I emailed some notes to INTER back in 2019 when i had a previous fight with the device and labview driver, i've pasted these into the end of https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/WPI-Aladdin-Syringe-Pump

**Comment by FreddieAkeroyd** [comment]
I can't see us sending the command to turn off safe mode and enable basic mode, so that may be the issue? The labview driver used to send that sequence on startup

**Comment by rerpha** [comment]
Email sent off to confirm what address the pump is on and which cable type has been used

**Comment by rerpha** [comment]
The pump is now working. I will add to the list of hotfixes on POLREF then put this ticket in review

**Comment by davidkeymer** [comment]
I shall also add some more information to the relevant wiki page.
