### ISSUE TITLE
Sample Changer: Maintain xml ordering for positions

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6424]
As an instrument scientist using the sample changer code I would like my position options to be the same order on the OPI as they are on the XML. Currently they are ordered alphabetically meaning C10B appears before C1B.

## Acceptance Criteria
* Positions in the OPI list are ordered as they are in the xml
* There is a test for this

**Comment by Adam-Szw** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6656
