### ISSUE TITLE
Motion set points/sample changer: Be clearer on the reason for loading issues

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6425]
As an instrument scientist using motion set points or the sample changer I would like a clear idea of why my set points are not getting correctly loaded in. Two issues that I would particularly like to be notified of are:
* There are spaces in the names of my positions
* There are two positions pointing to the same place
* There is no new line at the end of file

## Acceptance Criteria
* The above errors are displayed on relevant OPIs when they occur
* Other possible common errors are also displayed

**Comment by FreddieAkeroyd** [comment]
"There are two positions pointing to the same place" is no longer an error after https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/25

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/27
https://github.com/ISISComputingGroup/ibex_gui/pull/1447

**Comment by rerpha** [comment]
Just a thought - we have motion setpoints ioc tests - could you add some for invalid txt files? unit tests look good, but would be nice to cover setting the error message and checking filename etc.
