### ISSUE TITLE
SANS Sample Changer: Deploy latest version to LARMOR/ZOOM

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6427]
As an instrument scientist on LARMOR/ZOOM I would like the latest SANS sample changer additions that have been tested on LOQ (https://github.com/ISISComputingGroup/IBEX/issues/6227).

## Acceptance Criteria
* Latest changes are put on LARMOR and ZOOM
* Wiki is updated
* Synoptics and configs still point to appropriate blocks on the instruments

**Comment by JamesKingWork** [comment]
Confirmed has correct files for 

- https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/20/files
- https://github.com/ISISComputingGroup/IBEX/issues/6392
- https://github.com/ISISComputingGroup/IBEX/issues/6409
- https://github.com/ISISComputingGroup/IBEX/issues/6414
