### ISSUE TITLE
Support: Clean up C: Drives

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6432]
As an instrument scientist, I would like enough disk space on my computer to do experiments.

Acceptance criteria:

- [x] There are no important critical C: drives listed in Nagios and ones that were have a reasonable amount of space

Instruments listed at time of writing:

- [x] Merlin
- [x] MARI
- [x] Polaris
- [x] LET

Possibly want to think about:

- [ ] DETMON
- [ ] SELAB

**Comment by FreddieAkeroyd** [comment]
I've cleared up space on POLARIS

I've cleared up some on SELAB and MARI. On MARI the disk is tight and the DB is not too large, @ChrisM-S maybe we can run the "disk cleanup" as i think spudulike has quite a bit of temporary file space used.

LET was not the usual issue - it was a DAE fault causing large amounts of event data to be written.

**Comment by JamesKingWork** [comment]
> I've cleared up space on POLARIS
> 
> I've cleared up some on SELAB and MARI. On MARI the disk is tight and the DB is not too large, @ChrisM-S maybe we can run the "disk cleanup" as i think spudulike has quite a bit of temporary file space used.
> 
> LET was not the usual issue - it was a DAE fault causing large amounts of event data to be written.

There is one large archive/sample.ibd file in the MySQL folders (6.9gb). Would a truncation of the database not clear this up?

**Comment by FreddieAkeroyd** [comment]
Yes it would get us 7gb, it is just that we are usually truncating when it is larger so it is not getting us back as much as we usually get, and my concern was it may not be enough

**Comment by FreddieAkeroyd** [comment]
polaris still has 5gb in its database, worth clearing that if we can, but i managed to get it above 11gb by removing other things not affecting colelction

**Comment by JamesKingWork** [comment]
I have truncated the database on POLARIS

**Comment by ChrisM-S** [comment]
I’ve Pulled back a few more GB on MARI C:. including a 2GB video from vlc which I saved to the stage-deleted area just in case.

Whilst looking in treesize, I noticed that at least half of its data disk was filled up with old ibex backups in data\old and old giant icp log files so have had a go at these too.  I suspect this may have been a problem on LET and others as they all eat into the spare room left on the data area for “emergencies” like we had on LET.

**Comment by JamesKingWork** [comment]
Current size:

- LET 19.3gb
- MARI 12.4gb (quite a bit of temp used up by Spudulike and a large archive database file but they're doing a run so I didn't want to mess with it)
- POLARIS 15.4gb (disconnected Eurotherm was starting to fill it up, so I have stopped the IOC and removed the larger logs)
- MERLIN 23.9gb (the server is not even running so I have started it)

**Comment by JamesKingWork** [comment]
@ChrisM-S to add more space to MARI C Drive from the NDH, the rest we are happy that we have enough to get to maintenance day

**Comment by ChrisM-S** [comment]
10G added to MARI now 22GB free

**Comment by rerpha** [comment]
listed machines OK, detmon still has ~6GB, SELAB has @6GB, RIKENFE doesn't look worth worrying over.
