### ISSUE TITLE
LET: recover after disk filling up

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6437]
The LET data disk filled up, causing the ICP to crash. There was an experiment in place and data logging had stopped as mysql and sqlite were on the same disk. Fortunately the data browser had been lefty plotting data and, with help from @DominicOram we were able to pull the necessary data out of the graph buffer. The underlying issue looks to be noisy detectors as the count rate was high even though the shutter was closed.

## acceptance criteria

* sample environment data recovered
* disk space cleaned up
* could this have been caught earlier?

**Comment by FreddieAkeroyd** [comment]
See #6432

**Comment by GRyall** [comment]
Issue was resolved and understood. No action remaining, closing ticket.
