### ISSUE TITLE
LET: Set up MERLIN linear sample changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6439]
As a scientist on LET I would like to use the MERLIN linear sample changer.

## Acceptance Criteria
* The MERLIN linear sample changer is set up on LET

**Comment by DominicOram** [comment]
Now happening tomorrow, expect a phone call.

**Comment by DominicOram** [comment]
Now set up. See wrap up email in exp controls inbox for details

**Comment by JamesKingWork** [comment]
Was this really a zero-pointer?

**Comment by JamesKingWork** [comment]
"We had some issues with the homing of the axis where it would not successfully get to the low limit in one move. I implemented a hotfix that will retry this move but it means when homing the axis you will see it stop/start a few times. We will look at a long term fix in the long shutdown with [this ticket](https://github.com/ISISComputingGroup/IBEX/issues/5739#issuecomment-828385127)." - @DominicOram (Just wanted to record that the two are connected)

**Comment by DominicOram** [comment]
Sorry, probably more like 2 after all the homing issues.
