### ISSUE TITLE
CCD100: Confirm we can communicate with new model [TIMEBOX: 1 day]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6440]
As a scientist on various beamlines I would like to be able to communicate with the new CCD100 devices bought by pressure & furnace. JN has done the wiring on these but CG has bought them.

## Acceptance Criteria
* Second CCD100 is tested
* Any oddities about the device are documented on the wiki (we know they use USB over serial so we may want to document cabling at least)

**Comment by DominicOram** [comment]
See email chain on experiment controls inbox for more details

**Comment by FreddieAkeroyd** [comment]
Is this the same device as in #3821 ?

**Comment by rerpha** [comment]
Will be having a play with one we've got in the office to see how we can talk to it.

**Comment by rerpha** [comment]
Have sent off an email to manufacturer to find out if we need to use a specific usb-C to rs-232 adapter as yesterday it wasn't giving the correct response back from the commands sent and instead echo'd weird characters. the baud rate etc. is all fixed going by the manual and this was all set correctly.

**Comment by rerpha** [comment]
No luck with our IOC via ethernet - sending weird null chars after the line feeds, and sometimes random data. 

Will put this in impeded for now as I would like to know if we are using the right usb-c to rs-232 adapter cable.

**Comment by rerpha** [comment]
Ok, this is no longer impeded as the manufacturer has stated you can't use usb-c to rs-232. We will be able to talk to the CCD100 via ethernet, however our IOC will need modifying to suit as there were some funny looking line endings that weren't being parsed by the IOC properly. The commands we were sending from the IOC seemed correct and gave an output but weren;t in the correct format.

**Comment by rerpha** [comment]
Still as part of this ticket we need to:
- [ ] make our IOC work with the new CCD 
- [ ] confirm with CG that we can control and configure it at the same time

**Comment by rerpha** [comment]
Dom and I are going to try and get our IOC working with the Mk3 on Thursday, will log down any details here and on the wiki page

**Comment by rerpha** [comment]
did a bit of testing but i managed to accidentally `make clean` the whole of my epics dir so postponing til i'm back in the office - may be able to have a look tomorrow

**Comment by rerpha** [comment]
I';m not finished yet but thought i should post an update. the device seems to spuriously send command-ok responses after a command but we expect it to return as follows
*<a>*:<cmd>;<params>CRLF
<data>CRLF
!<a>!<response>CRLF

but there are two things wrong. Firstly instead of the above it will respond (if behaving) with this: 

*<a>*:<cmd>;<params>CRLF
<data>CRLF
!<a>!<response>CRLF\00

as the packet seems to have a null terminator byte on the end of it. have got around this by using either \00 as the interminator or the entire command-ok sequence which seem to work fine. 

The second issue is that the device sometimes ONLY sends the last part of the response like so: 

!<a>!<response>CRLF\00

which currently causes the PV to go into read alarm even with a mismatch handler. Freddie and I looked with Wireshark and the device truly was not sending the first part of the command with the command and then the data so this seems like an issue in the device. nowhere in the manual mentions it either! 

progress so far:

https://github.com/ISISComputingGroup/EPICS-ioc/pull/624
https://github.com/ISISComputingGroup/EPICS-CCD100/pull/6

**Comment by rerpha** [comment]
Next course of action is I am going to email the supplier. This doesn't seem like the correct behaviour. We can live with the \00 terminator but the spurious messages are making things difficult.

**Comment by rerpha** [comment]
email sent off, putting in impeded

**Comment by FreddieAkeroyd** [comment]
More a workaround, but did you try a  i/o intr record - it only processes on matching input, so should not alarm. You would just do the "out" and "in" from separate records, and the i/o intr in would just run on matching data and ignore other things https://paulscherrerinstitute.github.io/StreamDevice/processing.html#iointr

**Comment by rerpha** [comment]
I did try i/o on the scan but it didn't appear to be processing the readback, but could try doing it via separate in/out records

**Comment by rerpha** [comment]
Next step i'm goign to try, suggested by Freddie, is to see if the vendor software has the same behaviour with the missing info in the tcp packets. their website is currently down so can't download the software but will have a go with wireshark when i can.

**Comment by rerpha** [comment]
ok, the vendor software actually doesn't query on a loop - it sends `arp3` which means the device starts streaming every 1 second - i am going to try this in the protocol on startup then use i/o intr to capture any data it sends. Wondering if that might solve the weird packets on the other readbacks.

**Comment by rerpha** [comment]
ok, it's still doing it, i'm going to try and get another CCD unit to see if it's just this one that's forgetting to send the command+data packet. if so we could probably try the i/o intrs approach for everything but that's a workaround rather than a proper solution IMO.

**Comment by rerpha** [comment]
Forgot to update this ticket, I had some success with the FTDI driver and using the CCD100 via USB as a Virtual Com Port (VCP) - there are a few errors in the proto but it seems to be able to talk to the device. Still need some investigation as to whether the missing data issue still occurs.

**Comment by rerpha** [comment]
Email sent off 16/08/2021, no reply yet

**Comment by rerpha** [comment]
Have just chased up as no reply as of today

**Comment by rerpha** [comment]
CG has another so will pop down to grab it next week

**Comment by rerpha** [comment]
Have picked it up so moving this out of impeded now

**Comment by FreddieAkeroyd** [comment]
Tested, but needs an asyn interpose layer writing to remove NULLs and so cleanup code

**Comment by rerpha** [comment]
> Tested, but needs an asyn interpose layer writing to remove NULLs and so cleanup code

Might ask for a hand with this in the new year if possible please

**Comment by FreddieAkeroyd** [comment]
Putting impeded as need to retest in lab with new asyn interpose and will not be able to do that before sprint end; also need to see if we can use mk3 modified protocol file with original ccd or need to keep them different

**Comment by FreddieAkeroyd** [comment]
Have merged new protocol under new name `devCCD100_mk3.proto` so it is on instrument if needed, putting into impeded until can check with original and merge protocols

**Comment by FreddieAkeroyd** [comment]
The devices have been returned and the protocol file was merged to allow use in 10.0.0 so it is only a "code review"
