### ISSUE TITLE
CAEN: investigate handling of return values

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6442]
As an instrument scientist, I would like to confirm that I am correctly retrieving values from my CAEN crate.

A bug appeared on MuSR where slot 0, but not 4 and 12 retrieved the names correctly from the device. This was due to a change in the behaviour of the vendor library when giving CAENHVRESULT return values breaking a piece of code that checks this value and cuts off the retrieval of names if the result is not CAENHV_OK.

This ticket is to investigate the handling of the return values in both the old HVCAEN and new HVCAENA IOCs as this change in behaviour could have broken additional features.

Acceptance criteria:

- [ ] Investigation into the handling of return values is carried out on the old and new IOCs
- [ ] Any issues found are listed and fixed (or tickets made to fix them if appropriate)
- [ ] If necessary fixes are deployed to instruments when appropriate

**Comment by JamesKingWork** [comment]
# HVCAEN drivers investigation

Problem: CAEN HV Wrapper library now returns an error code when a slot (and possibly channel) is not in use. In at least one place we were using the returned code to decide whether to continue to check further slots and channel names. Will this be a problem anywhere else?

## HVCAENx527 support module

### HVCAENx527.c

Line 223 to 373 - OK. Not used to control logic only printing.
Line 403 - OK. This returns but that is fine, because if we aren't talking to the crate correctly then it shouldn't initialise it
Line 426 and 434 - OK. Not used to control logic.
Line 490 to 495 - ISSUE. Returns if channel parameter information returns not CAENHV_OK. Cuts off loop and ends initialisation of crate possibly missing later channels.
Line 558 to 614 - MAYBE. If a non CAENHV_OK value is the crate is considered non-initialisable which I think is correct.
Line 923 to 995 - MAYBE. Return values used to detect if we're unable to get a parameter.
Line 999 to 1052 - OK. Return values are checked to return an error code.
Line 1058 to 1278 - ISSUE. Will deinit crate if return value is not CAENHV_OK from any channel parameter. This function is awful!
Line 1283 to 1451 - ISSUE. On failing to set any channel parameter will deinit crate and return thus preventing any checks on further crates.
Line 1458 to 1531 - OK now as return value no longer checks for CAENHV_OK.
Line 1609 to 1632 - OK. Uses return value to know whether to return given channel name.
Line 1635 to 1655 - OK. Uses return value to know what whether to report an error value.
Lines 1916 to 1955 - OK. Uses return value from crate wide wrapper library functions.

## CAENHVAsyn support module

### board.cpp

Line 94 - OK. Returns preventing getting that board's further information, but the returned code is incorrect when the board is not connected so we don't want to get that information anyway.
Lines 114 and 117 - ISSUE. Throws error if not CAENHV_OK meaning that if just this parameter that returns not OK then the rest of the parameters will not be retrieved for that board.

### channel.cpp

Line 74 - OK. Returns preventing getting that board's further information, but the returned code is incorrect when the channel is not connected so we don't want to get that information anyway.
Line 104 and 107 - ISSUE. Throws error if not CAENHV_OK meaning that if it is just this channel parameter which is incorrect no other channel parameters will be retrieved even if correct.

### crate.cpp

Line 30 - OK. Returns preventing getting that crates system properties, but the returned code is not CAENHV_OK when the crate is not connected so we don't want to get that information anyway.
Line 48 - OK. This does not cut off any retrieval of any further system properties.
Line 54 - ISSUE. This break will crash out of the loop on finding a write only parameter, should it be continue?
Line 110 - OK. Same reason as line 30 but for the crate map.
Line 191 - OK. If InitSystem returns an error code then we should be throwing an error as this signifies the problem rather than hiding it.

### system_property.cpp

Line 82 - OK. Throwing an error signifies to the calling function (readOctet) that there was a problem getting the system property. This function handles only the getting of one value at a time and handles the exception correctly.
The same is the case for line 99, 128, 139, 162 and 175. They are all called by different functions but handled correctly in the same way.

### board_parameter.cpp

Line 57 - ISSUE. This would be correct for the same reasons as line 82 in system_property.cpp but it is additionally called by printInfo which does not handle the runtime_error thrown.
Line 80 - OK. For the same reasons as line 82 in system_property.cpp.
Line 106 to 122 - ISSUE. Throws a runtime_error if it cannot get any of the minval, maxval, unit and exp. This is not handled by the function which creates it and will cut off a for loop in GetBoardParams preventing the getting of further board parameters.
Line 152 to 157 - ISSUE. For the same reasons as lin 106 to 122 in this file.

### channel_parameter.cpp

Line 111 to 127 and 158 to 163 - ISSUE. For the same reasons as line 106 to 122 in board_parameter.cpp.
Line 63 - ISSUE. For the same reason as line 57 in board_parameter.cpp.
Line 255 - MAYBE. I am not sure if there is a printInfo that uses this as I can only see a virtual method defined in the header.

**Comment by JamesKingWork** [comment]
PRs: 
- https://github.com/ISISComputingGroup/CAENHVAsyn/pull/3
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6490

**Comment by JamesKingWork** [comment]
To test HVCAENA:

- Check out master on ioc and CAENHVAsyn submodules, make CAENHVAsyn support module and HVCAENA ioc
- In globals.txt use the IP address labelled TEST CRATE from crates.txt in the ISIS_Experiment_Controls share and the settings
```
HVCAENA_01__READ_ONLY=1
HVCAENA_01__SYS_TYPE_0=2
```
- Run the HVCAENA ioc (navigate to ioc/master/HVCAENA/iocBoot/iocHVCAENA-IOC-01 and do `runIoc.bat st.cmd`
- If you git status you will see a file with a name containing crateInfo.txt, save this to somewhere else to avoid overwriting
- Check out the branch Ticket6442_handling_of_return_values checked out for the CAENHVAsyn support module
- Make the support and ioc again 
- Run the ioc and confirm that the crateInfo.txt file produced is the same as the one produced using the master branch

**Comment by FreddieAkeroyd** [comment]
You have looked at the `HVCAENA` in some detail, I have a question. How well does it handle subsequent loss of network connection to a crate after the initial successful connection?

**Comment by JamesKingWork** [comment]
> You have looked at the `HVCAENA` in some detail, I have a question. How well does it handle subsequent loss of network connection to a crate after the initial successful connection?

I have some reservations as the behaviour I have seen is that the IOC logs a lot and I haven't seen it attempt to reconnect. There is a ticket to investigate this behaviour here https://github.com/ISISComputingGroup/IBEX/issues/6159.

**Comment by FreddieAkeroyd** [comment]
Ah OK, from a search of the code I couldn't see where it attempted to reconnect, so wondered  whether it aborted the ioc and relied on procserv to restart it etc.

**Comment by JamesKingWork** [comment]
Not that I've seen but it definitely could do with some proper investigation

**Comment by FreddieAkeroyd** [comment]
I am able to connect to the test crate with the old ioc, but with the new one i get
```
function 'initSystem' : CAENHV_InitSystem:  Connection failed  (num. 4100)
c++ error: CAENHV_InitSystem:  Connection failed  (num. 4100)
```

**Comment by FreddieAkeroyd** [comment]
OK, connects if system type is 3 - but then I get a runtime stack corruption in debug mode

**Comment by FreddieAkeroyd** [comment]
Error seems to be in `CAENHVGetBdParamProp` getting the exponent, code uses `int8_t` and manual says it is `int16_t`, but still crashes when I change it. Will look more another day.

**Comment by FreddieAkeroyd** [comment]
Now fixed and working
