### ISSUE TITLE
MUONFE: investigate homing on momentum slits

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6443]
The muon momentum slits define their homing setup as
```
GalilStartController("Galil","$(GALIL)/gmc/galil_Default_Header.gmc;$(GALIL)/gmc/galil_Home_Thread.gmc!$(GALIL)/gmc/galil_Home_Home.gmc!$(GALIL)/gmc/galil_Home_Home.gmc!$(GALIL)/gmc/galil_Home_Home.gmc!$(GALIL)/gmc/galil_Home_ForwLimit.gmc;$(GALIL)/gmc/galil_Default_Footer.gmc!$(GALIL)/gmc/galil_Muon_Slits.gmc",0,0,3)
```
Is this right? The momentum slits are axis D (0104) but  forward limit home is defined for axis E?

**Comment by FreddieAkeroyd** [comment]
With help of David and Kathryn and Jamie teh axis was moved off its low limit and then the IBEX himing program corrected to be the high limit, it was then successfully homed in IBEX

**Comment by JamesKingWork** [comment]
IS noted today (27th April 2021) "we have beam and a correctly homed set of momentum slits we have noticed an increase in rate" and "Cycle 19/4 (Feb-Mar 2020) had the expected rate. Cycles 20-2 and 20-3 (autumn 2020) had around 2/3 of the expected rate: we didn’t find a reason for this at the time. Now it’s returned to normal.". I think we can consider this ticket done and any further investigation into how the configuration was incorrect can be done as part of a different ticket.
