### ISSUE TITLE
LET: RB Number search not working

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6451]
As an instrument scientist on LET I would like to be able to search for my RB number in the Experiment Details perspective. Currently when you try and search the following error is put in the logs and there are no results:

```
2021-04-28 10:03:12.461 [main] ERROR uk.ac.stfc.isis.ibex.experimentdetails.database.SearchModel - Error searching experiments: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'exp_data.user.organisation' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

## Acceptance Criteria
* Searching RB numbers does not cause the above error
* There is a system test covering this

**Comment by DominicOram** [comment]
Fixed temporarily on LET by setting SQL mode:

```SET GLOBAL sql_mode='';```

But we should fix the query.

**Comment by DominicOram** [comment]
Once the GUI is updated and deployed we should make sure to set the database `sql_mode` back to `'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' on the following instruments:
- [ ] LET
- [ ] IRIS
`

**Comment by rerpha** [comment]
PRs:
IBEX - https://github.com/ISISComputingGroup/ibex_gui/pull/1290
Squish tests - https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/88

Have also updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-Squish to explain the new env var needed for the mysql password

**Comment by rerpha** [comment]
I can't find a way of setting the env var through jenkins so will RDP into squish machine to set it
