### ISSUE TITLE
[30/4/21] Waterbath setup on VESUVIO (Julabo FP50)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6457]
As the instrument scientist involved in the carbon capture project, I want to be able to control the waterbath which will provide the necessary temperature behaviours.

## Acceptance Criteria
* The waterbath is in a component/config with appropriate blocks added

**Comment by DominicOram** [comment]
Water bath set up as a component.

We had no manual for this model so added one to the share.
