### ISSUE TITLE
HIFI Cryomag: Gaussmeter IOC (Lakeshore LS460)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#646]
As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the Gaussmeter will improve that module of code

**Acceptance Criteria**
1. Write an IOC for communicating with a Lakeshore LS460 Gaussmeter (needed in other places eventually)
1. Write an emulator for the LS460
1. Write the IOC test framework for the LS460
1. Create an OPI for the LS460

**Notes**
1. This will be a standard stream/asyn driver
1. There is a copy of the manual in http://www.facilities.rl.ac.uk/isis/projects/ts1/HIFICryomagnetSoftwareImprovement/Manuals/Forms/AllItems.aspx

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 647.  Created by kvlb23 on 2015-02-06T11:47:30, last modified: 2015-02-06T13:20:52_

**Comment by KathrynBaker** [comment]
Original ticket content:

As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the Gaussmeter will improve that module of code
#### Acceptance Criteria
1. Write an IOC for communicating with a Lakeshore LS460 Gaussmeter (needed in other places eventually)
2. Alter the existing LabVIEW code to reference the IOC
#### Notes
1. The existing GUI interface should be maintained until all changes are complete, although the code underneath should be updated to use the PVs from the IOC
2. When altering the LabVIEW GUIs care should be taken over the existence of hidden datasocket links
3. The lvDCOM IOC referring to the DS and EI VI will need to have the PVs now being generated from an IOC removed from it's listing

**Comment by samueljackson92** [comment]
This still needs some work. The issues I found are as follows:

 - The new Lakeshore460 support folder was missing in from the `.gitmodules` file in the EPICS repo. I've added it for you on a branch called `Ticket646_Lakeshore460`.

 - I'm confused as to which DB file should be used? The one in EPICS/ioc or EPICS/support/lakeshore460? One of them needs to be removed in favor of the other and the build needs to be updated accordingly.

 - The DB file needs simulation records adding to it. You can read all about this [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation)

 - The device emulator PR has a few python errors that prevent the emulator from running. There's also a few style comments to fix while you're there.
 - The IOC test framework PR has a merge conflict that needs resolving

**Comment by samueljackson92** [comment]
@Mukz95 can you make a PR for your branch for this on ISISComputingGroup/EPICS?

**Comment by Mukz95** [comment]
@samueljackson92 I have now  created a PR for the branch

**Comment by samueljackson92** [comment]
Ok some additional points. Running the DbUnitChecker shows the following issues:
```
WARNING: Multiple instances of $(P)SOURCE:SP in .\db\lakeshore460.db
WARNING: Multiple instances of $(P)OUTPUTSTATUS:SP in .\db\lakeshore460.db
WARNING: Multiple instances of $(P)OUTPUTSTATUS in .\db\lakeshore460.db
WARNING: Multiple instances of $(P)SOURCE in .\db\lakeshore460.db
WARNING: Multiple instances of $(P)SOURCE:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Multiple instances of $(P)OUTPUTSTATUS:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Multiple instances of $(P)OUTPUTSTATUS in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Multiple instances of $(P)SOURCE in .\LKSH460-IOC-01App\Db\lakeshore460.db
```
Looks like you've got duplicate entries for some records. Additionally none of your PVs are marked as interesting. I'm sure at least one of them is interesting to the user :smile: .

I also found I needed to add the following line to your `std.cmd` just after line 6( `< envPaths`)

Finally I found a couple more comments for your tests in the test framework.

**Comment by Mukz95** [comment]
I have made and commited the changes above.

**Comment by samueljackson92** [comment]
As discussed a few more issues with the DB unit checker:
```
ERROR: Missing description on $(P)UNIT in .\db\lakeshore460.db
ERROR: Missing description on $(P)UNIT:SP in .\db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTSTATUS in .\db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTSTATUS:SP in .\db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTMODE in .\db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTMODE:SP in .\db\lakeshore460.db
ERROR: Missing description on $(P)FILTER in .\db\lakeshore460.db
ERROR: Missing description on $(P)FILTER:SP in .\db\lakeshore460.db
ERROR: Missing description on $(P)RELMODE in .\db\lakeshore460.db
ERROR: Missing description on $(P)RELMODE:SP in .\db\lakeshore460.db
ERROR: Missing description on $(P)UNIT in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)UNIT:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTSTATUS in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTSTATUS:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTMODE in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)OUTPUTMODE:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)FILTER in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)FILTER:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)RELMODE in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing description on $(P)RELMODE:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)RELSMODE in .\db\lakeshore460.db
WARNING: Blank fields on $(P)RELS:MULTIPLIER in .\db\lakeshore460.db
WARNING: Blank fields on $(P)RELMODEREADING in .\db\lakeshore460.db
WARNING: Blank fields on $(P)RELRM:MULTIPLIER in .\db\lakeshore460.db
WARNING: Blank fields on $(P)FIELDREADING in .\db\lakeshore460.db
WARNING: Blank fields on $(P)FIELD:MULTIPLIER in .\db\lakeshore460.db
WARNING: Blank fields on $(P)MAX:MULTIPLIER in .\db\lakeshore460.db
WARNING: Blank fields on $(P)MAXREADING in .\db\lakeshore460.db
WARNING: Blank fields on $(P)RELSMODE in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)RELS:MULTIPLIER in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)RELMODEREADING in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)RELRM:MULTIPLIER in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)FIELDREADING in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)FIELD:MULTIPLIER in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)MAX:MULTIPLIER in .\LKSH460-IOC-01App\Db\lakeshore460.db
WARNING: Blank fields on $(P)MAXREADING in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing units on $(P)RELSMODE:SP in .\db\lakeshore460.db
ERROR: Missing units on $(P)ALLFIELDS in .\db\lakeshore460.db
ERROR: Missing units on $(P)FWIN in .\db\lakeshore460.db
ERROR: Missing units on $(P)FWIN:SP in .\db\lakeshore460.db
ERROR: Missing units on $(P)FNUM in .\db\lakeshore460.db
ERROR: Missing units on $(P)FNUM:SP in .\db\lakeshore460.db
ERROR: Missing units on $(P)RELSMODE:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing units on $(P)ALLFIELDS in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing units on $(P)FWIN in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing units on $(P)FWIN:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing units on $(P)FNUM in .\LKSH460-IOC-01App\Db\lakeshore460.db
ERROR: Missing units on $(P)FNUM:SP in .\LKSH460-IOC-01App\Db\lakeshore460.db
Units in project and number of instances: {}
```

**Comment by John-Holt-Tessella** [comment]
List of pull requests:

 - https://github.com/ISISComputingGroup/EPICS/pull/101/files
 - https://github.com/ISISComputingGroup/EPICS-Lakeshore460/pull/1/files
 - https://github.com/ISISComputingGroup/ibex_gui/pull/559
 - https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/42
 - https://github.com/ISISComputingGroup/EPICS-ioc/pull/183
 - https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/28

**Comment by John-Holt-Tessella** [comment]
This needs to be looked at. I have hooked up a real Lakeshore and the IOC doesn't talk. It is a combination of a couple of things:

1. Commands are arriving too fast the manual says 
    - Guarantee that no other communication is started for 50 ms after the last character is transmitted. 
    - Not initiate communication more than 20 times per second.  "
1. The field values have extra spaces after
1. Some of the set points push every 1s they should be passive
1. We may need to split fast reads and slow reads to get all values back. Do we need all the values?
1. The SP values should do an init
1. Can we refactor the protocol file to take a parameter which is the channel. e.g. instead of
    ```
    getMagneticFieldReading
    {
        out "FIELD?";
        in "%f";
    }

    readXFieldReading
    {
        out "CHNL X";
        getMagneticFieldReading;
    }

    readYFieldReading
    {
        out "CHNL Y";
        getMagneticFieldReading;
    }

    readZFieldReading
    {
        out "CHNL Z";
        getMagneticFieldReading;
    }

    ```
   use
    ```
    getMagneticFieldReading
    {
       out "CHNL \$1";
	out "FIELD?";
        in "%f";
    }
    ```
1. Plus noticed that there is no icon in GUI
1. Probably could do with a graph on the OPI 
1. Add value to Channel
1. Use linking containers of channels X-V

I am afraid that I didn't get that far into the review it will probably need revisting

Also see comment:

 - [ ] IOC

**Comment by FreddieAkeroyd** [comment]
Shouldn't we be issuing the commands as a combined entity e.g. "CHNL X;FIELD?" That would cut down on the number/rate of device accesses and also stop us falling foul of a 50ms delay between "CHNL X" and "FIELD?" when done separately as we currently have. We may still need to guard against doing another combined entity within 50ms

**Comment by GDH-ISIS** [comment]
LabVIEW driver does not appear to require a 50ms delay between commands. Commands sent as a "combined entity" (using ";") do look possible according to the manual - I tried briefly, but did not have much luck beyond a single return value read back (please ensure the command does not exceed 64 characters according to the manual). 
Commands that set a value do not appear to return a reply in the LabVIEW driver and it takes approximately 4 seconds to read the information it requests for 4 channels (x,y,z and vector). The information read back could be selectively chosen if necessary to increase the update rate on the more important/frequent information (fanout???)

**Comment by FreddieAkeroyd** [comment]
you can send multiple commands but only one query (which must be the last item) as part of a ; separated string. So it will only help for single reads, but would allow sending several setpoints at once (if that is useful) that fit into a 64 character string

**Comment by ChrisM-S** [comment]
Seems very similar to the Thurlby PSUs, send another command too soon and you are dead, requesting a response neatly links you into the response time of the kit - also separated by a semicolon... :-)
https://github.com/ISISComputingGroup/EPICS-TDKLambdaGenesys/pull/2#issuecomment-225826517

**Comment by esouthren** [comment]
Pull requets (other pull requests in link)

https://github.com/ISISComputingGroup/EPICS-ioc/pull/210
