### ISSUE TITLE
HLM View: Review Code

### ISSUE THREAD

**Issue by mihai-stfc** [ISISComputingGroup/IBEX#6460]
Review the code and functionality of the [HLM View](https://github.com/ISISNeutronMuon/HLM_View) web app.

#### To run
To set-up and run the app, check the [deployment notes](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/HLM-Web-Server:-Apache-and-mod_wsgi-deployment-notes). 

For review purposes, running it with the Django development server should be enough:
1. Make sure `DEBUG` is set to `True` in `project\settings.py`.
2. Add the non version controlled static files: [static.zip](https://github.com/ISISNeutronMuon/HLM_View/files/6404513/static.zip) 
3. To use the Grafana dashboard running on NDAHEMON, replace all iframe Grafana links in `hlmview\templates` from `localhost:3000` to `ndahemon:3000` (in `building.html` and `details.html`)
4. Use an online Django secret key generator and create a `secret_key.txt` file with the key inside in the `HLM_View\project` folder. 
5. Run `python manage.py runserver` in `HLM_View\`

**Comment by aaron-long** [comment]
Added the details about the secret key (django) generation to the review ticket and wiki. Looks really good 👍
