### ISSUE TITLE
Revisit Reflectometry Scripts

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6462]
As an INTER scientist, I would like the shared reflectometry script library to fulfil requirements for INTER:
- The scripts should cater to a setup with 2 mirrors (currently we expect a single supermirror). This should be reflected in the InstrumentConstants class, which needs to be made more flexible for differente setups. This may need some discussion with the INTER scientists to clarify requirements
- Height / Height2 aka. Coarse Height / Fine Height aka. Sample Height/Sample Offset mean different things on different instruments. We either need to cater to different naming schemes in the scripts or find a convention that works for all reflectometers

#### Acceptance Criteria
- `run_angle` script allows for a case with two supermirrors
- `InstrumentConstants` class expects a sensible set of constants to be defined in the reflectometry server (e.g. don't complain about `SM_Z` missing if `SM1_Z` and `SM2_Z` are used
- Cater to INTER's naming scheme of fine / coarse sample height axes (without breaking it for POLREF)

**Comment by DominicOram** [comment]
Not all of this is required for cycle, spun out https://github.com/ISISComputingGroup/IBEX/issues/6499 which is the minimum required on INTER.

**Comment by ThomasLohnert** [comment]
Superseded by https://github.com/ISISComputingGroup/IBEX/issues/7596
