### ISSUE TITLE
Journal Viewer: Some instruments are missing access on the independent journal viewer

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#6466]
The list at https://data.isis.rl.ac.uk/journals which is used by the independent journal viewer software needs updating with instruments which have been added/updated in the last few years.

Missing are:

  ARGUS
  CHRONUS
  EMMA-A
  IMAT
  ZOOM

***Acceptance Criteria***
1. The missing instruments are added to the journal viewer export link
2. Muon scientists are informed

**Comment by FreddieAkeroyd** [comment]
Is the EMMA-A directory incorrectly named on the archive? The data files all start EMMA-A but the directory is \\isis\inst$\ndxemma  ARGUS and CHRONUS are probably still looking at a riken machine that no longer exists

**Comment by FreddieAkeroyd** [comment]
Though IMAT and ZOOM were not on the web page, the relevant links were in place for journal viewer to work. It is just argus and chronus that are missing

**Comment by FreddieAkeroyd** [comment]
Links added for ARGUS and CHRONUS. EMMA-A worked if referred to as EMMA  as hyperlinks need share name (NDXEMMA) not machine name (NDXEMMA-A).  I’ve added additional file system links to make it work under either name.

**Comment by FreddieAkeroyd** [comment]
Scientists notified as per email chain in exp controls

**Comment by DominicOram** [comment]
Confirmed now works
