### ISSUE TITLE
HIFI Cryomag: Keithley 2700 Scanner IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#647]
As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the scanner will improve that module of code

**Acceptance Criteria**
1. Write an IOC for communicating with a Keithley 2700
1. Write an emulator for the Keithley 2700
1. Write the IOC test framework for the Keithley 2700
1. Create an OPI for the Keithley 2700

**Notes**
1. This will be a standard stream/asyn driver
1. There is a copy of the manual in http://www.facilities.rl.ac.uk/isis/projects/ts1/HIFICryomagnetSoftwareImprovement/Manuals/Forms/AllItems.aspx
1. Consider undertaking #2460 with this, and incorporating both with the existing Kiethley 2400

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 648.  Created by kvlb23 on 2015-02-06T11:50:21, last modified: 2015-02-06T13:21:04_

**Comment by KathrynBaker** [comment]
Original content of ticket;

As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the Scanner will improve that module of code
#### Acceptance Criteria
1. Write an IOC for communicating with a Keithly 2700 Temperature Scanner
2. Alter the existing LabVIEW code to reference the IOC
#### Notes
1. The existing GUI interface should be maintained until all changes are complete, although the code underneath should be updated to use the PVs from the IOC
2. When altering the LabVIEW GUIs care should be taken over the existence of hidden datasocket links
3. The lvDCOM IOC referring to the DS and EI VI will need to have the PVs now being generated from an IOC removed from it's listing

**Comment by KathrynBaker** [comment]
The commands and behaviour for this are very similar to the Keithley 200 (Ticket #2460), as such the requirements for that device should be considered whilst writing this, as should the structure of the protocol files, and st.cmd files. See the Danfysik IOC and support module for an example of one IOC allowing the use of multiple protocol files and setups based on a model of device

**Comment by AdrianPotter** [comment]
It is imperative to cross-link pull requests against the original tickets. Otherwise I do not know what changes are associated with this work and I could easily miss something

**Comment by AdrianPotter** [comment]
Changes requests across most pull requests. It's not bad, but there are a few issues to address that are repeated throughout the code.

This will likely be blocked until the Lakeshore is merged unless its code can be removed from the PRs. That's possible but would require high level Git magic that probably isn't worth the risk.

**Comment by AdrianPotter** [comment]
Please let me know, or come and see me if you'd like to discuss or clarify any of the requested changes.

**Comment by AdrianPotter** [comment]
Someone else will need to pick up this rework now that @Mukz95 has finished

**Comment by esouthren** [comment]
Link to IOC and other pull requests associated with ticket:

https://github.com/ISISComputingGroup/EPICS-ioc/pull/238

**Comment by AdrianPotter** [comment]
There are some comments to address on each PR. I haven't yet run the code since the nature of the changes would invalidate any functional test I ran now anyway. Someone else please feel free to pick up the re-review when done since I'll be away.

**Comment by esouthren** [comment]
Note - the physical Keithley 2700 is on my desk, I can MOXA it if anyone wants to do the review on the hardware.

**Comment by Tom-Willemsen** [comment]
Full list of PRs for this ticket (putting them all in one list as the cross-links on this issue are getting confusing).
- https://github.com/ISISComputingGroup/EPICS/pull/100/files
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/238
- https://github.com/ISISComputingGroup/EPICS-KeithleyDVM/pull/2/files
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/60/files
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/51/files
- https://github.com/ISISComputingGroup/ibex_gui/pull/648/files
