### ISSUE TITLE
genie_python: check use of ca_pend_io 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6470]
There have been issues with channel acccess on HRPD / MERLIN. When looking at the genie python code it would appear that the use of pend_io does not seem quite to be correct as per CA docs. pend_io is not needed for a search if a callback is specified, also with completion callbacks pend_event/poll should strictly be used rather than pend_io. As we use pre-emptive callbacks in CA then it may not matter quite as much

## Acceptance criteria

- recommended CA calls are used

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/326
