### ISSUE TITLE
Reflectometry: Components ordered incorrectly

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6472]
POLREF reported an issue where parameters suddenly stopped accepting setpoints. Some investigation revealed that this is because the server is throwing exceptions when calculating the incoming beam down the beam after setting a specific supermirror angle of -0.025. The IOC them needs a restart before accepting any setpoints again. The exceptions were:

```
[2021-05-03 22:10:01] Exception occurred in processing an event: Component ordered incorrectly 5182.759283006313 > 5182.635156201881, has LONG_AXIS moved too far?
```

It looks like the theta component is using it's own outgoing beam as incoming beam, but not sure where the issue stems from, needs more investigation.

#### Acceptance Criteria:
- Cause of the error is understood and fixed
- Write a test to catch this case

**Comment by ThomasLohnert** [comment]
Cause of error documented on PR: https://github.com/ISISComputingGroup/EPICS-refl/pull/39

After discussion with @DominicOram and @RaiBishal, we have decided that the check is not so important as it is more of a safeguard for theoretical future beamlines, so it is preferable to remove it for now and revisit this requirement a new beamline looms, rather than spend a lot more time delving into the bench code now.

**Comment by DominicOram** [comment]
Can you add some points to this @ThomasLohnert? it was more than a 0!
