### ISSUE TITLE
HIFI Cryomag: Compressor Code replace

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#648]
As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the interactions with the compressors will improve that module of code
#### Acceptance Criteria
1. Write an IOC for communicating with the compressors
2. Alter the existing LabVIEW code to reference the IOC
#### Notes
1. The existing GUI interface should be maintained until all changes are complete, although the code underneath should be updated to use the PVs from the IOC
2. When altering the LabVIEW GUIs care should be taken over the existence of hidden datasocket links
3. The lvDCOM IOC referring to the DS and EI VI will need to have the PVs now being generated from an IOC removed from it's listing
4. The compressors use an odd (and unavoidable by the looks of things) protocol
5. It may be possible to use it directly in an IOC too - this would need investigating further, otherwise the communciations may need to remain in LabVIEW with the IOC being accessed either via lvDCOM or other suitable methods.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 649.  Created by kvlb23 on 2015-02-06T11:59:48, last modified: 2015-02-06T13:21:24_

**Comment by LiamPanchaud** [comment]
PRs:

[OPI](https://github.com/ISISComputingGroup/ibex_gui/pull/893)

**Comment by Alistair-McGann-Tessella** [comment]
Only minor changes required, overall it functions well

**Comment by Tom-Willemsen** [comment]
Discussed in sprint planning: can this ticket be moved out of ready? (either rework done or move back into bucket or ...)

**Comment by KathrynBaker** [comment]
@ChrisColeExpControl This is probably something for you to pick up as part of the cryomag work before moving on to the PSUs
