### ISSUE TITLE
setup cloud vnc acccess for ESS to ess detector computer 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6482]
ESS need access via cloud to linux detector computer

**Comment by FreddieAkeroyd** [comment]
Access was set up and successfully used for experiments

**Comment by rerpha** [comment]
in case someone needs to do something like this in the future: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Remote-Working
