### ISSUE TITLE
TRITON: Fix channel poll rate

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6484]
When reacting to a support call on OSIRIS where the Triton IOC was failing to get the 4K and J-T temperature values I noticed in the Triton log: `ErrorCan't set "IN:OSIRIS:TRITON_01:CHANNELS:T2:STATE.SCAN" to "15 second" Extraneous characters`. A macro has recently been added to configure the CHANNEL_POLL_RATE which defaults to "15 second" which is not a valid value according to https://docs.epics-controls.org/en/latest/guides/EPICS_Process_Database_Concepts.html#periodic-scanning.

## Acceptance criteria:

- [x] Instruments hotfixed with a valid scan rate
- [x] Valid scan rate set as default for triton
- [x] Scientists using triton are aware they may need to restart their IOC to get this fix
- [x] Hotfix listed at https://github.com/ISISComputingGroup/IBEX/wiki

## Notes:

get_ioc_usage.bat shows the following instruments using it:

- [ ] DEMO has TRITON_01
- [x] IMAT has TRITON_01
- [x] IRIS has TRITON_01
- [ ] ~~MERLIN has TRITON_01~~ is on older version of IBEX
- [x] OSIRIS has TRITON_01 (Don't need to be notified as they already have it set to 2 second for their component)
- [x] LET has TRITON_01
- [x] EMU has TRITON_01 (Don't need to be notified as they have it set to 2 second from the globals.txt)
- [x] MUSR has TRITON_01 (Don't need to be notified as they aren't running IBEX)

**Comment by davidkeymer** [comment]
Additional PR by @FreddieAkeroyd to change default value to 10 seconds in `config.xml`
https://github.com/ISISComputingGroup/EPICS-ioc/pull/617
