### ISSUE TITLE
GUI: Be clearer that Run Control Menu is temporary

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6488]
As an instrument scientist I would like it to be clearer that setting I put in the run control menu will be overridden by the configuration values when I switch configuration and how I can remedy this.

## Acceptance Criteria
* There is a message to this effect on the menu
* There is a link to the user manual providing more detail on how the differences between the run controls
* Optionally, there is a button that guides you to where you can edit the run control in the configuration

**Comment by Adam-Szw** [comment]
Ticket needs to be completed about writing tests for this [#6639](https://github.com/ISISComputingGroup/IBEX/issues/6639)

**Comment by rerpha** [comment]
Looks good - I have made a tiny change and renamed the button text from "show manual \n run control" to "show user manual \n run control" as it confused me at first that I was being shown the "manual run control" - have pushed this. 

also, release notes: https://github.com/ISISComputingGroup/IBEX/pull/6641
