### ISSUE TITLE
Script Generator: Reformulate how we save and load parameters to make it more user friendly

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6492]
As a script generator user, I find the current parameters file workflow a problem. When I click "Generate Script", an sgp (parameters file) is also created. I can currently also generate an sgp file by clicking "Save Parameters". When I click "Save Parameters" this updates the pointer and UI label to the current script generator parameters file, but when I click "Generate Script" the current parameters file pointer is not updated. My workflow expects the current parameters file to be the same as the script I am generating. The load and save parameters file mechanism is more complex than required. 

This ticket is to couple the parameters file to the script fully removing the "Save Parameters" and "Save Parameters As" button and renaming the "Load Parameters" button to "Load Script" as these are confusing the workflow. The new workflow will be to click "Generate Script" which produces the two files and updates the current script parameters file.

## Acceptance Criteria:

- [x] The "Save Parameters" and "Save Parameters As" buttons are removed
- [x] When I press "Generate Script" two files are saved and the current script parameters file asterisk is updated
- [x] When I press "Generate Script As" I am able to give a name to the files saved and the current script parameters name and asterisk is updated
- [x] The "Load Parameters" button is renamed to "Load Script"
- [x] The "Current Parameters File" label is changed to "Current Script"
- [x] Fix squish and unit tests to work with changes

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1317

**Comment by JamesKingWork** [comment]
Didn't mean to move this back, it is complete
