### ISSUE TITLE
Script Generator: Time of last generation

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6493]
As a user of the script generator, I would like to know time and date of the last time I generated a script alongside the "Current parameters file".

## Acceptance criteria:

- [ ] Time and date of the last generation is displayed alongside the "Current parameters file" which is updated each time a script is generated

## Notes:

- This ticket was written assuming https://github.com/ISISComputingGroup/IBEX/issues/6492 is complete. If it is not complete then whenever the script parameters file is updated the time and date should be updated

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1319

**Comment by JamesKingWork** [comment]
Probably best to review after https://github.com/ISISComputingGroup/IBEX/issues/6492 is complete

**Comment by JamesKingWork** [comment]
Code looks good and has been merged, for the rework can we add a couple of squish tests to make sure this is clear at the start and then updates each time a script is generated

**Comment by mihai-stfc** [comment]
> Code looks good and has been merged, for the rework can we add a couple of squish tests to make sure this is clear at the start and then updates each time a script is generated

Added squish tests: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/104

**Comment by mihai-stfc** [comment]
Updated points to cover squish tests as well
