### ISSUE TITLE
CHIPIR: Set up TTI PL303-3 [14/05/21]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6496]
As a user on CHIPIR I would like to use a TTI PL303-3 in my experiment.

## Acceptance Criteria
* The TTI is set up so that values can be read/set in SECI
* https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Thurlby-Thandar-TTI-PLP-Power-Supply is updated with information about how to connect up the device

**Comment by davidkeymer** [comment]
* PSU in screened room connected directly to nearby MOXA using standard cabling.  (Communication could not be established using the sockets and patch panel, although this works for Ethernet devices.)

* Output fed to blockhouse using SE patch panel.

* VI updated from SourceSafe and configured accordingly.

* SECI blocks created and demonstration of [web dashboard](http://dataweb.isis.rl.ac.uk/SeciWeb/DefaultImplement.aspx?Instrument=chipir) given.  Monitoring the PSU output was all that was required for the remote users.

* Device [wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Thurlby-Thandar-TTI-PLP-Power-Supply) updated with additional information.

**Comment by DominicOram** [comment]
All looks good, thanks @davidkeymer
