### ISSUE TITLE
HIFI Cryomag: Main Magnet Control rewrite

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#650]
As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the Main magnet control will improve that module of code
#### Acceptance Criteria
1. Write an IOC for communicating with Main Magnet PSU
2. Alter the existing LabVIEW code to reference the IOC
#### Notes
1. The existing GUI interface should be maintained until all changes are complete, although the code underneath should be updated to use the PVs from the IOC
2. When altering the LabVIEW GUIs care should be taken over the existence of hidden datasocket links
3. The lvDCOM IOC referring to the DS and EI VI will need to have the PVs now being generated from an IOC removed from it's listing
4. A greater level of reverse engineering is required to ensure that the functionality is retained

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 651.  Created by kvlb23 on 2015-02-06T13:22:41, last modified: 2015-02-06T13:23:42_

**Comment by KathrynBaker** [comment]
Well and truly superseded by now with other cryomag work - this whole step is being skipped
