### ISSUE TITLE
Web dashboard: Use only channel access for config data

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6517]
As a developer I would like to remove code that is rarely used and has broken in the past. As of https://github.com/ISISComputingGroup/IBEX/issues/6511 the web dashboard uses channel access to get the config information and only falls back on the blockserver's webserver if this fails. Provided it works we should just use channel access and remove the blockserver webserver, using a camonitor will also reduce the traffic on the webserver e.g. going some way to https://github.com/ISISComputingGroup/IBEX/issues/3635

## Acceptance Criteria
- [ ] The JSON_bourne logs are checked to make sure channel access does not fail without good reason
- [ ] The fallback webserver code is removed
- [ ] The webserver is removed from the blockserver
- [ ] The wiki is updated
- [ ] We use a monitor rather than a caget in JSON bourne

**Comment by JamesKingWork** [comment]
Currently testing removing the use of the webserver on json bourne, want to see if it fixes our current issues where json bourne just stops running (for seemingly no apparent reason)

**Comment by rerpha** [comment]
new one does this
