### ISSUE TITLE
POLREF: Set up little blue sample changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6518]
As an instrument scientist on POLREF I would like to be able to use my little blue sample changer.

## Acceptance Criteria
* The little blue sample changer works on POLREF

**Comment by DominicOram** [comment]
The axis was originally going to use a SMC100 controller but we could not get this to work. Instead we connected it to a spare Galil axis, 0505. The limits on the device were the wrong way round, I compensated for this by reversing the motor/encoder type. However, homing to a limit was not working, likely because of the reversed limit switches. The scientist was happy to run without regularly homing it.

**Comment by rerpha** [comment]
can verify the motor was being controlled by IBEX, and is still showing readbacks.
