### ISSUE TITLE
Reflectometry: High RAM usage in IBEX [TIMEBOX: 2.5 Days]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6524]
As an instrument scientist on POLREF I would like IBEX to use less RAM as I am getting warnings from windows about it. The instrument scientists will give us some screenshots of the resource usage.

## Acceptance Criteria
* RAM use is reduced
* System tests are correctly capturing this

**Comment by JamesKingWork** [comment]
Squish tests are currently capturing a high amount of memory usage in suite_configuration_tests.tst_can_create_lots_of_blank_configs so this is a good time to do this

**Comment by RaiBishal** [comment]
## High RAM usage in POLREF:
![Refl high ram](https://user-images.githubusercontent.com/55101160/122772349-31ad3500-d29f-11eb-8640-e78366ae99da.PNG)
The Screenshot above shows the jump in memory usage when OPI in reflectometry perspective is opened. (Including all tabs)
This seems to be normal for reflectometry OPI as it is a huge OPI. The memory usage is still below the maximum limit (1GB). 


### Memory that is not being cleared by GC:
![tenured](https://user-images.githubusercontent.com/55101160/122781484-c61b9580-d2a7-11eb-971b-6f36aabee721.PNG)

Here, the memory in Old space is not being collected by GC even after manually triggering GC. This is taking up 526MB of memory. The screenshot was taken after Refl OPI was opened in its refl perspective. Memory in Old space before refl OPI was opened was approx 150MB. 

### Conclusion:
There does not seem to be any obvious memory leak. It seems that the Refl OPI is taking up roughly 400MB of RAM. The max JVM heap size is 1GB and the RAM usage in POLREF does not seem to go above 1GB but stays around 971MB before GC, hence the RAM usage is reasonable. @ThomasLohnert is looking to have the latest version of IBEX in POLREF which has the latest version of Refl OPI. We can check if the latest version of IBEX in POLREF has any performance issues (slow client) and create new tickets accordingly.


PR to correctly capture high RAM usage:
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/100

**Comment by DominicOram** [comment]
It feels a bit like we're just shifting the goal posts here. Yes the client is set at a max of 1 GB but I don't think I'm comfortable calling it a day as:
* 400 MB is massive for one small part of the GUI
* The creating lots of blank configs test did work at some point, the limit was set there to make sure it didn't produce memory leaks

I think to be happier with this it would be good to know:
* What exactly is using all the memory in the refl OPI? The sheer number of PVs? The scripts?
* Why has the creating a lot of blank configs test now failed? Is the memory actually growing with each new config (indicating a memory leak)? Is the 1 GB it's now set to small enough to catch future memory leaks?

Also has the IS been told about the DAE memory leak, they asked to know about anything we found.

**Comment by RaiBishal** [comment]
> * What exactly is using all the memory in the refl OPI? The sheer number of PVs? The scripts?

This is mostly being used by `RhinoScriptStore` and roughly about 150MB. Rest is occupied by other objects/classes which looks reasonable.

> * Why has the creating a lot of blank configs test now failed? Is the memory actually growing with each new config (indicating a memory leak)? Is the 1 GB it's now set to small enough to catch future memory leaks?

There is no memory leak in heap when we are creating lot of blank configs. If there is a memory leak then the leak is happening else where (I ran out of time to investigate as I was only looking for leak in heap memory). Squish gets the 
memory of IBEX as a whole process rather than the just size of the heap, consequently, failing the memory leak test.

> Also has the IS been told about the DAE memory leak, they asked to know about anything we found.

I have not, windows just happen to give us warning about DAE using excessive memory when we were investigating IBEX in POLREF. I will let them know about it.

**Comment by DominicOram** [comment]
I appreciate that we've reached the timebox on this but it still feels like there are a lot of unanswered questions.

> This is mostly being used by RhinoScriptStore and roughly about 150MB. Rest is occupied by other objects/classes which looks reasonable.

Great, why is RhinoScriptStore using so much memory? Is the problem lots of small scripts running or one large script? Could we change something about the way we're using scripts in the reflectometry perspective to reduce this RAM usage? It looks like we could change it to use the inbuilt JS interpreter ([here](https://github.com/ControlSystemStudio/cs-studio/blob/f0ca39dca14f11911d665fd7529c03da8aeede98/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder/src/org/csstudio/opibuilder/script/ScriptStoreFactory.java#L195)). Does this improve RAM usage?

> There is no memory leak in heap when we are creating lot of blank configs. If there is a memory leak then the leak is happening else where (I ran out of time to investigate as I was only looking for leak in heap memory). Squish gets the
memory of IBEX as a whole process rather than the just size of the heap, consequently, failing the memory leak test.

Ok, but that doesn't answer the question of why that test is now failing when it wasn't previously.

> This will depend on the size of the objects that are leaking. I think we need to determine the base memory IBEX should consume and determine from there on wards on maximum memory it can have so that the memory is not too big or small.

We did determine the base memory, it was the 500 MB that the test was passing with. By increasing the test limit we've now shifted the goal posts on this. The memory usage of the JVM works something like this:
1. You set a max heap size
2. It starts with a small heap, if it needs more it will increase the heap size a bit
3. Once it reaches the max heap size it no longer increases but just runs the GC more often (increasing CPU usage)
The client was allowed 1GB of heap so that it would rarely get to stage 3. The system tests were kept at 500MB so that if the client went above 500MB (which should be rare and probably indicates a memory leak) we would catch it. I know don't think we would catch such a memory leak?

I think that given that we've reached the timebox on this I'll merge to get the tests passing and I've made a new ticket to address the above issues (https://github.com/ISISComputingGroup/IBEX/issues/6652)

**Comment by RaiBishal** [comment]
Thanks for reviewing this ticket. I will leave some comments and my "theory" on why the squish test might be failing. It might be helpful or confusing for a future developer looking to working on #6652.

> Ok, but that doesn't answer the question of why that test is now failing when it wasn't previously.

The only plausible answer I can think of is dependency update. Squish test had been failing since dep update back in Dec 2020(if I am not mistaken). If this is the case, It also makes sense why the heap consumption is not increasing whilst the overall memory is during the squish test. 
Unfortunately, to test this theory, I would have had to date my dependencies back to whatever it was before Dec 2020, and was I running out of time. However, You can use jcmd native memory tracking tool to determine where the memory is being consumed the most. I doubt it will be as easy as doing heap dump in VisualVM.

>The system tests were kept at 500MB so that if the client went above 500MB (which should be rare and probably indicates a memory leak) we would catch it

This is just out of curiosity, how did we determine that 500MB is the limit? It looks to me that 500MB is not a big enough playing room for IBEX to determine whether there is a memory leak or not.

**Comment by DominicOram** [comment]
No worries, it's good work, I'm glad we know more about it all, it would just be nice to know even more! Yh, dependency updates might be part of it. If we can't easily get it back below 1GB I think it's fine, we just need to be more certain about what is using the memory, why and why we can't reduce it. 500MB was decided as the GUI worked comfortably at this limit. The limit was made 3 years ago (https://github.com/ISISComputingGroup/IBEX/issues/3574) and so it could well not be attainable anymore but I'm worried that if we don't keep a bit of an eye on it we will just let it slip to get bigger and bigger.
