### ISSUE TITLE
HIFI Cryomag: Magnets Control rewrite

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#653]
As a support person, I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the main magnets control will improve that module of code
#### Acceptance Criteria
1. Create an IOC to cover the logic detailed in the Software Requirements System and the appropriate section of the Test Plan documents in the Detailed Requirements section of the HIFI Cryomagnet rewrite project (http://www.facilities.rl.ac.uk/isis/projects/ts1/HIFICryomagnetSoftwareImprovement/Detailed%20Requirements/Forms/AllItems.aspx)
2. A ticket is created to cover the testing with hardware
#### Notes
1. For the initial version there are some changes needed to the VI running on NDXHIFI to use this IOC instead of the existing LabVIEW solution, this may be spun out into another ticket

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 654.  Created by kvlb23 on 2015-02-06T13:27:26, last modified: 2015-02-06T13:29:49_

**Comment by KathrynBaker** [comment]
Original text of ticket:

As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the main mangets control will improve that module of code

Acceptance Criteria
Create an IOC to cover any logic not currently enacted (mainly from this VI)
Alter the existing LabVIEW code to reference the appropriate IOCs
Notes
The existing GUI interface should be maintained until all changes are complete, although the code underneath should be updated to use the PVs from the IOC
When altering the LabVIEW GUIs care should be taken over the existence of hidden datasocket links
The lvDCOM IOC referring to the DS and EI VI will need to have the PVs now being generated from an IOC removed from it's listing
Some extra reverse engineering may be required before undertaking this.
This is reliant on stories #650 and #651 being completed first

**Comment by KathrynBaker** [comment]
Requirements and Testing documents available in http://www.facilities.rl.ac.uk/isis/projects/ts1/HIFICryomagnetSoftwareImprovement/Detailed%20Requirements/Forms/AllItems.aspx
Please use these documents to guide testing if unsure
The behavior of the underlying IOCs is not part of this testing, and these are still being developed, this is echoed in the follow on tickets listed below
Note that the ramp table functionality has not been implemented, as the IOC it needs to link to is still in development

IOC Testing Framework PR: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/413
IOC PR: https://github.com/ISISComputingGroup/EPICS-ioc/pull/585
OPI PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1255
Release Notes Branch: https://github.com/ISISComputingGroup/IBEX/blob/Ticket653_Add_IOC_HIFIMAGS/release_notes/ReleaseNotes_Upcoming.md

Follow on tickets to cover work not yet undertaken:
Tests with devices in recsim/devsim were not possible as there is still development ongoing, new ticket #6220 to cover this
Implement the ramp table functions which were not pushed for as there was still development ongoing, new ticket #6221 to cover this
There are some potentially confusing names now in the IOC directory, the unused IOC should be removed, new ticket #6222 has been created to resolve that
Hardware testing requires access to the hardware, and the cryosms IOC to be completed, new ticket #6223 allows for this
This should be used before HIFI is converted to IBEX, ticket #6224 covers the need for changes within the appropriate VIs
