### ISSUE TITLE
genie_python: review obsolete packages

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6531]
Now support for python 2.7 has been dropped, we should review `requirements.txt` for any unnecessary additions as these can cause issues e.g. enum34 caused problems on python startup on ESS daq linux machine. Do we need backports, 2to3, six, ...

## Acceptance criteria

- Figure out what each requirement is used for
- Unnecessary modules removed
- It is obvious from the release notes what we have removed

**Comment by FreddieAkeroyd** [comment]
Maybe do during #6370 ?

**Comment by rerpha** [comment]
Was just about to suggest this!

**Comment by rerpha** [comment]
Follows on from #6132

**Comment by DominicOram** [comment]
As we do this we should try and document what each dependency is for and why it is there, probably jut as comments in the requirements.txt. I think we have got a lot of stuff in there that people have just thrown in.

**Comment by rerpha** [comment]
> As we do this we should try and document what each dependency is for and why it is there, probably jut as comments in the requirements.txt. I think we have got a lot of stuff in there that people have just thrown in.

or better yet, we make separate `requirements.txt`s for each repository that requires special dependencies, even if they are stored in genie python itself. You can create requirements files with custom names and then include them in a parent `requirements.txt`

**Comment by rerpha** [comment]
so for example we have a `bskafka-requirements.txt` which means we can pull anything kafka out of the main `requirements.txt`

**Comment by DominicOram** [comment]
Yes, e.g. https://github.com/ISISComputingGroup/IBEX/issues/5426

**Comment by KathrynBaker** [comment]
Estimated in [IBEX Pointing (scrumpy)](https://play-game.scrumpypoker.com/#/room/nkkgetpzayqn) to **3**, the average vote was **2.8** story points.

**Comment by Tom-Willemsen** [comment]
Substantially similar issue in other repo. `genie` itself no longer has these requirements (or any others that it doesn't directly use)
