### ISSUE TITLE
Standalone script generator: stop python from generating .pyc files

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6533]
As a developer I would like the standalone version of the script generator to NOT generate .pyc bytecode files. This takes up unnecessary space and can be avoided by doing [this](https://stackoverflow.com/questions/9408366/stop-python-from-generating-pyc-files)

Obviously this is less performant so investigation on performance implications should be done first. 

### Acceptance criteria
- The standalone script generator is investigated to see if it is unusable without the .pyc files
- If not, these are disabled when building

**Comment by DominicOram** [comment]
Do you mean pyc files of the generated script? Is it definitely the script generator doing this or does genie_python do it when you load it in?

**Comment by rerpha** [comment]
> Do you mean pyc files of the generated script? Is it definitely the script generator doing this or does genie_python do it when you load it in?

pyc files of any python code bundled in with the script generator by the looks of it. There are lots of .pyc files for `tests` in site-packages which surely don't need to exist? Maybe we should run `pyclean` before making the executable? I have no idea what's doing it, all I know is they are taking up extra space for probably little gain. Instrument PCs are inherently short on space and seeing as the script generator isn't built for raw performance why do we keep the .pyc files?

**Comment by DominicOram** [comment]
Ok, how much disk space are we actually talking here? If we're really that desperate to save space this seems like a very small amount.

**Comment by rerpha** [comment]
> Ok, how much disk space are we actually talking here? If we're really that desperate to save space this seems like a very small amount.

just over 120MB, so not huge amounts of space, but over 10% of the built script generator's directory size

**Comment by JamesKingWork** [comment]
We should think carefully about whether we want to take the hit on performance as we have already had poor performance on instrument machines before

**Comment by rerpha** [comment]
> We should think carefully about whether we want to take the hit on performance as we have already had poor performance on instrument machines before

ok, going to close this, I think making the script generator unstable or less performant isn't worth the risk just for some disk space. No ISs have commented/moaned about it, was just my own way of thinking how we can free up some disk space on instrument machines.

**Comment by JamesKingWork** [comment]
> 
> 
> > We should think carefully about whether we want to take the hit on performance as we have already had poor performance on instrument machines before
> 
> ok, going to close this, I think making the script generator unstable or less performant isn't worth the risk just for some disk space. No ISs have commented/moaned about it, was just my own way of thinking how we can free up some disk space on instrument machines.

And that is a good thing to think about as scientists have expressed concern at the size of the script generator, but we just need to think carefully about trade offs
