### ISSUE TITLE
Support: Keithley 2410 usage on HRPD

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6534]
As an HRPD scientist, I want to use a Keithley 2410 to source voltage and measure current. We support the Keithley 2400 series, but the `:READ?` command does not seem to work with this model. They also wanted to measure on current not resistance which needed to be set correctly in the protocol.

## Acceptance criteria:

- [x] Scientists are happy with Keithley 2410 setup on HRPD
- [x] Any changes to 2410 are configurable for usage for next time

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-Keithley2400/pull/3
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/619

Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6535

**Comment by JamesKingWork** [comment]
Turns out I made a mistake you can read from the 2410 with `:READ?` just need OUTPUT:MODE to be set to ON

**Comment by FreddieAkeroyd** [comment]
The model supports both `READ` and `MEAS` according to the manual, so we need to think a bit more as they do slightly different things. Do we just want to MEAS everywhere? MEAS appears to be a one shot measurement and performs a configure, read does not do a configure or turn output on, it says it is for a sequence of readings

**Comment by JamesKingWork** [comment]
It sounds to me like we should keep `:READ?` as we are in theory doing a series of measurements and don't want to change the output to on with every read I would think

**Comment by JamesKingWork** [comment]
Now happily running on HRPD thanks to @KathrynBaker

**Comment by rerpha** [comment]
where HRPD are using a keithley 2410 do we need to use a pv value for OUTPUT:MODE:SP to be set to ON on config change?

**Comment by JamesKingWork** [comment]
I think they're aware that they need to be in OUTPUT:MODE ON now and didn't request automatic setting of the PV, so should be fine
