### ISSUE TITLE
Fix POLREF DAE tab

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6536]
As someone looking at the DAE spectra tab on POLREF I'd like them all to be able to respond, at the moment three of them are showing vague pink borders...

**Acceptance Criteria**
1. The spectra graphs all respond to their settings on POLREF

**Comment by KathrynBaker** [comment]
Screen snippet of the problem:

![image](https://user-images.githubusercontent.com/10552381/119416406-6ef7c480-bceb-11eb-85e2-6559b85af250.png)

**Comment by KathrynBaker** [comment]
Added labels and guessed the points at a half day, as I have no idea what might be upsetting the GUI in this way, so it will need some focussed time for finding it, but I anticipate it being a quick type fix once the source is found, and the review is easy

**Comment by KathrynBaker** [comment]
I also recalled during a discussion on Technical that the local PVs for the Mode (except on the one working graph) all seemed to be null, which may actually be the issue underlying this and the graphs borders are a symptom of a missing bit of information there instead

**Comment by JamesKingWork** [comment]
Seems to be ok with a different gui (see image below). I will advise them to restart the client

![image](https://user-images.githubusercontent.com/54139864/119638212-57fdc300-be0e-11eb-88c7-6d4a473fa463.png)
