### ISSUE TITLE
INTER: Testing time

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6538]
As an instrument scientist on INTER I would like to test IBEX.

## Acceptance Criteria
* Latest IBEX is on INTER
* INTER works to the scientists satisfaction

**Comment by ThomasLohnert** [comment]
Scientists have run some test experiments, my understanding is it went fine apart from some issues with the supermirrors - follow up ticket created here: https://github.com/ISISComputingGroup/IBEX/issues/6613

**Comment by rerpha** [comment]
Have updated https://github.com/ISISComputingGroup/IBEX/wiki/INTER-Instrument-Details#control-system
