### ISSUE TITLE
HIFI Cryomag: New GUI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#654]
As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the GUI to use our newer standards will provide greater longevity
#### Acceptance Criteria
1. Create Java interfaces/OPIs for each component (Gaussmeter, Scanner, Cryocooler, Magnet PSUs)
2. Create configuration files and synoptic settings as appropriate
#### Notes
1. This is reliant on stories #646, #647, #648, #649, #650, #651, #653 all being complete first

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 655.  Created by kvlb23 on 2015-02-06T13:30:45, last modified: 2015-02-06T13:30:45_

**Comment by KathrynBaker** [comment]
Closing this issue as the GUIs are all being undertaken within the other tickets (which was not the workflow and standard acceptance criteria when this ticket was written).
