### ISSUE TITLE
WISH: Discuss migration with instrument scientists

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6540]
As a WISH IS I would like to be able to use IBEX. As a developer I would like to know what needs be migrated for this and in what order. Particularly things that need to be discussed:

* Which configs are used and how often (and which devices)
* Which scripts are used and how often
* What features they find most useful in SECI
* What features they wish SECI had (without promising we will do these for the migration but will be useful to know)

## Acceptance Criteria
* The above is discussed with the scientist and documented at https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details
* Tickets are created for anything that does not already have a ticket

**Comment by davidkeymer** [comment]
Instrument scientists would like meeting at beginning of shutdown as they're too busy during cycle.  The did say to work through the devices in the SECI "base" configuration in the meantime.

**Comment by rerpha** [comment]
I am currently working on a WISH base component so will update this this as I progress.

**Comment by rerpha** [comment]
Ok, I believe I have a (mostly-complete) WISH base component + configuration with all groups and associated blocks created. I have set up the galils with the correct homing routines on NDXWISH. Only blocks I couldn't configure completely in the base config were the ones referencing the vacuum PLC and the ORC_cycle and ORC_STATUS blocks, which are currently pointing towards a disconnected SIMPLE record, we should leave these and do them as part of #6032 and #6034

**Comment by rerpha** [comment]
galil setup .bat script lives in the galil dir on the branch and is called `caputgalils.bat`.

**Comment by davidkeymer** [comment]
Meeting held on 07/07/2021.  All three ISs present, along with DK, JH, MS from ExptCtrls.  SE equipment discussed and rough priority list created:

1. Jaws
1. Oscillating Radial Collimator
1. McLennan rotation controller (with at least one Newport stage)

1. ITC (for OI Blue cryostat)
1. Eurotherm (for Orange cryostat and CCR)
1. 10T and 14T magnets (OI Teslatron with IPS)

1. Lakeshore 350 / 370

1. ISIS automatic needle valve controller (new in-house device - check with JN)

1. Alignment Flange (with neutron camera)

1. Triton dilution fridge
1. Mercury Heliox

1. PEARL pressure controller
1. Razorbill strain cell (small PSU)
1. Tektronix AFG 3021B Function Generator
1. Baratron gas cell (As used on IRIS)

See [WISH instrument details](WISH-Instrument-Details) for more information.

**Comment by davidkeymer** [comment]
More points from meeting:

* Discussed SECI (sub)configurations.  Decided ExptCtrls group would create an IBEX component when each device is tested, leaving ISs to assemble a configuration to their requirements.

* Open Genie scripts are very simple and should not pose any challenges.  PM will send a typical example in due course.  ISs happy to write their own as and when.

* ISs interested in script generator so have been invited to general discussion meeting.  Only concern was whether or not a "change temperature" command could be issued before ending a run (to save time for next run).  This is possible with an appropriate script definition.

* One request, which is common amongst all ISs apparently, is to be able to change the title of a run after it has ended.  This will need following up with the rest of the ExptCtrls group.

* ISs would also like to be able to use the WISH-SETUP machine to prepare experiments in advance.  @ChrisM-S is the person to ask of its status.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/6678 created for razorbill

**Comment by rerpha** [comment]
Going to stick this in review now as think we've got all the tickets written. We are still waiting on scripts so will create a ticket when we receive one to convert to Python.

**Comment by DominicOram** [comment]
* The [WISH details page](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details) hasn't been updated with any of this information. For example some of those devices are not listed on it and it still has placeholders for things like which configs/scripts we're going to convert and what date we'll be doing things
* There are no tickets for the automatic needle valve, alignment flange (what is this?) or the request for changing title
* I think a ticket for the scripting would be good, even if it's just a placeholder for now

**Comment by rerpha** [comment]
Will do the rework today

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/6694 created for converting scripts

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/6035 covers alignment flange, will add note to ticket and update wiki page for this

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/6695 created for needle valve - discussion ticket to try and figure out how we control it. Not adding to WISH instrument migration but will add to wiki page

**Comment by rerpha** [comment]
Have added more info to the instrument details page containing notes about the alignment flange/xyz stage, razorbill and configs. I don't want to document all of the configs as there are loads and they all revolve around the base config with other things added into it, so have added a note about creating components for each device then letting them create the configs from there.
