### ISSUE TITLE
NICOS: Flashing git window

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6542]
https://github.com/ISISComputingGroup/IBEX/issues/6296 is reoccurring on my windows 10 machine. The protocol version in NICOS matches with the protocol version defined in IBEX but the problem is persistent.

Acceptance criteria:
- Find the root cause of the issue and document it
- Fix it

**Comment by RaiBishal** [comment]
Starting scipt server manually(without running ibex server) `C:\Instrument\Apps\epics\ISIS\ScriptServer\start_nicos_daemon_cmd.bat` seems to work fine.

**Comment by JamesKingWork** [comment]
> Starting scipt server manually(without running ibex server) `C:\Instrument\Apps\epics\ISIS\ScriptServer\start_nicos_daemon_cmd.bat` seems to work fine.

Seems to still happen for me even when I run nicos like this. Requires the gui to be running as this creates new connections and errors which results in the flashing window.

**Comment by JamesKingWork** [comment]
The problem is that we expect a response to consist of 3 packages: a status, one which we throwaway as we think it is empty and the response. The packages we are receiving from the get banner command getbanner are null, "ok" and "". It looks like we have the protocol genuinely wrong.

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1301
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6552
