### ISSUE TITLE
DC Lab: Set up danfysik 9700

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6544]
As a power supply support person I would like to be able to talk to a Danfysik 9700.

## Acceptance Criteria
* SCIDEMO is set up to talk to the danfysik in the DC lab

**Comment by DominicOram** [comment]
DFKPS_01 is now talking to a Danfysik 9700. The major difference between the 9700 and 9100 is that the 9700 uses `115200` baud, whereas the 9100 uses `9600`. The baud is not exposed to the client so I set it via globals. I have updated docs in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Danfysik

**Comment by ChrisM-S** [comment]
Thank you @DominicOram, MOXA cables are now on order for the RIKEN Fe PSUs!
