### ISSUE TITLE
Move one emulator and IOC test to a support directory

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6555]
As a support person I would like to be able to specify in the IOC test framework where my emulator and test are. Currently they're in a central location but as of https://github.com/ISISComputingGroup/IBEX/issues/6131 we want to move them around. I would then like to put the emulator and tests into the support directory and be able to run "make ioctests" from this directory to run the test.

## Acceptance Criteria
* The emulator and test paths can be specified when running the IOC test framework 
* A simple IOC has the tests and emulator moved into it's support directory (preserving history)
* Running "make ioctests" in this directory runs the IOC Test
* Running "make ioctests" in EPICS_TOP recursively runs all tests (including this one), this is done as part of the IOC system tests jenkins build and the results are correctly uploaded to jenkins
* It is documented on https://github.com/ISISComputingGroup/IBEX/issues/6556 how to do this exactly for other IOCs (remember to preserve history)
* The wiki is changed to match this new structure
* ~The ioc generator script is corrected to match this~ Pulled into https://github.com/ISISComputingGroup/IBEX/issues/4659

**Comment by rerpha** [comment]
we should document that as a developer we should still run the command from support\ioctestframework\master as it is more verbose and you can more easily pass options to the command such as -f or -tm DEVSIM etc. 

on the build server or just running for sanity you could use `make ioctests`

**Comment by aaron-long** [comment]
Can you add the ability for the IoCTestFramework `run_tests.py` and the drivers associated tests to be called via a bat file in the driver directory. As discussed this improves the developer workflow for being able to see a line-by-line output of test results. We are a happy for now that the `make ioctests` does not give results until finished if this is an alternative option.

**Comment by DominicOram** [comment]
`bat` file added and documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Testing-Framework
