### ISSUE TITLE
MERLIN: slow dae performance

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6560]
MERLIN is suffering slow performance on begin/end etc. and microamps are updating slowly. I believe this is due to a lowdown in DAE transfer from the hardware, which is having a bad effect on IBEX. It is not clear where the problem is in the hardware.

## Acceptance criteria

- IBEX is better able to handle slow DAE performance

**Comment by FreddieAkeroyd** [comment]
From an analysis of the code all I can guess at the moment is that it is the DAE spectra reads that ultimately cause an issue. These run on loops and I think they may end up on one of the same timer queues as channel access, so can delay that. THe attached PR tries two things:
- adds a thread yield between spectra reads
- puts spectra reads onto a separate timer queue

**Comment by FreddieAkeroyd** [comment]
Maybe this fixes #4843 too?

**Comment by FreddieAkeroyd** [comment]
microamps and frames have jerky updates, commands like begin are not actioned straight away 

To deploy, new version of isisdae.dll is in `c:\Instrument\Apps\EPICS\support\isisdae\master\bin\windows-x64\new` 
So:
* Stop isisdae-ioc (no need to stop isisicp) 
* copy old isisdae.dll into an "old" subdirectory
* copy new isisdae.dll from "new" subdirectory to windows-x64
* restart isisdae-ioc

do microamps, frames, begin behave better?

**Comment by FreddieAkeroyd** [comment]
This didn't seem to help merlin, but was only able to try at end of cycle. Their DAE is also being removed for DAE3 so maybe call this done for now.

**Comment by DominicOram** [comment]
As I put on the PR can you document `ISISDAE_TIMER_PRIORITY` somewhere on the wiki?

**Comment by FreddieAkeroyd** [comment]
Added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-and-the-ICP for now, they were originally only there to allow easy changing during testing on MERLIN before fixing a value, but as that proved inconclusive their future may need deciding later
