### ISSUE TITLE
Fix Build VHDs job

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6566]
The Build VHDs job is failing and also causing the same problem listed in #6267 where it leaves SPARE70 unable to run system or IOC tests. The job has been disabled for the moment

## acceptance criteria

* Mechanism for creating VHDs is reviewed and fixed/changed where necessary
* consider moving vhd job to a different server to stop future vhd issues affecting system/ioc tests

**Comment by JamesKingWork** [comment]
Impeded waiting on a suitable machine to test on

**Comment by JamesKingWork** [comment]
NDHSPARE11 is now available and set up

**Comment by JamesKingWork** [comment]
VHD job successfully run on NDHSPARE11 https://epics-jenkins.isis.rl.ac.uk/job/Create_VHD/360/

**Comment by JamesKingWork** [comment]
The create_vhd job has run on NDHSPARE11 quite a few times (earlier unsuccessfully but more recently all have been successful). I haven't seen the job put the directory structure into a weird state, so I think this ticket is done now. I'm not sure if @FreddieAkeroyd  has any thoughts on that?

**Comment by rerpha** [comment]
Has been stable and has passed at least the last 5 builds. IOC tests etc haven't hung either by the looks of things.
