### ISSUE TITLE
GUI: Add blocks from "beam information" tab of Beam Status perspective

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6568]
As a user I would like to be able to right-click and add/log values shown in the "beam information" tab of the Beam Status perspective, in the same way as I can with device screens/OPIs. This would mean I could easily log or add to my config the beam current for TS1, for example. 
![beaminfo](https://user-images.githubusercontent.com/14823767/120790468-ebc84100-c52a-11eb-928d-7fccff37aebb.png)

### Acceptance criteria
- Context menu is shown when right clicking any of the fields in the beam information tab, and the same options as in the Process Variable sub-menu in the context menu for right-clicking a field in an OPI are shown. 

![contextmenuoptions](https://user-images.githubusercontent.com/14823767/120790344-bcb1cf80-c52a-11eb-8eda-2b657512ce85.png)

**Comment by rerpha** [comment]
Proposing as we have lots of migrations coming up and I think this will help with replacing the beam-logger VI and easily creating the required blocks.

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1331

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6660

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Views
