### ISSUE TITLE
Eurotherm: display millivolts somewhere

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6571]
As a supporter  I would like to know the millivolts returned from the eurotherm easily rather than having to work out the PV, this will quickly tell me whether i have an issue in calibration file and also help me identify which eurotherm is which sensor number.  Do we need an advanced screen on the eurotherm?

## acceptance criteria

* millivolts value easily accessible

**Comment by JackEAllen** [comment]
Locations of pull requests made as part of this issue:
- Update OPI: 
    - https://github.com/ISISComputingGroup/ibex_gui/pull/1333
- Update EPICS EUROTHRM record
    - https://github.com/ISISComputingGroup/EPICS-ioc/pull/627
