### ISSUE TITLE
GUI: Add a "refresh" button

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6574]
As a developer I would like a way to fix some GUI issues without killing scientist's scripts. Occasionally we see issues such as disconnected blocks (that really are connected) or an incorrect DAE status. These issues can normally be fixed by switching to the current instrument but this kills any running scripts and so can disrupt experiments.

## Acceptance Criteria
* There is a mechanism for refreshing the GUI, which remakes all the PV connections (like switching to the current instrument) but does not kill running scripts

## Notes
* The underlying GUI connection issues will be fixed in other tickets
* More widespread use of the script server in the future will fix this

**Comment by Adam-Szw** [comment]
IBEX GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1401
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7065

**Comment by rerpha** [comment]
Could you add a step in the release manual tests template? This would be fairly difficult to squish test but we should make sure we test it even if just every time we make a release.

**Comment by Adam-Szw** [comment]
Step added to manual system tests. [line 20 here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests)
