### ISSUE TITLE
Builds: Give error if builds haven't deployed to correct locations

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6575]
As a maintainer of IBEX, I want to know when my builds haven't been deployed to the correct locations for a while. This came to our attention when we realised the gui build hadn't deployed correctly since March (it is now June) so we were not testing the correct gui. This is a ticket to create a tool that scans the build areas for expected deploys and notifies us if the expectations aren't matched.

Acceptance criteria:

- [ ] Tool is created and running successfully
- [ ] Tool checks at least: genie_python, EPICS and gui

**Comment by FreddieAkeroyd** [comment]
See also #6570

**Comment by JamesKingWork** [comment]
I've added a tool in https://github.com/ISISComputingGroup/ibex_utils/pull/119 that runs on Jenkins to check for kits$ for if the client, epics and genie python most recent builds are more than 5 days old. See https://epics-jenkins.isis.rl.ac.uk/view/WallDisplay/job/Stale%20Builds%20Checker/ for it running. When merged we need to change the branch of this checker Jenkins job back to master.
