### ISSUE TITLE
IMAT: Recommission Motion

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6581]
As an instrument scientist on IMAT I would like my motion to be as reliable and accurate as possible. Currently on many axes the accuracy is not as good as expected. As such I would like them re-commissioned.

## Acceptance Criteria
* It is decided which axes are the most dire (JN is organising a meeting for this)
* ~This recomissioning is done (good opportunity to test the new Galil driver?)~ will do this in subsequent tickets

**Comment by DominicOram** [comment]
Meeting has been organised

**Comment by DominicOram** [comment]
My summary for the meeting (and in priority order):
•	Jaws have issues where they need power cycling to move and subsequently then homing, which is slow and unreliable. (see https://github.com/ISISComputingGroup/IBEX/issues/6631)
•	Large rotation stage does not work. This will be fixed by moving to the latest Beckhoff code (see https://github.com/ISISComputingGroup/IBEX/issues/6153) 
•	Ordering and naming of the sample stack items is not consistent (see https://github.com/ISISComputingGroup/IBEX/issues/6632) 
•	You need to manually toggle the encoder before homing on the lens adjustment (see https://github.com/ISISComputingGroup/IBEX/issues/6633)
•	Your large rotation needs slowing down and tomography rotation speeding up (see https://github.com/ISISComputingGroup/IBEX/issues/6634)
•	Adding better icons/pictures to the synoptic/OPI to make it more obvious which axis are which (see https://github.com/ISISComputingGroup/IBEX/issues/6635)

**Comment by rerpha** [comment]
Looks good, thanks
