### ISSUE TITLE
WISH: Teslatron not talking to devices

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6583]
WISH needed ISOBUS addresses for their Teslatron magnet to be updated after changing equipment. However afterwards, they ran into a problem where parts of the equipment stopped responding correctly, namely the magnet would scale the given field incorrectly (i.e. SP of 0.01T resulted in the magnet ramping to 1T).

Investigation revealed that settings for the PSU in the `TESLATRON.INI` had been cleared. It is not obvious how this happened. Issue was resolved by reverting to settings found in a backup file from 2016.

**Comment by KathrynBaker** [comment]
Marking as no release notes, as there aren't any that are applicable.
