### ISSUE TITLE
PEARL: Label network connections to make cable tracing easier

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6595]
As someone connecting up devices on PEARL, I would like the network tracing to be more obvious. There are a bunch of patch panels on the beamline and another set in the cabin (with a few on the outside of the cabin the other side of the cabin to the beamline patch panels). It was not clear from the two network cabinets in the PEARL cabin and the setup cabin what patch panels went where.

## Acceptance criteria:

- [ ] The labelling on the network cabinets and patch panels is clearer
- [ ] The share contains a document describing the PEARL network setup 
  - With the idea that the document on the share is located in a place where we can add descriptions of the setup for other instruments

**Comment by rerpha** [comment]
What I'm proposing is we use some sort of system, which we should document properly, to identify where the patches go through. For example:

C1 - C9 could refer to being patched through to Instrument cabin ports 1-9
S1 - S9 patched through to Setup cabin ports 1-9
I1 - I9 patched to ISIS Network ports 1-9 

We could do something like this for other instruments too in the future

**Comment by rerpha** [comment]
Some notes added to https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details#pearl-networking , still not finished as the network tester has died on us, will need to go back

**Comment by rerpha** [comment]
I'm going to call this done as all that is required left to do is me going and sticking 4 labels on some ports which i will do as soon as the IS responds, wiki should be updated with all information about the patch panels.

**Comment by JamesKingWork** [comment]
Have we confirmed that the ports in the rack are definitely the ones that go out to the patch panel?

**Comment by DominicOram** [comment]
I don't think we should merge this until it's done. If it's not yet labelled, it's not done. If that's waiting on the IS then put it as a task or impeded.

**Comment by rerpha** [comment]
cool, no we don't know for certain, probs need to go down with two laptops, so will do that before sticking this back in review

**Comment by rerpha** [comment]
All tested, 1-5 come through to the patch panel, have sent email off to IS and updated wiki
