### ISSUE TITLE
Update stream device to 2.8.20

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6596]
As a developer I would like to use the updated stream device as it prints non-ascii characters better in debugging output and also includes changes to reduce log file output size

## Acceptance criteria

non printable characters do not have   `\033[7m` added when output printed in log file 
less logging volume on disconnected devices

Note: this version changes STREAM_PROTOCOL_PATH separator to be `;` on windows, this is to avoid issues with c: etc. We should check our STREAM_PROTOCOL_PATH  to see if this has any affect, in particular do we ever specify more than one directory to search for protocol files

**Comment by ThomasLohnert** [comment]
Is this just a review? @FreddieAkeroyd

**Comment by FreddieAkeroyd** [comment]
Yes, just a review. @rerpha may have already looked at this during the CCD investigation as the stream debug output he posted to teams looked to be missing `\033[7m` characters

**Comment by FreddieAkeroyd** [comment]
@DominicOram do we still need your original `previousMismatch` code, or does the work you did at the code camp and  which is brought in by this PR replace this? See https://github.com/ISISComputingGroup/EPICS-StreamDevice/compare/vendor...update_to_2_8_19 for our local changes to upstream 2.8.20 that will remain after PR is merged

**Comment by DominicOram** [comment]
I think leave it in for now, we need a new ticket for setting up the deadband for the logging

**Comment by FreddieAkeroyd** [comment]
Original system is now re-instated
