### ISSUE TITLE
PEARL: set up PACE 5000 Pressure Controller

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6598]
PEARL needed a PACE 5000 setting up yesterday (16/06/2021) which was not talking to its SECI VI. The cables needed tracing but PEARL has very poor socket labelling and ethernet passthrough boxes which make things a bit confusing. 

I have created this ticket as it took 3 of us to finally get it working so used a few points in the sprint (and most of a morning!) 

Following on from this #6595 has been created to go and label the patch boxes and so on to make things like this clearer for next time and also for when we migrate them to IBEX.

**Comment by rerpha** [comment]
updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Pressure-Monitors 
and created https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PACE5000

**Comment by rerpha** [comment]
to review: check that documentation makes sense. Device was talking correctly and we've received no support calls since so must be still working.

**Comment by davidkeymer** [comment]
Both wiki pages checked.
Also the [original ticket](https://github.com/ISISComputingGroup/IBEX/issues/6044) that was created as part of the migration list, and the [PEARL wiki page](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details).
