### ISSUE TITLE
CHIPIR: Review and clean up old EPICS IOCs

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6600]
As a developer I would like to be sure what IOCs we currently have for CHIPIR, modernise them if they are useful and remove them if they are not. In the ISIS directory we currently have:
* CHIPIR_Collimator
* CHIPIR_Filter_set
* Chipir_LV_FP
* Chipir_XYZ

## Acceptance Criteria
* The above IOCs are evaluated and either modernised and documented if useful or removed if not

**Comment by DominicOram** [comment]
All the IOCs are LVDCOM IOCs that are talking to the SECI VIs for CHIPIR. Generally will not be useful in moving CHIPIR to IBEX. The devices can be properly integrated in https://github.com/ISISComputingGroup/IBEX/issues/6601. I'll remove these from the build tree and archive the repos.

**Comment by rerpha** [comment]
RN: https://github.com/ISISComputingGroup/IBEX/pull/6642
