### ISSUE TITLE
CHIPIR: Create basic config and meet to discuss next steps

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6601]
As an IS on CHIPIR I would like to be able to use the basic devices that I have on my beamline (mostly motion control). I would then like to have a discussion about how to go forward with IBEX.

## Acceptance Criteria
- [x] A test machine is created for CHIPIR to have a play around with IBEX
- [x]  A base CHIPIR config is created with simulated motion control elements
- [x] A meeting is had with CHIPIR to discuss what they would like next from IBEX

time inm planning  01:26 23/5/24

**Comment by rerpha** [comment]
current branch is http://control-svcs/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/NDXCHIPIR_migration

**Comment by rerpha** [comment]
Have handed the machine over to scientists, next step is get feedback from them/show them around and then start doing the real migration part of #6187

**Comment by rerpha** [comment]
To review check out `NDXCHIPIR_migration` in your config area and run it up, see the base config, should contain most of what's needed running in devsim. Plan is to merge this branch into `NDXCHIPIR` and remvoe all the devsim/recsim simlevels

**Comment by Tom-Willemsen** [comment]
Seems like a sensible enough starting point for further discussion with scientists
