### ISSUE TITLE
Reflectometry: Install latest version on POLREF and sanitise snags list

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6606]
As a developer working on reflectometry I would like to make sure I am working on the tickets that are most impactful. Currently the reflectometry snags list contains some items which are done, some which are probably done but not confirmed done due to the rollback of IBEX on POLREF etc.

## Acceptance Criteria
* The latest IBEX version is re-instated on POLREF with https://github.com/ISISComputingGroup/IBEX/issues/6472 corrected
* Snag list items presumed fixed but not yet tested are tested on POLREF. Tidy up snag list as appropriate
* The rest of the snags list is looked at with the scientists to make sure that everything is on there and we know what priority to do it in

**Comment by ThomasLohnert** [comment]
This is done. Closing
