### ISSUE TITLE
Instrument Scripts: Discuss the future of the scans library

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6607]
As an IS using the scans library I want to be sure that it works and is well maintained. As a developer I want to be confident in maintaining it and ensuring it doesn't break workflows on any instruments.

## Acceptance Criteria
* A meeting is had with reflectometry and SANS groups to discuss how we proceed with the scans library
* Notes from the meeting are written up and agreed upon

## Notes
* Release procedure for the library has already been discussed in https://github.com/ISISComputingGroup/IBEX/issues/5858#issuecomment-726889278 and sent around to the scientists

**Comment by ThomasLohnert** [comment]
Superseded by https://github.com/ISISComputingGroup/IBEX/issues/7548 & subtickets
