### ISSUE TITLE
IBEX: Confirm before deleting Configuration and Components

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6627]
As a user, I would like to see delete on confirm dialogue before a component/configuration is deleted. Currently, it just deletes the component/config without confirming with the user.

**Acceptance criteria:**

- Delete confirmation dialog is displayed before deleting a component/configuration
- Squish test is added

**Comment by Adam-Szw** [comment]
Code PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1338
Release Notes PR: https://github.com/ISISComputingGroup/IBEX/pull/6706

**Comment by Adam-Szw** [comment]
Impeded because we are waiting for floating Squish licence to create tests for this ticket

**Comment by Adam-Szw** [comment]
Tests added (PR above or here https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/113)
