### ISSUE TITLE
IMAT: Make sample stack OPI and icon more realistic

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6635]
As an IS on IMAT I would like the sample stack synoptic icon and OPI to look more like my actual sample stack to avoid confusion.

## Acceptance Criteria
* The synoptic icon for the sample stack looks more realistic
* There is a diagram of the sample stack on the OPI so that it is clear what axis is moving what

**Comment by Adam-Szw** [comment]
Code PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1341
Release Notes PR: https://github.com/ISISComputingGroup/IBEX/pull/6713
