### ISSUE TITLE
Beckhoff: Ensure we can communicate with ESS shared codebase

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6637]
As an instrument scientist I would like to be able to communicate with a Beckhoff.

To do this OPC tags need to be added to the beckhoff code so that appropriate tags appear in the tpy file. This was done in https://bitbucket.org/europeanspallationsource/tc_mca_std_lib/branch/MBP-113-add_OPC_attributes but that is now too far out of date and so has been picked up again in https://bitbucket.org/europeanspallationsource/tc_mca_std_lib/branch/MBP-113_OpcUaAttributes.

## Acceptance Criteria
* There is appropriate documentation on the wiki on how to add OPC comments to the code so that they propagate to the IOC
* The above branch has these tags correctly (talk to @Simon-Cooper about getting them on and merged)
* The above branch is run in the Beckhoff system tests

**Comment by DominicOram** [comment]
Updated some of the documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff

**Comment by rerpha** [comment]
tried to set up the test runner on my machine but XAE won't download, trying to register just 404s... will try again later.

**Comment by rerpha** [comment]
Currently the inputs and outputs of each axis are not linked to the PLC driver automatically using the mappings.xml file, despite build.bat outputting text to say it has mapped them

**Comment by rerpha** [comment]
TwincatAutomationTools needed some work too, I have some changes that need to be pushed

**Comment by rerpha** [comment]
Have pushed the changes, mappings are now working correctly and build.bat does not open an IDE.
