### ISSUE TITLE
Create a central Graylog server

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6645]
May be linked to https://github.com/ISISComputingGroup/IBEX/issues/5818 as we'll need to find a server for both 

As a developer I would like a central Graylog server to be set up so I can push to it from various sources on multiple instruments. This could be done following the guide on the [Graylog docs](https://docs.graylog.org/en/4.0/pages/installation/docker.html#persisting-data) using Docker or we could run it on the machine itself.

### Acceptance criteria
- Graylog server is set up
- Changes made in #5447 are modified to push to a central server rather than a local one
- Changes are documented in genie python release notes and on the dev wiki detailing deployment/installation of graylog server

**Comment by rerpha** [comment]
doing this next friday I think, going to just run one on a data streaming server

**Comment by rerpha** [comment]
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Graylog updated with details on graylog server
- Genie python: https://github.com/ISISComputingGroup/genie_python/pull/350 
- Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6756

**Comment by rerpha** [comment]
To test this

log into madara's graylog web interface 
open up a genie python window and type some commands 
confirm they come up when searching for new logs

**Comment by rerpha** [comment]
note that this is not really a permanent solution - to do that we'd need to update screamingudder/ansible-kafka-centos but I don't have the time to do this. We aren't really relying on graylog that heavily even if we log from genie python so that's why i've crossed out a system test in this ticket along with updating ansible.

**Comment by rerpha** [comment]
permanent solution is https://github.com/ISISComputingGroup/IBEX/issues/6760

**Comment by JamesKingWork** [comment]
Link to permanent solution https://github.com/ISISComputingGroup/IBEX/issues/6760
