### ISSUE TITLE
IRIS IOC SDTEST_01 is Invalid - Unable to get Read Values

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6647]
As a instrument scientists, I want to...

- Get read values from the SDTEST_1 IOC.

IRIS are currently experiencing problems with the SDTEST_1 IOC where they are unable to get read values. 
The heaters are connected and working as usual.

This should be looked into and if needed, it may be worth reaching out to IRIS for more details to get things back up and running

**Comment by FreddieAkeroyd** [comment]
The error is "No reply within 1000 ms" and seems to have started happening at 11am on 8th July, everything looks fine with the moxa connection so I suspect the hardware at the other end is the issue. As all 4 devices are failing, maybe they have all been switched off or are on a common power supply that has failed?

**Comment by DominicOram** [comment]
Turned out the device was switched off, I turned it back on. Not sure if there's much to learn from this.
