### ISSUE TITLE
start_ibex_server: warn if started as admin

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6650]
As a developer i would like to be warned if i accidentally start the server from an admin prompt

## Acceptamce |Criteria

start_ibex_server aborts if run as admin

**Comment by FreddieAkeroyd** [comment]
You may be able to use the same approach as in https://github.com/ISISNeutronMuon/ISISICP/blob/master/labview%20modules/DAE/register_programs.cmd there it uses
```
net session >nul 2>&1
if not %errorlevel% == 0 (
    echo Administrative permissions required, use   inst_admin_account  or 03 fed id account
    goto ERROR
)
```
So you just need to invert the logic to exit if admin rather than exit if not admin

**Comment by JamesKingWork** [comment]
Is there a PR for this? Not quite sure how to start the review

**Comment by rerpha** [comment]
> Is there a PR for this? Not quite sure how to start the review

found it https://github.com/ISISComputingGroup/EPICS/pull/264/files
