### ISSUE TITLE
Release: Create a Release [w/c 26/7/2021]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6651]
As someone invested in the IBEX project I want to create a release so that we have a tested system that can be deployed to systems as appropriate.

As this is a release during the long shutdown there are no deployments to consider, or demos to provide as even more will have changed by the time the instruments are in use again. However, distributing release notes would be beneficial as would receiving feedback on them so that we can improve them in the future.

Acceptance Criteria:

- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)
 - [ ] Distribute release notes via email [Instrument scientist release email](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Updating-Instrument-Machines#a-new-release)

**Comment by KathrynBaker** [comment]
Assigning 13 points as that is the typical value for a release for the last few releases

**Comment by Adam-Szw** [comment]
Updates will be emailed to Instrument Scientists after review just in case

**Comment by RaiBishal** [comment]
> sorry, dont have time to do a proper review, but is the nicos flashing window issue still an issue for this release?

flashing windows only occurs for brief amount of time when we run client initially(however long it takes for client to connect nicos I believe). After that it seems to be fine.

**Comment by Adam-Szw** [comment]
It is actually still flashing for me

**Comment by RaiBishal** [comment]
seems weird. NDXSCIDEMO does not seem to have this problem.

**Comment by rerpha** [comment]
hmm. just checked the two files to compare and they are the same, so i'm not sure whats causing it

**Comment by RaiBishal** [comment]
> hmm. just checked the two files to compare and they are the same, so i'm not sure whats causing it

Can you actually queue a script in nicos server in your dev machine? If I remember correctly, #6296 was happening because of version mismatch and not being able to establish connection with script server from GUI.

**Comment by rerpha** [comment]
nope, just says in script server window 

"The connection to the script server failed"

**Comment by rerpha** [comment]
flashing every 10 seconds

```
[Enter `^Ec?' for help]
[-- MOTD -- console for NICOSDAEMON]
[17:46:56] Daemon    : [new handler] connection from []
[17:47:06] Daemon    : [new handler] connection from []
[17:47:16] Daemon    : [new handler] connection from []
```

**Comment by JamesKingWork** [comment]
I'm happy that the steps have all been done and it looks like it's running correctly on scidemo, we just need to send the email out to the scientists now, but I won't let that hold up the ticket
