### ISSUE TITLE
Script Generator: Improve readability of generated scripts

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6658]
As a user of the script generator, I would like to be able to easily understand and edit my produced scripts. Currently, the produced scripts are not as readable as others produced by other script generators.

## Acceptance criteria:

- [ ] Investigation into other script generators, discussion with scientists and understanding of how we produce scripts has produced a consensus as to how we want scripts to look after generation
- [ ] New look scripts are generated by the script generator

## Notes:

- It may be worth coming up with some ideas of what we are capable of and what we think scientists may want, and then presenting it to them for discussion

**Comment by ThomasLohnert** [comment]
Some thoughts from Muons on what would be useful:
- Ensure parameters in function call are in same order as in script generator table
- Generate comment by `runscript` calls that this is the actually executing code
- Generate comment on each run instruction to link to each action ID (future: action title?)

**Comment by isaachilly** [comment]
PRs:

[Code](https://github.com/ISISComputingGroup/ibex_gui/pull/1616)
[Release notes](https://github.com/ISISComputingGroup/IBEX/pull/8040)
