### ISSUE TITLE
Script Generator: Current script label not appearing

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6662]
As a user of the script generator, I would like to see the current script I am editing. Currently, there is a bug causing it not to be displayed.

## Acceptance criteria:

- [ ] Current script is displayed

**Comment by Adam-Szw** [comment]
What are the steps to reproduce? Seems to show up fine for me.
![Untitled](https://user-images.githubusercontent.com/60976405/128680309-cf881f7f-480a-4401-86c9-f4ed30f815b1.png)

**Comment by JamesKingWork** [comment]
It seems to show up for me as well now, there were no real steps to create the bug that I did in the first place as far as I can remember it just didn't show up and I couldn't seem to make it show up at the time. I wonder if some later work has fixed the issue or something went wrong in my eclipse (I have started a new workspace since).

**Comment by Adam-Szw** [comment]
Maybe someone fixed it while working on a different ticket. What should we do with this ticket now?
