### ISSUE TITLE
Script Generator: Built script generator is broken

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6663]
When I build and start the script generator this is what I see:

![image](https://user-images.githubusercontent.com/54139864/126642035-0424a8ea-d28e-4e2c-9c69-433e9a2fbe92.png)

This also happens for builds pulled from the build server, but not those run from eclipse.

**Comment by RaiBishal** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1332
RN: https://github.com/ISISComputingGroup/IBEX/pull/6668
