### ISSUE TITLE
Genie_python: improve logging

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6666]
Follows on from https://github.com/ISISComputingGroup/IBEX/issues/5447

As a developer I would like genie python to log more effectively. Currently if an exception is raised because a block exists it is put into syslog level 7 (debug) - it should be at least a warning if not an error. We now use the `logging` library in python so we should make use of it! Part of this may be using it globally - see [here](https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial)

### Acceptance criteria
- Logging is improved in genie python: 
  - Exceptions give errors rather than warnings
  - Graylog + file writing functionality is left intact 
  - Currently being in simulation mode does not log anything. We should fix this and add a filter to the log record to say whether or not genie python is in simulation mode

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/347
