### ISSUE TITLE
Git Issue Templates

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6667]
Issue raised by: developer

### Who
- IBEX

### What?
Add a few GitHub issue templates to the project for a trail period.

### Where?
- `.github/ISSUE_TEMPLATE/`

### Why
To create a formalised structure for creating issues containing the necessarily detail for a developer to begin working on a given issue without first needing to plan how to tackle the issue.

Issue templates will be used for a trial period to determine what does and doesn't work in the templates as part of the IBEX development workflow.

### Acceptance Criteria
- Issue templates are present in `.github/ISSUE_TEMPLATE/`
- Issue templates contain no grammatical errors

**Comment by Tom-Willemsen** [comment]
We have some templates now.
