### ISSUE TITLE
WISH: IOC & OPI for Razorbill strain cell RP100 (small PSU) 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6678]
As a WISH instrument scientist I would like to be able to control my Razorbill strain cell from IBEX. 

Currently a VI exists for this in `C:\LabVIEW Modules\Drivers\Razorbill RP100 Strain Cell PSU`, it looks like this: 

![rp100fp](https://user-images.githubusercontent.com/14823767/127155661-85c21a38-9642-4eb6-864d-4ce1d852defd.png)

### Acceptance criteria
- IOC, emulator and system tests exist for the Razorbill strain cell
- OPI is created and sent off to scientists to make sure it meets their needs

Notes: 
- Razorbill is controlled via serial, COM3 on WISH
- Manual exists for the Razorbill RP100 at `\shares\ISIS_Experiment_Controls\Manuals\Razorbill RP100`

**Comment by davidkeymer** [comment]
Pull Requests:

[IOC]()
[Support]()
[GUI]()

[Wiki Page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Razorbill-RP100-Strain-Cell-PSU)

**Comment by davidkeymer** [comment]
Unit now available in the office for testing and/or reviewing.

**Comment by davidkeymer** [comment]
Closing issue as marked as review complete.
