### ISSUE TITLE
Blockserver: Only affected IOCs are restarted when macros/pvsets changed

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#668]
As a user, when modifying my current config (e.g. changing a COM port), I would like only the affected IOCs to be restarted, not the whole instrument.

== Acceptance Criteria ==
1. The only IOCs that are restarted on a configuration modification are those that have been modified.

== Notes ==
1. See also ticket:695
1. This will require that the !BlockServer compare IOC settings for newly loaded (or modified) configurations to the active one.
1. There should be a setting to override this behaviour and restart all IOCs (e.g. a checkbox to "Re-start everything")
1. If the user switches from one configuration to another, then all IOCs will have to be re-started (that is beyond the scope of this ticket and is the subject of another ticket).

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 669.  Created by ffv81422 on 2015-02-18T17:20:15, last modified: 2015-08-20T16:23:28_

**Comment by kjwoodsISIS** [comment]
This ticket is no longer relevant.  No further need for this ticket to remain open.

**Comment by DominicOram** [comment]
I actually think this is still a valid ticket. We are still very heavy handed with what we do when the blockerver restarts. This ticket would greatly improve the time taken to switch configs.

**Comment by kjwoodsISIS** [comment]
Superseded by ticket #3051.
