### ISSUE TITLE
EMU: Investigate control VIs for RF Kit

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6685]
As an EMU scientist, I would like to be able to control my RF Kit.

## Acceptance criteria

- [ ] Control VIs are investigated and behaviour understood
- [ ] Behaviour to be implemented in IBEX agreed with muon scientists
- [ ] Either
  - Behaviour implemented in IBEX
  - Tickets created and prioritised to implement behaviour in IBEX

## Notes:

- This relies on:
  - https://github.com/ISISComputingGroup/IBEX/issues/6081
  - https://github.com/ISISComputingGroup/IBEX/issues/6080
  - https://github.com/ISISComputingGroup/IBEX/issues/5154
  - https://github.com/ISISComputingGroup/IBEX/issues/6079

**Comment by KathrynBaker** [comment]
Closing this has been superseded
