### ISSUE TITLE
GUI: Script Generator should notify user that they don't have Notepad++ installed or possibly allow use of normal Notepad

### ISSUE THREAD

**Issue by Adam-Szw** [ISISComputingGroup/IBEX#6692]
### Description
As a User I would like to know why Script Generator doesn't allow me to open my scripts and how to remedy this. Currently after launching Script Generator on a clean machine (for example virtual machine) which doesn't have notepad++ installed and trying to save a script and open it, an error shows up saying "Failed to find notepad to launch".

This could be confusing to a user since they do have normal notepad installed, just not notepad++. We could improve this by explaining that Notepad++ is needed and how to obtain it OR possibly allow usage of normal notepad with some recommendation of using Notepad++.

### How to reproduce:
- Open Script Generator on a machine without Notepad++ (This was discovered on clean VM)
- Load script definition and add some actions
- Click save as
- Click yes to open in notepad

### Acceptance Criteria:
- Error message has been amended to give clearer information to user
- Optionally: Use normal Notepad instead and inform user they could/should obtain Notepad++
- There are tests for this

**Comment by Adam-Szw** [comment]
This was discovered during manual tests for release 8.0.0

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1336

**Comment by JamesKingWork** [comment]
A nice improvement!
