### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by Adam-Szw** [ISISComputingGroup/IBEX#6693]
As a developer I would like to be sure that none of the IBEX dependencies get too out of date. Following the latest release we  [#6651](https://github.com/ISISComputingGroup/IBEX/issues/6651) should update our dependencies. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates

### Acceptance Criteria
- [ ] Dependencies are updated
- [ ] New dependencies are listed in the upcoming release notes
- [ ] IBEX is roughly tested to confirm it still works

**Comment by GRyall** [comment]
see #8468 for a completed ticket for this and #8597 for a current ticket.
