### ISSUE TITLE
WISH: discussion with JN about automatic needle valve 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6695]
As a WISH (and possibly other instruments) instrument scientist I would like to control an automatic needle valve. This is a new in-house designed device which we aren't sure how to control yet so a discussion with JN needs to happen before we try and write an IOC for it. 

### Acceptance criteria
- Discussion is had to find out more information on the new device
- Device and how to control it is documented on the dev wiki 
- Ticket is created for the IOC and OPI to control it

**Comment by KathrynBaker** [comment]
If this is the latest iteration then the valve is controlled via a Eurotherm and requires nothing special, if we do need to control the extended aspects that was the trigger for #4240, as those controls are outside of the existing memory space.
However, there is a project for a cryostat controller, which will be driven via a Beckhoff system, that is not yet at a stage for us to do anything with it, and the interactions should stay as standard Beckhoff for us (it's what I'm pushing for), which would mean limited interactions - this is also longer term.

**Comment by DominicOram** [comment]
Consider whether we need SECI support for this too if they need to switch back and forth

**Comment by KathrynBaker** [comment]
When the automatic needle valve came up in a discussion for another instrument, I asked after this one.

This is the Eurotherm version with extra commands in Modbus. WISH will want access to some of those extra settings.

The commands available will be:
Switch between Auto and Manual Mode
In Auto mode, a temperature can be set
In Manual mode, a flow can be set

JN will confirm with me the values that can be read.

As such. #4240 will handle the IOC, and has been proposed for sprint 2021_09_23. #6777 has been created to handle the interface for this work.

**Comment by rerpha** [comment]
Great, thanks, have updated https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details linking to this ticket and the others created.
