### ISSUE TITLE
NICOS: Still flashing on some setups

### ISSUE THREAD

**Issue by Adam-Szw** [ISISComputingGroup/IBEX#6696]
[NICOSDAEMON-20210803.log](https://github.com/ISISComputingGroup/IBEX/files/6922863/NICOSDAEMON-20210803.log)
As an Ibex user I would like NICOS to work on my setup.

### Description
On my machine (NDW1798) NICOS window is still flashing and not logging in properly. It is however working on SCIDEMO.
At one point while testing this behaviour (for example by running multiple IBEX Clients, one from Eclipse and another as deployed client) it was able to log-in but typically it fails.

Logs are included from NDW1798 to help with this. 
This was discovered in 8.0.0 release.

### To reproduce
- On NDW1798 (or another machine for which this problem occurs)
- Run IBEX Server and IBEX Client
- You should be able to see NICOS window flashing and logs showing abnormal behaviour
- Cannot add script to queue in Script Server

### Acceptance Criteria
- NICOS works correctly
- After bug is understood, create a test that checks for this

**Comment by Adam-Szw** [comment]
I believe @rerpha also has this problem?

**Comment by rerpha** [comment]
Yes I am, using the maven and eclipse built client. Error message is the same as in #6296

**Comment by rerpha** [comment]
I think bring this into the sprint, its a very bad bug that could cause users to actually have seizures

**Comment by JamesKingWork** [comment]
Is this due to updating nicos as a dependency? For reference, the problem I found last time is described here https://github.com/ISISComputingGroup/IBEX/issues/6542#issuecomment-852961275 and the fix is in that ticket. Specifically changes to https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/GetBanner.java#L53 may be required

**Comment by Adam-Szw** [comment]
PR for code: https://github.com/ISISComputingGroup/ibex_gui/pull/1342
Working on adding tests but I would appreciate if someone else checked if this also works on their setup since
this issue is not experienced by everyone somehow

**Comment by JamesKingWork** [comment]
To anyone who picks this up as a review, this reverses changes I made to fix the issue before. Not quite sure why it causes trouble on some machines and not others, we may want to investigate further as to why when reviewing.

**Comment by Adam-Szw** [comment]
After talking with @JamesKingWork we decided that Squish tests will be needed for this and that we need more tests for NICOS in general. I cannot create squish tests (no licence) so ticket: [#6725](https://github.com/ISISComputingGroup/IBEX/issues/6725) will have to implement tests fo this.

**Comment by Adam-Szw** [comment]
Release notes PR: https://github.com/ISISComputingGroup/IBEX/pull/6726
