### ISSUE TITLE
Script Generator: Validating individual global parameters

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6703]
As a script definition writer I would like to be able to provide validation for global parameters individually and for that validation to be displayed on the global parameter. Currently, we can use global parameters in the validation of actions and we check if global parameters can be cast to a given type. We could adapt the casting to give a nice message to the user or alternatively allow the script definition to define a specific validation function.

## Acceptance criteria:

- [ ] In a script definition a scientist can define a validation function
- [ ] When the validation function returns invalid the box for the global parameter goes red and a tooltip gives a useful message defined by the validation function

## Notes:

- We may just need to change the `globalParamsValid` function in script_definition_loader.py to print a nicer message. For example, we could define a ValidationError which a script definition can raise in the validator with a string to provide the error message

**Comment by JamesKingWork** [comment]
PRs:

- https://github.com/ISISComputingGroup/ScriptDefinitions/pull/7
- https://github.com/ISISComputingGroup/ibex_gui/pull/1337
- https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/107

Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6705

**Comment by Adam-Szw** [comment]
Looks good to me and I think test and documentation presents this nicely. I couldn't run the test though (no Squish licence) so I will need someone to help with this. Didn't merge yet. I also don't have permission to merge into genie_python. Just a small suggestion - maybe Minor instead of Patch would be more fitting since we introduce new functionality?

**Comment by JamesKingWork** [comment]
You're right, I have changed the release notes to Minor instead of Patch. It's odd that you can't merge into genie_python as you are part of the group that has write access to that repo, we should fix that but in the meantime, I can just merge it when you merge the rest (as you've approved it already). I am not sure who has licenses to run squish, @DominicOram @rerpha @RaiBishal @ThomasLohnert maybe?

**Comment by rerpha** [comment]
Will just run it now.

**Comment by rerpha** [comment]
tests all pass for me!

**Comment by Adam-Szw** [comment]
Everything is approved but I don't have permissions to merge (could only merge into ScriptDefinitions) @JamesKingWork

**Comment by rerpha** [comment]
weird, you should be in icp-write so should have permissions.. will merge for you
