### ISSUE TITLE
SANS2D: Deploy latest version of IBEX

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6708]
### Description
After quick catch with SANS2D team, their concern was them not being familiar enough with IBEX. They would like some time to play around in IBEX so that they can familiarise themselves with IBEX. As the latest version of IBEX contains breaking changes, we should deploy it to SANS2D.

### Acceptance criteria:
- [x] Latest version of IBEX is deployed to SANS2D

**Comment by rerpha** [comment]
Could you update the SANS2D entry in https://github.com/ISISComputingGroup/IBEX/wiki pls?
