### ISSUE TITLE
EPICS Terminal does not run run_tests.bat if another ET is open 

### ISSUE THREAD

**Issue by daryakoskeroglu** [ISISComputingGroup/IBEX#6714]
As a developer, I am using run_tests.bat to run tests I created in test_genie_python_dae. Occasionally, the terminal stops at line:
`"ERROR: IPython does not exist, auto complete not installed"`

When I tried to open another EPICS Terminal and run the tests while the other terminal tab is open, the new terminal stuck too.

### Acceptance Criteria
    1. EPICS Terminal runs the tests without getting stuck

**Comment by Tom-Willemsen** [comment]
Not reproducible at the moment.
