### ISSUE TITLE
Background plots continue to be unreliable and poorly presented [Timebox: 2.5 days]

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6719]
As an EMU user/scientist, I would like my background plots to be more reliable and better presented. This ticket is to sit down and work out what is unreliable about the plots and what is poorly presented and fix those issues.

As an INTER scientist, I would like my background plots to be more reliable. INTER report "not refreshing, ill-sized and disappearing plot windows".

## Acceptance criteria:

- [ ] Symptoms and causes of unreliability and poor presentation identified (this should be in discussion with muon and reflectometry instrument scientists)
- [ ] Identified causes are corrected

## Notes

- Dates and offsets on axes may be a problem
- From the IS: "Graphs of log values such as temperature should not have an offset subtracted so the numbers on the Y axis are near zero, with the offset hidden behind the legend. This matplotlib feature can be turned off: https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.ticklabel_format.html with useOffset=False"

**Comment by KathrynBaker** [comment]
+1 from INTER

**Comment by Tom-Willemsen** [comment]
+1 again from INTER (see footprints message dated 28/06/2022)

**Comment by JackEAllen** [comment]
+1 from POLREF also

**Comment by Tom-Willemsen** [comment]
Impeded until we can test on a reflectometer; I have emailed relevant scientists to request a testing time but have not yet had replies. I want to test that the concept of the changes works on a reflectometer before spending any more time on them. The instability issues are somewhat tricky to reproduce on dev machines.

**Comment by Tom-Willemsen** [comment]
Testing time on INTER on Mon 8th August.

Detectors will be off, but I am hoping to be able to use real motors for the scans and set up some simple fake monitor counts to scan against (e.g. just point the monitor blocks at some user pvs and use genie_python to set them as a function of motor pos). Then, with scientists, run a representative scans workflow and try to see whether the new approach is any better than the current approach.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1462
- https://github.com/ISISComputingGroup/genie_python/pull/366
- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/97
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Matplotlib
