### ISSUE TITLE
EMU: ZF system issues [Timebox: 0.5 days]

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6722]
EMU ZF system developed a problem during the April Cycle where errors were momentarily reported, automatically cleared, with the system continuing to run. @FreddieAkeroyd investigated and discovered that currents appear to be set to an accuracy that exceeds to capability of the Kepco supplies. The same problem has been found on MuSR during testing. Why this problem didn't show up during 2020 on EMU is not understood.

**This ticket is not to fix the issues but to record information and understand the problem**.

## Acceptance criteria:

- [ ] Show and describe how to reliably reproduce these issues for when we come around to test and fix them during testing on Windows 10
- [ ] Record information on the issue that will be helpful when implementing later fix

**Comment by JamesKingWork** [comment]
EMU scientists will set up for us to test

**Comment by FreddieAkeroyd** [comment]
The accuracy issue is mentioned in #6515

When setting a current > 25% of max, the requested ibex accuracy is not achievable. Usually one of the three axes is running at > 25%, so some errors would be expected. However all axes showed regular errors, whereas previously very few errors were reported.   

Part of the analysis should also look at the labview Vi and see if it actually checked the setpoint readback

**Comment by JamesKingWork** [comment]
The ZF system is up and ready for testing

**Comment by JamesKingWork** [comment]
With the zero field controller set up as normal and in auto-feedback mode we get a lot of the following in the log `[2021-08-20 15:08:13] sevr=major zero_field.st: Power supply writes failed to get within tolerance. Setpoints = (X=-0.863557, Y=1.476879, Z=0.764690), setpoint readbacks = (X=-0.863530, Y=1.477460, Z=0.764660). Diffs = (dX=-0.000027, dY=-0.000581, dZ=0.000030). <<TRUNCATED>>`. I have had a quick look at the VI and it is relatively complex so have not been able to discern if the setpoint readback is checked.

**Comment by FreddieAkeroyd** [comment]
For info, Y is very close to the accuracy limit in this particular case.  >25% of range is >1.5A and there only an accuracy of .0012 is achievable rather than .0002

**Comment by JamesKingWork** [comment]
The tolerance of 0.0002 came from testing and commissioning on real hardware here https://github.com/ISISComputingGroup/IBEX/issues/4840

**Comment by FreddieAkeroyd** [comment]
removed `ExtraInput=Ignore` doesn't seem to have broken anything, but not produced any insights either

**Comment by JamesKingWork** [comment]
Sent an email to instrument scientists asking:
"The checking of the setpoint readback happens near the end with the question “New currents within limits?”. We have done some investigation into the VI and we thought that the setpoint readback was being checked with a tolerance of 0.01, but it actually checks the setpoint against itself not the readback. As far as we can tell this same check isn’t done in the LabVIEW. Was this a requirement that was meant to be implemented in the LabVIEW or was it a new one for the IBEX IOC?

The tolerance of 0.0002 was defined during the testing and commissioning of the system and we are wondering if the kepco didn’t get into the tighter tolerance in SECI either but wasn’t shown because the tolerance was higher. How comfortable would we be in loosening the tolerance? We could tighten the tolerance in the SECI zerofield controller and test if it gets within the tolerance still."

**Comment by JamesKingWork** [comment]
Having done some investigation into the pink borders, they are unlikely to be caused by the setpoint-readback not being within a tolerance of the setpoint. The measured corrected and measured raw come directly from the zfmag IOC, but the PVs that they come from don't go into alarm.

**Comment by FreddieAkeroyd** [comment]
I though that https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/9 might have been the reason we didn't see error messages before. If the return type of fabs() was assumed integer this might mean the tolerance function never worked in ibex properly before. However removing the `<math.h>` include doesn't remove the errors :-(

**Comment by JamesKingWork** [comment]
It was suggested that instead of waiting on a timeout for the readback to be within a tolerance of the setpoint, we waited until another setpoint was sent, then writing to the logs and incrementing the counter. I have implemented this on the branch and tested it on EMU and it's a metric that I think won't be of use, it counts up so fast that it looks like the readback almost never gets within tolerance of the setpoint before another is sent.

**Comment by JamesKingWork** [comment]
I think we have found a better solution. Instead of waiting for the setpoint readback to be within tolerance of the setpoint, the IOC checks just before a setpoint is set that the setpoint readback is within the tolerance of the previous setpoint that was set. The IOC calculates the percentage of times the setpoint readback is in tolerance for the last 1000 setpoints sent (calculated using compress records) and displays this on the “State machine diagnostics” section of the advanced tab in the zero-field controller device screen. This solution provides a diagnostic to check whether setpoints are being accepted without causing us to wait before writing. The changes are currently running on EMU and you can see the “Write success” is around 30-34%.

**Comment by FreddieAkeroyd** [comment]
It would be interesting to confirm that SECI has the same "write success" by this criteria, not sure how easy that is to add?

**Comment by JamesKingWork** [comment]
I agree it would be interesting but I think it would take considerable time to edit the LabVIEW to do this as the logic is different e.g. using retries.

**Comment by JamesKingWork** [comment]
Another clue: When I added a second thread which queries the measured voltage every second the Python sometimes got stuck on a read. This wouldn't seem to map to the error we are seeing as we would expect a read timeout in the log. I then commented out the SCAN on all kepco records except those related to the current. When commented out there are no longer messages in the log saying that the setpoint-readback isn't within tolerance.

**Comment by FreddieAkeroyd** [comment]
OK, so the measured current  was still being read as well as setpoint, but not much else? That is an interesting finding. Maybe turn off 1 second poll of current readback and add back 1 second poll of voltage, that would have same overall kepco poll rate, but different item.

**Comment by JamesKingWork** [comment]
Yeah just the current and the current setpoint readback, it is very interesting. Unfortunately turning off either of the current or current setpoint readback prevents us from seeing the symptom as they are part of the mechanism that causes it. If I put back one or two of the polls the symptom comes back but slower.

**Comment by JamesKingWork** [comment]
Based on this finding I am now trying to more carefully control scan loops to give a buffer between each time the device is queried (see PR https://github.com/ISISComputingGroup/EPICS-kepco/pull/16). Initially, this is looking very good, with the symptom not repeating itself. I will leave it over lunch and see if it occurs at all in that time.

**Comment by JamesKingWork** [comment]
After meeting with instrument scientists they are happy that we have provided a solution for this problem and consider this particular piece of the work package on the zero-field to be done. Their next highest priority is captured here https://github.com/ISISComputingGroup/IBEX/issues/6797 and they wish us to review and improve the overall performance of the zero-field in another work package to be completed at a later date.

To review this ticket: Confirm that the EMU zero field system is no longer seeing the issues listed above and the code changes are reasonable in https://github.com/ISISComputingGroup/IBEX/issues/6799.

**Comment by DominicOram** [comment]
The logs on EMU are still showing the error but at a significantly reduced rate, more like a couple of times a day than every 5 minutes. Code looks good, and there is sufficient comments on here to have a good idea of what's going on
