### ISSUE TITLE
EMU: Enhanced cryostat control scripts

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6729]
As an instrument scientist and user on EMU, I need enhanced cryostat control scripts, so that systems running under pressure control will heat and cool automatically to the desired temperature, automatically adjusting the gas flow and heater for optimal running. This ticket is to sit down with EMU scientists and gather requirements, agree on an appropriate algorithm. A ticket should be spun off to test the scripts when complete and will be carried out with other testing after the migration of EMU to Windows 10.

## Acceptance criteria:

- [x] Requirements are gather for the enhanced scripts
- [x] Algorithm and design decided upon
  - [x] Dev manual page describing the problem and design complete
  - [x] OPI design is on a branch
  - [x] Flowchart describes desired behaviour
  - [x] Example lookup table is produced
- [ ] Ticket to implement is created and linked

## Notes

- We should agree at this point exact numbers so requirements don't keep growing

**Comment by JamesKingWork** [comment]
Have a look at the little blue cryostat for refl

**Comment by DominicOram** [comment]
Cryogenics team should be in the meeting too

**Comment by JamesKingWork** [comment]
Meeting has been had with me, @KathrynBaker, @rerpha, the EMU team and a member of the cryo team. The cryo team will send some more details and I will write up a design from it and present it to the group.

**Comment by JamesKingWork** [comment]
Design for UI of enhanced mercury cryostat control: https://github.com/ISISComputingGroup/ibex_gui/pull/1374

**Comment by JamesKingWork** [comment]
Updated design based on scientists and cryo feedback at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC-Enhanced-Cryostat-Control with test script written in Settings/config/NDXEMU/Python/inst under the name cryo_control_test.py.

**Comment by JamesKingWork** [comment]
Putting this into review, cryogenics have confirmed that the algorithm looks good

**Comment by KathrynBaker** [comment]
The scientists confirmed that the tests were complete and the test script worked well with a few adjustments for the whole temperature range, as such the system can now be incorporated into IBEX. I have created #6947 to complete this work.
