### ISSUE TITLE
SANS2D: Test sample changer

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6732]
As an IS I would like to be confident in IBEX being able to control sample changer. Currently, SANS2D does not have the SANS sample changer so this will need to be done after https://github.com/ISISComputingGroup/IBEX/issues/6708. 

### Acceptance criteria:
- [ ] Check that the function from SECI is replicated

**Comment by RaiBishal** [comment]
Tested on SANS2D with Leide. 
Racks definition files(xml) have been setup in the config area and works as expected.

**Comment by rerpha** [comment]
Can see the rack definitions file does exist on the branch - all working as expected in person so don't think there is anything else to review.
