### ISSUE TITLE
Support for SANS2D

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6734]
Helping out SANS2D to set up their basic configuration, with synoptics and making sure that their devices are talking to our IOCs.

**Comment by DominicOram** [comment]
If you look on https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/NDXSANS2D no changes have been made to the SANS2D configs for ~10 months. Is this correct or is there an issue where it's not pushing config changes? Was there anything in doing this ticket that you could have added to the wiki or to https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details to help support SANS2D in the future?

**Comment by RaiBishal** [comment]
> If you look on https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/NDXSANS2D no changes have been made to the SANS2D configs for ~10 months. Is this correct or is there an issue where it's not pushing config changes? 

Looked like the local branch was diverged from the origin. I have fixed it now and resolved some conflicts.

> Was there anything in doing this ticket that you could have added to the wiki or to https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details to help support SANS2D in the future?

Nothing new to add to SANS2D wiki at this point.

**Comment by GRyall** [comment]
Work was completed and documented. Closing ticket.
