### ISSUE TITLE
MDT: fix deployment folder version control

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6741]
The mdt share has "dev1", "dev1 backup", and "prod1" folders present - these top 3 look to be in git, but each folder also individually has a .svn repository

## acceptance criterial

- remove unnecessary directories
- remove duplicate version control systems
- document best way for a developer to work on this after installing mdt tools locally. Is it
  - clone folder locally
  - make edits and create share of folder, setting boot host to be your own machine 
  - boot up hyperv vm using your local share
  - when ok push back to central share. Currently can't make PR as not in github, but could make a branch and other developer review

currently the git repo is file based and too big for github. A query has been submitted to stfc gitlab
as a test shows that it supports git LFS. However we need to note that Git for windows seems to have issues
with files over 4GB so we may need to be selective about what we include to avoid corruption. For example what do we count as derived files and hence not include in version control. Do we need to "deploy" from the share creating a release etc. rather than trying to put all generated binaries into git. 
  
`https://github.com/git-for-windows/git/issues/1063`
`https://github.com/git-lfs/git-lfs/issues/2434`

**Comment by ChrisM-S** [comment]
This ticket is now significantly out of date.  The areas specified are all obsolete and whilst the documentation at [building-an-mdt-build-server](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-a-windows-10-MDT-build-server#building-an-mdt-build-server) contains some useful setup information for building a developer system with MDT it is also out of date.  Building a test instrument VM is documented at [Building-a-windows-10-instrument-machine-from-MDT](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-a-windows-10-instrument-machine-from-MDT#building-a-new-instrument-virtual-machine-from-mdt).  Setting up an MDT developer system is now best done by checking out a local folder on the developers machine from the site Git Lab repository and editing boot and .ini files (as well as installing the MDT packages on the developers local machine).

I suspect there are more tickets for regularizing the build/documentation of an MDT Windows 10 instrument system and a central production build share but this one should probably be closed as it does appear to be holding 8 points which could probably be better used elsewhere!

**Comment by KathrynBaker** [comment]
Given that this is out of date, and limited work was undertaken against it, it is being closed and zeroed out of the system
