### ISSUE TITLE
SANS: Stop button in Sample Changer OPI

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6743]
### Description
The current Sample changer OPI does not have a stop button so we have to go to ToM to stop any motors. It would be a lot easier if there was a stop button in the Sample changer OPI itself.

### Acceptance criteria:

- [x] Stop button in Sample changer OPI is present
- [x] Stop button stops the movement of relevant motors

**Comment by Adam-Szw** [comment]
I am going to assume the ticket is talking about **SANS** Sample Changer OPI, rather than Sample Changer, since the latter appears to have stop buttons in it already.

**Comment by Adam-Szw** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6936
IBEX GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1382
