### ISSUE TITLE
HIFIMAGS: Fix for statemachine getting stuck in quench

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6744]
As a user of the hifi magnets, when I set the operating mode to be high field and the magnet is not quenching, I would like the high field to be set. The hifimags IOC system test was failing intermittently when setting the high field operating mode because the output did not reach the correct gauss. This was because the state machine was getting stuck in the quench state and could not the correctly react to the operating mode set.

## Steps to reproduce

1. Check out the branch created for this ticket and replace the changes made with:
  - ```when () {
      errlogSevPrintf(errlogMajor, "Stuck in quench");
    } state quench```
2. Start the IOC
3. Set HIFIMAGS_01:X:TARGET to 1
4. Set HIFIMAGS_01:X:ZERO to 0.2
5. Set HIFIMAGS_01:X:ZEROFIELD to 0.3
6. Set HIFIMAGS_01:SIM:X:QUENCH to 1 (quenched)
7. Set HIFIMAGS_01:SIM:X:QUENCH to 0 (not quenched)
8. Set HIFIMAGS_01:SIM:M:QUENCH to 1 (quenched)
9. Set HIFIMAGS_01:SIM:M:QUENCH to 0 (not quenched)
10. Set OPMODE:SP to 1 (high field)
11. Confirm X:OUTPUT:FIELD:GAUSS != 0.2
12. Confirm logs are printing "Stuck in quench"

## Acceptance criteria:

- [ ] Steps to reproduce above are followed between point 2 and 11
  - Revert the changes made in point 1 back to what is in the branch I have created
  - The  X:OUTPUT:FIELD:GAUSS should be correctly set to 0.2
- [ ] It is confirmed with @KathrynBaker or @LilithCole that these changes will not have an adverse affect on the hifimags control
- [ ] IOC tests no longer intermittently fail

**Comment by rerpha** [comment]
Sorry @LilithCole , all yours!

**Comment by KathrynBaker** [comment]
After a quick look, so long as the tests are passing, it should be OK. I'm not in a position to verify that all the tests in the suite pass, but can confirm that the logic is sound enough

**Comment by rerpha** [comment]
Will run the tests now

**Comment by rerpha** [comment]
Tests pass!
