### ISSUE TITLE
SANS: Remove excessive logging for Sample Changer OPI

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6748]
### Description
After every N seconds (less than 3 I think) the sample position file is rewritten which is then logged in the GALIL IOC log. This will cause disk space to fill up quickly and will make it difficult to read through the log file (constant refresh). 

### Acceptance criteria

- [ ] Change logging rate

**Comment by FreddieAkeroyd** [comment]
There are 10 lines per second of the form `sampleChanger: writing motionsetpoints lookup file` in the log, this suggests the 0.1 second scan loop for `$(P)AVAILABLE_SLOTS` in sampleChanger.db is triggering a recalculation. It looks like this and several other functions create a new instance of the converter class on every call, which results in the files being regenerated. I think `sampleChanger.cpp` needs some attention.
