### ISSUE TITLE
Beckhoff: Merge the Automation Tools

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6751]
As a developer I would like the Beckhoff test code to be as simple as possible. Currently there are two sets of Automation Tools that  are required to test the code:
* The automation tools used by the IOCTestFramework to run a Twincat solution locally (https://github.com/ISISComputingGroup/BeckhoffTestRunner/tree/master/util_scripts/AutomationTools). These were written by us.
* The automation tools to create a specific solution file for a hardware setup given some configuration files (https://github.com/Simon-Cooper/twinCATAutomationTools). Originally written by @Simon-Cooper 

They do similar things and could share a lot of code.

## Acceptance Criteria
* The code is brought into one repository that meets the needs of both us and @Simon-Cooper 
* The code is in a repository that can be accessed by both groups

**Comment by rerpha** [comment]
TCAT: https://github.com/ISIS-Motion-Control/twinCATAutomationTools/pull/13 (once merged we should update the submodule in BeckhoffTestRunner)
BeckhoffTestRunner: `use_simons_runner` - whoops, i should have branched off this
IOCtestframework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/490

todo update the wiki
