### ISSUE TITLE
Add method of getting the number of axes for a motor controller

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6755]
As an instrument scientist I would like to be able to control all the axes on a controller ~through the GUI~(spun out into https://github.com/ISISComputingGroup/IBEX/issues/6865), even if there are more than 8 of them. This limit was set by the Galils but the Beckhoffs have no such limit. 

## Acceptance Criteria
* A PV is added for the total number of axes per controller, regardless of whether it's a Galil, Beckhoff, Mclennan etc. 

## Notes
This is required for #6865 and #6823

**Comment by rerpha** [comment]
needed for #6754 to display all axes in IBEX

**Comment by rerpha** [comment]
the restore_motor_positions script may only support up to 8 axes, though im not sure we'll need to use this for beckhoffs?

**Comment by ThomasLohnert** [comment]
A minor thing but I noticed that you can just overwrite the value in `:AXES_NUM`. Not sure whether this is by design, unimportant or a potential weakness - if it's the latter it might be worth setting `.DISP` ?
