### ISSUE TITLE
Data streaming: update forwarder version

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6758]
As a developer I would like to test and use the latest Python-based forwarder and archive the C++ one so we no longer keep it as a submodule 
This involves: 
- Archiving the old fork (forward_epics_to_kafka) 
- removing submodule for it
- Forking https://github.com/ess-dmsc/forwarder cloning this on NDADATASTREAM then restarting the nssm service
- ~possibly need to update inst_servers/BlockServerToKafka to push the correct config To the forwarder~ - schema has stayed the same so no changes required

**Comment by rerpha** [comment]
have forked the forwarder: https://github.com/ISISComputingGroup/forwarder

**Comment by rerpha** [comment]
We could also get it logging to graylog

**Comment by rerpha** [comment]
have updated forwarder and is now pushing to graylog - see http://madara<suffix>:9000/search?q=gl2_source_input%3A613893484d1e057a30d736b0&rangetype=relative&relative=0

**Comment by rerpha** [comment]
r5fk has not changed so inst_servers does not work. 

To review this ticket: 
check the graylog output and make sure it is updating - should be pushing the prod version of the forwarder's output.

**Comment by JamesKingWork** [comment]
Looks like the forwarder is working nicely as seen in graylog and NDADATASTREAM also seems happy. For the rework can we please archive the old fork and remove it as a submodule.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/271
