### ISSUE TITLE
EMU: Commission and test on Windows 10

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6761]
As an EMU instrument scientist, I would like to be on windows 10 and have my kit tested to ensure we can run correctly in the next cycle.

### Acceptance Criteria

- [ ] Instrument scientists are comfortable with running the next cycle on windows 10
- [ ] The muon barndoors are controllable through the MUONJAWS IOC (this is an lvdcom LabVIEW driver)
- [ ] IOCs to control kit have been tested sufficiently (to be discussed with scientists, potential kit to test: zero field system, danfysik, eurotherm, julabo, heliox, genesys, caenv895, ITC503, ILM200, mercury, triton, lksh372)
- [ ] Background script plots are as adequate as before move to Win 10
- [ ] Regularly run scripts are tested
- [ ] Changes made in https://github.com/ISISComputingGroup/IBEX/issues/4130 to CAEN summary OPI work

**Comment by davidkeymer** [comment]
Closing ticket as EMU have been running on Windows 10 for about 2 years since the long shutdown.
