### ISSUE TITLE
PEARL Pressure Controller: Test Hardware

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6762]
As a: developer

I would like communicate with both PEARL and WISH to arrange a time to test the Pearl pressure controller. This should be done after testing with the emulator #7114

### Acceptance Criteria
- [ ] Ensure EPICS logic written as part of #6040 behaves as expected against PEARL pressure controller hardware.
- [ ] Logic not handled by the device is correctly documented and placed into new issues where appropriate to align with functionality of existing LabView VI implementation.
- [ ] Ensure OPI screen in IBEX displays information as expected when testing hardware. 

### Extra Information
_Why it is needed?_
In order to correctly develop the IOC and OPI, testing of the hardware is required to ensure that work completed as part of #6040 works as expected. 
Testing the hardware will also gain insight into what is device specific controller logic and what needs to be developed further using DB logic as the separation between the two is not incredibly clear in the Manual. 
Once a clear separation of logic is known and documented, work can continue with adding functionality to PEARLPC OPI device screen which reflects LabView VI functionality.

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by rerpha** [comment]
Minor issue spotted - `LAST_ERR` didn't seem to match up with the error code at least in the case of the errcode being 6 which should correlate to "General Error" - the LED was on for `GENERAL_ERROR`. I did have a quick look with nothing that obvious in the code. I can spin out a ticket but i'm tempted to wait and see if there are any other errors found by the IS before doing so

**Comment by Tom-Willemsen** [comment]
@rerpha I'll have a look at that issue this afternoon.

**Comment by Tom-Willemsen** [comment]
Device was tested this morning on WISH. Communicated fine apart from issue described above ([fixed in PR](https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/8)). Configs and scripts written on WISH with scientist, and scientist is happy that system was behaving as expected.

**Comment by FreddieAkeroyd** [comment]
@rerpha @Tom-Willemsen As far as we know this has worked fine other than the minor error code fix in the PR?

**Comment by rerpha** [comment]
> @rerpha @Tom-Willemsen As far as we know this has worked fine other than the minor error code fix in the PR?
Yes.

**Comment by rerpha** [comment]
> > @rerpha @Tom-Willemsen As far as we know this has worked fine other than the minor error code fix in the PR?

Yes
