### ISSUE TITLE
PEARL Pressure Controller: Detect Seal Fail DB Logic

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6764]
As a: developer

I would like to add DB logic to detect if a seal failure has occurred to trigger a seal fail mode which can only be turned off once the device has been power cycled as specified in the manual. 

The device allows for a seal fail value to be set by the user. 
When the pressure suddenly drops by the seal fail value set, a seal fail mode should be set which locks out any other functionality until power cycled.

When a seal fail mode is active, this should be displayed using an LED in the OPI. 

### Acceptance Criteria
What is the acceptance criteria?
- [ ] Seal fail mode initiated if pressure drops suddenly by seal fail value
- [ ] Seal fail mode displayed in OPI as LED

### Extra Information
_Why it is needed?_
Detecting a seal failure is an important requirement of the device in order to function as expected.

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by JackEAllen** [comment]
One thing to note is that when the device is placed into a seal fail mode, the device should not be allowed to return to it's previous state until power cycled. I recommend disabling access to the record once set. So if a binary out EPICS record is used to set the seal fail mode. When set to 1, the record should then be disabled meaning it can't be set back to 0 until power cycled.

**Comment by FreddieAkeroyd** [comment]
I believe you can just set the seal fail limit, and the device will then detect a seal fail itself - pressure does not need to be monitored on the db side to detect a seal fail. When a seal fail occurs (exceed specified sf level) then the SF status flag is set to indicate a seal failure and the hardware locks itself until a power cycle

**Comment by Adam-Szw** [comment]
Waiting for https://github.com/ISISComputingGroup/IBEX/issues/6774 to be reviewed

**Comment by Adam-Szw** [comment]
Additional things to look at carried over from here: https://github.com/ISISComputingGroup/IBEX/issues/6774#issuecomment-1146802078
