### ISSUE TITLE
PEARL Pressure Controller: Detect If Motors are Active

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6765]
As a: developer

I would like to determine using DB logic if the motors are active or not to then create an LED to display this in the OPI device screen.

Functionality to determine if motors are active or not is not clearly documented in the manual and relies on information collected as part of #6763 

### Acceptance Criteria
- [ ] If device motors are active, an LED displays this in the OPI device screen

### Extra Information
_Why it is needed?_
- To determine if the Motors are active. 
- This could be useful for debugging purposes should the controller behave as desired.
- The functionality is already present in the LabView VI and so it is likely that both PEARL and WISH will want this functionality carried over to the IBEX GUI device screen.

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by KathrynBaker** [comment]
Detail on the LabVIEW implementation (part of #6763):
The proto file for the `st` command covers this, the part of that string related to the motors being active is the 5th section and is true if that part of the returned value from status is not equal to 0 (so $1.E as I read the protocol file)
