### ISSUE TITLE
PEARL Pressure Controller: Remote and Local Mode

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6767]
As a: developer

I would like to create remote and local mode db logic to display LED's in the OPI device screen to replicate existing functionality present within the LabView VI based on information which will be documented as part of #6763 as the manual does not provide sufficient information to achieve desired functionality. 

### Acceptance Criteria
- [ ] DB logic to handle local and remote modes.
- [ ] LED's in the OPI to display if device is in remote or local mode.

### Extra Information
_Why it is needed?_
To replicate existing functionality present within the LabView VI 

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by KathrynBaker** [comment]
Detail on the LabVIEW implementation (part of #6763):
The proto file for the st command covers this, the part of that string related to remote mode is the 7th section and is true if that part of the returned value from status is not equal to 0 (so $1.G as I read the protocol file)

**Comment by Tom-Willemsen** [comment]
Already complete as part of an earlier ticket.
