### ISSUE TITLE
SANS2D: Test S6 on beamline

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6773]
## Where?
In Beamline

## Acceptance criteria 
- [ ] S6 is tested in SANS2D beamline

**Comment by JamesKingWork** [comment]
I don't feel like I can review this until some information on what steps were taken to test S6 and the results of this testing have been given

**Comment by RaiBishal** [comment]
Did the followings tests:
- Motors  and axis were set up for this S6
- Made sure that S6 can reach all the setpoints(small, medium, large, x large) without hitting the limit. These setpoints can be found in SANS2D settings area inside  `motionSetPoints\scarper_aperture.txt`.
- Made sure that behaviour in IBEX is consistent with SECI

Result:
Scientists were happy that the motors can get to all setpoints as SECI. I cannot be anymore precise with this testing without the beam. S6 is inside a chamber and moving S6 to different setpoints(S, M, L, XL) is used to determine the size of the beam. IS will inform us if they see any issue with it when they test it with beam next time.

**Comment by JamesKingWork** [comment]
Sounds good!
