### ISSUE TITLE
PEARL Pressure Controller: Cell and Pump Pressure

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6774]
As a: developer

I would like to create the DB logic and fields in the OPI to display the cell and pump pressure values based on information documented as part of #6763 to carry functionality over from LabVIEW VI implementation.

### Acceptance Criteria
- [x] Create DB logic for reading back pump pressure
- [x] Create appropriate fields in OPI device screen to display cell and pump pressure values

### Extra Information
_Why it is needed?_
- Functionality exists in LabView VI and should be replicated in IBEX GUI device screen for consistency.

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by KathrynBaker** [comment]
Detail on the LabVIEW implementation (part of #6763):
Cell Pressure
- Send the command `vr0087`
- Discard the first 7 characters returned
- The remainder are converted into a decimal value which is the cell pressure

Pump Pressure
- Send the command `vr0088`
- Discard the first 7 characters returned
- The remainder are converted into a decimal value which is the pump pressure

**Comment by FreddieAkeroyd** [comment]
There is now a `get_memory` in the EPICS stream protocol so this should be straightforward

**Comment by Adam-Szw** [comment]
There is more that needs to be done for this ticket:

- [ ] Implement Start, Stop, Retract and send parameters buttons from VI
- [ ] Cleanup commands from emulator and replace them with backdoor where applicable
- [ ] Cleanup useless records and implement whats missing based on VI

**Comment by Adam-Szw** [comment]
- [ ] Servo loop mode from VI to be added as well

**Comment by Adam-Szw** [comment]
Not everything was changed and/or implemented based on VI. I moved some of the requirements to other PearlPC tickets. Made sure to make commits very descriptive, so refer to that when reviewing. PRs:
pearlPC support: https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/5
ibex GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1416
release notes: https://github.com/ISISComputingGroup/IBEX/pull/7157

**Comment by Adam-Szw** [comment]
How to review:
- checkout correct branches and be sure to use 'make clean uninstall' and then 'make' on support/ioc directories
- run the tests
- open labview VI (see in ticket description) and compare if functionality aligns between the two
- look on the commit notes to see what was supposed to be changed and see if it indeed works as intended
- all the other standard review stuff such as code quality etc.

**Comment by FreddieAkeroyd** [comment]
Lookign good:
* On VI increasing/decreasing pressure comes from device inputs, so logic in DB may not be needed
* user limit might best be set by macro, but maybe leave that until setting other parameters also in labview .ini e.g. d+, o+,d-, o-
