### ISSUE TITLE
Beckhoff: Use direction from PLC

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6776]
As a developer I would like the Beckhoff PLC to tell me which direction it is moving in, rather than calculating it myself inside the motor record. 

### Acceptance Criteria
- [ ] The TWINCAT motor record gets its direction directly from the PLC rather than calculating it

### Extra Information
* The direction is now exposed in the PLC side https://bitbucket.org/europeanspallationsource/tc_mca_std_lib/pull-requests/44

**Comment by rerpha** [comment]
tcioc: https://github.com/ISISComputingGroup/EPICS-tcIoc/pull/9

**Comment by rerpha** [comment]
Tests all passing, there are already tests for direction. Hooray for TDD
