### ISSUE TITLE
Deployment [w/c 11/10/2021]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6780]
As someone invested in the IBEX project I want to deploy a recent release to the systems below:

- EMU - **pending Win10 migration, hold off for now**
    - [x] Started
    - [x] Completed
- SURF
    - [x] Started
    - [x] Completed
- LARMOR (may need earlier for Beckhoff testing)
    - [x] Started
    - [x] Completed
- IMAT (will need for Beckhoff testing)
    - [x] Started
    - [x] Completed
- CRISP (will need for Beckhoff testing)
    - [x] Started
    - [x] Completed
- POLREF (needed for testing of reflectometry updates)
    - [x] Started
    - [x] Completed

**Comment by KathrynBaker** [comment]
SANS2D might also need a deployment as well, it will depend on when the stober drives are being tested.

**Comment by JamesKingWork** [comment]
Could try out copying from a VHD

**Comment by DominicOram** [comment]
EMU is now done so I'll move this to review
