### ISSUE TITLE
Jenkins: cleanup jobs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6783]
The following jenkins jobs may no longer be needed, or could be improved

* TCIocTest - not ran for a year, delete?

* System_Tests_IOCs, System_Tests_IOCs_debug - IOC tests moved to system tests, delete?

* squish_install_client_server_python - shouldn't System_Tests_Squish install ibex itself like other system tests?

* new_runtests_build - superceded, delete?

* Install_latest_client_server_and_genie_python - superceded, delete?

* inst_servers_python_3 - now we are python 3 is this no longer needed?

* ibex_gui_E3_maint - not ran since 2018, delete?

## acceptance criteria

unneeded jobs removed

**Comment by FreddieAkeroyd** [comment]
Re: squish system_tests_ui_e4  - when merged, swap squish jenkins back to running master branch

**Comment by rerpha** [comment]
what is https://epics-jenkins.isis.rl.ac.uk/job/shared_scripting_docs/ ? should we remove this too?

**Comment by rerpha** [comment]
also https://epics-jenkins.isis.rl.ac.uk/job/fig/

**Comment by KathrynBaker** [comment]
The jobs list is currently looking fairly clean - whilst there are still a few disabled they can be got on the next spring clean of the jobs.
