### ISSUE TITLE
SANS2D: Use delayed moves for tank collision avoidance

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6785]
As an IS on SANS2D I want to be sure that the hardware inside my tank doesn't collide with each other. Various methods have been tried in IBEX to do this (https://github.com/ISISComputingGroup/IBEX/issues/5894) but it was decided that we should instead do it the same way that SECI does:

* There are top-level PVs and a top level OPI for the tank
* Setting positions to these top level PVs use [delayed moves](https://github.com/ISISComputingGroup/IBEX/issues/6786)
* The set PV can only be actioned if the move will not cause a collision

### Acceptance Criteria
- [ ] The above is implemented
- [ ] The old way of doing collision avoidance on SANS2D is removed
- [ ] There are tests for this behaviour
- [ ] Blocks are added to these PVs
- [ ] Check if we need to take rotation into account

## Notes
* Because this is a set of top-level PVs there will be no collision avoidance for moves made via the table of motors @RaiBishal to confirm with the scientists that this is ok (They are fine with it, asked Sarah on 20/09/2021)
* For the same reason blocks should not be added to the low level motors/axes

**Comment by DominicOram** [comment]
As part of removing the old code for collision avoidance we can remove https://github.com/ISISComputingGroup/EPICS-galil/blob/master/GalilSup/Db/galil_sans2d_front_det_limit_footer.dmc (also solving homing issues on S6)

**Comment by RaiBishal** [comment]
PRs:
https://github.com/ISISComputingGroup/ibex_gui/pull/1358
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/491/files
https://github.com/ISISComputingGroup/EPICS-ioc/pull/639
https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/35
