### ISSUE TITLE
ibex install: check not running as admin

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6796]
As a developer I would like the ibex install script not to allow me to install as admin. This check is probably best done in two places:

* the `install_to_inst` bat file as this can get run on its own. The approach described in #6650 should be applicable
* the python upgrade script - check at the start so does not fail much later on.

## acceptance criteria

* installation fails if ran as admin

**Comment by FreddieAkeroyd** [comment]
First bit added as https://github.com/ISISComputingGroup/EPICS/commit/74c0d30f920479defe82725a2e6e356599ea2529 as would be useful for release

**Comment by danielmaclaren** [comment]
Link to Pull Request:

https://github.com/ISISComputingGroup/ibex_utils/pull/157
