### ISSUE TITLE
Java: Move to new long-term support (LTS) version 17

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6798]
As a developer, I would like to keep our Java versions up to date. As of September 2021, Java 17 is the new LTS version replacing Java 11 (our currently used version) which has an end of life date in September 2023.

## Acceptance criteria:

- [ ] Both client and server-side IBEX software runs on OpenJDK 17

## Notes

- We need to find out whether CSS and other dependencies will support Java 17

**Comment by JamesKingWork** [comment]
> Could be done as part of the next dependency update?

I think the dependency update is probably big enough as it is and this could be a relatively large chunk of work depending on how easy it is to get diirt and CSS to work with it

**Comment by FreddieAkeroyd** [comment]
I think we have until at least mid 2023 with java 11?

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/8468 moves to java 21 for server runtime
