### ISSUE TITLE
upgrade script: handle previous choice of old or new galil driver

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6814]
The upgrade script currently prompts for you to choose old or new galil driver (default n), but in subsequence releases it should detect what you currently have installed. The mechanism currently installs new galil driver to ioc/GALIL and old one to ioc/GALIL-OLD - it would need to
* if there is neither a GALIL-OLD or GALIL-NEW prompt user (default to n at moment)
* if there is GALIL and GALIL-OLD but no GALIL-NEW then install as normal (this will keep as NEW)
* if there is GALIL and GALIL-NEW but no GALIL-OLD then it will need to run `swap_galil.bat NEW` to make the new driver the default, install ibex server, then run `swap_galil.bat OLD` to put things back. Note: on reflection, initially running `swap_galil.bat NEW` is not needed as the install replace all files, but running `swap_galil.bat OLD` at end is definitely.    

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/New-Galil-Driver

## Acceptance criteria

above steps implemented

**Comment by FreddieAkeroyd** [comment]
@ThomasLohnert I have adjusted logic, think it is correct now

**Comment by ThomasLohnert** [comment]
It currently only checks (and resets) the driver version for the use case "install latest build only", is that intended? The method for selecting Galil also gets called as part of a regular deploy and first time install, but will not actually do anything at the moment. Should we implement the same mechanism for those or just remove the step?

**Comment by FreddieAkeroyd** [comment]
@ThomasLohnert you are right, I hadn't noticed the logic was only used by that method. I've decided the logic is actually in the wrong place and have moved it into the ibex server install, so it now gets done automatically in all cases
