### ISSUE TITLE
Instrument Demos for Release 10.0.0

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6819]
As a user of IBEX I would like to be kept abreast of new features of IBEX. Given that we have just done a release (https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/Release-Notes_v9.0.0.md) we should demo new features. See https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos.

## Notes
List of instruments to demo to:

* [x] LARMOR
* [x]  IMAT 
* [x]  POLREF 
* [x]  INTER
* [x]  SANS2D
* [x]  WISH
* [x]  LET
* [x]  NIMROD
* [x]  ZOOM 

None of them will have had a demo since 7.4, so make sure to cover all releases in between.

## Acceptance Criteria
- [x] Demos are assigned across the group
- [ ] Demos are performed and minuted on the wiki

**Comment by rerpha** [comment]
LARMOR\SANS2D\ZOOM done.

**Comment by rerpha** [comment]
All done now

**Comment by KathrynBaker** [comment]
I've seen various bits of tickets and notes, I'm going to call this complete
