### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6820]
As a developer I would like to be sure that none of the IBEX dependencies get too out of date. Following the latest release (https://github.com/ISISComputingGroup/IBEX/issues/6778) we should update our dependencies. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates

## Acceptance Criteria
- [ ] Dependencies are updated
- [ ] New dependencies are listed in the upcoming release notes
- [ ] IBEX is roughly tested to confirm it still works

**Comment by rerpha** [comment]
ActiveMQ: https://github.com/ISISComputingGroup/EPICS-ActiveMQ/pull/9

**Comment by LilithCole** [comment]
Things that work:
- updating log4j api and core, joda time, and mysql connector java (all that need updating except activemq) (jars are in private share\data for tickets\this ticket)
- updating eclipse version in targetplatform & parent pom
- updating efxclipse
- updating eclipse/releases
- updating jacorb and py4j from shadow (_test folders)

Things that break it:
- updating activemq makes complaints about the logger and not being able to find log4j classes on runtime, but no errors on compilation
- updating eclipse orbit leads to issues even being able to find its modules
- updating cs studio from shadow (found next to current version, css_gui_dep_test) leads to runtime errors of being unable to find packages from apache batik, bouncycastle and javax

**Comment by LilithCole** [comment]
https://github.com/ISISComputingGroup/ibex_gui/tree/TIcket_6820_dependencies works so far, has jar changes and some targetplatform dependencies updated

**Comment by rerpha** [comment]
We should re-check the dependencies again when picking this ticket up as they may have gone stale by now

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ActiveMQ/pull/9
- https://github.com/ISISComputingGroup/nicos/pull/5
- https://github.com/ISISComputingGroup/ibex_utils/pull/131
- https://github.com/ISISComputingGroup/genie_python/pull/367
- https://github.com/ISISComputingGroup/ibex_gui/pull/1466

To review:
- Check out all branches above
- Stop ibex server
- In IBEX utils repo, run `upgrade_mysql.bat` to update your local MySQL installation
- In genie_python, run `dev_build_python.bat` to rebuild your local python
- In GUI, run `build.bat` to generate a built client
- In GUI (eclipse):
  * If your eclipse is not version 2022-06, update to 2022-06 (on share at `\\isis\inst$\Kits$\CompGroup\ICP\Developer Tools`)
  * Reload target platform
  * Depending on your eclipse configuration, you may need to change workspace compliance settings to Java 17
- Start IBEX server
- Verify that all **major** functionality still works with new dependencies
  * Check in both GUI built via eclipse and GUI built via maven
  * e,g. configs, blocks, basic scripting via genie_python, perspectives in GUI display sensibly
