### ISSUE TITLE
Beckhoff: Add to motors moving and to stop all

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6823]
As a user I would like the motors moving indicator to inform me when Beckhoff axes are moving and I would like Beckhoff axes to stop when I press stop all.

### Acceptance Criteria
* When a Beckhoff axis is moving the global moving flag is set to true
* When I press stop all on the GUI all Beckhoff motors are also stopped

**Comment by rerpha** [comment]
Turns out the motor utils do a similar thing (but in reverse) to how we check the number of axes on a record, and therefore should be a dynamic. The changes needed in this ticket are loading the axisUtils records in as well as adding the twincat IOC to the fan record.

**Comment by rerpha** [comment]
the moving flag will oscillate currently, https://github.com/ISISComputingGroup/IBEX/issues/6874 is to fix it

**Comment by JackEAllen** [comment]
Tests seem to pass as expected. Using in simulation mode, the global moving flag is set to true and the stop motors moving in the GUI works as expected. 👍

**Comment by rerpha** [comment]
Great, thanks Jack
