### ISSUE TITLE
SANS Sample Changer: Document Sample Changer

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6824]
As a a Developer

I would like to add comments to the Sample Changer to document functionality to make the repository more developer friendly.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Documentation is well written and there are no spelling errors
- [ ] Documentation is consistent
- [ ] Documentation explains code well.

### Extra Information
_Why it is needed?_
To make the repository more developer friendly.

## How to Test
_verbose instructions for reviewer to test changes
- Checkout [SANS Sample Changer](https://github.com/ISISComputingGroup/EPICS-sampleChanger/tree/Ticket6824_sample_changer_delayed_move) branch from `C:\Instrument\Apps\EPICS\support\sampleChanger\master`.
- Navigate to `sampleChanger\master\sampleChangerApp\src` to inspect:
    - [ ] `sampleChanger\master\sampleChangerApp\src\converter.cpp`
    - [ ]  `sampleChanger\master\sampleChangerApp\src\converter.h`
    - [ ]  `sampleChanger\master\sampleChangerApp\src\sample_changer.py`
    - [ ]  `sampleChanger\master\sampleChangerApp\src\sampleChanger.cpp`
    - [ ]  `sampleChanger\master\sampleChangerApp\src\sampleChanger.h`
- Read through docstrings and comments to ensure they describe functionality well.
- Determine if documentation added is well written and contains no spelling errors.
- Ensure that documentation is consistent in format

**Comment by JackEAllen** [comment]
To review please see the following PR:
[Sample Changer](https://github.com/ISISComputingGroup/EPICS-sampleChanger/pull/11)

**Comment by RaiBishal** [comment]
Looks good it is surely helpful but I feel like we are missing documentation on few more places

**function declarations**
converter.h: line 74, 75, 76, 69, 

**class**
converter.h: line 14

**struct and its member variables** 
converter.h: line 18, 36, 25, 48

**Methods of class sample_changer**
sample_changer.py

**Comment by JackEAllen** [comment]
> Looks good it is surely helpful but I feel like we are missing documentation on few more places
> 
> **function declarations** converter.h: line 74, 75, 76, 69,
> 
> **class** converter.h: line 14
> 
> **struct and its member variables** converter.h: line 18, 36, 25, 48
> 
> **Methods of class sample_changer** sample_changer.py

I've added more documentation to `converter.h` and also `sampleChanger.h`. 
Where would you like me to add more documentation inside `sample_changer.py`? There is a docstring for both the `PV` class and `move_to` method already. I don't believe there are any other methods inside `sample_changer.py`
