### ISSUE TITLE
POLREF: Set up Little Blue Cryostat

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6833]
Soft matter want to test the little blue cryostat on POLREF on Wed 20/10/2021 and would like some help setting it up in IBEX before then. 

### Acceptance Criteria
- [ ] Cryostat is set up and working on POLREF

### Extra Information
Some documentation is available at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC

**Comment by rerpha** [comment]
Looks like they already have a component for this so should be a case of plugging it into whatever COM37 maps over to and loading the component

**Comment by rerpha** [comment]
Yeh I think before that the IOC was running without the device actually hooked up
