### ISSUE TITLE
Script Generator: Queue actions individually

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6841]
As a script generator user, I would like to be able to control my script dynamically and display feedback from the script in the generator. We need to queue each action separately to be able to do this control and display.

### Acceptance Criteria

- [x] When queueing a script in the script generator each action is queued one at a time
- [ ] Another script cannot jump in between actions of the running script generator script
- [x] Queued actions are ID'd in such a way they can be recognised as script generator actions and the current action identified
- [x] Actions are queued in such a way that their order and values can be manipulated and more can be added

### Extra Information
_Other tickets to consider when implementing this ticket_

https://github.com/ISISComputingGroup/IBEX/issues/6657
https://github.com/ISISComputingGroup/IBEX/issues/4176
https://github.com/ISISComputingGroup/IBEX/issues/6684

_Where required files/links are_
Part of the [ibex_gui repo](https://github.com/ISISComputingGroup/ibex_gui) see the script generator and Nicos plugins.

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1375
RN: https://github.com/ISISComputingGroup/IBEX/pull/6887
Docs: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IBEX-Script-Generator-Dynamic-Scripting

This work at least partially completes: https://github.com/ISISComputingGroup/IBEX/issues/6657, https://github.com/ISISComputingGroup/IBEX/issues/6684 and https://github.com/ISISComputingGroup/IBEX/issues/4176. After this ticket is complete we should reconsider those tickets and work out what is left to do on them. I have spun off squish testing into https://github.com/ISISComputingGroup/IBEX/issues/6888.

**Comment by JamesKingWork** [comment]
I have gone over the code and pair programmed a part of this with @SamJenkins1.

**Comment by JamesKingWork** [comment]
An idea of how to review this ticket:

- The expected behaviour is described here: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/114/files
- The script generator code is here: https://github.com/ISISComputingGroup/ibex_gui/pull/1375/files
- Review if expected behaviour is reasonable and covers edge cases
- Check that the script generator changes correctly implement the expected behaviour
- Carry out full code review on script generator code and tests
- Confirm all unit tests pass
- Confirm existing squish tests pass
- Propose squish testing ticket for next sprint https://github.com/ISISComputingGroup/IBEX/issues/6888
- Reevaluate what is required for the rest of the dynamic scripting tickets: https://github.com/ISISComputingGroup/IBEX/issues/6684, https://github.com/ISISComputingGroup/IBEX/issues/4176, https://github.com/ISISComputingGroup/IBEX/issues/6657

**Comment by JamesKingWork** [comment]
The behaviour currently pauses on an invalid action. Muons have now suggested they may want to configure between skipping invalid actions and pausing. They have also suggested that at the start of the script if there are any invalid actions the user should be warned. I think these are reasonable requests and we should consider how best to do them, but have spun it off into https://github.com/ISISComputingGroup/IBEX/issues/6899 and https://github.com/ISISComputingGroup/IBEX/issues/6900.

**Comment by JamesKingWork** [comment]
Demo: ![dynamic_scripting](https://user-images.githubusercontent.com/54139864/142455617-702b74c1-ca98-4a4d-9f63-ae52bdf160ca.gif)

**Comment by JamesKingWork** [comment]
I think this ticket is complete @ThomasLohnert ?

**Comment by ThomasLohnert** [comment]
It is, I just added the rework label to signify that rework was done as part of completing the ticket (which we cared about at one point from a PM point of view)
