### ISSUE TITLE
SANS Group: 17T (Birmingham) Magnet in IBEX

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6850]
As a scientist in the SANS group I need to be able to control the 17T (Birmingham) magnet in IBEX

## Acceptance Criteria
1. There is an IOC for the magnet, along with associated tests
2.  There is an OPI for the magnet, along with appropriate tests

## Notes
1. There has been a proposal accepted which will need beamtime in 2022
2. Whilst this is a cryogenic magnet with extremely similar software to the HIFI Cryomagnet, this one is interacted with via serial protocol

**Comment by KathrynBaker** [comment]
There is now a file in the manuals section simply titled `Birmingham 17T magnet`. Most of this is straightforward stream commands, there is the need for an extra one before setting a value, there are a couple of values that are sent in the same reply, and there is calculation to convert a value into a percentage, all detailed in the PDF that isn't the RS232 protocol one in the manuals folder.

**Comment by KathrynBaker** [comment]
Not needed for cycle 2021/2 but likely to be needed early in the 2022 cycles (before summer) - criteria adapted to reflect this

**Comment by KathrynBaker** [comment]
The experiment is due around the end of July

**Comment by JackEAllen** [comment]
Experiment is planned to take place on the 24th July and they would like to test it at least a couple of weeks in advance so a rough deadline for this is maybe 8th July.

**Comment by JackEAllen** [comment]
* Support: https://github.com/ISISComputingGroup/EPICS_17T_Birmingham_Magnet/tree/6850_17t_birmingham_magnet

**Comment by Tom-Willemsen** [comment]
Emulator has been tested via loopback on office moxa from the old labview driver. Still needs to be tested against hardware, which I understand is planned as part of https://github.com/ISISComputingGroup/IBEX/issues/7107

**Comment by JackEAllen** [comment]
Pressure for testing this is now off. When arranging time to test, I was informed that they forgot to inform us that the experiment had been cancelled and that the 17T Birmingham Magnet is not required until November and that the magnet should arrive on site in October.
