### ISSUE TITLE
Beckhoff: Meeting to discuss updating PLC code + tcioc + TWINCAT in the future

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6852]
We should have a meeting with the motion team to discuss how we roll out and handle updates to the PLC code (tpy file standards etc) and updates in tcioc. 

### Acceptance Criteria
- [ ] Meeting is had
- [ ] It is documented how we handle updates to PLC code and so on
- [ ] If a mechanism is needed for this a ticket is created for the implementation of this

**Comment by rerpha** [comment]
Meeting was had, the outcome is that there is now a document (which i believe I can share with the group) about updating PLC code. From our point of view we are still going to release as normal and therefore not much needs to change from us. The PLC code will follow semantic versioning. The document is still being written but will outline steps for us to take in order to update tcioc alongside the PLC code. I pushed that it should be backwards compatible and that if the interface changes a major version number should be incremented - minor & patch are going to be reserved for "invisible changes" ie motion logic that isn't exposed via OPC and so on.

**Comment by DominicOram** [comment]
Can you put a link to the document somewhere on the wiki? I believe it is in sharepoint so people will need to log in and ask permission to view it, which is fine.
