### ISSUE TITLE
SQUISH Test: Creating Squish tests for Ticket 6568

### ISSUE THREAD

**Issue by daryakoskeroglu** [ISISComputingGroup/IBEX#6853]
As a developer/ IBEX GUI user, I want to have tests for the new right click menu to add block from "beam information" tab of Beam Status perspective

### Acceptance Criteria

- [ ] There are Squish tests for [#6568]

**Comment by daryakoskeroglu** [comment]
PR: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/110
Release Notes PR:  https://github.com/ISISComputingGroup/IBEX/pull/6876

**Comment by Adam-Szw** [comment]
Testing method:
- master branch of GUI, built using build.bat
- master branch of ibex server (EPICS directory)
- checked out squish tests ticket branch
on a freshly-reinstalled Squish:
- file -> open test suite -> squish tests folder -> check all tests
- manage AUT -> selected  Dev/ibex_gui/built_client
- press the button to start the test

tst_verify_saved_block_info_is_correct_in_blocks currently fails with following error
![image](https://user-images.githubusercontent.com/60976405/159340204-442cee0c-0b5f-499e-bb6f-bbfd9b73a0cc.png)

tst_verify_pv_address_in_log_plotter passes with following results
![image](https://user-images.githubusercontent.com/60976405/159340689-0596bb2f-2ad8-43e5-b66e-cf0ab95e1c76.png)

Other than that - mostly code organisation - some things should be moved to helper methods to help clarity

**Comment by daryakoskeroglu** [comment]
The reason why it cannot recognize the label is because the label name includes the value of that variable we are trying to right-click on while performing testing, which is Beam Current in this case. As the beam is on right now, Beam Current is constantly changing which makes it impossible for Squish to recognize the label with the method in the tests. I will investigate this and try to find another way to make Squish recognize the Synchrotron Panel labels without variable values.

**Comment by daryakoskeroglu** [comment]
![image](https://user-images.githubusercontent.com/56968931/166908308-4a2bca01-f54a-4436-a304-a5f2da3c6ad4.png)

**Comment by daryakoskeroglu** [comment]
Fixed the problem.
Here is the screenshot of the test results:
![image](https://user-images.githubusercontent.com/56968931/166908418-4bea110a-a370-437c-88f3-4ac5652b60ef.png)

Changes that were made:

1. Created `:Synchrotron.Current_Label` to use instead of `:Synchrotron.0.00_Label`, as the old label was recognized with the value of the Beam Current (which was 0.00 in the time when the tests were created). Now, instead of trying to match "0.00" caption to find the label, Squish is using something called "The Catch-All * Descriptor" which means that for all objects, no matter what their caption is, other properties will be used to find the label.
2. Created `:BeamCurrent:Menu` to use instead of `:0.00_menu`, for the same reasons above. It's container is pointing at  `:Synchrotron.Current_Label`.
