### ISSUE TITLE
Beckhoff & MDT: install XAR tools 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6859]
As a developer I would like the Beckhoff XAR tools (required to use Beckhoff PLCs) to be installed when deploying a windows 10 image to an instrument. This means that I can talk to a Beckhoff out-of-the-box. 

### Acceptance Criteria
- [ ] XAR tools are added to the list of software that gets put into a Windows 10 VHD 

### Extra Information
A copy of the XAR tools installed on IMAT, LARMOR etc can be found at `<public share>\third_party_installers\special_drivers\Beckhoff`

**Comment by FreddieAkeroyd** [comment]
For review see NDXDCLAB as just installed

**Comment by rerpha** [comment]
Brilliant, thanks
