### ISSUE TITLE
Beckhoff: use velocity from controller

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6861]
As a developer I would like to use the SP velocity from a controller rather than having to input this information manually when commissioning. 

### Acceptance Criteria
- [ ] It is decided how we go about setting the velocity from a Beckhoff controller and which field to use
- [ ] this is implemented in the motor record logic.

### Extra Information
Some information exists in the ST struct already, we may be able to use these fields.

**Comment by rerpha** [comment]
tried to do this, it#s not as simple as just polling the velocity in the poll() func

**Comment by rerpha** [comment]
i think this may be because we're autosaving VELO

**Comment by FreddieAkeroyd** [comment]
currently you would probably need to remove VELO from autosave and then create an extra PV that reads it from the controller during PINI and sets VELO on the motor record. I am not sure how hard it is to get the motor record to do this itself,  it may not every query the device for such and adding this would make it less generic.

**Comment by rerpha** [comment]
> currently you would probably need to remove VELO from autosave and then create an extra PV that reads it from the controller during PINI and sets VELO on the motor record. I am not sure how hard it is to get the motor record to do this itself, it may not every query the device for such and adding this would make it less generic.

https://github.com/ISISComputingGroup/EPICS-ioc/compare/tc_get_velo_at_startup?expand=1 seems to work - does this look suitable? Autosave looks like it can even be left on for now, i'm guessing this is because of the PINI which would happen afterwards.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/708 seems to work reliably. It's slightly unorthodox but the motor record doesn't really seem to support any other means of doing this so I don't think it's too untidy

release notes https://github.com/ISISComputingGroup/IBEX/pull/7254
