### ISSUE TITLE
Handover: LSi Correlator (SANS-DLS)

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6871]
As a developer I would like to better understand how the LSi Correlator (for SANS-DLS experiements) is supported in IBEX, so that I am well-positioned to take on its future support and development.

### Acceptance Criteria

- [x] Any known suggestions for improvement or enhancement are documented as tickets and listed below in a comment.
- [x] @JackEAllen is briefed on the LSiCorrelator and is comfortable acting as a component steward for the device
- [x] Scientists are aware that @JackEAllen is now looking after the device
- [x] Could run through one or two of the small tickets below

### Extra Information

Dev manual link: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/LSi-Correlator
Support repository: https://github.com/ISISComputingGroup/EPICS-LSICorrelator
IOC directory: https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/LSICORR
PCASPy: https://pcaspy.readthedocs.io/en/latest/

Outstanding work on correlator IOC to complete:

- https://github.com/ISISComputingGroup/IBEX/issues/6828
- https://github.com/ISISComputingGroup/IBEX/issues/5426
- https://github.com/ISISComputingGroup/IBEX/issues/5304
- https://github.com/ISISComputingGroup/IBEX/issues/5197
- https://github.com/ISISComputingGroup/IBEX/issues/4918

**Comment by JackEAllen** [comment]
To review, please see [THIS PR](https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/11) for instructions on how to test
