### ISSUE TITLE
Calibration File updates November 2021

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6879]
As a user of RhFe sensors at ISIS I want to be able to use the latest set of them and so have access to the associated calibrations

## Acceptance Criteria
- [x] A method of converting from .curve to a calibration file has been created (if possible automate, otherwise instruction on the wiki for doing it manually)
- [x] The most recent 10 sensors (F850, F849, F848, F847, F846, F764, F763, F762, F760, F774; see email in experiment controls inbox from 4/11/2021 for the first 9 and 8/11/2021 for F774) have all been added to the appropriate repo (instructions at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files) ready for the next deployment

**Comment by rerpha** [comment]
Looks like .curves are different to .dats so some logic may be required - temp/resistance looks like it's swapped column numbers between them, and there are a couple of other things in the header that will need to be ignored

**Comment by daryakoskeroglu** [comment]
Conversion script PR: https://github.com/ISISComputingGroup/ibex_utils/pull/120
Added new calibration files to  http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/common.git repo

**Comment by daryakoskeroglu** [comment]
Calibration Files wiki page [https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files] is updated

**Comment by JackEAllen** [comment]
> Conversion script PR: [ISISComputingGroup/ibex_utils#120](https://github.com/ISISComputingGroup/ibex_utils/pull/120) Added new calibration files to http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/common.git repo (calibration repo will need updating after the review)

Looks good! 
I've left some feedback on the .curve converter script to merge in with the .dat converter script to follow a DRY methodology.
I can see that the most recent 10 sensors (F850, F849, F848, F847, F846, F764, F763, F762, F760, F774 have all been added to [Control-SVCS](http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/common.git repo) 👍

**Comment by daryakoskeroglu** [comment]
Release Notes PR: https://github.com/ISISComputingGroup/IBEX/pull/6933

**Comment by JackEAllen** [comment]
Conversion script PR has now been merged in along with corresponding release notes and new calibration files have been added to control SVCS](http://control-svcs.isis.cclrc.ac.uk/gitroot/instconfigs/common.git repo)
