### ISSUE TITLE
FRIDAY (Day only) 19th November 2021

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6880]
As a member of the IBEX team I want to take the chance to have a "Friday"

## Acceptance Criteria
- [ ] We spend the 19th of November working on Friday tickets (short ones)
- [ ] There is a zoom meeting open all day (so that the office can be connected with any remote people, and they can connect with each other - cameras can be off, mics can be silenced, but it can provide a 'room' that we can interact in)
- [ ] As many as are comfortable/available should be in the office

**Comment by DominicOram** [comment]
I can bring in cake/pizza!

**Comment by rerpha** [comment]
![test](https://media.giphy.com/media/60zLQKKcmEbE4/giphy.gif)

**Comment by DominicOram** [comment]
Yes, we did this. There was pizza. Given that a lot of the Friday tickets were pointed themselves I'm going to remove the points on this to avoid double pointing.
