### ISSUE TITLE
Simulated Motor: Moving after setting MRES fails

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6881]
When using a simulated motor the first move after setting an MRES fails. e.g. the following do not work:
* MRES -> MOVE
* MRES -> JOG

but the following (2nd move) will work:
* MRES -> MOVE -> MOVE

It appears you can also somehow get the simulated motor out of this state but I haven't worked out exactly how. I spent half a day debugging and found that adding print statements/breakpoints into the motor code would fix the problem and so continuing to debug will be hard. Given that this has only been seen on simulated motors and is a known problem I stopped digging any further.

## Acceptance criteria 
- [ ] Setting an MRES and then moving a simulated motor works first time

**Comment by FreddieAkeroyd** [comment]
This only fails for me if VAL/DVAL is 0 when I set MRES, is that the same for you?

**Comment by FreddieAkeroyd** [comment]
The above two PRs look to fix it on my machine, but may not in general - it does seem intermittent sometimes.
