### ISSUE TITLE
WISH Magnet: Correct state machine behaviour of Non-Persistent mode

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#6891]
As an instrument scientist or technician, I would like the control of the Oxford Instruments 10T cryomagnet to behave in the correct way when running in non-persistent mode.  A fault with state machine logic in the IOC was discovered during testing.

### Acceptance Criteria

1. When set to non-persistent mode, the magnet control behaves in the correct way

### Notes:

The magnet IOC is used by many other instruments who mainly run in persistent mode.  This works well, and is the most commonly used (and tested) mode.  Non-persistent mode is used less often, but most extensively by WISH, which is why the bug was discovered while testing the hardware during migration.

The state machine is written in SNL.

These are the findings from the testing, written by the technician (AJ):

When going from one persistent setpoint to a second persistent setpoint (works fine)
1. The power supply ramps the leads to the current that is persisted in the magnet (which IBEX reads from the power supplies’ memory).
1. The switch heater is turned on.
1. The power supply ramps the magnet to the new setpoint.
1. The switch heater is turned off.
1. The power supply ramps the leads to zero.
 
When going from a persistent setpoint to a non-persistent setpoint (works fine)
1. The power supply ramps the leads to the current that is persisted in the magnet (which IBEX reads from the power supplies’ memory).
1. The switch heater is turned on.
1. The power supply ramps the magnet to the new setpoint and leaves the heater on.
 
When going from a non-persistent setpoint to a non-persistent setpoint (doesn’t work correctly)
1. The power supply ramps the magnet to the last recorded persistent current (IBEX says “Set PSU to match magnet), which is zero if persistent mode has not been used yet. This should not happen, and makes no sense as the magnet is inherently already matched to the power supply as it is in non-persistent mode.
1. IBEX sends the “Heater on” command and shows “Turn heater on & wait” which does nothing as the heater is already on. This should not happen
1. The power supply ramps the magnet to the new setpoint and leaves the heater on.
 
When going from a non-persistent setpoint to a persistent setpoint (doesn’t work correctly)
1. The power supply ramps the magnet to the last recorded persistent current (IBEX says “Set PSU to match magnet), which is zero if persistent mode has not been used yet. This should not happen.
1. IBEX sends the “Heater on” command and shows “Turn heater on & wait” which does nothing as the heater is already on. This should not happen
1. The power supply ramps the magnet to the new setpoint.
1. The switch heater is turned off.
1. The power supply ramps the leads to zero.

**Comment by FreddieAkeroyd** [comment]
This is the IPS. It is ultimately doing the correct thing, but with some unnecessary steps that make things take longer than they should.

**Comment by davidkeymer** [comment]
Pull requests:

[IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/771)
[Test Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/588)

[Wiki Page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Oxford-Instruments-IPS)

**Comment by pheest** [comment]
Are we aware of a dependency on the LabVIEW runtime 2018 being installed, in order to build the IOC test framework?
