### ISSUE TITLE
LSi Correlator : GitHub Action to Run Pylint Checks

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6892]
As a: Developer

I would like to implement a linting check using GitHub actions for the LSI Correlator repository. 

Having Linting checks within a GitHub action will aid in improving consistent programming standards throughout the repository by following PEP 8 and possibly PEP 257 to check docstring format.

This will likely have a large upfront cost in errors and warnings, but should still be done to allow developers to fix lint errors and warnings on a touch code basis. 

### Acceptance Criteria
- [x] GitHub action to run pytlint checks on remote branches.
- [x] GitHub action reads from a `.pylintrc` file so we can easily modify rules if needed

---

#### _Why it is needed?_

Enforcing PEP conventions will allow for a more standardised codebase while also making the codebase more readable for new developers.

Including PEP will remove the need for code styling to be included in the code review stage, allowing developers to focus on what really matters. It is then up to the developer to make sure all pylint checks pass for code modified before a branch is ready for review to merge into master branch.

#### _Where required files/links are_
**Repository locations:**
- https://github.com/ISISComputingGroup/EPICS-LSICorrelator

**Required files:**
- [x] `.pylintrc`
- [x] `.github/workflows/pylint.yml`

**Comment by JamesKingWork** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/11

**Comment by JackEAllen** [comment]
Please see [PR](https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/12) for testing guidance.
