### ISSUE TITLE
SANS2D: Test Collision avoidance(hardware testing)

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6896]
Test Collision avoidance for SANS2D vacuum tank

**Comment by RaiBishal** [comment]
Tested following things:
- When not in motion all motors in Vac tank OPI is in `pause` state
- When the distance between Front detector and Front baffle is <= 1050 movement is inhibited and error message is displayed
- When the distance between Front Baffle and Rear baffle is <= 210 movement is inhibited and error message is displayed
- When the distance between Rear Baffle and Rear Detector is <= 350 movement is inhibited and error message is displayed
- When the motor is stopped using `STOP MOTION` motor goes back to `pause` state

Results
Collision avoidance itself did work and motion was allowed and inhibited when appropriate, but other issues were discovered #6910.

**Comment by JamesKingWork** [comment]
Looks good! We should probably propose https://github.com/ISISComputingGroup/IBEX/issues/6910 to be done soon so we don't lose the ability to reproduce it
