### ISSUE TITLE
WISH: Update converted instrument script with support for PEARL Pressure Controller

### ISSUE THREAD

**Issue by daryakoskeroglu** [ISISComputingGroup/IBEX#6897]
As an instrument scientist I would like my base instrument script to support the PEARL Pressure Controller by completing the conversion of the original OpenGENIE functions. The current converted script does not provide this support as the driver for the controller has not yet been completed.

See the ticket here: [#6694]

### Acceptance Criteria
- [ ] finish conversion of routines file
- [ ] changes are documented [here](https://github.com/ISISComputingGroup/IBEX/wiki/WISH-Instrument-Details)

### Notes
- See comments below

**Comment by davidkeymer** [comment]
Will check with ISs whether or not the PEARL Pressure Controller functions defined in the OpenGENIE routines files are __actually__ required to be converted and present in the equivalent GeniePython `inst.py` file.  It may be that the functionality is already natively provided by GeniePython (which I suspect it is).

**Comment by rerpha** [comment]
Not strictly converted directly, but function for setting pressure which deals with runcontrol and max/min/nominal pressure is in inst.py and scientists are happy
