### ISSUE TITLE
Script Generator: Behaviour on invalid action

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6900]
As a script generator user, I would like to be able to configure whether an invalid action is skipped over or paused on.

### Acceptance Criteria

- [x] A user can configure whether invalid actions are skipped over or paused on.
- [x] Warning at the start of the script run is corrected to specify how invalid actions will be handled (if https://github.com/ISISComputingGroup/IBEX/issues/6899 is complete already)
- [x] Squish tests cover this behaviour or at the least the steps for the squish tests are written and stored in the system tests repo

### Extra Information
_Why it is needed?_
There may be cases where when running overnight we don't want a script to stop running and other cases where due to the nature of a script where one step could rely on the previous step we wouldn't want to skip onto the next one.

_Where required files/links are_
Code and unit tests to be implemented in https://github.com/ISISComputingGroup/ibex_gui projects: uk.ac.stfc.isis.ibex.scriptgenerator.dynamicscripting and uk.ac.stfc.isis.ibex.scriptgenerator.tests
System tests repo: https://github.com/ISISComputingGroup/System_Tests_UI_E4

**Comment by JamesKingWork** [comment]
As of https://github.com/ISISComputingGroup/IBEX/issues/6841 the script generator pauses on an invalid action

**Comment by ThomasLohnert** [comment]
Preferred default for Muons is skip, not pause.
