### ISSUE TITLE
HIFI-CRYOMAG: CP2800 communication issues

### ISSUE THREAD

**Issue by LilithCole** [ISISComputingGroup/IBEX#6901]
## Where?
The CP2800 compressors are currenty not communicating correctly, although they supposedly functioned correctly in the past. 

## Reproducible?
yes

### To Reproduce
- Attempt to connect to one of the two CP2800 compressors on NDXHIFI-CRYOMAG to read elapsed minutes or power status.

## Acceptance criteria 
- [ ] elapsed minutes and power status can be read from a CP2800 with no errors in the log.

**Comment by LilithCole** [comment]
IOC has been tested and is currently running with the streamdevice patch on NDXHIFI-CRYOMAG.

**Comment by LilithCole** [comment]
PRs:

Streamdevice:
https://github.com/ISISComputingGroup/EPICS-StreamDevice/pull/13
Release Notes:
https://github.com/ISISComputingGroup/IBEX/pull/6925

**Comment by ThomasLohnert** [comment]
PRs have been merged, should this be moved to review complete?

**Comment by daryakoskeroglu** [comment]
> PRs have been merged, should this be moved to review complete?

Yes, will do this now!
