### ISSUE TITLE
Repository README Files: Modify 

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#6903]
As a: developer

I would like to add links to the relevant WIKI information to some repos and add links on some WIKI pages back to those repos to allow me to easily find relevant information I may need to tackle a given issue.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] URLs added to a repositories README.md to relevant recourses where applicable:
    - [ ]  WIKI Pages
    - [ ] Relevant file locations such as manuals
    - [ ] Locations of other relevant repositories.
- [ ] URLS on WIKI pages linked too in repositories back to the relevant repositories. 

### Extra Information
_Why it is needed?_
This issue was created in response to discussions which took place in the retrospective meeting which notes can be found for in the WIKI [HERE](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Retrospective-notes-2021.11.17).

_Where required files/links are_
Repositories modified in response to retrospective:
_add here as modified_
**PEARL Pressure Controller**
- [x] https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/2
- [x] https://github.com/ISISComputingGroup/EPICS-ioc/pull/656
- [x] https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/24
- [x] https://github.com/ISISComputingGroup/EPICS-jaws/pull/16
- [x] https://github.com/ISISComputingGroup/EPICS-Triton/pull/4
- [ ] https://github.com/ISISComputingGroup/EPICS-Flipprps/pull/4

**Comment by JackEAllen** [comment]
Just adding documentation for the Pearl Pressure controller for today:
- https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/2
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/656

We could keep this issue open to track where documentation has been added so far for the time being. 

The next time this issue is looked at, we should aim to try adding minimum documentation to another type of repository to see if the same format used for the Pearl Pressure controller works for other repositories.

**Comment by JackEAllen** [comment]
To review, please look at the below PR's and tick checkboxes inside issue description
- https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/2
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/656

**Comment by JamesKingWork** [comment]
Can we add links to the support and ioc modules at https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details#note-pressure-cell-controller

**Comment by JackEAllen** [comment]
> Can we add links to the support and ioc modules at https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details#note-pressure-cell-controller

Should be able to find changes [HERE](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details#pearl-notes)

**Comment by JackEAllen** [comment]
# Motion Set Points
To Review, please look at the below PR's and tick checkboxes inside issue description
- https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/24

**Comment by JackEAllen** [comment]
# Jaws
To Review, please look at the below PR's and tick checkboxes inside issue description
- https://github.com/ISISComputingGroup/EPICS-jaws/pull/16

**Comment by JackEAllen** [comment]
# Triton
To Review, please look at the below PR's and tick checkboxes inside issue description
- https://github.com/ISISComputingGroup/EPICS-Triton/pull/4

**Comment by JackEAllen** [comment]
CRISP Spin Flipper
To Review, please look at the below PR's and tick checkboxes inside issue description
- https://github.com/ISISComputingGroup/EPICS-Flipprps/pull/4
- [WIKI](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CRISP-Spin-Flipper) - Added url to CRISP spin flipper repo

**Comment by JackEAllen** [comment]
Once the above changes have passed review for CRISP spin flipper, Triton, Jaws, and motion set points, please remove the issue from the project board to be picked up again as a "Friday" ticket to further document repos.
