### ISSUE TITLE
SANS2D: Galils inside Vacuum tank

### ISSUE THREAD

**Issue by RaiBishal** [ISISComputingGroup/IBEX#6910]
## Where?
**SANS2D.**

## Description
When testing the new collision avoidance for SANS2D vacuum using GALILMUL with @DominicOram some issues related to galils were discovered. The collision avoidance itself is working fine.

There was CAEN related issue as well which was causing it to inhibit detector motion but I have not included it here.

### **Following events occurred in particular order**

16/11/2021

1. Front detector and Rear detector motor stalling
2. We were able to move rear detector without stalling after changing the `.VELO` speed to homesepeed
3. Dom discovered that `_STEPSMOOTH_MON` was not set correctly, so we set it to `16` as it was in SECI
4. Rear detector was homed and its speed was set to original speed
5. Rear detector movements seemed to work fine 
6. Front detector moved fine after setting `_STEPSMOOTH_MON` to correct value

We did not home Front Detector this day, Only the Rear detector was homed.

17/11/2021
1. Front Detector stalling again
2. Rear Detector stalling again
3. Front detector and Rear detector moving towards negative direction when the SP was set to positive
4. When trying to home Front Detector it started homing multiple times so we restarted the IOC which eventually fixed the (infinite?) homing loop
5. We homed the Front Detector
6. Front Detector movements worked fine
7. We homed the Rear Detector
8. Rear Detector movements worked fine

## How?
when testing Collision Avoidance in SANS2D

## Reproducible?
Maybe?

### To Reproduce
Not sure, seem to happen ocassionally

## Acceptance criteria 
- [ ] Discussion
- [ ] Figure out the cause of the issue
- [ ] Document it if necessary

**Comment by FreddieAkeroyd** [comment]
The `IT` command also needs to be sent, there is not a PV for this

**Comment by FreddieAkeroyd** [comment]
Remove some duplicated code that is also in incorrect place https://github.com/ISISComputingGroup/EPICS-ioc/commit/914fa9b5d464aa0684195dc6ad19295967a122d1

**Comment by FreddieAkeroyd** [comment]
See #6919

**Comment by FreddieAkeroyd** [comment]
I think this is done?

**Comment by RaiBishal** [comment]
@FreddieAkeroyd Yes move it to review now.
