### ISSUE TITLE
NIMROD: set up motion setpoints for camera 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6932]
As a NIMROD scientist I would like to have motion set points so that my camera is in/out of the beam and can be controlled with a single PV to do so. 

### Acceptance Criteria
- [x] Positions for in/out are determined by moving the camera in/out of the beam and measuring
- [x] Motion setpoints are set up with this in mind
- [x] Information for this is added to the [NIMROD instrument details page](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details)

**Comment by rerpha** [comment]
OK, Motion setpoints have been set up for rough values, though they may fine tune these when the beam comes back online to get it really accurate. Currently IN is -20mm and OUT is -306mm (roughly on the lower limit switch) 

To review: 
- Check [motion setpoints](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motion-Set-points) config for `NDXNIMROD` and make sure it looks correct - you could checkout NDXNIMROD and start an ibex server to see if it loads in the positions with a device screen with the motion setpoints name `CAMERA`
- Check instrument details page and make sure it makes sense

**Comment by JackEAllen** [comment]
NDXNIMROD seems to look good from testing in sim mode and changes to instrument details page make sense. Happy to mark this issue as complete 👍
