### ISSUE TITLE
CS-Studio/GUI: sort out max_array_bytes

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6937]
Our local CS Studio is limited to 65535 bytes on an array, i am not sure about the ibex gui. This causes an issue when viewing some large waveforms
``` 
ibex gui

$ git grep array|grep max
base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini:org.csstudio.platform.libs.epics/max_array_bytes=65536
base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/ca/ca.xml:                max_array_bytes="20000000" />
base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/ca/ca.xml:                max_array_bytes="16384" />-->
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevAdditionalInterpreterSettings.java:                   preferenceService.getString(PREFERENCE_STORE_ID_FOR_EPICS_LIBS, "max_array_bytes", "16384", null);


cs studio

$ git grep array|grep max

Config/css_rap.ini:org.csstudio.platform.libs.epics/max_array_bytes=160000
Config/settings.ini.in:org.csstudio.platform.libs.epics/max_array_bytes=460000
Source/workspaces/org.csstudio.isis.product/plugin_customization.ini:org.csstudio.platform.libs.epics/max_array_bytes=460000
plugin_customization.ini:org.csstudio.platform.libs.epics/max_array_bytes=65536
plugin_customization.ini:org.csstudio.diirt.util.core.preferences/diirt.ca.max.array.size=65536
```
note that values are not consistent!

## acceptance criteria

max_array_bytes is consistent across installations

**Comment by FreddieAkeroyd** [comment]
I propose to increase them all to 20000000

**Comment by rerpha** [comment]
should we make this more consistent everywhere we specify it? for example, the blockserver start cmd batch it's set to 1000000, this differs in other parts of the server. I know this ticket is just for the gui/css but was wondering if we had plans to change it everywhere

**Comment by FreddieAkeroyd** [comment]
There is no harm in doing that, though it is probably not needed for the blockserver. I was updating the GUI values and making it consistent as we have had cases when large areaDetector arrays did not display due to picking up the wrong value. The blockserver will never need to process such large arrays, so would not suffer this particular issue, but i guess needs at least the current value to handle some of its char arrays for blocks and configurations?
