### ISSUE TITLE
RIKEN: IOC & OPI for Transtechnik PSU - Steering Magnet control

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#6942]
As a muon scientist I would like to control and monitor the Transtechnik power supplies for the steering magnets on the RIKEN front-end.

#### Acceptance Criteria
1. The Transtechnik IOC must allow me to control the following variables:
   * voltage
   * current
   * HV status
   * Local/Remote Status
1. The OPI must display the following fields:
   * voltage
   * current
   * HV status
   * Local/Remote Status
   * Fault status
   * Interlock status
1. I can control the Transtechnik PSU via genie_python scripts.
1. IBEX must support at least 2 Transtechnik IOC instances.

#### Notes
1. The RIKEN front-end will feature 2 Transtechnik PSUs.
1. IBEX should support at least 2 Transtechnik IOC instances.
1. These PSUs are used in the EPB and are controlled by Vsystem, maintained by the Accelerator Controls group.  It may be possible to convert or adapt the Vsystem driver to EPICS.  RB in said group has been contacted for more information.
1. It is currently unknown whether or not an EPICS driver already exists.
1. At the time of writing, the two units to be installed are (believed to be) on the mezzanine area above the DAC in R55.

**Comment by davidkeymer** [comment]
A reply has been received from RW in the Accelerator Controls Group (edited version follows):

> We control those PSUs via RS-422 serial connection. ...There is an addressing phase, followed by a command phase. The commands are very similar to the older Danfysik PSUs...
> ...A manual will be useful as it will list all of the available status bits, we only care about a few in the control system.

He also sent the source code for the communications part of the VISTA driver.  File uploaded to the [RIKEN FE area](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/RIKEN%20FE/TransTechnik%20PSU%20VISTA%20comms%20driver%20-%20ttk_function.cpp) of the ICP Discussions Sharepoint site.

**Comment by rerpha** [comment]
Do we know the model of this device @davidkeymer  ? if so, do we have a manual?

**Comment by daryakoskeroglu** [comment]
> > Do we know the model of this device @davidkeymer ? if so, do we have a manual?
> 
> @rerpha No and no. I can enquire, unless @daryakoskeroglu has already. I shall, however, try to finalise the user requirements and therefore the acceptance criteria for this ticket.

@davidkeymer I emailed Richard H regarding the questions and CC'd  you on the email.

**Comment by daryakoskeroglu** [comment]
Received the manual and added to the shares. Can be found here: \\isis\shares\ISIS_Experiment_Controls\Manuals\Transtechnik Power Supply

**Comment by Tom-Willemsen** [comment]
We've now acquired a different manual, which seems to match the hardware much more closely (and detail the meanings of the status bits). It's been added to the usual manuals share under `Transtechnik Power Supply\Mk2_Commands_Proposal.doc`.

**Comment by Tom-Willemsen** [comment]
Hardware testing arranged for 11:00 28/07/2022

**Comment by Tom-Willemsen** [comment]
Power supply has been tested in DC Lab with Richard H.

Things that came out of testing:
- We tested as many interlock bits as possible against the hardware, all worked and were labelled correctly. Based on this I have reasonable confidence that the status bits are correct.
- Power supply reads and sets of voltage/current/power are correct
- We can reduce inrush time from 30s to 20s (testing with device showed that actual inrush takes ~14s)
- The status bit reporting from the power supply can report all interlocks cleared, but the power supply may still need a reset command sending (the status bits go away when the interlock is *physically* cleared, but the PSU still needs a reset after this).
  * I'll note this on the wiki
- The waiting logic is correct, it could potentially be optimised in certain cases (e.g. waiting a bit less after a reset/power off than after a power on), but the current logic is safe too.
