### ISSUE TITLE
CRISP, IMAT, MARI, SELAB: disk space cleanup before we all leave

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6944]
the above 3 instruments (as well as NDXSELAB) were showing nagios warnings about disk space. the dbs need to be truncated/logs need to be cleared

### Acceptance criteria
- [ ] above instruments have sufficient disk space
- [ ] IOCs that are logging frequently are investigated
- [ ] nagios disk space time to full warnings are no longer

**Comment by KathrynBaker** [comment]
Those instruments are no longer showing warnings, so all looks good going into the holiday season
