### ISSUE TITLE
Cryogenics: Implement the Enhanced Cryostat Control as IOC logic

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6947]
As someone using cryogenics at ISIS (especially on EMU)  I need enhanced cryostat control scripts, so that systems running under pressure control will heat and cool automatically to the desired temperature, automatically adjusting the gas flow and heater for optimal running. 

### Acceptance Criteria
- [x] The python test script is enacted at the IOC level
- [x] ~~There is a desire to supply the definition of the pressure law as a Python function~~
    - Implemented as a linear interpolation using a text file similar to eurotherm ramp files. 
- [x] The following values should be user configurable:
   - [x] CUTOFF_POINT in Kelvin
   - [x] PRESSURE_SETPOINT_MIN in mbar
   - [x] PRESSURE_SETPOINT_MAX in mbar
   - [x] CONSTANT_PRESSURE_VALUE in mbar
   - [x] DELAY_BETWEEN_SETS in ms
   - [x] TEMP_SCALE
   - [x] PRESSURE_SET_BLOCK
   - [x] TEMP_BLOCK
   - [x] TEMP_SET_BLOCK
- [ ] PID values for the Mercury Pressure Control need to be sent to the device and managed in a similar fashion to the TPAR files
  - This is being implemented as a separate ticket.
- [x] Find a way to disambiguate this clearly from the LBC logic as they are both doing very similar things (controlling NV pressure based on temperature)
- [x] Ensure this logic and the "little blue cryostat" are mutually exclusive with each other

### Notes
- The design from #6729 is available at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC-Enhanced-Cryostat-Control and #6279 is likely to have other useful information
- The final script to be used to ensure the above is available in the EMU scrips as `cryo_control_test_v3.py`
- This is likely to need a state machine
- There is a test report available, which should be read in conjunction with the previous tickets to ensure that the requirements are understood well

## To Review
- [ ] https://github.com/ISISComputingGroup/EPICS-MercuryiTC/pull/22
- [ ] https://github.com/ISISComputingGroup/EPICS-ioc/pull/723
- [ ] https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/563
- [ ] https://github.com/ISISComputingGroup/ibex_gui/pull/1472
- [ ] https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/153
- [ ] https://github.com/ISISComputingGroup/EPICS-upgrade/pull/68
- [ ] https://github.com/ISISComputingGroup/IBEX/pull/7334

**Comment by KathrynBaker** [comment]
Original content of the ticket:

As someone using cryogenics at ISIS (especially on EMU) I need enhanced cryostat control scripts, so that systems running under pressure control will heat and cool automatically to the desired temperature, automatically adjusting the gas flow and heater for optimal running.

## Acceptance Criteria
- [] Implement the logic designed and tested within https://github.com/ISISComputingGroup/IBEX/issues/6729
## Notes
- Use the previous ticket to find more details if necessary
- The design from https://github.com/ISISComputingGroup/IBEX/issues/6729 is available at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC-Enhanced-Cryostat-Control

**Comment by rerpha** [comment]
ps OPI exists here: https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket6729_enhanced_cryostat_control

more info here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MercuryiTC-Enhanced-Cryostat-Control

**Comment by Tom-Willemsen** [comment]
Clarification from cryogenics, this needs to be separate (but mutually exclusive with) the little blue cryostat logic. I've added the following acceptance criteria to the ticket:

> - Find a way to disambiguate this clearly from the LBC logic as they are both doing very similar things (controlling NV pressure based on temperature)
> - Ensure this logic and the "little blue cryostat" are mutually exclusive with each other

**Comment by ConorMFinn** [comment]
Additional info from cryo seems to suggest that the LBC cryostat is a "Flow" type and the ones for EMU are "VTI" type. This seems like a potentially good way to differenciate the logic
