### ISSUE TITLE
Investigate config checker failure

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6948]
jenkins config tests are failing with
```
Exception occurred while parsing file blocks.xml in configuration Eurotherms as XML
```
the `blocks.xml` file is blank so not valid xml. Find how that happened e.g. was it overwritten, or was there no blocks file (as no blocks) and then e.g. a test or other program trying to open one created a blank file as a result?

## Acceptance criteria

cause understood and tests again passing

**Comment by rerpha** [comment]
looks like it was modified on the 15/12/2021 which was when they were playing around with eurotherms and i had to clear some disk space, so may have been that they created a config but didnt have enough disk space to write the blocks.xml file. If so I don't think there's much we can do about it for next time except keeping an eye on disk space as we are now.

**Comment by KathrynBaker** [comment]
Config checker has passed, calling this done
