### ISSUE TITLE
Device generator: update license year dynamically

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6951]
I would like the device generator and other places where we use a license to update automatically so we don't have to keep updating them. This isn't super important because of implied copyright etc. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [x] We never have to update the year in a license ever again

### Extra Information
We could replace this during 'device generation' - ie put a placeholder in the license then format it when copying

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX_device_generator/pull/19

Took me 5 minutes in my lunch break, please review other things in favour of this, we need to prioritise getting things that actually matter in, this is just something that was keeping me up at night 😄 

to test generate a device and check the LICENSE file in `support\devicename\master\` has the correct year in it.

**Comment by JackEAllen** [comment]
Changes made in https://github.com/ISISComputingGroup/IBEX_device_generator/pull/19 work as expected and have now been merged in so closing this issue.
Hopefully we never have to update the year in a license file ever again 🤞
