### ISSUE TITLE
Release: Create a Release [w/c 17/01/2022]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6955]
As someone invested in the IBEX project I want to create a release so that we have a tested system that can be deployed to systems as appropriate.

### Acceptance Criteria:

- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] We decide where to deploy to and an appropriate deployment ticket is created - see ticket #6956 
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)
- [ ] [Create a ticket to give instrument demos](https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos)
- [ ] Distribute release notes via email [Instrument scientist release email](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Updating-Instrument-Machines#a-new-release)

**Comment by rerpha** [comment]
Point 5 is being done in #6820 so ticking off this ticket

**Comment by JackEAllen** [comment]
[#84](https://github.com/ISISComputingGroup/system_tests/pull/84) has been merged in which should fix system tests moving us on to [testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing).

**Comment by rerpha** [comment]
I think the last step makes more sense to do as part of the same email asking about deploying in #6956 - we will send the release notes with the question

**Comment by ThomasLohnert** [comment]
I'm slightly confused, the actual built releases are in ICP/Releases, but I can't find the release branches for `ibex_gui` and `genie_python` ? (consequently, same for automated release builds https://epics-jenkins.isis.rl.ac.uk/view/Release/) 

What am I missing?

All the rest looks good to me!

**Comment by ThomasLohnert** [comment]
Ok makes sense, sorry just wanted to understand what's going on. Great, I'll call this done then!
