### ISSUE TITLE
IMAT: reinstall EPICS on MCP PC 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6962]
The C: drive on the PC used to control the MCP camera is failing, facilities IT will replace and reinstall O/S but EPICS for MCP/pixelman will need setting up again. Winfried has made a copy of `c:/Instrument` and FIT have recorded the various camera specific ethernet adapter settings    

## Acceptance criteria

- system working as before

**Comment by ChrisM-S** [comment]
Also taken a copy of the archive copying task definition which will probably be lost if this happens.  Looks like there is also a new copying problem which has now appeared since the last cycle so data doesn't reach the archive server currently...
