### ISSUE TITLE
Motors with noisy analogue feedback: find solution

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6975]
When analogue feedback is used the noise on the signal can cause issues as documented in #4670, #4706 and #6740
 
A solution to this is documented in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Smoothing-Motor-Readback, this will not require #6954 or #6808 for the moment.

The solution will initially be used on WISH, but would likely be useful on MERLIN and NIMROD too

## Acceptance criteria

- documentation understandable
-  currrent deployment on MTR0101 and MTR0105 on WISH work

Updating other motors on WISH will be done during WISH deployment

**Comment by FreddieAkeroyd** [comment]
See https://github.com/ISISComputingGroup/EPICS-galil/blob/master/GalilSup/Db/galil_motor_extras.template for code

**Comment by FreddieAkeroyd** [comment]
@davidkeymer will apply to WISH

**Comment by davidkeymer** [comment]
Will configure and test appropriate axes on WISH as part of the review.

**Comment by FreddieAkeroyd** [comment]
Putting in in progress as need to update links as now done a different way

**Comment by FreddieAkeroyd** [comment]
Docs now updated - as it has been tested on wish, probably matter of checking documentation https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Smoothing-Motor-Readback

**Comment by rerpha** [comment]
instructions look good and although still occasionally flickering the WISH jaws look a lot happier than they ever have done.
