### ISSUE TITLE
Squish System Tests: Investigate waiting dialog warnings (Timebox: 2.5D)

### ISSUE THREAD

**Issue by Adam-Szw** [ISISComputingGroup/IBEX#6980]
## About
Squish tests display warning and/or stop execution of tests depending on Squish settings / machine specifics in some tests. As a developer I would like my tests to work reliably regardless of setup so I can confirm functionality of the system. While this currently includes only warnings it could highlight a wider issue with the test environment where for example some tests would fail because machine loads new config too quickly.

## Where?
Squish System tests - specifically most tests in suite_configuration_tests, everywhere that `wait_for_waiting_for_dialogue_to_close()` appears.

## How?
The issue was found during review of ticket https://github.com/ISISComputingGroup/IBEX/issues/6853 where the test would pass for most people, but not on NDW1798. Further investigation revealed that the same problem would cause warnings on the test server.

## Reproducible?
Tricky

### To Reproduce
Run tests from suite_configuration_tests on Jenkins or run the tests yourself on machine that experiences the problem (NDW1798)

## Acceptance criteria 
- [ ] Reason for warnings and/or tests failing is understood
- [ ] Troublesome functionality is fixed

Attached screenshot of warnings on test server and on NDW1798
![image](https://user-images.githubusercontent.com/60976405/150557532-97b0aa3a-b19b-4e78-a02c-51d8a3daf38a.png)
![image](https://user-images.githubusercontent.com/60976405/150557677-3fd59af1-e60b-4869-bec7-59fc6d0b8cd2.png)

**Comment by daryakoskeroglu** [comment]
It is been noticed that imports have multiple warnings in suite_configuartions_test, such as import redefinition warning for importing _wait_for_waitin_for_dialogue_to_close()_ from utilities which is already imported by configuration_dialogues.py . This may show that the test suite is outdated and may need upgrade - which is a possible solution for the issue mentioned in this ticket. Removing waiting function after opening-exiting configuration dialogues is also another solution, as no warnings are shown after testing this solution.

**Comment by daryakoskeroglu** [comment]
Putting this in review so that solutions could be discussed and perhaps create a new ticket for implementing the solution.

**Comment by daryakoskeroglu** [comment]
In today's stand-up meeting, it was discussed that removing _wait_for_waitin_for_dialogue_to_close()_ would be an option to solve the issue as the tests are always give "Never found waiting for update shell to open" warning.

During the process of removing the lines, it was discovered that there is an error in _tst_can_add_edit_and_delete_block_to_current_config_ which doesn't relate to the waiting for dialogue issue. 
PR: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/117

**Comment by Adam-Szw** [comment]
After checking out the branch I had several critical errors for missing files in various tests not modified on this branch. I rebased the ticket onto current master and ran some tests. I stopped the tests after an hour since it was taking too long. Here are the results:
![image](https://user-images.githubusercontent.com/60976405/175355787-dd793036-3672-4a24-9b10-030644b22cee.png)
As you can see, some of the tests are failing.
Could you please make sure to do the following to make sure its not just on my side:
- ensure that you have newest Ibex GUI master
- build said GUI using build.bat thats located in C:\Instrument\Dev\ibex_gui\build
- check out the commit **before** my rebasing to confirm the errors were there
- check out lastest commit to confirm that tests that failed for me also fail
Full log with the errors can be found attached
[report.zip](https://github.com/ISISComputingGroup/IBEX/files/8969358/report.zip)
use option 'import test results' located in top right of test results box in squish to view

**Comment by Adam-Szw** [comment]
I can confirm that the tests are now passing with exception of the test that we expect to fail and have a new ticket for
