### ISSUE TITLE
CHIPIR: Secondary Shutter & Filters on Beckhoff: Create an appropriate st.cmd

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6983]
As a user of CHIPIR I want to continue being able to see whether or not my secondary shutter and filters are in or out of the beam

## Acceptance Criteria
1. An st.cmd exists with appropriate supporting files to run the system is in git ready for deployment

## Notes
1. See for more details: https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details#note-beckhoff
1. This is due to be in use on the beamline on the 16th of March 2022
1. https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Release-Single-IOC should be considered when designing this, or potentially https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Configure-Mini-Inst
1. This should be followed by #6984 and #6985

**Comment by KathrynBaker** [comment]
Given that CHIPIR is still on SECI, we can always look at just giving them a single IOC at the moment, depending on the preferences for the Windows 10 roll out on SECI instruments. Otherwise as it is a single IOC, just the 'nightly' build would be enough rather than the release - they won't be using anything else yet.

**Comment by rerpha** [comment]
on a mini inst? we'll need to include lua as a support module as well, just a thought

**Comment by rerpha** [comment]
Now that #6984 is in review I could just modify the st-common.lua file even further that is on there to exclude all of the motor control stuff, unless we want a more permanent change.

**Comment by rerpha** [comment]
Have modified `\\NDXCHIPIR\c$\Instrument\Apps\EPICS\ioc\master\TC\iocBoot\iocTC-IOC-01\st-common.lua` to disable the motor record loading, this should be sufficient.

**Comment by JackEAllen** [comment]
Happy o put this through, can see changes in `\\NDXCHIPIR\c$\Instrument\Apps\EPICS\ioc\master\TC\iocBoot\iocTC-IOC-01\st-common.lua` to disable the motor record loading.
