### ISSUE TITLE
CHIPIR: Secondary Shutter & Filters on Beckhoff: Install the appropriate files etc.

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6984]
As a user of CHIPIR I want to continue being able to see whether or not my secondary shutter and filters are in or out of the beam

## Acceptance Criteria
1. The appropriate files are installed on CHIPIR
1. An appropriate `mini_inst` with associated `globals.txt` is created

## Notes
1. See for more details: https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details#note-beckhoff
1. This is due to be in use on the beamline on the 16th of March 2022
1. For mini instrument details see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Configure-Mini-Inst
1. https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Release-Single-IOC may be more appropriate
1. #6983 needs to be completed first
1. #6985 will ideally follow this

**Comment by rerpha** [comment]
Will also need to install twincat XAR

**Comment by rerpha** [comment]
- [ ] EPICS copied over
- [ ] TwinCAT XAR installed
- [ ] globals.txt created 
- [ ] startup.txt created

**Comment by rerpha** [comment]
To review check \\Instrument\Settings\config\NDXCHIPIR\configurations for the globals.txt and startup.txt file , check they look about right (ignore MTRCTRL, it needs to be there but wont be doing anything)

**Comment by JackEAllen** [comment]
Happy to put this through, can see globals.txt and startup.txt files respectively in ` \Instrument\Settings\config\NDXCHIPIR\configurations`, TwinCat XAR is visible in the system tray and modified scan rate in `ioc\master\TC\iocBoot\iocTC-IOC-01\st-common.lua`
