### ISSUE TITLE
CHIPIR: Secondary Shutter & Filters on Beckhoff: VI to view in SECI

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6985]
As a user of CHIPIR I want to continue being able to see whether or not my secondary shutter and filters are in or out of the beam

## Acceptance Criteria
1. There is a VI which reads the PVs relating to whether or not these items are in or out of the beam
1. This VI is installed on CHIPIR and added to the SECI configuration

## Notes
1. See for more details: https://github.com/ISISComputingGroup/IBEX/wiki/CHIPIR-Instrument-Details#note-beckhoff
1. This is due to be in use on the beamline on the 16th of March 2022
1. #6983 should be completed first, and ideally #6984 as well

**Comment by KathrynBaker** [comment]
The VIs have been altered, and left flexible for setting up once we know what the PVs are, as such I'm putting this into review, there may need to be some alterations, but that won't be obvious until we get to testing with hardware.

The VIs are in the appropriate place to pull them onto CHIPIR when the time comes, and a copy are in a folder caller `\LabVIEW Modules\Ticket6985 VIs`, which is in our CompGroup area on Kits, to allow for reviewing as appropriate.

**Comment by rerpha** [comment]
Looks good to me, can see where the PVs will need to be input to enable the controls.

**Comment by rerpha** [comment]
Commissioning ticket: https://github.com/ISISComputingGroup/IBEX/issues/7067
