### ISSUE TITLE
Friday

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#6992]
As a developer I would like to have "Friday" quality development time which fundamentally benefits users and developers in the long term.

## Acceptance Criteria
- [x] Pick a date
- [ ] We spend the a day on Friday tasks/tickets
- [ ] There is a zoom meeting open all day (so that the office can be connected with any remote people, and they can connect with each other - cameras can be off, mics can be silenced, but it can provide a 'room' that we can interact in)
- [ ] As many as are comfortable/available should be in the office

### Extra Information
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Friday-Quality-Time

**Comment by rerpha** [comment]
![](https://media1.giphy.com/media/LqzgIzNWDiyFG/giphy.gif?cid=ecf05e47yutdj1ki976ebxif4h9ieiwa6dz3zj8in344oa6y&rid=giphy.gif&ct=g)

**Comment by KathrynBaker** [comment]
Suggesting keeping to just a day on the 11th of March a specifically one day Friday (and yes. that is a Friday!)

**Comment by KathrynBaker** [comment]
I've put a calendar invite in, so I'll take at least some responsibility for it

**Comment by KathrynBaker** [comment]
Friday has now happened, those who could took part. Sending this straight to closed as at least @ThomasLohnert and I were in the wash up at the end of the day having done some Friday type work (and I know others had been too, so I'm not concerned about the points)
