### ISSUE TITLE
TC: $(AXIS) not defined on iocstartup

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6997]
As a scientist I would like my axis config to be loaded correctly by the TC IOC. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] axis.cmd is loaded properly

### Extra Information
`axis.cmd` will get loaded in from `instrument\settings\config\xxxx\configurations\twincat\`, but the actual db that lives in https://github.com/ISISComputingGroup/EPICS-axis or `\support\axis\master\` on a machine is not defined. It is on a Galil IOC, so that may give some hints on what sets it.

**Comment by FreddieAkeroyd** [comment]
I suspect is it just missing
```
AXIS=$(SUPPORT)/axis/master
```
from `configure\RELEASE` - however it is probably worth adding
```
MOTOREXT=$(SUPPORT)/motorExtensions/master
```
too

**Comment by rerpha** [comment]
PRs:
- IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/670
- Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7007

Will hotfix this on LARMOR and add to list of hotfixes, potentially on IMAT and SANS2D too.
