### ISSUE TITLE
TCioc: Design review and future options

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6999]
As a developer I would like to have a review of tcioc going forward and a design review of a python based prototype as an alternative which I have created: https://github.com/rerpha/pytcioc

### Acceptance Criteria
- [ ] Meeting is scheduled for this
- [ ] Meeting is had, and outcome is documented. We should think about: 
  - [ ] Why a python-based alternative may be suitable over the existing c++ tcioc
  - [ ] how we are going to avoid legacy/homegrown code and how, if we are going to use it, we can make it generalised for twincat applications in other facilities etc. 
  - [ ] Technology for serving PVs etc. - is Pcaspy the best approach or are there alternatives?
  - [ ] Whether or not we should handle the motor record stuff within the application or if we should do this the standard way with a c++ motor driver. 

### Extra Information
My current thoughts are:
Tcioc is a very simple program in essence, for our use case at least, all it needs to be able to do are provide a bridge between EPICS and ADS (TwinCAT's comms protocol). Currently it also takes a .tpy file (which describes the PLC code variables) and converts it to a .db file which is then loaded in by the IOC. 

 we could make this modular, so split up: 
- tpy - db file conversion
- pv serving
- motor record serving

Which would allow us to replace tcioc with our python alternative in stages. for example, getting it just serving the PVs that tcioc generates and puts in the db file first, then actually loading the tpy file second, and finally doing the motor record stuff on top. 

Doing it in Python over C++ in theory will be slower, however in real world use tcioc has caused some issues with race conditions, delays etc. and it is reasonably difficult to debug on an instrument. I have tested my prototype with 9 axes and it seems to be copying, though that is just with camonitors etc. and not the motor record on top (this will probably need to be done first)
Tcioc is also not unit tested, which may be easier to do starting from the ground up and following TDD approaches.

**Comment by rerpha** [comment]
Have only assigned myself because I will be in this meeting (unless I get hit by a bus/trampled by a pack of angry llamas), however someone else could organise it.

**Comment by FreddieAkeroyd** [comment]
Some thoughts:

- pcaspy uses the legacy cas framework, so may not want to depend on this e.g. no epics V4 support
- there are other python options e.g. http://mdavidsaver.github.io/pyDevSup/, https://github.com/paulscherrerinstitute/asynPythonDriver
- Also examine the ESS approach?

**Comment by FreddieAkeroyd** [comment]
* Not use addresses from tpy, instead take names and then lookup and cache a handle for later use using the special IndexGroups ADSIGRP_SYM_HNDBYNAME and ADSIGRP_SYM_VALBYHND. This avoids address changes in tpy file. 
* Not use tpy file at all, instead use a mapping file of epics -> plc name, and access plc variable by caching and using handle obtained via special IndexGroups ADSIGRP_SYM_HNDBYNAME and ADSIGRP_ SYM_VALBYHND
*

**Comment by rerpha** [comment]
Could also discuss reading/writing ADS method, 

- using Device Notifications https://infosys.beckhoff.com/english.php?content=../content/1033/tcadsamsspec/html/tcadsamsspec_adscmd_adddevicenotification.htm&id= (pyads: https://pyads.readthedocs.io/en/latest/documentation/connection.html#device-notifications) 
- read/write multiple https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_adsdll2/9007199379576075.html&id=9180083787138954512 (pyads: https://pyads.readthedocs.io/en/latest/documentation/connection.html#read-and-write-multiple-variables-with-one-command)

**Comment by FreddieAkeroyd** [comment]
Some notes to bear in mind:
* from python docs "Be aware to release handles before closing the port to the PLC. Leaving handles open reduces the available bandwidth in the ADS router." This may mean that killing the IOC introduces a resource leak in the ADS router is you use handles.
* From general docs, there is a limit on number of active notifications (may be ~500)
tcIoc currently uses address based tpy, they may be doing this because they tried the other routes and had issues, so we should confirm this before we go down any such routes

**Comment by rerpha** [comment]
One thing to note, which is slightly annoying, is tcioc seems to strip off whatever is before the first `.` of an ADS name, probably for brevity/epics char limits. This makes it difficult when using PROG files to expose auxiliary vars like motor temps etc. because the prog name gets cut off, meaning instead of AXIS_1:FTEMPERATUREMOTOR you just get FTEMPERATUREMOTOR, so for 5 axes like on SANS2D the names are duplicated, meaning we can't load them in EPICS (or we can only load 1 of them)

**Comment by rerpha** [comment]
Freddie and I have been trying to get AdsDriver (https://github.com/Cosylab/adsDriver)  to compile on windows to test it out as an alternative. I have created https://github.com/ISISComputingGroup/IBEX/issues/7522 to continue investigating
