### ISSUE TITLE
CCD100: test mk3 protocol file with mk2 device

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7005]
As a developer I would like to know if the mk3 (tcp) CCD100 protocol file added during #6440 can be merged/adapted for use with an existing mk2 (serial) CCD100

## acceptance criteria

* mk2 device tested
* files merged or macro added to select device to use

**Comment by KathrynBaker** [comment]
Terminators can be set using in the st.cmd file, alternatively different protocol files could be opened based on the model number, slightly more complicated, but possible using a macro that is then compared in the st.cmd file (we do this for Danfysiks as an example)

**Comment by rerpha** [comment]
I don't think you can set [system vars](https://paulscherrerinstitute.github.io/StreamDevice/protocol.html#sysvar) when referencing a .proto file from a db - we tried setting the terminator based on $(IFMK3) and then passing as `$2` of each .proto() call but it didn't work. 

I also don't think we'd be able to uncomment the `in` line which is required for the mk2 but not mk3

**Comment by Tom-Willemsen** [comment]
You don't have to set the terminators at the streamdevice level, it can be done at the asyn level instead.

See https://github.com/ISISComputingGroup/EPICS-ioc/blob/7a9a8b3bedfd769d10797b4e1642500763c427f7/KHLY2400/iocBoot/iocKHLY2400-IOC-01/st-common.cmd#L18 for an example of how we do variable terminators for a keithley 2400 for example.

If it's just one protocol function that's different, we might just need to have `read_mk2` and `read_mk3` functions - or have different protocol fragments with the same function names. There might still be a small amount of duplication but at least not a full `.proto` file.

Give me a shout on teams if this doesn't make sense and I will explain better...

**Comment by rerpha** [comment]
protocol file for a keithley 2400 (note no terminators in this file as tom says they are set at asyn level) https://github.com/ISISComputingGroup/EPICS-Keithley2400/blob/master/Keithley2400Sup/Keithley2400.proto

**Comment by esmith1729** [comment]
https://github.com/ISISComputingGroup/EPICS-asyn/blob/master/asyn/miscellaneous/asynInterposeEos.c#L328-L336

Asyn doesn't let you use more than 2 characters for the Eos characters it seems?

**Comment by rerpha** [comment]
Evan and I have modified it so it works with 3 chars: https://github.com/ISISComputingGroup/EPICS-asyn/pull/25

I'm not sure if it was set to a 2 char limit for a good reason but if not it might be worth pushing this upstream?

**Comment by FreddieAkeroyd** [comment]
It would be good to confirm changes with mk3 hardware - i see `getSP` is now `in "SP VALUE:\_%f\_";` but was `in "SP VALUE:%f\_";` for a mk3 so a bit of subsequent space handling may be needed

**Comment by rerpha** [comment]
putting back in progress. CG to set up CCDs in lab after CMS has reserved some IPs for R55

**Comment by rerpha** [comment]
decided to remove the tests, as there's no point testing against the prevention of something if it is no longer an issue. we don't test logging for other IOCs either.
