### ISSUE TITLE
IBEX GUI: Use tree view in IOC list using IOC description as the key

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7013]
Following on from #6272 I would like to reduce the repetition (or hide it at least) in the IOC list screens. 

We could do this by utilising a tree view with the IOC description for the key as a first approach. 

### Acceptance Criteria
- [x] Make sure the descriptions for each IOC are sensible - if not these should be changed for clarity before adding to the tree view
- [x] A tree view is introduced to both the start/stop and add/remove IOC screens using IOC description as the "key" of the tree
- [x] Filtering out running/in config IOCs is added 
- [x] A toggle button for expand/collapse all items in tree view is added
- [x] A squish test is written for both screens
- [x] Any manual tests are updated accordingly

### Extra Information
This is just the GUI side of things, nothing in the backend (other than IOC descriptions) will need to be changed here. The architecture from SQL etc. should be the same, just how we use the data in the GUI will be different. 

How this will look: 
```
- IOCS:
  -  Galil Motion Controller:
     - GALIL_01
     - GALIL_02
  - Mclennan Motion Controller:
     - MCLENN_01
     - MCLENN_02
   - Eurotherm Temperature controller
      - EUROTHRM_01
      - EUROTHRM_02
   - etc 
```
Obviously not in that order, should be sorted in alphabetical order. 

## How to Test
checkout the new branch in the GUI and IOCs, run `make iocstartups` in `Instrument\Apps\EPICS`
start ibex, edit a config and go to add ioc, a tree in order of descriptions should be shown. there should be buttons to expand or collapse all items in the tree.
go to the start/stop ioc menu, a similar tree should be shown, with a section at the top for any IOCs that are running, or are in the current config.

check that the squish tests pass.

**Comment by ThomasLohnert** [comment]
Code looks really good, great work! The main piece of rework is around the collapsing/expanding behaviour, check comment on ibex_gui PR. Plus another couple nitpicky comments on GUI and system tests.
