### ISSUE TITLE
WISH + LET ORC: various db issues 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7025]
Nb this is just the issues with calculations for swept distance, and was due to PINIs happening more than once and maths being affected subsquently. All this ticket/PR does is copy what I hotfixed onto LET and WISH 

## Where?
The WISH ORC is having some issues: 

- `fullrev` doesn't seem to be set to anything other than 0 on the device on startup
- Swept distance readback is half what it should be
- (possibly because of above) the overshoot is incorrect for the swept distance
- on IOC startup the operating frequency seems to be double what it should be (0.8 not 0.4) 

## Acceptance criteria 
- [x] Above issues are fixed and tested on real device
- [x] Hotfix on WISH is made
- [x] hotfix is listed on ibex wiki

Note that this is a difficult one to test on a simulated Galil as user vars are not supported
Also note that these just apply to the WISH collimator as it uses different logic to the others

**Comment by rerpha** [comment]
Hotfix has been made on WISH, scientists are happy with it, so will put these changes in a PR, but there was a change to the shared db used by the LET collimator which we need to think about when copying the changes across.

**Comment by rerpha** [comment]
Fix - this should work for LET and WISH collimators: https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/43
RNs: https://github.com/ISISComputingGroup/IBEX/pull/7072

**Comment by rerpha** [comment]
Moving back to in progress because they are still having issues anyway

**Comment by rerpha** [comment]
hotfixes are on WISH and LET. Note that this was not the cause of the jolting seen on WISH but wouldn't help with LET as some of the maths was being calculated wrongly. I fixed this on LET and it got them through the cycle but #7116 was stopping WISH

**Comment by rerpha** [comment]
Not really much to review here, just make sure that the FLNK logic makes sense

**Comment by FreddieAkeroyd** [comment]
@rerpha should there be release notes?  If not please mark as no release notes

**Comment by rerpha** [comment]
> @rerpha should there be release notes? If not please mark as no release notes

https://github.com/ISISComputingGroup/IBEX/pull/7183
