### ISSUE TITLE
Eurotherm: support more than 7 channels per IOC

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7026]
As an INTER scientist, I would like to be able to run at least 8 channels off a single Eurotherm unit. Currently, the IOC only allows 7 channels while the protocol should support many more than that. Not sure where this number comes from in IBEX, might need investigation whether there is a reason this is limited or whether we can just copy/paste in more.

### Acceptance Criteria
- A single Eurotherm IOC can control at least 8 channels simultaneously

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_
- [x] Checkout [THIS PR](https://github.com/ISISComputingGroup/EPICS-ioc/pull/675) for the [Eurotherm IOC](https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/EUROTHRM).
- [x] Checkout [THIS PR](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/524) for the [IOC system test](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework) changes to reflect changes made to [Eurotherm IOC](https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/EUROTHRM).
- [x] Proofread the README.md in the Eurotherm IOC repo.
- [x] Ensure URLs have been added to the [Eurotherm wiki page](https://github.com/ISISComputingGroup/IBEX/wiki/Eurotherms/_edit#useful-recources) to the IOC repo and [EPICS-IOC_Test_Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework).
- [x] Open an EPICS terminal and navigate to the `eurotherm.py` system test and use the following command to check the default. channel (channel 1) passes all unit tests: `python run_tests.py -t eurotherm`.
    - [x] repeat this step after changing the channel a few times - See instructions in README.md of [Eurotherm IOC](https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/EUROTHRM) to do this if needed.
-  [x] Ensure [Release Notes](https://github.com/ISISComputingGroup/IBEX/pull/7056) have been created and merge in

**Comment by KathrynBaker** [comment]
Whilst not necessarily relevant, the LabVIEW version allowed for up to 10 Eurotherms with full front panels, and 2, 6, or 8 in simplified ones
