### ISSUE TITLE
SANS2D: Enable guide axes after vacuum permit loss

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7032]
As a SANS2D Scientist I would like my Guide axes 1-5 to be re-enabled after a vacuum permit loss. Currently if I stop/start the front end vacuum and the permit from the vacuum PLC is lost, I have to manually re-enable the axes through the "Beckhoff engineering" OPI which is tedious. 

These are Beckhoff/TC controlled, currently this is not supported but the motion team are working on getting it added in. 

### Acceptance criteria
- [x] A method of sorting this out is discussed with the scientists (outcome: just do whatever is simplest) 
- [x] This is implemented and put onto SANS2D
- [x] The method is tested and the scientists are happy

**Comment by rerpha** [comment]
Tested, added note to https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details#note-guides to document. 

Scientist is happy with functionality - we were able to move the guides after the vacuum permit had been re-established.

**Comment by JackEAllen** [comment]
> Tested, added note to https://github.com/ISISComputingGroup/IBEX/wiki/SANS2D-Instrument-Details#note-guides to document.
> 
> Scientist is happy with functionality - we were able to move the guides after the vacuum permit had been re-established.

For consistent history in this issue, the above url has been updated to: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-Instrument-Details#note-guides

**Comment by JackEAllen** [comment]
Looks good so closing this. 🥇
