### ISSUE TITLE
Instrument: excessive archiving

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7038]
After running `archive_rates.py` teh following appeared on WISH
```
IN:WISH:CS:DASHBOARD:TAB:1:1:VALUE.VAL  count=60        rate=2.00 Hz
IN:WISH:CS:DASHBOARD:TAB:2:1:VALUE.VAL  count=60        rate=2.00 Hz
IN:WISH:CS:DASHBOARD:TAB:1:2:VALUE.VAL  count=30        rate=1.00 Hz
IN:WISH:TIME_OF_DAY.VAL count=30        rate=1.00 Hz
```
I am not sure we really need to be archiving these.

The first three are in `dashboard.db` , the last in INSTETC

## Acceptence Criteria
 - [ ] Remove info archive field from TIME_OF_DAY as there should be a timestamp 

### Discussed in planning 05/09/24
16:45

**Comment by rerpha** [comment]
this has already been done in INSTETC by the looks of it? https://github.com/ISISComputingGroup/EPICS-ioc/commit/4abe574d7a61fb9347f7c67b18e34c77b0b2ae97

**Comment by rerpha** [comment]
done on NDXWISH in `10b3a74f46`

**Comment by Tom-Willemsen** [comment]
I think we should do it on all instruments (probably via an upgrade script)

**Comment by rerpha** [comment]
that's fine - just being lazy, is there _anything_ you can think of that should actually be archived in dashboard.db? I think they are all derived from stuff that probably already is archived, can we just remove info(archive, "VAL") from all?

**Comment by FreddieAkeroyd** [comment]
the only reason to archive them would be if we were allowing people to right click on them to plot a graph (like on blocks), but we are not and many are combined strings like "good / raw" so not plottable anyway.  It is also unclear what you would be  archiving if you did look back as they have names like `IN:WISH:CS:DASHBOARD:TAB:1:1:VALUE`. So i'd say to just remove all line of the form `info(archive, ".*")` - if we create a python script to do this we can run it as an upgrade but also separately via the backdoor if we wish.

**Comment by rerpha** [comment]
i'm feeling lazy and i'm going to run `sed -i '/info(archive, "VAL")/d' dashboard.db`  on every instrument I think unless anyone has any objections.

**Comment by rerpha** [comment]
I have done this and added a note to the private scripts repo to explain how ssh can be used for this sort of thing. To review, check that instruments don't have `info(archive,"VAL")` in their `dashboard.db`s - i left dashboard_muon.db as it doesn't look to be used.

**Comment by Tom-Willemsen** [comment]
Looks like it's been successfully removed on all instruments, and the phone lines haven't exploded yet, so happy to call this done.
