### ISSUE TITLE
PEARL Pressure Controller: Umbrella Issue for Readback Values from Status Command

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#7043]
This issue is an umbrella issue to complete the below linked issues as part of development for the PEARL Pressure Controller for Wish ready for the next cycle.

## Where?
_Where is the issue likely to be (be as specific as possible e.g. file paths, related issues etc.)_

Umbrella issue for Pearl Pressure Controller encapsulating DB logic and updating OPI as required to replicate LabVIEW VI Implementation.
- [#6779](https://github.com/ISISComputingGroup/IBEX/issues/6779)
- [#6768](https://github.com/ISISComputingGroup/IBEX/issues/6768)
- [#6767](https://github.com/ISISComputingGroup/IBEX/issues/6767)
- [#6766](https://github.com/ISISComputingGroup/IBEX/issues/6766)
- [#6765](https://github.com/ISISComputingGroup/IBEX/issues/6765)

## How?
_How did the issue come about/known cause of issue if any? (**delete subheader if not applicable**)_
WISH require the Pearl Pressure controller for the next cycle within IBEX. To make this possible, an IOC and OPI need to be developed to match existing functionality present in the LabVIEW VI implementation of the Pearl Pressure controller.

## Acceptance criteria 
- [ ] All associated issues have been completed
- [ ] All associated issues have been tested.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

### Extra Information
_Why it is needed?_
- Functionality exists in LabView VI and should be replicated in IBEX GUI device screen for consistency

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by KathrynBaker** [comment]
Estimated in [IBEX Pointing (scrumpy)](https://play-game.scrumpypoker.com/#/room/nkkgetpzayqn) to **5**, the average vote was **5** story points.

**Comment by Tom-Willemsen** [comment]
The only outstanding work on this ticket is to add the `BUSY` (motors moving) flag to the OPI; all other work has already been done as part of other tickets.

PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1430
