### ISSUE TITLE
Pearl Pressure Controller: Umbrella Issue For Cell and Pump Pressure 

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#7044]
## Where?
_Where is the issue likely to be (be as specific as possible e.g. filepaths)_

This issue is an umbrella issue to complete the below linked issues as part of development for the PEARL Pressure Controller for Wish ready for the next cycle.
- [#6774](https://github.com/ISISComputingGroup/IBEX/issues/6774)
- [#6770](https://github.com/ISISComputingGroup/IBEX/issues/6770)

## How?
_How did the issue come about/known cause of issue if any? (**delete subheader if not applicable**)_

How did the issue come about/known cause of issue if any? (delete subheader if not applicable)
WISH require the Pearl Pressure controller for the next cycle within IBEX. To make this possible, an IOC and OPI need to be developed to match existing functionality present in the LabVIEW VI implementation of the Pearl Pressure controller.

## Acceptance criteria 
- [ ] All associated issues have been completed
- [ ] All associated issues have been tested.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

### Extra Information
_Why it is needed?_
- Functionality exists in LabView VI and should be replicated in IBEX GUI device screen for consistency.

_Where required files/links are_
- Manual: `\\isis\shares\ISIS_Experiment_Controls\Manuals\PEARL Pressure Controller\PEARL handbook_v3_5.docx`
- Labview Vi: `C:\LabVIEW Modules\Instruments\PEARL\PEARL Pressure Cell Controller`
- Please see conversation in #6040 to view a screenshot of LabView VI for reference.
- PEARL Pressure Controller Emulator: `C:\Instrument\Apps\EPICS\support\PearlPressureController\master`
- PEARL Pressure Controller IOC: `C:\Instrument\Apps\EPICS\ioc\master\PEARLPC`
- PEARL Pressure Controller OPI: `C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\resources`

**Comment by ThomasLohnert** [comment]
Not sure whether this is highest priority work for Pearl PC. Adding to high as stand in for _some_ pressure controller work, we can discuss whether we want to do something else instead
