### ISSUE TITLE
SANS2D: Fix Vacuum Status and Positional Status of Apertures and Guides FRONTEND Screen.

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#7047]
As instrument scientist

Currently the "Vacuum" status displays as `OFF` even when the vacuum is on indicating that the PV (`IN:SANS2D:FINS_VAC:GUIDE:STATUS:AT_VACUUM.RVAL`) is not updating correctly. As an instrument scientists, I would like to see this fixed.

Alongside this the, "positional" status displayed in the SANS2D FRONTEND Apertures and Guides OPI is disabled.  

I would like to swap the FRONTEND screen "positional" status PV: `IN:SANS2D:_POSITIONAL_ERROR` to use the opposite of `IN:SANS2D:LKUP:AG:POSITIONED` PV which indicates the LED for the "In position" value in the SANS2D Aperture and Guides OPI. 

Reversing the logic used to indicate In position seems like a simpler solution for displaying whether of not the "Positional" should be displayed.  

![SANS2D_Apertures_and_guides_OPI_Problem](https://user-images.githubusercontent.com/32413847/155582125-43151536-30f6-425f-b8d8-73c8a936be85.PNG)

### Acceptance Criteria

_What is the acceptance criteria?_
- [ ] The "Vacuum" status is resolved to correctly reflect the state of the vacuum.
- [x] The "positonal" field uses the opposite value used to indicate the "Position" status from the PV: `IN:SANS2D:LKUP:AG:POSITIONED` and displays desired behaviour. 

### Extra Information
_Why it is needed?_
To resolve ongoing issues on SANS2D Apertures and Guides FRONTEND ready for the start of cycle.

_Where required files/links are_
-  Instrument\Apps\EPICS\support\motionSetPoints\master\motionSetPointsApp\
- Instrument\Apps\EPICS\support\motionSetPoints\master\motionSetPointsApp\Db\O.Common\motionSetPoints10Axis.db

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
We may also be able to remove the crap in custom_records.db too if no longer needed. 

For the "positional error" I was thinking of using a `calc` record that does this: 

1 if (inpos_dmov and NOT inpos)

for the vacuum status the RVAL may not be able to be used. Either way this will involve modifying custom_records.db on SANS2D as well as their front end OPI (which we'll have to patch over)

**Comment by rerpha** [comment]
Have modified custom_records.db to suit the above logic, now need to fix the vacuum status

**Comment by rerpha** [comment]
ok, scientist has said tomorrow morning would be a good time to test so have patched over the changes and just needs an ioc restart of FINS_01 to pick up the changes. Found out that GUIDE:STATUS.RVAL was not being propagated as well as AT_VACUUM

**Comment by rerpha** [comment]
change has been made but next opportunity to test is next wednesday

**Comment by rerpha** [comment]
release notes https://github.com/ISISComputingGroup/IBEX/pull/7101
