### ISSUE TITLE
Genie_python: Silent waitfor

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7054]
As an INTER scientist, I would like to run a "silent" `waitfor_x`, i.e. disabling output to the console.

### Acceptance Criteria
- [x] Give all `waitfor_` methods an optional `silent` parameter, which disables printing outputs to the console.

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by ThomasLohnert** [comment]
@aaron-long could you add a [release notes PR](https://github.com/ISISComputingGroup/IBEX/pulls) please?

**Comment by aaron-long** [comment]
> @aaron-long could you add a [release notes PR](https://github.com/ISISComputingGroup/IBEX/pulls) please?

Done
https://github.com/ISISComputingGroup/IBEX/pull/7150/files
