### ISSUE TITLE
GUI: Fix text in groups panel disappearing when resizing

### ISSUE THREAD

**Issue by Adam-Szw** [ISISComputingGroup/IBEX#7060]
## Where?
Groups panel

## How?
Most likely introduced here https://github.com/ISISComputingGroup/IBEX/issues/7039

## Reproducible?
Yes

### To Reproduce
Have server not running while opening Ibex GUI. Resize groups panel. Text will disappear

## Acceptance criteria 
- [ ] bug is fixed

**Comment by Adam-Szw** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1400

**Comment by rerpha** [comment]
looks good, and sory to nitpick, but ive noticed something else - if i:
1. go from maximised to windowed with an empty config
1. while windowed, change to a config which has several small groups in
1. maximise the window
The groups don't seem to scale to their smallest when collapsed. 


clicking either of the two controls to hide or sort solves this! Sticking in rework for now as its very close but would be good to have it working perfectly

**Comment by Adam-Szw** [comment]
Thanks for spotting this! It would actually be a big problem if left unchecked. I found the cause of the problem and now all related bugs should be fixed but please do double-check in case I missed something

**Comment by rerpha** [comment]
Great, fixed now, thanks Adam
