### ISSUE TITLE
Beckhoff engineering view: show hexed error ID 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7062]
As a support staff member I would like to have some more info on the beckhoff engineering OPI:
- A hexed error value
- An indicator that you have to press load on the axis number for it to show
- An indicator on the actual axis sub-opi itself of what axis is being shown
- a sensible default for the axis num spinner (currently 0)

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Above things are added

**Comment by rerpha** [comment]
OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1399
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7063

To review, build a client and switch instrument to one that has a beckhoff such as SANS2D, then check the beckhoff engineering screen to make sure it meets the acceptance criteria

**Comment by JackEAllen** [comment]
Closing as OPI and Release notes have been merge in. Beckhoff engineering view correctly displays Axis:
![image](https://user-images.githubusercontent.com/32413847/156763465-3b65f204-24c9-454d-be8c-5d3c62c1c864.png)
