### ISSUE TITLE
Data streaming cluster updates

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7066]
Today I:

- took down the dev cluster (ask me why on teams if you want more info) 
- updated kafka, zookeeper, etc and general updates on the prod nodes 
- fixed the statistics node, so grafana should now work

https://github.com/ISISComputingGroup/ansible-kafka-centos has also been updated with the playbook I used

To review: check the grafana instance is working again, password should be on keeper.

**Comment by JackEAllen** [comment]
I can access `madara:3000` and see the disk space for each broker so closing this issue now complete.
