### ISSUE TITLE
CHIPIR filter set commissioning 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7067]
The (now) Beckhoff-driven filter set will need to be commissioned in person which will follow most of the steps in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff-Commissioning but without the motor setup and the fact that they are using a mini-inst. 

Prior work: 

https://github.com/ISISComputingGroup/IBEX/issues/6983
https://github.com/ISISComputingGroup/IBEX/issues/6984
https://github.com/ISISComputingGroup/IBEX/issues/6985

**Comment by rerpha** [comment]
will be happening next monday (14th)

**Comment by rerpha** [comment]
Instructions are basically:

- Set up the route to the beckhoff from the XAR icon in system tray - `right click -> router -> edit routes` - further info on the [commissioning page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff-Commissioning)
- put the `.tpy` file, named whatever it is in globals.txt, in `C:\instrument\settings\config\NDXCHIPIR\configurations\twincat\`
- start the mini inst - this should generate a .db file in the above directory
- make a note of PV names and input those into the labview VI. If this does not give a value then use `.RVAL` on the PV.

**Comment by KathrynBaker** [comment]
Due to who was around and similar I ended up not doing this, but David did, with some help from Freddie and Jack. Things are commissioned and running to the best of our abilities, if there are any issues now, they can be dealt with separately to this ticket.
