### ISSUE TITLE
Tech Debt/Hackathon on the 22/04/2022

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7103]
As someone working on the IBEX project I'd like to spend some time making it better in a concerted effort with the rest of the group.

## Acceptance Criteria
- [ x] The day is planned and an invite sent - this has been done but as it is likely to be early in the next sprint it was important to get it in calendars
- [ ] The day has been and some team members worked on the hackathon

## Notes
- Initial suggestion is #6556, we can choose a different topic as appropriate

**Comment by rerpha** [comment]
This has happened. Assigning you Kathryn as you organised it!
