### ISSUE TITLE
Tek AFG3XXX: ioc leaks sockets when device in strange state

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7111]
As a user I do not wish the TekAfg3xxx to leak network sockets, it seems to be fine if the device is swithed off, but on INTER it currently seems to be ion a strange state allowing an initial vxi connection but then printing
```
inst0 vxiCreateDeviceLink RPC error : RPC: Unable to receiveError 10054,
```
repeatedly that results in a leak of network sockets that eventually cause issues on the computer

## To Test

start up the TEKAFG3XXX ioc with IP address of a box (ask on Teams), start task manager, add the handle and "memory private" columns, and observe that handles increases over time (and memory private too if you wait long enough). A few minutes is long enough for handles. You should see the above error printed periodically too.

After applying patch, above items should remain steady

## Acceptance criteria

* no more handle/memory leaks

**Comment by Adam-Szw** [comment]
Email sent if we can test the tek afg to instrument scientists. Waiting for response now to review the ticket.

**Comment by Adam-Szw** [comment]
After testing, I can confirm that on master version the values rise slowly and on the patch they stay the same over time.
