### ISSUE TITLE
NIMROD: Move camera configurations to base component/synoptic

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7112]
As an instrument scientist on NIMROD I'd like the settings and interactions for my camera to be in my 'base' configurations/synoptics rather than attached to my sample stack so that it is always available to me.

## Acceptance Criteria
- [x] The camera is moved to the base configuration and synoptic

## Notes
- This may mean moving the IOC for the sample stack to the base configuration, this should not stop the blocks etc. being hosted in the sample stack config, but it may be worth checking with the instrument scientists whether they are happy with that, actually want to move all parts of the sample stack config into their 'base' setups, or are happy leaving things as they are if this is down to the IOC access.

**Comment by rerpha** [comment]
>This may mean moving the IOC for the sample stack to the base configuration
We will have to do this as the camera is on the same Galil

**Comment by JackEAllen** [comment]
This issue should be applied on a maintenance day or post-cycle should NIMROD agree to moving the sample stack to the base configuration.

**Comment by JackEAllen** [comment]
Sent an email over to NIMROD to make sure this is still what they want and waiting for a reply before progressing with this issue.

**Comment by JackEAllen** [comment]
NIMROD want to be able to easily revert changes made as part of this issue so I have created a backup which we can revert back too named `C:\Instrument\Settings\config\NDXNIMROD_20220818_pre_camera_config_move`

**Comment by JackEAllen** [comment]
# Review
## How to review
- [ ] Remote into NDXNIMROD
- [ ] open up the IBEX client
- [ ] Check that the camera component exists on every synoptic and can be opened
- [ ] Check that the camera component exists in every configuration
- [ ] Once happy with changes, close IBEX client
- [ ] Stop Ibex server `C:\Instrument\Apps\EPICS\stop_ibex_server.bat`

**Comment by NikolaRoev** [comment]
A few follow up questions.

- Should the camera blocks be in a group?
- Should the `Base` component contain the common `Beam_info`, `beamline_vacuum`, and `Jaws`, or should it be renamed to something more descriptive like `Camera`. As a user I would expect the `Base` component to contain all these standard components. At the moment it's a bit misleading.
- As the point above, should the camera component be a part of the `Base` configuration?
- The camera part in the `Base` synoptic is named "Neutron Camera", while all others are just "Camera". Should this be made consistent as it may be hinting at two different types of cameras?
- I have noticed that the camera is always at the end of the synoptic, does that reflect the physical reality of the beamline?

**Comment by JackEAllen** [comment]
> * contain the common `Beam_info`, `beamline_vacuum`, and `Jaw`

I've contacted NIMROD to ask if they are happy with the changes made and to comment on your suggestions. I'll update this thread when they get back to me.

In terms of the cameras placement, yes, the camera is always at the end physically. It's the only camera they tend to use so I would assume they would prefer to keep it as just camera to keep it short, but I've passed on the suggestion in case they would prefer Neutron Camera.

**Comment by JackEAllen** [comment]
Waiting on comments from NIMROD

**Comment by JackEAllen** [comment]
NIMROD replied to my initial email verifying that they are happy with the current changes made and did not ask for any additional changes to be made mentioned by @NikolaRoev during the review of this issue. 
I asked NIMROD to get back to me after physically checking that they are happy with the the changes to components, configurations and synoptics, but have not heard back which I'm going to assume means they are happy with the changes.
If this changes, I will reopen the issue to work on any changes requested.
@NikolaRoev, are you happy to put this through review?
