### ISSUE TITLE
motionsetpoints: handle duplicate positions better  

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7118]
As a scientists I would like motion setpoints to handle duplicate positions betters. On SANS2D two racks can end up with items at the same offset, this is not allowed probably because the system thinks it can't make a unique back translation of position to name. However as we should know the intended setpoint, this provides a way to choose whihc of teh matching alternatives is best to use, otherwise SECI just returned one of the options and the scientists already accepted this. 

## Acceptance criteria

*duplicate positions are not an error, tests updated to test this and they pass

**Comment by ThomasLohnert** [comment]
Add a line about the current behaviour on the user wiki until this is fixed

**Comment by rerpha** [comment]
as a (rubbish) workaround, could you use a 2-axis motion setpoints with one axis pointing at SIMPLE:DOUBLE ? 
On SANS2D they have a 10 axis motionsetpoints set up where several axes are the same SP over multiple motionsetpoints and it seems to work fine

**Comment by Adam-Szw** [comment]
Is this ticket finished, given https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/25 ? Otherwise what needs to be done given this?

**Comment by FreddieAkeroyd** [comment]
@Adam-Szw I think it is probably done

**Comment by rerpha** [comment]
should we make it set-able from somewhere to be able to allow/disallow duplicate positions? just thinking `allow_duplicate_coords` will never be false unless you recompile after setting it to true, or maybe im missing something
