### ISSUE TITLE
Remove BKHOFF IOC and MCAG code

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7125]
The BKHOFF IOC was used along with the MCAG code on IMAT for their rotation and height stage but has now been superceded by the new collaboration code and run under the TC ioc. We should remove it as it's dead! 

Note this is part of #6854 , CRISP jaws still need to be re-commissioned. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] IOC is removed
- [ ] any references to BKHOFF are removed

**Comment by rerpha** [comment]
PRs

IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/682
Release notes:

**Comment by daryakoskeroglu** [comment]
@rerpha Everything looks good, thank you! Before we archive MCAG repo, I think it is worthwhile updating the README file about removing the IOC

**Comment by rerpha** [comment]
> @rerpha Everything looks good, thank you! Before we archive MCAG repo, I think it is worthwhile updating the README file about removing the IOC

Cheers, have made https://github.com/ISISComputingGroup/EPICS-MCAG_Base_Project/pull/9
