### ISSUE TITLE
instruments: clean up disk space prior to cycle

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7128]
Prior to cycle, the databases need clearing up on TS2, particularly IMAT (which is very short of space).  LARMOR, LET, ZOOM, SANS2D I did earlier in the week, so hopefully those are still OK.  Check anyway.

Check first box for in progress, second box when done.

IMAT
- [x] In progress
- [x] Complete

LET
- [x] In progress
- [x] Complete

NIMROD
- [x] In progress
- [x] Complete

ZOOM
- [x] In progress
- [x] Complete

INTER
- [x] In progress
- [x] Complete

POLREF - see comment below
- [ ] In progress
- [ ] Complete

OFFSPEC
- [x] In progress
- [x] Complete

LARMOR
- [x] In progress
- [x] Complete

WISH
- [x] In progress
- [x] Complete

**Comment by davidkeymer** [comment]
Follow instructions on [this dev wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space) to reduce database size.  The script works well, but give it time to complete as there's no progress indicator.  Database password can be found in the usual place.

Then if IOC log file directory (/instrument/var/logs/ioc) also large (greater than 1GB), move files to `\\isis\inst$\backups$\stage-deleted\<inst>`.  Create an appropriately named directory there first e.g. YYYYMMDD_IOC_logs.  Compressing the files before the move also helps as the ratio is high.  This can be done simply by selecting the files in the directory, then `right-click -> send to -> compressed (zipped) folder` then naming the file as suggested above before moving.

Sometimes cached Windows update files are also present on the C drive.  These can be removed by running the `Windows Disk Clean-Up` utility from the Start Menu and selecting the appropriate files after the scan is complete.

**Comment by rerpha** [comment]
all instruments listed now have >10GB as per a nagios search
