### ISSUE TITLE
SANS Instruments: Making do_sans, do_trans more robust

### ISSUE THREAD

**Issue by TCMeldrum** [ISISComputingGroup/IBEX#7132]
As a user, I would like the do_sans do_trans functions to be more robust.

### Acceptance Criteria
- [ ] Scripts more robust
- [ ] Scripts easier to use with better documention 

### Extra Information
There are a few features that instrument scientists would like to have with the do_sans/do_trans functions that don't currently exist that should be implemented. Further, they would like the code to be more readable and easier to use in general as well as more robust error handling.

**Note for reviewer: if putting this ticket back into rework, please find a willing volunteer to pick up the rework changes as Thomas C-M is no longer working on this project.**

**Comment by rerpha** [comment]
Have put the pair review label on this as I think it'd be good to look with someone else, as its quite a large set of changes

**Comment by NikolaRoev** [comment]
Reviewed this together with @Tom-Willemsen and assigned myself. Will do the rework eventually.
