### ISSUE TITLE
GUI: Improve how interacting with log plotter when it's disabled notifies the user

### ISSUE THREAD

**Issue by Adam-Szw** [ISISComputingGroup/IBEX#7133]
As a user, I would like to know why I can't interact with log plotter. Currently if log plotter perspective is disabled, but I try to, for example, add a PV to log plotter, simply nothing will happen.

### Acceptance Criteria
- [ ] There is a notification that log plotter needs to be enabled when trying to add PV to log plotter from an OPI
- [ ] Same thing but when doing it from Beam perspective

**Comment by NikolaRoev** [comment]
- https://github.com/ISISComputingGroup/ibex_gui/pull/1465
- (Release Notes) https://github.com/ISISComputingGroup/IBEX/pull/7314
