### ISSUE TITLE
Nicos Pop Up Episode 2 Part 3: The Re-Re-Re-Return [Timebox: 7 days]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7135]
As a user / scientist / developer I would like to not be interrupted by frequent pop up windows. The Nicos process is still causing a git window to pop up periodically whenever the client fails to make a connection, despite numerous attempts to fix it (see https://github.com/ISISComputingGroup/IBEX/issues/4511, https://github.com/ISISComputingGroup/IBEX/issues/5159, https://github.com/ISISComputingGroup/IBEX/issues/6296, https://github.com/ISISComputingGroup/IBEX/issues/6542 and https://github.com/ISISComputingGroup/IBEX/issues/6696)  The client usually does connect to the script server eventually, but the amount of tries it takes seems completely unpredictable.

I propose that in addition to making the connection more stable, we should change the Nicos IOC so that it does not start up automatically, but rather is added to instrument configs like other IOCs. My rationale is that 
a) most instruments don't make use of the script server (mostly relevant for users of the script generator)
b) if there is a problem again, it will only affect a select few instruments
We just need to make sure we have tests in place to catch any issues since this will make problems with Nicos less visible.

Please discuss below.

### Acceptance Criteria
- [ ] The IBEX client connects to the script server more reliably
- [ ] Nicos IOC is started explicitly (e.g. by adding it to config), not implicitly
- [ ] There is a system test (can be manual) to check the connection is working

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
@ThomasLohnert  What and why is a git window being spawned?

**Comment by FreddieAkeroyd** [comment]
What is the git window doing that nicos starts? If we were able to make git not create a window (like python v pythonw) , would that be an acceptable workaround?

**Comment by FreddieAkeroyd** [comment]
I have pushed ISISComputingGroup/nicos#6 that doesn't fix the underlying issue, but does hide the window that is its most visible effect. That probably means we could re-prioritise fixing the underlying issue if we wish, it is mentioned above that the connection  is usually made eventually, so just hiding the flashing window may be good enough for now.

**Comment by KathrynBaker** [comment]
If the window isn't flashing then yes, fixing the underlying issue is probably less of a priority

**Comment by FreddieAkeroyd** [comment]
nicosdaemon can be started from start/top iocs in gui, but this does not update this to say it is "running". Probably some code to do this in reflectometry server.
