### ISSUE TITLE
GUI: DAE information not showing in GUI after changes

### ISSUE THREAD

**Issue by LilithCole** [ISISComputingGroup/IBEX#7138]
## Where?
Seen on SANS2D at the start of cycle 22/1

## How?
When using a script to togggle vetoes and switch between using ISIS pulses and the internal clock, the values were being correctly set in the underlying PVs but were not being updated in the DAE screen

## Reproducible?
yes

### To Reproduce
- On SANS2D, use the scripts to switch DAE timing source.
- Switch to the DAE screen and observe unchanged values
- (Optional) Switch instrument and back to see the updates make it into the GUI

## Acceptance criteria 
- [ ] DAE information changes are reflected more promptly in the GUI.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
We need to re-read the XML from the IOC used to populate the screen to resync IOC.
* a simple option might be to add a refresh button to the dae screen  to reload the XML. It might be nice if this was also done whenever the DAE perspective was activated. It woudl be too risky to do it whenever a dae tab was changed as this might overwrite changes a user was in the process of making. 
* a more complex option would be to poll ioc and update fields that have changed, but you would not want to overwrite a user in the process of making a change before they pressed "apply changes", so may be better for another day or not at all

**Comment by FreddieAkeroyd** [comment]
Add a refresh button for the moment

**Comment by FreddieAkeroyd** [comment]
@Adam-Szw the refresh button was just a possible alternative to fixing the issue if it turned out to be very awkward. If you have fixed the issue then i see no reason for a refresh button. Thanks!

**Comment by Adam-Szw** [comment]
I implemented suggested changes. Indeed it appears to still work as intended and fix the ticket issue.
