### ISSUE TITLE
SANS2D: Oerlikon IOC Pressure is formatted with no decimal places

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#7140]
## Where?
On SANS2D the Oerlikon IOC on shows 0 digits of precision on the Block display and on the OPI (seems to just show 0 on the OPI).  For some reason, the PREC field for the PRESSURE record is not set correctly (should be set to 3).  It is also not possible to change the precision from the command line in Genie Python.  This would normally be done with

```python
>>> g.set_pv(“IN:SANS2D:OERCONE_01:PRESSURE.PREC”, 3)
```
followed if necessary by a restart of the client.

## Reproducible?
[Yes/~~No~~]

### To Reproduce
Anywhere other than on SANS2D (where it has been temporarily edited to be correct), the `.db` file in the support module has no "PREC" field so adding a block will show 0 digits of precision on an emulator test.

## Acceptance criteria 
- [ ] The issue is fixed permanently to it will be correct on the next IBEX release for all Oerlikon IOCs
- [ ] The OPI formats correctly for a figure like 1.57 x 10E-7
- [ ] A block formats correctly for a similar figure to the above
- [ ] The reason why the precision cannot be set from the command line can be explained

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
the db record has ASG set to readonly hence settign does not work, should just need PREC setting in DB

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-Oercone/commit/c621e0df3ce5d719bf68f4c7c01f88b716fc6423
