### ISSUE TITLE
RIKENFE: Trial "First Fix" of RIKENFE control system

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#7145]
As an agile developer and as a systems person and as an instrument scientist I would like to have a first instance of the complete agile "product" (the RIKENFE system) with as many items as possible.  Ideally consisting of

  - The control machine computer and VM attached to the network (not necessarily located in it's final rack)
  - A recent version of the IBEX software with at least one or two new components for the RIKENFE project.
  - A connection to at least one or two pieces of control systems hardware via network or RS232 (not necessarily in their final location)

## Acceptance criteria 
- [ ] Update RIKENFE to v10 IBEX and install appropriate drivers (e.g. Technix PSU, DG645)
- [ ] Connect to existing hardware and test
- [ ] Add at least one MOXA NPort to machine, e.g for test of Technix PSU
- [ ] Add test results to comment on this ticket
- [ ] Demonstrate system to RIKEN scientists and/or project manager(s)

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

### NOTE:
This could provide a concrete demonstration to our customers that we are making progress and that we are also very much dependent on continuing progress of hardware installations etc. to be able to continue our progress and testing.

**Comment by davidkeymer** [comment]
This work has been covered by other tickets.  Given that beam was taken by RIKEN, closing this ticket.
