### ISSUE TITLE
IBEX GUI: IOC start/stop treeview auto-expanding when an IOC is continually restarting

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7147]
As a user when I have a constantly restarting IOC I would like my IOC start/stop window to:

- [ ] Not scroll to the top of the list when it refreshes the treeview
- [ ] not auto-expand all of the running/in config IOCs if i have selected "collapse"
- [ ] (maybe as another ticket) not show a blank entry in the treeview of the following IOCS: 
  - HVCAENA_02
  - HVCAENA_03
  - HVCAENA_04
  - NANODAC_01

![Animation](https://user-images.githubusercontent.com/14823767/168637908-03485578-6b17-4cbe-b8e0-84ccb916e6ae.gif)

## Reproducible?
yes

### To Reproduce
- have a running server with an IOC that restarts constantly - you could achieve this by commenting out iocInit() in an st.cmd
- view the start/stop window

## Acceptance criteria 
- [ ] Above issues are fixed

**Comment by rerpha** [comment]
Sorry, I panicked and pulled this into the sprint as i thought it was for all IOCs regardless of state, but it only seems to occur when an ioc is restarting in a loop.

**Comment by FreddieAkeroyd** [comment]
@rerpha did you want to propose it instead?

**Comment by NikolaRoev** [comment]
The blank group of these specific IOCs is not an issue on current master.

A possible way to reproduce:
- Remove `config.xml` from an IOC. Works for any config file not just the one in `*-IOC-01`. This can happen if the IOC submodule has been reverted to a state before an IOC was added and the remaining files are not cleaned up.
- Restart the server.
- IOC(s) with missing config files will now be under a blank label as they don't have a description.
- To fix, restore the config file, or remove the files, and restart the server again.
