### ISSUE TITLE
IBEX has no Exit menu item

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#715]
There is no Exit item on any of the IBEX menus.  Some people (perhaps a minority) naturally tend to use Exit to terminate an application.  It would be nice if IBEX had an Exit menu item.

Of course, there is an easy "workaround" - you can click on the Close box at the top right of the window.  But if that is not your "default" way of closing an application, you have to think twice about how to close IBEX.  And, since people tend to leave IBEX running all the time (and rarely need to close IBEX), this is not an urgent issue.

Also make the exit menu more informative - like "Are you sure you want to exit IBEX?".

Since IBEX does not have a File menu, perhaps the Instrument menu is the natural place for an Exit menu item.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 716.  Created by skn09965 on 2015-04-14T09:35:48, last modified: 2015-07-02T11:03:25_

**Comment by mattclarke** [comment]
This appears to have been done a while back, so either it was a duplicate or somebody forgot to  close it.
