### ISSUE TITLE
Verify behaviour IOC/OPI not connecting outside of configuration [timebox: 0.5 day]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7152]
As someone using IBEX I need to be able to start IOCs and see the information on OPIs that are not in the current configuration or components of the current configuration, at the moment I'm not sure that this is the case

## Acceptance Criteria
- [ ] The situation described in the notes has been reproduced
- [ ] If the behaviour is verified then a new ticket is created to fix this

## Notes
- This was seen on ZOOM, initial situation when we got involved:
   - IOC is in a component and configured
   - The component is *not* in the configuration
   - The OPI is loaded from the device screens
   - IOC running, all items on the OPI were disconnected, PORT macro error seen in the IOC
- Fix 1 saw the PORT macro being added to globals.txt
   - The Port was now found, the OPI remained disconnected, there were no visibile indicators on the nport implying that communications were being undertaken
- Added the component to the configuration
   - The OPI sprang into life after a few minutes

- This should not be the case, the IOC should start happily, and the OPI talk to the IOC whether it is in the configuration or not, need to ascertain if this is reproducible, and where the error came about

**Comment by FreddieAkeroyd** [comment]
In the `globals.txt` case there were no active sensors defined (`ADDR_1` etc) which looks to mean no communication, i thought the opi may have come up all grey tabs but that is one to check, maybe pv manager had been disconnected for too long

**Comment by FreddieAkeroyd** [comment]
ticket sis to reproduce, see if just port defined on a eurothern in globals gives this behaviour

**Comment by rerpha** [comment]
Wouldn't this mean if you ran an IOC through the test framework for example it wouldnt show up in an OPI? I think that works fine?

**Comment by rerpha** [comment]
On a new client we should try this with and without the "refresh PVs" button as that may kick it into action

**Comment by KathrynBaker** [comment]
Seen something similar on SANS2D for the Julabos, just went with adding them to the configuration

**Comment by Tom-Willemsen** [comment]
For the original issue, assuming this was a eurotherm based on Freddie's comment about `ADDR_1` macros, this is how a eurotherm looks with no address macros set:

![image](https://user-images.githubusercontent.com/24375813/174810910-f4e20d71-bfef-4f80-8079-e34a8800e1d5.png)

i.e. all tabs are greyed out as expected signifying that no addresses are configured. @KathrynBaker can you confirm whether this the same as what you saw on ZOOM? 

If we want to make this more obvious, we could add a message on the OPI along the lines of "no addresses configured" if *none* of the tabs are enabled?

---

For a Julabo with only a port macro and no others, the IOC loads all records for me. However I wouldn't expect it to be able to communicate without setting the comms macros as detailed on the wiki (these are different for each julabo). Looking at the logs for the julabo on SANS2D on 26/05/2022 shortly before Kathryn's comment, I see the julabo had loaded it's DB records but was not communicating properly, which seems to correlate with what I'd expect if comms macros weren't set. 

@KathrynBaker can you confirm whether the issue with the Julabos on SANS2D was the PVs being in INVALID alarm, or whether it was the PVs not existing *at all*?

**Comment by KathrynBaker** [comment]
I'd agree the Eurotherm looks to be that as there was no address set it didn't quite work, so that is somewhat to be expected.

It may well be that the issue on SANS2D is just those missing macros in a similar fashion.

The confusion is coming from things like device screens etc. which are there, but if they are not in the configuration they don't start sensibly - I'm going to suggest follow up tickets that would be to add a warning for any device screen that isn't in the current configuration and therefore may not have the correct settings being shown, as well as a specific one for no addresses set in Eurotherms.

**Comment by KathrynBaker** [comment]
I can agree on the synoptics over device screens, I'm just not sure things actually work that way. A ticket means that one day we will look at it and go "oh yes, we still ought to do that" - it's one to be a reminder in about five years time rather than something to do now.

**Comment by ThomasLohnert** [comment]
Warning label is currently not very easy to read (see screenshot)
![image](https://user-images.githubusercontent.com/18398579/175337153-d78d90de-93be-41f6-9ae8-158b095535dc.png)

I don't think OPI rules handle disconnected PVs very well, this might have to be done as a script instead
