### ISSUE TITLE
web dashboard/json bourne: support https

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7156]
The web dashboards (dataweb.isis.rl.ac.uk) does not currently support `https` access, this looks to be causing issues with eduroam in some circumstances. I added a certificate to the server but if you access `'https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=larmor` in chrome with the developer tools debug console you get
```
Mixed Content: The page at 'https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=larmor' was loaded over HTTPS, but requested an insecure script 'http://dataweb.isis.rl.ac.uk:60000/?callback=jQuery321044040486312244775_1653002064842&Instrument=larmor&_=1653002064845'. This request has been blocked; the content must be served over HTTPS.
```
json bourne serves information from port 60000 but not in secure format. 

Though the issue was reported by an isis scientist connected externally via eduroam, we have been having strange issues with local visitors on eduroam being unable to connect to dashboards. This may resolve that too.  

## Acceptance criteria

* json bourne updated to serve details over https. Could probably do this from the same 60000 port as we only have one instance running.
* js file son server changed to use https

**Comment by rerpha** [comment]
potentially just need to do this https://stackoverflow.com/questions/18307131/how-to-create-https-tornado-server in https://github.com/ISISComputingGroup/JSON_bourne/blob/master/webserver.py#L92-L94

**Comment by LilithCole** [comment]
If somebody shows me where the cert and key are I'd happily just FR that

**Comment by FreddieAkeroyd** [comment]
It is IIS so was installed as per https://www.digicert.com/kb/csr-creation-ssl-installation-iis-10.htm however the cer i was sent didn't work and i had to import it "PKCS#7, PEM encoded". I am not sure where the private key is, we'll need to look at some more docs...

**Comment by FreddieAkeroyd** [comment]
https://www.digicert.com/kb/ssl-support/apache-ssl-export.htm

**Comment by FreddieAkeroyd** [comment]
Manged to extract certificates from server, briefly tested and it seems to work though it upsets existing web dashboards until they are restarted/cached cleared. It seems the browsers cache the javascript and don't check if it has changed, hence don't notice the swap to https on 60000. So we'll need to coordinate with a post to scientists. Alternative would be to setup a new port for https, but we'd need to get it opened at firewall etc. so easier just to get people to reset browsers

**Comment by Tom-Willemsen** [comment]
Dashboards all seem to be working ok for me on https; can this issue be closed?

**Comment by rerpha** [comment]
I think both work with https now

**Comment by FreddieAkeroyd** [comment]
above mentions https on 60000 but that didn't cover all situations as some places only allow https on 443, in end needed to add second IP address to server
