### ISSUE TITLE
IMAT: Setup for an experiment test by 27 June 2022

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7176]
As a scientist on IMAT I want to be able to undertake the testing of a setup for an experiment test (the full experiment will follow later in 2022, this is a test of principles) that will be using the first few days of beam in cycle 2022/02.

## Acceptance Criteria
- [ ] The Mezei flipper has been set up on IMAT

## Notes
- The Mezei flipper is a known spin flipper that already exists in IBEX, this should be a set up only requirement
- There are three motion stages in use, but they will each use the existing spare motion axis (5A) on the IMAT Galil for the following steps (for information only)
   - the axis will be connected to stage A, which will be scanned into position using neutrons - stepping through positions, judging the peak and going back to the highest point
   - the axis will then be connected to stage B, and will be scanned into position using neutrons - stepping through positions, judging the peak and going back to the highest point
   - the axis will then be connected to stage C (linear stage), which will be used and live during the experiment/testing
- The motion interactions will again be setup only, if anything is needed from experiment controls at all

**Comment by rerpha** [comment]
2 rotating and 1 tilt axes commissioned yesterday. Linear stage being commissioned today by Tom W along with Mezei Flipper.

**Comment by Tom-Willemsen** [comment]
Linear stage comissioned offline in motion lab. Comissioning on IMAT later today. 

No major complications from our perspective, mostly just needed more amps to the motor by the electronics people.

**Comment by Tom-Willemsen** [comment]
Scientists have set up the mezei flipper themselves, which seems to be talking ok.

However on reading the logs for it I noticed that they've changed from a hardcoded port 80 to a dynamic (?) port allocation, so currently it is connecting with:

```
drvAsynIPPortConfigure("L0", "ndw2310:65432:80")
```

Which seems to *work*, but isn't really correct. We should either provide a `PORT` macro defaulting to `80` that can be changed by the user, or just make it part of the `HOST` macro and remove `:80` from the `st.cmd`.

**Comment by rerpha** [comment]
> or just make it part of the HOST macro and remove :80 from the st.cmd
I think this is the best way to do it - i seem to recall other places we specify ports as part of the address

**Comment by FreddieAkeroyd** [comment]
having a separate PORT macro is good when there is a useful default, otherwise putting it as part of HOST is probably better.

It appears "ndw2310:65432:80" is actually a valid asyn address, but the 80 i think would be taken as an incoming local UDP port...

**Comment by rerpha** [comment]
not sure if there is a useful default if it keeps changing in their code! who knows what it will be next time... 😀

**Comment by FreddieAkeroyd** [comment]
I wasn't sure how often it was changing, but if it is pretty much every time then just a HOST macro mandating HOST:port syntax is probably best

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/7206 - just in case we do need to patch it over to IMAT

**Comment by Tom-Willemsen** [comment]
Final linear stage now comissioned on IMAT. Scientist is happy that he does not need any further support from us at the moment.
