### ISSUE TITLE
block server: stop popup console window when reloading archiver

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7179]
As a developer and user I do not want to see a popup console window whenever i change config. This is cause by the blockserver running a bat file to reload the archive. The same approach as in #7163 can be used

## acceptance criterial

loading/changing config does not popup window for block archive.

**Comment by rerpha** [comment]
I still get window popups, but I think they might be the IOCs themselves.. can demonstrate if helpful

**Comment by FreddieAkeroyd** [comment]
You can eliminate that by
* stop ibex server
* git pull in the top EPICS directory
* run create_icp_binaries 
* copy  cygwin1.dll from  `shares\ISIS_Experiment_Controls\data for tickets\Ticket7179` to `tools\master\cygwin_bin`
* start ibex server
at this point you should have no flashing window. This is the fixed cygwin dll that i am trying to find an alternative to ...
