### ISSUE TITLE
IBEX: stop flashing popup console windows

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7181]
As a user and developer I do not want to see flashing console windows when I start ibex or change configurations. The windows are caused by console programs starting consoles and come from three sources:

- nicos git window on connection (and reconection) (#7163)
- blockserver running bat file to reload archiver on config load/change (#7179)
- procServ starting IOCS (the majority and this ticket)

## to test

* stop ibex server
* checkout the five ticket PRs linked below and then run `create_icp_binaries` and `make iocstartups` in top EPICS directory
* `git checkout master && git pull` in  `ISIS/ScriptServer/master` to make sure up to date with the nicos fix from above 
* start ibex server

at this point you should have no flashing windows from anything. 

## acceptance criteria

* various ibex opeations performed, such as start/stop ibex server, start/stop iocs, change configuration etc. with no flashing window appearing and everything performing as expected

## after merge

delete `cygwin_bin` and `cygwin_bin64` from
`Kits$\CompGroup\ICP\Binaries\EPICS_Tools`  once merged as they will no longer be needed (leave the `cygwin` directory which is the new mini-install tree that will now be copied and used)

**Comment by FreddieAkeroyd** [comment]
I can remove the procServ issue by an addition to the cygwin DLL, modifying the code that emulates a linux fork() to allow an environement variable `CYGWIN_FORK_HIDEWINDOW` to be set to hide any console window created as part of the fork(). Will see if any other options work, did try linking procServ as a purely windows app and also creating a special launcher for the `runIOC.bat` but it looked like this was not working. But will maybe check approach with a simpler example.

**Comment by FreddieAkeroyd** [comment]
OK, change of plan - can remove window by rearranging how we call cygwin.  It looks like if we ship a mini cygwin tree that has e.g. terminal and device file, then we don't get a flashing window.

**Comment by rerpha** [comment]
Does https://github.com/ISISComputingGroup/EPICS-gateway need to be updated too? Looks like it calls cygwin in some of its start/stop scripts
