### ISSUE TITLE
ENGIN-X INSTRON/ARACCESS inconsistently creating log files [timebox: 2 days]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7204]
## Where?

ENGIN-X, using the ARACCESS IOC to put values from the stress rig IOC into data files in `c:\logs\INSTRON_01`.

## How?

Instrument scientist reports that ARACCESS is:
- Inconsistently creating log files
- Missing some data in continuous files, that is later found to be present in the full log file
  * Scientist reports that the continuous file "misses" values in the middle of the file, i.e. it is not just a file-flushing problem

## Reproducible?

No - inconsistent at least. I was not able to reproduce this with the scientist, but the scientist reports that they previously did the exact same steps with no file being created.

### To Reproduce

- Turn on both stress rig and ARACCESS ioc.
- Turn logging on, wait a while, then turn logging off
- If issue is present, then log files may not be generated

## Acceptance criteria 
- [ ] Cause of issue is understood
- [ ] Test written to reproduce issue
- [ ] Issue fixed

Suggest timeboxing this ticket.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by NikolaRoev** [comment]
Fix for missing `Run Number`: https://github.com/ISISComputingGroup/IBEX/issues/7315. If missing values mentioned in issue are just `Run Number`s this should solve that.

[Branch](https://github.com/ISISComputingGroup/system_tests/tree/Ticket7204_fix_archiver_access_log) with system tests added for `ArchiverAccess`. I was not able to consistently reproduce any issue with the logs but these tests have had a failure every run.

Encountered issues:
- Missing `Run Number` (most likely solved).
- The continuous, full, or either log would not be generated. Log generation would also sometimes take a long time.
- Duplicate data entries. A range of timepoints would be duplicated multiple times. Happened in either log. This was consistent for a while but stopped. Possibly local issue with my machine.
- A single data entry would be missing from one log but be present in the other. This was the only consistent issue I was able to reproduce running the tests.

**Comment by Tom-Willemsen** [comment]
@NikolaRoev if you've reached the end of the timebox and there are still outstanding issues as you've described, could you write up some tickets for the issues you've found (and maybe propose the most important/consistent one)?

**Comment by ConorMFinn** [comment]
@NikolaRoev Review of work done:

- [ ] The system test seems to be sensible from a code review standpoint (there's a few minor style issues but nothing major). Were the failures you were experiencing on each run consistent or different each time? If they're consistent, a ticket to include the test and fix the consistent issues would be nice to have.
  - Also, unsure if this is expected, but when running the test module locally it appears not to generate any logs for all 3 tests. 

> A single data entry would be missing from one log but be present in the other. This was the only consistent issue I was able to reproduce running the tests.

- [ ] This seems like it could do with ticket that's proposed, given it's consistent.

> The continuous, full, or both logs would not be generated. Log generation would also sometimes take a long time.

- [ ] This could also do with a ticket. 

When these tickets are written, could you make sure that they link back to either the branch you've created for the new system test or to a PR for it?

**Comment by ConorMFinn** [comment]
New issue created at https://github.com/ISISComputingGroup/IBEX/issues/7372

Not proposing the new one yet, we'll wait and see if ENGIN-X complain about it again after the new Instron setup.
