### ISSUE TITLE
RIKEN/TPG300: Test TPG300 extensions against hardware

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7205]
## Where?

We made changes to the TPG300 IOC in https://github.com/ISISComputingGroup/IBEX/issues/5877, these changes should be tested against hardware to make sure they work correctly.

## Acceptance criteria 
- [ ] All existing functionality still works
- [ ] All functionality in above-mentioned ticket has been tested on hardware
- [ ] All issues found in testing have been fixed, or new issues created for the fixes

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
test what is possible of new functionality, but most important is to check existing functionality still works

**Comment by Tom-Willemsen** [comment]
Did hardware testing on a TPG300 on vesuvio. Fundamentally we can still read pressures, which is the main functionality I was worried about breaking.

Problems found in testing:
- Setting `UNITS:SP` to something other than `mbar` causes `UNITS:SP` to get reset to empty string. `UNITS` still updates correctly, so this seems non-critical (and may be why our tests did not catch this)
- I was unable to change the switching functions (which is the main new functionality that was added). Error is:
```
2022/07/26 16:20:40.904405 L0 IN:VESUVIO:TPG300_01:FUNCTION:ASSIGN:SP:OUT: Input "<15>"
2022/07/26 16:20:40.904423 L0 IN:VESUVIO:TPG300_01:FUNCTION:ASSIGN:SP:OUT: mismatch after 0 bytes ""
2022/07/26 16:20:40.904432 L0 IN:VESUVIO:TPG300_01:FUNCTION:ASSIGN:SP:OUT: got "<15>" where "<06>" was expected
```
- All relay contacts on vesuvio are off. We will need to test this when we get access to a RIKEN TPG300 where the relay statuses are meaningful.

**Comment by JackEAllen** [comment]
> Did hardware testing on a TPG300 on vesuvio. Fundamentally we can still read pressures, which is the main functionality I was worried about breaking.
> 
> Problems found in testing:
> 
> * ~Setting `UNITS:SP` to something other than `mbar` causes `UNITS:SP` to get reset to empty string. `UNITS` still updates correctly, so this seems non-critical (and may be why our tests did not catch this)~
>   
>   * Seems to also happen on master, so not critical, but should be fixed when we get an opportunity
> * I was unable to change the switching functions (which is the main new functionality that was added). Error is:
> 
> ```
> 2022/07/26 16:20:40.904405 L0 IN:VESUVIO:TPG300_01:FUNCTION:ASSIGN:SP:OUT: Input "<15>"
> 2022/07/26 16:20:40.904423 L0 IN:VESUVIO:TPG300_01:FUNCTION:ASSIGN:SP:OUT: mismatch after 0 bytes ""
> 2022/07/26 16:20:40.904432 L0 IN:VESUVIO:TPG300_01:FUNCTION:ASSIGN:SP:OUT: got "<15>" where "<06>" was expected
> ```
> 
> * All relay contacts on vesuvio are off. We will need to test this when we get access to a RIKEN TPG300 where the relay statuses are meaningful. This is new functionality
> 
> I've created and proposed #7255 to actually investigate/fix these issues for RIKEN

Seems reasonable and new Issues describes what needs to be done. I would like to see some form of testing instructions added the the issue description to duplicate some of the testing you have done as part of this issue in #7255 so a reviewer can be explicit when testing work when completed.

**Comment by JackEAllen** [comment]
Happy with the test instructions so marking this as complete 👍
