### ISSUE TITLE
Add system test to confirm can begin without rb number / instetc

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7208]
This is a test of  ISISComputingGroup/genie_python#364   on WISH they were unable to begin a run because it could not print the current rb number to scrteen. This ticket is to test that begin is not dependent on such information, so sould need to follow the actiosn as listed on the ticket i.e.

* check DAE in SETUP
* Stop the INSTETC ioc
* check get_rb_number() fails
* begin run
* check DAE in RUNNING state
* restart instetc
* check get_rb_number() works

**Comment by aaron-long** [comment]
- Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7226
- PR: https://github.com/ISISComputingGroup/system_tests/pull/86
