### ISSUE TITLE
TTIPLP: implement overcurrent and overvoltage protection trips

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7213]
## Where?

As a user on SANS2D, I would like to implement overcurrent and overvoltage reporting in the TTIPLP driver. This caused confusion as one of their power supplies had tripped but this was not clear from IBEX.

## How?

Implement the "limit event status" command in the TTIPLP driver (the command is `LSR1?` or `LSR2?` for power supplies 1 & 2 respectively).

Specifically we are interested in bits 2 & 3  (OCP and OVP) but all bits would be useful to read and log.

The command to read these bits *may* also clear them, so we may need to implement some form of latching in the IOC.

Consider also implementing `TRIPRST` (reset all trip conditions) at the same time.

## Acceptance criteria 
- [x] OCP and OVP errors can be read from IOC and OPI

## How to Test 
We have the physical device, so that should make testing easier. Most of thes

1. Set the voltage trip value to 1V, set the current trip to 1A. 
2. Set the voltage to 0.5V and the current to 0.05A
3. The volt limit light should come on to indicate that the voltage is the current limiting factor. 
4. Set the voltage to 2V
5. The voltage trip light should come on, an alarm should be triggered, the output should be set to OFF. 
6. Click the reset button, the alarm should be cleared and the light should go off. 
7. Set the voltage back to 0.5V. (Remember to switch the output back on)
8. Set the current stip to 0.001A, set the volt limit to 5V, set the volts to 4V, similar trip but for current this time
9. Set the voltage to 4V, volt trip to 5V, current to 0.02A, current trip to 0.5A. You should see the current limit light switch on

**Comment by ConorMFinn** [comment]
Todo:
- [ ] Determine if reading from the the `LSR1?` and `LSR2?` registers also clears them
- [ ] Implement the functionality into the [emulator](https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/blob/9ec4636b4e1850356559b977d6797026239d58ac/lewis_emulators/ttiplp/device.py)
- [ ] Write additional [tests](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/master/tests/ttiplp.py) for new functionality.
- [ ] Add functions to the [proto file](https://github.com/ISISComputingGroup/EPICS-Ttiplp/blob/master/ttiplpSup/ttiplp.proto) to access the registers 
- [ ] Add functions to the ioc [db file](https://github.com/ISISComputingGroup/EPICS-Ttiplp/blob/master/ttiplpSup/ttiplp.db#L8) to read from the registers and (potentially) store them until `TRIPRST` is called. These should probably appear as alarms in the GUI. 
- [ ] Implement `TRIPRST` to reset the trip conditions
- [ ] Do we need trip warning light/switch/thing on the [opi](https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.opis/resources/ttiplp.opi)?
