### ISSUE TITLE
Reflectometry: Wrong Velocity Being Cached [Timebox: 3 days for 2 people]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7215]
As a user of the reflectometry server, I would like to be sure motor axes are reliably restored to their pre-move velocity after a coordinated move.

At the moment, it appears there is a bug that results in the wrong velocity (i.e. the slower velocity set for the coordinated move) being saved to the autosave file which is used for restoring it post move. The cache restore logic is handled by some logic based on events in the reflectometry server and by monitoring DMOV. I have not been able to identify a clear pattern to when this happens, could be down to a race condition or a specific case that isn't appropriately covered by the logic.

### Acceptance Criteria
- [ ] Find the reason the wrong velocity gets cached sometimes
- [ ] Change the code so it does not happen anymore
- [ ] Add appropriate tests

### Extra Information
_Why it is needed?_
This is a nuisance for reflectometry users if they want to move motor axes directly as they either need to endure extremely slow moves or frequently reset the velocity by hand. Either way, this wastes a lot of their time.

_Where required files/links are_
Relevant files to look at are most likely:
- `ReflectometryServer/ioc_driver.py`
- `ReflectometryServer/pv_wrapper.py`

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by pheest** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/45
