### ISSUE TITLE
GUI: Spectra OPIs in DAE not always connecting

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7216]
As a user of the IBEX client, I would like to be able to see all spectra plots on the DAE immediately when I open the relevant tab.

POLREF have reported a bug where currently, some or all of the spectra OPIs show as disconnected initially. The workaround they have used is to keep resetting the layout until all plots have successfully connected. 

Not sure if this has been observed anywhere else, please comment if you can confirm or deny whether this is a problem on other beamlines

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Spectra plot OPI reliably connects on first try

## How to Test

@ThomasLohnert is this easily reproducible (on POLREF)? Otherwise more a test it doesn't make things worse.

* `caget %MYPVPREFIX%DAE:SPEC:1:1:Y.STAT` and `caget %MYPVPREFIX%DAE:SPEC:1:1:Y.UDF` will not work before PR but will afterwards
* GUI panel does not show disconnected spectra or pink border
* you can set `var isisdaePCASDebug 1` in the isisdae IOC console window and it will print a message each time an update  timer expires, a spectra pv is updated (scanned),  and interest (basically a camonitor) happens to a PV. You should only see expiring timers for items being monitored, a caget on an unmonitored PV will just print a "doscan" message to console.   Previously there would have been a lot of unnecessary scans on items that were no longer of "interest", but you would need to back port a few print statements to show this. 
* it is hard to reproduce the original issue, it may require a slower computer than most developers desktops  
* There is an additional path to get a pink border on a plot that happens if the Mode: (cound/us or counts) box doesn't get created properly (it looks blank). This is a separate GUI issue and not covered in this ticket.

**Comment by davidkeymer** [comment]
@FreddieAkeroyd  will check whether or not a  ticket exists for the issue mentioned in his comment above.

**Comment by FreddieAkeroyd** [comment]
Trying to remove old PVs/spectra looks a bit messy, however though memory can get a bit large it is not the biggest issue. The failing to connect may be due to there being too many slow scan timer loops left running after a scan, so have attempted to improve the performance of this  

* Do not slow scan PVs that are not being monitored
* Reduce scan rate on fixed pvs that do not change

In addition, i have occasionally seen a pink border arounf a plot so also tried

* Remove alarm level limits on axis PVs
* Add SEVR STAT and UDF fields to data arrays (though not sure if GUI accesses these)

**Comment by LilithCole** [comment]
Happy with the changes once I got my head around them, but my server has fallen over at some point so I'm rebuilding in order to check it actually runs. Sadly not going to be ready before review/retro at this point, but _pretty much certain_ it'll go straight to review complete

**Comment by LilithCole** [comment]
Seems to be working (or at least not breaking on my machine), only issue is that I'm unable to check the extra logging, getting this error when attempting to change debug level:
![image](https://user-images.githubusercontent.com/52697922/189363004-8025c890-4e33-48d0-9bde-e5d0ad3e4833.png)

**Comment by FreddieAkeroyd** [comment]
Did you rebuild your `isisdae-ioc-01` ioc after rebuilding `support\isisdae` ?
