### ISSUE TITLE
ZOOM 17T Birmingham Magnet: Test New IOC and OPI on Hardware

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#7217]
## Where?
Test IOC and OPI on Hardware for the 17T Birmingham Magnet in advance of experiment taking place in November 2022 and make changes where applicable if things do not work as expected, making sure to update the emulator also where needed.

## How?
A new emulator, IOC and OPI have been developed for the 17T Birmingham Magnet based on the LabVIEW as part of **[this issue](https://github.com/ISISComputingGroup/IBEX/issues/6850)**.

The IOC, and OPI have not yet been tested with the real hardware which will no be accessible until October 2022 ready for an experiment in November (specific dates yet to be confirmed).

## Acceptance criteria 
- [ ] IOC has been tested on hardware and communicates well with the device
- [ ] OPI has been tested with the IOC on the Hardware. 
- [ ] Emulator and system tests are updated if changes are required during testing.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

### Additional Notes:
* Support:  https://github.com/ISISComputingGroup/EPICS_17T_Birmingham_Magnet/tree/main
* IOC: https://github.com/ISISComputingGroup/EPICS/tree/6850_17T_birmingham_magnet_support
* OPI:https://github.com/ISISComputingGroup/ibex_gui/tree/6850_b17tmag_opi
* Manual Locations: 
    * /Manuals/Birmingham_17T_Magnet/Birmingham 2017T 20Magnet.pdf
    * /Manuals/Birmingham_17T_Magnet/Birmingham 2017T 20Magnet 20RS232 syntax 20v4.6.pdf

**Comment by JackEAllen** [comment]
Currently, the experiment requiring the 17T Magnet is Scheduled for 9th November 2022. The magnet should be available a couple of weeks prior to this date in the Mag Lab. I will update this issue with a date from which we can begin testing the magnet once confirmed.

**Comment by JackEAllen** [comment]
Arrival date of 17T Mag not confirmed, but at the earliest, 1st November, but likely 3rd or 4th November so best to follow up for arranging a date for testing around this time in advance of beam on the 9th November with Zoom. Magnet should be installed on the test stand in the cryo lab for testing IOC and OPI.

**Comment by LilithCole** [comment]
A couple of minor issues:
- ready light logic is inverted
- comms errors flashing due to polling too quick

Will link fixes here then put in impeded until magnet is cool and either something breaks, at which point I'll put it back in in progress and fix it, or everything's fine, and I'll put it through to review.

**Comment by LilithCole** [comment]
Small changes mentioned earlier, magnet was used by ZOOM with no other issues besides an adapter needing to be replaced.

[support](https://github.com/ISISComputingGroup/EPICS_17T_Birmingham_Magnet/pull/3)
[Release Notes](https://github.com/ISISComputingGroup/IBEX/pull/7527)
