### ISSUE TITLE
Training: Run a User Course

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7219]
As someone who is new to IBEX I'd like to learn how to use it

## Acceptance Criteria
1. A course is scheduled 
1. The course content is updated as appropriate
1. The setup for the course is undertaken, enough sandbox instruments are available
1. The attendees are identified and contacted with the information of when the course will be
1. The course happens

## Notes
1. https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Training-Instrument-Scientists-in-IBEX has information about running training courses
1. This really needs to happen, KB to find the specific date it needs to happen by

## Timestamp in planning meting
0:00 4/4/24

**Comment by KathrynBaker** [comment]
This is likely to go over the next two sprints, but ensuring that the date is set soon is in everyone's best interest

**Comment by ThomasLohnert** [comment]
+1 from Excitations group (new starter)

**Comment by KathrynBaker** [comment]
We will aim to run this at Easter

**Comment by LilithCole** [comment]
Request from riken to have the option to do this entirely in the morning , and virtually so that Japanese scientists can benefit

**Comment by FreddieAkeroyd** [comment]
See #8293

**Comment by LilithCole** [comment]
Training course was run on 17/04/24
