### ISSUE TITLE
ibex install: stop multiple python installs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7227]
The ibex install script, certainly as used for system tests, installs python twice. It installs python separately, then calls the GUI `install_client.bat` that installs both the GUI and an external genie python.

* locate all places where `install_client.bat` is used in the ibex installer
* if genie python is already installed separately in this pathway, replace `install_client.bat` with `install_gui_with_builtin_python.bat`  

If a place is found where `install_client.bat` is used but genie python is not installed separately, consider changing to explicitly install genie python and then call   `install_gui_with_builtin_python.bat`  instead as this give a finer degree of control if needed

## Acceptance criteria

* genie python is only installed once during an ibex install

**Comment by aaron-long** [comment]
- PR: https://github.com/ISISComputingGroup/ibex_utils/pull/126
- Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7231
