### ISSUE TITLE
FMR: allow standalone control of VNA

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7228]
As a POLREF scientist/user I want to control the VNA (vector network analyser) on its own as well as part of the rest of the FMR kit. 

Currently the IOC runs on an NDW which goes around with this kit. 

We should modify the existing IOC to take a macro of whether or not the VNA is being used on its own or alongside the rest of the FMR kit. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [x] Macro is added to control just the VNA or all the FMR kit 
- [x] LVDCOM wrapper is added for the VNA on its own, as the VI is different. 
- [x] Above is deployed on NDW that runs the kit

### Extra Information
an OPI is probably not needed at this time as the VNA can be controlled via blocks. 

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
above patched over and scientist is happy that they can talk to the VNA on its own. 

NB this is only a temporary solution, the long term solution is likely going to be that we talk to the kit individually from IBEX, so didn't bother trying to be clever about duplication etc. in the db file and so on.

**Comment by Tom-Willemsen** [comment]
This is fine as a temporary solution; plan is for a requirements meeting to figure out longer-term plan for this equipment.

Also note POLREF are just using the usual FMR opi for this, with several disconnected fields.
