### ISSUE TITLE
Shadow user & developer manuals: serve over https as well.

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7229]
## Where?

https://shadow.nd.rl.ac.uk/ibex_user_manual/Home

## How?

- `https://shadow.nd.rl.ac.uk/ibex_user_manual/Home` does not work to get to the wiki (404)
- `http://shadow.nd.rl.ac.uk/ibex_user_manual/Home` does work
- Modern browsers will auto-correct `http` to `https` where available, this means that the user manual link accessed from `Help -> User manual` does not work when opened in a modern browser configuration (e.g. IDAAS, scientist desktop installs)

Edit the apache webserver configuration on shadow to serve the manual over both http and https.

## Reproducible?
Yes

### To Reproduce
Visit https://shadow.nd.rl.ac.uk/ibex_user_manual/Home , notice that it 404s.

## Acceptance criteria 
- [ ] https://shadow.nd.rl.ac.uk/ibex_user_manual/Home works

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
`https` now works, there is a redirect on `http` but also updated GUI links to use `https` directly

**Comment by rerpha** [comment]
the genie python docs link seems to still try and get http rather than https?

**Comment by rerpha** [comment]
i think they might be loaded by an external web page actually, sorry

**Comment by FreddieAkeroyd** [comment]
no problem, thanks for checking, we do need to update the external page though. I see it comes from `weblinks.opi`

**Comment by FreddieAkeroyd** [comment]
address in weblinks and target page now updated to https
