### ISSUE TITLE
jaws: centre moving if one motor stalls

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7234]
There has been a recent issue on INTER where one of the axes stalled and this caused the centre to move. Actually both blades failed to move, but one said it was on a limit whereas one stalled and this difference in behaviour caused the drift as the motor record VAL was updated in one case the then propagated back.

The best option may be to remove any feedback from the low level motor VAL to top level setpoints

## acceptance criteria

* new system tests fail before PR but pass afterwards
* moving jaws from GUI works as expected
* set centre on gui, then change a motor on low level motor screen, then set gap on GUI restores original centre
* set a gap or centre at high level, then when moving stop motion early at lower level motor screen. Jaws setpoint should go into alarm at higher level opi.

**Comment by ThomasLohnert** [comment]
By "Top level setpoints" do you mean PVs coming from the Jaws motor abstraction or reflectometry server PVs?

To clarify, the reflectometry server does not monitor any setpoint PVs, and does not care if they change at a lower level, they are write only

**Comment by FreddieAkeroyd** [comment]
It may need a discussion with scientists as it will mean that moves on the low level table will get overwritten e.g. if they move one or both blades to change the centre and/or gap at the low level. then:
* setting a new gap at the high level will restore the previous centre
* setting a new centre at the high level will restore the previous gap
However it may be this behaviour will lead to less potential lost time

**Comment by FreddieAkeroyd** [comment]
PRs:

https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/45
https://github.com/ISISComputingGroup/EPICS-jaws/pull/18
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/547

**Comment by FreddieAkeroyd** [comment]
Instruments wishing to use the autosave feature will also need `jaws.cmd` updating to add `IFINIT_FROM_AS=$(IFINIT_JAWS_FROM_AS=#),IFNOTINIT_FROM_AS=$(IFNOTINIT_JAWS_FROM_AS=)` e.g.
```
$(IFIOC_GALIL_01=#) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS0:,mXN=MTR0101,mXS=MTR0103,mXW=MTR0102,mXE=MTR0104,IFINIT_FROM_AS=$(IFINIT_JAWS_FROM_AS=#),IFNOTINIT_FROM_AS=$(IFNOTINIT_JAWS_FROM_AS=)")
```
This can be done everywhere as default is not to use autosave, and doesn't need to do done if autosave feature is not required

**Comment by rerpha** [comment]
great, thanks, we should do #7504
