### ISSUE TITLE
IOC Selection dialog: allow search on IOC name

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7236]
## Where?

As a developer/user, I would like to be able to add IOCs to my configuration if I know the ioc name.

This is exemplified by trying to add `SIMPLE` to a configuration - it is not obvious that this is found under a "Basic IOC providing simple data types" description - needing an experienced user who knows the IOC name they want to add to have to expand all descriptions until they find the IOC they need. But the problem is more general than simply fixing a few ioc descriptions.

This should apply to both the add ioc dialog in configuration menus, and also the start/stop ioc dialog.

## How?

Add a search function to the IOC selection dialog which matches both the description and the ioc name. This way an experienced user could search for `SIMPLE`, `EUROTHRM`, etc, and be presented with a relatively small number of matches. The search should also match the IOC description text.

## Reproducible?

Yes

## Acceptance criteria 
- [ ] If I know the name of an IOC, I can add it to my config easily, regardless of knowing/not knowing it's IOC description
- [ ] If I know some of the description of the IOC, I can add it to my config easily
- [ ] Specific example usages:
  * If I search for `EUROTHRM_01`, I am presented with a single option (`EUROTHRM_01`)
  * If I search for `eurothrm`, I am presented with all possible eurotherm IOCS (`EUROTHRM_01`, `EUROTHRM_02`, etc)
  * If I search for `LKSH`, I am presented with all the iocs for each type of lakeshore controller (`LKSH336_01`, `LKSH340_01`, etc)
  * If I search for `temperature`, I am presented with all iocs that contain "temperature" in their IOC description
  * If I don't enter anything in search box (default), then the menu contains the same options as currently.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
I've put this as training on the basis that:
- The relevant dialogs already exist and would only need a search bar adding
- The change is relatively low-risk and tightly confined to the UI, unlikely to spiral into a bigger issue
- We have an example of a *mostly* similar search functionality in the PV selection dialog for blocks. Other examples of searching/filtering in the GUI are in the ioc log and journalviewer perspectives.

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1449
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7251
