### ISSUE TITLE
Review IOC descriptions

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7237]
## Where?

As a user/developer, I would like the IOC descriptions to be as consistent as possible

We now use the IOC descriptions much more prominently, for example in IOC start/stop menu and configuration menus. We should go through our IOC descriptions and make them as consistent as possible so that they are useful for our users.

Some examples:
- `SIMPLE` -> `Basic IOC providing some PVs for simple data types`
  * This is not useful for a user, and developers wanting to use simple are unlikely to think of this description as the first place to look for `SIMPLE`.
- `ROTSC` -> `The HRPD/GEM/POLARIS sample changer`
  * This causes the IOC to be grouped alphabetically under `T` which isn't logical for this IOC. Suggest that our new convention should always omit a leading "The".
 - `TTIEX355P` -> `TTIEX355P`
   * The description here provides no more context than the IOC names used to. Suggest that our new convention always include manufacturer/model name in a human-readable form where appropriate.
 - `ZFMAGFLD` -> `Zero field controller field strength` vs  `ZFCNTRL` -> `Muon zero field controller`, these should logically use a similar naming scheme

## How?

**Step 1:** decide on a convention for IOC descriptions. While some IOCs might need more/less info in their descriptions, we should document some general guidelines for what they should include and what they should (generally) look like. Agree this with team (can be a discussion on teams technical channel or similar).

**Step 2:** review *all* of our existing descriptions against these new guidelines, adjusting/clarifying any descriptions as necessary.

## Acceptance criteria 
- [ ] A documented convention for IOC descriptions exists on the wiki
- [ ] Our existing IOC descriptions follow this standard as closely as reasonably possible

## How to Test 

1. Check that the convention is on the wiki (https://github.com/ISISComputingGroup/IBEX/issues/7237#issuecomment-1219772633)
2. Check in the GUI that you have a few too many IOCs listed under "The", and that a few of the IOCs listed in https://github.com/ISISComputingGroup/IBEX/issues/7237#issuecomment-1225974538 don't follow the convention
3. Stop your IBEX server and GUI
4. Pull the appropriate branches from git
5. From an EPICS command prompt in the root EPICS folder do the following: `make iocstartups`
6. Restart your IBEX server
7. Reopen your GUI
8. Check that the IOC list is now following the convention
9. Double check that there are no spelling mistakes or issues in any of the changed descriptions

NOTE
If the GUI hasn't updated with the new descriptions after a restart of both aspects then something isn't going right for the update which should be running as far as I'm aware. Please create and propose a separate ticket to resolve that issue, and run `iocdb.sql` which is in `EPICS\iocstartups` directly by hand

**Comment by KathrynBaker** [comment]
I'm about to pull together a list of the items we support (a long standing item on my to do list) - it would make sense if I at least identify the items that don't correspond to a TBD standard - I may even fix them if things do stay this quiet.

**Comment by KathrynBaker** [comment]
I have added the following page to the dev wiki: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Descriptions
It is linked to from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOCs

**Comment by KathrynBaker** [comment]
Accidentally changed on master directly (already reviewed, some had further changes which are listed below in the EPICS-IOC changes):
CAENV895
CONTROLSVCS
COUETTE
CP2800
CRYVALVE
DETADC
DG645
DMA4500M
EGXCOLIM
EUROTHRM
FERMCHOP
FINS
FLIPPRPS
FMR
GEMORC
HAMEG8123
HIFIMAG
HIFIMAGS
HLG
HLX503
HUBER

IOC Descriptions Changed in EPICS-IOC:
B17TMAG
BGRSCRPT
CAENMCA
DETADC
FMR
HLG
HVCAENA
HVCAEN
ILM200
INDFURN
INHIBITR
INSTETC
IPS
ISISDAE
KEYLKG
KHLY6517
KNRK6
LKSH460
MERCURY
MEZFLIPR
MUONJAWS
MUONTPAR
NANODAC
NEOCERA
NGPSPSU
NWPRTXPS
PEARLPC
PSCTRL
PT2025
QEPRO
REFL
RKNDIO
ROTSC
ROTSTIRR
RUNCTRL
SAMPOS
SDTEST
SECI2IBEX
SEPRTR
SM300
SP2XX
SPINFLIPPER
SPRLG
STPS350
STSR400
TC
TECHNIX
TEKAFG3XXX
TEKDMM4040
TEST
TIZR
TJMPER
TPG26X
TPG300
TPG36X
TRANTECH
TRITON
TTI355
WBVALVE
WEBCAM
ZFCNTRL
ZFMAGFLD

Other Repos where changes were made:
SIMPLE IOC
ChopperSim

Changed in build_ioc_startups.py:
ALARM
ARACCESS
ARBLOCK
ARINST
BSKAFKA
