### ISSUE TITLE
Schneider PLC IOC: Refactor to make generic

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7240]
As a developer, I would like the existing Schneider PLC IOC to be generic enough for any application.  Currently it seems to be specifically configured for GEM(?) and only reads two hard-coded addresses for a heartbeat and a gate-valve.

### Notes

- This is required for the PLC that will be used on RIKEN as part of the refurbishment project.
- The IOC appears to support MODBUS over TCP, which is required for RIKEN.  However, the IP address macro has a default value and should be removed.

**Comment by rerpha** [comment]
perhaps best to follow how the omron/FINS does it? https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Omron-FINS

**Comment by FreddieAkeroyd** [comment]
The changes will work as is on GEM as it defines `IPADDR`, the removed default IP was for a test PLC in R3
