### ISSUE TITLE
IBEX install: fails if partial release

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7250]
running ibex deployment fails for 10.0.1 as it tries to install epics and genie_python from the 10.0.1 directory but there is only a client there. Trying to pass a different server directory to `instrument_deploy.bat` is not supported (it is by the python called). Normally you would have 10.0.0 already installed and then only choose to install e.g. client, but currently there is no easy way to start from an earlier installed version and update to 10.0.0 (python + server) and 10.0.1 (client)     

## Acceptance criteria

* A partial ibex release e.g. 10.0.1 does not break installs of other ibex components 
* should it pick latest release of each component e.g. mix of 10.0.0 and 10.0.1 as appropriate?

**Comment by KathrynBaker** [comment]
Suggested solution in considering this - was to use simulated links/similar
