### ISSUE TITLE
IOC & OPI for T-Jump Cell (Phase 1)

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7253]
As a: SANS scientist, I would like an IOC and OPI to control a T-Jump cell created in house. This cell allows you to rapidly change the temperature of a sample by swapping out a block in contact with a given sample for a block of a different temperature to effect a rapid temperature change.

This is the ticket for Phase 1 of the T-Jump apparatus (driver for the device which undertakes the temperature jumps)

### Acceptance Criteria
- [ ] There is an IOC for the T-Jump device in accordance to the spec document
- [ ] There is an OPI for the T-Jump device in accordance to the spec document
- [ ] There is a device emulator which simulates input/output of the T-Jump device
- [ ] There is a set of IOC Tests which tests the behaviour of the IOC against the device emulator

### Extra Information
Detailed information for the entire T-Jump apparatus can be found [HERE](https://stfc365.sharepoint.com/sites/ISISProject-813/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FISISProject%2D813%2FShared%20Documents%2FGeneral%2FTechnical%20documentation%2F01%20Design%2FSoftware%20Work%20Package&viewid=f91da496%2D72ac%2D4e58%2D90fe%2Dfceba8e86f54)

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/EPICS-tjmper/pull/1
https://github.com/ISISComputingGroup/EPICS/pull/291
https://github.com/ISISComputingGroup/EPICS-ioc/pull/710
https://github.com/ISISComputingGroup/ibex_gui/pull/1453

**Comment by rerpha** [comment]
Looks good, but think we can use templating and possibly skip the recsim tests if functionality is covered with emulator. @NikolaRoev  if you need a hand let me know! 

OPI looks good, have added default TJMPER macro for ease of use.
