### ISSUE TITLE
ibex device generator: consolidate location of ioc template files

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7263]
The ioc device generator has some ioc template files similar to what EPICS `makeBaseApp.pl` has. It uses makeBaseApp for the ioc boot area but not the support module. I feel this is slightly confusing as it means that a normal makeBaseApp and the device generator do not give the same result, is there any reason all the templates could not be in the standard area?  

## Acceptance criteria

* same set of templates used in all cases

**Comment by NikolaRoev** [comment]
The device generator is using `makeSupport.pl` from `asyn` rather than `makeBaseApp` from `EPICS/base`, but it does not have its own templates. After a discussion with Freddie this is fine for the moment.
