### ISSUE TITLE
IOC Test framework: refactor device disconnection logic

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7266]
## Where?

In many of our IOC test suites, we are simulating device disconnection using a code block that looks something like:

```python
    @contextlib.contextmanager
    def _disconnect_device(self):
        self.lewis.backdoor_set_on_device("connected", False)
        try:
            yield
        finally:
            self.lewis.backdoor_set_on_device("connected", True)
```

which is used like:

```python
    @parameterized.expand(parameterized_list(READ_PVS))
    @skip_if_recsim("Requires emulator backdoor")
    def test_WHEN_device_disconnects_THEN_pvs_go_into_alarm(self, _, pv):
        self.ca.assert_that_pv_alarm_is(pv, self.ca.Alarms.NONE)

        with self._disconnect_device():
            self.ca.assert_that_pv_alarm_is(pv, self.ca.Alarms.INVALID, timeout=30)

        self.ca.assert_that_pv_alarm_is(pv, self.ca.Alarms.NONE, timeout=30)
```

With corresponding `device.connected` attributes and `@conditional_reply("connected")` decorators on the emulator side.

There are several examples where this pattern is used verbatim e.g. [1](https://github.com/ISISComputingGroup/EPICS_17T_Birmingham_Magnet/blob/8bbf867bd1d35bca8d07c2caefe8508a2f6ba558/system_tests/tests/b17tmag.py#L131) [2](https://github.com/ISISComputingGroup/EPICS-Technix/blob/a27780f4e62926242dd6f5e4917380994404970e/system_tests/tests/technix.py#L111) [3](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/5f681796c8764a49672b38a612e711c28a5324d3/tests/lakeshore372.py#L66), and also some examples where we have written functionally similar code to achieve the same goal, for example [1](https://github.com/ISISComputingGroup/EPICS-knrk6/blob/473998bff8e708b7c79364d4cf54752def0b7154/system_tests/tests/knrk6.py#L47) [2](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/bd85ad9635aa94b1009e56c34d9719847e346b5e/tests/flipprps.py#L45) [3](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/5f681796c8764a49672b38a612e711c28a5324d3/tests/chtobisr.py#L43) (with varying levels of error resilience, re-connection checking, checking all readbacks, etc).

We should reduce this duplication of similar code accross our test suites.

## How?

Move the context manager noted above into the IOCTestFramework itself as a utility function. Refactor the tests which use this context manager or a functionally similar pattern to use the common utility.

Note that the examples above are just a few examples - we should search **all** ioc tests for similar patterns and refactor them to use the common utility. 

As a starting point, a recursive search for `backdoor_set_on_device("connected", False)` in `.py` files in `c:\instrument\apps\epics` should find most occurences where this is used. Note that not all tests are in `support/IOCTestFramework/master` - some are in device-specific modules.

## Acceptance criteria 
- [ ] Code duplication in IOC test suites is reduced
- [ ] Documentation exists on the wiki/ioc testframework README for how to use the new utility function
- [ ] All modified test suites still pass as before
- [ ] If an assertion fails in one test, the `connected` attribute is put back before the next test runs. This is handled by the `try-finally` in the context manager above

## How to Test 
 - **Check logic** of refactored logic looks sensible 
 - Run tests for modules where **emulator files** have been **changed**
 - Run tests where desired for modules with **more complex refactoring**
 - Check **Jenkins** after merge!

**Comment by boeuf-codes** [comment]
Found an issue with sm300 test module (`sm300.Sm300Tests.test_GIVEN_motor_is_disconnected_WHEN_get_axis_x_ioc_position_THEN_alarm_is_disconnected`) but out of scope to fix.

**Comment by boeuf-codes** [comment]
Pull requests:
- https://github.com/ISISComputingGroup/EPICS_17T_Birmingham_Magnet/pull/2
- https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/9
- https://github.com/ISISComputingGroup/EPICS-Technix/pull/2
- https://github.com/ISISComputingGroup/EPICS-Aldn1000/pull/5
- https://github.com/ISISComputingGroup/EPICS-CCD100/pull/9
- https://github.com/ISISComputingGroup/EPICS-knrk6/pull/3
- https://github.com/ISISComputingGroup/EPICS-Wbvalve/pull/5
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/558
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/151

**Comment by JackEAllen** [comment]
Changes look good and execute as expected.
