### ISSUE TITLE
IBEX GUI: Display IOC Run Mode in Start Stop IOC's

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#7268]
As a: developer

I believe it might be nice to quickly jump into the start stop IOC menu to see what mode my running IOC is using compared jumping into editing the config and editing the IOC to view this information.

Understanding that this is not something instrument scientists would likely want to see, I envision this information would only be visible on selecting an option which is set to "off" by default.

Create a selection box in the preferences menu, alongside the colour settings/select visible perspectives menus - defaulting to "off" which when selected enables a fourth column in the start/stop IOCs table.

Once enabled, the fourth column should have  have shortened names to describe IOC running mode such as `R/D/<blank>`:
* RECSIM: `R`
* DEVSIM:`D`
* Nothing: `<blank>`

This information can just be displayed in a fourth column of the start stop IOC table:
| IOC | Status | In Config? | Mode | 
| ---- | ------- | ----------- | ------ |
| GALIL_01 | Running | Yes | R |
| AG33220A_01 | Running | No | D |
| ASTRIUM_01 | Running | No |   |
| ECLAB_01 | Stopped | No |   |

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] I can see an abbreviation of the mode an IOC is running in (`R/D/<blank>`), in the start stop IOC table as a fourth column only when the option to do so is enabled from the preferences menu.
- [ ] By default, the option to display the fourth column is set to false.
- [ ] A squish test exists to test this behaviour

### Extra Information
_Why it is needed?_
* To speed up debugging and support process 

_Where required files/links are_
* https://github.com/ISISComputingGroup/ibex_gui/blob/a7f4462bbb654732bd57d916239bc71c6087275d/base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocPanel.java

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_
- [x] **Check Fourth Column Visibility Before Configuring Option in Preferences to View Fourth Column**
    - [x]  Open the start stop IOC's window:  IOC>Start/stop IOCs
    - [x] Check that a fourth column is not visible

- [x] **Check Fourth Column Visibility After Configuring Option in Preferences to View Fourth Column**
    - [x] Navigate to preferences in menu and configure viewing of IOC run mode to display RECSIM and DEVSIM in start/stop IOCs table. 
    - [x] Open the start stop IOC's window:  IOC>Start/stop IOCs
    - [x]  Check that a fourth column is now visible

- [x] **Check that the Mode of a Running IOC is Correctly Displayed if in RECSIM or DEVSIM**
    - [x]  Edit your config to see to include an IOC and change it's mode to RECSIM and select Auto-Start and Auto-Restart: Configuration>Edit Current Configuration...>IOCs>Add IOC>
    - [x] Navigate to preferences in menu and configure viewing of IOC run mode to display RECSIM and DEVSIM in start/stop IOCs table. 
    - [x] Open the start stop IOC's window:  IOC>Start/stop IOCs
    - [x] Check that a fourth column displays either R or D for the running IOC respective of what you selected in your configuration

**Comment by FreddieAkeroyd** [comment]
Instrument scientists often use "manager mode", I would not be surprised if some instruments run in it all the time as that happened in SECI that had a similar feature. So my feeling is the "Mode" column needs to be more hidden than just manager mode, a preference that has to be actively enabled by the user.

**Comment by JackEAllen** [comment]
> Instrument scientists often use "manager mode", I would not be surprised if some instruments run in it all the time as that happened in SECI that had a similar feature. So my feeling is the "Mode" column needs to be more hidden than just manager mode, a preference that has to be actively enabled by the user.

@FreddieAkeroyd  Do you think something like a simple tick box to make the fourth table visible in manager mode only would be a good way to achieve this where the tick box is only visible in manager mode to allow this functionality?

**Comment by Tom-Willemsen** [comment]
I'm not sure tying it to manager mode at all makes sense - how about just an option in the preferences menu, alongside the color settings/select visible perspectives menus - defaulting to off?

Longer term this could also perhaps control whether the recsim/devsim/none selectors show up in the config menus - scientists should rarely if ever want to put their IOCs into sim mode themselves, without at least some input from us. (note: if any ioc is *already* in sim mode then either a warning should be shown in the config menus or the recsim/devsim controls should be shown regardless of the preference).

**Comment by JackEAllen** [comment]
> I'm not sure tying it to manager mode at all makes sense - how about just an option in the preferences menu, alongside the color settings/select visible perspectives menus - defaulting to off?
> 
> Longer term this could also perhaps control whether the recsim/devsim/none selectors show up in the config menus - scientists should rarely if ever want to put their IOCs into sim mode themselves, without at least some input from us. (note: if any ioc is _already_ in sim mode then either a warning should be shown in the config menus or the recsim/devsim controls should be shown regardless of the preference).

This sounds like the best solution as it keeps the setting away from users unless they are certain they want to see this in the start stop ioc table.

**Comment by JackEAllen** [comment]
I will update the issue description to match the newly agreed functionality.
