### ISSUE TITLE
IBEX GUI: Script Generator Icon Does Is not Visible on Left Side Menu Collapse

### ISSUE THREAD

**Issue by JackEAllen** [ISISComputingGroup/IBEX#7270]
## Where?
When collapsing the left side menu, the script generator icon becomes invisible. 

I believe this is due to the size of the icon being too large to scale down correctly on side menu collapse.

Decrease the size of the script generator icon such that it is still visible when the full sized side menu is collapsed.

![image](https://user-images.githubusercontent.com/32413847/182344390-9813b8e8-0bb8-4586-8b1a-6b4cd43c2903.png)

## How?
Found during system testing for release 11.0.0.  

## Reproducible?
Yes

### To Reproduce
- Collapse the left side menu of version 11.0.0 of the GUI

## Acceptance criteria 
- [ ] Script generator icon size has been reduced
- [ ] Icon is visible in left side menu when collapsed
- [ ] Icon is visible in left side menu at full size
- [ ] Squish test to check test this behaviour.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
tada https://github.com/ISISComputingGroup/ibex_gui/pull/1455

**Comment by JackEAllen** [comment]
> tada [ISISComputingGroup/ibex_gui#1455](https://github.com/ISISComputingGroup/ibex_gui/pull/1455)

Bellisimo!

![image](https://user-images.githubusercontent.com/32413847/182363062-6c0cdffb-fcd5-4fb1-8d4d-4ab6881e182e.png)

**Comment by JackEAllen** [comment]
@rerpha  Is it worth adding a squish test? Happy to pass it if not.

**Comment by rerpha** [comment]
> @rerpha Is it worth adding a squish test? Happy to pass it if not.

nah, testing is for losers 

probs not worth doing in all seriousness, I think i'll just add a note to a wiki page saying they have to be 24x24px

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Adding-a-Button-to-the-Perspective-Switcher#adding-a-new-icon

**Comment by JackEAllen** [comment]
> > @rerpha Is it worth adding a squish test? Happy to pass it if not.
> 
> nah, testing is for losers
> 
> probs not worth doing in all seriousness, I think i'll just add a note to a wiki page saying they have to be 24x24px

I guess this makes me a loser 😥

Cool thanks for the changes, will merge in now and close the issue
