### ISSUE TITLE
Instrument Demos for Release 11.0.0

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7273]
As a user of IBEX I would like to be kept abreast of new features of IBEX. Given that we have just done a release (https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_v11.0.0.md) we should demo new features. See https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos.

List of instruments to demo to:

(TBD?)

## Acceptance Criteria
- [ ] Demos are assigned across the group
- [ ] Demos are performed and minuted on the wiki

**Comment by KathrynBaker** [comment]
Given that the deployment is still TBC as to who will need a demo, this will get a lower priority
