### ISSUE TITLE
GUI: review usage of `finalize()`

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7275]
## Where?

As a developer, I would like the GUI to not use deprecated and error-prone java functionality.

As of java 9, the [`finalize` method on `Object` is deprecated](https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#finalize--). Use of finalizers has been heavily discouraged in many sources for a long time, because they are extremely difficult to write and use correctly. For example:
- The official java documentation states the following: 
> The finalization mechanism is inherently problematic. Finalization can lead to performance issues, deadlocks, and hangs. Errors in finalizers can lead to resource leaks; there is no way to cancel finalization if it is no longer necessary; and no ordering is specified among calls to finalize methods of different objects. Furthermore, there are no guarantees regarding the timing of finalization. The finalize method might be called on a finalizable object only after an indefinite delay, if at all.
- _Effective Java_ by J. Bloch has an entire subchapter named "avoid finalizers"
- Various [well-regarded java coding standards](https://wiki.sei.cmu.edu/confluence/display/java/MET12-J.+Do+not+use+finalizers)
- [Our own wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions#dont-mess-with-finalizers)
- Numerous other sources

## How?

We currently have 3 places in the GUI where we are overriding `finalize`. We should review what the finalizer is attempting to do in each case, and remove or replace it with a supported mechanism.

From a cursory examination, it looks like these finalizers can never actually be triggered, because they are trying to remove listeners, but the listener itself looks like it prevents the object from being finalizable (the object is reachable from a GC root *via* the listener). Decide whether this is a problem in each case, and either:
- Remove the finalizer, if it is not required
- Refactor the code so that a finalizer is not required. For example:
  * Adding a `close` method to release resources and calling it in an appropriate place
  * Refactoring so that listeners do not need to be closed - if a listener is only added once as a static variable then it does not need to be closed - it's lifetime is the same as the application lifetime. However adding listeners on each _instantiation_ of a class without ever closing them is a programming error which is likely to cause a memory leak.
  * Replacing listeners with explicit gets of the listened-for value at runtime
- Use a supported mechanism such as `PhantomReference` - but only as a last resort if the refactoring above is not possible - generally we should not be doing anything in IBEX which requires such advanced cleanup mechanisms
  * While `PhantomReference` is supported and *better* than `finalize`, it is still very difficult to use correctly - hence wanting to avoid it if at all possible

## Acceptance criteria 
- [ ] The GUI uses supported functions to perform it's cleanup operations
- [ ] Checkstyle config is updated to include [NoFinalizer](https://checkstyle.sourceforge.io/config_coding.html#NoFinalizer) as an error

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
I have also updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/GUI-Coding-Conventions#dont-mess-with-finalizers with details of alternative approaches to `finalize`

**Comment by ConorMFinn** [comment]
Completed via 
- ISISComputingGroup/ibex_gui#1493
