### ISSUE TITLE
Reflectometry server: don't serve more elements in `LOG` than the declared size of `LOG`

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7276]
## Where?

The reflectometry server has a 10,000 element char waveform in which it stores it's log. But if the server logs more than 10,000 characters, it actually serves more bytes over channel access than it's declared size.

This ~crashes the gateways and~ is generally not valid/expected behaviour for a CA server.

Edit: @FreddieAkeroyd has now [patched](https://github.com/ISISComputingGroup/EPICS-gateway/commit/54f14819f24128d1b4b9fee0f19052cbaa14d99a) the gateway so that it truncates rather than crashes - but I still think we should fix this at the reflectometry server level too.

## How?

The reflectometry server should truncate it's log to 10,000 characters before serving it, or keep only recent log messages such that it's size is less than 10,000 characters.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
I've put this as training as the actual change is probably quite simple - but may benefit from a little input from Thomas/Jack about whether it is better to only serve recent messages, or just truncate the log at 10,000 chars.

**Comment by FreddieAkeroyd** [comment]
Additional information for @NikolaRoev 
* The reflectometry server is https://github.com/ISISComputingGroup/EPICS-refl and uses 
https://pcaspy.readthedocs.io/en/latest/ for serving process variables
* It defines the size of its string to return at https://github.com/ISISComputingGroup/EPICS-refl/blob/1d205f0eb8403cbd8661942ec927e65815fdeb4b/ReflectometryServer/ChannelAccess/pv_manager.py#L160
* However when it needs to return data from https://github.com/ISISComputingGroup/EPICS-refl/blob/1d205f0eb8403cbd8661942ec927e65815fdeb4b/ReflectometryServer/ChannelAccess/reflectometry_driver.py#L118 it just returns `STATUS_MANAGER.error_log` without checking that it fits into the size it declared above.

A truncated version of the error log needs to be returned  if it is too long, but as I expect old messages are at the start of the string truncation should be from the start and not the end of the string. 

Would also be worth checking if anything similar is done for another variable that will also need attention

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/42
