### ISSUE TITLE
GUI: checkstyle

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7282]
As a developer I would like the checkstyle warnings to be slightly lower.

I noticed this while doing another GUI ticket but didn't want to combine the changes in a single PR as that may have been confusing.

https://github.com/ISISComputingGroup/ibex_gui/pull/1459

**Comment by JackEAllen** [comment]
Changes look good so have merged in and happy to mark this one as complete.
