### ISSUE TITLE
Release 11.0.0 does not upgrade config repository version

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7286]
It seems the configuration upgrade step is missing from release 11.0.0, after an install it remains at 10.0.0
  
A 11.0.0. upgrade step was added to `misc/upgrade/master` and this is tagged as the 11.00 release, but teh submodule versions must not have been pushed prior to release build. This upgrade step is a "No Op" so release functionality is not affected, but for consistencey this shoudl be corrected.

## Acceptance criteria

- installing release 11.0.0 upgrades config version
- add a manual system tests step to check config version

## for discussion

Do we adjust git tags so a rebuild of release 11 gives the correct config version?

**Comment by rerpha** [comment]
ah yes, I forgot to add the submodule after making the change to misc/upgrade/master, whoops!

**Comment by rerpha** [comment]
Hannah and I have patched the release on the share and added a step to the manual system tests template as well as adding notes on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release and in dev-changes-memo

**Comment by rerpha** [comment]
I reverted the change on the share as i think it was actually correct - I ran it with `    ("11.0.0", None),` as the last upgrade step and the config_version.txt is correct.
