### ISSUE TITLE
seqPVmacros.h: reduce duplication

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7292]
## Where?

As a developer I would like to reduce duplicated code.

## How?

The header `seqPVmacros.h`, which is used by many SNL state machines, is [currently duplicated in many places throughout the codebase](https://github.com/search?q=org%3AISISComputingGroup+seqpvmacros&type=code). Refactor these to use a header in a common location to reduce duplication (*).

(*) we should only refactor the modules we have written - modules we have got externally might be best left alone to make it easier to merge in future changes from vendor branches

## Acceptance criteria 
- [ ] Duplication reduced

**Comment by NikolaRoev** [comment]
https://github.com/ISISComputingGroup/EPICS-utilities/pull/21
https://github.com/ISISComputingGroup/EPICS-ioc/pull/717
https://github.com/ISISComputingGroup/EPICS-hlx503/pull/8
https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/pull/10
https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/17
https://github.com/ISISComputingGroup/EPICS-transtechnik/pull/2
https://github.com/ISISComputingGroup/EPICS-Jsco4180/pull/14
https://github.com/ISISComputingGroup/EPICS-Keithley_2001/pull/4
