### ISSUE TITLE
Evaluate PI Stage

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7299]
As a scientist on SANS2D I want to use a specific PI stage

## Acceptance Criteria
- [ ] Check that the manuals (ask Kathryn for the links) match with the existing PI drivers

## Notes
- There is a standard command set which may match what we already have

**Comment by KathrynBaker** [comment]
Controller in question is https://www.physikinstrumente.store/uk/c-867.1u/, this uses the PI General command set which is also in use in MotorApp according to https://github.com/ISISComputingGroup/EPICS-motor/tree/master/motorApp/PIGCS2Src

I've added the User Manual for the c-867.1u into our manuals and the command set looks similar enough to ones that we already so configuration should be all that this takes to get it working, and similarly the commands inside the c code look to match. I have informed the scientist that asked me about this in the first place that this is the case. (Direct emails)

**Comment by FreddieAkeroyd** [comment]
This does indeed look to be GCS v2 from the manual, so should be supported and hopefully work easily. Would be worth a test if the device is around.

**Comment by KathrynBaker** [comment]
If we want to test it, that would be a second ticket, as the acceptance criteria is just to decide whether or not the manuals look like it will be OK
