### ISSUE TITLE
Beckhoff: remove motor record autosaving on comms error at ioc startup 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7319]
As a developer I would like to not restore the default motor settings if a beckhoff cannot be reached during ioc startup. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Autosave is prevented from rolling back to the default motor values (ie DESC being set to MTRXXXX (Beckhoff) ) when a beckhoff cannot be reached on startup. 
## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
One consideration I've thought of is that soft limits will need to be preserved somehow, so we may need to autosave those still. I am against tying in Beckhoff "soft limits" into the motor record and would still like a layer of abstraction that stops a user from even sending a move to a beckhoff if over the soft limits. If we did tie the Beckhoff ones in we would get errors (requiring resets) in order to move again.

**Comment by rerpha** [comment]
right, instead of removing autosave, we probably just need to make sure we dont autosave any values when a beckhoff cannot be reached on startup. The main issue is that if this happens the motor record defaults get reverted and these are then saved, potentially losing settings.

**Comment by FreddieAkeroyd** [comment]
This is the default motor record autosave as opposed to reflectometry server autosave? A longer term change may be to move from auto to manual save - we then don't periodically save, but just when a "save settings" button/command is actioned. This is very easy to change in our current setup from a technical viewpoint, it is more the change in workflow of remembering to manually "save" that may cause issues

**Comment by rerpha** [comment]
yes - this is if TC starts up but cant talk to beckhoff, seems to reset back to basic_asyn_motor vals

**Comment by rerpha** [comment]
A save settings button would probably work as the only things that need to be autosaved for beckhoffs are very rarely touched - desc (sometimes, though this can be brought in from controller) EGU, offsets and soft limits

**Comment by FreddieAkeroyd** [comment]
we may be able to make autosave conditional on motor startup success #8417 though i'm not totally sure why a bad startup leads to values getting set to defaults

**Comment by rerpha** [comment]
will try https://github.com/ISISComputingGroup/EPICS-ioc/pull/869 on SURF. I need to make sure to get rid of any NUM_AXES definitions in globals.txt or base components before merging this ticket as it used to be required to specify num of axes until i automated it by polling the controller at startup so that might unintentionally prevent the exit

**Comment by rerpha** [comment]
this isn't really an easy one test as it requires a simulated beckhoff, but you could check the TC_01 logs for SURF and see that their autosave values shouldn't have changed (or at least gone back to 0 for OFF etc.) after deploying this change
