### ISSUE TITLE
TC/Beckhoff: Motionsetpoints missing 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7324]
The Motionsetpoints module is currently not loaded by TC correctly as it's not in the CONFIGURE/RELEASE file, despite the st-common.cmd attempting to load motion setpoints .cmd files. This hasn't been spotted before as the only application so far using motion setpoints is SANS2D, in which the Galil IOC loads the motion setpoints file instead.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/721
https://github.com/ISISComputingGroup/IBEX/pull/7325

I will likely need to patch this over to SANDALS to test the sample changer. 

To test this, spin up a simulated beckhoff with https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff-testing with a motionsetpoints.cmd file in your PLC_solution dir (see tcioc_motion.py for where this is) or alternatively wait and see this on SANDALS in the next few days.

**Comment by FreddieAkeroyd** [comment]
Don't you need to add `motionSetPoints.dbd` to the DBD list too? Or is it indirectly included elsewhere?

**Comment by rerpha** [comment]
> Don't you need to add `motionSetPoints.dbd` to the DBD list too? Or is it indirectly included elsewhere?

yes i do , have just added

**Comment by rerpha** [comment]
now patched on sandals, so can review on there, will be much easier than setting it up manually
