### ISSUE TITLE
Instron MiniTower - run test with scientists [Timebox: 2.5 days]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7327]
## Where?

As an instrument scientist I want to have confidence that the new control of the stress rig via `Arby.dll` has equivalent functionality compared to the old interface.

To achieve this, I would like to run a representative stress rig script to prove that the new control is working properly.

Script should include:
- Control in each of the 3 modes (position, stress, strain)
- Waveforms
- Changing step times
- Any 'weird' items (e.g. scripts which send arbitrary commands?)

Also test:
- Stop
- Panic stop
- Any other writable parameters not tested by script above

## How?

This issue was spawned by investigations in https://github.com/ISISComputingGroup/IBEX/issues/7296. Further detail is on that ticket and in the Instron manuals area on the usual share.

## Acceptance criteria 
- [x] Test has been run with input from scientists

Either:
- [ ] The test ran successfully
or:
- [x] Issues were identified during testing, and have been either fixed (if quick) or tickets created for the fixes (if complicated)

Note: If this ticket is done before the actions from https://github.com/ISISComputingGroup/IBEX/issues/7326, then logging/file generation using ARACCESS should be considered **out of scope** for this ticket. Issue 7326 will define which approach we need to use for logging/file generation.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by KathrynBaker** [comment]
2.5 days for the testing, .5 for extra issue writing and review

**Comment by Tom-Willemsen** [comment]
Instron console application installed on new PC along with relevant IBEX components. Next step is to take it down to ENGIN-X and plug it into the stress rig to see if it works. Have emailed scientists asking for a convenient time when we can do this.

**Comment by FreddieAkeroyd** [comment]
It should now be possible to install a 32bit build via the deployment script

**Comment by Tom-Willemsen** [comment]
Initial testing:
- Installed "console" on instron PC
- Needed to put the rig ID (written on sticker on rig) into instron configuration tool
- Needed to upload the calibration files (stored in `\\isis\shares\ISIS_Experiment_Controls\Manuals\Instron_Stress_Rig\MiniTower (Ethernet - Arby)\ENGIN-X 100kN rig calibration files 2022-09-01\Instron Cal Files`) to the new console install
- Set up ethernet adapter with `10.0.0.1` private address on a `255.0.0.0` subnet
- Plugged in MMI (via USB) and rig controller (via ethernet) to the new PC.
- Both "console" and IBEX happy reading from rig
- Some trouble writing:
  * Random hydraulic trips?
  * Sometimes moving in wrong direction - wrong PIDs?
  * Sometimes just randomly fails to write anything and needs various items power-cycled (?)

**Comment by Tom-Willemsen** [comment]
> Sometimes moving in wrong direction - wrong PIDs?

Narrowed this down to the rig doing relative moves instead of absolute moves now with `C1,1` - but only if the instron console application hasn't done a move itself yet. Using arby spy we figured out that "console" doesn't use `C1,1` and instead uses:

```
C500,1;C38,1
C916,0
C914,4
C916,2
C372
```

to start a ramp. Porting this approach into the IBEX protocol seems to have fixed the absolute/relative move issues. Arby does complain that the `C38,1` above is invalid, but it also doesn't start a move without it... 😕 - I've told the scientist they may just have to live with the occasional "invalid command" messages that pop up in testlog as this doesn't make much sense to me and I'm not sure it's valuable to spend much time fixing this.

Now tested & working ok:
- General reading (all parameters)
- Setting parameters on all channels (pos/stress/strain) and setting off moves
- Stopping rig, setting cross sectional area, etc

Still to test:
- Waveform generator
- Arbitrary commands
- Representative test script

**Comment by Tom-Willemsen** [comment]
Scientists are now happy that the stress rig is working adequately for cycle - ramps, waveforms and a representative test script have been run successfully.

PRs for changes made during testing:
- https://github.com/ISISComputingGroup/IBEX/pull/7512
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/753
- https://github.com/ISISComputingGroup/EPICS-InstronArby/pull/3
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/577
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/158
