### ISSUE TITLE
Motionsetpoints: OFFSET:SP missing units

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7332]
OFFSET gets .EGU set by the substitution files, but OFFSET:SP does not:

![Screenshot 2022-09-06 153148](https://user-images.githubusercontent.com/14823767/188662278-0f3ce958-f67f-4348-96aa-0991484248ea.png)

In this example the SP should have "deg" as that is the underlying .EGU of the motor record. This is because it's missing from the unit setter substitution which means it defaults to "mm" as this is is the default VAL field in the single axis template. 

### Acceptance criteria
- [ ] OFFSET:SP has the same units as the motor record it will be acting on

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/29
https://github.com/ISISComputingGroup/IBEX/pull/7333

**Comment by Tom-Willemsen** [comment]
Reviewer: please double check this doesn't cause a regression of https://github.com/ISISComputingGroup/IBEX/issues/6423 because of https://github.com/ISISComputingGroup/IBEX/issues/6433

**Comment by FreddieAkeroyd** [comment]
I've proposed we do #6433 next sprint

**Comment by JackEAllen** [comment]
> Reviewer: please double check this doesn't cause a regression of #6423 because of #6433

I believe this does not cause a regression of #6423 as we are using NPP as default.
