### ISSUE TITLE
Build servers: update [Timebox: 1 day]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7335]
## Where?

As a developer I would like our build servers to use supported configurations.

As of latest dependency updates, IBEX no longer supports W7. We should remove/reimage/reconfigure build servers which use W7.

See https://epics-jenkins.isis.rl.ac.uk/computer/ for details of current build server OSes.

- VEGAS seems to be extremely slow, it only runs `build_area_maintenance` and last time it ran successfully it took 4 days to run...
- RENO used to run system_tests_iocs, but these now run elsewhere, and I can't see that RENO is actually needed for anything.
- SQUISH 

## Acceptance criteria 
- [x] All build servers are on an OS that IBEX supports
- [x] Turn off VEGAS and RENO
- [x] In-place upgrade for SQUISH

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
Have added squish server to the list, i think it was down when you originally checked, but it is a W7 virtual machine

**Comment by KathrynBaker** [comment]
Discussion in the planning meeting was that RENO and VEGAS can probably just be turned off, SQUISH needs a little more thought

**Comment by Tom-Willemsen** [comment]
To review:
- Check https://epics-jenkins.isis.rl.ac.uk/computer/, all build nodes are on a supported OS
- Squish tests are *running* (note: not currently passing, but the tests are being run correctly)
- RENO and VEGAS are no more
- `build_area_maintenance` is still running, on a different & supported node

**Comment by KathrynBaker** [comment]
All looks appropriate and as expected. Things which should be running are, and all OSs as expected.
