### ISSUE TITLE
ibex gui linux jenkins: build master instead of separate branch

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7337]
The `ibex_gui_linux_pipeline` jenkins build is currently building a `linux_rpm` branch which can become out of step with master. There are a small number of changes there related to avoiding unnecessary information sharing on the IDAaaS system.

## Acceptance criteria

* The changes made on `linux_rpm` branch are added to master in a way that they only apply on linux

**Comment by KathrynBaker** [comment]
Need to protect the changes with an if linux check
