### ISSUE TITLE
Create IBEX 11.1 (11 plus the plotting changes)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7340]
As someone deploying IBEX V11 I need a version of IBEX 11 which has the plotting changes in it

## Acceptance Criteria
- [x] IBEX V11.1 is created
- [x] V11.1 is deployed to MUSR
- [x] V11.1 is deployed to POLREF
- [ ] V11.1 is deployed to INTER
- [x] V11.1 is deployed to EMU

**Comment by Tom-Willemsen** [comment]
Should also contain changes to CSS rules engine which solve memory issues for users of REFL opi.

**Comment by Tom-Willemsen** [comment]
Discussion in office was to use `master` from just before dependency updates were merged to create v11.1, as this should have all of the relevant changes.

Potentially use the actual builds already done on Jenkins, as the old branches *may* no longer work with the newly-updated dependencies on the shares.

**Comment by Tom-Willemsen** [comment]
- POLREF
  * [x] Email sent asking scientists about deployment
  * [x] Deployed
- INTER
  * [x] Email sent asking scientists about deployment
  * [ ] Deployed
- MuSR
  * [x] Email sent asking scientists about deployment
  * [ ] Deployed

**Comment by Tom-Willemsen** [comment]
Just waiting for INTER to confirm when they want this deployed. Putting this in impeded in the meantime.

**Comment by KathrynBaker** [comment]
- EMU
  - [ ] Email sent asking scientists about deployment
  - [ ] Deployed

**Comment by Tom-Willemsen** [comment]
I have not had replies from INTER. I'll spin that out into a task so that this ticket can go through.

**Comment by KathrynBaker** [comment]
I'm aware that these have gone out, and with the recent changes the memory issues on POLREF are less
