### ISSUE TITLE
LKSH336: use `getAOUT` to read channels 3&4 in place of `getHTR`

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7343]
On testing with cryogenics and scientists, the functionality added to read channels 3 & 4 on a lakeshore works except that the readback comes back as 0. On further investigation a slightly different command is needed to read channels 3&4. the command is already present in protocol file as `getAOUT`, just need to call it instead of `getHTR`.

Note: this is already patched on LARMOR and ZOOM

Needed for running 3D magnet

**Comment by boeuf-codes** [comment]
Pull requests:
 - https://github.com/ISISComputingGroup/EPICS-ioc/pull/727
 - https://github.com/ISISComputingGroup/EPICS-lakeshore/pull/6
