### ISSUE TITLE
Muon "RF": Refinement of requirements for components and saving and storing device settings

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7369]
As someone supporting the use of the "RF" equipment on IBEX I want to understand the Instrument scientists need/want when it comes to sharing components and saving and restoring device settings

## Acceptance Criteria
- [ ] Appropriate meetings and discussions are held
   - [ ] With the scientists - scheduled for 27/9/22
   - [ ] Within the IBEX team - if required
- [ ] Requirements are written up and agreed
- [ ] Tickets are created to refine the design (these tickets to include the creation of the tickets for the implementation) and the umbrella ticket (#7370) is updated with those ticket numbers

## Notes
- This is a continuation of #7298 
- The aim of that ticket was for a system of RF equipment, which is not what the scientists want any more, and so the individual interactions can be considered more specifically

**Comment by KathrynBaker** [comment]
Marked as impeded as I'm waiting for the meeting with the scientists

**Comment by KathrynBaker** [comment]
Pointed at 3 - a little over half a day for the various meetings at most (allowing for 2 or 3 IBEX team members if that follow up meeting is required), an hour or so for writing up, and some time for a review.

**Comment by KathrynBaker** [comment]
Bear this in mind https://github.com/ISISComputingGroup/IBEX/issues/7298#issuecomment-1247748603 when thinking about the next stages, and refer to it again if appropriate in the tickets created here.

**Comment by KathrynBaker** [comment]
Notes post the meeting:
Ended up including the discussion for #7367 for this, comments added to that ticket.
Priorities were highlighted and reordered in #7370.

For the components aspect:
- The concept of "blocks only" components is acceptable for the use of the same devices in different experiments
- The ability to just "copy component from another instrument" via the GUI is the feature to aim for
- There is a potential workaround and long winded way of doing it at the moment (copy the file in the background, restart the blockserver) but that will likely require effort from the experiment controls group so would be unsustainable
- Ticket #7389 created to undertake the next iteration of design and considerations for this from a technical point of view

Saving and Storing Device Settings aspect:
- This has been asked for in the past (e.g. #1449)
- There are potential workarounds via scripting, but lists of PVs to save, and their associated values, are not ideal for ensuring correctness once you get beyond a small number, it is too easy to make mistakes in the script that are valid but hidden (e.g. saving the same PV twice because the single character difference between _01 and _02 isn't corrected)
- Ticket #7393 created to undertake the next iteration of design and considerations for this from a user and technical point of view

The two areas for discussion in the team have been added as additional tickets, so no further discussion is anticipated. Returning this ticket to impeded as I await confirmation that the requirements are acceptable to the scientists.

**Comment by KathrynBaker** [comment]
No response from the scientists at this time, so we should deal with anything as and when it gets communicated to us

**Comment by Tom-Willemsen** [comment]
Design tickets seem reasonable to me.
