### ISSUE TITLE
IBEX client: improve detecting of multiple clients

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7381]
The current mechanism for detecting an attempt to start a second client and prompting/warning the user seems unreliable. I believe it uses a temporary file that may not get cleaned up sometimes? An alternative should be used that avoid needing to be explicitly cleaned up e.g. 
- named mutex (these are system wide on windows, so can only be created once and all processes interacvt with the same instance, but may need jni calls)
- FileLock - Java has this class, try to exclusively lock a file, warn is can't, hopefully this is implemented via an operating system lock that gets cleaned up automatically at process termination

## Acceptance criteria

multiple client detection is more reliable

**Comment by Tom-Willemsen** [comment]
Investigate using https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileLock.html / https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileChannel.html
