### ISSUE TITLE
ENGIN-X INSTRON: test 32 bit builds

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7385]
## Where?

As a developer deploying 32-bit builds I want to be sure that needed functionality works.

Note: https://github.com/ISISComputingGroup/IBEX/issues/7384 should be done first

We should run some tests against 32-bit builds:

## Acceptance criteria 
- [ ] Run IOC tests against a 32-bit EPICS
  * If many tests fail, we can fall back to only running the `INSTRONA` tests, but it would be better to run all IOC tests so create a ticket to get them working in the future
- [ ] Write a new test which checks that a 64-bit client (e.g. `caget`) can read from a 32-bit IOC via a 32-bit gateway

## How to Test 
Order in which to test:
 - check out IOC test framework changes and check:
   - changes work fine 
   - tests which are _consistently_ failing on Jenkins [`System_Tests_win32`](https://epics-jenkins.isis.rl.ac.uk/job/System_Tests_win32/) are handled in these changes
   - then merge if you're happy
- check out Jenkinsfile changes 
   - check these look fine
- have a look at the Jenkins system tests jobs (as `System_Tests_win32` is checked out onto my branch for `\system_tests`)
  - check `System_Tests_win32` is running IOC tests and only the `test_x86_build` suite on system tests
  - if it is, then merge these changes and revert 'branches to build' back to '`*/master`'
- have another look at the Jenkins system tests jobs
  - check all other versions of x64 `System_Tests` jobs are running all tests still
  - check the consistently failing tests from earlier are now being skipped 

Seperately:
 - verify samplechanger fix works
 - verify new system test `text_x86_build` works as specified 
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
@boeuf-codes The associated 32bit build ticket 7384 has now been merged

**Comment by FreddieAkeroyd** [comment]
just waiting for jenkins job to run again

**Comment by LilithCole** [comment]
with this tests now fail to run unless you're starting them at a similar depth to support\IocTestFramework\master due to the filepath of ../../../epics_host_arch.txt

**Comment by FreddieAkeroyd** [comment]
if you have run config_env then that is always fine, otherwise it assumes `instrument\apps\epics` that may not be correct? I winder if it is better to look at `EPICS_HOST_ARCH`  environment variable, that will give the same result on a config_env, if that is not defined then we assume 64bit arch

**Comment by FreddieAkeroyd** [comment]
@LilithCole have done both ways - does above PR work for you?
