### ISSUE TITLE
DAE Spectra view: pink border around spectra

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7386]
As a scientist I would like my spectra plots not to have a pink border. Some of the plots on polref have this as shown. It would appear to be caused by a null value in one of the spectrum/period/mode local variables e.g. if you hover over the pink item above the graph then you get:
* For spectrum   `loc://_LOCAL:SPEC:SPECTRA1 has null value.`
* For period number `loc://_LOCAL:SPEC:PERIOD3 has null value.`

Reloading the OPI did not appear to clear it, but reset layout did

Also seen on WISH where mode dropdown was completely blank
 
## Acceptance criteria

* Issue with null value of local OPI variables identified and fixed so plots no longer have pink border

![polref_spectra](https://user-images.githubusercontent.com/1132753/192390813-28be370f-cf82-4fdf-b0c5-dd9c09494e13.PNG)

**Comment by FreddieAkeroyd** [comment]
Some information from @Tom-Willemsen

I'm pretty sure this is a race condition between the CSS thread which manages local PVs (which is lazily spawned when an OPI first needs it), and our thread that writes to those PVs. If any other OPI is opened first I think this wouldn't occur, and can be tricky to reproduce on a dev machine as they're often faster than instruments and CSS may create the thread "just in time" for our code as the OPI is opening.
 
If the write fails we could spawn a background thread that tries the write again once a second if value is unavailable or null until it succeeds? It should eventually succeed once css spawns the relevant thread, and this would be relatively easy to implement...

**Comment by boeuf-codes** [comment]
PRs:
 - https://github.com/ISISComputingGroup/ibex_gui/pull/1485
 - https://github.com/ISISComputingGroup/IBEX/pull/7404
