### ISSUE TITLE
Deployment: deploy ibex 11.1 to TS1 instruments for next cycle

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7388]
Deploy ibex to the following instruments. TS1 are also undergoing a W10 upgrade, the deployment can be done before or after an upgrade as files are just copied across to the new VM image.

## TS1 Instruments already running W10 (can do now)

INES
- [x] In progress
- [x] Done

SANDALS
- [x] Done

MUSR
- [x] Done

EMU
- [x] Done

RIKENFE
- [x] Done

IRIS
- [x] In progress
- [x] Done

ARGUS and CHRONUS are on W10 but running SECI, so will not deploy
HIFI runs mini inst only, so not deploying

## TS1 Instruments running W7 and awaiting upgrade to W10 (can do now)

LOQ - blocks
- [x] In progress
- [x] Done

CRISP
- [x] In progress
- [x] Done

ENGINX
- [x] In progress
- [x] Done

ENGINX_SETUP
- [x] In progress
- [x] Done

GEM
- [x] In progress
- [x] Done

HRPD
- [x] In progress
- [x] Done

MAPS
- [x] In progress
- [x] Done

MARI
- [x] In progress
- [x] Done

MERLIN - blocks
- [x] In progress
- [x] Done

POLARIS
- [x] In progress
- [x] Done

SURF
- [x] In progress
- [x] Done

TOSCA
- [x] In progress
- [x] Done

VESUVIO
- [x] In progress
- [x] Done

MUONFE
- [x] In progress
- [x] Done

Others

SELAB
-   [x] In progress
-   [x] Done

EMMA
- [x] In progress
- [x] Done

SOFTMAT
- [x] In progress
- [x] Done

SXD and PEARL are running SECI and do not need ibex.
CRYOLAB_R80n needs renaming to CRYOLAB_R80 first
 
## TS1 Instruments in process of being upgraded to W10, **do not** do an ibex upgrade at this point

IRIS_SETUP
- [x] Ready
- [x] In progress
- [x] Done

OSIRIS
- [x] Ready
- [x] In progress
- [x] Done

ALF
- [x] Ready
- [x] In progress
- [x] Done

**Comment by davidkeymer** [comment]
SANDALS would be good to get done early so that commissioning of Beckhoff-controlled jaws and sample-changer can continue, as well as newly-installed SKF G5 chopper controllers.

**Comment by JackEAllen** [comment]
LOQ ideally needs upgrading to W10 and IBEXV11.1 by early October to move #7182 out of impeded to test before instrument is required by IS mid-October provided TS1 deadlines don't slip further

**Comment by Tom-Willemsen** [comment]
Decide whether we want to deploy 11.1 or 11.0 to instruments that haven't explicitly asked for the plotting changes; v11.0 is the version we system tested.

**Comment by rerpha** [comment]
> SANDALS would be good to get done early so that commissioning of Beckhoff-controlled jaws and sample-changer can continue, as well as newly-installed SKF G5 chopper controllers.

sandals already on 11.0.0 with some patches that may not be in v11.1.0(?) - perhaps worth skipping if the SKF changes are in 11.0.0?

**Comment by FreddieAkeroyd** [comment]
decided at standup meeting to deploy 11.1 everywhere

**Comment by rerpha** [comment]
osiris deployed to but having issues with motionsetpoints - spun out into task
not sure on status of cryolab machine, also spun out into task

**Comment by FreddieAkeroyd** [comment]
@rerpha OSIRIS issue may be due to 
``` 
sevr=minor motionSetPoints: Lookup file C:/Instrument/Settings/config/NDXOSIRIS/configurations/motionSetPoints/BeFilter.txt contains no rows
```
This is not a new error (i see it in pre-upgrade log files), but the previous motionSetpoint code must have behaved better. Looking at the git log it seems the file may always have been like this, which seems strange...
