### ISSUE TITLE
Friday - organise

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7392]
As a developer I would like to have "Friday" quality development time which fundamentally benefits users and developers in the long term.

## Acceptance Criteria
- [x] Pick a date
- [x] We spend the a day on Friday tasks/tickets
- [x] There is a zoom meeting open all day (so that the office can be connected with any remote people, and they can connect with each other - cameras can be off, mics can be silenced, but it can provide a 'room' that we can interact in)
- [x] As many as are comfortable/available should be in the office

### Extra Information
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Friday-Quality-Time

**Comment by ThomasLohnert** [comment]
Proposing as this we have not had a friday in a few months.

**Comment by KathrynBaker** [comment]
Whilst we haven't had a Friday, this sprint is a short one, and might not be a good opportunity for a Friday, as we should probably have the discussion post the conferences first.

**Comment by rerpha** [comment]
Friday has now happened
