### ISSUE TITLE
Muon "RF": Save and Restore Device Settings - Design

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7393]
As someone using a device within a configuration for multiple experiments I want to be able to easily save and restore settings so that I don't have to enter them manually and risk mistakes.

## Acceptance Criteria
- [ ] There are tickets to ensure that the workflow(s) listed below can be achieved in a sensible manner by appropriate levels of developers, with consideration that this is a basic workflow only
- [ ] Ticket https://github.com/ISISComputingGroup/IBEX/issues/7370 is updated as appropriate

### Save
- Select Save Settings - A dialog is displayed with the PV selector set up
- Select PVs to save, confirm save - a dialog is displayed allowing the file to be named arbitrarily

### Load
- Select Load Settings - A dialog/list of named saved files is displayed
- Select a file, confirm apply settings - The PVs in the file are set to the values in the file

### Copy Settings from another instrument
- Select Copy Settings from another instrument - the instrument list is displayed
- Select an instrument and confirm - A list of settings files on the that instrument is displayed
- Select a file to be copied locally, select copy - the file is copied locally, and is available when looking at the list to load

## Design decisions still required to be made
- Does this need a configurations/saved sets of PVs option?
- Can these files be saved anywhere, or are they a new folder in Instrument\Settings?
- Should you be able to load/copy multiple settings files?
- Do they need to be stored in version control?

## Notes
- This is a ticket to design and make sure we have all the areas covered, however, if in discussion of this ticket it is realised that this is straightforward then the acceptance criteria can be altered to enacting the workflows
- It is envisaged that whilst this may be a recurring task, it does not need scripting
- This is likely to need a new menu in the GUI

**Comment by FreddieAkeroyd** [comment]
Fo info, caenv895 currently uses epics configMenu - PVs for saving are indicated by `info(vmeconfig, "VAL")` in https://github.com/ISISComputingGroup/EPICS-CAENVME/blob/master/CAENVMEApp/Db/v895CardHeader.template
 and then optionally mand availabe to load via setup in https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd

**Comment by pheest** [comment]
[Review of EPICS save.docx](https://github.com/ISISComputingGroup/IBEX/files/10852345/Review.of.EPICS.save.docx)

**Comment by pheest** [comment]
Muon "RF": Save and Restore Device Settings – Design Thoughts
High-level
The PVs to be saved or loaded should almost certainly be an attribute of the IOC.
It doesn't make sense to allow PVs to be copied from/to unrelated IOCs, so the user interface should prevent this.
Values can be loaded from the same IOC type stored present on either the local, or a remote, instrument.
GUI
The 'Edit IOC' panel (EditPanel.java), with 'PV Sets' tab seems to be place this should go.
The tab currently seems to serve no or little purpose - see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Sets. It is therefore available for use to load and save sets of PV values.
The 'PV Values' tab currently allows only manual entry of PV names and values. The tab could instead allow the user to select PVs from the currently edited IOC and input the value.
It is not clear whether these panel tabs should (or do) set the IOC start-up value of a PV, or the current value. The current value would of course normally be set through the device screen. If the values in the panel tab can update the IOC at any time, would user updates in the device screen need to update the values in the panel tab also?
Is it the intent of the ticket that PV value sets could be applied at any time?
Saving
Selected PV sets should probably be saved to a subdirectory of Settings\Config\<inst name>\configurations.
A fixed location for the file(s) is essential if IBEX is to locate it and publish the content.
There could possibly be a sub-folder for each IOC name type (e.g. DFKPS for Danfysik power supply), allowing then one or more sets of PV values to be stored in named file(s).
An alternate approach could save PV set files to a Windows server, accessible by other instruments?
Transport
Stored file selection, PV names/value sets could be transmitted between instruments using the blockserver. 
This usage would be similar to copying components between instruments as implemented under ticket https://github.com/ISISComputingGroup/IBEX/issues/7515 .
As noted above, the use of PV sets is a concept that is already – at least partially – implemented in the block server.
Loading
The user would need to select an instrument to copy from, leading to a selection of PV sets applicable to the locally-selected IOC that have been saved.
It would be valid to copy from e.g., DFKPS_01 to DFKPS_03. In other words, _<nn> needs to be discarded from the IOC name, before allowing selection.
The local name prefix would need to be prepended to the PV name(s) before applying the values.
The IOC suffix (e.g., _01) would also need to be appended from the local IOC name.

**Comment by FreddieAkeroyd** [comment]
Which of the current tools best fulfils our criteria? The original PVsets was going to be based on autosave, sets of interest could be specified either via req files or in the db as info records. I am not sure if a user will want to choose arbitrary sets of pvs themselves, more they will want to save based on some template created probably by us. These sets of pvs may have a lifetime, so we will need to be careful about future changes to pv names and logic in case they invalidate already created saved PVs.

**Comment by pheest** [comment]
I am minded to recommend the m-epics-saverestore tool from ESS.
In that it seems to do what is requested, in a fairly simple way.

**Comment by FreddieAkeroyd** [comment]
I don't like the way it spawns python from an asub though, i would prefer integrating it into something like pcaspy. It is mainly using autosave from pyepics, i'm not sure if we do or do not need the ess additions. Given we are looking at phoebus, i'd be interested to see a bit more of the PVtable approach too.

**Comment by Tom-Willemsen** [comment]
@pheest @FreddieAkeroyd and I just had a discussion about this in the office - we decided we'll create mockups for two approaches - saving PVs 'directly' and saving blocks - then once we have the mockups it's much easier to decide which we prefer (and to ask for feedback from interested scientists)

**Comment by pheest** [comment]
<img width="2661" alt="Save Collection" src="https://user-images.githubusercontent.com/16592055/226593667-b3d0120e-f17b-432c-aa90-8b37d6218da8.png">
<img width="2867" alt="Import Collection" src="https://user-images.githubusercontent.com/16592055/226593675-723b2fc9-311f-4f93-8dcf-f57e9e1c4da9.png">
Attached GUI mock-ups showing how this might work.

**Comment by FreddieAkeroyd** [comment]
The two possible approaches are to select/save PV or select/save block. I am not sure i can tell this from the mock-ups, the first has a PV selector which looks to be the PV approach, but then a table appears that looks like it has a block name in it? 

In the block approach what happens if you right click on an item in an OPI that isn't a block - does it prompt you to/automatically create a block? Also how are the items indexed when saved - by block name or by underlying PV name?  If block name it may allow them to be applied to different configurations if appropriate block names are shared, but it may make it harder to apply across different instruments where the same IOC name is used but blocks may be named differently.

**Comment by KathrynBaker** [comment]
We have made a decision to use PVs at least initially (post standup on the 22nd of June 2023, whole team at that time present bar LC), I will create the tickets related and close this ticket ASAP.

**Comment by KathrynBaker** [comment]
New tickets created which break the requirements down more (#7854, #7855, #7856)
