### ISSUE TITLE
POLREF: HTS magnet niggles

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7397]
## Where?

As a scientist on POLREF I would like the following changes to the HTS magnet system:
- [x] Make maget status work (currently seems to be getting back time instead of status ?!)
  * See also https://github.com/ISISComputingGroup/IBEX/issues/7391
- [x] Voltage scale should be +/- 2V on OPI
- [x] Current scale should be +/- 217A on OPI
- [x] Remove "Operating mode" control from OPI
- [x] Write a basic linear calibration assuming 0T = 0A and 3T = 217A
  * Scientists may provide a better calibration at some point, when they put hall probe in magnet
- [x] Ramp rate should have a minimum of 5A/min (as 0 implicitly means "as fast as possible") and a maximum of 30A/min
- [x] Move "Ramp status" control to advanced screen and/or put under manager mode and/or just remove from OPI
  * POLREF scientists went back on this as it caused issues, have put it back. Instead they've asked for the IOC to automatically set the ramp status to ON at ioc start, which I've done via PV sets on POLREF.
  * Ideally ramp would be turned on as field/curr is set - have spun this out as https://github.com/ISISComputingGroup/IBEX/issues/7400
- [x] Remove T5 & T6 from graphs as these permanently read 999K and don't correspond to anything physically
- [x] Can we put limits on Kepco voltage SP to +/- 1.5V (maybe use PV sets in config)

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-SMRTMON/pull/6
  * Have verified that this is appropriate against hardware as best I can; looks reasonable and `extrainput = ignore` is not needed.
- https://github.com/ISISComputingGroup/ibex_gui/pull/1484
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/155
- https://github.com/ISISComputingGroup/IBEX/pull/7398
- Added `hts_calib.dat` to common calibs directory in git and on POLREF
- POLREFs configs now use PV sets to set the limits described in ticket
- Changed units from G to T as this is what POLREF scientists think in, also set PREC to 4 for field readbacks

**Comment by rerpha** [comment]
have added a line to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Kepco#hts-smart-monitor to mention this ticket.

**Comment by rerpha** [comment]
did anyone get a pic of how the smart monitor was wired up to the kepcos, kepcos to moxa? if so we should add that to the wiki as well

**Comment by Tom-Willemsen** [comment]
I didn't get a picture, but the kepcos sit in a half-height 19-inch rack labelled "HTS magnet", along with the smart monitor. I didn't notice whether there was a moxa in the rack (c.f. 3D magnet) or whether they wire these devices into their normal beamline moxas.

**Comment by rerpha** [comment]
> I didn't get a picture, but the kepcos sit in a half-height 19-inch rack labelled "HTS magnet", along with the smart monitor. I didn't notice whether there was a moxa in the rack (c.f. 3D magnet) or whether they wire these devices into their normal beamline moxas.

ok, i may wander down at some point and get a pic of the setup unless @davidkeymer managed to snap one
