### ISSUE TITLE
GUI: "Landing" View

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7403]
As a user, I would benefit from an IBEX landing page displaying some useful information/guidance. At the moment we default to the Alarms view for no particular reason I am aware of (other than it comes first alphabetically). 

### Acceptance Criteria
I propose adding a landing perspective (opened by default on GUI startup) that contains:
- a blurb for each (visible) perspective, explaining its purpose
- Web Links OPI moved here from Web Links perspective
- Perhaps a space that displays a webpage or similar we can use for communicating information to all users of IBEX, e.g. for announcements like telling scientists preparing for the switch to Python3 in the past, or for addressing temporary support issues (e.g. "There was a network outage last night which affected xyz, we are looking into it please stop calling")

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
point 3 could be tacked onto JSON_Bourne, I think a REST interface would be enough to edit the currently displayed message

**Comment by rerpha** [comment]
could rename web links opi to "Home", make it default rather than alarm view, and add blurbs + web view for point 3 on it

**Comment by rerpha** [comment]
feel free to take off label if you disagree - thought this might be a good training (but not first issue) ticket
