### ISSUE TITLE
T-Jump: Test in Soft Matter Lab (30th Jan 2023)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7405]
As someone getting the T-Jump up and running I'd like to test that the system works with IBEX

## Acceptance Criteria
- [x] An up to date version of IBEX/the T-Jump IOC is available on SOFTMAT
- [x] The system is tested with the team in the soft matter lab

## Notes
- This is planned for Mid October, but is waiting on the availability of the hardware (still being worked on) and it being put in the soft matter lab
- It was implied that we could not test at this time, and so there is a reputational advantage in actually testing this, as we are in a state to do so, and if there are any errors there will be a chance to fix them before the system is in place on a beamline
- The system will be tested/used on LOQ during cycle 2022/04 (November - December 2022)
- At least the T-JUMP IOC is needed, the system level would also be useful, an up to date IBEX might not be a bad idea

**Comment by KathrynBaker** [comment]
I now have some dates for this, so shall pull it onto the tasks board.

**Comment by rerpha** [comment]
has this been patched onto LOQ, and do we need to do the same for the other SANS instruments?
