### ISSUE TITLE
Plotting: show coordinates when hovering over graph

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7406]
## Where?

As a user of plotting on reflectometers, I would like to be able to hover over a point on the graph to get coordinates for this point.

This is possible in the underlying webagg backend that we use as the basis for our custom backend - we do not need to implement any complex logic as part of this issue, we just need to tell matplotlib where the mouse is positioned and it will reply with the coordinates in a form suitable for display.

This is largely a translation exercise from the [existing MPL JS implementation](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/web_backend/js/mpl.js) into our RCP implementation in the GUI.

## How?

- Hook up eclipse mouseOver handlers in view to send mouse over events to the model (throttle rate to e.g. 10Hz to not overload backend)
  * I believe the appropriate eclipse API is `plotCanvas.addMouseTrackListener(new MouseTrackListener() {` - this has hover, enter and exit methods which eclipse will call when the mouse traverses the relevant widget - we can get curson positions from the `.x` and `.y` fields of the events from this API.
- In the model, send the appropriate message describing the mouseevent to the MPL backend
  * See `mpl.figure.prototype.mouse_event` in [equivalent MPL code](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/web_backend/js/mpl.js) for details of how to implement this
- Add support for handling `message` events from the MPL backend in model
  * These come in as JSON messages, we are already parsing the JSON but ignoring event types we haven't implemented yet
  * See `mpl.figure.prototype.handle_message` in [equivalent MPL code](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/web_backend/js/mpl.js)
- Pass through `message` from model to view and display it in the view

## Acceptance criteria 
- [ ] Hovering over a part of a matplotlib graph in the GUI allows the coordinates of the point to be seen
- [ ] Functionally similar to hovering on a plot drawn by the native matplotlib `webagg` backend

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by ConorMFinn** [comment]
Completed Via:
- ISISComputingGroup/ibex_gui#1492
- #7425
