### ISSUE TITLE
tcioc: move settick and unsettick to beckhoff test runner

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7409]
we should move settick and unsettick to the beckhoff test runner repo as its not something that should be added upstream to tcioc or really ever deployed to an instrument. 

these two batch scripts are required for running a simulated beckhoff which is not something that will ever be done on an instrument machine, however beckhofftestrunner is used locally to test against a simulated beckhoff. 

### acceptance criteria
- settick.bat and unsettick.bat are moved from support/tcioc/master to BeckhoffTestRunner

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/BeckhoffTestRunner/pull/12
https://github.com/ISISComputingGroup/EPICS-tcIoc/pull/19

to review check that the moved scripts are the same

**Comment by Tom-Willemsen** [comment]
Can you update the wiki page at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff-testing#building-and-simulating-the-code which references `settick` in `tcioc\master`?

**Comment by rerpha** [comment]
good spot, done
