### ISSUE TITLE
SCANS Library: Refine requirements document

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7411]
As someone who is involved in the SCANS library in any way I want to make sure that the initial requirements are up to specification

## Acceptance Criteria
- [x] The requirements (as a document or wiki pages) are understandable are complete - this means adding in flow charts for logic, and improving some of the wording and display of the requirements, as appropriate

## Notes
- There is most of a document already in place
- This should be minor updates

**Comment by KathrynBaker** [comment]
Proposed only to ensure that others can see the work and see some understanding of the requirements as it is going on.

**Comment by Tom-Willemsen** [comment]
Documents are in `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket7411` for the moment - if & when we start implementing this library, they should become part of the documentation for the library.

**Comment by KathrynBaker** [comment]
Opinion of instrument scientists being sought in order to review this

**Comment by FreddieAkeroyd** [comment]
Moved to impeded while instrument scientist opinions are sought

**Comment by KathrynBaker** [comment]
Finally the document is complete. It can be viewed at https://stfc365.sharepoint.com/:w:/r/sites/ISISProject-1396/Shared%20Documents/General/Project%20documentation/

It has been agreed by the scientists involved, and as @FreddieAkeroyd was involved in those emails, and has already read the document, he may be the best reviewer for this ticket.
