### ISSUE TITLE
SCANS Library: BlueSky Evaluation

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7412]
As someone wanting to scan items on the beamlines, I want to make sure that the most obvious solution that is used somewhere else is not appropriate to us before starting on a coding job.

## Acceptance Criteria
- [ ] The requirements doc/wiki pages have a section detailing where BlueSky would be an appropriate solution or what work would be needed to make it suitable for the ISIS requirements

**Comment by KathrynBaker** [comment]
Proposed only to ensure that others can see the work and see some understanding of the requirements as it is going on. Note that this should still be pointed.

**Comment by Tom-Willemsen** [comment]
Document is in `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket7412`.

**Comment by KathrynBaker** [comment]
As I didn't actually do anything for this, I shall take my face off it, and then review it

**Comment by KathrynBaker** [comment]
Document is clear enough in scope of what was being considered, I am content that it can be taken forward alongside the requirements to hopefully provide a solution that benefits our instruments.
