### ISSUE TITLE
Test VTI SPC on Muon Beamline(s)

### ISSUE THREAD

**Issue by ConorMFinn** [ISISComputingGroup/IBEX#7415]
The new software pressure control system for the Mercury ITC controllers should be tested to make sure it’s working as intended.

This was ironed out with some python scripts prior to the IBEX implementation, so it may be worth running both v3/v4 of those scripts and checking they run the same way. 

Need to sort this out with Peter Baker or Chris Lawson. 

## Acceptance criteria 
- [x] A date/time to get the SPC tested is organised. 
- [x] Upgrade NDXEMU to include the new functionality
- [ ] Run the config upgrade script on NDXEMU
- [ ] Any issues found during testing are written as tickets (or fixed if very minor). 

Details of the original testing done with the python scripts can be found here: `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket7415andTicket6947_VTI_SPC`

## PRs:
- [ ] https://github.com/ISISComputingGroup/EPICS-ioc/pull/743

- Updated the wiki page here for the hotfix made on EMU: https://github.com/ISISComputingGroup/IBEX/wiki

**Comment by ConorMFinn** [comment]
Test report:
- Config for Temp Card 1 set up, need to run the config upgrade script on the machine properly when this is fully deployed.
- Initially wasn't able to find the calibration file for the pressure max lookup (issue given below).
- Successfully cooled from 100K down to 2K. Then back up to 50K. Some slight, but expected, overshoot. 
- Now running an overnight script to test another two big jumps in temperature and a ramp from high to low. 

Issues Found:
- [ ] Using `$(INSTRUMENT)` in `st-temp-spc.cmd` didn't return the right dir. Replace this with `$(ICPCONFIGHOST)`

**Comment by Tom-Willemsen** [comment]
Final report for this (from scientists) is in `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket7415andTicket6947_VTI_SPC\Cryostat Pressure Control_KY.docx`
