### ISSUE TITLE
IBEX GUI: Add motor controller field in ToM motor details

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7418]
As a developer/ops person i would like a field in the table of motors advanced view which tells me what type of motor controller an axis is being driven by. this would mean we don't have to dig into macros/globals/the settings area to figure it out. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] a field is shown in the ToM advanced view which says galil/beckhoff/smc100/mclennan/linmot etc. 

### Extra Information
we could load in a controller id record in addition to the motor record if we want to be consistent? 

does the motor record have any support for this already?

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
Does it actually need to be in the ToM or would displaying it on the motor + motor details OPIs be sufficient? Asking because the advanced ToM is already pretty crowded...

**Comment by rerpha** [comment]
> Does it actually need to be in the ToM or would displaying it on the motor + motor details OPIs be sufficient? Asking because the advanced ToM is already pretty crowded...

sorry, motor details is what i meant, forgot about the actual advanced view which shows motor energised etc.

**Comment by rerpha** [comment]
(in progress)
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/740
motor: https://github.com/ISISComputingGroup/EPICS-motor/pull/51
galil (uses galil motor extras rather than motorstatus.db): https://github.com/ISISComputingGroup/EPICS-galil/pull/67
gui:

**Comment by rerpha** [comment]
ps, deliberately left out the sm300 as we are removing it
