### ISSUE TITLE
Plotting: implement pan/zoom functionality

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7427]
## Where?

As a scientist on EMU and Reflectometers I would like the ability to pan/zoom matplotlib plots. To make the pan/zoom useful we will also need to implement the matplotlib toolbar containing "home", "back" and "forwards" buttons as well.

## How?

SImilar to https://github.com/ISISComputingGroup/IBEX/issues/7406, this does not require any complex logic in the UI - we just need to listen to cursor events and send these to matplotlib via websocket, which will then respond with an appropriately zoomed/panned plot image. Similarly the home/back/forwards buttons just send an event to the matplotlib backend - no special logic is required. 

Mouse positions are already being sent, so the only remaining implementation to be done as part of this ticket is:
- Send mouseup, mousedown, and mousedoubleclick events to matplotlib when the corresponding eclipse event is fired on the plot canvas.
- Implement the pan/zoom buttons along with home, backwards and forwards.
- Listen to the matplotlib messages specifying whether forwards/back are enabled, and enable/disable the buttons accordingly

Use the [existing matplotlib JS implementation](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/web_backend/js/mpl.js) as an implementation guide.

## Acceptance criteria 
- [ ] As a user:
  * [ ] I can pan a plot
  * [ ] I can zoom a plot
  * [ ] I can go back to a "previous" view after a pan or zoom operation
  * [ ] I can go forwards to a view after pressing back
  * [ ] I can reset the original view of the plot (equivalent to matplotlib "home" button)
  * [ ] The back & forwards buttons are enabled or disabled correctly when I cannot go back/forwards
- [ ] Functionaliy similar to the pan/zoom functionality to the native matplotlib WebAgg backend (tip: this is accessible at 127.0.0.1:8988 in a web browser when you have plotted from IBEX, but avoid having both open at the same time)

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
feel free to re-point if my guess is wrong, just satisfying project board checks

**Comment by boeuf-codes** [comment]
PRs:
 - https://github.com/ISISComputingGroup/ibex_gui/pull/1497
 - https://github.com/ISISComputingGroup/IBEX/pull/7462
