### ISSUE TITLE
start/stop ibex server: log to \instrument\var\ibex_server instead

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7429]
As a developer i would like the start/stop ibex server scripts to log to a folder inside of \instrument\var\logs instead of just the root of the directory. On my dev machine it is starting to clog up the root directory after so many starts/stops, would think the same will be happening on instruments. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] start_ibex_server.bat and stop_ibex_server.bat both log to \instrument\var\logs\ibex_server\ rather than \instrument\var\logs
- [ ] ~optionally, the existing files are moved from instrument disks to new folder~ meh, we can do this next time we are in \instrument\var\logs by chance

### Extra Information
This ticket will involve making a fresh deployment create an ibex_server directory in \instrument\var\logs as well as modifying start/stop_ibex_server.bat to log to it.

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
I think we cannot rely on the deployment script to create the directory e.g. developers do not do deployments to their computers. Some directories already get created in config_env, or maybe create it in the start/stop script itself

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/304

**Comment by rerpha** [comment]
to test start and stop ibex server and make sure the log goes to C:\instrument\var\logs\ibex_server\ instead of C:\instrument\var\logs

**Comment by rerpha** [comment]
probably not, the server start/stop is just for us for debugging really, which is why we now log them to file and only show a simplified output
