### ISSUE TITLE
Beckhoff: set up a virtual INTER to test against refl server

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7432]
may be able to just spin up https://github.com/ISIS-Motion-Control/MCU_xxx-Inter_Detector_Bench and create a refl server

## Acceptance Criteria
- [ ] The INTER configs are copied to MOTION
- [ ] The configs are changed to match the new configuration of INTER
- [ ] The refl server is changed to match the new configuration of INTER

## Notes
- NDXMOTION is a requirement before we can do this

**Comment by rerpha** [comment]
probably done on new NDXMOTION machine

**Comment by KathrynBaker** [comment]
Impeded as NDXMOTION doesn't exist yet

**Comment by rerpha** [comment]
DESC setting bat file in twincat dir of config repo - we will need to copy this over to ndxinter

**Comment by KathrynBaker** [comment]
All as expected
