### ISSUE TITLE
Deployment script: make choice of old or new galil driver more obvious

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7441]
## Where?

As a developer I would like to not accidentally deploy the new galil driver to instruments.

The current deploy script gives the choice between new and old, it defaults to old but we should make it more obvious that "new" is not necessarily the "better" choice.

In the latest round of deploys a small number of instruments were given the wrong driver so the instructions do need improving to prevent this reoccuring

## How?

Change documentation and deploy script to be more obvious/verbose about the choice between new & old galil drivers

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
It should auto-detect the best choice for you from a previous install and not prompt, unless the EPICS directory has been removed prior to running the script. Or was it prompting in other situations too?

**Comment by Tom-Willemsen** [comment]
From memory it is always prompting - hence the wrong choice being made on a couple of instruments during deploys.
