### ISSUE TITLE
Galil: changing MRES/ERES does not re-apply soft limits

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7446]
I noticed when setting up the mini jaws that by: 
setting a soft HLM/LLM to 40 and -40 respectively, then changing the motor and encoder res, did not re-apply soft limits going by the new resolutions. this then made moves prematurely hit the old soft limits. 

for info the soft limits applied in the table of motors are then scaled by the motor or encoder res and sent to the galil, this doesn't seem to work when you change the resolutions 

this may be by design, but i cant think of a use case where it'd be useful as the old soft limits are effectively useless if not re-scaled to resolution?

### Acceptance criteria
- [ ] Changing motor resolution re-applies soft limits 
- [ ] changing encoder resolution if UEIP == 1 re-applies soft limits to the galil

**Comment by FreddieAkeroyd** [comment]
There is a general motor record comment on this at https://epics-modules.github.io/motor/motorRecord.html#Fields_res "Currently, changes to motor-resolution fields have no effect on the values of limit fields (although they should). " however it is not clear what the correct behaviour should be e.g. should it preserve userspace (keep 40, send new raw steps for limits) or preserve raw (change userspace 40 to match raw steps on motor with new resolution). It looks like it preserves userspace and resets raw steps, i wasn't sure from the comment if the motor people were expecting the limits to adjust rather than keep the same?

**Comment by rerpha** [comment]
i think the latter would make more sense (probably easier too?) - on mres change adjust our end and keep steps the same. i think that'd be immediately apparent that the soft limits then need re-adjusting

**Comment by rerpha** [comment]
i might be getting this wrong, but it looks like we scale velo in the motor record when mres is changed? i guess we only do that on the epics side for a galil, so i think it would make sense to do the same with soft lims?  https://github.com/ISISComputingGroup/EPICS-motor/blob/master/motorApp/MotorSrc/motorRecord.cc#L2836-L2847

**Comment by rerpha** [comment]
ok, starting to see why this probably wasn't done beforehand. currently we update some fields on mres update ie. velo and vmax. VELO can be re-worked out because it's just `UREV*S`, VMAX is `UREV*SMAX` etc. as they are derived from other fields on the record so just need to be re-calculated. 

soft limits are not derived from other field values (although they are scaled TO the device when new values are sent ie. [here](https://github.com/ISISComputingGroup/EPICS-motor/blob/master/motorApp/MotorSrc/motorRecord.cc#L4010)), they are in some cases obtained from the device but not always.

To change limits properly I think we need to initially store MRES as another field (PMRES?) 

then on MRES/UREV change:
1. update MRES
1. scale soft limits by the difference in the new vs old MRES, by doing (MRES/PMRES)*{LLM, HLM, DHLM, DLLM}
1. store last MRES as PMRES

I think this would work, but i wanted to make sure doing this made sense before delving even further in to add the extra field. Alternatively - 

it would be much easier to re-scale the soft limits and send them to the device on an mres change so that the soft limits shown to the user are re-applied - you just do the same as if the limit values had been changed (set_dial_highlimit() etc) - this means if someone put in soft limits beforehand then changed mres they would still be correct on the device

**Comment by rerpha** [comment]
pr created upstream, awaiting feedback, so will put this in impeded

**Comment by kmpeters** [comment]
> pr created upstream, awaiting feedback, so will put this in impeded

Pull req #93 (https://github.com/epics-modules/motor/pull/193) was merged today.

**Comment by rerpha** [comment]
Cheers Kevin. 
@FreddieAkeroyd I might just merge in motor/master for this ticket, unless you think there might be things that break our fork
