### ISSUE TITLE
Windows 10: firewall rules & deployment

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7449]
Issue to capture time spent on diagnosing W10 firewall issues & deployment of solution.

**Comment by FreddieAkeroyd** [comment]
I think I did them all ?

**Comment by Tom-Willemsen** [comment]
To review: verify that you can connect to a selection of W10 instruments in both TS1 and TS2 using JMX (e.g. via visual vm) and to ioc shells via `console`.

**Comment by FreddieAkeroyd** [comment]
Checked JMX via nagios - seems to be working
