### ISSUE TITLE
Dynamic starting of IOCs

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7450]
As someone using/maintaining IBEX I'm getting tired of the long list of processes that don't actually do anything on my system potentially and the slow down and resource usage this costs, generating a python service which will spawn things as appropriate would be beneficial to limiting the problems.

## Acceptance Criteria
- [ ] There is a new python server which will perform the same functionality as the procserv control IOC
- [ ] This server should be a drop in substitution, and any test suites should work the same whichever version of procserv control is being run.

## Notes
- This would give us better control, make it easier to support any cut down instruments. 
- Make sure that the logic and communication protocol are encapsulated/abstracted enough to not be a hassle to change, and initially use pcaspy. 
- Do not forget the build IOC startups functionality which will also need to be included in the future.
- This was considered and agreed upon as a solution in relation to #3858

**Comment by FreddieAkeroyd** [comment]
This has been accomplished in #8558 by instead adjusting the SNL program in the existing procServControl
