### ISSUE TITLE
Extend TPG IOC to include the variations for the 500 series

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7458]
As someone reading pressures in IBEX I want to be able to do so from the most recent version of Pfeiffer Vacuum Gauge in use at ISIS.

## Acceptance Criteria
- [ ] Chase up if hardware is available, ~~if not, create a new ticket to test with hardware, and reduce the points on this ticket appropriately~~
- [ ] The emulator is refactored to accommodate both models of the TPG
- [ ] There are dbs, protos, substitute, and templates as appropriate for the 500 series TPGs
- [ ] Wiki page for the TPG500 is added 

## Notes
- These will not be available imminently, but will be made available to us once they are on site (expected in early 2023), as such this is not to be picked up too early
- The existing IOC deals with ~~26x and 36x models~~ the 300 model, so extending this to the 500 series should be straightforward to implement as similar functionality is already in place
- This model will be used in both the INTER and SURF upgrades that are due to be undertaken in 2023

**Comment by boeuf-codes** [comment]
Note: as part of this ticket, some suspicions about the TPG300 were hardware tested.
- TPG300s confirmed using `<CR><LF>` as a terminator for all commands
- Remains unseen whether the repeated `B1` for SPx is a typo or not

**Comment by boeuf-codes** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/798
- https://github.com/ISISComputingGroup/EPICS-TPG/pull/12
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/169
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/604
- https://github.com/ISISComputingGroup/ibex_gui/pull/1563

New wiki page:
 - [TPGx00](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TPGx00)

Spin-off tickets:
- https://github.com/ISISComputingGroup/IBEX/issues/7860
- https://github.com/ISISComputingGroup/IBEX/issues/7870

**Comment by zsoltkebel** [comment]
### For the reviewer

If you confirm that the device now behaves correctly please clarify that this ticket is not relevan anymore:
- https://github.com/ISISComputingGroup/IBEX/issues/7860

as well as remove the "known issues" part accordingly from the wiki:
- [TPGx00](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TPGx00)

See [this wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TPGx00#talking-to-a-real-device-or-the-emulator) on how to test commands sent directly to device or emulator.
