### ISSUE TITLE
truncate ts2 databases

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7460]
- SANS2D 
    - [x] Started
    - [x] Completed
- WISH
    - [x] Started
    - [x] Completed
- IMAT
    - [x] Started
    - [x] Completed
- INTER
    - [x] Started
    - [x] Completed
- LARMOR
    - [x] Started
    - [x] Completed
- LET
    - [x] Started
    - [x] Completed
- NIMROD
    - [x] Started
    - [x] Completed
- POLREF
    - [x] Started
    - [x] Completed
- ZOOM
    - [x] Started
    - [x] Completed

**Comment by rerpha** [comment]
instructions here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space 

happy to let others see me do it first though

**Comment by KathrynBaker** [comment]
The warnings that were there have gone away, I think I am happy that this was done
