### ISSUE TITLE
TOSCA: Configuration set up for in-situ illumination (experiment 5th December 2022)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7465]
As someone using the in-situ illumination on TOSCA I will need some help with the setup, and want to be sure that the functionality I need is in place.

## Acceptance Criteria
- [ ] A Keithley 2400 IOC component is created on TOSCA, with suitable blocks for the experiment

## Notes
- There is no need for a specific OPI or any special code at this time
- The main requirement for this experiment is being able to turn the output of the Keithley on and off
- Being able to read the voltage and current is highly desired
- Being able to set other values such as the voltage would be beneficial
- Looking at the existing IOC, it should provide all the stated functionality already, however, if the desired and beneficial functionality isn't available a ticket should be created to cover adding it before the experiments in February/March 2023

**Comment by rerpha** [comment]
email sent off asking best time to do setup

**Comment by rerpha** [comment]
going on thursday to set it up with the device

**Comment by rerpha** [comment]
Done - may just close this as there isn't much to review minus just checking the keithley2400 component on TOSCA - user is happy.
