### ISSUE TITLE
Keithley 2290 HV power supply

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7468]
## Where?

As an electronics technician supporting HV experiments I would like a Keithley 2290-10 power supply to be supported in IBEX.

- https://download.tek.com/datasheet/1KW-61672-0_2290_High_Voltage_PowerSupply_Datasheet_040720.pdf
- https://download.tek.com/manual/2290-10-900-01_C_Nov_2016_User.pdf

> We have just purchased a new power supply that has RS232 comms. We would love to get this added to IBEX when possible.
> We are not screaming for it per se but would greatly increase our capabilities
> You can physically have the unit if it helps you.

> The PSU will just be used for any HV experiments, generally field type experiments and also CHIPIR have a lot of HV experiments. Full control would be ideal please.
> I can also physically drop off the unit if you believe this to be of help.

## Acceptance criteria 
- [ ] Keithley 2290-10 can be controlled in IBEX
- [ ] Has emulator
- [ ] Has tests
- [ ] Has OPI

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by pheest** [comment]
https://github.com/ISISComputingGroup/EPICS-KeithleyHVPS
https://github.com/ISISComputingGroup/EPICS
https://github.com/ISISComputingGroup/ibex_gui
https://github.com/ISISComputingGroup/EPICS
https://github.com/ISISComputingGroup/IBEX
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-2290
\\isis\shares\ISIS_Experiment_Controls\Manuals\Keithley_2290

**Comment by pheest** [comment]
The system has not yet been tested with the output enabled.
I believe it should work, but in particular the operation of trips and alarms needs to be reviewed.

**Comment by pheest** [comment]
Tests run from C:\Instrument\Apps\EPICS\support\Keithley_2290\master with 'make ioctests'.

**Comment by FreddieAkeroyd** [comment]
Equipment is not static and can be moved away from a beam line and then brought back for a different experiment, so we are careful about what we autosave and apply/pini so as not to cause surprised. This we need to be careful about ` $(P)VOLT:SP` and `$(P)VOLT_ON:SP`. In general we would not automatically turn a supply on when the ioc starts, we would instead just initialise its value to something appropriate by using e.g. stream device @init handler. So VOLT_ON should definitely not be PINI,  VOLT:SP probably not either as somebody could connect a power supply that is on having set a value by the front panel, then start the ioc and the voltage would jump. So i think it is best if both were not PINI/autosave but instead used @init stream device handlers, but if it is not possible to read this status from the hardware we may need to discuss.

**Comment by pheest** [comment]
This approach is possible, *except* for the $(P)VOLT_ON:SP value which is not readable as a setpoint value.
Trying to use the VOLT_ON status readback to initialise the setpoint creates some interesting chicken-or-egg issues.

**Comment by FreddieAkeroyd** [comment]
Thank you for your work on this. I seem to have a problem with turning the supply on/off against the emulator, the system test for turning on did not check the actual readback status, when i changed it to do this it failed. If i try to turn it on and off from the gui, the led for on never lights up.
