### ISSUE TITLE
Motor & Motor details OPIs: make jog buttons more intuitive

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7471]
## Where?

As an instrument scientist on VESUVIO I would like the behaviour of the "jog" buttons on the motor & motor details OPIs to be more intuitive.
- It is not obvious enough that jogs are active - can we make the buttons a different colour or add an LED or similar when jog is active
- It is possible to enable jog in both directions simultaneously, with unclear behaviour. We should probably prevent this in the UI side.
  * Might be good to also prevent this for the home buttons - it's equally unclear what "homing in both directions simultaneously" means.
- Write a task to deploy these changes to VESUVIO and inform the scientists once this ticket is complete.

## How?

- Make the behaviour of the jog buttons more intuitive

## Acceptance criteria 
- [ ] The behaviour of the jog buttons is more intuitive

## How to Test 

Test that the behaviour of the jog buttons is more intuitive

**Comment by rerpha** [comment]
i don't think there's a specific field in the motor record for jog-moving, so would probably need to use MOVN and DIR to decide which button to colour

**Comment by KathrynBaker** [comment]
Make sure you discuss how the buttons should be more intuitive when you pick this ticket up if you don't already know.

**Comment by rerpha** [comment]
>can we make the buttons a different colour 

no, the ToM is probably the only place in the GUI that is (somewhat) colourblind friendly, i think we should keep this way and prefer the second solution of adding an LED next to it. PR attached :-) 


https://github.com/ISISComputingGroup/ibex_gui/pull/1507
https://github.com/ISISComputingGroup/IBEX/pull/7500

screenshots: 
![image](https://user-images.githubusercontent.com/14823767/203991319-31d7809d-eeb5-4a2b-b5f1-827a2b0873df.png)
![image](https://user-images.githubusercontent.com/14823767/203991274-72c01d8d-cae9-4607-9dc6-38f17f2452b2.png)
