### ISSUE TITLE
Script server - ensure ZMQ socket not existing errors are handled gracefully

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7483]
## Where?

Scientist on INTER (BW) reported the following error:

![image](https://user-images.githubusercontent.com/24375813/203011493-99573d3b-6a83-4993-9344-6a026cbd7703.png)

This should be handled internally, not propagated up and shown to the user in a message box.

## Acceptance criteria 
- [ ] Ensure this error is handled correctly
- [ ] Write tests to prove this

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
Can the error be reproduced? if so, how?

**Comment by NikolaRoev** [comment]
I mentioned steps in the pull request. I think the message box is some built client/Eclipse thing for unhandled exceptions, does not happen in the code as far as I could see.

**Comment by rerpha** [comment]
> I mentioned steps in the pull request 

ah sorry, hadn't got that far!
