### ISSUE TITLE
Eurotherm: calibration needs processing twice to apply fully

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7484]
## Where?

Scientist on NIMROD (TH) reports:

> Minor-ish bug report: I switched the calibration file from Pt100.txt to Pt100_C.txt for the NIMROD eurotherm, but the behaviour was *very* odd. Pt100_C.txt changed the units quoted to C, but still had the value in K (i.e. 295 for room temp), when I switched to Pt100_K.txt it did the opposite (i.e. showed 22K!!!)
> 
> After some trial and error I found you have to press enter twice when changing the calibration file name – first to change the quoted units, second to change the actual values. As long as we know to do this it is OK (so fix not urgent), but I thought I’d make you aware of the slightly weird behaviour.

## Acceptance criteria 
- [ ] Calibration only needs processing once to apply fully
- [ ] IOC tests written/updated to prove this

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
great, thanks, will send reply back to Tom saying we've fixed it and itll be in the next release
