### ISSUE TITLE
Moxa NPorts change the associated computer without having to know the IP address [Timebox: 4.5 days]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7490]
As someone supporting things like the 3D magnet, which has a Moxa Nport device that moves with it, but can become associated with the 'wrong' instrument for a given experiment I want to be able to change the associated instrument without having to know what the IP Address for that instrument is via a web page.

## Acceptance Criteria
- [ ] There is a web page I can navigate to which allows me to associate the moxa for specific equipment with the instrument it is currently be used on

## Notes
- Whilst the existing NPort web page suits us, it is too much detail for technicians doing equipment move - simple is the key element here
- There are various ways into those parts of the NPort settings, we need to check which is most appropriate for this, and see if we can use it
- This is probably best timeboxed, with any unsuccessful methods recorded, and appropriate new tickets created once more investigation has been documented for making this kind of functionality available
- It is worth just testing using a computer name instead of an IP address in the appropriate settings page, but as accessing that page requires knowing the IP address of the NPort, and the name in order to know the password for the NPort, it is less likely to be an easy to use interface for the technicians who have requested this

**Comment by KathrynBaker** [comment]
A script would be fine for the implementation, but a web page is the preferred option for the techs to just go and say "this piece of kit" is on "this computer" rather than them needing to know much of anything about it.

**Comment by Tom-Willemsen** [comment]
I've reached the timebox for this, with partial success. As a user there is a webpage you can go to, type in an instrument hostname, and the allowable IP list on the moxa will be updated to reflect that new hostname.

PRs:
- https://github.com/ISISComputingGroup/moxa-configurator/pull/1
- https://github.com/ISISComputingGroup/IBEX/pull/7563
- Docs: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Moxa-configurator

Current deficiencies:
- Currently limited to managing a single moxa per webserver instance - although I've written the code to hopefully be reasonably easy to extend to managing multiple moxas per webserver, I just didn't get to this within the timebox. Created https://github.com/ISISComputingGroup/IBEX/issues/7565 to capture this work.
- The UI/UX is extremely basic and could be made a lot nicer. No ticket yet - I think we should get some user feedback first.
