### ISSUE TITLE
Jenkins System_Tests_win32 job: Enable system tests 

### ISSUE THREAD

**Issue by boeuf-codes** [ISISComputingGroup/IBEX#7498]
As a developer I would like to see the system tests being run on the 32-bit Jenkins job `System_Tests_win32`. 

It was previously disabled due to some issues with ISISDAE working with 32-bit builds. 

### Acceptance Criteria
- [ ] Issues with ISISDAE and 32-bit builds fixed
- [ ] `call run_tests.bat` is run for all system test jobs again

### Extra Information
_Why it is needed?_

_Where required files/links are_

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
Build passed https://epics-jenkins.isis.rl.ac.uk/job/System_Tests_win32/44/

**Comment by Tom-Willemsen** [comment]
As mentioned above all code changes for this issue are part of https://github.com/ISISComputingGroup/IBEX/issues/7385 - so closing this issue.
