### ISSUE TITLE
JAWS: update jaws.cmd for position autosave

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7504]
As per https://github.com/ISISComputingGroup/IBEX/issues/7234 Instruments wishing to use the autosave feature will also need `jaws.cmd` updating to add `IFINIT_FROM_AS=$(IFINIT_JAWS_FROM_AS=#),IFNOTINIT_FROM_AS=$(IFNOTINIT_JAWS_FROM_AS=)`  as done in https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/45 e.g.
```
$(IFIOC_GALIL_01=#) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS0:,mXN=MTR0101,mXS=MTR0103,mXW=MTR0102,mXE=MTR0104,IFINIT_FROM_AS=$(IFINIT_JAWS_FROM_AS=#),IFNOTINIT_FROM_AS=$(IFNOTINIT_JAWS_FROM_AS=)")
```
This can be done everywhere as default is not to use autosave, it can be done pre-deploy as macros have defaults. It does not need to be done if autosave feature will never be required, but no harm to do everywhere for consistency

Key instruments to add this to would be ones that scan jaws gaps e.g. reflectometers 

NOTE: just make the above change to`jaws.cmd` change at this stage, do not enable `INIT_JAWS_FROM_AS` in configuration/globals.txt   Before use of autosave can be enabled there needs to be an autosaved value, which requires the ioc to have been run once with the changes in   https://github.com/ISISComputingGroup/IBEX/issues/7234 and hence needs to be done after next deploy on an as-requested basis

## Acceptance Criteria
- [ ] Write a script to run within the config upgrade script (in misc/master)

**Comment by KathrynBaker** [comment]
Some instruments have already had this applied (INTER and POLREF most likely)

**Comment by KathrynBaker** [comment]
Check for the macro, if it is there don't add, otherwise add it as appropriate; edge cases should raise a notification to look at things as required
Don't forget there are other ways that loads jaws.db (e.g. jaws.cmd and slits files potentially)

**Comment by FreddieAkeroyd** [comment]
There are edge cases to consider if this is to be done automatically:
- it is not just `jaws.db` though that is the most common,  jaws_vertical.db, split_jaws_header_vertical.db, and split_jaws_horizontal.db are also in scope. 
- in fact anything that loads `slits.template` from https://github.com/ISISComputingGroup/EPICS-jaws/tree/master/jawsApp/Db is in scope, so a `dbLoadRecords` of `someName.db` that has been created by an IOC substitutions file that loads `slits.template` is in scope too. 
I am not sure if we have any occurrences of the second, need to perform a search of all repositories to look for anything that depends on `slits.template`

**Comment by pheest** [comment]
Is https://github.com/ISISComputingGroup/EPICS-jaws/pull/2 at all relevant to this pull request?

**Comment by NikolaRoev** [comment]
Change it to 12.0.1
