### ISSUE TITLE
Beckhoff/tcioc: use status for limits not raw inputs

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7506]
Currently we use `STINPUTS-BLIMITFWD/BWD` which are the raw inputs for a limit switch, but limits have been added to the standard status array - we should instead use stStatus.bFwEnabled and stStatus.bBwEnabled 

the nice bit about this is unit tests that set limits can stay the same as they are setting the stinput fields which stStatus.bfw/bbwenabled use.

**Comment by rerpha** [comment]
need to test this https://github.com/ISISComputingGroup/EPICS-tcIoc/pull/20

**Comment by rerpha** [comment]
to review run tests as described in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff-testing#building-simulating-and-testing-the-code - the existing limits test should still pass

**Comment by LilithCole** [comment]
All changes look sound, functionality should be checked with existing tests, so would be happy to push through if the next reviewer  could run the tests. (BUT be sure to only install 4024.11 twincat otherwise the test runner won't work, hence my abandoning of the review).

**Comment by rerpha** [comment]
now superceded by #7522 which includes the changes
