### ISSUE TITLE
Beckhoff: replace countdbgrep with something that polls GVL_APP.nAXIS_NUM to get number of axes

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7526]
instead of counting the number of BENABLE PVs there are, I would like to first poll the beckhoff i am about to talk to for the number of axes it has.

**Comment by FreddieAkeroyd** [comment]
This needs to take into account if there is a communication issue, you don't want to think there are 0 axes and so not generate the autosave req file leading to all the previous motor settings getting lost

**Comment by rerpha** [comment]
i think by design its fine as a macro, it will hopefully never change after commissioning. Closing as i think this is a problem that doesn't exist
