### ISSUE TITLE
Focussing guide for Surf new slits, and motion, Beckhoff critical axis

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7533]
As someone who uses SURFI want to be able to incorporate the upgraded items within IBEX

## Acceptance Criteria
The following items can be used:
- [x] SURF Beckhoff
- [x] TPG 500 (#7458)

**Comment by rerpha** [comment]
impeded as motion team not ready. apparently some of the new tank axes aren't using the correct motors and are therefore stalling

**Comment by rerpha** [comment]
from surfs safety system: 
https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/63

the rest of the changes so far have been in the config area/autosave
