### ISSUE TITLE
Beckhoff/TC: set up motorextensions for SANS2D and LARMOR

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7539]
SANS2D and LARMOR have some extra fields in their beckhoff that they expose, currently through a TPY along with the rest of the motion fields. 

As we have now switched to a method that doesn't use the TPY file any longer, these fields need to be manually added and loaded in by some motorExtensions db files instead. we should create these and deploy/patch them on to save having to do this on the fly. 

The reason we should use motorExtensions is that if something needs to be changed globally it's much easier to do this in motorExtensions then just deploy, than try and edit each instance in the settings area/modify them with an upgrade script.

### Acceptance criteria
 - [x] Dbs are loaded in by SANS2D and LARMOR for the torque values and bump strip status respectively (see tc_project_app.db in settings area of respective instrument) - may be worth adding the PT100 readings for SANDALS as well. IMAT does not have any special fields, and CHIPIR probably won't be updated for a while as they are running a mini inst. 
 - [x] either an upgrade step for this is added or a note added to the release (or hotfix added if this ticket is completed after the release is created) to make a motorExtensions.cmd file for each instrument using a beckhoff with custom fields
 - [x] documentation is updated to make this the standard going forward for custom beckhoff fields

**Comment by rerpha** [comment]
I think an upgrade step is overkill for this as the beckhoff instruments (SANS2D, LARMOR and IMAT) need reconfiguring anyway and the SANDALS pt100s are due to change so i won't do them in this ticket and instead add them to motorextensions in #6097 

PRs: 
- motorextensions: https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/48
- RNs: https://github.com/ISISComputingGroup/IBEX/pull/7540

**Comment by Tom-Willemsen** [comment]
Task added for deployment: https://github.com/ISISComputingGroup/IBEX/projects/8#card-87462702
