### ISSUE TITLE
SANDALS: Enable reading of V2 valve status from PLC

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7543]
As a SANDALS beamline scientist, I would like to know the status of the new V2 gate valve so that it can be set appropriately for data collection.  If closed, data would be invalid.

An OPI need not be created as this is for a single value.  However, if a "vacuum" OPI already exists, then it could be included.  The intention is to add a block and enable run-control.

### Acceptance criteria 
- [x] Status of V2 valve can be read remotely
- [x] Appropriate block created in base configuration and run-control enabled

### Notes
- Scientists have strongly recommended that the work is completed in time for the 2022/05 cycle beginning on 07/02/2023
- The status of the valve can currently be seen on the local PLC HMI.  RS will allow this to be read remotely via FINS protocol.
- The connection details of the PLC and FINS node have already been provided.  See email to ExptCtrls on 19/12/2022@09:59
- Detailed FINS Wiki page [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Omron-FINS)

**Comment by davidkeymer** [comment]
Power to the SANDALS area, and therefore the PLC, is currently off and is expected to return by 13/01/2023.

**Comment by rerpha** [comment]
I don't think i;m going to bother creating an emulator for this as i have confirmed it works with the real device, and i think implementing the watchdog counter would take longer than actually writing all the fins dbs 

output from a camonitor with RS changing the v1 valve (same logic as v2): 
```
TE:NDW1836:FINS_VAC:V1VALVE:STATUS 2023-01-17 15:28:43.544956 Open  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:45.531703 47  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:47.531816 49  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:49.530974 51  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:51.530904 53  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:53.534107 55  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:55.535347 57  
TE:NDW1836:FINS_VAC:V1VALVE:STATUS 2023-01-17 15:28:55.552329 Opening/closing  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:57.559508 59  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:28:59.559599 61  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:01.560347 63  
TE:NDW1836:FINS_VAC:V1VALVE:STATUS 2023-01-17 15:29:02.529133 Closed  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:03.561036 65  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:05.565005 67  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:07.563012 69  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:09.564042 71  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:11.565170 73  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:13.568179 75  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:15.570064 77  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:17.570264 79  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:19.567322 81  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:21.570286 83  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:23.574302 85  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:25.530169 87  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:27.528343 89  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:29.526387 91  
TE:NDW1836:FINS_VAC:V1VALVE:STATUS 2023-01-17 15:29:30.529466 Opening/closing  
TE:NDW1836:FINS_VAC:WATCHDOG:RAW 2023-01-17 15:29:31.526337 93  
```

**Comment by rerpha** [comment]
PRs

ioc: https://github.com/ISISComputingGroup/EPICS-ioc/pull/766 
RN: https://github.com/ISISComputingGroup/IBEX/pull/7571
task: https://github.com/ISISComputingGroup/IBEX/projects/8#card-87657451

have patched this over to SANDALS, added blocks for error status and valve status. The scientists can add run control as needed.

**Comment by rerpha** [comment]
patched onto sandals. change listed here https://github.com/ISISComputingGroup/IBEX/wiki and task to re-patch here https://github.com/ISISComputingGroup/IBEX/projects/8#card-87657451

PRS
ioc: https://github.com/ISISComputingGroup/EPICS-ioc/pull/766
RNs: https://github.com/ISISComputingGroup/IBEX/pull/7571 

wikis updated: 
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Omron-FINS
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANDALS-Instrument-Details#note-gate-valve-plc
