### ISSUE TITLE
config version: make git commit message better

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7545]
Currently when an ibex deployment is being done and `config_version.txt` in `instrument/settings/config/...` is modified, it gets pushed along with the rest of the files by the blockserver into git with a generic commit message. It would be good on tracking upgrades if this file was pushed with an appropriate commit message, possibly even tagging the whole repo at the same time. The gitweb interface lets us see a list of commit messages for just that file, so it would give us a convenient log of upgrade versions and dates 

Who is responsible for doing the commit of `config_version.txt` - choices are:
- config upgrade script in https://github.com/ISISComputingGroup/EPICS-upgrade 
- blockserver (treats any change to config_version.txt as special and pushed with commit message containing file contents)

probably first option, unless we can see a separate path for a config version upgrade in which case second may be needed. 

TDB: tag repository on upgrade? e.g. on branch NDXMERLIN, create tag NDXMERLIN_10_1_0

**Comment by rerpha** [comment]
could just modify https://github.com/ISISComputingGroup/EPICS-inst_servers/blob/master/ConfigVersionControl/git_message_provider.py to check config_version.txt

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-upgrade/pull/70 i decided to change the config upgrade script for finer granularity for tagging between versions in case we need to roll back at all. 

To test this, change your local config_version.txt to 7.0.0 and check that:
`git log` shows several `upgraded from vx.x.x to vx.x.x`
and check the tags exist.
