### ISSUE TITLE
ENGINX: Extend functionality of existing Superlogics IOC and OPI

### ISSUE THREAD

**Issue by NikolaRoev** [ISISComputingGroup/IBEX#7561]
Follows on from https://github.com/ISISComputingGroup/IBEX/issues/5621.

As an instrument scientist on ENGINX I would like to use a Superlogics 8018 thermocouple and an 8016 strain gauge reader modules for data logging. The system has not been used since migration to IBEX.

The current IOC and OPI are designed for a 8000-Series thermocouple. The strain gauge reader has only one 
output channel and somewhat different commands.

### Acceptance Criteria
- [ ] Add support for an 8016 strain gauge reader to the existing IOC.
- [ ] Modify the OPI to accommodate the requested changes.

### Extra Information
Manuals: `file://isis/shares/ISIS_Experiment_Controls/Manuals/SuperLogics/`
Email from scientists: [email.pdf](https://github.com/ISISComputingGroup/IBEX/files/10401681/email.pdf)
Current setup:
![Superlogics_Thermo_Strain_RS232](https://user-images.githubusercontent.com/47421460/212071365-71f8b9bb-83cd-4644-a7c2-607ae7ad1166.jpg)

#### Notes
Might be better as a separate IOC as there are macros in the thermocouple that will not be present in the strain gauge.

**Comment by rerpha** [comment]
Do we know when these will be used next (if at all?) if soon, we should propose this ticket?

**Comment by NikolaRoev** [comment]
Judging by the email, this is a might be good to have eventually situation. Nothing urgent.

**Comment by rerpha** [comment]
ok, lets propose it to bring up at the next planning meeting, if only to keep the group up to speed
