### ISSUE TITLE
Keithley 2290 HV power supply testing - with suitable load fitted

### ISSUE THREAD

**Issue by pheest** [ISISComputingGroup/IBEX#7568]
## Where?
This ticket follows #7468 Keithley 2290 HV power supply, which was closed without completing all tests because no suitable load for the power supply had yet been fitted.

## How?
A suitable load has now been fitted to the test supply.
This allows testing to proceed.

## Reproducible?
[N/A]

### To Reproduce
- 

## Acceptance criteria 
- [ ] Tested to set voltage.
- [ ] Tested to set voltage and current limits.
- [ ] Tested to limit or trip when limits are exceeded.
- [ ] Tested for recovery from trip scenarios.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by pheest** [comment]
https://github.com/ISISComputingGroup/EPICS-KeithleyHVPS/pull/1
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-2290

**Comment by rerpha** [comment]
I am going to put this in impeded as I think #7468 needs to be merged first

**Comment by FreddieAkeroyd** [comment]
Will merge with exisiting review as PR was in response to comments there
