### ISSUE TITLE
GUI: Build for Windows 11 [Timebox: 2.5 days]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7581]
As someone encouraging the use of IBEX in a client server mode, and with the potential for Windows 11 to be increasingly used by those wanting to run clients, I want to test the client on Windows 11 and, if necessary, adjust the build system

## Acceptance Criteria
- [x] The client is proven to run on Windows 11, this may or may not need to be a separate build 
- [x] The client is connected to an IBEX server and displays the right values from a visual inspection by an individual
- [x] The client is connected to an IBEX server with appropriate permissions and can write values to an IBEX server (is this appropriate?)
- [ ] ~The suite of squish tests is tried against the client running on windows 11 (is this appropriate?)~ not really achievable on a developer machine due to time constraints and needing the machine for support duties, so span out to #8270 
- [ ] If necessary, a windows 11 client build is added to Jenkins - Spun out to #8269 

## Notes
- It may not be necessary to build the client separately on or for Windows 11, the existing builds of the GUI and python for W10 should be tried first and hopefully be OK.   
- The IBEX server is not being built or tested on Windows 11
- ~There are not any plans currently to use windows 11 on systems supplied by the FIT service desk or ourselves (this will change in time)~ - we think this has now changed. 
- Accessing a windows 11 system to test this may not be straightforward. We do have some Azure msdn credits and there are W11 VMs there, but they do not have access to site network. We can try asking FIT if they can create a W11 machine on their hyperV cluster.

**Comment by rerpha** [comment]
Can confirm that, under windows 11: 

the (eclipse built) GUI runs:
(todo)

the (maven built) GUI runs:
(todo)

CSS runs:
![image](https://github.com/ISISComputingGroup/IBEX/assets/14823767/b5f608d0-6255-4d2d-811c-a09180125b31)

as does the server - though I haven't built this on win11, I just left in place when i upgraded from win10. I did run most of the IOC tests and the ones that ran pass, I don't have daqmx to test some of the weird ones out though.

**Comment by KathrynBaker** [comment]
Initial tests all look good, the spun out tickets are also appropriate for the scope and other considerations of being an operational team.
