### ISSUE TITLE
Install script: fix adding autostart link

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7589]
As someone updating IBEX I don't want to add a second auto start link

## Acceptance criteria
- [ ] The script has been updated to check for the autostart link and it isn't added
- [ ] There are potentially multiple places (all users, local) and multiple names have existed for the script which should be harmonised

**Comment by KathrynBaker** [comment]
It may be as simple as the script is using a different location to that used in Windows 10, so the harmonisation should be fairly straightforward after agreeing the location

**Comment by pheest** [comment]
https://github.com/ISISComputingGroup/ibex_utils/pull/153
