### ISSUE TITLE
He3 filling station control software: labview modernisation

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7591]
## Where?

Software is called "Mefista" - running on Labview on a windows 7 machine (not on the network). Goran N can supply source code.

Acceptance criteria:
- [ ] Transition to win 10
- [ ] Replace NI PXI crate hardware - possibly no like-for-like replacement from NI - so labview may need modifying to account for new electronics
  * New hardware not yet purchased - have asked them to make sure our group is in the loop before anything is purchased and to include our group in any relevant meetings.

This replacement is mostly "preventative" - if the existing PXI cards fail they cannot be replaced - ideal timescales for this are apparently ~6 months (or shorter if the existing hardware fails)

Request is coming from "instrument development group".

Contact details for relevant person to contact about this are at `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket7591\contact.txt`

## Acceptance criteria 
- [ ] We have appropriately supported the migration of the "mefista" system to win10 & new electronics.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by KathrynBaker** [comment]
Not truly our area of expertise, and no resource to help, scientists have been advised to contact those with more expertise and more directly with NI
