### ISSUE TITLE
samplechanger: make case insensitive

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7598]
As someone using motion setpoints in scripting on SANS instruments I would like the system to be case insensitive so that I do not have to concern myself for that side of things

## Acceptance Criteria
- [x] All variations of text in a setpoint are acceptable to the scripting, see comments below for likely location to ensure this can be maintained
- [x] The OPI only displays uppercase versions of the positions

**Comment by KathrynBaker** [comment]
Updated information from the science group:

> We now have an inconsistency with the SANS scripting that means that instruments are behaving differently when preset positions are being used.  I believe this crept in when a request was made to allow Sans2d to have some camel case positions enabled (so, for example, 1CTRod).  This now means the following (the positions are given as examples):
> 
> For Sans2d:  1CT are now different positions 1ct
> For all other SANS instruments (I hope!):  1CT and 1ct are the same position
> 
> I don’t think camel case is handled by any instrument (although it would be fabulous if we could handle camel case if it’s a lot of work then we don’t need it at present).
> 
> After meeting with the SANS Group to discuss this issue then we are agreed that we would like to change Sans2d back and have 1CT and 1ct be the same.  We are happy to make the necessary changed to the present positions involving ‘Rod’.

> Please can we have 1CT = 1ct = 1Ct = 1cT on all 4 instruments; ie, that no matter what we/User types it will move to the same position (on that instrument).
> 
> The Changer OPI position combo boxes should only show the capitalised positions.
> 
> And the conversion needs to happen before the position checking for the scripting in _poslist is called in instrument.py (lines around L230, at least on LOQ).
>

**Comment by KathrynBaker** [comment]
Original ticket text:

> There were issues on SANS with the same changer and scans library, this may have been due to recent changes at reading positions from a PV and the scans library having a different case. This ticket is to make samplechanger names case insensitive, which seems like a good idea even if not teh solution. Motionsetpoints is already case insensitive .

**Comment by NikolaRoev** [comment]
- https://github.com/ISISComputingGroup/EPICS-sampleChanger/pull/15
- https://github.com/ISISComputingGroup/IBEX/pull/7669
