### ISSUE TITLE
GUI: add help icon/link to windows [TIMEBOX: 2.5 days]

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7599]
As a user I find having to go out of modal dialogues eg. the create/edit component/config window (and then the block creation window) very difficult to find help on a particular subject in the wiki thereafter. 

I Would like to add some sort of help icon in each window/perspective in the gui which opens a piece of documentation on how to use it. This should open a separate (**NON-MODAL**) web view window containing helpful information of the current view. 
For example the "add block" window should open the help page for adding blocks and their settings in the wiki in a web view. 

### Acceptance criteria
- [ ] Identify the locations in both the GUI and user manual where this would be useful
- [ ] A method of adding a help page where useful is identified
- [ ] Above is put in place where possible in the GUI

This may become an umbrella ticket, but we should get started on it first.

**Comment by boeuf-codes** [comment]
**PRs:**
 - GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1529
 - https://github.com/ISISComputingGroup/IBEX/pull/7633

New ticket for further work:
 - https://github.com/ISISComputingGroup/IBEX/issues/7632

**Comment by rerpha** [comment]
couple of things i noticed: 
- we should probably use our shadow hosted version of the user manual as that means if site internet goes out externally they will still be able to get help
- did you mean to add the script defs submodule in as part of your gui PR?
