### ISSUE TITLE
Catalytic Flow Reactor provisional driver

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7601]
As someone conducting an experiment with the catalytic flow reactor I want to be able to do some rough synchronisation of the behaviour of the reactor with the beamline at ISIS

## Acceptance Criteria
- [ ] There is a stream IOC that can be run up which will respond to an interrupt when data is available to update the appropriate PVs (see notes)

## Notes
- This is a bespoke piece of user equipment
- We are only reading it, there is no control of the device, but there is a need to split runs based on the behaviour of the reactor
- The data sent from the system consists of the following as a comma separated string: a state number, a block number (this is the cycle that the reactor is in), a "take data" indicator (start data collecting when it is a 1, stop data collecting when 0)
- The data will be updated roughly every 10 seconds without us sending a command
- All three will need blocks (our kind of block, which is used as a label to indicate the information), with the third one being used in scripting to define some suitable `wait_for` states before undertaking a `begin` or `end` as appropriate
- An experiment is scheduled for this on POLARIS in March 2023, this adds value, and simplifies the experiment and data analysis
- It is a sub D-9 COM port, using RS232 (other details not available at this point in time)
- This does not need a GUI

**Comment by KathrynBaker** [comment]
It may be achievable using SD TEST, so check that and the interrupt nature of being sent data every 10 seconds within that framework IOC

**Comment by rerpha** [comment]
if we dont have a device in the office that will send data over serial, this could be _very_ easily achieved with an arduino.

**Comment by KathrynBaker** [comment]
I don't think we do have anything that just spits data at us, so yes via an Arduino/similar is probably a good plan for us for testing. We should also consider getting the equipment to run an adruino through a moxa nport for similar testing (I have done it before, but I'm pretty sure that for once I have no notes, only the recollection that I used a hat that I bought myself and brought home in 2020 and I'm not sure where it is)

**Comment by Tom-Willemsen** [comment]
> PS my "emulator" is an arduino nano [...]

Can we make sure we also write a normal lewis emulator please so that we can test using ioc test framework etc? If you need an example of sending a constant stream of unsolicited messages from lewis, see the `mecfrf` stream interface for an example.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-Catflwr/pull/1
https://github.com/ISISComputingGroup/EPICS-ioc/pull/775

sounds like no OPI is needed so think this is sufficient. Will create task in task board to actually hook the thing up and set blocks etc. up on POLARIS
