### ISSUE TITLE
POLREF: new newport XPS stage for HTS magnet (configuration/test) [TIMEBOX: 0.5 day]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7602]
As a scientist on POLREF I will be using a new Newport XPS motion stage with the HTS magnet on 13th March.

Stage is currently setup for testing, I think we should commission it while we have testing access rather than waiting for the experiment day.

Some extra details in exp controls mailbox 01/02/2023

## Acceptance Criteria
- [ ] We have the motor parameters available for the experiment when it is on POLREF

**Comment by FreddieAkeroyd** [comment]
the XPS is listed in https://github.com/ISISComputingGroup/EPICS-motor/blob/master/motorApp/NewportSrc/devNewport.dbd along with SMC100 so i suspect you could use the SMC100 ioc but just change st.cmd to call a different configure command and maybe load a different db if we didn't have time for a full ioc.

**Comment by FreddieAkeroyd** [comment]
Or use https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/NWPRTXPS

**Comment by Tom-Willemsen** [comment]
Lowri & I went to have a look, we did IP configuration on the controller box (and this has now been reserved in DHCP by CMS). However we weren't able to use the manufacturer software itself to talk to the stage - we were getting a hang when the controller reboots after applying a stage configuration. We didn't get as far as trying any IBEX/EPICS stuff as the setup in the manufacturer software is a prerequisite.

I have let the support group/electronics know and given them the appropriate manuals, and said that we can go back to look at it once the hardware is confirmed as working from the manufacturer software.

**Comment by rerpha** [comment]
as of about 10 minutes ago, the newport controller is still "munted" and is coming up with EEPROM errors so leaving this in impeded until softmat/CK get in touch with manufacturer

**Comment by Tom-Willemsen** [comment]
Reply from manufacturer:

> this looks really like an issue inside the controller. The first error “unable to read Smart EEPROM” indicates that the controller cannot detect the stage. But the subsequent error “driver EEPROM reading failure for driver XPS-DRV11” says that the controller cannot even detect the driver card.
> 
> Hence the list of stages is empty.
> 
> This is not an error in configuration, this is an error in the hardware of some sort. The only place that you could check yourself, is the ribbon cable that connects the backplane of the driver cards with the rest of the controller.
> 
> If you want, you can try to check the seat of this cable. But the next logical step would be to return the controller through an RMA so we can check it.

**Comment by Tom-Willemsen** [comment]
Reply from soft-matter team after the troubleshooting note above from manufacturer:

> The driver card wasn’t quite engaged in the connector in the box.
> We were able to move the stage once we had rebooted the controller.

Sounds like it is now moving ok from manufacturer software, so we should be able to connect IBEX to it and test from the IBEX perspective.

**Comment by Tom-Willemsen** [comment]
This has been tested in the soft-matter lab and a config is present on SOFTMAT. Soft matter group are happy with the IBEX control.

Current plan is for it to be used next cycle sometime on POLREF, so copy over/recreate config on POLREF when that happens (the config is very easy - just an IP address and stage name - the IP is on the unit itself, the stage name is in the manufacturer interface or can be copied from the component on SOFTMAT).

**Comment by davidkeymer** [comment]
- Confirmed IBEX component on SOFTMAT created 10/03/2023@10:35.
- Checked IOC log `NWPRTXPS_01-20230310.log` and confirmed successful communication with device.
