### ISSUE TITLE
GUI: autocomplete runs function (!)

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7604]
In the ibex gui scripting console type:

```
def x():
    print("hello")
```

Then `x().` (to trigger the autocomplete) - the GUI prints "Hello" in a loop - this is very bad if e.g. the function has some effects that should not run immediately.

Worse, if `x()` does `time.sleep(...)` it hangs the GUI for that amount of time.

I think we probably need to fix this one and deploy a hotfix in time for cycle...

**Comment by Tom-Willemsen** [comment]
See if we can simply disable autocomplete as a hotfix for instruments.

**Comment by rerpha** [comment]
i tried giving this a go, i dont think its as simple as just setting an ipython autosuggest/turning jedi off, and also seems to be limited to the client scripting perspective (couldnt reproduce in a standalone genie_python.bat). I think setting autocomplete to off _can_ be done by some pydev prefs, but im not sure on how to actually set them in a good way

**Comment by rerpha** [comment]
pydev pr: https://github.com/ISISComputingGroup/Pydev/pull/4
i have uploaded this to the p2 repo, just testing that a client works

**Comment by Tom-Willemsen** [comment]
In a meeting with myself, @ThomasLohnert @FreddieAkeroyd @KathrynBaker we decided:
- We will create a patch release with the hotfix above to disable autocomplete.
- We will patch this on all TS2 instruments as a priority
- We will prioritise looking for a better fix for TS1 instruments
  * If we find a better fix - great - we will deploy that to TS1 in time for beam
  * If we don't find a better fix, we will deploy the hotfix above to TS1 instruments closer to beam start

**Comment by Tom-Willemsen** [comment]
Deploys (TS2):
- [ ] WISH
- [ ] LARMOR
- [ ] INTER
- [ ] POLREF
- [ ] SANS2D
- [ ] ZOOM
- [ ] IMAT
- [ ] LET
- [ ] NIMROD

**Comment by FreddieAkeroyd** [comment]
Having  installed pvdev into a standalone eclipse, the behaviour is definitely there. As noted in #7850:
* in editor view autocomplete doesn't run the function
* in the pydev console it does run the function
It may be possible to fix by looking through https://github.com/ISISComputingGroup/Pydev/tree/master/plugins/org.python.pydev.ast/src/org/python/pydev/ast/codecompletion and/or posting a bug report to pydev
