### ISSUE TITLE
SANS2D: goudsmit magnet

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7605]
As a scientist on SANS2D I will be using the "goudsmit" magnet for an experiment on 6th-7th March.

The magnet will be controlled by the Danfysik (model 8500) located just behind SANS2D blockhouse.

The magnet has been used previously on LOQ, so the main thing that needs doing as part of this ticket is creating configs/components/synoptics & pointing the danfysik to the goudsmit calibration file.

**Comment by Tom-Willemsen** [comment]
Went down to SANS2D today, and set up the relevant component + opi, but was unable to test due to being unable to power up the danfysik control board (it is interlocked out).

Done steps:
- Copy over component from LOQ
- Change COM port to SANS2D's (from historic SECI configs - if doesn't work, may need double checking)

To be done Monday 6th:
- Check danfysik address and input into IOC macros (currently assumed address is the same as LOQ's supply; may not be the case)
- Check serial settings etc against what the control board has set up
- Establish comms and test with the magnet plugged in etc.

**Comment by rerpha** [comment]
I _think_ they are OK. I didn;'t actually set anything up, but rang cabin a few times and left note saying to give us a call, but it all appears to be talking - the blocks for field etc. are all reading and updating, so think they must have got the comms settings right

**Comment by davidkeymer** [comment]
Have checked log files from 06/03/2023.  Valid values for `Field` (`IN:SANS2D:DFKPS_01:FIELD`) start to appear from run `SANS2D00077218` in the middle of the day and continue thereafter.

As previous comment states, ExptCtrls Group was not contacted during the day despite best efforts and so it was correctly assumed that the PSU and magnet were behaving as expected.  Closing ticket as a result.
