### ISSUE TITLE
Multiple instruments: GUI freeze and crash [Timebox: 4.5 days, 0.5 days review]

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7610]
The GUI froze on WISH, scientist noticed values were not updating, clicked on synoptic perspective which them caused an hourglass and after 5 mins or so a GUI crash. They restarted GUI and all fine.  Looking at nagios client memory started shooting up around 06:30 AM this morning

## Acceptance Criteria
- [ ] Reproduce the error
- [ ] Get a debugger set up and see if the cause of the crash can be seen
- [ ] Create a ticket to either continue the timebox if the error hasn't been found, or to apply the fix as appropriate

**Comment by Tom-Willemsen** [comment]
LARMOR & INTER have both reported a similar problem which looks like a memory leak of some sort, we then get `java heap space` errors on basically random threads once the issue occurs.
