### ISSUE TITLE
IBEX upgrade script: ensure backup steps work before continuing

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7611]
As a developer I want to make sure we have backups of the old version of IBEX before updating - in case we need to roll any items back in future.

On LET it looks like the GUI backup step failed, this made a support issue much harder than necessary.

Propose looking for some "sentinel" files (e.g. the `VERSION.txt`) for each of EPICS, gui & python and only letting the script proceed if they are present.

**Comment by danielmaclaren** [comment]
## Pull Requests:

https://github.com/ISISComputingGroup/ibex_utils/pull/158
