### ISSUE TITLE
Beckhoff: log less

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7618]
IMAT filled up their disk with 10+GB of messages in <24h of the form:

```
[2023-02-14 23:59:59] 2023/02/14 23:59:58.391 [ERROR] C:\Instrument\Apps\EPICS\support\adsDriver\master\adsApp\src\ADSPortDriver.cpp:747 integerRead(): [ads-port] Read failed(1010): data could not be read
```

after a plc code change. 

### Acceptance criteria:
- [ ] The beckhoff driver does not log _unreasonable_ amounts after a plc change on the controller, or on disconnection from the hardware.

**Comment by rerpha** [comment]
consider adding a last error code to https://github.com/ISISComputingGroup/adsDriver/blob/main/adsApp/src/ADSPortDriver.cpp#L745 and only log if its a new code

**Comment by rerpha** [comment]
we should probably make a PR [upstream](https://github.com/Cosylab/adsDriver) for this too, i suspect cosylab will want it

**Comment by rerpha** [comment]
I am going to submit two separate PRs upstream. 

1. Make the sum-read rate configurable from AdsOpen() ioc command
2. Add another ioc command option to not print loads if the same status has occurred

once these are approved i will merge in upstream and update our st-common to utilise the new command args

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/866
https://github.com/ISISComputingGroup/adsDriver/pull/4
https://github.com/ISISComputingGroup/IBEX/pull/8405

**Comment by rerpha** [comment]
potentially linked to #8339

**Comment by Tom-Willemsen** [comment]
The linked changes slow down the logging rate when disconnected to ~330MB/day (rather than 10GB). Further improvements in https://github.com/ISISComputingGroup/IBEX/issues/8406
