### ISSUE TITLE
Migrate manual system tests to a better platform - Proposal

### ISSUE THREAD

**Issue by NikolaRoev** [ISISComputingGroup/IBEX#7623]
As a developer I would like the manual system tests to be better organized and easier to carry out. The current solution is a shared spreadsheet making it inconvenient, among other things, to see who is working on which section and which tests have failed.

### Acceptance Criteria
- [x] Proposed solution will improve the manual system tests workflow.

#### Note
If proposal is accepted create a ticket to migrate the manual system tests to the new platform.

**Comment by NikolaRoev** [comment]
https://github.com/users/NikolaRoev/projects/6/views/1

When a new release needs to be tested, the template project can just be copied.

**Comment by KathrynBaker** [comment]
Agreed that the proposal should be undertaken, ticket in next sprint to undertake the creation of the template
