### ISSUE TITLE
LET: more accurate 'moving' indicator for oscillating collimator

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7625]
Currently on LET, the collimator moving pv just uses whether the collimator is *trying* to move as it's "moving" status. Having had some recent mechanical issues on LET, it would be useful to be able to directly read whether the collimator is *actually* moving physically.

This would reduce troubleshooting time on the instrument in cases of future collimator issues, and mean that the scientists have a more reliable block to put run-control on, reducing lost time.

### Acceptance criteria

- [ ] A new PV is available, based on the galil digital input, that detects whether the collimator is physically moving
  * [ ] Add to OPI
  * [ ] Tell relevant instruments about newly-available PV and ask whether they'd like their existing blocks/run control to use this new PV
- [ ] Check whether MERLIN/WISH collimators have a similar laser system, and also extend to them if so

### Implementation notes

The LET collimator is fitted with a laser which is plugged into the galil's digital input (and so already being read by IBEX - as `IN:LET:MOT:DMC01:Galil0Bi5_STATUS`.

This ticket is to provide a new PV for "collimator moving" on LET, where the logic is that if the laser PV has changed recently then it is moving, else it is stopped (it may stop with the laser pv either ON or OFF - the important thing is whether or not it has changed recently).

An epics `compress` record containing a circular buffer of recent values can be used for this, monitor last `n` seconds of values from the laser PV, take a min/max of circular buffer (also easy to do in EPICS), if min==max then collimator is stopped, else collimator is moving.

Alternatively we may be able to use the existing stability check DB and map unstable -> moving and stable -> stopped.

**Comment by rerpha** [comment]
annoyingly, its a different digital in number..... https://github.com/ISISComputingGroup/EPICS-galil/blob/master/GalilSup/Db/galil_Oscillating_Collimator_Merlin.dmc#L35

vs LETs https://github.com/ISISComputingGroup/EPICS-galil/blob/master/GalilSup/Db/galil_Oscillating_Collimator.dmc#L35

**Comment by rerpha** [comment]
once you're happy pls could you make a task to test on MERLIN/LET/both - difficult to test on our testbed galil as we haven't got anything fed into the digital i/os

**Comment by boeuf-codes** [comment]
PRs:

- https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/52
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/590
- https://github.com/ISISComputingGroup/EPICS-upgrade/pull/71
- https://github.com/ISISComputingGroup/ibex_gui/pull/1533
- https://github.com/ISISComputingGroup/EPICS-galil/pull/72
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/776

Release notes:

- https://github.com/ISISComputingGroup/IBEX/pull/7647

**Comment by boeuf-codes** [comment]
To set up to (sort of) test: 

1. Checkout various branches etc.
2. Copy the three files (not the readme) from `support\motorExtensions\master\settings\oscillatingCollimator` to your `configurations\galil`
3. Make `support\galil` and then `ioc\master\galil` (e.g. run `cd C:\Instrument\Apps\EPICS\support\galil\master && make clean uninstall && make && cd C:\Instrument\Apps\EPICS\ioc\master\GALIL && make` in an EPICS terminal)
4. Make `support\motorExtensions` (e.g. run `cd C:\Instrument\Apps\EPICS\support\motorExtensions\master\oscillatingCollimatorApp\Db && make clean uninstall && make`)

To test PV logic:
You should be set up to write/read to `$(P)MOT:DMC01:Galil0Bi5_STATUS` which is the laser PV the moving indicator is looking at - you can use this to check the logic of `$(P):MOT:OSCCOL:COLLIM_MOVING`:

- Useful to run a `camonitor` on `$(P)MOT:STAB:_VAL_BUFF` to see what values are in the buffer
- Also useful to run a `camonitor` on `$(P)MOT:STAB:IS_STABLE` as this is the PV that `COLLIM_MOVING` maps its values from

To test the visibility of the new group box:

- [ ]  Check the box is visible when loading `oscillatingCollimator_Let` from your `configurations\galil\oscillatingCollimator.cmd`
- [ ]  Check box is NOT visible when loading `oscillatingCollimator_Wish` from your `configurations\galil\oscillatingCollimator.cmd`

**Comment by Tom-Willemsen** [comment]
Please could you add some docs to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MERLIN,-LET-and-WISH-Oscillating-radial-collimators about this. For example:
- What controls whether it is used on wish/let/merlin?
- How this new check works
- How many samples / what sampling period are we using and where are these defined
- Some background about the laser system for people who don't know anything about it
-

**Comment by boeuf-codes** [comment]
@Tom-Willemsen 
Added documentation: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/MERLIN,-LET-and-WISH-Oscillating-radial-collimators#moving-indicators
