### ISSUE TITLE
Discussion: Check for divergence in Instrument Scripts

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7626]
As a developer, I would like to minimise divergence from the latest master version for instruments using the shared scripts library. We should make sure changes that have been made on any beamline are integrated into master following a cycle and all instruments updated subsequently. It would be useful to have an automated check that flags up when changes are present would be useful to ensure these do not get missed, or not discovered until it is too late to properly integrate e.g. just before a cycle.

This may require a technical discussion first to decide how and when we want to perform this check. 
- Do we want to run this check continuously or e.g. once after a cycle?
- Can we run it as part of configchecker? Do we want to? 
- Can we check the state on remote machines or do instruments need to automatically push local changes similar to the config area?

Something to consider is that if an instrument needs to make a change during cycle this may cause alerts until we are able to resolve it post cycle.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Have a discussion and decide what the solution should look like
- [ ] Write and propose a follow up ticket for implementing the solution

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by KathrynBaker** [comment]
Check after each cycle (so it isn't always red)

**Comment by FreddieAkeroyd** [comment]
There was mention above of automatically pushing changes, but that would depend on where the changes were - on the common or instrument specific branch. Automatic pushing might require putting each instrument onto its own branch, but then you would need to e.g. each cycle merge the instrument branch to master and also merge master back to the instrument branch to keep everybody up to date with all changes all in step. Having each instrument pushing to its own branch may make running a central jenkins test easier etc. but then is when and how often to check and what to check for:
- are there changes
- do tests still pass
- is it currently mergable without resolving conflicts

It might be possible to check remotely by mounting the drive or remote execution of git, remote mounting of the drive may give some issues though as the drive would typically be mounted under a different username to the file owners and git has started to not like this and moan about it a lot. Usually we have mounted `c$` via an admin account, we could share the script area separately read-only and then mount it as the local account  which might get round the git permission issues.

**Comment by esmith1729** [comment]
Notes of meeting on 10/07/2023
Attendees: Thomas L., Kathryn B., David K., Chris M., Jack H., Daniel M., Evan S., Zsolt K.

## Add new in-between cycle Task:
- Automated script run at the end of each cycle
- Instruments each on their own separate branch with an expected name

     > need to force scientists to not use their own little branches
     > given its our responsibility to run the git end of things, this will hopefully be an acceptable thing from scientists
- We can then run all of these checks for changes remotely, like instrument checker
- Script that runs git foo at the end of each cycle
- Creating new "flag" that tells whether we are in-cycle or out of cycle
- script that goes around all the instruments and pulls from master after this
- If someone's done something that can't be merged, that could be okay, but they'll need to stay on that same branch (?), but not get any of the benefits of the merge 
- Probably better as a "one shot" script than to run it continuously

### Running continuously might have issues:
- scans library is hard to read
- it's not trivial to tell how changes will impact everyone else
- Might work for just use by SANS, or Reflectometry, etc. exclusively, but it will be used by all of them, so this might cause huge issues to run continuously

## Where to run this process?
- One of the build servers? e.g. Jenkins
- Could run on the "instrument checker"
- Output when last repositories have been updated

# Action Items from Today
- Create ticket for possible in-cycle flag
- Clarify the procedure (make sure well documented and submit for discussion at next S.A.G.), might involve another meeting depending on response from SAG
- Write 3 scripts:
- Push for each instrument their local scripts repo branch to the remote repo, so we can check it on the central server
- Jenkins job that checks all changes to master
- One script that pulls down each branch and sees if it can merge master without problems

  > good chance that this will be difficult, have to "force pull" maybe, throw away local changes
  > might only be when we do deploys

**Comment by davidkeymer** [comment]
- Have checked that the minutes above accurately reflect the discussion (so has TL).
- Have read through all subsequently created tickets to check that they correspond to the actions from the discussion.
