### ISSUE TITLE
RIKEN: Remote tuning of Separators

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7628]
As an instrument scientist or PSU technician, I would like a way to _remotely_ tune the RIKEN separators with control of the PSU output and feedback from the vacuum system.

Suggestion from IS:
> "...a strip chart with 5 curves: positive voltage, negative voltage, positive current, negative current, vacuum. Current, voltage and pressure would have independent y-axes (maybe auto scaled, or set to suitable fixed ranges) with pressure being logarithmic, but they share a common time axis. There would also be numeric values of all these parameters, setpoint boxes for the voltage/current, and on/off buttons."

### Acceptance Criteria
- [ ] An OPI exists showing the relevant information and controls to be able to remotely tune a single separator
- [ ] Appropriate macros to be able to configure the OPI for each separator

### Notes
- PSU for control is Technix: two per separator, one per plate (+ve & -ve).
- Vacuum readback is provided by a specific channel on the relevant TPG300.  IOCs for all devices are running on RIKENFE, with PVs for each channel
- There are three RIKEN separators (1, 2, and 3).  This ticket is for tuning _one_ separator, i.e. values from two Technix IOCs and one TPG300 IOC

**Comment by zsoltkebel** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1559
- https://github.com/ISISComputingGroup/IBEX/pull/7871

**Comment by zsoltkebel** [comment]
update rate of the graph will need to be changed to 0.2 sec. Change trigger PV's scan field.

**Comment by zsoltkebel** [comment]
TODO: Remove autosaveFields from .db and use @init in the protocol to get value from device on localisation instead.

**Comment by zsoltkebel** [comment]
To update the graph more frequently:
- Scan rate of `:RAW` to set to .2 seconds (put it out into a macro that defaults to 1 second)
- change in XY Graph the trace update mode to `trigger on Y`
- ~~ No need to change MDEL field because in real setting the value will most likely change frequently enough ~~

Comment:
Device simulator seems to be very slow
