### ISSUE TITLE
Running genie_python in Mantid

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7631]
As a muon scientists I would like to be able to use genie python within Mantid to be able to calibrate across beamlines

## acceptance criteria

* Able to read a pv in Mantid

## to test
 
Run `add_genie_python_to_mantid.bat` and then  in a mantid scripting window try
```
from genie_python import genie as g
print(g.get_pv("CS:INSTLIST"))
```

There may be two errors/warnings:
```
Unable to disable CA console errors from COM.DLL: Could not find module 'COM.DLL' (or one of its dependencies). Try using the full path with constructor syntax.
```
this can be ignored, it is related to us using a locally modified version to reduce printing to screen

```
WARNING: genie_python only guarantees support for Python version 3.10.6, you are running 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
```
This is just stating that we use a different python base version to mantid

**Comment by KathrynBaker** [comment]
We probably should add it to the user manual, or at least make it appropriately explicit how to use genie_python within mantid. It's only used in a couple of places, and potentially only in the muon front end as standard. It has been used elsewhere in the past.

**Comment by FreddieAkeroyd** [comment]
Mantid is not installed on instruments, the script would be run on analysis computers that are not part of an ibex deploy. So adding it to the user manual is probably the only option really.

**Comment by FreddieAkeroyd** [comment]
It is only used in a few special cases as you are effectively scripting from an analysis computer

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/FAQ may be the best place for a "can i run genie_python in mantid?"

**Comment by rerpha** [comment]
added to https://github.com/ISISComputingGroup/ibex_user_manual/wiki/FAQ#can-i-run-scripts-from-mantid
