### ISSUE TITLE
GUI: Adding perspective help icons 

### ISSUE THREAD

**Issue by boeuf-codes** [ISISComputingGroup/IBEX#7632]
As a user I would like more of the IBEX GUI to have help icons. 

See [Ticket #7599](https://github.com/ISISComputingGroup/IBEX/issues/7599) for places that have already had them added.

Some places that could do with icons:
 - Perspectives:
   - Reflectometry
   - Scripting
   - Script server

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Perspectives mentioned above have relevant help icons

### Extra Information

For some guidance on adding help buttons, see the documentation written in  [Ticket #7599](https://github.com/ISISComputingGroup/IBEX/issues/7599) 

## How to Test
Check that there is a functional help button in the Script Server perspective and in the menu bar of the console in the Scripting perspective. These should link users to the relevant section of the shadow hosted wiki.

**Comment by ThomasLohnert** [comment]
Reflectometry front panel OPI already has a help button that links to https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Reflectometry-View

**Comment by will2201** [comment]
Making a new ticket regarding the OPIs for difficult iocs and any other places people would like help icons.
