### ISSUE TITLE
DAE: spectra graphs stop updating

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7636]
As a user I would like the spectra graphs to not stop updating. This has been an ongoing issue, some improvements were made as part of https://github.com/ISISComputingGroup/IBEX/issues/7216 but on analysis of a dump of a hung system it looks like a deadlock was introduced in https://github.com/ISISComputingGroup/EPICS-isisdae/pull/78 by calling this->timer.cancel() in exPV::interestDelete()

Previously timers were never cancelled but changed to a longer time period, it was felt this was clogging up the timer queue on instruments that scanned a lot of specta. However interestDelete() is called as part of  casPVI::removeMonitor that was taken a out the PV's lock, if the timer is running then it calls  casPVI::getExtServer which also tries to take out the PV lock, so there is a race condition that if the timer is active at the point a cancel is issued, it could deadlock on the PV lock.

This PR removes the timer cancel call from  interestDelete() and instead does not requeue the timer if interest has changed to false, it means the timer will stay in the queue and fire one final time when nobody is "interested" but the final result will be the same with no more timers being queued for non-interested (non monitored) PVs     

## Acceptance criteria

This is difficult to reproduce, probably just confirm that the same tests as done in https://github.com/ISISComputingGroup/IBEX/issues/7216 still work as expected

**Comment by rerpha** [comment]
maybe i'm doing something wrong, but on a simulated dae i still get pink borders despite this being in the log: 

``` 
epics> var isisdaePCASDebug 1
epics> CAS: exPV::doScan() updating data for "SPEC:1:1:Y.STAT"
CAS: exPV::interestDelete() in PV "SPEC:1:1:Y.STAT"
CAS: exPV::doScan() updating data for "SPEC:1:1:Y.UDF"
CAS: exPV::interestDelete() in PV "SPEC:1:1:Y.UDF"
CAS: exPV::interestRegister() in PV "SPEC:1:1:X"
CAS: exPV::interestRegister() in PV "SPEC:1:1:Y"CAS: exPV::doScan() updating data for "SPEC:1:1:X"

CAS: exPV::doScan() updating data for "SPEC:1:1:Y"
CAS: exPV::interestRegister() in PV "SPEC:1:1:X.EGU"
CAS: exPV::interestRegister() in PV "SPEC:1:1:Y.EGU"
CAS: exPV::expire() timer expired "SPEC:1:1:X"
CAS: exPV::doScan() updating data for "SPEC:1:1:X"
CAS: exPV::expire() timer expired "SPEC:1:1:Y"
```
