### ISSUE TITLE
SKF G5 Chopper IOC: Read additional values from controller to aid diagnostics on LET

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7658]
As a support technician, I would like to be able to log rotor axis positions to diagnose the cause of a particular controller error.  Staff need to analyse rotor speed and position data to determine whether or not a correlation exists between the two.  Only the IOC can log both (and more).

With this information, support staff will take the appropriate course of action, whether this be to decrease tolerances slightly, or  consult SKF for retuning the chopper itself.

### Acceptance Criteria
- [ ] Specified values are recorded appropriately

### Notes

- Communication with the controller is via MODBUS over Ethernet.  A configuration file exists (equivalent of a protocol file) which specifies which MODBUS addresses correspond to which chopper values (e.g. frequency, phase, start, stop, etc.).

- This ticket would involve adding the following addresses to this file and creating appropriate PVs to read them, and subsequently be logged.

| Address | Description | Length (bytes) | Type | Units | Access | Category | Purpose |
| ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- |
| 40911 | Peak Position FSV V13 | 2 | int16 | micrometers | R | Information | Gets the full scale value of peak position V13. |
| 40912 | Peak Position FSV W13 | 2 | int16 | micrometers | R | Information | Gets the full scale value of peak position W13. |
| 40913 | Peak Position FSV V24 | 2 | int16 | micrometers | R | Information | Gets the full scale value of peak position V24. |
| 40914 | Peak Position FSV W24 | 2 | int16 | micrometers | R | Information | Gets the full scale value of peak position W24. |
| 40915 | Peak Position FSV Z12 | 2 | int16 | micrometers | R | Information | Gets the full scale value of peak position Z12. |

![snippet](https://github.com/ISISComputingGroup/IBEX/assets/47421460/5cfb7d6d-1009-480a-9a7b-cd0876b8479d)

### How to Test

- Specified values appear in the archive

**Comment by davidkeymer** [comment]
It is not yet known how support staff would like to access this logged data.  Currently, ExptCtrls group is requested to extract values from the archive and return them in a formatted form (e.g. spreadsheet, or text file).  It may be that the support staff would like instant access, so a local installation of the IBEX client, configured appropriately, would be required.

**Comment by NikolaRoev** [comment]
- https://github.com/ISISComputingGroup/EPICS-SKFChopper/pull/8
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/167
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/599
- https://github.com/ISISComputingGroup/IBEX/pull/7817
- https://github.com/ISISComputingGroup/IBEX/issues/7816
