### ISSUE TITLE
Instrument hotfix process: make better [Timebox: 2 days]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7662]
As a developer I would like the hotfix process for instruments to be "better" and "less error prone", so that we avoid running into situations where we miss a hotfix being reapplied. Current hotfixes are added to a manual wiki page https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information--hotfixes but durign deployment a check needs to be made to look for missing hotfixes -  see #6994 for discussion 

### Acceptance criteria
- A selection of possible solutions is considered - note that this doesn't have to be just one solution, catching these kinds of problems at multiple levels may be a good thing!
- Discuss these solutions with the group
- Create & propose tickets for any solutions which the group decides are a good idea (or just do them if they're trivial)

**Comment by rerpha** [comment]
Could we add a step in the upgrade steps which just runs `git status` in \instrument\apps\epics, prints out the result and says you should check all of these changes against what's on the hotfix page?

**Comment by esmith1729** [comment]
# Meeting Notes 10/10/23
Attendees: Thomas Lohnert, Freddie Akeroyd, Kathryn Baker, David Keymer, Jack Harper, Sudeepta Chakraborty, Will Simms, Isaac Hill, Zsolt Kebel, Daniel McLaren, Evan Smith

## Summary: 
### Short term: Using control services, after deploy each instrument moved to own branch for EPICS
- When doing a hotfix:
     - Create ticket, commit to instrument branch, go back to ticket and fill in details, and make the changes in our development repos 
     - Add it to the wiki as well manually

### Long term:
- Process will check for those hotfixes automatically and update the hotfixes page

### Very long term: 
- Get everything less dependent so we can deploy and do fixes more easily generally


## Other Notes
- We want some kind of process that checks on instruments locally, whether uncommitted changes, and then set a PV in the Blockserver such as “undocumented hotfixes” that we can check in standup

- Blockserver pushes configs already; it could also push these changes for hotfixes, and “keep an eye on it”.

- Initial commit can be done as part of the deployment script. It could do an initial commit right after a deploy as well to the local instrument, which could refer to the ticket for the Release. 
     - Could function as a “marker” between which there will be hotfixes

- Putting instrument onto a branch and pushing it could be done during shutdown – Task
- Going around during shutdown and checking hotfixes, etc. 

### Should probably do the same for ibex_gui repository and genie_python, others as well

# Next steps:
- Write a task for checking hotfixes on instruments during shutdown
- Ticket: existence of repo, branching, etc. and adding to deploy script
- Ticket: automation script to check hotfix status

**Comment by KathrynBaker** [comment]
I think those tickets all cover the work required.
