### ISSUE TITLE
WISH: IOC and OPI for Keysight E4980AL LCR Meter

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7663]
As an instrument scientist, I would like to remotely control a Keysight (previously Agilent) E4980AL LCR meter.

There is currently a VI which provides basic functionality, and so it is proposed to replicate this level in the IOC & OPI.

### Acceptance Criteria
- [ ] An IOC and OPI exist for the device
- [ ] Tests, wiki page, etc are also created.

### Notes
- WISH scientists would like to perform a test with this device and the [Razorbill RP100 PSU](https://github.com/ISISComputingGroup/IBEX/issues/6678) at the end of the current cycle (end of March 2023) or failing that, during the following shutdown.
- Experiments using both devices are planned for May and July this year.  The May experiment is being performed by a 'local' user who is willing to come early to help set up and test the equipment.
- This LCR meter and the Razorbill PSU will soon be available in the office for testing.  Given this and the time pressure, it may be possible to omit the creation of an emulator and test directly with the hardware.

### Existing Code
- A VI exists here `C:\LabVIEW Modules\Drivers\Agilent E4980\Agilent E4980 - Front Panel.vi`.  It provides access to various setup parameters (which are sent to the device once on startup), and two continuous readbacks.
- A detailed analysis of the VI code has _not_ been performed.  However, the underlying setup and configuration sub-vis look like they could be simplified considerably.

**Comment by davidkeymer** [comment]
Photos of unit:

![Keysight_E4980AL_LCR_Meter_01](https://user-images.githubusercontent.com/10550207/224990796-a818fe94-ca03-47f4-8cd8-13f6b927cc78.jpg)
![Keysight_E4980AL_LCR_Meter_02](https://user-images.githubusercontent.com/10550207/224990801-8ab9d8a5-4f36-4dd0-9e6c-6b726d20ce13.jpg)

**Comment by rerpha** [comment]
so far
wiki page: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keysight-E4980AL-LCR-Meter
ioc https://github.com/ISISComputingGroup/EPICS-ioc/compare/master...Ticket7663_Add_IOC_KSE4980
support https://github.com/ISISComputingGroup/EPICS-Kse4980/compare/Ticket7663_Add_IOC_KSE4980
opi https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket7663_Add_IOC_KSE4980
