### ISSUE TITLE
Migrate manual system tests to a better platform - Implementation

### ISSUE THREAD

**Issue by NikolaRoev** [ISISComputingGroup/IBEX#7667]
Follows on from #7623.

### Acceptance Criteria
- [x] Manual system tests template project is created and tests are moved to it from the spreadsheet.
- [x] Wiki page is updated to reflect the new workflow.

### Extra Information
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests
Example project: https://github.com/orgs/ISISComputingGroup/projects/8

#### Note
Do this after https://github.com/ISISComputingGroup/IBEX/issues/7709 is completed.

**Comment by KathrynBaker** [comment]
It was decided to do this before completing #7709 as that was not being picked up, and with the team size having increased again ensuring this activity is simpler is important. A comment has been added to ask that the manual tests be removed from the template when they are completed.

**Comment by rerpha** [comment]
Looks good to me. The fully automated ones have been removed (makes sense to me) and the rest look to be present.
