### ISSUE TITLE
Save and Restore Device Settings - Implementation

### ISSUE THREAD

**Issue by pheest** [ISISComputingGroup/IBEX#7673]
As someone using a device within a configuration for multiple experiments I want to be able to easily save and restore settings so that I don't have to enter them manually and risk mistakes

### Acceptance Criteria
- [ ] A user can save a collection of PV names and values.
- [ ] A user can import and apply the values to another instrument or device.
- [ ] Additional GUI and data transport capabilities have been added to make this work.
- [ ] This is system tested.

### Extra Information
See #7393 for discussion outcome and paper prototype. 

**Saving PV collections**
PV collections should be saved or edited by means of a new sub-menu of the existing ‘Configurations’ menu.
The existing PV Selector dialog is primarily aimed at selecting input (read) PVs, but for this usage we need to select only setpoint (write) PVs. The existing dialog could be enhanced to support this requirement.
The existing dialog allows selection by use of partial names, e.g. an IOC name like KHLY2290_01. This functionality should be extended to allow use of wildcards such as ‘*’ or ‘?’. This would allow the user to enter e.g. KHLY2290_01:VOLT*:SP and select the setpoints beginning with ‘VOLT’.
It should also be possible to select individual PV names for saving to a collection by right-clicking in an OPI. Existing usage similarly allows PVs to be saved into configurations and components.
PV collections should be saved on the instrument computer using XML format. Values to store include a ‘friendly name’, the full PV name and the PV value. 
**Transporting PV collections**
The blockserver should be updated to serve PV collection details including ‘friendly names’, full PV names and values over channel access. Values would need to read from the instrument over channel access when saving the collection.
**Applying PV collections**
PV collections should be imported by means of a sub-menu of the existing ‘Configurations’ menu. The user would select an instrument to import from, and then select a collection to import. There is no need to make a special case of the local instrument as it can be similarly selected. 
There should be a new dialog that displays a list of the PVs and their values. The dialog should require the user to confirm the application of PV values by clicking a check box for each.
It should also be possible to apply a selection of PVs to an OPI by right-clicking. The dialog should display only those values that are applicable to the current OPI. 
After importing PV values in this way, the imported PV collection should be saved locally using the original name.

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by KathrynBaker** [comment]
Superseded by #7854 #7855 #7856
