### ISSUE TITLE
Discuss method of showing moxa ports and their COM mappings to scientists

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7675]
So many of our support calls are scientists asking what COM ports map to which moxas etc. - we should make a perspective/web page or something helpful and obvious to show this. 

Some ideas;
macros for moxa IPs and COM start numbers are stored in globals.txt, served by INSTETC and then shown on a perspective/help page/somewhere very obvious to the scientists - we should say on this page to go and check the moxa IP on the front panel to see whether it matches whats in the GUI. 
ie. MOXA1=x.x.x.x
MOXA2=y.y.y.y

and therefore COM ports 5-21 are on moxa 1, which has IP x.x.x.x, 
COM22-38 are moxa 2, which has ip y.y.y.y
this needs to be obvious when setting up IOCs, so a web page may be better 

we may have something in the user manual already, but clearly the scientists are not finding it/its too generic and doesnt say where COM ports start. 

### Acceptance criteria 
- [x] A short discussion is had on how to do this
- [x] A ticket is created to do the work with implementation details on.

**Comment by rerpha** [comment]
this could be added on to the home page/landing view if we are doing that too #7403

**Comment by rerpha** [comment]
Right, here is my idea, but we need to discuss this so will organise something. 

In globals.txt INSTETC loads in MOXAXX__NAME, MOXAXX_IPADDR and MOXAXX_STARTNUM for each Moxa where XX is the moxa number. This is then served by INSTETC or similar as PVs then we either use an OPI or a webpage (json_bourne?) to show the list of IPs. if it's stored in globals.txt it's not config specific and is also stored in version control. 
For display we should use a perspective as this is very obvious to the user/scientist, however we may need to also show it when someone hits help in the edit component/configuration "edit IOC" dialogue as well as that's where COM ports etc. are most useful. 

<insert mockup here>

We need to discuss these edge cases: 
Moxa port nums - do we _always_ have 16 ports on a Moxa or are there any models in use which use less? 
Contiguous ports - Is every moxa port contiguous everywhere? 

And need to discuss whether adding this to the web dashboard might be more accessible/futureproof than just INSTETC with an OPI to display it, in which case json_bourne will need to be modified as will ARINST if possible. 
Personally I think modifying the web dashboard to show it would make most sense as
A) the perspective only has to display a web page
B) a user can hit the help icon in the "edit ioc" page and get taken to the web page

I think this ticket should only cover permanent Moxas, not the floating models which go around with temporary sample env equipment.

**Comment by FreddieAkeroyd** [comment]
actually just noticed it has a COMNO array under server in registry listing the com port number for the moxa port

**Comment by rerpha** [comment]
right, just confirmed we can get all we need from the registry ie. 

```python
import winreg as wrg
import socket

location = wrg.HKEY_LOCAL_MACHINE

params = wrg.OpenKeyEx(location,r"SYSTEM\\CurrentControlSet\\Services\\npdrv\\Parameters")
server_count = wrg.QueryValueEx(params, "Servers")[0]

for server_num in range(1, server_count+1):
    soft = wrg.OpenKeyEx(location,f"SYSTEM\\CurrentControlSet\\Services\\npdrv\\Parameters\\Server{server_num}")
    ip_addr_bytes = wrg.QueryValueEx(soft,"IPAddress")[0].to_bytes(4)
    ip_addr = ".".join([str(int(x)) for x in ip_addr_bytes])
    hostname = socket.gethostbyaddr(ip_addr)[0]
    print(f"IP {ip_addr} hostname {hostname}")
    start_num_com = 1
    com_nums = enumerate(wrg.QueryValueEx(soft,"COMNO")[0], 1)
    for count, value in com_nums: 
        print(f"physical port {count} COM number {value}")
```
Gives us the IP, host, physical port->COM mapping, which i think is perfect

**Comment by rerpha** [comment]
one option we could do i suppose is just run up a flask server with the above code and point a perspective in the client to it

**Comment by FreddieAkeroyd** [comment]
We could build a static page same way an we do `beamlog` and then just refer to it from each ndx

**Comment by rerpha** [comment]
is that the newer nport "driver manager" rather than nport administrator?

**Comment by rerpha** [comment]
ok, might as well do that if the info is already there and COM mappings exist?

**Comment by FreddieAkeroyd** [comment]
question is now whether to do it centrally or on a per instrument basis. Doing it centrally makes it easier to refer to off instrument and means not running a web server per instrument, though doing on instrument we don't have to make a web page - a python script could make an OPI directly or some other table, csv or xml etc format that can be loaded by an opt - even a mysql database table. Doing on instrument would allow for private network moxas if we were to use them ever.

**Comment by rerpha** [comment]
Discussion had. To summarise: 

OPI view or similar to display mappings, with a button to force an update. 

Data will be served via channel access by instetc 

db server will poll registry when button is pressed and PV put to, then push values to local mysql instance and push to INSTETC 

OPI will also be visible in edit ioc dialogue by help button or similar.

**Comment by rerpha** [comment]
Discussion was had. Ticket is #7720

**Comment by KathrynBaker** [comment]
@rerpha the central aspect is missing from your notes and tickets
The other thing is the other ticket makes sense within the context of those of us who had the discussion, but anybody else (or ourselves after time) but I don't think there is enough detail to fulfil the above summary in it. Could you detail the sub tasks better please, e.g. split off a python script which will read the registry and post it to the SQL database when the trigger is seen from INSTETC getting that information and displaying it.

**Comment by rerpha** [comment]
when you say central do you mean the central mysql instance to push the info to? 

I think if we are going to do so perhaps #5818 would make sense to do first as we could use that , in which case #7720  is impeded until then. 

Have added some more info to the ticket on implementation in db server etc.

**Comment by FreddieAkeroyd** [comment]
```
Data will be served via channel access by instetc`
db server will poll registry when button is pressed and PV put to, then push values to local mysql instance and push to INSTETC
```
do we need INSTETC in the loop - doesn't db server already serve PV's as it is pcaspy?

regarding central aspect, we don't necessarily need it in a central mysql, what we wanted I believe was a central summary  page independent of an instrument being up, which could be done by polling mysql on each instrument (a similar idea to   http://beamlog.nd.rl.ac.uk/inst_summary.xml - it just polls and summarises information across instruments to build a static html page)

**Comment by rerpha** [comment]
we don't need INSTETC, sorry had put that on the new ticket already but not updated here. 

ok - will add that to ticket

**Comment by davidkeymer** [comment]
Attended meeting, read [ticket](https://github.com/ISISComputingGroup/IBEX/issues/7720) documenting resulting work.
Marking as reviewed and complete.
