### ISSUE TITLE
Tektronix AFG3XXX - option to configure number of channels

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7677]
POLREF used a `AFG3011C` model signal generator, which only has a single channel (physically). This caused many errors in the IOC log because the IOC is currently set up to assume (and read) 2 channels.

This ticket is to make the number of channels on the IOC _configurable_ - for example via an IOC macro or similar mechanism.

We should be able to borrow a `AFG3011C` from electronics if we need to do a test with hardware.

### Acceptance criteria
- [ ] Number of channels on the `Tektronix AFG3XXX` is configurable in IOC macros

**Comment by zsoltkebel** [comment]
To review, make sure channels are spin up when changing the new `CHANNEL1` or `CHANNEL2` macros in any variation of yes and no.
