### ISSUE TITLE
CaChannel: do not leak threads 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7686]
As a developer I would like genie_python not to leak threads. Currently each time the CA library is connected to an extra background thread is created, this was a side effect of changes made for the reflectometry server.

also as part of issue added exporting on debug symbols, and tidied up how an epics build is used as part of pcaspy/cachannel build
 
## Acceptance Criteria

running ioc tests does not lead to increasing thread count of the python process (see task manager)

## To test

- the genie_python branch pulls in the CaChannel `debug_builds` branch automatically, so you just need to swap branch for genie python and build
-  After merging CaChannel, you need to update the genie_python branch to remove `@debug_builds` from `git+https://github.com/ISISComputingGroup/CaChannel@debug_builds`  in `common_build_python.bat` before merging it

**Comment by FreddieAkeroyd** [comment]
Hmm ... just tried to add release notes for a second time :-D

**Comment by rerpha** [comment]
is label automation just not working at all now?
