### ISSUE TITLE
Deploy polarized SANS code for ZOOM/LARMOR during next shutdown

### ISSUE THREAD

**Issue by pheest** [ISISComputingGroup/IBEX#7688]
As an instrument script developer I want to deploy my script changes on the instrument so that I can use my updated scan modes.

### Acceptance Criteria
- [ ] Instrument scripts are updated to relevant beam lines during next shutdown.

### Extra Information
Pull request https://github.com/ISISNeutronMuon/InstrumentScripts/pull/107 was reviewed under https://github.com/ISISComputingGroup/IBEX/issues/7613 and is ready for deployment on relevant beam lines.

## How to Test
The scripts were tested using simulated IOCs and with both ZOOM and LARMOR configurations.

**Comment by GRyall** [comment]
will be caught by #7914 which is in progress
