### ISSUE TITLE
Document OPI Properties

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#769]
As a support person, I want the parameters (properties) of each OPI to be documented, so that I can assign appropriate values to each parameter when I am creating/editing Synoptics.

== Acceptance Criteria ==
1. Each\* OPI has a documented meaningful description in the opi_info.xml file.
1. The macros for the OPI and their descriptions are in the opi_info.xml file.

*Only the "front-panel" OPIs for now

== Notes ==
1. Most of the OPIs used on LARMOR have been added to the XML file, but they lack a proper description and the macros.
1. See also #844 (do it at the same time).

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 770.  Created by skn09965 on 2015-05-27T16:13:18, last modified: 2015-08-28T15:03:16_

**Comment by IsabellaRey** [comment]
NOTE: #844 was not addressed together with this ticket. See comment on #844 itself.

**Comment by IsabellaRey** [comment]
This is a duplicate of #1289

**Comment by AdrianPotter** [comment]
Awaiting reworks for #1289

**Comment by Tom-Willemsen** [comment]
Done as part of #1289
