### ISSUE TITLE
LET: Fix Setup of Rotation Stages

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7695]
As a: LET Instrument Scientist

Issue described in an email by LET scientists:

> LET runs with 3 different rotation stages - each of which requires 3 different components in IBEX. There are often issues with the setups of these - where they initially don't work.
> Currently the McLennan rotation stage on the LET Orange cryostat is running in open loop mode - without the encoder.  This did not use to be the case, but for some reason it couldn't be made to work in closed loop mode last cycle. 
> This needs to be fixed for next cycle.  Ideally, parameters needed by IBEX to run each rotation stage should be hard-printed on each rotation stage. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] McLennan Rotation stage can be run in closed loop mode with encoder
  * Note this refers to the *specific* rotation stage that LET used last cycle with the orange cryostat - just needs it's settings checking/updating/testing on LET,
- [ ] Make switching between different rotation stages more intuitive
    - [ ] Talk to the scientists about what their requirements are exactly
    - [ ] Depending on the requirements, set up config components that have the correct settings, or if the configurations are subject to change, record the required parameters in a sensible place e.g. printed on the equipment as I believe LET are suggesting in their email

### Extra Information
> Severity: CRITICAL - Causing lost beamtime
> Priority: P2 - Workaround available, but inconvenient

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by KathrynBaker** [comment]
This may be something to coordinate with EUSG, it's access to the numbers, and look them up or get them put onto the stage in question with a label.

**Comment by FreddieAkeroyd** [comment]
May split to separate tickets as fixing closed loop is likely to be resolved sooner than the longer term labelling solution

**Comment by FreddieAkeroyd** [comment]
Also added switch settings and encoder resolution notes to wiki https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/McLennan-motors

**Comment by FreddieAkeroyd** [comment]
Move mclennan changes to #7727 so can be reviewed

**Comment by rerpha** [comment]
Sounded like waiting on hardware investigation @FreddieAkeroyd ? have put in impeded

**Comment by FreddieAkeroyd** [comment]
Yes, have asked motion to take a look as encoder readback seems odd
![let_stage](https://github.com/ISISComputingGroup/IBEX/assets/1132753/c1c075fe-d50c-44a9-8d10-564608c913a3)
![let_stage2](https://github.com/ISISComputingGroup/IBEX/assets/1132753/b9d964cc-fcdf-4dcc-beab-97ccb3508b48)

**Comment by FreddieAkeroyd** [comment]
motion group are looking at this
