### ISSUE TITLE
RIKEN: Enable control of Line Valves from Vacuum Overview OPI

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7700]
As a RIKEN instrument scientist, I would like to be able to remotely control the seven line valves in the vacuum system.

This feature was always originally intended, and yet it was missed from the implementation in [5878](https://github.com/ISISComputingGroup/IBEX/issues/5878) and [7629](https://github.com/ISISComputingGroup/IBEX/issues/7629) because it wasn't clearly specified.  Also it may have been missed due to the number of people who have worked on the tickets.

#### Acceptance Criterion
- The valve icons need to be clickable and then trigger the PV

#### Notes
- Only remote _OPENING_ is allowed by the PLC
- Records already exist in the RIKEN DB [`C:\Instrument\Apps\EPICS\ioc\master\SCHNDR\db\RIKENFE.db`] of the Schneider PLC IOC [`LV(1..7):OPEN:SP`] - a record for each valve needs to be forced to process (`.PROC` field written to) to trigger a falling edge sequence which the PLC detects and subsequently opens the valve, subject to safety conditions.

**Comment by KathrynBaker** [comment]
Not quite a flash review due to the complexity of the OPI

**Comment by davidkeymer** [comment]
IS confirmed all updates functioning as intended.
