### ISSUE TITLE
MK3 Chopper: Test IOC (and VI) with v8.7 DLL

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7701]
As a developer, I would like to test the new v8.7 MK3 chopper DLL with the IOC (and VI) so that I can let PC know whether or not it is compatible with IBEX (and SECI).

#### Acceptance Criterion
- Compatibility of v8.7 MK3 Chopper DLL with IBEX and SECI is determined
- Any issues found will be spun out into new tickets

#### Notes
- The change to the DLL is required because of the imminent (required) upgrade of the chopper servers' OS from Windows 2012 to 2016.
- This ticket is of a higher priority than that for [implementing recommended methods of reading and writing values](https://github.com/ISISComputingGroup/IBEX/issues/3567), which should be completed subsequently.

**Comment by KathrynBaker** [comment]
There is a test server which should behave in a suitable fashion for testing.

**Comment by esmith1729** [comment]
No code changes to merge, but tested on NDXOSIRIS's 32 bit LabVIEW build, pointing at NDSR63CHOPTEST1 server. Checked the 64 bit DLL on my own machine, pointed at that same server. It works in IBEX and LabVIEW pointed at the test server, but haven't got a chance to test on actual hardware, will have to do during a shutdown, when the Chopper servers are upgraded.
