### ISSUE TITLE
Archive engine: add JMX monitoring and investigate `CrashOnOutOfMemoryError`

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#7710]
As a developer I would like the behavious of the archive engine under memory-exhaustion to be better:
- Add JMX monitoring (similar to how the IBEX GUI does it) to the archive engines
- Investigate adding `-XX:+CrashOnOutOfMemoryError` or `-XX:+ExitOnOutOfMemoryError` to force a restart of the archive engine if it runs out of memory, rather than trying to "limp along".

**Comment by Tom-Willemsen** [comment]
- https://github.com/ISISComputingGroup/cs-studio/pull/14
- https://github.com/ISISComputingGroup/IBEX/pull/7811

**Comment by davidkeymer** [comment]
- Reviewed code and tested CSS still builds with changes
- Checked JMX server started by connecting VisualVM
- Did _not_ reproduce 'out of memory' error as part of review
