### ISSUE TITLE
Muon Zerofield System: Add check to Setpoint Readback from PSUs

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7715]
As a developer, I would like the Zerofield IOC to make sure that it doesn't react to any invalid setpoints read from a power supply.

### Acceptance Criterion
- [ ] A 'sanity' check is present in the Zerofield code to ignore any invalid PSU setpoint readbacks

### Extra Information

During zerofield testing on MuSR, occasional  'spikes' were seen on the X-field.  These were caused by an invalid setpoint being read from its associated PSU (Kepco), a correction being added, and then sent back to the PSU as a new setpoint.  This was outside the physical range of the device, which defaulted to maximum output which then subsequently saturated the magnetometer.

Related to #7716 

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by FreddieAkeroyd** [comment]
This may also be relevant https://github.com/ISISComputingGroup/IBEX/issues/7719

**Comment by esmithExperimentControls** [comment]
[Link to PR](https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/18)

**Comment by esmithExperimentControls** [comment]
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/598

**Comment by esmithExperimentControls** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/7812
