### ISSUE TITLE
Muon Zerofield System: Add maximum Current setpoint ramp rate 

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7716]
As a developer, I would like the Zerofield IOC to limit its rate of controlling the correction fields by using a maximum ramp rate.

### Acceptance Criteria
- [ ] Maximum ramp rate is implemented in the Zerofield IOC
- [ ] A macro is made available to configure the rate

### Extra Information

During zerofield testing on MuSR, occasional 'spikes' were seen on the X-field. These were caused by an invalid setpoint being read from its associated PSU (Kepco), a correction being added, and then sent back to the PSU as a new setpoint. This was outside the physical range of the device, which defaulted to maximum output which then subsequently saturated the magnetometer.

Related to #7715 

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
I think an ioc test for zfcntrl might be nice if possible to test that the behaviour is fixed with the new ramp rate configuration. I also think that the default ramp rate hasn't changed - it was 1.0 hardcoded in the file? Do MuSR need to set a smaller ramp rate?

**Comment by NikolaRoev** [comment]
The changes I have made only expose the setting of the initial ramp rate through macros. Ramping on the Kepco is already tested. The Zerofield control IOC just writes current to the Kepcos it controls.

I don't think a smaller default ramp rate is needed for MuSR.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ReadASCII/pull/16/files#diff-54f8720d54f10c75f9ab9396639be9973c1f8748e294ce022649922c1cbbe030L84-L85

but if this was set to 1.0 anyway, im not sure why MuSR's zero field system spiked?

**Comment by rerpha** [comment]
talked with Nikola - my misunderstanding, ignore the last few comments
