### ISSUE TITLE
WISH set up LCR meter and Strain cell 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7717]
WISH need to be able to test a Keysight E4980AL + Razorbill RP100 setup on WISH_SETUP

### Acceptance criteria
- [x] Relevant support module, ioc and OPIs are copide over to WISH_SETUP
- [x] hotfixes list is updated

**Comment by davidkeymer** [comment]
25/03/2023 Hardware and software setup copied to WISH for actual experiment.
