### ISSUE TITLE
kepco: communication improvements

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7719]
As a developer I would like to remove `ExtraInput = ignore` from the kepco protocol https://github.com/ISISComputingGroup/EPICS-kepco/blob/master/kepcoApp/protocol/kepco.proto as it potentially increases the chance of a corrupt reply being interpreted as a good one.  

We may also want to consider adding `;*OPC?` to the end of set commands which should return `1` when it completes, however i might have already tries this and found our cards did not support it

**Comment by KathrynBaker** [comment]
Closing in favour of #7778 which is more comprehensive
