### ISSUE TITLE
GUI tests not being picked up by maven if file not ending with "Test"

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7725]
Some IBEX GUI unit tests are not being picked up by Maven as the files they're in do not end in "Test". This is bad!

You can see this in `uk.ac.stfc.isis.ibex.ui.devicescreens.tests` - these tests can be run in eclipse and some fail, but in the maven build (see jenkins/ibex_gui_build for the latest one) all tests are fine and only 8 are picked up in that test module.  

This ticket is to modify https://github.com/ISISComputingGroup/ibex_gui/blob/master/build/check_build.py to find out exactly which tests those are, and to rename the files so they _are_ run (and fail) 
we should then fix them thereafter. 

### Acceptance criteria
- [ ] the check_build script is modified to check for files within eclipse plugins that end in ".tests" which do not have the suffix "Test" and error/print them out
- [ ] The offending files are then renamed to include the "Test" suffix so they are run in the build, then either fixed if trivial or other tickets are created to fix them. It may be that some of them actually pass but aren't picked up. 

### Notes 
to run a maven build, use `build.bat` inside `build`  which will run all the tests. there may be a better way of doing this!

**Comment by Tom-Willemsen** [comment]
The exact pattern that test class names must match is documented in the `<includes>` parameter [here](https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/test-mojo.html).

**Comment by esmithExperimentControls** [comment]
[Link to Pull Request](https://github.com/ISISComputingGroup/ibex_gui/pull/1547)
