### ISSUE TITLE
Kepco BOP PSU: Investigate communications issue seen on Muon Zerofield system [Timebox: 2 days]

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7778]
As a muon (or neutron) instrument scientist, I would like the communications with my Kepco BOP PSU to be reliable.

While investigating recent zerofield issues seen on MuSR, it was discovered that the PSU occasionally sent (or a reply was misinterpreted) an invalid setpoint.  e.g.  actual setpoint: 0.74, readback: 9.74.

## Acceptance criteria 
- [ ] Source of communications problem is found
- [ ] Any resultant work is split out into further tickets

### Notes
- [Link to original support issue](https://teams.microsoft.com/l/message/19:8f40434ddbc744ec8f73bc7d240169c4@thread.skype/1682679095415?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&groupId=d9946ec3-a454-424f-b673-5ffcb9f9ade0&parentMessageId=1682679095415&teamName=IBEX%20Developers&channelName=support-issues&createdTime=1682679095415&allowXTenantAccess=false)
- Zerofield tickets for more details: #7715 #7716
- Suggest removing the  `ExtraInput = Ignore;` from the Kepco protocol file.  Also see [this ticket](https://github.com/ISISComputingGroup/IBEX/issues/7719) for more information.
- Enable I/O tracemasks and write output to file for later analysis
- Check whether or not the LabVIEW driver shows this behaviour
- Consider use of *OPC as well (see comment)

**Comment by KathrynBaker** [comment]
From Ticket #7719 

As a developer I would like to remove ExtraInput = ignore from the kepco protocol https://github.com/ISISComputingGroup/EPICS-kepco/blob/master/kepcoApp/protocol/kepco.proto as it potentially increases the chance of a corrupt reply being interpreted as a good one.

We may also want to consider adding ;*OPC? to the end of set commands which should return 1 when it completes, however i might have already tries this and found our cards did not support it

**Comment by davidkeymer** [comment]
Impeded until can get an opportunity to test the suggested changes to the Kepco protocol file.

**Comment by FreddieAkeroyd** [comment]
One of the kepcos giving issue was right on the full/quarter range point - as additional accuracy not needed have added  #7945 as this continued switching may cause a delay?

**Comment by FreddieAkeroyd** [comment]
Currently testing with scientists

**Comment by FreddieAkeroyd** [comment]
ISISComputingGroup/EPICS-kepco#22
ISISComputingGroup/EPICS-ZFCNTRL#19
ISISComputingGroup/EPICS-DeviceEmulator#173
ISISComputingGroup/EPICS-IOC_Test_Framework#608
ISISComputingGroup/EPICS-ioc#807
ISISComputingGroup/EPICS-zfmagfld#8
ISISComputingGroup/ibex_gui#1668

ISISComputingGroup/EPICS-DAQmxBase#9 already merged

**Comment by rerpha** [comment]
has this been patched onto MuSR? if so, it should be added here https://github.com/ISISComputingGroup/IBEX/wiki
