### ISSUE TITLE
SANS2D & others?: Component NOT in configuration appears to override one in a configuration

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#7779]
This occurred on SANS2D during setup of a complex experiment with several components.

There are different routes to edit components in a configuration, one from a right click on a block and one from the Menu bar.  This was how this issues was spotted but may not be significant.  It is probably reproducible with the current CCR configuration as setup on SANS2D

In this case the NON configuration component OERCON_1 component parameters (baud rate) appeared to override the baud rate in the MKS component with the Baratron OERCON_1 and two Vaccuum pumps.

### To Reproduce
Open and edit the OERCON_1 component whilst the CCR configuration is active. Set the baud rate to a different value to that in the MKS component, see which baud rate is effective on the OERCON_1 ioc.

## Acceptance criteria 
- [ ] There is a warning for editing a component which is not in the active configuration (but could be added).
- [ ] The issue of a component out of a configuration overriding a value in a component included in a configuration is investigated and solved (or a ticket create if the solution is more difficult)

## How to Test 
As for instructions for how to Reproduce

**Comment by Tom-Willemsen** [comment]
Logs for the relevant date all indicate the BAUD macro was being loaded from the correct component?

```
[2023-05-10 11:38:44] icpconfigLoad: * $(BAUD)="19200" (/components/MKS_gas_panel)
```

for example (I can see this component changed from 19200 to using default around `12:36:15` in the relevant log).

**Comment by ChrisM-S** [comment]
Closing this ticket as there is no evidence that the unloaded component had an effect on the IOC (although it was changed at the same time).  I suspect someone else changed the loaded MKS one in parallel, the OERCON component was changed around 12:26 to 9600 (by date of last xml change), the change at 12:38 to the MKS component seems to have taken effect at 12:40 when communication started working.
