### ISSUE TITLE
GUI: Synoptic component icon change bug

### ISSUE THREAD

**Issue by NikolaRoev** [ISISComputingGroup/IBEX#7789]
## Description
When creating a new synoptic component the default icon is `UNKNOWN`. Changing targets when the initial icon is `UNKNOWN` will select the default icon for each target. If the icon has been previously changed by the user to something else, changing targets should not change the icon again, unless the user does it, or if the user sets the icon back to `UNKNOWN`. In a specific set of circumstances that does not seem to be the case.

## Reproducible?
YES

### To Reproduce
- Create a new synoptic component.
- Select target with default icon `X`.
- Change icon to `Y`.
- Select target with default icon of `Y`.
- Select any target.
- The icon will now change as if the initial icon was `UNKNOWN`.

## Acceptance criteria 
- [ ] Issue is fixed.

#### Note
Testing of this behaviour will be handled in https://github.com/ISISComputingGroup/IBEX/issues/7787

**Comment by danielmaclaren** [comment]
Link to ticket:

https://github.com/ISISComputingGroup/ibex_gui/pull/1552
