### ISSUE TITLE
w/c 5/9/26 - MUONFE: convert remaining RS422 danfysiks to RS232

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7819]
As someone who maintains the muon front end danfysiks I would like them to communicate over RS-232 like the rest of the danfysiks in that area. 

### Acceptance criteria
- [x] Moxa cables are switched from the 422 adapters to standard Moxa (Male?) cables
- [x] Nport is configured to serialise rs-232 on the existing ports using RS-422
- [x] IOCs are tested and remain working

**Comment by rerpha** [comment]
Happening on 5/6/23

**Comment by FreddieAkeroyd** [comment]
@rerpha could you clarify which ioc logs DFKPS 01,02,07,09 are currently giving errors but they may not be the ones of relevance

**Comment by rerpha** [comment]
its DKFPS 05 06 07 08 09 - may be likely some are turned off as I saw TS up there a few days ago. They were talking when we switched them over- verified by DC team
