### ISSUE TITLE
ZOOM: Monitoring of testing of Detector Motion System

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#782]
As an engineer testing the movement of the Detector Motion System on ZOOM I want to make sure that it is behaving the same in vacuum as it does in air, so need a web cam to monitor the testing of the system when under vacuum.

#### Acceptance Criteria
1. The web cam is set up and monitoring can occur

#### Notes
1. Gareth Howells has done this for the same group in the past
1. This is in liaison with the engineering team rather than the scientists
1. This may occur late in sprint 2015_06_04, or early in sprint 2015_07_02

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 783.  Created by kvlb23 on 2015-06-03T16:16:36, last modified: 2015-09-17T14:44:09_

**Comment by KathrynBaker** [comment]
Some support has been provided as necessary (the last bit being from the networks experts) This ticket is no longer applicable so removing from the backlog.
