### ISSUE TITLE
MERLIN: IOC & OPI for Fermi Chopper condition monitoring system

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7820]
As a chopper technician or instrument scientist, I would like to be able to remotely monitor and log environmental conditions associated with the Fermi Chopper.

This chopper is (will be) a newly installed system of a new design, and so logging of condition monitoring data will be important to have in place from the beginning of the commissioning stage.

### Acceptance Criteria
- [ ] An IOC exists for communication with the condition monitoring system
- [ ] Logging is configured for important values
- [ ] #7846

### Extra Information
- The system uses PR Electronics 4500 modules, specifically the [4116 universal transmitter](https://www.prelectronics.com/products/multifunctional-devices/4100/universal-transmitter-4116/) fitted with [4511 communication enablers](https://www.prelectronics.com/products/communication-interfaces/4500/communication-enabler-4511)
- There are four single-channel units daisy-chained together
- Each measures a single temperature e.g. chopper pit, cooling water, chopper body and spare.
- The system uses `MODBUS RTU` for communication
- Manuals for the devices are in the shared network directory
- More information can be obtained from TC of Controls Group
- It may be possible to test using the unit from MERLIN before it is required
- Ticket for supporting the [chopper controller itself](https://github.com/ISISComputingGroup/IBEX/issues/6100)

**Comment by danielmaclaren** [comment]
Links to the pull requests:

- https://github.com/ISISComputingGroup/EPICS-Pre4500/pull/1
- https://github.com/ISISComputingGroup/EPICS/pull/335
- https://github.com/ISISComputingGroup/ibex_gui/pull/1592
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/805

**Comment by rerpha** [comment]
release notes https://github.com/ISISComputingGroup/IBEX/pull/7981
