### ISSUE TITLE
Triangulate pydev autocomplete bug

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7850]
As a person using IBEX scripting, I would like to be able to make use of the autocomplete function in the client embedded pydev console. At the moment we have disabled autocomplete in absence of a proper fix to https://github.com/ISISComputingGroup/IBEX/issues/7604. As a preparatory step for implementing a fix, we should investigate at what point this bug was introduced. We should be able to do this by running older releases of the client and checking whether the behaviour is present. This will hopefully allow us to narrow down the source of the bug, or confirm it has been there all along.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] We know which version of pydev introduced the autocomplete bug described in the linked issue above.

### Extra Information
To reproduce the bug, define a function in the client script console e.g. 
```
def test():
    print("hi")
```
then type `test().` to trigger autocompletion. If the bug is present, it will print "hi" in a tight loop.

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by NikolaRoev** [comment]
Release `5.0.0` with pydev `6.3.1`: Single execution of function, not continuous.
Release `6.0.0` with pydev `5.9.2`: Bug behaviour reproduced.
Release `7.1.0` with pydev `7.5.0`: Bug behaviour reproduced.

We can probably assume that the bug was not introduced by a dependency update of pydev.

**Comment by FreddieAkeroyd** [comment]
Hi,

I believe release `5.0.0` used pydev `5.2.0` so just to confirm: did you check `5.0.0` with both its original and an upgraded pydev `6.3.1` ?

**Comment by NikolaRoev** [comment]
I just went by what the release notes said https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/Release-Notes-v5.0.0.md, but you are correct. Double checking the share, IBEX release `5.0.0` has pydev `5.2.0.201608171824`.

**Comment by FreddieAkeroyd** [comment]
So it is either:
* something we changed between 5.0.0 and 6.0.0
* something that changed in pydev between 5.2.0 and 5.9.2
* some thing that changed in a dependency of eitehr us or pydev that indirectly causes the issue
To narrow further we would need to try release 5.0.0 with pydev 5.9.2 and release 6.0.0 with pydev 5.2.0 to confirm if it is a gui, pydev, or both issue
 
*: Single execution of function, not continuous.
Release 6.0.0 with pydev 5.9.2: Bug behaviour reproduced.

**Comment by FreddieAkeroyd** [comment]
though given the number of files changed between gui 5.0.0 and 6.0.0 we may want to narrow it down a bit more with the other 5.* gui versions

**Comment by NikolaRoev** [comment]
Should have probably been clearer, the bug still happens but it just executes once and the autocomplete UI opens and closes quickly. I am assuming that the slightly different behavior is due to IBEX code.

**Comment by FreddieAkeroyd** [comment]
I installed pvdev into a standalone eclipse, the behaviour is definitely there. I noted that:
- in editor view autocomplete doesn't run the function
- in the pydev console it does run the function

It may be possible to fix by looking through https://github.com/ISISComputingGroup/Pydev/tree/master/plugins/org.python.pydev.ast/src/org/python/pydev/ast/codecompletion and/or posting a bug report to pydev

**Comment by FreddieAkeroyd** [comment]
It looks like the issue has been there for a while, I am not sure how much further back we can check as it gets hardere with older versions. Given it doesn't show in editor view in PyDev itself might explain why it hasn't been noticed/fixed
