### ISSUE TITLE
Ibex_gui: Update Beam Status screen to include 2 new PVs

### ISSUE THREAD

**Issue by esmith1729** [ISISComputingGroup/IBEX#7852]
## Where?
Beam Status, under the "Beam Information" tab

## How?
2 new PVs were created as a result of this ticket: https://github.com/ISISComputingGroup/IBEX/issues/7822 :

- TG:TS2:DMOD:BEAM:LIM
- TG:TS2:DMOD:CHRGCHNG:TIME

These 2 PVs need to be displayed into the "Beam Information" tab, which is in the "Beam Status" Screen. The format for displaying these can be copied from the other PVs which are displayed here, such as AC:TS2:BEAM:STAT or TG:TS2:DMOD:BEAM, for example. Searching within the Java code for either of these PVs will likely lead one to the right place.

## Reproducible?
No

## Acceptance criteria 
- [ ] TG:TS2:DMOD is visible under "Beam Information"
- [ ] TG:TS2:DMOD:CHRGCHNG:TIME is visible under "Beam Information"

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by danielmaclaren** [comment]
Link to PR:

https://github.com/ISISComputingGroup/ibex_gui/pull/1556

**Comment by rerpha** [comment]
release notes (just to link to ticket) https://github.com/ISISComputingGroup/IBEX/pull/7853
