### ISSUE TITLE
dataweb: Tidy up instrument links

### ISSUE THREAD

**Issue by esmith1729** [ISISComputingGroup/IBEX#7861]
## Where?
on dataweb page

## How?
When clicking links that aren't listed as "(IBEX)", the back button doesn't work. There are also options for SECI and IBEX on instruments which no longer need SECI, these links can be removed. e.g. HRPD doesn't have a back button, but HRPD (IBEX) does.

## Reproducible?
Yes

### To Reproduce
- Go to dataweb
- Click a link that doesn't have (IBEX) after the instrument name
- try to go back to dataweb page

## Acceptance criteria 
- [ ] excess links are removed
- [ ] "back" funtionality works from each instrument page

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
This will be obsoleted by both no seci instruments remaining and the new web dashboard before we're likely to pick it up.
