### ISSUE TITLE
genie_python: can load_script spot missing brackets on function call

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7866]
An instrument script contained `g.end` rather than `g.end()` which was not reported as an error by `load_script` which just said
```
W: 14: Statement seems to have no effect (pointless-statement)
```
Typing `g.end` is not a python syntax error, but prints details of the function to screen instead of executing the function, which is not the intention. Is it possible to catch such errors better?

Ticket is to investigate `pylint` options (load_script uses pylint) so see if it is possible to trap this. Just making a `pointless-statement` an error may make too many scrips fails, what is considered a `pointless-statement` and is it possible to be more selective about what "pointless" things to error on. Or is there another pylint check we can enable that would catch this.    

## to reproduce

create a `myfile.py` file with contents
```
from genie_python import genie as g
from genie_python import BLOCK_NAMES as b

def myscript():
    g.begin()
    g.end
```
then use `g.load_script("myfile.py")` to load. The line `g.end` is not intended, it should be `g.end()` however there will just be a warning about `pointless-statement`

**Comment by FreddieAkeroyd** [comment]
There seems to be some caching issue - if i load a file with an error, it complains but then continues to complain if i correct the error and reload; similarly if i first load a correct file and then add a mistake, on reload it continues to say the file is OK

is it possible to reduce the amount of traceback output - currently it gives 

```
File C:\Instrument\Apps\Python\Lib\site-packages\genie_python\genie.py:1126, in load_script(name, check_script, warnings
_as_error)
   1124 instrument_full_name = _genie_api.get_instrument_full_name()
   1125 sc = ScriptChecker()
-> 1126 errs = sc.check_script(full_name, instrument_full_name, warnings_as_error=warnings_as_error)
   1127 if len(errs) > 0:
   1128     combined = "script not loaded as errors found in script: "

File C:\Instrument\Apps\Python\Lib\site-packages\genie_python\genie_script_checker.py:184, in ScriptChecker.check_script
(self, script_name, instrument_name, warnings_as_error)
    182     g_error_line = re.search(r'g\.', line)
    183     if g_error_line:
--> 184         raise Exception('An error has been found on line {} within the file {}, please check the "g." statement
and ensure that the brackets are not missing.'.format(error_line_numbers[line_numbers_position], script_name))
    186 return errors

Exception: An error has been found on line 11 within the file myfile.py, please check the "g." statement and ensure that
 the brackets are not missing.
```

**Comment by will2201** [comment]
Have just tried testing this myself and it works for me.

**Comment by FreddieAkeroyd** [comment]
Seems fine now, have just tided up output to remove  traceback
