### ISSUE TITLE
genie_python: load_script does not print name of script loaded to log file 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7867]
It would be helpful for debugging instrument issues if `load_script` recorded the name of the script it loaded to the genie python log file in `c:\instrument\var\logs`. It may be a few print statements just need to be changed to use `print_and_log` as details are printed to screen in the console, just not to the log file.

To test:
- create a py file defining a function
- use `g.load_script` to load it 
- check details of the run of the `load_script` command are placed in the genie python log file

**Comment by rerpha** [comment]
release notes might be good, just as its a nice feature?
