### ISSUE TITLE
Aeroflex Signal Generator - Add Local and Remote control buttons

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7878]
As an instrument scientist, I would like buttons to select `Local` or `Remote` control on the Aeroflex OPI.

### Acceptance Criteria:

- Local and Remote control modes are selectable remotely (if device allows)
- Display of current mode on OPI

#### Notes:

- It may not be possible to put the unit into 'Local mode' via a remote command
- A command may also need to be added to the protocol file
- A 'Local mode' button exists on the physical unit, but it's unknown whether or not 'Remote mode' is immediately entered on receiving a command (as other devices do) - IS will check current behaviour and report back.  If this is the case, the IOC will need to be stopped to be able to operate the unit locally, unless communications can be stopped temporarily somehow.

**Comment by ThomasLohnert** [comment]
Device does not provide remote/local control, you can just enable or disable the keyboard on the device. i.e. Remote control is always active

**Comment by davidkeymer** [comment]
Suggestion to use the disable field (`.SDIS`) to prevent scanning of the appropriate record.  This would stop the IOC communicating and prevent the device going into Local mode.

**Comment by FreddieAkeroyd** [comment]
There is an existing `$(P)DISABLE` record that sets `.SDIS` mentioned above. So this ticket needs
```
field(SDIS, "$(P)DISABLE")
```
added to all records on 2 second SCAN - many already have this

Then something like a control mode `$(P)CMODE:SP` bo PV with  0=REMOTE 1=LOCAL that  writes directly to `$(P)DISABLE` and a `$(P)CMODE` bi PV that reads from `$(P)DISABLE`

GUI can then have a "Control Mode" readback referencing  `$(P)CMODE` and local/remote buttons to write 0 or 1 to `$(P)CMODE:SP`

**Comment by danielmaclaren** [comment]
[ibex_gui pull request ](https://github.com/ISISComputingGroup/ibex_gui/pull/1608)
[ioc pull request](https://github.com/ISISComputingGroup/EPICS-Aeroflex/pull/7)
