### ISSUE TITLE
Aeroflex Signal Generator - Remove Control to select frequency units

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7879]
As an instrument scientist, I would like the units of frequency to be fixed at MHz on the Aeroflex signal generator OPI.

Comment from IS:

> "At present the IOC allows for a choice of units for the RF Frequency. In practice, experiments can always work in ‘MHz’ (people will be thinking in these units), so this control can be removed … ‘MHz’ should be hard coded in the same way that ‘dBm’ currently is for RF level."

### Acceptance Criterion:

- Frequency units are fixed at MHz

#### Notes:

- Update `.EGU` fields of appropriate PVs

**Comment by zsoltkebel** [comment]
IOC: https://github.com/ISISComputingGroup/EPICS-Aeroflex/pull/4
IBEX gui: https://github.com/ISISComputingGroup/ibex_gui/pull/1570
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7924
