### ISSUE TITLE
Aeroflex Signal Generator - Remove Reset button

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7881]
As an instrument scientist, I would like the ‘Reset to Factory Settings’ button on the Aeroflex signal generator OPI to be removed.

Comment from IS:

> "The button ‘Reset to Factory Settings’ seems dangerous and likely has no useful application. This should be removed."

### Acceptance Criterion:

- ‘Reset to Factory Settings’ button is removed from the OPI

#### Notes:

- Suggest leaving functionality in the IOC and do not expose it in the OPI.

**Comment by davidkeymer** [comment]
This button will **definitely** need removing before the device is used in an experiment in September 2023.

**Comment by zsoltkebel** [comment]
### Pull Requests

IBEX gui: https://github.com/ISISComputingGroup/ibex_gui/pull/1571
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7925
