### ISSUE TITLE
Aeroflex Signal Generator - Remove Set button

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7882]
As an instrument scientist, I would like the 'Set' button on the Aeroflex signal generator OPI to be removed.

Comment from IS:

> "After defining a block and using ‘cset’ to set values, the values don’t propagate without pushing the ‘set’ button. Preference would be for immediate action. As an aside, it appears to be quite difficult to push the ‘set’ button from a script."

### Acceptance Criterion:

- 'Set' button is removed in favour of accepting values when CR/Enter is pressed in setpoint box

#### Notes:

- The requested behaviour is the default for all other OPIs.  Suspect this is a carryover from translating the VI to an IOC&OPI as having a 'Set' button is the SECI method

**Comment by esmith1729** [comment]
# Pull Requests:

- https://github.com/ISISComputingGroup/EPICS-Aeroflex/pull/5
- https://github.com/ISISComputingGroup/ibex_gui/pull/1574

# Release Notes: 

- https://github.com/ISISComputingGroup/IBEX/pull/7928
