### ISSUE TITLE
Aeroflex Signal Generator - Test IOC and OPI with alternative models

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7883]
As an instrument scientist, I would like the Aeroflex signal generator OPI to be compatible with other similar makes and models.

Comment from IS:

> "At present the IOC appears to allow for two different signal generator models. In fact we have a few more that are used interchangeably for experiments. I will test the IOC with our remaining units (I imagine the command sets are very similar) and report back my experience … could be control for some additional models will need to be added to the IOC."

### Acceptance Criteria:

- IOC and OPI are tested with alternative models of signal generator
- Additional tickets are created as necessary should problems be found

#### Notes:

- Manufacturer has changed hands several times and units have been rebadged.  Some units also have different specifications.
- Display make and model on OPI as read from device (e.g. output of `*IDN?` SCPI command) - if possible, create additional ticket for this
- Physical units can be set up by ISs for testing

**Comment by davidkeymer** [comment]
This would be best started in the August sprint due to availability of equipment, beamlines and scientists.

**Comment by ThomasLohnert** [comment]
Can be controlled via VI in case this is not done in time for September

**Comment by FreddieAkeroyd** [comment]
This is related to #8015 - we need to get all the aeroflex together and make sure we are consistemt. I forget how many models we have now as i think one of them broke

**Comment by FreddieAkeroyd** [comment]
Moved work to #8015
