### ISSUE TITLE
DG645 Delay Generator - Add Local and Remote control buttons

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7884]
As an instrument scientist, I would like buttons to select 'Local' and 'Remote' control modes on the DG645 OPI.

### Acceptance Criteria:

- Local and Remote modes are selectable remotely
- Display of current mode on OPI
- If possible, add ability to temporarily halt IOC communications (see notes)

#### Notes:

- Currently, the device will immediately go into remote mode on receiving a command and therefore prevents any local control.  This means that the IOC needs to be stopped to configure the device locally (which is often the case).

**Comment by FreddieAkeroyd** [comment]
Done in #7893
