### ISSUE TITLE
DG645 Delay Generator - Add units to Readback Delay

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7887]
As an instrument scientist, I would like units to be visible on a block created from the readback of a delay on the DG645 OPI.

### Acceptance Criterion:

- Units are added to the readback of all delay values

#### Notes:

- Units are selectable, so `.EGU` field requires updating on change

**Comment by will2201** [comment]
**Note for review:** #1604 can be merged first. This should make the real OPI changes in #1605 more clear.
