### ISSUE TITLE
DG645 Delay Generator - Correct function to Load and Save configurations

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7888]
As an instrument scientist, I would like a function to load and save configurations to numbered memory locations on the DG645 OPI.

- Use case 1:  IS configures DG645 _locally_ and saves to memory, then recalls settings from this location _remotely_
- Use case 2:  IS modifies DG645 configuration _remotely_, then saves settings to memory location

### Acceptance Criteria:

- Configurations can be remotely loaded and saved to _any_ memory location
- PV is created and displayed on OPI to store last restored memory location (e.g. initialise to -1)

#### Notes:

- Remove/hide current controls for saving configurations (looks like reused EDM panel?) as does not meet requirements
- There are 10 locations in which configurations can be saved (0-9)
- Future requirement to save configuration to disk to enable new unit(s) to be set up quickly (new separate ticket required)

**Comment by FreddieAkeroyd** [comment]
keywords to use in Db are `SAVE` and `RECALL` as per 
https://github.com/ISISComputingGroup/EPICS-delaygen/blob/master/delaygenApp/src/drvAsynDG645.cpp

**Comment by FreddieAkeroyd** [comment]
Emulator support was added in #7893 - this also has a few OPI changes so you may want to branch off this instead of master to avoid later conflicts

**Comment by esmith1729** [comment]
# Pull Requests:

- https://github.com/ISISComputingGroup/ibex_gui/pull/1584
- https://github.com/ISISComputingGroup/EPICS-DG645/pull/8

These Pull requests to delaygen and ibex_gui are necessary to review changes:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/801
- https://github.com/ISISComputingGroup/ibex_gui/pull/1581


# To Test:

- Do all the appropriate pulls, etc.
- Connect directly to the DG645 via IBEX, without DEV or RECSIM (get the COM port etc. from NPort admin)
- Use the OPI, change a few settings to delay, and then pick a save slot other than 0, and save those settings. 
- Select 0 from the drop down, and click Load, and wait for the IOC to restart. 0 Should load device defaults, which should be 0 in all delay fields. 
- Load from the slot you had saved to before, and after the IOC restarts, ensure that your settings have loaded as they were before.
