### ISSUE TITLE
DG645 Delay Generator - Correct Plot Displays on OPI [Timebox: 1.5d]

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7889]
As an instrument scientist, if provided, I would like the plots on the DG645 OPI to be accurate and useful.

These are not strictly required, so if the correction is not too complicated, implement.  Otherwise remove/hide plots entirely.

Comment from IS:

> "The ‘Plots’ could be very useful to show a pulse sequence; however, at present they are often wrong and are sometimes nonsense..."

### Acceptance Criterion:

- Plots display correctly **_or_** are removed/hidden

#### Notes:

- Possibly related to calculation of 'Width' covered by another ticket

**Comment by ThomasLohnert** [comment]
Talk to IS to understand what is actually wrong with the plots

**Comment by zsoltkebel** [comment]
# PRs

- https://github.com/ISISComputingGroup/ibex_gui/pull/1596
