### ISSUE TITLE
DG645 Delay Generator - Correct Width display on OPI [Timebox 1.5D]

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7890]
As an instrument scientist, if shown, I would like the display of the widths readback on the DG645 OPI to be accurate and representative.

These are not strictly required, so if the correction is not too complicated, implement.  Otherwise remove/hide values entirely.

### Acceptance Criterion:

- Widths display correctly **_or_** are removed/hidden

#### Notes:

- Related to display of plots covered by another ticket
- This may need some investigation into the IOC `CALC` records due to selectable width units

**Comment by zsoltkebel** [comment]
- https://github.com/ISISComputingGroup/EPICS-DG645/tree/Ticket7890_correct_width
