### ISSUE TITLE
DG645 Delay Generator - Investigate and Correct inability to reliably enter values on OPI [TIMEBOX: 1.5 days]

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7891]
As an instrument scientist, I would like values entered into the DG645 OPI to work reliably and consistently.

Comment from IS:

> "I’m unable to reliably enter values in the various boxes to set delays, sometimes they’re accepted and work, but more often values either disappear or result in a contradictory outcome; sometimes values are accepted and actioned with incomplete information, such as assuming a channel link, which could be risky if the equipment is being used to time high power apparatus."

### Acceptance Criteria:

- Values can be entered into the various boxes consistently and reliably
- A check for valid values of the 'Channel Link', 'Delay' and 'Units' must be present before writing to the device

#### Notes:

- OPI scripts may be interfering with inputting values

**Comment by zsoltkebel** [comment]
Above mention was accidental, PR is linked to another ticket.
