### ISSUE TITLE
DG645 Delay Generator - Label readback delays on OPI

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7892]
As an instrument scientist, I would like readback of the channels on the DG645 OPI to be labelled.

### Acceptance Criterion:

- Readback channels are labelled correspondingly

#### Notes:

- At present, it is not obvious that the channel readback boxes on the right of the OPI correspond to the settings on the left.  Labelling would be sufficient.

**Comment by esmith1729** [comment]
# Pull Request: 

- https://github.com/ISISComputingGroup/ibex_gui/pull/1603

# Release Notes: 

- https://github.com/ISISComputingGroup/IBEX/pull/8005
