### ISSUE TITLE
DG645 Delay Generator - Populate setpoint boxes on OPI with values read from device

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7893]
As an instrument scientist, I would like the settings boxes on the DG645 OPI to reflect the hardware when the IOC starts, rather than being blank.

Comment from IS:

> "The interface is frustrating to use – when the IOC starts it would be helpful if it populated all the entry boxes with lines, values and units read back from the equipment, rather than clearing everything."

### Acceptance Criterion:

- Add setpoints to autosave

**Comment by LilithCole** [comment]
Make sure they are in the autosave, this is something that we cannot do.

**Comment by zsoltkebel** [comment]
### PRs
- https://github.com/ISISComputingGroup/EPICS-DG645/pull/7
- https://github.com/ISISComputingGroup/IBEX/pull/7937

**Comment by FreddieAkeroyd** [comment]
The community driver did already restore values from device on startup, issue was that the additional PV later we had added did not take advantage of this. Now adjusted PVs so this can happen without needing to use autosave.

PRs

https://github.com/ISISComputingGroup/EPICS-delaygen/pull/2
https://github.com/ISISComputingGroup/EPICS-ioc/pull/801
https://github.com/ISISComputingGroup/ibex_gui/pull/1581
https://github.com/ISISComputingGroup/EPICS-DG645/pull/7
https://github.com/ISISComputingGroup/IBEX/pull/7937

**Comment by FreddieAkeroyd** [comment]
There is now a DG645 in office that we can do some testing with
