### ISSUE TITLE
DG645 Delay Generator - Remove Reset to Factory Settings button on OPI

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7894]
As an instrument scientist, I would like the ‘Reset to Factory Settings’ button on the DG645 OPI to be removed as it could potentially destroy an experiment.

Comment from IS:

> "The ‘Reset to Factory Settings’ button is not needed and appears to be a very good way of destroying your experiment! This kind of thing shouldn’t be done remotely."

### Acceptance Criterion:

- The ‘Reset to Factory Settings’ button is removed from the OPI

#### Notes:

- Keep function in IOC, but remove from OPI

**Comment by esmith1729** [comment]
This is removed already on current master branch. Functionality has been included into the Save/Load configurations settings. Loading the 0 slot is equivalent to resetting to factory settings.
