### ISSUE TITLE
Pydev: Investigate a possible solution to fix autocomplete [Timebox: 3.5 days]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7898]
As a developer/user/instrument scientist, I would like to  be able to make use of pydevs autocomplete function when using the scripting console in IBEX. Currently, we have disabled it completely to avoid the bug described in #7604, however this is not a good permanent solution since this is a major usability feature which speeds up user interactions considerably and protects against wrong inputs. We should find a proper fix so we can restore this functionality for all people who use the IBEX scripting console.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Autocomplete is enabled in the pydev console embedded in IBEX
- [ ] Running autocomplete on a function call does not execute the function as per #7604

### Extra Information
- This bug originates in the Pydev itself. We have had an investigation to try and the pydev release in which the bug originated. (see #7850) it appears the bug has been present in some form as far back as we are able to check however the unintended behaviour has become more egregious between release 5.2 and 6.0 as it now executes the function continuously instead of just once.
- As https://github.com/ISISComputingGroup/IBEX/issues/7850#issuecomment-1617882780 bug seems to occur in script console but not in editor of standalone pydev

Possible approaches:
1. Fix in our existing PyDev fork and submit PR to main Pydev repository
1. Raise a bug report to PyDev developers and let them fix it
1. Find some kind of workaround?

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
the culprit is `AUTOCOMPLETE_ON_DOT` - this runs the function. Zsolt and I are just looking to see if we can change the behaviour for this,

**Comment by rerpha** [comment]
btw, we can track issues at https://www.brainwy.com/tracker/PyDev/#

**Comment by rerpha** [comment]
we've spent a day looking into this, commenting various things out, but i can't seem to find out exactly where is causing it - tempted to revert our change and set the toggles back so we have autocompletion as I think really it's just an edge case. 1245 has been created for a fix, so perhaps we should just wait until the next dependency update for a fix?

**Comment by fabioz** [comment]
Just as a note from PyDev, what happens is that when the user adds the `.` there, it changes the document due to the content printed and then because the document changed it re-requests the completion based on the new document in the interactive console.

There are 2 things to fix:
1. Hide the content assist when the interactive console appends content from the output.
2. Add an option so that when something is a call() it won't be code-completed. This should be optional because it's not always the case that you don want it. For instance, if it was something as: `MyClass().`, users do expect that to complete...

**Comment by rerpha** [comment]
Plan of action for this ticket is: 

revert the change on our fork, build and put back on our p2 site then point the gui to it
create batch script to enable/disable it if needed
make another ticket to fix the issue in pydev and get rid of the bat files

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/Pydev/pull/7 - have put this on p2 site as `PyDev\` 

The difficulty with the script to enable/disable is you either need to 
- copy in a jar which has AC disabled 
- edit the file in the jar - this isn't a good idea
