### ISSUE TITLE
All instruments: Truncate Databases

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7906]
As a developer or system administrator, I would like the disk space on the control machines to be sufficient for the instruments to run and collect data.

### Acceptance Criteria
- Disk space is freed on the machines listed below

#### Notes
- Instructions [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space)
- Machines in list are sorted by priority, highest at top (based on `critical` and `warning` status of Nagios check)
- Log files will be moved by a central script on the maintenance day or at a later date

### TS1 
- EMU 
  - [x] Started
  - [x] Completed
- IRIS_SETUP
  - [x] Started
  - [x] Completed
- TOSCA
  - [x] Started
  - [x] Completed
- HIFI-CRYOMAG
  - [x] Started
  - [x] Completed 
- MARI
  - [x] Started
  - [x] Completed
- OSIRIS
  - [x] Started
  - [x] Completed
 
### TS2 
- SANS2D
  - [x] Started
  - [x] Completed

**Comment by zsoltkebel** [comment]
Checked Nagios and everything seems fine. There are no messages about `\instrument\var\mysql\` in critical.
