### ISSUE TITLE
Instrument Scripts: Jenkins job that checks for divergence 

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7911]
As a user of the InstrumentScripts / Scans library, I would like my scripts repository to be brought up to date frequently. At the moment, we do this manually on a case-by-case basis as appropriate, we should put a more well defined process into place as discussed here: https://github.com/ISISComputingGroup/IBEX/issues/7626#issuecomment-1628704391.

One part of this process is having an automated central service that checks whether the instruments have made any local changes that need to be integrated into master. This ticket is for writing the jenkins job that pulls the latest changes from the repository and checks all instrument branches against the last known "up to date" version of the branch.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] We have a jenkins job that pulls changes in the InstrumentScripts repository and checks the latest commits on a number of given branches (likely named `NDX<INSTRUMENT>` against a previous version

### Extra Information
- Depends on: https://github.com/ISISComputingGroup/IBEX/issues/7915

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by LilithCole** [comment]
currently looks like it isn't tracking added files, also printing memory locations instead of file names
