### ISSUE TITLE
GUI: make "show title and users in dataweb" option more visible

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7921]
As a user I would like my "show title and users in dataweb" button to be more obviously placed. currently it is in the DAE tab next to the title, but we have some empty space in the dashboard where it could also be placed. if this isn't possible, a right click menu for it in the dashboard might be nice too. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] A user can view/change whether their users and title names are shown in the dataweb from the dashboard as well as the DAE perspective. 

### Extra Information
_Why it is needed?_

_Where required files/links are_

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
may be a case of just changing https://github.com/ISISComputingGroup/JSON_bourne/blob/master/external_webpage/instrument_information_collator.py#L98C22-L98C33 but I didn't want to hotfix as I know there are some http/https things going on with json bourne atm!

**Comment by danielmaclaren** [comment]
[Link to pull request](https://github.com/ISISComputingGroup/ibex_gui/pull/1583)

**Comment by ThomasLohnert** [comment]
- Functionality is sound!
- Some minor layout changes needed, explanation on PR
- Missing [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)
