### ISSUE TITLE
web dashboard/DAE: show "disabled" rather than "unavailable" when users and title hidden

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7923]
As a user I would like the web dashboard to be more helpful and say "disabled" or "hidden" (and if possible, a tooltip on how to show/hide it)

Curently if you go into the GUI and hide the users/title from the web dashboard it then just says "Unavailable" on the web dashboard with no explanation as to why they are unavailable.  

### Acceptance criteria
- [ ] web dashboard shows either "disabled" or "hidden" (i prefer the latter) if the users and title are hidden in the DAE perspective's run summary tab

**Comment by rerpha** [comment]
may be a case of just changing https://github.com/ISISComputingGroup/JSON_bourne/blob/master/external_webpage/instrument_information_collator.py#L98C22-L98C33 but I didn't want to hotfix as I know there are some http/https things going on with json bourne atm!

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#developmenttesting for instructions on spinning up your own json_bourne webserver

**Comment by FreddieAkeroyd** [comment]
All changes to json bourne are now pushed to git, so you should be able to deploy a new master (or a branch so long as you have merged recent master)

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/JSON_bourne/pull/57 5 min change, should really be a flash review

**Comment by rerpha** [comment]
ps softmat has users hidden for testing/reviewing
