### ISSUE TITLE
Script Generator: Behaviour on Script Definition Repo Updates

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7932]
As a Muon Scientist, I would like to prevent users from accidentally modifying the existing script definitions. At the moment, when there is a discrepancy between the local and remote repository, the script generator displays the following message:

![image](https://github.com/ISISComputingGroup/IBEX/assets/18398579/33cab1cd-4d5c-40b8-b647-0e7a7d6b2fc6)

The Muon scientists do not want to give users the option to update the script repository as this may lead to unexpected / undesired consequences. Instead they just want to prompt them to notify their local contact to update the script definitions at their earliest convenience.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] When updates are available in the script definitions repository, do not give users the option to automatically update, but just prompt them to notify their local contact.

### Extra Information
Muon group has assigned "crucial" priority to this change.

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by esmith1729** [comment]
# Pull Request:

- https://github.com/ISISComputingGroup/ibex_gui/pull/1591


# Release Notes: 

- https://github.com/ISISComputingGroup/IBEX/pull/7974
