### ISSUE TITLE
Script Generator: UI Tweaks for Muons

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7934]
As a Muon scientist/user, I would like the script generator view to be clearly legible. I think this has partly been addressed by https://github.com/ISISComputingGroup/IBEX/issues/7843, however there were some specific changes the Muon group have requested that may not be included yet - see acceptance criteria.

### Acceptance Criteria
_What is the acceptance criteria?_
- [x] Visually group related buttons together
- [ ] Increase button text size
- [x] Change wording from "Generate" to "Save"
- [x] Maximise vertical space given to actions table. To this end, consider moving buttons to side of script generator rather than underneath.

### Extra Information
- Muon group has assigned "important" priority to this issue.
- It might be worth creating a mockup of the layout for circulation among muon group before implementing the design in order to avoid needless iterations.

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by zsoltkebel** [comment]
## PR

- https://github.com/ISISComputingGroup/ibex_gui/pull/1637/files
