### ISSUE TITLE
Device Generator: produces wrong branch reference in .gitmodules in EPICS-top

### ISSUE THREAD

**Issue by zsoltkebel** [ISISComputingGroup/IBEX#7935]
## Issue

On newly created submodules we realised that the generator puts `refs/head/main` as branch reference instead of the correct `main`.

![image](https://github.com/ISISComputingGroup/IBEX/assets/25386639/9fe86c14-ebb0-42b8-a85f-f0e0455c539a)

We saw this issue with the new IOCs of [Meas 905](https://github.com/ISISComputingGroup/IBEX/issues/6041) and [Pace 5000](https://github.com/ISISComputingGroup/IBEX/issues/6044).

You can see the correct format around here: https://github.com/ISISComputingGroup/EPICS/blob/a01672b08ce4f38809aa843476bf7209a3c6c5c7/.gitmodules#L746

## Get started

Probably look around somewhere here to investigate: https://github.com/ISISComputingGroup/IBEX_device_generator/blob/22331cb0549a3e729179262a055472530a1ac3fe/utils/git_utils.py#L155C49-L155C49

## Acceptance criteria

- [ ] The script generator adds the correct branch name when run to generate a new device submodule.

## How to Test

Probably by creating a new dummy device and seeing the format of the .gitmodules in EPICS-top

**Comment by rerpha** [comment]
after _extensive_ debugging, Evan and I found that this is the cause: https://github.com/ISISComputingGroup/IBEX_device_generator/blob/master/utils/git_utils.py#L157 

the annoying thing about this is it's a call to `gitpython` itself, which doesn't allow for any sort of method to disable the remote prefix (ie the `/refs/heads/` part) so we're having to call `subprocess.run()` instead. We have added a comment for this in the code as well.

**Comment by esmith1729** [comment]
# Pull Request: 

- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/31

# To test: 

- create a dummy device, and check that the .gitmodules file has the correct "branch" (should be just "main) in Instrument/Apps/EPICS
