### ISSUE TITLE
DAE: change_monitor from genie python not reflected in acqusition tab

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7944]
A `change_monitor` from genie python works and is displayed in the run information gui tab, but not in the data acquisition tab where values are set. We had a similar issue with wiring tables that was fixed, maybe a data binding issue? Maybe some items such as the monitor spectrum number got missed?

## Acceptance Criteria

Changing monitor number from genie python is reflected in GUI experiment setup page
 
## To test

* With old client run e.g. `g.change_monior(12, 1000, 2000)` - value will not change in experiment details panel, but will in run information panel
* With new client monitor number should update in both places

**Comment by FreddieAkeroyd** [comment]
I think previous fix for wiring tables was in https://github.com/ISISComputingGroup/ibex_gui/pull/1419

**Comment by zsoltkebel** [comment]
# PRs

- https://github.com/ISISComputingGroup/ibex_gui/pull/1645
- - https://github.com/ISISComputingGroup/ibex_gui/pull/1589

**Comment by zsoltkebel** [comment]
Needs someone else's review
