### ISSUE TITLE
Upgrade script: call moxa db setup script

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7948]
As #7720 is now merged, we need to call the sql script which sets up the database which contains the ip addresses, com port numbers etc which is updated by and read from the dabatase server which presents the com port mappings as PVs. 

We need to call https://github.com/ISISComputingGroup/EPICS/blob/master/SystemSetup/moxas_mysql_schema.txt as done by https://github.com/ISISComputingGroup/EPICS/blob/master/SystemSetup/config_mysql.bat#L35 (don't call this whole script in the upgrade step as it'll wipe the database!) 

Upgrade scripts: https://github.com/ISISComputingGroup/EPICS-upgrade 

### Acceptance criteria
- [ ] When updating from <insert version here> to the latest version of IBEX (containing #7720) the database for moxa details is created.

**Comment by FreddieAkeroyd** [comment]
After https://github.com/ISISComputingGroup/EPICS-upgrade/pull/75 is merged it just need to use  `run_sql_file` in the upgrade script step
