### ISSUE TITLE
W/C: 21st August 2023: Deploy the release as appropriate

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7950]
Deploy a full release to the following instruments:

EMU
- [x] In Progress
- [x] Complete

MUSR
- [x] In Progress
- [x] Complete

MUONFE (machine name moved from NDEMUONFE to NDXMUONFE)
- [x] In Progress
- [x] Complete

RIKENFE
- [x] In Progress
- [x] Complete

HIFI_CRYOMAG
- [x] In Progress
- [x] Complete

OSIRIS
- [x] In Progress
- [x] Complete

IRIS
- [x] In Progress
- [x] Complete

IRIS_SETUP
- [x] In Progress
- [x] Complete

TOSCA
- [x] In Progress
- [x] Complete

VESUVIO
- [x] In Progress
- [x] Complete

ALF
- [x] In Progress
- [x] Complete

LET
- [x] In Progress
- [x] Complete

MAPS
- [x] In Progress
- [x] Complete

MARI
- [x] In Progress
- [x] Complete

MERLIN
- [x] In Progress
- [x] Complete

NIMROD
- [x] In Progress
- [x] Complete

SANDALS
- [x] In Progress
- [x] Complete

SELAB
- [x] In Progress
- [x] Complete

SOFTMAT
- [x] In Progress
- [x] Complete

DCLAB
- [x] In Progress
- [x] Complete

DETMON (20230830 - unpingable)
- [ ] In Progress
- [ ] Complete

PEARL (upgrade existing unused clone install)
- [x] In Progress
- [x] Complete

PEARL_SETUP (new install)
- [x] In Progress
- [x] Complete

INTER (leave to JH)
- [x] In Progress
- [x] Complete

**Comment by KathrynBaker** [comment]
Note that deploys may be held up if the release isn't ready and in the need for certain systems to be available, however, this would be best started during this week as the following week is a short one

**Comment by LilithCole** [comment]
I could be able to assist with a couple in the background while rewriting docs

**Comment by KathrynBaker** [comment]
As DETMON is unavailable and is not a direct instrument and there are no updates to their IOCs, I'm going to push that to the next deploy, so there will be an entry in the PI board in the next PI to include DETMON in the next deploy. It won't be a ticket as there will be the Group A deploy anyway in need of a ticket.
