### ISSUE TITLE
Stanford PS300 series power supplies

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#7951]
There is an exisiting community IOC now imported to  https://github.com/ISISComputingGroup/EPICS-SRS_PS300 - we should use this to replace the lvdcom implementation at https://github.com/ISISComputingGroup/EPICS-Stanford_PS350 - see #6213 for other features that may be added. There is an IOC a `STPS350` ioc using lvdcom that could be changed, or a new IOC added

##Acceptance Criteria

* IOC created referring to support module
* review support module and create aliases or otherwise to fit ISIS naming conventions
*  add emulator and tests
* create an OPI

**Comment by davidkeymer** [comment]
Added missing [PR](https://github.com/ISISComputingGroup/EPICS/pull/350) for submodule.
