### ISSUE TITLE
Beckhoff/TwinCAT: Add INTER vars and use templated db files for ADS variables

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7955]
The INTER tank's new beckhoff will have a set of PVs which we need to read from and write to that are on top of the usual beckhoff motion variables. 

There is also lot of boilerplate in both the motorextensions and ioc area for the TC IOC, we should utilise templating for this as it'd avoid typos too. 

### Acceptance criteria
- Substitution file is created for a read-only ADS pv
- Substitution file is created for a write-only ADS pv
- motorextensions uses these substitution files and uses templates for existing instruments
- ioc\master\TC uses these sub files for the common motor fields that run on beckhoffs
- INTER tank PVs are added using the above

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/55
 
- I deliberately left out the sans2d ones as they are per-axis and already use a substitutions file


To review:
- checkout master on motorextensions and `make`, copy the `db` folder at the top-level as this is generated and rename it to db-old. Then check out this branch and diff the sandals sample changer, larmor bench, chipir filter set and sans2d guides db files. they should contain the same PVs. 
- Compare the below screenshot of INTER variables to the inter_tank.substitutions file


![image](https://github.com/ISISComputingGroup/IBEX/assets/14823767/d41aea15-155b-46af-8fcc-165ae05968fd)

**Comment by zsoltkebel** [comment]
sandals sample db seems to be missing the EGU field in the new build

**Comment by zsoltkebel** [comment]
In the single_axis_tc.db `$(P)ASTAXES_$(AXIS_NUM):STCONTROL-FJOGVELOCITY:RBV` is missing in the new db file compared to the old. Also `$(P)AXIS_NUM` is missing, not sure if that is intentional?

**Comment by zsoltkebel** [comment]
All corrected.
