### ISSUE TITLE
OPIs: Checking colour values match colour definitions

### ISSUE THREAD

**Issue by will2201** [ISISComputingGroup/IBEX#7961]
As a: developer, I would like to make sure all colours used in the OPI match the defined RGB values stated in isis_colours.def file

### Acceptance Criteria
_What is the acceptance criteria?_
- [x] If an OPI does not have correct RGB attributes in a color tag according to the definition, display an error line when running check_opi_format.py.
- [x] If an OPI does not have correct font attributes in a opifont.name tag according to the definition, display an error line when running check_opi_format.py.
- [x] We have a script that will update OPI color and opifont.name tags to conform to definitions.

### Extra Information
_Why it is needed?_
We want colours to look consistent, even if  isis_colours.def is not able to be loaded.
We want any changes we make to a definition of a colour to be reflected. (There may be a separate ticket to make the GUI aware of isis_colours.def )

_Where required files/links are_
Script that checks the OPI: C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\check_opi_format.py
ISIS colour RGB definitions: C:\Instrument\Apps\EPICS\CSS\master\Share\isis_colours.def
ISIS font definitions: C:\Instrument\Apps\EPICS\CSS\master\Share\isis_fonts.def
#### New files
1. C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\check_OPI_format_utils\definition_checker.py
2. C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis\update_values.py

## How to Test
_verbose instructions for reviewer to test changes_
#### Testing RGB and font checks
1. In a <color> tag in one of the OPI XML files, change at least one of the "red", "green" or "blue" attributes where the "name" attribute corresponds to a colour defined in the isis_colours.def file.
3. In an <opifont.name> tag in the same OPI XML file, change at least one of the "fontName", "height" or "style" attributes where the text of the tag corresponds to a font defined in the isis_fonts.def file. 
4. Run ```python3 check_opi_format.py -file <opi file name>```. Errors lines should be output for the fonts and colours that fail to match defined values. 
Note: Using the ```-file``` argument is to stop the script running on every OPI. The script should work without the argument, it will just make it more difficult to find the intentionally created errors. 

#### Testing update_values.py
1. Run ```python3 update_values.py -file <opi file name> -attribute <font/color>```. The attributes that were originally changed to be incorrect should now be changed back and conform to the definition given in the definition file.

**Comment by will2201** [comment]
Checks now include fonts, and a separate script has been written to update any incorrect font or color tags with correct attribute values, according to isis_colours.def, or isis_fonts.def

**Comment by will2201** [comment]
Checks now include fonts, and a separate script has been written to update any incorrect font or color tags with correct attribute values, according to isis_colours.def, or isis_fonts.def

**Comment by will2201** [comment]
Checks now include fonts, and a separate script has been written to update any incorrect font or color tags with correct attribute values, according to isis_colours.def, or isis_fonts.def

**Comment by will2201** [comment]
PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1594

**Comment by zsoltkebel** [comment]
I added some comments into the PR here: https://github.com/ISISComputingGroup/ibex_gui/pull/1594#pullrequestreview-1619670669

**Comment by zsoltkebel** [comment]
# PRs

- https://github.com/ISISComputingGroup/ibex_gui/pull/1600
- https://github.com/ISISComputingGroup/IBEX/pull/7998
