### ISSUE TITLE
Test DHP30330 IOC and OPI with real device

### ISSUE THREAD

**Issue by zsoltkebel** [ISISComputingGroup/IBEX#7966]
The IOC should be tested with real device to see for example if the amount of whitespaces matter or not in the comm protocol.
 
This ticket is related to https://github.com/ISISComputingGroup/IBEX/issues/6042

**Comment by rerpha** [comment]
screenshot of sorensen talking OK with ibex: 
![image](https://github.com/ISISComputingGroup/IBEX/assets/14823767/7b9e648d-7611-4223-9daa-a6edadbd565f)

https://github.com/ISISComputingGroup/EPICS-Dhp30330/pull/2
https://github.com/ISISComputingGroup/IBEX/wiki
release notes to do
