### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7976]
As someone supporting IBEX I want to make sure the dependencies are up to date, as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates.

## Acceptance Criteria
- [x] Dependency upgrade steps have been undertaken
- [x] Dependencies are listed in the upcoming release notes
- [x] Rough test of IBEX undertaken to verify basic function of the system

**Comment by will2201** [comment]
PRs for this ticket:
[ibex_gui](https://github.com/ISISComputingGroup/ibex_gui/pull/1659)
[genie_python](https://github.com/ISISComputingGroup/genie_python/pull/397)
[pydev](https://github.com/ISISComputingGroup/Pydev/pull/6)
[isis_css_top](https://github.com/ISISComputingGroup/isis_css_top/pull/17)
[ActiveMQ](https://github.com/ISISComputingGroup/EPICS-ActiveMQ/pull/15)
[IOCLogServer](https://github.com/ISISComputingGroup/EPICS-IocLogServer/pull/31)
[Nicos](https://github.com/ISISComputingGroup/nicos/pull/9)

**Comment by FreddieAkeroyd** [comment]
Have temporarily moved to impeded, but may be better to leave in review with a note, but will discuss.

We will be doing a release soon so probably do not want to merge these until after that, so we could do the review and just hold off on the merge, or leave it all until after the release.

**Comment by FreddieAkeroyd** [comment]
repointed to work left for testing etc
