### ISSUE TITLE
Instrument Demos August/September 2023

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7977]
As a user of IBEX I would like to be kept abreast of new features of IBEX. Given that we have just done a release (https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/Release-Notes-v13.0.1.md) we should demo new features. 

## Acceptance Criteria
- [x] Script a demo and generate a slide deck to ensure that new features are detailed from release 11.0.0 to release 13.0.1
- [x] Record the general demo and upload it
- [x] Assign teams to appropriate groups to demo on the https://github.com/ISISComputingGroup/IBEX/wiki/Timetable-for-Instrument-Demos page (this has been done for August 2023)

## Notes
- No demos were done for version 12.0.1, so those items need to be included as well for this demo
- This is the first time attempting a recording, so where to keep it needs to be confirmed and will be delayed until after the demos need to be done due to time constraints

**Comment by rerpha** [comment]
Looks good, times just need to be organised by the relevant demo'ers
