### ISSUE TITLE
INTER: show logic state in IBEX GUI, forward plc axis description to .DESC

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7979]
As an INTER scientist I would like to see:

- [x] A description of an axis which matches what the PLC says in the table of motors
- [x] the logic state that the INTER beckhoff is in
- [x] the logic state that the INTER beckhoff last errored in

### Acceptance criteria
- [x] Above fields are populated and shown in IBEX

**Comment by rerpha** [comment]
covers #6860

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-motorExtensions/compare/master...flash_add_logic_state_for_inter 
https://github.com/ISISComputingGroup/EPICS-ioc/compare/inter_additions?expand=1

**Comment by rerpha** [comment]
I can't get cs-studio to open and behave. the bit left of this ticket is to show the 2 logic state pvs on the existing INTER tank OPI

**Comment by rerpha** [comment]
This is now patched on NDXINTER, so can VNC in to see the OPI, however the beckhoff will be on and off for the next few days while we're commissioning. Will update this comment with a screenshot or something for the reviewer to confirm that DESC forwarding is working fine

**Comment by KathrynBaker** [comment]
As per a discussion relating to the difficulties in reviewing it, progressing it as completed
