### ISSUE TITLE
Upgrade script: add option to use previously selected Galil driver

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7982]
As a developer I would like the upgrade scripts to be more clever about the galil drivers and provide an option to use whatever was previously selected, or just print what was last used before confirming the step. It's a bit annoying to have to check in the backup files manually. 

### Acceptance criteria
- [ ] Upgrade script either prints out what was last used and gives the option of new/old galil driver, or if straightforward just provides a third option to use the same as last time

Additional info: 
https://github.com/ISISComputingGroup/ibex_utils/tree/master/installation_and_upgrade are where the upgrade steps. we normally run instrument_deploy.bat to roll out a new release to an instrument (more info [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#upgrading-ibex-to-the-latest-version))

if there is a file called galil-old.txt in ioc\master the old galil driver was used. you will need to check the last backup of EPICS for this as it's a previous step in the upgrade script

**Comment by FreddieAkeroyd** [comment]
There is already a check for this in the upgrade script https://github.com/ISISComputingGroup/ibex_utils/blob/a40a612c2f0f6a88bac391da3b70bb6e52cbf688/installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py#L445 but it doesn't work if the EPICS directory is removed first. Checking the last backup is not necessarily reliable as it may not exist (skipped or deleted as on a _SETUP system with smaller disk for example). We could try and check the existing EPICS and cache a value pre delete, but it may be better if we recorded information like this in the ibex settings area instead e.g. xml/json file representing a dictionary of install and options.
