### ISSUE TITLE
Upgrade script: make less slow + bad

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7987]
As a developer I would like to make the upgrade script faster and less error prone. 

A few things we have already thought of: 

- combine backup steps like "backup motor pvs", "backup block values" and "backup blockserver PVs" as well as parallellise them so they all do a caget at once
- be more clever about upgrading java/mysql if they are already the latest version - consider removing the prompt for these
- make the "backup motor PVs" try more than 8 controllers 
- do a `git status` in ibex_gui, genie_python and EPICS and print out the result BEFORE asking to back up these directories and move them to c:\data\old
- remove the "record running VIs" on instruments that are not running SECI ( might have to have an exclude/includelist centrally for this unless we can do it programmatically)

### Acceptance criteria 
- [ ] Above modifications are made to the upgrade script for instrument_deploy.bat

**Comment by davidkeymer** [comment]
The 'back up old directories' step also needs improvement.  It should check that there is sufficient local diskspace before starting the process.  Ideally it should copy any previous backups to the network share ('stage-deleted') and only keep the most recent.
Even better would be to zip the files beforehand to vastly improve copy speed over the network, as it's very low for thousands of tiny files.

**Comment by davidkeymer** [comment]
May not be strictly part of this ticket, but the 'truncate database' script also needs a little work:  It creates a backup directory which has the same name as the 'backup old directories' step of the upgrade script (e.g. 'ibex_backup_2023_01_24').  Ideally it should be named differently to avoid confusion.

**Comment by zsoltkebel** [comment]
# PRs
- https://github.com/ISISComputingGroup/ibex_utils/pull/165
