### ISSUE TITLE
GUI: Hidden perspective buttons carry over when switching instrument

### ISSUE THREAD

**Issue by will2201** [ISISComputingGroup/IBEX#7991]
## Where?
Switching from an instrument that has hidden perspective buttons carries across the hidden setting to the perspective buttons on the instrument being switched to.
## Reproducible?
Yes

### To Reproduce
- In the IBEX GUI, switch to an instrument that has some hidden perspectives (e.g. ALF) 
- Switch instrument to one that doesn't currently have the same perspectives hidden. (e.g. EMU)
- Notice that these hidden perspectives remain hidden on the instrument that has just been switched to (Compare the difference between the table in Preferences -> Select visible perspectives (Visible to Users column) to the perspective buttons that are actually visible in the GUI - there will be a mismatch.)
#### Note:
There is a "Use Local Settings" checkbox in Preferences -> Select visible perspectives. The GUI behaves as expected when this box is ticked. The bug refers to when this box is unticked and the "Visible to Users" column should be being applied but isn't.

![EMU hidden perspectives](https://github.com/ISISComputingGroup/IBEX/assets/141733136/69f2af9c-e9c7-4f3b-ae0e-c162ad95e556)

## Acceptance criteria 
- [ ] Visible perspective buttons in the GUI should always align with the relevant column of the table in Preferences -> Select visible perspectives. 

## How to Test 
No changes are made for this ticket, so no testing required. Comment explaining this decision below.

**Comment by will2201** [comment]
Further investigation has shown that this bug is reproducible only in the case that the IBEX server is not running. It is not strictly a bug because it is not possible to get the new perspective settings in this case. The solution should be to produce a pop-up box that notifies the user that the perspectives settings were unable to be obtained from the network.

**Comment by will2201** [comment]
Pop-up and warning text already exist for this in the 'select visible perspectives' window. Had planned to introduce a global pop-up on server being down but it was decided this would likely negatively impact user experience for what is arguably an edge-case. 
No changes are made for this ticket.

**Comment by esmith1729** [comment]
It appears that the decision was made to not do anything about this issue, closing this issue.
