### ISSUE TITLE
GUI: disable add beam status PV to config if blockserver is not running

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7995]
As a user I can hang the GUI for 30s or so if I try and add a block to one of the beam status PVs when my blockserver is not running. 

for device screens, we disable the option to add blocks to configs when the blockserver is down/not running, we should do the same here. 

### Acceptance criteria
- [ ] When the blockserver is not running, a user cannot attempt to add a beam status PV to their configuration

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1662 - this relies on #8155 for the helper method, so review that first
https://github.com/ISISComputingGroup/IBEX/pull/8157

**Comment by zsoltkebel** [comment]
Jack and I worked more on this so someone else should review it now.
