### ISSUE TITLE
DAE perspective: drop-downs etc are not greyed out when pointing at another instrument

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8011]
As a developer I would like the DAE controls to ALL be greyed out when looking at another instrument. 

Currently I can change drop-down values, set vetos etc. - wouldn't think this would change anything because of access control, but we should make it not look like we can change things

### acceptance criteria
- [ ] When switching to an instrument that is not my own I cannot change any of the controls in the DAE perspective
- [ ] Squish test added for this if easy, otherwise manual system test step

**Comment by danielmaclaren** [comment]
[link to pull request](https://github.com/ISISComputingGroup/ibex_gui/pull/1622)

**Comment by danielmaclaren** [comment]
- https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/141

**Comment by danielmaclaren** [comment]
- https://github.com/ISISComputingGroup/IBEX/pull/8059
