### ISSUE TITLE
[PEARL Pressure Controller]: "Advanced" Tab locked out when not in Manager Mode

### ISSUE THREAD

**Issue by esmith1729** [ISISComputingGroup/IBEX#8032]
As an instrument scientist, I do not want the options available in the "Advanced" tab of the PEARL Pressure Controller to be available when not in Manager Mode

## Where?
PEARL Pressure Controller OPI

## Acceptance criteria 
- [x] "Advanced" tab is not accessible when not in Manager Mode

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by zsoltkebel** [comment]
## PRs

-  https://github.com/ISISComputingGroup/ibex_gui/pull/1618
- https://github.com/ISISComputingGroup/IBEX/pull/8048

Instructions on how to test are in the PR discussion.
