### ISSUE TITLE
genie python: load_script looked like checking wrong script as script in wrong directory 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8033]
On VESUVIO when they tried to load a script with load_script they were getting errors repeated on screen for a previous script that really did have errors. It seems like:
- either load_script was loading the wrong file or
- load_script was still checking the old file even if not loading it

**Comment by FreddieAkeroyd** [comment]
Turns out the same script was in both `u:\scripts` and `C:\Instrument\Settings\config\NDXVESUVIO\Python\inst` and files in `inst` are re-imported, so it looked liek it was re-importing a previous script only because the file was also in the `inst` area.  Realised that when i renamed the one in `u:\scripts` and it still kept complaining!

**Comment by FreddieAkeroyd** [comment]
I guess we could think if we can improve on this, but I suspect the `inst` is  all import by design. We haven't had thi sissue before, but maybe we should be more specific on imports of files?

**Comment by isaachilly** [comment]
# PRS

[Code](https://github.com/ISISComputingGroup/genie_python/pull/390)
[ReleaseNotes](https://github.com/ISISComputingGroup/IBEX/pull/8082)
