### ISSUE TITLE
Aldn1000: Investigate Emulator Issues [TIMEBOX: 2 days]

### ISSUE THREAD

**Issue by esmith1729** [ISISComputingGroup/IBEX#8036]
## Where?
the aldn1000 emulator

## How?
System tests have been somewhat regularly failing, one of which is on the Aladdin 1000.

Some system tests, notably "test_GIVEN_pump_on_WHEN_set_pump_off_THEN_pump_paused", will sometimes fail randomly, and it appears to be an issue with the emulator of the aladdin itself, rather than the system tests. It at first was thought that the "timeout" was not long enough for this test, but having tested it up to 60 seconds, this does not appear to be the case. Settings in the "timeout" method were also changed, within channel_access.py, which is in IOCTestFramework utils, to poll the emulator less frequently (setting `time.sleep` there to 0.1 or 0.2 instead of 0.01) , to give it more time to process, but this also didn't appear to fully fix this issue. 

Currently it is thought that the core issue lies in the logic of the emulator, that it somehow gets into a state when running this test that it cannot get out of, where it will return "stopped" instead of "paused"

## Reproducible?
Sometimes. Try running the system tests, and if the "test_GIVEN_pump_on_WHEN_set_pump_off_THEN_pump_paused" fails, you will see the issue. May need to run several times, or after running in RECSIM, etc. to get it to fail.

## Acceptance criteria 
- [ ] The emulator is looked at, and the issue resolved, or further tickets are created to resolve it. 

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by esmith1729** [comment]
This has probably been solved by https://github.com/ISISComputingGroup/EPICS-Aldn1000/pull/7/

**Comment by FreddieAkeroyd** [comment]
tests now passing
