### ISSUE TITLE
genie_python: load_script check for tabs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8047]
As a user or instrument scientist i would like to be warned if my python script loaded by `load_script` contains tab characters

### Acceptance Criteria
warning message printed by `load_script` 

### notes

we already run `pylint` on a load_script, maybe an option to do this check there as PEP8 recommends spaces over tabs, otherwise we'll need to check the file ourselves.

**Comment by danielmaclaren** [comment]
[Link to pull request](https://github.com/ISISComputingGroup/genie_python/pull/391)
