### ISSUE TITLE
Instrument Hotfix Process: Update Deploy Script with Instrument Branches of EPICS

### ISSUE THREAD

**Issue by esmith1729** [ISISComputingGroup/IBEX#8057]
## Where?
As discussed here: https://github.com/ISISComputingGroup/IBEX/issues/7662, and here: https://github.com/ISISComputingGroup/IBEX/issues/8054, The deploy script for upgrading instruments needs to change to be able to check out the Instrument branches of EPICS.

## Acceptance criteria 
- [ ] Deploy script can check out correct branch on instrument
- [ ] Deploy script can then commit to the instrument branch just after the deploy has been completed.

## How to Test 
Probably use a SETUP machine that isn't in use
(**Add before making a PR**)_

**Comment by isaachilly** [comment]
## PRs

[Deploy Script](https://github.com/ISISComputingGroup/ibex_utils/pull/169)
