### ISSUE TITLE
motion setpoints: show full file path instead of just filename in device screen

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8071]
As a user of motion setpoints I would like to see the _full_ filepath of the motionsetpoints file where my positions are listed, as opposed to just the filename. 

### Acceptance criteria
- [ ] On the motion setpoints OPI(s, there are at least 2) I can see the full filepath of the motion setpoints position file in use

**Comment by rerpha** [comment]
as this would go over the 40 char limit, suggest adding another PV for the directory?

**Comment by rerpha** [comment]
its an asynoctet which looks like it still has the 40 char limit?

**Comment by FreddieAkeroyd** [comment]
You can use char waveform with asynOctet to get a longer name

**Comment by FreddieAkeroyd** [comment]
You'll also need to update the OPI to explicitly tell it "string" rather than "default" in the display format properties of the text widget, otherwise it will not know to interpret the char waveform and show numbers rather than a string

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/30
https://github.com/ISISComputingGroup/ibex_gui/pull/1629
https://github.com/ISISComputingGroup/IBEX/pull/8075/files
