### ISSUE TITLE
Instruments: truncate databases

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8085]
As a developer or system administrator, I would like the disk space on the control machines to be sufficient for the instruments to run and collect data.

### Acceptance Criteria
- [x] list of machines created
- [x] Disk space is freed on the machines listed below

#### Notes
- to get a list of current database sizes see [nagios](https://control-mon.isis.cclrc.ac.uk/nagios/cgi-bin/status.cgi?servicegroup=mysql_db&style=detail) - add all warning and critical, and then reviews the largest that are green. You can click the arrow at top of service column to sort by service name. 
- Instructions to reduce space [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space)
- Machines in list are sorted by priority, highest at top (based on `critical` and `warning` status of Nagios check)
- Log files will be moved by a central script on the maintenance day or at a later date

## Instruments

- RIKENFE
  - [x] Started
  - [x] Completed

- INES
  - [x] Started
  - [x] Completed

- TOSCA
  - [x] Started
  - [x] Completed

- HIFI-CRYOMAG
  - [x] Started
  - [x] Completed

- SANDALS
  - [x] Started
  - [x] Completed

- LET
  - [x] Started
  - [x] Completed

- EMU
  - [x] Started
  - [x] Completed

- ENGINX
  - [x] Started
  - [x] Completed

- MUSR
  - [x] Started
  - [x] Completed

**Comment by Chsudeepta** [comment]
Started truncation for HIFI-CRYOMAG. Unfortunately not able to connect to the script and also getting error when doing manually.

**Comment by davidkeymer** [comment]
Insufficient disk space on CRYOMAG machine to create local backup.  Currently moving previous backup to network drive.

**Comment by davidkeymer** [comment]
CRYOMAG - Database backup complete.  Unable to truncate.  Still needs maintenance.  Have cleared diskspace so not as urgent.

**Comment by FreddieAkeroyd** [comment]
The var disk was full on both CRYOMAG and RIKENFE, this was causing the database to malfunction and not log data properly. I have now corrected this.

**Comment by GRyall** [comment]
Was completed and carried out again since
