### ISSUE TITLE
INTER: condense tank screen into one page, use buttons rather than 1/0 toggles

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8091]
See expt ctrls inbox for suggestion of new design. 

### Acceptance criteria
- [ ] inter tank OPI is modified to match the suggestions in SC's email.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1634

**Comment by rerpha** [comment]
child of #7532

**Comment by rerpha** [comment]
pathced on NDXINTER - https://github.com/ISISComputingGroup/IBEX/wiki updated

**Comment by Chsudeepta** [comment]
Reviewed the changes. Some screen elements aren't as expected - one field is missing (Speed Limit) and three spurious fields are present (SETVELO_XXX).
