### ISSUE TITLE
genie_python (RIKENFE): Fix root cause of not being able to load PV CS:INSTLIST from genie_python [TIMEBOX: 1 day]

### ISSUE THREAD

**Issue by zsoltkebel** [ISISComputingGroup/IBEX#8099]
Behaviour only on RIKENFE

caget from console works to get `CS:INSTLIST`

However when trying from the scripting console within the gui or a standalone genie_python console it cannot access it through get_pv()

More information in Teams technical thread.

**Comment by KathrynBaker** [comment]
Timebox this to look into reproducing this in the first instance

**Comment by KathrynBaker** [comment]
The thread now has a reference to this ticket to allow searching for that number to help locate it (slightly fewer hits than anything else)

**Comment by FreddieAkeroyd** [comment]
Firewall rule for `A:\python3\python.exe` was present but disabled, re-enable and everything works.

**Comment by FreddieAkeroyd** [comment]
Added comment to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/genie_python-Troubleshooting#can-read-local-pvs-from-instrument-but-not-eg-csinstlist-or-accelerator-ones-like-beam-current

**Comment by FreddieAkeroyd** [comment]
To test - log onto rikenfe and    `g.get_pv("CS:INSTLIST")` in genie python
