### ISSUE TITLE
PEARL: set up camera

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8105]
As a PEARL scientist I have a camera I would like to use in conjuction with the alignment flange. 

The model of this camera is FLIR BFS-PGE which looks to be a network cam. 

We may be able to set up something similar to TOSCA's sample positioner camera using the `WEBCAM` IOC that @FreddieAkeroyd set up - see https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/WEBCAM and control-svcs/git/?p=instconfigs/inst.git;a=blob;f=configurations/configurations/TOSCA_standard/iocs.xml;h=f46ddf747b92298596986370aaed3c403ca37f4f;hb=refs/heads/NDXTOSCA

### Acceptance criteria
- [x] Camera is tested in office to make sure compatibility with WEBCAM 
- [x] Camera is set up on PEARL 

Note: This is an IP camera, so we probably need to decide whether it's OK to stick on the isis network or whether PEARL (if it has one?) can have it on their private network

**Comment by FreddieAkeroyd** [comment]
Is a webcam type view enough? This seems to be a  Blackfly S GigE camera and i believe ADSpinnaker https://areadetector.github.io/areaDetector/ADSpinnaker/ADSpinnaker.html may support it

**Comment by rerpha** [comment]
current branches: 
https://github.com/ISISComputingGroup/EPICS-ioc/pull/new/Ticket8105
and   https://github.com/ISISComputingGroup/EPICS-areaDetector/pull/new/Ticket8105

**Comment by rerpha** [comment]
I have submitted this upstream (https://github.com/areaDetector/ADGenICam/pull/39) 

but have also updated the adgenicam and adspinnaker components of our fork of areaDetector: https://github.com/ISISComputingGroup/EPICS-areaDetector/pull/16

ioc: https://github.com/ISISComputingGroup/EPICS-ioc/pull/823

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PEARL-Instrument-Details#note-camera

**Comment by rerpha** [comment]
Note for reviewer, camera is in the office, can be set up if needed for testing, though it is a bit fiddly

**Comment by FreddieAkeroyd** [comment]
@rerpha is the IOC specific to PEARL and needs to be called PEARLCAM? If another instrument bought the same camera model, what would be different?

**Comment by rerpha** [comment]
yes i suppose so, could call it BFLYCAM or something instead as it _should_ work for any black fly model?

**Comment by rerpha** [comment]
ok - should now be more generic and allow for any GENICAM camera, have renamed the IOC also
