### ISSUE TITLE
ibex_gui: Use IBEXButtonFactory throughout the code to create generic buttons [Timebox: 2.5D]

### ISSUE THREAD

**Issue by zsoltkebel** [ISISComputingGroup/IBEX#8106]
As a developer I would like the gui code to use the new IBEXButtonFactory to create buttons throughout. The factory was created in this ticket #7934.

### Acceptance Criteria
- [ ] All button instantiation happens through the factory methods
- [ ] New factory methods are created if needed

## How to Test

Using squish tests.

**Comment by isaachilly** [comment]
## PRs

- https://github.com/ISISComputingGroup/ibex_gui/pull/1680
- https://github.com/ISISComputingGroup/IBEX/pull/8234

## To test

1. Check a sample of the buttons work correctly.
2. Look at the builder class and suggest any much needed improvements.
