### ISSUE TITLE
MOXA view: show connection status

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8109]
The moxa view added to IBEX in #7720 is very useful to show physical mapping, but it would also be good to know which ports were actually in use e.g. host connection name or connection statistics. We have read this information for other displays via web or SNMP, need to think if this needs a moxa ioc or we can get it direct, so will update ticket later.

### Acceptance Criteria
* more details about an port are displayed to indicate it is in use or not (e.g. status, bytes sent/received) 

## How to Test
* can test on any moxa

## Notes

See ticket #7720 for background. We populate a database with details about moxa mapping in the block server process, then serve this to the GUI where they are displayed in the moxa perspective. This ticket is to add some further details to be displayed in the current moxa perspective in the client. These additional details are sligtjhly more dynamic than the fixed mapping of which moxa port -> which COM windows port e.g. com port status (up/down), baud rate, bytes sent/received on port. 

As shown below it is possible to read these via the SNMP protocol e.g. using the snmp walk command. The approach would probably be:

- locate an appropriate python SNMP module to add to the blockserver
- gather additional details from the moxa using SNMP. It might be the currrent mechanism needs adjusting slightly, for example i do not know how often it checks com port mapping but checking whether a port is up/down and bytes sent/received needs to be done reasonable regularly to be useful
- Send these additional details to the client in additiona to current details
- Adjust rendering on the client to display these
- Consider if additional view options are useful on the client e.g. to show just connected/in use moxa ports rather than all

**Comment by rerpha** [comment]
Consider that the blockserver should be doing this rather than the GUI itself, so may need to add a row to the sql db for connected

**Comment by FreddieAkeroyd** [comment]
snmp looks to get com port status (up/down), baud rate, bytes sent/received, so adding an snmp query may be useful

I downloaded the MIB `wget http://www.icir.org/fenner/mibs/extracted/RFC1317-MIB-rfc1317.txt`, saved it to `~/.snmp/mibs` and the `snmpwalk -m ALL -v1 -c public ip_addr` showed what was available. There is an IOC snmp module, but if we think blockserver is best then python has snmp modules

**Comment by FreddieAkeroyd** [comment]
might be useful to show 
```
DISMAN-EXPRESSION-MIB::sysUpTimeInstance 
SNMPv2-MIB::sysName.0 
```
at top of screen, then `.2` to `.17` of these to correspond to 16 ports of moxa
 
IF-MIB::ifType.2 = INTEGER: rs232(33)
IF-MIB::ifSpeed.2 = Gauge32: 9600
IF-MIB::ifOperStatus.2 = INTEGER: up(1)
IF-MIB::ifInOctets.2 = Counter32: 35612812
IF-MIB::ifOutOctets.2 = Counter32: 2085048881

**Comment by Chsudeepta** [comment]
Following PRs are to be reviewed for closing this task:
https://github.com/ISISComputingGroup/genie_python/pull/395
https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/383
https://github.com/ISISComputingGroup/IBEX/pull/8143
https://github.com/ISISComputingGroup/ibex_gui/pull/1656
