### ISSUE TITLE
ibex_gui: script generator use delegate pattern for view and model [Timebox: 4D]

### ISSUE THREAD

**Issue by zsoltkebel** [ISISComputingGroup/IBEX#8118]
As a developer I think the code would be more robust and maintainable if we made use of the delegate pattern in the ScriptGeneratorViewModel.java file.

The model should not need to know about the UI elements and how they exactly need to behave. Currently the view and the model have intertwined responsibility where we pass the Label and other UI widget object down to the model with the [bind](https://github.com/ISISComputingGroup/ibex_gui/blob/48567dd99ebd77a54d54b5f42c05ed02edea385e/base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java#L775C10-L775C10) method.

Instead we could consider using a ScriptGeneratorDelegate or ScriptSelectionDelegate interface that defines the methods for handling changes in the model.

Then from the view we can implement this interface and attach the view object to be the delegate for the model.

The delegate interface could be something like:
```java
interface ScriptSelectionDelegate {
    public void onHelpTextChange(ScriptGeneratorViewModel model, String newText);
    
    ...
    // any more useful behaviour defining methods that concern the ui
}
```

The model would have code such as: 
```java
class ScriptGeneratorViewModel ... {
    ScriptSelectorDelegate scriptSelectorDelegate;

    public void setScriptSelectorDelegate(ScriptSelectorDelegate delegate) {
        this.scriptSelectorDelegate = delegate;
    }

    ...
    // When something happens that UI needs to react to just call
    if (scriptSelectionDelegate != null) {
        scriptSelectionDelegate.onHelpTextChange();
    }
}
```

And finally the view would be something like:
```java
class ScriptGeneratorView extends ... implements ScriptSelectorDelegate {

    //In setup
   scriptGeneratorModel.setScriptSelectorDelegate(this);

    @Override
    public void onHelpTextChange(ScriptGeneratorViewModel model, String newText) {
        this.helpLabel.setText(newText);
        // anything else yui related
    }
}
```

### Acceptance Criteria

- [ ] the code is refactored to use this pattern
- [ ] eliminate the need to have instance variables that are java swt components within the model

### Extra Information
_Why it is needed?_

_Where required files/links are_

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by ThomasLohnert** [comment]
If not completed within timebox, create follow up ticket

**Comment by zsoltkebel** [comment]
See relevant pull request in the development section on the right panel
