### ISSUE TITLE
Add parsed console outputs to all applicable Jenkins builds/checks that filter to only error lines [Timebox: 2D]

### ISSUE THREAD

**Issue by isaachilly** [ISISComputingGroup/IBEX#8123]
As a developer I'd like to see  "console output (parsed)" added to all applicable Jenkins builds/checks that filter to just the ["faliure", "error"] lines etc? 

### Acceptance Criteria
- [ ] Create a list of applicable Jenkins builds/checks
- [ ] Parsed outputs added to each build/check in the applicable list
- [ ] When a error occurs, the line is shown in the parsed output

### Extra Information
We often spend time searching the outputs with `ctrl-f`  and inevitably the person doing stand-up scrolls just past the line everyone is reading etc. Hopefully it speed up the times we do look at the output.

## How to Test
- [ ] Locate a failed check/build and check any errors in full console output appear in the parsed console output and nothing else.

**Comment by zsoltkebel** [comment]
For reviewer:
- [ ] Remove ticket branches from jenkins jobs for: Instrument Script Checker, Config Checker.

**Comment by rerpha** [comment]
automation is being a bit weird. going to leave this open til the jenkins jobs have passed
