### ISSUE TITLE
Run Control: stuck in WAITING state unless resynced [Timebox: 1day]

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8140]
During OFFSPEC testing on 11/12/23, after a config change and save, OFFSPEC got stuck in a WAITING state despite blocks with run control being in range. After this, we tried to disable them adhoc by using the run control menu, but this didn't solve anything. A restart of the RUNCTRL_01 IOC also didn't fix this and the way to get them running again was to manually resync by doing `caput IN:OFFSPEC:CS:RC:SYNC:SP 1` from an epics terminal. 

I suspect that the issue is a race condition if blocks are using the "suspend if invalid" field set to true. The local gateway restarts which makes everything look invalid for a brief moment and I think the run control IOC never resyncs after this point. 

This is reasonably critical as if a scientist has a configuration with some blocks that have this field ticked it may be stuck in WAITING indefinitely if their script changes config for example. 

### Acceptance criteria
- [x] This issue is reproduced by saving a config with a block that suspends on invalid
- [x] if above, the issue is prevented

### Notes
This may have to be done a few times and if not reproducible on a dev machine should be tried on OFFSPEC as well. 
A possible solution is to make RUNCTRL resync on a timed interval which would make the issue less impactful as it may only be stuck in WAITING every eg. 15 seconds.

**Comment by KathrynBaker** [comment]
A resync on run control startup may be enough, and may be wise anyway, but the logic needs to be checked in relation to the blockserver

**Comment by rerpha** [comment]
Can reproduce this locally by adding a block with "suspend if invalid" enabled then trying to start a run. Interestingly, if i do a 

`caget %MYPVPREFIX%CS:SB:<newblockname>` the PV does not exist...

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-RunControl/pull/15 
https://github.com/ISISComputingGroup/IBEX/pull/8274

This solves it, and seems a good idea to have anyway as an IOC restart should then fix the DAE getting stuck in WAITING when it shouldn't be for any other reason as well.
