### ISSUE TITLE
Beckhoff: allow two instances of the TC IOC 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8160]
As a Beckhoff user I would like to be able to start using the portable beckhoffs that are potentially due to replace Mclennans. 

In the case that an instrument uses a permanent beckhoff, we may need 2 instances of TC - this ticket is to make another copy and identify + fix any potential issues like _1 being hardcoded somewhere instead of being macro'd

### Acceptance criteria
- [x] TC is modified to allow 2 instances 
- [x] this is tested with 2 beckhoffs at the same time (1 on local laptop and another using MCU_001 in R106?)

**Comment by FreddieAkeroyd** [comment]
The `inter_beckhoff_params.opi` file has a hard coded TC_01, is that OK as it is inter specific?

**Comment by rerpha** [comment]
I think so yes - should never be on 02 really
