### ISSUE TITLE
Deploy to Winter Group (w/c 22/1/24)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8164]
Deploy a full release to the following instruments:

IMAT
- [x] In Progress
- [x] Complete
- [x] TC patched

IMAT-UCBDETECT (32-bit)
- [x] In Progress
- [ ] Complete

ENGINX
- [x] In Progress
- [x] Complete

ENGINX_SETUP
- [x] In Progress
- [x] Complete

ENGINX-STRESS1 (32 bit)
- [x] In Progress
- [x] Complete

CRISP
- [x] In Progress
- [x] Complete

INTER
- [x] In Progress
- [x] Complete
- [x] TC patched

OFFSPEC
- [x] In Progress
- [x] Complete

POLREF
- [x] In Progress
- [x] Complete

SURF
- [x] In Progress
- [x] Complete
- [x] TC patched

LARMOR
- [x] In Progress
- [x] Complete
- [x] TC patched

LOQ
- [x] In Progress
- [x] Complete

SANS2D
- [x] In Progress
- [x] Complete
- [x] TC patched

ZOOM
- [x] In Progress
- [x] Complete

GEM
- [x] In Progress
- [x] Complete

HRPD
- [x] In Progress
- [x] Complete

HRPD_SETUP
- [x] In Progress
- [x] Complete

INES
- [x] In Progress
- [x] Complete

PEARL
- [x] In Progress
- [x] Complete

PEARL_SETUP
- [x] In Progress
- [x] Complete

POLARIS
- [x] In Progress
- [x] Complete

SXD
- [x] In Progress
- [x] Complete

WISH
- [x] In Progress
- [x] Complete

WISH_SETUP
- [x] In Progress
- [x] Complete

EMMA
- [x] In Progress
- [x] Complete

~CRYOLAB_R55~ (Does not exist)
- [ ] In Progress
- [ ] Complete

CRYOLAB_R80
- [x] In Progress
- [x] Complete

DETMON (Unavailable last release)
- [x] In Progress
- [x] Complete

SELAB2
- [x] In Progress
- [x] Complete

**Comment by rerpha** [comment]
TC is missing from the release so i am goingto patch onto all the instruments that need it

**Comment by rerpha** [comment]
versions on inst_summary seem to match. galil-old also looks fine to me

**Comment by FreddieAkeroyd** [comment]
repointed for review in new sprint
