### ISSUE TITLE
SRS P300 HV PSU

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8165]
As someone wanting to control HV Power Supplies at ISIS, I want to get the SRS P300 added to IBEX to simplify workflows and control.

##Acceptance Criteria
- [ ] There is an IOC for the SRS P300
- [ ] There are appropriate IOC Tests for the SRS P300
- [ ] There is an OPI for the SRS P300
- [ ] There are release notes for the new device

##Notes
- The Manual can be found in the usual place
- There is a note of the task, and a timeline, request came from IEOD

**Comment by FreddieAkeroyd** [comment]
Is this the same as #7951 ?

**Comment by KathrynBaker** [comment]
Duplicate Issue
