### ISSUE TITLE
Review User Training Course Materials [Timebox: 2.5 days]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8178]
There is a Powerpoint is in the user manual wiki
Need to add:
alarms view updates
moxa view
Script Generator

Ensure we know what needs changing, make a start on adding, create a new ticket if the timebox runs out

Points: 8

**Comment by zsoltkebel** [comment]
Added slides and notes for new features. Updated team photos (some are still missing). New slides can be identified by "New Feature" label in the bottom left corner. Put slides onto shares at `\training\Updated training slides for IBEX\IBEX Initial Training.pptx`
