### ISSUE TITLE
PEARL pressure controller: Add "Purge" functionality

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8181]
As a user I would like to be able to purge the pearl pressure controller in a similar way to how we retract the rams

This would require the same conditions that "retract" is under ie. under X bar pressure. We may need to contact (someone?) to find out what the command for this is. 

Currently this is done manually by Graham B (of iesg?) with an rs-232 interface so this means he doesn't need to come over and do it! 

### Acceptance criteria
- [ ] Purge button added to OPI 
- [ ] Purge function added to IOC

**Comment by rerpha** [comment]
note this is not just for PEARL - WISH use it too

**Comment by rerpha** [comment]
email sent off

**Comment by rerpha** [comment]
Just talked with GB (who is leaving this thursday!)
the command to purge is `PU` - this needs to be done under the same conditions as the "retract" functionality, though the controller itself will also have some safety built in. 
PU will respond with either some message about how it's failed, or the current pressure if it's now retracting.

**Comment by isaachilly** [comment]
## PRs

- https://github.com/ISISComputingGroup/ibex_gui/pull/1684
- https://github.com/ISISComputingGroup/IBEX/pull/8273
- https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/14

### To test:

1. Checkout to the above branches. 
2. Start the IOC by running in a EPICS terminal run_tests.bat -a
3. Check purge functionality seems acceptable and makes sense from reading the manual and common sense.

**Comment by rerpha** [comment]
still impeded

**Comment by rerpha** [comment]
happening next shutdown (august)

**Comment by rerpha** [comment]
still happening next shutdown
