### ISSUE TITLE
deploy script: directory backup script ignores the ignore list

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8186]
A backup during a deploy failed with
```
PermissionError: [WinError 5] Access is denied: 'C:\\Instrument\\Settings\\$RECYCLE.BIN\\S-1-5-21-1529648298-3970
```
This directory is passed to the ignore list   https://github.com/ISISComputingGroup/ibex_utils/blob/96a53f316a6f43ccdacefceb9a3cdc70ceaff5ee/installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py#L132 but it is not passed on to the actual file move/copy function https://github.com/ISISComputingGroup/ibex_utils/blob/96a53f316a6f43ccdacefceb9a3cdc70ceaff5ee/installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py#L101

## Acceptance Criteria

* Backup command processes the ignore list

**Comment by isaachilly** [comment]
Hopefully changes added in linked PR fix this issue.

## PRS
https://github.com/ISISComputingGroup/ibex_utils/pull/176

**Comment by FreddieAkeroyd** [comment]
Thanks @isaachilly
