### ISSUE TITLE
Tasks on Instruments not being deployed to

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8199]
As someone supporting IBEX I want to know that the instruments not being deployed to also have appropriate updates and changes applied to them. For the deploy in January 2024 there are two items in the task list, as well as a number of databases which would benefit from truncation. These actions are listed below.

CHIPIR
- [x] Deploy RhFe Files

ARGUS
- [x] Deploy RhFe Files

CHRONUS
- [x] Deploy RhFe Files

EMU
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

HIFI
- [x] Deploy RhFe Files
- [x] run `fix_procserv` (needs ibex server stopped)

MUSR
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

MUONFE
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

RIKENFE
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

HIFI_CRYOMAG
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

OSIRIS
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

IRIS
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

IRIS_SETUP
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

TOSCA
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

VESUVIO
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

ALF
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

LET
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

MAPS
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

MARI
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

MERLIN
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

NIMROD
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

SANDALS
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] Truncate Database
- [x] run `fix_procserv` (needs ibex server stopped)

SELAB
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

SELAB2
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

SOFTMAT
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

DCLAB
- [x] Deploy RhFe Files
- [x] Switch to hotfix process release branch
- [x] run `fix_procserv` (needs ibex server stopped)

**Comment by esmith1729** [comment]
Is the RhFe step done by running a `git pull` in config/common?

**Comment by zsoltkebel** [comment]
SELAB2 hotfic branch step was uncomplete. Completed now.
