### ISSUE TITLE
Deploy Script: some motor PVs are ok not to be backed up

### ISSUE THREAD

**Issue by zsoltkebel** [ISISComputingGroup/IBEX#8201]
Show simpler error message if the PV is a galil specific one on a linmot for example.
![image](https://github.com/ISISComputingGroup/IBEX/assets/25386639/d7be7f41-87b2-4742-8378-94bee6cd8ff9)

**Comment by rerpha** [comment]
Hint: use (in psuedocode) get_pv_value("MTRXXXX_IOCNAME").startsWith("GALIL") for getting the extra values.
