### ISSUE TITLE
IPS - un-committed changes on NDXWISH from 12.0.1

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8206]
There were some un-committed changes that hadn't made the 14.0.0 release which we need to re-patch on, this ticket is to capture the changes so they are in the next release. 

### acceptance criteria
- [x] changes are put into PRs to be added for the next release
- [x] changes are re-patched over to ndxwish's 14.0.0 release 
- [x] hotfix re-added to ibex wiki page

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/827
https://github.com/ISISComputingGroup/EPICS-IPS/pull/8
https://github.com/ISISComputingGroup/IBEX/pull/8207

**Comment by rerpha** [comment]
To review check that
\instrument\apps\epics\ioc\master\ips now matches \\ndxwish\c$\Data\old\ibex_backup_2024_01_26\EPICS\ioc\master\IPS
and 
C:\Instrument\Apps\EPICS\support\IPS\master\OxInstIPSApp\data\OxInstIPS.protocol now matches  \\ndxwish\c$\Data\old\ibex_backup_2024_01_26\EPICS\support\ips\master\data\OxInstIPS.protocol

**Comment by rerpha** [comment]
haven't had much time to look at this any further, but we should email WISH scientists and ask whether they are using it soon or not.

**Comment by davidkeymer** [comment]
WISH will be using the IPS with two different magnets this cycle.  First time later this month (February).

Have been in touch with WISH scientists, and AJ of cryogenics, to arrange a test with the IPS.  Will check each version of the software and combine if necessary.

**Comment by rerpha** [comment]
We have just tested in the cryolab, and the version on 14.0.0 works perfectly - have talked to scientists and reverted NDXWISH to 14.0.0, so a `git status` should show no changes in `\instrument\apps\epics\` on NDXWISH.
