### ISSUE TITLE
INTER/CHIPIR: control of lindy network enabled power socket

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8210]
As  INTER and CHIPIR scientists i would like to control the lindy network enabled power socket 
https://www.lindy.co.uk/networking-c5/ipower-switch-classic-8-p4456

### Acceptance Criteria
* control available from ibex

### Extra Information
Using SNMP might be a good option - we have an epics SNMP support module in ibex

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Chsudeepta** [comment]
The IOC and corresponding POI has been created:
IOC: https://github.com/ISISComputingGroup/EPICS-Lndyisw/pull/1
OPI: https://github.com/ISISComputingGroup/ibex_gui/pull/1686
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/8279
