### ISSUE TITLE
refl: string constants are not displayed correctly

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8227]
As a reflectometry user I would like to have a string constant and I would like it to be displayed correctly. 

Currently these are given a type of "float_type" which causes the GUI to display each character in the char array as hex. 

This was noticed yesterday when helping INTER out with adding some string constants, which we noticed weren't displayed correctly. 

### Acceptance criteria
- [ ] String constants are displayed correctly

as you can see in this pic of INTER's constants tab, "OPI" and "slits" are strings that are not displayed correctly. 
<img width="571" alt="image" src="https://github.com/ISISComputingGroup/IBEX/assets/14823767/c4a0120c-129e-4afb-b8f8-080458938ec9">

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-refl/pull/56
https://github.com/ISISComputingGroup/ibex_gui/pull/1679
https://github.com/ISISComputingGroup/IBEX/pull/8228

To review:
- check out NDXINTER's config branch
- start ibex server
- go to the reflectometry perspective -> constants tab 
and check that the "OPI" constant says "INTER"

**Comment by Chsudeepta** [comment]
Code reviewed
