### ISSUE TITLE
Apply IBEXButtonBuilder to all applicable perspective buttons Timebox [1 day max]

### ISSUE THREAD

**Issue by isaachilly** [ISISComputingGroup/IBEX#8235]
## Where?
Convert buttons to use IBEXButtonBuilder in all perspectives where applicable.

Extension to: 
- https://github.com/ISISComputingGroup/IBEX/issues/8106

## How?
Ideally programmer could create an automated program to do this.
Most likely this ticket get's chipped away at by 1+ programmer manually converting each button.

- Do as many as possible in the timebox

## Acceptance criteria 
- [ ] Buttons changed don't break any functionality/tests
- [ ] Once timebox is exhausted, make a follow on ticket documenting the areas of the codebase that have been looked at already
   - [ ] Same timebox

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

## Time in planning
33:00 4/4/24

**Comment by zsoltkebel** [comment]
The IBEXButtonBuilder has been refactored as per group discussion so this ticket needs some further work to adopt the new design. Main difference: instead of buld use the `get()` method to retrieve the SWT Button instance if needed. You can find more details in the ticket #8311.
