### ISSUE TITLE
IOC generator: fixes need

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8249]
As a user of the IOC generator i would like some improvements/fixes:

- it needs to make sure the local git repository (top and ioc/master) is on an up to date master/main before making branches,  otherwise there are going to be a lot of merge conflicts later. Maybe people should start with a new developer build? The script should at least warn you 
- the script doesn't check if it has already added a directory to a makefile e.g. `IOCDIRS += name` can get added multiple times if script is rerun due to errors 
- it forces support and github repository to use the same shortened name as the ioc, it would be nice if these could be longer and more descriptive than the necessary short ioc name. Our IOC name is short and non really readable, out support directory name and github repository name can be more descriptive

## acceptance criteria

- above issues fixed

**Comment by esmith1729** [comment]
- It seems like there is some attempt to make sure that the `IOCDIRS += name` line isn't added more than once, but apparently isn't working well enough. I am going to try putting it into an `if not os.path.exists()` block. Might have to do something clever if we want to actually parse the list of IOCDIRS. 

![image](https://github.com/ISISComputingGroup/IBEX/assets/131008854/0087875a-5796-4dac-8e4f-e9084f47993b)

**Comment by esmith1729** [comment]
Sort of a confusing issue; there seems to be a problem where the device_generator script actually doesn't add the IOC name to the IOCDIRS list in `ioc/master` Makefile. Additionally, when I try to run this step again after generating the device, I get this error message: 

![image](https://github.com/ISISComputingGroup/IBEX/assets/131008854/c55c1ad7-7348-4427-ac77-87aff82e00a9)

I have run `make iocstartups` several times from EPICS top and can't seem to get this step to work. I believe this step `Add template IOC` is the step that would add the IOC name to the `ioc/master` Makefile, but it's getting interrupted by this error, and skipping to the next step, which is also a problem.

**Comment by esmith1729** [comment]
## PR:

- https://github.com/ISISComputingGroup/IBEX_device_generator/pull/33

## To Review:

- [ ] Create a github token from your own profile, some details can be found in device_generator readme
- [ ]  Create 2 test devices using the generator script, and ensure that IOC starts and can run (you still need to run `make` in support and ioc before doing this!), and that its system tests and OPI pass tests. The two test devices will have:
- [ ] 1.) A unique support module name *different* from the IOC name, and 
- [ ] 2.) the string "NONE" in the support_module_name field, to test that the IOC name will take its place in all relevant substitutions that the device_generator script performs.

The new command line format for device_generator is as follows: 

`%python3% IBEX_device_generator.py --name=NAME --support_module_name=NONE --ticket=TICKET --device_count=DEVICE_COUNT --use_git --github_token GITHUB_TOKEN `


- [ ] Update the device generator Readme with the new command line format, make sure to include support_module_name, and info about default being "NONE" in all caps.

**Comment by zsoltkebel** [comment]
# Changes:

## Local Git repository checks

The script check local git repo state before creating branch.

## Duplicate Makefile entries

The code checks if support module has been appended and won't re-add it to the list if so.

## Different IOC name and support directory/repository name.
<- Before the name could include spaces and the IOC name would be calculated from it by removing spaces, making it all caps etc.

-> Instead, now there are two command line arguments:
- `--ioc_name` (replaces `--name`) which should be the final string that will be used for the IOC. This will exactly reflect the IOC prefix and name and has to conform to the requirements. (length, characters etc.)
- `--device_name` if not defined will be equal to the IOC name. If defined the can be a longer name including spaces and such. this will be used to infer the support module name and the repository name.
