### ISSUE TITLE
McLennan: make IOC work if crate is power cycled

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8253]
As a user of the mclennan I would like the IOC to continue to work if the crate is power cycled, tiem was lost recent;y on an instrument due to this as it was not noticed the encoder ratio had reverted to a previous NVRAM value. Varios options are possibe:

- we send all necessary parameters on a move, however this may mean affect readbacks until a move?
- we have a monitor thread to check values and resend / save
- Mclennans are the most likely things to be power cycled as they're temporary and get moved around
- Possibly have a monitor on power cycle like the galils, but instead of raising to nagios it simply resends the parameters 

### Acceptance Criteria
- [ ] Investigate how to identify a power cycle
   - check manuals for uptime command or similar
- [ ] on power cycle of a mclennan crate ibex control is not affected

## How to Test
- [ ] there is a mclennan crate in the office, make sure this works against hardware

## Time in planning
38:20 4/4/24

**Comment by isaachilly** [comment]
## To test

1. Check the code quality is acceptable.
2. Check the tests are logical and pass.

Already tested on device.

**Comment by rerpha** [comment]
if you really want to test on office mclennan, settings are 9600,7,e,1, no flow control.

**Comment by FreddieAkeroyd** [comment]
This is different to what is said in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/McLennan-motors#office-mclennan-settings but i know we have two mclennan creates. Can we either make them both the same and in agreement with the wiki (changing as necessary), or label the crates each with their settings

**Comment by isaachilly** [comment]
Yes the settings were changed during mine and David's attempts to make the crates talk. They can be put back or as you say can change wiki etc and label creates as well.

**Comment by rerpha** [comment]
now labelled, wiki updated as well.
