### ISSUE TITLE
Windows 11: Set up build job that sets build target to win11

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8268]
As a developer I would like to make sure we build against win11. This follows on from #7581 

### Acceptance criteria
- [ ] In the same way as win7 and 10, we build EPICS for windows 11. 
- [ ] After this has run if there are any build errors follow up tickets are created to solve them if not trivial.

- can be done on an existing windows 10 machine, just target windows 11 in parameters

## Time in planning
1:25:00 4/4/24

**Comment by FreddieAkeroyd** [comment]
There are two things to consider here, building on windows 11 and building for a windows 11 target. We currently build on windows 10 for a windows 7 or higher target, you could target windows 11 from a windows 10 build node if you wished, these are just options you choose in the windows SDK. What you are really chosing is what operating system features you wish to rely on being present, windows is pretty good with backward compatibility so you normally target the minimum OS version that provides what you need or wish to be able to run on. In our case targetting windows 7 has been sufficient, but we could increase to windows 10 at some point. So there is a bit of a build matrix to consider. Building on W11 but targetting W7 or W10 and then testing this on W10 and W11 is probably the most important combinations, this covers a developer with W11 locally building something they might copy to an instrument (which runs W10). Building on W11 with a W11 target architecture and then testing this is less important at this stage as with the instruments being W10 we would have our build system targetting this and not W11. There is also VS2022 to bring into the mix, but that is yet another item to add to the build matrix...

**Comment by GRyall** [comment]
Is running in Jenkins on a schedule and generating files.
