### ISSUE TITLE
Windows 11: Set up build node for GUI

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8269]
As a developer I would like to build the GUI on a windows 11 machine. 

### Acceptance criteria
- [x] A Windows 11 build/test node has been set up
- [x] Jenkins job created for building the GUI on a windows 11 build node.

## Time in planning
1:15:55 4/4/24

**Comment by Chsudeepta** [comment]
Verified the job. The last run was successful.
