### ISSUE TITLE
IBEX GUI: remind user that server will still be running on client close

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8281]
As a developer I would like the IBEX GUI "Are you sure you want to close this application?" window to remind the user that the IBEX server will still be running in the background, this is sometimes forgotten as under SECI it was different.
   
### Acceptance Criteria
- [x] GUI message box for "exit ibex client" mentions the server will still be running and how to close it

### Extra Information
Possibly additional text along the lines of

`Closing this GUI will not terminate the IBEX server processes that are communicating with devices and logging data in the background. If you wish to shutdown all IBEX components use the "stop ibex server" link in the Windows start menu. If you wish to start or restart IBEX, use the "start ibex server" link in the Windows start menu`

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1687
https://github.com/ISISComputingGroup/IBEX/pull/8282
