### ISSUE TITLE
Mclennan: Allow certain values to be made available to edit without restarting the IOC

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8284]
As a scientist using the Mclennan there are times when I want to be able to edit the Jog velocity as well as the high and low limits, as these are not readily editable as the places to change them are non-persisting I would like a macro to let me make this change anyway that can be set in globals.txt. 

### Acceptance Criteria
- [ ] A security group is created that allows for the JVEL, HLM, and LLM to be set or not based on a specific macro which defaults to not allowing changes
- [ ] There are tests both with and without that macro set to ensure the beaviour is as expected

### Extra Information
- Selective access security for certain fields is already present in Mclennans, look at how it's already being done and extend it with macros

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

## Time in planning
1:42:45 4/4/24

**Comment by isaachilly** [comment]
### PRs

- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/619 
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/843 (has instructions on how to test)
- https://github.com/ISISComputingGroup/IBEX/pull/8296
