### ISSUE TITLE
jenkins: improve stale build checker

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8287]
As a developer I would like the "state builds checker" jenkins job not to warn about state incremental builds. A clean build is built every night so if a clean build has not appeared on the server then that is an error, however an incremental build is only built on a code change and hence it not having run for a few days is not necessarily a problem.

* The jenkins job runs https://github.com/ISISComputingGroup/ibex_utils/blob/master/build_tools/check_builds_are_recent.py   and currently has a single list of `epics_builds` and `x_days`, this should be separated into clean (or nightly) and incremental builds with different configurable values.
* build lists and days could potentially be a jenkins job parameters and not hard coded (this is done on some other jobs)

### Acceptance Criteria
- [ ] job list and warn days is more configurable

## How to Test
- put jenkins job onto the branch and run it from web gui

Note - following merge, Jenkins configuration will need updating to point at master and not the developnment branch

**Comment by GRyall** [comment]
What do we want to check on the incremental builds - still a warning if unchanged for a number of days, but just a larger number of days?

**Comment by FreddieAkeroyd** [comment]
Yes, we want to know if an incremental build has completely stopped being published, but it will need a longer lifetime. Maybe we give it two weeks and see?

**Comment by GRyall** [comment]
I have added a small piece of follow on work in #8329

**Comment by GRyall** [comment]
PR - https://github.com/ISISComputingGroup/ibex_utils/pull/195
