### ISSUE TITLE
IBEX GUI: add "add to clipboard" option when selecting a PV on a device screen

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8299]
As a user/developer I would like the option to copy the full PV name of a PV from an opi/device screen or accelerator PV. 

### Acceptance criteria
- [x] When right clicking a PV on a device screen I can copy the PVs name to my clipboard
- [x] When right clicking a PV on the beam status perspective I can copy the PVs name to my clipboard

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1693
https://github.com/ISISComputingGroup/IBEX/pull/8300

**Comment by Chsudeepta** [comment]
Verified in Motors, Device Screens and Beam Status screens - working fine as expected. However the tooltip one sees by hovering the mouse to the copy option is wrong.

**Comment by Chsudeepta** [comment]
The changes are coming up fine. We can close this
