### ISSUE TITLE
Organise a Friday: Suggested 17th May 2024

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8306]
As someone developing IBEX I'd like to have a day to work on some of the items that are not a priority but are potentially fun, interesting, or useful, as such putting a day aside to start/continue such work is helpful, this is always called a "Friday" even if it happens on a different day.

### Acceptance Criteria
- [x] The day is booked in calendars
- [x] An afternoon stand up to catch people up on what was done is booked
- [x] A comment can be added here with a list of potential tickets is available to spark ideas for anyone that needs them, or the Friday project board can be consulted
- [x] The Friday happened

### Notes
- The 8 points is related to the fact that most tickets on a Friday do not get pointed individually, and are allowed to be 0 points because of this allocation
- Whilst this ticket does not require release notes, those undertaken may, please do not forget them

**Comment by danielmaclaren** [comment]
As has been said on a previous Friday post "The purpose of this day is to pick up things that would not likely get prioritised, fun stuff for a Friday usually" so I've selected a few interesting tickets from the board below:

[Teatime?](https://github.com/ISISComputingGroup/IBEX/issues/8257)
[OPIs: Identify locations for new help icons](https://github.com/ISISComputingGroup/IBEX/issues/8027)
[Tabulate ioc test failures #6739 ](https://github.com/ISISComputingGroup/IBEX/issues/6739)
[System Tests: Automate manual system tests using Squish](https://github.com/ISISComputingGroup/IBEX/issues/7709)

Please feel free to browse the ['Friday Label'](https://github.com/ISISComputingGroup/IBEX/labels/Friday) on the Project Board as there are plenty more to pick from! 

(or if the inspiration strikes you, feel free to add your own)
