### ISSUE TITLE
Instruments: handle local changes to calibration files

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8315]
Currently we have an instrument specific branch for configurations, but a separate repository for calibration files with all instruments on master. How do we handle local instrument changes e.g. locally created ramp files etc.

- do we just leave repo as "dirty"
- do we try and push these, but we may get conflicts
- do we put instruments onto their own calib branch and push, we then need to merge master rather than pull master on an update
- do we try and keep local changes in a separate area/naming scheme (e.g. `local_`  prefix) so we can gitignore them

### Acceptance Criteria
- [x] A meeting is held to decide on our process
- [x] Tickets are created as appropriate

### Time in Planning
00:49:49 02/05/24

**Comment by FreddieAkeroyd** [comment]
If we go for a local pushed instrument branch then we can track changes better and so potentially let other groups manage the area a bit themselves?

**Comment by rerpha** [comment]
the scientists already have a local calib directory which is their space really. perhaps we should make it more clear that if they want to use a custom file they need to use that directory?

**Comment by FreddieAkeroyd** [comment]
yes i think we need to make their local calib area clearer, then we need to discuss the scenario of a new temp sensor is needed in a hurry:
- do they drop it in the local calib directory, in which case we need to manage the fact a duplicate may appear in the real calib directory later, jenkins warning?
- do we provide a mechanism for SE team to update master and pull new version?

**Comment by isaachilly** [comment]
# Actions to take resulting from team meeting on 25/05/2024:

In order of first to do:
1. Create Jenkins job to check the status of config dir. Similar to Scripts Divergence Check job we already have.
2. Organise and have meeting with Maxim and relevant to discuss the process; either sticking to the previous agreement or modifying it.
3. Based on the above meeting, if the reversion back to previous agreement causes the current system of local calib files to not be sufficient deal with this as it occurs.

**Comment by isaachilly** [comment]
## Actions to take:

1. Look at Jenkins Instrument Config https://epics-jenkins.isis.rl.ac.uk/job/HotfixStatusChecker_config/
2. Organise and have meeting with Maxim and relevant to discuss the process; either sticking to the previous agreement or modifying it.
Based on the above meeting, if the reversion back to previous agreement causes the current system of local calib files to not be sufficient, deal with this as it occurs.

**Comment by jackbdoughty** [comment]
Meeting held on 13/12/24. Agreed on the following:

- More responsibility to electronics to push calibration file changes to common repo
- As such they will need instructions/a tool to access git and make changes with ease
- Less stress on using local calibrations dir unless absolutely needed

**Comment by jackbdoughty** [comment]
Follow on ticket made: https://github.com/ISISComputingGroup/IBEX/issues/8606
