### ISSUE TITLE
ALL: Preliminary ticket to assess and remove blocks on instrument disk space control

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#8320]
## Space on instrument system disks
Space is difficult to control on systems disks because of:

  1. Growing/untrimmed database files(s)
  2. Growing/untrimmed log files
  3. Need for a clear choice on how much data for the above should be kept on the instruments.
  4. Issues with "archiving" any trimmed data are not part of this ticket as systems exist to ensure this is done regardless of any local space control strategies

## Acceptance criteria 
- [x] a. All files/types which need trimming/size management are identified
- [x] b. Ideal sizes/amount of data to be retained physically on the instrument disk are defined.
- [x] c. Results are recorded and can inform the next step in this process

## Notes
1. From a systems view (i.e. not losing beam time due to system disk becoming overfull), the maximum size of the files/sum of total file sizes should be controlled.
2. From a science/robustness view, the instrument should retain sufficient local data to enable viewing of at least recent data and logs.
3. For this ticket, there is no assumption of another source of data logging/error log files, just the question of how much would be useful to ensure is stored on the local instrument disk.

### Time in Planning
01:13:00 02/05/24

## Time in planning meeting (18/07/24)
18:00

**Comment by GRyall** [comment]
Discussion in planning suggests we may have covered this as part of  #8321. @ChrisM-S could you confirm if this still needs to be open and either close it or clarify what is left and propose again.
