### ISSUE TITLE
Danfysik -  make CURR PV raise its alarm to the alarm perspective

### ISSUE THREAD

**Issue by isaachilly** [ISISComputingGroup/IBEX#8342]
As a user the red major alarms are not showing on alarm perspective. This is because CURR PV doesn't have info(alarm, "<name of IOC (not including _0X)>") in db records.

Wiki page - https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches#3-alarm-pvs

### Acceptance Criteria
- [ ] Alarm did not show up with absence  of alarm field in db record
- [ ] Alarm field correctly added to the `CURR` PV 
- [ ] Alarm shows up in the alarm perspective due to the alarm field is added to db record

### Extra Information
Umbrella ticket: 
- https://github.com/ISISComputingGroup/IBEX/issues/8189

## How to Test
_verbose instructions for reviewer to test changes

time in planning 00:47 23/5/24
~24 20/06/24

**Comment by jackbdoughty** [comment]
[Link to IOC PR](https://github.com/ISISComputingGroup/EPICS-ioc/pull/868)
[Release Notes](https://github.com/ISISComputingGroup/IBEX/pull/8418)
See IOC PR for testing instructions
