### ISSUE TITLE
Conserver Log: start a new logfile each day

### ISSUE THREAD

**Issue by GRyall** [ISISComputingGroup/IBEX#8362]
As a developer I would like the conserver log to start a new log file each day, matching our other logs. 

### Acceptance Criteria
- [ ] The process generating conserver logs starts a new file each day

### Extra Information
This will enable #8363 

## How to Test
* You'll need to install cygwin as per README.txt in toos/master
* after building branch, start ibex and then leave overnight to see if new conserver dated log is created

time in planning 01:44 23/5/24

**Comment by FreddieAkeroyd** [comment]
I had previously added support for fpassing file names through strftime(), and i have confirmed that sending `SIGUSR2` as per https://www.conserver.com/docs/conserver.man.html will create a new log file with a new date. This signal can be sent via `C:\Instrument\Apps\EPICS\tools\master\cygwin\bin\kill.exe -USR2 <pid>`  but it is probably better if we could raise this signal / trigger this action  inside the program automatically every day.  So maybe a thread that periodically wakes up and checks the time and when past midnight sends a USR2 signal.
