### ISSUE TITLE
ConServer Log: log files older than 10 days are deleted

### ISSUE THREAD

**Issue by GRyall** [ISISComputingGroup/IBEX#8363]
As a systems administrator I would like conserver log files on Instrument PCs older than 10 days to be deleted, this will reduce effort spent freeing space on instrument PCs and match the period other logs are kept before being moved off instrument PCs. 

### Acceptance Criteria
- [ ] An automated process is in place that deletes conserver logs older than 10 days
- [ ] Appropriate checks are in place that this script is running appropriately
- [ ] The process is documented in the developer wiki

### Extra Information
This ticket is a result of the discussion that took place as part of #8321 .

See also: [developer wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Data-Generation-and-Storage-on-Instrument-PCs-(NDX's)).

This ticket will require #8362 to have been completed, so that their is not a monolithic log file, but separate ones for each day. 

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

Discussed ~1:02 20/06/24

**Comment by LilithCole** [comment]
To be done as part of https://github.com/ISISComputingGroup/IBEX/issues/8342

**Comment by GRyall** [comment]
@LilithCole  that doesn't look like the right ticket?
