### ISSUE TITLE
Gateways: why are they failing? [Timebox: 2.5 days]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8371]
## Where?
Multiple instruments have seen this, some with impacts on other local devices, where the PVs seem to be unavailable on other instruments

## How?
We do not know how this came about, but a few too many have seen this during the most recent cycle, starting with SURF, and including INES, and a number of others (not always realised by anyone other than ourselves). Currently it is usually resolved by restarting the IBEX server on the instrument, but this can take a number of tries.

## Reproducible?
No

## Acceptance criteria 
- [ ] There has been some research into why and how these are failing, and possible fixes.
- [ ] If time allows a fix is applied, if not a ticket is created to either apply the fix or continue the investigation.

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

time in planning 01:55 23/5/24

**Comment by FreddieAkeroyd** [comment]
On INES I killed just the external `gateway.exe` process but on restart it did not serve PVS externally. When I looked closely at the log it had bound to the wrong internet interface, in fact it had bound to loopback like the block gateway should do. I had to restart all of IBEX server to get this to work. The gateway is managed by procServ, i don't know if there is some interference between the external and block gateways causing their settings to be merged in some cases.

**Comment by ChrisM-S** [comment]
We tried a full restart on the NGEM PC earlier on but still still this did not clear things up (but which would have restarted IBEX

**Comment by FreddieAkeroyd** [comment]
### Failing gateway
```
[Fri May 10 12:30:12 2024] @@@ Restarting child "GWEXT"
[Fri May 10 12:30:16 2024] EPICS_CA_ADDR_LIST=127.255.255.255
[Fri May 10 12:30:16 2024] EPICS_CAS_INTF_ADDR_LIST=127.0.0.1
[Fri May 10 12:30:16 2024] EPICS_CAS_IGNORE_ADDR_LIST=127.0.0.1
[Fri May 10 12:30:16 2024] Statistics PV prefix is IN:INES:CS:GATEWAY:EXTERNAL
```
### working gateway
```
[Wed Apr 24 10:37:27 2024] @@@ Restarting child "GWEXT"
[Wed Apr 24 10:37:34 2024] EPICS_CA_ADDR_LIST=127.255.255.255
[Wed Apr 24 10:37:34 2024] EPICS_CAS_INTF_ADDR_LIST=130.246.54.235
[Wed Apr 24 10:37:34 2024] EPICS_CAS_IGNORE_ADDR_LIST=130.246.54.235
[Wed Apr 24 10:37:34 2024] Statistics PV prefix is IN:INES:CS:GATEWAY:EXTERNAL
```
 `EPICS_CAS_INTF_ADDR_LIST` gets set incorrectly - basically the external gateway starts up but uses the block gateway settings
