### ISSUE TITLE
GUI: fix `uk.ac.stfc.isis.ibex.utilities` dependency definitions

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#8393]
## Where?

In the gui in `uk.ac.stfc.isis.ibex.utilities` we seem to have manual classpath entries pointing at the `.m2` cache folder, looking for a byte-buddy version of `1.14.11`. However the target platform is actually resolving `1.14.9` so this fails.

It would be better for it to use the standard OSGi dependency mechanisms to fix this problem at source, rather than pointing the classpath directly at the `.m2` folder in an error-prone way.

While this doesn't prevent the GUI from launching in eclipse, we should not have "usual errors" which we ignore.

Marked as "good first issue" as the `utilities` application is very simple and you should be able to follow any OSGi hello-world style dependencies tutorial. There are also two examples in IBEX of applications defined in this way (main gui & script generator).

## Acceptance criteria 

- Define these dependencies / utility application using the usual OSGi mechanisms
- No errors when importing GUI into a fresh eclipse workspace (if you already have byte-buddy 1.14.11 cached in `.m2` for some reason, remove this before testing).

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1739 - it isn't actually built by eclipse or maven, and the same functionality exists in https://github.com/ISISComputingGroup/ibex_utils/tree/master/ibex_gui_utilities
