### ISSUE TITLE
[CSS]: Build CSS with Java 17

### ISSUE THREAD

**Issue by Chsudeepta** [ISISComputingGroup/IBEX#8398]
With Java 11 being sunset soon, as a Experiments Controls engineer, I want to build the CSS with latest version of Java. The target is Java 17 or 21.

## Acceptance criteria 
- [x] The CSS should build without any issues with Java 17
- [x] The build components should be correctly expanded by the set_css.bat 
- [x] The start_css.bat should open up the CSS and it should be able to use the OPI editor

## How to Test 
- [x] Download Java 17 from https://adoptium.net/en-GB/
- [x] Download the isis_css_top 
- [x] Run the build.bat
- [x] The .zip files for alarms, cs-studio etc should be created in corresponding folder
- [x] Go to C:\Instrument\Apps\EPICS\ICP_Binaries\CSS. read the instructions README_ADDING_NEW_FILES.txt
- [x] Copy the new .zip files
- [x] Run set_css.bat, followed by start_css.bat
- [x] Check you are able to open/update any of the existing OPIs in the OPI editor.

**Comment by Chsudeepta** [comment]
https://github.com/ISISComputingGroup/cs-studio/pull/16
https://github.com/ISISComputingGroup/isis_css_top/pull/22

**Comment by rerpha** [comment]
should we (ca we?) push upstream to https://github.com/ControlSystemStudio/cs-studio ?
