### ISSUE TITLE
HIFI: Group 3 Hall Probe

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8400]
As a user of HIFI I want to be able to read the values from the Group 3 Hall Probe to use with regards to the zerofield on HIFI.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] The frequency of readings needed is confirmed with the instrument scientists
- [ ] The UI design is confirmed with the instrument scientists
- [ ] IOC for Group 3 Hall Probe created
- [ ] OPI for Group 3 Hall Probe created
- [ ] Appropriate emulators and tests are created

### Extra Information
- This is a spin off ticket from #6088 and there is more detail in there of background
- The manual can be found at: https://wiki.jlab.org/ciswiki/images/6/62/G3_MAN_DTM-151-S.pdf
- There is no specific VI for this device, so the OPI needs to start from "scratch", a suggested layout would be:
![image](https://github.com/ISISComputingGroup/IBEX/assets/10552381/30e3a1a4-3dab-4f42-957a-66ba7dbf5848)
- The system will need a macro for the number of probes
- This is currently considered one device, with 2 COM ports, and 3 probes at each port
- Each probe needs a name, Address, and axis definition (axis is +/- X|Y|Z)
- On startup for each probe send `A%d SE0GDR3GCNNUFG` where %d is the address, this initialises the probes in the expected way, including set the range to the highest index
- Send `A%d F` at the rate agreed in the acceptance criteria, to each probe using %d for the probe address, and multiply the returned value by 1 or -1 based on the direction of the probe (e.g. X is +1, -X is -1)
- If `F` returns `OVER RANGE`, increase the range if possible, this may be most clearly dealt with in SNL or a script record as there are other range changes to consider too.
- If the absolute value of the field reading is less than the corresponding move down point (-1, 2500, 5000, 1000, these are all roughly 83% of the previous range level, ranges are 3000, 6000, 12000, 30000):
	- Change the range value down a level
- Otherwise:
	- If the absolute value is more than the corresponding move down point (2900, 5800, 11600, 999999, which are all roughly 97% of the current range value):
		- Change the range up a level
	- Otherwise
		- Do nothing
- The range is altered using `A%d R%d` replacing the `%d`s with the address of the probe and the range index to use.
- Send `A%d T` to get the temperatures for each probe where %d is the probe address

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

planning 92:00 2024/10/31

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-Group3HallProbe/pull/1
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/888
- https://github.com/ISISComputingGroup/ibex_gui/pull/1746
- https://github.com/ISISComputingGroup/EPICS/pull/375

Manual:
- `\\isis\shares\ISIS_Experiment_Controls\Manuals\Group3__Hall_Probe`

Docs:
- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Group3-Hall-Probe
