### ISSUE TITLE
Ibex: Training course for technicians 

### ISSUE THREAD

**Issue by GRyall** [ISISComputingGroup/IBEX#8404]
As an ISIS sample environment technician I would like a better understanding of how to interact with IBEX. As a member of the Experiment Controls Team I would like to reduce the number of calls received when equipment is moved.

Chris L has suggested that we should run a training course on IBEX for technicians. This should focus less on scripting and more on practical use of ibex when moving and setting up equipment.  The pace of the course should also be considered and plenty of time left for questions and answers. Proposed steps listed in acceptance criteria bellow. 

The suggested time frame for running the course is W/C 9th September (the week before the cycle starts). 

## Acceptance criteria 
- [x] A new set of training material is created largely based on the existing Ibex training, but removing the scripting and increasing the number of practical examples of adding and setting up devices as they are moved (e.g. moxa view, motors). Some physical hardware to take into training may be a useful training tool.
- [x] A date is booked for training and Sample Environment group invited (or multiple dates if need be - the group has 28 people in it including apprentices and students). A room with computers for training may be best. Please also invite @GRyall if available.

 
## Time in planning meeting (18/07/24)
22:09

**Comment by Tom-Willemsen** [comment]
- Provisional date: 11th September
- R34 computer training room booked out for that day + afternoon of 10th for computer setup time
- Sample environment technicians invited to express interest

**Comment by Tom-Willemsen** [comment]
The room has capacity for 12 + trainer. Actual machines needed will depend on sign-ups (only one so far...)

**Comment by Tom-Willemsen** [comment]
Slides on sharepoint (linked from wiki). Per discussion with Chris L, have gone with relatively few slides (covering just basics of some useful IBEX views - moxa, alarms, log plotter, plus the configurations (but not synoptics) section of the scientist training. Added more emphasis on comms, with slides on basics of serial etc.

Idea is then to spend a bit more time with some _practical_ demos of connecting serial/ethernet devices up to IBEX and creating blocks/device screens/plotting values from them in the log plotter/seeing what alarms they give when not talking/etc.

Have not gone into huge detail with motors as they are complicated and I didn't feel I had enough space in a half-day course for it - but if the course runs short we can always add in a discussion about motion (especially if we happen to be able to take a motion controller down to the training room).

Hopefully should be paced to leave plenty of time for questions.
