### ISSUE TITLE
polref: get laser button working

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8408]
as a polref scientist i would like the button that says turn laser off/on on the polref reflectometry front panel to work properly.

### acceptance criteria
- [x] button turns the laser on and off

**Comment by rerpha** [comment]
have added the background script to their base component, need to go down and see if the buttons work

**Comment by rerpha** [comment]
this involved adding the background script IOC to polref's base config. to review check it's in there and running

**Comment by jackbdoughty** [comment]
minor change - it works and scientists are happy
