### ISSUE TITLE
POLREF: re-zero motor from command line

### ISSUE THREAD

**Issue by GRyall** [ISISComputingGroup/IBEX#8411]
As a POLREF instrument scientist I would like a way to re-zero a motor on the motor table or PV used in the reflectometry server from the command line

### Acceptance Criteria
- [ ] motor can be re-zeroed from command line
- [ ] POLREF have been contacted and confirm that their needs are met

### Extra Information
"We have two primary ways to do this from the motor table and the reflectometry server, but not from the command line.

If we could have a way of doing this on the command line this would allow us to automate a lot of the beamline alignment procedures like the slit gaps and list centres.

This would be a big time saver."

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by rerpha** [comment]
suggestioN: put this in genie python advanced API. also make it require manager mode to run (as you would need for table of motors)

**Comment by FreddieAkeroyd** [comment]
* There is some existing logic in https://github.com/ISISComputingGroup/EPICS-inst_servers/blob/master/scripts/restore_motor_positions.py that it may be worth refactoring onto here 
* you may need to allow for frozen v variable offset mode in the motor record

**Comment by jackbdoughty** [comment]
See following links for ticket.

[PR link to system tests](https://github.com/ISISComputingGroup/system_tests/pull/107)
[PR link to EPICS-inst_servers](https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/395)
[PR link to genie-python](https://github.com/ISISComputingGroup/genie_python/pull/418)
