### ISSUE TITLE
WISH: make identifying motor controller associated with collimator clearer

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8421]
As a wish scientitist I would like it to be clearer on the collimator OPI which galil IOC i should restart for the oscillating collimator. If the galil is power cycled, currently this requires the program to be downloaded again, which is only done on ioc startup.
 
## Acceptance criteria
- [ ] procedure to restart motor ioc clearer from OPI

## Notes  

It may be sufficient to just display the underlying motor number somewhere on the collimator OPI, however i think we now have a PV containing the IOC name so it may be possible to display the actual IOC name on the OPI

It may be useful having a button to open the underlying motor screen anyway?

**Comment by rerpha** [comment]
MOT is a configurable macro available to the OPI, so we can show the MTRXXXX and the IOCNAME easily

**Comment by jackbdoughty** [comment]
[IBEX GUI PR](https://github.com/ISISComputingGroup/ibex_gui/pull/1724)
[Release Notes PR](https://github.com/ISISComputingGroup/IBEX/pull/8432)
