### ISSUE TITLE
Motor settings: restructure?

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#8427]
## Where?

Currently motor settings (e.g. `jaws.cmd`) are sometimes found in a few different places:
- `c:\instrument\apps\EPICS/support/motorExtensions/master/settings`
- `c:\instrument\settings\...\galil`
  * Or `..\jaws`, `..\motorExtensions` and other similar directories
- Sometimes in `c:\instrument\apps\epics\support\ioctestframework\master\test_support` or `test_data` and similar directories (for IOC tests)

This can cause problems when settings get out of sync with each other, which recently caused an issue on GEM. See discussion in teams "support-issues" channel 23/04/2024 @ 14:30 for further context.

Probably a brief meeting to decide a plan and then spin off any required tickets

## Acceptance criteria 
- [ ] Agreed plan about (through either a meeting or online discussion):
  * [ ] Exactly which areas are the "authoritative" copies
  * [ ] Where the settings are kept so that they can be accessed by both instruments and IOC tests
  * [ ] Minimising duplication so that settings in github and in the instrument settings area don't diverge.
  * [ ] Whether there are different/better structures for any of these areas that we want to adopt
- [ ] If trivial to implement, implement the plan. If not, spin out tickets  

## How to Test 
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

## Time in planning meeting (18/07/24)
1:44:00

**Comment by rerpha** [comment]
can we remove `c:\instrument\apps\EPICS\support\motorExtensions\master\settings` in favour of just making a branch to be merged into whatever instrument they apply to? if they're not used by tests they are probably superfluous?

**Comment by Tom-Willemsen** [comment]
meeting tbd

**Comment by Tom-Willemsen** [comment]
Meeting 14th August @ 15:00

**Comment by Tom-Willemsen** [comment]
## Outcome of meeting
- The central source of truth will be `c:\instrument\apps\epics\support\motorExtensions\master\settings\INST_NAME`
- At least initially, the structure below that directory will be equivalent to the existing structure under the `settings` area
- Long term view:
  * The settings area should be "numbers" (e.g. motion setpoints files describing mapping of pos name <-> motor SP)
  * The `motorExtensions` area should be "code" e.g. `st.cmd` fragments etc.

## Acceptance criteria for implementation phase of this issue
- [ ] Existing motor settings in `c:\instrument\settings\...` for each instrument are copied to `c:\instrument\apps\epics\support\motorExtensions\master\settings\INST_NAME`
  * Check and adjust any paths as necessary, but do not do any _structural_ refactoring
- [ ] Write an upgrade script for the next deployment that:
  * Runs `git log` on the motor settings directories
  * If any commits exist in between the date that the settings were copied and the deployment date, raise a message stating that a manual re-copy/re-merge needs to be done
  * If no commits exist in between the date that the settings were copied and the deployment date, delete the motor settings directories in `c:\instrument\settings\...`. 
- [ ] Adjust the motor `st-common.cmd`s to look at `motorExtensions\master\settings\INST_NAME` rather than the settings area.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/65 (the big one)
- https://github.com/ISISComputingGroup/EPICS-upgrade/pull/82
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/875
- https://github.com/ISISComputingGroup/IBEX/pull/8497

To review:
- [ ] Check motor settings have been migrated from config area -> motorExtensions
  * Check any hard-coded paths have been adjusted as necessary
  * This is the bit of the change that would be good to pair-review, there are a **lot** of settings migrated over, I have done my best to go through and check these for any hard-coded paths and any obvious mistakes, but would be good to have several pairs of eyes on this to reduce the chances that I've missed things.
- [ ] Check that the motor IOCs for galil, galilmul, mclennan, linmot, smc100, sm300 and twincat have all been adjusted to point at the new settings area correctly
- [ ] Run a representative selection of ioc system tests using motors and motor settings to prove no _obvious_ functionality has been broken
  * e.g. `python run_tests.py -t galil galilmul mclennan linmot refl jaws sm300`, and any others which are seen as useful.
