### ISSUE TITLE
Remove old stanford SR400 and PS350 LVDCOM IOCs 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8461]
As a developer I would like to remove the now-superfluous LVDCOM IOCS for the Stanford SR400 photon counter and the PS350 power supply. These are now covered by stream device IOCs instead (done in #7951 and #6214 ) 

### acceptance criteria
- the two lvdcom iocs are removed

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/873
https://github.com/ISISComputingGroup/IBEX/pull/8462

**Comment by rerpha** [comment]
have also archived https://github.com/ISISComputingGroup/EPICS-Stanford_SR400 and https://github.com/ISISComputingGroup/EPICS-Stanford_PS350

**Comment by davidkeymer** [comment]
Have checked that removed IOCs are no longer built by running `make` in `IOC\master` directory.
