### ISSUE TITLE
Deploy to Summer group (w/c 19/8/2024)

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8467]
Deploy a full release to the following instruments:

###Summer
CHIPIR
- [x] NDX and NDH patches done
- [ ] In Progress
- [ ] Complete

ARGUS
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

CHRONUS
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

EMU
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

HIFI
- [x] NDX and NDH patches done
- [ ] In Progress
- [ ] Complete

MUSR
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

MUONFE
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

RIKENFE
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

HIFI-CRYOMAG
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

OSIRIS
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

IRIS
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

IRIS_SETUP
- [x] NDX and NDH patches done
- [ ] In Progress
- [ ] Complete

TOSCA
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

VESUVIO
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

ALF
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

LET
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

MAPS
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

MARI
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

MERLIN
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

NIMROD
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

SANDALS
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

SELAB (leave for moment - VHD test?)
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

SELAB2 (leave for moment - VHD test?)
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

SOFTMAT
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

DCLAB
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

DETMON
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

## Extras
SXD
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

### Time in Planning
00:01 08/08/2024

**Comment by FreddieAkeroyd** [comment]
HIFI is still SECI, was it worth doing now or just leave to next time when it is being migrated?

**Comment by davidkeymer** [comment]
Have deployed v15 to SELAB and SELAB2 for training courses.

**Comment by Tom-Willemsen** [comment]
Spun out CHIPIR, HIFI, IRIS_SETUP into tasks so that we can get the rest of this ticket through the system.

HIFI - is a mini-inst so likely not urgent
CHIPIR - migration work ongoing?
IRIS_SETUP - was being used when we looked during shutdown, needs to wait until it's not in use.

**Comment by davidkeymer** [comment]
Have checked version of all instruments (apart from the three above exceptions) via the [Instrument Summary page](https://beamlog.nd.rl.ac.uk/inst_summary.xml).  Not all machines are listed, so used local client to connect and check version in `Help -> About` menu.  Needed to RD to DETMON to check its version.
