### ISSUE TITLE
 Repo checks: check for permissions on EPICS repos

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#8480]
As a: [developer/user/instrument/project requirement] I would like the repo_checks build to make sure every repository in EPICS has permissions set for:
- [x] `ICP-read` as a reader 
- [x] `ICP-write` as a writer
- [x] `ICP-writeandmerge` as a maintainer

so that the release build works reliably

The release build script noticed this but repo checks didn't, this meant an issue wasn't detected until release time.

Make the repo checks catch this error.

### Acceptance Criteria
- [x] Repo checks catch this error.

## How to Test
- [x] Verify that repo checks would catch this error
### Discussed in planning 05/09/24
14:50

**Comment by FreddieAkeroyd** [comment]
While doing this we should also check that `ICP-WriteAndMerge` has `Maintain` access thought it is not required for a release

**Comment by iangillingham-stfc** [comment]
PR ready for review:
https://github.com/ISISComputingGroup/EPICS/pull/369
Release notes updated.
