### ISSUE TITLE
GUI: INSTETC and DAE appear in the IOC list in the configuration editor

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#851]
These IOCs shouldn't appear in the list (see the start/stop IOC menu)

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 852.  Created by mjc23 on 2015-07-23T13:47:52, last modified: 2015-08-28T15:03:16_

**Comment by DominicOram** [comment]
Fixed
