### ISSUE TITLE
Blockserver failing to start

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8511]
Blockserver is failing to start with error 
```
[Tue Sep 17 17:28:35 2024] [2024-09-17 17:28:35.420261] MAJOR: Unable to format ioc start time: time data '17/09/2024 17:28:34' does not match format '%m/%d/%Y %H:%M:%S'
```
This has happened after https://github.com/ISISComputingGroup/EPICS-devIocStats/pull/4

### Acceptance criteria

- blockserver starts again

### Notes

Original PR was done to fix issue with date format on GUI, however it looks like there are dependencies on original IOC date format elsewhere than just GUI. If we can find all dependencies we can fix them, otherwise we could get GUI to reformat just its date

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-devIocStats/pull/5
