### ISSUE TITLE
GALIL: print more of motor error message

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8512]
The motor error message is truncated in the OPI - in this case it was "begin not valid with motor off"

![image](https://github.com/user-attachments/assets/2d6e648e-094b-4208-aa96-55298867b404)

## Acceptance Criteria

- [ ] Reduce truncation of error message by widening the box in the OPI (~40)

## Planning
19/12/24 - Assumed that the error message is truncated by OPI, if widening box in OPI doesn't fix it - open new ticket.

**Comment by KathrynBaker** [comment]
Acceptance criteria assumption - it is just as simple as widening the box to 40 characters

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1759
