### ISSUE TITLE
CHIPIR: more LNDYISW iocs

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#8516]
# Issue Description

Chipir have at least 4 lindyisw's, maybe more, make some more IOCs available (maybe 6 in total?)

# Acceptance Criteria
- [x] More lndyisw iocs available

# How to Review
<sub>Before making a PR... </sub>
- _Provide verbose instructions for the reviewer to test that your changes work and fix the issue_
- _Describe if/how you have implemented testing for this issue_
- _Provide screenshots of the feature to help the reviewer if relevant_

<sub>_If not applicable, write "Not applicable"_</sub>

[comment]: <> (FILL IN BELOW)
> ...

<sub>**To the reviewer: Make sure to [update submodules](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow#reviewing-work-for-the-submodules-of-epics)!** </sub>

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/880
https://github.com/ISISComputingGroup/IBEX/pull/8517
