### ISSUE TITLE
Alternative Synoptic View

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#852]
As a scientist, I want a view that comprises a simplified synoptic, a scripting window and a graphing window, so
that I have all three elements in a single view.

== Acceptance Criteria ==
1. On selecting the "alternative synoptic", I see all 3 views
1. a synoptic showing just the icons representing the individual devices (i.e. no PVs)
2. a scripting window
3. a graphing window
   1. I can interact with all 3 views in the same way as I can interact with the existing individual views

== Notes ==
1. Need a name for this "alternative synoptic" or "combined view"
1. When you double-click on a synoptic icon, does it display the OPI (as it does now?) - presumably, yes.
1. Some other issues to consider before implementing this ticket:
1. Do we need more feedback from scientists? (no need to wait for the feedback - just ask for it)
2. has the Ctrl+C issue (see #750) been fixed?  (we ought to fix it first).
3. Scripting window can be slow to load first time.  Consider loading it in the background when IBEX client starts up.
4.  Any other irritating problems associated with synoptic views or scripting windows that we could fix at the same time?

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 853.  Created by skn09965 on 2015-07-23T13:53:05, last modified: 2015-08-28T15:03:16_

**Comment by KathrynBaker** [comment]
+1 from the muon scientists - although all they want to see is scripting and logging in the same window - this was the closest ticket I could find relating to combined views

**Comment by ThomasLohnert** [comment]
Since different instruments have different needs, we should create something like a customizable "front panel" perspective, where scientists can assemble their layout from arbitrary viewparts and save the layout with E4 (depends on https://github.com/ISISComputingGroup/IBEX/issues/3503)

**Comment by KathrynBaker** [comment]
Consideration of these displays is no longer practical given the changes over time
