### ISSUE TITLE
SANS2D: BioLogic MPS 70/4 (stopped flow) setup

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#8528]
# Issue Description

SANS2D occasionally want to use a BioLogic MPS 70/4 controller for a stopped-flow setup.

The device has 3 physical interfaces (network, usb, serial-over-rj45).

However, from all of the manuals that I can see, there is not an obvious documented command set that we can use remotely.

This ticket is to talk with the scientists and other relevant parties to figure out if or how we support this thing. 

**We may not be able to talk to it from IBEX, in which case this ticket becomes to write notes on the wiki about what the agreed setup looks like.**

### Additional Information

This setup was last used on SANS2D on 3/10/2024. Setup notes from _that_ experiment, which was set up in a non-optimal way:

> There is manufacturer software that they can use for this experiment, as they don't need to script it from IBEX directly, so we set up a laptop with the manufacturer software on it in the sample area and then they are RDPing to this laptop to use the manufacturer software when they need to.
> 
> Laptop is connected to the device via a local USB connection. Laptop is networked on a wired connection (patched through to cabin via SANS9 in our case, but any network port would work). Laptop is incredibly slow and was complaining about loads of windows updates etc, so I don't have 100% faith it'll survive the experiment.
>
> For avoidance of doubt, the actual device is not on the ISIS network or connected to our MOXA at all - it is just connected via USB to the scientist's laptop. There is no software link whatsoever to IBEX.

# Acceptance Criteria

Either:
- IBEX supports this device (or tickets written for that support)
Or:
- Notes describing the "agreed" setup of this device, with input from other groups, on wiki
Or:
- We agree with scientists and other support groups that this setup will not be supported from a computing perspective

# How to Review
<sub>Before making a PR... </sub>
- _Provide verbose instructions for the reviewer to test that your changes work and fix the issue_
- _Describe if/how you have implemented testing for this issue_
- _Provide screenshots of the feature to help the reviewer if relevant_

<sub>_If not applicable, write "Not applicable"_</sub>

[comment]: <> (FILL IN BELOW)
> ...

<sub>**To the reviewer: Make sure to [update submodules](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow#reviewing-work-for-the-submodules-of-epics)!** </sub>

**Comment by GRyall** [comment]
I have confirmed with RD that there is currently no requirement for control of this from IBEX. A new laptop has been ordered to control it in future and the preferred set up is controlling it using serial as the USB has  a known issue where it times out.

**Comment by GRyall** [comment]
Documented on wiki: [https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/BioLogic-MPS-70-4-(stopped-flow)](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/BioLogic-MPS-70-4-(stopped-flow)). Closing ticket.
