### ISSUE TITLE
Automatically move crash dumps

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8537]
As a developer I  would like crash dumps to be automatically moved from the instrument to stage-deleted after a period of time. Currently they accumulate in  `c:\Instrument\Scratch\CrashDumps` in the instrument 

There is an existing `stage-deleted\dumps\NDXyyy` area - do we wish to change this to be in the usual hierarchy e.g. `stage-deleted\NDXyyyy\CrashDumps`

##Acceptance Criteria 

- [ ]  Crash dumps are automatically moved from the instrument to stage-deleted after a period of time using similar paths as for other rotations by updating logrotate script in comment bellow, matching the same period of time for other rotations. 

## Planning
19/12/2024 - ideal for next release. Consider for patching onto other tickets

**Comment by Tom-Willemsen** [comment]
I think this is quite easy to add to https://github.com/ISISComputingGroup/EPICS/blob/master/utils/logrotate.py so putting this as a good first issue.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS/pull/380
