### ISSUE TITLE
Have a "Friday"

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8554]
As a developer I like to have Fridays, and spending a day on less urgent but fulfilling tasks can bring joy.

### Acceptance Criteria
- [x] A day where most of the team is available is identified by checking the calendars of the whole team
- [x] An invite is sent to the group for that day, so that time can be put aside
- [ ] A list of tasks that have a Friday label on them is collated
- [x] A meeting is scheduled in the late afternoon for a catch up on the state of things
- [x] The day happens

### Notes
- In this context a "Friday" task is as the story says, items that as developers we find fulfilling, but which cannot necessarily be prioritised against the rest of the workload
- Tasks can be returned to if not complete in a single day on further Fridays
- Majority of the points will be to cover the friday items that might not otherwise get pointed, but the person named on the ticket is the one who will do the organising
- Once the day of the meeting has occurred, this can be considered complete there is little to review

planning 76:00 2024/10/31

**Comment by Tom-Willemsen** [comment]
"Friday" 13th Nov

**Comment by Tom-Willemsen** [comment]
Linking some of the issues I'm aware of / have PRs - please edit if yours is missing:

- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/55
- https://github.com/ISISComputingGroup/IBEX/issues/8566
- https://github.com/ISISComputingGroup/IBEX/issues/8280
