### ISSUE TITLE
Truncate mysql databases pre-cycle on instruments

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8562]
As a developer or system administrator, I would like the disk space on the control machines to be sufficient for the instruments to run and collect data.

### Acceptance Criteria
- [x] list of machines created
- [x] scientists notified https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space
- [x] Disk space is freed on the machines listed below

#### Notes
- to get a list of current database sizes see [nagios](https://control-mon.isis.cclrc.ac.uk/nagios/cgi-bin/status.cgi?servicegroup=mysql_db&style=detail) - add all warning and critical, and then reviews the largest that are green. You can click the arrow at top of service column to sort by service name. 
- Instructions to reduce space [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Database-Troubleshooting#reducing-database-disc-space)
- Machines in list are sorted by priority, highest at top (based on `critical` and `warning` status of Nagios check)
- Log files will be moved by a central script on the maintenance day or at a later date

## Instruments

- NDXSOMETHING
  - [ ] Started
  - [ ] Completed

planning 115:00 2024/10/31

**Comment by Tom-Willemsen** [comment]
## High priority (warning in nagios)

- NDXEMU
  * [ ] Started
  * [ ] Completed
- NDXHIFI-CRYOMAG
  * [ ] Started
  * [ ] Completed
- NDXIMAT
  * [ ] Started
  * [ ] Completed
- NDXINES
  * [ ] Started
  * [ ] Completed
- NDXMUSR
  * [ ] Started
  * [ ] Completed
- NDXOSIRIS
  * [ ] Started
  * [ ] Completed
- NDXRIKENFE
  * [ ] Started
  * [ ] Completed
- NDXSANDALS
  * [ ] Started
  * [ ] Completed
- NDXTOSCA
  * [ ] Started
  * [ ] Completed
- NDXMERLIN
  * [ ] Started
  * [ ] Completed

## Lower priority (large-ish but not yet warning, >~5GB)


- NDXINTER
  * [ ] Started
  * [ ] Completed
- NDXIRIS
  * [ ] Started
  * [ ] Completed
- NDXLARMOR
  * [ ] Started
  * [ ] Completed
- NDXMAPS
  * [ ] Started
  * [ ] Completed
- NDXMARI
  * [ ] Started
  * [ ] Completed
- NDXMUONFE
  * [ ] Started
  * [ ] Completed
- NDXOFFSPEC
  * [ ] Started
  * [ ] Completed
- NDXPOLREF
  * [ ] Started
  * [ ] Completed
- NDXSANS2D
  * [ ] Started
  * [ ] Completed
- NDXSURF
  * [ ] Started
  * [ ] Completed
- NDXWISH
  * [ ] Started
  * [ ] Completed
- NDXZOOM
  * [ ] Started
  * [ ] Completed

**Comment by Tom-Willemsen** [comment]
All done except MERLIN which is down. Have spun merlin out into [a task](https://github.com/orgs/isisComputingGroup/projects/17/views/4?pane=issue&itemId=86938935) to avoid it blocking this ticket which is mostly complete.
