### ISSUE TITLE
New MARI dashboard showing UNKNOWN for DAE fields in header

### ISSUE THREAD

**Issue by mducle** [ISISComputingGroup/IBEX#8569]
The web-dashboard [on MARI](https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=mari) is currently showing `UNKNOWN` in the DAE fields in the main header (coloured-background bit). It should be showing the `Good/Raw Frames`, `Current/Total`, `Monitor Counts`, `Inst. Time`, `Run Time` and `Period`.

Restarting the IBEX server on the NDX machine doesn't work.

A quick check shows that the same behaviour is happening on [MAPS](https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=maps), [LARMOR](https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=larmor), and [OFFSPEC](https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=offspec). Might be others too.

**Comment by mducle** [comment]
Thanks, we'll use the new dashboard. These info are not critical.

**Comment by Tom-Willemsen** [comment]
@mducle I have set the relevant PVs to be archived again on MARI. Next time you restart ibex server, these should get picked up again by https://dataweb.isis.rl.ac.uk/IbexDataweb/default.html?Instrument=mari - let us know if not.

p.s. if you have any non-urgent feedback/suggestions on the _new_ webdashboard I linked in my first comment, do feel free to create issues in the [webdashboard repo](https://github.com/ISISComputingGroup/WebDashboard). (For anything urgent please continue to use phone or group email). Thanks!

**Comment by mducle** [comment]
@Tom-Willemsen Thanks for this. I just restarted the IBEX server and the DAE info is now shown in the old dashboard but the [new dashboard](https://isiscomputinggroup.github.io/WebDashboard/instrument?name=mari) is showing `NaN` for all the non-DAE variables (i.e. the only the ones where the old dashboard used to show `UNKNOWN` are now correctly displayed in the new dashboard).

I guess that since the new dashboard is not in production that we leave it as it is, and then revert the `dashboard.db` file when we switch over?
