### ISSUE TITLE
Config GUI: Add a button to  the IOC PV Values Screen to launch the lookup screen to the IOC PV Values Screen

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#857]
As a User I'd like to be able to look-up the PVs on the IOC PV Values screen in the same way as with the Blocks and Synoptic Editor.

== Acceptance Criteria ==
1. There is a button to launch the PV lookup screen
1. The selected PV is propagated back to the IOC PV Values

== Notes ==

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 858.  Created by kvlb23 on 2015-07-30T13:44:28, last modified: 2015-08-28T15:03:16_

**Comment by KathrynBaker** [comment]
Screen no longer accessible, closing the ticket
