### ISSUE TITLE
MUONTPAR: fix test failures with static build and tidy up code

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8573]
The muontpar system tests fail with the static EPICS build, error is `Write access denied for PV TE:SPARE53:MUONTPAR_01:SAVE_FILE` but this is likely due to an earlier fault.

**Comment by FreddieAkeroyd** [comment]
Couple of questions:
- newFileWarning is only set on file not found and not other file errors, is that correct?
- getline is used to read lines in a file, then all lines are concatenated together to store in single char array - could the file just be directly read into the char array?

**Comment by rerpha** [comment]
@FreddieAkeroyd am i OK to review this?

**Comment by FreddieAkeroyd** [comment]
@rerpha yes - and please comment on questions above too

**Comment by rerpha** [comment]
> newFileWarning is only set on file not found and not other file errors, is that correct?

Just trying to think which other errors _should_ indicate that the writer is going to make a new file. if it can't load a file it shouldn't overwrite it I don't think? 

> getline is used to read lines in a file, then all lines are concatenated together to store in single char array - could the file just be directly read into the char array?

possibly - I think Isaac may have done this for the CSS to show newlines but i'm not certain - if it works OK reading directly in we could do that instead and I think that simplifies the logic a fair bit?

**Comment by rerpha** [comment]
@FreddieAkeroyd I think https://github.com/ISISComputingGroup/EPICS-FileServer/pull/5 works just as well so I don't think you have to split up by line.

**Comment by FreddieAkeroyd** [comment]
what should we do if saveFile or readFile fail, currently if saveFile failed it would still flag unsaved changes, is that enough?

**Comment by rerpha** [comment]
hmm, in all of those cases perhaps it'd just be sufficient to set the `LOG` PV to say what has happened?

**Comment by FreddieAkeroyd** [comment]
how about that now - i also cleared `P_fileContents` on any file read error not just file not found, does that sound right? It calls eaed file whenever filename changes, people could not accidentally lose what they have typed if they want to change filename?
