### ISSUE TITLE
ibex installer: install visual studio redistributable

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8576]
Currently IOCs will crash if installed on a computer with an outdated Visual Studio redistributable. The IBEX installer needs to install the VC redistributable during deployment.

## Acceptance criteria

* `vc_redist.x64.exe` installled on a 64 bit install,  both `vc_redist.x86.exe` and ``vc_redist.x64.exe` on a 32bit install 

## Notes

* During build `vc_redist.x64.exe`  and `vc_redist.x86.exe` are copied from the Visual Studio area to the `EPICS/crtl` directory, so after installing EPICS the ibex deployment tool can pick these up from there so they do not need to be stored separately
* Ideally system test servers should run the same version of redistributable as we will deploy. As i think admin prompt may happen, it is probably not possible to auto-update them as part of jenkins job

Time in recording of planning meeting: 00h32m 2024/11/28

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_utils/pull/214
Not going to add release notes as it's in ibex_utils and therefore not deployed on instruments.
