### ISSUE TITLE
Synoptics: Can add unlimited READ and WRITE items with the same name!

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#858]
A limit of two - one read and one write would probably be sufficient.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 859.  Created by mjc23 on 2015-08-03T13:06:38, last modified: 2015-08-28T15:03:16_

**Comment by mattclarke** [comment]
It works as expected but "PV name" and "PV name " (trailing space) are considered unique.
It the gui riddled with these sorts of error?

**Comment by DominicOram** [comment]
Awaiting merge of https://github.com/ISISComputingGroup/ibex_gui/pull/403

**Comment by DominicOram** [comment]
Stopped working on this ticket as it was getting tangled with work from https://github.com/ISISComputingGroup/IBEX/issues/1611. Pick up again once 1611 has been complete
