### ISSUE TITLE
Pinhole Selector GUI: Load & Operational Positions

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#865]
As a scientist, I need to be able to switch the pinhole selector between loading mode and operational mode, so that, 
(a) during setup, I can rotate the pinhole selector to positions that allow new pinhole cartridges to be loaded and, 
(b) during experiments, I can rotate the pinhole selector to place different pinholes in the beam.

== Acceptance Criteria ==
1. I can choose whether the pinhole selector is in "loading mode" or "operational mode"
1. In "loading mode" the pinhole selector can be positioned so that pinhole cartidges can be loaded and unloaded
1. In "operational mode" the pinhole selector can be positioned so that pinhole cartidges can placed in the beam

== Notes ==
1. We could use a checkbox to indicate "loading mode" or "operational mode"
1. Use state of checkbox to select between two sets of positions - loading set and an operational set.
   1. In "loading mode" the key position is at the "9 o'clock" position (that's where the door on the casing is).
   1. In "operational mode" the key position is at the "12 o'clock" position (that's where the beam is).  Should we distinguish these visually?
   1. See attachment for an illustration of how the pinhole selector is positioned in the different modes.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 866.  Created by skn09965 on 2015-08-06T11:55:30, last modified: 2015-09-23T12:37:49_

**Comment by KathrynBaker** [comment]
Superseded by later tickets, but this was completed a while back
