### ISSUE TITLE
Random Console Window Appearing

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#870]
I discovered an interesting twist, and more testing is probably needed, but if you have a python console connected, open the Alarms view, then change instruments you get a console tab alongside the alarms Not a big issue as I don't think we're using much in the way of alarms, but not what we want to happen really.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 871.  Created by kvlb23 on 2015-08-14T16:12:41, last modified: 2015-08-14T16:13:02_

**Comment by kjwoodsISIS** [comment]
_Trac comment by kvlb23 on 2015-08-14 16:13:02:_

Put into pending as an unlikely scenario - not urgent

**Comment by rerpha** [comment]
No longer an issue as a warning appears when switching instruments stating all current consoles will be closed.
