### ISSUE TITLE
Synoptic editor - select block should allow filtering by group

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#883]
As a user when selecting a block I would like to filter by group. I should be able to choose from the groups in a drop down and see only blocks for that group.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 884.  Created by whb43145 on 2015-08-26T14:25:18, last modified: 2015-08-28T15:03:16_

**Comment by KathrynBaker** [comment]
The same block selector is being used across all areas, and has been altered frequently, this requirement has probably been superceded.
