### ISSUE TITLE
IMAT: Test Beckhoff Motor Controller on Sample Stack

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#889]
As a support person, I want to test the Beckhoff Motor Controller and the ESS driver with the IMAT sample stack, so that I can determine how well they work.
#### Tasks
1. Install ESS software on IMAT Beckhoff Motor Controller
2. Test how well ESS software is able to control the motion of the IMAT sample stack
#### Notes
1. We have already tested the ESS software on the Beckhoff Motor Controller intended for ZOOM (see ticket:816).
2. **N.B.:** the scope of this issue is deliberately limited to testing the ESS software on IMAT and documenting the results of the tests.  If the tests determine that more work is required, new issues will be created.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 890.  Created by skn09965 on 2015-08-27T14:04:09, last modified: 2016-01-26T14:31:08_

**Comment by FreddieAkeroyd** [comment]
Installed and working
