### ISSUE TITLE
PV Validation

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#894]
As an IBEX user I would like the PVs I enter to have basic validation done.

Would need to confirm what valid PVs are, but check for things like spaces and special characters. Alternatively this could be done by checking the PV exists.

The PVs are entered in the synoptic editor and the block tab of the config editor.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 895.  Created by whb43145 on 2015-09-07T11:25:06, last modified: 2015-10-21T09:25:33_

**Comment by KathrynBaker** [comment]
PR was closed
