### ISSUE TITLE
EPICS Gateway is converting some characters to numbers

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#917]
To reproduce enter the character 'a' into the value field of a sample parameter. This is converted to '10' in the GUI before it is written to the relevant PV.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 918.  Created by ffv81422 on 2015-09-23T17:27:05, last modified: 2016-01-28T11:51:39_

**Comment by kjwoodsISIS** [comment]
_Trac comment by ffv81422 on 2015-11-02 11:54:32:_

This is due to the gateway converting the characters.

**Comment by kjwoodsISIS** [comment]
Not critical to fix at present time.

**Comment by GRyall** [comment]
Confirmed fixed in  #2410
