### ISSUE TITLE
Synoptic View: Don't tab into indicators

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#933]
If I'm tabbing, I don't want the cursor to be placed inside the read only values.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 934.  Created by kvlb23 on 2015-09-24T16:01:05, last modified: 2015-09-24T16:01:05_

**Comment by DominicOram** [comment]
Can no longer reproduce
