### ISSUE TITLE
Log Plotter functionality

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#939]
The log plotter does need some work before it can be regarded as fit for purpose:
- Add plots without right-clicking on a block, i.e. needs some sort of plot creator wizard
- Be able to save plots, so they appear next time the GUI starts - this sounds like a can of worms!

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 940.  Created by mjc23 on 2015-10-09T09:50:44, last modified: 2016-01-25T15:17:29_

**Comment by kjwoodsISIS** [comment]
_Trac comment by skn09965 on 2015-10-28 08:48:54:_

ticket:955 has been raised to address the naming issue.

**Comment by KathrynBaker** [comment]
+1 for saving plots as part of config from muons

**Comment by DominicOram** [comment]
Given the first part of this ticket is done and there is a new ticket for the second part i'm closing it.
