### ISSUE TITLE
Synoptic: change all PVs to remote

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#971]
As a developer I would like all the PVs in the synoptic to be remote.

Transferring synoptics to other instruments would then require a batch search and replace of the preset in the XML.  This likely to be a manual step, but it is worth doing now (rather than later).

There is a ticket to create a wizard for this (#973), but it is not urgent

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 972.  Created by mjc23 on 2015-11-11T15:53:57, last modified: 2016-01-28T10:22:50_

**Comment by IsabellaRey** [comment]
I think this was worked on branch "Ticket972" and already merged. It should probably just move to complete, need to confirm with Ian
