### ISSUE TITLE
Look into UI/System Testing

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#978]
To help catch bugs in IBEX some system testing might be useful. This could be done via a UI test framework which uses a simulation mode BlockServer, for some initial tests. Ultimately the EPICS backend will need to be running too.

Something like SWTBot might provide the UI testing framework http://www.eclipse.org/swtbot/. The aim would probably be to get a broad range of fairly simple tests to begin with, rather than comprehensive testing.

This is a big area, with a lot that would be desirable to test in the long term. For this ticket investigate testing between the GUI and the BlockServer and decide:

1. How much time would be required to get tests running locally, and on the buildserver?
1. What tools to use? Is it likely a move to Eclipse 4 would mean starting system tests from scratch?
1. What tests to begin with?

To finish off this ticket some further tickets should be created for the work to get a small set of initial tests running.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 980.  Created by whb43145 on 2015-11-12T11:04:28, last modified: 2016-01-12T09:34:08_

**Comment by ianbush** [comment]
See Developer's Manual wiki pages:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT

**Comment by ianbush** [comment]
Ticket for implementation - https://github.com/ISISComputingGroup/IBEX/issues/1108
