### ISSUE TITLE
IMAT: Support for attenuator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#979]
As a scientist, I want to enable/disable the operation of the beam attenuator, so that I can control when it is in use (or not).

#### Acceptance Criteria
1. A GUI to enable/disable its operation
1. Ability to control the attenuator from a script.

#### Notes
1. The attenuator will be directly controlled from a PLC
1. Need to consult with Rob Searle - see settings defined in e-mail below.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 981.  Created by skn09965 on 2015-11-12T11:35:50, last modified: 2016-01-28T12:03:16_

**Comment by kjwoodsISIS** [comment]
Postpone until IMAT is ready to start using the attenuator.  Bring this issue into whichever sprint is in progress at the time.

**Comment by FreddieAkeroyd** [comment]
Winfried was asking about this, Rob Searle will be sending us PLC details

**Comment by kjwoodsISIS** [comment]
PLC settings from Rob Searle:
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 10 June 2016 10:31
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Akeroyd, Freddie (STFC,RAL,ISIS)
> Subject: FW: IMAT Sample Attenuator Control
> 
> Dear Kevin,
> 
> Please find below details for the IMAT PLC from Rob Searle – I apologise for not passing this on earlier.
> 
> Regards,
> 
> Gareth
> 
>> From: Searle, Rob (STFC,RAL,ISIS) 
>> Sent: 26 May 2016 12:26
>> To: Howells, Gareth (STFC,RAL,ISIS)
>> Subject: IMAT Sample Attenuator Control
>> 
>> Hi Gareth, 
>> As promised the other week, details of the Sample Attenuator for IMAT are below:
>> 
>> PLC IPaddress: 130.246.39.181
>> PLC FINS Node: 181
>> Network:             1
>> 
>> Control Word: W510       (This word will self-reset to 0)
>>               W510.00               set true to request Sample Attenuator to Open
>>               W510.01               set true to request Sample Attenuator to Close
>> 
>> Status Word: W511
>>              W511.00               true when Sample Attenuator requested to open via HMI or EPICS
>>              W511.01               true when Sample Attenuator is OPEN
>>              W511.02               true when Sample Attenuator is CLOSED
>> 
>> If you need anything else give me a shout (though I’m out until the 6th June)
>> Cheers
>> Rob.
>> 
>> Rob Searle
>> ISIS Design Division - Electrical 
>> R2 1.20,
>> STFC, Rutherford Appleton Laboratory
>> Chilton, Didcot, Oxfordshire
>> OX11 0QX
>> 
>> Tel:    01235 446614
>> Mob:    07917 556370
>> Fax:    01235 446311
>> Email:  rob.searle@stfc.ac.uk
>>
