### ISSUE TITLE
MUON FRONT END: Danfysik 8000 series EPICS

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#980]
As a Muon Front End User I will want to control power supplies from the Danfysik 8000 series within EPICS

== Acceptance Criteria ==
1. Danfysik 8000 series power supply units can be controlled from EPICS

== Notes ==
1. The list of commands required for this control needs to be confirmed, but should be limited to read/write of the standard PSU values - current and voltage - This is available in the comments
1. There is a stream based IOC that already exists, and it should be possible to acquire this and alter if necessary
1. If there is no existing driver, or it cannot be sourced easily, this is just a stream device driver, so straightforward
1. The IOC will need to be incorporated into our setup - main IOC in support listing, IOC to run in IOCs, appropriate repositories created
1. Four IOCs should be added to the list so that it is possible to perform the setup with an IOC available for each Muon instrument (HiFi, MuSR and EMU) and one for the front end control. Each IOC could be talking to multiple power supplies.
1. We expect that #980, #982 & #983 will take 2 points for all 3 tickets.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 982.  Created by kvlb23 on 2015-11-12T12:00:55, last modified: 2016-01-28T11:50:38_

**Comment by kjwoodsISIS** [comment]
_Trac comment by kvlb23 on 2016-01-22 15:12:24:_

Assuming a match to the LabVIEW as the requirements then the following commands will be needed:

||=Command=||=Desc=||=Notes=||
||WA nnnnnn||Set Set Point Current||Padded with 0 to be 6 digits||
||RS||Reset Interlocks||||
||PO +||Set Polarity Positive||This and P- was done via a binary record||
||PO -||Set Polarity Negative||This and P+ was done via a binary record||
||REM||Set Remote Mode||REM, LOC, UNLOCK and LOCK are all in one VI, so could be done via a mbbi record||
||LOC||Set Local Mode||REM, LOC, UNLOCK and LOCK are all in one VI, so could be done via a mbbi record||
||UNLOCK||Unlock the front panel||REM, LOC, UNLOCK and LOCK are all in one VI, so could be done via a mbbi record||
||LOCK||Lock the front panel||REM, LOC, UNLOCK and LOCK are all in one VI, so could be done via a mbbi record||
||F||Turn the Main Power Off||||
||N||Turn the Main Power On||This is preceded by setting the Set Point Current to 0||
||S1||Read the status||There is quite a bit of post processing to decode the response into a cluster of Booleans labelled appropriately for each status bit||
||AD 2||Read Output Voltage||Result is divided by 100 before being used||
||AD 8||Read Optional Iout(16 bit)||Result is divided by 100000 before being used||

During startup the commands UNLOCK and REM are sent to the PSU
During shutdown the commands UNLOCK and LOC are sent to the PSU
Note that the set points are converted and calibrated between different units and for the behaviour of the magnet.

**Comment by IsabellaRey** [comment]
This ticket was tested and merged. Outstanding issues after testing have been captured as part of #1170
