### ISSUE TITLE
IBEX: GUI: Open an OPI outside of a synoptic

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#985]
As a support person (or instrument scientist) I want to be able to open an OPI without having to add it to a synoptic.

##### Acceptance Criteria
1. Create a design for how this would work.
2. Define how the BlockServer needs to change to support the design.

##### Eventual Desired Outcome
1. It is possible to open an OPI without having first created a synoptic with it.

##### Notes
1. OPIs often require macros to be set, some interface will be required for entry of this information prior to display
2. We need to decide where to display it

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Opening-an-OPI-Outside-of-a-Synoptic

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 987.  Created by kvlb23 on 2015-11-12T16:01:30, last modified: 2016-01-28T11:55:53_

**Comment by IsabellaRey** [comment]
This resulted in a hackathon to work both on the blockserver and the GUI.

There are a number of stories to finish up the work:
#1121
#1122 
#1123 
#1124 
#1125 
#1126 
#1127 
#1129
